### ISSUE TITLE
优化内存占用

### ISSUE THREAD

**Issue by aptx17** [XTLS/Xray-core#10]
哥，后面会有xctl吗？发现内置json一启动就占用将近80M内存，openwrt有点吃不消。
![20201126230406892](https://user-images.githubusercontent.com/41042297/100367143-bd7a1e00-303c-11eb-8f54-e710cf57b581.jpg)
1.0
----------
![20201126225820157](https://user-images.githubusercontent.com/41042297/100367222-dda9dd00-303c-11eb-8e50-540fb80e74d8.jpg)
4.32.1

**Comment by rprx** [comment]
理论上不会这样，v2ray-core v4.32.1 也是不依赖 ctl，Xray-core v1.0.0 进一步吃了 ctl，多试几次看看。

**Comment by aptx17** [comment]
> 理论上不会这样，v2ray-core v4.32.1 也是不依赖 ctl，Xray-core v1.0.0 进一步吃了 ctl，多试几次看看。

哦~忘了说了，我的4.32.1是自编译有ctl的，如果用官方的也是会将近80M 。
VPS服务器x86平台，XEN \ KVM，debian9、10刚试了是正常的15-20M启动内存范围。
不知道是不是我路由器armv8 cpu架构的问题（内核5.4）。

**Comment by rprx** [comment]
等等看有无更多反馈，你可以先尝试编译精简版的 Xray

但若只在一个机器上有差异，就比较奇怪了

**Comment by shenlijun** [comment]
家里搞一个all in one，上面做网关，你就不会在意这些细节了

**Comment by rprx** [comment]
https://github.com/XTLS/Xray-core/issues/38

看来这的确是个值得关注的问题

**Comment by rprx** [comment]
https://github.com/2dust/v2rayNG/issues

NG 一些 issue 可能是这个原因，似乎只有 arm64 存在这种问题

之后会研究对应的解决方案

**Comment by aptx17** [comment]
> #38
> 
> 看来这的确是个值得关注的问题

嗯嗯，他说的那个是上图虚拟内存VIRT吧？就是v2ray向系统申请的虚拟内存（如果小机自身内存过小，虚拟内存没设置，就会启动不起来），虽然不会全用到，不过4800M将近4G的申请，感觉是不是有点大？我记得没爆出aead重放问题之前的v2ray版本，申请的虚拟内存好像是780M左右（不过这又是另个问题了）。 我现在的是RES实时内存，一启动就80M。可能确实是arm64的问题。下图帮你测了4.31.3，有ctl是正常的。另台arm64机器过几天到了在试试看吧。
![20201206015124](https://user-images.githubusercontent.com/41042297/101260068-0f6f2200-3768-11eb-940c-c1ae0b3bb44e.png)

**Comment by rprx** [comment]
https://github.com/XTLS/Xray-core/issues/68#issuecomment-745275733

**Comment by rprx** [comment]
https://github.com/XTLS/Xray-core/releases/tag/v1.1.4
