### ISSUE TITLE
路由支持按照ip源地址国别设定规则

### ISSUE THREAD

**Issue by LearZhou** [XTLS/Xray-core#100]
目前xray继承了v2ray的路由设定规则，"ip"字段可按国别分流目的地址，但源地址"source"字段仅支持固定ip或者cidr格式的地址段。

若能让xray按照源地址的国别设定路由规则，将拓展路由规则的灵活性。

**Comment by rprx** [comment]
有空时加上

**Comment by badO1a5A90** [comment]
https://github.com/XTLS/Xray-core/blob/40271c09a0f6f9f5d4ff1b07baadff2d205b9459/app/router/config.go#L115

是有这个支持的, 即可以使用类似下面写法分流
```
      {
        "type": "field",
        "source": [
          "geoip:cn"
        ],
        "outboundTag": "out-1"
      },
```

**Comment by badO1a5A90** [comment]
文档已修改
