### ISSUE TITLE
1.5.4版本修复的 Domain socket 配置访问权限，似乎没有解决

### ISSUE THREAD

**Issue by chika0801** [XTLS/Xray-core#1001]
我是开的 VLESS grpc TLS
用nginx前置，xray后置，xray是用官方脚本标准安装（未带root参数）

nginx配置里
用user nginx（默认值是nginx）连不通。
换成user nobody nogroup，就通了。

nginx配置是
<pre>
user nginx;
worker_processes auto;

error_log /var/log/nginx/error.log notice;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '[$time_local] $remote_addr:$remote_port "$request" "$http_referer" "$http_user_agent"';
    access_log /var/log/nginx/access.log main;

    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl http2;

        ssl_certificate /etc/ssl/private/fullchain.cer;
        ssl_certificate_key /etc/ssl/private/private.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers TLS13_AES_128_GCM_SHA256:TLS13_AES_256_GCM_SHA384:TLS13_CHACHA20_POLY1305_SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305;
        ssl_prefer_server_ciphers on;

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

        location /lovelive {
            if ($request_method != "POST") {
                return 404;
            }

            client_body_buffer_size 1m;
            client_body_timeout 1h;
            client_max_body_size 0;
            grpc_intercept_errors on;
            grpc_read_timeout 1h;
            grpc_send_timeout 1h;
            grpc_set_header X-Real-IP $remote_addr;
            grpc_socket_keepalive on;

            grpc_pass grpc://unix:/dev/shm/grpc.socket;
        }

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
}
</pre>

Xray配置是
<pre>
{
    "log": {
        "access": "",
        "error": "/var/log/xray/error.log",
        "loglevel": "warning"
    },
    "dns": {
        "servers": [
            "1.1.1.1"
        ],
        "queryStrategy": "UseIPv4"
    },
    "routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "type": "field",
                "ip": [
                    "1.1.1.1"
                ],
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "domain": [
                    "geosite:category-ads-all",
                    "geosite:cn"
                ],
                "outboundTag": "block"
            },
            {
                "type": "field",
                "ip": [
                    "geoip:cn",
                    "geoip:private"
                ],
                "outboundTag": "block"
            }
        ]
    },
    "inbounds": [
        {
            "listen": "/dev/shm/grpc.socket",
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "ee48f7be-6ae9-5654-9b61-8466aa8e16bc"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "grpc",
                "grpcSettings": {
                    "serviceName": "lovelive"
                }
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "settings": {
                "domainStrategy": "UseIPv4"
            },
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "settings": {
                "response": {
                    "type": "http"
                }
            },
            "tag": "block"
        }
    ]
}
</pre>

**Comment by chika0801** [comment]
@yuhan6665 thanks

**Comment by yuhan6665** [comment]
解决的方法是增加了 chmod 配置项：
"listen": "/dev/shm/grpc.socket,0666",

**Comment by chika0801** [comment]
感谢大佬 2333
