### ISSUE TITLE
双重加密的疑问

### ISSUE THREAD

**Issue by wangyifan349** [XTLS/Xray-core#1002]
请问一下,xray-core在使用双重加密的是时候,vmess(aes-128-gcm)+ws+tls+cloudflare代理，这样的话,cloudflare是否能看到我访问了网站访问记录.
求大佬解答下，谢谢大佬们

**Comment by yuhan6665** [comment]
用 vmess 加密时 cdn 不能看到任何内容 用 trojan 或者 vless 可能可以看到

**Comment by Ra2-IFV** [comment]
不会
而且CF底子很硬，不会把log交给CPC的

**Comment by yuhan6665** [comment]
Closing
