### ISSUE TITLE
在CENTOS 下 切换Xray 节点就失效了

### ISSUE THREAD

**Issue by loofeal** [XTLS/Xray-core#1003]
在CENTOS 下 切换Xray 节点就失效了
1.4.2 可以用 单切换其他任何版本的核心就会节点失效。不知道有解决方法吗

**Comment by yuhan6665** [comment]
盲猜是 alterid 问题 ;)

**Comment by loofeal** [comment]
> 



> 盲猜是 alterid 问题 ;)

怎么解决？

**Comment by loofeal** [comment]
> 盲猜是 alterid 问题 ;)

64改0可以了，感谢大佬！
