### ISSUE TITLE
安全中心报有威胁

### ISSUE THREAD

**Issue by kaiby** [XTLS/Xray-core#1008]
![image](https://user-images.githubusercontent.com/3312664/161244158-f8b2474f-ecba-4046-8c1e-1106abaa1808.png)

**Comment by yuhan6665** [comment]
I've seen no thread from the source. Consider whitelist xray.exe.

**Comment by Ra2-IFV** [comment]
检查下是不是从github下的，再校验下，没问题的话就加白名单吧
（微软和CPC有一腿的）

**Comment by doudouhn6** [comment]
微软和CPC有一腿，那么xray和谁有一腿呢？

**Comment by yuhan6665** [comment]
先关了

**Comment by Ra2-IFV** [comment]
开源的，能和谁有关系...
放心用吧，都用爱发电的

doudouhn6 ***@***.***> 於 2022年4月7日 週四 下午10:57寫道：
