### ISSUE TITLE
XTLS+VLESS入站希望支持proxy，以获取正确的源地址

### ISSUE THREAD

**Issue by LearZhou** [XTLS/Xray-core#101]
目前XTLS+VLESS的用例，一般假设是在TCP 443监听端口的最前端。对于xray运行在后端，比如前端用HaProxy分流的应用场景，xtls获取的源地址是HaProxy所在的本地地址，并非原始源地址。

希望能够增加XTLS+VLESS入站proxy支持，以便能利用HaProxy的send-proxy或者send-proxy v2的功能，获取真实的源地址。

**Comment by badO1a5A90** [comment]
proxy protocol 已经是支持的，包括TCP ws 等传输模式的inbound接收，以及回落时的发送。

具体配置值是 acceptProxyProtocol

具体查看这里https://xtls.github.io/config/transports/tcp/

**Comment by LearZhou** [comment]
"streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
          //"acceptProxyProtocol": true,
          "alpn": [
            "http/1.1"
          ],
          "minVersion": "1.2",
我试过这个地方，但不起作用。你说的跟我指的，可能不是一回事。

**Comment by badO1a5A90** [comment]
你写错地方了，看我发你的文档地址

**Comment by LearZhou** [comment]
XTLS + VLESS配置example里面，没找到tcpSettings配置的地方呀。

**Comment by badO1a5A90** [comment]
自己加上去呀

"streamSettings": {
                "network": "tcp",
                "security": "xtls",
                 "tcpSettings": {
                   "acceptProxyProtocol": true
                },
                "xtlsSettings": {
                    "alpn": [
                        "http/1.1"
                    ],
                    "minVersion": "1.2",

**Comment by LearZhou** [comment]
多谢指点。经过一番折腾之后，终于搞定了！

**Comment by aorosora** [comment]
原来还得单独加一个 `tcpSettings` ，我也加在了 `xtlsSettings` 里面，折腾一个多小时。

**Comment by rprx** [comment]
不过目前服务端 XTLS 前的 PROXY protocol 会使服务端的 ReadV/Splice 失效。。。
