### ISSUE TITLE
XTLS已经被检测识别了吗？标记为不安全？

### ISSUE THREAD

**Issue by qwerttvv** [XTLS/Xray-core#1014]
![webwxgetmsgimg](https://user-images.githubusercontent.com/56712217/161489227-5f7e3889-8a4c-44ff-b37e-8e7ea8be6d7c.jpg)

安卓手机客户端SagerNet提示的

https://github.com/SagerNet/SagerNet

**Comment by waloyn** [comment]
SagerNet的内核是v2ray，和xray的理念不合，v2ray在4.33的时候就移除XTLS支持了。

**Comment by qwerttvv** [comment]
> SagerNet的内核是v2ray，和xray的理念不合，v2ray在4.33的时候就移除XTLS支持了。
SagerNet可以用xtls的，流控也可以选splice

**Comment by waloyn** [comment]
> > SagerNet的内核是v2ray，和xray的理念不合，v2ray在4.33的时候就移除XTLS支持了。
> 
> SagerNet可以用xtls的，流控也可以选splice

是可以用，但是会提示。SagerNet的v2ray核心是fork的v2fly，不是原版。

**Comment by qwerttvv** [comment]
> > > SagerNet的内核是v2ray，和xray的理念不合，v2ray在4.33的时候就移除XTLS支持了。
> > 
> > 
> > SagerNet可以用xtls的，流控也可以选splice
> 
> 是可以用，但是会提示。SagerNet的v2ray核心是fork的v2fly，不是原版。

这东西除了技术层面，似乎还有其他恩怨的感觉啊

**Comment by chika0801** [comment]
https://github.com/XTLS/Go/issues/17

https://github.com/XTLS/Go/issues/16

若使用VLESS tcp xtls，xray前置+回落的配置，不放心建议在服务器端配置加
https://github.com/chika0801/Xray-examples/blob/bdbcff1e5b7a5f8db713848d190d326a6188a9ea/VLESS-TCP-XTLS/config_server.json#L71

另外提醒下请注意
https://github.com/XTLS/Xray-core/discussions/593#discussioncomment-845165

不使用VPS访问CN是一个好习惯。如以后遇端口443被封后，建议自查。

**Comment by doudouhn6** [comment]
> > > > SagerNet的内核是v2ray，和xray的理念不合，v2ray在4.33的时候就移除XTLS支持了。
> > > 
> > > 
> > > SagerNet可以用xtls的，流控也可以选splice
> > 
> > 
> > 是可以用，但是会提示。SagerNet的v2ray核心是fork的v2fly，不是原版。
> 
> 这东西除了技术层面，似乎还有其他恩怨的感觉啊

那当然，林徽因还鄙视张爱玲呢！还不是留下了终身遗憾

**Comment by CarbonPool** [comment]
> [XTLS/Go#17](https://github.com/XTLS/Go/issues/17)
> 
> [XTLS/Go#16](https://github.com/XTLS/Go/issues/16)
> 
> 若使用VLESS tcp xtls，xray前置+回落的配置，不放心建议在服务器端配置加 https://github.com/chika0801/Xray-examples/blob/bdbcff1e5b7a5f8db713848d190d326a6188a9ea/VLESS-TCP-XTLS/config_server.json#L71
> 
> 另外提醒下请注意 [#593 (comment)](https://github.com/XTLS/Xray-core/discussions/593#discussioncomment-845165)
> 
> 不使用VPS访问CN是一个好习惯。如以后遇端口443被封后，建议自查。

按配置文件加强了下路由黑名单，一些网站访问提示ERR_SSL_PROTOCOL_ERROR，比如acwifi

**Comment by gcphym** [comment]
> [XTLS/Go#17](https://github.com/XTLS/Go/issues/17)
> 
> [XTLS/Go#16](https://github.com/XTLS/Go/issues/16)
> 
> 若使用VLESS tcp xtls，xray前置+回落的配置，不放心建议在服务器端配置加 https://github.com/chika0801/Xray-examples/blob/bdbcff1e5b7a5f8db713848d190d326a6188a9ea/VLESS-TCP-XTLS/config_server.json#L71
> 
> 另外提醒下请注意 [#593 (comment)](https://github.com/XTLS/Xray-core/discussions/593#discussioncomment-845165)
> 
> 不使用VPS访问CN是一个好习惯。如以后遇端口443被封后，建议自查。

按照https://github.com/XTLS/Go/issues/17 里 https://github.com/hahahrfool/xtls-/blob/main/README.md 的说法，开启"minVersion": "1.3"好像并没有解决问题啊

**Comment by chika0801** [comment]
> > [XTLS/Go#17](https://github.com/XTLS/Go/issues/17)
> > [XTLS/Go#16](https://github.com/XTLS/Go/issues/16)
> > 若使用VLESS tcp xtls，xray前置+回落的配置，不放心建议在服务器端配置加 https://github.com/chika0801/Xray-examples/blob/bdbcff1e5b7a5f8db713848d190d326a6188a9ea/VLESS-TCP-XTLS/config_server.json#L71
> > 另外提醒下请注意 [#593 (comment)](https://github.com/XTLS/Xray-core/discussions/593#discussioncomment-845165)
> > 不使用VPS访问CN是一个好习惯。如以后遇端口443被封后，建议自查。
> 
> 按照[XTLS/Go#17](https://github.com/XTLS/Go/issues/17) 里 https://github.com/hahahrfool/xtls-/blob/main/README.md 的说法，开启"minVersion": "1.3"好像并没有解决问题啊

它提的内容要攻击要有UUID你自用的UUID只有你自己知道。所以不想加"minVersion": "1.3"也成，强迫症就加。还是那句话做好VPS禁止访问CN IP哪有什么端口被封的事。

**Comment by xyli09** [comment]
xtls 443 被ban

**Comment by chika0801** [comment]
> xtls 443 被ban

建议你不要太爱惜端口和IP，现在换个端口继续用，在VPS配置文件上加上禁止访问CN IP。

如果以后443解了换不换回来都可以随便你。

**Comment by bash99** [comment]
> 

我出现了 play商店能浏览不能下载 的问题
加上一行
{"type": "field", "domain": ["googleapis.cn"],"outboundTag": "direct"},
绕过去了
