### ISSUE TITLE
Bug report 从1.4.5往后的版本里日志里面不显示入站的标签了....

### ISSUE THREAD

**Issue by wutongskype** [XTLS/Xray-core#1017]
Bug report 从1.4.5往后的版本里日志里面不显示入站的标签了....

**1.4.5** 
2022/04/06 03:42:54 tcp:127.0.0.1:42136 accepted tcp:api.github.com:443 [gRPC_34567_direct >> direct]
2022/04/06 03:42:54 tcp:127.0.0.1:42136 accepted tcp:www.youtube.com:443 [gRPC_34567_direct >> direct]
2022/04/06 03:42:55 tcp:127.0.0.1:42136 accepted tcp:i.ytimg.com:443 [gRPC_34567_direct >> direct]
2022/04/06 03:42:57 tcp:127.0.0.1:42136 accepted tcp:yt3.ggpht.com:443 [gRPC_34567_direct >> direct]
2022/04/06 03:42:58 tcp:127.0.0.1:42136 accepted tcp:rr3---sn-i3belnl7.googlevideo.com:443 [gRPC_34567_direct >> direct]
2022/04/06 03:42:58 tcp:127.0.0.1:42136 accepted tcp:jnn-pa.googleapis.com:443 [gRPC_34567_direct >> direct]
2022/04/06 03:42:59 tcp:127.0.0.1:42136 accepted tcp:youtube.com:443 [gRPC_34567_direct >> direct]

**1.5.4 成这样了.... [gRPC_34567_direct >> direct] 这个只显示出站了.....**

2022/04/06 03:43:32 127.0.0.1:42356 accepted tcp:mtalk.google.com:5228 [direct]
2022/04/06 03:43:32 tcp:127.0.0.1:42366 accepted tcp:i.ytimg.com:443 [direct]
2022/04/06 03:43:32 tcp:127.0.0.1:42366 accepted tcp:i.ytimg.com:443 [direct]
2022/04/06 03:43:32 tcp:127.0.0.1:42366 accepted tcp:i.ytimg.com:443 [direct]
2022/04/06 03:43:32 127.0.0.1:42356 accepted tcp:pushstream.tradingview.com:443 [direct]
2022/04/06 03:43:32 127.0.0.1:42356 accepted tcp:pushstream.tradingview.com:443 [direct]
2022/04/06 03:43:32 127.0.0.1:42356 accepted tcp:charts-storage-notifications.tradingview.com:443 [direct]
2022/04/06 03:43:34 tcp:127.0.0.1:42366 accepted tcp:www.youtube.com:443 [direct]
2022/04/06 03:43:35 127.0.0.1:42356 accepted tcp:clients4.google.com:443 [direct]
2022/04/06 03:43:36 tcp:127.0.0.1:42366 accepted tcp:lp-push-server-47.lastpass.com:443 [direct]
2022/04/06 03:43:36 127.0.0.1:42356 accepted tcp:prodata.tradingview.com:443 [direct]
2022/04/06 03:43:36 127.0.0.1:42356 accepted tcp:charts-storage.tradingview.com:443 [direct]
2022/04/06 03:43:37 tcp:127.0.0.1:42366 accepted tcp:yt3.ggpht.com:443 [direct]
2022/04/06 03:43:37 127.0.0.1:42356 accepted tcp:telemetry.tradingview.com:443 [direct]
2022/04/06 03:43:37 tcp:127.0.0.1:42366 accepted tcp:jnn-pa.googleapis.com:443 [direct]

**Comment by yuhan6665** [comment]
@wutongskype 感谢报告这个问题！在 https://github.com/XTLS/Xray-core/pull/1028 修复了
