### ISSUE TITLE
DNS分流逻辑的问题

### ISSUE THREAD

**Issue by Bearljj** [XTLS/Xray-core#1020]
我的DNS模块配置如下：
"dns": {
    "servers": [     
      {
        "address": "223.5.5.5",
        "domains": ["geosite:cn"],
        "expectIPs": ["geoip:cn"]
      },
      {
        "address": "114.114.114.114",
        "domains": ["geosite:cn"]
      },
      {
        "address": "1.1.1.1",
        "domains": ["geolocation-!cn"]
      },
      "localhost"
    ]
  },
按说google、youtube等都应该走到1.1.1.1去，但是log里
2022/04/06 15:54:51 [Info] [2459844033] proxy/socks: TCP Connect request to tcp:www.google.com.hk:443
2022/04/06 15:54:51 [Info] [2459844033] app/dispatcher: sniffed domain: www.google.com.hk
2022/04/06 15:54:51 [Debug] app/dns: domain www.google.com.hk will use DNS in order: [UDP:223.5.5.5:53 UDP:114.114.114.114:53 UDP:1.1.1.1:53 localhost]
2022/04/06 15:54:51 [Debug] app/dns: UDP:223.5.5.5:53 querying DNS for: www.google.com.hk.
2022/04/06 15:54:51 [Info] app/dns: UDP:223.5.5.5:53 got answer: www.google.com.hk. TypeA -> [31.13.70.9] 11.907143ms
2022/04/06 15:54:51 [Debug] app/dns: UDP:223.5.5.5:53 updating IP records for domain:www.google.com.hk.
2022/04/06 15:54:51 [Info] app/dns: UDP:223.5.5.5:53 got answer: www.google.com.hk. TypeAAAA -> [[2001::caa0:8234]] 12.086858ms
2022/04/06 15:54:51 [Debug] app/dns: UDP:223.5.5.5:53 updating IP records for domain:www.google.com.hk.
2022/04/06 15:54:51 [Info] app/dns: failed to lookup ip for domain www.google.com.hk at server UDP:223.5.5.5:53 > expectIPs not match
2022/04/06 15:54:51 [Debug] app/dns: UDP:114.114.114.114:53 querying DNS for: www.google.com.hk.
2022/04/06 15:54:51 [Info] app/dns: UDP:114.114.114.114:53 got answer: www.google.com.hk. TypeA -> [108.160.169.174] 26.971937ms
2022/04/06 15:54:51 [Debug] app/dns: UDP:114.114.114.114:53 updating IP records for domain:www.google.com.hk.
2022/04/06 15:54:51 [Info] app/dns: UDP:114.114.114.114:53 got answer: www.google.com.hk. TypeAAAA -> [[2001::6ca0:a9ba]] 26.9904ms
2022/04/06 15:54:51 [Debug] app/dns: UDP:114.114.114.114:53 updating IP records for domain:www.google.com.hk.
2022/04/06 15:54:51 [Info] [2459844033] app/dispatcher: taking detour [proxy] for [tcp:www.google.com.hk:443]
2022/04/06 15:54:51 [Info] [2459844033] proxy/vless/outbound: tunneling request to tcp:www.google.com.hk:443 via 127.0.0.1:2022
显然没有按照预期逻辑执行，我使用的是(https://github.com/Loyalsoldier/v2ray-rules-dat)中的规则文件

**Comment by yuhan6665** [comment]
I think this is because geosite:cn contains [www.google.com.hk](http://www.google.com.hk/)

**Comment by yuhan6665** [comment]
Closing
