### ISSUE TITLE
[Feature request] Add support for shadowsocks-2022 ciphers

### ISSUE THREAD

**Issue by Shikopat** [XTLS/Xray-core#1029]
Please Add support for shadowsocks-2022 ciphers:

2022-BLAKE3-AES-128-GCM
2022-BLAKE3-AES-256-GCM
2022-BLAKE3-CHACHA20-IETF-POLY1305

Regards

**Comment by 3mc4** [comment]
Still waiting for [v1.5.6](https://github.com/XTLS/Xray-core/releases/tag/v1.5.6) to be released.
