### ISSUE TITLE
关于反向代理和回落同时使用的问题

### ISSUE THREAD

**Issue by shenlijun** [XTLS/Xray-core#103]
想法是这样，家里的机器上用nginx/apache做web，假如就启用80端口
然后用反向代理来访问，服务器用8080端口

服务器那边的velss+tcp+xtls希望直接可以回落到8080，感觉上应该可以
但是现在直接回落访问不了，但是如果回落到服务器端的nginx，nginx再反向代理到8080就可以访问
是设置的问题？还是目前的机制不支持？

目前的设置非要绕一下不必要的nginx，看着难受

**Comment by rprx** [comment]
需要日志

**Comment by eMeab** [comment]
请贴上配置 以及 日志。

**Comment by shenlijun** [comment]
服务端配置

{
    "reverse": {
        "portals": [
            {
                "tag": "portal",
                "domain": "www.xxx.com"
            }
        ]
    },
    "inbounds": [
        {
            "tag": "tunnel",
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "email": "xxx",
                        "id": "xxx",
                        "level": 1,
                        "flow": "xtls-rprx-direct"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": "8800",
                        "xver": 1
                    },
                    {
                        "alpn": "h2",
                        "dest": "/8800",
                        "xver": 1
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "alpn": [
                        "h2",
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "xxx",
                            "keyFile": "xxx"
                        }
                    ]
                }
            }
        },
        {
            "tag": "webServer",
            "port": 8800,
            "protocol": "dokodemo-door",
            "settings": {
                "address": "192.168.232.6",
                "port": 80,
                "network": "tcp"
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "settings": {}
        },
        {
            "protocol": "blackhole",
            "settings": {},
            "tag": "blocked"
        }
    ],
    "routing": {
        "domainStrategy": "AsIs",
        "rules": [
            {
                "type": "field",
                "outboundTag": "blocked",
                "protocol": [
                    "bittorrent"
                ]
            },
            {
                "type": "field",
                "outboundTag": "portal",
                "inboundTag": [
                    "webServer"
                ]
            },
            {
                "type": "field",
                "outboundTag": "portal",
                "inboundTag": [
                    "tunnel"
                ],
                "domain": [
                    "full:xxx.com"
                ]
            }
        ]
    }
}

**Comment by shenlijun** [comment]
客户端配置

`{
    "reverse": {
        "bridges": [
            {
                "tag": "bridge",
                "domain": "www.xxx.com"
            }
        ]
    },
    "dns": {
        "servers": [
            "8.8.8.8",
            "1.1.1.1",
            {
                "address": "223.5.5.5",
                "port": 53,
                "domains": [
                    "geosite:cn",
                    "www.vps.com",
                    "ntp.org"
                ]
            },
            {
                "address": "114.114.114.114",
                "port": 53,
                "domains": [
                    "geosite:cn",
                    "www.vps.com",
                    "ntp.org"
                ]
            }
        ]
    },
    "routing": {
        "domainStrategy": "IPOnDemand",
        "rules": [
            {
                "type": "field",
                "inboundTag": [
                    "bridge"
                ],
                "domain": [
                    "full:www.xxx.com"
                ],
                "outboundTag": "tunnel"
            },
            {
                "type": "field",
                "inboundTag": [
                    "bridge"
                ],
                "outboundTag": "bridge_out"
            },
            {
                "type": "field",
                "port": "53",
                "network": "udp",
                "inboundTag": [
                    "transparent"
                ],
                "outboundTag": "dns_out"
            },
            {
                "type": "field",
                "port": "123",
                "network": "udp",
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "ip": [
                    "223.5.5.5",
                    "114.114.114.114"
                ],
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "ip": [
                    "8.8.8.8",
                    "1.1.1.1"
                ],
                "outboundTag": "proxy"
            },
            {
                "type": "field",
                "domain": [
                    "geosite:category-ads-all"
                ],
                "outboundTag": "block"
            },
            {
                "type": "field",
                "protocol": [
                    "bittorrent"
                ],
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "ip": [
                    "geoip:private",
                    "geoip:cn",
                    "xxx.xxx.xxx.xxx"
                ],
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "domain": [
                    "geosite:cn",
                    "www.vps.com",
                    "ntp.org"
                ],
                "outboundTag": "direct"
            }
        ]
    },
    "inbounds": [
        {
            "port": 1080,
            "protocol": "socks",
            "settings": {
                "auth": "noauth",
                "udp": true
            },
            "streamSettings": {
                "sockopt": {}
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            }
        },
        {
            "port": 1081,
            "protocol": "dokodemo-door",
            "settings": {
                "followRedirect": true,
                "network": "tcp,udp"
            },
            "streamSettings": {
                "sockopt": {
                    "tproxy": "tproxy"
                }
            },
            "tag": "transparent",
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "xxx.xxx.xxx.xxx",
                        "port": 443,
                        "users": [
                            {
                                "id": "xxx",
                                "flow": "xtls-rprx-splice",
                                "encryption": "none",
                                "level": 1
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "serverName": "www.vps.com"
                },
                "sockopt": {
                    "mark": 255
                }
            },
            "tag": "tunnel",
            "mux": {
                "enabled": false
            }
        },
        {
            "protocol": "freedom",
            "streamSettings": {
                "sockopt": {
                    "mark": 255
                }
            },
            "tag": "bridge_out"
        },
        {
            "protocol": "freedom",
            "settings": {
                "domainStrategy": "UseIP"
            },
            "streamSettings": {
                "sockopt": {
                    "mark": 255
                }
            },
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "settings": {},
            "streamSettings": {
                "sockopt": {
                    "mark": 255
                }
            },
            "tag": "block"
        },
        {
            "protocol": "dns",
            "settings": {},
            "streamSettings": {
                "sockopt": {
                    "mark": 255
                }
            },
            "tag": "dns_out"
        }
    ]
}
`

**Comment by shenlijun** [comment]
日志不报错
服务端的access.log是这样
2020/12/24 19:53:31 127.0.0.1:33344 accepted tcp:192.168.232.6:80 [portal]

客户端是这样
2020/12/25 03:52:32   accepted tcp:192.168.232.6:80 [bridge_out]

浏览器报错是

无法访问此网站
网址为 https://www.vps.com/ 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_HTTP2_PROTOCOL_ERROR

**Comment by shenlijun** [comment]
难道是需要我的apache2开ssl？

**Comment by shenlijun** [comment]
把fallbacks换成socks到nginx，nginx再反代到8800就可以用了
直接落到8800就不行

**Comment by jimmy-1972** [comment]
究竟是8080还是8800？

**Comment by shenlijun** [comment]
> 究竟是8080还是8800？

这个根本不重要

**Comment by shenlijun** [comment]
还有用了Gitea，也是同样的问题

本地用3000，反代的服务器用8300，用路径/git回落到8300好像报的错误是一样的

用socks回落到nginx，然后nginx将路径/git/代理到http://127.0.0.1:8300/就可以

web也一样用socks回落到nginx，然后nginx将路径/代理到http://127.0.0.1:8800就可以

**Comment by shenlijun** [comment]
反代的管道因该是没问题的，我反代的web，ssh，ftp，gitea之类的都可以正常用
只是web和git需要浏览器访问所以需要回落，现在中间夹着一个nginx还可以用

**Comment by Rakau** [comment]
上上nginx的配置

**Comment by eMeab** [comment]
> 反代的管道因该是没问题的，我反代的web，ssh，ftp，gitea之类的都可以正常用
> 只是web和git需要浏览器访问所以需要回落，现在中间夹着一个nginx还可以用

h2 的回落需要 回落到h2c的端口

**Comment by shenlijun** [comment]
> > 反代的管道因该是没问题的，我反代的web，ssh，ftp，gitea之类的都可以正常用
> > 只是web和git需要浏览器访问所以需要回落，现在中间夹着一个nginx还可以用
> 
> h2 的回落需要 回落到h2c的端口

家里的apache开了h2也不行
还有一个问题是Gitea不知道有没有配置这些东西地方

**Comment by eMeab** [comment]
> > > 反代的管道因该是没问题的，我反代的web，ssh，ftp，gitea之类的都可以正常用
> > > 只是web和git需要浏览器访问所以需要回落，现在中间夹着一个nginx还可以用
> > 
> > 
> > h2 的回落需要 回落到h2c的端口
> 
> 家里的apache开了h2也不行
> 还有一个问题是Gitea不知道有没有配置这些东西地方

需要回到的是h2c 不是h2 gitea没h2c

**Comment by eMeab** [comment]
> > > 反代的管道因该是没问题的，我反代的web，ssh，ftp，gitea之类的都可以正常用
> > > 只是web和git需要浏览器访问所以需要回落，现在中间夹着一个nginx还可以用
> > 
> > 
> > h2 的回落需要 回落到h2c的端口
> 
> 家里的apache开了h2也不行
> 还有一个问题是Gitea不知道有没有配置这些东西地方

alpn 只填写 ["http/1.1"] 
把h2 回落的全删掉 应该就能访问 不过代价是网页没h2

**Comment by shenlijun** [comment]
> > > > 反代的管道因该是没问题的，我反代的web，ssh，ftp，gitea之类的都可以正常用
> > > > 只是web和git需要浏览器访问所以需要回落，现在中间夹着一个nginx还可以用
> > > 
> > > 
> > > h2 的回落需要 回落到h2c的端口
> > 
> > 
> > 家里的apache开了h2也不行
> > 还有一个问题是Gitea不知道有没有配置这些东西地方
> 
> 需要回到的是h2c 不是h2 gitea没h2c

刚才确定了下，apache注释的地方也要有h2c



> > > > 反代的管道因该是没问题的，我反代的web，ssh，ftp，gitea之类的都可以正常用
> > > > 只是web和git需要浏览器访问所以需要回落，现在中间夹着一个nginx还可以用
> > > 
> > > 
> > > h2 的回落需要 回落到h2c的端口
> > 
> > 
> > 家里的apache开了h2也不行
> > 还有一个问题是Gitea不知道有没有配置这些东西地方
> 
> alpn 只填写 ["http/1.1"]
> 把h2 回落的全删掉 应该就能访问 不过代价是网页没h2

我试试这个，如果要兼顾gitea的话不要h2也罢

**Comment by shenlijun** [comment]
> > > > 反代的管道因该是没问题的，我反代的web，ssh，ftp，gitea之类的都可以正常用
> > > > 只是web和git需要浏览器访问所以需要回落，现在中间夹着一个nginx还可以用
> > > 
> > > 
> > > h2 的回落需要 回落到h2c的端口
> > 
> > 
> > 家里的apache开了h2也不行
> > 还有一个问题是Gitea不知道有没有配置这些东西地方
> 
> alpn 只填写 ["http/1.1"]
> 把h2 回落的全删掉 应该就能访问 不过代价是网页没h2

Bad Request
Your browser sent a request that this server could not understand.

**Comment by eMeab** [comment]
> Bad Request
> Your browser sent a request that this server could not understand.

ctrl + F5 刷新网页试下

**Comment by shenlijun** [comment]
> > Bad Request
> > Your browser sent a request that this server could not understand.
> 
> ctrl + F5 刷新网页试下

不行，web和gitea都是这样的错误

**Comment by eMeab** [comment]
> > > Bad Request
> > > Your browser sent a request that this server could not understand.
> > 
> > 
> > ctrl + F5 刷新网页试下
> 
> 不行，web和gitea都是这样的错误

xver:0

**Comment by shenlijun** [comment]
> > > > Bad Request
> > > > Your browser sent a request that this server could not understand.
> > > 
> > > 
> > > ctrl + F5 刷新网页试下
> > 
> > 
> > 不行，web和gitea都是这样的错误
> 
> xver:0

果然可以了

**Comment by eMeab** [comment]
> 果然可以了
请Close

**Comment by shenlijun** [comment]
> > 果然可以了
> > 请Close

万分感谢！！！！！！！！！！！！

**Comment by shenlijun** [comment]
最后确定，只要是xver:0就ok，不用取消h2
