### ISSUE TITLE
common.Must(core.RequireFeatures(...))的疑问

### ISSUE THREAD

**Issue by risetechlab** [XTLS/Xray-core#1033]
Hi，请教一下各位
这个地方：[strategy_leastping.go#L23](https://github.com/XTLS/Xray-core/blob/main/app/router/strategy_leastping.go#L23)，common.Must()是放在PickOutbound()中的，这部分是不是不适合放到[InjectContext()](https://github.com/XTLS/Xray-core/blob/main/app/router/strategy_leastping.go#L17)中？
因为我希望strategy，能在发生PickOutbound()调用前，就调用observatory的一些东西（例如告知observatory，订阅其结果的更新）。
我试了下，把common.Must(core.RequireFeatures(...))挪到InjectContext()中，程序也能正常运行，但不知道是不是这种结果无法得到保证：调用InjectContext()时，是不是这时候无法保证能获取到observatory？

**Comment by yichya** [comment]
个人理解 `extension.Observatory` 的实现 `observatory.Observer` 是在 `github.com/xtls/xray-core/app/observatory` 的 [`init()`](https://github.com/XTLS/Xray-core/blob/main/app/observatory/observer.go#L236) 里面被注入的，它肯定发生在 Xray 完成启动之前，所以这里应该不会有拿不到 `extension.Observatory` 的问题。

当然，既然这个项目依赖注入满天飞，那其实就什么时候用到什么时候去 Require 就得了（

**Comment by yuhan6665** [comment]
之前测会 panic 所以移了 https://github.com/XTLS/Xray-core/commit/7c240e8630815d2954a3ffac7860f0e06011de11
我认为依赖注入的顺序是由这里决定的
https://github.com/XTLS/Xray-core/blob/main/infra/conf/xray.go#L553

**Comment by risetechlab** [comment]
@yichya 
@yuhan6665 
好的，了解了，谢谢两位大佬的解疑！
