### ISSUE TITLE
heroku 上，服务端config.json  "port":"env:PORT" 失效了？

### ISSUE THREAD

**Issue by devwak** [XTLS/Xray-core#1034]
heroku 上部署，需要环境变量PORT,  原v2fly中测试 config.json 中，使用 "port":"env:PORT" 正常。

测试转Xray, 相同部署heroku 报错如下：
`
zha@TESTIT:~/xray$ ./Xray0
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 linux/amd64)
A unified platform for anti-censorship.
2022/04/26 11:20:12 Using default config:  /home/zha/xray/config.json
2022/04/26 11:20:12 [Info] infra/conf/serial: Reading config: /home/zha/xray/config.json
Failed to start: main: failed to load config files: [/home/zha/xray/config.json] > infra/conf/serial: failed to decode config: /home/zha/xray/config.json > infra/conf/serial: failed to read config file at line 1 char 1 > infra/conf: invalid port: env:PORT > invalid character 'e' looking for beginning of value
zha@TESTIT:~/xray$
`

config.json ：
`
{
   "log": {
      "access": "none",
      "error": "none",
      "loglevel": "none"
   },
   "inbounds": [
      {
         "port":"env:PORT",
         "protocol": "vmess",
         "settings": {
            "clients": [
               {
                  "id": "......",
                  "alterId": 64
               }
            ]
         },
         "streamSettings": {
            "network": "ws",
            "security": "none",
            "wsSettings": {
               "path": "/mypath"
            }
         }
      }
   ],
   "outbounds": [
      {
         "protocol": "freedom",
         "settings": {}
      }
   ]
}`

**Comment by devwak** [comment]
这个报错信息取自本机测试。 @yuhan6665

**Comment by yichya** [comment]
try applying this patch

```diff
diff --git a/infra/conf/common.go b/infra/conf/common.go
index 0de3072..873ae94 100644
--- a/infra/conf/common.go
+++ b/infra/conf/common.go
@@ -207,7 +207,7 @@ func (list *PortList) UnmarshalJSON(data []byte) error {
        for _, rangeStr := range rangelist {
                trimmed := strings.TrimSpace(rangeStr)
                if len(trimmed) > 0 {
-                       if strings.Contains(trimmed, "-") {
+                       if strings.Contains(trimmed, "-") || strings.Contains(trimmed, "env:") {
                                from, to, err := parseStringPort(trimmed)
                                if err != nil {
                                        return newError("invalid port range: ", trimmed).Base(err)
```

**Comment by devwak** [comment]
@yichya perfect, test passed.  thx
