### ISSUE TITLE
关于远程doH的问题

### ISSUE THREAD

**Issue by markkwanhz** [XTLS/Xray-core#104]
客户端设置了如下的DNS object，outbound除了freedom另一个为vless+xtls
`
"dns":{
  "servers": [
     {
      "address": "https://1.0.0.1/dns-query",
      "domains": ["geosite:geolocation-!cn"]
     },
     {
      "address": "https+local://223.5.5.5/dns-query",
      "expectIPs": ["geoip:cn"],
      "domains": ["geosite:cn"]
     }
  ]
}
`
客户端会时不时的出现以下的log
`
app/dns: failed to retrieve response > Post "https://1.0.0.1/dns-query": io: read/write on closed pipe
`

**Comment by badO1a5A90** [comment]
简单来说这是因为远程DOH在并发时，多个DNS请求通过一个连接发出，但第一个DNS请求被返回时，连接即关闭。
后续请求就会报这个错误，然后使用下一个DNS服务器请求解析（虽然看起来可以继续工作但可能就漏DNS请求到其他服务器了）
实际验证，修改成每个远程doh都用独立HTTP client 可以解决，但似乎效率有点低。

**Comment by markkwanhz** [comment]
想了一下好像的确这个方案是比较实际的，我感觉一般网络客户端在发起dns查询时应该也是一次查询一个连接吧？

**Comment by badO1a5A90** [comment]
其他模式连接是保持的。

**Comment by badO1a5A90** [comment]
其他模式指本地 /远程UDP模式，本地doh模式。（其实只有远程doh会这样）。

**Comment by badO1a5A90** [comment]
> 想了一下好像的确这个方案是比较实际的，我感觉一般网络客户端在发起dns查询时应该也是一次查询一个连接吧？

这个模式我有键盘了可以给一波代码，到时候你可以试试，至少能用，也不会有DNS泄漏

**Comment by markkwanhz** [comment]
> > 想了一下好像的确这个方案是比较实际的，我感觉一般网络客户端在发起dns查询时应该也是一次查询一个连接吧？
> 
> 这个模式我有键盘了可以给一波代码，到时候你可以试试，至少能用，也不会有DNS泄漏

我现在改成了本地doh，远程是udp模式。我感觉从vps出口到dns服务器这一段应该没啥问题

**Comment by badO1a5A90** [comment]
这个组合不会有问题。

**Comment by zhfreal** [comment]
> > > 想了一下好像的确这个方案是比较实际的，我感觉一般网络客户端在发起dns查询时应该也是一次查询一个连接吧？
> > 
> > 
> > 这个模式我有键盘了可以给一波代码，到时候你可以试试，至少能用，也不会有DNS泄漏
> 
> 我现在改成了本地doh，远程是udp模式。我感觉从vps出口到dns服务器这一段应该没啥问题

doh的意义除了防止解析结果被篡改之外，还有更重要的是保证私密性。如果只是为了防篡改，个人觉得就没必要doh，传统模式加代理即可。

**Comment by markkwanhz** [comment]
> > > > 想了一下好像的确这个方案是比较实际的，我感觉一般网络客户端在发起dns查询时应该也是一次查询一个连接吧？
> > > 
> > > 
> > > 这个模式我有键盘了可以给一波代码，到时候你可以试试，至少能用，也不会有DNS泄漏
> > 
> > 
> > 我现在改成了本地doh，远程是udp模式。我感觉从vps出口到dns服务器这一段应该没啥问题
> 
> doh的意义除了防止解析结果被篡改之外，还有更重要的是保证私密性。如果只是为了防篡改，个人觉得就没必要doh，传统模式加代理即可。

确实是，多谢指导

**Comment by mariokart1992** [comment]
大佬，能教一下怎么解决这个问题吗？是在客户端设置http么？

**Comment by markkwanhz** [comment]
> 大佬，能教一下怎么解决这个问题吗？是在客户端设置http么？

大佬不敢当。我就把客户端的dns object改成 `{ "servers": [ { "address": "1.1.1.1", "domains": ["geosite:geolocation-!cn"] }, { "address": "https+local://223.5.5.5/dns-query", "expectIPs": ["geoip:cn"], "domains": ["geosite:cn"] } ] }` 

你可以对比一下我原来的写法和现在的写法

**Comment by mariokart1992** [comment]
好的，谢谢，我了解这个解析的原理了，感谢

**Comment by rprx** [comment]
应该可以修改远程 DoH 的行为？

**Comment by badO1a5A90** [comment]
> 应该可以修改远程 DoH 的行为？

我上面回复的方式可以修复，但效率较低。
因为每一次解析都要重新起新连接。（虽然目前本身远程doh的行为就是如此了，并且有错误）
我自己在用这种修复后模式，因为我线路延迟低。
如果延迟高，并且设置了路由规则中每次域名都要用内置DNS服务器解析为IP进行匹配之类的规则，应该就会很影响体验了。

**Comment by rprx** [comment]
> 如果延迟高，并且设置了路由规则中每次域名都要用内置DNS服务器解析为IP进行匹配之类的规则，应该就会很影响体验了。

应该不会吧，因为以前的行为也只能返回一个有效结果

**Comment by badO1a5A90** [comment]
> 客户端设置了如下的DNS object，outbound除了freedom另一个为vless+xtls
> `"dns":{ "servers": [ { "address": "https://1.0.0.1/dns-query", "domains": ["geosite:geolocation-!cn"] }, { "address": "https+local://223.5.5.5/dns-query", "expectIPs": ["geoip:cn"], "domains": ["geosite:cn"] } ] }`
> 客户端会时不时的出现以下的log
> `app/dns: failed to retrieve response > Post "https://1.0.0.1/dns-query": io: read/write on closed pipe`

@markkwanhz 1.2.2已经修复了这个错误,请升级后试一下.

**Comment by markkwanhz** [comment]
> > 客户端设置了如下的DNS object，outbound除了freedom另一个为vless+xtls
> > `"dns":{ "servers": [ { "address": "https://1.0.0.1/dns-query", "domains": ["geosite:geolocation-!cn"] }, { "address": "https+local://223.5.5.5/dns-query", "expectIPs": ["geoip:cn"], "domains": ["geosite:cn"] } ] }`
> > 客户端会时不时的出现以下的log
> > `app/dns: failed to retrieve response > Post "https://1.0.0.1/dns-query": io: read/write on closed pipe`
> 
> @markkwanhz 1.2.2已经修复了这个错误,请升级后试一下.

测试过了，已经没问题，感谢！

**Comment by badO1a5A90** [comment]
> 
> 测试过了，已经没问题，感谢！

对了, 另一个DOH的修改是,现在也支持路由分流了(以前傻傻的走第一个outbound)
也就是现在的行为模式正常了. https://github.com/XTLS/Xray-core/pull/147
你也可以试一下.

**Comment by markkwanhz** [comment]
> > 测试过了，已经没问题，感谢！
> 
> 对了, 另一个DOH的修改是,现在也支持路由分流了(以前傻傻的走第一个outbound)
> 也就是现在的行为模式正常了. #147
> 你也可以试一下.

遇到了新的问题,我用另一台电脑,win7的(之前的是win10),用远程doH会遇到这个问题:

2021/01/18 19:15:03 [Error] app/dns: failed to retrieve response for raw.githubusercontent.com. > Post "https://1.0.0.1/dns-query": x509: certificate is valid for 1.1.1.1, 1.0.0.1, 162.159.36.1, 162.159.46.1, 2606:4700:4700::1111, 2606:4700:4700::1001, 2606:4700:4700::64, 2606:4700:4700::6400, not 1.0.0.1

这个错误在win10里面没有,我换成非doH就没报错了,能定位原因吗

**Comment by badO1a5A90** [comment]
@eMeab  破案了. 
windows 7的锅. 见 
https://community.cloudflare.com/t/cloudflared-1-1-1-1-ssl-issue/15321
https://github.com/golang/go/issues/30985
