### ISSUE TITLE
xray自动监听53/UDP

### ISSUE THREAD

**Issue by dfldylan** [XTLS/Xray-core#1043]
#504 该问题经测试，最新版本还是存在
设备是r4s，arm64架构
注意下图中 ，我只是简单地mv xray /usr/bin/v2ray了，因此名字是v2ray
<img width="629" alt="截屏2022-05-01 23 22 15" src="https://user-images.githubusercontent.com/28103567/166153396-ac507815-4d50-42f4-ac0f-f99efdccec0f.png">
更换成v2ray 4.44后，就没有这个问题
<img width="629" alt="截屏2022-05-01 23 24 25" src="https://user-images.githubusercontent.com/28103567/166153411-5486568f-d6b9-4973-8ec9-f4eb44c49491.png">
另外，原问题中提到了xray有时候会监听8.8.8.8:53
在我这里我看到过监听114.114.114.114:53
可能是我在dnsmasq中设置了本机dns转发到114.114.114.114
谢谢！

**Comment by vojeus** [comment]
> #504 该问题经测试，最新版本还是存在
> 设备是r4s，arm64架构
> 注意下图中 ，我只是简单地mv xray /usr/bin/v2ray了，因此名字是v2ray
> <img width="629" alt="截屏2022-05-01 23 22 15" src="https://user-images.githubusercontent.com/28103567/166153396-ac507815-4d50-42f4-ac0f-f99efdccec0f.png">
> 更换成v2ray 4.44后，就没有这个问题
> <img width="629" alt="截屏2022-05-01 23 24 25" src="https://user-images.githubusercontent.com/28103567/166153411-5486568f-d6b9-4973-8ec9-f4eb44c49491.png">
> 另外，原问题中提到了xray有时候会监听8.8.8.8:53
> 在我这里我看到过监听114.114.114.114:53
> 可能是我在dnsmasq中设置了本机dns转发到114.114.114.114
> 谢谢！
> 

这是xray在dns查询

**Comment by dfldylan** [comment]
这里我dns只启用了114.114.114.114
<img width="436" alt="截屏2022-05-02 09 54 02" src="https://user-images.githubusercontent.com/28103567/166175498-42f510a8-56be-4f3a-be60-ea2d2b16ba0f.png">
看一下xray的日志：
<img width="833" alt="截屏2022-05-02 09 53 42" src="https://user-images.githubusercontent.com/28103567/166175518-d56e68b1-ec5d-4897-8752-732aced0c2fe.png">
明明都直连114.114.114.114:53了，为什么监听了一下192.168.2.1:53呢
谢谢！

**Comment by geniusyjiang** [comment]
路由器上透明代理遇到同样的问题，为何会无故占用53端口！！！我甚至将配置文件中dns段所有内容都删了，还是会无故占用192.168.1.1:53，dnsmasq正常占用了该端口的情况下还能占用！导致局域网内机器不能正常解析dns，然后无故断网！

**Comment by geniusyjiang** [comment]
暂时换回1.5.4版了，看看有没有同样的问题。如果还是有问题，那就只能换回v2ray了。

**Comment by dfldylan** [comment]
> 暂时换回1.5.4版了，看看有没有同样的问题。如果还是有问题，那就只能换回v2ray了。

别折腾了，xray好像所有版本都有这个问题

**Comment by geniusyjiang** [comment]
> 

发现一个临时解决方案，iptables设置53端口不转发xray，这样就不会监听53端口了

**Comment by dfldylan** [comment]
> > > 暂时换回1.5.4版了，看看有没有同样的问题。如果还是有问题，那就只能换回v2ray了。
> > 
> > 
> > 别折腾了，xray好像所有版本都有这个问题
> 
> 发现一个临时解决方案，iptables设置53端口不转发xray，这样就不会监听53端口了

听起来不是这样

**Comment by geniusyjiang** [comment]
> > > > 暂时换回1.5.4版了，看看有没有同样的问题。如果还是有问题，那就只能换回v2ray了。
> > > 
> > > 
> > > 别折腾了，xray好像所有版本都有这个问题
> > 
> > 
> > 发现一个临时解决方案，iptables设置53端口不转发xray，这样就不会监听53端口了
> 
> 听起来不是这样

试试不就知道了，反正我是这样解决问题了，没再监听53端口

**Comment by Kaze1027** [comment]
没搞懂你这是在干什么，我用得好好的啊，而且也没有出现莫名占用53端口的问题
![Uploading Screenshot_20220526_091819.jpg…]()

**Comment by Kaze1027** [comment]
![Uploading Screenshot_20220526_091819.jpg…]()

**Comment by dfldylan** [comment]
> 没搞懂你这是在干什么，我用得好好的啊，而且也没有出现莫名占用53端口的问题

你是透明代理吗，转发UDP了吗

**Comment by Kaze1027** [comment]
我不知道你用的什么方案，我用的ssrp，很好用，没有任何问题

**Comment by dfldylan** [comment]
> ![Screenshot_20220526_091819](https://user-images.githubusercontent.com/51438620/170396587-8633126a-3050-4a52-8aec-ac284eacb96d.jpg)

看看iptables -t mangle -L -n

**Comment by Kaze1027** [comment]
root@BillMikeWrt:~# iptables -t mangle -L -n
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
RRDIPT_INPUT  all  --  0.0.0.0/0            0.0.0.0/0           

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
RRDIPT_FORWARD  all  --  0.0.0.0/0            0.0.0.0/0           
TCPMSS     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp flags:0x06/0x02 /* !fw3: Zone wan MTU fixing */ TCPMSS clamp to PMTU
TCPMSS     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp flags:0x06/0x02 /* !fw3: Zone wan MTU fixing */ TCPMSS clamp to PMTU
TCPMSS     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp flags:0x06/0x02 /* !fw3: Zone wan MTU fixing */ TCPMSS clamp to PMTU
TCPMSS     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp flags:0x06/0x02 /* !fw3: Zone wan MTU fixing */ TCPMSS clamp to PMTU

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
RRDIPT_OUTPUT  all  --  0.0.0.0/0            0.0.0.0/0           

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         

Chain RRDIPT_FORWARD (1 references)
target     prot opt source               destination         
RETURN     all  --  192.168.8.50         0.0.0.0/0           
RETURN     all  --  0.0.0.0/0            192.168.8.50        
RETURN     all  --  192.168.8.122        0.0.0.0/0           
RETURN     all  --  0.0.0.0/0            192.168.8.122       
RETURN     all  --  192.168.8.108        0.0.0.0/0           
RETURN     all  --  0.0.0.0/0            192.168.8.108       
RETURN     all  --  192.168.8.118        0.0.0.0/0           
RETURN     all  --  0.0.0.0/0            192.168.8.118       
RETURN     all  --  192.168.8.215        0.0.0.0/0           
RETURN     all  --  0.0.0.0/0            192.168.8.215       
RETURN     all  --  192.168.8.136        0.0.0.0/0           
RETURN     all  --  0.0.0.0/0            192.168.8.136       
RETURN     all  --  192.168.8.208        0.0.0.0/0           
RETURN     all  --  0.0.0.0/0            192.168.8.208       
RETURN     all  --  192.168.8.153        0.0.0.0/0           
RETURN     all  --  0.0.0.0/0            192.168.8.153       
RETURN     all  --  192.168.8.244        0.0.0.0/0           
RETURN     all  --  0.0.0.0/0            192.168.8.244       
RETURN     all  --  192.168.8.167        0.0.0.0/0           
RETURN     all  --  0.0.0.0/0            192.168.8.167       
RETURN     all  --  192.168.8.248        0.0.0.0/0           
RETURN     all  --  0.0.0.0/0            192.168.8.248       
RETURN     all  --  192.168.8.185        0.0.0.0/0           
RETURN     all  --  0.0.0.0/0            192.168.8.185       
RETURN     all  --  192.168.8.178        0.0.0.0/0           
RETURN     all  --  0.0.0.0/0            192.168.8.178       
RETURN     all  --  192.168.8.187        0.0.0.0/0           
RETURN     all  --  0.0.0.0/0            192.168.8.187       
RETURN     all  --  192.168.8.179        0.0.0.0/0           
RETURN     all  --  0.0.0.0/0            192.168.8.179       
RETURN     all  --  192.168.8.103        0.0.0.0/0           
RETURN     all  --  0.0.0.0/0            192.168.8.103       

Chain RRDIPT_INPUT (1 references)
target     prot opt source               destination         
RETURN     all  --  0.0.0.0/0            0.0.0.0/0           
RETURN     all  --  0.0.0.0/0            0.0.0.0/0           

Chain RRDIPT_OUTPUT (1 references)
target     prot opt source               destination         
RETURN     all  --  0.0.0.0/0            0.0.0.0/0           
RETURN     all  --  0.0.0.0/0            0.0.0.0/0           
root@BillMikeWrt:~#

**Comment by dfldylan** [comment]
> root@BillMikeWrt:~# iptables -t mangle -L -n Chain PREROUTING (policy ACCEPT) target prot opt source destination
> 
> Chain INPUT (policy ACCEPT) target prot opt source destination RRDIPT_INPUT all -- 0.0.0.0/0 0.0.0.0/0
> 
> Chain FORWARD (policy ACCEPT) target prot opt source destination RRDIPT_FORWARD all -- 0.0.0.0/0 0.0.0.0/0 TCPMSS tcp -- 0.0.0.0/0 0.0.0.0/0 tcp flags:0x06/0x02 /* !fw3: Zone wan MTU fixing _/ TCPMSS clamp to PMTU TCPMSS tcp -- 0.0.0.0/0 0.0.0.0/0 tcp flags:0x06/0x02 /_ !fw3: Zone wan MTU fixing _/ TCPMSS clamp to PMTU TCPMSS tcp -- 0.0.0.0/0 0.0.0.0/0 tcp flags:0x06/0x02 /_ !fw3: Zone wan MTU fixing _/ TCPMSS clamp to PMTU TCPMSS tcp -- 0.0.0.0/0 0.0.0.0/0 tcp flags:0x06/0x02 /_ !fw3: Zone wan MTU fixing */ TCPMSS clamp to PMTU
> 
> Chain OUTPUT (policy ACCEPT) target prot opt source destination RRDIPT_OUTPUT all -- 0.0.0.0/0 0.0.0.0/0
> 
> Chain POSTROUTING (policy ACCEPT) target prot opt source destination
> 
> Chain RRDIPT_FORWARD (1 references) target prot opt source destination RETURN all -- 192.168.8.50 0.0.0.0/0 RETURN all -- 0.0.0.0/0 192.168.8.50 RETURN all -- 192.168.8.122 0.0.0.0/0 RETURN all -- 0.0.0.0/0 192.168.8.122 RETURN all -- 192.168.8.108 0.0.0.0/0 RETURN all -- 0.0.0.0/0 192.168.8.108 RETURN all -- 192.168.8.118 0.0.0.0/0 RETURN all -- 0.0.0.0/0 192.168.8.118 RETURN all -- 192.168.8.215 0.0.0.0/0 RETURN all -- 0.0.0.0/0 192.168.8.215 RETURN all -- 192.168.8.136 0.0.0.0/0 RETURN all -- 0.0.0.0/0 192.168.8.136 RETURN all -- 192.168.8.208 0.0.0.0/0 RETURN all -- 0.0.0.0/0 192.168.8.208 RETURN all -- 192.168.8.153 0.0.0.0/0 RETURN all -- 0.0.0.0/0 192.168.8.153 RETURN all -- 192.168.8.244 0.0.0.0/0 RETURN all -- 0.0.0.0/0 192.168.8.244 RETURN all -- 192.168.8.167 0.0.0.0/0 RETURN all -- 0.0.0.0/0 192.168.8.167 RETURN all -- 192.168.8.248 0.0.0.0/0 RETURN all -- 0.0.0.0/0 192.168.8.248 RETURN all -- 192.168.8.185 0.0.0.0/0 RETURN all -- 0.0.0.0/0 192.168.8.185 RETURN all -- 192.168.8.178 0.0.0.0/0 RETURN all -- 0.0.0.0/0 192.168.8.178 RETURN all -- 192.168.8.187 0.0.0.0/0 RETURN all -- 0.0.0.0/0 192.168.8.187 RETURN all -- 192.168.8.179 0.0.0.0/0 RETURN all -- 0.0.0.0/0 192.168.8.179 RETURN all -- 192.168.8.103 0.0.0.0/0 RETURN all -- 0.0.0.0/0 192.168.8.103
> 
> Chain RRDIPT_INPUT (1 references) target prot opt source destination RETURN all -- 0.0.0.0/0 0.0.0.0/0 RETURN all -- 0.0.0.0/0 0.0.0.0/0
> 
> Chain RRDIPT_OUTPUT (1 references) target prot opt source destination RETURN all -- 0.0.0.0/0 0.0.0.0/0 RETURN all -- 0.0.0.0/0 0.0.0.0/0 root@BillMikeWrt:~#

看起来走的不是mangle表，看看
iptables -t nat -L -n

**Comment by Kaze1027** [comment]
root@BillMikeWrt:~# iptables -t nat -L -n
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
SS_SPEC_WAN_AC  tcp  --  0.0.0.0/0            0.0.0.0/0            /* _SS_SPEC_RULE_ */
prerouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom prerouting rule chain */
zone_lan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
zone_wan_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
zone_VPN_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
zone_vpn_prerouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
REDIRECT   udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 redir ports 53
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53 redir ports 53

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
SS_SPEC_WAN_AC  tcp  --  0.0.0.0/0            0.0.0.0/0            /* _SS_SPEC_RULE_ */

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
postrouting_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom postrouting rule chain */
zone_lan_postrouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
zone_wan_postrouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
zone_wan_postrouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
zone_VPN_postrouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
zone_vpn_postrouting  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */

Chain MINIUPNPD (1 references)
target     prot opt source               destination         

Chain MINIUPNPD-POSTROUTING (1 references)
target     prot opt source               destination         

Chain SS_SPEC_WAN_AC (2 references)
target     prot opt source               destination         
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            match-set netflix dst redir ports 303
RETURN     all  --  0.0.0.0/0            0.0.0.0/0            match-set whitelist dst
SS_SPEC_WAN_FW  all  --  0.0.0.0/0            0.0.0.0/0            match-set blacklist dst
RETURN     all  --  0.0.0.0/0            0.0.0.0/0            match-set bplan src
SS_SPEC_WAN_FW  all  --  0.0.0.0/0            0.0.0.0/0            match-set fplan src
RETURN     tcp  --  0.0.0.0/0            64.64.224.39         tcp dpt:!53
RETURN     all  --  0.0.0.0/0            0.0.0.0/0            match-set ss_spec_wan_ac dst
RETURN     all  --  0.0.0.0/0            0.0.0.0/0            match-set china dst
SS_SPEC_WAN_FW  all  --  0.0.0.0/0            0.0.0.0/0            match-set gmlan src ! match-set china dst
SS_SPEC_WAN_FW  all  --  0.0.0.0/0            0.0.0.0/0           

Chain SS_SPEC_WAN_FW (4 references)
target     prot opt source               destination         
RETURN     all  --  0.0.0.0/0            0.0.0.0/8           
RETURN     all  --  0.0.0.0/0            10.0.0.0/8          
RETURN     all  --  0.0.0.0/0            127.0.0.0/8         
RETURN     all  --  0.0.0.0/0            169.254.0.0/16      
RETURN     all  --  0.0.0.0/0            172.16.0.0/12       
RETURN     all  --  0.0.0.0/0            192.168.0.0/16      
RETURN     all  --  0.0.0.0/0            224.0.0.0/4         
RETURN     all  --  0.0.0.0/0            240.0.0.0/4         
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 22,53,587,465,995,993,143,80,443,853,9418 redir ports 1234

Chain postrouting_VPN_rule (1 references)
target     prot opt source               destination         

Chain postrouting_lan_rule (1 references)
target     prot opt source               destination         

Chain postrouting_rule (1 references)
target     prot opt source               destination         

Chain postrouting_vpn_rule (1 references)
target     prot opt source               destination         

Chain postrouting_wan_rule (1 references)
target     prot opt source               destination         

Chain prerouting_VPN_rule (1 references)
target     prot opt source               destination         

Chain prerouting_lan_rule (1 references)
target     prot opt source               destination         

Chain prerouting_rule (1 references)
target     prot opt source               destination         

Chain prerouting_vpn_rule (1 references)
target     prot opt source               destination         

Chain prerouting_wan_rule (1 references)
target     prot opt source               destination         

Chain zone_VPN_postrouting (1 references)
target     prot opt source               destination         
postrouting_VPN_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom VPN postrouting rule chain */

Chain zone_VPN_prerouting (1 references)
target     prot opt source               destination         
prerouting_VPN_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom VPN prerouting rule chain */

Chain zone_lan_postrouting (1 references)
target     prot opt source               destination         
postrouting_lan_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom lan postrouting rule chain */
SNAT       tcp  --  192.168.8.0/24       192.168.8.1          tcp dpt:80 /* !fw3: 管理口 (reflection) */ to:192.168.8.1
SNAT       udp  --  192.168.8.0/24       192.168.8.1          udp dpt:80 /* !fw3: 管理口 (reflection) */ to:192.168.8.1
SNAT       tcp  --  192.168.8.0/24       192.168.8.50         tcp dpt:3389 /* !fw3: 3389 (reflection) */ to:192.168.8.1

Chain zone_lan_prerouting (1 references)
target     prot opt source               destination         
prerouting_lan_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom lan prerouting rule chain */
DNAT       tcp  --  192.168.8.0/24       124.162.157.250      tcp dpt:81 /* !fw3: 管理口 (reflection) */ to:192.168.8.1:80
DNAT       udp  --  192.168.8.0/24       124.162.157.250      udp dpt:81 /* !fw3: 管理口 (reflection) */ to:192.168.8.1:80
DNAT       tcp  --  192.168.8.0/24       124.162.157.250      tcp dpt:3389 /* !fw3: 3389 (reflection) */ to:192.168.8.50:3389

Chain zone_vpn_postrouting (1 references)
target     prot opt source               destination         
postrouting_vpn_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom vpn postrouting rule chain */
FULLCONENAT  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */

Chain zone_vpn_prerouting (1 references)
target     prot opt source               destination         
prerouting_vpn_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom vpn prerouting rule chain */
FULLCONENAT  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */

Chain zone_wan_postrouting (2 references)
target     prot opt source               destination         
MINIUPNPD-POSTROUTING  all  --  0.0.0.0/0            0.0.0.0/0           
postrouting_wan_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom wan postrouting rule chain */
FULLCONENAT  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */

Chain zone_wan_prerouting (2 references)
target     prot opt source               destination         
MINIUPNPD  all  --  0.0.0.0/0            0.0.0.0/0           
prerouting_wan_rule  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3: Custom wan prerouting rule chain */
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:81 /* !fw3: 管理口 */ to:192.168.8.1:80
DNAT       udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:81 /* !fw3: 管理口 */ to:192.168.8.1:80
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:3389 /* !fw3: 3389 */ to:192.168.8.50:3389
FULLCONENAT  all  --  0.0.0.0/0            0.0.0.0/0            /* !fw3 */
root@BillMikeWrt:~#

**Comment by vojeus** [comment]
这个问题与xray无关。 你们应该这样理解，有一个udp请求被转发到xray代理了。

应该可以在iptables查询到相关转发规则。 

比如我使用gv时，会有以下记录， 这并不是说xray监听了443端口。 而是有目标为142.250.68.10:443的udp请求被代理了。

udp        0      0 142.250.68.10:443       0.0.0.0:*                           3158/xray

**Comment by Kaze1027** [comment]
对啊，所以我一直也没明白他这是什么问题，我也想知道他这是什么方案，怎么会有这些问题

**Comment by wy580477** [comment]
翻墙插件劫持53端口udp流量闹出来的幺蛾子。用了现场翻墙插件就别折腾dns，不然没有dns相关基础知识就掉坑里了。

**Comment by dfldylan** [comment]
> 这个问题与xray无关。 你们应该这样理解，有一个udp请求被转发到xray代理了。
> 
> 应该可以在iptables查询到相关转发规则。
> 
> 比如我使用gv时，会有以下记录， 这并不是说xray监听了443端口。 而是有目标为142.250.68.10:443的udp请求被代理了。 当有返回数据时， 该远程地址， 对xray来说，就是Local Address。
> 
> udp 0 0 142.250.68.10:443 0.0.0.0:* 3158/xray

你这种说法是否有依据或者是否有文档出处。如果是我知识不足我想学习一下。
https://github.com/XTLS/Xray-core/issues/504#issuecomment-818388950 
就像这里说的，netstat 中我用了-l参数，应该是监听端口啊

**Comment by vojeus** [comment]
> 

我不是说这不是listen, 而是这条记录的表达的是xray把远程服务器的返回转发给实际访问者。 
实际上你会发现所有的udp返回都会有类似的记录，绑定的都是远程目录地址。
而你出现53的记录，是因为dns请求被代理了。

**Comment by vojeus** [comment]
> 你这种说法是否有依据或者是否有文档出处。如果是我知识不足我想学习一下。 [#504 (comment)](https://github.com/XTLS/Xray-core/issues/504#issuecomment-818388950) 就像这里说的，netstat 中我用了-l参数，应该是监听端口啊

这条记录的表达的是xray把远程服务器的返回转发给实际访问者。
实际上你会发现所有的udp返回都会有类似的记录，-l参数可查到，laddr都是远程目标地址。而绑定非本地地址是不行的。同地址多次绑定也不行。
当有返回时xray发送了一条laddr为远程地址的消息(FackeUDP)， 而系统认为他是个udp listen, 实际并不是。

你出现192.168.2.1:53的记录，是因为你把目标为内网的请求交给xray代理了。

**Comment by dfldylan** [comment]
> > 你这种说法是否有依据或者是否有文档出处。如果是我知识不足我想学习一下。 [#504 (comment)](https://github.com/XTLS/Xray-core/issues/504#issuecomment-818388950) 就像这里说的，netstat 中我用了-l参数，应该是监听端口啊
> 
> 这条记录的表达的是xray把远程服务器的返回转发给实际访问者。 实际上你会发现所有的udp返回都会有类似的记录，-l参数可查到，laddr都是远程目标地址。而绑定非本地地址是不行的。同地址多次绑定也不行。 当有返回时xray发送了一条laddr为远程地址的消息(FakeUDP)， 而系统认为他是个udp listen, 实际并不是。
> 
> 你出现192.168.2.1:53的记录，是因为你把目标为内网的请求交给xray代理了。
懂了，之前看的一篇大佬的文章https://github.com/XTLS/Xray-core/discussions/237#discussion-2876529

> 等需要往回发包时，代理软件会先在本地伪造出“返回的 UDP 包的来源二元组”的 socket，用这个 socket 把包发回去（这个原理就是可能会遇到 too many open files 的原因）。相比于其它软件，Xray-core 对这里有专门的优化，更优雅且有更好的性能。

原来就是在这里，
看起来我被netstat误导了，谢谢大家
