### ISSUE TITLE
编译1.5.5遇到的GO问题

### ISSUE THREAD

**Issue by Michaol** [XTLS/Xray-core#1046]
编译HW选择xray-core编译时出现了
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.

下面是log
SHELL= flock /home/michaol/lede/tmp/.Xray-core-1.5.5.tar.gz.flock -c '  	/home/michaol/lede/scripts/download.pl "/home/michaol/lede/dl" "Xray-core-1.5.5.tar.gz" "3f8d04fef82a922c83bab43cac6c86a76386cf195eb510ccf1cc175982693893" "" "https://codeload.github.com/XTLS/Xray-core/tar.gz/v1.5.5?"    '
rm -f /home/michaol/lede/build_dir/target-x86_64_musl/Xray-core-1.5.5/.built
touch /home/michaol/lede/build_dir/target-x86_64_musl/Xray-core-1.5.5/.built_check
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/home/michaol/lede/tmp/go-build" GO_MOD_CACHE_DIR="/home/michaol/lede/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/xtls/xray-core" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/xtls/xray-core/main" GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/home/michaol/lede/build_dir/target-x86_64_musl/Xray-core-1.5.5" GO_BUILD_DIR="/home/michaol/lede/build_dir/target-x86_64_musl/Xray-core-1.5.5/.go_work/build" GO_BUILD_BIN_DIR="/home/michaol/lede/build_dir/target-x86_64_musl/Xray-core-1.5.5/.go_work/build/bin" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/home/michaol/lede/staging_dir/target-x86_64_musl/usr/share/gocode/src" GOOS="linux" GOARCH="amd64" GO386="" GOAMD64="v1" GOARM="" GOMIPS="" GOMIPS64="" GOPPC64="" CGO_ENABLED=1 CC="x86_64-openwrt-linux-musl-gcc" CXX="x86_64-openwrt-linux-musl-g++" CGO_CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/michaol/lede/build_dir/target-x86_64_musl/Xray-core-1.5.5=Xray-core-1.5.5 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_CPPFLAGS="-I/home/michaol/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/include -I/home/michaol/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include/fortify -I/home/michaol/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include" CGO_CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/michaol/lede/build_dir/target-x86_64_musl/Xray-core-1.5.5=Xray-core-1.5.5 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_LDFLAGS="-L/home/michaol/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/lib -L/home/michaol/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib -znow -zrelro" GOPATH="/home/michaol/lede/build_dir/target-x86_64_musl/Xray-core-1.5.5/.go_work/build" GOCACHE="/home/michaol/lede/tmp/go-build" GOMODCACHE="/home/michaol/lede/dl/go-mod-cache" GOENV=off /usr/bin/env bash /home/michaol/lede/feeds/packages/lang/golang//golang-build.sh build -v -buildvcs=false -trimpath -ldflags "all=-buildid '1650976451' -linkmode external -extldflags '-L/home/michaol/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/lib -L/home/michaol/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib -Wl,-z,now -Wl,-z,relro'"        -ldflags "-s -w -X github.com/xtls/xray-core/core.build=OpenWrt -X github.com/xtls/xray-core/core.version=1.5.5 -buildid '1650976451' -linkmode external -extldflags '-L/home/michaol/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/lib -L/home/michaol/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib -Wl,-z,now -Wl,-z,relro'"  
Finding targets
go: downloading github.com/golang/protobuf v1.5.2
go: downloading google.golang.org/protobuf v1.28.0
go: downloading golang.org/x/sys v0.0.0-20220422013727-9388b58f7150
go: downloading github.com/pires/go-proxyproto v0.6.2
go: downloading google.golang.org/grpc v1.46.0
go: downloading github.com/lucas-clemente/quic-go v0.27.0
go: downloading golang.org/x/net v0.0.0-20220421235706-1d1ef9303861
go: downloading go.starlark.net v0.0.0-20220328144851-d1966c6b9fcd
go: downloading golang.org/x/crypto v0.0.0-20220411220226-7b82a4e95df4
go: downloading github.com/xtls/go v0.0.0-20210920065950-d4af136d3672
go: downloading github.com/refraction-networking/utls v1.0.0
go: downloading github.com/gorilla/websocket v1.5.0
go: downloading google.golang.org/genproto v0.0.0-20220422154200-b37d22cd5731
go: downloading github.com/ghodss/yaml v1.0.1-0.20190212211648-25d852aebe32
go: downloading github.com/pelletier/go-toml v1.9.5
go: downloading github.com/v2fly/ss-bloomring v0.0.0-20210312155135-28617310f63e
go: downloading github.com/seiflotfy/cuckoofilter v0.0.0-20220411075957-e3b120b3f5fb
go: downloading github.com/francoispqt/gojay v1.2.13
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/riobard/go-bloom v0.0.0-20200614022211-cdc8013cb5b3
go: downloading github.com/dgryski/go-metro v0.0.0-20211217172704-adc40b04c140
go: downloading golang.org/x/text v0.3.7
go: downloading github.com/marten-seemann/qtls-go1-18 v0.1.1
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.

Building targets
no Go files in /home/michaol/lede/build_dir/target-x86_64_musl/Xray-core-1.5.5/.go_work/build

make[3]: *** [Makefile:51: /home/michaol/lede/build_dir/target-x86_64_musl/Xray-core-1.5.5/.built] Error 1
make[3]: Leaving directory '/home/michaol/lede/feeds/helloworld/xray-core'
time: package/feeds/helloworld/xray-core/compile#1.53#0.17#3.59
    ERROR: package/feeds/helloworld/xray-core failed to build.
make[2]: *** [package/Makefile:116: package/feeds/helloworld/xray-core/compile] Error 1
make[2]: Leaving directory '/home/michaol/lede'
make[1]: *** [package/Makefile:110: /home/michaol/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/michaol/lede'
make: *** [/home/michaol/lede/include/toplevel.mk:230: world] Error 2

求助，谢谢！

**Comment by chika0801** [comment]
https://github.com/xiaorouji/openwrt-passwall.git

我用的passwall作者这边更新的xray-core

替换的源码里自带的老版本，是成功的

**Comment by Michaol** [comment]
> https://github.com/xiaorouji/openwrt-passwall.git
> 
> 我用的passwall作者这边更新的xray-core
> 
> 替换的源码里自带的老版本，是成功的

同样的config，github云编译就没问题，偏偏本地就出错，搞不明白。

**Comment by yuhan6665** [comment]
`error obtaining VCS status: exit status 128`
本地依赖下载不来

**Comment by Michaol** [comment]
重做整个Ubuntu后解决了

**Comment by shu0802** [comment]
https://github.com/XTLS/Xray-core/releases 网站上下载来放哪个文件夹里可以编译
