### ISSUE TITLE
Xray:443 --> Nginx --> Xray(gRPC)能连通 但是nginx error.log里面一直报错

### ISSUE THREAD

**Issue by zxczaq001** [XTLS/Xray-core#1048]
2022/05/03 04:08:10 [error] 16598#16598: *928 upstream sent frame for closed stream 1 while reading upstream, client: 127.0.0.1, server: b.yhxy.work, request: "POST //TunMulti HTTP/2.0", upstream: "grpc://127.0.0.1:6666", host: "xxx:443"
这个报错怎么解决

**Comment by chika0801** [comment]
你要发xray配置 nginx配置别人才能帮你

建议你从简单的nginx - xray 开始
https://github.com/chika0801/Xray-examples/tree/main/VLESS-gRPC-TLS

**Comment by xqzr** [comment]
参考 https://github.com/XTLS/Xray-examples/tree/main/VLESS-GRPC#nginx
再不行 升级 Nginx 版本

**Comment by zxczaq001** [comment]
> 你要发xray配置 nginx配置别人才能帮你
> 
> 建议你从简单的nginx - xray 开始 https://github.com/chika0801/Xray-examples/tree/main/VLESS-gRPC-TLS

 server {
    listen 127.0.0.1:33223 http2;
    server_name  xxx;
    root /usr/share/nginx/html;
    index index.php index.html index.htm;
	location / {

		client_max_body_size 0;
		client_body_timeout 1071906480m;
		grpc_read_timeout 1071906480m;
		grpc_pass grpc://127.0.0.1:6666;
	}




}
嗯 我原来用的是xray TCP协议回落nginx33223  gRPC协议走的中转gost-->gost-->gRPC 无聊就想试试能不能Xray:443 --> Nginx --> Xray(gRPC)

**Comment by zxczaq001** [comment]
> 参考 https://github.com/XTLS/Xray-examples/tree/main/VLESS-GRPC#nginx 再不行 升级 Nginx 版本

版本是1.14.2

**Comment by xqzr** [comment]
> 版本是1.14.2

建议升级到最新版本

**Comment by mclovin-2k** [comment]
Xray:443 --> Nginx (Location 分流) --> Xray(gRPC)
                                                     ↳  --> Xray(WS)
这种是可以的。
我现在就是这样用的。
就是不知道有没有什么安全隐患。

**Comment by chika0801** [comment]
> ```js
> Xray:443 --> Nginx (Location 分流) --> Xray(gRPC)
>                                ↳  --> Xray(WS)
> ```
> 
> 这种是可以的。 我现在就是这样用的。 就是不知道有没有什么安全隐患。

没什么隐患

**Comment by mclovin-2k** [comment]
> > ```js
> > Xray:443 --> Nginx (Location 分流) --> Xray(gRPC)
> >                                ↳  --> Xray(WS)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这种是可以的。 我现在就是这样用的。 就是不知道有没有什么安全隐患。
> 
> 没什么隐患

就是不知道 Xray 发布 gRPC 的时候，为什么建议用域名分流。我这样分流明显更简单。

**Comment by chika0801** [comment]
> > > ```js
> > > Xray:443 --> Nginx (Location 分流) --> Xray(gRPC)
> > >                                ↳  --> Xray(WS)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 这种是可以的。 我现在就是这样用的。 就是不知道有没有什么安全隐患。
> > 
> > 
> > 没什么隐患
> 
> 就是不知道 Xray 发布 gRPC 的时候，为什么建议用域名分流。我这样分流明显更简单。

xray发布grpc时没什么建议域名分流，而且不是建议你这么复杂的流程。

纯就nginx前置 path(servername) 分流到 后置的xray

我的模板
https://github.com/chika0801/Xray-examples/tree/main/VLESS-gRPC-TLS

**Comment by yuhan6665** [comment]
close as solved

**Comment by dream110fly** [comment]
@zxczaq001 hi， how do you slove this problem?
