### ISSUE TITLE
In game voice not functioning

### ISSUE THREAD

**Issue by syahmisenpai97** [XTLS/Xray-core#1052]
Hello, I have problem with in game voice not function. I using xray vless xtls in openwrt passwall and ssr plus still no voice in game. Game that i play is Valorant. Need Help. TQ

**Comment by xqzr** [comment]
```
{
 "sniffing": {
  "enabled": true,
  "destOverride": [
   "http",
   "tls"
  ],
  "domainsExcluded": [
   "bnxp.vivox.com"
  ]
 }
}
```

**Comment by Eidreven** [comment]
> Hello, I have problem with in game voice not function. I using xray vless xtls in openwrt passwall and ssr plus still no voice in game. Game that i play is Valorant. Need Help. TQ

I got same issue .

**Comment by Eidreven** [comment]
> ```
> {
>  "sniffing": {
>   "enabled": true,
>   "destOverride": [
>    "http",
>    "tls"
>   ],
>   "domainsExcluded": [
>    "bnxp.vivox.com"
>   ]
>  }
> }
> ```


What is this?
