### ISSUE TITLE
gRPC发现闪断bug v1.5.5

### ISSUE THREAD

**Issue by wutongskype** [XTLS/Xray-core#1053]
出现情况为客户端使用Multi模式, 传输数据时会闪断, 使用gun模式时正常

测试命令: curl -o /dev/null https://speed.cloudflare.com/__down?bytes=209715200

以下为gRPC_Multi 日志 debug
[access.log](https://github.com/XTLS/Xray-core/files/8636383/access.log)
[error.log](https://github.com/XTLS/Xray-core/files/8636384/error.log)

以下为gRPC_Gun 日志 debug
[access.log](https://github.com/XTLS/Xray-core/files/8636388/access.log)
[error.log](https://github.com/XTLS/Xray-core/files/8636389/error.log)

**Comment by wutongskype** [comment]
服务器配置
"streamSettings": {
     "network":"grpc",
     "grpcSettings": {
		          												"serviceName": "grpc.miaosky.party",
		          												"multiMode": false,
		          												"idle_timeout": 66, 
		          												"health_check_timeout": 33,
		          												"permit_without_stream": true,
		          												"initial_windows_size": 0

**Comment by hadow** [comment]
the same problem
