### ISSUE TITLE
[bug] 开启内置DNS后，仍然会通过系统DNS查询

### ISSUE THREAD

**Issue by Hubedge** [XTLS/Xray-core#1058]
## 测试1
通过`/etc/resolv.conf`配置系统DNS为`8.8.8.8`，搭配如下Xray配置，https://www.doileak.com/classic.html 显示同时存在来自Cloudflare和Google的DNS查询。
```json
{
    "log": {
        "loglevel": "warning"
    },
    "dns": {
        "servers": [
            "1.1.1.1",
            "1.0.0.1"
        ]
    },
    "inbounds": [],
    "outbounds": [
        {
            "protocol": "freedom",
            "settings": {
                "domainStrategy": "UseIPv4" //出站连接时使用内置DNS，即1.1.1.1
            }
        },
        {
            "protocol": "blackhole",
            "tag": "blocked"
        }
    ],
    "routing": {
        "domainStrategy": "AsIs", // 路由阶段不进行DNS查询
        "rules": [
            {
                "type": "field",
                "ip": [
                    "geoip:private"
                ],
                "outboundTag": "blocked"
            }
        ]
    }
}
```

## 测试2
相同的Xray配置，在`/etc/resolv.conf`配置系统DNS为`1.1.1.1`后，测试显示只收到来自Cloudflare的DNS查询。

## 预期
无论系统DNS为何，在该Xray配置配置下，doileak都应该只收到来自Cloudflare的DNS查询。

**Comment by chika0801** [comment]
这问题你是用路由器上的软件翻墙吗？不是，是用客户端如v2rayn，也要发客户端配置。

和xray 服务器配置无关。你要搜下 dns 查询流程

**Comment by chika0801** [comment]
看了客户端配置，服务器配置，没发现什么问题

建议你在服务器配置dns部分加，再测试下。我拿你发的链接测了我的配置，没dns泄露。你这测试网站我是第一次见。其它类似测试网站我自己用的配置也没问题。

"queryStrategy": "UseIPv4"
https://github.com/chika0801/Xray-examples/blob/c7fd07ae78e731396f1e916d19b57af27d565c29/VLESS-TCP-XTLS/config_server.json#L11

**Comment by yuhan6665** [comment]
@xqzr 说 windows 的系统 socks 代理是 socks4 不支持域名代理 所以流量在进入 core 之前有一次 DNS 解析
想要完全避免泄漏可以使用 proxifier 之类的全局代理工具

**Comment by chika0801** [comment]
手机使用v2rayN 自定义配置 fakedns。

还是复现了1楼的情况

手机客户端不可能是sockv4的锅吧

**Comment by Hubedge** [comment]
有没有可能是浏览器的预加载之类的功能导致了一次多余的DNS查询？但即使这样也应该走服务端xray配置的内置DNS啊。

目前发现Edge和Chrome都有一楼的情况，浏览器的flag是默认。Chrome 101.0.4951.54，Edge 101.0.1210.39

**Comment by vojeus** [comment]
内置dns是路由和outbound使用的，你访问网站的dns查询，会根据inbound方式，由路由器或远端服务器处理。

**Comment by Hubedge** [comment]
服务端把系统DNS设置为一个显然不是DNS服务的IP后，客户端浏览器仍然能正常上网，且测试显示只收到来自Cloudflare的查询，说明这一次系统DNS的查询不是必需的。

**Comment by yuhan6665** [comment]
噢 我理解错了 能看一下服务端的 debug 日志？

**Comment by chika0801** [comment]
我复现的vps用的Debian11，刚才找了一台Debian10的，一样的xray客户端(v2rayN)，服务器端配置，没有复现出1楼的现象。怕是和Deian10 11有关。手里没ubuntu的vps。

**Comment by chika0801** [comment]
> 服务端把系统DNS设置为一个显然不是DNS服务的IP后，客户端浏览器仍然能正常上网，且测试显示只收到来自Cloudflare的查询，说明这一次系统DNS的查询不是必需的。

我把resolv.conf里面乱写一个 IP，一样复现了你的情况。你VPS系统是什么？

**Comment by chika0801** [comment]
> 噢 我理解错了 能看一下服务端的 debug 日志？
[access.txt](https://github.com/XTLS/Xray-core/files/8667165/access.txt)
[error.txt](https://github.com/XTLS/Xray-core/files/8667166/error.txt)

**Comment by chika0801** [comment]
另一个VPS，用的一个DD脚本安装的debian11，只是用的HY，比如hy配置是1.1.1.1，resolv.conf是8.8.8.8，不会出现1楼现象。

可能真是xray这边，我目前发现在debian11上出的问题。

**Comment by vojeus** [comment]
用于测试的地址无返回。流程如下。
1. app/dns 查询内部dns未命中。
2. transport/internet/tcp 会直接使用域名进行链接。（这里会调用本地dns，但是查询仍是未命中）

**Comment by Hubedge** [comment]
> > 服务端把系统DNS设置为一个显然不是DNS服务的IP后，客户端浏览器仍然能正常上网，且测试显示只收到来自Cloudflare的查询，说明这一次系统DNS的查询不是必需的。
> 
> 我把resolv.conf里面乱写一个 IP，一样复现了你的情况。你VPS系统是什么？

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

**Comment by chika0801** [comment]
> 

服务端resolv.conf 的IP是 8.8.8.8，服务端 xray 内置DNS设置为一个非DNS服务的IP：

仍然能上网，但是能够明显感觉变慢，应该是在等待xray内置DNS超时然后使用系统DNS查询


我也遇到这现象

**Comment by Bearljj** [comment]
你们这个讨论的是服务端DNS问题，我同时发现客户端也会用Xray配置的DNS以外的本机DNS去查询，感觉这个更容易造成DNS泄露吧，毕竟客户端在墙内

**Comment by Hubedge** [comment]
同意，如果客户端也有这样的问题那就有点危险了。建议改成：如果设置了内置DNS，就只使用内置DNS查询，不使用系统DNS。

有人可以draft一个fix并PR到v2fly吗，或者我去把这个raise到v2fly？

**Comment by ZacharyRen77** [comment]
我也碰到了该问题，和系统应该是没关系的。我测试了centos7,ubuntu20,debian10，都出现了该现象。我还发现，xray版本为1.5.3的时候一切都很正常，当更新了1.5.4之后就会出现该现象，1.5.5也没有改善。

**Comment by WordsWorthLess** [comment]
我用openwrt, 通過iptables挾持了局域網内所有主機的DNS請求，然後用XRAY内建DNS分流，發現依然會出現DNS泄漏

**Comment by timi-owo** [comment]
有没有一种可能是没有配置 `SystemDialer` 的 `domainStrategy`
出入站的 `address` 如果填写的是域名，默认不进入 Xray 的内置 DNS 流程，直接交由系统 DNS 解析。

https://xtls.github.io/config/transport.html#sockoptobject
```
"streamSettings": {
	"sockopt": {
		"domainStrategy": "UseIP"
	}
}
```

**Comment by ccwater666** [comment]
这个问题最后是怎么解决的呢。我现在用最新版本的，好像还是可以复现这个问题。
