### ISSUE TITLE
反复出现 VMessAEAD is enforced and a non VMessAEAD connection is received. 

### ISSUE THREAD

**Issue by wangling12** [XTLS/Xray-core#1063]
两端均为1.5.5，且alterid均设为0之后，依旧反复出现该信息：

>  rejected  common/drain: common/drain: unable to drain connection > EOF > proxy/vmess/encoding: invalid user: VMessAEAD is enforced and a non VMessAEAD connection is received. You can still disable this security feature with environment variable xray.vmess.aead.forced = false . You will not be able to enable legacy header workaround in the future.

**Comment by yuhan6665** [comment]
有可能是主动探测或者网络随机攻击流量 不影响使用可以不管

**Comment by yuhan6665** [comment]
closing

**Comment by chika0801** [comment]
> 

你要不换v2fly的core再试试了

**Comment by yuhan6665** [comment]
> 影响使用,不是攻击流量,确定就是来自于客户端的流量.毕竟不是网断了,谁会去看日志呢... 添加`xray.vmess.aead.forced=false`之后已经一切正常了,先用着吧

你确定你客户端是xray 1.5.5？

**Comment by kang000feng** [comment]
> xray.vmess.aead.forced=false

请问楼主你升级到最新版本这个变量还能正常生效吗？ 

请教楼上各位开发者，这个变量名称是不是失效了？ 我升级到最新的版本1.8.23上 添加这个环境变量， 客户端关闭aead加密就会报错, 请问是更换的新的变量名称，还是说彻底停止对这个功能的支持？ 
xray.vmess.aead.forced=false

**Comment by Fangliding** [comment]
@kang000feng 去年就删掉了
