### ISSUE TITLE
爲什麽我的CPU占用特別高“？

### ISSUE THREAD

**Issue by 87502560** [XTLS/Xray-core#1064]
![image](https://user-images.githubusercontent.com/9465563/168327626-e2d87b33-566b-4fca-9e38-da49db05dba6.png)
同樣程序，其他服務器卻很正常，不知道爲啥？

**Comment by FranzKafkaYu** [comment]
> ![image](https://user-images.githubusercontent.com/9465563/168327626-e2d87b33-566b-4fca-9e38-da49db05dba6.png) 同樣程序，其他服務器卻很正常，不知道爲啥？

看样子是存在内存泄漏，物理内存与虚拟内存占用过高。看样子是通过x-ui进行搭建的，请问使用的是哪一个x-ui版本，xray core版本是多少，以及相关的系统版本信息

**Comment by 87502560** [comment]
> > ![image](https://user-images.githubusercontent.com/9465563/168327626-e2d87b33-566b-4fca-9e38-da49db05dba6.png) 同樣程序，其他服務器卻很正常，不知道爲啥？
> 
> 看样子是存在内存泄漏，物理内存与虚拟内存占用过高。看样子是通过x-ui进行搭建的，请问使用的是哪一个x-ui版本，xray core版本是多少，以及相关的系统版本信息

最新版本 0.3.2

**Comment by FranzKafkaYu** [comment]
> > > ![image](https://user-images.githubusercontent.com/9465563/168327626-e2d87b33-566b-4fca-9e38-da49db05dba6.png) 同樣程序，其他服務器卻很正常，不知道爲啥？
> > 
> > 
> > 看样子是存在内存泄漏，物理内存与虚拟内存占用过高。看样子是通过x-ui进行搭建的，请问使用的是哪一个x-ui版本，xray core版本是多少，以及相关的系统版本信息
> 
> 最新版本 0.3.2

还有xray core 版本，节点信息等等

**Comment by 87502560** [comment]
> > ![image](https://user-images.githubusercontent.com/9465563/168327626-e2d87b33-566b-4fca-9e38-da49db05dba6.png) 同樣程序，其他服務器卻很正常，不知道爲啥？
> 
> 看样子是存在内存泄漏，物理内存与虚拟内存占用过高。看样子是通过x-ui进行搭建的，请问使用的是哪一个x-ui版本，xray core版本是多少，以及相关的系统版本信息

xray core版本怎麽看的?有命令嗎?

**Comment by FranzKafkaYu** [comment]
> 

面板首页有一个xray状态，后面的就是版本号信息

**Comment by 87502560** [comment]
> 

xray 状态: running 1.4.2

**Comment by FranzKafkaYu** [comment]
> > 
> 
> xray 状态: running 1.4.2

请更新到最新版本试试是否有所缓解

**Comment by 87502560** [comment]
真的可以,非常感謝!!!!!

**Comment by 87502560** [comment]
> > > 
> > 
> > 
> > xray 状态: running 1.4.2
> 
> 请更新到最新版本试试是否有所缓解

最新版的好像不行，客戶端無法上網，上升了一個版本可以了。謝謝codeerfanbaby,請收下我的感謝！
