### ISSUE TITLE
为什么我的不能翻墙了？请大神指教

### ISSUE THREAD

**Issue by ccerty** [XTLS/Xray-core#1065]
买的英国VPS，广播IP，搭好服务端后，电脑端用V2rayN连接，可以ping通、TCPing也能通，ssh能正常连接，但就是不能翻墙，测试真连接延迟显示操作超时。手机也用不了这个节点。请教下各位大神是什么原因，同样搭建方法在别的vps上可以翻墙，就这个不行，不知道是哪里出了问题，是VPS的原因吗？

**Comment by chika0801** [comment]
你要不加xray的tg群来群里问。或找个你认识的懂的网友发他ip root 密码找人帮你看看。

**Comment by ccerty** [comment]
> 你要不加xray的tg群来群里问。或找个你认识的懂的网友发他ip root 密码找人帮你看看。

新手上路，还不会用这些，大神有时间能帮我看下吗

**Comment by chika0801** [comment]
> > 你要不加xray的tg群来群里问。或找个你认识的懂的网友发他ip root 密码找人帮你看看。
> 
> 新手上路，还不会用这些，大神有时间能帮我看下吗

你也要注册个tg，来加xray的tg群。不可能qqwx联系你吧。

**Comment by xqzr** [comment]
log

**Comment by yuhan6665** [comment]
closing
