### ISSUE TITLE
openwrt 透明代理

### ISSUE THREAD

**Issue by wilinz** [XTLS/Xray-core#1067]
iptables -t mangle -A XRAY -p tcp -j TPROXY --on-port 12345 --tproxy-mark 1

为啥报错
iptables v1.8.7 (legacy): unknown option "--on-port"
Try `iptables -h' or 'iptables --help' for more information.

**Comment by churchmice** [comment]
iptables-mod-tproxy
装了没有？

**Comment by yuhan6665** [comment]
not a xray issue. Closing
