### ISSUE TITLE
【问题已解决，希望改进文档】关于采用xtls加密的情况下，使用ip地址建立与xray服务器连接的问题

### ISSUE THREAD

**Issue by Memorywzd** [XTLS/Xray-core#1069]
### Discussed in https://github.com/XTLS/Xray-core/discussions/1068

<div type='discussions-op-text'>

<sup>Originally posted by **Memorywzd** May 17, 2022</sup>
使用环境：vps一台，Windows电脑一台，Android手机一部
服务端：
```
user@vps:~$ xray --version
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 linux/amd64)
A unified platform for anti-censorship.
```
客户端：`v2rayN v5.9` , `v2rayNG v1.7.3(Lib v23, Xray-core v1.5.4)`

使用情景：连接至vps的网络较为不稳定，白天正常稳定较低ping值，0丢包率；晚高峰时段跳ping严重，丢包严重（也许有大佬可以给出原因）
![image](https://user-images.githubusercontent.com/52624361/168642433-ae42f0f2-bd4d-4d59-9e0d-b652ba950aba.png)

由于vps接入了ipv4 & ipv6双栈网络，又注意到走ipv6的链路异常的稳定，ping值维持在一个可以接受的较高值（经查ipv6路由要比v4绕一些），但是丢包率可以做到近乎0，因此考虑在路由器端做自动切换，白天走ipv4，晚高峰走ipv6。

查阅[官方的配置文档](https://xtls.github.io/config/transport.html#tlsobject)（配置指南章-基础配置节-传输方式小节-StreamSettingsObject的TLSObject项）中有如下描述：

> TLSObject
> ```
> {
>   "serverName": "xray.com",
>   "rejectUnknownSni": false,
>   "allowInsecure": false,
>   "alpn": ["h2", "http/1.1"],
>   "minVersion": "1.2",
>   "maxVersion": "1.3",
>   "cipherSuites": "此处填写你需要的加密套件名称,每个套件名称之间用:进行分隔",
>   "certificates": [],
>   "disableSystemRoot": false,
>   "enableSessionResumption": false,
>   "fingerprint": ""
> }
> ```
> `serverName: string`
> 
> 指定服务器端证书的域名，在连接由 IP 建立时有用。
> 
> 当目标连接由域名指定时，比如在 Socks 入站接收到了域名，或者由 Sniffing 功能探测出了域名，这个域名会自动用于 serverName，无须手动配置。

于是在服务器中进行如下配置：
使用xray监听443端口，vless协议，回落至nginx防探测；重点考察xtls配置如下
```
"streamSettings": {
          "network": "tcp",
          "security": "xtls",
          "xtlsSettings": {
            "allowInsecure": false, // 正常使用应确保关闭
            "minVersion": "1.2", // TLS 最低版本设置
            "serverName": "**** domain.name ****",
            "alpn": ["http/1.1"],
            "certificates": [
              {
                "certificateFile": "/path/to/cert/file.crt",
                "keyFile": "/path/to/key/file.key"
              }
            ]
          }
        }
```
完成配置后重启xray，在客户端配置处将服务器地址填写为ip取代域名，测试服务不可用。
Windows端v2rayN报：`基础连接已关闭：发送时发生错误`
Android端v2rayNG报：`io: read/write on closed pipe `；偶尔在日志中会看到`tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config`字样。该错误提示难以稳定复现，仅偶然出现在日志中。
另：仅将客户端的”地址“配置由具体ip地址改回域名则无任何问题，故排除客户端配置错误，不再提供具体配置信息。

搜了一圈issue里面好像没有相关的，感觉应该不是bug，也许是我配置错了，就没敢开issue，在这里请大家指导
</div>

解决方案：在客户端添加证书所签发给的域名至"SNI”项目。

希望在相应文档中增加此说明。

**Comment by yuhan6665** [comment]
closing
