### ISSUE TITLE
大佬能否编译个OPENWRT-x86-64版啊，N多软路由用户都需要。。。

### ISSUE THREAD

**Issue by FatDNA** [XTLS/Xray-core#107]
谢谢大佬们的XRay项目，性能确实比原版V2Ray要强，如能发布最多软路由用户使用的openwrt-x86-64版，实在功德无量。。。

**Comment by AkinoKaede** [comment]
如果您需要二進制檔的話 linux-64 就是，如果您需要軟體包這個有待討論

**Comment by FatDNA** [comment]
> 如果您需要二進制檔的話 linux-64 就是，如果您需要軟體包這個有待討論

谢谢大佬指点，我不知道LUNUX-64版能在openwrt运行。

**Comment by kiggc** [comment]
ssr+   passwall等工具都支持啊，如果不会编译  可以到这个网站下载  https://openwrt.download/  
比如ssr+   https://openwrt.download/R20.12.17/packages/x86_64/helloworld/luci-app-ssr-plus_181-4_all.ipk
也可以手动命令行启动  比如下面保存sh文件运行

#!/bin/bash
screen -dmS xray
screen -x -S xray -p 0 -X stuff "/root/xray --config=/root/xray.json"
screen -x -S xray -p 0 -X stuff $'\n'

**Comment by FatDNA** [comment]
> ssr+ passwall等工具都支持啊，如果不会编译 可以到这个网站下载 https://openwrt.download/
> 比如ssr+ https://openwrt.download/R20.12.17/packages/x86_64/helloworld/luci-app-ssr-plus_181-4_all.ipk
> 也可以手动命令行启动 比如下面保存sh文件运行
> 
> #!/bin/bash
> screen -dmS xray
> screen -x -S xray -p 0 -X stuff "/root/xray --config=/root/xray.json"
> screen -x -S xray -p 0 -X stuff $'\n'

谢谢大佬告知。一直在使用openwrt-v2ray项目，但这位大佬暂时还未开xray项目。

**Comment by kiggc** [comment]
![image](https://user-images.githubusercontent.com/74247387/103151952-c554eb80-47bd-11eb-91b1-af545317c875.png)

ssr+ 早就支持xray了  现在新版本把xray隐藏了  选择vless +xtls会自动调用/usr/bin/xray/ 下的xray文件

**Comment by rprx** [comment]
@kiggc 好像是编译时选带什么吧，VMess 也是 Xray 了

**Comment by FatDNA** [comment]
非常感谢各位v2ray系列项目大佬们的辛勤付出！[https://tse3-mm.cn.bing.net/th/id/OIP.QFE0eDyyn5-7g_qC0YeTlwHaG3?pid=Api&rs=1](url)
