### ISSUE TITLE
Server 端的 Xray 进程，正常运行1周后，突然 panic 然后就挂了。

### ISSUE THREAD

**Issue by mclovin-2k** [XTLS/Xray-core#108]
XRAY 版本 ：1.1.4。
VPS OS：Debian 10 x64

日志：
Dec 19 11:11:40 localhost.localdomain xray[1136]: 2020/12/19 11:11:40 [Info] main/jsonem: Reading config: /usr/local/etc/xray/reverse.json
Dec 19 11:11:40 localhost.localdomain xray[1136]: 2020/12/19 11:11:40 [Info] main/jsonem: Reading config: /usr/local/etc/xray/routing.json
Dec 19 11:11:40 localhost.localdomain xray[1136]: 2020/12/19 11:11:40 [Info] main/jsonem: Reading config: /usr/local/etc/xray/stats.json
Dec 19 11:11:40 localhost.localdomain xray[1136]: 2020/12/19 11:11:40 [Info] main/jsonem: Reading config: /usr/local/etc/xray/transport.json
Dec 27 11:03:21 localhost.localdomain xray[1136]: panic: extending out of bound
Dec 27 11:03:21 localhost.localdomain xray[1136]: goroutine 1207593 [running]:
Dec 27 11:03:21 localhost.localdomain xray[1136]: github.com/xtls/xray-core/common/buf.(*Buffer).Extend(...)
Dec 27 11:03:21 localhost.localdomain xray[1136]:         github.com/xtls/xray-core/common/buf/buffer.go:79
Dec 27 11:03:21 localhost.localdomain xray[1136]: github.com/xtls/xray-core/common/mux.FrameMetadata.WriteTo(0x100ff60, 0xc0008d9730, 0x300500000, 0xc002010001, 0xc0005088a0, 0xc00046bcf0, 0xc00045efc0)
Dec 27 11:03:21 localhost.localdomain xray[1136]:         github.com/xtls/xray-core/common/mux/frame.go:64 +0x6cb
Dec 27 11:03:21 localhost.localdomain xray[1136]: github.com/xtls/xray-core/common/mux.writeMetaWithFrame(0xff80a0, 0xc0001a1fe0, 0x100ff60, 0xc0008d9730, 0x300460000, 0x2010001, 0xc00046bd58, 0x1, 0x1, 0x1, ...)
Dec 27 11:03:21 localhost.localdomain xray[1136]:         github.com/xtls/xray-core/common/mux/writer.go:66 +0x106
Dec 27 11:03:21 localhost.localdomain xray[1136]: github.com/xtls/xray-core/common/mux.(*Writer).writeData(0xc000521110, 0xc00046bd58, 0x1, 0x1, 0x0, 0x0)
Dec 27 11:03:21 localhost.localdomain xray[1136]:         github.com/xtls/xray-core/common/mux/writer.go:83 +0xf6
Dec 27 11:03:21 localhost.localdomain xray[1136]: github.com/xtls/xray-core/common/mux.(*Writer).WriteMultiBuffer(0xc000521110, 0xc00049f048, 0x0, 0x0, 0x0, 0x0)
Dec 27 11:03:21 localhost.localdomain xray[1136]:         github.com/xtls/xray-core/common/mux/writer.go:103 +0x18d
Dec 27 11:03:21 localhost.localdomain xray[1136]: github.com/xtls/xray-core/common/buf.copyInternal(0xff9fc0, 0xc000b52948, 0xff8ec0, 0xc000521110, 0xc0008d4320, 0xc000b52948, 0xff8ec0)
Dec 27 11:03:21 localhost.localdomain xray[1136]:         github.com/xtls/xray-core/common/buf/copy.go:87 +0x19e
Dec 27 11:03:21 localhost.localdomain xray[1136]: github.com/xtls/xray-core/common/buf.Copy(0xff9fc0, 0xc000b52948, 0xff8ec0, 0xc000521110, 0x0, 0x0, 0x0, 0x4550cb, 0x2277ca7024047)
Dec 27 11:03:21 localhost.localdomain xray[1136]:         github.com/xtls/xray-core/common/buf/copy.go:104 +0xa8
Dec 27 11:03:21 localhost.localdomain xray[1136]: github.com/xtls/xray-core/common/mux.fetchInput(0x100eb60, 0xc000521080, 0xc0005210b0, 0xff80a0, 0xc0001a1fe0)
Dec 27 11:03:21 localhost.localdomain xray[1136]:         github.com/xtls/xray-core/common/mux/client.go:261 +0x56c
Dec 27 11:03:21 localhost.localdomain xray[1136]: created by github.com/xtls/xray-core/common/mux.(*ClientWorker).Dispatch
Dec 27 11:03:21 localhost.localdomain xray[1136]:         github.com/xtls/xray-core/common/mux/client.go:301 +0xfa
Dec 27 11:03:21 localhost.localdomain systemd[1]: xray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 27 11:03:21 localhost.localdomain systemd[1]: xray.service: Failed with result 'exit-code'.

19号11点启动的，27号11点挂了。中间似乎也没有什么异常。

**Comment by rprx** [comment]
这算是成功遇到了 Mux 的 BUG？

**Comment by mclovin-2k** [comment]
> 这算是成功遇到了 Mux 的 BUG？

需要我提供什么东西呢？这个BUG能修吗？

**Comment by rprx** [comment]
应该是遇到了极端情况，导致 Mux 在调用 buffer 的 Extend 时剩余空间不够而 panic 了，以前遇到意外退出会自动重启。

原本的 Mux 已是快 deprecated 的状态，大概不会进行修改，但可以改进处理意外情况的方式。

**Comment by mclovin-2k** [comment]
> 应该是遇到了极端情况，导致 Mux 在调用 buffer 的 Extend 时剩余空间不够而 panic 了，以前遇到意外退出会自动重启。
> 
> 原本的 Mux 已是快 deprecated 的状态，大概不会进行修改，但可以改进处理意外情况的方式。

OK。那就不管了。
