### ISSUE TITLE
app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp IP: i/o timeout dial tcp IP: operation was canceled] > common/retry: all retry attempts failed

### ISSUE THREAD

**Issue by pojkoo340** [XTLS/Xray-core#1080]
This error is happening for all connections for like 10-15 minutes, then everything works fine for 10-15 minutes. Then it repeats like this (working - not working) again and again.

**Server config:**

{
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "block"
      },
      {
        "type": "field",
        "domain": [
          "geosite:category-ads-all"
        ],
        "outboundTag": "block"
      }
    ]
  },
  "inbounds": [
    {
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "id here",
            "flow": "xtls-rprx-direct"
          }
        ],
        "decryption": "none"
 },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
          "minVersion": "1.2",
          "certificates": [
            {
              "certificateFile": "/usr/local/etc/xray/cert.pem",
              "keyFile": "/usr/local/etc/xray/key.pem"
            }
          ]
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": ["http","tls"]
      }
    }
  ],
  "outbounds": [
    {
      "tag": "direct",
      "protocol": "freedom"
    },
    {
      "tag": "block",
      "protocol": "blackhole"
    }
  ]
}

**Client config:**
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "socks",
      "port": 10809,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "allowTransparent": false
      }
    },
    {
      "tag": "http",
      "port": 10810,
      "listen": "127.0.0.1",
      "protocol": "http",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "allowTransparent": false
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "my IP here",
            "port": 443,
            "users": [
              {
                "id": "my id here",
                "alterId": 0,
                "email": "t@t.tt",
                "security": "auto",
                "encryption": "none",
                "flow": "xtls-rprx-direct"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
          "allowInsecure": false,
          "serverName": "my domain here"
        }
      },
      "mux": {
        "enabled": false,
        "concurrency": -1
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    }
  ],
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "domainMatcher": "linear",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "enabled": true
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": [
          "domain:example-example.com",
          "domain:example-example2.com"
        ],
        "enabled": true
      },
      {
        "type": "field",
        "outboundTag": "block",
        "domain": [
          "geosite:category-ads-all"
        ],
        "enabled": true
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": [
          "geosite:cn"
        ],
        "enabled": true
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "geoip:private",
          "geoip:cn"
        ],
        "enabled": true
      },
      {
        "type": "field",
        "port": "0-65535",
        "outboundTag": "proxy",
        "enabled": true
      }
    ]
  }
}

I don't know how to use Markdown yet so it looks ugly, sorry.

People already told me that both configs are absolutely fine.

I haven't even installed nginx for the domain, just used the xray-yes script. Maybe it is the solution? Or nginx is not necessary?

**Comment by yuhan6665** [comment]
Sounds like GFW interference or networking issue. Suggest to try different protocols and not at 晚高峰

**Comment by jojeee1** [comment]
I have exactly the same problem. 15-20 minutes everything works fine, but then it stops working for 15-20 minutes and after that everything works again. Is there a solution to this problem? The problem is when I use vless tcp xtlc.

**Comment by pojkoo340** [comment]
Yes, the problem was that the 443 port on Digital Ocean is being blocked by the russian state internet censorship. I've changed the port and everything is fine. So that problem is always external, I suppose.

**Comment by jojeee1** [comment]
> Yes, the problem was that the 443 port on Digital Ocean is being blocked by the russian state internet censorship. I've changed the port and everything is fine. So that problem is always external, I suppose.

Большее спасибо за ответ. Я из России... У меня тоже всё заработало после смены порта.

**Comment by jojeee1** [comment]
> > > Yes, the problem was that the 443 port on Digital Ocean is being blocked by the russian state internet censorship. I've changed the port and everything is fine. So that problem is always external, I suppose.
> > 
> > 
> > Большее спасибо за ответ. Я из России... У меня тоже всё заработало после смены порта.
> 
> А где у вас VPS находится, если не секрет? Тоже DO или еще где-то?

Тоже DO, нидерланды. Сейчас кстати заработало снова на 433 порту.

**Comment by yuzhihun** [comment]
遇到同样的问题，修改端口后可以正常链接

**Comment by shadowericq** [comment]
修改端口后可以正常链接

**Comment by radian-rgc** [comment]
How can change the port ?
mean i have to change the VPS location ?

This is my config:

```
{
  "log": {
    "loglevel": "warning",
    "access": "/var/log/v2ray/access.log", 
    "error": "/var/log/v2ray/error.log"
  },
  "inbounds": [{
    "port": 10000,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "4db99e96-xxxxx-xxxx-b1fb-xxxxxxxx",
          "level": 1,
          "alterId": 64
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "wsSettings": {
        "path": "/vroom"
      }
    }
  }],
  "outbounds": [{
    "protocol": "freedom",
    "settings": {}
  },{
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  }],
  "routing": {
    "rules": [
      {
        "type": "field",
        "ip": ["geoip:private"],
        "outboundTag": "blocked"
      }
    ]
  }
}

```

**Comment by Hatef-Rostamkhani** [comment]
> 

"port": 10000,

for example change to 80 and disable firewall

"port": 80,

**Comment by eng-reza** [comment]
Hi dear hatef 
i'm faced to this problem too, so please tell me how can i change the port that you said? thank you

**Comment by Hatef-Rostamkhani** [comment]
> Hi dear hatef i'm faced to this problem too, so please tell me how can i change the port that you said? thank you

Hi dear , In inbounds section , change the port 

for example :

"inbounds": [{
    "port": 443,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "4db99e96-xxxxx-xxxx-b1fb-xxxxxxxx",
          "level": 1,
          "alterId": 64
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "wsSettings": {
        "path": "/vroom"
      }
    }

**Comment by Jacky9520** [comment]
> 遇到同样的问题，修改端口后可以正常链接

请问下这个到底是什么原因造成的，端口被墙？有没有一劳永逸的办法？

**Comment by RookieTerry** [comment]
人在海外，可以排除GFW的原因，用电脑端的v2rayn连接另一个国家的节点服务器同样遇到这种错误

**Comment by I-y6o-I** [comment]
> > > > Yes, the problem was that the 443 port on Digital Ocean is being blocked by the russian state internet censorship. I've changed the port and everything is fine. So that problem is always external, I suppose.
> > > 
> > > 
> > > Большее спасибо за ответ. Я из России... У меня тоже всё заработало после смены порта.
> > 
> > 
> > А где у вас VPS находится, если не секрет? Тоже DO или еще где-то?
> 
> Тоже DO, Нидерланды. Сейчас кстати заработало снова на 443 порту.

У вас не возникает просадок по скорости? У меня тоже сервер на DO, до сих пор не нашел решение.

**Comment by h0rper** [comment]
@I-y6o-I , не знаю, решили ли вы проблему, НО. Мне на винде помогло удаление всех лишних сетевых адаптеров, включая неиспользуемый Wifi (просто удалил все, кроме самого PCIE). Проще говоря, чтобы остался лишь один включённый.
