### ISSUE TITLE
求xray的API命令行参数adi、ado、rmi、rmo详解

### ISSUE THREAD

**Issue by a108393** [XTLS/Xray-core#1082]
<img width="778" alt="WechatIMG1383" src="https://user-images.githubusercontent.com/91522471/170838861-fe54047c-af28-46ef-b808-25e9ffe1682c.png">

版本/version: xray 1.4.2
操作系统/OS: centos
我想通过command命令来操作xray，请求帮助。
譬如  xray api adi [--server=127.0.0.1:8080] <c1.json> [c2.json]...
c1.json和c2.json怎么写？

求api下的adi、ado、rmi、rmo的json详细的参数示例！感谢！！

**Comment by tsosunchia** [comment]
@a108393 1. 有  Discussions 区就是不用😅
2. 这种Google一下就能查到的问题就不要问了

**Comment by a108393** [comment]
> 

非常感谢你的回复！！！
真的是没有google到，所以才发出提问的。也到了v2ray里面查过，还有x-ui也查过，都没有找到详细的说明。

我这就挪到discuzz里去。再次感谢！

**Comment by a108393** [comment]
@tsosunchia 
非常感谢你的回复！！！
真的是没有google到，所以才发出提问的。也到了v2ray里面查过，还有x-ui也查过，都没有找到详细的说明。

我这就挪到discuzz里去。再次感谢！

**Comment by a108393** [comment]
@tsosunchia 实在是查了好几天没找到才发贴的，抱歉，感谢！
