### ISSUE TITLE
Mac OS Qv2ray 在升级内核至1.55及以上版本后，系统 Warning报错

### ISSUE THREAD

**Issue by daehub** [XTLS/Xray-core#1086]
Mac OS 系统在使用 Qv2ray 时，Xray内核升级至1.55及以上版本后，系统一直出现Warning报错，内容如下：

2022/05/30 09:32:10 [Warning] [3323097023] app/proxyman/inbound: connection ends > proxy/http: connection ends > proxy/http: failed to write response > write tcp 127.0.0.1:8889->127.0.0.1:55936: write: protocol wrong type for socket
2022/05/30 09:32:10 127.0.0.1:56120 accepted http://r3.o.lencr.org/MFgwVqADAgEAME8wTTBLMAkGBSsOAwIaBQAEFEjayaD7K9MtT%2FDeaNL1Z7c1%2BbPEBBQULrMXt1hWy65QCUDmH6%2BdixTCxgISBJFEnIdxJ5QwNwVEgmNx0Jm9 [http_IN >> ABLENET]
2022/05/30 09:32:10 [Warning] [3634672517] app/proxyman/inbound: connection ends > proxy/http: connection ends > proxy/http: failed to write response > write tcp 127.0.0.1:8889->127.0.0.1:55915: write: broken pipe
2022/05/30 09:32:10 [Warning] [224221934] app/proxyman/inbound: connection ends > proxy/http: connection ends > proxy/http: failed to write response > write tcp 127.0.0.1:8889->127.0.0.1:55932: write: broken pipe
2022/05/30 09:32:10 127.0.0.1:56122 accepted http://r3.o.lencr.org/MFgwVqADAgEAME8wTTBLMAkGBSsOAwIaBQAEFEjayaD7K9MtT%2FDeaNL1Z7c1%2BbPEBBQULrMXt1hWy65QCUDmH6%2BdixTCxgISBJFEnIdxJ5QwNwVEgmNx0Jm9 [http_IN >> ABLENET]
2022/05/30 09:32:10 [Warning] [1417786523] app/proxyman/inbound: connection ends > proxy/http: connection ends > proxy/http: failed to write response > write tcp 127.0.0.1:8889->127.0.0.1:55938: write: broken pipe
2022/05/30 09:32:10 [Warning] [647242928] app/proxyman/inbound: connection ends > proxy/http: connection ends > proxy/http: failed to write response > write tcp 127.0.0.1:8889->127.0.0.1:55934: write: broken pipe
2022/05/30 09:32:10 127.0.0.1:56124 accepted http://r3.o.lencr.org/MFgwVqADAgEAME8wTTBLMAkGBSsOAwIaBQAEFEjayaD7K9MtT%2FDeaNL1Z7c1%2BbPEBBQULrMXt1hWy65QCUDmH6%2BdixTCxgISBJFEnIdxJ5QwNwVEgmNx0Jm9 [http_IN >> ABLENET]
2022/05/30 09:32:10 [Warning] [2437789276] app/proxyman/inbound: connection ends > proxy/http: connection ends > proxy/http: failed to write response > write tcp 127.0.0.1:8889->127.0.0.1:55928: write: broken pipe

服务端无论使用1.55前版本还是1.55后版本，都出现同样报错，结果是系统负载过大，虽然功能正常，但是不具备使用条件。

由于1.55版本后，内梳修改较大，看错误日志，感觉客户端在请求验证证书。服务端的确使用了Let's Encrypt域名证书，但是之前版本不会出现以上问题。

我想请教各位大神，是不是我的系统配置缺少某些配置项引起的呢，望指教。

**Comment by yuhan6665** [comment]
1.5.5 好像没有相关改动

不一定跟 warning 日志相关 所以问题具体表现是什么 建议多测试 例如不同版本 不同设备

> 系统负载过大，虽然功能正常，但是不具备使用条件

**Comment by Rangtian** [comment]
Qv2ray不是停更好久了么？

**Comment by flowercoder** [comment]
不要用Qv2ray，建议用小火箭，无界面的可以用Txray

**Comment by yuhan6665** [comment]
close as invalid
