### ISSUE TITLE
如何将访问转为QUIC

### ISSUE THREAD

**Issue by genufish** [XTLS/Xray-core#1087]
场景：服务器仅支持QUIC，命令行程序只支持HTTP/1.1
想建立一个代理将http/1.1连接转为quic发往后端
在可以使用自签发证书的情况下配置文件该怎么写
尝试dokodemo-door加freedom似乎不对

`{
    "port": 1090,
    "listen": "127.0.0.1",
    "protocol": "dokodemo-door",
    "settings": {
      "network": "tcp",
      "address": "127.0.0.1",
      "port": 80,
      "followRedirect": true
    },
    "sniffing": {
      "enabled": true,
      "destOverride": ["http", "tls"]
    },
    "streamSettings": {
      "security": "tls",
      "tlsSettings": {
        "alpn": ["http/1.1"],
        "certificates": [
          {
            "usage": "issue",
            "certificate": [
              "-----BEGIN CERTIFICATE-----",
              "-----END CERTIFICATE-----"
            ],
            "key": [
              "-----BEGIN RSA PRIVATE KEY-----",
              "-----END RSA PRIVATE KEY-----"
            ]
          }
        ]
      }
  ｝
}

{
    "protocol": "freedom",
    "settings": {
      "redirect": ":443"
    },
    "streamSettings": {
      "network":"quic",
      "security": "tls",
      "tlsSettings": {
        "alpn": ["h3-29"],
        "allowInsecure": true
      },
      "quicSettings":{
        "security": "none",
        "header": {
          "type": "none"
        }
      }
    }
  }

`

**Comment by yuhan6665** [comment]
你的命令行和服务端必须互相支持 代理不改变原流量
