### ISSUE TITLE
如何ipv6入站，ipv4出站

### ISSUE THREAD

**Issue by Sweetestcc** [XTLS/Xray-core#1088]
本地ipv6带宽更大，想用ipv6连接代理服务器，然后走ipv4访问目标网站，请问如何做到？

在inbound填写v6地址，outbound使用UseIPv4就可以吗
服务器是双栈服务器

**Comment by chika0801** [comment]
客户端地址填vps的v6地址。服务器的配置文件无特别的地方。

**Comment by mclovin-2k** [comment]
有两个方法：
1. server 的 freedom outbound 写 UseIPv4。
2. 修改 server 的路由策略为 IPv4 优先。

**Comment by Sweetestcc** [comment]
> 有两个方法：
> 
> 1. server 的 freedom outbound 写 UseIPv4。
> 2. 修改 server 的路由策略为 IPv4 优先。

我尝试一下

**Comment by chika0801** [comment]
> > 客户端地址填vps的v6地址。服务器的配置文件无特别的地方。
> 
> 这样回程也是走ipv6吗

j是
