### ISSUE TITLE
SS疑似有bug，speedtest測速會瞬間讓程序掛掉

### ISSUE THREAD

**Issue by kousyougi** [XTLS/Xray-core#109]
1.1.5版的xray，用下面的設定。可以正常上網。但用Speedtest測速會瞬間掛掉。
Server端裝在 Debian 10 跟在 Openwrt X86-64 測試都是一樣的反應。

![unnamed](https://user-images.githubusercontent.com/43228565/103180798-31297800-48d4-11eb-995a-f23a3b2a3e95.png)

{
  "inbounds": [
    {
            "listen": "0.0.0.0",
            "port": 10024,
            "protocol": "shadowsocks",
            "settings": {
                "method": "chacha20-ietf-poly1305",
                "password": "123456789",
                "network": "tcp,udp"
            }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}

**Comment by badO1a5A90** [comment]
有挂掉时候的日志吗？

**Comment by kousyougi** [comment]
● xray.service - Xray Service
   Loaded: loaded (/etc/systemd/system/xray.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-12-28 11:24:15 CST; 15s ago
     Docs: https://github.com/xtls
  Process: 1171 ExecStart=/etc/xray/xray run -config /etc/xray/config.json (code=exited, status=2)
 Main PID: 1171 (code=exited, status=2)

Dec 28 11:24:15 vm245398 xray[1171]: github.com/xtls/xray-core/proxy/shadowsocks.(*Server).handlerUDPPayload(0xc000238780, 0x10952e0, 0xc000426480, 0x109d860, 0xc00042c600, 0x1095960, 0xc0002422e0, 0
Dec 28 11:24:15 vm245398 xray[1171]:         github.com/xtls/xray-core/proxy/shadowsocks/server.go:144 +0x61f
Dec 28 11:24:15 vm245398 xray[1171]: github.com/xtls/xray-core/proxy/shadowsocks.(*Server).Process(0xc000238780, 0x10952e0, 0xc000426480, 0x3, 0x109d860, 0xc00042c600, 0x1095960, 0xc0002422e0, 0x1000
Dec 28 11:24:15 vm245398 xray[1171]:         github.com/xtls/xray-core/proxy/shadowsocks/server.go:66 +0x190
Dec 28 11:24:15 vm245398 xray[1171]: github.com/xtls/xray-core/app/proxyman/inbound.(*udpWorker).callback.func1(0x0, 0x0, 0x0, 0x1096720, 0xc000481530, 0x30042dd5a, 0xc00011f680, 0xc00042c600, 0x1096
Dec 28 11:24:15 vm245398 xray[1171]:         github.com/xtls/xray-core/app/proxyman/inbound/worker.go:307 +0x23c
Dec 28 11:24:15 vm245398 xray[1171]: created by github.com/xtls/xray-core/app/proxyman/inbound.(*udpWorker).callback
Dec 28 11:24:15 vm245398 xray[1171]:         github.com/xtls/xray-core/app/proxyman/inbound/worker.go:292 +0x286
Dec 28 11:24:15 vm245398 systemd[1]: xray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 28 11:24:15 vm245398 systemd[1]: xray.service: Failed with result 'exit-code'.

完整error.log
[x-error.log](https://github.com/XTLS/Xray-core/files/5745777/x-error.log)

下面是設定

{
  "log": {
    "loglevel": "debug",
    "access": "/tmp/x-access.log",
    "error": "/tmp/x-error.log"
  },
  "inbounds": [
    {
            "listen": "0.0.0.0",
            "port": 10024,
            "protocol": "shadowsocks",
            "settings": {
                "method": "chacha20-ietf-poly1305",
                "password": "123456789",
                "network": "tcp,udp"
            }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}

**Comment by xianren78** [comment]
估计还是udp的锅

**Comment by rprx** [comment]
是 v1.1.5 的 UDP FullCone 改造导致的，但是该问题触发概率极低，试试这个版本 https://t.me/projectXray/111998

**Comment by kousyougi** [comment]
> 是 v1.1.5 的 UDP FullCone 改造导致的，但是该问题触发概率极低，试试这个版本 https://t.me/projectXray/111998

上面這個版本沒掛掉，可以滿速跑。

**Comment by rprx** [comment]
感谢测试与反馈 https://github.com/XTLS/Xray-core/commit/13ad3fddf6f7ff01fe9541b6c9f2dca6f7f87e4b
