### ISSUE TITLE
入站如何监听指定IP地址？

### ISSUE THREAD

**Issue by CCCAUCHY** [XTLS/Xray-core#1090]
入站如何监听指定IP地址？写`"listen": "192.168.1.xxx"`会报错

**Comment by denwork** [comment]
"inbounds": [
    {
      "port": 8387,
      "listen": "192.168.1.100", #需要是主机上存在的ip地址
      "protocol": "shadowsocks",
      "settings": {
        "method": "AES-256-GCM",
        "network": "tcp,udp",
        "ivCheck": true,
        "password": "xxxxxxx"
      }
    }
]

**Comment by yuhan6665** [comment]
https://unix.stackexchange.com/questions/127723/what-are-the-benefits-of-using-several-ip-addresses-on-a-server

**Comment by yuhan6665** [comment]
closing
