### ISSUE TITLE
关于证书的问题

### ISSUE THREAD

**Issue by someonewating** [XTLS/Xray-core#1098]
我想请教一下，为什么vless + tcp + xtls的配置方案中的证书文件必须是证书链文件？
在我初步配置里我使用了cloudflare提供的证书和密钥，但是服务器端error.log中报错bad certificate。在替换了Let's encrypt的fullchain.crt证书和私钥后即可正常工作。
请问为什么一定需要证书链文件而不能是普通的证书文件？因为我用过cloudflare的证书成功搭建过https，所以很不解为什么xray不能用cloudflare的证书。请赐教。

**Comment by gitsang** [comment]
不用证书链吧，把 allowInsecure 加上就好了，自签名应该都行

**Comment by someonewating** [comment]
谢谢你的回复。我已经搞清楚了，由于cloudflare的origin certificate是一个自签名证书，只被cloudflare的CDN信任，client不会信任，所以allowinsecure必须为true。From: ***@***.*** ***@***.***> on behalf of Sangriot ***@***.***>Sent: Tuesday, June 7, 2022, 4:09 PMTo: Xray-core ***@***.***>Cc: 1870828369 ***@***.***>; author ***@***.***>Subject: Re: [XTLS/Xray-core] 关于证书的问题 (Issue #1098)

不用证书链吧，把 allowInsecure 加上就好了，自签名应该都行

**Comment by lhbdhr** [comment]
> 谢谢你的回复。 我已经搞清楚了，由于cloudflare的origin certificate是一个自签名证书，只被cloudflare的CDN信任，client不会信任，所以allowinsecure必须为true。

然而 v2rayng 必须为fullchain证书，要么就跳过验证，否则不能用。

**Comment by chika0801** [comment]
楼上正解，不然你会遇到v2rayn上通ng上不通的现象。
