### ISSUE TITLE
没有xray.service了？

### ISSUE THREAD

**Issue by GleenJi** [XTLS/Xray-core#110]
大佬们，如果以后不再提供xray.service文件，对于喜欢自己手动安装的该怎么知道xray.service文件内容有变化啊，还是说.service文件内容不会变化了直接用v1.1.3的就行了😂

**Comment by xianren78** [comment]
service文件变化应该不大，能启动就行了吧。

**Comment by xiaoyaoyuxin** [comment]
用root版的脚本即可~

**Comment by rprx** [comment]
https://github.com/XTLS/Xray-install/blob/main/install-release.sh#L491

**Comment by GleenJi** [comment]
> 
> 
> https://github.com/XTLS/Xray-install/blob/main/install-release.sh#L491

谢谢，之前看到过，我忘了，抱歉👍
