### ISSUE TITLE
b站手机端可加载但无法播放视频

### ISSUE THREAD

**Issue by Sweetestcc** [XTLS/Xray-core#1101]
A服务器用nginx将流量转发到B服务器的vmess端口，通过B服务器解锁港澳台，但是直连B服务器的时候没有问题。（由于B服务器的动态IP被ban了，才出此办法），有无大神求解

**Comment by Sweetestcc** [comment]
> 

好像不是这个问题，pc端是没有问题的，手机端仅仅是视频无法播放一直显示正在缓冲，番剧就是进度条加载出来但无法播放，但评论，图片什么的都可以加载出来，加了国内直连的路由也还是如此

**Comment by qist** [comment]
有没有配置去广告。你看看日志。浏览器开启移动设备模式。去看看

**Comment by Sweetestcc** [comment]
> 有没有配置去广告。你看看日志。浏览器开启移动设备模式。去看看

没有配置去广告
看了一下accepted的ip，pc和app端被解析到不同的地方，pc走美国akamai，上海腾讯云
而app端走到新加坡akamai，再到上海阿里云
我翻了一下有个人好像也有这个问题，他也提到了手机被解析到阿里云的问题

**Comment by Sweetestcc** [comment]
另提一下，我从另一个商家搞了一台新的可以直连，也偶尔出现此问题

**Comment by qist** [comment]
你在墙外还是国内，国内不建议走外面绕一圈回来，配置好分流。

**Comment by Sweetestcc** [comment]
> 你在墙外还是国内，国内不建议走外面绕一圈回来，配置好分流。

人在国内，其实我不太懂分流的设置，查了一下别人的配置方法也各不相同
然后发现这个问题仅会在app上出现，手机浏览器也是没有问题的

**Comment by qist** [comment]
app 内置dns 解析了。建议找个好点的客户端，其实与服务器关系不大。clash 这个不错你可以看看。

**Comment by Sweetestcc** [comment]
> app 内置dns 解析了。建议找个好点的客户端，其实与服务器关系不大。clash 这个不错你可以看看。

去google play下了个新的app，就可以了

**Comment by Sweetestcc** [comment]
> app 内置dns 解析了。建议找个好点的客户端，其实与服务器关系不大。clash 这个不错你可以看看。

看样子是国内app内置dns的问题，clash是不是能劫持dns

**Comment by qist** [comment]
可以

**Comment by Sweetestcc** [comment]
好像还是不行，仍未解决

**Comment by Sweetestcc** [comment]
好像也跟协议相关。换成vless+tcp+xtls之后就没有这个问题了原本是vmess+ws+tls

**Comment by Misanalia** [comment]
我也遇到了这个问题，请问具体是怎么解决的呢？

**Comment by SQLimit** [comment]
> 我也遇到了这个问题，请问具体是怎么解决的呢？
> 
> v2rayng v.1.7.38   xray core v.1.7.5  vless+vision
> 
> 搬瓦工cn2gia分流geosite:bilibili到香港阿里云
> 分流203.107.0.0/16到香港阿里云
> 
> b站客户端开启https播放后可加载无法播放，关闭后大概率可播放
> 
> 电脑网页版一切正常

是tcp tls吗？

**Comment by Misanalia** [comment]
> > 我也遇到了这个问题，请问具体是怎么解决的呢？
> > v2rayng v.1.7.38   xray core v.1.7.5  vless+vision
> > 搬瓦工cn2gia分流geosite:bilibili到香港阿里云
> > 分流203.107.0.0/16到香港阿里云
> > b站客户端开启https播放后可加载无法播放，关闭后大概率可播放
> > 电脑网页版一切正常
> 
> 是tcp tls吗？
是的 
协议:vless
传输协议:tcp 
流控:xtls-rprx-vision
tls

**Comment by qist** [comment]
v2rayng 应该可用收集日志，你打开看看日志内容，解决就很快了。猜是解决不了问题得。

**Comment by Misanalia** [comment]
> v2rayng 应该可用收集日志，你打开看看日志内容，解决就很快了。猜是解决不了问题得。

v2rayng的日志全是ip地址，很难分辨具体访问了什么，我该怎么做?
我在ip地址中发现了美国，日本，德国的ip归属地，猜测是dns问题？
发现了发往3478端口的udp ip归属地为上海(123.60.93.20)

**Comment by qist** [comment]
建议换个工具试试。https://github.com/MetaCubeX/ClashMetaForAndroid 我推存这个。

**Comment by Misanalia** [comment]
> > v2rayng 应该可用收集日志，你打开看看日志内容，解决就很快了。猜是解决不了问题得。
> 
> v2rayng的日志全是ip地址，很难分辨具体访问了什么，我该怎么做? 我在ip地址中发现了美国，日本，德国，丹麦的ip归属地，猜测是dns问题(dns不应该是服务器负责解析吗)？ 发现了发往3478端口的udp ip归属地为上海(123.60.93.201)(仅在打开b站客户端后出现)
> 
> 服务器访问日志中发现： 刚进入视频时，访问域名upos-hz-mirrorakam.akamaized.net，在几秒后，不再访问它变成了**国内**ip地址端口为8000。 因为服务器禁止了访问**国内**ip，放行后**可能会**正常播放。 我的问题是这种行为是正常的吗？既然b站客户端开启了https播放，仅在视频刚开始使用 域名upos-hz-mirrorakam.akamaized.net:443之后却变成了**国内**ip:8000还能保证加密吗？ 这种流量回国行为我想避免，明明upos-hz-mirrorakam.akamaized.net在香港解析后为香港地址，却在几秒后变成**国内**地址...

服务器错误日志为info时发现了：app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: failed to open connection to tcp:203.107.1.65:80 > common/retry: [dial tcp 203.107.1.65:80: connect: connection refused] > common/retry: all retry attempts failed

**Comment by Misanalia** [comment]
问题已解决，原因是:
(测试位置:**香港**)

1.不能完全禁止国内ip   (*.bilibili.com**可能**解析到大陆，如需其他指定ip需要设置hosts)
2.xray设置dns和clientIp (不设置clientIp **可能**解析到奇奇怪怪的地址,查看错误日志("loglevel": "info")并开启dns日志("dnsLog": true)可查看)
3.放行8000端口 (b站客户端**可能**只在视频开始时访问upos-hz-mirrorakam.akamaized.net，之后为国内IP:8000)
4.freedom出站需要设置"domainStrategy": "UseIP",使用xray 内部dns服务器

纯小白只能通过大量测试论证，无法提供更多的信息，抱歉。

**Comment by Misanalia** [comment]
服务器dns劫持到香港后依然无法播放
