### ISSUE TITLE
XTLS的direct和origin模式似乎不能混用？

### ISSUE THREAD

**Issue by Gabirel** [XTLS/Xray-core#111]
## 基础信息

服务端版本信息：`xray v1.1.4` 
客户端版本信息：`xray v1.1.4` 和`qv2ray 2.7.0-pre1:6039`

## 问题描述

1. 当服务端使用direct模式的时候，客户端使用`xtls-rprx-direct`。则部分网站正常
2. 当服务端使用direct模式的时候，客户端使用`xtls-rprx-origin`。则无法访问

我记得以前在v2ray v4.30.2的时候，似乎可以混用？（可能我记错了）

如果不能混用，希望文档[可以](https://github.com/rprx/v2fly-github-io/blob/master/docs/config/protocols/vless.md#xtls-%E9%BB%91%E7%A7%91%E6%8A%80)跟进

**Comment by xianren78** [comment]
把似乎去了，因为确实不能混用。

**Comment by rprx** [comment]
是的，不能混用。

**Comment by badO1a5A90** [comment]
已加入文档 FAQ
