### ISSUE TITLE
1.4以后的版本不支持vmess+tcp了么

### ISSUE THREAD

**Issue by fanbin8592** [XTLS/Xray-core#1110]
1.4以后的版本不支持vmess+tcp了么，今天从1.3升级到1.5以后国内中转不能用了。入站用的vmess+tcp。
1.4 1.5都不行了。
是怎么回事呢

**Comment by fanbin8592** [comment]
{
  "log": {
    "access": "none",
    "error": "none",
    "loglevel": "none"
  },
   "dns": {
    "servers": [
		{
        "address": "https+local://doh.pub/dns-query",
        "domains": ["geosite:cn"],
		"expectIPs": ["geoip:cn"]
      	},
		{
		"address": "https://1.1.1.1/dns-query"
		}
    ]
  },
  "inbounds": [
{
        "port": 19953,
        "protocol": "vmess",
        "settings": {
            "clients": [
                {
                    "id": "0000000000000000000000000000000",
                    "alterId": 0
                }
            ]
        }
    }
  ],
  "outbounds": [
        {
      "tag": "proxy",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "000000000000000000000000.xyz",
            "port": 443,
            "users": [
              {
                "id": "00000000000000000000000000000",
                "alterId": 0,
                "email": "t@t.tt",
                "security": "auto",
                "encryption": "none",
                "flow": "xtls-rprx-direct"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
          "allowInsecure": true
        }
      },
      "mux": {
        "enabled": false,
        "concurrency": -1
      }
    },


    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    }
  ],
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "domainMatcher": "mph",
    "rules": [
{
        "type": "field",
        "outboundTag": "direct",
        "protocol": [
          "bittorrent"
        ],
        "enabled": true
      },
      {
        "type": "field",
        "outboundTag": "block",
        "domain": [
          "geosite:category-ads-all"
        ],
        "enabled": true
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": [
          "geosite:cn"
        ],
        "enabled": true
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "geoip:private",
          "geoip:cn"
        ],
        "enabled": true
      },
      {
        "type": "field",
        "port": "0-65535",
        "outboundTag": "proxy",
        "enabled": true
      }
    ]  
}
}

**Comment by yuhan6665** [comment]
大概是客户端 alterid 问题

**Comment by fanbin8592** [comment]
> 大概是客户端alterid问题

什么问题alterid0 和4 都试过都不行。

**Comment by yuhan6665** [comment]
你说“国内中转”那么你有几个服务器？客户端和每一个服务器分别是？版本是？

**Comment by fanbin8592** [comment]
> 你说“国内中转”那么你有几个服务器？客户端和每一个服务器分别是？版本是？

国外都是最新用的vless    客户端也是最新     就是中转用了vmess+tcp入站不行，中转ss   socks5入站都没事
