### ISSUE TITLE
对"domainStrategy": "XX XXX" 的疑问

### ISSUE THREAD

**Issue by tlsalex** [XTLS/Xray-core#1114]
上一张从官网截的一张图。具体疑问在图下方

![why](https://user-images.githubusercontent.com/36788337/174484283-9e65c9e2-5fd0-48d0-9e05-430838f937fc.png)

1. 如果我把domainStrategy 设置Asis, 根据官方配置文档里 ”内置 DNS 服务器“
 的介绍，Xray 是不再依赖DNS来路由数据的，这个和容易理解。

2. 如果我把domainStrategy 设置为IPIfNonMatch, 配置文件里的DNS模块，是不是不需要 "domains": ["geosite:geolocation-!cn"] 或 "domains": ["geosite:cn"] 来限定是哪类域名就用哪个DNS来解析域名 或不需要"expectIPs": ["geoip:cn"] 之类的设置，即只需指定DNS IP, 这个路由策略表明在被匹配的域名与任何基于domain的规则都不匹配的情况下，将该域名解析成IP， 再用解析到的IP 去匹配基于IP的规则； 如果在第一轮基于域名的匹配规则都没匹配上，DNS解析的时候，就不应该指定： 假如该域名在 "domains": ["geosite:geolocation-!cn"] 里，就用 "address": "1.1.1.1", 去解析，否则没有意义了，因为Xray并不知道该域名是属于哪一类域名，否则在第一轮匹配的时候就能做出路由选择了。 可能是我理解的还不全面，存在错误，请帮忙指出不对的地方。

3. 如果我把domainStrategy 设置为IPOnDemand, 意思是对任何域名，都需要先通过DNS来解析成IP，这时就可以指定：如果该域名如果在 "domains": ["geosite:geolocation-!cn"] 里，就用 "address": "1.1.1.1",去解析， 再用解析到的IP去匹配基于IP的路由规则，这样的话，路由模块是不是就没必要包含基于域名的路由规则？ 还是说先判断路由模块里是否包含有基于IP的路由规则，如果有则所有域名必须解析成IP在进行IP规则匹配，如果没有，则不解析IP，直接通过域名规则去做路由选择。是这样理解吗？

总得来说，把domainStrategy
设置为IPOnDemand时，DNS模块指定domains 或 expectIPs 的参数才有意义，
设置为IPIfNonMatch 或Asis 时，DNS模块指定domains 或 expectIPs 的参数 是没有意义的，
设置为Asis 时，设置DNS模块是没有意义的。

可以这样理解吗？

**Comment by tlsalex** [comment]
只就路由而论

**Comment by Nyar233** [comment]
显示指定可能是为了减少dns泄露（个人判断）

**Comment by tlsalex** [comment]
Anyone can help?

**Comment by chika0801** [comment]
这个几句解释不清楚

https://github.com/chika0801/Xray-examples/tree/main/VLESS-TCP-XTLS#dns%E6%9F%A5%E8%AF%A2%E6%B5%81%E7%A8%8B%E8%AF%B4%E6%98%8E
这链接是以我的配置为例简单的说明，你要进一步学，推荐看最后那些推荐文章。

然后在客户端配置建议开debug后访问网站，看日志，结合学到的知识，就搞明白了。

假设你用win系统 客户端是v2rayn（这种情况非透明代理）看日志搞懂dns比较好（简单）

复杂情况是你用透明代理，dns解析如果又用xay的dns模块（比如openwrt系统上的passwall2插件）

**Comment by yuhan6665** [comment]
你想的基本是对的 只是忽略了 DNS 模块有其它几个用途：

- Freedom 出口可以指定使用它解析 可以直连访问一些 dns 污染 但没有 sni 屏蔽的网站
- 透明代理 安卓vpn代理 访问之前的 dns 流量会进入 core 的 DNS 模块 这个 dns 如果没搞好也有问题

**Comment by yuhan6665** [comment]
close as solved
