### ISSUE TITLE
geosite:geolocation-!cn 排在规则第一条时 apple.com.cn 并没有走代理

### ISSUE THREAD

**Issue by GeorgeRudd** [XTLS/Xray-core#1119]
xray 1.5.8
geosite文件 使用的是增强版路由规则 https://github.com/Loyalsoldier/v2ray-rules-dat

客户端配置
```json
{
   "log":{
      "access":"",
      "error":"",
      "loglevel":"info"
   },
   "dns":{
      "servers":[
         "8.8.8.8",
         {
            "address":"223.5.5.5",
            "skipFallback":true,
            "domains":[
               "geosite:cn"
            ],
            "expectIPs":[
               "geoip:cn"
            ]
         }
      ],
      "queryStrategy":"UseIPv4"
   },
   "routing":{
      "domainStrategy":"IPIfNonMatch",
      "domainMatcher":"mph",
      "rules":[
         {
            "type":"field",
            "outboundTag":"proxy",
            "domain":[
               "geosite:geolocation-!cn"
            ]
         },
         {
            "outboundTag":"direct",
            "type":"field",
            "domain":[
               "geosite:cn"
            ]
         },
         {
            "outboundTag":"proxy",
            "type":"field",
            "ip":[
               "8.8.8.8"
            ]
         },
         {
            "outboundTag":"direct",
            "type":"field",
            "ip":[
               "223.5.5.5",
               "geoip:cn",
               "geoip:private"
            ]
         }
      ]
   },
   "inbounds":[
      {
         "tag":"socks",
         "protocol":"socks",
         "listen":"127.0.0.1",
         "port":10808,
         "settings":{
            "auth":"noauth",
            "udp":true
         },
         "streamSettings":{
            "network":"tcp",
            "security":"none"
         },
         "sniffing":{
            "enabled":true,
            "destOverride":[
               "http",
               "tls"
            ],
            "metadataOnly":false
         },
         "allocate":{
            "strategy":"always"
         }
      },
      {
         "tag":"http",
         "protocol":"http",
         "listen":"127.0.0.1",
         "port":10809,
         "settings":{
            "allowTransparent":false
         },
         "streamSettings":{
            "network":"tcp",
            "security":"none"
         },
         "sniffing":{
            "enabled":true,
            "destOverride":[
               "http",
               "tls"
            ],
            "metadataOnly":false
         },
         "allocate":{
            "strategy":"always"
         }
      }
   ],
   "outbounds":[
      {
         "tag":"proxy",
         "protocol":"",
         "settings":{
            "servers":[
               {
                  "address":"",
                  "port":12345,
                  "method":"",
                  "password":""
               }
            ]
         },
         "streamSettings":{
            "network":"tcp",
            "security":"none"
         },
         "mux":{
            "enabled":false,
            "concurrency":-1
         }
      },
      {
         "tag":"direct",
         "protocol":"freedom",
         "settings":{
            "domainStrategy":"UseIPv4"
         }
      },
      {
         "tag":"block",
         "protocol":"blackhole",
         "settings":{
            
         }
      }
   ]
}
```
访问apple.com走代理 accepted tcp:www.apple.com:443 [socks -> proxy]
访问apple.com.cn是直连 accepted tcp:www.apple.com.cn:443 [socks -> direct]

apple类别在geosite:geolocation-!cn 里面，那访问apple.com.cn应该也走代理才对啊

**Comment by chika0801** [comment]
这问题应该去grofile作者的主页提。

**Comment by chancat87** [comment]
> xray 1.5.8 geosite文件 使用的是增强版路由规则 https://github.com/Loyalsoldier/v2ray-rules-dat
> 
> 客户端配置
> 
> ```json
> {
>    "log":{
>       "access":"",
>       "error":"",
>       "loglevel":"info"
>    },
>    "dns":{
>       "servers":[
>          "8.8.8.8",
>          {
>             "address":"223.5.5.5",
>             "skipFallback":true,
>             "domains":[
>                "geosite:cn"
>             ],
>             "expectIPs":[
>                "geoip:cn"
>             ]
>          }
>       ],
>       "queryStrategy":"UseIPv4"
>    },
>    "routing":{
>       "domainStrategy":"IPIfNonMatch",
>       "domainMatcher":"mph",
>       "rules":[
>          {
>             "type":"field",
>             "outboundTag":"proxy",
>             "domain":[
>                "geosite:geolocation-!cn"
>             ]
>          },
>          {
>             "outboundTag":"direct",
>             "type":"field",
>             "domain":[
>                "geosite:cn"
>             ]
>          },
>          {
>             "outboundTag":"proxy",
>             "type":"field",
>             "ip":[
>                "8.8.8.8"
>             ]
>          },
>          {
>             "outboundTag":"direct",
>             "type":"field",
>             "ip":[
>                "223.5.5.5",
>                "geoip:cn",
>                "geoip:private"
>             ]
>          }
>       ]
>    },
>    "inbounds":[
>       {
>          "tag":"socks",
>          "protocol":"socks",
>          "listen":"127.0.0.1",
>          "port":10808,
>          "settings":{
>             "auth":"noauth",
>             "udp":true
>          },
>          "streamSettings":{
>             "network":"tcp",
>             "security":"none"
>          },
>          "sniffing":{
>             "enabled":true,
>             "destOverride":[
>                "http",
>                "tls"
>             ],
>             "metadataOnly":false
>          },
>          "allocate":{
>             "strategy":"always"
>          }
>       },
>       {
>          "tag":"http",
>          "protocol":"http",
>          "listen":"127.0.0.1",
>          "port":10809,
>          "settings":{
>             "allowTransparent":false
>          },
>          "streamSettings":{
>             "network":"tcp",
>             "security":"none"
>          },
>          "sniffing":{
>             "enabled":true,
>             "destOverride":[
>                "http",
>                "tls"
>             ],
>             "metadataOnly":false
>          },
>          "allocate":{
>             "strategy":"always"
>          }
>       }
>    ],
>    "outbounds":[
>       {
>          "tag":"proxy",
>          "protocol":"",
>          "settings":{
>             "servers":[
>                {
>                   "address":"",
>                   "port":12345,
>                   "method":"",
>                   "password":""
>                }
>             ]
>          },
>          "streamSettings":{
>             "network":"tcp",
>             "security":"none"
>          },
>          "mux":{
>             "enabled":false,
>             "concurrency":-1
>          }
>       },
>       {
>          "tag":"direct",
>          "protocol":"freedom",
>          "settings":{
>             "domainStrategy":"UseIPv4"
>          }
>       },
>       {
>          "tag":"block",
>          "protocol":"blackhole",
>          "settings":{
>             
>          }
>       }
>    ]
> }
> ```
> 
> 访问apple.com走代理 accepted tcp:www.apple.com:443 [socks -> proxy] 访问apple.com.cn是直连 accepted tcp:www.apple.com.cn:443 [socks -> direct]
> 
> apple类别在geosite:geolocation-!cn 里面，那访问apple.com.cn应该也走代理才对啊

gosite:apple-cn 这个才是可以直连的列表
