### ISSUE TITLE
运行 xray api stats 报错

### ISSUE THREAD

**Issue by morooi** [XTLS/Xray-core#112]
版本：1.1.5
在 macOS 11.1 中直接运行和使用秋大构建的 1.1.5 Docker 环境均复现

报错：
``` bash
$ xray api stats --server=127.0.0.1:27711
failed to get stats: rpc error: code = Unknown desc = app/stats/command:  not found.
```

测试过 `xray api statsquery` 和 `xray api statssys` 均有输出且正常

部分配置内容：
``` json
{
    "inbounds": [
        {
            "port": 27711,
            "listen": "127.0.0.1",
            "protocol": "dokodemo-door",
            "settings": {
                "address": "127.0.0.1"
            },
            "tag": "api"
        }
    ],
    "routing": {
        "rules": [{
            "type": "field",
            "inboundTag": [
                "api"
            ],
            "outboundTag": "api"
        }]
    },
    "stats": {},
    "api": {
        "tag": "api",
        "services": [
            "StatsService"
        ]
    },
    "policy": {
        "levels": {
            "0": {
                "statsUserUplink": true,
                "statsUserDownlink": true
            }
        },
        "system": {
            "statsInboundUplink": true,
            "statsInboundDownlink": true,
            "statsOutboundUplink": true,
            "statsOutboundDownlink": true
        }
    }
}
```

另外请问一下，可不可以使用 VLESS 的回落，配合 path 进行远程 API 调用（客户端和服务端不在同一个机器上）

比如使用如下方式

``` bash
$ xray api statsquery --server=https://example.com:443/api
```

**Comment by JimhHan** [comment]
您好，使用stats查询需要添加一个参数 `name` ，例如：
`xray api stats --server=127.0.0.1:27711 -name "inbound>>>api>>>traffic>>>downlink"`
 详情请参阅[这个文档](https://xtls.github.io/config/stats/)。


> 另外请问一下，可不可以使用 VLESS 的回落，配合 path 进行远程 API 调用（客户端和服务端不在同一个机器上）

这个暂时是不行的，目前回落只支持解析 `alpn` 与 `HTTP1.x` 的 `path` ，但 `grpc` 使用的是 `h2`。
目前有一个关于 `sni` 的 [Pull Request](https://github.com/XTLS/Xray-core/pull/84)，合并后可以用`sni`分流以达到目的。

**Comment by morooi** [comment]
> 您好，使用stats查询需要添加一个参数 `name` ，例如：
> `xray api stats --server=127.0.0.1:27711 -name "inbound>>>api>>>traffic>>>downlink"`
> 详情请参阅[这个文档](https://xtls.github.io/config/stats/)。
> 
> > 另外请问一下，可不可以使用 VLESS 的回落，配合 path 进行远程 API 调用（客户端和服务端不在同一个机器上）
> 
> 这个暂时是不行的，目前回落只支持解析 `alpn` 与 `HTTP1.x` 的 `path` ，但 `grpc` 使用的是 `h2`。
> 目前有一个关于 `sni` 的 [Pull Request](https://github.com/XTLS/Xray-core/pull/84)，合并后可以用`sni`分流以达到目的。

**非常感谢解答！**
提此 issue 前我查阅过 xray 的文档，也参考过 v2fly 的文档，都没能找到相关用法😂

接下来就期待新版本了！

**Comment by peopleel** [comment]
在最新版本的Xay 1.3.1 CentOS7中，我也复现了此问题。

**Comment by morooi** [comment]
> 在最新版本的Xay 1.3.1 CentOS7中，我也复现了此问题。

使用方式的问题，看楼上解答。

**Comment by peopleel** [comment]
> > 在最新版本的Xay 1.3.1 CentOS7中，我也复现了此问题。
> 
> 使用方式的问题，看楼上解答。

谢谢，已解决
