### ISSUE TITLE
Xray是无法代理ntp吗？

### ISSUE THREAD

**Issue by xsm1997** [XTLS/Xray-core#1121]
如果ntp走了代理，本地xray client可以看到udp 123端口的ntp连入，但是服务器看不到相关log。

我确定客户端和服务器都没配置ntp相关的路由规则（包括直连也没配置）。

同时，使用发包工具测试发送122端口和124端口，客户端和服务器均可看到log，唯独123端口服务器没有log。

这是bug还是feature？

**Comment by xsm1997** [comment]
补充：客户端和服务器均使用官方example中的xtls配置，flow使用xtls-rprx-splice和xtls-rprx-direct，无任何特殊配置。因相关性很低，故不贴出。

**Comment by chika0801** [comment]
你客户端指用的软路由？还是？

**Comment by xsm1997** [comment]
> 你客户端指用的软路由？还是？

vyos软路由，采用白话文教程中类似的nftables tproxy方法配置。

tcpdump抓udp 123端口的包，抓得到，xray客户端log中有显示，但服务器log中没有显示，实际上ntp同步也不通。

**Comment by xsm1997** [comment]
哦，破案了，本地123端口运行着ntpd，关了就好了，不只为何开着ntpd就会冲突，大家有什么思路和建议吗？

**Comment by yuhan6665** [comment]
按理说流量如果进入 core 那么你本地开不开 ntpd 应该不影响分流的 贴一下有问题的日志看看

**Comment by yuhan6665** [comment]
close as solved
