### ISSUE TITLE
用官方script升级后，Xray无法启动？

### ISSUE THREAD

**Issue by stevenGu** [XTLS/Xray-core#1125]
ubuntu 20.04LTS , Xray安装后一直正常工作，考虑安全问题，使用官网推荐的方法：
“# bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install” 命令来升级，过程正常。
显示“info: Xray is installed.”。但是无法启动xray!

![image](https://user-images.githubusercontent.com/1780889/176817292-feff26c1-e032-438c-ad93-ec152abe31c2.png)

如何解决“**(code=exited, status=203/EXEC)**”？

**Comment by yuhan6665** [comment]
需要看启动失败的日志 如果不会可以尝试手动启动看是啥错误

**Comment by chika0801** [comment]
建立重装系统后尝试

**Comment by stevenGu** [comment]
**https://github.com/XTLS/Xray-core/issues/1125#issuecomment-1172824186**
如果重新安装系统和Xray后，估计Xray会恢复正常。 那就不知道按官方推荐方式升级后，出错的原因了。

**Comment by chika0801** [comment]
其它人没遇到，不是那种个个人都遇到的（bug），每个人情况不一样，说不清楚，你要不加--version 1.5.8 试下升级到158报错不

**Comment by stevenGu** [comment]
谢谢了

**Comment by zhyonchen** [comment]
是不是/etc/systemd/system/xray.service里面的User=nobody?
改成User=root就能用systemctl启动了
猜测你可能用了回落Unix文件没有读写权限

**Comment by yuhan6665** [comment]
close as invalid issue without error log
