### ISSUE TITLE
openwrt编译失败

### ISSUE THREAD

**Issue by rosewu550** [XTLS/Xray-core#1128]
报错日志：
Building targets
../../../../../dl/go-mod-cache/github.com/sagernet/sing-shadowsocks@v0.0.0-20220619134218-830a2f478eb1/shadowaead_2022/protocol.go:29:2: no required module provides package github.com/sagernet/sing/common/replay; to add it:
	go get github.com/sagernet/sing/common/replay
../../../../../dl/go-mod-cache/github.com/sagernet/sing@v0.0.0-20220619130320-8793fe5e067d/common/bufio/conn.go:15:2: no required module provides package github.com/sagernet/sing/common/task; to add it:
	go get github.com/sagernet/sing/common/task

make[3]: *** [Makefile:51: /home/wuwei/openwrt/lede/build_dir/target-x86_64_musl/Xray-core-1.5.8/.built] Error 1
make[3]: Leaving directory '/home/wuwei/openwrt/lede/feeds/small/xray-core'
time: package/feeds/small/xray-core/compile#3.38#0.72#17.38
    ERROR: package/feeds/small/xray-core failed to build.
make[2]: *** [package/Makefile:116: package/feeds/small/xray-core/compile] Error 1
make[2]: Leaving directory '/home/wuwei/openwrt/lede'
make[1]: *** [package/Makefile:110: /home/wuwei/openwrt/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/wuwei/openwrt/lede'
make: *** [/home/wuwei/openwrt/lede/include/toplevel.mk:230: world] Error 2

openwrt源码：
L大master分支最新代码（https://github.com/coolsnowwolf/lede）

**Comment by FranzKafkaYu** [comment]
@rosewu550 这应该是本地编译相关依赖没有齐全

**Comment by rosewu550** [comment]
> @rosewu550 这应该是本地编译相关依赖没有齐全

@FranzKafkaYu 你好，如何追踪到缺失那个依赖嘛，我本地下载dl库时，没有发现任何报错哎

**Comment by FranzKafkaYu** [comment]
@rosewu550 编译错误中有提示，go get的内容即为缺失的依赖，按照提示下载即可

**Comment by rosewu550** [comment]
> @rosewu550 编译错误中有提示，go get的内容即为缺失的依赖，按照提示下载即可

好的，多谢

**Comment by yuhan6665** [comment]
close as solved

**Comment by samlin39** [comment]
> @rosewu550 编译错误中有提示，go get的内容即为缺失的依赖，按照提示下载即可

请教按照go get执行命令，下载后再次编译还是一样的报错。
`../../../../../dl/go-mod-cache/github.com/compose-spec/compose-go@v1.8.2/cli/options.go:26:2: no required module provides package github.com/compose-spec/compose-go/consts; to add it:
        go get github.com/compose-spec/compose-go/consts`
执行
`go get github.com/compose-spec/compose-go/consts`
可以看到下载成功，在以下目录
`~/go/src/github.com/compose-spec/compose-go/consts`

但是再次编译还是提示
`no required module provides package github.com/compose-spec/compose-go/consts; to add it:
        go get github.com/compose-spec/compose-go/consts``

**Comment by samlin39** [comment]
> > @rosewu550 这应该是本地编译相关依赖没有齐全
> 
> @FranzKafkaYu 你好，如何追踪到缺失那个依赖嘛，我本地下载dl库时，没有发现任何报错哎

你好，请问怎么解决的？谢谢
