### ISSUE TITLE
如何给日志增加流量统计

### ISSUE THREAD

**Issue by paul13579** [XTLS/Xray-core#113]
请问如何才能给日志增加流量统计，比如说可以记录每条连接的上下行所用流量这样？

**Comment by NutterChen** [comment]
能否详细解释下需求，有点儿没搞懂啥意思

**Comment by rprx** [comment]
我记得是有这个功能的

**Comment by badO1a5A90** [comment]
这是需要统计每一次连接的上下行数据吗（类似Nginx）

**Comment by paul13579** [comment]
是的，就是这个意思

**Comment by Leozaki** [comment]
写插件很容易实现的呀..1分钟API取1次流量数据然后日志打印出来（不过是否清理你自己决定
