### ISSUE TITLE
API命令行增加用户

### ISSUE THREAD

**Issue by stoneport** [XTLS/Xray-core#1131]
在API功能描述文档中，包含**在一个入站代理中添加一个用户**这一功能。
[API 接口 | Project X](https://xtls.github.io/config/api.html#%E7%9B%B8%E5%85%B3%E9%85%8D%E7%BD%AE)

> HandlerService
> 一些对于入站出站代理进行修改的 API，可用的功能如下：
> 添加一个新的入站代理；
> 添加一个新的出站代理；
> 删除一个现有的入站代理；
> 删除一个现有的出站代理；
> 在一个入站代理中添加一个用户（仅支持 VMess、VLESS、Trojan、Shadowsocks（v1.3.0+））；
> 在一个入站代理中删除一个用户（仅支持 VMess、VLESS、Trojan、Shadowsocks（v1.3.0+））；

但是在**命令参数**文档中，却没有单独添加/删除用户的参数。
[命令参数 | Project X](https://xtls.github.io/document/command.html#xray-api)

```
xray api <command> [arguments]
        restartlogger Restart the logger
        stats         Get statistics
        statsquery    Query statistics
        statssys      Get system statistics
        adi           Add inbounds
        ado           Add outbounds
        rmi           Remove inbounds
        rmo           Remove outbounds
```

请问单独添加用户有什么隐藏的命令参数吗？或者这是个未完成的TODO？

**Comment by yuhan6665** [comment]
事实上 *ray 提供的是 grpc 的接口 你所看到的命令行只是在这之上再加了一层 用户友好的输入和输出
因为添加一个用户没有现成的 json 所以没做上层接口 需要自行开发使用 grpc 的业务逻辑

幸运的是 @crossfw 大佬已经写了一个 api 的使用范例并开源了 https://github.com/crossfw/Xray-API-documents
推荐你看一下[这里](https://github.com/crossfw/Xray-API-documents/blob/eb3b152dfda6e3503667be426b3caebe61bc81d5/examples/alterInbound.go#L13)

**Comment by markvlenvision** [comment]
无奈不会go,有没有Java版本（发出了白嫖的声音。。。

**Comment by yuhan6665** [comment]
> 无奈不会go,有没有Java版本（发出了白嫖的声音。。。

当初谷歌搞 grpc 一个重要的优点就是跨语言 API 
你如果有相关经验 只需要编译一下 proto 应该不难的 你可以成为下一个大佬 :)

**Comment by yuhan6665** [comment]
close as solved

**Comment by puzzle9** [comment]
> 无奈不会go,有没有Java版本（发出了白嫖的声音。。。

其实 你可以用 `protoc` 编译个 `java` 的出来使用
