### ISSUE TITLE
反向代理 -- 为什么要在portal 这一端的Inbound里的settings 指定IP信息

### ISSUE THREAD

**Issue by tlsalex** [XTLS/Xray-core#1133]
`Xray 1.5.5`
以下是从官方文档拷贝过来的code, 文档里表面在bridge 端的outbound的setting里需要指定被访问的服务器的信息，这个很容易理解，但我不明白为什么在portal 端的inbound的 setting里还需要指定IP信息，这IP信息有什么用，跟被访问的IP有什么关系？我尝试把端口的信息去掉，反向代理同样是可以起作用的。 

相对Frp来说，xray的逻辑很难理解。

Bridge 端的outbound
```
{
  "tag": "out",
  "protocol": "freedom",
  "settings": {
    "redirect": "127.0.0.1:80" // 将所有流量转发到网页服务器  
  }
}
```

portal端的inbound
```
{
  "tag": "external",
  "port": 80,
  "protocol": "dokodemo-door",
  "settings": {
    "address": "127.0.0.1", -----意义在哪
    "port": 80,   -----意义在哪
    "network": "tcp" 
  }
}
```
以下log是没在portal 端inbound的setting里指定端口信息，只指定了IP和 network:tcp的情况下得到的
```
2022/07/06 22:35:28 x.x.x.x:3999 accepted tcp:127.0.0.1:0 [external -> portal]
2022/07/06 22:35:28 x.x.x.x:3998 accepted tcp:127.0.0.1:0 [external -> portal]
2022/07/06 22:35:46 x.x.x.x:4008 accepted tcp:127.0.0.1:0 [external -> portal]
```

**Comment by yuhan6665** [comment]
你贴的两个 127.0.0.1:80 应该是只填任意一个就行了

**Comment by yuhan6665** [comment]
close as solved

**Comment by anonbaby** [comment]
建议在文档中说明。portal端的inbound "settings": "address": 我以为是portal监听的IP，所以写了0.0.0.0，于是CPU和内存都打满了

> 你贴的两个 127.0.0.1:80 应该是只填任意一个就行了
