### ISSUE TITLE
xrayerror日志老提示这个，请问是哪里没设置好嘛,

### ISSUE THREAD

**Issue by rianjskis** [XTLS/Xray-core#1134]
2022/07/06 15:19:09 [Error] app/dns: failed to retrieve response for cloudflarestream.com. > Post "https://1.1.1.1/dns-query": context canceled
2022/07/06 15:22:21 [Error] app/dns: failed to retrieve response for blog.cloudflare.com. > Post "https://1.1.1.1/dns-query": context canceled
2022/07/06 15:22:22 [Error] app/dns: failed to retrieve response for cloudflare.com. > Post "https://1.1.1.1/dns-query": context canceled
2022/07/06 15:23:29 [Error] app/dns: failed to retrieve response for 1111-releases.cloudflareclient.com. > Post "https://1.1.1.1/dns-query": context canceled
2022/07/06 15:27:20 [Error] app/dns: failed to retrieve response for rr3---sn-n3cgv5qc5oq-bh26r.googlevideo.com. > Post "https://1.1.1.1/dns-query": context canceled
这是xraydns配置文件
{
    
    "dns": {
        "servers": [
            "https+local://1.1.1.1/dns-query"
        ],
        "queryStrategy": "UseIPv4"
    },
    "routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "type": "field",
                "domain": [
                    "geosite:category-ads-all"
                ],
                "outboundTag": "block"
            },
            {
                "type": "field",
                "ip": [
                    "geoip:cn",
                    "geoip:private"
                ],
                "outboundTag": "block"
            }
        ]
    },

**Comment by rianjskis** [comment]
> `+local`去掉

去了后还是这样😅😅😅😅

**Comment by azzvx** [comment]
试一下`ping 1.1.1.1`看看响应时间是多少，我这边只要1-2ms，TTL=251，说明是被ISP劫持走了，`1.1.1.1`并不可用。`1.0.0.1`倒是正常的。
改成：
```
"servers": [
        "https+local://1.0.0.1/dns-query"
]
```

**Comment by rianjskis** [comment]
> 

![Screenshot_20220712_092417](https://user-images.githubusercontent.com/86937445/178387989-cc695817-ee96-4c31-b295-d6dac57f30a9.jpg)
老哥，这个显示，如何

**Comment by wy580477** [comment]
1. 运营商dns劫持只会劫持UDP请求，DOH请求有证书验证，无法劫持。

2. 使用Doh dns以后，日志这个报错就会出现，实际上不影响使用。无视即可。

**Comment by rianjskis** [comment]
> 1. 运营商dns劫持只会劫持UDP请求，DOH请求有证书验证，无法劫持。
> 2. 使用Doh dns以后，日志这个报错就会出现，实际上不影响使用。无视即可。

对，实际我用的话不影响

**Comment by rianjskis** [comment]
> 1. 运营商dns劫持只会劫持UDP请求，DOH请求有证书验证，无法劫持。
> 2. 使用Doh dns以后，日志这个报错就会出现，实际上不影响使用。无视即可。

只是出现这个报错，我还以为有啥不对哈哈哈😂😂

**Comment by azzvx** [comment]
> 1. 运营商dns劫持只会劫持UDP请求，DOH请求有证书验证，无法劫持。
> 2. 使用Doh dns以后，日志这个报错就会出现，实际上不影响使用。无视即可。

1.ISP在内网IP 1.1.1.1架了一台服务器，然后真正的1.1.1.1你就访问不到了，这是IP劫持。
2.ping走的是ICPM协议，不是UDP。
3.不影响正常使用是因为在所有dns服务器不可用的时候，xray会请求主机的dns做解析，相当于你配置文件里面的设置被跳过。
建议设置dns为1.1.1.1之前测试一下，国内许多地方的ISP都有做IP劫持，1.1.1.1是访问不了的，建议用1.0.0.1代替。

![QQ截图20220712110647](https://user-images.githubusercontent.com/1546898/178400034-607171a0-6596-4fef-8559-5e6d37d56da0.png)
我这边的1.1.1.1连53端口都没开放

**Comment by wy580477** [comment]
> 3.不影响正常使用是因为在所有dns服务器不可用的时候，xray会请求主机的dns做解析，相当于你配置文件里面的设置被跳过。
建议设置dns为1.1.1.1之前测试一下，国内许多地方的ISP都有做IP劫持，1.1.1.1是访问不了的，建议用1.0.0.1代替。

你在服务端开一下doh就知道了，服务器完全可用情况下也有这个报错。

**Comment by rianjskis** [comment]
> > 1. 运营商dns劫持只会劫持UDP请求，DOH请求有证书验证，无法劫持。
> > 2. 使用Doh dns以后，日志这个报错就会出现，实际上不影响使用。无视即可。
> 
> 1.ISP在内网IP 1.1.1.1架了一台服务器，然后真正的1.1.1.1你就访问不到了，这是IP劫持。 2.ping走的是ICPM协议，不是UDP。 3.不影响正常使用是因为在所有dns服务器不可用的时候，xray会请求主机的dns做解析，相当于你配置文件里面的设置被跳过。 建议设置dns为1.1.1.1之前测试一下，国内许多地方的ISP都有做IP劫持，1.1.1.1是访问不了的，建议用1.0.0.1代替。
> 
> ![QQ截图20220712110647](https://user-images.githubusercontent.com/1546898/178400034-607171a0-6596-4fef-8559-5e6d37d56da0.png)我这边的1.1.1.1连53端口都没开放

![1](https://user-images.githubusercontent.com/86937445/178412777-d8e46c0a-0847-493a-ab62-c82f4d69f9c0.png)
我这1.1.1.1 跟1.0.0.1都正常吧。
