### ISSUE TITLE
反向代理 -- 如何基于域名或基于访问路径做映射

### ISSUE THREAD

**Issue by tlsalex** [XTLS/Xray-core#1135]
目前看到信息，似乎是portal端的一个端口映射一个内网端口，有N个需要映射的端口，就得在portal暴露N个端口？
如果要映射多个内网端口，但在portal 这一端只通过一个端口去访问，如何实现？

比如有三个内网端口需要映射， portal 这一端的一个inbound 监听在 443，
希望通过 svc1.mysite.com, svc2.mysite.com, svc3.mysite.com 去访问这三个内网服务
希望通过 mysite.com/svc1 mysite.com/svc2 mysite.com/svc3 去访问这三个内网服务

如何实现这两个方式？ 改用其它协议？根据域名做回落？

```
{
  "tag": "external",
  "port": 80,
  "protocol": "dokodemo-door",
  "settings": {
    "address": "127.0.0.1",
    "port": 80,
    "network": "tcp"
  }
```
}

**Comment by yuhan6665** [comment]
因为 portal 是有公网的 推荐使用 https://guide.v2fly.org/app/reverse2.html 里面的方法用客户端访问
这样不仅有鉴权 而且搭好之后可以访问内网任意地址

**Comment by yuhan6665** [comment]
close as solved
