### ISSUE TITLE
可否做一个基于网页的配置生成器 --Xadmin

### ISSUE THREAD

**Issue by tlsalex** [XTLS/Xray-core#1138]
对于小白用户来说，心里只想让服务快速跑起来，但长长的配置code和眼花缭乱的格式缩减，让人生畏；

对于小白用户来说，一般是通过用网上的脚本生成服务器端的配置，再通过vless的链接导入到客户端来完成这个配置流程，或是套用官方给出的模板；

以上两点，对于小白用户来说，都显得太依赖外在因素了，但是，搭建服务的时候，小白估计都知道首选什么协议，是否启用传输层安全，etc..,  所以可否做这样一个基于网页的管理平台出来：
创建服务配置的时候，用户选择了所使用的协议后，自动生成默认的配置值，用户除了可以选择使用默认配置，还可以修改默认值，比如选择使用vless ，自动生成该协议对应的settings内容和streamsettings的内容，同时，streamsettings里的内容还可以通过下拉框来选择选用什么传输方式，哪一种传输层安全机制。

**Comment by FranzKafkaYu** [comment]
@tlsalex X-UI可以满足你的需要，请自行Google

**Comment by chika0801** [comment]
不能，小白就抄模板或一键好了，要想懂都要自学

**Comment by tlsalex** [comment]
强大的东西需要复杂的配置，不认为是个好事

**Comment by yuhan6665** [comment]
close as solved
