### ISSUE TITLE
cipherSuites 字段中无法屏蔽TLS 1.3的协议。

### ISSUE THREAD

**Issue by tomxiang1** [XTLS/Xray-core#114]
在cipherSuites字段中只加入TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384，但还是会出现TLS_AES_128_GCM_SHA256协议无法屏蔽。
还有就是cipherSuites字段中加入的加密协议无法按照加入顺序排序发到服务器。

**Comment by xianren78** [comment]
TLS1.3设计如此。cipherSuites字段本就是服务端下发用的。

**Comment by eMeab** [comment]
TLS1.3 无法指定加密套件

**Comment by tomxiang1** [comment]
> TLS1.3设计如此。cipherSuites字段本就是服务端下发用的。

我的目的：
1、主要是加强对称加密强度。
2、服务器端不强制指定加密("preferServerCipherSuites":false)就可以由客户端排头的加密协议为主，这要如果是不支持aes硬件加密的客户端设备就可以把chacha20-poly1305写在最前面协商，达到性能最佳。

**Comment by eMeab** [comment]
> > TLS1.3设计如此。cipherSuites字段本就是服务端下发用的。
> 
> 我的目的：
> 1、主要是加强对称加密强度。
> 2、服务器端不强制指定加密("preferServerCipherSuites":false)就可以由客户端排头的加密协议为主，这要如果是不支持aes硬件加密的客户端设备就可以把chacha20-poly1305写在最前面协商，达到性能最佳。

目前TLS1.3 无法指定加密套件

**Comment by guanhemeng** [comment]
> > TLS1.3设计如此。cipherSuites字段本就是服务端下发用的。
> 
> 我的目的：
> 1、主要是加强对称加密强度。
> 2、服务器端不强制指定加密("preferServerCipherSuites":false)就可以由客户端排头的加密协议为主，这要如果是不支持aes硬件加密的客户端设备就可以把chacha20-poly1305写在最前面协商，达到性能最佳。

如果要在服务端指定密码套件，请选择TLS1.2。
"preferServerCipherSuites"项若不存在即为false（无需配置），
客户端指定密码套件请参见v2ray之前的TLS设计缺陷，罕见的TLS指纹可能会成为显著的特征。

**Comment by rprx** [comment]
@tomxiang1 

正常情况下客户端会选择最合适的加密套件（比如没有 AES-NI 就选择 chacha）

**Comment by tomxiang1** [comment]
> @tomxiang1
> 
> 正常情况下客户端会选择最合适的加密套件（比如没有 AES-NI 就选择 chacha）

- 下面是客户端用Trojan-gfw ，服务端用xray搭建的trojan服务。(preferServerCipherSuites":false)
- 把AES对称加密协议放前面，客户端与服务端就协商成AES。
![1](https://user-images.githubusercontent.com/45867336/103395912-73201b80-4b6b-11eb-9dd8-f9dedf46d0c9.jpg)
![2](https://user-images.githubusercontent.com/45867336/103395916-76b3a280-4b6b-11eb-97b3-39b1cc442f16.jpg)
![3](https://user-images.githubusercontent.com/45867336/103395919-79ae9300-4b6b-11eb-8ee3-42f668ff867c.jpg)


如果把chacha20放前面，客户端与服务端就协商成chacha20。但是xray的客户端cipherSuites字段无法做到这一点。
![4](https://user-images.githubusercontent.com/45867336/103395996-c98d5a00-4b6b-11eb-80c6-8f9036a56467.jpg)
![5](https://user-images.githubusercontent.com/45867336/103395997-cb571d80-4b6b-11eb-9c77-8de4b898bc2c.jpg)
![6](https://user-images.githubusercontent.com/45867336/103396004-cdb97780-4b6b-11eb-8318-0680e03fc465.jpg)
