### ISSUE TITLE
xray uses dns from dhcp, how to avoid this?

### ISSUE THREAD

**Issue by BK8000L** [XTLS/Xray-core#1141]
i want to make a proxy for Turkmenistan where port 53 is filtered and monitored, so I want to exclude the use of udp dns. I made this configuration, but it does not work as I need, please help
```
{
	"log": {
		"loglevel": "warning"
	},
	"dns": {
		"servers": [
			"8.8.8.8"
		]
	},
	"inbounds": [
		{
			"tag": "socks",
			"listen": "127.0.0.1",
			"port": 10808,
			"protocol": "socks",
			"settings": {
				"auth": "noauth",
				"udp": true
			}
		}
	],
	"outbounds": [
		{
			"tag": "proxy_for_DNS",
			"protocol": "vless",
			"settings": {
				"vnext": [
					{
						"address": "95.182.113.34",
						"port": 82,
						"users": [
							{
								"encryption": "none",
								"id": "a6d517cd-5094-4df5-bd1e-f75aa0568aa5",
								"level": 0
							}
						]
					}
				]
			},
			"mux": {
				"enabled": true,
				"concurrency": 1024
			},
			"streamSettings": {
				"network": "tcp"
			}
		},
		{
			"tag": "proxy",
			"protocol": "vless",
			"settings": {
				"vnext": [
					{
						"address": "begi.0ka0.tk",
						"port": 82,
						"users": [
							{
								"encryption": "none",
								"id": "a6d517cd-5094-4df5-bd1e-f75aa0568aa5",
								"level": 0
							}
						]
					}
				]
			},
			"streamSettings": {
				"network": "tcp"
			}
		},
		{
			"protocol": "freedom",
			"settings": {},
			"tag": "direct"
		}
	],
	"routing": {
		"domainStrategy": "IPOnDemand",
		"rules": [
			{
				"port": 53,
				"outboundTag": "proxy_for_DNS",
				"type": "field"
			},
			{
				"network": "tcp,udp",
				"outboundTag": "proxy",
				"type": "field"
			}
		]
	}
}
```
in the rules, I specified that port 53 should go to proxy_for_DNS, but when I start using the config, in wireshark I see that there is a dns request begi.0ka0.tk to 192.168.0.1 (my router dns server).
![2022-07-13_04-47](https://user-images.githubusercontent.com/82240117/178635030-885aa4fb-7bfd-4e9c-994a-f9f7fca05f91.png)
how to avoid it? my proxy server has dynamic ip so i have to use domain.
"proxy" and "proxy_for_DNS" are different servers, and i want to use "proxy_for_DNS" only once for dns request for "begi.0ka0.tk", or use "proxy_for_DNS" only for dns

**Comment by yuhan6665** [comment]
vless protocol works based on the assumption that censorer don't block a little-known website, in your case "begi.0ka0.tk". Usually that means DNS should work for your domain.
Maybe, you can try a protocol without https, like vmess or shadowsocks

**Comment by BK8000L** [comment]
i used vmess and it didn't change anything ;(
So no way to exlude 192.168.0.1 using only xray?

**Comment by BK8000L** [comment]
omg, a few minutes ago they blocked 178.x.x.x (my server is in there) in Turkmenistan, Cloudflare doesn't work properly since a few days ago...

**Comment by timi-owo** [comment]
Try this configuration below, better way is use DoH if possible.
```
{
	"log": {
		"loglevel": "warning"
	},
	"dns": {
		"tag": "dns",
		"servers": [
			"8.8.8.8"
		]
	},
	"inbounds": [
		{
			"tag": "local",
			"listen": "127.0.0.1",
			"port": 10808,
			"protocol": "socks",
			"settings": {
				"auth": "noauth",
				"udp": true
			}
		}
	],
	"outbounds": [
		{
			"protocol": "freedom",
			"settings": {},
			"tag": "direct"
		},
		{
			"tag": "proxy_for_DNS",
			"protocol": "vmess",
			"settings": {
				"vnext": [
					{
						"address": "95.182.113.34",
						"port": 82,
						"users": [
							{
								"alterId": 0,
								"security": "auto",
								"id": "a6d517cd-5094-4df5-bd1e-f75aa0568aa5"
							}
						]
					}
				]
			},
			"mux": {
				"enabled": true,
				"concurrency": 1024
			},
			"streamSettings": {
				"network": "tcp",
				"sockopt": {
					"domainStrategy": "UseIP"
				}
			}
		},
		{
			"tag": "proxy",
			"protocol": "vmess",
			"settings": {
				"vnext": [
					{
						"address": "begi.0ka0.tk",
						"port": 82,
						"users": [
							{
								"alterId": 0,
								"security": "auto",
								"id": "a6d517cd-5094-4df5-bd1e-f75aa0568aa5"
							}
						]
					}
				]
			},
			"streamSettings": {
				"network": "tcp",
				"sockopt": {
					"domainStrategy": "UseIP"
				}
			}
		}
	],
	"routing": {
		"domainStrategy": "IPOnDemand",
		"rules": [
			{
				"inboundTag": ["dns"],
				"outboundTag": "proxy_for_DNS",
				"type": "field"
			},
			{
				"inboundTag": ["local"],
				"outboundTag": "proxy",
				"type": "field"
			}
		]
	}
}
```
In this configuration :
- Any request from `127.0.0.1:10808` will be proxied by `proxy` outbound.
- Resolving for outbound host will be proxied by `proxy_for_DNS` outbound.
- Dns request sending from xray will through 'udp over tcp' by `proxy_for_DNS` outbound.

**BE CAREFUL** outbound `proxy_for_DNS` must input ip as `address`, dont input domains here.

**Comment by BK8000L** [comment]
@timi-owo omg, it works! No more dns queries in Wireshark, thank you!

**Comment by mankhan10** [comment]
Link plz

**Comment by BK8000L** [comment]
@timi-owo can you please remove my ip and domain from your comment? it shows up on google lol

**Comment by timi-owo** [comment]
> @timi-owo can you please remove my ip and domain from your comment? it shows up on google lol

ok

**Comment by pundoo** [comment]
Any better solution for this? @RPRX This is basically leaking DNS when using inbound `socks` proxy (on windows), `http` works ok (sends dns queries to the vps)

**Comment by BK8000L** [comment]
@timi-owo can you please remove the comment about my ip address? thx
