### ISSUE TITLE
重提Routing Balancer的问题

### ISSUE THREAD

**Issue by BI7PRK** [XTLS/Xray-core#1146]
一段时间以前，使用了 Routing Balancer 配置，在负载均衡策略（strategy_type）的选项使用 “leastPing” 时，连接行为会变成直连。连接观测（Observatory）也已经进行了配置。

之前也有开过Issues，似乎没任何响应。接下来的一段时间里，经常折腾试图解决我认为可能是自己无知导致的问题。但是折腾这么久后，越来越怀疑这是个bug。
请大佬们指教一下。谢谢。

场景：
服务器有:  `serv_1, serv_2` 两台

Balancer config:

```PY
{
//...

selector: [ 'serv_' ],
strategy_type: “leastPing”   //<<-- 用这个选项时， 连接并不会走 【server】中的任何一项。而是直连 “direct”。
// 或者
strategy_type: “random”  //<<-- 这个则能成功随机使用【server】中的任何一项。

//...

}
```

**Comment by wy580477** [comment]
observatory项配置了么，leastPing策略需要observatory项的观察数据。

**Comment by azzvx** [comment]
Xray貌似并不支持设置Balancer策略。

Xray对BalancerObject的描述：
```
{
    "tag": "balancer",
    "selector": []
}
```
V2ray对BalancerObject的描述：
```
{
    "tag": "balancer",
    "selector": [],
    "strategy": {
      "type": "random"
    }
}
```

**Comment by chika0801** [comment]
xray不支持，这是v2fly 5.x版本的新功能，lz问错地方了

**Comment by yuhan6665** [comment]
https://github.com/XTLS/Xray-core/issues/872 我注意到你的观测地址是一个 404 尝试改成
https://www.google.com/generate_204

**Comment by BI7PRK** [comment]
感谢以上几位大佬解答。

> #872 我注意到你的观测地址是一个 404 尝试改成
> https://www.google.com/generate_204
观测地址已经尝试变更过好几个，结果是一样的。尝试有：
- 内置默认URL
- 回复提到的URL
- 自己搭的URL，返回 200 状态码
- github api 中的某个url  <<-- `这个不可取，因为URL随时有变动导致 404`

**Comment by yuhan6665** [comment]
感谢你的回复
xray 使用这个功能的人不多
你可以贴一下可行的配置 方便后来人

**Comment by BI7PRK** [comment]
经过百般折腾出来的主备切换方案。
至于前面踩过的命运陷阱就不提了。
正面总结一下配置思路，有不对的地方请大佬指教。

我自己的材料：


R4S

一个颇为友好的固件订制（极力推荐）：
https://github.com/kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1

我自己从大佬们forked来后再修改的：
https://github.com/BI7PRK/luci-app-v2ray

少不了的灵魂魔戒：（软件包 --> xray-geodata）
https://github.com/XTLS/Xray-core

辅助：
SmartDNS
方案：
两个或以上 VPS
Tag: S1, S2

```LOG

网络 -->> DHCP/DNS -->> Dnsmasq：
 	- 绑定53， DNS转发：127.0.0.1#5300
 	- 忽略解析文件
 	- 忽略 /etc/hosts

网络 -->> v2ray
 - 入站：
	// 以下是DNS服务
 	- tag:  dns_in 
	- 端口: 5300
	- 协议 Dokodemo-door
	- 地址：127.0.0.1
	- 端口 6053     << 这里是交给本地的 SmartDNS 服务。

	// 以下是透明代理服务
	-  tag:  transparent
	- 端口: 10809
	- 协议 Dokodemo-door
	- 自动转发: yes   


 - 出站

	- 配置那些服务器了，Tag: S1, S2
	- Freedom协议的域名策略要用：UseIP <<---关键配置
	- 别名/tag: dns_out， 协议: DNS  <<-- 提供给DNS处理的隧道

- DNS
	Tag: dns_servers
	禁用缓存：yes
	查询策略：UseIP <<---关键配置
	服务列表（仅2个）：
		1，208.67.222.222
		2，223.5.5.5

- 连接观测 
	- 检测地址: www.google.com/generate_204
	- 探测间隔: 5m
	- 出站标识前缀: S    <<--匹配了 [S1,S2]
- 路由负载均衡
	-Tag: balancer
	- 策略: leastPing
	- 匹配前缀: S    <<--匹配了 [S1,S2]
- 路由
	解析策略：IPOnDemand
	匹配算法：mph
	
	- Tag: DNS_IO:: 入站标识 dns_in，出站标识: dns_out <<-- 实现了DNS 内部隧道:  Dnsmasq ->> dns_in ->> dns_out --（A+AAAA）->> DNS（dns_servers）
	- Tag：DNS_proxy:: IP: [208.67.222.22, 1.1.1.1], 入站连接标识:dns_servers, 负载均衡器标识: balancer  <<-- 实现了 DNS --> 爬梯
	- Tag：DNS_direct:: IP: [2223.5.5.5], 入站连接标识:dns_servers， 出站连接标识：direct   <<--正常上路
	- (忽略其它隧道配置)
	- Tag：proxy_any_ips:: IP: 0.0.0.0/0,    负载均衡器标识: balancer -->>爬梯  <<<--- 这一条必须是放在最后
	
```

**Comment by OPPO9008** [comment]
> 感谢你的回复 xray 使用这个功能的人不多 你可以贴一下可行的完整配置 方便后来人

我测试 也是有这个问题， 确定了leastPing 是不可用的

**Comment by adamgonglj** [comment]
> 感谢你的回复 xray 使用这个功能的人不多 你可以贴一下可行的完整配置 方便后来人

我最近配置了balancer，就是好像功能并没有起作用。
