### ISSUE TITLE
相同的 config.json，在 Linux 端无效，在 Mac 端有效

### ISSUE THREAD

**Issue by YangEfei** [XTLS/Xray-core#1147]
如题，我在 Mac 端使用一套 vless + xtls 配置的代理服务器，使用的客户端为 V2RayU，使用的内核为 XRay 1.4.2，配置完成后可正常访问 Google 等外网。

之后将 config.json 复制到 Linux 服务器上进行配置（CentOS7），直接使用 XRay 加载该配置运行，XRay 版本为 1.5.5，通过 proxychains4 进行代理后发现打出的日志为权限无效或过期等内容，具体如下：

`2022/07/19 00:44:09 [Warning] [3842434669] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxx):  > x509: certificate has expired or is not yet valid: current time 2022-07-19T00:44:05+08:00 is after 2021-09-30T14:01:15Z transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxx):  > x509: certificate has expired or is not yet valid: current time 2022-07-19T00:44:06+08:00 is after 2021-09-30T14:01:15Z transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxx):  > x509: certificate has expired or is not yet valid: current time 2022-07-19T00:44:07+08:00 is after 2021-09-30T14:01:15Z transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxx):  > x509: certificate has expired or is not yet valid: current time 2022-07-19T00:44:08+08:00 is after 2021-09-30T14:01:15Z] > common/retry: all retry attempts failed
2022/07/19 00:44:09 [Info] [3842434669] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe`

其中服务器信息已做屏蔽。

不知道是否有相关经历的朋友可以分享一下经验？非常感谢！

**Comment by chika0801** [comment]
建议vps端 各客户端core升级成最新版本，帖下 客户端，vps端config.json内容

**Comment by chika0801** [comment]
看客户端配置你用的组合是vless ws tls。你能不能再找个vps用xray core搭好，vps端配置用一样的，测试下能不能通（排除法）
另外建议帖个vps的config文件内容。或加xray的tg群白天找水友求助（方便有人实时回复你）

**Comment by yaotthaha** [comment]
你不如检查一下证书（包括根证书）是不是过期了，或者是时间没有同步

**Comment by qist** [comment]
用的免费证书，Let‘s Encrypt 中间ca过期过建议升级系统ca证书

**Comment by fengqi** [comment]
重新签发一个证书，或者"allowInsecure": false这里改为true

**Comment by xqzr** [comment]
`fullchain.cer`
