### ISSUE TITLE
关于 http 代理的请求头伪装

### ISSUE THREAD

**Issue by loveqianool** [XTLS/Xray-core#1148]
这个 http 代理会验证 UA，使用 xray 的 http 伪装发现它会发出两条连接，第一条成功修改了 UA，但是第二条又变回了默认的 Go-http-client/1.1，请问有没有办法把第二条的 UA 也一起伪装了。
 
![微信截图_20220720183935](https://user-images.githubusercontent.com/739497/179962717-c405bfaf-b8f5-4bb9-a453-2a4c3c2fcb75.png)
![微信截图_20220720183949](https://user-images.githubusercontent.com/739497/179962730-c21d3b79-5530-48a5-9424-dcc9a1e83726.png)

使用下面的配置文件
```
{
  "log": {
    "loglevel": "info"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": "10808",
      "protocol": "socks"
    }
  ],
  "outbounds": [
    {
      "protocol": "http",
      "settings": {
        "servers": [
          {
            "address": "14.215.179.244",
            "port": 443
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "tcpSettings": {
          "header": {
            "type": "http",
            "request": {
              "headers": {
                "Host": [
                  "www.bing.com"
                ],
                "User-Agent": [
                  "baiduboxapp"
                ]
              }
            }
          }
        }
      },
      "tag": "proxy"
    }
  ]
}
```

**Comment by xqzr** [comment]
https://t.me/projectXray/1426596

**Comment by yuhan6665** [comment]
似乎是一个可信的 bug 加个 tag 等有缘大佬。。

**Comment by Fangliding** [comment]
很明显它只处理头不处理后续

**Comment by yuhan6665** [comment]
既然是我们发出的 connect 应该可以改 看了一下可能是这个地方
https://github.com/XTLS/Xray-core/blob/1593677b090e7e5684d075b43e5cac106621402e/proxy/http/client.go#L251

**Comment by Fangliding** [comment]
有没有一种可能http代理的header（include ua）是可以自定义的（）
https://xtls.github.io/config/outbounds/http.html#serverobject
```
  "headers": {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36",
    "Accept-Language": "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2"
  }
```

**Comment by Fangliding** [comment]
这个tcp的伪装 真的就是 发个包 意思一下 后面的部分肯定是对应协议的dialer再处理了 这是http代理刚好发的也是 http头 所以会给人一种 未按预期发送的行为
比如如果这里的出站的vmess后面直接就是乱码的vmess数据了
