### ISSUE TITLE
Does shadowsocks-2022 support dynamically add user?

### ISSUE THREAD

**Issue by pocketW** [XTLS/Xray-core#1149]
Hi,

I want to dynamically add users for an inbound using shadowsocks-2022_multi. However, I found that the `proxy.UserManager` interface has not been implemented by `shadowsocks-2022/inbound_multi.go`. Do you think is there any chance to implement this interface for shadowsocks-2022?

**Comment by moranno** [comment]
+1

**Comment by SaintShit** [comment]
+1
