### ISSUE TITLE
请问下载的 Xray-macos-64.zip 中 xray 如何通过命令行启动啊

### ISSUE THREAD

**Issue by LandChanning** [XTLS/Xray-core#115]
版本号是 1.1.5

RT，不能用 v2ray 类似的命令行启动了😋，也没找到相关说明

**Comment by rprx** [comment]
@LandChanning 比如？

**Comment by MarksonHon** [comment]
RT是啥 你的系统版本是啥

**Comment by LandChanning** [comment]
呃，比如之前下载 v2ray core 之后，可以在 mac 上使用 v2ray --config config.json 启动

**Comment by LandChanning** [comment]
macOs 10.15.7

> RT是啥 你的系统版本是啥

**Comment by rprx** [comment]
@LandChanning 问题可能存在，等待更多报告

**Comment by rprx** [comment]
等下，你此前是否完全没用过 Xray？而且启动都是 -config 吧，不是两个 -

**Comment by LandChanning** [comment]
> 等下，你此前是否完全没用过 Xray？而且启动都是 -config 吧，不是两个 -

对，第一次使用xray，之前一直在用 v2ray，都是参考 v2fly.org 的文档，
![image](https://user-images.githubusercontent.com/8448947/103290715-25010000-4a25-11eb-9497-4bf90dcba01d.png)

使用如下命令运行
![image](https://user-images.githubusercontent.com/8448947/103290418-75c42900-4a24-11eb-9027-4ce1f5173c7e.png)

换成 xray 后，想参考上述运行方法，提示 xray 命令不存在，已经将 xray 授权为可执行文件
![image](https://user-images.githubusercontent.com/8448947/103291201-2bdc4280-4a26-11eb-8d38-50dfee81b67a.png)

**Comment by AkinoKaede** [comment]
很簡單, xray 不在你設定的 $PATH 中
請使用
```bash
./xray run --config=/path/to/config.json
```

**Comment by rprx** [comment]
### ./xray

**Comment by LandChanning** [comment]
刚才着急截图命令输错了，加了 ./ 依然提示错误
![image](https://user-images.githubusercontent.com/8448947/103291617-23d0d280-4a27-11eb-967e-746c0a5cbea1.png)

**Comment by rprx** [comment]
不使用 sudo 呢

**Comment by eMeab** [comment]
> 刚才着急截图命令输错了，加了 ./ 依然提示错误
> ![image](https://user-images.githubusercontent.com/8448947/103291617-23d0d280-4a27-11eb-967e-746c0a5cbea1.png)

你先找到xray 这个程序在哪

**Comment by AkinoKaede** [comment]
> 刚才着急截图命令输错了，加了 ./ 依然提示错误
> ![image](https://user-images.githubusercontent.com/8448947/103291617-23d0d280-4a27-11eb-967e-746c0a5cbea1.png)

建議使用 `ls` 查看資料夾下是否存在為 xray 的執行檔

**Comment by LandChanning** [comment]
> 不使用 sudo 呢
可以运行了，不能使用 sudo，但需要授权可执行
![image](https://user-images.githubusercontent.com/8448947/103291958-cbe69b80-4a27-11eb-968e-16391e937fa3.png)

感谢各位回复

**Comment by rprx** [comment]
> 
> 
> @LandChanning 问题可能存在，等待更多报告

本来以为是改了配置加载相关代码而引入的问题

**Comment by LandChanning** [comment]
> > @LandChanning 问题可能存在，等待更多报告
> 
> 本来以为是改了配置加载相关代码而引入的问题

哈哈 耽误大家时间了 之前使用 v2ray时不用特意修改权限 就没往这想
