### ISSUE TITLE
希望＊ray能增加个基于sni的转发功能

### ISSUE THREAD

**Issue by wutongskype** [XTLS/Xray-core#1151]
有人可能会说现有的fallbacks，经过我的研究发现现在的fallbacks是先解密了在回落，有点缺点意思。如果回落点是个tls服务就不行了。

我希望的功能有点像nginx那个单端口复用，sni回落，但是nginx设置有点复杂，还要另外在开个程序，额外占用一个端口，还不能和ray同时用一个端口，作为前端两者只能取其一。

希望还可以添加个sni置换的功能。比如客户端带着sni baidu.com请求ray服务器，服务器把sni换成google.com在请求c上的tls服务。这其中ray服务器不负责建立tls链接，只是改一下sni然后转发给c，不知可行不。

**Comment by layou233** [comment]
@wutongskype nginx...

**Comment by Fangliding** [comment]
@wutongskype 啥后端服务必须有tls
回落的本身用途就是允许xray前置 回落去伪站或者nginx搭的正经网站 如果有更复杂的需求还是Nginx前置解决比较好
不太可能说为了方便单独加这一个功能

**Comment by iKira** [comment]
先捋清楚你这个需求的目的是什么。伪装？还是仅仅是单纯的转发？
你要伪装的话，Nginx前置是最佳的解决办法，配置起来并不复杂，你需要的是去研究Nginx配置文件的耐心而已。
如果你要实现转发的话，现有fallbacks、Nginx的stream配置都能实现转发。
VLESS fallbacks SNI shunt：https://github.com/XTLS/Xray-core/releases/tag/v1.2.2
