### ISSUE TITLE
Why is the Xray-core version number displayed differently?

### ISSUE THREAD

**Issue by fim5** [XTLS/Xray-core#1152]
Why is the Xray-core version number displayed differently
![v2rayN软件显示的Xray内核版本号](https://user-images.githubusercontent.com/105143810/180344083-cd8e6297-6e02-42ee-82b6-4750aeeecd44.PNG)
![下载的Xray内核版本号](https://user-images.githubusercontent.com/105143810/180344092-5f1e98ef-560c-48b9-8afd-c9aa6c67721a.jpg)
?

**Comment by fim5** [comment]
who knew? please reply quickly, thanks

**Comment by fim5** [comment]
What's causing this?

**Comment by chika0801** [comment]
https://github.com/XTLS/Xray-core/releases
最新版本是1.5.9

**Comment by yuhan6665** [comment]
Not an issue. Please check where is core located. You might have more than one
