### ISSUE TITLE
My country blocked xray TLS fingerprint

### ISSUE THREAD

**Issue by BK8000L** [XTLS/Xray-core#1153]
starting from a few days ago, i cant connect to my xray server using TLS, cipher doesnt matter, i can see TCP RST in wireshark after client hello
![image](https://user-images.githubusercontent.com/82240117/180474018-c1682f37-3b7e-43b1-b262-bef167daef0a.png)
its actually not only xray, dns-crypt with DoH doesnt work too, but i can access DoH web page using chrome.
I tried to use fake http header with user agent, but they blocked my server ip after i downloaded 1.5gb. Please help me recover TLS connection and set it up so they wont block my server IP.

**Comment by Lostlester07** [comment]
Who is this and what the Hell are you chatting about???

**Comment by chika0801** [comment]
你可以尝试一下 ping 或者使用 tcpping VPS的443端口 ，看看你到你的VPS网络状态是否正常。

或者再购买一个新VPS（即更换VPS的IP地址），买新域名申请SSL证书，建议你选尝试。
