### ISSUE TITLE
求助：Xray Server Active: failed 

### ISSUE THREAD

**Issue by Artoriasmercer** [XTLS/Xray-core#1155]
各位好
本人是纯小白，根据诸位大佬凝聚心血写出的这篇：https://xtls.github.io/document/level-0/ch01-preface.html 
一文搭建自己的Xray，在第七章的时候本来是绿色的Xray Server Active (running)，在进行了添加BBR之后就变成了红色的Xray Server Active: failed ，代码如下，恳请各位大佬的鼎力相助

mercer@racknerd-a72264:~$ sudo systemctl status xray
Warning: The unit file, source configuration file or drop-ins of xray.service changed on disk. Run
● xray.service - Xray Service
   Loaded: loaded (/etc/systemd/system/xray.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/xray.service.d
           └─10-donot_touch_single_conf.conf
   Active: failed (Result: exit-code) since Sat 2022-07-23 06:37:34 EDT; 2h 13min ago
     Docs: https://github.com/xtls
  Process: 453 ExecStart=/usr/local/bin/xray run -config /usr/local/etc/xray/config.json (code=exit
 Main PID: 453 (code=exited, status=23)

Jul 23 06:37:34 racknerd-a72264 systemd[1]: Started Xray Service.
Jul 23 06:37:34 racknerd-a72264 xray[453]: Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18
Jul 23 06:37:34 racknerd-a72264 xray[453]: A unified platform for anti-censorship.
Jul 23 06:37:34 racknerd-a72264 xray[453]: 2022/07/23 06:37:34 [Info] infra/conf/serial: Reading co
Jul 23 06:37:34 racknerd-a72264 xray[453]: Failed to start: main: failed to load config files: [/us
Jul 23 06:37:34 racknerd-a72264 systemd[1]: xray.service: Main process exited, code=exited, status=
Jul 23 06:37:34 racknerd-a72264 systemd[1]: xray.service: Failed with result 'exit-code'.

**Comment by chika0801** [comment]
反正你看完小小白教程了，重装vps系统，用我这个吧
https://github.com/chika0801/Xray-install

**Comment by wy580477** [comment]
journalctl -ru xray，看详细出错信息。

**Comment by Artoriasmercer** [comment]
> 
请问大佬我在安装Xray时一直提示bash: curl: command not found 是怎么回事呀？我按照网上的方法安装了curl可还是提示这个

**Comment by Artoriasmercer** [comment]
> 反正你看完小小白教程了，重装vps系统，用我这个吧 https://github.com/chika0801/Xray-install
请问大佬我在安装Xray时一直提示bash: curl: command not found 是怎么回事呀？我按照网上的方法安装了curl可还是提示这个

**Comment by chika0801** [comment]
> > 反正你看完小小白教程了，重装vps系统，用我这个吧 https://github.com/chika0801/Xray-install
> > 请问大佬我在安装Xray时一直提示bash: curl: command not found 是怎么回事呀？我按照网上的方法安装了curl可还是提示这个
apt install curl, 这样安的吗？是用root账户登录的吗

**Comment by Artoriasmercer** [comment]
> > > 反正你看完小小白教程了，重装vps系统，用我这个吧 https://github.com/chika0801/Xray-install
> > > 请问大佬我在安装Xray时一直提示bash: curl: command not found 是怎么回事呀？我按照网上的方法安装了curl可还是提示这个
> > > apt install curl, 这样安的吗？是用root账户登录的吗

用你这个指令可以了大佬，网上的都不行...
感谢感谢，我再继续下一步

**Comment by chika0801** [comment]
还有问题来xray的tg群问

**Comment by Artoriasmercer** [comment]
> 还有问题来xray的tg群问

lol，我还没建好梯子，有问题还是先劳烦您屈尊在这里解答吧！

**Comment by chika0801** [comment]
那你试试我那个教程吧，一步一步来，不要跳顺序，前言准备工作看清楚。。。

**Comment by Artoriasmercer** [comment]
> 那你试试我那个教程吧，一步一步来，不要跳顺序，前言准备工作看清楚。。。
好的老哥

**Comment by chika0801** [comment]
再送你一个这教程，我才当小白时觉得不错
https://github.com/uselibrary/Getting-Started-with-Linux/blob/main/tutorial.md

**Comment by Artoriasmercer** [comment]
> 再送你一个这教程，我才当小白时觉得不错 https://github.com/uselibrary/Getting-Started-with-Linux/blob/main/tutorial.md
> 
> vps linux操作入门向，介绍

好的，多谢老哥

**Comment by chika0801** [comment]
https://github.com/chika0801/Xray-examples/tree/main/Shadowsocks-2022-TCP
你出可以试试 这个组合 不需要申请ssl证书，非常简单

**Comment by Artoriasmercer** [comment]
> https://github.com/chika0801/Xray-examples/tree/main/Shadowsocks-2022-TCP 你出可以试试 这个组合 不需要申请ssl证书，非常简单
再次感谢
我在申请证书上卡了好久...，不过我一直用的V2ray，不太习惯SSH

**Comment by Artoriasmercer** [comment]
> https://github.com/chika0801/Xray-examples/tree/main/Shadowsocks-2022-TCP 你出可以试试 这个组合 不需要申请ssl证书，非常简单
老哥我再申请证书这一步：acme.sh --issue -d chika.example.com --standalone --keylength ec-256 时
把"chika.example.com"换成了我域名在Cloudflare上解析的两个网址结果都出现了验证错误
JAKE.NS.CLOUDFLARE.COM:Verify error:2803:f800:50::6ca2:c17a: Invalid response from http://jake.ns.cloudflare.com/.well-known/acme-challenge/3AFIlEtJwUlDsb2qN8G0Vrh3fwqR1Pw-_wxXP9_fI5g: 403
这是其中一段错误，请问是怎么回事？

**Comment by chika0801** [comment]
你ping下你的域名，看看IP是不是你VPS的IP。acme这个申请报错不好说哪里不对，光在网上这样你一句我一句的说

**Comment by Artoriasmercer** [comment]
> 你ping下你的域名，看看IP是不是你VPS的IP。acme这个申请报错不好说哪里不对，光在网上这样你一句我一句的说

ping出来确实不太一样，但同在加州…这种情况要重新设置子域名吗？

**Comment by chika0801** [comment]
你在cf的那个设置的网页，你看看你填的子域名，那里填ip的地方是不是填对了你vps的ip。

**Comment by Artoriasmercer** [comment]
> 你在cf的那个设置的网页，你看看你填的子域名，那里填ip的地方是不是填对了你vps的ip。

又打扰了老哥，申请证书这一步实在搞得我头大，我直接跳过这一步了。在下面配置V2ray时把地址填成了服务器ip地址，所有设置都按你的教程设置好了，测试服务器ping是正常的，但测试tcping就超时了，而且也没有效果（不能自由上网），请问这是怎么回事？一定要申请证书吗？

**Comment by yuhan6665** [comment]
建议搞最简单的 vmess 裸奔 https://github.com/XTLS/Xray-examples/tree/main/VMess-TCP
有兴趣再慢慢学习

**Comment by Artoriasmercer** [comment]
> apt install curl

感谢老哥，已经可以了

**Comment by chika0801** [comment]
能翻墙了，去youtube搜 翻墙 教程 ，有各种手把手的演示

**Comment by Artoriasmercer** [comment]
> 能翻墙了，去youtube搜 翻墙 教程 ，有各种手把手的演示

好的老哥，我从零开始学起

**Comment by yuhan6665** [comment]
to the stars and beyond!
