### ISSUE TITLE
IOS APP

### ISSUE THREAD

**Issue by libea18** [XTLS/Xray-core#1156]
hello. i need a developer ios that make a vpn app with xray-core 
anyone could help me ?

**Comment by libea18** [comment]
I hope you can help me.

**Comment by chika0801** [comment]
这里没有人能帮你

**Comment by yuhan6665** [comment]
You may find some dev from GitHub projects that publish these apps

**Comment by leecaa** [comment]
@libea18 我可以

**Comment by ghostwolf90** [comment]
@leecaa 
前輩你們好，小弟我也想開發iOS手機端的xray client app，這幾週已經收尋網路上很多方式，還未找到解法
目前只有學會 Network Extension的 VPN 和 DNS 功能，請問網路上有能夠使用的 XrayKit 的套件嗎？
目前有參考一些開源專案 Mango、OpenVpn-iOS、BearFree、ShadowsocksX-NG，還沒有一些方向
在請各位前輩給點提示，指引指引的前方的道路，感謝喔
我的TG: https://t.me/bit_lai
