### ISSUE TITLE
Xray-core被收录于awesome-vpn/wiki/Cores

### ISSUE THREAD

**Issue by hugetiny** [XTLS/Xray-core#1158]
https://github.com/awesome-vpn/awesome-vpn/wiki/Cores

请自由编辑，添加，纠错。维护一个完全公共开放的VPN维基百科吧)

**Comment by chika0801** [comment]
3qu

**Comment by hugetiny** [comment]
> 3qu

大量第三方测试显示Xray是目前最快的一个核心，请继续加油。
有空的话，请编辑wiki中不对的部分，本人对这一系列加密核心理解比较粗浅

**Comment by chika0801** [comment]
看了下wiki链接里的xray部分，Shadowsocks后面写下面的就行了（和你在SagerNet写的是一样的）
2022-blake3-aes-128-gcm
2022-blake3-aes-256-gcm
2022-blake3-chacha20-poly1305
AES-256-GCM
AES-128-GCM
ChaCha20-Poly1305

**Comment by hugetiny** [comment]
> 看了下wiki链接里的xray部分，Shadowsocks后面写下面的就行了（和你在SagerNet写的是一样的） 2022-blake3-aes-128-gcm 2022-blake3-aes-256-gcm 2022-blake3-chacha20-poly1305 AES-256-GCM AES-128-GCM ChaCha20-Poly1305
> 
> 我去wiki上修了下

好家伙，刚刚支持啊。Xray-core只有telegram吗？我想找找官方文档有吗

**Comment by chika0801** [comment]
> > 看了下wiki链接里的xray部分，Shadowsocks后面写下面的就行了（和你在SagerNet写的是一样的） 2022-blake3-aes-128-gcm 2022-blake3-aes-256-gcm 2022-blake3-chacha20-poly1305 AES-256-GCM AES-128-GCM ChaCha20-Poly1305
> > 我去wiki上修了下
> 
> 好家伙，刚刚支持啊。Xray-core只有telegram吗？我想找找官方文档有吗

文档
https://xtls.github.io/Xray-docs-next

还有tg群

**Comment by hugetiny** [comment]
欢迎多来改改
