### ISSUE TITLE
panic: Calling IP() on a DomainAddress

### ISSUE THREAD

**Issue by maskedeken** [XTLS/Xray-core#116]
在往buf.Buffer的UDP属性赋值的时候，创建
&net.UDPAddr{
    IP:   addr.IP(),
    Port: int(port.Value()),
}

但这里的addr是从addrParser.ReadAddressPort()而来，这里的addr有可能是域名，如果直接调用addr.IP()，会直接panic

func (domainAddress) IP() net.IP {
	panic("Calling IP() on a DomainAddress.")
}

**Comment by rprx** [comment]
两天前的提交已经修复 https://github.com/XTLS/Xray-core/commit/13ad3fddf6f7ff01fe9541b6c9f2dca6f7f87e4b

（不过最新的 commit 有问题，等下会 force

**Comment by maskedeken** [comment]
怎么解决循环引用的问题？

**Comment by rprx** [comment]
https://github.com/XTLS/Xray-core/commit/6bcac6cb1016295a0722015ec853ece135766cc3

**Comment by rprx** [comment]
> 
> 
> 怎么解决循环引用的问题？

https://github.com/XTLS/Xray-core/commit/6bcac6cb1016295a0722015ec853ece135766cc3

**Comment by rprx** [comment]
如果发现存在其它问题，也请直接反馈

比如目前发现任意门 TPROXY 那里不能缓存 conns，只能发一个包就 close，否则行为会异常，等下打算看看把 dial 改为 listen 的表现

**Comment by z719893361** [comment]
问题修复了吗，我用最新版碰到了相同的问题

**Comment by somebodywashere** [comment]
Also had this a few times on one server. Can you by any chance have any outbound with ForceIP?

I didn't checked the code but I didn't see this error anymore when I removed plain ForceIP from outbound (ForceIPv4v6 & ForceIPv6v4 is ok for me)

**Comment by somebodywashere** [comment]
> i posted my full config above, no I don't use any variant of ForceIP.

Oh, sorry, didn't pay enough attention. Now I see. That's strange than.

**Comment by sssagsag** [comment]
Hi @RPRX  , on core 1.8.23, this log appears and gets disconnected.(go1.22.5 linux/amd64)

XRAY: panic: Calling IP() on a DomainAddress.
XRAY: 0x15626b0?, {0x156c6d0?, 0xc009f7b9c8?})

**Comment by mmmray** [comment]
by the way, I patched the panic in question to print out the inner domain address, and it shows all kinds of normal hosts/domain names. Therefore this is not the same bug as #3628, where things such as `DomainAddress("192.168.0.1")` were constructed.

**Comment by mmmray** [comment]
Some update here. I patched xray with this patch on top of 1.8.23:

```diff
diff --git a/features/routing/session/context.go b/features/routing/session/context.go
index 3c9764b..5153b12 100644
--- a/features/routing/session/context.go
+++ b/features/routing/session/context.go
@@ -2,6 +2,8 @@ package session

 import (
        "context"
+       "time"
+       "fmt"

        "github.com/xtls/xray-core/common/net"
        "github.com/xtls/xray-core/common/session"
@@ -50,8 +52,15 @@ func (ctx *Context) GetTargetIPs() []net.IP {
                return nil
        }

-       if ctx.Outbound.Target.Address.Family().IsIP() {
-               return []net.IP{ctx.Outbound.Target.Address.IP()}
+       addr := ctx.Outbound.Target.Address
+
+       if addr.Family().IsIP() {
+               time.Sleep(time.Millisecond)
+               addr2 := ctx.Outbound.Target.Address
+               if !addr2.Family().IsIP() {
+                       fmt.Println("XDEBUG before: ", addr, "after: ", addr2)
+               }
+               return []net.IP{addr.IP()}
        }

        return nil
```

And am getting this output after a while:

```
XDEBUG before:  1.1.1.1 after:  mqtt-mini.facebook.com
XDEBUG before:  149.154.167.41 after:  scontent-fra3-2.cdninstagram.com
XDEBUG before:  157.240.253.61 after:  mtalk.google.com
XDEBUG before:  1.1.1.1 after:  mtalk.google.com
XDEBUG before:  157.240.253.61 after:  mtalk.google.com
XDEBUG before:  149.154.167.223 after:  www.google.com
```

I think it means that the `ctx` (or outbound, or target, ..) is being modified _while_ `GetTargetIPs` is being called, and that's why it's crashing.

**Comment by sssagsag** [comment]
> Hi @RPRX @yuhan6665 @mmmray , on core 1.8.23, this log appears and stop core .(go1.22.5 linux/amd64)
> 
> 2024/08/13 21:08:29 DEBUG - XRAY: 2334503 2024/08/13 21:08:29 DEBUG - XRAY: {0x156c6d0?, 0xc00977fc98?}) 2024/08/13 21:08:29 DEBUG - XRAY: github.com/xtls/xray-core/common/net.domainAddress.IP(...) 2024/08/13 21:08:29 DEBUG - XRAY: panic: Calling IP() on a DomainAddress.
> 
> what is problem ?

my problem sloved with this options in 1.8.23

protocol": "freedom",
      "settings": {
        "domainStrategy": "ForceIPv4

and 

routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [

The problem was in asIs  for freedom and routing

**Comment by yuhan6665** [comment]
We should fix crash even if you configured wrong, please try to post your stacktace

**Comment by mmmray** [comment]
I applied those config changes and got the same crash almost immediately

```
panic: Calling IP() on a DomainAddress.

goroutine 123018 [running]:
github.com/xtls/xray-core/common/net.domainAddress.IP(...)
    github.com/xtls/xray-core/common/net/address.go:172
github.com/xtls/xray-core/features/routing/session.(*Context).GetTargetIPs(0xc004175428)
    github.com/xtls/xray-core/features/routing/session/context.go:54 +0x5f
github.com/xtls/xray-core/app/router.(*MultiGeoIPMatcher).Apply(0xc0003a63e0, {0x156c770?, 0xc004175428?})
    github.com/xtls/xray-core/app/router/condition.go:143 +0x3e
github.com/xtls/xray-core/app/router.(*ConditionChan).Apply(0x495c9d?, {0x156c770, 0xc004175428})
    github.com/xtls/xray-core/app/router/condition.go:32 +0x5c
github.com/xtls/xray-core/app/router.(*Rule).Apply(...)
    github.com/xtls/xray-core/app/router/config.go:30
github.com/xtls/xray-core/app/router.(*Router).pickRouteInternal(0xc000367a40, {0x156c770, 0xc004175428})
    github.com/xtls/xray-core/app/router/router.go:196 +0x176
github.com/xtls/xray-core/app/router.(*Router).PickRoute(0x1562810?, {0x156c770?, 0xc004175428?})
    github.com/xtls/xray-core/app/router/router.go:84 +0x25
github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc000398fc0, {0x1562810, 0xc0050cd350}, 0xc00418dea0, {{0x15625a8, 0xc005974c10}, 0x1bb, 0x2})
    github.com/xtls/xray-core/app/dispatcher/default.go:420 +0x307
created by github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 123015
    github.com/xtls/xray-core/app/dispatcher/default.go:252 +0x56c
```

I think I know though where the race condition happens:

https://github.com/XTLS/Xray-core/blob/41d03d1856a5b16521610792601a20fb1195418e/app/dispatcher/default.go#L242

this line essentially mutates outbound concurrently. dispatch launches a goroutine, meaning that multiple dispatch calls can produce multiple goroutines that all access the same outbound concurrently.

**Comment by mmmray** [comment]
@yuhan6665 it's two completely unrelated connections going through the same outbound.

**Comment by yuhan6665** [comment]
That should be different contexts though

> it's two completely unrelated connections going through the same outbound.

**Comment by mmmray** [comment]
it's possible the contexts are different but pointing to the same outbound object.
