### ISSUE TITLE
正則表達式報錯 

### ISSUE THREAD

**Issue by rootmelo92118** [XTLS/Xray-core#1162]
## 配置
```
"dns": {
        "hosts": {
            "regexp:^(?!^google\\.com$|^v2ray\\.com$|.+\\.google\\.com$)": "192.168.33.5"
        },
        "servers": [
            "1.1.1.1"
        ]
       }
```

## 錯誤信息
```
Xray 1.5.9 (Xray, Penetrates Everything.) Custom (go1.18.4 darwin/arm64)
A unified platform for anti-censorship.
2022/07/26 18:01:57 [Info] infra/conf/serial: Reading config: tes.json
Failed to start: main: failed to create server > app/dns: failed to create hosts > app/dns: failed to create domain matcher > app/dns: failed to create str matcher > error parsing regexp: invalid or unsupported Perl syntax: `(?!`
```

## 報錯原因
[https://stackoverflow.com/questions/38933898/error-parsing-regexp-invalid-or-unsupported-perl-syntax](https://stackoverflow.com/questions/38933898/error-parsing-regexp-invalid-or-unsupported-perl-syntax)

**Go regex does not support lookarounds.**

## 期望結果

正則表達式正常加載

## 其他信息

網上搜索的結果是，Golang的regexp支援語法並不完整而導致錯誤出現，而我在網絡上也找到了一個庫與標準庫語法幾乎相同，但是支援更多正則表達式語法的庫：[https://github.com/dlclark/regexp2](https://github.com/dlclark/regexp2)
希望能使用這個取代原有的標準庫（建議使用 RE2 compatibility mode），因為其實你不知道使用者會寫出什麼樣的內容，兼容更完整的寫法也符合Xray給予自身「平台」的定位。

[https://blog.csdn.net/dianxin113/article/details/118769094](https://blog.csdn.net/dianxin113/article/details/118769094)

**Comment by yuhan6665** [comment]
能不能这样：不用 host 你给这三个 domain 分别配一个正常的 DNS 比如 1.1.1.1 然后剩下走一个黑洞 DNS

**Comment by rootmelo92118** [comment]
> 能不能这样：不用 host 你给这三个 domain 分别配一个正常的 DNS 比如 1.1.1.1 然后剩下走一个黑洞 DNS

也可以
