### ISSUE TITLE
内置dns设置成走block，但是最后还是成功打开了网页，为啥？

### ISSUE THREAD

**Issue by GeorgeRudd** [XTLS/Xray-core#1164]

**Comment by gubiao** [comment]
第二个DNS: 223.5.5.5的skipFallback设置为true, 否则第一个DNS查询失败还会继续查询第二个DNS, 日志中已经有体现了.

**Comment by chika0801** [comment]
看了客户端配置，日志

从日志来看 请救这域名解析 8.8.8.8命中block了，

2022/07/30 00:10:01 DNS accepted udp:8.8.8.8:53 [xray.system.ed9a2024-a739-4fba-896b-8f0e90d03cb8 -> block]

2022/07/30 00:10:01 [Info] transport/internet/udp: failed to handle UDP input > io: read/write on closed pipe

都是失败的

**Comment by chika0801** [comment]
测试了一下，也是DNS设置8.8.8.8 在路由里把8.8.8.8阻止，日志也是显示阻止，最后还是把这请求通过第1个出站（代理）送走了

不知道为什么，平时也没专门这样设置，不研究了。

**Comment by chika0801** [comment]
https://www.v2fly.org/config/dns.html#dns-%E5%A4%84%E7%90%86%E6%B5%81%E7%A8%8B

这流程图和解释文字，理解了下就是反正不行，就不解析了，（反正就不做本地的把域名解析成IP，也就不会进行IP相关的匹配）。
这个请求，就走第1个出站，去你VPS上了。这程序代码就这个逻辑吧，你不这样试，我也从没故意这样试过。反正作者写代码就这样设计的，问个什么也没意义。

**Comment by chika0801** [comment]
安卓代理原理和电脑 上的N 的hhttp scok不一样

第1 2 配置是透明代理模式 第3也是，只是DNS请求用系统的进行，不引入到xray配置里。

你要研究透明代下下的DNS工作流程可以，不在你1楼提出的在电脑上用N出现的现象，我觉得分2个类别讨论。

**Comment by yuhan6665** [comment]
*ray 牵涉好几个 dns 比较复杂

2022/07/30 00:10:05 [Info] features/**routing**/dns: resolve ip for mtalk.google.com > app/dns: returning nil for domain mtalk.google.com > multierr: context deadline exceeded | 

这个日志就是说路由使用的 dns 失败 结果会使 ray 只能通过域名分流 而不能 IP 分流

在浏览器 socks 代理时 路由里面写相应的 block 规则有效

**Comment by yuhan6665** [comment]
@GeorgeRudd 你说的没错
事实上 socks5 代理客户端 （包括安卓的仅代理模式）本来是不发出 dns 的 只是因为 *ray 特殊的 ip 分流 以及 freedom 直连时才需要
https://github.com/2dust/v2rayNG/wiki/Mode
