### ISSUE TITLE
这篇文章所说的xray问题解决了吗？

### ISSUE THREAD

**Issue by XxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxX0** [XTLS/Xray-core#1165]
https://github.com/e1732a364fed/xtls-/blob/main/README.md

**Comment by xqzr** [comment]
没有。

**Comment by aawwsslll** [comment]
不要用xtls了，我不信邪，使用xtls大概不到一个月443端口被屏蔽了。
同时我这个ip用tcp的vmess已经两年多都没事。证明这个xtls确实不够安全。速度对比vmess提升也就一点点。
建议现在还是VLESS + TCP + TLS + Nginx + WebSocket 回落并存模式，不过我443端口没了，想用也用不了，回vmess了。

**Comment by chika0801** [comment]
> 不要用xtls了，我不信邪，使用xtls大概不到一个月443端口被屏蔽了。 同时我这个ip用tcp的vmess已经两年多都没事。证明这个xtls确实不够安全。速度对比vmess提升也就一点点。 建议现在还是VLESS + TCP + TLS + Nginx + WebSocket 回落并存模式，不过我443端口没了，想用也用不了，回vmess了。

今天xray群各种组合都有被封443的xtls不背锅

**Comment by zxbiao** [comment]
> > 不要用xtls了，我不信邪，使用xtls大概不到一个月443端口被屏蔽了。 同时我这个ip用tcp的vmess已经两年多都没事。证明这个xtls确实不够安全。速度对比vmess提升也就一点点。 建议现在还是VLESS + TCP + TLS + Nginx + WebSocket 回落并存模式，不过我443端口没了，想用也用不了，回vmess了。
> 
> 今天xray群各种组合都有被封443的xtls不背锅

我用了xtls+vless+ws+grpc都没有被封443，怕不是流量过大或者IP段处于特别关注范围。dog.jpg

**Comment by aawwsslll** [comment]
> > > 不要用xtls了，我不信邪，使用xtls大概不到一个月443端口被屏蔽了。 同时我这个ip用tcp的vmess已经两年多都没事。证明这个xtls确实不够安全。速度对比vmess提升也就一点点。 建议现在还是VLESS + TCP + TLS + Nginx + WebSocket 回落并存模式，不过我443端口没了，想用也用不了，回vmess了。
> > 
> > 
> > 今天xray群各种组合都有被封443的xtls不背锅
> 
> 我用了xtls+vless+ws+grpc都没有被封443，怕不是流量过大或者IP段处于特别关注范围。dog.jpg

也就是前一天晚上逛了逛e站就被封了。

**Comment by aawwsslll** [comment]
> > 不要用xtls了，我不信邪，使用xtls大概不到一个月443端口被屏蔽了。 同时我这个ip用tcp的vmess已经两年多都没事。证明这个xtls确实不够安全。速度对比vmess提升也就一点点。 建议现在还是VLESS + TCP + TLS + Nginx + WebSocket 回落并存模式，不过我443端口没了，想用也用不了，回vmess了。
> 
> 今天xray群各种组合都有被封443的xtls不背锅

vmess用了两年多稳如老狗。

**Comment by SekiBetu** [comment]
没有解决，不过这次的封端口问题很有可能不是xtls带来的，而是tls over tls本身的特征，个人猜测

**Comment by aawwsslll** [comment]
> 没有解决，建议弃用xtls换用tls，不过这次的封端口问题很有可能不是xtls带来的，而是tls over tls本身的特征，个人猜测
确实，这次好像是大规模封443端口了，tls也有很多中招的。

**Comment by chika0801** [comment]
https://hostloc.com/thread-1082330-1-1.html

**Comment by yuhan6665** [comment]
已解决
