### ISSUE TITLE
内存占用疑问

### ISSUE THREAD

**Issue by tanbx** [XTLS/Xray-core#1172]
![屏幕截图 2022-08-05 101701 (2)](https://user-images.githubusercontent.com/108619712/182990116-986d5c43-1f6d-423b-9d90-8c52bc1b6f46.jpg)
![屏幕截图 2022-08-05 101853 (2)](https://user-images.githubusercontent.com/108619712/182990137-f00e2fe1-e5e5-4ca6-97af-dfbd52e351bd.jpg)
![屏幕截图 2022-08-05 101336 (2)](https://user-images.githubusercontent.com/108619712/182990148-995b5ab4-82e4-4661-b23d-8f2b4ce3dda7.jpg)

在虚拟机 ubuntu20.04 测试xray1.5.5，
用 cat /proc/{进程id}/status 指令看到的内存占用很大。
用 systemctl status xray 指令看到的就少很多。

不知道那个数据才靠谱。

我也也在虚拟机安装openwrt上测试过 1.5.9 。同样的config.json，结果系统显示的内存占用是等于ubuntu中进程占用的结果的。
![屏幕截图 2022-08-05 104927](https://user-images.githubusercontent.com/108619712/182991190-49188a6b-5729-4778-a4a8-2d9d00314422.jpg)

**Comment by changyp6** [comment]
I have the same issue.
My router always OOM-Kill xray these days.
It seems that this issue starts since July 26th.

**Comment by yichya** [comment]
看内存占用请以 VmRSS 为准。
Go 的 VmSize 因为它的内存分配机制设计，看起来会很高，它并不代表实际的内存占用。

**Comment by guaguaya66** [comment]
![image](https://user-images.githubusercontent.com/31442507/187076110-fa62a1ce-8d24-4f47-a24b-7d2847881ae7.png)

**Comment by zhfreal** [comment]
据我观察，服务端开启ss-2022后内存飙升, 系统1G内存可占500-600M内存，基本上吃满。在systemd启动脚本中加入MemoryMax=100M进行限制后，肉眼可见达到100M占用后不断GC，此时速率受影响。服务端其它vmess，vless,  trojan暂未发现内存问题。客户端开启ss-2022未发现内存问题。全部使用最新的xray版本。
已暂时使用shadowsocks-rust代替使用ss相关协议。

**Comment by Fangliding** [comment]
dup
