### ISSUE TITLE
FreeBSD环境下以服务端运行，使用KCP + 动态端口会在2小时后引发空指针panic，导致程序退出

### ISSUE THREAD

**Issue by cnbatch** [XTLS/Xray-core#1176]
同样的问题也出现在v2ray-core：https://github.com/v2fly/v2ray-core/issues/1807

两个月前已经有人给v2ray-core提交了修复代码：https://github.com/v2fly/v2ray-core/pull/1821
但还没merge。

当时同样的配置文件用在xray-core上也遇到了相同的错误

![Screenshot_20220809_013125_xray-core](https://user-images.githubusercontent.com/8210187/183481117-8d29171d-19d9-4d4b-8434-4f32d78bc1b2.png)

xray-core生成的错误日志：

> 2022/08/08 23:14:02 [Info] app/dns: DNS: created UDP client initialized for 108.61.10.10:53
> 2022/08/08 23:14:02 [Info] app/dns: DNS: created UDP client initialized for [2001:19f0:300:1704::6]:53
> 2022/08/08 23:14:02 [Info] app/dns: DNS: created localhost client
> 2022/08/08 23:14:02 [Info] transport/internet/udp: listening UDP on 0.0.0.0:51208
> 2022/08/08 23:14:02 [Info] transport/internet/kcp: listening on 0.0.0.0:51208
> 2022/08/08 23:14:02 [Info] transport/internet/udp: listening UDP on 0.0.0.0:56247
> 2022/08/08 23:14:02 [Info] transport/internet/kcp: listening on 0.0.0.0:56247
> 2022/08/08 23:14:02 [Info] transport/internet/udp: listening UDP on 0.0.0.0:30000
> 2022/08/08 23:14:02 [Info] transport/internet/kcp: listening on 0.0.0.0:30000
> 2022/08/08 23:14:02 [Warning] core: Xray 1.5.9 started
> 2022/08/09 00:16:02 [Info] transport/internet/udp: listening UDP on 0.0.0.0:55287
> 2022/08/09 00:16:02 [Info] transport/internet/kcp: listening on 0.0.0.0:55287
> 2022/08/09 00:16:02 [Info] transport/internet/udp: listening UDP on 0.0.0.0:54934
> 2022/08/09 00:16:02 [Info] transport/internet/kcp: listening on 0.0.0.0:54934

xray-core和v2ray-core能否一并修复这个bug？

**Comment by yuhan6665** [comment]
感谢反馈 搬了 等下个版本
