### ISSUE TITLE
rpc 开放的接口能写一些文档吗

### ISSUE THREAD

**Issue by lionelkali** [XTLS/Xray-core#1177]
我想用 java 来调用 xray rpc 接口，但是在我工程里作为客户端调 xray 接口的时候，比如 addInbound 接口，grpc 接口需要在 
 AddInboundRequest 对象里构建一个 InboundHandlerConfig 对象，InboundHandlerConfig 对象里参数不是很清楚，不知道传一些什么参数，希望大佬给予解惑

**Comment by yuhan6665** [comment]
Tag 就直接写没错
TypedMessage 可能需要从 receiverconfig 转换 跟 go 相似吧
https://github.com/crossfw/Xray-API-documents/blob/eb3b152dfda6e3503667be426b3caebe61bc81d5/examples/addInbound.go#L28

**Comment by lionelkali** [comment]
对就是 ReceiverSettings 这个参数和 ProxySettings 这两个参数不明白是做什么，具体有什么用，对应到 config.json配置文件里的字段是什么。
