### ISSUE TITLE
浏览器报错SSL_ERROR_BAD_SERVER

### ISSUE THREAD

**Issue by cuppasama** [XTLS/Xray-core#118]
配置一切ok，连接也没有任何问题，客户端日志正常，但打不开网页，浏览器报错SSL_ERROR_BAD_SERVER。
我非程序员，是初次尝试搭建vps，买域名、申请证书、搭网页的坑都趟了一遍，靠搜索走完全程。但这个问题貌似没人问过，谢谢！
ps：1.能够正常访问服务器端的静态网页。2.服务器端配置完全参照sample。

**Comment by AkinoKaede** [comment]
希望能公开配置文件方便检查问题（敏感信息请务必隐藏

**Comment by cuppasama** [comment]
> 
> 
> 希望能公开配置文件方便检查问题（敏感信息请务必隐藏

谢谢。但其实和example几乎一样。
{
    "log": {
        "loglevel": "info"
    },
    "inbounds": [
        {
            "port": 443, # 可以换成其他端口
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "XXXXXXXXXXXXXXXXXXXX", // 填写UUID，可以使用xray uuid生成
                        "flow": "xtls-rprx-direct",
                        "level": 0
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": www.baidu.com:80 // 回落配置，可以直接转到其他网站，例如"www.baidu.com:80"
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "alpn": [
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "/etc/letsencrypt/live/XXXXXXXXXXXXXX/fullchain.pem", // 换成你的证书，绝对路径
                            "keyFile": "/etc/letsencrypt/live/XXXXXXXXXXXXXXX/privkey.pem" // 换成你的私钥，绝对路径
                        }
                    ]
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ]
}

**Comment by cuppasama** [comment]
客户端配置如下（v2rayn自动生成）：
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "proxy",
      "port": 10808,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "XXXXXXXXXXXXXXXXXX",
            "port": 443,
            "users": [
              {
                "id": "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                "alterId": 0,
                "email": "t@t.tt",
                "security": "auto",
                "encryption": "none",
                "flow": "xtls-rprx-direct"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
          "allowInsecure": false
        }
      },
      "mux": {
        "enabled": false,
        "concurrency": -1
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    }
  ],
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api"
      }
    ]
  }
}

**Comment by xianren78** [comment]
你是真的fallback到www.baidu.com:80端口？实际上www.baidu.com:80端口已经不提供http服务了，直接转向https了。

**Comment by cuppasama** [comment]
> 
> 
> 你是真的fallback到www.baidu.com:80端口？实际上www.baidu.com:80端口已经不提供http服务了，直接转向https了。

了解了，不过这个和我遇到的问题是不是没有关系？

**Comment by cuppasama** [comment]
> 
> 
> 你是真的fallback到www.baidu.com:80端口？实际上www.baidu.com:80端口已经不提供http服务了，直接转向https了。

虽然并不是很懂，但我试着把回落注释掉了，还是存在同样的问题。

**Comment by cuppasama** [comment]
另外，po下nginx配置文件，我怀疑这里有问题。谢谢。
user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

# Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
#include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    server {
        listen       80 default_server;
        listen       [::]:80 default_server;
        server_name  XXXXXXXXXXXXXX www.XXXXXXXXXXXXXXX;
        rewrite ^(.*) https://$server_name$1 permanent;
        root         /usr/share/nginx/html;
        location / {
        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }

# Settings for a TLS enabled server.
#
    server {
        listen       443 ssl http2 default_server;
        server_name  XXXXXXXXXXXXXX www.XXXXXXXXXXXXXXXXX;
        root         /usr/share/nginx/html;
        ssl_certificate /etc/letsencrypt/live/XXXXXXXXXXXXXXXXXX/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/XXXXXXXXXXXXXXXXXXXX/privkey.pem;
        ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;
    ssl_ecdh_curve secp384r1;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_session_tickets off;
    keepalive_timeout 70;
#
        location / {
        }
#
        error_page 404 /404.html;
            location = /40x.html {
        }
#
        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }

}

**Comment by rprx** [comment]
Xray 和 Nginx 都是 443？

**Comment by cuppasama** [comment]
> Xray 和 Nginx 都是 443？

对的

**Comment by AkinoKaede** [comment]
> > Xray 和 Nginx 都是 443？
> 
> 对的

這樣是不行的…

**Comment by cuppasama** [comment]
> 
> 
> > > Xray 和 Nginx 都是 443？
> > 
> > 
> > 对的
> 
> 這樣是不行的…

照葫芦画瓢，看来我找错葫芦了。应该改成什么呢？

**Comment by xianren78** [comment]
[配置1：端口转发、端口回落，没有启用 PROXY protocol。配置2：进程转发、进程回落，没有启用 PROXY protocol。配置3：进程转发、进程回落，启用了 PROXY protocol。](https://github.com/lxhao61/integrated-examples/tree/master/v2ray(vless%2Btcp%2Btls)%2Bnginx)
配置1 2 3分别对应1_ 2_ 3_的两个文件，配对使用。

**Comment by cuppasama** [comment]
> 
> 
> [参考这个链接](https://github.com/lxhao61/integrated-examples/tree/master/v2ray(vless%2Btcp%2Btls)%2Bnginx)
> 配置1：端口转发、端口回落，没有启用 PROXY protocol。配置2：进程转发、进程回落，没有启用 PROXY protocol。配置3：进程转发、进程回落，启用了 PROXY protocol。配置1 2 3分别对应1_ 2_ 3_的两个文件，配对使用。

感谢。尝试了配置1，但仍未成功，情况如下（已经配置了服务器防火墙，打开了配置文件中涉及的全部81、82端口）。

客户端报错
v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vless/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp XXXXXXXX:443: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed

浏览器报错PR_END_OF_FILE_ERROR

且访问静态网页变得十分缓慢。/sigh

**Comment by xianren78** [comment]
看看你的xray和nginx启动了吗？

**Comment by cuppasama** [comment]
> 
> 
> 看看你的xray和nginx启动了吗？

bingo！配置文件多粘了行，xray没启动。。。

**Comment by cuppasama** [comment]
感谢各位！
由于本issue过于业余，主动关闭，再次表示感谢。
