### ISSUE TITLE
xray 最新版本启动的时候连的 IP 是啥

### ISSUE THREAD

**Issue by anozh** [XTLS/Xray-core#1181]
`lsof -Pn -p $(pstree xray)`

![telegram-cloud-photo-size-5-6321218195377205231-y](https://user-images.githubusercontent.com/5038951/184472371-f248946b-3254-466f-9c8f-7851d0307f62.jpg)

**Comment by cross-hello** [comment]
Oh, you stir up a terrible Sabbath.
Just want to hit you, **10.0.4.15** is your local host ip, and it showed that it replied to 80 port of **23.2.16.105**, which is your **xray** client.

Aug 13, 2022 14:49:19 anozh ***@***.***>:

**Comment by anozh** [comment]
> 

no prob. it's a private address

**Comment by anozh** [comment]
seems due to the oscpstapling

https://github.com/XTLS/Xray-core/blob/76638d793c4b48aa863e4ecc17c4a3b6b2915a4f/common/ocsp/ocsp.go#L69-L69
