### ISSUE TITLE
xray如何屏蔽访问国内IP

### ISSUE THREAD

**Issue by q3128923436** [XTLS/Xray-core#1182]
{
        "type": "field",
        "outboundTag": "block",
        "domain": [
          "geosite:cn"
        ],
        "enabled": true
      },
      {
        "type": "field",
        "outboundTag": "block",
        "ip": [
          "geoip:private",
          "geoip:cn"
        ],
        "enabled": true
      },
这段要插在哪里
  "outbounds": [{
    "protocol": "freedom",
    "settings": {}
  },{
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  },]
}

**Comment by chika0801** [comment]
https://github.com/chika0801/Xray-examples/blob/d5596420fafa216d80cad30423a129fc0e068ab9/VLESS-TCP-XTLS/config_server.json#L24

**Comment by xqzr** [comment]
https://t.me/projectXray/993013

**Comment by yuhan6665** [comment]
closing
