### ISSUE TITLE
gRPC rejected by proxy/trojan

### ISSUE THREAD

**Issue by malikshi** [XTLS/Xray-core#1183]
i have 3 servers with running same configuration, after 2-3 month per today one of servers can't connected to all gRPC.
access.log
```
2022/08/15 07:54:32 162.158.162.161:16652 rejected  proxy/trojan: not trojan protocol
2022/08/15 07:54:32 140.213.126.219:38249 rejected  proxy/trojan: not trojan protocol
2022/08/15 07:54:32 140.213.126.219:39824 rejected  proxy/trojan: not trojan protocol
2022/08/15 07:54:33 140.213.126.219:33193 rejected  proxy/trojan: not trojan protocol
2022/08/15 07:54:33 172.70.142.23:64864 rejected  proxy/trojan: not trojan protocol
2022/08/15 07:54:33 140.213.126.219:25425 rejected  proxy/trojan: not trojan protocol
2022/08/15 07:54:33 140.213.126.219:62974 rejected  proxy/trojan: not trojan protocol
2022/08/15 07:54:33 140.213.126.219:39840 rejected  proxy/trojan: not trojan protocol
2022/08/15 07:54:33 140.213.126.219:61353 rejected  proxy/trojan: not trojan protocol
2022/08/15 07:54:33 140.213.126.219:39838 rejected  proxy/trojan: not trojan protocol
2022/08/15 07:54:33 172.70.188.63:14346 rejected  proxy/trojan: not trojan protocol
2022/08/15 07:54:33 172.70.143.130:49284 rejected  proxy/trojan: not trojan protocol
2022/08/15 07:54:33 140.213.126.219:39842 rejected  proxy/trojan: not trojan protocol
2022/08/15 07:54:33 162.158.162.135:20358 rejected  proxy/trojan: not trojan protocol
2022/08/15 07:54:33 140.213.126.219:12087 rejected  proxy/trojan: not trojan protocol
2022/08/15 07:54:33 140.213.126.219:15783 rejected  proxy/trojan: not trojan protocol
2022/08/15 07:54:33 140.213.126.219:3357 rejected  proxy/trojan: not trojan protocol
2022/08/15 07:54:33 162.158.170.45:24904 rejected  proxy/trojan: not trojan protocol
2022/08/15 07:54:33 162.158.170.97:12722 rejected  proxy/trojan: not trojan protocol
2022/08/15 07:54:33 162.158.170.45:24920 rejected  proxy/trojan: not trojan protocol
2022/08/15 07:54:33 162.158.170.45:24922 rejected  proxy/trojan: not trojan protocol
2022/08/15 07:54:33 114.122.206.80:36852 rejected  proxy/trojan: not trojan protocol
2022/08/15 07:54:34 162.158.171.24:23822 rejected  proxy/trojan: not trojan protocol
2022/08/15 07:54:34 162.158.162.27:17074 rejected  proxy/trojan: not trojan protocol
2022/08/15 07:54:34 140.213.126.219:35257 rejected  proxy/trojan: not trojan protocol
2022/08/15 07:54:34 203.78.114.20:58141 rejected  proxy/trojan: not trojan protocol
```
nginx log

```
127.0.0.1 - - [15/Aug/2022:07:57:28 +0700] "POST /TESTNAMEGRPC/Tun HTTP/2.0" 502 150 "-" "grpc-go/1.48.0" "-"
127.0.0.1 - - [15/Aug/2022:07:57:28 +0700] "POST /TESTNAMEGRPC/Tun HTTP/2.0" 502 150 "-" "grpc-go/1.48.0" "-"
127.0.0.1 - - [15/Aug/2022:07:57:28 +0700] "POST /TESTNAMEGRPC/Tun HTTP/2.0" 502 150 "-" "grpc-go/1.48.0" "-"
127.0.0.1 - - [15/Aug/2022:07:57:28 +0700] "POST /TESTNAMEGRPC/Tun HTTP/2.0" 502 150 "-" "grpc-go/1.48.0" "-"
127.0.0.1 - - [15/Aug/2022:07:57:28 +0700] "POST /TESTNAMEGRPC/Tun HTTP/2.0" 502 150 "-" "grpc-go/1.48.0" "-"
127.0.0.1 - - [15/Aug/2022:07:57:28 +0700] "POST /TESTNAMEGRPC/Tun HTTP/2.0" 502 150 "-" "grpc-go/1.48.0" "-"
127.0.0.1 - - [15/Aug/2022:07:57:28 +0700] "POST /TESTNAMEGRPC/Tun HTTP/2.0" 502 150 "-" "grpc-go/1.48.0" "-"
127.0.0.1 - - [15/Aug/2022:07:57:28 +0700] "POST /TESTNAMEGRPC/Tun HTTP/2.0" 502 150 "-" "grpc-go/1.48.0" "-"
127.0.0.1 - - [15/Aug/2022:07:57:28 +0700] "POST /TESTNAMEGRPC/Tun HTTP/2.0" 502 150 "-" "grpc-go/1.48.0" "-"
127.0.0.1 - - [15/Aug/2022:07:57:28 +0700] "POST /TESTNAMEGRPC/Tun HTTP/2.0" 502 150 "-" "grpc-go/1.48.0" "-"
127.0.0.1 - - [15/Aug/2022:07:57:28 +0700] "POST /TESTNAMEGRPC/Tun HTTP/2.0" 502 150 "-" "grpc-go/1.48.0" "-"
127.0.0.1 - - [15/Aug/2022:07:57:28 +0700] "POST /TESTNAMEGRPC/Tun HTTP/2.0" 502 150 "-" "grpc-go/1.48.0" "-"
127.0.0.1 - - [15/Aug/2022:07:57:28 +0700] "POST /TESTNAMEGRPC/Tun HTTP/2.0" 502 150 "-" "grpc-go/1.48.0" "-"
127.0.0.1 - - [15/Aug/2022:07:57:29 +0700] "POST /TESTNAMEGRPC/Tun HTTP/2.0" 502 150 "-" "grpc-go/1.48.0" "-"
127.0.0.1 - - [15/Aug/2022:07:57:29 +0700] "POST /TESTNAMEGRPC/Tun HTTP/2.0" 502 150 "-" "grpc-go/1.48.0" "-"
127.0.0.1 - - [15/Aug/2022:07:57:29 +0700] "POST /TESTNAMEGRPC/Tun HTTP/2.0" 502 150 "-" "grpc-go/1.48.0" "-"
127.0.0.1 - - [15/Aug/2022:07:57:30 +0700] "POST /TESTNAMEGRPC/Tun HTTP/2.0" 502 150 "-" "grpc-go/1.48.0" "-"
127.0.0.1 - - [15/Aug/2022:07:57:30 +0700] "POST /TESTNAMEGRPC/Tun HTTP/2.0" 502 150 "-" "grpc-go/1.48.0" "-"
127.0.0.1 - - [15/Aug/2022:07:57:30 +0700] "POST /TESTNAMEGRPC/Tun HTTP/2.0" 502 150 "-" "grpc-go/1.48.0" "-"
127.0.0.1 - - [15/Aug/2022:07:57:30 +0700] "POST /TESTNAMEGRPC/Tun HTTP/2.0" 502 150 "-" "grpc-go/1.48.0" "-"
127.0.0.1 - - [15/Aug/2022:07:57:30 +0700] "POST /TESTNAMEGRPC/Tun HTTP/2.0" 502 150 "-" "grpc-go/1.48.0" "-"
127.0.0.1 - - [15/Aug/2022:07:57:31 +0700] "POST /TESTNAMEGRPC/Tun HTTP/2.0" 502 150 "-" "grpc-go/1.48.0" "-"
```

Trojan(front) fallback to nginx(grpc)

**Comment by malikshi** [comment]
It's fixed by changing subdomain/domain, but i want to know why grpc being rejected by Trojan?

**Comment by chouchjel** [comment]
兄弟，我也遇到了相同的问题，网上没找到解决办法，我试了换域名重装系统、换端口可以联通，但是第二天又老毛病犯了

**Comment by malikshi** [comment]
> Brother, I also encountered the same problem. I couldn’t find a solution on the Internet. I tried changing the domain name, reinstalling the system, and changing the port to connect, but the same old problem occurred the next day.

Which method do you use? Socket Unix or listen port try both of them.

**Comment by gunsluo** [comment]
I have the same issue.

**Comment by Octy-Sui** [comment]
I'm facing the same problem, while trying in this way Xray + trojan + gRPC + tsl + nginx (reverse proxy -> gRPC):
I attempted two approaches: using a port and listening to a socket, but encountered the same issue in both cases. The server displays the following error: 'app/proxyman/inbound: connection ends > proxy/trojan: invalid protocol or invalid user.' However, it functions correctly when connecting directly, bypassing Nginx.

Xray 1.8.6 (Xray, Penetrates Everything.) Custom (go1.21.4 linux/amd64)
server config as:
`
{
  "log": {
    "loglevel": "debug",
    "error": "/var/log/xray/error.log",
    "access": "/var/log/xray/access.log"
  },
  "inbounds": [
    {
      "listen": "/dev/shm/XrayTrojangRPC.socket,0666",
      "protocol": "trojan",
      "settings": {
        "clients": [
          {
            "password": "Trojan@1226!",
            "email": "user@example.com"
          }
        ],
      "streamSettings": {
        "network": "grpc",
        "grpcSettings": {
          "serviceName": "dailyorder",
          "idle_timeout": 60,
          "initial_windows_size": 65555
        },
        "security": "tls",
        "tlsSettings": {
          "certificates": [
            {
              "certificateFile": "/usr/local/etc/xray/fly.example.com_nginx/fly.example.com_bundle.crt",
              "keyFile": "/usr/local/etc/xray/fly.example.com_nginx/fly.example.com.key"
            }
          ]
        }
      }
    }
  }
  ],
  "outbounds": [
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "blocked",
      "protocol": "blackhole",
      "settings": {}
    }
  ]
}`

nginx config as:
`
proxy_connect_timeout 60s;
proxy_send_timeout 60s;
proxy_read_timeout 60s;
send_timeout 60s;
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name fly.example.com;

    ssl_certificate /usr/local/etc/xray/fly.example.com_nginx/fly.example.com_bundle.crt;
    ssl_certificate_key /usr/local/etc/xray/fly.example.com_nginx/fly.example.com.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384';
  
    client_header_timeout 1071906480m;
    keepalive_timeout 1071906480m;
  
    location /dailyorder {
        client_max_body_size 0;
        client_body_buffer_size 512k;
        client_body_timeout 1071906480m;
        grpc_read_timeout 1071906480m;
        grpc_pass unix:/dev/shm/XrayTrojangRPC.socket;
        grpc_set_header Host $http_host;
        grpc_set_header X-Real-IP $remote_addr;
        grpc_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
`

how did you solve it?

**Comment by Fangliding** [comment]
be blocked by fw(¿)
