### ISSUE TITLE
Shadowsocks 配置文件错误

### ISSUE THREAD

**Issue by ckckchen** [XTLS/Xray-core#1187]
```
{
"port":57235,
 "protocol": "shadowsocks",
"settings":{
"password": "WoshiniBABA@",
 "method": "2022-blake3-chacha20-poly1305",
  "network": "tcp,udp"
 }
           }
```
使用最新的2022时，配置文件报错
Failed to start: main: failed to create server > proxy/shadowsocks_2022: create service > decode psk: illegal base64 data at input byte 11
这是怎么回事呢

**Comment by FranzKafkaYu** [comment]
@ckckchen 查看example，ss2022对于psk长度存在要求

**Comment by Act0r1** [comment]
Failed to start: main: failed to create server > proxy/shadowsocks_2022: create service > bad key

it is mean, that i somewhere put don't correct key ? if yes, can u say where pls ?

**Comment by dimrus3** [comment]
openssl rand -base64 16   
The result obtained replaces the password
"password": "WoshiniBABA@",
