### ISSUE TITLE
XRAY 的shadowsocks使用

### ISSUE THREAD

**Issue by ckckchen** [XTLS/Xray-core#1188]
现在文档里对shadowsocks的描述不是很详细，我有以下几个配置问题。
1.https://github.com/XTLS/Xray-examples/tree/main/Shadowsocks-2022
这里客户端的配置文件上有一个  uot选项 ， 但是在官方文档里， 并没有看到这一条。必须要在客户端配置uot才能使用udp over tcp吗？

2. xray是否支持使用shadowsocks的插件呢？如果可以该怎么写配置文件呢？
3. 是否支持并建议回落到shadowsocks呢？ 如果可以回落的话能支持套CDN吗？
谢谢！

**Comment by chika0801** [comment]
1.https://github.com/XTLS/Xray-examples/tree/main/Shadowsocks-2022
这里客户端的配置文件上有一个 uot选项 ， 但是在官方文档里， 并没有看到这一条。必须要在客户端配置uot才能使用udp over tcp吗？

官方文档没及时更新，以更新说明为主吧。UOT参数是在客户端配置里加。


2.xray是否支持使用shadowsocks的插件呢？如果可以该怎么写配置文件呢？

SS插件指和这个类似的吗？https://github.com/v2fly/v2ray-examples/tree/master/Shadowsocks-Websocket-Web-TLS
我映像里Xray这边的SS没见人跑 ws tls的用法。


3.是否支持并建议回落到shadowsocks呢？ 如果可以回落的话能支持套CDN吗？
因为xray这边没见有ss套WS TLS的玩法。你要传统就vmess/vless ws tls过CDN。

这边的SS都是 TCP，用SS自己的加密 AEAD或2022版。
