### ISSUE TITLE
Best client for heavy congestion?

### ISSUE THREAD

**Issue by alcatraz-zz** [XTLS/Xray-core#1195]
Hey fellow users

This might be a bit offtopic. I'm using X-ray for years with a debian server and V2rayNG on all my clients. Problem is, when the network is congested I get MUCH lower bandwidth.

I'm curious to try optimizing the link for heavy congestion. What server and client offers the best performance? Server and client both on debian with the same (latest) kernel and bbrplus on both ends?

One thing is sure. There must be something better than older android versions running v2rayNG and xiaomi routers, right? I want to make the best out of the situation.

Thanks! /Mike

**Comment by yuhan6665** [comment]
1. try CDN like CF
2. try tcp BBR or hysteria
3. Add money

**Comment by alcatraz-zz** [comment]
Hysteria seems to work better actually. Thank you very much.

**Comment by yuhan6665** [comment]
closing
