### ISSUE TITLE
更新订阅失败

### ISSUE THREAD

**Issue by uppadavaya** [XTLS/Xray-core#1197]
更新Core成功
配置成功
[] [Shadowsocks] v2rayfree.eu.org - 美国华盛顿Cogent通信公司 16(38***18:5601)
启动服务(2022/8/27 9:45:50)...
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 windows/amd64)
A unified platform for anti-censorship.
2022/08/27 09:45:51 [Info] infra/conf/serial: Reading config: D:\Program files\websurf\v2rayN-Core\v2rayN-Core\config.json
2022/08/27 09:45:51 [Warning] core: Xray 1.5.5 started
2022/08/27 09:45:51 127.0.0.1:49688 accepted tcp:127.0.0.1:0 [api -> api]
下载开始...
下载开始...
2022/08/27 09:45:55 127.0.0.1:49690 accepted //github.com:443 [http -> proxy]
2022/08/27 09:45:55 127.0.0.1:49693 accepted //github.com:443 [http -> proxy]
2022/08/27 09:45:57 127.0.0.1:49695 accepted //objects.githubusercontent.com:443 [http -> proxy]
...10%
...20%
2022/08/27 09:46:03 127.0.0.1:49697 accepted //objects.githubusercontent.com:443 [http -> proxy]
...30%
...40%
...10%
...50%
...20%
...30%
...60%
...40%
...50%
...70%
...60%
...80%
...70%
...90%
...80%
2022/08/27 09:46:11 127.0.0.1:49699 accepted //mail.google.com:443 [http -> proxy]
...90%
...100%
下载 GeoFile: geoip 成功
...100%
下载 GeoFile: geosite 成功
更新订阅开始
git->开始获取订阅内容
git->The request returned with HTTP status code NotFound
git->无效的订阅内容
-------------------------------------------------------
remarks->开始获取订阅内容
remarks->无效的 URI: 未能确定 URI 的格式。
remarks->无效的订阅内容
-------------------------------------------------------
remarks->开始获取订阅内容
remarks->无效的 URI: 未能确定 URI 的格式。
remarks->无效的订阅内容
-------------------------------------------------------
remarks->开始获取订阅内容
remarks->无效的 URI: 未能确定 URI 的格式。
remarks->无效的订阅内容
-------------------------------------------------------
remarks->开始获取订阅内容
remarks->无效的 URI: 未能确定 URI 的格式。
remarks->无效的订阅内容
-------------------------------------------------------
remarks->开始获取订阅内容
remarks->无效的 URI: 未能确定 URI 的格式。
remarks->无效的订阅内容
-------------------------------------------------------
remarks->开始获取订阅内容
remarks->无效的 URI: 未能确定 URI 的格式。
remarks->无效的订阅内容
-------------------------------------------------------
更新订阅结束

**Comment by uppadavaya** [comment]
已经是最新版

**Comment by chika0801** [comment]
这问题和Xray程序无关。建议你去你买的机场发工单问机场的，或加你买的机场的TG群问老板。

**Comment by uppadavaya** [comment]
> 这问题和Xray程序无关。建议你去你买的机场发工单问机场的，或加你买的机场的TG群问老板。

我发错地方了吗，我不知道什么机场发工单哈，就是自己PC上的v2rayN（版本是5.32）更新订阅是这样子，会失败

**Comment by iwoomi** [comment]
> > 这问题和Xray程序无关。建议你去你买的机场发工单问机场的，或加你买的机场的TG群问老板。
> 
> 我发错地方了吗，我不知道什么机场发工单哈，就是自己PC上的v2rayN（版本是5.32）更新订阅是这样子，会失败

你更新订阅的那个订阅地址是谁给你的，你就去找谁

**Comment by uppadavaya** [comment]
> > > 这问题和Xray程序无关。建议你去你买的机场发工单问机场的，或加你买的机场的TG群问老板。
> > 
> > 
> > 我发错地方了吗，我不知道什么机场发工单哈，就是自己PC上的v2rayN（版本是5.32）更新订阅是这样子，会失败
> 
> 你更新订阅的那个订阅地址是谁给你的，你就去找谁

明白了。谢谢楼上两位

**Comment by chika0801** [comment]
> > > > 这问题和Xray程序无关。建议你去你买的机场发工单问机场的，或加你买的机场的TG群问老板。
> > > 
> > > 
> > > 我发错地方了吗，我不知道什么机场发工单哈，就是自己PC上的v2rayN（版本是5.32）更新订阅是这样子，会失败
> > 
> > 
> > 你更新订阅的那个订阅地址是谁给你的，你就去找谁
> 
> 明白了。谢谢楼上两位

那把这ISS关闭下

**Comment by yuhan6665** [comment]
closing
