### ISSUE TITLE
1.5.10版本UOT失效（UDP over TCP）

### ISSUE THREAD

**Issue by jh0072110** [XTLS/Xray-core#1204]
服务端和客户端换回1.5.9一切安好…
SS2022……
抱歉我没有拉logs……

**Comment by jh0072110** [comment]
唉，完全没人理这个issue，那我更新汇报一下，1.6.0的UOT依旧是嗝屁的…

**Comment by timi-owo** [comment]
1.5.10 之前的版本有这个问题吗

**Comment by liuzipeng** [comment]
请问一下 uot一定要ss2022 才支持吗？

**Comment by jh0072110** [comment]
> 请问一下 uot一定要ss2022 才支持吗？
支不支持反正现在都是嗝屁的，最后一个能用的版本是1.5.9

**Comment by jh0072110** [comment]
这个bug不出意外的传承到了1.6.1……

**Comment by jh0072110** [comment]
> for me just [v1.5.8](https://github.com/XTLS/Xray-core/releases/tag/v1.5.8) works. next versions do not work with _"uot": true_

这么奇怪的吗……

**Comment by escapezn** [comment]
xray 1.6.1服务端，clash.meta 1.13.1客户端，ss+ws uot正常

**Comment by jh0072110** [comment]
> xray 1.6.1服务端，clash.meta 1.13.1客户端，ss+ws uot正常
> 
> 更新：使用Android clash.meta客户端确实发现xray1.6.1有问题，换成1.5.9正常，但Windows上1.6.1无问题

那看起来是linux端的问题？（我瞎说的，反正没人修…

**Comment by jh0072110** [comment]
The same issue in 1.6.2

**Comment by database64128** [comment]
@hdid UoT is not part of the Shadowsocks 2022 protocol.

Related discussions: shadowsocks/shadowsocks-rust#834

**Comment by jh0072110** [comment]
Honestly I don't care if it's the original function of shadowsocks, but it is a feature that xray wrote in the old release notes, so it's an issue, unless xray decides to no longer support this feature :)

**Comment by database64128** [comment]
@hdid https://github.com/shadowsocks/shadowsocks-rust/issues/834#issuecomment-1121254412

**Comment by jh0072110** [comment]
好久没关注，已经默默被修好了（感恩！
