### ISSUE TITLE
xray错误23

### ISSUE THREAD

**Issue by gzz4454** [XTLS/Xray-core#1205]
{
    "log": {
        "loglevel": "error",
        "access": "/var/log/xray/access.log",
        "error": "/var/log/xray/error.log"
    },

    "inbounds": [
        {
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "e7743b24-27ec-11ed-a261-0242ac120002", 
                        "flow": "xtls-rprx-direct",
                        "level": 0,
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": 8080
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "alpn": [
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "/etc/ssl/private/域名.crt",
                            "keyFile": "/etc/ssl/private/域名.key"
                        }
                    ]
                }
            }
        }
    ],
       
  "outbounds": [
        {
            "protocol": "freedom"
        }
    ]
}
请问config文件有什么问题?

**Comment by gzz4454** [comment]
域名在config文件里已经改为网址了
然后启动xray的时候提示加载config文件出错

**Comment by FranzKafkaYu** [comment]
@gzz4454 Xray完整的错误日志贴一下

**Comment by gzz4454** [comment]
> @gzz4454 Xray完整的错误日志贴一下

xray没有启动成功，日志文件里没有内容

**Comment by FranzKafkaYu** [comment]
@gzz4454 systemctl status xray应该能看到一些错误信息，你也可以先通过xray命令行检查config，使用xray help run获取帮助

**Comment by gzz4454** [comment]
> @gzz4454 systemctl status xray应该能看到一些错误信息，你也可以先通过xray命令行检查config，使用xray help run获取帮助

这个命令就是提示加载config文件出错，所以我才把我config贴了出来，emmm xray help run等过几天我再试一下，配置文件没什么大问题是吗？

**Comment by chika0801** [comment]
chown -R nobody:nogroup /etc/ssl/private/

试试改证书权限

**Comment by gzz4454** [comment]
> chown -R nobody:nogroup /etc/ssl/private/
> 
> 试试改证书权限

755吗？

**Comment by gzz4454** [comment]
> chown -R nobody:nogroup /etc/ssl/private/
> 
> 试试改证书权限

文件夹和证书都要755权限？我好想改了文件夹的，证书的没改

**Comment by chika0801** [comment]
> > chown -R nobody:nogroup /etc/ssl/private/
> > 试试改证书权限
> 
> 文件夹和证书都要755权限？我好想改了文件夹的，证书的没改

你试下了来

**Comment by uid36216** [comment]
直接命令行运行就知道哪里错了

**Comment by gzz4454** [comment]
> @gzz4454 systemctl status xray应该能看到一些错误信息，你也可以先通过xray命令行检查config，使用xray help run获取帮助

xray run help
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 linux/amd64)
A unified platform for anti-censorship.
2022/08/31 06:47:43 Using config from STDIN
2022/08/31 06:47:43 [Info] infra/conf/serial: Reading config: stdin:
到这一步就卡住不动了

**Comment by gzz4454** [comment]
> 直接命令行运行就知道哪里错了

xray run help
Xray 1.5.5 (Xray, Penetrates Everything.) Custom (go1.18.1 linux/amd64)
A unified platform for anti-censorship.
2022/08/31 06:47:43 Using config from STDIN
2022/08/31 06:47:43 [Info] infra/conf/serial: Reading config: stdin:
到这一步就卡住不动了

**Comment by gzz4454** [comment]
改了log文件等级为warning后就出现一行
2022/08/31 06:56:48 [Warning] core: Xray 1.5.5 started

**Comment by FranzKafkaYu** [comment]
> 改了log文件等级为warning后就出现一行 2022/08/31 06:56:48 [Warning] core: Xray 1.5.5 started

这表明没有错误，正常启动。

**Comment by gzz4454** [comment]
> > 改了log文件等级为warning后就出现一行 2022/08/31 06:56:48 [Warning] core: Xray 1.5.5 started
> 
> 你需要根据xray run help的命令提示来测试config....

!!!明明之前还是各种报错，然后重新试了一下果然好了...

**Comment by gzz4454** [comment]
莫名其妙的解决了，谢谢各位

**Comment by FranzKafkaYu** [comment]
> 改了log文件等级为warning后就出现一行 2022/08/31 06:56:48 [Warning] core: Xray 1.5.5 started

如以下命令：
./xray-linux-amd64  -c config.json  -test

如果测试OK，你会得到Configuration OK的提示
