### ISSUE TITLE
版本疑问

### ISSUE THREAD

**Issue by dakezuo** [XTLS/Xray-core#1206]
请问，我在服务端内核为1.4.3及1.4.3以前的内核可以正常使用，1.4.3以后也就是1.4.5开始的内核无法正常使用，也不是客户端内核太低，客户端内核为1.5.9，我也查看了版本更新日志，1.4.3到1.4.5的更新似乎并没有多少区别，有和我一样的人吗？以及能否告知需要修改什么来适配现在的版本内核

**Comment by FranzKafkaYu** [comment]
@dakezuo 应该只有你。针对这个问题还是提供一下日志比较好。

**Comment by dakezuo** [comment]
> @dakezuo 应该只有你。针对这个问题还是提供一下日志比较好。


2022/09/01 13:58:10 tcp:127.0.0.1:53633 accepted tcp:chrome.google.com:443 [proxy]
2022/09/01 13:58:34 127.0.0.1:53659 accepted //apresolve.spotify.com:443 [proxy]
2022/09/01 13:58:44 127.0.0.1:53666 accepted //104.199.240.237:4070 [proxy]
2022/09/01 13:58:45 tcp:127.0.0.1:53670 accepted tcp:google.com:443 [proxy]

日志里面只显示接收到了请求，也没报错之类的，但就是无法使用，切回1.4.3之后就能使用了，很奇怪

**Comment by FranzKafkaYu** [comment]
@dakezuo 问题应该出在你的配置上，使用的什么协议呢

**Comment by dakezuo** [comment]
> @dakezuo 问题应该出在你的配置上，使用的什么协议呢

vmess协议

**Comment by FranzKafkaYu** [comment]
@dakezuo 检查一下altetId

**Comment by dakezuo** [comment]
> @dakezuo 检查一下altetId

我重新查阅了更新日志，看到了这一条，⚠️ VMESS AEAD 已在 2022 年 1 月 1 日强制启用 请注意更新服务端 移除 alterId 参数，看来有可能是这个的原因，我是从老版的v2-ui面板迁移到x-ui的，看来我需要修改下里面之前的配置参数

**Comment by yuhan6665** [comment]
close as solved
