### ISSUE TITLE
nginx、xray443端口冲突问题

### ISSUE THREAD

**Issue by CussiusKon** [XTLS/Xray-core#1210]
```
nginx 监听端口：
server {
    listen 80;
    listen [::]:80;
    server_name xxx.com;
    return 301 https://$host$request_uri;
}
...............


xray:
"inbounds": [
    {
      "listen": "0.0.0.0",
      "port": 443,
      "protocol": "vless",
      ................
  }
]
```
xray监听443,正常使用。后来我在nginx中添加了如下监听端口，xray配置不变，导致nginx和xray端口冲突，总有一个启动不了
```
server {
  listen 80 default_server;
  listen [::]:80 default_server;

  listen 443 default_server;
  listen [::]:443 default_server;
  ssl_reject_handshake on;

  server_name _;
  return 444;
}
```
但是单独使用nginx是没有问题的，这种情况正常的吗还是是我配置有问题，有什么办法可以解决吗，谢谢

**Comment by chika0801** [comment]
是这样的，不能2个程序都监听443

**Comment by chika0801** [comment]
使用vless回落功能
我的配置示例
https://github.com/chika0801/Xray-examples/tree/main/VLESS-TCP-TLS

**Comment by CussiusKon** [comment]
> 是这样的，不能2个程序都监听443

但是单独nginx上面形式的监听两个443是可以的

**Comment by zhfreal** [comment]
> 

nginx一个主实例http服务可以多域名共享443，然后可以启动多个子进程共同服务。但两个主实例就不能同时兼听443。
甚至一个主实例也不能同时使stream负载服务和HTTP服务（也就是上面的应用）同时监听443。

**Comment by chika0801** [comment]
> > 是这样的，不能2个程序都监听443
> 
> 想错了。有没有可以让xray拒绝直接通过ip进行访问的办法呢

xray前置接收443这种组合里的
https://github.com/chika0801/Xray-examples/blob/beaa6bb7fc2f632f915115b5f37578120c28a6fd/VLESS-TCP-TLS/config_server.json#L61
这个参数

可能是你问的意思

**Comment by CussiusKon** [comment]
> 

是我要的效果，翻了文档没找到。非常感谢

**Comment by chika0801** [comment]
那你把iss关了
