### ISSUE TITLE
xray traffic problem

### ISSUE THREAD

**Issue by xkjdox** [XTLS/Xray-core#1213]
after update to 1.5.10 xray-traffic cannot to used
when i try to downgrade to 1.5.8 its normal again

**Comment by yuhan6665** [comment]
should be fixed in 1.6.0. Close for now

**Comment by adisubagja** [comment]
same
now im using 1.6.0 have this issue now

**Comment by xkjdox** [comment]
> should be fixed in 1.6.0. Close for now

not working too

**Comment by alirezaac** [comment]
i have the issue on one of my machines i cannot use xray above 1.5.3.
