### ISSUE TITLE
Add SIP003 plugin support to Shadowsocks

### ISSUE THREAD

**Issue by ghost** [XTLS/Xray-core#1216]
Like this https://github.com/SagerNet/v2ray-core/commit/eca94065a44e92ca805ca2f97908759b94909cbe

**Comment by lxhao61** [comment]
直接配置就可以实现你想要的。
[v2ray(SS+v2ray-plugin)+caddy\nginx](https://github.com/lxhao61/integrated-examples/tree/main/v2ray(SS%2Bv2ray-plugin)%2Bcaddy%5Cnginx)
[v2ray(SS+grpc)+caddy\nginx](https://github.com/lxhao61/integrated-examples/tree/main/v2ray(SS%2Bgrpc)%2Bcaddy%5Cnginx)
