### ISSUE TITLE
Xray-windows-64 v1.5.10， Cylance报有木马，可能是误报

### ISSUE THREAD

**Issue by AndyJiangPro** [XTLS/Xray-core#1218]
Xray-windows-64 v1.5.10， Cylance报有木马 Trojan.Malware.300983.susgen
[Xray-windows-64.zip](https://github.com/XTLS/Xray-core/releases/download/v1.5.10/Xray-windows-64.zip)

扫描结果链接： https://www.virustotal.com/gui/file/de9704d8bc67f331950b657036ffc02c8298db8f8fb50406c5fbcd47e556f426

**Comment by chika0801** [comment]
误报
隔壁也有类似
https://github.com/EAimTY/tuic/issues/76

**Comment by Fangliding** [comment]
木马（Trojan） 那Xray确实有（）
