### ISSUE TITLE
适配Apple silicon

### ISSUE THREAD

**Issue by TinyFlag** [XTLS/Xray-core#122]
go语言现已原生支持Apple silicon平台,希望在release中有macOS-arm版

**Comment by rprx** [comment]
Go 1.16 正式版出来就有了，不远了

**Comment by badO1a5A90** [comment]
似乎现在先自行clone go的仓库编译go，然后用自己编译的go编译xray是可行的。quic部分会有一些问题，简单的处理方式是不编译进去即可。

**Comment by soffchen** [comment]
github.com/lucas-clemente/quic-go 最新也支持 1.16 了，我觉得可以迁移支持 1.16rc 了

**Comment by badO1a5A90** [comment]
> github.com/lucas-clemente/quic-go 最新也支持 1.16 了，我觉得可以迁移支持 1.16rc 了

确实没问题了.

**Comment by badO1a5A90** [comment]
https://github.com/XTLS/Xray-core/releases/tag/v1.2.2

从 v1.2.2 之后都会有了
