### ISSUE TITLE
it seems that xray 1.5.5 doesnt work on win10 arm32 1709...

### ISSUE THREAD

**Issue by vqsld** [XTLS/Xray-core#1221]
https://github.com/vqsld/logs/blob/main/error-xray1.5.5.txt
**but version 1.5.4 does work well.**

**Comment by yuhan6665** [comment]
Seems a go 1.18 runtime issue. Can you try newer builds:
https://github.com/XTLS/Xray-core/actions/runs/3071755835

**Comment by vqsld** [comment]
> Seems a go 1.18 runtime issue. Can you try newer builds: https://github.com/XTLS/Xray-core/actions/runs/3071755835

**sorry,im just a user not a developer,so i dont konw how to make binary package...**

**Comment by yuhan6665** [comment]
Can you try upgrade to xray 1.6.0 and see if it still show error? If so can you post the new error log?

**Comment by vqsld** [comment]
> Can you try upgrade to xray 1.6.0 and see if it still show error? If so can you post the new error log?

the same...😥

**Comment by vqsld** [comment]
> Can you try upgrade to xray 1.6.0 and see if it still show error? If so can you post the new error log?

this is the error log of the version 1.6.0.
[https://github.com/vqsld/logs/blob/main/error-xray-1.6.0.txt](url)

**Comment by yuhan6665** [comment]
From what I can tell, it is golang runtime issue since 1.18. Can you submit a bug report to https://github.com/golang/go with the log and your system info? Thank you!
