### ISSUE TITLE
Shadowsocks-2022 too many open files 问题

### ISSUE THREAD

**Issue by winds365** [XTLS/Xray-core#1224]
在一台中转服务器上，玩游戏3-4个小时左右，出现大量failed to accepted raw connections > accept tcp [::]:12345: accept4: too many open files日志
然后游戏掉线，只能重启中转服务器的xray
配置文件为
inbounds: [shadowsocks]
outbounds: [shadowsocks]
xray版本 v1.5.10

顺便问下，[示例](https://github.com/XTLS/Xray-examples/tree/main/Shadowsocks-2022)里的服务端 JSON (中转)，是部署到中转服务器上的吗？那为什么outbounds里又是直连？

**Comment by mand-byte** [comment]
> 在一台中转服务器上，玩游戏3-4个小时左右，出现大量failed to accepted raw connections > accept tcp [::]:12345: accept4: too many open files日志 然后游戏掉线，只能重启中转服务器的xray 配置文件为 inbounds: [shadowsocks] outbounds: [shadowsocks] xray版本 v1.5.10
> 
> 顺便问下，[示例](https://github.com/XTLS/Xray-examples/tree/main/Shadowsocks-2022)里的服务端 JSON (中转)，是部署到中转服务器上的吗？那为什么outbounds里又是直连？

/etc/systemd/system/multi-user.target.wants/xray.service
[Service]
添加
```
LimitNPROC=10000
LimitNOFILE=1000000
`` `

**Comment by winds365** [comment]
> > 在一台中转服务器上，玩游戏3-4个小时左右，出现大量failed to accepted raw connections > accept tcp [::]:12345: accept4: too many open files日志 然后游戏掉线，只能重启中转服务器的xray 配置文件为 inbounds: [shadowsocks] outbounds: [shadowsocks] xray版本 v1.5.10
> > 顺便问下，[示例](https://github.com/XTLS/Xray-examples/tree/main/Shadowsocks-2022)里的服务端 JSON (中转)，是部署到中转服务器上的吗？那为什么outbounds里又是直连？
> 
> /etc/systemd/system/multi-user.target.wants/xray.service [Service] 添加
> 
> ```
> LimitNPROC=10000
> LimitNOFILE=1000000
> ```

这前添加过
LimitNOFILE=1000000
但是还是会断流
