### ISSUE TITLE
能不能使用外部Fakedns 

### ISSUE THREAD

**Issue by y1rn** [XTLS/Xray-core#1225]
background：
    手机端使用shadowrocket，规则有3M。启动加载和每次请求对手机电量多少造成压力。

问题：
    有没有方案把url match 放到私有dns server，代理客户端只做mapping和地址覆盖。

**Comment by wy16W2pIilK1xgqN** [comment]
不行
Fakedns 主要作用是 把域名的真实IP 对应到另一个IP上，
外部应用没法传递这些数据。

请关闭这个问题吧。

**Comment by yichya** [comment]
可以用 dokodemo-door 自己做，但是 3m 的规则怕是难了点，而且对于 wildcard 的域名就还是得有个跟 fakedns 一样的机制做自动分配，所以怕是不行（

**Comment by y1rn** [comment]
> 不行 Fakedns 主要作用是 把域名的真实IP 对应到另一个IP上， 外部应用没法传递这些数据。
> 
> 请关闭这个问题吧。

可以把私有dns查询到的ip作为fake ip，xray client只需缓存一下这个mapping，主要问题是这个缓存mapping的生命周期

**Comment by y1rn** [comment]
我在[adguardhome](https://github.com/y1rn/AdGuardHome) 添加fakedns配置
