### ISSUE TITLE
关于监听UDP流量问题

### ISSUE THREAD

**Issue by YongChingShieh** [XTLS/Xray-core#1228]
文档 https://xtls.github.io/config/outbounds/vless.html#userobject 里面说
`
启用了 Xray-core 的 XTLS 时，通往 UDP 443 端口的流量默认会被拦截（一般情况下为 QUIC），这样应用就不会使用 QUIC 而会使用 TLS，XTLS 才会真正生效。实际上，QUIC 本身也不适合被代理，因为 QUIC 自带了 TCP 的功能，它作为 UDP 流量在通过 VLESS 协议传输时，底层协议为 TCP，就相当于两层 TCP 了。
若不需要拦截，请在客户端填写 xtls-rprx-*-udp443，服务端不变。
`

那么请问如何在服务端关闭拦截通往 UDP 443 端口的流量?

**Comment by xqzr** [comment]
`服务端不变`
Chrome Socks5 UDP 没有支持。

**Comment by YongChingShieh** [comment]
> `服务端不变` Chrome Socks5 UDP 没有支持。

在服务器上同时部署了 tuic(http/3 监听443 udp流量)  xray(监听443)
出现的情况是xray把443端口上tpc和udp都全部拦截  以致于tuic无法收到来自客户端的udp流量

**Comment by YongChingShieh** [comment]
> tuic换成其它端口能通吧？

换个端口能通 感觉443有毒 算了不折腾了

**Comment by chika0801** [comment]
> > tuic换成其它端口能通吧？
> 
> 换个端口能通 感觉443有毒 算了不折腾了

你如果问udp 443为什么不通，我遇到过，一些vps它就这样（dd完系统，xray占tcp443）udp用hy或tuic占udp的443就不通，换其它端口，客户端马上通。

**Comment by YongChingShieh** [comment]
> > > tuic换成其它端口能通吧？
> > 
> > 
> > 换个端口能通 感觉443有毒 算了不折腾了
> 
> 你如果问udp 443为什么不通，我遇到过，一些vps它就这样（dd完系统，xray占tcp443）udp用hy或tuic占udp的443就不通，换其它端口，客户端马上通。

我是Oracle vps 自带防火墙已经关闭了的 并且在Oracle后台也开启了tcp/udp 443入站 猜测是联通运营商屏蔽了....

**Comment by chika0801** [comment]
> > > > tuic换成其它端口能通吧？
> > > 
> > > 
> > > 换个端口能通 感觉443有毒 算了不折腾了
> > 
> > 
> > 你如果问udp 443为什么不通，我遇到过，一些vps它就这样（dd完系统，xray占tcp443）udp用hy或tuic占udp的443就不通，换其它端口，客户端马上通。
> 
> 我是Oracle vps 自带防火墙已经关闭了的 并且在Oracle后台也开启了tcp/udp 443入站 猜测是联通运营商屏蔽了....

甲骨文，我春川东京，arm和amd没遇到（都dd成debian11）。我遇到的vps指花钱买的那些，有几个商家的。现在hy tuic我都随便跑1w几端口，不用443了。
