### ISSUE TITLE
为什么访问http会什么也不返回， 这种情况时正常的吗？ https正常返回

### ISSUE THREAD

**Issue by qiuxiangling** [XTLS/Xray-core#1230]
![image](https://user-images.githubusercontent.com/68261800/192245740-6a57ca9d-b9cc-4718-a07d-2dda59dff9f7.png)
xray：
{
  "log": {
    "loglevel": "debug",
    "access": "/usr/local/xray/logs/access.log",
    "error": "/usr/local/xray/logs/error.log"
  },
  "dns": {
    "servers": [
      "localhost"
    ]
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "block"
      },
      {
        "type": "field",
        "domain": [
          "geosite:category-ads-all"
        ],
        "outboundTag": "block"
      },
      {
        "type": "field",                                                        
        "domain": [                                                             
          "geosite:cn"                                            
        ],                                                                      
        "outboundTag": "block"
      },
      {
        "type": "field",                                                        
        "domain": [                                                             
          "geoip:cn"
        ],                                                                      
        "outboundTag": "block"
      }
    ]
  },
  "inbounds": [
    {
      "port": 4443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "",
            "flow": "xtls-rprx-direct",
            "level": 0
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "dest": "8080",
            "xver": 0
          },
          {
            "alpn": "h2",
            "dest": "8081",
            "xver": 0
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
          "allowInsecure": false,
          "minVersion": "1.3",
          "alpn": ["http/1.1", "h2"],
          "certificates": [
            {
              "certificateFile": "/usr/local/xray/ssl/fullchain.pem",
              "keyFile": "/usr/local/xray/ssl/key.pem"
            }
          ]
        }
      }
    }
  ],
  "outbounds": [
    {
      "tag": "direct",
      "protocol": "freedom"
    },
    {
      "tag": "block",
      "protocol": "blackhole"
    }
  ]
}
nginx:
worker_processes  1;
events {
    worker_connections  1024;
}
http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
    server {
        listen       80;
        server_name  ;
        location / {
            root   html;
            index  index.html index.htm;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
    server {
        listen 127.0.0.1:8080 proxy_protocol;
        location / {
            root   /usr/local/nginx/html;
            index  index.html index.htm;
        }
        add_header Strict-Transport-Security "max-age=63072000" always;
    }
    server {
        listen 127.0.0.1:8081 http2 proxy_protocol;
        location / {
            root   /usr/local/nginx/html;
            index  index.html index.htm;
        }
    }
}

**Comment by chika0801** [comment]
{
"dest": "8080",
"xver": 1
},
{
"alpn": "h2",
"dest": "8081",
"xver": 1
}

0改1

**Comment by qiuxiangling** [comment]
> { "dest": "8080", "xver": 1 }, { "alpn": "h2", "dest": "8081", "xver": 1 }
> 
> 0改1

不行 还是一样的
nginx access日志：
127.0.0.1 - - [26/Sep/2022:18:09:56 +0800] "GET /websocket HTTP/1.1" 200 4 "-" "-"
127.0.0.1 - - [26/Sep/2022:18:09:56 +0800] "GET /websocket HTTP/1.1" 200 4 "-" "-"
127.0.0.1 - - [26/Sep/2022:18:09:56 +0800] "GET /websocket HTTP/1.1" 200 4 "-" "-"
123.112.68.11 - - [26/Sep/2022:18:09:57 +0800] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
127.0.0.1 - - [26/Sep/2022:18:10:12 +0800] "GET /websocket HTTP/1.1" 200 4 "-" "-"
127.0.0.1 - - [26/Sep/2022:18:10:15 +0800] "GET /websocket HTTP/1.1" 200 4 "-" "-"
127.0.0.1 - - [26/Sep/2022:18:10:16 +0800] "GET /websocket HTTP/1.1" 200 4 "-" "-"
127.0.0.1 - - [26/Sep/2022:18:10:16 +0800] "GET /websocket HTTP/1.1" 200 4 "-" "-"

xray error日志：
2022/09/26 18:11:21 [Info] [3263319921] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > context canceled
2022/09/26 18:11:21 [Info] [3865688685] proxy/vless/inbound: firstLen = 0
2022/09/26 18:11:21 [Info] [3865688685] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly
2022/09/26 18:11:21 [Info] [3865688685] proxy/vless/inbound: realName = 
2022/09/26 18:11:21 [Info] [3865688685] proxy/vless/inbound: realAlpn = 
2022/09/26 18:11:21 [Info] [3865688685] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > tls: first record does not look like a TLS handshake
2022/09/26 18:11:22 [Info] [913220342] proxy/vless/inbound: firstLen = 0
2022/09/26 18:11:22 [Info] [913220342] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly
2022/09/26 18:11:22 [Info] [913220342] proxy/vless/inbound: realName = 
2022/09/26 18:11:22 [Info] [913220342] proxy/vless/inbound: realAlpn = 
2022/09/26 18:11:22 [Info] [913220342] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > tls: first record does not look like a TLS handshake
2022/09/26 18:11:22 [Info] [1543879138] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > context canceled
2022/09/26 18:11:22 [Info] [2924514097] proxy/vless/inbound: firstLen = 0
2022/09/26 18:11:22 [Info] [2924514097] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly
2022/09/26 18:11:22 [Info] [2924514097] proxy/vless/inbound: realName = 
2022/09/26 18:11:22 [Info] [2924514097] proxy/vless/inbound: realAlpn = 
2022/09/26 18:11:22 [Info] [2924514097] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > tls: first record does not look like a TLS handshake
2022/09/26 18:11:22 [Info] [3096652194] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > context canceled

**Comment by chika0801** [comment]
https://github.com/chika0801/Xray-examples/tree/main/VLESS-TCP-TLS
你试试我这模板

**Comment by qiuxiangling** [comment]
> https://github.com/chika0801/Xray-examples/tree/main/VLESS-TCP-TLS 你试试我这模板

我用的您XTLS的模板 然后还是domain:443的形式访问不会跳转到https, 页面显示第一张图，curl domain:443 返回为空, curl https://domain 返回正常， 如果我这样测试符合Xray的XTLS协议回落的的情况下， 您可以在验证一下

**Comment by chika0801** [comment]
> > https://github.com/chika0801/Xray-examples/tree/main/VLESS-TCP-TLS 你试试我这模板
> 
> 我要用XTLS， 我用TLS不如去用Trojan-go ヾ(≧▽≦*)o

xtls我那链接里也有

**Comment by qiuxiangling** [comment]
> > > https://github.com/chika0801/Xray-examples/tree/main/VLESS-TCP-TLS 你试试我这模板
> > 
> > 
> > 我要用XTLS， 我用TLS不如去用Trojan-go ヾ(≧▽≦*)o
> 
> xtls我那链接里也有

用过了， 上边一条是结果。。。

**Comment by chika0801** [comment]
> > > > https://github.com/chika0801/Xray-examples/tree/main/VLESS-TCP-TLS 你试试我这模板
> > > 
> > > 
> > > 我要用XTLS， 我用TLS不如去用Trojan-go ヾ(≧▽≦*)o
> > 
> > 
> > xtls我那链接里也有
> 
> 用过了 结果： [#1230 (comment)](https://github.com/XTLS/Xray-core/issues/1230#issuecomment-1258855950)

那我不知道了，我输入我域名跳转 反代都正常

**Comment by qiuxiangling** [comment]
> > > > > https://github.com/chika0801/Xray-examples/tree/main/VLESS-TCP-TLS 你试试我这模板
> > > > 
> > > > 
> > > > 我要用XTLS， 我用TLS不如去用Trojan-go ヾ(≧▽≦*)o
> > > 
> > > 
> > > xtls我那链接里也有
> > 
> > 
> > 用过了 结果： [#1230 (comment)](https://github.com/XTLS/Xray-core/issues/1230#issuecomment-1258855950)
> 
> 那我不知道了，我输入我域名跳转 反代都正常

浏览器缓存 啥的清理了没，， 我带缓存访问也是可以跳转的， 缓存清理后 就不能跳转了

**Comment by qiuxiangling** [comment]
http://domain:port 不会回落，error.log报错：
2022/09/27 11:34:01 [Info] [2036687039] proxy/vless/inbound: firstLen = 0
2022/09/27 11:34:01 [Info] [2036687039] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly
2022/09/27 11:34:01 [Info] [2036687039] proxy/vless/inbound: realName = 
2022/09/27 11:34:01 [Info] [2036687039] proxy/vless/inbound: realAlpn = 
2022/09/27 11:34:01 [Info] [2036687039] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > tls: first record does not look like a TLS handshake

看报错像检查是不是tls握手的流量 不是tls握手的流量不会回落
