### ISSUE TITLE
可否考虑加入kcp前向纠错功能呢

### ISSUE THREAD

**Issue by hellodomng** [XTLS/Xray-core#1232]
看到过v2ray讨论过是否加入前向纠错功能：[https://github.com/v2ray/v2ray-core/issues/2569](https://github.com/v2ray/v2ray-core/issues/2569)

不过后向纠错重传导致延迟很高，体验会变差，UDP协议有些地区速度还可以，可否考虑加入前向纠错功能？

**Comment by BI7PRK** [comment]
关于被lock或者被QoS的情况。我个人的总结是不要单纯寄望于武器。除了武器之外，还有一个因素就是使用技巧。刀再利，没有功夫也没用。

我的稳定方案是：
+ 3个VPS. （都在USA）
+ VLESS+XTLS
+ 用【连接观测】进行主备自动切换。
在Server端进行以下配置非常有必要。目的是杜绝这样的链路：user (CN)-->vps (OUTSIDE)-->server(CN). 一去一回会被识别。
```JSON
"routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "domain": [
                    "geosite:cn"
                ],
                "outboundTag": "block",
                "type": "field"
            },
            {
                "ip": [
                    "geoip:cn"
                ],
                "outboundTag": "block",
                "type": "field"
            }
        ]
    }
```

效果如何？

![Snipaste_2022-09-30_11-18-54](https://user-images.githubusercontent.com/24989210/193184109-f3a2cf61-1845-4952-81c9-8c0a7fab52ea.png)

**Comment by chika0801** [comment]
> 关于被lock或者被QoS的情况。我个人的总结是不要单纯寄望于武器。除了武器之外，还有一个因素就是使用技巧。刀再利，没有功夫也没用。
> 
> 我的稳定方案是：
> 
> * 3个VPS. （都在USA）
> * VLESS+XTLS
> * 用【连接观测】进行主备自动切换。
>   在Server端进行以下配置非常有必要。目的是杜绝这样的链路：user (CN)-->vps (OUTSIDE)-->server(CN). 一去一回会被识别。
> 
> ```json
> "routing": {
>         "domainStrategy": "IPIfNonMatch",
>         "rules": [
>             {
>                 "domain": [
>                     "geosite:cn"
>                 ],
>                 "outboundTag": "block",
>                 "type": "field"
>             },
>             {
>                 "ip": [
>                     "geoip:cn"
>                 ],
>                 "outboundTag": "block",
>                 "type": "field"
>             }
>         ]
>     }
> ```
> 
> 效果如何？
> 
> ![Snipaste_2022-09-30_11-18-54](https://user-images.githubusercontent.com/24989210/193184109-f3a2cf61-1845-4952-81c9-8c0a7fab52ea.png)

https://github.com/XTLS/Xray-core/discussions/593#discussioncomment-845165
这里说过，有不知道的网友，有做一键脚本作者不信的，我是当时看到后就加了，我信
