### ISSUE TITLE
是否能有一个精简版本呢

### ISSUE THREAD

**Issue by jmwangde3** [XTLS/Xray-core#1233]
现在不停的往里加东西,本身大小和占用内存都飞速上升,是否可以有一个精简版本的方便小内存设备使用呢(比如各种硬路由?)

**Comment by chika0801** [comment]
没有

**Comment by yuhan6665** [comment]
golang 这个架构下 core 已经是相当精简了 需要更小的程序建议你看看 rust 的项目
目前可能有一些内存泄漏的问题需要慢慢修。。
先关了
