### ISSUE TITLE
[Operation] Bypass TLS over TLS detection

### ISSUE THREAD

**Issue by cross-hello** [XTLS/Xray-core#1239]
Turn on client **Enable Multiplexer** setting.(based on description think the setting could provide multiple handshake inside one TCP connect, thus change the detectable size of package. So it may could pass C&C detection)

Before setting you can't use China mobile internet connect to your server, 
After you can.

**Comment by SekiBetu** [comment]
I suspect it doesn't work.

**Comment by cross-hello** [comment]
This time the problem may relate with package length.
Make Internet experiment on China mobile internet:
The first one with MUX option close:
![Screenshot_2022_1006_231311](https://user-images.githubusercontent.com/42733664/194351912-b1fdd9ce-3096-483e-8bb2-e15fb4ea8a5f.png)
The second one with MUX option open:
![Screenshot_2022_1006_231621](https://user-images.githubusercontent.com/42733664/194352106-52e4f7f4-b96b-408b-8bc3-d3f8564fe2bf.png)
Here are the code:
~~~python
import time
TIME=300
succ=0
task=0
fail=0

def g():
    global succ, task,fail
    try:
        html=rs.get("http://google.com")
        succ+=1
        print("success :", succ)
    except:
        fail+=1
        print("fail :", fail)
    task-=1

#for a in range(0,10000):
for a in range(0,TIME):
    while task==10:
        time.sleep(0.01)
    #qd.start_new_thread(g,())
    #print("start create new stread")
    task+=1
    qd.start_new_thread(g,())

print("\n\n open mux:")
#print("\n\n No mux:")
print(" success rate:", succ/(succ+fail))
print("fail rate:", fail/(succ+fail))
~~~

**Comment by yuhan6665** [comment]
我在实验版本中增加了最简单的 tls 握手长度混淆
https://github.com/XTLS/Xray-core/pull/1235
大家可以试试
https://github.com/XTLS/Xray-core/actions/runs/3212748729

**Comment by josephw1122** [comment]
https://github.com/refraction-networking/utls
