### ISSUE TITLE
请求解决 Sniffing 与 MTProto + Fake TLS 冲突问题

### ISSUE THREAD

**Issue by betaxab** [XTLS/Xray-core#124]
接 V2ray 那边的 issue： https://github.com/v2fly/v2ray-core/issues/63

MTG 的 repo 是：https://github.com/9seconds/mtg ，我使用这个搭建的 (MTProto3 + Fake TLS) MTG 服务端。

简单来说就是 Telegram 开了 MTG 代理并连上 V2ray 服务器（开了 Sniffing）时，Telegram 就无法连接到 MTG 服务端了。

#### 其它说明：

分享 MTG Proxy 的本意是让不经常开 v2ray 客户端软件、省电用途、或其它个人原因的用户能正常用 Telegram。使用 MTG Proxy 连接到 Telegram 的用户，连接到任意 v2ray+sniffing 节点后，将无法再连接到 Telegram（每次开了 V2ray 客户端都需要手动关闭 Telegram 的 Proxy 才可正常连接到 Telegram）。

经常开关 Telegram 的 Proxy 是一件非常麻烦的事。这也违背了分享 MTG Proxy 的用意。

Sniffing 是一项有趣且非常实用的功能。通过该功能可以禁用 BT 协议、网站等。

我无法控制用户使用什么支持 V2ray 的客户端，也无法控制用户连接到具体哪个 v2ray+sniffing 节点，只能控制服务端确保使用最新的 xray 核心和配置。

 @eMeab 表示可以解决这个问题，所以提出本 issue，谢谢。

**Comment by eMeab** [comment]
先把SniffingObject设置成这样看看
`      "sniffing": {
        "enabled": true,
        "destOverride": []
      },`

**Comment by rprx** [comment]
如果 MTProto 的 Fake TLS header 和普通 TLS 有明显区别，则很容易做到

**Comment by Rirmach** [comment]
考虑到Sniffing与Fake TLS不兼容的原因是嗅探到了SNI后将流量转发到了假SNI的主机上去了，所以如果MTProto是在你自己的服务器上搭建的，或许可以考虑用Web回落的方式配置MTProto？

**Comment by dyhkwong** [comment]
1. You are contributing an implementation to block MTProto if you implement this;
2. Even if you solved this, you still need to solve every  similar issue like Tor and Apple push, etc. which is impossible / unrealistic;
3. Maybe you can open an issue for your GUI to provide an option to enable sniffing but disable destOverride;
4. Maybe you can make a feature request for core to implement "destOverride whitelist"

**Comment by pty819** [comment]
假如你在使用安卓，请直接在分应用代理的选项里排除telegram。

**Comment by rprx** [comment]
https://github.com/XTLS/Xray-core/commit/0b4858d016e727a7fa99fb2727e3be081b32d401

**Comment by rprx** [comment]
https://github.com/XTLS/Xray-core/releases/tag/v1.2.3

**Comment by daiaji** [comment]
V2真没打算更新MTProto支持FakeTLS吗？
