### ISSUE TITLE
Trojan配置问题

### ISSUE THREAD

**Issue by Simonskiii** [XTLS/Xray-core#1240]
```
{
            "port": 10099,
"listen":"127.0.0.1",
            "protocol": "trojan",
"tag":"trojan",
            "settings": {
                "clients": [
                    {
                        "password":"uuid",
                        "email": "love@example.com"
                    }
                ],
"fallbacks": [  ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "alpn": [
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "/home/vipsadmin/cert/www/www.crt",
                            "keyFile": "/home/vipsadmin/cert/www/www.key"
                        }
                    ]
                }
            }
}
```
大佬们，我把这个新加到inbounds里，x2ray restart就运行不起来了，删掉就好了。我这个配置检查了很多遍都是和x2ray examples能对上。请问这个是有什么配置错误吗？
（可不可能我前面还有一个配置trojan + grpc，inbounds 不支持同样的协议重复两次？

**Comment by chika0801** [comment]
你发加上后，会报错时，完全的config配置来看看

**Comment by Simonskiii** [comment]
```
 "inbounds": [
{
            "port": 10099,
"listen":"127.0.0.1",
            "protocol": "trojan",
"tag":"trojan",
            "settings": {
                "clients": [
                    {
                        "password":"uuid",
                        "email": "love@example.com"
                    }
                ],
"fallbacks": [  ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "alpn": [
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "/home/vipsadmin/cert/www/www.crt",
                            "keyFile": "/home/vipsadmin/cert/www/www.key"
                        }
                    ]
                }
            }
        }
, {
        "port":10800,
        "listen": "127.0.0.1",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "", // 填写你的 UUID
            "alterId": 0,
            "email": "azureuser@yourdomain.com"
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "dest": 80 
          }
        ]
      },

      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/rayx"
        }
    }},
{
            "port": 10089,
            "listen": "127.0.0.1",
            "protocol": "trojan",
            "tag": "VLESSTROJAN",
            "settings": {
                "clients": [
                    {
                        "password": "uuid",
                        "email": "yourmail@gmail.com"
                    }
                ]
            },
            "streamSettings": {
                "network": "grpc",
	      "security": "none",
                "grpcSettings": {
                    "serviceName": "serviceName"
                }
            }
        }
  ],
```

**Comment by Simonskiii** [comment]
> 你发加上后，会报错时，完全的config配置来看看

我怀疑是inbounds不能包含两个trojan，有没有这个可能。。。

**Comment by chika0801** [comment]
看你配置，你是nginx前置 ws 路径给xray

你加了trojan，

            "port": 10099,
"listen":"127.0.0.1",

listen这行不填 要填就4个0，表示对外监听。
至于json格式有不有问题去json.cn粘贴了看看

**Comment by chika0801** [comment]
> > 你发加上后，会报错时，完全的config配置来看看
> 
> 我怀疑是inbounds不能包含两个trojan，有没有这个可能。。。

没有

**Comment by Simonskiii** [comment]
> 看你配置，你是nginx前置 ws 路径给xray
> 
> 你加了trojan，
> 
> "port": 10099,
> "listen":"127.0.0.1",
> 
> listen这行不填 要填就4个0，表示对外监听。
> 
> https://github.com/chika0801/Xray-examples/blob/39ce7bc4bc7e3785535f42d19c893e1bd807837d/Trojan-TCP-TLS/config_server.json#L19
> 或抄个现成的示例，最后检查json格式
> 
> 至于json格式有不有问题去json.cn粘贴了看看

麻了，json格式没问题，4个0也不行。我这个用nginx sni分流了一下

**Comment by chika0801** [comment]
> > 看你配置，你是nginx前置 ws 路径给xray
> > 你加了trojan，
> > "port": 10099,
> > "listen":"127.0.0.1",
> > listen这行不填 要填就4个0，表示对外监听。
> > https://github.com/chika0801/Xray-examples/blob/39ce7bc4bc7e3785535f42d19c893e1bd807837d/Trojan-TCP-TLS/config_server.json#L19
> > 或抄个现成的示例，最后检查json格式
> > 至于json格式有不有问题去json.cn粘贴了看看
> 
> 麻了，json格式没问题，4个0也不行。我这个用nginx sni分流了一下

和nginx sni分流无关吧.

你确定xray 配置文件没问题，重启xray程序成功了。你客户端地址填你vps的ip sni填你vps上ssl证书包含的域名试试通不？

**Comment by Simonskiii** [comment]
> > > 看你配置，你是nginx前置 ws 路径给xray
> > > 你加了trojan，
> > > "port": 10099,
> > > "listen":"127.0.0.1",
> > > listen这行不填 要填就4个0，表示对外监听。
> > > https://github.com/chika0801/Xray-examples/blob/39ce7bc4bc7e3785535f42d19c893e1bd807837d/Trojan-TCP-TLS/config_server.json#L19
> > > 或抄个现成的示例，最后检查json格式
> > > 至于json格式有不有问题去json.cn粘贴了看看
> > 
> > 麻了，json格式没问题，4个0也不行。我这个用nginx sni分流了一下
> 
> 和nginx sni分流无关吧.
> 
> 你确定xray 配置文件没问题，重启xray程序成功了。你客户端地址填你vps的ip sni填你vps上ssl证书包含的域名试试通不？

问题在于，一加上这个配置，就重启不成功😰

**Comment by Simonskiii** [comment]
> > > 看你配置，你是nginx前置 ws 路径给xray
> > > 你加了trojan，
> > > "port": 10099,
> > > "listen":"127.0.0.1",
> > > listen这行不填 要填就4个0，表示对外监听。
> > > https://github.com/chika0801/Xray-examples/blob/39ce7bc4bc7e3785535f42d19c893e1bd807837d/Trojan-TCP-TLS/config_server.json#L19
> > > 或抄个现成的示例，最后检查json格式
> > > 至于json格式有不有问题去json.cn粘贴了看看
> > 
> > 麻了，json格式没问题，4个0也不行。我这个用nginx sni分流了一下
> 
> 和nginx sni分流无关吧.
> 
> 你确定xray 配置文件没问题，重启xray程序成功了。你客户端地址填你vps的ip sni填你vps上ssl证书包含的域名试试通不？

根本启动不了，根本无法定位错误😷

**Comment by chika0801** [comment]
> > > > 看你配置，你是nginx前置 ws 路径给xray
> > > > 你加了trojan，
> > > > "port": 10099,
> > > > "listen":"127.0.0.1",
> > > > listen这行不填 要填就4个0，表示对外监听。
> > > > https://github.com/chika0801/Xray-examples/blob/39ce7bc4bc7e3785535f42d19c893e1bd807837d/Trojan-TCP-TLS/config_server.json#L19
> > > > 或抄个现成的示例，最后检查json格式
> > > > 至于json格式有不有问题去json.cn粘贴了看看
> > > 
> > > 
> > > 麻了，json格式没问题，4个0也不行。我这个用nginx sni分流了一下
> > 
> > 
> > 和nginx sni分流无关吧.
> > 你确定xray 配置文件没问题，重启xray程序成功了。你客户端地址填你vps的ip sni填你vps上ssl证书包含的域名试试通不？
> 
> 根本启动不了，根本无法定位错误😷

你说清楚呀，
如果json格式没问题，程序还启不来，检查证书的用户名和组不能都是root 是nobody nogroup样..

**Comment by Simonskiii** [comment]
> > > > > 看你配置，你是nginx前置 ws 路径给xray
> > > > > 你加了trojan，
> > > > > "port": 10099,
> > > > > "listen":"127.0.0.1",
> > > > > listen这行不填 要填就4个0，表示对外监听。
> > > > > https://github.com/chika0801/Xray-examples/blob/39ce7bc4bc7e3785535f42d19c893e1bd807837d/Trojan-TCP-TLS/config_server.json#L19
> > > > > 或抄个现成的示例，最后检查json格式
> > > > > 至于json格式有不有问题去json.cn粘贴了看看
> > > > 
> > > > 
> > > > 麻了，json格式没问题，4个0也不行。我这个用nginx sni分流了一下
> > > 
> > > 
> > > 和nginx sni分流无关吧.
> > > 你确定xray 配置文件没问题，重启xray程序成功了。你客户端地址填你vps的ip sni填你vps上ssl证书包含的域名试试通不？
> > 
> > 根本启动不了，根本无法定位错误😷
> 
> 你说清楚呀，
> 如果json格式没问题，程序还启不来，检查证书的用户名和组不能都是root 是nobody nogroup样..

有点超出我的理解范围了。。。是证书的权限问题吗。麻烦您了，我还在学习中😭

**Comment by chika0801** [comment]
chown -R nobody:nogroup /etc/ssl/你实际证书的目录
改用户名和组的命令

**Comment by chika0801** [comment]
如果真是证书方面问题，大部分人不知道，它起源于
https://github.com/v2fly/fhs-install-v2ray/wiki/Insufficient-permissions-when-using-certificates-zh-Hans-CN

**Comment by Simonskiii** [comment]
> 如果真是证书方面问题，大部分人不知道，它起源于
> https://github.com/v2fly/fhs-install-v2ray/wiki/Insufficient-permissions-when-using-certificates-zh-Hans-CN

好了好了，感谢老哥啊！！！我捅咕一晚上了一直没找到原因

**Comment by Simonskiii** [comment]
> 如果真是证书方面问题，大部分人不知道，它起源于
> https://github.com/v2fly/fhs-install-v2ray/wiki/Insufficient-permissions-when-using-certificates-zh-Hans-CN

诶老哥，但是为什么nginx用的证书就没权限问题呢？

**Comment by chika0801** [comment]
> > 如果真是证书方面问题，大部分人不知道，它起源于
> > https://github.com/v2fly/fhs-install-v2ray/wiki/Insufficient-permissions-when-using-certificates-zh-Hans-CN
> 
> 诶老哥，但是为什么nginx用的证书就没权限问题呢？

建议去这链接里 问v2fly安装脚本的作者

**Comment by Simonskiii** [comment]
> > > 如果真是证书方面问题，大部分人不知道，它起源于
> > > https://github.com/v2fly/fhs-install-v2ray/wiki/Insufficient-permissions-when-using-certificates-zh-Hans-CN
> > 
> > 诶老哥，但是为什么nginx用的证书就没权限问题呢？
> 
> 建议去这链接里 问v2fly安装脚本的作者

感谢老哥了！

**Comment by qist** [comment]
## xray 配置
```
{
  "inbounds": [
    {
      // "port": 6666,
      "listen": "/run/xray/trojan-ws.sock,0666",
      "protocol": "trojan",
      "tag": "TROJANWS",
      "settings": {
        "clients": [
          {
            "password": “password",
            "email": "ocezs.xxx.com_TROJAN_WS"
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "none",
        "wsSettings": {
          "path": "/efnxuvlqws",
          "headers": {}
        },
        "sockopt": {
          "tcpFastOpen": true
        }
      },
      "tag": "TROJANWS",
      "sniffing": {
        "enabled": false,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    }
  ]
}
``` 
## nginx 配置
```
upstream trojan-ws {
        least_conn;
        server unix:/run/xray/trojan-ws.sock max_fails=3 fail_timeout=30s;
        keepalive 1000;
}

    location /efnxuvlqws {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $clientRealIp;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-NginX-Proxy true;
        proxy_http_version 1.1;
        proxy_ssl_server_name on;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_ssl_session_reuse off;
        proxy_redirect off;
        proxy_pass http://trojan-ws;

    }
```

**Comment by yuhan6665** [comment]
close as solved
