### ISSUE TITLE
[need code help] where to modify TLS handshake padding 

### ISSUE THREAD

**Issue by cross-hello** [XTLS/Xray-core#1242]
Hello, would like to have a try for padding second TLS handshake package. https://blog.zorinaq.com/my-experience-with-the-great-firewall-of-china/ (Ida 4)
Where could start(not previous experience with golang)?

**Comment by SakuraSakuraSakuraChan** [comment]
https://github.com/XTLS/Xray-core/pull/1235
Can can need

**Comment by yuhan6665** [comment]
Added in https://github.com/XTLS/Xray-core/pull/1235
