### ISSUE TITLE
DNS内置服务器工作流程问题

### ISSUE THREAD

**Issue by Simonskiii** [XTLS/Xray-core#1243]
```
"dns": {
        "hosts":{
"services.googleapis.cn":"142.250.204.138"
},
```
dns配置如上，但是access.log没有被解析成功，而是被路由规则block了。
```
2022/10/08 14:39:29 127.0.0.1:0 accepted tcp:services.googleapis.cn:443 [VLESSTROJAN -> block] email: yourmail@gmail.com
2022/10/08 14:39:29 127.0.0.1:0 accepted tcp:services.googleapis.cn:443 [VLESSTROJAN -> block] email: yourmail@gmail.com
```
我想实现把services.goolgeapis.cn通过host转成services.googleapis.com，然后就可以通过路由规则了，请问应该如何实现呢

**Comment by azzvx** [comment]
想要使用内置DNS需要把DNS请求拦截到`DNS出站协议`。如果不拦截，那么仅在路由过程中使用。
另外
```
// 3.2 屏蔽广告
      {
        "type": "field",
        "domain": [
        "geosite:cn", --> services.goolgeapis.cn包含在这个规则里面，直接拦截了
          "geosite:category-ads-all" // 分流条件：geosite 文件内，名为"category-ads-all"的规则（各种广告域名）
        ],
        "outboundTag": "block" // 分流策略：交给出站"block"处理（黑洞屏蔽）
      }
```

**Comment by Simonskiii** [comment]
> 想要使用内置DNS需要把DNS请求拦截到`DNS出站协议`。如果不拦截，那么仅在路由过程中使用。 另外
> 
> ```
> // 3.2 屏蔽广告
>       {
>         "type": "field",
>         "domain": [
>         "geosite:cn", --> services.goolgeapis.cn包含在这个规则里面，直接拦截了
>           "geosite:category-ads-all" // 分流条件：geosite 文件内，名为"category-ads-all"的规则（各种广告域名）
>         ],
>         "outboundTag": "block" // 分流策略：交给出站"block"处理（黑洞屏蔽）
>       }
> ```

【想要使用内置DNS需要把DNS请求拦截到DNS出站协议】emmm老哥是指在outbounds里写dns吗？？我没太理解怎么操作。。。

**Comment by Fangliding** [comment]
Not a core issue
