### ISSUE TITLE
作者 为什么没更新 消失了吗

### ISSUE THREAD

**Issue by qiuxiangling** [XTLS/Xray-core#1247]

**Comment by chika0801** [comment]
你也许火星了，如果你指的作者是rprx，他的tg账号超过1年没登陆了。

**Comment by qiuxiangling** [comment]
> 

回不来了吗φ(*￣0￣)

**Comment by chika0801** [comment]
没有人知道

**Comment by chika0801** [comment]
> 传说是一些xtls协议设计上的缺陷无法解决，只能装死避风头？

夜之城的传奇都是你死后的事

**Comment by Cwek** [comment]
> > 传说是一些xtls协议设计上的缺陷无法解决，只能装死避风头？
> 
> 夜之城的传奇都是你死后的事

只是听说而已。有人分析xtls里面存在一些硬编码校验问题，可以被利用来嗅探或者攻击，那位仁兄就说原作者修不好就躲着不见人了。

好像是issue 1165。

**Comment by chika0801** [comment]
> > > 传说是一些xtls协议设计上的缺陷无法解决，只能装死避风头？
> > 
> > 
> > 夜之城的传奇都是你死后的事
> 
> 只是听说而已。有人分析xtls里面存在一些硬编码校验问题，可以被利用来嗅探或者攻击，那位仁兄就说原作者修不好就躲着不见人了。
> 
> 好像是issue 1165。

e主席健在的。你喜欢luci吗？

**Comment by Cwek** [comment]
> > > > 传说是一些xtls协议设计上的缺陷无法解决，只能装死避风头？
> > > 
> > > 
> > > 夜之城的传奇都是你死后的事
> > 
> > 
> > 只是听说而已。有人分析xtls里面存在一些硬编码校验问题，可以被利用来嗅探或者攻击，那位仁兄就说原作者修不好就躲着不见人了。
> > 好像是issue 1165。
> 
> e主席健在的。你喜欢luci吗？

只是看到了，说句见过的可能性……

如果不是解决不了缺陷而躲着的话，也可能是现实贵人事忙？

**Comment by vinograd-cyber** [comment]
如果长期不更新，还不如使用[`v2fly`](https://www.v2fly.org/), 虽然xlts一骑绝尘，但是更新慢的话，跟不上长城的策略升级

**Comment by qiuxiangling** [comment]
> 

可能开小号 了吧ψ(｀∇´)ψ

**Comment by shenlijun** [comment]
> > > 传说是一些xtls协议设计上的缺陷无法解决，只能装死避风头？
> > 
> > 
> > 夜之城的传奇都是你死后的事
> 
> 只是听说而已。有人分析xtls里面存在一些硬编码校验问题，可以被利用来嗅探或者攻击，那位仁兄就说原作者修不好就躲着不见人了。
> 
> 好像是issue 1165。

当初因为xtls许可协议的问题和v2ray分了家，现在发现xtls出了问题，修复不了的话xray项目就成笑话了
现在经常发release的维护者在那个issue里用英文回答中文主题，还被题主羞辱了英文语法
悲剧~~~~~~

**Comment by chika0801** [comment]
> > > > 传说是一些xtls协议设计上的缺陷无法解决，只能装死避风头？
> > > 
> > > 
> > > 夜之城的传奇都是你死后的事
> > 
> > 
> > 只是听说而已。有人分析xtls里面存在一些硬编码校验问题，可以被利用来嗅探或者攻击，那位仁兄就说原作者修不好就躲着不见人了。
> > 好像是issue 1165。
> 
> 当初因为xtls许可协议的问题和v2ray分了家，现在发现xtls出了问题，修复不了的话xray项目就成笑话了 现在经常发release的维护者在那个issue里用英文回答中文主题，还被题主羞辱了英文语法 悲剧~~~~~~

https://github.com/XTLS/Xray-core/pull/1235

已经修了，这位是V吧，去杀亚当重锤

**Comment by DanielChen008** [comment]
> 你也许火星了，如果你指的作者是rprx，他的tg账号超过1年没登陆了。

会不会像 SS 作者因为肉身在朝内，被请去喝过茶了… 不管怎样，感谢这些大神让网络百花齐放。

**Comment by shenlijun** [comment]
> > > > > 传说是一些xtls协议设计上的缺陷无法解决，只能装死避风头？
> > > > 
> > > > 
> > > > 夜之城的传奇都是你死后的事
> > > 
> > > 
> > > 只是听说而已。有人分析xtls里面存在一些硬编码校验问题，可以被利用来嗅探或者攻击，那位仁兄就说原作者修不好就躲着不见人了。
> > > 好像是issue 1165。
> > 
> > 
> > 当初因为xtls许可协议的问题和v2ray分了家，现在发现xtls出了问题，修复不了的话xray项目就成笑话了 现在经常发release的维护者在那个issue里用英文回答中文主题，还被题主羞辱了英文语法 悲剧~~~~~~
> 
> #1235
> 
> 已经修了，这位是V吧，去杀亚当重锤

1.维护者自己的主题都没说解决，你脑放就这么大？
2.既然解决了，你猜为什么维护者没有引用那个提出问题的issue？https://github.com/XTLS/Go/issues/17
3.很可惜你错了，我从X出来的时候就一直用X
4.阻碍发展的永远都是那些只会喊“好支威有666”的麻瓜，而不是认真提建议的人，可悲的是麻瓜往往喜欢站在这些人的对立面，顺便把自己往火坑里推
5.在哈洛加斯玩光油打赤搏

**Comment by chika0801** [comment]
> > > > > > 传说是一些xtls协议设计上的缺陷无法解决，只能装死避风头？
> > > > > 
> > > > > 
> > > > > 夜之城的传奇都是你死后的事
> > > > 
> > > > 
> > > > 只是听说而已。有人分析xtls里面存在一些硬编码校验问题，可以被利用来嗅探或者攻击，那位仁兄就说原作者修不好就躲着不见人了。
> > > > 好像是issue 1165。
> > > 
> > > 
> > > 当初因为xtls许可协议的问题和v2ray分了家，现在发现xtls出了问题，修复不了的话xray项目就成笑话了 现在经常发release的维护者在那个issue里用英文回答中文主题，还被题主羞辱了英文语法 悲剧~~~~~~
> > 
> > 
> > #1235
> > 已经修了，这位是V吧，去杀亚当重锤
> 
> 1.维护者自己的主题都没说解决，你脑放就这么大？ 2.既然解决了，你猜为什么维护者没有引用那个提出问题的issue？[XTLS/Go#17](https://github.com/XTLS/Go/issues/17) 3.很可惜你错了，我从X出来的时候就一直用X 4.阻碍发展的永远都是那些只会喊“好支威有666”的麻瓜，而不是认真提建议的人，可悲的是麻瓜往往喜欢站在这些人的对立面，顺便把自己往火坑里推 5.在哈洛加斯玩光油打赤搏

![Screenshot_2022-10-13-12-14-06-164_org telegram messenger](https://user-images.githubusercontent.com/88967758/195498339-42806850-c3a1-4e34-a727-d045837ffc5f.png)

**Comment by FranzKafkaYu** [comment]
@shenlijun Talk is cheap, show me your code

**Comment by shenlijun** [comment]
> > > > > > > 传说是一些xtls协议设计上的缺陷无法解决，只能装死避风头？
> > > > > > 
> > > > > > 
> > > > > > 夜之城的传奇都是你死后的事
> > > > > 
> > > > > 
> > > > > 只是听说而已。有人分析xtls里面存在一些硬编码校验问题，可以被利用来嗅探或者攻击，那位仁兄就说原作者修不好就躲着不见人了。
> > > > > 好像是issue 1165。
> > > > 
> > > > 
> > > > 当初因为xtls许可协议的问题和v2ray分了家，现在发现xtls出了问题，修复不了的话xray项目就成笑话了 现在经常发release的维护者在那个issue里用英文回答中文主题，还被题主羞辱了英文语法 悲剧~~~~~~
> > > 
> > > 
> > > #1235
> > > 已经修了，这位是V吧，去杀亚当重锤
> > 
> > 
> > 1.维护者自己的主题都没说解决，你脑放就这么大？ 2.既然解决了，你猜为什么维护者没有引用那个提出问题的issue？[XTLS/Go#17](https://github.com/XTLS/Go/issues/17) 3.很可惜你错了，我从X出来的时候就一直用X 4.阻碍发展的永远都是那些只会喊“好支威有666”的麻瓜，而不是认真提建议的人，可悲的是麻瓜往往喜欢站在这些人的对立面，顺便把自己往火坑里推 5.在哈洛加斯玩光油打赤搏
> 
> ![Screenshot_2022-10-13-12-14-06-164_org telegram messenger](https://user-images.githubusercontent.com/88967758/195498339-42806850-c3a1-4e34-a727-d045837ffc5f.png)
> 
> 喷之前建议来xray群潜潜水没人说你菜

当初xtls也是吹的飞起，别人说可能有问题的时候一堆人上来就骂，也不知道这些人是什么心态，直到有人发了23 3 3，这段时间怕是那些人也都偷偷的改了tls吧……

yuhan这哥们好在话说得不满，也没在github的面上说解决了，不过照他喜欢隔几天就发个per-release这种习惯，我在暂时还是会观望一段时间

群？大家都得喊666的地方我呆不惯，毕竟现实中给我喊666的比我需要喊666的时候多一点

**Comment by shenlijun** [comment]
> @shenlijun Talk is cheap, show me your code

1.大家用中文交流的时候非得用英文是想表达什么样的信号呢？
2.歧视我这个白板号，那你有没有问过你们的大老板还有投资人：“show me your code”？

**Comment by chika0801** [comment]
> > > > > > > > 传说是一些xtls协议设计上的缺陷无法解决，只能装死避风头？
> > > > > > > 
> > > > > > > 
> > > > > > > 夜之城的传奇都是你死后的事
> > > > > > 
> > > > > > 
> > > > > > 只是听说而已。有人分析xtls里面存在一些硬编码校验问题，可以被利用来嗅探或者攻击，那位仁兄就说原作者修不好就躲着不见人了。
> > > > > > 好像是issue 1165。
> > > > > 
> > > > > 
> > > > > 当初因为xtls许可协议的问题和v2ray分了家，现在发现xtls出了问题，修复不了的话xray项目就成笑话了 现在经常发release的维护者在那个issue里用英文回答中文主题，还被题主羞辱了英文语法 悲剧~~~~~~
> > > > 
> > > > 
> > > > #1235
> > > > 已经修了，这位是V吧，去杀亚当重锤
> > > 
> > > 
> > > 1.维护者自己的主题都没说解决，你脑放就这么大？ 2.既然解决了，你猜为什么维护者没有引用那个提出问题的issue？[XTLS/Go#17](https://github.com/XTLS/Go/issues/17) 3.很可惜你错了，我从X出来的时候就一直用X 4.阻碍发展的永远都是那些只会喊“好支威有666”的麻瓜，而不是认真提建议的人，可悲的是麻瓜往往喜欢站在这些人的对立面，顺便把自己往火坑里推 5.在哈洛加斯玩光油打赤搏
> > 
> > 
> > ![Screenshot_2022-10-13-12-14-06-164_org telegram messenger](https://user-images.githubusercontent.com/88967758/195498339-42806850-c3a1-4e34-a727-d045837ffc5f.png)
> > 喷之前建议来xray群潜潜水没人说你菜
> 
> 当初xtls也是吹的飞起，别人说可能有问题的时候一堆人上来就骂，也不知道这些人是什么心态，直到有人发了23 3 3，这段时间怕是那些人也都偷偷的改了tls吧……
> 
> yuhan这哥们好在话说得不满，也没在github的面上说解决了，不过照他喜欢隔几天就发个per-release这种习惯，我在暂时还是会观望一段时间
> 
> 群？大家都得喊666的地方我呆不惯，毕竟现实中给我喊666的比我需要喊666的时候多一点

你行你上，欢迎你pr，没有欠你，没人要你的666

**Comment by FranzKafkaYu** [comment]
> > @shenlijun Talk is cheap, show me your code
> 
> 1.大家用中文交流的时候非得用英文是想表达什么样的信号呢？ 2.歧视我这个白板号，那你有没有问过你们的大老板还有投资人：“show me your code”？

1.你真是想太多，心思这么复杂活得不累么
2.如果你有任何贡献，欢迎把你的大号亮出来我去瞻仰一番，我给你喊666

**Comment by shenlijun** [comment]
> > > > > > > > > 传说是一些xtls协议设计上的缺陷无法解决，只能装死避风头？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 夜之城的传奇都是你死后的事
> > > > > > > 
> > > > > > > 
> > > > > > > 只是听说而已。有人分析xtls里面存在一些硬编码校验问题，可以被利用来嗅探或者攻击，那位仁兄就说原作者修不好就躲着不见人了。
> > > > > > > 好像是issue 1165。
> > > > > > 
> > > > > > 
> > > > > > 当初因为xtls许可协议的问题和v2ray分了家，现在发现xtls出了问题，修复不了的话xray项目就成笑话了 现在经常发release的维护者在那个issue里用英文回答中文主题，还被题主羞辱了英文语法 悲剧~~~~~~
> > > > > 
> > > > > 
> > > > > #1235
> > > > > 已经修了，这位是V吧，去杀亚当重锤
> > > > 
> > > > 
> > > > 1.维护者自己的主题都没说解决，你脑放就这么大？ 2.既然解决了，你猜为什么维护者没有引用那个提出问题的issue？[XTLS/Go#17](https://github.com/XTLS/Go/issues/17) 3.很可惜你错了，我从X出来的时候就一直用X 4.阻碍发展的永远都是那些只会喊“好支威有666”的麻瓜，而不是认真提建议的人，可悲的是麻瓜往往喜欢站在这些人的对立面，顺便把自己往火坑里推 5.在哈洛加斯玩光油打赤搏
> > > 
> > > 
> > > ![Screenshot_2022-10-13-12-14-06-164_org telegram messenger](https://user-images.githubusercontent.com/88967758/195498339-42806850-c3a1-4e34-a727-d045837ffc5f.png)
> > > 喷之前建议来xray群潜潜水没人说你菜
> > 
> > 
> > 当初xtls也是吹的飞起，别人说可能有问题的时候一堆人上来就骂，也不知道这些人是什么心态，直到有人发了23 3 3，这段时间怕是那些人也都偷偷的改了tls吧……
> > yuhan这哥们好在话说得不满，也没在github的面上说解决了，不过照他喜欢隔几天就发个per-release这种习惯，我在暂时还是会观望一段时间
> > 群？大家都得喊666的地方我呆不惯，毕竟现实中给我喊666的比我需要喊666的时候多一点
> 
> 你行你上，欢迎你pr，没有欠你，没人要你的666

又开始了，**好好的开源社区，搞得跟饭圈一样恶心**
不能说有问题，要不就是恶语相向，要不就是你行你上，可能很多人会翻个墙就是周围小伙伴里的“大神”了吧，眼里揉不得沙子
我在这里发过很多issue和讨论，总还是希望它变得更好的，不过也无所谓了，我的vps和客户端性能都足够，完全用不上xtls
说实话X这边issue的氛围和V那边差了不少，很多问题issue都是以骂战而关闭结束的

**Comment by uioasder** [comment]
> > > > @shenlijun Talk is cheap, show me your code
> > > 
> > > 
> > > 1.大家用中文交流的时候非得用英文是想表达什么样的信号呢？ 2.歧视我这个白板号，那你有没有问过你们的大老板还有投资人：“show me your code”？
> > 
> > 
> > 1.你真是想太多，心思这么复杂活得不累么 2.如果你有任何贡献，欢迎把你的大号亮出来我去瞻仰一番，我给你喊666
> 
> 1.现实中的一个场景：“哎我只是开个玩笑嘛，你怎么玩不起啊”，是怎得玩笑还是贱这个得细品。这个不是类比你的英文，只是想说有的人嘴里说的和心里想的可能不太一样。还有其实咱们的英语水平应该连很多初中生都不如； 2.我就这么个白板号，也不觉得有什么可丢人的，你把自己主页搞满了花里胡哨，说实话我也没有高看你一眼。因为很简单，这世界不只有GitHub。
> 
> PS：知道为什么小孩喜欢比考试成绩么？他们出去玩为什么喜欢比胆子大么？因为那时候能拿得出手得东西不太多。 知道你为什么喜欢搞英文么？知道你为什么喜欢代码量么？知道我为什么问你有没有问过大老板和投资人么？
> 
> 年轻人，风雨中飘摇的芸芸众生，大部分站稳脚跟都不是一件易事，自以为能拉开差距并产生鄙视链的东西也许连毛都不是，又何必去做鲁迅先生笔下那既是狼又是羊的角色呢，内心自以为有小得意，殊不知别人背后在用怪异的眼神看着你

**Comment by uioasder** [comment]
> > > > @shenlijun Talk is cheap, show me your code
> > > 
> > > 
> > > 1.大家用中文交流的时候非得用英文是想表达什么样的信号呢？ 2.歧视我这个白板号，那你有没有问过你们的大老板还有投资人：“show me your code”？
> > 
> > 
> > 1.你真是想太多，心思这么复杂活得不累么 2.如果你有任何贡献，欢迎把你的大号亮出来我去瞻仰一番，我给你喊666
> 
> 1.现实中的一个场景：“哎我只是开个玩笑嘛，你怎么玩不起啊”，是怎得玩笑还是贱这个得细品。这个不是类比你的英文，只是想说有的人嘴里说的和心里想的可能不太一样。还有其实咱们的英语水平应该连很多初中生都不如； 2.我就这么个白板号，也不觉得有什么可丢人的，你把自己主页搞满了花里胡哨，说实话我也没有高看你一眼。因为很简单，这世界不只有GitHub。
> 
> PS：知道为什么小孩喜欢比考试成绩么？他们出去玩为什么喜欢比胆子大么？因为那时候能拿得出手得东西不太多。 知道你为什么喜欢搞英文么？知道你为什么喜欢代码量么？知道我为什么问你有没有问过大老板和投资人么？
> 
> 年轻人，风雨中飘摇的芸芸众生，大部分站稳脚跟都不是一件易事，自以为能拉开差距并产生鄙视链的东西也许连毛都不是，又何必去做鲁迅先生笔下那既是狼又是羊的角色呢，内心自以为有小得意，殊不知别人背后在用怪异的眼神看着你

我看了一堆你的讨论，结果你也就发了一堆无用的牢骚，也没有针对问题提出任何有用的建议，极端点说，那个漏洞甚至都不是你发现的。开发组也不欠你什么啊，你觉得不好用就别用，也没人强迫你用。你也别说你希望这个项目变得更好，因为我只看到你恼怒的样子

**Comment by shenlijun** [comment]
> > > > > @shenlijun Talk is cheap, show me your code
> > > > 
> > > > 
> > > > 1.大家用中文交流的时候非得用英文是想表达什么样的信号呢？ 2.歧视我这个白板号，那你有没有问过你们的大老板还有投资人：“show me your code”？
> > > 
> > > 
> > > 1.你真是想太多，心思这么复杂活得不累么 2.如果你有任何贡献，欢迎把你的大号亮出来我去瞻仰一番，我给你喊666
> > 
> > 
> > 1.现实中的一个场景：“哎我只是开个玩笑嘛，你怎么玩不起啊”，是怎得玩笑还是贱这个得细品。这个不是类比你的英文，只是想说有的人嘴里说的和心里想的可能不太一样。还有其实咱们的英语水平应该连很多初中生都不如； 2.我就这么个白板号，也不觉得有什么可丢人的，你把自己主页搞满了花里胡哨，说实话我也没有高看你一眼。因为很简单，这世界不只有GitHub。
> > PS：知道为什么小孩喜欢比考试成绩么？他们出去玩为什么喜欢比胆子大么？因为那时候能拿得出手得东西不太多。 知道你为什么喜欢搞英文么？知道你为什么喜欢代码量么？知道我为什么问你有没有问过大老板和投资人么？
> > 年轻人，风雨中飘摇的芸芸众生，大部分站稳脚跟都不是一件易事，自以为能拉开差距并产生鄙视链的东西也许连毛都不是，又何必去做鲁迅先生笔下那既是狼又是羊的角色呢，内心自以为有小得意，殊不知别人背后在用怪异的眼神看着你
> 
> 我看了一堆你的讨论，结果你也就发了一堆无用的牢骚，也没有针对问题提出任何有用的建议，极端点说，那个漏洞甚至都不是你发现的。开发组也不欠你什么啊，你觉得不好用就别用，也没人强迫你用。你也别说你希望这个项目变得更好，因为我只看到你恼怒的样子

是啊，**好好的开源社区，搞得跟饭圈一样恶心**，我是开心不起来的

**Comment by ihuanx** [comment]
我以前玩LOL的时候 ..  有很多生活不如意的人 就喜欢在聊天框对线..  不是和敌方(所有人)对线,就是和我方对线..  
而对线的内容也基本与游戏无关..   所以我能理解这种现象..  他们只是纯粹为了释放愤怒. 即使愤怒不源于游戏本身.

**Comment by uioasder** [comment]
> > > > > > @shenlijun Talk is cheap, show me your code
> > > > > 
> > > > > 
> > > > > 1.大家用中文交流的时候非得用英文是想表达什么样的信号呢？ 2.歧视我这个白板号，那你有没有问过你们的大老板还有投资人：“show me your code”？
> > > > 
> > > > 
> > > > 1.你真是想太多，心思这么复杂活得不累么 2.如果你有任何贡献，欢迎把你的大号亮出来我去瞻仰一番，我给你喊666
> > > 
> > > 
> > > 1.现实中的一个场景：“哎我只是开个玩笑嘛，你怎么玩不起啊”，是怎得玩笑还是贱这个得细品。这个不是类比你的英文，只是想说有的人嘴里说的和心里想的可能不太一样。还有其实咱们的英语水平应该连很多初中生都不如； 2.我就这么个白板号，也不觉得有什么可丢人的，你把自己主页搞满了花里胡哨，说实话我也没有高看你一眼。因为很简单，这世界不只有GitHub。
> > > PS：知道为什么小孩喜欢比考试成绩么？他们出去玩为什么喜欢比胆子大么？因为那时候能拿得出手得东西不太多。 知道你为什么喜欢搞英文么？知道你为什么喜欢代码量么？知道我为什么问你有没有问过大老板和投资人么？
> > > 年轻人，风雨中飘摇的芸芸众生，大部分站稳脚跟都不是一件易事，自以为能拉开差距并产生鄙视链的东西也许连毛都不是，又何必去做鲁迅先生笔下那既是狼又是羊的角色呢，内心自以为有小得意，殊不知别人背后在用怪异的眼神看着你
> > 
> > 
> > 我看了一堆你的讨论，结果你也就发了一堆无用的牢骚，也没有针对问题提出任何有用的建议，极端点说，那个漏洞甚至都不是你发现的。开发组也不欠你什么啊，你觉得不好用就别用，也没人强迫你用。你也别说你希望这个项目变得更好，因为我只看到你恼怒的样子
> 
> 是啊，**好好的开源社区，搞得跟饭圈一样恶心**，我是开心不起来的

既然你给不出任何建议，也提交不了任何代码，又要抱怨，我的建议是别用，就不会生气，你也别回了，就这样

**Comment by yuhan6665** [comment]
Close as spam. Please have constructive discussions.

**Comment by FranzKafkaYu** [comment]
> > > > @shenlijun Talk is cheap, show me your code
> > > 
> > > 
> > > 1.大家用中文交流的时候非得用英文是想表达什么样的信号呢？ 2.歧视我这个白板号，那你有没有问过你们的大老板还有投资人：“show me your code”？
> > 
> > 
> > 1.你真是想太多，心思这么复杂活得不累么 2.如果你有任何贡献，欢迎把你的大号亮出来我去瞻仰一番，我给你喊666
> 
> 1.现实中的一个场景：“哎我只是开个玩笑嘛，你怎么玩不起啊”，是怎得玩笑还是贱这个得细品。这个不是类比你的英文，只是想说有的人嘴里说的和心里想的可能不太一样。还有其实咱们的英语水平应该连很多初中生都不如； 2.我就这么个白板号，也不觉得有什么可丢人的，你把自己主页搞满了花里胡哨，说实话我也没有高看你一眼。因为很简单，这世界不只有GitHub。
> 
> PS：知道为什么小孩喜欢比考试成绩么？他们出去玩为什么喜欢比胆子大么？因为那时候能拿得出手得东西不太多。 知道你为什么喜欢搞英文么？知道你为什么喜欢代码量么？知道我为什么问你有没有问过大老板和投资人么？
> 
> 年轻人，风雨中飘摇的芸芸众生，大部分站稳脚跟都不是一件易事，自以为能拉开差距并产生鄙视链的东西也许连毛都不是，又何必去做鲁迅先生笔下那既是狼又是羊的角色呢，内心自以为有小得意，殊不知别人背后在用怪异的眼神看着你

1.别用"咱们"，你个人仅代表你个人。
2.我也没求你也没想着你能高看我一眼。
3.针对你PS的部分，我根本不care。
4.当然欢迎有价值的讨论与合理提出问题。可在这个issue里，我看到的却是一些阴阳怪气的东西。
5.好好的开源社区变成这样，你应该反思是不是也有你的一份功劳。

以上，后续不再做任何回复。

**Comment by SekiBetu** [comment]
> > > > > > > > 传说是一些xtls协议设计上的缺陷无法解决，只能装死避风头？
> > > > > > > 
> > > > > > > 
> > > > > > > 夜之城的传奇都是你死后的事
> > > > > > 
> > > > > > 
> > > > > > 只是听说而已。有人分析xtls里面存在一些硬编码校验问题，可以被利用来嗅探或者攻击，那位仁兄就说原作者修不好就躲着不见人了。
> > > > > > 好像是issue 1165。
> > > > > 
> > > > > 
> > > > > 当初因为xtls许可协议的问题和v2ray分了家，现在发现xtls出了问题，修复不了的话xray项目就成笑话了 现在经常发release的维护者在那个issue里用英文回答中文主题，还被题主羞辱了英文语法 悲剧~~~~~~
> > > > 
> > > > 
> > > > #1235
> > > > 已经修了，这位是V吧，去杀亚当重锤
> > > 
> > > 
> > > 1.维护者自己的主题都没说解决，你脑放就这么大？ 2.既然解决了，你猜为什么维护者没有引用那个提出问题的issue？[XTLS/Go#17](https://github.com/XTLS/Go/issues/17) 3.很可惜你错了，我从X出来的时候就一直用X 4.阻碍发展的永远都是那些只会喊“好支威有666”的麻瓜，而不是认真提建议的人，可悲的是麻瓜往往喜欢站在这些人的对立面，顺便把自己往火坑里推 5.在哈洛加斯玩光油打赤搏
> > 
> > 
> > ![Screenshot_2022-10-13-12-14-06-164_org telegram messenger](https://user-images.githubusercontent.com/88967758/195498339-42806850-c3a1-4e34-a727-d045837ffc5f.png)
> > 喷之前建议来xray群潜潜水没人说你菜
> 
> 当初xtls也是吹的飞起，别人说可能有问题的时候一堆人上来就骂，也不知道这些人是什么心态，直到有人发了23 3 3，这段时间怕是那些人也都偷偷的改了tls吧……
> 
> yuhan这哥们好在话说得不满，也没在github的面上说解决了，不过照他喜欢隔几天就发个per-release这种习惯，我在暂时还是会观望一段时间
> 
> 群？大家都得喊666的地方我呆不惯，毕竟现实中给我喊666的比我需要喊666的时候多一点

别搞党争了，现在已经众生平等了，在墙的新版本下，没有任何一个工具可以躲过检测，xtls的那些小问题墙根本不会去探测，因为已经有了更加通用和精准的tls in tls检测，你用啥都一样，都被检测

**Comment by shenlijun** [comment]
> 我以前玩LOL的时候 .. 有很多生活不如意的人 就喜欢在聊天框对线.. 不是和敌方(所有人)对线,就是和我方对线.. 而对线的内容也基本与游戏无关.. 所以我能理解这种现象.. 他们只是纯粹为了释放愤怒. 即使愤怒不源于游戏本身.

唉，改不了了，见到玩花活和装X的总忍不住上去踢两脚

说到游戏，其实都一样，什么事情玩的6的都是极少数，剩下绝大多数菜又蜜汁自信的人放一起，不吵吵才奇怪

**Comment by shenlijun** [comment]
> > > > > > > @shenlijun Talk is cheap, show me your code
> > > > > > 
> > > > > > 
> > > > > > 1.大家用中文交流的时候非得用英文是想表达什么样的信号呢？ 2.歧视我这个白板号，那你有没有问过你们的大老板还有投资人：“show me your code”？
> > > > > 
> > > > > 
> > > > > 1.你真是想太多，心思这么复杂活得不累么 2.如果你有任何贡献，欢迎把你的大号亮出来我去瞻仰一番，我给你喊666
> > > > 
> > > > 
> > > > 1.现实中的一个场景：“哎我只是开个玩笑嘛，你怎么玩不起啊”，是怎得玩笑还是贱这个得细品。这个不是类比你的英文，只是想说有的人嘴里说的和心里想的可能不太一样。还有其实咱们的英语水平应该连很多初中生都不如； 2.我就这么个白板号，也不觉得有什么可丢人的，你把自己主页搞满了花里胡哨，说实话我也没有高看你一眼。因为很简单，这世界不只有GitHub。
> > > > PS：知道为什么小孩喜欢比考试成绩么？他们出去玩为什么喜欢比胆子大么？因为那时候能拿得出手得东西不太多。 知道你为什么喜欢搞英文么？知道你为什么喜欢代码量么？知道我为什么问你有没有问过大老板和投资人么？
> > > > 年轻人，风雨中飘摇的芸芸众生，大部分站稳脚跟都不是一件易事，自以为能拉开差距并产生鄙视链的东西也许连毛都不是，又何必去做鲁迅先生笔下那既是狼又是羊的角色呢，内心自以为有小得意，殊不知别人背后在用怪异的眼神看着你
> > > 
> > > 
> > > 我看了一堆你的讨论，结果你也就发了一堆无用的牢骚，也没有针对问题提出任何有用的建议，极端点说，那个漏洞甚至都不是你发现的。开发组也不欠你什么啊，你觉得不好用就别用，也没人强迫你用。你也别说你希望这个项目变得更好，因为我只看到你恼怒的样子
> > 
> > 
> > 是啊，**好好的开源社区，搞得跟饭圈一样恶心**，我是开心不起来的
> 
> 既然你给不出任何建议，也提交不了任何代码，又要抱怨，我的建议是别用，就不会生气，你也别回了，就这样

确实是，就跟影业一样，我这届用户不行

就好比你自己不会治病，吃了医生开的药效果也一般，那就建议别治

**Comment by shenlijun** [comment]
> > > > > @shenlijun Talk is cheap, show me your code
> > > > 
> > > > 
> > > > 1.大家用中文交流的时候非得用英文是想表达什么样的信号呢？ 2.歧视我这个白板号，那你有没有问过你们的大老板还有投资人：“show me your code”？
> > > 
> > > 
> > > 1.你真是想太多，心思这么复杂活得不累么 2.如果你有任何贡献，欢迎把你的大号亮出来我去瞻仰一番，我给你喊666
> > 
> > 
> > 1.现实中的一个场景：“哎我只是开个玩笑嘛，你怎么玩不起啊”，是怎得玩笑还是贱这个得细品。这个不是类比你的英文，只是想说有的人嘴里说的和心里想的可能不太一样。还有其实咱们的英语水平应该连很多初中生都不如； 2.我就这么个白板号，也不觉得有什么可丢人的，你把自己主页搞满了花里胡哨，说实话我也没有高看你一眼。因为很简单，这世界不只有GitHub。
> > PS：知道为什么小孩喜欢比考试成绩么？他们出去玩为什么喜欢比胆子大么？因为那时候能拿得出手得东西不太多。 知道你为什么喜欢搞英文么？知道你为什么喜欢代码量么？知道我为什么问你有没有问过大老板和投资人么？
> > 年轻人，风雨中飘摇的芸芸众生，大部分站稳脚跟都不是一件易事，自以为能拉开差距并产生鄙视链的东西也许连毛都不是，又何必去做鲁迅先生笔下那既是狼又是羊的角色呢，内心自以为有小得意，殊不知别人背后在用怪异的眼神看着你
> 
> 1.别用"咱们"，你个人仅代表你个人。 2.我也没求你也没想着你能高看我一眼。 3.针对你PS的部分，我根本不care。 4.当然欢迎有价值的讨论与合理提出问题。可在这个issue里，我看到的却是一些阴阳怪气的东西。 5.好好的开源社区变成这样，你应该反思是不是也有你的一份功劳。
> 
> 以上，后续不再做任何回复。

1.眼界低就容易自信，没见过就表示不存在，推荐再品品“坐井观天”；
2.说着不care，说着没希望别人高看，实际行动却很诚实：明显的汉语环境非要来一个英文？你的ID要叫自己“法国人”？主页搞得花里胡哨不会只想给自己看吧？网站上自我感动的小作文搞还自我鉴定？
3.看到白板号赶紧上来@一下，发个英文就不叫阴阳怪气了？别人回手一个嘴巴子，打出你一张双标脸？
