### ISSUE TITLE
中国大规模地封锁基于TLS的翻墙服务器 [请强烈考虑实施 uTLS ]

### ISSUE THREAD

**Issue by josephw1122** [XTLS/Xray-core#1253]
If more than 5 clients are simultaneously connected for a few hours (any devices, such as Windows, Android, iOS) the GFW will block the Public ipv4 address.

如果超过 5 个客户端同时连接几个小时（任何设备，例如 Windows、Android、iOS），GFW 将阻止公共 ipv4 地址。

Please implement more nondetectable elements into the protocol.
请在协议中实现更多不可检测的元素。

**Comment by josephw1122** [comment]
请强烈考虑实施 uTLS : https://github.com/refraction-networking/utls
Please strongly consider implementing uTLS : https://github.com/refraction-networking/utls
https://github.com/refraction-networking/utls


https://github.com/net4people/bbs/issues/129
中国大规模地封锁基于TLS的翻墙服务器
"自北京时间2022年10月3日起，超过一百名用户报告他们至少有一台基于TLS的翻墙服务器被封锁了。被封锁的服务器使用的协议包括了[trojan](https://github.com/trojan-gfw/trojan)，[Xray](https://github.com/XTLS/Xray-core)，[V2Ray TLS+Websocket](https://www.v2fly.org/config/transport/websocket.html)，[VLESS](https://www.v2fly.org/config/protocols/vless.html)，以及[gRPC](https://www.v2fly.org/config/transport/grpc.html)。我们还未收到任何[naiveproxy](https://github.com/klzgrad/naiveproxy)被封锁的消息。

下面是我们总结的关于这次封锁的一些信息，以其我们的一些推测和分析

封锁先是针对翻墙服务的端口。如果用户在端口被封后，[改换了端口](https://gfw.report/blog/ss_tutorial/zh/#%E9%85%8D%E7%BD%AE%E5%A4%87%E7%94%A8%E7%AB%AF%E5%8F%A3%E6%9D%A5%E7%BC%93%E8%A7%A3%E7%AB%AF%E5%8F%A3%E5%B0%81%E9%94%81)，那么整个服务器都会被封锁。需要指出，封锁似乎只是基于端口或IP地址，与翻墙服务有关的域名似乎并没有被加入到GFW的DNS或SNI黑名单中。

尽管大多数用户报告443端口被封，一部分使用非443端口的用户也报告了封锁。尽管大多数用户的服务器在流行的VPS提供商那里（[比如](https://bandwagonhost.com/)），但至少有一位用户位于欧洲的家中的服务器也被封锁了。

在一些案例中（并非全部案例中），封锁是动态的：用户通过浏览器还是可以直接访问翻墙端口，但同一个端口，用翻墙软件就连不通。

所有以上的信息都指向GFW已经可以精准的识别并封锁这些翻墙协议，而并非简单地封锁所有的443端口，或封锁所有的流行机房。

基于以上信息，我们推测（但还未进行实证性的测量），这些封锁可能与翻墙软件客户端发出的[Clienthello指纹](https://tlsfingerprint.io/)相关。开发者们或许可以考虑采用[uTLS](https://github.com/refraction-networking/utls)。这个https://github.com/net4people/bbs/issues/54，[这篇总结](https://gfw.report/blog/v2ray_weaknesses/zh/#%E7%8B%AC%E7%89%B9%E7%9A%84tls-clienthello%E6%8C%87%E7%BA%B9)，以及[这篇博文](https://zhufan.net/2022/06/18/tls%E6%8F%A1%E6%89%8B%E6%8C%87%E7%BA%B9%E6%A3%80%E6%B5%8B%E6%81%B6%E6%84%8F%E8%BD%AF%E4%BB%B6%E6%B5%81%E9%87%8F/)都是关于TLS指纹的，也许会有帮助。

下一步，我们将调查GFW是否真的使用了客户端发出的TLS指纹来识别这些协议。与此同时，如果您有任何翻墙服务器被封锁，或者有任何可以证实或反驳我们的推测的例子，我们都欢迎您或公开地或私下地与我们分享。因为这会帮助我们快速定位许多问题的根源。我们私下的联系方式可见[GFW Report](https://gfw.report/)的页脚。"

**Comment by josephw1122** [comment]
https://github.com/refraction-networking/utls#roller

**Comment by ZhuangJiayu** [comment]
老哥你有认真看之前的讨论帖吗？首先uTLS并不能解决问题，其次xray-core早就支持uTLS了

**Comment by josephw1122** [comment]
目前哪些客户端（如 Android、iOS 和 Windows）支持 uTLS？

**Comment by gzlboy** [comment]
最近ip好容易被封，新开服务器没两天，xray服务就不能用了@@

**Comment by ZhuangJiayu** [comment]
> 目前哪些客户端（如 Android、iOS 和 Windows）支持 uTLS？

自定义配置

**Comment by SekiBetu** [comment]
uTLS的未来已经明确，并不能躲避指纹检测，短期内自己试试吧，长期内可以考虑浏览器转发功能

**Comment by hedsbj** [comment]
> If more than 5 clients are simultaneously connected for a few hours (any devices, such as Windows, Android, iOS) the GFW will block the Public ipv4 address.
> 
> 如果超过 5 个客户端同时连接几个小时（任何设备，例如 Windows、Android、iOS），GFW 将阻止公共 ipv4 地址。
> 
> Please implement more nondetectable elements into the protocol. 请在协议中实现更多不可检测的元素。

如果是

**Comment by hedsbj** [comment]
如果是这样“如果超过 5 个客户端同时连接几个小时（任何设备，例如 Windows、Android、iOS），GFW 将阻止公共 ipv4 地址。”，那你协议如何 都不管用，它只是怀疑就干了你，类似于要白名单管理了

**Comment by windguider** [comment]
> 最近ip好容易被封，新开服务器没两天，xray服务就不能用了@@

你用的手机客户端是哪个

**Comment by phyzhenli** [comment]
> 最近ip好容易被封，新开服务器没两天，xray服务就不能用了@@

我也...很快就没了

**Comment by zxbiao** [comment]
说到底还是流量大和热门VPS商家的IP段原因，有些大佬说备机都基本不连的也被墙了。墙不需要知道你用什么协议，加密程度如何，只要你流量大和经常连接某些优质线路的IP段，就可以把你加入可疑名单了，加入名单之后下次就可疑触发被墙，一旦被墙之后换端口，就同于是代理服务器，所以撞墙之后一定不要从443换其他端口，套个CF的CDN苟活一下。我位于CC机房的辣鸡VPS也被墙了，套了CDN之后，今天居然解封了，能直连。

**Comment by phyzhenli** [comment]
我搭建的是纯vmess，没加任何多余的东西，两台vps分别位于Digital Ocean的旧金山和谷歌云的洛杉矶，都只有我自己用。以前没被封禁过，但在10.3号、10.9号和最近几天接连被封禁，换ip也很快被封。今天尝试了NaiveProxy，速度确实快，稳定性还有待观察。

**Comment by hunter-xue** [comment]
> 我搭建的是纯vmess，没加任何多余的东西，两台vps分别位于Digital Ocean的旧金山和谷歌云的洛杉矶，都只有我自己用。以前没被封禁过，但在10.3号、10.9号和最近几天接连被封禁，换ip也很快被封。今天尝试了NaiveProxy，速度确实快，稳定性还有待观察。

我也是一样的情况，Digital Ocean莫名被封，没有其他用户，自己用的流量也不大，只是日常的上网。
不过，traceroute一下，发现最终无法连接的那一条好像不是在骨干网上，是在digital ocean那一侧。已经提交了SR，等待客服回复原因...

**Comment by evolutionboy** [comment]
<img width="1045" alt="AES指纹_2022-10-17_22-09-50" src="https://user-images.githubusercontent.com/15674703/196244334-9d97b7ee-0179-4636-9512-1e0c783209f3.png">
这张图里说的是真是假呀，好像这帐号是四小时前才注册的，我也是tg上看到这张截图的。

**Comment by bbcbbk** [comment]
> @evolutionboy 应该是真的。这很好的解释了 Trojans 这两天也不行了。

这样看来 我只在x86软路由上用可能也是我这次9台小鸡一个没挂的原因吧

**Comment by f1098** [comment]
@evolutionboy 也有用户报告说，电脑能连，手机就是不能。我记得 Nginx 和 Xray 都可以指定加密方法的吧？有除外AES和国密的常用加密方法（参数）吗？

**Comment by XgHao** [comment]
uTls 服务端配了后 客户端还需要配置吗

**Comment by chika0801** [comment]
> uTls 服务端配了后 客户端还需要配置吗

只改客户端配置

**Comment by mclovin-2k** [comment]
我觉得就是你们配置/用法有问题。
我自己的卢森堡，圣何塞，新加坡，首尔等多个VPS，全部都是传统的VLESS + XTLS + WS + GRPC配置，没有一个被封的。

**Comment by qiangliu8183** [comment]
> 我觉得就是你们配置/用法有问题。 我自己的卢森堡，圣何塞，新加坡，首尔等多个VPS，全部都是传统的VLESS + XTLS + WS + GRPC配置，没有一个被封的。

你牛逼，GFW给你开绿灯

**Comment by ChainZeaxion** [comment]
> > 我觉得就是你们配置/用法有问题。 我自己的卢森堡，圣何塞，新加坡，首尔等多个VPS，全部都是传统的VLESS + XTLS + WS + GRPC配置，没有一个被封的。
> 
> 你牛逼，GFW给你开绿灯

可以反向发展，封锁是基于你的流量特征异常，那你就伪装成正常流量跑，比如某些大站的CDN，某些测速网站的CDN这样
由于使用习惯，很少有对源IP和目的IP长时间长链接大流量跑吧
如果有这种习惯，那怎么伪装，应该还是会被淦
就大部分日常使用来说，这流量都是起起伏伏
所以尽可能伪装成大站流量跑，还是比较靠谱，尤其是伪装成测速站

**Comment by mclovin-2k** [comment]
> > 我觉得就是你们配置/用法有问题。 我自己的卢森堡，圣何塞，新加坡，首尔等多个VPS，全部都是传统的VLESS + XTLS + WS + GRPC配置，没有一个被封的。
> 
> 你牛逼，GFW给你开绿灯

大多数被封端口/IP的反馈，都没有什么有效信息。与其说是反馈，不如说是臆测/抱怨。
我只能认为这些人的技术水平偏低，很可能不了解 V2Ray / Xray 这类工具的一些常识性知识（比如禁止 Server 端访问 CN ）。
从 GoAgent、SS、SSR 到 Vmess、TLS，被封的抱怨从未停止过。
我并不觉得现在的抱怨和以前的抱怨有什么区别。

**Comment by littlemingone** [comment]
> > > 我觉得就是你们配置/用法有问题。 我自己的卢森堡，圣何塞，新加坡，首尔等多个VPS，全部都是传统的VLESS + XTLS + WS + GRPC配置，没有一个被封的。
> > 
> > 
> > 你牛逼，GFW给你开绿灯
> 
> 大多数被封端口/IP的反馈，都没有什么有效信息。与其说是反馈，不如说是臆测/抱怨。 我只能认为这些人的技术水平偏低，很可能不了解 V2Ray / Xray 这类工具的一些常识性知识（比如禁止 Server 端访问 CN ）。 从 GoAgent、SS、SSR 到 Vmess、TLS，被封/不能用的抱怨从未停止过。 我并不觉得现在的抱怨和以前的抱怨有什么区别。

问一下，你的这些vps有手机端用户吗？目前很多人都反应说电脑连没事，安卓的v2rayng或者苹果的shadowrocket连完就要寄

**Comment by mclovin-2k** [comment]
> > > > 我觉得就是你们配置/用法有问题。 我自己的卢森堡，圣何塞，新加坡，首尔等多个VPS，全部都是传统的VLESS + XTLS + WS + GRPC配置，没有一个被封的。
> > > 
> > > 
> > > 你牛逼，GFW给你开绿灯
> > 
> > 
> > 大多数被封端口/IP的反馈，都没有什么有效信息。与其说是反馈，不如说是臆测/抱怨。 我只能认为这些人的技术水平偏低，很可能不了解 V2Ray / Xray 这类工具的一些常识性知识（比如禁止 Server 端访问 CN ）。 从 GoAgent、SS、SSR 到 Vmess、TLS，被封/不能用的抱怨从未停止过。 我并不觉得现在的抱怨和以前的抱怨有什么区别。
> 
> 问一下，你的这些vps有手机端用户吗？目前很多人都反应说电脑连没事，安卓的v2rayng或者苹果的shadowrocket连完就要寄

当然有了，V2RayNG、SagerNet、Matsuri。全部都用。
你说的那些人以前有，现在有，将来仍然会有。

**Comment by ChainZeaxion** [comment]
> 

我毛子的线路已经快5年了，自从配置开出来到现在，一直没挂过，最开始sr裸奔仨月，四年前改直接前置sr后置web，三年前改前置sr后接tr再接web再接v2，两年前把尾巴上的v2加了grpc
美西俩个，有一个被鈤了半年放出来了，另一个一直没出过事
美西那个是四年前被鈤的，后面一起跟毛子线路一样时间点改过配置之后再也没被鈤过
港港线路是三年前加的，开出来就跟毛子线路一样做配置

客户端ios 安卓 windows linux routeros啥都有
app 基本上能用的都测了，不能用的也测了（那肯定连不上）
现在是直连ojbk，cdn中转ojbk
唯一的就是grpc套cdn非443，原理上少了前置sr和tr两层，用的备用8443
直连443=sr=tr/trwbst=v2=grpc=web
直连8443=v2=grpc=web

带宽速度上（大流，下载，视频缓冲）
直连 trwbst>v2wbst>sr>grpc
套cdn trwbst>v2wbst>grpc
反应速度上（小流，网页，api查询）
直连 grpc>sr>tr/trwbst/v2wbst
套cdn gprc>=trwbst>v2wbst

mux可以酌情开，对小流有明显提升，尤其是安卓客户端，很多不开mux速度死慢
大流不能太频繁新增操作，比如短时间内多次启动测速-中断测速-快速再跑测速，会导致链路阻塞断流

另外我所有线路都没禁cn，其实正常情况下，不太清楚禁不禁有多大好处，还没接触到相关资料依据

**Comment by wanglongbiao** [comment]
> 说到底还是流量大和热门VPS商家的IP段原因，有些大佬说备机都基本不连的也被墙了。墙不需要知道你用什么协议，加密程度如何，只要你流量大和经常连接某些优质线路的IP段，就可以把你加入可疑名单了，加入名单之后下次就可疑触发被墙，一旦被墙之后换端口，就同于是代理服务器，所以撞墙之后一定不要从443换其他端口，套个CF的CDN苟活一下。我位于CC机房的辣鸡VPS也被墙了，套了CDN之后，今天居然解封了，能直连。

确实，我一开始端口被封了，换了端口之后能用，然后 ip 就被封了，到现在还不能连上。

**Comment by azzvx** [comment]
今天试着架tuic，手贱用QQ的代理测试测通了没有，然后发现域名被封了，Xray也跟着躺枪（用的同一套证书）。
对，就是域名（或者说证书）。
双端换IP，只要TLS带SNI，秒封。
IP直接裸连正常，换域名后正常。

**Comment by ChainZeaxion** [comment]
> 

我这环境是电信，我发现电信这激霸玩意儿发现你大流量之后先拉高延迟，再拉低带宽，基本上油管4K60fps就是个门限，也就是单线程超过50Mbps（短时间瞬发似乎问题不大）一定时间，可能超过10秒就开始搞事情了，最惨不忍睹的是延迟翻三倍，带宽拉到最大2Mbps，而且tcp丢包拉到65%，udp丢包拉到45%
但是只要你在这个门限以内，比如你各种调优限制死你最大突发就45Mbps而且小于10秒（10秒只是个推测值），那基本上就一路畅通

**Comment by yohototo** [comment]
443端口被封了会自动解封吗>_<

**Comment by sishldadao** [comment]
> 
这种就是被QoS了，如果流量一直高，就会被彻底封了。我被封过好几次

**Comment by HaiGe120** [comment]
> 我搭建的是纯vmess，没加任何多余的东西，两台vps分别位于Digital Ocean的旧金山和谷歌云的洛杉矶，都只有我自己用。以前没被封禁过，但在10.3号、10.9号和最近几天接连被封禁，换ip也很快被封。今天尝试了NaiveProxy，速度确实快，稳定性还有待观察。
你好，请问后续有被封锁吗

**Comment by phyzhenli** [comment]
> 我搭建的是纯vmess，没加任何多余的东西，两台vps分别位于Digital Ocean的旧金山和谷歌云的洛杉矶，都只有我自己用。以前没被封禁过，但在10.3号、10.9号和最近几天接连被封禁，换ip也很快被封。今天尝试了NaiveProxy，速度确实快，稳定性还有待观察。
> 你好，请问后续有被封锁吗

最近用了一个月，稳定性非常好，没有被封过。就是某些ip的vps会在某些wifi甚至4G下连不通（vps没问题，因为另一台笔记本可以连），我后来挑了一个在所有wifi和4G下都能连的IP，一直用到现在，没有问题。

**Comment by ZqinKing** [comment]
> 说到底还是流量大和热门VPS商家的IP段原因，有些大佬说备机都基本不连的也被墙了。墙不需要知道你用什么协议，加密程度如何，只要你流量大和经常连接某些优质线路的IP段，就可以把你加入可疑名单了，加入名单之后下次就可疑触发被墙，一旦被墙之后换端口，就同于是代理服务器，所以撞墙之后一定不要从443换其他端口，套个CF的CDN苟活一下。我位于CC机房的辣鸡VPS也被墙了，套了CDN之后，今天居然解封了，能直连。

换不换端口没关系，只要放一段时间它就会解封，大概需要二十几天。

**Comment by chika0801** [comment]
建议关闭这个ISS

**Comment by hamedsbt** [comment]
The Trojan-Server, in my opinion, should be treated as a regular web server and should serve a web page by default.
So Trojan-Server should detect requests generated by Trojan-Client? If it isn't, serve a specified web page (site).

**Comment by FisherMS** [comment]
> 最近ip好容易被封，新开服务器没两天，xray服务就不能用了@@
疯了一样。

**Comment by FisherMS** [comment]
> 如果是这样“如果超过 5 个客户端同时连接几个小时（任何设备，例如 Windows、Android、iOS），GFW 将阻止公共 ipv4 地址。”，那你协议如何 都不管用，它只是怀疑就干了你，类似于要白名单管理了。这样的话自己搭自己小范围内用可能 更安心

现在应该就是这样了吧。

**Comment by fingertap** [comment]
我测试了一下，我这边是所有的https流量都被禁了，但是http的流量没事。不管走的是哪个端口，443或者别的也好，https这种他识别不了的都会挂。我自己的网站80能访问,443和别的用https的就不行。

**Comment by myrisc** [comment]
我碰到个神奇的问题，oracle的鸡一个没封，联通的宽带，走的全是vless+xtls,好好的一年多了，稳得很，但是最近入手了buyvm的，开始好好的vless，几天后不行了，开不开tls全都无法翻，感觉不是墙的问题，ip也通端口也通，重装了vps也不行，但是ssr就没问题，头一次碰到这问题，难道buyvm那边封了协议

**Comment by Fangliding** [comment]
finished
