### ISSUE TITLE
Want xtls to support socks

### ISSUE THREAD

**Issue by cod-soap** [XTLS/Xray-core#1260]
I'm testing xray-core performance  now. when I want to try socks5 protocol with xtls. Happend the flowing error :

 `Failed to start: main: failed to load config files: [xxxx.json] > /infra/conf: XTLS doesn't supports socks for now.`
![image](https://user-images.githubusercontent.com/25627194/196310058-6f271b24-5335-486f-8bd2-2edf082c59d5.png)

So，Is any plan For xtls to support socks?
Or I do it by myself, How to do it, I need some suggestion.

Here is My config.json
```json
{
    "inbounds": [
        {
            "port": 8000,
            "protocol": "socks",
            "settings": {
                "clients": [
                    {
                        "id": "1eb6e917-774b-4a84-aff6-b058577c60a5"
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "minVersion": "1.2",
                    "maxVersion": "1.2",
                    "certificates": [
                        {
                            "certificateFile": "xxx.crt",
                            "keyFile": "xxx.key"
                        }
                    ]
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "settings": {

            }
        }
    ],
    "log": {
        "access": "access.log",
        "error": "error.log",
        "loglevel": "warning",
        "dnsLog": false
    }
}

```

**Comment by cod-soap** [comment]
Aslo I want to know. What protocols does xtls support？
I found example which shows support trojan and vless

**Comment by e1732a364fed** [comment]
> only support vless or trojan. xtls implementation is quite complex. I think it is hard to port to support other protocols

只是v2ray/xray的架构 以及 实现的位置单独放在了每个protocol里 导致的而已。只要解耦合即可。比如 在verysimple中 同类的 tls lazy encrypt 可以支持 所有明文传输的协议，如 socks，trojan 和 vless。

**Comment by yuhan6665** [comment]
解耦和是一个问题，目前写法把过滤，padding，裸奔都放在一起了。确实，过滤和padding 将来可以看怎么改成通用的
