### ISSUE TITLE
v2ray use multiple connection and then bond them at other end

### ISSUE THREAD

**Issue by lambdaxyzt** [XTLS/Xray-core#1263]
there is problem in internet which ISP's throttle download and upload rate , but not sure how , but it mostly should be done per TCP Connection , for example you bought VPS with 1Gbps speed as they say in Plan , but when you want use it , speed maybe goes around 200Mbps or lower or even blocked like torrent download , anyway , there is a solution that if you can split TCP connection among multipath and then join them at other end , but ISP sees every path as separate connection so does not throttled them , maybe I have some academic mistakes but I think you should get idea , maybe we should use a solution for linux not v2ray but need to know how do it then how use it with v2ray.
any suggestion ?!

**Comment by MorrowShore** [comment]
Would be really cool though? There's MUX already, might as well go all the way.
