### ISSUE TITLE
新版1.61，如何配置的几点疑问。

### ISSUE THREAD

**Issue by AxIauk** [XTLS/Xray-core#1268]
1、原使用 VLESS over TCP with XTLS，现在如何修改？改成VLESS+TCP+TLS后再用uTLS？
2、uTLS的配置参数增加到配置文件的什么位置？有没有简洁的配置案例？
"tlsSettings": {
    "fingerprint": "chrome"
}

**Comment by chika0801** [comment]
如果你用v2rayn，就把xtls改成 tls，下面有使用指纹的选项（英文）

然后你去它文件夹里看config.json文件就懂了

**Comment by AxIauk** [comment]
（使用xtls 没用tls）
服务器这么设置行吗？
"inbounds"
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
          "allowInsecure": false, 
          **"fingerprint": "chrome"**
          "minVersion": "1.2", 
          "alpn": ["http/1.1"],
          "certificates": [
            {
              "certificateFile": "/etc/apache2/ssl.crt/ca-bundle.crt",
              "keyFile": "/etc/ssl/private/ssl-cert-snakeoil.key"
            }
          ]

linux客户端，透明代理
"outbounds"
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        **"fingerprint": "chrome"**
        "sockopt": {
          "mark": 2
        }

**Comment by yuhan6665** [comment]
xtls 目前 不支持 utls
另外 utls fingerprint 只需要在客户端配置
