### ISSUE TITLE
对于没有使用 chrome/* 指纹的 tls 客户端丢弃链接

### ISSUE THREAD

**Issue by ellermister** [XTLS/Xray-core#1272]
如何配置服务器, 对于没有使用 chrome 指纹的链接选择丢弃。

这将能够有助于定位分析出 `fingerprint: chrome` 的作用，验证服务器被封禁因素。

@HirbodBehnam

**Comment by yuhan6665** [comment]
I think it does not make sense to drop connection since fingerprint changes over time.
A good way is to add fingerprint to sharing links so all clients can update it.

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/issues/1539#issuecomment-1386573605
https://github.com/XTLS/Xray-core/issues/1472#issuecomment-1382683509
