### ISSUE TITLE
路由模块端口无法入站

### ISSUE THREAD

**Issue by Yuki-J1** [XTLS/Xray-core#1275]
有个软件会使用80,443,20002,30840,38050,30841-30859这些端口。
![image](https://user-images.githubusercontent.com/41263770/197700515-54c223c0-8a4e-436f-bb07-14d0ca804ffe.png)
![image](https://user-images.githubusercontent.com/41263770/197700773-65f8da9e-6f3e-4f0b-9ea8-6d74877ea43a.png)
![image](https://user-images.githubusercontent.com/41263770/197702745-75d50fd0-771d-40cd-82d8-82835894a9b1.png)

然后我想让这些端口产生的流量走代理，然后我修改了我的客户端配置文件

{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "debug"
  },
  "inbounds": [
    {
      "tag": "socks",
      "port": 10808,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": false,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "allowTransparent": false
      }
    },
    {
      "tag": "http",
      "port": 10809,
      "listen": "127.0.0.1",
      "protocol": "http",
      "sniffing": {
        "enabled": false,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "allowTransparent": false
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "",
            "port": 12257,
            "users": [
              {
                "id": "",
                "alterId": 0,
                "email": "",
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp"
      },
      "mux": {
        "enabled": false,
        "concurrency": -1
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    }
  ],
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "domainMatcher": "linear",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "enabled": true
      },
      {
        "type": "field",
        "port": "80,443,20002,30840,38050,30841-30859",
        "inboundTag": [],
        "outboundTag": "proxy",
        "enabled": true
      },
      {
        "type": "field",
        "port": "7777-7778,27015,3478-3480,27060,50481",
        "inboundTag": [],
        "outboundTag": "proxy",
        "enabled": true
      },
      {
        "type": "field",
        "inboundTag": [],
        "outboundTag": "direct",
        "domain": [
          "geosite:cn"
        ],
        "enabled": true
      },
      {
        "type": "field",
        "inboundTag": [],
        "outboundTag": "direct",
        "ip": [
          "geoip:private",
          "geoip:cn"
        ],
        "enabled": true
      }
    ]
  }
}

尝试代理后发现80 443好像被代理了，其他的端口没有被代理。
![image](https://user-images.githubusercontent.com/41263770/197701168-02fd691d-ccc1-4ea2-ac54-ca1131304722.png)

![image](https://user-images.githubusercontent.com/41263770/197701393-92c9ca52-c020-4fcd-89ff-f280d2ea9711.png)

![image](https://user-images.githubusercontent.com/41263770/197703124-f65a2bbb-06f1-4c38-ae8a-e463d739ec40.png)

请问这是为什么，该如何解决呢，拜谢<(_ _*)>

**Comment by azzvx** [comment]
可能你的软件不支持读取系统的代理设置，你可以使用Proxifier强制软件走代理。

**Comment by Yuki-J1** [comment]
> 

谢谢你的建议，我回去考虑并尝试。

**Comment by Yuki-J1** [comment]
> 

![image](https://user-images.githubusercontent.com/41263770/197724980-60f93f1f-e686-401e-a474-f2b3cd0862ab.png)
我使用了您说的Proxifier并设置了代理指向xray的代理127.0.0.1:10809, 我成功在日志中看到了代理信息。
非常感谢您的帮助。

**Comment by Yuki-J1** [comment]
> 可能你的软件不支持读取系统的代理设置，你可以使用Proxifier强制软件走代理。

![image](https://user-images.githubusercontent.com/41263770/197725610-dda5e8d0-2dd5-4a65-addc-fe56674ae4d3.png)

我使用了您说的Proxifier并设置了代理指向xray的代理127.0.0.1:10809, 我成功在日志中看到了代理信息。
非常感谢您的帮助。

**Comment by yuhan6665** [comment]
Close as solved
