### ISSUE TITLE
给服务器被强的各位提一个建议

### ISSUE THREAD

**Issue by hkbase** [XTLS/Xray-core#1276]
**很多时候vps被封，并不是加密方式被墙正向识别的，而是国产软件及互联网服务商这些内鬼，主动上报给墙的管理部门的。**

国产软件及互联网服务提供商，都有后台上报机制，发现实名账号通过国外ip使用服务，都会被标记上报，举例：国内账号通过国外ip访问阿里云盘服务，会导致阿里云盘账号被封，同时相关部门也就知道了你在翻墙。
建议：在vps的xray服务分流规则配置时加上禁止国内域名ip访问，从而避免带来vps的ip被墙的风险。
参考代码规则如下：

>    "routing": {
    "domainStrategy": "IPIfNonMatch",
        "rules": [
      {
      "type": "field",
      "domain": ["geosite:category-ads-all","geosite:cn"],
      "outboundTag": "block"
      },  
      {
      "type": "field",
      "outboundTag": "block",
      "ip": ["geoip:cn"]
             }
        ]
    },

**Comment by chika0801** [comment]
https://github.com/XTLS/Xray-core/discussions/593#discussioncomment-845165

这里早说说过了

**Comment by AxIauk** [comment]
按规则修改了，怎么简单测试？

**Comment by chika0801** [comment]
> 按规则修改了，怎么简单测试？

如果你问vps禁止访问cn ip，要测试，在客户端路由规则全局走代理，打不开cn网站既生效了。

**Comment by Cptmacmillan2022007** [comment]
> > 按规则修改了，怎么简单测试？
> 
> 如果你问vps禁止访问cn ip，要测试，在客户端路由规则全局走代理，打不开cn网站既生效了。

按照那个代码规则测试了下确实如此

**Comment by wancaibida** [comment]
`category-ads-all` 也需要吗

**Comment by hkbase** [comment]
才发完帖子，我的服务器也被封了，应该是针对性的阻断，ip可以ping通，但就是xray（vless+tcp+xtls）服务连接不上。

**Comment by Michaol** [comment]
> 

我也是vless+tcp+xtls集体沦陷（换端口也不能恢复，通过其他VPS分流过去其实是正常能用，唯国内不行），其他协议无论走tls或者xtls，端口基本24小时被阻断，log会看到端口开始是正常的，一旦有稍大流量数据就出现握手失败，端口活命时间最长的是trojan和SS（2002-blake3），10000以下端口甚至几分钟到几个钟就被阻断，推测是为了对付CF CDN转发。

**Comment by FarrowE** [comment]
> > 按规则修改了，怎么简单测试？
> 
> 如果你问vps禁止访问cn ip，要测试，在客户端路由规则全局走代理，打不开cn网站既生效了。

不应该测试cn ip，应该在geoip:cn或geosite之外再单独+一条外国网站的IP，然后通过代理访问测试，如果是CN IP用来测试，如果设置不成功，反而自投罗网。应该测试一个无关外国的IP或网站，确认特定网站无法访问再试试CN风险才低。

**Comment by Cptmacmillan2022007** [comment]
> > > 按规则修改了，怎么简单测试？
> > 
> > 
> > 如果你问vps禁止访问cn ip，要测试，在客户端路由规则全局走代理，打不开cn网站既生效了。
> 
> 不应该测试cn ip，应该在geoip:cn或geosite之外再单独+一条外国网站的IP，然后通过代理访问测试，如果是CN IP用来测试，如果设置不成功，反而自投罗网。应该测试一个无关外国的IP或网站，确认特定网站无法访问再试试CN风险才低。

试下这个网站

ipleak.net

如果没有cn的国旗基本安全

**Comment by earendal** [comment]
有道理，决定在VPS上修改下

**Comment by Smallthing** [comment]
> ipleak.net

有没有可能 ，这种网站本身就是钓鱼的呢

**Comment by cross-hello** [comment]
We would not use such websites which only possible be used for domestic 
residents.

----------------------------------------

*From: *Smallthing ***@***.***>
*To: *XTLS/Xray-core ***@***.***>
*CC: *Subscribed ***@***.***>
*Date: *Nov 17, 2022 04:41:10
*Subject: *Re: [XTLS/Xray-core] 给服务器被强的各位提一个建议 (Issue #1276)

**Comment by taxtigerno1** [comment]
> 昨天才发完帖子，今天我的服务器也被封了，应该是针对性的阻断， xray版本为1.6.0 具体表现为：vps的ip可以ping通，也可以正常ssh上去，但就是xray（vless+tcp+xtls）服务连接不上，trojan协议，也挂了。 很快就被打脸，看来这几天大家应该都集体沦陷了，😭～～ 猜测应该与最近爆出的那个漏洞有关。

我今天也出现这情况，没有nginx作伪装站，就vless+tls和trojan+tls，域名申请了证书，结果还是被墙。但是ssh能连接上，应该是域名被墙了。请问怎么解决？

**Comment by RPRX** [comment]
@taxtigerno1 2025 年了，还不用 Vision 不用 REALITY 不用 XHTTP 的话就别翻墙了

**Comment by taxtigerno1** [comment]
> [@taxtigerno1](https://github.com/taxtigerno1) 2025 年了，还不用 Vision 不用 REALITY 不用 XHTTP 的话就别翻墙了

我有个节点就是trojan+reality的，还是被封了

**Comment by RPRX** [comment]
@taxtigerno1 Trojan 那么明显的典型 TLS in TLS，不封你封谁

**Comment by RPRX** [comment]
@taxtigerno1 你有没有想过问题在于你就是要搞这些奇葩用法，都 REALITY 了，好好的 Vision 你不用，非要去搭配 Trojan

**Comment by taxtigerno1** [comment]
> [@taxtigerno1](https://github.com/taxtigerno1) 你有没有想过问题在于你就是要搞这些奇葩用法，都 REALITY 了，好好的 Vision 你不用，非要去搭配 Trojan

谢谢大佬指教，我加你tg频道了。现在貌似域名被封，好像ip没被封，是不是搭建一个vless+vision+reality节点可以拯救？请大佬指教

**Comment by RPRX** [comment]
IP 没被封的话你可以试下 REALITY Vision/XHTTP 偷大厂域名，不过你这个 IP 有黑历史了，可能以后会被重点关注，或者被拉清单

**Comment by WFGukasha** [comment]
考古，这是一个22年的issue哩！不过最近gfw貌似有点虚

**Comment by taxtigerno1** [comment]
> IP 没被封的话你可以试下 REALITY Vision/XHTTP 偷大厂域名，不过你这个 IP 有黑历史了，可能以后会被重点关注，或者被拉清单

偷大厂域名是怎么回事？我自己有域名，然后用自己域名不行是吗？我知道reality不需要域名

**Comment by WFGukasha** [comment]
> > IP 没被封的话你可以试下 REALITY Vision/XHTTP 偷大厂域名，不过你这个 IP 有黑历史了，可能以后会被重点关注，或者被拉清单
> 
> 偷大厂域名是怎么回事？我自己有域名，然后用自己域名不行是吗？我知道reality不需要域名


比如火狐的addons，这玩意其实怕误ban的，可以利用这一点

**Comment by RPRX** [comment]
不是用自己的域名不行，而是你那边 GFW 不待见你自己的域名，就应该偷别人的域名

以及你用自己域名的话，Trojan+REALITY 在流量特征上就是纯 Trojan，怪不得你被封，可能你但凡用个 Vision 就不会被封了

**Comment by WFGukasha** [comment]
> 不是用自己的域名不行，而是你那边 GFW 不待见你自己的域名，就应该偷别人的域名
> 
> 以及你用自己域名的话，Trojan+REALITY 在流量特征上就是纯 Trojan，怪不得你被封，可能你但凡用个 Vision 就不会被封了

那我现在在后台无差别禁止流量回国这个方法可行吗？~~毕竟国内网站走代理本来就很神金~~

**Comment by taxtigerno1** [comment]
> addons

我的域名使用的是cloundflare解析DNS到VPS，现在我把小云朵点亮使用代理状态原来的节点也连接不上。请问现在所谓的偷大厂域名是指那个地方要配置大厂的域名呢？

**Comment by WFGukasha** [comment]
> > addons
> 
> 我的域名使用的是cloundflare解析DNS到VPS，现在我把小云朵点亮使用代理状态原来的节点也连接不上。请问现在所谓的偷大厂域名是指那个地方要配置大厂的域名呢？

传输层安全选reality，sni用火狐addons，指纹也是火狐

**Comment by RPRX** [comment]
> 那我现在在后台无差别禁止流量回国这个方法可行吗？~~毕竟国内网站走代理本来就很神金~~

当然要禁，不然一去一回直接对上了

**Comment by WFGukasha** [comment]
> > addons
> 
> 我的域名使用的是cloundflare解析DNS到VPS，现在我把小云朵点亮使用代理状态原来的节点也连接不上。请问现在所谓的偷大厂域名是指那个地方要配置大厂的域名呢？

tls选reality，sni用火狐addons，浏览器指纹也选择火狐

**Comment by RPRX** [comment]
> > > 那我现在在后台无差别禁止流量回国这个方法可行吗？~毕竟国内网站走代理本来就很神金~
> > 
> > 
> > 当然要禁，不然一去一回直接被 GFW 对上了
> 
> 再加上双浏览器，分别负责国内外网站的访问

我就是 Chrome 访问国外，Edge 访问国内，Tor 登录 GitHub，我不开系统全局代理的

**Comment by WFGukasha** [comment]
> > > > 那我现在在后台无差别禁止流量回国这个方法可行吗？~毕竟国内网站走代理本来就很神金~
> > > 
> > > 
> > > 当然要禁，不然一去一回直接被 GFW 对上了
> > 
> > 
> > 再加上双浏览器，分别负责国内外网站的访问
> 
> 我就是 Chrome 访问国外，Edge 访问国内，Tor 登录 GitHub，我不设系统全局代理的

我是双火狐

**Comment by taxtigerno1** [comment]
> > > > 那我现在在后台无差别禁止流量回国这个方法可行吗？~毕竟国内网站走代理本来就很神金~
> > > 
> > > 
> > > 当然要禁，不然一去一回直接被 GFW 对上了
> > 
> > 
> > 再加上双浏览器，分别负责国内外网站的访问
> 
> 我就是 Chrome 访问国外，Edge 访问国内，Tor 登录 GitHub，我不设系统全局代理的

不同区域还要用不同浏览器，好累

**Comment by h0cheung** [comment]
Google 的国内域名，如 service.googleapi.cn、play商店国内 cdn 等，也属于需要被拦截的范畴吗

**Comment by Kc2353** [comment]
> Google 的国内域名，如 service.googleapi.cn、play商店国内 cdn 等，也属于需要被拦截的范畴吗

问题是 **“回程流量”会经过墙** ，与具体目标可信与否无关

**Comment by Kc2353** [comment]
硬要说大概就是是否可以解密了，但是对判断基本无影响
