### ISSUE TITLE
Feature Request:（社群建设）创建Matrix聊天室并与现有Telegram频道桥接

### ISSUE THREAD

**Issue by Kruegerrr** [XTLS/Xray-core#1278]
[Matrix](https://matrix.org/)作为一个开源、安全、邦联式的通信网络正在被越来越多的开源社群使用，请问Project X开发者能否考虑在Matrix上创建聊天室，并利用Matrix的桥接功能使现有的Telegram频道与Matrix聊天室互通，让用户能更自由的平台选择仔细想使用的通信平台？

**Comment by yuhan6665** [comment]
Thanks for your suggestion, not consider it for now
