### ISSUE TITLE
Apple IOS ( Oneclick - 91VPN - FairVPN -Other clients) Problem with 1.4.5 or Higher

### ISSUE THREAD

**Issue by soda120new** [XTLS/Xray-core#1285]
Only with version 1.4.2 or 1.4.3 apple IOS vmess clients (Like : OneClick . 91VPN . FairVPN ....) works . Not works with higher versions . Why ?

**Comment by userisamir** [comment]
+1

**Comment by asalisaf** [comment]
+1

**Comment by yuhan6665** [comment]
alterId issue. Need to update server.

**Comment by soda120new** [comment]
> alterId issue. Need to update server.

Update server to which version exactly  ?

**Comment by soda120new** [comment]
Not solved with 1.6.2

**Comment by MrVb0** [comment]
> Only with version 1.4.2 or 1.4.3 apple IOS vmess clients (Like : OneClick . 91VPN . FairVPN ....) works . Not works with higher versions . Why ?

I have this problem too, please help me [#240](https://github.com/XrayR-project/XrayR/issues/240)
