### ISSUE TITLE
xray issue

### ISSUE THREAD

**Issue by dark190** [XTLS/Xray-core#1286]
Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 linux/amd64)

A unified platform for anti-censorship.

2022/10/27 22:05:10 [Info] infra/conf/serial: Reading config: bin/config.json

Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: invalid VMess user > json: cannot unmarshal string into Go struct field VMessAccount.alterId of type uint16

please help

**Comment by yuhan6665** [comment]
wrong config. Please update to new version.
