### ISSUE TITLE
xray出现内存溢出问题

### ISSUE THREAD

**Issue by kasugu** [XTLS/Xray-core#1288]
xray核心在我的设备上出现了严重的内存溢出问题，占用大量内存和cpu资源，出现时机大约是网络上传带宽占用较高/xray某个出站协议出现连接问题时，日志可以看到大量连接失败记录，在短时间内打印了几万行的连接失败日志，大小大约几百兆字节。截图第一张为第二次出现该问题时的cpu占用
![IMG_20221028_203849](https://user-images.githubusercontent.com/86145376/198589573-b8ed2c94-d514-4db6-b870-3610e89260cf.jpg)
第二张为第一次出现该问题时第一页最后的日志记录
![IMG_20221028_204111](https://user-images.githubusercontent.com/86145376/198589692-6b533edd-4747-4777-8217-02ae937976ad.jpg)
第三张为最后一页最后的日志记录
![IMG_20221028_204255](https://user-images.githubusercontent.com/86145376/198590117-ba939074-bf67-4ebe-ba52-7ae3703ea534.jpg)

**Comment by XuuKoo** [comment]
发现同样的问题

**Comment by kasugu** [comment]
第三次出现此问题，可以看到xray的内存占用在一分钟内从1300兆字节增长到了1500兆字节(实际用时可能半分钟不到)
![Screenshot_2022-10-29-18-19-51-701_com omarea vtools](https://user-images.githubusercontent.com/86145376/198827207-4ca92f2a-eecb-4e7b-9451-29df69e8c73e.jpg)
![Screenshot_2022-10-29-18-20-11-197_com omarea vtools](https://user-images.githubusercontent.com/86145376/198827211-2cbef482-af96-46e6-9862-ce83330bc32c.jpg)

**Comment by XuuKoo** [comment]
我用老版本了，新的ss暂时用不上

**Comment by aabbccgg** [comment]
The same problem. And maybe is the ipv6 or quic's connection error in my case.

**Comment by aabbccgg** [comment]
The same problem. And maybe it is the ipv6 or quic's connection error in my case.
