### ISSUE TITLE
Create account 

### ISSUE THREAD

**Issue by arshamX** [XTLS/Xray-core#1289]
How can i create multi accounts with same port like 1234

**Comment by 0xLem0nade** [comment]
For Vmess/VLESS :
```
{
    "inbounds": [
        {
            // rest of the config
            "protocol": "vmess",
            "settings": {
                "clients": [
                    {
                        "id": "client1-uuid",
                        "security": "aes-128-gcm"
                    },
                    {
                        "id": "client2-uuid",
                        "security": "chacha20-poly1305"
                    }
                ]
            }
            // rest of the config
        }
    ]
}
```

For Trojan:
```
{
    "inbounds": [
        {
            // rest of the config
            "protocol": "trojan",
            "settings": {
                "clients": [
                    {
                        "password": "client1-password",
                        "email": "client2-email"
                    },
                    {
                        "password": "client2-password",
                        "email": "client2-email"
                    }
                ]
            }
            // rest of the config
        }
    ]
}
```

**Comment by arshamX** [comment]
thanks for your time but this way makes accounts in one time i would like to create accounts in different time periods

**Comment by 0xLem0nade** [comment]
As stated in the [wiki](https://xtls-github-io.translate.goog/config/api.html#%E7%9B%B8%E5%85%B3%E9%85%8D%E7%BD%AE), the API interface might be what you're looking for:
>Add a user to an inbound proxy (VMess, VLESS, Trojan, Shadowsocks (v1.3.0+) only);
>Delete a user in an inbound proxy (VMess, VLESS, Trojan, Shadowsocks (v1.3.0+) only);

But I haven't had any experience with that so far. If you get it working, update us here.

**Comment by yuhan6665** [comment]
You can find good examples of api usage in https://github.com/crossfw/Xray-API-documents
