### ISSUE TITLE
希望Trojan协议能够支持xtls-rprx-vision流控

### ISSUE THREAD

**Issue by DreamFerry** [XTLS/Xray-core#1290]
在我尝试基于Trojan使用最新的xtls-rprx-vision流控时发现以下错误提示：
Trojan clients: "flow" doesn't support "xtls-rprx-vision" in this version
希望能够提供支持

**Comment by 70599** [comment]
这不是错误，这是正常提示，请看好release的说明

**Comment by DreamFerry** [comment]
> 这不是错误，这是正常提示，请看好release的说明

请注意，本issue发出时维护者尚未提供完整的说明
