### ISSUE TITLE
如何开启TFO

### ISSUE THREAD

**Issue by GeorgeRudd** [XTLS/Xray-core#1291]
服务端 debian10 /etc/sysctl.conf 里设置 net.ipv4.tcp_fastopen=3
客户端 win11 android12 
v2rayN v2rayNG 都使用自定义配置 ss2022协议
"sockopt": {
"tcpFastOpen": true
}
使用 grep '^TcpExt:' /proc/net/netstat | cut -d ' ' -f 87-92  | column -t 观察 TCPFastOpenPassive  TCPFastOpenPassiveFail 都是0

**Comment by xqzr** [comment]
```
net.ipv4.tcp_fastopen=3
net.ipv4.tcp_fastopen_blackhole_timeout_sec=0
```

**Comment by xqzr** [comment]
检查客户端 系统 TFO 参数
