### ISSUE TITLE
can't execute commands

### ISSUE THREAD

**Issue by mmdzov** [XTLS/Xray-core#1292]
When I run xray.exe, any command (example: **xray version** or **xray help**) goes to the next line when I press enter, and the command is not executed.

```
Xray 1.6.2 (Xray, Penetrates Everything.) Custom (go1.19.2 windows/amd64)
A unified platform for anti-censorship.   

2022/10/30 14:18:26 Using config from STDIN                              
2022/10/30 14:18:26 [Info] infra/conf/serial: Reading config: stdin:     


```

**Comment by cross-hello** [comment]
It is expected behavior. Running to this you should have two port opening if you type `netstat -ab|grep xray -A 3 |unique `:
![image](https://user-images.githubusercontent.com/42733664/198977688-da384fa3-7e5b-45c5-8f4e-1278a5eae6a3.png)
