### ISSUE TITLE
vless已经弃用了

### ISSUE THREAD

**Issue by punsloony** [XTLS/Xray-core#1293]
#[vless已被v2fly弃用](https://www.v2fly.org/v5/config/proxy/vless.html)，xray是不是也要弃用了🤔，当前中国大规模地封锁基于TLS的翻墙服务器 #1253 ，我该继续使用xray典型的vless tcp xtls，还是转而使用tuic、wireguard等基于UDP的协议捏？

**Comment by chika0801** [comment]
建议换hy tuic 不要用 tcp tls等tcp类的

**Comment by wanglongbiao** [comment]
> 我一直使用典型配置vless tcp xtls，三次被封后用回典型的vless tcp tls，使用接近一个月无事，无任何多余配置，仍然保持大流量使用习惯。改变的是使用设备的数量。手机坚决不连入。一切ok。

为啥不用手机就没事？是因为 armv8 的 aes 指纹吗？

**Comment by Smallthing** [comment]
> > 我一直使用典型配置vless tcp xtls，三次被封后用回典型的vless tcp tls，使用接近一个月无事，无任何多余配置，仍然保持大流量使用习惯。改变的是使用设备的数量。手机坚决不连入。一切ok。
> 
> 为啥不用手机就没事？是因为 armv8 的 aes 指纹吗？
手机上的app流量通透？

**Comment by yuhan6665** [comment]
感谢反馈，关于手机导致被封听到一些类似情况，有几个猜测
1. 手机上有很多人习惯开全局，而且后台应用都会产生流量，有很多会回国，所以最近推荐在服务端禁用 cn
2. 手机上会产生更多的 DNS over proxy 类型流量（可以改配置避免）
3. 处理器的问题？（可以试试 chrome os?）

**Comment by YR1044** [comment]
utls能否解决问题？

**Comment by AxIauk** [comment]
> utls能否解决问题？



> 感谢反馈，关于手机导致被封听到一些类似情况，有几个猜测
> 
> 1. 手机上有很多人习惯开全局，而且后台应用都会产生流量，有很多会回国，所以最近推荐在服务端禁用 cn
> 2. 手机上会产生更多的 DNS over proxy 类型流量（可以改配置避免）
> 3. 处理器的问题？（可以试试 chrome os?）

之前看到几个爆料，比较担心处理器问题和识别数量。所以针对这两点，在手机环境中做了三点变动：1，开启utls，2，使用IPV6服务器，3，服务器只给手机一个设备使用。
一直稳定。

**Comment by YR1044** [comment]
> > utls能否解决问题？
> 
> > 感谢反馈，关于手机导致被封听到一些类似情况，有几个猜测
> > 
> > 1. 手机上有很多人习惯开全局，而且后台应用都会产生流量，有很多会回国，所以最近推荐在服务端禁用 cn
> > 2. 手机上会产生更多的 DNS over proxy 类型流量（可以改配置避免）
> > 3. 处理器的问题？（可以试试 chrome os?）
> 
> 之前看到几个爆料，比较担心处理器问题和识别数量。所以针对这两点，在手机环境中做了三点变动：1，开启utls，2，使用IPV6服务器，3，服务器只给手机一个设备使用。 一直稳定。

请问，utls是只在客户端开启即可吗？服务端需要重新搭建吗

**Comment by showhand-eth** [comment]
亲测手机端被干得很严重
方案：vless tcp xtls，服务端已更改tls指纹。
梯子一：之前一直在手机端用，最近每天早上醒来就被封端口，更换端口后可以继续用。
梯子二：之前一直在PC端用，从来没有被封禁过，最近为了做封禁实验，只给移动端用，两天后封禁。
移动端配置：OnePlus 9 ColorOS v12.1，V2rayNG v1.7.23 (Xray-core v1.6.1)，后更换为SagerNet 0.8.1-rc02 SagerNet/v2ray-core v5.0.16，均会导致频繁封禁。

两个移动端均采用全局VPN但**分应用代理**，接入过联通网络/电信家宽，普通量级的流量。

可以确认移动端有问题。

**Comment by AxIauk** [comment]
> > > utls能否解决问题？
> > 
> > 
> > > 感谢反馈，关于手机导致被封听到一些类似情况，有几个猜测
> > > 
> > > 1. 手机上有很多人习惯开全局，而且后台应用都会产生流量，有很多会回国，所以最近推荐在服务端禁用 cn
> > > 2. 手机上会产生更多的 DNS over proxy 类型流量（可以改配置避免）
> > > 3. 处理器的问题？（可以试试 chrome os?）
> > 
> > 
> > 之前看到几个爆料，比较担心处理器问题和识别数量。所以针对这两点，在手机环境中做了三点变动：1，开启utls，2，使用IPV6服务器，3，服务器只给手机一个设备使用。 一直稳定。
> 
> 请问，utls是只在客户端开启即可吗？服务端需要重新搭建吗

xtls 不支持，服务器 tls不需要设置utls，手机端开启 utls

**Comment by yuhan6665** [comment]
有个想法，可以尝试把 VPN 模式关掉，使用仅代理模式，然后装一个 [Firefox nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix)  通过这个 [英文教程](https://mullvad.net/en/help/socks5-proxy/#get-started) 把 socks5 设置到127.0.0.1:10808
这种模式其它 app 比如 YouTube 就翻不了了，但是流量特征无限接近电脑（而且省电:）

**Comment by alirezaac** [comment]
well its started this week in iran too, i reproduced that tls blocking with armv8a, testet all things but using that cpu will get it blocked.

**Comment by wanglongbiao** [comment]
> 亲测手机端被干得很严重 方案：vless tcp xtls，服务端已更改tls指纹。 梯子一：之前一直在手机端用，最近每天早上醒来就被封端口，更换端口后可以继续用。 梯子二：之前一直在PC端用，从来没有被封禁过，最近为了做封禁实验，只给移动端用，两天后封禁。 移动端配置：OnePlus 9 ColorOS v12.1，V2rayNG v1.7.23 (Xray-core v1.6.1)，后更换为SagerNet 0.8.1-rc02 SagerNet/v2ray-core v5.0.16，均会导致频繁封禁。
> 
> 两个移动端均采用全局VPN但**分应用代理**，接入过联通网络/电信家宽，普通量级的流量。
> 
> 可以确认移动端有问题。

这样一来，是不是 arm 架构的软路由、旁路由也不能用了？

**Comment by KyonCN** [comment]
目前七八个服务器全部 vless-tcp-xtls，五六个人用。至今没有被封的。客户端除了一个国际版miui全部是iOS，openwrt和macOS。 utls都没有设置

**Comment by HSK077** [comment]
10月初被封的80,443端口到现在还没解封

**Comment by Biercenter** [comment]
听你们这么一说还真有可能是手机的锅，用了几年都没事，前几天出差一次，IP被Q了

**Comment by chika0801** [comment]
> > > 我一直使用典型配置vless tcp xtls，三次被封后用回典型的vless tcp tls，使用接近一个月无事，无任何多余配置，仍然保持大流量使用习惯。改变的是使用设备的数量。手机坚决不连入。一切ok。
> > 
> > 
> > 为啥不用手机就没事？是因为 armv8 的 aes 指纹吗？
> 
> 我目前**没有看到任何有关于 AES 指纹的 “论文及研究”** ，如果您或者提到 AES 指纹的人有的话，可以发出来大家讨论一下。 我认为，手机使用容易被屏蔽，可能因为是**手机上有部分软件暴露了代理服务器的出口地址**。

https://github.com/net4people/bbs/issues/129#issuecomment-1282034021

**Comment by yyuurrii34** [comment]
> 

so it's nothing to do with the utls fingerprint?the arm64-v8a cpu generates the figures for blocking?

**Comment by yyuurrii34** [comment]
> well its started this week in iran too, i reproduced that tls blocking with armv8a, testet all things but using that cpu will get it blocked.

so it's nothing to do with the utls fingerprint?the arm64-v8a cpu generates the figures for blocking?

**Comment by xiaopang0v0** [comment]
> > > > 我一直使用典型配置vless tcp xtls，三次被封后用回典型的vless tcp tls，使用接近一个月无事，无任何多余配置，仍然保持大流量使用习惯。改变的是使用设备的数量。手机坚决不连入。一切ok。
> > > 
> > > 
> > > 为啥不用手机就没事？是因为 armv8 的 aes 指纹吗？
> > 
> > 
> > 我目前**没有看到任何有关于 AES 指纹的 “论文及研究”** ，如果您或者提到 AES 指纹的人有的话，可以发出来大家讨论一下。 我认为，手机使用容易被屏蔽，可能因为是**手机上有部分软件暴露了代理服务器的出口地址**。
> 
> [net4people/bbs#129 (comment)](https://github.com/net4people/bbs/issues/129#issuecomment-1282034021)

事实上**只有他的一句话而已**，我在谷歌和中国知网以及谷歌学术上**没有搜索到任何有关于 AES 指纹的研究和报告**。

**我个人认为**，社区不能在没有确切证据的情况下，仅仅因为这么一个人的话，投入大量的精力去研究和验证这个虚无缥缈的 “指纹”。

ARM 设备被封锁，更应该检查是否在**设备中存在可能导致代理 IP 地址泄露的因素**。

**Comment by xiaopang0v0** [comment]
> > > > 我一直使用典型配置vless tcp xtls，三次被封后用回典型的vless tcp tls，使用接近一个月无事，无任何多余配置，仍然保持大流量使用习惯。改变的是使用设备的数量。手机坚决不连入。一切ok。
> > > 
> > > 
> > > 为啥不用手机就没事？是因为 armv8 的 aes 指纹吗？
> > 
> > 
> > 我目前**没有看到任何有关于 AES 指纹的 “论文及研究”** ，如果您或者提到 AES 指纹的人有的话，可以发出来大家讨论一下。 我认为，手机使用容易被屏蔽，可能因为是**手机上有部分软件暴露了代理服务器的出口地址**。
> 
> [net4people/bbs#129 (comment)](https://github.com/net4people/bbs/issues/129#issuecomment-1282034021)

神经网络模型无法区分来自 **AES-256-GCM** 或 **chacha20poly1305** 和未修改源的数据。
https://github.com/cross-hello/Neural-network-classify-aes-256-gcm-with-chacha20-poly1305

_Originally posted by @cross-hello in https://github.com/XTLS/Xray-core/discussions/1295#discussioncomment-4143877_

**Comment by Biercenter** [comment]
要是有些官方的流氓软件给你来个后台国内和国外IP检测，什么加密方式都没用，直接暴露。我在想是不是有这个可能。

**Comment by yoohooyoo** [comment]
> 要是有些官方的流氓软件给你来个后台国内和国外IP检测，什么加密方式都没用，直接暴露。我在想是不是有这个可能。

一直都有，某60就会报告。

**Comment by Biercenter** [comment]
某60我是没用，就担心miui这种系统或者系统app来个检查就比较致命了

Runer ***@***.***> 于2022年11月15日周二 18:16写道：

**Comment by patchescamerababy** [comment]
> > 要是有些官方的流氓软件给你来个后台国内和国外IP检测，什么加密方式都没用，直接暴露。我在想是不是有这个可能。
> 
> 一直都有，某60就会报告。

用某为和苹果，软路由，cdn和IPLC结合，半年以来目前主要的IP没有被封，可以考虑在vps上用warp

**Comment by Biercenter** [comment]
我原先用vless+ws+tls+网站伪装，用了几年都没事，就前几天出差一次被墙了。我有2个猜测，一个是大家说的终端超过5个？我算了下我的是4个终端，还有就是要么就是读取手机应用列表

**Comment by cross-hello** [comment]
What province is the destination and source? Is it possible for the 
different limitations of zone?

----------------------------------------

*From: *Biercenter ***@***.***>
*To: *XTLS/Xray-core ***@***.***>
*CC: *Nanyu ***@***.***>; Mention ***@***.***>
*Date: *Nov 15, 2022 12:48:10
*Subject: *Re: [XTLS/Xray-core] vless已经弃用了 (Issue #1293)

**Comment by qeqeq1** [comment]
使用vless ws tls，高位端口。本人使用几乎没出现任何问题。

但类似的配置，不同的高位端口，提供给我的同学使用，不超过一星期端口就被屏蔽，流量只有1G-2G的样子
有意思的事，尽管如此，我的IP未收到任何影响

**Comment by xieruiyin** [comment]
请问有什么好的翻墙方法吗，我的也是端口被封，到现在还没解封

**Comment by aptexd** [comment]
> 使用vless ws tls，高位端口。本人使用几乎没出现任何问题。
> 
> 但类似的配置，不同的高位端口，提供给我的同学使用，不超过一星期端口就被屏蔽，流量只有1G-2G的样子 有意思的事，尽管如此，我的IP未收到任何影响

我月初时候也这样，后来改了三次端口，ip 就被 ban 了

**Comment by ttym** [comment]
> 亲测手机端被干得很严重 方案：vless tcp xtls，服务端已更改tls指纹。 梯子一：之前一直在手机端用，最近每天早上醒来就被封端口，更换端口后可以继续用。 梯子二：之前一直在PC端用，从来没有被封禁过，最近为了做封禁实验，只给移动端用，两天后封禁。 移动端配置：OnePlus 9 ColorOS v12.1，V2rayNG v1.7.23 (Xray-core v1.6.1)，后更换为SagerNet 0.8.1-rc02 SagerNet/v2ray-core v5.0.16，均会导致频繁封禁。
> 
> 两个移动端均采用全局VPN但**分应用代理**，接入过联通网络/电信家宽，普通量级的流量。
> 
> 可以确认移动端有问题。

电信的问题，联通使用没问题，我只要一连电信网络，端口必然GG，目前只用联通网络已经坚挺了快半个月了

**Comment by bit-lang** [comment]
菊花和小米国内版手机，系统内置蔷检测代码。其他的品牌不了解

**Comment by wangyufeng2006** [comment]
@bit-lang 这个有来源吗

**Comment by qeqeq1** [comment]
> 菊花和小米国内版手机，系统内置蔷检测代码。其他的品牌不了解

这是无来源地随意猜测，是不可靠的。
我的手机运行MIUI13和MIUI12.5，两台手机均高强度fq两年（使用同一IP的服务器），除了xtls导致我的443被很快阻断外，未受到特殊影响
但是，我的同学使用的是vivo手机，这显然，如果内置检测的说法成立，应该是我使用的端口被屏蔽的更快。

**Comment by Biercenter** [comment]
> > 菊花和小米国内版手机，系统内置蔷检测代码。其他的品牌不了解
> 
> 这是无来源地随意猜测，是不可靠的。 我的手机运行MIUI13和MIUI12.5，两台手机均高强度fq两年（使用同一IP的服务器），除了xtls导致我的443被很快阻断外，未受到特殊影响 但是，我的同学使用的是vivo手机，这显然，如果内置检测的说法成立，应该是我使用的端口被屏蔽的更快。

在家都是路由器翻的，有4年了没封，这次出差一次用的miui13封了。我的猜测是被检测到了，要么就是特殊时段封BWG的IP段。

**Comment by cross-hello** [comment]
It is observed sometimes(most often happen near 12:00 UTC +8)android 
client will only allow date upload and not any data download( had 
disallow insecure option before).
The log of server is normal, except the log of client will show 
connection pass max time intervals. 


----------------------------------------

*From: *qeqeq1 ***@***.***>
*To: *XTLS/Xray-core ***@***.***>
*CC: *Nanyu ***@***.***>; Mention ***@***.***>
*Date: *Nov 24, 2022 10:22:25
*Subject: *Re: [XTLS/Xray-core] vless已经弃用了 (Issue #1293)

**Comment by cross-hello** [comment]
If you don't do any remedies, after a time the connection of client will 
back. Otherwise restart client will recover connection(client is behind a 
stable internet router).
So it is somewhat annoying.

----------------------------------------

*From: *Nanyu ***@***.***>
*To: *XTLS/Xray-core ***@***.***>
*CC: *Nanyu ***@***.***>; Your activity 
***@***.***>
*Date: *Nov 24, 2022 11:26:20
*Subject: *Re: [XTLS/Xray-core] vless已经弃用了 (Issue #1293)

**Comment by cross-hello** [comment]
At now we at least could conclude that isn't definite methods to detect 
VMESS/VLESS.
But it must have some characteristics residing in Android or iPhone which 
cause the problems.
What is normal internet traffic in Android if without proxy. Would it 
request Google from time to time and get a tcp rst?

----------------------------------------

*From: ***@***.***
*To: *XTLS/Xray-core 
***@***.***>
*Date: *Nov 24, 2022 11:26:04
*Subject: *Re: [XTLS/Xray-core] vless已经弃用了 (Issue #1293)

**Comment by cross-hello** [comment]
The log looks like this:
![Screenshot_20221124_230318](https://user-images.githubusercontent.com/42733664/203815427-4b14d7b3-3bf1-4bc6-b66b-973a99b51fde.jpg)

It is worth to mention although connection to server have broken as shown in log, other traffic flow to local country is not broken(radio real-time could continually play along the broken time period).

**Comment by yuhan6665** [comment]
@cross-hello what you describe sounds like 晚高峰丢包 :)

**Comment by bit-lang** [comment]
不是猜测。
是手机厂商的人告诉我的。你用旧款的不影响。
新款已经内置

**Comment by bit-lang** [comment]
> > 菊花和小米国内版手机，系统内置蔷检测代码。其他的品牌不了解
> 
> 
> 
> 这是无来源地随意猜测，是不可靠的。
> 
> 我的手机运行MIUI13和MIUI12.5，两台手机均高强度fq两年（使用同一IP的服务器），除了xtls导致我的443被很快阻断外，未受到特殊影响
> 
> 但是，我的同学使用的是vivo手机，这显然，如果内置检测的说法成立，应该是我使用的端口被屏蔽的更快。

不是猜测。手机厂商的人告诉我的。
你用旧款手机没影响。
新款手机内置

**Comment by Biercenter** [comment]
> > > 菊花和小米国内版手机，系统内置蔷检测代码。其他的品牌不了解
> > 
> > 
> > 这是无来源地随意猜测，是不可靠的。
> > 我的手机运行MIUI13和MIUI12.5，两台手机均高强度fq两年（使用同一IP的服务器），除了xtls导致我的443被很快阻断外，未受到特殊影响
> > 但是，我的同学使用的是vivo手机，这显然，如果内置检测的说法成立，应该是我使用的端口被屏蔽的更快。
> 
> 不是猜测。手机厂商的人告诉我的。 你用旧款手机没影响。 新款手机内置

这个可能性很大，我之前一直用的都是米10，偶尔出门用数据流量翻都没事。这次是双11刚买的红米K50至尊版，立马封了。对比以前和现在就是手机换了，其它操作都是一样的

**Comment by patchescamerababy** [comment]
> > > 菊花和小米国内版手机，系统内置蔷检测代码。其他的品牌不了解
> > 
> > 
> > 这是无来源地随意猜测，是不可靠的。
> > 我的手机运行MIUI13和MIUI12.5，两台手机均高强度fq两年（使用同一IP的服务器），除了xtls导致我的443被很快阻断外，未受到特殊影响
> > 但是，我的同学使用的是vivo手机，这显然，如果内置检测的说法成立，应该是我使用的端口被屏蔽的更快。
> 
> 不是猜测。手机厂商的人告诉我的。 你用旧款手机没影响。 新款手机内置

需要更多证据及细节，如具体手机型号和系统版本号
Need more evidence and details, such as specific phone model and system version number

**Comment by cross-hello** [comment]
We have uninstalled most of specific vendors softwares, including some 
may be used as backdoor via police.

----------------------------------------

*From: *patchescamerababy ***@***.***>
*To: *XTLS/Xray-core ***@***.***>
*CC: *Nanyu ***@***.***>; Mention ***@***.***>
*Date: *Nov 24, 2022 15:25:27
*Subject: *Re: [XTLS/Xray-core] vless已经弃用了 (Issue #1293)

**Comment by qeqeq1** [comment]
> > > 菊花和小米国内版手机，系统内置蔷检测代码。其他的品牌不了解
> > 
> > 
> > 这是无来源地随意猜测，是不可靠的。
> > 我的手机运行MIUI13和MIUI12.5，两台手机均高强度fq两年（使用同一IP的服务器），除了xtls导致我的443被很快阻断外，未受到特殊影响
> > 但是，我的同学使用的是vivo手机，这显然，如果内置检测的说法成立，应该是我使用的端口被屏蔽的更快。
> 
> 不是猜测。手机厂商的人告诉我的。 你用旧款手机没影响。 新款手机内置

本人用过四台小米设备
搭载MIUI11的K20；搭载MIUI12.5的K20PRO；搭载MIUI11—>12的mix2s；搭载MIUI13的K40S，这些设备上难以体验出差异。
由于我的老设备已被我停止更新且很少使用，需要更多证据证明类似信息。
我主力使用K40S，在这台手机上端口被封的概率仍然小于我的同学（使用vivo的）除非我们解释为vivo有更严厉的算法。
并且若是MIUI直接上报,那么审查设备可以100%判定该IP的异常流量，没有必要通过封禁端口进行封禁，直接封禁IP是更好的选择。
由于手机系统大版本更新、软件升级的同时，GFW审查设备、原理或者能力也在升级，形式变化下审查力度也在变化。
单纯依靠型号或是版本在两短时间内的结果判断是不可靠的。我们需要更多的控制变量，或者直接审查手机系统软件的数据包（是否上报了代理服务器的信息）。
我更倾向于，封禁端口的原因仅仅是GFW难以判断该流量具体情况，但对此有之怀疑，于是封禁端口。

**Comment by alirezaac** [comment]
well we thing you guys have the same problem we have with phones in [iran](https://github.com/net4people/bbs/issues/156)

**Comment by ttym** [comment]
> > > > 菊花和小米国内版手机，系统内置蔷检测代码。其他的品牌不了解
> > > 
> > > 
> > > 这是无来源地随意猜测，是不可靠的。
> > > 我的手机运行MIUI13和MIUI12.5，两台手机均高强度fq两年（使用同一IP的服务器），除了xtls导致我的443被很快阻断外，未受到特殊影响
> > > 但是，我的同学使用的是vivo手机，这显然，如果内置检测的说法成立，应该是我使用的端口被屏蔽的更快。
> > 
> > 
> > 不是猜测。手机厂商的人告诉我的。 你用旧款手机没影响。 新款手机内置
> 
> 这个可能性很大，我之前一直用的都是米10，偶尔出门用数据流量翻都没事。这次是双11刚买的红米K50至尊版，立马封了。对比以前和现在就是手机换了，其它操作都是一样的

你有没有考虑过是运营商在作怪？明确告诉你电信现在xtls 100%封端口，我用联通和移动的就正常，手机只要一连上电信的WiFi  最快两个小时，最迟一天，所以和设备是无关的，我现在只用联通的流量卡  基本上半个多月都正常了

**Comment by ttym** [comment]
> > > 菊花和小米国内版手机，系统内置蔷检测代码。其他的品牌不了解
> > 
> > 
> > 这是无来源地随意猜测，是不可靠的。
> > 我的手机运行MIUI13和MIUI12.5，两台手机均高强度fq两年（使用同一IP的服务器），除了xtls导致我的443被很快阻断外，未受到特殊影响
> > 但是，我的同学使用的是vivo手机，这显然，如果内置检测的说法成立，应该是我使用的端口被屏蔽的更快。
> 
> 不是猜测。手机厂商的人告诉我的。 你用旧款手机没影响。 新款手机内置

我就是米10U 用了快两年了，没有你说的问题，所以厂商监测这个猜测不靠谱，目前我亲身经历的就是电信网络的运营商会导致端口被封，可以排除设备原因了

**Comment by bit-lang** [comment]
> > > > 菊花和小米国内版手机，系统内置蔷检测代码。其他的品牌不了解
> 
> > > 
> 
> > > 
> 
> > > 这是无来源地随意猜测，是不可靠的。
> 
> > > 我的手机运行MIUI13和MIUI12.5，两台手机均高强度fq两年（使用同一IP的服务器），除了xtls导致我的443被很快阻断外，未受到特殊影响
> 
> > > 但是，我的同学使用的是vivo手机，这显然，如果内置检测的说法成立，应该是我使用的端口被屏蔽的更快。
> 
> > 
> 
> > 不是猜测。手机厂商的人告诉我的。 你用旧款手机没影响。 新款手机内置
> 
> 
> 
> 我就是米10U 用了快两年了，没有你说的问题，所以厂商监测这个猜测不靠谱，目前我亲身经历的就是电信网络的运营商会导致端口被封，可以排除设备原因了

用了2年算旧型号了吧。
厂商在新机器的系统底层内置外网的访问监测。
而且有没有可能，是软硬件结合的监测，所以旧机器升级新系统也不受影响

**Comment by binbooly** [comment]
翻墙组合：MT7621 的硬路由 + OpenWRT + VLESS + XTLS + TCP，未开启 uTLS，就是很常规很基础的配置，中国电信。全家人各种手机 PC 均翻墙。

已经快两年了都很稳定，但从今年国庆节期间第一次被封端口开始，截止目前两个月内已经被封了5次端口了。昨天又被封，已经把 XTLS 换成了 TLS，其它都没变，再观察一下。

总被封端口的配置：
----------------------
![1](https://user-images.githubusercontent.com/65035816/204995382-ad3c9468-8e52-4c76-8757-ded5c0514854.png)
----------------------
![2](https://user-images.githubusercontent.com/65035816/204995398-93e05afc-378a-44e4-ae8b-d74c1ce82d50.png)
----------------------
![3](https://user-images.githubusercontent.com/65035816/204995409-8233d55a-e924-41e1-8c6a-079e2567a258.png)

**Comment by WeiPopInc** [comment]
> 

我是用的红米X40刷PixelExperience系统，电脑和手机用起来，第二天也是照样被封

**Comment by cross-hello** [comment]
May you should use phone produced in other countries 🙄

----------------------------------------

*From: *WeiPopInc ***@***.***>
*To: *XTLS/Xray-core ***@***.***>
*CC: *Nanyu ***@***.***>; Mention ***@***.***>
*Date: *Dec 7, 2022 01:54:21
*Subject: *Re: [XTLS/Xray-core] vless已经弃用了 (Issue #1293)

**Comment by CXwudi** [comment]
也有人怀疑是手机客户端有特征被识别出来了
https://github.com/p4gefau1t/trojan-go/pull/464#issuecomment-1301561755

**Comment by VeganBirdie** [comment]
手机端被识别不应该是各种apps出卖吗,连ISP都不一定介入？网络硬件什么的不懂，不学这些不干这行，不过硬件后门什么的似乎不大可能，毕竟厂商要赚钱，没必要为了赵家的要求付出额外成本，而且很多手机在海外出口上市，被查出来就完蛋。一直用步步高“厂妹机”，装了googleplay所有软件都从google下载，除了少数必须不使用国产app，关闭几乎所有权限、信息提示弹窗。每个月跑几百G的视频音频流量常年无事。去年VPS被墙发生在手机端开着VPS使用淘宝后，以及在桌面端使用百度，开启猪场加速器的同时使用VPS浏览网页。
之前有新闻：某市区委书记被抓查获N多台矿机挖矿币值2亿，他怎么弄到那么多显卡？没准政府真的在使用AI提升GFW。今年一月中旬SS还能用，很顺畅；后来开始降速、丢包；现在完全连不上。应该是GFW升级在本地区实装了，换其他工具协议都不行。而且现在SSH登陆有更长的延迟，以前5秒验证，现在需要半分多钟；前几天IPV6秒登，今天开始IPV6也有延迟。

**Comment by bcegkmqs23** [comment]
> 并且若是MIUI直接上报,那么审查设备可以100%判定该IP的异常流量，没有必要通过封禁端口进行封禁，直接封禁IP是更好的选择。

对手是职业的、有组织的开发者，在需要隐蔽手段的时候用一用这种策略也不是很意外的事情。

还是需要其他的研究或论证路线。

**Comment by Mxptxz** [comment]
之前用trojan+xtls,一直很稳定,自己用和另一个朋友,上个星期给我亲人装了一个,先是被降速,然后封端口,最后直接IP被封,过程时间一共是两个周.我很怀疑他的手机,用的华为.也没有root,但是我奇怪的是,直到现在我的那台aws依然被限速,即便我换了IP,换了协议,换了端口,我不清楚这是怎么做到的.能够在我全部换了一遍的情况下,依然如此.

**Comment by Fangliding** [comment]
弃用(指拖到现在)
