### ISSUE TITLE
xtls-rprx-vision + grpc报错

### ISSUE THREAD

**Issue by Tsukimeizi** [XTLS/Xray-core#1297]
server:
`{
    "inbounds": [
        {
            "listen": "[::]",
            "port": 23333,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "XXXX",
                        "flow": "xtls-rprx-vision"
                    }
                ],
                "decryption": "none"
            },
            "sniffing": {
                "enabled": false
            },
            "streamSettings": {
                "network": "grpc",
                "grpcSettings": {
                    "serviceName": "XXXX"
                },
                "security": "tls",
                "tlsSettings": {
                    "serverName": "XXXX",
                    "rejectUnknownSni": true,
                    "certificates": [
                        {
                            "certificateFile": "XXXX.pem",
                            "keyFile": "XXXX.key"
                        }
                    ]
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "settings": {
                "domainStrategy": "UseIPv4"
            }
        }
    ]
}
`

client:

`{
    "inbounds": [
        {
            "port": "1080",
            "protocol": "socks",
            "settings": {
                "auth": "noauth",
                "udp": true
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "[XXXX]",
                        "port": 23333,
                        "users": [
                            {
                                "id": "XXXX",
                                "flow": "xtls-rprx-vision",
                                "encryption": "none"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "grpc",
                "grpcSettings": {
                    "serviceName": "XXXX"
                },
                "security": "tls",
                "tlsSettings": {
                    "serverName": "XXXX"
                }
            }
        }
    ]
}
`

启动客户端报错：
./xray run -c ./xray.json
Xray 1.6.2 (Xray, Penetrates Everything.) Custom (go1.19.2 darwin/arm64)
A unified platform for anti-censorship.
2022/10/31 16:33:46 [Info] infra/conf/serial: Reading config: ./xray.json
2022/10/31 16:33:46 [Warning] core: Xray 1.6.2 started
panic: interface conversion: stat.Connection is *cnc.connection, not *tls.Conn

goroutine 41 [running]:
github.com/xtls/xray-core/proxy/vless/outbound.(*Handler).Process(0x1400037a6c0, {0x102e3f1c0, 0x1400037a270}, 0x14000154120, {0x102e39360, 0x140002e1810})
	github.com/xtls/xray-core/proxy/vless/outbound/outbound.go:151 +0x1868
github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dispatch(0x14000254300?, {0x102e3f1c0, 0x1400037a270}, 0x14000154120)
	github.com/xtls/xray-core/app/proxyman/outbound/handler.go:147 +0x1f4
github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0x140003763c0, {0x102e3f1c0, 0x1400037a270?}, 0x14000154120, {{0x102e40ab0?, 0x1400003e094?}, 0x0?, 0x0?})
	github.com/xtls/xray-core/app/dispatcher/default.go:492 +0xbd0
created by github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch
	github.com/xtls/xray-core/app/dispatcher/default.go:302 +0x410

**Comment by chika0801** [comment]
现在vision流控只能是 vless tcp tls组合使用

**Comment by yuhan6665** [comment]
感谢反馈这个问题 后面会加一个警告 xtls 只能用 tcp domainsocket 这种底层传输
