### ISSUE TITLE
xray grpc 使用nginx: unix反代不成功

### ISSUE THREAD

**Issue by Cicedasay** [XTLS/Xray-core#1299]
`                  {
                      "alpn": "h2",
                      "dest": "/.../h2.sock",
                      "xver": 1
                  },
                  {
                      "dest": "/.../default.sock",
                      "xver": 1
                  },
                  {
                    "dest": 8080,
                    "xver": 1
                  },
===========================
        {
            "listen": "/.../grpc.sock",
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "xxxx-xxxx"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "grpc",
                "security": "none",
                "grpcSettings": {
                    "acceptProxyProtocol": true,
                    "serviceName": "xxx",
                }
            }
        },
=============================
nginx

server {
      listen unix:/.../default.sock proxy_protocol default_server;
      listen unix:/.../h2.sock proxy_protocol default_server http2;

      location /xxx {
          if ($request_method != "POST") {
             return 404;
          }
          client_max_body_size 0;
          client_body_timeout 1h;
          grpc_set_header Host $host;
          grpc_set_header X-Real-IP $remote_addr;
          grpc_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          grpc_socket_keepalive on;

          grpc_pass unix:/.../grpc.sock;
      }
    location / {
        proxy_pass http://www.xxx.com;
    }

**Comment by chika0801** [comment]
参考一下官方模板
https://github.com/XTLS/Xray-examples/tree/main/VLESS-GRPC

另外你最好是把你的nginx xray配置粘完整，格式一下，方便别人查年

**Comment by Cicedasay** [comment]
nginx监听8443就能用 开SSL就能用

**Comment by Cicedasay** [comment]
> 先参考一下官方模板 https://github.com/XTLS/Xray-examples/tree/main/VLESS-GRPC
> 
> 另外你最好是把你的nginx xray配置粘完整，格式一下，方便别人看

额额, 第一次发issues, 截取的部分

**Comment by Cicedasay** [comment]
> 先参考一下官方模板 https://github.com/XTLS/Xray-examples/tree/main/VLESS-GRPC
> 
> 另外你最好是把你的nginx xray配置粘完整，格式一下，方便别人看

非常感谢你, 问题解决了, 可能是我使用的域名已经有一条回落规则了,连接的时候换一个域名就解决了... 非常感谢你发送的官方模板,它对我也很有帮助. 谢谢你!

**Comment by yuhan6665** [comment]
closing as solved
