### ISSUE TITLE
启动时能印出基本讯息吗？

### ISSUE THREAD

**Issue by delphinuz** [XTLS/Xray-core#13]
像是local ip/port、remote ip/port，tls or xtls之类的，才知道目前的client<->server是使用tls或xtls，direct或origin。

另外能否socks5/http port共用，像gost一样，也省了安装http->socks5的proxy。

**Comment by rprx** [comment]
v2 的配置相对复杂，这样和输出整个配置文件就没太大区别了（或者把 inbound&outbound 转成 yaml/toml 再输出？

Socks5 & HTTP 端口复用需要改架构，目前 Xray 不倾向于这种修改，但新项目应该会同时支持两者

**Comment by delphinuz** [comment]
主要是配置xtls不等于实际就是tls，需要xray告之实际的连线方式，不然完全不知真正的连线方式是哪种。

**Comment by rprx** [comment]
> 
> 
> 主要是配置xtls不等于实际就是tls，需要xray告之实际的连线方式，不然完全不知真正的连线方式是哪种。

XTLS 是否生效是根据真实代理内容（是否为 TLS）来定的，每个连接都不同。

你可以设置临时环境变量 `XRAY_VLESS_XTLS_SHOW = true` 打开 XTLS 的 CLI 输出看看。

**Comment by vitaminx** [comment]
> > 主要是配置xtls不等于实际就是tls，需要xray告之实际的连线方式，不然完全不知真正的连线方式是哪种。
> 
> XTLS 是否生效是根据真实代理内容（是否为 TLS）来定的，每个连接都不同。
> 
> 你可以设置临时环境变量 `XRAY_VLESS_XTLS_SHOW = true` 打开 XTLS 的 CLI 输出看看。

这个参数我可以加载客户端的config里面么？
具体哪个位置
