### ISSUE TITLE
quic 流量不能通过chrome socks5 代理，那这部分流量会直连？

### ISSUE THREAD

**Issue by GeorgeRudd** [XTLS/Xray-core#1301]
使用场景：
 win11 chrome106 chrome://flags/#enable-quic 保持默认 default，默认实际上就是 enabled
chrome 安装了 Proxy SwitchyOmega 插件 代理服务器设置socks5 127.0.0.1:10808 运行着V2rayN（非系统代理）

现在访问 https://quic.nginx.org/ 显示并没有使用 quic，是因为quic 流量不能通过chrome socks5 代理？是直连？如果直连，是不是就会被 GFW 知道要访问网址？

以上都是我看完 https://halfrost.com/quic_start/ 这篇文章之后的猜测，如果有地方说错请包涵

**Comment by YongChingShieh** [comment]
我的认为是  本地---socket5(v2rayN客户端)---quic(v2ray服务端)  所以感觉依然是socks5代理 就像我用tuic代理一样

**Comment by chika0801** [comment]
未被代理的quic流量是直连吗？
应该是走http还是http2

不推荐用quic，原因大概是代理协议对quic没加速效果（可能更慢）

你可看看 https://github.com/HyNetwork/hysteria/wiki/%E5%85%B3%E4%BA%8E-HTTP3

所以不用折腾quic流量了

**Comment by SakuraSakuraSakuraChan** [comment]
就算socks5支持UDP，Chrome也不会发起QUIC连接，就和系统代理是一样的，想出现QUIC请使用透明代理/Tun

**Comment by SakuraSakuraSakuraChan** [comment]
> > 就算socks5支持UDP，Chrome也不会发起QUIC连接，就和系统代理是一样的，想出现QUIC请使用透明代理/Tun
> 
> 也就是说只要设置了127.0.0.1这种系统代理就不会发起quic连接？为啥呢

Chrome是这么设定的，原因就不知道了。
