### ISSUE TITLE
关于重复DNS解析

### ISSUE THREAD

**Issue by First-Dream** [XTLS/Xray-core#1302]
### 什么是重复DNS解析
某个域名在首次访问（即不存在缓存）时，建立连接之前需要解析多次。Xray支持FakeDNS为透明代理省去首次访问的一次域名解析，但实际测试发现，重复解析在Xray中仍然存在，且不局限于透明代理。
### 流量探测和路由
大多数应用直接将域名封装在入站连接中，Xray可以直接获取域名。对于没有封装域名的入站连接，Xray通过流量探测获取域名。
若路由策略设置为非`AsIs`，Xray可能在路由过程中解析域名，但出站连接仍然封装域名，服务端需要重复解析域名才能建立连接。
流量探测可以设置`routeOnly`让Xray在出站连接封装原始IP，但对于直接封装域名的入站连接，Xray始终在出站连接封装域名。
Xray文档中提到

> 在能保证 被代理连接能得到正确的 DNS 解析 时，使用 routeOnly 且开启 destOverride 的同时，将路由匹配策略 domainStrategy 设置为 AsIs 即可实现全程无 DNS 解析进行域名及 IP 分流。此时遇到 IP 规则匹配时使用的 IP 为域名原始 IP。

此解决方案的局限性是直接封装域名的入站连接无法使用IP分流，需要前置代理解析域名，可能不适合非透明代理环境。
### FakeDNS
FakeDNS伪造DNS应答并建立映射关系，流量探测通过映射关系将FakeIP还原为域名。
显然`routeOnly`选项对FakeDNS无效，FakeIP必须还原为域名，即使在路由过程中解析域名，Xray仍然在出站连接封装域名。
### 测试方法
由于本人代理服务器始终有猪使用，不方便截取日志，故暂时只放出测试方法。

1. 服务端与客户端均设置`dnsLog`启用域名解析日志
2. 客户端使用v2rayNG自定义配置模拟透明代理+FakeDNS环境，使用`curl http://github.com`建立连接
3. 客户端使用`curl -x socks5h://127.0.0.1:2080 http://github.com`模拟封装域名的连接，使用`curl -x socks5://127.0.0.1:2080 http://github.com`模拟封装IP的连接
4. 修改Xray配置文件的`domainStrategy` `routeOnly`等选项，执行curl命令，观察客户端与服务端是否同时出现`DOH//1.1.1.1 got answer` `DOH//1.1.1.1 cache HIT`（示例）等域名解析日志

### 出站封装IP可能导致的问题
大多数用户只有一个出站代理，境外流量（包括解析境外域名的DNS）会被路由到唯一的代理服务器。若用户配置了多个不同国家地区的出站代理，可能导致CDN解析不正确降低访问速度，因此建议将出站封装IP设为可选功能以适应更多环境。

**Comment by First-Dream** [comment]
> 你写的东西我没太看懂。你看看这个能不能解决你的问题 [#1161 (comment)](https://github.com/XTLS/Xray-core/issues/1161#issuecomment-1199703568)

可以作为临时解决方案，但会降低性能 ~~套娃是不好的~~

**Comment by yuhan6665** [comment]
我个人推荐尽量减少客户端dns（减少泄露和 dns over proxy 的时间）服务端做一次 DNS 无伤大雅（速度很快且可以找到最好的目标服务CDN，减少代理反而跑回国的烦恼）

**Comment by ExtremeIce-Gai** [comment]
做了一遍测试，
v2rayNG关掉流量探测，asis，仅代理，adguard使用DOH（当然是小众的，境内外自动分流），不会重复解析，全是IP
V2rayN关掉流量探测 asis DNS设置出站改为useIP，也是看不到域名了
另一运营商的软路由 clash meta核关掉流量探测也可以达成只有IP的结果，但是分流转会域名什么的暂无从考究。
总结一下，如果完全信任目前使用的DOH服务器可以直接解析成ip 不探测域名，避免不必要的二次解析
fakeip因为始终没用，无法测试。

**Comment by Fangliding** [comment]
主要看配置怎么写的
