### ISSUE TITLE
请教如何修改本地出口ip

### ISSUE THREAD

**Issue by denwork** [XTLS/Xray-core#1303]
目前我服务器上有多个ip地址，我希望指定某个用户固定从一个本地ip地址去访问目的网站。并且可以通过api切换出口的ip地址，不知道应该怎么做？
如果api做不到，是否可以告诉我源代码中绑定本地ip地址作为访问目标网站的代码在什么地方？比如：
```
destAddrPort := fmt.Sprintf("%s:%d", addr, port)
	netAddr := &net.TCPAddr{IP: net.ParseIP("192.168.16.192")}
	d := net.Dialer{
		Timeout:   time.Second * 5,
		LocalAddr: netAddr}
	dest, err := d.Dial("tcp", destAddrPort)
```

我看了很久源码也没找到地方，也没有看到可以修改routing配置的api。希望能得到大神的帮助，非常感谢！

**Comment by yuhan6665** [comment]
你开多个 outbound 每个配置不同的 sendthrough 就行了
https://xtls.github.io/config/outbound.html#outboundobject
API 应该可以删掉已有的 outbound 然后加一个新的

**Comment by denwork** [comment]
> 你开多个 outbound 每个配置不同的 sendthrough 就行了 https://xtls.github.io/config/outbound.html#outboundobject API 应该可以删掉已有的 outbound 然后加一个新的

多谢，找到思路了。 inbound和routing都不用修改，只要写在配置文件中，切换时删除掉对应的outbound再根据当前的标签重新生成一个outbound规则。
