### ISSUE TITLE
小白的一些问题

### ISSUE THREAD

**Issue by Dictat111** [XTLS/Xray-core#1306]
v2ray,ssr这些东西看什么书比较好?学习一下

**Comment by TheValkyrja** [comment]
谷歌.jpg
可以用诸如翻墙/代理协议的关键词检索，找到类似简单介绍“主流代理协议”的blog，点进去再具体对每个条目本身以及其中所出现的看不懂的名词进行进一步检索。

**Comment by chika0801** [comment]
> v2ray,ssr这些东西看什么书比较好?学习一下

https://github.com/chika0801/Xray-examples#%E6%8E%A8%E8%8D%90%E6%96%87%E7%AB%A0

**Comment by HSK077** [comment]
小小白白话文
[https://xtls.github.io/Xray-docs-next/document/level-0/](url)

**Comment by yuhan6665** [comment]
Answered
