### ISSUE TITLE
How can I set request header  X-Forwarded-For 

### ISSUE THREAD

**Issue by jingslunt** [XTLS/Xray-core#1315]
怎么修改请求头 X-Forwarded-For

**Comment by lxhao61** [comment]
1、Nginx 反代 WebSocket（WS）才需要修改X-Forwarded-For。
[v2ray(vless\vmess+WS)+caddy\nginx](https://github.com/lxhao61/integrated-examples/tree/main/v2ray(vless%5Cvmess%2BWS)%2Bcaddy%5Cnginx)
2、Caddy 或 Nginx  反代 gRPC 是修改X-Real-IP。
[v2ray(vless\vmess+grpc)+caddy\nginx](https://github.com/lxhao61/integrated-examples/tree/main/v2ray(vless%5Cvmess%2Bgrpc)%2Bcaddy%5Cnginx)

**Comment by yuguanching** [comment]
如果我今天已經確定inbound時有抓到客戶端的source ip
那當我要做freedom 出站時,要怎麼讓這個source ip也一併往外傳遞呢？

**Comment by jingslunt** [comment]
> 1、Nginx 反代 WebSocket（WS）才需要修改 X-Forwarded-For。 [v2ray(vless\vmess+WS)+caddy\nginx](https://github.com/lxhao61/integrated-examples/tree/main/v2ray(vless%5Cvmess%2BWS)%2Bcaddy%5Cnginx) 2、Caddy 或 Nginx 反代 gRPC 是修改 X-Real-IP。 [v2ray(vless\vmess+grpc)+caddy\nginx](https://github.com/lxhao61/integrated-examples/tree/main/v2ray(vless%5Cvmess%2Bgrpc)%2Bcaddy%5Cnginx)

二者都修改了，测试请求httpbin.org/get 并没有获取到

**Comment by lxhao61** [comment]
> > 1、Nginx 反代 WebSocket（WS）才需要修改 X-Forwarded-For。 [v2ray(vless\vmess+WS)+caddy\nginx](https://github.com/lxhao61/integrated-examples/tree/main/v2ray(vless%5Cvmess%2BWS)%2Bcaddy%5Cnginx) 2、Caddy 或 Nginx 反代 gRPC 是修改 X-Real-IP。 [v2ray(vless\vmess+grpc)+caddy\nginx](https://github.com/lxhao61/integrated-examples/tree/main/v2ray(vless%5Cvmess%2Bgrpc)%2Bcaddy%5Cnginx)
> 
> 二者都修改了，测试请求httpbin.org/get 并没有获取到

给你参考的两示例是最简单反代应用（仅反代），若还有其它应用（回落/分流、SNI分流等），请参考其它对应示例。
