### ISSUE TITLE
xray配置文件config.json报错

### ISSUE THREAD

**Issue by FollowHeart007** [XTLS/Xray-core#132]
当我写好配置文件，然后用命令“systemctl start xray”启动xray时，xray启动失败，然后查看报错文件，显示第47行有一个无效的“：”，47行是出口outbounds的设置。这里的设置我是把作者rprx给出的设置文件原封不动的照抄过来的，并没有做出修改。所以我很困惑为什么会这里报错。下面附上报错截图和config.json配置截图。
![屏幕截图 2021-01-03 181605](https://user-images.githubusercontent.com/58877068/103476390-0d909100-4df0-11eb-81ad-2b849395bcc7.jpg)
![Inked屏幕截图 2021-01-03 181452_LI](https://user-images.githubusercontent.com/58877068/103476457-e25a7180-4df0-11eb-9238-494307453c25.jpg)
![Inked屏幕截图 2021-01-03 181509_LI](https://user-images.githubusercontent.com/58877068/103476458-e6868f00-4df0-11eb-937f-9d2812d8729b.jpg)

**Comment by NutterChen** [comment]
Please use copy and paste and translation of websites effectively

the line 47

**Comment by jiuqi9997** [comment]
@FollowHeart007 把46行的 } 改成 ] 试试

**Comment by FollowHeart007** [comment]
> @FollowHeart007 把46行的 , 去掉，46和47中间加一行 写 ]

是的，确实如此，非常感谢。

**Comment by FollowHeart007** [comment]
> @FollowHeart007 把46行的 , 去掉，46和47中间加一行 写 ]

我遇到了一个新的问题：我用certbot为我的服务器申请了证书和私钥，我把他们放在了/etc/letsencrypt/live/servername.com/文件夹下，但是xray报错说无法打开这些文件。我用ls -l命令查看这些文件，他们都是“777”权限，所以为什么会无法打开呢，下面附上报错截图
![屏幕截图 2021-01-03 213728](https://user-images.githubusercontent.com/58877068/103480015-ac2aeb00-4e0c-11eb-86e8-d9284b693c5a.jpg)
![屏幕截图 2021-01-03 213601](https://user-images.githubusercontent.com/58877068/103480017-af25db80-4e0c-11eb-855d-be3e643a0bd9.jpg)
![屏幕截图 2021-01-03 213950](https://user-images.githubusercontent.com/58877068/103480033-ce246d80-4e0c-11eb-9393-61e5ab308624.jpg)

**Comment by jiuqi9997** [comment]
xray应该是用的nobody用户来读证书，此时需要证书目录+证书文件和私钥的访问权限。我猜是目录权限没给。我的做法是设置定时任务，将证书定时复制到nobody用户可读的目录并且设置文件权限

**Comment by AkinoKaede** [comment]
> > @FollowHeart007 把46行的 , 去掉，46和47中间加一行 写 ]
> 
> 我遇到了一个新的问题：我用certbot为我的服务器申请了证书和私钥，我把他们放在了/etc/letsencrypt/live/servername.com/文件夹下，但是xray报错说无法打开这些文件。我用ls -l命令查看这些文件，他们都是“777”权限，所以为什么会无法打开呢，下面附上报错截图
> ![屏幕截图 2021-01-03 213728](https://user-images.githubusercontent.com/58877068/103480015-ac2aeb00-4e0c-11eb-86e8-d9284b693c5a.jpg)
> ![屏幕截图 2021-01-03 213601](https://user-images.githubusercontent.com/58877068/103480017-af25db80-4e0c-11eb-855d-be3e643a0bd9.jpg)
> ![屏幕截图 2021-01-03 213950](https://user-images.githubusercontent.com/58877068/103480033-ce246d80-4e0c-11eb-9393-61e5ab308624.jpg)

参考 [https://github.com/v2fly/fhs-install-v2ray/wiki/Insufficient-permissions-when-using-certificates-zh-Hans-CN](https://github.com/v2fly/fhs-install-v2ray/wiki/Insufficient-permissions-when-using-certificates-zh-Hans-CN)

**Comment by rprx** [comment]
如上，或者你可以指定用 root 运行 Xray https://github.com/XTLS/Xray-install#advance
