### ISSUE TITLE
存在上级代理的透明代理不能转发所有流量

### ISSUE THREAD

**Issue by islercn** [XTLS/Xray-core#1321]
我有一个国内的上级https代理，我要在路由器上把它转成透明代理方便日常办公，本地和目标网络是都支持ipv6的

之前我试过[goproxy](https://github.com/snail007/goproxy)和[gost](https://github.com/go-gost/gost)，其中goproxy的透明代理支持ipv6但包转发存在[问题](https://github.com/snail007/goproxy/issues/480)，gost的[透明代理不支持ipv6](https://github.com/ginuerzh/gost/issues/827)但是包转发没有问题，所以我一直是goproxy转发ipv6，gost转发ipv4。

最近心血来潮试了试xray，用的1.6.3版本，配好之后发现xray的情况和goproxy一样，支持ipv6，但是部分软件无法正常使用。

inbounds设置如下：

    "inbounds": [
        {
            "port": 123,
            "protocol": "dokodemo-door",
            "sniffing": {
                "enabled": true,
                "destOverride": ["http", "tls"]
            },
            "settings": {
                "network": "tcp,udp",
                "followRedirect": true
            },
            "streamSettings": {
                "sockopt": {
                    "tproxy": "redirect"
                }
            }
        }
    ],

**Comment by Fangliding** [comment]
放个模板配置 没日志没ipt配置 在这让人算命呢(

**Comment by islercn** [comment]
> 模板配置 没日志没ipt配置 在这让人算命

IPT：
iptables -t nat -A work -p tcp -m set --match-set worklist dst -j REDIRECT --to-ports 123

日志（只记录到这么多，xxx.com和10.1.1.2对应同一台机器）：
透明代理日志：
2024/06/20 12:38:01 [Debug] [1299392023] proxy/dokodemo: processing connection from: 192.168.1.101:63925
2024/06/20 12:38:01 [Info] [1299392023] proxy/dokodemo: received request for 192.168.1.101:63925
2024/06/20 12:38:02 [Info] [1299392023] app/dispatcher: default route for tcp:10.1.1.2:2345

SOCKS代理日志：
2024/06/20 12:25:43 [Info] [1352458977] proxy/socks: TCP Connect request to tcp:xxx.com:2345
2024/06/20 12:25:43 [Info] [1352458977] app/dispatcher: default route for tcp:xxx.com:2345

[可以看](https://github.com/snail007/goproxy/issues/480)

有一个带密码的https代理，我把它转成了透明代理，用iptables转发。在测试中，上网、远程桌面什么的都没问题，但是用xshell之类的软件通过ssh连代理后的服务器，直接没反应（提示连接，然后就卡在那了），且：
1.kill掉xray，起ss的透明代理（其他都不变），秒连（意味着iptables转发没有问题）
2.用putty，秒连；用MobaXterm，连不上，和xshell一样（ss下可连）
3.将这个https代理用goproxy转成socks5，然后xshell下ssh设置这个socks5代理，秒连，但是xray连socks5也不行

抓包的数据上看，除了xshell的包长度超过1500，putty没超，别的地方似乎没有任何区别了。
