### ISSUE TITLE
xray相同配置，使用V2ray  ,电脑客户端能用，安卓手机端无法使用。

### ISSUE THREAD

**Issue by henhuo** [XTLS/Xray-core#1322]
**日志**
2022/11/10 13:46:47 127.0.0.1:49281 accepted //plw.szchengji-inc.com:443 [http -> proxy]
2022/11/10 13:46:47 127.0.0.1:49283 accepted //hpd.baidu.com:443 [http -> proxy]
2022/11/10 13:46:48 127.0.0.1:49285 accepted //xiaowangshen.com:443 [http -> proxy]
2022/11/10 13:46:59 127.0.0.1:49289 accepted //api.qrserver.com:443 [http -> proxy]
2022/11/10 13:46:59 127.0.0.1:49290 accepted //api.qrserver.com:443 [http -> proxy]
2022/11/10 13:47:01 127.0.0.1:49295 accepted //plw.szchengji-inc.com:443 [http -> proxy]
2022/11/10 13:47:07 127.0.0.1:49297 accepted http://notify3.note.youdao.com/pushserver3/client?ClientVer=61000010000&GUID=PC13072dc26ff7cbf2c&app=ydrive&cl=desktop&client_ver=61000010000&cto=60000&device_id=PC13072dc26ff7cbf2c&device_name=V3098&device_type=PC&did=PC13072dc26ff7cbf2c&keyfrom=pc&lp=1667054064149&os=Windows&os_ver=Windows%2010&pv=1&subvendor=&vendor=website&vendornew=website&ver=0 [http -> proxy]
2022/11/10 13:48:30 [Warning] [388033796] proxy/http: failed to read response from notify3.note.youdao.com > io: read/write on closed pipe

**配置信息如如下：**

[
    {
        "address":"toyclub.live",
        "flow":"xtls-rprx-direct",
        "host":"toyclub.live",
        "id":"ef4f52e0-5297-42b2-9235-2be3256caa45",
        "network":"tcp",
        "port":443,
        "protocol":"vless",
        "ps":"toyclub.live_ef4f52e0-5297-42b2-9235-2be3256caa45",
        "security":"none",
        "sni":"toyclub.live",
        "tls":"xtls"
    }
]

**具体问题：**
windows电脑使用v2ray N  可以连接网。安卓使用V2RAY NG  无法连接。是什么原因。

**Comment by FranzKafkaYu** [comment]
@henhuo server端证书是否使用了fullchain.cer,或者v2rayNG内针对节点开启allow insecure

**Comment by henhuo** [comment]
> @henhuoserver端证书是否使用了fullchain.cer，或者v2rayNG内部节点开启允许不安全

换了一个端口，就可以正常使用，使用443端口无法连网。

**Comment by yuhan6665** [comment]
closing as solved
