### ISSUE TITLE
[Bug] vision流控报错：SSL_ERROR_BAD_MAC_READ

### ISSUE THREAD

**Issue by htfcuddles** [XTLS/Xray-core#1323]
Xray v1.6.3 流控xtls-rprx-vision
部分网站（例如：https://dictionary.goo.ne.jp)无法建立SSL，错误：SSL_ERROR_BAD_MAC_READ

客户端日志如下：
```
2022/11/10 16:52:59 [Info] [1291770050] proxy/http: request to Method [CONNECT] Host [dictionary.goo.ne.jp:443] with URL [//dictionary.goo.ne.jp:443]
2022/11/10 16:52:59 [Info] [1291770050] app/dispatcher: sniffed domain: dictionary.goo.ne.jp
2022/11/10 16:52:59 [Info] [1291770050] app/dispatcher: taking detour [proxy] for [tcp:dictionary.goo.ne.jp:443]
2022/11/10 16:52:59 [Info] [1291770050] transport/internet/tcp: dialing TCP to tcp:xxx:xxx
2022/11/10 16:52:59 [Debug] transport/internet: dialing to tcp:xxx:xxx
2022/11/10 16:52:59 127.0.0.1:10698 accepted //dictionary.goo.ne.jp:443 [http -> proxy]
2022/11/10 16:53:00 [Info] [1291770050] proxy/vless/outbound: tunneling request to tcp:dictionary.goo.ne.jp:443 via xxx.com:xxx
2022/11/10 16:53:00 [Info] [1291770050] proxy/vless/encoding: XtlsFilterTls13 found tls client hello! 517
2022/11/10 16:53:00 [Info] [1291770050] proxy/vless/encoding: XtlsPadding 517 473 0
2022/11/10 16:53:00 [Info] [1291770050] proxy/vless/encoding: Xtls Unpadding new block0 16 content 4850 padding 0 0
2022/11/10 16:53:00 [Info] [1291770050] proxy/vless/encoding: XtlsFilterTls13 found tls 1.2! 1163
2022/11/10 16:53:00 [Info] [1291770050] proxy/vless/encoding: XtlsPadding 126 944 0
2022/11/10 16:53:00 [Info] [1291770050] proxy/vless/encoding: Xtls Unpadding new block0 0 content 51 padding 854 0
2022/11/10 16:53:00 [Info] [1291770050] proxy/vless/encoding: XtlsPadding 1539 0 1
2022/11/10 16:53:01 [Info] [1291770050] proxy/vless/encoding: Xtls Unpadding new block0 0 content 8192 padding 0 1
2022/11/10 16:53:01 [Info] [1291770050] app/proxyman/inbound: connection ends > proxy/http: connection ends > read tcp 127.0.0.1:10809->127.0.0.1:10698: wsarecv: An existing connection was forcibly closed by the remote host.
```

**Comment by cross-hello** [comment]
Expected as the same problem of here:
https://github.com/XTLS/Xray-core/issues/1313#issuecomment-1307139155

**Comment by yuhan6665** [comment]
8192 这个问题应该在 v1.6.4 修好了 如果遇到其它问题导致 TLS 握手失败 欢迎大家再发详细 issue 我们会继续改进

**Comment by htfcuddles** [comment]
更新：@yuhan6665 我测试了v1.6.4 还是同样的报错

客户端日志：
2022/11/14 10:50:40 [Info] [539251937] proxy/http: request to Method [CONNECT] Host [dictionary.goo.ne.jp:443] with URL [//dictionary.goo.ne.jp:443]
2022/11/14 10:50:40 [Info] [539251937] app/dispatcher: sniffed domain: dictionary.goo.ne.jp
2022/11/14 10:50:40 127.0.0.1:8322 accepted //dictionary.goo.ne.jp:443 [http -> proxy]
2022/11/14 10:50:40 [Info] [539251937] app/dispatcher: taking detour [proxy] for [tcp:dictionary.goo.ne.jp:443]
2022/11/14 10:50:40 [Info] [539251937] transport/internet/tcp: dialing TCP to tcp:xxx.xxx:xxx
2022/11/14 10:50:40 [Debug] transport/internet: dialing to tcp:xxx.xxx:8443
2022/11/14 10:50:40 [Info] [539251937] proxy/vless/outbound: tunneling request to tcp:dictionary.goo.ne.jp:443 via xxx.xxx:xxx
2022/11/14 10:50:40 [Info] [539251937] proxy/vless/encoding: XtlsFilterTls13 found tls client hello! 517
2022/11/14 10:50:40 [Info] [539251937] proxy/vless/encoding: XtlsPadding 517 712 0
2022/11/14 10:50:40 [Info] [539251937] proxy/vless/encoding: Xtls Unpadding new block0 16 content 4850 padding 0 0
2022/11/14 10:50:40 [Info] [539251937] proxy/vless/encoding: XtlsFilterTls13 found tls 1.2! 1163
2022/11/14 10:50:40 [Info] [539251937] proxy/vless/encoding: XtlsPadding 126 1239 0
2022/11/14 10:50:41 [Info] [539251937] proxy/vless/encoding: Xtls Unpadding new block0 0 content 51 padding 1120 0
2022/11/14 10:50:41 [Info] [539251937] proxy/vless/encoding: XtlsPadding 1539 0 1
2022/11/14 10:50:41 [Info] [539251937] proxy/vless/encoding: Xtls Unpadding new block0 0 content 8192 padding 0 1
2022/11/14 10:50:41 [Info] [539251937] app/proxyman/inbound: connection ends > proxy/http: connection ends > read tcp 127.0.0.1:10809->127.0.0.1:8322: wsarecv: An existing connection was forcibly closed by the remote host.
