### ISSUE TITLE
trojan正常可登录游戏，使用xray的trojan代理无法登录

### ISSUE THREAD

**Issue by feileb** [XTLS/Xray-core#133]
服务器和客户端之前是trojan1.16版本，今天试了xray 1.2.0版本，游戏无法登录
服务端和客户端确认都已经更新xray 1.2.0，尝试了xtls，tls都不行。
使用了中转服务器，所以在配置中指定了域名，游戏加速使用的是netch连本地的socks端口
不知道是不是配置问题，网页连接速度比trojan慢很多，且游戏登录直接卡死。
服务端配置：
```json
{
    "inbounds":[
        {
            "protocol": "trojan",
            "listen": "0.0.0.0",
            "port": 443,
            "settings": {
                "clients": [
                    {
                        "password": "password",
                        "email": "default@trojan"
                    }
                ],
                "fallbacks": [
                    {
                        "dest": 8080
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "alpn": [
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "/var/www/ssl/nobody/fullchain.pem",
                            "keyFile": "/var/www/ssl/nobody/privkey.pem"
                        }
                    ]
                }
            }
        }
    ],
    "outbounds":[
        {
            "protocol": "freedom"
        }
    ]
}
```
客户端配置：
```json
{
    "inbounds": [
        {
            "listen": "127.0.0.1",
            "port": 1080,
            "protocol": "socks",
            "settings": {
                "udp": true
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "trojan",
            "settings": {
                "servers": [
                    {
                        "address": "1.1.1.1",
                        "port": 20000,
                        "password": "password"
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "alpn": [
                        "http/1.1"
                    ],
                    "serverName": "domain",
                    "allowInsecureCiphers": false,
                    "allowInsecure": false
                }
            }
        }        
    ]
}

```

**Comment by feileb** [comment]
trojan和xray都是使用命令行直接运行并监听socks5 1080端口，netch连接1080端口代理游戏。
原trojan服务端配置：
```json
{
    "run_type": "server",
    "local_addr": "0.0.0.0",
    "local_port": 443,
    "remote_addr": "127.0.0.1",
    "remote_port": 8080,
    "password": [
        "password"
    ],
    "log_level": 1,
    "ssl": {
        "cert": "/var/www/ssl/nobody/fullchain.pem",
        "key": "/var/www/ssl/nobody/privkey.pem",
        "key_password": "",
        "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384",
        "cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
        "prefer_server_cipher": true,
        "alpn": [
            "http/1.1"
        ],
        "alpn_port_override": {
            "h2": 81
        },
        "reuse_session": true,
        "session_ticket": false,
        "session_timeout": 600,
        "plain_http_response": "",
        "curves": "",
        "dhparam": ""
    },
    "tcp": {
        "prefer_ipv4": false,
        "no_delay": true,
        "keep_alive": true,
        "reuse_port": false,
        "fast_open": false,
        "fast_open_qlen": 20
    },
    "mysql": {
        "enabled": false,
        "server_addr": "127.0.0.1",
        "server_port": 3306,
        "database": "trojan",
        "username": "trojan",
        "password": "",
        "key": "",
        "cert": "",
        "ca": ""
    }
}

```
trojan客户端配置:
```json
{
    "run_type": "client",
    "local_addr": "127.0.0.1",
    "local_port": 1080,
    "remote_addr": "1.1.1.1",
    "remote_port": 20000,
    "password": [
        "password"
    ],
    "log_level": 1,
    "ssl": {
        "verify": true,
        "verify_hostname": true,
        "cert": "",
        "cipher_tls13":"TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
        "sni": "domain",
        "alpn": [
            "h2",
            "http/1.1"
        ],
        "reuse_session": true,
        "session_ticket": false,
        "curves": ""
    },
    "tcp": {
        "no_delay": true,
        "keep_alive": true,
        "fast_open": false,
        "fast_open_qlen": 20
    }
}

```

**Comment by feileb** [comment]
我以前也用过vmess和vless，这两个登录游戏没问题，只是切换账号会掉线，不确定是什么问题，只有trojan可以比较完美的代理。
最近看到xray实现了udp fullcone，想试试xtls+trojan。

**Comment by rprx** [comment]
NatTypeTester 3.3 检测是 FullCone 吗

**Comment by feileb** [comment]
下面是今天测试的结果，xray服务端和客户端(windows)都是1.2.0
# xray tls+trojan
## rfc5780
我记得以前测试出现过`mapping`和`filtering`都是`EndpointIndependent`的结果，但是今天测试未出现
今天多次测试，结果一致：
```
binding:Success
mapping:EndpointIndependent
filtering:AddressAndPortDependent
```
## rfc3489
第一次
`nat type:PortRestrictedCone`
此时连续测试，都是`fullcone`
如果等一会再测试，又恢复`PortRestrictedCone`

# trojan
## rfc5780
多次测试，结果一致
```
binding:Success
mapping:EndpointIndependent
filtering:AddressAndPortDependent
```
## rfc3489
多次测试，结果一致
`nat type:PortRestrictedCone`

**Comment by JimhHan** [comment]
@feileb 这个或许真的是xray的问题

**Comment by eMeab** [comment]
> 下面是今天测试的结果，xray服务端和客户端(windows)都是1.2.0
> 
> # xray tls+trojan
> ## rfc5780
> 我记得以前测试出现过`mapping`和`filtering`都是`EndpointIndependent`的结果，但是今天测试未出现
> 今天多次测试，结果一致：
> 
> ```
> binding:Success
> mapping:EndpointIndependent
> filtering:AddressAndPortDependent
> ```
> 
> ## rfc3489
> 第一次
> `nat type:PortRestrictedCone`
> 此时连续测试，都是`fullcone`
> 如果等一会再测试，又恢复`PortRestrictedCone`
> 
> # trojan
> ## rfc5780
> 多次测试，结果一致
> 
> ```
> binding:Success
> mapping:EndpointIndependent
> filtering:AddressAndPortDependent
> ```
> 
> ## rfc3489
> 多次测试，结果一致
> `nat type:PortRestrictedCone`

请确认落地服务器的防火墙是否放行UDP流量

**Comment by feileb** [comment]
监听端口的tcp和udp都是放行的，不过都经过了中转，
考虑中转有可能影响，可以用国内的vps测试fullcone，但是无法测试游戏登录

**Comment by eMeab** [comment]
> 监听端口的tcp和udp都是放行的，不过都经过了中转，
> 考虑中转有可能影响，可以用国内的vps测试fullcone，但是无法测试游戏登录

能否提供是什么游戏

**Comment by feileb** [comment]
> > 监听端口的tcp和udp都是放行的，不过都经过了中转，
> > 考虑中转有可能影响，可以用国内的vps测试fullcone，但是无法测试游戏登录
> 
> 能否提供是什么游戏

枫之谷，就是冒险岛的台服

**Comment by hwx929** [comment]
你把客户端版本换成1.14就可以了。
我也无法登陆游戏，我玩的游戏甚至不是走udp的，而是tcp的，用了1.2，测试一下，完美，fullcone，结果游戏进不去我以为维护了，结果一天过去了还是不行，就看隔壁贴子退回1.4，游戏就能进了。

这1.2感觉就是专门拿来测试显示fullcone的……没看到实际意义。

**Comment by rprx** [comment]
@hwx929 

> 这1.2感觉就是专门拿来测试显示fullcone的……没看到实际意义。

注意 issue 区是问题区，大部分人没问题

**Comment by hwx929** [comment]
> @hwx929
> 
> > 这1.2感觉就是专门拿来测试显示fullcone的……没看到实际意义。
> 
> 注意 issue 区是问题区，大部分人没问题
是问题区啊？所以我回答了别人的问题？你看他是不是也是用原版没问题用了新的1.2就跪了？

大部分人甚至不知道是有问题，比如我本人就以为服务器维护了，今天还登不了才觉得是不是服务器又更新了一波vpsip段了，都准备换个ip再说了？要不是我看到隔壁哪个google voice的哥们提了句1.14我甚至完全不会往1.2有问题方面考虑。

你看看是不是这样，浏览网页没问题，NatType测试没问题，什么都没问题，但是游戏进不去，这就是1.2的表现啊？
fullcone专用版？

**Comment by rprx** [comment]
@hwx929 

你有病吧？说了是问题区，就是出问题的才来看才来反应的，没问题的又不会来这里开 issue 说没问题

我建议你在 TG 里问一问多少人有问题

**Comment by mritd** [comment]
直接锁了就行了

**Comment by badO1a5A90** [comment]
> > @hwx929
> > > 这1.2感觉就是专门拿来测试显示fullcone的……没看到实际意义。
> > 
> > 
> > 注意 issue 区是问题区，大部分人没问题
> > 是问题区啊？所以我回答了别人的问题？你看他是不是也是用原版没问题用了新的1.2就跪了？
> 
> 大部分人甚至不知道是有问题，比如我本人就以为服务器维护了，今天还登不了才觉得是不是服务器又更新了一波vpsip段了，都准备换个ip再说了？要不是我看到隔壁哪个google voice的哥们提了句1.14我甚至完全不会往1.2有问题方面考虑。
> 
> 你看看是不是这样，浏览网页没问题，NatType测试没问题，什么都没问题，但是游戏进不去，这就是1.2的表现啊？
> fullcone专用版？

回复毫无对开发者的礼貌和尊重。
开发者不欠你什么，有问题可以问，请保持你的礼貌和尊重，不然不欢迎。

block

**Comment by badO1a5A90** [comment]
XTLS blocked hwx929 now

挂起来

**Comment by eMeab** [comment]
> > > 监听端口的tcp和udp都是放行的，不过都经过了中转，
> > > 考虑中转有可能影响，可以用国内的vps测试fullcone，但是无法测试游戏登录
> > 
> > 
> > 能否提供是什么游戏
> 
> 枫之谷，就是冒险岛的台服

据我所知登录大概率是不走UDP的 或许可以参考一下这个
https://github.com/XTLS/Xray-core/issues/129#issuecomment-754384105

**Comment by rprx** [comment]
Netch 直接新建 trojan 代理试试

目前没有其它 socks 入 + trojan 出 无法登录游戏的报告，若基本的网页连接都有问题，则一般是配置等问题，建议检查 DNS

**Comment by rprx** [comment]
如果问题仍然存在，请开新的 issue

**Comment by feileb** [comment]
我没说这个游戏跟udp有关系，以前vless和vmess在切换角色的时候大概率掉线，只是现在xray更新了trojan相关的就再试试
我提的这个这个问题更新这个版本以后，登录是ok的
https://github.com/XTLS/Xray-core/issues/127#issuecomment-756722763
后面如果有切换问题，我再提新issue

**Comment by rprx** [comment]
。。。应该早说游戏是 TCP 的，NAT 检测是 UDP 的，与 TCP 游戏无关

切换账号会掉线的话，倒是很像 https://github.com/XTLS/Xray-core/issues/129 的情况，难道说游戏的 TCP 有特殊操作？

**Comment by rprx** [comment]
@feileb 所以切换是没有问题吗？

**Comment by feileb** [comment]
> @feileb 所以切换是没有问题吗？

昨天试了一下，之前的登录问题已经解决了，但是切换好像还是会掉线，和之前vmess、vless的表现差不多
等下周我专门测试一下，把日志整理下再发出来
