### ISSUE TITLE
xray 可以接收到來源ip, 但找不到方法可以在出站時傳遞出去

### ISSUE THREAD

**Issue by yuguanching** [XTLS/Xray-core#1330]
### 客戶端配置：
```
{
  "log": {
    "loglevel": "debug"
  },
  "inbounds": [{
      "port": "1080",
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true
      }
    },
    {
      "tag": "httpEntrance_proxy",
      "port": "1088",
      "protocol": "http",
      "settings": {}
    }
  ],
  "outbounds": [

    {
      "tag": "myProxy",
      "protocol": "vless",
      "settings": {
        "vnext": [{
          "address": "xxx.xxx.xxx",
          "port": 443,
          "users": [{
            "id": "xxxxxxxxxxxxx",
            "encryption": "none",
            "level": 0
          }]
        }]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "wsSettings": {
          "path": "/xx-ray"
        },
        "tlsSettings": {
          "serverName": "xxx.xxx.xxx"
        },
        "sockopt": {
          "domainStrategy": "UseIP"
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "blocked",
      "protocol": "blackhole",
      "settings": {}
    }
  ],
  "dns": {
    "servers": [{
        "address": "https+local://xxx.xxx.xxx.xxx/dns-query",
        "domains": [
          "xxx.xxx.xxx"
        ]
      },
      "1.1.1.1",
      "8.8.8.8"
    ]
  },
  "routing": {
    "rules": [{
        "type": "field",
        "domain": ["geosite:category-ads-all"],
        "outboundTag": "blocked"
      },
      {
        "type": "field",
        "inboundTag": ["httpEntrance_direct"],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "domain": [
          "geosite:cn",
          "mozilla.com",
          "mozilla.net",
          "google.com"
        ],
        "outboundTag": "direct"
      }
    ],
    "domainStrategy": "IPOnDemand"
  }
}
```

### 服務端配置：
```
{
  "log": {
    "loglevel": "debug",
    "access": "",
    "error": ""
  },
  "inbounds": [
    {
      "tag": "xx-inbound",
      "listen": "0.0.0.0",
      "port": 5885,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "xxxxxxxxxxxxx"
          }
        ],
        "decryption": "none",
        "fallbacks":[
          {
            "dest": 8080
          },
          {
            "path": "/xx-ray",
            "dest": 5886,
            "xver": 1
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "none",
        "tlsSettings": {
          "minVersion": "1.3",
          "alpn": [
            "http/1.1"
          ],
          "certificates": [
            {
              "certificateFile": "/etc/xray/creds/tls.crt",
              "keyFile": "/etc/xray/creds/tls.key"
            }
          ]
        }
      }
    },
    {
      "tag": "xx-ws-inbound",
      "port": 5886,
      "listen": "127.0.0.1",
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "19eb2f48-0bf9-4426-8495-5b379e98a698",
            "level": 0,
            "email": "jerry@szTest.org"
          }
        ],
        "decryption": "none",
        "fallbacks":[
          {
            "dest": "8080"
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "none",
        "wsSettings": {
          "acceptProxyProtocol": true,
          "path": "/xx-ray"
        }
      }
    }
  ],
  "outbounds": [
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
      }
    },
    {
      "tag": "blocked",
      "protocol": "blackhole",
      "settings": {}
    }
  ],
  "routing":{
    "domainStrategy":"IPOnDemand",
    "rules":[{
      "type": "field",
      "inboundTag": ["xx-inbound","xx-ws-inbound"],
      "outboundTag": "direct"
    }]
  }
}

```

以下說明

整個流程是在本機端把客戶端xray架起來運作後
監聽到流量並用vless協議包起來後
透過自建的dns服務解析到域名ip
之後打到對應的xray服務端(走的是ws的傳輸模式)
初步入站驗證過後
走freedom出站直連

以上流程對應的配置中,敏感資訊已用xxx屏蔽掉

結果上來說路線整個是通的
可以順暢科學上網
但有個需求目前無法完成
我希望能把客戶端的來源ip
一路傳到最後呼叫的目的地

但目前觀察到的現象是
xray inbound可以接收到來源ip(透過觀察log得知)
但目前所有的outbound 協議都找不到對應的設定來讓source ip 可以繼續往下傳

目前我有看到唯一可以讓ip往下傳的只有fallback回落到nginx 時
有設定xver : 1 ,也就是有設定proxy protocol時可以做到
但正常出站的流量我目前找不到方法或者開關

而在這樣的情境下
最終目標處收到的ip
都是xray 服務端這個節點的ip(以我的服務端來說是架在雲上,所以被接收到的便是雲服務對外的NAT IP)

以上說明
再煩請大神們解惑

**Comment by zxbiao** [comment]
不知道能不能让你明白，或许个别是有误的。
大部分科学上网都是拿节点的ip对解密后流量作类似NAT的地址翻译去转发流量，请求目标网站的从而绕过审查，不可能将客户端的IP直接透传到目标网络。根据路由协议的概念，只有路由转发才能直接将客户端的IP送达，而这个又会受防火墙所监控。或双端的程序做特殊配置（码代码）才能透传客户端真实IP，例如nginx/caddy之类或支持proxy protocol（HAProxy）的反代服务。

**Comment by azzvx** [comment]
`streamSettings`的`tcpSettings`，`httpSettings`以及`sockopt`项目里面有`acceptProxyProtocol`选项，应该是用于传递真实IP的。
具体如何用没用过不太清楚。应该有涉及到反向代理。

**Comment by yuguanching** [comment]
> 

有的
關於acceptProxyProtocol
官方文件裡面很多地方都有提到
我最早看到是在webSocket那邊

但無論是出現在哪裡
它的說明都有提到一點：
“僅適用於inbound”
也就是說 它只能滿足於「接收」客端IP
這一點也確實有效
我的vless+ws+tls 在inbound的log都有看到客端ip

但涉及到outbound要把流量送出去的時候
則找不到門路
我也有頭鐵直接把acceptProxyProtocol直接在outbound設定
但沒有作用

**Comment by yuguanching** [comment]
> 不知道能不能让你明白，或许个别是有误的。 大部分科学上网都是拿节点的ip对解密后流量作类似NAT的地址翻译去转发流量，请求目标网站的从而绕过审查，不可能将客户端的IP直接透传到目标网络。根据路由协议的概念，只有路由转发才能直接将客户端的IP送达，而这个又会受防火墙所监控。或双端的程序做特殊配置（码代码）才能透传客户端真实IP，例如nginx/caddy之类或支持proxy protocol（HAProxy）的反代服务。
> 
> 就像家里的宽带一样，假定你内网地址是192.168.1.1，以下简称为a。出口网口（宽带拨号后）的地址是172.16.25.25，以下简称为b。目标地址是10.0.35.35，以下简称为c。 当a访问c时，c一般情况下获取到的客户端地址是b（NAT网关）。 但当b和c同时做了特殊配置（haproxy），就能把a的地址正确地传给c。


感謝大大講解
對於科學上網的初衷我能理解
一般來說應是要隱藏客端的ip才能達到保護效果

今天是想透過Xray的優秀機制來建通道並架設服務
由於我們的服務會需要客端ip來進行分析
所以才會提出這個情境實現的可能性
因為我這邊純粹測試nginx確實可以做到真實ip的傳遞
那XRay也有涉及部份反代的功能
ip接收與發送兩個動作中
接收已經有做到了
那照理說發送出去應該也不會太困難才對

**Comment by yuguanching** [comment]
> 不知道能不能让你明白，或许个别是有误的。 大部分科学上网都是拿节点的ip对解密后流量作类似NAT的地址翻译去转发流量，请求目标网站的从而绕过审查，不可能将客户端的IP直接透传到目标网络。根据路由协议的概念，只有路由转发才能直接将客户端的IP送达，而这个又会受防火墙所监控。或双端的程序做特殊配置（码代码）才能透传客户端真实IP，例如nginx/caddy之类或支持proxy protocol（HAProxy）的反代服务。
> 
> 就像家里的宽带一样，假定你内网地址是192.168.1.1，以下简称为a。出口网口（宽带拨号后）的地址是172.16.25.25，以下简称为b。目标地址是10.0.35.35，以下简称为c。 当a访问c时，c一般情况下获取到的客户端地址是b（NAT网关）。 但当b和c同时做了特殊配置（haproxy），就能把a的地址正确地传给c。

另外根據您的說明
我有先嘗試過一個做法
但目前是失敗的
想請問一下原因

基於您說的
目前可能只有nginx/caddy等反代服務可以傳遞真實ip
所以我有嘗試將outbound設定成freedom (配合redirect)或是 http
在設定address時
把流量導到127.0.0.1:8081
也就是本機端的nginx服務
預期nginx可以作為到目標網址前的中轉
做一些ip傳遞的處理
但實作的結果
nginx那邊都可以收到流量
但似乎都沒有辦法正常解析 伴隨的是400 bad request

故我想問的是
我這一通操作
技術上來說是可行的嗎？

**Comment by zxbiao** [comment]
> > 不知道能不能让你明白，或许个别是有误的。 大部分科学上网都是拿节点的ip对解密后流量作类似NAT的地址翻译去转发流量，请求目标网站的从而绕过审查，不可能将客户端的IP直接透传到目标网络。根据路由协议的概念，只有路由转发才能直接将客户端的IP送达，而这个又会受防火墙所监控。或双端的程序做特殊配置（码代码）才能透传客户端真实IP，例如nginx/caddy之类或支持proxy protocol（HAProxy）的反代服务。
> > 就像家里的宽带一样，假定你内网地址是192.168.1.1，以下简称为a。出口网口（宽带拨号后）的地址是172.16.25.25，以下简称为b。目标地址是10.0.35.35，以下简称为c。 当a访问c时，c一般情况下获取到的客户端地址是b（NAT网关）。 但当b和c同时做了特殊配置（haproxy），就能把a的地址正确地传给c。
> 
> 另外根據您的說明 我有先嘗試過一個做法 但目前是失敗的 想請問一下原因
> 
> 基於您說的 目前可能只有nginx/caddy等反代服務可以傳遞真實ip 所以我有嘗試將outbound設定成freedom (配合redirect)或是 http 在設定address時 把流量導到127.0.0.1:8081 也就是本機端的nginx服務 預期nginx可以作為到目標網址前的中轉 做一些ip傳遞的處理 但實作的結果 nginx那邊都可以收到流量 但似乎都沒有辦法正常解析 伴隨的是400 bad request
> 
> 故我想問的是 我這一通操作 技術上來說是可行的嗎？

从技术上来说是可行的，但配置会很复杂。

`客户端真实IP(a)->网关(b)->科学上网节点(c)[xray fallbacks，需要开启PROXY protocol]->nginx(c)->nginx再反代后端服务器(d)`
这样后端d就能看到b的真实IP地址，需要xray fallbacks正确配置和nginx的启用传递真实IP。
但如果是xray非回落的数据包就会被xray所处理，这样会导致后端d取得的是c的ip
优点：xray做前端能搞xtls-whatever
缺点：xray fallbacks配置复杂，特别是要正确回落时，nginx反代时可能会出现莫名奇怪的古怪问题。

`客户端真实IP(a)->网关(b)->nginx(c)分流->nginx再反代后端服务器(d)
                                                                  ->xray科学上网`
这种就能通过nginx的来反代后端服务器，从而将b的真实IP传递到d，而科学上网的流量就直接交给xray来处理。
优点：配置简单多了，不用搞xray fallbacks。
缺点：xray做后端就不能搞xtls-whatever了

**Comment by penggongkui** [comment]
借楼请教一个问题，通过freedom传出去的流量有可能保持原来的ipv6地址吗？应该就是ip forward ，当前测试curl 6.ipw.cn 返回的似乎是xray所在机器的地址。

**Comment by Fangliding** [comment]
> 借楼请教一个问题，通过freedom传出去的流量有可能保持原来的ipv6地址吗？应该就是ip forward ，当前测试curl 6.ipw.cn 返回的似乎是xray所在机器的地址。

不能
