### ISSUE TITLE
vision流控一直连接r3.o.lencr.org

### ISSUE THREAD

**Issue by tdjnodj** [XTLS/Xray-core#1331]
@yuhan6665

现象：使用vison时日志里显示一直连接r3.o.lencr.org，即使在网络空闲时也如此。当网速达到一定大小时，CPU会异常升高。
环境：macos X 10.14
           xray-1.6.3
复现：使用其他协议、流控没有此现象

日志：
```
 tcp:127.0.0.1:60330 accepted tcp:r3.o.lencr.org:80 [proxy]
```

此外，使用本流控时首次打开的每一个域名都要过很久才能加载出来，而别的协议则没有这么高的首次打开延迟。并且重启xray会重置这个超长加载时间。

**Comment by chika0801** [comment]
log建议开成debug，取复现现象时的部分。如果有服务器端的debug日志更能帮到开发者分析问题。

**Comment by 973kt** [comment]
https://howtoremove.guide/r3-o-lencr-org/
侬中毒了

**Comment by chika0801** [comment]
> https://howtoremove.guide/r3-o-lencr-org/ 侬中毒了

高手呀

**Comment by cross-hello** [comment]
🤭

----------------------------------------

*From: *chika0801 ***@***.***>
*To: *XTLS/Xray-core ***@***.***>
*CC: *Subscribed ***@***.***>
*Date: *Nov 12, 2022 15:45:10
*Subject: *Re: [XTLS/Xray-core] 
vision流控一直连接r3.o.lencr.org[https://vision流控一直连接r3.o.lencr.org] (Issue 
#1331)

**Comment by yuhan6665** [comment]
Close as solved

**Comment by tdjnodj** [comment]
> 解决后关闭

我使用自编译的的内核就不会有上述现象，是workflow被篡改了吗？

**Comment by tdjnodj** [comment]
> https://howtoremove.guide/r3-o-lencr-org/ 侬中毒了

使用别的内核、别的协议时不会有这些日志，CPU占用也没有飙升。我用了自己编译的xray内核也是这个现象，只是减轻了一点而已。

**Comment by 973kt** [comment]
> > https://howtoremove.guide/r3-o-lencr-org/ 侬中毒了
> 
> 使用别的内核、别的协议时不会有这些日志，CPU占用也没有飙升。我用了自己编译的xray内核也是这个现象，只是减轻了一点而已。

误会了，我结论下得武断了，不一定是malware，给你造成困扰十分抱歉。
我查了我的日志里也有“ accepted tcp:x1.c.lencr.org:80 ”类似的访问，又Google一下，发现应该是letsencrypt的证书验证的访问，看起来我们使用了letsencrypt的证书，就会产生类似的访问，应该是正常的。附上网址供参考：https://letsencrypt.org/docs/lencr.org/

**Comment by yuhan6665** [comment]
@973kt 感谢探究这个问题 我也学到了新东西

**Comment by cross-hello** [comment]
🤣 And have some joy inside.

----------------------------------------

*From: *yuhan6665 ***@***.***>
*To: *XTLS/Xray-core ***@***.***>
*CC: *Nanyu ***@***.***>; Comment ***@***.***>
*Date: *Nov 13, 2022 03:19:11
*Subject: *Re: [XTLS/Xray-core] 
vision流控一直连接r3.o.lencr.org[https://vision流控一直连接r3.o.lencr.org] (Issue 
#1331)

**Comment by tdjnodj** [comment]
@yuhan6665 
这非常值得修复，如果屏蔽r3.o.lencr.org可能会带来安全性问题，不屏蔽又会使本机大量访问消耗网络、CPU资源。
