### ISSUE TITLE
1.6.4还是有间或性的SSL ERROR

### ISSUE THREAD

**Issue by GreatMichaelLee** [XTLS/Xray-core#1336]
日志没法发，比如我github拉代码就会出现这种，一般出现在首次连接时。

![image](https://user-images.githubusercontent.com/20067401/201640745-2b504f49-2af4-4b83-b1fe-cd171b8e4c54.png)

**Comment by loydcheung** [comment]
> 日志没法发，比如我github拉代码就会出现这种，一般出现在首次连接时。
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/20067401/201640745-2b504f49-2af4-4b83-b1fe-cd171b8e4c54.png)
> 
> 
> 
> 
> 
> 

我也有同样的问题，GitHub拉代码有时也会这样，有时表现为q外网上不去，要重启ssr才打。我是用的xtls-whatever模板改的vision和其他ss等协议共存。

**Comment by GreatMichaelLee** [comment]
抓了一些服务端的日志，客户端的日志不好抓

2022/11/14 20:03:37 [Info] [3747596729] proxy/vless/inbound: received request for tcp:github.com:443
2022/11/14 20:03:37 [Info] [3747596729] proxy/vless/encoding: Xtls Unpadding new block0 16 content 399 padding 831 0
2022/11/14 20:03:37 [Info] [3747596729] proxy/vless/encoding: XtlsFilterTls13 found tls client hello! 399
2022/11/14 20:03:37 [Info] [3747596729] app/dispatcher: sniffed domain: github.com
2022/11/14 20:03:37 [Info] [3747596729] app/dispatcher: default route for tcp:github.com:443
2022/11/14 20:03:37 [Info] [3747596729] proxy/freedom: opening connection to tcp:github.com:443
2022/11/14 20:03:37 [Debug] app/dns: domain github.com will use DNS in order: [localhost]
2022/11/14 20:03:37 [Info] app/dns: Localhost got answer: github.com -> [20.205.243.166]
2022/11/14 20:03:37 [Info] [3747596729] proxy/freedom: dialing to tcp:20.205.243.166:443
2022/11/14 20:03:37 [Info] [3747596729] transport/internet/tcp: dialing TCP to tcp:20.205.243.166:443
2022/11/14 20:03:37 [Debug] transport/internet: dialing to tcp:20.205.243.166:443
2022/11/14 20:03:37 [Info] [3747596729] proxy/vless/encoding: XtlsFilterTls13 found tls 1.3! 2858 TLS_AES_128_GCM_SHA256
2022/11/14 20:03:37 [Info] [3747596729] proxy/vless/encoding: XtlsPadding 2858 0 0
2022/11/14 20:03:37 [Info] [3747596729] proxy/vless/encoding: Xtls Unpadding new block0 0 content 6 padding 956 0
2022/11/14 20:03:37 [Info] [3747596729] proxy/vless/encoding: Xtls Unpadding new block0 0 content 58 padding 1168 2
2022/11/14 20:03:37 [Info] [3747596729] proxy/vless/encoding: XtlsRead readV
2022/11/14 20:03:37 [Info] [3747596729] proxy/vless/encoding: XtlsPadding 158 1200 2
2022/11/14 20:03:37 [Info] [3747596729] proxy/vless/encoding: XtlsWrite writeV 0 1363 0
2022/11/14 20:03:38 [Info] [3725496517] proxy/vless/inbound: firstLen = 0
2022/11/14 20:03:38 [Info] [3725496517] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly
2022/11/14 20:03:38 [Info] [3725496517] proxy/vless/inbound: realName =
2022/11/14 20:03:38 [Info] [3725496517] proxy/vless/inbound: realAlpn =
2022/11/14 20:03:38 [Info] [3725496517] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > tls: client offered only unsupported versions: [303 302 301]
2022/11/14 20:03:38 [Info] [595593979] proxy/vless/inbound: firstLen = 0
2022/11/14 20:03:38 [Info] [595593979] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly
2022/11/14 20:03:38 [Info] [595593979] proxy/vless/inbound: realName =
2022/11/14 20:03:38 [Info] [595593979] proxy/vless/inbound: realAlpn =
2022/11/14 20:03:38 [Info] [595593979] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > tls: client offered only unsupported versions: [303 302 301]
2022/11/14 20:03:39 [Info] [2469488651] proxy/vless/inbound: firstLen = 0
2022/11/14 20:03:39 [Info] [2469488651] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly
2022/11/14 20:03:39 [Info] [2469488651] proxy/vless/inbound: realName =
2022/11/14 20:03:39 [Info] [2469488651] proxy/vless/inbound: realAlpn =
2022/11/14 20:03:39 [Info] [2469488651] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > tls: client offered only unsupported versions: [303 302 301]
2022/11/14 20:03:39 [Info] [2561887883] proxy/vless/inbound: firstLen = 0
2022/11/14 20:03:39 [Info] [2561887883] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly
2022/11/14 20:03:39 [Info] [2561887883] proxy/vless/inbound: realName =
2022/11/14 20:03:39 [Info] [2561887883] proxy/vless/inbound: realAlpn =
2022/11/14 20:03:39 [Info] [2561887883] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > tls: client offered only unsupported versions: [303 302 301]
2022/11/14 20:03:40 [Info] [3563102118] proxy/vless/inbound: firstLen = 0
2022/11/14 20:03:40 [Info] [3563102118] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly
2022/11/14 20:03:40 [Info] [3563102118] proxy/vless/inbound: realName =
2022/11/14 20:03:40 [Info] [3563102118] proxy/vless/inbound: realAlpn =
2022/11/14 20:03:40 [Info] [3563102118] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > tls: client offered only unsupported versions: [303 302 301]
2022/11/14 20:03:41 [Info] [4074699051] proxy/vless/inbound: firstLen = 0
2022/11/14 20:03:41 [Info] [4074699051] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly
2022/11/14 20:03:41 [Info] [4074699051] proxy/vless/inbound: realName =
2022/11/14 20:03:41 [Info] [4074699051] proxy/vless/inbound: realAlpn =
2022/11/14 20:03:41 [Info] [4074699051] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > tls: client offered only unsupported versions: [303 302 301]
2022/11/14 20:03:41 [Info] [2199637514] proxy/vless/inbound: firstLen = 0
2022/11/14 20:03:41 [Info] [2199637514] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly
2022/11/14 20:03:41 [Info] [2199637514] proxy/vless/inbound: realName =
2022/11/14 20:03:41 [Info] [2199637514] proxy/vless/inbound: realAlpn =
2022/11/14 20:03:41 [Info] [2199637514] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > tls: client offered only unsupported versions: [303 302 301]
2022/11/14 20:03:41 [Info] [3369705821] proxy/vless/inbound: firstLen = 0
2022/11/14 20:03:41 [Info] [3369705821] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly
2022/11/14 20:03:41 [Info] [3369705821] proxy/vless/inbound: realName =

**Comment by GreatMichaelLee** [comment]
我找到问题了，我客户端的配置里没有minVersion:1.3 这一句，服务端加了这一句，把服务端的最小版本1.3配置去掉后正常了许多（偶尔还有408超时报出），所以我猜是不是当客户端用TLS 1.2的时候，服务端就识别不了？还是其实是随机匹配的？我看日志里有提说客户端提供了不支持的版本303/302/301. 现在xray core支持TLS1.3吗？ @yuhan6665

**Comment by linusdrop** [comment]
Повторное возникновение проблемы

**Comment by linusdrop** [comment]
> 手机chrome还是不断地报“ERR_SSL_BAD_RECORD_MAC_ALERT", 刷新几次能好
Повторное возникновение проблемы!

**Comment by even0306** [comment]
![4ab6921d605de5671bb68d379178445](https://user-images.githubusercontent.com/58162761/201815442-e970e9dc-6091-414d-8f28-c958d56d2d83.jpg)
我也出现了，pc端日志没有保存进文件，一直在跳，只能先截图了，这个1767是不是新的8192

**Comment by GreatMichaelLee** [comment]
时不时的出这种error到底啥原因？频率很高啊

![image](https://user-images.githubusercontent.com/20067401/202605305-c59768b1-61cd-40ca-8f14-d75b57c37a8c.png)

**Comment by vinograd-cyber** [comment]
I also encountered the same problem, I reverted to stable version 1.6.1 situation has been greatly alleviated, beta version 1.6.2, 3, 4 have the same problem, I hope the official can be resolved in the next version.

**Comment by GreatMichaelLee** [comment]
这个问题有什么进展吗？刚试了那个fix big hello的auto build版本，貌似没有解决这个问题。

**Comment by vinograd-cyber** [comment]
![图片](https://user-images.githubusercontent.com/96408692/203217561-b35dbfcb-6489-43fe-89ba-f9c589e8053d.png)
https的时不时错误，过两秒钟刷新又可以了，这个问题用稳定版1.6.1也经常发生，希望官方能解决下呢

**Comment by GreatMichaelLee** [comment]
> 可能是TLS v1.3的问题， 用V2rayN windows 客户端，使用xray 1.6.4核心，在option V2rayN setting里，勾上Enable Security Protocol TLS v1.3试试可能可以解决这个问题。

试了，没啥用，外甥打灯笼-照旧-_-!

**Comment by RPRX** [comment]
请使用 v1.7.2+ https://github.com/XTLS/Xray-core/releases/tag/v1.7.2
