### ISSUE TITLE
大量报failed是不是内核处理数据流的问题

### ISSUE THREAD

**Issue by KC9226** [XTLS/Xray-core#134]
![QQ图片20210104222255](https://user-images.githubusercontent.com/24265418/103544867-b10aa000-4edb-11eb-9080-85586d106f01.png)
请大佬指教

**Comment by C222l** [comment]
![3D28A904-2A6F-4A4F-BC03-83EE4354FCED](https://user-images.githubusercontent.com/75424407/103545512-a270b880-4edc-11eb-9866-0cf96a0edfaf.jpeg)
我这客户端也报，我大白，不懂

**Comment by fangshixiong** [comment]
2021/01/04 23:28:49 [Warning] [951023429] proxy/http: failed to read response from iofqxhydalbfw > io: read/write on closed pipe
2021/01/04 23:28:49 [Warning] [509578200] proxy/http: failed to read response from tluwsprjcyh > io: read/write on closed pipe
2021/01/04 23:28:49 [Warning] [1257451418] proxy/http: failed to read response from zkgqgkgjlus > io: read/write on closed pipe

v2rayn 4.3 Xray 1.20也遇到了类似情况。

**Comment by rprx** [comment]
统一回复：连接异常断开是常有的现象，比如可以试试开着命令行输出，然后直接把浏览器关掉

**Comment by badO1a5A90** [comment]
已加入文档 FAQ
