### ISSUE TITLE
最近想从trojan转xray来但是trojan的特性没有完全实现

### ISSUE THREAD

**Issue by hudingwen** [XTLS/Xray-core#1349]
由于长期使用数据库管理trojan用户，导致无法从gfw-trojan迁移到xray-trojan中来，希望能完善此特性。

主要问题是多台服务器的时候不知道xray中是如何统一管理一个用户id能在所有服务器上进行识别?
当我在trojan-gfw中使用数据库管理时,我不需要考虑我的后端api是java,go,C#,php语言，我只需要往数据库中标记用户或者添加用户id即可即在所有trojan服务上进行应用,以至于在迁移时我只需要迁移数据库和备份还原数据库操作

**Comment by kireiyume** [comment]
开机场？那你该考虑xrayR之类后端，xray只是散户玩的平台，不适合你

**Comment by hudingwen** [comment]
没有 就是管理不方便  经常换服务器

**Comment by yuhan6665** [comment]
close as not planed
