### ISSUE TITLE
使用Vision流控时，客户端不识别TLS_AES_256_GCM_SHA384

### ISSUE THREAD

**Issue by mirror1342** [XTLS/Xray-core#1354]
版本：1.6.4
使用场景：路由器透明代理
重现步骤：iOS 15 油管APP播放视频，此时*.googlevideo.com走了TLS_AES_256_GCM_SHA384，其流量被路由器上的Xray透明代理

客户端配置：
```
        {
            "tag": "test",
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "----",
                        "port": 443,
                        "users": [
                            {
                                "flow": "xtls-rprx-vision",
                                "encryption": "none",
                                "id": "----"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "fingerprint": ""
                }
            }
        },
```

服务端配置：
```
        {
            "listen": "0.0.0.0",
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "flow": "xtls-rprx-vision",
                        "id": "----"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": 80
                    }
                ]
            },
            "sniffing": {"enabled": true,"destOverride": ["http","tls"]},
            "streamSettings": {
                "network": "tcp",
                "security":"tls",
                "tlsSettings": {
                  "alpn": ["http/1.1"],
                  "certificates": [
                    {
                      "certificateFile":"----",
                      "keyFile":"----"
                    }
                  ]
                }
            }
        },
```

客户端日志：
![client](https://user-images.githubusercontent.com/118648583/202886389-dc85fe9f-5da7-41c5-985a-f979bc48b187.jpg)
可见客户端没有found TLS1.3和TLS_AES_256_GCM_SHA384，是否生效不明。

服务端日志：
![server](https://user-images.githubusercontent.com/118648583/202886393-a2477b8d-0ac8-4d2b-b424-fd25243b7923.jpg)
可见服务端识别出了TLS_AES_256_GCM_SHA384

期待结果：只要检测到TLS，就输出TLS版本。当TLS1.3时，输出加密套件名称。这样用户看到加密套件名称就知道已生效，否则就是没生效。

希望解决并排查同类问题。

**Comment by yuhan6665** [comment]
感谢报告 可能是过滤有一点问题 这个问题每次都会发生吗？当发生时除了日志异常以外有什么现象？

**Comment by lxhao61** [comment]
> 感谢报告 可能是过滤有一点问题 这个问题每次都会发生吗？当发生时除了日志异常以外有什么现象？

说到过滤，没有明白‘内层流量为 TLSv1.3 时直接转发（已过滤掉 TLSv1.2），且客户端自动应用 Splice’这句话的意思。是否xtls-rprx-vision仅工作在TLSv1.3，不必配置minVersion最小为TLSv1.2（配置也无效）.

**Comment by mirror1342** [comment]
> 感谢报告 可能是过滤有一点问题 这个问题每次都会发生吗？当发生时除了日志异常以外有什么现象？
只要是TLS_AES_256_GCM_SHA384，每次都会发生。客户端无 found TLS1.3和TLS_AES_256_GCM_SHA384，但是服务端有。路由器是misple的低端硬路由，现象我只能说路由器负载升高。

**Comment by yuhan6665** [comment]
@lxhao61 是 xtls 仅 TLS1.3。遇到内层 1.2 会包一层让外界看见 TLS1.3。
TLS版本配置影响的外层版本，可以修改，只要外层协商出1.3就没问题

**Comment by yuhan6665** [comment]
@mirror1342 有点意思 我试一下 如果不好复现 我可能需要加一点日志再找你测

**Comment by lxhao61** [comment]
@yuhan6665 @simpleandstupid 感谢回复及释疑，谢谢！

**Comment by yuhan6665** [comment]
@mirror1342 你的issue很有用 发现了一个问题 应该修好了 https://github.com/XTLS/Xray-core/commit/494a10971b7c942f4c72ffe0ff116f21481b0bd9 等下个版本

**Comment by mirror1342** [comment]
@yuhan6665 已编译测试，结果如下。图中有2个请求，分别用蓝色和绿色标注。客户端这边2个请求都识别为TLS1.2，服务端则1个识别为TLS1.2，1个识别为TLS1.3 TLS_AES_256_GCM_SHA384。

客户端：
![屏幕截图 2022-11-22 004324](https://user-images.githubusercontent.com/118648583/203101972-9727bf58-3226-4671-9a66-a4c5ac6bd2f1.jpg)

服务端
![屏幕截图 2022-11-22 004630](https://user-images.githubusercontent.com/118648583/203102330-926bc58e-12c3-4cad-b68f-007487ca5597.jpg)

**Comment by yuhan6665** [comment]
嗯。。可能这个不太好修，我增加了一些日志，能再帮忙测一下这个自动构建？https://github.com/XTLS/Xray-core/actions/runs/3520236523

**Comment by mirror1342** [comment]
@yuhan6665 

客户端
![屏幕截图 2022-11-22 213421](https://user-images.githubusercontent.com/118648583/203316301-2897c42c-ff06-4870-a925-dca63e97283d.jpg)

服务端
![屏幕截图 2022-11-22 213222](https://user-images.githubusercontent.com/118648583/203316482-963cb222-67c8-4a04-ac98-63482b3c6da2.jpg)

**Comment by yuhan6665** [comment]
又改了一个版本 麻烦你再测一下自动构建 https://github.com/XTLS/Xray-core/actions/runs/3538057779

**Comment by mirror1342** [comment]
稍等，环境在别人家，我要找别人测

**Comment by yuhan6665** [comment]
请试用 1.6.5 如果有问题再打开

**Comment by mirror1342** [comment]
已测试OK

![屏幕截图 2022-12-10 005805](https://user-images.githubusercontent.com/118648583/206742014-4a92ac56-348b-4a95-800f-0246730b65d0.jpg)
