### ISSUE TITLE
连续端口被封有没有好的建议？

### ISSUE THREAD

**Issue by jcyuan** [XTLS/Xray-core#1356]
稳定使用了几年，最近不知道为什么，端口两天必被封，换了新端口后，两天后必定又被封。
是检测到了特征值？不太可能吧？！
大家有没有好的建议应对这种情况？或者能不能分析是什么原因被封？非常感谢。

**Comment by chika0801** [comment]
原因几句说不清楚。不是你一人遇到。10月3日开始的，常态化了。应对是使用xtls vision流控，或用hysteria（在github里搜）。

**Comment by jcyuan** [comment]
> 

感谢回复！我试下。

**Comment by jcyuan** [comment]
> 原因几句说不清楚。不是你一人遇到。10月3日开始的，常态化了。应对是使用xtls vision流控，或用hysteria（在github里搜）。
感谢回复！我试下。

**Comment by jcyuan** [comment]
> 原因几句说不清楚。不是你一人遇到。10月3日开始的，常态化了。应对是使用xtls vision流控，或用hysteria（在github里搜）。

想请教下，Hy不是代理吗。那用它来请求v2ray能绕过是什么原理？

**Comment by qist** [comment]
https://github.com/apernet/hysteria  这个把。 客户端用Clash.Meta

**Comment by jcyuan** [comment]
> > 原因几句说不清楚。不是你一人遇到。10月3日开始的，常态化了。应对是使用xtls vision流控，或用hysteria（在github里搜）。
> 
> 想请教下，Hy不是代理吗。那用它来请求v2ray能绕过是什么原理？

刚才想错了，原来v2ray只是用来作为客户端。先试下看看能顶几天。
可惜没有安卓端。

**Comment by jcyuan** [comment]
> > > > 原因几句说不清楚。不是你一人遇到。10月3日开始的，常态化了。应对是使用xtls vision流控，或用hysteria（在github里搜）。
> > > 
> > > 
> > > 想请教下，Hy不是代理吗。那用它来请求v2ray能绕过是什么原理？
> > 
> > 
> > 刚才想错了，原来v2ray只是用来作为客户端。先试下看看能顶几天。 可惜没有安卓端。
> 
> vision流控安卓上用v2rayng hy协议安桌上用sagernet

收到，感谢！👍

**Comment by Kia678** [comment]
https://github.com/XTLS/Xray-core/issues/1358

**Comment by lemures-t** [comment]
https://github.com/2dust/v2rayNG/releases

**Comment by chika0801** [comment]
> > > > > 原因几句说不清楚。不是你一人遇到。10月3日开始的，常态化了。应对是使用xtls vision流控，或用hysteria（在github里搜）。
> > > > 
> > > > 
> > > > 想请教下，Hy不是代理吗。那用它来请求v2ray能绕过是什么原理？
> > > 
> > > 
> > > 刚才想错了，原来v2ray只是用来作为客户端。先试下看看能顶几天。 可惜没有安卓端。
> > 
> > 
> > vision流控安卓上用v2rayng hy协议安桌上用sagernet
> 
> 收到，感谢！ 用vision的话，需要选uTLS吗？是只适用于xtls对吧？tls有用吗？
> 
> 刚测了下，貌似不行，538用vision，提示不支持该flow， 然后就是安卓上的v2rayNG还没更新新版，没有vision项 😞

用vision的话，需要选uTLS吗？是只适用于xtls对吧？tls有用吗？
uTLS客户端有这个选项，建议选上

刚测了下，貌似不行，538用vision，提示不支持该flow，
更新xray-core到最新版本

然后就是安卓上的v2rayNG还没更新新版，没有vision项 😞
更新NG到最新版本

**Comment by vinograd-cyber** [comment]
hysteria 这个软件我测试过了，不是很稳定，时不时就网络超时，项目开始于今年三月，还是一个很年轻的软件，虽然号称比kcptun快，但是稳定远远不及kcptun。

**Comment by maplecool** [comment]
https://github.com/maplecool/easytrojan
试试这个项目

**Comment by jcyuan** [comment]
我用vision了。不想折腾。但是vision目前还是beta没有正式release，目前延迟很高。
