### ISSUE TITLE
在1.6.4中对于quic 5min无数据断开的修改好像失效了

### ISSUE THREAD

**Issue by aabbccgg** [XTLS/Xray-core#1357]
如题，1.6.4中quic又回到了默认的30s无连接断开。而在 #475 中是修改了的，并设置了5min的keepalive。

另外，对于window ssh无法代理（http/socks）的问题也请看一下 #1347 。^_^

**Comment by aabbccgg** [comment]
尝试这样进行了修改，5min断开连接+8s握手超时
#1365

**Comment by yuhan6665** [comment]
solved

**Comment by S-Tsunemori** [comment]
https://github.com/XTLS/Xray-core/pull/475#issuecomment-814220882 里面RPRX的原话（部分）：

> 为了避免产生特征，MaxIdleTimeout 均不传值、采用默认的 30s 更合适？

原本的修改只是开启了quic-go自带的keepalive而没有固定任何数值，这两个固定数值（8秒和300秒）是如何选定的？是否可能成为xray流量的特征？

**Comment by aabbccgg** [comment]
> [#475 (comment)](https://github.com/XTLS/Xray-core/pull/475#issuecomment-814220882) 里面RPRX的原话（部分）：
> 
> > 为了避免产生特征，MaxIdleTimeout 均不传值、采用默认的 30s 更合适？
> 
> 原本的修改只是开启了quic-go自带的keepalive而没有固定任何数值，这两个固定数值（8秒和300秒）是如何选定的？是否可能成为xray流量的特征？

这个修改早就因为版本合并被覆盖了，从新按照RPRX的5分钟超时继续了设置。go的keepalive倒是可以检测，所以我最后的提交并没有使用keepalive而是让客户端自己有通信来keep，你在5min内重新通信就自动刷新了。8s handshake超时很正常吧，而且也很难从外部进行检测，gfw要这样关联context检测成本过高了，相当于每个连接就要创建一个时钟。当然你可以做成4-8s随机的，然而意义有限。

**Comment by S-Tsunemori** [comment]
> > [#475 (comment)](https://github.com/XTLS/Xray-core/pull/475#issuecomment-814220882) 里面RPRX的原话（部分）：
> > > 为了避免产生特征，MaxIdleTimeout 均不传值、采用默认的 30s 更合适？
> > 
> > 
> > 原本的修改只是开启了quic-go自带的keepalive而没有固定任何数值，这两个固定数值（8秒和300秒）是如何选定的？是否可能成为xray流量的特征？
> 
> 这个修改早就因为版本合并被覆盖了，从新按照RPRX的5分钟超时继续了设置。go的keepalive倒是可以检测，所以我最后的提交并没有使用keepalive而是让客户端自己有通信来keep，你在5min内重新通信就自动刷新了。8s handshake超时很正常吧，而且也很难从外部进行检测，gfw要这样关联context检测成本过高了，相当于每个连接就要创建一个时钟。当然你可以做成4-8s随机的，然而意义有限。

被检测指的应该是和其他的quic-go程序表现出了不同的、独有的特征吧？quic-go默认的表现是如果没有使用keepalive，那么30秒无流量会断开。xray在现在这么修改之后既没有使用keepalive又5分钟维持连接没有断开，这不是xray独有而其他quic-go程序不具有的特征吗？

**Comment by aabbccgg** [comment]
> > > [#475 (comment)](https://github.com/XTLS/Xray-core/pull/475#issuecomment-814220882) 里面RPRX的原话（部分）：
> > > > 为了避免产生特征，MaxIdleTimeout 均不传值、采用默认的 30s 更合适？
> > > 
> > > 
> > > 原本的修改只是开启了quic-go自带的keepalive而没有固定任何数值，这两个固定数值（8秒和300秒）是如何选定的？是否可能成为xray流量的特征？
> > 
> > 
> > 这个修改早就因为版本合并被覆盖了，从新按照RPRX的5分钟超时继续了设置。go的keepalive倒是可以检测，所以我最后的提交并没有使用keepalive而是让客户端自己有通信来keep，你在5min内重新通信就自动刷新了。8s handshake超时很正常吧，而且也很难从外部进行检测，gfw要这样关联context检测成本过高了，相当于每个连接就要创建一个时钟。当然你可以做成4-8s随机的，然而意义有限。
> 
> 被检测指的应该是和其他的quic-go程序表现出了不同的、独有的特征吧？quic-go默认的表现是如果没有使用keepalive，那么30秒无流量会断开。xray在现在这么修改之后既没有使用keepalive又5分钟维持连接没有断开，这不是xray独有而其他quic-go程序不具有的特征吗？


首先：这并不是第一次修改5min超时，在某个版本前一直是5min超时，是合并quic覆盖了设置。
其次：请问gfw如何判断断开/保活？您有看过未断开但是无数据时的表现吗？ 在我这边测试，和断开了是表现一致的，在0rrt下要怎么判断是重发了还依然保活的呢？就算我们假设上述都可以检测，难道gfw为每个链接开启一个时差计算功能吗，未免开销也太高了，上文我已经解释了，gfw基本上不会去支持基于context的检测。
然后：请问网页客户端用quic，也会实现x min的超时，怎么区分是正常h2 quic设置还是xray客户端呢？
最后，如果您不认可这个修改，可以提issue覆盖commit，但是请证明可以检测而不是猜测。如果您实在担心这个问题，可以选择使用自定义的修改编译而不是公开发布版本。
