### ISSUE TITLE
如何配置能中转vless + xtls和回落的trojan，到另外一台出口vps

### ISSUE THREAD

**Issue by LearZhou** [XTLS/Xray-core#136]
如：
client ->|-> vps1 (relay server) ->vps2 -> THE internet
这种配置，若vps1入口配置成vless + xtls回落到trojan，那么应当如何配置出口路由，使其原样转发到vps2（vps2也是配置成vless + xtls回落到trojan）而能够保持trojan对udp的支持。

目前我用
    "rules": [
      {
        "type": "field",
        "user": [ "vless-relay@example.com" ],
        "outboundTag": "out-vless-xtlst",
        "inboundTag": [ "in-vless-xtls" ]
      },
这种vps1的配置，客户端配置成vps1的trojan的密码，结果NatTypeTester测试出来的RFC 3489为UnsupportedServer，似乎有明显问题。

问题是，这种情况应该如何配置，能够保持转发效率，而且能保证回落的trojan的udp能达成full cone？

另外，客户端设置vps1的trojan密码不对，似乎设置为vps2的trojan密码也不行啊。

**Comment by rprx** [comment]
目前 vps1 和 vps2 间不能用 VLESS，否则会失去 FullCone

客户端应该用 vps1 的 trojan 密码
