### ISSUE TITLE
更新1.64版本后，vnext工作不正常

### ISSUE THREAD

**Issue by youngxlover** [XTLS/Xray-core#1366]
因为测试vision流控的关系，升级1.64版，vision正常，vnext失效。
回退1.61版本，立即恢复。

**Comment by chika0801** [comment]
vnext是？你说清楚

**Comment by youngxlover** [comment]
链式代理，部分域名分流到其他服务器，用的是vless的出站

**Comment by yuhan6665** [comment]
麻烦贴一下配置和日志

**Comment by youngxlover** [comment]
{
      "tag": "sj",
      "protocol": "vless",
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
		  "serverName": "example.com",
          "allowInsecure": false
        }
      },
      "settings": {
        "vnext": [
          {
            "address": "example.com",
            "port": 443,	
            "users": [
              {
                "id": "xxxx5502-83f6-4d9b-assssssssssssss",
                "encryption": "none",
				"flow": "xtls-rprx-direct",
				"level": 0
              }
            ]
          }
        ]
      }
    },

配置如上， youtube分流到这个服务器

1.61正常状态下，访问youtube的日志
Nov 24 13:00:27 instance-2021xxxx-xxxx xray[124032]: 2022/11/24 13:00:27 127.0.0.1:0 accepted tcp:www.youtube.com:443 [VLESSGRPC -> sj]

升级到1.64测试版，访问非链式代理的网站，正常
2022/11/24 13:33:41 127.0.0.1:0 accepted tcp:raw.githubusercontent.com:443 [VLESSGRPC >> IPv4-out]
访问youtube,  xray似乎是直接重启了，没有记录。errorlog也没有记录，显示的是启动。
浏览器端，显示错误是无法解析响应。

回退1.61，恢复正常。

**Comment by yuhan6665** [comment]
链式代理相关的配置都贴一下

**Comment by youngxlover** [comment]
{
    "outbounds":[
        {
            "protocol":"freedom",
            "settings":{
                "domainStrategy":"UseIPv4"
            },
            "tag":"IPv4-out"
        },
        {
            "protocol":"freedom",
            "settings":{
                "domainStrategy":"UseIPv6"
            },
            "tag":"IPv6-out"
        },
        {
            "protocol":"blackhole",
            "tag":"blackhole-out"
        },
    {
      "tag": "GoNetflix",
      "protocol": "vmess",
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false
        },
        "wsSettings": {
          "path": "ws"
        }
      },
      "mux": {
        "enabled": true,
        "concurrency": 8
      },
      "settings": {
        "vnext": [
          {
            "address": "111",
            "port": 443,
            "users": [
              {
                "id": "111",
                "security": "auto",
                "alterId": 0
              }
            ]
          }
        ]
      }
    },
	{
      "tag": "sj",
      "protocol": "vless",
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
		  "serverName": "111",
          "allowInsecure": false
        }
      },
      "settings": {
        "vnext": [
          {
            "address": "111",
            "port": 443,	
            "users": [
              {
                "id": "111",
                "encryption": "none",
				"flow": "xtls-rprx-direct",
				"level": 0
              }
            ]
          }
        ]
      }
    },
		{
      "tag": "cc",
      "protocol": "vless",
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
		  "serverName": "111",
          "allowInsecure": false
        }
      },
      "settings": {
        "vnext": [
          {
            "address": "111",
            "port": 443,	
            "users": [
              {
                "id": "111",
                "encryption": "none",
				"flow": "xtls-rprx-direct",
				"level": 0
              }
            ]
          }
        ]
      }
    }
    ]
}

是这样吗？

**Comment by yuhan6665** [comment]
主要是需要知道你的链式代理 客户端 服务端是如何配置的

**Comment by youngxlover** [comment]
服务端inbound

{
  "inbounds": [
    {
      "port": 443,
      "protocol": "vless",
      "tag": "VLESSTCP",
      "settings": {
        "clients": [
          {
            "id": "id",
            "add": "example.top",
            "flow": "xtls-rprx-direct",
            "email": "example_VLESS_XTLS/TLS-direct_TCP"
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "dest": 31296,
            "xver": 1
          },
          {
            "alpn": "h2",
            "dest": 31302,
            "xver": 0
          },
          {
            "path": "/gbaxws",
            "dest": 31297,
            "xver": 1
          },
          {
            "path": "/gbaxvws",
            "dest": 31299,
            "xver": 1
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
          "minVersion": "1.2",
          "alpn": [
            "h2",
            "http/1.1"
          ],
          "certificates": [
            {
              "certificateFile": "/etc/v2ray-agent/tls/example.crt",
              "keyFile": "/etc/v2ray-agent/tls/example.key",
              "ocspStapling": 3600,
              "usage": "encipherment"
            }
          ]
        }
      }
    }
  ]
}

**Comment by yuhan6665** [comment]
请试用 1.6.5 如果有问题再打开
