### ISSUE TITLE
How to limit IP connection

### ISSUE THREAD

**Issue by ZebcoWeb** [XTLS/Xray-core#1369]
How to limit that a specific IP can connect to Vmess or other protocols?

**Comment by FighterTunnel** [comment]
@teddysun

**Comment by yuhan6665** [comment]
Not a feature for core

**Comment by hiddify** [comment]
So how can we do that?

**Comment by cross-hello** [comment]
Be care to follow every steps 

```sh 

su ufw deny from 0.0.0.0/0 to any

```
😏

**Comment by hiddify** [comment]
I did it but it show command not found ufw would you please explain more 
😏
