### ISSUE TITLE
1.2.0 感觉 Google voice 貌似不能用了 

### ISSUE THREAD

**Issue by aresbigboy** [XTLS/Xray-core#138]
我用的是Android版的 v2rayNG 采用最新的 xray-core 1.2.0
客户端outbound跑的 vless xtls splice

**Comment by rprx** [comment]
（我现在开始研究一下 UDP 可能存在的问题并修复

**Comment by aresbigboy** [comment]
> （我现在开始研究一下 UDP 可能存在的问题并修复

多谢。我试了一下，从1.1.5版本开始vless xtls splice 模式 gv就不能打电话了。
等您修复。

**Comment by rprx** [comment]
目前的方向是 DNS 和 IPv6

**Comment by rprx** [comment]
确定 1.1.4 正常吗

**Comment by aresbigboy** [comment]
> 确定 1.1.4 正常吗

确定 1.1.4 正常，我已经回退1.1.4了。

**Comment by rprx** [comment]
服务端保持 1.2.0 吗？

**Comment by aresbigboy** [comment]
> 服务端保持 1.2.0 吗？

对的。服务端及我的中专机都保持在了1.2.0。不论是用中转，还是直连vps。 只要客户端是 1.1.4 就正常。

**Comment by rprx** [comment]
麻烦发一下客户端 1.2.0 的相关日志

**Comment by rprx** [comment]
由于你说的是 VLESS，且是客户端的问题，相关的改动主要是 Socks 入站，但代码怎么看都没问题，这里需要提供更多信息

**Comment by rprx** [comment]
试一下不同的 dns 配置

**Comment by GleenJi** [comment]
> 
> 
> 我用的是Android版的 v2rayNG 采用最新的 xray-core 1.2.0
> 客户端outbound跑的 vless xtls splice

大兄弟，这个splice怎么开启啊😂，我用的1.20版本配置splice提示这个版本不支持，xray无法启动，只能用direct

**Comment by badO1a5A90** [comment]
这应该和 v2rayNG 有关.
使用 1.2.0的xray, 做透明代理, 手机通过透明代理可以正常拨打GV并且通话.
使用  v2rayNG 1.5.8(核心为xray1.2.0),能拨打GV,但接通后立刻中断.

**Comment by rprx** [comment]
@badO1a5A90 太好了，你能复现

**Comment by badO1a5A90** [comment]
目前测试的一些组合:
1. 使用 1.2.0的xray,socks inbound+VLESS outbound, 浏览器设置socks代理为xray的socks inbound, 能拨打GV,并且正常通话.(另一个GV是手机接听且使用透明代理)
2. 使用 1.2.0的xray,http inbound+VLESS outbound, 浏览器设置http代理为xray的http inbound, 能拨打GV,并且正常通话.(另一个GV是手机接听且使用透明代理)
3. 使用 1.2.0的xray, 做透明代理,  手机A 通过透明代理可以正常拨打GV并且通话.
4. 使用 v2rayNG 1.5.8(核心为xray1.2.0), 手机A能拨打GV,但接通后立刻中断

**Comment by rprx** [comment]
根据 https://github.com/2dust/AndroidLibXrayLite/blob/main/interact.go ，v2rayNG 启动 Xray 的方式绕过了此前的配置检测机制，该机制的作用是对 VLESS、VMess 应用 Symmetric 而不是 FullCone，否则 UDP 会出问题（Clash 的就一直存在问题）

https://github.com/XTLS/Xray-core/commit/ee15cc253f5576bc393895a9ddd2e90bf1f4fda0 这个提交应该解决了问题，等 NG 新版本即可。

**Comment by lizkes** [comment]
@rprx 赞

**Comment by badO1a5A90** [comment]
服务端 xray v1.2.1
手机端 https://github.com/2dust/v2rayNG/releases/tag/1.5.9
已经完美解决这个问题.

(强烈建议更新至 v1.2.1, 也包括了其他UDP问题的解决)

**Comment by wanxj119** [comment]
@rprx 感谢！

**Comment by gonboy** [comment]
> 
> 
> 我用的是Android版的 v2rayNG 采用最新的 xray-core 1.2.0
> 客户端outbound跑的 vless xtls splice

如何配置才能支持 google voice .
是否需要开启特定udp端口？ 代理端口是否必须是443?

**Comment by FreemanDQ** [comment]
> > 我用的是Android版的 v2rayNG 采用最新的 xray-core 1.2.0
> > 客户端outbound跑的 vless xtls splice
> 
> 如何配置才能支持 google voice . 是否需要开启特定udp端口？ 代理端口是否必须是443?

同问，最新版本中，通话不会被直接挂断，但是听不到任何声音。

**Comment by Buttires1984** [comment]
是不是跟STUN有关系？

**Comment by FreemanDQ** [comment]
> 

请问应该在设置里作出哪些修改？

**Comment by gs002143** [comment]
好像ios的小火箭也是不能gv打电话
