### ISSUE TITLE
vision版本大面积重复报错，let'scrypt证书，也更换了ip，非443端口

### ISSUE THREAD

**Issue by isyume** [XTLS/Xray-core#1380]
如题，服务器系统重装过，也更换了ip，非443端口，但是搭建vision后有大面积报错，上网会出现断流情况。

rejected  proxy/vless/encoding: failed to read request version > read tcp 10.0.0.4:58290-> ip地址:47824: read: connection reset by peer

就像上面那样，偶尔会显示 accepted tcp:ip地址:端口 [direct]。

**Comment by chika0801** [comment]
这点信息，我们也帮不上你。你只能靠自己研究。或换如https://github.com/chika0801/sing-box-install

**Comment by cross-hello** [comment]
So the server still could be connected, just sometimes can't transit 
traffic?

----------------------------------------

*From: *isyume ***@***.***>
*To: *XTLS/Xray-core ***@***.***>
*CC: *Subscribed ***@***.***>
*Date: *Nov 26, 2022 12:15:34
*Subject: *[XTLS/Xray-core] vision版本大面积重复报错，let'scrypt证书，也更换了ip，非443端口 
(Issue #1380)

**Comment by cross-hello** [comment]
Next time when you use, if could please use Wireshark to capture some 
packets in Client.

----------------------------------------

*From: *isyume ***@***.***>
*To: *XTLS/Xray-core ***@***.***>
*CC: *Subscribed ***@***.***>
*Date: *Nov 26, 2022 12:15:34
*Subject: *[XTLS/Xray-core] vision版本大面积重复报错，let'scrypt证书，也更换了ip，非443端口 
(Issue #1380)

**Comment by cross-hello** [comment]
Give us some days(/weeks, if not talk about months or years), we maybe 
could provide code to rewrite ip of pcap file, so then you could replace 
all sensitive data(like your server ip to another ip like 
7.7.7.7[https://7.7.7.7]) in pcap file.

----------------------------------------

*From: *Nanyu ***@***.***>
*To: *XTLS/Xray-core ***@***.***>
*CC: *Nanyu ***@***.***>; Your activity 
***@***.***>
*Date: *Nov 27, 2022 15:12:16
*Subject: *Re: [XTLS/Xray-core] 
vision版本大面积重复报错，let'scrypt证书，也更换了ip，非443端口 (Issue #1380)

**Comment by yuhan6665** [comment]
看一下服务端日志 如果没有收到请求是网络问题或者被墙

**Comment by cross-hello** [comment]
Ok, we finished. Now you could use the code to remove servers information 
from Wireshark pcap traffic capture file.

https://github.com/cross-hello/Replace-IP-and-Ethc-mac-in-pcapng-file

תודה לאל.

----------------------------------------

*From: *Nanyu ***@***.***>
*To: *XTLS/Xray-core ***@***.***>
*CC: *Nanyu ***@***.***>; Your activity 
***@***.***>
*Date: *Nov 27, 2022 15:29:59
*Subject: *Re: [XTLS/Xray-core] 
vision版本大面积重复报错，let'scrypt证书，也更换了ip，非443端口 (Issue #1380)
