### ISSUE TITLE
[Feature Request] Reload configuration

### ISSUE THREAD

**Issue by npwc** [XTLS/Xray-core#1381]

**Comment by yuhan6665** [comment]
There are a couple stale pull requests about gRPC apis. If we can integrate those, we can control inbound, outbound, routing. That is pretty much what we need?

**Comment by deorth-kku** [comment]
> There are a couple stale pull requests about gRPC apis. If we can integrate those, we can control inbound, outbound, routing. That is pretty much what we need?  

Do we have routing control on grpc api now? I don't see it on the documents.  
If so, will it be added to the `xray api` subcommand?  
Thank you.
