### ISSUE TITLE
RoutingObject的attrs不工作

### ISSUE THREAD

**Issue by wenzhuning** [XTLS/Xray-core#1382]
路由配置如下：

{
"type": "field",
"network": "tcp",
"inboundTag": ["redir-tcp"],
"attrs": "attrs[':path'].startswith('/d?dn')"
"outboundTag": "block"
}

实测不生效，配置都是按官网写的，反复检查没问题，但是仍然不工作

**Comment by xqzr** [comment]
仅在代理 http 协议时起作用
