### ISSUE TITLE
1.6.5继续有ERR_SSL_BAD_RECORD_MAC_ALERT错误

### ISSUE THREAD

**Issue by GreatMichaelLee** [XTLS/Xray-core#1384]
![image](https://user-images.githubusercontent.com/20067401/204188476-31287ef6-56a9-43b6-9ec9-831e04b8d120.png)

**Comment by mclovin-2k** [comment]
Same here.

**Comment by loydcheung** [comment]
我这边用了一天多下来，虽然还不是最完美，但比起前面几版常常断，1.6.5稳定多了，只发生过一两次youtube断流，不用重启，大概一两分钟自行恢复，没有日志不确定原因。

**Comment by e54385991** [comment]
似乎1.64 不发生此问题 , 在openwrt passwall 中 使用rprx-vision

**Comment by loydcheung** [comment]
我重新编译openwrt去除了turboacc,试了两天暂时没问题了，之前光关闭没有用。

**Comment by loydcheung** [comment]
> 我重新编译openwrt去除了turboacc,试了两天暂时没问题了，之前光关闭没有用。

刚发完贴，又断连了...继续测试。

**Comment by GreatMichaelLee** [comment]
> > 我重新编译openwrt去除了turboacc,试了两天暂时没问题了，之前光关闭没有用。
> 
> 刚发完贴，又断连了...继续测试。

跟turboacc没什么关系吧，应该是协议兼容适配的问题。

**Comment by ZqinKing** [comment]
1.6.6-2断断续续出现，ERR_SSL_PROTOCOL_ERROR和ERR_SSL_BAD_RECORD_MAC_ALERT。协议用的xtls-rprx-vision,none

**Comment by RPRX** [comment]
请使用 v1.7.2+ https://github.com/XTLS/Xray-core/releases/tag/v1.7.2
