### ISSUE TITLE
Chrome & Firefox uTLS problem

### ISSUE THREAD

**Issue by H-Ir** [XTLS/Xray-core#1388]
Hi, I used the uTLS in Iraan but only safari and randomized work, Chrome and Firefox fingerprints are blocked. I think the fingerprints used are related to older versions of chrome & firefox. Can you fix it?

**Comment by yoohooyoo** [comment]
> 

Maybe you should rather go to the utls project's github page and commit?
[utls](https://github.com/refraction-networking/utls)

**Comment by yuhan6665** [comment]
Closing, please ask this with UTLS
