### ISSUE TITLE
1.6.5版本的新增的wireguard是否有必要

### ISSUE THREAD

**Issue by ixxmu** [XTLS/Xray-core#1390]
1 1.6.5 的wireguard出口可以用指定ip或者ipv4/v6的warp出口即可，为什么要新增实体？

2 warp这种方式已经被用烂了，并且近期开始现warp断开的情况。之前这个排错了半天以为是梯子的问题，最后发现是warp的出口自动断了，后来换了其他的脚本刷ip才能正常，虽然依旧会出现偶尔断开的情况。

用这个本身就是在薅其他服务的基础上进行的加持为何要出现核心版本上，况且这也增加了代码量，另外就算核心不增加此功能，当前也已经可以用自带路由表的方式实现一样的功能，感谢开发者们的努力，但极致、简洁同时性能爆表的特性才是xray才应该有的,显然支持薅warp是不需要的！

纯讨论 无其他，再次感谢大佬们给我们带来这么棒的工具！

**Comment by GreatMichaelLee** [comment]
我觉得折腾什么wireguard还不如把核心功能做稳定啊，现在vision流控问题感觉好多，干嘛不把vision做稳定，去折腾什么wireguard呢？当然，这是我的一家之言，有人可能会喷，你不用不代表别人不用^_^,希望能解决报RECORD_BAD_ALERT和什么PROTOCOL_MISMATCH之类的错误。

**Comment by hqvv** [comment]
新版客户端文件upx压缩后 比原来增加了近1M , 这对16M Flash的硬路由不够友好了。

**Comment by hkbase** [comment]
我暂时又用回xtls-rprx-direct、xtls-rprx-splice了，新版vision还不稳定，老是断流。

**Comment by BI7PRK** [comment]
自从10月份开始，开发决策有点乱了阵势。性能和稳定才是最核心的。

**Comment by AlvinZhu** [comment]
我觉得集成wireguard这个功能挺好，支持。
1 vision的稳定性和合并集成wireguard的pull requests是两码事，并不存在因果关系。
2 xray本来就集成了各种不同的出入站协议，一站式的整合配置确实好用。我倒不认为xray追求简洁。在xray/v2ray出现之前，shadowsocks配合iptable，dnsproxy等等一堆工具也能组合出目前的大部分功能，但是现在我觉得xray这种集成的方式更舒服。
3 关于体积，xray相对来说还是比较重量级的。16M Flash要想得到比较完整的功能体验，本来要用也是放内存盘或者额外插U盘，再加上gesite geoip体积也很大，多这1M不会有本质区别。
4 薅warp羊毛是薅，薅cdn羊毛不是薅吗？为啥不把tls+ws的支持去掉？
xray功能很多，有些功能总有人是需要的，某个功能自己不需要就提议去掉这种做法我觉得不合适
感谢社区提供这么优秀的工具。

**Comment by reeceyng** [comment]
xray创立之初的特色我记得是“超集”吧

**Comment by chika0801** [comment]
> xray创立之初的特色我记得是“超集”吧

Project X 的群聊

交流群可在底线之上随便水，不要撕逼，没有滥权。
有问题尽管随便问，知道的尽量回答。
禁政治，禁NSFW



Xray 是 v2ray 的超集，含更好的整体性能和 XTLS 等一系列增强，且完全兼容 v2ray-core 的功能及配置。

“配置兼容，整体更好”

Channel：https://t.me/projectXtls

https://github.com/XTLS

**Comment by binbooly** [comment]
> 1 1.6.5 的wireguard出口可以用指定ip或者ipv4/v6的warp出口即可，为什么要新增实体？
> 
> 2 warp这种方式已经被用烂了，并且近期开始现warp断开的情况。之前这个排错了半天以为是梯子的问题，最后发现是warp的出口自动断了，后来换了其他的脚本刷ip才能正常，虽然依旧会出现偶尔断开的情况。
> 
> 用这个本身就是在薅其他服务的基础上进行的加持为何要出现核心版本上，况且这也增加了代码量，另外就算核心不增加此功能，当前也已经可以用自带路由表的方式实现一样的功能，感谢开发者们的努力，但极致、简洁同时性能爆表的特性才是xray才应该有的,显然支持薅warp是不需要的！
> 
> 纯讨论 无其他，再次感谢大佬们给我们带来这么棒的工具！

很赞赏这位朋友的总结：专注核心功能，极致、简洁同时性能爆表的 xray。如果包揽全部功能，但又做的不够极致，总感觉就是一个玩玩就行不能当真的玩具。目前升级使用到了 1.5.4，一年多以后感觉 Xray 还不错，只是近期突然开始被封端口了...，又想念起了 Trojan，稳如老狗...

**Comment by Felix2yu** [comment]
V2ray本身定位就类似于瑞士军刀，有一堆入站、出站、代理、传输协议可供搭配组合。
理论上跟别的工具一样只要做好你自己的VMess协议就好了，干嘛不务正业去支持SS、Trojan、VLESS这些。V2ray、Xray从设计之初就不是一个小而美的极简工具。

**Comment by cross-hello** [comment]
Did you use UTLS? The releate feature only mature after 1.6.+

----------------------------------------

*From: *binbooly ***@***.***>
*To: *XTLS/Xray-core ***@***.***>
*CC: *Subscribed ***@***.***>
*Date: *Nov 30, 2022 16:43:36
*Subject: *Re: [XTLS/Xray-core] 1.6.5版本的新增的wireguard是否有必要 (Issue #1390)

**Comment by Rangtian** [comment]
> 我用的是硬路由，而且是自己编译的 OpenWRT，所以 xray 的版本升级很麻烦，目前 1.5.4 还不错。其实对于我来说，稳是第一要素，其次是速度够快，多数时候不会逼迫自己去使用一些新的功能。可能是因为我是自用的原因，如果提供商业服务的话，可能需要更多的功能兼容更多的用户需求。

flippy 编译的 Openwrt支持手动升级 xray，很方便。应该是有相关插件的，你研究看看。

![image](https://user-images.githubusercontent.com/22640407/204950423-6bdbbc41-f2c2-412a-aac3-2280da8c5c14.png)

**Comment by ixxmu** [comment]
> > 1 1.6.5 的wireguard出口可以用指定ip或者ipv4/v6的warp出口即可，为什么要新增实体？
> > 2 warp这种方式已经被用烂了，并且近期开始现warp断开的情况。之前这个排错了半天以为是梯子的问题，最后发现是warp的出口自动断了，后来换了其他的脚本刷ip才能正常，虽然依旧会出现偶尔断开的情况。
> > 用这个本身就是在薅其他服务的基础上进行的加持为何要出现核心版本上，况且这也增加了代码量，另外就算核心不增加此功能，当前也已经可以用自带路由表的方式实现一样的功能，感谢开发者们的努力，但极致、简洁同时性能爆表的特性才是xray才应该有的,显然支持薅warp是不需要的！
> > 纯讨论 无其他，再次感谢大佬们给我们带来这么棒的工具！
> 
> 很赞赏这位朋友的总结：专注核心功能，极致、简洁同时性能爆表的 xray。如果包揽全部功能，但又做的不够极致，总感觉就是一个玩玩就行不能当真的玩具。目前升级使用到了 1.5.4，一年多以后感觉 Xray 还不错，只是近期突然开始被封端口了...，又想念起了 Trojan，稳如老狗...

如果坚持使用老版本，用支持utls的客户端即可，路由器上 ssr+ 一直都支持，Android上v2rayNG也是一直支持的； 如果更新到了1.6.1之后，可以继续使用支持utls的xtls系列协议了

**Comment by hax0r31337** [comment]
> 用这个本身就是在薅其他服务的基础上进行的加持为何要出现核心版本上

wireguard协议不是只有warp在用，这个功能也可以用在其他wireguard协议的VPN服务上，比如 [ProtonVPN](https://protonvpn.com/support/wireguard-configurations/)，这家服务商允许用户导出wireguard配置文件

**Comment by thank243** [comment]
wireguard proto is not only use on warp. You can bypass the firewall to your home under NAT.

**Comment by IRN-Kawakaze** [comment]
各平台的WireGuard官方客户端对分流的支持不太好，只支持AllowedIps这一种方式，在Windows平台上，大量的AllowedIps甚至可能会导致故障。Xray支持WireGuard出站可以非常有效地改善这一现状，有望成为一个优秀的WireGuard客户端以及wg2proxy工具。

至于WARP？官方已经在逐步封禁非官方客户端，并且Xray目前不支持修改数据包的wg.reserved字段，导致它在很多热门地区无法连接上WARP，它不是一个合适的WARP客户端。

**Comment by ZqinKing** [comment]
> 

升级麻烦？你用的是ssrplus吧。只有ssrplus升级麻烦，因为他把xray给重命名了。

**Comment by mirror1342** [comment]
> 各平台的WireGuard官方客户端对分流的支持不太好，只支持AllowedIps这一种方式，在Windows平台上，大量的AllowedIps甚至可能会导致故障。Xray支持WireGuard出站可以非常有效地改善这一现状，有望成为一个优秀的WireGuard客户端以及wg2proxy工具。
> 
> 至于WARP？官方已经在逐步封禁非官方客户端，并且Xray目前不支持修改数据包的wg.reserved字段，导致它在很多热门地区无法连接上WARP，它不是一个合适的WARP客户端。

我手头的VPS，至少有一半连不上warp出站，能连上的速度也就30m

**Comment by chika0801** [comment]
> 给人的感觉就是继承了国内软件公司的风气，啥都想往里塞，变成一个水桶

倒不是什么向里面塞，WireGuard对这平台真有用

**Comment by csryt** [comment]
@GiteeWaste 对于不受自己掌握的东西，且未付费的情况下，个人觉得吐槽不合适。建议可以。

**Comment by csryt** [comment]
@pvqogw 这就很完美！

**Comment by hqvv** [comment]
> Wireguard 要把 gvisor 那一坨绑上确实是大了好多，不过要把它去掉倒是也很简单，删几个文件几行代码就行了

恳请大神搞一个精简版的分支，比如只包含Vision 和 reality的极精简版本。
或者给个实例代码 告知如何精简掉某个模块，感谢

**Comment by yichya** [comment]
> 或者给个实例代码 告知如何精简掉某个模块，感谢

https://github.com/yichya/Xray-core/tree/expvar_dns

**Comment by chika0801** [comment]
> > Wireguard 要把 gvisor 那一坨绑上确实是大了好多，不过要把它去掉倒是也很简单，删几个文件几行代码就行了
> 
> 恳请大神搞一个精简版的分支，比如只包含Vision 和 reality的极精简版本。 或者给个实例代码 告知如何精简掉某个模块，感谢

没这样的分支

**Comment by hqvv** [comment]
> > 或者给个实例代码 告知如何精简掉某个模块，感谢
> 
> https://github.com/yichya/Xray-core/tree/expvar_dns
> 
> （仅供参考，不做 release，不打算 pr，不保证兼容性，不要直接拿来用

感激不尽！ 我先fork一份 学习学习

**Comment by hqvv** [comment]
> > 或者给个实例代码 告知如何精简掉某个模块，感谢
> 
> https://github.com/yichya/Xray-core/tree/expvar_dns
> 
> （仅供参考，不做 release，不打算 pr，不保证兼容性，不要直接拿来用

测试过了 可以用，真心感谢 @yichya

编译后可执行文件变小了 1.5M。 对16M flash的老路由非常友好了。
另外感觉内存和CPU占用也都变低了:  用vision 流控, AR9344的芯片，平时约5% CPU占用，刚启动时也不会超过60%，已经非常理想了。在Xray换新的协议前，我应该不会再更新版本了 。

感谢大神挽救了我的随身小路由，谢谢！

**Comment by flintt** [comment]
> > > 或者给个实例代码 告知如何精简掉某个模块，感谢
> > 
> > 
> > https://github.com/yichya/Xray-core/tree/expvar_dns
> > （仅供参考，不做 release，不打算 pr，不保证兼容性，不要直接拿来用
> 
> 测试过了 可以用，真心感谢 @yichya
> 
> 编译后可执行文件变小了 1.5M。 对16M flash的老路由非常友好了。 另外感觉内存和CPU占用也都变低了: 用vision 流控, AR9344的芯片，平时约5% CPU占用，刚启动时也不会超过60%，已经非常理想了。在Xray换新的协议前，我应该不会再更新版本了 。
> 
> 感谢大神挽救了我的随身小路由，谢谢！

请问ar9344用的是mips哪个版本？我试了mips32和mips32le，运行都报错

**Comment by hqvv** [comment]
> 请问ar9344用的是mips哪个版本？我试了mips32和mips32le，运行都报错

直接编译的，不是很确定具体啥 arch
