### ISSUE TITLE
I can't connect to github ,how to solve?

### ISSUE THREAD

**Issue by xuanlanlinghun** [XTLS/Xray-core#1393]
wget -P /root -N --no-check-certificate "https://raw.githubusercontent.com/mack-a/v2ray-agent/master/install.sh" && chmod 700 /root/install.sh && /root/install.sh
--2022-11-30 20:47:31--  https://raw.githubusercontent.com/mack-a/v2ray-agent/master/install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-11-30 20:47:31 ERROR 404: Not Found.

**Comment by FranzKafkaYu** [comment]
@xuanlanlinghun seriously？

**Comment by xuanlanlinghun** [comment]
help me! I can't run xray! How to bring up the panel

**Comment by FranzKafkaYu** [comment]
> help me! I can't run xray! How to bring up the panel

@xuanlanlinghun The author has deleted this script,so you can't use wget to download it any more.

**Comment by xuanlanlinghun** [comment]
OK，thank you!

**Comment by xuanlanlinghun** [comment]
The script should be in the vps already, do you know the command to run xray?

**Comment by xuanlanlinghun** [comment]
ok, thank you!

**Comment by chika0801** [comment]
> ok, thank you!

https://github.com/reeceyng/v2ray-agent/
