### ISSUE TITLE
硬路由 OpenWRT SSRPlus VLESS XTLS TCP 的组合最近怎么决被封端口

### ISSUE THREAD

**Issue by binbooly** [XTLS/Xray-core#1394]
硬路由 OpenWRT SSRPlus VLESS XTLS TCP 的组合，之前一年多一直用着很稳定，可就从今年国庆节那几天开始，总是被封端口，换了 IP 后最多撑1个月不到就又被封。今天又被封端口，已经把 XTLS 换成了 TLS，试段时间看。
大家都用什么方式？

**Comment by binbooly** [comment]
![1](https://user-images.githubusercontent.com/65035816/204854434-6b9acca8-4204-4a7c-bf20-c20b87c222d9.png)
![2](https://user-images.githubusercontent.com/65035816/204854448-40f06c6d-062f-4896-ab4e-44ecb5fea087.png)

**Comment by BI7PRK** [comment]
VLESS+TLS 服务端禁止回来。客户端开启uTLS，有两个关键点：
- 服务端禁止回访
- 客户端开启 uTLS

**Comment by binbooly** [comment]
> VLESS+TLS 服务端禁止回来。客户端开启uTLS，有两个关键点：
> 
> * 服务端禁止回访
> * 客户端开启 uTLS

服务端禁止回访，这个怎么配置可以点拨一下吗？

**Comment by cross-hello** [comment]
Maybe could effect if set the configuration in server.

    {
        "domain": [
          "geosite:cn"
        ],
        //"outboundTag": "bypass",
        "outboundTag": "block",
        "type": "field"
      },
       {
        "type": "field",
        "outboundTag": "block",
        "ip": [
          "geoip:cn"
        ],
        "enabled": true
      }

----------------------------------------

*From: *binbooly ***@***.***>
*To: *XTLS/Xray-core ***@***.***>
*CC: *Subscribed ***@***.***>
*Date: *Dec 1, 2022 07:03:58
*Subject: *Re: [XTLS/Xray-core] 硬路由 OpenWRT SSRPlus VLESS XTLS TCP 
的组合最近怎么决被封端口 (Issue #1394)

> VLESS+TLS 服务端禁止回来。客户端开启uTLS，有两个关键点：
>
* > 服务端禁止回访
* > 客户端开启 uTLS

**Comment by cross-hello** [comment]
Before the two rules, append one rule allow your ip in outbound. 
Otherwise server may refuse send packets to you if you sit in the 
country.

----------------------------------------

*From: *Nanyu ***@***.***>
*To: *XTLS/Xray-core ***@***.***>
*CC: *Nanyu ***@***.***>; Your activity 
***@***.***>
*Date: *Dec 1, 2022 11:00:13
*Subject: *Re: [XTLS/Xray-core] 硬路由 OpenWRT SSRPlus VLESS XTLS TCP 
的组合最近怎么决被封端口 (Issue #1394)

**Comment by shenlijun** [comment]
尝试下naiveproxy？

**Comment by binbooly** [comment]
暂时在客户端设置了只允许被墙的域名和 IP 走代理，其它域名和IP全都直连。这样先观察一下，如果再被封端口下一步就添加服务端 cn 到 blackhole 的 outboundTag。

这两天了解了一下原因，有说是 TLS Client Hello 的原因，有说是 ARM AES 加密被破的原因，有说是流量过大的原因。我打算结合我自已的使用情况具体排查一下原因。

目前从大家的讨论中看出来 Naive Proxy & hysteria  & TUIC 均能正常使用，抽空也搭个新梯子备用。
