### ISSUE TITLE
[疑问]"proxySettings":{"tag":""} 与 "sockopt":{"dialerProxy":""} 的区别？

### ISSUE THREAD

**Issue by enterusernamecontinue** [XTLS/Xray-core#1395]
如题，平时都是使用前者来实现套娃。

但是，前几天看到发布页里《[通过 Cloudflare Warp 增强代理安全性](https://xtls.github.io/Xray-docs-next/document/level-2/warp.html#%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8-warp-%E9%93%BE%E5%BC%8F%E4%BB%A3%E7%90%86)》中描述的“客户端使用 warp 链式代理”配置：
```
{
    "outbounds": [
        {
            ... ...
            "tag": "proxy1"
        },
        {
            "protocol": "wireguard",
            "settings": {
                "secretKey": "我的私钥",
                "peers": [
                    {
                        "publicKey": "Warp公钥",
                        "endpoint": "engage.cloudflareclient.com:2408"
                    }
                ]
            },
            "streamSettings": {
                "sockopt": {
                    "dialerProxy": "proxy1"
                }
            },
            "tag": "proxy2"
        }
    ]
}
```
想知道使用 `"sockopt":{"dialerProxy":""}` 与 "proxySettings":{"tag":""} 的原理区别，望解答，感谢。
```
{
    "outbounds": [
        {
            ... ...
            "tag": "proxy1"
        },
        {
            "protocol": "wireguard",
            "settings": {
                "secretKey": "我的私钥",
                "peers": [
                    {
                        "publicKey": "Warp公钥",
                        "endpoint": "engage.cloudflareclient.com:2408"
                    }
                ]
            },
            "proxySettings": {
                "tag": "proxy1",
                "transportLayer": true
            },
            "tag": "proxy2"
        }
    ]
}
```

**Comment by enterusernamecontinue** [comment]
实际使用过程中，同样的 proxy 和 outfall 出站配置，使用“链式转发”比“出站代理”的 CPU 开销要大一点。

“出站代理” client.json
```
{
    "outbounds": [
        {
            "streamSettings": {
                "network": "tcp"
            },
            "tag": "proxy"
        },
        {
            "streamSettings": {
                "network": "tcp"
            },
            "proxySettings": {
                "tag": "iplc",
                "transportLayer": true
            },
            "tag": "outfall"
        }
    ]
}
```

“链式转发” client.json
```
{
    "outbounds": [
        {
            "streamSettings": {
                "network": "tcp"
            },
            "tag": "proxy"
        },
        {
            "streamSettings": {
                "network": "tcp",
                "sockopt": {
                    "dialerProxy": "proxy"
                }
            },
            "tag": "outfall"
        }
    ]
}
```

请问，一般分别是什么场景下推荐使用“出站代理”或“链式转发”？

**Comment by rui0572** [comment]
根据[此处](https://github.com/XTLS/Xray-core/blob/main/infra/conf/xray.go#L321)的代码，

```
            "proxySettings": {
                "tag": "iplc",
                "transportLayer": true
            },
```

与

```
            "streamSettings": {
                "sockopt": {
                    "dialerProxy": "iplc"
                }
            },
```

是等效的。

**Comment by chika0801** [comment]
一般自建的群友都用不上。你硬要说用，比如你买了机场，也有一个不好线路的vps，就链式代理，通过 你 到 机场 vps，机场vps访问你的vps，机场就只知道，你的ip，你只访问了你vps的ip。

那为什么不直接买有回程优化的vps了。

**Comment by enterusernamecontinue** [comment]
<details> <summary>Quote</summary>
> 根据[此处](https://github.com/XTLS/Xray-core/blob/main/infra/conf/xray.go#L321)的代码，
> 
> ```
>             "proxySettings": {
>                 "tag": "proxy",
>                 "transportLayer": true
>             },
> ```
> 
> 与
> 
> ```
>             "streamSettings": {
>                 "sockopt": {
>                     "dialerProxy": "proxy"
>                 }
>             },
> ```
> 
> 是等效的。
</details>

@rui0572 感谢回复。

我在测试过程中，发现使用 `{"proxySettings":{"tag":""}}` 比 `{"streamSettings":{"sockopt":{"dialerProxy":""}}}` 的 CPU 开销确实要小一点。

如果两者是等效，那但凡需要代理出站时，直接“无脑”使用 `{"proxySettings":{"tag":""}}` 可否？（本人非 Coder ，判读有困难，抱歉。）

**Comment by enterusernamecontinue** [comment]
### 
> 一般自建的群友都用不上。你硬要说用，比如你买了机场，也有一个不好线路的vps，就链式代理，通过 你 到 机场 vps，机场vps访问你的vps，机场就只知道，你的ip，你只访问了你vps的ip。
> 
> 那为什么不直接买有回程优化的vps了。
### 

@chika0801 感谢回复。

可能是我没表达清楚，我明白出站代理的用途，我是想了解——在什么情形下选择使用 `{"proxySettings":{"tag":""}}` ，另外又在什么情形下选择使用 `{"streamSettings":{"sockopt":{"dialerProxy":""}}}` 。

**Comment by rui0572** [comment]
> 如果两者是等效

注意，需要设置 `"transportLayer": true` 二者才是等效的。

如果只是 `{"proxySettings":{"tag":""}}`，你测到 CPU 开销较小可能是因为其[不经过“底层传输方式”](https://xtls.github.io/config/outbound.html#proxysettingsobject)。

**Comment by enterusernamecontinue** [comment]
> > 如果两者是等效
> 
> 注意，需要设置 `"transportLayer": true` 二者才是等效的。
> 
> 如果只是 `{"proxySettings":{"tag":""}}`，你测到 CPU 开销较小可能是因为其[不经过“底层传输方式”](https://xtls.github.io/config/outbound.html#proxysettingsobject)。

明白，谢谢。

**Comment by Sdator** [comment]
> > 如果两者是等效
> 
> 注意，需要设置 `"transportLayer": true` 二者才是等效的。
> 
> 如果只是 `{"proxySettings":{"tag":""}}`，你测到 CPU 开销较小可能是因为其[不经过“底层传输方式”](https://xtls.github.io/config/outbound.html#proxysettingsobject)。

你好，请问这里的不经过“底层传输方式”应该怎样理解？哪种链式代理情况下需要使用“底层传输方式”，又或什么情况下不需要使用？
