### ISSUE TITLE
  "balancerTag": "balancer" 字段不工作？

### ISSUE THREAD

**Issue by Fhokud** [XTLS/Xray-core#1398]
{
  "type": "field",
  "network": "tcp",
 "inboundTag": ["socks"],
  "balancerTag": "balancer"
},
{
  "type": "field",
  "network": "udp",
"outboundTag": "proxy-sg"
}
    ],
      "balancingRule":[
       {
      "tag": "balancer",
      "selector": ["proxy"]
      }
    ]
  }
}

问题出在  "balancerTag": "balancer"上，按照文档这些字段没有任何问题。
但是我只要添加了  "balancerTag": "balancer"

会输出错误
Failed to start: main: failed to create server > app/router: this rule has no effective fields

请大佬解惑

**Comment by chika0801** [comment]
这功能很少有人用，建议不用得了

**Comment by azzvx** [comment]
你是从什么奇奇怪怪的地方看来的配置，字段名都是错的。
```
"routing": {
    "balancers": [{ "tag": "proxy", "selector": ["vps-ws"] }],
    "rules": [
      {
        "type": "field",
        "inboundTag": ["tproxy-in"],
        "domains": ["geosite:gfw", "geosite:greatfire"],
        "balancerTag": "proxy"
      }
    ]
  }
```

**Comment by Fhokud** [comment]
> 
怪不得😂

**Comment by Fhokud** [comment]
> 你是从什么奇奇怪怪的地方看来的配置，字段名都是错的。
> 
> ```
> "routing": {
>     "balancers": [{ "tag": "proxy", "selector": ["vps-ws"] }],
>     "rules": [
>       {
>         "type": "field",
>         "inboundTag": ["tproxy-in"],
>         "domains": ["geosite:gfw", "geosite:greatfire"],
>         "balancerTag": "proxy"
>       }
>     ]
>   }
> ```

感谢
