### ISSUE TITLE
README内容补充请求

### ISSUE THREAD

**Issue by ChanthMiao** [XTLS/Xray-core#140]
最近因为一些原因对xray进行断点调试。我不是很熟悉go的编译选项，不过实际操作下来发现，想要正常地通过dlv工具进行断点调试的话，需要注意一下编译选项（得带上debug info）。`go build -o xray.exe -gcflags="all=-N -l"  -ldflags " -buildid=" ./main`生成的binary才可以正常打断点。请求在REAME加上这一注意事项。

**Comment by badO1a5A90** [comment]
也可以加入到文档网站

**Comment by badO1a5A90** [comment]
编译可以进行debug的程序,即可以用dlv附加到运行的程序进行调试.
关键的编译选项在于:
**不使用** ldflags 中的 '-w -s' 选项.

说明：
-w 禁止生成debug信息,注意使用该选项后，无法使用 gdb 进行调试
-s 禁用符号表

PS:其实用vscode调试似乎更方便.

**Comment by badO1a5A90** [comment]
已加入文档 https://xtls.github.io/develop/intro/compile/#%E6%89%8B%E5%B7%A5%E7%BC%96%E8%AF%91

**Comment by ChanthMiao** [comment]
> 已加入文档 https://xtls.github.io/develop/intro/compile/#%E6%89%8B%E5%B7%A5%E7%BC%96%E8%AF%91

神速啊。
PS，我就是vsc调试的，vsc的golang调试依赖dlv，故障排除还得多谢vsc的golang插件文档。
