### ISSUE TITLE
What are the security risks of not using XTLS with VLESS?

### ISSUE THREAD

**Issue by iranxray** [XTLS/Xray-core#1400]
Right now, in Iran, we see that VLESS without XTLS performs really good. So, we were wondering what the security risks are for the user and the server owner. Does GFW detect VLESS traffic without XTLS? Does it endanger users even if the underlying app (Twitter, WhatsApp, Instagram, etc) uses HTTPS?

**Comment by chika0801** [comment]
在中国从10月3日开始的封锁，和”供应商“的报料。

目前已知有 TLS in TLS 检测，uTLS 检测，客户端/服务器端AES加密流检测。这些信息来自 https://github.com/net4people/bbs/issues/129#issuecomment-1266617327 ，有的报料原作者已删除，有网友保存了。

如果你遇到问题，你应该尝试

XTLS VISION（TCP）
https://github.com/chika0801/Xray-examples/tree/main/VLESS-TCP-XTLS-Vision

Hysteria（UDP）
https://github.com/chika0801/hysteria-install

TUIC（UDP）
https://github.com/chika0801/tuic-install

**Comment by chika0801** [comment]
或关注此项目 https://github.com/XTLS/Xray-core/issues/1397

**Comment by yuhan6665** [comment]
Answered
