### ISSUE TITLE
透明代理环境中，对于Cloudflare的dns服务器1.1.1.1来说，看到的是我国内客户端的ip还是国外服务端vps的ip？

### ISSUE THREAD

**Issue by GeorgeRudd** [XTLS/Xray-core#1407]
https://blog.skk.moe/post/what-happend-to-dns-in-proxy/ 
这篇文章说 在透明代理模式下，不论是否需要 IP 规则分流都需要先进行一次 DNS 解析才能建立连接。

https://tachyondevel.medium.com/%E6%BC%AB%E8%B0%88%E5%90%84%E7%A7%8D%E9%BB%91%E7%A7%91%E6%8A%80%E5%BC%8F-dns-%E6%8A%80%E6%9C%AF%E5%9C%A8%E4%BB%A3%E7%90%86%E7%8E%AF%E5%A2%83%E4%B8%AD%E7%9A%84%E5%BA%94%E7%94%A8-62c50e58cbd0
这篇文章说 从我们机器发出去的一个 DNS 请求会是这个样子的：
+------+-------+--------------------------+
| IP 头| UDP 头 | DNS 头 及 其 请 求 内 容  |
+------+-------+--------------------------+

客户端配置了V2Ray DNS Outbound 来劫持dns，此时访问 google.com ，对于Cloudflare的dns服务器1.1.1.1来说，看到的是我国内客户端的ip还是国外服务端vps的ip？（因为开启了routeOnly所以不用考虑服务端）

**Comment by yuhan6665** [comment]
一般代理情况服务器只能看到VPS IP
