### ISSUE TITLE
High CPU Usage 1.6.5

### ISSUE THREAD

**Issue by deathline94** [XTLS/Xray-core#1411]
Hey . the title is self-explanatory . basically for the past couple of days cpu constantly spikes to 99% usage and goes back down
a little and goes back up . the process responsible for that high cpu usage is "xray-linux-amd6" according to Top .
now , of course , i didnt change anything recently and i've been running my server for couple of month now without any problems.
this started only from 2 days ago . i was wondering if anybody else has this problem or is there a solution to this . Thanks

**Comment by curkan** [comment]
Hello, how did you solve this problem? I have the same

**Comment by soda120new** [comment]
I found solution
Tested and working

Telegram : @soda120
Email : soda120@gmail.com

**Comment by FSystem88** [comment]
The whole problem lies in the WireGuard protocol, which was developed under Xray. Maybe it'll help you. It's better not to create WGs, but to transfer them to your own pure WireGuard.
