### ISSUE TITLE
底层协议使用h2时会有阻塞的情况

### ISSUE THREAD

**Issue by f0re1gnKey** [XTLS/Xray-core#1418]
历史悠久的问题，任何加密协议搭配h2都会有这种情况

**Comment by wenzhuning** [comment]
这种是tcp层面的阻塞，跟mux一样，无法解决，一般是丢包导致的，线路越差越可能阻塞，可以尝试把connIdle设置为2，这样当阻塞超过2秒就会重新请求，可以缓解阻塞感知
