### ISSUE TITLE
any example to change request methode from GET to Anyone ?

### ISSUE THREAD

**Issue by xkjdox** [XTLS/Xray-core#1419]
please answer me

**Comment by cross-hello** [comment]
Do you mean api of *ray?
Don't know, never provoke before.
But may be future need to find a time to have a play.

----------------------------------------

*From: *xkjdox ***@***.***>
*To: *XTLS/Xray-core ***@***.***>
*CC: *Subscribed ***@***.***>
*Date: *Dec 9, 2022 11:37:44
*Subject: *[XTLS/Xray-core] any example to change request methode from 
GET to Anyone ? (Issue #1419)

**Comment by yuhan6665** [comment]
Closing as invalid. If you want to re-open, please provide more details
