### ISSUE TITLE
开着系统代理会不会影响直连流量？

### ISSUE THREAD

**Issue by DiritoTech** [XTLS/Xray-core#1423]
客户端Xray设置http入站设置，并在windows系统代理中启用后
![tmp280A](https://user-images.githubusercontent.com/96611541/206882463-42dc9c95-0aea-4683-9c56-801570a91033.png)

那些以“直连”形式出站的流量，它们的属性是否和不开启xray和系统代理 时相同呢？

例如一个udp直连流量，流入不支持udp的http系统代理后，再以直连的方式出站，这个过程是否会失去udp属性？

**Comment by Fangliding** [comment]
不会 udp根本不会走这玩意
