### ISSUE TITLE
游戏王长时间转圈圈问题

### ISSUE THREAD

**Issue by jzjohn789** [XTLS/Xray-core#1424]
和这位大佬的问题一样
https://github.com/XTLS/Xray-core/issues/482
只要客户端不用VPN模式，就可以正常用，然后我看了下日志
2种模式的地址都一样，完全看不出是哪里出的问题，有没有哪位大哥遇到一样的问题呢？

**Comment by Fangliding** [comment]
似乎没有大哥遇到一样的问题（）
