### ISSUE TITLE
服务端崩溃

### ISSUE THREAD

**Issue by paul13579** [XTLS/Xray-core#143]
版本：1.2.0

panic: runtime error: slice bounds out of range [28:0]
goroutine 142478 [running]:
github.com/xtls/xray-core/common/buf.(*Buffer).Read(...)
        github.com/xtls/xray-core/common/buf/buffer.go:186
github.com/xtls/xray-core/common/buf.SplitBytes(0xc001496218, 0x1, 0x1, 0xc0072a0000, 0x24, 0x2000, 0x0, 0x2, 0x203001, 0x203001)
        github.com/xtls/xray-core/common/buf/multi_buffer.go:105 +0x2e6
github.com/xtls/xray-core/common/buf.(*BufferedReader).Read(0xc00409e9c0, 0xc0072a0000, 0x24, 0x2000, 0xc00004cbf8, 0x7f090091e9c8, 0x28)
        github.com/xtls/xray-core/common/buf/reader.go:68 +0x223
io.ReadAtLeast(0x10a5d20, 0xc00409e9c0, 0xc0072a0000, 0x24, 0x2000, 0x24, 0x40fd38, 0x30, 0xed7020)
        io/io.go:314 +0x87
io.ReadFull(...)
        io/io.go:333
github.com/xtls/xray-core/common/buf.(*Buffer).ReadFullFrom(0xc00437dc20, 0x10a5d20, 0xc00409e9c0, 0xc000000024, 0x2, 0x2, 0x2)
        github.com/xtls/xray-core/common/buf/buffer.go:209 +0xab
github.com/xtls/xray-core/proxy/vless/encoding.(*LengthPacketReader).ReadMultiBuffer(0xc00437dbf0, 0x20, 0xe6e680, 0xc00139c8e0, 0xc004221fc0, 0xc00004cdd0)
        github.com/xtls/xray-core/proxy/vless/encoding/addons.go:181 +0x209
github.com/xtls/xray-core/common/buf.copyInternal(0x10a69a0, 0xc00437dbf0, 0x10a51c0, 0xc0042f3920, 0xc004221fa0, 0xb7d801, 0xc004221f80)
        github.com/xtls/xray-core/common/buf/copy.go:81 +0x49
github.com/xtls/xray-core/common/buf.Copy(0x10a69a0, 0xc00437dbf0, 0x10a51c0, 0xc0042f3920, 0xc00004cf38, 0x1, 0x1, 0x10a5cc0, 0xc004272690)
        github.com/xtls/xray-core/common/buf/copy.go:104 +0xa8
github.com/xtls/xray-core/proxy/vless/inbound.(*Handler).Process.func4(0x0, 0x0)
        github.com/xtls/xray-core/proxy/vless/inbound/inbound.go:463 +0x405
github.com/xtls/xray-core/common/task.OnSuccess.func1(0x0, 0x0)
        github.com/xtls/xray-core/common/task/task.go:12 +0x2f
github.com/xtls/xray-core/common/task.Run.func1(0xc001496268, 0xc005462f60, 0xc0042f39a0)
        github.com/xtls/xray-core/common/task/task.go:28 +0x2b
created by github.com/xtls/xray-core/common/task.Run
        github.com/xtls/xray-core/common/task/task.go:27 +0xdc

panic: crypto/cipher: invalid buffer overlap
goroutine 704452 [running]:
crypto/aes.(*gcmAsm).Seal(0xc0032952c0, 0xc00125c002, 0x0, 0x1ffe, 0xc002508a70, 0xc, 0x10, 0xc00125c000, 0x518, 0x2000, ...)
        crypto/aes/aes_gcm.go:125 +0x4cd
github.com/xtls/xray-core/common/crypto.(*AEADAuthenticator).Seal(0xc003c18d60, 0xc00125c002, 0x0, 0x1ffe, 0xc00125c000, 0x518, 0x2000, 0x2000, 0xc001d05b50, 0x70c638, ...)
        github.com/xtls/xray-core/common/crypto/auth.go:82 +0x13d
github.com/xtls/xray-core/common/crypto.(*AuthenticationWriter).seal(0xc001bd8c30, 0xc00125c000, 0x518, 0x2000, 0x1ad6, 0x2000, 0xc00152f6e8)
        github.com/xtls/xray-core/common/crypto/auth.go:259 +0x3b3
github.com/xtls/xray-core/common/crypto.(*AuthenticationWriter).writeStream(0xc001bd8c30, 0xc00152f6e8, 0x1, 0x1, 0x0, 0x0)
        github.com/xtls/xray-core/common/crypto/auth.go:292 +0x32c
github.com/xtls/xray-core/common/crypto.(*AuthenticationWriter).WriteMultiBuffer(0xc001bd8c30, 0xc00152f6e8, 0x1, 0x1, 0x0, 0x0)
        github.com/xtls/xray-core/common/crypto/auth.go:341 +0x85
github.com/xtls/xray-core/common/buf.copyInternal(0x10a71c0, 0xc002ce6de8, 0x10a5e80, 0xc001bd8c30, 0xc003b87c40, 0xc003c88801, 0xc003b87c20)
        github.com/xtls/xray-core/common/buf/copy.go:87 +0x19e
github.com/xtls/xray-core/common/buf.Copy(0x10a71c0, 0xc002ce6de8, 0x10a5e80, 0xc001bd8c30, 0xc001d05e48, 0x1, 0x1, 0x40fd38, 0x30)
        github.com/xtls/xray-core/common/buf/copy.go:104 +0xa8
github.com/xtls/xray-core/proxy/vmess/inbound.transferResponse(0x10a62a0, 0xc003c886f0, 0xc003ef10a0, 0xc003c885a0, 0xc0003ec740, 0x10a71c0, 0xc002ce6de8, 0xc003c88810, 0x1, 0xc0003ec768)
        github.com/xtls/xray-core/proxy/vmess/inbound/inbound.go:200 +0x1a6
github.com/xtls/xray-core/proxy/vmess/inbound.(*Handler).Process.func2(0x0, 0x0)
        github.com/xtls/xray-core/proxy/vmess/inbound/inbound.go:326 +0x326
github.com/xtls/xray-core/common/task.Run.func1(0xc002ce6df8, 0xc001e0bb00, 0xc002dac800)
        github.com/xtls/xray-core/common/task/task.go:28 +0x2b
created by github.com/xtls/xray-core/common/task.Run
        github.com/xtls/xray-core/common/task/task.go:27 +0xdc

**Comment by rprx** [comment]
看起来是两个独立的 panic，这是用来做什么了

**Comment by paul13579** [comment]
具体场景我也不清楚，因为不是只有自己在用，是看了下日志发现的问题

**Comment by rprx** [comment]
上面的 panic 我可以研究一下规避，下面的目前不太熟悉

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/issues/1501#issuecomment-1375293435
