### ISSUE TITLE
现在vision是否还不支持前置代理？

### ISSUE THREAD

**Issue by tianlichunhong** [XTLS/Xray-core#1430]
我用的最新版，xray 1.6.6，配置了前置代理，发现不通。但是我用的v2ly的内核，同样的前置代理配置+vless是可以的。是xray不支持前置代理，还是说vision目前不支持前置代理？有大佬指导一下吗？谢谢！

**Comment by ELXIAGHT** [comment]
这个issue，可能对你有参考。#1339

**Comment by tianlichunhong** [comment]
> 这个issue，可能对你有参考。#1339

这个不是我说的前置代理。是这个前置代理 https://guide.v2fly.org/app/parent.html#%E5%AE%A2%E6%88%B7%E7%AB%AF

**Comment by ELXIAGHT** [comment]
一直支持的，我自己用是没问题的。

________________________________

**Comment by lrisora** [comment]
忘了哪里看的：“用 OutboundObject 的 ProxySettingsObject 设置前置代理时 streamSettings 失效”
所以只能在有限的出站协议里使用
通用的前置代理需要借助一个dokodemo-door来重路由流量
例：
[config_client.txt](https://github.com/XTLS/Xray-core/files/10275553/config_client.txt)

此处连接clash的sock出站可更换为任意出站协议或负载均衡

**Comment by KevinMX** [comment]
> 忘了哪里看的：“用 OutboundObject 的 ProxySettingsObject 设置前置代理时 streamSettings 失效” 所以只能在有限的出站协议里使用 通用的前置代理需要借助一个dokodemo-door来重路由流量

https://xtls.github.io/config/outbound.html#proxysettingsobject

可以使用兼容 v2fly 的 transportLayer 解决这个问题。

**Comment by tianlichunhong** [comment]
> 忘了哪里看的：“用 OutboundObject 的 ProxySettingsObject 设置前置代理时 streamSettings 失效” 所以只能在有限的出站协议里使用 通用的前置代理需要借助一个dokodemo-door来重路由流量 例： [config_client.txt](https://github.com/XTLS/Xray-core/files/10275553/config_client.txt)
> 
> 此处连接clash的sock出站可更换为任意出站协议或负载均衡

你这个方式确实有效。已经在用了。真是非常感谢！

**Comment by crazypeace** [comment]
> > 忘了哪里看的：“用 OutboundObject 的 ProxySettingsObject 设置前置代理时 streamSettings 失效” 所以只能在有限的出站协议里使用 通用的前置代理需要借助一个dokodemo-door来重路由流量 例： [config_client.txt](https://github.com/XTLS/Xray-core/files/10275553/config_client.txt)
> > 此处连接clash的sock出站可更换为任意出站协议或负载均衡
> 
> 你这个方式确实有效。已经在用了。真是非常感谢！

你好, 那个做例子的 txt 文件没看懂. 那个 inbound 里面的 dokodemo-door , 浏览器怎么设置?

你自己有没有实际使用的配置文件? 能去敏了发出来让我参考参考吗?

**Comment by lrisora** [comment]
> > > 忘了哪里看的：“用 OutboundObject 的 ProxySettingsObject 设置前置代理时 streamSettings 失效” 所以只能在有限的出站协议里使用 通用的前置代理需要借助一个dokodemo-door来重路由流量 例： [config_client.txt](https://github.com/XTLS/Xray-core/files/10275553/config_client.txt)
> > > 此处连接clash的sock出站可更换为任意出站协议或负载均衡
> > 
> > 
> > 你这个方式确实有效。已经在用了。真是非常感谢！
> 
> 你好, 那个做例子的 txt 文件没看懂. 那个 inbound 里面的 dokodemo-door , 浏览器怎么设置?
> 
> 你自己有没有实际使用的配置文件? 能去敏了发出来让我参考参考吗?

浏览器直接用有注释` // v2rayN 本地监听端口`的入站(这个例子里面有一个socks5和一个http)
浏览器不使用dokodemo-door，这个是用来进行“重路由”的入栈，不应直接使用
这个已经很接近我在用的了，只有我现在用的visoin+REALITY和一些自定义路由的区别

这个原理是主Outbound原本是直接发往vps的ip:端口，
但为实现前置代理将主Outbound的address和port改为一个本机的ip:端口（此处是127.0.0.1:1760）
dokodemo-door入栈会监听这个本机的ip:端口（此处是127.0.0.1:1760），
dokodemo-door将数据包目的地改为vps的ip:端口
并用路由将dokodemo-door入栈的所有数据转发给clash出站

这样缺点是效率略低，数据包会在系统的tcp栈里面多转一圈
transportLayer 更好但REALITY好像还不支持（至少在我使用的1.8.3里面）

我选的1760端口不太好，偶尔会发生端口已被某些程序占用导致xray打不开，此时需要换个端口
直接用一个大端口可能碰撞概率要低一些
