### ISSUE TITLE
1.6.6怎么删了？

### ISSUE THREAD

**Issue by GreatMichaelLee** [XTLS/Xray-core#1432]
是有功能问题bug还是安全风险？我需要回退吗？。。。。

**Comment by hrimfaxi** [comment]
我升级了服务器，好像断流有些严重，回退了

**Comment by qianxu2001** [comment]
> vision 的 UDP 炸了 考虑了一下还是决定重新发版

不改版本号似乎官方的一键安装脚本识别不到更新（

**Comment by GreatMichaelLee** [comment]
是的，这个很烦，建议重新发布1.6.7



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月13日(周二) 下午4:20
收件人: ***@***.***&gt;;
抄送: "michael ***@***.******@***.***&gt;;
主题: Re: [XTLS/Xray-core] 1.6.6怎么删了？ (Issue #1432)




  
vision 的 UDP 炸了 考虑了一下还是决定重新发版
  
不改版本号似乎官方的一键安装脚本识别不到更新（
