### ISSUE TITLE
客户端和服务端都开启了TFO，但是实测不生效

### ISSUE THREAD

**Issue by wenzhuning** [XTLS/Xray-core#1433]
如图：

![微信截图_20221213112558](https://user-images.githubusercontent.com/113741196/207219402-9d7f4859-d314-4390-9cb5-85aa4add86e7.png)

**Comment by wenzhuning** [comment]
配置文件没问题，都是按官网文档写的
"streamSettings": {
"sockopt": {
"tcpFastOpen": true
}
}

**Comment by kckm** [comment]
TFO需要网络中间设备的支持

**Comment by xqzr** [comment]
#1291

**Comment by xqzr** [comment]
~没有适配~ Windows TFO
