### ISSUE TITLE
请问，xtls-rprx-vision,none流控是什么意思？适合什么场景？

### ISSUE THREAD

**Issue by hkbase** [XTLS/Xray-core#1434]
xray v1.6.6新版本里的(xtls-rprx-vision,none)流控是什么意思？与（xtls-rprx-vision）的区别是？麻烦知道的教一下～谢谢

**Comment by KeithXZhai** [comment]
关于vision流控的说明在这里：https://github.com/XTLS/Xray-core/discussions/1295
简单来说就是xray为了解决tls in tls问题发展出来的新方案。

**Comment by yuhan6665** [comment]
none 的意思是兼容无流控的 vless-tcp-tls

**Comment by ZqinKing** [comment]
> none 的意思是兼容无流控的 vless-tcp-tls

苹果用户表示很有用。

**Comment by loydcheung** [comment]
> none 的意思是兼容无流控的 vless-tcp-tls 

目前用1.6.6-2服务端没有配置none也能兼容vless-tcp-tls，1.6.6第一版不行。
