### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by degfw** [XTLS/Xray-core#1436]
Is it possible to [release](https://github.com/XTLS/Xray-core/releases) using [semantic versioning](https://semver.org/spec/v2.0.0.html)?

**Comment by FranzKafkaYu** [comment]
@GreatMichaelLee 不会吧，除非脚本写得不好，版本号就是获取一下tag而已。

**Comment by GreatMichaelLee** [comment]
版本号只识别x.x.x这种格式，不会识别1.6.6-2这种，所以每次检测都会说有新版本。原因是binary里读出来的还是1.6.6

**Comment by yuhan6665** [comment]
我的考虑是不想留下原1.6.6所以这么搞了
下次会注意

**Comment by jinwyp** [comment]
发布一个1.6.7吧
https://github.com/XTLS/Xray-core/issues/1441
