### ISSUE TITLE
体积优化,路由器容量优化

### ISSUE THREAD

**Issue by z826540272** [XTLS/Xray-core#144]
无论是v2ray还是xray,都越来越大
是否考虑为小容量设备优化
目前16M内存路由器可以勉强安装下v2ray,xray体积大了一些,还没测试

**Comment by rprx** [comment]
https://github.com/upx/upx/releases

**Comment by z826540272** [comment]
这个减小的体积并不大,会减慢启动速度,增加内存占用

**Comment by badO1a5A90** [comment]
这个可以压缩至大约5m。
启动速度是必须付出的代价
至于占用内存，启动静置稳定后是差不多的，实际运行占用看负载。

**Comment by z826540272** [comment]
路由器的那个只读文件系统本身也会压缩,我对比过区别,upx压缩与否固件容量的区别在500K不到1M左右

**Comment by rprx** [comment]
如上所述，如果需要在 16MB 容量的路由器上运行 Xray，建议亲自尝试 UPX，可以把 Xray 压至 5MB 左右

不觉得启动速度很重要，因为这是一次性的，而且为了达成目标，它就更不重要了

内存占用应该不会显著增加

**Comment by badO1a5A90** [comment]
16M是真的有点小啊。。。如果你会编译或许可以试着裁剪你自己需要的部分编译。看看最后能不能满足

**Comment by yichya** [comment]
其实想不 upx 也可以试试把 squashfs 的 block size 拉满，默认 256KB 开到 2MB 大概能再多剩下 1MB 左右

**Comment by z826540272** [comment]
我改成512 就和upx差不太多了

**Comment by quintus-lab** [comment]
openwrt系统里一堆应用都是upx压缩的，怎么就嫌弃xray用upx了？

**Comment by zhfish** [comment]
16M机器的cpu，能跑到50M么。。。换了吧

**Comment by z826540272** [comment]
> 16M机器的cpu，能跑到50M么。。。换了吧
> 50M都跑不到，没必要用xray吧，老老实实ss也行

原版V2可以跑到80Mbps,而且50M就够用了,足够我看4k视频.
用什么主要是机场决定的,不然我直接用SSR了

**Comment by rprx** [comment]
对于 Golang，优化二进制体积是相对麻烦且不一定能做到的事情，这个刚需也实在太少（可能不到 1%），投入产出比相差太大

目前 UPX 可以很好地解决问题，我认为应该在文档中推荐 UPX

**Comment by badO1a5A90** [comment]
已加入文档 FAQ
