### ISSUE TITLE
版本号能不能不要写成1.6.6-2

### ISSUE THREAD

**Issue by jinwyp** [XTLS/Xray-core#1441]
版本号能不能不要写成1.6.6-2 直接1.6.7不行吗？ 版本号这么随意改变， 导致很多一键脚本直接无法安装了。

打破了常规的版本规则 导致无法下载

正常都是以下这种，
https://github.com/XTLS/Xray-core/releases/download/v1.6.6/Xray-linux-64.zip

**Comment by ZqinKing** [comment]
> 版本号能不能不要写成1.6.6-2 直接1.6.7不行吗？ 版本号这么随意改变， 导致很多一键脚本直接无法安装了。
> 
> 打破了常规的版本规则 导致无法下载
> 
> 正常都是以下这种， https://github.com/XTLS/Xray-core/releases/download/v1.6.6/Xray-linux-64.zip

用https://github.com/XTLS/Xray-install.git一切正常，第三方一键脚本不兼容，自个儿改去。

**Comment by KyonCN** [comment]
> > 版本号能不能不要写成1.6.6-2 直接1.6.7不行吗？ 版本号这么随意改变， 导致很多一键脚本直接无法安装了。
> > 打破了常规的版本规则 导致无法下载
> > 正常都是以下这种， https://github.com/XTLS/Xray-core/releases/download/v1.6.6/Xray-linux-64.zip
> 
> 用[https://github.com/XTLS/Xray-install.git一切正常，第三方一键脚本不兼容，自个儿改去。](https://github.com/XTLS/Xray-install.git%E4%B8%80%E5%88%87%E6%AD%A3%E5%B8%B8%EF%BC%8C%E7%AC%AC%E4%B8%89%E6%96%B9%E4%B8%80%E9%94%AE%E8%84%9A%E6%9C%AC%E4%B8%8D%E5%85%BC%E5%AE%B9%EF%BC%8C%E8%87%AA%E4%B8%AA%E5%84%BF%E6%94%B9%E5%8E%BB%E3%80%82)

开发者自己都说下个版本会注意命名规范了，这个issue的槽点难道不是把两天前的issue又发了一遍吗？

**Comment by RPRX** [comment]
能，下次发 issue 请礼貌些。
