### ISSUE TITLE
very slow with wireguard

### ISSUE THREAD

**Issue by xhsnalii** [XTLS/Xray-core#1446]
Hi, I used wireguard pre-release, but it's very slow.
Anyone have a solution? 
My VPS is 2 Gbps, but with Wireguard pre-release it barely crosses 40 Mbps.

**Comment by ZqinKing** [comment]
> Hi, I used wireguard pre-release, but it's very slow. Anyone have a solution? My VPS is 2 Gbps, but with Wireguard pre-release it barely crosses 40 Mbps.

You can try warp + socks

**Comment by kdurov** [comment]
> You can try warp + socks

they key is not to use official warp client as it's buggy, laggy, no log settings, and even take up some ports including port 53
