### ISSUE TITLE
VLESS-TCP-XTLS-Vision 是否支持MKCP

### ISSUE THREAD

**Issue by hen1332** [XTLS/Xray-core#1450]
能正常启动，但是连接失败。outbounds是freedom。inbounds配置如下：
  	"inbounds": [
  {
        "tag":"xtls-in",
        "listen": "0.0.0.0",
        "port": 12000,
        "protocol": "vless",
        "settings": {
          "clients": [
            {
              "id": "ID", 
              "flow": "xtls-rprx-vision"
            }
          ],
          "decryption": "none",
          "fallbacks": [
            {
              "dest": 8080 
            }
          ]
        },
        "streamSettings": {
          "network": "mkcp",
          "kcpSettings": {
            "uplinkCapacity": 100,
            "downlinkCapacity": 100,
            "congestion": true,
            "readBufferSize": 4,
            "writeBufferSize": 4,
            "header": {
              "type": "none"
            },
            "seed": "srtp"
          },
          "security": "tls",
          "tlsSettings": {
            "allowInsecure": false, 
            "minVersion": "1.2", 
            "alpn": ["http/1.1"],
            "certificates": [
              {
                "certificateFile": "/home/xray_cert/xray.crt",
                "keyFile": "/home/xray_cert/xray.key"
              }
            ]
          }
        }
      }]

**Comment by RPRX** [comment]
其实，XTLS 支持 mKCP 没有意义

**Comment by RPRX** [comment]
（从抗识别的角度来说）

**Comment by hen1332** [comment]
> 回到问题，看 Vision 代码是不支持 mKCP 的

感谢解答。测试过了，MKCP和MUX都不支持，其实也不适合这样配置。学习中
