### ISSUE TITLE
SSL_ERROR_BAD_MAC_ALERT

### ISSUE THREAD

**Issue by msshn** [XTLS/Xray-core#1454]
I'm getting this error randomly when using flow: xtls-rprx-vision
usually the website loads after 1 or 2 refreshes but still annoying.
my setup is like "https://github.com/XTLS/Xray-examples/tree/main/VLESS-TCP-XTLS-Vision" example
browsers: Librewolf, Brave
this does not occur on any other config like vless+tls+ws or etc.

**Comment by GreatMichaelLee** [comment]
this is really an annoying issue, but either the developer still have no clue on addressing this issue or they don't have interests on fixing this yet. Looks like mutiple instance reported but non further fix ongoing.

**Comment by even0306** [comment]
the  same as you，hope to fix soon

**Comment by loydcheung** [comment]
it seems all the recent problems are vanished in v1.7.0, it becomes solid again!

**Comment by msshn** [comment]
Thanks to the devs for new release!
Errors reduced a lot but I still have this error here and there
I use it with nginx + fake website, maybe that's the issue

**Comment by loydcheung** [comment]
after 2 days of stable running, i got frequent errors tonight with 1.7.0. When i git pull, it returns: "fatal: unable to access 'https://github.com/coolsnowwolf/lede/': gnutls_handshake() failed: The TLS connection was non-properly terminated."

**Comment by alireza1023** [comment]
after upgrade to 1.7.0 it's annoying a lot on windows firefox
shadowrocket doesn't work and chrome on ios says ERR_SSL_PROTOCOL-ERROR

**Comment by cross-hello** [comment]
So, why don't you upgrade to 1.7.1
[shrug]

Jan 7, 2023 16:51:30 alireza1023 ***@***.***>:

**Comment by msshn** [comment]
Update to version 1.7.1
I haven't encountered any SSL errors with this version ever since. (Thanks @rprx and welcome back)
Remember to update both your server and client.

**Comment by RPRX** [comment]
请使用 v1.7.2+ https://github.com/XTLS/Xray-core/releases/tag/v1.7.2
