### ISSUE TITLE
VLESS-TCP-XTLS-Vision协议测速带宽下降

### ISSUE THREAD

**Issue by ZqinKing** [XTLS/Xray-core#1455]
oracle在韩国的云服务器，升级前使用1.6.1+VLESS-TCP-XTLS协议，fast测速为260Mbps，跑满带宽，油管为14W。
升级至1.6.6-2+VLESS-TCP-XTLS-Vision后，fast测试为130Mbps。油管为4W~6W波动。
还有一个现象，升级后使用fast测试，跑几秒后必然会速度降至0。然后重新上去。

**Comment by zhucaidan** [comment]
不光是这个协议。。其他协议也是只要下载进程过大就直接卡死，或者无速度，不知道从哪个版本开始的

**Comment by ZqinKing** [comment]
用1.6.1跑tcp-xtls是正常的。

在 2022年12月25日，02:18，主菜单 ***@***.***> 写道：

﻿

不光是这个协议。。其他协议也是只要下载进程过大就直接卡死，或者无速度，不知道从哪个版本开始的

**Comment by RPRX** [comment]
请使用 v1.7.2+ https://github.com/XTLS/Xray-core/releases/tag/v1.7.2

**Comment by ZqinKing** [comment]
> 请使用 v1.7.2+ https://github.com/XTLS/Xray-core/releases/tag/v1.7.2

已更新，目前测试fast之前的异常现象已经消失。感谢大佬。
