### ISSUE TITLE
服務器端用新版 Xray 1.6.x 堅持幾天就崩潰

### ISSUE THREAD

**Issue by LearZhou** [XTLS/Xray-core#1457]
具體記不得從哪一個版本開始的了，但基本上過幾天服務就崩潰了。注意：我沒啟用崩潰重啟機制，因為系統沒有 systemd。

換回較早的版本就沒問題。這個服務器端的配置文件沒變，未用新版新增的流控或者功能。

**Comment by zhucaidan** [comment]
> 具體記不得從哪一個版本開始的了，但基本上過幾天服務就崩潰了。注意：我沒啟用崩潰重啟機制，因為系統沒有 systemd。
> 
> 換回較早的版本就沒問題。這個服務器端的配置文件沒變，未用新版新增的流控或者功能。

你目前用的最新的稳定服务器版本是哪一个？重启后就恢复了吗？

**Comment by LearZhou** [comment]
印象中在 1.6.x 之前的版本不會崩潰。目前退回到了 1.5.2，沒有此問題。

**Comment by reeceyng** [comment]
我的连续运行8天了

**Comment by LearZhou** [comment]
> 我的连续运行8天了

你確定 systemd 進程守護沒有起作用重啟？而是服務一直跑8天？

**Comment by xianren78** [comment]
新版对server内存要求会高一些，加上swap会极大减少崩溃。

**Comment by ffallah** [comment]
Yes it crashes and I sent a bug report, but no one cares.
There is a problem with buffers.

xray 1.6.1 crashes with the following error in log :

panic: runtime error: slice bounds out of range [2:0]

goroutine 1699405 [running]:
github.com/xtls/xray-core/common/buf.(*Buffer).Read(...)
github.com/xtls/xray-core/common/buf/buffer.go:253
github.com/xtls/xray-core/common/buf.SplitBytes({0xc00c62b7d8, 0x1, 0x1}, {0xc007b5a000?, 0xc00b170e70?, 0xc006a07dfc?}) github.com/xtls/xray-core/common/buf/multi_buffer.go:105 +0x290
github.com/xtls/xray-core/common/buf.(*BufferedReader).Read(0xc00bce2570, {0xc007b5a000?, 0xc00bb9e060?, 0x0?}) github.com/xtls/xray-core/common/buf/reader.go:68 +0x92 io.ReadAtLeast({0x11ca3c0, 0xc00bce2570}, {0xc007b5a000, 0x2e, 0x2000}, 0x2e) io/io.go:332 +0x9a io.ReadFull(...)
io/io.go:351
github.com/xtls/xray-core/common/buf.(*Buffer).ReadFullFrom(0xc00bb9e060?, {0x11ca3c0?, 0xc00bce2570?}, 0x2?)
github.com/xtls/xray-core/common/buf/buffer.go:276 +0x85 github.com/xtls/xray-core/proxy/vless/encoding.(*LengthPacketReader).ReadMultiBuffer(0xc002c2dfb0) github.com/xtls/xray-core/proxy/vless/encoding/addons.go:180 +0x205
github.com/xtls/xray-core/common/buf.copyInternal({0x11cb1c0, 0xc002c2dfb0}, {0x11c9700, 0xc00bb6abc0}, 0xc00b7338a8)
github.com/xtls/xray-core/common/buf/copy.go:81 +0x69 github.com/xtls/xray-core/common/buf.Copy({0x11cb1c0, 0xc002c2dfb0}, {0x11c9700, 0xc00bb6abc0}, {0xc001394f20, 0x1, 0xc001394f18?})
github.com/xtls/xray-core/common/buf/copy.go:104 +0xa5 github.com/xtls/xray-core/proxy/vless/inbound.(*Handler).Process.func4()
github.com/xtls/xray-core/proxy/vless/inbound/inbound.go:514 +0x1f9
github.com/xtls/xray-core/common/task.OnSuccess.func1()
github.com/xtls/xray-core/common/task/task.go:12 +0x25
github.com/xtls/xray-core/common/task.Run.func1(0xc0005c2001?)
github.com/xtls/xray-core/common/task/task.go:28 +0x2e
created by github.com/xtls/xray-core/common/task.Run github.com/xtls/xray-core/common/task/task.go:27 +0xde

**Comment by LearZhou** [comment]
請大佬看看能否修正。測試了 1.7.0 只堅持了 5 天多一點；估計 1.7.1 仍然有這個問題。

**Comment by even0306** [comment]
> 請大佬看看能否修正。測試了 1.7.0 只堅持了 5 天多一點；估計 1.7.1 仍然有這個問題。
能给一下日志便于分析问题

**Comment by LearZhou** [comment]
問題是，崩潰是無聲無息發生的，日誌都是正常的，沒有任何特殊的訊息在裡面。

請問該如何做，能幫助分析崩潰的問題？

**Comment by cross-hello** [comment]
Change log level to "debug" 😎

Jan 9, 2023 04:36:40 LearZhou ***@***.***>:

**Comment by LearZhou** [comment]
設置了 debug，目前在跑 1.7.2 ，過幾天看結果。

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/issues/1501#issuecomment-1375293435
