### ISSUE TITLE
Does anyone know which GUI Clients in linux can support xray?

### ISSUE THREAD

**Issue by brucejuz** [XTLS/Xray-core#1458]
Does anyone know which GUI Clients in linux can support xray?
Thanks very much!
Or anyone knows how to use xray in linux?
Thanks!

**Comment by istek** [comment]
v2rayA

**Comment by cross-hello** [comment]
Sorry don't know.
Xray has registered as a startup service of linux computer.
So after system boots, anything is normal.
But for the problem how to configure? Yes, you indeed need to ask past history🤣

**Comment by iopq** [comment]
> v2rayA

only old versions

**Comment by Retia-Adolf** [comment]
[MatsuriDayo/nekoray](https://github.com/MatsuriDayo/nekoray) : Qt based cross-platform GUI proxy configuration manager (backend: v2ray / sing-box)

**Comment by cross-hello** [comment]
***@***.***/creating-a-linux-service-with-systemd-611b5c8b91d6], follow the steps, write out linux services.

Dec 26, 2022 20:30:53 Retia ***@***.***>:

**Comment by H-Ir** [comment]
Qv2ray

**Comment by iopq** [comment]
https://github.com/xbclub/xraya

it's just a copy of v2ray, but has xray support

**Comment by cross-hello** [comment]
Do it as your favor.

Though the Linux​ laptop we use may never need to mind the matter after insert xray as a system service.
(by the way, you need to configure global agent settings for git, pip, wget, curl, apt, golang)

Mar 5, 2023 15:16:20 iopq ***@***.***>:

**Comment by iopq** [comment]
It uses iptables to make a proxy that all of the connections go through without having to configure it for every app. As such, it works for Steam, Wine, etc.

**Comment by ShervinR** [comment]
> [MatsuriDayo/nekoray](https://github.com/MatsuriDayo/nekoray) : Qt based cross-platform GUI proxy configuration manager (backend: v2ray / sing-box)

arigaato :)

**Comment by ShervinR** [comment]
> [MatsuriDayo/nekoray](https://github.com/MatsuriDayo/nekoray) : Qt based cross-platform GUI proxy configuration manager (backend: v2ray / sing-box)

arigaato :)

**Comment by ld202167** [comment]
> https://github.com/xbclub/xraya
> 
> 它只是 v2ray 的副本，但具有 xray 支持

谢谢你 v2ray只支持 无法支持xray均衡负载 而且每更新
