### ISSUE TITLE
What would be the server config?

### ISSUE THREAD

**Issue by railwaysystem** [XTLS/Xray-core#1459]
Client config below :
```
"outbounds": [
    {
      "mux": {
        "concurrency": 8,
        "enabled": false
      },
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "<some address that I can access without vpn>", // this address is like SNI/Bughost, owned by someonelse,
            "port": 80,
            "users": [
              {
                "alterId": 0,
                "encryption": "",
                "flow": "",
                "id": "46f0879c-c6ed-4182-90b7-8e8337dc8089",
                "level": 8,
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "",
        "wsSettings": {
          "headers": {
            "Host": "<service provider server host>"
          },
          "path": "/vmess"
        }
      },
      "tag": "proxy"
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    }
  ],
```

![image](https://user-images.githubusercontent.com/87419688/209896271-f9e07b20-2609-4be3-83b8-9dfbfc9bc1cc.png)

Above config is generated by free Vmess/Vless providers like https://sshstores.net.
But when I deploy my own, I am not able to use SNI/BUGHOST as address.

So what would be the server config for this type of client config???

**Comment by iopq** [comment]
Most people use port 443, port 80 was weird sometimes

**Comment by wy580477** [comment]
Like this:
![Screenshot_2022-12-25-12-30-15-661_com microsoft emmx dev](https://user-images.githubusercontent.com/98247050/209457041-6f2574f3-649b-487d-abda-6bfb0b06e8d8.png)

You set host to whatever domain on client side.

If you are going to use tls, you need to turn off client side certificate verification. Then you can set sni to whatever domain.

**Comment by railwaysystem** [comment]
> Most people use port 443, port 80 was weird sometimes

none are working for me.

**Comment by railwaysystem** [comment]
> Like this: ![Screenshot_2022-12-25-12-30-15-661_com microsoft emmx dev](https://user-images.githubusercontent.com/98247050/209457041-6f2574f3-649b-487d-abda-6bfb0b06e8d8.png)
> 
> You set host to whatever domain on client side.
> 
> If you are going to use tls, you need to turn off client side certificate verification. Then you can set sni to whatever domain.

i tried putting sniffing section on server side...but still i am not able to use random host address on client side.
But my port is 80. Will this be causing any problem?

**Comment by railwaysystem** [comment]
> Like this: ![Screenshot_2022-12-25-12-30-15-661_com microsoft emmx dev](https://user-images.githubusercontent.com/98247050/209457041-6f2574f3-649b-487d-abda-6bfb0b06e8d8.png)
> 
> You set host to whatever domain on client side.
> 
> If you are going to use tls, you need to turn off client side certificate verification. Then you can set sni to whatever domain.

![image](https://user-images.githubusercontent.com/87419688/209896311-38aecbeb-5f37-4432-a70d-85f96e2c698f.png)

**Comment by us254** [comment]
```
"inbounds": [
    {
        "port": 80,
        "protocol": "vmess",
        "settings": {
            "clients": [
                {
                    "id": "46f0879c-c6ed-4182-90b7-8e8337dc8089",
                    "alterId": 0,
                    "level": 8
                }
            ]
        },
        "streamSettings": {
            "network": "ws",
            "wsSettings": {
                "path": "/vmess"
            }
        },
        "tag": "proxy"
    }
],
"outbounds": [
    {
        "protocol": "freedom",
        "tag": "direct"
    },
    {
        "protocol": "blackhole",
        "tag": "block"
    }
]
```
