### ISSUE TITLE
免费ss节点测试，客户端开启udp后，上传文件到onedrive会中途卡死

### ISSUE THREAD

**Issue by jacklee789** [XTLS/Xray-core#146]
免费ss节点测试，客户端v2rayn4.5，内核Xray1.2.0
如果客户端开启udp，下载可以完成，上传文件到onedrive会中途卡死。
如果客户端关闭udp，下载可以完成，上传文件到onedrive也可以完成。
不知道是不是和 https://github.com/XTLS/Xray-core/issues/129 一样的问题。
另外原版ss客户端也会卡死，没有找到关闭udp的选项。

**Comment by badO1a5A90** [comment]
建议更新至xray v1.2.1 测试下, 此版本解决了大量UDP相关的问题.

**Comment by jacklee789** [comment]
内核更新到xray v1.2.1后上传可以完成，谢谢。
