### ISSUE TITLE
add fallback setting to all protocols when using TLS/XTLS stream

### ISSUE THREAD

**Issue by emdaitaj** [XTLS/Xray-core#1469]
curranty only trojan+tcp+tls/xtls has fallback ability 
you can't use fallback with vless/vmess

when using tls , having fallback is necessary to stay undetected from vpn server ,pass human/robot checks of tls website
vision flow control is only available for vless-tcp-tls too , it's not an upgrade if you can't respond like an https website when opened in a browser

**Comment by SakuraSakuraSakuraChan** [comment]
> curranty only trojan+tcp+tls/xtls has fallback ability you can't use fallback with vless/vmess

No

**Comment by RPRX** [comment]
> curranty only trojan+tcp+tls/xtls has fallback ability you can't use fallback with vless/vmess

Where did you get this info? Both VLESS and Trojan support `fallbacks` in Xray-core.
