### ISSUE TITLE
VLESS 分享链接标准提案 能不能增加一下"fingerprint": "chrome"

### ISSUE THREAD

**Issue by LsnmxNB** [XTLS/Xray-core#1472]
"fingerprint": "chrome" // 通过 uTLS 库 模拟 Chrome / Firefox / Safari 或随机生成的指纹

目前 v2rayN，v2rayNG 分享链接VLESS-TCP-XTLS-Vision都没有"fingerprint": "chrome"导出来，默认都是留空

**Comment by cross-hello** [comment]
Oh, could set default fingerprint to "randomized"?
This way at least willn't exposure common golang birthmark.

Dec 29, 2022 21:41:56 LsnmxNB ***@***.***>:

**Comment by thank243** [comment]
> "fingerprint": "chrome" // 通过 uTLS 库 模拟 Chrome / Firefox / Safari 或随机生成的指纹
> 
> 目前 v2rayN，v2rayNG 分享链接VLESS-TCP-XTLS-Vision都没有"fingerprint": "chrome"导出来，默认都是留空

So why don't you open a issue on v2rayN group?

**Comment by 8884361** [comment]
> "fingerprint": "chrome" // 通过 uTLS 库 模拟 Chrome / Firefox / Safari 或随机生成的指纹
> 
> 目前 v2rayN，v2rayNG 分享链接VLESS-TCP-XTLS-Vision都没有"fingerprint": "chrome"导出来，默认都是留空

这是GUI前端的问题，请找对应客户端的项目去提Issues ，例如 [2dust/v2rayN](../../../2dust/v2rayN) 或者 [2dust/v2rayNG](../../../2dust/v2rayNG)

**Comment by RPRX** [comment]
抱歉，的确是 VLESS 分享链接标准提案没有及时更新，fingerprint 参数还会加些选项，等~~秒天秒地秒空气的~~ Reality 协议加入 Xray-core 后，会一起更新一次 VLESS 分享链接标准提案，下个版本发布
