### ISSUE TITLE
交叉编译的时候可以根据 tags 编译以缩小体积吗

### ISSUE THREAD

**Issue by cary-sas** [XTLS/Xray-core#1473]
假如只需要xray 包含nat，client功能，不需要服务端功能，可以像这样定义一些 tags 编译吗 ？
 `go build -tags "nat client"`

**Comment by qiuzi** [comment]
@cary-sas 没有这个功能吧

**Comment by cross-hello** [comment]
In the other hand, maybe could try **gccgo**- gnu go compiler, could get a more optimized code and smaller size, but with a longer compilation time.

For golang tag, could visit document
https://www.digitalocean.com/community/tutorials/customizing-go-binaries-with-build-tags


Dec 29, 2022 23:58:24 cary-sas ***@***.***>:

**Comment by cross-hello** [comment]
Sorry, maybe **gccgo** is difficult to search corresponding documents.
Find a new project named [tinygo](https://github.com/tinygo-org/tinygo), specializing for microcontroller.
Though it is some problems needing to correct now.
 
![image](https://user-images.githubusercontent.com/42733664/210046875-5030c337-796e-4e8b-9c6f-a49582b5dfed.png)

**Comment by chika0801** [comment]
> > @cary-sas 没有这个功能吧
> 
> [trojan-go](https://github.com/p4gefau1t/trojan-go#%E7%A7%BB%E6%A4%8D%E6%80%A7)的项目就有类似的功能 [<img alt="image" width="658" src="https://user-images.githubusercontent.com/61653855/210129034-2e11a640-407d-483c-9da4-7380c97186b9.png">](https://github.com/p4gefau1t/trojan-go#%E7%A7%BB%E6%A4%8D%E6%80%A7)

xray项目一直没这功能

**Comment by mirror1342** [comment]
v2ray时代的遗留问题

**Comment by hqvv** [comment]
恳请大佬们关注这个问题，目前xray经过upx压缩后9M左右。 体积再大下去，就会淘汰掉所有使用 16M nor flash的路由。
而由于有一段时间32M nor flash支持有一些问题， 造成16M nor flash 几乎是一些老设备的标配。
===
对速度没有太多需求的老设备，性能是够跑 xray的。但由于flash尺寸的问题，导致无缘用上新版 xray, 会是一件令人遗憾的事。

**Comment by Fangliding** [comment]
没有计划（史山代码）
