### ISSUE TITLE
xray在服务器能否实现多线程请求数据

### ISSUE THREAD

**Issue by wenzhuning** [XTLS/Xray-core#1478]
很多vps对单线程进行限速，如果能实现多线程请求数据，这样就能提高上网体验

**Comment by wenzhuning** [comment]
我是这样想的，xray对每个请求自动探测，获取请求数据的大小，这个数据大小可以由用户配置，当请求数据达到配置大小后，就自动多线程请求

**Comment by quackerd** [comment]
这个能否同一机器xray端口多开然后用load balancing

**Comment by lihaixin** [comment]
可以的，我就是用在Linux做
 {
  "tag": "balancer",
  "selector": []
}

**Comment by denwork** [comment]
是不是可以启多个xray实例，然后再运行一个haproxy进行负载均衡。

**Comment by jliveusa** [comment]
> 可以的，我就是用在Linux做 { "tag": "balancer", "selector": [] }

请问如何实现？有代码可以参考吗？谢谢

**Comment by qist** [comment]
https://xtls.github.io/config/routing.html#balancerobject
