### ISSUE TITLE
Youtube prefer TCP instead of UDP in VLESS-TCP-XTLS

### ISSUE THREAD

**Issue by GektorUA** [XTLS/Xray-core#1479]
I have make config VLESS-TCP-XTLS from https://github.com/XTLS/Xray-examples/tree/main/VLESS-TCP-XTLS-WHATEVER

SERVER:
inbound part:

    {
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id" : "some-id",
            "flow": "xtls-rprx-direct",
            "level": 0
          }
        ],
        "decryption": "none",
        "fallbacks": [
           {
             "dest": 1080,
             "xver": 1
           }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "sockopt": {
          "tcpFastOpen": true
        },
        "xtlsSettings": {
        "serverName": "my.domain.com",
        "alpn": ["h2"],
        "minVersion": "1.3",
        "certificates": [
          {
            "ocspStapling": 3600,
            "certificateFile" : "/path/to/my.cer",
            "keyFile" : "/path/to/my.key"
          }
        ]
        }
      }
   }

CLIENT:
inbound part:

     {
      "listen": "127.0.0.1",
      "port": 1080,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true
      },
      "streamSettings": {
        "sockopt": {
          "tcpFastOpen": true
        }
      }
     }

outbound part:

    {
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "my.domain.com",
            "port": 443,
            "users": [
              {
                "id": "some-id",
                "flow": "xtls-rprx-splice",
                "encryption": "none"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
          "serverName" : "my.domain.com"
        },
        "sockopt": {
          "tcpFastOpen": true,
        }
      }

Then forward all traffic through tun2socks in 127.0.0.1 socks of xray on same host.
UDP is works (i have check it by OpenVPN UDP client - and it's connects, data is flowing), but Youtube doesn't use UDP at all, it's sends some small packets, but didn't switch on UDP in any case. I have try many times on different PCs/notebooks/smartphones, result is same.

I have add outbound Trojan and route UDP through it:
SERVER:
added inbound part:

    {
      "port": 1080,
      "listen": "127.0.0.1",
      "protocol": "trojan",
      "settings": {
        "clients": [
          {
            "password": "somepassword",
            "level": 0
          }
        ]
      },
      "streamSettings": {
        "sockopt": {
          "tcpFastOpen": true
        },
        "network": "tcp",
        "security": "none",
        "tcpSettings": {
           "acceptProxyProtocol": true
        }
      }
    }

CLIENT:
added outbound part:

    {
      "tag":"udp",
      "protocol": "trojan",
      "settings": {
      "servers": [
          {
            "address": "my.domain.com",
            "port": 443,
            "password": "somepassword"
          }
      ]
      },
      "streamSettings": {
        "sockopt": {
          "tcpFastOpen": true,
          "mark": 255
        },
        "network": "tcp",
        "security": "tls",
        "tlsSettings": {
        "serverName": "my.domain.com"
        }
      }
    }

+add routes to froward UDP traffic through Trojan.

Youtube switch on UDP flow without any troubles on all devices.

If add on client to Trojan in servers part:
           "flow": "xtls-rprx-splice"
or
           "flow": "xtls-rprx-direct"
Youtube stop switch on UDP flow in any cases, and use only TCP.

I can leave Trojan "as is", but in my tests if i have start download torrents, after some time i have get in Chrome browser:
ERR_CONNECTION_ABORTED on all web pages.

If i have stop download torrents, after some time error disappear.

So, i have 2 questions:
1. Why Youtube doesn't use UDP in VLESS (i think, as Trojan have same, there is issue with xtls-rprx-direct/xtls-rprx-splice)?
2. Why when i have fallback to Trojan with UDP on high load with torrents i have get ERR_CONNECTION_ABORTED and TCP working with failures?

**Comment by lihaixin** [comment]
delete 

 "sockopt": {
      "tcpFastOpen": true,
      "mark": 255
    },

**Comment by RPRX** [comment]
XTLS drops inner UDP/443 requests by default. Use xtls-*-udp443 at client side if you want to avoid that (not recommend).

**Comment by RPRX** [comment]
> But in that case all UDP traffic is forwarding directly to the server

It's impossible.
