### ISSUE TITLE
可否让config.json中的证书配置支持软链接而不是必须.pem文件？

### ISSUE THREAD

**Issue by 18601673727** [XTLS/Xray-core#1481]
每3个月 我都要ssh上去 然后重新复制`certbot`更新下来的`fullchain.pem`和`privkey.pem`俩文件到`/usr/local/etc/xray`目录，然后`chown nobody:nogroup`它俩，万一忘了就是再次排查xray启动错误，麻烦死了。

**Comment by 18601673727** [comment]
@cross-hello  https://henrywithu.com/coexistence-of-web-applications-and-vless-tcp-xtls/

**Comment by cross-hello** [comment]
How about setting a crontab task to copy certification file regularly?
Write a shell file to */usr/local/etc/crontab/copy_certification.sh* , like
```shell
cp /etc/letsencrypt/live/webgame.example.com/* /usr/local/etc/xray/
chown nobody:nogroup  /usr/local/etc/xray/*
echo "backup time: $(date) “
```

Then `chmod +x /usr/local/etc/crontab/copy_certification.sh`. 

Add crontab task
`* * * 1 * /usr/local/etc/crontab/copy_certification.sh>>/usr/local/etc/crontab/copy_certification.sh.log`
This way the files will be backuped each month

**Comment by cross-hello** [comment]
Oh no, [shy],  time of crontab should be
` 4 4 1 * * *`(each month first day at 4:04 am)

**Comment by 18601673727** [comment]
怎么说呢 治不了本 优雅的治个标也挺好

**Comment by cross-hello** [comment]
@18601673727 Hello, Sir. Why do you say xray don't support file soft link? What is error show?

**Comment by RPRX** [comment]
应该是文件权限的问题，与是否软链无关

**Comment by 18601673727** [comment]
@cross-hello 具体我也没有留意 但是重新复制并调整权限后就能启动了 很有可能是权限问题

**Comment by cross-hello** [comment]
We just ponder the situation where link file have different allowed right with linked file. What will it happen?
We don't know now.
But for easy using, change file mode to 777 is preferred.

Jan 8, 2023 11:38:21 18601673727 ***@***.***>:

**Comment by 18601673727** [comment]
@cross-hello @RPRX 很遗憾我又来了，证书又双叒叕过期了，这次我意识到虽然certbot自动更新了证书，但nginx和xray都没有pick到，并且软链依旧是不支持的，如果有软链成功配置运行的案例，请务必分享给我，因为没pick到的问题通过cronjob每天自动重启service就很好解决，但复制证书和对新证书修改权限是比较麻烦的。

**Comment by FranzKafkaYu** [comment]
1.为什么不让Nginx/xray直接读取证书呢 2.即使你真的要单独复制证书并修改权限，写一个脚本，使用crontab周期执行就好了，还能进行定期重启服务，清理日志等，这算是一个比较优雅的解决方案。

**Comment by cross-hello** [comment]
Sorry, don't experience situations where you are. Don't know explicitly what problem you meet.

Cloudflared could issue free SSL certificate, and will update certificate valid date automatically.

Mar 5, 2023 08:25:32 18601673727 ***@***.***>:
