### ISSUE TITLE
[BUG]TLS1.3下无法正确使用指定的密码套件

### ISSUE THREAD

**Issue by ShoukakuChuuCC** [XTLS/Xray-core#1484]
配置
"tlsSettings": {
          "rejectUnknownSni": true,
          "minVersion": "1.3",
          "cipherSuites": "TLS_CHACHA20_POLY1305_SHA256",
          "certificates": [
            {
              "certificateFile": "path",
              "keyFile": "path"
            }
          ]
        }
TLS1.3抓包
![image](https://user-images.githubusercontent.com/38343280/210502685-46e4acd7-6261-4138-83d6-67142943a4cb.png)
![image](https://user-images.githubusercontent.com/38343280/210502735-8810804f-ae29-4c42-b02a-10fa02d799ed.png)

TLS1.2下则正常
"tlsSettings": {
          "rejectUnknownSni": true,
          "minVersion": "1.2",
          "maxVersion": "1.2",
          "cipherSuites": "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
          "certificates": [
            {
              "certificateFile": "path",
              "keyFile": "path"
            }
          ]
        }
TLS1.2抓包
![image](https://user-images.githubusercontent.com/38343280/210502959-068b3a8f-3977-4097-bc46-df670ab5281c.png)
![image](https://user-images.githubusercontent.com/38343280/210502989-85054ec9-7446-4fee-bfab-ff1e0afca4bd.png)

**Comment by cross-hello** [comment]
UTLS has changed ciphersuites of client, so it may be can't specify explicity.

**Comment by ShoukakuChuuCC** [comment]
> UTLS has changed ciphersuites of client, so it may be can't specify explicity.

Even if UTLS is not used, TLS1.3 cannot use the specified cipher suite
However, if TLS1.2 is used, the specified cipher suite works properly with or without UTLS

**Comment by cross-hello** [comment]
Can you pose the cipher suites of server?

**Comment by yuhan6665** [comment]
It is not supported by Go.
https://github.com/golang/go/issues/29349#issuecomment-449143820
