### ISSUE TITLE
访问https 网站报错 error:0A000126:SSL routines::unexpected eof while reading

### ISSUE THREAD

**Issue by ailncode** [XTLS/Xray-core#1485]
1.安装 xray-core
2.配置
3.配置http_proxy
`export http_proxy=http://127.0.0.1:10809/
export https_proxy=http://127.0.0.1:10809/`
4.访问https 网站
`
root@dev:~# curl -v https://www.google.com
* Uses proxy env variable https_proxy == 'http://127.0.0.1:10809/'
*   Trying 127.0.0.1:10809...
* Connected to (nil) (127.0.0.1) port 10809 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to www.google.com:443
> CONNECT www.google.com:443 HTTP/1.1
> Host: www.google.com:443
> User-Agent: curl/7.81.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
<
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.0 (OUT), TLS header, Unknown (21):
* TLSv1.3 (OUT), TLS alert, decode error (562):
* error:0A000126:SSL routines::unexpected eof while reading
* Closing connection 0
curl: (35) error:0A000126:SSL routines::unexpected eof while reading`
`
5.错误日志
`
root@dev:~# cat /var/log/xray/error.log
2023/01/04 16:53:16 [Warning] core: Xray 1.7.0 started
2023/01/04 16:53:29 [Warning] [2412608028] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > read tcp 111.6.230.102:41516->161.81.212.108:553: read: connection reset by peer
2023/01/04 16:55:28 [Warning] [1462954465] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > read tcp 111.6.230.102:41518->161.81.212.108:553: read: connection reset by peer
2023/01/04 16:59:57 [Warning] [939198484] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > read tcp 111.6.230.102:41520->161.81.212.108:553: read: connection reset by peer
`

系统版本：Ubuntu Server LTS 22.04.1
`
root@dev:~# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
`

xray 版本：1.7.0
root@dev:~# xray version
Xray 1.7.0 (Xray, Penetrates Everything.) Custom (go1.19.4 linux/amd64)
A unified platform for anti-censorship.

curl 版本： 7.81.0
`
root@dev:~# curl --version
curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.13
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
`

openssl 版本：3.0.2
`
root@dev:~# openssl version
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
`

**Comment by bigding123** [comment]
i got same problam,how to solve?
