### ISSUE TITLE
Sni proxy for fake tls

### ISSUE THREAD

**Issue by hiddify** [XTLS/Xray-core#1486]
Is it possible to have sni proxy with xray core
For faketls protocols like mtproxy?

**Comment by RPRX** [comment]
Reality

**Comment by RPRX** [comment]
> > Reality
> 
> what is reality?

Coming soon

**Comment by hiddify** [comment]
Wow Thanks

Do you have any link to the source code?
I am really interested in knowing more about it :*

**Comment by Fangliding** [comment]
@RPRX Is it like shadowtls?

**Comment by RPRX** [comment]
> @RPRX Is it like shadowtls?

Nope. It's real TLS, but better.

**Comment by RPRX** [comment]
> Wow Thanks
> 
> Do you have any link to the source code? I am really interested in knowing more about it :*

Haven't been released yet, but soon.

**Comment by hiddify** [comment]
@RPRX Can reality fix this issue?
From what i understand from [here](https://github.com/XTLS/REALITY), in reality, you check the SNI, if it is in serverNames, then it will be passed to the inbound,
However, My Question was that can we define for example if the SNI is www.google.com and TLS version is 1.3 then pass it to a faketls protocol (like telegram mtproxy)?

Can you please help me?

**Comment by hiddify** [comment]
suggestion:
similar to fallback object change it to an array:
```
"realitySettings": {
{"serverNames": [ "example.com","www.example.com"], minClientVer="1.3", maxClientVer="1.3",  "dest": "example.com:443", "xver": 0},
{ "dest": "1.example.com:443", "xver": 0}, // no serverNames mean all
}
```
