### ISSUE TITLE
无法全局代理

### ISSUE THREAD

**Issue by bestmikecat** [XTLS/Xray-core#149]
仅ipv6的vps，使用dns64,采用vless+ws+tls+cdn,在电脑上的v2ray客户端使用一切正常，但在手机端按全局配置操作却不行，然后我将设置中的"ipv6优先"打开，再将远程DNS改为ipv6的Dns，发现只有google等国外网站可以打开，国内网站均不行，只有关闭上述，使用绕过大陆网站模式，才能直连国内网站同时代理国外网站。
用vmess+ws+tls+cdn时也有上述问题，但换用1.8版Kitsunebi后一切正常，不知道什么问题。

**Comment by rprx** [comment]
@bestmikecat 先试试 NG 1.5.9

**Comment by bestmikecat** [comment]
@rprx 还是不行

**Comment by rprx** [comment]
@bestmikecat 说实话我没看懂你想实现什么，vps 只有 ipv6 的话，当然连不了普遍只支持 ipv4 的国内网站

**Comment by bestmikecat** [comment]
@rprx 我用了dns64. 关于dns64>>https://luotianyi.vc/2701.html<<可以看一下这个网页，可使纯ipv6主机访问ipv4网站，而且我在电脑的v2ray客户端全局是正常的，在手机的v2rayng上无法全局代理国内的网站，选择全局只能打开google等国外网站，国内网站都打不开。
希望能所有网站都走全局代理

**Comment by xianren78** [comment]
你导出来NG的配置应该可以看出来，ipv6优先的时候也是用的ipv4的DNS。想用得用自定义配置

**Comment by ymcoming** [comment]
你PC端全局可以，也可能是config.json里面做了分流啊！
再说dns64/nat64已经不是一个好的方法了，毕竟别人提供dns64/nat64是为广大公众服务的，所以会在流量/速度上都会做不少限制。

**Comment by bestmikecat** [comment]
@ymcoming 我没用分流，而且vmess的安卓Kitsunebi客户端正常，要是Kitsunebi有vless估计也可能正常，不知道是不是v2rayng的问题

**Comment by rprx** [comment]
试试 NG v1.5.10

https://github.com/2dust/v2rayNG/releases/download/1.5.10/v2rayNG_1.5.10_arm64-v8a.apk

**Comment by bestmikecat** [comment]
@rprx 我尝试了一下自定义配置，自己写json文件，将DNS改为了ipv6的DNS64地址，发现全局可以正常使用了，不过也是奇怪，电脑端也没有自定义过DNS, 却能正常使用。
另外，我还手动打开了mux, 代理时延迟降低了不少，似乎在v2rayng上mux是默认关闭的，也没有个图形化设置开关，电脑端反倒是有开关，也许可以在v2rayng上改进一下。

**Comment by rprx** [comment]
DNS64 或许可以加入文档
