### ISSUE TITLE
请问 在不想使用域名的情况下，最佳协议选择是啥？

### ISSUE THREAD

**Issue by eromoe** [XTLS/Xray-core#1490]
RT
我看了一下，不用域名应该是所有的tls 都无法使用吧，因为证书依赖域名。

**Comment by wy580477** [comment]
可以用ip证书。

**Comment by eromoe** [comment]
不太理解网络技术，看了一些教程都是讲域名，一键安装脚本也是。

**Comment by cross-hello** [comment]
Maybe you could use **duck dns** to get free second domain.

Jan 5, 2023 13:24:00 eromoe ***@***.***>:

**Comment by eromoe** [comment]
Too complicate, I am searching for a simple way , easy deploy easy reinstall. 
I have used freenode domain and cloudflare deployed v2ray + tls +ws , once the domain expired , something went wrong(maybe candy config? ) , need do everything again .
I just don't like the domain way,which bring much unesesary effort.

**Comment by cross-hello** [comment]
For domain expired, do you specify **SSL Certificate Validity Period**?
You could use [certbot](https://github.com/certbot/certbot) to auto renew. May could follow the steps of tutorial https://docs.digitalocean.com/support/how-can-i-renew-lets-encrypt-certificates/

If you mean domain name validation time, you need to find corresponding scripts for different website to refresh.

**Comment by even0306** [comment]
vmess系列

**Comment by cross-hello** [comment]
😅  Why not use absolute one click script? May be the repository could help? 
https://github.com/maplecool/easytrojan

**Comment by eromoe** [comment]
@cross-hello Yeah, but too much detail on the knowledge chains, the more things the more complicate , and the more accidents, right ? 
So, really I think easy and rubost is more important.

**Comment by eromoe** [comment]
@cross-hello  looks good , but it rely on 免费域名 sounds unstable .... let me have a try :)

**Comment by cross-hello** [comment]
You don't have to pay or renew for domain level more than second.

**Comment by eromoe** [comment]
trojan seems not stable as tcp+http, it is blcoked now.  On same vps, tcp+http service works for years without blocking.

**Comment by eromoe** [comment]
but tcp+http doesn't support udp proxy is painful ...

**Comment by cross-hello** [comment]
Last time we use neural network to discriminate, but full connected network need a lot of computation. So we don't know if it is not enough training time or others. Next time we may use convolution neural network to have a try(we are still learning),

**Comment by chika0801** [comment]
加钱买域名，用SSL证书，用hysteria

**Comment by cross-hello** [comment]
(off topic) why not use self signed certificate?

Jan 6, 2023 11:28:55 chika0801 ***@***.***>:

**Comment by eromoe** [comment]
@cross-hello I think maybe it is my android client didn't open utls , but I am not sure. Scan from qrcode lose that config .

**Comment by eromoe** [comment]
@chika0801 不加钱且图方便嘛，VPS migrate 的话ip换了证书啥的都得换，tcp+http的migrate 以后只要换个ip就好了，这个是优势。

**Comment by cross-hello** [comment]
Got it. Just don't know why you intended to let your vps get blocked.

**Comment by hansid** [comment]
楼主可以去namesilo买一个域名。最低一年1.99美刀，也就一顿饭钱。
或者用hysteria的自签证书。

**Comment by chika0801** [comment]
> 

2楼说的要不开IP证书用上SSL证书用有TLS的协议组合，不要就没有了，随便选vmess tcp ss tcp跑就是了，不爱惜VPS IP即可

**Comment by eromoe** [comment]
我常年tcp+http都没被封，换ip 主要是有的时候觉得速度不够快就换一下，不是很频繁
应该是443端口被封了，换一个端口trojan 又可以用了

**Comment by eromoe** [comment]
这次新建协议主要是为了udp代理。

**Comment by cross-hello** [comment]
Socks5 support tcp + udp.

Jan 6, 2023 13:53:19 eromoe ***@***.***>:

**Comment by KyonCN** [comment]
freenom可以申请一年的免费域名 到期了还可以免费续

**Comment by lewishuang14** [comment]
> 

freenom 貌似不能用了，账号名下的域名不见了，申请新域名又提示错误。

**Comment by eromoe** [comment]
对 freenom 问题很多，以前几年前吧申请过几次，基本要折腾很久才能申请成功，域名续期也有问题。

**Comment by cross-hello** [comment]
What? Really! ?

[cid:eu.faircode.email.55]

Jan 7, 2023 13:31:43 eromoe ***@***.***>:

**Comment by eromoe** [comment]
My experience,  register/login looping , order looping,  lost login status on payment  . sometime would be normal ,  once you success , the domain does keep a year, renew also face above problem .  Many years ago .

**Comment by cross-hello** [comment]
🤭 The above information is grabbed via web scraper(so it could login smoothly) . Now we need to wait for final fourteen days to capture refresh domain related api to finally finish the script.

Jan 7, 2023 14:58:23 eromoe ***@***.***>:

**Comment by bash99** [comment]
支持ShadowTLS的那些服务器和客户端

**Comment by ZqinKing** [comment]
没有域名也能正常用，客户端侧直接填IP，然后忽略安全性校验，服务端用自签证书顶上就可以。

**Comment by ZqinKing** [comment]
> 没有域名也能正常用，客户端侧直接填IP，然后忽略安全性校验，服务端用自签证书顶上就可以。

不过忽略安全性校验，容易被中间人攻击。如果是指浏览浏览网站的话问题也不是很大。

**Comment by RPRX** [comment]
VLESS XTLS Vision Reality

**Comment by RPRX** [comment]
> VLESS XTLS Vision Reality

很显然，我指的是，它们可以一起用：VLESS + XTLS Vision + Reality

~~我尽量不鸽~~

**Comment by alongL** [comment]
1.2.3.4.sslip.io 将被自动解析到1.2.3.4这个IP地址， 不用申请且免费的域名  https://sslip.io

**Comment by alongL** [comment]
1.2.3.4.nip.io   这个也是一样的，自动返回  1.2.3.4

**Comment by bdhwrsh** [comment]
hysteria 2
