### ISSUE TITLE
rpc error: code = Canceled desc = context canceled

### ISSUE THREAD

**Issue by AlirezaGhanavati** [XTLS/Xray-core#1491]
Hello everyone
I am getting this error on the server. I am using Vless+gRPC+Tls.
` app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to transfer request payload > transport/internet/grpc/encoding: failed to fetch hunk from gRPC tunnel > rpc error: code = Canceled desc = context canceled`
Is there any solution?

**Comment by SakuraSakuraSakuraChan** [comment]
Do you have any problem on the client's side or not?

**Comment by AlirezaGhanavati** [comment]
After some time (eg 12 hours), the client won't connect or has high ping time.
To solve this problem, I kill the xray process on both sides and run it again. With this method, the problem is solved for a while.
It should be noted that this period of time is not certain. Sometimes it is 12 hours and sometimes 1 day or more.
I must also say that my traffic goes through Cloudflare CDN

**Comment by SakuraSakuraSakuraChan** [comment]
> After some time (eg 12 hours), the client won't connect or has high ping time. To solve this problem, I kill the xray process on both sides and run it again. With this method, the problem is solved for a while. It should be noted that this period of time is not certain. Sometimes it is 12 hours and sometimes 1 day or more. Meanwhile, my traffic goes through Cloudflare CDN

https://github.com/XTLS/Xray-examples/commit/c05cb1adb688e2f2bb01bd4c703c8c5dcbb8cebd

**Comment by roachsinai** [comment]
> After some time (eg 12 hours), the client won't connect or has high ping time. To solve this problem, I kill the xray process on both sides and run it again. With this method, the problem is solved for a while. It should be noted that this period of time is not certain. Sometimes it is 12 hours and sometimes 1 day or more. Meanwhile, my traffic goes through Cloudflare CDN

Same issue, but seems I only restart on server could solve this problelm.
