### ISSUE TITLE
手机端使用外网app老出问题

### ISSUE THREAD

**Issue by e1lite** [XTLS/Xray-core#1493]
我是自己建的机场，手机端用的v2rayNG，但刷红迪的时候经常就卡住加载不出来了，得重启节点才行，其他app也有偶尔加载不出来图片得重启节点的问题，但频率没有红迪出问题那么高。电脑端的话应该没有问题，想问一下这是我机场的问题吗？该如何解决？

**Comment by mirror1342** [comment]
那是因为v2rayNG本身就很有问题，反正我用默认配置根本打不开油管视频。

**Comment by e1lite** [comment]
> 那是因为v2rayNG本身就很有问题，反正我用默认配置根本打不开油管视频。

这样吗？那安卓还有类似v2rayNG的软件吗？

**Comment by Array-Cats** [comment]
是不是你的手机杀后台杀的有点太狠了，我只能说我没有遇到过类似的问题（基本排除幸存者偏差，因为我家里面不同牌子的手机都没遇到过）

**Comment by cross-hello** [comment]
Find a old time app which could pilot global traffic. Then run xray in [termux](https://github.com/termux/termux-app) , export listened http and socks5 port.
Then use the app to listen.

Jan 7, 2023 12:44:08 e1lite ***@***.***>:

**Comment by mirror1342** [comment]
如果你用的是ss节点，换shadowsocks for android马上秒开。

**Comment by e1lite** [comment]
> 是不是你的手机杀后台杀的有点太狠了，我只能说我没有遇到过类似的问题（基本排除幸存者偏差，因为我家里面不同牌子的手机都没遇到过）

能问下你的协议是什么吗？我是vless+tcp+xtls，是我协议的问题吗？

我的问题就是打开红迪时评论加载不出来，此时看得出网速很差，只有几kb的样子，然后如果我断开节点重连，网速就能达到100+kb，可以把评论加载出来了，但我如果切出去上别的app，外网的或者国内的，再切回红迪就又是这种情况，只能断开节点再重连。

**Comment by RPRX** [comment]
如果你使用的协议是 XTLS Vision，请使用 v1.7.2+ https://github.com/XTLS/Xray-core/releases/tag/v1.7.2
