### ISSUE TITLE
客户端用旧版v2ray 4.32.1可以和xray服务端兼容不？

### ISSUE THREAD

**Issue by emiyalee1005** [XTLS/Xray-core#15]
主要是现在主流客户端软件集成的还是v2ray

**Comment by xianren78** [comment]
可，但是建议换..系统版直接替换core就行，安卓NG已经有基于xray的版本了。欢迎加入tg群聊使用问题。

**Comment by winXray** [comment]
[https://github.com/winXray/winXray](https://github.com/winXray/winXray)   windows Xray 客户端（包含Xray服务端一键安装工具）
