### ISSUE TITLE
v1.7.2 VLESS-TCP-XTLS-Vision 在使用默认配置时国内有些网站打不开

### ISSUE THREAD

**Issue by pp686** [XTLS/Xray-core#1502]
默认配置里的"domainStrategy": "IPIfNonMatch",国内的wotgame.cn网站无法打开
改成原来"domainStrategy": "AsIs",后就能打开了。 这两个不同配置对VLESS-TCP-XTLS-Vision有何影响吗？

**Comment by FranzKafkaYu** [comment]
@pp686 流控与你的路由配置互不影响。国内域名打不开先确定一下你客户端的代理模式，结合日志来看是否是客户端block或者服务端block。默认情况下，国内域名会直连，不经过代理。

**Comment by chika0801** [comment]
你要发你vps端配置，说详细，你默认配置指客户端吗？客户端用的什么软件如v2rayn，路由怎么填的之类。
这样描述问题，别人是过猜。

**Comment by mirror1342** [comment]
你不会换一个出站试下？

**Comment by RPRX** [comment]
参考二三四楼

**Comment by even0306** [comment]
xtls.github.io 中有关于这两个配置的区别

**Comment by pp686** [comment]
自己的passwall有BUG…… 开了TCP Default Proxy Mode 中国列表以外就会这样  选GFW列表就正常了。用其它端不会出现这个情况……
