### ISSUE TITLE
mtls 雙向驗證

### ISSUE THREAD

**Issue by yuguanching** [XTLS/Xray-core#1508]
想請問各位大佬
目前xray 有在vless + tls 出站或是訪問dns時
允許設定雙向tls驗證的功能嗎？

**Comment by xqzr** [comment]
`usage`
https://xtls.github.io/config/transport.html#tlsobject

**Comment by yuguanching** [comment]
有的
這個篇章我有先閱讀過
之前tlsSettings 若有設 certificates
都是針對「將xray作為服務端時」的inbound節點做設定

那如果今天是要搞雙向tls驗證

是要將tlsSettings的certificates,
設定在「將xray作為客戶端」的outbound裡面嗎？
目前尚未找到這樣設定的先例
個人嘗試也並未試出效果

**Comment by HeXis-YS** [comment]
在客户端的`outbound`中配置好CA证书，将`usage`设置为`verify`

**Comment by cross-hello** [comment]
```config 
tlsSettings": {
          "certificates": [
            {
              "certificate": [
                "-----BEGIN CERTIFICATE-----",
                "...",
                "-----END CERTIFICATE-----"
              ],
              "usage": "verify"
            }

```
We set this in client, though we think it is single direction certification, not bidirectional.

**Comment by xqzr** [comment]
`certificates` is array
