### ISSUE TITLE
PVE Linux - LXC Container - Ubuntu - Docker 報錯

### ISSUE THREAD

**Issue by asiaqa** [XTLS/Xray-core#1515]
用最新源碼編譯xray-core v1.7.2. 使用linux-386設置..

在Docker image alpine linux, 只要在使用XLTS - Vision，用一段時間（２分鐘左右）就會報錯...

panic: runtime error: slice bounds out of range [:538] with capacity 0

goroutine 1293 [running]:
github.com/xtls/xray-core/common/buf.(*Buffer).BytesRange(...)
/github/workspace/tmp/common/buf/buffer.go:141
github.com/xtls/xray-core/proxy/vless/encoding.XtlsUnpadding({0x8f3a2e0, 0xb8117a0}, {0xb2e7ac0, 0x1, 0x1}, {0xa7e1520, 0x10, 0x10}, 0xa9a0dac, 0xa9a0da8, ...)
/github/workspace/tmp/proxy/vless/encoding/encoding.go:579 +0xd08
github.com/xtls/xray-core/proxy/vless/encoding.XtlsRead.func1({0x8f3a2e0, 0xb8117a0}, {0x8f3e2a0, 0xb2e7a30}, {0x0, 0x0}, {0x8f39c4c, 0xb2e7ae0}, 0xa9a0eb8, 0xaba7702, ...)
/github/workspace/tmp/proxy/vless/encoding/encoding.go:298 +0x45a
github.com/xtls/xray-core/proxy/vless/encoding.XtlsRead({0x8f309f0, 0xb6c0b28}, {0x8f31940, 0xb2e7b20}, {0x8f30d38, 0xbb90480}, {0x8f3e2a0, 0xb2e7a30}, {0x8f39c4c, 0xb2e7ae0}, ...)
/github/workspace/tmp/proxy/vless/encoding/encoding.go:336 +0x11f
github.com/xtls/xray-core/proxy/vless/inbound.(*Handler).Process.func4()
/github/workspace/tmp/proxy/vless/inbound/inbound.go:566 +0x42d
github.com/xtls/xray-core/common/task.OnSuccess.func1()
/github/workspace/tmp/common/task/task.go:12 +0x23
github.com/xtls/xray-core/common/task.Run.func1(0xb6545f0)
/github/workspace/tmp/common/task/task.go:28 +0x2b
created by github.com/xtls/xray-core/common/task.Run
/github/workspace/tmp/common/task/task.go:27 +0xbe

謝謝大佬幫忙看看

**Comment by yuhan6665** [comment]
https://github.com/XTLS/Xray-core/pull/1520

**Comment by cross-hello** [comment]
Is there any tool that could automatically detect golang memory leaks?
We doubt if there is some place maybe error inside  🤔

Jan 11, 2023 22:49:57 yuhan6665 ***@***.***>:

**Comment by yuhan6665** [comment]
@cross-hello pprof

**Comment by RPRX** [comment]
分析详见 https://github.com/XTLS/Xray-core/pull/1520#issuecomment-1383512869 ，https://github.com/XTLS/Xray-core/commit/c83209f6421d68a61ba720292be215123a32ead8 直接申请内存，Go 会定期 GC，不需要显式 release `first` 了，请测试

**Comment by RPRX** [comment]
> @ThreeSourLemon @yuhan6665 @RPRX 谢谢，剛試了first 那個amd64. xtls 連不上。 我把1.72 and first 的ERROR log 附上。谢谢！ config.json 完全一致。。。。 [error-first.log](https://github.com/XTLS/Xray-core/files/10426588/error-first.log) [error-172.log](https://github.com/XTLS/Xray-core/files/10426589/error-172.log) [access-first.log](https://github.com/XTLS/Xray-core/files/10426590/access-first.log) [access-172.log](https://github.com/XTLS/Xray-core/files/10426593/access-172.log)

```
	first := buf.FromBytes(make([]byte, buf.Size))
	first.Clear()
```

改成这个写法应该可行，麻烦测试一下，按 README 编译即可，能连上的话我 force-push

**Comment by RPRX** [comment]
（注意第一行相比之前少了个 0）

**Comment by RPRX** [comment]
@yuhan6665 麻烦帮忙把 main 分支 reset 到上一个 commit

**Comment by yuhan6665** [comment]
好的 没事 你辛苦了 这个问题又让你帮忙

**Comment by RPRX** [comment]
你们手好快，其实。。。我还想加些注释，以防它被改回去。。。

**Comment by RPRX** [comment]
> 好的 没事 你辛苦了 这个问题又让你帮忙

没关系，这个问题是一直存在的，非常感谢你和 @asiaqa 的测试
