### ISSUE TITLE
一个vless地址，几百个用户并发链接

### ISSUE THREAD

**Issue by MrsZ** [XTLS/Xray-core#1516]
服务器配置4c16G，部署的最新版本xray。
前提：网卡 磁盘 负载等性能都正常。

高峰时期一个vless+tcp+xtls 节点大概有200-500左右的用户链接访问。
会导致很多用户无法链接网络，连通率在30-50%左右。
如果降到几十个人链接一个vless 连通率就正常了。

针对这种问题，请问有什么好的改善吗？ 创建多个vless地址  ？或者说一个vless 地址多少并发链接最合适呢。 感谢

**Comment by RPRX** [comment]
服务器访问被代理的网站需要临时端口，看一下是不是临时端口不够用了

**Comment by RPRX** [comment]
（如果是的话，说明你需要多准备些 IP 地址）

**Comment by RPRX** [comment]
或者扩大临时端口范围，我印象中两倍应该没问题

**Comment by MrsZ** [comment]
好的感谢。
我去进行排查一下是否是端口用完的问题。

您之前有测试过一个vless地址跑多少个并发最合适吗？如果端口够用的情况下。

**Comment by RPRX** [comment]
硬件够用、端口够用，理论上无限并发
服务端的临时端口耗尽是因为用户很多，500 个用户，一个用户同时用 20 个端口，就要 10000 个端口了

~~当然，可以写一些代码来复用请求端口，TCP 四元组不同就行，只是我不开机场，暂时没有这方面的需求~~

**Comment by MrsZ** [comment]
好的，非常感谢。

**Comment by RPRX** [comment]
先关了。所以的确是临时端口耗尽的问题吗？
