### ISSUE TITLE
inbound Socks 协议流量统计异常

### ISSUE THREAD

**Issue by denwork** [XTLS/Xray-core#1522]
用xray搭建的主机，inbound使用的socks协议。但是发现流量统计有问题，没办法判断公司员工使用流量的情况。
```
./xray api statsquery --server=127.0.0.1:10085 -pattern ""
{
    "stat":  [
        {
            "name":  "user>>>ppp_3>>>traffic>>>uplink",
            "value":  "6594"
        },
        {
            "name":  "user>>>ppp_3>>>traffic>>>downlink",
            "value":  "24053"
        }
    ]
}
```
看youtube视频，过一段时间以后依然是这样。只会增加很少部分的流量。查看日志发现使用udp的协议加载视频。udp传输的流量没有统计在内。
```
2023/01/11 17:41:05 udp:202.77.21.180:38325 accepted udp:64.233.189.113:443 [direct]
2023/01/11 17:41:07 udp:202.77.21.180:41163 accepted udp:8.8.8.8:53 [direct]
2023/01/11 17:41:08 udp:202.77.21.180:40439 accepted udp:172.217.163.42:443 [direct]
2023/01/11 17:41:08 udp:202.77.21.180:47686 accepted udp:8.8.8.8:53 [direct]
2023/01/11 17:41:09 udp:202.77.21.180:37457 accepted udp:142.251.43.22:443 [direct]
```

**Comment by denwork** [comment]
github.com/xtls/xray-core/app/proxyman/inbound/worker.go

![image](https://github.com/XTLS/Xray-core/assets/21987200/f78bf430-427a-44fe-9acd-10424e30ac0f)

socks5代理总是走不到里面，uplink和downlink总是为nil。所以造成当socks5使用udp传输流量时，无法正常统计到流量。
不知道正常的udp流量统计是否在这个地方？谁能解释解释？

**Comment by FanXinShi233** [comment]
我今天也遇到了一样的问题，看youtube不计算流量。

**Comment by denwork** [comment]
能力有限，至今找不到办法解决。只能期待那位大神能出来处理一下。
应该是udp传输无法关联到对应的counter上面导致的

**Comment by yuhan6665** [comment]
Should be fixed in 1.8.9. Reopen if still happens
