### ISSUE TITLE
Memory leak ? 2GB Memory usage

### ISSUE THREAD

**Issue by ffallah** [XTLS/Xray-core#1523]
My Xray version 1.6.6 is consuming more than 2GB of memory. it is configured in vless+ws+tls mode.
The bandwidth usage is about 100-200mbps with several hundred of clients.
Is it normal for Xray to use this much of memory ?
When I restart the Xray the memory usage goes down significantly but It eventually builds up again.

**Comment by SakuraSakuraSakuraChan** [comment]
@ffallah Try Verysimple

**Comment by HeXis-YS** [comment]
That should be a normal memory consumption with several hundred clients. If you want to reduce memory usage further, try reducing the value of `bufferSize`.

**Comment by Fangliding** [comment]
dup
