### ISSUE TITLE
想问一下shadowrocket连接后无法上网的问题

### ISSUE THREAD

**Issue by e1lite** [XTLS/Xray-core#1526]
我的ipad上用shadowrocket启用节点后，连通性测试没有问题，能实时宣示，但无法上外网，我目前用的是xray1.7.2版本，协议是XTLS Vision，请问是哪里出问题了，如何解决，谢谢

**Comment by FranzKafkaYu** [comment]
@e1lite 目前应该没有IOS客户端支持xtls-rprx-vison流控，为了兼容普通的tls模式，请在服务端将flow配置为“xtls-rprx-vison,none”试试。

**Comment by e1lite** [comment]
> @e1lite 目前应该没有IOS客户端支持xtls-rprx-vison流控，为了兼容普通的tls模式，请在服务端将flow配置为“xtls-rprx-vison,none”试试。

非常感谢大佬！我按照您的方法已经解决了问题，真的谢谢您！！

**Comment by alireza1023** [comment]
> @e1liteAt present, no IOS client should support xtls-rprx-vison flow control. In order to be compatible with the normal tls mode, please try to configure the flow as "xtls-rprx-vison,none" on the server.

but it worked in 1.6.1
now I disable XTLS Direct in shadowrocket and it works

**Comment by SakuraSakuraSakuraChan** [comment]
@alireza1023 There is no vision flow in 1.6.1

**Comment by alireza1023** [comment]
> @e1liteAt present, no IOS client should support xtls-rprx-vison flow control. In order to be compatible with the normal tls mode, please try to configure the flow as "xtls-rprx-vison,none" on the server side.

now ShadowRocket supports Vision
