### ISSUE TITLE
I need instructions for configuring xtls vision fallback vless/vmess ws. I Use Caddy. Give me the most powerful configuration

### ISSUE THREAD

**Issue by Thaomtam** [XTLS/Xray-core#1527]

**Comment by FranzKafkaYu** [comment]
@Thaomtam Why don't use "please" here.Nobody cares what you want.And if you want help,please be polite first.And there are a lot of examples that you can refer to,like this [one](https://github.com/XTLS/Xray-examples/blob/main/All-in-One-fallbacks-Nginx/server.json)

**Comment by Thaomtam** [comment]
> @Thaomtam Why don't use "please" here.Nobody cares what you want.And if you want help,please be polite first.And there are a lot of examples that you can refer to,like this [one](https://github.com/XTLS/Xray-examples/blob/main/All-in-One-fallbacks-Nginx/server.json)

I write with google translate. I'm not good at English. I'm really sorry buddy
