### ISSUE TITLE
I have an idea about xtls fallback warp.

### ISSUE THREAD

**Issue by Thaomtam** [XTLS/Xray-core#1528]
Instead of leaving the warp in the outbound, if I place the warp in the fallback or inboud. Will it change.
This is my configuration: 
{
    "log": {
        "loglevel": "debug"
    },
    "inbounds": [
        {
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "XTLS-VISION-X",
                        "flow": "xtls-rprx-vision",
                        "level": 0,
                        "email": "mtem16557@gmail.com",
                        "alterId": 0
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": 1310, 
                        "xver": 1
                    },
                    {
                        "path": "/Vless",
                        "dest": 1234,
                        "xver": 1
                    },
                    {
                        "path": "/TCP", 
                        "dest": 2345,
                        "xver": 1
                    },
                    {
                        "path": "/Vmess", 
                        "dest": 3456,
                        "xver": 1
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "certificates": [
                        {
                            "certificateFile": "/usr/local/etc/xray/ssl/xray_ssl.crt",
                            "keyFile": "/usr/local/etc/xray/ssl/xray_ssl.key"
                        }
                    ]
                }
            }
        },
        {
            "port": 1310,
            "listen": "127.0.0.1",
            "protocol": "trojan",
            "settings": {
                "clients": [
                    {
                        "password": "XTLS-VISION-X", 
                        "level": 0,
                        "email": "ngthanhhuy951@gmail.com"
                    }
                ],
                "fallbacks": [
                    {
                        "dest": 8080 
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "none",
                "tcpSettings": {
                    "acceptProxyProtocol": true
                }
            }
        },
        {
            "port": 1234,
            "listen": "127.0.0.1",
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "XTLS-VISION-X", 
                        "level": 0,
                        "email": "ngthanhhuy951@gmail.com"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "ws",
                "security": "none",
                "wsSettings": {
                    "acceptProxyProtocol": true, 
                    "path": "/Vless" 
                }
            }
        },
        {
            "port": 2345,
            "listen": "127.0.0.1",
            "protocol": "vmess",
            "settings": {
                "clients": [
                    {
                        "id": "XTLS-VISION-X", 
                        "level": 0,
                        "email": "ngthanhhuy951@gmail.com"
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "none",
                "tcpSettings": {
                    "acceptProxyProtocol": true,
                    "header": {
                        "type": "http",
                        "request": {
                            "path": [
                                "/TCP" 
                            ]
                        }
                    }
                }
            }
        },
        {
            "port": 3456,
            "listen": "127.0.0.1",
            "protocol": "vmess",
            "settings": {
                "clients": [
                    {
                        "id": "XTLS-VISION-X", 
                        "level": 0,
                        "email": "ngthanhhuy951@gmail.com"
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "security": "none",
                "wsSettings": {
                    "acceptProxyProtocol": true, 
                    "path": "/Vmess" 
                }
            }
        }
    ],
    "outbounds":[
        {
            "tag":"INTERNET_OUT",
            "protocol":"freedom"
        },
        {
           "protocol": "wireguard",
           "settings": {
                "secretKey": "QzzSp/BaBlC/q5ZCVpMDc0SDspu4a3LlSCByd+0wsgE=",
                "peers": [
                       {
                          "publicKey": "bmSOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
                          "endpoint": "162.259.293.9:2408"
                       }
                   ]
              },
           "tag": "wireguard-1"
         }
    ],
    "routing":{
        "domainStrategy": "IPIfNonMatch",
        "rules":[
            {
                "type":"field",
                "outboundTag":"wireguard-1",
                "domain":[
                    "geosite:netflix",
                    "geosite:google",
                    "domain:ip.gs"
                ]
            },
            {
                "type":"field",
                "outboundTag":"INTERNET_OUT",
                "network":"udp,tcp"
            }
        ]
    },
    "dns":{
        "servers":[
            "1.1.1.1",
            "1.0.0.1"
        ]
    }
}

**Comment by Fangliding** [comment]
¿
