### ISSUE TITLE
升级到1.7.2以后，用vision，没有速度

### ISSUE THREAD

**Issue by 881997** [XTLS/Xray-core#1530]
部署了CDN+ws+tls 和vision两个
升级到1.7.2以后，vision没有速度，延迟CDN>vision,测速CDN可以到1M以上，vision  0.1M或者0
![微信截图_20230114235710](https://user-images.githubusercontent.com/10362985/212482271-4384f9b9-67d2-433e-9674-a85795c2ca88.png)
![test](https://user-images.githubusercontent.com/10362985/212482278-94353489-9945-4274-b9cf-d3eab2fa4886.png)

服务端配置
{
    "log": {
      "loglevel": "warning",
      "access": "/dev/null",
      "error": "/dev/null"
    },
    "inbounds": [{
      "listen":"127.0.0.1",
      "port": 10000,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "test-id",
            "level": 1,
            "alterId": 0
          }
        ]
      },
          "streamSettings": {
          "network": "ws",
          "wsSettings": {
          "path": "/bannedbook"
          }
      }
    },
  {
      "listen": "0.0.0.0",
      "port": 11111,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "test-id",
            "flow": "xtls-rprx-vision"
          }
        ],
          "decryption": "none"
      },
       "streamSettings": {
          "network": "tcp",
          "security": "tls",
          "tlsSettings": {
                      "rejectUnknownSni": true,
                      "certificates": [
                          {
                              "certificateFile": "/etc/letsencrypt/live/www.xxx.com/fullchain.pem",
                              "keyFile": "/etc/letsencrypt/live/www.xxx.com/privkey.pem"
                          }
                      ]
                  }
        },
       "sniffing": {
                  "enabled": true,
                  "destOverride": [
                      "http",
                      "tls"
                  ]
              }
    }
 ],
    "outbounds": [
      {
        "protocol": "freedom",
        "settings": {},
        "tag": "allowed"
      },
      {
        "protocol": "blackhole",
        "settings": {},
        "tag": "blocked"
      }
    ],
    "routing": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "geoip:private"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  }

**Comment by FranzKafkaYu** [comment]
@881997 请贴出配置文件。

**Comment by chika0801** [comment]
看了你的服务器配置，没什么特别的，也没有问题。

不要用v2rayN自带的测速功能，你至少去speedtest.net网页版跑一下。建议你关了这ISS。
