### ISSUE TITLE
建议内置dns可以自定义ttl缓存时间和缓存数量

### ISSUE THREAD

**Issue by wenzhuning** [XTLS/Xray-core#1531]
建议内置dns可以自定义ttl缓存时间和缓存数量

**Comment by wenzhuning** [comment]
这个功能的需求场景是：对于客户端来说，dns的解析结果并不重要，因为服务端会重新解析一次，fakedns会污染解析结果，如果可以自定义ttl，那么我可以将解析结果设置一个很长的时间，这样就能降低dns解析带来的耗时，提高访问体验

**Comment by mirror1342** [comment]
你的意思是不代理DNS流量，直接向运营商查询？那还有什么耗时的，都是秒回。

**Comment by Fangliding** [comment]
唔 DNS
