### ISSUE TITLE
想问一下关于tiktok的问题

### ISSUE THREAD

**Issue by e1lite** [XTLS/Xray-core#1535]
我用的内核是xray1.7.2，然后协议是vless+tcp+xtls vision，结果我发现即使用浏览器，我也无法打开tiktok的网页版，然后我根据网上一些教程，把whoer.net的伪装度调到了100%网页版还是打不开，而且我的ipad应该没有用xtls vision协议，但也打不开网页。想问一下是哪里的问题，有解决方法吗？谢谢大家了。

**Comment by kkd8** [comment]
是你的服务器有问题

**Comment by e1lite** [comment]
> 是你的服务器有问题，服务端与客户端的配置贴出来，log信息这些。

好的，我去重新检查了下服务端的设置，发现我原先没有DNS设置，现在我照教程添加了DNS设置之后可以正常打开了，谢谢您！
