### ISSUE TITLE
请问如何防止DNS泄露

### ISSUE THREAD

**Issue by e1lite** [XTLS/Xray-core#1538]
我用的内核是xray1.7.2，然后协议是vless+tcp+xtls vision，我在服务端里用的是教程里的DNS设置，就是这个:
![_RH48D8CD4LLN)JL{M]%WBH(1).png](https://user-images.githubusercontent.com/119770322/212900748-4261a40d-53f3-4660-ae9f-eaaaaf156c52.png)
但我在whoer.net进行DNS泄露测试时，还是显示我的DNS查询不受保护。想问一下应该如何修改设置可以解决这个问题呢？谢谢大家了。

**Comment by chika0801** [comment]
和服务器配置无关。

和你用户的客户端加怎么设置有关。

pc的v2rayn 安卓的ng 等，这里几句说不清楚，你有兴趣研究来xraytg群问吧。

建议你不要在意这些dns泄露测试。比如大家用passwall ssrp+翻墙的都有这现象。

**Comment by e1lite** [comment]
> 

哦哦好的明白了，谢谢您！
