### ISSUE TITLE
xtls-rprx-vision是否不支持fallback

### ISSUE THREAD

**Issue by barton0426** [XTLS/Xray-core#1541]
从老版本xtls切换到xtls-rprx-vision后，发现fallback不能正常工作了，另一个端口的xtls fallback正常 
求助 感谢
{
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "****",
                        "flow": "xtls-rprx-vision,none"                        
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": 880,
                        "xver": 1
                    },
		   {
                        "path": "/tmhhost",
                        "dest": 12345,
                        "xver": 1
		    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "certificates": [
                        {
                            "certificateFile": "/etc/ssl/xray/fullchain.pem",
                            "keyFile": "/etc/ssl/xray/privkey.pem"
                        }
                    ]
                }
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            }
        }

**Comment by RPRX** [comment]
否，对比时请严格控制变量
