### ISSUE TITLE
Python API

### ISSUE THREAD

**Issue by hiddify1** [XTLS/Xray-core#1543]
We have just developed python API for Xray. 
I think it will help all to better use Xray :)

https://github.com/hiddify/xtlsapi

**Comment by RPRX** [comment]
`Installation` 和 `GUI Clients` 等确实很久没有更新了，这样吧，大家把基于 Xray-core 的项目（任何）跟贴发到这个 issue，我们会在下个版本前视项目的实际情况，比如比较新颖或 star 多（代表大家已认可），把它们加进 README

**Comment by RPRX** [comment]
（我的意思是，非作者本人也可以提交项目，~~因为作者本人最近可能没空~~）

**Comment by RPRX** [comment]
（我的意思是，非项目作者本人也可以提交，~~因为项目作者本人最近可能没空~~）

**Comment by hiddify** [comment]
I am preparing a simple generic UI for X-UI and i will let you know.

**Comment by RPRX** [comment]
Added.
