### ISSUE TITLE
May I know how to build Android version of xray ?

### ISSUE THREAD

**Issue by passxyz-test** [XTLS/Xray-core#1545]
I saw there is a Android build in each release. May I know how to build it?

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/blob/77d2f9edd7c3badb4738abdae5bda16c29ea287a/.github/workflows/release.yml#L53-L56

**Comment by cross-hello** [comment]
We install golang in termux. And then follow normal compilation steps. 
![Uploading Screenshot_2023_0121_124450.png…]()
