### ISSUE TITLE
想问一下xtls-rprx-vision突然降速是什么问题

### ISSUE THREAD

**Issue by e1lite** [XTLS/Xray-core#1547]
我用的xray1.7.2，协议是xtls-rprx-vision，之前一直都好好的，今天突然网速变得很慢，延迟也变得很高，尤其是安卓端的v2rayNG，平均延迟是2000-4000ms。然后我在测网速的网站测试，平均延迟也是200-400ms，但下载速度仅有1-3mb/s，而且在用app时也达不到这个速度，也就几百k/s，导致实际应用中很卡。

应该不是vps的问题，我问过客服，客服给我的文件直接通过ssh测试的速度是100mb/s。

我最近改动的配置文件就是nginx.conf和xray-config.json里的dns设置，想问一下是这两个问题导致的速度变慢吗，还是其他原因？如何解决延迟高和网速慢的问题呢？谢谢大家，也祝大家新年快乐！

**Comment by chika0801** [comment]
你要说下你vps商家，套餐价格，什么回程线路。

猜你的vps是国际线路回程，速度不稳是回程线路正常波动。

如果你帖nginx 和 xray配置文件，能更好帮你分析。

**Comment by e1lite** [comment]
> 你要说下你vps商家，套餐价格，什么回程线路。
> 
> 猜你的vps是国际线路回程，速度不稳是回程线路正常波动。
> 
> 如果你帖nginx 和 xray配置文件，能更好帮你分析。

我用的是racknerd，是黑色星期五买的vps，16.88$/年，回程线路是这个：
![D P18~BYT37)J_$9XK46EBB](https://user-images.githubusercontent.com/119770322/213845822-9cde9ce0-3bdd-48fe-ba9a-5ea2984ceb49.png)

我的nginx配置文件是这样：
![image](https://user-images.githubusercontent.com/119770322/213845935-2e51dda7-abb8-4a1b-8f89-ac937fbe1699.png)

xray配置文件是这样：
![{8C9`7UVW6CP 7U)$I5SZCJ](https://user-images.githubusercontent.com/119770322/213846252-22e3cca4-db6a-4b21-9585-fa5ca4a93b6d.png)
![Z$WY4`BPSLICFRU9@{Q~PHT](https://user-images.githubusercontent.com/119770322/213846259-96b9f2a3-62e8-4d84-aef8-a8a0a0ecb403.png)
![$3AK%}O_3{0ZTG7LPBCTNP1](https://user-images.githubusercontent.com/119770322/213846266-0ac65164-6db8-485d-8a53-af971ed657f3.png)
![HE6`Q%RZYY9 )JQ%125NXBF](https://user-images.githubusercontent.com/119770322/213846270-37e0d388-c9e1-431b-af8b-c326795c81a0.png)
dns设置那里注释掉了是我以为它是导致延迟高和网速慢的原因。

然后我在v2rayN上出现了这几个问题：
![1{U958 AZ6E(I 95$ICVP27](https://user-images.githubusercontent.com/119770322/213846348-46b1d81f-b0c8-4109-b487-ec492b1d061e.png)
![(RL6`HG_}C4O19WS}T80CBB](https://user-images.githubusercontent.com/119770322/213846364-e9d2f304-09b9-4aa3-b0f9-737b15b31ab5.png)
![image](https://user-images.githubusercontent.com/119770322/213846409-77d9cc34-8e9d-4c55-ba52-33d1f776b693.png)

贴的图可能不太好看，麻烦大家帮我分析一下，谢谢各位

**Comment by chika0801** [comment]
racknerd的机是国际线路，速度不波动才不正常。
建议在这类线路的vps上用hysteria，如果用tcp类的就会出现你客户端觉得时快时卡的体验。

当然你加钱买香港cmi回程日本的软银 iij回程的vps，用tcp类会好些。

**Comment by chika0801** [comment]
看了下你帖图出来的配置没什么问题。你没发dns和路由模块的截图，就不知道了。
建议流控 把none去了，去后，客户端如果是用非vision就连不上。如果你有在ios上用的需要，再写段入站开如trojan tcl tls即可。以后端口被封，也分的开是用哪种组合的被封。

n里面的错误信息，你没遇到打开网页有什么不管它吧，我没事也不管n里的日志。

**Comment by e1lite** [comment]
> 看了下你帖图出来的配置没什么问题。你没发dns和路由模块的截图，就不知道了。
> 建议流控 把none去了，去后，客户端如果是用非vision就连不上。如果你有在ios上用的需要，再写段入站开如trojan tcp tls即可。以后端口被封，也分的开是用哪种组合的端口被封的。
> 
> n里面的错误信息，你没遇到打开网页有什么不管它吧，我没事也不管n里的日志。

哦哦，刚才可能是排版的问题，现在都有了，麻烦你再看一下，哪里的none就是我ipad用来连接的，我去研究下trojan tcp tls。

**Comment by chika0801** [comment]
看了dns和路由部分，你dns不写，就是vps系统默认的，不写吧，我也不爱写了。

geosite cn可不用，不然如果你在路由器上用插件有些莫名问题。虽然你引到了warp,我还是建议你不用。 有geoip cn过滤就行了。

trojan tcp tls去模板复制段入站，粘贴，端口改下不要重了就行，trojan入站里回落不配都成（简单点）就给你ipad上用。

ipad看nf要把你vps解nf搞掉的。

**Comment by e1lite** [comment]
> 看了dns和路由部分，你dns不写，就是vps系统默认的，不写吧，我也不爱写了。
> 
> geosite cn可不用，不然如果你在路由器上用插件有些莫名问题。虽然你引到了warp,我还是建议你不用。 有geoip cn过滤就行了。
> 
> trojan tcp tls去模板复制段入站，粘贴，端口改下不要重了就行，trojan入站里回落不配都成（简单点）就给你ipad上用。
> 
> ipad看nf要把你vps解nf搞掉的。

不好意思隔了几天我又来麻烦您了，我把协议换成了hysteria，连接后流媒体(网飞，hbo，disney+)的网页版均能打开，但app就不行，想问一下是matsuri设置的问题，还是我hysteria协议的问题，怎么修改啊，谢谢了。
