### ISSUE TITLE
是否考虑加入新功能

### ISSUE THREAD

**Issue by divhvs** [XTLS/Xray-core#1550]
因为观察到服务器流量下行总是比上行多，这十分不符合正常网站流量比例。因此是否考虑新增在出站流量中加入随机无效数据的功能，使得出站流量增多。虽然会占用一定的宽带和性能，但是对防墙可能会有一定帮助？

**Comment by xqzr** [comment]
服务器跑 BT
~~防商家~~

**Comment by RPRX** [comment]
~~我觉得这样做对防墙没有帮助，除非你非要买国内云的服务器~~
