### ISSUE TITLE
PCC implement 

### ISSUE THREAD

**Issue by e3lz** [XTLS/Xray-core#1552]
hello , could you try this in the core https://github.com/kaiwenzha/PCC-Vivace
i tried to do it in kernel , but it also require to add function inside core

**Comment by FranzKafkaYu** [comment]
it's inappropriate to implement this in xray core. Xray core is a platform aimed at bypassing censorships, while not for network performance.

**Comment by e3lz** [comment]
I know , but the only way to implement this is within the software , Please Please try to do it at least for the beta version . this as they say in the test improve performance a lot .

**Comment by FranzKafkaYu** [comment]
> I know , but the only way to implement this is within the software , Please Please try to do it at least for the beta version . this as they say in the test improve performance a lot .

it's your personal need and seriously this should be implemented in Kernel.And you can use other methods to realize what you want here. it's inappropriate for xray to implement such feature.Unless you can give specific reasons that why xray core need to implement this.So plz don't waste developer's time and close this issue. Thanks.

**Comment by e3lz** [comment]
thanks for your suggestion , PCC allows to have more stable connection , but bbr only make the connection fast on the beginning of the request , Im experiencing a lot of drop request when i make the request long enough to be recolonized as websocket connection , that's why i asked to do this , maybe china doesn't do this , but if your in iran , GFW will observe the connection frequent length , anyway thanks for your suggestion , i hope developers dig more into this .
