### ISSUE TITLE
希望增加config.json的base64支持，以规避平台对文件关键字的审计

### ISSUE THREAD

**Issue by fscarmen** [XTLS/Xray-core#1555]
现在在一些容器类的平台部署，config.json的内容都是明文的，如inbound / outbound / protocol。
希望能把该文件base64编码后，xray内置解码。

**Comment by fscarmen** [comment]
> #76 同理，这种措施缺乏实际意义 （*ray配置文件可以转pb）

那些容器平台有些需要先上传文件，即使上传经过base64编码，运行之前仍然得解码回来，这样本地就有明文的配置文件了，如果能直接读取编码后的文件就更容易骗过平台不会被删实例和封号。

**Comment by RPRX** [comment]
这样做不如把解析后的 pb 直接嵌入 Xray 可执行文件，如果平台连可执行文件都分析，那里面还有很多特征字符串，~~建议疯狂加壳~~
以前我甚至想过 build 指令 https://github.com/v2fly/v2ray-core/pull/335#issuecomment-717910249
不过 build 指令实现起来比较麻烦，还是编译前 generate 出 pb，然后编译时 embed 吧，只是需要自己编译，PR is welcomed

**Comment by mirror1342** [comment]
解码完走标准输入不就行了

**Comment by yuchen1456** [comment]
感觉可以自己写一下✍

加个前缀，例如bs64:或者bs:
./xray  -c  bs:file

容器一般是用vless或者vmess的ws协议，这样也可以内置一个ws的config，读取config只需PORT和wsPath以及指定vless/vmess，例如我们指定以0.0.0.0开头：

VLESS：
./xray  -c  0.0.0.0:PORT/wsPath/vl
（默认vless，也可以省掉后面的/vl）

VMESS:
./xray  -c  0.0.0.0:PORT/wsPath/vm


以上这样只是在xray  -config  file，进行file的前缀判断，然后处理自己的特殊需求，可以兼容原版，增加功能

**Comment by yuchen1456** [comment]
> 感觉可以自己写一下✍
> 
> 加个前缀，例如bs64:或者bs: ./xray -c bs:file
> 
> 容器一般是用vless或者vmess的ws协议，这样也可以内置一个ws的config，读取config只需PORT和wsPath以及指定vless/vmess，例如我们指定以0.0.0.0开头：
> 
> VLESS： ./xray -c 0.0.0.0:PORT/wsPath/vl （默认vless，也可以省掉后面的/vl）
> 
> VMESS: ./xray -c 0.0.0.0:PORT/wsPath/vm
> 
> 以上这样只是在xray -config file，进行file的前缀判断，然后处理自己的特殊需求，可以兼容原版，增加功能

只需改一下
main/confloader/external/external.go
这个文件里面的ConfigLoader函数，增加一个arg前缀判断和arg处理函数yourConfigHandleFunction即可，
case strings.HasPrefix(arg, "0.0.0.0:"):
		data, err = yourConfigHandleFunction(arg)

**Comment by wy580477** [comment]
在PaaS上我遇到过四种风控：
1. 部署时候审查代码，很少见，只能Railway上碰到过。
2. 构建容器时审查日志，在Heroku上碰到过，出现桌面环境包必被封。
3. 部署后审查进程名，Heroku上碰到过，Rclone只要一跑流量就会被封，但改了名字就没事。
4. 使用量风控，这个常见，经常部署了很久没事，突然跑了很多流量就被封。

依我看，部署后再审查文件内容这种做法，不是太可行，需要消耗大量服务器资源。

**Comment by fscarmen2** [comment]
> 解码完走标准输入不就行了

这个方案符合我希望要的，谢谢你和各位老大的解答。

**Comment by fscarmen** [comment]
> 解码完走标准输入不就行了

这个方案符合我希望要的，谢谢你和各位老大的解答。

**Comment by fscarmen** [comment]
> 解码完走标准输入不就行了

这样是不是在本地仍然有解码后的文件啊？有没有办法直接使用base64编码的，本地不留明文的config.json
因为有的容器类平台需要上传方案，或者需要从github项目导入的，这样他就能搜关键词给风控
我想法是用base64的文件不让他查出来

**Comment by AAkira45** [comment]
首先build好的程序，无论其是否本身加密，都有被关键字的可能，相比于配置文件，如果平台一定要审计，最后一定会落实到程序本身，在这种情况下，你需要的可能不是一个加密的config，你需要的可能是一个更加安全的使用平台，否则即使是只加密config，平台依然可以采用对程序二进制使用关键字等方法进行识别，使用base64编码的文件也具有显著特征，觉得个人在这种使用环境下更应该去采用更加安全的环境去使用。
