### ISSUE TITLE
使用XTLS-RPRX-VISION流控后，无法连接到Tor网络。

### ISSUE THREAD

**Issue by kosakuraiori** [XTLS/Xray-core#1561]
问题症状：
我使用Xray（本地客户端为V2RayN）作为Tor Browser的前置代理。
在几天前我还在使用Shadowsocks+Xray Plugin（协议为WSS）时，这个前置代理是可以直接访问Tor网络的。
但在我更换为Xray（XTLS-RPRX-VISION流控）后，无法连接到Tor网络，必须再前置一个Tor obfs4网桥才可以。
服务器是相同的。

Tor日志：

> 2023-01-26 13:15:58.626 [NOTICE] New control connection opened from 127.0.0.1.
> 2023-01-26 13:15:58.626 [NOTICE] New control connection opened from 127.0.0.1.
> 2023-01-26 13:15:58.632 [NOTICE] DisableNetwork is set. Tor will not make or accept non-control network connections. Shutting down all existing connections.
> 2023-01-26 13:16:00.261 [NOTICE] Opening Socks listener on 127.0.0.1:9150
> 2023-01-26 13:16:00.261 [NOTICE] Opened Socks listener connection (ready) on 127.0.0.1:9150
> 2023-01-26 13:16:00.684 [NOTICE] Bootstrapped 3% (conn_proxy): Connecting to proxy
> 2023-01-26 13:16:00.685 [NOTICE] Bootstrapped 4% (conn_done_proxy): Connected to proxy
> 2023-01-26 13:16:00.687 [NOTICE] Bootstrapped 10% (conn_done): Connected to a relay
> 2023-01-26 13:16:16.719 [WARN] Problem bootstrapping. Stuck at 10% (conn_done): Connected to a relay. (TLS_ERROR; TLS_ERROR; count 10; recommendation warn; host E05562DD7E211267766B3AD67FF1BC981A0A432C at 88.99.70.165:443)
> 2023-01-26 13:16:16.719 [WARN] 10 connections have failed:
> 2023-01-26 13:16:16.719 [WARN] 10 connections died in state handshaking (TLS) with SSL state SSLv3/TLS write client hello in HANDSHAKE
> 2023-01-26 13:16:16.724 [NOTICE] Closing no-longer-configured Socks listener on 127.0.0.1:9150
> 2023-01-26 13:16:16.725 [NOTICE] DisableNetwork is set. Tor will not make or accept non-control network connections. Shutting down all existing connections.
> 2023-01-26 13:16:16.725 [WARN] Problem bootstrapping. Stuck at 10% (conn_done): Connected to a relay. (DONE; DONE; count 11; recommendation warn; host 129611304F3D935351FD2550713487EF2EEA505A at 162.251.116.82:443)
> 2023-01-26 13:16:16.725 [WARN] 11 connections have failed:
> 2023-01-26 13:16:16.725 [WARN] 11 connections died in state handshaking (TLS) with SSL state SSLv3/TLS write client hello in HANDSHAKE
> 2023-01-26 13:16:16.726 [WARN] Problem bootstrapping. Stuck at 10% (conn_done): Connected to a relay. (DONE; DONE; count 12; recommendation warn; host 1F2EB70268CE9E18CE864D44D793E2091F3CE72C at 46.4.57.75:8443)
> 2023-01-26 13:16:16.726 [WARN] 12 connections have failed:
> 2023-01-26 13:16:16.726 [WARN] 12 connections died in state handshaking (TLS) with SSL state SSLv3/TLS write client hello in HANDSHAKE
> 2023-01-26 13:16:16.742 [NOTICE] Delaying directory fetches: DisableNetwork is set.
> 2023-01-26 13:17:21.911 [NOTICE] New control connection opened from 127.0.0.1.

Xray日志：

> 配置成功
> [] [VLESS] (******164:443)
> 启动服务(2023/1/26 21:15:50)...
> Xray 1.7.2 (Xray, Penetrates Everything.) Custom (go1.19.4 windows/amd64)
> A unified platform for anti-censorship.
> 2023/01/26 21:15:50 [Info] infra/conf/serial: Reading config: C:\Users\********\Documents\v2rayN\config.json
> 2023/01/26 21:15:50 [Warning] core: Xray 1.7.2 started
> 2023/01/26 21:15:50 127.0.0.1:49931 accepted tcp:127.0.0.1:0 [api -> api]
> 2023/01/26 21:16:00 tcp:127.0.0.1:49952 accepted tcp:193.122.15.219:443 [socks -> proxy]
> 2023/01/26 21:16:00 tcp:127.0.0.1:49951 accepted tcp:212.83.43.95:443 [socks -> proxy]
> 2023/01/26 21:16:03 tcp:127.0.0.1:49955 accepted tcp:217.160.49.126:443 [socks -> proxy]
> 2023/01/26 21:16:07 tcp:127.0.0.1:49957 accepted tcp:80.92.204.251:9201 [socks -> proxy]
> 2023/01/26 21:16:08 tcp:127.0.0.1:49959 accepted tcp:141.147.45.13:443 [socks -> proxy]
> 2023/01/26 21:16:09 tcp:127.0.0.1:62674 accepted tcp:74.123.98.10:443 [socks -> proxy]
> 2023/01/26 21:16:10 tcp:127.0.0.1:62676 accepted tcp:51.38.65.160:9001 [socks -> proxy]
> 2023/01/26 21:16:11 tcp:127.0.0.1:62680 accepted tcp:109.238.11.6:443 [socks -> proxy]
> 2023/01/26 21:16:12 tcp:127.0.0.1:62684 accepted tcp:193.108.118.209:80 [socks -> proxy]
> 2023/01/26 21:16:13 tcp:127.0.0.1:62686 accepted tcp:88.99.70.165:443 [socks -> proxy]
> 2023/01/26 21:16:14 tcp:127.0.0.1:62689 accepted tcp:162.251.116.82:443 [socks -> proxy]
> 2023/01/26 21:16:15 tcp:127.0.0.1:62691 accepted tcp:46.4.57.75:8443 [socks -> proxy]
> 2023/01/26 21:16:16 tcp:127.0.0.1:62695 accepted tcp:cdn.sstatic.net:443 [socks -> proxy]
> 2023/01/26 21:17:22 tcp:127.0.0.1:62702 accepted tcp:cdn.sstatic.net:443 [socks -> proxy]
> 2023/01/26 21:17:23 tcp:127.0.0.1:62711 accepted tcp:cdn.sstatic.net:443 [socks -> proxy]
> 2023/01/26 21:17:23 tcp:127.0.0.1:62713 accepted tcp:cdn.sstatic.net:443 [socks -> proxy]
> 2023/01/26 21:17:23 tcp:127.0.0.1:62715 accepted tcp:cdn.sstatic.net:443 [socks -> proxy]

**Comment by kosakuraiori** [comment]
> 服务端有没有开启流量嗅探？要关闭

好的我回去看看，我用一键脚本装的，不太清楚配置文件在哪

**Comment by kosakuraiori** [comment]
> 服务端有没有开启流量嗅探？要关闭

服务器没有开启流量嗅探，没有sniffing配置

**Comment by hakter** [comment]
应该不是协议问题，是近期网络环境造成了的，我用vless+ws+cdn一样

**Comment by kosakuraiori** [comment]
> 应该不是协议问题，是近期网络环境造成了的，我用vless+ws+cdn一样

那没法解释为什么我之前用SS+Xray Plugin就没问题
