### ISSUE TITLE
TLS when using Vision flow

### ISSUE THREAD

**Issue by hawshemi** [XTLS/Xray-core#1562]
**Is it normal that TLS is set to TLS when using Vision flow? or should it be XTLS?
Because when I change to XLTS, I cannot connect to the server.
Is Vision flow only on TLS and not XTLS?**

**Comment by PouriaMzn** [comment]
It should be tls and not xtls, the config could be  vless+tcp+tls+vision

**Comment by RPRX** [comment]
XTLS Vision 基于 TLS 库实现了旧 XTLS 库的功能，所以目前 Vision 需要选 TLS 库。

**Comment by RPRX** [comment]
（或 REALITY 库）
