### ISSUE TITLE
support vision in wss ?

### ISSUE THREAD

**Issue by emdaitaj** [XTLS/Xray-core#1566]
i use nginx +wss+vless
(nginx does ssl processing and forwards http ws to xray-core)
i works with direct flow
when vision is used i get : 
2023/01/27 23:50:44 xxxxxx(my client ip):0 rejected  proxy/vless/encoding: failed to read request version > websocket: close 1000 (normal)

vision in direct tls (without nginx+wss) works fine , but it keeps getting detected and  blocked by ISPs so i'm trying to set it up with nginx

so please fix it it is technically possible to use vision inside wss

**Comment by FranzKafkaYu** [comment]
@emdaitaj Impossible. xtls-rprx-vision flow need to handle tls by xray core itself.

**Comment by RPRX** [comment]
REALITY 解决服务端指纹的问题，明后天就出的可能性较大

**Comment by ThreeSourLemon** [comment]
@RPRX 期待

**Comment by RobertHashMan** [comment]
@RPRX Reality is still WIP now?How about release the document to let us know what is "Reality" on earth?

**Comment by RPRX** [comment]
1. 实现 REALITY —— 年前就实现了
2. 把 REALITY 加进 Xray-core —— 到今天写完了
3. 写一篇文章介绍它 —— 尚未完成

我本机直接改 uTLS 库（客户端）和 TLS 库（服务端）实现 REALITY 并不麻烦，但把它包装成普通用户能配置的 `security` 比想象中麻烦一些，因为配置方式、逻辑等与 TLS 完全不同，不像当年加 XTLS 可以直接复制 TLS 的支持代码，比当年加 XTLS 麻烦很多

好在已经写完了，@yuhan6665 会先拿到代码进行测试，预计于 2.2 发布代码、模板和文章

**Comment by FranzKafkaYu** [comment]
撒花撒花:sparkles:，希望能时不时透露一下进度！ @RPRX @yuhan6665
