### ISSUE TITLE
考虑加入SSR

### ISSUE THREAD

**Issue by Alion548** [XTLS/Xray-core#157]
大佬有没有考虑加入SSR协议

**Comment by AkinoKaede** [comment]
我觉得没必要，ShadowsocksR 已经很多年没有维护过了

**Comment by rprx** [comment]
首先感谢水 issue，不过 Xray 的 http header 等似乎已经可以满足 SSR 的需求？

**Comment by z826540272** [comment]
有好处，因为很多大机场用的ssr

**Comment by Rakau** [comment]
个人觉得没必要，一个停了3年的项目。而且加密没有AEAD，且自带混淆的功能特征一大堆，我实在没想到用SSR人是想干什么？游戏？

**Comment by Alion548** [comment]
有些机场还在使用SSR

**Comment by Butterflyflower** [comment]
@Alion548 SSR没有人维护了🙈

**Comment by ymcoming** [comment]
> 有些机场还在使用SSR

如果你只是为了用机场的SSR，那跟xray无关呀！这最多是NG的事。

**Comment by Alion548** [comment]
> > 有些机场还在使用SSR
> 
> 如果你只是为了用机场的SSR，那跟xray无关呀！这最多是NG的事。

要看xray的定位，如果是一个工具集合，那再支持一个还有用户使用率的协议也是好的。NG只是个GUI不关NG的事情。

**Comment by Alion548** [comment]
不过我觉得要摒弃SSR机场，老旧协议没多大支持必要，还是把精力用在其它如xUDP上面吧。

**Comment by z826540272** [comment]
> 个人觉得没必要，一个停了3年的项目。而且加密没有AEAD，且自带混淆的功能特征一大堆，我实在没想到用SSR人是想干什么？游戏？

有aead，而且是最先有的

**Comment by z826540272** [comment]
> 不过我觉得要摒弃SSR机场，老旧协议没多大支持必要，还是把精力用在其它如xUDP上面吧。
这样的话，没优势的重复协议都可以删了
ss客户端不好用，用的人应该不多
