### ISSUE TITLE
[HELP] Server A to Server B with real user ip

### ISSUE THREAD

**Issue by MrVb0** [XTLS/Xray-core#1575]
Hello
I have 2 servers: server A and server B
Server A is in my country and Server B is in a foreign country
I want to bypass filtering by installing xrayr on server B (V2board-XrayR).
But direct connections to forigen servers from the GFW side are severely disrupted
So I want to establish a connection from server A to server B as follows:
Client > Server A > Server B (XrayR)

- I want the user's real IP to reach server B. (to use Global Device Limit XrayR)
- Also, I want some of the sites and IPs I want not to go to the server and open directly with server A (preferably open with the user's real IP / or / at least open with the IP of server A)
- I want this traffic from server A to server B to look clean and away from GFW's view

Is this possible with xray-core?
How can I do this?
Thank you for helping me in this work.

**Comment by DeAref** [comment]
you should install xray on **server A** and use outbound to send traffic for **server B**

https://xtls.github.io/config/outbound.html#outboundobject

**Comment by Fangliding** [comment]
proxy protocol
