### ISSUE TITLE
DNS出站代理的奇怪行为

### ISSUE THREAD

**Issue by longxk** [XTLS/Xray-core#1576]
### 需求
透明代理所有流量到局域网内某Socks代理，同时劫持所有DNS请求，也通过该Socks代理转发到tcp://1.1.1.1:53。

### 配置
参考文档: [TProxy 透明代理](https://xtls.github.io/document/level-2/tproxy.html) 配置iptables和Xray，将流量都转发到Xray透明代理端口处理。Xray配置附在最后。

### 问题
DNS出站代理配置中的settings和proxySettings似乎都没有生效。
DNS请求仍然发往系统默认DNS服务器，并被默认出站代理blackhole拦截。

感觉预期行为应该是：
1. DNS请求改写为DNS出站配置中network, address, port
2. DNS请求通过proxySettings中指定的代理发出

目前的变通实现是：
1. 配置内置DNS服务器，配置上游为tcp://1.1.1.1
2. 配置路由规则指定内置DNS服务器的流量转发到Socks代理

**xray_config.json**

```
{
  "log": {
    "loglevel": "info"
  },

  //workaround
  "dns": {
    "servers": [
      "tcp://1.1.1.1:53"
    ],
    "tag": "dns-server"
  },

  "inbounds": [
    {
      "port": 12345,
      "protocol": "dokodemo-door",
      "settings": {
        "network": "tcp,udp",
        "followRedirect": true
      },
      "streamSettings": {
        "sockopt": {
          "tproxy": "tproxy"
        }
      }
    }
  ],

  "outbounds": [
    {
      "tag": "socks-proxy",
      "protocol": "socks",
      "settings": {
        "servers": [
          {
            "address": "192.168.11.66",
            "port": 6666
          }
        ]
      }
    },

    {
      "tag": "dns-hijack",
      "protocol": "dns",
      "settings": {
        "network": "tcp",
        "address": "1.1.1.1",
        "port": 53
      },
      "proxySettings": {
        "tag": "socks-proxy"
      }
    }
  ],

  "routing": {
    "rules": [
      //workaround
      {
        "type": "field",
        "inboundTag": ["dns-server"],
        "outboundTag": "socks-proxy"
      },
      {
        "type": "field",
        "port": 53,
        "outboundTag": "dns-hijack"
      }
    ]
  }
}
```

**Comment by wy580477** [comment]
给你改了一下，tproxy入站以后，udp dns请求会被劫持到协议为dns的出站，这样dns请求会被内置的dns模块处理，也就文件中指定的tcp://1.1.1.1:53。

```
{
  "dns": {
    "servers": [
      "tcp://1.1.1.1:53"
    ]
  },
  "inbounds": [
    {
      "port": 12345,
      "protocol": "dokodemo-door",
      "settings": {
        "network": "tcp,udp",
        "followRedirect": true
      },
      "streamSettings": {
        "sockopt": {
          "tproxy": "tproxy"
        }
      }
    }
  ],
  "outbounds": [
    {
      "tag": "socks-proxy",
      "protocol": "socks",
      "settings": {
        "servers": [
          {
            "address": "192.168.11.66",
            "port": 6666
          }
        ]
      }
    },
    {
      "protocol": "dns",
      "tag":  "dns-out"
    }
  ],
  "routing": {
    "rules": [
      {
        "type": "field",
        "port": 53,
        "network": "udp",
        "outboundTag": "dns-out"
      }
    ]
  }
}
```

**Comment by longxk** [comment]
@wy580477 是的，我上面提到的变通实现就是这样。
我的问题是：DNS出站协议的settings和proxySettings没有效果吗？
这篇官方文档：[TProxy 透明代理](https://xtls.github.io/document/level-2/tproxy.html)，配置了DNS出站的settings和proxySettings，但是实际上应该是没有效果的，最终也是通过内置DNS服务器，由路由或者默认出站代理出站。

**Comment by Lithium768** [comment]
端口53路由到 `dns_hijack` 会先将请求交由内置 dns 解析, 内置 dns 不写的话默认就是走系统 dns.
只有内置 dns 解析不了的请求才会真的走 `dns_hijack` 发出.

**Comment by longxk** [comment]
> 端口53路由到 `dns_hijack` 会先将请求交由内置 dns 解析, 内置 dns 不写的话默认就是走系统 dns. 只有内置 dns 解析不了的请求才会真的走 `dns_hijack` 发出. 单纯只想劫持建议尝试用 freedom 出站配置 redirect 实现.

你是指iptables REDIRECT吗？
这个没办法实现将UDP的DNS请求，**改写为TCP协议**，并转发到特定服务器。

**Comment by Lithium768** [comment]
> > 端口53路由到 `dns_hijack` 会先将请求交由内置 dns 解析, 内置 dns 不写的话默认就是走系统 dns. 只有内置 dns 解析不了的请求才会真的走 `dns_hijack` 发出. 单纯只想劫持建议尝试用 freedom 出站配置 redirect 实现.
> 
> 你是指iptables REDIRECT吗？ 这个没办法实现将UDP的DNS请求，**改写为TCP协议**，并转发到特定服务器。

```
{
    "protocol": "freedom",
    "tag":  "dns-out",
    "settings": {
        "redirect": "1.1.1.1:53"
    },
    "proxySettings": {
        "tag": "socks-proxy"
    }
}
```

**Comment by Smallthing** [comment]
弄个unbound用iptables转发不香吗？

**Comment by longxk** [comment]
不折腾了，使用变通实现
