### ISSUE TITLE
XTLS-RPRX-VISION中反向代理的Mux是否被自动被启用？

### ISSUE THREAD

**Issue by arlequinfei** [XTLS/Xray-core#1579]
目前使用xray做了一个内网穿透的功能来实现公司内网的访问。
有个小小的问题请教下各位大佬们。

配置使用的是[官方文档](https://xtls.github.io/config/reverse.html)的配置，没有加多余的东西，只是改为vless+tls+xtls-rprx-vision

在客户端使用XTLS-RPRX-VISION流控制时，启用mux，提示：

```text
[Warning] failed to handler mux client connection > proxy/vless/outbound: xtls-rprx-vision doesn't support Mux
```

查看[相关文档](https://xtls.github.io/config/reverse.html#reverseobject)，说在

```text
反向代理默认已开启 [Mux](https://xtls.github.io/development/protocols/muxcool/)，请不要在其用到的 outbound 上再次开启 Mux。
```

所以想知道XTLS-RPRX-VISION流控制中，反向代理的Mux是什么状态？担心配置不合理影响并发。

**Comment by cross-hello** [comment]
No, vision don't support MUX( for using of XUDP)

**Comment by cross-hello** [comment]
ref: https://github.com/XTLS/Xray-core/pull/1567

**Comment by Fangliding** [comment]
估计不会触发vision特性
