### ISSUE TITLE
usage of protobuf

### ISSUE THREAD

**Issue by khordady** [XTLS/Xray-core#1580]
hi, I would like to know where did you use of Protobuf in your code. I'm new to Go and Protobuf and studying them in real world help me get advanced. Thank you for your great project.😘

**Comment by SakuraSakuraSakuraChan** [comment]
@khordady gRPC, I suppose

**Comment by khordady** [comment]
yes I know gRPC, but i meant which part of data transferring? And why choosed gRPC in that part?

**Comment by RPRX** [comment]
1. 加载配置与 API
2. VLESS Addons
3. gPRC（gRPC 就是用 ProtoBuf 编码，没看懂你在问什么）
