### ISSUE TITLE
1.7.3 release action run failed

### ISSUE THREAD

**Issue by smallprogram** [XTLS/Xray-core#1582]

**Comment by smallprogram** [comment]
repairing.....

**Comment by FranzKafkaYu** [comment]
it seems that quic-go can't build with go1.20，I got this error：  

Error: ../../../go/pkg/mod/github.com/lucas-clemente/quic-go@v0.31.1/internal/qtls/go120.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.20 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.20 yet. F...) as int value in variable declaration

**Comment by RPRX** [comment]
被 GitHub 背刺两次，一次是上传时默认丢掉 .github 文件夹，一次是 1.20 被识别成 1.2，加引号解决了，~~CI 的默认示例要更新了~~

现在还有一个小问题是：如何用最新的 release.yml 去跑 release v1.7.3？Re-run action 还是会用旧版 release.yml

**Comment by FranzKafkaYu** [comment]
@RPRX 直接删除pre-release的版本，同时需要删除tag，重新跑action

**Comment by RPRX** [comment]
> @RPRX 直接删除pre-release的版本，同时需要删除tag，重新跑action

目前不倾向于这样做

**Comment by FranzKafkaYu** [comment]
> > @RPRX 直接删除pre-release的版本，同时需要删除tag，重新跑action
> 
> 目前不倾向于这样做

貌似没有更好的选择~

**Comment by RPRX** [comment]
> > > @RPRX 直接删除pre-release的版本，同时需要删除tag，重新跑action
> > 
> > 
> > 目前不倾向于这样做
> 
> 貌似没有更好的选择~

有的，我看到可以手动跑指定分支的 release.yml，想到一个办法：fork 出一个分支，把 release 判断取反，然后手动跑它

**Comment by smallprogram** [comment]
我这为啥没毛病捏。。。
![image](https://user-images.githubusercontent.com/6050360/216259772-0653b65d-b746-454c-8cf2-8ef72fd98db6.png)

**Comment by RPRX** [comment]
Update：完美达成目标，分支名必须与目标 tag 同名（该分支已删）

**Comment by FranzKafkaYu** [comment]
> Update：完美达成目标，分支名必须与目标 tag 同名（该分支已删）

学到了~
