### ISSUE TITLE
为什么查询dns后任务不会释放什么原因？

### ISSUE THREAD

**Issue by qiuxiangling** [XTLS/Xray-core#1586]
![1675331364552](https://user-images.githubusercontent.com/68261800/216290885-ad3bf697-bc2e-40c2-8d43-1aeb98c44a08.png)

使用tproxy透明代理配置的
https://xtls.github.io/document/level-2/tproxy_ipv4_and_ipv6.html

**Comment by qiuxiangling** [comment]
不释放的原因 时缓存吗？

**Comment by SQLimit** [comment]
> 不释放的原因 时缓存吗？

可以试一下 "disableCache": true

**Comment by qiuxiangling** [comment]
> > 不释放的原因 时缓存吗？
> 
> 可以试一下 "disableCache": true

![(AIK7K$7ASO`5WYFEAY}`3D](https://user-images.githubusercontent.com/68261800/216492653-30107c36-4261-4beb-8970-ce584b472a09.png)
![$)9ORC(8YI9V0BPDG1Q3 `T](https://user-images.githubusercontent.com/68261800/216492954-3fa293b9-0988-47d1-ae73-249348028cdb.png)

我加了禁用缓存后， 还是这样， 这是是不是正常现象？

**Comment by ttc0419** [comment]
之前在v2rayNG也汇报过类似问题，服务端trojan-go dns查询产生的tcp连接不会关闭，详见https://github.com/2dust/v2rayNG/issues/1940

**Comment by qiuxiangling** [comment]
负责dns这块的大佬  来解释一下呗， 小内存的路由器一直这样下去不内存满了

**Comment by SQLimit** [comment]
> 负责dns这块的大佬  来解释一下呗， 小内存的路由器一直这样下去不内存满了 

你贴一下客户端配置，看看

**Comment by qiuxiangling** [comment]
> > 负责dns这块的大佬  来解释一下呗， 小内存的路由器一直这样下去不内存满了
> 
> 你贴一下客户端配置，看看

{
  "log": {
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "all-in",
      "port": 1080,
      "protocol": "dokodemo-door",
      "settings": {
        "network": "tcp,udp",
        "followRedirect": true
      },
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      },
      "streamSettings": {
        "sockopt": {
          "tproxy": "tproxy",
          "mark": 255
        }
      }
    }
  ],
  "outbounds": [
    {
      //此为默认outbound，路由(routing)模块若未匹配到任何规则，则默认走此 proxy 出口，如果你希望直连国内优先请将下面 direct 出口放到 outbound 第一，看不懂可忽略
      "tag": "proxy",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "yourdomain.domain", //改为你自己的域名，直接填写ipv4或ipv6地址也可以
            "port": 443,
            "users": [
              {
                "id": "uuid", //填写uuid，可通过在终端中输入 xray uuid 生成；此处也支持任意字符串（https://xtls.github.io/config/inbounds/vless.html#clientobject）
                "encryption": "none",
                "flow": "xtls-rprx-vision"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "sockopt": {
          "mark": 255
        },
        "network": "tcp",
        "security": "tls", //注意使用 xtls-rprx-vision 流控此处需为 tls
        "tlsSettings": {
          //注意使用 xtls-rprx-vision 流控此处需为 tlsSettings
          "allowInsecure": false,
          "serverName": "yourdomain.domain", //改为你自己的域名
          "fingerprint": "chrome" //模拟TLS Client Hello指纹，可选 chrome, firefox, safari, randomized, 具体参考 https://xtls.github.io/config/transport.html#tlsobject
        }
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP"
      },
      "streamSettings": {
        "sockopt": {
          "mark": 255
        }
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    },
    {
      "tag": "dns-out",
      "protocol": "dns",
      "streamSettings": {
        "sockopt": {
          "mark": 255
        }
      }
    }
  ],
  "dns": {
    "servers": [
      {
        "address": "联通派dns",
        "port": 53,
        "domains": [
          "geosite:cn",
          "ntp.org"
        ]
      },
      {
        "address": "联通派dns备",
        "port": 53,
        "domains": [
          "geosite:cn",
          "ntp.org"
        ]
      },
      {
        "address": "8.8.8.8",
        "port": 53,
        "domains": ["geosite:geolocation-!cn"]
      },
      {
        "address": "1.1.1.1",
        "port": 53,
        "domains": ["geosite:geolocation-!cn"]
      }
    ]
  },
  "routing": {
    "domainMatcher": "hybrid",
    "domainStrategy": "IPIfNotMatch",
    "rules": [
      {
        "type": "field",
        "inboundTag": ["all-in"],
        "port": 53,
        "network": "udp",
        "outboundTag": "dns-out"
      },
      {
        "type": "field",
        "inboundTag": ["all-in"],
        "port": 123,
        "network": "udp",
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "inboundTag": ["all-in"],
        "port": chronyd_port,
        "network": "udp",
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "ip": ["联通派dns", "联通派dns备"],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "ip": ["8.8.8.8", "1.1.1.1"],
        "outboundTag": "proxy"
      },
      {
        "type": "field",
        "domain": ["geosite:category-ads-all"],
        "outboundTag": "block"
      },
      {
        "type": "field",
        "protocol": ["bittorrent"],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "ip": ["geoip:private", "geoip:cn"],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "domain": ["geosite:cn"],
        "outboundTag": "direct"
      }
    ]
  }
}

**Comment by qiuxiangling** [comment]
> > 负责dns这块的大佬  来解释一下呗， 小内存的路由器一直这样下去不内存满了
> 
> 你贴一下客户端配置，看看

我配置中把注释去掉了， 就把国内dns换了， 还有加了chronyd服务器端口直连的配置

**Comment by qiuxiangling** [comment]
> > 负责dns这块的大佬  来解释一下呗， 小内存的路由器一直这样下去不内存满了
> 
> 你贴一下客户端配置，看看
防火墙也是tproxy代理页面的防火墙配置
https://xtls.github.io/document/level-2/tproxy_ipv4_and_ipv6.html
用的nft

**Comment by SQLimit** [comment]
> > > 负责dns这块的大佬  来解释一下呗， 小内存的路由器一直这样下去不内存满了
> > 
> > 
> > 你贴一下客户端配置，看看
> > 防火墙也是tproxy代理页面的防火墙配置
> > https://xtls.github.io/document/level-2/tproxy_ipv4_and_ipv6.html
> > 用的nft

配置看起来没什么问题，有一点，那个routing里的strategy，IPIfNonMatch，是我没看仔细，一直写的是Not，这个是我太菜，你改一下。
看你IP 172.20.1.1是内网IP吧，应该是域名和你配置的所有dns都不匹配，走localhost了？你可以试试在dns的server里加“119.29.29.29”，让解析不到的网址用这个试试。

**Comment by qiuxiangling** [comment]
> > > > 负责dns这块的大佬  来解释一下呗， 小内存的路由器一直这样下去不内存满了
> > > 
> > > 
> > > 你贴一下客户端配置，看看
> > > 防火墙也是tproxy代理页面的防火墙配置
> > > https://xtls.github.io/document/level-2/tproxy_ipv4_and_ipv6.html
> > > 用的nft
> 
> 配置看起来没什么问题，有一点，那个routing里的strategy，IPIfNonMatch，是我没看仔细，一直写的是Not，这个是我太菜，你改一下。 看你IP 172.20.1.1是内网IP吧，应该是域名和你配置的所有dns都不匹配，走localhost了？你可以试试在dns的server里加“119.29.29.29”，让解析不到的网址用这个试试。

根据目前观察 不是不会关闭， 是要经过一段时间后才会关闭

这样写域名解析没问题， 所有dns查询会在防火墙拦截，然后进入xray，xray来代理dns解析工作（怎么实现这就不清楚了，原谅我不会go语言，还没阅读代码go代码的能力） 

但是dns反向解析时， 会失败， 在linux ping时有体现，会在解析出ip后等一会才会出延迟时间（windows 默认把dns反向解析禁用了）， 如果局域网机器ssh开着dns也会很慢

**Comment by qiuxiangling** [comment]
已经解决

**Comment by cross-hello** [comment]
🙃 You must don't know how to get others' favor.

Feb 13, 2023 18:48:01 秋湘灵 ***@***.***>:

**Comment by Moladoogh** [comment]
No ,I'm  so sorry. I can't copy  and paste   this config. Can you  send
 vpn account  or config  to me for download   and  copy  ,paste  to  xray
app

در تاریخ دوشنبه ۱۳ فوریهٔ ۲۰۲۳،‏ ۱۴:۲۱ Nanyu ***@***.***>
نوشت:
