### ISSUE TITLE
请问现在xtls vision还能否支持fallback？

### ISSUE THREAD

**Issue by huggin** [XTLS/Xray-core#1587]
fallback才是我最想要的功能，可以其xray服务的同时，提供几个其他的https服务

**Comment by FranzKafkaYu** [comment]
当然支持，不过官方建议只回落到nginx，不要回落或分流到其他协议。

**Comment by huggin** [comment]
Thanks for the rapid response. Could you please give me a sample config?

**Comment by FranzKafkaYu** [comment]
same before.

**Comment by huggin** [comment]
It seems not working for me. I have to set 'security": "tls"' to make xtls-rprx-vision work but my fallbak website won't work under security tls. It has to be "security xtls" to make my fallback website work.

**Comment by FranzKafkaYu** [comment]
![image](https://user-images.githubusercontent.com/38254177/216556692-1f57aa41-cefa-4851-9d13-68a9dd4093f0.png)  
![image](https://user-images.githubusercontent.com/38254177/216556915-a71688f8-fe9d-41dc-9b93-b767b146370b.png)

it works for me.

**Comment by huggin** [comment]
> 

Could you please show me the streamSettins as well?

**Comment by huggin** [comment]
> ![image](https://user-images.githubusercontent.com/38254177/216556692-1f57aa41-cefa-4851-9d13-68a9dd4093f0.png) ![image](https://user-images.githubusercontent.com/38254177/216556915-a71688f8-fe9d-41dc-9b93-b767b146370b.png)
> 
> it works for me.

Could you please show me the streamSettings as well?

**Comment by FranzKafkaYu** [comment]
> > ![image](https://user-images.githubusercontent.com/38254177/216556692-1f57aa41-cefa-4851-9d13-68a9dd4093f0.png) ![image](https://user-images.githubusercontent.com/38254177/216556915-a71688f8-fe9d-41dc-9b93-b767b146370b.png)
> > it works for me.
> 
> Could you please show me the streamSettings as well?

![image](https://user-images.githubusercontent.com/38254177/216586647-15a2b6b8-c872-47b8-9e31-9407aa832df3.png)

**Comment by huggin** [comment]
Thanks, man. Apparently, my webserver doesn't support h2. After I removed the h2 config, it worked like a charm.

**Comment by huggin** [comment]
It's resolved.

**Comment by iulo** [comment]
@FranzKafkaYu Could you share your nginx steam config?
