### ISSUE TITLE
是不是可以通过tls的双向认证来加强安全

### ISSUE THREAD

**Issue by lqxhub** [XTLS/Xray-core#1588]
最近端口被封了好几次 就想到了是不是可以通过tls的双向认证来加强安全   这样的话  是不是就可以避免 一些探测

但是这样是不是也会增大了特征, 方便 gfw的识别

**Comment by shenlijun** [comment]
ray系的反向代理最稳
想翻得稳要靠机场订阅

自建翻可以试试naiveproxy

**Comment by yoohooyoo** [comment]
双向认证是用于客户端和服务端互相确认对方身份可信性的，不是用于解决“协议被识别”这个问题的。
如果增加了大概率只会增加特征。

**Comment by lqxhub** [comment]
> 双向认证是用于客户端和服务端互相确认对方身份可信性的，不是用于解决“协议被识别”这个问题的。 如果增加了大概率只会增加特征。

确实 会增加 特征  得不偿失

**Comment by RPRX** [comment]
Instead，你可以用 REALITY，它是强制双向认证，但不会把特征拉满，且不基于现有的根证书体系，比常规的 TLS 更安全

REALITY 已经解决 @yuhan6665 测出的多线程问题，~~预计于~~ 我还是不预告了，万一又鸽了

**Comment by FranzKafkaYu** [comment]
> Instead，你可以用 REALITY，它是强制双向认证，但不会把特征拉满，且不基于现有的根证书体系，比常规的 TLS 更安全
> 
> REALITY 已经解决 @yuhan6665 测出的多线程问题，~预计于~ 我还是不预告了，万一又鸽了

Come On.

**Comment by tdjnodj** [comment]
> 不基于现有的根证书体系

难道是像 [这个脚本](https://github.com/SySS-Research/clone-cert) 一样对证书偷梁换柱吗？

**Comment by RPRX** [comment]
> > 不基于现有的根证书体系
> 
> 难道是像 [这个脚本](https://github.com/SySS-Research/clone-cert) 一样对证书偷梁换柱吗？

REALITY 是生成一个最小证书，然后用 hmac 对其中的公钥签名填到 signature，客户端接管证书验证，可以区分它与正常证书

所以证书链攻击对 REALITY 完全无效，比如来自 CA 的攻击、手机（系统）内置根证书等，比普遍没 pin 证书的 TLS 更安全

**Comment by RPRX** [comment]
回复下群，以上只是 REALITY 的一部分原理，解释一下为什么比你正在用的 TLS 更安全，不是全部原理，不要激动，~~大的还在后面~~

顺便回复下风扇滑翔翼，XTLS 和 TLS 并不是只差一个 AES，因为是它代理，裸奔后开了 Splice，比没开的 Socks 代理消耗更低

**Comment by RPRX** [comment]
> REALITY 是生成一个最小证书，然后用 hmac 对其中的公钥签名填到 signature，客户端接管证书验证，可以区分它和正常证书

解决白名单的不是这个，这个只是客户端对服务端的身份认证，取代 TLS 的根证书体系

**Comment by RPRX** [comment]
也不是 ShadowTLS，它是向中间人展示证书，TLSv1.2，和我两年前预告时的想法差不多，不过这样做会有一些问题，假 TLS 等

所以今年我改变想法了，**REALITY 是 TLSv1.3，并且是一条货真价实的 TLS，不是假的**

**Comment by RPRX** [comment]
真的不是我不想发，问题是最近主要在处理 Xray-core v1.7.x，~~小作文进度暂停了~~

~~这是最后一条消息，不知道的还以为我是在自言自语~~

**Comment by zozx** [comment]
@RPRX 在github上看確實有點像自言自語

**Comment by yoohooyoo** [comment]
> 
等你

**Comment by free-the-internet** [comment]
How we can avoid exposing the certificate by IP (and thus fining by https://search.censys.io/ when we use CDN?
For example the setup is VLESS  WS + CDN.

**Comment by RPRX** [comment]
> How we can avoid exposing the certificate by IP (and thus fining by https://search.censys.io/ when we use CDN? For example the setup is VLESS WS + CDN.

CloudFlare 有回源 IP 列表，你可以只允许它们访问。

**Comment by wy580477** [comment]
> 



> How we can avoid exposing the certificate by IP (and thus fining by https://search.censys.io/ when we use CDN? For example the setup is VLESS WS + CDN.

You can also use Cloudflared tunnel.  https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/

**Comment by free-the-internet** [comment]
> > How we can avoid exposing the certificate by IP (and thus fining by https://search.censys.io/ when we use CDN? For example the setup is VLESS WS + CDN.
> 
> CloudFlare 有回源 IP 列表，你可以只允许它们访问。


> > 
> 
> > How we can avoid exposing the certificate by IP (and thus fining by https://search.censys.io/ when we use CDN? For example the setup is VLESS WS + CDN.
> 
> You can also use Cloudflared tunnel. https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/

The problem with this is that we can't use VISION after. Can't we do something like this in NGINX configuration?
```
server {
  listen 443 default_server ssl http2;  ssl_certificate /etc/nginx/ssl/examplecom/tls.crt;
  ssl_certificate_key /etc/nginx/ssl/examplecom/tls.key;
}
```
Source:
https://blog.palark.com/keep-your-eyes-open-how-to-avoid-exposing-your-internal-proxy/

In CDN mode, I believe that NGINX is in the front, so we should be able to do this. right?

**Comment by wy580477** [comment]
> Source: https://blog.palark.com/keep-your-eyes-open-how-to-avoid-exposing-your-internal-proxy/
> 
> In CDN mode, I believe that NGINX is in the front, so we should be able to do this. right?

The link which you gave, needs a tcp loadbalancer before your server. You can't archeive this on a single server.

**Comment by woodlyer** [comment]
give some firewall technology as reference:
http://blog.nsfocus.net/author/wangmeng7/
