### ISSUE TITLE
1.7.3是有2个fingerprint了吗

### ISSUE THREAD

**Issue by shuiliu11** [XTLS/Xray-core#1589]
<img width="780" alt="屏幕截图 2023-02-03 131946" src="https://user-images.githubusercontent.com/29864568/216520428-9bfcf960-565f-4689-920e-042050da1b65.png">
我的理解是,xray启动时一个, 设置"fingerprint":XXX又是一个.

**Comment by ThreeSourLemon** [comment]
@shuiliu11 不填就随机给你个的意思吧  检测到有设置就用你设置的？

**Comment by RPRX** [comment]
你们的理解都错了，我更新了 release note：
- 若选 `random`，相当于从 `ModernFingerprints` 中随机选一个指纹，注意它与 `randomized` 不同，后者是随机生成指纹。
前段时间有 `safari` 指纹更稳的反馈，注意现在选 `ios` 才是前段时间的 `safari`，它与现在的 `safari` 不同。

> unknown fingerprint: radomized

指纹名填错了，少了个 n：
- 若有 `fingerprint`，Xray-core 启动时会检查它是否存在，若不存在将报错。

**Comment by ThreeSourLemon** [comment]
@shuiliu11 默认就是random

**Comment by RPRX** [comment]
相当于现在多了六个选项 https://github.com/2dust/v2rayN/commit/26dd0d0ea5b258d938a49f74343dcf8a60dc682e
还可以手动填写 uTLS 库的原生指纹名，详见 release note 开头的链接和说明

**Comment by RPRX** [comment]
> @shuiliu11 默认就是random

否
