### ISSUE TITLE
xtls-rprx-vision在多文件下载/上传时性能问题

### ISSUE THREAD

**Issue by miku1958** [XTLS/Xray-core#1590]
我有个使用场景, 需要在自搭的网盘里同步一个超级大超级多文件(10W+)的文件夹, 每次需要同步的文件数可能有100+, 这个网盘是搭在Azure上的, VPS也是Azure的.

之前用纯TLS的时候可以跑满本地的千兆网, 但是换成xtls-rprx-vision后速度大概只有50MB/s, 大概是之前的一半左右, 客户端是部署在mac上的, 同步的时候xray会吃满一颗CPU核心(100%), 换到一个性能比较弱的装了Openwrt的路由器上测试, CPU吃满后大概能有4MB/s, 之前至少也有10MB/s

**Comment by miku1958** [comment]
htop上看路由器上的xray应该是有多线程的?
<img width="777" alt="image" src="https://user-images.githubusercontent.com/24806909/216523056-17df8ea7-032b-4830-86ac-4fbe06dc5f66.png">
我奇怪是不是mac上的多线程有bug?

**Comment by RPRX** [comment]
即使你的网盘非 TLSv1.3，XTLS Vision 的性能至少也是和 TLS 持平（就是同一套代码），请控制变量进行测试并排查其它问题。

**Comment by DamonLee35** [comment]
> 我有个使用场景， 需要在自搭的网盘里同步一个超级大超级多文件（10W+）的文件夹， 每次需要同步的文件数可能有100+， 这个网盘是搭在Azure上的， VPS也是Azure的。
> 
> 之前用纯TLS的时候可以跑满本地的千兆网， 但是换成xtls-rprx-vision后速度大概只有50MB/s， 大概是之前的一半左右， 客户端是部署在mac上的， 同步的时候xray会吃满一颗CPU核心（100%）， 换到一个性能比较弱的装了Openwrt的路由器上测试， CPU吃满后大概能有4MB/s， 之前至少也有10MB/s

我的VPS使用xtls-rprx-vision也会出现传输性能衰减，测试了很多次
