### ISSUE TITLE
cannot load embed: malformed module path "embed": missing dot in first path element

### ISSUE THREAD

**Issue by avboy1337** [XTLS/Xray-core#1591]
linux下编译报错。

**Comment by avboy1337** [comment]
± |main U:2 ✗| → go build -o xray -trimpath -ldflags "-s -w -buildid=" ./main         
build github.com/xtls/xray-core/main: cannot load embed: malformed module path "embed": missing dot in first path element

**Comment by FranzKafkaYu** [comment]
@avboy1337  release的action都能跑过，建议先看看自己的配置是否正确。
