### ISSUE TITLE
xray-core今天开始编译不过去啦？

### ISSUE THREAD

**Issue by guhill1** [XTLS/Xray-core#1592]
x86版本，
/feeds/small8/xray-core failed to build
大佬们这是怎么回事 ，有类似的吗？

feeds/small8/xray-core/makefile:这个有问题吗？
include $(TOPDIR)/rules.mk

PKG_NAME:=xray-core
PKG_VERSION:=1.7.3
PKG_RELEASE:=1

PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
PKG_SOURCE_URL:=https://codeload.github.com/XTLS/Xray-core/tar.gz/v$(PKG_VERSION)?
PKG_HASH:=dcca9bd46813129325dd9128d34b096475668032f919677dbf5aaeea93b6694f

PKG_MAINTAINER:=Tianling Shen <cnsztl@immortalwrt.org>
PKG_LICENSE:=MPL-2.0
PKG_LICENSE_FILES:=LICENSE

PKG_BUILD_DIR:=$(BUILD_DIR)/Xray-core-$(PKG_VERSION)
PKG_BUILD_DEPENDS:=golang/host
PKG_BUILD_PARALLEL:=1
PKG_USE_MIPS16:=0

GO_PKG:=github.com/xtls/xray-core
GO_PKG_LDFLAGS:=-s -w
GO_PKG_BUILD_PKG:=$(GO_PKG)/main
GO_PKG_LDFLAGS_X:= \
	$(GO_PKG)/core.build=OpenWrt \
	$(GO_PKG)/core.version=$(PKG_VERSION)

include $(INCLUDE_DIR)/package.mk
include $(TOPDIR)/feeds/packages/lang/golang/golang-package.mk

define Package/xray-core
  TITLE:=A platform for building proxies to bypass network restrictions
  SECTION:=net
  CATEGORY:=Network
  URL:=https://xtls.github.io
  DEPENDS:=$(GO_ARCH_DEPENDS) +ca-bundle
endef

define Package/xray-core/description
  Xray, Penetrates Everything. It helps you to build your own computer network.
  It secures your network connections and thus protects your privacy.
endef

define Package/xray-core/install
	$(call GoPackage/Package/Install/Bin,$(PKG_INSTALL_DIR))
	$(INSTALL_DIR) $(1)/usr/bin/
	$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/bin/main $(1)/usr/bin/xray
endef

$(eval $(call BuildPackage,xray-core))

**Comment by FranzKafkaYu** [comment]
编译xray core需要使用Go 1.20+版本，请看release说明。

**Comment by yichya** [comment]
可以参考 [https://github.com/yichya/openwrt-xray](https://github.com/yichya/openwrt-xray) 临时加一个 patch 兼容 Go 1.18+

**Comment by guhill1** [comment]
> 可以参考 https://github.com/yichya/openwrt-xray 临时加一个 patch 兼容 Go 1.18+

好的，谢谢指点

**Comment by RPRX** [comment]
> 可以参考 https://github.com/yichya/openwrt-xray 临时加一个 patch 兼容 Go 1.18+

这样改可以用低版本编译吗

**Comment by RPRX** [comment]
@yuhan6665 v2rayNG 遇到的那个问题，可以用这个方法试试，如果能解决，我们补发一个小版本

**Comment by yichya** [comment]
> 这样改可以用低版本编译吗

可以呀，我其实没太理解你为啥在那里写了一个 qtls-go-1-20

**Comment by RPRX** [comment]
> 可以呀，我其实没太理解你为啥在那里写了一个 qtls-go-1-20

~~与时俱进~~，其实是担心引入的版本多会增加体积，不过我没测试具体差异，~~有可能是只差一点~~
目前看来只有这个问题阻止了用低版本编译，那么我觉得是可以补发个小版本的，正好我也想再改点代码

**Comment by yichya** [comment]
> 与时俱进

稍微等一等 OpenWrt（

> 其实是担心引入的版本多会增加体积

不会的，看 go.mod 就知道了，实际上 `qtls-go1-18` `qtls-go1-19` `qtls-go1-20` 都在 `// indirect` 里面，编译的时候都会带进去

![image](https://user-images.githubusercontent.com/3683052/216603773-4bf7c186-c4d9-44a0-8710-68f4288d1ece.png)

**Comment by RPRX** [comment]
> 不会的，看 go.mod 就知道了，实际上 `qtls-go1-18` `qtls-go1-19` `qtls-go1-20` 都在 `// indirect` 里面，编译的时候都会带进去
> 
> ![image](https://user-images.githubusercontent.com/3683052/216603773-4bf7c186-c4d9-44a0-8710-68f4288d1ece.png)

只是依赖有写，实际上没用到的代码不会编译到最终的二进制中，我没看 quic-go 的代码，不过它应该是用 `go:build` 区分了
比如你的 [patch](https://github.com/yichya/openwrt-xray/commit/36eb227774e1def18f77f9a5016b1231ed107771) 里也含 `qtls-go1-20`，它依赖 Go 1.20 的新库 `crypto/ecdh`，没区分的话，不可能可以用低版本编译

**Comment by yichya** [comment]
> 只是依赖有写，实际上没用到的代码不会编译到最终的二进制中，我没看 quic-go 的代码，不过它应该是用 `go:build` 区分了 比如你的 [patch](https://github.com/yichya/openwrt-xray/commit/36eb227774e1def18f77f9a5016b1231ed107771) 里也含 `qtls-go1-20`，它依赖 Go 1.20 的新库 `crypto/ecdh`，没区分的话，不可能可以用低版本编译

确实，我刚刚试了一下，按我那样改的话二进制大了大概 90kb 左右。我打算照抄一下 quic-go 的做法

**Comment by RPRX** [comment]
其实也就 CipherSuiteTLS13、AEADAESGCMTLS13、xorNonceAEAD
我看了一下，是没有必要指定一个库的，我打算把它们复制出来

> 按我那样改的话二进制大了大概 90kb 左右

~~也可能是 Go 1.20 编译出来的体积小点~~

**Comment by yichya** [comment]
> 我打算照抄一下 quic-go 的做法

#1593 我试了一下应该可以

**Comment by RPRX** [comment]
`go:linkname` 也行，不过这个方法过于 hack，容易随着 Go 版本的迭代而 broken

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/commit/00c95761189162504ebc2c0df3266e9395c7e40d 结构体复制出来了，对函数用了 go:linkname，可以用 Go 1.19.5 编译了，~~不过别急，这两天会再发个小版本~~
