### ISSUE TITLE
是否有必要移除旧的XTLS流控

### ISSUE THREAD

**Issue by FranzKafkaYu** [XTLS/Xray-core#1596]
如题，旧的XTLS流控原本为VLESS的专属，后来Xray将Trojan协议改造使其也可以使用这些相应的流控。而现在xtls-rprx-vision流控属于VLESS专属，如果要完全移除老的流控，Trojan也无法再使用相应的流控。  

考虑到国内在国内旧的流控确实不再安全，但是在其他地方也许还有一些存在的现实意义(即使是增加流量分析的样本量)。如果不移除旧的流控，是否可以从GUI上做相应提示?

**Comment by FranzKafkaYu** [comment]
还忘了群友反馈的一个情况，IOS目前没有适配xtls-rprx-vision流控的客户端，过早移除老的流控可能会有一些不便。

**Comment by RPRX** [comment]
~~XTLS/REALITY 和 XTLS/Go 一换一~~

XTLS Vision 在任何方面都比旧版 XTLS 强，只是内层 TLSv1.2 时不裸奔，而 TLSv1.2 已经越来越少了，所以保留旧版的必要性不大

其实仔细想想，你就会发现 XTLS Vision 没有必要支持 Trojan 了，以前支持是为了同端口，~~现在和它同端口会直接 get blocked~~
假如说是想用 Trojan+Vision，不和原版 Trojan 共存的那种，那就更没有意义了，因为不如直接用原生的 VLESS+Vision

**Comment by RPRX** [comment]
> 还忘了群友反馈的一个情况，IOS目前没有适配xtls-rprx-vision流控的客户端，过早移除老的流控可能会有一些不便。

我觉得如果确实需要用旧版 XTLS，可以先不升至 v1.8.0，v1.7.x 的小版本就是为这种情况准备的

**Comment by FranzKafkaYu** [comment]
OK.

**Comment by alireza1023** [comment]
> I also forgot a situation reported by the group friends. Currently, IOS does not have a client that adapts to xtls-rprx-vision flow control. It may be inconvenient to remove the old flow control too early.

now ShadowRocket supports it
