### ISSUE TITLE
Using uTLS fingerprints beside XTLS =-RPRX-VISION

### ISSUE THREAD

**Issue by arashammm** [XTLS/Xray-core#1597]
Hi.

As I understand the new uTLS fingerprints can only be used with ws or https network. Unfortunatly XTLS and XTLS-RPRX-VISION only work with tcp network. So is there any way we can both implement XTLS and uTLS fingerprints (on clinet side ofcouse) at the same time? or the XTLS itself provides browser fingerprints to fully mimic usual tls traffic?

I would like to hear others solutions or ideas.

Thanks in advance

**Comment by us254** [comment]
[https://github.com/XTLS/Xray-core/commit/8ef609ff46cd764138d9427bb97c57fdc28d150f](url)

**Comment by arashammm** [comment]
So according to this  commit  I shoud chage these 3 files in the sorce code?
What about the newly added fingerprints in the latest version? can we use those fingerprints that way?

But according to config example you mentioned the uTLS can be used beside XTLS in the latest version without any modifications? Am I right?

**Comment by us254** [comment]
Yes, that's correct. To set a client-side fingerprint, the settings of the
client software application need to be configured. The source code does not
need to be modified for this.

**Comment by arashammm** [comment]
Ok Thanks
I will configure clinet side like this json.
https://github.com/chika0801/Xray-examples/blob/main/VLESS-TCP-XTLS-Vision/config_client.json

**Comment by RPRX** [comment]
XTLS Vision 支持 uTLS fingerprints
