### ISSUE TITLE
geoip rule is very slow

### ISSUE THREAD

**Issue by qfewzz** [XTLS/Xray-core#1600]
when i add geoio:CODE rule on the server side, it takes about 10 seconds just to start fetching some websites like youtube. google.com is ok. when i deleted this rule, the problem solved. when i use the same rule in the client side, in the same way, i don't experience such a problem and everything is fast.
i have tested with different country codes. there is no other rule that may cause conflict, and i have tested this several times with different devices, different protocols and protocol settings. i'm the only user of the server, so there is no resource issue. also i monitored logs, when i start opening youtube website, it takes that 10 seconds for youtube.com to show up in the logs(when geoip rule is there).

**Comment by JimmyHuang454** [comment]
可能是你配置的问题，① ip rules 会先通过DNS解析domain，② 然后再查询geoip

以上两步具体是哪一步有问题，需要更多log来帮助发现问题，是DNS解析慢？还是你的VPS内存太少了导致查询慢？

**Comment by qfewzz** [comment]
thanks! the problem was that resolving hostname to IP was taking too long because of some limitations, I used DNS object and the problem is solved.
