### ISSUE TITLE
出现吃内存情况

### ISSUE THREAD

**Issue by asiaon123** [XTLS/Xray-core#1603]
lede 的编译 xray-core 1.7.3

```
[ 5663.276059] xray invoked oom-killer: gfp_mask=0x100cca(GFP_HIGHUSER_MOVABLE), order=0, oom_score_adj=0
[ 5663.285459] CPU: 2 PID: 5439 Comm: xray Not tainted 5.4.230 #0
[ 5663.291284] Stack : 00100cca 8007f304 80710000 807166dc 80790000 807166a4 80715548 8daefbcc
[ 5663.299644]         808d0000 8ff6a630 80760da3 806a3d50 00000002 00000001 8daefb70 0ce04c72
[ 5663.308008]         00000000 00000000 80910000 00000000 00000030 00000177 322e342e 23203033
[ 5663.316369]         00000000 00000119 00000000 00045b13 80000000 80790000 00000000 8075e2cc
[ 5663.324734]         00000000 80760000 00000240 00000000 00000001 80388868 00000008 808d0008
[ 5663.333092]         ...
[ 5663.335538] Call Trace:
[ 5663.338005] [<8000b64c>] show_stack+0x30/0x100
[ 5663.342442] [<805e4ec8>] dump_stack+0xa4/0xdc
[ 5663.346783] [<80113004>] dump_header+0x60/0x1fc
[ 5663.351294] [<80113b04>] oom_kill_process+0x1f4/0x1fc
[ 5663.356331] [<8011421c>] out_of_memory+0x250/0x398
[ 5663.361121] [<801592e8>] __alloc_pages_nodemask+0x808/0xeb8
[ 5663.366701] [<8010eae4>] pagecache_get_page.part.61+0x150/0x418
[ 5663.372601] [<8010f2e8>] filemap_fault+0x534/0xa58
[ 5663.377379] [<8013dcc0>] __do_fault+0x40/0x128
[ 5663.381809] [<8014304c>] handle_mm_fault+0x91c/0xd20
[ 5663.386767] [<80017244>] do_page_fault+0x108/0x4b8
[ 5663.391543] [<8001c708>] tlb_do_page_fault_0+0x118/0x120
[ 5663.397014] Mem-Info:
[ 5663.399340] active_anon:34307 inactive_anon:53 isolated_anon:0
[ 5663.399340]  active_file:367 inactive_file:847 isolated_file:69
[ 5663.399340]  unevictable:0 dirty:0 writeback:0 unstable:0
[ 5663.399340]  slab_reclaimable:1232 slab_unreclaimable:9763
[ 5663.399340]  mapped:38 shmem:1071 pagetables:209 bounce:0
[ 5663.399340]  free:3697 free_pcp:113 free_cma:0
[ 5663.431710] Node 0 active_anon:137228kB inactive_anon:212kB active_file:1468kB inactive_file:2828kB unevictable:0kB isolated(anon):0kB isolated(file):276kB mapped:152kB dirty:0kB writeback:0kB shmem:4284kB writeback_tmp:0kB unstable:0kB all_unreclaimable? no
[ 5663.454576] Normal free:16836kB min:16384kB low:20480kB high:24576kB active_anon:136760kB inactive_anon:212kB active_file:852kB inactive_file:3444kB unevictable:0kB writepending:0kB present:262144kB managed:251368kB mlocked:0kB kernel_stack:2112kB pagetables:836kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
[ 5663.482343] lowmem_reserve[]: 0 0 0
[ 5663.485867] Normal: 112*4kB (UME) 77*8kB (UE) 149*16kB (UME) 99*32kB (UME) 47*64kB (UME) 8*128kB (UME) 2*256kB (UM) 1*512kB (M) 1*1024kB (M) 2*2048kB (M) 0*4096kB = 16792kB
[ 5663.501312] 2166 total pagecache pages
[ 5663.505093] 0 pages in swap cache
[ 5663.508405] Swap cache stats: add 0, delete 0, find 0/0
[ 5663.513643] Free swap  = 0kB
[ 5663.516515] Total swap = 0kB
[ 5663.519403] 65536 pages RAM
[ 5663.522202] 0 pages HighMem/MovableOnly
[ 5663.526062] 2694 pages reserved
[ 5663.529210] Tasks state (memory values in pages):
[ 5663.533973] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[ 5663.542638] [    724]    81   724      372       21    20480        0             0 ubusd
[ 5663.550813] [    733]     0   733      264        8    16384        0             0 askfirst
[ 5663.559375] [    767]     0   767      300       14    20480        0             0 urngd
[ 5663.567617] [   1484]   514  1484      371       35    16384        0             0 logd
[ 5663.575751] [   1536]     0  1536      491       27    16384        0             0 rpcd
[ 5663.583913] [   1856]     0  1856      727       13    20480        0             0 hostapd
[ 5663.592254] [   1857]     0  1857      727       14    20480        0             0 wpa_supplicant
[ 5663.601249] [   1859]   101  1859     1429       75    24576        0             0 hostapd
[ 5663.609662] [   1860]   101  1860     1378       56    24576        0             0 wpa_supplicant
[ 5663.618694] [   1920]     0  1920      523       39    20480        0             0 netifd
[ 5663.626983] [   1974]     0  1974      438       28    16384        0             0 odhcpd
[ 5663.635278] [   2181]     0  2181     1274       90    24576        0             0 uhttpd
[ 5663.643630] [   3314]     0  3314      304       13    20480        0             0 odhcp6c
[ 5663.651999] [   3320]     0  3320      342        8    20480        0             0 udhcpc
[ 5663.660313] [   4277]     0  4277      348       16    20480        0             0 miniupnpd
[ 5663.668912] [   4334]     0  4334      318       13    20480        0             0 dropbear
[ 5663.677383] [   4493]     0  4493      430       23    16384        0             0 nlbwmon
[ 5663.685787] [   4994]     0  4994      727       26    16384        0             0 ntpd
[ 5663.693946] [   4996]   123  4996      342       10    16384        0             0 ntpd
[ 5663.702045] [   5115]     0  5115     1398       68    20480        0             0 ttyd
[ 5663.710199] [   5391]     0  5391   173417    25500   159744        0             0 xray
[ 5663.718352] [   5414]     0  5414      841      570    20480        0             0 dns2tcp
[ 5663.726730] [   6344]     0  6344      727       26    20480        0             0 dnsmasq
[ 5663.735115] [   6346]   453  6346     2456     2058    24576        0             0 dnsmasq
[ 5663.743505] [   6401]     0  6401      344       14    20480        0             0 monitor.sh
[ 5663.752109] [   6449]     0  6449      343       11    20480        0             0 crond
[ 5663.760440] [  12174]     0 12174      672       85    12288        0             0 luci
[ 5663.768594] [  12201]     0 12201      342        8    16384        0             0 sleep
[ 5663.776818] [  12203]   453 12203     2456     2056    24576        0             0 dnsmasq
[ 5663.785303] [  12204]   453 12204     2439     2054    24576        0             0 dnsmasq
[ 5663.793748] [  12205]   453 12205     2439     2054    24576        0             0 dnsmasq
[ 5663.802106] [  12206]   453 12206     2456     2054    24576        0             0 dnsmasq
[ 5663.810509] [  12207]   453 12207     2439     2055    24576        0             0 dnsmasq
[ 5663.818930] [  12208]   453 12208     2439     2054    24576        0             0 dnsmasq
[ 5663.827309] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=xray,pid=5391,uid=0
[ 5663.839735] Out of memory: Killed process 5391 (xray) total-vm:693668kB, anon-rss:102000kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:156kB oom_score_adj:0
[ 5666.060331] oom_reaper: reaped process 5391 (xray), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

**Comment by RPRX** [comment]
v17.2 到 v1.7.3 的更改应该不会导致这样，测一下 v1.7.2 有没有问题

**Comment by RPRX** [comment]
v1.7.2 到 v1.7.3 的更改应该不会导致这样，测一下 v1.7.2 有没有问题

**Comment by Michaol** [comment]
是不是用了xray-core带的shadowsocks？

**Comment by asiaon123** [comment]
> v1.7.2 到 v1.7.3 的更改应该不会导致这样，测一下 v1.7.2 有没有问题

我是在做多线程下载操作，之前1.7.2没有这个问题，还是相对比较稳定的

**Comment by asiaon123** [comment]
> 是不是用了xray-core带的shadowsocks 2022？

没有使用

**Comment by RPRX** [comment]
> > 是不是用了xray-core带的shadowsocks 2022？
> 
> 没有使用

所以用的是什么呢？你应该会替换 bin 吧，麻烦先测试一下 https://github.com/XTLS/Xray-core/actions/runs/4065854152

**Comment by asiaon123** [comment]
> > > 是不是用了xray-core带的shadowsocks 2022？
> > 
> > 
> > 没有使用
> 
> 所以用的是什么呢？你应该会替换 bin 吧，麻烦先测试一下 https://github.com/XTLS/Xray-core/actions/runs/4065854152

好的 我测试好了来反馈一下

**Comment by RPRX** [comment]
有结果吗

**Comment by asiaon123** [comment]
> 有结果吗

我试了一下1.7.2的没有出现 又切回1.7.3也没有再出现了

**Comment by RPRX** [comment]
> > 有结果吗
> 
> 我试了一下1.7.2的没有出现 又切回1.7.3也没有再出现了

OK

**Comment by mclovin-2k** [comment]
![image](https://user-images.githubusercontent.com/5440567/217169656-50b558ef-df7f-4ad6-8dae-f9b494aec8f7.png)
这是我用代理在SpeedTest.net上（多线程）测速时，Server端的内存占用，这算正常吗？
此时 Server VPS 512MB 内存已经耗尽，发生了肉眼可见的降速。

Server - XRAY 1.7.3 (Linux AMD64)
Client - XRAY 1.7.3 (Windows AMD64)
协议：VLESS + TCP + VISION + TLS

**Comment by RPRX** [comment]
@mclovin-2k 试试 1.7.2

**Comment by mclovin-2k** [comment]
> @mclovin-2k 试试 1.7.2

一样

**Comment by davidtall** [comment]
’‘’
[ 1087.329128] Node 0 active_anon:0kB inactive_anon:28372kB active_file:504kB inactive_file:2224kB unevictable:0kB isolated(anon):0kB isolated(file):128kB mapped:12kB dirty:0kB writeback:0kB shmem:20kB writeback_tmp:0kB unstable:0kB all_unreclaimable? no
[ 1087.351806] DMA32 free:16016kB min:16384kB low:20480kB high:24576kB active_anon:0kB inactive_anon:28372kB active_file:24kB inactive_file:2488kB unevictable:0kB writepending:0kB present:261952kB managed:235016kB mlocked:0kB kernel_stack:4016kB pagetables:1592kB bounce:0kB free_pcp:60kB local_pcp:4kB free_cma:0kB
[ 1087.379455] lowmem_reserve[]: 0 0 0
[ 1087.382964] DMA32: 1233*4kB (UMEH) 701*8kB (UMEH) 253*16kB (UMEH) 30*32kB (UMH) 10*64kB (H) 3*128kB (H) 1*256kB (H) 0*512kB 0*1024kB 0*2048kB 0*4096kB = 16828kB
[ 1087.397617] 781 total pagecache pages
[ 1087.401868] 48 pages in swap cache
[ 1087.405269] Swap cache stats: add 131872, delete 131824, find 3479/101556
[ 1087.412226] Free swap  = 0kB
[ 1087.415246] Total swap = 116732kB
[ 1087.418575] 65488 pages RAM
[ 1087.421362] 0 pages HighMem/MovableOnly
[ 1087.425203] 6734 pages reserved
[ 1087.428346] Tasks state (memory values in pages):
[ 1087.433055] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[ 1087.441694] [    870]     0   870      311       23    32768        8             0 ubusd
[ 1087.449888] [    871]     0   871      211        1    28672       13             0 askfirst
[ 1087.458337] [    901]     0   901      245        2    28672       15             0 urngd
[ 1087.466523] [   1882]     0  1882      304        2    28672       37             0 logd
[ 1087.474622] [   1934]     0  1934      398       20    32768       13             0 rpcd
[ 1087.482720] [   2436]     0  2436      449       26    32768       18             0 netifd
[ 1087.490991] [   2511]     0  2511      363       23    32768       11             0 odhcpd
[ 1087.499266] [   2614]     0  2614      266        0    28672       18             0 netserver
[ 1087.507801] [   2724]     0  2724     1355       25    40960      125             0 uhttpd
[ 1087.516075] [   2785]     0  2785      435        2    28672       34             0 dbus-daemon
[ 1087.524785] [   2858] 65534  2858      567       38    32768       55             0 avahi-daemon
[ 1087.533578] [   2914]     0  2914      219        0    32768       13             0 vlmcsd
[ 1087.541853] [   3372]     0  3372      329       18    32768       22             0 pppd
[ 1087.549959] [   3374]     0  3374      260        2    32768       15             0 dropbear
[ 1087.558403] [   3556]     0  3556      433        1    32768      138             0 dynamic_dns_upd
[ 1087.567969] [   6738]     0  6738      250       11    28672        7             0 odhcp6c
[ 1087.576459] [   6838]     0  6838      284       17    32768        3             0 miniupnpd
[ 1087.585267] [   7736]     0  7736      338        1    32768       38             0 beardropper
[ 1087.594044] [   7975]     0  7975     8800       14   106496      426             0 smbd
[ 1087.602149] [   7976]     0  7976     5555       82    77824      268             0 nmbd
[ 1087.610248] [   7987]     0  7987      341        2    32768       24             0 logread
[ 1087.618615] [   7988]     0  7988      338        2    32768       39             0 beardropper
[ 1087.627493] [   8100]     0  8100      312       12    32768        3             0 ntpd
[ 1087.635612] [   9451]     0  9451     8421       14   102400      420             0 smbd-notifyd
[ 1087.644409] [   9452]     0  9452     8423       12   102400      422             0 cleanupd
[ 1087.652859] [  10261]     0 10261      222       10    28672        8             0 wsdd2
[ 1087.661048] [  16253]     0 16253  1233008      621   143360      362             0 xray
[ 1087.669498] [  16362]     0 16362  1233008      797   143360      524             0 xray
[ 1087.677608] [  16405]     0 16405  1233171     1677   163840     2174             0 xray
[ 1087.685715] [  16446]     0 16446  1250451     3389   348160    23376             0 xray
[ 1087.693812] [  17209]   453 17209      682       43    40960       17             0 dnsmasq
[ 1087.702169] [  17273]     0 17273      316       18    28672        2             0 monitor.sh
[ 1087.711446] [  17321]     0 17321      312       11    28672        4             0 crond
[ 1087.719809] [  22745]     0 22745      312        1    32768       13             0 sleep
[ 1087.728301] [  23770]     0 23770      633      124    32768       18             0 luci
[ 1087.736540] [  23772]     0 23772     5555      107    77824      243             0 nmbd
[ 1087.744789] [  23782]     0 23782      316       17    28672        2             0 monitor.sh
[ 1087.753472] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=xray,pid=16446,uid=0
[ 1087.765948] Out of memory: Killed process 16446 (xray) total-vm:5001804kB, anon-rss:13548kB, file-rss:8kB, shmem-rss:0kB, UID:0 pgtables:340kB oom_score_adj:0
‘’‘
1.8.0 版本，出现内存溢出的情况，红米ax6s
