### ISSUE TITLE
empty content type

### ISSUE THREAD

**Issue by aliwebto** [XTLS/Xray-core#1606]
hi guys , This is a report from cloudflare and it shows that the content of requests is empty . This can help the firewall (GFW ) to detect normal traffic from v2ray traffic .Any solution?
![image](https://user-images.githubusercontent.com/70484690/216825551-adfe7b94-c36b-4788-9c2b-888c80fd729e.png)

**Comment by SakuraSakuraSakuraChan** [comment]
> This can help the firewall (GFW ) to detect normal traffic from v2ray traffic .

How？

**Comment by aliwebto** [comment]
> > This can help the firewall (GFW ) to detect normal traffic from v2ray traffic .
> 
> How？

It is very suspicious when there is a request with a lot of empty content on the server

**Comment by Fangliding** [comment]
It is
And it won't make any help to gfw
