### ISSUE TITLE
core.DialUDP: how to close Read the udp.dispatcherConn

### ISSUE THREAD

**Issue by rurirei** [XTLS/Xray-core#1611]
as per: https://github.com/v2fly/v2ray-core/issues/2258

a udp.dispatcherConn returned by core.DialUDP won't close it's c.Read(), blocks after the c.cache be received out.
https://github.com/XTLS/Xray-core/blob/58b81cb6638fbae029dcdb40e1e51a75b01e53d7/transport/internet/udp/dispatcher.go#L152-L175

possible fix: call handleInput() directly like this
```go
func (c *dispatchConn) Read(p []byte) (int, error) {
	mb, err := c.link.Reader.ReadMultiBuffer()
	if err != nil {
		return 0, err
	}

	return mb.CopyTo(p), nil
}
```
or a unreliable timeout simply:
```go
func (c *dispatcherConn) ReadFrom(p []byte) (int, net.Addr, error) {
	select {
	case <-c.done.Wait():
		return 0, nil, io.EOF
	case packet := <-c.cache:
		n := copy(p, packet.Payload.Bytes())
		return n, &net.UDPAddr{
			IP:   packet.Source.Address.IP(),
			Port: int(packet.Source.Port),
		}, nil
	}
	case <-time.After(time.Second *4):
		return 0, nil, io.EOF
	}
}
```

**Comment by RPRX** [comment]
所以为什么需要提前返回呢？Read 阻塞是正常行为

**Comment by rurirei** [comment]
though c.Close() closes the Read, i won't know the time when i should to close this conn.

> 所以为什么需要提前返回呢？Read 阻塞是正常行为

**Comment by rurirei** [comment]
as this blocks always except i call c.Close(), but there is the time point?
```go
var localConn

var remoteConn, err := core.DialUDP(ctx, dest)

io.Copy(localConn, remoteConn)
```

**Comment by RPRX** [comment]
> though c.Close() closes the Read, i won't know the time when i should to close this conn.
> 
> > 所以为什么需要提前返回呢？Read 阻塞是正常行为

在 Xray 实现的代理协议中，超时不活跃的会被自动 Close（取决于你设置的 policy），这是在外部控制的
~~虽然 *ray 的代码写得跟迷宫一样，自带混淆，不细看的话很难说这个 Close 有没有被调用~~
同理，你可以自己在外部实现一个超时不活跃调用 Close

**Comment by rurirei** [comment]
> > though c.Close() closes the Read, i won't know the time when i should to close this conn.
> > > 所以为什么需要提前返回呢？Read 阻塞是正常行为
> 
> 在 Xray 实现的代理协议中，超时不活跃的会被自动 Close（取决于你设置的 policy），这是在外部控制的 ~虽然 *ray 的代码写得跟迷宫一样，自带混淆，不细看的话很难说这个 Close 有没有被调用~ 同理，你可以自己在外部实现一个超时不活跃调用 Close

that's why there is a issue. either v2ray or xray do not call c.Close(), as core.Dial and core.DialUDP is for external api. but those won't provide any io.EOF mechanism to close its Read method.

**Comment by RPRX** [comment]
> // DialUDP provides a way to exchange UDP packets through Xray instance to remote servers.
// Since it is under a proxy context, the LocalAddr() in returned PacketConn will not show the real address.
//
// TODO: SetDeadline() / SetReadDeadline() / SetWriteDeadline() are not implemented.
//
// xray:api:beta
func DialUDP(ctx context.Context, v *Instance) (net.PacketConn, error) {

...

**Comment by rurirei** [comment]
>> 同理，你可以自己在外部实现一个超时不活跃调用 Close

though a timeout is not reliable enough i thought.

**Comment by rurirei** [comment]
to call handleInput() directly, rather than using c.cache channel to receive the packet is more immidiate and could give me a error, maybe? tested ok in my situation. 
```go
func (c *dispatchConn) Read(p []byte) (int, error) {
	mb, err := c.link.Reader.ReadMultiBuffer()
	if err != nil {
		return 0, err
	}

	return mb.CopyTo(p), nil
}
```

**Comment by RPRX** [comment]
看起来这个 `dispatcherConn` 只有 API 用到了对吧

**Comment by rurirei** [comment]
> 看起来这个 `dispatcherConn` 只有 API 用到了对吧

yes.

**Comment by RPRX** [comment]
```go
type Dispatcher struct {
	sync.RWMutex
	conns      map[net.Destination]*connEntry
	dispatcher routing.Dispatcher
	callback   ResponseCallback
	callClose  ...
}
```

给它加一个 `callClose` 然后在 `handleInput` 里 defer 调用吧，你来还是我来，我正准备发个小版本

**Comment by RPRX** [comment]
这个问题本质上是因为，在代理协议中它是被控方，不用考虑 Close 别人，但作为 API 和代理协议的桥梁，它没有传导 Close 信息

所以最合适的做法是加个回调

**Comment by rurirei** [comment]
> ```go
> type Dispatcher struct {
> 	sync.RWMutex
> 	conns      map[net.Destination]*connEntry
> 	dispatcher routing.Dispatcher
> 	callback   ResponseCallback
> 	callClose  ...
> }
> ```
> 
> 给它加一个 `callClose` 然后在 `handleInput` 里 defer 调用吧，你来还是我来，我正准备发个小版本

thanks for reply.

that won't solve, as c.cache is channel to be received out, the packets waited in c.cache would be received out or not on the time when callClose callback is called, says there is no garantee for c.cache is read out or not even then c.callClose done.

https://github.com/XTLS/Xray-core/blob/58b81cb6638fbae029dcdb40e1e51a75b01e53d7/transport/internet/udp/dispatcher.go#L105-L133

**Comment by rurirei** [comment]
the key point is that we won't know the time when c.cache would be read out.

**Comment by RPRX** [comment]
或者可以判断一下，chan 里还有数据的话就处理，直到没有再返回 io.EOF

**Comment by RPRX** [comment]
```go
func (c *dispatcherConn) ReadFrom(p []byte) (int, net.Addr, error) {
	var packet *udp.Packet
	select {
	case <-c.done.Wait():
		if len(c.cache) != 0 {
			packet = <-c.cache
			break
		}
		return 0, nil, io.EOF
	case packet = <-c.cache:
	}
	return copy(p, packet.Payload.Bytes()), &net.UDPAddr{
		IP:   packet.Source.Address.IP(),
		Port: int(packet.Source.Port),
	}, nil
}
```

比如这样，我这边全改好了，你看没问题的话我就 commit 了

**Comment by rurirei** [comment]
```go
func (c *dispatcherConn) ReadFrom(p []byte) (int, net.Addr, error) {
	var packet *udp.Packet

        if len(c.cache) > 0 {
		packet = <-c.cache
	} else {
                select {
	        case <-c.done.Wait():
		     return 0, nil, io.EOF
	        }
        }

	return copy(p, packet.Payload.Bytes()), &net.UDPAddr{
		IP:   packet.Source.Address.IP(),
		Port: int(packet.Source.Port),
	}, nil	
}
```

**Comment by rurirei** [comment]
BTW is there any disadvantage of len(c.cache)?

**Comment by RPRX** [comment]
> ```go
> func (c *dispatcherConn) ReadFrom(p []byte) (int, net.Addr, error) {
> 	var packet *udp.Packet
> 
>         if len(c.cache) > 0 {
> 		packet = <-c.cache
> 	} else {
>                 select {
> 	        case <-c.done.Wait():
> 		     return 0, nil, io.EOF
> 	        }
>         }
> 
> 	return copy(p, packet.Payload.Bytes()), &net.UDPAddr{
> 		IP:   packet.Source.Address.IP(),
> 		Port: int(packet.Source.Port),
> 	}, nil	
> }
> ```

显然，你的代码有 bug，会被直接锁死直到 done

**Comment by RPRX** [comment]
> ```go
> func (c *dispatcherConn) ReadFrom(p []byte) (int, net.Addr, error) {
> 	var packet *udp.Packet
> 
>         if len(c.cache) > 0 {
> 		packet = <-c.cache
> 	} else {
>                 select {
> 	        case <-c.done.Wait():
> 		     return 0, nil, io.EOF
>                 default:
>                     return 0, nil, nil
> 	        }
>         }
> 
> 	return copy(p, packet.Payload.Bytes()), &net.UDPAddr{
> 		IP:   packet.Source.Address.IP(),
> 		Port: int(packet.Source.Port),
> 	}, nil	
> }
> ```

显然，还是有 bug，会无限循环

**Comment by rurirei** [comment]
> ```go
> func (c *dispatcherConn) ReadFrom(p []byte) (int, net.Addr, error) {
> 	var packet *udp.Packet
> 	select {
> 	case <-c.done.Wait():
> 		if len(c.cache) != 0 {
> 			packet = <-c.cache
> 			break
> 		}
> 		return 0, nil, io.EOF
> 	case packet = <-c.cache:
> 	}
> 	return copy(p, packet.Payload.Bytes()), &net.UDPAddr{
> 		IP:   packet.Source.Address.IP(),
> 		Port: int(packet.Source.Port),
> 	}, nil
> }
> ```
> 
> 比如这样，我这边全改好了，你看没问题的话我就 commit 了

sorry and that's ok.

**Comment by RPRX** [comment]
OK

> BTW is there any disadvantage of len(c.cache)?

Golang 对 channel 的内置方法，应该是并发安全的，~~不过反正我们这里没有并发~~

**Comment by RPRX** [comment]
写法改成了再 select 一次，我觉得这样更好，~~不过应该不会有人并发调用 Read 吧~~

麻烦你本地测一下 https://github.com/XTLS/Xray-core/commit/e0b02014ea362cea010c21d7f44d8eebbc34cbb5

**Comment by RPRX** [comment]
> aware whether it's ok to add callClose() for all udp with NewDispatcher. (to change the ResponseCallbackFunc is not recommanded i thought).

对，目前如果主动 Close 了 `dispatcherConn`，并不会传导到代理协议侧，~~由于要改的代码比较多~~，PR is welcomed

https://github.com/XTLS/Xray-core/pull/1542 这个有点相似
