### ISSUE TITLE
如何代理本机游戏呢

### ISSUE THREAD

**Issue by alphaokxyz** [XTLS/Xray-core#1613]
Windows系统，可以代理游戏吗？现在用的clash，nat有问题，netch不稳定。各位游戏玩家怎么实现的游戏加速器呢？

**Comment by zozx** [comment]
@alphaokxyz 1. 建议自己买加速器
2. 开Tun模式

**Comment by alphaokxyz** [comment]
@zozx 什么客户端？clash的tun我打开了，nat类型不行，玩不了gta 。

**Comment by zozx** [comment]
@alphaokxyz 那应该就不是客户端问题，是你自己网络环境依旧不行
打游戏其实还是建议自己用加速器(虽然我自己玩GTA5的时候也是随便找个节点

**Comment by chika0801** [comment]
建议花钱买加速器省时省力省心，不省钱

**Comment by King-Of-Knights** [comment]
既然有了节点，为啥不先折腾折腾再说加速器的事呢。GTA5 对NAT类型十分敏感，对延迟不算特别敏感，Netch已经可以很好解决这个问题，首先尝试以下几个步骤：

1. 你的节点是自建还是机场，如果是机场，先启动Netch确认是不是NAT 1，如果不是NAT 1甚至是UDP block，找机场主沟通，看有没有游戏节点，没有的话，此时建议加速器解决。如果是自建，放开高位的端口的防火墙(1024-65535)，这个时候NAT 1应该就有了；
2. Netch 中最好选进程模式，进程模式代理的应用包括游戏主程序(GTA5.exe)、R星启动器(Rockstar-Games-Launcher.exe)、Soical Club相关东西(Social-Club-Setup.exe和SocialClubHelper.exe)都要代理上，当然也可以把Steam(Steam.exe)或者Epic代理上；
3. 启动Netch后，把游戏关了重进，按Home键打开Social Club查看网络信息，如果网络地址是你的VPS地址，且NAT为开放，那就表明代理成功了，可以进游戏了；
4. 通过以上三步，你对游戏延迟不满意或者掉线频繁，这个时候就是你的线路问题，netch和xray对此无能为力，此时建议上加速器。

**Comment by shenlijun** [comment]
uu加速器，openwrt插件

**Comment by Alex-Joe-Lee** [comment]
> 4\. 或者

我的nat是fullcone模式了，但是游戏总是频繁掉线可能是什么原因呢？
