### ISSUE TITLE
Problem with configuring xtls-rprx-vision

### ISSUE THREAD

**Issue by arashammm** [XTLS/Xray-core#1615]
Hello to Xray community!

I try to configure xtls-rprx-vision on my server
Here is my server side configuration:

> {
>     "log": {
>         "loglevel": "warning"
>     },
>     "inbounds": [
>         {
>             "port": 443,
>             "protocol": "vless",
>             "settings": {
>                 "clients": [
>                     {
>                         "id": "uuid",
>                         "flow": "xtls-rprx-vision",
>                         "level": 0,
>                         "email": "love@example.com"
>                     }
>                 ],
>                 "decryption": "none",
>                 "fallbacks": [
>                     {
>                         "dest": 80
>                     }
>                 ]
>             },
>             "streamSettings": {
>                 "network": "tcp",
>                 "security": "xtls",
>                 "xtlsSettings": {
>                     "alpn": [
>                         "http/1.1"
>                     ],
>                     "certificates": [
>                         {
>                             "certificateFile": "address to full chain",
>                             "keyFile": "address to privkey"
>                         }
>                     ]
>                 }
>             }
>         }
>     ],
>     "outbounds": [
>         {
>             "protocol": "freedom"
>         }
>     ]
> }
> 

I have configured nginx as fallback server which works fine and https is enabled in browser.

This is my client side configuration :

> 
> {
>   "log": {
>     "loglevel": "warning"
>   },
>   "inbounds": [
> {
>           "listen": "127.0.0.1",
>       "protocol": "socks",
>       "settings": {
>         "udp": true,
>         "auth": "noauth"
>       },
>       "port": "1085"
> 
> }
>   ],
>   "outbounds": [
>     {
>       "protocol": "vless",
>       "settings": {
>           "vnext": [
>               {
>                   "address": "address to my website",
>                   "port": 443,
>                   "users": [
>                       {
>                           "id": "uuid",
>                           "encryption": "none",
>                           "flow": "xtls-rprx-vision"
>                       }
>                   ]
>               }
>           ]
>       },
>       "streamSettings": {
>           "network": "tcp",
>           "security": "tls",
>           "tlsSettings": {
>                  "serverName": "my website address",
>               "allowInsecure": false,
>               "fingerprint": "chrome"
>           }
>       }
>     }
>   ]
> }
> 

But this client configuration doesn't work .
When I try google.com with xray 
I  don't get anything. just following lines appear in xray log :

> 
> 2023/02/06 16:27:48 tcp:127.0.0.1:53309 accepted tcp:fonts.gstatic.com:443
> 2023/02/06 16:27:51 tcp:127.0.0.1:53344 accepted tcp:clients4.google.com:443
> 2023/02/06 16:27:52 tcp:127.0.0.1:53346 accepted tcp:mainnet.infura.io:443
> 2023/02/06 16:27:53 tcp:127.0.0.1:53354 accepted tcp:clients4.google.com:443
> 2023/02/06 16:27:53 tcp:127.0.0.1:53362 accepted tcp:mainnet.infura.io:443
> 2023/02/06 16:27:53 tcp:127.0.0.1:53364 accepted tcp:optimizationguide-pa.googleapis.com:443
> 2023/02/06 16:27:53 tcp:127.0.0.1:53366 accepted tcp:fonts.gstatic.com:443
> 2023/02/06 16:27:53 tcp:127.0.0.1:53367 accepted tcp:www.gstatic.com:443
> 2023/02/06 16:27:53 tcp:127.0.0.1:53365 accepted tcp:www.google.com:443
> 2023/02/06 16:27:55 tcp:127.0.0.1:53381 accepted tcp:www.google.com:443
> 2023/02/06 16:27:55 tcp:127.0.0.1:53383 accepted tcp:www.gstatic.com:443
> 2023/02/06 16:27:55 tcp:127.0.0.1:53385 accepted tcp:fonts.gstatic.com:443
> 2023/02/06 16:27:55 tcp:127.0.0.1:53387 accepted tcp:optimizationguide-pa.googleapis.com:443
> 2023/02/06 16:27:57 tcp:127.0.0.1:53416 accepted tcp:mainnet.infura.io:443
> 2023/02/06 16:27:58 tcp:127.0.0.1:53424 accepted tcp:mainnet.infura.io:443
> 

What do i do wrong? It seems that maybe xtls is blocked on my region which is odd because the fallback website and regular tls works fine.

**Comment by chika0801** [comment]
服务器配置

修改

```
                "security":"tls",
                "tlsSettings":{
```

你可能疏忽了
