### ISSUE TITLE
Could XTLS-RPRX-VISION be used with cdn?

### ISSUE THREAD

**Issue by arashammm** [XTLS/Xray-core#1619]
Hello there.

I have a general question...

XTLS in the concept is a very great proxy configuration which no additional encryption is used. However becuase of its charachteristics the tls certificate should be installed directly on the Xray core. I was wondering is it possible to use XTLS(RPRX-VISION mode) with cdn in between?
My main concern is since the cdn should terminate the first tls encryption and than recrypt everything to send it to xray on the server is it possible to use it and if yes does this setup interfere with XTLS and its similarity to regular tls?

 I would appreciate if anyone can refer to useful tutorial for this job.

**Comment by xianren78** [comment]
no...

**Comment by arashammm** [comment]
I'm sorry but that wasn't clear...
It's not possible to use XTLS-RPRX-VISION with cdn?

**Comment by SakuraSakuraSakuraChan** [comment]
Still no
