### ISSUE TITLE
能否集成mkcp+udp2raw

### ISSUE THREAD

**Issue by bestmikecat** [XTLS/Xray-core#1622]
用mkcp很久了,代理网页挺好用的,但发现在使用mkcp透明代理时使用远程桌面经常断线,而且下载文件速度有时也一般,相同服务器下用vmess+tcp测试反而比mkcp快,可能是被限速了,使用各种伪装类型还是没有用,因为我的某些原因有时只能用mkcp,而默认情况下在openwrt单独搭建udp2raw搭配mkcp又比较繁琐,不利于小白操作,所以能否将udp2raw或类似的faketcp功能集合在一起?感谢.

**Comment by ThreeSourLemon** [comment]
@bestmikecat 你可以试试hysteria

**Comment by bestmikecat** [comment]
> @bestmikecat 你可以试试hysteria

用过hysteria,感觉速度很一般,打开网页延迟高,我实际测试不如mkcp快,不知道为什么.

**Comment by alongL** [comment]
mkcp is not very good.
https://github.com/v2ray/v2ray-core/issues/2735

**Comment by SakuraSakuraSakuraChan** [comment]
tuic
mieru的UDP模式(同样来自于KCP)

**Comment by alongL** [comment]
> > @bestmikecat 你可以试试hysteria
> 
> 用过hysteria,感觉速度很一般,打开网页延迟高,我实际测试不如mkcp快,不知道为什么.

把hysteria配置里面的带宽值改大，hyst就像疯子一样，速度一下就起来了。（不过还是会被识别，从而qos，过一会就连不上了)
