### ISSUE TITLE
Body Encryption/Encoding 

### ISSUE THREAD

**Issue by ghost** [XTLS/Xray-core#1624]
Hi, I am trying to use vmess/vless with a CDN, i tried both tcp with http headers and h2, however in both of them the body of http request does not have any kind of encoding/encryption so my CDN will block it as a malformed http packet.

```
GET / HTTP/1.1
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: mydomain.com
Pragma: no-cache
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36 Edg/84.0.522.49

??U?9:??j??>ͦ?y=??
??`3?]1p)#z?~FH\?r? ?
*?{˞?؇??cO?q?????? T?y4rM???Z2??
                                ?
```

is there anyway to encode the body to something like base64 to avoid this problem ?

**Comment by annachan1337** [comment]
I also can't use ws due to CDN support.

**Comment by us254** [comment]
encoding the body of the HTTP request using Base64 is one solution to avoid the issue with your CDN blocking malformed HTTP packets.

Base64 is a commonly used encoding method for binary data, and it can be used to encode the body of your HTTP request so that it appears as a standard text string rather than a binary string. This will prevent the CDN from blocking the request as a malformed HTTP packet.

To encode the body of the HTTP request using Base64, you can use a Base64 encoding library in the programming language of your choice to encode the body, and then add the encoded data to the body of the HTTP request.

Here's an example in Python to demonstrate this process:

```
import base64

def encode_body_base64(body):
    # Encode the body using base64
    encoded_body = base64.b64encode(body.encode('utf-8'))
    # Decode the encoded body to a string
    decoded_body = encoded_body.decode('utf-8')
    return decoded_body

body = "??U?9:??j??>ͦ?y=??\n??`3?]1p)#z?~FH\\?r? ?\n*?{˞?؇??cO?q?????? T?y4rM???Z2??\n                                ?"
encoded_body = encode_body_base64(body)

# Add the encoded body to the HTTP request
http_request = "GET / HTTP/1.1\nAccept-Encoding: gzip, deflate\nConnection: keep-alive\nHost: mydomain.com\nPragma: no-cache\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36 Edg/84.0.522.49\n\n{}".format(encoded_body)

print(http_request)
```
This is just one example, but the process of encoding the body of the HTTP request using Base64 should be similar in other programming languages.

**Comment by annachan1337** [comment]
> encoding the body of the HTTP request using Base64 is one solution to avoid the issue with your CDN blocking malformed HTTP packets.
> 
> Base64 is a commonly used encoding method for binary data, and it can be used to encode the body of your HTTP request so that it appears as a standard text string rather than a binary string. This will prevent the CDN from blocking the request as a malformed HTTP packet.
> 
> To encode the body of the HTTP request using Base64, you can use a Base64 encoding library in the programming language of your choice to encode the body, and then add the encoded data to the body of the HTTP request.
> 
> Here's an example in Python to demonstrate this process:
> 
> ```
> import base64
> 
> def encode_body_base64(body):
>     # Encode the body using base64
>     encoded_body = base64.b64encode(body.encode('utf-8'))
>     # Decode the encoded body to a string
>     decoded_body = encoded_body.decode('utf-8')
>     return decoded_body
> 
> body = "??U?9:??j??>ͦ?y=??\n??`3?]1p)#z?~FH\\?r? ?\n*?{˞?؇??cO?q?????? T?y4rM???Z2??\n                                ?"
> encoded_body = encode_body_base64(body)
> 
> # Add the encoded body to the HTTP request
> http_request = "GET / HTTP/1.1\nAccept-Encoding: gzip, deflate\nConnection: keep-alive\nHost: mydomain.com\nPragma: no-cache\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36 Edg/84.0.522.49\n\n{}".format(encoded_body)
> 
> print(http_request)
> ```
> 
> This is just one example, but the process of encoding the body of the HTTP request using Base64 should be similar in other programming languages.

Thank you, i know how base64 encoding works.
I am looking for an option in xray.

**Comment by us254** [comment]
> Hi, I am trying to use vmess/vless with a CDN, i tried both tcp with http headers and h2, however in both of them the body of http request does not have any kind of encoding/encryption so my CDN will block it as a malformed http packet.
> 
> ```
> GET / HTTP/1.1
> Accept-Encoding: gzip, deflate
> Connection: keep-alive
> Host: mydomain.com
> Pragma: no-cache
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36 Edg/84.0.522.49
> 
> ??U?9:??j??>ͦ?y=??
> ??`3?]1p)#z?~FH\?r? ?
> *?{˞?؇??cO?q?????? T?y4rM???Z2??
>                                 ?
> ```
> 
> is there anyway to encode the body to something like base64 to avoid this problem ?

you can use HAProxy to obfuscate HTTP request body by using some options and directives. For example, you can use option http-buffer-request to give HAProxy access to the body, and then use req.body to access it. You can also use declare capture and http-request capture to capture the request body in a slot. You can also use log-format to log the request body.

**Comment by us254** [comment]
> Hi, I am trying to use vmess/vless with a CDN, i tried both tcp with http headers and h2, however in both of them the body of http request does not have any kind of encoding/encryption so my CDN will block it as a malformed http packet.
> 
> ```
> GET / HTTP/1.1
> Accept-Encoding: gzip, deflate
> Connection: keep-alive
> Host: mydomain.com
> Pragma: no-cache
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36 Edg/84.0.522.49
> 
> ??U?9:??j??>ͦ?y=??
> ??`3?]1p)#z?~FH\?r? ?
> *?{˞?؇??cO?q?????? T?y4rM???Z2??
>                                 ?
> ```
> 
> is there anyway to encode the body to something like base64 to avoid this problem ?

to use HTTP request smuggling in your example, you need to craft a request that contains both Content-Length and Transfer-Encoding: chunked headers, and then append a second request after the first one’s body[1](https://portswigger.net/web-security/request-smuggling)[2](https://www.imperva.com/learn/application-security/http-request-smuggling/). For example:

```
POST / HTTP/1.1
Host: www.baidu.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
Accept-Encoding: gzip, deflate
Connection: keep-alive
Pragma: no-cache
Content-Length: 13
Transfer-Encoding: chunked

0

SMUGGLED

GET /secret HTTP/1.1
Host: www.bing.com
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46
Accept-Encoding: gzip, deflate
Connection: keep-alive
Pragma: no-cache
```

[This request might cause the front-end server to process only the first part of the request up to SMUGGLED, and then forward the second part of the request to the back-end server as a new request](https://portswigger.net/web-security/request-smuggling)[1](https://portswigger.net/web-security/request-smuggling). [This way, you can potentially access a different resource or bypass some security checks on the back-end server](https://www.imperva.com/learn/application-security/http-request-smuggling/)[2](https://www.imperva.com/learn/application-security/http-request-smuggling/).

[However, this technique depends on how the servers handle duplicate or conflicting headers, and it might not work in every case](https://crashtest-security.com/http-request-smuggling/)[3](https://crashtest-security.com/http-request-smuggling/)[2](https://www.imperva.com/learn/application-security/http-request-smuggling/). [You also need to consider how the servers will respond to your smuggled request and whether you can receive or manipulate the response](https://honoki.net/2020/02/18/http-request-smuggling-5-practical-tips/)

**Comment by Fangliding** [comment]
impossible
