### ISSUE TITLE
境内的中转节点配置

### ISSUE THREAD

**Issue by alcatraz-zz** [XTLS/Xray-core#1627]
从本地网络到境外的代理服务器这之间有某些干扰和单纯的丢包。用softether已经弄了个中转节点，结果不错，但用xray怎么配置境内的中转节点？（vless)

是用dokodemo-door吧或者。。

**Comment by slinar** [comment]
直接iptables做nat大概会更方便一点

**Comment by alcatraz-zz** [comment]
> 中转机直接iptables做nat大概会更方便一点

谢谢回复啊。有例子吗？

中转机不在客户端那面。公网两点怎么做NAT？

**Comment by slinar** [comment]
```shell
# 参数客户端直接根据真实的远程xray服务器的参数来配置即可(客户端outbounds中address与port参数除外,应配置成中转机的IP与下方的ingress_port)
# 远程xray服务器的IP
export remote_xray_server_ip=

# 远程xray服务器的端口
export remote_xray_server_port=

# 中转机的公网IP
export out_interface_ip=

# 本地入端口(与客户端outbounds中配置的服务器端口相同)
export ingress_port=

iptables -t nat -A PREROUTING -p tcp -m tcp --dport ${ingress_port} -j DNAT --to-destination ${remote_xray_server_ip}:${remote_xray_server_port}
iptables -t nat -A POSTROUTING -p tcp -d ${remote_xray_server_ip}/32 -j SNAT --to-source ${out_interface_ip}
iptables -A FORWARD -s ${remote_xray_server_ip}/32 -j ACCEPT
iptables -A FORWARD -d ${remote_xray_server_ip}/32 -j ACCEPT
```

**Comment by alcatraz-zz** [comment]
> ```shell
> # 客户端直接根据真实的远程xray服务器的参数来配置即可(客户端outbounds中address与port参数除外,应配置成中转机的IP与下方的ingress_port)
> # 远程xray服务器的IP
> export remote_xray_server_ip=
> 
> # 远程xray服务器的端口
> export remote_xray_server_port=
> 
> # 中转机的公网IP
> export out_interface_ip=
> 
> # 本地入端口(与客户端outbounds中配置的服务器端口相同)
> export ingress_port=
> 
> # 开启IP转发
> echo 1 > /proc/sys/net/ipv4/ip_forward
> 
> iptables -t nat -A PREROUTING -p tcp -m tcp --dport ${ingress_port} -j DNAT --to-destination ${remote_xray_server_ip}:${remote_xray_server_port}
> iptables -t nat -A POSTROUTING -p tcp -d ${remote_xray_server_ip}/32 -j SNAT --to-source ${out_interface_ip}
> iptables -A FORWARD -s ${remote_xray_server_ip}/32 -j ACCEPT
> iptables -A FORWARD -d ${remote_xray_server_ip}/32 -j ACCEPT
> ```

特别好用，太好了！！！
