### ISSUE TITLE
回落不成功

### ISSUE THREAD

**Issue by XueqiangDong** [XTLS/Xray-core#1630]
从本站提供的最简单的样例测试搭建，服务器端config.json配置：
```
{
  "log": {
    "loglevel": "warning",
    "access": "/xxx/access.log",
    "error": "/xxx/error.log"
  },
  "dns": null,
  "inbounds": [
    {
      "listen": null,
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "xxx-xxx",
            "level": 0
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "dest": 6600
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "tls",
        "tlsSettings": {
          "certificates": [
            {
              "certificateFile": "/xxxxx",
              "keyFile": "/xxxxx"
            }
          ],
          "alpn": []
        },
        "tcpSettings": {
          "acceptProxyProtocol": false,
          "header": {
            "type": "none"
          }
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}
```
服务器端回落到本地，6600，使用 nginx docker 6600:6600端口映射，监控这个端口
客户端cofig.json配置
```
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "socks",
      "port": 10808,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": true
      }
    },
    {
      "tag": "http",
      "port": 10809,
      "listen": "127.0.0.1",
      "protocol": "http",
      "settings": {
        "udp": true
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "xxx.ga",
            "port": 443,
            "users": [
              {
                "id": "xxxxxx",
                "encryption": "none",
                "level": 0
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "tls"
      }
    }
  ]
}
```
代理可以正常使用，但正常的直接网址访问应该回落到 nginx ，日志显示错误：
 app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to dial to 127.0.0.1:6600 > common/retry: [dial tcp 127.0.0.1:6600: connect: connection refused] > common/retry: all retry attempts failed
大神帮看看配置哪里出了问题？
补充：网址直接 https://xxx.ga:6600 是没有问题的

**Comment by chika0801** [comment]
https://github.com/chika0801/Xray-examples/blob/main/VLESS-TCP-XTLS-Vision/config_server_with_fallbacks.json
参考下我的 nginx配置也是开了2条在接相应端口，为什么这样写我现在忘记原因了，只记得老早版本更新时官方提到推荐的，就延续下这写法。
http1.1 和h2

**Comment by XueqiangDong** [comment]
> https://github.com/chika0801/Xray-examples/blob/main/VLESS-TCP-XTLS-Vision/config_server_with_fallbacks.json 参考下我的 nginx配置也是开了2条在接相应端口，为什么这样写我现在忘记原因了，只记得老早版本更新时官方提到推荐的，就延续下这写法。 http1.1 和h2

你这里的回落 8001/8002 是 nginx 监听？nginx 是安装版本还是 docker 版本？

**Comment by chika0801** [comment]
是的，里面有nginx配置。nginx是官方安装方式，非docker。

**Comment by XueqiangDong** [comment]
我的难道是因为 docker 方式问题？安装 nginx 需要安装一大堆编译依赖，不想使用安装。
好像转过去了，nginx 有请求日志，但有错误
```
192.168.112.1 - - [08/Feb/2023:20:16:42 +0000] "PRI * HTTP/2.0" 400 157 "-" "-" "-"
```

**Comment by XueqiangDong** [comment]
把配置改成和你一样的8001/8002，nginx 也完全拷贝你的，也不行，连回落都没转到 nginx 那里

**Comment by chika0801** [comment]
我不用docker不清楚原因了，你直接安nginx测试下了

**Comment by XueqiangDong** [comment]
nginx 改成这样好像就可以了：
``` 
   listen 8001 proxy_protocol;
    listen  8002 http2 proxy_protocol;
```
看来是 nginx 配置问题，再去好好研究下，谢谢了

**Comment by XueqiangDong** [comment]
> 我不用docker不清楚原因了，你直接安nginx测试下了

理论上 docker 和直接安装没啥区别，只要注意处理好主机的 localhost 和 container 的 localhost，只是 docker 更加干净，我主力服务器就是用的 nginx docker

**Comment by XueqiangDong** [comment]
你的搭建真省事，直接回落到别人网站上，自己网站都不需要搭了

**Comment by chika0801** [comment]
有就行，nginx默认页都机，又没人看内容的

**Comment by limetw** [comment]
试试"xver": 1，或者Unix domain socket替换端口

**Comment by XueqiangDong** [comment]
> 试试"xver": 1，或者Unix domain socket替换端口

应该是 http2 的问题，我以前的 nginx 都没添加这个选项，xray 回落应该是默认使用了 http2

**Comment by shaoberry** [comment]
is webserver http2, e.g. wordpress? I set `http2 on` in nginx.conf and fixed the issue.
