### ISSUE TITLE
Which is better? WS or Vision?

### ISSUE THREAD

**Issue by alan21j** [XTLS/Xray-core#1633]

**Comment by chika0801** [comment]
推荐使用Vision

**Comment by RPRX** [comment]
WS 的 ALPN 特征过于明显，直连肯定不用它，套 CDN 首选 GPRC，其次 WS

**Comment by MJamshidnejad** [comment]
> The ALPN feature of WS is too obvious

What do you mean by "The ALPN feature of WS is too obvious"?
