### ISSUE TITLE
可以告诉开发者 现在 fingerprint 支持哪些协议吗

### ISSUE THREAD

**Issue by cary-sas** [XTLS/Xray-core#1635]
你好，
有没有文档可以帮我们归纳一下，客户端下的参数 fingerprint 可以适用于哪些协议吗？ 因为xray 支持的协议很多，不知道哪些协议和组合可以用  fingerprint 这个参数

**Comment by chika0801** [comment]
xray更新日志有提到

目前推荐用的是（交流用缩写）
 vless tcp tls vision

还有就是
xxx ws tls 也可用 utls功能

**Comment by RPRX** [comment]
TCP / WS / H2 / GRPC
+
TLS / REALITY
