### ISSUE TITLE
Failed to use xtls-rprx-vision, found outer tls version 771 

### ISSUE THREAD

**Issue by Narakuku** [XTLS/Xray-core#1643]
使用docker版本客户端 升级为1.7.5
https://hub.docker.com/r/teddysun/xray

服务端客户端都改为xtls-rprx-vision模式之后，报错
app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to use xtls-rprx-vision, found outer tls version 771

**Comment by Narakuku** [comment]
自行解决：
删除VMess残留配置
"security": "auto",
之后解决 😓

**Comment by Narakuku** [comment]
> 自行解决： 删除VMess残留配置 "security": "auto", 之后解决 😓

莫名其妙问题又出现了 目前发现可能不是 "security": "auto", 参数导致 很奇怪

**Comment by Narakuku** [comment]
目前发现可能和指纹参数有关

>       "fingerprint": "random",

客户端重启之后随机出现

**Comment by RPRX** [comment]
> 目前发现可能和指纹随机参数有关
> 
> > ```
> >   "fingerprint": "random",
> > ```
> 
> 客户端重启之后随机出现

https://github.com/XTLS/Xray-core/commit/4d5c3195d2a6efd6fe33fd13ad79e0b54d213937

**Comment by Amaterasu33** [comment]
1.7.5 目前发现Fingerprint设置为 android或者360 会导致出现found outer tls version 771的问题，其他的选项都正常

**Comment by RPRX** [comment]
> 1.7.5 目前发现Fingerprint设置为 android或者360 会导致出现found outer tls version 771的问题，其他的选项都正常

https://github.com/XTLS/Xray-core/issues/1666#issuecomment-1435494076

**Comment by Amaterasu33** [comment]
> > 1.7.5 目前发现Fingerprint设置为 android或者360 会导致出现found outer tls version 771的问题，其他的选项都正常
> 
> [#1666 (comment)](https://github.com/XTLS/Xray-core/issues/1666#issuecomment-1435494076)

👍感谢
