### ISSUE TITLE
水狐频繁触发“建立安全连接失败”

### ISSUE THREAD

**Issue by CussiusKon** [XTLS/Xray-core#1645]
水狐浏览器最新版，xray两端版本均为1.7.5。
服务端配置如下，客户端使用xrayn 6.9版本

> {
  "log": {
    "loglevel": "error"
    ,"access": "/var/log/xray/access.log"
    ,"error": "/var/log/xray/error.log"
  },
  // 2_DNS 设置
  "dns": {
    "servers": [
      "https+local://1.1.1.1/dns-query",
      "localhost"
    ]
  },
  // 3*分流设置
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "ip": [
         "geoip:private"
        ],
        "outboundTag": "block"
      },
      {
        "type": "field",
        "domain": [
	  "geosite:private",
            "geosite:category-ads-all"
        ],
        "outboundTag": "block" 
      },
      {
        "type": "field",
        "domain": [
          "domain:googleapis.cn",
          "geosite:google",
          "geosite:steam"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "ip": [
         "geoip:google"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "domain": [
          "geosite:cn"
        ],
        "outboundTag": "block"
      },
      {
        "type": "field",
        "ip": [
          //"geoip:private",
          "geoip:cn"
        ],
        "outboundTag": "block"
      }
    ]
  },
  "inbounds": [
    {
      "listen": "0.0.0.0",
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "123",
            "flow": "xtls-rprx-vision"
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            //"alpn": "h2",
            "xver": 1,
            "dest": 1234
          },
          {
            "alpn": "h2",
            "xver": 1,
            "dest":  1235
          },
          {
            "path": "/abc",
            "xver": 1,
            "dest": 1236
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "tls",
        "tlsSettings": {
          "rejectUnknownSni": true,
          "minVersion": "1.2",
          "certificates": [
            {
              "certificateFile": "xxx",
              "keyFile":         "xxx"
            }
          ]
        }
      }
      ,
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ],
        "routeOnly": true
      }
    },
    {
      "port": 1236,
      "listen": "127.0.0.1",
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "123"
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
      "network": "ws",
      "security": "none",
      "wsSettings": {
        "acceptProxyProtocol": true, // 提醒：若你用 Nginx/Caddy 等反代 WS，需要删掉这行
        "path": "/abc" // 必须换成自定义的 PATH，需要和上面的一致
        }
      }
    }
  ],
  // 5*出站设置
  "outbounds": [
    // 5.1 第一个出站是默认规则，freedom 就是对外直连（vps 已经是外网，所以直连）
    {
      "tag": "direct",
      "protocol": "freedom"
    },
    // 5.2 屏蔽规则，blackhole 协议就是把流量导入到黑洞里（屏蔽）
    {
      "tag": "block",
      "settings": {
          "response": {
               "type": "http"
          }
      },
      "protocol": "blackhole"
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "handshake": 2,
        "connIdle": 120,
        "uplinkOnly": 1,
        "downlinkOnly": 1
      }
    }
}

xrayn正常配置，vless tcp tls，流控vision。使用水狐浏览器高频率建立安全连接失败，edge也会有，但少的多，偶尔会出现。

**Comment by CussiusKon** [comment]
网站打开一次后，短时间再打开此站点就很快，但是隔一段时间再打开就很慢，或者直接报错打不开。
水狐错误提示：
`建立安全连接失败

连接到 www.youtube.com 时发生错误。PR_END_OF_FILE_ERROR

    由于不能验证所收到的数据是否可信，无法显示您想要查看的页面。
    建议向此网站的管理员反馈这个问题。`

edge错误提示：
`嗯… 无法访问此页面似乎 www.google.com 关闭了连接
请尝试：

检查连接
[检查代理和防火墙](chrome-error://chromewebdata/#buttons)
[运行 Windows 网络诊断](javascript:diagnoseErrors())
ERR_CONNECTION_CLOSED`
edge有时先显示错误页面后接着自动刷新就正常打开网页了，很奇怪。

xrayn控制台显示最多日志：
`[Warning] [267878046] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [read tcp 192.168.1.11:54786->:443: wsarecv: An existing connection was forcibly closed by the remote host. read tcp 192.168.1.11:54787->:443: wsarecv: An existing connection was forcibly closed by the remote host. read tcp 192.168.1.11:54793->:443: wsarecv: An existing connection was forcibly closed by the remote host. read tcp 192.168.1.11:54796->443: wsarecv: An existing connection was forcibly closed by the remote host. read tcp 192.168.1.11:54798->:443: wsarecv: An existing connection was forcibly closed by the remote host.] > common/retry: all retry attempts failed`

**Comment by chika0801** [comment]
你先把服务器配置换成Xray github模板里的版本，测试下故障能不能复现了。

**Comment by CussiusKon** [comment]
> 你先把服务器配置换成Xray github模板里的版本，测试下故障能不能复现了。

你说的是这个模板吗 https://github.com/XTLS/Xray-examples/blob/main/VLESS-TCP-XTLS-Vision/config_server.json，试过了表现和我之前的配置差别不大，另外想问一下监听端口一般不是用443吗，现在改变了吗？

**Comment by chika0801** [comment]
是这个。如果你这配置现象复现，配置问题的可能性很小。不是必须用443，其它端口也可以。
盲猜你vps商家是？或者你用一个配置文件，在不同vps上测试，排除vps线路问题。

**Comment by CussiusKon** [comment]
> 是这个。如果你这配置现象复现，配置问题的可能性很小。不是必须用443，其它端口也可以。 盲猜你vps商家是？或者你用一个配置文件，在不同vps上测试，排除vps线路问题。

龟壳。之前一直用的老版本套cdn，pre版我都没升级，最近看到正式版发布就升上来了，发现只要用vision就有这个现象，前几次进网页超级慢，并且极高概率报错。可能跟线路也有一定关系，本来速度也不怎么快。

**Comment by hnliuzesen** [comment]
> > 是这个。如果你这配置现象复现，配置问题的可能性很小。不是必须用443，其它端口也可以。 盲猜你vps商家是？或者你用一个配置文件，在不同vps上测试，排除vps线路问题。
> 
> 龟壳。之前一直用的老版本套cdn，pre版我都没升级，最近看到正式版发布就升上来了，发现只要用vision就有这个现象，前几次进网页超级慢，并且极高概率报错。可能跟线路也有一定关系，本来速度也不怎么快。

跟线路可能没关系，我的是香港的服务器，之前速度和延迟都挺快的，换了流控之后用 Chrome 也经常出现这个问题，在网上搜说是被墙了，但都是间歇性的，就没去查问题原因。日志类似这样 app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp <server_ip>:443: operation was canceled] > common/retry: all retry attempts failed

**Comment by GleenJi** [comment]
我一直以为是正常现象，我也是经常第一次连接连不上，再连才能好，日志里也有不少这种错误

**Comment by abelyuan00** [comment]
出现相同情况

**Comment by CussiusKon** [comment]
两端都更新至最新版本后，这个问题几乎没有再出现，先关闭了
