### ISSUE TITLE
ShadowsocksR Plus+无法运行Xray-core v1.7.5内核

### ISSUE THREAD

**Issue by siren202101** [XTLS/Xray-core#1648]
平台：360T7路由器
插件：ShadowsocksR Plus+
只要升级Xray-core v1.7.5内核就无法运行

**Comment by fuokgfw** [comment]
这个，你得找L大解决吧···

**Comment by zxczaq001** [comment]
https://github.com/fw876/helloworld/issues/1107
应该是这个问题 升级你的luci

**Comment by chika0801** [comment]
推荐你用这个的源码 https://github.com/hanwckf/immortalwrt-mt798x 能正常编译，我试了

**Comment by RPRX** [comment]
> [fw876/helloworld#1107](https://github.com/fw876/helloworld/issues/1107) 应该是这个问题 升级你的luci

√
