### ISSUE TITLE
Socks5 inbound via unix domain socket

### ISSUE THREAD

**Issue by GektorUA** [XTLS/Xray-core#1649]
Is it possible configure Xray to accept  Socks5 Unix socket inbound?

**Comment by hacker5510** [comment]
> Is it possible configure Xray to accept Socks5 Unix socket inbound?

https://xtls.github.io/config/inbound.html#inboundobject
![image](https://user-images.githubusercontent.com/18069281/218310291-addb7dfe-212d-439c-96f1-7f17ab714114.png)
