### ISSUE TITLE
不定时随机连发3个莫名请求，并立即fialed,是xray的运行机制么？

### ISSUE THREAD

**Issue by KC9226** [XTLS/Xray-core#165]
2021/01/14 01:51:20 127.0.0.1:52137 accepted http://clkamnus/ [proxy]
2021/01/14 01:51:20 127.0.0.1:52138 accepted http://atmesdeexldlmv/ [proxy]
2021/01/14 01:51:20 127.0.0.1:52139 accepted http://fqcczbrps/ [proxy]
2021/01/14 01:51:21 [Warning] [156741643] proxy/http: failed to read response from atmesdeexldlmv > io: read/write on closed pipe
2021/01/14 01:51:21 [Warning] [2843073855] proxy/http: failed to read response from fqcczbrps > io: read/write on closed pipe
2021/01/14 01:51:22 [Warning] [1978544652] proxy/http: failed to read response from clkamnus > io: read/write on closed pipe
Xray不定时随机连发3个莫名请求，并立即fialed,是xray的运行机制么？
如上面三个随机http链接，请指教。

**Comment by rprx** [comment]
不是，这应该是你在浏览器地址栏输入时，浏览器随时发起的请求

**Comment by DuckSoft** [comment]
@KC9226 这是 Chrome

**Comment by badO1a5A90** [comment]
鸭鸭大佬好像打字丢了一半,帮鸭鸭大佬补完
"这是 chrome 用来判断当前网络环境用的随机请求"

https://mikewest.org/2012/02/chrome-connects-to-three-random-domains-at-startup/
