### ISSUE TITLE
XTLS-RPRX-VISION+Xray-core1.7.5访问远程桌面时出现错误

### ISSUE THREAD

**Issue by dogxgit** [XTLS/Xray-core#1652]
本地客户端V2RayN，使用XTLS-RPRX-VISION流控，访问远程桌面出现了一个错误，指示【发生身份验证错误 给函数提供的标志无效】。此错误发生在Xray-core版本1.7.5中。当切回Xray-core版本1.7.3时，则没有出现该错误。

**Comment by yuhan6665** [comment]
麻烦试一下 https://github.com/XTLS/Xray-core/actions/runs/4159105019
如果仍然有问题请发两端日志

**Comment by dogxgit** [comment]
> 麻烦试一下 https://github.com/XTLS/Xray-core/actions/runs/4159105019 如果仍然有问题请发两端日志

更换后一切正常

**Comment by Gzxhwq** [comment]
@yuhan6665 https://github.com/XTLS/Xray-core/pull/1646 这个可以rebase一下吗？action里的没有reality，但是又碰到这个bug
