### ISSUE TITLE
使用iptables过滤DNS污染/抢答

### ISSUE THREAD

**Issue by hkbase** [XTLS/Xray-core#1658]
具体方法参考下面的链接：
https://ilpl.me/2021/08/15/LInux-iptables-security-dns/
文中的方法，截止到今日依然有效。
经过本人实测，真的很完美，麻烦RPRX老大看一下，能否借鉴进xray里，让xray越来越好。

**Comment by wyx2685** [comment]
直接硬查dns是不是生怕gfw不知道你在访问什么网站

**Comment by azzvx** [comment]
为啥不反过来考虑。如果发现GFW抢答IP，就强制走代理？
