### ISSUE TITLE
不能正常接受 Proxy Protocol 的 LOCAL（本地请求）

### ISSUE THREAD

**Issue by bohanyang** [XTLS/Xray-core#166]
inbound 的 acceptProxyProtocol 不能正常接受本地请求

已测试无法正常工作的"本地请求"：
* Haproxy 转发本地 unix socket 到 xray (Proxy Protocol v1 v2 都不行，xray tcp+xtls websocket 都不行)
* Haproxy 2+ `send-proxy-v2` 的 health check（使用了 LOCAL command 而不是 PROXY command）。 见 haproxy/haproxy#511

虽然是比较小众的 bug ，但还是希望能够修复
不确定是不是跟底层所用的 pires/go-proxyproto 有关

**Comment by rprx** [comment]
TCP 的有问题吗

**Comment by bohanyang** [comment]
有问题。试了一下 vmess tcp（无加密无TLS）也不行
因为 vmess outbound address 好像不支持 unix socket，为了测试，haproxy 又配置了一个端口转发到 socket
测试配置
```
frontend test1
  bind 127.0.0.1:7665
  default_backend test2

backend test2
  server test2-1 unix@/run/haproxy/web.sock

frontend inbound
  bind 127.0.0.1:7664
  bind unix@/run/haproxy/web.sock user haproxy mode 666
  default_backend xray

backend xray
  server xray-1 127.0.0.1:9800 send-proxy
```
这样配置的话 `send-proxy` 发送的源地址应该是 unix socket，就不行（客户端报错`[Warning] [2229848210] proxy/http: failed to read response from example.com > io: read/write on closed pipe`）
backend test2 换成 127.0.0.1:7664 就正常（ `send-proxy` 发送的源地址应该是 127.0.0.1）

**Comment by rprx** [comment]
看起来这里的问题是不能接收 unix 地址？

**Comment by bohanyang** [comment]
嗯，是这个意思。同样接收 unix 地址 proxy protocol，nginx 没问题，但 xray 不行。
不太会 golang，尝试修改 https://github.com/XTLS/Xray-core/blob/d85162ea44ff99d9aad6e7117fcef41e950fda8b/transport/internet/system_listener.go#L80
为 proxyproto.USE 好像没效果

**Comment by bohanyang** [comment]
应该不是底层库的问题，测试能正常接收请求

**Comment by rprx** [comment]
可能是当前代码里的 Address 结构不支持存 DS 地址

**Comment by bohanyang** [comment]
搞了半天忘记开 debug log 了……
有两种错误
```
Jan 14 14:08:54 server xray[26814]: 2021/01/14 14:08:54 [Info] [686264629] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > address @: missing port in address
Jan 14 14:10:15 server xray[27184]: 2021/01/14 14:10:15 [Info] [2599772984] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > proxyproto: can't read proxy protocol version and command
```

**Comment by bohanyang** [comment]
pp v2 的问题已经找到，
hexdump 出的 pp header `00000000  0d 0a 0d 0a 00 0d 0a 51  55 49 54 0a 20 00 00 00` 第 14 个 byte 是 UNSPEC (\x00)
而 https://github.com/pires/go-proxyproto/blob/adbbabed1f24a2123e1d4368ae8da8378b347643/addr_proto.go#L16
里面没有 UNSPEC

**Comment by bohanyang** [comment]
pp v1 的问题也已经找到，一般是 `PROXY <PROTO> <SRC_ADDR> <DEST_ADDR> <SRC_PORT> <DEST_PORT>`
空格隔开分 6 部分。
```
00000000  50 52 4f 58 59 20 54 43  50 34 20 31 32 37 2e 30  |PROXY TCP4 127.0|
00000010  2e 30 2e 31 20 31 32 37  2e 30 2e 30 2e 31 20 35  |.0.1 127.0.0.1 5|
00000020  30 33 31 38 20 37 36 36  34 0d 0a 16 03 01 01 1f  |0318 7664.......|
```
而 unknown connection 是`PROXY UNKNOWN`只有两部分。
可是 https://github.com/pires/go-proxyproto/blob/adbbabed1f24a2123e1d4368ae8da8378b347643/v1.go#L31
这个实现无情地拒绝了 len < 6 的 header

v2 的 UNSPEC 和 v1 的 "PROXY UNKNOWN\r\n" 都是协议规定的，可以给 pires/go-proxyproto 提个 issue 或 pr 解决一下

**Comment by rprx** [comment]
https://github.com/XTLS/Xray-core/releases/tag/v1.2.3
