### ISSUE TITLE
Add plugin system

### ISSUE THREAD

**Issue by meaqese** [XTLS/Xray-core#1663]
Thank you for your work! 

I think it is necessary to add a plugin system, for example as in https://github.com/drk1wi/Modlishka . This would allow us to improve xray for ourselves, but without changing the core itself and keep the possibility of fast core updates in the future.

**Comment by Michaol** [comment]
Is that similar to Caddy2 or Nginx? Xray-core works perfectly with Caddy2 and Nginx.

**Comment by meaqese** [comment]
> Is that similar to Caddy2 or Nginx? Xray-core works perfectly with Caddy2 and Nginx.

No, by plugins I mean a plugin written in Golang that, for example, can do something with every request. I.e. we will have to write a plugin, and we will be able to integrate it with xray without pain.

I think this will open up a new part of the development of xray-core, where people will make additions to xray-core, but without touching the source code.

Imagine the situation, as it usually happens, somebody cool guy make a fork of the original repository (xray-core), make some changes, everything is fine and everyone is happy, a few months pass, the fork is thrown away, and you have already implemented this fork on the prod and then what to do? How to develop further? How to keep up with new versions of the original repository?

I have indicated above only a part of the problems that the plugin system can solve, I am sure there are other problems that it could solve.
