### ISSUE TITLE
[功能请求] `security` 支持 SChannel

### ISSUE THREAD

**Issue by xqzr** [XTLS/Xray-core#1665]
例：
```json
{
    "security": "schannel"
}
```
相关链接：
https://learn.microsoft.com/zh-cn/windows/win32/com/schannel
https://pkg.go.dev/github.com/alexbrainman/sspi/schannel

**Comment by rurirei** [comment]
>> supports the following public-key based protocols: SSL (Secure Sockets Layer) versions 2.0 and 3.0, Transport Layer Security (TLS) 1.0, and Private Communication Technology (PCT) 1.0.

what about the PCT 1.0?
