### ISSUE TITLE
Xray-core crashed when establishing connections to a new configuration profile

### ISSUE THREAD

**Issue by testcaoy7** [XTLS/Xray-core#1666]
Xray-core version: c7358a3 (Downloaded from GitHub Action Build)
Xray-core will crash and return "panic: runtime error: invalid memory address or nil pointer dereference" when served as client role.

Oddly, this error only happen once, in the first attempt to connect to a new configuration profile. The second run returns no error and I do not know if xray server will crash due to the server will be restarted by my systemd service profile.

Please see the attachment for detail.

![screenshot](https://user-images.githubusercontent.com/11433217/219827474-e9d169df-5ea9-4643-9906-488558105299.jpg)

**Comment by RPRX** [comment]
对了，指纹是 `randomized` 吗？

**Comment by RPRX** [comment]
你可以把你的 GitHub 绑到那个机器人上，就可以直接用 Telegram 回复了

**Comment by testcaoy7** [comment]
@RPRX "fingerprint": "random"
请问是正确的值是"randomized"吗

**Comment by RPRX** [comment]
> @RPRX "fingerprint": "random" 请问是正确的值是"randomized"吗

不是，推荐优先用这两个以外的

目前猜测 `random` 内某些指纹不支持 TLSv1.3，导致 `uConn.HandshakeState.State13.EcdheParams == nil`，具体的我需要再看看

**Comment by RPRX** [comment]
目前发现这三个指纹不支持 TLSv1.3
- `HelloIOS_12_1`
- `HelloAndroid_11_OkHttp`
- `Hello360_7_5`

**Comment by RPRX** [comment]
目前发现 `random` 内这三个指纹不支持 TLSv1.3
- `HelloIOS_12_1`
- `HelloAndroid_11_OkHttp`
- `Hello360_7_5`

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/commit/4d5c3195d2a6efd6fe33fd13ad79e0b54d213937 选 `random` 应该没问题了

对于 Vision 和 REALITY，暂不能选 `android` 和 `360`，它们指向的指纹不支持 TLSv1.3

**Comment by RPRX** [comment]
~~REALITY 有 Vision 的 Splice 可用，干嘛还要同是内核态的 eBPF，不如网卡直接转发~~

[REALITY](https://github.com/XTLS/REALITY) 即将 256 stars，加油！

**Comment by RPRX** [comment]
XTLS 高性能的核心在于 ReadV 和 Splice，**由操作系统内核支持，与改不改 TLS 库无关**

想要更高的性能，只有硬件级转发，需要网卡支持该功能，有兴趣的试试怎么调用

**Comment by Fangliding** [comment]
@RPRX 快点端上来罢
