### ISSUE TITLE
proper way to restart xray ?

### ISSUE THREAD

**Issue by ffallah** [XTLS/Xray-core#1668]
Whenever I restart my xray process by killing it, I end up with too many orphaned sockets :
```
[Feb18 09:00] net_ratelimit: 1283 callbacks suppressed
[  +0.000001] TCP: too many orphaned sockets
[  +0.004094] TCP: too many orphaned sockets
[  +0.000625] TCP: too many orphaned sockets
[  +0.000543] TCP: too many orphaned sockets
[  +0.000595] TCP: too many orphaned sockets
[  +0.002491] TCP: too many orphaned sockets
[  +0.000558] TCP: too many orphaned sockets
[  +0.000559] TCP: too many orphaned sockets
[  +0.000524] TCP: too many orphaned sockets
[  +0.000560] TCP: too many orphaned sockets
```
is there a proper way to restart xray so it closes the sockets properly before restart ?

**Comment by cross-hello** [comment]
For termux maybe you just could `pkill`.
For linux you could try `systemctl restart xray`.(you have to write xray service file before. For reference, see ***@***.***/creating-a-linux-service-with-systemd-611b5c8b91d6` )

**Comment by ffallah** [comment]
What you have both proposed is the same as killing the process and doesnt answer my question. we probably need a commit to send xray the stop signal. something like "xray stop".

**Comment by cross-hello** [comment]
All right, why non-golang worker how to deal with such depth technique detail. 
See here:  https://stackoverflow.com/a/37980397
