### ISSUE TITLE
less+tcp + xtls-rprx-vision ，无法使用443端口作为代理

### ISSUE THREAD

**Issue by James-handsome** [XTLS/Xray-core#1670]
xray 1.75版本，搭建的是 vless+tcp + xtls-rprx-vision 的模式, 发生一件奇怪的事情，就是无法使用443端口作为代理，使用443端口，会连接不上，使用3000端口，可以正常使用
{
      "port": 3000,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "xxxxx",
            "flow": "xtls-rprx-vision"
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "dest": 8080
          }
        ]
      },

**Comment by chika0801** [comment]
测试方法，先把你现在配置的监听端口改回443，重启xray或vps生效。去 ping.pe 输入ip:端口 如果只有cn地区不通，意思是443端口被封。

**Comment by James-handsome** [comment]
> 测试方法，先把你现在配置的监听端口改回443，重启xray或vps生效。去 ping.pe 输入ip:端口 如果只有cn地区不通，意思是443端口被封。

我试试

**Comment by RPRX** [comment]
如果你之前用了其它协议导致 TCP/443 端口被封，**Vision 并没有“解封已经被封的端口”的能力**，换个 IP 或端口

如果这是你新开到的 IP，说明这个 IP 的 TCP/443 端口已经被别人搞封了，换个 IP 或端口
