### ISSUE TITLE
运行./xray x25519失败

### ISSUE THREAD

**Issue by mhnhh123** [XTLS/Xray-core#1676]
我按照https://github.com/XTLS/REALITY运行   ./xray x25519报错
root@racknerd-b07d66:/usr/local/bin# ./xray x25519
xray x25519: unknown command
Run 'xray help' for usage.
已配置xray环境版本号是v1.7.5
root@racknerd-b07d66:/usr/local/bin# xray version
Xray 1.7.5 (Xray, Penetrates Everything.) Custom (go1.20 linux/amd64)
A unified platform for anti-censorship.
服务器是racknerd
安装的系统是Debian11
root@racknerd-b07d66:/usr/local/bin# cat /etc/debian_version
11.6

**Comment by SQLimit** [comment]
这个版本还不支持REALITY，需要在action里下载最新编译的版本才能用REALITY

**Comment by FranzKafkaYu** [comment]
@mhnhh123 你需要运行最新的xray core,请从action中下载最新版本或者自行编译最新版本进行测试使用。

**Comment by Edwin-Kevin** [comment]
reality目前还没进版，可以等发版或者去action里面下载编译好的版本

**Comment by limetw** [comment]
wget https://go.dev/dl/go1.20.1.linux-amd64.tar.gz && tar -C /usr/local -xzf go1.20.1.linux-amd64.tar.gz && export PATH=$PATH:/usr/local/go/bin && go version && git clone https://github.com/XTLS/Xray-core.git && cd Xray-core && go mod download && CGO_ENABLED=0 go build -o xray -trimpath -ldflags "-s -w -buildid=" ./main && systemctl stop xray && mv xray /usr/local/bin/xray && systemctl start xray && cd /root && rm -rf /root/Xray-core

**Comment by Nirvanatin** [comment]
How do we fix this?
```
error obtaining VCS status: exit status 128
        Use -buildvcs=false to disable VCS stamping.
```

**Comment by cross-hello** [comment]
Literal mean, append `
> *-buildvcs=false*
` to which command you fail.

Feb 19, 2023 23:02:31 Nirvanatin ***@***.***>:

**Comment by Nirvanatin** [comment]
完成了，谢谢你。可以请你给我一点客户那端的提示吗？

**Comment by cross-hello** [comment]
How could you hold a mirror and ask where to look face?

Feb 20, 2023 01:29:31 Nirvanatin ***@***.***>:

**Comment by chika0801** [comment]
> wget https://go.dev/dl/go1.20.1.linux-amd64.tar.gz && tar -C /usr/local -xzf go1.20.1.linux-amd64.tar.gz && export PATH=$PATH:/usr/local/go/bin && go version && git clone https://github.com/XTLS/Xray-core.git && cd Xray-core && go mod download && CGO_ENABLED=0 go build -o xray -trimpath -ldflags "-s -w -buildid=" ./main && systemctl stop xray && mv xray /usr/local/bin/xray && systemctl start xray && cd /root && rm -rf /root/Xray-core

thank you.

**Comment by naadercc** [comment]
> @mhnhh123You need to run the latest xray core, please download the latest version from action or compile the latest version for testing.

should the latest action-compiled version be used on the server side or just the client side or both?

**Comment by chika0801** [comment]
> 完成了，谢谢你。可以请你给我一点客户那端的提示吗？

https://github.com/chika0801/Xray-examples/blob/main/VLESS-XTLS-uTLS-REALITY/config_client.json

服务端配置有2个，一个自己偷自己,nginx来加载tls证书。另一个就是偷别人网站的形式。
