### ISSUE TITLE
RPRX Vision + Reality 配合 HaProxy 不成功

### ISSUE THREAD

**Issue by LearZhou** [XTLS/Xray-core#1678]
配置參考了 RPRX 剛剛更新的配置說明。構架採用的是 HaProxy 前置，用某知名網站的域名作為 serverName。

在 HaProxy 用的第4層 sni 判斷進行轉發，但是這樣連不通。

是否可能用 HaProxy 前置用 sni 分流轉發的方式，來支持不同用途的多域名？

如果確認可能，那我會貼出自己的配置，請大佬幫看看哪裡出錯了。

BTW，客戶端和服務器端都更新到了每日構建版。

**Comment by RPRX** [comment]
> 是否可能用 HaProxy 前置用 sni 分流轉發的方式，來支持不同用途的多域名？

可，REALITY 是强化版 TLSv1.3，但流量外观仍是普通 TLSv1.3，支持被 SNI 分流（需要客户端发了 SNI）

我猜你可能给 HaProxy 配置了发 PROXY protocol，但没给 Xray 配置接收，或者反过来了

**Comment by LearZhou** [comment]
破案啦！原來是服務器新加入了一個監聽端口用於 Vision + Reality，但卻忘記開防火牆了。

**Comment by LearZhou** [comment]
雖然能用了，但是在 HaProxy 使用 send-proxy-v2，Xray 接收方該怎麼配置不太清楚，試著改了幾種組合都沒成功。

@RPRX 能否給一個示例？因為用 Proxy protocol 還是有一些用處的，比如測試時在 log 裡面顯示 ip 來處等。

**Comment by RPRX** [comment]
单个 inbound 的 `"sockopt"` 设 `"acceptProxyProtocol": true`
