### ISSUE TITLE
为什么1.7.2版本的文件与1.7.5版本的文件是一样的？都是2023.01.01 08:00:00的文件，大小也一样。确定是不通版本的文件？

### ISSUE THREAD

**Issue by weew2** [XTLS/Xray-core#1680]
为什么1.7.2版本的文件与1.7.5版本的文件是一样的？都是2023.01.01 08:00:00的文件，大小也一样。确定是不通版本的文件？

**Comment by FranzKafkaYu** [comment]
@weew2 你应该先确认是否是你自己的操作问题，可以先对比md5值。

**Comment by weew2** [comment]
> 
我是下载之后，添加到项目中，SVN提示就是同一个文件，才进行了检查，发现日期和大小都一样，才来问下的

**Comment by weew2** [comment]
> @weew2 你应该先确认是否是你自己的操作问题，可以先对比md5值。

我是下载之后，添加到项目中，SVN提示就是同一个文件，才进行了检查，发现日期和大小都一样，才来问下的

**Comment by Fangliding** [comment]
@Fangliding Xray-android-arm64-v8a.zip

1.7.5
MD5= 8ceb0046b8db47c4039e94457006b851
1.7.2
MD5= 5e10d86446308c783e0211c6332a59b8

**Comment by FranzKafkaYu** [comment]
> > @weew2 你应该先确认是否是你自己的操作问题，可以先对比md5值。
> 
> 我是下载之后，添加到项目中，SVN提示就是同一个文件，才进行了检查，发现日期和大小都一样，才来问下的

如果真是这种错误，社区早就发现了，你应该检查自己的操作，或者通过比对哈希校验等方式来进行确认。

**Comment by weew2** [comment]
通过md5确实获取的值不一致。
