### ISSUE TITLE
wireguard output 在树莓派3b+ 报错

### ISSUE THREAD

**Issue by billzhuang** [XTLS/Xray-core#1682]
最新版 1.7.5

跑在树莓派3b+上，armv7 32位u，启动后，访问wg出口时，便会报如下错位

···
Feb 20 11:35:01 raspberrypi xray[29332]:         github.com/sagernet/wireguard-go@v0.0.0-20221116151939-c99467f53f2c/device/receive.go:290 +0x454
Feb 20 11:35:01 raspberrypi xray[29332]: github.com/sagernet/wireguard-go/device.(*Device).RoutineHandshake(0x1b3b680, 0x1)
Feb 20 11:35:01 raspberrypi xray[29332]:         github.com/sagernet/wireguard-go@v0.0.0-20221116151939-c99467f53f2c/device/device.go:224 +0x118
Feb 20 11:35:01 raspberrypi xray[29332]: github.com/sagernet/wireguard-go/device.(*Device).IsUnderLoad(0x1b3b680)
Feb 20 11:35:01 raspberrypi xray[29332]:         go.uber.org/atomic@v1.10.0/int64.go:45
Feb 20 11:35:01 raspberrypi xray[29332]: go.uber.org/atomic.(*Int64).Load(...)
Feb 20 11:35:01 raspberrypi xray[29332]:         runtime/internal/atomic/atomic_arm.s:280 +0x14
Feb 20 11:35:01 raspberrypi xray[29332]: runtime/internal/atomic.Load64(0x1b3b754)
Feb 20 11:35:01 raspberrypi xray[29332]:         runtime/internal/atomic/unaligned.go:8 +0x24
Feb 20 11:35:01 raspberrypi xray[29332]: runtime/internal/atomic.panicUnaligned()
Feb 20 11:35:01 raspberrypi xray[29332]: goroutine 1605 [running]:
Feb 20 11:35:01 raspberrypi xray[29332]: panic: unaligned 64-bit atomic operation
···

是个bug？ https://pkg.go.dev/sync/atomic#pkg-note

还是编译的问题？还是我的问题？

**Comment by Fangliding** [comment]
无日志
