### ISSUE TITLE
REALITY过程中xray.service报错

### ISSUE THREAD

**Issue by mhnhh123** [XTLS/Xray-core#1686]
我的服务器是racknerd
系统是Debian11
按照https://github.com/chika0801/Xray-examples/tree/main/VLESS-XTLS-uTLS-REALITY
在https://github.com/XTLS/Xray-core/actions/runs/4209833887下载服务端[Xray-linux-64](https://github.com/XTLS/Xray-core/suites/11060561984/artifacts/562395505)
通过Xftp上传至/root目录下
权限是root@racknerd-b07d66:~# ls -al
total 48408
drwx------  5 root root     4096 Feb 20 23:43 .
drwxr-xr-x 18 root root     4096 Feb 20 23:04 ..
drwx------  7 root root     4096 Feb 20 23:12 .acme.sh
-rw-r--r--  1 root root      602 Feb 20 23:11 .bashrc
drwxr-xr-x  2 root root     4096 Feb 20 23:21 bin
-rw-r--r--  1 root root  9579189 Feb 18 05:57 geoip.dat
-rw-r--r--  1 root root  1519067 Feb 18 05:57 geosite.dat
-rw-r--r--  1 root root    16725 Feb 18 05:57 LICENSE
drwxr-xr-x  3 root root     4096 Aug 19  2021 .local
-rw-r--r--  1 root root      161 Jul  9  2019 .profile
-rw-r--r--  1 root root     3658 Feb 18 05:57 README.md
-rw-------  1 root root      122 Feb 20 23:36 .Xauthority
-rwxrwxrwx  1 root root 25862144 Feb 18 05:57 xray
-rwxrwxrwx  1 root root     1983 Feb 20 23:18 xray.json
-rw-r--r--  1 root root 12540683 Feb 20 23:07 Xray-linux-64.zip
-rwxrwxrwx  1 root root      336 Feb 20 23:43 xray.service
服务端
{
    "log": {
        "loglevel": "warning"
    },
    "routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "type": "field",
                "domain": [
                    "geosite:category-ads-all"
                ],
                "outboundTag": "block"
            },
            {
                "type": "field",
                "ip": [
                    "geoip:cn"
                ],
                "outboundTag": "block"
            }
        ]
    },
    "inbounds": [
        {
            "listen": "0.0.0.0",
            "port": 14443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "mhnhh123",
                        "flow": "xtls-rprx-vision"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "tcp",
                "security": "reality",
                "realitySettings": {
                    "show": false,
                    "dest": "8006",
                    "xver": 1,
                    "serverNames": [
                        "dd.mhnhh.com" 
                    ],
                    "privateKey": "9MascsLz6UyX9r9aGXMvd-wxPTgVnY7rCy7L61oZGH0", 
                    "shortIds": [
                        ""
                    ]
                }
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "tag": "block"
        }
    ],
    "policy": {
        "levels": {
            "0": {
                "handshake": 3,
                "connIdle": 180
            }
        }
    }

}
xray.service的路径是/etc/systemd/system/xray.service
内容如下[Unit]
After=network.target

[Service]
User=root
WorkingDirectory=/root
CapabilityBoundingSet=CAP_NET_BIND_SERVICE CAP_NET_RAW
AmbientCapabilities=CAP_NET_BIND_SERVICE CAP_NET_RAW
ExecStart=/root/xray server -c /root/xray.json --log-level info
Restart=on-failure
RestartSec=10
LimitNOFILE=infinity

[Install]
WantedBy=multi-user.target
nginx配置
user nginx;
worker_processes auto;

error_log /var/log/nginx/error.log notice;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    log_format main '[$time_local] $remote_addr "$http_referer" "$http_user_agent"';
    access_log /var/log/nginx/access.log main;

    server {
        listen 80;
        return 301 https://$host$request_uri;
    }

    server {
        listen 127.0.0.1:8006 ssl http2 proxy_protocol;
        set_real_ip_from 127.0.0.1;

        ssl_certificate /etc/ssl/private/fullchain.cer; 
        ssl_certificate_key /etc/ssl/private/private.key; 

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers TLS13_AES_128_GCM_SHA256:TLS13_AES_256_GCM_SHA384:TLS13_CHACHA20_POLY1305_SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305;

        ssl_session_timeout 1d;
        ssl_session_cache shared:SSL:10m;
        ssl_session_tickets off;

        ssl_stapling on;
        ssl_stapling_verify on;
        resolver 1.1.1.1 valid=60s;
        resolver_timeout 2s;

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

        location / {
            resolver 1.1.1.1;
            set $example https://www.lovelive-anime.jp;
            proxy_pass $example;
            proxy_ssl_server_name on;
        }
    }
}
输出systemctl status xray报错，错误如下

root@racknerd-b07d66:~# systemctl status xray
● xray.service
     Loaded: loaded (/etc/systemd/system/xray.service; disabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2023-02-20 23:57:34 EST; 6s ago
    Process: 24258 ExecStart=/root/xray server -c /root/xray.json --log-level info (code=exited, status=2)
   Main PID: 24258 (code=exited, status=2)
        CPU: 3ms

Feb 20 23:57:34 racknerd-b07d66 systemd[1]: xray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 20 23:57:34 racknerd-b07d66 systemd[1]: xray.service: Failed with result 'exit-code'.

**Comment by RPRX** [comment]
检查配置
