### ISSUE TITLE
关于域名和ip的问题，我有一个疑惑

### ISSUE THREAD

**Issue by lyx32** [XTLS/Xray-core#169]
现在情况是这样的。
我是用域名+kcp。
现在我的域名解析好像挂了。（ping不通域名）
但是我ping IP可以通，xshell也能远程到vps。
于是我把V2aryN的域名改成IP。V2rayN不报错了，但是我还是不能访问google。

按照我的理解，我的域名因为域名解析挂了，所以不能得到我的IP。
那我直接给IP，跳过域名解析这一步，理论上应该就可以了，但是不知道为什么还是不行。

**Comment by rprx** [comment]
@lyx32 配置

**Comment by lyx32** [comment]
vps
`{
	"log": {
		"loglevel": "warning"
	}, 
	"inbounds": [
		{
			"listen": "0.0.0.0", 
			"port": 4433, 
			"protocol": "vless", 
			"settings": {
				"clients": [
					{
						"id": "xxxxxxxxx", 
						"level": 0, 
						"email": "a@b.com",
						"flow":"xtls-rprx-direct"
					}
				], 
				"decryption": "none"
			}, 
			"streamSettings": {
				"network": "kcp",                 
				"kcpSettings": {
					"mtu":1350,
					"tti":50,
					"uplinkCapacity": 100,
					"downlinkCapacity": 100,
					"congestion": false,
					"readBufferSize":2,
					"writeBufferSize":2,
					"header":{
						"type": "dtls"
					}
				}
			}
		}
	], 
	"outbounds": [
		{
			"protocol": "freedom", 
			"settings": { }
		}
	]
}`



V2rayN



`{

	"log": {
		"access": "",
		"error": "",
		"loglevel": "warning"
	},
	"inbounds": [{
			"tag": "proxy",
			"port": 1099,
			"listen": "127.0.0.1",
			"protocol": "socks",
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls"
				]
			},
			"settings": {
				"auth": "noauth",
				"udp": true
			}
		},
		{
			"tag": "api",
			"port": 56295,
			"listen": "127.0.0.1",
			"protocol": "dokodemo-door",
			"settings": {
				"udp": false,
				"address": "127.0.0.1"
			}
		}
	],
	"outbounds": [{
			"tag": "proxy",
			"protocol": "vless",
			"settings": {
				"vnext": [{
					"address": "xxxxxxxxx",
					"port": 4433,
					"users": [{
						"id": "xxxxxxxx",
						"alterId": 0,
						"email": "t@t.tt",
						"security": "auto",
						"encryption": "none",
						"flow": ""
					}]
				}]
			},
			"streamSettings": {
				"network": "kcp",
				"kcpSettings": {
					"mtu": 1350,
					"tti": 50,
					"uplinkCapacity": 100,
					"downlinkCapacity": 100,
					"congestion": false,
					"readBufferSize": 2,
					"writeBufferSize": 2,
					"header": {
						"type": "dtls"
					}
				}
			},
			"mux": {
				"enabled": true,
				"concurrency": 8
			}
		},
		{
			"tag": "direct",
			"protocol": "freedom",
			"settings": {}
		},
		{
			"tag": "block",
			"protocol": "blackhole",
			"settings": {
				"response": {
					"type": "http"
				}
			}
		}
	],
	"stats": {},
	"api": {
		"tag": "api",
		"services": [
			"StatsService"
		]
	},
	"dns": {
		"servers": [
			"223.5.5.5",
			"8.8.8.8",
			"1.1.1.1"
		]
	},
	"routing": {
		"domainStrategy": "IPIfNonMatch",
		"rules": [{
				"type": "field",
				"inboundTag": [
					"api"
				],
				"outboundTag": "api"
			},
			{
				"type": "field",
				"outboundTag": "proxy",
				"domain": [
					"geosite:google",
					"geosite:github",
					"geosite:netflix",
					"geosite:steam",
					"geosite:telegram",
					"geosite:tumblr",
					"geosite:speedtest",
					"geosite:bbc",
					"domain:gvt1.com",
					"domain:textnow.com",
					"domain:twitch.tv",
					"domain:wikileaks.org",
					"domain:naver.com"
				]
			},
			{
				"type": "field",
				"outboundTag": "proxy",
				"ip": [
					"91.108.4.0/22",
					"91.108.8.0/22",
					"91.108.12.0/22",
					"91.108.20.0/22",
					"91.108.36.0/23",
					"91.108.38.0/23",
					"91.108.56.0/22",
					"149.154.160.0/20",
					"149.154.164.0/22",
					"149.154.172.0/22",
					"74.125.0.0/16",
					"173.194.0.0/16",
					"172.217.0.0/16",
					"216.58.200.0/24",
					"216.58.220.0/24",
					"91.108.56.116",
					"91.108.56.0/24",
					"109.239.140.0/24",
					"149.154.167.0/24",
					"149.154.175.0/24"
				]
			},
			{
				"type": "field",
				"outboundTag": "direct",
				"domain": [
					"domain:12306.com",
					"domain:51ym.me",
					"domain:52pojie.cn",
					"domain:8686c.com",
					"domain:abercrombie.com",
					"domain:adobesc.com",
					"domain:air-matters.com",
					"domain:air-matters.io",
					"domain:airtable.com",
					"domain:akadns.net",
					"domain:apache.org",
					"domain:api.crisp.chat",
					"domain:api.termius.com",
					"domain:appshike.com",
					"domain:appstore.com",
					"domain:aweme.snssdk.com",
					"domain:bababian.com",
					"domain:battle.net",
					"domain:beatsbydre.com",
					"domain:bet365.com",
					"domain:bilibili.cn",
					"domain:ccgslb.com",
					"domain:ccgslb.net",
					"domain:chunbo.com",
					"domain:chunboimg.com",
					"domain:clashroyaleapp.com",
					"domain:cloudsigma.com",
					"domain:cloudxns.net",
					"domain:cmfu.com",
					"domain:culturedcode.com",
					"domain:dct-cloud.com",
					"domain:didialift.com",
					"domain:douyutv.com",
					"domain:duokan.com",
					"domain:dytt8.net",
					"domain:easou.com",
					"domain:ecitic.net",
					"domain:eclipse.org",
					"domain:eudic.net",
					"domain:ewqcxz.com",
					"domain:fir.im",
					"domain:frdic.com",
					"domain:fresh-ideas.cc",
					"domain:godic.net",
					"domain:goodread.com",
					"domain:haibian.com",
					"domain:hdslb.net",
					"domain:hollisterco.com",
					"domain:hongxiu.com",
					"domain:hxcdn.net",
					"domain:images.unsplash.com",
					"domain:img4me.com",
					"domain:ipify.org",
					"domain:ixdzs.com",
					"domain:jd.hk",
					"domain:jianshuapi.com",
					"domain:jomodns.com",
					"domain:jsboxbbs.com",
					"domain:knewone.com",
					"domain:kuaidi100.com",
					"domain:lemicp.com",
					"domain:letvcloud.com",
					"domain:lizhi.io",
					"domain:localizecdn.com",
					"domain:lucifr.com",
					"domain:luoo.net",
					"domain:mai.tn",
					"domain:maven.org",
					"domain:miwifi.com",
					"domain:moji.com",
					"domain:moke.com",
					"domain:mtalk.google.com",
					"domain:mxhichina.com",
					"domain:myqcloud.com",
					"domain:myunlu.com",
					"domain:netease.com",
					"domain:nfoservers.com",
					"domain:nssurge.com",
					"domain:nuomi.com",
					"domain:ourdvs.com",
					"domain:overcast.fm",
					"domain:paypal.com",
					"domain:paypalobjects.com",
					"domain:pgyer.com",
					"domain:qdaily.com",
					"domain:qdmm.com",
					"domain:qin.io",
					"domain:qingmang.me",
					"domain:qingmang.mobi",
					"domain:qqurl.com",
					"domain:rarbg.to",
					"domain:rrmj.tv",
					"domain:ruguoapp.com",
					"domain:sm.ms",
					"domain:snwx.com",
					"domain:soku.com",
					"domain:startssl.com",
					"domain:store.steampowered.com",
					"domain:symcd.com",
					"domain:teamviewer.com",
					"domain:tmzvps.com",
					"domain:trello.com",
					"domain:trellocdn.com",
					"domain:ttmeiju.com",
					"domain:udache.com",
					"domain:uxengine.net",
					"domain:weather.bjango.com",
					"domain:weather.com",
					"domain:webqxs.com",
					"domain:weico.cc",
					"domain:wenku8.net",
					"domain:werewolf.53site.com",
					"domain:windowsupdate.com",
					"domain:wkcdn.com",
					"domain:workflowy.com",
					"domain:xdrig.com",
					"domain:xiaojukeji.com",
					"domain:xiaomi.net",
					"domain:xiaomicp.com",
					"domain:ximalaya.com",
					"domain:xitek.com",
					"domain:xmcdn.com",
					"domain:xslb.net",
					"domain:xteko.com",
					"domain:yach.me",
					"domain:yixia.com",
					"domain:yunjiasu-cdn.net",
					"domain:zealer.com",
					"domain:zgslb.net",
					"domain:zimuzu.tv",
					"domain:zmz002.com",
					"domain:samsungdm.com"
				]
			},
			{
				"type": "field",
				"outboundTag": "block",
				"domain": [
					"geosite:category-ads-all"
				]
			},
			{
				"type": "field",
				"outboundTag": "direct",
				"ip": [
					"geoip:private"
				]
			},
			{
				"type": "field",
				"outboundTag": "direct",
				"ip": [
					"geoip:cn"
				]
			},
			{
				"type": "field",
				"outboundTag": "direct",
				"domain": [
					"geosite:cn"
				]
			}
		]
	}
}`

**Comment by lyx32** [comment]
不需要域名，IP，UUID吗？
不要这个恐怕不好测试吧。

**Comment by rprx** [comment]
删掉服务端的 flow 即可

**Comment by lyx32** [comment]
还真是。我这个配置是从tcp+xtls里面复制过来的。
唉，好尴尬。
