### ISSUE TITLE
Proxy Protocol 某些情况下会有IP识别问题

### ISSUE THREAD

**Issue by himgoods** [XTLS/Xray-core#1690]
RT，使用nginx stream模块转发，
转发链为：nginx A  --->  nginx B  --->  Xray-core

在机器有IPv6的时候Proxy Protocol的原始地址会变为IPv6兼容模式(IPv4-Mapped IPv6 Address)，实际显示为：   ::ffff:123.123.123.123
所有 IPv4 地址都会以 "::ffff:" 为前缀，这时把流量转发到XrayR会出现以下报错：
 proxyproto: invalid address

附nginx配置

NGINX SERVER A
> stream{
> set_real_ip_from 0.0.0.0/0;
> set_real_ip_from ::/0;
> server{
> listen 123;
> listen [::]:123;
> listen 123 udp;
> listen [::]:123 udp;
> proxy_protocol on;
> proxy_pass 123.123.123.123:12345
> }
> }

NGINX SERVER B
> stream{
> set_real_ip_from 0.0.0.0/0;
> set_real_ip_from ::/0;
> server{
> listen 12345 proxy_protocol;
> listen [::]:12345 proxy_protocol;
> listen 123 udp;
> listen [::]:123 udp;
> proxy_protocol on;
> proxy_pass 127.0.0.1:10086 #Xray-core
> }
> }

**Comment by RPRX** [comment]
非 Xray 的问题，接收 PROXY protocol 用的是这个库：https://github.com/pires/go-proxyproto ，麻烦发到它的 issue 区。
