### ISSUE TITLE
[求教]有没有方法降低vmess协议的内存占用？

### ISSUE THREAD

**Issue by moranno** [XTLS/Xray-core#1692]
一次性需要载入很多用户，xray进程内存占用超过1G，求教可以降低vmess内存占用的方法？

**Comment by RPRX** [comment]
换协议

**Comment by moranno** [comment]
> 换协议

我想问的是有没有可能从代码/配置/缓存/链接保持等等方便来优化内存占用呢？

目前vmess比较稳，其他协议被墙的快，等reallity被大量客户端支持前还暂时不想换协议。

**Comment by RPRX** [comment]
> 我想问的是有没有可能从代码/配置/缓存/链接保持等等方便来优化内存占用呢？

或许有，不开机场，没研究过，且对优化 VMess 协议不感兴趣，~~可能把 VMess 非 AEAD 的代码删了就行~~

> 目前vmess比较稳，其他协议被墙的快

你指的是 TLS 类封端口吧，目前的经验是纯 XTLS Vision 能有效防止被封（对比得出），未知流量类一般直接封整个 IP，good luck

> 等reallity被大量客户端支持前还暂时不想换协议

首先 REALITY 还没 release，其次我说“换协议”的意思是，VMess 协议的设计，用户一多就是会这样，换协议是根本解决办法

**Comment by Fangliding** [comment]
要性能可以玩singbox
一次载入了多少多用户 吃一个G有点厉害
机场的后端不是这样罢()

**Comment by moranno** [comment]
> 你指的是 TLS 类封端口吧，目前的经验是纯 XTLS Vision 能有效防止被封（对比得出），未知流量类一般直接封整个 IP，good luck
如果你有兴趣可以加我tg: @missmoranno 和你分享在十万用户量级上的防墙经验。

**Comment by moranno** [comment]
> ~可能把 VMess 非 AEAD 的代码删了就行~

能否指个方向，非 AEAD 的相关代码在哪写文件下？我尝试下删除打个包试试。
