### ISSUE TITLE
REALITY: add multiple condition

### ISSUE THREAD

**Issue by hiddify** [XTLS/Xray-core#1701]
The reality seems great. However, adding a list instead of a single condition makes it more powerful.
For example, if a client with tls1.2 wants to connect to our servers obviously it is the GTW bot. So no request should be processed by xray and just forward to decoy site.

Additionally,  if we want to use FakeTLS protocols like MTProxy it can be useful.

I suggest to change the reality settings to support a list entries instead of  a single entry.

Example:

```json
"realitySettings": {
    "serverNames": ["reality.com"],
     "minClientVer" : "1.7.5", 
     "maxClientVer" : "1.8.0",
     "private_key": "",
      ...
     "fallback":[
           { "minTlsVer" : "1.3", "serverNames" : [ "google.com"], "dest": "127.0.0.1:1000", "xver": 0}, //for faketls protocol
           { "serverNames" : ["google.com"], "dest": "google.com:443", "xver": 0}, // if tls version is less than 1.3 for sni google.com 
           { "dest" : "@decoy_or_xtls_inbound", "xver": 2} // similar to fallback, means all others go to decoy_or_xtls_inbound without ssl termination
     ]
}
```

related to https://github.com/XTLS/Xray-core/issues/1486

**Comment by RPRX** [comment]
“暂不支持”的意思是，基于现在的模式，收了完整的 Client Hello 且服务端还没发数据时还是能分流的，以后要出的“预先构建模式”需要一次 Read 到完整的 Client Hello，也是能分流，所以多 dest 支持可能会在以后的版本中加入，但默认 dest 的选择是个小问题

**Comment by hiddify** [comment]
Great thank you :-)
I love your core and have prepared an always free UI for xray-core https://github.com/hiddify/hiddify-config/wiki/Home-En

I try to provide a simple way for all users so i am sure that the future release can help many users ;)

**Comment by RPRX** [comment]
REALITY 服务端的目标是对外表现出纯粹的端口转发特性，是这类协议的最优解，支持 SNI 分流是会更方便，但也会增加一些风险

我没有详细研究过你提到的 FakeTLS 或它的实现，若它有把未通过认证的流量转发出去的功能，其实你不用等 REALITY 支持 SNI 分流，完全可以为这类协议用同一个域名，前后串在一起，若最终指向的 IP:Port 有多个网站，也可以用不同的域名

其实无论是 SNI 分流还是上述方案，都增加了端口被封的风险，只是我认为上述方案增加的风险更少，只剩短板效应
