### ISSUE TITLE
关于WebSocketObject 中"headers"

### ISSUE THREAD

**Issue by shuiliu11** [XTLS/Xray-core#1704]
关于WebSocketObject 中
"headers": {
    "Host": "xray.com"
  }
这一项, 在自定义客户端文件中这样写不能正常代理.如果留空,代理正常,这是为什么.
[Warning] [155281010] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxx.com/path): 403 Forbidden > websocket: bad handshake] > common/retry: all retry attempts failed

以下是配置文档的说明
headers: map {string: string}
自定义 HTTP 头，一个键值对，每个键表示一个 HTTP 头的名称，对应的值是字符串。
默认值为空。

**Comment by cross-hello** [comment]
Different Host name could get different effect.
Some will speed up internet, and some will limit speed to zero.

**Comment by cross-hello** [comment]
But the confused thing is hostname in client hello always be server name.

So... Where could see web socket name?

Feb 24, 2023 17:59:33 Nanyu ***@***.***>:
