### ISSUE TITLE
此网站无法提供安全连接www.google.com 使用了不受支持的协议。 ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### ISSUE THREAD

**Issue by heygo1345678** [XTLS/Xray-core#1712]
已修复，请测试 https://github.com/XTLS/Xray-core/commit/bdbca3380b0fc51e7c41766c419ff19d4a8c1f78

_Originally posted by @RPRX in https://github.com/XTLS/Xray-core/issues/1697#issuecomment-1445290751_
 
测试了 accepting PROXY protocol 可以获取访客真实IP了，但是不能访问网站了，只能连接tg,
chrome浏览器访问境外网站提示：
此网站无法提供安全连接www.bbc.com 发送的响应无效。
尝试运行 Windows 网络诊断。
ERR_SSL_PROTOCOL_ERROR

此网站无法提供安全连接www.google.com 使用了不受支持的协议。
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

客户端也更新到这个版本问题依旧

**Comment by RPRX** [comment]
感谢反馈，等下修复

**Comment by RPRX** [comment]
已修复，请测试 https://github.com/XTLS/Xray-core/commit/c38179a67feb993d63adc99cc7f4918e4d1d5c57

**Comment by heygo1345678** [comment]
> 已修复，请测试 [c38179a](https://github.com/XTLS/Xray-core/commit/c38179a67feb993d63adc99cc7f4918e4d1d5c57)

好的，已测试，访客IP和浏览器上网无问题了，多谢大佬
