### ISSUE TITLE
The Reality protocol does not support CDN, so what can we do to use Reality in Iran where we need to use CDN to obtain good speed?

### ISSUE THREAD

**Issue by us254** [XTLS/Xray-core#1717]
The Reality protocol is not compatible with CDN, which can result in slower speeds when used in locations such as Iran where CDN is necessary for optimal performance. Given this limitation, what alternative options or solutions can be implemented to ensure that Reality can still be used effectively in Iran without sacrificing speed?

**Comment by wy580477** [comment]
You should try [hysteria](https://github.com/apernet/hysteria), it's optimized for lossy and unstable connections.

**Comment by computerscot** [comment]
There are several reports of Iran deliberately throttling connections to proxy servers.

* "xray/vless/xtls/trojan all speed limited as of today" https://github.com/net4people/bbs/issues/185
* "Iran/China is probably using deep learning to detect VPN traffic" https://github.com/net4people/bbs/issues/184
* "Iran limiting v2ray and shadowsocks private servers" https://github.com/net4people/bbs/issues/166

It could be that Iran's censors view a Hetzner VPS as likely to be proxy server, regardless of the protocol used. 

Or it could be network metrics that make it look like a proxy server. If all your traffic goes to one IP address, and you are the only person sending traffic to that IP address, it looks suspiciously like a proxy server.

So you could try using a non-obvious VPS provider, and you could try only using your proxy server intermittently, but there are no guarantees this would work.

**Comment by maliohammad** [comment]
> > You should try [hysteria](https://github.com/apernet/hysteria), it's optimized for lossy and unstable connections.
> 
> Are there any options besides employing the hysteria protocol? Specifically, how do individuals in China effectively utilize the reality protocol to circumvent the GFW? Could the sluggish line quality be attributed to the German origin of my virtual private server or is it due to the dissimilarities between the Iranian and Chinese firewalls and their impact on the TCP protocol?

What ISP are you using? For me hysteria didn't work at all (irancell)
