### ISSUE TITLE
服务端升级Vision padding upgrade版本后，客户端使用V2rayNG+juiceSSH连接时报错

### ISSUE THREAD

**Issue by wyx2685** [XTLS/Xray-core#1723]
服务端更新到#1646 版本后，安卓机使用旧客户端V2rayNG代理SSH连接时认证失败报错，packet len too high
回退服务端版本到[55dc26f](https://github.com/XTLS/Xray-core/commit/55dc26f22840c83045e6f34221533aa3cbe977a2)后可以正常连接。
使用协议vless+vision+tls

报错信息
![Screenshot_2023-03-01-08-06-13-954_com sonelli juicessh](https://user-images.githubusercontent.com/24352157/222011883-764902de-103a-4dd3-8955-da4f8b559860.jpg)

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/issues/1722#issuecomment-1449882532

**Comment by wyx2685** [comment]
> 感谢测试 麻烦试一下 https://github.com/XTLS/Xray-core/actions/runs/4304326723

客户端是否需要升级？
只升服务端的情况下表现一致

**Comment by yuhan6665** [comment]
都升级一下看看 如果不行可能是另一个问题 麻烦打一下两端日志

**Comment by wyx2685** [comment]
服务端新版本 vision
客户端新版本 手机连wifi使用路由器透明代理vision
没有异常可以连接ssh

 v2rayNG没法更新，报错只发生在使用v2rayNG的情况
(其实是催更？)

**Comment by yuhan6665** [comment]
@wyx2685 那先用这个偷跑版本测试吧 :) https://github.com/yuhan6665/v2rayNG/releases/download/aar-test/v2rayNG_1.7.38_null.apk

**Comment by wyx2685** [comment]
使用偷跑版后连接正常了

**Comment by yuhan6665** [comment]
谢谢 先关了
