### ISSUE TITLE
新的padding方式后，curl http code 返回000

### ISSUE THREAD

**Issue by xianren78** [XTLS/Xray-core#1724]
测试命令
      curl -s -o /dev/null -w "%{http_code}" https://www.google.com

原来的padding正常返回301或者200等等，现在的返回000，表现并不一致，不确定这是bug还是feature...

**Comment by yuhan6665** [comment]
可能是 bug 检查一下两端是否都是 [7b54255](https://github.com/XTLS/Xray-core/commit/7b54255cc1b3ce4c275b713e6289d0cd45ec50ea) 如是麻烦打一下两端日志

**Comment by xianren78** [comment]
> 可能是 bug 检查一下两端是否都是 [7b54255](https://github.com/XTLS/Xray-core/commit/7b54255cc1b3ce4c275b713e6289d0cd45ec50ea) 如是麻烦打一下两端日志

客户端目前是clash meta ，等我再测试一下xray做客户端。

**Comment by xianren78** [comment]
补充一下，curl使用了http代理，似乎和那个tg无法使用http代理的问题一致。

**Comment by yuhan6665** [comment]
修好了 感谢大家帮我抓虫 https://github.com/XTLS/Xray-core/actions/runs/4324509449
