### ISSUE TITLE
REALITY服务器没有正常工作，日志如下，请问是什么原因？

### ISSUE THREAD

**Issue by tianlichunhong** [XTLS/Xray-core#1726]
服务器日志：
REALITY remoteAddr: XXX.XXX.XXX.XXX:38477  hs.c.AuthKey: [XXXXX]
REALITY remoteAddr: XXX.XXX.XXX.XXX:38477  hs.c.ClientVer: [1 7 5]
REALITY remoteAddr: XXX.XXX.XXX.XXX:38477  hs.c.ClientTime: 2023-03-02 05:22:27 +0000 UTC
REALITY remoteAddr: XXX.XXX.XXX.XXX:38477  hs.c.ClientShortId: [XXXXX]
REALITY remoteAddr: XXX.XXX.XXX.XXX:38477  hs.c.conn == conn: true
REALITY remoteAddr: XXX.XXX.XXX.XXX:38477  len(s2cSaved): 4832     Server Hello: 127
REALITY remoteAddr: XXX.XXX.XXX.XXX:38477  len(s2cSaved): 4705     Change Cipher Spec: 6
REALITY remoteAddr: XXX.XXX.XXX.XXX:38477  len(s2cSaved): 4699     Encrypted Extensions: 41
REALITY remoteAddr: XXX.XXX.XXX.XXX:38477  len(s2cSaved): 4658     Certificate: 4737
REALITY remoteAddr: XXX.XXX.XXX.XXX:38477  len(s2cSaved): 5081     Certificate: 4737
REALITY remoteAddr: XXX.XXX.XXX.XXX:38477  len(s2cSaved): 344      Certificate Verify: 286
REALITY remoteAddr: XXX.XXX.XXX.XXX:38477  len(s2cSaved): 58       Finished: 58
REALITY remoteAddr: XXX.XXX.XXX.XXX:38477  hs.handshake() err: write tcp 10.0.1.152:2302->XXX.XXX.XXX.XXX:38477: write: connection reset by peer
REALITY remoteAddr: XXX.XXX.XXX.XXX:38477  handled: false
REALITY remoteAddr: XXX.XXX.XXX.XXX:38478
REALITY remoteAddr: XXX.XXX.XXX.XXX:38478  hs.clientHello.sessionId: [xxx]

在客户端看到的也是connection reset by peer。这是什么原因？被墙拦截了？至少客户端发信息是到了服务器。可惜客户端收不到。

**Comment by RPRX** [comment]
这是很明显的纯 SNI 阻断，换个目标域名就行了
