### ISSUE TITLE
使用fallback，xver = 1，nginx开启proxy_protocol也无法正常连接

### ISSUE THREAD

**Issue by Qingshui001** [XTLS/Xray-core#1729]
利用fallback，从port：443进入，使用的是vless+xtls，分别回落到8082是ws，8083是trojan，从8083回落到8080网站。如果xver = 0的话，就正常，xver = 1 的话，即便nginx加上proxy protocol也无法使用，网页会显示404notfound。配置如下

nginx配置

>server {
  listen 80;
  server_name xyz.abc;
  rewrite ^(.*)$ https://${server_name}$1 permanent; 
}
server {
  listen 8080 proxy_protocol;
  listen [::]:8080 proxy_protocol;
  server_name xyz.abc;
  access_log /data/wwwlogs/access.log combined;
  index index.html index.htm index.php;
  root /data/wwwroot/xyz.abc;
set_real_ip_from 127.0.0.1;
real_ip_header proxy_protocol;
proxy_set_header X-Real-IP $proxy_protocol_addr; 
proxy_set_header X-Forwarded-For $proxy_protocol_addr ;
  add_header Content-Security-Policy "upgrade-insecure-requests";

xray配置

>"inbounds": [
        {
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "",
                        "flow": "xtls-rprx-direct",
                        "level": 0,
                        "email": ""
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": 8083, 
                        "xver": 1
                    },
                    {
                        "path": "/path", 
                        "dest": 8082,
                        "xver": 1
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "alpn": [
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "/pem", 
                            "keyFile": "/key" 
                        }
                    ]
                }
            }
        },
        {
            "port": 8083,
            "listen": "127.0.0.1",
            "protocol": "trojan",
            "settings": {
                "clients": [
                    {
                        "password": "",
                        "level": 0,
                        "email": ""
                    }
                ],
                "fallbacks": [
                    {
                        "dest": 8080
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "none",
				 "tcpSettings": {
                    "acceptProxyProtocol": true
                }
            }
        },
        {
            "port": 8082,
            "listen": "127.0.0.1",
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "",
                        "level": 0,
                        "email": ""
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "ws",
                "security": "none",
                "wsSettings": {
                    "path": "/path" 
                }
            },
			 "sniffing": {
              "enabled": true,
              "destOverride": [
                "http",
                "tls"
               ]
            }
        }
    ]

**Comment by chika0801** [comment]
xver 1,ws 那段参考
https://github.com/chika0801/Xray-examples/blob/e1e9ecc74f1b579642b5d120fd8408761a7f654f/VLESS-TCP-TLS%2BVMess-Websocket-TLS%2BTrojan-TCP-TLS/config_server.json#L85

加 "acceptProxyProtocol": true

**Comment by Qingshui001** [comment]
> xver 1,ws 那段参考 https://github.com/chika0801/Xray-examples/blob/e1e9ecc74f1b579642b5d120fd8408761a7f654f/VLESS-TCP-TLS%2BVMess-Websocket-TLS%2BTrojan-TCP-TLS/config_server.json#L85
> 
> 加 "acceptProxyProtocol": true
加上之后，网页显示未发送任何数据。
ERR_EMPTY_RESPONSE
好像还是proxy protocol格式不对，挠头

**Comment by RPRX** [comment]
你没给 trojan 处 fallbacks 加 xver

**Comment by Qingshui001** [comment]
> 你没给 trojan 处 fallbacks 加 xver

感谢，我直接从https://github.com/XTLS/Xray-examples/blob/main/VLESS-TCP-XTLS-WHATEVER/config_server.json
模板复制过来的，不知怎么把这个搞没了。复制需谨慎啊。
