### ISSUE TITLE
Reality does not verify certificates of its destination

### ISSUE THREAD

**Issue by testcaoy7** [XTLS/Xray-core#1734]
Actually, I consider this is a "feature".
We can use a self-signed CA to issue any certificates to Reality.
And Reality does not care if the certificate is self-signed. It will not verify it.

Config:
```
    "inbounds": [
        {
            "tag": "vless-in",
            "listen": "0.0.0.0",
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "e7608361-3f0b-4d52-bf9f-bd9dea5a2a6b",
                        "flow": "xtls-rprx-vision"
                    }
                ],
		"decryption": "none"
            },
            "streamSettings": {
                "network": "tcp",
                "security": "reality",
                "realitySettings": {
                    "show": false,
                    "privateKey": "<Server_X25519_Private_Key>",
                    "shortIds": ["<Server_Short_ID>"],
                    "dest": "127.0.0.1:444",
                    "serverNames": ["www.gov.cn"]
                }
            }
        },
        {
            "tag": "dummy-ca",
            "listen": "127.0.0.1",
            "port": 444,
            "protocol": "http",
            "settings": {"allowTransparent": true},
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "rejectUnknownSni": false,
                    "alpn": ["http/1.1"],
					"minVersion": "1.3",
                    "certificates": [
                        {
                            "usage": "issue",
                            "oneTimeLoading": true,
                            "certificateFile": "fakeCA.cer",
                            "keyFile": "fakeCA.key"
                        }
                    ]
                }
            }
        }
    ]
```

Just set a dummy HTTP inbound, with TLS configuration set to use a CA certificate. And it will sign your Reality with any SNI you set, in the "serverNames" array.

**Comment by RPRX** [comment]
我强调过，[REALITY 是全程真实的 TLS，它并不需要，实际也没有“偷证书”](https://github.com/XTLS/Xray-core/issues/1697#issuecomment-1441246622)，因为 TLSv1.3 把证书给加密了，中间人看不到证书

[Example](https://github.com/XTLS/REALITY) 也有说明：REALITY 客户端应当收到由“**临时认证密钥**”签发的“**临时可信证书**”，正常不会收到目标网站的真证书

目标网站是自己选的，你得保证目标网站的证书有效，就像允许哪些 serverNames 也由服务端决定一样，想的话你随便填都行

**Comment by RPRX** [comment]
还有，**只要 `dest` 有默认证书，你就可以填任何 `serverNames`**，查看 https://github.com/XTLS/Xray-core/issues/1681#issuecomment-1436655742 ，并不是自签 CA 的功劳

其实我本地早就根据近期 issue 更新了 example，包括这部分内容，只是还没放出来，~~我讨厌单独花时间解释~~

**Comment by cross-hello** [comment]
![image](https://user-images.githubusercontent.com/42733664/222670087-682b3d1d-3438-423f-8a29-115be8fef974.png)
Indeed, now you could spend time to talk with assembly.

**Comment by RPRX** [comment]
~~你看，现在又变成 1023 了~~（干得漂亮！）

**Comment by RPRX** [comment]
> 并不是自签 CA 的功劳

这个更准确的表述为，自签 CA 并没有起到特别的作用，反而遇到主动探测的话会露馅得很彻底，还不如返回 `dest` 默认的证书。
