### ISSUE TITLE
Multiple IP addresses

### ISSUE THREAD

**Issue by A5DkjGQUZx** [XTLS/Xray-core#1735]
Hi,
I have a server with N interfaces and M IP addresses.
How can I limit an outgoing or incoming instance to bind to one or more IP addresses?
For the Inbound we have `listen` object but can I use an array with it? But on the clients side and for the outbound there is no such option to select the IP address and/or interface for outgoing packets...
Comments are appreciated :)
Thanks!

**Comment by IRN-Kawakaze** [comment]
I don't know of any way for inbound to bind to multiple IPs.

For outbound, you can use "sendThrough" to bind to an IP, or use "StreamSettings->sockopt->interface" to bind to an interface.

**Comment by xqzr** [comment]
`vnext` is array

**Comment by firefoxOnFire** [comment]
> I don't know of any way for inbound to bind to multiple IPs.
> 
> For outbound, you can use "sendThrough" to bind to an IP, or use "StreamSettings->sockopt->interface" to bind to an interface.

`or use "StreamSettings->sockopt->interface" to bind to an interface` how to do that? can you send one example??

**Comment by IRN-Kawakaze** [comment]
> > I don't know of any way for inbound to bind to multiple IPs.
> > For outbound, you can use "sendThrough" to bind to an IP, or use "StreamSettings->sockopt->interface" to bind to an interface.
> 
> `or use "StreamSettings->sockopt->interface" to bind to an interface` how to do that? can you send one example??

```
    "outbounds": [
        {
            "tag": "freedom-0",
            "protocol": "freedom",
            "settings": {},
            "streamSettings": {
                "sockopt": {
                    "interface": "eth0"
                }
            }
        },
        {
            "tag": "freedom-1",
            "protocol": "freedom",
            "settings": {},
            "streamSettings": {
                "sockopt": {
                    "interface": "eth1"
                }
            }
        }
    ]
```

https://xtls.github.io/Xray-docs-next/config/transport.html#sockoptobject

**Comment by firefoxOnFire** [comment]
> > > I don't know of any way for inbound to bind to multiple IPs.
> > > For outbound, you can use "sendThrough" to bind to an IP, or use "StreamSettings->sockopt->interface" to bind to an interface.
> > 
> > 
> > `or use "StreamSettings->sockopt->interface" to bind to an interface` how to do that? can you send one example??
> 
> ```
>     "outbounds": [
>         {
>             "tag": "freedom-0",
>             "protocol": "freedom",
>             "settings": {},
>             "streamSettings": {
>                 "sockopt": {
>                     "interface": "eth0"
>                 }
>             }
>         },
>         {
>             "tag": "freedom-1",
>             "protocol": "freedom",
>             "settings": {},
>             "streamSettings": {
>                 "sockopt": {
>                     "interface": "eth1"
>                 }
>             }
>         }
>     ]
> ```
> 
> Refer to: https://xtls.github.io/Xray-docs-next/config/outbound.html#outboundobject https://xtls.github.io/Xray-docs-next/config/transport.html#streamsettingsobject https://xtls.github.io/Xray-docs-next/config/transport.html#sockoptobject

Thanks, this worked. All the time I was following v2ray documentation. That's why i never found these settings. Silly me
