### ISSUE TITLE
怎么去掉敏感http header

### ISSUE THREAD

**Issue by 6Glory9** [XTLS/Xray-core#1737]
1. VLESS over TCP with XTLS 配置时
2. 最终服务端会显示这两个http header,暴露出真实的ip
- forwarded
- x-forwarded-for

**Comment by chika0801** [comment]
发下服务端xray配置

**Comment by 6Glory9** [comment]
{
	"log": {
		"loglevel": "warning"
	},
	"inbounds": [{
		"listen": "0.0.0.0",
		"port": 443, //监听的端口
		"protocol": "vless",
		"settings": {
			"clients": [{
				"id": "id", //此处为你的UUID
				"level": 0,
				"email": "v2rayssr@v2rayssr.com",
				"flow": "xtls-rprx-direct"
			}],
			"decryption": "none",
			"fallbacks": [{
				"dest": xx //默认回落端口
			}]
		},
		"streamSettings": {
			"network": "tcp",
			"security": "xtls",
			"xtlsSettings": {
				"serverName": "www", //你的域名
				"alpn": [
					"http/1.1"
				],
				"certificates": [{
					"certificateFile": "/etc/nginx/cert/xxx.cf.pem",
					"keyFile": "/etc/nginx/cert/xxx.cf.key"
				}]
			}
		}
	}],
	"outbounds": [{
		"protocol": "freedom"
	}]

}

**Comment by 6Glory9** [comment]
> 发下服务端xray配置

已经发了

**Comment by chika0801** [comment]
看了配置，你Xray监听443，xray是能得到访问者真实IP。

> 最终服务端会显示这两个http header,暴露出真实的ip
我没明白你这句话问的是什么意思？你再说清楚些了。

**Comment by picklefan** [comment]
~~估计用的机场,还不想让机场得到他的ip~~

**Comment by 6Glory9** [comment]
> 看了配置，你Xray监听443，xray是能得到访问者真实IP。
> 
> > 最终服务端会显示这两个http header,暴露出真实的ip
> 
> 我没明白你这句话问的是什么意思？你再说清楚些了。

我的目标的地址是 google.com.
google.com服务器获取 http请求，能获取这个两个http header
- forwarded proto=http;host=www.google.com;for="read ip:55786"
- x-forwarded-for real ip,proxy id
这样暴露 real ip，就达不到翻墙目地。

**Comment by chika0801** [comment]
我不懂  forwarded 这几个值，但是一般情况是谷歌网站得到的是vps的ip，从你发的xray配置来看。

不知道你是怎么测试的？方法能讲下吗？

**Comment by 6Glory9** [comment]
> 我不懂 forwarded 这几个值，但是一般情况是谷歌网站得到的是vps的ip，从你发的xray配置来看。
> 
> 不知道你是怎么测试的？方法能讲下吗？

我自己搭建一个服务器，通过vps访问，把请求的http header 全部打印出来。就能看到了。
他的real id 确实是vps id，但http header 还附加 forwarded 和 x-forwarded-for 这两个http header 间接暴露 real ip

**Comment by 6Glory9** [comment]
> 我不懂 forwarded 这几个值，但是一般情况是谷歌网站得到的是vps的ip，从你发的xray配置来看。
> 
> 不知道你是怎么测试的？方法能讲下吗？

nginx 有类似方式，把 forwarded 和 x-forwarded-for 去掉或者重新定义了。

**Comment by chika0801** [comment]
你的意思是你搭了一个网站，你连上代理用的VPS去访问自己的网站，看到的forwarded 和 x-forwarded-for值里有你自己的IP。

我不懂这块，帮不上你。

**Comment by 6Glory9** [comment]
@yuhan6665 @RPRX @nekohasekai @dependabot[bot]

**Comment by RPRX** [comment]
你浏览器访问的网站是 HTTPS，外层是 TLS，Xray-core 没有、且很难修改其中 HTTP 的 header

**Comment by yichya** [comment]
你的服务端和客户端搭建的方式没有说清楚，看到的具体是哪个 ip 也没说清楚。我按最简单的方式（除了 xray 之外中间没有插任何 nginx 之类的）自己试了一下，没看见这两个 header。

```
> env http_proxy=socks5://192.168.123.2:1080 curl http://127.0.0.1:8000 --verbose
* Uses proxy env variable http_proxy == 'socks5://192.168.123.2:1080'
*   Trying 192.168.123.2:1080...
* SOCKS5 connect to IPv4 127.0.0.1:8000 (locally resolved)
* SOCKS5 request granted.
* Connected to (nil) (192.168.123.2) port 1080 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:8000
> User-Agent: curl/7.86.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Server: BaseHTTP/0.6 Python/3.10.9
< Date: Sat, 04 Mar 2023 04:01:19 GMT
< Content-type: text/html
<
* Closing connection 0
<html><head><title>https://pythonbasics.org</title></head><p>Request: [('Host', '127.0.0.1:8000'), ('User-Agent', 'curl/7.86.0'), ('Accept', '*/*')]</p><body><p>This is an example web server.</p></body></html>⏎
```

**Comment by 6Glory9** [comment]
> 你浏览器访问的网站是 HTTPS，外层是 TLS，Xray-core 没有、且很难修改其中 HTTP 的 header

https://www.cnblogs.com/leijiangtao/p/4355660.html
你看看这个。

**Comment by 6Glory9** [comment]
> > 你浏览器访问的网站是 HTTPS，外层是 TLS，Xray-core 没有、且很难修改其中 HTTP 的 header
> 
> https://www.cnblogs.com/leijiangtao/p/4355660.html 你看看这个。

![image](https://user-images.githubusercontent.com/6240229/222875201-fdc26037-a129-43de-b9c0-87fb7349207a.png)

**Comment by yichya** [comment]
（我有一种想法，这哥可能是在客户端前面放了一个 nginx 做反代

**Comment by 6Glory9** [comment]
> （我有一种想法，这哥可能是在客户端前面放了一个 nginx 做反代

我的客服端只有一个v2rayN

**Comment by RPRX** [comment]
浏览器到 google.com 是 TLS 加密，能在其中加 header 的只有浏览器端和 google.com

而你正常用浏览器不会这么加，google.com 只知道你服务器的 IP

所以你的本地 IP 被加到 header 里，只可能是本地的锅，~~有可能是浏览器插件~~

**Comment by yichya** [comment]
> 我的客服端只有一个v2rayN

那我们捋一下。比如说

* 你跑 v2rayN 的机器叫 A，IP 是 a
* 你的 VPS 叫 B，IP 是 b
* 你打算打出来 HTTP Request Header 的机器叫 C，IP 是 c

那按照你的描述，有几个细节需要确认

1. A 上给 v2rayN 发起请求的是什么，直接是浏览器还是经过了其他的软件（比如 nginx 或者什么去广告代理之类的），这一步发出来的 HTTP Request 有没有 x-forwarded-for
2. C 看到的是 a 还是 b
3. B 前面有没有 CDN 或者其他的中转设施

**Comment by 6Glory9** [comment]
> > 我的客服端只有一个v2rayN
> 
> 那我们捋一下。比如说
> 
> * 你跑 v2rayN 的机器叫 A，IP 是 a
> * 你的 VPS 叫 B，IP 是 b
> * 你打算打出来 HTTP Request Header 的机器叫 C，IP 是 c
> 
> 那按照你的描述，有几个细节需要确认
> 
> 1. A 上给 v2rayN 发起请求的是什么，直接是浏览器还是经过了其他的软件（比如 nginx 或者什么去广告代理之类的），这一步发出来的 HTTP Request 有没有 x-forwarded-for
> 2. C 看到的是 a 还是 b
> 3. B 前面有没有 CDN 或者其他的中转设施

我找到原因了。

**Comment by chika0801** [comment]
说说原因了，让我们也知道下

**Comment by 6Glory9** [comment]
> 说说原因了，让我们也知道下

浏览器插件，自己带的。换了一个浏览器就解决了。

**Comment by SakuraSakuraSakuraChan** [comment]
能否说下是哪个插件

**Comment by 6Glory9** [comment]
> 能否说下是哪个插件

mode header
