### ISSUE TITLE
能否给route的banlace加一个健康检查

### ISSUE THREAD

**Issue by iceliuhacker** [XTLS/Xray-core#1751]
有了健康检查，就不会担心用户请求到故障的服务端。

**Comment by KoriIku** [comment]
Please refer to the introduction about the failover in the following article, I think leaf has already implemented the functionality you described.

https://tachyondevel.medium.com/%E7%AE%80%E5%8D%95%E4%BB%8B%E7%BB%8D-leaf-%E7%9A%84%E8%AF%B7%E6%B1%82%E5%88%86%E5%8F%91%E6%9C%BA%E5%88%B6-cecde244afb
