### ISSUE TITLE
最新源代码golang 1.19编译失败

### ISSUE THREAD

**Issue by Gzxhwq** [XTLS/Xray-core#1755]
由于openwrt主线仍然停留在1.19，所以希望能修一下

https://github.com/XTLS/Xray-core/commit/79c0b0a0f2c82a67e353be41c2a85dcb9cbbfe59

../pkg/mod/github.com/xtls/reality@v0.0.0-20230308170557-1c3141866eb7/handshake_server_tls13.go:101:23: undefined: bytes.Clone

**Comment by wyx2685** [comment]
@Gzxhwq 已经要求1.19.6以上，go可以官网自己下载升级

**Comment by Gzxhwq** [comment]
已经是1.19.6了

https://github.com/coolsnowwolf/packages/blob/master/lang/golang/golang/Makefile
https://github.com/openwrt/packages/blob/master/lang/golang/golang/Makefile

**Comment by yichya** [comment]
`bytes.Clone()` 确实是 1.20 才带进来的 https://github.com/golang/go/issues/57126

```go
// Clone returns a copy of b[:len(b)].
// The result may have additional unused capacity.
// Clone(nil) returns nil.
func Clone(b []byte) []byte {
	if b == nil {
		return nil
	}
	return append([]byte{}, b...)
}
```

**Comment by BI7PRK** [comment]
> `bytes.Clone()` 确实是 1.20 才带进来的 [golang/go#57126](https://github.com/golang/go/issues/57126)
> 
> ```go
> // Clone returns a copy of b[:len(b)].
> // The result may have additional unused capacity.
> // Clone(nil) returns nil.
> func Clone(b []byte) []byte {
> 	if b == nil {
> 		return nil
> 	}
> 	return append([]byte{}, b...)
> }
> ```

大佬 ，我拿了你的代码来学习了。刚刚尝试编译确实是这个错误，
```SHELL
go: downloading github.com/xtls/utls v1.2.3
go: downloading github.com/xtls/reality v0.0.0-20230308170557-1c3141866eb7
# github.com/xtls/reality
../../../../dl/go-mod-cache/github.com/xtls/reality@v0.0.0-20230308170557-1c3141866eb7/handshake_server_tls13.go:101:23: undefined: bytes.Clone
make[2]: *** [Makefile:72: /tmp/tmp.j3UbI8QGKN/build_dir/target-aarch64_cortex-a53_musl/openwrt-xray/openwrt-xray-v1.7.5/.built] Error 2
make[2]: Leaving directory '/home/runner/work/openwrt-xray/openwrt-xray'
time: package/xray-core/compile#105.58#10.91#63.85
    ERROR: package/xray-core failed to build.
make[1]: *** [package/Makefile:116: package/xray-core/compile] Error 1
make[1]: Leaving directory '/tmp/tmp.j3UbI8QGKN'
make: *** [/tmp/tmp.j3UbI8QGKN/include/toplevel.mk:224: package/xray-core/compile] Error 2
Error: Process completed with exit code 2.
```

**Comment by RPRX** [comment]
感谢反馈，会修复，~~虽然客户端其实没用到这个库~~

To 群里：还有别的问题吗

**Comment by Fangliding** [comment]
@RPRX 能不能把reality scanner加到xray命令行里()

**Comment by RPRX** [comment]
@Fangliding 加到 Xray 里是比较方便，但它还处于开发阶段，目前解耦更好，~~你也不想给 v1.8.0 再加个 release-blocker 吧~~

**Comment by yoohooyoo** [comment]
> 感谢反馈，会修复，~虽然客户端其实没用到这个库~
> 
> To 群里：还有别的问题吗

没有啦没有啦，排排坐静等发版。(期待脸)

**Comment by FranzKafkaYu** [comment]
> @Fangliding 加到 Xray 里是比较方便，但它还处于开发阶段，目前解耦更好，~你也不想给 v1.8.0 再加个 release-blocker 吧~

还请一并更新分享链接标准～

**Comment by RPRX** [comment]
计划是发版后依次更新 example、分享链接标准、release note、文章

**Comment by RPRX** [comment]
前两个比较快，~~后两个等吧~~

**Comment by BI7PRK** [comment]
我以为是昨天，3.8节，大佬会发v1.8

**Comment by rurirei** [comment]
it's aggressive to requires go 1.20.

**Comment by RPRX** [comment]
> 我以为是昨天，3.8节，大佬会发v1.8

~~v1.7.2 是 01.07，v1.7.5 是 02.08，所以 v1.8.0 是 03.09~~

**Comment by RPRX** [comment]
> it's aggressive to requires go 1.20.

目前会保持对 Go 1.19 的兼容性，~~只是我本地只有 Go 1.20.1，所以没发现 Go 1.19 没 bytes.Clone()~~

**Comment by rurirei** [comment]
it's better to keep compatibiliable with go 1.18.

**Comment by Edwin-Kevin** [comment]
@RPRX 所以1.8.1是04.10，1.8.2是05.11（逃）

**Comment by thisdk** [comment]
GFW : 我们现在掌握了一条重要线索.已经能识别某富强软件的版本发布节奏了

**Comment by RPRX** [comment]
感谢反馈，https://github.com/XTLS/Xray-core/releases/tag/v1.8.0 应该可以用 Go 1.19 编译，请测试

**Comment by RPRX** [comment]
To 群里，在传输非 TLS 时，v1.8.0 与 v1.7.5 可能不兼容

**Comment by RPRX** [comment]
（指 XTLS Vision）

**Comment by Extreme-Icer** [comment]
@RPRX 已经复现了，暂时回退服务端到175，等ng新版

**Comment by BI7PRK** [comment]
准备睡觉了才看到放出来，_瘾_诱爱拍折腾的人。😄😄😄

**Comment by chika0801** [comment]
试了下 客户端 1.75 服务端 1.80 VLESS+VISION+TLS 是有 在传输非 TLS 时，v1.8.0 与 v1.7.5 可能不兼容

手机上一个手游，被代理，连不上服务器（这样试出来的）

**Comment by chika0801** [comment]
又复现不了了，再多用用看，等个ng和路由器插件也快升1.8.0了

**Comment by RPRX** [comment]
其实我更希望你们多测测 REALITY，~~因为代码又小改了一点~~

**Comment by chika0801** [comment]
win11上用v2rayn，和服务端更新了1.8.0暂没发现异常

手机v2rayng是1.75连服务端1.8.0这样的组合也用不了好长时间了，这样用，在手机上，目前没发现什么明显的异常

**Comment by chika0801** [comment]
> > it's aggressive to requires go 1.20.
> 
> 目前会保持对 Go 1.19 的兼容性，~只是我本地只有 Go 1.20.1，所以没发现 Go 1.19 没 bytes.Clone()~

在编译openwrt固件，使用下面命令更新go版本。我发现 https://github.com/openwrt/packages/branches/openwrt-22.03/lang/golang/golang 链接里面的版本还是1.19.6。幸好没强行要求必需使用1.20版本，不然openwrt那边编译又要失败。

        rm -rf feeds/packages/lang/golang/golang
        svn co https://github.com/openwrt/packages/branches/openwrt-22.03/lang/golang/golang feeds/packages/lang/golang/golang

**Comment by RPRX** [comment]
现在肯定会兼容 Go 1.19 的，一是 OpenWRT，二是 NG 那边用 Go 1.20 编译的包有点问题，包括 1.20.2，@yuhan6665 还在研究
