### ISSUE TITLE
Wechat may be agent spy

### ISSUE THREAD

**Issue by cross-hello** [XTLS/Xray-core#1758]
### Environment
- System : Windows10
- Set System variable: http_proxy=http://a.b.c.d:10811

### Phenomenon
After setting, explorer will connect 50051, 50052, 50053 port iteratively per three seconds.
![image](https://user-images.githubusercontent.com/42733664/223945773-aaa11928-f614-4d32-b884-e42d73d29af1.png)

### thought 
Af first, think it as the problem of Windows.
Then search get https://answers.microsoft.com/zh-hans/windows/forum/all/explorer%E4%B8%80%E7%9B%B4%E5%9C%A8%E8%AE%BF/7395ec69-6357-45e6-b794-72cad3b71de6

 Then find it is wechat driver cause explorer to establish connection.
 https://developers.weixin.qq.com/community/enterprisewechat/doc/000cacfa3a4c0086845af0caf56c01

After remove the wechat driver and restart explorer. The above ports explorer stop visit.

Here are the packages of removed wechat driver.
[WXDrive.zip](https://github.com/XTLS/Xray-core/files/10928705/WXDrive.zip)

### How to replicate
1. set global system variable : **http_proxy=http://a.b.c.d:10811**
2. extract package to **C:\Program Files (x86)\WXDrive**
3. restart windows explorer
4. Visit connectting log on a.b.c.d server.( Please block .*localhost.* before: `"regexp:.*localhost.*"`)

**Comment by RPRX** [comment]
~~哪有我们刚发现的某浏览器插件厉害~~

**Comment by rurirei** [comment]
what about install Wechat? inside a sandbox?

**Comment by cross-hello** [comment]
Directly remove the folder and restart explorer will be ok.

**Comment by cross-hello** [comment]
😱 Just set global system variable the day(for golang could download package), then find server with a lot of stranger logs.

**Comment by cross-hello** [comment]
Inside *WeDriveService64_70.dll* could get:
![image](https://user-images.githubusercontent.com/42733664/223955031-677044eb-d3a8-4aab-bf36-259e055e6848.png)

This is all know, sorry for unfamiliar with IDA PRO

**Comment by cross-hello** [comment]
All right, become calm. Why localhost could be spreaded? And did the connection with localhost with special meaning? 

Just don't know why observe it on server log.

OK, bye.

**Comment by RPRX** [comment]
> ~哪有我们刚发现的某浏览器插件厉害~

我们即将发布对该插件的行为分析

**Comment by KevinMX** [comment]
@pvqogw 笑死

**Comment by RPRX** [comment]
该插件，实时监控、明文上传用户浏览记录等隐私信息，

> > > ~哪有我们刚发现的某浏览器插件厉害~
> > 
> > 
> > 我们即将发布对该插件的行为分析
> 
> 不务正业，点名批评@RPRX ！
> 
> > REALITY 的下一个主要目标是“预先构建模式”，即提前采集目标网站特征，XTLS 的下一个主要目标是 0-RTT
> 
> 还不努力去实现，成天七搞八搞，东一榔头，西一棒槌的

该插件实时监控、明文上传用户浏览记录等隐私信息，~~所以不能拖，优先安排上~~

**Comment by RPRX** [comment]
> 该插件实时监控、明文上传用户浏览记录等隐私信息，~所以不能拖，优先安排上~

~~不要以吃瓜的心态看待，可能你浏览器里就有，别最后吃瓜吃到自己头上了~~
