### ISSUE TITLE
How to implement Encrypted Client Hello for XTLS-RPRX-VISION?

### ISSUE THREAD

**Issue by arashammm** [XTLS/Xray-core#1759]
Hello to great community of Xray.

I'm looking for a way to implement ECH in my XTLS-RPRX-VISION configuration.
Both my server and client are linux amd64. 
Is there any guide/tutorial/example to do so?
Is that even possible to use Encrypted Client Hello for Xray in any from?

Any help would be appreciated.
Thanks.

**Comment by cross-hello** [comment]
China has blocked ECH(Encrypted Client Hello) wholly.

And it seems don't support in *ray by now.

But just to see if it will someone submit PR.

Mar 9, 2023 21:11:40 arashammm ***@***.***>:

**Comment by arashammm** [comment]
Since I'm using this setup for Iran I hope that ECH would solve the interefereing problem of Client Hello Message

**Comment by Lippiece** [comment]
This was actually implemented! But for `tls` security.

Also looking for a way to enable Encrypted Client Hello with REALITY.

https://github.com/XTLS/Xray-core/pull/3813
