### ISSUE TITLE
没有去分析，1.7.5 用的vmess+ws+nginx+tls,没套cdn

### ISSUE THREAD

**Issue by yyiu** [XTLS/Xray-core#1760]
没有去分析，1.7.5 用的vmess+ws+nginx+tls,没套cdn
发现不能用之后换了v之后立马正常，换回1.7.5第一次访问后马上被阻断，只换了服务器端，其它配置不变，这样看来应该是有什么特征被找到了

_Originally posted by @yyiu in https://github.com/XTLS/Xray-core/issues/1750#issuecomment-1462162875_

**Comment by cross-hello** [comment]
Could you try again?

Mar 9, 2023 22:34:06 yyiu ***@***.***>:

**Comment by RPRX** [comment]
在群里发一次，在评论发一次，最后再开个 issue，~~你可真是锲而不舍~~

一、不要用 WSS，尤其是直连，原因写过了 https://github.com/XTLS/Xray-core/issues/1750#issuecomment-1459469821
二、你描述的情况看起来像一次偶然，请复现，否则不具有参考价值
