### ISSUE TITLE
Shadowsocks 2022新协议在反向代理中使用不正常

### ISSUE THREAD

**Issue by muziling** [XTLS/Xray-core#1761]
配置是参考 https://github.com/XTLS/Xray-examples/tree/main/ReverseProxy/Shadowsocks-2022 配置的
在portals 端重启了 xray， bridges端不会自动重新连接上，等很久都没连上。
这时只有重启 bridges端 才能再次连上portals 。

用早期的 Shadowsocks 协议（比如aes-128-gcm）则正常， portals 端xray随便重启， bridges端都能马上自动连接上来。

**Comment by keyuxing** [comment]
+1 同样有此问题
