### ISSUE TITLE
为啥升级后，报错用不了呀Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: VLESS clients: "flow" doesn't support "xtls-rprx-direct" in this version

### ISSUE THREAD

**Issue by 454592673** [XTLS/Xray-core#1764]
![image](https://user-images.githubusercontent.com/22283930/224195482-1235c748-9b12-49b3-832a-7a3cc35273c5.png)

**Comment by FranzKafkaYu** [comment]
> ![image](https://user-images.githubusercontent.com/22283930/224195482-1235c748-9b12-49b3-832a-7a3cc35273c5.png)

1.8版本已经不再支持xtls-rprx-direct/ xtls-rprx-origin流控。

**Comment by FranzKafkaYu** [comment]
在不知道软件做了什么改动的情况下请不要随意升级，节省自己的时间也节省开发者的时间。

**Comment by 454592673** [comment]
现有的账户没有使用到xtls,都是普通的vless+tls+cdn,很奇怪了

**Comment by FranzKafkaYu** [comment]
> 现有的账户没有使用到xtls,都是普通的vless+tls+cdn,很奇怪了

自行查看/usr/local/x-ui/bin/config.json内的配置内容，也许是旧版x-ui的BUG.

**Comment by h2ch** [comment]
@FranzKafkaYu 除vision以外的流控，已在1.8中移除，要用direct降级服务端

**Comment by 454592673** [comment]
![image](https://user-images.githubusercontent.com/22283930/224197583-4fbe26b1-4209-40cd-8d93-f1a278d2c92b.png)
很离谱，没开tls，自己加了flow：xtls-rprx-direct

**Comment by 454592673** [comment]
![image](https://user-images.githubusercontent.com/22283930/224197741-7164d253-62e9-4808-af4d-248e6cfa3c32.png)
很离谱，没开tls，自己加了flow：xtls-rprx-direct

**Comment by ThreeSourLemon** [comment]
@454592673 这是xui的问题吧

**Comment by 454592673** [comment]
那边作者没有开issues,flow可以换成哪些参数不影响性能呢，待会儿全文替换掉

**Comment by FranzKafkaYu** [comment]
> 那边作者没有开issues,flow可以换成哪些参数不影响性能呢，待会儿全文替换掉

如果使用原版x-ui，无法解决该问题，请降级服务端xray core版本.

**Comment by GreatMichaelLee** [comment]
1.8.0为什么没有release notes啊？REALITY怎么用，给个文档啊~

**Comment by ZhuangJiayu** [comment]
direct在1.8.0已经弃用了

**Comment by GreatMichaelLee** [comment]
> > 1.8.0为什么没有release notes啊？REALITY怎么用，给个文档啊~
> 
> https://github.com/XTLS/REALITY

看不懂，怎么办，这个feature感觉一头雾水，也不知道每个配置项代表啥意思，是可以默认缺省还是需要配置，比如shortId, publickey我从哪里构造？长度多长？都不清楚。

**Comment by qist** [comment]
https://github.com/XTLS/Xray-examples/tree/main/VLESS-TCP-XTLS-Vision

**Comment by GreatMichaelLee** [comment]
> https://github.com/XTLS/Xray-examples/tree/main/VLESS-TCP-XTLS-Vision

这个example里没用REALITY的的配置样例，其他地方有的样例也没有说明publickey, shortId, SpideX到底是何种用途，如何配置，参数范围是什么...

**Comment by qist** [comment]
这个方案类似shadow-tls  publickey, shortId, 客户端服务器验证啊。他这个例子写的很详细啊。

**Comment by GreatMichaelLee** [comment]
> 这个方案类似shadow-tls publickey, shortId, 客户端服务器验证啊。他这个例子写的很详细啊。

没用过shadow-tls,之前都是xtls用下来的.....-_-!

**Comment by chika0801** [comment]
> 我刚测试了，可以用，但每隔几分钟就断了，不知道啥原因，重启xray又能用几分钟

我这边测试的VPS机 不好回程线路有VU和VIR的法兰克福，对联通是200MS，其它好回程线路的VPS，都没有这现象。

**Comment by RPRX** [comment]
麻烦请原版 x-ui 作者修复该问题

**Comment by diablo2999** [comment]
> 麻烦请原版 x-ui 作者修复该问题

相关配置在 /etc/x-ui/x-ui.db 内，删除或修改配置，即可。

**Comment by lniaen** [comment]
只需要进入XTLS选项中，选择无，再关闭即可。

**Comment by php737** [comment]
> 只需要进入XTLS选项中，选择无，再关闭即可。
具体是怎么设置的啊? 麻烦教一下

**Comment by ototsu** [comment]
不折腾就v1.7.5

**Comment by wpowen** [comment]
1.7.5正常，亲测。就是不知道pass wall 版本比较高能不能用啊。小火箭正常

**Comment by weasonn** [comment]
> > 只需要进入XTLS选项中，选择无，再关闭即可。
> > 具体是怎么设置的啊? 麻烦教一下

入站列表，点击编辑，打开下面的tls，此时上方的users里面会出现id flow email这些参数，把flow设置为空，然后再关掉tls保存就行了。

**Comment by Zhgong** [comment]
> > 只需要进入XTLS选项中，选择无，再关闭即可。
> > 具体是怎么设置的啊? 麻烦教一下
当然，以下是您刚刚描述的软件操作步骤：

1. **进入“修改入站”设置**。
2. **打开“xtls”**：在“修改入站”设置中找到与“xtls”相关的选项，并将其打开。
3. **在“flow”下拉菜单中选中“无”**：
   - 找到“flow”的下拉菜单。
   - 在下拉选项中选择或点击“无”。
4. **重新关闭“xtls”设置**：
   - 返回到与“xtls”相关的设置部分。
   - 关闭“xtls”选项。

**Comment by appotry** [comment]
https://github.com/FranzKafkaYu/x-ui 用这个新的仓库吧，原作者已经失联很久了

不过也有同样的bug

**Comment by Windriderking** [comment]
> > 麻烦请原版 x-ui 作者修复该问题
> 
> 相关配置在 /etc/x-ui/x-ui.db 内，删除或修改配置，即可。

我艹，老哥一说我打看一，这玩意居然明文保存ui管理员密码。赶紧卸载老老实实手动管理了。

**Comment by Windriderking** [comment]
> https://github.com/FranzKafkaYu/x-ui 用这个新的仓库吧，原作者已经失联很久了
> 
> 不过也有同样的bug

用了你这个仓库的，检查了一下一看ui管理员密码还是明文保存的。。。无语了

**Comment by appotry** [comment]
> > https://github.com/FranzKafkaYu/x-ui 用这个新的仓库吧，原作者已经失联很久了
> > 不过也有同样的bug
> 
> 用了你这个仓库的，检查了一下一看ui管理员密码还是明文保存的。。。无语了

这个新仓库作者人还在，issues开着的，可以去提交问题单

**Comment by Fangliding** [comment]
@appotry 自己部署自用的服务没必要搞那么复杂 你的vless uuid还是明文存储的呢

**Comment by Windriderking** [comment]
> 
你说这些都没有shell公开对外啊。一旦脱裤还是挺麻烦的，当然我也同意，自己用的能偷懒还是偷懒了。但是一个最基本的hahs+salt实现起来能有多麻烦呢

**Comment by Windriderking** [comment]
> @Windriderking 建议你手动安装，没有这些问题，不靠别人的脚本，自己把握。

之前我确实一直都是手动管理的。

**Comment by Fangliding** [comment]
@Windriderking 你行你上.jpg

**Comment by chika0801** [comment]
> > @Windriderking 建议你手动安装，没有这些问题，不靠别人的脚本，自己把握。
> 
> 之前我确实一直都是手动管理的。

手动安装指 https://github.com/XTLS/Xray-install

**Comment by Windriderking** [comment]
> > > @Windriderking 建议你手动安装，没有这些问题，不靠别人的脚本，自己把握。
> > 
> > 
> > 之前我确实一直都是手动管理的。
> 
> 手动安装指 https://github.com/XTLS/Xray-install

我是这个意思，我懂的谢谢。。。

**Comment by haoyaxuan** [comment]
已经找到了解决办法，在打开【编辑】界面时，在控制台执行如下命令：`delete inModal.inbound.settings.vlesses[0].flow`，后点击保存。
如下：
![image](https://github.com/XTLS/Xray-core/assets/47971326/90847208-00e3-4945-857f-4babf5b2a91d)

有效前提：必须是vless协议

**Comment by zhoujun0601** [comment]
> ### Fix Bug
> > 已经找到了解决办法，在打开【编辑】界面时，在控制台（按F12打开）
> > 执行如下命令：`delete inModal.inbound.settings.vlesses[0].flow`，后点击【修改】，前提协议必须是vless。
> > 如下：
> 
> ## ![image](https://user-images.githubusercontent.com/47971326/268211829-e9f18ba1-1d65-46a1-b78f-74c40d52fa0b.png)
> ### 有图有真相
> ## ![image](https://user-images.githubusercontent.com/47971326/268198672-ea1e9c79-ec3c-4599-bb0c-954948001431.png)
> ## ![image](https://user-images.githubusercontent.com/47971326/268198898-07178240-cd91-4392-8a2c-fba0be04c6e8.png)
> ### 缺点
> 每次编辑的时，都需要执行命令

不错，能解决问题

**Comment by jeawell** [comment]
我有个土办法，一个节点一个节点试，最后找到出错的节点，编辑配置，按照报错修改，我的是Failed to start: main: failed to load config files: [stdin:] > infra/conf: VLESS users: "flow" doesn't support "xtls-rprx-vision-udp443-udp443" in this version，然后就改443端口的节点的流控为xtls-rprx-vision-udp443就可以了，我500多个节点，最后找到2个出错，改了后就可以用了。

<img width="835" height="375" alt="Image" src="https://github.com/user-attachments/assets/3170ea93-efcc-4cb2-b578-d8718805649d" />
