### ISSUE TITLE
按照最新的vision和nginx配置后无法正常回落8001和8002端口

### ISSUE THREAD

**Issue by loydcheung** [XTLS/Xray-core#1768]
xray 报错日志：

2023/03/10 05:32:13 [Warning] [1306286989] app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to dial to 127.0.0.1:8001 > common/retry: [dial tcp 127.0.0.1:8001: connect: connection refused] > common/retry: all retry attempts failed
2023/03/10 05:32:22 [Warning] [1979228075] app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to dial to 127.0.0.1:8001 > common/retry: [dial tcp 127.0.0.1:8001: connect: connection refused] > common/retry: all retry attempts failed
2023/03/10 05:32:33 [Warning] [2907571396] app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to dial to 127.0.0.1:8001 > common/retry: [dial tcp 127.0.0.1:8001: connect: connection refused] > common/retry: all retry attempts failed

除了example里的示例和常规的nginx证书配置外，还需要什么其他配置吗？8001和8002端口是不是需要对应到具体的其他服务。

**Comment by loydcheung** [comment]
配置完全照搬的这个https://github.com/XTLS/Xray-examples/blob/main/VLESS-TCP-XTLS-Vision/nginx.conf

**Comment by chika0801** [comment]
你发下你的服务端配置，和nginx配置，我自己测试是正常的。

**Comment by chika0801** [comment]
示例的8001 8002接xray服务端配置的回落，反代有一个动漫网站。

**Comment by chika0801** [comment]
示例的8001 8002接xray服务端配置的回落，反代有一个动漫网站。

**Comment by loydcheung** [comment]
> 示例的8001 8002接xray服务端配置的回落，反代有一个动漫网站。

感谢大佬救助，
nginx配置完全照搬，
服务端配置也基本没啥改动：
{
  "inbounds": [
{
	"listen": "0.0.0.0",
	"port": 443,
	"protocol": "vless",
	"settings": {
	"clients": [
        {
          "id"： ""
        "flow": "xtls-rprx-vision"
        }
      ],
	"decryption": "none"
	"fallbacks": [
		{
		"dest": 8001,
		"xver": 1
		},
		{
		"alpn": "h2",
		"dest": "8002",
		"xver": 1
		}
	]
	},
        "streamSettings": {
               "network": "tcp",
		"security": "tls",
		"tlsSettings": {
			"rejectUnknownSni": true,
			"minVersion": "1.2",
			"certificates": [
                        {
			"ocspStapling": 3600,
                            "certificateFile": "/root/.acme.sh/.../fullchain.cer",
 "keyFile": "/root/.acme.sh/.../xxx.key"
                        }
                    ]
		}
	},
	"sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            }
},
{     
	"listen": "127.0.0.1",
	"port": 8002,
        "protocol": "vmess",
        "settings": {
         "clients": [
        {
             "id": "13b7e176-83ae-4958-b0e4-3c9b2f24c67c",
           "level": 0
          }
        ]
      }
}
],
  "outbounds": [
	{
	"protocol": "freedom",
	"tag": "direct"
	},
	{
	"protocol": "blackhole",
	"tag": "block"
  }
],
  "log": {
	"loglevel": "warning",
	"access": "/var/log/xray/access.log",
	"error": "/var/log/xray/error.log"
	},
  "routing": {
	"domainStrategy": "IPIfNonMatch",
	"rules": [
	{
	"type": "field",
        "ip": [
		"geoip:cn"
		],
        "outboundTag": "block"
	}
    ]
  },
 "policy": {
        "levels": {
            "0": {
                "handshake": 3,
                "connIdle": 188
            }
        }
    }
}

**Comment by chika0801** [comment]
我看你发的服务端配置，你加了一段这个，你可能不了解xray配置原理。你把这段删了。如果你nginx配置是用的我那个示例的，nginx里监听了8002的。你在Xray配置里写的下面这段也没有作用。
```
{
            "listen":"127.0.0.1",
            "port":8002,
            "protocol":"vmess",
            "settings":{
                "clients":[
                    {
                        "id":"13b7e176-83ae-4958-b0e4-3c9b2f24c67c",
                        "level":0
                    }
                ]
            }
        }
```

**Comment by loydcheung** [comment]
> 我看你发的服务端配置，你加了一段这个，你可能不了解xray配置原理。你把这段删了。如果你nginx配置是用的我那个示例的，nginx里监听了8002的。你在Xray配置里写的下面这段也没有作用。
> 
> ```
> {
>             "listen":"127.0.0.1",
>             "port":8002,
>             "protocol":"vmess",
>             "settings":{
>                 "clients":[
>                     {
>                         "id":"13b7e176-83ae-4958-b0e4-3c9b2f24c67c",
>                         "level":0
>                     }
>                 ]
>             }
>         }
> ```

删掉了，还是有阻断问题，可能要换个IP再试试了。
大佬，还有个问题，用你的nginx配置会占用80端口，到90天的时候证书acme自动更新的问题怎么解决？

**Comment by chika0801** [comment]
删后，你输入你域名，浏览器显示的网页是个动漫网站了吧。（表示 回落到nginx 8002 通了）

关于阻断（我此突然打不开网页，等3分钟左右，自己就好了。不通期间ping你VPS的端口，可能显示国内也是通的）

建议是换好回程的VPS，如果证书是免费的，看看CA是不是LE的，不要用ZERO的CA的证书。

客户端 比如在v2rayN配置界面，地址填你VPS的IP，SNI填你SSL证书里包含的域名。

上面的建议你试试能不能对阻断遇到有改善。

**Comment by chika0801** [comment]
> 大佬，还有个问题，用你的nginx配置会占用80端口，到90天的时候证书acme自动更新的问题怎么解决？

在nginx配置里把 80跳转443部分用 # 注释掉

或我的笨办法是写个Crontab定时任务 ，定时执行一个xxx.sh 脚本内容如下

```
#!/usr/bin/env bash
systemctl stop nginx
/root/.acme.sh/acme.sh --cron --home /root/.acme.sh
systemctl start nginx

```

**Comment by loydcheung** [comment]
> 没法推荐，不知道你一年想花多少RMB买机，你是什么宽带。一般来说 HK CMI回程在170-280RMB一年 9929回程在200-300一年 4837回程有130-250一年的 GIA也有200-300一年的
> 
> 
> 
> 便宜的软银 IIJ回程的。

我上海电信、联通双路宽带负载均衡。现在用的Vultr洛杉矶节点。一年费用也400左右了，之前一直挺稳的，就最近开始疯狂阻断。有没有其他的好用的美国好回程主机推荐。

话说我刚才设置了提子只走联通，貌似稳了一段时间了。应该大概率是像大家说的是电信在作恶

**Comment by chika0801** [comment]
VU 年青人的第1台VPS，我也是才入门时被博客AFF MAN推荐买的（当时没买机经验纯小白）。你一直在用就2333。纯推荐无AFF，你买cloudsilk的美西9929吧，活动到11日年付用码后200RMB。

如果你能主用联通，收软银东京回程的机。要全新机只推荐www.silicloud.com/cn/activity/vps 网页最下面的2年付34.54刀的那个套餐。这家顶上有试用的套餐你买来试得了。

**Comment by loydcheung** [comment]
> VU 年青人的第1台VPS，我也是才入门时被博客AFF MAN推荐买的（当时没买机经验纯小白）。你一直在用就2333。纯推荐无AFF，你买cloudsilk的美西9929吧，活动到11日年付用码后200RMB。
> 
> 如果你能主用联通，收软银东京回程的机二手（如果你有收二手经验）。要全新机现在推荐 [www.silicloud.com/cn/activity/vps](http://www.silicloud.com/cn/activity/vps) 网页最下面的2年付34.54刀的那个套餐。这家顶上有试用的套餐你买来试得了。

我冲了一个cloudsilk，但是付完款快一天了怎么状态还是在审核中，是不是跑路了。
<img width="96" alt="image" src="https://user-images.githubusercontent.com/59357798/224470204-4ae89ba1-839d-4038-a800-807dee8d9872.png">

**Comment by chika0801** [comment]
> > VU 年青人的第1台VPS，我也是才入门时被博客AFF MAN推荐买的（当时没买机经验纯小白）。你一直在用就2333。纯推荐无AFF，你买cloudsilk的美西9929吧，活动到11日年付用码后200RMB。
> > 如果你能主用联通，收软银东京回程的机二手（如果你有收二手经验）。要全新机现在推荐 [www.silicloud.com/cn/activity/vps](http://www.silicloud.com/cn/activity/vps) 网页最下面的2年付34.54刀的那个套餐。这家顶上有试用的套餐你买来试得了。
> 
> 我冲了一个cloudsilk，但是付完款快一天了怎么状态还是在审核中，是不是跑路了。 <img alt="image" width="96" src="https://user-images.githubusercontent.com/59357798/224470204-4ae89ba1-839d-4038-a800-807dee8d9872.png">

发工单或去他tg群问老板，这里不是全球工单论坛，PS他现在不会跑
