### ISSUE TITLE
Speed Optimization

### ISSUE THREAD

**Issue by arashammm** [XTLS/Xray-core#1776]
hello there

I use XTLS-RPRX-VISION for my proxy and I  also enabled bbr on the server.

But it still seems a little sluggish. Is there any other tweaks that I could make to xtls core or server to increase the speed and reduce latency?

**Comment by sduoduo233** [comment]
try [hysteria](https://github.com/apernet/hysteria), it is optimized for bad networks

**Comment by arashammm** [comment]
> try [hysteria](https://github.com/apernet/hysteria), it is optimized for bad networks

hysteria is great but unfortunatly it gets blocked within hours in my region!

Can anyone guide about using mux configuration in client side?
Does that have anything with speed and latency?

**Comment by cross-hello** [comment]
How much megabytes per second do you expect?

Mar 12, 2023 17:50:36 arashammm ***@***.***>:

**Comment by Fangliding** [comment]
ot
