### ISSUE TITLE
UDP crashed with FakeDNS

### ISSUE THREAD

**Issue by zengboin** [XTLS/Xray-core#1777]
-sn-i3belney.googlevideo.com for xUDP buffer at 0
2023/03/12 06:50:42 [Debug] transport/internet/udp: UDP original destination: udp:198.18.236.115:443
2023/03/12 06:50:42 [Info] [2703513486] app/dispatcher: [fakedns client] override with domain: rr2---sn-i3belney.googlevideo.com for xUDP buffer at 0
2023/03/12 06:50:42 [Info] [2703513486] app/dispatcher: [fakedns client] restore FakeIP: udp:198.18.236.115:443[198.18.236.115 [fc00::186:d495:ed18]] for xUDP buffer at 0
2023/03/12 06:50:42 [Info] [2703513486] app/dispatcher: [fakedns client] restore FakeIP: udp:198.18.236.115:443[198.18.236.115 [fc00::186:d495:ed18]] for xUDP buffer at 0
2023/03/12 06:50:42 [Info] [2703513486] app/dispatcher: [fakedns client] restore FakeIP: udp:198.18.236.115:443[198.18.236.115 [fc00::186:d495:ed18]] for xUDP buffer at 0
2023/03/12 06:50:42 [Info] [2703513486] app/dispatcher: [fakedns client] restore FakeIP: udp:rr2---sn-i3belney.googlevideo.com:443[198.18.236.115 [fc00::186:d495:ed18]] for xUDP buffer at 0
panic: Calling IP() on a DomainAddress.

goroutine 4103 [running]:
github.com/xtls/xray-core/common/net.domainAddress.IP(...)
        github.com/xtls/xray-core/common/net/address.go:164
github.com/xtls/xray-core/proxy/dokodemo.(*PacketWriter).WriteMultiBuffer(0xc0027f69c0, {0xc0034c3118?, 0x0?, 0xc001cfae60?})
        github.com/xtls/xray-core/proxy/dokodemo/dokodemo.go:274 +0x1cc
github.com/xtls/xray-core/common/buf.copyInternal({0x145dca0, 0xc002151160}, {0x145cc00, 0xc0027f69c0}, 0xc0027d4c48)
        github.com/xtls/xray-core/common/buf/copy.go:87 +0x175
github.com/xtls/xray-core/common/buf.Copy({0x145dca0, 0xc002151160}, {0x145cc00, 0xc0027f69c0}, {0xc001cfaf38, 0x1, 0x0?})
        github.com/xtls/xray-core/common/buf/copy.go:104 +0xa5
github.com/xtls/xray-core/proxy/dokodemo.(*DokodemoDoor).Process.func3()
        github.com/xtls/xray-core/proxy/dokodemo/dokodemo.go:226 +0xef
github.com/xtls/xray-core/common/task.Run.func1(0xc0019c1e90?)
        github.com/xtls/xray-core/common/task/task.go:28 +0x2e
created by github.com/xtls/xray-core/common/task.Run
        github.com/xtls/xray-core/common/task/task.go:27 +0xde

**Comment by rurirei** [comment]
>> -sn-i3belney.googlevideo.com for xUDP buffer at 0
2023/03/12 06:50:42 [Debug] transport/internet/udp: UDP original destination: udp:198.18.236.115:443

is fake dns compatibiable with a transparent proxy?

**Comment by zengboin** [comment]
Yes.
