### ISSUE TITLE
出站流量通过路由规则判断失败，一直走第一个出站

### ISSUE THREAD

**Issue by gzm930508** [XTLS/Xray-core#1780]
为了解锁Netflix、Disney等流媒体，有三个VPS，一个我连接的，另外两个根据访问不同的地址走相应的VPS。
服务器xray配置如下：
### 主要连接 VPS1：
    "log": {
        "access": "/var/log/xray/access.log",
        "error": "/var/log/xray/error.log",
        "loglevel": "warning"
    },
    "api": {
        "tag": "api",
        "services": [
            "StatsService"
        ]
    },
    "stats": {},
    "policy": {
        "levels": {
            "0": {
                "statsUserUplink": true,
                "statsUserDownlink": true
            }
        },
        "system": {
            "statsInboundUplink": true,
            "statsInboundDownlink": true,
            "statsOutboundUplink": true,
            "statsOutboundDownlink": true
        }
    },
    "inbounds": [
        {
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "uuid",
                        "flow": "xtls-rprx-direct",
                        "level": 0,
                        "email": "1"
                    },
                    {
                        "id": "uuid",
                        "flow": "xtls-rprx-direct",
                        "level": 0,
                        "email": "2"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": 35001,
                        "xver": 1
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "alpn": [
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "",
                            "keyFile": ""
                        }
                    ]
                }
            }
        },
        {
            "listen": "127.0.0.1",
            "port": 10085,
            "protocol": "dokodemo-door",
            "settings": {
                "address": "127.0.0.1"
            },
            "tag": "api"
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "tag": "block"
        },
        {
            "protocol": "vmess",
            "settings": {
                "vnext": [
                    {
                        "address": "VPS2 IP",
                        "port": 35801,
                        "users": [
                            {
                                "id": "uuid",
                                "security": "auto",
                                "alterId": 0
                            }
                        ]
                    }
                ]
            },
            "tag": "unlock-streaming-media-01"
        },
        {
            "protocol": "vmess",
            "settings": {
                "vnext": [
                    {
                        "address": "VPS3 IP",
                        "port": 35801,
                        "users": [
                            {
                                "id": "uuid",
                                "security": "auto",
                                "alterId": 0
                            }
                        ]
                    }
                ]
            },
            "tag": "unlock-streaming-media-02"
        }
    ],
    "routing": {
        "domainStrategy": "AsIs",
        "rules": [
            {
                "type": "field",
                "inboundTag": [
                    "api"
                ],
                "outboundTag": "api"                
            },
            {
                "type": "field",
                "ip": [
                    "geoip:cn",
                    "geoip:private"
                ],
                "outboundTag": "block"
            },
            {
                "type": "field",
                "domain": [
                    "geosite:netflix",
                    "geosite:google"
                ],
                "outboundTag": "unlock-streaming-media-01"
            },
            {
                "type": "field",
                "domain": ["geosite:disney"],
                "outboundTag": "unlock-streaming-media-02"
            }
        ]
    }

### VPS2:
    "log": {
        "access": "/var/log/xray/access.log",
        "error": "/var/log/xray/error.log",
        "loglevel": "warning"
    },
    "inbounds": [
        {
            "listen": "0.0.0.0",
            "port": 35801,
            "protocol": "vmess",
            "settings": {
                "clients": [
                    {
                        "id": "uuid"
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp"
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "tag": "block"
        }
    ],
    "routing": {
        "domainStrategy": "AsIs",
        "rules": [
            {
                "type": "field",
                "ip": [
                    "geoip:private"
                ],
                "outboundTag": "block"
            }
        ]
    }

VPS3的配置和VPS2相同，现在访问netflix和disney都是直接走的fredom，没通过解锁的两个VPS

**Comment by amirhosss** [comment]
From the documentation: 

> For each connection, the route will be judged according to these rules from **top to bottom**, and when the **first effective rule is encountered**, the connection is forwarded to the or or it

**Comment by IRN-Kawakaze** [comment]
在vps1的inbound加入sniffing模块后再做尝试，否则传入的如果是IP连接肯定匹配不到基于域名的规则。
sniffing模块配置样例：
```
……省略……
    "inbounds": [
        {
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls",
                    "quic"
                ]
            },
            "port": 443,
            "protocol": "vless",
……省略……
```

提醒：入站开启sniffing之后，routing的domainStrategy建议改为IPOnDemand或IPIfNonMatch，避免基于IP的规则无法生效。

**Comment by chika0801** [comment]
看完配置有人回了，vps1入站记得开域名嗅探（你一般是用比如亚马逊tv棒接wifi，wifi前面边软路由环境，vps1入站有域名嗅探参数就是 asis也可以

**Comment by gzm930508** [comment]
> 

可以了，确实是缺了这块，补上就正常了，谢谢。

**Comment by gzm930508** [comment]
> > 在vps1的inbound加入sniffing模块后再做尝试，否则传入的如果是IP连接肯定匹配不到基于域名的规则。
> sniffing模块配置样例：
> 
> ……省略……
>     "inbounds": [
>         {
>             "sniffing": {
>                 "enabled": true,
>                 "destOverride": [
>                     "http",
>                     "tls",
>                     "quic"
>                 ]
>             },
>             "port": 443,
>             "protocol": "vless",
> ……省略……
> 提醒：入站开启sniffing之后，routing的domainStrategy建议改为IPOnDemand或IPIfNonMatch，避免基于IP的规则无法生效。
> 
> 

确实是因为缺少这块内容，补上就可以了，谢谢。

**Comment by gzm930508** [comment]
> 在vps1的inbound加入sniffing模块后再做尝试，否则传入的如果是IP连接肯定匹配不到基于域名的规则。 sniffing模块配置样例：
> 
> ```
> ……省略……
>     "inbounds": [
>         {
>             "sniffing": {
>                 "enabled": true,
>                 "destOverride": [
>                     "http",
>                     "tls",
>                     "quic"
>                 ]
>             },
>             "port": 443,
>             "protocol": "vless",
> ……省略……
> ```
> 
> 提醒：入站开启sniffing之后，routing的domainStrategy建议改为IPOnDemand或IPIfNonMatch，避免基于IP的规则无法生效。

确实是因为缺少这块内容，加上之后就可以了，谢谢。

**Comment by gzm930508** [comment]
> 看完配置有人回了，vps1入站记得开域名嗅探（你一般是用比如亚马逊tv棒接wifi，wifi前面边软路由环境，vps1入站有域名嗅探参数就是 asis也可以

跟你说的差不多，我是AX86U刷的官改，然后apple tv或者手机 电脑这些连，我按照上面的方法加上sniffing之后目前满足需求了，谢谢。
