### ISSUE TITLE
TLS Version set to 1.3 but the xray client sends 1.0

### ISSUE THREAD

**Issue by arashammm** [XTLS/Xray-core#1781]
hello there

So I tried to analyze the client hello message on XTLS-RPRX-VISION to further analyze flaws on my configuration.

I noticed that despite setting tls version to 1.3 on both client and server. my client side still sends client hello in TLSv1.1 

<img width="1122" alt="Screen Shot 2023-03-12 at 11 40 56 PM" src="https://user-images.githubusercontent.com/121300770/224570729-9d1c17c9-2e6e-4e28-b507-6a453fcf7ae9.png">

is that something normal? is the client hello tls protocol is always set to 1.1 and than later in the handshake it will change to 1.3?
or I can configure that in xray config file?

here is my server side  :

...
    "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                 "rejectUnknownSni": true,
                    "minVersion": "1.3",
                    "alpn": [
                        "http/1.1"
                    ],
....

here is my client side:

...
 "streamSettings": {
          "network": "tcp",
          "security": "tls",
          "tlsSettings": {
"serverName": "my sni",
 "minVersion": "1.3",
              "allowInsecure": false,
              "fingerprint": "random"
....

**Comment by lxhao61** [comment]
```
          "alpn": [
            "http/1.1"
          ]
````
改成如下试试
```
          "alpn": [
            "h2", 
            "http/1.1"
          ]
````

**Comment by arashammm** [comment]
> ```
>           "alpn": [
>             "http/1.1"
>           ]
> ```
> 
> Delete the "alpn" configuration block (the default is as follows) or try as follows
> 
> ```
>           "alpn": [
>             "h2", 
>             "http/1.1"
>           ]
> ```

thanks for the help.
but since i'm  just investigation client hello I don't think this part has anything to do with that.
I'm assuming the issue is about using rather old tls fingerprints?

**Comment by SakuraSakuraSakuraChan** [comment]
@arashammm Not sure if this helps
https://groups.google.com/g/golang-nuts/c/lBLqbPuh8Rk

**Comment by cross-hello** [comment]
> hello there
> 
> So I tried to analyze the client hello message on XTLS-RPRX-VISION to further analyze flaws on my configuration.
> 
> I noticed that despite setting tls version to 1.3 on both client and server. my client side still sends client hello in TLSv1.1
> 
> <img alt="Screen Shot 2023-03-12 at 11 40 56 PM" width="1122" src="https://user-images.githubusercontent.com/121300770/224570729-9d1c17c9-2e6e-4e28-b507-6a453fcf7ae9.png">
> 
> is that something normal? is the client hello tls protocol is always set to 1.1 and than later in the handshake it will change to 1.3? or I can configure that in xray config file?
> 
> here is my server side :
> 
> ... "streamSettings": { "network": "tcp", "security": "tls", "tlsSettings": { "rejectUnknownSni": true, "minVersion": "1.3", "alpn": [ "http/1.1" ], ....
> 
> here is my client side:
> 
> ... "streamSettings": { "network": "tcp", "security": "tls", "tlsSettings": { "serverName": "my sni", "minVersion": "1.3", "allowInsecure": false, "fingerprint": "random" ....

Yes, it is intended.

For TLS 1.3, record layer could be set to TLS 1.0 or TLS 1.2.

see here: https://www.analysisman.com/2021/06/wireshark-tls1.2.html?m=1

**Comment by RPRX** [comment]
首先标题错了，它发的是 1.0，我帮你改了，其次这个是 RFC 8446 推荐的行为：https://www.rfc-editor.org/rfc/rfc8446#section-5.1

**Comment by RPRX** [comment]
To 群里：

其实 [REALITY example](https://github.com/XTLS/REALITY#vless-xtls-utls-reality-example-for-xray-core) 文字第一行说的就是 dest 指向本机的 Nginx：

> 若用 REALITY 取代 TLS，**可消除服务端 TLS 指纹特征**，仍有前向保密性等，**且证书链攻击无效，安全性超越常规 TLS**

并且，客户端必须开指纹模拟，不能用 Go 的指纹，参考 https://github.com/XTLS/Xray-core/discussions/1773#discussioncomment-5276077

~~秒天秒地秒空气真不是吹的~~

**Comment by csryt** [comment]
@RPRX 来水啊
