### ISSUE TITLE
Fingerprinting Captured Client Hello

### ISSUE THREAD

**Issue by arashammm** [XTLS/Xray-core#1782]
Hello again to the beloved xray community.

Xray is a very promising project amongst new circumventing tools for bypassing firewalls.

I wanted to request an enhancement to this project for the savy who want to use their own captured client hello fingerprint in tls proxies such as XTLS.

It would be great if we had the ability to capture a regular client hello packet from our browser to camouflage website and implement that inside xray core (client-side).
I know that [utls](https://github.com/refraction-networking/utls) has this option in itself and with little tweaking inside the xray code this method is possible.

This way we get a vary wide range of unique fngerprints for each set up which makes it very hard to be flagged.

Right now, the default fingerprints in xray/utls are flagged and recognized very easily after a day or so.

And at the end, if anyone could help me to where to look in xray codes to confgiure that option I would appreciate it.

**Comment by cross-hello** [comment]
```json
"tlsSettings": {
  "fingerprint": "randomized"
}
```

**Comment by arashammm** [comment]
> ```json
> "tlsSettings": {
>   "fingerprint": "randomized"
> }
> ```

can you elaborate more?
how can I use randomized to implement my custome fingerprint?
I couldn't find that anywhere

**Comment by cross-hello** [comment]
None, can't customize to specify fingerprint in configuration.

"fingerprint": "randomized" generate a new fingerprint for you each time.

Mar 13, 2023 08:41:49 arashammm ***@***.***>:

**Comment by arashammm** [comment]
> None, can't customize to specify fingerprint in configuration. "fingerprint": "randomized" generate a new fingerprint for you each time. Mar 13, 2023 08:41:49 arashammm ***@***.***>:
> […](#)

Thanks for the clarification. 
so it seems this would be a viable option to add in future releases. Don’t you think?

Btw, with randomized we can get a randomized client hello with random bytes from firefox, chrome, and ios?

**Comment by bcegkmqs23** [comment]
> > None, can't customize to specify fingerprint in configuration. "fingerprint": "randomized" generate a new fingerprint for you each time. Mar 13, 2023 08:41:49 arashammm _**@**_.***>:
> > […](#)
> 
> Thanks for the clarification. so it seems this would be a viable option to add in future releases. Don’t you think?
> 
> Btw, with randomized we can get a randomized client hello with random bytes from firefox, chrome, and ios?

If I didn't misremember: `"random"` means randomly choose one from `"firefox", "chrome"` etc., and `"randomized"` means a generated completely random fingerprint.

**Comment by zxcvos** [comment]
[Xray-docs-next](https://xtls.github.io/Xray-docs-next/en/config/transport.html#tlsobject)

> "random": randomly select one in newer versions of browsers
> "randomized": generate a completely random and unique fingerprint (100% compatible with TLS 1.3 using X25519)

**Comment by GreatMichaelLee** [comment]
so I am just wondering, which one will be less recognizable patten between 'random','randomized' and a paticular fingerprint? If my setup  is only having the traffic among my softrouter and mobile phone to VPS(M to 1）,  does that mean random will be more safer since it looks like more real?

**Comment by RPRX** [comment]
这是个很好的想法，建议在 uTLS 也发一下

**Comment by arashammm** [comment]
> a, I suggest posting it in uTLS

Thanks for the suggestion RPRX.
but I think they implemented this kind of action in their code earlier.

See [here](https://github.com/refraction-networking/utls#fingerprinting-captured-client-hello).

**Comment by arashammm** [comment]
> ing, which one will be less recognizable patten between 'random','randomized' and a paticular fingerprint? If my setup is only having the traffic among my softrouter and mobile phone to VPS(M to 1）, does that mean random will be more safer since it

Obviously randomized option is more unique and less recognizable in that manner.
But I don't know exactly how "randomized" works and maybe the created fingerprint works but it's not like any other typical browser fingerprint which makes it more recognizable in that way.

And this brings me back to my main question earlier. how exactly randomized fingerprint works??  like what cipher suites it will choose from randomly?

**Comment by elrazez** [comment]
I'm still wondering which one is the best at keeping the server IP undetected from GFW: random, randomized or a static one (chrome, firefox, etc.).

any explanations/suggestions would be appreciated.

**Comment by elrazez** [comment]
ok found this:

              https://github.com/XTLS/Xray-core/commit/f32921df307d80063fddcd5e6aa11d95f57f394e

> But we should avoid using it unless we have to, see https://github.com/refraction-networking/utls/pull/157#issuecomment-1417156797

简单来说，当你所在的地区连常规浏览器的指纹都封锁时，可以试一下 `randomized` 指纹，否则不要用。

_Originally posted by @RPRX in https://github.com/XTLS/Xray-core/issues/1752#issuecomment-1460076776_
