### ISSUE TITLE
how to set disguise site in xray-core?

### ISSUE THREAD

**Issue by firefoxOnFire** [XTLS/Xray-core#1788]
![IMG_20230313_223529](https://user-images.githubusercontent.com/122431170/224774122-5f2dd796-7099-418f-99b4-22cd12faf9a1.jpg)
How to do exactly same thing in xray?? Is it possible to add those sites i can access without vpn easily??

**Comment by computerscot** [comment]
You could try the new Xray REALITY security from Xray-core version 1.8.0.

**Comment by firefoxOnFire** [comment]
> You could try the new Xray REALITY security from Xray-core version 1.8.0.

Can you show how to setup this ? You can post server config.

**Comment by computerscot** [comment]
https://github.com/chika0801/Xray-examples/tree/main/VLESS-XTLS-uTLS-REALITY
