### ISSUE TITLE
vmess 连接另一台 vmess

### ISSUE THREAD

**Issue by ycsks** [XTLS/Xray-core#1789]
两台vps都部署了xray、v2ray，配置如下。请问如何能实现：电脑→vps1→vps2→互联网  ，两台vps都属国外的
===========================vps1
{

    "log": {
        "loglevel": "warning"
    },
    "routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "type": "field",
                "ip": [
                    "geoip:cn",
                    "geoip:private"
                ],
                "outboundTag": "block"
            }
        ]
    },
    "inbounds": [
        {
            "port": 443,   //端口
            "protocol": "vless",  //协议类型
            "settings": {
                "clients": [
                    {
                        "id": "e8c78356-0fd0-4285-8c3d-81ab92af7627",  //替换为你的uuid
                        "flow": "xtls-rprx-vision"   //流控
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": 10010,   //Trojan协议的分流端口
                        "xver": 1
                    },
                    {
                        "path": "/vlessws",    //vless+ws的分流路径
                        "dest": 10011,      //分流端口
                        "xver": 1
                    },
                    {
                        "path": "/vmessws",   //vmess+ws的分流路径
                        "dest": 10012,    //分流端口
                        "xver": 1
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "rejectUnknownSni": true,   //服务端接收到的 SNI 与证书域名不匹配即拒绝 TLS 握手
                    "fingerprint": "chrome",    //TLS指纹伪装，伪装为chrome浏览器指纹
                    "allowInsecure": false,   //不允许不安全连接（仅用于客户端）
                    "alpn": [
                        "http/1.1","h2"
                    ],
                    "certificates": [
                        {
                            "ocspStapling": 3600,   //OCSP 装订更新，与证书热重载的时间间隔
                            "certificateFile": "/etc/ssl/private/cert.crt",   //证书位置，绝对路径
                            "keyFile": "/etc/ssl/private/private.key"   //私钥位置，绝对路径
                        }
                    ]
                }
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            }
        },
        {
            "port": 10010,   //trojan节点的分流端口
            "listen": "127.0.0.1",
            "protocol": "trojan",  
            "settings": {
                "clients": [
                    {
                        "password": "pass"  //替换为你的密码
                    }
                ],
                "fallbacks": [
                    {
                        "alpn": "h2",  //h2回落
                        "dest": 81,   //h2回落端口
                        "xver": 1
                    },
                    {
                       "dest": 82,  //http/1.1回落端口
                       "xver": 1 
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "none",
                "tcpSettings": {
                    "acceptProxyProtocol": true
                }
            }
        },
        {
            "port": 10011,   //vless+ws节点的分流端口
            "listen": "127.0.0.1",
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "9482f046-5d3a-46e1-826f-9fd52e052e16"   //替换为你的uuid
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "ws",  
                "security": "none",
                "wsSettings": {
                    "acceptProxyProtocol": true,   //若使用Nginx/Caddy等反代WS，需要删掉这行
                    "path": "/vlessws"   //ws的路径，需要和分流的一致
                }
            }
        },
        {
            "port": 10012,   //vmess+ws节点的分流端口
            "listen": "127.0.0.1",
            "protocol": "vmess",
            "settings": {
                "clients": [
                    {
                        "id": "38db3b14-e79c-4561-9745-1a97228cc80f"   //替换为你的uuid
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "security": "none",
                "wsSettings": {
                    "acceptProxyProtocol": true,   //若使用Nginx/Caddy等反代WS，需要删掉这行
                    "path": "/vmessws"   //ws的路径，需要和分流的一致
                }
            }
        }
    ], 
    "outbounds": [
        {
            "protocol": "freedom",
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "tag": "block"
        }
    ]
}
===========================vps2           doprax.com
{

	"log": {
		"access": "/dev/null",
		"error": "/dev/null",
		"loglevel": "warning"
	},
	"inbounds": [{
			"port": 10000,
			"listen": "127.0.0.1",
			"protocol": "vmess",
			"settings": {
				"clients": [{
					"id": "UUID",
					"alterId": 0
				}]
			},
			"streamSettings": {
				"network": "ws",
				"wsSettings": {
					"path": "VMESS_WSPATH"
				}
			}
		},
		{
			"port": 20000,
			"listen": "127.0.0.1",
			"protocol": "vless",
			"settings": {
				"clients": [{
					"id": "UUID"
				}],
				"decryption": "none"
			},
			"streamSettings": {
				"network": "ws",
				"wsSettings": {
					"path": "VLESS_WSPATH"
				}
			}
		}
	],
	"outbounds": [{
		"protocol": "freedom",
		"settings": {}
	}],
	"dns": {
		"server": [
			"8.8.8.8",
			"8.8.4.4",
			"localhost"
		]
	}
}

**Comment by us254** [comment]
To achieve the network flow computer → vps1 → vps2 → Internet, you can configure vps1 to forward traffic to vps2. To do this, you can modify the configuration of vps1 to include an outbound connection to vps2.

Here's an example of how to configure vps1 to forward traffic to vps2:

Edit the configuration file of vps1 and add an outbound connection to vps2. The configuration should look like this:
```
"outbounds": [
    {
        "protocol": "vmess",
        "settings": {
            "vnext": [
                {
                    "address": "vps2_ip_address",
                    "port": vps2_port,
                    "users": [
                        {
                            "id": "38db3b14-e79c-4561-9745-1a97228cc80f",
                            "alterId": 64
                        }
                    ]
                }
            ]
        },
        "streamSettings": {
            "network": "tcp",
            "security": "tls"
        },
        "tag": "proxy"
    }
]

```
Modify the routing settings of vps1 to send all traffic to the outbound connection created in step 1:

```
"routing": {
    "rules": [
        {
            "type": "field",
            "outboundTag": "proxy"
        }
    ]
}
```

This will cause all traffic to be forwarded to vps2.

**Comment by enterusernamecontinue** [comment]
如果 VPS1 在墙外的话，先给 VPS2 新增个入站：
```
{
    "inbounds": [
        {
            "port": 12345,
            "protocol": "vmess",
            "settings": {
                "clients": [
                    {
                        "id": "vps2-new-uuid",
                        "email": "pc-vps1-vps2@free.com"
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp"
            }
        }
    ]
}
```

然后给 VPS1 新增一个入站 uuid 、一个出站和一条路由规则：
```
{
    "inbounds": [
        {
            "settings": {
                "clients": [
                    {
                        "id": "vps1-new-uuid",
                        "flow": "xtls-rprx-vision",
                        "email": "pc-vps1-vps2@free.com"
                    }
                ]
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "vmess",
            "settings": {
                "vnext": [
                    {
                        "address": "vps2_ip",
                        "port": 12345,
                        "users": [
                            {
                                "id": "vps2-new-uuid"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp"
            },
            "tag": "vps2"
        }
    ],
    "routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "type": "field",
                "user": [
                    "pc-vps1-vps2@free.com"
                ],
                "outboundTag": "vps2"
            }
        ]
    }
}
```

客户端使用新 uuid 连 VPS1 。

**Comment by charley008** [comment]
我记得没错的话，客户端里面设置就好了，在出站代理 里面用proxysettings
"proxySettings": {
        "tag": "another-outbound-tag"

**Comment by zhuang1234** [comment]
我有点不太理解为何要用vps1作为一个跳板去使用vps2去连接，而且还都在国外

**Comment by Zxis233** [comment]
> 我有点不太理解为何要用vps1作为一个跳板去使用vps2去连接，而且还都在国外

落地鸡和中转鸡，可以查一下看看

**Comment by vongoethe** [comment]
这样降低效率，不如直接用dokodemo door实现
