### ISSUE TITLE
打开证书的时候提示没有权限

### ISSUE THREAD

**Issue by ponyzhou404** [XTLS/Xray-core#179]
letsencrypt的证书。
/live/domain/ 文件夹和 /archive/domain/ 文件夹下的所有文件已经用chmod 777改了权限。
但是在用systemctl status查看xray的时候还是会显示：
`Failed to start: main: failed to load config files: [/usr/local/etc/xray/config.json] > infra/conf: Failed to build TLS config. > infra/conf: failed to parse certificate > open /etc/letsencrypt/live/domain/fullchain.pem: permission denied`

有没有大佬知道是个什么情况。

**Comment by flyawayazure** [comment]
@ponyzhou404 上层目录可能没有给够权限（？），上层目录至少要有x权限才能进入

**Comment by ponyzhou404** [comment]
> @ponyzhou404 上层目录可能没有给够权限（？），上层目录至少要有x权限才能进入

惊了，原来是这样。
现在好了。
谢谢大佬。

**Comment by rprx** [comment]
可以加入文档

**Comment by badO1a5A90** [comment]
已加入文档 FAQ

**Comment by scroge** [comment]
> @ponyzhou404 上层目录可能没有给够权限（？），上层目录至少要有x权限才能进入

人家已经说明了，目录都是777了，就不是x权限的问题了。

**Comment by Tao314** [comment]
我也碰到了这个问题，解决方案应该如下
1. 把原来的安装文件夹删除
2. 重新安装，在安装命令后添加 -u root ， 完整命令如下
bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install -u root

重新安装后问题解决
