### ISSUE TITLE
[enhancement] Allow usage of environment variables in config file

### ISSUE THREAD

**Issue by Lorilandly** [XTLS/Xray-core#1791]
TLDR
`systemd`提供了专门用于传递证书给程序（程序可能本来没有权限访问证书）的一个途径`LoadCredencial=`，比手动修改权限的方式安全并简洁。然而，`systemd`的这个功能需要使用环境变量来传递证书，但`xray`的配置文件并不支持环境变量。我的建议是可以在配置文件中添加对环境变量的支持，或直接读取相对应的环境变量。例如：
```json
"certificates": [
    {
        "certificateFile": "$CREDENTIALS_DIRECTORY/fullchain",
        "keyFile": "$CREDENTIALS_DIRECTORY/privkey"
    }
]
```

正文
理想状态下，ssl证书只应该能够被root用户访问，而xray不应该拥有太多权限。xray如想使用ssl证书（需root权限），需要修改证书权限或者用`nobody`用户`chown`证书（[source](https://github.com/v2fly/fhs-install-v2ray/wiki/Insufficient-permissions-when-using-certificates)）。然而，这些方法或是存在[安全隐患](https://github.com/XTLS/Xray-install/issues/54)，或是不优雅（需添加新用户）。

`systemd`提供了一套完整的方法使得在不修改权限的情况下让进程能够访问特定的read protected files，例如`/var/log`、`/var/cache`、证书等，同时保证它不能访问任何它不应该访问的文件（[参考](https://systemd.io/CREDENTIALS/)）。但是`systemd`传证书的方式有点小尴尬，需要用到环境变量`$CREDENTIALS_DIRECTORY`。这是因为传递的这个路径是动态的，不一定是在一个能提前得知的位置。

如果现在就想使用`systemd`来传递证书，把环境变量写在配置里的话，需要在`systemd`里这样启动`xray`
```
ExecStart=/bin/sh -c '/usr/bin/envsubst < /usr/local/etc/xray/config.json | /usr/local/bin/xray'
```
显而易见的不是很好看

所以如果config能支持环境变量那是再好不过了。或者`xray`也可以直接读取这个环境变量？如果有什么别的好方法也 pls let me know!

related #206

**Comment by Fangliding** [comment]
挺好看的 就这么用吧（）
