### ISSUE TITLE
现在的版本不支持xtls-rprx-vision,none吗

### ISSUE THREAD

**Issue by fyhong** [XTLS/Xray-core#1795]
我填xtls-rprx-vision,none会报错
Failed to start: main: failed to load config files: [vle.json] > infra/conf: VLESS clients: "flow" doesn't support "xtls-rprx-vision,none" in this version

**Comment by RPRX** [comment]
v1.8.0 不支持这种写法了，只支持 `""` 或 `"xtls-rprx-none"`

顺便，Shadowrocket 2.2.25 的 Vision 对应的服务端是 Xray-core v1.7.5，[与 v1.8.0 不完全兼容](https://github.com/XTLS/Xray-core/issues/1755#issuecomment-1462355442)，建议：

- **若要用小火箭的 Vision，服务端及其它客户端暂时使用 v1.7.5，勿升级到 v1.8.0**
- 除此之外的情况，[升级到 v1.8.0 后应给 Vision 加上 REALITY，后置 Nginx 处理 TLS](https://github.com/XTLS/Xray-core/issues/1781#issuecomment-1465730056)，就没有不同版本 Vision 的兼容性问题了

**Comment by chika0801** [comment]
记下了

**Comment by fyhong** [comment]
如果不支持这样写的话，我想兼容普通 TLS 连接，是不是没办法了

**Comment by vangork** [comment]
> 除此之外的情况，https://github.com/XTLS/Xray-core/issues/1781#issuecomment-1465730056，就没有不同版本 Vision 的兼容性问题了

`除此之外`是指pc端的可以通过后置nginx处理tls消除1.7.5和1.8.0的兼容性问题么？ 说明小火箭和xray对于vision的实现有差别？
`后置nginx处理tls`是指https://github.com/chika0801/Xray-examples/tree/main/VLESS-XTLS-uTLS-REALITY/steal_yourself这里描述的偷自己么？说明偷自己和偷其他网站对于客户端用xtls vision访问有差别？
@RPRX 望解答

**Comment by chika0801** [comment]
> > 除此之外的情况，[https://github.com/XTLS/Xray-core/issues/1781#issuecomment-1465730056，就没有不同版本](https://github.com/XTLS/Xray-core/issues/1781#issuecomment-1465730056%EF%BC%8C%E5%B0%B1%E6%B2%A1%E6%9C%89%E4%B8%8D%E5%90%8C%E7%89%88%E6%9C%AC) Vision 的兼容性问题了
> 
> `除此之外`是指pc端的可以通过后置nginx处理tls消除1.7.5和1.8.0的兼容性问题么？ 说明小火箭和xray对于vision的实现有差别？ `后置nginx处理tls`是指[https://github.com/chika0801/Xray-examples/tree/main/VLESS-XTLS-uTLS-REALITY/steal_yourself这里描述的偷自己么？说明偷自己和偷其他网站对于客户端用xtls](https://github.com/chika0801/Xray-examples/tree/main/VLESS-XTLS-uTLS-REALITY/steal_yourself%E8%BF%99%E9%87%8C%E6%8F%8F%E8%BF%B0%E7%9A%84%E5%81%B7%E8%87%AA%E5%B7%B1%E4%B9%88%EF%BC%9F%E8%AF%B4%E6%98%8E%E5%81%B7%E8%87%AA%E5%B7%B1%E5%92%8C%E5%81%B7%E5%85%B6%E4%BB%96%E7%BD%91%E7%AB%99%E5%AF%B9%E4%BA%8E%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%94%A8xtls) vision访问有差别？ @RPRX 望解答

自己偷自己和你偷别人 tls 证书都不是xray处理，你偷别人 别人用nginx处理就是nginx的tls特征用的caddy就是caddy的。

你偷自己，用什么是你自己定的，这样来理解吧

**Comment by RPRX** [comment]
据说 Shadowrocket 2.2.26 TF 版已支持 Xray-core v1.8.0 的 Vision，请测试

**Comment by jh0072110** [comment]
> 据说 Shadowrocket 2.2.26 TF 版已支持 Xray-core v1.8.0 的 Vision，请测试

还是不完全兼容，访问网页没问题打不开tg🫠

**Comment by RPRX** [comment]
> > 据说 Shadowrocket 2.2.26 TF 版已支持 Xray-core v1.8.0 的 Vision，请测试
> 
> 还是不完全兼容，访问网页没问题打不开tg🫠

~~前几天群里说的，那现在有 2.2.27 TF 吗~~

**Comment by jh0072110** [comment]
> > > 据说 Shadowrocket 2.2.26 TF 版已支持 Xray-core v1.8.0 的 Vision，请测试
> > 
> > 
> > 还是不完全兼容，访问网页没问题打不开tg🫠
> 
> ~前几天群里说的，那现在有 2.2.27 TF 吗~

看起来…没有…

**Comment by EricMzky** [comment]
大佬们，我也出现这个问题了。现在是最新的xray xtsl （vless），然后小火箭也是最新的；Tele还是连接不上。。。你们怎么解决的啊？谢谢大佬们

**Comment by huazhuoxian** [comment]
V1.8.1解决这个问题了吗？
