### ISSUE TITLE
add github ci for building binaries

### ISSUE THREAD

**Issue by acc557** [XTLS/Xray-core#18]
https://github.com/v2fly/v2ray-core/blob/master/.github/workflows/release.yml

**Comment by rurirei** [comment]
#7

**Comment by rprx** [comment]
这是一开始的打算（可以看到源代码很干净），目前也有两个相关 PR #7 #16，计划在下个版本 release 后开始这项工作。

**Comment by acc557** [comment]
close as duplicate
