### ISSUE TITLE
有关于 "路由" 功能相关的询问

### ISSUE THREAD

**Issue by HtnrxUNc** [XTLS/Xray-core#1803]
提示：当前我没有遭到 xray 无法启动，崩溃，无法连接 的问题，此 issues  只是用于询问关于我所遇见的路由相关的问题
各位 xray 项目的开发者你好
我目前已经在服务器上成功的搭建了 xray 并且已经连接成功
后来我发现其他的应用基本上都可以正常连接，只有 google play 无法下载和更新应用。
我使用 google 搜索相关问题，并且尝试使用其他没有配置路由的节点之后
发现可能造成该问题的相关回复

> 在一些大陆 ROM 预置的 Google Play 服务中，会使得 Google Play 向 services.googleapis.cn 请求数据，本来应该是 services.googleapis.com。
>
> 但是这个问题并非没有解决方案，多数国外 DNS 会将这个域名指向大陆以外的 IP，而大陆 DNS 很容易把他指向一个北京的 IP（因此无法连接）

我尝试了其他的没有配置路由功能的节点，似乎成功的下载或更新（在同一个设备同一个网络，没有尝试任何的清除数据，变量只有 v2rayNG更换节点及更换节点可能导致的相关变量）

所以我同样检查了两个节点在 google 数据库中的地理位置，其中一个能够下载和更新的节点被定位于 东南亚 。而 另一个无法下载和更新的节点被定位于 美国

这是我目前使用的配置中的路由的配置

[config.txt](https://github.com/XTLS/Xray-core/files/10986634/config.txt)

请注意，如果你检查到我发布的配置存在 排版，括号的配对等问题，这可能是因为我错误的复制了多余的配置或缺少了部分配置。（再次声明，这并非原配置文件的问题，因为使用该配置的 xray 正确的运行并正常的连接）

我尝试在配置中加入了 ` "~!services.googleapis.cn",` 这与下方的 `"geoip:cn",` 存在冲突，xray是否会放行 ` "~!services.googleapis.cn",` 的流量？
当我加入 ` "~!services.googleapis.cn",` 之后，google play 依然没有成功的下载与更新，但这与我当前的提问不符，我将会自行查找答案。如果成功解决我将会回复在本 issues 下

请注意，我在服务端中的配置写入黑洞配置是有原因的，我无法控制所有的连接设备，所以我只能在服务端的配置中写入黑洞。如果有更好的方法可以回复我。但是如果是修改连接的客户端有关的方案我无法采纳，因为我无法控制所有的连接的设备。

**Comment by cross-hello** [comment]
Copy from a unknown place:
```json
"dns": {   "disableCache": true,
       "disableFallbackIfMatch": true,  
       "hosts": {
    "domain:googleapis.cn": "googleapis.com" 
  }
}

**Comment by Smoovsky** [comment]
Let's start with your config first:
```json
{
    "routing": {
        "domainStrategy": "AsIs",
        "rules": [
            {
                "type": "field",
                "inboundTag": [
                    "xtls"
                ],
                "domain": [
                    // never seen this syntax before, will this ever work?
                    // "~!services.googleapis.cn", 
                    // geoip doesn't work as a "domain" config item
                    // "geoip:cn",
                    // this rule looks fine
                    "geosite:cn"
                    // this is protocal, won't work as a "domain" config item
                    // ,"bittorrent"
                ],
                "outboundTag": "block"
            },
            {
                "type": "field",
                "inboundTag": [
                    "xtls"
                ],
                "domain": [
                    // will not work as "geosite:cn" has already been blocked above
                    "geosite:geolocation-!cn"
                ],
                "outboundTag": "proxy"
            }
        ]
    }
}
```

It should be something link:
```
{
    "routing": {
        "domainStrategy": "AsIs",
        "rules": [
            {
                "type": "field",
                "inboundTag": [
                    "xtls"
                ],
                "domain": [
                    // make sure all google related domain goes to “proxy"
                    "regexp:google"
                ],
                "outboundTag": "proxy"
            },
            {
                "type": "field",
                "inboundTag": [
                    "xtls"
                ],
                "domain": [
                    "geosite:cn"
                ],
                "outboundTag": "block"
            },
            {
                "type": "field",
                "inboundTag": [
                    "xtls"
                ],
                "ip": [
                    "geoip:cn"
                ],
                "outboundTag": "block"
            },
            {
                "type": "field",
                "inboundTag": [
                    "xtls"
                ],
                "protocol": [
                    "bittorrent"
                ],
                "outboundTag": "block"
            }
            // note you can omit this item if "proxy" is your first(default) outbound
            , {
                "type": "field",
                "inboundTag": [
                    "xtls"
                ],
                "outboundTag": "proxy"
            }
        ]
    }
}
```

Also note that if your client's routing rule is based on sniffing, then routing solely on the server side is not enough. If the client resolves a wrong IP on its side and could not make the connection in the first place, sniffing won't work either. You will have to make sure the client resolves the correct IP(using hosts or xray's dns server or configure your own dns server) or use FakeDNS in the first place.

And lastly, to gain enough confidence in one's assumption, enabling logging and seeing all requests and routing in action is always something desirable.
