### ISSUE TITLE
求 linux平台支持xtls-rprx-vision的客户端

### ISSUE THREAD

**Issue by ling9916** [XTLS/Xray-core#1806]
【系统环境】
linux x86_64架构，平铺式窗口管理器

求支持xtls-rprx-vision的客户端

**Comment by thisdk** [comment]
[Xray-linux-64.zip](https://github.com/XTLS/Xray-core/releases/download/v1.8.0/Xray-linux-64.zip)
这个满足不了你么

**Comment by ling9916** [comment]
不是这个，我想要的是类似Qv2ray带GUI的客户端

**Comment by AAlieZZ** [comment]
https://github.com/xbclub/xraya

**Comment by fannwong001** [comment]
如果只有几个节点，就用命令行启动程序，监听socks，再在GUI客户端上新建socks连接，127.0.0.1:port，如果是订阅很多节点那种还是等clash支持吧。

**Comment by zozx** [comment]
@ling9916 Clash.Meta + Yacd-meta

**Comment by iopq** [comment]
> [https://github.com/xbclub/xraya ](https://github.com/xbclub/xraya)

I packaged a module for the NUR, but I had to fork this

https://iopq.wordpress.com/2023/07/25/installing-xraya-module-pre-release-from-the-nur-on-nixos/

**Comment by Fangliding** [comment]
Not a core issue
