### ISSUE TITLE
Reality only supports port 443?

### ISSUE THREAD

**Issue by clcc2019** [XTLS/Xray-core#1807]
Reality only supports port 443?

**Comment by RPRX** [comment]
支持任何端口，建议 443

**Comment by clk01** [comment]
> 支持任何端口，建议 443

大佬你好，我443被封了，使用其他端口的话比如我reality用12345端口，servername写github.com:443，那墙是不是认为我访问的是github.com:12345？

**Comment by RPRX** [comment]
@clk01 对，建议你换个干净的 IP 再用 REALITY

**Comment by clk01** [comment]
> @clk01 对，建议你换个干净的 IP 再用 REALITY

那模拟正规网站不能用443的话是不是看起来比自建域名的其他端口的流量看起来问题更大。小站非443可能他用，SSH、NAS之类的，正规网站不会访问80和443以外吧。

**Comment by RPRX** [comment]
@clk01 这不是废话。。。

**Comment by clk01** [comment]
> @clk01 这不是废话。。。

嗯，刚才写错了servername没有端口，我以为dest中的github.com:443就是模拟成访问443了。自己用什么端口都无所谓了，是我理解错了，谢谢大佬。
