### ISSUE TITLE
Vision/shadowrocket 问题反馈

### ISSUE THREAD

**Issue by Johnny256Dawson** [XTLS/Xray-core#1808]
发现了一个问题，就是最新版1.75 xray core用vision 协议的时候，油管会卡（用了去广告插件），但是同样配置和节点，用ws tls就挺流畅，还有就是用vision 电报上传不动，用ws tls就很快；然后我服务端回退到1.7.0，发现vision 油管没那么卡了，但是又有新的卡，卡法不一样，电报上传还是没反应，同样的配置（同一个wifi，手机型号和系统，软件版本，小火箭模块配置、版本等，排除基站拥堵，无线网使用设备影响，可以假设变量只有xray version）用ws tls电报上传文件居然比1.7.5的版本的ws tls快很多，之前用流量也是这样，但是不知道是小火箭（2.2.25）适配问题，还是xray的适配问题，我都一并反馈给两个平台了，vision 近期还有除此之外的其他问题如用vision 上不了WhatsApp、vision 1.7.5 刷推特偶尔断流等，望核实
如果有其他朋友也有使用中的各种也可以一起讨论

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/issues/1795#issuecomment-1468148685

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/issues/1795#issuecomment-1474716767
