### ISSUE TITLE
"xtls-rprx-vision"配置，代理可用，但客户端返回大量错误。是什么原因？怎样优化呢？

### ISSUE THREAD

**Issue by free8jet** [XTLS/Xray-core#1809]
wsarecv: An existing connection was forcibly closed by the remote host.] > common/retry: all retry attempts failed

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/issues/1813#issuecomment-1474707067

**Comment by csryt** [comment]
@RPRX 我老早就讲了 这种吊问题来群里问 有大把客服。非得发gayhub
