### ISSUE TITLE
iptables rules error when building TPROXY with docker in a synology nas

### ISSUE THREAD

**Issue by CN1984** [XTLS/Xray-core#181]
> ~ # iptables -t mangle -A XRAY -p tcp -j TPROXY --on-port 12345 --tproxy-mark 1 
iptables v1.8.6 (legacy): unknown option "--on-port"

Docker:
[teddysun/xray](https://hub.docker.com/r/teddysun/xray)

System Infomation:
> ~ # cat /etc/os-release                                                                                                                                                                                     
NAME="Alpine Linux"                                                                                                                                                                                         
ID=alpine                                                                                                                                                                                                   
VERSION_ID=3.13.0                                                                                                                                                                                           
PRETTY_NAME="Alpine Linux v3.13"                                                                                                                                                                            
HOME_URL="https://alpinelinux.org/"                                                                                                                                                                         
BUG_REPORT_URL="https://bugs.alpinelinux.org/"

> ~ # uname -a                                                                                                                                                                                                
Linux b834b17d2726 4.4.59+ #25426 SMP PREEMPT Mon Dec 14 18:48:52 CST 2020 x86_64 Linux

> ~ # lsmod | grep iptable                                                                                                                                                                                    
iptable_mangle          1656  0                                                                                                                                                                             
iptable_nat             1959  2                                                                                                                                                                             
nf_nat_ipv4             4775  1 iptable_nat                                                                                                                                                                 
iptable_filter          1592  1                                                                                                                                                                             
ip_tables              13836  3 iptable_mangle,iptable_nat,iptable_filter                                                                                                                                   
x_tables               16046 19 xt_ipvs,xt_mark,iptable_mangle,xt_conntrack,xt_addrtype,ip6table_filter,ip6_tables,ipt_MASQUERADE,xt_REDIRECT,xt_nat,xt_recent,xt_iprange,xt_limit,xt_state,xt_tcpudp,xt_mul
tiport,xt_LOG,iptable_filter,ip_tables

**Comment by rprx** [comment]
可能 alpine 的 iptables 是阉割版？

**Comment by CN1984** [comment]
> 可能 alpine 的 iptables 是阉割版？

Ye, look like the alpine linux removed the iptables's tproxy mod. 
This docker image was found in the [document](https://xtls.github.io/links/), would you tell the author about this issue?

**Comment by rprx** [comment]
> 
> 
> > 可能 alpine 的 iptables 是阉割版？
> 
> Ye, look like the alpine linux removed the iptables's tproxy mod.
> This docker image was found in the [document](https://xtls.github.io/links/), would you tell the author about this issue?

@badO1a5A90

**Comment by badO1a5A90** [comment]
已加入文档 FAQ

**Comment by hronro** [comment]
请问 Alpine 的 iptables 不支持 tproxy 是哪里的消息？我找了半天没找到过相关的信息

**Comment by juneszh** [comment]
@hronro 
Finally found the reason is that my device system (Synology DSM) does not support iptables, not Alpine.
