### ISSUE TITLE
Failed to start: main: failed to load config files: [/etc/xray/config.json] > infra/conf: Please use VLESS flow "xtls-rprx-vision" with TLS or REALITY.

### ISSUE THREAD

**Issue by jasonbohan** [XTLS/Xray-core#1812]
Xray 1.8.0 (Xray, Penetrates Everything.) Custom (go1.20.2 linux/amd64)
A unified platform for anti-censorship.
2023/03/18 11:40:38 [Info] infra/conf/serial: Reading config: /etc/xray/config.json
Failed to start: main: failed to load config files: [/etc/xray/config.json] > infra/conf: Please use VLESS flow "xtls-rprx-vision" with TLS or REALITY.

已经在/etc/config.json 配置里再flow 那边改为了xtls-rprx-vision了。
            "settings": {
                "clients": [
                    {
                        "id": "xxxx",
                        "flow": "xtls-rprx-vision",
                        "level": 0

**Comment by RPRX** [comment]
配置的 security 需改成 tls 或 reality

**Comment by Merdan-Kurbanov** [comment]
hello i have a same problem .how to solve this ?

**Comment by ToorajValaee** [comment]
It's because there was a client with xtls valued xtls-rprx-direct

to fix it, just edit your clients and make not in xtls, if xtls is off, then turn it on, change it to not and then you can turn it off again

**Comment by xworks** [comment]
change flow to "xtls-rprx-vision"

……
{
"id": "xxxx",
"flow": "xtls-rprx-vision",
"level": 0
}
……

also, change security to "tls"

……
      "security": "tls",
……
