### ISSUE TITLE
Xray vless+h2 server verifies "www.example.com"  in the host and the other cores cannot connect

### ISSUE THREAD

**Issue by amirhosss** [XTLS/Xray-core#1817]
I checked the logs of both sing-box and xray clients when they're trying to connect to the xray vless+h2 server with caddy frontend and found that if the host value on client side is empty, the **xray client** sends **"www.example.com"** in the host of http2 and the xray server **will verify** it but in **sing-box case**, it sends the **ip address value** of outbound and the xray server **does not verify** it.

Could you please check https://github.com/XTLS/Xray-core/blob/main/transport/internet/http/config.go ?

**Comment by chika0801** [comment]
https://github.com/SagerNet/sing-box/issues/444

https://github.com/SagerNet/sing-box/issues/412

https://github.com/SagerNet/sing-box/issues/441

与它们有关的ISS。

**Comment by chika0801** [comment]
已解决 https://github.com/SagerNet/sing-box/commit/aea02c074e42d7c64863c4fe83239e21dd3c856e

**Comment by amirhosss** [comment]
You sure? i checked the commit and they added "www.example.com"

**Comment by amirhosss** [comment]
> [SagerNet/sing-box@aea02c0](https://github.com/SagerNet/sing-box/commit/aea02c074e42d7c64863c4fe83239e21dd3c856e)
> 
> I tested it and it was not fixed

You sure? i checked the commit and they added "www.example.com"

**Comment by chika0801** [comment]
I tested it again and it's fixed
