### ISSUE TITLE
关于REALITY一些疑问

### ISSUE THREAD

**Issue by tou-7** [XTLS/Xray-core#1818]
疑问:
1.如何找到适合自己的"serverNames"列表
2.当REALITY成熟,大量运用,一键脚本,网上各类模板!可能大量使用一样"serverNames"列表,是否影响
想法:
1.能否,取消服务端"serverNames"列表,由客户端设置就可以(跟uTLS一样)
(就算"serverNames"列表网站失效,不用进入vps修改)
(每次连接,服务端验证网站,不合乎终止连接)
2.能否像类似geoip.dat,geosite.dat文件!提供可靠,随机的网站
(在配置根据自己的vps机房或区域设置,文件随机提供可靠低延迟网站)

**Comment by Fangliding** [comment]
@tou-7 1 客户端设置绝对是不行的(那会被扫走当代理的)
2

**Comment by chika0801** [comment]
1，有个扫描工具，输入你vps的ip扫。或你直接用你vps商家的网址

2，大规模不会的，个人自建党用多，自建的人又是比例小的怎么找冷门网站又好的条件就是自己的事了。你实在不想申请个证书自己偷自己得了

**Comment by RPRX** [comment]
1. https://github.com/XTLS/RealiTLScanner
2. 不妥，~~理由太多，懒得说了~~
