### ISSUE TITLE
增加 dns over tls （DOT）功能

### ISSUE THREAD

**Issue by architecturers** [XTLS/Xray-core#1819]
dns over quic 秒限流
dns over http 三次握手 折腾回来 dns请求基本失败 一堆报错
sing-box的 dns over tls 效果很好 
希望能够增加此功能

**Comment by Fangliding** [comment]
@architecturers 难道没有吗(惊恐)

**Comment by Fangliding** [comment]
@Fangliding 嗯。xray的dot好像是dns over tcp 不过用doh不就行了()

**Comment by offferu** [comment]
支付！顺便把doh3也支持了，
h3://unfiltered.adguard-dns.com/dns-query
h3://dns.google/dns-query

**Comment by rurirei** [comment]
dns over quic?


> 支持！顺便把doh3也支持了， h3://unfiltered.adguard-dns.com/dns-query h3://dns.google/dns-query

**Comment by rurirei** [comment]
almost not necessary to use a dns over tls server.

**Comment by rurirei** [comment]
but could be done by uses a tls conn simply here.
```go
conn, err = tls.Client(conn, address.Domain())
```
https://github.com/XTLS/Xray-core/blob/d9af02812f22aad5d415fb0b01b855d21c2d1078/app/dns/nameserver_tcp.go#L221

**Comment by RPRX** [comment]
DNS over TLS 对我们来说意义不大，对于客户端，853 端口过于独特，所以 DoH 更好，还能复用连接
如果你那里遇到了问题，应该看是不是自己没配好，或者修 DoH 的实现

对于两端，对于任何 DNS 加密，最终很少有 ECH，可以避免篡改，但无法避免审计。如果想本地解析然后走代理，不如远端解析
