### ISSUE TITLE
用xray 1.8.0的香港vps已被墙

### ISSUE THREAD

**Issue by foramsxx** [XTLS/Xray-core#1820]
服务端配置参考的这个：   
https://github.com/XTLS/REALITY/blob/0d0713b108c8451d9a40fdbc3cb279681bcc1203/README.md?plain=1#L14

客户端用的最新的passwall 

vps在香港，完全自己使用，目前国内已ping不通

reality被墙的原因还不清楚, 之前用的vision没被墙

**Comment by RPRX** [comment]
Won't fix

**Comment by RPRX** [comment]
我还是说一下这个 issue 的问题在哪：

1. 提供的信息太少，比如目标域名是什么、有没有禁回国流量等，都没有说，这里不算命，参考 https://github.com/XTLS/Xray-core/issues/1813#issuecomment-1474707067
2. REALITY 目前没有大规模被封报告，解决孤例被封问题的投入回报比太低，建议直接换 IP，参考 https://github.com/XTLS/Xray-core/issues/1544#issuecomment-1402118517
3. ~~你知道 Hong Kong 的数据，Mainland 随时可以依法调取吧，如果你用的是阿里云腾讯云什么的就更。。。~~

Hong Kong 是近，延迟是低，只是和裸奔没区别。

**Comment by foramsxx** [comment]
感谢回复， 希望我只是个例，后面我会再用其他国家节点试一试^_^

**Comment by hubmusk** [comment]
> 我还是说一下这个 issue 的问题在哪：
> 
> 1. 提供的信息太少，比如目标域名是什么、有没有禁回国流量等，都没有说，这里不算命，参考 [vision reality connection is quite weak. Easy to lose connection. #1813 (comment)](https://github.com/XTLS/Xray-core/issues/1813#issuecomment-1474707067)
> 2. REALITY 目前没有大规模被封报告，解决孤例被封问题的投入回报比太低，建议直接换 IP，参考 [Vision流控这两天也开始封端口了，流量特征可能已被识别 #1544 (comment)](https://github.com/XTLS/Xray-core/issues/1544#issuecomment-1402118517)
> 3. ~你知道 Hong Kong 的数据，Mainland 随时可以依法调取吧，如果你用的是阿里云腾讯云什么的就更。。。~
> 
> Hong Kong 是近，延迟是低，只是和裸奔没区别。

完了，我用的亚马逊Hong Kong VPS，我还以为很安全呢。。。
