### ISSUE TITLE
inboud from another network adapter

### ISSUE THREAD

**Issue by abbaszahiri** [XTLS/Xray-core#1822]
I made a home VPN server on a raspberry pi which works great on its wired network adapter (actually as a bridge to my main VPN server in abroad). 

Now I need to have inbound traffic from its wireless adapter! 
I can connect to that by softwares like SocksDroid or other proxy clients but my TV doesn't support any VPN or proxy. Can I solve this problem by a tun driver? how can I?! 

In another word, I need to have my IP located in abroad just by getting connected to server's wireless adapter and without using an extra proxy client. How can I solve that in server side?

Previously, I had an Outline client came with a tun/tap driver shared on wireless adapter. but now with Xray, I just have a user level proxy server! that doesn't respond all my needs.

**Comment by abbaszahiri** [comment]
I'm still waiting ...

**Comment by Fangliding** [comment]
Coming sooooooon(I'm not sure)
