### ISSUE TITLE
I want to ask for sample configuration, grpc reality. Thank you

### ISSUE THREAD

**Issue by Thaomtam** [XTLS/Xray-core#1827]

**Comment by Fangliding** [comment]
@Thaomtam https://github.com/chika0801/Xray-examples/tree/main/VLESS-XTLS-uTLS-REALITY

**Comment by Fangliding** [comment]
@Fangliding 搞错了 是这个
https://github.com/chika0801/Xray-examples/tree/main/VLESS-gRPC-uTLS-REALITY

**Comment by Thaomtam** [comment]
> @Fangliding 搞错了 是这个
> https://github.com/chika0801/Xray-examples/tree/main/VLESS-gRPC-uTLS-REALITY
I tried, no connection

**Comment by Thaomtam** [comment]
> @Fangliding 搞错了 是这个
> https://github.com/chika0801/Xray-examples/tree/main/VLESS-gRPC-uTLS-REALITY
I tried, no connection

**Comment by Thaomtam** [comment]
> I just tested gRPC with REALITY and with the configuration above. 
> 
> It works fine. 
> 
> If you want to copy my test procedure, it is on my blog at https://cscot.pages.dev/2023/03/21/Testing%20gRPC%20H2%20on%20Xray%20REALITY/

after testing. I found that h2 has better speed and latency than grpc

**Comment by Thaomtam** [comment]
> I just tested gRPC with REALITY and with the configuration above. 
> 
> It works fine. 
> 
> If you want to copy my test procedure, it is on my blog at https://cscot.pages.dev/2023/03/21/Testing%20gRPC%20H2%20on%20Xray%20REALITY/

after testing. I found that h2 has better speed and latency than grpc
