### ISSUE TITLE
Can't use all speed

### ISSUE THREAD

**Issue by Doxestic** [XTLS/Xray-core#1828]
Hello there
I have xray on a linux server with speed of 40MBps(byte not bit) but when i connect using on of client my ping is 400+ and download speed is so low
Why can't i use all of the linux speed and how to fix this?

**Comment by chika0801** [comment]
你的地点，到你的VPS，是不是 网络线路 质量不太好造成的 ping 400+，以及达不到你说的 40Mbps 的速度。
