### ISSUE TITLE
iOS Shadowrocket 分享节点时无法正确处理 XTLS-RPRX-Vision，导入后会变成 XTLS-RPRX-Direct

### ISSUE THREAD

**Issue by armstrongchen** [XTLS/Xray-core#1831]
也许在这里说此事不太适合，但是我没有找到 Shadowrocket 的反馈渠道。

当我手动添加 XTLS-RPRX-Vision 的节点到小火箭（Shadowrocket），然后导出分享地址，再导入刚才导出的分享地址，XTLS-RPRX-Vision 会自动变成 XTLS-RPRX-Direct。

请问应该怎么解决这个问题？

**Comment by apmfly** [comment]
手动改一下就好

**Comment by ZhuangJiayu** [comment]
shadowrocket 用 vision 有没有遇到 telegram 连不上的情况

**Comment by chika0801** [comment]
> Shadowrocket

 Shadowrocket 有TG群，好像你找下有作者邮箱，发EMAIL也能报BUG

**Comment by SakuraSakuraSakuraChan** [comment]
@ZhuangJiayu 服务端用1.7.5试试

**Comment by ZhuangJiayu** [comment]
> @ZhuangJiayu 服务端用1.7.5试试

感谢，我晚上试一下

**Comment by chika0801** [comment]
> shadowrocket 用 vision 有没有遇到 telegram 连不上的情况

❗Shadowrocket 2.2.25 的 Vision 对应的服务端是 Xray-core v1.7.5，与 https://github.com/XTLS/Xray-core/issues/1755#issuecomment-1462355442，建议：

若要用小火箭的 Vision，服务端及其它客户端暂时使用 v1.7.5，勿升级到 v1.8.0

**Comment by armstrongchen** [comment]
好的，我去找找作者的邮箱。

**Comment by armstrongchen** [comment]
昨天下午作者已经在测试版中修复了这个 Bug。
