### ISSUE TITLE
有部分网站总是报protocol error

### ISSUE THREAD

**Issue by GreatMichaelLee** [XTLS/Xray-core#1833]
我用的是www.ebay.com做dest和serverName, 但是访问个别网站时总会报protocol error,比如香港政府网站，不知是何原因

但访问谷歌，油管，小鸟又完全正常。去掉代理访问www.gov.hk也正常。

![image](https://user-images.githubusercontent.com/20067401/226323971-d71abdcb-50ff-46a8-90e5-7a969f8cd32f.png)

**Comment by RPRX** [comment]
~~不发配置不发日志~~

**Comment by chika0801** [comment]
> ~不发配置不发日志~

发图不发种，菊花被人？

**Comment by Lather0519** [comment]
試試這個：進入(edge or chrome)://net-internals/#hsts
把dest的網址輸入到```
Delete domain security policies
Input a domain name to delete its dynamic HSTS policy. (You cannot delete preloaded entries.):

Domain: 
example.com
```
點delete。
再輸入到
```
Query HSTS/PKP domain
Input a domain name to query the current HSTS/PKP set:

Domain: 
example.com
 
```
點query

**Comment by chika0801** [comment]
开玩笑一下

**Comment by GreatMichaelLee** [comment]
> 試試這個：進入(edge or chrome)://net-internals/#hsts 把dest的網址輸入到
> 
> ```
> Delete domain security policies
> Input a domain name to delete its dynamic HSTS policy. (You cannot delete preloaded entries.):
> 
> Domain: 
> example.com
> ```
> 
> 點delete。顯示已刪除。 再輸入到
> 
> ```
> Query HSTS/PKP domain
> Input a domain name to query the current HSTS/PKP set:
> 
> Domain: 
> example.com
>  
> ```
> 
> 點query。顯示沒找到即可。

![image](https://user-images.githubusercontent.com/20067401/226330918-0740730e-4391-4910-83b8-142a7ef101f8.png)

**Comment by GreatMichaelLee** [comment]
我觉得跟网站有关系，但也说不上来和协议是否有关系，我打开Info.gov.hk没问题，但打开www.gov.hk就是报这个错，你们的能行吗，是不是跟网站tls证书有关系？

![image](https://user-images.githubusercontent.com/20067401/226331615-dcb3c386-e29e-48f8-8441-efef3fa66c8a.png)
![image](https://user-images.githubusercontent.com/20067401/226331752-8756f153-f6f1-4bec-a6cb-7fbe36b8c01e.png)

**Comment by Lather0519** [comment]
> > 試試這個：進入(edge or chrome)://net-internals/#hsts 把dest的網址輸入到
> > ```
> > Delete domain security policies
> > Input a domain name to delete its dynamic HSTS policy. (You cannot delete preloaded entries.):
> > 
> > Domain: 
> > example.com
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 點delete。顯示已刪除。 再輸入到
> > ```
> > Query HSTS/PKP domain
> > Input a domain name to query the current HSTS/PKP set:
> > 
> > Domain: 
> > example.com
> >  
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 點query。顯示沒找到即可。
> 
> ![image](https://user-images.githubusercontent.com/20067401/226330918-0740730e-4391-4910-83b8-142a7ef101f8.png) 然后还是一样。

你輸ebay幹什麼？

**Comment by GreatMichaelLee** [comment]
> > > 試試這個：進入(edge or chrome)://net-internals/#hsts 把dest的網址輸入到
> > > ```
> > > Delete domain security policies
> > > Input a domain name to delete its dynamic HSTS policy. (You cannot delete preloaded entries.):
> > > 
> > > Domain: 
> > > example.com
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 點delete。顯示已刪除。 再輸入到
> > > ```
> > > Query HSTS/PKP domain
> > > Input a domain name to query the current HSTS/PKP set:
> > > 
> > > Domain: 
> > > example.com
> > >  
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 點query。顯示沒找到即可。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/20067401/226330918-0740730e-4391-4910-83b8-142a7ef101f8.png) 然后还是一样。
> 
> 你輸ebay幹什麼？

我reality配的dest就是www.ebay.com啊....www.hk.gov也试了，一样，不管用。

**Comment by RPRX** [comment]
> 不是我不想发啊，老板们，主要是隐私信息mask烦，日志里有太多ip要处理，挺烦的，批量也烦。配置也是，要处理uuid, key等等，配置很普通了，就是一个reality出站，routing几个分流，入站一个socks, 没有dns模块，没搞什么特别花样

理解不能，你想让我们帮你解决问题，你还嫌麻烦，不发配置不发日志，意思是就该我们花宝贵的时间帮你算命吗，我给过机会了

这类 issue 以后真的要直接 Close as not planned，~~不要手下留情~~ https://github.com/XTLS/Xray-core/issues/1813#issuecomment-1474707067

**Comment by GreatMichaelLee** [comment]
OK.

**Comment by RPRX** [comment]
你要理解，我们不知道你怎么配的，只能靠猜，是 Vision 还是 H2 还是 gRPC，是不是路由配错了，之类的，~~这不就开始算命了吗~~

**Comment by GreatMichaelLee** [comment]
客户端debug日志
[log.txt](https://github.com/XTLS/Xray-core/files/11017678/log.txt)

**Comment by RPRX** [comment]
~~那啥，hello.sessionId 和 uConn.AuthKey 是要码掉的~~

**Comment by RPRX** [comment]
发一下服务端的日志

**Comment by GreatMichaelLee** [comment]
[log.txt](https://github.com/XTLS/Xray-core/files/11017790/log.txt)
客户端的，mask搞死我了，老板。。。。服务端的晚点，没同时开debug

**Comment by RPRX** [comment]
你发的第一个日志我就看到了客户端没问题，你删掉吧

~~此外我要把 Show 打开时输出的密文 SessionID 删掉，AuthKey 只留一半~~
