### ISSUE TITLE
1.80 Vision/Reality 使用奈飞解锁服务， 速度无法上去

### ISSUE THREAD

**Issue by ibinlike** [XTLS/Xray-core#1834]
场景：
电信， Openwrt Passwall最新版本， xray 版本： 1.80
服务器： 新加坡 AWS LS， xray 版本： 1.80

服务器配置： 参考Chika的Vision和Reality配置。 增加了DNS 分流配置， 普通域名是到1.1.1.1去解析； 奈飞去解锁服务器那边去解析。 

状况: 能正常上网， 但是奈飞的的速度非常慢， 平均速度大概只有10Mb左右， 导致视频很模糊。 同样的节点在1.75的时候没有这个问题， 速度在36Mb左右（由于passwall xray 已经升级到1.80， 1.75和1.80的兼容性问题， 所以也就把服务器端升级到1.80）， 同样如果现在使用Hy也没有问题。 

以下是Vision服务器的部分配置以及debug 信息：
![debug](https://user-images.githubusercontent.com/12690686/226341768-32b46715-a858-4cbf-9e74-63881a9b3e95.jpg)
![outbound config](https://user-images.githubusercontent.com/12690686/226341780-505e76dc-ed91-42af-bc96-090d763d5f56.jpg)
![inbounds config](https://user-images.githubusercontent.com/12690686/226341785-09c0fa9f-c2f5-438c-a034-af2d7581e932.jpg)
![dns config](https://user-images.githubusercontent.com/12690686/226341788-adf1f2ff-af7d-46d3-9013-c9a22e77b0ab.jpg)

还请帮忙看看， 到底是什么问题。 谢谢。

**Comment by chika0801** [comment]
路由 部分你写了内容吗，有的话发下截图。

或先把出站部分的 UseIP改成 UseIPv4这个试试看。

好久看到有人用dns分流解nf了。你试试看了来。

**Comment by ibinlike** [comment]
路由部分的配置如下， 我刚把UseIP改成了UseIPv4. 速度仍然上不去。 我可以再观察一下。 

![routing](https://user-images.githubusercontent.com/12690686/226344194-044ed6f8-df5c-4cdf-9481-3f174a84d53b.jpg)

**Comment by ilafz** [comment]
passwall xray core 1.8.0  我遇到的问题是 使用一天之后所有流量都会走代理 分流自动失效 需要重新应用一次

**Comment by ibinlike** [comment]
> passwall xray core 1.8.0 我遇到的问题是 使用一天之后所有流量都会走代理 分流自动失效 需要重新应用一次

我设置的是全局代理， 由Xray来分流。 分流是成功的， 因为那个服务器同时走TG和奈飞流量， 看日志是分流成功了的。

**Comment by chika0801** [comment]
你现在的问题是路由器用passwall透明代理，你有比如亚马逊电视棒，在上面看NF很慢。

你找个电脑接到这路由器下，去看NF网页版慢不慢。思路是做对比测试。

你还可以在换成ssrp+，再来测试。排除法嘛。原因只能你这样一步步查了。

**Comment by ilafz** [comment]
> > passwall xray core 1.8.0 我遇到的问题是 使用一天之后所有流量都会走代理 分流自动失效 需要重新应用一次
> 
> 我设置的是全局代理， 由Xray来分流。 分流是成功的， 因为那个服务器同时走TG和奈飞流量， 看日志是分流成功了的。

是passwall规则管理那个吗 用geoip:cn 来分流 我试了但是无法代理 而且必须要开高级设置里的流量嗅探 屏蔽udp quic 才能正常使用

**Comment by ibinlike** [comment]
再更新一下今天测测试内容：AWS LS使用了静态地址绑定到VPS的。 在传输过程中， 有规律的出现以下写错误。  

是因为中间有IP映射， 所以在传输过程中， 无法在私有地址和宽带公有地址直接传输吗？

![Xnip2023-03-23_20-30-44](https://user-images.githubusercontent.com/12690686/227205125-6b4116a7-8d18-4680-b3c8-c2f3040696aa.jpg)

**Comment by wy580477** [comment]
> 再更新一下今天测测试内容：AWS LS使用了静态地址绑定到VPS的。 在传输过程中， 有规律的出现以下写错误。
> 
> BWG CN2和欧洲的CN2是没有这个静态地址映射的设置， 所以怀疑是因为这个原因导致了Reality进行传输过程中， 老是被reset， 速度就被拉下来了。
> 
> ![Xnip2023-03-23_20-30-44](https://user-images.githubusercontent.com/12690686/227205125-6b4116a7-8d18-4680-b3c8-c2f3040696aa.jpg)

不要怀疑AWS的网络结构，头部大厂不会有这种低级问题。找其它原因吧。

**Comment by chika0801** [comment]
建议不用aws的机好了，你好回程线路机上没遇到类似问题。

你折腾这aws机也是费你时间呀。 aws，甲骨文机总有群友反馈各种莫名问题。

**Comment by ibinlike** [comment]
> 建议不用aws的机好了，你好回程线路机上没遇到类似问题。
> 
> 你折腾这aws机也是费你时间呀。 aws，甲骨文机总有群友反馈各种莫名问题。

哈哈哈哈， 我找到问题了。 Dest那个地方， 

我用的是learn.microsoft.com. 不知道啥原因， 在AWS LS上， 就出问题了。 

我换了一个SG的网站， 速度就正常了。 
![Xnip2023-03-24_09-48-49](https://user-images.githubusercontent.com/12690686/227404132-79889c31-629f-478f-b105-c3fde3c7d726.jpg)
