### ISSUE TITLE
Reality 需要重新 xray x25519 配置private和public码

### ISSUE THREAD

**Issue by xcf13363175** [XTLS/Xray-core#1835]
服务端：debian amd64 xray 1.8.0 使用https://github.com/chika0801/Xray-examples/tree/main/VLESS-XTLS-uTLS-REALITY 自己偷自己模板
客户端：OpenWrt SSRP xray 1.8.0

配置成功并且回流道本地的8080端口的网页，使用一切正常。大概3天连不上外网，域名可以正常回流到本地的网页，重新配置private和public码可以代理上网。

**Comment by xcf13363175** [comment]
第二次出现

**Comment by xcf13363175** [comment]
https://github.com/XTLS/Xray-core/issues/1834#issuecomment-1477264053
和passwall现象还不一样，重启客户端和服务端没用，只能重新配置。

**Comment by chika0801** [comment]
vps商家是什么？

**Comment by xcf13363175** [comment]
> vps商家是什么？

cloudsilk 日本 CMI 线路

**Comment by chika0801** [comment]
你更换其它好回程线路（对你）商家的vps，用同一协议组合，测试。

当出现现象时，观察下，比如宽带电信出现了，同。时间点，电信5g能复现不。或联通5g能复现不。

最近类似现象都有人反映，原因不清楚。

**Comment by xcf13363175** [comment]
感谢回复，再测试一下到群里反馈。

**Comment by RPRX** [comment]
> 重新配置private和public码可以代理上网。
> 只能重新配置。

这显然是不可能的。

**Comment by lxhao61** [comment]
> [xcf13363175](/xcf13363175)



> 服务端：debian amd64 xray 1.8.0 使用https://github.com/chika0801/Xray-examples/tree/main/VLESS-XTLS-uTLS-REALITY 自己偷自己模板 客户端：OpenWrt SSRP xray 1.8.0
> 
> 配置成功并且回流道本地的8080端口的网页，使用一切正常。大概3天连不上外网，域名可以正常回流到本地的网页，重新配置private和public码可以代理上网。

检查

**Comment by lxhao61** [comment]
> 服务端：debian amd64 xray 1.8.0 使用https://github.com/chika0801/Xray-examples/tree/main/VLESS-XTLS-uTLS-REALITY 自己偷自己模板 客户端：OpenWrt SSRP xray 1.8.0
> 
> 配置成功并且回流道本地的8080端口的网页，使用一切正常。大概3天连不上外网，域名可以正常回流到本地的网页，重新配置private和public码可以代理上网。

1、建议检查一下Nginx是否支持TLSv1.3，TLSv1.3需使用版本不小于1.1.1的OpenSSL库编译才支持。
2、建议直接Nginx中配置一个伪装网站，不要用Nginx反代到其它网站。
符合如上再试一试。

**Comment by xcf13363175** [comment]
> 1、建议检查一下Nginx是否支持TLSv1.3，TLSv1.3需使用版本不小于1.1.1的OpenSSL库编译才支持。
2、建议直接Nginx中配置一个伪装网站（HTTP/2），不要用Nginx反代到其它网站（HTTPS）。

偷的是自己的网页，符合上面的2点。可能是个例，先关闭issue了。

**Comment by Alirazi1976123** [comment]
F

در تاریخ پنجشنبه ۲۳ مارس ۲۰۲۳،‏ ۰۸:۱۶ RPRX ***@***.***> نوشت:
