### ISSUE TITLE
Usage of environment

### ISSUE THREAD

**Issue by iran-free-net** [XTLS/Xray-core#1837]
Hello
Sorry, but I couldn't find anything about how can I set environment variables!
I'm talking about these variables:

1) The resource file path: Name: or .xray.location.assetXRAY_LOCATION_ASSET
2) Configuration file location: Name: or .xray.location.configXRAY_LOCATION_CONFIG
3) Multi-configuration directory: Name: or .xray.location.confdirXRAY_LOCATION_CONFDIR

so confused how to setup and use them for xray. can you please help me about it?

**Comment by Fangliding** [comment]
export xxx=xxx
