### ISSUE TITLE
使用vision导致apt-get异常

### ISSUE THREAD

**Issue by ZqinKing** [XTLS/Xray-core#1840]
更新成vision协议后PVE更新出现异常，关闭代理即恢复正常。
W: GPG error: http://ftp.debian.org/debian bullseye InRelease: Splitting up /var/lib/apt/lists/partial/ftp.debian.org_debian_dists_bullseye_InRelease into data and signature failed
E: The repository 'http://ftp.debian.org/debian bullseye InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://security.debian.org bullseye-security InRelease: Splitting up /var/lib/apt/lists/partial/security.debian.org_dists_bullseye-security_InRelease into data and signature failed
E: The repository 'http://security.debian.org bullseye-security InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://ftp.debian.org/debian bullseye-updates InRelease: Splitting up /var/lib/apt/lists/partial/ftp.debian.org_debian_dists_bullseye-updates_InRelease into data and signature failed
E: The repository 'http://ftp.debian.org/debian bullseye-updates InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by chika0801** [comment]
我用xshell 代理设置用本机http端口进xray，xray用vision连接到vps，没遇到你的现象

**Comment by ZqinKing** [comment]
> 我用xshell 代理设置用本机http端口进xray，xray用vision连接到vps，没遇到你的现象

那我换回老版本试试，确认一下是不是服务器网络本身问题

**Comment by ZqinKing** [comment]
> 我用xshell 代理设置用本机http端口进xray，xray用vision连接到vps，没遇到你的现象

测试了一遍，老版本的xtls没问题，新版的vision使用https的源也没问题。就是默认的http源会出异常。

**Comment by chika0801** [comment]
http https源操具体什么命令？我回头测试下

**Comment by ZqinKing** [comment]
就是apt的源从http切到https上，使用vision就没问题。

在 2023年3月22日，10:59，chika0801 ***@***.***> 写道：

﻿

http https源操具体什么命令？我回头测试下

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/issues/1795#issuecomment-1468148685

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/issues/1755#issuecomment-1462355442

**Comment by ZqinKing** [comment]
> [#1795 (comment)](https://github.com/XTLS/Xray-core/issues/1795#issuecomment-1468148685)

感谢，是服务端单独升级到了1.8.0现在已退回1.7.5，已经没有问题了。

**Comment by chika0801** [comment]
好奇你客户端代理用的什么程序？xray core版本是？

**Comment by RPRX** [comment]
虽然他没说版本，~~但是这个命比较好算~~

@chika0801 顺便给 Xray-core 弄个 issue 模板吧，天天算命，麻了

**Comment by RPRX** [comment]
@ZqinKing 其实你发这个 issue 就应该说一下客户端、服务端的版本，现在很多人都知道 v1.8.0 和 v1.7.5 的 Vision 不兼容了

**Comment by chika0801** [comment]
> @chika0801 顺便给 Xray-core 弄个 issue 模板吧，天天算命，麻了

我是真不会弄 2333

**Comment by RPRX** [comment]
今天上午我还看到群里有位 epyc 的发言，“vision现在确实还有很多异常 github issue区有好多”，然后拿这个 issue 举例，“这个诺”

多少有点问题

虽然我说要专注于模板、文章，不回 issue，但这种 issue 真的是不能放着不管，心累，而这又是由于没写 release note 造成的，艹

**Comment by ZqinKing** [comment]
> 

用的1.7.5忘记升级了。

**Comment by ZqinKing** [comment]
> 

不好意思，下次注意。主要是因为client点比较多，经常有client、server版本不一致的情况，从xtls-tcp开始一直在用都能正常用，也是近期才切到的vision协议上，所以没往版本不一致的问题上想。

**Comment by RPRX** [comment]
没关系，我只是吐槽一下现在的节奏不对，等下我给开 issue 加个 notice，~~以后就不用算命了~~
