### ISSUE TITLE
Vision v1.8.0 和 v1.7.5 代理非 TLS 时不兼容，won't fix，请同步更新版本，小火箭是 Vision v1.7.5，服务端勿升级到 v1.8.0，Vision v1.8.0 和 v1.7.5 代理非 TLS 时不兼容，Vision v1.8.0 和 v1.7.5 代理非 TLS 时不兼容，重要的事情说三遍

### ISSUE THREAD

**Issue by RPRX** [XTLS/Xray-core#1843]
**如题，日经 issue，回复麻了，v1.8.0 的 release note 等写完文章后才会写，所以先开个 issue 单独把这个说明 pin 起来**

其实我是想服务端兼容的，@yuhan6665 的意思是能用 TLS 就能更新到新版，也是合理的，~~但是相关 issue 我已经处理到快吐了~~

**Clash.Meta 和 sing-box 的 Vision 是 v1.8.0 的，小火箭的 Vision 是 v1.7.5 的，解决办法见 https://github.com/XTLS/Xray-core/issues/1795#issuecomment-1468148685**

**Comment by RPRX** [comment]
至于为什么会不兼容，是因为 Vision 最初只 padding 了内层 TLS Client Hello、Server Hello 等，而 v1.8.0 实现了 https://github.com/XTLS/Xray-core/pull/1610#issuecomment-1418546068

**因为内层协议头的长度特征很容易被用来识别，所以对于非 TLS 流量，包括服务端先发包的流量，我们也要加一些 padding**

此外我在写 REALITY 时发现对于内层 TLS 流量只 padding 两三个包还是不够，必须再处理几个包，这个还会有调整，兼容 v1.8.0

**Comment by Ght55** [comment]
Pls new update 
Very good app
New core update fast connection  
Pls fast test connection 
Pls buffering update 
Fix bug
✅️
