### ISSUE TITLE
Looking for subscription solution for Xray

### ISSUE THREAD

**Issue by arashammm** [XTLS/Xray-core#1845]
I'm looking for a subscription system to add mutliple xray servers and clients choose which server to use. Something like v2ray subscription in Clash App.

Can anyone guide me how to do that?
Is there any code available for xray to do this job?

**Comment by xqzr** [comment]
https://t.me/projectXray/1707345

**Comment by arashammm** [comment]
> xray -c config.json -c https://********.xyz/out.json
> 入站由本地（自己）定义；出站由远端（机场）定义

i'm sorry but I didn't quite get that.
How xray core has subsptiption function?

can you explain more?

**Comment by iran-free-net** [comment]
For subscription purpose you should write your own
it's not so complicated, just find how you able to create share link (I mean something like vless://uuiduuid-uuid-uuid-uuid-uuiduuiduuid:port@...) and put it somewhere in your web server and let your users fetch in type of simple text format.
also remember to for some clients you just able to use only basecode 64 format and others in simple format

**Comment by arashammm** [comment]
> For subscription purpose you should write your own it's not so complicated, just find how you able to create share link (I mean something like vless://uuiduuid-uuid-uuid-uuid-uuiduuiduuid:port@...) and put it somewhere in your web server and let your users fetch in type of simple text format. also remember to for some clients you just able to use only basecode 64 format and others in simple format

yes I'm aware of writing a python or bash code to serve the file to clients. but My question is what format should the dynamic link would be provided to clients? I mean in gui apps like FairVPN, Oneclick, V2rayN etc...

**Comment by us254** [comment]
https://t.me/xenstarp/15099

https://t.me/xenstarp/15879
