### ISSUE TITLE
经测试，1.8.0版本使用vision 时telegram 无法联网，YouTube 客户端时而无法连网［通过浏览器访问（无此步骤客户端始终不能联网）YouTube 域名正常，随之客户端正常］，1.7.5无此问题，核实为服务端dns问题，错误日志如下，请测试1.8.0dns模块适配性或其他问题

### ISSUE THREAD

**Issue by Johnny256Dawson** [XTLS/Xray-core#1846]
xray_log$ tail -f error.log 
2023/02/14 03:40:34 [Error] app/dns: failed to retrieve response for rr3---sn-a5meknsy.googlevideo.com. > Post "https://1.1.1.1/dns-query": context canceled
2023/02/14 03:40:34 [Error] app/dns: failed to retrieve response for rr3---sn-a5meknsy.googlevideo.com. > Post "https://1.1.1.1/dns-query": context canceled
2023/02/14 03:45:46 [Error] app/dns: failed to retrieve response for encrypted-tbn0.gstatic.com. > Post "https://1.1.1.1/dns-query": context canceled
2023/02/14 03:45:46 [Error] app/dns: failed to retrieve response for encrypted-tbn0.gstatic.com. > Post "https://1.1.1.1/dns-query": context canceled
2023/02/14 09:13:07 [Error] app/dns: failed to retrieve response for cdn.ampproject.org. > Post "https://1.1.1.1/dns-query": context canceled
2023/02/14 09:13:07 [Error] app/dns: failed to retrieve response for cdn.ampproject.org. > Post "https://1.1.1.1/dns-query": context canceled
2023/02/14 22:07:49 [Error] app/dns: failed to retrieve response for cdn.ampproject.org. > Post "https://1.1.1.1/dns-query": context canceled
2023/02/14 22:45:37 [Error] app/dns: failed to retrieve response for cdn.ampproject.org. > Post "https://1.1.1.1/dns-query": context canceled
2023/02/15 09:52:29 [Error] app/dns: failed to retrieve response for rr4---sn-a5meknd6.googlevideo.com. > Post "https://1.1.1.1/dns-query": context canceled

**Comment by RPRX** [comment]
v1.8.0 没改 DNS 解析 吧

**Comment by RPRX** [comment]
Telegram 无法联网，你确定两边的版本一样吗，今天刚 pin 了个 notice，重要的事情说三遍了，~~不会没看到吧~~

**Comment by RPRX** [comment]
请允许我优雅地吐出一个部首：艹

**Comment by Johnny256Dawson** [comment]
可能因为没有留意到问题的跟进情况所以又发了遍

**Comment by Johnny256Dawson** [comment]
顺便问一嘴r佬这一年没见了，去哪嗨森了

**Comment by RPRX** [comment]
> > 不是，之前你不是发过 issue 我告诉过你了吗 #1808 ，怎么又发，很好玩吗
> 
> ~可能有release note的话，此类issue会少很多？~

有没有一种可能，

**Comment by RPRX** [comment]
> 可能因为没有留意到问题的跟进情况所以又发了遍，顺便问一嘴r佬这一年没见了，去哪嗨森了，你知道这一年我们是怎么过的吗

知道啊，hysteria

**Comment by Larvan2** [comment]
@RPRX 这是双关吗

**Comment by RPRX** [comment]
> @RPRX 这是双关吗

~~你们xray就没有自己的群吗~~

**Comment by Larvan2** [comment]
🤣

**Comment by RPRX** [comment]
> > > 不是，之前你不是发过 issue 我告诉过你了吗 #1808 ，怎么又发，很好玩吗
> > 
> > 
> > ~可能有release note的话，此类issue会少很多？~
> 
> 有没有一种可能，

~~搜一下这几天我的发言吧，多的不说了，实在是很累了~~
