### ISSUE TITLE
v2rayng 

### ISSUE THREAD

**Issue by 1513984439** [XTLS/Xray-core#1848]

**Comment by nebulabox** [comment]
你可能误解了，这个xray其实是和v2ray不同的License，xray的License相比较v2ray的要求的更加严格。v2ray的授权更加开放自由，是真正的自由软件，源代码你随便拿去改动也是可以的。而xray的作者更倾向于，你们免费用我编译好的软件可以，但是我源代码是不能随便给你们用的。

**Comment by Fangliding** [comment]
@nebulabox ?

**Comment by RPRX** [comment]
？这个 issue 是啥

@nebulabox 而你在瞎 bb 什么？

**Comment by nebulabox** [comment]
@RPRX  “瞎 bb ”是什么意思？ 你是想表达人品差，但是还怕拿到火上烤？ 只是偶尔路过，下次不会碰这个门，恶心。

**Comment by zxcvos** [comment]
> 


什么智障，自己不会看一下 MPL 2.0 的内容吗？

**Comment by RPRX** [comment]
@nebulabox 瞎 bb 指的是：
1. 这个 issue 什么内容都没有，你回复一串 license？
2. 你觉得你说得很对？
3. 爱用用，不用滚，loser 不要在这里秀智商

**Comment by aa51513** [comment]
> ？这个 issue 是啥
> 
> @nebulabox 而你在瞎 bb 什么？

这年头智障这么多，你还搭理它，是我没想到的

**Comment by RPRX** [comment]
这个 issue 删了，莫名其妙
