### ISSUE TITLE
reality不支持cloudflare反代节点做中转了吗？

### ISSUE THREAD

**Issue by Pacio** [XTLS/Xray-core#1849]
试了好几个配置，都只能使用本机ip才通，换了[ip-scanner](https://github.com/ip-scanner)
[cloudflare](https://github.com/ip-scanner/cloudflare)的节点就废了~可是高峰期用中转节点真的很好用
---------------------------------------------------------------------------------
配置都是偷别的tls网站

**Comment by Nyar233** [comment]
reality 不支持 cdn

**Comment by Pacio** [comment]
好吧，那我还是直接用xtls-rprx-vision算了
