### ISSUE TITLE
使用xray 面板 Ver:0.3.2 ,切换v1.8.0 核心报错. v1.7.5 能正常运行.

### ISSUE THREAD

**Issue by zengjw33** [XTLS/Xray-core#1850]
使用xray 面板 Ver:0.3.2 ,切换v1.8.0 核心报错. v1.7.5 能正常运行.

**Comment by Pacio** [comment]
你赶紧关了吧，这个问题都被提烂了，1.8.0不兼容老配置

**Comment by Nyar233** [comment]
新版本不支持旧的流控，请按此模板修改：https://github.com/chika0801/Xray-examples/tree/main/VLESS-XTLS-Vision

另外提 iss 时请提供有效消息，不要让人猜

**Comment by RPRX** [comment]
原版 X-UI 即使配置正确，也用不了 v1.8.0，现在有非常多活跃的 X-UI 分支，你可以都试试

**Comment by RPRX** [comment]
或者试试 https://github.com/XTLS/Xray-core/issues/1764#issuecomment-1474742128
