### ISSUE TITLE
Xray outbound traffic to a different network interface 

### ISSUE THREAD

**Issue by arashammm** [XTLS/Xray-core#1851]
Here is a setup I would like to accomplish :
Client connects to the xray (on linux) using interface ens1 device ip :192.168.23.21
xray than sends the outbound traffic to another interface (ens2) which is connected to internet / gateway ip : 10.1.1.1

is that accomplishable by xray itself?
Does anyone have suggesstions?

**Comment by arashammm** [comment]
> https://xtls.github.io/config/outbound.html#outboundobject Use sendthrough. You can get ip of interface from ifconfig command .

I should put the ip of gateway of that interface in the sendthrough or the ip of my device itself?

**Comment by firefoxOnFire** [comment]
> > https://xtls.github.io/config/outbound.html#outboundobject Use sendthrough. You can get ip of interface from ifconfig command .
> 
> I should put the ip of gateway of that interface in the sendthrough or the ip of my device itself?

Ip of gateway.
