### ISSUE TITLE
Reality配置域名为gofile.io时handle失败，网站支持tls1.3和http2，没有跳转。换成www.microsoft.com就没问题。

### ISSUE THREAD

**Issue by fannwong001** [XTLS/Xray-core#1857]
如题。xray版本号[82b0955](https://github.com/XTLS/Xray-core/commit/82b09550d0596e7b2316f874d59c8e4131eb3c5a)
配置的情况：
"flow": ""
"network": "h2",
"security": "reality",
"dest": "gofile.io:443",
"serverNames": ["gofile.io"]

客户端执行情况：xx.xx.xx.xx代表服务器ip
[Warning] [51660904] transport/internet/http: failed to dial to tcp:xx.xx.xx.xx:443 > Put "https://xx.xx.xx.xx:443/": EOF

服务端执行情况：src-ip代表客户端ip
REALITY remoteAddr: src-ip:7475        hs.c.ClientVer: [1 8 0]
REALITY remoteAddr: src-ip:7475        hs.c.ClientTime: 2023-03-26 21:16:07 +0800 HKT
REALITY remoteAddr: src-ip:7475        hs.c.ClientShortId: [0 0 0 0 0 0 0 0]
REALITY remoteAddr: src-ip:7475        hs.c.conn == conn: true
REALITY remoteAddr: src-ip:7475        len(s2cSaved): 99       Server Hello: 93
REALITY remoteAddr: src-ip:7475        handled: false

把两边配置文件中gofile.io换成www.microsoft.com以后就正常了，其他配置没变。
客户端和服务器都放在墙外也试过了，一样的情况。

**Comment by chika0801** [comment]
那就不用gofile.io好了，为什么不能的原因不重要。

**Comment by azzvx** [comment]
`gofile.io`的安全配置:
![QQ截图20230326101607](https://user-images.githubusercontent.com/1546898/227751598-2c809590-db51-4cd3-8040-9a1ac769c351.png)
`www.microsoft.com`的安全配置:
![QQ截图20230326101617](https://user-images.githubusercontent.com/1546898/227751599-91784b31-6cb2-4e8f-a9be-4aeda9f31290.png)
或许是Xray对P-384的支持不完善造成的。

**Comment by RPRX** [comment]
看起来对于 Chrome 的 Client Hello，目标网站并没有选择 X25519，而是选择了 P-384，不符合条件，因为 REALITY 需要 X25519

**Comment by fannwong001** [comment]
> `gofile.io`的安全配置:
> 
> ![QQ截图20230326101607](https://user-images.githubusercontent.com/1546898/227751598-2c809590-db51-4cd3-8040-9a1ac769c351.png)
> 
> `www.microsoft.com`的安全配置:
> 
> ![QQ截图20230326101617](https://user-images.githubusercontent.com/1546898/227751599-91784b31-6cb2-4e8f-a9be-4aeda9f31290.png)
> 
> 或许是Xray对P-384的支持不完善造成的。

请问这个信息在哪里查的，我昨天发现ssllabs访问不了了，就用curl和其他的网站查了一下没发现问题。(不过今天换了个网站查了发现确实有问题。)

**Comment by azzvx** [comment]
Chrome的开发者工具
![QQ截图20230326140127](https://user-images.githubusercontent.com/1546898/227758253-f411fe3e-053f-462d-ae97-f353e7e8eda4.png)

**Comment by fannwong001** [comment]
> 看起来对于 Chrome 的 Client Hello，目标网站并没有选择 X25519，而是选择了 P-384，不符合条件，因为 REALITY 需要 X25519

确实是这个原因，不过我设置的是ios，看了看Safari用的是P-521
![image](https://user-images.githubusercontent.com/37928893/227758274-d16b00db-6eff-4a70-8446-fb220b30e64a.jpeg)
他里面列出来的只有P-384和P-521，另外还有个信息可能可以更明显的判定这个域名不能用，就是openssl握手失败(RFC5746)，但是PC上chrome浏览器访问是没问题的啊🤔️。
![image](https://user-images.githubusercontent.com/37928893/227758505-3da5b147-8e50-4174-99d3-70b72929e5d8.jpeg)

**Comment by RPRX** [comment]
Chrome 的 Client Hello 中 key_share 只有 X25519，但 supported_groups 还有 P-256 和 P-384，服务端会要求 Chrome 重新握手

此外 Chrome 用的是 BoringSSL，不是 OpenSSL

**Comment by fannwong001** [comment]
> Chrome的开发者工具
> 
> ![QQ截图20230326140127](https://user-images.githubusercontent.com/1546898/227758253-f411fe3e-053f-462d-ae97-f353e7e8eda4.png)
> 
> 

原来这里就有，谢谢

**Comment by fannwong001** [comment]
> Chrome 的 Client Hello 中 key_share 只有 X25519，但 supported_groups 还有 P-256 和 P-384，服务端会要求 Chrome 重新握手
> 
> 
> 
> 此外 Chrome 用的是 BoringSSL，不是 OpenSSL

原来如此，涨知识，谢谢

**Comment by fannwong001** [comment]
> 那就不用gofile.io好了，为什么不能的原因不重要。

第一时间就换了，但还是记录一下，防止有别人踩坑吧
