### ISSUE TITLE
1.8.0版本DNS的queryStrategy可能失效了

### ISSUE THREAD

**Issue by liuhgiceblood** [XTLS/Xray-core#1859]
`
{    // 2_DNS设置
    "dns": {
        "tag": "internal_dns",
        //"clientIp": "0.0.0.0",
        "queryStrategy": "UseIPv4",        //UseIPv4 只查询 A 记录；UseIPv6 只查询 AAAA 记录。默认值为 UseIP，即查询 A 和 AAAA 记录。
        "disableCache": false,
        "disableFallback": false,
        "disableFallbackIfMatch": false,
        "servers": [
            "localhost"
        ]
    }
}
`
DNS配置如上，1.7.5版本服务端只会解析为IPV4请求，而1.8.0仍然会优先解析为IPV6，并且访问网站IPV6的IP。
作为客户端客户请求没有问题，全部都是IPv4，但上到服务端，服务端获取sni做二次解析后就变IPv6了。

**Comment by chika0801** [comment]
发下你服务端完整配置

**Comment by liuhgiceblood** [comment]
> 发下你服务端完整配置

{
    "log": {
        "dnsLog": true,        //必须debug级别日志才显示
        //"access": "/var/log/xray/access.log",        // 访问记录
        //"error": "/var/log/xray/error.log",        // 错误记录
        "loglevel": "warning" // 内容从少到多: "none", "error", "warning", "info", "debug"
    }
}
{    // 2_DNS设置
    "dns": {
        "tag": "internal_dns",
        //"clientIp": "0.0.0.0",
        "queryStrategy": "UseIPv4",        //UseIPv4 只查询 A 记录；UseIPv6 只查询 AAAA 记录。默认值为 UseIP，即查询 A 和 AAAA 记录。
        "disableCache": false,
        "disableFallback": false,
        "disableFallbackIfMatch": false,
        "servers": [
            "localhost"
        ]
    }
}
{
    // 分流设置
    // 所谓分流，就是将符合否个条件的流量，用指定`tag`的出站协议去处理（对应配置的5.x内容）
    "routing": {
        //AsIs:仅用 [domain] 来匹配(不使用内置DNS)
        //IPIfNonMatch:如果其他所有规则都匹配不上，那就转化成 IP 去匹配 IP 规则
        //IPOnDemand:当匹配时碰到任何基于 IP 的规则，将域名立即解析为 IP 进行匹配
        "domainStrategy": "IPOnDemand",
        "rules": [
            {
                "type": "field",
                "inboundTag": ["api"],
                "outboundTag": "api"
            },
            //广告域名屏蔽
            //{
            //    "type": "field",
            //    "domain": ["geosite:category-ads-all"],
            //    "outboundTag": "block"
            //},
            {
                "type": "field",
                "protocol": [
                  "bittorrent"
                ],
                "outboundTag": "blackhole"
            },
            // 禁止国内IP
            {
                "type": "field",
                "ip": ["geoip:cn", "geoip:private"],
                "outboundTag": "blackhole"
            },
            // 禁止国内域名，域名误判比较多，慎重使用，比如：ssl.gstatic.com在cn里
            //{
            //    "type": "field",
            //    "domain": ["geosite:cn"],
            //    "outboundTag": "blackhole"
            //},
            {
                "type": "field",
                "ip": ["8.8.8.8", "8.8.4.4"],
                "outboundTag": "IPv4-out"
            }
            // 国外域名代理
            //{
            //    "type": "field",
            //    "domain": ["geosite:geolocation-!cn"],
            //    "outboundTag": "192.168.1.40:8443"
            //},
        ]
    }
}{
    "api": {
        "tag": "api",
        "services": [
            "StatsService"
        ]
    },
        "stats": {},
    "policy": {
        "levels": {
            "0": {
                "handshake": 2, // 连接建立时的握手时间限制，单位为秒，默认值为 4，建议与默认值不同 
                "connIdle": 120, // 连接空闲的时间限制，单位为秒，默认值为 300，建议与默认值不同
                "statsUserUplink": true,  //用户上行流量统计
                "statsUserDownlink": true    //用户下行流量统计
            }
        },
        "system": {
            "statsInboundUplink": true,
            "statsInboundDownlink": true,
            "statsOutboundUplink": true,
            "statsOutboundDownlink": true
        }
    }
}{
    "inbounds": [
        {
            "tag": "VLESS_VS_RL",
            //"listen": "127.0.0.1",
            "port": "6010",
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "2f905929e07",    // 执行 xray uuid 生成，或 1-30 字节的字符串
                        "flow": "xtls-rprx-vision",
                        "email": "root@abc.com"
                    },
                    {
                        "id": "sdfsdfds",
                        "flow": "xtls-rprx-vision",
                        "email": "sdfsdfds.com"
                    },
                    {
                        "id": "sdfsdfds",
                        "flow": "xtls-rprx-vision",
                        "email": "sdfsdfdsm"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "tcp",
                "security": "reality",
                "realitySettings": {
                    "show": false, // 若为 true，输出调试信息
                    "dest": "www.microsoft.com:443", // 目标网站最低标准：国外网站，支持 TLSv1.3 与 H2，域名非跳转用（主域名可能被用于跳转到 www）
                    "xver": 0,
                    "serverNames": [ //客户端可用的serverName列表，暂不支持 * 通配符，执行:xray tls ping download.microsoft.com，填 "Allowed domains" 的值
                        "www.microsoft.com",
                        "staticview.microsoft.com"
                    ],
                    "privateKey": "bXooFtOXX4", // 执行 xray x25519 生成，填 "Private key" 的值
                    //"publicKey": "slrNfTqH3xI",  //该参数用于客户端，这里仅仅保存
                    "shortIds": [ // 客户端可用的 shortId 列表，可用于区分不同的客户端
                        "98a2", // 若有此项，客户端 shortId 可为空
                        "84bc985a", // 0 到 f，长度为 2 的倍数，长度上限为 16，或执行 openssl rand -hex 8 生成
                        "721665"
                    ]
                }
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls",
                    "quic",
                    "fakedns"
                ]
            }
        }
    ]
}
{
    "inbounds": [
        {
            "tag": "VLESS_H2_RL",
            //"listen": "127.0.0.1",
            "port": 6012,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "2f905929e07",    // 执行 xray uuid 生成，或 1-30 字节的字符串
                        "flow": "",
                        "email": "root@abc.com"
                    },
                    {
                        "id": "sdfsdfds",
                        "flow": "",
                        "email": "sdfsdfds.com"
                    },
                    {
                        "id": "sdfsdfds",
                        "flow": "",
                        "email": "sdfsdfdsm"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "h2",
                "security": "reality",
                "realitySettings": {
                    "show": false, // 若为 true，输出调试信息
                    "dest": "www.microsoft.com:443", // 目标网站最低标准：国外网站，支持 TLSv1.3 与 H2，域名非跳转用（主域名可能被用于跳转到 www）
                    "xver": 0,
                    "serverNames": [ //客户端可用的serverName列表，暂不支持 * 通配符，执行:xray tls ping download.microsoft.com，填 "Allowed domains" 的值
                        "www.microsoft.com",
                        "staticview.microsoft.com"
                    ],
                    "privateKey": "dgdgsdfgsdf", // 执行 xray x25519 生成，填 "Private key" 的值
                    //"publicKey": "dgdgsdfgsdf",  //该参数用于客户端，这里仅仅保存
                    "shortIds": [ // 客户端可用的 shortId 列表，可用于区分不同的客户端
                        "dgdgsdfgsdf", // 若有此项，客户端 shortId 可为空
                        "dgdgsdfgsdf", // 0 到 f，长度为 2 的倍数，长度上限为 16，或执行 openssl rand -hex 8 生成
                        "dgdgsdfgsdf"
                    ]
                }
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls",
                    "quic",
                    "fakedns"
                ]
            }
        }
    ]
}{
    "inbounds": [
        {
            "tag": "VLESS_GRPC_RL",
            //"listen": "127.0.0.1",
            "port": 6013,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "2f905929e07",    // 执行 xray uuid 生成，或 1-30 字节的字符串
                        "flow": "",
                        "email": "root@abc.com"
                    },
                    {
                        "id": "sdfsdfds",
                        "flow": "",
                        "email": "sdfsdfds.com"
                    },
                    {
                        "id": "sdfsdfds",
                        "flow": "",
                        "email": "sdfsdfdsm"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "grpc",
                "security": "reality",
                "realitySettings": {
                    "show": false, // 若为 true，输出调试信息
                    "dest": "www.microsoft.com:443", // 目标网站最低标准：国外网站，支持 TLSv1.3 与 H2，域名非跳转用（主域名可能被用于跳转到 www）
                    "xver": 0,
                    "serverNames": [ //客户端可用的serverName列表，暂不支持 * 通配符，执行:xray tls ping download.microsoft.com，填 "Allowed domains" 的值
                        "www.microsoft.com",
                        "staticview.microsoft.com"
                    ],
                    "privateKey": "dgdgsdfgsdf", // 执行 xray x25519 生成，填 "Private key" 的值
                    //"publicKey": "dgdgsdfgsdf",  //该参数用于客户端，这里仅仅保存
                    "shortIds": [ // 客户端可用的 shortId 列表，可用于区分不同的客户端
                        "dgdgsdfgsdf", // 若有此项，客户端 shortId 可为空
                        "dgdgsdfgsdf", // 0 到 f，长度为 2 的倍数，长度上限为 16，或执行 openssl rand -hex 8 生成
                        "dgdgsdfgsdf"
                    ]
                },
                "grpcSettings": {
                    "serviceName": "www.microsoft.com" // 指定服务名称，若客户端为 Clash Meta Kernel，不能留空
                }
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls",
                    "quic",
                    "fakedns"
                ]
            }
        }
    ]
}{
    "inbounds":[
        {
            //"listen": "127.0.0.1",
            "port": "7001-7008",
            "protocol": "vless",
            "tag": "VLESS_VS",
            "settings": {
                "clients": [
                    {
                        "id": "2f905929e07",    // 执行 xray uuid 生成，或 1-30 字节的字符串
                        "flow": "xtls-rprx-vision",
                        "email": "root@abc.com"
                    },
                    {
                        "id": "sdfsdfds",
                        "flow": "xtls-rprx-vision",
                        "email": "sdfsdfds.com"
                    },
                    {
                        "id": "sdfsdfds",
                        "flow": "xtls-rprx-vision",
                        "email": "sdfsdfdsm"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "certificates": [
                        {
                            "certificateFile": "./conf/xray/cert/fullchain.pem",
                            "keyFile": "./conf/xray/cert/private.pem"
                        }
                    ]
                }
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls",
                    "quic",
                    "fakedns"
                ]
            }
        }
    ]
}{
    "inbounds":[
        {
            //"listen": "127.0.0.1",
            //"port": 10002,
            "listen": "/tmp/vmess_ws.socket,0666",
            "protocol": "vmess",
            "tag": "VMESS_WS",
            "settings": {
                "disableInsecureEncryption": true,    //true：仅接受加密传输
                "clients": [
                    {
                        "security": "auto",    //包含："aes-128-gcm" | "chacha20-poly1305" | "auto" | "none" | "zero"
                        "id": "2f905929e07",    // 执行 xray uuid 生成，或 1-30 字节的字符串
                        "email": "root@abc.com"
                    },
                    {
                        "security": "auto",    //包含："aes-128-gcm" | "chacha20-poly1305" | "auto" | "none" | "zero"
                        "id": "sdfsdfds",
                        "email": "sdfsdfds.com"
                    },
                    {
                        "security": "auto",    //包含："aes-128-gcm" | "chacha20-poly1305" | "auto" | "none" | "zero"
                        "id": "sdfsdfds",
                        "email": "sdfsdfdsm"
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "wsSettings": {
                    //"acceptProxyProtocol": true,    //仅fallbacks模式使用
                    "path": "/vmws"
                },
                "security": "none"
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls",
                    "quic",
                    "fakedns"
                ]
            }
        }
    ]
}{
    "inbounds":[
        {
            //"listen": "127.0.0.1",
            //"port": 10002,
            "listen": "/tmp/vmess_grpc.socket,0666",
            "protocol": "vmess",
            "tag": "VMESS_GRPC",
            "settings": {
                "disableInsecureEncryption": true,    //true：仅接受加密传输
                "clients": [
                    {
                        "security": "auto",    //包含："aes-128-gcm" | "chacha20-poly1305" | "auto" | "none" | "zero"
                        "id": "2f905929e07",    // 执行 xray uuid 生成，或 1-30 字节的字符串
                        "email": "root@abc.com"
                    },
                    {
                        "security": "auto",    //包含："aes-128-gcm" | "chacha20-poly1305" | "auto" | "none" | "zero"
                        "id": "sdfsdfds",
                        "email": "sdfsdfds.com"
                    },
                    {
                        "security": "auto",    //包含："aes-128-gcm" | "chacha20-poly1305" | "auto" | "none" | "zero"
                        "id": "sdfsdfds",
                        "email": "sdfsdfdsm"
                    }
                ]
            },
            "streamSettings": {
                "network": "grpc",
                "grpcSettings": {
                    "serviceName": "vr-lb.otxn.com" // 填写你的 ServiceName
                },
                "security": "none"
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls",
                    "quic",
                    "fakedns"
                ]
            }
        }
    ]
}{
    "inbounds":[
        {
            "listen": "127.0.0.1",
            "port": 65001,
            "protocol": "dokodemo-door",
            "settings": {
                "address": "127.0.0.1"
            },
            "tag": "api"
        }
    ]
}{
    "outbounds":[
        {
            "tag":"Any-out",
            "protocol": "freedom", 
            "settings": {
                "domainStrategy": "AsIs"
            }
        },
        {
            "tag":"blackhole",
            "protocol":"blackhole"
        },
                //以下必须启用DNS模块
        {
            "tag":"Any-out2",
            "protocol":"freedom",
            "settings":{
                "domainStrategy":"UseIP"
            }
        },
        {
            "tag":"IPv4-out",
            "protocol":"freedom",
            "settings":{
                "domainStrategy":"UseIPv4"
            }
        },
        {
            "tag":"IPv6-out",
            "protocol":"freedom",
            "settings":{
                "domainStrategy":"UseIPv6"
            }
        }
    ]
}
================
我是多配置模式。
xtls-rprx-vision+xtls那部分1.75和1.80没有任何变化，使用这个查询IP的目标网站从ipv4变成了ipv6。

**Comment by RPRX** [comment]
v1.8.0 相对于 v1.7.5 没动 DNS 解析的代码，所以不会有区别，再测测（若真的有区别，可能是 Go 1.20.2 或依赖库的锅）

**Comment by picklefan** [comment]
## 我是个小白但是我就是想给你的json拿去自动缩进一下
```
{
    "log":{
       "dnsLog":true,
       "access":"/var/log/xray/access.log",
       "error":"/var/log/xray/error.log",
       "loglevel":"warning":"none",
       "error",
       "warning",
       "info",
       "debug"
    }
 }{
    // 2_DNS设置"dns":{
       "tag":"internal_dns",
       "clientIp":"0.0.0.0",
       "queryStrategy":"UseIPv4",
       //UseIPv4 只查询 A 记录；UseIPv6 只查询 AAAA 记录。默认值为 UseIP，即查询 A 和 AAAA 记录。"disableCache":false,
       "disableFallback":false,
       "disableFallbackIfMatch":false,
       "servers":[
          "localhost"
       ]
    }
 }{
    // 分流设置
 // 所谓分流，就是将符合否个条件的流量，用指定tag的出站协议去处理（对应配置的5.x内容）"routing":{
       :"仅用"[
          "domain"
       ]"来匹配(不使用内置DNS)
 //IPIfNonMatch":"如果其他所有规则都匹配不上，那就转化成 IP 去匹配 IP 规则
 //IPOnDemand":"当匹配时碰到任何基于 IP 的规则，将域名立即解析为 IP 进行匹配""domainStrategy":"IPOnDemand",
       "rules":[
          {
             "type":"field",
             "inboundTag":[
                "api"
             ],
             "outboundTag":"api"
          },
          {
             "type":"field",
             "domain":[
                "geosite:category-ads-all"
             ],
             "outboundTag":"block"
          },
          {
             "type":"field",
             "protocol":[
                "bittorrent"
             ],
             "outboundTag":"blackhole"
          },
          {
             "type":"field",
             "ip":[
                "geoip:cn",
                "geoip:private"
             ],
             "outboundTag":"blackhole"
          },
          {
             "type":"field",
             "domain":[
                "geosite:cn"
             ],
             "outboundTag":"blackhole"
          },
          {
             "type":"field",
             "ip":[
                "8.8.8.8",
                "8.8.4.4"
             ],
             "outboundTag":"IPv4-out"
          }{
             "type":"field",
             "domain":[
                "geosite:geolocation-!cn"
             ],
             "outboundTag":"192.168.1.40:8443"
          }
       ]
    }
 }{
    "api":{
       "tag":"api",
       "services":[
          "StatsService"
       ]
    },
    "stats":{
       
    },
    "policy":{
       "levels":{
          "0":{
             "handshake":2,
             // 连接建立时的握手时间限制，单位为秒，默认值为 4，建议与默认值不同"connIdle":120,
             // 连接空闲的时间限制，单位为秒，默认值为 300，建议与默认值不同"statsUserUplink":true,
             "statsUserDownlink":"true //用户下行流量统计"
          }
       },
       "system":{
          "statsInboundUplink":true,
          "statsInboundDownlink":true,
          "statsOutboundUplink":true,
          "statsOutboundDownlink":true
       }
    }
 }{
    "inbounds":[
       {
          "tag":"VLESS_VS_RL",
          "listen":"127.0.0.1",
          "port":"6010",
          "protocol":"vless",
          "settings":{
             "clients":[
                {
                   "id":"2f905929e07",
                   // 执行 xray uuid 生成，或 1-30 字节的字符串"flow":"xtls-rprx-vision",
                   "email":"root@abc.com"
                },
                {
                   "id":"sdfsdfds",
                   "flow":"xtls-rprx-vision",
                   "email":"sdfsdfds.com"
                },
                {
                   "id":"sdfsdfds",
                   "flow":"xtls-rprx-vision",
                   "email":"sdfsdfdsm"
                }
             ],
             "decryption":"none"
          },
          "streamSettings":{
             "network":"tcp",
             "security":"reality",
             "realitySettings":{
                "show":false,
                "dest":"www.microsoft.com:443",
                // 目标网站最低标准：国外网站，支持 TLSv1.3 与 H2，域名非跳转用（主域名可能被用于跳转到 www）"xver":0,
                "serverNames":[
                   :"xray tls ping download.microsoft.com，填""Allowed domains""的值""www.microsoft.com",
                   "staticview.microsoft.com"
                ],
                "privateKey":"bXooFtOXX4",
                // 执行 xray x25519 生成，填"Private key""的值
 //""publicKey":"slrNfTqH3xI",
                "shortIds":[
                   "98a2",
                   "84bc985a",
                   // 0 到 f，长度为 2 的倍数，长度上限为 16，或执行 openssl rand -hex 8 生成"721665"
                ]
             }
          },
          "sniffing":{
             "enabled":true,
             "destOverride":[
                "http",
                "tls",
                "quic",
                "fakedns"
             ]
          }
       }
    ]
 }{
    "inbounds":[
       {
          "tag":"VLESS_H2_RL",
          "listen":"127.0.0.1",
          "port":6012,
          "protocol":"vless",
          "settings":{
             "clients":[
                {
                   "id":"2f905929e07",
                   // 执行 xray uuid 生成，或 1-30 字节的字符串"flow":"",
                   "email":"root@abc.com"
                },
                {
                   "id":"sdfsdfds",
                   "flow":"",
                   "email":"sdfsdfds.com"
                },
                {
                   "id":"sdfsdfds",
                   "flow":"",
                   "email":"sdfsdfdsm"
                }
             ],
             "decryption":"none"
          },
          "streamSettings":{
             "network":"h2",
             "security":"reality",
             "realitySettings":{
                "show":false,
                "dest":"www.microsoft.com:443",
                // 目标网站最低标准：国外网站，支持 TLSv1.3 与 H2，域名非跳转用（主域名可能被用于跳转到 www）"xver":0,
                "serverNames":[
                   :"xray tls ping download.microsoft.com，填""Allowed domains""的值""www.microsoft.com",
                   "staticview.microsoft.com"
                ],
                "privateKey":"dgdgsdfgsdf",
                // 执行 xray x25519 生成，填"Private key""的值
 //""publicKey":"dgdgsdfgsdf",
                "shortIds":[
                   "dgdgsdfgsdf",
                   "dgdgsdfgsdf",
                   // 0 到 f，长度为 2 的倍数，长度上限为 16，或执行 openssl rand -hex 8 生成"dgdgsdfgsdf"
                ]
             }
          },
          "sniffing":{
             "enabled":true,
             "destOverride":[
                "http",
                "tls",
                "quic",
                "fakedns"
             ]
          }
       }
    ]
 }{
    "inbounds":[
       {
          "tag":"VLESS_GRPC_RL",
          "listen":"127.0.0.1",
          "port":6013,
          "protocol":"vless",
          "settings":{
             "clients":[
                {
                   "id":"2f905929e07",
                   // 执行 xray uuid 生成，或 1-30 字节的字符串"flow":"",
                   "email":"root@abc.com"
                },
                {
                   "id":"sdfsdfds",
                   "flow":"",
                   "email":"sdfsdfds.com"
                },
                {
                   "id":"sdfsdfds",
                   "flow":"",
                   "email":"sdfsdfdsm"
                }
             ],
             "decryption":"none"
          },
          "streamSettings":{
             "network":"grpc",
             "security":"reality",
             "realitySettings":{
                "show":false,
                "dest":"www.microsoft.com:443",
                // 目标网站最低标准：国外网站，支持 TLSv1.3 与 H2，域名非跳转用（主域名可能被用于跳转到 www）"xver":0,
                "serverNames":[
                   :"xray tls ping download.microsoft.com，填""Allowed domains""的值""www.microsoft.com",
                   "staticview.microsoft.com"
                ],
                "privateKey":"dgdgsdfgsdf",
                // 执行 xray x25519 生成，填"Private key""的值
 //""publicKey":"dgdgsdfgsdf",
                "shortIds":[
                   "dgdgsdfgsdf",
                   "dgdgsdfgsdf",
                   // 0 到 f，长度为 2 的倍数，长度上限为 16，或执行 openssl rand -hex 8 生成"dgdgsdfgsdf"
                ]
             },
             "grpcSettings":{
                "serviceName":"www.microsoft.com"
             }
          },
          "sniffing":{
             "enabled":true,
             "destOverride":[
                "http",
                "tls",
                "quic",
                "fakedns"
             ]
          }
       }
    ]
 }{
    "inbounds":[
       {
          "listen":"127.0.0.1",
          "port":"7001-7008",
          "protocol":"vless",
          "tag":"VLESS_VS",
          "settings":{
             "clients":[
                {
                   "id":"2f905929e07",
                   // 执行 xray uuid 生成，或 1-30 字节的字符串"flow":"xtls-rprx-vision",
                   "email":"root@abc.com"
                },
                {
                   "id":"sdfsdfds",
                   "flow":"xtls-rprx-vision",
                   "email":"sdfsdfds.com"
                },
                {
                   "id":"sdfsdfds",
                   "flow":"xtls-rprx-vision",
                   "email":"sdfsdfdsm"
                }
             ],
             "decryption":"none"
          },
          "streamSettings":{
             "network":"tcp",
             "security":"tls",
             "tlsSettings":{
                "certificates":[
                   {
                      "certificateFile":"./conf/xray/cert/fullchain.pem",
                      "keyFile":"./conf/xray/cert/private.pem"
                   }
                ]
             }
          },
          "sniffing":{
             "enabled":true,
             "destOverride":[
                "http",
                "tls",
                "quic",
                "fakedns"
             ]
          }
       }
    ]
 }{
    "inbounds":[
       {
          "listen":"127.0.0.1",
          "port":10002,
          "listen":"/tmp/vmess_ws.socket,0666",
          "protocol":"vmess",
          "tag":"VMESS_WS",
          "settings":{
             "disableInsecureEncryption":true,
             "clients":[
                {
                   "security":"auto",
                   "aes-128-gcm""|""chacha20-poly1305""|""auto""|""none""|""zero""id":"2f905929e07",
                   // 执行 xray uuid 生成，或 1-30 字节的字符串"email":"root@abc.com"
                },
                {
                   "security":"auto",
                   "aes-128-gcm""|""chacha20-poly1305""|""auto""|""none""|""zero""id":"sdfsdfds",
                   "email":"sdfsdfds.com"
                },
                {
                   "security":"auto",
                   "aes-128-gcm""|""chacha20-poly1305""|""auto""|""none""|""zero""id":"sdfsdfds",
                   "email":"sdfsdfdsm"
                }
             ]
          },
          "streamSettings":{
             "network":"ws",
             "wsSettings":{
                "acceptProxyProtocol":true,
                "path":"/vmws"
             },
             "security":"none"
          },
          "sniffing":{
             "enabled":true,
             "destOverride":[
                "http",
                "tls",
                "quic",
                "fakedns"
             ]
          }
       }
    ]
 }{
    "inbounds":[
       {
          "listen":"127.0.0.1",
          "port":10002,
          "listen":"/tmp/vmess_grpc.socket,0666",
          "protocol":"vmess",
          "tag":"VMESS_GRPC",
          "settings":{
             "disableInsecureEncryption":true,
             "clients":[
                {
                   "security":"auto",
                   "aes-128-gcm""|""chacha20-poly1305""|""auto""|""none""|""zero""id":"2f905929e07",
                   // 执行 xray uuid 生成，或 1-30 字节的字符串"email":"root@abc.com"
                },
                {
                   "security":"auto",
                   "aes-128-gcm""|""chacha20-poly1305""|""auto""|""none""|""zero""id":"sdfsdfds",
                   "email":"sdfsdfds.com"
                },
                {
                   "security":"auto",
                   "aes-128-gcm""|""chacha20-poly1305""|""auto""|""none""|""zero""id":"sdfsdfds",
                   "email":"sdfsdfdsm"
                }
             ]
          },
          "streamSettings":{
             "network":"grpc",
             "grpcSettings":{
                "serviceName":"vr-lb.otxn.com"
             },
             "security":"none"
          },
          "sniffing":{
             "enabled":true,
             "destOverride":[
                "http",
                "tls",
                "quic",
                "fakedns"
             ]
          }
       }
    ]
 }{
    "inbounds":[
       {
          "listen":"127.0.0.1",
          "port":65001,
          "protocol":"dokodemo-door",
          "settings":{
             "address":"127.0.0.1"
          },
          "tag":"api"
       }
    ]
 }{
    "outbounds":[
       {
          "tag":"Any-out",
          "protocol":"freedom",
          "settings":{
             "domainStrategy":"AsIs"
          }
       },
       {
          "tag":"blackhole",
          "protocol":"blackhole"
       },
       {
          "tag":"Any-out2",
          "protocol":"freedom",
          "settings":{
             "domainStrategy":"UseIP"
          }
       },
       {
          "tag":"IPv4-out",
          "protocol":"freedom",
          "settings":{
             "domainStrategy":"UseIPv4"
          }
       },
       {
          "tag":"IPv6-out",
          "protocol":"freedom",
          "settings":{
             "domainStrategy":"UseIPv6"
          }
       }
    ]
 }
```

**Comment by chika0801** [comment]
你把

2_DNS设置"dns":{
       "tag":"internal_dns",
       "clientIp":"0.0.0.0",
       "queryStrategy":"UseIPv4",

useipv4改成useip。

因为看你出站有用useipv4 useipv6。dns里不改会有这问题


https://www.v2fly.org/config/dns.html#dnsobject

如果本选项设置为 UseIPv4，而 freedom 协议 outbound 中的 domainStrategy 选项设置为 UseIPv6，会导致从 freedom 协议 outbound 发出的连接的 DNS 查询被 Go 运行时接管，进而导致 DNS 泄漏；反之同理。

配置其它方面没发现问题。

**Comment by chika0801** [comment]
如果你想研究，建议开debug保存日志，然后自己找实验网站，观察日志便得知在服务端，这网址在xray里经历了什么样的流程

**Comment by liuhgiceblood** [comment]
> 如果你想研究，日志开debug保存日志，然后自己找实验网站访问，观察日志便得知在服务端，这网址在xray里经历了什么样的流程

 非常感谢，我查出问题了，原因是outbounds第一个我不小心设置为AsIs了，不过确实没想到这里的配置覆盖了DNS里的配置。

**Comment by chika0801** [comment]
```
       {
          "tag":"Any-out",
          "protocol":"freedom",
          "settings":{
             "domainStrategy":"AsIs"
          }
       },
```

第1个出站我看你是ASIS 哈哈哈没事习惯算命了

**Comment by iceliuhacker** [comment]
> ```
>        {
>           "tag":"Any-out",
>           "protocol":"freedom",
>           "settings":{
>              "domainStrategy":"AsIs"
>           }
>        },
> ```
> 
> 第1个出站我看你是ASIS 哈哈哈没事习惯算命了

也算学到新东西吧，outbound优先级高于dns内的设置，虽然不起眼，但是确很关键
