### ISSUE TITLE
openwrt主路由运行xray客户端启用doh后大量出现`context deadline exceeded`错误信息

### ISSUE THREAD

**Issue by 70599** [XTLS/Xray-core#186]
### 错误信息（大量出现，每秒数条）：
```
2021/01/19 13:48:21 [Error] app/dns: failed to retrieve response for p30-bookmarks.icloud.com. > Post "https://dns.google/dns-query": context deadline exceeded
```

### 搭配这样的`warning`（同样大量出现）：
```
2021/01/19 13:49:01 [Warning] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: i/o timeout] > common/retry: all retry attempts failed
```

### 使用感受：
域名解析概率成功，伴随较明显卡顿感。

### 客户端配置：
```json
{
	"log": {
		"loglevel": "warning",
		"error": "/var/log/xray_error.log"
	},
	
	"inbounds": [
		{
			"tag": "dns-in",
			"port": 5300,
			"protocol": "dokodemo-door",
			"settings": {
				"address": "1.1.1.1",
				"port": 53,
				"network": "tcp,udp"
			}
		},
		{
			"tag": "all-in",
			"port": 12345,
			"protocol": "dokodemo-door",
			"settings": {
				"network": "tcp,udp",
				"followRedirect": true
			},
			"sniffing": {
				"enabled": true,
				"destOverride": ["http", "tls"]
			},
			"streamSettings": {
				"sockopt": {
					"tproxy": "tproxy"
				}
			}
		},
		{
			"tag": "socks-in",
			"protocol": "socks",
			"port": 9050,
			"settings": {
				"udp": true
			}
		}
	],
	
	"outbounds": [
		{
			"tag": "direct",
			"protocol": "freedom",
			"settings": {
				"domainStrategy": "UseIPv4"
			}
		},
		{
			"tag": "proxy",
			"protocol": "vless",
			"settings": {
				"vnext": [{
					"address": "服务器URL",
					"port": 443,
					"users": [{
						"id": "uuid",
						"flow": "xtls-rprx-splice",
						"encryption": "none"
					}]
				}]
			},
			"streamSettings": {
				"network": "tcp",
				"security": "xtls"
			}
		},
		{
			"tag": "block",
			"protocol": "blackhole",
			"settings": {
				"response": {
					"type": "http"
				}
			}
		},
		{
			"tag": "dns-out",
			"protocol": "dns"
		}
	],
	
	"dns": {
		"hosts": {
			"服务器URL": "服务器IP",
			"dns.google": "8.8.8.8",
			"dns.alidns.com": "223.5.5.5"
		},
		"servers": [
			{
				"address": "https://dns.google/dns-query",
				"domains": [
					"geosite:geolocation-!cn"
				]
			},
			{
				"address": "https+local://dns.alidns.com/dns-query",
				"domains": [
					"geosite:cn"
				],
				"expectIPs": [
					"geoip:cn"
				]
			},
			"114.114.114.114"
		]
	},
	
	"routing": {
		"domainStrategy": "IPIfNonMatch",
		"rules": [
			{
				"type": "field",
				"domain": [
					"geosite:category-ads-all"
				],
				"outboundTag": "block"
			},
			{
				"type": "field",
				"inboundTag": [
					"dns-in"
				],
				"outboundTag": "dns-out"
			},
			{
				"type": "field",
				"inboundTag": [
					"all-in"
				],
				"port": 53,
				"network": "udp",
				"outboundTag": "dns-out"
			},
			{
				"type": "field",
				"ip": [
					"223.5.5.5"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"ip": [
					"1.1.1.1",
					"8.8.8.8"
				],
				"outboundTag": "proxy"
			},
			{
				"type": "field",
				"domain": [
					"geosite:cn"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"protocol":["bittorrent"],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"ip": [
					"geoip:cn",
					"geoip:private"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field", 
				"domain": [
					"geosite:tld-cn",
					"geosite:apple-cn",
					"geosite:private"
				],
				"outboundTag": "direct"
			},
			{
				"type": "field",
				"domain": [
					"geosite:geolocation-!cn"
				],
				"outboundTag": "proxy"
			},
			{
				"type": "field",
				"outboundTag": "direct",
				"domain": [
					"geosite:cn"
				]
			},
			{
				"type": "field",
				"network": "tcp,udp",
				"outboundTag": "proxy"
			}
		]
	}
}
```

**Comment by nJhEqnvK** [comment]
> {
> 				"type": "field",
> 				"network": "tcp,udp",
> 				"outboundTag": "proxy"
> 			}

你最后一条路由啥意思，所有tcp和udp都走代理？

看warning是有连接超时（就是涉及到国外的dns信息会通过你的"proxy"传输至墙外，但这个传输过程超时了，造成了dns查询失败），你把DoH换成普通dns试试呢：
```
"dns": {
		"hosts": {
			"服务器URL": "服务器IP",
			"dns.google": "8.8.8.8",
			"dns.alidns.com": "223.5.5.5"
		},
		"servers": [
			{
				"address": "8.8.8.8",
				"domains": [
					"geosite:geolocation-!cn"
				]
			},
			{
				"address": "223.5.5.5",
				"domains": [
					"geosite:cn"
				],
				"expectIPs": [
					"geoip:cn"
				]
			},
			"114.114.114.114"
		]
	},
```

**Comment by 70599** [comment]
> 你最后一条路由啥意思，所有tcp和udp都走代理？
我的理解是它前面的路由规则都没有匹配到的流量，走proxy。

> 你把DoH换成普通dns试试呢
普通dns都是正常的。
我在测试没有问题后，才开始尝试doh的。

**Comment by badO1a5A90** [comment]
> 你最后一条路由啥意思，所有tcp和udp都走代理？
这个算是兜底规则,都不匹配就走代理拉倒...应该也没什么问题.

群里他回复说过 https+local://dns.alidns.com/dns-query 也是一样的错误的.
这是直连国内的阿里DOH都连不通...非常奇怪,整个环境一定有一些奇怪的问题.
普通dns他也有奇怪的错误.(但不影响解析)-->建议也描述一下 @70599 h

**Comment by nJhEqnvK** [comment]
> > 你最后一条路由啥意思，所有tcp和udp都走代理？
> > 这个算是兜底规则,都不匹配就走代理拉倒...应该也没什么问题.
> 
> 群里他回复说过 https+local://dns.alidns.com/dns-query 也是一样的错误的.
> 这是直连国内的阿里DOH都连不通...非常奇怪,整个环境一定有一些奇怪的问题.
> 普通dns他也有奇怪的错误.(但不影响解析)-->建议也描述一下 @70599 h

应该是线路的特殊体质了，像我移动的线路正常的DNS都能随即丢包，DoH反而没那么厉害，电信则是反过来的，只有公司的教育网稳如老狗~~CERNET永远的神~~

**Comment by 70599** [comment]
> > 你最后一条路由啥意思，所有tcp和udp都走代理？
> > 这个算是兜底规则,都不匹配就走代理拉倒...应该也没什么问题.
> 
> 群里他回复说过 https+local://dns.alidns.com/dns-query 也是一样的错误的.
> 这是直连国内的阿里DOH都连不通...非常奇怪,整个环境一定有一些奇怪的问题.
> 普通dns他也有奇怪的错误.(但不影响解析)-->建议也描述一下 @70599 h

对，只要是设置了doh服务器，就一定会大量输出`context deadline exceeded`错误。
即使在xray配置文件内设置了`dns.hosts`，即使是`https://223.5.5.5/dns-query`这样使用IP域名的doh服务器。

“不影响解析”的描述不太契合，我能明显感觉到卡顿，还会随机找不到服务器。

**Comment by badO1a5A90** [comment]
不影响解析是指你用普通DNS的时候...

**Comment by nJhEqnvK** [comment]
> > > 你最后一条路由啥意思，所有tcp和udp都走代理？
> > > 这个算是兜底规则,都不匹配就走代理拉倒...应该也没什么问题.
> > 
> > 
> > 群里他回复说过 https+local://dns.alidns.com/dns-query 也是一样的错误的.
> > 这是直连国内的阿里DOH都连不通...非常奇怪,整个环境一定有一些奇怪的问题.
> > 普通dns他也有奇怪的错误.(但不影响解析)-->建议也描述一下 @70599 h
> 
> 对，只要是设置了doh服务器，就一定会大量输出`context deadline exceeded`错误。
> 即使在xray配置文件内设置了`dns.hosts`，即使是`https://223.5.5.5/dns-query`这样使用IP域名的doh服务器。
> 
> “不影响解析”的描述不太契合，我能明显感觉到卡顿，还会随机找不到服务器。

其实问题也不是找不到服务器，而是无法建立连接。。。

**Comment by badO1a5A90** [comment]
你用普通DNS的时候, 那个error应该也是不合理的.

**Comment by nJhEqnvK** [comment]
> 你用普通DNS的时候, 那个error应该也是不合理的,但确实不影响使用.

他说普通DNS正常，问题应该就是DoH了

> > 你最后一条路由啥意思，所有tcp和udp都走代理？
> 
> 我的理解是它前面的路由规则都没有匹配到的流量，走proxy。
> 
> > 你把DoH换成普通dns试试呢
> 
> 普通dns都是正常的。
> 我在测试没有问题后，才开始尝试doh的。

**Comment by badO1a5A90** [comment]
不用DOH不是有   app/dns: UDP:127.0.0.1:5311 cannot find the pending request 错误么.

**Comment by nJhEqnvK** [comment]
> cannot find the pending request

不知道了，刚下班没看群，不过在隔壁issue https://github.com/XTLS/Xray-core/issues/185#issuecomment-762914214 已经解决他的问题了，我们就当无事发生好了（逃

**Comment by badO1a5A90** [comment]
看到了...这是个什么原理?求解

**Comment by 70599** [comment]
> 不用DOH时, 不是有 app/dns: UDP:127.0.0.1:5311 cannot find the pending request 错误么.

这个错误是，设置CoreDNS（DoT）为xray的dns服务器时发生的错误信息，具体配置如下：
xray的`dns.servers`：
```json
"servers": [
	{
		"address": "127.0.0.1",
		"port": 5311,
		"domains": [
			"geosite:geolocation-!cn"
		]
	},
	{
		"address": "127.0.0.1",
		"port": 5301
		"domains": [
			"geosite:cn"
		],
		"expectIPs": [
			"geoip:cn"
		]
	},
	"114.114.114.114"
]
```

CoreDNS的配置：
```
.:5301 {
	bind 127.0.0.1
	forward . tls://223.5.5.5 tls://223.6.6.6 {
		tls_servername dns.alidns.com
	}
	cache
}

.:5311 {
	bind 127.0.0.1
	forward . tls://1.1.1.1 tls://1.0.0.1 {
		tls_servername 1dot1dot1dot1.cloudflare-dns.com
	}
	cache
}
```

**Comment by badO1a5A90** [comment]
emmm,所以经过隔壁 https://github.com/XTLS/Xray-core/issues/185 的设置后,也好了吗

**Comment by 70599** [comment]
#185 的主要问题是，主路由内运行xray后，路由器本身不能解析域名（客户端可以）。
本issue的主要问题是，doh不正常。

#185 经过解答后，路由器本机已经可以正常解析域名了。
这个doh还是不能使用。
（看起来可能是我线路环境（联通光纤500M）的原因）

**Comment by badO1a5A90** [comment]
了解. 不过连阿里的DOH都不通有点不可思议
你能把error.log日志开到debug,看一下输出吗?

**Comment by nJhEqnvK** [comment]
> 看到了...这是个什么原理?求解

其实这个也有openwrt的锅。。。好像openwrt在某些特殊设置下会把wan通告的DNS再通告给子网设备。。。

可以通过DHCP option强制设定DHCP的相关通告内容，比如DNS（option 6），网关（option 3，旁路由时特别有用）
~~另外TG因为加了一些朋友不方便说话，但没想到版聊居然在群里面被直播了~~

等周末有时间我写教程吧，咕咕咕

**Comment by badO1a5A90** [comment]
> 等周末有时间我写教程吧，咕咕咕

教程*2, 拜托了, 哈哈哈.🙏
这两个帖子我觉得也可以搞进大案牍术做个link了.(然后加上你教程
可以给其他人很多信息和参考.

**Comment by 70599** [comment]
> 了解. 不过连阿里的DOH都不通有点不可思议
> 你能把error.log日志开到debug,看一下输出吗?

大概有没有1分钟的样子，总长度500多行。
[debug.log](https://github.com/XTLS/Xray-core/files/5837004/debug.log)

**Comment by badO1a5A90** [comment]
浏览器直接访问 https://dns.alidns.com/dns-query 能打开吗

**Comment by 70599** [comment]
passwall版本<=4-7的时候有doh的选项，当初用passwall+xray+doh的时候没有感觉到明显的问题（相当低概率找不到服务器）。
所以我觉得`我的网络`和`doh不可用`没有那么强的因果关系。

> 浏览器直接访问 https://dns.alidns.com/dns-query 能打开吗

可以。显示`no 'dns' query parameter found`，应该是正常的。

**Comment by badO1a5A90** [comment]
> passwall版本<=4-7的时候有doh的选项，当初用passwall+xray+doh的时候没有感觉到明显的问题（相当低概率找不到服务器）。
> 所以我觉得`我的网络`和`doh不可用`没有那么强的因果关系。
> 
> > 浏览器直接访问 https://dns.alidns.com/dns-query 能打开吗
> 
> 可以。显示`no 'dns' query parameter found`，应该是正常的。

那可以排除你网络问题了, 暂时没有头绪

**Comment by nJhEqnvK** [comment]
> 那可以排除你网络问题了, 暂时没有头绪

不一定，运营商一般会给53端口做白名单不会QOS（~~你甚至可以在53强行UDP高速传输~~），但是像DoH就不一定给开了白名单了，所以你懂的。。。

**Comment by 70599** [comment]
Firefox有浏览器内置的DoH功能，我把它设置为`https://dns.alidns.com/dns-query`，测试解析结果如下：
![Kapture 2021-01-20 at 00 23 33](https://user-images.githubusercontent.com/5929170/105062823-fde29f00-5ab5-11eb-8d05-866ef5af3b08.gif)

按照xray的分流配置，应该没有经过VPS，看起来工作正常。

**Comment by 70599** [comment]
我如下尝试只使用一个阿里的DoH服务器，好像不怎么出错（方便反复编辑，改成yaml格式了）。
```yaml
dns:
  hosts:
    服务器1_URL: 服务器1_IP
    服务器2_URL: 服务器2_IP
    dns.google: 8.8.8.8
    dns.alidns.com: 223.5.5.5
    
  servers:
  - address: 1.1.1.1
    domains:
    - geosite:geolocation-!cn
  - address: https+local://223.5.5.5/dns-query
    domains:
    - geosite:cn
    expectIPs:
    - geoip:cn
  - 8.8.8.8
  - 114.114.114.114
```

偶发原理不明的错误：
```
[Error] app/dns: failed to retrieve response for 服务器1_URL. > DOH server returned code 500
```

是这样发生的吗：

1. 需要查询某域名，进入`dns.servers[0]`
2. `dns.servers[0].address`是`1.1.1.1`，按分流规则需要走proxy
3. proxy的服务器是`服务器1_URL`，需要解析成IP
4. （不知道因为什么）跳过了`dns.hosts`，进入`dns.servers[1]`查询`服务器1_URL`的IP
5. `dns.servers[1]`返回了500错误

为什么会跳过`dns.hosts`呢？
它不是优先级最高吗？

**Comment by 70599** [comment]
我把光猫改成桥接，用路由器pppoe拨号以后，这个故障（不完全）消失了。。。
同样的错误还是会出，但是少了很多。

**Comment by Oakento** [comment]
同样是光猫桥接+路由器pppoe拨号，但这个故障依旧大量发生。。。
```json
{
    "inbounds": [
        {
            "listen": "127.0.0.1",
            "port": 53,
            "protocol": "dokodemo-door",
            "tag": "dns-in",
            "settings": {
                "address": "8.8.8.8",
                "port": 53,
                "network": "tcp,udp"
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "dns",
            "tag": "dns-out"
        }
    ],
    "dns": {
        "tag": "dns",
        "hosts": {
            "doh.alidns.com": "223.5.5.5",
        },
        "servers": [
            "https://doh.alidns.com/dns-query"
        ]
    }
}
```
然后出来一堆context deadline exceeded
```
2021/02/26 19:22:29 [Info] app/dns: DOH//doh.alidns.com querying: vortex.data.microsoft.com.
2021/02/26 19:22:29 [Info] app/dispatcher: default route for tcp:doh.alidns.com:443
2021/02/26 19:22:29 [Info] proxy/dns: handling DNS traffic to tcp:doh.alidns.com:443
2021/02/26 19:22:29 [Info] app/dns: DOH//doh.alidns.com querying: vortex.data.microsoft.com.
2021/02/26 19:22:29 [Info] app/dispatcher: default route for tcp:doh.alidns.com:443
2021/02/26 19:22:29 [Info] proxy/dns: handling DNS traffic to tcp:doh.alidns.com:443
2021/02/26 19:22:29 [Info] app/dns: failed to lookup ip for domain assets.gitlab-static.net at server DOH//doh.alidns.com > context deadline exceeded
2021/02/26 19:22:29 [Error] app/dns: failed to retrieve response for assets.gitlab-static.net. > Post "https://doh.alidns.com/dns-query": context deadline exceeded
2021/02/26 19:22:29 [Info] app/proxyman/outbound: failed to process outbound traffic > proxy/dns: connection ends > context deadline exceeded
```
