### ISSUE TITLE
REALITY protocol是否支持websocket和cdn转发

### ISSUE THREAD

**Issue by jiamingl98** [XTLS/Xray-core#1861]
看到的REALITY protocol 配置案例都是基于tcp协议 想问一下该协议是否支持ws+cdn

**Comment by RPRX** [comment]
不支持

**Comment by RPRX** [comment]
总有人想给 REALITY 套 CDN，想啥呢。。。最基本的，域名不是你的，CDN 怎么会把流量转发给你。。。如果域名是你的，那么 REALITY / Vision 这些想套 CDN 需要 CDN 开 TCP 层面的端口转发，通常不是免费的。
