### ISSUE TITLE
problem with trojan-grpc-caddy

### ISSUE THREAD

**Issue by arashammm** [XTLS/Xray-core#1862]
hello there.
I tried to configure  trojan-grpc-caddy server
when I tried to access in browser my servicename which is https://mydomain.com/abc I get error not found from caddy 
Also in xray logs I don't see anything hitting xray which means there is problem redirectin grpc request from caddy to xray core.
I use xray 1.8.0 

my caddy file :

> mydomain.com:443 {
>         @grpc {
>                 protocol grpc
>                 path  /abc/*
>         }
>         reverse_proxy @grpc unix//dev/shm/Xray-Trojan-gRPC.socket {
>                 transport http {
>                         versions h2c
>                 }
>         }
> root * /usr/share/caddy
>         file_server
> 
>  log {
>     output file /root/supg.log
>     level INFO
>   }
> }
> 

my xray server.json

> 
> {
>   "log": {
>     "loglevel": "warning"
>   },
>   "inbounds": [
>     {
>       "listen": "/dev/shm/Xray-Trojan-gRPC.socket,0666",
>       "protocol": "trojan",
>       "settings": {
>         "clients": [
>           {
>             "password" : "123"  
>           }
>         ]
>       },
>       "streamSettings": {
>         "network": "grpc",
>         "grpcSettings": {
>           "serviceName" : "/abc/"
>         }
>       }
>     }
>   ],
>   "outbounds": [
>     {
>       "tag": "direct",
>       "protocol": "freedom",
>       "settings": {}
>     },
>     {
>       "tag": "blocked",
>       "protocol": "blackhole",
>       "settings": {}
>     }
>   ],
>   "routing": {
>     "domainStrategy": "AsIs",
>     "rules": [
>       {
>         "type": "field",
>         "ip": [
>           "geoip:private"
>         ],
>         "outboundTag": "blocked"
>       }
>     ]
>   }
> }

what did I do wrong?

**Comment by RPRX** [comment]
请参考 https://github.com/lxhao61/integrated-examples
