### ISSUE TITLE
REALITY 客户端进程被killall再重启后，断连了几分钟，可能被墙了几分钟

### ISSUE THREAD

**Issue by fannwong001** [XTLS/Xray-core#1863]
我自己分析是被墙了。下面是详细过程：
一台虚拟机上运行openwrt(22.03)系统做旁路网关，上面运行xray([82b0955](https://github.com/XTLS/Xray-core/commit/82b09550d0596e7b2316f874d59c8e4131eb3c5a))
配置大概：
    "flow": ""
    "network": "h2",
    "security": "reality",
    "fingerprint": "ios",
    "shortId": "",

1、手机连旁路网关；
2、windows不连旁路网关，同一个局域网，运行一个windows版的xray，与openwrt上的配置相同，版本相同，节点相同，监听http，chrome浏览器通过系统代理看油管视频；
3、手机登几个网站、看看油管之类的，锁屏；
4、在openwrt上killall xray，稍微等5秒，再手动启动xray

然后windows上的油管视频断了，手机也连不上网了，服务器收不到包了，openwrt上的日志：
2023/03/27 16:31:28 192.168.1.100:40164 accepted tcp:1.1.1.1:53 [tcp_redir >> a3eab3220c721]
2023/03/27 16:31:29 192.168.1.100:40166 accepted tcp:1.1.1.1:53 [tcp_redir >> a3eab3220c721]
2023/03/27 16:31:37 [Error] transport/internet/http: failed to dial to xxx.xxx.xxx.xxx:443 > dial tcp xxx.xxx.xxx.xxx:443: i/o timeout
然后要等好几分钟才能变好。

没有第2步的时候也是同样的情况，或者第2步里连的是naiveproxy的一个节点，也会断连(ssh通过这个节点代理远程被断线)
没有第3步的时候，也就是长时间没有连接建立，这时候执行第4步就没事。
（后来在windows上测试了一下，也是同样的情况，看着油管的时候暂停，不要关闭网页，然后关闭xray等几秒再重开）
可能这样突然断开再连接，会暴露某些特征？

**Comment by FranzKafkaYu** [comment]
需要统一一下被墙的定义。

"然后要等好几分钟才能变好"，这种情况不能称之为被墙，请修改一下描述，避免误导。

**Comment by fannwong001** [comment]
> 需要统一一下被墙的定义。
> 
> 
> 
> "然后要等好几分钟才能变好"，这种情况不能称之为被墙，请修改一下描述，避免误导。

服务端都收不到包了，我个人认为是被墙了，虽然时间不长，但也有十来分钟，应该被墙检测到了某些特征。我在标题上加个时长吧，这个具体有几分钟我没有计算，也不想再测试了，昨天晚上搞挂了一台，过了很久没好。

**Comment by RPRX** [comment]
如果你觉得是被 GFW 墙了，**至少同时用不同的网络来测试吧**，比如电脑连 OpenWrt，手机开流量

**假如你的节点有很多人用，其中一个客户端突然关机会导致所有人突然用不了？我觉得不太现实**

**Comment by fannwong001** [comment]
> 如果你觉得是被 GFW 墙了，**至少同时用不同的网络来测试吧**，比如电脑连 OpenWrt，手机开流量
> 
> 
> 
> **假如你的节点有很多人用，其中一个客户端突然关机会导致所有人突然用不了？我觉得不太现实**

用手机流量确认了，nc命令可以连通server的443端口，宽带局域网内连不通。应该是带着源ip目的ip一起被墙的，至于是运营商还是gfw就不知道了。我前面不是说只有目的ip被墙。

重启客户端这个触发条件确实很奇怪，今天发现服务端重启一下也会引起断流几分钟。
挂代理连ssh的时候也容易断线一下。
然后这个ip好像被我玩坏了，以前用过的几个serverName都不好使了，用不了几分钟就断了，然后就换成了同网络另一个节点的hostname，这样用起来就正常了，只要不在使用时重启就没事。
最近确实不好翻了，前些天flow选vison就经常断流了，后来换成新版本，换了服务器节点，改用了h2。

我说的这些也只是我自己的真实情况提供给你们参考，我也不是专业测试人员，具体该怎么处理还是看你们需要。

**Comment by RPRX** [comment]
我觉得大概率是你本地网络相关配置的问题，小概率是你本地线路的问题
