### ISSUE TITLE
Please DO NOT ask questions here / 这里（issues）仅用于提出潜在 bug

### ISSUE THREAD

**Issue by RPRX** [XTLS/Xray-core#1878]
这里（issues）仅用于提出潜在 bug，不会用 Xray 请去 [Project X 群](https://t.me/projectXray) 求助，解决速度最快，未解决、其它问题可以发到 [Discussions](https://github.com/XTLS/Xray-core/discussions)

v1.8.1 后会加 issue templates

其实已经写好了，但是 v1.8.0 REALITY show 会输出密文 Session ID，可用于匹配，贴日志的人不一定会码掉，所以暂时没放上来

**Comment by FranzKafkaYu** [comment]
@RPRX we need issue template for now.

**Comment by yuhan6665** [comment]
Closing since we have the issue template
