### ISSUE TITLE
功能请求:brew仓库支持安装apple silicon版本

### ISSUE THREAD

**Issue by TinyFlag** [XTLS/Xray-core#188]
@N4FA @xiruizhao 现已有macos-arm64版本二进制,请求支持安装arm版

**Comment by xiruizhao** [comment]
Done. https://github.com/xiruizhao/homebrew-xray/commit/7fc41630be3e5a765924a182dbf2b805c4f76189

**Comment by rprx** [comment]
@N4FA 的等他看到应该会处理

顺便一提，目前 M1 的版本是直接用 Go 1.16 beta1 编译的，Reproducible

**Comment by TinyFlag** [comment]
现在 @xiruizhao 的仓库提交记录中写了1.2.3但是其中的脚本还是1.2.2

**Comment by xiruizhao** [comment]
抱歉sed没写对，现在改好了。

**Comment by rprx** [comment]
@KyonCN
