### ISSUE TITLE
tiktok相关域名被归到cn？

### ISSUE THREAD

**Issue by iwoomi** [XTLS/Xray-core#1886]
我是使用[XTLS/Xray-install](https://github.com/XTLS/Xray-install)一键脚本安装的xray
```bash
bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install
```

服务器端添加以下路由后，导致tiktok.com被完全阻断，而去掉之后它就不阻断，所以一定是因为xray的geosite.dat把tiktok域名归到cn了，不知道xray的geosite.dat是来自哪个上游？
```
{
    "type": "field",
    "outboundTag": "block",
    "domain": [
        "geosite:cn"
    ]
}
```

我在[v2fly/domain-list-community](https://github.com/v2fly/domain-list-community)提问了[issues/1585](https://github.com/v2fly/domain-list-community/issues/1585)，但v2fly的是归到非cn的。

**Comment by h2ch** [comment]
@iwoomi 这个看安装脚本里geosite部分就知道安装的哪一个，当然你也可以fork一下自己构建需要的

**Comment by h2ch** [comment]
@iwoomi 看了下脚本，xray用的是download_link_geosite="https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat"

**Comment by iwoomi** [comment]
> @iwoomi 看了下脚本，xray用的是download_link_geosite="https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat"

感谢提醒，已经在那边问过了，那个说是有问题没解决，我去安装脚本那儿提个issue，去建议使用[Loyalsoldier/domain-list-custom](https://github.com/Loyalsoldier/domain-list-custom)
