### ISSUE TITLE
@RPRX        http传输层的文档 和 回落的文档 发生冲突

### ISSUE THREAD

**Issue by architecturers** [XTLS/Xray-core#1888]
![屏幕截图 2023-04-03 004337](https://user-images.githubusercontent.com/26484669/229367054-46aa33e3-74ca-4b56-b63b-f25755080a28.png)
这是http传输配置的文档 说明http传输层 可以使用回落

![屏幕截图 2023-04-03 004443](https://user-images.githubusercontent.com/26484669/229367084-37492207-4639-4efb-abe8-bb0f9fd5f3d6.png)
这是回落的文档 说明要使用回落 传输层只能是tcp

http传输层可以使用回落吗？
vless +回落 +http传输层

**Comment by RPRX** [comment]
任何配置都能用回落，建议有 TLS 或 REALITY

**Comment by architecturers** [comment]
那也就是说 回落的文档错了
