### ISSUE TITLE
后续大佬会支持XTLS的MUX功能吗

### ISSUE THREAD

**Issue by ywyha** [XTLS/Xray-core#189]
如题

**Comment by rprx** [comment]
XTLS 原理上暂不支持 MUX（文档可能有说明）

**Comment by ywyha** [comment]
> XTLS 原理上暂不支持 MUX（文档可能有说明）

感谢大佬解惑，谢谢

**Comment by badO1a5A90** [comment]
> XTLS 原理上暂不支持 MUX（文档可能有说明）

XTLS 原理剖析待你填坑。
