### ISSUE TITLE
v2ray infra/conf: unknown cipher method: aes-256-cfb

### ISSUE THREAD

**Issue by jeffery9** [XTLS/Xray-core#1890]
v2rayU  report ' v2ray infra/conf: unknown cipher method: aes-256-cfb '

**Comment by jeffery9** [comment]
ref  https://github.com/yanue/V2rayU/issues/1109

**Comment by SakuraSakuraSakuraChan** [comment]
https://github.com/v2fly/v2ray-core/pull/235
预期行为，一定要用的话按照上面PR的日期去找更早的版本

**Comment by jeffery9** [comment]
v2fly/v2ray-core/pull/566

**Comment by jeffery9** [comment]
v2fly/v2ray-core/pull/566 
 
从 https://github.com/v2fly/v2ray-core/releases/tag/v4.34.0 去掉了 这些 cipher

**Comment by jeffery9** [comment]
v2fly/v2ray-core/pull/566 
 
从 https://github.com/v2fly/v2ray-core/releases/tag/v4.34.0 去掉了 这些 cipher

> 

应该使用此版本之前的  https://github.com/v2fly/v2ray-core/releases/tag/v4.34.0
