### ISSUE TITLE
请教一些关于Reality回落的问题

### ISSUE THREAD

**Issue by WROIATE** [XTLS/Xray-core#1891]
目前如果我不配置fallback，访问自己的域名，会回落Reality到dest，这时我的域名与dest真实证书就会不匹配，显示证书错误，那是不是需要同时配置https的回落和tls的回落？

**Comment by chika0801** [comment]
发下具体配置才能分析

**Comment by chika0801** [comment]
懂你问的意思了。你上面发的报错是正常的。要测试的方法是，你改WIN的HOSTS文件，把VPS的IP对应到你dest网站的网址。

然后关开浏览器（确保HOSTS已生效），在浏览器输入DEST的网址，显示DEST网站的内容。这样来验证。

**Comment by ixxmu** [comment]
这一定是不正常的，访问你域名追过去一看证书是错误的，应该是需要配置默认回落的，至今都没有配置说明出来，不知道这里的回落是不是这样用的

**Comment by WROIATE** [comment]
@ixxmu 
这个问题从原理上来说是符合预期的，因为访问机器时是通过直连IP+指定SNI标识进行的TLS链接，全程不包含自己的域名信息，理论上你只需要在nginx前置代理上针对IP直连的请求返回444就可以避免被追查（毕竟中间人得不到你真实域名的情况下也只能通过IP来链接）

@chika0801 
我其实是想了解下，Reality是只针纯TLS进行伪装吗？已经不再考虑应用层HTTPS了吗？是默认中间人探测重放也只会根据TLS来吗？如果用户不像我上述一样，针对IP直连的请求进行拒绝，那暴露的可能性是不是会很高呢（毕竟IP直连后是会返回dest证书的，其中包含了dest的域名信息，探测人通过WHOIS数据库查询域名信息或者通过遍历dns查询到IP与域名不对等，是不是会直接暴露）

**Comment by chika0801** [comment]
等REALITY更新文档。或看看

REALITY工作原理零碎
https://github.com/XTLS/Xray-core/issues/1734#issuecomment-1453135481
https://github.com/XTLS/Xray-core/issues/1701#issuecomment-1442150048
https://github.com/XTLS/Xray-core/issues/1697#issuecomment-1441215569
https://github.com/XTLS/Xray-core/issues/1697#issuecomment-1441246622
https://github.com/XTLS/Xray-core/issues/1588#issuecomment-1415861613

**Comment by heibailiangxiangwang20** [comment]
> 等REALITY更新文档。或者看看
> 
> 现实工作原理零碎 [#1734（评论）](https://github.com/XTLS/Xray-core/issues/1734#issuecomment-1453135481) [#1701（评论）](https://github.com/XTLS/Xray-core/issues/1701#issuecomment-1442150048) [#1697（评论）](https://github.com/XTLS/Xray-core/issues/1697#issuecomment-1441215569) [#1697（评论）](https://github.com/XTLS/Xray-core/issues/1697#issuecomment-1441246622) [#1588（评论）](https://github.com/XTLS/Xray-core/issues/1588#issuecomment-1415861613)

我想请教一下，如果排除省钱买域名，自己配置这些因素的话，到底是偷别人的好，还是偷自己的安全？
其实我们接触v2ray-xray已经好几年了，在加上您那里有很全面的配置文件，所以配置对我们来说不是大问题，在加上一个域名就几块钱的事。所以我只想知道这两种偷法到底哪个安全，能抗防火墙。
我只想更安全，不被封ip端口这些，但从不怕繁琐的配置

**Comment by chika0801** [comment]
我觉得偷别人还是偷自己区别是这样的。你偷别人，万一别人网站VPS挂了，你就不通，别人的因素你无法100%排除，就这而以。

**Comment by heibailiangxiangwang20** [comment]
> 我觉得偷别人还是偷自己区别是这样的。你偷别人，万一别人网站VPS挂了，你就不通，别人的因素你无法100%排除，就这而以。
> 
> 你换个角度想偷自己，自己VPS挂了，你肯定也连不通，排查就方便点吧。

感谢大神回复，那就是基本也没啥区别了

**Comment by ixxmu** [comment]
> 

是 符合预期的，这种用法也是没有问题，但是从浏览器访问你的域名A，但是实际上显示却是域名B的证书，对浏览器或者用户来说就是不正常的；

1.8.0的 vision 解决了TLS in TLS的问题，新的 reality 解决的 SNI 名单阻断问题，具体可看之前讨论的TLS的**[生死5包](https://github.com/XTLS/Xray-core/discussions/1295)**；

不了解背后的代码实现，但是 shadowTLS 目前是可以国内外域名通吃，几乎不挑域名（v3需要挑域名），不知道为何reality对域名的要求这么严格，求大神解答或者等正式的release吧

**Comment by chika0801** [comment]
> 但是从浏览器访问你的域名A，但是实际上显示却是域名B的证书，对浏览器或者用户来说就是不正常的；

你客户端地址填vps的 ip

**Comment by RPRX** [comment]
这个 issue 我没看，只想回复这一句：

> 不了解背后的代码实现，但是 shadowTLS 目前是可以国内外域名通吃，几乎不挑域名（v3需要挑域名），不知道为何reality对域名的要求这么严格，求大神解答或者等正式的release吧

https://github.com/XTLS/REALITY/pull/2#issuecomment-1479956295

**简单来说，不是能不能的问题，而是应不应该的问题，这些协议握手时要连接目标服务端，你的国外机器填个国内域名合适吗**

这个原因是非常显而易见的啊，写模板时我以为一笔带过提醒一下，大家就明白了，~~真的是我高估了~~

**Comment by Ymjie** [comment]
借楼问一下，如果多台服务器配置REALITY 使用同一对privateKey、publicKey 会有什么安全问题吗？

**Comment by chika0801** [comment]
> 借楼问一下，如果多台服务器配置REALITY 使用同一对privateKey、publicKey 会有什么安全问题吗？

我几台vps就这样用的shortid也一样，自己1个人用，主要是方便点

**Comment by GreatMichaelLee** [comment]
> 借楼问一下，如果多台服务器配置REALITY 使用同一对privateKey、publicKey 会有什么安全问题吗？

用passwall给reality节点配负载均衡，必须用同样的key啊，没啥问题。

**Comment by LOpSSH** [comment]
> 你可以配置本地ng 转发example.com 然后你的域名配置ssl这样就显示正常了。

不是很懂你说的，可以提供一个location片段吗？

**Comment by Misaka-blog** [comment]
@AminA193 no thx 😅
