### ISSUE TITLE
xr.exe改名为v2ray.exe在v2rayN使用。设置里开启MUX不选，就连接失败。

### ISSUE THREAD

**Issue by fangshixiong** [XTLS/Xray-core#19]
我是把xr.exe改名为v2ray.exe，放在v2rayN中使用。

这时候在v2rayn的设置里，开启MUX选项，是选中，生成的config文件中，MUX值是false。正常代理，可以打开网页。

在v2rayn的设置里，开启MUX选项，不选中，生成的config文件中，MUX是false。连接失败，不能打开网页。

**Comment by fangshixiong** [comment]
连接的服务器换成VMESS协议

这时候在v2rayn的设置里，开启MUX选项，是选中，生成的config文件中，MUX值是true。正常代理，可以打开网页。

在v2rayn的设置里，开启MUX选项，不选中，生成的config文件中，MUX是false。正常代理，可以打开网页。

**Comment by rprx** [comment]
可否重新描述一下

**Comment by fangshixiong** [comment]
> 可否重新描述一下

windows客户端 v2rayN V3.27
下载Xray-core v1.0.0的Xray-windows-64.zip，将.exe.改名为v2ray.exe，放入v2rayN使用。

我的VPS使用bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh) --remove卸载了v2ray-core。使用 bash <(curl -L https://raw.githubusercontent.com/XTLS/Xray-install/main/install-release.sh) 安装好xray。并在VPS上修改好了xray的config文件，确认是使用VLESS+xtls readv。

----------------------------------------------------------------------------------------------------

进入v2rayN填好服务器的各信息。v2rayn—参数设置—开启MUX多路复用 选中，正常代理上网。     查看v2rayN文件内的config文件"mux": {        "enabled": false,   "concurrency": -1


v2rayn—参数设置—开启MUX多路复用 不选中，打不开任何网页，不能上网。     查看v2rayN文件内的config文件"mux": {        "enabled": false,   "concurrency": -1

**Comment by rprx** [comment]
我知道 v2rayN 会在使用 XTLS 时自动关闭用户选的 Mux，难道用户没选 Mux 时会反过来吗。。。看起来也不是啊

对比两个配置文件的不同之处看看

**Comment by fangshixiong** [comment]
> 我知道 v2rayN 会在使用 XTLS 时自动关闭用户选的 Mux，难道用户没选 Mux 时会反过来吗。。。看起来也不是啊
> 
> 对比两个配置文件的不同之处看看

你好，我对比了两个配置文件。配置文件的内容完全一样。

我已经在v2rayN提交了这个反馈了。

**Comment by fangshixiong** [comment]
> 我知道 v2rayN 会在使用 XTLS 时自动关闭用户选的 Mux，难道用户没选 Mux 时会反过来吗。。。看起来也不是啊
> 
> 对比两个配置文件的不同之处看看
你好，我发现原因了

启动V2rayN程序，LOGO如下，是启动服务Xray 1.0.0。

配置成功
[VLESS] 搬瓦工 日本(kotori***club:443)
启动服务(2020/11/29 18:56:16)...
Xray 1.0.0 (Xray, Penetrates Everything.) Custom (go1.15.5 windows/amd64)
A unified platform for anti-censorship.
2020/11/29 18:56:16 [Info] github.com/xtls/xray-core/v1/main/jsonem: Reading config: C:\v2rayN\config.json




我在 v2rayn—参数设置—开启MUX多路复用 不选中 ，确定。  是启动服务V2Ray 4.33.0 ，就不能上网。

配置成功
[VLESS] 搬瓦工 日本(kotori***club:443)
启动服务(2020/11/29 18:57:41)...
V2Ray 4.33.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.5 windows/amd64)
A unified platform for anti-censorship.
2020/11/29 18:57:41 [Info] v2ray.com/core/main/jsonem: Reading config: C:\v2rayN\config.json



需要在V2rayN软件里，选中我的那个配置，按回车。重新载入。就正常了

配置成功
[VLESS] 搬瓦工 日本(kotori***club:443)
启动服务(2020/11/29 18:58:52)...
Xray 1.0.0 (Xray, Penetrates Everything.) Custom (go1.15.5 windows/amd64)
A unified platform for anti-censorship.
2020/11/29 18:58:52 [Info] github.com/xtls/xray-core/v1/main/jsonem: Reading config: C:\v2rayN\config.json
