### ISSUE TITLE
socks 在 `Inbound` 中的行为

### ISSUE THREAD

**Issue by xqzr** [XTLS/Xray-core#1901]
服务器 有两个 IP（A、B）入站开了个 socks。
地址 A 收到客户端请求，却用 地址 B 回复 客户端（UDP）。

由于客户端（蜂窝网），不能被动接受包，导致 UDP 不通。

地址 B 通过“隐私扩展”（rfc3041）生成。

**Comment by rurirei** [comment]
could you target the IPv6 privacy extension ip addr?

**Comment by xqzr** [comment]
客户端使用 地址 B 请求时，UDP 通。因为 服务端使用 地址 B 回复

**Comment by rurirei** [comment]
xray brings the udp cone-nat here as this is a question about your network situation only.

**Comment by xqzr** [comment]
https://t.me/projectXray/2307557

**Comment by rurirei** [comment]
sorry as no Telegram.

> https://t.me/projectXray/2307557

**Comment by chika0801** [comment]
> sorry as no Telegram.
> 
> > https://t.me/projectXray/2307557

![photo_2023-04-30_01-40-51](https://user-images.githubusercontent.com/88967758/235355286-6b9fd63f-e94e-48d8-8dce-5c550cdbff1a.jpg)
看到你这个issue，我也遇到了（linux服务器，SLAAC地址，纯内网跨VLAN），原因应该是rfc3041生成的地址路由优先级高于EUI64，你试试用源进源出能不能解决。 RFC3041本就是为了隐藏 SLAAC获取的地址.
