### ISSUE TITLE
内置dns服务器outbound不走leastPing balancer

### ISSUE THREAD

**Issue by Smoovsky** [XTLS/Xray-core#1902]
如题，当内置dns服务器通过routing rule匹配到leastPing balancer类型的outbound的时候会跳过并且走默认outbound（等于什么都没匹配到）。
把strategy改到random问题就好了; 这个问题在只有一个leastPing balancer的时候也会被触发。

之前一直没有发现，直到上周8888返回的结果开始被污染了才发现。

可能相关：#1792

**Comment by Fangliding** [comment]
still exits？
