### ISSUE TITLE
~Xray core Change

### ISSUE THREAD

**Issue by YRS200** [XTLS/Xray-core#1905]
hi guys! do you knopw how to change  xray core version i want to change it older version what commands do i need to use can anyone help me plz!

**Comment by nursery01** [comment]
```
git clone -b v1.8.0 [https](https://github.com/XTLS/Xray-core.git)
go build ./main.go
```

**Comment by YRS200** [comment]
![image](https://user-images.githubusercontent.com/110148911/230531208-0369f4a9-e637-465f-8db0-b91de8a12b0f.png)
it is giving error

**Comment by chika0801** [comment]
https://github.com/chika0801/Xray-install/blob/main/compile_Xray-core.md

或者你去下载编译好的文件

**Comment by YRS200** [comment]
![image](https://user-images.githubusercontent.com/110148911/230531509-c344a5af-4d46-4b26-ad35-fd4f9b259244.png)
i am using some autoscript and here is some xray services not running i have my other server that everything is ok but if i install it to my new server it is not running any solution the other server's xray core version is 1.7.2 also want to change it to 1.7.2

**Comment by YRS200** [comment]
![image](https://user-images.githubusercontent.com/110148911/230531816-288419a2-166d-4b42-aab1-1246f3144b0b.png)
my xray is located here

**Comment by chika0801** [comment]
通常要更新xray的版本，就替换你vps上面的xray文件，重启xray后就生效了。

你的问题是什么？

**Comment by YRS200** [comment]
xray service is not running check below screenshot plz!

**Comment by YRS200** [comment]
> 通常要更新xray的版本，就替换你vps上面的xray文件，重启xray后就生效了。
> 
> 你的问题是什么？

xray service is not running check below screenshot plz!

**Comment by YRS200** [comment]
> xray service is not running check below screenshot plz!

我认为问题出在 xray-core 版本

**Comment by nursery01** [comment]
Sorry , I didn't check my code.

Edited

**Comment by nursery01** [comment]
> > xray service is not running check below screenshot plz!
> 
> 
> 
> 我认为问题出在 xray-core 版本

這是你的自動化shell有問題，這不屬於xray的問題

**Comment by YRS200** [comment]
你能帮忙修一下吗？

**Comment by Fangliding** [comment]
Not a core issue
