### ISSUE TITLE
无法通过trojan xtls协议连接POE(流放之路)

### ISSUE THREAD

**Issue by lizkes** [XTLS/Xray-core#191]
服务器是腾讯云轻量香港，使用trojan+xtls卡在载入界面无法进入游戏。
[服务端日志](https://pastebin.ubuntu.com/p/wb2Nn2DGT4/)
[客户端日志](https://pastebin.ubuntu.com/p/Y878rCrPyN/)
[服务端配置](https://pastebin.ubuntu.com/p/x3yfknyzrx/)
[客户端配置](https://pastebin.ubuntu.com/p/CxN874dv6T/)

奇怪的是，相同配置的aws日本服务器可以正常进入。
[服务端日志](https://pastebin.ubuntu.com/p/JSxpWBpggc/)
[客户端日志](https://pastebin.ubuntu.com/p/hgvHScYTfD/)
[服务端配置](https://pastebin.ubuntu.com/p/9BFXK8F9P9/)
[客户端配置](https://pastebin.ubuntu.com/p/2yPWNqjBNv/)

**Comment by lizkes** [comment]
@lizkes 这个

**Comment by rprx** [comment]
建议检查服务器防火墙是否一致

**Comment by lizkes** [comment]
@rprx 都是全开的

**Comment by lizkes** [comment]
腾讯云防火墙
![图片](https://user-images.githubusercontent.com/20457790/105157359-ddfbbb80-5b47-11eb-9d0b-d80083cdbdd3.png)

**Comment by jiuqi9997** [comment]
@lizkes 那就更怪了，先试试ss行不行吧

**Comment by rprx** [comment]
发现的一些区别：

1. 上面的连接的是 web.poecdn.com:80，下面的连接的是 web.poecdn.com:443，但上面的更早，客户端应该有重定向缓存
2. 下面的有通往 443 端口的 udp 包，上面的没有

**Comment by lizkes** [comment]
> 
> 
> 发现的一些区别：
> 
>     1. 上面的连接的是 web.poecdn.com:80，下面的连接的是 web.poecdn.com:443，但上面的更早，客户端应该有重定向缓存
> 
>     2. 下面的有通往 443 端口的 udp 包，上面的没有

这游戏是TCP连接的，官方说不会发UDP包。
我觉得应该就是端口的问题，用腾讯云代理，本地发的是web.poecdn.com:80连接，导致连不上

**Comment by rprx** [comment]
@lizkes 你现在重新测试一下看看

**Comment by lizkes** [comment]
破案了，是腾讯云服务器的IP段被POE封了。
阿里云服务器使用相同配置可以正常连通（垃圾腾讯）。
