### ISSUE TITLE
Bug in adding vless user using api : flow is ignored 

### ISSUE THREAD

**Issue by hiddify-com** [XTLS/Xray-core#1917]
Using api it is not possible to create user without flow.

The client successfully works with xtls-xrpx-vission but it won't work with normal tls.

It is notable to mention that not adding the flow in config file cause clients working fine but when create with api, it includes the client with xtls-xrpx-vission

**Comment by RPRX** [comment]
> Using api it is not possible to create user without flow.

根据代码，应该没有这个限制
