### ISSUE TITLE
一个小小BUG，路由匹配规则时会区分大小写

### ISSUE THREAD

**Issue by CatSamaDD** [XTLS/Xray-core#192]
域名下的路径是区分大小写的，但是域名是不区分大小写的。
Xray匹配路由规则时会把域名区分大小写。
打个比方，我设置abc123.com 走 dircert 
然后访问 ABC123.COM 的时候就不会匹配这个规则
但其实他们是同一个域名。
一般浏览器会把域名大写字母自动转成小写，但是有些软件是不会的，比如我之前反应FTPS连接问题时用的FileZilla。
![QQ截图20210120205101](https://user-images.githubusercontent.com/34727840/105177150-31591400-5b1e-11eb-80bc-440917ddd205.png)

**Comment by rprx** [comment]
匹配前应当 strings.ToLower

**Comment by rprx** [comment]
https://github.com/XTLS/Xray-core/commit/5aa053a65fd8888a2a7c8c32ab12e0afe89ebb06

**Comment by rprx** [comment]
https://github.com/XTLS/Xray-core/releases/tag/v1.2.3
