### ISSUE TITLE
WireGuard outbound 在 FakeDNS 下无法访问外网

### ISSUE THREAD

**Issue by zengbo** [XTLS/Xray-core#1922]
Xray 使用 WireGuard 协议做为 outbound， 同时开启了 FakeDNS，访问网站的时候会提示服务被断开，感觉是使用 FakeDNS 返回的 FakeIP 访问的时候，WireGuard 协议没有去用 FakeIP 查询真实的域名，而是直接用这个 FakeIP 访问了。

**Comment by h2ch** [comment]
@zengbo 使用了fakeip，访问不会走服务端的路由设置，个人已经体验证实了，需要走服务端路由，先关闭fakeip，待后续看有佬摆弄摆弄一下不

**Comment by h2ch** [comment]
@zengbo 又或者说服务端需要把fakeip也加进路由… fakeip非刚需没研究过

**Comment by Fangliding** [comment]
没有配置
