### ISSUE TITLE
请问xray怎么调用啊?

### ISSUE THREAD

**Issue by tess1199** [XTLS/Xray-core#1927]
我是客户端. 如果用命令行模式以这个服务器打开, 需要什么命令呢?
vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogIue+juWbveOAkOS7mOi0ueaOqOiNkO+8mmh0dHBzOi8vdHQudmcvdmlw44CRMzA2IiwNCiAgImFkZCI6ICJjZi1sdC1kbnMuc2hhcmVjZW50cmUub25saW5lIiwNCiAgInBvcnQiOiAiODAiLA0KICAiaWQiOiAiODIzYzMxZGEtNzAxZi00ODNkLWIzNmUtODk2ZTVjZjA5ODdhIiwNCiAgImFpZCI6ICIwIiwNCiAgInNjeSI6ICJhdXRvIiwNCiAgIm5ldCI6ICJ3cyIsDQogICJ0eXBlIjogIm5vbmUiLA0KICAiaG9zdCI6ICJueTEuc2hhcmVjZW50cmVwcm8ub3JnIiwNCiAgInBhdGgiOiAiL3NoaXJrZXIiLA0KICAidGxzIjogIiIsDQogICJzbmkiOiAiIiwNCiAgImFscG4iOiAiIg0KfQ==

解码后是这个信息:
{
  "v": "2",
  "ps": "美国【付费推荐：https://tt.vg/vip】306",
  "add": "cf-lt-dns.sharecentre.online",
  "port": "80",
  "id": "823c31da-701f-483d-b36e-896e5cf0987a",
  "aid": "0",
  "scy": "auto",
  "net": "ws",
  "type": "none",
  "host": "ny1.sharecentrepro.org",
  "path": "/shirker",
  "tls": "",
  "sni": "",
  "alpn": ""
}

好像也没有什么实例之类的, 去哪里找用法?

**Comment by FranzKafkaYu** [comment]
@tess1199 内核不支持直接识别分享链接，你需要的是将分享链接转化为配置文件，这一般是GUI客户端做的事。

**Comment by tess1199** [comment]
> @tess1199 内核不支持直接识别分享链接，你需要的是将分享链接转化为配置文件，这一般是GUI客户端做的事。

我想自己调用一下, 分享链接又很多种, 比如vless,vmess,ss,ssr,我怎么把各种不同 的转成统一的配置文件, 有没有格式的文档啊? 或者有没有已经写好的转换工具呢?

**Comment by FranzKafkaYu** [comment]
> > @tess1199 内核不支持直接识别分享链接，你需要的是将分享链接转化为配置文件，这一般是GUI客户端做的事。
> 
> 我想自己调用一下, 分享链接又很多种, 比如vless,vmess,ss,ssr,我怎么把各种不同 的转成统一的配置文件, 有没有格式的文档啊? 或者有没有已经写好的转换工具呢?

开箱即用的应该没有，不过你可以借鉴GUI客户端源码。

**Comment by tess1199** [comment]
> > > @tess1199 内核不支持直接识别分享链接，你需要的是将分享链接转化为配置文件，这一般是GUI客户端做的事。
> > 
> > 
> > 我想自己调用一下, 分享链接又很多种, 比如vless,vmess,ss,ssr,我怎么把各种不同 的转成统一的配置文件, 有没有格式的文档啊? 或者有没有已经写好的转换工具呢?
> 
> 开箱即用的应该没有，不过你可以借鉴GUI客户端源码。

那请问如果有1w个地址, 怎么最快的验证呢? 导入gui客户端不太现实,也慢, 自己调用验证比较好, 有现成的程序吗?

**Comment by KouYiGuo** [comment]
参考 [vmessping](https://github.com/v2fly/vmessping) 自己写一段脚本或者 go 程序即可。
