### ISSUE TITLE
[疑问] streamSettings - sockopt - interface 参数对 UDP 流量不生效

### ISSUE THREAD

**Issue by IRN-Kawakaze** [XTLS/Xray-core#1930]
服务端出站配置：

```
    "outbounds": [
        {
            "tag": "warp",
            "protocol": "freedom",
            "settings": {},
            "streamSettings": {
                "sockopt": {
                    "interface": "wgcf"
                }
            }
        }
    ]
```

服务端策略路由：

```
root@hostname:/home/debian# ip rule
0:	from all lookup local
32764:	from 172.16.0.2 lookup 500
32765:	from all oif wgcf lookup 500
32766:	from all lookup main
32767:	from all lookup default

root@hostname:/home/debian# ip -6 rule
0:	from all lookup local
32764:	from 2606:4700:110:WIREGUARD:CLIENT:IPv6:ADDRESS:xxxx lookup 500
32765:	from all oif wgcf lookup 500
32766:	from all lookup main

root@hostname:/home/debian# ip route show table 500
default dev wgcf scope link
```

现象：
TCP 流量会遵循 streamSettings - sockopt - interface 参数，从 wgcf 网卡出站，但 UDP 流量不会。

测试方法：
比如客户端通过代理连接 UDP 流量（WebRTC或者WireGuard），或者服务端配置文件里增加以下 DNS 配置：

```
    "dns": {
        "servers": [
            "8.8.8.8"
        ]
    }
```

通过打开 WebRTC 测试网站、客户端连接 WireGuard+`tcpdump -i 本机网卡 -n udp and host ${WirGuard Server IP}`或客户端打开任意网站+`tcpdump -i 本机网卡 -n udp and host 8.8.8.8`抓包，可以发现对应的 UDP 流量经由本机网卡出站，而非 wgcf 网卡出站。

疑问：
1、这个现象是 Xray 的 BUG 还是策略路由与 UDP 流量的特性？（有[了解到](https://stackoverflow.com/questions/68796409/why-raw-udp-packet-does-not-follow-routing-rules) raw UDP 流量可能只能匹配上 to dst 的策略路由规则，实测 to dst 规则确实可以匹配上）

2、如果是策略路由与 UDP 流量的特性所致，interface 参数的正确食用方法是什么呢？（oif wgcf lookup 500 无法匹配上，from 172.16.0.2 lookup 500 也无法匹配上。如果使用 to dst lookup 500 的策略路由，则 UDP 流量去向就完全由策略路由决定，streamSettings - sockopt - interface 参数没有起到应有的作用）

**Comment by Fangliding** [comment]
已经修复
