### ISSUE TITLE
[bug] CIDR mismatch

### ISSUE THREAD

**Issue by Loyalsoldier** [XTLS/Xray-core#1933]
You guys should fix this old bug from V2Ray.

Reference: https://github.com/v2fly/v2ray-core/pull/1155
Solution: https://github.com/v2fly/v2ray-core/pull/1157

Note: https://github.com/inetaf/netaddr has been deprecated, use https://pkg.go.dev/go4.org/netipx instead.

**Comment by kdurov** [comment]
感谢帮开 issue。
我还想看看具体什么情况能 reproduce 后开的。

**Comment by RPRX** [comment]
感谢反馈
