### ISSUE TITLE
chatgpt解锁outbounds分流求教

### ISSUE THREAD

**Issue by jaesony** [XTLS/Xray-core#1934]
"routing": {
		"domainStrategy":"IPIfNonMatch",
		"rules": [
			{
				"type": "field",
				"domain": [
					"geosite:netflix",
					"openai.com"
				],
				"outboundTag": "warp"
			},
			{
				"type": "field",
				"ip": [
					"geoip:cn"
				],
				"outboundTag": "blocked"
			}
		]
	},
	"outbounds": [
		{
			"tag":"warp",
			"protocol": "socks",
			"settings": {
				"servers": [
					{
						"address": "127.0.0.1",
						"port": 40000
					}
				]
			}
		},
		{
			"protocol": "freedom"
		},
		{
			"tag": "blocked",
			"protocol": "blackhole"
		}
	],
用warp解锁chatgpt，"protocol": "freedom"不能能放在outbounds第一条，只能放后面，否则1020错误。奇怪的是Netflix解锁没问题

**Comment by jaesony** [comment]
找到原因了，前面连接用的是uds，改成端口就好了

**Comment by nuoooo** [comment]
> 

你是咋改就好的~
