### ISSUE TITLE
VLESS-XTLS-uTLS-REALITY 可以设置路径 path 吗？

### ISSUE THREAD

**Issue by bulesky89857** [XTLS/Xray-core#1938]
一直用vmess ws tls  使用path 分流到nginx，公用443端口，VLESS-XTLS-uTLS-REALITY可以和nginx公用443端口吗，如何设置？

**Comment by lxhao61** [comment]
https://github.com/lxhao61/integrated-examples/tree/main/Xray(M%2BK%2BB%2BG%2BA)%2BNginx

**Comment by bulesky89857** [comment]
> https://github.com/lxhao61/integrated-examples/tree/main/Xray(M%2BK%2BB%2BG%2BA)%2BNginx

谢谢，我看看

**Comment by bulesky89857** [comment]
> https://github.com/lxhao61/integrated-examples/tree/main/Xray(M%2BK%2BB%2BG%2BA)%2BNginx

算了，看不懂。。。

**Comment by chika0801** [comment]
建议翻墙和建站用不同vps，不推荐用n合1的协议配置（不好分锅）

**Comment by lxhao61** [comment]
WebSocket与gRPC有套CDN需求，合理的n合1的协议配置从来不是问题，只有使用问题：如目前不推荐直接使用WebSocket与gRPC的应用，而套CDN无碍。

**Comment by bulesky89857** [comment]
> > > https://github.com/lxhao61/integrated-examples/tree/main/Xray(M%2BK%2BB%2BG%2BA)%2BNginx
> > 
> > 
> > 算了，看不懂。。。
> 
> 这么详细的就看不懂，那无办法了（只有自我增强网络基础知识再看吧。）。

举步维艰

**Comment by bulesky89857** [comment]
> 建议翻墙和建站用不同vps，不推荐用n合1的协议配置（不好分锅）

感觉那样vps 有点浪费资源

**Comment by onlypurewater** [comment]
搜nginx sni分流教程，我用面板的就nginx软件那里加stream模块规则，网站nginx那里把监听端口改一下。还是很简单的。这样做还不影响以前已有域名配置下的path规则。

**Comment by newmacuser** [comment]
https://lala.im/8602.html
试试这个？也是nginx前置sni分流

**Comment by lxhao61** [comment]
> https://lala.im/8602.html 试试这个？也是nginx前置sni分流

奇葩！示例把简单问题（仅一个Xray的REALITY Vision配置即可）复杂化（加SNI分流），值得你推荐？
