### ISSUE TITLE
路由匹配规则不生效

### ISSUE THREAD

**Issue by Alion548** [XTLS/Xray-core#194]
使用v2rayNG，通过VLESS协议，发现国内IP不遵循分流规则，诡异的是相同的服务端配置Shadowrocket正常分流。
![image](https://user-images.githubusercontent.com/8340545/105285788-122ab700-5bf0-11eb-836d-132fc5597898.png)
![image](https://user-images.githubusercontent.com/8340545/105285989-6b92e600-5bf0-11eb-9d53-9cf65caf8384.png)
![image](https://user-images.githubusercontent.com/8340545/105285847-28387780-5bf0-11eb-98d8-e168030dd69a.png)

**Comment by AkinoKaede** [comment]
应该是配置错误，需要 domain 和 ip 同时满足，应该写成两条规则

```json
 {
        "ip": [
          "geoip:cn",
          "geoip:private"
        ],
        "inboundTag": [
          "In_vless_all"
        ],
        "outboundTag": "ou_direct",
        "type": "field"
      },
      {
        "domain": [
          "geosite:cn"
        ],
        "inboundTag": [
          "In_vless_all"
        ],
        "outboundTag": "ou_direct",
        "type": "field"
      }
```

**Comment by badO1a5A90** [comment]
> 使用v2rayNG，通过VLESS协议，发现国内IP不遵循分流规则，诡异的是相同的服务端配置Shadowrocket正常分流。
> ![image](https://user-images.githubusercontent.com/8340545/105285788-122ab700-5bf0-11eb-836d-132fc5597898.png)
> ![image](https://user-images.githubusercontent.com/8340545/105285989-6b92e600-5bf0-11eb-9d53-9cf65caf8384.png)
> ![image](https://user-images.githubusercontent.com/8340545/105285847-28387780-5bf0-11eb-98d8-e168030dd69a.png)

规则写在一条内,表示需要"同时成立",即你这条规则内的 所有条件 都满足,规则才会被匹配.
所以你的规则 同时有 domain 和 ip (即目标又是域名同时又是IP) 必然是不成立的.

**Comment by Alion548** [comment]
![image](https://user-images.githubusercontent.com/8340545/105327726-35faf680-5c0a-11eb-87c3-800cf42d9db7.png)
拆分这样也是没法匹配到

**Comment by rprx** [comment]
也就是说相同的服务端路由配置，客户端为 Shadowrocket 时服务端可以识别，但客户端为 v2rayNG 时不行？

**Comment by Alion548** [comment]
> 也就是说相同的服务端路由配置，客户端为 Shadowrocket 时服务端可以识别，但客户端为 v2rayNG 时不行？

是的，客户端我是全局流量走代理，在服务端做分流。

**Comment by rprx** [comment]
应该是流量被代理的形式不同（域名/IP），服务端加个嗅探试试

**Comment by Alion548** [comment]
> 应该是流量被代理的形式不同（域名/IP），服务端加个嗅探试试

从日志看都是IP形式，而且没有被匹配到，走默认出口了

**Comment by badO1a5A90** [comment]
建议发一下服务端的完整规则。

**Comment by Alion548** [comment]
``` json
{
    "log": {
        "access": "/var/log/v2ray_access.log",
        "error": "/var/log/v2ray_error.log",
        "loglevel": "debug"
    },
    "inbounds": [
        {
            "tag": "in_vless_all",
            "port": 5201,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "##",
                        "flow": "xtls-rprx-direct"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "alpn": [
                        "h2",
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "##",
                            "keyFile": "##"
                        }
                    ]
                }
            }
        }
    ],
    "outbounds": [
        {
            "tag": "ou_data",
            "protocol": "vmess",
            "settings": {
                "vnext": [
                    {
                        "address": "##",
                        "port": ##,
                        "users": [
                            {
                                "id": "##",
                                "security": "auto",
                                "alterId": 2
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "wsSettings": {
                    "path": "##",
                    "headers": {
                        "Host": "##"
                    }
                }
            },
            "mux": {
                "enabled": false,
                "concurrency": -1
            }
        },
        {
            "tag": "ou_direct",
            "protocol": "freedom",
            "settings": {
                "domainStrategy": "UseIPv4"
            }
        },
        {
            "tag": "ou_blackhole",
            "protocol": "blackhole",
            "response": {
                "type": "http"
            }
        }
    ],
    "routing": {
        "domainStrategy": "IPOnDemand",
        "rules": [
            {
                "type": "field",
                "network": "tcp,udp",
                "inboundTag": [
                    "se_dns"
                ],
                "outboundTag": "ou_direct"
            },
            {
                "type": "field",
                "network": "tcp,udp",
                "inboundTag": [
                    "in_vless_all"
                ],
                "ip": [
                    "geoip:private",
                    "geoip:cn"
                ],
                "outboundTag": "ou_direct"
            },
            {
                "type": "field",
                "network": "tcp,udp",
                "inboundTag": [
                    "in_vless_all"
                ],
                "domain": [
                    "geosite:cn"
                ],
                "outboundTag": "ou_direct"
            }
        ]
    },
    "dns": {
        "tag": "se_dns",
        "servers": [
            "127.0.0.1"
        ]
    }
}
```
![image](https://user-images.githubusercontent.com/8340545/105433389-756e2500-5c94-11eb-8adb-74dd4099b133.png)
![image](https://user-images.githubusercontent.com/8340545/105433536-c1b96500-5c94-11eb-908b-6fe8374baa45.png)

**Comment by Alion548** [comment]
大佬们可以复现不？

**Comment by SekiBetu** [comment]
与issue无关：建议把路由配置写在客户端进行，服务端运行不太方便修改

**Comment by Alion548** [comment]
> 与issue无关：我看到你的路由规则是在服务端使用的，建议把路由配置写在客户端进行，服务端运行不太方便修改
是的，不过我的需求需要让客户端走全局，在服务端再分流。目的是为了规避客户端网络环境的某些限制。

**Comment by badO1a5A90** [comment]
看了配置,感觉可能.是这样一种情形.

客户端没开嗅探, 也不是本地DNS解析.
所以当本地应用访问一个域名 abc.com 时.
首先 DNS 远程解析得到了一个最适合VPS的IP1.2.3.4(VPS如果在境外比如美西,那大概率不是国内IP)
然后本地应用向1.2.3.4发起连接, 流量进入xray(v2rayNG), 被代理到服务端
服务端根据1.2.3.4 分流至ou_data (其实是没有匹配)

或许你把嗅探勾上看一下是否可以,
这样 本地应用向1.2.3.4发起连接时,嗅探到abc.com,会把1.2.3.4替换成abc.com. 服务端就可以根据abc.com分流

**Comment by Alion548** [comment]
> 看了配置,感觉可能.是这样一种情形.
> 
> 客户端没开嗅探, 也不是本地DNS解析.
> 所以当本地应用访问一个域名 abc.com 时.
> 首先 DNS 远程解析得到了一个最适合VPS的IP1.2.3.4(VPS如果在境外比如美西,那大概率不是国内IP)
> 然后本地应用向1.2.3.4发起连接, 流量进入xray(v2rayNG), 被代理到服务端
> 服务端根据1.2.3.4 分流至ou_data (其实是没有匹配)
> 
> 或许你把嗅探勾上看一下是否可以,
> 这样 本地应用向1.2.3.4发起连接时,嗅探到abc.com,会把1.2.3.4替换成abc.com. 服务端就可以根据abc.com分流

v2rayNG 开启嗅探后就正常了。不过又发现一个问题：
服务端路由匹配使用 IPOnDemand 模式，遇到了
``` json
{
    "type": "field",
    "network": "tcp,udp",
    "inboundTag": [
        "in_vless_all"
    ],
    "ip": [
        "geoip:private",
        "geoip:cn"
    ],
    "outboundTag": "ou_direct"
}
```
不是会将域名转换为IP再进行匹配吗？此时的DNS应该是走本地吧。

**Comment by badO1a5A90** [comment]
> > 看了配置,感觉可能.是这样一种情形.
> > 客户端没开嗅探, 也不是本地DNS解析.
> > 所以当本地应用访问一个域名 abc.com 时.
> > 首先 DNS 远程解析得到了一个最适合VPS的IP1.2.3.4(VPS如果在境外比如美西,那大概率不是国内IP)
> > 然后本地应用向1.2.3.4发起连接, 流量进入xray(v2rayNG), 被代理到服务端
> > 服务端根据1.2.3.4 分流至ou_data (其实是没有匹配)
> > 或许你把嗅探勾上看一下是否可以,
> > 这样 本地应用向1.2.3.4发起连接时,嗅探到abc.com,会把1.2.3.4替换成abc.com. 服务端就可以根据abc.com分流
> 
> v2rayNG 开启嗅探后就正常了。不过又发现一个问题：
> 服务端路由匹配使用 IPOnDemand 模式，遇到了规则
> 
> ```json
> {
>     "type": "field",
>     "network": "tcp,udp",
>     "inboundTag": [
>         "in_vless_all"
>     ],
>     "ip": [
>         "geoip:private",
>         "geoip:cn"
>     ],
>     "outboundTag": "ou_direct"
> }
> ```
> 
> 不是会将域名转换为IP再进行匹配吗？此时的DNS应该是走本地吧。

会解析并且进行这条规则的匹配.
服务器解析的IP当然是适合服务器自己的.
所以如果你的VPS在境外,大概率解析得到的IP 是不会符合geoip:cn的.

**Comment by Alion548** [comment]
> > > 看了配置,感觉可能.是这样一种情形.
> > > 客户端没开嗅探, 也不是本地DNS解析.
> > > 所以当本地应用访问一个域名 abc.com 时.
> > > 首先 DNS 远程解析得到了一个最适合VPS的IP1.2.3.4(VPS如果在境外比如美西,那大概率不是国内IP)
> > > 然后本地应用向1.2.3.4发起连接, 流量进入xray(v2rayNG), 被代理到服务端
> > > 服务端根据1.2.3.4 分流至ou_data (其实是没有匹配)
> > > 或许你把嗅探勾上看一下是否可以,
> > > 这样 本地应用向1.2.3.4发起连接时,嗅探到abc.com,会把1.2.3.4替换成abc.com. 服务端就可以根据abc.com分流
> > 
> > 
> > v2rayNG 开启嗅探后就正常了。不过又发现一个问题：
> > 服务端路由匹配使用 IPOnDemand 模式，遇到了规则
> > ```json
> > {
> >     "type": "field",
> >     "network": "tcp,udp",
> >     "inboundTag": [
> >         "in_vless_all"
> >     ],
> >     "ip": [
> >         "geoip:private",
> >         "geoip:cn"
> >     ],
> >     "outboundTag": "ou_direct"
> > }
> > ```
> > 
> > 
> > 不是会将域名转换为IP再进行匹配吗？此时的DNS应该是走本地吧。
> 
> 会解析并且进行这条规则的匹配.
> 服务器解析的IP当然是适合服务器自己的.
> 所以如果你的VPS在境外,大概率解析得到的IP 是不会符合geoip:cn的.

这台VPS在境内，而且我看本地DNS解析返回的IP符合geoip:cn的。

**Comment by badO1a5A90** [comment]
> 这台VPS在境内，而且我看本地DNS解析返回的IP符合geoip:cn的。

那按你的配置, 这条规则应该要生效分流到ou_direct才对...所以日志里面分流到了ou_data吗?有点奇怪了

**Comment by badO1a5A90** [comment]
或许是geoip:cn数据不足的缘故?你在
```
    "ip": [
        "geoip:private",
        "geoip:cn"
    ],
```
里直接添加IP试试
```    "ip": [
        "1.2.3.4",
        "geoip:private",
        "geoip:cn"
    ],
```

**Comment by Alion548** [comment]
> 或许是geoip:cn数据不足的缘故?你在
> 
> ```
>     "ip": [
>         "geoip:private",
>         "geoip:cn"
>     ],
> ```
> 
> 里直接添加IP试试
> 
> ```
>         "1.2.3.4",
>         "geoip:private",
>         "geoip:cn"
>     ],
> ```

也是不行，这个问题应该挺好复现的。

**Comment by badO1a5A90** [comment]
> 也是不行，这个问题应该挺好复现的。

我自己就有很多类似分流写法,并无问题.

你的完整规则就上面那些吗?是不是被其他规则截胡了?

**Comment by Alion548** [comment]
> > 也是不行，这个问题应该挺好复现的。
> 
> 我自己就有很多类似分流写法,并无问题.
> 
> 你的完整规则就上面那些吗?是不是被其他规则截胡了?

没有其它规则，这里有点迷

**Comment by KirbyKFC** [comment]
需检查v2rayNG日志，v2rayNG有额外的DNS查询，是直接查询远程DNS的。
客户端和服务端不开嗅探的话，全程只有海外IP参与路由，没有域名。

**Comment by zhj9709** [comment]
服务端需要开嗅探，我玩过这种。不加嗅探 nslookup 百度都是国外的ip。

**Comment by Alion548** [comment]
我在服务端开启探测，客户端关闭探测也是不正常
``` json
{
    "tag": "in_vless",
    "port": 5520,
    "protocol": "vless",
    "settings": {
        "clients": [
            {
                "id": "##"
            }
        ],
        "decryption": "none"
    },
    "streamSettings": {
        "network": "tcp",
        "security": "none"
    },
    "sniffing": {
        "enabled": true,
        "destOverride": [
            "http",
            "tls"
        ]
    }
}
```

**Comment by zhj9709** [comment]
> 我在服务端开启探测，客户端关闭探测也是不正常
> 
> ```json
> {
>     "tag": "in_vless",
>     "port": 5520,
>     "protocol": "vless",
>     "settings": {
>         "clients": [
>             {
>                 "id": "##"
>             }
>         ],
>         "decryption": "none"
>     },
>     "streamSettings": {
>         "network": "tcp",
>         "security": "none"
>     },
>     "sniffing": {
>         "enabled": true,
>         "destOverride": [
>             "http",
>             "tls"
>         ]
>     }
> }
> ```

那就都开着吧，反正服务端不开会有奇怪的问题

**Comment by Alion548** [comment]
开启服务端嗅探就正常了，刚刚是配错入口，乌龙乌龙。
