### ISSUE TITLE
reality最好还是搭配443端口使用吗？

### ISSUE THREAD

**Issue by Pacio** [XTLS/Xray-core#1941]
不用443好像也能用啊

**Comment by xcf262352133** [comment]
是不是会一眼假

**Comment by jgh004** [comment]
现在推荐哪个方案？如果必须nginx前置的时候，用哪个方案好？

**Comment by yoohooyoo** [comment]
> 是不是会一眼假

会的，一眼假。

**Comment by chika0801** [comment]
> 现在推荐哪个方案？如果必须nginx前置的时候，用哪个方案好？

sni分流，共用443

**Comment by thisdk** [comment]
用nginx前置stream分流,性能会不会降低?我听别人说nginx前置后.会比直接xray直接监听::443会慢

**Comment by chika0801** [comment]
你试试，哪果有降价我猜你也感觉不到

**Comment by OnlyCharacters** [comment]
TLS 的 client hello 会有 server name 字段。
我 server name 用的是微软的官网。像这种大网站如果不是 443 端口肯定一眼假（至少人看得出来。

**Comment by pijiuping** [comment]
> > 现在推荐哪个方案？如果必须nginx前置的时候，用哪个方案好？
> 
> sni分流，共用443

试过，不行。stream里设置SNI分流，将流量转到本地的xray，用不了。

**Comment by wxhooong** [comment]
> > > 现在推荐哪个方案？如果必须nginx前置的时候，用哪个方案好？
> > 
> > 
> > sni分流，共用443
> 
> 试过，不行 stream里使用域名进行SNI分流，将流量转到本地的xray端口，用不了 以前用这种方法，是可以分流给WS、gRPC的 猜测需要配置TLS网站，在网站里再proxy到xray才行，但这样就多了一层加密失去了意义，证书也是自己的域名

我成功了哎，nginx分流填dest设置的域名，分流指向端口是节点配置的端口。为了验证你说的加密问题我把机子之前的伪装域名删了证书清了也重启了，还是能连接。是我忽略了什么问题吗，别用着用着自以为安全结果ip墙了。

**Comment by iKira** [comment]
> > > 现在推荐哪个方案？如果必须nginx前置的时候，用哪个方案好？
> > 
> > 
> > sni分流，共用443
> 
> 试过，不行 stream里使用域名进行SNI分流，将流量转到本地的xray端口，用不了 以前用这种方法，是可以分流给WS、gRPC的 猜测需要配置TLS网站，在网站里再proxy到xray才行，但这样就多了一层加密失去了意义，证书也是自己的域名

是你自己的问题，可以这么用。

**Comment by Oooutman** [comment]
> > > 现在推荐哪个方案？如果必须nginx前置的时候，用哪个方案好？
> > 
> > 
> > sni分流，共用443
> 
> 试过，不用 流里使用名进SNI分流，将流量转到本地的xray端口，用不用 以前用这种方法，是可以分流给WS、gRPC的 猜测需要配的设置TLS网站，在网站里再代理到xray才行，但这样就多了一层加密丢失了意义，证明书也是自己的域名

我试过可以用的。回到不用443伪装性是否变差的问题，我问了 NewBing 说是不会
```
当您使用Xray代理并使用REALITY协议时，Xray代理服务器会伪造一个TLS握手消息，该消息包含了一个看起来像是来自他人网站的证书。这就好比您拿着一个钥匙，钥匙上标着别人的名字，但实际上它能打开您自己家的门。

当客户端收到这个伪造的TLS握手消息时，它会认为自己正在与他人网站建立加密连接。这就好比第三者看到您拿着别人的钥匙，以为您要去别人家。但实际上，客户端正在与Xray代理服务器建立加密连接，而不是与他人网站建立连接。

因此，当您使用REALITY协议时，您可以指定一个真实存在的网站作为目标，Xray代理服务器将会伪造一个看起来像是来自该网站的证书。这样，代理流量就可以看起来像是来自该网站的普通HTTPS流量。
```
不过 NewBing 说起胡话来也是义正言辞，有没有大佬来确认下。

**Comment by lhbdhr** [comment]
reality的原理确实是sni伪造。chatgpt说的没错。
大公司的服务器https也有可能不只在443端口，从技术上来说，哪个端口都无所谓，都不会导致伪装变差。但是人约定俗成用443，你非要用高位端口，对于人来说，很明显。对于机器，从技术上来说，没有使伪装变差。

**Comment by Fangliding** [comment]
Not a core issue
