### ISSUE TITLE
UDP时延抖动

### ISSUE THREAD

**Issue by z826540272** [XTLS/Xray-core#196]
UDP零丢包，但存在时延抖动现象，大概为1秒内间歇性抖动15ms+-，
影响竞技游戏体验
测试方式
玩csgo，打开net_graph 1参数，观察sv抖动。
只有CSGO可以看这个参数，别的游戏只能看ping。
已知加速器和直连无抖动，直连白天有丢包，晚上丢包很少或者不丢包。sv稳定。
ping稳定。loss稳定。sv不稳定，导致服务器判定缓慢。

**Comment by z826540272** [comment]
部分时候，2秒内无抖动。使用PC和路由器分别测试，排除了CPU资源抢占的影响。

**Comment by rprx** [comment]
零丢包是 Trojan？

**Comment by rprx** [comment]
（你描述的这个现象挺玄学的

**Comment by rprx** [comment]
目测是 Trojan，UDP over TCP 是可靠传输，所以零丢包，但线路不是非常好时的确可能会时延抖动。

代理这类游戏推荐使用 Shadowsocks 的原生 UDP，非可靠传输，允许丢包，相对来说时延不抖动。

**Comment by z826540272** [comment]
我用的是VMESS,0丢包.

**Comment by rprx** [comment]
VMess 也是 UDP over TCP，试试 Shadowsocks

**Comment by z826540272** [comment]
> （你描述的这个现象挺玄学的

非玄学,可以复现,怀疑是v2ray等一众翻墙工具的问题.我可以开个国内服务器来测试

**Comment by rprx** [comment]
对于 UDP over TCP，理论上是可以解释通的，解决办法就是用原生 UDP 的协议

**Comment by z826540272** [comment]
> VMess 也是 UDP over TCP，试试 Shadowsocks
Shadowsocks我用不了,我下次弄个国内网络来测试下,首先使用VPN玩游戏确定线路本身不丢包,之后再换成v2ray,如果换成vmess网络体验变差的话,那应该就是v2ray的问题,UDP over TCP 理论上也不应该导致网络性能变差.
等我测试好了希望你排查下是哪个环节导致的问题

**Comment by rprx** [comment]
不是，这个刚刚已经解释过了，而且结合你的情况来看，packet 本身就有丢包时 UDP over TCP 时延抖动是很正常的

**Comment by z826540272** [comment]
你的意思是udp over tcp 会有自动重传?所以游戏本身不显示丢包

**Comment by rprx** [comment]
首先你的网络几乎不可能是零丢包的，这是前提。假设本身时延稳定，现在有两种情况：

1. 原生 UDP 代理，即允许丢包的非可靠乱序传输，但仍时延稳定
2. UDP over TCP，实现了不丢包的可靠有序传输，代价就是时延变得不稳定（因为你的网络本身有丢包）

**Comment by z826540272** [comment]
网络本身可以0丢包的.
即使是原生UDP,也存在时延抖动现象.
移动宽带直连HK游戏服务器.0丢包,存在轻度时延抖动.

**Comment by XuuKoo** [comment]
> 
> 
> VMess 也是 UDP over TCP，试试 Shadowsocks

如果tcp层面使用了over tls与https共用443端口，达到了一个较好的伪装，那使用ss的udp（仅代理udp）是否会增加服务器被识别的风险？

**Comment by z826540272** [comment]
> > VMess 也是 UDP over TCP，试试 Shadowsocks
> 
> 如果tcp层面使用了over tls与https共用443端口，达到了一个较好的伪装，那使用ss的udp（仅代理udp）是否会增加服务器被识别的风险？

没必要，掩耳盗铃，纯ssr或者vmess tcp都没被封

**Comment by z826540272** [comment]
这个问题，只有gfw从业人员清楚

**Comment by Fangliding** [comment]
虽然这里不是贴吧但是挖坟好像也不是好习惯
