### ISSUE TITLE
有關xudp最新支持MUX的設定疑慮

### ISSUE THREAD

**Issue by Lather0519** [XTLS/Xray-core#1963]
使用環境：Xray only 
其餘配套：vision+reality
端口：443 only 
根據 [XUDP：VLESS & VMess & Mux UDP FullCone NAT](https://github.com/XTLS/Xray-core/discussions/252)，我暫時在xray中把普通UDP看同於XUDP

xudp使用MUX設定代碼和疑慮如下
{
  "enabled": true, 
  "concurrency": -1, 
  "xudpConcurrency": 16, 
  "xudpProxyUDP443": "skip" 
}

按我理解：
`true`，MUX功能啓用
concurrency `-1`，TCP不使用MUX
xudpConcurrency `16`，UDP使用MUX（~~抑或正確來說這裏的udp處理方式是uot？~~）
xudpProxyUDP443 `skip`，UDP使用MUX但不承载 443 端口流量，並且udp 443 流量使用代理工具默認的UDP處理方式。

疑慮：
那麼在上述xray設定環境下，
我認爲  「xudpProxyUDP443 `skip` 或 `allow` ，都不會改變xray對udp的處理方式➡️UOT」，對嗎？
如果是 xudpProxyUDP443 `reject`  呢？ 因爲TCP是 -1，那麼只使用了443端口的代理流量是不是等於沒有使用MUX？

**Comment by chika0801** [comment]
xudpProxyUDP443 allow 让UDP443流量，用MUX方式，是UoT

xudpProxyUDP443 false 让UDP443流量，没用MUX方式，是UoT，此时假设你流控是 xtls-rprx-vision，UDP443被阻止。

**Comment by Lather0519** [comment]
> xudpProxyUDP443 allow 让UDP443流量，用MUX方式，是UoT
> 
> xudpProxyUDP443 false 让UDP443流量，没用MUX方式，是UoT，此时假设你流控是 xtls-rprx-vision，UDP443被阻止。假设你流控是 xtls-rprx-vision-udp443，理论上UDP443是通的，UoT，没MUX加成。

是我基礎不足，很多地方混淆了。
我重新分了一下
```
UOT是udp的一種傳輸協議
MUX是流量的一種傳輸方式
xudpProxyUDP443 更改的是443端口中的udp是否使用mux，而對udp是以什麼形式傳輸沒有改變。
一種使用場景是：多個代理端口，skip後，唯獨udp 443 端口流量不走MUX，並且由原本的代理工具對udp流量進行處理。
```
這樣理解對嗎？

**Comment by RPRX** [comment]
你们对 `reject` 的理解有误，它是默认值，即拒绝代理 UDP/443 流量，就像 XTLS 不带 `-udp443` 时一样

其它的基本没错，~~看代码~~ 看文档就懂了

**Comment by RPRX** [comment]
还有我看到群里对增强版 XUDP 的理解有误，其实它指的是 Global ID & UoT Migration，而不是 XUDP Mux，后者两年前就有了，这次只是顺便加了两个配置项，让它更灵活可控了，当然使用 XTLS Vision 时还会对它加 padding，这是第三个层面

**Comment by RPRX** [comment]
简单理解：**XUDP 的 `reject` 和 XTLS 不带 `-udp443` 时一样，都是让被代理的 UDP/443 流量（基本上是 QUIC）进 blackhole**

~~当然 blackhole 的默默 drop 和 XUDP、XTLS 的积极 reject 还是有区别的，理解不了就当进 blackhole 了吧~~

**Comment by chika0801** [comment]
请问下频道中给的 "xudpConcurrency" 是8，文档中是16，普通使用是更建议用8或16，还是无所谓区别不大了。（条件是不在乎vps内存占用，打游戏时以稳定性优先）

**Comment by RPRX** [comment]
@chika0801 其实，内存占用多少与这个值几乎无关，~~此外我把频道的改成 16 了~~，@yuhan6665 的文档本来是 128，~~也不是不行~~

打游戏时不建议开 XUDP Mux，建议走 VLESS 默认的 Single XUDP，其它时候建议开 Mux，剩下的等文章

**Comment by Anonpigo** [comment]
do you help me for use reality support v2ray client for ios 14 or 15 ?

**Comment by Lather0519** [comment]
> do you help me for use reality support v2ray client for ios 14 or 15 ?

see the main of xray.

**Comment by Lather0519** [comment]
> Reopen，供大家参考
TG羣的新推送
`xtls-0rtt-vision
xtls-0rtt-vision-udp443`

我對此有疑問，~~先不討論增強版xudp增加了什麼東西（反正現在也不知道是什麼東西，沒出文檔）~~：
vision-udp443 = xudpproxyudp443 'skip',
vision = xudpproxyudp443 'reject'。
沒有問題吧？

vision-udp433+MUX = xudpproxyudp443 'allow'

若果vision-udp443有的 xudpproxyudp443 都有，還做得更好，~~那vision加回去的vision-udp443寫法意義不明？~~
我就是不明白這裏

**Comment by Lather0519** [comment]
> Reopen，供大家参考

這樣到底有沒有成功走xudp
{
"enabled": true,
"concurrency": -1,
"xudpConcurrency": 0,
}

**Comment by chika0801** [comment]
> 打游戏时不建议开 XUDP Mux，建议走 VLESS 默认的 Single XUDP

@RPRX 请问这句话正确的实现，哪一个是正确的？

A
```
            "mux": {
                "enabled": false,
                "concurrency": -1,
                "xudpConcurrency": 16,
                "xudpProxyUDP443": "reject"
            },
```

B
```
            "mux": {
                "enabled": true,
                "concurrency": -1,
                "xudpConcurrency": 0,
                "xudpProxyUDP443": "reject"
            },
```

**Comment by RPRX** [comment]
@chika0801 @Lather0519 

如果 "xudpConcurrency": 0，就当这项不存在，和 v1.8.1 前的规则一样，这样说能理解吧。不过 "xudpProxyUDP443" 是独立项。

> @RPRX 请问这句话正确的实现，哪一个是正确的？

A 是只给 UDP 开 Mux。B 是走 UDP 走 TCP 的 Mux，由于 TCP 是 -1，就是不走 Mux，此时 Mux 没有在 VLESS 前处理 UDP 流量，UDP 流量就会由 VLESS 来处理，也就是默认 Single XUDP。如果是 SS，就是原生 UDP。

但是为了兼容旧版，Vision 的 VLESS Single XUDP 目前还没有 padding，想要 padding 的话需要这样设：

```
            "mux": {
                "enabled": true,
                "concurrency": -1,
                "xudpConcurrency": 1,
                "xudpProxyUDP443": "reject"
            },
```

**Comment by RPRX** [comment]
此外，使用 SS 时，可以只开 XUDP Mux，这样就相当于 UoT，并且有增强版 XUDP 的 Global ID & UoT Migration 加成。

"xudpConcurrency" 设 1 和 Single XUDP 是一样的效果，只是用到的代码不一样，前者是 common/mux，后者是 common/xudp。

**Comment by RPRX** [comment]
@Lather0519 从 v1.8.1 开始，"xudpConcurrency": 0 是兼容旧版，但 "xudpProxyUDP443" 默认是 "reject"，相当于改了行为。

这个我怎么说呢。。。如果你开 Mux，它会拦截 QUIC，如果你开 XTLS，它也会拦截 QUIC，你同时开就是双重拦截。

**Comment by RPRX** [comment]
XUDP 一直是基于 Mux，看上古文章 https://github.com/XTLS/Xray-core/discussions/252 ，common/xudp 是为了方便 VLESS & VMess 默认启用 XUDP 而写的单独实现

**Comment by Weltolk** [comment]
> @chika0801 @Lather0519
> 
> 如果 "xudpConcurrency": 0，就当这项不存在，和 v1.8.1 前的规则一样，这样说能理解吧。不过 "xudpProxyUDP443" 是独立项。
> 
> > @RPRX 请问这句话正确的实现，哪一个是正确的？
> 
> A 是只给 UDP 开 Mux。B 是 UDP 走 TCP 的 Mux，由于 TCP 是 -1，就是不走 Mux，此时 Mux 没有在 VLESS 前处理 UDP 流量，UDP 流量就会由 VLESS 来处理，也就是默认 Single XUDP。如果是 SS，就是原生 UDP。
> 
> 但是为了兼容旧版，Vision 的 VLESS Single XUDP 目前还没有 padding，想要 padding 的话需要这样设：
> 
> ```
>             "mux": {
>                 "enabled": true,
>                 "concurrency": -1,
>                 "xudpConcurrency": 1,
>                 "xudpProxyUDP443": "reject"
>             },
> ```

A的enabled是false, 我(go小白,有错误烦请指出)看源码的逻辑是enabled为true时, 才会进入设置mux相关参数的逻辑, 才会设置xudp

https://github.com/XTLS/Xray-core/blob/d3060c28f826ba62f5f77085fa1dc2a20f5cd19f/app/proxyman/outbound/handler.go#L111

所以A的预期行为应该是走common/xudp? 根本不过mux

**Comment by RPRX** [comment]
anonymous 说得对，不要纠结 QUIC，上古文章 https://github.com/XTLS/Xray-core/discussions/237 我就说过它不适合被代理，尤其是 XTLS，就算是 Hysteria 也推荐你干掉它

**Comment by Extreme-Icer** [comment]
> 
> A的enabled是false, 我(go小白,有错误烦请指出)看源码的逻辑是enabled为true时, 才会进入设置mux相关参数的逻辑, 才会设置xudp
> 
> https://github.com/XTLS/Xray-core/blob/d3060c28f826ba62f5f77085fa1dc2a20f5cd19f/app/proxyman/outbound/handler.go#L111
> 
> 所以A的预期行为应该是走common/xudp? 根本不过mux

你可以理解为没开mux（

**Comment by RPRX** [comment]
@Weltolk 是的，我没看到那里写的 false，~~等下改~~

**Comment by Lather0519** [comment]
> @Weltolk 是的，我没看到那里写的 false，~等下改~

阿這
~~我以爲你已經注意到了~~

**Comment by Lather0519** [comment]
> ~其实我真的觉得只要看得懂 if，直接看代码比看文档都更容易理解~

~~是的，要是看得懂也不用寫issue了~~

**Comment by RPRX** [comment]
To 群里：不要想着开 9999，目前的代码里累计连接数到 128 就一定会开新的 Mux

**Comment by RPRX** [comment]
注意是累计，还不是同时，这个以后可能也会开放出来配置

**Comment by RPRX** [comment]
> 特别注意，**即使你用 mKCP、QUIC 作为底层传输方式，UoT 的也并不会表现出原生 UDP 的那些特性。** https://github.com/XTLS/Xray-core/discussions/237

**Comment by RPRX** [comment]
比如 MTProto 和 Legacy VMess 的代码，还有很多兼容远古配置的代码，还有很多没用到的抽象层，我都想删掉

**Comment by Extreme-Icer** [comment]
@RPRX xray2.0重构计划 start！

**Comment by RPRX** [comment]
@Extreme-Icer 没必要彻底重构，Go 语言就这样了。先精简代码，删掉没用的，再优化性能。配置会保持兼容，除了被删掉的。

我的计划是始终维护 Go Xray-core 作为多协议平台，有空时再填上 Rust NEXT-core 的坑，全新架构，只支持 VLESS 相关协议。

**Comment by Lather0519** [comment]
> @Extreme-Icer 没必要彻底重构，Go 语言就这样了。先精简代码，删掉没用的，再优化性能。配置会保持兼容，除了被删掉的。
> 
> 我的计划是始终维护 Go Xray-core 作为多协议平台，有空时再填上 Rust NEXT-core 的坑，全新架构，只支持 VLESS 相关协议。

~~下一代xray架構忽然確定？~~

**Comment by RPRX** [comment]
> 推薦搭配不良林的視頻觀看 [【进阶•UDP穿透篇】WebRTC泄漏真实IP、搭建游戏节点必看的UDP代理知识！原生UDP和UoT的区别，P2P联机UDP打洞，实现游戏最佳的fullcone，为什么QUIC会导致youtube降速](https://www.youtube.com/watch?v=GQg5JIQIjgk)

~~这个视频的后半段感觉像是照着我的文章讲了一遍，不过对于看不进文章的小白来说也还行，毕竟也是相当于给了 credit。~~

**Comment by Lather0519** [comment]
> > 推薦搭配不良林的視頻觀看 [【进阶•UDP穿透篇】WebRTC泄漏真实IP、搭建游戏节点必看的UDP代理知识！原生UDP和UoT的区别，P2P联机UDP打洞，实现游戏最佳的fullcone，为什么QUIC会导致youtube降速](https://www.youtube.com/watch?v=GQg5JIQIjgk)
> 
> ~这个视频的后半段感觉像是照着我的文章讲了一遍，不过对于看不进文章的小白来说也还行，毕竟也是相当于给了 credit。~

視頻生動，對入門玩家不錯
~~R佬就放過他吧~~
~~說不定他是你的頭號粉絲~~

**Comment by Lather0519** [comment]
> > ~下一代xray架構忽然確定？~
> 
> 不会叫 Xray，可能也不会叫 NEXT。

~我都猜到了，叫Nexray~

**Comment by KouYiGuo** [comment]
> > ~下一代xray架構忽然確定？~
> 
> 不会叫 Xray，可能也不会叫 NEXT。

不以 X 开头就是重大利好，不然又要陷入取名困境。

**Comment by RPRX** [comment]
> ~我都猜到了，叫Nexray~

~~还是别 ray 了，这次真的不想有任何关联~~

**Comment by KouYiGuo** [comment]
RLESS

**Comment by rui0572** [comment]
NEXT 多好
~~NEXT = Next EXordinary Techology~~

**Comment by RPRX** [comment]
新项目名不打算用现有知名单词了

**Comment by Fangliding** [comment]
@RPRX 起码有新项目()

**Comment by RPRX** [comment]
> RLESS

~~这是要给 VLESS 改名还是~~

> NEXT 多好 ~NEXT = Next EXordinary Techology~

新项目名不打算用现有知名单词了

> 我用了几个月的VLESS-TCP，因为我总认为外层TLS的那1RTT也无必要....我却又不愿意用多路复用，于是只好用vless-tcp了....

。。？

**Comment by yuhan6665** [comment]
~~Sager~~ 萨格尔王？:rofl:

**Comment by RPRX** [comment]
> ~Sager~ 萨格尔王？🤣

~~叉瑞威兔瑞~~

**Comment by RPRX** [comment]
> > ~Sager~ 萨格尔王？🤣
> 
> 艾克斯瑞

我觉得这个“中文翻译”挺好的，~~以后我们就用它吧~~

**Comment by xsm1997** [comment]
> 简单理解：**XUDP 的 `reject` 和 XTLS 不带 `-udp443` 时一样，都是让被代理的 UDP/443 流量（基本上是 QUIC）进 blackhole**
> 
> ~当然 blackhole 的默默 drop 和 XUDP、XTLS 的积极 reject 还是有区别的，理解不了就当进 blackhole 了吧~

问一个无关的问题，XUDP和XTLS是如何reject掉udp 443流量的？是通过icmp port unreachable吗？

**Comment by RPRX** [comment]
> 问一个无关的问题，XUDP和XTLS是如何reject掉udp 443流量的？是通过icmp port unreachable吗？

对于 UoT 来源，是 close TCP，对于 UDP 来源，~~或许就相当于默默 drop~~

**Comment by xsm1997** [comment]
> > 问一个无关的问题，XUDP和XTLS是如何reject掉udp 443流量的？是通过icmp port unreachable吗？
> 
> 对于 UoT 来源，是 close TCP，对于 UDP 来源，~或许就相当于默默 drop~
所以从理论上说，如果我可以在透明代理那层（比如软路由）用icmp port unreachable（iptables reject）来处理udp 443端口流量的话，或许会更好？貌似我这里有些linux设备是等待quic超时才回退到https的？

（现阶段openwrt的passwall的做法是iptables drop）

**Comment by RPRX** [comment]
@xsm1997 可以，不过正常来说都会同时请求，不会等 QUIC 超时吧，有些环境就是 UDP 不通，等超时的话用户体验会很差

**Comment by chika0801** [comment]
> ```
>             "mux": {
>                 "enabled": true,
>                 "concurrency": -1,
>                 "xudpConcurrency": 1,
>                 "xudpProxyUDP443": "reject"
>             },
> ```
> 
> 这个代码是添加在服务端的吗？ 不会受vmess+ws的影响吧？

客户端 两端要1.8.1 你vmess ws 加了也用是上

**Comment by timi-owo** [comment]
@RPRX 想请教 R 佬一个问题

目前使用 XTLS Vision + TCP + TLS，但是想上多路复用减少 RTT，暂定想法是将传输层改为 H2 + TLS 或者启用内置的 Mux。

以前有很多人用 grpc，但据说跑大流量跑不满宽带，我自己没实测。后面貌似在哪里看到过 R 佬说 grpc 基于 h2，不如直接上 h2。所以想请教下目前的 h2 和自带的 mux 更建议使用哪种方案？

我个人的理解是 h2 没有对 UoT 加 padding，但 mux 在正确设置的情况下会 padding UoT 流量，请问我的理解是否正确？

**Comment by chika0801** [comment]
grpc/h2大带宽跑多少，我是这样测的，假设vps cpu性能不是瓶颈，线路条件好，带宽够（本地和服务端）

开vless vision tcp tls（前者）和vless grpc/h2 reality（后者）

客户端用idm软件，设置本地http代理端口进xray，连服务端。idm用16线程。

下载vps本机上的一个比如5g的文件。前者跑得到比如500Mbps，后都比如就300Mbps。

**Comment by chika0801** [comment]
1.8.1 版本客户端配置加了 mux 那系列参数，我理解是对 udp over tcp 加了padding。

至于你本身开的哪种协议组合。比如 vless vision tcp tls就是vision在做 tls in tls处理。
你用的是vless h2 reality，就是h2的多路复用在作用。

**Comment by timi-owo** [comment]
@chika0801 谢谢你的回答，我对 1.8.1 xudp mux 新增设定的理解是：

`xudpConcurrency` 表示底层一条 tcp 连接（会算到 `concurrency` 里面）能承载多少个 udp over tcp 请求。

如果 `xudpConcurrency` = 0，相关逻辑就会走旧代码，行为跟 1.8.1 之前的一致且兼容（也就当它不存在）。

如果 `xudpConcurrency` > 0，会使用 xudp 的新代码，新代码会对 udp 里的敏感流量加 padding，还有一些诸如 "断流重连后端口不变" 之类的优化和完善，但因为行为上的改变，需要双端都是 1.8.1 版本。

如果 `xudpConcurrency` = 1，就相当于没开 uot 的多路复用（single xudp），但是因为走的新代码，所以有 padding 加持。

---

我对 mux 的理解是逻辑层面实现的多路复用，最终还是要交由传输层处理，如果传输层已经自带了多路复用，~就会有 “mux in mux" 的效果？~，但网络链路上的表现还是以传输层的行为为准。（没看过代码，纯属猜测）

假设 mux 的参数设定如下：

```
"mux":
{
    "enabled": true,
    "concurrency": 10,
    "xudpConcurrency": 5,
    "xudpProxyUDP443": "reject"
}
```

假设此时 inbound 过来 100 个 tcp 请求、10 个 udp 请求。

首先到了 mux 这边会发起 10 条 tcp 连接（个人称之为 mux 信道），每条 mux 信道承载这 100 / 10 个 tcp 请求。

然后还有 10 个 udp 请求，根据 `xudpConcurrency` 的值，会产生两条 udp over tcp 连接，但又没超过 `concurrency` 的值，所以只需要一条 mux 信道用于承载这 10 个 udp 请求。

最终需要建立 10 + 1 个 mux 信道，交由传输层（假设为 h2），由于 h2 自带多路复用，对外只需发起一条 tcp 连接就能承载这 11 条 mux 信道。

**（以上纯属个人理解，所有假设结果均为云，没有实测，如有错误请大佬指正）**

**Comment by Lather0519** [comment]
【關於高海千歌疑似在project X群針對我進行濫權】
高海千歌最後一次濫權時間：凌晨 00:10:35 5/6/2023
                      濫權原因：未知（小鬼本人拒絕回答）

我猜測會被濫權之前的最後兩個事情經過：
1️⃣. 回答群友疑問「64當日牆內無人討論和陰陽怪氣」:
”看不到不是很正常，讓你看到說明沒有在控評。“
2️⃣. RPRX在某個issue中回覆「use gRPC」，於是我與群友討論「是否應該從vision轉到gRPC，使用gRPC是否會有tls in tls的問題」：
“~~R佬都這麼說了，我要不要從vision轉到gRPC呢~~”
群友：“（RPRX “use gRPC“ 原話的截圖）”

“「圖」（高海千歌 github 列出gRPC和vision協議優缺點的截圖）"
群友：”別急。”

”我很急“
群友：“「圖」（轉發世界的原話，原話大致意思是 tls in tls 屬於炒作，目前還沒有被大規模封禁的報告）”

“那世界什麼時候跟RPRX打一架？
群友：“爲什麼要打架？”

“（project X 官方群 其中一個pin內容中的開頭 ‘有人說tls in tls 是炒作……' 的截圖）“ 
群友：“tcp的tls in tls 跟 gRPC有什麼關係？”

到此突然被禁言7天。
這次確實不同以往，我不清楚被禁言7天的原因。隨後禮貌兩次問高海千歌禁言原因，他拒絕回覆。

- **被封當天沒有涉政、也沒有散播謠言**
- 根據以往有幾次也幾乎是屬於被濫權的邊界，我認爲這次是小鬼自己心情不好，拿我出氣。
- 當然我也不會跟喜歡無理取鬧的小鬼聊天，~~現在的問題是我今天不跟他聊天他也要找機會禁言我~~
- 最後我自己退群了，雖然看似小問題，但我之前被他禁言過不少次，多數都是7天，除開有2、3次脫綱涉政被封我沒有異議，其餘幾次基本都是找到一點機會就想禁言我。
- 我不知道這次幾時惹惱了他，我亦知道自己跟他的性格不合（我開RPRX玩笑他當真，還說屬於散播謠言，威脅我要禁言。我好心回答群友問題，我自認因爲水平不夠解釋的不清楚，但也沒有造成誤導，然後高海千歌說我在胡亂回答以此取樂，我當時？？？），所以平時基本不理他。
- 爲了泄憤，我選擇在這裏公開婊高海千歌（群裏被禁言，但群有github issues推送）。
- 你應該是個正在讀書的小屁孩，我平時上網遇到你這種傲氣時期的學生仔挺多的，理解，所以我也懶得再跟你對峙。你玩得開心就好。~~注意不要太沉迷網路~~
- 
- 群裏有聊天記錄可以搜~~（只要沒被刪）~~😄
- ~~若果這次是我有錯~~，~~反正我退群了~~ 不存在的。

**Comment by chika0801** [comment]
https://github.com/XTLS/Xray-core/issues/2175#issuecomment-1575620931
```
Use gRPC
```
https://t.me/projectXray/2446595
你是只看到Use gRPC，你真有点链接进去看这话回复的是什么内容吗？。

带节奏机会来了，说了如下的话 https://t.me/projectXray/2446606
```
R佬都這麼說了，我要不要把vision換成gRPC呢
```

正好继续再带节奏
```
世界什麼時候跟rprx打一架
```
https://t.me/projectXray/2446630
https://t.me/projectXray/2446635

我看到了前后对话，禁言你7天。

你来私我问原因，懂非必要不私人，我没理你，最后骂我一句，我就拉黑你了。

没人删你历史发言，你以往带了哪些节奏，谁都可以看。

**Comment by Lather0519** [comment]
> [#2175 (comment)](https://github.com/XTLS/Xray-core/issues/2175#issuecomment-1575620931)
> 
> ```
> Use gRPC
> ```
> 
> https://t.me/projectXray/2446595 你是只看到Use gRPC，你真有点链接进去看这话回复的是什么内容吗？。
> 
> 带节奏机会来了，说了如下的话 https://t.me/projectXray/2446606
> 
> ```
> R佬都這麼說了，我要不要把vision換成gRPC呢
> ```
> 
> 正好继续再带节奏
> 
> ```
> 世界什麼時候跟rprx打一架
> ```
> 
> https://t.me/projectXray/2446630 https://t.me/projectXray/2446635
> 
> 我看到了前后对话，禁言你7天。
> 
> 你来私我问原因，懂非必要不私人，我没理你，最后骂我一句，我就拉黑你了。
> 
> 没人删你历史发言，你以往带了哪些节奏，谁都可以看。

建議你有過於表達自我中心的心理問題就去治。
若果説 ~~這樣就是帶節奏~~，我可以認為是不敢大方承認你就是在玩針對。
希望你在tg公告寫上：小白非技術性發問一律封禁

你還是大方承認自己針對我玩權限就行了，我第一次發言被你如何對待，如你所説，大家都可以看~~（問題是為什麼要浪費時間當裁判）~~
我換個青蛙頭像説我在其他群帶節奏，我説那不是我，你一句道歉沒有直接消失。
你的氣度，你的認知，你的社會經驗，只允許你活在網路。

**Comment by FranzKafkaYu** [comment]
就事论事，请不要附带人身攻击。诸如`你有過於表達自我中心的心理問題就去治`，`你的氣度，你的認知，你的社會經驗，只允許你活在網路`，`你應該是個正在讀書的小屁孩，我平時上網遇到你這種傲氣時期的學生仔挺多的，理解，所以我也懶得再跟你對峙`这些对话不应出现。

**Comment by oilfieldtools** [comment]
你们讨论的都太高深了
https://github.com/2dust/v2rayN/issues/5251
我的出现了这个问题，有可以帮忙解决的吗？

**Comment by oilfieldtools** [comment]
提示如下， 
FATAL[0000] create service: parse outbound[120]: unsupported flow: xtls-rprx-vision-udp443

我将configSpeedtest文件里的【xtls-rprx-vision-udp443】，改成【xtls-rprx-vision】
保存后，重新运行，无效，它自己还是恢复成【xtls-rprx-vision-udp443】
我目前是通过重新安装解决问题。
