### ISSUE TITLE
xtls-rprx-vision和reality配合时，outbound到warp的socks转发不成功

### ISSUE THREAD

**Issue by seanzhang9999** [XTLS/Xray-core#1966]
测试现象
同一台vps

标准rprx vision流控
1.  使用tls和域名证书 
2. 可以正常上openai 没有1020
3.  ip138能显示warp地址

在流控上增加reality
1. openai报告1020 
2. ip138不显示ip 报告503

**Comment by picklefan** [comment]
你肯定配置错了，我就是socks5 warp-cli，自己慢慢找

**Comment by jaesony** [comment]
浏览器关掉quic试试

**Comment by seanzhang9999** [comment]
> 

老板你是用的reality加vision么 我现在很奇怪是同样的配置没有reality能过

**Comment by seanzhang9999** [comment]
> 你肯定配置错了，我就是socks5 warp-cli，自己慢慢找

谢谢您的正确性判断，果然我是配置文件忽略了大小写，谢谢谢谢

**Comment by seanzhang9999** [comment]
工作成长 是个人配置问题
