### ISSUE TITLE
Is this the magic trick to use dokodemo-door to make reality  protocol invisible to GFW?

### ISSUE THREAD

**Issue by us254** [XTLS/Xray-core#1968]
for example,
If you wanna use `google.com` as your SNI for `reality`  protocol, you better watch out. The GFW will hit up port 80 of Google and your server to see if you’re legit. If they don’t match, you’re toast!

All you gotta do is add this inbound config and you’re good to go. No more gfw drama!
```
{
   "listen": "0.0.0.0",
   "port": 80,
   "protocol": "dokodemo-door",
   "settings": {
     "address": "google.com",
     "port": 80,
     "network": "tcp"
   }
 },
 ```

**Comment by RPRX** [comment]
https://github.com/XTLS/REALITY#readme

> 配置加分项：**禁回国流量，TCP/80、UDP/443 也转发**（REALITY 对外表现即为端口转发，目标 IP 冷门或许更好）

**Comment by jiushibushuo** [comment]
直接用中文吧，这装的不地道的英格利希看着真难受

> for example, If you wanna use `google.com` as your SNI for `reality` protocol, you better watch out. The GFW will hit up port 80 of Google and your server to see if you’re legit. If they don’t match, you’re toast!
> 
> All you gotta do is add this inbound config and you’re good to go. No more gfw drama!
> 
> ```
> {
>    "listen": "0.0.0.0",
>    "port": 80,
>    "protocol": "dokodemo-door",
>    "settings": {
>      "address": "google.com",
>      "port": 80,
>      "network": "tcp"
>    }
>  },
> ```

**Comment by us254** [comment]
> 嗯，是可以添加两个dokodemo-door入站，TCP 80和UDP 443都转发到目标IP。

https://github.com/chika0801/Xray-examples/issues/47#issuecomment-1515788731

那文件的意思是 https://github.com/XTLS/REALITY

这里面有一句话

配置加分项：禁回国流量，TCP/80、UDP/443 也转发（REALITY 对外表现即为端口转发，目标 IP 冷门或许更好）

其实加不加也无所谓。

至于你用的访问VPS：443 显示 什么

你要测试 REALITY效果，我们是这样的，把windows的hosts文件，VPS的IP 对应你目标网站域名，保存。

然后关，开浏览器，输入目标网站网址，显示的是那网站的内容。
