### ISSUE TITLE
这么占用内存吗？

### ISSUE THREAD

**Issue by sheiy** [XTLS/Xray-core#1979]
<img width="1725" alt="image" src="https://user-images.githubusercontent.com/12210038/233565399-fc2399d2-f2d4-45aa-a228-e6743f7c00a6.png">

**Comment by jdnt** [comment]
![image](https://user-images.githubusercontent.com/1711790/233622085-5fdbe598-8295-4352-9109-ada526a8183e.png)
没感觉呀
LEDE  R23.4.1  6.1.24
xray 1.8.1 
passwall 4.64-6
reality+tcp

**Comment by sheiy** [comment]
@jdnt 方便把你的固件发一份给我吗？

**Comment by jdnt** [comment]
> @jdnt 方便把你的固件发一份给我吗？难道是我这固件有问题？我是自己编译的

 我也是自己编译的。x86测试内核（6.x），只留了igb、8169和esxi的万兆虚拟网卡驱动，加上全选的passwall，旁路模式直通了一个网口。如果都是自己编译，感觉固件导致问题的因素比较小。截图有点像在PVE下运行，如果是PVE可以把固件转成lxc用ct host来运行，这样才是完全体。

如果排除固件原因，也可能和运行方式有关，你的截图里开了10个passwall线程，内存占用率也会相应提高，可以先测试一下单线程运行。

**Comment by sheiy** [comment]
@jdnt 你用的哪个仓库和分支的代码编译的呢 我来编译一个试试呢 多谢

**Comment by jdnt** [comment]
>



> @jdnt 你用的哪个仓库和分支的代码编译的呢 我来编译一个试试呢 多谢；没找到哪里设置passwall的线程。。。方便来个截图不；我是truenas里运行的

https://github.com/coolsnowwolf/lede
https://github.com/xiaorouji/openwrt-passwall
我没有做额外设置，用的是reality+tcp，这样就是单线程。我也不清楚10个线程是怎么产生的  :flushed:

**Comment by sheiy** [comment]
@jdnt 你是单节点吗？

**Comment by jdnt** [comment]
> @jdnt 你是单节点吗？

哦，我懂你意思了。是的
![image](https://user-images.githubusercontent.com/1711790/233758988-ba4b7ab9-ed26-4ebc-a098-f3086282b68a.png)

**Comment by sheiy** [comment]
@jdnt 多谢  你居然申请到了oracle 云

**Comment by sheiy** [comment]
@jdnt 多谢   我用最新的代码编译过  好了

**Comment by ZqinKing** [comment]
> > @jdnt 你是单节点吗？
> 
> 哦，我懂你意思了。是的 ![image](https://user-images.githubusercontent.com/1711790/233758988-ba4b7ab9-ed26-4ebc-a098-f3086282b68a.png)

你的oracle能开两个2核12G内存的arm机器吗？我这无论怎么改配置都只能启一个arm的机器。资源是有的，就是第二个申请出来就会被关掉。

**Comment by jdnt** [comment]
@ZqinKing 不太清楚，我是新加坡区刚开不久注册的，直接开了4核，所以也开不了第二台。
