### ISSUE TITLE
all stream vision 功能请求

### ISSUE THREAD

**Issue by feng-king** [XTLS/Xray-core#1985]
对于非tcp stream，没法用到vision的某些特性，即对特定包进行填充，以减小tls in tls的特征，是否可以将这个特性实现到vless层，以支持所有协议(stream) non-tlsintls。

**Comment by RPRX** [comment]
1. VLESS 会加其它 flow、启用 seed，进行流量整形 https://github.com/XTLS/Xray-core/discussions/1295#discussioncomment-4636342
2. 实现 padding 简单，但它最多缓解了内层 TLS 握手的特征，无法解决加密套娃的问题。所以我看到有人问“想问下大家，目前有解决 TLS in TLS “特征”的同时又支持复用的方案吗？”，世界回复了一个带 padding 的 h2mux，呃，我们知道 NaiveProxy 就是 h2+padding，它仍有 TLS over(in) TLS 的 Known weaknesses https://github.com/klzgrad/naiveproxy#known-weaknesses

**Comment by feng-king** [comment]
> 1. VLESS 会加其它 flow、启用 seed，进行流量整形 [XTLS Vision, fixes TLS in TLS, to the star and beyond #1295 (comment)](https://github.com/XTLS/Xray-core/discussions/1295#discussioncomment-4636342)
> 2. 实现 padding 简单，但它最多缓解了内层 TLS 握手的特征，无法解决加密套娃的问题。所以我看到有人问“想问下大家，目前有解决 TLS in TLS “特征”的同时又支持复用的方案吗？”，世界回复了一个带 padding 的 h2mux，呃，我们知道 NaiveProxy 就是 h2+padding，它仍有 TLS over(in) TLS 的 Known weaknesses https://github.com/klzgrad/naiveproxy#known-weaknesses

感谢回复，希望seed和新的flow会是未来😊
