### ISSUE TITLE
whatsapp/telegram voice & video calling in fairvpn / wingsx / v2box / napsternetv

### ISSUE THREAD

**Issue by ssmetall** [XTLS/Xray-core#1989]
Hello, unfortunately, in fairvpn and wingx programs, when we make a voice call with telegram and whatsapp, the sound is fragmented. But this problem does not exist in v2box and napsternetv programs.
The tested connection is vless + tls + ws. Due to the unavailability of the programmers of these programs, I had to post here, I apologize to the respected rprx

**Comment by lostsoul6** [comment]
So what are you expecting ? They can't fix something they don't own or have access to !

**Comment by megasoheilsh** [comment]
> 

So that the programmers of these programs may see the problem on GitHub
