### ISSUE TITLE
我觉得可以引入可选的分享加密（基于AES），自定义密钥，防止未授权的传播，之前的vmess就有很多泄露出去的，根本base64只是让人看不懂。而且实现AES也不会很复杂，更加保护分享的安全。适用于个人分享，以及保护订阅被盗时阻止非法访问。

### ISSUE THREAD

**Issue by RainThings** [XTLS/Xray-core#199]
我觉得可以引入可选的分享加密（基于AES），自定义密钥，防止未授权的传播，之前的vmess就有很多泄露出去的，根本base64只是让人看不懂。而且实现AES也不会很复杂，更加保护分享的安全。适用于个人分享，以及保护订阅被盗时阻止非法访问。
具体可以这样 ：密文头部改为 Avless://或 Avmess:// 以提示需要自定义密钥解密。

_Originally posted by @RainThings in https://github.com/XTLS/Xray-core/issues/91#issuecomment-765059563_

**Comment by eMeab** [comment]
都分享了.怎麽還要加密呢.

**Comment by JimhHan** [comment]
@RainThings 

分享链接加密引入了一个问题，怎么保证密钥不被“未授权的传播”？

如果您所分享的用户，可以保护密钥的安全，那么，也用能力保护分享链接的安全。
如果您所分享的用户，不能保护分享链接的安全，那么，有何能力保护密钥的安全呢？

**Comment by lizkes** [comment]
@JimhHan https://tool.oschina.net/encrypt/ 你要的实现

**Comment by RainThings** [comment]
> https://tool.oschina.net/encrypt/你要的实现

是整合，不是孤立的工具

**Comment by RainThings** [comment]
> @RainThings
> 
> 分享链接加密引入了一个问题，怎么保证密钥不被“未授权的传播”？
> 
> 如果您所分享的用户，可以保护密钥的安全，那么，也用能力保护分享链接的安全。
> 如果您所分享的用户，不能保护分享链接的安全，那么，有何能力保护密钥的安全呢？

这个不是防止人为的主动传播，它主要的作用是防止传输中的泄露，你主动发出去并提供解密密钥，这是无法避免的，任何加密都阻止不了。所有的技术都只是降低泄露的可能。这样做的好处主要是对于订阅链接的更一层保护，即使订阅泄露也无法解析内容。
被分享的用户不能保证安全，这是任何都解决不了的，分享链接永远都可能是高风险的，加密仅仅只能保护传输过程，就如同tls，终端上的问题并不是它可以解决的。

**Comment by SekiBetu** [comment]
保护分享链接的传输，那如何保护密匙的传输

**Comment by NutterChen** [comment]
分享链接不必考虑那么复杂

机器懂
自然人懂

就行

至于订阅被泄露，可以在机场更换订阅链接

**Comment by NutterChen** [comment]
@NutterChen 甚至，base64都不用搞，得到你节点信息的人，想要攻击你的人，难道不会解个base64？

**Comment by NutterChen** [comment]
> 保护分享链接的传输，那如何保护密匙的传输，如果密匙和分享链接都是同一种传输方式，风险性是一样的，"密匙就是传输的分享链接"
> 
> 分享链接是方便给客户端的，并不是说你给一条分享链接给内核就能运行了，你的需求应该让客户端去实现，但我很怀疑会有客户端做这种无意义的事情
> 
> 即使订阅泄露也无法解析内容，什么情况下能泄露订阅，这种情况下人家会不会拿到密匙

可以推荐他用napsternetV,但是广告轰炸

**Comment by flyawayazure** [comment]
@NutterChen 我觉得这不属于一个网络工具应该具备的功能…
你也许需要的是gpg一类的工具…

**Comment by AkinoKaede** [comment]
> > @RainThings
> > 分享链接加密引入了一个问题，怎么保证密钥不被“未授权的传播”？
> > 如果您所分享的用户，可以保护密钥的安全，那么，也用能力保护分享链接的安全。
> > 如果您所分享的用户，不能保护分享链接的安全，那么，有何能力保护密钥的安全呢？
> 
> 这个不是防止人为的主动传播，它主要的作用是防止传输中的泄露，你主动发出去并提供解密密钥，这是无法避免的，任何加密都阻止不了。所有的技术都只是降低泄露的可能。这样做的好处主要是对于订阅链接的更一层保护，即使订阅泄露也无法解析内容。
> 被分享的用户不能保证安全，这是任何都解决不了的，分享链接永远都可能是高风险的，加密仅仅只能保护传输过程，就如同tls，终端上的问题并不是它可以解决的。

其实，机场所提供的 URL 本身就带有一个 Secret，大家在一些服务上登录账号的过程其实也差不多。如果你害怕泄露，可以尝试手动输入，防止窃取剪切板。如果认为其无序且长，这一点其实可以通过修改相关项目实现，这里就不赘述。

**Comment by NutterChen** [comment]
> @NutterChen 我觉得这不属于一个网络工具应该具备的功能…
> 你也许需要的是gpg一类的工具…

？？？啊这,你回复错人了

**Comment by Fhokud** [comment]
可以考虑一下非对称加密算法

**Comment by NutterChen** [comment]
我也认为这不是xray-core需要做的事情

采用xray-core的客户端应当必须能够读和出xray-core的标准分享链接

同时可以读取其他格式，不做要求

至于你的需求

强烈推荐  NapsternetV

来自乌干达的一个安卓客户端

可加密配置文件(密码)

可指定该配置文件可用的设备

可指定加密的配置文件失效时间

加密后，节点信息完全不可见

**Comment by RainThings** [comment]
> 我也认为这不是xray-core需要做的事情
> 
> 采用xray-core的客户端应当必须能够读和出xray-core的标准分享链接
> 
> 同时可以读取其他格式，不做要求
> 
> 至于你的需求
> 
> 强烈推荐 NapsternetV
> 
> 来自乌干达的一个安卓客户端
> 
> 可加密配置文件(密码)
> 
> 可指定该配置文件可用的设备
> 
> 可指定加密的配置文件失效时间
> 
> 加密后，节点信息完全不可见

这主要是希望标准统一化，让保护范围更广泛。不至于混乱。

**Comment by RainThings** [comment]
> @NutterChen 我觉得这不属于一个网络工具应该具备的功能…
> 你也许需要的是gpg一类的工具…

但是这个是应用在邮件上的，不是很适合。

**Comment by SekiBetu** [comment]
> > 我也认为这不是xray-core需要做的事情
> > 采用xray-core的客户端应当必须能够读和出xray-core的标准分享链接
> > 同时可以读取其他格式，不做要求
> > 至于你的需求
> > 强烈推荐 NapsternetV
> > 来自乌干达的一个安卓客户端
> > 可加密配置文件(密码)
> > 可指定该配置文件可用的设备
> > 可指定加密的配置文件失效时间
> > 加密后，节点信息完全不可见
> 
> 这主要是希望标准统一化，让保护范围更广泛。不至于混乱。并不是说我们需要一个特别的客户端。

xray-core根本无法读取分享链接啊，你这就是在提出一个客户端的需求

**Comment by RainThings** [comment]
> > > @RainThings
> > > 分享链接加密引入了一个问题，怎么保证密钥不被“未授权的传播”？
> > > 如果您所分享的用户，可以保护密钥的安全，那么，也用能力保护分享链接的安全。
> > > 如果您所分享的用户，不能保护分享链接的安全，那么，有何能力保护密钥的安全呢？
> > 
> > 
> > 这个不是防止人为的主动传播，它主要的作用是防止传输中的泄露，你主动发出去并提供解密密钥，这是无法避免的，任何加密都阻止不了。所有的技术都只是降低泄露的可能。这样做的好处主要是对于订阅链接的更一层保护，即使订阅泄露也无法解析内容。
> > 被分享的用户不能保证安全，这是任何都解决不了的，分享链接永远都可能是高风险的，加密仅仅只能保护传输过程，就如同tls，终端上的问题并不是它可以解决的。
> 
> 其实，机场所提供的 URL 本身就带有一个 Secret，大家在一些服务上登录账号的过程其实也差不多。如果你害怕泄露，可以尝试手动输入，防止窃取剪切板。如果认为其无序且长，这一点其实可以通过修改相关项目实现，这里就不赘述。

这个的意义在于独立于他们，保护secret被不慎泄露，类似于双因素身份验证。

**Comment by RainThings** [comment]
> > > 我也认为这不是xray-core需要做的事情
> > > 采用xray-core的客户端应当必须能够读和出xray-core的标准分享链接
> > > 同时可以读取其他格式，不做要求
> > > 至于你的需求
> > > 强烈推荐 NapsternetV
> > > 来自乌干达的一个安卓客户端
> > > 可加密配置文件(密码)
> > > 可指定该配置文件可用的设备
> > > 可指定加密的配置文件失效时间
> > > 加密后，节点信息完全不可见
> > 
> > 
> > 这主要是希望标准统一化，让保护范围更广泛。不至于混乱。并不是说我们需要一个特别的客户端。
> 
> xray-core根本无法读取分享链接啊，你这就是在提出一个客户端的需求

这个是整个体系的问题，不是针对某个特定的客户端或是核心。

**Comment by RainThings** [comment]
> 可以考虑一下非对称加密算法

就像TLS

**Comment by SekiBetu** [comment]
所以到底是什么场景激发了你的这个奇怪的需求

**Comment by RainThings** [comment]
> 所以到底是什么场景激发了你的这个奇怪的需求，一直搞不明白

看看那些漫天的分享吧。。。。。。。
我本身也是运营者。。。。。。

**Comment by SekiBetu** [comment]
> > 所以到底是什么场景激发了你的这个奇怪的需求，一直搞不明白
> 
> 看看那些漫天的分享吧。。。。。。。
> 我本身也是运营者。。。。。。

所以引入了这一套加密，可以阻止这些分享嘛

**Comment by RainThings** [comment]
> > > 所以到底是什么场景激发了你的这个奇怪的需求，一直搞不明白
> > 
> > 
> > 看看那些漫天的分享吧。。。。。。。
> > 我本身也是运营者。。。。。。
> 
> 所以引入了这一套加密，可以阻止这些分享嘛

我只是希望这些在v2ray-core的时候的事情不要再xray-core上重演。

**Comment by SekiBetu** [comment]
> > > > 所以到底是什么场景激发了你的这个奇怪的需求，一直搞不明白
> > > 
> > > 
> > > 看看那些漫天的分享吧。。。。。。。
> > > 我本身也是运营者。。。。。。
> > 
> > 
> > 所以引入了这一套加密，可以阻止这些分享嘛
> 
> 我只是希望这些在v2ray-core的时候的事情不要再xray-core上重演。

你加了加密只不过让分享的人多复制一个密匙，有区别吗

**Comment by JimhHan** [comment]
> 这个不是防止人为的主动传播，它主要的作用是防止传输中的泄露

请使用 HTTPS

> 这个的意义在于独立于他们，保护secret被不慎泄露，类似于双因素身份验证。

这个与双因素身份验证**完全不相似**，因为你无法在用户启动代理时为他们的客户端输入密钥，**且**不被对方截获。

> 我只是希望这些在v2ray-core的时候的事情不要再xray-core上重演。

我很负责任地说，绝大部分被泄露的分享**不是**由于没有“一个密钥以保护分享链接”，**而是用户主动传播所导致**。

如果你真的需要保护您的节点安全，请选择NapsternetV。

**Comment by RainThings** [comment]
> > > > > 所以到底是什么场景激发了你的这个奇怪的需求，一直搞不明白
> > > > 
> > > > 
> > > > 看看那些漫天的分享吧。。。。。。。
> > > > 我本身也是运营者。。。。。。
> > > 
> > > 
> > > 所以引入了这一套加密，可以阻止这些分享嘛
> > 
> > 
> > 我只是希望这些在v2ray-core的时候的事情不要再xray-core上重演。
> 
> 你加了加密只不过让分享的人多复制一个密匙，有区别吗
保护密钥就不只是这里的事了，而是整个体系的东西，比如在订阅时，密钥直接发送
到邮箱或tg，获取难度就更高

**Comment by SekiBetu** [comment]
> > > > > > 所以到底是什么场景激发了你的这个奇怪的需求，一直搞不明白
> > > > > 
> > > > > 
> > > > > 看看那些漫天的分享吧。。。。。。。
> > > > > 我本身也是运营者。。。。。。
> > > > 
> > > > 
> > > > 所以引入了这一套加密，可以阻止这些分享嘛
> > > 
> > > 
> > > 我只是希望这些在v2ray-core的时候的事情不要再xray-core上重演。
> > 
> > 
> > 你加了加密只不过让分享的人多复制一个密匙，有区别吗
> > 保护密钥就不只是这里的事了，而是整个体系的东西，比如在订阅时，密钥直接发送
> > 到邮箱或tg，获取难度就更高

保护密匙就是保护分享链接

**Comment by JimhHan** [comment]
> 保护密钥就不只是这里的事了，而是整个体系的东西，比如在订阅时，密钥直接发送到邮箱或tg，获取难度就更高

绝大部分被泄露的分享不是由于没有“一个密钥以保护分享链接”，而是用户主动传播所导致。此加密毫无意义，即使存在这个密钥，用户同样能够解密为原始链接。

**Comment by DuckSoft** [comment]
@JimhHan 不做。

**Comment by RainThings** [comment]
这个也只是我的想法，我也没有实际贡献的能力，这确实超出了范围

**Comment by SekiBetu** [comment]
不是超出范围的问题，而是根本毫无意义

**Comment by lizkes** [comment]
你这种需求，可以在外层实现，服务端把分享AES加密后在客户端解密。需要自制客户端

**Comment by RainThings** [comment]
Thank you all

**Comment by SekiBetu** [comment]
多和自己下棋

**Comment by RainThings** [comment]
搞技术总是有很多东西需要自已去想，有需求才有开发的动力。

**Comment by RainThings** [comment]
> 多和自己下棋

感谢。

**Comment by ertuil** [comment]
个人对此有一些其他理解，仅供参考，本人也**用不着加密分享，利益无关**。我认为标准化的过程就是一种统一的过程，从目的上不就是为了防止各个客户端各自为证和私有协议满天飞的过程吗？

从另一个角度说，我们可以认为 vmess 和 vless 协议本身和其具体实现是解耦的（正如 trojan 协议和 trojan-gfw、trojan-go、xray的关系一样）。因此是不是可以认为 vless 等的分享链接其实和具体实现是相对解耦的呢？那么在标准化的过程中考虑更多可能场景和实际需求似乎也没有什么不妥。

谈到具体的好处，这种加密的连接有一个好处就是是复制粘贴过程中带来的泄漏（我想很多人的分享链接都是明文存储在某个地方以便于随时取用的吧？）

因此，我个人的看法是是不是应该调研这种需求是否广泛呢，或者是咱们设计标准化的时候，有没有必要考虑一定的扩展性呢？因为实际 vless 分享链接提案确实是在这个仓库的 issue里，那么在这里提出一种建议也似乎并无不妥，我想 @RainThings 的本意并非是要放入 xray-core 中吧？

这是一点个人看法，仅供参考，不要撕逼哦（moe）

**Comment by ertuil** [comment]
个人对此有一些其他理解，仅供参考，本人也**用不着加密分享，利益无关**。我认为标准化的过程就是一种统一的过程，从目的上不就是为了防止各个客户端各自为证和私有协议满天飞的过程吗？
从另一个角度说，我们可以认为 vmess 和 vless 协议本身和其具体实现是解耦的（正如 trojan 协议和 trojan-gfw、trojan-go、xray的关系一样）。因此是不是可以认为 vless 等的分享链接其实和具体实现是相对解耦的呢？那么在标准化的过程中考虑更多可能场景和实际需求似乎也没有什么不妥。

这种加密的连接有一个好处就是可以防止恶意的 subconvertor 等带来的泄漏，或者是复制粘贴过程中带来的辅助（我想很多人的共享连接都是明文存储在某个地方以便于随时取用吧？）

因此，我个人的看法是是不是应该调研这种需求呢？因为实际vless 分享链接提案确实是在这个仓库里，那么在这里提出一种

**Comment by RainThings** [comment]
> 个人对此有一些其他理解，仅供参考，本人也**用不着加密分享，利益无关**。我认为标准化的过程就是一种统一的过程，从目的上不就是为了防止各个客户端各自为证和私有协议满天飞的过程吗？
> 
> 从另一个角度说，我们可以认为 vmess 和 vless 协议本身和其具体实现是解耦的（正如 trojan 协议和 trojan-gfw、trojan-go、xray的关系一样）。因此是不是可以认为 vless 等的分享链接其实和具体实现是相对解耦的呢？那么在标准化的过程中考虑更多可能场景和实际需求似乎也没有什么不妥。
> 
> 谈到具体的好处，这种加密的连接有一个好处就是是复制粘贴过程中带来的泄漏（我想很多人的分享链接都是明文存储在某个地方以便于随时取用的吧？）
> 
> 因此，我个人的看法是是不是应该调研这种需求是否广泛呢，或者是咱们设计标准化的时候，有没有必要考虑一定的扩展性呢？因为实际 vless 分享链接提案确实是在这个仓库的 issue里，那么在这里提出一种建议也似乎并无不妥，我想 @RainThings 的本意并非是要放入 xray-core 中吧？
> 
> 这是一点个人看法，仅供参考，不要撕逼哦（moe）

的确，这个是对整个体系的建议，只放进core是肯定没法完成的，既不必要也难以实现。

**Comment by Nek0kawa1** [comment]
这是要把宇宙塞进地球吗，加密方式无穷种，客户端也是无穷种，曾经认为的RC4也是最强的加密，也被淘汰了，现在要定一个加密为官方标准了？

**Comment by RainThings** [comment]
> 这是要把宇宙塞进地球吗，加密方式无穷种，客户端也是无穷种，曾经认为的RC4也是最强的加密，也被淘汰了，现在要定一个加密为官方标准了？

统一，减少麻烦，避免第三方客户端乱来。

**Comment by DuckSoft** [comment]
谁爱定谁定，我的建议是不要和core扯上关系。

**Comment by Nek0kawa1** [comment]
> > 这是要把宇宙塞进地球吗，加密方式无穷种，客户端也是无穷种，曾经认为的RC4也是最强的加密，也被淘汰了，现在要定一个加密为官方标准了？
> 
> 统一，减少麻烦，避免第三方客户端乱来。

那为什么要用AES，不用chacha

**Comment by badO1a5A90** [comment]
不做

**Comment by RainThings** [comment]
> 谁爱定谁定，我的建议是不要和core扯上关系。

这个确实很抱歉，但是真的不好找地方提出来。

**Comment by RainThings** [comment]
> 不做

这个本身就不是属于core的事。

**Comment by NutterChen** [comment]
不做

**Comment by RainThings** [comment]
> > > 这是要把宇宙塞进地球吗，加密方式无穷种，客户端也是无穷种，曾经认为的RC4也是最强的加密，也被淘汰了，现在要定一个加密为官方标准了？
> > 
> > 
> > 统一，减少麻烦，避免第三方客户端乱来。
> 
> 那为什么要用AES，不用chacha

流行，且安全性久经考验，兼容性好，几乎能用HTTPS的都行。

**Comment by ertuil** [comment]
> > 这是要把宇宙塞进地球吗，加密方式无穷种，客户端也是无穷种，曾经认为的RC4也是最强的加密，也被淘汰了，现在要定一个加密为官方标准了？
> 
> 统一，减少麻烦，避免第三方客户端乱来。

同样不赞同这种方式，强编码 AES，这种设计非常不妥当…… 

> 谁爱定谁定，我的建议是不要和core扯上关系。

我感觉在这里提是因为 vless 分享协议是在这里提的。公开建议也没有别的地方提出。并不和 core 有关，甚至 core 和分享链接也不相关。

**Comment by RainThings** [comment]
> 不做

这个确实不是core的事。

**Comment by Nek0kawa1** [comment]
> > > > 这是要把宇宙塞进地球吗，加密方式无穷种，客户端也是无穷种，曾经认为的RC4也是最强的加密，也被淘汰了，现在要定一个加密为官方标准了？
> > > 
> > > 
> > > 统一，减少麻烦，避免第三方客户端乱来。
> > 
> > 
> > 那为什么要用AES，不用chacha
> 
> 流行，且安全性久经考验，兼容性好，几乎能用HTTPS的都行。

那我设备不支持AES，我被你的标准淘汰了吗

**Comment by RainThings** [comment]
> > > > > 这是要把宇宙塞进地球吗，加密方式无穷种，客户端也是无穷种，曾经认为的RC4也是最强的加密，也被淘汰了，现在要定一个加密为官方标准了？
> > > > 
> > > > 
> > > > 统一，减少麻烦，避免第三方客户端乱来。
> > > 
> > > 
> > > 那为什么要用AES，不用chacha
> > 
> > 
> > 流行，且安全性久经考验，兼容性好，几乎能用HTTPS的都行。
> 
> 那我设备不支持AES，我被你的标准淘汰了吗

这只是建议，请不要杠。

**Comment by Nek0kawa1** [comment]
没有杠啊，这是这个建议第一步要做的事，确定加密方式啊，你连一个确定的加密方式都找不出来，怎么进行下一步

**Comment by AkinoKaede** [comment]
> > > > 这是要把宇宙塞进地球吗，加密方式无穷种，客户端也是无穷种，曾经认为的RC4也是最强的加密，也被淘汰了，现在要定一个加密为官方标准了？
> > > 
> > > 
> > > 统一，减少麻烦，避免第三方客户端乱来。
> > 
> > 
> > 那为什么要用AES，不用chacha
> 
> 流行，且安全性久经考验，兼容性好，几乎能用HTTPS的都行。

其實加個 bit 就能決定下用哪個密碼器，不過呢，我們並不打算做這個。

**Comment by DuckSoft** [comment]
@RainThings 以我之见，都别在这吵架了。觉得自己的观点好，那就梳理好细节，清清楚楚整整齐齐地拿出来，做成提案。你们这东一榔头西一棒槌吵来吵去，最后啥也不得成。

**Comment by RainThings** [comment]
> > > 这是要把宇宙塞进地球吗，加密方式无穷种，客户端也是无穷种，曾经认为的RC4也是最强的加密，也被淘汰了，现在要定一个加密为官方标准了？
> > 
> > 
> > 统一，减少麻烦，避免第三方客户端乱来。
> 
> 同样不赞同这种方式，强编码 AES，这种设计非常不妥当……
> 
> > 谁爱定谁定，我的建议是不要和core扯上关系。
> 
> 我感觉在这里提是因为 vless 分享协议是在这里提的。公开建议也没有别的地方提出。并不和 core 有关，甚至 core 和分享链接也不相关。

我只是提出建议。

**Comment by RainThings** [comment]
> > > 这是要把宇宙塞进地球吗，加密方式无穷种，客户端也是无穷种，曾经认为的RC4也是最强的加密，也被淘汰了，现在要定一个加密为官方标准了？
> > 
> > 
> > 统一，减少麻烦，避免第三方客户端乱来。
> 
> 同样不赞同这种方式，强编码 AES，这种设计非常不妥当……
> 
> > 谁爱定谁定，我的建议是不要和core扯上关系。
> 
> 我感觉在这里提是因为 vless 分享协议是在这里提的。公开建议也没有别的地方提出。并不和 core 有关，甚至 core 和分享链接也不相关。

我只是提出建议。

**Comment by RainThings** [comment]
> @RainThings 以我之见，都别在这吵架了。觉得自己的观点好，那就梳理好细节，清清楚楚整整齐齐地拿出来，做成提案。你们这东一榔头西一棒槌吵来吵去，最后啥也不得成。

我会抽空整理并提供整个提案

**Comment by badO1a5A90** [comment]
> > @RainThings 以我之见，都别在这吵架了。觉得自己的观点好，那就梳理好细节，清清楚楚整整齐齐地拿出来，做成提案。你们这东一榔头西一棒槌吵来吵去，最后啥也不得成。
> 
> 我会抽空整理并提供整个提案。

已锁帖，等提案吧。
