### ISSUE TITLE
Reality + Cloudflare Workers 

### ISSUE THREAD

**Issue by oftenhamed** [XTLS/Xray-core#1991]
大家好，我有一个关于将 REALITY 与 Cloudflare Workers 结合使用的理论。

 我用 x-ui 面板设置了一个 vps 并在上面运行 Reality。

 我使用以下代码在我的 cloudflare worker 中创建了一项新服务：

 addEventListener(
    "fetch", (event) => {
        let url = new URL(event.request.url);
        url.hostname = "your.domain";
        url.port = 443;
        url.protocol = "https";
        let request = new Request(url, event.request);
        event.respondWith(
        fetch(request)
        )
    }
)

 我将使用我的服务器 ip 创建的记录类型 A 子域放在上面脚本的 your.domain 部分中。

 我终于用 v2rayNG 中的工作人员地址更改了实际服务器 ip，我可以成功连接到我的 vps。

 唯一的问题是config第一次连接，但是一断开就不会再连接了。 我必须等待几分钟才能再次连接

你认为问题是什么？ 你能想一想这个理论吗？

**Comment by oftenhamed** [comment]
English translation 

Hey guys, I have a theory about using REALITY with Cloudflare Workers.

I set up a vps with x-ui panel and run Reality on it.

I've created a new service in my cloudflare workers using this code:

addEventListener(
    "fetch", (event) => {
        let url = new URL(event.request.url);
        url.hostname = "your.domain";
        url.port = 443;
        url.protocol = "https";
        let request = new Request(url, event.request);
        event.respondWith(
        fetch(request)
        )
    }
)

I put the record type A subdomain that I created with my server ip in the your.domain section in the script above.

I finally changed the actual server ip with the workers address in the v2rayNG and I can connect successfully to my vps.

The only problem is that the config connects for the first time, but does not connect again as soon as it is disconnected. I have to wait for a few minutes for it to connect again.

**Comment by JimmyHuang454** [comment]
https://www.j000e.com/cloudflare/cfworkers_reverse_proxy.html
