### ISSUE TITLE
用SS协议加2022-blake3-chacha20-poly1305加密到底该用什么密码?

### ISSUE THREAD

**Issue by linsan970809** [XTLS/Xray-core#1994]
"inbound": {
        "protocol": "shadowsocks",
        "port": 182,
        "settings": {
            "method": "2022-blake3-chacha20-poly1305",
            "password": "eXVodWFuMzRxNTkzNjM=",
            "level": 0,
	    "network": "tcp,udp"
        }
    },
method字段我用过的密码有,这些密码不是说密钥不合法就是长度不对,到底填什么才能成功?
1111111111111111111111111111111q  
ajsheng327haus
1234567891234567
!@#1254812545ds1AJHHGpo89u8765tf

![20230427140417_o](https://user-images.githubusercontent.com/61045370/234773495-b9d534b0-6d32-4142-9697-d39ae13b7ace.jpg)

**Comment by liaoliaots** [comment]
1，连接到你的VPS服务器
2，运行 openssl rand -base64 32，生成的内容为密码，才可兼容 2022-blake3-chacha20-poly1305

**Comment by linsan970809** [comment]
> 1，SSH连接到你的VPS服务器 2，运行openssl rand -base64 32，生成的内容为密码，才可包含2022-blake3-chacha20-poly1305

可以了,十分感谢您的回复

**Comment by yuhan6665** [comment]
solved

**Comment by EricMzky** [comment]
> 1，SSH连接到你的VPS服务器(Linux) 2，运行 openssl rand -base64 32，生成的内容为密码，才可兼容 2022-blake3-chacha20-poly1305

666啊
