### ISSUE TITLE
Bridge mode on Android -- DNS issue

### ISSUE THREAD

**Issue by mglwolf** [XTLS/Xray-core#1995]
大家都知道国内的IP紧缺，所以我想把旧的android电话做为bridge做穿透。外网的VPS做portal.
我手上有两部手机，一部rooted, 另一部没有, 作为普通的vless/ss/vmess服务器都没问题，但是作为bridge或portal是就遇到DNS解释的问题，如下：
2023/04/27 06:11:17 [Warning] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [dial tcp: lookup xxxt.axxxxm.com on [::1]:53:

1,尝试了在bridge加入DNS配置：
      "protocol": "freedom",
      "settings":{
         "domainStrategy": "UseIP"
         },
      "tag": "iNet"
    }
  ],
    "dns": {
      "servers": [
        "1.1.1.1",
        "1.0.0.1"
      ]
    }
   },
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
           "bridge"
        ],
        "domain": [
           "full:reverse.proxy"
        ],
        "outboundTag": "interconn"
      },
      {
        "type": "field",
        "inboundTag": [
           "bridge"
但这样的设定并不起作用，请问上述的设定是否有优化的空间？

2，在rooted的手机上修改/system/etc/resolve.conf，但同样也不起作用，xray还是向系统发起DNS查询，所以想请教一下还有没有别的办法？

谢谢

**Comment by simplerick-simplefun** [comment]
实在不行再套一层什么协议，这样xray识别是只有目标ip，没有sni

**Comment by rurirei** [comment]
i don't know parts of reverse proxy impl.

try dns-out and domainStrategy = AsIs.

```json
{
  "tag": "dns-out",
  "port": "53"
}
```

> [Warning] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [dial tcp: lookup xxxt.axxxxm.com on [::1]:53:

**Comment by mglwolf** [comment]
No it's not working, maybe Android(termux) is not a full Lunix, the program always use system DNS, but the result it returns is incorrect, that what ever your domainStrategy is Asis or IPOnDemand are not working,
 
I have tested the config on sandbox or even Openwrt, it's working good, just Android.

**Comment by mglwolf** [comment]
> 实在不行再套一层什么协议，这样xray识别是只有目标ip，没有sni

尝试了一下，它自己会不停跑死循环比较奇怪，然而这样的配置文件，我在VM/Sandbox/OpenWrt上跑也是正常的(在OpenWrt上必須用IPOnDemand)

**Comment by rurirei** [comment]
try listens on :53 dokodemo-door with elevated privileges.

> No it's not working, maybe Android(termux) is not a full Lunix, the program always use system DNS, but the result it returns is incorrect, that what ever your domainStrategy is Asis or IPOnDemand are not working,
> 
> I have tested the config on sandbox or even Openwrt, it's working good, just Android.
