### ISSUE TITLE
[Feature Request] UDP related enhancement

### ISSUE THREAD

**Issue by nJhEqnvK** [XTLS/Xray-core#200]
开贴讨论下关于UDP的一些建议和需求：

1. 游戏：
    - 主要针对NAT Type之类的 https://github.com/XTLS/Xray-core/issues/161 
    - 后期可能会添加*Accelerator*协议针对游戏需求 https://github.com/XTLS/Xray-core/issues/197#issuecomment-765051618
    > **Accelerator** 协议不同于 XUDP（后者是 UDP over TCP 的 MUX），它专门保持原生 UDP 特性来代理 UDP 流量，计划支持：
    > 
    > 1. 强大的多倍发包，含一些参数，比如倍数抖动、长度抖动、间隔抖动
    > 2. 客户端也可以始终只使用一个 UDP 端口与服务端通信
    > 3. 加密方式参考 Shadowsocks AEAD，外加时间戳防长期重放等
    > 4. 当然，服务端也支持单端口多用户，且实现高性能
    > 5. 会逐步加上类似 udp2raw 的一些伪装方式
2. 丢包/QOS
    - 国内三大运营商针对UDP都有不同程度的QoS，其中以移动最为nt（19-23时丢包率50+），出国流量的QoS更为严重，可能可以通过[Udp2raw](https://github.com/wangyu-/udp2raw-tunnel)那样给UDP包加上TCP或ICMP header，绕过UDP屏蔽或QoS
    - 还有一种办法为规避QoS规则（长时间连接\长时间大流量），看能不能在policy中添加类似kcp的`autoexpire`参数 https://github.com/xtaci/kcptun/issues/776
    `--autoexpire value set auto expiration time(in seconds) for a single UDP connection, 0 to disable (default: 0)`
    - 一些相关的链接 https://www.v2ex.com/t/684714 | https://www.v2ex.com/t/212873 | https://www.v2ex.com/t/468163
    
大家可以针对UDP讨论一下

**Comment by rprx** [comment]
#161 应该属于罕见情况？

**Comment by nJhEqnvK** [comment]
> #161 应该属于罕见情况？

（那只是我随手搜的NAT Type举得例子233

主要是很多游戏对NAT Type有要求，感觉大家对游戏的需求挺高的

**Comment by eMeab** [comment]
或許可以把這個issue 移到discussions 進行討論

**Comment by rprx** [comment]
@eMeab 现在转换不了了

**Comment by nJhEqnvK** [comment]
> 或許可以把這個issue 移到discussions 進行討論

~~之前在discussion开过贴讨论[ipv6旁路由](https://github.com/XTLS/Xray-core/discussions/162)，结果没人理我，大家的参与度远小于前几天在另外一个issue中对透明代理的讨论=。=、~~

**Comment by testermania** [comment]
vmess websocket + CDN（cloudflare）udp被阻止。

我尝试开/关多路复用器和其他电击服务器没有任何变化。

没有CDN, 黄色的udp标志出现

netch ntt.log

Other address is
Binding test: Fail
Local address:
Mapped address:
Nat mapping behavior: Unknown
Nat filtering behavior: Unknown
result: Unknown

**Comment by XuuKoo** [comment]
想问下目前xray能达到NAT几了？

**Comment by rprx** [comment]
> 
> 
> 想问下目前xray能达到NAT几了？

除了 VLESS/VMess/Mux，其它都能 FullCone

**Comment by rprx** [comment]
> 
> 
> 想问下目前xray能达到NAT几了？

目前除了 VLESS/VMess/Mux，其它都能 FullCone

**Comment by deximy** [comment]
Accelerator可以考虑引入udpspeeder的特性？感觉那个在减少网络抖动方面确实有一定效果。

**Comment by Smallthing** [comment]
如果多余了请删除，请问这个还有动向吗，谢谢
