### ISSUE TITLE
如何找到一个适合 REALITY 配置的目标网站？

### ISSUE THREAD

**Issue by us254** [XTLS/Xray-core#2005]
我想使用 REALITY 配置，我需要一个目标网站。我在我的客户端上运行 RealiTLScanner by @yuhan6665，在我的服务器上运行 openssl s_client，来检查一个域名是否支持 TLS v 1.3，ALPN h2 和 OCSP。例如：

`./RealiTLScanner -addr www.microsoft.com -showFail -o `

`openssl s_client -connect microsoft.com:443 -status `

 如果两个测试都通过，我就把那个域名作为目标网站。我还需要一个离我的服务器 IP 近，不太出名，而且使用 CDN 的域名。找到这样的域名的最好方法是什么？有没有什么工具或方法可以帮助我？这是找到目标网站的好方法吗？你有没有其他的建议，可以帮助我找到一个快速的目标网站，用于 REALITY？

**Comment by chika0801** [comment]
如果你不非常爱惜你VPS的IP，选广大群雄常用的苹果、微软、动漫.jp那些都是可以的。

没有什么找的捷径。找的方法（教程）说了，你要特别爱惜自己VPS就按方法试了。

且我的一个经验，如果你遇到使用一些目标网站，感觉VPS速度变慢，经常像线路不稳定的现象，或明天正常，后天完全连不上。建议换其它目标网站可能有奇效。或用自己偷自己方式有奇效。

**Comment by s0fx2** [comment]
打开你想要配置成为目标的网站，使用浏览器的web开发工具调试，在控制台打开协议，刷新页面，看到H2或者HTTP/2就是支持h2的网站，然后点击证书看是不是tls 1.3，还有就是ip地址是否和你vps地址相近，越近越好。

**Comment by tomxiang1** [comment]
![image](https://user-images.githubusercontent.com/45867336/236618853-2d8917d7-93db-4101-9c0e-79b647e15528.png)
点击进入看详情

**Comment by enterusernamecontinue** [comment]
访问 https://myip.ms/xxx.xxx.xxx.xxx ，点击 “Owner IP Range” 这一栏的【Other Sites on IP »】按钮，然后查看 “Known Websites between IP: xx.xx.xx.xx - xx.xx.xx.xx” 域名列表。

尝试使用浏览器“直连”访问列表中的站点域名，并在【开发者工具】的“安全”和“网络”选项卡中查看相关信息是否符合要求。

**Comment by azzvx** [comment]
打开https://bgp.tools/
输入你的VPS IP，回车
然后点DNS选项卡，选Show Forward DNS
下面有你同网段一堆域名给你选，然后挑几个域名，点进去，然后用浏览器的开发者工具看看是不是TLS 1.3以及X25519证书的。
好处是：同网段、网站都够冷门、延迟都在1ms内偷证书速度飞快。

**Comment by startui** [comment]
666

**Comment by leic4u** [comment]
> 访问 https://myip.ms/xxx.xxx.xxx.xxx ， 点击 “Owner IP Range” 这一栏的【Other Sites on IP »】按钮， 然后查看 “Known Websites between IP: xx.xx.xx.xx - xx.xx.xx.xx” 域名列表。
> 
> 尝试使用浏览器“直连”访问列表中的站点域名， 并在【开发者工具】的“安全”和“网络”选项卡中查看相关信息是否符合要求。

此方法最方便。补充一下：

1. 「安全」选项卡查看以下内容，显示 `已使用 TLS 1.3 、X25599` 为符合要求的网站，其他不符合。
![image](https://github.com/XTLS/Xray-core/assets/32786903/753e9c02-e476-4705-9030-5575387b6dce)

2. 「网络」选项卡需要先刷新页面，在表头空白处点击右键，勾选协议，如协议列中出现 `H2` 为符合要求的网站，没有出现则不符合。
![image](https://github.com/XTLS/Xray-core/assets/32786903/a4352385-2ab2-4e6b-ae5d-1148f1f07ac2)

**Comment by zhfish** [comment]
mark，好方法

**Comment by aptexd** [comment]
![Image](https://github.com/user-attachments/assets/85f531f0-d574-4b17-aa8b-36f6ab231193)
光有h2的链接也不行，似乎必须和主站IP一样才行
也就是主站的请求是 h2

**Comment by somehow22** [comment]
> > 访问 https://myip.ms/xxx.xxx.xxx.xxx ， 点击 “Owner IP Range” 这一栏的【Other Sites on IP »】按钮， 然后查看 “Known Websites between IP: xx.xx.xx.xx - xx.xx.xx.xx” 域名列表。
> > 尝试使用浏览器“直连”访问列表中的站点域名， 并在【开发者工具】的“安全”和“网络”选项卡中查看相关信息是否符合要求。
> 
> 此方法最方便。补充一下：
> 
>     1. 「安全」选项卡查看以下内容，显示 `已使用 TLS 1.3 、X25599` 为符合要求的网站，其他不符合。
>        ![image](https://github.com/XTLS/Xray-core/assets/32786903/753e9c02-e476-4705-9030-5575387b6dce)
> 
>     2. 「网络」选项卡需要先刷新页面，在表头空白处点击右键，勾选协议，如协议列中出现 `H2` 为符合要求的网站，没有出现则不符合。
>        ![image](https://github.com/XTLS/Xray-core/assets/32786903/a4352385-2ab2-4e6b-ae5d-1148f1f07ac2)

现在 myip.ms 空白页面？我梯子没问题啊

**Comment by aijwfsibari** [comment]
> 打开https://bgp.tools/ 输入你的VPS IP，回车 然后点DNS选项卡，选Show Forward DNS 下面有你同网段一堆域名给你选，然后挑几个域名，点进去，然后用浏览器的开发者工具看看是不是TLS 1.3以及X25519证书的。 好处是：同网段、网站都够冷门、延迟都在1ms内偷证书速度飞快。

如果是广播ip，虽然同网段，但有可能地区甚至国家不同，反而慢了吧

**Comment by Shallowhave** [comment]
mark

**Comment by LeveinOvO** [comment]
上面的网站似乎显示加号了，我找到了个[新的](https://search.dnslytics.com/)，选CIDR搜索。

**Comment by zhiguang127** [comment]
好东西，mk了
