### ISSUE TITLE
请问 Xray-core 做为客户端是否可以设置代理链或者前置代理？配置文件如何写

### ISSUE THREAD

**Issue by vitaminx** [XTLS/Xray-core#2006]
请问用 Xray-core 作为客户端是否可以给它设置一个前置代理，或者设置客户端代理链？
实现流量路径：本地App → 其他代理软件 → Xray-core → 目标地址
请问是否可以实现？配置文件如何写？

搜索了 “Xray代理链”、“Xray前置代理” ...... 都没有找到答案

**Comment by nursery01** [comment]
你的意思是(app) -> socks5(other proxy soft) -> socks5(Xray) -> server

我經常這麼用

**Comment by vitaminx** [comment]
> 

对的 这个怎么设置？

**Comment by chika0801** [comment]
要看  其他代理软件 具体是什么软件。简单说来，其他代理软件 如果支持出站（发出请求）到本机socks端口。那你可以在本机的Xray配置中，入站配置写一个接收这个socks端口的内容，实现你的目的。

**Comment by vitaminx** [comment]
> 你的意思是(app) -> socks5(other proxy soft) -> socks5(Xray) -> server
> 
> ~我经常这么用~
请问这个如何实现？

**Comment by crazypeace** [comment]
不想自己动手改配置文件的话，可以试试这个v2rayN, 通过界面来操作。
https://github.com/crazypeace/v2rayN/releases/tag/v2rayN-Xray-Outbound-Socks
演示视频
https://www.youtube.com/watch?v=TtHEWS6H3RE
