### ISSUE TITLE
xray的inbounds流量使用本地的adguardhome dns服务器解析

### ISSUE THREAD

**Issue by renol89303** [XTLS/Xray-core#2008]
我在vps（vps是国外服务器）中部署了mosdns，adguardhome和xray，xray和mosdns都部署在host网络，adguardhome部署在其他网络，mosdns为adguardhome的上游DNS服务器，想把xray的vmess流量通过adguardhome解析去广告，然后使用mosdns解析，目前问题是不知道inbounds的vmess流量如何通过adguardhome作DNS解析
adguardhome容器的监听地址是192.168.1.8:5223
以下是我的配置文件，求教
![image_15](https://user-images.githubusercontent.com/86635916/235311106-dff6d31f-aa7f-4dad-af4d-e57b4e0ff74f.png)
![image_16](https://user-images.githubusercontent.com/86635916/235311114-cf93fa98-8a69-42f3-b962-b83e7b17c04a.png)
![image_17](https://user-images.githubusercontent.com/86635916/235311118-8ba0a3c6-850d-443a-9ac9-b93d4cb45b00.png)

**Comment by yuhan6665** [comment]
去广告推荐在网页端做 代理服务器可能收到 IP 无法用 DNS 去广告
