### ISSUE TITLE
配置成reality后无法连接

### ISSUE THREAD

**Issue by wangmice** [XTLS/Xray-core#2010]
客户端和服务端都是1.8.1，系统都是ubuntu 22.04
服务端配置如下：关键配置处
"security": "reality",
"realitySettings": {
"show": true,
"dest": "80",
"xver": 0,
"serverNames": ["服务器域名"],
"privateKey": "XXXXXXXXXXXXXXXXXXXXXXXXXXX",
"shortIds": [
"",
"0123",
"01234567",
"0123456789abcdef"
]
},
"sniffing": {
"enabled": true,
"destOverride": [
"http",
"tls"
]
}

服务端日志文件没有错误输出，以下是服务端systemd journal
hs.c.AuthKey[:16]: [91 65 19 202 175 15 62 209 21>
REALITY remoteAddr: 客户端IP:端口 hs.c.ClientVer: [1 8 1]
REALITY remoteAddr: 客户端IP:端口 hs.c.ClientTime: 2023-04-29 11:49:43 +0800 CST
REALITY remoteAddr: 客户端IP:端口 hs.c.ClientShortId: [254 35 0 0 0 0 0 0]
REALITY remoteAddr: 客户端IP:端口 hs.c.conn == conn: true
REALITY remoteAddr: 客户端IP:端口 handled: false

客户端配置：
"security": "reality",
"realitySettings": {
"show": true,
"fingerprint": "randomized",
"serverName": "服务器域名",
"publicKey": "XXXXXXXXXXXXXXXXXXX",
"shortId": "0123",
"spiderX": "/robot"
},

日志如下：

2023/04/29 11:50:51 [Warning] [711696793] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [EOF dial tcp 服务器IP: operation was canceled] > common/retry: all retry attempts failed
2023/04/29 11:50:51 [Warning] [2271365908] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [EOF dial tcp 服务器IP: operation was canceled] > common/retry: all retry attempts failed
2023/04/29 11:50:51 [Warning] [2730667776] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [EOF dial tcp 服务器IP: operation was canceled] > common/retry: all retry attempts failed
2023/04/29 11:50:51 [Warning] [4022686976] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [EOF dial tcp 服务器IP: operation was canceled] > common/retry: all retry attempts failed
2023/04/29 11:50:52 [Warning] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [EOF] > common/retry: all retry attempts failed

wget -O- -4 https://www.facebook.com/

正在解析主机 [www.facebook.com](http://www.facebook.com/) ([www.facebook.com](http://www.facebook.com/))... 31.13.70.36
正在连接 [www.facebook.com](http://www.facebook.com/) ([www.facebook.com)|31.13.70.36|:443](http://www.facebook.com%29%7C31.13.70.36%7C:443/)... 已连接。
OpenSSL: error:0A000126:SSL routines::unexpected eof while reading
无法建立 SSL 连接。

配置成tls无异常，就reality有问题，完全是按照示例上配置的

用chrome浏览网页显示：
无法访问此网站， 意外终止了连接。
请试试以下办法：
检查网络连接
检查代理服务器和防火墙
运行 Windows 网络诊断
ERR_CONNECTION_CLOSED

发在讨论区无人回答，故开了一个issue

**Comment by chika0801** [comment]
如果服务端和客户端 公/私钥 短ID 服务名称几个因素都填对了的。建议这样试：先用VLESS Vsiion TLS确定客户端和服务端能通试试速度正常不。再用REALITY，更换目标网站网址，多换一些。最后使用自己偷自己看能不能通。

**Comment by chika0801** [comment]
> 再用REALITY，更换目标网站网址，多换一些。最后使用自己偷自己看能不能通。

那接下来试。再用REALITY，更换目标网站网址，多换一些。最后使用自己偷自己看能不能通。

**Comment by chika0801** [comment]
> > "shortId": "0123", 这个值必须为双数。去看文档吧，省的r佬骂
> 
> 是吧？我以为长度必须为双数，没注意是必须是偶数？

他明显忽悠你只能为偶数这句话。

不想自己编，打 执行 openssl rand -hex 8 ，8可换成2 4 6

**Comment by chika0801** [comment]
> 有点疑惑，我用浏览器打开我的服务器域名网站，显示的是一个错误页面： 421 Misdirected Request cloudflare
> 
> 并没有正确打开cloudflare的网站，是不是servername也要填1.1.1.1？

测试方法是 当dest为目标网址是不是填1.1.1.1 修改WIn的hosts文件 填 VPS的IP 空格 你的目标网址

关，开浏览器，输入目标网址显示 目标网址内容。

你现在是用1.1.1.1我也不知道怎么测试。你其实不用管这测试就行了。

**Comment by chika0801** [comment]
我从联通APP的上网详单上，看过。有时候显示我VPS的IP，有时候显示的是目标网站的网址（我SNI和DEST填的一个网址）

GFW看到你访问了你VPS的IP。至于它看到的SNI，比如是你客户端填的SNI，还是你用NO SNI配置时没填SNI就是目标地址1.1.1.1吧我也深入理解自觉了。不知道了。

**Comment by s0fx2** [comment]
我昨天遇到的问题和你一样，所有东西确认几次都输入正确，打开调试，一直显示handled: false。然后我翻到一个博主的server config，他使用了H2，没有使用tcp，如果使用h2，那么流控就是空，客户端和服务器流控都为空，然后handled: True，就连上了。

**Comment by LearnForDreamK** [comment]
> 1.1.1.1:443

我也出现这个问题了，看了楼主的issue改成1.1.1.1也没效果，直接把dest和servername换成微软的就好了

**Comment by facebook20146** [comment]
这个问题我换了好几个网站，死活都不行，用的hiddify面板，好像是伊朗人开发的，提了问题也没人答应。之前用xui面板，也是这样情况，还有其他原因吗

**Comment by chika0801** [comment]
> 这个问题我换了好几个网站，死活都不行，用的hiddify面板，好像是伊朗人开发的，提了问题也没人答应。之前用xui面板，也是这样情况，还有其他原因吗

用自己偷自己 形式试试了

**Comment by azzvx** [comment]
前面有好几个issue了。
REALITY偷的网站必须满足`TLS 1.3`以及`X25519`的证书格式两项，不满足的会失败。现在许多大站都是`P-256`，`P-384`的证书，没法偷。
![QQ截图20230508201646](https://user-images.githubusercontent.com/1546898/236821756-474c744a-6083-4342-a6c5-fc76ac77d616.png)

**Comment by RPRX** [comment]
> 现在许多大站都是`P-256`，`P-384`的证书，没法偷。

？？？

**Comment by facebook20146** [comment]
> 

怎么偷自己的，能否指导一下

**Comment by facebook20146** [comment]
> 前面有好几个issue了。 REALITY偷的网站必须满足`TLS 1.3`以及`X25519`的证书格式两项，不满足的会失败。现在许多大站都是`P-256`，`P-384`的证书，没法偷。 ![QQ截图20230508201646](https://user-images.githubusercontent.com/1546898/236821756-474c744a-6083-4342-a6c5-fc76ac77d616.png)

网站没有问题，感觉是面板证书或者设置的问题，但是不知道怎么看日志，怎么排查

**Comment by facebook20146** [comment]
> > 这个问题我换了好几个网站，死活都不行，用的hiddify面板，好像是伊朗人开发的，提了问题也没人答应。之前用xui面板，也是这样情况，还有其他原因吗
> 
> 用自己偷自己 形式试试了

能否指导一下，面板怎么偷自己的

**Comment by chika0801** [comment]
> > > 这个问题我换了好几个网站，死活都不行，用的hiddify面板，好像是伊朗人开发的，提了问题也没人答应。之前用xui面板，也是这样情况，还有其他原因吗
> > 
> > 
> > 用自己偷自己 形式试试了
> 
> 能否指导一下，面板怎么偷自己的

参考
https://github.com/chika0801/Xray-examples/tree/main/VLESS-XTLS-uTLS-REALITY/steal_yourself
如果还有问题来xray群问也行

**Comment by facebook20146** [comment]
> > > > 这个问题我换了好几个网站，死活都不行，用的hiddify面板，好像是伊朗人开发的，提了问题也没人答应。之前用xui面板，也是这样情况，还有其他原因吗
> > > 
> > > 
> > > 用自己偷自己 形式试试了
> > 
> > 
> > 能否指导一下，面板怎么偷自己的
> 
> 参考 https://github.com/chika0801/Xray-examples/tree/main/VLESS-XTLS-uTLS-REALITY/steal_yourself 如果还有问题来xray群问也行

能否分享下群，我不懂编程，完全就是用一键脚本弄得

**Comment by chika0801** [comment]
https://t.me/projectXray

**Comment by facebook20146** [comment]
> https://t.me/projectXray

谢谢，已加
