### ISSUE TITLE
How can I block traffic to range of IPs ?

### ISSUE THREAD

**Issue by lostsoul6** [XTLS/Xray-core#2011]
Hello my friends ,

I like to block access to Telegram for my xray users . I have the IP ranges of Telegram :  

91.105.192.0/23
91.108.4.0/22
91.108.8.0/22
91.108.12.0/22
91.108.16.0/22
91.108.20.0/22
91.108.56.0/23
91.108.58.0/23
95.161.64.0/20
149.154.160.0/21
149.154.168.0/22
149.154.172.0/22
185.76.151.0/24
2001:67c:4e8::/48
2001:b28:f23c::/48
2001:b28:f23d::/48
2001:b28:f23f::/48
2a0a:f280:203::/48

what is the correct syntax to block traffic to Telegram in xray config ? I checked many syntaxes but either I get error or the IPs are not blocked . 

Thank you for your help .

**Comment by SasukeFreestyle** [comment]
This is a correct for the IPs you provided, but I have not checked if they match all telegram servers.

```json
   "routing":{
      "domainStrategy":"IPIfNonMatch",
      "rules":[
         {
            "type":"field",
            "outboundTag":"block",
            "ip":[
               "91.105.192.0/23",
               "91.108.4.0/22",
               "91.108.8.0/22",
               "91.108.12.0/22",
               "91.108.16.0/22",
               "91.108.20.0/22",
               "91.108.56.0/23",
               "91.108.58.0/23",
               "95.161.64.0/20",
               "149.154.160.0/21",
               "149.154.168.0/22",
               "149.154.172.0/22",
               "185.76.151.0/24",
               "2001:67c:4e8::/48",
               "2001:b28:f23c::/48",
               "2001:b28:f23d::/48",
               "2001:b28:f23f::/48",
               "2a0a:f280:203::/48"
            ]
         }
      ]
   },
   "outbounds":[
      {
         "protocol":"freedom",
         "tag":"direct"
      },
      {
         "protocol":"blackhole",
         "tag":"block"
      }
```

**Comment by lostsoul6** [comment]
@SasukeFreestyle 

Thank you so much for answering . I tested it and it didn't work for me . First I thought the IPs were wrong so I tested a website with a single IP and it didn't work . I think I'm adding the code to a wrong place . The following is my current x-ray configuration . can you please add your code to my config and send me the full correct syntax ?

`{
  "log": {
    "loglevel": "warning",
    "access": "./access.log",
    "error": "./error.log"
  },
  "api": {
    "tag": "api",
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ]
  },
  "inbounds": [
    {
      "tag": "api",
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "blocked",
      "protocol": "blackhole",
      "settings": {}
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "statsUserDownlink": true,
        "statsUserUplink": true
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "port": "443",
        "network": "udp",
        "outboundTag": "block"
      },
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api"
      },
      {
        "type": "field",
        "outboundTag": "blocked",
        "ip": [
          "geoip:private"
        ]
      },
      {
        "type": "field",
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ]
      },
      {
        "type": "field",
        "outboundTag": "blocked",
        "domain": [
          "geosite:category-ads-all",
          "geosite:category-ads",
          "geosite:google-ads",
          "geosite:spotify-ads"
        ]
      },
      {
        "type": "field",
        "outboundTag": "blocked",
        "ip": [
          "geoip:ir"
        ]
      },
      {
        "type": "field",
        "outboundTag": "blocked",
        "domain": [
          "regexp:.*\\.ir$",
          "ext:iran.dat:ir",
          "ext:iran.dat:other",
          "ext:iran.dat:ads",
          "geosite:category-ir"
        ]
      }
    ]
  },
  "stats": {}
}`

**Comment by SasukeFreestyle** [comment]
Your blackhole protocol has the tagname "blocked"
```json
      {
         "tag":"blocked",
         "protocol":"blackhole",
         "settings":{
             }
```
 while 
 
```json
        "type": "field",
        "port": "443",
        "network": "udp",
        "outboundTag": "block"
```
was named "block" because of this it will not match the rule, fixed it for you.

This is also a good online tool to check your Json if you have further problems.

https://jsonformatter.curiousconcept.com

Full syntax.

```json
{
   "log":{
      "loglevel":"warning",
      "access":"./access.log",
      "error":"./error.log"
   },
   "api":{
      "tag":"api",
      "services":[
         "HandlerService",
         "LoggerService",
         "StatsService"
      ]
   },
   "inbounds":[
      {
         "tag":"api",
         "listen":"127.0.0.1",
         "port":62789,
         "protocol":"dokodemo-door",
         "settings":{
            "address":"127.0.0.1"
         }
      }
   ],
   "outbounds":[
      {
         "protocol":"freedom",
         "settings":{
            
         }
      },
      {
         "tag":"blocked",
         "protocol":"blackhole",
         "settings":{
            
         }
      }
   ],
   "policy":{
      "levels":{
         "0":{
            "statsUserDownlink":true,
            "statsUserUplink":true
         }
      },
      "system":{
         "statsInboundDownlink":true,
         "statsInboundUplink":true
      }
   },
   "routing":{
      "domainStrategy":"IPIfNonMatch",
      "rules":[
         {
            "type":"field",
            "outboundTag":"blocked",
            "ip":[
               "91.105.192.0/23",
               "91.108.4.0/22",
               "91.108.8.0/22",
               "91.108.12.0/22",
               "91.108.16.0/22",
               "91.108.20.0/22",
               "91.108.56.0/23",
               "91.108.58.0/23",
               "95.161.64.0/20",
               "149.154.160.0/21",
               "149.154.168.0/22",
               "149.154.172.0/22",
               "185.76.151.0/24",
               "2001:67c:4e8::/48",
               "2001:b28:f23c::/48",
               "2001:b28:f23d::/48",
               "2001:b28:f23f::/48",
               "2a0a:f280:203::/48"
            ]
         },
         {
            "type":"field",
            "port":"443",
            "network":"udp",
            "outboundTag":"blocked"
         },
         {
            "type":"field",
            "inboundTag":[
               "api"
            ],
            "outboundTag":"api"
         },
         {
            "type":"field",
            "outboundTag":"blocked",
            "ip":[
               "geoip:private"
            ]
         },
         {
            "type":"field",
            "outboundTag":"blocked",
            "protocol":[
               "bittorrent"
            ]
         },
         {
            "type":"field",
            "outboundTag":"blocked",
            "domain":[
               "geosite:category-ads-all",
               "geosite:category-ads",
               "geosite:google-ads",
               "geosite:spotify-ads"
            ]
         },
         {
            "type":"field",
            "outboundTag":"blocked",
            "ip":[
               "geoip:ir"
            ]
         },
         {
            "type":"field",
            "outboundTag":"blocked",
            "domain":[
               "regexp:.*\\.ir$",
               "ext:iran.dat:ir",
               "ext:iran.dat:other",
               "ext:iran.dat:ads",
               "geosite:category-ir"
            ]
         }
      ]
   },
   "stats":{
      
   }
}
```

**Comment by lostsoul6** [comment]
@SasukeFreestyle 

That worked perfectly and now telegram app is stuck on connecting while connected to this server . Is there anyway to contact you on telegram or via e-mail ? I want to block some more apps on this server and I'm looking for someone to take care of it . I can also pay for the project .

My issue is that for example I want to block whatsapp application but when using the following rule , only whatsapp domains are blocked but I can still send messages on whatsapp android application :

"geosite:whatsapp",

As it seems , I should find all whatsapp IP addresses as well again which I haven't been able to yet . Is it a way to block this app by hostname ? I have already tried blocking the following but I'm still able to send messages on whatsapp android app :  

               "whatsapp-plus.info",
               "whatsapp-plus.me",
               "whatsapp-plus.net",
               "whatsapp.cc",
               "whatsapp.com",
               "whatsapp.info",
               "whatsapp.net",
               "whatsapp.org",
               "whatsapp.tv",
               "whatsappbrand.com",

I would be thankful if you could help me fix this and I also can pay for your services if required .

**Comment by lostsoul6** [comment]
@SasukeFreestyle Dear friend don't bother with the above post as I found out that it is impossible to block whatsapp android app unless you block the whole internet or you have GFW :D . I blocked all the IPs that Meta owns and checked wireshark to check what happens . It used Amazon IPs to load the app ! I blocked all Amazon IPs and it used Google Cloud IPs to load the app . I guess rather than Allowing everything and blocking unwanted content , I can block everything and then allow the ones I want ! For this I need your help to change the config again . How can I change the config you sent me to block everything then allow domains ?

```
{
   "log":{
      "loglevel":"warning",
      "access":"./access.log",
      "error":"./error.log"
   },
   "api":{
      "tag":"api",
      "services":[
         "HandlerService",
         "LoggerService",
         "StatsService"
      ]
   },
   "inbounds":[
      {
         "tag":"api",
         "listen":"127.0.0.1",
         "port":62789,
         "protocol":"dokodemo-door",
         "settings":{
            "address":"127.0.0.1"
         }
      }
   ],
   "outbounds":[
      {
         "protocol":"freedom",
         "settings":{
            
         }
      },
      {
         "tag":"blocked",
         "protocol":"blackhole",
         "settings":{
            
         }
      }
   ],
   "policy":{
      "levels":{
         "0":{
            "statsUserDownlink":true,
            "statsUserUplink":true
         }
      },
      "system":{
         "statsInboundDownlink":true,
         "statsInboundUplink":true
      }
   },
   "routing":{
      "domainStrategy":"IPIfNonMatch",
      "rules":[
         {
            "type":"field",
            "outboundTag":"blocked",
            "ip":[
               "91.105.192.0/23",
               "91.108.4.0/22",
               "91.108.8.0/22",
               "91.108.12.0/22",
               "91.108.16.0/22",
               "91.108.20.0/22",
               "91.108.56.0/23",
               "91.108.58.0/23",
               "95.161.64.0/20",
               "149.154.160.0/21",
               "149.154.168.0/22",
               "149.154.172.0/22",
               "185.76.151.0/24",
               "2001:67c:4e8::/48",
               "2001:b28:f23c::/48",
               "2001:b28:f23d::/48",
               "2001:b28:f23f::/48",
               "2a0a:f280:203::/48"
            ]
         },
         {
            "type":"field",
            "port":"443",
            "network":"udp",
            "outboundTag":"blocked"
         },
         {
            "type":"field",
            "inboundTag":[
               "api"
            ],
            "outboundTag":"api"
         },
         {
            "type":"field",
            "outboundTag":"blocked",
            "ip":[
               "geoip:private"
            ]
         },
         {
            "type":"field",
            "outboundTag":"blocked",
            "protocol":[
               "bittorrent"
            ]
         },
         {
            "type":"field",
            "outboundTag":"blocked",
            "domain":[
               "geosite:category-ads-all",
               "geosite:category-ads",
               "geosite:google-ads",
               "geosite:spotify-ads"
            ]
         },
         {
            "type":"field",
            "outboundTag":"blocked",
            "ip":[
               "geoip:ir"
            ]
         },
         {
            "type":"field",
            "outboundTag":"blocked",
            "domain":[
               "regexp:.*\\.ir$",
               "ext:iran.dat:ir",
               "ext:iran.dat:other",
               "ext:iran.dat:ads",
               "geosite:category-ir"
            ]
         }
      ]
   },
   "stats":{
      
   }
}
```

**Comment by mglwolf** [comment]
You no need to block the whole internet, just move to China That's it :-)
please enable debug mode on xray-core, then you will see the activities of wts, and you can make your own blocking strategy.
{
   "log":{
      "loglevel":"debug",

**Comment by lostsoul6** [comment]
> No need to block the whole internet, just move to China That's it :-) please enable debugging mode on xray-core, then you will see the activities of wts, and make your own blocking strategy. { "log":{ "loglevel":"debug",

You think China is the worst ? Mate , come to Iran . that's basically 5000 times worse :))

**Comment by ahmadipiralvan** [comment]
Hi
I am looking to restrict my inbound connections to IPs of a specific country.
For example, only Russian or Chinese users can connect to my server and my inbounds.
Is such a thing possible?
