### ISSUE TITLE
xray on vmess GRPC on server is restarting because of huge ram usage

### ISSUE THREAD

**Issue by dragonfly20004** [XTLS/Xray-core#2016]
Hi. the server is configured to use vmess with grpc and there is 10 clients using it.
the problem is The RAM used by the program fills up quickly and starting to push inside swap memory. ultimately will be restarted by systemd and all the clients experience a suddent disconnect.
i have tried these methods:
reducing buffer size to 0
limiting ram usage in systemd by MemoryLimit to 1GB => still xray will restart
tried to reduce the keepalive time from systemctl to 30 seconds it helps with disconnecting open tcp connections but it did not help with ram usage and ram usage still remains the same even people disconnects ( it may take 10-15 minutes to see a drop in ram usage but not alot for example a service with only single user on it after 5 speedtests reached about 700 megabyte ram usage and after 15 minutes it goes back to like 300 megabytes!)

by the way thanks for your effort on this app.

**Comment by dragonfly20004** [comment]
and seems it's only related to grpc transport. in the h2 mode everything works perfectly

**Comment by dragonfly20004** [comment]
ok. i found the problem. WIREGUARD in OUTBOUND is causing this !

**Comment by yuhan6665** [comment]
Fixed in latest main build

**Comment by yuhan6665** [comment]
If you can, try latest main

**Comment by artemkaa2001** [comment]
Unfortunately, the issue has not been resolved; even on the newest version, the same memory leak remains.
