### ISSUE TITLE
1.8.1 panic

### ISSUE THREAD

**Issue by GreatMichaelLee** [XTLS/Xray-core#2017]
passwall 4.65-2+ lede 最新仓库（6.1.25内核） x86 平台，xray core 1.8.1 发现Panic

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x9d3c80]

goroutine 1830889 [running]:
github.com/xtls/xray-core/transport/internet/reality.UClient.func1.2(0x1)
        github.com/xtls/xray-core/transport/internet/reality/reality.go:190 +0x1c0
github.com/xtls/xray-core/transport/internet/reality.UClient.func1()
        github.com/xtls/xray-core/transport/internet/reality/reality.go:229 +0x47b
created by github.com/xtls/xray-core/transport/internet/reality.UClient
        github.com/xtls/xray-core/transport/internet/reality/reality.go:154 +0xd9d

**Comment by H1JK** [comment]
This only happens when the REALITY authentication fails, in other words, you most likely configured REALITY incorrectly.

**Comment by GreatMichaelLee** [comment]
100% sure no incorrect configuration and it works fine when xray core start up.



---Original---
From: ***@***.***&gt;
Date: Tue, May 2, 2023 18:25 PM
To: ***@***.***&gt;;
Cc: "michael ***@***.******@***.***&gt;;
Subject: Re: [XTLS/Xray-core] 1.8.1 panic (Issue #2017)




 
This only happens when the REALITY authentication fails, in other words, you most likely configured REALITY incorrectly.

**Comment by chika0801** [comment]
试试把 dest 目标网站换其它的了。

或用 no sni any sni那种

或用 自己偷自己 那种。

**Comment by GreatMichaelLee** [comment]
这个换dest具体的"科学"原因是啥？还是玄学…



---Original---
From: ***@***.***&gt;
Date: Tue, May 2, 2023 19:38 PM
To: ***@***.***&gt;;
Cc: "michael ***@***.******@***.***&gt;;
Subject: Re: [XTLS/Xray-core] 1.8.1 panic (Issue #2017)




 
试试把 dest 目标网站换其它的了。
 
或用 no sni any sni那种
 
或用 自己偷自己 那种。

**Comment by chika0801** [comment]
> 这个换dest具体的"科学"原因是啥？还是玄学…
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Tue, May 2, 2023 19:38 PM To: ***@***.***&gt;; Cc: "michael ***@***.******@***.***&gt;; Subject: Re: [XTLS/Xray-core] 1.8.1 panic (Issue #2017) 试试把 dest 目标网站换其它的了。 或用 no sni any sni那种 或用 自己偷自己 那种。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

自己几个vps莫名遇到，后自己总结的。

现象是假设几个vps全是优化线路开vless vision tls的速度一切正常。

换vless vision reality，目标域名1，客户端现象是点链接第1次dns感觉多等了n秒。目标域名2，现象是在v2rayn里点测延时时快时慢，打开网页也慢。

现在3就是比如昨天一节正常。今天起床用死活不通。看服务端日志没接收到任何请求。

用自己偷自己再也没遇到上面现象。或尝试no sni 也没遇到。这莫名现象群里我观察有其它也遇到类似的 我都这样建议排查下

**Comment by RPRX** [comment]
第 190 行，可能是上面的 `req, _ = http.NewRequest("GET", firstURL, nil)` 或 `req, _ = http.NewRequest("GET", string(prefix)+getPathLocked(paths), nil)` 返回了 error，不过当初我本地测试是没问题的。

认证失败时才会触发这部分代码，应该有不少人触发过，第一次收到 panic 报告。

---

目标网站/域名的选择会极大程度地影响 REALITY 代理的延迟、速度、稳定性等：
1. 至少目前，REALITY 每次都要去拿握手包，需要注意目标网站近不近、稳不稳定（请求多了就把你半拉黑也是一种不稳定）。
2. 运营商层面可能会给某些域名更高的流量优先级，拥堵时优先保证它们的流量通过。
3. GFW 层面至少有黑名单（google）和白名单（microsoft），可能还有其它名单，比如偶尔干扰/限速名单（github？）

你们对照排查一下。

**Comment by chika0801** [comment]
我遇到过不同vps，选比如www.apple.com learn.microsoft.com
，表现是客户端填信息时，排除公钥，短id都正确，sni填上面的，在v2rayn保存配置，浏览器http代理访问，浏览器打不开网页。看v2rayn的日志就发送代理到vps。
vps端日志没接收到任何请求。（日志没变化滚动更新）

此时我去vps配置上改成no sni any sni后保存重启xray。客户端在v2rayn中跟着对应修改，马上就通了。速度也一切正常。

类似现象，我这我是最近2周陆续观察了。现在自己用有一些vps要不用自己偷自己，要不是no sni any sni形式，就一直正常。

原理说不清楚。但是一我用dest是www.lovelive-anime.jp这倒是没遇到。用apple microsotf 遇到过

**Comment by chika0801** [comment]
加上最近是群内一直有群友来问reality内似昨天通，今天不通了。或一直连不通。我自己测试其它dest网址时也遇到类似的，我才开始留意。
比如最近的这位 https://t.me/projectXray/2297385，所以我给上面的建议排除法试试了

**Comment by RPRX** [comment]
~~也可能是你们天天逮着 microsoft、apple 之类的偷，GFW 开始测试了~~，有人说伊朗那边就有运营商在“内测” yahoo 的 IP 白名单。

---

REALITY 以后会出个缓存模式，提前采集目标网站的特征，就不用每次都去拿了，这也是相对于 ShadowTLS 之类的优势之一。

还有就是 REALITY 隐藏玩法的任意 SNI、无 SNI，对 REALITY 来说，只要 serverName 是 serverNames 之一，想填啥就填啥。
我需要说明一下不是只有 1.1.1.1 和 8.8.8.8，而是绝大多数网站都有“默认证书”。不过不希望这个玩法泛滥，因为特征明显。

**Comment by chika0801** [comment]
伊朗白名单ip的事，是前几天他们老哥深夜在群里说（讨论）的样（我还有点印象）

我问chatgpt哪些是有https://ip的网站回答的是1.1.1.1 8.8.8.8 9.9.9.9我试了不通。还能有其它的？有空研究下了。

这玩法也怕泛滥啊。

**Comment by chika0801** [comment]
@5e2t 你去年就遇到几分钟断这现象了呀。我查了iss是
https://github.com/3andne/restls/issues/8

和这个讨论 https://github.com/XTLS/Xray-core/discussions/1772

**Comment by RPRX** [comment]
To tinyflag east：“只要 serverName 是 serverNames 之一”的意思是只要服务端写了，客户端就能填，不需要 dest 真的有那个网站

SNI 分流与“REALITY 对外表现为端口转发”的目标不符，REALITY 服务端的实现非常严谨，对任何非认证流量都是纯端口转发
本质上，REALITY 是一开始就双向转发，同时在旁路尝试对双向流量进行条件非常严格的认证，~~这句话我好像在哪说过~~

**Comment by RPRX** [comment]
> 我问chatgpt哪些是有 https://ip 的网站回答的是1.1.1.1 8.8.8.8 9.9.9.9我试了不通。还能有其它的？有空研究下了。

显然是误解了 https://t.me/projectXtls/78 ，一般来说 TLS 服务端都有个“默认证书”，除非配置了拒绝未知 SNI 之类的
[RealiTLScanner](https://github.com/XTLS/RealiTLScanner) 就是用这个原理来扫 IP 段的网站的，~~换句话说它扫出来的网站都可以无 SNI，极大概率也能任意 SNI~~

**Comment by chika0801** [comment]
马上再去试试 [RealiTLScanner](https://github.com/XTLS/RealiTLScanner) 扫 :disappointed_relieved:

**Comment by RPRX** [comment]
To 群里：对于喜欢用已经黑了的 IP/IP 段测试 REALITY 的，我只能说，

**Comment by shadow750d6** [comment]
> To 群里：对于喜欢用已经黑了的 IP/IP 段测试 REALITY 的，我只能说，

只能说干得漂亮

**Comment by RPRX** [comment]
~~建议拉满，以后只用甲骨文~~

**Comment by chika0801** [comment]
现在看到提起甲骨文，回想真是用甲骨文遇到3分钟之类莫名现象的群友是最多的。:scream::scream::scream:

**Comment by shadow750d6** [comment]
> @chika0801 据用甲骨文的群友描述，甲骨文绝大部分IP都被GFW列为黑名单了。。。

甲骨文那么难开通，怎么会用到拉黑的地步

**Comment by chika0801** [comment]
@shadow750d6 hostloc 一个MJJ论坛有卖，还有各TG群 发卡站有卖料卡（黑料）吧注册的了。。。MJJ市场太大，有市场就有供应？

**Comment by zizifn** [comment]
> 第 190 行，可能是上面的 `req, _ = http.NewRequest("GET", firstURL, nil)` 或 `req, _ = http.NewRequest("GET", string(prefix)+getPathLocked(paths), nil)` 返回了 error，不过当初我本地测试是没问题的。
> 
> 认证失败时才会触发这部分代码，应该有不少人触发过，第一次收到 panic 报告。
> 
> 目标网站/域名的选择会极大程度地影响 REALITY 代理的延迟、速度、稳定性等：
> 
> 1. 至少目前，REALITY 每次都要去拿握手包，需要注意目标网站近不近、稳不稳定（请求多了就把你半拉黑也是一种不稳定）。
> 2. 运营商层面可能会给某些域名更高的流量优先级，拥堵时优先保证它们的流量通过。
> 3. GFW 层面至少有黑名单（google）和白名单（microsoft），可能还有其它名单，比如偶尔干扰/限速名单（github？）
> 
> 你们对照排查一下。

我有点理解不了。为什么每次都需要目标网站的包？ 如果我想学习下原理，请问有什么轻松的办法可以拿到 reality的SSLKEYLOGFILE， 然后可以在 wireshark 看到 解密的tls 报文吗？

**Comment by RPRX** [comment]
@zizifn 方向错了，你应该看 https://github.com/XTLS/REALITY/blob/main/tls.go 的 Server 函数

本质上是对通过认证的外层 TLS 进行了一次~~大开脑洞的~~事先约好的 MitM，加上一些细节需要注意

**Comment by RPRX** [comment]
顺便先简单说一下 v1.8.1 [增强版 XUDP](https://github.com/XTLS/Xray-core/issues/1963#issuecomment-1512532299) 的 [Global ID & UoT Migration](https://xtls.github.io/development/protocols/muxcool.html#%E6%96%B0%E5%BB%BA%E5%AD%90%E8%BF%9E%E6%8E%A5-new) 有什么效果：

v1.8.1 以前，你用任何 UoT，假设服务端用 A 端口与多目标通信，若 TCP 断了，比如切换网络，重连后服务端会改用 B 端口。
v1.8.1 开始，你用 VLESS（包括 Mux.Cool），即使 TCP 断了，重连后服务端还是会用 A 端口。

尤其是，对 P2P 有奇效。从某种程度上来说，这才是真正的 FullCone。双端 Xray-core v1.8.1+ 自动启用，无需额外配置。

可以用 [NatTypeTester](https://github.com/HMBSbige/NatTypeTester)，先连接家里 WiFi 测一下，再连接手机热点（流量）测一下，你会发现服务端出口端口没变，~~挺神奇的。~~

~~更多内容，咕咕咕，请等文章。~~

**Comment by chika0801** [comment]
好耶x2

**Comment by RPRX** [comment]
To 6：恭喜盲生发现了华点。这只是一个序幕。~~更多内容，咕咕咕，请等文章。~~

**Comment by RPRX** [comment]
To Ace Yui：何止不会断流，~~难道大家以为 Vision 的 0-RTT 是 TCP fast open 加 TLS early data 吗。~~

**Comment by zizifn** [comment]
> @zizifn 方向错了，你应该看 https://github.com/XTLS/REALITY/blob/main/tls.go 的 Server 函数
> 
> 本质上是对通过认证的外层 TLS 进行了一次~大开脑洞的~事先约好的 MitM，加上一些细节需要注意

有没有一种可能，就是直接修改浏览器发过来 client hello 的 sni，然后把真正的 sni 和 uuid 加密 放入到 clienthello 的某个 extension 中，然后 server 在解密，在把原本浏览器得 clienthello sni 复原，这样以后到所以包都可以原封不动。

**Comment by GreatMichaelLee** [comment]
> > @zizifn 方向错了，你应该看 https://github.com/XTLS/REALITY/blob/main/tls.go 的 Server 函数
> > 本质上是对通过认证的外层 TLS 进行了一次~大开脑洞的~事先约好的 MitM，加上一些细节需要注意
> 
> 有没有一种可能，就是直接修改浏览器发过来 client hello 的 sni，然后把真正的 sni 和 uuid 加密 放入到 clienthello 的某个 extension 中，然后 server 在解密，在把原本浏览器得 clienthello sni 复原，这样以后到所以包都可以原封不动。

那这个extension会不会变成特征，被GFW识别，以后直接看到有这种特征的hello全部reject

**Comment by RPRX** [comment]
@zizifn Why not https://github.com/XTLS/Xray-core/discussions/1993#discussioncomment-5737892

**Comment by zizifn** [comment]
> > > @zizifn 方向错了，你应该看 https://github.com/XTLS/REALITY/blob/main/tls.go 的 Server 函数
> > > 本质上是对通过认证的外层 TLS 进行了一次~大开脑洞的~事先约好的 MitM，加上一些细节需要注意
> > 
> > 
> > 有没有一种可能，就是直接修改浏览器发过来 client hello 的 sni，然后把真正的 sni 和 uuid 加密 放入到 clienthello 的某个 extension 中，然后 server 在解密，在把原本浏览器得 clienthello sni 复原，这样以后到所以包都可以原封不动。
> 
> 那这个extension会不会变成特征，被GFW识别，以后直接看到有这种特征的hello全部reject

mtls 有一个 send client 证书，可以利用这个把 uuid 和原始 sni 加密放进去。mtls 在互联网很常见。

**Comment by zizifn** [comment]
> > > > @zizifn 方向错了，你应该看 https://github.com/XTLS/REALITY/blob/main/tls.go 的 Server 函数
> > > > 本质上是对通过认证的外层 TLS 进行了一次~大开脑洞的~事先约好的 MitM，加上一些细节需要注意
> > > 
> > > 
> > > 有没有一种可能，就是直接修改浏览器发过来 client hello 的 sni，然后把真正的 sni 和 uuid 加密 放入到 clienthello 的某个 extension 中，然后 server 在解密，在把原本浏览器得 clienthello sni 复原，这样以后到所以包都可以原封不动。
> > 
> > 
> > 那这个extension会不会变成特征，被GFW识别，以后直接看到有这种特征的hello全部reject
> 
> mtls 有一个 send client 证书，可以利用这个把 uuid 和原始 sni 加密放进去。mtls 在互联网很常见。这样做 server 基本就是多处理一个 send client 证书的包。其他和直接访问网站全部都一样。根本没有多余延迟和解密。

我感觉 reality 既然已经有了预先生成的 私钥和公钥，完全可以利用 mtls 的机制，传递 uuid 和原始 sni. 抛弃现在用 tls 传递原始 client hello 的逻辑。

**Comment by RPRX** [comment]
To January：~~这是什么断章取义的合订本？~~

都是 TLS，但怎么用 TLS，是有讲究的，有句话我早就想对鼓吹 Trojan 平替 VLESS 的人说：**真以为 Trojan 能用一辈子？**
早在三年前的 VLESS BETA 我就给你们说过，光套一层加密并不能掩盖里面的时序特征，所以 VLESS 有 flow 机制。
但是呢，以前的 GFW 没上手段，简单套个 TLS 在实践上的确还可以用，就像 WS ALPN 一直很明显，但以前它能用。
它们还能用，我就没必要提前出牌，等 GFW 上了手段，我再继续出牌，并且不推荐大家再用旧的 WS、无 flow 等。

有一点需要再次强调，我支持的始终是 TLS 上的百花齐放，而不是 TCP 上的，原因以前说过很多，可以去 [v2ray](https://github.com/v2ray/v2ray-core/issues/2523#issuecomment-636548331) 翻翻。
前段时间不是有个论文嘛，~~算了不想说了，有空时再评论。~~

**Comment by RPRX** [comment]
To qyj crower：当你对着一个端口转发测出和转发目标不同的 jarm 指纹时，应该去改系统 host，注意是系统 host。

**Comment by nursery01** [comment]
> 它们还能用，我就没必要提前出牌，等 GFW 上了手段，我再继续出牌

不愧是rprx，不過中國應該有世界大部分網站的dns ip，~~如果使用ip白名單，效果可比sni白名單好~~

**Comment by timi-owo** [comment]
> 顺便先简单说一下 v1.8.1 [增强版 XUDP](https://github.com/XTLS/Xray-core/issues/1963#issuecomment-1512532299) 的 [Global ID & UoT Migration](https://xtls.github.io/development/protocols/muxcool.html#%E6%96%B0%E5%BB%BA%E5%AD%90%E8%BF%9E%E6%8E%A5-new) 有什么效果：
> 
> v1.8.1 以前，你用任何 UoT，假设服务端用 A 端口与多目标通信，若 TCP 断了，比如切换网络，重连后服务端会改用 B 端口。 v1.8.1 开始，你用 VLESS（包括 Mux.Cool），即使 TCP 断了，重连后服务端还是会用 A 端口。
> 
> 尤其是，对 P2P 有奇效。从某种程度上来说，这才是真正的 FullCone。双端 Xray-core v1.8.1+ 自动启用，无需额外配置。
> 
> 可以用 [NatTypeTester](https://github.com/HMBSbige/NatTypeTester)，先连接家里 WiFi 测一下，再连接手机热点（流量）测一下，你会发现服务端出口端口没变，~挺神奇的。~
> 
> ~更多内容，咕咕咕，请等文章。~

每次在各种 Issues 和 Discussions 看到 R 佬的发言，就感觉无意中又收集到一个新的 “宝藏碎片”。

这绝对不是自言自语，请 R 佬以后务必多讲，这些原理相关的内容我们也爱看，也能引发更多的思考。

~（不过我也能理解，组织语言写文章有时候比写代码更麻烦）~

**Comment by chika0801** [comment]
https://t.me/projectXray/2344671

Neko LSD 的reality 被阻断复现方法
1. tcping -t <VPS_IP> 443
2. curl -v https://www.apple.com --resovle www.apple.com:443:<VPS_IP> 重复几次，直到无法捂手
3.  观察tcping 出现超时
4.  traceroute -d <VPS_IP>，在城域网-骨干网边界被空路由
5.  等待tcping恢复，统计tcping失败次数共计90次，频率2秒1次，共计180秒
---------------------------------------
6.  分析结果，DNS A记录与SNI不一致，与优先CFIP阻断方式相同

**Comment by Smallthing** [comment]
> 顺便先简单说一下 v1.8.1 [增强版 XUDP](https://github.com/XTLS/Xray-core/issues/1963#issuecomment-1512532299) 的 [Global ID & UoT Migration](https://xtls.github.io/development/protocols/muxcool.html#%E6%96%B0%E5%BB%BA%E5%AD%90%E8%BF%9E%E6%8E%A5-new) 有什么效果：
> 
> v1.8.1 以前，你用任何 UoT，假设服务端用 A 端口与多目标通信，若 TCP 断了，比如切换网络，重连后服务端会改用 B 端口。 v1.8.1 开始，你用 VLESS（包括 Mux.Cool），即使 TCP 断了，重连后服务端还是会用 A 端口。
> 
> 尤其是，对 P2P 有奇效。从某种程度上来说，这才是真正的 FullCone。双端 Xray-core v1.8.1+ 自动启用，无需额外配置。
> 
> 可以用 [NatTypeTester](https://github.com/HMBSbige/NatTypeTester)，先连接家里 WiFi 测一下，再连接手机热点（流量）测一下，你会发现服务端出口端口没变，~挺神奇的。~
> 
> ~更多内容，咕咕咕，请等文章。~

这个我没有操作成功，还是会变，具体断掉i的是哪一层呢

**Comment by RPRX** [comment]
> 这个我没有操作成功，还是会变，具体断掉i的是哪一层呢

~~让我算命吗~~ 我只能说若你严格按照我写的去操作 就能成功

**Comment by Smallthing** [comment]
> > 这个我没有操作成功，还是会变，具体断掉i的是哪一层呢
> 
> ~让我算命吗~ 我只能说若你严格按照我写的去操作 就能成功

什么配置都没改第二天就成功了。可以的。

**Comment by base510** [comment]
@RPRX release下载的1.8.1和1.7.5 amd64服务端，运行ss2022多用户模式都出现panic 
①
2023/04/30 20:00:38 [Error] common/net: invalid IP format: []
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x982078]

goroutine 92630 [running]:
github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).getUoTConnection(0xc0001d5ce0, {0x13eeb40, 0xc0008e5290}, {{0x0?, 0x0?}, 0x7f?, 0x0?})
        github.com/xtls/xray-core/app/proxyman/outbound/uot.go:14 +0x58
github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dial(0xc0001d5ce0, {0x13eeb40?, 0xc0008e5290?}, {{0x0, 0x0}, 0xb, 0x2})
        github.com/xtls/xray-core/app/proxyman/outbound/handler.go:214 +0xa26
github.com/xtls/xray-core/proxy/freedom.(*Handler).Process.func1()
        github.com/xtls/xray-core/proxy/freedom/freedom.go:140 +0x2c6
github.com/xtls/xray-core/common/retry.(*retryer).On(0xc00125dd08, 0xc00125dd60)
        github.com/xtls/xray-core/common/retry/retry.go:27 +0xdb
github.com/xtls/xray-core/proxy/freedom.(*Handler).Process(0xc00021bce0, {0x13eeb40, 0xc0008e5290}, 0xc0008e2460, {0x13e6748, 0xc0001d5ce0})
        github.com/xtls/xray-core/proxy/freedom/freedom.go:126 +0x4b0
github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dispatch(0xc000c07920?, {0x13eeb40, 0xc0008e5290}, 0xc0008e2460)
        github.com/xtls/xray-core/app/proxyman/outbound/handler.go:147 +0x211
github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc0001c7f80, {0x13eeb40, 0xc0008e5290}, 0xc0008e2460, {{0x0, 0x0}, 0xb, 0x2})
        github.com/xtls/xray-core/app/dispatcher/default.go:492 +0xbfe
created by github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch
        github.com/xtls/xray-core/app/dispatcher/default.go:302 +0x4ea


②
2023/05/01 20:16:07 [Error] common/net: invalid IP format: []
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x6f5e78]

goroutine 28590 [running]:
github.com/xtls/xray-core/features/routing/session.(*Context).GetTargetDomain(0xc036cdfdb0?)
        github.com/xtls/xray-core/features/routing/session/context.go:79 +0x78
github.com/xtls/xray-core/app/router.(*DomainMatcher).Apply(0xc036cdfd68?, {0x149afb8?, 0xc031542f18?})
        github.com/xtls/xray-core/app/router/condition.go:107 +0x2c
github.com/xtls/xray-core/app/router.(*ConditionChan).Apply(0xc036cdfdd0?, {0x149afb8, 0xc031542f18})
        github.com/xtls/xray-core/app/router/condition.go:32 +0x6e
github.com/xtls/xray-core/app/router.(*Rule).Apply(...)
        github.com/xtls/xray-core/app/router/config.go:63
github.com/xtls/xray-core/app/router.(*Router).pickRouteInternal(0xc000239600, {0x149afb8, 0xc031542f18})
        github.com/xtls/xray-core/app/router/router.go:94 +0x196
github.com/xtls/xray-core/app/router.(*Router).PickRoute(0x1490720?, {0x149afb8?, 0xc031542f18?})
        github.com/xtls/xray-core/app/router/router.go:72 +0x27
github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc0000833e0, {0x1490720, 0xc039e6ee40}, 0xc039f5d720, {{0x0, 0x0}, 0xb, 0x2})
        github.com/xtls/xray-core/app/dispatcher/default.go:452 +0x2bc
created by github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch
        github.com/xtls/xray-core/app/dispatcher/default.go:302 +0x4ea

**Comment by lanvada** [comment]
> 第 190 行，可能是上面的 `req, _ = http.NewRequest("GET", firstURL, nil)` 或 `req, _ = http.NewRequest("GET", string(prefix)+getPathLocked(paths), nil)` 返回了 error，不过当初我本地测试是没问题的。
> 
> 认证失败时才会触发这部分代码，应该有不少人触发过，第一次收到 panic 报告。
> 
> 目标网站/域名的选择会极大程度地影响 REALITY 代理的延迟、速度、稳定性等：
> 
> 1. 至少目前，REALITY 每次都要去拿握手包，需要注意目标网站近不近、稳不稳定（请求多了就把你半拉黑也是一种不稳定）。
> 2. 运营商层面可能会给某些域名更高的流量优先级，拥堵时优先保证它们的流量通过。
> 3. GFW 层面至少有黑名单（google）和白名单（microsoft），可能还有其它名单，比如偶尔干扰/限速名单（github？）
> 
> 你们对照排查一下。

#2366 #2368 
我目前的每个服务器选择的目标网站都是我通过chatgpt查询的当地常用的网站，然后又通过域名查询确认了ip和我的服务器在同一个国家。另外在我服务器全挂掉之后，我也测试了这些目标网站和我的伪装网站能否在墙内直连，也都可以连接上

**Comment by Fangliding** [comment]
Reopen if it's still exists
