### ISSUE TITLE
协议 WireGuard 出栈存在内存泄漏

### ISSUE THREAD

**Issue by r06ertray** [XTLS/Xray-core#2031]
1、运行 Xray，配置文件如下 (需使用 wgcf 创建可用的 secretKey)
```
{
    "log": {
        "loglevel": "warning"
    },
    "inbounds": [
        {
            "port": 12345,
            "listen": "127.0.0.1",
            "protocol": "http",
            "settings": {
                "udp": true
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "wireguard",
            "settings": {
                "secretKey": "********************************************",
                "address": [
                    "172.16.0.2/32"
                ],
                "peers": [
                    {
                        "publicKey": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
                        "endpoint": "engage.cloudflareclient.com:2408",
                        "allowedIPs": [
                            "0.0.0.0/0"
                        ]
                    }
                ]
            }
        }
    ]
}
```

2、使用 Xray 的代理通道访问网络(以 https://cloudflare.com 为例)
```
while true; do curl -s -o /dev/null -x http://127.0.0.1:12345 https://cloudflare.com; done
```

3、使用 htop 观察 Xray 进程的内存，会发现 RES 占用持续缓慢增涨

**Comment by hululu1068** [comment]
我也碰到这个情况。。。
之前设置定时重启，有所缓解。现在用[wireproxy](https://github.com/pufferffish/wireproxy)，转成socks接口使用，效果还不错。

**Comment by r06ertray** [comment]
> 我也碰到这个情况。。。 之前设置定时重启，有所缓解。现在用[wireproxy](https://github.com/pufferffish/wireproxy)，转成socks接口使用，效果还不错。

确实可以，效果不错

**Comment by hululu1068** [comment]
> > 我也碰到这个情况。。。 之前设置定时重启，有所缓解。现在用[wireproxy](https://github.com/pufferffish/wireproxy)，转成socks接口使用，效果还不错。
> 
> 确实可以，效果不错
Commit [e732470](https://github.com/XTLS/Xray-core/commit/e7324700edf886afea14845c648f40abdf6e9818)已经解决了，现在正常了。

<img width="383" alt="image" src="https://github.com/XTLS/Xray-core/assets/68652362/9d19c88d-c3a6-4982-bebf-f21f84e48883">
