### ISSUE TITLE
Add support for process-based traffic routing

### ISSUE THREAD

**Issue by orwithout** [XTLS/Xray-core#2032]
Description:

Add the ability to route process-based network traffic to different proxy servers in Xray-core. This feature will allow users to manage connections to different proxy servers more easily and bring added convenience and flexibility to the software.

Expected Result:

Xray-core users will be able to send network traffic of a specific process to designated proxy servers as required by using this feature.

Additional Information:

Currently, there is no way to route network traffic of a specific process to designated proxy servers in Xray-core. Many users have been asking for this feature, citing its presence in other proxy software such as Clash for Windows and Proxifier. Therefore, adding this feature would make Xray-core competitive in a crowded market.

Users will appreciate this feature since it will provide them with a way to better manage their network traffic.

In our research to find alternatives to Xray-core, we found the following software and applications to support process-based proxy redirection: 

- Microsoft Application Request Routing 
- Free utility called KKcap 
- Azure Active Directory Application Proxy

However, we should not overlook the unique strengths of Xray-core.

**Comment by Fangliding** [comment]
One day(pigeoning)
