### ISSUE TITLE
Security Vulnerability Found

### ISSUE THREAD

**Issue by ghost** [XTLS/Xray-core#2038]
Hi,

I would like to report a potential security vulnerability. Can you please [create a GHSA ](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/creating-a-repository-security-advisory) and add me as a collaborator?

**Comment by RPRX** [comment]
>  Private vulnerability reporting • Enabled
Allow users to privately report potential security vulnerabilities

**Comment by RPRX** [comment]
感谢你的报告，截至目前，HTTP 入站 99% 以上的用例为“在本地接收代理请求”，所以其实现并不严谨，类似的还有 Socks 的 UDP

不过，你可以直接发起一个 PR 以修改相关的代码

**Comment by RPRX** [comment]
@porcupineyhairs 鉴于此漏洞的实际危害性几乎为零，我想我们可以先直接公开讨论它。

经过和 @yuhan6665 的讨论，相比于 HTTP 入站，我们更关心其它入站是否有类似的弱点，麻烦你查看一下。

即使有，我个人认为，这样的攻击在复杂的操作系统加公网传输的环境下几乎无法成功实践，但若修复，我们可以发一个 v1.8.2。

**Comment by RPRX** [comment]
> 即使有，我个人认为，这样的攻击在复杂的操作系统加公网传输的环境下几乎无法成功实践，但若修复，我们可以发一个 v1.8.2。

这里指的是其它入站，至于 HTTP 入站，它原本的设计目标见文档 https://xtls.github.io/config/inbounds/http.html
