### ISSUE TITLE
请问一下数据库或带端口的连接可以走xray吗？

### ISSUE THREAD

**Issue by tokaiyip** [XTLS/Xray-core#2039]
目前客户端是本机，服务端在服务器上，使用的是vless+reality，想实现本机连了服务器的xray后数据库连接也能流入到服务器走代理，但是在inbound里设置了对应的数据库ip和端口，但是流量流不进去，请问这个可以实现的吗？如果实现配置文件需怎么写？希望能尽快得到您的答复，谢谢！

**Comment by chika0801** [comment]
你要发下，你现在的客户端服务端配置。

**Comment by tokaiyip** [comment]
> 你要发下，你现在的客户端服务端配置。
我排查了一下，好像是本机的客户端时候就已经没进去，这个listen是要listen数据库的IP吗？还是需要改为0.0.0.0直接监听全局
  "inbounds" : [
    {
      "listen" : "127.0.0.1",
      "protocol" : "socks",
      "settings" : {
        "ip" : "127.0.0.1",
        "auth" : "noauth",
        "udp" : false
      },
      "tag" : "socksinbound",
      "port" : 1081
    },
    {
      "listen" : "127.0.0.1",
      "protocol" : "http",
      "settings" : {
        "timeout" : 0
      },
      "tag" : "httpinbound",
      "port" : 8001
    }
  ]

**Comment by tokaiyip** [comment]
> 你要发下，你现在的客户端服务端配置。
我排查了一下，好像是本机的客户端时候就已经没进去，这个listen是要listen数据库的IP吗？还是需要改为0.0.0.0直接监听全局
  "inbounds" : [
    {
      "listen" : "127.0.0.1",
      "protocol" : "socks",
      "settings" : {
        "ip" : "127.0.0.1",
        "auth" : "noauth",
        "udp" : false
      },
      "tag" : "socksinbound",
      "port" : 1081
    },
    {
      "listen" : "127.0.0.1",
      "protocol" : "http",
      "settings" : {
        "timeout" : 0
      },
      "tag" : "httpinbound",
      "port" : 8001
    }
  ]

**Comment by tokaiyip** [comment]
> 你要发下，你现在的客户端服务端配置。




我排查了一下，好像是本机的客户端时候就已经没进去，这个listen是要listen数据库的IP吗？还是需要改为0.0.0.0直接监听全局
"inbounds" : [
{
"listen" : "127.0.0.1",
"protocol" : "socks",
"settings" : {
"ip" : "127.0.0.1",
"auth" : "noauth",
"udp" : false
},
"tag" : "socksinbound",
"port" : 1081
},
{
"listen" : "127.0.0.1",
"protocol" : "http",
"settings" : {
"timeout" : 0
},
"tag" : "httpinbound",
"port" : 8001
}
]

**Comment by qist** [comment]
这个要你的使用连接数据库的工具支持代理才可以当然使用tun 就可以连接不需要你的数据库工具支持代理。

**Comment by RPRX** [comment]
可以
