### ISSUE TITLE
［提案］关于加密分享链接的初步提案

### ISSUE THREAD

**Issue by RainThings** [XTLS/Xray-core#204]
这里是初步整理的内容，可能并不完善，需要很多的建议。
这是对https://github.com/XTLS/Xray-core/issues/199 的更新与补充。

**Comment by RainThings** [comment]
![IMG_1611326408731](https://user-images.githubusercontent.com/61218971/105505104-84d88700-5d03-11eb-94b8-1c855be845f1.jpg)

**Comment by SekiBetu** [comment]
以上提案的内置部分如需实现，会经历以下几个步骤：
1、分享链接将会包含config.json的全部内容而不是目前的基础部分
2、使Xray-core支持读取分享链接

以上的提案外置部分可以简单概括为：加密一个文本

**Comment by NutterChen** [comment]
另外个人认为，还应当为订阅链接绑定许可的设备的IMEI, 网卡的MAC地址, 规定允许连接的IP地址段

连接时向节点主人发送 请求许可 

这样可以做到万无一失

**Comment by RainThings** [comment]
> 以上提案的内置部分如需实现，会经历以下几个步骤：
> 1、分享链接将会包含config.json的全部内容而不是目前的基础部分
> 2、使Xray-core支持读取分享链接
> 
> 以上的提案外置部分可以简单概括为：加密一个文本

但这十分影响性能，理应弃用。

**Comment by RainThings** [comment]
> 另外个人认为，还应当为订阅链接绑定许可的设备的IMEI, 网卡的MAC地址, 规定允许连接的IP地址段
> 
> 连接时向节点主人发送 请求许可
> 
> 这样可以做到万无一失

最小的信息收集，理应是最优的选择。

**Comment by AkinoKaede** [comment]
> 另外个人认为，还应当为订阅链接绑定许可的设备的IMEI, 网卡的MAC地址, 规定允许连接的IP地址段
> 
> 连接时向节点主人发送 请求许可
> 
> 这样可以做到万无一失

还建议添加绑定三要素，人脸识别技术，声纹鉴定技术。更可公安局线下核验。（大笑

**Comment by RainThings** [comment]
> > 另外个人认为，还应当为订阅链接绑定许可的设备的IMEI, 网卡的MAC地址, 规定允许连接的IP地址段
> > 连接时向节点主人发送 请求许可
> > 这样可以做到万无一失
> 
> 最小的信息收集，理应是最优的选择。

你是想更快的进铁窗

**Comment by MarksonHon** [comment]
我感觉内核做这事有点牛刀诛虎，不对路数。况且加密后的节点信息如何被客户端解密呢？使用密钥/公钥配对么？

**Comment by NutterChen** [comment]
![Бесполезная работа](https://s3.ax1x.com/2021/01/22/soswjK.jpg "шутка")

**Comment by RainThings** [comment]
> 我感觉内核做这事有点牛刀诛虎，不对路数。况且加密后的节点信息如何被客户端解密呢？使用密钥/公钥配对么？

这个事嘛，本来就没打算让core做

**Comment by jiuqi9997** [comment]
这提案被否决了

**Comment by RainThings** [comment]
尽力而为
