### ISSUE TITLE
1.8.1 客户端连接grpc连接不了

### ISSUE THREAD

**Issue by wuruiwm** [XTLS/Xray-core#2040]

**Comment by wuruiwm** [comment]
openwrt下passwall，x86环境，我手动下载二进制文件替换为1.8.0，就可以正常连接，再替换为1.8.1就不行
![image](https://user-images.githubusercontent.com/32637402/236621826-dadac452-8eff-43a2-8068-ec38617c7383.png)

**Comment by wuruiwm** [comment]
感谢解答，我用的是xrayr 0.9.0部署的   对应xray-core版本是1.7.5
所以可能是版本不对应的问题

**Comment by RPRX** [comment]
去掉 /

**Comment by wuruiwm** [comment]
去掉/果然可以了，1.7.5-1.8.1都可以正常连接 感谢r大
