### ISSUE TITLE
reality协议多数时候被部分网站拒绝访问

### ISSUE THREAD

**Issue by aheig** [XTLS/Xray-core#2045]
比如下面这个
https://www.amazon.com/gp/bestsellers/hpc/13213826011/ref=pd_zg_hrsr_hpc

**Comment by chika0801** [comment]
你要说你客户端用什么程序（环境）发客户端服务端配置才能分析。

**Comment by aheig** [comment]
客户端用的Openwrt，Xray内核版本1.8.1，国内外分流，
网站返回：Request was throttled. Please wait a moment and refresh the page

**Comment by chika0801** [comment]
客户端换如win上的v2rayn 安卓的ng，现象复现吗？

**Comment by aheig** [comment]
客户端用安卓nekobox，问题一样，win客户端暂时没做测试

**Comment by chika0801** [comment]
发服务端配置了

**Comment by aheig** [comment]
可能是阿里云的服务器被亚马逊限流，其他协议也会偶尔出现

**Comment by RPRX** [comment]
这一看就是服务器 IP 有问题，能说成是协议的锅，也是 6
