### ISSUE TITLE
带宽最多40Mbps，是被ISP限速吗？

### ISSUE THREAD

**Issue by HuengchI** [XTLS/Xray-core#2048]
vps是100M独占带宽，但是下载速度最多40Mbps，这种现象有人遇到过吗？之前有老哥提到过是运营商无差别限速？
使用别人的机场就能达到100Mbps（跑满我家的带宽）。想来机场用的技术不可能比reality先进，不知道它们怎么突破限制的？

**Comment by reF1nd** [comment]
@HuengchI VPS不还要看线路吗？运营商QoS只是一方面而已。

**Comment by RPRX** [comment]
？什么问题都往这里发

**Comment by RPRX** [comment]
To Anshi：

> ~~快进到劝群友换 vps~~

What about vps-blacklist？

**Comment by HuengchI** [comment]
> 这种issue不甩手一个关闭留着过年？^^

噗嗤
