### ISSUE TITLE
单独升级xray

### ISSUE THREAD

**Issue by aheig** [XTLS/Xray-core#205]
弱弱的问一句
       怎么单独升级openwrt的各种插件中的xray内核啊

**Comment by skiinder** [comment]
需要重新编译吧，我每次都是重新编译升级的

**Comment by rprx** [comment]
1. 下载对应的 Xray-linux-*.zip，解压出可执行文件 xray
2. FTP 连接 OpenWrt，替换 /usr/bin/xray
3. SSH 连接 OpenWrt，执行 `chmod +x /usr/bin/xray`
