### ISSUE TITLE
Heavy RAM usage while using WARP in outbound rules

### ISSUE THREAD

**Issue by arash88** [XTLS/Xray-core#2050]
8GB of RAM gets maxed out in a minute when I'm using Cloudflare WARP in outbound rules ( Xray-Core 1.8.1 ). My Config is as followed:

{
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    },
	{
        "tag":"warp",
        "protocol":"wireguard",
        "settings":{
            "secretKey":"",
            "address":[
                "172.16.0.2/32",
                ""
            ],
            "peers":[
                {
                    "publicKey":"",
                    "endpoint":"engage.cloudflareclient.com:2408"
                }
            ],
        "reserved":[0, 0, 0], 
        "mtu": 1280
        }
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "handshake": 10,
        "connIdle": 100,
        "uplinkOnly": 2,
        "downlinkOnly": 3,
        "statsUserUplink": true,
        "statsUserDownlink": true,
        "bufferSize": 10240
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      },
	  {
                "type":"field",
                "outboundTag": "warp",
                "domain":[
                    "geosite:google",
                    "geosite:netflix",
                    "geosite:spotify",
                    "geosite:nvidia",
                    "geosite:bytedance",
                    "domain:ip.gs"
                ]
            }
    ]
  },
  "stats": {}
}

**Comment by lostsoul6** [comment]
@arash88 Hello Sir , Were you able to find a solution for this ?

**Comment by arash88** [comment]
> @arash88 Hello Sir , Were you able to find a solution for this ?

Hi, no I have disabled it.
Hey @RPRX, Maybe you know how to fix this?

**Comment by dreamph666** [comment]
It seems to be solved in #2068.

**Comment by arash88** [comment]
> It seems to be solved in #2068.

It seems it's still the case even in Xray-core 1.8.1

**Comment by malikshi** [comment]
> > It seems to be solved in #2068.
> 
> It seems it's still the case even in Xray-core 1.8.1

did you try use binary from https://github.com/XTLS/Xray-core/actions/runs/4975120328 ?

**Comment by arash88** [comment]
> did you try use binary from https://github.com/XTLS/Xray-core/actions/runs/4975120328 ?

@malikshi @lostsoul6 
Thanks, it fixes the issue

**Comment by yuhan6665** [comment]
Solved
