### ISSUE TITLE
routing中的protocol是否支持匹配"quic"协议?

### ISSUE THREAD

**Issue by kckm** [XTLS/Xray-core#2057]
文档里是只写了http tls bittorrent。
而实际我测试写了quic在protocol，匹配blackhole。确实能看到某些连接被匹配到blackhole，但是更多的连接是没有被匹配到的。
这个结果就很怪，往往是第一条连接被匹配，之后的好几条都不行，而youtube会发起多次quic连接尝试，所以仍然不能阻止quic。

**Comment by xqzr** [comment]
#1885
