### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by ssmetall** [XTLS/Xray-core#2059]
deleted

**Comment by nursery01** [comment]
https://github.com/XTLS/Xray-core/discussions/2054#discussioncomment-5856405

**Comment by RPRX** [comment]
你们那边的 GFW 是地狱模式，所以，恕我直言，**以你们每发现一个能用的方式就奔走相告的习惯**，任何方式都活不长久。

是有方法可以破局，但若公开了，传播了，伊朗很快就会直接切断整个国际网络，最终你们连真 yahoo 都访问不了。

**Comment by nursery01** [comment]
我引用我之前的那句話

https://github.com/XTLS/Xray-core/issues/2017#issuecomment-1532647337

你剩餘的牌應該也是無法應對伊朗

**Comment by RPRX** [comment]
@nursery01 就算 ip 白名单，我照样出得去

**Comment by megasoheilsh** [comment]
> 

how to do ?

**Comment by nursery01** [comment]
@RPRX 喔我知道了，你的意思是即使是只剩下少量銀行IP能走，你也能翻出去，~~那你可能是中國體制內的人~~我先刪了這條吧

**Comment by megasoheilsh** [comment]
> 

Currently, if the ip does not match the white sni, it will be blocked

**Comment by megasoheilsh** [comment]
> 你们那边的 GFW 是地狱模式，所以，恕我直言，**以你们每发现一个能用的方式就奔走相告的习惯**，任何方式都活不长久。
> 
> 是有方法可以破局，但若公开了，传播了，伊朗很快就会直接切断整个国际网络，最终你们连真 yahoo 都访问不了。

Hello Mr. rprx, help us, the speed of reality is very low, how to connect base on ip whitelist ?  According to the investigations, the network does not whitelist based on SNI

**Comment by megasoheilsh** [comment]
> > > 你们那边的 GFW 是地狱模式，所以，恕我直言，**以你们每发现一个能用的方式就奔走相告的习惯**，任何方式都活不长久。
> > > 是有方法可以破局，但若公开了，传播了，伊朗很快就会直接切断整个国际网络，最终你们连真 yahoo 都访问不了。
> > 
> > 
> > Hello Mr. rprx, help us, the speed of reality is very low, how to connect base on ip whitelist ? According to the investigations, the network does not whitelist based on SNI anymore
> 
> Plz don't request for more here.The speed is more related to the network environment and hardware conditions. REALITY can help you access the outside but it can't improve network speed.


Mr. Kafka, your problem is that you are erasing the face of the problem. We Iranians know the difference between hardware problems and blocking by your firewall! So there is no need for your advice!

**Comment by RPRX** [comment]
**你们可以请求“通往那些白名单 IP 路径上的任何一个节点（企业/政府）”帮忙，让其识别 REALITY 并分流，这是第一类方式。**
[得益于 REALITY 的设计](https://t.me/projectXtls/74)，即使伊朗 GFW 拿到了客户端配置（公钥），它也无法用来验证某一条连接是否为 REALITY。
建议给每个人分配不同的 ShortID，若客户端配置泄露了，有助于揪出谁是内鬼，这便是 ShortID 存在的意义。

~~第二类方式是杀手锏，暂时不方便说出来。~~ 总之，我觉得会有人愿意帮你们分流的，~~希望你们别被全面断开国际互联网。~~

**Comment by RPRX** [comment]
只需生成一对公私钥，对于来自伊朗的流量，拿私钥验证一下是否为 REALITY，成本非常低。

**Comment by megasoheilsh** [comment]
> 只需生成一对公私钥，对于来自伊朗的 TLSv1.3 Client Hello，拿私钥验证一下是否为 REALITY 即可，成本非常低。

Isn't this key that we generate the same as private and public key?

**Comment by megasoheilsh** [comment]
> **你们可以请求“通往那些白名单 IP 路径上的任何一个节点（企业/政府）”帮忙，让其识别 REALITY 并分流，这是第一类方式。** [得益于 REALITY 的设计](https://t.me/projectXtls/74)，即使伊朗 GFW 拿到了客户端配置（公钥），它也无法用来验证某一条连接是否为 REALITY。 建议给每个人分配不同的 ShortID，若客户端配置泄露了，有助于揪出谁是内鬼，这便是 ShortID 存在的意义。
> 
> ~第二类方式是杀手锏，暂时不方便说出来。~ 总之，我觉得会有人愿意帮你们分流的，~希望你们别被全面断开国际互联网。~

Right now, we are using internal vps, but unfortunately these servers are also experiencing problems, we also assigned a ShortID for each person, but the problem was not solved, is there a way to spoof the IP?

**Comment by megasoheilsh** [comment]
Currently, no whitelist has been applied to sni and even porn domains are connected with reality and vmess http tcp. (full port sites are blocked)

**Comment by megasoheilsh** [comment]
> 看到你回复的 [#2054 (reply in thread)](https://github.com/XTLS/Xray-core/discussions/2054#discussioncomment-5872592)
> 
> ~是不是那个运营商发现 IP 白名单误杀率太高，所以改成了限速所有出境连接~

maybe , i'm in investigation

**Comment by RPRX** [comment]
我猜它的开发者（们）也在看这个 issue，~~别害羞，出来走两步聊聊天呗~~

**Comment by megasoheilsh** [comment]
> 我猜它的开发者（们）也在看这个 issue，~别害羞，出来走两步聊聊天呗~

Is there a solution to this problem?

**Comment by RPRX** [comment]
> Is there a solution to this problem?

我猜它是单连接限速，所以，你先试试多线程下载

**Comment by RPRX** [comment]
> > > Is there a solution to this problem?
> > 
> > 
> > 我猜它是单连接限速，所以，你先试试多线程下载
> 
> I tried it, unfortunately it didn't make a difference

~~那可能是单用户限速~~

**Comment by SaintShit** [comment]
> > Is there a solution to this problem?
> 
> 我猜它是单连接限速，所以，你先试试多线程下载

Yes it is, it seems that some IPs have limited uploads, like after early seconds, upstream gets severely reduced. and we can put the blame on REALITY, I've test NoTLS traffic and also real tls, they all are the same. the IP's limited.
I think this came from the fact that Iran gov don't give a fuck about the quality of the internet they sell to people, cuz currently you cannot even open some websites well too.

**Comment by alidxdydz** [comment]
> > > Is there a solution to this problem?
> > 
> > 我猜它是单连接限速，所以，你先试试多线程下载
> 
> Yes it is, it seems that some IPs have limited uploads, like after early seconds, upstream gets severely reduced. and we can't put the blame on REALITY, I've tested NoTLS traffic and also real tls, they all are the same. the IP's limited.
> I think this came from the fact that Iran gov don't give a fuck about the quality of the internet they sell to people, cuz currently you cannot even open some websites well too.

@RPRX 
I'm not a network guy but I've seen a network specialist comments on this matter. He says: first connection spees is low and they get the first bytes of connection and regex it so that they extract fingerprint out of it. If the regex was successful the spees increases and if not, whole connecion drops.

**Comment by lilcheti** [comment]
Ok so i created this telegram group https://t.me/howisuconnected to discuss about how we are connected on each isp

**Comment by OxJ4ck** [comment]
> This matter, it can be seen at the moment that even Iran's strictest ISP cannot afford the consequences of IP whitelisting
> 
> This is a good thing for us, ~which means that China's GFW will not implement IP whitelisting~

i have strange issue, i can use REALITY with yahoo sni in one ISP but it's not working in other ISP, when i changes the sni it's will be ok in other ISP too.

**Comment by lostsoul6** [comment]
@megasoheilsh
Also looking for that . Reality doesn't work anymore with our current config . Any new method is appreciated @RPRX

**Comment by megasoheilsh** [comment]
Unfortunately, v2ray has been detected by the government and I don't know if the problem is vless or vmess, but ssh tunnel, openvpn and mikrotik tunnel protocols are connected without problems and with great speed, and this problem will reach China soon, dear @rprx please  Think about v2ray because it will be complete block in Iran and china

**Comment by chika0801** [comment]
@megasoheilsh 

The v2ray name (usage rights) is now maintained by the v2fly community.

I would suggest that if you use the v2ray program with various protocols used in it, such as VMESS Trojan paired with, say, websocks tls, and encounter issues like being blocked. You can go to the v2fly community to give feedback. https://github.com/v2fly/v2ray-core/issues

Although the Xray community can usually post any feedback here, but the developer's energy is limited.

If you encounter problems using Xray's VLESS protocol, and Vision flow control, such as adding the REALITY protocol, you can continue to give us feedback here in the community.

This is a more efficient way to communicate.

**Comment by megasoheilsh** [comment]
> @megasoheilsh
> 
> The v2ray name (usage rights) is now maintained by the v2fly community.
> 
> I would suggest that if you use the v2ray program with various protocols used in it, such as VMESS Trojan paired with, say, websocks tls, and encounter issues like being blocked. You can go to the v2fly community to give feedback. https://github.com/v2fly/v2ray-core/issues
> 
> Although the Xray community can usually post any feedback here, but the developer's energy is limited.
> 
> If you encounter problems using Xray's VLESS protocol, and Vision flow control, such as adding the REALITY protocol, you can continue to give us feedback here in the community.
> 
> This is a more efficient way to communicate.

Okay, don't be too angry

**Comment by chika0801** [comment]
> Okay, don't be too angry

No anger, friend.

**Comment by megasoheilsh** [comment]
The results of the investigations:

1- Iran's Internet is entirely in the hands of Chinese engineers (gfw) (Iranians are not literate) and with the first demonstration in China, you will become like us.

2- They can monitor all vless, vmess, trojan, and shadowsocks protocols and block them if necessary (according to openvpn and cisco, mikortik and even ssh protocols) they can connect at the right speed without any problem

3- Four days ago, there was a 24-hour blackout on Iran's Internet, which no one had an explanation for, and after connecting the reality system and http header, it was blocked (SNI is no longer whitelisted, only IP is whitelisted).

If xraycore developers #rprx don't think about these problems, soon, less than 1 year, our access to the Internet will be cut off.

**Comment by lilcheti** [comment]
@megasoheilsh can u elaborate more on how to connect using openvpn, cisco or mikrotik?

**Comment by megasoheilsh** [comment]
> 

search on internet or youtube plz

**Comment by megasoheilsh** [comment]
> > > 
> > 
> > 
> > search on internet or youtube plz
> 
> Stop taking nonsense. Reality is working fine on all ISPs and your problem is finding a proper Dest and SNI. All of your mentiond protocols are also blocked and the reason they are still working is they are using Tunnel to connect two servers. You can do this with v2ray and there is lots of tutorial on the Internet. Just google it.

you Stop your bullshit idiot, I don't use Iran's server for openvpn, pptp,... and you know which village do you live in?  , because mci has blocked Reality in Tehran province, and I set sni to the amount of hair on your head and it didn't work

**Comment by SaintShit** [comment]
> > This matter, it can be seen at the moment that even Iran's strictest ISP cannot afford the consequences of IP whitelisting
> > This is a good thing for us, ~which means that China's GFW will not implement IP whitelisting~
> 
> i have strange issue, i can use REALITY with yahoo sni in one ISP but it's not working in other ISP, when i changes the sni it's will be ok in other ISP too.

I got involved in this too, and I concluded that MCI's blocking SNIs relative to the IP, like the thing previously happened to Cloudflare IPs that when your domain was filtered, it still worked with a series of IPs. while on filtered IPs, traffic was redirected to 10.10.34.36.

by the way, I'd appreciate it if you have any conclusion on this to tell

**Comment by alidxdydz** [comment]
> > > > 
> > > 
> > > 
> > > search on internet or youtube plz
> > 
> > Stop taking nonsense. Reality is working fine on all ISPs and your problem is finding a proper Dest and SNI. All of your mentiond protocols are also blocked and the reason they are still working is they are using Tunnel to connect two servers. You can do this with v2ray and there is lots of tutorial on the Internet. Just google it.
> 
> you Stop your bullshit idiot, I don't use Iran's server for openvpn, pptp,... and you know which village do you live in?  , because mci has blocked Reality in Tehran province, and I set sni to the amount of hair on your head and it didn't work

I live in Tehran village.

**Comment by megasoheilsh** [comment]
Tonight in Tehran, the ip white list was implemented on mobinnet and mci network, even without vpn, nothing works properly, even the speed test is zero.

**Comment by lostsoul6** [comment]
> Tonight in Tehran, the ip white list was implemented on mobinnet and mci network and a few datacenters , even without vpn, nothing works properly, even the speed test is zero.

I predict that the internet will be cut off in maximum 2 months and they would just give it to people like students , doctors and researchers . for regular people it will be North Korea .

**Comment by us254** [comment]
> **YOU CAN ASK FOR HELP FROM "ANY NODE (ENTERPRISE/GOVERNMENT) ON THE PATH TO THOSE WHITELISTED IPS" TO IDENTIFY REALITY AND OFFLOAD TRAFFIC, WHICH IS THE FIRST WAY. 

On one hand, you suggested that we can use reality with any node (enterprise/government) on the path to those whitelisted IPs to offload traffic as a way to improve connection and speed. However, elsewhere, you mentioned that using SS/VMess in the domestic segment of transit (VPS/datacenter=NODE (ENTERPRISE/GOVERNMENT)) is self-deception and not secure.

Based on your previous statement, I understand that only reality is safe to use in the domestic segment of transit when the traffic has to pass through the domestic public network.

**Comment by tomxiang1** [comment]
> 这件事，目前可以看出，连伊朗最严格的 ISP 都无法承担 IP 白名单的后果
> 
> 对我们来说是一件好事，~这意味着中国的 GFW 更不会实施 IP 白名单~

不要太乐观，以往的经验告诉我们，GFW是有很多策略用在不同的时期，比如和平时期的检查策略应该就不会用IP白名单，但是开会时期、战争时期、敏感时期等等，都不排除使用IP白名单，宁愿错杀一千不愿放过一个。

**Comment by free-the-internet** [comment]
What are the recent developments on this? @ssmetall 

@RPRX , do we have TLS in TLS detection problem on VLESS too using Vision?
@RPRX I read somewhere that there were an attack from the censor trying to target fake SNI by sending a server hello containing the certificate corresponding to the server name in client hello. "Do we have a mechanism/What is a good mechanism" to identify these packets as well as a suitable reaction?

**Comment by free-the-internet** [comment]
As this topic gets abandoned by others, I'm getting news that the IP matching SNI technique is imposed by Irancell in some areas, beginning from 17, 18 May.

**Comment by us254** [comment]
در مورد همراه اول 

برای بدست اوردن ip تمیز (whitelist)به این نتایج رسیدیم؛ 
شما باید از ip استفاده کنید که قبلا برای یک سرویسی غیر از vpn در ایران در حال استفاده باشه و یا مدتی در پنل آروان ثبت شده باشد(آروان خالی صدرصد نیست)
ما برای سرویس خودمون از خدمات v2b استفاده میکردیم
به همین دلیل یک سرور مخصوص پنل داشتیم، ip این سرور بخاطر این که پنل v2b بالا بوده (حدود ۳ ماه), ip داخل لیست سفید قرار گرفته و آپلود قابل قبولی با یاهو در همراه اول داشتیم.

متوجه نشدم چی می گه.😵‍💫

**Comment by us254** [comment]
About the Mci isp

We wanted to get an IP that is whitelisted, so we found out these things:
You need to use an IP that is already used for a non-vpn service in Iran or has been registered in Arvan's panel for a while.
We used v2b services for our service.
That's why we had a special server for the panel. The IP of this server is whitelisted because the v2b panel has been running for about 3 months. We had a good upload speed with Yahoo on the MCI

**Comment by us254** [comment]
Irancell isp employs only sni whitelist and it is compatible with Reality. However, The MCI ISP has implemented a whitelist of “IP and domain” that is exclusive for tcp protocol and

and the method of the bridge from the domestic VPs to the foreign one, operate smoothly.

**Comment by grdll** [comment]
> Mr. Kafka, you are erasing the base of the problem. We Iranians know the difference between hardware problems and blocking by your fu*ck GFW firewall! So there is no need for your advice!

**我们也是受害者**，**GFW就算中国不卖给伊朗**，**你们自己也会整个出来**，赚钱罢了，"**hardware problems**"如果包括伊朗**出国**用的**国际链路**使用的**线缆**及**设备**，那确实就跟"**hardware problems**"有很大关系，恕我直言你们国家出国常见就两条路，要么阿塞拜疆要么阿曼，**出国容量实在低的可怜**，而且伊朗国内平均固定宽带网速现在在Speedtest by Ookla上还是没有超过50Mbps，光纤普及率低的离谱，我不敢想象为了**优先保证政企能访问**为前提而对普通用户实施的QoS政策有多严格。

> If xraycore developers @RPRX don't think about these problems, soon, less than 1 year, we access to the Internet will be cut off.
> search on internet or youtube plz

那你们自己写吧，别一边骂中国人一边叫中国人帮你们写协议了，**人家搁这做慈善还要被骂**，叫你们给点证据比如说抓包啥的，你还叫别人上网自己去搜，**希望伊朗早日封锁国际互联网，降低低素质人口的网络输出**。

> 不要太乐观，以往的经验告诉我们，GFW是有很多策略用在不同的时期，比如和平时期的检查策略应该就不会用IP白名单，但是开会时期、战争时期、敏感时期等等，都不排除使用IP白名单，宁愿错杀一千不愿放过一个。

每次在网上看到别人说XX地方IP白名单然后我找个当地用同样ISP的朋友测试同样的协议都是一点问题都没有，同样下面的话送给咱们破口大骂的伊朗朋友，都被墙搞这么多次了，自备多点不同入站的中转机场/各种类型的IPLC/不同线路的VPS/使用多个不同的协议应该已经成为共识了才对啊？~~哦吼，好像伊朗没有机场也没有IPLC。~~

**Comment by epsilonzeio** [comment]
> GFW on your side is in hell mode, so, with all due respect, **with your habit of running around and telling people about every way you find one that works** , any way won't last long.
> 
> There is a way to break the situation, but if it is made public and spread, Iran will soon cut off the entire international network directly, and eventually you will not even be able to access the real Yahoo.

How can Iran cut off the international network? Do you mean shutting down all the routers and switches from outside or simply blocking some ASNs?
