### ISSUE TITLE
参数可否试用环境变量？

### ISSUE THREAD

**Issue by bibugo** [XTLS/Xray-core#206]
我看port参数有说明可以使用env:PORT格式使用环境变量，其他参数可不可以？例如id="env:UUID"

**Comment by rprx** [comment]
port 属于所有入站的公共参数，而 id 只有 VLESS 和 VMess 有

使用环境变量的意义是？

**Comment by bibugo** [comment]
没很大意义，就问一下有没有这功能。我自己弄了个dockerfile，uuid用环境变量输入，如果直接能用环境变量，就不需要运行时用sed修改config文件了。

**Comment by cuihao777** [comment]
> 没很大意义，就问一下有没有这功能。我自己弄了个dockerfile，uuid用环境变量输入，如果直接能用环境变量，就不需要运行时用sed修改config文件了。

这个完全可以用 bash 脚本读取环境变量来替换配置文件里的内容啊。
