### ISSUE TITLE
国内上网IP固定的被限制，vps IP可以更换，可有解决办法？

### ISSUE THREAD

**Issue by xiagw** [XTLS/Xray-core#2061]
1. 使用的Vision 配置， https://github.com/XTLS/Xray-examples/tree/main/VLESS-TCP-XTLS-Vision
1. 在国内其他地方都可以通过 vps 上网
1. 某个位置外网IP固定的被限制，
1. vps IP可以更换，

访问方式：xray client(固定IP） --> vps（浮动IP）

可有解决办法？

**Comment by WordsWorthLess** [comment]
如果你不强求使用xtls / reality的话，其实不需要修改境外VPS的IP地址，
通过WebSocket /gRPC等传输方式配合Cloudflare/CloudFront的 CDN，
有一些优选IP脚本，可以筛选出 网速快的IP地址，自己修改一下脚本，筛选出IP后自动更新Xray配置文件服务器端的IP地址并重启Xray客户端

甚至你觉得优选IP脚本太浪费时间的话，可以设置成随机在CDN的 CIDR里面选一个IP, 定时更新配置文件的节点地址，重启客户端

**Comment by zxbiao** [comment]
后者考虑通过国内机中转再出国？

**Comment by xiagw** [comment]
> 如果你不强求使用xtls / reality的话，其实不需要修改境外VPS的IP地址， 通过WebSocket /gRPC等传输方式配合Cloudflare/CloudFront的 CDN， 有一些优选IP脚本，可以筛选出 网速快的IP地址，自己修改一下脚本，筛选出IP后自动更新Xray配置文件服务器端的IP地址并重启Xray客户端
> 
> 甚至你觉得优选IP脚本太浪费时间的话，可以设置成随机在CDN的 CIDR里面选一个IP, 定时更新配置文件的节点地址，重启客户端

WebSocket 不是据说容易被q 吗？
还是走 xtls 比较好吧？

**Comment by RPRX** [comment]
标题：国内上网IP固定的被限制
正文：某个位置外网IP固定的被限制

~~要不要看看你在说什么~~
