### ISSUE TITLE
How to make latency lower ? 如何降低延迟

### ISSUE THREAD

**Issue by jiangying000** [XTLS/Xray-core#2065]
I feel VLESS-XTLS-uTLS-REALITY is slow to open website 
感觉 明显比原来的 shadowsocks 延迟高了（虽然稳定性提升很多，不会断了）

服务器，客户端 都是 1.8.1 内核

我的配置
![image](https://github.com/XTLS/Xray-core/assets/23182033/91996157-b72c-4f2c-b03a-0ad3bdc4243d)

**Comment by zxbiao** [comment]
请加钱买一个线路优化的VPS
CT->CN2-GIA（AS4809）单双程均可，双程完美。
CU->AS4837优化或AS9929单双程均可，双程完美。
CM->CMI（AS9808）单双程均可，双程完美。

**Comment by jiangying000** [comment]
现在就是同一台服务器，改了协议以后慢了很多，我希望最好能做到原来shadowsocks的速度。
原来基本上都在零点几秒，现在最多的时候要四五秒。

**Comment by wy580477** [comment]
> 现在就是同一台服务器，改了协议以后慢了很多，我希望最好能做到原来shadowsocks的速度。 原来基本上都在零点几秒，现在最多的时候要四五秒。

用 h2 / grpc 传输层

**Comment by zxbiao** [comment]
> 现在就是同一台服务器，改了协议以后慢了很多，我希望最好能做到原来shadowsocks的速度。 原来基本上都在零点几秒，现在最多的时候要四五秒。

那就用RTT-0的VLESS-H2-uTLS-REALITY
https://github.com/chika0801/Xray-examples/tree/main/VLESS-H2-uTLS-REALITY

**Comment by jiangying000** [comment]
@wy580477 @zxbiao 谢谢，开启 h2 以后，快了一大截，延迟明显低了，够我的要求了，留个 v2rayn 配置图后来人参考（流控要留空）
![d1087dae2872a588d2c3848e015c5be](https://github.com/XTLS/Xray-core/assets/23182033/db291179-bfbf-457c-8022-8c98261443a2)
