### ISSUE TITLE
Can different ids share the same client id and work normally?

### ISSUE THREAD

**Issue by cliusz** [XTLS/Xray-core#2067]
I just accidentally discovered a major strange phenomenon, and it can even reproduce.
The 23 characters and 17 characters in the client id can work normally with nodes with only one user id.
Looking forward to the official verification verification investigation. Thanks!

**Comment by chika0801** [comment]
Can you tell us more about the situation? Give specific examples.

**Comment by cliusz** [comment]
Thank for your care!

server config come from richhkaen example, and it's core version is 1.8.1
only one client id:
`"id": "abcde:13888888888",`
but in shadowrocket with "abcde:1388888888" and "abcee:1388888888:may12" both work normally.

**Comment by cliusz** [comment]
Another preblom: Frequent disconnections of a few minutes with Vision on all type client.

**Comment by chika0801** [comment]
> 谢谢你的关心！
> 
> 服务器配置来自richhkaen example，它的核心版本是1.8.1 只有一个客户端id： `"id": "abcde:13888888888",` 但在shadowrocket 中，“abcde:1388888888”和“abcee:1388888888:may12”都可以正常工作。

I still can't understand your question. Would it be okay if you post a specific configuration example?

**Comment by chika0801** [comment]
> server config come from richhkaen example, and it's core version is 1.8.1 only one client id: `"id": "abcde:13888888888",` but in shadowrocket with "abcde:1388888888" and "abcee:1388888888:may12" both work normally.

I still can't understand your question. Would it be okay if you post a specific configuration example?

**Comment by chika0801** [comment]
> Another preblom: Frequent disconnections of a few minutes with Vision on all type client.

https://github.com/XTLS/Xray-core/discussions/1772 

Are you in mainland China? If so, is it similar to the one in this discussion thread now?

**Comment by RPRX** [comment]
可以，但不建议
