### ISSUE TITLE
Feature request: TUN device

### ISSUE THREAD

**Issue by A5DkjGQUZx** [XTLS/Xray-core#2069]
Maybe Xray-core can be equipped with built-in TUN support similar to https://sing-box.sagernet.org/faq/#tun ?

Currently I am using https://github.com/heiher/hev-socks5-tunnel on my Linux machines but would be nice to be able to manage everything in one place with Xcore.

@RPRX

**Comment by FranzKafkaYu** [comment]
@A5DkjGQUZx you can refer to this:https://github.com/XTLS/Xray-core/actions/runs/4778132555 for now.

**Comment by chika0801** [comment]
参考 https://github.com/chika0801/Xray-install/tree/main/Tun

**Comment by RPRX** [comment]
已有该计划

**Comment by A5DkjGQUZx** [comment]
> Reference https://github.com/chika0801/Xray-install/tree/main/Tun

This is not the same thing.
Waiting for https://github.com/XTLS/Xray-core/actions/runs/4778132555 to be merged and released...
Thanks!

**Comment by adamgonglj** [comment]
> 已有该计划

太赞了，用了clash Linux下的tun模式，非常不好用，还是觉得xray好用。
Windows，xray + "sing-box tun" + vrayN不太好用，clash 在Windows下的tun好用

**Comment by adamgonglj** [comment]
吐槽一下sing-box，文档少得可怜，甚至还有错的。

**Comment by adamgonglj** [comment]
> @A5DkjGQUZx you can refer to this:https://github.com/XTLS/Xray-core/actions/runs/4778132555 for now.

人家说的是build-in tun，内建的tun

**Comment by chika0801** [comment]
> 吐槽一下sing-box，文档少得可怜，甚至还有错的，因为我找example configuration都报错。

https://github.com/chika0801/sing-box-examples

**Comment by adamgonglj** [comment]
> > 吐槽一下sing-box，文档少得可怜，甚至还有错的，因为我找example configuration都报错。
> 
> https://github.com/chika0801/sing-box-examples

相信我，这个我看过。

**Comment by chika0801** [comment]
> > > 吐槽一下sing-box，文档少得可怜，甚至还有错的，因为我找example configuration都报错。
> > 
> > 
> > https://github.com/chika0801/sing-box-examples
> 
> 相信我，这个我看过，我需要有dns,dns-out的，你的config_server.json里面是没有相关配置的，不全。 https://github.com/chika0801/sing-box-examples/blob/main/Tun/config_server.json 这个文档简单到根本无法读，我想在outbound里面使用dns out.

网上都是自学，你如果想问，要么发ISS等个有缘人，要么去如sing-box的tg群问。你在这这样描述我也帮不上。

> https://github.com/chika0801/sing-box-examples/blob/main/Tun/config_server.json
> 这个文档简单到根本无法读，我想在outbound里面使用dns out.

没人义务要写好详细，懂的都懂，不懂的也是靠自己试，我也是这样学过来的。
