### ISSUE TITLE
请求更换 Xray 路由规则文件加强版

### ISSUE THREAD

**Issue by fangxingweiai** [XTLS/Xray-core#207]
https://github.com/Loyalsoldier/v2ray-rules-dat

**Comment by rprx** [comment]
https://github.com/XTLS/Xray-rules-dat

**Comment by 70599** [comment]
> https://github.com/XTLS/Xray-rules-dat

这个看起来空的仓库是在建中吗？

**Comment by rprx** [comment]
> > https://github.com/XTLS/Xray-rules-dat
> 
> 这个看起来空的仓库是在建中吗？

是的，当它准备好时，Xray 会切换过去

**Comment by morooi** [comment]
撸了个使用 [Loyalsoldier/v2ray-rules-dat](https://github.com/Loyalsoldier/v2ray-rules-dat) 的 homebrew tap

用 Mac 的话可以试试（support Apple Silicon） => https://github.com/morooi/homebrew-xray
