### ISSUE TITLE
how to locate access.log and error.log in /var/log without permisson denied problem?

### ISSUE THREAD

**Issue by cliusz** [XTLS/Xray-core#2072]
Do not modify service user and group (let it is original nobody:nogroup).
Why xray create root:root customize log file such as /var/log/xray/acess8443.log and /var/log/xray/error8443.log?

**Comment by cliusz** [comment]
Failed to start: main: failed to create server > app/log: failed to initialize access logger > open /var/log/xray/access8443.log permission denied.  (code-exited, status=23)

**Comment by RPRX** [comment]
如果你先用 root 手动运行了 Xray，产生的日志文件就是属于 root 的
