### ISSUE TITLE
What is the relationship between 'servername' and 'Dest' in the reality configuration?

### ISSUE THREAD

**Issue by us254** [XTLS/Xray-core#2077]
"Can it be said that in a reality configuration , the `servername` parameter corresponds to the `SANs`listed in the `SSL certificate` for the `Dest` website?"

For example, if the 'Dest' website is set to `yahoo.com`, would 'servername' be a `list of SANs associated with the yahoo.com` domain as listed in its SSL certificate? 

The `SANs(servername)` listed for the `yahoo.com(Dest)` domain are:

tw.rd.yahoo.com
s.yimg.com
mbp.yimg.com
hk.rd.yahoo.com
fr-ca.rogers.yahoo.com
ddl.fp.yahoo.com
ca.rogers.yahoo.com
ca.my.yahoo.com
brb.yahoo.net
add.my.yahoo.com

**Comment by iamtheted** [comment]
> `dest` 填一个实际存在的网站，`serverNames` 基本上填什么都行，即使 `dest` 没有该域名，已经说过很多次了，请自行搜索

Hello there!
I hope you're all doing great!

Does GFW see the "Dest" we have set in the reality configuration or It only sees "SNI" ? 
Also, Can we set "Dest" an IP of the SNI or not?
I am a little confused, please clarify on this if It is possible.

I really appreciate it
