### ISSUE TITLE
REALITY project could have a singlly build go.mod or some introductions

### ISSUE THREAD

**Issue by nathnial** [XTLS/Xray-core#2080]
I just git clone the XTLS/REALITY program to my local PC. And I want build this reality project singlly & locally, but when I execute "go build" in this project, it's do nothing.

**Comment by us254** [comment]
https://github.com/chika0801/Xray-install/blob/main/compile_Xray-core.md

**Comment by chika0801** [comment]
楼上发的那个和楼主问的不是一个事吧

**Comment by nursery01** [comment]
單獨REALITY，沒有入口是無法編譯的

**Comment by RPRX** [comment]
XTLS/REALITY 是一个依赖库，无法单独编译
