### ISSUE TITLE
诸位屌大的, 我请教一下  address 填写域名或IP 有什么区别

### ISSUE THREAD

**Issue by wangz-code** [XTLS/Xray-core#2083]
比如伪装域名:  example.com   实际IP: 192.168.1.1

address: 为IP时会更容易被发现吗?  还是说都一样 

```
{
  "vnext": [
    {
      "address": "example.com",
      "port": 443,
      "users": [
        {
          "id": "5783a3e7-e373-51cd-8642-c83782b807c5",
          "encryption": "none",
          "flow": "xtls-rprx-vision",
          "level": 0
        }
      ]
    }
  ]
}
```

**Comment by chaoge1x** [comment]
address填写域名或者IP都一样

**Comment by chika0801** [comment]
没区别。

出站时 你地址填IP SNI填你VPS上SSL证书中包含的域名，可以一份证书你在N个VPS上使用，你并不需要在域名网站上设置域名指向哪个VPS的IP，方便你自己测试。

**Comment by RPRX** [comment]
Address 填域名会被解析为 IP，且 SNI 会被设为该域名，除非你另填了 serverName

**Comment by wangz-code** [comment]
谢谢各位!   我是在用国内vps 转发到国外vps 的时候遇到的  nginx 配置不能填写域名只能用用IP+端口

我配置另外设置了 带ssl 证书的 serverName
