### ISSUE TITLE
Reality did not work properly since last week

### ISSUE THREAD

**Issue by williamswu2000** [XTLS/Xray-core#2084]
Since last Tuesday, all my VPSs that were deployed Reality have been blocked. Even I rebooted the router or modem, the connection was stopped by GFW automatically in 1-2 minutes. it seems GFW can accurately detect Reality protocol now.

**Comment by yoohooyoo** [comment]
> Since last Tuesday, all my VPSs that were deployed Reality have been blocked. Even I rebooted the router or modem, the connection was stopped by GFW automatically in 1-2 minutes. it seems GFW can accurately detect Reality protocol now.
Perhaps providing more information would allow people to help you better.
For example 
1. Your current location?(country)
2. Your configuration information after desensitization? 
3. Your phenomena and logs before and after this condition?

**Comment by iwoow** [comment]
https://github.com/XTLS/Xray-examples/tree/main/VLESS-TCP-XTLS-Vision

**Comment by RPRX** [comment]
未提供有效信息，请在 https://github.com/XTLS/Xray-core/issues/2059 继续讨论
