### ISSUE TITLE
一个新项目？（被打

### ISSUE THREAD

**Issue by Fhokud** [XTLS/Xray-core#209]
xTLS可否增加类似openwrt-v2ray的项目，方便路由器用户
https://github.com/kuoruan/openwrt-v2ray

**Comment by AkinoKaede** [comment]
我想 @kuoruan 说的很明确，你可以开一个分支…

**Comment by soffchen** [comment]
Hello World 和 Passwall 现在都支持 xray 的

**Comment by 70599** [comment]
> Hello World 和 Passwall 现在都支持 xray 的

这两个都是ip转发之类配合传统无路由分流的协议（ss之类）的懒人包。
v2ray和xray有完整的路由分流特性，但是Hello World和Passwall为了兼容最多种类的协议，只是把v2ray的outbound当成ss在跑而已。
ssrp改名Hello World后几乎没用过，不多做评论。
Passwall运行xray时tcp一个进程、udp一个进程、运行dns over https的话还要再跑两个进程。
这么多进程只负责处理转发过来的流量，分流、转发还需要额外的chinadns、ipset等等，它们又要各自加载各种黑白名单。

没有做过详细测试，我不是想说这样性能差、速度慢，但是有xray这样全功能的程序，还这么搞，至少逻辑上很不优雅。

楼主应该就是想要一个可以图形化界面配置xray复杂功能，最大化利用xray的各种特性，优雅运行xray的项目。

但是现实是@kuoran貌似没有兴趣适配xray，能有精力用爱发电的人也有限。
所以基本上两个选择：

1. 用懒人包（Hello World和Passwall）能用就行，不要在意优雅不优雅
2. 自己爬各种教程优雅运行xray，繁琐一些

**Comment by Fhokud** [comment]
可以仅仅提供打包好的.ipk（xray版）文件吗

**Comment by kuoruan** [comment]
路由器上可以根据自己的 CPU 架构，从 https://github.com/XTLS/Xray-core/releases 下载对应的二进制文件上传到路由器即可。

编一个 ipk 倒是很简单，主要是需要配套的 `luci-app-xray`，这个就比较麻烦了

不知道作者有没有兴趣在 `Project X` 这个组织中开一个 xray-openwrt？@rprx

**Comment by ouyo** [comment]
@kuoruan 这是要付诸行动了嘛

**Comment by badO1a5A90** [comment]
我的想法是Project X 现在(或许一直都是)应该专心在core及core直接相关的内容. 周边生态需要靠其他大佬们支持.
一来专精方向不同,更专精的人肯定可以做的更好.
二来Project X 现在精力有限,需要专注对付core本身.

**Comment by AkinoKaede** [comment]
> 路由器上可以根据自己的 CPU 架构，从 https://github.com/XTLS/Xray-core/releases 下载对应的二进制文件上传到路由器即可。
> 
> 编一个 ipk 倒是很简单，主要是需要配套的 `luci-app-xray`，这个就比较麻烦了
> 
> 不知道作者有没有兴趣在 `Project X` 这个组织中开一个 xray-openwrt？@rprx

似乎是没有放在组织内的必要性的…就比如 Arch Linux 的 PKGBUILD 我也是放在我自己的仓库里的…

**Comment by rprx** [comment]
@kuoruan 

其实图形界面上有一个 [luci-app-xray](https://github.com/yichya/luci-app-xray) @yichya ，不过目前我不了解这方面的具体情况

`Xray-openwrt` 或 `openwrt-xray` 放哪里应该都可以（而且 openwrt 各大插件是自己编译的信仰加成版，不会下载这个。。。

---

Xray 一直在把相关项目列入 core 的 README.md，这个列表是不断扩展的，随时欢迎加入

这个理念是 Xray 不需要有每个仓库/项目的控制权（时间上也管理不过来），而是交给更专业的人做，放到自己的账号下更有成就感

**Comment by soffchen** [comment]
其实，xray 自己内置一个类似于 clash dashboard 的东东才是王道。

**Comment by SekiBetu** [comment]
> 其实，xray 自己内置一个类似于 clash dashboard 的东东才是王道。

把网页集成在二进制运行文件里，你在开什么国际玩笑

**Comment by yichya** [comment]
> @kuoruan
> 
> 其实图形界面上有一个 [luci-app-xray](https://github.com/yichya/luci-app-xray) @yichya ，不过目前我不了解这方面的具体情况
> 
> `Xray-openwrt` 或 `openwrt-xray` 放哪里应该都可以（而且 openwrt 各大插件是自己编译的信仰加成版，不会下载这个。。。
> 
> Xray 一直在把相关项目列入 core 的 README.md，这个列表是不断扩展的，随时欢迎加入
> 
> 这个理念是 Xray 不需要有每个仓库/项目的控制权（时间上也管理不过来），而是交给更专业的人做，放到自己的账号下更有成就感

[luci-app-xray](https://github.com/yichya/luci-app-xray) 这个小东西的初衷确实是像上面 @70599 说的那样，尽可能充分利用 xray 已有的功能（http / socks / tproxy 入站，dns 服务器，很全面的协议支持，甚至包括真的用来当 https 服务器反代一些服务）的同时，保持尽可能的简洁。

目前受限于个人精力这个项目暂时还只是自用性质（主要是确实比较忙，很难有时间适配各个不同版本的 openwrt 以及大家各异的需求），当然也十分欢迎大家尝试。

**Comment by rprx** [comment]
@yichya 建一个 `openwrt-xray` 仓库来 release ipk？

**Comment by yichya** [comment]
> @yichya 建一个 `openwrt-xray` 仓库来 release ipk？

我找时间照着 https://github.com/kuoruan/openwrt-v2ray 搞一个。

**Comment by yichya** [comment]
> > @yichya 建一个 `openwrt-xray` 仓库来 release ipk？
> 
> 我找时间照着 https://github.com/kuoruan/openwrt-v2ray 搞一个。

[yichya/openwrt-xray](https://github.com/yichya/openwrt-xray) 

暂时只放了 xray 和个人比较习惯的 [Loyalsoldier/v2ray-rules-dat](https://github.com/Loyalsoldier/v2ray-rules-dat)，之后考虑一下是否加上一个很简单的 init.d 以及一些自动追新版本之类的 actions

**Comment by rprx** [comment]
@yichya 

缺编译好的 ipk，这个是主要需求。。。

规则之后可以换成 [Xray-rules-dat](https://github.com/XTLS/Xray-rules-dat)

**Comment by yichya** [comment]
> @yichya
> 
> 缺编译好的 ipk，这个是主要需求。。。
> 
> 规则之后可以换成 [Xray-rules-dat](https://github.com/XTLS/Xray-rules-dat)

在配 actions 了。。。

**Comment by yichya** [comment]
> > @yichya
> 
> > 
> 
> > 缺编译好的 ipk，这个是主要需求。。。
> 
> > 
> 
> > 规则之后可以换成 [Xray-rules-dat](https://github.com/XTLS/Xray-rules-dat)
> 
> 
> 
> 在配 actions 了。。。

https://github.com/yichya/openwrt-xray/releases/tag/v1.2.3

**Comment by rprx** [comment]
@yichya ok 了，下个版本前会把两个仓库都加入 README.md

**Comment by rprx** [comment]
@yichya https://github.com/XTLS/Xray-core/commit/59c7c4897c39f7d5b2a4132a08270687f813ab49

**Comment by sinoll** [comment]
> Hello World 和 Passwall 现在都支持 xray 的

这两个我都试用了。lucai-app-xray3.6 怎么配置都 不通。 passwall 还行 大部分能通。

这种预定义模板的就是这么拉跨。我正在学习文档，争取像在台式机上配置一样，每一个双引号和逗号都是我自己敲进去的，明确知道它在这里起什么作用。
