### ISSUE TITLE
主路由做透明代理,指定某台设备通过TPROXY,访问国内特别慢

### ISSUE THREAD

**Issue by lionkingc** [XTLS/Xray-core#2094]
主路由做透明代理, 已实现全部设备无感上网,但有些设备没必要经过转发,例如风扇,电饭煲之类的...
目标:  指定的设备通过XRAY, 其他设备不经过XRAY走直连.
原: iptables -t mangle -A XRAY -p udp -j TPROXY --on-ip 127.0.0.1 --on-port 12345 --tproxy-mark 1
改: 增加了-s 192.168.0.188

经过以上设置后,其他设备能正常上网,指定的IP 188这台已能通过XRAY上外网, 
但是上内网特别慢, 上百度加载图片都要好久.  输出显示正常[all-in -> direct]
有没大佬知道要怎么改? 谢谢.

完整配置如下:
------------------------------------------------------------------------------------
```
ip rule add fwmark 1 table 100
ip route add local 0.0.0.0/0 dev lo table 100
iptables -t mangle -N XRAY
iptables -t mangle -A XRAY -d 127.0.0.1/32 -j RETURN
iptables -t mangle -A XRAY -d 127.0.1.1/32 -j RETURN
iptables -t mangle -A XRAY -d 172.16.0.0/12 -j RETURN
iptables -t mangle -A XRAY -d 224.0.0.0/4 -j RETURN
iptables -t mangle -A XRAY -d 169.254.0.0/16 -j RETURN
iptables -t mangle -A XRAY -d 255.255.255.255/32 -j RETURN
iptables -t mangle -A XRAY -d 192.168.0.0/16 -p tcp -j RETURN
iptables -t mangle -A XRAY -d 192.168.0.0/16 -p udp ! --dport 53 -j RETURN
iptables -t mangle -A XRAY -j RETURN -m mark --mark 0xff
iptables -t mangle -A XRAY -s 192.168.0.188 -p udp -j TPROXY --on-ip 127.0.0.1 --on-port 12345 --tproxy-mark 1
iptables -t mangle -A XRAY -s 192.168.0.188 -p tcp -j TPROXY --on-ip 127.0.0.1 --on-port 12345 --tproxy-mark 1
iptables -t mangle -A PREROUTING -j XRAY

iptables -t mangle -N XRAY_MASK
iptables -t mangle -A XRAY_MASK -d 127.0.0.1/32 -j RETURN
iptables -t mangle -A XRAY_MASK -d 127.0.1.1/32 -j RETURN
iptables -t mangle -A XRAY_MASK -d 172.16.0.0/12 -j RETURN
iptables -t mangle -A XRAY_MASK -d 224.0.0.0/4 -j RETURN
iptables -t mangle -A XRAY_MASK -d 169.254.0.0/16 -j RETURN
iptables -t mangle -A XRAY_MASK -d 255.255.255.255/32 -j RETURN
iptables -t mangle -A XRAY_MASK -d 192.168.0.0/16 -p tcp -j RETURN
iptables -t mangle -A XRAY_MASK -d 192.168.0.0/16 -p udp ! --dport 53 -j RETURN
iptables -t mangle -A XRAY_MASK -j RETURN -m mark --mark 0xff
iptables -t mangle -A XRAY_MASK -p udp -j MARK --set-mark 1
iptables -t mangle -A XRAY_MASK -p tcp -j MARK --set-mark 1
iptables -t mangle -A OUTPUT -j XRAY_MASK

iptables -t mangle -N DIVERT
iptables -t mangle -A DIVERT -j MARK --set-mark 1
iptables -t mangle -A DIVERT -j ACCEPT
iptables -t mangle -I PREROUTING -p tcp -m socket -j DIVERT
```

**Comment by WordsWorthLess** [comment]
```
iptables -t mangle -A XRAY -d 192.168.0.0/16 -p udp ! --dport 53 -j RETURN
iptables -t mangle -A XRAY -s 192.168.0.188 -p tcp -j TPROXY --on-ip 127.0.0.1 --on-port 12345 --tproxy-mark 1
```
你把192.168.0.188的DNS请求发往透明代理处理了
不清楚你的XRAY是怎么处理dns的，最好发一下配置文件
如果用外国的DNS来解析baidu的域名，那可能解析到的ip未必是国内的

**Comment by azzvx** [comment]
你的`freedom`出站有标记`SO_MARK`为`0xff`么？
```
{
      "tag": "direct",
      "protocol": "freedom",
      "streamSettings": { "sockopt":{"mark":255} }
},
```
你代理了DNS查询，不做标记那么会出现DNS回环导致DNS查询速度极慢。

**Comment by lionkingc** [comment]
> ```
> iptables -t mangle -A XRAY -d 192.168.0.0/16 -p udp ! --dport 53 -j RETURN
> iptables -t mangle -A XRAY -s 192.168.0.188 -p tcp -j TPROXY --on-ip 127.0.0.1 --on-port 12345 --tproxy-mark 1
> ```
> 
> 你把192.168.0.188的DNS请求发往透明代理处理了 不清楚你的XRAY是怎么处理dns的，最好发一下配置文件 如果用外国的DNS来解析baidu的域名，那可能解析到的ip未必是国内的 可以试一下在xray的配置文件添加以下dns配置，看看有没有改善
> 
> ```
> "dns": {
> 		"servers": [
> 			{
> 				"address": "8.8.8.8",
> 				"domains": [ "geosite:geolocation-!cn" ],
> 				"skipFallback": true
> 			},
> 			{
> 				"address": "114.114.114.114",
> 				"domains": [ "geosite:cn" ],
> 				"expectIPs": [ "geoip:cn" ],
> 			}
> 		],
> }
> ```

谢谢回复. 之前没加-s 192.168.0.188 这句话时, 即内网全部设备都由xray来处理DNS和流量走向时, 国内国外都正常, 速度也都挺快. 加了这句后, 其他设备只能上国内, 这台188的主机可以同时国内外, 但是国内变的特别慢. 

完整配置附下文.

**Comment by lionkingc** [comment]
> 

应该是有的, 我附上完整配置

--------------------------------------------
{
  "log": {
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "all-in",
      "port": 12345,
      "protocol": "dokodemo-door",
      "settings": {
        "network": "tcp,udp",
        "followRedirect": true
      },
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      },
      "streamSettings": {
        "sockopt": {
          "tproxy": "tproxy","mark":255
        }
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vless",
      "settings": {
        "vnext": [{
          "port": 443,
          "users": [{
            "flow": "xtls-rprx-vision",
            "encryption": "none",
            "id": "xxxxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxx",
            "level": 0
          }],
          "address": "xx.xx.xx.xx"
        }]
      },
      "streamSettings": {
        "security": "reality",
        "network": "tcp",
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        },
        "sockopt": {
          "mark": 255
        },
        "realitySettings": {
          "publicKey": "xxxxxxxxxxxxxxxxxx",
          "spiderX": "\/",
          "serverName": "trip.com",
          "shortId": "1234",
          "fingerprint": "chrome"
        }
      },
      "mux": {
        "enabled": false
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "AsIs"
      },
      "streamSettings": {
        "sockopt": {
          "mark": 255
        }
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    },
    {
      "tag": "dns-out",
      "protocol": "dns",
      "proxySettings": {
        "tag": "proxy"
      },
      "streamSettings": {
        "sockopt": {
          "mark": 255
        }
      }
    }
  ],
  "dns": {
    "queryStrategy": "UseIP",
    "servers": [
      "https://1.1.1.1/dns-query",
      "https://doh.dns.sb/dns-query",
      {
        "address": "119.29.29.29",
        "port": 53,
        "domains": ["geosite:cn"],
        "expectIPs": ["geoip:cn"]
      },
      {
        "address": "223.6.6.6",
        "port": 53,
        "domains": ["geosite:cn"]
      }
    ]
  },
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "inboundTag": ["all-in"],
        "port": 53,
        "network": "tcp,udp",
        "outboundTag": "dns-out"
      },
      {
        "type": "field",
        "inboundTag": ["all-in"],
        "port": 123,
        "network": "udp",
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "domain": ["geosite:cn", "geosite:apple-cn", "domain:msftconnecttest.com", "domain:msftncsi.com",  "domain:router.asus.com"],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "ip": ["geoip:private", "geoip:cn", "223.6.6.6", "119.29.29.29"],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "protocol": ["bittorrent"],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "domain": ["geosite:geolocation-!cn"],
        "outboundTag": "proxy"
      },
      {
        "type": "field",
        "ip": ["1.1.1.1", "8.8.8.8"],
        "outboundTag": "proxy"
      }
    ]
  }
}


-------------------------------------------

**Comment by yyiu** [comment]
"https://1.1.1.1/dns-query",
      "https://doh.dns.sb/dns-query",

这两个放下面去

**Comment by azzvx** [comment]
感觉是路由器的本机的DNS查询重路由后没有得到妥善处理导致的，你加`-s 192.168.0.188`之前Xray在处理，加了之后就不知道了。
你可以添加一个dokodemo-door然后路由到direct，然后把所有的连接再tproxy到这个dokodemo-door。
我一般会在Xray里面配置3个dokodemo-door，一个强制直连，一个强制代理，一个走路由。

**Comment by lionkingc** [comment]
> 感觉是路由器的本机的DNS查询重路由后没有得到妥善处理导致的，你加`-s 192.168.0.188`之前Xray在处理，加了之后就不知道了。 你可以添加一个dokodemo-door然后路由到direct，然后把所有的连接再tproxy到这个dokodemo-door。 我一般会在Xray里面配置3个dokodemo-door，一个强制直连，一个强制代理，一个走路由。

好的谢谢, 尝试改好了3个dokodemo-door,  iptables那边也是这样写吗?
'''
iptables -t mangle -A XRAY -s 192.168.0.188 -p tcp -j TPROXY --on-ip 127.0.0.1 --on-port 12345 --tproxy-mark 1
iptables -t mangle -A XRAY -s 192.168.0.111 -p tcp -j TPROXY --on-ip 127.0.0.1 --on-port 1111 --tproxy-mark 1
iptables -t mangle -A XRAY -s 192.168.0.222 -p tcp -j TPROXY --on-ip 127.0.0.1 --on-port 2222 --tproxy-mark 1
'''
