### ISSUE TITLE
采用nginx前置，grpc模式下，useragent存在问题

### ISSUE THREAD

**Issue by HSXX** [XTLS/Xray-core#2095]
客户端服务端均为1.8.1
在客户端设置"user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0",
在服务端nginx日志看到在客户端设置的useragent后多加了grpc-go/1.54.0，日志中为"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0 grpc-go/1.54.0"

**Comment by Fangliding** [comment]
grpc-go的特性
