### ISSUE TITLE
Mux 功能的问题？

### ISSUE THREAD

**Issue by tomxiang1** [XTLS/Xray-core#2097]
"mux": {
		"enabled": true,
		"concurrency": 1024,
		"xudpConcurrency": 1024
	   }
outbounds为vless+tls+tcp时配置mux，已经把concurrency加到1024，但实际使用中mux主连接没有达到1024个子连接就又会创建新的主连接，请教大佬们，创建新的主连接除了子连接达到1024后，还有什么其他条件会触发创建新的主连接？
第二个问题：如果想要保持主连接长期有效需要怎么配置呢？

**Comment by tomxiang1** [comment]
费劲的分析了源码，原来是Mux的实现有问题
![image](https://github.com/XTLS/Xray-core/assets/45867336/fec6911a-ed38-4e0a-a2a8-c1c991f7f285)
![image](https://github.com/XTLS/Xray-core/assets/45867336/0cb7fe71-0fd8-4e4c-a0e6-cdd1f8c1626c)
问题就出在count上，count只简单的做了加加运算并且还用来做子连接的ID，并且MaxConnection被写死成了128，这样一来不管你并发concurrency配置成什么，只要count++到了128就要重新创建新的主连接。找到问题就可以下手魔改了。
![image](https://github.com/XTLS/Xray-core/assets/45867336/079cd7cd-29a5-4b3d-9009-abaa53ac2d88)
ID是两个字节也就是65535以内都可以
![image](https://github.com/XTLS/Xray-core/assets/45867336/dad8673c-a44c-4546-9c90-1ff9d8935d69)
屏蔽子连接个数限制，count只做了++没做--所以这个判断没意义。
![image](https://github.com/XTLS/Xray-core/assets/45867336/f5ff0a61-404f-434c-aa51-1660803939f7)
![image](https://github.com/XTLS/Xray-core/assets/45867336/bb7e6df6-f7a8-4799-a797-0b5a87899b7a)
for true {
		if m.count >= 65534 {
	    		m.count=0
		}
		m.count++
        	se, found := m.sessions[m.count]
		if found == false || se == nil {
		    break
		}
	}
分别在Allocate方法和Add方法中增加，count现在单纯是用来做子连接ID了。65535远远大于1024，应该不会有找不到可以ID的情况，所以应该不会死循环。

**Comment by tomxiang1** [comment]
CDN + vless + tls + Mux(修改版) + Balancer  或者 CDN + vless + tls + grpc +  Balancer  效果一样。丝滑，延迟低。
不走CDN推荐 vless + reality + h2 + Balancer  丝滑，丝滑，还是丝滑，延迟最低。
Balancer  是被严重低估的功能，h2、grpc、Mux，都是单连接复用，延迟低，访问丝滑。
在单个vps上多开几个这种单连接复用通道用Balancer去负载均衡后非常奈斯。
建议带宽100Mbps左右的vps最好控制在2个通道连接。vps带宽大的可以增加通道连接，但好最大控制在5个左右。

**Comment by RPRX** [comment]
v1.9.0 会继续改 Mux，不过在此之前计划发个 v1.8.2

**Comment by Smallthing** [comment]
> CDN + vless + tls + Mux(修改版) + Balancer 或者 CDN + vless + tls + grpc + Balancer 效果一样。丝滑，延迟低。 不走CDN推荐 vless + reality + h2 + Balancer 丝滑，丝滑，还是丝滑，延迟最低。 Balancer 是被严重低估的功能，h2、grpc、Mux，都是单连接复用，延迟低，访问丝滑。 在单个vps上多开几个这种单连接复用通道用Balancer去负载均衡后非常奈斯。 建议带宽100Mbps左右的vps最好控制在2个通道连接。vps带宽大的可以增加通道连接，但好最大控制在5个左右。

意思是不同的shortid做负载均衡？

**Comment by tomxiang1** [comment]
> 意思是不同的shortid做负载均衡？

可以不需要，只要是outbounds中的对象即可。

**Comment by tomxiang1** [comment]
> v1.9.0 会继续改 Mux，不过在此之前计划发个 v1.8.2

非常奈斯，期待你的修改。

**Comment by Smallthing** [comment]
> > 意思是不同的shortid做负载均衡？
> 
> 可以不需要，只要是outbounds中的对象即可。

设置好了 效果拔群 希望有一天不需要h2也可以0rtt 那就爽了

**Comment by SuperNG6** [comment]
> > 意思是不同的shortid做负载均衡？
> 
> 可以不需要，只要是outbounds中的对象即可。

可否给一个你的完整的带Balancer的配置文件，我最近也在研究

**Comment by tomxiang1** [comment]
> > > 意思是不同的shortid做负载均衡？
> > 
> > 
> > 可以不需要，只要是outbounds中的对象即可。
> 
> 可否给一个你的完整的带Balancer的配置文件，我最近也在研究 据我所知，目前 xray 的 Balancer 没有健康检查，grpc和h2容易断流，效果是不如clash端负载均衡的。 #1751

 {
  "log": {
     "loglevel": "none"
  },
  "inbounds": [{
      "listen": "0.0.0.0",
      "port": 1080,
      "protocol": "socks",
      "tag": "socks1080_in",
      "settings": {
          "auth": "noauth",
          "udp": true
           },
       "sniffing": {
             "enabled": true,
             "destOverride": ["http","tls"]
           }
      },      
      {
        "listen": "0.0.0.0",
        "port": 1081,
        "protocol": "http",
        "tag": "socks1081_in",
         "sniffing": {
             "enabled": true,
             "destOverride": ["http","tls"]
             }
       }
    ],

  "outbounds": [
        {
            "tag": "vlessrea1-out",
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                      "address": "XXX.XXX.XXX.XXX",
                         "port": 443,
                         "users": [
                            {
                                "id": "XXXXXXXXXXXX",
                                "flow": "", 
                                "encryption": "none"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "h2",                
                "security": "reality",
                "realitySettings": {
                    "show": false, 
                    "fingerprint": "chrome", 
                    "serverName": "XXXXXXXXXXXX", 
                    "publicKey": "XXXXXXXXXXXX", 
                    "shortId": "",
                    "spiderX": "/"
                }
            }
        },
         {
            "tag": "vlessrea2-out",
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                      "address": "XXX.XXX.XXX.XXX",
                         "port": 443,
                         "users": [
                            {
                                "id": "XXXXXXXXXXXX",
                                "flow": "", 
                                "encryption": "none"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "h2",                
                "security": "reality",
                "realitySettings": {
                    "show": false, 
                    "fingerprint": "chrome", 
                    "serverName": "XXXXXXXXXXXX", 
                    "publicKey": "XXXXXXXXXXXX", 
                    "shortId": "",
                    "spiderX": "/"
                }
            }
        }
    ],
    "routing": {        
        "balancers": [
            {
             "tag": "vlessrea-out-balancer",
             "selector": ["vlessrea1-out","vlessrea2-out"]
            }
         ],       
        "rules": [         
         {
	   "type": "field",
	   "domain": ["geosite:private","geosite:cn"],
	   "outboundTag": "direct-out"
	 },
         {
           "type": "field",
           "protocol": ["bittorrent"],
           "outboundTag": "direct-out"
         },
	 {
	   "type": "field",	 
	   "ip": ["geoip:private","geoip:cn"],
           "outboundTag": "direct-out"
	 },
         {
           "type": "field",
           "inboundTag": ["socks1080_in","http1081_in"],
           "balancerTag": "vlessrea-out-balancer"
         }
       ]
    }
}

**Comment by SuperNG6** [comment]
> > > > 意思是不同的shortid做负载均衡？
> > > 
> > > 
> > > 可以不需要，只要是outbounds中的对象即可。
> > 
> > 
> > 可否给一个你的完整的带Balancer的配置文件，我最近也在研究 据我所知，目前 xray 的 Balancer 没有健康检查，grpc和h2容易断流，效果是不如clash端负载均衡的。 #1751
> 
> { "log": { "loglevel": "none" }, "inbounds": [{ "listen": "0.0.0.0", "port": 1080, "protocol": "socks", "tag": "socks1080_in", "settings": { "auth": "noauth", "udp": true }, "sniffing": { "enabled": true, "destOverride": ["http","tls"] } }, { "listen": "0.0.0.0", "port": 1081, "protocol": "http", "tag": "socks1081_in", "sniffing": { "enabled": true, "destOverride": ["http","tls"] } } ],
> 
> "outbounds": [ { "tag": "vlessrea1-out", "protocol": "vless", "settings": { "vnext": [ { "address": "XXX.XXX.XXX.XXX", "port": 443, "users": [ { "id": "XXXXXXXXXXXX", "flow": "", "encryption": "none" } ] } ] }, "streamSettings": { "network": "h2", "security": "reality", "realitySettings": { "show": false, "fingerprint": "chrome", "serverName": "XXXXXXXXXXXX", "publicKey": "XXXXXXXXXXXX", "shortId": "", "spiderX": "/" } } }, { "tag": "vlessrea2-out", "protocol": "vless", "settings": { "vnext": [ { "address": "XXX.XXX.XXX.XXX", "port": 443, "users": [ { "id": "XXXXXXXXXXXX", "flow": "", "encryption": "none" } ] } ] }, "streamSettings": { "network": "h2", "security": "reality", "realitySettings": { "show": false, "fingerprint": "chrome", "serverName": "XXXXXXXXXXXX", "publicKey": "XXXXXXXXXXXX", "shortId": "", "spiderX": "/" } } } ], "routing": { "balancers": [ { "tag": "vlessrea-out-balancer", "selector": ["vlessrea1-out","vlessrea2-out"] } ], "rules": [ { "type": "field", "domain": ["geosite:private","geosite:cn"], "outboundTag": "direct-out" }, { "type": "field", "protocol": ["bittorrent"], "outboundTag": "direct-out" }, { "type": "field", "ip": ["geoip:private","geoip:cn"], "outboundTag": "direct-out" }, { "type": "field", "inboundTag": ["socks1080_in","http1081_in"], "balancerTag": "vlessrea-out-balancer" } ] } }

感谢

**Comment by us254** [comment]
> > > > It means that different shortids are used for load balancing?
> > > 
> > > 
> > > It is not necessary, as long as it is an object in outbounds.
> > 
> > 
> > Can you give me your complete configuration file with Balancer? I am also researching recently. As far as I know, there is currently no health check for Balancer in xray, grpc and h2 are easy to cut off, and the effect is not as good as the load balancing on the clash side. #1751
> 
> { "log": { "loglevel": "none" }, "inbounds": [{ "listen": "0.0.0.0", "port": 1080, "protocol": "socks", "tag": "socks1080_in", "settings": { "auth": "noauth", "udp": true }, "sniffing": { "enabled": true, "destOverride": ["http","tls"] } }, { "listen": "0.0.0.0", "port": 1081, "protocol": "http", "tag": "socks1081_in", "sniffing": { "enabled": true, "destOverride": ["http","tls"] } } ],
> 
> "outbounds": [ { "tag": "vlessrea1-out", "protocol": "vless", "settings": { "vnext": [ { "address": "XXX.XXX.XXX.XXX", "port": 443, "users": [ { "id": "XXXXXXXXXXXX", "flow": "", "encryption": "none" } ] } ] }, "streamSettings": { "network": "h2", "security": "reality", "realitySettings": { "show": false, "fingerprint": "chrome", "serverName": "XXXXXXXXXXXX", "publicKey": "XXXXXXXXXXXX", "shortId": "", "spiderX": "/" } } }, { "tag": "vlessrea2-out", "protocol": "vless", "settings": { "vnext": [ { "address": "XXX.XXX.XXX.XXX", "port": 443, "users": [ { "id": "XXXXXXXXXXXX", "flow": "", "encryption": "none" } ] } ] }, "streamSettings": { "network": "h2", "security": "reality", "realitySettings": { "show": false, "fingerprint": "chrome", "serverName": "XXXXXXXXXXXX", "publicKey": "XXXXXXXXXXXX", "shortId": "", "spiderX": "/" } } } ], "routing": { "balancers": [ { "tag": "vlessrea-out-balancer", "selector": ["vlessrea1-out","vlessrea2-out"] } ], "rules": [ { "type": "field", "domain": ["geosite:private","geosite:cn"], "outboundTag": "direct-out" }, { "type": "field", "protocol": ["bittorrent"], "outboundTag": "direct-out" }, { "type": "field", "ip": ["geoip:private","geoip:cn"], "outboundTag": "direct-out" }, { "type": "field", "inboundTag": ["socks1080_in","http1081_in"], "balancerTag": "vlessrea-out-balancer" } ] } }

"Should this be configured on the client-side or the server-side?"
