### ISSUE TITLE
使用grpc时，客户端sockopt设置不生效

### ISSUE THREAD

**Issue by zjudongze** [XTLS/Xray-core#2098]
https://xtls.github.io/en/config/transport.html#transportobject
使用grpc时，sockopt参数不生效；导致android上master分支（目前 bb26f85）使用go默认的15秒保活，非常耗电

例如
{
  "network": "grpc",
  "security": "reality",
  "grpcSettings": {},
  "sockopt": {
    "mark": 0,
    "tcpFastOpen": false,
    "tproxy": "off",
    "domainStrategy": "AsIs",
    "dialerProxy": "",
    "acceptProxyProtocol": false,
    "tcpKeepAliveInterval": 60
  }
}

**Comment by Fangliding** [comment]
恐怕那是grpc自带的
