### ISSUE TITLE
日志【fallback starts > github.com/xtls/xray-core/v1/proxy/vless/encoding: invalid request version】

### ISSUE THREAD

**Issue by flyhigherpi** [XTLS/Xray-core#21]
会是什么原因呢

**Comment by rprx** [comment]
比如网站被浏览器访问

**Comment by badO1a5A90** [comment]
> 比如网站被浏览器访问

这个日志确实看起来很多人会觉得出现了错误。

**Comment by flyhigherpi** [comment]
> 比如网站被浏览器访问

我在两台vps上分别用v2rayagnet部署了

> 比如网站被浏览器访问

我在两个vps上用agent一键部署，最后加了vless-kcp的参数，一台正常。
这是连接失败的vps的日志。

**Comment by rprx** [comment]
@flyhigherpi 

如果配置完全一样，一台正常一台失败，则应该非程序问题

**Comment by flyhigherpi** [comment]
> @flyhigherpi
> 
> 如果配置完全一样，一台正常一台失败，则应该非程序问题

{
  "inbounds":[
    {
      "port": 443,
      "protocol": "vless",
      "tag":"VLESSTCP",
      "settings": {
        "clients": [
          {
            "id": "b6dd2f04-2b1b-3054-5ce4-e461dea56395",
            "add": "",
            "flow":"xtls-rprx-origin",
            "email": "VLESS_XTLS/TLS-origin_TCP"
          },
          {
            "id": "86eff3a3-73f4-1663-4531-d2abdc4acf6f",
            "flow":"xtls-rprx-direct",
            "email": "VLESS_XTLS/TLS-direct_TCP"
          }
        ],
        "decryption": "none",
        "fallbacks": [
            {"dest":80,"xver":0}
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
          "alpn": [
            "http/1.1"
          ],
          "certificates": [
            {
              "certificateFile": "/etc/v2ray-agent/tls/x.crt",
              "keyFile": "/etc/v2ray-agent/tls/x.key"
            }
          ]
        }
      }
    },
    {
      "tag": "kcp-vless-55512",
      "port": 55512,
      "protocol": "vless",
      "settings": {
        "clients": [
          {"email": "03@kcp-vless-55512", "level": 0, "id": "01e9bb6e-8607-47c1-9acf-267318290c03"},
          {"email": "04@kcp-vless-55512", "level": 0, "id": "02e9bb6e-8607-47c1-9acf-267318290c04"}
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "kcp",
        "kcpSettings": {
          "mtu": 1350,
          "tti": 50,
          "uplinkCapacity": 30,
          "downlinkCapacity": 100,
          "congestion": false,
          "readBufferSize": 3,
          "writeBufferSize": 3,
          "header": {"type": "none"},
          "seed": "kcpPassword"
        }
      },
      "sniffing": {"enabled": true, "destOverride": ["http", "tls"]}
    }
  ]
}
配置内的xtls-direct可用。就是最后部分的kcp不可用。挺奇怪的。已经放一边了。

**Comment by rprx** [comment]
@flyhigherpi 

同样配置试试 v2ray-core v4.32.1

**Comment by rprx** [comment]
https://github.com/XTLS/Xray-core/releases/tag/v1.1.2

试试最新版本，若问题仍然存在，请开新的 issue。
