### ISSUE TITLE
REALITY+utls+vless+ipv4 的情况下 443 和 非443端口（比如 1234）的稳定性差距？

### ISSUE THREAD

**Issue by jiangying000** [XTLS/Xray-core#2101]
有人试过吗，我现在用的是 非443端口，上次用了一周被封了。
如果改成 443 优势有多大？

**Comment by AlphaGHX** [comment]
甲骨文首尔，443 端口，已经稳定运行半个月，累计跑了 100G。
目前感觉还稳定，之前用 Trojan-go 跑 443 基本一天就封。

**Comment by RPRX** [comment]
REALITY 放 443 显然更合理

**Comment by toyo2333** [comment]
> 

如果端口被封了。就没办法了。。也不能套CDN救，换ip要5刀。。肉疼。

**Comment by toyo2333** [comment]
> REALITY 放 443 显然更合理

如果端口被封了。就没办法了。。也不能套CDN救，换ip要5刀。。肉疼。
