### ISSUE TITLE
Lack of Websocket Support in Xray Core for Iranian Users

### ISSUE THREAD

**Issue by masood5400** [XTLS/Xray-core#2105]
Hello,

I hope this message finds you well. I would like to address an issue regarding the Xray Core repository. Firstly, I want to express my appreciation for the fantastic new Reality feature that works seamlessly on TCP and gRPC. It has greatly improved my experience.

However, I would like to bring to your attention the fact that Xray Core currently lacks support for Websocket connections. This limitation poses a challenge for users in Iran who rely on Websocket for certain applications and integrations. I understand that implementing this feature may require significant development effort, but I believe it would greatly enhance the usability of Xray Core for a broader audience.

Could you please provide an estimated timeline for when Websocket support might be available in Xray Core? This information would be extremely helpful for planning purposes and managing user expectations.

Thank you for your attention to this matter. I look forward to your response and the future improvements to Xray Core.

Best regards

**Comment by lostsoul6** [comment]
> > Could you please provide an estimated timeline for when Websocket support might be available in Xray Core?
> 
> websocket is available in xray core long time ago,plz follow this [link](https://xtls.github.io/config/transports/websocket.html) and check more details.

I think he meant websocket with REALITY .

**Comment by masood5400** [comment]
I mean websocket with REALITY .

**Comment by us254** [comment]
https://github.com/XTLS/Xray-core/discussions/1921#discussioncomment-5562063


Reality, working principle is different. I think it can never use cdn. unless it discards its original function and redesigns it.
If its functions and disadvantages become the same as ws+cdn, then it makes no sense.
