### ISSUE TITLE
pls realse stable version

### ISSUE THREAD

**Issue by xmohammad1** [XTLS/Xray-core#2106]
hey , first of all thanks for helping us to skip filterting , new protcol (reality) works great in iran , so fast and all good , the only problem is some apps like v2rayn or v2rayng most ppl use it still on 1.7.5 xray version which is last stable xraycore , pls release a new stable version we need it so bad <3

**Comment by Michaol** [comment]
In fact, you can download and replace both of these apps yourself in the pre-release ver.

**Comment by RPRX** [comment]
重复 https://github.com/XTLS/Xray-core/issues/2104
