### ISSUE TITLE
DPI vs. v2ray

### ISSUE THREAD

**Issue by alidxdydz** [XTLS/Xray-core#2107]
I wonder if you have seen this repo and what is your idea about this repo?

https://github.com/rickyzhang82/V2Ray-Deep-Packet-Inspection

**Comment by ZhuangJiayu** [comment]
照你们这个翻github的速度，我要是GFW开发者我能高兴死，天天蹲在这个repo的issue里找各位老哥发现的检测方法，工作也太简单了。

**Comment by alidxdydz** [comment]
> 你们伊朗兄弟们能不能懂得低调一点，别看到个东西就满世界宣传。

I think you are missing some important points.
First, it's already on the internet and it only takes to search v2ray+DPI.
Second, if v2ray was working fine no one would bother to see what could be the problem. So, I assume GFW already knows about this and maybe it has implemented it.
Third, author clearly says he has reached out to v2ray developers (don't know if he has reached to xray devs). However, he had no answer.

**Comment by alidxdydz** [comment]
> 你们伊朗兄弟们能不能懂得低调一点，别看到个东西就满世界宣传。

Just think about the other day @RPRX introducing "Trojan Killer" so everyone was able to see the TLS in TLS bug.

**Comment by alidxdydz** [comment]
> 你们伊朗兄弟们能不能懂得低调一点，别看到个东西就满世界宣传。

Just think about the other day that @RPRX introduced "Trojan Killer" so everyone was able to see the TLS in TLS bug.
I believe these kind of problems, help Devs to improve their Protocols.
For example, see here for Mieru:
https://github.com/enfein/mieru/issues/54

**Comment by mega-optimus** [comment]
If the claim is true, i think it's an opportunity to integrate similar models into testing pipeline, to make the protocol truely anonymous.

**Comment by alidxdydz** [comment]
> If the claim is true, i think it's an opportunity to integrate similar models into testing pipeline, to make the protocol truely anonymous.

All of the tests had been done during before utls adoption. Therefore, I was wondering if devs have tested these after utls adoption.

**Comment by RPRX** [comment]
1. 这个东西，早就见过，用深度学习的方式来做流量分类，可以，但有个小问题是，可解释性比较差，参数量越大越难解释
2. 我清楚地知道所有已知协议的问题，请各位牢记，我有 N 种方式精准识别所有已知协议，这里的东西在我看来都只是玩具
