### ISSUE TITLE
Fallback Support for XTLS Reality

### ISSUE THREAD

**Issue by amir-devman** [XTLS/Xray-core#2108]
I have tried to have both xtls vision and reality as fallback on 443 port on the same server but looks like it can't be happening even reality with tcp + reality h2 with different paths/alpn.

Is fallback supported for reality or it's not implemented or is it impossible to implement?

**Comment by us254** [comment]
https://github.com/chika0801/Xray-examples/blob/main/VLESS-H2-uTLS-REALITY/config_server_shared_port.json

**Comment by amir-devman** [comment]
> https://github.com/chika0801/Xray-examples/blob/main/VLESS-H2-uTLS-REALITY/config_server_shared_port.json

Have you tried reallity fallback with xtls vision tcp?

**Comment by RPRX** [comment]
`fallbacks` 的 `path` 暂不支持 h2c

**Comment by flyinthe-sky** [comment]
> `fallbacks``path`H2C is not currently supported

is it now?
