### ISSUE TITLE
PATH直接用UUID没什么安全隐患吧。

### ISSUE THREAD

**Issue by daiaji** [XTLS/Xray-core#2112]
UUID本身就是随机的。
这应该没啥问题吧？

**Comment by RPRX** [comment]
通常情况下是没问题的

**Comment by RPRX** [comment]
看了下群，Super Catcat 这次说话比较正常，当然，不要用和 VLESS 相同的 UUID，要生成新的

**Comment by daiaji** [comment]
是因为和path和UUID相同，安全性稍微弱些？
