### ISSUE TITLE
please add "max_connections" option in mux

### ISSUE THREAD

**Issue by peymanhaji** [XTLS/Xray-core#2115]
sing-box has "max_connections" option in multiplex(mux)
is very useful to me i can handle number of connections with it.

please add this option to xray

xray has option "concurrency" is similar to"max_streams" of sing-box (but i need "max_connections" feature)

**Comment by RPRX** [comment]
重复 https://github.com/XTLS/Xray-core/issues/2097#issuecomment-1554499626
