### ISSUE TITLE
DNS issue with Reality protocol

### ISSUE THREAD

**Issue by mglwolf** [XTLS/Xray-core#2116]
Hi, 
我在json下设定了DNS 如下：
  "dns": {
    "servers": [
      "1.1.1.1",
      "1.0.0.1"
    ]
  }

那么它在跑VLESS协议时能初始化DNS:
Xray 1.8.1 (Xray, Penetrates Everything.) Custom (go1.20.3 linux/arm64)
A unified platform for anti-censorship.
2023/05/20 16:24:38 [Info] infra/conf/serial: Reading config: apps/xray/vmess.json
2023/05/20 16:24:38 [Debug] app/log: Logger started
2023/05/20 16:24:38 [Info] app/dns: DNS: created UDP client initialized for 1.1.1.1:53
2023/05/20 16:24:38 [Info] app/dns: DNS: created UDP client initialized for 1.0.0.1:53
2023/05/20 16:24:38 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:443
2023/05/20 16:24:38 [Info] transport/internet/websocket: listening TCP(for WS) on 0.0.0.0:443
2023/05/20 16:24:38 [Warning] core: Xray 1.8.1 started

但是当改为跑Reality协议时它就无法运作:
Xray 1.8.1 (Xray, Penetrates Everything.) Custom (go1.20.3 linux/arm64)
A unified platform for anti-censorship.
2023/05/20 16:25:25 [Info] infra/conf/serial: Reading config: reality.json
2023/05/20 16:25:25 [Debug] app/log: Logger started
2023/05/20 16:25:25 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:443
2023/05/20 16:25:25 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:443
2023/05/20 16:25:25 [Warning] core: Xray 1.8.1 started

那么结果是：
2023/05/20 16:18:31 [Info] transport/internet/tcp: REALITY: failed to dial dest: dial tcp: lookup itunes.apple.com on [::1]:53: read udp [::1]:35408->[::1]:53: read: connection refused

敬请指教。

**Comment by mglwolf** [comment]
{
  "log": {
    "loglevel": "debug"
  },
    "inbounds": [
        {
            "listen": "0.0.0.0",
            "port": 443,
            "protocol": "vless",
            "tag": "reality",
            "sniffing": {
              "enabled": true,
               "destOverride": [
                 "http",
                 "quic",
                 "tls"
                ]
            },
            "settings": {
                "clients": [
                    {
                        "id": "xxxx",
                        "flow": "xtls-rprx-vision"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "tcp",
                "security": "reality",
                "realitySettings": {
                    "show": false,
                    "dest": "itunes.apple.com:443",
                    "xver": 0,
                    "serverNames": [
                        "itunes.apple.com",
                    ],
                    "privateKey": "xxxx",
                    "minClientVer": "",
                    "maxClientVer": "",
                    "maxTimeDiff": 0,
                    "shortIds": [
                        "xxxx"
                    ]
                }
            }
        }
    ]
},
    "outbounds":[
    {
        "protocol": "freedom",
        "settings": {
            "domainStrategy": "UseIP"
      },
        "tag": "iNet"
    }
],
    "dns": {
      "servers": [
        "1.1.1.1",
        "1.0.0.1"
      ]
    }
},
,
   "routing": {
     "domainStrategy": "IPOnDemand",
     "rules": [
       {
         "type": "field",
         "inboundTag": [
            "reality"
         ],
         "outboundTag": "iNet"
       },

**Comment by RPRX** [comment]
理论上，REALITY 配置不会影响 DNS 配置
