### ISSUE TITLE
Limit Concurrent Connections from the same UUID

### ISSUE THREAD

**Issue by arashammm** [XTLS/Xray-core#2118]
hello to xray community.
I was wondering without using the x-ui web panel , is there any API defined in xray core to limit concurrent connection from the same UUID , the setup I would like to have is to limit the use of an uuid to just one client.
Also can anyone guide me where should I find in the xray code the ability to check the uuids for active connection and disallow new connections from the active uuid?

Any help would be appreciated as always

**Comment by us254** [comment]
You can use XrayR as a backend for your Xray-core server, and configure it to connect to your panel. XrayR supports limiting concurrent connections from the same UUID by setting the userConnLimit parameter in the config file. You can also set the nodeConnLimit parameter to limit the total connections of the node. For more details, please refer to the documentation of XrayR at https://github.com/XrayR-project/XrayR-doc.

**Comment by arashammm** [comment]
Can XrayR configured to be the backend of x-ui panel?
If yes can you guide me how can I do that?

**Comment by arashammm** [comment]
Any other ideas?
I specially need to find out what part of xray code could be responsible for checking uuid of clients to setup my own application for detecting concurrent connections

**Comment by yuhan6665** [comment]
No plan for core

**Comment by metaligh** [comment]
Is it possible to somehow configure one connection for vless panel 3x-ui?
