### ISSUE TITLE
请问我配置了服务器和客户端，但是一直无法使用是什么原因？

### ISSUE THREAD

**Issue by aborover** [XTLS/Xray-core#213]
按照小白教程的配置
服务端配置：
{
    "log": {
        "loglevel": "warning",
        "access": "/home/xray_log/access.log",
        "error": "/home/xray_log/error.log"
    },

    "dns": {
        "servers": [
            "https+local://1.1.1.1/dns-query",
            "localhost"
        ]
    },

    "routing": {
        "domainStrategy": "AsIs",
        "rules": [
            {
                "type": "field",
                "ip": [
                    "geoip:private"
                ],
                "outboundTag": "block"
            },
            {
                "type": "field",
                "domain": [
                    "geosite:category-ads-all"
                ],
                "outboundTag": "block"
            }
        ]
    },

    "inbounds": [
        {
            "port": 1111,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "uid",
                        "flow": "xtls-rprx-direct",
                        "level": 0
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": 443
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "allowInsecure": false,
                    "minVersion": "1.2",
                    "alpn": [
                        "http/1.1","h2"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "crt.crt",
                            "keyFile": "key.key"
                        }
                    ]
                }
            }
        }
    ],

    "outbounds": [
        {
            "tag": "direct",
            "protocol": "freedom"
        },
        {
            "tag": "block",
            "protocol": "blackhole"
        }
    ]
}
客户端配置：
{
    "inbounds": [
        {
            "listen": "127.0.0.1",
            "port": 8000,
            "protocol": "socks",
            "settings": {
                "udp": true
            }
        },
        {
            "listen": "127.0.0.1",
            "port": 8001,
            "protocol": "http"
        }
    ],
    "log": {
        "access": "/home/xray_log/access.log",
        "error": "/home/xray_log/error.log",
        "loglevel": "warning"
    },
    "outbounds": [
        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "IP",
                        "port": 1111,
                        "users": [
                            {
                                "encryption": "none",
                                "flow": "xtls-rprx-splice",
                                "id": "uid",
                                "level": 0
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "allowInsecure": false,
                    "serverName": "域名"
                }
            }
        },
        {
            "protocol": "freedom"
        },
        {
            "protocol": "blackhole"
        }
    ],
    "routing": {
        "domainStrategy": "AsIs",
        "rules": [
            {
                "domain": [
                    "geosite:category-ads-all"
                ],
                "outboundTag": "block",
                "type": "field"
            },
            {
                "domain": [
                    "geosite:cn"
                ],
                "outboundTag": "direct",
                "type": "field"
            },
            {
                "ip": [
                    "geoip:cn",
                    "geoip:private"
                ],
                "outboundTag": "direct",
                "type": "field"
            },
            {
                "domain": [
                    "geosite:geolocation-!cn"
                ],
                "outboundTag": "proxy",
                "type": "field"
            }
        ]
    }
}
Qv2ray里分组状态上有返回的连接速度，但是打不开墙外网站。自己的网站也能打开

**Comment by rprx** [comment]
客户端非 Linux 时用 XTLS Direct

**Comment by aborover** [comment]
客户端是linuxmint 20.1

**Comment by aborover** [comment]
> 客户端非 Linux 时用 XTLS Direct

客户端是linuxmint 20.1

**Comment by luoluodaduan** [comment]
有可能是 log文档 你要先创建xray_log文件夹 不知道如果不使用 http/2 我觉得是不是应该删除 h2 选项

**Comment by luoluodaduan** [comment]
还有客户端 是splice 服务端是direct  改成一致吧

**Comment by 70599** [comment]
自己看看

1. 有没有日志
2. 日志里有没有错误信息

**Comment by rprx** [comment]
回落的使用方式错误（但可以打开部署的网站很正常），也没有附日志，可能比如 Xray 没运行起来，或者防火墙没放行 1111 端口

如果仍未解决问题，请附上日志开新的 issue，没有日志只能靠猜，效率很低
