### ISSUE TITLE
建议shadowsocks 支持domainsocket

### ISSUE THREAD

**Issue by nick008a** [XTLS/Xray-core#2130]
https://www.v2fly.org/config/inbounds.html#inboundobject

VLESS、VMess、Trojan 都支持domainsocket了，求支持 shadowsocks 

如果能支持shadowsocks +WebSocket+domainsocket就更完美了！

**Comment by RPRX** [comment]
我记得这个文档没写 Shadowsocks，只是因为 Shadowsocks 有原生 UDP，如果你只开 TCP，应该是可以的，代码中应该没有限制
