### ISSUE TITLE
 Question about Source Code Availability and Package Trustworthiness of the Hiddify panel

### ISSUE THREAD

**Issue by tavallaie** [XTLS/Xray-core#2132]
I attempted to access the source code for the [hiddify](https://github.com/hiddify/hiddify-config) project on their GitHub repository, but I was unable to locate it. However, during my exploration of their setup, I discovered that they rely on a PyPI package named [hiddifypanel](https://pypi.org/project/hiddifypanel/). This package appears to be a binary, and it is unclear whether it contains any potential backdoors or security vulnerabilities. For reference, you can find the binary at the following [PyPI Inspector link](https://inspector.pypi.io/project/hiddifypanel/7.0.0.dev21/packages/83/86/cede2f5856f45d627cd3421267a4a9e1a397e0d2c0bead3d38a2a833de98/hiddifypanel-7.0.0.dev21-cp310-cp310-manylinux2014_aarch64.whl/hiddifypanel/__main__.py).

It is worth noting that the hiddify team is currently advertising that the XTLS-core team trusts their project. Therefore, I kindly request the repository maintainers to either remove or explicitly tag the project as a partially open source/commercial panel. Alternatively, it would be beneficial to conduct a thorough inspection of the package to ensure its integrity and absence of any potential backdoors in the future.

Thank you for your attention to this matter.

**Comment by hiddify1** [comment]
Dear tavallaie,
Thank you for your comment.
All the api, clients, and also the configuration and connection parts are open source and not only open source but also automatically compile and publish while in that list there are many other close source applications and paid applications.


By the way, what you are talking is about the rebranding out always free UI for non commercial use and unfortunately our license does not allow you to rebrand it. 
If you want to have your name on the panel, you can build a new system with your name and use the open source version of hiddify-config. You just need to follow install.sh, run.sh format and in your panel provide json formated user informations.

**Comment by yuhan6665** [comment]
closing as irrelevant
