### ISSUE TITLE
关于全局地址本的需求

### ISSUE THREAD

**Issue by iceliuhacker** [XTLS/Xray-core#2136]
目前路由规则、DNS规则使用的地址标签是各自的，能否新增一个全局地址本，比如：
addtag: "xxx.com"
["domain:xxx.com","domain:xxx.net"]

然后可以将改地址本即可以直接在dns规则里使用，也可以在路由规则里使用。
这样能让解析和路由更加统一。

**Comment by yuhan6665** [comment]
geosite 不行吗？

**Comment by liuhgiceblood** [comment]
> geosite 不行吗？

很多地址不在geosite里，所以需要自定义域名清单，但是发现route和dns里要配置两遍。但如果有全局地址簿，只需要修改一个就可以，甚至某些原因可能更地方调用。
比如某些地址a用户用1.1.1.1解析，b用户用2.2.2.2解析。路由上两个用户走得也不同，没有全局地址簿，就需要设置四次。

**Comment by yuhan6665** [comment]
你可以试试自制 dat https://guide.v2fly.org/routing/sitedata.html#%E5%A4%96%E7%BD%AE%E7%9A%84%E5%9F%9F%E5%90%8D%E6%96%87%E4%BB%B6
