### ISSUE TITLE
pls release a version with sing-box optimizations

### ISSUE THREAD

**Issue by xmohammad1** [XTLS/Xray-core#2139]
hi how you guys doing good , sing-box optimizations are perry much useful like when i check my reality + grpc config ping is 120ms with sing-box core and when i test with xray core is like 300 , also i feel more speed with sing-box core in web searching and other things
pls release a version with some optimizations like sing-box  , thanks in advance

**Comment by us254** [comment]
You have been influenced by the persuasive advertisements of sing-box by @isegsro and his colleague. I have tried sing-box and I found it to be significantly slower and inferior to Xray. Advertising can create a false impression. It can make a subpar product seem more appealing in the minds of consumers.

**Comment by us254** [comment]
I have tested various sing-box configurations for their latency and speed, and I found no difference from xray. I think some people  are promoting sing-box with exaggerated claims of speed. There is nothing special about sing-box, so I don’t understand why there is so much hype about it.

**Comment by RPRX** [comment]
是这样的，绝大多数伊朗人分不清 Xray-core / v2fly-core / v2ray-core，这个问题早就回复过了 https://github.com/XTLS/Xray-core/discussions/2023#discussioncomment-5787253

**Comment by RPRX** [comment]
偶尔看到伊朗人说 v2ray REALITY，麻了。。。~~虽然 APP 确实叫 v2rayNG~~

你们要明白，一般来说，我们倾向于被称为 Xray，因为 v2ray 可能用于指代 v2fly 内核，避免歧义，我们这边一般说 Xray 和 v2fly
如果具体到项目名，当你看到 Xray-core 和 v2ray-core 的字眼，要知道这两个不是同一个东西，有很多区别，性能上的功能上的
