### ISSUE TITLE
关于fallback回落地址的问题

### ISSUE THREAD

**Issue by fivetime** [XTLS/Xray-core#214]
关于fallback回落地址的问题：
测试如下：
1、将fallback回落配置到nginx的80端口，正常curl请求则由nginx回应http报文。
2、用telnet连接到端口，随便输入一些字符，则直接断开连接，不会交给nginx去响应http

对于GFW来识别这个就很好判断了，正常的nginx用telnet连接后，不管发送什么错误字符，至少会响应http 400

**Comment by jiuqi9997** [comment]
@fivetime 回落做成转发才能实现什么都给nginx回应

**Comment by rprx** [comment]
回落是我写 VLESS 时首创的“首包长度分流”模式，对于你描述的情况，会把任何后续数据都转发到 nginx，不应该存在区别

**Comment by rprx** [comment]
如果你指的是非 TLS 请求导入到 Nginx TLS 端口时的 400，对于这种情况，参考 https://github.com/v2fly/v2ray-core/issues/375#issue-733632517

>- 服务端 TLS/XTLS 不同的配置也有不同的指纹，与 Caddy 能配置出的效果一致最佳
>- 但这不成问题，因为服务端 TLS 的不同配置、前置分流等非常常见（包括 是/否 处理 TLS）
>- 举个例子，SNI 预分流的场景下也不会响应非 TLS 数据，可选 1 就不是必要的

**Comment by fivetime** [comment]
回落做成转发和不转发日志如下：
127.0.0.1 - - [28/Jan/2021:13:54:38 +0000] "PROXY TCP4 61.118.x.x 172.26.x.x 59225 6120" 400 157 "-" "-"
127.0.0.1 - - [28/Jan/2021:14:00:45 +0000] "GET / HTTP/1.1" 403 153 "-" "curl/7.55.1"

转发日志是一个PROXY的请求，nginx如何区分该请求是否一个正常的curl发送的还是telnet随便输入的？
我的意思是正常的curl请求的http应该响应200，而telnet输入错误的字符应该响就http 400

**Comment by rprx** [comment]
@fivetime 试试不使用 xver

**Comment by rprx** [comment]
@fivetime 感觉这里好像存在一些误解或概念混乱，请重新详细描述一下配置方式及测试过程

**Comment by fivetime** [comment]
···
                    "settings": {
                                "clients": [],
                                "decryption": "none",
                                "fallbacks": [
                                        {
                                                "dest": 80
                                        }
                                ]
                                ,"fail": {"dest":443,"xver":0}
                        }
···

这是回落的配置，当用curl请求时，则可以由nginx响应200； 当用telnet输入错误的请求时，则直接断开连接

**Comment by fivetime** [comment]
我希望用telnet输入错误的请求时，也由nginx回应http 400

**Comment by rprx** [comment]
是由 Xray 处理 TLS 对吧？

**Comment by rprx** [comment]
（请发更完整的配置，以及说明对哪个端口进行的测试

**Comment by fivetime** [comment]
完整的配置
```
{
			"tag": "vl_tcp",
			"port": 6120,
			"listen": "0.0.0.0",
			"protocol": "vless",
			"settings": {
				"clients": [],
				"decryption": "none",
				"fallbacks": [
					{
						"dest": 80
					}
				]
			},
			"streamSettings": {
				"network": "tcp",
				"security": "xtls",
				"xtlsSettings": {
					"alpn": [
						"h2",
						"http/1.1"
					],
					"certificates": [
						{
							"certificateFile": "/data/programs/nginx/cert/localhost.crt",
							"keyFile": "/data/programs/nginx/cert/localhost.key"
						}
					]
				}
			}
		}
```

**Comment by rprx** [comment]
@fivetime 然后 curl 和 telnet 均是对 6120 端口进行测试？

**Comment by fivetime** [comment]
是的

**Comment by fivetime** [comment]
curl能回应http 200，telnet则直接断开连接，按正常的nginx处理应该是回应http 400

**Comment by rprx** [comment]
@fivetime 是的，这种情况参考 https://github.com/XTLS/Xray-core/issues/214#issuecomment-769143311

**Comment by fivetime** [comment]
这个```"fail": { "dest":8443, "xver":0 }```应该写在哪个json节点下面？

**Comment by rprx** [comment]
@fivetime 目前还没有加此功能，你看错重点了。。。

**Comment by fivetime** [comment]
就是说目前没法实现telnet输入错误的http请求，没办法由nginx响应http code 400？

**Comment by rprx** [comment]
@fivetime 是的，而且这很常见，无法作为识别依据

**Comment by fivetime** [comment]
不对，这不常见，GFW一看就知道你这个nginx是藏在vless后面

**Comment by rprx** [comment]
@fivetime 你仔细看我的回复。。。

**Comment by luoluodaduan** [comment]
我觉得前置 nginx分流能解决你提出的问题

**Comment by rprx** [comment]
握手失败的回落功能早就有计划却迟迟没有开发，是因为不足以作为识别依据；目前的重点是解决客户端的 TLS 指纹问题。

**Comment by kirin10000** [comment]
> 握手失败的回落功能早就有计划却迟迟没有开发，

@rprx 如果不能保证Xray服务端的TLS指纹和web服务器的相同，不建议开发此功能。

因为绝大多数的TLS前置分流器都没有对非TLS流量处理，比如Haproxy。如果Xray能对非TLS流量处理，反而可能引入更多特征

比如配置Xray回落Nginx，如果能够从服务端指纹得知前置的不是Nginx，并且它又能对非TLS流量处理，是Xray的可能性大大增加了。
