### ISSUE TITLE
xray切换到1.8节点reality不可以用

### ISSUE THREAD

**Issue by hoyrian** [XTLS/Xray-core#2141]
我的xray面板在1.7.5reality节点正常可以使用，但是反而升级为1.8后节点就不可用

**Comment by ZhuangJiayu** [comment]
大哥你就这一句话，也没个日志，甚至不知道是哪个面板，这谁能帮你呢

**Comment by hoyrian** [comment]
x-ui面板
[2210273253] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: EOF"] > common/retry: all retry attempts failed

**Comment by hoyrian** [comment]
x-ui面板
[2210273253] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: EOF"] > common/retry: all retry attempts failed

**Comment by nursery01** [comment]
1.7.5和1.8不相容

**Comment by onenora** [comment]
1.75哪里来的reality？？

**Comment by zxbiao** [comment]
reality是1.8.x才有的功能。。。
从错误信息来看是gRPC协议的问题，是不是引用了已在1.8.x弃用的flow了？

**Comment by hoyrian** [comment]
[FranzKafkaYu]的x-ui面板 xray 1.7.5也是有reality的， v2rayn的xray最新版1.7.5也是有reality
xui配置如下 
{
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 36996,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "policy": {
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ]
  },
  "stats": {}
}

**Comment by zxbiao** [comment]
> [FranzKafkaYu]的x-ui面板 xray 1.7.5也是有reality的， v2rayn的xray最新版1.7.5也是有reality xui配置如下 { "api": { "services": [ "HandlerService", "LoggerService", "StatsService" ], "tag": "api" }, "inbounds": [ { "listen": "127.0.0.1", "port": 36996, "protocol": "dokodemo-door", "settings": { "address": "127.0.0.1" }, "tag": "api" } ], "outbounds": [ { "protocol": "freedom", "settings": {} }, { "protocol": "blackhole", "settings": {}, "tag": "blocked" } ], "policy": { "system": { "statsInboundDownlink": true, "statsInboundUplink": true } }, "routing": { "rules": [ { "inboundTag": [ "api" ], "outboundTag": "api", "type": "field" }, { "ip": [ "geoip:private" ], "outboundTag": "blocked", "type": "field" }, { "outboundTag": "blocked", "protocol": [ "bittorrent" ], "type": "field" } ] }, "stats": {} }

把X-UI的模板贴出来并没有什么用。。。你看一下你的节点是不是引用了旧有的流控（flow）

**Comment by hoyrian** [comment]
flow是空的，没有用流控。vless+grpc+reality

**Comment by FranzKafkaYu** [comment]
Reality需要xray core 1.7.5以上，也就是1.8.0与1.8.1版本支持，1.7.5不支持。

**Comment by ZhuangJiayu** [comment]
1.7.5release版本不支持reality，1.7.5有几个在1.8.0发布前的代码编译后是支持reality的，但xui和v2rayn引用的都是release版本的。所以理论上是不支持的。建议检查内核版本，同时尝试简化协议，换掉gRPC试试

**Comment by yuhan6665** [comment]
close as invalid
