### ISSUE TITLE
Xray-core是否可以设置后置代理？如何设置

### ISSUE THREAD

**Issue by vitaminx** [XTLS/Xray-core#2143]
Xray-core是否可以作为后置代理使用（比如作为tor或者其他代理客户端的后置代理）？如何可以请问如何设置？

**Comment by Fangliding** [comment]
@vitaminx 任意门套套套

**Comment by vitaminx** [comment]
> @vitaminx 任意门套套套

目前主要用的是 clashXPro 和 Xray-core，ClashXPro 可定制化程度低，Xray-core 可定制化程度高，占用资源少；我希望实现的功能是：流量 → 代理服务器1 → tor三级跳 → 代理服务器2 →目标地址

**Comment by yuhan6665** [comment]
大概要把tor搞成透明代理 然后应用本身再开一个代理就是后置

**Comment by vitaminx** [comment]
> 

这个方法能实现，但是不够灵活，可以像 v2ray 一样使用 proxySettings 嵌套设置代理链么？
