### ISSUE TITLE
xray不支持 v2raya下的均衡负载吗

### ISSUE THREAD

**Issue by curui** [XTLS/Xray-core#2144]
截至 2021 年 8 月 27 日，xray 尚未支持基于观测的负载均衡，因此在 v2rayA 中连接多个节点为 v2fly/v2ray-core 所独有。关于负载均衡可参阅 
  怎么样才能选择多个节点呢

**Comment by tianlichunhong** [comment]
可以的，比如在客户端（这个例子是随机）：
	"balancers": [
		{
			"tag": "balancers1",
			"selector": [
				"reality1",
				"reality2",
				"reality3"
			],
			"strategy": {
				"type": "random"
			}
		},
