### ISSUE TITLE
Xray 1.8.1 Socks模式  无法作 udp 双栈同时代理

### ISSUE THREAD

**Issue by ximiTech** [XTLS/Xray-core#2149]
最近测试时偶然发现 Xray 1.8.1 Socks模式 ipv6下 无法作 udp 双栈同时代理

**Comment by chika0801** [comment]
建议补充详细内容

**Comment by ximiTech** [comment]
测试环境如下：
passwall(xray socks模式)通过tuic的本地socks端口联网，测试webrtc泄露情况，在webrtc的ip地址识别中发现，只显示出ipv4地址，无法显示出ipv6地址。
