### ISSUE TITLE
Block everything But 1 website

### ISSUE THREAD

**Issue by The13east** [XTLS/Xray-core#2150]
Hi 
I saw examples of blocking some IPs or websites but I want to block everything and let some websites through ! can anyone help me with that ? 
Also while blocking IPs will they open from the normal internet or they will be blocked while using the proxy ? 
I want to run a services for gaming and one for twitch and youtube 
if anyone can Help me it would be great

**Comment by nima1024m** [comment]
Hello,
Put the Blackhole outbound prior to Freedom and route your desired website to Freedom in Routing section.
In this case, all the IPs and Domains which are not present in Routing will be directed to first outbound which is Blackhole.

**Comment by The13east** [comment]
> Hello, Put the Blackhole outbound prior to Freedom and route your desired website to Freedom in Routing section. In this case, all the IPs and Domains which are not present in Routing will be directed to first outbound which is Blackhole.

I'm a super noob in this can i get a example for it ?

**Comment by us254** [comment]
```
{
  "inbounds": [
    {
      "port": 1080,
      "protocol": "socks",
      "settings": {
        "auth": "noauth"
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "blackhole",
      "settings": {}
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "Freedom"
    }
  ],
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "domain": [
          "twitch.com",
          "youtube.com"
        ],
        "outboundTag": "Freedom"
      }
    ]
  }
}
```

**Comment by The13east** [comment]
this is my config file right now ! I'm kinda confused atm


{
  "log": {
    "loglevel": "warning"
  },
 
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ]
  },
  "stats": {}
}

**Comment by The13east** [comment]
> 

I understand the outbound now but i still dont get the routing rules 
my config is up here now can you pls replace the part so i can understand it better ?

**Comment by yuhan6665** [comment]
https://xtls.github.io/config/routing.html

**Comment by The13east** [comment]
Guys can i get some help ?
