### ISSUE TITLE
Questions about Reality

### ISSUE THREAD

**Issue by CC0126** [XTLS/Xray-core#2164]
6.1日刚刚开始，Reality 1.8.1会有很大机率造成多次访问后被阻断（无论是通过浏览器直接访问IP的443接口，还是通过客户端访问）
目前用的是microsoft的域名，和自己的域名都试过

客户端表现为 刚开始可以连接，但连接一会后会掉线
浏览器表现为 前5~10次左右可以正常访问，之后再访问会超时，访问超时时，证书有机率被劫持为一个未知域名的证书（前10次正常访问不会出现此现象）

ping 433一直都是通的

如果需要任何详细的日志，我可以帮助获取一下

**Comment by chika0801** [comment]
你遇到此现象的vps商家是什么？

你拿其它vps，协议配置不变，能否复现？

> 和自己的域名
你是指你有一个正常建站的域名，你dest里填的是它？

**Comment by RPRX** [comment]
~~整个大新闻，过个儿童节~~

**Comment by CC0126** [comment]
vps Olink Cloud

我还有一个bandwagong host的vps，Reality部署成功后，也会出现此现象

你是指你有一个正常建站的域名，你dest里填的是它：是的

**Comment by chika0801** [comment]
> 你是指你有一个正常建站的域名，你dest里填的是它：是的

建议你采用方便交流用俗称的“自己偷自己”形式，在你遇到此现象的vps上，都测试下。

或者先进行更换你用的微软的网址，建议换下你vps所在地博物馆，旅游局类的网址，观察能否复现。

**Comment by RPRX** [comment]
我简单说一下，你用自己的域名时，相当于不依赖 CA 的 Nginx TLS，你要说一下你用的协议，看看是不是 TLS in TLS 之类的问题

然后证书被劫持这种事情比较少见，如果经常出现，~~我怀疑是运营商盯上你了~~，你可以换个运营商试试，比如连接手机热点

**Comment by CC0126** [comment]
自己偷自己：
已经测试了两个VPS（因为我只有bandwagonghost和olinkcloud），确实会导致出现上面issue所说的问题。
具体表现为：
在部署“自己偷自己”后，刚刚开始无任何问题，可以正常使用。但只要使用一段时间后（应该是经过了大量的请求后），协议开始变的不稳定起来，具体可以表现为：长连接掉线、测试连接提示SSL handshake Timeout。此时访问自己的域名，同样会出现上述的“特殊证书劫持”现象

建议换下你vps所在地博物馆...：
我是否需要找寻对大陆为白名单的域名？我可以通过直接访问这些域名来测试这些域名是否可以使用吗？

**Comment by CC0126** [comment]
> 

证书劫持是今天刚刚才有的现象，我一直使用的是电信4G手机热点，我连接了邻居的移动WiFi，同样会出现这个问题。

**Comment by chika0801** [comment]
你难道在大陆白名单地区？

你可以下发你服务端配置，看看你用的协议组合形式是什么。

**Comment by chika0801** [comment]
我说的自己偷自己，是 https://github.com/chika0801/Xray-examples/tree/main/VLESS-XTLS-uTLS-REALITY/steal_yourself 这种配置形式。

我不是提你在dest处填你自己建站的域名。

所以你前面说的你试过自己偷自己是？

**Comment by CC0126** [comment]
抱歉，我可能回复的并不及时，因为我的Reality已经彻底无法使用了，因此很难访问这个issue
我给您发一下我的配置：
{
  "inbounds": [
    {
      "port": 443,
      "protocol": "vless",
      "tag": "VLESSReality",
      "settings": {
        "clients": [
          {
            "id": "**",
            "email": "**-vless_reality_vision",
            "flow": "xtls-rprx-vision"
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "dest": "31305",
            "xver": 1
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "show": false,
          "dest": "<我自己的域名>:443",
          "xver": 0,
          "serverNames": [
            "<我自己的域名>"
          ],
          "privateKey": "**",
          "publicKey": "**",
          "maxTimeDiff": 70000,
          "shortIds": [
            ""
          ]
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    }
  ]
}

**Comment by CC0126** [comment]
我如何判断我是否在白名单地区？我直接访问www.microsoft.com和www.apple.com是没有任何问题的

**Comment by chika0801** [comment]
建议你换我上面给你链接里的那种俗称偷自己试试。

不用你上面配置中dest处填你自己建站域名的方式。

另外问下

"fallbacks": [
{
"dest": "31305",
"xver": 1

你这31305端口是什么程序接的开的什么程序？

**Comment by chika0801** [comment]
> 我如何判断我是否在白名单地区？我直接访问www.microsoft.com和www.apple.com是没有任何问题的

一般指在福建省省会城市和特别的泉州市，可能还有其它周边城市，可能3家运营商都有，可能3家策略有些差异

**Comment by RPRX** [comment]
To Skyline：偷自己：

1. 解决服务端 TLS 指纹问题
2. 不依赖 CA，更安全
3. 客户端必须选 uTLS 指纹，防猪队友

~~这些我以前说过，懒得找在哪了，干脆重新打一遍~~

**Comment by RPRX** [comment]
To 768 L：REALITY 是有偷一些东西的，所以可以写“偷自己”，但不能写“偷证书”，因为 REALITY 没偷证书

**Comment by RPRX** [comment]
To a：这个想法挺好的，改成选择题，提供中英两种语言

**Comment by RPRX** [comment]
To 万花 齐芳：~~还是来 issue 说吧，这是公开的记录~~

**Comment by RPRX** [comment]
~~或者有人把他的聊天记录转发到 GitHub 吗~~

**Comment by RPRX** [comment]
关键是他已经发了这个 issue，就需要公开记录一下相关讨论，否则没加群的人看不到

**Comment by RPRX** [comment]
@chika0801 把相关的聊天记录转发到 GitHub 吧，从今天他的第一次发言开始

**Comment by chika0801** [comment]
问了下他没什么特别的地方（信息）。

给他建议还要排除下VPS到他那回程线路是不是波动（比如商家母鸡在被打）。

他之前就在群里的，我觉得类似他这情况，在群里也有其它人遇到过，来问用了REALITY怎么怎么有不稳。要一一排查要素也太多。只是他今天正好发个ISS来问，有引来大家围观（帮助）。

**Comment by RPRX** [comment]
~~标题起得好，围观少不了~~

我有一个想法，证书不对的情况，由于他访问的是 https://IP，没发 SNI，所以有可能是微软配置的策略，而不是连接被劫持了。

**Comment by chika0801** [comment]
![1](https://github.com/XTLS/Xray-core/assets/88967758/eb1f5ffe-5f41-47b6-8cff-36743595b3ef)

![2](https://github.com/XTLS/Xray-core/assets/88967758/f9611151-574b-4827-87d0-0d314dadcfd2)

![3](https://github.com/XTLS/Xray-core/assets/88967758/0fa213d8-f241-4483-be7b-7bb18aa77411)

![4](https://github.com/XTLS/Xray-core/assets/88967758/008d374e-a797-4b68-9c9b-0f0460a6adf0)

![5](https://github.com/XTLS/Xray-core/assets/88967758/3ea29aec-31dc-4bb9-aa07-aa458ea51e4b)

**Comment by chika0801** [comment]
建议把这ISS关了，他在群里的

**Comment by chika0801** [comment]
你遇到的莫名不稳（暂称）的现象，你也不是第1个来群里问，之前也时不时有人问。

每个人情况不一样，对单一的反馈，只能问你下基本情况，给点建议，网上（群）互助，也只能做这么多。

**Comment by Fangliding** [comment]
> To a：这个想法挺好的，改成选择题，提供中英两种语言

就把选中translate版本单独发出来然后消息提供一个跳转link好了
顺便要召唤某人的话直接在github打 @用户名 应该也是可以召唤的
test @Kyouka_Hikawa

**Comment by Lather0519** [comment]
小白用reality 還是建議自己偷自己，這樣出了事更好賴reality

**Comment by chika0801** [comment]
![屏幕截图 2023-06-01 201612](https://github.com/XTLS/Xray-core/assets/88967758/ad374ec8-228d-43bf-b48b-b2176714a49d)

你遇到的看你描述应该是 https://github.com/XTLS/Xray-core/discussions/1772 这种现象。

**Comment by chika0801** [comment]
![屏幕截图 2023-06-01 201741](https://github.com/XTLS/Xray-core/assets/88967758/5108d4a9-e3e4-4170-ab08-86031d9de0c8)


看你描述，你遇到的是 https://github.com/XTLS/Xray-core/discussions/1772 这种现象。

**Comment by RPRX** [comment]
@CC0126 之前我看到你在群里说换个接入点就好了，我的建议是，你应该把所有消息同步到 GitHub 上，~~不要报忧不报喜~~

另外你偷自己的话在墙看来和你用 TLS 是差不多的，而对于 REALITY 我们一般更关注偷别人的问题，所以这个问题实际上是 TLS 的问题了

最近大家都懂的，不排除 GFW 又开始范围攻击之类的，如果没有大规模的针对性的封锁报告，我们不会将其视为“精准识别”，不会花时间解决只有一两个人遇到的问题
