### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by drno88** [XTLS/Xray-core#2165]
Good afternoon. Thank you very much for your work!
i am using xray xtls-rprx-vision protocol.
Can you please tell me how to correctly write outbound so that I can redirect the user there by id \ uuid or email ?

I want different users to log out through different network interfaces.

For example user1 - eth1
user2-eth2
etc

an example of my configuration (yes, there are extra outbounds, don't pay attention)
https://pastebin.com/raw/fDgtH5f9
Someone can help me with this? Thank you very much in advance!

**Comment by yuhan6665** [comment]
https://xtls.github.io/config/routing.html#ruleobject
https://github.com/XTLS/Xray-core/pull/1494

**Comment by drno88** [comment]
@yuhan6665 
@WordsWorthLess 

Thanks for your reply.
I don't mind doing it with a route. I'm just not very experienced in creating such configurations yet, if you don't mind, could you give an example based on my server configuration? Thank you in advance
