### ISSUE TITLE
能不能坐最简单的HTTP伪装?

### ISSUE THREAD

**Issue by linsan970809** [XTLS/Xray-core#2170]
我不追求速度，我只是要查谷歌文档而已，
能不能做最简单的HTTP加密直连做内容伪装为HTML网站
然后套一个Cloudflare就可以
速度达到1 00K/S对我来说就够用了，
HTTPS ,域名证明书申请,NGINX配置伪装这些东西小白真的搞不来
类似goflyway就非常棒,可惜它不更新了,不能走Cloudflare

**Comment by Fangliding** [comment]
@linsan970809 vmess:喵喵喵

**Comment by qist** [comment]
ws 不就可以了么。

**Comment by linsan970809** [comment]
> ws 不就可以了么。

所有的教程都写WS需要TLS

**Comment by qist** [comment]
你不是走cdn 么 cdn 那边可以开启tls 不就可以么。记得回源选择http

**Comment by linsan970809** [comment]
> 你不是走cdn 么 cdn 那边可以开启tls 不就可以么。记得回源选择http
非常感谢,我试试

**Comment by flowerinsnowdh** [comment]
最简单的就是

* 节点服务器裸VLESS over WS +回落
* CDN直接HTTP回源

不过这种方法风险极高，有能力最好还是折腾一下

**Comment by liuhgiceblood** [comment]
小学生？

**Comment by ShadowLoong** [comment]
还是要提高自己的姿势水平

**Comment by lhbdhr** [comment]
既然你的时间这么宝贵,没时间学习各种配置,花钱买个机场呗,你看个文档而已,最小流量的套餐就够了.很便宜的.
