### ISSUE TITLE
当 reality 通过 http 出站代理时，`streamSettings`.`network`不为`tcp`时，设置 http 出站代理的 `headers` 会导致程序崩溃

### ISSUE THREAD

**Issue by flowerinsnowdh** [XTLS/Xray-core#2174]
# 问题描述
我在测试 reality over http 时，程序崩溃，经过测试我发现组合 reality over (h2/grpc) over http 的同时，设置 http 出站协议的 HTTP 头会导致进程崩溃

## 我的设定
我的想法是

```plantext
浏览器 <---[::1]---> 入站{Socks} <---Routing---> 出站{VLESS over Reality} <---`sockopt`.`dialerProxy`---> 出站{HTTP} <---公网---> 节点服务器 <---[::1]---> 入站{HTTP} <---[::1]---> 入站{VLESS over Reality} <---Routing---> 出站{Freedom}
```

和之前的 realtiy over socks5 想法一样

## 回到问题

后来因为[这个Discussions](https://github.com/XTLS/Xray-core/discussions/2172)，我发现了HTTP出站是可以设置 Headers 的，因为 User-Agent 太过显眼，所以我就在 HTTP 出站中添加了

<details open="true">

```json
"headers": {
    "User-Agent": "FAKEVALUE"
}
```

</details>

* 其中`FAKEVALUE`是为了保护隐私而设定的占位符，把它理解成这里该有的内容就可以了，以下也一样

VLESS的`streamSettings`出站配置如下

<details>

```json
"streamSettings": {
    "network": "h2",
    "httpSettings": {
        "host": [
            "FAKEVALUE"
        ],
        "path": "FAKEVALUE"
    },
    "security": "reality",
    "realitySettings": {
        "serverName": "FAKEVALUE",
        "fingerprint": "chrome",
        "shortID": "FAKEVALUE",
        "publicKey": "FAKEVALUE",
        "spiderX": "FAKEVALUE"
    },
    "sockopt": {
        "domainStrategy": "AsIs",
        "dialerProxy": "<出站 HTTP 标签>"
    }
}
```

</details>

当`network`为`h2`时，一旦有一个连接进入该出站，就会出现以下错误，随后程序崩溃

<details>

```console
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xac0608]

goroutine 15 [running]:
github.com/xtls/xray-core/proxy/http.fillRequestHeader({0x12f1ce0, 0xc00027cab0}, {0xc00014ac18?, 0x1, 0x0?})
        github.com/xtls/xray-core/proxy/http/client.go:179 +0xe8
github.com/xtls/xray-core/proxy/http.(*Client).Process(0xc0003549c0, {0x12f1ce0, 0xc00027cab0}, 0xc000d46100, {0x12e9860, 0xc000e5d300})
        github.com/xtls/xray-core/proxy/http/client.go:95 +0x41b
github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dispatch(0x0?, {0x12f1ce0, 0xc00027cab0}, 0xc000d46100)
        github.com/xtls/xray-core/app/proxyman/outbound/handler.go:201 +0x2a7
created by github.com/xtls/xray-core/transport/internet.redirect
        github.com/xtls/xray-core/transport/internet/dialer.go:122 +0x3f
```

</details>

我把多个协议测试了一下，结果如下

|   传输协议   |  结果  |
| :----------: | :----: |
|     TCP      |   ✔    |
|   HTTP/H2    |   ✖    |
|     gRPC     |   ✖    |
| DomainSocket | 未测试 |

如果把`outbounds`.`http`.`settings`.`headers`删掉或者把`outbounds`.`vless`.`streamSettings`.`network`改成`tcp`就不会报错，可以正常运行

# 完整配置

<details>

```json
{
    "log": {
        "access": "log\\access.log",
        "error": "log\\error.log",
        "loglevel": "error"
    },
    "routing": {
        "domainStrategy": "AsIs",
        "rules": [
            {
                "domain": [
                    // 略
                ],
                "outboundTag": "out-block",
                "type": "field"
            },
            {
                "domain": [
                    // 略
                ],
                "outboundTag": "out-reality-over-socks-node",
                "type": "field"
            },
            {
                "ip": [
                    // 略
                ],
                "outboundTag": "out-reality-over-socks-node",
                "type": "field"
            }
        ]
    },
    "inbounds": [
        {
            "protocol": "socks",
            "tag": "in-socks",
            "listen": "::1",
            "port": 0, // FAKEVALUE
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "tag": "out-direct"
        },
        {
            "protocol": "blackhole",
            "tag": "out-block"
        },
        // {
        //     "protocol": "socks",
        //     "tag": "out-reality-over-socks-socks",
        //     "settings": {
        //         "servers": [
        //             {
        //                 "address": "FAKEVALUE",
        //                 "port": 0, // FAKEVALUE
        //                 "users": [
        //                     {
        //                         "user": "FAKEVALUE",
        //                         "pass": "FAKEVALUE"
        //                     }
        //                 ]
        //             }
        //         ]
        //     }
        // },
        {
            "protocol": "http",
            "tag": "out-reality-over-socks-socks",
            "settings": {
                "servers": [
                    {
                        "address": "FAKEVALUE",
                        "port": 0, // FAKEVALUE
                        "users": [
                            {
                                "user": "FAKEVALUE",
                                "pass": "FAKEVALUE"
                            }
                        ]
                    }
                ],
                "headers": {
                    "User-Agent": "FAKEVALUE"
                }
            }
        },
        {
            "protocol": "vless",
            "tag": "out-reality-over-socks-node",
            "settings": {
                "vnext": [
                    {
                        "address": "FAKEVALUE",
                        "port": 443,
                        "users": [
                            {
                                "id": "FAKEVALUE",
                                "encryption": "none"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "h2",
                "httpSettings": {
                    "host": [
                        "FAKEVALUE"
                    ],
                    "path": "FAKEVALUE"
                },
                "security": "reality",
                "realitySettings": {
                    "serverName": "FAKEVALUE",
                    "fingerprint": "chrome",
                    "shortID": "FAKEVALUE",
                    "publicKey": "FAKEVALUE",
                    "spiderX": "FAKEVALUE"
                },
                "sockopt": {
                    "domainStrategy": "AsIs",
                    "dialerProxy": "out-reality-over-socks-socks"
                }
            }
        }
    ]
}
```

</details>

该问题是仅客户端的，不管有没有服务端连接都会出现该问题，所以服务端配置就不放出来了

<details open="true">

```console
D:\FAKEPATH>xray version
Xray 1.8.1 (Xray, Penetrates Everything.) Custom (go1.20.3 windows/amd64)
A unified platform for anti-censorship.
```

</details>

# 简单猜测
由于我是Java程序员，不能完全理解Go语言，但是我猜测应该是某处代码逻辑出了问题，导致变量或内存地址读取的问题

关键词：
* fillRequestHeader
* (*Client).Process
* transport/internet/dialer.go

**Comment by WordsWorthLess** [comment]
h2可以在streamSettings配置http_header,但是我没测试过
”streamSettings": {
"httpSettings": {
"headers": {
"User-Agent:":  [ "Mozilla/5.0 (iPhone; CPU iPhone OS 16_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15E148 Safari/604.1" ]
}
}
}

gRPC也能单独配置useragent的，这个我测试过是没问题的

“grpcSettings": {
"user_agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 16_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15E148 Safari/604.1"
}

**Comment by flowerinsnowdh** [comment]
> h2可以在streamSettings配置http_header,但是我没测试过 ”streamSettings": { "httpSettings": { "headers": { "User-Agent": [ "Mozilla/5.0 (iPhone; CPU iPhone OS 16_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15E148 Safari/604.1" ] } } }
> 
> gRPC也能单独配置useragent的，这个我测试过是没问题的
> 
> “grpcSettings": { "user_agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 16_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15E148 Safari/604.1" }

这么做就是 出站{REALITY} over 出站{HTTP} over H2/gRPC ，这个头添加的是在 H2 上的，而非 出站{HTTP} 上，也就是说 出站{HTTP} 还是原来的 UA ，这个UA只是改了最外层的底层传输协议

**Comment by us254** [comment]
The issue is that when you set the headers property on the http outbound protocol, it causes the program to crash if the streamSettings.network property is not set to tcp.

The reason for this is that the headers property is only used for HTTP connections, and if the streamSettings.network property is not set to tcp, then the connection will not be an HTTP connection.

To work around this issue, you can either set the streamSettings.network property to tcp or you can remove the headers property from the http outbound protocol.

**Comment by flowerinsnowdh** [comment]
> The issue is that when you set the headers property on the http outbound protocol, it causes the program to crash if the streamSettings.network property is not set to tcp.
> 
> The reason for this is that the headers property is only used for HTTP connections, and if the streamSettings.network property is not set to tcp, then the connection will not be an HTTP connection.
> 
> To work around this issue, you can either set the streamSettings.network property to tcp or you can remove the headers property from the http outbound protocol.

<hr />

说的并不完全对

<hr />

# 首先
根据OSI模型，传输层协议只有 TCP 和 UDP，其他协议都是传输层之上的，当底层传输协议为 H2/gRPC 时，真正的传输层还是TCP，当前模型应该是这样的

<details open="true">

```xml
<Physical_DataLink_Network>
    <Transport protocol="TCP">
        <Stream protocol="H2">
            <Outbound protocol="HTTP">
                <Outbound protocol="VLESS" security="REALITY">
                    True Data
                </Outbound>
            </Outbound>
        </Stream>
    </Transport>
</Physical_DataLink_Network>
```

</details>

* 为了方便理解和阅读，我写成了 XML 格式，请把它理解为网络模型

TCP 属于`传输层`，H2 属于`底层传输流层`，HTTP 属于`出站层`，它们不应该互相影响；如果把 H2 换成了 TCP，也仅仅只是把`底层传输流`层省去了而已

<hr />

# 其次
这个报错明显是程序 BUG，若非 BUG，应当在程序退出前有信息输出
