### ISSUE TITLE
设置mux的情况下，程序一旦发起udp就会崩溃

### ISSUE THREAD

**Issue by Smallthing** [XTLS/Xray-core#2180]
```

"streamSettings": {                                            
          "network": "h2",                                             
          "security": "reality",                                       
          "realitySettings": {                                         
            "show": false,                                             
            "publicKey": "xxxxxxxx",
            "shortId": "0123456789abcdef",                             
            "serverName": "",                         
            "fingerprint": "chrome",                                   
            "spiderX": "/"                                             
          }
        },
	"mux": {
                "enabled": true,
                "concurrency": -1,
                "xudpConcurrency": 1,
                "xudpProxyUDP443": "reject"
            }

```

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x70 pc=0x14e5cf5]

goroutine 79 [running]:
github.com/xtls/xray-core/common/session.(*Inbound).SetCanSpliceCopy(...)
        github.com/xtls/xray-core/common/session/session.go:59
github.com/xtls/xray-core/proxy/vless/outbound.(*Handler).Process(0xc0003bbdd0, {0x1c48d58, 0xc000304370}, 0xc000322120, {0x1c409a0, 0xc0003c8c80})
        github.com/xtls/xray-core/proxy/vless/outbound/outbound.go:162 +0xd35
github.com/xtls/xray-core/common/mux.(*DialingWorkerFactory).Create.func1({0x1ba6e204e58, 0xc0003bbdd0}, {0x1c409a0, 0xc0003c8c80}, {0x1c3a040, 0xc0003f22e8})
        github.com/xtls/xray-core/common/mux/client.go:156 +0x1c8
created by github.com/xtls/xray-core/common/mux.(*DialingWorkerFactory).Create
        github.com/xtls/xray-core/common/mux/client.go:150 +0x245

**Comment by Smallthing** [comment]
xudpConcurrency 设置为0则没问题
平台是 win11 x64

**Comment by us254** [comment]
If you are using Xray-core with H2, you should disable Mux by setting the mux.enabled setting to false. This will improve performance and avoid any potential bugs.
Mux should only be used with TCP, and H2 does not need mux.

**Comment by yuhan6665** [comment]
感谢反馈 你可以试一下这个action
https://github.com/XTLS/Xray-core/actions/runs/5172864225

**Comment by Smallthing** [comment]
> If you are using Xray-core with H2, you should disable Mux by setting the mux.enabled setting to false. This will improve performance and avoid any potential bugs. Mux should only be used with TCP, and H2 does not need mux.

I use it for udp

**Comment by Smallthing** [comment]
> 感谢反馈 你可以试一下这个action https://github.com/XTLS/Xray-core/actions/runs/5172864225

这个版本工作正常。

**Comment by Smallthing** [comment]
但是这个版本喷射战士会排不进队伍。改成 0 可以

**Comment by Smallthing** [comment]
先不发issue了 等1.8.x或者1.9正式版后 我再做测试
