### ISSUE TITLE
"rejectUnknownSNI" is missing in reality.

### ISSUE THREAD

**Issue by X-Oracle** [XTLS/Xray-core#2185]
Hi Guys.

I can't find the 'rejectUnknownSni' in reality ?
Is it missed by mistake or on purpose?
Would you please tell me the theory about it if it was on purpose?

Regards,

**Comment by RPRX** [comment]
REALITY 服务端只接受 `serverNames` 中有的 SNI，其它情况都应该交给 `dest` 处理
