### ISSUE TITLE
[讨论]请问有人做过IPV4 OVER IPV6的架构么

### ISSUE THREAD

**Issue by HEXtoDEC** [XTLS/Xray-core#2188]
如题，如果自己和服务器都有IPV6，是否有人尝试做过这种隧道，有什么坑点吗。

![BO336 )MW@)EV_DK$K5SNEH](https://github.com/XTLS/Xray-core/assets/14139451/7b844dd9-aeb3-46e7-b43b-4a63c61a6e1d)

我用工具转发，好像可以……

目前在服务器上使用SOCAT，监听一个端口，转发到XRAY端口。然后在IPV6栈上互联成功。

**Comment by qist** [comment]
XRAY 本身就可以双栈支持得啊。用你得v6 ip 连接就可以了。

**Comment by HEXtoDEC** [comment]
> XRAY 本身就可以双栈支持得啊。用你得v6 ip 连接就可以了。

确实。。。

我现在只要在软路由上面配个V6就完事了。。傻了我。
