### ISSUE TITLE
Google开发者网站显示403错误

### ISSUE THREAD

**Issue by ccimage** [XTLS/Xray-core#2189]
https://developer.android.com/
https://developer.google.com/
都是同样的问题
![image](https://github.com/XTLS/Xray-core/assets/1228378/cc5b57ac-9558-445f-844d-6306c1444a56)

这是什么问题呢？  
内核xray 1.7.5 （client, server both)  websocket
服务器上是x-ui安装的。 通过nginx中转，并且用cloudflare cdn加速
试过vless和vmess

服务器上用cutl访问上述地址，都是能成功的。

**Comment by zxbiao** [comment]
用XRAY 1.8.1可以访问
* 是不是VPS的IP不干净
* X-UI配置不正确
所以这个是算命issue，可以关了。

**Comment by ccimage** [comment]
> Use WARP for Google.
> 
> https://github.com/fscarmen/warp

这是自己部署warp服务吗？ 用原生warp基本上是很难连上的啊

**Comment by Fangliding** [comment]
> > Use WARP for Google.
> > https://github.com/fscarmen/warp
> 
> 这是自己部署warp服务吗？ 用原生warp基本上是很难连上的啊

cf官方的warp-cli代码很垃圾 仅此而已
warp都是官方warp 没有自己部署的说法

**Comment by ccimage** [comment]
谢谢各位 我研究一下。问题先关了
先试试升级xray，再试试用warp（看起来复杂点）
