### ISSUE TITLE
[update]xray绑定出站网卡为cloudflare warp 不走双栈

### ISSUE THREAD

**Issue by Extreme-Icer** [XTLS/Xray-core#2190]
~~sendthrough目前的设计只能有两个情况：一个是0000（或者是默认不用写），一个是绑定另一网卡（如wireguard）的**单个**IP。
那么有没有什么实现办法，让sendthrough支持绑定另一张网卡的all ips，或V4V6可以同时写？
分流就比较麻烦了，不好做双栈~~

Update：xray有一个streamSettings的sockopt，支持linux绑定网卡
经过实测，若绑定wireguard网卡，xray请求V6会提示网络不可用，V4正常。
VPS双栈。

**Comment by JimmyHuang454** [comment]
一个outbound只能绑定一个interface，你可以通过balancer选择不同的outboud

**Comment by ysmintor** [comment]
直接用interface指定warp网卡不就行吗？warp网卡上有ipv4和ipv6 @Extreme-Icer

**Comment by Extreme-Icer** [comment]
interface绑定是ipv4only
已经用wgcf替代了。

自我的 Galaxy 發送
