### ISSUE TITLE
WebRTC 会泄露client IP ?

### ISSUE THREAD

**Issue by tanbx** [XTLS/Xray-core#2191]
vps和客户端都用xray 1.8.1，采用过如下配置测试，都不能隐藏client IP
客户端用openwrt做的透明代理
1、vps用 nginx通过sni分流进入xray。用vless realtiy xtls-rprx-vision
2、xray直接处理vps一个外部端口。用realtiy xtls-rprx-vision
3、给vps 套用了cdn。用 vless ws tls

客户端把browserleaks.com域名纳入代理名单

在电脑上用egde和chrome浏览器访问 https://browserleaks.com/webrtc 做tcp指纹检查
它都能发现我的client IP
![xray_ip](https://github.com/XTLS/Xray-core/assets/108619712/99ac8bba-2ff0-4574-92ba-9225b4ba5c97)

**Comment by tanbx** [comment]
我对tcp技术不了解，也许这是通信必须的条件。但这样gwf是不是很容易发现呢？

**Comment by Fangliding** [comment]
webrtc漏的 和xray没关系 禁用webrtc

**Comment by Michaol** [comment]
没有问题，是你自己的WebRTC泄露，检查你自己的设置。
![微信图片_20230610103452](https://github.com/XTLS/Xray-core/assets/22289837/57301a2d-8df7-4940-9754-f5853a21f3b4)

**Comment by chika0801** [comment]
你在openwrt上面用的是什么插件如passwall ssrp ，你说清楚和你用的这些设置选项的关。

**Comment by tanbx** [comment]
浏览器可以配置，但其它应用它就不会泄露？还是在openwrt或vps上配置哪里可以把这个禁掉？

**Comment by tanbx** [comment]
openwrt 上用passwall

**Comment by chika0801** [comment]
> openwrt 上用passwall

把代理udp流量意思的选项选上后测试下

**Comment by tanbx** [comment]
确实，把passwall中的upd打开就不见了 client IP。
不懂原理，谢谢指点

**Comment by chika0801** [comment]
> 确实，把passwall中的upd打开就不见了 client IP。 不懂原理，谢谢指点

webrtc是用一个叫stun的协议样，这协议我搜了下是走在udp上。

当你插件中不选代理udp时，所以那些检测网站检查udp自然是你本机ip。大意是这样。

**Comment by tanbx** [comment]
vps中既然没用到udp，passwall中自然也就不开udp。没想到会这样。

非常感谢！

**Comment by chika0801** [comment]
插件中，你要开代理udp流量，还有个情景是你要打游戏，所以要代理udp流量。

webrtc泄露这事一些ytb上的up主在发（赚流量=钱） 一些检测泄露网站有这项目（是为推销vpn为主目的）

**Comment by tanbx** [comment]
但它确实会泄露client IP，所以我们配置vps和client看来都应该把udp配上，用不用另一回事，安全才最重要。

**Comment by chika0801** [comment]
webtrc泄露你不管也没啥，不要给自己制造太多焦虑。
你要看，不代理udp，在chrome安个插件也能解决。

**Comment by tanbx** [comment]
如果gwf在国外做个网站来检测，然后用某些钓鱼方法或在你的电脑中植入些东西，那就是裸奔了。我觉得就是个安全漏洞，需要提醒配置的人关注。

**Comment by chika0801** [comment]
看个人想法吧，对了你把标题改下得了，你搞懂原理了，建议别标题党

**Comment by Fangliding** [comment]
@tanbx 这个会漏本地IP
实际上就大多数人绕过大陆的路由配置大多数都是漏的()

**Comment by ycy-contribution** [comment]
嗯，确实会泄漏的，而且WebRTC作为浏览器默认开启的功能，各种终端也不一定都好关。
在考虑攻击者可以对网站进行注入的情况下，好端端的你把WebRTC功能关了也足以让人怀疑你在翻墙。

**Comment by red-co** [comment]
@ycy-contribution 可webrtc不关，就不需要怀疑了，看到了你挂的代理和原始ip，直接把你封了。

**Comment by red-co** [comment]
这是需要对webRTC进行一定程度的伪装
