### ISSUE TITLE
一个似乎不是太重要的warning

### ISSUE THREAD

**Issue by AIDA64S** [XTLS/Xray-core#2196]
(理论上这个issue应该在Reality的)

`app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [REALITY: processed invalid connection] > common/retry: all retry attempts failed`

VPS是hostEONS的垃圾OpenVZ，服务器使用Ubuntu 22.04，使用xray-install安装核心(最新beta1.8.1)，使用最新版的x-ui。
协议是VLESS+TCP+Reality，服务端和客户端的shortID都为0，监听地址0.0.0.0，端口443，使用xtls-rerx-version流控,没有设置fallback。服务器和电脑都时间同步。

客户端日志中很常见此类warning，但似乎不影响连接，研究了一下午实在没找到这个warning出现的原因，如果大佬们看到了且已经知道此问题原因，能告诉一下小弟，小弟感激不尽

**Comment by RPRX** [comment]
> common/retry: all retry attempts failed

> VPS是hostEONS的垃圾OpenVZ

线路垃圾导致偶尔连不上

**Comment by AIDA64S** [comment]
补充，x-ui的日志中一直在warning
`get xray traffic failed: rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: EOF"`

**Comment by chika0801** [comment]
建议，只要你日常开网页没发现什么异常，不看日志即可没这些烦恼。

**Comment by AIDA64S** [comment]
服务端的配置
`{
  "log": null,
  "routing": {
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ]
  },
  "dns": null,
  "inbounds": [
    {
      "listen": "0.0.0.0",
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "模板uuid",
            "flow": "xtls-rprx-vision"
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "show": false,
          "dest": "www.microsoft.com:443",
          "xver": 0,
          "serverNames": [
            "www.microsoft.com"
          ],
          "privateKey": "模板私钥",
          "minClientVer": "",
          "maxClientVer": "",
          "maxTimeDiff": 0,
          "shortIds": [
            ""
          ]
        }
      },
      "tag": "api",
      "sniffing": null
    },
    {
      "listen": "0.0.0.0",
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "实际用户uuid",
            "email": "实际用户邮箱",
            "flow": "xtls-rprx-vision"
          }
        ],
        "decryption": "none",
        "fallbacks": []
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "show": false,
          "dest": "www.microsoft.com:443",
          "xver": 0,
          "serverNames": [
            "www.microsoft.com"
          ],
          "privateKey": "实际私钥",
          "publicKey": "实际公钥",
          "minClient": "",
          "maxClient": "",
          "maxTimediff": 0,
          "shortIds": [
            ""
          ]
        },
        "tcpSettings": {
          "header": {
            "type": "none"
          },
          "acceptProxyProtocol": false
        }
      },
      "tag": "inbound-443",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "transport": null,
  "policy": {
    "levels": {
      "0": {
        "handshake": 10,
        "connIdle": 100,
        "uplinkOnly": 2,
        "downlinkOnly": 3,
        "statsUserUplink": true,
        "statsUserDownlink": true,
        "bufferSize": 10240
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "stats": {},
  "reverse": null,
  "fakeDns": null
}`

**Comment by AIDA64S** [comment]
> 



> 建议，只要你每天打开网页没有发现什么异常，不看日期志即可没有这些烦恼。



> 建议，只要你日常开网页没发现什么异常，不看日志即可没这些烦恼。

使用上当然是这样的，只不过还是很想知道原因(学软件的执念)，顺道来看看有没有人有类似的情况，如果大佬们太忙就直接忽略

**Comment by chika0801** [comment]
那你买个好回程线程的vps，不要用xui了，自建一下 dest不要用默认软件的，自己找个再观察下了。

**Comment by AIDA64S** [comment]
看x-ui的warning，看起来应该是流量监控部分没设置好

**Comment by RPRX** [comment]
我不知道你用 Xray 或 v2 多久了，线路垃圾时，偶尔有一个连接没成功然后报这种错是很常见的，这是常识，大家都见过

你可以 ping 服务器 IP，看看是不是偶尔丢个包

**Comment by AIDA64S** [comment]
啊搞糊涂了，纠正一点，今天换的这个VLESS+Reality的服务器是阿里云，没有也无需套用CDN的，质量还是挺不错的，只是今天刚换协议(以前用的Trojan端口最近封的厉害)

**Comment by chika0801** [comment]
所以建议不要管日志

**Comment by Fangliding** [comment]
经典理论
能连上就别管（）

**Comment by AIDA64S** [comment]
哈哈哈，好的，不过还是谢谢各位了

**Comment by RPRX** [comment]
不建议用阿里云、腾讯云等。

这个 warning 只有三种可能：

1. 线路丢包，概率最大
2. GFW 搞事，概率最小
3. `dest` 不给力，~~其实我不确定它会不会导致这个 warning，有段时间没看代码了~~

**Comment by AIDA64S** [comment]
以上问题以解决，可以关闭

**Comment by HANS-555** [comment]
怎么解决的。我也遇到同样的问题。全部丢包。正常用了一天。其他的连不上。

**Comment by chika0801** [comment]
> 怎么解决的。我也遇到同样的问题。全部丢包。正常用了一天。其他的连不上。

你要学如何排查VPS的端口是否被封，你遇到的和这楼主提的问题不一样。

**Comment by HANS-555** [comment]
报同样的错。我走IPV6去YOUTUBE连不上。GOOGLE  NETFLIX正常。难道YOUTUBE封我的IPV6？3台机子的IPV6都不能上。不可能3台一起封这么巧吧。我换回IPV4就能正常上。我到现在都没搞懂是什么原因。我觉得封端口的可能性不大。因为3台一起封不可能。

**Comment by chika0801** [comment]
你走ipv6去是什么意思？你是不是路由器刷op，用ssrp passwall插件，手机接wifi翻墙遇到的？

**Comment by like99168** [comment]
> 哈哈哈，好的，不过还是谢谢各位了

 X-UI: Failed to fetch Xray traffic:rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: EOF"

我也遇到这个问题了，请问您是如何解决的，谢谢
