### ISSUE TITLE
用http强制访问tls端口时nginx和xray的表现不同

### ISSUE THREAD

**Issue by secXsQuared** [XTLS/Xray-core#220]
机器A：nginx + ssl @ 443
机器B：xray + tls + fallback to 80 + nginx plain http @ 80 

然后从浏览器访问http://A:443和http://B:443. 这时候A机器显示“400 Bad Request The plain HTTP request was sent to HTTPS port"

B会等上大概3-5秒然后显示connection reset. Log里是"app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > tls: first record does not look like a TLS handshake"

https两个机器的表现一样, 都能访问到网页。

就是想问一下这个是nginx default config还是说nginx在发现有http发到https口自动返回HTTP 400，如果是后者的话GFW用http来探测443口是否可以区分真正的webserver和xray。还是说只有nginx这样干，apache和caddy的表现是否和xray的一致？

**Comment by rprx** [comment]
https://github.com/XTLS/Xray-core/issues/214#issuecomment-769143311

**Comment by whoshoe** [comment]
> 机器A：nginx + ssl @ 443
> 机器B：xray + tls + fallback to 80 + nginx plain http @ 80
> 
> 然后从浏览器访问[http://A:443和http://B:443](http://A:443%E5%92%8Chttp://B:443). 这时候A机器显示“400 Bad Request The plain HTTP request was sent to HTTPS port"
> 
> B会等上大概3-5秒然后显示connection reset. Log里是"app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > tls: first record does not look like a TLS handshake"
> 
> https两个机器的表现一样, 都能访问到网页。
> 
> 就是想问一下这个是nginx default config还是说nginx在发现有http发到https口自动返回HTTP 400，如果是后者的话GFW用http来探测443口是否可以区分真正的webserver和xray。还是说只有nginx这样干，apache和caddy的表现是否和xray的一致？

如果你nginx没有设置http自动301到https的话nginx和xray的表现是一致的。即用http:443强制访问的时候都是返回ERR_EMPTY_RESPONSE。

**Comment by flyawayazure** [comment]
@whoshoe trijan-go可以解决类似的问题，可以考虑下（

**Comment by whoshoe** [comment]
> @whoshoe trijan-go可以解决类似的问题，可以考虑下（

伪装站没必要设置http跳转https，无指纹所以不构成一个问题。

**Comment by secXsQuared** [comment]
好的，谢谢解答，没指纹我就放心了! closing.

**Comment by rprx** [comment]
上面的讨论有点奇怪，看我在 #214 中的回复即可。

**Comment by secXsQuared** [comment]
TLDR:

http到https口不需要返回400，tls可以选择切断链接，这不能作为指纹。
