### ISSUE TITLE
gRPC  + acceptProxyProtocol --> not working

### ISSUE THREAD

**Issue by hiddify-com** [XTLS/Xray-core#2204]
I understand that gRPC+acceptProxyProtocol behind haproxy will not work and based on the documentation there is no acceptProxyProtocol in the grpcSettings and even using "sockopt": {
    "acceptProxyProtocol": true  }, will not work.

Is it possiblle to use acceptProxyProtocol=true with gRPC?

**Comment by chika0801** [comment]
Can you provide some specific configuration examples? For instance, when you mention HAProxy listening on a port with Xray as the backend?

I'm not familiar with HAProxy as I don't use it. If you can provide more detailed information, perhaps someone else can assist you.

**Comment by cty123** [comment]
I believe this is related to #2232. Could you pull the latest version of xray-core and try again.

**Comment by Benjamin1919** [comment]
Do not use 
```
"sockopt": {
  "acceptProxyProtocol": true
}
```
when you have a nginx/caddy proxy ahead gRPC/websocket/httpupgrade
