### ISSUE TITLE
Problem with grpc api

### ISSUE THREAD

**Issue by ezioadf2** [XTLS/Xray-core#2215]
Hi
Im devloping an v2ray pannel for  with node.js but doc is very bad,there is a func called toTypedMessage, i cant understand why developer used it,  when we have a proto file standard with normal data type like string,int or etc why developer used a code from golang where we want set a variable for api, for this method i cant develop pannel with node.js, is there any alternarive?
[toTypedMessage File](https://github.com/XTLS/Xray-core/blob/main/common/serial/typed_message.go) 
[Api examples where method used](https://github.com/XTLS/Xray-API-documents/blob/main/examples/addInbound.go)

**Comment by sudospaes** [comment]
did you find a way ?
Its seem you should use grpc api for use that
