### ISSUE TITLE
禁用回国流量无效

### ISSUE THREAD

**Issue by toyo2333** [XTLS/Xray-core#2223]
```
{
  "routing": {
    "rules": [
	  {
        "type": "field",
        "outboundTag": "IP4_out",
        "domain": [
			"p3terx.com",
			"ip6.me"
        ]
      },
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private","geoip:cn"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
    {
        "type": "field",
        "outboundTag": "blocked",
        "domain": [
		"geosite:category-ads-all"
        ]
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ]
  },
  "stats": {}
}
```
客户端开全局代理，然后浏览器输入baidu.com 发现还是可以打开的。

我在vps上ping了下baidu.com 也是国内ip，按理说应该要屏蔽啊，但没有。

正确的屏蔽回国流量的做法应该是怎样的？

**Comment by toyo2333** [comment]
> 发服务端完整配置才能全面分析
> 
> 猜是要入站加域名嗅探
> 
> 路由的策略用 https://github.com/chika0801/Xray-examples/blob/main/VLESS-XTLS-Vision/config_server.json#L6

感谢回复解答。我知道原因了。因为我没有写        "domainStrategy": "IPIfNonMatch",这就是的默认路由域名解析策略是是域名就规则走完就出站了，而不会走到ip规则命中我封锁回国流量的设置。

我现在有两个做法，
1，就是加上上面这个，但这个感觉会有性能开销。因为每个域名都要去做一次域名解析后再查一边ip规则。
2，直接换用geosite:cn,放到域名规则里。

我们目前改为了2了，有效。再次感谢。另外，我不知道我对于做法1的        "domainStrategy": "IPIfNonMatch",的性能开销担心是否是成立的？还是我多虑了？

**Comment by chika0801** [comment]
domainStrategy": "IPIfNonMatch",的性能开销

建议不要在意，你给商家vps节约cpu干嘛。

建议不要用geosite cn阻止，如果你是用的加强版geo且你没细读它readme时。你可能会用了客户端遇到莫名现象

**Comment by toyo2333** [comment]
> domainStrategy": "IPIfNonMatch",的性能开销
> 
> 建议不要在意，你给商家vps节约cpu干嘛。
> 
> 建议不要用geosite cn阻止，如果你是用的加强版geo且你没细读它readme时。你可能会用了客户端遇到莫名现象

好已经改好了。

大佬，我之所以搞这个是因为昨天443端口被封了，用的vless+ws+tls+Web前置 的方式。所以这次改的再严谨一点。

也有人给我推荐新协议，在想如果想试试新协议，该怎么选呢？好复杂好乱

VLESS-XTLS-Vision 
VLESS-XTLS-uTLS-REALITY
VLESS-gRPC-uTLS-REALITY

还有什么偷自己的组合。

换一个ip要5刀，不想折腾。求给一步到位的方案。谢谢！

**Comment by chika0801** [comment]
你用ws tls 被封443可能和这禁回国关系不大，和用ws tls关系大些。

VLESS-XTLS-Vision
VLESS-XTLS-uTLS-REALITY

2选1了，不想学reality相关就换成VLESS-XTLS-Vision

**Comment by chika0801** [comment]
你443被封换端口继续用，不必花钱找商家换ip。你懒连ws tls都不用换，遇到被封端口再换其它端口，反正gfw也只是封你端口，你只要哪天客户端不通时，自己会排查，有动手能力就是了。

**Comment by chika0801** [comment]
> > 你443被封换端口继续用，不必花钱找商家换ip。你懒连ws tls都不用换，遇到被封端口再换其它端口，反正gfw也只是封你端口，你只要哪天客户端不通时，自己会排查，有动手能力就是了。
> 
> 谢谢指路，我看到个说法，就是同一个ip，如果封过一次端口，换了再封几次的话，ip就没了。相当于多折腾几次而已，最终难逃一死。
> 
> 另外，cdn也能解决，但我不想用cdn，线路本身还可以。没必要负优化。

我有的机去年10月开的trojan tcp tls组合形式被封端口数量10秒以上，ip都一直正常的。你大胆试ip不是你的，不要爱惜商家的机子ip和端口即可

**Comment by Kikyo-chan** [comment]
这几天我的（Hosteons 家买的的103.114.X.X拉斯维加斯）VPS常用端口（443，8443）也封了，我使用的是VLESS-XTLS-uTLS-REALITY,不过我在换了几个大端口就可以了，好像隐隐感觉大事不妙了。

**Comment by toyo2333** [comment]
> 这几天我的（Hosteons 家买的的103.114.X.X拉斯维加斯）VPS常用端口（443，8443）也封了，我使用的是VLESS-XTLS-uTLS-REALITY,不过我在换了几个大端口就可以了，好像隐隐感觉大事不妙了。

怕了。那reality官方到底推荐用什么端口呢？

**Comment by toyo2333** [comment]
> > > 你443被封换端口继续用，不必花钱找商家换ip。你懒连ws tls都不用换，遇到被封端口再换其它端口，反正gfw也只是封你端口，你只要哪天客户端不通时，自己会排查，有动手能力就是了。
> 
> > 
> 
> > 谢谢指路，我看到个说法，就是同一个ip，如果封过一次端口，换了再封几次的话，ip就没了。相当于多折腾几次而已，最终难逃一死。
> 
> > 
> 
> > 另外，cdn也能解决，但我不想用cdn，线路本身还可以。没必要负优化。
> 
> 
> 
> 我有的机去年10月开的trojan tcp tls组合形式被封端口数量10秒以上，ip都一直正常的。你大胆试ip不是你的，不要爱惜商家的机子ip和端口即可

大佬，我想问 代理客户端正确的使用姿势是怎样的。我前几天都是手机一直开着，12 24小时开着这样。这种会不会不好？

另外，客户端本身是否有可能有漏洞暴露特征。我用过火箭 stash 和最近新装的pharos

**Comment by Axe-l** [comment]
<img width="399" alt="image" src="https://github.com/XTLS/Xray-core/assets/45731066/0ffe0b8d-9ef9-4e94-b182-3223124fc9dc">
<img width="569" alt="image" src="https://github.com/XTLS/Xray-core/assets/45731066/cf2c82f9-3158-44a5-ac6c-40f8c6c9a542">

我改这样ping百度也是国内的ip啊？？

**Comment by toyo2333** [comment]
> <img width="399" alt="image" src="https://github.com/XTLS/Xray-core/assets/45731066/0ffe0b8d-9ef9-4e94-b182-3223124fc9dc">
> 
> <img width="569" alt="image" src="https://github.com/XTLS/Xray-core/assets/45731066/cf2c82f9-3158-44a5-ac6c-40f8c6c9a542">
> 
> 
> 
> 我改这样ping百度也是国内的ip啊？？
你改好后，客户端开启全局，然后打开百度应该就打不开了这个时候浏览器地址栏baidu.com会变成www.baidu.com 你在vps上ping后者，得到的IP应该是百度香港ip。同理你打开jd.com应该会跳到globe.jd.com。这些是做了区分的。其它没有专门为国外IP做优化的网站 比如豆瓣 一些什么的 应该就直接打不开了。这是预期效果。

**Comment by chika0801** [comment]
> 我改这样ping百度也是国内的ip啊？？

你说清楚你本地电脑是HTTP SOCKS代理？你PING用的什么程序，这程序 走到代理没有之类才能分析

**Comment by hhhflow2020** [comment]
> https://github.com/chika0801/Xray-install

啥端口都行 都是平等的

**Comment by cola77777** [comment]
{
        "type": "field",
        "outboundTag": "blocked",
        "domain": [
          "geosite:cn",
          "geosite:geolocation-cn"
        ]
      }
