### ISSUE TITLE
无法注册netflix，是netflix检测到xray代理了禁止注册吗？

### ISSUE THREAD

**Issue by ynhzzu** [XTLS/Xray-core#2224]
<img width="970" alt="image" src="https://github.com/XTLS/Xray-core/assets/15062203/5120ed79-5f1f-4c45-8755-bfe5c2aa4194">

**Comment by ynhzzu** [comment]
服务器ip是新加坡，已经用nf工具检测了，可以观看netflix。

**Comment by chika0801** [comment]
发你服务端配置

**Comment by ynhzzu** [comment]
> 

{
    "log":{
        "access":"/var/log/xray/access.log",
        "error":"/var/log/xray/error.log",
        "loglevel":"warning"
    },
    "dns":{
        "servers":[
            "https+local://1.1.1.1/dns-query",
            "localhost"
        ]
    },
    "routing":{
        "domainStrategy":"AsIs",
        "rules":[
            {
                "type":"field",
                "ip":[
                    "geoip:private"
                ],
                "outboundTag":"block"
            },
            {
                "type":"field",
                "domain":[
                    "domain:google.com"
                ],
                "outboundTag":"direct"
            },
	    {
                "type":"field",
                "domain":[
                    "domain:netflix.com"
                ],
                "outboundTag":"ip6-out"
            }
        ]
    },
    "inbounds":[
        {
            "listen":"0.0.0.0",
            "port":60443,
            "protocol":"vless",
            "settings":{
                "clients":[
                    {
                        "id":"***",
                        "flow":"xtls-rprx-vision"
                    }
                ],
                "decryption":"none",
                "fallbacks":[
                    {
                        "dest":"8081",
                        "xver":1
                    },
                    {
                        "alpn":"h2",
                        "dest":"8082",
                        "xver":1
                    }
                ]
            },
            "streamSettings":{
                "network":"tcp",
                "security":"tls",
                "tlsSettings":{
                    "rejectUnknownSni":true,
                    "minVersion":"1.2",
                    "certificates":[
                        {
                            "ocspStapling":3600,
                            "certificateFile":"/etc/xray/certificate.crt",
                            "keyFile":"/etc/xray/private.key"
                        }
                    ]
                }
            },
            "sniffing":{
                "enabled":true,
                "destOverride":[
                    "http",
                    "tls"
                ]
            }
        }
    ],
    "outbounds":[
        {
            "protocol":"freedom",
            "tag":"direct"
        },
        {
            "protocol":"blackhole",
            "tag":"block"
        },
        {
            "protocol":"freedom",
            "settings":{
                "domainStrategy":"UseIPv4"
            },
            "tag":"ip4-out"
        },
	{
            "protocol":"freedom",
            "settings":{
                "domainStrategy":"UseIPv6"
            },
            "tag":"ip6-out"
        }
    ],
    "policy":{
        "levels":{
            "0":{
                "handshake":1,
                "connIdle":100
            }
        }
    }
}

**Comment by ynhzzu** [comment]
<img width="556" alt="image" src="https://github.com/XTLS/Xray-core/assets/15062203/b4d02e90-4010-4f46-8d45-52c4ed2e502f">

**Comment by chika0801** [comment]
"domain:netflix.com"

改成 geosite:netflix 试试

要改，还不行，要分析，日志级别开debug，访问 nf ，发日志部分来看看

**Comment by ynhzzu** [comment]
2023/06/19 18:06:58 [Info] [1802033341] proxy/vless/inbound: firstLen = 1186
2023/06/19 18:06:58 [Info] [1802033341] proxy/vless/inbound: received request for tcp:www.google.com:443
2023/06/19 18:06:58 [Info] [1802033341] proxy/vless/encoding: Xtls Unpadding new block0 16 content 517 padding 844 0
2023/06/19 18:06:58 [Info] [1802033341] proxy/vless/encoding: XtlsFilterTls found tls client hello! 517
2023/06/19 18:06:58 [Info] [1802033341] app/dispatcher: sniffed domain: www.google.com
2023/06/19 18:06:58 [Info] [1802033341] app/dispatcher: taking detour [direct] for [tcp:www.google.com:443]
2023/06/19 18:06:58 [Info] [1802033341] proxy/freedom: opening connection to tcp:www.google.com:443
2023/06/19 18:06:58 [Info] [1802033341] transport/internet/tcp: dialing TCP to tcp:www.google.com:443
2023/06/19 18:06:58 [Debug] transport/internet: dialing to tcp:www.google.com:443
2023/06/19 18:06:58 [Info] [1802033341] proxy/vless/encoding: XtlsFilterTls found tls 1.3! 4449 TLS_AES_128_GCM_SHA256
2023/06/19 18:06:58 [Info] [1802033341] proxy/vless/encoding: XtlsPadding 4449 32 0
2023/06/19 18:06:59 [Info] [1802033341] proxy/vless/encoding: Xtls Unpadding new block0 0 content 74 padding 1297 0
2023/06/19 18:07:04 [Info] [3258127896] proxy/vless/inbound: firstLen = 1163
2023/06/19 18:07:04 [Info] [3258127896] proxy/vless/inbound: received request for tcp:ichnaea-web.netflix.com:443
2023/06/19 18:07:04 [Info] [3258127896] proxy/vless/encoding: Xtls Unpadding new block0 16 content 517 padding 561 0
2023/06/19 18:07:04 [Info] [3258127896] proxy/vless/encoding: XtlsFilterTls found tls client hello! 517
2023/06/19 18:07:04 [Info] [3258127896] app/dispatcher: sniffed domain: ichnaea-web.netflix.com
2023/06/19 18:07:04 [Info] [3258127896] app/dispatcher: taking detour [ip6-out] for [tcp:ichnaea-web.netflix.com:443]
2023/06/19 18:07:04 [Info] [3258127896] proxy/freedom: opening connection to tcp:ichnaea-web.netflix.com:443
2023/06/19 18:07:04 [Debug] app/dns: domain ichnaea-web.netflix.com will use DNS in order: [DOHL//1.1.1.1 localhost]
2023/06/19 18:07:04 [Info] app/dns: DOHL//1.1.1.1 querying: ichnaea-web.netflix.com.
2023/06/19 18:07:04 [Debug] transport/internet: dialing to tcp:1.1.1.1:443
2023/06/19 18:07:04 [Info] app/dns: DOHL//1.1.1.1 got answer: ichnaea-web.netflix.com. TypeAAAA -> [[2620:108:700f::23a1:7bd2] [2620:108:700f::340c:bca9] [2620:108:700f::3428:de2f] [2620:108:700f::22d2:a36f] [2620:108:700f::2352:a7d8] [2620:108:700f::23a5:9c56] [2620:108:700f::2cf0:59b2] [2620:108:700f::3695:afdf]] 12.385405ms
2023/06/19 18:07:04 [Info] [3258127896] proxy/freedom: dialing to tcp:[2620:108:700f::2cf0:59b2]:443
2023/06/19 18:07:04 [Info] [3258127896] transport/internet/tcp: dialing TCP to tcp:[2620:108:700f::2cf0:59b2]:443
2023/06/19 18:07:04 [Debug] transport/internet: dialing to tcp:[2620:108:700f::2cf0:59b2]:443
2023/06/19 18:07:04 [Info] [2170743662] proxy/vless/inbound: firstLen = 1186
2023/06/19 18:07:04 [Info] [2170743662] proxy/vless/inbound: received request for tcp:www.facebook.com:443
2023/06/19 18:07:04 [Info] [2170743662] proxy/vless/encoding: Xtls Unpadding new block0 16 content 517 padding 807 0
2023/06/19 18:07:04 [Info] [2170743662] proxy/vless/encoding: XtlsFilterTls found tls client hello! 517
2023/06/19 18:07:04 [Info] [2170743662] app/dispatcher: sniffed domain: www.facebook.com
2023/06/19 18:07:04 [Info] [2170743662] app/dispatcher: default route for tcp:www.facebook.com:443
2023/06/19 18:07:04 [Info] [2170743662] proxy/freedom: opening connection to tcp:www.facebook.com:443
2023/06/19 18:07:04 [Info] [2170743662] transport/internet/tcp: dialing TCP to tcp:www.facebook.com:443
2023/06/19 18:07:04 [Debug] transport/internet: dialing to tcp:www.facebook.com:443
2023/06/19 18:07:04 [Info] [2170743662] proxy/vless/encoding: XtlsFilterTls found tls 1.3! 212 TLS_AES_128_GCM_SHA256
2023/06/19 18:07:04 [Info] [2170743662] proxy/vless/encoding: XtlsPadding 212 1023 0
2023/06/19 18:07:04 [Info] [3258127896] proxy/vless/encoding: XtlsFilterTls found tls 1.2! 3456
2023/06/19 18:07:04 [Info] [3258127896] proxy/vless/encoding: XtlsPadding 3456 94 0
2023/06/19 18:07:04 [Info] [2170743662] proxy/vless/encoding: Xtls Unpadding new block0 0 content 668 padding 705 0
2023/06/19 18:07:04 [Info] [2170743662] proxy/vless/encoding: XtlsPadding 245 828 2
2023/06/19 18:07:04 [Info] [2170743662] proxy/vless/encoding: XtlsWrite writeV 0 1078 0
2023/06/19 18:07:05 [Info] [3258127896] proxy/vless/encoding: Xtls Unpadding new block0 0 content 126 padding 1103 0
2023/06/19 18:07:05 [Info] [2170743662] proxy/vless/encoding: Xtls Unpadding new block0 0 content 31 padding 973 2
2023/06/19 18:07:05 [Info] [2170743662] proxy/vless/encoding: XtlsRead readV
2023/06/19 18:07:05 [Info] [3258127896] proxy/vless/encoding: XtlsPadding 51 872 0
2023/06/19 18:07:05 [Info] [3258127896] proxy/vless/encoding: Xtls Unpadding new block0 0 content 608 padding 636 1
2023/06/19 18:07:05 [Info] [3258127896] proxy/vless/encoding: XtlsPadding 1416 90 1
2023/06/19 18:07:07 [Info] [764355386] proxy/vless/inbound: firstLen = 993
2023/06/19 18:07:07 [Info] [764355386] proxy/vless/inbound: received request for tcp:ichnaea-web.netflix.com:443
2023/06/19 18:07:07 [Info] [764355386] proxy/vless/encoding: Xtls Unpadding new block0 16 content 517 padding 391 0
2023/06/19 18:07:07 [Info] [764355386] proxy/vless/encoding: XtlsFilterTls found tls client hello! 517
2023/06/19 18:07:07 [Info] [764355386] app/dispatcher: sniffed domain: ichnaea-web.netflix.com
2023/06/19 18:07:07 [Info] [764355386] app/dispatcher: taking detour [ip6-out] for [tcp:ichnaea-web.netflix.com:443]
2023/06/19 18:07:07 [Info] [764355386] proxy/freedom: opening connection to tcp:ichnaea-web.netflix.com:443
2023/06/19 18:07:07 [Debug] app/dns: domain ichnaea-web.netflix.com will use DNS in order: [DOHL//1.1.1.1 localhost]
2023/06/19 18:07:07 [Debug] app/dns: DOHL//1.1.1.1 cache HIT ichnaea-web.netflix.com -> [2620:108:700f::23a1:7bd2 2620:108:700f::340c:bca9 2620:108:700f::3428:de2f 2620:108:700f::22d2:a36f 2620:108:700f::2352:a7d8 2620:108:700f::23a5:9c56 2620:108:700f::2cf0:59b2 2620:108:700f::3695:afdf]
2023/06/19 18:07:07 [Info] [764355386] proxy/freedom: dialing to tcp:[2620:108:700f::23a1:7bd2]:443
2023/06/19 18:07:07 [Info] [764355386] transport/internet/tcp: dialing TCP to tcp:[2620:108:700f::23a1:7bd2]:443
2023/06/19 18:07:07 [Debug] transport/internet: dialing to tcp:[2620:108:700f::23a1:7bd2]:443
2023/06/19 18:07:09 [Info] [764355386] proxy/vless/encoding: XtlsFilterTls found tls 1.2! 3456
2023/06/19 18:07:09 [Info] [764355386] proxy/vless/encoding: XtlsPadding 3456 192 0
2023/06/19 18:07:09 [Info] [1750764842] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to transfer request payload > read tcp 127.0.0.1:60443->127.0.0.1:53768: read: connection reset by peer
2023/06/19 18:07:09 [Info] [764355386] proxy/vless/encoding: Xtls Unpadding new block0 0 content 126 padding 1260 0
2023/06/19 18:07:09 [Info] [764355386] proxy/vless/encoding: XtlsPadding 51 975 0
2023/06/19 18:07:10 [Info] [764355386] proxy/vless/encoding: Xtls Unpadding new block0 0 content 1295 padding 98 1
2023/06/19 18:07:10 [Info] [3258127896] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > context canceled
2023/06/19 18:07:11 [Info] [3613849341] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > context canceled
2023/06/19 18:07:11 [Info] [680227104] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > context canceled
2023/06/19 18:07:14 [Info] [300347530] proxy/vless/inbound: firstLen = 1170
2023/06/19 18:07:14 [Info] [300347530] proxy/vless/inbound: received request for tcp:clients4.google.com:443
2023/06/19 18:07:14 [Info] [300347530] proxy/vless/encoding: Xtls Unpadding new block0 16 content 517 padding 572 0
2023/06/19 18:07:14 [Info] [300347530] proxy/vless/encoding: XtlsFilterTls found tls client hello! 517
2023/06/19 18:07:14 [Info] [300347530] app/dispatcher: sniffed domain: clients4.google.com
2023/06/19 18:07:14 [Info] [300347530] app/dispatcher: taking detour [direct] for [tcp:clients4.google.com:443]
2023/06/19 18:07:14 [Info] [300347530] proxy/freedom: opening connection to tcp:clients4.google.com:443
2023/06/19 18:07:14 [Info] [300347530] transport/internet/tcp: dialing TCP to tcp:clients4.google.com:443
2023/06/19 18:07:14 [Debug] transport/internet: dialing to tcp:clients4.google.com:443
2023/06/19 18:07:14 [Info] [300347530] proxy/vless/encoding: XtlsFilterTls found tls 1.3! 6942 TLS_AES_128_GCM_SHA256
2023/06/19 18:07:14 [Info] [300347530] proxy/vless/encoding: XtlsPadding 6942 217 0
2023/06/19 18:07:14 [Info] [764355386] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > context canceled
2023/06/19 18:07:14 [Info] [300347530] proxy/vless/encoding: Xtls Unpadding new block0 0 content 74 padding 1313 0
2023/06/19 18:07:14 [Info] [300347530] proxy/vless/encoding: Xtls Unpadding new block0 0 content 2350 padding 63 2
2023/06/19 18:07:14 [Info] [300347530] proxy/vless/encoding: XtlsRead readV
2023/06/19 18:07:14 [Info] [300347530] proxy/vless/encoding: XtlsPadding 966 141 2
2023/06/19 18:07:14 [Info] [300347530] proxy/vless/encoding: XtlsWrite writeV 0 1112 0
2023/06/19 18:07:29 [Debug] app/dns: DOHL//1.1.1.1 cleanup ichnaea-web.netflix.com.
2023/06/19 18:07:38 [Info] [2629711719] proxy/vless/inbound: firstLen = 1186
2023/06/19 18:07:38 [Info] [2629711719] proxy/vless/inbound: received request for tcp:www.netflix.com:443
2023/06/19 18:07:38 [Info] [2629711719] proxy/vless/encoding: Xtls Unpadding new block0 16 content 536 padding 603 0
2023/06/19 18:07:38 [Info] [2629711719] proxy/vless/encoding: XtlsFilterTls found tls client hello! 536
2023/06/19 18:07:38 [Info] [2629711719] app/dispatcher: sniffed domain: www.netflix.com
2023/06/19 18:07:38 [Info] [2629711719] app/dispatcher: taking detour [ip6-out] for [tcp:www.netflix.com:443]
2023/06/19 18:07:38 [Info] [2629711719] proxy/freedom: opening connection to tcp:www.netflix.com:443
2023/06/19 18:07:38 [Debug] app/dns: domain www.netflix.com will use DNS in order: [DOHL//1.1.1.1 localhost]
2023/06/19 18:07:38 [Info] app/dns: DOHL//1.1.1.1 querying: www.netflix.com.
2023/06/19 18:07:38 [Info] app/dns: DOHL//1.1.1.1 got answer: www.netflix.com. TypeAAAA -> [[2600:1f14:62a:de85:d7:e7a1:8f7d:f6f5] [2600:1f14:62a:de84:880a:88cc:a16:5423] [2600:1f14:62a:de83:c61a:d6e:18b0:65f7]] 2.666887ms
2023/06/19 18:07:38 [Info] [2629711719] proxy/freedom: dialing to tcp:[2600:1f14:62a:de83:c61a:d6e:18b0:65f7]:443
2023/06/19 18:07:38 [Info] [2629711719] transport/internet/tcp: dialing TCP to tcp:[2600:1f14:62a:de83:c61a:d6e:18b0:65f7]:443
2023/06/19 18:07:38 [Debug] transport/internet: dialing to tcp:[2600:1f14:62a:de83:c61a:d6e:18b0:65f7]:443
2023/06/19 18:07:38 [Info] [2629711719] proxy/vless/encoding: XtlsFilterTls found tls 1.3! 212 TLS_AES_128_GCM_SHA256
2023/06/19 18:07:38 [Info] [2629711719] proxy/vless/encoding: XtlsPadding 212 1074 0
2023/06/19 18:07:39 [Info] [2629711719] proxy/vless/encoding: Xtls Unpadding new block0 0 content 64 padding 1223 0
2023/06/19 18:07:39 [Info] [2629711719] proxy/vless/encoding: Xtls Unpadding new block0 0 content 98 padding 1064 2
2023/06/19 18:07:39 [Info] [2629711719] proxy/vless/encoding: XtlsRead readV
2023/06/19 18:07:39 [Info] [2629711719] proxy/vless/encoding: XtlsPadding 517 414 2
2023/06/19 18:07:39 [Info] [2629711719] proxy/vless/encoding: XtlsWrite writeV 0 936 0
2023/06/19 18:07:44 [Info] [1359716082] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > context canceled
2023/06/19 18:07:45 [Info] [731279259] proxy/vless/inbound: firstLen = 1186
2023/06/19 18:07:45 [Info] [731279259] proxy/vless/inbound: received request for tcp:mtalk.google.com:5228
2023/06/19 18:07:45 [Info] [731279259] proxy/vless/encoding: Xtls Unpadding new block0 16 content 517 padding 790 0
2023/06/19 18:07:45 [Info] [731279259] proxy/vless/encoding: XtlsFilterTls found tls client hello! 517

**Comment by wy15** [comment]
<img width="182" alt="image" src="https://github.com/XTLS/Xray-core/assets/1898296/66ea4ffe-e4a4-407f-abe1-bd848d51927f">
ip是已经受限了。换ip吧，或者用warp出口

**Comment by ynhzzu** [comment]
netflix禁了vps的机房

**Comment by msbtx** [comment]
遇到过，跟客户端有关，dns泄露、udp没代理之类的问题，用sock5或者http代理应该没问题

**Comment by houmie** [comment]
Hello @chika0801 

Sorry can you explain how this Warp works?  I'm also very keen to learn how the Warped Wireguard (?) works to watch Netflix from a VPS.  Thank you

**Comment by chika0801** [comment]
> Hello @chika0801
> 
> Sorry can you explain how this Warp works? I'm also very keen to learn how the Warped Wireguard (?) works to watch Netflix from a VPS. Thank you

WARP works, I suggest you go to the cloudflare site and search for the equivalent. You don't actually have to learn the Warp principles.

As for netflix all unlocked content. For example, your VPS has an IP that can only watch netflix homebrew content. You want to achieve the goal of being able to watch all the content. I suggest you buy a VPS from another merchant and test it again. Instead of expecting warp to solve this one problem.

The usage of warp to solve this problem has been used massively for the Chinese community with poor results. For example, Chinese community likes to use Singapore VPS, even if this VPS uses warp ip with warp, most of them can't watch netflix content.

Translated with DeepL.com (free version)
