### ISSUE TITLE
reality里client-fingerprint可以不同端用一套么？

### ISSUE THREAD

**Issue by toyo2333** [XTLS/Xray-core#2229]
我用clash的客户端配置，所以希望用一套配置。 

我想知道，client-fingerprint 如果在windows上设置为了ios这样做是否有问题（同理，全部设置为chrome后在ios手机上用）

正确的做法是怎样的 谢谢大佬们盼望回复啊

**Comment by RPRX** [comment]
如果等价于 Xray-core 中的 `fingerprint`，一般来说没大问题。建议去 Clash.Meta 的群里再问一下。

**Comment by toyo2333** [comment]
> 如果等价于 Xray-core 中的 `fingerprint`，一般来说没大问题。建议去 Clash.Meta 的群里再问一下。

就是等价xray中的那个选项。

我的问的是我全部改ios，那么windows客户端用这个指纹也是合适的么？ 我只想维护一个yaml配置文件

**Comment by RPRX** [comment]
~~学一下中文好吗~~

> 一般来说没大问题。

**Comment by RPRX** [comment]
Update：小问题是 https://t.me/projectXtls/181

~~比如说你开着 iOS 的指纹，TTL 却不符合 iOS 的默认值，就挺尴尬的~~

之前没说是不想给 GFW 提供思路，毕竟这么用的人很多，但是根据 b c 在群里发的消息，我觉得 GFW 疑似已经开始区分系统了

**Comment by RPRX** [comment]
> @RPRX 我发的包，无论Windows上还是Linux上Hop limit都是64啊........

r u sure?

**Comment by RPRX** [comment]
@5e2t 再看看 IPv6（要看自己发的包，不要看到对面去了）

**Comment by RPRX** [comment]
@5e2t NAT 模式会减一个 TTL，比如移动网络运营商可以据此判断流量是“直连”还是经过了手机热点

**Comment by RPRX** [comment]
@5e2t ~~建议把症状重新完整表述一下~~

**Comment by toyo2333** [comment]
> 手机流量不减TTL，NAT模式下的Linux减两个TTL，都会收到RST。在只会减一个TTL的网络下的Windows也会收到RST；在只会减一个TTL的网络下的Linux系统不会收到RST。

你上述说
手机从Wi-Fi切到流量：ttl不变，结果从正常变成了RST （这什么原因？这又和ttl没关系了？）

另外，你windows原本默认的ttl是多少，出现RST的时候不是用的默认的ttl么？

**Comment by toyo2333** [comment]
太乱了。我都看不懂了。为啥我这里realty不管用什么设备 什么网络 都没问题。你那就那么多问题。

5e2t ***@***.***>于2023年8月10日 周四10:43写道：

**Comment by toyo2333** [comment]
这没问题。我也想搞清楚状况。避免以后配置不当导致被ban啊

5e2t ***@***.***>于2023年8月10日 周四10:46写道：

**Comment by RPRX** [comment]
@5e2t 首先家里的网络和移动网络应当视为不同的环境，其次很明显它对不同的 TTL 有不同的策略，**你选一个网络定量测试一下，只看最终发给运营商时的 TTL**，Linux 改 TTL 很方便。IPv4 如果最终发的包除了源端口完全一样，结果却不同，这就有鬼了。

**Comment by yoohooyoo** [comment]
> @toyo2333 我都不知道怎么该TTL

Windows 修改TTL命令：（以修改为64为例）
使用管理员模式打开powershell
`netsh interface ipv4 set global defaultcurhoplimit=64`

验证方法是ping 127.0.0.1，看后面的TTL有没有从默认的128变为64
可以测试下

**Comment by nursery01** [comment]
> 之前没说是不想给 GFW 提供思路，毕竟这么用的人很多

我是不是做了壞事了😦

**Comment by ZqinKing** [comment]
windows的TTL也不是固定的，WIN 7、XP和WIN10的默认值是不一样的
