### ISSUE TITLE
请帮我看看这个配置有什么问题

### ISSUE THREAD

**Issue by fyhong** [XTLS/Xray-core#2231]
一运行就一直报错
2023/06/20 21:41:48 [Info] transport/internet/tcp: REALITY: processed invalid connection
2023/06/20 21:41:48 [Info] transport/internet/tcp: REALITY: processed invalid connection
2023/06/20 21:41:49 [Info] transport/internet/tcp: REALITY: processed invalid connection
2023/06/20 21:41:49 [Info] transport/internet/tcp: REALITY: processed invalid connection
2023/06/20 21:41:49 [Info] transport/internet/tcp: REALITY: processed invalid connection
2023/06/20 21:41:49 [Info] transport/internet/tcp: REALITY: processed invalid connection
2023/06/20 21:41:49 [Info] transport/internet/tcp: REALITY: processed invalid connection
2023/06/20 21:41:49 [Info] transport/internet/tcp: REALITY: processed invalid connection
2023/06/20 21:41:49 [Info] transport/internet/tcp: REALITY: processed invalid connection
2023/06/20 21:41:49 [Info] transport/internet/tcp: REALITY: processed invalid connection
2023/06/20 21:41:49 [Info] transport/internet/tcp: REALITY: processed invalid connection
2023/06/20 21:41:49 [Info] transport/internet/tcp: REALITY: processed invalid connection
2023/06/20 21:41:50 [Info] transport/internet/tcp: REALITY: processed invalid connection

以下是我的配置
{
"log": { "loglevel": "info" },
"api": {"services": [ "HandlerService", "LoggerService", "StatsService" ], "tag": "api" },
"stats": {},
  "policy": {
    "levels": { "0": { "statsUserUplink": true, "statsUserDownlink": true } },
    "system": { "statsInboundUplink": true, "statsInboundDownlink": true, "statsOutboundUplink": true, "statsOutboundDownlink": true }
  },
    "inbounds": [
{ "port": 29521, "protocol": "dokodemo-door", "settings": { "address": "127.0.0.1" }, "tag": "api", "sniffing": null },
        {
            "port": 443, "protocol": "vless",
            "settings": {
                "clients": [
{ "id": "vps",  "flow": "xtls-rprx-vision", "email": "vps" }
                ],
                "decryption": "none"
            },
      "sniffing": { "enabled": true, "destOverride": ["http", "tls", "quic"] },
            "streamSettings": {
                "network": "tcp",  "security": "reality",
		"realitySettings": {
		"show": false,
		"dest": "teams.microsoft.com:443",
		"xver": 0,
		"serverNames": [ "teams.microsoft.com" ],
		"privateKey": "mJ6Eg7-vY0nH7y0RNFzSTr1vdgwt-wMyFyKa69Xa91w",
		"shortIds": [ "6ba85179e30d4fc2" ]
                }
            }
        }
    ],
    "outbounds": [
        { "protocol": "freedom", "tag": "direct" },
        { "protocol": "freedom", "tag": "ipv6_out", "settings": { "domainStrategy": "UseIPv6" } },
        { "protocol": "Blackhole", "tag": "block" }
    ],
  "routing": {
    "domainStrategy": "IPOnDemand",
    "strategy": "rules",
    "rules": [
      { "inboundTag": [ "api" ], "outboundTag": "api", "type": "field" },
      { "type": "field", "outboundTag": "blocked", "ip": [ "geoip:private" ] },
	{ "type": "field", "domain": [ "openai.com", "ai.com", "geosite:google" ], "outboundTag": "ipv6_out" },
      {"type": "field", "outboundTag": "blocked", "protocol": [ "bittorrent" ] },
      { "type": "field", "domain": [ "geosite:category-ads-all" ], "outboundTag": "block" }
    ]
  }
}

**Comment by fyhong** [comment]
将上面配置的"dest": "teams.microsoft.com:443",改为"dest": "learn.microsoft.com:443",
可以正常运行。这是为什么

**Comment by chika0801** [comment]
> 将上面配置的"dest": "teams.microsoft.com:443",改为"dest": "learn.microsoft.com:443", 可以正常运行。这是为什么

不为什么，可能用这个learn.microsoft.com ,随机出现你感觉速度慢，时通时不通，建议再换其它目标网站。

**Comment by fyhong** [comment]
我反复测试了，只要teams.microsoft.com就会报上面的错误，换回learn.microsot.com完全正常

**Comment by chika0801** [comment]
> 我反复测试了，只要teams.microsoft.com就会报上面的错误，换回learn.microsot.com完全正常

你用的VPS，用一些域名，就会莫名不通，换了就会通。但是通得了好久，中途时不时稳，说不清楚。

以前都讨论过这问题的，建议你不要用AWS 甲骨文 VU 这类商家的机，DEST的域名换换你VPS当地旅游局博物馆之类的。

**Comment by fyhong** [comment]
上面的域名是微软的啊。按道理不会被强的。。

**Comment by chika0801** [comment]
几句说不清楚原理。我也不懂这块。我只是建议你再遇到怎么排查好一点。你有兴趣隔壁这ISS。https://github.com/XTLS/Xray-core/issues/2230

**Comment by lockqueen** [comment]
> 我反复测试了，只要teams.microsoft.com就会报上面的错误，换回learn.microsot.com完全正常

teams.microsoft.com他不是tls1.3

**Comment by zxbiao** [comment]
> > 我反复测试了，只要teams.microsoft.com就会报上面的错误，换回learn.microsot.com完全正常
> 
> teams.microsoft.com他不是tls1.3

```
# curl --tlsv1.3 -I https://teams.microsoft.com
curl: (35) error:0A000126:SSL routines::unexpected eof while reading

# curl --tlsv1.3 -I https://learn.microsoft.com
HTTP/2 301
content-length: 0
location: /en-us/
request-context: appId=cid-v1:b1c5b6ea-7ff0-41d3-9862-84c5e1dc3be7
x-datacenter: wus
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
x-ua-compatible: IE=edge
x-xss-protection: 1; mode=block
nel: {"report_to":"network-errors","max_age":604800,"success_fraction":0.01,"failure_fraction":1.0}
report-to: {"group":"network-errors","max_age":604800,"endpoints":[{"url":"https://mdec.nelreports.net/api/report?cat=mdocs"}]}
x-azure-ref: 0fIOSZAAAAAB/jfVJlwNWQZoqQCO6mjxlU0pDRURHRTAzMTAANzE2ODkyMGUtOWY1Yi00YTYyLWIxNmUtZDViZTYzY2U2MWU3
cache-control: no-cache, no-store
expires: Wed, 21 Jun 2023 04:58:36 GMT
date: Wed, 21 Jun 2023 04:58:36 GMT
set-cookie: original_req_url=https://learn.microsoft.com/; expires=Wed, 21-Jun-2023 04:58:41 GMT; secure; HttpOnly; SameSite=Lax
akamai-cache-status: Miss from child, Miss from parent
strict-transport-security: max-age=31536000; includeSubDomains; preload
```

你是对的
