### ISSUE TITLE
出现如下问题，系统是debian10

### ISSUE THREAD

**Issue by waersan-github** [XTLS/Xray-core#2234]
Xray 1.8.1 (Xray, PenetratesEverything.) Custom (go1.20.3linux/amd64)切换版本
重启
A unified platform for anti-censorship.
2023/06/21 00:27:25 lnfolinfra/conf/serial: Reading config:bin/config;json
Failed to start:
app/proxyman/inbound: failed tolisten TCP on 62789 >
transport/internet: failed to listen onaddress: 127.0.0.1:62789 >
transport/internet/tcp: failed to listenICP on 127.0.0.1:62789 > listen tcp127.0.0.1:62789: bind: cannot assignrequested address

**Comment by FranzKafkaYu** [comment]
@waersan-github 出现该问题通常是由于系统问题，可以尝试:  
1.更换其他系统  
2.修改配置模板中"listen": "127.0.0.1",与address": "127.0.0.1"为"0.0.0.0"

**Comment by RPRX** [comment]
非 core 问题，换系统。另外如果指定的端口在系统的动态端口范围内，可能刚好正被其它程序占用。
