### ISSUE TITLE
V1.8.3 Server端报告一个关于"dest": "/dev/shm/xray/h1.sock"问题，不知算不算Bug。

### ISSUE THREAD

**Issue by wansenlyt** [XTLS/Xray-core#2236]
昨日在vps debain 11X64上更新了v1.8.3版服务端，原来v1.8.1配置的路径为"dest": "/dev/shm/xray/h1.sock"，不能启动，查看错误日志，发现不能在/dev/shm/下创建xray文件夹，将原配置修改为"dest": "/dev/shm/h1.sock"后，配置的其它内容不修改，启动正常。
不知上述问题算不算一个bug，特来反馈下。同时感谢开发者们的奉献。

**Comment by chika0801** [comment]
你是传递给nginx的话试试

"listen": "/dev/shm/grpc.socket,0666",

加,0666

**Comment by wansenlyt** [comment]
> 你是传递给nginx的话试试
> 
> "listen": "/dev/shm/grpc.socket,0666",
> 
> 加,0666

我其实想反馈的问题是V1.8.3不知是权限还是其它的问题（我不懂编程，请见谅），在启动时不能像V1.8.1之前一样可以在/dev/shm文件夹下创建文件夹了。即：我在V1.8.1的配置路径为/dev/shm/xray/h1.sock时，可以正常启动和使用，而在V1.8.3下，必须将配置路径改为/dev/shm/h1.sock，才可正常使用。

**Comment by lockqueen** [comment]
install的时候加个-u root，应该就能创建文件夹了吧？

**Comment by RPRX** [comment]
181 应该也没“顺便建文件夹”的功能吧

**Comment by wansenlyt** [comment]
> 

181是可以“顺便建文件夹”的，因为升级到183才发现不行的。：)

**Comment by RPRX** [comment]
> 181是可以“顺便建文件夹”的，因为升级到183才发现不行的。：)

183 没改相关的代码，也改不了，因为这个完全取决于 Golang 的官方库，除非它改了行为

你现在再测测 181，如果以前 181 可以，现在却不行，那可能是权限问题，或是你记错了

**Comment by wansenlyt** [comment]
> > 181是可以“顺便建文件夹”的，因为升级到183才发现不行的。：)
> 
> 183 没改相关的代码，也改不了，因为这个完全取决于 Golang 的官方库，除非它改了行为
> 
> 你现在再测测 181，如果以前 181 可以，现在却不行，那可能是权限问题，或是你记错了

测试过了，181确实可以顺便建文件夹；可能是Golang 官方库变化吧，猜测也是权限问题，请见谅不懂编程；不过也不是什么大问题，修改下路径就好了。谢谢你们的无私付出。
