### ISSUE TITLE
dialerProxy不能转发xtls-rprx-vision的流量

### ISSUE THREAD

**Issue by maskedeken** [XTLS/Xray-core#2238]
应用场景是利用dialerProxy转发到带TLS分片的freedom outbound，握手之后就显示context canceled

原因应该是dialerProxy转发流量创建的是cnc.connection，而cnc.connection没有实现syscall.Conn，而XRV需要依赖rawConn

**Comment by RPRX** [comment]
是的，也是这个原因导致不能中转，其实就是写法的问题，改为不依赖 rawConn 变量就好了，不过 splice 还是要拿 freedom conn

我给 @yuhan6665 说过，他还没修，你可以改一下发个 PR
