### ISSUE TITLE
geoip怎么表达除了cn以外的所有ip?

### ISSUE THREAD

**Issue by dotNetDR** [XTLS/Xray-core#224]
geoip:cn 代表cn的ip
那我该如何指定非cn的ip呢？是geoip:!cn吗？

**Comment by dotNetDR** [comment]
能否补充一下geo*的匹配说明规则？

**Comment by zhj9709** [comment]
https://github.com/Loyalsoldier/v2ray-rules-dat

**Comment by dotNetDR** [comment]
> https://github.com/Loyalsoldier/v2ray-rules-dat

是问geoip怎么用非操作，你丢的链接大部分是介绍geosite

**Comment by zhj9709** [comment]
> > https://github.com/Loyalsoldier/v2ray-rules-dat
> 
> 是问geoip怎么用非操作，你丢的链接大部分是介绍geosite

以前文档里有很多国家的geoip的，现在好像没了，反正应该没有!cn这种，但其他国家有geoip:cn这种的，把cn换掉。

**Comment by zhj9709** [comment]
```
geoip:ae,
geoip:au,
geoip:br,
geoip:ca,
geoip:de,
geoip:dk,
geoip:es,
geoip:fi,
geoip:fr,
geoip:gb,
geoip:gr,
geoip:hk,
geoip:id,
geoip:il,
geoip:in,
geoip:iq,
geoip:ir,
geoip:it,
geoip:jp,
geoip:kr,
geoip:mo,
geoip:my,
geoip:nl,
geoip:no,
geoip:nz,
geoip:ph,
geoip:ru,
geoip:sa,
geoip:sg,
geoip:th,
geoip:tr,
geoip:tw,
geoip:us,
geoip:vn
```

**Comment by dotNetDR** [comment]
好的，多谢指出~

**Comment by rprx** [comment]
建议把 CN 分流走，剩下的就是非 CN 的了
