### ISSUE TITLE
通过软路由连接xray reality之后，依然无法登录大菠萝4

### ISSUE THREAD

**Issue by lmz00ok** [XTLS/Xray-core#2249]
各位小伙伴，有玩大菠萝4的么？
我买的日本打板搬瓦工服务器，但PS5账号是港服的。
PS5所连接的路由已经安装openwrt，通过passwall连接至reality节点。
但是还是无法登陆大菠萝4。
各位又遇到这种情况么？
跪求解答。

我的xray配置里面已经屏蔽了 geoip:cn 和 geosite:cn

**Comment by chika0801** [comment]
passwall里面你把代理UDP也选上了的吧？ 看看它设置菜单 代理 TCP UDP是不是选成所有端口的了。

**Comment by WordsWorthLess** [comment]
听说Diablo 4连接困难是因为国内的DNS将游戏服务器的地址解析到网易原来的diablo的服务器
但是网易已经跟暴雪解除合作了，国内可以把游戏服务器的IP解析到韩国的服务器上
我不玩Diablo4,所以没测试过

**Comment by RPRX** [comment]
~~无版本无配置无日志，三无 issue~~

**Comment by lmz00ok** [comment]
> passwall里面你把代理UDP也选上了的吧？ 看看它设置菜单 代理 TCP UDP是不是选成所有端口的了。

UDP是关闭的啦

**Comment by lmz00ok** [comment]
@

> 听说Diablo 4连接困难是因为国内的DNS将游戏服务器的地址解析到网易原来的diablo的服务器 但是网易已经跟暴雪解除合作了，国内可以把游戏服务器的IP解析到韩国的服务器上 我不玩Diablo4,所以没测试过

@WordsWorthLess 多谢，请问 如何手动解析？

**Comment by chika0801** [comment]
> > passwall里面你把代理UDP也选上了的吧？ 看看它设置菜单 代理 TCP UDP是不是选成所有端口的了。
> 
> UDP是关闭的啦

开了再试呀。。。

**Comment by lmz00ok** [comment]
> ~无版本无配置无日志，三无 issue~

@RPRX 多谢提醒， to be honest 这是我在git上发的第一个issue。。。。
passwall 版本4.66-8, xray plugin版本1.8.1
硬路由型号：红米AX6000
OPENWRT版本：ImmortalWrt 18.06-5.4-SNAPSHOT r11814-ef0c86bdb0 / LuCI branch (git-22.323.17670-f9380b5)
内核版本：5.4.224
VPS面板：X-UI
X-ui 所用xray内核 1.8.0
X-ui节点配置信息：
协议VLESS
端口1888
flow control: xtls-rprx-vision
utls: chrome

日志暂时不知道怎么抓，因为是用PS5去连接的大菠萝4
PS5为港服，VPS为搬瓦工日本bbtec路线。

**Comment by jdnt** [comment]
刚好看到。前段时间也被朋友忽悠入了D4
两个步骤：
1、要把prod.actual.battle.net解析到其他服，你可以ping一下看看出来的是不是cn开头的，随便解析的kr或者us都行。以smartdns为例：
`cname /prod.actual.battle.net/kr.actual.battle.net`
2、passwall 高级设置、tcp转发端口加上
`1119:6119,28890:28910,54540:54580`
分的不是很细，但是1119一定要有，54xxx的是进游戏分配的服务器，如果宽带直连没问题（例如联通）这段可以不需要。28xxx的建议加上，这个端口段会决定连接的服务器区域。

**Comment by lmz00ok** [comment]
> 刚好看到。前段时间也被朋友忽悠入了D4 两个步骤： 1、要把prod.actual.battle.net解析到其他服，你可以ping一下看看出来的是不是cn开头的，随便解析的kr或者us都行。以smartdns为例： `cname /prod.actual.battle.net/kr.actual.battle.net` 2、passwall 高级设置、tcp转发端口加上 `1119:6119,28890:28910,54540:54580` 分的不是很细，但是1119一定要有，54xxx的是进游戏分配的服务器，如果宽带直连没问题（例如联通）这段可以不需要。28xxx的建议加上，这个端口段会决定连接的服务器区域。

@jdnt 非常感谢！
但是不知道为什么，我在smartdns的域名地址里面设置了 上面的cname指令，却依然ping出cn的域名。但是nslookup 指令是ok的。我的passwall设置里：
![image](https://github.com/XTLS/Xray-core/assets/137563675/f8d02169-de9f-44ef-a30b-c4fa9631b06b)
请问还需要做什么特别的设置来使它生效嘛？查了半天还是解决不了。。

**Comment by jdnt** [comment]
一个简单的判断，只要能开google，xray和passwall就肯定不会有问题（说明TCP端口代理生效）。ping出cn开头的CDN说明问题出在dns上。我前几天去另一个不常住的家里玩的时候也出现也同样的问题，用的是r2s，后来编译了最新的openwrt就正常了。原因未知，可能是老版本smartdns的配置未生效。
这里有一个最直接的解决方案，把解析写进PC的host里。只要这一步正确了，游戏就能正常进入了。

**Comment by chancat87** [comment]
建议你升级到passwall2

**Comment by chzzfly** [comment]
使用clash meta连接reality打游戏是没有问题的，我已经用了近半个月了，但语音聊天这个服务不可用，加不进去语音房。

**Comment by gungnirayu** [comment]
> 刚好看到。前段时间也被朋友忽悠入了D4 两个步骤： 1、要把prod.actual.battle.net解析到其他服，你可以ping一下看看出来的是不是cn开头的，随便解析的kr或者us都行。以smartdns为例： `cname /prod.actual.battle.net/kr.actual.battle.net` 2、passwall 高级设置、tcp转发端口加上 `1119:6119,28890:28910,54540:54580` 分的不是很细，但是1119一定要有，54xxx的是进游戏分配的服务器，如果宽带直连没问题（例如联通）这段可以不需要。28xxx的建议加上，这个端口段会决定连接的服务器区域。

我这里54xxx加上就翻不了了，不知大为撒，大雕知道更新是用哪些端口吗？

**Comment by gungnirayu** [comment]
昨天又试了一下，不用梯子，直接把prod.actual.battle.net对应的ip在hosts里写死，然后直连亚服，比通过美国vps连美服延迟低一半……
