### ISSUE TITLE
一键测速core error

### ISSUE THREAD

**Issue by deeplee** [XTLS/Xray-core#2253]
启动服务(2023/6/24 星期六 17:28:31)...
Xray 1.7.5 (Xray, Penetrates Everything.) Custom (go1.20 windows/amd64)
A unified platform for anti-censorship.
2023/06/24 17:28:31 [Info] infra/conf/serial: Reading config: stdin:
Failed to start: main: failed to load config files: [stdin:] > infra/conf: Trojan password is not specified.
Cannot mix synchronous and asynchronous operation on process stream.
2023/6/24 星期六 17:28:31 运行Core失败，请看日志

**Comment by RPRX** [comment]
GUI 客户端的 Trojan 配置有误，非 core 问题

**Comment by RuGuoo** [comment]
你好，有解决吗，我也遇到同样的情况
