### ISSUE TITLE
Question about [VLESS protocol]: Need help from repository maintainer or developer.

### ISSUE THREAD

**Issue by lmmqxyx404** [XTLS/Xray-core#2257]
1. I have read the [doc](https://xtls.github.io/development/protocols/vless.html#request-response).
2. And  I plan to implement the serverside with the conf(vless+tcp) by _**RUST**_.
3. I don't understand the **Flow** and **Encryption** keyword. 
4. Furthermore, What should I do  to deal with the N-byte protobuf information? Give me more precise description.
5. What is the  behaviour of the  **Encryption**? 

I sincerely hope that the vless protocol documentation can be as clear and straightforward as [Trojan](https://trojan-gfw.github.io/trojan/protocol.html)

**Comment by RPRX** [comment]
感谢你的支持，首先根据你说的 235，可能你没怎么用过 VLESS，其次 VLESS 还在开发中，以后会出一个总的协议规范。

~~其实我打了很多字被 Tor 吞了，不想重新打~~，简而言之就是：目前不建议这样做。

**Comment by RPRX** [comment]
你有时间的话，可以先研究一下 Rust 结合 Chromium 或写一个 Rust 版 uTLS 库，它们会很有用。
