### ISSUE TITLE
trojan 可否设置多个密码

### ISSUE THREAD

**Issue by bigbighill** [XTLS/Xray-core#226]
原版trojan 配置文件 是支持多个密码的。

"password": ["xxxxxx","xxxxxx"]

![IMG_20210201_224724_668](https://user-images.githubusercontent.com/26495337/106474525-f8d31600-64df-11eb-8385-24f49e29b9df.jpg)

**Comment by xianren78** [comment]
支持的，写法与gfw不一样，格式如下，继续罗列
"protocol": "trojan",
		"settings": {
			"clients": [{
				"password": "pass1",
				"email": "pass1@gmail.com"
			}, {
				"password": "pass2",
				"email": "pass2@gmail.com"
			}, {
				"password": "pass3",
				"email": "pass3@gmail.com"
			}

**Comment by bigbighill** [comment]
原来是这种语法格式，谢谢楼上

**Comment by rprx** [comment]
需要在文档中着重说明，Shadowsocks 的也需要更新
