### ISSUE TITLE
QUIC fragmentation

### ISSUE THREAD

**Issue by FDeghy** [XTLS/Xray-core#2262]
Please add QUIC (UDP) fragmentation.

**Comment by RPRX** [comment]
然而伊朗 GFW 对 UDP 几乎是全封

**Comment by RPRX** [comment]
题外话：我打算在 Golang 官方实现的 QUIC 发布后给 REALITY 加上 QUIC 支持，但偷别人会有一些小问题比如 https://github.com/XTLS/Xray-core/discussions/1903#discussioncomment-5543921

偷自己或 GFW 没找到你偷的目标是没问题的，到时还会删掉现有的 QUIC 和 mKCP 传输层，它们已经没用了

**Comment by chika0801** [comment]
太好了

**Comment by RPRX** [comment]
To 艾莉卡：0-RTT 是 XTLS 的，和这个不是一回事

我和 @yuhan6665 备忘了非常多的计划，~~有很多你们想不到的好东西~~

**Comment by Fangliding** [comment]
@RPRX 有很多有生之年的好东西（绝望）

**Comment by RPRX** [comment]
> @RPRX 有很多有生之年的好东西（绝望）

别人赚钱的东西都能有生之年系列，~~这一分不赚还倒贴时间还担风险的东西当然更是有生之年系列~~，随缘写代码随缘更新随缘发版

就像这方面的 REALITY、XUDP 等很多文章我是写了一半就没继续写了，我想了想，如果一篇十万就很有动力了，~~我能每天写一篇~~

每篇文章创造的价值肯定不止这点钱，更别说代码本身创造的价值已难以衡量，~~问题是这种项目有人给我也不敢收~~

**Comment by FranzKafkaYu** [comment]
@RPRX R佬可以开一个加密货币捐赠通道的

**Comment by RPRX** [comment]
> @RPRX R佬可以开一个加密货币捐赠通道的

捐赠只能收到小钱，~~我对小钱不感兴趣~~

**Comment by chika0801** [comment]
传下去

**Comment by RPRX** [comment]
To Xiao：进不进去其实与数额无关，收一分钱都能被当把柄被扣帽子，人家正愁没借口弄你呢，~~收个小钱结果牢底坐穿就很搞笑了~~

印象最深的是有个人卖节点就赚了一千多被判三年，一千多能干啥，赚上亿也判得差不多，只是想找个借口弄你罢了，中国就这样

**Comment by RPRX** [comment]
> 其實我現在主力在用vless + kcp. 不知道為什麼。用了很久都沒有被牆。包括ipv4,ipv6. 包括翻出去以及翻進來。而且mkcp延遲真的很低(等同tuic v5)。建議保留。。。

UDP 类延迟都是一样的，至于墙不墙，体验好不好，目前严重因地区而异。mKCP 的话不混淆就暴露，几年前被 GFW 针对了才出了混淆，变成了全随机数和 SS 类似，墙起来也没有难度，只是现在 GFW 重心不在 UDP 而已 https://github.com/XTLS/Xray-core/discussions/1903#discussioncomment-5544515

这么说吧，mKCP 能做到的，QUIC 都能做到，**Hysteria、mKCP 开了混淆差不多**，我也不懂 Hy 火的时候是大家都忘了有 mKCP 吗

所以你这个没被墙很正常啊，Hysteria 开混淆都有人没被墙，凭啥 mKCP 要被墙

注：上述“混淆”指的不是 header 伪装，加 header 当然也能加，但是更假，SSR 系列

**Comment by RPRX** [comment]
To nick22 li：你想表达什么，mKCP 是 mKCP 的样子，Hy 是 QUIC 的样子，白名单协议，你较真这俩谁被捉过，公平吗

**Comment by RPRX** [comment]
To nick22 li：Hy 建议你开混淆，外观上就和 mKCP 开混淆一样了，做的事情也都是 ~~暴力发包~~，无非是比比谁调的参数更暴力

你要说被封案例，都有不少，一个人没被封不代表其他人没被封，若一条线路用 Hy 开混淆不封，换 mKCP 开混淆也不会封

而且 mKCP 的混淆还出得更早，只是没火起来，~~虽然我要删了 mKCP，但公道话还是要说的~~

**Comment by RPRX** [comment]
总结：~~看来还是 QUIC 更吸引眼球~~

实际上相比于其它 UDP 协议，QUIC 的确更有优势，因为它本身就是广泛使用的白名单协议，且最终的趋势肯定是不加混淆、伪装
