### ISSUE TITLE
我红米10x pro 稳定版12.5.6,miad目录找到也是和11一样，压缩目录，改名，删除原目录，目前没广告，这个软件能卸载吗？反正只是一个广告推送app？

### ISSUE THREAD

**Issue by Alirazi1976123** [XTLS/Xray-core#2266]
我红米10x pro 稳定版12.5.6,miad目录找到也是和11一样，压缩目录，改名，删除原目录，目前没广告，这个软件能卸载吗？反正只是一个广告推送app？

_Originally posted by @fj4090 in https://github.com/2dust/v2rayNG/issues/930#issuecomment-973793067_

**Comment by chika0801** [comment]
你发错地方了
