### ISSUE TITLE
是否可以通过激光技术实现中转翻墙 ?

### ISSUE THREAD

**Issue by wanghuiyt** [XTLS/Xray-core#2268]
**我有一个设想. 在云南-越南边境, 或者漠河-俄罗斯, 隔着公路或者河面就能出国的那种地方, 以云南-越南为例, 在云南和越南各自竖起来一个杆子A, B, 顶部是激光发射器, A 通过激光射到 B, 反之亦然. 通过光的有无来实现AB之间的01通信, . 然后 A 杆子接入国内运营商网络作为代理, 通过 xray 加密流量辐射到全国, 是否可行 ?**

![20230628145520](https://github.com/XTLS/Xray-core/assets/25444996/35778d16-c489-48de-a6dc-c30c66e3db01)

**Comment by Fangliding** [comment]
@wanghuiyt 怎么这种乱七八糟的东西也跑来issues区

**Comment by RPRX** [comment]
~~哥们不是通信专业的吧~~

**Comment by RPRX** [comment]
我说一下吧，光的本质是电磁波，而电磁波可以通过调制解调直接携带信息，效率比“通过光的有无来实现AB之间的01通信”高 N 倍

所以这个想法很脑洞，但是不够专业，~~完了暴露了我学过通信~~

**Comment by wanghuiyt** [comment]
> 我说一下吧，光的本质是电磁波，而电磁波可以通过调制解调直接携带信息，效率比“通过光的有无来实现AB之间的01通信”高 N 倍
> 
> 所以这个想法很脑洞，但是不够专业，~完了暴露了我学过通信~

谢谢大佬解答

**Comment by RPRX** [comment]
To xtfso：量子纠缠态的前提是“未经观测”，一经观测就不再“纠缠”，所以无法承载自定义信息，~~完了暴露了我学过量子物理~~

**Comment by wanghuiyt** [comment]
6 啊大佬. 完全解答了疑惑.

**Comment by wanghuiyt** [comment]
> To xtfso：量子纠缠态的前提是“未经观测”，一经观测就不再“纠缠”，所以无法承载自定义信息，~完了暴露了我学过量子物理~

6 啊大佬. 完全解答了疑惑.

**Comment by CCCAUCHY** [comment]
> 我说一下吧，光的本质是电磁波，而电磁波可以通过调制解调直接携带信息，效率比“通过光的有无来实现AB之间的01通信”高 N 倍
> 
> 所以这个想法很脑洞，但是不够专业，~完了暴露了我学过通信~

只要编入《十万个为什么》就不会暴露了

**Comment by RPRX** [comment]
To 群里：友情提醒，卫星是可以被打碎的，~~血本无归系列~~

**Comment by lsyxiaopang** [comment]
> 业

但是如果类似于光纤的方式传输，是否能在抗干扰等方面优于射频

**Comment by HoshinoTouko** [comment]
学术界有人设想过通过空气在数据中心中进行光交换，并且实现过原型系统。但实际上会有很多问题，比如需要对空气质量有很高的要求，抗干扰能力弱，对位置精度等也有要求。想要实现可用的带宽也是很复杂的问题。
