### ISSUE TITLE
请求大佬们维护ProxySu ，现已无法使用，疑似acme.sh更新导致

### ISSUE THREAD

**Issue by xnxnsu** [XTLS/Xray-core#227]

**Comment by guanhemeng** [comment]
proxysu不是project x维护的，你需要找proxysu解决而非proxysu

**Comment by AkinoKaede** [comment]
那你应该把 Issue 发到 ProxySU，而不是 Xray-core

**Comment by rprx** [comment]
我们没有权限，请发到 ProxySU。

看了一眼，已有两个 issues：
https://github.com/proxysu/ProxySU/issues/100
https://github.com/proxysu/ProxySU/issues/98
