### ISSUE TITLE
Reaility problem with spam from "dest"server

### ISSUE THREAD

**Issue by somebodywashere** [XTLS/Xray-core#2275]
Hello! I noticed sometime very strange behavior of Xray's Reality that causes connection to stop working.

I tried two times to use server close to me (same hosting). Both it was perfect configured and everything correct (TLS 1.3, X... H2 etc). Also that happened once or twice with BIG destination servers like dl.google.com and eset.com.

First time I had problems with connection for about 3 times a week. And after a while I got banned by hoster a few days after because of DDoS.

And yesterday I had problems again. It worked very good at first, but about 3-4 hours after (probably because number of clients trippled from the last time) It's stopped working.

I still don't understand a reason behind this, but I noticed that Reality sometime become very aggressive and I got reverse DDoS or something like that. Noone can connect and use my server, but TCP connection is going crazy, 5-10k TCP connections from the "dest" server IP.

I can't understand what's happening because both error.log and access log have nothing special.

To fix it today I tried to set dest to 127.0.0.1:443 and I got spammed myself with 50K TCP connections and wait a bit.

**Comment by Smallthing** [comment]
似乎是因为现在的reality不会”缓存“ 目标服务器的信息，所以他会在每次发起链接去读取，我也发现了这点，所以我使用了self host，效果还可以。
英文就懒得打了，翻译 软件凑合看看吧。

**Comment by chika0801** [comment]
I'm not sure exactly what the cause of the phenomenon you are experiencing is. I suggest you try what we commonly call the steal yourself mode. You can refer to the example configuration in the link. If there is no SNI whitelist blocking technology for firewalls in your area.

Probably the process is that you install NGINX on your VPS to load the SSL certificate and the dest in the Xray config file fills in the local port that the local nginx listens on, in this form.

https://github.com/chika0801/Xray-examples/tree/main/VLESS-XTLS-uTLS-REALITY/steal_yourself

**Comment by somebodywashere** [comment]
The 

> I'm not sure exactly what the cause of the phenomenon you are experiencing is. I suggest you try what we commonly call the steal yourself mode. You can refer to the example configuration in the link. If there is no SNI whitelist blocking technology for firewalls in your area.
> 
> Probably the process is that you install NGINX on your VPS to load the SSL certificate and the dest in the Xray config file fills in the local port that the local nginx listens on, in this form.
> 
> https://github.com/chika0801/Xray-examples/tree/main/VLESS-XTLS-uTLS-REALITY/steal_yourself

Can you explain more of how does it work? Where do I get certificate for reality?

**Comment by chika0801** [comment]
> Can you explain more of how does it work? Where do I get certificate for reality?

I will only talk about the process.

Steal your own form, you need to buy a domain name yourself, apply for an SSL certificate for this domain name (free or paid makes no difference)

The dest parameter in the Xray configuration is the local port, Nginx listens to this port and loads the SSL certificate.

At this point in the Xray configuration, the "serverNames" parameter can be filled in with any domain name, but I suggest you fill in your own purchased domain name as mentioned earlier.

**Comment by Fangliding** [comment]
Unavoidable question
