### ISSUE TITLE
ask in English please ...

### ISSUE THREAD

**Issue by abbaszahiri** [XTLS/Xray-core#2278]
I tried to join https://t.me/projectXray

but it asked me sth in Chinese.
and I cannot read Chinese. Wrong answer and now it says I cannot join that :(

Please ask in English such an important question...

**Comment by chika0801** [comment]
Contact my ID @chika_virnf and let me know your ID. When you join, I will approve your request.

**Comment by Smallthing** [comment]
you can use some screenshot + ocr to do it， very easy
在94年开始上网，互联网英文为主我都是这么干的

**Comment by r06ertray** [comment]
It's time to learn Chinese, hahaha

**Comment by Fangliding** [comment]
It will get fixed

**Comment by Fangliding** [comment]
already changed into using two languages()
