### ISSUE TITLE
Android系统境内DNS设置成localhost无法正确识别

### ISSUE THREAD

**Issue by CharlesWou** [XTLS/Xray-core#2280]
使用的V2rayNG外壳GUI，配置文件中设置境内DNS为"localhost"，无法获取到ISP运营商提供的DNS。

只能手工设定成固定的值，比如223.5.5.5这种。
但是这种公共DNS，没有本地ISP运营商优化的好，对于国内页面（如百度），解析出来的IP没本地运营商DNS解析出来的IP延迟低，速度快。

**Comment by chika0801** [comment]
我也试了下使用localhost是失败了，原因不清楚，应该是安卓系统那边有限制，暂时没解决方案，建议你不要在意了。

**Comment by KobeArthurScofield** [comment]
安卓的 VPN 模式下 DNS 会被 VPN 服务接管并导流到 VPN 应用，填 ```localhost``` 可能会导致死循环。

仅代理模式没有这个问题，不过可能用起来不便就是了。

**Comment by CharlesWou** [comment]
@KobeArthurScofield 
是这样的，我在google play中找到一款软件名叫DNS Changer for IPv4/IPv6（https://git.frostnerd.com/PublicAndroidApps/DnsChanger），这个软件能获取到系统中wifi的dns，vpn（tun0）的dns，data数据流量对应的dns。
如果localhost有会导致死循环，有没有可能在vpn挂起来前，先获得到系统dns，然后用对应dns替换localhost
![Screenshot_20230703-025033](https://github.com/XTLS/Xray-core/assets/24507084/9817ed88-71ff-4ec6-b189-049023164c9f)
![Screenshot_20230703-024953](https://github.com/XTLS/Xray-core/assets/24507084/b8e93c57-99e2-4519-9fe1-bb88403b8523)
![Uploading Screenshot_20230703-025003_EDIT_1.png…]()

**Comment by yqk100** [comment]
https://stackoverflow.com/questions/38959067/dns-lookup-issue-when-running-my-go-app-in-termux

跟这个差不多，都是因为没有resolv.conf造成的；
在Android shell下也是这种结果。

**Comment by rainin9** [comment]
换Nekobox，直连DNS设置为local

**Comment by CharlesWou** [comment]
> 换Nekobox，直连DNS设置为local

666

**Comment by us254** [comment]
1:  `pkg update`
2:  `pkg install proot`
3:  `pkg install termux-exec`
4:  `mkdir -p ~/my_chroot`
5:  `echo "nameserver 8.8.8" > ~/my_chroot/resolv.conf`
6:  `termux-chroot`
7:  `cat /etc/resolv.conf`
