### ISSUE TITLE
Unix sockets do not get unlinked

### ISSUE THREAD

**Issue by nimagp** [XTLS/Xray-core#2282]
Every time xray-core runs, it creates the sockets but doesn't delete them on exit 
And when it starts, complains about the sockets being already in bind. The only solution is to delete the files when starting xray-core
It would be great to rebind to the sockets if they exist, or at least delete them on exit
Using Ubuntu 22.04 and xray-core 1.8.1

**Comment by chika0801** [comment]
This problem is known and has been there since previous older versions.

**Comment by nimagp** [comment]
> This problem is known and has been there since previous older versions.

Is there a fix in progress?

**Comment by chika0801** [comment]
There is no plan to fix it, and as you said, you know the way to fix it.
