### ISSUE TITLE
Reality sni 白名单

### ISSUE THREAD

**Issue by linehman** [XTLS/Xray-core#2283]
### Discussed in https://github.com/XTLS/Xray-core/discussions/2281

<div type='discussions-op-text'>

<sup>Originally posted by **linehman** July  1, 2023</sup>
大家好。 伊朗防火墙最近在一家主要移动运营商上启用了基于 SNI 的过滤。 在一些流行的 VPS 提供商上，干净的 IP 没有任何限制，几乎所有流行的协议都全速工作。 我在这里谈论的是干净的 IP，重点不在于哪个协议首先被阻止。 但是，如果您的服务器的干净 IP 来自不太知名的提供商，您将遇到上传速度限制问题。 例如，使用干净的Hetzner IP，没有问题，但是使用小型VPS提供商提供的干净IP，就会出现一些问题。 SSH 上传和下载速度非常快。 但是，如果您仅使用 speedtest.net 作为 SNI，则可以绕过上传速度限制。 使用 vmess/vless TCP + HTTP 标头时也是如此。 除非使用 speedtest.net 作为标头，否则上传速度接近于零。 其他协议（例如 Stealth openvpn）都可以。 再次，如果我使用与现实不同的协议，服务器的IP地址将很快被封锁。 所以我的问题是防火墙如何区分其他 SNI 上的合法流量和假 Xray 流量？ 我们该如何解决这个问题呢？ 最后但并非最不重要的一点是，许多伊朗用户在 Twitter 上报告了这个问题，并且不限于我的情况。

Hi everyone. Iran firewall has recently enabled SNI-based filtering on a major mobile operator. On some popular VPS providers clean IPs there is no restriction and almost all popular protocols work at full speed. I'm talking about clean IP here and the point is not which protocol gets blocked first. However if your server's clean IP is from a less known provider you will run into upload speed limit issues. For instance, with a clean Hetzner IP, there is no problem, but with a clean IP provided by a small VPS provider, there are some problems. SSH speed is very fast for upload and download. However, if you use reality only with speedtest.net as your SNI, you can bypass the upload speed limit. The same applies when using the vmess/vless TCP + HTTP headers. Unless speedtest.net is used as a header the upload speed is close to zero. Other protocols such as stealth openvpn are fine. Once again, if I use another protocol than reality, the server's IP address will be blocked quickly. So my question is how the firewall distinguishes between legit traffic on other SNIs and fake Xray ones? And how can we solve this issue? Last but not least this issue has been reported by many Iranian users on Twitter and is not limited to my case.</div>

**Comment by us254** [comment]
You showcase the strong performance of vless TCP without TLS, SSH, and stealth OpenVPN. This raises the question of whether the reality protocol is necessary when these alternatives are available.

**Comment by linehman** [comment]
@us254 As you mentioned, the main reason for using reality is in order to pervent server ip block by Irans firewall. Other protocols are identified and blocked after a few days ( This also depends on other factors such as number of users and traffic). 

While some people had success with some vps providers, many other users like me are facing issues with other providers. So I think there may be some kind of IP whitelist going on, but I can't be sure about that.

And my question is how the upload speed of reality is getting limited? if this is an ip limit , the situation should be the same for ssh and openvpn. And if this is a sni whitelist how can they determine the connection is reality and not regular web traffic? since there is no limit on regular internet traffic upload speed.

In my opinion this is a combination of ip whitelist and sni filtering. regarding speedtest.net sni , I believe it's going to be limited in near future too.

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/discussions/2281#discussioncomment-6353098

请在“Discussions”讨论
