### ISSUE TITLE
[Feature] 日志format建议，日志json

### ISSUE THREAD

**Issue by lhbdhr** [XTLS/Xray-core#2295]
辛苦大佬能不能考虑给日志format一下啊，最好是json格式。
这样的话日志的可读性会很高。

**Comment by yomnxkcs** [comment]
<img src="https://www.kindpng.com/picc/m/460-4600221_surprised-emoji-transparent-background-hd-png-download.png" width="60">
快说，你是不是ChatGPT派来的间谍？
