### ISSUE TITLE
Error in gRPC API Calls

### ISSUE THREAD

**Issue by itsamirhn** [XTLS/Xray-core#2296]
I could't call any gRPC in `xray.app.stats.command.StatsService` package.
On calling GetStats I'm getting not found error.
On calling QueryStats I'm getting `rpc error: code = Unknown desc = app/stats/command: QueryStats only works its own stats.Manager.`

**Comment by Yuki-J1** [comment]
https://github.com/v2ray/v2ray-core/issues/2171
