### ISSUE TITLE
关于reality偷自己时候的疑问

### ISSUE THREAD

**Issue by toyo2333** [XTLS/Xray-core#2299]
1，我自己的域名是A，并且用acme.sh申请了一个免费的证书，dest指向本机Nginx监听的端口；
2，Nginx再反代域名B（比如某个其他站点）

备注：这样设置是不想专门给域名再做个页面，所以反代出去了

问题：
1.这样做是否正确？还是说不合适？
2.因为A和B域名不同（证书也不同），这样会成为一个特征么？

**Comment by chika0801** [comment]
我一直这样的，nginx反代个其它网站，我觉得不会有什么特征

**Comment by iKira** [comment]
反代出去的不都是http站点了吗

**Comment by lxhao61** [comment]
Nginx反代出去的是HTTPS，而Rreality的dest要求转发给HTTP/2及TLS1.3网站。

**Comment by toyo2333** [comment]
> Nginx反代出去的是HTTPS（HTTP/1.1+TLS）网站，而Rreality的dest要求转发给HTTP/2及TLS1.3网站。

反代出去的，也可以是HTTP/2及TLS1.3网站吗？

**Comment by lxhao61** [comment]
> > Nginx反代出去的是HTTPS（HTTP/1.1+TLS）网站，而Rreality的dest要求转发给HTTP/2及TLS1.3网站。
> 
> 反代出去的，也可以是HTTP/2及TLS1.3网站吗？

可以，HTTP/2网站向下兼容HTTPS。

**Comment by toyo2333** [comment]
> > > Nginx反代出去的是HTTPS（HTTP/1.1+TLS）网站，而Rreality的dest要求转发给HTTP/2及TLS1.3网站。
> > 
> > 
> > 反代出去的，也可以是HTTP/2及TLS1.3网站吗？
> 
> 可以，HTTP/2网站向下兼容HTTPS。
谢谢 

楼歪了，我最开始提问的是 整个过程出现A和B两个域名“因为A和B域名不同（证书也不同），这样会成为一个特征么？”

**Comment by chika0801** [comment]
> > > > Nginx反代出去的是HTTPS（HTTP/1.1+TLS）网站，而Rreality的dest要求转发给HTTP/2及TLS1.3网站。
> > > 
> > > 
> > > 反代出去的，也可以是HTTP/2及TLS1.3网站吗？
> > 
> > 
> > 可以，HTTP/2网站向下兼容HTTPS。
> > 谢谢
> 
> 楼歪了，我最开始提问的是 整个过程出现A和B两个域名“因为A和B域名不同（证书也不同），这样会成为一个特征么？”

这样用了一段时间了，我自己的vps没发现遇到什么异常

**Comment by okoklai** [comment]
怎么会有人偷自己的域名，那跟搭VLESS+WS有啥区别。偷大厂的域名，就是因为大厂现在一时半会不敢封。你弄个不知名的小域名，天天跑流量，分分钟给你拉黑啊。

**Comment by toyo2333** [comment]
> 怎么会有人偷自己的域名，那跟搭VLESS+WS有啥区别。偷大厂的域名，就是因为大厂现在一时半会不敢封。你弄个不知名的小域名，天天跑流量，分分钟给你拉黑啊。

我觉得主要还是由2个原因：
1、你选的那个大厂的域名的IP不一定合适，比如微软，有可能给你返回一个国内的IP，那就很搞笑了。
2、另外就是如果大厂的IP和你vps机房的IP之间连接的延迟，可能会导致体验问题（不是所有大厂在你vps附近都由cdn节点），简单来说就是不可控。

**Comment by okoklai** [comment]
> > 怎么会有人偷自己的域名，那跟搭VLESS+WS有啥区别。偷大厂的域名，就是因为大厂现在一时半会不敢封。你弄个不知名的小域名，天天跑流量，分分钟给你拉黑啊。
> 
> 我觉得主要还是由2个原因： 1、你选的那个大厂的域名的IP不一定合适，比如微软，有可能给你返回一个国内的IP，那就很搞笑了。 2、另外就是如果大厂的IP和你vps机房的IP之间连接的延迟，可能会导致体验问题（不是所有大厂在你vps附近都由cdn节点），简单来说就是不可控。

是不是对reality有什么误解？偷的是域名（证书），不是IP。大厂返回哪里的IP并不重要。打个比方，使用微软的域名，那么墙看到的是你在访问microsoft.com，并且IP是你小鸡的IP。那么你一定会疑问，墙要是知道这个IP并不是microsoft.com的，那启不是会被禁吗？没错，但是墙无法确定IP是否为microsoft.com的，因为一个域名可以对应很多个IP，所以它现在只能认为你和小鸡的通信，是在访问microsoft.com。这就是为什么reality中的一个加分项为：与域名IP或CDN段接近，这样更具迷惑性。

另外对于延时，只取决于你和你的小鸡之间的连接速度，跟大厂用的哪里的IP和CDN根本没有关系。唯一受影响的只是证书验证的时间快慢而已。那也只是TLS开始通信的前几次握手会有影响。

那么再回到你偷自己的域名这个问题来：墙看到的是你在访问你自己的xyz域名，IP就是你的小鸡。这种特性无疑是过于明显，所以会针对这个xyz域名进行封禁。

**Comment by toyo2333** [comment]
> > > 怎么会有人偷自己的域名，那跟搭VLESS+WS有啥区别。偷大厂的域名，就是因为大厂现在一时半会不敢封。你弄个不知名的小域名，天天跑流量，分分钟给你拉黑啊。
> > 
> > 
> > 我觉得主要还是由2个原因： 1、你选的那个大厂的域名的IP不一定合适，比如微软，有可能给你返回一个国内的IP，那就很搞笑了。 2、另外就是如果大厂的IP和你vps机房的IP之间连接的延迟，可能会导致体验问题（不是所有大厂在你vps附近都由cdn节点），简单来说就是不可控。
> 
> 是不是对reality有什么误解？偷的是域名（证书），不是IP。大厂返回哪里的IP并不重要。打个比方，使用微软的域名，那么墙看到的是你在访问microsoft.com，并且IP是你小鸡的IP。那么你一定会疑问，墙要是知道这个IP并不是microsoft.com的，那启不是会被禁吗？没错，但是墙无法确定IP是否为microsoft.com的，因为一个域名可以对应很多个IP，所以它现在只能认为你和小鸡的通信，是在访问microsoft.com。这就是为什么reality中的一个加分项为：与域名IP或CDN段接近，这样更具迷惑性。
> 
> 另外对于延时，只取决于你和你的小鸡之间的连接速度，跟大厂用的哪里的IP和CDN根本没有关系。唯一受影响的只是证书验证的时间快慢而已。那也只是TLS开始通信的前几次握手会有影响。
> 
> 那么再回到你偷自己的域名这个问题来：墙看到的是你在访问你自己的xyz域名，IP就是你的小鸡。这种特性无疑是过于明显，所以会针对这个xyz域名进行封禁。

对对对，你说得对

**Comment by Sumire-Heanna** [comment]
> > > 怎么会有人偷自己的域名，那跟搭VLESS+WS有啥区别。偷大厂的域名，就是因为大厂现在一时半会不敢封。你弄个不知名的小域名，天天跑流量，分分钟给你拉黑啊。
> > 
> > 
> > 我觉得主要还是由2个原因： 1、你选的那个大厂的域名的IP不一定合适，比如微软，有可能给你返回一个国内的IP，那就很搞笑了。 2、另外就是如果大厂的IP和你vps机房的IP之间连接的延迟，可能会导致体验问题（不是所有大厂在你vps附近都由cdn节点），简单来说就是不可控。
> 
> 是不是对reality有什么误解？偷的是域名（证书），不是IP。大厂返回哪里的IP并不重要。打个比方，使用微软的域名，那么墙看到的是你在访问microsoft.com，并且IP是你小鸡的IP。那么你一定会疑问，墙要是知道这个IP并不是microsoft.com的，那启不是会被禁吗？没错，但是墙无法确定IP是否为microsoft.com的，因为一个域名可以对应很多个IP，所以它现在只能认为你和小鸡的通信，是在访问microsoft.com。这就是为什么reality中的一个加分项为：与域名IP或CDN段接近，这样更具迷惑性。
> 
> 另外对于延时，只取决于你和你的小鸡之间的连接速度，跟大厂用的哪里的IP和CDN根本没有关系。唯一受影响的只是证书验证的时间快慢而已。那也只是TLS开始通信的前几次握手会有影响。
> 
> 那么再回到你偷自己的域名这个问题来：墙看到的是你在访问你自己的xyz域名，IP就是你的小鸡。这种特性无疑是过于明显，所以会针对这个xyz域名进行封禁。

Domains operated by major companies are generally expected to have PTR records in the DNS. This gives accessibility for clients, including GFW, to discover corresponding domain(s) based on an IP address. Taking this above into consideration, censor(s) still could find that you are accessing a 'legal' website but in a connection to an 'irregular' ip.

**Comment by Xyncgas** [comment]
墙可以增强他的检测力，而你只要露出一个破绽就会被请喝茶

**Comment by l619534951** [comment]
这样和直接设置TLS有什么区别吗

**Comment by Fangliding** [comment]
Not a core issue

**Comment by xiaoxiaomolimicha** [comment]
> > > 怎么会有人偷自己的域名，那跟搭VLESS+WS有啥区别。偷大厂的域名，就是因为大厂现在一时半会不敢封。你弄个不知名的小域名，天天跑流量，分分钟给你拉黑啊。
> > 
> > 
> > 我觉得主要还是由2个原因： 1、你选的那个大厂的域名的IP不一定合适，比如微软，有可能给你返回一个国内的IP，那就很搞笑了。 2、另外就是如果大厂的IP和你vps机房的IP之间连接的延迟，可能会导致体验问题（不是所有大厂在你vps附近都由cdn节点），简单来说就是不可控。
> 
> 是不是对reality有什么误解？偷的是域名（证书），不是IP。大厂返回哪里的IP并不重要。打个比方，使用微软的域名，那么墙看到的是你在访问microsoft.com，并且IP是你小鸡的IP。那么你一定会疑问，墙要是知道这个IP并不是microsoft.com的，那启不是会被禁吗？没错，但是墙无法确定IP是否为microsoft.com的，因为一个域名可以对应很多个IP，所以它现在只能认为你和小鸡的通信，是在访问microsoft.com。这就是为什么reality中的一个加分项为：与域名IP或CDN段接近，这样更具迷惑性。
> 
> 另外对于延时，只取决于你和你的小鸡之间的连接速度，跟大厂用的哪里的IP和CDN根本没有关系。唯一受影响的只是证书验证的时间快慢而已。那也只是TLS开始通信的前几次握手会有影响。
> 
> 那么再回到你偷自己的域名这个问题来：墙看到的是你在访问你自己的xyz域名，IP就是你的小鸡。这种特性无疑是过于明显，所以会针对这个xyz域名进行封禁。

谢谢您这么详细的解答，真的大有收获，茅塞顿开！

**Comment by aijwfsibari** [comment]
> > > 怎么会有人偷自己的域名，那跟搭VLESS+WS有啥区别。偷大厂的域名，就是因为大厂现在一时半会不敢封。你弄个不知名的小域名，天天跑流量，分分钟给你拉黑啊。
> > 
> > 
> > 我觉得主要还是由2个原因： 1、你选的那个大厂的域名的IP不一定合适，比如微软，有可能给你返回一个国内的IP，那就很搞笑了。 2、另外就是如果大厂的IP和你vps机房的IP之间连接的延迟，可能会导致体验问题（不是所有大厂在你vps附近都由cdn节点），简单来说就是不可控。
> 
> 是不是对reality有什么误解？偷的是域名（证书），不是IP。大厂返回哪里的IP并不重要。打个比方，使用微软的域名，那么墙看到的是你在访问microsoft.com，并且IP是你小鸡的IP。那么你一定会疑问，墙要是知道这个IP并不是microsoft.com的，那启不是会被禁吗？没错，但是墙无法确定IP是否为microsoft.com的，因为一个域名可以对应很多个IP，所以它现在只能认为你和小鸡的通信，是在访问microsoft.com。这就是为什么reality中的一个加分项为：与域名IP或CDN段接近，这样更具迷惑性。
> 
> 另外对于延时，只取决于你和你的小鸡之间的连接速度，跟大厂用的哪里的IP和CDN根本没有关系。唯一受影响的只是证书验证的时间快慢而已。那也只是TLS开始通信的前几次握手会有影响。
> 
> 那么再回到你偷自己的域名这个问题来：墙看到的是你在访问你自己的xyz域名，IP就是你的小鸡。这种特性无疑是过于明显，所以会针对这个xyz域名进行封禁。

请问如果自己的xyz域名443端口配置反代一个个人网盘的登陆页面会不会好一些

**Comment by andylau004** [comment]
> > > 怎么会有人偷自己的域名，那跟搭VLESS+WS有啥区别。偷大厂的域名，就是因为大厂现在一时半会不敢封。你弄个不知名的小域名，天天跑流量，分分钟给你拉黑啊。
> > 
> > 
> > 我觉得主要还是由2个原因： 1、你选的那个大厂的域名的IP不一定合适，比如微软，有可能给你返回一个国内的IP，那就很搞笑了。 2、另外就是如果大厂的IP和你vps机房的IP之间连接的延迟，可能会导致体验问题（不是所有大厂在你vps附近都由cdn节点），简单来说就是不可控。
> 
> 是不是对reality有什么误解？偷的是域名（证书），不是IP。大厂返回哪里的IP并不重要。打个比方，使用微软的域名，那么墙看到的是你在访问microsoft.com，并且IP是你小鸡的IP。那么你一定会疑问，墙要是知道这个IP并不是microsoft.com的，那启不是会被禁吗？没错，但是墙无法确定IP是否为microsoft.com的，因为一个域名可以对应很多个IP，所以它现在只能认为你和小鸡的通信，是在访问microsoft.com。这就是为什么reality中的一个加分项为：与域名IP或CDN段接近，这样更具迷惑性。
> 
> 另外对于延时，只取决于你和你的小鸡之间的连接速度，跟大厂用的哪里的IP和CDN根本没有关系。唯一受影响的只是证书验证的时间快慢而已。那也只是TLS开始通信的前几次握手会有影响。
> 
> 那么再回到你偷自己的域名这个问题来：墙看到的是你在访问你自己的xyz域名，IP就是你的小鸡。这种特性无疑是过于明显，所以会针对这个xyz域名进行封禁。

--------


高水平详解、、、
