### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by XuuKoo** [XTLS/Xray-core#230]
看文档目前xray的ss已经到达fullcone，如果tcp数据用了ws+tls进行了掩护，那udp数据是不是相当于ss裸连，会增加服务器暴露、封锁的风险？

**Comment by eMeab** [comment]
udp数据通常占很少带宽. GFW可能不太注意. 不过害怕的话现在的trojan 也能fullcone

**Comment by XuuKoo** [comment]
另外想问下，论udp性能，xray里的trojan会比trojan-gfw更好嘛？

因为这里有个性能测试，当时原生trojan的udp性能是不如vmess的：[https://github.com/v2ray/discussion/issues/818]()

```
二、发送UDP数据包，每个包1KB，共发10万个包

服务器发包给客户端

协议                包/秒       与vless对比
loopback            54525          4.48
vmess (tls tcp)     12656          1.04
Vless (tls tcp)     12171          1.00
Trojan (tls)         4338          0.36
客户端发包给服务器

协议                包/秒      与vless对比
loopback            59347         5.79
Vless (tls tcp)     10256         1.00
vmess (tls tcp)     10108         0.99
Trojan (tls)         2833         0.28
```

**Comment by XuuKoo** [comment]
> udp数据通常占很少带宽. GFW可能不太注意. 不过害怕的话现在的trojan 也能fullcone

另外请问socks协议是udp over tcp吗？

**Comment by rprx** [comment]
今天写一篇文章讲 UDP

**Comment by XuuKoo** [comment]
> 今天写一篇文章讲 UDP

谢谢

**Comment by AkinoKaede** [comment]
> 看文档目前xray的ss已经到达fullcone，如果tcp数据用了ws+tls进行了掩护，那udp数据是不是相当于ss裸连，会增加服务器暴露、封锁的风险？

是的，根据 Shadowsocks 白皮书第 4.6 节第 2 条，UDP 不会被插件转发

**Comment by zjy2200656** [comment]
可以请教下各位大佬怎么开放vps所有端口吗

**Comment by Butterflyflower** [comment]
@zjy2200656 用Debian系统
