### ISSUE TITLE
Game Voice chat not working

### ISSUE THREAD

**Issue by Eidreven** [XTLS/Xray-core#2309]
**Hello, I have a problem with an in-game voice, not functioning. I using xray tls websocket vless with ssl still no voice in game. Game that i play is Valorant. Need Help. TQ**

**Comment by MikeISL** [comment]
这个东西我知道，是sniffing 问题，关闭它，要不你得让Vivox 域名下的所有IP不要经过代理

**Comment by do02fw** [comment]
Use openvpn+udp
