### ISSUE TITLE
xtls-rprx-vision 使用打不开Google

### ISSUE THREAD

**Issue by fadang123** [XTLS/Xray-core#2312]
能访问YouTube，twitter 打不开Google，打开Google 显示404  确定了不是浏览器问题，我用Google手机也是这样

**Comment by chika0801** [comment]
你要发下你服务端配置文件才能分析，这是个例问题，你要提供信息才能分析。

**Comment by fadang123** [comment]
不知道是不是服务器问题，第一次部署使用没问题，用了几天突然就Google打不开，然后重装，重新部署就一直这样
{
  "log": {
    "loglevel": "warning",
    "error": "/var/log/xray/error.log",
    "access": "/var/log/xray/access.log"
  },
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "stats": {},
  "policy": {
    "levels": {
      "0": {
        "handshake": 2,
        "connIdle": 128,
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    },
    "system": {
      "statsInboundUplink": true,
      "statsInboundDownlink": true,
      "statsOutboundUplink": true,
      "statsOutboundDownlink": true
    }
  },
  "dns": {
    "servers": [
      "https+local://cloudflare-dns.com/dns-query",
      "1.1.1.1",
      "1.0.0.1",
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "type": "field",
        "protocol": [
          "bittorrent"
        ],
        "outboundTag": "block"
      },
      {
        "type": "field",
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "block"
      },
      {
        "type": "field",
        "ip": [
          "geoip:cn"
        ],
        "outboundTag": "block"
      },
      {
        "type": "field",
        "domain": [
          "geosite:category-ads-all"
        ],
        "outboundTag": "block"
      },
      {
        "type": "field",
        "domain": [
          "domain:ipinfo.io",
          "domain:ip.sb",
          "geosite:openai"
        ],
        "outboundTag": "warp"
      }
    ]
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 32768,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api",
      "sniffing": null
    },
    {
      "tag": "xray-script-xtls-reality",
      "listen": "0.0.0.0",
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "email": "vless@xtls.reality",
            "id": "568048c8-24b3-4ba1-a532-d25d65636535",
            "flow": "xtls-rprx-vision",
            "level": 0
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "show": false,
          "dest": "www.leercapitulo.com:443",
          "xver": 0,
          "serverNames": [
            "leercapitulo.com",
            "www.leercapitulo.com"
          ],
          "privateKey": "0KrT5cDoS8vDLgzAY4lmMRq6wwrn870rCiGOP5PyoHk",
          "shortIds": [
            "",
            "63",
            "6d26",
            "55de6677",
            "ff6e3fbe54897f63"
          ]
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    }
  ],
  "outbounds": [
    {
      "tag": "direct",
      "protocol": "freedom"
    },
    {
      "tag": "block",
      "protocol": "blackhole"
    },
    {
      "tag": "warp",
      "protocol": "socks",
      "settings": {
        "servers": [
          {
            "address": "172.17.0.2",
            "port": 40001
          }
        ]
      }
    }
  ]
}

**Comment by chika0801** [comment]
我查看了你发的服务端配置，它没有任何问题。你需要说你用的什么客户端APP，怎么设置这APP的，要从客户端来分析为什么你就打不开GOOGLE。

**Comment by fadang123** [comment]
用的V2rayNG最新版,没设置APP，就是使用默认设置，然后通过剪切板导入的配置信息

**Comment by fadang123** [comment]
主要一开始几天能用，过了几天就只有Google打不开

**Comment by mclovin-2k** [comment]
小白去用机场啊。
你既不会看配置，也不会看日志。这还搞什么自建。

**Comment by fadang123** [comment]
你这是来显优越了？

**Comment by mclovin-2k** [comment]
> 你这是来显优越了？

首先 这里是 Xray-core 的Issue区 就算你用的NG有问题也不应该发在这里。
其次 你提供的信息太少  就算发到NG区 也没有人能解决
最后 你姿势水平太差 比你强也体现不出来优越性

**Comment by Cl-He-O** [comment]
能 404 就是打开了

**Comment by fadang123** [comment]
就是别的twitter什么都能打开，就只有Google 404

**Comment by yaoyao-moe** [comment]
跳转到了
https://google.cn/m
吧

ip送中了……or 缓存不干净

用 https://google.com/ncr

**Comment by fadang123** [comment]
是这个，谢谢

**Comment by WordsWorthLess** [comment]
说一下我的离奇经历，一台香港的NAT VPS配置了cn域名及CN IP走黑洞以后，YouTube访问正常，但是谷歌主页偶尔莫名其妙地跳403，后来在服务端配置路由 gstatic.com这个域名走直连就好了，可能你的问题也与此有关

看你的路由配置，domainStrategy用的是IPIfNonMatch, 如果域名没有匹配到基于域名的规则，就解析成IP重新匹配一次IP规则，你的域名规则只有openai、查ip地址的网站以及广告规则，那其它域名基本上都要重新解析一次再匹配IP规则
如果你的gstatic.com被解析成CN的ip地址，那可能就匹配到那条黑洞的规则，导致谷歌访问异常.


试试添加一条路由规则，并将这个规则放置在geosite:cn > block这个规则前
```
{
"type": "field",
"domain": [ "gstatic.com" ],
"outboundTag": "direct"
}

```
又或者添加一个dns server配置，并将这个dns服务器在servers中置顶
```
{
"address": "8.8.8.8",
"domains": [ "gstatic.com" ],
"expectIPs": [ "geoip:us" , "geoip:hk" ]
}
```
