### ISSUE TITLE
x-ui面板的xray配置文件如何转化为单独的xray文件

### ISSUE THREAD

**Issue by zkx8525** [XTLS/Xray-core#2313]
{
"dns": {
    "hosts": {
      "geosite:netflix": "6.6.6.6",
      "geosite:disney": "6.6.6.6"
    },
     "servers": [
      "8.8.8.8",
      "1.1.1.1"
    ]
  },
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {"domainStrategy": "UseIP"}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "policy": {
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ]
  },
  "stats": {}
}
以上的xray面板配置代码在xui面板的xray配置中设置即可使用，如果不用xui面板，直接编辑xray的配置文件上述代码要如何配置转化呢，求帮助！！！

**Comment by FranzKafkaYu** [comment]
@zkx8525 x-ui生成的配置文件:/usr/local/x-ui/bin/config.json，直接使用该配置即可。

**Comment by Fangliding** [comment]
@FranzKafkaYu 温馨提示 前往不要尝试直接在安装xui机器上编辑这个文件（）

**Comment by zkx8525** [comment]
可是并不能解锁nf，我现在是只安装了xray，然后xray文件里面有一条节点信息，我不知道怎么把xui解锁配置文件修改到xray的文件里

**Comment by zkx8525** [comment]
@FranzKafkaYu 好像不能直接弄xui的配置文件，我把xui的代码复制到xray里面，没啥用

**Comment by FranzKafkaYu** [comment]
> @FranzKafkaYu 好像不能直接弄xui的配置文件，我把xui的代码复制到xray里面，没啥用

你需要的是将/usr/local/x-ui/bin/config.json文件的内容复制到xray core所使用的配置文件内，修改节点自身相关信息，其余不做修改。

**Comment by zkx8525** [comment]
@FranzKafkaYu 我xray的节点是vmess，这个代码是任意门的节点，我从inbound到outbound之间替换了vmess节点还是不行

**Comment by chika0801** [comment]
我猜你问题是：你有一个vps b解nf，你现在连的是vpa a，你想修改vps a的配置，让nf的域名，转到vps b上去，你不会写配置，是吗？

**Comment by zkx8525** [comment]
@chika0801 我以前是直接用的xui面板把我发的配置文件放到xui的xray配置文件，改一下里面的ip就能解锁nf，但是我现在不用xui面板了，直接用的xray，我想的是怎么改才能达到跟xui一样的效果，这是具体xui改xray配置解锁nf的教程：https://bulianglin.com/archives/netflix4.html

**Comment by chika0801** [comment]
> @chika0801 我以前是直接用的xui面板把我发的配置文件放到xui的xray配置文件，改一下里面的ip就能解锁nf，但是我现在不用xui面板了，直接用的xray，我想的是怎么改才能达到跟xui一样的效果，这是具体xui改xray配置解锁nf的教程：https://bulianglin.com/archives/netflix4.html

要么，你发你现在的服务端配置，我直接在上面帮你改下，要不，我发个示例，你自己改一下？
