### ISSUE TITLE
关于vless+ws+tls套一个SOKCKS5的住宅IP，用proxy全局出站无法连通的问题

### ISSUE THREAD

**Issue by Mr250luch** [XTLS/Xray-core#2318]
这边有个sokcs5的住宅IP代理，想给用vless的vps去用，这边vps的配置全部走这个住宅IP，客户端能连通，但无法上网。。。然后如果用分流的方式在outbounds保留freedom,再用rule规则制定域名去走proxy，就能用了。。但我想所有的流量都去这个住宅IP的sokcs5，请问我这写的有问题吗？

想要实现的方式是：家庭网关 — vps（vless ws+tls）— socks5服务器 — 外网

这个是能正常使用的配置，但要制定域名去分流：
{
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "proxy",
      "protocol": "socks",
      "settings": {
        "servers": [
          {
            "address": "xxx.xxx.xxx.xxx,
            "port": xxxx,
            "users": [
              {
                "user": "xxxxx",
                "pass": "xxxxx"
              }
            ]
          }
        ]
      }
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "policy": {
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
    "routing": {
    "rules": [
      {
        "type": "field",
        "outboundTag": "proxy",
        "domain": [
          "ip.gs",
          "geosite:openai",
          "geosite:netflix",
          "geosite:facebook",
          "geosite:paypal",
          "geosite:twitter",
          "geosite:amazon",
          "geosite:disney",
        ]
      },
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ]
  },
  "stats": {}
}

这个是我写的全部走sokcs5出站，能连上但没法上网：
{
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "socks",
      "settings": {
        "servers": [
          {
            "address": "xxx.xxx.xxx.xxx,
            "port": xxxx,
            "users": [
              {
                "user": "xxxxx",
                "pass": "xxxxx"
              }
            ]
          }
        ]
      }
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "policy": {
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
    "routing": {
    "rules": [      
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ]
  },
  "stats": {}
}

**Comment by chika0801** [comment]
你试一下入站加域名嗅探参数

```
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls",
                    "quic"
                ]
            }
```

要分析需要你用 **这个是我写的全部走sokcs5出站，能连上但没法上网：** 这套配置，日志开Debug，然后访问下，把过程中的日志帖上来看看。

**Comment by Mr250luch** [comment]
> 

按照您的方法在入站哪里加了嗅探，这么写的：
{
  "inbounds": [
    {
      "tag": "****.json",
      "port": 50107,
      "listen": "127.0.0.1",
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "****"
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "ws",
        "security": "none",
        "wsSettings": {
          "path": "/****",
          "headers": {
            "Host": "****"
          }
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls",
          "quic"
        ]
      }
    }
  ]
}

出站还是我主楼贴的全部走代理的方法，现在都连不通了，运行日志显示是这个：
2023/07/11 04:23:01 127.0.0.1:39404 accepted tcp:127.0.0.1:0 [api -> api]
2023/07/11 04:23:10 172.71.214.240:0 accepted tcp:49.4.37.181:5223 [VLESS-WS-TLS-www.teradyne.net.json >> proxy]
2023/07/11 04:23:11 127.0.0.1:50546 accepted tcp:127.0.0.1:0 [api -> api]
2023/07/11 04:23:24 172.71.214.240:0 accepted tcp:www.google.com:443 [VLESS-WS-TLS-www.teradyne.net.json >> proxy]
2023/07/11 04:23:26 162.158.179.99:0 accepted tcp:www.google.com:443 [VLESS-WS-TLS-www.teradyne.net.json >> proxy]
2023/07/11 04:23:27 162.158.179.99:0 accepted tcp:49.4.37.181:443 [VLESS-WS-TLS-www.teradyne.net.json >> proxy]
2023/07/11 04:23:28 172.71.214.240:0 accepted tcp:www.google.com:443 [VLESS-WS-TLS-www.teradyne.net.json >> proxy]
2023/07/11 04:23:31 127.0.0.1:38086 accepted tcp:127.0.0.1:0 [api -> api]
2023/07/11 04:23:33 162.158.179.99:0 accepted tcp:www.google.com:443 [VLESS-WS-TLS-www.teradyne.net.json >> proxy]
2023/07/11 04:23:39 172.71.214.240:0 accepted tcp:www.google.com:443 [VLESS-WS-TLS-www.teradyne.net.json >> proxy]
2023/07/11 04:23:41 172.71.214.240:0 accepted tcp:www.google.com:443 [VLESS-WS-TLS-www.teradyne.net.json >> proxy]
2023/07/11 04:23:42 162.158.179.99:0 accepted tcp:www.google.com:443 [VLESS-WS-TLS-www.teradyne.net.json >> proxy]
2023/07/11 04:23:43 172.71.210.210:0 accepted tcp:www.google.com:443 [VLESS-WS-TLS-www.teradyne.net.json >> proxy]
2023/07/11 04:23:44 172.71.214.240:0 accepted tcp:www.google.com:443 [VLESS-WS-TLS-www.teradyne.net.json >> proxy]
2023/07/11 04:23:52 162.158.179.99:0 accepted tcp:www.google.com:443 [VLESS-WS-TLS-www.teradyne.net.json >> proxy]
2023/07/11 04:23:53 172.71.214.240:0 accepted tcp:www.google.com:443 [VLESS-WS-TLS-www.teradyne.net.json >> proxy]
2023/07/11 04:23:58 172.71.210.210:0 accepted tcp:49.4.37.181:443 [VLESS-WS-TLS-www.teradyne.net.json >> proxy]
2023/07/11 04:24:01 127.0.0.1:37622 accepted tcp:127.0.0.1:0 [api -> api]
2023/07/11 04:24:04 162.158.179.99:0 accepted tcp:www.google.com:443 [VLESS-WS-TLS-www.teradyne.net.json >> proxy]
2023/07/11 04:24

错误日志显示：
2023/07/11 04:24:04 [Warning] [1049108270] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > proxy/socks: server rejects request: 2
2023/07/11 04:24:16 [Warning] [1998827735] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > proxy/socks: server rejects request: 2
2023/07/11 04:24:16 [Warning] [3193581085] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > proxy/socks: server rejects request: 2
2023/07/11 04:24:18 [Warning] [3320534786] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > proxy/socks: server rejects request: 2
2023/07/11 04:24:20 [Warning] [1315063256] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > proxy/socks: server rejects request: 2
2023/07/11 04:24:21 [Warning] [1985037718] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > proxy/socks: server rejects request: 2
2023/07/11 04:24:22 [Warning] [1207041969] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > proxy/socks: server rejects request: 2
2023/07/11 04:24:28 [Warning] [2803082549] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > proxy/socks: server rejects request: 2

还有就是想问下这样代理socks出站能支持udp吗？现在我这路由器装了clsah走链式代理(先vlemss后socks5）能正常上网使用，就是没法udp

**Comment by chika0801** [comment]
我总结一下需要的信息

你这是在客户端你想问客户端配置怎么配吗？

如果是，你要说清楚你现在的环境，比如你上面提到的 **现在我这路由器装了clsah走链式代理(先vlemss后socks5）能正常上网使用，就是没法udp** 我们知道你的环境才能帮你分析

这环境我帮不了你，因为我没这样用过。

你提到你详细的使用环境描述后，你一般要提供各代理软件你具体的配置文件，别人才能进一步分析，不然不这样做，求助等于没效率。

**Comment by Mr250luch** [comment]
> 我总结一下需要的信息
> 
> 你这是在客户端你想问客户端配置怎么配吗？
> 
> 如果是，你要说清楚你现在的环境，比如你上面提到的 **现在我这路由器装了clsah走链式代理(先vlemss后socks5）能正常上网使用，就是没法udp** 我们知道你的环境才能帮你分析
> 
> 这环境我帮不了你，因为我没这样用过。
> 
> 你提到你详细的使用环境描述后，你一般要提供各代理软件你具体的配置文件，别人才能进一步分析，不然不这样做，求助等于没效率。

不好意思，最后那段问题和我说的问题无关 引起了误解，我删除了。我是想问在服务器端的配置问题，不是客户端问题😥

**Comment by chika0801** [comment]
> > 我总结一下需要的信息
> > 你这是在客户端你想问客户端配置怎么配吗？
> > 如果是，你要说清楚你现在的环境，比如你上面提到的 **现在我这路由器装了clsah走链式代理(先vlemss后socks5）能正常上网使用，就是没法udp** 我们知道你的环境才能帮你分析
> > 这环境我帮不了你，因为我没这样用过。
> > 你提到你详细的使用环境描述后，你一般要提供各代理软件你具体的配置文件，别人才能进一步分析，不然不这样做，求助等于没效率。
> 
> 不好意思，最后那段问题和我说的问题无关 引起了误解，我删除了。我是想问在服务器端的配置问题，不是客户端问题😥

建议你发下你服务端配置（重新发份，完整版吧，一般没什么隐藏，注意下json格式方便看）如果你发的这配置，是失败的结果 ，你把日志也附上来，日志用Debug级别，才能进一步分析。

**Comment by Mr250luch** [comment]
> > > 我总结一下需要的信息
> > > 你这是在客户端你想问客户端配置怎么配吗？
> > > 如果是，你要说清楚你现在的环境，比如你上面提到的 **现在我这路由器装了clsah走链式代理(先vlemss后socks5）能正常上网使用，就是没法udp** 我们知道你的环境才能帮你分析
> > > 这环境我帮不了你，因为我没这样用过。
> > > 你提到你详细的使用环境描述后，你一般要提供各代理软件你具体的配置文件，别人才能进一步分析，不然不这样做，求助等于没效率。
> > 
> > 
> > 不好意思，最后那段问题和我说的问题无关 引起了误解，我删除了。我是想问在服务器端的配置问题，不是客户端问题😥
> 
> 建议你发下你服务端配置（重新发份，完整版吧，一般没什么隐藏，注意下json格式方便看）如果你发的这配置，是失败的结果 ，你把日志也附上来，日志用Debug级别，才能进一步分析。

不好意思打扰倒了，这是我服务端的配置，依然只能从客户端连通节点没法传输数据，debug的日志一直重复这几段贴在最下面了（*是我的socks5服务器的地址和账号密码)
```
{
  "log": {
    "access": "/var/log/xray/access.log",
    "error": "/var/log/xray/error.log",
    "loglevel": "debug"
   },
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "tag": "proxy_a",
      "protocol": "socks",
      "settings": {
        "servers": [
          {
            "address": "****",
            "port": ****,
            "users": [
              {
                "user": "*****",
                "pass": "*****"
              }
            ]
          }
        ]
      }
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "policy": {
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "rules": [
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ]
  },
  "stats": {}
}
```

2023/07/12 14:37:12 [Debug] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:xxxx
2023/07/12 14:37:14 [Info] [1321903743] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to transfer request payload > websocket: close 1000 (normal)
2023/07/12 14:37:41 [Info] [3639962393] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > EOF
2023/07/12 14:37:43 [Info] [4145505862] proxy/vless/inbound: firstLen = 271
2023/07/12 14:37:43 [Info] [4145505862] proxy/vless/inbound: received request for udp:8.8.8.8:53
2023/07/12 14:37:43 [Info] [4145505862] app/dispatcher: default route for udp:8.8.8.8:53
2023/07/12 14:37:43 [Debug] [4145505862] app/proxyman/outbound: proxying to proxy_a for dest udp:8.8.8.8:53
2023/07/12 14:37:43 [Info] [4145505862] proxy/freedom: connection opened to udp:8.8.8.8:53, local endpoint 0.0.0.0:0, remote endpoint 0.0.0.0:0

**Comment by chika0801** [comment]
我看了下配置，和日志，我帮不上了。你现在有一个疑问，你说你发的配置是服务端的，它的入站从配置上看是一个自由门监听的本机62789端口。

你描述的是你是用 （vless ws+tls） 组合连接到服务端。你能说明一下这点吗？

**Comment by Mr250luch** [comment]
这个问题研究了几天发现问题所在，入站协议用vless或vmess的话只能代理出站的tcp，我把network只写tcp的话是能正常使用了，把network删了或者写成udp的话就是能连通节点无法传输数据了。。。但把入站协议换成别的 比如ssr这种，tcp和udp都能同时出站代理了，这个是我成功使用的配置文件。
'''
{
  "inbounds": [
    {
      "tag": "我的VLESS协议入站",
      "port": XXXXX,
      "listen": "127.0.0.1",
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "XXXXXXXX"
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "ws",
        "security": "none",
        "wsSettings": {
          "path": "/XXXX",
          "headers": {
            "Host": "XXXXXX"
          }
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "proxy",
      "protocol": "socks",
      "settings": {
        "servers": [
          {
            "address": "我的住宅IP服务(不可操作)",
            "port": XXXX,
            "users": [
              {
                "user": "XXXXX",
                "pass": "XXXXX"
              }
            ]
          }
        ]
      }
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "policy": {
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
    "routing": {
    	"rules": [
      {
        "type": "field",
        "network": "tcp",
        "inboundTag": [
          "我的VLESS协议入站"
        ],
        "outboundTag": "proxy"
      }
    ]
  },
  "stats": {}
}
'''

**Comment by zypfff** [comment]
看起来就知道很高级的样子我过来看看热闹
