### ISSUE TITLE
How Can we allow just special websites and IP addresses in the X-ray configuration?

### ISSUE THREAD

**Issue by mobagheri** [XTLS/Xray-core#2319]
I want to modify the following code to just allow users connect to the special websites and IP addresses and rest of them will be blocked. For example, my users just have and access to "facebook.com" and "143.65.xxx.xxx". Please help me. Thanks

{
  "log": {
    "loglevel": "warning",
    "access": "./access.log",
    "error": "./error.log"
  },
  "api": {
    "tag": "api",
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ]
  },
  "inbounds": [
    {
      "tag": "api",
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "blocked",
      "protocol": "blackhole",
      "settings": {}
    },
    {
      "tag": "WARP",
      "protocol": "socks",
      "settings": {
        "servers": [
          {
            "address": "127.0.0.1",
            "port": 40000
          }
        ]
      }
    },
    {
      "tag": "IPv4",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIPv4"
      }
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "statsUserDownlink": true,
        "statsUserUplink": true
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api"
      },
      {
        "type": "field",
        "outboundTag": "blocked",
        "ip": [
          "geoip:private",
          "geoip:ir",
          "geoip:cn",
          "geoip:ru"
        ]
      },
      {
        "type": "field",
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ]
      },
      {
        "type": "field",
        "outboundTag": "WARP",
        "domain": [
          "geosite:google",
          "geosite:openai",
          "geosite:netflix",
          "geosite:spotify"
        ]
      },
      {
        "type": "field",
        "outboundTag": "IPv4",
        "domain": [
          "geosite:google",
          "geosite:netflix"
        ]
      },
      {
        "type": "field",
        "outboundTag": "blocked",
        "domain": [
          "geosite:category-ads-all",
          "ext:iran.dat:ads",
          "geosite:speedtest",
          "regexp:.*\\.ir$",
          "ext:iran.dat:ir",
          "ext:iran.dat:other",
          "geosite:category-ir",
          "geosite:cn",
          "regexp:.*\\.cn$",
          "geosite:category-gov-ru",
          "regexp:.*\\.ru$"
        ]
      }
    ]
  },
  "stats": {}
}

**Comment by chika0801** [comment]
For the inbound part, it is recommended that you add domain sniffing related parameters to ensure that the content of the request into Xray is the domain name.

For the outbound part, put blackhole (blocking) in the first place. The matching logic of outbound is from top to bottom, the request that doesn't have a hit in the routing section will go to the 1st outbound by default, i.e. black hole.

For the routing part, refer to the example and you should be able to understand it. It is also recommended to use "domainStrategy": "IPIfNonMatch", the parameter

```
{
    "log":{
        "loglevel":"warning",
        "access":"./access.log",
        "error":"./error.log"
    },
    "inbounds":[
        {
            "tag":"api",
            "listen":"127.0.0.1",
            "port":62789,
            "protocol":"dokodemo-door",
            "settings":{
                "address":"127.0.0.1"
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls",
                    "quic"
                ]
            }
        }
    ],
    "outbounds":[
        {
            "tag":"block",
            "protocol":"blackhole"
        },
        {
            "tag":"direct",
            "protocol":"freedom"
        }
    ],
    "routing":{
        "domainStrategy":"IPIfNonMatch",
        "rules":[
            {
                "type":"field",
                "outboundTag":"direct",
                "domain":[
                    "geosite:facebook"
                ]
            },
            {
                "type": "field",
                "ip": [
                    "geoip:cn",
                    "143.65.xxx.xxx"
                ],
                "outboundTag": "direct"
            }
        ]
    }
}
```

**Comment by chika0801** [comment]
https://xtls.github.io/Xray-docs-next/document/level-1/routing-lv1-part1.html

This is a tutorial to learn Xray configuration, it's only in Chinese, you translate it and you should be able to understand the processing logic pretty quickly.

**Comment by mobagheri** [comment]
> For the inbound part, it is recommended that you add domain sniffing related parameters to ensure that the content of the request into Xray is the domain name.
> 
> For the outbound part, put blackhole (blocking) in the first place. The matching logic of outbound is from top to bottom, the request that doesn't have a hit in the routing section will go to the 1st outbound by default, i.e. black hole.
> 
> For the routing part, refer to the example and you should be able to understand it. It is also recommended to use "domainStrategy": "IPIfNonMatch", the parameter
> 
> ```
> {
>     "log":{
>         "loglevel":"warning",
>         "access":"./access.log",
>         "error":"./error.log"
>     },
>     "inbounds":[
>         {
>             "tag":"api",
>             "listen":"127.0.0.1",
>             "port":62789,
>             "protocol":"dokodemo-door",
>             "settings":{
>                 "address":"127.0.0.1"
>             },
>             "sniffing": {
>                 "enabled": true,
>                 "destOverride": [
>                     "http",
>                     "tls",
>                     "quic"
>                 ]
>             }
>         }
>     ],
>     "outbounds":[
>         {
>             "tag":"block",
>             "protocol":"blackhole"
>         },
>         {
>             "tag":"direct",
>             "protocol":"freedom"
>         }
>     ],
>     "routing":{
>         "domainStrategy":"IPIfNonMatch",
>         "rules":[
>             {
>                 "type":"field",
>                 "outboundTag":"direct",
>                 "domain":[
>                     "geosite:facebook"
>                 ]
>             },
>             {
>                 "type": "field",
>                 "ip": [
>                     "geoip:cn",
>                     "143.65.xxx.xxx"
>                 ],
>                 "outboundTag": "direct"
>             }
>         ]
>     }
> }
> ```

Thank you for your assistance. It is greatly appreciated that you took the time to answer my questions.

**Comment by mobagheri** [comment]
> https://xtls.github.io/Xray-docs-next/document/level-1/routing-lv1-part1.html
> 
> This is a tutorial to learn Xray configuration, it's only in Chinese, you translate it and you should be able to understand the processing logic pretty quickly.

Awesome. I am going to read it. Thanks.

**Comment by chika0801** [comment]
You're welcome.

**Comment by mobagheri** [comment]
> The key changes:
> 
> Added a blackhole outbound first to block unmatched traffic.
> 
> Allow direct access only to facebook.com and the specified IP.
> 
> Other traffic will hit the blackhole and be blocked.
> 
> This restricts access to just the specified domain and IP while blocking everything else.

Thank you for pointing out such important points.
