### ISSUE TITLE
Have a problem in set the dns server

### ISSUE THREAD

**Issue by aabbccgg** [XTLS/Xray-core#2324]
I had set  a dns server in xray, but it seems not work as well as what I want.
In my opinion, it would focused to use my locally deployed DNS service at 172.17.0.1. However, Xray used my system's default DNS 8.8.8.8 instead.
Here is my config:
   ```
 "dns": {
        "servers": [
            "172.17.0.1"
        ],
        "queryStrategy": "UseIP",
        "disableCache": true,
        "disableFallback": true,
        "disableFallbackIfMatch": true,
        "tag": "dns_inbound"
    },
    "routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "type": "field",
                "ip": [
                    "geoip:cn"
                ],
                "outboundTag": "block"
            }
        ]
    },
```

**Comment by chika0801** [comment]
> https://xtls.github.io/Xray-docs-next/config/outbounds/freedom.html#outboundconfigurationobject

> When the destination address is a domain name, configure the corresponding value, Freedom's behavior pattern is as > > > follows.

> "AsIs": Freedom obtains an IP through the system DNS server, and sends a connection to this domain.
> "UseIP", "UseIPv4" and "UseIPv6": Xray uses the [built-in DNS server](https://xtls.github.io/Xray-docs-next/config/dns.html) to > resolve the IP, and issue a connection to this domain. The default value is "AsIs".



Since I don't have your complete configuration, I presume that you should be adding the above parameter on the way out, and this XRAY will use the XRAY's internal DNS (i.e. 127.0.0.1) on the way out. But this setup is usually used on the server side. You mean you client side, you need more information from you if you want further help.
