### ISSUE TITLE
developer.android和developers.google都是403

### ISSUE THREAD

**Issue by GameByHand** [XTLS/Xray-core#2325]
这个问题困扰我很久了。
Google.com都是正常的，gmail也能用，搜索也可以。 google scholar也能用。
就是开发者不能，返回403错误。
部署的主机上用curl访问developers又是正常的。
现在不知道是客户端问题，还是服务器端的问题。
试过好多版本xray都一样，从1.5到1.8.3都是一样的结果。

**Comment by chika0801** [comment]
你要发下你服务端配置文件，猜下可能你用了geosite cn 阻止的规则。

**Comment by GameByHand** [comment]
> 你要发下你服务端配置文件，猜下可能你用了 geosite cn 阻止的规则。

我看是用了 geosite cn ， 这个不能用？

**Comment by GameByHand** [comment]
{
  "log": {
    "loglevel": "debug"
  },
  "api": {
    "tag": "api",
    "services": ["HandlerService", "LoggerService", "StatsService"]
  },
  "inbounds": [
    {
      "tag": "api",
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "blocked",
      "protocol": "blackhole",
      "settings": {}
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "statsUserDownlink": true,
        "statsUserUplink": true
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "inboundTag": ["api"],
        "outboundTag": "api"
      },
      {
        "type": "field",
        "outboundTag": "blocked",
        "ip": ["geoip:private"]
      },
      {
        "type": "field",
        "outboundTag": "blocked",
        "protocol": ["bittorrent"]
      }
    ]
  },
  "stats": {}
}

**Comment by GameByHand** [comment]
是因为Google使用了172开头的IP，被当作是私有ip了？

**Comment by chika0801** [comment]
看了你配置，没发现问题。你将日志改为debug。然后在客户端访问那2个不行的网址，你在服务端看下日志，粘贴上来帮你分析下。

**Comment by GameByHand** [comment]
我做了两个改动
去掉 屏蔽private
使用ipv4连接Google 就好了
谢谢 @[chika0801](https://github.com/chika0801)

**Comment by chika0801** [comment]
这也行？解决就好，下回通过看日志debug级别，自己也能查。。。

**Comment by GameByHand** [comment]
![image](https://github.com/XTLS/Xray-core/assets/139455099/9f35fc52-8ee3-4bbf-a114-276e89a77212)
这个问题可以关闭了
