### ISSUE TITLE
用v2rayNG测试是可以ping通的，但就是上不了任何网站

### ISSUE THREAD

**Issue by zhaifangzhi** [XTLS/Xray-core#2326]
用v2rayNG测试是可以ping通的，但就是上不了任何网站，有大佬能看下是什么问题吗？ 以下是我的服务端配置文件:
{
    "log": {
        "loglevel": "warning"
    },
    "routing": {
        "domainStrategy": "AsIs",
        "rules": [
            {
                "type": "field",
                "ip": [
                    "geoip:private"
                ],
                "outboundTag": "block"
            }
        ]
    },
    "inbounds": [
        {
            "listen": "0.0.0.0",
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "b3e779ec-3dd9-48af-82c1-99e63cff6e5b",
                        "flow": "xtls-rprx-vision"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "tcp",
                "security": "reality",
                "realitySettings": {
                    "show": true,
                    "dest": "www.amazon.com:443",
                    "xver": 0,
                    "serverNames": [
                        "www.amazon.com"
                    ],
                    "privateKey": "mKFh7EQZdG4OyPCzhNznnO06KyZKspUUS8FygW-GelA",
                    "shortIds": [
                        "78985179e30d4fc6"
                    ]
                }
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls",
                    "quic"
                ]
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "tag": "block"
        }
    ],
    "policy": {
        "levels": {
            "0": {
                "handshake": 2,
                "connIdle": 120
            }
        }
    }
}

以下是我的客户端配置文件:
{
    "log": {
        "loglevel": "warning"
    },
    "inbounds": [
        {
            "listen": "127.0.0.1",
            "port": 1080,
            "protocol": "socks",
            "settings": {
                "udp": true
            }
        },
        {
            "listen": "127.0.0.1",
            "port": 1081,
            "protocol": "http"
        }
    ],
    "outbounds": [
        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "34.172.177.153",
                        "port": 443,
                        "users": [
                            {
                                "id": "b3e779ec-3dd9-48af-82c1-99e63cff6e5b",
                                "encryption": "none",
                                "flow": "xtls-rprx-vision"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "reality",
                "realitySettings": {
                    "show": false,
                    "fingerprint": "chrome",
                    "serverName": "www.amazon.com",
                    "publicKey": "Jug2YYszcv07641aN0Y32dZIPPPYLTHyOFKhXllW8lQ",
                    "shortId": "78985179e30d4fc6",
                    "spiderX": "/"
                }
            },
            "tag": "proxy"
        },
        {
            "protocol": "freedom",
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "tag": "block"
        }
    ]
}

**Comment by lxsq** [comment]
你的UUID、私钥露了个干净。

**Comment by chika0801** [comment]
检查因素有，公私钥是对应的，短id一致，剩下建议更换dest处填的网址试试。

**Comment by GleenJi** [comment]
你得测真链接延迟，ping tcp都是测试vps ip能否ping通

**Comment by GleenJi** [comment]
还有网址可以试试别的，我之前也是试了一些网址，有的网址就是不能用，当然也有可能就是私钥公钥没对应上等问题，你还得看看服务端的xray运行成功了吗，不排除格式错误

**Comment by zhaifangzhi** [comment]
> 还有网址可以试试别的，我之前也是试了一些网址，有的网址就是不能用，当然也有可能就是私钥公钥没对应上等问题，你还得看看服务端的xray运行成功了吗，不排除格式错误

解决了，还有个问题就是VLESS-XTLS-uTLS-REALITY使用非443端口影响伪装效果吗？另外怎么在配置中禁回国流量？

**Comment by chika0801** [comment]
你是怎么解决的？

**Comment by zhaifangzhi** [comment]
> 你是怎么解决的？
嗯，就是看了你的example，谢谢！另外，VLESS-XTLS-uTLS-REALITY使用非443端口影响伪装效果吗？如果影响的化，服务端如何通过shortid的不同进行限速？或者aws lightsail虚拟机多用户根本就不需要限速？反正官方也没说明带宽是多少

**Comment by chika0801** [comment]
那你关闭本iss下

**Comment by zhaifangzhi** [comment]
> 那你关闭本iss下

关闭了，但是最后的问题还是在心上啊....

**Comment by chika0801** [comment]
非443有人这样用，没人反馈过什么，你可自己试，非必须443其它端口都能用。

xray配置中没限制功能。
