### ISSUE TITLE
io:read/write on closed pipe

### ISSUE THREAD

**Issue by AIDA64S** [XTLS/Xray-core#2328]
经典老问题，我是用的Vless+Xtls+Reality，用了有一段时间了，结果今天准备使用发现不能用了，我一开始以为是时间的问题，所以同步手机时间，外加服务器使用chrony同步服务器时间，但仍然这样

**Comment by FranzKafkaYu** [comment]
如dest使用www.microsoft.com，请更换为其他符合条件的网站域名

**Comment by AIDA64S** [comment]
> 如dest使用www.microsoft.com，请更换为其他符合条件的网站域名

我试试

**Comment by FranzKafkaYu** [comment]
@AIDA64S 如已解决，请关闭该issue。
