### ISSUE TITLE
安装完VLESS-XTLS-uTLS-REALITY后，如何解锁netflix及hbo等流媒体服务啊？

### ISSUE THREAD

**Issue by zhaifangzhi** [XTLS/Xray-core#2329]
以下是我现在的xray配置文件： 
"log": {
        "loglevel": "warning",
    "access": "/var/log/xray/access.log",
    "error": "/var/log/xray/error.log"
    },
    "routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "type": "field",
                "ip": [
                    "geoip:cn",
                    "geoip:private"
                ],
                "outboundTag": "block"
            }
        ]
    },
    "inbounds": [
        {
            "listen": "0.0.0.0",
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "285a4afc-21fc-11ee-bdec-4bc1d2e4e530",
                        "flow": "xtls-rprx-vision"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "tcp",
                "security": "reality",
                "realitySettings": {
                    "show": false,
                    "dest": "www.lovelive-anime.jp:443",
                    "xver": 0,
                    "serverNames": [
                        "www.lovelive-anime.jp"
                    ],
                    "privateKey": "EEOPIeiZr6fLkDTVij1ScxVHRwut2B4GCHhzGKBQQlk",
                    "shortIds": [
                        ""
                    ]
                }
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls",
                    "quic"
                ]
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "tag": "block"
        }
    ],
    "policy": {
        "levels": {
            "0": {
                "handshake": 2,
                "connIdle": 120
            }
        }
    }
}

**Comment by Michaol** [comment]
问错地方了

**Comment by zhaifangzhi** [comment]
> 问错地方了

那应该在哪里问啊？

**Comment by JobAbout** [comment]
你的服务器的 ip 如果不干净会被网飞禁止访问，可以在网上搜索教程用 cloudflare 的 warp 程序来解锁

**Comment by chika0801** [comment]
假设你VPS A是翻墙用，回国好线路。VPS B是全解NF的。参考此示例

https://github.com/chika0801/Xray-examples/blob/main/unlock_netflix.md

**Comment by zhaifangzhi** [comment]
> 假设你VPS A是翻墙用，回国好线路。VPS B是全解NF的。参考此示例
> 
> https://github.com/chika0801/Xray-examples/blob/main/unlock_netflix.md

试了下，还是不行啊
我的vps A现在配置如下:
{
    "log": {
        "loglevel": "warning",
    "access": "/var/log/xray/access.log",
    "error": "/var/log/xray/error.log"
    },
    "routing": {
        "domainStrategy": "IPIfNonMatch",
         "rules": [
        {
            "type": "field",
            "ip": [
                "geoip:cn",
                "geoip:private"
            ],
            "outboundTag": "block"
        },
        {
            "type": "field",
            "outboundTag": "block",
            "protocol": ["bittorrent"]
        },
        {
            "type": "field",
            "domain": ["geosite:netflix"],
            "outboundTag": "netflix"
        }
    ]
    },
    "inbounds": [
        {
            "listen": "0.0.0.0",
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "285a4afc-21fc-11ee-bdec-4bc1d2e4e530",
                        "flow": "xtls-rprx-vision"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "tcp",
                "security": "reality",
                "realitySettings": {
                    "show": false,
                    "dest": "www.lovelive-anime.jp:443",
                    "xver": 0,
                    "serverNames": [
                        "www.lovelive-anime.jp"
                    ],
                    "privateKey": "EEOPIeiZr6fLkDTVij1ScxVHRwut2B4GCHhzGKBQQlk",
                    "shortIds": [
                        ""
                    ]
                }
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls",
                    "quic"
                ]
            }
        }
    ],
    "outbounds": [
    {
        "protocol": "freedom",
        "tag": "direct"
    },
    {
        "protocol": "blackhole",
        "tag": "block"
    },
    {
        "protocol": "shadowsocks",
        "settings": {
                "servers": [
                    {
                        "address": "192.18.136.160",
                        "port": 443,
                        "method": "2022-blake3-aes-128-gcm",
                        "password": "0HBc9+QT7jEc1/HiyrrFlQ=="
                    }
                ]
            },
            "tag": "netflix"
    }
],
    "policy": {
        "levels": {
            "0": {
                "handshake": 2,
                "connIdle": 120
            }
        }
    }
}

VPS B现在配置如下:
{
    "log": {
        "loglevel": "warning"
    },
    "inbounds": [
        {
            "listen": "0.0.0.0",
            "port": 443,
            "protocol": "shadowsocks",
            "settings": {
                "method": "2022-blake3-aes-128-gcm",
                "password": "0HBc9+QT7jEc1/HiyrrFlQ==",
                "network": "tcp,udp"
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "settings": {
                "domainStrategy": "UseIPv4"
            },
            "tag": "direct"
        }
    ]
}

手机上v2rayNG设置及netflix错误如下:
![NG1](https://github.com/XTLS/Xray-core/assets/11608991/882bf925-b263-42b2-86ba-8c8c12281dc5)
![NG2](https://github.com/XTLS/Xray-core/assets/11608991/1ffeb0a9-7484-438b-9025-1d389c6eb5cc)
![netflix](https://github.com/XTLS/Xray-core/assets/11608991/03132beb-e1a5-4cbe-af61-536fa7a33d2b)

shadowsocks改成80端口也试了下，还是不行

**Comment by zhaifangzhi** [comment]
> 假设你VPS A是翻墙用，回国好线路。VPS B是全解NF的。参考此示例
> 
> https://github.com/chika0801/Xray-examples/blob/main/unlock_netflix.md

另外最后一百行的access.log内容如下：
2023/07/15 11:04:44 110.54.156.135:15187 accepted tcp:www.google.com.hk:443 [direct]
2023/07/15 11:04:44 110.54.156.135:15189 accepted tcp:optimizationguide-pa.googleapis.com:443 [direct]
2023/07/15 11:04:44 110.54.156.135:15191 accepted tcp:privacyportaluat.onetrust.com:443 [direct]
2023/07/15 11:04:44 110.54.156.135:15197 accepted udp:8.8.8.8:53 [direct]
2023/07/15 11:04:45 110.54.156.135:41891 accepted tcp:mtalk.google.com:5228 [direct]
2023/07/15 11:04:46 110.54.156.135:41893 accepted tcp:www.netflix.com:443 [netflix]
2023/07/15 11:04:47 110.54.156.135:41898 accepted tcp:ssl.gstatic.com:443 [direct]
2023/07/15 11:04:48 110.54.156.135:41901 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:04:48 110.54.156.135:41900 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:04:48 110.54.156.135:41899 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:04:48 110.54.156.135:41905 accepted tcp:beincrypto-com.webpkgcache.com:443 [direct]
2023/07/15 11:04:48 110.54.156.135:41908 accepted tcp:id.google.com.hk:443 [direct]
2023/07/15 11:04:49 110.54.156.135:41907 accepted tcp:content-autofill.googleapis.com:443 [direct]
2023/07/15 11:04:51 110.54.156.135:41921 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:04:51 110.54.156.135:41920 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:04:51 110.54.156.135:41922 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:04:52 110.54.156.135:41926 accepted tcp:chrome.cloudflare-dns.com:443 [direct]
2023/07/15 11:04:52 110.54.156.135:41929 accepted tcp:tunnel.googlezip.net:443 [direct]
2023/07/15 11:04:52 110.54.156.135:41927 accepted tcp:chrome.cloudflare-dns.com:443 [direct]
2023/07/15 11:04:53 110.54.156.135:41936 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:04:54 110.54.156.135:41934 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:04:54 110.54.156.135:41935 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:04:54 110.54.156.135:41941 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:04:54 110.54.156.135:41940 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:04:54 110.54.156.135:41942 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:04:54 110.54.156.135:41952 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:04:54 110.54.156.135:41953 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:04:55 110.54.156.135:41958 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:04:55 110.54.156.135:41957 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:04:55 110.54.156.135:41959 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:04:55 110.54.156.135:41962 accepted tcp:chrome.cloudflare-dns.com:443 [direct]
2023/07/15 11:04:55 110.54.156.135:41961 accepted tcp:tunnel.googlezip.net:443 [direct]
2023/07/15 11:04:55 110.54.156.135:41963 accepted tcp:chrome.cloudflare-dns.com:443 [direct]
2023/07/15 11:04:58 110.54.156.135:41979 accepted tcp:clients4.google.com:443 [direct]
2023/07/15 11:05:00 110.54.156.135:41989 accepted tcp:adservice.google.com.hk:443 [direct]
2023/07/15 11:05:11 110.54.156.135:15245 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:05:11 110.54.156.135:15247 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:05:11 110.54.156.135:15246 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:05:12 110.54.156.135:15248 accepted tcp:in.appcenter.ms:443 [direct]
2023/07/15 11:05:12 110.54.156.135:15251 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:05:12 110.54.156.135:15249 accepted tcp:outlook.office365.com:443 [direct]
2023/07/15 11:05:12 110.54.156.135:15250 accepted tcp:outlook.office.com:443 [direct]
2023/07/15 11:05:13 110.54.156.135:15253 accepted tcp:login.microsoftonline.com:443 [direct]
2023/07/15 11:05:13 110.54.156.135:15254 accepted tcp:login.microsoftonline.com:443 [direct]
2023/07/15 11:05:16 110.54.156.135:15287 accepted tcp:outlook.office.com:443 [direct]
2023/07/15 11:05:16 110.54.156.135:15286 accepted tcp:outlook.office.com:443 [direct]
2023/07/15 11:05:16 110.54.156.135:15289 accepted tcp:outlook.office365.com:443 [direct]
2023/07/15 11:05:16 110.54.156.135:15290 accepted tcp:login.microsoftonline.com:443 [direct]
2023/07/15 11:05:17 110.54.156.135:15300 accepted tcp:outlook.office365.com:443 [direct]
2023/07/15 11:05:17 110.54.156.135:15301 accepted tcp:outlook.office.com:443 [direct]
2023/07/15 11:05:18 110.54.156.135:15299 accepted tcp:outlook.office.com:443 [direct]
2023/07/15 11:07:30 110.54.156.135:42374 accepted tcp:159.138.87.251:5223 [direct]
2023/07/15 11:07:31 110.54.156.135:42375 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:07:31 110.54.156.135:42382 accepted tcp:www.google.com:443 [direct]
2023/07/15 11:07:31 110.54.156.135:42383 accepted tcp:mtalk.google.com:5228 [direct]
2023/07/15 11:07:34 110.54.156.135:42388 accepted tcp:www.google.com:443 [direct]
2023/07/15 11:07:34 110.54.156.135:42389 accepted tcp:91.108.56.117:443 [direct]
2023/07/15 11:07:34 110.54.156.135:42390 accepted tcp:91.108.56.153:443 [direct]
2023/07/15 11:07:36 110.54.156.135:42393 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:07:36 110.54.156.135:42394 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:07:36 110.54.156.135:42395 accepted tcp:chrome.cloudflare-dns.com:443 [direct]
2023/07/15 11:07:37 110.54.156.135:42396 accepted tcp:chrome.cloudflare-dns.com:443 [direct]
2023/07/15 11:07:37 110.54.156.135:42398 accepted tcp:chrome.cloudflare-dns.com:443 [direct]
2023/07/15 11:07:37 110.54.156.135:42397 accepted tcp:chrome.cloudflare-dns.com:443 [direct]
2023/07/15 11:07:37 110.54.156.135:42401 accepted tcp:www.google.com.hk:443 [direct]
2023/07/15 11:07:37 110.54.156.135:42402 accepted tcp:www.google.com:443 [direct]
2023/07/15 11:07:40 110.54.156.135:42411 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:07:40 110.54.156.135:42413 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:07:40 110.54.156.135:42412 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:07:41 110.54.156.135:42414 accepted tcp:optimizationguide-pa.googleapis.com:443 [direct]
2023/07/15 11:07:41 110.54.156.135:42416 accepted tcp:beincrypto-com.webpkgcache.com:443 [direct]
2023/07/15 11:07:41 110.54.156.135:42417 accepted tcp:tunnel.googlezip.net:443 [direct]
2023/07/15 11:07:41 110.54.156.135:42418 accepted tcp:chrome.cloudflare-dns.com:443 [direct]
2023/07/15 11:07:44 110.54.156.135:42421 accepted tcp:chrome.cloudflare-dns.com:443 [direct]
2023/07/15 11:07:46 110.54.156.135:15726 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:07:46 110.54.156.135:15727 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:07:47 110.54.156.135:15730 accepted tcp:sgminorshort.wechat.com:80 [direct]
2023/07/15 11:07:47 110.54.156.135:15733 accepted tcp:chrome.cloudflare-dns.com:443 [direct]
2023/07/15 11:07:47 110.54.156.135:15734 accepted tcp:chrome.cloudflare-dns.com:443 [direct]
2023/07/15 11:07:48 110.54.156.135:15739 accepted tcp:adservice.google.com.hk:443 [direct]
2023/07/15 11:07:48 110.54.156.135:15744 accepted tcp:encrypted-tbn0.gstatic.com:443 [direct]
2023/07/15 11:07:48 110.54.156.135:15743 accepted tcp:encrypted-tbn0.gstatic.com:443 [direct]
2023/07/15 11:07:49 110.54.156.135:15779 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:07:50 110.54.156.135:15798 accepted tcp:play.googleapis.com:443 [direct]
2023/07/15 11:07:51 110.54.156.135:15825 accepted tcp:clients4.google.com:443 [direct]
2023/07/15 11:07:52 110.54.156.135:15888 accepted tcp:www.netflix.com:443 [netflix]
2023/07/15 11:07:52 110.54.156.135:15894 accepted tcp:assets.nflxext.com:443 [netflix]
2023/07/15 11:07:52 110.54.156.135:15893 accepted tcp:cdn.cookielaw.org:443 [direct]
2023/07/15 11:07:54 110.54.156.135:15914 accepted tcp:geolocation.onetrust.com:443 [direct]
2023/07/15 11:07:56 110.54.156.135:42435 accepted tcp:ae.nflximg.net:443 [netflix]
2023/07/15 11:07:56 110.54.156.135:42436 accepted tcp:www.netflix.com:443 [netflix]
2023/07/15 11:07:57 110.54.156.135:42437 accepted tcp:ichnaea-web.netflix.com:443 [netflix]
2023/07/15 11:07:58 110.54.156.135:42447 accepted tcp:www.netflix.com:443 [netflix]
2023/07/15 11:07:58 110.54.156.135:42449 accepted tcp:ichnaea-web.netflix.com:443 [netflix]
2023/07/15 11:07:59 110.54.156.135:42461 accepted udp:1.1.1.1:53 [direct]
2023/07/15 11:07:59 110.54.156.135:42463 accepted tcp:metrics1.data.hicloud.com:6447 [block]
2023/07/15 11:08:01 110.54.156.135:42466 accepted tcp:metrics1.data.hicloud.com:6447 [block]
2023/07/15 11:08:02 110.54.156.135:42471 accepted tcp:metrics1.data.hicloud.com:6447 [block]
2023/07/15 11:08:03 110.54.156.135:42468 accepted tcp:sgminorshort.wechat.com:80 [direct]
2023/07/15 11:08:04 110.54.156.135:42478 accepted tcp:metrics1.data.hicloud.com:6447 [block]

**Comment by chika0801** [comment]
你在SSH软件中，看VPSA和B，Xray的日志，命令是 journalctl -u xray --output cat -f。比如你看到VPS B接收到NF域名的请求了，就表示你A和B的配置是没有问题的。

至于你发的手机访问NF主页注册失败的图片，原因我不清楚为什么注册不起。

这是一个检查VPSIP是不是全解的命令 https://github.com/chika0801/tool#%E6%B5%81%E5%AA%92%E4%BD%93%E8%A7%A3%E9%94%81

**Comment by zhaifangzhi** [comment]
> 你在SSH软件中，看VPSA和B，Xray的日志，命令是 journalctl -u xray --output cat -f。比如你看到VPS B接收到NF域名的请求了，就表示你A和B的配置是没有问题的。
> 
> 至于你发的手机访问NF主页注册失败的图片，原因我不清楚为什么注册不起。
> 
> 这是一个检查VPSIP是不是全解的命令 https://github.com/chika0801/tool#%E6%B5%81%E5%AA%92%E4%BD%93%E8%A7%A3%E9%94%81
> 
> 补充：我看了你发的A和B的配置，你配置都写对了的。所以你先要确定你VPS B的IP是不是全解NF，用上面链接的命令可以查看。

VPS B上运行journalctl -u xray --output cat -f，输出如下：
2023/07/15 11:07:57 138.3.210.163:34418 accepted ichnaea-web.netflix.com:443 [direct]
2023/07/15 11:07:58 138.3.210.163:34430 accepted www.netflix.com:443 [direct]
2023/07/15 11:07:58 138.3.210.163:34436 accepted ichnaea-web.netflix.com:443 [direct]
2023/07/15 13:29:51 138.3.210.163:37436 accepted www.netflix.com:443 [direct]
2023/07/15 13:29:51 138.3.210.163:37450 accepted assets.nflxext.com:443 [direct]
2023/07/15 13:29:54 138.3.210.163:37460 accepted ae.nflximg.net:443 [direct]
2023/07/15 13:29:55 138.3.210.163:37470 accepted ichnaea-web.netflix.com:443 [direct]
2023/07/15 13:29:55 138.3.210.163:37476 accepted www.netflix.com:443 [direct]
2023/07/15 13:29:56 138.3.210.163:37484 accepted www.netflix.com:443 [direct]
2023/07/15 13:29:56 138.3.210.163:37488 accepted ichnaea-web.netflix.com:443 [direct]
....

运行bash <(curl -L -s check.unlock.media)后，输出如下：
输入数字  [4]: [ 跨国平台+北美平台 ]检测
输入数字  [5]: [ 跨国平台+南美平台 ]检测
输入数字  [6]: [ 跨国平台+欧洲平台 ]检测
输入数字  [7]: [跨国平台+大洋洲平台]检测
......
请输入正确数字或直接按回车:4
 [流媒体平台及游戏区域限制测试]

脚本适配OS: CentOS 6+, Ubuntu 14.04+, Debian 8+, MacOS, Android (Termux), iOS (iSH)

 ** 正在测试IPv4解锁情况
--------------------------------
 ** 您的网络为: Oracle Cloud (192.18.*.*)
============[ Multination ]============
 Dazn:                                  No
 HotStar:                               No
 Disney+:                               Yes (Region: US)
 Netflix:                               Originals Only
 YouTube Premium:                       Yes
 Amazon Prime Video:                    Yes (Region: US)
 TVBAnywhere+:                          Yes
 iQyi Oversea Region:                   US
 Viu.com:                               No
 YouTube CDN:                           San Jose, CA
 Netflix Preferred CDN:                 San Jose, CA
 Spotify Registration:                  No
 Steam Currency:                        USD
 ChatGPT:                               No
=======================================
===========[ North America ]===========
 FOX:                                   Yes
 Hulu:                                  Failed
 NFL+:                                  Yes
 ESPN+:[Sponsored by Jam]               No
 Epix:                                  No
 Starz:                                 No
 Philo:                                 Yes
 FXNOW:                                 Yes
 TLC GO:                                Yes
 HBO Max:                               Yes
 Shudder:                               Yes
 BritBox:                               Yes
 Crackle:                               Yes
 CW TV:                                 Yes
 A&E TV:                                Yes
 NBA TV:                                Yes
 NBC TV:                                Yes
 Fubo TV:                               No
 Tubi TV:                               Yes
 Sling TV:                              Yes
 Pluto TV:                              Yes
 Acorn TV:                              Yes
 SHOWTIME:                              Yes
 encoreTVB:                             Yes
 Funimation:                            Yes (Region: US)
 Discovery+:                            Yes
 Paramount+:                            Yes
 Peacock TV:                            Yes
 Popcornflix:                           Yes
 Crunchyroll:                           Yes
 KBS American:                          No
 KOCOWA:                                Yes
 Maths Spot:                            Failed
 ---CA---
 CBC Gem:                               No
 Crave:                                 Yes
=======================================
当前主机不支持IPv6,跳过...
本次测试已结束，感谢使用此脚本

另外，VPS B上输入cat /proc/version，输出：Linux version 5.4.17-2136.310.7.el7uek.aarch64 (mockbuild@build-ol7-aarch64.oracle.com) (gcc version 7.3.0 20180125 (Red Hat 7.3.0-7) (GCC)) #2 SMP Tue Aug 9 19:23:53 PDT 2022

**Comment by chika0801** [comment]
从上面你发的信息，你VPS B的甲骨文IP，NF只解自制。你买台其它VPS用这方法试试了。

**Comment by RPRX** [comment]
183 的 Vision 不支持中转，main 支持 https://github.com/XTLS/Xray-core/actions/runs/5545742665

**Comment by zhaifangzhi** [comment]
> 从上面你发的信息，你VPS B的甲骨文IP，NF只解自制。你买台其它VPS用这方法试试了。
> 
> 或你把VPS B套上Warp测下Warp的IP一般能全解NF。

把vps B换成aws虚拟机可以了，还有两个问题
1，如果这台vps B太多人使用，会不会对其ip造成污染，以致于往后无法解锁netflix？一般多少用户会饱和？
2，如果还要解锁chatgpt(我测了，也是支持的)，是不是就在rules中加个{
"type": "field",
"domain": ["geosite:chatgpt"],
"outboundTag": "chatgpt"
}
然后在outbounds中再加个{
"protocol": "shadowsocks",
"settings": {
"servers": [
{
"address": "192.18.136.160",
"port": 443,
"method": "2022-blake3-aes-128-gcm",
"password": "0HBc9+QT7jEc1/HiyrrFlQ=="
}
]
},
"tag": "chatgpt"
}，是这样吗？还是有其它更简洁的写法？本身有...怕封号...不敢测

以下是我现在vps A的配置：
{
"log": {
"loglevel": "warning",
"access": "/var/log/xray/access.log",
"error": "/var/log/xray/error.log"
},
"routing": {
"domainStrategy": "IPIfNonMatch",
"rules": [
{
"type": "field",
"ip": [
"geoip:cn",
"geoip:private"
],
"outboundTag": "block"
},
{
"type": "field",
"outboundTag": "block",
"protocol": ["bittorrent"]
},
{
"type": "field",
"domain": ["geosite:netflix"],
"outboundTag": "netflix"
}
]
},
"inbounds": [
{
"listen": "0.0.0.0",
"port": 443,
"protocol": "vless",
"settings": {
"clients": [
{
"id": "285a4afc-21fc-11ee-bdec-4bc1d2e4e530",
"flow": "xtls-rprx-vision"
}
],
"decryption": "none"
},
"streamSettings": {
"network": "tcp",
"security": "reality",
"realitySettings": {
"show": false,
"dest": "www.lovelive-anime.jp:443",
"xver": 0,
"serverNames": [
"www.lovelive-anime.jp"
],
"privateKey": "EEOPIeiZr6fLkDTVij1ScxVHRwut2B4GCHhzGKBQQlk",
"shortIds": [
""
]
}
},
"sniffing": {
"enabled": true,
"destOverride": [
"http",
"tls",
"quic"
]
}
}
],
"outbounds": [
{
"protocol": "freedom",
"tag": "direct"
},
{
"protocol": "blackhole",
"tag": "block"
},
{
"protocol": "shadowsocks",
"settings": {
"servers": [
{
"address": "192.18.136.160",
"port": 443,
"method": "2022-blake3-aes-128-gcm",
"password": "0HBc9+QT7jEc1/HiyrrFlQ=="
}
]
},
"tag": "netflix"
}
],
"policy": {
"levels": {
"0": {
"handshake": 2,
"connIdle": 120
}
}
}
}

**Comment by iopq** [comment]
> > wrong place
> 
> Where should I ask?

I did a tutorial that shows how to install cloudflare warp and use it ONLY for certain domains

https://iopq.wordpress.com/2023/03/23/set-up-xray-vless-vision-with-a-cloudflare-warp-backup/

you could try this approach

**Comment by zhaifangzhi** [comment]
> > > wrong place
> > 
> > 
> > Where should I ask?
> 
> I did a tutorial that shows how to install cloudflare warp and use it ONLY for certain domains
> 
> https://iopq.wordpress.com/2023/03/23/set-up-xray-vless-vision-with-a-cloudflare-warp-backup/
> 
> you could try this approach

Already change vps, it work. Why need to use wrap with shared ip, seems more danger

**Comment by chika0801** [comment]
> 1，如果这台vps B太多人使用，会不会对其ip造成污染，以致于往后无法解锁netflix？一般多少用户会饱和？
太多人？我没给太多人用，都是个人用，不知道。什么时候这IP不能全解NF，一般你给别人用，别人有用IOS系统的手机和平板，IP就掉得快了（已成熟的网上经验）。

**Comment by chika0801** [comment]
现在许多VPS IP也解GPT了，你实在要像NF这样转到VPS B的形式，就在路由规则中加对应的，或套warp都是方法

参考 https://github.com/chika0801/Xray-examples/blob/main/wireguard.md 另外建议你发配置学下语法格式，不是你一直有运气遇得到有耐心复制你的格式化后帮你看配置和回复的人。

**Comment by iopq** [comment]
> > > > wrong place
> > > 
> > > 
> > > Where should I ask?
> > 
> > 
> > I did a tutorial that shows how to install cloudflare warp and use it ONLY for certain domains 
> > [https://iopq.wordpress.com/2023/03/23/set-up-xray-vless-vision-with-a-cloudflare-warp-backup/ ](https://iopq.wordpress.com/2023/03/23/set-up-xray-vless-vision-with-a-cloudflare-warp-backup/)
> > you could try this approach
> 
> Already change vps, it work. Why need to use wrap with shared ip, seems more danger

it depends, for ChatGPT warp works the best because they don't block it

**Comment by GleenJi** [comment]
本质就是使用分流功能，将匹配的流媒体的geosite和geoip分流到能解锁的vps上（或者购买解锁流媒体的dns）

**Comment by zypfff** [comment]
> 你在SSH软件中，看VPSA和B，Xray的日志，命令是journalctl -u xray --output cat -f。比如你看到VPS B接收到NF域名的请求了，就说明你A和B的配置是没有问题的。
> 
> 由于你发的手机访问NF主页注册失败的图片，原因我狮子为什么注册不起。
> 
> 这是一个检查VPSIP不是完整解压的命令https://github.com/chika0801/tool#%E6%B5%81%E5%AA%92%E4%BD%93%E8%A7%A3%E9%94%81
> 
> 补充：我看了你发的A和B的配置，你的配置都写对了。所以你首先要确定你的VPS B的IP不是全解NF，用上面链接的命令查看。

大家好初来乍到对许多问题都很不解所以来请求大佬的帮助
在我用xui搭建tcp reality的协议后
在小火箭上连接
然后把还原伪装度100的ios下载tk后
发现tk显示没有网络连接  但是视频可以显示出来也可以往下刷就是不播放
然后我查找资料说我小火箭的代理没有开启  但是当我开启小火箭的代理模式后我发现我的节点网络直接用不了
请问大家是不是在协议方面搭建的和tk需要网络配置不符合 还是我手机上的小火箭设置不正确
希望有人能给我一些宝贵的建议谢谢看到的各位！！！！

**Comment by zypfff** [comment]
> 假设你的VPS A是翻墙用，回国好线路。VPS B是全解NF的。参考此示例
> 
> https://github.com/chika0801/Xray-examples/blob/main/unlock_netflix.md

您好请问可以给您留一个我的联系方式吗我有一些类似的问题想请教一下这是我的邮箱19071043325@163.com
希望您看到

**Comment by chika0801** [comment]
> 大家好初来乍到对许多问题都很不解所以来请求大佬的帮助 在我用xui搭建tcp reality的协议后 在小火箭上连接 然后把还原伪装度100的ios下载tk后 发现tk显示没有网络连接 但是视频可以显示出来也可以往下刷就是不播放 然后我查找资料说我小火箭的代理没有开启 但是当我开启小火箭的代理模式后我发现我的节点网络直接用不了 请问大家是不是在协议方面搭建的和tk需要网络配置不符合 还是我手机上的小火箭设置不正确 希望有人能给我一些宝贵的建议谢谢看到的各位！！！！

我没在IOS用过tiktok，听说你如果不想手机只插外国卡看tiktok，要用一些脚本改什么，你自己再去搜下方法了。

**Comment by chika0801** [comment]
> 您好请问可以给您留一个我的联系方式吗我有一些类似的问题想请教一下这是我的邮箱[XXX@163.com]

建议你删除这条信息，保护个人隐私。

**Comment by Fangliding** [comment]
off tpoic
