### ISSUE TITLE
Xray REALITY 已经被识别了吗？

### ISSUE THREAD

**Issue by bluehj777** [XTLS/Xray-core#2330]
xray 1.8.3 从昨天开始，所有几个节点的Xray REALITY都挂了，之前这么用了几个月从来没有问题。这几个节点切换到V2RAY，没有问题，说明节点IP没被封。尝试换XRAY的端口，也解决不了，说明端口也没被封。我纯个人用，也不跑什么大流量，几个地区的节点也是不同的VPS服务商，一个瓦工的，一个斯巴达的，一个越南的小商家

服务器配置

    {
      "port": 443,
      "protocol": "vless",
      "listen": "0.0.0.0",
      "settings": {
        "udp": true,
        "clients": [
          {
            "id": "xxxxx-xxxx-xxxx-xxx-xxxxxxxxx",
            "flow": "xtls-rprx-vision"
          }
        ],
        "decryption": "none"
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "show": false,
          "dest": "www.microsoft.com:443",
          "xver": 0,
          "serverNames": [
            "www.microsoft.com"
          ],
          "privateKey": "CUNYlCf1ECUNYlCf1ECUNYlCf1E",
          "publicKey": "MqjyIXM9TMqjMqjyIXM9TMqjyIXyIXMqjyIXM9TMqjyIX",
          "maxTimeDiff": 0,
          "shortIds": [
            ""
          ]
        }
      }
    }

客户端配置：

  "outbound": {
    "protocol": "vless",
    "settings": {
      "vnext": [
        {
          "address": "节点1",
          "port": 443,
          "users": [
            {
              "id": "xxxxx-xxxx-xxxx-xxx-xxxxxxxxx",
              "alterId": 0,
              "security": "auto",
			  "encryption": "none",
              "flow": "xtls-rprx-vision"
            }
          ]
        }
      ]
    },
          "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "serverName": "www.microsoft.com",
          "fingerprint": "chrome",
          "show": false,
          "publicKey": "MqjyIXM9TMqjMqjyIXM9TMqjyIXyIXMqjyIXM9TMqjyIX",
          "shortId": "",
          "spiderX": ""
        }
      }

**Comment by FranzKafkaYu** [comment]
@bluehj777 参考[链接](https://t.me/projectXtls/153)，简单来说：请更换dest为其他符合条件的网站域名

**Comment by bluehj777** [comment]
> @bluehj777 参考[链接](https://t.me/projectXtls/153)，简单来说：请更换dest为其他符合条件的网站域名

嗯，似乎已解决，确实是www.microsoft.com用不了。谢谢
