### ISSUE TITLE
Vmess dynamic port w/ mKCP unstable issue in recent builds

### ISSUE THREAD

**Issue by heartboiled** [XTLS/Xray-core#2331]
Vmess动态端口+mKCP连线极端不稳定
-
之前自用Vmess动态端口+mKCP，稳定使用很久，安全度过整个6月

近日尝试从1.7.5升级到目前beta最新版，调整设置后上机发现经常会断开连接
同传输配置更换到v2fly或者老版本就无任何问题
怀疑是近期版本的udp相关改动产生影响？

现在暂时平行使用v2fly专门开kcp，但是我本身长期使用xray，xtls-vision也有在使用，
wireguard出口也非常香甜可口，希望有办法可以救一下

**Comment by RPRX** [comment]
Won't fix.

https://github.com/XTLS/Xray-core/issues/2262#issuecomment-1609104744
_我打算在 Golang 官方实现的 QUIC 发布后给 REALITY 加上 QUIC 支持，到时还会删掉现有的 QUIC 和 mKCP 传输层_

**Comment by heartboiled** [comment]
> [#2262 (comment)](https://github.com/XTLS/Xray-core/issues/2262#issuecomment-1609104744) _我打算在 Golang 官方实现的 QUIC 发布后给 REALITY 加上 QUIC 支持，到时还会删掉现有的 QUIC 和 mKCP 传输层_

收到
