### ISSUE TITLE
releaty协议+反连, 是不是偷证书的网站需要变化一下，变成偷国内的网站？

### ISSUE THREAD

**Issue by LearnForDreamK** [XTLS/Xray-core#2337]
我用海外的vps/裸机反连国内的ecs， 这个时候国内的机器就是服务端了，就变成 国外->国内 ， 这个时候偷国外网站的证书是不是有点奇怪。

**Comment by chika0801** [comment]
想了下你说的是有理，这是你国内机当服务端，应该选国内网站。

**Comment by Smallthing** [comment]
别的不说 偷国外你不觉得卡吗 小心国内机被当成间谍抓起来

**Comment by LearnForDreamK** [comment]
> 

我选的亚马逊，速度体感还行😂。  这还能被抓嘛，为啥😨

**Comment by LearnForDreamK** [comment]
> 别的不说 偷国外你不觉得卡吗 小心国内机被当成间谍抓起来

我选的亚马逊，速度体感还行😂。 这还能被抓嘛，为啥😨

**Comment by chika0801** [comment]
> > 别的不说 偷国外你不觉得卡吗 小心国内机被当成间谍抓起来
> 
> 我选的亚马逊，速度体感还行😂。 这还能被抓嘛，为啥😨

你在国内不管是自己办的家宽，还是买的VPS之类，你付钱，就找得到实人，我是这样理解的。
