### ISSUE TITLE
DEST/SNI www.microsoft.com NOT WORKING

### ISSUE THREAD

**Issue by sharon-git** [XTLS/Xray-core#2339]
I tried www.google.com, bing.com.... and many other TLS 1.3 sites.
Nothing works.

any ideas on what to do?

**Comment by chika0801** [comment]
This domain does not have TLS 1.3 Replacing the domain with another one solves the problem. It happened a couple days ago.

**Comment by LearnForDreamK** [comment]
微软的tls降级成1.2了好像，换成dl.google.com

**Comment by sharon-git** [comment]
I tried putting dl.google.com but it still doesn't work.
Any ideas what to do?

**Comment by chika0801** [comment]
> dl.google.com

用这个，有人试了，最后IP被封，你去看Xray TG频道记得发过新闻

**Comment by chika0801** [comment]
> I tried putting dl.google.com but it still doesn't work. Any ideas what to do?

Whether you are configuring it and the client never connects through, or it used to pass and now it doesn't.

REALITY related parameters are those, public and private keys, short ID, DEST fill in the target URL.

The rest is some VPS basics, such as port IP is not normal, backhaul line is good, you need to check these factors yourself. You just type and ask us can only rely on guessing, can only help you here.

**Comment by sharon-git** [comment]
Do i need to generate new keys and short ID if i change to dl.google.com?

**Comment by chika0801** [comment]
Changing the URL of the Dest parameter, and the fact that you change the public and private keys of the server and client, they are 2 problematic points and you deal with them separately.

It's not that you change the URL of the DEST parameter once, you have to change your previous key.

**Comment by sharon-git** [comment]
I looked in the telegram group, someone said to put www.samsung.com.
it's still doesn't work.

I did not generate any new keys, I only changed in config file DEST from www.microsoft.com to www.samsung.com.
NO LUCK! what should I do?

**Comment by FranzKafkaYu** [comment]
@sharon-git  plz show me your configurations,including server side and client side.

**Comment by chika0801** [comment]
You changed the parameters of dest and restarted Xray with the command to take effect, right? If you are installing manually. If you are XUI panel is some other operation. Only you can try it yourself, can't guess other factors. You can try not to use this combination and use other proxy protocols. These are your personal capabilities.

**Comment by sharon-git** [comment]
{
  "log": {
    "loglevel": "warning"
  },
  "inbounds": [ 
    {
      "listen": "0.0.0.0",
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "*************************************",
            "flow": "xtls-rprx-vision"
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "show": false,
          "dest": "www.samsung.com:443",
          "xver": 0,
          "serverNames": [
            "www.samsung.com"
          ],
          "privateKey": "*****************************************************",
          "minClientVer": "1.8.5",
          "shortIds": [ 
            "*******************"
          ]
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    }
  ],
  "routing": {
    "rules": [
      {
        "type": "field",
        "protocol": [
          "bittorrent"
        ],
        "outboundTag": "blocked",
        "ip": [
          "geoip:cn",
          "geoip:private"
        ] 
      }
    ]
  },
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
    "tag": "blocked",
      "protocol": "blackhole",
      "settings": {}
    }
  ]
}


Server: xray-linux-arm32-v5.
Client: v2rayNG Android

getting error net/http: TLS handshake timeout.

**Comment by sharon-git** [comment]
PROBLEM SOLVED!

Downgrade in config:
"minClientVer": "1.8.5",
to
"minClientVer": "1.8.0",

and set DEST www.samsung.com

Now working!

**Comment by chika0801** [comment]
If you had posted your server-side configuration as soon as you arrived, we would have known the problem. If you don't share it, we can only guess from experience.

https://github.com/chika0801/Xray-examples/blob/main/VLESS-XTLS-uTLS-REALITY/config_server.json

Don't add unnecessary parameters indiscriminately, this is an example, please refer to it.

**Comment by chika0801** [comment]
Ok, no thanks, problem solved you need to close this ISS.
