### ISSUE TITLE
VLESS-XTLS-uTLS-REALITY回落域名是否支持套CDN

### ISSUE THREAD

**Issue by TingTing1990** [XTLS/Xray-core#2340]
看了一些脚本和教程有说不支持，但是我的回落域名设置的是Docker的caddy域名并且在CF打开云朵后节点正常
服务器配置：
{
    "log": {
        "disabled": false,
        "level": "info",
        "output": "/usr/local/sing-box/sing-box.log",
        "timestamp": true
    },
    "inbounds": [
        {
            "type": "vless",
            "tag": "vless-in",
            "listen": "::",
            "listen_port": 非443端口,
            "sniff": true,
            "sniff_override_destination": true,
            "users": [
                {
                    "uuid": "隐私",
                    "flow": "xtls-rprx-vision"
                }
            ],
            "tls": {
                "enabled": true,
                "server_name": "Docker反代的域名",
                "reality": {
                    "enabled": true,
                    "handshake": {
                        "server": "Docker反代的域名",
                        "server_port": 443
                    },
                    "private_key": "隐私",
                    "short_id": [
                        "隐私"
                    ]
                }
            }
        }
    ],
    "outbounds": [
        {
            "type": "direct",
            "tag": "direct"
        },
        {
            "type": "block",
            "tag": "block"
        }
    ],
    "route": {
        "geoip": {
            "path": "geoip.db",
            "download_url": "https://github.com/SagerNet/sing-geoip/releases/latest/download/geoip.db",
            "download_detour": "direct"
        },
        "geosite": {
            "path": "geosite.db",
            "download_url": "https://github.com/SagerNet/sing-geosite/releases/latest/download/geosite.db",
            "download_detour": "direct"
        },
        "rules": [
            {
                "geoip": "cn",
                "outbound": "block"
            },
            {
                "geosite": "category-ads-all",
                "outbound": "block"
            }
        ],
        "final": "direct"
    }
}

客服端GUI配置就是服务器填写的IP，端口为服务器的非443端口，其他流控等参数和服务器一致

**Comment by qist** [comment]
本来就可以啊。只是说的你的服务器不支持过cdn与客户端连接。

**Comment by TingTing1990** [comment]
> 本来就可以啊。只是说的你的服务器不支持过cdn与客户端连接。

多谢，我这个服务器配置和客户端的描述没问题吧

**Comment by qist** [comment]
没问题的。能连接就可以了。

**Comment by TingTing1990** [comment]
> 没问题的。能连接就可以了。

感谢！

**Comment by chika0801** [comment]
测试一下推送到群

**Comment by chika0801** [comment]
"handshake": {
"server": "Docker反代的域名",

这里 这个目标网址用不用CDN，REALITY都能用它，你是这意思吧。

**Comment by TingTing1990** [comment]
> 

是的，我在服务器查看日志，发现：

2023-07-19 12:24:11 ERROR [1221108723 155ms] inbound/vless[vless-in]: process connection from [国内地区IP和端口] flow mismatch: expected xtls-rprx-vision, but got none

不知道是否属于正常

**Comment by TingTing1990** [comment]
> ```
> "handshake": {
> "server": "Docker反代的域名",
> ```
> 
> 这里 这个目标网址用不用CDN，REALITY都能用它，你是这意思吧。

原来是[sing-box-examples](https://github.com/chika0801/sing-box-examples)的大佬，是说有点眼熟，配置文件就是用的大佬扩了下的...sing-box服务器端支持TUIC V5吗？看官方文档里的入站没有这个

**Comment by chika0801** [comment]
> > 
> 
> 是的，我在服务器查看日志，发现：
> 
> 2023-07-19 12:24:11 ERROR [1221108723 155ms] inbound/vless[vless-in]: process connection from [国内地区IP和端口] flow mismatch: expected xtls-rprx-vision, but got none
> 
> 不知道是否属于正常
> 
> PS：登录ssh看的日志

如果你客户端翻墙没遇到开网页上tg有什么异常，我从来不看两端日志，我也不知道你发这日志产生的原因

**Comment by chika0801** [comment]
> > ```
> > "handshake": {
> > "server": "Docker反代的域名",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这里 这个目标网址用不用CDN，REALITY都能用它，你是这意思吧。
> 
> 原来是[sing-box-examples](https://github.com/chika0801/sing-box-examples)的大佬，是说有点眼熟，配置文件就是用的大佬扩了下的...sing-box服务器端支持TUIC V5吗？看官方文档里的入站没有这个

singbox不支持tuic

ps 才发现你在xray这问singbox的配置，挺有理

**Comment by TingTing1990** [comment]
> 
哈哈，主要是问REALITY，贴配置主要是排查看配置是否有问题，不同核心只是格式不一样，原理还是差不多的

话说大佬这个错误日志正常吗？
2023-07-19 12:24:11 ERROR [1221108723 155ms] inbound/vless[vless-in]: process connection from [国内地区IP和端口] flow mismatch: expected xtls-rprx-vision, but got none

**Comment by chika0801** [comment]
你出现看到这错误，你客户端能不能正常翻墙嘛？不能就要检查填的各参数了。我这样才能回答你。

**Comment by TingTing1990** [comment]
能够正常翻墙

**Comment by chika0801** [comment]
https://github.com/XTLS/Xray-core/issues/2340#issuecomment-1641436257

前面说了，我是不会管的，建议你也是不要管吧

**Comment by TingTing1990** [comment]
> [#2340 (comment)](https://github.com/XTLS/Xray-core/issues/2340#issuecomment-1641436257)
> 
> 前面说了，我是不会管的，建议你也是不要管吧

多谢，我是直接拉下来了，没注意，不好意思

**Comment by chika0801** [comment]
> > > 
> > 
> > 
> > 哈哈，主要是问REALITY，贴配置主要是排查看配置是否有问题，不同核心只是格式不一样，原理还是差不多的
> > 说话大佬国内这个错误日志正常吗？ 2023-07-19 12:24:11 ERROR [1221108723 155ms] inbound/vless[vless-in]: process connection from [地区IP和端口] flow Mismatch:预期xtls-rprx-vision，但没有得到
> 
> > > 
> > 
> > 
> > 哈哈，主要是问REALITY，贴配置主要是排查看配置是否有问题，不同核心只是格式不一样，原理还是差不多的
> > 说话大佬国内这个错误日志正常吗？ 2023-07-19 12:24:11 ERROR [1221108723 155ms] inbound/vless[vless-in]: process connection from [地区IP和端口] flow Mismatch: 预期xtls-rprx-vision，但没有得到
> 
> 您好我的reality协议在小火箭中打开代理模式后无法使用请问是什么原因

小火箭是最新版本，如果打不开任何网页，说明你填的那些配置信息里有什么地方没填对。

一个填法示例 https://github.com/chika0801/Xray-examples/tree/main/VLESS-XTLS-uTLS-REALITY#shadowrocket---v2231-%E5%8F%8A%E4%BB%A5%E4%B8%8A%E7%89%88%E6%9C%AC-%E9%85%8D%E7%BD%AE%E7%A4%BA%E4%BE%8B

**Comment by zypfff** [comment]
谢谢大佬虽然我现在的水平看懂还是有点困难但是我会一直学习的再次感谢🙏
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年07月26日 10:28 |
| 收件人 | XTLS/Xray-core ***@***.***> |
| 抄送人 | zypfff ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [XTLS/Xray-core] VLESS-XTLS-uTLS-REALITY回落域名是否支持套CDN (Issue #2340) |

哈哈，主要是问REALITY，贴配置主要是排查看配置是否有问题，不同核心只是格式不一样，原理还是差不多的
说话大佬国内这个错误日志正常吗？ 2023-07-19 12:24:11 ERROR [1221108723 155ms] inbound/vless[vless-in]: process connection from [地区IP和端口] flow Mismatch:预期xtls-rprx-vision，但没有得到

哈哈，主要是问REALITY，贴配置主要是排查看配置是否有问题，不同核心只是格式不一样，原理还是差不多的
说话大佬国内这个错误日志正常吗？ 2023-07-19 12:24:11 ERROR [1221108723 155ms] inbound/vless[vless-in]: process connection from [地区IP和端口] flow Mismatch: 预期xtls-rprx-vision，但没有得到

您好我的reality协议在小火箭中打开代理模式后无法使用请问是什么原因

小火箭是最新版本，如果打不开任何网页，说明你填的那些配置信息里有什么地方没填对。

一个填法示例 https://github.com/chika0801/Xray-examples/tree/main/VLESS-XTLS-uTLS-REALITY#shadowrocket---v2231-%E5%8F%8A%E4%BB%A5%E4%B8%8A%E7%89%88%E6%9C%AC-%E9%85%8D%E7%BD%AE%E7%A4%BA%E4%BE%8B
