### ISSUE TITLE
Introduce sing box reality daily telegram

### ISSUE THREAD

**Issue by GhostOfSarina** [XTLS/Xray-core#2343]
I would like to introduce the sing-box daily telegram service. It is a small script written in a bash script and the Golang language. It automatically makes vmess reality based on a sing box and sends it into the telegram channel with diffrent SNI.  Based on the cronjob schedule send a new configuration to the channel. 

If you don't mind, introduce this project as a [sing-box-daily-telegram](https://github.com/GhostOfSarina/sing-box-daily-telegram) in your Readme.
We built this project in memory of Sarina Esmailzadeh, who was killed in Iran.

https://github.com/GhostOfSarina/sing-box-daily-telegram

**Comment by chika0801** [comment]
https://github.com/XTLS/Xray-core/discussions

Suggest you post this in the discussion forum.
