### ISSUE TITLE
请教一下 xray 能拦截指定域名或路径的请求吗?  

### ISSUE THREAD

**Issue by wangz-code** [XTLS/Xray-core#2344]
比方 https://qianwen.aliyun.com/waterMark

尝试这样写不生效
``` 
{

                 "domain": [                   
                    "qianwen.aliyun.com/waterMark"
                ],
                "outboundTag": "block",
                "type": "field"
}


```

看了文档尝试用了  attrs  的 path 属性 但是好像没生效
```
    {
                "attrs":{
                    ":path": "/waterMark"
                },
                "outboundTag": "block",
                "type": "field"
     },

```

我想要使用这个域名下其他内容, 最好能把匹配的路径比如广告之类的进黑洞

**Comment by chika0801** [comment]
https://xtls.github.io/Xray-docs-next/config/routing.html#ruleobject

完整匹配：由 "full:" 开始，余下部分是一个域名。当此域名完整匹配目标域名时，该规则生效。例如 "full:xray.com" 匹配 "xray.com" 但不匹配 "www.xray.com"。

看了下你的要求，你试试这个了。

**Comment by flowerinsnowdh** [comment]
既然使用 HTTPS，就意味着浏览器到服务器之间的信道是加密的，而路径位于头中，自然也是被加密的，无论是 Xray 客户端、节点服务器还是中间人都无法窃取

**Comment by Fangliding** [comment]
path是加密读不到的(https的话)

**Comment by wangz-code** [comment]
> https://xtls.github.io/Xray-docs-next/config/routing.html#ruleobject
> 
> 完整匹配：由 "full:" 开始，余下部分是一个域名。当此域名完整匹配目标域名时，该规则生效。例如 "full:xray.com" 匹配 "xray.com" 但不匹配 "www.xray.com"。
> 
> 看了下你的要求，你试试这个了。

试过了不行,  看楼下说的好像这参数部分会被加密无法读取 谢谢了
