### ISSUE TITLE
socks5密码认证模式是不是坏了?

### ISSUE THREAD

**Issue by CCCAUCHY** [XTLS/Xray-core#2348]
```
rejected  proxy/socks: no matching auth method
2023/07/19 14:37:14 [Info] [1847585350] app/proxyman/inbound: connection ends > proxy/socks: failed to read request > proxy/socks: no matching auth method
```
不管换什么密码都认证不了

**Comment by dianso** [comment]
dont lose say
please use english

**Comment by cty123** [comment]
Could you double check if the auth is turned on, like here: https://github.com/XTLS/Xray-examples/blob/main/Socks5-TLS/config_server.json#L23. Also please attach your config.json, it's hard to tell if it's a bug or a misconfiguration.

**Comment by CCCAUCHY** [comment]
> Could you double check if the auth is turned on, like here: https://github.com/XTLS/Xray-examples/blob/main/Socks5-TLS/config_server.json#L23. Also please attach your config.json, it's hard to tell if it's a bug or a misconfiguration.

YES. Because no one can connect it except "noauth".

**Comment by ansonhorse** [comment]
STILL face this issue:
```
tcp:x.x.x.x:17719 rejected  proxy/socks: no matching auth method
```

```
Xray 1.8.13 (Xray, Penetrates Everything.) 3120ca4 (go1.22.3 linux/amd64)
A unified platform for anti-censorship.
```

```json
{
  "log": {
    "access": "/var/log/xray/access.log",
    "error": "/var/log/xray/error.log",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": 10808,
      "protocol": "socks",
      "settings": {
        "auth": "password",
        "accounts": [
          {
            "user": "user",
            "pass": "a123456bb"
          }
        ],
        "udp": true,
        "ip": "127.0.0.1",
        "userLevel": 0
      }
    }
  ]
}
```

@CCCAUCHY I wonder if you have solved the problem? 🤝

**Comment by jjqtony** [comment]
"auth": "password"
