### ISSUE TITLE
Xray的Trojan-Go模式似乎与Trojan-Go的mux不兼容

### ISSUE THREAD

**Issue by Cathgao** [XTLS/Xray-core#235]
lean的SSR+已经使用Xray替换掉独立的Trojan-Go，但实际使用中发现问题。SSR+使用Trojan模式并开启TLS没有问题，但一旦开启MUX就无法上网。服务端为Trojan-Go最新版，有以下报错：
```
Jan 27 13:36:31 vultrguest trojan-go[105654]: [ERROR] 2021/01/27 13:36:31 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | freedom failed to dial v1.mux.cool:**** | dial tcp: lookup v1.mux.cool on 108.61.10.10:53: no such host
Jan 27 13:36:31 vultrguest trojan-go[105654]: [INFO]  2021/01/27 13:36:31 user ********************  from ****:16767 tunneling to v1.mux.cool:**** closed sent: 0 B recv: 0 B
```
 关闭MUX后一切正常

#https://github.com/fw876/helloworld/issues/351

**Comment by guanhemeng** [comment]
首先做个科普：
trojan是协议，trojan-gfw/trojan-go是trojan的实现，一个c语言编写，一个go语言编写。
xray的trojan支持是从v2ray继承来的，包括mux。ray系的mux公认存在一定问题（不建议使用，还没有修），
trojan-go的是smux，它们是不兼容的。

**Comment by ywyha** [comment]
希望尽早支持这个特性，大佬们加油~

**Comment by rprx** [comment]
可以把“似乎”去掉，他们不是同一个 mux。不过打算改 mux 了，还计划加上对 smux 的支持。

**Comment by ywyha** [comment]
基友们，如果哪天修复了trajon-go，麻烦踢我一脚！！~~！

**Comment by chr09670** [comment]
等待修复

**Comment by bash99** [comment]
> 等待修复

有没有trojan-go之外的客户端支持 smux 的？

**Comment by vxmp** [comment]
> 

期待大佬修复^_^

**Comment by Swiftfrog** [comment]
2024了，还是不支持smux。

**Comment by Cathgao** [comment]
> 2024了，还是不支持smux。

不用想了，Trojan都要被淘汰了。要么不用smux要么换别的协议吧

**Comment by yetnelson** [comment]
发现clash的custom smux跟ray的mux类似，trojan-go也不兼容，open stream时也是会发送一个自定义的destination，trojan-go的smux就会请求这个unknown host

**Comment by RPRX** [comment]
~~都 2025 了，别瞎整这些有的没的了，都给我用 XHTTP 的 XMUX~~

**Comment by yetnelson** [comment]
@RPRX 受宠若惊，作者大大这么快就回复了
