### ISSUE TITLE
关于REALITY 为什么有时候会代理无法连接

### ISSUE THREAD

**Issue by wzry2580** [XTLS/Xray-core#2353]
现在目前能正常使用，隔了一部分时间之后，代理工具上面点击连接显示超时，xui 服务器端应该没问题 但是连接应该是经过了DNS服务器，谷歌的，不确定是否是跟DNS服务器这个问题有关，代理工具是用的安卓 NekoBox 也有可能跟测试网站有关，这都是代理工具中的，有一个测试网址，用的是CF，或者是跟握手的网站有关，可能是被他们拉黑ip了 只是我的猜测，欢迎大佬 给我解答一下

**Comment by wzry2580** [comment]
xui 运行日志


`18 07:47:39 C20230718074592 systemd[1]: Started x-ui Service.
Jul 18 07:47:39 C20230718074592 x-ui[1692]: 2023/07/17 23:47:39 x-ui 0.3.4.4:20230717
Jul 18 07:47:39 C20230718074592 x-ui[1692]: 2023/07/17 23:47:39 INFO - web server run http on [::]:30000
Jul 18 07:47:39 C20230718074592 x-ui[1692]: 2023/07/17 23:47:39 INFO - Wait 2 seconds for telegram bot ready
Jul 18 07:47:41 C20230718074592 x-ui[1692]: SSHLogin[2023-07-17 23:46:00] early than XUI start[2023-07-17 23:47:39],don't notify
Jul 18 07:50:48 C20230718074592 x-ui[1692]: 2023/07/17 23:50:48 INFO - wzry2580 login success,Ip Address:13.212.244.212
Jul 18 07:50:48 C20230718074592 x-ui[1692]: 2023/07/17 23:50:48 INFO - user 1 login success
Jul 18 07:51:28 C20230718074592 x-ui[1692]: 2023/07/17 23:51:28 INFO - RecordXrayVersion: v1.8.3Jul 18 07:53:39 C20230718074592 x-ui[1692]: 2023/07/17 23:53:39 INFO - We got 1 members in client
Jul 18 08:15:04 C20230718074592 x-ui[1692]: 2023/07/18 00:15:04 WARNING - stop server err: multierr: close tcp [::]:30000: use of closed network connection |
Jul 18 08:15:04 C20230718074592 x-ui[1692]: 2023/07/18 00:15:04 INFO - web server run http on [::]:30000
Jul 18 08:15:04 C20230718074592 x-ui[1692]: 2023/07/18 00:15:04 INFO - We got 1 members in client
Jul 18 08:15:04 C20230718074592 x-ui[1692]: 2023/07/18 00:15:04 INFO - Wait 2 seconds for telegram bot ready
Jul 18 09:37:04 C20230718074592 x-ui[1692]: 2023/07/18 01:37:04 INFO - We got 2 members in client
Jul 18 15:09:14 C20230718074592 x-ui[1692]: 2023/07/18 07:09:14 INFO - We got 2 members in client
Jul 18 15:09:14 C20230718074592 x-ui[1692]: 2023/07/18 07:09:14 INFO - We got 5 members in client
Jul 18 15:13:10 C20230718074592 systemd[1]: Stopping x-ui Service...
Jul 18 15:13:10 C20230718074592 x-ui[1692]: get signal: terminated
Jul 18 15:13:11 C20230718074592 systemd[1]: x-ui.service: Deactivated successfully.
Jul 18 15:13:11 C20230718074592 systemd[1]: Stopped x-ui Service.
Jul 18 15:13:11 C20230718074592 systemd[1]: x-ui.service: Consumed 3min 18.430s CPU time.
Jul 18 15:13:11 C20230718074592 systemd[1]: Started x-ui Service.
Jul 18 15:13:11 C20230718074592 x-ui[69711]: 2023/07/18 07:13:11 x-ui 0.3.4.4:20230717
Jul 18 15:13:11 C20230718074592 x-ui[69711]: 2023/07/18 07:13:11 INFO - web server run http on [::]:30000
Jul 18 15:13:11 C20230718074592 x-ui[69711]: 2023/07/18 07:13:11 INFO - We got 2 members in client
Jul 18 15:13:11 C20230718074592 x-ui[69711]: 2023/07/18 07:13:11 INFO - We got 5 members in client
Jul 18 15:13:11 C20230718074592 x-ui[69711]: 2023/07/18 07:13:11 INFO - Wait 2 seconds for telegram bot ready
Jul 18 15:13:13 C20230718074592 x-ui[69711]: 2023/07/18 07:13:13 INFO - get xray version from database: v1.8.3
Jul 18 15:13:13 C20230718074592 x-ui[69711]: 2023/07/18 07:13:13 INFO - xray Version from database is: v1.8.3
Jul 18 15:13:19 C20230718074592 x-ui[69711]: SSHLogin[2023-07-18 07:13:00] early than XUI start[2023-07-18 07:13:11],don't notify
Jul 18 15:13:29 C20230718074592 x-ui[69711]: get signal: terminated
Jul 18 15:13:29 C20230718074592 systemd[1]: Stopping x-ui Service...
Jul 18 15:13:29 C20230718074592 systemd[1]: x-ui.service: Deactivated successfully.
Jul 18 15:13:29 C20230718074592 systemd[1]: Stopped x-ui Service.
Jul 18 15:13:29 C20230718074592 systemd[1]: Started x-ui Service.
Jul 18 15:13:29 C20230718074592 x-ui[69859]: 2023/07/18 07:13:29 x-ui 0.3.4.4:20230717
Jul 18 15:13:29 C20230718074592 x-ui[69859]: 2023/07/18 07:13:29 INFO - web server run http on [::]:30000
Jul 18 15:13:29 C20230718074592 x-ui[69859]: 2023/07/18 07:13:29 INFO - We got 2 members in client
Jul 18 15:13:29 C20230718074592 x-ui[69859]: 2023/07/18 07:13:29 INFO - We got 5 members in client
Jul 18 15:13:29 C20230718074592 x-ui[69859]: 2023/07/18 07:13:29 INFO - Wait 2 seconds for telegram bot ready
Jul 18 15:13:31 C20230718074592 x-ui[69859]: 2023/07/18 07:13:31 INFO - get xray version from database: v1.8.3
Jul 18 15:13:32 C20230718074592 x-ui[69859]: 2023/07/18 07:13:32 INFO - xray Version from database is: v1.8.3
Jul 18 15:15:01 C20230718074592 x-ui[69859]: 2023/07/18 07:15:01 INFO - We got 2 members in client
Jul 18 15:15:01 C20230718074592 x-ui[69859]: 2023/07/18 07:15:01 INFO - We got 5 members in client
Jul 18 15:15:02 C20230718074592 x-ui[69859]: 2023/07/18 07:15:02 INFO - We got 2 members in client
Jul 18 15:15:02 C20230718074592 x-ui[69859]: 2023/07/18 07:15:02 INFO - We got 5 members in client
Jul 18 15:15:07 C20230718074592 x-ui[69859]: 2023/07/18 07:15:07 INFO - We got 2 members in client
Jul 18 15:15:07 C20230718074592 x-ui[69859]: 2023/07/18 07:15:07 INFO - We got 5 members in client
Jul 18 15:15:08 C20230718074592 x-ui[69859]: 2023/07/18 07:15:08 INFO - We got 2 members in client
Jul 18 15:15:08 C20230718074592 x-ui[69859]: 2023/07/18 07:15:08 INFO - We got 5 members in client
Jul 18 15:18:33 C20230718074592 x-ui[69859]: 2023/07/18 07:18:33 WARNING - stop server err: multierr: close tcp [::]:30000: use of closed network connection |
Jul 18 15:18:34 C20230718074592 x-ui[69859]: 2023/07/18 07:18:34 INFO - web server run http on [::]:30000
Jul 18 15:18:34 C20230718074592 x-ui[69859]: 2023/07/18 07:18:34 INFO - We got 2 members in client
Jul 18 15:18:34 C20230718074592 x-ui[69859]: 2023/07/18 07:18:34 INFO - We got 5 members in client
Jul 18 15:18:34 C20230718074592 x-ui[69859]: 2023/07/18 07:18:34 INFO - Wait 2 seconds for telegram bot ready
Jul 18 15:19:02 C20230718074592 x-ui[69859]: 2023/07/18 07:19:02 INFO - We got 2 members in client
Jul 18 15:19:02 C20230718074592 x-ui[69859]: 2023/07/18 07:19:02 INFO - We got 5 members in client
Jul 18 15:19:02 C20230718074592 x-ui[69859]: 2023/07/18 07:19:02 INFO - We got 2 members in client
Jul 18 15:19:02 C20230718074592 x-ui[69859]: 2023/07/18 07:19:02 INFO - We got 5 members in client
Jul 18 15:20:13 C20230718074592 x-ui[69859]: 2023/07/18 07:20:13 INFO - We got 2 members in client
Jul 18 15:20:13 C20230718074592 x-ui[69859]: 2023/07/18 07:20:13 INFO - We got 5 members in client
Jul 18 15:20:18 C20230718074592 x-ui[69859]: 2023/07/18 07:20:18 INFO - We got 2 members in client
Jul 18 15:20:18 C20230718074592 x-ui[69859]: 2023/07/18 07:20:18 INFO - We got 5 members in client
Jul 18 15:20:20 C20230718074592 x-ui[69859]: 2023/07/18 07:20:20 INFO - We got 2 members in client
Jul 18 15:20:20 C20230718074592 x-ui[69859]: 2023/07/18 07:20:20 INFO - We got 5 members in client
Jul 19 12:00:28 C20230718074592 systemd[1]: Stopping x-ui Service...
Jul 19 12:00:28 C20230718074592 x-ui[69859]: get signal: terminated
Jul 19 12:00:28 C20230718074592 systemd[1]: x-ui.service: Deactivated successfully.
Jul 19 12:00:28 C20230718074592 systemd[1]: Stopped x-ui Service.
Jul 19 12:00:28 C20230718074592 systemd[1]: x-ui.service: Consumed 7min 49.943s CPU time.
Jul 19 12:00:28 C20230718074592 systemd[1]: Started x-ui Service.
Jul 19 12:00:29 C20230718074592 x-ui[221144]: 2023/07/19 04:00:29 x-ui 0.3.4.4:20230717
Jul 19 12:00:29 C20230718074592 x-ui[221144]: 2023/07/19 04:00:29 INFO - web server run http on [::]:30000
Jul 19 12:00:29 C20230718074592 x-ui[221144]: 2023/07/19 04:00:29 INFO - We got 2 members in client
Jul 19 12:00:29 C20230718074592 x-ui[221144]: 2023/07/19 04:00:29 INFO - We got 5 members in client
Jul 19 12:00:29 C20230718074592 x-ui[221144]: 2023/07/19 04:00:29 INFO - Wait 2 seconds for telegram bot ready
Jul 19 12:00:31 C20230718074592 x-ui[221144]: 2023/07/19 04:00:31 INFO - get xray version from database: v1.8.3
Jul 19 12:00:31 C20230718074592 x-ui[221144]: 2023/07/19 04:00:31 INFO - xray Version from database is: v1.8.3
Jul 19 13:00:00 C20230718074592 x-ui[221144]: 2023/07/19 05:00:00 INFO - Run InboundTrafficAlert Job...
Jul 19 13:00:00 C20230718074592 x-ui[221144]: 2023/07/19 05:00:00 INFO - get inboundTrafficNotify is 0
Jul 19 13:00:00 C20230718074592 x-ui[221144]: 2023/07/19 05:00:00 WARNING - current traffic notify  diff is:0
Jul 19 13:00:00 C20230718074592 x-ui[221144]: 2023/07/19 05:00:00 INFO - Run InboundExpireNotify Job...
Jul 19 13:00:00 C20230718074592 x-ui[221144]: 2023/07/19 05:00:00 INFO - get inboundExpireNotify time is 0
Jul 19 13:00:00 C20230718074592 x-ui[221144]: 2023/07/19 05:00:00 WARNING - current Expire notify time diff is:0
Jul 20 13:00:00 C20230718074592 x-ui[221144]: 2023/07/20 05:00:00 INFO - Run InboundTrafficAlert Job...
Jul 20 13:00:00 C20230718074592 x-ui[221144]: 2023/07/20 05:00:00 INFO - get inboundTrafficNotify is 0
Jul 20 13:00:00 C20230718074592 x-ui[221144]: 2023/07/20 05:00:00 WARNING - current traffic notify  diff is:0
Jul 20 13:00:00 C20230718074592 x-ui[221144]: 2023/07/20 05:00:00 INFO - Run InboundExpireNotify Job...
Jul 20 13:00:00 C20230718074592 x-ui[221144]: 2023/07/20 05:00:00 INFO - get inboundExpireNotify time is 0
Jul 20 13:00:00 C20230718074592 x-ui[221144]: 2023/07/20 05:00:00 WARNING - current Expire notify time diff is:0
Jul 20 17:33:50 C20230718074592 systemd[1]: Stopping x-ui Service...
Jul 20 17:33:50 C20230718074592 x-ui[221144]: get signal: terminated
Jul 20 17:33:51 C20230718074592 systemd[1]: x-ui.service: Deactivated successfully.
Jul 20 17:33:51 C20230718074592 systemd[1]: Stopped x-ui Service.
Jul 20 17:33:51 C20230718074592 systemd[1]: x-ui.service: Consumed 13min 26.595s CPU time.
Jul 20 17:33:51 C20230718074592 systemd[1]: Started x-ui Service.
Jul 20 17:33:51 C20230718074592 x-ui[485916]: 2023/07/20 17:33:51 x-ui 0.3.4.4:20230717
Jul 20 17:33:51 C20230718074592 x-ui[485916]: 2023/07/20 17:33:51 INFO - web server run http on [::]:30000
Jul 20 17:33:51 C20230718074592 x-ui[485916]: 2023/07/20 17:33:51 INFO - We got 2 members in client
Jul 20 17:33:51 C20230718074592 x-ui[485916]: 2023/07/20 17:33:51 INFO - We got 5 members in client
Jul 20 17:33:52 C20230718074592 x-ui[485916]: 2023/07/20 17:33:52 INFO - Wait 2 seconds for telegram bot ready
Jul 20 17:33:54 C20230718074592 x-ui[485916]: SSHLogin[2023-07-20 17:33:00] early than XUI start[2023-07-20 17:33:51],don't notify
Jul 20 17:33:54 C20230718074592 x-ui[485916]: 2023/07/20 17:33:54 INFO - get xray version from database: v1.8.3
Jul 20 17:33:54 C20230718074592 x-ui[485916]: 2023/07/20 17:33:54 INFO - xray Version from database is: v1.8.3
Jul 20 17:35:51 C20230718074592 x-ui[485916]: 2023/07/20 17:35:51 INFO - We got 2 members in client
Jul 20 17:35:51 C20230718074592 x-ui[485916]: 2023/07/20 17:35:51 INFO - We got 5 members in client
Jul 20 17:36:11 C20230718074592 x-ui[485916]: 2023/07/20 17:36:11 INFO - We got 2 members in client
Jul 20 17:36:11 C20230718074592 x-ui[485916]: 2023/07/20 17:36:11 INFO - We got 5 members in client
Jul 21 04:00:04 C20230718074592 systemd[1]: Stopping x-ui Service...
Jul 21 04:00:04 C20230718074592 x-ui[485916]: get signal: terminated
Jul 21 04:00:06 C20230718074592 systemd[1]: x-ui.service: Deactivated successfully.
Jul 21 04:00:06 C20230718074592 systemd[1]: Stopped x-ui Service.
Jul 21 04:00:06 C20230718074592 systemd[1]: x-ui.service: Consumed 4min 46.933s CPU time.
Jul 21 04:00:06 C20230718074592 systemd[1]: Started x-ui Service.
Jul 21 04:00:06 C20230718074592 x-ui[561502]: 2023/07/21 04:00:06 x-ui 0.3.4.4:20230717
Jul 21 04:00:06 C20230718074592 x-ui[561502]: 2023/07/21 04:00:06 INFO - web server run http on [::]:30000
Jul 21 04:00:06 C20230718074592 x-ui[561502]: 2023/07/21 04:00:06 INFO - We got 2 members in client
Jul 21 04:00:06 C20230718074592 x-ui[561502]: 2023/07/21 04:00:06 INFO - We got 5 members in client
Jul 21 04:00:06 C20230718074592 x-ui[561502]: 2023/07/21 04:00:06 INFO - Wait 2 seconds for telegram bot ready
Jul 21 04:00:08 C20230718074592 x-ui[561502]: 2023/07/21 04:00:08 INFO - get xray version from database: v1.8.3
Jul 21 04:00:08 C20230718074592 x-ui[561502]: 2023/07/21 04:00:08 INFO - xray Version from database is: v1.8.3`

**Comment by FranzKafkaYu** [comment]
> 现在目前能正常使用，隔了一部分时间之后，代理工具上面点击连接显示超时，xui 服务器端应该没问题 但是连接应该是经过了DNS服务器，谷歌的，不确定是否是跟DNS服务器这个问题有关，代理工具是用的安卓 NekoBox 也有可能跟测试网站有关，这都是代理工具中的，有一个测试网址，用的是CF，或者是跟握手的网站有关，可能是被他们拉黑ip了 只是我的猜测，欢迎大佬 给我解答一下

将服务端节点配置中目标网站修改为面板监听端口，可选域名填写为面板登录域名，重新导入分享链接至客户端试试
