### ISSUE TITLE
能否把nekoray写到GUI Clients的Windows及Linux处，因为nekoray 3.10开始已经完全使用Xray-core v1.8.3作为内核

### ISSUE THREAD

**Issue by egg1234** [XTLS/Xray-core#2354]
nekoray 3.10开始已经完全使用Xray-core v1.8.3作为内核，并且现在使用Xray-core v1.8.3内核已经发布到3.12版了，图形化配置界面原生支持REALITY协议配置，而且GUI Clients分别支持linux桌面版及windows版

**Comment by chika0801** [comment]
你复制一份这个仓库，修改一下readme，再PR提交过来就是了
