### ISSUE TITLE
关于通过源ip特征和主动访问识别reality的可能性

### ISSUE THREAD

**Issue by Weltolk** [XTLS/Xray-core#2358]
今天在群里看到有人提出了一个关于识别reality的方法
我根据我的理解和知识储备想了一下：

使用reality，对外的特征应该是做为目标域名的一个节点
此时如果使用的是访问量较为高的域名 比如www.microsoft.com，那么通过源ip特征，应该可以做为识别reality的一个很有意义的参考：
如果该ip确实是微软域名的一个节点，那么访问量应该很多，而且访问的源ip应该来自全国各地，并且不会有太明显的时序特征，比如晚上睡觉时间还会有来自全国各地的许多访问
而如果是用于翻墙，那么源ip通常只有国内固定地区的某些ip，且访问量相对于正常的微软域名来说应当很低，且应该存在较为明显的时序特征
另外，主动访问该翻墙节点时，与正常的访问微软域名应该是有明显的差距的，无法做到完美伪装
最后，识别的成本应该也不高，gfw只需要统计热门域名突然出现的冷门ip，而且出现后一段时间内符合上面说的用于翻墙时的特征，即可确认

希望不吝赐教，知识储备较少，有错误烦请指出，谢谢

**Comment by chika0801** [comment]
置顶看下 https://github.com/XTLS/Xray-core/issues/2230，你在一个群有人回你的那人是黑子

**Comment by chika0801** [comment]
至于你的VPS，只有你1人访问，源IP就你自己来自你自己的地区这问题，你不用VLESS协议，用其它协议也不一样嘛。

**Comment by Weltolk** [comment]
> 至于你的VPS，只有你1人访问，源IP就你自己来自你自己的地区这问题，你不用VLESS协议，用其它协议也不一样嘛。

这是reality相关的问题，淫威reality使用了目标网站的证书

**Comment by chika0801** [comment]
> > 至于你的VPS，只有你1人访问，源IP就你自己来自你自己的地区这问题，你不用VLESS协议，用其它协议也不一样嘛。
> 
> 这是reality相关的问题，因为reality使用了目标网站的证书

> 最后，识别的成本应该也不高，gfw只需要统计热门域名突然出现的冷门ip，而且出现后一段时间内符合上面说的用于翻墙时的特征，即可确认

那你问的是这句吧？建议你用偷自己形式得了

**Comment by Weltolk** [comment]
> 相关可先看下 #2230 PS 你在一个群有人( F-35C)那人是黑子

看完了，我们说的有一点差别
我说的这种方法主要是针对服务端源ip单一和出国流量中突然出现的热门域名的冷门ip
gfw应该只需要短时间针对性收集一下就可以得到结果，比如国内某个地区的日常流量访问www.microsoft.com时的目标ip。最后可以得到结果发现整个地区只有某几个ip的目标ip是reality服务端的那个ip

**Comment by Weltolk** [comment]
> > 最后，识别的成本应该也不高，gfw只需要统计热门域名突然出现的冷门ip，而且出现后一段时间内符合上面说的用于翻墙时的特征，即可确认
> 
> 那你问的是这句吧？建议你用偷自己形式得了

我目前是偷自己，我说的是偷热门域名的情况

**Comment by chika0801** [comment]
https://github.com/ihciah/shadow-tls/issues

https://github.com/3andne/restls/issues

说个题外话，你也可以去上面2个github问问他们作者的看法

**Comment by Weltolk** [comment]
> https://github.com/ihciah/shadow-tls/issues
> 
> https://github.com/3andne/restls/issues
> 
> 说个题外话，你也可以去上面2个github问问他们作者的看法

还未使用过，不过我看README.md，貌似是类似reality的原理，我感觉会有类似的问题

**Comment by Weltolk** [comment]
> https://github.com/ihciah/shadow-tls/issues
> 
> https://github.com/3andne/restls/issues
> 
> 说个题外话，你也可以去上面2个github问问他们作者的看法
> 
> 再补充一个 https://github.com/JimmyHuang454/JLS

还未使用过，不过我看README.md，貌似是类似reality的原理，我感觉会有类似的问题

**Comment by chika0801** [comment]
https://github.com/net4people/bbs/issues

和老外交流推荐你去这儿

**Comment by chika0801** [comment]
> > https://github.com/ihciah/shadow-tls/issues
> > https://github.com/3andne/restls/issues
> > 说个题外话，你也可以去上面2个github问问他们作者的看法
> > 再补充一个 https://github.com/JimmyHuang454/JLS
> 
> 还未使用过，不过我看README.md，貌似是类似reality的原理，我感觉会有类似的问题

https://github.com/JimmyHuang454/JLS#10-%E7%94%A8-ip-%E6%9F%A5-%E5%9F%9F%E5%90%8D

这位作者有这一段话

**Comment by Weltolk** [comment]
> https://github.com/net4people/bbs/issues
> 
> 和老外交流推荐你去这儿

我主要想先问一下xray这边各位佬的想法（因为一直在用）（

**Comment by chika0801** [comment]
群里好像没什么想法吧，REALITY出了这几个月该怎么用就怎么用着，也没见什么。这边倒是时不时有来问XXX原理的帖子

**Comment by chika0801** [comment]
你有兴趣可去关闭的ISS区 或讨论区找找历史帖子 比如这个ISS，看到有时候作者会回复一些内容，只是平时没人特意收集。

**Comment by Weltolk** [comment]
> > > https://github.com/ihciah/shadow-tls/issues
> > > https://github.com/3andne/restls/issues
> > > 说个题外话，你也可以去上面2个github问问他们作者的看法
> > > 再补充一个 https://github.com/JimmyHuang454/JLS
> > 
> > 
> > 还未使用过，不过我看README.md，貌似是类似reality的原理，我感觉会有类似的问题
> 
> https://github.com/JimmyHuang454/JLS#10-%E7%94%A8-ip-%E6%9F%A5-%E5%9F%9F%E5%90%8D
> 
> 这位作者有这一段话

如果gfw这么仁慈的话确实是没事，但是如果加大力度，是有可能这么做的

**Comment by Weltolk** [comment]
> 你有兴趣可去关闭的ISS区 或讨论区找找历史帖子 比如这个ISS #2317
> 
> 看到有时候作者会回复一些内容，只是平时没人特意收集。
> 
> 就靠网友来发帖，说不定通过你发的这ISS，作者会透露一些他自己的看法出来 笑

我也想知道RPRX佬的想法（

**Comment by Weltolk** [comment]
> 群里好像没什么想法吧，REALITY出了这几个月该怎么用就怎么用着，也没见什么。这边倒是时不时有来问XXX原理的帖子

CHIKA0801大佬怎么看（

**Comment by chika0801** [comment]
> > 群里好像没什么想法吧，REALITY出了这几个月该怎么用就怎么用着，也没见什么。这边倒是时不时有来问XXX原理的帖子
> 
> CHIKA0801大佬怎么看，有没有可行性（

我不懂这方面，没看法

**Comment by RPRX** [comment]
~~如果刚讨论完 [钓鱼](https://github.com/XTLS/Xray-core/issues/2317) 又讨论这个，天天讨论这些事情我都不用写代码了~~

简单说一下，先说源 IP，这当然是 weakness 之一，个人自建代理的通病，单点大流量，很久以前大家就在讨论。其实你搭过网站看过日志的话，会知道一直都有人扫，有自动程序访问，不过它们的帮助可能有限，~~**干脆我们推广些 REALITY 机场？**~~

时序特征的话，我们可以 reshape 成目标网站的特征，SpiderX 的设计就是做点贡献，不过最好还是基于采集，这个不是大问题。当然如果你指的是单一节点的使用特征，参考上一段，这样的问题主要是协议以外的问题，~~或者说是钱的问题。~~

对于域名，我的 [建议](https://github.com/XTLS/Xray-core/discussions/2256#discussioncomment-6295296) 是优先用自己的，~~还有 CDN 备用~~，偷别人的域名就是会有一些解决不了的三体问题，这个一开始就 [说过](https://github.com/3andne/restls/issues/2#issuecomment-1426938995)，所以对我来说 REALITY 最关注的是 GFW 偷配置、证书链攻击等加密安全性问题（已完美解决），其次才是 SNI 白名单问题。

最后，参考 [这两段](https://github.com/XTLS/Xray-core/issues/2230#issuecomment-1598256976)，我觉得总是有人想识别 REALITY，这无可厚非，~~我自己都想过很多~~。干脆直接假设 GFW 精准封锁“偷别人”，伊朗基本上就差这个了，部署了你还翻得出去吗？所以说 like it or not，“偷别人”已经是最后防线了，~~**它没了就等着过好日子吧。**~~

**Comment by chika0801** [comment]
画重点

天天讨论这些事情我都不用写代码了

**Comment by chika0801** [comment]
ps bot现在是坏的，群收不到githib的消息推送

**Comment by RPRX** [comment]
BTW，~~某协议~~ 的说法错误百出，不建议引述，随便找个开发者看都能指出一堆错误，所以交给别人吧，我是没空，~~别被拉低了水平~~

**Comment by Fangliding** [comment]
> ps bot现在是坏的，群收不到github的消息推送

之前被人解绑了 后来XQ把仓库绑回去了不知道为什么还是收不到（悲）

**Comment by Weltolk** [comment]
> ~~如果刚讨论完 [钓鱼](https://github.com/XTLS/Xray-core/issues/2317#issuecomment-1630407700) 又讨论这个，天天讨论这些事情我都不用写代码了~~
> 
> 简单说一下，先说源 IP，这当然是 weakness 之一，个人自建代理的通病，单点大流量，很久以前大家就在讨论。 其实你搭过网站看过日志的话，会知道一直都有人扫，有自动程序访问，不过它们的帮助可能有限，~~**干脆我们推广些 REALITY 机场？**~~
> 
> 时序特征的话，我们可以 reshape 成目标网站的特征，SpiderX 的设计就是做点贡献，不过最好还是基于采集，这个不是大问题。 当然如果你指的是单一节点的使用特征，参考上一段，这样的问题主要是协议以外的问题，~~或者说是钱的问题。~~
> 
> 对于域名，我的 [建议](https://github.com/XTLS/Xray-core/discussions/2256#discussioncomment-6295296) 是优先用自己的，~~还有 CDN 备用~~，偷别人的域名就是会有一些解决不了的三体问题，这个一开始就 [说过](https://github.com/3andne/restls/issues/2#issuecomment-1426938995)。 所以对我来说 REALITY 最关注的是 [GFW 偷密码、证书链攻击](https://github.com/3andne/restls/issues/2#issuecomment-1426969161) 等加密安全性问题（已完美解决），其次才是 SNI 白名单问题。
> 
> 最后，参考 [这两段](https://github.com/XTLS/Xray-core/issues/2230#issuecomment-1598256976)，我觉得总是有人想识别 REALITY，这无可厚非，~~我自己都想过很多~~。 干脆直接假设 GFW 精准封锁“偷别人”，伊朗基本上就差这个了，部署了你还翻得出去吗？所以说 like it or not，“偷别人”已经是最后防线了，~~**它没了就等着过好日子吧。**~~

感谢回复，我想了一下，确实是自建翻墙本身就存在的问题。
至于域名，偷自己的话确实最安全。

**Comment by RPRX** [comment]
~~https://github.com/XTLS/Xray-core/issues/2360 既然已经开始流行扫反代 CDN 的 IP 当加速了，你可以选择反代 CDN 让别人扫去用，缺点是有可能被 WSS 封了端口~~

自建代理解决不了单点大流量等使用特征问题，~~或许加钱可解~~
