### ISSUE TITLE
建议reality增加默认SNI验证，防止成为CDN反代中继节点被他人CF翻墙流量薅羊毛

### ISSUE THREAD

**Issue by simplerick-simplefun** [XTLS/Xray-core#2360]
**问题：**

参考：[免费给垃圾节点提速，独家分享寻找反代IP](https://www.youtube.com/watch?v=NbruiJShUCE) 。我大概描述一下，不用实际看视频：
有些人的VPS的reality节点设置中，dest的目标网站用了CF的CDN服务。那么reality会把dest解析成CF的一个边缘IP（Edge IP）。
这时，任何不是真实连接到该reality节点的流量（即不具备reality预设的privatekey的流量），都会被reality反代到dest解析出的IP，也就是CF的边缘IP。
那么，这个reality节点/这个VPS的IP，就可以被其他的程序当作一个CF的边缘IP使用。就导致了其他的任何套ws/h2/grpc的翻墙流量，都可以通过访问这个VPS的IP，来访问自己使用了CF作为CDN的翻墙节点。
简单地说，就是被薅羊毛。

**解决办法：**

- 建议reality改为默认检查来访流量的sni，如果不是dest预设的sni，则阻断/黑洞该流量，并进行error log，方便外部防火墙软件（如fail2ban）封禁来源IP。
- 如果reality不做更改，用户可自行安装配置前置SNI分流。我目前用的是haproxy，nginx也可以，先检查来访流量要访问哪个SNI，如果是reality dest的SNI，就把流量转发给xray，如果是跟VPS上的服务无关的SNI，则阻断/黑洞。

----------------------------
从xray开发/维护组和R佬的角度看，免费无偿开发出很好用的翻墙代理，结果一堆小白用了之后成了流量肉鸡，好说不好听，传出去名声不好。
小白才不管你那么多，他们就知道用了你的xray-reality，自己就被别人偷跑流量，就来骂你。
然后还可能有一些智商\*优越\*的开发者来嘲讽你。比如上次那个什么JLS。

**Comment by sduoduo233** [comment]
dest不选套cf的网站不就行了？

**Comment by RPRX** [comment]
对于非 REALITY 流量，全转发到 dest 才是正确的，SNI 分流的话能探测出来，有此需求请用 Nginx 等软件实现。

**Comment by RPRX** [comment]
你可以在 Discussions 发一个 dest 为 CF 的判断方法、风险提示及解决方案：不选 CF，或者 SNI 分流，附上 Nginx 等软件的配置

或者，找到源站，其实更好 https://t.me/projectXtls/72

**Comment by chika0801** [comment]
> dest不选套cf的网站不就行了？

行的

**Comment by chika0801** [comment]
参考时间点是微软关TLS 1.3那天，隔壁论坛开始有提醒帖子：https://www.nodeseek.com/post-13519-1 https://www.nodeseek.com/post-13407-1

**Comment by simplerick-simplefun** [comment]
> 对于非 REALITY 流量，全转发到 dest 才是正确的，SNI 分流的话能探测出来，有此需求请用 Nginx 等软件实现。

这里我没想明白。如果reality dest域名设置是套了CDN的站，那么访问vps ip并且是其他的套了该CDN的域名时，vps应该做什么反应。
按照您的说法，应该全部反代，来达到表现跟CDN一致。但是只要简单的查一下IP的WHOIS信息，就能发现，VPS的IP所属的ASN+ORG+ISP跟CDN所属的ASN+ORG+ISP是大大不同的。这种情况下VPS彻底表现为与CDN一样是不是也不好？

当然自己偷自己是最好的；但是如果遇到泉州白名单那样的网络环境，可能就只能偷一些的大的学校/机构的网站，而这种网站普遍是套用CDN的。所以这个问题也真实存在。

**Comment by RPRX** [comment]
看到群里有误解，https://t.me/projectXtls/72 是建议你反代源站，而不是 CDN 节点，~~不要理解错了~~，不过“仅此一家”可能难做到

~~不过反代 CDN 节点的好处是可选的 SNI 非常多~~

扫去当加速这件事早就有 [讨论](https://github.com/3andne/restls/issues/2#issuecomment-1426965587)，~~无非是文章还没发加上时间久了一些人都忘了，天天搞得像发现了新大陆一样~~

**Comment by RPRX** [comment]
> 这里我没想明白。如果reality dest域名设置是套了CDN的站，那么访问vps ip并且是其他的套了该CDN的域名时，vps应该做什么反应。 按照您的说法，应该全部反代，来达到表现跟CDN一致。但是只要简单的查一下IP的WHOIS信息，就能发现，VPS的IP所属的ASN+ORG+ISP跟CDN的Edge IP所属的ASN+ORG+ISP是大大不同的。这种情况下VPS彻底表现为与CDN一样是不是也不好？
> 
> 当然自己偷自己是最好的；但是如果遇到泉州白名单那样的网络环境，可能就只能偷一些的大的学校/机构的网站，而这种网站普遍是套用CDN的。所以这个问题也真实存在。

首先，对于选域名我的建议是 [这样](https://github.com/XTLS/Xray-core/discussions/2256#discussioncomment-6295296) 的。其次，如果担心选 CDN 会有这样那样的问题，就不要选它。第二段的“只能”应该不成立。

总之 REALITY 的预期对外表现只是端口转发，另外目前不知道 GFW 会不会封 SNI 分流反代，建议用 Nginx 等软件是借用特征。

**Comment by chika0801** [comment]
@RPRX

https://t.me/projectXray/2627223

这个商家叫威鱼云，开了有2年多了，好家伙

**Comment by FlyingStarlight** [comment]
想问一下这样白嫖是指
1. SNI设置成了自己的站点导致被白嫖？
2. 现阶段如果被白嫖会有access.log打印吗
