### ISSUE TITLE
我怀疑REALITY是不是能够被GFW识别？还是存在潜在的BUG或是流量会被AWS拦截？还是我获取的acme.sh证书有潜在问题？

### ISSUE THREAD

**Issue by lanvada** [XTLS/Xray-core#2368]
我使用的配置在如下issue中：
#2366

我一共搭了8个服务器，我购买的是AWS的EC2实例，类型全部是t3a，其中2个使用Vision，6个使用Reality，在今天上午大概9点半左右，所有的Reality服务器全部失效了。我分别使用了两台电脑和手机测试链接，V2rayN和ShadowsocksR都无法连接。但是另外两个Vision服务器还可以正常使用。
我尝试修复其中的一个服务器，但是未能成功，在今天晚上八点左右，所有服务器突然又恢复了连接。我并未对它们进行任何更改，在失去连接之前也没有动过。没有更新过Docker，没有更新过nginx和xray的image，也没有修改过配置，没有更新过证书。我检查了所有服务器上的运行日志，也未发现任何报错。

注1：服务器失效指无法通过V2rayN和Shadowrocket等工具访问，但是域名和ip都能正常访问
注2：我用的V2RayN和服务器端的Xray是1.8.3版本，Shadowrocket是最新版的APP

这实在是太玄学了！！！
太吓人了，还以为突然就与世隔绝了，承受不住啊。

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/issues/2017#issuecomment-1532345891

**Comment by lanvada** [comment]
> 

感谢！我去研究一下这个issue

**Comment by lanvada** [comment]
> [#2017 (comment)](https://github.com/XTLS/Xray-core/issues/2017#issuecomment-1532345891)

大佬你好，我看评论中提到了有可能是目标网站把我的ip拉黑了？但感觉也不太像啊，我的六个服务器每个都指向了不同的网站，我为每个服务器都申请了域名，通过nginx反代到这些真实网站

**Comment by lanvada** [comment]
> [#2017 (comment)](https://github.com/XTLS/Xray-core/issues/2017#issuecomment-1532345891)

我看了一遍评论说实话完全没看懂。。。我应该如何去避免类似的事情发生呢？大佬你能给个大概的事故原因和解决方向嘛？我去研究

**Comment by chika0801** [comment]
> > [#2017 (comment)](https://github.com/XTLS/Xray-core/issues/2017#issuecomment-1532345891)
> 
> 大佬你好，我看评论中提到了有可能是目标网站把我的ip拉黑了？但感觉也不太像啊，我的六个服务器每个都指向了不同的网站，我为每个服务器都申请了域名，通过nginx反代到这些真实网站

意思是你都是用的偷自己形式，如果是，就不是选DEST这方面的问题（可能性少）

**Comment by chika0801** [comment]
> > [#2017 (comment)](https://github.com/XTLS/Xray-core/issues/2017#issuecomment-1532345891)
> 
> 我看了一遍评论说实话完全没看懂。。。我应该如何去避免类似的事情发生呢？大佬你能给个大概的事故原因和解决方向嘛？我去研究

看不懂正常的。另外一直没问你你VPS商家是？

再则，你还要排除你遇到的不通现象是不是类似，随机中断约3分钟，参考 https://github.com/XTLS/Xray-core/discussions/1772 。如果是这现象（相似），只能换VPS商家。

基本上影响的就这些因素，能帮你猜的都猜完了，剩下靠你自己了。

**Comment by lanvada** [comment]
> > > [#2017 (comment)](https://github.com/XTLS/Xray-core/issues/2017#issuecomment-1532345891)
> > 
> > 
> > 大佬你好，我看评论中提到了有可能是目标网站把我的ip拉黑了？但感觉也不太像啊，我的六个服务器每个都指向了不同的网站，我为每个服务器都申请了域名，通过nginx反代到这些真实网站
> 
> 意思是你都是用的偷自己形式？如果是，就不是选DEST这方面的问题（可能性少）

嗯嗯 是的，我都是参考那个偷自己的配置，写的config，只是把配置上的域名改成了我的，以及在xray的config里面加了warp，在整体外面加了层docker

**Comment by chika0801** [comment]
> 只是把配置上的域名改成了我的

示例中的偷自己 Dest 那儿是填的本机端口，我不确定你如果是填 **比如自己设置一个子域名，申请了SSL证书由你VPS的nginx加载它，这子域名正确指向了你VPS的IP了** 这样做的效果怎么样。

你不会是开机场大佬吧？如果是（玩笑）建议找其它VPS商家的试试了。因为你是说全部中断，只能帮你到这了。

**Comment by lanvada** [comment]
> > 只是把配置上的域名改成了我的
> 
> 示例中的偷自己 Dest 那儿是填的本机端口，我不确定你如果是填 **比如自己设置一个子域名，申请了SSL证书由你VPS的nginx加载它，这子域名正确指向了你VPS的IP了** 这样做的效果怎么样。
> 
> 你不会是开机场大佬吧？如果是（玩笑）建议找其它VPS商家的试试了。因为你是说全部中断，只能帮你到这了。

那倒不是，我都是自己用的。我平时做后端开发的工作也不多(基本没有)，有的东西也搞不太懂，再研究下去就得复习一下大学学的计算机网络了。。。
搞得节点多只是有“与世隔绝”恐惧症。在AWS上面按三年期付费t3a实例，才一个月1.6-1.7美元，倒不是很贵。。

**Comment by chika0801** [comment]
你可能要入行当MJJ，买遍各地VPS，找到适合自己的，又是一个折腾的路呀。
