### ISSUE TITLE
Self signed cert + public key pinning

### ISSUE THREAD

**Issue by mozilla-firefox** [XTLS/Xray-core#2371]
Hi
I use self signed cert with allowInsecure enabled. It's really good i enjoy it!
But, allowInsecure=1 will not work in Android and Desktop and iOS clients
In desktop and android can enable the global allowInsecure option
but in iOS there is no any option for it (except 1 paid client)

You made all this problems because of a possibility of MitM attack
But i'm wondering why you don't use public key pinning to avoid MitM ? like how ssh servers work

Thank you.

**Comment by RPRX** [comment]
https://xtls.github.io/en/config/transport.html#tlsobject

**Comment by RPRX** [comment]
> I mean public key pinning for self-signed certificates, not a cert chain.

我没有看懂这句是什么意思，pin 证书功能主要就是用于验证自签证书的。不过它不支持分享，而且一个主动探测就露馅。

如果你只想验证公钥也行，效果上没有区别：https://github.com/XTLS/Xray-core/blob/51769fdde1ca663dcb08d942618e480bee13109f/transport/internet/tls/config.proto#L73-L85

---

如果你只想显示特定 SNI 而不管其它的，REALITY [隐藏玩法](https://github.com/XTLS/Xray-core/discussions/1988#discussioncomment-5736999) 就能做到，且它支持分享、强制客户端非 Golang 指纹。

如果不会配置，麻烦问 @chika0801

**Comment by chika0801** [comment]
You're asking a question that I don't understand. I don't usually use self-signed books. If you need someone to help you further, I suggest you describe your situation and the questions you want to ask in more detail, and you can go to the discussion forum and make a post.

**Comment by chika0801** [comment]
Use self-signed certificates? For example, if you use vmess websocks tcp TLS, you will need to use the TLS certificate at the point where the certificate is replaced with a self-signed certificate, and the client will then turn on, for example, the Allow insecure certificates parameter to use it.

Do you mean the self-signed certificates used in this combination? I don't use self-signed certificates myself, so I can't help you.

If you are referring to the use of REALITY, there is a hidden trick that allows the client to fill in any SNI value, and the client does not need to turn on the Allow Insecure Certificates parameter.

If that is the usage you are asking about. You try this one parameter in your server side configuration.

"dest": "1.1.1.1:443", e.g. for 1.1.1.1.1 or some other big company's website.
"serverNames": [ 
                        ""
                    ],.

Leave the value of "serverNames" blank. At this point, your client fills in the SNI location, which can be left blank or arbitrary.

This is the so-called REALITY hidden play, this method is not recommended by the author of large-scale use, the author has mentioned that it has some characteristics. Use more people, it may not be convenient to use.

**Comment by RPRX** [comment]
对于上面说的两件事（pin 证书链/公钥、REALITY 隐藏玩法），你可能都理解错了，建议到 Project X 的群聊寻求帮助

**Comment by RPRX** [comment]
@mozilla-firefox 

1. 还是理解有误，TLSv1.3 证书是加密的，GFW 看不到 REALITY 的证书。没必要支持 TLSv1.2，麻烦太多，~~参考 XTLS 的历史。~~
2. 你说的是缓存模式，要收集很多源站特征才会出。但源站挂了、REALITY 没挂，不假吗，一个主动探测就能确定是 REALITY。

**Comment by RPRX** [comment]
感觉你是被一些“偷证书”的叫法给忽悠了，至少目前，REALITY 发的是由“临时认证密钥”签发的“临时可信证书”，而不是源站的证书

https://github.com/XTLS/REALITY 看最后那几段

**Comment by Fangliding** [comment]
@RPRX 但是没有什么适合的谓语 搞得要像二游念玩家名字一样避讳来避讳去 迫不得已才念一下(

**Comment by RPRX** [comment]
“偷别人”
