### ISSUE TITLE
REALITY: Is it possible to have multiple destinations?

### ISSUE THREAD

**Issue by alphajoza** [XTLS/Xray-core#2374]
The `dest` field in `realitySettings` is of type string. Is it possible to have multiple destinations so that user could have the option of choosing different SNIs? (if yes, an example configuration is really appreciated)

I tested the above scenario using a layer 4 proxy that checks SNI of the TLS handshake and based on that redirects the traffic to appropriate port and it works just fine but I'm curious if this could be done with Xray alone (using `fallbacks` maybe?)

**Comment by RPRX** [comment]
https://xtls.github.io/en/config/outbounds/vless.html#outboundconfigurationobject

**Comment by alphajoza** [comment]
> https://xtls.github.io/en/config/outbounds/vless.html#outboundconfigurationobject

My apologies, I wasn't clear enough in my initial question.
**I was talking about having multiple SNIs on the same port.**

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/issues/2360#issuecomment-1646716162

**Comment by alphajoza** [comment]
> [#2360 (comment)](https://github.com/XTLS/Xray-core/issues/2360#issuecomment-1646716162)

The problem with using layer 4 proxies (such as haproxy, nginx, ...) for checking the SNI and diverting the traffic based on that, is that, (as far as I tested) when checking the TLS fingerprint of server (using [jarm](https://github.com/salesforce/jarm)), the fingerprint becomes all zeros, which if I'm not mistaken, defeats the purpose of using Reality in eliminating server TLS fingerprint characteristics.

**Comment by RPRX** [comment]
有没有一种可能，正是因为 SNI 分流会有问题，所以 REALITY 自身不支持 SNI 分流？

**Comment by RPRX** [comment]
有没有一种可能，正是因为 SNI 分流会有问题，所以 REALITY 才没有内置 SNI 分流？我们并不推荐 SNI 分流。
