### ISSUE TITLE
有支持针对udp和tcp的出站规则吗

### ISSUE THREAD

**Issue by bakasine** [XTLS/Xray-core#2379]
当前有一个应用场景, 我有一台中转和落地机, 落地机不支持udp所以希望能配置成当是udp的时候直接中转机出站

**Comment by chika0801** [comment]
```
{
    "log": {
        "loglevel": "warning"
    },
    "routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "type": "field",
                "network": "udp",
                "outboundTag": "direct"
            }
        ]
    },
    "inbounds": [

    "outbounds": [
        {
            "protocol": "shadowsocks",
            "settings": {
                "servers": [
                    {
                        "address": "落地机IP",
                        "port": 80,
                        "method": "2022-blake3-aes-128-gcm",
                        "password": "密码"
                    }
                ]
            },
            "tag": "落地机"
        },
        {
            "protocol": "freedom",
            "tag": "direct"
        }
    ]
}
```

第1个出站是连接到落地机的配置，路由中，把udp端口的请求，tag到  direct，即中转机出站，你试试了。

**Comment by bakasine** [comment]
> ```
> {
>     "log": {
>         "loglevel": "warning"
>     },
>     "routing": {
>         "domainStrategy": "IPIfNonMatch",
>         "rules": [
>             {
>                 "type": "field",
>                 "network": "udp",
>                 "outboundTag": "direct"
>             }
>         ]
>     },
>     "inbounds": [
> 
>     "outbounds": [
>         {
>             "protocol": "shadowsocks",
>             "settings": {
>                 "servers": [
>                     {
>                         "address": "落地机IP",
>                         "port": 80,
>                         "method": "2022-blake3-aes-128-gcm",
>                         "password": "密码"
>                     }
>                 ]
>             },
>             "tag": "落地机"
>         },
>         {
>             "protocol": "freedom",
>             "tag": "direct"
>         }
>     ]
> }
> ```
> 
> 第1个出站是连接到落地机的配置，路由中，把udp端口的请求，tag到 direct，即中转机出站，你试试了。
> 
> 什么商家的VPS落地机，没听过不能UDP出站的VPS。

感谢大佬, 可以了
是个垃圾线路的便宜香港鸡做的落地, 然后用腾讯云做中转拉直

**Comment by chika0801** [comment]
建议说下商家名字避坑

**Comment by bakasine** [comment]
> 建议说下商家名字避坑
hytron 这家

**Comment by chika0801** [comment]
这家在nodeseek loc看到不少帖子，名字有个印象
