### ISSUE TITLE
一个有关outbounds的问题

### ISSUE THREAD

**Issue by arootwzz** [XTLS/Xray-core#2380]
以下是我的配置，为了解锁流媒体，主用机是🇯🇵机器，解锁机是🇺🇸机器，但是当我使用下面的配置之后全部的流量都走了解锁机，任何地方查询本机ip均是🇺🇸那台机器的，这是怎么回事呢

{
  "log": {
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "listen": "0.0.0.0",
      "port": 443, //监听端口
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "UUID", //修改为自己的UUID
            "flow": "xtls-rprx-vision"
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "show": false, 
          "dest": "www.cloudflare.com:443", //转发给自己设定的目标网站，目标网站选择到自己服务器延迟低的。
          "xver": 0, 
          "serverNames": [
            "www.cloudflare.com" //修改为目标网站证书对应的域名
          ],
          "privateKey": "iEkYfzpc7lHJSQf_e3WsGwnsupaOrgZpYxuq7IqwBkI", //修改为执行xray x25519后生成的私钥。
          "shortIds": [ 
            "" //若有此项，客户端shortId可为空。若不为空，可0到f（0123456789abcdef），长度为2的倍数，长度上限为16。
          ]
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    }
  ],
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {  //奈飞流量规则
        "type": "field",
        "domain": [
          "geosite:netflix",
          "geosite:disney"
        ],
        "outboundTag": "Nf" 
      },
      {    //BT流量直连
        "type": "field",
        "protocol":[
          "bittorrent"
        ], 
        "outboundTag": "direct"
      },
      {   //直连中国大陆主流网站IP和保留IP
        "type": "field",
        "ip": [
          "geoip:cn",
          "geoip:private"
        ],
        "outboundTag": "direct" 
      },
      { //直连中国大陆主流网站域名
        "type": "field", 
        "domain": [
          "geosite:cn"
        ],
        "outboundTag": "direct"
      },
      {   //广告拦截
        "type": "field", 
        "domain": [
          "geosite:category-ads-all"
        ],
        "outboundTag": "block"  
      }
    ]
  },
  "outbounds": [
    {  //奈飞流量出站配置
      "tag": "Nf", //出站标识
      "protocol": "vless", //解锁节点协议类型
      "settings": {
        "vnext": [
          {
            "address": "x.x.x.x", //解锁节点ip地址
            "port": 443, //解锁机端口
            "users": [
              {
                "id": "UUID", //解锁节点uuid
                "encryption": "none",
                "flow": "xtls-rprx-vision" //解锁节点流控
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "serverName": "www.microsoft.com", //解锁节点目标网站
          "fingerprint": "chrome", //解锁节点uTLS
          "publicKey": "BbsXUhWriBmcf55OtVAbp68jWqv-1qduf0EXzIV8Xxk", //解锁节点公钥
          "shortId": "" //解锁节点shortId
        }
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom" 
    },
    {
      "tag": "block",
      "protocol": "blackhole"
    }
  ]
}
以下是日志

Jul 27 15:23:37 tk2-406-44131 xray[3893631]: Xray 1.8.3 (Xray, Penetrates Everything.) Custom (go1.20.5 linux/amd64)
Jul 27 15:23:37 tk2-406-44131 xray[3893631]: A unified platform for anti-censorship.
Jul 27 15:23:37 tk2-406-44131 xray[3893631]: 2023/07/27 15:23:37 [Info] infra/conf/serial: Reading config: /usr/local/etc/xray/config.json
Jul 27 15:23:38 tk2-406-44131 xray[3893631]: 2023/07/27 15:23:38 [Warning] core: Xray 1.8.3 started
Jul 27 15:23:43 tk2-406-44131 xray[3893631]: 2023/07/27 15:23:43 218.68.211.179:41077 accepted udp:1.1.1.1:53 [Nf]
Jul 27 15:23:43 tk2-406-44131 xray[3893631]: 2023/07/27 15:23:43 218.68.211.179:41077 accepted udp:1.1.1.1:53 [Nf]
Jul 27 15:23:43 tk2-406-44131 xray[3893631]: 2023/07/27 15:23:43 218.68.211.179:41077 accepted udp:1.1.1.1:53 [Nf]
Jul 27 15:23:43 tk2-406-44131 xray[3893631]: 2023/07/27 15:23:43 218.68.211.179:41077 accepted tcp:www.google.com:443 [Nf]
Jul 27 15:23:43 tk2-406-44131 xray[3893631]: 2023/07/27 15:23:43 218.68.211.179:41077 accepted tcp:beacons.gcp.gvt2.com:443 [Nf]
Jul 27 15:23:43 tk2-406-44131 xray[3893631]: 2023/07/27 15:23:43 218.68.211.179:41077 accepted tcp:mtalk.google.com:5228 [Nf]
Jul 27 15:23:44 tk2-406-44131 xray[3893631]: 2023/07/27 15:23:44 218.68.211.179:41077 accepted tcp:www.google.com:443 [Nf]
Jul 27 15:23:48 tk2-406-44131 xray[3893631]: 2023/07/27 15:23:48 218.68.211.179:41077 accepted udp:1.1.1.1:53 [Nf]
Jul 27 15:23:48 tk2-406-44131 xray[3893631]: 2023/07/27 15:23:48 218.68.211.179:41077 accepted udp:1.1.1.1:53 [Nf]
所有的流量全部走了Nf

**Comment by chika0801** [comment]
"outbounds"

你出站模块，第1个出站配置是NF，这是默认值。你应该把默认的改为

```
{
"tag": "direct",
"protocol": "freedom"
},
```

没在路由中命中 NF 规则的请求，就默认走到 "protocol": "freedom" 直连出站了。你看看

**Comment by arootwzz** [comment]
> > 非常感谢
> 
> 
> 
> 你试试应该能行，下次发配置用 ``` 3个这符号，加在代码最前和最后，就有格式了。看起方便一些。
好的，这是我第一次在GitHub发issue，好多格式还都不知道，因为这次谷歌和已有的issue实在是查不到结果，现在已经弄好了，我看了你的回复然后把出口模块Nf段代码的位置后置就解决了~
