### ISSUE TITLE
RAM usage bug in linux

### ISSUE THREAD

**Issue by hosseinkhojany** [XTLS/Xray-core#2384]
flutter:   "routing": {
flutter:     "domainStrategy": "AsIs",
flutter:     "rules": [
flutter:       {
flutter:         "type": "field",
flutter:         "inboundTag": [
flutter:           "api"
flutter:         ],
flutter:         "outboundTag": "api",
flutter:         "enabled": true
flutter:       },
flutter:       {
flutter:         "type": "field",
flutter:         "domain": [
flutter:           "regexp:.*.ir$",
flutter:           "ext:iran.dat:ir",
flutter:           "ext:iran.dat:other",
flutter:           "geosite:category-ir-gov",
flutter:           "geosite:category-ir-news",
flutter:           "geosite:category-ir-bank",
flutter:           "geosite:category-ir-tech",
flutter:           "geosite:category-ir-travel",
flutter:           "geosite:category-ir-shopping",
flutter:           "geosite:category-ir-insurance",
flutter:           "geosite:category-ir-scholar",
flutter:           "geosite:category-ir-payment",
flutter:           "geosite:category-ir-social-media",
flutter:           "geosite:category-ir-media",
flutter:           "geosite:category-ir-bourse",
flutter:           "geosite:category-ir",
flutter:           "google.com",
flutter:           "www.google.com",
flutter:           "snapp",
flutter:           "digikala",
flutter:           "speedtest",
flutter:           "whatismyipaddress",
flutter:           "tapsi",
flutter:           "blogfa",
flutter:           "bank",
flutter:           "sb24.com",
flutter:           "sheypoor.com",
flutter:           "tebyan.net",
flutter:           "beytoote.com",
flutter:           "telewebion.com",
flutter:           "Film2movie.ws",
flutter:           "Setare.com",
flutter:           "Filimo.com",
flutter:           "Torob.com",
flutter:           "Tgju.org",
flutter:           "Sarzamindownload.com",
flutter:           "soft98.ir",
flutter:           "downloadha.com",
flutter:           "P30download.com",
flutter:           "P30download.ir",
flutter:           "Sanjesh.org",
flutter:           "whatismyipaddress.comwww.whatismyip.com",
flutter:           "www.speedtest.net",
flutter:           "speedtest.net"
flutter:         ],
flutter:         "outboundTag": "direct",
flutter:         "enabled": true
flutter:       },
flutter:       {
flutter:         "type": "field",
flutter:         "ip": [
flutter:           "geoip:private",
flutter:           "geoip:ir"
flutter:         ],
flutter:         "outboundTag": "direct",
flutter:         "enabled": true
flutter:       }
flutter:     ]
flutter:   }
flutter: }

when I set this routing rule to xray core 1.8.3 or 1.8.1 my 8GB ram doing full in 20 second
I did test that confing in android ios or windows that was okay,but in linux nope!

**Comment by ZqinKing** [comment]
First you need to make sure that there is a formatting error in your json

**Comment by ZqinKing** [comment]
First you need to make sure that your JSON is not malformed

**Comment by hosseinkhojany** [comment]
I fix ram usage by change my tunnel from tun2socks to hev-socks5 but geo asset not working ):
