### ISSUE TITLE
@RPRX reality 是不是 不兼容 domain_socket 

### ISSUE THREAD

**Issue by architecturers** [XTLS/Xray-core#2390]
只在服务端 启动了 domain socket。
文件写道了 listen: "/tmp/xray.socket"
传输层 是grpc
服务端 无报错
客户端 报错：不能连接到服务端地址 
而且客户端 没有reality 握手成功的 信息

**Comment by chika0801** [comment]
Xray配置
```
                "realitySettings": {
                    "dest": "/dev/shm/nginx.sock",
                    "xver": 1,

```

nginx配置
```
    server {
        listen                  unix:/dev/shm/nginx.sock ssl proxy_protocol;
        http2                   on;

```

我是这样写的，是正常工作的。

**Comment by architecturers** [comment]
你这是偷自己啊。你试一试偷别人可以正常工作吗？

**Comment by chika0801** [comment]
我理解你问的问题是用  domain socket 写法，你没有通。

你回我的意思又是问偷别人？

建议你发你的配置文件，以便帮你，不然只能过猜。

**Comment by architecturers** [comment]
"dest": "/dev/shm/nginx.sock",
这句话是偷自己的证书
我的是
"dest": "www.minix.org:443",

**Comment by chika0801** [comment]
> 只在服务端 启动了 domain socket。
> 文件写道了 listen: "/tmp/xray.socket"


那你问的这2句话，你具体什么意思？

**Comment by architecturers** [comment]
我的意思你的tls证书是偷自己的nginx服务器的。我的是偷别人网站的。你试一试偷别人网站的能不能通

**Comment by architecturers** [comment]
`{
    //"log": {},
    
    //"api": {},
    
    "dns": {
        "servers": [
            "8.8.8.8",
            "localhost"
        ],
        
        //"clientIp": "1.2.3.4",
        //"queryStrategy": "UseIP",
        //"disableCache": false,
        //"disableFallback": false,
        //"disableFallbackIfMatch": false,
        "tag": "dns_inbound"
    },
    
    //"routing": {},
    //"policy": {},
    
    "inbounds": [
        {
            //"listen": "127.0.0.1",
            "port": "xxxxxx",
            
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "xxxxxxxxxxxxxxxxxxxxxxxxx"
                        //"level": 0,
                        //"email": "love@xray.com",
                        //"flow": "xtls-rprx-vision"
                    }
                ],
                "decryption": "none",
                
                "fallbacks": [
                    {
                        //"name": "",
                        //"alpn": "",
                        //"path": "",
                        "dest": "www.minix3.org:443"
                        //"xver": 0
                    }
                ]
            },
            
            "streamSettings": {
                
                "network": "grpc",
                "grpcSettings": {
                    "serviceName": "minix3"
                },
                
                "security": "reality",
                "realitySettings": {
                    "show": true,
                    "dest": "www.minix3.org:443",
                    //"xver": 0,
                    "serverNames": [
                        "",
                        "minix3.org",
                        "www.minix3.org:443"
                    ],
                    "privateKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                    //"minClientVer": "",
                    //"maxClientVer": "",
                    //"maxTimeDiff": 0,
                    "shortIds": ["xxxxxxxxxxxxxxxxxx"]
                }
            },
            
            "tag": "proxy-in",
            "sniffing": {"enabled": false}
        }
    ],
    
    "outbounds": [
        {
            "protocol": "freedom",
            "settings": {"domainStrategy": "UseIP"},
            
            "tag": "direct-out"
        }
    ]
    
    //"transport": {},
    //"stats": {},
    //"reverse": {},
    //"fakedns": {}
}

`

**Comment by chika0801** [comment]
看了一下你配置，你现在用这配置是不通吗？

你配置中，下面这段可以不写，也不起作用。其它地方没什么问题。
```
            "fallbacks": [
                {
                    //"name": "",
                    //"alpn": "",
                    //"path": "",
                    "dest": "www.minix3.org:443"
                    //"xver": 0
                }
            ]
```

**Comment by architecturers** [comment]
`

{
    //"log": {},
    
    //"api": {},
    
    "dns": {
        "servers": [
            "8.8.8.8",
            "localhost"
        ],
        
        //"clientIp": "1.2.3.4",
        //"queryStrategy": "UseIP",
        //"disableCache": false,
        //"disableFallback": false,
        //"disableFallbackIfMatch": false,
        "tag": "dns_inbound"
    },
    
    //"routing": {},
    //"policy": {},
    
    "inbounds": [
        {
            "listen": "/dev/shm/domain.socket,0666",
            "port": "xxxxxx",
            
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "xxxxxxxxxxxxxxxxxxxxxxxxx"
                        //"level": 0,
                        //"email": "love@xray.com",
                        //"flow": "xtls-rprx-vision"
                    }
                ],
                "decryption": "none",
                
                "fallbacks": [
                    {
                        //"name": "",
                        //"alpn": "",
                        //"path": "",
                        "dest": "www.minix3.org:443"
                        //"xver": 0
                    }
                ]
            },
            
            "streamSettings": {
                
                "network": "grpc",
                "grpcSettings": {
                    "serviceName": "minix3"
                },
                
                "security": "reality",
                "realitySettings": {
                    "show": true,
                    "dest": "www.minix3.org:443",
                    //"xver": 0,
                    "serverNames": [
                        "",
                        "minix3.org",
                        "www.minix3.org:443"
                    ],
                    "privateKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                    //"minClientVer": "",
                    //"maxClientVer": "",
                    //"maxTimeDiff": 0,
                    "shortIds": ["xxxxxxxxxxxxxxxxxx"]
                }
            },
            
            "tag": "proxy-in",
            "sniffing": {"enabled": false}
        }
    ],
    
    "outbounds": [
        {
            "protocol": "freedom",
            "settings": {"domainStrategy": "UseIP"},
            
            "tag": "direct-out"
        }
    ]
    
    //"transport": {},
    //"stats": {},
    //"reverse": {},
    //"fakedns": {}
}



`

**Comment by chika0801** [comment]
> 的意思你的tls证书是偷自己的nginx服务器的。我的是偷别人网站的。你试一试

https://github.com/chika0801/Xray-examples/tree/main/VLESS-gRPC-uTLS-REALITY

我用这套模板能通

**Comment by architecturers** [comment]
把入站的监听 改成
     "listen": "/dev/shm/domain.socket,0666",
就不通了

**Comment by architecturers** [comment]
第一个通的，改成第二个就不通了

**Comment by chika0801** [comment]
> 把入站的监听 改成 "listen": "/dev/shm/domain.socket,0666", 就不通了

因为只能Xray前置监听443端口，你这用法猜测是如NGINX前置监听443，传递给Xray是不行的。

除非你用 NGINX SNI 分流形式倒是可以。

**Comment by chika0801** [comment]
> 第一个通的，改成第二个就不通了

本来就不能这样简单改下，你如果提问描述清楚（有点提问技术）早给你说了。不用反复问你什么意思。

**Comment by architecturers** [comment]
我没装www服务器，从minix3偷证书

**Comment by architecturers** [comment]
minix3.org

**Comment by chika0801** [comment]
> 我没装www服务器，从minix3偷证书

那你 第2个配置中         `"listen": "/dev/shm/domain.socket,0666",` 你写这句，是哪个程序传递过来进Xray的？

**Comment by architecturers** [comment]
不能直接传递吗？
原始的是listen：“127.0.0.1”，是个Linux loopback 地址
domain_socket 是lo的另一种写法吗 只不过不走网络栈 速度更快

**Comment by chika0801** [comment]
你是服务端

你第1个配置
```
        //"listen": "127.0.0.1",
        "port": "xxxxxx",
```
这里你注释了 //"listen" 即不写这个参数，它默认值是0.0.0.0，表示对外监听v4+6，所以我也说你这段配置没问题。

你第2个配置
```
        "listen": "/dev/shm/domain.socket,0666",
        "port": "xxxxxx",
```
`        "listen": "/dev/shm/domain.socket,0666",` 我理解这是表示监听本机的一个进程传递，通常前面由一个程序（如NGINX）发过来，所以我前面也那样回你的。

如果你没理解到我说的意思，可能我们交流不在一个平台，还是那句话只能帮你到这了.

**Comment by architecturers** [comment]
好的 我再看看 谢谢你的帮助
