### ISSUE TITLE
how to use fragment in xray core?

### ISSUE THREAD

**Issue by TKZ2009** [XTLS/Xray-core#2392]
it seems like you're added the gfw_resist_tls_proxy fragment and 
i just wanna know how to use it in the xray core

**Comment by chika0801** [comment]
This is a feature added in version 1.8.3. I checked the documentation and it is in the ability to add a corresponding parameter when the outbound is freedom.

Documentation link: https://xtls.github.io/Xray-docs-next/config/outbounds/.html#outboundconfigurationobject

I don't know what scenario would use this parameter. This parameter is not used by many people in China.

**Comment by TKZ2009** [comment]
i wanna use workers too, but i can't find out how to use fragment in xray core
i used your frame but i dont know what i need to replace
can you plz tell me where and what i need to change in this frame?

**Comment by TKZ2009** [comment]
> "VLess WS TLS configuration can be made using Cloudflare workers. Although Cloudflare worker addresses are blocked in Iran, this Fragmented TLS Handshake Message method can still be used to unblock workers' domains. In fact, one of the benefits of this method is that it allows for the use of VLess WS TLS protocols even when there is no remote server available. To achieve this, the fragmentation setting in `freedom outbound` can be configured as follows:
> ```
> "fragment": {
> "packets": "tlshello",
> "length": "100-200",
> "interval": "10-20" // ms
> }
> ```
> This setting makes the domain of Cloudflare workers that were previously blocked open and usable."
> 
> 
> 
> 
> ```
> {
>   "log": {
>     "loglevel": "debug",
>     "dnsLog": false
>   },
>   "inbounds": [
>     {
>       "listen": "127.0.0.1",
>       "port": 10808,
>       "protocol": "socks",
>       "tag": "socks"
>     }
>   ],
>   "outbounds": [
>     {
>       "tag": "proxy",
>       "protocol": "VLESS",
>       "settings": {},
>       "streamSettings": {
>         "network": "ws",
>         "security": "tls",
>         "tlsSettings": {},
>         "wsSettings": {},
>         "sockopt": {
>           "dialerProxy": "fragment",
>           "mark": 255
>         }
>       }
>     },
>     {
>       "tag": "fragment",
>       "protocol": "freedom",
>       "settings": {
>         "fragment": {
>           "packets": "tlshello",
>           "length": "100-200",
>           "interval": "10-20"
>         }
>       },
>       "streamSettings": {
>         "sockopt": {
>           "TcpNoDelay": true,
>           "mark": 255
>         }
>       }
>     }
>   ]
> }
> ```

thank u so much. i can use it now. It gives me 600ms ping, which is good but it doesn't open youtube or other apps it just useble on telegram

**Comment by vfarid** [comment]
Just to prove fragment is important in Iran, look at the video I recorded with MCI internet, the largest mobile operator of Iran:
- in the first 4 attempts I tested a vless config over cloudflare worker. 2 failure + 2 unacceptable ping
- second time i added fragment to the same config and you can see all pings are about 600ms.

https://github.com/XTLS/Xray-core/assets/23278340/c95519b4-ef21-4c1f-b40b-40e487397387
