### ISSUE TITLE
请问代理连通性跟网络运营商有关系吗？

### ISSUE THREAD

**Issue by ZChidori** [XTLS/Xray-core#2395]
我家庭网络是广电网，用ssr的时候很正常但是v2就断断续续的，使用流量的时候都正常，请问可能是哪的原因呢？有没有办法优化

**Comment by chika0801** [comment]
只和你的vps商家到你这（你的运营商）线路质量好不好有关系。

建议你办个联通，大部分10-15刀年付的vps都能拉拉

**Comment by ZChidori** [comment]
我可以ssh访问到服务器，ssr使用正常也能说明连通性没问题，那么还有可能是什么原因导致的呢？

**Comment by chika0801** [comment]
先问下你说的ssr是指什么程序？
