### ISSUE TITLE
Would it be better if client side allows to configure several values for serverName and spiderX

### ISSUE THREAD

**Issue by nuying117** [XTLS/Xray-core#2396]
It seems that, in server side, we can configure several serverNames in realitySettings, in client side, from the current implementation, we'd pick one of them and configure it in the field serverName, but sometimes, when gfw detects it and slow down the speed, changing to another server name would help. I am thinking if in the client side, users also can configure several server names, then xray just pick one of it to use, would it increase the connection stability? i.e. not that easy to be detected by gfw?

and also some other testing shows that, changing the value of spiderX also helps, so probably, allowing some "randomized" spiderX or allowing users to configure a set of customized spiderX values, then xray just pick one in each transmission, it may also helps on the connection stability?

**Comment by chika0801** [comment]
> It seems that, in server side, we can configure several serverNames in realitySettings, in client side, from the current implementation, we'd pick one of them and configure it in the field serverName, but sometimes, when gfw detects it and slow down the speed, changing to another server name would help. I am thinking if in the client side, users also can configure several server names, then xray just pick one of it to use, would it increase the connection stability? i.e. not that easy to be detected by gfw?

The server side is configured with multiple service names, and the client fills in one of the list of service names on the server side, which should have been fixed by the author at design time. I think it's highly unlikely that the author referenced your suggestion.

> and also some other testing shows that, changing the value of spiderX also helps, so probably, allowing some "randomized" spiderX or allowing users to configure a set of customized spiderX values, then xray just pick one in each transmission, it may also helps on the connection stability?

There is a problem with the client filling in the value of spiderX. This parameter, in our area (mainland China), I don't think many users use it. I can't advise you on that either.

**Comment by nuying117** [comment]
> The server side is configured with multiple service names, and the client fills in one of the list of service names on the server side, which should have been fixed by the author at design time. I think it's highly unlikely that the author referenced your suggestion

I saw that you had anwsered many questions and should be an very experienced developer/user of xray, could you share your opinion about this proposal? :)

> There is a problem with the client filling in the value of spiderX. This parameter, in our area (mainland China), I don't think many users use it. I can't advise you on that either.

could you please share your suggestions? maybe I'd have to change the serverName manually?

**Comment by chika0801** [comment]
> could you please share your suggestions? maybe I'd have to change the serverName manually in case the speed is slown down?

If you are using REALITY, for example, dest is now using speedtest.net, and one day you feel that your client's upload or download speed is slowed down by the limitation, you can try to change dest to fill in the domain name of another website.

This phenomenon has been mentioned by some users from Iran region as far as I remember.

> I saw that you had anwsered many questions and should be an very experienced developer/user of xray, could you share your opinion about this proposal? :)

I am not an Xray developer. As a user then, I have no opinion for or against your proposal. It's up to the Xray developers.
