### ISSUE TITLE
h2: Dial Hangs on Client.Do(request)

### ISSUE THREAD

**Issue by IConfigYou** [XTLS/Xray-core#2402]
Hi
I am working on `h2` transport. However, it doesn't work as expected. after investigating source code and logging. I've noticed that h2 transport has `Dial` problem. after doing more, I found that this code block in `Dial` method is bug prone:
```
go func() {
response, err := client.Do(request)
....
}
```
when execution reaches to this function and line. hangs! **no error is thrown and no response** is retrieved. it worth to say that, I used `v2rayN` in both latest and last preview version but same results.

the strange thing is that when I use `nekobox` GUI client, I see the xray-core program didn't hang on `client.Do(request)` and request and responses are sent and received correctly.

both `nekobox` and `v2rayN` GUI clients use same xray-core. However, in `v2rayN` , `xray-core` hangs on `client.Do(request)` but in `nekobox`, `xray-core` do not hang

**Comment by RPRX** [comment]
刚好你可以帮忙测试下 https://github.com/XTLS/Xray-core/issues/2355#issuecomment-1646156399
