### ISSUE TITLE
现在vemss代理不能用了吗，第二天就封

### ISSUE THREAD

**Issue by sunjiabin17** [XTLS/Xray-core#2403]
这两天试着配了两次raksmart家的vps和amazon sg的ec2 服务器搭建vmess协议代理，都是第二天就封。最简单的配置
<img width="876" alt="image" src="https://github.com/XTLS/Xray-core/assets/41134681/55864103-d6f1-48fe-bd26-e4e2b1c59196">

**Comment by chika0801** [comment]
可以用，当你遇到客户端不通时，你会改配置去换端口就行了。

**Comment by sunjiabin17** [comment]
@chika0801 可是ip已经被墙了呀，ssh都连不上了，改端口还有用吗。。。

**Comment by chika0801** [comment]
不好意思，刚才没仔细看你发的图。下意识以为你用的是 VMESS + TCP + TLS

从你的图片中看你开的协议组合，交流时用语为 VMESS + TCP，它和如 SS + TCP 一样，用了是最后都是VPS被封IP的结果。所以建议你不要使用了。

**Comment by sunjiabin17** [comment]
好的谢谢，请教一下您有什么推荐的配置组合吗
________________________________

**Comment by nursery01** [comment]
你用了ID64，真的是好機會，你用代理連結ssh，看看log有沒有不認識的IP

**Comment by sunjiabin17** [comment]
@nursery01 ID64这个配置并没有使用，只用到了id0，因为id设置为0，ios端的小火箭才能连上，否则手机连不上

**Comment by chika0801** [comment]
> 推荐你用 https://github.com/chika0801/Xray-examples 这里面提示到协议组合类型。你可以手动安，复制粘贴配置，或用面板，或一键脚本等搭建。

> 推荐你用 https://github.com/chika0801/Xray-examples 这里面提示到协议组合类型。你可以手动安，复制粘贴配置，或用面板，或一键脚本等搭建。

前面说过了

**Comment by sunjiabin17** [comment]
@chika0801 非常感谢
