### ISSUE TITLE
trajan+ws+tls fallback，浏览器访问返回404

### ISSUE THREAD

**Issue by crazysvn** [XTLS/Xray-core#2406]
trojan+tcp的fallback是成功的。但trajan+ws+tls fallback，浏览器访问返回404

XrayR中trajan+ws+tls fallback部分的配置：
EnableFallback: true # Only support for Trojan and Vless
FallBackConfigs: # Support multiple fallbacks
-
SNI: # TLS SNI(Server Name Indication), Empty for any
Alpn: # Alpn, Empty for any
Path: # HTTP PATH, Empty for any
Dest: 983 # Required, Destination of fallback, check https://xtls.github.io/config/features/fallback.html for details.
ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for dsable

nginx配置：
server {
listen 983 http2;
root /www/wwwroot/fake-site; # 改成你自己的路径
index index.html;
server_name noname.com; # 改成你自己的域名
}

**Comment by chika0801** [comment]
建议提供 nginx xray 配置，才能帮你分析一下。

建议再建议我放弃使用 xxx ws tls 这一组合形式。

**Comment by RPRX** [comment]
https://xtls.github.io/config/features/fallback.html#fallbackobject “只能用于 TCP+TLS 传输组合”

因为 fallbacks 是 VLESS 层面的，你懂原理的话可以玩花的，不懂的话就遵循文档
