### ISSUE TITLE
GFW基於自己的dns和root dns獲取正常的dns-ip list，來判斷是否是代理網站或者sni欺詐

### ISSUE THREAD

**Issue by nursery01** [XTLS/Xray-core#2407]
我之前似乎搞錯了一個問題，我之前的專案是以平民視角進行旁路檢測代理，但是我忘記了GFW是擁有上帝視角的，它擁有鏡像root dns，isp也擁有自己的dns，也就是說它可能已經擁有接近完整的dns-ip list，它已經擁有dns-ip白名單了，能通過網域名稱拉取到正確的ip list，所以基於dns-ip判斷代理站是可以實現的，誤報率可以降至接近0，并且可以接近100%精準的識別非正常dns解析的代理網站，以及sni欺詐，實現原理是GFW基於自身的dns拉取正確的ip list，在通過另一個上帝視角，也就是OSI 1~4層拉取資訊，然後進行對比。如果ip發生變動了怎麽辦？如果ip發生變動，那麽就以最新的dns-ip爲準，不正常dns解析的網站封掉不會有太大影響，因爲當前dns-ip解析的網站可以正常訪問，銀行也可以正常工作

至於解決方法，我還是比較看好複製自己網站的方式。如果網站還有幾千人也許訪問會更好？(玄學？)

但是内層的時序和頻率還是難以掩蓋，只要使用它就會產生這種結果

**Comment by chika0801** [comment]
建议你发在讨论区

**Comment by RPRX** [comment]
我猜 GFW 还没研究出来如何拿到指定域名的所有合法 IP，否则已经在伊朗实装了，但它肯定在朝着这个方向努力，也有可能成功

我的看法是：https://github.com/XTLS/Xray-core/issues/2230#issuecomment-1598300822

**Comment by nursery01** [comment]
如果中國覺得有必要這麼做，我覺得憑中國人力和技術實裝這套系統，說得最慢一點3年內是可以的，畢竟這套系統沒有附加太大損害，並且十分精準

我目前在dns工作機制上知識也有欠缺，我拉取一次只拉到4條ip，這明顯不是完整的

Q 如果我研究出來會不會把它做出來？

A 不會，沒時間

**Comment by RPRX** [comment]
~~我觉得吧，都常温常压超导了，GFW 这种逆势的玩意儿还是别继续丢人现眼了~~
