### ISSUE TITLE
v2ray 中转路由后全局bilibli一直正在缓冲

### ISSUE THREAD

**Issue by CarbonPool** [XTLS/Xray-core#241]
客户端均为开启全局模式，不使用outbounds ss中转则不会出现一直正在缓冲 0kb，PC网页端是秒加载的，不知道app是什么情况
server v2fly 4.34.0
client v2rayNG xray-core 1.2.4
配置如下：
`{
	"inbounds": [
        {
            "port": 10004,
            "protocol": "vless",
            "listen":"127.0.0.1",
            "settings": {
                "clients": [
                    {
                        "id": "HIDE"
                    }
                ],
                "decryption": "none"
            },
            "tag": "v2hk",
            "streamSettings": {
                "network": "ws",
                "wsSettings": {
                    "path": "HIDE"
                }
            }
        }
    ],
	"outbounds": [
        {
            "protocol": "freedom",
            "settings": {},
            "tag": "direct"
        },
        {
            "protocol": "shadowsocks",
            "settings": {
                "servers": [
                    {
                        "address": "HIDE",
                        "port": "HIDE",
                        "method": "aes-128-gcm",
                        "password": "HIDE"
                    }
                ]
            },
            "streamSettings": {},
            "tag": "outhk"
        }
    ],
    "routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "type": "field",
                "inboundTag": "v2hk",
                "outboundTag": "outhk",
                "network": "tcp,udp"
            }
        ]
    }    
}
`

例如
![QQ图片20210210034250](https://user-images.githubusercontent.com/26106045/107418886-252b0a00-6b52-11eb-98b1-cf7f425baa43.png)
![Screenshot_2021-02-10-03-42-22-585_哔哩哔哩](https://user-images.githubusercontent.com/26106045/107418903-28be9100-6b52-11eb-9d3c-af72d73f3691.png)

开始有一点速度，后面就没速度了，目前不清楚是否还有限于其他服务器原因，但是只在app端发生。

**Comment by ymcoming** [comment]
先不谈这个问题，单纯你配置就不合理。想分流就特定网站分流，想中转就端口转发。从你的用法来说是全流量中转，v2ray-->ss，多了一次加解密，还不如端口转发。

回过来谈你遇到的问题，明显是dns解析的问题，至于pc和移动端解析的差异，那是2个平台的差异。你要定位问题，首先要确保2个平台都用同一DNS来解析

**Comment by CarbonPool** [comment]
> 先不谈这个问题，单纯你配置就不合理。想分流就特定网站分流，想中转就端口转发。从你的用法来说是全流量中转，v2ray-->ss，多了一次加解密，还不如端口转发。
> 
> 回过来谈你遇到的问题，明显是dns解析的问题，至于pc和移动端解析的差异，那是2个平台的差异。你要定位问题，首先要确保2个平台都用同一DNS来解析

我不太明白后面的意思，A服务器SS是阿里云轻量HK的默认DNS，B服务器vless是某服务器dns是1.1.1.1，在PC端是正常的，也开启过本地dns似乎在此问题上效果一致，有没有什么办法排除解决此问题呢

**Comment by ymcoming** [comment]
可能的原因就是PC那边本地DNS已经抢在v2ray设定的全局前面解析出了bilibli的国内服务器IP地址，所以是直连

而你手机NG，bilibli走了代理DNS，解析成了bilibili的海外服务器IP，因为你在NG上选择了全局代理，肯定就是代理DNS来解析IP，NG应该劫持了手机的本地DNS

同理，PC那边，V2ray没有劫持PC的本地DNS，所以正常。

NG的正确使用方式是分应用，或者直接让bilibli直连。加个这个 "domain": ["geosite:bilibili"]

**Comment by CarbonPool** [comment]
> 可能的原因就是PC那边本地DNS已经抢在v2ray设定的全局前面解析出了bilibli的国内服务器IP地址，所以是直连
> 
> 而你手机NG，bilibli走了代理DNS，解析成了bilibili的海外服务器IP，因为你在NG上选择了全局代理，肯定就是代理DNS来解析IP，NG应该劫持了手机的本地DNS
> 
> 同理，PC那边，V2ray没有劫持PC的本地DNS，所以正常。
> 
> NG的正确使用方式是分应用，或者直接让bilibli直连。加个这个 "domain": ["geosite:bilibili"]

感谢，添加直连接为我工作，
![Screenshot_2021-02-10-14-41-58-937_哔哩哔哩](https://user-images.githubusercontent.com/26106045/107475130-99939680-6bae-11eb-8da4-ab23fd4e8df5.png)

针对所有视频内容，我不太理解是否是routing配置原因，使用中转就会卡住，分应用代理无效，添加直连解决，但有上图那个问题，去掉那一层路由不走中直连不需要也可以浏览，目前发现应该仅限于b站发生。

**Comment by dongjuanyong** [comment]
正巧搞过双线策略路由，当时研究了一下b站的cdn策略
网页端，通过客户dns获得对应线路的ip，从对应线路的ip访问播放器直接获得视频cdn地址
手机端，通过访问阿里云的api接口（https://help.aliyun.com/document_detail/52679.html）获得所需要的cdn线路ip，与本机dns无关，即你所获得cdn线路与访问阿里云服务器的源地址相关

**Comment by CarbonPool** [comment]
> 正巧搞过双线策略路由，当时研究了一下b站的cdn策略
> 网页端，通过客户dns获得对应线路的ip，从对应线路的ip访问播放器直接获得视频cdn地址
> 手机端，通过访问阿里云的api接口（https://help.aliyun.com/document_detail/52679.html ）获得所需要的cdn线路ip，与本机dns无关，即你所获得cdn线路与访问阿里云服务器的源地址相关

也许正是阿里云轻量HK解析的问题，我刚刚使用了其他运营服务器同样的方法测试无此问题
