### ISSUE TITLE
可以用现有的privatekey 导出 publickey 吗

### ISSUE THREAD

**Issue by cary-sas** [XTLS/Xray-core#2412]
如果不小心把客户端的 publickey 丢失了，可以用服务端的 privatekey 再生成出正确的 publickey 吗？

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/blob/017b56adf53d4813d01252157140dd9df5688477/main/commands/all/x25519.go#L20

麻烦 @yuhan6665 更新下 https://xtls.github.io/document/command.html
