### ISSUE TITLE
客户端功能优化建议

### ISSUE THREAD

**Issue by ac169** [XTLS/Xray-core#2413]
目前使用遇到的问题：

1. Xray 二进制文件和附加的geoip.dat geosite.dat文件算下来基本都在35M以上了，这个大小对于PC来说不算什么对于一些小型设备来说实在太大了

> 建议:
>> 1. 能否单独出一个只有客户端所需功能的二进制文件，以减少二进制文件大小。毕竟 使用客户端的用户绝对比使用服务端的多。
>> 2. 将 geoip.dat geosite.dat 附加文件变为可选项，很多时候流量在进入 Xray 已经做过前置筛选，这个时候Xray只需要无脑向后端发送就可以了，所以这个区分功能能不是必须的。 比如 浏览器上已经使用了 SwitchyOmega 插件，基本上过来的都是需要处理的流量。

2. API 不太完善（特别是针对客户端功能方面）

> 建议:
>> 1. 增加多节点，导入切换等API功能，目前使用 1.6.x - 1.7.x 看到有 xray api ado  但是不是很清楚是否支持客户端常用的节点切换功能
>> 2. API 是否可以增加 Restful 版本，目前 gRPC 通用性感觉差点，特别是客户端方面

**Comment by Fangliding** [comment]
@ac169 1 不加geo文件 按文档写出来的配置直接喜提不能运行 这俩文件不能删觉得可以不要 太想当然了 大多数情况下都是需要这俩文件 
2 not planned（实际上是没人写） 要的话可以去用clash

**Comment by RPRX** [comment]
> 能否单独出一个只有客户端所需功能的二进制文件，以减少二进制文件大小。毕竟 使用客户端的用户绝对比使用服务端的多。

我觉得 Xray-core 并不大，以后基本上是保持这个体积了。当然可以有更小的，猜你想要：VLESS 内核 https://github.com/XTLS/Xray-core/issues/1880#issuecomment-1491614281

> 将 geoip.dat geosite.dat 附加文件变为可选项，很多时候流量在进入 Xray 已经做过前置筛选，这个时候Xray只需要无脑向后端发送就可以了，所以这个区分功能能不是必须的。 比如 浏览器上已经使用了 SwitchyOmega 插件，基本上过来的都是需要处理的流量。

是可选的啊，你配置不涉及 geo 的话直接删掉即可

> 增加多节点，导入切换等API功能，目前使用 1.6.x - 1.7.x 看到有 xray api ado 但是不是很清楚是否支持客户端常用的节点切换功能

~~说实话不想在屎山上添砖加瓦了，只想删东西，加这些功能不如直接重启。~~ 猜你想要：VLESS 内核 https://github.com/XTLS/Xray-core/issues/1880#issuecomment-1491614281

> API 是否可以增加 Restful 版本，目前 gRPC 通用性感觉差点，特别是客户端方面

~~同上~~

**Comment by ac169** [comment]
> @ac169 1 不加geo文件 按文档写出来的配置直接喜提不能运行 这俩文件不能删 觉得可以不要 太想当然了 大多数情况下都是需要这俩文件 放下游作者的角度想 上游一个变更 搞得要单独获取geo文件 你觉得是所有下游大动干戈好还是你自己自个把geo文件剥掉好 2 not planned（实际上是没人写） 要的话可以去用clash

“可选项” 这个词有歧义吗？

**Comment by RPRX** [comment]
不过我们或许可以把 Release 中默认包含的 geo 文件删掉，因为很多服务端脚本、GUI 客户端都有单独更新 geo 文件的功能了

**Comment by Fangliding** [comment]
> > @ac169 1 不加geo文件 按文档写出来的配置直接喜提不能运行 这俩文件不能删 觉得可以不要 太想当然了 大多数情况下都是需要这俩文件 放下游作者的角度想 上游一个变更 搞得要单独获取geo文件 你觉得是所有下游大动干戈好还是你自己自个把geo文件剥掉好 2 not planned（实际上是没人写） 要的话可以去用clash
> 
> “可选项” 这个词有歧义吗？

core是在release里发布的 我不知道release里有什么 "可选项" 达到目的只有两种 1是剥掉所有发布文件中的geo文件然后单独发布 我指的是这种 如果您指的是在release中的发布文件中再加一个后戳 比如 Xray-linux-32-without-geo.zip 之类的 那么这样会让本来就已经非常长的assets列表翻个倍从62个变成124个

**Comment by ac169** [comment]
> 我觉得 Xray-core 并不大，以后基本上是保持这个体积了。当然可以有更小的，猜你想要：VLESS 内核 [#1880 (comment)](https://github.com/XTLS/Xray-core/issues/1880#issuecomment-1491614281)

对于PC来说是不大，但是毕竟还是有很多存储不是很大的设备，

> 是可选的啊，你配置不涉及 geo 的话直接删掉即可

之前使用的时候并不是这样，配置文件也没有看到相关配置选项，他会自动下载这两个文件，最后好像手动建了一个空文件才解决问题

**Comment by RPRX** [comment]
> 对于PC来说是不大，但是毕竟还是有很多存储不是很大的设备，

很多 ×
极少数 √

> 之前使用的时候并不是这样，配置文件也没有看到相关配置选项，他会自动下载这两个文件，最后好像手动建了一个空文件才解决问题

这是你用的 GUI 客户端的事情，不是 Xray-core 的要求

**Comment by wy580477** [comment]
> 之前使用的时候并不是这样，配置文件也没有看到相关配置选项，他会自动下载这两个文件，最后好像手动建了一个空文件才解决问题

谁写的客户端工具找谁去，核心不背这锅

**Comment by Fangliding** [comment]
> > 我觉得 Xray-core 并不大，以后基本上是保持这个体积了。当然可以有更小的，猜你想要：VLESS 内核 [#1880 (comment)](https://github.com/XTLS/Xray-core/issues/1880#issuecomment-1491614281)
> 
> 对于PC来说是不大，但是毕竟还是有很多存储不是很大的设备，
> 
> > 是可选的啊，你配置不涉及 geo 的话直接删掉即可
> 
> 之前使用的时候并不是这样，配置文件也没有看到相关配置选项，他会自动下载这两个文件，最后好像手动建了一个空文件才解决问题

那是你自己用的软件自动下载了 xray core在加载的时候如果用到了但是没有geo文件 会直接抛出错误

**Comment by Fangliding** [comment]
> > > 我觉得 Xray-core 并不大，以后基本上是保持这个体积了。当然可以有更小的，猜你想要：VLESS 内核 [#1880 (comment)](https://github.com/XTLS/Xray-core/issues/1880#issuecomment-1491614281)
> > 
> > 
> > 对于PC来说是不大，但是毕竟还是有很多存储不是很大的设备，
> > > 是可选的啊，你配置不涉及 geo 的话直接删掉即可
> > 
> > 
> > 之前使用的时候并不是这样，配置文件也没有看到相关配置选项，他会自动下载这两个文件，最后好像手动建了一个空文件才解决问题
> 
> 那是你自己用的软件自动下载了 xray core在加载的时候如果用到了但是没有geo文件 会直接抛出错误

eg
```
Failed to start: main: failed to load config files: config.json > infra/conf: invalid field rule > infra/conf: failed to load GeoIP: private > infra/conf: failed to load file: geoip.dat > infra/conf: failed to open file: geoip.dat > open geoip.dat: The system cannot find the file specified
```

**Comment by ac169** [comment]
> > 之前使用的时候并不是这样，配置文件也没有看到相关配置选项，他会自动下载这两个文件，最后好像手动建了一个空文件才解决问题
> 
> 谁写的客户端工具找谁去，核心不背这锅

[![pPEtge0.jpg](https://s1.ax1x.com/2023/08/07/pPEtge0.jpg)](https://imgse.com/i/pPEtge0)

**Comment by ac169** [comment]
> 很多 × 极少数 √

这么说的话 二进制大小的问题就没有必要讨论了

> > 之前使用的时候并不是这样，配置文件也没有看到相关配置选项，他会自动下载这两个文件，最后好像手动建了一个空文件才解决问题
> 
> 这是你用的 GUI 客户端的事情，不是 Xray-core 的要求

[![pPEtge0.jpg](https://s1.ax1x.com/2023/08/07/pPEtge0.jpg)](https://imgse.com/i/pPEtge0)

上图就是我直接下载官方文件 不上传附加文件的结果 并没有使用任何第三方客户端

**Comment by Fangliding** [comment]
> > > 之前使用的时候并不是这样，配置文件也没有看到相关配置选项，他会自动下载这两个文件，最后好像手动建了一个空文件才解决问题
> > 
> > 
> > 谁写的客户端工具找谁去，核心不背这锅
> 
> [![pPEtge0.jpg](https://camo.githubusercontent.com/29472d5d109250d45fe226af8b4b3a4aca8893f9b2497701d397403510bc1f35/68747470733a2f2f73312e617831782e636f6d2f323032332f30382f30372f705045746765302e6a7067)](https://imgse.com/i/pPEtge0)

>这个时候Xray只需要无脑向后端发送就可以了，所以这个区分功能能不是必须的
结果你自己的配置文件里用了geosite:google

**Comment by wy580477** [comment]
> [![pPEtge0.jpg](https://camo.githubusercontent.com/29472d5d109250d45fe226af8b4b3a4aca8893f9b2497701d397403510bc1f35/68747470733a2f2f73312e617831782e636f6d2f323032332f30382f30372f705045746765302e6a7067)](https://imgse.com/i/pPEtge0)
> 
> 上图就是我直接下载官方文件 不上传附加文件的结果 并没有使用任何第三方客户端 这锅与客户端根本没有关系

。。。。。。。无 fuck 可说。

**Comment by ac169** [comment]
> > > > 之前使用的时候并不是这样，配置文件也没有看到相关配置选项，他会自动下载这两个文件，最后好像手动建了一个空文件才解决问题
> > > 
> > > 
> > > 谁写的客户端工具找谁去，核心不背这锅
> > 
> > 
> > [![pPEtge0.jpg](https://camo.githubusercontent.com/29472d5d109250d45fe226af8b4b3a4aca8893f9b2497701d397403510bc1f35/68747470733a2f2f73312e617831782e636f6d2f323032332f30382f30372f705045746765302e6a7067)](https://imgse.com/i/pPEtge0)
> 
> > 这个时候Xray只需要无脑向后端发送就可以了，所以这个区分功能能不是必须的
> 
> 结果你自己的配置文件里用了geosite:google

这个问题我也怀疑过，但是我搜索 配置文件中 geo 字样没有结果。等我重新弄一个

**Comment by ac169** [comment]
> > [![pPEtge0.jpg](https://camo.githubusercontent.com/29472d5d109250d45fe226af8b4b3a4aca8893f9b2497701d397403510bc1f35/68747470733a2f2f73312e617831782e636f6d2f323032332f30382f30372f705045746765302e6a7067)](https://imgse.com/i/pPEtge0)
> > 上图就是我直接下载官方文件 不上传附加文件的结果 并没有使用任何第三方客户端 这锅与客户端根本没有关系
> 
> 。。。。。。。无 fuck 可说。

秀儿

**Comment by RPRX** [comment]
> 这么说的话 二进制大小的问题就没有必要讨论了

目前为了极少数设备去裁剪 Xray 对我们来说收益太低，看你最初的发言应该是没用过 UPX，还有些裁剪 Xray 的项目你可以找找

> [![pPEtge0.jpg](https://camo.githubusercontent.com/29472d5d109250d45fe226af8b4b3a4aca8893f9b2497701d397403510bc1f35/68747470733a2f2f73312e617831782e636f6d2f323032332f30382f30372f705045746765302e6a7067)](https://imgse.com/i/pPEtge0)
> 
> 上图就是我直接下载官方文件 不上传附加文件的结果 并没有使用任何第三方客户端

100% 是你的配置里写有 "geosite:google"（如果只需要 geo 文件中的一小部分数据，有一些裁剪 geo 文件的项目你也可以找找）

**Comment by yiguoapp** [comment]
https://github.com/XTLS/libXray/blob/main/geo_cut.go

裁剪 geo 文件，来了来了。

**Comment by RPRX** [comment]
三年前说过 https://github.com/XTLS/Xray-core/issues/43#issuecomment-742519740 ，至今 Xray-core 的二进制大了约 1/3，或许是时候尽可能地默认启用 UPX 压缩了，这件事情比较简单

@yichya 应该比较熟悉（为了 reproducible，[编译文档](https://xtls.github.io/development/intro/compile.html) 需要新增压缩指引）

**Comment by ac169** [comment]
> UPX

这个方案其实早就了解过，问题是往往空间小的设备使用这个方案问题也不少。 空间这个问题就当我没说吧！

**Comment by ac169** [comment]
之前提的需求主要是在xray客户端集中部署这种场景下产生的问题和需求，如果是单机客户端，连上面的需求也没有!

**Comment by wangz-code** [comment]
> > 能否单独出一个只有客户端所需功能的二进制文件，以减少二进制文件大小。毕竟 使用客户端的用户绝对比使用服务端的多。
> 
> 我觉得 Xray-core 并不大，以后基本上是保持这个体积了。当然可以有更小的，猜你想要：VLESS 内核 [#1880 (comment)](https://github.com/XTLS/Xray-core/issues/1880#issuecomment-1491614281)
> 
> > 将 geoip.dat geosite.dat 附加文件变为可选项，很多时候流量在进入 Xray 已经做过前置筛选，这个时候Xray只需要无脑向后端发送就可以了，所以这个区分功能能不是必须的。 比如 浏览器上已经使用了 SwitchyOmega 插件，基本上过来的都是需要处理的流量。
> 
> 是可选的啊，你配置不涉及 geo 的话直接删掉即可
> 
> > 增加多节点，导入切换等API功能，目前使用 1.6.x - 1.7.x 看到有 xray api ado 但是不是很清楚是否支持客户端常用的节点切换功能
> 
> ~说实话不想在屎山上添砖加瓦了，只想删东西，加这些功能不如直接重启。~ 猜你想要：VLESS 内核 [#1880 (comment)](https://github.com/XTLS/Xray-core/issues/1880#issuecomment-1491614281)
> 
> > API 是否可以增加 Restful 版本，目前 gRPC 通用性感觉差点，特别是客户端方面
> 
> ~同上~
VLESS 内核 这个还有后续吗?
