### ISSUE TITLE
Google Admob Detecting Reality

### ISSUE THREAD

**Issue by DeusExMachina1993** [XTLS/Xray-core#2417]
hi, i can not open Google admob when using Xray with reality protocol, (i can open the site when using ssh tunneling with my vps).
is there any guide how can config reality to not detect by google?
![image](https://github.com/XTLS/Xray-core/assets/13149437/f1cb59e0-fcfa-4db9-940c-313112fe3009)

**Comment by Rangtian** [comment]
I can access Google Admob without any problem using Xray-Core 1.8.3 and Reality.

**Comment by chika0801** [comment]
你把你用的xray 服务端配置发一下，才能帮到

**Comment by DeusExMachina1993** [comment]
this is my xray-config
`{
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private",
          "geoip:ir"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      },
      {
        "outboundTag": "blocked",
          "domain": [
"regexp:.*\\.ir$",
"ext:iran.dat:ir",
"ext:iran.dat:other",
"geosite:category-ir",
"geosite:category-gov-ir",
"geosite:category-news-ir",
"geosite:category-media-ir",
"geosite:category-social-media-ir",
"geosite:category-bank-ir",
"geosite:category-payment-ir",
"geosite:category-insurance-ir",
"geosite:category-education-ir",
"geosite:category-tech-ir",
"geosite:category-travel-ir",
"geosite:category-shopping-ir",
"geosite:category-scholar-ir",
"geosite:category-bourse-ir",
"geosite:category-forums-ir",
"geosite:category-ads",
"geosite:category-ads-all",
            "snapp", "digikala", "divar", "tapsi", "blogfa", "irancell", "bank", "sb24.com", "sheypoor.com", "tebyan.net", "beytoote.com", "telewebion.com", "Film2movie.ws", "Setare.com", "Filimo.com", "Torob.com", "Tgju.org", "Sarzamindownload.com", "downloadha.com", "P30download.com", "Sanjesh.org", "apparat.com", "eitaa.com", "emofid.com", "yektanet.com", "zhaket.com", "rtl-theme.com", "tgju.org", "iranecar.com", "tasnimnews.com", "netafraz.com", "blogfa.com", "faradars.org", "parspack.com", "mehrnews.com", "iranserver.com", "agah.com", "mizbanfa.net", "mihanwebhost.com", "shahrekhabar.com", "abzarwp.com", "niazerooz.com", "music-fa.com", "yasdl.com", "sheypoor.com", "mihanwp.com", "maktabkhooneh.org", "doostihaa.com", "arzdigital.com", "heyvagroup.com", "sarzamindownload.com", "banimode.com", "istgah.com", "uploadboy.com", "upmusics.com", "snapp.taxi", "sahamyab.com", "hamyarwp.com", "blogsky.com", "iranhost.com", "motamem.org", "irantalent.com", "abasmanesh.com", "talahost.com", "rayamarketing.com", "meghdadit.com", "alopeyk.com", "sariasan.com", "nahayatnegar.com", "khabarvarzeshi.com", "civilica.com", "parscoders.com", "khanoumi.com", "19kala.com", "Farsnews.com", "Varzesh3.com", "Namnak.com", "Aparat.com", "telewebion.com", "torob.com", "ninisite.com", "safarmarket.com",  "ticket-charter.com", "blitcharter.com", "mrbilit.com", "flightio.com", "snapptrip.com", "utravs.com", "tikban.com", "melicharter.com", "digicharter.com", "kishzoom.net", "rahbal.com", "melicharter.org", "irtour.org", "aracharter.com", "charter1.net", "melicharter.net", "samtik.com", "charter361.com", "3click.com", "amincharter.com", "ticketarzan.com", "mancharter.net", "app.irancharter.mobi", "simorgh24.com", "ba-charter.com", "sourtik.com", "deltaban.com", "charter724.vip", "mellicharter.org", "charter123.net", "mahancharter.com", "cheapcharter.net", "eligasht.com", "kish44.com"
          ],
        "type": "field"
      }
    ]
  },
  "stats": {}
}`


my sni: www.speedtest.net
port: 443
flow: xtls-rprx-vision
