### ISSUE TITLE
闲置分享

### ISSUE THREAD

**Issue by hahatu112113** [XTLS/Xray-core#2418]
vless://cc5574bf-5e8c-4a0d-b0e3-[b2c8715ddcbe@45.89.107.246:48578](https://b2c8715ddcbe@45.89.107.246:48578/)?type=tcp&security=reality&sni=[www.icloud.com](https://www.icloud.com/)&pbk=S-g0oP36DShii1uPOnZDSEhp_wQghX6h68PgMivOmD4&flow=xtls-rprx-vision&fp=chrome#free|DXIb.love

**Comment by chika0801** [comment]
提醒慎用陌生链接

**Comment by xqzr** [comment]
#1878
