### ISSUE TITLE
(x)tlsSettings.alpn 默认值不生效

### ISSUE THREAD

**Issue by BioniCosmos** [XTLS/Xray-core#242]
```json
"fallbacks": [
    {
        "name": "example.com",
        "alpn": "http/1.1",
        "dest": 7000,
        "xver": 1
    },
    {
        "name": "example.com",
        "alpn": "h2",
        "dest": 7001,
        "xver": 1
    }
]
```

在指定 `(x)tlsSettings.alpn` 为 `["h2", "http/1.1"]` 时，上述配置工作正常。测试方法是使用 cURL 通过 `--http1.1` 和 `--http2` 参数分别进行请求。

文档中提到，`(x)tlsSettings.alpn` 的默认值是 `["h2", "http/1.1"]`，所以我尝试将该项删掉。这时，使用 HTTP/2 请求时工作正常，但使用 HTTP/1.1 时，日志中会出现以下错误：

```
[Info] [1368524018] proxy/vless/inbound: realAlpn =
[Warning] [1368524018] app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to find the default "alpn" config
```

cURL 返回 `curl: (52) Empty reply from server`。

感觉就像是没指定 HTTP/1.1 一样。

所以，是我对文档理解有误，还是程序出现 bug 了？

**Comment by rprx** [comment]
**现有关于 VLESS 的文档都是残的，之前被 v2fly 那边不懂的人乱改了一通，所以我现在只写代码不碰文档，你应当看这个版本：**

https://github.com/rprx/v2fly-github-io/blob/master/docs/config/protocols/vless.md#fallbackobject

**建议只按需用两种填法：省略、填 `"h2"`。**

**Comment by rprx** [comment]
（抱歉上面的回复是加粗的，因为现在想起来还是很气

**Comment by BioniCosmos** [comment]
> **所以模板里从未出现过填 `http/1.1`，因为客户端请求不一定带 ALPN，你填 `http/1.1` 此时就匹配不到了。**

这个我懂了，刚才把 `"alpn": "http/1.1"` 删掉后的确可以正常访问了。

但我还是不懂，为什么 `(x)tlsSettings.alpn` 指定 `["h2", "http/1.1"]` 和不指定（默认值）会有区别？指定时，`realAlpn = http/1.1`；不指定时，`realAlpn =` 且会出现 `failed to find the default "alpn" config`。难道说这一部分的文档也是错误的吗？请大佬为我排忧解惑！

**Comment by rprx** [comment]
确定行为是这样吗（我也觉得奇怪）

**Comment by JimhHan** [comment]
`transport`为 `tcp`时，`ALPN` 的默认值为`h2`：
https://github.com/XTLS/Xray-core/blob/523c416bb56b3e2ffe101e7c02a323cfa770bfda/transport/internet/tcp/hub.go#L75-L80

**Comment by GleenJi** [comment]
> 
> 
> > **所以模板里从未出现过填 `http/1.1`，因为客户端请求不一定带 ALPN，你填 `http/1.1` 此时就匹配不到了。**
> 
> 这个我懂了，刚才把 `"alpn": "http/1.1"` 删掉后的确可以正常访问了。
> 
> 但我还是不懂，为什么 `(x)tlsSettings.alpn` 指定 `["h2", "http/1.1"]` 和不指定（默认值）会有区别？指定时，`realAlpn = http/1.1`；不指定时，`realAlpn =` 且会出现 `failed to find the default "alpn" config`。难道说这一部分的文档也是错误的吗？请大佬为我排忧解惑！

一前一后顺序位置不对好像还真不一样，之前我用trojan 443 回落到80端口，xtls的alpn默认值也就是不填的情况下访问我的域名提示什么来的忘了反正无法访问我的网站，然后换成["http/1.1","h2"]才能正常打开，如果写成["h2", "http/1.1"]和默认不写一样的情况打不开

**Comment by BioniCosmos** [comment]
的确不一样。谁在前，谁的优先级高。虽然你把 HTTP/1.1 放前面可以正常，但这样 HTTP/2 基本就属于无效配置了。

**Comment by dongjuanyong** [comment]
发现个问题，以下基于回落到打开h2c支持的caddy（单一端口）。虽然配置文件的说明是这么写的：
```
alpn: [ string ]
一个字符串数组，指定了 TLS 握手时指定的 ALPN 数值。默认值为 ["h2", "http/1.1"]。
```
但实际上，不填alpn时，用curl --http1.1测试没问题。但加入-v仔细看

```
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=……以下略
```
会发现这么一句：
```
* ALPN, server did not agree to a protocol
```
**把`"alpn": ["h2"]`加入到配置中，与以上测试结果一致**

而把默认的
```
    "alpn": [
        "h2",
        "http/1.1"
    ],
```
加上重新测试，反应如预期般正常
```
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http/1.1
```
感觉配置说明文件似乎和实际代码不一致

**Comment by AkinoKaede** [comment]
@dongjuanyong 

https://github.com/XTLS/Xray-core/blob/523c416bb56b3e2ffe101e7c02a323cfa770bfda/transport/internet/tcp/hub.go#L75-L80

在使用 TCP 时，ALPN 被设为 h2

**Comment by dongjuanyong** [comment]
> @dongjuanyong 
> 
> https://github.com/XTLS/Xray-core/blob/523c416bb56b3e2ffe101e7c02a323cfa770bfda/transport/internet/tcp/hub.go#L75-L80
> 
> 在使用 TCP 时，ALPN 被设为 h2
> 

文档里写的默认配置是没问题的（h2+http1.1），而实际代码是这样的话（只有h2）很令人费解。
web server我研究的不多，会有很对只支持h2而不支持http1.1的server存在么，这样是不是很容易暴露？

**Comment by AkinoKaede** [comment]
> > @dongjuanyong
> > https://github.com/XTLS/Xray-core/blob/523c416bb56b3e2ffe101e7c02a323cfa770bfda/transport/internet/tcp/hub.go#L75-L80
> > 
> > 在使用 TCP 时，ALPN 被设为 h2
> 
> 文档里写的默认配置是没问题的（h2+http1.1），而实际代码是这样的话（只有h2）很令人费解。
> web server我研究的不多，会有很对只支持h2而不支持http1.1的server存在么，这样是不是很容易暴露？

这个是 DarienRaymond 写的，不太清楚她当时的想法，当时是没有回落这个功能的

**Comment by rprx** [comment]
考古发现，之前 dialer 和 hub 都是默认只写 h2 https://github.com/v2ray/v2ray-core/commit/30f27706e0e12669b20bdd47992a792dbc2579fc

去年修指纹问题时改了 dialer 和文档，没改 hub https://github.com/v2ray/v2ray-core/commit/8e791e92bc1898e11904bf54462635aed864cd04

**Comment by rprx** [comment]
@GleenJi https://github.com/XTLS/Xray-core/issues/275#issuecomment-781106450

**Comment by rprx** [comment]
@GleenJi 你需要单独设置 alpn h2 时回落到 Nginx 的 h2c，而不是 80 端口
