### ISSUE TITLE
河南新上的SNI/HOST黑名单墙

### ISSUE THREAD

**Issue by 5e2t** [XTLS/Xray-core#2426]
新开个issue，防止在别人的帖子回复时，打扰到别人.......

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/issues/2229

**Comment by Fangliding** [comment]
@5e2t 所以到底是rst包被Linux过滤了还是Linux发出的包由于某些特征免于拦截

**Comment by RPRX** [comment]
我想说的是在 #2229 继续讨论，你这非要搞两个地方。。。

**Comment by RPRX** [comment]
1. 电脑是“直出”还是经过了路由器
2. 你在 WireShark 内看到 TTL 改了吗
3. 问题不在 IP 栈的话，可能在 TCP 栈，看一下 window、MSS 等有什么区别

**Comment by RPRX** [comment]
你对比一下 Windows 和 Linux 的 TTL 相同时，它们发出的 TCP 数据报有哪些区别，发到这里

**Comment by capxax** [comment]
> * 电脑是“直出”还是经过了路由器
> * 你在 WireShark 内看到 TTL 改了吗
> * 问题不在 IP 栈的话，可能在 TCP 栈，看一下 window、MSS 等有什么区别

在河南昨天用reality，用的自己的.xyz域名，连了大概1小时后，发现打不开，后来用浏览器访问自己的域名，也会显示连不上，但是ip可以访问，后来reality偷微软的域名，就可以连上了

**Comment by capxax** [comment]
![IMG_8884](https://github.com/XTLS/Xray-core/assets/20886982/8d79f668-026e-4b78-814d-26d709fb4803)
自己的域名打不开，但是ip可以

**Comment by RPRX** [comment]
把 Windows 的改成和 Linux 相同看看

**Comment by RPRX** [comment]
@capxax 抱歉折叠了图，有点刷屏，看起来最近河南上了 SNI 黑名单，~~可能 .xyz 整个都黑了~~

**Comment by mclovin-2k** [comment]
> @capxax 抱歉折叠了图，有点刷屏，看起来最近河南上了 SNI 黑名单，~可能 .xyz 整个都黑了~

6月份就有人反应这个情况了。
而且不光是代理，正经建站的也会被封域名。

**Comment by RPRX** [comment]
注：白底的是 Windows，黑底的是 Linux

@5e2t 看一下 TCP 的第一个 SYN 包

**Comment by RPRX** [comment]
目前看起来最有可能是 `TCP Option - Timestamps`，你 Windows 加上它或 Linux 删掉它看看

**Comment by RPRX** [comment]
Bingo，~~看来 GFW 又偷懒了~~

之前你说 Linux 虚拟机的网络模式改为 NAT 会收到 RST，看看是不是 TTL 的原因（修改 Linux 的 TTL 为 64、128 左右）

**Comment by nursery01** [comment]
謝謝你的發現喔，我又知道了一個虛擬機的設計機制

**Comment by RPRX** [comment]
这是实现的锅，其实它也可以选择保留这个选项，这个虚拟机的“NAT 模式”可能是为了简单而几乎完全重新封装 TCP，更像是代理

**Comment by RPRX** [comment]
关于 TSopt，RFC 7323 的规定如下：

<details>

```
   A TCP MAY send the TSopt in an initial <SYN> segment (i.e., segment
   containing a SYN bit and no ACK bit), and MAY send a TSopt in
   <SYN,ACK> only if it received a TSopt in the initial <SYN> segment
   for the connection.

   Once TSopt has been successfully negotiated, that is both <SYN> and
   <SYN,ACK> contain TSopt, the TSopt MUST be sent in every non-<RST>
   segment for the duration of the connection, and SHOULD be sent in an
   <RST> segment (see Section 5.2 for details).  The TCP SHOULD remember
   this state by setting a flag, referred to as Snd.TS.OK, to one.  If a
   non-<RST> segment is received without a TSopt, a TCP SHOULD silently
   drop the segment.  A TCP MUST NOT abort a TCP connection because any
   segment lacks an expected TSopt.

   Implementations are strongly encouraged to follow the above rules for
   handling a missing Timestamps option and the order of precedence
   mentioned in Section 5.3 when deciding on the acceptance of a
   segment.

...

   [RFC1323] recommended that <RST> segments NOT carry timestamps and
   that they be acceptable regardless of their timestamp.  At that time,
   the thinking was that old duplicate <RST> segments should be
   exceedingly unlikely, and their cleanup function should take
   precedence over timestamps.  More recently, discussions about various
   blind attacks on TCP connections have raised the suggestion that if
   the Timestamps option is present, SEG.TSecr could be used to provide
   stricter acceptance tests for <RST> segments.

   While still under discussion, to enable research into this area it is
   now RECOMMENDED that when generating an <RST>, if the segment causing
   the <RST> to be generated contains a Timestamps option, the <RST>
   should also contain a Timestamps option.  In the <RST> segment,
   SEG.TSecr SHOULD be set to SEG.TSval from the incoming segment and
   SEG.TSval SHOULD be set to zero.  If an <RST> is being generated
   because of a user abort, and Snd.TS.OK is set, then a Timestamps
   option SHOULD be included in the <RST>.  When an <RST> segment is
   received, it MUST NOT be subjected to the PAWS check by verifying an
   acceptable value in SEG.TSval, and information from the Timestamps
   option MUST NOT be used to update connection state information.
   SEG.TSecr MAY be used to provide stricter <RST> acceptance checks.
```

</details>

太长不看版：**（2014）建议 RST 带上 TSopt，接收方应检查，以对抗 RST 攻击（GFW 常用于阻断 TCP 连接的手段）**

最有可能是你那边的 GFW 没处理这种情况，只会发普通 RST 包，~~结果还没到你电脑就被扔了~~

**Comment by RPRX** [comment]
启用 TCP Timestamps 选项，Windows：

```
netsh interface tcp set global timestamps=enabled
```

Linux（IPv6 应该类似吧）：

```
sysctl -w net.ipv4.tcp_timestamps=1
```

显然人们不知道自己的设备有没有开 TSopt，有的默认开了就没被阻断，这就是人们对河南新上的 SNI 黑名单说法不一的原因之一

**Comment by Fangliding** [comment]
> 启用 TCP Timestamps 选项，Windows：
> 
> ```
> netsh interface tcp set global timestamps=enabled
> ```
> 
> Linux（IPv6 应该类似吧）：
> 
> ```
> sysctl -w net.ipv4.tcp_timestamps=1
> ```
> 
> 显然人们不知道自己的设备有没有开 TSopt，有的默认开了就没被阻断，这就是人们对河南新上的 SNI 黑名单说法不一的原因之一

补充一点 Windows查看该选项是否启用 ```netsh interface tcp show global``` RFC 1323 时间戳 比如我这就是开的（）

**Comment by RPRX** [comment]
~~下一步就是等你那边的 GFW 修复了~~，若这个方法凉了还能根据 TTL 扔 RST 包，~~结果 GFW 看到这句同时又安排上了~~

~~总之各地 GFW 的供应商不一，而这种最基础的 RST 攻击都是自己写的，这里不漏那里漏，长期可用，就像新手总会写出 SQL 注入~~

**Comment by toyo2333** [comment]
mac系统和ios系统呢？

**Comment by RPRX** [comment]
@toyo2333 Google?

@5e2t 我更新了 https://github.com/XTLS/Xray-core/issues/2426#issuecomment-1672957790 ，最后一行你看一下

**Comment by Fangliding** [comment]
> @RPRX 我只能说在这件事情上，似乎越新的系统越占优势，我的手机能访问，跟我的手机是安卓13系统，应该有些关系

很多手机UI这个选项是开的 可以用adb shell看 或者root了也可以看（和启用）

**Comment by RPRX** [comment]
> @RPRX 而且最重要的是...........是完全不知道怎么测试

~~写一个 XGFW 就好测试了~~

> RFC 1323 时间戳初始是allowed，和enabled有区别吗

@simpleandstupid 看它说明 allowed 仅是入站允许，而 enabled 还加了出站主动协商，所以应改成 enabled

**Comment by awsawsz** [comment]
![image](https://github.com/XTLS/Xray-core/assets/141311002/5c0e83a7-7e43-4be3-aa4d-532906298be3)
刚开始还好，请问这是升级后伪装结果不让握手成功吗？

**Comment by toyo2333** [comment]
> netsh interface tcp show global

我这里是allowed，win11系统。目前都正常。 那还有必要改为enabled么？

**Comment by awsawsz** [comment]
> @awsawsz 我不是很懂你的这个RST，你这个RST跟我的是不一样的。

这个已经是设置后又出现的新阻断了，不再瞬时收到RST了，帮忙分析一下吧

**Comment by Mrzqd** [comment]
移动数据被reset应该四月份左右就开始了，我在四月份的时候一个正常建站的域名就被reset了，省外和宽带都正常，只有在河南省使用移动数据时候被reset。

**Comment by changqingmundus** [comment]
確實，這個我也遇到過，移動電信最狠，聯通有時還有點緩存能用

**Comment by chika0801** [comment]
https://www.nodeseek.com/post-18486-1
一个帖子

**Comment by awsawsz** [comment]
> @awsawsz 既然不再瞬时收到RST了，那你应该就已经是不再被阻断了。这个RST可能只是服务器正常发的RST而已。

你说对了，的确不一样，现在它学会狂发包，和瞬时RST不一样，学会了发很多个。
有没有方法设置TTL延迟接受时间。

**Comment by toyo2333** [comment]
mac和ios会有这个问题么？怎么预设配置避免这个情况？

**Comment by SakuraChanNya** [comment]
我真服了这些人。打击翻墙就打击的精准点，为什么搞一刀切害我们正常站长的网站，是没技术吗？

**Comment by mclovin-2k** [comment]
> 我真服了这些人。打击翻墙就打击的精准点，为什么搞一刀切害我们正常站长的网站，是没技术吗？我们正常网站里又没有任何违规内容，就因为访问人数多，在河南给一刀切死了。

是的  就是没那个技术

**Comment by SakuraChanNya** [comment]
> > 我真服了这些人。打击翻墙就打击的精准点，为什么搞一刀切害我们正常站长的网站，是没技术吗？我们正常网站里又没有任何违规内容，就因为访问人数多，在河南给一刀切死了。
> 
> 是的 就是没那个技术

没技术就老老实实用保守的方法，把误伤降到最低，这样搞算什么本事？只能说____

**Comment by mclovin-2k** [comment]
> > > 我真服了这些人。打击翻墙就打击的精准点，为什么搞一刀切害我们正常站长的网站，是没技术吗？我们正常网站里又没有任何违规内容，就因为访问人数多，在河南给一刀切死了。
> > 
> > 
> > 是的 就是没那个技术
> 
> 没技术就老老实实用保守的方法，把误伤降到最低，这样搞算什么本事？只能说____

他们是向上负责的，所以就……

**Comment by awsawsz** [comment]
> 我真服了这些人。打击翻墙就打击的精准点，为什么搞一刀切害我们正常站长的网站，是没技术吗？我们正常网站里又没有任何违规内容，就因为访问人数多，在河南给一刀切死了。

这事儿也好办，如果你是正规站长，网上工信部投诉，让河南干部看看给网络造成的伤害，或许给你域名放出来呢？

**Comment by SakuraChanNya** [comment]
> > 我真服了这些人。打击翻墙就打击的精准点，为什么搞一刀切害我们正常站长的网站，是没技术吗？我们正常网站里又没有任何违规内容，就因为访问人数多，在河南给一刀切死了。
> 
> 这事儿也好办，如果你是正规站长，网上工信部投诉，让河南干部看看给网络造成的伤害，或许给你域名放出来呢？

投诉能有用？我的站在福建那种懂的都懂的地方，甚至都没像河南这样完全封死

**Comment by awsawsz** [comment]
> > > 我真服了这些人。打击翻墙就打击的精准点，为什么搞一刀切害我们正常站长的网站，是没技术吗？我们正常网站里又没有任何违规内容，就因为访问人数多，在河南给一刀切死了。
> > 
> > 
> > 这事儿也好办，如果你是正规站长，网上工信部投诉，让河南干部看看给网络造成的伤害，或许给你域名放出来呢？
> 
> 投诉能有用？只能试试看。 我的站在福建那种懂的都懂的地方，甚至都没像河南这样完全封死

被打要还手，如果不能还手起码也得喊疼啊，不能让人瞧不起

**Comment by Framyy** [comment]
怀疑河南已经修复,windows开启RFC 1323时间戳后仍然收到reset, 运营商河南电信
![image](https://github.com/XTLS/Xray-core/assets/95495416/379870dd-73e2-4a31-812c-babeb539a145)

**Comment by RPRX** [comment]
@Framyy 看 https://github.com/XTLS/Xray-core/issues/2426#issuecomment-1672957790 最后两行，@5e2t 那里 RST 包根本就没到电脑，是中间路由扔的，可能你的线路上均没有严格检查

你遇到的情况可能证明了 Windows 也没严格检查 RST 包，所以这个方法能否实际起作用还得看中间路由，~~或者给 Windows 打补丁~~

**Comment by chika0801** [comment]
@5e2t 这儿

> @nodemynode [#0](https://www.nodeseek.com/post-18486-1#0) 发布于2023/8/10 20:36:33，编辑于2023/8/11 11:49:50
> # SNI阻断情况
> > 近期访问我的N IP小站时，经常出现SNI阻断情况。
> > 原本以为是地市做的阻断，但是经过对Nginx日志分析后，发现全国各省市普遍存在SNI情况。
> 
> ## 1. 简要说明
> - 当前的SNI墙对于`白名单域名`外的任意域名均存在SNI阻断情况。这个白名单不是指备案，可能为通管部门做的白名单。
> - 阻断的表现为:
> 	- `客户端` 连接 `站点服务器`
> 	- `阻断设备` 向`站点服务器` 发送 `TCP RST包`
> 		- 站点服务器若使用nginx,则可在日志中查到状态码为`499`的条目
> 		- `cat access.log |grep " 499 "`  该命令简单过滤出499状态码的日志条目
> 	- `阻断设备` 向`客户端` 发送 `TCP RST包`
> 		- 客户端表现为:  浏览器提示`ERR_CONNECTION_RESET`
> 		- 使用wireshark抓包,过滤出站点服务器IP,即可看到TCP RST包
> - 499状态码的定义
> 	- 参考[nginx 499错误原因](https://blog.csdn.net/github_30641423/article/details/119787706)
> 	- ![](https://i.miji.bid/2023/08/10/b31b6d6538e06cda89b1b5f855aff306.png)
> 	- 即: 服务端以为客户端提前断开连接
> 
> ## 2. 地域性阻断统计
> - 以下为数据统计表
> ![](https://i.miji.bid/2023/08/10/ec35f066dee98e19b5a147148fc5df54.png)
> ![](https://i.miji.bid/2023/08/10/cbc9bb74722828430eeea70ac2f16225.png)
> 
> ## 3. SNI阻断的特性
> - 根据近期站点Nginx日志分析,得出以下结论.
> 	- **域名SNI阻断不分地区,全国人人可得**
> - 日志为`同一域名,同一IP,无CDN,国外域名,HK IP`情况下得到
> 	- 域名注册时间不超过一个月
> 	- 站点/IP/域名无违规内容
> - 日志数据量
> 	- 总访问量约: **130W**
> 	- 499日志约:   **22W**
> 	- 阻断概率约: 15% ~ 20%
> 
> ## 4. 后续
> - 测试了一些导致SNI阻断的情况
> 	- 子域名指向境外服务器,阻断情况会根据访问量逐渐提高,直到`完全封禁`该子域名,有概率喜提`主域名完全封禁`.
> 	- 停止解析一段时间时间后,会自动解除`完全封禁`,恢复到`间断性/概率性`阻断的情况.
> 	- 若有多个不同域名(例如a.11.com/b.22.com)指向同一境外服务器,则会`完全封禁`指向该IP的子域名
> - **使用境内IP+境内备案域名,且无子域名指向境外情况下,一般不会阻断**
> 	- 若有子域名指向境外,且访问量过高,会导致 `*.domain.com` 被封禁.
> 	- 不同地区之间也会有SNI墙,阻断设备不止一层,市级有市级的阻断,省级有省级的阻断,国际出口有国际出口的阻断设备
> 
> -----
> ## 补充
> - 联通全国阻断率22%
> - 移动全国阻断率16%
> - 电信全国阻断率29%

**Comment by chika0801** [comment]
转一个链接 解决SNI阻断的办法

https://telegra.ph/%E8%A7%A3%E5%86%B3SNI%E9%98%BB%E6%96%AD%E7%9A%84%E5%8A%9E%E6%B3%95-08-11

**Comment by chika0801** [comment]
win11 查询的结果
```
TCP 全局参数
----------------------------------------------
接收方缩放状态          : enabled
接收窗口自动调节级别    : normal
加载项拥塞控制提供程序  : default
ECN 功能                      : disabled
RFC 1323 时间戳                 : allowed
初始 RTO                         : 1000
接收段合并状态    : enabled
非 Sack Rtt 复原             : disabled
最大 SYN 重新传输次数             : 4
快速打开                           : enabled
快速打开回退                  : enabled
HyStart                             : enabled
比例费率降低         : enabled
节奏配置文件                      : off
```

**Comment by awsawsz** [comment]
> 怀疑河南已经修复,windows开启RFC 1323时间戳后仍然收到reset, 运营商河南电信 ![image](https://user-images.githubusercontent.com/95495416/259968154-379870dd-73e2-4a31-812c-babeb539a145.png)

你这个就和我手机网络一样了，宽带和手机网络不是一个

**Comment by RPRX** [comment]
@chika0801 ？？？

**Comment by chika0801** [comment]
https://github.com/XTLS/Xray-core/issues/2426#issuecomment-1674281825

发的是这个帖子的内容

**Comment by RPRX** [comment]
@chika0801 感觉你最近不太正常啊，没看 issue 不至于 channel 也没看吧，你发的链接不就是这里的研究？上次你忘了 https://github.com/XTLS/Xray-core/discussions/2211 我就觉得有点怪，之后还有一件事也让我觉得怪，~~话说你是 chika0801 吗，爆金币被 JC 登号的是你？~~

还有这简中互联网是什么垃圾场，那个链接把这里的内容复制过去，再在下面附上“教程来自”两个机场，也是令人开眼

**Comment by chika0801** [comment]
打扰了，已折叠

**Comment by RPRX** [comment]
@chika0801 关键你以前挺细心的，记性也挺好的，最近是咋回事，~~换人了？~~

**Comment by RPRX** [comment]
@5e2t 你先用移动网络找到一个即使开了 TSopt 也只会发普通 RST 包的网站，再测一下家宽开了 TSopt 是不是收不到它的 RST 包

**Comment by RPRX** [comment]
@5e2t 找一个“正常”的网站

**Comment by RPRX** [comment]
“你先用移动网络找到一个即使开了 TSopt 也只会发普通 RST 包的网站”，指的是网站自己发的 RST 包，不是 GFW 发的

**Comment by RPRX** [comment]
> 也不可能是运营商固定宽带网络上的路由器 扔的不带Timestamps的RST（因为显然运营商必须配合墙）

> 总结： 墙不给 开了TCP Timestamps的固定宽带网络 发RST， 给没开TCP Timestamps选项的固定宽带网络发RST，

因为这样推有点怪，这次的 SNI 黑名单看起来挺统一的，专门对某条线路检查 TSopt 然后不发 RST 的概率太低，~~除非是故意留后门~~

我觉得更有可能是一些线路上有较新的设备，自带较新的安全功能，比如严格检查了 RST 包，要测这个就是按上面我说的方法

**Comment by awsawsz** [comment]
> @RPRX 总结： 墙不给 开了TCP Timestamps的固定宽带网络 发RST， 给没开TCP Timestamps选项的固定宽带网络发RST，
> 
> 对于数据流量网络，无论开不开TCP Timestamps，墙都会发伪造的RST。
> 
> 无论任何一种情况，均未收到过带Timestamps的 RST。

这个是最终答案，两个网络经过不同的路由器。可能设置了不同的策略。
数据流量网络的RST发送可能无法绕过，客户端和服务端同发，而且发送频率是针对每一条，简单timestamps无法绕过。
看来RST攻击针对TCP连接是非常有效的。

**Comment by RPRX** [comment]
@5e2t 检查 TTL 是 VPS 发给你的吗，~~还是很难接受专门对于特定线路检查 TSopt 然后不发 RST 这种设定~~

**Comment by RPRX** [comment]
还有一种可能是对你的家宽来说，SNI 黑名单发 RST 的回程线路（原路？）上有设备严格检查了 RST 包，但 VPS 的回程线路没有

**Comment by RPRX** [comment]
@5e2t 那可能是因为上面那句话，或者有其它的可能，总之“~~还是很难接受专门对于特定线路检查 TSopt 然后不发 RST 这种设定~~”

@awsawsz 你说的这个是我的猜想，~~和你引用的猜想正好相反~~

**Comment by mclovin-2k** [comment]
> TCP timestamps选项在TCP报头的最后12字节里，”固定宽带网络“上的墙，可能直接把TCP timestamps选项的这12字节，当成clienthello 的前12字节了，导致根本识别不出来clienthello。 @RPRX

这个看起来是比较合理的推测。就是宽带网络墙的代码写的不太好有BUG。

**Comment by RPRX** [comment]
> 根据推测，由于开启了TCP timestamps选项之后 TCP报头 多了12字节，应当是”固定宽带网络“ 上的墙在 遇到开启TCP timestamps的流量时 识别不出来clienthello了，所以就无法对黑名单里的域名发RST了。 @RPRX 

@5e2t ~~这个长度没必要硬编码吧~~，你测一下客户端开 TCP timestamps，服务端不开

**Comment by RPRX** [comment]
@5e2t 那找个其它会改变 TCP 报头长度的 opt 试试？

**Comment by RPRX** [comment]
@5e2t 谢谢你的测试，不过 TFO 相当于加了一个变量，为了消除这个变量的影响，建议再找个 opt 验证一下

**Comment by RPRX** [comment]
@5e2t 好的，我转发一下，~~另外你可以试试分片在你那里好不好使~~

**Comment by RPRX** [comment]
> 根据延迟来判断，任何一个RST都不可能是河南的墙给我发的。

这倒不一定，延迟无法往小造假，但可以往大“造假”，目前看起来 RST 攻击是基于“实时的事后流量分析”，并不是完全的 in-path

所以如果它转到另一个设备的分析有一些时间成本，或故意拖延，就会造成“墙在边境出口”的假象

它可能是双向发 RST，你对时后测试一下 VPS 收到 RST 的时间，如果它非常接近边境出口到 VPS 的时间，则更可信一些

**Comment by RPRX** [comment]
@5e2t ~~写刚刚那条的时候还没看到你新发的消息~~，这样看来的确像是北上广边境出口的墙，~~而且我刚发现 VPS 测延迟的逻辑有误~~

**Comment by RPRX** [comment]
以及，至少说明了它没有故意拖延？~~除非它拉着 Client Hello 一起拖延~~，你看一下延迟正不正常（和 ping 相比）

**Comment by RPRX** [comment]
> @RPRX VPS的抓包和延迟已证明clienthello没有被拖延，clienthello未被拖延，证明VPS收到的RST未被拖延。

这也说明了它进行分析的时间成本并不高，第一个 RST 就 0.1ms，后三个 RST 是 0.9ms

~~当然还有一种可能是如果对任何包它都要先分析再放行，掩盖了一些时间成本~~

**Comment by RPRX** [comment]
@5e2t 我觉得你测出的 tlshello 分片对于河南 GFW 和北上广 GFW 的区别挺有意思的，因为分片后按常规解析实际上是不太行的，除非它采用了一些非常规的方式，~~比如不判断收完整没就硬上解析~~，这种风格很像你猜的它把 TCP 报头的长度给硬编码了

**Comment by RPRX** [comment]
@5e2t 对了，你那里不同的运营商写了不同的墙，你可以在数据流量网络上测一下 RST、分片等

话说你在 https://github.com/XTLS/Xray-core/issues/2426#issuecomment-1719685919 放的第一张图有点问题，协议套娃没带底层传输方式

此外有没有福建一些白名单地区的朋友按上面的方法测一下分片，~~不需服务器过墙还挺实用的~~

**Comment by testmemory** [comment]
河南联通，稳定复现本文所述情况。原由：外地工作，老家过节，到家发现Windows电脑使用v2rayN客户端无法连接，软路由和手机却稳定连接，抓包发现域名受到sni攻击。遂一路查资料到此处。    
上文描述的几乎每个细节都在我的设备上复现了，包括不同域名的rst报文数量、如有多个rst报文他们到达的延迟的区别、包内填充的`01 02 03 04 05 06 07 08 09 00`    
补充另外的一个细节，因个人原因，去往我域名的流量多数不在河南发出，而在我的工作城市的居住地每天都会产生数百GB的去往该域名的流量，仅有极少（可以肯定在每月MB级别）的流量从河南发出。而在年初过年时家中仍可正常连接，不理解河南的墙是如何把我的域名列入黑名单的。难不成是早就盯上我了，只是现在开始行动罢了。
另外，之前搭建时使用UDP协议使用同一主域名、同一证书做了一个备份，该链路由于更少的流量仍未受到封锁。

**Comment by DoyoDia** [comment]
我的域名进了黑名单之后连境内流量都会被RST重置，有什么建议可以判断RST包是从哪儿发的吗

**Comment by Fangliding** [comment]
> 号又没了，先不回去了。

https://github.com/XTLS/Xray-core/issues/3086

**Comment by HappyLeslieAlexander** [comment]
admin powershell 

netsh interface tcp set global timestamps=enabled

**Comment by HappyLeslieAlexander** [comment]
最好的方法就是用Reality，偷白名单域名

5e2t ***@***.***> 于
2024年5月27日周一 15:36写道：

**Comment by Fangliding** [comment]
转成discussion了 issues区会被机器人转发太刷屏了
