### ISSUE TITLE
使用VLESS-XTLS-uTLS-REALITY时网站不支持http2/3协议

### ISSUE THREAD

**Issue by do02fw** [XTLS/Xray-core#2427]
我在使用这个协议访问Google和YouTube时，通过浏览器抓包发现使用了http1.1协议，当我使用openvpn的udp协议访问Google和YouTube时，网站使用了http3协议，http3协议响应更快，有没有办法让VLESS-XTLS-uTLS-REALITY支持http2和http访问网站？

**Comment by Fangliding** [comment]
@do02fw h2是支持的 没有的话大概是你自己问题 h3不支持 因为浏览器的系统代理不支持过udp 而且h3过xray不见得比h2快

**Comment by do02fw** [comment]
有没有办法让它支持浏览器的HTTP3协议？

**Comment by chika0801** [comment]
你要想用 http3 ，客户端流控 `"flow": "xtls-rprx-vision-udp443"` 这样改

如果你还用到了

```
            "mux": {
                "enabled": true,
                "concurrency": -1,
                "xudpConcurrency": 16,
                "xudpProxyUDP443": "reject"
            },
```

改为 `"xudpProxyUDP443": "allow"`

**Comment by chika0801** [comment]
> 有没有办法让它支持浏览器的HTTP3协议？

windows下使用tun模式，比如用sing-box开tun,用socks传给xray入站

**Comment by chika0801** [comment]
另外建议你不要用QUIC （http3) 一般情况并不快

**Comment by do02fw** [comment]
> > 有没有办法让它支持浏览器的HTTP3协议？
> 
> windows下使用tun模式，比如用sing-box开tun,用socks传给xray入站
> 
> 参考 https://github.com/chika0801/Xray-install/tree/13d1e9ef9bd06e748083e41f3b2d2913b46ccb98/Tun

不适用TUN模式的话没法使用HTTP3吗？我打开v2rayNG的tun模式后并没有代理，不知道为什么，我代理设置的是不改变系统代理，然后TUN按钮是打开的，以管理员身份运行的，IP地址一查还是本机的IP地址不是服务器的IP

**Comment by mclovin-2k** [comment]
没有H3是因为XTLS默认屏蔽了443的UDP吧
没有H2是你自己的问题了

**Comment by chika0801** [comment]
> > > 有没有办法让它支持浏览器的HTTP3协议？
> > 
> > 
> > windows下使用tun模式，比如用sing-box开tun,用socks传给xray入站
> > 参考 https://github.com/chika0801/Xray-install/tree/13d1e9ef9bd06e748083e41f3b2d2913b46ccb98/Tun
> 
> 不适用TUN模式的话没法使用HTTP3吗？我打开v2rayNG的tun模式后并没有代理，不知道为什么，我代理设置的是不改变系统代理，然后TUN按钮是打开的，以管理员身份运行的，IP地址一查还是本机的IP地址不是服务器的IP

你如果用v2rayN的TUN模式，主要是做GUI客户端真是一言难尽，如果你没什么知识，软件作者也帮不了你。用tun需求一定基本知识，和自己排错能力。建议你参考上面发你的一个流程，因为那里把sing-box的tun模式配置都配好了，你有点基础会改下配置，就开箱即用。

**Comment by do02fw** [comment]
> > > > 有没有办法让它支持浏览器的HTTP3协议？
> > > 
> > > 
> > > windows下使用tun模式，比如用sing-box开tun,用socks传给xray入站
> > > 参考 https://github.com/chika0801/Xray-install/tree/13d1e9ef9bd06e748083e41f3b2d2913b46ccb98/Tun
> > 
> > 
> > 不适用TUN模式的话没法使用HTTP3吗？我打开v2rayNG的tun模式后并没有代理，不知道为什么，我代理设置的是不改变系统代理，然后TUN按钮是打开的，以管理员身份运行的，IP地址一查还是本机的IP地址不是服务器的IP
> 
> 你如果用v2rayN的TUN模式，主要是做GUI客户端真是一言难尽，如果你没什么知识，软件作者也帮不了你。用tun需求一定基本知识，和自己排错能力。建议你参考上面发你的一个流程，因为那里把sing-box的tun模式配置都配好了，你有点基础会改下配置，就开箱即用。

openvpn目前也没有被识别？openvpn我使用的是TLS1.3+UDP，算法是chacha20-poly1305+SHA512

**Comment by chika0801** [comment]
openvpn 你用久一点连出国，那一天只是早和晚来的问题

**Comment by do02fw** [comment]
> openvpn 连国外VPS，你用久一点，那一天只是早和晚来的问题

那openvpn的流量目前能识别出来吗？有没有特征？

**Comment by do02fw** [comment]
我用openvpn UDP协议能到600M的速度，香港

**Comment by do02fw** [comment]
> > 那openvpn的流量目前能识别出来吗？有没有特征？
> 
> 我认为能识别，能就自然有特征。
> 
> 不能的话，大家目前翻墙主流就用它了。谁开发其它协议了。这道理。

这是我测试的，看视频是http1.1，浏览网页http2
![3](https://github.com/XTLS/Xray-core/assets/138294823/934b6ffb-c553-4390-bbba-1b04acc6b55d)

**Comment by wy580477** [comment]
天啊，油管 CDN 要么 h3 要么 http 1.1，没有 h2 的。

现在代理协议对 udp 带宽都没有优化，h3 速度都跑不起来的，所以一般都是屏蔽 quic，强制用 http 1.1 了。

**Comment by do02fw** [comment]
> 天啊，油管视频 CDN 要么 h3 要么 http 1.1，没有 h2 的。
> 
> 现在代理协议对 udp 带宽都没有优化，h3 速度都跑不起来的，所以一般都是屏蔽 quic，强制用 http 1.1 了。

如何解除quic的屏蔽，这个tun模式真垃圾，开了没效果

**Comment by RPRX** [comment]
首先，VPN 协议的特征都很明显，且 GFW 已经能稳定封锁，所以人们不用 VPN
其次，QUIC over TCP 是 **DEBUFF**，遇上 XTLS 后者更无法发挥实质作用，所以 XTLS 默认把它禁了（以及浏览器代理并不支持它）
最后，加载视频走 H2 也是 **DEBUFF**，多条视频挤一条 TCP H2，吞吐量上得去吗？所以油管的设计是加载视频走 HTTP/1.1

所以根本没有问题，这些有啥想不通的，~~你以为有问题是因为只看到过这些协议的表面宣传，而没有实质性研究过它们的实现原理~~

**Comment by do02fw** [comment]
> 首先，VPN 协议的特征都很明显，且 GFW 已经能稳定封锁，所以人们不用 VPN 其次，QUIC over TCP 是 **DEBUFF**，遇上 XTLS 后者更无法发挥实质作用，所以 XTLS 默认把它禁了（以及浏览器代理并不支持它） 最后，加载视频走 H2 也是 **DEBUFF**，多条视频挤一条 TCP H2，吞吐量上得去吗？所以油管的设计是加载视频走 HTTP/1.1
> 
> 所以根本没有问题，这些有啥想不通的，~你以为有问题是因为只看到过这些协议的表面宣传，而没有实质性研究过它们的实现原理~

主要我还是想要那种能代理全部流量的，希望xtls以后可以支持

**Comment by chika0801** [comment]
白话解释：可以代理quic，用了你不会感觉到快，比如小白喜欢秀的ytb跑分

**Comment by do02fw** [comment]
> 白话解释：可以代理quic，用了你不会感觉到快，比如小白喜欢秀的ytb跑分
> 
> 官话见这个解释写得挺好
> 
> https://hysteria.network/zh/docs/about-http3/

不是的，我用openvpn＋udp协议，YouTube能到20万，而且是http/3，wireguard也可以到20万，但是wireguard在ipv4环境下容易封。

**Comment by do02fw** [comment]
我希望能推出全局代理的协议，抛弃socket协议，比如魔改wireguard或者openvpn，socket不能代理所有流量，玩游戏时需要icmp协议和udp，如果udp 转tcp会增加延迟，udp对udp是最快的。
