### ISSUE TITLE
xray在linux与windows中运行结果不一致

### ISSUE THREAD

**Issue by 91he** [XTLS/Xray-core#2429]
版本：v1.8.3
配置：xtls-rprx-vision + tcp + tls 无伪装
现象：相同的代码，编译成linux版本运行正常，编译成exe则代理异常。（通过windows版本的xray socks5代理则超时，通过wsl2下linux版本socks5代理则正常。）
运行环境：linux为wsl2，windows为win11
复现方式：设置chrome浏览器代理为xray的sock5，打开google
补充说明：此问题主要影响了通过浏览器访问google，对其它网站的影响似乎较小。

**Comment by RPRX** [comment]
检查配置

**Comment by 91he** [comment]
> 检查配置
@RPRX 2者使用了同一份配置文件
