### ISSUE TITLE
分流到Lnmp1.7环境下的动态wordpress网站网页乱码

### ISSUE THREAD

**Issue by man2018** [XTLS/Xray-core#243]
各位大佬，希望能替我解决下，实在找不到解决思路了。

目前使用nginx sni域名分流来使用xray，翻墙是正常的。翻墙域名是v.xxx.com ，目前要解决的问题是输入https://v.xxx.com网页正常显示，而不是乱码。

以下是nginx配置
`server
    {
        listen 127.0.0.1:82;
        #listen [::]:443 ssl http2;
        server_name v.xxx.com;
        index index.html index.htm index.php default.html default.htm default.php;
        root  /home/wwwroot/www.xxx.com;

        #ssl_certificate /usr/local/nginx/conf/ssl/xxx.com/fullchain.cer;
        #ssl_certificate_key /usr/local/nginx/conf/ssl/xxx.com/xxx.com.key;
        #ssl_session_timeout 5m;
        #ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        #ssl_prefer_server_ciphers on;
        #ssl_ciphers "TLS13-AES-256-GCM-SHA384:TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-128-GCM-SHA256:TLS13-AES-128-CCM-8-SHA256:TLS13-AES-128-CCM-SHA256:EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5";
        #ssl_session_cache builtin:1000 shared:SSL:10m;
        ## openssl dhparam -out /usr/local/nginx/conf/ssl/dhparam.pem 2048
        #ssl_dhparam /usr/local/nginx/conf/ssl/dhparam.pem;

        include rewrite/none.conf;
        #error_page   404   /404.html;

        # Deny access to PHP files in specific directory
        #location ~ /(wp-content|uploads|wp-includes|images)/.*\.php$ { deny all; }

        include enable-php.conf;

        location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
        {
            expires      30d;
        }

        location ~ .*\.(js|css)?$
        {
            expires      12h;
        }

        location ~ /.well-known {
            allow all;
        }

        location ~ /\.
        {
            deny all;
        }

        access_log  /home/wwwlogs/www.xxx.com.log;
    }`
目前输入www.xxx.com网站是正常的，此域名的https也是正常的

**Comment by AkinoKaede** [comment]
我想这应该是由编码引起的问题，应该在 meta 标签中配置正确的编码

**Comment by man2018** [comment]
> 我想这应该是由编码引起的问题，应该在 meta 标签中配置正确的编码

如果不用xray来设置证书就没有样式乱码

**Comment by i553041** [comment]
> > 我想这应该是由编码引起的问题，应该在 meta 标签中配置正确的编码
> 
> 如果不用xray来设置证书就没有样式乱码

我朋友也遇到一模一樣的問題，他也是用LNMP，我還以為這個issue是他開的，我自己沒用LNMP，但我有幫他研究過，我用LNMP本來的虛擬主機配置也攪不定，我用自己的配置，都研究了很久，不過最終都攪定了，你參考一下，首先xray這樣配置回落：

```
"fallbacks": [
          {
            "alpn": "h2",
            "dest": 8083,
            "xver": 2
          },
          {
            "dest": 8082,
            "xver": 2
          }
        ]
```

nginx的虛擬主機配置如下(這是我自己的配置，不關LNMP的事)：

```
server {
    listen 80;
    listen [::]:80;
    server_name wp.abc.com;
    return 301 https://wp.abc.com$request_uri;
}

server {
        listen 8082 proxy_protocol;
        listen [::]:8082 proxy_protocol;
        listen 8083 proxy_protocol http2;
        listen [::]:8083 proxy_protocol http2;
     server_name wp.abc.com;
     error_page 404 /404.html;
     error_page 400 /404.html;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    root   /var/www/wp.abc.com/;
     index index.html index.php;
     keepalive_timeout   70;
     ssl_protocols TLSv1.2 TLSv1.3;
     ssl_certificate /etc/v2ray/ecc384.crt;
     ssl_certificate_key /etc/v2ray/ecc384.key;
     ssl_ecdh_curve secp384r1;
     ssl_prefer_server_ciphers on;
     ssl_session_cache   shared:SSL:10m;
     ssl_session_timeout 10m;
     ssl_session_tickets on;
     ssl_stapling on;
     ssl_stapling_verify on;
     ssl_trusted_certificate  /etc/v2ray/new-miniserv.pem;
     ssl_dhparam /etc/nginx/ssl/dhparam.pem;
     gzip on;
     fastcgi_read_timeout 360;
     client_max_body_size 2000M;
        location /1/ {
        autoindex               on; 
        autoindex_exact_size    off; 
        autoindex_localtime     on; 
        }
location = /404.html {
        root /var/www/wp.abc.com/;
}

location ~ \.php$ {
        set $php_root /var/www/wp.abc.com;
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        fastcgi_param HTTPS "on";
        fastcgi_param PHP_VALUE "max_execution_time=1800
                                post_max_size=1500M
                                upload_max_filesize=32M
                                max_input_time=1800
                                max_file_uploads=300";
    }
}
```

在自己和朋友的機器上實測，只要加上這一句：

fastcgi_param HTTPS "on";

就不再走位了，至於為甚麼也不知道，但不加上那一句的話WP會走位，加了就沒事了。

**Comment by man2018** [comment]
> > > 我想这应该是由编码引起的问题，应该在 meta 标签中配置正确的编码
> > 
> > 
> > 如果不用xray来设置证书就没有样式乱码
> 
> 我朋友也遇到一模一樣的問題，他也是用LNMP，我還以為這個issue是他開的，我自己沒用LNMP，但我有幫他研究過，我用LNMP本來的虛擬主機配置也攪不定，我用自己的配置，都研究了很久，不過最終都攪定了，你參考一下，首先xray這樣配置回落：
> 
> ```
> "fallbacks": [
>           {
>             "alpn": "h2",
>             "dest": 8083,
>             "xver": 0
>           },
>           {
>             "dest": 8082,
>             "xver": 0
>           }
>         ]
> ```
> 
> nginx的虛擬主機配置如下(這是我自己的配置，不關LNMP的事)：
> 
> ```
> server {
>     listen 80;
>     listen [::]:80;
>     server_name wp.abc.com;
>     return 301 https://wp.abc.com$request_uri;
> }
> 
> server {
>         listen 8082 ;
>         listen [::]:8082 ;
>         listen 8083 http2;
>         listen [::]:8083 http2;
>      server_name wp.abc.com;
>      error_page 404 /404.html;
>      error_page 400 /404.html;
>     add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
>     root   /var/www/wp.abc.com/;
>      index index.html index.php;
>      keepalive_timeout   70;
>      ssl_protocols TLSv1.2 TLSv1.3;
>      ssl_certificate /etc/v2ray/ecc384.crt;
>      ssl_certificate_key /etc/v2ray/ecc384.key;
>      ssl_ecdh_curve secp384r1;
>      ssl_prefer_server_ciphers on;
>      ssl_session_cache   shared:SSL:10m;
>      ssl_session_timeout 10m;
>      ssl_session_tickets on;
>      ssl_stapling on;
>      ssl_stapling_verify on;
>      ssl_trusted_certificate  /etc/v2ray/new-miniserv.pem;
>      ssl_dhparam /etc/nginx/ssl/dhparam.pem;
>      gzip on;
>      fastcgi_read_timeout 360;
>      client_max_body_size 2000M;
>         location /1/ {
>         autoindex               on; 
>         autoindex_exact_size    off; 
>         autoindex_localtime     on; 
>         }
> location = /404.html {
>         root /var/www/wp.abc.com/;
> }
> 
> location ~ \.php$ {
>         set $php_root /var/www/wp.abc.com;
>         include snippets/fastcgi-php.conf;
>         fastcgi_pass unix:/run/php/php7.4-fpm.sock;
>         fastcgi_param HTTPS "on";
>         fastcgi_param PHP_VALUE "max_execution_time=1800
>                                 post_max_size=1500M
>                                 upload_max_filesize=32M
>                                 max_input_time=1800
>                                 max_file_uploads=300";
>     }
> }
> ```
> 
> 在自己和朋友的機器上實測，只要加上這一句：
> 
> fastcgi_param HTTPS "on";
> 
> 就不再走位了，至於為甚麼加了會沒事我也不知道，但不加上那一句的話WP就會走位。

谢谢大哥 我解决了 哈哈

**Comment by rprx** [comment]
WordPress 放回落后似乎容易出现样式问题，这个解决方案可以加入文档。
