### ISSUE TITLE
V2ray的流量可以被防火墙检测了

### ISSUE THREAD

**Issue by do02fw** [XTLS/Xray-core#2433]
刚刚在哔哩哔哩刷到的视频，这个视频是防火墙的演示视频，其中就识别了v2ray的流量，而且发现了伪装域名和真实域名IP不匹配，希望大家可以看一下，目前的防火墙已经可以识别出目标域名和目标IP不匹配的能力，这代表着偷证书也没用，可以匹配域名的IP。
【一分钟快速发现“网络穿透”行为-哔哩哔哩】 https://www.bilibili.com/video/BV1eu411H7Cr
![Screenshot_20230811_014746](https://github.com/XTLS/Xray-core/assets/138294823/1c274a40-5633-4875-b16c-abe571b474bf)
![Screenshot_20230811_014737](https://github.com/XTLS/Xray-core/assets/138294823/2cb6c0da-ccf9-4431-b9d2-156aa502af95)

**Comment by RPRX** [comment]
1. "25600"
2. "V2ray"
3. nice try，下次别发国内链接了

**Comment by do02fw** [comment]
> 1. "25600"
> 2. "V2ray"
> 3. nice try，下次别发国内链接了

但是我看它别的也可以识别。不只是v2ray

**Comment by chika0801** [comment]
建议你可去b站私信up主，告诉他本项目，或问问他

**Comment by do02fw** [comment]
> 建议你可去b站私信up主，告诉他本项目，或问问他

 我怀疑它是内鬼
