### ISSUE TITLE
xray config path match error

### ISSUE THREAD

**Issue by Emersonksc** [XTLS/Xray-core#244]
system: win10
xray version: 1.23

**first, i followed the default convention. in official document,it says as follow:**
![image](https://user-images.githubusercontent.com/48752001/107668968-3a2ba880-6ccc-11eb-8960-3cf04d5c50e9.png)
**so i put my config file in the same directory as follow:**
![image](https://user-images.githubusercontent.com/48752001/107669636-e5d4f880-6ccc-11eb-9765-d38a1ebb9750.png)
**but when i ran xray , i got information like this:**
![image](https://user-images.githubusercontent.com/48752001/107669937-38aeb000-6ccd-11eb-8e3a-d6d2b6599ca1.png)
**so i used the command xray run -c [config path] but it didn't work**
![image](https://user-images.githubusercontent.com/48752001/107670525-ca1e2200-6ccd-11eb-9c0f-916c48b25fde.png)
**i really confused by this , was there something i ignore or it just a bug?**

**i will appreciate if anyone can help me with this problem**

**Comment by jiuqi9997** [comment]
Try `xray run -config [path]`

**Comment by soffchen** [comment]
```xray run -c "D:\Program Files....config.json"```

路径有空格，头尾加引号

**Comment by Emersonksc** [comment]
thinks

**Comment by Emersonksc** [comment]
it didn't work
![image](https://user-images.githubusercontent.com/48752001/107721455-a54e9c80-6d17-11eb-864a-f0fa08b9586d.png)

**Comment by dongjuanyong** [comment]
看图标莫不是.txt的扩展名没去掉？

**Comment by Emersonksc** [comment]
i got it , the windows hide the extension in default. so when i change the extension ,it didn't work 
i have fixed it ,now everything is ok

thinks for you guys
