### ISSUE TITLE
求教:关于vless+tcp(http伪装),无法回落的问题

### ISSUE THREAD

**Issue by 189er** [XTLS/Xray-core#2440]
我的配置文件(xray-core v1.7.5):

> {
>     "log": {"loglevel": "debug"},
>     "inbounds": [
>         {
>             "port": 58080,
>             "protocol": "vless",
>             "settings": {
>                 "clients": [  {  "id": "466eb1fe-6943-4935-b893-9e8adb3c6b12"}],
>                 "decryption": "none",
>                 "fallbacks": [  {  "dest": 60080 }  ]
>             },
>             "streamSettings": 
>             {
>                   "network": "tcp",
>                   "security": "none",
>                   "tcpSettings": {
>                     "acceptProxyProtocol": false,
>                     "header": {
>                                     "type": "http",
>                                     "request": {
>                                                 "path": [ "/vtcp58080"],
>                                                 "version": "1.1",
>                                                 "headers":{
>                                                     "Host": ["xxx.xiaomiqiu123.top"]
>                                                     }
>                                                 },
>                                     "response": {}
>                                     }
>                 }
>             }
>         } 
>     ], "outbounds": [ { "protocol": "freedom" }  ]
> }

使用这个命令tcpdump -i any -s0 -w aa.pcap tcp port 60080  ,发现只有tcp  syn和ack的包,没有push的包,不知道为啥?

日志提示如下:

> 2023/08/13 12:52:11 [Warning] core: Xray 1.7.5 started                                                                                   
> 2023/08/13 12:56:21 [Info] [1450547822] proxy/vless/inbound: firstLen = 0                                                                
> 2023/08/13 12:56:21 [Info] [1450547822] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly                    
> 2023/08/13 12:56:25 [Info] [1450547822] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > context canceled    
> 2023/08/13 12:58:25 [Info] [274667614] proxy/vless/inbound: firstLen = 0                                                                 
> 2023/08/13 12:58:25 [Info] [274667614] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly                     
> 2023/08/13 12:58:37 [Info] [274667614] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > context canceled

**Comment by Fangliding** [comment]
回落需要开启tls
