### ISSUE TITLE
建议加入fake dns功能

### ISSUE THREAD

**Issue by bestmikecat** [XTLS/Xray-core#245]
在Kitsunebi上有这个功能，v2rayng没有，能不能把这个功能集成到xray内核中？感觉fake dns挺好用的.

**Comment by AkinoKaede** [comment]
未来可能会从 v2fly/v2ray-core 中合并相关提交

**Comment by rprx** [comment]
去年十月底我开了很多 Welcome PR，详见：https://github.com/v2fly/v2ray-core/issues?q=is%3Aissue+author%3Arprx+

其中这个 issue 已被完成：[v2ray 应加入 Fake IP、代理组等实用性功能 #377](https://github.com/v2fly/v2ray-core/issues/377)

[Fake DNS with full V2 intergration #406](https://github.com/v2fly/v2ray-core/pull/406)

[v5: Health Check & LeastLoad Strategy #589](https://github.com/v2fly/v2ray-core/pull/589)

**所以 fake dns 功能肯定会加**，Xray-core 之前没做 fake dns 也是因为 v2fly 那边在做了，没有必要重复造轮子。

https://github.com/v2fly/v2ray-core/pull/406 的时间跨度很长（去年分裂期间就写好了，近期才被合并），v2fly-core v4.35.0 没问题的话会 merge 过来。

**Comment by rurirei** [comment]
v2fly/v2ray-core#406 ok on my Windows, Linux, and Android.

**Comment by rprx** [comment]
https://github.com/XTLS/Xray-core/commit/f50eff5ebb9edfb8016002663921c7a779d5bec7
https://github.com/XTLS/Xray-core/commit/d7cd71b74195a64b6617b6f0abc27fb2f8e5102d
