### ISSUE TITLE
疑似内存泄露

### ISSUE THREAD

**Issue by Karmylr** [XTLS/Xray-core#2452]
在OpenWrt上用xray-core来科学上网。突然断网了：
![image](https://github.com/XTLS/Xray-core/assets/69903376/28949fd5-69e5-4cfa-9d37-2441419a2ec2)
重启之后因为自动启动xray-core而再次卡死：
![image](https://github.com/XTLS/Xray-core/assets/69903376/88afbb83-2b32-4f1c-9ba4-198a5e4785ec)

有没有类似clash.meta的pprof工具来检查占用情况？

**Comment by zhuxining** [comment]
用的 mack-a 大佬的脚本，启动后内存会逐步增加，服务停止重启恢复，循环往复

![image](https://github.com/XTLS/Xray-core/assets/12285468/76e1cd38-42e8-4d1f-b900-d1cfea8f0a02)

Linux iZt4ngf0ay8xbyx4fn6e3qZ 6.6.0-14-generic #14-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 30 10:27:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Fangliding** [comment]
无配置无日志
