### ISSUE TITLE
路由规则详情设置里面不能添加中文信息吗？ 我想给网址添加备注

### ISSUE THREAD

**Issue by Emilia66666** [XTLS/Xray-core#2455]
启动服务(2023/8/12 9:46:13)...
Xray 1.8.0 (Xray, Penetrates Everything.) Custom (go1.20.2 windows/amd64)
2023/08/12 09:46:13 Using default config: C:\ChangYon\v2rayN\guiConfigs\config.json
A unified platform for anti-censorship.
2023/08/12 09:46:13 [Info] infra/conf/serial: Reading config: C:\ChangYon\v2rayN\guiConfigs\config.json
panic: runtime error: index out of range [138] with length 127
goroutine 1 [running]:
github.com/xtls/xray-core/common/strmatcher.(*ACAutomaton).Add(0xc0035c6960, {0xc00070ace0, 0x1e42?}, 0x1)
github.com/xtls/xray-core/common/strmatcher/ac_automaton_matcher.go:138 +0x685
github.com/xtls/xray-core/common/strmatcher.(*MphMatcherGroup).AddPattern(0xc0009dce10, {0xc00070ace0?, 0x0?}, 0x1)
github.com/xtls/xray-core/common/strmatcher/mph_matcher.go:72 +0x28b
github.com/xtls/xray-core/app/router.NewMphMatcherGroup({0xc00022f4d0, 0x2, 0xc000680000?})
github.com/xtls/xray-core/app/router/condition.go:75 +0x13b
github.com/xtls/xray-core/app/router.(*RoutingRule).BuildCondition(0xc0002511e0)
github.com/xtls/xray-core/app/router/config.go:80 +0x2cb
github.com/xtls/xray-core/app/router.(*Router).Init(0xc000219500, {0x16871c0, 0xc000098360}, 0xc0009d67e0, {0x210f068f9a0?, 0x1f5a1d8?}, {0x210ca5d9cf8?, 0xc0009de500})
github.com/xtls/xray-core/app/router/router.go:48 +0x445
github.com/xtls/xray-core/app/router.init.1.func1.1({0x210f068f9a0?, 0x1f5a1d8?}, {0x210ca5d9cf8?, 0xc0009de500?})
github.com/xtls/xray-core/app/router/router.go:144 +0x6f
reflect.Value.call({0x12ce2e0?, 0xc000098390?, 0x66f8f6?}, {0x14b50ba, 0x4}, {0xc000098570, 0x2, 0x2?})
reflect/value.go:586 +0xb07
reflect.Value.Call({0x12ce2e0?, 0xc000098390?, 0x138c680?}, {0xc000098570?, 0x14ad860?, 0x20?})
reflect/value.go:370 +0xbc
github.com/xtls/xray-core/core.(*resolution).resolve(0xc000595b00, {0xc00048d300, 0x9, 0x10})
github.com/xtls/xray-core/core/xray.go:74 +0x513
github.com/xtls/xray-core/core.(*Instance).AddFeature(0xc0009de460, {0x1684930?, 0x1f5a1d8?})
github.com/xtls/xray-core/core/xray.go:315 +0x2b6
github.com/xtls/xray-core/core.initInstanceWithConfig(0xc000287dd0, 0xc0009de460)
github.com/xtls/xray-core/core/xray.go:221 +0x413
github.com/xtls/xray-core/core.New(0x14b53d2?)
github.com/xtls/xray-core/core/xray.go:164 +0x77
main.startXray()
github.com/xtls/xray-core/main/run.go:190 +0x228
main.executeRun(0x1eefe00?, {0xc000079690?, 0x20?, 0x12a2300?})
github.com/xtls/xray-core/main/run.go:65 +0x45
github.com/xtls/xray-core/main/commands/base.Execute()
github.com/xtls/xray-core/main/commands/base/execute.go:64 +0x636
main.main()
github.com/xtls/xray-core/main/main.go:22 +0x1aa
Cannot mix synchronous and asynchronous operation on process stream.
2023/8/12 9:46:13 系统代理设置改变
2023/8/12 9:46:15 当前服务的真连接延迟: -1 ms

**Comment by Hisir0909** [comment]
应该是json不能加注释的限制把

**Comment by Fangliding** [comment]
不能写注释（绝望）

**Comment by KoinuDayo** [comment]
> > xray的json支持注释的，然后你是v2raym的话得用
> > 
> > ```js
> > /*注释内容*/
> > ```
> > 
> > 这样注释，不然配置内容后面的部分也会被注释掉，导致出错
> 
> v2 5.39版本好像是直接可以输入中文的 

v6是重构过的，跨大版本应该是不兼容
