### ISSUE TITLE
(配合cloudflare下)大家有成功使用假host的没？ 能否分享下配置。

### ISSUE THREAD

**Issue by insoxin** [XTLS/Xray-core#246]
目的免流host伪装

WebSocket+TLS+nginx与Cloudflare CDN梯子，伪装域名(host)的功能无法使用

将客户端中的伪装域名(host)设置成自己的域名www.myhostxxxx.top或者不设置，能够联网。
将其设置成伪装的，比如www.ted.com或者www.youku.com之类的，无法联网

**Comment by GleenJi** [comment]
这个问题之前v2ray就有过，因为host涉及到websocket host和tls servername，不填的话如果address是域名则自动应用到websocket host和tls servername，如果address是指定ip，那么你的websocket host和tls servername需要填你的域名,你填其他的比如baidu.com，youku.com肯定不行啊

**Comment by LearZhou** [comment]
websocket host具体该怎么设置？
        "wsSettings": {
          "host": "your domain",
          "path": "/your path"
        },
这个不好使。搜索了一下，也没查到具体该怎么做才能自选ip。

**Comment by i553041** [comment]
> 目的免流host伪装
> 
> WebSocket+TLS+nginx与Cloudflare CDN梯子，伪装域名(host)的功能无法使用
> 
> 将客户端中的伪装域名(host)设置成自己的域名www.myhostxxxx.top或者不设置，能够联网。
> 将其设置成伪装的，比如www.ted.com或者www.youku.com之类的，无法联网

不理解為何要設置偽裝域名，如果牆有這種檢測功能，檢測你的域名/IP時，發現你的域名/IP，偽裝成youku.com而且網站內容也是youku的，那不就是此地無銀三百兩，一個超級明顯的特徵嗎？

ws+tls+nginx的話，只需一台服務器加一個功能正常的偽裝網站已經足夠了吧？至少這種配置我自己就運行了接近2年了，(19年5月開始運行到現在)，而且我還沒套CDN都沒有被封，你是套了CF CDN的，更加應該比我更安全，個人認為根本不需要使用甚麼偽裝域名，有點畫蛇添足，多此一舉。

ws+tls+nginx，就是要從外面看來，數據是完全的https，令牆以為是普通https而不加攔截，攪些甚麼偽裝域名除了有可能增加特徵外，實在不知道有甚麼用，個人認為真的不需要。

**Comment by GleenJi** [comment]
> 
> 
> 目的免流host伪装
> 
> WebSocket+TLS+nginx与Cloudflare CDN梯子，伪装域名(host)的功能无法使用
> 
> 将客户端中的伪装域名(host)设置成自己的域名www.myhostxxxx.top或者不设置，能够联网。
> 将其设置成伪装的，比如www.ted.com或者www.youku.com之类的，无法联网

你搜索sni是什么就知道了，我也是小白，你的疑问再了解sni后应该就明白了

**Comment by GleenJi** [comment]
> 
> 
> websocket host具体该怎么设置？
> 
> ```
>         "wsSettings": {
>           "host": "your domain",
>           "path": "/your path"
>         },
> ```
> 
> 这个不好使。搜索了一下，也没查到具体该怎么做才能自选ip。

address填cf的ip，websocket host和tls servername填写你的域名

**Comment by Tiamisu** [comment]
你想做的和域名前置有些类似，即tls连接的时候sni是一个域名，真正传输的时候又是另一个域名。但现在cloudflare已经ban了域名前置。

**Comment by AkinoKaede** [comment]
此题无解，CloudFlare 会验证使用者身份
