### ISSUE TITLE
Xray stop working if testing the VMESS  config that miss configured.

### ISSUE THREAD

**Issue by M450ud** [XTLS/Xray-core#2460]
If you use Xray for vmess config's which the 'Path' parameter is only '/' char the app will stop working and go to panic mode (according to the log). also, the latest version has the bug.
the bug cause problem when checking a list; the user must find the buggy config by checking it one by one.

**Comment by M450ud** [comment]
this is a sample config:
vmess://eyJhZGQiOiI5NC4xNTQuMTU3LjEwMCIsImFpZCI6IjAiLCJob3N0IjoiIiwiaWQiOiI0YTc1YzNiYS1mMmU5LTExZWQtYmYxYi1mMjNjOTEzNjlmMmQiLCJuZXQiOiJ3cyIsInBhdGgiOiIvIiwicG9ydCI6IjgwIiwicHMiOiLwn4es8J+Hp0dCIiwic2N5IjoiYXV0byIsInNuaSI6IiIsInRscyI6IiIsInR5cGUiOiIiLCJ2IjoiMiJ9

and log :

panic: runtime error: slice bounds out of range [1:0]
goroutine 1878 [running]:
github.com/xtls/xray-core/transport/internet/grpc.(*Config).getServiceName(0xc0003d4c40)
	github.com/xtls/xray-core@v1.0.0/transport/internet/grpc/config.go:25 +0x15e
github.com/xtls/xray-core/transport/internet/grpc.dialgRPC({0x11a4d60, 0xc001355050}, {{0x11a61b8?, 0xc0007481e8?}, 0x2?, 0x0?}, 0xd229a7?)
	github.com/xtls/xray-core@v1.0.0/transport/internet/grpc/dial.go:65 +0x4d5
github.com/xtls/xray-core/transport/internet/grpc.Dial({0x11a4d60, 0xc001355050}, {{0x11a61b8, 0xc0007481e8}, 0x823, 0x2}, 0xc001354fc0?)
	github.com/xtls/xray-core@v1.0.0/transport/internet/grpc/dial.go:27 +0x18d
github.com/xtls/xray-core/transport/internet.Dial({0x11a4d60, 0xc001355050}, {{0x11a61b8?, 0xc0007481e8?}, 0x81e8?, 0xc0?}, 0x6?)
	github.com/xtls/xray-core@v1.0.0/transport/internet/dialer.go:58 +0x1ef
github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dial
(
0xc000ce0080
,
{0x11a4d60
?,
0xc001355050?}, {{0x11a61b8, 0xc0007481e8}, 0x823, 0x2})
	github.com/xtls/xray-core@v1.0.0/app/proxyman/outbound/handler.go:310 +0xad7
github.com/xtls/xray-core/proxy/vmess/outbound.(*Handler).Process.func1()
	github.com/xtls/xray-core@v1.0.0/proxy/vmess/outbound/outbound.go:68 +0xa3
github.com/xtls/xray-core/common/retry.(*retryer).On(0xc001021c68, 0xc001021cd0)
	github.com/xtls/xray-core@v1.0.0/common/retry/retry.go:27 +0xdb
github.com/xtls/xray-core/proxy/vmess/outbound.(*Handler).Process(0xc0013546c0, {0x11a4d60, 0xc001355050}, 0xc000f9a2e0, {0x119d060, 0xc000ce0080})
	github.com/xtls/xray-core@v1.0.0/proxy/vmess/outbound/outbound.go:66 +0x1ee
github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dispatch(0xc000ce0080, {0x11a4d60, 0xc001355050}, 0xc000f9a2e0)
	github.com/xtls/xray-core@v1.0.0/app/proxyman/outbound/handler.go:240 +0x75f
github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc000d3f860, {0x11a4d60, 0xc001355050}, 0xc000f9a2e0, {{0x11a6180, 0xc000234a50}, 0x1bb, 0x2})
	github.com/xtls/xray-core@v1.0.0/app/dispatcher/default.go:490 +0xbfe
created by github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch
	github.com/xtls/xray-core@v1.0.0/app/dispatcher/default.go:302 +0x4ea
[Error] Core exited, restarting.

**Comment by benjaminyin01** [comment]
不是vless更好吗 怎么还有用vmess的
