### ISSUE TITLE
Socks5 udp Mobile proxy

### ISSUE THREAD

**Issue by bannyhm** [XTLS/Xray-core#2467]
I ask for help in setting up. What should be my XRAY Server (Windows PC) and Xray Client (Mobile Phone) settings so that the user can visit sites with the Xray Client (Mobile Phone) ip address and UDP support by proxy? The client IP is constantly changing.
![Sheme socks](https://github.com/XTLS/Xray-core/assets/72357001/2b3ac980-49e2-4f40-ab15-56fc9405c38f)

**Comment by chika0801** [comment]
I looked at your schematic pictures. First of all, what method are you using, to share your cell phone's network, to your computer (PC)?

I haven't tried connecting the phone with a data cable, and the phone turns on network sharing to the computer (PC), as I recall at this point a virtual NIC is created on the computer for the purpose of sharing the phone's network. At this point the PC should be accessing the internet through the phone's 4G network.

So I think at this time the computer (PC) is a server, according to the general situation, running Xray on this computer is to use the server configuration.

**Comment by bannyhm** [comment]
Thanks for responding to my problem. I'm just getting started with this. Now I'm trying to use something like this configuration, server:
{
   "outbounds": [
     {
       "protocol": "freedom"
     }
   ],
   "inbounds": [
     {
       "protocol": "socks",
       "settings": {},
       "port": 6410,
       "tag": "inbound-6410"
     }
   ],
   "outbounds": [
{"protocol": "socks",
"tag": "outbound-6410",
"settings": {
"servers": [{"address": "prmi9t.duckdns.org", "port": 6410}]
}
}]
  
   }
}

Client:
{
   "outbounds": [
     {
       "protocol": "freedom"
     }
   ],
   "inbounds": [
     {
       "protocol": "socks",
       "settings": {},
       "port": 6410,
       "tag": "inbound-6410"
     }
   ],
   "routing": {
     "rules": [
       {
         "type": "field",
         "inboundTag": ["inbound-6410"],
         "outboundTag": "outbound-6410"
       }
     ]
   },
   "outbound": {
     "protocol": "socks",
     "settings": {
       "servers": [
         {
           "address": "188.xxx.54.xx",
           "port": 6410,
           "users": [
             {
               "user": "user",
               "pass": "user"
             }
           ]
         }
       ]
     },
     "tag": "outbound-6410"
   }
}.
My phones are far away from the server and are not wired to it. I was able to set up such a scheme with FRP, but their Socks5 plugin doesn't support UDP

**Comment by chika0801** [comment]
```
    "inbounds": [
        {
            "listen": "127.0.0.1",
            "port": 10808,
            "protocol": "socks",
            "settings": {
                "udp": true
            }
        }
    ],
```

When your PC computer as a server, if the inbound protocol is scoks protocol, you need to add the following parameter in the configuration to make socks support udp protocol. You can check the parameter description in Xray's documentation.

```
            "settings": {
                "udp": true
            }
```

**Comment by bannyhm** [comment]
Can I agree with you for payment to set up the connection scheme I need?

**Comment by bannyhm** [comment]
I'm very bad at this topic. The mobile phones I use in my scheme change ip address every 10 minutes

**Comment by bannyhm** [comment]
I tried to set up an FRP tunnel and included in this scheme on the client SocksServerUltimate.apk - it works. But when I try to replace in this scheme SocksServerUltimate.apk with XRAY with settings



{ 
  "log": {
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": 6412,
      "protocol": "socks",
      "settings": {
        "auth": "password",
        "accounts": [
          {
            "user": "user",
            "pass": "user"
          }
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom"
    }
  ]
}



, in XRAY logs I get

Xray 1.8.3 (Xray, Penetrates Everything.) Custom (go1.20.5 linux/arm64) 
A unified platform for anti-censorship.
2023/08/23 19:27:07 [Info] infra/conf/serial: Reading config: ./xray-client.json 
2023/08/23 19:27:07 [Warning] core: Xray 1.8.3 started
2023/08/23 19:27:49 tcp:127.0.0.1:37484 accepted tcp:chek.zennolab.com:80
2023/08/23 19:30:26 tcp:127.0.0.1:37488 accepted tcp:ip.bablosoft.com:80
2023/08/23 19:30:27 tcp:127.0.0.1:37490 accepted tcp:ip1.bablosoft.com:443
2023/08/23 19:30:34 tcp:127.0.0.1:37492 accepted tcp:optimizationguide-pa.googleapis.com:443
2023/08/23 19:30:34 tcp:127.0.0.1:37494 accepted tcp:optimizationguide-pa.googleapis.com:443
2023/08/23 19:30:35 tcp:127.0.0.1:37496 accepted tcp:optimizationguide-pa.googleapis.com:443
2023/08/23 19:30:36 tcp:127.0.0.1:37498 accepted tcp:optimizationguide-pa.googleapis.com:443

As a result, I get no positive response when sending resource requests
Please help me find my mistake.

**Comment by bannyhm** [comment]
> ```
>     "inbounds": [
>         {
>             "listen": "127.0.0.1",
>             "port": 10808,
>             "protocol": "socks",
>             "settings": {
>                 "udp": true
>             }
>         }
>     ],
> ```
> 
> When your PC computer as a server, if the inbound protocol is scoks protocol, you need to add the following parameter in the configuration to make socks support udp protocol. You can check the parameter description in Xray's documentation.
> 
> ```
>             "settings": {
>                 "udp": true
>             }
> ```
> 
> > My phones are far away from the server and are not wired to it. I was able to set up such a scheme with FRP, but their Socks5 plugin doesn't support UDP
> 
> Regarding your PC computer connecting to your phone, use FRP or some other method (e.g. you can also use Xray to establish a connection, or a tunneling type program like type gost, or use port forwarding). The methods are many.
> 
> I see that in both the server-side and client-side configurations you posted, the outbound section says 2, which is incorrect, the outbound is 1 section and can have different outbound configurations.

Hello. I am studying and experimenting with the settings. Tell me why when running Socks5 on an android client, together with an frp tunnel with this configuration:

{
  "log": {
    "loglevel": "debug"
  },
  "inbounds": [
    {
      "port": 6395,
      "protocol": "socks",
      "settings": {
        "auth": "password",
        "accounts": [
          {
            "user": "user",
            "pass": "user"
          }
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom"
    },
    {
      "protocol": "dns",
      "settings": {
        "servers": [
          {
            "address": "[8.8.8.8](https://8.8.8.8/)",
            "port": 53,
            "domains": ["."]
          }
        ]
      }
    }
  ]
}

I get an error:
./xray -c ./client.json                       Xray 1.8.4 (Xray, Penetrates Everything.) Custom (go1.21.0 linux/arm)                               A unified platform for anti-censorship.           2023/08/31 11:09:28 [Info] infra/conf/serial: Reading config: ./client.json                         2023/08/31 11:09:28 [Debug] app/log: Logger started
2023/08/31 11:09:28 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:6395            2023/08/31 11:09:28 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:6395                    2023/08/31 11:09:28 [Warning] core: Xray 1.8.4 started
2023/08/31 11:09:39 [Info] [4019650842] proxy/socks: TCP Connect request to tcp:optimizationguide-pa.googleapis.com:443                               2023/08/31 11:09:39 [Info] [4019650842] app/dispatcher: default route for tcp:optimizationguide-pa.googleapis.com:443                                 2023/08/31 11:09:39 [Info] [4019650842] transport/internet/tcp: dialing TCP to tcp:optimizationguide-pa.googleapis.com:443                            2023/08/31 11:09:39 [Debug] transport/internet: dialing to tcp:optimizationguide-pa.googleapis.com:443                                                2023/08/31 11:09:39 tcp:127.0.0.1:45841 accepted tcp:optimizationguide-pa.googleapis.com:443
2023/08/31 11:09:39 [Info] [4019650842] transport/internet/tcp: dialing TCP to tcp:optimizationguide-pa.googleapis.com:443
2023/08/31 11:09:39 [Debug] transport/internet: dialing to tcp:optimizationguide-pa.googleapis.com:443                                                2023/08/31 11:09:39 [Info] [1188240663] proxy/socks: TCP Connect request to tcp:optimizationguide-pa.googleapis.com:443                               2023/08/31 11:09:39 [Info] [1188240663] app/dispatcher: default route for tcp:optimizationguide-pa.googleapis.com:443                                 2023/08/31 11:09:39 tcp:127.0.0.1:45842 accepted tcp:optimizationguide-pa.googleapis.com:443        2023/08/31 11:09:39 [Info] [1188240663] transport/internet/tcp: dialing TCP to tcp:optimizationguide-pa.googleapis.com:443                            2023/08/31 11:09:39 [Debug] transport/internet: dialing to tcp:optimizationguide-pa.googleapis.com:443
2023/08/31 11:09:39 [Info] [1188240663] transport/internet/tcp: dialing TCP to tcp:optimizationguide-pa.googleapis.com:443
2023/08/31 11:09:39 [Debug] transport/internet: dialing to tcp:optimizationguide-pa.googleapis.com:443
2023/08/31 11:09:39 [Info] [4019650842] transport/internet/tcp: dialing TCP to tcp:optimizationguide-pa.googleapis.com:443
2023/08/31 11:09:39 [Debug] transport/internet: dialing to tcp:optimizationguide-pa.googleapis.com:443
2023/08/31 11:09:39 [Info] [1188240663] transport/internet/tcp: dialing TCP to tcp:optimizationguide-pa.googleapis.com:443                            2023/08/31 11:09:39 [Debug] transport/internet: dialing to tcp:optimizationguide-pa.googleapis.com:443
2023/08/31 11:09:40 [Info] [4019650842] transport/internet/tcp: dialing TCP to tcp:optimizationguide-pa.googleapis.com:443
2023/08/31 11:09:40 [Debug] transport/internet: dialing to tcp:optimizationguide-pa.googleapis.com:443
2023/08/31 11:09:40 [Info] [1188240663] transport/internet/tcp: dialing TCP to tcp:optimizationguide-pa.googleapis.com:443                            2023/08/31 11:09:40 [Debug] transport/internet: dialing to tcp:optimizationguide-pa.googleapis.com:443
2023/08/31 11:09:40 [Info] [78890652] proxy/socks: TCP Connect request to tcp:ip.bablosoft.com:80   2023/08/31 11:09:40 [Info] [78890652] app/dispatcher: default route for tcp:ip.bablosoft.com:80     2023/08/31 11:09:40 [Info] [78890652] transport/internet/tcp: dialing TCP to tcp:ip.bablosoft.com:802023/08/31 11:09:40 [Debug] transport/internet: dialing to tcp:ip.bablosoft.com:80                  2023/08/31 11:09:40 tcp:127.0.0.1:45843 accepted tcp:ip.bablosoft.com:80                            2023/08/31 11:09:40 [Info] [78890652] transport/internet/tcp: dialing TCP to tcp:ip.bablosoft.com:802023/08/31 11:09:40 [Debug]
transport/internet: dialing to tcp:ip.bablosoft.com:80                  2023/08/31 11:09:40 [Info] [78890652] transport/internet/tcp: dialing TCP to tcp:ip.bablosoft.com:802023/08/31 11:09:40 [Debug] transport/internet: dialing to tcp:ip.bablosoft.com:80                  2023/08/31 11:09:40 [Info] [4019650842] transport/internet/tcp: dialing TCP to tcp:optimizationguide-pa.googleapis.com:443                            2023/08/31 11:09:40 [Debug] transport/internet: dialing to tcp:optimizationguide-pa.googleapis.com:443                                                2023/08/31 11:09:40 [Info] [1188240663] transport/internet/tcp: dialing TCP to tcp:optimizationguide-pa.googleapis.com:443                            2023/08/31 11:09:40 [Debug] transport/internet: dialing to tcp:optimizationguide-pa.googleapis.com:443                                                2023/08/31 11:09:40 [Info] [78890652] transport/internet/tcp: dialing TCP to tcp:ip.bablosoft.com:802023/08/31 11:09:40 [Debug] transport/internet: dialing to tcp:ip.bablosoft.com:80                  2023/08/31 11:09:40 [Info] [4019650842] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: failed to open connection to tcp:optimizationguide-pa.googleapis.com:443 > common/retry: [dial tcp: lookup optimizationguide-pa.googleapis.com on [::1]:53: read udp [::1]:50241->[::1]:53: read: connection refused dial tcp: lookup optimizationguide-pa.googleapis.com on [::1]:53: read udp [::1]:58034->[::1]:53: read: connection refused dial tcp: lookup optimizationguide-pa.googleapis.com on [::1]:53: read udp [::1]:39120->[::1]:53: read: connection refused dial tcp: lookup optimizationguide-pa.googleapis.com on [::1]:53: read udp [::1]:57594->[::1]:53: read: connection refused dial tcp: lookup optimizationguide-pa.googleapis.com on [::1]:53: read udp [::1]:39806->[::1]:53: read: connection refused] > common/retry: all retry attempts failed
2023/08/31 11:09:40 [Info] [4019650842] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe        2023/08/31 11:09:40 [Info] [1188240663] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: failed to open connection to tcp:optimizationguide-pa.googleapis.com:443 > common/retry: [dial tcp: lookup optimizationguide-pa.googleapis.com on [::1]:53: read udp [::1]:35727->[::1]:53: read: connection refused dial tcp: lookup optimizationguide-pa.googleapis.com on [::1]:53: read udp [::1]:46317->[::1]:53: read: connection refused dial tcp: lookup optimizationguide-pa.googleapis.com on [::1]:53: read udp [::1]:56477->[::1]:53: read: connection refused dial tcp: lookup optimizationguide-pa.googleapis.com on [::1]:53: read udp [::1]:49024->[::1]:53: read: connection refused dial tcp: lookup optimizationguide-pa.googleapis.com on [::1]:53: read udp [::1]:58088->[::1]:53: read: connection refused] > common/retry: all retry attempts failed                                      2023/08/31 11:09:40 [Info] [1188240663] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2023/08/31 11:09:40 [Info] [78890652] transport/internet/tcp: dialing TCP to tcp:ip.bablosoft.com:802023/08/31 11:09:40 [Debug] transport/internet: dialing to tcp:ip.bablosoft.com:80                  2023/08/31 11:09:41 [Info] [78890652] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: failed to open connection to tcp:ip.bablosoft.com:80 > common/retry: [dial tcp: lookup ip.bablosoft.com on [::1]:53: read udp [::1]:57316->[::1]:53: read: connection refused dial tcp: lookup ip.bablosoft.com on [::1]:53: read udp [::1]:55109->[::1]:53: read: connection refused dial tcp: lookup ip.bablosoft.com on [::1]:53: read udp [::1]:57149->[::1]:53: read: connection refused dial tcp: lookup ip.bablosoft.com on [::1]:53: read udp [::1]:44840->[::1]:53: read: connection refused dial tcp: lookup ip.bablosoft.com on [::1]:53: read udp

**Comment by us254** [comment]
There is an issue with the DNS resolution of the domain ip.bablosoft.com. The error message indicates that the DNS server at [::1]:53 is returning a "connection refused" error when attempting to resolve the domain.
