### ISSUE TITLE
单IPV6出站，无法正常解析DNS访问IPV6的网站

### ISSUE THREAD

**Issue by jyogyou** [XTLS/Xray-core#2471]
我是用IPV4连接进服务器的IPV4，服务器上有IPV6，我想使用IPV6出站，于是配置如下，这个配置是X-UI的面板，1.8.3XRAY内核
{
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
     "tag": "ipv6",
     "sendThrough": "2403:71c0:2000::40a:83c9",
     "protocol": "freedom",
     "settings": {
        "domainStrategy": "UseIP"
     }
   },
    {
      "tag": "direct",    
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "handshake": 10,
        "connIdle": 100,
        "uplinkOnly": 2,
        "downlinkOnly": 3,
        "statsUserUplink": true,
        "statsUserDownlink": true,
        "bufferSize": 10240
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "rules": [
      {
       "inboundTag": [
         "inbound-46023"
       ],
       "outboundTag": "ipv6",
       "type": "field"
     },
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "network": "udp,tcp"
      }
    ]
  },
  "stats": {}
}
客户端使用IPV4连接进服务器，连接OK，就是无法打开网站，就连youtube都无法打开，然后客户端这边设置全局代理，如果客户端这边设置了IPV6的DNS后却能打开网站，但会优先使用本地IPV6，比如访问ip.sb显示的是本地国内IP，但youtube有能打开，这个情况我困惑了很久找不到解决办法，有没有哪位大神遇到过同样的问题，请帮我解答下。

**Comment by chika0801** [comment]
看你发的配置入站只有1个API入站。我不用XUI，没其它入站难关XUI是用API的入站也不对。帮不了你。

**Comment by jyogyou** [comment]
> 

感谢恢复，折腾了一天，给配置添加了DNS，各种OutboundConfigurationObject尝试完，都不行，最后是把本地客户端的DNS解析部分全删了，完全交给服务器就解决了，希望对其他同样遇到的有参考作用。
