### ISSUE TITLE
Allow IP addresses in logs to be masked

### ISSUE THREAD

**Issue by PoneyClairDeLune** [XTLS/Xray-core#2473]
Please allow IP addresses in logs to be masked or removed, and allow different masks to be applied to IPv4 and IPv6. For example, applying `/8` on `14.51.4.1` would let it output `14.0.0.0` instead, and `/32` on `919:28a1:72b1::5d3e` would make `919:28a1::` instead. Or setting both to `/0` would effectively disable IP logging.
This feature was already implemented in the [Caddy webserver](https://caddyserver.com/docs/caddyfile/directives/log#ip-mask).

PS: And [Hysteria](https://github.com/apernet/hysteria).

**Comment by Fangliding** [comment]
dup
