### ISSUE TITLE
能不能限制xray不要使用某些端口啊 

### ISSUE THREAD

**Issue by harvey-git** [XTLS/Xray-core#2481]
如题，我用了xray两年了，基本一切正常。
问题是，我最近在用android studio，然后发现其虚拟机通过adb连接不上，排查发现时被后台的xray占用了5037端口，临时关闭xray后再启动adb能连上，之后再启动xray就都正常了，问题是之后adb不能退出，一旦退出xray就会再次占用5037端口，导致adb再次连接不上，只能再手动通知xray一次……如此循环……

所以我想问问，能不能在配置文件里设置保留端口，这些保留端口 xray始终不会使用。

**Comment by mclovin-2k** [comment]
这两个我也同时用  并且我的Core是开机自启的  从未发现过此类问题

**Comment by qist** [comment]
win 系统
```
使用以下NETSH命令保留端口:

netsh int <ipv4|ipv6> Add excludedportrange [protocol=]tcp|udp [startport=]<integer> [numberofports=]<integer> [[store=]active|persistent]

例如,要为UDPv6保留端口55368-55372,请使用以下命令:

netsh int ipv6 add excludedportrange protocol=udp startport=55368 numberofports=5
```
linux 系统
```
net.ipv4.ip_local_reserved_ports= 1024-4096
```

**Comment by Fangliding** [comment]
这楼都啥玩意 配置文件里写了什么端口 xray就监听什么端口 只有可能是你的配置文件里把这个端口占了才会出现这种问题 检查你自己的配置文件或者客户端

**Comment by qist** [comment]
> @qist 想请教一下，如果按照你分享的命令保留了这些端口号，那么这些保留的端口号那些程序能够使用呢？因为按正常的理解，如果保留的端口号xray用不了，那么同样的android studio也应该用不了才是，因为命令里面并没有指定屏蔽某些程序使用这些保留端口
> 
> 谢谢！

所有程序都能静态监听端口，保留端口就不会动态的去使用了。程序连接外部保留端口就不会被使用。
