### ISSUE TITLE
enable ssl encryption for shadowsocks inbounds

### ISSUE THREAD

**Issue by AlefbeMedia** [XTLS/Xray-core#2483]
Hello
I have a question
Do Shadowsocks inbounds like Outline use ssl encryption in xray?

Considering that I am almost certain that they do not use encryption
How to enable ssl for shadowsocks inbounds?

**shadowsocks or outline themselves use ssl, but xray seems like this should be done manually.**

can you help me? very important

**Comment by chika0801** [comment]
Shadowsocks is a protocol that provides its own encryption method if you are using tcp transport.

If you are using websocks transport, the protocol is Shadowsocks and you are using the encryption method provided by Shadowsocks itself. In this case, you can use a combination of websocks+TLS.

**Comment by AlefbeMedia** [comment]
> Shadowsocks is a protocol that provides its own encryption method if you are using tcp transport.
> 
> If you are using websocks transport, the protocol is Shadowsocks and you are using the encryption method provided by Shadowsocks itself. In this case, you can use a combination of websocks+TLS.
> 
> That's my guess as to what you meant by your question. If you meant something else, please describe your question a bit more.

**My main problem is that when I install outline on my server, the connections connect at a very high speed, but this does not happen in xray, and in xray, shadowsocks inbounds do not work.**

**Comment by chika0801** [comment]
I don't know what program outline is.

> but this does not happen in xray, and in xray, shadowsocks inbounds do not work.
I guess it is because of the lack of certificate files in the xray core

If you need further help, you need to post the config file for your Xray. For example, server-side and client-side configuration files.

I can't guess from your description how you are using it.

**Comment by AlefbeMedia** [comment]
> I don't know what program outline is.
> 
> > but this does not happen in xray, and in xray, shadowsocks inbounds do not work.
> > I guess it is because of the lack of certificate files in the xray core
> 
> If you need further help, you need to post the config file for your Xray. For example, server-side and client-side configuration files.
> 
> I can't guess from your description how you are using it.

```
{
      "tag": "Shadowsocks TCP",
      "listen": "0.0.0.0",
      "port": 443,
      "protocol": "shadowsocks",
      "settings": {
        "clients": [],
        "network": "tcp,udp"
      }
    }
```
**Does shadowsocks not need certificate files for encryption? So why are they not addressed in the configuration?**

**Comment by chika0801** [comment]
https://github.com/chika0801/Xray-examples/tree/255cde93c195c0826e72d94e3279a991abe00bb8/Shadowsocks-2022-TCP

Please refer to the configuration example in the link above. the SS protocol is encrypted, the link uses "method": "2022-blake3-aes-128-gcm" . You need to understand this basic point. I replied to you in the previous reply.

**Comment by AlefbeMedia** [comment]
> https://github.com/chika0801/Xray-examples/tree/255cde93c195c0826e72d94e3279a991abe00bb8/Shadowsocks-2022-TCP
> 
> Please refer to the configuration example in the link above. the SS protocol is encrypted, the link uses `"method": "2022-blake3-aes-128-gcm" `. You need to understand this basic point. I replied to you in the previous reply.
> 
> With SS, in mainland China, the end result is that the IP address of the VPS will be blocked by the network firewall, which means you can't access the IP of your VPS in mainland China.
> 
> That's why we generally don't use SS protocols to leave the mainland Chinese network in mainland China.

**What is the best method for data encryption in shadowsocks?
My next question is:
Is there no need for certificate files for encryption in shadowsocks?**

**Comment by chika0801** [comment]
> What is the best method for data encryption in shadowsocks?

> Please refer to the configuration example in the link above. the SS protocol is encrypted, the link uses "method": "2022-blake3-aes-128-gcm" . You need to understand this basic point. I replied to you in the previous reply.


> Is there no need for certificate files for encryption in shadowsocks?

https://github.com/XTLS/Xray-core/issues/2483#issuecomment-1691067420
