### ISSUE TITLE
请问Nanopi R5S在openwrt中应该下载什么型号的核心文件包

### ISSUE THREAD

**Issue by XXXstyle** [XTLS/Xray-core#2492]
网上找了一圈没找到，来求助了。。谢谢！

**Comment by IRN-Kawakaze** [comment]
arm64-v8a

或许用不着自己选版本下载，版本比较新的openwrt可以尝试通过opkg更新xray-core。

**Comment by XXXstyle** [comment]
> arm64-v8a
> 
> 或许用不着自己选版本下载，版本比较新的openwrt可以尝试通过opkg更新xray-core。

感谢！
