### ISSUE TITLE
能否在其他Git平台提供仓库镜像，比如GitLab/Codeberg/BitBucket

### ISSUE THREAD

**Issue by ytxmobile98** [XTLS/Xray-core#2493]
现在GitHub被干扰很严重，没有别的梯子的话访问非常不稳定，作者是否可以考虑在其他Git平台（如GitLab/CodeBerg/BitBucket）建立镜像代码，方便大家下载Xray搭建梯子呢？谢谢🙏🏻

**Comment by Smallthing** [comment]
。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。知道github为啥干扰很严重吗。你是想让每个平台都这样？

**Comment by Fangliding** [comment]
git本来就是分布式的 代码你自己就可以传去你说的这些平台 传去gitee都可以只要他们不制裁你

**Comment by RPRX** [comment]
没有时间搞这么多平台，欢迎大家建立各种镜像/反代以方便国内访问

以前 gitee 有 Xray-core，现在不知道
