### ISSUE TITLE
tls1.3 不支持 这个加密套件吗？ TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256

### ISSUE THREAD

**Issue by architecturers** [XTLS/Xray-core#2495]
go tls库里面有这么一行 supportedOnlyTLS12
{TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256", supportedOnlyTLS12, false},

如果minVersion 设置为 1.3 会不会有冲突
我刚才试了 可以正常运行 ，不知道长时间运行 会不会 有问题

https://go.dev/src/crypto/tls/cipher_suites.go#L44

![屏幕截图 2023-08-27 195943](https://github.com/XTLS/Xray-core/assets/26484669/22b55336-3665-45a8-bbe8-e301b4807083)

**Comment by RPRX** [comment]
minVersion 1.3 就是只支持中间那三个套件

**Comment by architecturers** [comment]
"minVersion": "1.3",
"cipherSuites": "TLS_AES_128_GCM_SHA256",
当我这样设置的时候。

我测出来 密钥交换算法 是 x25519
go语言支持 ed25519 签名算法吗？
我自签了 一份ed25519的证书 目前运行还算正常 就是不知道能不能稳定运行

**Comment by RPRX** [comment]
> go语言支持 ed25519 签名算法吗？

这种问题能不能自己去搜？

**Comment by RPRX** [comment]
本来 issue 区就不是用来提问的，其次这些基础的、遍地答案的问题为什么要发这里？嫌我们不够忙？人肉 GPT？

**Comment by Fangliding** [comment]
> "minVersion": "1.3", "cipherSuites": "TLS_AES_128_GCM_SHA256", 当我这样设置的时候。
> 
> 我测出来 密钥交换算法 是 x25519 go语言支持 ed25519 签名算法吗？ 我自签了 一份ed25519的证书 目前运行还算正常 就是不知道能不能稳定运行

证书签名算法和访问的时候密钥交换算法不是一个玩意 哪怕是个RSA证书 Chrome也会告诉你用了25519交换密钥
证书签名算法不支持ed25519 这是ca/b form规定的 ecc证书用的NIST的曲线 没有CA会签发ed25519证书 支持就鬼知道了

**Comment by RPRX** [comment]
REALITY 就是 ed25519 证书，Go 支持

**Comment by architecturers** [comment]
我没问清楚 我知道go支持
我是问xray 是否支持
我查了一下 go 支持eddsa 需要 额外的代码  我不知道 xray 加了没
用这个证书 程序崩溃过 所以不知道 是不是证书的问题 还是程序有bug
另外看go的加密套件 只有ecdsa的 没有eddsa的 所以吃不准

**Comment by RPRX** [comment]
TLSv1.3 支持，1.2 可能会炸
