### ISSUE TITLE
是否可以指定dns的出站？

### ISSUE THREAD

**Issue by qianyu-wang** [XTLS/Xray-core#2496]
dns的server怎么指定用哪个outbound进行代理？根据规则访问不同地区的地址时会用不同地区的代理，但是dns似乎无法用对应的代理来解析域名。

**Comment by qianyu-wang** [comment]
> ```
> 
>     "dns": {
>         "servers": [
>             "1.1.1.1",
>             "8.8.8.8"
>         ]
>     },
> 
>     "routing": {
>         "rules": [
> 
>             {
>                 "type": "field",
>                 "ip": [
>                     "1.1.1.1"
>                 ],
>                 "outboundTag": "direct1"
>             },
>             {
>                 "type": "field",
>                 "ip": [
>                     "8.8.8.8"
>                 ],
>                 "outboundTag": "direct2"
>             }
>         ]
>     },
> 
>     "outbounds": [
>         {
>             "protocol": "xxx",
>             "settings": {
>                 "domainStrategy": "UseIPv4"
>             },
>             "tag": "direct1"
>         },
>         {
>             "protocol": "xxx",
>             "settings": {
>                 "domainStrategy": "UseIPv4"
>             },
>             "tag": "direct2"
>         }
>     ]
> ```
> 
> 比较麻烦，
> 
> > 根据规则访问不同地区的地址时会用不同地区的代理
> 
> 你列下你的路由规则 ，才能再帮你看看

我所有的dns都需要通过使用1.1.1.1来解析，因为我后面接了wireguard，我针对写了日本、香港和美国进行不同的出站规则 入站->日本出站->wireguard，入站->美国出站->wireguard，现在头疼的是因为路由只能给1.1.1.1指定某个出站，所以无法得到正确的ip来用ip规则来进行分流

**Comment by chika0801** [comment]
`入站->日本出站->wireguard`

问下你意思 比如你现在的VPS A是叫转，他配置就是 入站，出站到日本VPS。然后你日本VPS配置内容是入站，出站进wireguard？

**Comment by qianyu-wang** [comment]
> `入站->日本出站->wireguard`
> 
> 问下你意思 比如你现在的VPS A是中转，他配置就是 入站，出站到日本VPS（比如开SS2022协议）。然后你日本VPS配置内容是入站，出站进wireguard？

转wireguard是本地用任意门加规则进行链式代理的，VPS A是机场

**Comment by chika0801** [comment]
> > `入站->日本出站->wireguard`
> > 问下你意思 比如你现在的VPS A是中转，他配置就是 入站，出站到日本VPS（比如开SS2022协议）。然后你日本VPS配置内容是入站，出站进wireguard？
> 
> 转wireguard是本地用任意门加规则进行链式代理的，VPS A是机场

你意思是你客户端本地是用了链式代理，用机场（VPS A），机场再到你落地机，你落地机进warp。

那这种情况，我帮不了你。因为要分析DNS请求怎么做，应该比较麻烦（我也不会这样用）你看看别人了。

**Comment by qianyu-wang** [comment]
> 



> > > `入站->日本出站->wireguard`
> > > 问下你意思 比如你现在的VPS A是中转，他配置就是 入站，出站到日本VPS（比如开SS2022协议）。然后你日本VPS配置内容是入站，出站进wireguard？
> > 
> > 
> > 转wireguard是本地用任意门加规则进行链式代理的，VPS A是机场
> 
> 你意思是你客户端本地是用了链式代理，用机场（VPS A），机场再到你落地机，你落地机进warp。
> 
> 那这种情况，我帮不了你。因为要分析DNS请求怎么做，应该比较麻烦（我也不会这样用）你看看别人了。

没有落地机，本地是机场和wireguard两个出站，本地链式代理直接机场->wireguard
我看到sing-box里的dns server有detour这个配置，但是没在xray中找到，实在不行我把dns服务放到sing-box里，然后设置dns服务器为sing-box...就是有点麻烦，规则都要写两遍

**Comment by chika0801** [comment]
> 我看到sing-box里的dns server有detour这个配置，但是没在xray中找到

xray的DNS部分没对应功能的参数，是在路由部分通过对DNS的IP指定走哪个出站的tag

**Comment by qianyu-wang** [comment]
> > 我看到sing-box里的dns server有detour这个配置，但是没在xray中找到
> 
> xray的DNS部分没对应功能的参数，是在路由部分通过对DNS的IP指定走哪个出站的tag

是的，这样xray无法根据不同域名对同一个dns使用不同地区的代理去解析了，不晓得好不好改

**Comment by qianyu-wang** [comment]
> > 我看到sing-box里的dns server有detour这个配置，但是没在xray中找到
> 
> xray的DNS部分没对应功能的参数，是在路由部分通过对DNS的IP指定走哪个出站的tag

早上刚想到好像可以用任意门配合路由实现，任意门里目标地址写1.1.1.1:53，路由里根据inbound的tag来指定不同的出站
