### ISSUE TITLE
建议更换ws库为GOWebsockets，提升性能，减少资源

### ISSUE THREAD

**Issue by yukunwu** [XTLS/Xray-core#25]
参见文章https://yalantis.com/blog/how-to-build-websockets-in-go/
或者参见下面文档，作者是如何提升ws性能，减少资源占用的
[1m connections for websocket.pdf](https://github.com/XTLS/Xray-core/files/5615107/1m.connections.for.websocket.pdf)

**Comment by yukunwu** [comment]
建议库，链接https://github.com/sacOO7/gowebsocket

**Comment by rprx** [comment]
会考虑，之前在研究 0-RTT WebSocket 时研究过各种 WS 库，gobws 比较合适，应该可以实现分散读和集中写，减少内存拷贝次数

https://github.com/gobwas/ws

（你的链接有误

**Comment by yukunwu** [comment]
好的，辛苦作者了，已更新。因为在实际应用中也遇到类似问题，对于代理这种场景，一来高并发还是很有必要的，二来减少资源占用，在一些低端机上也比较省资源。
