### ISSUE TITLE
关于一个比较蠢的证书问题

### ISSUE THREAD

**Issue by shandongtlb** [XTLS/Xray-core#2500]
最近发现（其实早就有了）阿里华为腾讯可以申请digv的免费一年ssl证书，如果用它来搞vless+xtls+vison的话安全吗，个人感觉不太安全，毕竟这些证书是国内公司托管的。求大佬解答😂😂，这个问题确实问的比较蠢，大佬别喷哈。。
不想搞时间太短的证书，自动申请不想用，纯手动又怕忘。。

**Comment by RPRX** [comment]
私钥是他们生成的，他们有备份，所以不安全

**Comment by shandongtlb** [comment]
> 私钥是他们生成的，他们有备份，所以不安全

好的好的，如果这样的话，那我用reality指向自己的带有该证书的网站就可以解决了吧

**Comment by RPRX** [comment]
> > 私钥是他们生成的，他们有备份，所以不安全
> 
> 好的好的，如果这样的话，那我用reality指向自己的带有该证书的网站就可以解决了吧

可以是可以，但假如某天 GFW 尝试拿你的私钥对你进行中间人攻击，结果发现客户端进入了爬虫模式。。。

**Comment by RPRX** [comment]
To 群里：？B 给 A 发时间戳直到 A 觉得同步，此时 B 比 A 慢了 a 秒是不假，但 a 这个值你怎么读取出来？

**Comment by RPRX** [comment]
这个问题这么说吧，你就想宇宙中只有两个星球，只能用光速通信，这有鬼了才能算出单向延迟

**Comment by RPRX** [comment]
~~抱歉，加一个抽象的限制条件：往返光程不等~~

**Comment by RPRX** [comment]
这 GitHub BOT 关键的时刻掉链子，~~能不能换个~~

**Comment by Fangliding** [comment]
@RPRX 这没有鉴权和一堆bug的bot早想换了 但是好像没有竞品的说

**Comment by RPRX** [comment]
总之意思是，仅两点，通信往返时长不同，仅靠普通通信是没有办法测出单向延迟的，无解

**Comment by RPRX** [comment]
因为其实我也列了一些方程，变量总是比有效方程数多一个，唯一解法是再来个 a-b 的值，但这个东西无论如何都是得不到的

**Comment by RPRX** [comment]
从另一个角度来说，这个问题的本质是一个精准对时的问题，但只有上述两点是做不到的，除非先把它们拉到一块对时再分开

**Comment by RPRX** [comment]
然后什么叫非普通通信呢？~~比如你发个表给对面~~

**Comment by shandongtlb** [comment]
> > > 私钥是他们生成的，他们有备份，所以不安全
> > 
> > 
> > 好的好的，如果这样的话，那我用reality指向自己的带有该证书的网站就可以解决了吧
> 
> 可以是可以，但假如某天 GFW 尝试拿你的私钥对你进行中间人攻击，结果发现客户端进入了爬虫模式。。。

哈哈哈哈有道理 笑死我了
