### ISSUE TITLE
v2rayN中的xray.exe自动下载一些东西，不知道是什么，就算关闭自动配置系统代理仍然在下载东西

### ISSUE THREAD

**Issue by DesireDriver** [XTLS/Xray-core#2503]
![Snipaste_2023-08-30_16-53-45](https://github.com/XTLS/Xray-core/assets/143054311/dd1c2bdb-8bae-41f3-9e61-83a216876534)

**Comment by RPRX** [comment]
v2rayN 会自动更新 geo 文件
