### ISSUE TITLE
反连模式能建立多TCP连接吗

### ISSUE THREAD

**Issue by LearnForDreamK** [XTLS/Xray-core#2508]
开了反连模式只能启1个TCP长连接，速度很慢😭。    反连配置mux会报错😂

**Comment by chika0801** [comment]
发两端配置，学提问的智慧。

**Comment by Fangliding** [comment]
看文档 反向代理默认开启Mux
以及这玩意年久失修 最开始的目的就不是传送大量流量

**Comment by LearnForDreamK** [comment]
> 发两端配置，学提问的智慧。

服务端
`{
    "log": {
        "access": "/log/access.log",
        "error": "/log/error.log",
        "loglevel": "warnning",
        "pathSuffix": ".%Y-%m-%d"
    },
    "reverse": {
        "portals": [
            {
                "tag": "adsl-out-line-1",
                "domain": "adsl-1.ss.com"
            }
        ]
    },
    "inbounds": [
        {
            "tag": "tunnel",
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "adsl-1",
                        "email": "adsl-1@ss.com",
                        "flow": "xtls-rprx-vision",
                        "level": 0
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "tcp",
                "security": "reality",
                "realitySettings": {
                    "show": false,
                    "dest": "www.amazon.com:443",
                    "serverNames": [
                        "www.amazon.com"
                    ],
                    "privateKey": "xxxx",
                    "shortIds": [
                        ""
                    ]
                }
            }
        },
        {
            "port": 60001,
            "listen": "0.0.0.0",
            "tag": "http_proxy_port_60001",
            "protocol": "http",
            "settings": {
                "timeout": 0,
                "allowTransparent": false,
                "userLevel": 0
            }
        },
        {
            "port": 61001,
            "listen": "0.0.0.0",
            "tag": "socks_proxy_port_61001",
            "protocol": "socks",
            "settings": {
                "timeout": 0,
                "allowTransparent": false,
                "userLevel": 0,
                "accounts": [
                    {
                        "user": "",
                        "pass": ""
                    }
                ]
            }
        }
    ],
    "routing": {
        "rules": [
            {
                "type": "field",
                "inboundTag": [
                    "http_proxy_port_60001"
                ],
                "outboundTag": "adsl-out-line-1"
            },
            {
                "type": "field",
                "inboundTag": [
                    "socks_proxy_port_61001"
                ],
                "outboundTag": "adsl-out-line-1"
            },
            {
                "type": "field",
                "inboundTag": [
                    "tunnel"
                ],
                "user": [
                    "adsl-1@ss.com"
                ],
                "domain": [
                    "full:adsl-1.ss.com"
                ],
                "outboundTag": "adsl-out-line-1"
            }
        ]
    }
}`

客户端
`{
    "log": {
        "access": "/log/access.log",
        "error": "/log/error.log",
        "loglevel": "warning",
        "pathSuffix": ".%Y-%m-%d"
    },
    "reverse": {
        "bridges": [
            {
                "tag": "bridge1",
                "domain": "adsl-1.ss.com"
            }
        ]
    },
    "outbounds": [
        {
            "tag": "tunnel1",
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "xxxxx",
                        "port": 443,
                        "users": [
                            {
                                "id": "adsl-1",
                                "encryption": "none",
                                "flow": "xtls-rprx-vision",
                                "level": 0
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "reality",
                "realitySettings": {
                    "show": false,
                    "fingerprint": "chrome",
                    "serverName": "www.amazon.com",
                    "publicKey": "xxxxxxx",
                    "shortId": ""
                }
            },
            "mux": {
                "enabled": false,
                "concurrency": 1024
            }
        },
        {
            "protocol": "freedom",
            "sendThrough": "192.168.3.1",
            "settings": {
                "domainStrategy": "UseIP"
            },
            "streamSettings": {
                "sockopt": {
                    "tcpFastOpen": true
                }
            },
            "tag": "out1"
        }
    ],
    "routing": {
        "rules": [
            {
                "type": "field",
                "inboundTag": [
                    "bridge1"
                ],
                "domain": [
                    "full:adsl-1.ss.com"
                ],
                "outboundTag": "tunnel1"
            },
            {
                "type": "field",
                "inboundTag": [
                    "bridge1"
                ],
                "outboundTag": "out1"
            }
        ]
    },
    "dns": {
        "queryStrategy": "UseIP",
        "tag": "dns_inbound",
        "disableCache": true,
        "disableFallback": true,
        "servers": [
            {
                "address": "localhost",
                "port": 1053
            },
            "223.5.5.5"
        ]
    }
}`

看了下官方文档，明白反连会自动开启mux了😂。 但这个时候我在mux配置里的concurrency还会生效吗

**Comment by LearnForDreamK** [comment]
> 看文档 反向代理默认开启Mux 以及这玩意年久失修 最开始的目的就不是传送大量流量

哦哦哦 感谢大佬🧎‍♀️， 我这边场景是请求量非常大，每秒几千次，我担心用releaty协议走正向请求偷证书频率太高了会有问题，就用了反连😭

**Comment by RPRX** [comment]
主要是反连没开放修改 concurrency 之类的，但开放它们很简单，~~等一个有缘人？~~
