### ISSUE TITLE
询问一下xray作者，客户端对gfw封锁有多大的作用？

### ISSUE THREAD

**Issue by whatpig** [XTLS/Xray-core#2509]
不论服务端搭建什么

客户端到底对gfw侦测有用吗？

打个比方，用安卓的v2rayn、ios的小火箭亦或者软路由openwrt到底对gfw封锁行为有没有加成？

还是说只要服务端换成reality了就能比vless或者trojan之类的，不论客户端用啥，都会更抗封？

又或者说，比如说客户端（手机、电脑）安装了一些乱七八糟的软件、app是不是也会对gfw侦测有加成？比如手机安装了fzapp和电脑安装了乱七八糟的安全卫士。

是不是用软路由+openwrt或者linux客户端+干净的电脑系统和手机更有益抗封锁行为呢？

为什么有此一问，因为本人用1.7.5+vless+xtls用到现在一次没被封端口或者ip，用的是openwrt，在外面几乎不开小火箭之类的工具，所以想搞清楚这个问题，谢谢！

**Comment by lifei6671** [comment]
服务端和客户端是成对出现的，只要协议一致，理论上用什么客户端都无所谓。无非有些客户端支持伪造协议栈。

**Comment by RPRX** [comment]
不同的客户端当然有区别，但这个问题说多了~~不合适~~

**Comment by whatpig** [comment]
> 不同的客户端当然有区别，但这个问题说多了~不合适~

懂了，感谢解答！

**Comment by nursery01** [comment]
> 不同的客户端当然有区别，但这个问题说多了不合适

快講多，我想聽，~~不會翻船的~~
