### ISSUE TITLE
mac版本的xray-core v1.8.4在virustotal网站上查出来 Trojan.OSX.Psw，这个是怎么回事？

### ISSUE THREAD

**Issue by DesireDriver** [XTLS/Xray-core#2514]
mac版本的xray-core v1.8.4在virustotal网站上查出来 Trojan.OSX.Psw，这个是怎么回事？

**Comment by RPRX** [comment]
~~大概是因为 Xray-core 内置有 Trojan 协议，检测到关键字就~~

**Comment by DesireDriver** [comment]
我看到其他非v1.8.4版本中就没有爆出这个问题？
