### ISSUE TITLE
[Machine Translated] 允许面具日志中的IP地址

### ISSUE THREAD

**Issue by PoneyClairDeLune** [XTLS/Xray-core#2521]
Title: Allow IP addresses in logs to be masked

This issue is a machine-translated duplicate of #2473, just to try to garner a response from the Xray community, as this community seem to always prefer to ignore proposals sent in languages other than Chinese.

这个问题是 #2473 的机器翻译副本，只是为了尝试获得 Xray 社区的回应，因为这个社区似乎总是更喜欢忽略以中文以外的语言发送的提案。

请允许屏蔽或删除日志中的 IP 地址，并允许对 IPv4 和 IPv6 应用不同的掩码。 例如，在 `14.51.4.1` 上应用 `/8` 将使其输出 `14.0.0.0` ，而在 `919:28a1:72b1::5d3e` 上应用 `/32` 将使其输出 `919:28a1::` 。 或者将两者设置为 `/0` 将有效禁用 IP 日志记录。

此功能已在 Caddy 网络服务器中实现。

PS：还有歇斯底里。

**Comment by PoneyClairDeLune** [comment]
Please stop ignoring proposals posted in languages other than Chinese. Anti-censorship is not a fight exclusive to the Chinese people.
请停止忽略以中文以外的其他语言发布的建议。反审查不是中国人民独有的斗争。

If there are problems with proposals, please point them out. Any response is good for everyone involved. Plain indifference is just hurting this community.
如果提案有问题，请指出。任何回应对参与的每个人都有好处。简单的冷漠只是伤害了这个社区。

**Comment by RPRX** [comment]
你好，我们没有刻意忽略中文以外的提案，~~因为中文的提案也有很多没有回复，且最近忙着那啥~~

你提的这个功能不难实现，统一为设置掩码即可，@yuhan6665

**Comment by PoneyClairDeLune** [comment]
> 你好，我们没有刻意忽略中文以外的提案，~因为中文的提案也有很多没有回复，且最近忙着那啥~
> 
> 你提的这个功能不难实现，统一为设置掩码即可，@yuhan6665

Thank you for the notice and response! Just that be it in the issues or discussions, if it's not written in Chinese, it would be largely ignored, nearly always receiving no responses. The same cannot be said for posts in Chinese at all.
感谢您的通知和回复！只是无论是问题还是讨论，如果不是用中文写的，基本上都会被忽略，几乎总是得不到回应。对于中文帖子来说，情况完全不同。

**Comment by Fangliding** [comment]
Implemented in #3783
