### ISSUE TITLE
今天被封了（ERR_SSL_ UNRECOGNIZED_NAME_ALERT）

### ISSUE THREAD

**Issue by hkbase** [XTLS/Xray-core#2522]
服务端xray v1.8.4 配置：vless+vision+tcp+tls+fallback回落nginx静态伪装页面          端口：443
客户端xray v1.8.4 配置：vless+vision+tcp+tls+fingerprint 

用户端具体表现：
1、无法打开国外网站了。
2、用tcping监测服务器的端口是开放的。
3、浏览器报错信息如下图所示
![iShot_2023-09-06_09 03 11](https://github.com/XTLS/Xray-core/assets/9875710/050c0229-b7ba-4bc4-883a-a2b3f4e44ccc)
我把在服务端用acme.sh强制重新签发ssl证书，也无济于事。
正在准备切换到[REALITY]。。。。

**Comment by hkbase** [comment]
地理坐标：陕西省

**Comment by RPRX** [comment]
如果不是你配置错误的话，看起来最近墙又开始发力了，但你 tcping 端口开放，实际上用不了，很少见，~~这倒挺甲骨文的~~

**Comment by hkbase** [comment]
我可以确定不是配置问题，这个配置一直稳定在用好久了，直到今天早上，所有的国外网站都打不开了。
我现在已经在原端口的基础上把配置切换到reality协议了，然后网页秒开，各种丝滑流畅。。。。
哎，看来墙又加高了。。。

**Comment by RPRX** [comment]
根据你的情况，不会你那里也上什么白名单黑名单了吧，~~又多一个省？~~

**Comment by RPRX** [comment]
上半年各种报告挺多的，下半年 GFW 沉寂了，但昨天刚封了 https://1.1.1.1 ，看起来这两天它又开始搞事了

**Comment by hkbase** [comment]
因为顶楼贴的那个配置，我一直用的很稳定，就没着急升级到reality协议，只是把软件都更新到了1.8.4。
期间我尝试换到trojan协议，依然无效，最后只能升到最新的reality，才算恢复正常上网。
我这里是坐标是 西安市联通 。

**Comment by Remustarded** [comment]
我说为什么一直稳定的配置这两天有点不对劲,又开始作了🙄

**Comment by RPRX** [comment]
> @RPRX 这个 ERR_SSL_ UNRECOGNIZED_NAME_ALERT 应该包含了有价值的信息吧

你指的是可能 GFW 在伪造 alert？有段时间没研究 OpenSSL 和 BoringSSL 的代码了，@hkbase ~~你能不能换回去抓个包看一下~~

**Comment by RPRX** [comment]
> 因为顶楼贴的那个配置，我一直用的很稳定，就没着急升级到reality协议，只是把软件都更新到了1.8.4。 期间我尝试换到trojan协议，依然无效，最后只能升到最新的reality，才算恢复正常上网。 我这里是坐标是 西安市联通 。

你端口能通但浏览器都访问不了，这很白名单/增强版黑名单，换不能过白名单的协议是没用的，看看这个地区有没有更多报告

对了，服务器是甲骨文还是？

**Comment by RPRX** [comment]
@hkbase 很简单，配置不用换回去，你的域名还解析着那个 IP 吧，下载安装 WireShark，打开后选择你的上网途径（比如 WLAN）开始抓包，然后用浏览器访问你的域名，停止抓包，筛选出与你 IP 相关的所有包，打码 IP 后发上来就行

**Comment by mclovin-2k** [comment]
什么日志都没有 没有分析的价值
大家都是猜

**Comment by RPRX** [comment]
@hkbase 甲骨文的话这种阻断方式挺常见的，但报告集中在上半年，下半年还没什么报告，~~可能 GFW 给甲骨文上了白名单~~

**Comment by hkbase** [comment]
我刚才把配置都还原回去之一，上网又正常了，应该是个误会
应该是我把证书文件搞坏了～

**Comment by hkbase** [comment]
是人为因素导致的，误报～～。耽误大家时间了，对不起各位

**Comment by RPRX** [comment]
> 我可以确定不是配置问题，这个配置一直稳定在用好久了，直到今天早上，所有的国外网站都打不开了。

**Comment by hkbase** [comment]
> > 我可以确定不是配置问题，这个配置一直稳定在用好久了，直到今天早上，所有的国外网站都打不开了。

还是自己太粗心，最终还是配置的问题。
自己打脸了，向大家道歉。
换回旧配置后，发现依然可以奔放如初，继续停留在这个配置，直到不能用的那天。
