### ISSUE TITLE
这个貌似没有linux版

### ISSUE THREAD

**Issue by zerofo** [XTLS/Xray-core#2523]
https://github.com/XTLS/Xray-core/blob/f7c20b85dcbd6c2e8acf2589dfaef8a448daf337/README.md?plain=1#L87

**Comment by JobAbout** [comment]
你得去找这个仓库的作者

**Comment by Nyar233** [comment]
我寻思他项目里的截图不是有Ubuntu吗

**Comment by Nyar233** [comment]
得出没有linux版这个结论之前请先仔细看一下项目内容

https://github.com/LorenEteval/Furious#install:~:text=Note%3A%20Due%20to%20better%20binary%20files%20compatibility%20on%20Windows%20platform%2C%20Windows%20users%20can%20skip%20this%20section%20and%20download%20zip%20file%20in%20the%20release%20page%20that%20contains%20pre%2Dbuilt%20binaries.%20Otherwise%20you%20need%20to%20follow%20the%20instructions%20below.

**Comment by zerofo** [comment]
哦哦  ,要 python 自己装,  我看release 下面没有... 抱歉
