### ISSUE TITLE
我看到其他非v1.8.4版本中就没有爆出这个问题？

### ISSUE THREAD

**Issue by DesireDriver** [XTLS/Xray-core#2525]
我看到其他非v1.8.4版本中就没有爆出这个问题？

_Originally posted by @DesireDriver in https://github.com/XTLS/Xray-core/issues/2514#issuecomment-1709366952_

**Comment by yomnxkcs** [comment]
报毒的主动权在杀毒软件。他说你有毒就算没有也是有。然后有时候用些技术手段，比如加壳、虚拟机等，明明有毒也可以变成没有。上面说包含Trojan关键字是误传，显然不会用这么low的方法来查病毒。大概率是xray v1.8.4的有些二进制数据和某些病毒、木马的片段重复，或者有某些可疑行为。这其实很常见。正规的做法是提交误报申请，但通常需要附带个人身份信息，你会为这个软件交出自己的身份证吗？所以此路不通。

上面说了只是大概率，还有个小概率是xray真的有意无意引入了恶意代码，这只能一行行看代码了。但开发者在合并代码的时候已经检查过一次了，所以再检查一次的重任就交给你了。

**Comment by DesireDriver** [comment]
好的👌

**Comment by RPRX** [comment]
哈哈，~~包含 Trojan 关键字显然是开玩笑~~，偶尔有个版本被报毒很常见，我们都习惯了
