### ISSUE TITLE
关于回落路径匹配的问题

### ISSUE THREAD

**Issue by wbs306** [XTLS/Xray-core#253]
我在其他端口中用docker跑nextcloud，并把它的访问路径设置为`域名/cloud`。在fallbacks中，`path`我设置了`/cloud`，`dest`也是对应的端口，直接通过`域名/cloud`也可以正确访问。
现在的问题就是，当我登录成功之后，网页会跳转到`/cloud/apps/dashboard/`这一页面，导致fallbacks匹配过程中，拿到的`realPath`为`/cloud/apps/dashboard/`，这时便无法回落到设置的端口。
请问`path`的匹配是否可以使用通配符？或是改进匹配规则？

**Comment by rprx** [comment]
path 是为了分流到其它入站，不是这样用的。。。

最开始我写了正则匹配，后来注释掉了

**Comment by AkinoKaede** [comment]
可以不填 path，都会回落到 dest 去

**Comment by wbs306** [comment]
> path 是为了分流到其它入站，不是这样用的。。。
> 
> 最开始我写了正则匹配，后来注释掉了

一开始我也是让他直接分流，网站根目录是`/`，这时候通过`域名/cloud`这个方式访问上去没问题，但是当我登录上去之后，网页给跳转到`域名/apps/dashboard`去了，所以我只能考虑改变网站根目录，但是还是会有这个匹配问题。。。

**Comment by wbs306** [comment]
> 可以不填 path，都会回落到 dest 去

我的目的是想要访问不同路径的时候进行不同回落啊。。。

**Comment by AkinoKaede** [comment]
> > 可以不填 path，都会回落到 dest 去

这种事情可以交给 Nginx HaProxy 这样的软件去做

**Comment by wbs306** [comment]
> > > 可以不填 path，都会回落到 dest 去
> > 
> > 
> > 我的目的是想要访问不同路径的时候进行不同回落啊。。。
> 
> 这种事情可以交给 Nginx HaProxy 这样的软件去做

行吧
