### ISSUE TITLE
求助，启动不了服务

### ISSUE THREAD

**Issue by ddr7ddr** [XTLS/Xray-core#2533]
小白一个，麻烦大佬帮忙看一下。
Sep 08 16:21:42 glowing-idea-1.localdomain systemd[1]: Started Xray Service.
Sep 08 16:21:42 glowing-idea-1.localdomain xray[29571]: Xray 1.8.4 (Xray, Penetrates Everything.) Custom (go1.21.0 linux/amd64)
Sep 08 16:21:42 glowing-idea-1.localdomain xray[29571]: A unified platform for anti-censorship.
Sep 08 16:21:42 glowing-idea-1.localdomain xray[29571]: 2023/09/08 16:21:42 [Info] infra/conf/serial: Reading config: /usr/local/etc/xray/config.json
**Sep 08 16:21:42 glowing-idea-1.localdomain xray[29571]: Failed to start: main: failed to load config files: [/usr/local/etc/xray/config.json] > infra/conf: VLESS clients: "flow" doesn't support "xtls-rprx-vision,none" in this version**
Sep 08 16:21:42 glowing-idea-1.localdomain systemd[1]: xray.service: main process exited, code=exited, status=23/n/a
Sep 08 16:21:42 glowing-idea-1.localdomain systemd[1]: Unit xray.service entered failed state.
Sep 08 16:21:42 glowing-idea-1.localdomain systemd[1]: xray.service failed.

**Comment by chika0801** [comment]
`VLESS clients: "flow" doesn't support "xtls-rprx-vision,none" in this version`

把你的配置文件发上来才能帮你看。

**Comment by ddr7ddr** [comment]
是这个吗？感谢！没有工具，上个GITHUB都要刷半天网页，才打得开。
{
  "log": {
    "access": "none",
    "loglevel": "none"
  },
  "dns": {},
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "block"
      }
    ]
  },
  "policy": {},
  "inbounds": [
    {
      "port": 1330,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "1f097fc5-6d5a-425f-8e74-cbb6cba0a64c",
            "flow": "xtls-rprx-vision,none"
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "dest": 8080
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "tls",
        "tlsSettings": {
          "rejectUnknownSni": true,
          "minVersion": "1.2",
          "certificates": [
            {
              "ocspStapling": 3600,
              "certificateFile": "/usr/local/etc/xray/ssl/xray_ssl.crt",
              "keyFile": "/usr/local/etc/xray/ssl/xray_ssl.key"
            }
          ]
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "tag": "block"
    }
  ],
  "transport": {},
  "stats": {},
  "reverse": {}
}

**Comment by picklefan** [comment]
这不是写着吗，流控不支持，你把那个vision后面的none去掉就行了

**Comment by ddr7ddr** [comment]
太感谢了，可以了，一万个赞送给你。我之前用的是PROXYSU傻瓜式安装的，不知道为什么vision和none并列了。我手动进去改，就OK了。

**Comment by gili-gili** [comment]
infra/conf: VLESS clients: "flow" doesn't support "none" in this version

我搞不懂了，我看更新根本就没提到这个，这么大的改动也不说一下，Wiki也是没改，更新完天塌了
