### ISSUE TITLE
希望增加reality的密钥类型选择，现在就是单一的密钥类型X25519太集中了,希望增加 ECDHE-ECDSA, ECDHE-RSA, RSA

### ISSUE THREAD

**Issue by architecturers** [XTLS/Xray-core#2535]
目前这三种密钥交换算法 占据了 互联网的绝大多数。可以更好的大隐于市

**Comment by Fangliding** [comment]
里面用什么外面看不到的
主动探测的话 dest网站是什么 就是什么

**Comment by architecturers** [comment]
能探测出来 所有的reality都用这个 不好吧 还是分散点好

![屏幕截图 2023-09-09 123416](https://github.com/XTLS/Xray-core/assets/26484669/d92501ee-4914-4622-9f3e-bf0d6f9bb81d)

**Comment by Fangliding** [comment]
> 能探测出来 所有的reality都用这个 不好吧 还是分散点好
> 
> ![屏幕截图 2023-09-09 123416](https://user-images.githubusercontent.com/26484669/266760628-d92501ee-4914-4622-9f3e-bf0d6f9bb81d.png)

你下个手机版Chrome 随便点开什么网站 点左上角的锁 再点连接是安全的 都会跳出来 该连接使用AES_128_GCM（或者256） 并使用x25519作为密钥交换机制 除非服务端非常老旧。。

**Comment by architecturers** [comment]
`
   enum {

          /* Elliptic Curve Groups (ECDHE) */
          secp256r1(0x0017), secp384r1(0x0018), secp521r1(0x0019),
          x25519(0x001D), x448(0x001E),

          /* Finite Field Groups (DHE) */
          ffdhe2048(0x0100), ffdhe3072(0x0101), ffdhe4096(0x0102),
          ffdhe6144(0x0103), ffdhe8192(0x0104),

          /* Reserved Code Points */
          ffdhe_private_use(0x01FC..0x01FF),
          ecdhe_private_use(0xFE00..0xFEFF),
          (0xFFFF)
      } NamedGroup;

      struct {
          NamedGroup named_group_list<2..2^16-1>;
      } NamedGroupList;

`
x25519 只占了很小一部分 远没有那三个在tls1.3中的大

**Comment by Fangliding** [comment]
> ` enum {
> 
> ```
>       /* Elliptic Curve Groups (ECDHE) */
>       secp256r1(0x0017), secp384r1(0x0018), secp521r1(0x0019),
>       x25519(0x001D), x448(0x001E),
> 
>       /* Finite Field Groups (DHE) */
>       ffdhe2048(0x0100), ffdhe3072(0x0101), ffdhe4096(0x0102),
>       ffdhe6144(0x0103), ffdhe8192(0x0104),
> 
>       /* Reserved Code Points */
>       ffdhe_private_use(0x01FC..0x01FF),
>       ecdhe_private_use(0xFE00..0xFEFF),
>       (0xFFFF)
>   } NamedGroup;
> 
>   struct {
>       NamedGroup named_group_list<2..2^16-1>;
>   } NamedGroupList;
> ```
> 
> ` x25519 只占了很小一部分 远没有那三个在tls1.3中的大

浏览器基本默认都是x25519 少臆想了 这是可用列表 不是流量占比列表 其他的才罕见

**Comment by architecturers** [comment]
> 
标准tls1.3里
x25519 只能用于三个没有指定交换算法的套件里面
其他更广的套件都不是x25519 多查查再做结论 目前主流还是ECDHE-ECDSA, ECDHE-RSA, RSA 这三个 总的来说分散点 比集中好

而且go语言的tls1.3 只支持下面三个没指定的，太明显了。
	TLS_AES_128_GCM_SHA256       uint16 = 0x1301
	TLS_AES_256_GCM_SHA384       uint16 = 0x1302
	TLS_CHACHA20_POLY1305_SHA256 uint16 = 0x1303

go里面以下这写都不支持tls1.3 还有更多 只是把go里面的代码粘贴过来
	TLS_RSA_WITH_RC4_128_SHA                      uint16 = 0x0005
	TLS_RSA_WITH_3DES_EDE_CBC_SHA                 uint16 = 0x000a
	TLS_RSA_WITH_AES_128_CBC_SHA                  uint16 = 0x002f
	TLS_RSA_WITH_AES_256_CBC_SHA                  uint16 = 0x0035
	TLS_RSA_WITH_AES_128_CBC_SHA256               uint16 = 0x003c
	TLS_RSA_WITH_AES_128_GCM_SHA256               uint16 = 0x009c
	TLS_RSA_WITH_AES_256_GCM_SHA384               uint16 = 0x009d
	TLS_ECDHE_ECDSA_WITH_RC4_128_SHA              uint16 = 0xc007
	TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA          uint16 = 0xc009
	TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA          uint16 = 0xc00a
	TLS_ECDHE_RSA_WITH_RC4_128_SHA                uint16 = 0xc011
	TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA           uint16 = 0xc012
	TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA            uint16 = 0xc013
	TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA            uint16 = 0xc014
	TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256       uint16 = 0xc023
	TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256         uint16 = 0xc027
	TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256         uint16 = 0xc02f
	TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256       uint16 = 0xc02b
	TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384         uint16 = 0xc030
	TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384       uint16 = 0xc02c
	TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256   uint16 = 0xcca8
	TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 uint16 = 0xcca9

**Comment by architecturers** [comment]
也可以这么说吧 但是不准确
tls1.3 支持的套件几十个 很多 远远不止那三个

**Comment by Fangliding** [comment]
> 

reality必须要TLS1.3 要用到TLS1.3的特性 你要不看看你都复制了些什么过来

**Comment by architecturers** [comment]
速度最快的是 x25519的交换 +ed25519的签名+aes+gcm
其次是 ecdhe+ecdsa+aes+gcm
最差是 rsa+rsa+对称
可是市场上最多的是rsa那一系列

**Comment by architecturers** [comment]
> > 
> 
> reality必须要TLS1.3 要用到TLS1.3的特性 你要不看看你都复制了些什么过来

麻烦你多查查吧 ， 那是go语言的支持 不是tls1.3的支持 查完了 再出来回复 我复制的意思就是 太集中明显了

**Comment by architecturers** [comment]
> xray的tlsSettings里 写minVersion 1.3以后，加密套件也会只剩下三个。 话说我的确该抓包看看reality的clienthello握手包有几个加密套件。

对啊 go对tls1.3的支持 就那三个 所以说太集中了

**Comment by architecturers** [comment]
> 那你也说了，速度最快的这个组合以后肯定是越来越多的~

理论上是这样 实际上 现在好多公司 都是抱着rsa

**Comment by Fangliding** [comment]
> 
远不止那三个？
要我去多搜搜
要不你自己看看RFC8446
里面定义了几个
只定义了5个
另外两个CCM 虽然被定义了 gotls没做 openssl有但没有启用 我更没见过网站真用这个的

**Comment by architecturers** [comment]
> 

reality的交换是写死的 直接固定在客户端和服务器的 所以我说最好

> > 那你也说了，速度最快的这个组合以后肯定是越来越多的~
> 
> 理论上是这样 实际上 现在好多公司 都是抱着rsa



> 只定义了5个

只定义了5个 你就得出这个结论 行了 各自保留意见吧

**Comment by architecturers** [comment]
套件几十个 主流的交换算法 就我标题那三个

**Comment by Fangliding** [comment]
我总结一下 从一开始密钥类型就没说清楚在指什么
xray的ed25519 key 那是给证书用的 在TLS1.3 里 证书是加密的 证书用什么签名算法 不重要 这也是我一开始的意思cipher suites.
后面又扯扯扯 扯出来cipher suites 和xray用ed25519签名证书有半毛钱关系
到这里已经是无关话题了 什么乱七八糟的很多的cipher suites TLS1.3就定义了5个 实际用的就3个

**Comment by architecturers** [comment]
> 我总结一下 从一开始密钥类型就没说清楚在指什么 xray的ed25519 key 那是给证书用的 在TLS1.3 里 证书是加密的 证书用什么签名算法 不重要 这也是我一开始的意思 后面又扯扯扯 扯出来cipher suites 和xray用ed25519签名证书有半毛钱关系 到这里已经是无关话题了 什么乱七八糟的很多的cipher suites TLS1.3就定义了5个 实际用的就3个 在RFC里写的明明白白 会英语你可以自己看 什么什么公司抱着RSA不放 你先说清楚什么RSA RSA证书？ 那确实 但说了里面证书看不到压根不重要

听不懂 就别掺和了呗  您说的不一定全对 我可能也许会有一两处 对的地方吧 各自保留已经吧

**Comment by Fangliding** [comment]
> 
说话有歧义指出来说我我听不懂可以走？
我说的不一定全对 请指出
你说的有错 我指出有问题
各自保留 不是 这是一个很明显有对错的东西 不是什么哲学讨论 错的就是错的 错的还能保留 你可以说唯心主义唯物主义哪个好 这个可以保留 但是你觉得1+1>2 这还保留意见？

**Comment by architecturers** [comment]
> > 
> 
> 说话有歧义指出来说我我听不懂可以走？ 我说的不一定全对 请指出 你说的有错 我指出有问题 各自保留 不是 这是一个很明显有对错的东西 不是什么哲学讨论 错的就是错的 错的还能保留 你可以说唯心主义唯物主义哪个好 这个可以保留 但是你觉得1+1>2 这还保留意见？

你连 交换 签名 对称 都没弄清楚 还要掰扯啊 
怎么连好赖话都听不清楚啊
你真的是 职业吵架的

**Comment by Fangliding** [comment]
> > > 
> > 
> > 
> > 说话有歧义指出来说我我听不懂可以走？ 我说的不一定全对 请指出 你说的有错 我指出有问题 各自保留 不是 这是一个很明显有对错的东西 不是什么哲学讨论 错的就是错的 错的还能保留 你可以说唯心主义唯物主义哪个好 这个可以保留 但是你觉得1+1>2 这还保留意见？
> 
> 你连 交换 签名 对称 都没弄清楚 还要掰扯啊 怎么连好赖话都听不清楚啊 你真的是 职业吵架的

还是没有说出我哪是错的 就谁是职业吵架呢

请循其本 省略中间的瞎吵吵
看你的标题
"希望增加reality的密钥类型"
"现在是单一的密钥类型" 那么我就理解成 ./xray x25519 已经如上所说了
如果你指https://github.com/XTLS/Xray-core/issues/2535#issuecomment-1712425384 的那堆套件
这是我抓包到的client hello显示的套件
![25(DU9O$BZJKITSVM AE~$V](https://github.com/XTLS/Xray-core/assets/45535409/f735af63-0df0-4d78-be5a-760eb66a565b)

**Comment by architecturers** [comment]
> > > > 
> > > 
> > > 
> > > 说话有歧义指出来说我我听不懂可以走？ 我说的不一定全对 请指出 你说的有错 我指出有问题 各自保留 不是 这是一个很明显有对错的东西 不是什么哲学讨论 错的就是错的 错的还能保留 你可以说唯心主义唯物主义哪个好 这个可以保留 但是你觉得1+1>2 这还保留意见？
> > 
> > 
> > 你连 交换 签名 对称 都没弄清楚 还要掰扯啊 怎么连好赖话都听不清楚啊 你真的是 职业吵架的
> 
> 还是没有说出我哪是错的 只会说我 这没弄清楚 那没弄清楚 啥没弄清楚呢 不知道 到底谁是职业吵架呢
> 
> 请循其本 省略中间的瞎吵吵 看你的标题 "希望增加reality的密钥类型" "现在是单一的密钥类型" 那么我就理解成 ./xray x25519 已经如上所说了 如果你指[#2535 (comment)](https://github.com/XTLS/Xray-core/issues/2535#issuecomment-1712425384) 的那堆套件 这是我抓包到的client hello显示的套件 ![25(DU9O$BZJKITSVM AE~$V](https://user-images.githubusercontent.com/45535409/266765138-f735af63-0df0-4d78-be5a-760eb66a565b.png)

行吧 再回复一句
./xray x25519 生成的是交换密码 建立一个加密通道 用来传输偷的证书 ；在外界看来 就是 ./x25519(交换算法) + 偷的证书（签名）+ 对称算法的结合体 。这个结合体 最好符合用处最广的tls1.3套件 我就是这个意思 目前最广的 套件 是 
rsa+ rsa + 对称 ，第二是 ecdhe+ecdha+对称 ，reality是 x25519+偷的证书+对称。 想要大隐于市 最好是符合市占率最广的套件 。 tls1.3支持几十种套件 ，目前偷的证书 可以自己选 对称算法也算能选吧 就是交换密钥 写死了 。所以我说 加个密钥选择功能 。

**Comment by Fangliding** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 说话有歧义指出来说我我听不懂可以走？ 我说的不一定全对 请指出 你说的有错 我指出有问题 各自保留 不是 这是一个很明显有对错的东西 不是什么哲学讨论 错的就是错的 错的还能保留 你可以说唯心主义唯物主义哪个好 这个可以保留 但是你觉得1+1>2 这还保留意见？
> > > 
> > > 
> > > 你连 交换 签名 对称 都没弄清楚 还要掰扯啊 怎么连好赖话都听不清楚啊 你真的是 职业吵架的
> > 
> > 
> > 还是没有说出我哪是错的 只会说我 这没弄清楚 那没弄清楚 啥没弄清楚呢 不知道 到底谁是职业吵架呢
> > 请循其本 省略中间的瞎吵吵 看你的标题 "希望增加reality的密钥类型" "现在是单一的密钥类型" 那么我就理解成 ./xray x25519 已经如上所说了 如果你指[#2535 (comment)](https://github.com/XTLS/Xray-core/issues/2535#issuecomment-1712425384) 的那堆套件 这是我抓包到的client hello显示的套件 ![25(DU9O$BZJKITSVM AE~$V](https://user-images.githubusercontent.com/45535409/266765138-f735af63-0df0-4d78-be5a-760eb66a565b.png)
> 
> 行吧 再回复一句 ./xray x25519 生成的是交换密码 建立一个加密通道 用来传输偷的证书 ；在外界看来 就是 ./x25519(交换算法) + 偷的证书（签名）+ 对称算法的结合体 。这个结合体 最好符合用处最广的tls1.3套件 我就是这个意思 目前最广的 套件 是 rsa+ rsa + 对称 ，第二是 ecdhe+ecdha+对称 ，reality是 x25519+偷的证书+对称。 想要大隐于市 最好是符合市占率最广的套件 。 tls1.3支持几十种套件 ，目前偷的证书 可以自己选 对称算法也算能选吧 就是交换密钥 写死了 。所以我说 加个密钥选择功能 。

那你对reality的理解就错了 那个东西是用来签发临时可信证书的 外面看到的那个交换算法 和里面的证书的签名算法(我也说过了) 是两个东西 里面哪怕是个AES证书 外面也可以用x25519交换密钥
![G}G9Y@O7UM~L{Y%50} CP59](https://github.com/XTLS/Xray-core/assets/45535409/aa5980bd-a0fc-44ec-82cd-1f2d85f99443)
![WLUI}$TTCMO4MB~$A~3)@JD](https://github.com/XTLS/Xray-core/assets/45535409/132ba04a-bbfd-4671-a515-0aa06febd3ee)

**Comment by architecturers** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 说话有歧义指出来说我我听不懂可以走？ 我说的不一定全对 请指出 你说的有错 我指出有问题 各自保留 不是 这是一个很明显有对错的东西 不是什么哲学讨论 错的就是错的 错的还能保留 你可以说唯心主义唯物主义哪个好 这个可以保留 但是你觉得1+1>2 这还保留意见？
> > > > 
> > > > 
> > > > 你连 交换 签名 对称 都没弄清楚 还要掰扯啊 怎么连好赖话都听不清楚啊 你真的是 职业吵架的
> > > 
> > > 
> > > 还是没有说出我哪是错的 只会说我 这没弄清楚 那没弄清楚 啥没弄清楚呢 不知道 到底谁是职业吵架呢
> > > 请循其本 省略中间的瞎吵吵 看你的标题 "希望增加reality的密钥类型" "现在是单一的密钥类型" 那么我就理解成 ./xray x25519 已经如上所说了 如果你指[#2535 (comment)](https://github.com/XTLS/Xray-core/issues/2535#issuecomment-1712425384) 的那堆套件 这是我抓包到的client hello显示的套件 ![25(DU9O$BZJKITSVM AE~$V](https://user-images.githubusercontent.com/45535409/266765138-f735af63-0df0-4d78-be5a-760eb66a565b.png)
> > 
> > 
> > 行吧 再回复一句 ./xray x25519 生成的是交换密码 建立一个加密通道 用来传输偷的证书 ；在外界看来 就是 ./x25519(交换算法) + 偷的证书（签名）+ 对称算法的结合体 。这个结合体 最好符合用处最广的tls1.3套件 我就是这个意思 目前最广的 套件 是 rsa+ rsa + 对称 ，第二是 ecdhe+ecdha+对称 ，reality是 x25519+偷的证书+对称。 想要大隐于市 最好是符合市占率最广的套件 。 tls1.3支持几十种套件 ，目前偷的证书 可以自己选 对称算法也算能选吧 就是交换密钥 写死了 。所以我说 加个密钥选择功能 。
> 
> 那你对reality的理解就错了 那个东西是用来签发临时可信证书的 外面看到的那个交换算法 和里面的证书的签名算法是两个东西(我也说过了) 里面哪怕是个AES证书 外面也可以用x25519交换密钥 ![G}G9Y@O7UM~L{Y%50} CP59](https://user-images.githubusercontent.com/45535409/266766312-aa5980bd-a0fc-44ec-82cd-1f2d85f99443.png) ![WLUI}$TTCMO4MB~$A~3)@JD](https://user-images.githubusercontent.com/45535409/266766314-132ba04a-bbfd-4671-a515-0aa06febd3ee.png)

哦明白了 原来是让我找错啊
tls1.3 你查一查 支持这几个套件吗 这只是其中的一些 还有很多
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_PSK_WITH_AES_128_GCM_SHA256
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256

**Comment by architecturers** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 说话有歧义指出来说我我听不懂可以走？ 我说的不一定全对 请指出 你说的有错 我指出有问题 各自保留 不是 这是一个很明显有对错的东西 不是什么哲学讨论 错的就是错的 错的还能保留 你可以说唯心主义唯物主义哪个好 这个可以保留 但是你觉得1+1>2 这还保留意见？
> > > > 
> > > > 
> > > > 你连 交换 签名 对称 都没弄清楚 还要掰扯啊 怎么连好赖话都听不清楚啊 你真的是 职业吵架的
> > > 
> > > 
> > > 还是没有说出我哪是错的 只会说我 这没弄清楚 那没弄清楚 啥没弄清楚呢 不知道 到底谁是职业吵架呢
> > > 请循其本 省略中间的瞎吵吵 看你的标题 "希望增加reality的密钥类型" "现在是单一的密钥类型" 那么我就理解成 ./xray x25519 已经如上所说了 如果你指[#2535 (comment)](https://github.com/XTLS/Xray-core/issues/2535#issuecomment-1712425384) 的那堆套件 这是我抓包到的client hello显示的套件 ![25(DU9O$BZJKITSVM AE~$V](https://user-images.githubusercontent.com/45535409/266765138-f735af63-0df0-4d78-be5a-760eb66a565b.png)
> > 
> > 
> > 行吧 再回复一句 ./xray x25519 生成的是交换密码 建立一个加密通道 用来传输偷的证书 ；在外界看来 就是 ./x25519(交换算法) + 偷的证书（签名）+ 对称算法的结合体 。这个结合体 最好符合用处最广的tls1.3套件 我就是这个意思 目前最广的 套件 是 rsa+ rsa + 对称 ，第二是 ecdhe+ecdha+对称 ，reality是 x25519+偷的证书+对称。 想要大隐于市 最好是符合市占率最广的套件 。 tls1.3支持几十种套件 ，目前偷的证书 可以自己选 对称算法也算能选吧 就是交换密钥 写死了 。所以我说 加个密钥选择功能 。
> 
> 那你对reality的理解就错了 那个东西是用来签发临时可信证书的 外面看到的那个交换算法 和里面的证书的签名算法是两个东西(我也说过了) 里面哪怕是个AES证书 外面也可以用x25519交换密钥 ![G}G9Y@O7UM~L{Y%50} CP59](https://user-images.githubusercontent.com/45535409/266766312-aa5980bd-a0fc-44ec-82cd-1f2d85f99443.png) ![WLUI}$TTCMO4MB~$A~3)@JD](https://user-images.githubusercontent.com/45535409/266766314-132ba04a-bbfd-4671-a515-0aa06febd3ee.png)

别和我说go里面只是tls1.2支持
我说的是tls1.3的支持 不是go语言里面的支持

**Comment by Fangliding** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > 说话有歧义指出来说我我听不懂可以走？ 我说的不一定全对 请指出 你说的有错 我指出有问题 各自保留 不是 这是一个很明显有对错的东西 不是什么哲学讨论 错的就是错的 错的还能保留 你可以说唯心主义唯物主义哪个好 这个可以保留 但是你觉得1+1>2 这还保留意见？
> > > > > 
> > > > > 
> > > > > 你连 交换 签名 对称 都没弄清楚 还要掰扯啊 怎么连好赖话都听不清楚啊 你真的是 职业吵架的
> > > > 
> > > > 
> > > > 还是没有说出我哪是错的 只会说我 这没弄清楚 那没弄清楚 啥没弄清楚呢 不知道 到底谁是职业吵架呢
> > > > 请循其本 省略中间的瞎吵吵 看你的标题 "希望增加reality的密钥类型" "现在是单一的密钥类型" 那么我就理解成 ./xray x25519 已经如上所说了 如果你指[#2535 (comment)](https://github.com/XTLS/Xray-core/issues/2535#issuecomment-1712425384) 的那堆套件 这是我抓包到的client hello显示的套件 ![25(DU9O$BZJKITSVM AE~$V](https://user-images.githubusercontent.com/45535409/266765138-f735af63-0df0-4d78-be5a-760eb66a565b.png)
> > > 
> > > 
> > > 行吧 再回复一句 ./xray x25519 生成的是交换密码 建立一个加密通道 用来传输偷的证书 ；在外界看来 就是 ./x25519(交换算法) + 偷的证书（签名）+ 对称算法的结合体 。这个结合体 最好符合用处最广的tls1.3套件 我就是这个意思 目前最广的 套件 是 rsa+ rsa + 对称 ，第二是 ecdhe+ecdha+对称 ，reality是 x25519+偷的证书+对称。 想要大隐于市 最好是符合市占率最广的套件 。 tls1.3支持几十种套件 ，目前偷的证书 可以自己选 对称算法也算能选吧 就是交换密钥 写死了 。所以我说 加个密钥选择功能 。
> > 
> > 
> > 那你对reality的理解就错了 那个东西是用来签发临时可信证书的 外面看到的那个交换算法 和里面的证书的签名算法是两个东西(我也说过了) 里面哪怕是个AES证书 外面也可以用x25519交换密钥 ![G}G9Y@O7UM~L{Y%50} CP59](https://user-images.githubusercontent.com/45535409/266766312-aa5980bd-a0fc-44ec-82cd-1f2d85f99443.png) ![WLUI}$TTCMO4MB~$A~3)@JD](https://user-images.githubusercontent.com/45535409/266766314-132ba04a-bbfd-4671-a515-0aa06febd3ee.png)
> 
> 别和我说go里面只是tls1.2支持 我说的是tls1.3的支持 不是go语言里面的支持



> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > 说话有歧义指出来说我我听不懂可以走？ 我说的不一定全对 请指出 你说的有错 我指出有问题 各自保留 不是 这是一个很明显有对错的东西 不是什么哲学讨论 错的就是错的 错的还能保留 你可以说唯心主义唯物主义哪个好 这个可以保留 但是你觉得1+1>2 这还保留意见？
> > > > > 
> > > > > 
> > > > > 你连 交换 签名 对称 都没弄清楚 还要掰扯啊 怎么连好赖话都听不清楚啊 你真的是 职业吵架的
> > > > 
> > > > 
> > > > 还是没有说出我哪是错的 只会说我 这没弄清楚 那没弄清楚 啥没弄清楚呢 不知道 到底谁是职业吵架呢
> > > > 请循其本 省略中间的瞎吵吵 看你的标题 "希望增加reality的密钥类型" "现在是单一的密钥类型" 那么我就理解成 ./xray x25519 已经如上所说了 如果你指[#2535 (comment)](https://github.com/XTLS/Xray-core/issues/2535#issuecomment-1712425384) 的那堆套件 这是我抓包到的client hello显示的套件 ![25(DU9O$BZJKITSVM AE~$V](https://user-images.githubusercontent.com/45535409/266765138-f735af63-0df0-4d78-be5a-760eb66a565b.png)
> > > 
> > > 
> > > 行吧 再回复一句 ./xray x25519 生成的是交换密码 建立一个加密通道 用来传输偷的证书 ；在外界看来 就是 ./x25519(交换算法) + 偷的证书（签名）+ 对称算法的结合体 。这个结合体 最好符合用处最广的tls1.3套件 我就是这个意思 目前最广的 套件 是 rsa+ rsa + 对称 ，第二是 ecdhe+ecdha+对称 ，reality是 x25519+偷的证书+对称。 想要大隐于市 最好是符合市占率最广的套件 。 tls1.3支持几十种套件 ，目前偷的证书 可以自己选 对称算法也算能选吧 就是交换密钥 写死了 。所以我说 加个密钥选择功能 。
> > 
> > 
> > 那你对reality的理解就错了 那个东西是用来签发临时可信证书的 外面看到的那个交换算法 和里面的证书的签名算法是两个东西(我也说过了) 里面哪怕是个AES证书 外面也可以用x25519交换密钥 ![G}G9Y@O7UM~L{Y%50} CP59](https://user-images.githubusercontent.com/45535409/266766312-aa5980bd-a0fc-44ec-82cd-1f2d85f99443.png) ![WLUI}$TTCMO4MB~$A~3)@JD](https://user-images.githubusercontent.com/45535409/266766314-132ba04a-bbfd-4671-a515-0aa06febd3ee.png)
> 
> 哦明白了 原来是让我找错啊 tls1.3 你查一查 支持这几个套件吗 这只是其中的一些 还有很多 TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 TLS_ECDHE_PSK_WITH_AES_128_GCM_SHA256 TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256

1 你并没有正面回复我给出的解释
2 
![8)0OH 4IUD_1_0@L2P{NN6W](https://github.com/XTLS/Xray-core/assets/45535409/e77f5ca5-a2d0-4991-8cf6-895fa05d4695)
你在 https://github.com/XTLS/Xray-core/issues/2535#issuecomment-1712425384 说的 "go语言的tls1.3" 支持的三个 都赫然在列

**Comment by architecturers** [comment]
好的 谢谢你的回复
