### ISSUE TITLE
grpc acceptProxyProtocol

### ISSUE THREAD

**Issue by mozhutte** [XTLS/Xray-core#2537]
Hello,
Why we don't have acceptProxyProtocol in grpcSettings? How should we get IP of users behind something like CDN in grpc mode?

**Comment by lxhao61** [comment]
使用 sockopt 中 acceptProxyProtocol 来接收代理协议。

**Comment by mozhutte** [comment]
> 可使用 sockopt 的 acceptProxyProtocol 来接收代理协议。

Can you please provide an example for it's inbound?

**Comment by lxhao61** [comment]
[Xray(M+K)](https://github.com/lxhao61/integrated-examples/tree/main/Xray(M%2BK))

**Comment by lxhao61** [comment]
> > 可使用 sockopt 的 acceptProxyProtocol 来接收代理协议。
> 
> Can you please provide an example for it's inbound?

不好意，我上边回答偏题了。我被你 "为什么 grpcSettings 中没有acceptProxyProtocol？" 中 acceptProxyProtocol 误导了。grpc 模式下如何获取 CDN 等用户的 IP 跟是否有这个参数无关，参考 [V2Ray(SS+gRPC)+Nginx\Caddy](https://github.com/lxhao61/integrated-examples/tree/main/V2Ray(SS%2BgRPC)%2BNginx%5CCaddy) 示例。

**Comment by mozhutte** [comment]
I think in this scenario, nginx keeps real IP of the user and not xray itself. Is it true? But I want that real IP of user goes to xray log. Let me know if I'm wrong

**Comment by lxhao61** [comment]
不是。是 Nginx 及 Xray 都保留用户的真实 IP。Nginx 通过 grpc_set_header X-Real-IP $remote_addr 参数同步传递给了 Xray。
