### ISSUE TITLE
tls压缩传输

### ISSUE THREAD

**Issue by Fhokud** [XTLS/Xray-core#254]
在使用tls传输时，使用某种压缩算法压缩数据。
（作为可选项？）

**Comment by SekiBetu** [comment]
从成功攻击TLS的事例中来看，其中使用压缩时的攻击可以捕获到用HTTP头发送的参数，这个攻击可以劫持Cookie，这个漏洞我们称为CRIME。从TLS 1.3开始，协议就禁用了TLS压缩。

**Comment by Fhokud** [comment]
也许可以让压缩算法工作在vless层面？

**Comment by Pix-00** [comment]
理论上不可能（或者说不必要

“压缩”从信息论的角度上讲就是让变换后的消息的长度接近能表达原消息的信息熵的最小长度  从实践的角度上不精确的类似于寻找相似的模式（再不精确一点就是相似的字符串）之后记录并多次引用这些经常重复的模式从而缩减文件体积

“加密”是指消除原始消息的任何特征 甚至是连续两条消息之间的相似部分（不精确的说就是变得不可读）  这也就是说最起码能保证变换后的消息具有统计学意义上的随机性  也就是说这堆东西的信息熵几乎最大  也就是说  理论上不存在有效的算法可以压缩加密后的消息（因为一堆随机bit（不精确的说 随机的乱码）没有“相似的模式”这种东西

VLESS层面拿到的是已经被tls协议加密过的消息  按照上面两条原理  常规情况下（就是说没有国家背书  没有Google Microsoft这种体量的资本扶持  没有图灵和香农这种能开创学科的天才的情况） 几乎不可能做到你想的事情  （这东西做出来大概相当于万能破译机  （这可是真正意义上的万能  ~~才不是刚暴机那种曲解原意的假货~~

所以  我个人认为把时间花在这个想法上... 不是很有效率...

**Comment by rprx** [comment]
最开始设计 VLESS 时有过压缩的想法，后来发现目前绝大多数流量是已经加密过的，趋近于随机数，现有技术无法有效压缩它们。
