### ISSUE TITLE
xray核心修改意见

### ISSUE THREAD

**Issue by yijia10** [XTLS/Xray-core#2541]
上传直连，下载通过Cloudflare的cdn加速。思想轨迹，自家ip上传数据直连自己服务器，自己服务器使用Cloudflare优选ip发送数据到自家ip.实现下载速度成倍增加。实现需要2个uuid上传一个下载一个，还可以伪装任何域名，可以自定义私钥公钥，数据加密更加多样化。第一次异想天开请多多给意见。

**Comment by iKira** [comment]
用路由规则就能实现，认真把官方文档读熟、读透、读烂

https://xtls.github.io/document/level-2/warp.html#%E5%9C%A8%E6%9C%8D%E5%8A%A1%E7%AB%AF%E5%88%86%E6%B5%81%E5%9B%9E%E5%9B%BD%E6%B5%81%E9%87%8F%E8%87%B3%20warp
