### ISSUE TITLE
wireguard over vless is laggy

### ISSUE THREAD

**Issue by its0ka** [XTLS/Xray-core#2544]
im using vless+ws+tls+cdn config and forward port with dokodemo inbound on linux router

{
            "listen": "0.0.0.0",
            "port": 53481,
            "protocol": "dokodemo-door",
            "settings": {
                "address": "127.0.0.1",
                "network": "udp",
                "port": 53481
            }
        }

after connecting to wireguard (with official windows client) on local port the speed is low ~30mbit/sec (should be at least 200mbit/sec) and online games often stutter and report high ping spikes, but sometimes it's smooth and ping is fine, it doesn't matter if i download something in background or not. CPU usage is only ~30% on all cores. 
It's like network just stops working for a second or two and then resumes
it's not my internet because if i use socks it works fine.

**Comment by its0ka** [comment]
![image](https://github.com/XTLS/Xray-core/assets/125186204/eb26e23c-be6a-4ba3-ac14-c96c624ce959)
network is idling, only ping is running

**Comment by its0ka** [comment]
replaced xray client core to sing-box core and it now works fine, 0 lost packets. but sing-box lacks load balancing so it's not a solution for me

**Comment by its0ka** [comment]
sort of solved with https://manpages.ubuntu.com/manpages/focal/en/man1/balance.1.html as i only need round robin load balancing, but speed is even worse now ~7mbit

**Comment by us254** [comment]
Tuning Kernel Parameters: Sometimes, network performance can be improved by tuning certain kernel parameters. For instance, adjusting the values of `net.core.rmem_max, net.core.wmem_max, net.ipv4.tcp_rmem`, and `net.ipv4.tcp`_wmem could potentially help.

**Comment by its0ka** [comment]
@us254 i applied this and sadly no change at all even after rebooting 
https://wiki.archlinux.org/title/sysctl#:~:text=may%20save%20memory-,resources,-%3A

**Comment by its0ka** [comment]
it's fixed now, idk what changed exactly, but wg over xray now works fast and without crazy packet loss

**Comment by zeddit** [comment]
@its0ka hi bro. I am suffering the same issue.
My configuration is wg over vless+ws+tls.
However, in normal case, my connection condition is good, with ping RTT 100ms.
But I don't what happened, some times, the wireguard connection is bad, the ping RTT reaching 5000ms+ and the connection is unstable. This bad condition could not be recovered  by wireguard and xray themselves. I need to `systemctl restart wg0` to reset the interface, then the ping RTT is getting back to 100ms and the connection returns good.

have you ever suffered that problem and could you please give me some advice, thanks.

**Comment by its0ka** [comment]
@zeddit are you sure there is no traffic going through the tunnel when your ping is 5s+?

**Comment by zeddit** [comment]
@its0ka yes, the network layer has no problems. 
if the issue is caused by background traffic, then the problem would be recovered when the background traffic is gone.
