### ISSUE TITLE
NAT Port

### ISSUE THREAD

**Issue by codesaz** [XTLS/Xray-core#2545]
Hello good time

I had a request to write a NAT

i have panel "X-UI" , no access to linux , no access mikrotik and ... only x-ui , ok ?

now , i need to NAT range port to another IP , iam sure it's possible , but i sooo try , and can not do it .

for examle :

ip X-UI = 5.5.5.5

port 443 and 8080 NAT to IP 1.1.1.1

now , when i open 5.5.5.5 , website 1.1.1.1 must be open

**Comment by Smallthing** [comment]
This is not NAT
This is Reverse Proxy

**Comment by codesaz** [comment]
> This is not NAT This is Reverse Proxy

how to do ?


I think when there is data return, it is called a proxy

But the purpose is only to send connections

**Comment by us254** [comment]
If what you want to achieve is forwarding incoming traffic from port 443 and 8080 on IP address 5.5.5.5 to another IP address, then you are indeed looking for a reverse proxy setup, not traditional NAT.Reverse proxy is a more advanced feature than simple NAT/port forwarding.

**Comment by codesaz** [comment]
> If what you want to achieve is forwarding incoming traffic from port 443 and 8080 on IP address 5.5.5.5 to another IP address, then you are indeed looking for a reverse proxy setup, not traditional NAT. Reverse proxy is a more advanced feature than simple NAT/port forwarding.

yes , but nat with linux / mikrotik always sloved my work

now i must do it with xray

can you write the code example for me to test?

**Comment by Smallthing** [comment]
> > If what you want to achieve is forwarding incoming traffic from port 443 and 8080 on IP address 5.5.5.5 to another IP address, then you are indeed looking for a reverse proxy setup, not traditional NAT. Reverse proxy is a more advanced feature than simple NAT/port forwarding.
> 
> yes , but nat with linux / mikrotik always sloved my work
> 
> now i must do it with xray
> 
> can you write the code example for me to test?
> 
> ( i see this document and +6h i try ... not work for me )

mikrotik can do ***NAT*** to make you website accessable is because it's on ***Gateway***
