### ISSUE TITLE
downloads.openwrt.org/releases/packages 的版本仍然停留在 1.8.3-1, 何时会更新到 1.8.4

### ISSUE THREAD

**Issue by yukeiyang** [XTLS/Xray-core#2546]
我关注了很多10多天了，xray-core 版本一直没有更新。譬如：
https://downloads.openwrt.org/releases/packages-22.03/x86_64/packages/

**Comment by Fangliding** [comment]
@yukeiyang 之前好像因为编译问题
打包是那边负责 所以建议去imm那问（）

**Comment by yukeiyang** [comment]
@Fangliding 感谢
