### ISSUE TITLE
runtime: epollcreate failed with 89 fatal error: runtime: netpollinit failed

### ISSUE THREAD

**Issue by iaia1234iaia** [XTLS/Xray-core#2554]
`
@RT-AC66U-81B8:/jffs/Xray-linux-mips32le# /jffs/Xray-linux-mips32le/xray_so
ftfloat uuid
runtime: epollcreate failed with 89
fatal error: runtime: netpollinit failed

goroutine 1 [running, locked to thread]:
runtime.throw({0x1013231, 0x1b})
        runtime/panic.go:1077 +0x54 fp=0x1ca0cbc sp=0x1ca0ca8 pc=0x61864
runtime.netpollinit()
        runtime/netpoll_epoll.go:28 +0x298 fp=0x1ca0d0c sp=0x1ca0cbc pc=0x5c36c
runtime.netpollGenericInit()
        runtime/netpoll.go:216 +0x8c fp=0x1ca0d14 sp=0x1ca0d0c pc=0x5b1ec
internal/poll.runtime_pollServerInit()
        runtime/netpoll.go:208 +0x38 fp=0x1ca0d18 sp=0x1ca0d14 pc=0xa6c70
sync.(*Once).doSlow(0x197c1f0, 0x104adf4)
        sync/once.go:74 +0x114 fp=0x1ca0d40 sp=0x1ca0d18 pc=0xd0828
sync.(*Once).Do(...)
        sync/once.go:65
internal/poll.(*pollDesc).init(0x1c62118, 0x1c62100)
        internal/poll/fd_poll_runtime.go:39 +0x70 fp=0x1ca0d50 sp=0x1ca0d40 pc=0x15969c
internal/poll.(*FD).Init(0x1c62100, {0xff841d, 0x4}, 0x1)
        internal/poll/fd_unix.go:65 +0xb4 fp=0x1ca0d64 sp=0x1ca0d50 pc=0x15a924
os.newFile(0x3, {0x1c3c0c0, 0x28}, 0x1)
        os/file_unix.go:233 +0x1fc fp=0x1ca0d88 sp=0x1ca0d64 pc=0x169990
os.openFileNolog({0x1c3c0c0, 0x28}, 0x0, 0x0)
        os/file_unix.go:301 +0x210 fp=0x1ca0db8 sp=0x1ca0d88 pc=0x169c48
os.OpenFile({0x1c3c0c0, 0x28}, 0x0, 0x0)
        os/file.go:334 +0x70 fp=0x1ca0dd8 sp=0x1ca0db8 pc=0x16800c
os.Open(...)
        os/file.go:314
google.golang.org/protobuf/internal/detrand.binaryHash()
        google.golang.org/protobuf@v1.31.0/internal/detrand/rand.go:46 +0x70 fp=0x1ca0e74 sp=0x1ca0dd8 pc=0x183f30
google.golang.org/protobuf/internal/detrand.init()
        google.golang.org/protobuf@v1.31.0/internal/detrand/rand.go:38 +0x38 fp=0x1ca0e80 sp=0x1ca0e74 pc=0x184308
runtime.doInit1(0x18e21a8)
        runtime/proc.go:6740 +0x148 fp=0x1ca0fa4 sp=0x1ca0e80 pc=0x78458
runtime.doInit(...)
        runtime/proc.go:6707
runtime.main()
        runtime/proc.go:249 +0x4b8 fp=0x1ca0fec sp=0x1ca0fa4 pc=0x65c00
runtime.goexit()
        runtime/asm_mipsx.s:641 +0x4 fp=0x1ca0fec sp=0x1ca0fec pc=0xadbc0

goroutine 2 [force gc (idle)]:
runtime.gopark(0x104ac8c, 0x1967640, 0x11, 0x14, 0x1)
        runtime/proc.go:398 +0x128 fp=0x1c4afd4 sp=0x1c4afc8 pc=0x66128
runtime.goparkunlock(...)
        runtime/proc.go:404
runtime.forcegchelper()
        runtime/proc.go:322 +0x128 fp=0x1c4afec sp=0x1c4afd4 pc=0x65f04
runtime.goexit()
        runtime/asm_mipsx.s:641 +0x4 fp=0x1c4afec sp=0x1c4afec pc=0xadbc0
created by runtime.init.5 in goroutine 1
        runtime/proc.go:310 +0x44

goroutine 3 [GC sweep wait]:
runtime.gopark(0x104ac8c, 0x1968830, 0xc, 0x14, 0x1)
        runtime/proc.go:398 +0x128 fp=0x1c4b7c4 sp=0x1c4b7b8 pc=0x66128
runtime.goparkunlock(...)
        runtime/proc.go:404
runtime.bgsweep(0x1c60000)
        runtime/mgcsweep.go:280 +0xe8 fp=0x1c4b7e4 sp=0x1c4b7c4 pc=0x475f0
runtime.gcenable.func1()
        runtime/mgc.go:200 +0x64 fp=0x1c4b7ec sp=0x1c4b7e4 pc=0x34b9c
runtime.goexit()
        runtime/asm_mipsx.s:641 +0x4 fp=0x1c4b7ec sp=0x1c4b7ec pc=0xadbc0
created by runtime.gcenable in goroutine 1
        runtime/mgc.go:200 +0xb4

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x104ac8c, 0x1968f80, 0xd, 0x14, 0x2)
        runtime/proc.go:398 +0x128 fp=0x1c4bfbc sp=0x1c4bfb0 pc=0x66128
runtime.goparkunlock(...)
        runtime/proc.go:404
runtime.(*scavengerState).park(0x1968f80)
        runtime/mgcscavenge.go:425 +0x98 fp=0x1c4bfd0 sp=0x1c4bfbc pc=0x4389c
runtime.bgscavenge(0x1c60000)
        runtime/mgcscavenge.go:653 +0x74 fp=0x1c4bfe4 sp=0x1c4bfd0 pc=0x4429c
runtime.gcenable.func2()
        runtime/mgc.go:201 +0x64 fp=0x1c4bfec sp=0x1c4bfe4 pc=0x34b28
runtime.goexit()
        runtime/asm_mipsx.s:641 +0x4 fp=0x1c4bfec sp=0x1c4bfec pc=0xadbc0
created by runtime.gcenable in goroutine 1
        runtime/mgc.go:201 +0x114

goroutine 5 [runnable]:
runtime.runfinq()
        runtime/mfinal.go:176 fp=0x1c4c7ec sp=0x1c4c7ec pc=0x335d8
runtime.goexit()
        runtime/asm_mipsx.s:641 +0x4 fp=0x1c4c7ec sp=0x1c4c7ec pc=0xadbc0
created by runtime.createfing in goroutine 1
        runtime/mfinal.go:163 +0x98
ehong@RT-AC66U-81B8:/jffs/Xray-linux-mips32le#
ehong@RT-AC66U-81B8:/jffs/Xray-linux-mips32le# /jffs/Xray-linux-mips32le/xray_so
ftfloat
runtime: epollcreate failed with 89
fatal error: runtime: netpollinit failed

goroutine 1 [running, locked to thread]:
runtime.throw({0x1013231, 0x1b})
        runtime/panic.go:1077 +0x54 fp=0x1c98cbc sp=0x1c98ca8 pc=0x61864
runtime.netpollinit()
        runtime/netpoll_epoll.go:28 +0x298 fp=0x1c98d0c sp=0x1c98cbc pc=0x5c36c
runtime.netpollGenericInit()
        runtime/netpoll.go:216 +0x8c fp=0x1c98d14 sp=0x1c98d0c pc=0x5b1ec
internal/poll.runtime_pollServerInit()
        runtime/netpoll.go:208 +0x38 fp=0x1c98d18 sp=0x1c98d14 pc=0xa6c70
sync.(*Once).doSlow(0x197c1f0, 0x104adf4)
        sync/once.go:74 +0x114 fp=0x1c98d40 sp=0x1c98d18 pc=0xd0828
sync.(*Once).Do(...)
        sync/once.go:65
internal/poll.(*pollDesc).init(0x1c62118, 0x1c62100)
        internal/poll/fd_poll_runtime.go:39 +0x70 fp=0x1c98d50 sp=0x1c98d40 pc=0x15969c
internal/poll.(*FD).Init(0x1c62100, {0xff841d, 0x4}, 0x1)
        internal/poll/fd_unix.go:65 +0xb4 fp=0x1c98d64 sp=0x1c98d50 pc=0x15a924
os.newFile(0x3, {0x1c3e0c0, 0x28}, 0x1)
        os/file_unix.go:233 +0x1fc fp=0x1c98d88 sp=0x1c98d64 pc=0x169990
os.openFileNolog({0x1c3e0c0, 0x28}, 0x0, 0x0)
        os/file_unix.go:301 +0x210 fp=0x1c98db8 sp=0x1c98d88 pc=0x169c48
os.OpenFile({0x1c3e0c0, 0x28}, 0x0, 0x0)
        os/file.go:334 +0x70 fp=0x1c98dd8 sp=0x1c98db8 pc=0x16800c
os.Open(...)
        os/file.go:314
google.golang.org/protobuf/internal/detrand.binaryHash()
        google.golang.org/protobuf@v1.31.0/internal/detrand/rand.go:46 +0x70 fp=0x1c98e74 sp=0x1c98dd8 pc=0x183f30
google.golang.org/protobuf/internal/detrand.init()
        google.golang.org/protobuf@v1.31.0/internal/detrand/rand.go:38 +0x38 fp=0x1c98e80 sp=0x1c98e74 pc=0x184308
runtime.doInit1(0x18e21a8)
        runtime/proc.go:6740 +0x148 fp=0x1c98fa4 sp=0x1c98e80 pc=0x78458
runtime.doInit(...)
        runtime/proc.go:6707
runtime.main()
        runtime/proc.go:249 +0x4b8 fp=0x1c98fec sp=0x1c98fa4 pc=0x65c00
runtime.goexit()
        runtime/asm_mipsx.s:641 +0x4 fp=0x1c98fec sp=0x1c98fec pc=0xadbc0

goroutine 2 [force gc (idle)]:
runtime.gopark(0x104ac8c, 0x1967640, 0x11, 0x14, 0x1)
        runtime/proc.go:398 +0x128 fp=0x1c4afd4 sp=0x1c4afc8 pc=0x66128
runtime.goparkunlock(...)
        runtime/proc.go:404
runtime.forcegchelper()
        runtime/proc.go:322 +0x128 fp=0x1c4afec sp=0x1c4afd4 pc=0x65f04
runtime.goexit()
        runtime/asm_mipsx.s:641 +0x4 fp=0x1c4afec sp=0x1c4afec pc=0xadbc0
created by runtime.init.5 in goroutine 1
        runtime/proc.go:310 +0x44

goroutine 3 [GC sweep wait]:
runtime.gopark(0x104ac8c, 0x1968830, 0xc, 0x14, 0x1)
        runtime/proc.go:398 +0x128 fp=0x1c4b7c4 sp=0x1c4b7b8 pc=0x66128
runtime.goparkunlock(...)
        runtime/proc.go:404
runtime.bgsweep(0x1c60000)
        runtime/mgcsweep.go:280 +0xe8 fp=0x1c4b7e4 sp=0x1c4b7c4 pc=0x475f0
runtime.gcenable.func1()
        runtime/mgc.go:200 +0x64 fp=0x1c4b7ec sp=0x1c4b7e4 pc=0x34b9c
runtime.goexit()
        runtime/asm_mipsx.s:641 +0x4 fp=0x1c4b7ec sp=0x1c4b7ec pc=0xadbc0
created by runtime.gcenable in goroutine 1
        runtime/mgc.go:200 +0xb4

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x104ac8c, 0x1968f80, 0xd, 0x14, 0x2)
        runtime/proc.go:398 +0x128 fp=0x1c4bfbc sp=0x1c4bfb0 pc=0x66128
runtime.goparkunlock(...)
        runtime/proc.go:404
runtime.(*scavengerState).park(0x1968f80)
        runtime/mgcscavenge.go:425 +0x98 fp=0x1c4bfd0 sp=0x1c4bfbc pc=0x4389c
runtime.bgscavenge(0x1c60000)
        runtime/mgcscavenge.go:653 +0x74 fp=0x1c4bfe4 sp=0x1c4bfd0 pc=0x4429c
runtime.gcenable.func2()
        runtime/mgc.go:201 +0x64 fp=0x1c4bfec sp=0x1c4bfe4 pc=0x34b28
runtime.goexit()
        runtime/asm_mipsx.s:641 +0x4 fp=0x1c4bfec sp=0x1c4bfec pc=0xadbc0
created by runtime.gcenable in goroutine 1
        runtime/mgc.go:201 +0x114

goroutine 5 [runnable]:
runtime.runfinq()
        runtime/mfinal.go:176 fp=0x1c4c7ec sp=0x1c4c7ec pc=0x335d8
runtime.goexit()
        runtime/asm_mipsx.s:641 +0x4 fp=0x1c4c7ec sp=0x1c4c7ec pc=0xadbc0
created by runtime.createfing in goroutine 1
        runtime/mfinal.go:163 +0x98
`

**Comment by iaia1234iaia** [comment]
```
@RT-AC66U-81B8:/jffs/Xray-linux-mips32# /jffs/Xray-linux-mips32/xray uuid
/jffs/Xray-linux-mips32/xray: line 1:EL: not found
/jffs/Xray-linux-mips32/xray: line 2: syntax error: unexpected "("

```

**Comment by us254** [comment]
```
sudo nano /etc/sysctl.conf
```
Add the following line:
```
fs.file-max=500000
```
Save the file and exit the text editor.

To apply the changes, run the following command:
```
sudo sysctl -p
```

**Comment by us254** [comment]
The error messages you're seeing are coming from the Go runtime. They're indicating that the runtime is failing to initialize network polling (netpollinit) because the creation of an epoll instance (epollcreate) is failing with error code 89.

The error code 89 corresponds to `ENOSYS` in Linux, which means that the kernel you're using doesn't implement the system call you're trying to use. In this case, the system call is `epoll_create`, which is used for network I/O in Go.

This error typically happens when you're using an old version of the Linux kernel that does not support the `epoll_create` system call, or when the Go runtime doesn't correctly detect the system capabilities.

To fix this issue, you can try the following:

1. **Update your Linux kernel**: If you're using an old version of the Linux kernel, updating to a newer version that supports `epoll_create` might solve the problem. However, since you're using a specific device (RT-AC66U router), this might not be possible if the device manufacturer doesn't provide updates or if the device hardware doesn't support newer kernel versions.

2. **Use a different Go version**: The Go runtime's network polling implementation can vary between different Go versions. If you're using an older Go version, updating to a newer version might help. Conversely, if you're using a newer Go version, switching to an older version that uses a different network polling implementation might solve the issue.

3. **Change your Go build parameters**: When building your Go program, you can use the `GOOS` and `GOARCH` environment variables to specify the target operating system and architecture. Make sure these are set correctly for your target device. You might need to cross-compile your Go program on a different system with the correct `GOOS` and `GOARCH` values.

**Comment by Fangliding** [comment]
no config
