### ISSUE TITLE
[BUG] win环境 + ss + 2022-blake3-chacha20-poly1305 无法连接

### ISSUE THREAD

**Issue by xcanwin** [XTLS/Xray-core#2559]
作者你好，windows环境客户端在以下第6个场景存在bug，无法连接服务端，并且日志没有任何异常，谢谢：
1. 客户端为```MacOS```，protocol为```shadowsocks```，method为```chacha20-ietf-poly1305```时，可以连接服务端。
2. 客户端为```手机```，protocol为```shadowsocks```，method为```chacha20-ietf-poly1305```时，可以连接服务端。
3. 客户端为```Windows```，protocol为```shadowsocks```，method为```chacha20-ietf-poly1305```时，可以连接服务端。
4. 客户端为```MacOS```，protocol为```shadowsocks```，method为```2022-blake3-chacha20-poly1305```时，可以连接服务端。
5. 客户端为```手机```，protocol为```shadowsocks```，method为```2022-blake3-chacha20-poly1305```时，可以连接服务端。
6. 客户端为```Windows```，protocol为```shadowsocks```，method为```2022-blake3-chacha20-poly1305```时，**无法连接服务端**。

**Comment by xcanwin** [comment]
版本是1.8.4

**Comment by chise0713** [comment]
配置文件丢出来看看

**Comment by xcanwin** [comment]
> 配置文件丢出来看看

谢谢回复，在复制配置文件出来时突然找到原因了，```2022-blake3-chacha20-poly1305``` 必须客户端系统时间与服务端系统时间相同，之前windows的时间晚了90秒，设置一样后连接成功。
