### ISSUE TITLE
新代码编译后无法连接，替换官方发布的1.84版本没有问题

### ISSUE THREAD

**Issue by right0808** [XTLS/Xray-core#2560]
错误如下：
2023/09/15 18:18:48 [Info] [2069953534] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to transfer request payload > proxy: failed to process response > local error: tls: bad record MAC
2023/09/15 18:18:48 [Info] [2899512125] proxy/vless/inbound: firstLen = 1186
2023/09/15 18:18:48 [Info] [2899512125] proxy/vless/inbound: received request for tcp:alive.github.com:443
2023/09/15 18:18:48 [Info] [2899512125] proxy/vless/encoding: Xtls Unpadding new block0 16 content 612 padding 503 0
2023/09/15 18:18:48 [Info] [2899512125] proxy/vless/encoding: XtlsFilterTls found tls client hello! 612
2023/09/15 18:18:48 [Info] [2899512125] app/dispatcher: sniffed domain: alive.github.com
2023/09/15 18:18:48 [Info] [2899512125] app/dispatcher: default route for tcp:alive.github.com:443
2023/09/15 18:18:48 [Info] [2899512125] transport/internet/tcp: dialing TCP to tcp:alive.github.com:443
2023/09/15 18:18:49 [Info] [2899512125] proxy/freedom: connection opened to tcp:alive.github.com:443, local endpoint 10.0.8.17:58250, remote endpoint 140.82.113.26:443
2023/09/15 18:18:49 [Info] [2899512125] proxy: CopyRawConn readv
2023/09/15 18:18:49 [Info] [2899512125] proxy/vless/encoding: XtlsFilterTls found tls 1.3! 2819 TLS_AES_128_GCM_SHA256
2023/09/15 18:18:49 [Info] [2899512125] proxy/vless/encoding: XtlsPadding 2819 6 0
2023/09/15 18:18:49 [Info] [2899512125] proxy/vless/encoding: Xtls Unpadding new block0 0 content 64 padding 1325 0
2023/09/15 18:18:49 [Info] [2899512125] proxy/vless/encoding: Xtls Unpadding new block0 0 content 1094 padding 179 2
2023/09/15 18:18:49 [Info] [2899512125] proxy: CopyRawConn readv
2023/09/15 18:18:49 [Info] [2899512125] proxy/vless/encoding: XtlsPadding 158 1012 2
2023/09/15 18:18:49 [Info] [2899512125] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to transfer request payload > proxy: failed to process response > local error: tls: bad record MAC
2023/09/15 18:18:49 [Info] [1461219637] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > context canceled
2023/09/15 18:18:51 [Info] [13013093] proxy/vless/inbound: firstLen = 0
2023/09/15 18:18:51 [Info] [13013093] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly
2023/09/15 18:18:51 [Info] [13013093] proxy/vless/inbound: realName = ss.111111.xyz
2023/09/15 18:18:51 [Info] [13013093] proxy/vless/inbound: realAlpn = h2

**Comment by right0808** [comment]
2023/09/15 18:18:49 [Info] [2899512125] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to transfer request payload > proxy: failed to process response > local error: tls: bad record MAC
2023/09/15 18:18:49 [Info] [1461219637] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > context canceled

**Comment by chika0801** [comment]
https://github.com/XTLS/Xray-core/commit/efd32b0fb2a4f1b2d2e98b21916cfd9aa0e0b497#commitcomment-127240176

bug

**Comment by chika0801** [comment]
https://github.com/XTLS/Xray-core/commit/585d5ba7c8b64f6da60837546a70bbcfd2350c64

我测试了，是已修复
