### ISSUE TITLE
Improving Xray-core Performance with Kernel TLS

### ISSUE THREAD

**Issue by Alion548** [XTLS/Xray-core#2565]
Transport Layer Security (TLS) is an extremely popular cryptography protocol. Implementing TLS in the kernel (kTLS) improves performance by significantly reducing the need for copying operations between user space and the kernel.

https://docs.kernel.org/networking/tls.html
https://www.nginx.com/blog/improving-nginx-performance-with-kernel-tls/

**Comment by Fangliding** [comment]
When they finish it
