### ISSUE TITLE
Commit 585d5ba 问题

### ISSUE THREAD

**Issue by VariatezzZ** [XTLS/Xray-core#2567]
使用 curl 访问 https://github.com ，不用浏览器了，因为日志刷的太快。日志如下

**Client:**
2023/09/18 08:39:20 [Info] [3898921635] proxy/socks: TCP Connect request to tcp:20.205.243.166:443
2023/09/18 08:39:20 [Info] [3898921635] app/dispatcher: taking detour [outbound_vless-tcp-tls] for [tcp:20.205.243.166:443]
2023/09/18 08:39:20 [Info] [3898921635] transport/internet/tcp: dialing TCP to tcp:example.com:12345
2023/09/18 08:39:20 [Info] app/dns: returning 1 IP(s) for domain example.com -> [[]]
2023/09/18 08:39:20 [Info] transport/internet: replace destination with tcp:[]:12345
2023/09/18 08:39:20 [Info] [3898921635] proxy/vless/outbound: tunneling request to tcp:20.205.243.166:443 via example.com:12345
2023/09/18 08:39:20 [Info] [3898921635] proxy: XtlsFilterTls found tls client hello! 517
2023/09/18 08:39:20 [Info] [3898921635] proxy: XtlsPadding 517 456 0
2023/09/18 08:39:21 [Info] [3898921635] proxy: Xtls Unpadding new block, content 2814 padding 108 command 0
2023/09/18 08:39:21 [Info] [3898921635] proxy: XtlsFilterTls found tls 1.3! 1163 TLS_AES_128_GCM_SHA256
2023/09/18 08:39:21 [Info] [3898921635] proxy: XtlsPadding 64 917 0
2023/09/18 08:39:21 [Info] [3898921635] proxy: XtlsPadding 86 890 2
2023/09/18 08:39:21 [Info] [3898921635] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled

**Server:**
2023/09/18 08:39:20 [Info] [2551353627] proxy/vless/inbound: firstLen = 1038
2023/09/18 08:39:20 [Info] [2551353627] proxy/vless/inbound: received request for tcp:20.205.243.166:443
2023/09/18 08:39:20 [Info] [2551353627] app/dispatcher: default route for tcp:20.205.243.166:443
2023/09/18 08:39:20 [Info] [2551353627] transport/internet/tcp: dialing TCP to tcp:20.205.243.166:443
2023/09/18 08:39:20 [Info] [2551353627] proxy: Xtls Unpadding new block, content 517 padding 456 command 0
2023/09/18 08:39:20 [Info] [2551353627] proxy: XtlsFilterTls found tls client hello! 517
2023/09/18 08:39:21 [Info] [2551353627] proxy/freedom: connection opened to tcp:20.205.243.166:443, local endpoint 209.141.45.161:46434, remote endpoint 20.205.243.166:443
2023/09/18 08:39:21 [Info] [2551353627] proxy: CopyRawConn readv
2023/09/18 08:39:21 [Info] [2551353627] proxy: XtlsFilterTls found tls 1.3! 2814 TLS_AES_128_GCM_SHA256
2023/09/18 08:39:21 [Info] [2551353627] proxy: XtlsPadding 2814 108 0
2023/09/18 08:39:21 [Info] [2551353627] proxy: Xtls Unpadding new block, content 64 padding 917 command 0
2023/09/18 08:39:21 [Info] [2551353627] proxy: Xtls Unpadding new block, content 86 padding 890 command 2
2023/09/18 08:39:21 [Info] [2551353627] proxy: CopyRawConn readv
2023/09/18 08:39:21 [Info] [2551353627] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > context canceled

@yuhan6665

**Comment by chika0801** [comment]
具体现象是什么？比如浏览器打不开网站？

**Comment by VariatezzZ** [comment]
> 具体现象是什么？比如浏览器打不开网站？

见 https://github.com/XTLS/Xray-core/commit/585d5ba7c8b64f6da60837546a70bbcfd2350c64#commitcomment-127601381

**Comment by yuhan6665** [comment]
应该修好了
