### ISSUE TITLE
新版本，编译后，vision无法连接，错误如下

### ISSUE THREAD

**Issue by right0808** [XTLS/Xray-core#2569]
2023/09/18 11:54:28 [Info] [2067346808] proxy/vless/inbound: firstLen = 0
2023/09/18 11:54:28 [Info] [2067346808] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly
2023/09/18 11:54:28 [Info] [2067346808] proxy/vless/inbound: realName =
2023/09/18 11:54:28 [Info] [2067346808] proxy/vless/inbound: realAlpn =
2023/09/18 11:54:28 [Info] [2067346808] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > tls: no certificates configured
2023/09/18 11:54:29 [Info] [3389893111] proxy/vless/inbound: firstLen = 0
2023/09/18 11:54:29 [Info] [3389893111] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly
2023/09/18 11:54:29 [Info] [3389893111] proxy/vless/inbound: realName =
2023/09/18 11:54:29 [Info] [3389893111] proxy/vless/inbound: realAlpn =
2023/09/18 11:54:29 [Info] [3389893111] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > tls: no certificates configured
2023/09/18 11:54:29 [Info] [751923967] proxy/vless/inbound: firstLen = 0
2023/09/18 11:54:29 [Info] [751923967] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly
2023/09/18 11:54:29 [Info] [751923967] proxy/vless/inbound: realName =
2023/09/18 11:54:29 [Info] [751923967] proxy/vless/inbound: realAlpn =
2023/09/18 11:54:29 [Info] [751923967] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > tls: first record does not look like a TLS handshake
2023/09/18 11:54:29 [Info] [3553170250] proxy/vless/inbound: firstLen = 0
2023/09/18 11:54:29 [Info] [3553170250] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly
2023/09/18 11:54:29 [Info] [3553170250] proxy/vless/inbound: realName =
2023/09/18 11:54:29 [Info] [3553170250] proxy/vless/inbound: realAlpn =
2023/09/18 11:54:29 [Info] [3553170250] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > tls: no certificates configured

**Comment by chika0801** [comment]
是 vless vision tls 的组合配置吗？

**Comment by right0808** [comment]
对，tls + xtls-rprx-vision

**Comment by right0808** [comment]
再次测试了下，错误如下：
2023/09/18 12:24:36 [Info] [117015213] proxy: CopyRawConn readv
2023/09/18 12:24:36 [Info] [117015213] proxy: XtlsFilterTls found tls 1.3! 2819 TLS_AES_128_GCM_SHA256
2023/09/18 12:24:36 [Info] [117015213] proxy: XtlsPadding 2819 141 0
2023/09/18 12:24:36 [Info] [117015213] proxy: Xtls Unpadding new block, content 64 padding 1299 command 0
2023/09/18 12:24:36 [Info] [117015213] proxy: Xtls Unpadding new block, content 1097 padding 239 command 2
2023/09/18 12:24:36 [Info] [117015213] proxy: CopyRawConn readv
2023/09/18 12:24:37 [Info] [117015213] proxy: XtlsPadding 79 1193 0
2023/09/18 12:24:37 [Info] [117015213] proxy: XtlsPadding 79 976 2
2023/09/18 12:24:37 [Info] [117015213] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to transfer request payload > proxy: failed to process response > local error: tls: bad record MAC
2023/09/18 12:24:38 [Info] [1770214269] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > context canceled
2023/09/18 12:24:38 [Info] [2222312282] proxy/vless/inbound: firstLen = 1186
2023/09/18 12:24:38 [Info] [2222312282] proxy/vless/inbound: received request for tcp:clients4.google.com:443
2023/09/18 12:24:38 [Info] [2222312282] proxy: Xtls Unpadding new block, content 997 padding 129 command 0
2023/09/18 12:24:38 [Info] [2222312282] proxy: XtlsFilterTls found tls client hello! 997
2023/09/18 12:24:38 [Info] [2222312282] app/dispatcher: sniffed domain: clients4.google.com
2023/09/18 12:24:38 [Info] [2222312282] app/dispatcher: default route for tcp:clients4.google.com:443
2023/09/18 12:24:38 [Info] [2222312282] transport/internet/tcp: dialing TCP to tcp:clients4.google.com:443
2023/09/18 12:24:38 [Info] [2222312282] proxy/freedom: connection opened to tcp:clients4.google.com:443, local endpoint 10.0.8.17:46294, remote endpoint 142.251.42.238:443
2023/09/18 12:24:38 [Info] [2222312282] proxy: CopyRawConn readv
2023/09/18 12:24:38 [Info] [2222312282] proxy: XtlsFilterTls found tls 1.3! 5600 TLS_AES_128_GCM_SHA256
2023/09/18 12:24:38 [Info] [2222312282] proxy: XtlsPadding 5600 220 0
2023/09/18 12:24:38 [Info] [2222312282] proxy: XtlsPadding 1340 29 0
2023/09/18 12:24:38 [Info] [2222312282] proxy: Xtls Unpadding new block, content 74 padding 907 command 0
2023/09/18 12:24:38 [Info] [2222312282] proxy: Xtls Unpadding new block, content 98 padding 1167 command 2
2023/09/18 12:24:38 [Info] [2222312282] proxy: CopyRawConn readv
2023/09/18 12:24:38 [Info] [2222312282] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to transfer request payload > proxy: failed to process response > local error: tls: bad record MAC
2023/09/18 12:24:41 [Info] [2781066417] proxy/vless/inbound: firstLen = 1186
2023/09/18 12:24:41 [Info] [2781066417] proxy/vless/inbound: received request for tcp:www.youtube.com:443
2023/09/18 12:24:41 [Info] [2781066417] proxy: Xtls Unpadding new block, content 567 padding 725 command 0
2023/09/18 12:24:41 [Info] [2781066417] proxy: XtlsFilterTls found tls client hello! 567
2023/09/18 12:24:41 [Info] [2781066417] app/dispatcher: sniffed domain: www.youtube.com
2023/09/18 12:24:41 [Info] [2781066417] app/dispatcher: default route for tcp:www.youtube.com:443
2023/09/18 12:24:41 [Info] [2781066417] transport/internet/tcp: dialing TCP to tcp:www.youtube.com:443
2023/09/18 12:24:41 [Info] [2781066417] proxy/freedom: connection opened to tcp:www.youtube.com:443, local endpoint 10.0.8.17:52908, remote endpoint 172.217.160.78:443
2023/09/18 12:24:41 [Info] [2781066417] proxy: CopyRawConn readv
2023/09/18 12:24:41 [Info] [2781066417] proxy: XtlsFilterTls found tls 1.3! 6935 TLS_AES_128_GCM_SHA256
2023/09/18 12:24:41 [Info] [2781066417] proxy: XtlsPadding 6935 241 0
2023/09/18 12:24:41 [Info] [2781066417] proxy: Xtls Unpadding new block, content 74 padding 1192 command 0
2023/09/18 12:24:41 [Info] [2781066417] proxy: Xtls Unpadding new block, content 98 padding 839 command 2
2023/09/18 12:24:41 [Info] [2781066417] proxy: CopyRawConn readv
2023/09/18 12:24:41 [Info] [2781066417] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to transfer request payload > proxy: failed to process response > local error: tls: bad record MAC
2023/09/18 12:24:41 [Info] [266459536] proxy/vless/inbound: firstLen = 1186
2023/09/18 12:24:41 [Info] [266459536] proxy/vless/inbound: received request for tcp:alive.github.com:443
2023/09/18 12:24:41 [Info] [266459536] proxy: Xtls Unpadding new block, content 644 padding 658 command 0
2023/09/18 12:24:41 [Info] [266459536] proxy: XtlsFilterTls found tls client hello! 644
2023/09/18 12:24:41 [Info] [266459536] app/dispatcher: sniffed domain: alive.github.com
2023/09/18 12:24:41 [Info] [266459536] app/dispatcher: default route for tcp:alive.github.com:443
2023/09/18 12:24:41 [Info] [266459536] transport/internet/tcp: dialing TCP to tcp:alive.github.com:443
2023/09/18 12:24:41 [Info] [266459536] proxy/freedom: connection opened to tcp:alive.github.com:443, local endpoint 10.0.8.17:38172, remote endpoint 140.82.112.25:443
2023/09/18 12:24:41 [Info] [266459536] proxy: CopyRawConn readv
2023/09/18 12:24:42 [Info] [266459536] proxy: XtlsFilterTls found tls 1.3! 2820 TLS_AES_128_GCM_SHA256
2023/09/18 12:24:42 [Info] [266459536] proxy: XtlsPadding 2820 211 0
2023/09/18 12:24:42 [Info] [266459536] proxy: Xtls Unpadding new block, content 64 padding 1232 command 0
2023/09/18 12:24:42 [Info] [266459536] proxy: Xtls Unpadding new block, content 1097 padding 107 command 2
2023/09/18 12:24:42 [Info] [266459536] proxy: CopyRawConn readv
2023/09/18 12:24:42 [Info] [266459536] proxy: XtlsPadding 158 927 2
2023/09/18 12:24:42 [Info] [266459536] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to transfer request payload > proxy: failed to process response > local error: tls: bad record MAC

**Comment by right0808** [comment]
failed to transfer request payload > proxy: failed to process response > local error: tls: bad record MAC

**Comment by chika0801** [comment]
https://github.com/XTLS/Xray-core/issues/2567

这个也是用vless vision tcp 应该是bug

**Comment by right0808** [comment]
应该是bug，上上两个版本是没有问题的。

**Comment by hqvv** [comment]
遇到相同问题，Vision 不能用了。 折腾了半天 还以为是我的服务器被ban了...

**Comment by qist** [comment]
更新到最新版本编译应该好了。昨天我看无法就自己编译就好了。

**Comment by hqvv** [comment]
> 更新到最新版本编译应该好了。昨天我看无法就自己编译就好了。

我也测试了，编译了新版客户端可以用了。只是不知道是否需要替换服务器端

**Comment by chika0801** [comment]
两端都为 585d5ba 时
1. 用 VISION TLS 出现访问`TLS1.3`的网站打不开，`1.2`或`http://IP` `SSH`等是正常的。
2. 用 VISION REALITY 偷自己 时，无上述现象。

客户端为 585d5ba ，服务端为 1.8.4 时，无故障

**Comment by us254** [comment]
have successfully updated both the server and client to commit `585d5ba`.

As a result, `Reality_TCP_xtls-rprx-vision` is now functioning correctly without any connection issues.

**Comment by yuhan6665** [comment]
确实我发现只测试了reality ;)
感谢大家 我这两天再看下

**Comment by right0808** [comment]
@yuhan6665 谢谢：）

**Comment by yuhan6665** [comment]
应该修好了
