### ISSUE TITLE
配置文件通过json,yaml,toml转成了Go Struct，然后又转成Protobuf Struct是不是有点多余?

### ISSUE THREAD

**Issue by ansoda** [XTLS/Xray-core#257]
配置文件通过json,yaml,toml转成了Go Struct，然后又转成Protobuf Struct是不是有点多余?是不是可以把Protobuf这部分转换删除掉？

**Comment by AkinoKaede** [comment]
这是 V2Ray 历来已久的问题，根据 rprx 的描述，将在 Xray-next 中完成这项工作

**Comment by ansoda** [comment]
好的，谢谢。
