### ISSUE TITLE
"TLS + Vision + Fallback" vs "REALITY with steal oneself"

### ISSUE THREAD

**Issue by AmirHosseinCV** [XTLS/Xray-core#2578]
There is a new tutorial mentioned in the README, titled "[Xray REALITY with 'steal oneself' (English)](https://computerscot.github.io/vless-xtls-utls-reality-steal-oneself.html)".
I would like to know that what is the difference between this approach and using TLS + vision + fallback directly.

**Comment by chika0801** [comment]
Using REALITY to Steal Yourself

1 Requires the client to use uTLS to emulate a fingerprint. (Requirements from REALITY)
2 Stealing yourself is using your own ssl certificate that you applied for and put on top of your vps locally. It's easier to control yourself than just using REALITY DEST to fill in someone else's URL. (e.g. certificate expired, someone else's url malfunctioned)

**Comment by AmirHosseinCV** [comment]
Yes, I'm using this approach now, but using "TLS + Vision + Fallback" seems to be faster. I would like to know why shouldn't I use "TLS + Vision + Fallback" instead of reality with my own domain.

**Comment by chika0801** [comment]
As for the 2 combinations there is no difference in speed when I use them myself.

If you are not in mainland China and not looking for something very new. Your vps proxy node you use for 1 person yourself not for many friends (your region is not blocked badly). Based on this logic, you don't need to have to steal yourself with REALITY (and you said you feel slower with it)

**Comment by AmirHosseinCV** [comment]
Thanks for your response. I live in Iran, which has the worst censorship ever (they even block legal websites with high traffic). So, based on your description, reality with 'steal yourself' is the best choice.

**Comment by AmirHosseinCV** [comment]
I will certainly give them a try. Your assistance is greatly appreciated, and I wish you the best of luck! ❤️

**Comment by chika0801** [comment]
https://github.com/net4people/bbs/issues/277

You can refer to what is discussed in this one link
