### ISSUE TITLE
implement regex serverNames in reality config

### ISSUE THREAD

**Issue by its0ka** [XTLS/Xray-core#2580]
server example:
"serverNames": ["*.google.com"]

client example:
"serverName": ["anything.google.com"]

to make any subdomain for google.com work
at least like this and not full regex

**Comment by its0ka** [comment]
something like 
[random*4].google.com
on the client side to make a random string of 4 symbols would also be cool

**Comment by chika0801** [comment]
The use of this parameter is not supported on the server side *
