### ISSUE TITLE
魔改wireguard协议

### ISSUE THREAD

**Issue by do02fw** [XTLS/Xray-core#2581]
有个建议，魔改wireguard协议，目前所有的协议都是proxy，不能算vpn，而且tun也不是很好，wireguard是开源的，而且代码少，速度快，缺点是被识别了，希望开源推出魔改的wireguard协议，防止识别那种。proxy真的不适合全局代理，传输UDP太慢了。

**Comment by Fangliding** [comment]
@do02fw 全局的人一大堆直接给你全拍死了 你要用udp传输啥。。。

**Comment by do02fw** [comment]
> @do02fw 全局的人一大堆直接给你全拍死了 你要用udp传输啥。。。

http3是UDP协议，很多网站都是HTTP3了，比如pixiv p站，还有Google的网站，还有使用了cloudflare 的网站，都是HTTP3

**Comment by Fangliding** [comment]
@do02fw 也有h2啊（

**Comment by do02fw** [comment]
> @do02fw 也有h2啊（

h2没h3快没h3好

**Comment by Caiminoyume** [comment]
> proxy真的不适合全局代理，传输UDP太慢了。

@Fangliding 我觉得他是想要一个基于IP层代理的协议，伪装成TLS/QUIC即可

**Comment by chika0801** [comment]
这里不受理非Xray-core相关的问题，建议你关了这个ISS吧。

**Comment by Fangliding** [comment]
@do02fw 实际上连IETF和谷歌都不知道到底哪个快 h3动不动就回退回h2 在被xray代理的环境下 就h2更好 那就选h2 发明quic的目的就是为了找个更快的连接方式 为了h3而h3多少就有点本末倒置了
说这么多其实也就说明一下必要性真不高 排的比这优先的一大堆 还是那句话 你行你上（
