### ISSUE TITLE
app/proxyman/inbound: connection ends > proxy/http: failed to read http request > malformed HTTP request "\x05\x01\x00"

### ISSUE THREAD

**Issue by mttbx** [XTLS/Xray-core#2587]
The waring given by xray

**Comment by SakuraSakuraSakuraChan** [comment]
@mttbx Are u sure that's a legitimate request

**Comment by mttbx** [comment]
I don't know, but something seems wrong.

**Comment by us254** [comment]
The "\x05\x01\x00" part of the error message suggests that the client might be sending a SOCKS5 handshake instead of an HTTP request. SOCKS5 is a protocol used for proxy servers, and its handshakes start with "\x05". Ensure the client is sending an HTTP request and not a SOCKS5 or other types of non-HTTP requests.

**Comment by mttbx** [comment]
I just copy the config from online doc. I don't know why it happened.

**Comment by EvgenyNerush** [comment]
I have warning
```
app/proxyman/inbound: connection ends > proxy/http: connection ends > context canceled
```
when I try to use xray client with TorBrowser which hence can't connect. At the same time Firefox connects easily with the same proxy settings.

**Comment by ImanHz** [comment]
I got to this error when mistakenly set socks proxy with http port, i.e. 2081.

**Comment by EvgenyNerush** [comment]
I have set `"routeOnly": true` in sniffing objects (both client and server), and now Tor Browser works fine (via a bridge).

**Comment by shink** [comment]
same error

**Comment by berbunda** [comment]
I had same problem when i tried to set route-settings in client config.
I deleted it and change localhost port for socks5 to 6666
then it had work

**Comment by qigaowei** [comment]
其实是端口被占用了，检查端口试试
