### ISSUE TITLE
为出站代理添加 proxy protocol 支持

### ISSUE THREAD

**Issue by cxy930123** [XTLS/Xray-core#2590]
使用 Freedom 出站代理，设置 `redirect` 将请求转发到 nginx 服务器，nginx 无法获取客户端真实 IP。所以，可否为出站代理添加 proxy protocol 支持呢？

**Comment by qist** [comment]
sockopt acceptProxyProtocol 就是

**Comment by cxy930123** [comment]
> sockopt acceptProxyProtocol 就是

这个设置只对 inbound 有效，我想要的是对 outbound 有效

**Comment by iKira** [comment]
> > sockopt acceptProxyProtocol 就是
> 
> 这个设置只对 inbound 有效，我想要的是对 outbound 有效

你没有认真看文档。

**Comment by cxy930123** [comment]
> > > sockopt acceptProxyProtocol 就是
> > 
> > 这个设置只对 inbound 有效，我想要的是对 outbound 有效
> 
> 你没有认真看文档。

文档里明确写着仅用于inbound。

https://xtls.github.io/config/transport.html#sockoptobject

![IMG_20230926_165559.jpg](https://github.com/XTLS/Xray-core/assets/7006257/6fbd76cf-e341-4035-a1ef-e4f434462c9e)

**Comment by iKira** [comment]
> protocol

你看得还不够彻底。

> 
> https://xtls.github.io/config/transport.html#sockoptobject
> 
> 传输方式（transport）配置有两部分：
> 1. 全局配置（TransportObject）
> 2. 局部配置（StreamSettingsObject）
> 局部配置时,可以指定每个单独的入站或出站用怎样的方式传输。
>   "sockopt": {
>     "mark": 0,
>     "tcpFastOpen": false,
>     "tproxy": "off",
>     "domainStrategy": "AsIs",
>     "dialerProxy": "",
>     **"acceptProxyProtocol": false,**
>     "tcpKeepAliveInterval": 0
>   }

**Comment by cxy930123** [comment]
> > protocol
> 
> 你看得还不够彻底。
> 
> > https://xtls.github.io/config/transport.html#sockoptobject
> > 传输方式（transport）配置有两部分：
> > 
> > 1. 全局配置（TransportObject）
> > 2. 局部配置（StreamSettingsObject）
> >    局部配置时,可以指定每个单独的入站或出站用怎样的方式传输。
> >    "sockopt": {
> >    "mark": 0,
> >    "tcpFastOpen": false,
> >    "tproxy": "off",
> >    "domainStrategy": "AsIs",
> >    "dialerProxy": "",
> >    **"acceptProxyProtocol": false,**
> >    "tcpKeepAliveInterval": 0
> >    }

是有两部分，但无论是全局配置的 `transport.tcpSettings.acceptProxyProtocol`，还是局部设置的 `streamSettings.sockopt.acceptProxyProtocol`，都只对 `inbound` 有效，指示是否**接收** PROXY protocol，在 `outbound` 里是无效的。

而我想要的是针对 `outbound` 的设置，在 `outbound` 转发流量时 **发送**  PROXY protocol。

**Comment by wyx2685** [comment]
@cxy930123 目前没有这种东西，适用面太狭窄了，不妨考虑换个搭建结构不要用freedom转到nginx

**Comment by iKira** [comment]
> > > protocol
> > 
> > 
> > 你看得还不够彻底。
> > > https://xtls.github.io/config/transport.html#sockoptobject
> > > 传输方式（transport）配置有两部分：
> > > 
> > > 1. 全局配置（TransportObject）
> > > 2. 局部配置（StreamSettingsObject）
> > >    局部配置时,可以指定每个单独的入站或出站用怎样的方式传输。
> > >    "sockopt": {
> > >    "mark": 0,
> > >    "tcpFastOpen": false,
> > >    "tproxy": "off",
> > >    "domainStrategy": "AsIs",
> > >    "dialerProxy": "",
> > >    **"acceptProxyProtocol": false,**
> > >    "tcpKeepAliveInterval": 0
> > >    }
> 
> 是有两部分，但无论是全局配置的 `transport.tcpSettings.acceptProxyProtocol`，还是局部设置的 `streamSettings.sockopt.acceptProxyProtocol`，都只对 `inbound` 有效，指示是否**接收** PROXY protocol，在 `outbound` 里是无效的。
> 
> 而我想要的是针对 `outbound` 的设置，在 `outbound` 转发流量时 **发送** PROXY protocol。

你的实际使用场景是怎样的？

**Comment by Fangliding** [comment]
@iKira 现在暂时还不支持 估计以后也不会有(
硬要的话 可以使用vless的回落以发送 proxy protocol
https://xtls.github.io/config/features/fallback.html#fallbackobject

**Comment by us254** [comment]
This can be used to set a default destination for non-VLESS traffic, including sending it to another server that can handle the PROXY protocol.



```json
{
  "inbounds": [
    {
      "protocol": "vless",
      "settings": { ... },
      "streamSettings": { ... },
      "fallbacks": [
        {
          "dest": 80,
          "xver": 1
        }
      ]
    }
  ]
}
```
In this example, any non-VLESS traffic received on this inbound connection would be sent to port 80 on the same machine, with the PROXY protocol (version 1) added to the connection.

**Comment by cxy930123** [comment]
@iKira 我是想做网站访问的控制，网站无法直接访问，只有通过 xray 转发才能访问，相当于用 xray 来做鉴权。

比如我搭建了一个 [code-server](https://github.com/coder/code-server)，用于个人编程开发，所以我希望用 xray 来鉴权，别人不能访问到。但是开发应用的时候获取不到客户端IP，因为经过了 xray 的转发后IP丢失。

再比如我希望 xray 用户访问特定网址来查看自己的流量使用情况，这时候希望直接用 xray 做到免登录，而不是用账号密码登录。

我觉得作为一个完善的网络工具，是可以考虑实现往下一个节点发送 PROXY protocol 的功能的。

**Comment by iKira** [comment]
> @iKira 我是想做网站访问的控制，网站无法直接访问，只有通过 xray 转发才能访问，相当于用 xray 来做鉴权。
> 
> 比如我搭建了一个 [code-server](https://github.com/coder/code-server)，用于个人编程开发，所以我希望用 xray 来鉴权，别人不能访问到。但是开发应用的时候获取不到客户端IP，因为经过了 xray 的转发后IP丢失。
> 
> 再比如我希望 xray 用户访问特定网址来查看自己的流量使用情况，这时候希望直接用 xray 做到免登录，而不是用账号密码登录。
> 
> 我觉得作为一个完善的网络工具，是可以考虑实现往下一个节点发送 PROXY protocol 的功能的。

可以考虑在Nginx配置文件中增加 ‘auth_basic’、'auth_basic_user_file' 来实现鉴权。

**Comment by wanliyunyan** [comment]
@cxy930123 
```
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {
        "redirect": "127.0.0.1:40000",
        "proxyProtocol": 2
      }
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "block"
    }
  ],
```

大佬，nginx配置应该怎么写，能接收到来自xray的流量

**Comment by chika0801** [comment]
> @cxy930123
> 
> ```
>   "outbounds": [
>     {
>       "protocol": "freedom",
>       "settings": {
>         "redirect": "127.0.0.1:40000",
>         "proxyProtocol": 2
>       }
>     },
>     {
>       "protocol": "blackhole",
>       "settings": {},
>       "tag": "block"
>     }
>   ],
> ```
> 
> 大佬，nginx配置应该怎么写，能接收到来自xray的流量

listen                     127.0.0.1:8002 ssl proxy_protocol;

proxy_protocol 这个参数

**Comment by wanliyunyan** [comment]
谢谢了，其实就是多加一个 `"proxyProtocol": 2`，然后nginx 
```
    server {
        listen       端口 proxy_protocol;
    }
```  
之前不懂原理，白忙活半天
