### ISSUE TITLE
Compile error on ramips

### ISSUE THREAD

**Issue by hqvv** [XTLS/Xray-core#2594]
Hi All,

I have problem when compile xray-core for ramips router, but no issue when compile filogic.
Please kindly help to review this issue.
Thanks

`github.com/cloudflare/circl/sign/ed25519
github.com/cloudflare/circl/pke/kyber/kyber1024/internal
github.com/cloudflare/circl/pke/kyber/kyber1024
github.com/cloudflare/circl/pke/kyber/kyber512/internal
# runtime/cgo
gcc_mipsx.S: Assembler messages:
gcc_mipsx.S:27: Error: invalid operands `sw $18,12($29)'
gcc_mipsx.S:28: Error: invalid operands `sw $19,16($29)'
gcc_mipsx.S:29: Error: invalid operands `sw $20,20($29)'
gcc_mipsx.S:30: Error: invalid operands `sw $21,24($29)'
gcc_mipsx.S:31: Error: invalid operands `sw $22,28($29)'
gcc_mipsx.S:32: Error: invalid operands `sw $23,32($29)'
gcc_mipsx.S:33: Error: invalid operands `sw $30,36($29)'
gcc_mipsx.S:46: Error: invalid operands `jalr $20'
gcc_mipsx.S:50: Error: invalid operands `lw $18,12($29)'
gcc_mipsx.S:51: Error: invalid operands `lw $19,16($29)'
gcc_mipsx.S:52: Error: invalid operands `lw $20,20($29)'
gcc_mipsx.S:53: Error: invalid operands `lw $21,24($29)'
gcc_mipsx.S:54: Error: invalid operands `lw $22,28($29)'
gcc_mipsx.S:55: Error: invalid operands `lw $23,32($29)'
gcc_mipsx.S:56: Error: invalid operands `lw $30,36($29)'
gcc_mipsx.S:65: Error: invalid operands `lw $31,0($29)'
github.com/cloudflare/circl/pke/kyber/kyber768/internal
github.com/cloudflare/circl/kem/kyber/kyber1024
github.com/cloudflare/circl/ecc/goldilocks
github.com/cloudflare/circl/pke/kyber/kyber512
github.com/cloudflare/circl/sign/dilithium/internal/common
github.com/cloudflare/circl/pke/kyber/kyber768
golang.org/x/crypto/cryptobyte
github.com/cloudflare/circl/kem/kyber/kyber512
golang.org/x/net/idna
golang.org/x/crypto/sha3
github.com/cloudflare/circl/kem/kyber/kyber768
golang.org/x/crypto/curve25519
github.com/cloudflare/circl/sign/dilithium/mode2/internal
github.com/cloudflare/circl/sign/dilithium/mode3/internal
github.com/cloudflare/circl/kem/hybrid
github.com/sagernet/sing/common/atomic
github.com/cloudflare/circl/sign/ed448
github.com/sagernet/sing/common/x/list
github.com/sagernet/sing/common/cache
github.com/refraction-networking/utls/internal/helper
github.com/cloudflare/circl/sign/dilithium/mode2
github.com/sagernet/sing/common/auth
github.com/sagernet/sing/common/random
github.com/sagernet/sing/common/replay
github.com/sagernet/sing/common/logger
golang.org/x/crypto/poly1305
github.com/cloudflare/circl/sign/eddilithium2
github.com/cloudflare/circl/sign/dilithium/mode3
github.com/cloudflare/circl/sign/eddilithium3
github.com/cloudflare/circl/sign/schemes
github.com/cloudflare/circl/pki
github.com/sagernet/wireguard-go/rwcancel
gvisor.dev/gvisor/pkg/rand
gvisor.dev/gvisor/pkg/tcpip/network/hash
gvisor.dev/gvisor/pkg/tcpip/stack

make[3]: *** [Makefile:53: /home/hq/lede/openwrt/build_dir/target-mipsel_24kc_musl/Xray-core-1.8.4/.built] Error 1
make[3]: Leaving directory '/home/hq/lede/openwrt/package/mypackage/xray-core'
time: package/mypackage/xray-core/compile#19.08#3.14#25.81
    ERROR: package/mypackage/xray-core failed to build.
make[2]: *** [package/Makefile:120: package/mypackage/xray-core/compile] Error 1
make[2]: Leaving directory '/home/hq/lede/openwrt'
make[1]: *** [package/Makefile:114: /home/hq/lede/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/hq/lede/openwrt'
make: *** [/home/hq/lede/openwrt/include/toplevel.mk:232: world] Error 2`

**Comment by us254** [comment]
The error messages you've provided suggest that there are issues with the assembly code in the `gcc_mipsx.S` file, specifically with the `sw` (store word) and `lw` (load word) instructions.

The `sw` instruction is used to store a word from a register to memory, and `lw` is used to load a word from memory into a register. Both of these instructions expect two operands. The first operand is a register, and the second is an offset and a base register. The syntax is usually `sw register, offset(base register)` and `lw register, offset(base register)`.

The error messages are indicating that these instructions have invalid operands. This could mean the registers or memory addresses specified are incorrect or not accessible.

This error could be related to the specific architecture you're compiling for (ramips router). It's possible that the assembler code in the `gcc_mipsx.S` file is not compatible with this architecture.

Without more information about the build system, the version of the assembler you're using, and the complete build log, it's hard to provide a more precise answer.

**Comment by hqvv** [comment]
@us254  thanks for your reply.
The issue still exist for mips and ramips.
Many other projects also have this issue https://github.com/search?q=gcc_mipsx.S&type=issues
Which could be a common issue for go based projects.

**Comment by hqvv** [comment]
Problem solved by disable CGO
