### ISSUE TITLE
疑惑，使用了WS套了CDN，意外发现VPS有一些不应该存在的流量，且走了VmessWS的协议正常入站了

### ISSUE THREAD

**Issue by HalChoo** [XTLS/Xray-core#2595]
VPS搭建了Xray，其中Vmess+ws+TLS协议，另外使用CF的Worker代理了这个VPS的站点，访问Worker的流量都会被代理到VPS中，偶然间发现有一些没有拒绝的访问表现如下：

XXXX:XXX  accepted tcp:ht-cdn2.adtng.com:443 [VMessWS >> IPv4-out]

类似的访问记录时不时的会出现一些，IP和访问的域名都不是预期的访问记录，甚至还有黄漫网站……不是我本认的访问，节点未泄露，最重要的是，访问的IP按理来说不应该VMessWS入栈.

所以是使用Worker的原因导致的吗？求大家帮我分析下这种信息是什么个情况

**Comment by Fangliding** [comment]
@HalChoo 你打开一个网页 浏览器要向无数个网站打开连接获取 js img 以及其他各种加载网页所需的资源 日志里有你看不懂的网址很正常
