### ISSUE TITLE
[feature request] Support reload xray process

### ISSUE THREAD

**Issue by ko1ebayev** [XTLS/Xray-core#2596]
Ni Hao xray developers! Id like to reload xray process when updating my config, so can you please support something like SIGHUP signal or reload functionality in upcoming releases?

**Comment by chika0801** [comment]
This is a good suggestion. Do you want the ability to use the systemctl reload xray command to reload the config file without restarting the Xray process? Maybe wait for a fated person to add the code.

**Comment by ko1ebayev** [comment]
I think it will be easier and more useful to support cross-platform reload process. I also don’t have a very good idea of ​​what kind of implementations there might be, but I see some kind of separate command for updating the config on the fly, something like `xray update --config=/path/to/json`. Maybe I will make a pull-request with this feature later
