### ISSUE TITLE
关于国内网站分流到WARP网络的疑问

### ISSUE THREAD

**Issue by shandongtlb** [XTLS/Xray-core#2598]
之前看RP大佬说过，推荐还是直接将国内流量引入黑洞路由，用warp也可以，但会被标记。

但是黑洞这样的话手机上Googleplay商店访问cn域名会导致打不开进而无法跳转。同时懒得再去配置，因此还是想一刀切，cn全部走warp。

在此便有一个安全疑问，比如微信APP走warp后，会发现一个国内账号突然去了国外，标记账号为代理，然后查询该账号对应的手机串号，将串号发送给运营商，运营商调取可疑时段的流量记录，这样是不是就暴露了？于是再次分为两种可能：
1.使用的代理是xtls vision 或其他基于tls的代理，看你这段可疑时间内一直访问一个奇奇怪怪的域名，果断给你sni+ip阻断（当然，也可能不阻断，但就像RP大佬之前说的，留着监控你，钓鱼执法）
2.用的是reality，看你这段时间一直在访问一个白名单常见域名和一个陌生的ip，仍然标为可疑。当然，这样代理的服务端ip也就暴露了。

因此，综上所述，warp是不是一点也不安全了（悲

**Comment by Fangliding** [comment]
@shandongtlb 我都觉得麻烦 阁下身价几亿指的这么搞

**Comment by shandongtlb** [comment]
> @shandongtlb 我都觉得麻烦 阁下身价几亿指的这么搞

是的，我也说了这样成本会特别高，要是问值得那肯定是不值得，只是进行讨论

**Comment by qist** [comment]
内外分流做好了怎么还会有这样的问题呢.一开始就弄好啊.

**Comment by shandongtlb** [comment]
> 内外分流做好了怎么还会有这样的问题呢.一开始就弄好啊.

客户端已经 cn direct了，但是我怕其他人用的时候不做好客户端分流，所以只能在服务端分流做最后一道保障

**Comment by zxbiao** [comment]
有没有这么一种可能，微信就是通过设置了一些国外的DNS记录来<s>钓鱼</s>

**Comment by timi-owo** [comment]
> @shandongtlb 我都觉得麻烦 阁下身价几亿指的这么搞

这就麻烦了，那请问阁下是不是在某个湖字省？

**Comment by shandongtlb** [comment]
> 有没有这么一种可能，微信就是通过设置了一些国外的DNS记录来钓鱼

我丢，你这么一说更害怕了

**Comment by shandongtlb** [comment]
> 有没有这么一种可能，微信就是通过设置了一些国外的DNS记录来钓鱼

我现在是服务端block了cn域名和ip
安卓客户端direct cn域名和ip，并且分应用代理，微信APP设为直连，这样应该好点吧

**Comment by chika0801** [comment]
> 在此便有一个安全疑问，比如微信APP走warp后，会发现一个国内账号突然去了国外，标记账号为代理，然后查询该账号对应的手机串号，将串号发送给运营商，运营商调取可疑时段的流量记录，这样是不是就暴露了？于是再次分为两种可能：

就要看自己懂不懂，懂就分应用代理，不懂全局代理了微信也没法，是自己客户端自己控制的事。

> 1.使用的代理是xtls vision 或其他基于tls的代理，看你这段可疑时间内一直访问一个奇奇怪怪的域名，果断给你sni+ip阻断（当然，也可能不阻断，但就像RP大佬之前说的，留着监控你，钓鱼执法）

换一个逻辑，也有其他人问过。不管我是REALITY偷自己，还是VISION + TLS，我自己就那些VPS，也不是每个VPS都给朋友在用。今天用一个VPS，明天用另外一个VPS。防火墙真有精力查这几个VPS的IP，就只有你的地区的IP在访问这道理。解决方法“我们开一个机场吧”。。。

**Comment by chika0801** [comment]
> 我现在是服务端block了cn域名和ip

如果要解决 你去程到VPS，为了不让同时间段这VPS的IP访问国内，建议一些逻辑关联。方法你用的阻止，或CNIP扔WARP，或CNIP转到你另外台VPS的IP

**Comment by Johnny256Dawson** [comment]
@chika0801 黑名单一上，爱咋咋地

**Comment by Johnny256Dawson** [comment]
@Johnny256Dawson Final直接一条direct ，xray屏蔽国内流量，哪个国内应用能获取你的代理ip呢

**Comment by shandongtlb** [comment]
> > 在此便有一个安全疑问，比如微信APP走warp后，会发现一个国内账号突然去了国外，标记账号为代理，然后查询该账号对应的手机串号，将串号发送给运营商，运营商调取可疑时段的流量记录，这样是不是就暴露了？于是再次分为两种可能：
> 
> 就要看自己懂不懂，懂就分应用代理，不懂全局代理了微信也没法，是自己客户端自己控制的事。
> 
> > 1.使用的代理是xtls vision 或其他基于tls的代理，看你这段可疑时间内一直访问一个奇奇怪怪的域名，果断给你sni+ip阻断（当然，也可能不阻断，但就像RP大佬之前说的，留着监控你，钓鱼执法）
> 
> 换一个逻辑，也有其他人问过。不管我是REALITY偷自己，还是VISION + TLS，我自己就那些VPS，也不是每个VPS都给朋友在用。今天用一个VPS，明天用另外一个VPS。防火墙真有精力查这几个VPS的IP，就只有你的地区的IP在访问这道理。解决方法“我们开一个机场吧”。。。

通透，感谢！

**Comment by shandongtlb** [comment]
> > 我现在是服务端block了cn域名和ip
> 
> 如果要解决 你去程到VPS，为了不让同时间段这VPS的IP访问国内，建议一些逻辑关联。方法你用的阻止，或CNIP扔WARP，或CNIP转到你另外台VPS的IP

这就是我问的问题了，CNIP扔WARP时，微信获取warp的出站IP标记为异常，通过查找该微信账号，进而获得手机串号，于是运营商就找到你了。。。

**Comment by shandongtlb** [comment]
> > 我现在是服务端block了cn域名和ip
> 
> 如果要解决 你去程到VPS，为了不让同时间段这VPS的IP访问国内，建议一些逻辑关联。方法你用的阻止，或CNIP扔WARP，或CNIP转到你另外台VPS的IP

所以说目前最安全的办法感觉还是直接block伺候

**Comment by chika0801** [comment]
> > > 我现在是服务端block了cn域名和ip
> > 
> > 
> > 如果要解决 你去程到VPS，为了不让同时间段这VPS的IP访问国内，建议一些逻辑关联。方法你用的阻止，或CNIP扔WARP，或CNIP转到你另外台VPS的IP
> 
> 这就是我问的问题了，CNIP扔WARP时，微信获取warp的出站IP标记为异常，通过查找该微信账号，进而获得手机串号，于是运营商就找到你了。。。

如果不觉得分应用代理，不选微信，还是不放心，要么你这手机上就不安微信，或安微信的手机就不要开代理，总安全了。

**Comment by shandongtlb** [comment]
> > > > 我现在是服务端block了cn域名和ip
> > > 
> > > 
> > > 如果要解决 你去程到VPS，为了不让同时间段这VPS的IP访问国内，建议一些逻辑关联。方法你用的阻止，或CNIP扔WARP，或CNIP转到你另外台VPS的IP
> > 
> > 
> > 这就是我问的问题了，CNIP扔WARP时，微信获取warp的出站IP标记为异常，通过查找该微信账号，进而获得手机串号，于是运营商就找到你了。。。
> 
> 如果觉得用分应用代理，不选微信，还是不放心，要么你这手机上就不安微信，或安微信的手机就不要开代理（用2个手机），总安全了。

谢谢，个人现在分应用+block，应该问题不大了，主要是还有朋友在用，他们是一点都不懂，用的还是iOS，所以block，block，还是block！

**Comment by chika0801** [comment]
你不要免费拿机给朋友，发他aff链接叫他自己注册付款买个vps，你可以帮他搭，那机他自己用，你不参与
