### ISSUE TITLE
[Features Request] Add location asset search for V2Ray

### ISSUE THREAD

**Issue by AkinoKaede** [XTLS/Xray-core#26]
https://github.com/XTLS/Xray-core/blob/main/common/platform/others.go
```go
for _, p := range []string{
		defPath,
		filepath.Join("/usr/local/share/xray/", file),
		filepath.Join("/usr/share/xray/", file),
	} {
		if _, err := os.Stat(p); os.IsNotExist(err) {
			continue
		}

		// asset found
		return p
	}

```
可以看出 目前 Xray-core 會自動尋找 /usr/local/share/xray/ 和 /usr/share/xray/ 作為資源路徑。

這讓我為 Arch Linux 打包時造成了一定的困惑
目前 [AUR](https://aur.archlinux.org/packages/xray) 中採用 v2ray-domain-list-community 和 v2ray-geoip 作為依賴項，並在 service 文檔中設置環境變量 XRAY_LOCATION_ASSET=/usr/share/v2ray。
Arch Linux CN 方面則是打包了 xray-domain-list-community 和 xray-geoip。
但目前來看，兩種方法或許都不是最佳解決方案。
或許可以添加以下代碼在第32行之後
```go
filepath.Join("/usr/local/share/v2ray/", file),
filepath.Join("/usr/share/v2ray/", file),
```

**Comment by rprx** [comment]
你好，我看了你们的讨论 https://github.com/archlinuxcn/repo/issues/1996

其实我赞成 @dctxmei 的做法，主要原因是 Project X 将会发展出一个独立的生态。

关于 .dat files：https://github.com/XTLS/Xray-core/issues/9#issuecomment-736236174

**Comment by AkinoKaede** [comment]
> 你好，我看了你们的讨论 [archlinuxcn/repo#1996](https://github.com/archlinuxcn/repo/issues/1996)
> 
> 其实我赞成 @dctxmei 的做法，主要原因是 Project X 将会发展出一个独立的生态。
> 
> 关于 .dat files：[#9 (comment)](https://github.com/XTLS/Xray-core/issues/9#issuecomment-736236174)

感謝您的回复，我將會重新考慮此項問題。
