### ISSUE TITLE
Openwrt上没法自启动

### ISSUE THREAD

**Issue by snowwolf007cn** [XTLS/Xray-core#2602]
型号 | Netgear WNDR4300
架构 | Atheros AR9344 rev 2
目标平台 | ath79/nand
固件版本 | OpenWrt 22.03.5 r20134-5f15225c1e

Xray-core版本:1.8.3

安装以后，service里有xray，但是没有自启动，service start xray也没法启动

**Comment by Fangliding** [comment]
@snowwolf007cn 去找openwrt（）

**Comment by LeoOynick** [comment]
https://github.com/openwrt/packages/blob/openwrt-22.03/net/xray-core/files/xray.init

**Comment by harvey-git** [comment]
巧了，我也是owr2203.5，这是我自己在用的：/etc/init.d/xray 

`#!/bin/sh /etc/rc.common

START=80
ROOT=/etc/config/xray
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1



start() {
	echo "start xray..."
	ulimit -SHn 8192
	service_start $ROOT/xray run -c $ROOT/config.json
	#	echo "start transport Proxy rule..."
	#        nft -f $ROOT/nft-xray.conf
	#	ip rule add fwmark 1 table 100 
	#	ip route add local 0.0.0.0/0 dev lo table 100
#        uci add_list dhcp.@dnsmasq[0].server='127.0.0.1#1053'
 #       uci commit dhcp
  #      /etc/init.d/dnsmasq reload                                        
		echo "" > /var/log/error.log 
		echo "" > /var/log/access.log 

}

stop() {
	#	echo "stop transport Proxy rule"
	#	ip rule del fwmark 1 table 100 
	#	ip route del local 0.0.0.0/0 dev lo table 100
	#        nft delete table inet xray
	echo "stop xray."
	service_stop $ROOT/xray
   #    uci del dhcp.@dnsmasq[0].server
    #   uci commit dhcp
     # /etc/init.d/dnsmasq reload                                        
}
`

**Comment by mpjanet** [comment]
/etc/config/xray
Set Enabled to 1 (installed as 0)
I guess the developer want user to test configuration using command-line before start as a service.
