### ISSUE TITLE
协议为shadowsocks的时候无法连接到使用v2ray-plugin的shadowsocks-libev服务器

### ISSUE THREAD

**Issue by snowwolf007cn** [XTLS/Xray-core#2603]
目前只能使用mux disable的方式连接到没有加载v2ray-plugin的服务器
看日志的话，好像是chacha20ietfpoly1305: message authentication failed

**Comment by KobeArthurScofield** [comment]
老问题。因为 core 和 plugin 的实际处理方式不一样。参见 shadowsocks/v2ray-plugin#123
plugin 默认会强制使用 mux，但是因为 plugin 是将 transport 独立出来单独处理， mux 在两者里面一般处理路径不同：
core： mux→protocol→transport （mux→ss→ws）
plugin：protocol→mux→transport （ss→mux→ws）
这个流程差异会使 transport 以上的数据流格式不同导致处理失败。

解决办法是：
1. v2ray-plugin 加入参数 ```mux=0``` ，即强制关闭 mux。此方法必须令所有使用 plugin 的服务端和客户端添加此参数，core 端不用修改。（plugin 需求 1.2.0及以上）
2. （之前见过但是暂时找不到）core 额外加入一层来适配 plugin，即：客户端 core 开一个 dokodemo-door 入站，开一个带 mux 和指定 transport （ws，quic）的 freedom 出站指向服务器地址和端口，在 routing 中将这两个多出来的入站和出站代理连起来，然后 ss 出站的地址和端口指向 dokodemo-door 入站。此法不需要在 plugin 上添加额外的 mux 参数，但是对使用 core 的客户端只能使用自定义配置文件来处理。

**Comment by snowwolf007cn** [comment]
多谢回复，暂时试了下第一种方法，更改服务器端配置如下：
```json
    "plugin":"v2ray-plugin",
    "plugin_opts":"server;mux=0",
```
好像还是发不出去消息, v2ray-plugin的版本是4.19.1，用go1.12.7编译的

**Comment by KobeArthurScofield** [comment]
如果服务端不是 Xray-core 或者 V2Ray-core 的话客户端则不应该在 shadowsocks 协议上面启用 Mux，Mux 只有两端都是 core 才能正确处理（因为需要服务端处理 Mux.cool 协议）。
最好同时确认一下加密方式和密码无误，同时 ivcheck 没在服务端不支持时启用。
插件选项不指定情况下 path 默认为 ```/``` ，客户端和服务端保持一致；如果服务端上指定了 host，则客户端和服务端也必须一致。

> 第二种就是在透明代理的inbound基础上再加一个dokodemo-door的inbound，然后和一个freedom的outbound吧？

不需要透明代理，实际上配置里面额外添加的内容大致如下：

``` jsonc
{
    "inbounds": [
        {
            "listen": "127.0.0.1",
            "port": 1200,                   /* 模拟插件监听端口，可自定义 */
            "protocol": "dokodemo-door",
            "settings": {
                "address": "127.0.0.1",    /* 不要更动此值 */
                "network": "tcp"
            },
            "tag": "plugin-in"
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "settings": {
                "redirect": "address"    /* 服务器的地址端口， HOST:PORT */
            },
            "mux": {       /* 服务端不是 mux=0 时必须设置 */
                "enabled": true,
                "concurrency": 1
            },
            "streamSettings": {
                "security": "none",    /* 如果服务端使用 websocket-https 模式则为 tls */
                "network": "ws",
                "wsSettings": {
                    "path": "/",     /* 默认为 / ，服务端与客户端一致 */
                    "headers": {
                        "Host": "example.com"    /* 域名，如果服务端有指定则必须保持一致 */
                    }
                }
            },
            "tag": "plugin-out"
        }
    ],
    "routing": {
        "rules": [
            {
                "type": "field"
                "inboundTag": ["plugin-in"]
                "outboundTag": "plugin-out"
            }
        ]
    }
}
```

然后将 shadowsocks 出站的地址和端口改为 plugin-in 监听的地址和端口。

**Comment by Hareis** [comment]
我觉得他可能生效了 但是我仍然没法访问【股沟】
