### ISSUE TITLE
关于内置dns处理双栈站点的疑惑

### ISSUE THREAD

**Issue by yoshyv** [XTLS/Xray-core#2604]
想请教一个出站v4/v6优先级问题。
server其中相关配置如下。系统dns是dnsmasq的本地监听地址，dns并没有什么特殊处理。

```
{
    "dns": {"servers": "127.0.0.1"},
    "routing":
    {
        "domainStrategy": "IPIfNonMatch",
        "domainMatcher": "mph",
        "rules":
        [
            {
                "type": "field",
                "domain":
                [
                    "geosite:cn"
                ],
                "outboundTag": "block"
            },
            {
                "type": "field",
                "domain":
                [
                    "geosite:google"
                ],
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "ip":
                [
                    "geoip:cn"
                ],
                "outboundTag": "block"
            },
            {
                "type": "field",
                "ip":
                [
                    "geoip:private"
                ],
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "ip":
                [
                    "geoip:!cn"
                ],
                "outboundTag": "warp"
            }
        ]
    },
    "inbounds":[    ],
    "outbounds":
    [
        {
            "tag": "direct",
            "protocol": "freedom",
            "settings":
            {
                "domainStrategy": "UseIPv4"
            }
        },
        {
            "tag": "warp",
            "protocol": "wireguard",
            "settings":{},
        },
        {
            "tag": "block",
            "protocol": "blackhole"
        }
    ]
}
```

此配置情况下，本地连上后所有非cn的geoip 走warp出站的的请求都会优先v4。
奇怪的是，**如果把DNS字段里面的server改成 localhost** ，根据文档

> 使用本机预设的 DNS 配置。本机的 DNS 请求不受 Xray 控制。

> https://xtls.github.io/config/dns.html#dns-%E6%9C%8D%E5%8A%A1%E5%99%A8

个人理解，两种情况最后都是走系统dns解析。
然而修改后，所有双栈的网站都优先v6出站。尝试修改系统级别的 gai.conf 优先v4，依旧会是走v6出站。

请问这两种配置的差距在哪呢？
根据文档outbound里面除了freedom以外都不支持 domainStrategy。那么如何在使用 localhost 情况下优先v4出站呢？ 

谢谢。

**Comment by chika0801** [comment]
看了下你配置，你出站部分中，没有tag为warp的出站。那么非CNIP的域名应该用默认第1个出站`"tag": "direct",`。因为你用了
"domainStrategy": "UseIPv4"，域名请求命中XRAY的DNS缓存，选IPv4地址出站。（分析的流程过程）

> 那么如何在使用 localhost 情况下优先v4出站呢？
一般情况你VPS上的网卡有v4和v6就是在出站中用 domainStrategy 参数的useipv几来决定出站走v几的。

**Comment by yoshyv** [comment]
warp tag 是有的。去隐私时候删多了。
如果没有的话出站也不会走warp了。

我的疑问是为什么内置dns不同写法会导致warp出站优先v4/v6不同，以及如何在用localhost时候warp优先v4出站。

**Comment by chika0801** [comment]
> 我的疑问是为什么内置dns不同写法会导致warp出站优先v4/v6不同

内置DNS写localhost或127.0.0.1应该不会影响warp出口走v几。你要研究，你把日志开成debug客户端访问网站。服务端看日志来分析流程。

https://github.com/chika0801/Xray-examples/blob/main/wireguard.md
目前的XRAY版本你想控制进Wireguard是走V几，我是这样做的。

**Comment by yoshyv** [comment]
> 内置DNS写localhost或127.0.0.1应该不会影响warp出口走v几。你要研究，你把日志开成debug客户端访问网站。服务端看日志来分析流程。

我也是这样想的。但是我上面贴的配置除了入站和细节也没什么别的东西了。请问那边能测试下能否复现我这情况呢？我是 1.8.3版本因为1.8.4版本wiregurad吞吐量挺废的，速度慢。也不知道是不是通病。
 
> https://github.com/chika0801/Xray-examples/blob/main/wireguard.md 目前的XRAY版本你想控制进Wireguard是走V几，我是这样做的。
这个出站要复杂不少了。 xray 的 UseIPv4 近视优先 v4 对吧。好像配置后依然能访问v6。我的 freedom 直连出站就这样配置的。

**Comment by us254** [comment]
{
  "log": {
    "loglevel": "debug"
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "domainMatcher": "hybrid",
    "rules": [
      {
        "type": "field",
        "ip": [
          "::0/0"
        ],
        "outboundTag": "v6"
      }
    ]
  },
  "inbounds": [
    {}
  ],
  "outbounds": [
    {
      "tag": "v4",
      "protocol": "freedom",
      "streamSettings": {
        "sockopt": {
          "domainStrategy": "UseIPv4",
          "dialerProxy": "wireguard"
        }
      }
    },
    {
      "tag": "v6",
      "protocol": "freedom",
      "streamSettings": {
        "sockopt": {
          "domainStrategy": "UseIPv6",
          "dialerProxy": "wireguard"
        }
      }
    },
    {
      "protocol": "wireguard",
      "settings": {
        "secretKey": "M=",
        "address": [
          "172.16.0.2/32",
          "/128"
        ],
        "peers": [
          {
            "publicKey": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
            "allowedIPs": [
              "0.0.0.0/0",
              "::/0"
            ],
            "endpoint": "engage.cloudflareclient.com:2408"
          }
        ],
        "reserved": [
          49,
          71,
          76
        ],
        "mtu": 1280
      },
      "tag": "wireguard"
    },
    {
      "protocol": "blackhole",
      "tag": "block"
    }
  ]
}

**Comment by yoshyv** [comment]
@us254 的确可以这样哦，把::/0 这样v6地址单独分流一个。
这个配置没有完全理解，不过还是先感谢了。

日志调成info都多到看不过来，debug日志真不知道从哪开始看了 - -
