### ISSUE TITLE
Bug: MultiFile Multi inbound issue

### ISSUE THREAD

**Issue by hiddify-com** [XTLS/Xray-core#2606]
When we have multifile configuration with multi inbound, files with multiple inbounds will be ignored.

### x.json:
``` 
{
        "inbounds": [
       {
            "tag": "x1",
            "listen": "127.0.0.1",
            "port": 1001,
            "protocol": "socks"
        },
       {
            "tag": "x2",
            "listen": "127.0.0.1",
            "port": 1002,
            "protocol": "socks"
        }
        ]
}
```
### y.json:
``` 
{
        "inbounds": [
       {
            "tag": "y1",
            "listen": "127.0.0.1",
            "port": 2001,
            "protocol": "socks"
        },
       {
            "tag": "y2",
            "listen": "127.0.0.1",
            "port": 2002,
            "protocol": "socks"
        }
        ]
}
```

### z.json:
``` 
{
        "inbounds": [
       {
            "tag": "z1",
            "listen": "127.0.0.1",
            "port": 3001,
            "protocol": "socks"
        }
        ]
}
```
### The Problem
Inbounds of y.json override the inbounds in xray so inbounds in x.json will be ignored.

I have tried to do pull request but i could not identify the source of the issue.

### logs:

```
...
2023/10/02 12:40:03 [Info] infra/conf/serial: Reading config: x.json
2023/10/02 12:40:03 [Info] infra/conf/serial: Reading config: y.json
2023/10/02 12:40:03 [Info] infra/conf/serial: Reading config: z.json
xctl> [ z.json ] appended inbound with tag:  z1
2023/10/02 12:40:04 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:2001
2023/10/02 12:40:04 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:2002
2023/10/02 12:40:04 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:3001
2023/10/02 12:40:04 [Warning] core: Xray 1.8.4 started

```

**Comment by BioniCosmos** [comment]
@yuhan6665 I think we should revert changes #2655 and #2659 because the behaviour in the issue is expected.

The logic is [inherited from V2Ray](https://github.com/v2ray/v2ray-core/releases/tag/v4.23.0), so these are breaking changes.

[多文件配置 | Project X](https://xtls.github.io/config/features/multiple.html#%E6%95%B0%E7%BB%84)

**Comment by yuhan6665** [comment]
@BioniCosmos I think override behavior is ok. Please discuss with @hossinasaadi as well

**Comment by hossinasaadi** [comment]
@BioniCosmos 
https://xtls.github.io/config/features/multiple.html#%E6%95%B0%E7%BB%84
every inbound should have tag as you see in docs, if not the default tag name will be a empty string.
so when we add multiple config files, we identified inbound and outbounds with tag name (for update or replace them).

in your inbound file :
```json
{
  "inbounds": [
    {
      "port": 10000,
      "protocol": "socks"
    },
    {
      "port": 10001,
      "protocol": "socks"
    }
  ]
}

```
two inbound tag names assigned as "" so the first one port will replaced with second inbound.

**Comment by BioniCosmos** [comment]
@hossinasaadi 
Tags are not necessary. For example, I only want to set a simple Socks and HTTP server without tags. In such situation, override is unreasonable.
