### ISSUE TITLE
关于CF优选的问题

### ISSUE THREAD

**Issue by shaloushu** [XTLS/Xray-core#2607]
按照我之前的理解，只要GFW没有把CF的所有IP都封禁了，那么应该都是可以使用vmess+ws+tls+优选的方式的，但是前几天开始出现了一个让我及其费解的事，时至今日也无法解决。
这几年我一直使用vmess+ws+tls+优选的方式进行爬墙，前几天忽然不能用，经过检查，域名没问题，端口443也没问题，我就换成vmess+ws+优选的方式，端口使用80，好，又可以用了。第二天又不行，我把端口换成2052（其他CF可用的http，https端口都试过），也是只能撑一天，我又试了一下，换了一下二级域名，比如之前"Host": "a.xxx.com"，换成"Host": "b.xxx.com"，其他都不变，发现节点又可以用了，但是跟上述的一样，基本撑不过一天，就不行了。V2rayN的日志显示
transport/internet/websocket: failed to dial to (ws://x.xxx.com:8080/asffgasfas):  > dial tcp: lookup x.xxx.com: operation was canceled] > common/retry: all retry attempts failed
以上试错误信息，其中的x.xxx.com是解析了优选IP的域名，实际上不用域名直接使用IP也是跟上述的情况一样，能用的时候可以
贴一张图
![image](https://github.com/XTLS/Xray-core/assets/90125737/dd7b4424-1ebd-4dc8-a744-566091c3f242)

**Comment by shaloushu** [comment]
有没有什么办法解决，头都大了

**Comment by chika0801** [comment]
如果你问，用这种组合形式经常被封怎么办，建议不要用这个组合形式。

**Comment by shaloushu** [comment]
> 如果你问，用这种组合形式经常被封怎么办，建议不要用这个组合形式。
> 
> [#1750 (comment)](https://github.com/XTLS/Xray-core/issues/1750#issuecomment-1459340564)
> 
> [#1750 (comment)](https://github.com/XTLS/Xray-core/issues/1750#issuecomment-1459469821)

理解了，就是协议不行了。
