### ISSUE TITLE
关于 xray 内存占用问题

### ISSUE THREAD

**Issue by xiaobili** [XTLS/Xray-core#2608]
there is a problem about xray memory usage
-  after server lunched about two days，xray has a massive memory usage，
- This will result in being unable to access the internet through the Xray proxy.

**Comment by xiaobili** [comment]
i see

**Comment by iu7890** [comment]
我也有类似问题我的解决方案是添加任务让vps定时重启😨

**Comment by xiaobili** [comment]
> 我也有类似问题我的解决方案是添加任务让vps定时重启😨

我刚看了 install.sh 脚本，有 reloadCore 的定时任务，所以没必要再添加了

**Comment by xiaobili** [comment]
> we need more info for this issue: 1.verison & platform 2.configuration details 3.how many users do u have 4.memory usage details
> 
> for my own use,I didn't see any problems here.my xray process is stable and the memory occupation is 40 MiB.

The possible reason could be that multiple modes are simultaneously activated, and each mode has an independent process.

**Comment by zhuxining** [comment]
用的 mack-a 大佬的脚本，启动后内存会逐步增加，服务停止重启恢复，循环往复

![image](https://github.com/XTLS/Xray-core/assets/12285468/76e1cd38-42e8-4d1f-b900-d1cfea8f0a02)

Linux iZt4ngf0ay8xbyx4fn6e3qZ 6.6.0-14-generic #14-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 30 10:27:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Fangliding** [comment]
秒说不清 没有配置 第三方脚本我们管不了(
