### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Motech2** [XTLS/Xray-core#2611]
### Hello 
 **when Im trying to install the package I face this error :**
 
 sudo bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install
 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 30911  100 30911    0     0   429k      0 --:--:-- --:--:-- --:--:--  429k
error: Failed to get the latest release version.
Welcome bug report:https://github.com/XTLS/Xray-install/issues

**Comment by chise0713** [comment]
Check your network

**Comment by Motech2** [comment]
> Check your network
check what about my network ??
what exactly should I do ?

**Comment by us254** [comment]
manually download the script, inspect it, and run it locally:

```
wget https://github.com/XTLS/Xray-install/raw/main/install-release.sh
chmod +x install-release.sh
./install-release.sh @ install
```

**Comment by chise0713** [comment]
> > Check your network
> check what about my network ??
> what exactly should I do ?

Your connectivity to api.github.com, may be a dns pollution or your vps just cannot reach api.github.com.
We're not your parents,try to solve this by yourself.

**Comment by chise0713** [comment]
> manually download the script, and run it locally:
> 
> ```
> wget https://github.com/XTLS/Xray-install/raw/main/install-release.sh
> chmod +x install-release.sh
> ./install-release.sh @ install
> ```
> 

Local run don't need `@` , only ` bash -c "" ` needs it.

**Comment by us254** [comment]
To change the DNS servers on an Ubuntu system, you can follow these steps:

1. Open a terminal.

2. Edit the `/etc/resolv.conf` file using a text editor with root privileges. For example, you can use the `nano` editor:

   ```bash
   sudo nano /etc/resolv.conf
   ```

3. In the text editor, you'll see one or more lines starting with `nameserver`. These lines specify the current DNS servers used by your system.

4. Replace the existing `nameserver` entries with the IP addresses of your desired DNS servers. For example, to use Google's public DNS servers (8.8.8.8 and 8.8.4.4), modify the file to look like this:

   ```
   nameserver 8.8.8.8
   nameserver 8.8.4.4
   ```

5.. Save the changes and exit the text editor.

6.. To prevent Ubuntu from automatically overwriting your changes to `/etc/resolv.conf`, create a new file called `/etc/resolvconf/resolv.conf.d/base`:

    ```bash
    sudo nano /etc/resolvconf/resolv.conf.d/base
    ```

7.. Add your desired DNS server entries in this new file as well:

    ```
    nameserver 8

**Comment by yuhan6665** [comment]
closing
