### ISSUE TITLE
QUIC sniffer

### ISSUE THREAD

**Issue by FDeghy** [XTLS/Xray-core#2616]
Quic sniffer could not detect spotify.com domain in HTTP/3 packet and for this reason route object did not work.

**Comment by chika0801** [comment]
It is recommended not to proxy QUIC traffic, proxy it does not get faster, the Chinese community generally blocked UDP443 on the server side. XRAY VLESS protocol flow control VISION also blocks UDP443 by default.

So we didn't test much if the domain sniffing parameter really took effect correctly on demand.

**Comment by chise0713** [comment]
https://xtls.github.io/en/config/inbound.html#sniffingobject
Make sure your `destOverride` option has “quic” in it
