### ISSUE TITLE
Xray RTT延迟测试,即使开启Mux,来回延迟仍然明显高于SSR

### ISSUE THREAD

**Issue by z826540272** [XTLS/Xray-core#262]
我使用xray vmess协议,内网建立VMWARE服务器,模拟100ms RTT延迟.已知我的测试环境没有任何环路.内网服务器直连光猫网关
然后使用passwall软件测试百度延迟,已知我到百度的延迟是稳定的,波动在10ms内.
多次测试往返延迟,xray vmess TCP 协议时延稳定在680-650ms之间,
SSR无混淆,AEAD协议,时延在530-540ms左右,整体差距在150ms左右.
这时候打开mux设置,继续测试来回延迟,有明显降低,接近SSR,但是仍然高于SSR 10-20ms.
其他的协议没有测试,理论应该更慢,例如WS,TLS等.
看起来像是SSR协议并没有握手流程.可能VMESS协议设计缺陷导致的时延较高.
VLESS+TLS有没有解决这个时延问题?我猜没有

测试方法可能有问题，等深夜再重新用vps线路看看

**Comment by AkinoKaede** [comment]
TLS 1.3 有 1-RTT，若是 TLS 1.2 则有 3-RTT。VMess 本身为无状态协议没有握手流程。

**Comment by z826540272** [comment]
建议排查一下问题,因为mux可能速率不佳

**Comment by z826540272** [comment]
vps测试没有复现

**Comment by z826540272** [comment]
vps测试没有复现

**Comment by z826540272** [comment]
关不掉

**Comment by rprx** [comment]
总结：**所以此问题不存在，代码中也不是这样。**

这里只取决于协议组合本身的 RTT，此外开 Mux 可以真 0-RTT，连 TCP 本身的 1-RTT 都没有。

（看起来是最初模拟延迟的方式有问题）
