### ISSUE TITLE
xray 和 v2ray 是否还保持兼容？

### ISSUE THREAD

**Issue by hel1o-wor1d** [XTLS/Xray-core#2620]
两个项目都在持续更新，到底哪个效率最好？还能不能保持兼容？

**Comment by chika0801** [comment]
你如果问协议方面，你如果用VLESS协议及有关的，建议两端都用Xray-core

和一些Xray-core有关UDP方面的改进。其它方面大部分兼容。

**Comment by hel1o-wor1d** [comment]
能不能搞一些benchmark之类的，对内存、CPU、传输速率方面比较比较。

**Comment by chika0801** [comment]
不能哦，你有精力可以自己试试

**Comment by yuhan6665** [comment]
closing as answered
