### ISSUE TITLE
建议搞一些 apt、yum 仓库

### ISSUE THREAD

**Issue by hel1o-wor1d** [XTLS/Xray-core#2621]
建议搞一些 apt、yum 仓库。
虽然直接下载二进制文件就能运行，但是每个Linux都有自己的包管理工具，安装一个独立于系统管理体系之外程序，感觉不得劲。
各Linux大都用了v2ray的包，虽然版本低点，但是并没有X-ray的包。

**Comment by chika0801** [comment]
都用官方脚本安，一直没进apt仓库

**Comment by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [comment]
自己编译咯

**Comment by RPRX** [comment]
~~视角错误，你到底是为了用 Xray 还是~~

建议换个思路，都用 [Xray-install](https://github.com/XTLS/Xray-install) 安装，即使你换了 Linux 发行版也会用、知道文件都安装到哪了

Linux 现状：

1. 现有发行版都太垃圾，我要自己搞一个！
2. 发行版数量+1

~~让我们做到铁打的 Xray，流水的 Linux 包管理工具~~

**Comment by Fangliding** [comment]
xray当初就是打包问题才分家的（）

**Comment by stevejohnson7** [comment]
用docker/podman就是了，安全且好管理，没有乱七八糟的包管理问题
R主席倒是可以出个官方的docker，类似https://hub.docker.com/r/teddysun/xray
