### ISSUE TITLE
Improve API Documentation 

### ISSUE THREAD

**Issue by vpnagency** [XTLS/Xray-core#2638]
Hello
API (gRPC) documentation is incomplete and there is no example to describe how to call the API from deferent languages.
for example, I want to call API from a Node.js app, and i don't know how do it.

Please complete API documentation, with some examples for deferent languages (Node.js, python, ...).
Thank you

**Comment by Fangliding** [comment]
Just some basic grpc APIs. You can find tutorials everywhere, we cannot cover all languages
