### ISSUE TITLE
是否能套用只转发HTTP1.1的CDN？

### ISSUE THREAD

**Issue by ytai-chn** [XTLS/Xray-core#2640]
小白请教一下。我想使用Azure CDN转发流量，但是Azure CDN不支持HTTP2或WS回源，只支持HTTP1.1回源。如果采用VMESS+HTTP+TLS，其中将TLS的ALPN设置为HTTP1.1，是否在理论上应当能够被CDN转发呢？

**Comment by sduoduo233** [comment]
可以试试这个，把普通tcp连接转成两个http1.1的连接
https://github.com/sduoduo233/commonweb2

**Comment by yuhan6665** [comment]
I think you are looking for meek in v2fly?
