### ISSUE TITLE
ios14 在请求部分网页的时候会断开

### ISSUE THREAD

**Issue by Timssse** [XTLS/Xray-core#2643]
如题，iOS15、16、17都没有问题

**Comment by yuhan6665** [comment]
closing as known behavior

**Comment by Cyberbolt** [comment]
> It’s not related to this repo but it’s because of memory limit in iOS 14 that’s about 15 MB.

Does the Network Extension of iOS 17.3.1 also have a 15 MB limit? (link)[https://github.com/eycorsican/leaf/issues/453]
