### ISSUE TITLE
群晖 Nas 部署 xray，当大流量（例如 youtube 4K）会出现 xray 直接重启问题，提示 buffer 内存申请超出边界

### ISSUE THREAD

**Issue by binfooo** [XTLS/Xray-core#2644]
<img width="901" alt="image" src="https://github.com/XTLS/Xray-core/assets/67949953/54b2e126-fd23-4704-ab02-3e2a42b75a95">

**Comment by binfooo** [comment]
https://registry.hub.docker.com/r/teddysun/xray/ docker image
latest tags

**Comment by binfooo** [comment]
<img width="514" alt="image" src="https://github.com/XTLS/Xray-core/assets/67949953/4cc2ab9d-9cdf-4dd3-812e-fcadee739527">

**Comment by Wfgukasha** [comment]
![233FA5C48253B8AD401E8BD1CC97C969](https://github.com/XTLS/Xray-core/assets/162772997/04f3daa1-4fa8-4d8b-ab29-28d6605c6486)
24.3.9，补充一个问题截图

**Comment by yuhan6665** [comment]
should be fixed in v186. If you can still reproduce in latest version, open issue again.
