### ISSUE TITLE
Reality 是否已经被精确识别？

### ISSUE THREAD

**Issue by shandongtlb** [XTLS/Xray-core#2647]
本人lax地区机器，reality+自己的网站证书，在使用时遇到了一些状况。
配置：服务器入站，vless vison reality，443端口，dest指向本地的nginx，也就是所谓的“偷自己”
出站，block了cn的域名和ip，其他freedom

极少数情况下，电信连接失败，手机端app提示tls handshake time out，移动可以正常连接，从未有过问题
复现该问题后，使用电信通过浏览器访问自己的网站，却可以正常访问。

因此猜想，reality是否已经被识别？同样访问443端口，客户端连接失败但网页却没问题？
该问题很少复现，几乎一周才能碰到一次，难道是线路不稳定吗？
移动去程58807，联通电信去程cn2，回程三网均是cn2

**Comment by chika0801** [comment]
建议再找台好回程的vps搭上试试。社区没有快速许多相似的反馈。

**Comment by shandongtlb** [comment]
> 建议再找台好回程的vps搭上试试。社区没有快速许多相似的反馈。

用了两台垃圾回程的vps，发现没问题（笑

**Comment by chika0801** [comment]
建议你关闭这个iss，你可以在讨论区发一下你的经历分享。

**Comment by shandongtlb** [comment]
> 第一，先排除一下你IP的前身是否进过灰名单； 第二，排除使用国内的DNS，需要配合加密DNS吃用更加爽脆。
> 
> 我有好几个服务器，1个稍微冷门的美西（比BWG/DMIT便宜一点），一个随处可见的便宜美西（当然比VIR之类的要稍贵），一个甲骨文日本（免费）和韩国（付费/CN2-GIA双程）。 论正常的程度是 甲骨文韩国=甲骨文日本（估计是整个甲骨文AS段被进灰名单了）<随处可见的美西（回程优化）<冷门的美西（回程优化） 冷门的美西稳定得不得了，随处可见的有时会被干扰，甲骨文的哈哈就行，基本都是用来落地解锁的。
> 
> 欢迎在讨论区分享经历。

谢谢大佬，这样是不是就是加密DNS了
![Screenshot_20231018_085525_v2rayNG](https://github.com/XTLS/Xray-core/assets/40312509/cd81538a-c7bd-4399-9b27-c80cca2b6d54)
![Screenshot_20231018_085555_v2rayNG](https://github.com/XTLS/Xray-core/assets/40312509/22424a4f-9213-49d2-b6d6-4c2fb7cf5649)
![Uploading Screenshot_20231018_085600_v2rayNG.jpg…]()

**Comment by shandongtlb** [comment]
> 第一，先排除一下你IP的前身是否进过灰名单； 第二，排除使用国内的DNS，需要配合加密DNS吃用更加爽脆。
> 
> 我有好几个服务器，1个稍微冷门的美西（比BWG/DMIT便宜一点），一个随处可见的便宜美西（当然比VIR之类的要稍贵），一个甲骨文日本（免费）和韩国（付费/CN2-GIA双程）。 论正常的程度是 甲骨文韩国=甲骨文日本（估计是整个甲骨文AS段被进灰名单了）<随处可见的美西（回程优化）<冷门的美西（回程优化） 冷门的美西稳定得不得了，随处可见的有时会被干扰，甲骨文的哈哈就行，基本都是用来落地解锁的。
> 
> 欢迎在讨论区分享经历。

谢谢大佬，这样是不是就是开启加密DNS了
![Screenshot_20231018_085525_v2rayNG](https://github.com/XTLS/Xray-core/assets/40312509/c7df346d-357c-4e1a-b8a7-8e83700fc646)
![Screenshot_20231018_085555_v2rayNG](https://github.com/XTLS/Xray-core/assets/40312509/ff361a96-487e-4ef0-9436-48e695b1aadc)
![Screenshot_20231018_085600_v2rayNG](https://github.com/XTLS/Xray-core/assets/40312509/4cf40c75-f970-4840-93c5-bdc3b25bbd52)

**Comment by iKira** [comment]
服务器地址不要填域名，直接填IP，用sni指定握手域名。

**Comment by ixxmu** [comment]
请查看自己是否在白名单区域

**Comment by shandongtlb** [comment]
> 服务器地址不要填域名，直接填IP，用sni指定握手域名。

我填的就是ip，不知道为啥会这样

**Comment by shandongtlb** [comment]
> 请查看自己是否在白名单区域

白名单区域的话，按理说网站也是打不开的
