### ISSUE TITLE
Documentation for SpiderX

### ISSUE THREAD

**Issue by MEM-917** [XTLS/Xray-core#2656]
I searched different repositories and sites but couldn't find thorough and comprehensive documents on SpiderX.
Could someone share a link or manual on implementing and usage of this parameter?

**Comment by hossinasaadi** [comment]
> I searched different repositories and sites but couldn't find thorough and comprehensive documents on SpiderX. Could someone share a link or manual on implementing and usage of this parameter?

read : https://github.com/XTLS/REALITY/blob/main/README.en.md

**Comment by chika0801** [comment]
https://github.com/XTLS/Xray-core/discussions/2385

https://github.com/XTLS/Xray-core/issues/2076

https://github.com/XTLS/Xray-core/issues/2396

Let's say the website you fill in the DEST parameter is www.google.com

This site has a real URL www.google.com/abc

For the SpiderX parameter you can put /abc

For other things, you can see the link above. This parameter doesn't seem to be very important, there are some webmasters who are looking at the instructions from the source code comments.

**Comment by MEM-917** [comment]
> > I searched different repositories and sites but couldn't find thorough and comprehensive documents on SpiderX. Could someone share a link or manual on implementing and usage of this parameter?
> 
> read : https://github.com/XTLS/REALITY/blob/main/README.en.md

Thanks but I've read this and there is nothing useful in this one line comment: "The initial path and parameters of the crawler, recommended to be different for each client". It doesn't tell how to implement or how to use it.
I'm looking for an example or any document to understand how it works.

**Comment by MEM-917** [comment]
> #2385
> 
> #2076
> 
> #2396
> 
> Let's say the website you fill in the DEST parameter is [www.google.com](http://www.google.com)
> 
> This site has a real URL [www.google.com/abc](http://www.google.com/abc)
> 
> For the SpiderX parameter you can put /abc
> 
> For other things, you can see the link above. This parameter doesn't seem to be very important, there are some webmasters who are looking at the instructions from the source code comments.

Thanks. By your explanation, it seems that SpiderX is redundant because the server and client already have the assigned certificate. Unless the path in SpiderX is the list of other certificates. If that is the case, what should be in the designated path?

**Comment by chika0801** [comment]
> Unless the path in SpiderX is the list of other certificates. If that is the case, what should be in the designated path?

I haven't tried to fill in a directory path to specify the content of this parameter, for example /root/a.txt I don't think this is supported. I don't know if this is what you mean by asking, what happens?

**Comment by MEM-917** [comment]
> > Unless the path in SpiderX is the list of other certificates. If that is the case, what should be in the designated path?
> 
> I haven't tried to fill in a directory path to specify the content of this parameter, for example /root/a.txt I don't think this is supported. I don't know if this is what you mean by asking, what happens?

In Mr. [Sanaei's](https://github.com/MHSanaei/3x-ui) panel, I've experimented with different fillings for this parameter. There is absolutely no effect in connection whatsoever. E.g. if you put "/docs/" in  SpiderX, you can use the client without this or with a completely different string. Thus, it is redundant.
I haven't tried putting a json or txt file in the directory to see what happens. But the only thing that comes to mind is that it is an arbitrary parameter for circumventing censorship by deceiving filtering authority that you're visiting some specific website with a detailed path.

**Comment by chika0801** [comment]
If you ask the author's thought process when this parameter was devised. From what I remember, it was around the time that the designer wanted the client to have some traffic from other requests as well. The designer of this parameter has not published a detailed documentation to explain it, only some webmasters look at the usage commented in the code. If you know the code, you can study it yourself.

It is in mainland China in the self-built node users, usually very little to fill in anything, we generally leave the default blank did not write, that is, the use of the default value.

**Comment by MEM-917** [comment]
> If you ask the author's thought process when this parameter was devised. From what I remember, it was around the time that the designer wanted the client to have some traffic from other requests as well. The designer of this parameter has not published a detailed documentation to explain it, only some webmasters look at the usage commented in the code. If you know the code, you can study it yourself.
> 
> It is in mainland China in the self-built node users, usually very little to fill in anything, we generally leave the default blank did not write, that is, the use of the default value.

Thanks. I don't know GO language but it shouldn't be that much hassle to understand what it does and how it does. I will update this post on my findings; in the meantime, it's safe to say its mechanism is to manipulate DPI from the client side.

**Comment by WuSiYu** [comment]
It's documented here: https://github.com/XTLS/REALITY/blob/main/README.en.md (see crawler mode), so it only used when mitm happens, the reality server has been "bypassed", then client will acting as a crawler, the SpiderX option is the path to fetch
