### ISSUE TITLE
CLI tool

### ISSUE THREAD

**Issue by lilendian0x00** [XTLS/Xray-core#2660]
I've written a useful cli tool for UNIX users.

Is it possible to add this tool to your README so ppl can make use of it?

https://github.com/lilendian0x00/xray-knife

**Comment by chika0801** [comment]
https://github.com/XTLS/Xray-core/pulls

You can fork and then modify Readme.md, I suspect you should be welcomed!

**Comment by lilendian0x00** [comment]
> https://github.com/XTLS/Xray-core/pulls
> 
> You can fork and then modify Readme.md, I suspect you should be welcomed!

Done!
https://github.com/XTLS/Xray-core/pull/2663

**Comment by lilendian0x00** [comment]
@yuhan6665 Appreciate it much for the merge 🤝
