### ISSUE TITLE
xray 1.84 提示：Please use VLESS flow "xtls-rprx-vision" with TLS or REALITY.如何修改配置文件？

### ISSUE THREAD

**Issue by crazynet999** [XTLS/Xray-core#2662]
Oct 24 05:27:20 instance-20200804-1003 systemd[1]: Started Xray Service.
Oct 24 05:27:20 instance-20200804-1003 xray[18569]: Xray 1.8.4 (Xray, Penetrates Everything.) Custom (go1.21.0 linux/amd64)
Oct 24 05:27:20 instance-20200804-1003 xray[18569]: A unified platform for anti-censorship.
Oct 24 05:27:20 instance-20200804-1003 xray[18569]: 2023/10/24 05:27:20 [Info] infra/conf/serial: Reading config: /usr/local/etc/xray/config.json
Oct 24 05:27:20 instance-20200804-1003 xray[18569]: Failed to start: main: failed to load config files: [/usr/local/etc/xray/config.json] > infra/conf: Please use VLESS flow "xtls-rprx-vision" with TLS or REALITY.
Oct 24 05:27:20 instance-20200804-1003 systemd[1]: xray.service: Main process exited, code=exited, status=23/n/a
Oct 24 05:27:20 instance-20200804-1003 systemd[1]: xray.service: Failed with result 'exit-code'.
配置文件如下：
{
    "log": {
        "loglevel": "warning"
    },
    "inbounds": [
        {
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "XXXXXXXXXXXXXXXXXXX", // 填写你的 UUID
                        "flow": "xtls-rprx-direct",
                        "level": 0,
                        "email": "XXXXXXXXXXXX@gmail.com"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": 1310, // 默认回落到 Xray 的 Trojan 协议
                        "xver": 1
                    },
                    {
                        "path": "/websocket", // 必须换成自定义的 PATH
                        "dest": 1234,
                        "xver": 1
                    },
                    {
                        "path": "/vmesstcp", // 必须换成自定义的 PATH
                        "dest": 2345,
                        "xver": 1
                    },
                    {
                        "path": "/vmessws", // 必须换成自定义的 PATH
                        "dest": 3456,
                        "xver": 1
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "alpn": [
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "/etc/ssl/fullchain.pem",               // 换成你的证书，绝对路径
                            "keyFile": "/etc/ssl/key.pem"     // 换成你的私钥，绝对路径
                        }
                    ]
                }
            }
        },
        {
            "port": 1310,
            "listen": "127.0.0.1",
            "protocol": "trojan",
            "settings": {
                "clients": [
                    {
                        "password": "XXXXXXXXXXXXX", // 填写你的密码
                        "level": 0,
                        "email": "cXXXXXXXXXXXXXXXXX@gmail.com"
                    }
                ],
                "fallbacks": [
                    {
                        "dest": 80 // 或者回落到其它也防探测的代理
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "none",
                "tcpSettings": {
                    "acceptProxyProtocol": true
                }
            }
        },
        {
            "port": 1234,
            "listen": "127.0.0.1",
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "XXXXXXXXXXXXX", // 填写你的 UUID
                        "level": 0,
                        "email": "XXXXXXXXXXX9@gmail.com"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "ws",
                "security": "tls",
                "wsSettings": {
                    "acceptProxyProtocol": true, // 提醒：若你用 Nginx/Caddy 等反代 WS，需要删掉这行
                    "path": "/websocket" // 必须换成自定义的 PATH，需要和分流的一致
                }
            }
        },
        {
            "port": 2345,
            "listen": "127.0.0.1",
            "protocol": "vmess",
            "settings": {
                "clients": [
                    {
                        "id": "XXXXXXXXXXXXXXXXX", // 填写你的 UUID
                        "level": 0,
                        "email": "cXXXXXX@gmail.com"
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "none",
                "tcpSettings": {
                    "acceptProxyProtocol": true,
                    "header": {
                        "type": "http",
                        "request": {
                            "path": [
                                "/vmesstcp" // 必须换成自定义的 PATH，需要和分流的一致
                            ]
                        }
                    }
                }
            }
        },
        {
            "port": 3456,
            "listen": "127.0.0.1",
            "protocol": "vmess",
            "settings": {
                "clients": [
                    {
                        "id": "XXXXX", // 填写你的 UUID
                        "level": 0,
                        "email": "CXXXXXX@gmail.com"
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "security": "none",
                "wsSettings": {
                    "acceptProxyProtocol": true, // 提醒：若你用 Nginx/Caddy 等反代 WS，需要删掉这行
                    "path": "/vmessws" // 必须换成自定义的 PATH，需要和分流的一致
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "settings": {
              "domainStrategy": "UseIPv6"
              //设置默认用户走指定方式”UseIPv6”或者”UseIPv4”
          }
        }
    ]
}

**Comment by FranzKafkaYu** [comment]
@crazynet999   
参考：https://github.com/XTLS/Xray-examples/blob/main/VLESS-TCP-XTLS-Vision/config_server.json

**Comment by crazynet999** [comment]
那现在是不是WS没有用了，都是TCP的，更换了之后TCP可以，WS不行了，


另外，什么时候更新这个？

https://github.com/XTLS/Xray-examples/tree/main/VLESS-TCP-XTLS-WHATEVER

**Comment by chise0713** [comment]
See https://github.com/XTLS/Xray-examples/tree/main/VLESS-TCP-XTLS-Vision-REALITY

**Comment by yuhan6665** [comment]
> 那现在是不是WS没有用了，都是TCP的，更换了之后TCP可以，WS不行了，
> 
> 另外，什么时候更新这个？
> 
> https://github.com/XTLS/Xray-examples/tree/main/VLESS-TCP-XTLS-WHATEVER

文档需要大家的帮忙 :)
