### ISSUE TITLE
xray怎么测速啊

### ISSUE THREAD

**Issue by xiezy1** [XTLS/Xray-core#2665]

**Comment by chise0713** [comment]
https://testfiledownload.com/

**Comment by xiezy1** [comment]
xray 怎么测试节点的质量 我是在Linux上使用 没有图形化界面

**Comment by chise0713** [comment]
curl

**Comment by Fangliding** [comment]
单线程 wget speed.cloudflare.com/__down?bytes=1145141919810 -O /dev/null
以及这种问题不要发issue

**Comment by xiezy1** [comment]
> curl

我想实现批量测试所有节点 要一个个使用config 然后测试吗 这样好麻烦 而且速度很慢  实现windows软件里的一件测速得功能

**Comment by xiezy1** [comment]
> 单线程 wget speed.cloudflare.com/__down?bytes=1145141919810 -O /dev/null 以及这种问题不要发issue

🆗

**Comment by Fangliding** [comment]
> > 单线程 wget speed.cloudflare.com/__down?bytes=1145141919810 -O /dev/null 以及这种问题不要发issue
> 
> 🆗

复制错了
curl -x "socks5://127.0.0.1:1080" -o /dev/null http://speed.cloudflare.com/__down?bytes=1145141919810 -w
应该是这样(?) 端口换成自己的
