### ISSUE TITLE
透明代理导致外部dns请求异常

### ISSUE THREAD

**Issue by ChuLiqiang** [XTLS/Xray-core#2668]
参照文档配置完毕后，在其它主机用nslookup 测试dns服务器的，发现www.baidu.com域名解析超时。此时把iptables规则删掉后nslookup工具查询正常。有几个点特别奇怪。
1.配置完毕后，确实透明代理功能是正常的。只要把需要其它的机器dns和网关配置为透明代理ip即可
2.但是使用nslookup和dig工具直接测试dns服务器是失败的。
想了半天没想清楚为啥，求大家解惑。

https://xtls.github.io/document/level-2/tproxy.html#%E5%BC%80%E5%A7%8B%E4%B9%8B%E5%89%8D

**Comment by chika0801** [comment]
建议关了，发到讨论区更好。
