### ISSUE TITLE
v2ray怎么更换为Xray的内核与Xray协议

### ISSUE THREAD

**Issue by hfhgtfghf3443** [XTLS/Xray-core#267]
客户端是直接把v2ray内核替换成xray内核，服务器端怎么替换？也是直接把把v2ray内核替换成xray内核就可以了吗？

如果协议原来是v2ray的vmess+ws+tls+caddy或vless+ws+tls+caddy协议，怎么换成xray的vmess+ws+tls+caddy或vless+ws+tls+caddy协议？需要更改哪些内容呢？还是说不用更改协议把内核替换好就可以了

**Comment by AkinoKaede** [comment]
配置文件无需修改，更换软件请查阅相关文档。

**Comment by hfhgtfghf3443** [comment]
那原來的協議會不會被替換，我可以先把原來的配置文件拷貝出來，安裝好xray后再還原回去嗎？

**Comment by hfhgtfghf3443** [comment]
> 
> 
> 服务端使用 XTLS/Xray-install 安装，配置文件无需修改，客户端请查阅相关文档。
> 文档: https://xtls.github.io
> Telegram Group: https://t.me/projectXray

那原來的配置文件會不會被替換，我可以先把原來的配置文件拷貝出來，安裝好xray后再還原回去嗎？

**Comment by hfhgtfghf3443** [comment]
知道了

**Comment by AkinoKaede** [comment]
> 那原來的協議會不會被替換，我可以先把原來的配置文件拷貝出來，安裝好xray后再還原回去嗎？

如果原来使用 v2fly/fhs-install-v2ray 安装，只需在使用 XTLS/Xray-install 安装后将 /usr/local/etc/v2ray/config.json 拷贝至 /usr/local/etc/xray/config.json

**Comment by hfhgtfghf3443** [comment]
> 
> 
> > 那原來的協議會不會被替換，我可以先把原來的配置文件拷貝出來，安裝好xray后再還原回去嗎？
> 
> 如果原来使用 v2fly/fhs-install-v2ray 安装，只需在使用 XTLS/Xray-install 安装后将 /usr/local/etc/v2ray/config.json 拷贝至 /usr/local/etc/xray/config.json

原來是用第三方脚步安裝的，它的替換方式是一樣的吧，替換配置文件就可以了。

**Comment by hfhgtfghf3443** [comment]
原來是用第三方脚步安裝的，它的替換方式是一樣的吧，替換配置文件就可以了。

**Comment by hfhgtfghf3443** [comment]
知道了
