### ISSUE TITLE
求助，手动搭建的xray reality使用客户端连接无任何反应，努力了好久也无法解决

### ISSUE THREAD

**Issue by bubuqing99** [XTLS/Xray-core#2673]
这是我的服务端配置：

{
    "inbounds": [ // 服务端入站配置
        {
            "listen": "0.0.0.0",
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "f6350f71-1a3f-4c86-a70e-25c12beb7e4f", // 必填，执行 ./xray uuid 生成，或 1-30 字节的字符串
                        "flow": "xtls-rprx-vision" // 选填，若有，客户端必须启用 XTLS
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "tcp",
                "security": "reality",
                "realitySettings": {
                    "show": false, // 选填，若为 true，输出调试信息
                    "dest": "www.microsoft.com:443", // 必填，格式同 VLESS fallbacks 的 dest
                    "xver": 0, // 选填，格式同 VLESS fallbacks 的 xver
                    "serverNames": [ // 必填，客户端可用的 serverName 列表，暂不支持 * 通配符
                        "microsoft.com",
                        "www.microsoft.com"
                    ],
                    "privateKey": "cPU7apa0GTR0ItU7VHEcu17TXhRYC2xi0brNkO2xRV8", // 必填，执行 ./xray x25519 生成
                    "minClientVer": "", // 选填，客户端 Xray 最低版本，格式为 x.y.z
                    "maxClientVer": "", // 选填，客户端 Xray 最高版本，格式为 x.y.z
                    "maxTimeDiff": 0, // 选填，允许的最大时间差，单位为毫秒
                    "shortIds": [ // 必填，客户端可用的 shortId 列表，可用于区分不同的客户端
                        "", // 若有此项，客户端 shortId 可为空
                        "22" // 0 到 f，长度为 2 的倍数，长度上限为 16
                    ]
                }
            }
        }
    ]
}

下面是使用v2rayn客户端的配置

![image](https://github.com/XTLS/Xray-core/assets/57699051/590c55da-a515-4057-b7b4-1b8f4d7d6086)

输入systemctl status xray没有看到任何报错，v2rayn客户端也没报错。服务器443端口检测过没有被封，不知道是什么问题，我都懵了。

**Comment by kingwilliam** [comment]
microsoft 已封锁 xtls reality, 选期他 试试

**Comment by bubuqing99** [comment]
> microsoft 已封锁 xtls reality, 选期他 试试
> 
> [#2247 (comment)](https://github.com/XTLS/Xray-core/issues/2247#issuecomment-1606004024)

谢谢，我的是甲骨文云，难怪
