### ISSUE TITLE
具体特殊域名走特殊出口

### ISSUE THREAD

**Issue by junmin** [XTLS/Xray-core#2674]
目前已经在一个服务器B上配置了 VLESS-XTLS，大部分网站都正常访问。

但是发现一些自己常用的网站，限制了某些地域IP的访问又或者如果侦测到IP来自数据中心就不让访问，家庭普通IP就可以，所以这种情况，尽管是翻出去了也没用，甚至翻到了对应的国家也没用。

我想到一个办法，就是在对应的国家的家庭网络里 C 配置XRAY ，连接到已经配置好的公网上的B，如果需要访问某具体域名，就将请求转到 C 那里去访问。

但是我不知道这样的方法能不能实现，如果可以，大概是需要怎么样去配置？有什么可行的组合？希望大家帮忙一下，给点提示也可以。谢谢

**Comment by csryt** [comment]
@junmin 参考众多的 dokodemo door解锁范例 ，参考project X 官网route / outbound / inbound。

**Comment by csryt** [comment]
@junmin 这等小事，进群 https://t.me/projectXray  准备好搜索引擎，进群的验证题比较有趣

**Comment by chika0801** [comment]
B上看这段
https://github.com/chika0801/Xray-examples/blob/e4ac7a61ecd4ad75b3395fddeaf0efca052e2d00/self-use/Xray_server_primary.json#L19

C上看这段
https://github.com/chika0801/Xray-examples/blob/e4ac7a61ecd4ad75b3395fddeaf0efca052e2d00/self-use/Xray_server_secondary.json

**Comment by StarPriest** [comment]
验证码看这段
![image](https://github.com/XTLS/Xray-core/assets/18069281/bd952c13-38ca-43f0-99da-0904d73251cc)

**Comment by iKira** [comment]
方法一
xray-core用路由规则分流，仔细看看xray-core的官方文档。

方法二
Nginx stream模块分流，参考：
```
stream {
	map $ssl_preread_server_name $name {
		example.com forward;
	}
	upstream forward {
		server ip:port;
	}
	server {
		listen 443 reuseport;
		listen [::]:443 reuseport;
		proxy_pass $name;
		ssl_preread on;
	}
}
```

**Comment by junmin** [comment]
@csryt @chika0801 @iKira 

刚刚搞定了，是您们说的方法，用的 xray-core 路由配置

谢谢您们的帮忙
