### ISSUE TITLE
形如能分流吗？

### ISSUE THREAD

**Issue by ShotoZhao** [XTLS/Xray-core#2678]
rt

**Comment by xqzr** [comment]
对于 https 路径被加密，无法读取
对于 http 可以使用 `attrs`

**Comment by Fangliding** [comment]
@ShotoZhao 1 可以解密还要加密干嘛 办法当然有 自己装证书然后mitm 巨麻烦而已
2 域名放在SNI 是明文的

**Comment by xqzr** [comment]
> > 对于 https 路径被加密，无法读取 对于 http 可以使用 `attrs`
> 
> 两个疑问：
> 
> 1. 加密后不能解密吗？
> 2. 既然路径被加密了，为什么能匹配域名？
>    @xqzr  大佬请解答-.-

浏览器和站点才能解密
域名是域名；路径是路径
`https://<域名>/<路径>`
域名可以通过 未加密的 SNI 获取

**Comment by ShotoZhao** [comment]
> > > 对于 https 路径被加密，无法读取 对于 http 可以使用 `attrs`
> > 
> > 
> > 两个疑问：
> > 
> > 1. 加密后不能解密吗？
> > 2. 既然路径被加密了，为什么能匹配域名？
> >    @xqzr  大佬请解答-.-
> 
> 浏览器和站点才能解密 域名是域名；路径是路径 `https://<域名>/<路径>` 域名可以通过 未加密的 SNI 获取

好的，感谢解惑。

**Comment by ShotoZhao** [comment]
> @ShotoZhao 1 可以解密还要加密干嘛 办法当然有 自己装证书然后mitm 巨麻烦而已 2 域名放在SNI 是明文的

ok
