### ISSUE TITLE
求大佬们支持【hysteria】协议，用了很久家宽和IDC都很很丝滑。有缺点，但是好用

### ISSUE THREAD

**Issue by abcskjowjeoj** [XTLS/Xray-core#2679]
如题。
之前我也跟风说UDP 缺点XXXXX，比较抵触UDP类的协议(工具)。
后面我尝试了hy，真的好用。
虽然有缺点，也应该看到他的优点。
多支持点协议，累死GFW，让他们加班加到S。

用事实说话，跑了几百T流量。强烈推荐支持。也推荐其他大佬PR/DIY。

**Comment by abcskjowjeoj** [comment]
> 如题。 之前我也跟风说UDP 缺点XXXXX，比较抵触UDP类的协议(工具)。 后面我尝试了hy，真的好用。 虽然有缺点，也应该看到他的优点。 多支持点协议，累死GFW，让他们加班加到S。
> 
> 用事实说话，跑了几百T流量。强烈推荐支持。也推荐其他大佬PR/DIY。

可以加个hy inbound试试。

**Comment by chika0801** [comment]
详见 https://github.com/XTLS/Xray-core/issues/2635

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/issues/3547#issuecomment-2232800832
