### ISSUE TITLE
对于reality客户端身份验证方式的担忧

### ISSUE THREAD

**Issue by kyber1024** [XTLS/Xray-core#2682]
通过阅读[代码](https://github.com/XTLS/Xray-core/blob/d24a636c7523a6830327344a610cd3c40afddd2a/transport/internet/reality/reality.go#L157C23-L157C23)，注意到reality通过公钥的方式加密包含了xray版本，时间戳，client hello随机数等信息的session ID。并通过这种方式来向服务器证明客户端的合法性，从而收到服务端通过临时信任证书签名的回复，建立vless连接。
如同[tls1.3标准](https://datatracker.ietf.org/doc/html/rfc8446)提到的那样，session ID在真实的tls1.3握手过程中是可选的，原文为
This "compatibility mode" is partially negotiated: the client can opt to provide a session ID or not, and the server has to echo it. Either side can send
这意味着session ID存在与否都不会实际影响tls1.3握手，其在tls1.3中并非重要的部分，也不会有任何形式的验证，如果中间人篡改甚至删除这部分，服务端和客户端都不会有任何感知，但是session ID如果遭到篡改却会导致reality无法建立vless连接，只能进入爬虫模式。如果防火墙随机修改sessionID，然后观察客户端与服务端变化，是否可以识别reality。更进一步，无条件随机篡改所有tls1.3流量的session ID也可以完美封杀所有reality连接。

**Comment by RPRX** [comment]
> 这意味着session ID存在与否都不会实际影响tls1.3握手，其在tls1.3中并非重要的部分，也不会有任何形式的验证，如果中间人篡改甚至删除这部分，服务端和客户端都不会有任何感知

×

**Comment by RPRX** [comment]
~~为了回复这个 ×，花了些时间研究出了如何仅用 tor browser 开 2FA，GitHub 真会折腾人~~

**Comment by kyber1024** [comment]
重新检查了tls1.3协议。感谢协议设计者留下了session ID这样一个空间够大又可以高度自定义还安全无关的空间，甚至愿意用AEAD和签名来保护这片区域。他真的，我哭死

**Comment by nursery01** [comment]
設計者要是去掉的話，訪問tls1.2的網站就有問題了

**Comment by GreatBigWhiteWorld** [comment]
好像确实遇到了针对reality协议阻断的攻击，客户端日志正常，服务端日志无连入记录。检测服务器可ping，各个服务端口可正常连接服务，却只有reality翻墙流量无法到达服务器却不被客户端感知。
因为并不是新配置而是正常使用了很长时间的情况下突然出现以上情况，所以可以排除是配置问题。

**Comment by chika0801** [comment]
> 好像确实遇到了针对reality协议阻断的攻击，客户端日志正常，服务端日志无连入记录。检测服务器可ping，各个服务端口可正常连接服务，却只有reality翻墙流量无法到达服务器却不被客户端感知。 因为并不是新配置而是正常使用了很长时间的情况下突然出现以上情况，所以可以排除是配置问题。

https://github.com/XTLS/Xray-core/issues/2647
如果你遇到的环境和这类似

**Comment by RPRX** [comment]
~~纠错时间到~~

> 注意到reality通过公钥的方式加密包含了xray版本，时间戳，client hello随机数等信息的session ID

不是公钥加密，而是 x25519、hkdf 后用 aes-256-gcm 或 chacha20-poly1305 加密版本、时间戳、short id，附加验证数据为整个 client hello（除了前五字节和 session id），密文填充至 session id

> 那部分如果被中間人改了，伺服器那邊就不會進入vpn模式，因為shortid對不上號

是因为对 session id 的 aead 解密失败

> 好像确实遇到了针对reality协议阻断的攻击，客户端日志正常，服务端日志无连入记录

~~如果服务端日志无连入记录，客户端日志很难正常吧~~

**Comment by nursery01** [comment]
> 是因为对 session id 的 aead 解密失败

對的，我看到了，看代碼，我原本以為sessionid[0]固定是1，後來抓包了一下發現是加密隨機的，這個沒問題，不會成為特質

**Comment by GreatBigWhiteWorld** [comment]
> 
> ~如果服务端日志无连入记录，客户端日志很难正常吧~

我错了！原来loglevel要设置成warning才可以看到这种失败信息，之前是error级别。。。
无法连接的时候客户端的大量错误是：
`app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [context canceled dial tcp *.*.*.*:8443: operation was canceled] > common/retry: all retry attempts failed`
不过我的疑惑还是出现这种无法连接时ip正常ping，端口从本机用nc命令检测也是通的，不像我以前被断流时会出现要么ip要么端口检测不通了。这不是说墙可以在不封ip和端口的情况下只干扰reality流量？


> #2661 如果你遇到的条件和这类似

我连接失败时是各种客户端都同时无法连接（同一网络运营商环境）。但是持续有时几小时后会恢复正常。

**Comment by nursery01** [comment]
我想了想，1樓的觀點可能是，其實gfw可以刪除所有針對1.3網站的請求session ID，這樣所有reality就會變成網站模式，並且正常的1.3網站應該是能正常訪問的

這種方法從技術上能封鎖reality，但是從技術上無法識別它是否是reality，需要配合社會學，假如這個reality有大量請求，刪除session ID後請求數量下滑，這就有問題了

@kyber1024 你是這樣想的吧

**Comment by RPRX** [comment]
> 我想了想，1樓的觀點可能是，其實gfw可以刪除所有針對1.3網站的請求session ID，這樣所有reality就會變成網站模式，並且正常的1.3網站應該是能正常訪問的
> 
> 這種方法從技術上能封鎖reality，但是從技術上無法識別它是否是reality，需要配合社會學，假如這個reality有大量請求，刪除session ID後請求數量下滑，這就有問題了

×

我说明白一些，TLSv1.3 的 hkdf 包含 Client Hello 和 Server Hello 的数据，中间人进行任何修改都会导致加密密钥不匹配、解密失败

所以，这个 issue 是 @kyber1024 当时未研究透 TLSv1.3 的机制，而提出的根本不存在的问题
