### ISSUE TITLE
v2fly更新了一个新的传输方式httpupgrade，xray会跟进吗？

### ISSUE THREAD

**Issue by HXHGTS** [XTLS/Xray-core#2684]
v2fly更新了一个新的传输方式httpupgrade，理论上可以减小性能开销，xray会跟进吗？

**Comment by RPRX** [comment]
来个 PR

**Comment by RPRX** [comment]
~~说实话 i don't care any of these，ALPN 为 http/1.1 始终是硬伤，所以有 pr 就合，没 pr 就算了，doesn't matter~~

**Comment by yomnxkcs** [comment]
这个和ws的Early Data应该不是同一个东西。ed是用来减少rtt的。

注意哈，我不懂golang也没看过v2ray的源码，下面的分析可能完全是错！

ws请求可以简单的描述为以下过程
1.浏览器发送一个http格式的请求给服务器，告诉它我们改用ws协议通信
2.服务器回复好的
3.浏览器把数据封装成一个ws格式的消息发给服务器
4.服务器回复一个ws格式的消息
重复3，4两步骤

按v2fly那边的描述httpupgrade就是在第3，4步中把封装这步省掉，不用ws格式直接发送数据。大概就是省点CPU吧。

但是如果真是这么玩，从外面观察会看到一个ws链接里面传的数据却不是ws格式，明显的挂羊头卖狗肉嘛。
不过套上TLS之后可能就看不出来。

**Comment by RPRX** [comment]
今天喝死我了草，在酒吧就已经喝醉了，宵夜又 tm 被灌了几瓶啤的，一群傻逼玩意儿，睡觉了

**Comment by Nyar233** [comment]
> 今天喝死我了草，在酒吧就已经喝醉了，宵夜又 tm 被灌了几瓶啤的，一群傻逼玩意儿，睡觉了

nb 哈哈哈

**Comment by RPRX** [comment]
我就告诉你们，坐标广州，珠江新城，经常去夜店美女女围局抓手指，180+帅哥，能不能找到我

**Comment by RPRX** [comment]
哦不好意思，花城汇和琶醍的酒吧和帅哥美女太多，~~怕是找不到我，没什么事我就先睡了，fuck you~~

**Comment by RPRX** [comment]
~~下次开黑桃 A 请群友来喝~~

**Comment by JASONSE-LIN** [comment]
今晚消费又R公子买单~🎉🎉🎉

**Comment by RPRX** [comment]
GFW 就该摆烂，这样我能天天去夜店蹦迪，不然我还要写代码，写你妈的代码

**Comment by RPRX** [comment]
TMD 傻逼 GFW 让我花了大量时间搞 anti-censorship，有这时间去和美女亲嘴不香吗

**Comment by RPRX** [comment]
不好意思又说错了，什么亲嘴拉丝局什么的，~~绝对没去过~~

**Comment by RPRX** [comment]
老子去的都是正经帅哥美女局，男 a 女免、重度卡颜的那种，把你卡到酒吧门口和保安舞拳

**Comment by ihuanx** [comment]
哈哈哈哈哈哈  怪不得不更新了  染上酒瘾了

**Comment by RPRX** [comment]
> 哈哈哈哈哈哈 怪不得不更新了 染上酒瘾了

什么酒瘾啊，一点都不喜欢喝酒，去夜店主要是为了去和美女玩游戏的，都怪 GFW 不给力，没啥事做不就天天去酒吧玩吗

**Comment by RPRX** [comment]
下次来我的局啊，都是顶颜美女和180+帅哥，~~哦好像不能在这里拉人，不然暴露了~~，真睡了，安，今晚继续，蹦不死就往死里蹦

**Comment by HXHGTS** [comment]
666

**Comment by chise0713** [comment]
~~r佬发病了~~

**Comment by mclovin-2k** [comment]
几个菜啊 喝成这样

**Comment by Michaol** [comment]
> 我就告诉你们，坐标广州，珠江新城，经常去夜店美女女围局抓手指，180+帅哥，能不能找到我

我叼，原来R佬在珠江新城……得闲叫声，一齐吹水

**Comment by v03413** [comment]
不愧是R佬  🤣

**Comment by isr4z6er** [comment]
大佬们保重... 但是感觉有意无意泄漏自己信息还是太危险了，前车之鉴啊..

**Comment by maxfun0** [comment]
也许是虚晃一枪

**Comment by koiNoCirculation** [comment]
这是随机爆了一个地址然后让国安国宝白干一次是吧。

**Comment by RockNHawk** [comment]
大佬这么潇洒，谁能想到天天用的软件的作者是个天天去酒吧的大帅哥。
可惜不能来个 cross wall 作者颜值大 PK😅

**Comment by Tiiiiiida** [comment]
几个菜啊，喝成这样

**Comment by yzx1208** [comment]
RPRX这是喝了多少？不会待会也删了再断片？那就天路断绝！

**Comment by 1f-small-Xue-study-today** [comment]
慕名而来，合影

**Comment by lanbinshijie** [comment]
R佬注意身体（从各种意义上）

**Comment by j33h22** [comment]
快进到喝酒喝断片

**Comment by tianyilt** [comment]
R佬🐂🍺

**Comment by cross-hello** [comment]
Oh, why such depravity

**Comment by changev** [comment]
合影留念

**Comment by HeinousAgenda38** [comment]
合影

**Comment by shwangdev** [comment]
合影

**Comment by Papklp** [comment]
合影

**Comment by RuiFG** [comment]
合影

**Comment by Weltolk** [comment]
mark

**Comment by Fangliding** [comment]
@Weltolk 这下这成了有名合影帖了

**Comment by thisdk** [comment]
合影合影

**Comment by Ericwln** [comment]
kakaka

**Comment by Weltolk** [comment]
> @Weltolk 这下这成了有名合影帖了

mark

**Comment by dainslef** [comment]
mark

**Comment by fan51** [comment]
每天看你们聊天都能笑死😂

**Comment by junlongzzz** [comment]
沃~得~发~
O_◥左眼 用来忘记你
◤_O右眼 用来记住你
◤_O我记住了你
O_◥又忘记了你
他们都叫我King
（转身）（回头）O_◥

**Comment by jt1174595239** [comment]
已经有人把这段截图发公众号了

**Comment by Scott169** [comment]
也来mark一下

**Comment by HeinousAgenda38** [comment]
> 已经有人把这段截图发公众号了

这种人要么是傻子，要么是吃人血馒头的

**Comment by yqk100** [comment]
> 已经有人把这段截图发公众号了

直接举报传播xx

**Comment by Ducking69** [comment]
合影🤣

**Comment by WLOANOAK** [comment]
笑死我了

**Comment by jt1174595239** [comment]
别人发内网了 https://mp.weixin.qq.com/s/Mwb14jsUCtOAWV2NU_vNOA

**Comment by wanxiaochao** [comment]
刚看到 大佬这是喝的有点嗨了啊

**Comment by BoBoooooo** [comment]
mark ~

**Comment by RPRX** [comment]
> 接着 Xray-core 作者自爆了，表示已经无所谓了。

我那些 comments 都是 11.1 发的，而 Clash 等项目删库是 [11.2](https://github.com/net4people/bbs/issues/303) 开始的，时间都搞反了，还强拉因果关系，搁这儿写三国演义呢？

> 这些事件反映了当前网络环境和信息安全面临的严峻形势。所以各位网友，我们应该保持理智上网，不要过分偏激。

搞 IT 技术的要么会翻墙要么是垃圾，平时自己翻，但是发公众号上，哎，得谴责一下，就像公开会谴责别人 ghs，但私下里谁都想 ghs，太虚伪了吧，一个个都习惯了说假话，畸形社会舆论环境的必然产物。

**Comment by maskedeken** [comment]
[https://github.com/XTLS/Xray-core/pull/3087](https://github.com/XTLS/Xray-core/pull/3087)

**Comment by yuhan6665** [comment]
虽然是网红打卡景点但是~~作为专业的反审查工作者~~还是关了
