### ISSUE TITLE
关于路由规则，能否求一份相对完整的范例？

### ISSUE THREAD

**Issue by ffplayer** [XTLS/Xray-core#2689]
从clash转过来，之前好容易摸清楚了parser，可以自己写规则，然而这两天。。

于是在啃关于路由的[指南文档](https://xtls.github.io/document/level-1/routing-lv1-part1.html#_3-3-%E8%B7%AF%E7%94%B1)，基础的概念基本都掌握了，但在想有没有一个相对完整一些的配置示例，这样自己上手改起来能快很多，能避免掉很多语法标点对齐之类的问题。
比如有范例之后自己直接增减其中的域名/源ip对应规则会能少走很多弯路

有没有哪位能分享一下？感谢！！

**Comment by chika0801** [comment]
你要详细说一下你的需求，别人才好帮你。

**Comment by yuhan6665** [comment]
建议看一下图形客户端 导出完整配置 :)

**Comment by chise0713** [comment]
[chika0801/Xray-examples ( VLESS-XTLS-uTLS-REALITY/config_client.json#L7-L24 ) ](https://github.com/chika0801/Xray-examples/blob/e1bd463b08cd59c206069ae2317e5399a9e34447/VLESS-XTLS-uTLS-REALITY/config_client.json#L7-L24)
https://github.com/XTLS/Xray-core/issues/1878

**Comment by AKotov-dev** [comment]
[JSON Validator](https://jsonlint.com/)
[JSON Formatter & Validator](https://jsonformatter.curiousconcept.com/)
[...如果這就是你的意思](https://www.google.com/search?q=json+validator&oq=json+va&gs_lcrp=EgZjaHJvbWUqCggAEAAYsQMYgAQyCggAEAAYsQMYgAQyBwgBEAAYgAQyBggCEEUYOTIHCAMQABiABDIHCAQQABiABDIHCAUQABiABDIHCAYQABiABDIHCAcQABiABDIHCAgQABiABDIHCAkQABiABNIBCTYzMjJqMGoxNagCALACAA&sourceid=chrome&ie=UTF-8)

**Comment by ffplayer** [comment]
感谢各位提示，我再研究下，后续会发到Discussions去。
