### ISSUE TITLE
Xray Vision BUG

### ISSUE THREAD

**Issue by X-Oracle** [XTLS/Xray-core#2690]
client: 1.8.4  (Vless + TCP + reality +vision)
server: 1.8.4

it will end up in `EOF`, if I enable `mux.cool` and set `concurrency` to non-negative number.

`xudpConcurrency` works but need to set `concurrency` to `-1` .

**Comment by yuhan6665** [comment]
Currently you cannot use vision with mux (and set `concurrency` to non-negative number)
