### ISSUE TITLE
请问如何不代理二级域名,仅代理一级域名?

### ISSUE THREAD

**Issue by DiritoTech** [XTLS/Xray-core#2699]
因为想用new bing, 需要代理bing.com
但是代理了之后就无法使用cn.bing.com这个域名的国内必应搜索了，会自动跳转bing.com

是否有办法做到cn.bing.com直连，bing.com代理，而且也不会互相跳转呢？

**Comment by kingwilliam** [comment]
https://xtls.github.io/config/routing.html#ruleobject

可参考domain部份
domain: [string]
