### ISSUE TITLE
请问SSR+能支持Xray嘛？

### ISSUE THREAD

**Issue by linus4532** [XTLS/Xray-core#27]
能让SSR+支持Xray嘛？比如模拟成v2ray

**Comment by rprx** [comment]
请详细描述（加混淆？）

**Comment by kousyougi** [comment]
編譯lede固件 https://github.com/coolsnowwolf/lede/，make menuconfig 已經可以選xray了。
https://github.com/fw876/helloworld/blob/master/luci-app-ssr-plus/Makefile

**Comment by rprx** [comment]
@linus4532 

如果你指的是 openwrt 的 ssr plus 插件，最新版已经有 Xray 了，但据群友反馈现在可能存在些问题，建议过两天尝试。
