### ISSUE TITLE
关于16.02.2021晚间群聊事件的道歉和解释性说明

### ISSUE THREAD

**Issue by NutterChen** [XTLS/Xray-core#270]
先说明一下，我是 Xray.sh 和 Xray.dog 域名的持有者，此事件也与此域名有关。

今晚在Project X群中看到有人在说俄罗斯政局稳定与否的事情，作为长期在俄罗斯居住生活的人，我对此当然来了兴趣，就开启了滔滔不绝模式，其实也不算涛涛不绝，大概20句话以下，随后 "理性 吃瓜“ 老师来了，对我进行了 禁止键政 警告，随后我意识到错误，并提出主动退群，然后我就退群了。

退群过后，我就继续做自己的事情，这是，另一位经常交流的朋友突然来问我为什么退群了，说管理员说我利用项目为自己宣传，这是我才意识到事情已然变味，马上用朋友的号看了群，发现我的所有发言已经被删除，并且 "理性 吃瓜“ 说我通过买域名的方式 让项目替我做宣传，我就很疑惑了 

![photo_2021-02-16_20-31-01.jpg](https://i.loli.net/2021/02/17/fMg8dyOjKp4YCcG.jpg)

我在Xray项目最初就注册了 Xray.sh 和 Xray.dog 这两个域名，最开始，我的计划是将 xray.sh 捐献给Xray项目作为安装脚本和wiki页面使用，我也与rprx就此事进行了商量，rprx的意思是，域名转入到他的名下，在注册商账户,whois或者续费时必定留下互联网痕迹，于是拒绝了此事；此部分的谈话内容，我刚才查看了与rprx的聊天记录，发现已经遗失，当然，我既然敢在这里发，就说明是真实情况，rprx如有印象，也可以为此作证。

随后，我自己写了个网页，用来统计各xray安装脚本的使用量；再到最后，Xray推出了自己的官方wiki页面，我就将此域名用于反代官方wiki页面，直到现在仍然是这样，以后也是；因为一开始我就说了，Xray.sh 就当公益了，而 Xray.dog 我可能商用。

再说 "理性 吃瓜“ 的做法和说法，在我退群后立马造谣我利用域名为自己宣传？此种说法从何而来？不可否认，我有基于Xray的盈利项目，但我从来未将这两个域名与我的盈利项目扯上关系。

随后，我联系  "理性 吃瓜“  询问是不是触及到他的利益，并道歉，而得到的说法确是 ”好，你觉得是谣言，我并无此意，我去删除了。您也别跟我这里玩文字游戏“，”我的嘴说我想说的话“；每个人当然有言论自由的权利，但是这样的发言，未免太过无理取闹？最后，甚至上升到”我不得不怀疑你对项目的友好程度“的高度，对于项目友好程度？这我自己定论。我也是从xtls在Project V项目时就开始关注了，我进Project X群的时候，群里大概才三十四个人，我对Project X项目在代码提交,测试和社区建设上算是无任何帮助吧，我仅仅是在每次新版本发布时测试下api接口，当然，即使是这也是为了我自己的项目。(如果当初想捐献域名和水群算的话，算是一点儿贡献？)

宣传一事，了解我的盈利项目的朋友应该知道，我只在我们自己群，另一个youtuber的群(他做过相关教程视频)里宣传过；另外，就是我的telegram昵称了；但是这和 Xray.sh 此域名有任何关联？

再说回关于”键政“的事情，这的确是我的错误，我再次再次道歉，对于那些被我影响到群友，对不起你们了，我已经引咎主动退出了群，以后不会也不能再”键政“；另外，对于"理性 吃瓜“ ，你对於整个项目的贡献，是有目共睹的，作为一个受益于此项目的人，我也向你表示感谢。

至于谣言的事情，我不爽的点是，在我退出群后，马上清除我的聊天记录，并做出这种无端的所谓的”我的嘴说我想说的话“的中伤，这种做法我....无言。你可以说是你的怀疑，但是请至少为自己说过的话负一点责任；虽然我平常表现得大大咧咧，甚至可能会讨人厌，但是真正与我有过交集的人，我相信你们对我会有一个公正客观的看法。清者自清，我问心无愧。

晚安。

**Comment by NutterChen** [comment]
![1.png](https://i.loli.net/2021/02/17/gIodGuzrlWQBY5a.png)

**Comment by NutterChen** [comment]
![photo_2021-02-16_20-44-29.jpg](https://i.loli.net/2021/02/17/rWbU12kIvCo9uze.jpg)

**Comment by NutterChen** [comment]
从 对话 来看，所谓的我用域名为自己 做宣传，"理性 吃瓜“ 无任何证据，当然，无中生有，如何得来证据，除非他再造另一个谣，而我的要求，则是让其 自己好好解释吧。

而其的解释 不过”言论谨代表我的观点“，我认为，言论谨代表我的观点，你完全可以在我退出群与我当面对质，而不是在我退出群后，立马清除我的所有聊天记录，然后造谣。

而后文的什么有话群里说，我主动退出后你还不忘立马给我ban了让我无法看到群里消息(或许怕被我看见？)；另外，你都有删除消息的前科了，我说啥你都可以删除吧？

**Comment by AkinoKaede** [comment]
这个不应该发在 Issues

**Comment by NutterChen** [comment]
仅说明下情况，我键政了，我退群了，这不是造谣我的理由，行为过于幼稚

**Comment by NutterChen** [comment]
以下是 理性 吃瓜 老师的原话

没有，项目建群之初他就在群里了，确定Xray的名字之后，他就去注册了xray.sh和xray.dog之类的

.dog我觉得对项目不友好，但是我没有说话，没有一个字的评价，因为也许他是爱狗人士

.sh 他做过自己的landing页，加过统计脚本，试图转移给rprx但是大佬出于安全考虑没要。我觉得他就是抢注、就是不顾大佬个人安危，但是我没有说话，没有一个字的评价，因为rprx没有要，他的个人安全不受影响。那么人家注册自己的网站，我无权插嘴。

但是当初水友问官方脚本和网站在哪里， 他发xray.sh 算什么事情？他哪里官方了？

后来文档站上线了，他也不发了，我就忘了这么档子事。

直到昨天，他一顿键政，不理会提醒，我不得不怀疑他对项目的友好程度，才想起以前域名的事。

他可以反代文档站，可以做统计脚本，确实没有做什么私事。但是这个域名在他个人手里，他做什么不行？我对他个人态度怀疑了，自然需要怀疑域名是否会被滥用。这就叫，造谣？
