### ISSUE TITLE
[Feature] 更细致的 API

### ISSUE THREAD

**Issue by DarkCWK** [XTLS/Xray-core#2703]
现在的api只能增删出入口代理, 连查询都不行, 一部分配置无法操作 (例如内置 DNS 服务器)
希望可以有更细致的api

**Comment by Fangliding** [comment]
@DarkCWK 增删出入站API这玩意属于远古遗迹 没啥人用 so not planned（）

**Comment by DarkCWK** [comment]
或者更新一下整个API？现在的API属于是鸡肋了 : (
或者干脆改成一个重新加载配置的 API?

**Comment by zxbiao** [comment]
> 或者更新一下整个API？现在的API属于是鸡肋了 : ( 或者干脆改成一个热重载配置的 API?

R大佬好像说过xray不考虑做热重载

**Comment by Acytoo** [comment]
> 或者更新一下整个API？现在的API属于是鸡肋了 : ( 或者干脆改成一个热重载配置的 API?

请问你知道有任何其他支持热加载的代理程序吗?

**Comment by DarkCWK** [comment]
> > 或者更新一下整个API？现在的API属于是鸡肋了 : ( 或者干脆改成一个热重载配置的 API?
> 
> 请问你知道有任何其他支持热加载的代理程序吗?

别人不做的功能就不做了么?

**Comment by DarkCWK** [comment]
> > 或者更新一下整个API？现在的API属于是鸡肋了 : ( 或者干脆改成一个热重载配置的 API?
> 
> R大佬好像说过xray不考虑做热重载

既然如此那就只能每次重新打开进程了

**Comment by iKira** [comment]
做这个是在为机场打免费工 :)

**Comment by DarkCWK** [comment]
> 做这个是在为机场打免费工 :)

为啥呢

**Comment by AsenHu** [comment]
> > 做这个是在为机场打免费工 :)
> 
> 为啥呢

我觉得做这个 API 是方便开发的，不能完全算给机场打工。
这样吧，你来实现一个👍

**Comment by DarkCWK** [comment]
> > > 做这个是在为机场打免费工 :)
> > 
> > 
> > 为啥呢
> 
> 我觉得做这个 API 是方便开发的，不能完全算给机场打工。 这样吧，你来实现一个👍

我只是像知道为什么...如果你说连原因都不能说可以当我没问过

**Comment by AsenHu** [comment]
> > > > 做这个是在为机场打免费工 :)
> > > 
> > > 
> > > 为啥呢
> > 
> > 我觉得做这个 API 是方便开发的，不能完全算给机场打工。 这样吧，你来实现一个👍
> 
> 我只是像知道为什么...如果你说连原因都不能说可以当我没问过

![Screenshot_20231116_132623.jpg](https://github.com/XTLS/Xray-core/assets/78863300/60f91785-c629-43c1-b4c5-9c67f969f233)

**Comment by DarkCWK** [comment]
> ![Screenshot_20231116_132623.jpg](https://user-images.githubusercontent.com/78863300/283330293-60f91785-c629-43c1-b4c5-9c67f969f233.jpg)

懂了, 我当时是只考虑了客户端方面
不过热重载应该不算为机场打工吧, 毕竟改完配置要重新启动挺麻烦的

**Comment by chika0801** [comment]
改完配置重启xray生效，在个人自建中习惯了的

**Comment by DarkCWK** [comment]
> 改完配置重启xray生效，在个人自建中习惯了的

嘛...只是每次都要找到来 kill 觉得挺麻烦的, 或许我应该开一个 issus 希望类似 nginx 的指令, api 确实看起来像给机场打工

**Comment by CosecantYu** [comment]
> > 改完配置重启xray生效，在个人自建中习惯了的
> 
> 嘛...只是每次都要找到来 kill 觉得挺麻烦的, 或许我应该开一个 issus 希望类似 nginx 的指令, api 确实看起来像给机场打工

sudo systemctl restart xray

**Comment by DarkCWK** [comment]
> > > 改完配置重启xray生效，在个人自建中习惯了的
> > 
> > 
> > 嘛...只是每次都要找到来 kill 觉得挺麻烦的, 或许我应该开一个 issus 希望类似 nginx 的指令, api 确实看起来像给机场打工
> 
> sudo systemctl restart xray

Windows 用户震怒 (不是

**Comment by yuhan6665** [comment]
API （有机场写的话）可以加
热重载我觉得没必要
