### ISSUE TITLE
最近一些观察，目前在自己VPS搭建了两个协议分别是 vless+vison+tls和vless+vision+reality

### ISSUE THREAD

**Issue by lelegaga** [XTLS/Xray-core#2707]
<img width="388" alt="vless+vision+reality" src="https://github.com/XTLS/Xray-core/assets/92964742/88a0e9f5-6474-429d-8b3f-59e314101917">
<img width="380" alt="vless+vision+tls" src="https://github.com/XTLS/Xray-core/assets/92964742/19d0a3ff-4d1a-4b74-8c9c-8c6c2e80eb4d">
两个协议的配置大概如图所示，这几天发现对于vless+vison+tls协议中国移动的网络连不上而中国电信的网络可以正常连接，对于vless+vision+reality中国移动和中国电信都可以正常连接，对于vless+vison+tls协议中国移动的网络连不上的情况我感觉有些不理解，有没有大佬一起来讨论一下这种是什么情况，（注明前端时间vless+vison+tls协议中国移动的网络可以正常连接），会不会移动升级了对网络流量的监管，因为端口没被封，再加上移动能Ping通VPS的ip，并且能够正常连接vless+vision+reality！

**Comment by chika0801** [comment]
你这实验用的vps商家是？

是否在不同商家vps上测试？

**Comment by lelegaga** [comment]
VPS商家是racknerd，我只是好奇为什么在节点没被封情况下移动用不了而电信能用

**Comment by lelegaga** [comment]
> VPS商家是racknerd，我只是好奇为什么在节点没被封情况下移动用不了而电信能用

VPS商家是racknerd，我只是好奇为什么在节点没被封情况下移动用不了而电信能用

**Comment by chika0801** [comment]
> VPS商家是racknerd，我只是好奇为什么在节点没被封情况下移动用不了而电信能用

是否在不同商家vps上测试？

**Comment by lelegaga** [comment]
> > VPS商家是racknerd，我只是好奇为什么在节点没被封情况下移动用不了而电信能用
> 
> 是否在不同商家vps上测试？

这个倒没有，不过有我一些其它地区（省份）同样是移动也上不了，但他们电信能上

**Comment by chika0801** [comment]
那建议你多买些vps（不同商家的）

**Comment by lelegaga** [comment]
> 那建议你多买些vps（不同商家的）

会不会是移动网络的问题？

**Comment by chika0801** [comment]
我的看法是这方面说不清楚的事太多，不要多问why了，能解决就是

**Comment by yorunning** [comment]
同样rn和vless+vision+reality，三网连接没问题，就是速度很拉（rn的问题），vless+vison+tls这种不知道是什么搭配

**Comment by bill1112004** [comment]
上海移动同样存在此问题，是最近两周才开始vless+vison+tls用移动的宽带和5G都不能访问，但是联通可以。同样的VPS换成Reality的，移动就可以访问了，不知道到底是哪里出了问题

**Comment by bigfoool** [comment]
我也遇到一样的问题，vless+vison+tls广东移动的网络连不上而中国电信的网络可以正常连接。vless+vision+reality移动和电信都可以连上。vps是RN和斯巴达。

**Comment by zhaohongxuan** [comment]
上海移动访问不了eu.org域名，应该是域名被sni阻断了

**Comment by herozzm** [comment]
我也出现了这个问题，旧协议很正常，到reality 就不行了，联通可以，移动疯狂阻断，换什么sni都不行

**Comment by korben1029** [comment]
我也是rn家的，用的vless+vison+tls，试了一下，移动果然上不去，但是我把跳过证书验证改为true，就能正常连接，不知道为什么，我又试了下联通也没问题

**Comment by bill1112004** [comment]
上海移动不知道怎么，前几天vless+vison+tls还行，今天开始又不行，有一个DIMIT的节点，用了Reality就行，换联通的啥都行。什么道理啊？
