### ISSUE TITLE
[功能建议]命令行精简启动 xray

### ISSUE THREAD

**Issue by soffchen** [XTLS/Xray-core#271]
xtls-rprx-direct 目前也支持 fullcone，可以变成通杀协议了，而往往在实际使用中，很多人都直接用的极简的配置文件，比如
```
{
  "log": {
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": 1234,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "uuid",
            "flow": "xtls-rprx-direct",
            "level": 0,
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
          "alpn": [
            "http/1.1"
          ],
          "certificates": [
            {
              "certificateFile": "/path/to/cert.pem",
              "keyFile": "/path/to/key.pem"
            }
          ]
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom"
    }
  ]
}
```
建议可以简化成为命令行启动，在 docker 等场合，就可以直接快速启动而省去处理配置文件了，例如

服务器端：
```./xray server -listen 0.0.0.0:443 -uuid UUID -cert /path/to/cert.pem -key /path/to/key.pem```

客户端:
```./xray client -server 1.2.3.4:443 -socks5 0.0.0.0:1080 -redir 0.0.0.0:1081 -uuid UUID -name example.com -udp```

其它都按照默认配置来，这样到哪儿只需要带一个 bin 就都搞定了，高级使用再用配置文件。

**Comment by rprx** [comment]
可以有但不着急，因为还有更强的东西会出现

**Comment by shenlijun** [comment]
编辑命令行可能比编辑文件还麻烦……

**Comment by SekiBetu** [comment]
意义好像不太大，但是要加入的代码却很多余

**Comment by rprx** [comment]
目前计划协议完全成型后可以直接通过分享链接启动，这样也不需要再搞一套启动参数标准了。

顺便记录一下新的伪装方式：
1. 外表看起来完全是 Chrome、Firefox 的 **0-RTT** TLSv1.3，包括头部、data record、简单模拟错误响应
2. 不要求自己有域名/证书，**可以用别人的域名/证书**，头部信息错误则直接转发到对应的网站
3. 由于伪装成了 TLSv1.3，所以可以 **XTLS**（ReadV、Splice），性能 MAX

**Comment by soffchen** [comment]
支持，提这个的出发点是为了可以快速启动，不需要去编辑一个文本文件。命令行我只需要 -h 获取一下，就能手动填写完，开始工作了，给别人分享也只需要发一条命令过去，而不是发一个文件。分享链接启动基本可以满足了，只要发送这个链接文本即可。期待。

**Comment by deximy** [comment]
> 目前计划协议完全成型后可以直接通过分享链接启动，这样也不需要再搞一套启动参数标准了。
> 
> 顺便记录一下新的伪装方式：
> 
> 1. 外表看起来完全是 Chrome、Firefox 的 **0-RTT** TLSv1.3，包括头部、data record、简单模拟错误响应
> 2. 不要求自己有域名/证书，**可以用别人的域名/证书**，头部信息错误则直接转发到对应的网站
> 3. 由于伪装成了 TLSv1.3，所以可以 **XTLS**（ReadV、Splice），性能 MAX

所以以后streamSettings里的certificates可以不用了吗？
