### ISSUE TITLE
如何启动时默认启动多文件配置？

### ISSUE THREAD

**Issue by Birddle** [XTLS/Xray-core#2713]
我已经重启service了，但是似乎它没有后台以多目录启动，如何更改？
这是我的目录位置和配置：
<img width="440" alt="Screenshot 2023-11-10 at 13 30 34" src="https://github.com/XTLS/Xray-core/assets/86408260/2cebcfc5-7cd6-4c80-a222-4505ed4b3c09">

<img width="791" alt="Screenshot 2023-11-10 at 13 30 49" src="https://github.com/XTLS/Xray-core/assets/86408260/697fecfa-ffaa-4abc-8a53-d2b5c03edbe6">

<img width="939" alt="Screenshot 2023-11-10 at 13 29 48" src="https://github.com/XTLS/Xray-core/assets/86408260/9285ec6b-0d68-4753-8104-902a32aa5a1f">

**Comment by xqzr** [comment]
`systemctl daemon-reload`

**Comment by yuhan6665** [comment]
answered

**Comment by Birddle** [comment]
> `systemctl daemon-reload`
它不工作，似乎xray.service文件中的更改没有生效：

<img width="700" alt="image" src="https://github.com/XTLS/Xray-core/assets/86408260/96803035-3621-4353-ae7a-7c3cbdc71d37">

**Comment by wy580477** [comment]
> > `systemctl daemon-reload`
> > 它不工作，似乎xray.service文件中的更改没有生效：
> 
> <img alt="image" width="700" src="https://user-images.githubusercontent.com/86408260/282212214-96803035-3621-4353-ae7a-7c3cbdc71d37.png">

![image](https://github.com/XTLS/Xray-core/assets/98247050/67d0513b-165b-4335-90bb-2f6de6e8e268)

**Comment by Birddle** [comment]
> > > `systemctl daemon-reload`
> > > 它不工作，似乎xray.service文件中的更改没有生效：
> > 
> > 
> > <img alt="image" width="700" src="https://user-images.githubusercontent.com/86408260/282212214-96803035-3621-4353-ae7a-7c3cbdc71d37.png">
> 
> ![image](https://user-images.githubusercontent.com/98247050/282212437-67d0513b-165b-4335-90bb-2f6de6e8e268.png)

这是什么意思啊大佬，我没有这个conf文件啊

**Comment by Birddle** [comment]
恢复了xray.service中更改的部分，并在10-donot_touch_signle_congf.conf中更改，但是启动不起来了：

<img width="1421" alt="image" src="https://github.com/XTLS/Xray-core/assets/86408260/993c8987-639e-475b-81b1-134d4ce8e995">

**Comment by chise0713** [comment]
你猜猜为什么叫donnot_touch，你看了drop-in的描述了吗，让你在那个文件夹内再创建一个覆盖的conf文件

**Comment by Birddle** [comment]
> 你猜猜为什么叫donnot_touch，你看了drop-in的描述了吗，让你在那个文件夹内再创建一个覆盖的conf文件。 并且你的配置文件大概率有问题，已经成功读取了你给它的arg，但是没能载入

![image](https://github.com/XTLS/Xray-core/assets/86408260/50cb3487-9baf-4e05-abb5-9716820dafb4)

这些配置文件的内容只有Base文件是文档中的模版、
vmess文件内容是 
```
{
"inbounds":[
//...
//...
]
}
```
其他的文件内容都是`{}`
