### ISSUE TITLE
DNS config

### ISSUE THREAD

**Issue by Pro100x3mal** [XTLS/Xray-core#2715]
Hello. I want to use my own DNS resolver in xray. On the vps with Ubuntu, an xray server and the reality protocol (x-ui panel by alireza0) are installed and configured, and it also has the Unbound caching dns resolver installed. Unbound is configured as a system DNS resolver (127.0.0.1 in /etc/resolv.conf), access is allowed from 127.0.0.1/32 and the private network 10.0.0.0/8, port 53 is open to the private subnet 10.0.0.0/8. Wireguard server (10.10.10.0) is also installed on the vps. Wireguard client configurations indicate to use dns = 10.10.10.0. It turns out that all clients (ios, android, win, linux) are protected from DNS leaks, since domain name resolution occurs on the vps using Unbound. Please tell me how I can configure the xray-reality configuration so that all clients (ios, android, win, linux) also use my own Unbound dns resolver? At the same time, it is important that routing works with my configured routing rules on clients! At the moment, tests for dns leaks show that domain name resolution is not happening on the IP of my vps. I tried adding xray to the configuration:

  "dns": {
    "servers": [
      "127.0.0.1"
    ]
  },

but it doesn't work as it should

**Comment by us254** [comment]
```json
{
  "dns": {
    "servers": [
      {
        "address": "127.0.0.1",
        "port": 53
      }
    ]
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "inboundTag": ["dns-in"],
        "outboundTag": "dns-out"
      },
      // your other rules here
    ]
  },
  "inbounds": [
    {
      "port": 53,
      "tag": "dns-in",
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1",
        "port": 53,
        "network": "tcp,udp"
      }
    },
    // your other inbounds here
  ],
  "outbounds": [
    {
      "tag": "dns-out",
      "protocol": "dns",
      "settings": {
        "network": "tcp,udp",
        "address": "127.0.0.1",
        "port": 53
      }
    },
    // your other outbounds here
  ]
}
```

 the "dns" section is set to use your local Unbound DNS resolver (127.0.0.1 on port 53). An inbound with the "dokodemo-door" protocol is set up to listen for DNS requests on port 53, and a corresponding outbound is set up to handle these requests. The routing rules are set to route all DNS requests (tagged with "dns-in") through the "dns-out" outbound.

**Comment by us254** [comment]
To configure Xray to use your Unbound DNS resolver, you need to modify the Xray configuration file appropriately. The current configuration you have shared indicates that Xray is using `1.1.1.1` as the DNS server, as seen in the `"dns"` section of the configuration file. To switch to your Unbound DNS resolver, you should change this to the IP address of your Unbound DNS server.

Here's a step-by-step guide on how to modify your Xray configuration:

1. **Locate the DNS Configuration Section**: In your Xray configuration file, find the section that begins with `"dns": {`.

2. **Change the DNS Server Address**: Replace the current DNS server address (`1.1.1.1`) with the IP address of your Unbound DNS server. If your Unbound server is configured to listen on `127.0.0.1` for DNS queries, your `"dns"` section in the Xray config should look something like this:

   ```json
   "dns": {
       "servers": [
           "127.0.0.1"
       ]
   },
   ```

3. **Routing Configuration**: Make sure your routing rules in Xray do not interfere with the DNS traffic. You might need to adjust the routing rules to ensure DNS requests are correctly handled.

**Comment by us254** [comment]
Wireguard client configurations indicate to use dns = 10.10.10.0.  , The 10.10.10.0 is a network address and cannot be used as a DNS server address. You need to use the specific IP address of your xray/Unbound server within the Wireguard network. Typically, this would be an IP like 10.10.10.1, but you need to confirm the exact IP address assigned to your xray/Unbound server in the Wireguard network.

**Comment by us254** [comment]
Currently, you can remove the Wireguard configuration and use it in a simplified manner just to test if it works. Additionally, there is no need to set the DNS server. When you change the DNS server to your desired one, you don't have to include it in the configuration. Please delete the parts related to DNS and any other unnecessary components from the server configuration.

delete the parts>
```json
{
  "dns": {
    "servers": [
      {
        "address": "127.0.0.1",
        "port": 53
      }
    ]
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "inboundTag": ["dns-in"],
        "outboundTag": "dns-out"
      },
      // your other rules here
    ]
  },
  "inbounds": [
    {
      "port": 53,
      "tag": "dns-in",
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1",
        "port": 53,
        "network": "tcp,udp"
      }
    },
    // your other inbounds here
  ],
  "outbounds": [
    {
      "tag": "dns-out",
      "protocol": "dns",
      "settings": {
        "network": "tcp,udp",
        "address": "127.0.0.1",
        "port": 53
      }
    },
    // your other outbounds here
  ]
}
```

**Comment by us254** [comment]
You can use this configuration on the client side.

```json
{
  "log": {
    "loglevel": "warning"
  },
  "dns": {
    "servers": [
      "1.1.1.1"
    ],
    "queryStrategy": "UseIPv4"
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "dns-in"
        ],
        "outboundTag": "dns-out"
      },
      {
        "type": "field",
        "ip": [
          "1.1.1.1"
        ],
        "outboundTag": "proxy"
      }
    ]
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 10808,
      "protocol": "socks",
      "settings": {
        "udp": true
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls",
          "quic"
        ],
        "routeOnly": false
      }
    },
    {
      "listen": "127.0.0.1",
      "port": 10853,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "1.1.1.1",
        "port": 53,
        "network": "udp"
      },
      "tag": "dns-in"
    }
  ],
  "outbounds": [
    {
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "xxxx",
            "port": 443,
            "users": [
              {
                "id": "xxx",
                "encryption": "none",
                "flow": "xtls-rprx-vision"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "fingerprint": "chrome",
          "serverName": "xxx",
          "publicKey": "xxx",
          "shortId": "xx"
        },
        "mux": {
          "enabled": true,
          "concurrency": -1,
          "xudpConcurrency": 16,
          "xudpProxyUDP443": "reject"
        },
        "tag": "proxy"
      }
    },
    {
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIPv4"
      },
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "tag": "block"
    },
    {
      "protocol": "dns",
      "settings": {
        "nonIPQuery": "drop"
      },
      "proxySettings": {
        "tag": "proxy"
      },
      "tag": "dns-out"
    }
  ]
}
```
