### ISSUE TITLE
xray调用caddy自动申请的证书文件，提示权限错误

### ISSUE THREAD

**Issue by zsbstephen** [XTLS/Xray-core#273]
由于namesilo似乎无法通过dnsapi方式添加CNAME记录导致acme.sh获取证书失败，因此参照这个issue，保留caddy并通过caddy集成的自动获取/更新获取证书功能来获取证书，让xray直接调用caddy申请下来的证书文件。
[https://github.com/XTLS/Xray-core/issues/164#issuecomment-765053385](url)

caddy申请下来的证书绝对路径在/var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/下面，已给nobody权限：

`chown -R nobody:nogroup /var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/myserver.domain/
chown -R nobody:nogroup /var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/myserver.domain/myserver.domain.crt
chown -R nobody:nogroup /var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/myserver.domain/myserver.domain.key`

xray config配置文件如下：
`{
	"log": {
		"loglevel": "warning",
		"access": "/var/log/xray/access.log",
		"error": "/var/log/xray/error.log"
	},

	"inbounds": [ {
		"port": 443,
		"protocol": "vless",
		"settings": {
			"clients": [ {
				"id": "UUID",
				"level": 0,
				"email": "box@myemail"
			}
			],
			"decryption": "none",
			"fallbacks": [ {
				"dest": 80
			}
			]
		}		,
		"streamSettings": {
			"network": "tcp",
			"security": "tls",
			"tlsSettings": {
				"alpn": [
				"http/1.1"
				],
				"certificates": [ {
					"certificateFile": "/var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/myserver.domain/myserver.domain.crt",
					"keyFile": "/var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/myserver.domain/myserver.domain.key"
				}
				]
			}
		}
	}
	],

	"outbounds": [ {
		"protocol": "freedom"
	}	, {
		"protocol": "blackhole",
		"settings": {},
		"tag": "block"
	}
	],

	"routing": {
		"domainStrategy": "AsIs",
		"rules": [ {
			"type": "field",
			"ip": ["geoip:private"],
			"outboundTag": "blocked"
		}		, {
			"type": "field",
			"outboundTag": "block",
			"protocol": ["bittorrent"]
		}
		]
	}
}
`

然后xray提示下面的错误
`Feb 18 10:13:14 systemd[1]: Started Xray Service.
Feb 18 10:13:14 xray[3622]: Xray 1.3.0 (Xray, Penetrates Everything.) Custom (go1.15.8 linux/amd64)
Feb 18 10:13:14 xray[3622]: A unified platform for anti-censorship.
Feb 18 10:13:14 xray[3622]: 2021/02/18 10:13:14 [Info] infra/conf/serial: Reading config: /usr/local/etc/xray/config.json
Feb 18 10:13:14 xray[3622]: Failed to start: main: failed to load config files: [/usr/local/etc/xray/config.json] > infra/conf: Failed to build TLS config. > infra/conf: failed to parse certificate > open /var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/myserver.domain/myserver.domain.crt: permission denied > exit status 255
Feb 18 10:13:14 systemd[1]: xray.service: Main process exited, code=exited, status=23/n/a
Feb 18 10:13:14 systemd[1]: xray.service: Failed with result 'exit-code'.
`

**Comment by twzchi** [comment]
**1.查看证书文件权限
ls -ln  /var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/
2.crt, key文件需要以下权限即可 ：
-rw-r--r-- 
3 service xray restart
试试？？**

**Comment by rprx** [comment]
> https://t.me/projectXray/272543
> 话说 nobody 是 nogroup 吗

> 不一定
> 也有的发行版是 nobody:nobody

> nobody好像就是nobody
> 不一定是nogroup的样子

**Comment by jiuqi9997** [comment]
```
grep nogroup /etc/group
```
有nogroup组就设权限为`nobody:nogroup`，没有就设`nobody:nobody`

**Comment by zsbstephen** [comment]
> **1.查看证书文件权限 ls -ln /var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/ 2.crt, key文件需要以下权限即可 ： -rw-r--r-- 3 service xray restart 试试？？**
root@:~# ls -ln /var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/
total 8
drwx------ 2 65534 65534 4096 Jan 31 15:21 myserver.domain
drwx------ 2    33    33 4096 Feb 16 23:39 www.myserver.domain
root@:~# chown 0644 /var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/myserver.domain/myserver.domain.crt
root@:~# chown 0644 /var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/myserver.domain/myserver.domain.key

然后重启xray，还是一样的错误，不知道是不是我操作不对。

> > https://t.me/projectXray/272543
> > 话说 nobody 是 nogroup 吗
> 
> > 不一定
> > 也有的发行版是 nobody:nobody
> 
> > nobody好像就是nobody
> > 不一定是nogroup的样子
我这台VPS装的是debian10，nobody在nogroup组里面
root@:~# id nobody
uid=65534(nobody) gid=65534(nogroup) groups=65534(nogroup),33(www-data)

**Comment by twzchi** [comment]
1.。检测命令
sudo  journalctl --boot -u xray.service

**Comment by zsbstephen** [comment]
> 1.。检测命令
> sudo journalctl --boot -u xray.service

`Feb 18 17:49:16 systemd[1]: Started Xray Service.
Feb 18 17:49:16 xray[6728]: Xray 1.3.0 (Xray, Penetrates Everything.) Custom (go1.15.8 linux/amd64)
Feb 18 17:49:16 xray[6728]: A unified platform for anti-censorship.
Feb 18 17:49:16 xray[6728]: 2021/02/18 17:49:16 [Info] infra/conf/serial: Reading config: /usr/local/etc/xray/config.json
Feb 18 17:49:16 xray[6728]: Failed to start: main: failed to load config files: [/usr/local/etc/xray/config.json] > infra/conf: Failed to build TLS config. > infra/conf: failed to parse certificate > open /var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/myserver.domain/myserver.domain.crt: permission denied
Feb 18 17:49:16 systemd[1]: xray.service: Main process exited, code=exited, status=23/n/a
Feb 18 17:49:16 systemd[1]: xray.service: Failed with result 'exit-code'.
`

全都是一样的错误，不知道问题究竟出在哪。

**Comment by twzchi** [comment]
1；试试使用root权限运行？
2：证书使用fullchainpath安装？

**Comment by zsbstephen** [comment]
> 1；试试使用root权限运行？
> 2：证书使用fullchainpath安装？

感谢回复帮助。试了下将xray.service的user从nobody改成root，然后systemctl daemon-reload再systemctl restart xray，还是提示上面的错误。直接用root执行/usr/local/bin/xray run -config /usr/local/etc/xray/config.json ，也还是提示上面的错误，郁闷……

**Comment by jiuqi9997** [comment]
@zsbstephen 用root执行还能报permission denied，就离谱。

**Comment by zsbstephen** [comment]
@jiuqi9997
> @zsbstephen 用root执行还能报permission denied，就离谱。

我都懵了，不知道问题出在哪…… T_T

**Comment by dongjuanyong** [comment]
把caddy kill了试试，话说我当初这个也没折腾成功，现在是用cron每天拷出来一份用的

**Comment by rprx** [comment]
@zsbstephen 出现这种玄学问题，根据我的经验，selinux 你值得拥有（

**Comment by rprx** [comment]
@zsbstephen 不过刚听说 debian 没有 selinux，可能不是它的锅

**Comment by SekiBetu** [comment]
@rprx 纠正一下，是默认不安装SELinux

**Comment by mixool** [comment]
尝试用caddy自动申请证书给xray使用，只开放80和443端口，折腾无果，转投acmesh真香！
你可以尝试直接执行看看是否还报错：
`/usr/local/bin/xray run -config /usr/local/etc/xray/config.json`

**Comment by zsbstephen** [comment]
> 把caddy kill了试试，话说我当初这个也没折腾成功，现在是用cron每天拷出来一份用的

试过了，还是一样。

**Comment by zsbstephen** [comment]
> @zsbstephen 不过刚听说 debian 没有 selinux，可能不是它的锅

没有装SELinux，明天直接整个系统铲掉重装再试试。

**Comment by SekiBetu** [comment]
@zsbstephen 没必要，没权限就给权限，不行就chmod 777

**Comment by zsbstephen** [comment]
> 尝试用caddy自动申请证书给xray使用，只开放80和443端口，折腾无果，转投acmesh真香！

域名是从namesilo买的，不知道是不是namesilo的api有限制，acme.sh没办法添加CNAME记录鉴权，导致用dnsapi方式申请证书失败，因此只能暂时出此下策用caddy来申请证书了。

**Comment by zsbstephen** [comment]
@SekiBetu
> @zsbstephen 没必要，没权限就给权限，不行就chmod 777

试过了chmod 777了，一样是permission denied错误，就离谱……

**Comment by mixool** [comment]
> > 尝试用caddy自动申请证书给xray使用，只开放80和443端口，折腾无果，转投acmesh真香！
> 
> 域名是从namesilo买的，不知道是不是namesilo的api有限制，acme.sh没办法添加CNAME记录鉴权，导致用dnsapi方式申请证书失败，因此只能暂时出此下策用caddy来申请证书了。为了这个问题我在acme.sh的issue下面开了一个帖子。
> [https://github.com/acmesh-official/acme.sh/issues/3411](url)

你是直接A记录的话，为啥还要用api呢，standalone模式蛮好的啊
可以试一下这个脚本： https://github.com/mixool/across/tree/master/xray

**Comment by zsbstephen** [comment]
@mixool
> > > 尝试用caddy自动申请证书给xray使用，只开放80和443端口，折腾无果，转投acmesh真香！
> > 
> > 
> > 域名是从namesilo买的，不知道是不是namesilo的api有限制，acme.sh没办法添加CNAME记录鉴权，导致用dnsapi方式申请证书失败，因此只能暂时出此下策用caddy来申请证书了。为了这个问题我在acme.sh的issue下面开了一个帖子。
> > [https://github.com/acmesh-official/acme.sh/issues/3411](url)
> 
> 你是直接A记录的话，为啥还要用api呢，standalone模式蛮好的啊
> 可以试一下这个脚本： https://github.com/mixool/across/tree/master/xray

主要是方便，而standalone模式的话acme.sh官方脚本不会自动更新，要关闭caddy或者nginx或者apache来腾出80端口，也不能获取泛证书。另外我也只是个半途出家的初学者，所以手头有什么简单易用就用哪些了，这也是用caddy的主要原因。

**Comment by mixool** [comment]
` ~/.acme.sh/acme.sh --issue -d $domain --standalone --keylength ec-256 --pre-hook "systemctl stop caddy xray" --post-hook "~/.acme.sh/acme.sh --installcert -d $domain --ecc --fullchain-file /usr/local/etc/xray/xray.crt --key-file /usr/local/etc/xray/xray.key --reloadcmd \"systemctl restart caddy xray\""`

基本上等于自动获取和更新了

**Comment by Acytoo** [comment]
**我昨天也遇到这个问题，其实以前用python开发别的东西的时候，也遇到过caddy tls证书的权限问题。这里给出我的分析以及处理方法。**

caddy 申请的证书权限似乎只能属于 caddy 进程申请 tls 时的用户，自行修改证书文件权限似乎无效（至少我没有成功过）。而 caddy2 默认的用户是 caddy。两种解决思路：1，root 用户运行 caddy，root 用户运行xray；2，caddy用户 运行 xray。

建议使用第二种，把 xray.service 中的 User 值从 nobody 改为 caddy，这样就可以解决权限问题。

详细情况可以看我的日记 [试用xray，对比v2ray # 配置服务器端 xray](https://acytoo.com/ladder/v2-x-ray/#%E9%85%8D%E7%BD%AE%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%AB%AF-xray)

**Comment by rprx** [comment]
@Acytoo 为啥你的日记看起来这么。。。看来的确需要在 README 好好列举一下 Xray 强大在哪里

BTW，v2fly 的文档是我认真调了好久的，Xray 当前的文档与我无关

**Comment by Acytoo** [comment]
> @Acytoo 为啥你的日记看起来这么。。。看来的确需要在 README 好好列举一下 Xray 强大在哪里
> 
> BTW，v2fly 的文档是我认真调了好久的，Xray 当前的文档与我无关

大佬还不休息啊。也许xray很厉害吧，但在对于我这样能用就行的普通人来说，额，目前还没有体会到。

**Comment by zsbstephen** [comment]
> **我昨天也遇到这个问题，其实以前用python开发别的东西的时候，也遇到过caddy tls证书的权限问题。这里给出我的分析以及处理方法。**
> 
> caddy 申请的证书权限似乎只能属于 caddy 进程申请 tls 时的用户，自行修改证书文件权限似乎无效（至少我没有成功过）。而 caddy2 默认的用户是 caddy。两种解决思路：1，root 用户运行 caddy，root 用户运行xray；2，caddy用户 运行 xray。
> 
> 建议使用第二种，把 xray.service 中的 User 值从 nobody 改为 caddy，这样就可以解决权限问题。
> 
> 详细情况可以看我的日记 [试用xray，对比v2ray # 配置服务器端 xray](https://acytoo.com/ladder/v2-x-ray/#%E9%85%8D%E7%BD%AE%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%AB%AF-xray)

哇，感谢大佬提供的思路，有空立即改下配置试试看。
