### ISSUE TITLE
No I personally Tested Many IPs From Many datacanters .. it will stop working  

### ISSUE THREAD

**Issue by DrVictor77** [XTLS/Xray-core#2730]
> 
> "EVEN IF YOU USE BRAND NEW CLEAN IP, IT GETS BANNED AFTER 15 MIN OF USING REALITY"

'Brand new' ip address does not mean anything! Maybe last owner had wireguard or simple shadowsocks vpn on that IP!

Clean IP is an IP address that is not graylisted since last year!!! Do you own an IP address for a year and only used updated and modern protocols with reality+vision flow ?
I doubt that.

_Originally posted by @hawshemi in https://github.com/XTLS/Xray-core/issues/2451#issuecomment-1809014222_

**Comment by hawshemi** [comment]
**This is not a personal matter.**
If all IP addresses stopped working after 24 hours for MCCI, these GitHub issues and /net4people/bbs would have exploded by now!

**That is not the case.**

look at this post from a random guy:
[https://t.me/irgfw/9](https://t.me/irgfw/9)

**Comment by DrVictor77** [comment]
> **This is not a personal matter.** If all IP addresses stopped working after 24 hours for MCCI, these GitHub issues and /net4people/bbs would have exploded by now!
> 
> **That is not the case.**
> 
> look at this post from a random guy: https://t.me/irgfw/9

bro if u look at Telegram and twitter all around everyone is telling about this new stuff happening on MCI ... i know there are some old Reality IP and configs are working i actually have 2 of them ... butthe new ones get flagged so easy ..

**Comment by hawshemi** [comment]
@DrVictor77 


>  butthe new ones get flagged so easy ..

`new ones` means nothing new for Iran GFW. maybe that IP address is logged and listed as graylisted from a year ago! maybe 6 months ago one else had that IP address with plain old shadowsocks !!!
GFW doesn't care about the time you got the IP address...

**Comment by DrVictor77** [comment]
> @DrVictor77
> 
> > butthe new ones get flagged so easy ..
> 
> `new ones` means nothing new for Iran GFW. maybe that IP address is logged and listed as graylisted from a year ago! maybe 6 months ago one else had that IP address with plain old shadowsocks !!! GFW doesn't care about the time you got the IP address...

I Tested Vultr Azure Amazon these type of IPs Are so Rare Among VPN users i dont think it matters Im telling you i have so many flagged IPs but with Some rare SNI's It Will start To Work Again

**Comment by Fangliding** [comment]
Not a core issue
