### ISSUE TITLE
請問有遇到在編譯 Xary-core 時，打包出來的 Xraykit.xcframework 和 Mango 專案裡的 Xraykit.xcframework 不同嗎？

### ISSUE THREAD

**Issue by ghostwolf90** [XTLS/Xray-core#2732]
請問有遇到在編譯 Xary-core 時，打包出來的 Xraykit.xcframework 和 Mango 專案裡的 Xraykit.xcframework 不同嗎？

因為我用了這個專案 [AndroidLibXrayLite](https://github.com/2dust/AndroidLibXrayLite)
可以引用 xray-core 最新版本 1.8.5 的 xraykit.xcframework
但是裡面的方法和 Mango 專案提供的 Xraykit 完全不一樣
請問有大大知道 Mango裡的 Xraykit 是如何打包的嗎？

**Comment by onlypl** [comment]
Mango的库已经404了。。我用libXray也是完全不一样

**Comment by ghostwolf90** [comment]
你好，請問方便跟你詢問，該如何使用libXray打包出來的 .xcframework嗎？
我有打包 libXray和Xray-core的專案，兩個打包出來的.xcframework是一樣的.
方便加TG跟你請教嗎？感謝
我的TG: https://t.me/bit_lai

**Comment by ghostwolf90** [comment]
目前用libxray進行開發
