### ISSUE TITLE
Vless+xtls-rprx-vision+reality 可以支持tls1.3吗？

### ISSUE THREAD

**Issue by cxxp111** [XTLS/Xray-core#2742]
{
      "listen": "0.0.0.0",
      "port": "47200-47210",
      "protocol": "vless",
      "tag": "vless_reality_vision_in",
      "settings": {
        "clients": [
          {
            "id": "535746f8-7682-44c0-ad74-64d91cde06d5",
            "email": "xtls-rprx-vision",
            "flow": "xtls-rprx-vision"
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "dest": "icloud.com:443",
            "xver": 0
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "show": true,
          "dest": "",
          "xver": 0,
          "serverNames": [
            
          ],
          "privateKey": "YAcEHt1nAKjz1DzgIbFhnlafN7qZYV2eZIzAbJbZSEw",
          "publicKey": "Km5EPjd9ALebmRg1eA4No-CU8XndqLK1fUZGcxg9aSE",
          "maxTimeDiff": 70000,
          "shortIds": [
            "",
            "6ba85179e30d4fc2"
          ]
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    }

我这样配置的server inbound，但是看日志输出是tls1.2，可以弄成1.3吗

**Comment by chise0713** [comment]
https://xtls.github.io/config/transport.html#tlsobject

**Comment by yuhan6665** [comment]
应该是你看错了 不应该协商出 1.2

**Comment by cxxp111** [comment]
![image](https://github.com/XTLS/Xray-core/assets/36062594/c979da01-1e1e-48b9-98f4-49063f502617)
@yuhan6665 大佬看看这个呢？

**Comment by chika0801** [comment]
猜日志中意思是你访问的网站是tls1.2的，vision流控工作时是用的（什么）

你提问可以支持1.3 dest目标网站的tls要是1.3。建议你把问题讲清楚。

**Comment by cxxp111** [comment]
哦，意思是 dest不支持1.3，所以客户端没有用1.3连服务端，是吧 @chika0801

**Comment by chise0713** [comment]
> 哦，意思是 dest不支持1.3，所以客户端没有用1.3连服务端，是吧 @chika0801 

错，是访问网站时套在vision内部的tls版本是1.2，而不是vision是1.2，reality只支持tls1.3的dest
