### ISSUE TITLE
提示配置错误，但是没有找到报错日志，窗口又不能拉伸

### ISSUE THREAD

**Issue by LXFYJQ** [XTLS/Xray-core#2744]
![image](https://github.com/XTLS/Xray-core/assets/58595220/b17b22ec-881a-461e-9b85-f96e3b9352d2)

**Comment by ZqinKing** [comment]
好歹把配置贴出来啊。。。

**Comment by LXFYJQ** [comment]
![2023-11-23_12-17](https://github.com/XTLS/Xray-core/assets/58595220/905a3068-1e04-4360-a5b2-dcf1791a31d9)
![2023-11-23_12-18](https://github.com/XTLS/Xray-core/assets/58595220/76c82c15-3851-4085-a5f6-2a2f28c88564)
![2023-11-23_12-18_1](https://github.com/XTLS/Xray-core/assets/58595220/9c75438e-7832-4bd6-baef-cae0f291ee2c)
![2023-11-23_12-19](https://github.com/XTLS/Xray-core/assets/58595220/d738170e-9218-4117-bcf8-972eabb2d1b2)
![2023-11-23_12-19_1](https://github.com/XTLS/Xray-core/assets/58595220/411c15a2-7414-45d1-85c5-ec4b353bdc64)
大佬是这些吗
