### ISSUE TITLE
VLESS-TCP-XTLS-WHATEVER alpn若允许h2 web访问出错

### ISSUE THREAD

**Issue by vangork** [XTLS/Xray-core#275]
若将
https://github.com/XTLS/Xray-examples/blob/main/VLESS-TCP-XTLS-WHATEVER/config_server.json
第46行改成"h2","http/1.1"，此时用chrome访问网站，网页显示错误：ERR_HTTP2_PROTOCOL_ERROR，xray日志里报错如下：
2021/02/18 03:51:01 xxx.xxx.xxx.xxx:xxxx rejected  proxy/trojan: not trojan protocol

似乎h2下从vless fallback到trojan后无法再fallback，而http/1.1下则无此问题，望确认这是一个limitation还是一个bug。

**Comment by AkinoKaede** [comment]
Trojan 回落的 dest 有提供 H2C 吗

**Comment by vangork** [comment]
> Trojan 回落的 dest 有提供 H2C 吗?

按照如下配置的xray server fallback以及nginx http2，依旧同样的错误。
https://github.com/XTLS/Xray-examples/tree/main/VLESS-TCP-TLS

**Comment by AkinoKaede** [comment]
> > Trojan 回落的 dest 有提供 H2C 吗?
> 
> 按照如下配置的xray server fallback以及nginx http2，依旧同样的错误。
> https://github.com/XTLS/Xray-examples/tree/main/VLESS-TCP-TLS

请提供完整配置

**Comment by AkinoKaede** [comment]
仔细想了下，回落到 Trojan 后是没有 ALPN 的，所以这应该是一个局限性

**Comment by vangork** [comment]
```
"inbounds": [
  {
	"port": 443,
	"protocol": "vless",
	"settings": {
	  "clients": [
		{
		  "id": "someid",
		  "flow": "xtls-rprx-direct",
		  "level": 1,
		  "email": "xxx@email.com"
		}
	  ],
	  "decryption": "none",
	  "fallbacks": [
		{
		  "dest": 10000,
		  "xver": 1
		}
	  ]
	},
	"streamSettings": {
	  "network": "tcp",
	  "security": "xtls",
	  "xtlsSettings": {
		"alpn": [
		  "h2",
		  "http/1.1"
		],
		"certificates": [
		  {
			"certificateFile": "/etc/letsencrypt/live/somedomain/fullchain.pem",
			"keyFile": "/etc/letsencrypt/live/somedomain/privkey.pem"
		  }
		]
	  }
	},
	"tag": "vless"
  },
  {
	"port": 10000,
	"listen":"127.0.0.1",
	"protocol": "trojan",
	"settings": {
	  "clients": [
		{
		  "password": "somepassword",
		  "level": 1,
		  "email": "xxx@email.com"
		}
	  ],
	  "fallbacks": [
		{
		  "dest": "8080",
		  "xver": 1
		},
		{
		  "alpn": "h2",
		  "dest": 8081,
		  "xver": 1
		}
	  ]
	},
	"streamSettings": {
	  "network": "tcp",
	  "security": "none",
	  "tcpSettings": {
		"acceptProxyProtocol": true
	  }
	},
	"tag": "trojan"
  }
]
```

**Comment by AkinoKaede** [comment]
@vangork <https://github.com/XTLS/Xray-core/issues/275#issuecomment-781037467>

**Comment by vangork** [comment]
> 仔细想了下，回落到 Trojan 之后是没有 ALPN 的，所以这应该是一个局限性。
> 可以尝试使用 Caddy 等 Web Server，将 HTTP/1.1 和 H2C 服务提供在同一端口

> 仔细想了下，回落到 Trojan 之后是没有 ALPN 的，所以这应该是一个局限性。
> 可以尝试使用 Caddy 等 Web Server，将 HTTP/1.1 和 H2C 服务提供在同一端口

即使trojan下fallback在同一端口，web访问也会报错。应该是h2下vless fallback到trojan后trojan不会再次fallback了
rejected proxy/trojan: not trojan protocol

**Comment by vangork** [comment]
@AkinoKaede 此问题并不仅仅是documentation的问题，希望再次确认。

**Comment by AkinoKaede** [comment]
@vangork 试试改成
```
"inbounds": [
  {
	"port": 443,
	"protocol": "vless",
	"settings": {
	  "clients": [
		{
		  "id": "someid",
		  "flow": "xtls-rprx-direct",
		  "level": 1,
		  "email": "xxx@email.com"
		}
	  ],
	  "decryption": "none",
	  "fallbacks": [
		{
		  "dest": 10000,
		  "xver": 1
		}
	  ]
	},
	"streamSettings": {
	  "network": "tcp",
	  "security": "xtls",
	  "xtlsSettings": {
		"alpn": [
		  "h2"
		],
		"certificates": [
		  {
			"certificateFile": "/etc/letsencrypt/live/somedomain/fullchain.pem",
			"keyFile": "/etc/letsencrypt/live/somedomain/privkey.pem"
		  }
		]
	  }
	},
	"tag": "vless"
  },
  {
	"port": 10000,
	"listen":"127.0.0.1",
	"protocol": "trojan",
	"settings": {
	  "clients": [
		{
		  "password": "somepassword",
		  "level": 1,
		  "email": "xxx@email.com"
		}
	  ],
	  "fallbacks": [
		{
		  "dest": "8081",
		  "xver": 1
		}
	  ]
	},
	"streamSettings": {
	  "network": "tcp",
	  "security": "none",
	  "tcpSettings": {
		"acceptProxyProtocol": true
	  }
	},
	"tag": "trojan"
  }
]
```

**Comment by vangork** [comment]
@AkinoKaede 此时web可以正常访问，这是什么原因啊，http1.1和h2协商那边出问题了？

**Comment by AkinoKaede** [comment]
> @AkinoKaede 此时web可以正常访问，这是什么原因啊，http1.1和h2协商那边出问题了？

回落是通过 ALPN 判断的。回落到 Trojan 后，因为 TLS 已经被解密，所以没有 ALPN，此时流量会全部回落到没有配置 "alpn" 的回落目标中。

**Comment by vangork** [comment]
ok，这种情况下确实和nginx无法配合了。似乎也没什么好办法。谢谢。

**Comment by rprx** [comment]
Nginx 的话，推荐默认直接回落到 nginx，alpn h2 时回落到 trojan 再回落到 nginx（因为 trojan 的是 h2）

**Comment by rprx** [comment]
Nginx 的话，推荐 VLESS 默认直接回落到 nginx http/1.1，alpn h2 时先回落到 trojan 再默认直接回落到 nginx h2c

**因为服务端配置 alpn 为 h2 在前，用 VLESS、Trojan 时会协商出 h2，所以 trojan 只放 alpn h2 后面即可**

**Comment by rprx** [comment]
Nginx 的话，推荐 VLESS 默认直接回落到 Nginx http/1.1，alpn h2 时先回落到 Trojan 再默认直接回落到 Nginx h2c

**因为服务端配置 alpn 为 h2 在前，用 VLESS、Trojan 时会协商出 h2，所以 Trojan 只放 VLESS alpn h2 后面即可**

**Comment by vangork** [comment]
@rprx 感谢回复，问题已经全部搞清楚了。
