### ISSUE TITLE
Reality Vision 无法使用IMAP Gmail收发邮件。

### ISSUE THREAD

**Issue by Daryl-Do** [XTLS/Xray-core#2752]
Mac自带的Mail App， 用了vless-reality-vision节点后，无法连接到Gmail的邮箱。会出现下图两种报错

用的客户端是shadowrocket。

做了以下测试：
1. 更改reality的目标网站。改了好几个，均不行。
2. outlook，iCloud等不需要翻墙的邮箱不受影响。
3. 全局模式跑了也不行。
4. 同一主机的vmess节点没问题。

不知道是否是reality的bug？
<img width="260" alt="image" src="https://github.com/XTLS/Xray-core/assets/31330846/0551aa22-35ca-4ac4-8e5a-c839c35ebf12">
<img width="260" alt="image" src="https://github.com/XTLS/Xray-core/assets/31330846/f364e04a-6dba-4e07-bb78-ef58aabb6ecb">

**Comment by ynhzzu** [comment]
大概率是apple mail自身的问题，之前遇到过，后来换成Outlook了。记得之前查资料好像apple mail与google的认证机制有什么冲突，时间长忘了。

**Comment by Daryl-Do** [comment]
应该是shadowrocket+reality的问题。更新后问题解决了。
