### ISSUE TITLE
tproxy uses 100% of cpu and 500mb of ram

### ISSUE THREAD

**Issue by its0ka** [XTLS/Xray-core#2755]
my config https://pastebin.com/NUJMQk6r

then i run 

ip route add local default dev lo table 100
ip rule add fwmark 1 table 100

iptables -t mangle -N XRAY
iptables -t mangle -A XRAY -p tcp -j TPROXY --on-port 12345 --tproxy-mark 1
iptables -t mangle -A PREROUTING -p tcp --dport 443 -s 10.50.1.1 -j XRAY

and after 10 hours of use i see that xray uses 100% of cpu and 500mb of ram

"ss -nH state established dport = 12345" returns up to 3000 lines each time (it changes each time i run the command) like this one
"tcp  0   0  vps_ip:38470  vps_ip:12345"
all lines are the same except sport

and after deleting the rules from above it doesn't change at all, need to restart xray for it to calm down
what can be the issue?

**Comment by its0ka** [comment]
now it actually happened after only 10 minutes of usage

**Comment by its0ka** [comment]
i just tried "nc vps_ip 12345" from another vps and xray on my vps started what i described above

**Comment by hkbase** [comment]
你品尝tproxy的姿势不对，请参照官方文档
https://xtls.github.io/document/level-2/tproxy.html

**Comment by its0ka** [comment]
@hkbase i don't see any difference between my config and config from that document. every guide with tproxy makes it listen on 0.0.0.0 and i don't understand why

**Comment by harvey-git** [comment]
The freedom configuration of your xray export lacks the setting to mark data packets, and your iptables also lacks the conditions for bypassing the xray export data packet, which causes an infinite loop when you use the tproxy proxy.
The normal approach is to mark the exported freedom with a different mark (such as 255).
like this：
`{
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP"
      },
      "streamSettings": {
        "sockopt": {
          "mark": 255
        }
      }
    },`

**Comment by its0ka** [comment]
@harvey-git ok, it will mark the packets and then what? will xray discard them now? it didn't change anything for me.
xray starts to use 100% of cpu because of the loop (someone connects to xray_ip:port without tproxy mark, then xray forwards the request to the same xray_ip:port and it goes indefinitely, log file looks like this and it just doesn't stop https://pastebin.com/jcRNmWmr)
