### ISSUE TITLE
请求添加geoip反向匹配功能

### ISSUE THREAD

**Issue by sbcarp** [XTLS/Xray-core#2759]
因为业务要求，需要优先匹配非中国ip，然后再匹配中国ip

所以希望可以支持 `geoip:!cn`

目前的方案是手动对中国ip进行取反
```
224.0.0.0/3
223.224.0.0/12
223.255.128.0/18
223.255.192.0/19
223.255.240.0/21
223.255.248.0/22
...
```
大概有9000多行，这种方法比较低效，而且在中国ip更新后还要再手动调整

**Comment by sbcarp** [comment]
不知道这个功能是否合理，如果太麻烦的话就算了，谢谢

**Comment by xqzr** [comment]
> 所以希望可以支持 `geoip:!cn`

目前就支持

**Comment by sbcarp** [comment]
那就奇怪了，不知道为什么它不工作，我再测试一下😂

**Comment by JobAbout** [comment]
默认用的好像就是这个 [v2ray-rules-dat](https://github.com/Loyalsoldier/v2ray-rules-dat)

**Comment by maoxikun** [comment]
> > 所以希望可以支持 `geoip:!cn`
> 
> 目前就支持

"geosite:cn@!cn"和"geoip:!cn"好像是相似的（一个是domain，一个是ip），是否能支持一下"geosite:cn@!cn"简化成"geosite:!cn"

**Comment by chika0801** [comment]
> > > 所以希望可以支持 `geoip:!cn`
> > 
> > 
> > 目前就支持
> 
> "geosite:cn@!cn"和"geoip:!cn"好像是相似的（一个是domain，一个是ip），是否能支持一下"geosite:cn@!cn"简化成"geosite:!cn"

geosite cn 中的 !cn 指 你打开它目录看下就知道了，指结尾带 !cn 的域名

geoip:cn geoip数据库中cn分类的ip，结果在非cn分类，取反。是xray代码里实现的功能。

和geosite 中的人为标记，不是一个事。

ps 你真的什么需要geosite cn 域名值取反？可能要自己写代码实现

**Comment by maoxikun** [comment]
> > > > 所以希望可以支持 `geoip:!cn`
> > > 
> > > 
> > > 目前就支持
> > 
> > 
> > "geosite:cn@!cn"和"geoip:!cn"好像是相似的（一个是domain，一个是ip），是否能支持一下"geosite:cn@!cn"简化成"geosite:!cn"
> 
> geosite cn 中的 !cn 指 你打开它目录看下就知道了，指结尾带 !cn 的域名
> 
> geoip:cn geoip数据库中cn分类的ip，结果在非cn分类，取反。是xray代码里实现的功能。
> 
> 和geosite 中的人为标记，不是一个事。
> 
> ps 你真的什么需要geosite cn 域名值取反？可能要自己写代码实现

理解了，那[这个](https://github.com/XTLS/Xray-docs-next/pull/447)描述应该是geoip而不是geoip:cn吧
<img width="930" alt="image" src="https://github.com/XTLS/Xray-core/assets/106460972/da98140c-72e4-462d-bd8b-d5dc692f90a8">

**Comment by chika0801** [comment]
那段绿色文字 以 geoip:!cn 使用了为例，逗号后面解释了结果。

**Comment by maoxikun** [comment]
> 那段绿色文字 以 geoip:!cn 使用了为例，逗号后面解释了结果。

感觉改成“ 非geoip:cn中的的结果 ”好理解一点

**Comment by chika0801** [comment]
改了
