### ISSUE TITLE
Potential Issue between Xray 1.8.4 and 1.8.5/1.8.6 leading to GFW Detection

### ISSUE THREAD

**Issue by houmie** [XTLS/Xray-core#2769]
**Background:**

We have been successfully using Xray version 1.8.4 on our Bandwagon server for several months without any issues related to the Great Firewall of China (GFW). However, we encountered a significant problem after upgrading our server from Xray 1.8.4 to 1.8.5, and subsequently to 1.8.6.

**Issue:**

Post-upgrade, our server's IP was detected and subsequently blocked by the GFW, as confirmed by Bandwagon. This issue surfaced immediately following the upgrade, leading us to suspect a potential compatibility or detection issue between the client-side Xray 1.8.4 and server-side versions 1.8.5/1.8.6.

**Observations:**

- The issue coincided with the upgrade from 1.8.4 to 1.8.5/1.8.6.
- The IP blockage was confirmed to be specifically from Mainland China.

**Question/Concern:**

Is there a possibility that the newer versions of Xray (1.8.5 and 1.8.6) are not fully backward compatible with 1.8.4, in a way that makes them more detectable by the GFW? Alternatively, could the timing of our upgrade coincidentally align with an update in GFW’s detection mechanisms?

**Request:**

We would greatly appreciate any insights or confirmations regarding this potential issue. If this is a bug related to backward compatibility or a detection loophole, addressing it would be crucial for users operating under similar circumstances.

Thank you for your attention to this matter.

**Comment by zxbiao** [comment]
Bandwagon的IP段一直都在中国GFW的灰色名单中（在翻墙相关的论坛中一直都这样说），当有敏感事件时基本都是一堆倒。
除了Bandwagon之外，还有就是Oracle的IP段也是。

**Comment by houmie** [comment]
@zxbiao 

Thank you for sharing this insight. It seems I might need to reconsider my subscription with Bandwagon, given its IP range's status regarding the GFW. Could you recommend any other CN2GIA providers that might be a better alternative to Bandwagon? Also, it's useful to know that Oracle isn't a viable option either.

I'm quite surprised that the VLESS-VISION-TCP-REALITY configuration could be detected so readily by the GFW. As a temporary solution, I'm considering changing the IP address at Bandwagon and retrying with Xray Core 1.8.4 for both the client and server.

Do you believe the version mismatch between the server (1.8.4) and client (1.8.6), or vice versa, could have contributed to this detection? Or is it possible that the detection of my server by the GFW was merely coincidental? I'm trying to dissect the situation to identify the root cause.

**Comment by zxbiao** [comment]
> @zxbiao
> 
> Thank you for sharing this insight. It seems I might need to reconsider my subscription with Bandwagon, given its IP range's status regarding the GFW. Could you recommend any other CN2GIA providers that might be a better alternative to Bandwagon? Also, it's useful to know that Oracle isn't a viable option either.
> 
> I'm quite surprised that the VLESS-VISION-TCP-REALITY configuration could be detected so readily by the GFW. As a temporary solution, I'm considering changing the IP address at Bandwagon and retrying with Xray Core 1.8.4 for both the client and server.
> 
> Do you believe the version mismatch between the server (1.8.4) and client (1.8.6), or vice versa, could have contributed to this detection? Or is it possible that the detection of my server by the GFW was merely coincidental? I'm trying to dissect the situation to identify the root cause.

建议服务端和客户端使用同一版本号，还有Reality的DEST的选择会间接影响GFW的关注度（已知使用Microsoft.com/apple.com会导致服务器有一定机率被GFW屏蔽）。
