### ISSUE TITLE
IOS 端Quantumult X ,奇怪问题

### ISSUE THREAD

**Issue by kalagxw** [XTLS/Xray-core#277]
Quantumult X 暂不支持vless，服务端设置fallback回落到vmess+ws+tls。
直接采用落地机IP:端口直连可以建立连接
采用iptables中转后 不能建立连接
===================================================
用xray-core windows客户端尝试无问题。
似乎 【PROXY protocol】问题

**Comment by rprx** [comment]
目测是理解错误导致的配置错误，与 PROXY protocol 无关。如果客户端是一样的配置，不可能只有一个能连。

**Comment by kalagxw** [comment]
客户端（ios Quantumult X） 填中转信息不能连，填落地信息能连，其他配置不变
客户端（windows xray-core-win64 ）填中转 、落地信息均连。
看起来是Quantumult X问题？

**Comment by rprx** [comment]
@kalagxw 中转应当是透明的，不应该只有 Xray-core 能连，我认为你的 QX 填错了信息。
