### ISSUE TITLE
🆘 need help about best settings for multiple game and low ping

### ISSUE THREAD

**Issue by itsDantes** [XTLS/Xray-core#2773]
i need to know what is best config and settings can be made for gameـ i have some questions; 

1. How many users supported on a server with specifications info (RAM 2 and CPU 1) ?

2. What type of settings should be enabled on config? what is best config for getting best lowerping on games ? for example, kcp, grpc, ws, h2 or... 

3. how should shrink configs? for example, make 5 config and share them to 50 user or make 1 config is enough  ? 

4. what about configs security in some bullshit countries that they banned VPN... best settings that are always good for reducing ping, also It should be secure to reduce the possibility of filtering on servers.

**Comment by iopq** [comment]
1. Depends on the amount of data, I could support a lot for low bandwidth games, but then I accidentally DOS'd myself by syncing to the bitcoin network from one computer (should have turned off the proxy)

2. The fastest experience I got was on VLESS + vision, but it gets blocked often. Second best is on VLESS + REALITY + vision, the ping is always slightly higher, but it stays up unblocked

**Comment by Fangliding** [comment]
not a core issue
