### ISSUE TITLE
How to Completely disable any kind of LOG in console output

### ISSUE THREAD

**Issue by zerodwide** [XTLS/Xray-core#2774]
I just need to see ERROR logs on console and write it in log file.
i know how to enable log level to ERROR and store it in log file!

BUT, why all access logs like this is printed on console like this line:?

`Nov 30 18:37:24 fi1 XrayR[713086]: 2023/11/30 18:37:24 [IP:PORT] accepted ... `

Thanks in advance

**Comment by yuhan6665** [comment]
answered
