### ISSUE TITLE
balancer  不工作，从第一个 outbounds 出去了， 

### ISSUE THREAD

**Issue by Uhtred009** [XTLS/Xray-core#2777]
{
  "log": {
    "access": "",
    "error": "./error.log",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "socks",
      "port": 7889,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ],
        "routeOnly": false
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "allowTransparent": false
      }
    },
    {
      "tag": "http",
      "port": 7890,
      "listen": "127.0.0.1",
      "protocol": "http",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ],
        "routeOnly": false
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "allowTransparent": false
      }
    }
  ],
  "outbounds": [
    
    {
      "tag": "tw11",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "11.xxx.com",
            "port": 443,
            "users": [
              {
                "id": "xxx",
                "alterId": 0,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false,
          "serverName": "11.xxx.com"
        },
        "wsSettings": {
          "path": "/fb",
          "headers": {
            "Host": "11.xxx.com"
          }
        }
      },
      "mux": {
        "enabled": false,
        "concurrency": -1
      }
    },

    {
      "tag": "test11",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "57.xxx.com",
            "port": 10443,
            "users": [
              {
                "id": "xxx",
                "alterId": 0,
                "email": "t@t.tt",
                "security": "auto",
                "encryption": "none",
                "flow": "xtls-rprx-vision"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false
        }
      },
      "mux": {
        "enabled": false,
        "concurrency": -1
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    }
  ],
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [

     
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "enabled": true
      },
     
      {
        "id": "4994401533470426702",
        "type": "field",
        "outboundTag": "block",
        "domain": [
          "geosite:category-ads-all"
        ],
        "enabled": true
      },
      {
        "id": "5079714562843255463",
        "type": "field",
        "outboundTag": "direct",
        "domain": [
          "geosite:cn"
        ],
        "enabled": true
      },
      {
        "id": "5059010412196119074",
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "geoip:private",
          "geoip:cn"
        ],
        "enabled": true
      },
      {
        "id": "5696708702475119467",
        "type": "field",
        "port": "0-65535",
        "balancerTag": "balancer11",
        "enabled": true
      }
    ],

    "balancers": [{
      "tag": "balancer11",
      "selector": [
        "test11",
        "tw11"
      ],
      "strategy": {
        "type": "leastPing"
      }
     
    }]
  },

  "observatory": {
    "subjectSelector":[
      "balancer11"
    ],
    "probeURL": "https://api.github.com/_private/browser/stats",
    "probeInterval": "1s"
  }
  
}

能够成功启动，但是balancer  不工作，访问直接从第一个 outbounds 出去了， 请问下 是我的配置有问题吗，还是说xray 就没有这个功能？

**Comment by yomnxkcs** [comment]
配置好复杂有点看不懂，下面这个配置是干什么用的？
```json
{
  "routing": {
    "balancers": [
      {
        "strategy": {
          "type": "leastPing"  // 这里没看懂
        }
      }
    ]
  }
}
```
然后这里也没看懂，为什么填balancer的tag而不是outbound的tag?
```json
{
  "observatory": {
    "subjectSelector": [
      "balancer11" // 这里
    ]
  }
}
```

**Comment by Uhtred009** [comment]
> 配置好复杂有点看不懂，下面这个配置是干什么用的？
> 
> ```json
> {
>   "routing": {
>     "balancers": [
>       {
>         "strategy": {
>           "type": "leastPing"  // 这里没看懂
>         }
>       }
>     ]
>   }
> }
> ```
> 
> 然后这里也没看懂，为什么填balancer的tag而不是outbound的tag?
> 
> ```json
> {
>   "observatory": {
>     "subjectSelector": [
>       "balancer11" // 这里
>     ]
>   }
> }
> ```

这个是  负载均衡的一种配置，选取最快速的outbounds 出口

**Comment by Uhtred009** [comment]
> the configuration issue lies in the incorrect use of tags within the JSON configuration. The "balancerTag" in the routing rule and the "subjectSelector" in the "observatory" section should both be set to the tag of the load balancer, not the outbound tag. This mismatch is likely the cause of the balancer not functioning correctly. Correcting these tags to point to the load balancer should resolve the issue.

"balancers": [{
"tag": "balancer11",
"selector": [
"test11",
"tw11"
],
"strategy": {
"type": "leastPing"
}

}]
"balancers": [{
"tag": "balancer11",
"selector": [
"test11",
"tw11"
],
"strategy": {
"type": "leastPing"
}

}] 我都设置的是 负载均衡的出口 balancer11， 应该是没有错吧 ，检查了好几遍

**Comment by us254** [comment]
https://github.com/XTLS/Xray-core/issues/1146

**Comment by Uhtred009** [comment]
@yomnxkcs    确实如此，搞定了，感谢！  longlive   xray-core
