### ISSUE TITLE
VLESS-XTLS-REALITY+acceptProxyProtocol+nginx proxy_protocol on偶发性无法连接

### ISSUE THREAD

**Issue by bbi8** [XTLS/Xray-core#2779]
xray v1.8.4
nginx v1.24.0

nginx stream代理sni分流开启proxy_protocol on;
xray开启tcpSettings中的"acceptProxyProtocol": true
该组合在使用过程中会出现偶发性的无法连接

目前测试出稳定的复现方式：
重启nginx后立即访问 https://www.google.com 或 https://www.youtube.com （其他地址可能也会），确保是nginx重启后的第一个连接。
此时xray有访问日志无异常日志，nginx无异常日志，浏览器处于连接中，最终会超时连接失败。
经过第一个连接后，后续访问会偶发性的无法连接。

设置nginx proxy_protocol off;和xray"acceptProxyProtocol": false之后不会有此问题。

**Comment by chika0801** [comment]
建议发你的nginx配置和xray配置供其他人参考，或可能帮你分析一下

另外你觉得不稳了，就不要用nginx监听443sni分流这种形式就解决了嘛。

**Comment by zxcvos** [comment]
[#2754](https://github.com/XTLS/Xray-core/discussions/2754#discussioncomment-7861006)

**Comment by vinsec** [comment]
实测确实经过nginx sni分流，对性能影响挺大的，测速下行速度 峰/均值可能差4-6倍。目前没找到具体慢在哪里，怀疑是经过nginx分流，增加了多次 内核 -> Nginx -> 内核 -> Xray 的的数据拷贝和上下文切换。VPS性能比较差的情况估计就会这样。 感觉还是只能用 [Xray 监听 443 端口，通过 Fallbacks 功能 SNI 分流将网站流量回落到 Nginx 或 Caddy](https://xtls.github.io/document/level-1/fallbacks-with-sni.html#xray-%E9%85%8D%E7%BD%AE) 的方案了

@bbi8  不知道 @RPRX R大有啥思路么

**Comment by zhfreal** [comment]
我用的nginx/1.29.1，从官方的repo安装，对比haproxy3.0.11不严谨测速，没发现这两个工具的sni proxy有性能差异。

**Comment by vinsec** [comment]
> 我用的nginx/1.29.1，从官方的repo安装，对比haproxy3.0.11不严谨测速，没发现这两个工具的sni proxy有性能差异。

我是对比通过nginx sni分流到xray，以及客户端直连xray这两种方式。 前者性能损失非常大。
