### ISSUE TITLE
cloudflare closes grpc connection

### ISSUE THREAD

**Issue by its0ka** [XTLS/Xray-core#2780]
after starting the client and running 
"while true; do curl --socks5 127.0.0.1 1.1.1.1; done" in bash or
"while ($true) {C:\windows\curl --socks5 127.0.0.1 1.1.1.1}" in powershell
after a minute i get "curl: (52) Empty reply from server" and my xray connection to cloudflare closes and opens again immediately

client config: https://pastebin.com/73vdsKnH
server config: https://pastebin.com/sLLXMXb6

client log at the moment of disconnection: https://pastebin.com/uefMP36i
server log at the moment of disconnection:https://pastebin.com/sjmWJqtb

any way to solve this or create another config with cdn support and only 1 persistent connection?
if i use the same config but without a cdn, then connection can last for hours without disconnections

**Comment by its0ka** [comment]
thank you mahdi, then i'll use grpc over ws

**Comment by iopq** [comment]
> thank you mahdi, then i'll use grpc over ws

if you don't mind me asking, how did you solve your issue?

**Comment by its0ka** [comment]
@iopq https://pastebin.com/fcaQmCmb
