### ISSUE TITLE
请问能否在iOS行动装置启动 xraykit时，透过mac上的 conslog.app 看到 xray 的所有 log?

### ISSUE THREAD

**Issue by ghostwolf90** [XTLS/Xray-core#2785]
使用libxray打包出来的 xcframework 可以正常运作
唯独只有无法检视log的运作，因为想仿造当时 Mango 专案在运作时可以观看log
但碍于已联系不到作者，只能自行摸索开发现阶段的 go 程式码
尝试好几天都还没有办法把 log 显示出来，所以上来请教各位前辈

透過以下程式碼，也沒有運作
```
v2applog.RegisterHandlerCreator(v2applog.LogType_Console,
    func(lt v2applog.LogType, options v2applog.HandlerCreatorOptions) (v2commlog.Handler, error) {
          return v2commlog.NewLogger(CreateDefaultLogWriter()), nil
    })
```

**Comment by yuhan6665** [comment]
Not a core issue, please post in https://github.com/XTLS/libXray/issues/14
