### ISSUE TITLE
【‼️重要‼️】请在项目首页工具推荐列表移除关联了实名信息的项目

### ISSUE THREAD

**Issue by TrayBer** [XTLS/Xray-core#2792]
在寻找搭建工具时，发现该项目作者已经实名（中国大陆身份），请在首页移除推荐：
https://github.com/FranzKafkaYu/x-ui/

1、早期直接在个人项目页面挂微信收款码（目前已移除）、个人博客地址（含个人实名信息，例如微信二维码）；
2、Clash 项目集体停更**事件后**，该作者的个人博客仍然挂着个人微信二维码、微信公众号二维码（截止今日有效，已截图留存，为安全起见，不在这里提供），说明作者毫无安全意识；
3、该项目作者已在项目页面声明改为闭源；
4、该项目用户量较大（毕竟在 Web Panel 首位推荐），存在重大安全隐患；

‼️常识‼️：
**永远不要**使用**曾经**、**当前**实名过了的翻墙项目或辅助工具。

也请项目方、用户注意避开实名过的翻墙项目。
请各位项目作者、用户，注意个人安全。

**Comment by yuhan6665** [comment]
没有必要草木皆兵

**Comment by auto75** [comment]
推荐的那些xui面板都支持reality吗
重复#

**Comment by chise0713** [comment]
敢at世界，小心被block

**Comment by chise0713** [comment]
爱用用，不爱用不用，你可以提交pr删除那一行而不是在issue吐槽 #1878
