### ISSUE TITLE
v2rayN中这个xray.exe会在我不知情的情况下消耗2g流量，请问是什么原因

### ISSUE THREAD

**Issue by W1ndys** [XTLS/Xray-core#2799]
![image](https://github.com/XTLS/Xray-core/assets/109416673/6da16fbe-ad35-4c15-b111-aa52cc1d2603)

**Comment by fs8vsx59h** [comment]
那应该让谁消耗？v2rayN.exe?

**Comment by W1ndys** [comment]
> 那应该让谁消耗？v2rayN.exe?

我的意思是为什么会突然消耗这么多的流量，有没有什么规避方法，或者说消耗这么多是必然的

**Comment by fs8vsx59h** [comment]
它代理了多少流量他就消耗多少流量，有什么问题吗

**Comment by fs8vsx59h** [comment]
怀疑有东西偷跑流量就把xray日志存文件里

**Comment by W1ndys** [comment]
> 怀疑有东西偷跑流量就把xray日志存文件里

ok谢谢

**Comment by yuhan6665** [comment]
Not a core issue

**Comment by morning-start** [comment]
> > 怀疑有东西偷跑流量就把xray日志存文件里
> 
> ok谢谢

你看看测速文件，默认的是bytes=100000000，是800MB的。

**Comment by PLTAT** [comment]
未知异常 未开启代理 启动v2n后 xray开8k-12k个网络连接 这是正常的么 我记得旧版本是激活了代理之后才开始消耗流量 现在只要激活了 无论是本地还是代理都直接跑满硬件可承受带宽 是不是xray.exe被注入病毒了 这个问题是回报给v2n仓库 还是 xray仓库
