### ISSUE TITLE
建议添加类似wvray.exe后台运行程序

### ISSUE THREAD

**Issue by fxfxy** [XTLS/Xray-core#28]
建议添加类似wvray.exe后台运行程序，方便直接调用

**Comment by rprx** [comment]
发 v1.0.0 前简单调研过，Windows 无窗体可以通过多种其它方式来实现，所以没有增加编译 `wxray.exe` 的计划。

**Comment by badO1a5A90** [comment]
方式很多,如
建立一个hiderun.vbs文件,放在xray.exe同一目录
编辑内容为
```
CreateObject("WScript.Shell").Run "xray.exe",0
```
运行此vbs即可

**Comment by badO1a5A90** [comment]
也可以通过创建window服务/计划任务等方式实现

**Comment by rprx** [comment]
其实常见的 bat 批处理头加行 `@echo off` 也行，不过好像会闪一下。更推荐 vbs，简洁且似乎不会闪（待证实

**Comment by badO1a5A90** [comment]
> 其实常见的 bat 批处理头加行 `@echo off` 也行，不过好像会闪一下。更推荐 vbs，简洁且似乎不会闪（待证实

完全无感

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/101260823-72da5f00-372a-11eb-9254-60af286315c3.png)
![image](https://user-images.githubusercontent.com/38283893/101260834-8c7ba680-372a-11eb-93d0-0682112f3e05.png)
可以使用类似的手段进行无窗口后台运行

**Comment by rampageX** [comment]
CHP.EXE (Create Hidden Process)

http://www.commandline.co.uk/chp/

**Comment by fxfxy** [comment]
> > 其实常见的bat批处理头加行`@echo off`也行，不过好像会闪一下。更推荐vbs，简洁且似乎不会闪（待确认）
> 
> 完全无感

运行卡顿的电脑会闪一下

**Comment by fxfxy** [comment]
但还是建议增加wxray.exe，方便不同需求的用户直接使用

**Comment by fxfxy** [comment]
> 发v1.0.0前简单研究过，Windows无层次可以通过多种其他方式来实现，所以没有增加编译`wxray.exe`的计划。

但还是建议增加一下wxray.exe，方便不同需求的用户直接使用

**Comment by shenlijun** [comment]
> > 发v1.0.0前简单研究过，Windows无层次可以通过多种其他方式来实现，所以没有增加编译`wxray.exe`的计划。
> 
> 但还是建议增加一下wxray.exe，方便不同需求的用户直接使用

参看 @badO1a5A90 关于vbs的描述，一分钟的事，然后放个快捷方式到shell:startup里面，就可以开机启动了

**Comment by yezige** [comment]
win平台可以用powershell写脚本，用 `-WindowStyle Hidden` 参数
```
$currpath = Split-Path -Parent $MyInvocation.MyCommand.Definition
Start-Process -FilePath "${currpath}/core-xray/xray.exe" -ArgumentList "-config ${currpath}/config/blacklist-xray.json" -WindowStyle Hidden
```
