### ISSUE TITLE
如果reality偷的域名被重定向，那还能偷这个域名吗？

### ISSUE THREAD

**Issue by osongsongo** [XTLS/Xray-core#2806]
重定向过的域名支持h2跟tls1.3的话我试了是可以用的，但是这样符不符合reality的标准要求？被检测的风险会不会更高？

**Comment by xqzr** [comment]
重定向 发生在 HTTP 层(TLS 内层)

**Comment by osongsongo** [comment]
> 发生

所以说可以用吗？

**Comment by chise0713** [comment]
可以，会不会被检测看运气。
就中间人（人类）来说，你一个重定向域名怎么会进行这么多数据交换，先ban了再说。
但是网络审查又不是人来看，就算主动探测也不会发现什么问题。
