### ISSUE TITLE
Using X-Ray Core for Android

### ISSUE THREAD

**Issue by mistek131995** [XTLS/Xray-core#2808]
Hello, please tell me how to use X-Ray Core for Android? The file has no extension, is it used as a library in Android Studio? I'm still new to this, I would really appreciate a hint.

**Comment by chika0801** [comment]
https://github.com/2dust/v2rayNG/blob/master/.github/workflows/build.yml

You can refer to the commands used in the compilation file for the application v2rayNG.

**Comment by mistek131995** [comment]
> https://github.com/2dust/v2rayNG/blob/master/.github/workflows/build.yml
> 
> Вы можете обратиться к командам, используемым в файле компиляции для приложения v2rayNG.

In this example, they are building X Ray Core from source files, but I am interested in using what has already been built. As far as I understand it needs to be used in conjunction with NDK, am I right?

**Comment by yuhan6665** [comment]
I'd suggest use v2rayNG. There is a reason people develop client apps ;)
If you don't like VPN service, just use proxy only mode. It essentially run core with a config file.

**Comment by mistek131995** [comment]
I am interested in developing my own application, how else to gain new knowledge... I hope that someone will tell me how to use the build for Android.

**Comment by yuhan6665** [comment]
gomobile is the way to go

**Comment by mistek131995** [comment]
Regarding usage in Windows and, I think, in other operating systems similarly (Android = Linux, my guess):
The compiled file is executable, information about the launch is available on the official website. After launching, a proxy server is created on the device you are connecting to. IP - 127.0.0.1, port +1 - is specified in the inbounds block (if you specified port 10808, connect 10809). I managed to run everything in this version.

**Comment by YuMo226** [comment]
Have you found a solution yet? I also encountered the same problem

**Comment by mistek131995** [comment]
> Вы уже нашли решение? Я тоже столкнулся с такой же проблемой

Yes, you need to run the kernel as a process and connect to the proxy.
