### ISSUE TITLE
请问下 xray的tun 模式在windows上如何使用？

### ISSUE THREAD

**Issue by Uhtred009** [XTLS/Xray-core#2811]
请问下 xray的tun 模式在windows上如何使用 ？是按照issues 里面所提到的 
{
  "tun": {
    "inet4_address": "172.19.0.1/30",
    "stack": "system",
    "auto_route": true,
    "auto_detect_interface": true,
    "override_android_vpn": false
  },
  "outbounds": [
    {
      "protocol": "freedom"
    }
  ]
}    添加tun选项到 配置文件 ，然后启动 就可以自动转发系统的所有流量了吗 ？ 还是需要再配置一个虚拟网卡转发， 可以指点一下吗 ？

**Comment by chika0801** [comment]
这功能在测试分支中，都没什么人讨论使用，只有你自己测试了。

**Comment by Uhtred009** [comment]
可以给个大概的方向吗 ？

**Comment by chise0713** [comment]
没有

**Comment by chika0801** [comment]
建议你学sing-box的逻辑

参考 https://github.com/chika0801/sing-box-examples/tree/main/Tun

你可以把比如在windows下直连的文件名称加上比如xray.exe。这样sing-box来开TUN，代理的出站走你喜欢的core比如xray.exe。套一套的形式。

**Comment by Uhtred009** [comment]
@chika0801  感谢 一个非常有趣的解决方法

**Comment by zhangsan946** [comment]
xray的outbound windows下无法绑定interface，如果tun interface被选为默认路由的话，xray的outbound如何避免流量循环。

**Comment by vrnobody** [comment]
> xray的outbound windows下无法绑定interface，如果tun interface被选为默认路由的话，xray的outbound如何避免流量循环。

outbound可以指定interface啊。把[sendThrough](https://www.v2fly.org/config/outbounds.html#outboundobject)设置成物理网卡的IPv4地址（比如192.168.1.100)就可以。但是不知道为什么设置成IPv6地址不行。然后还要注意下DNS的问题。

**Comment by zhangsan946** [comment]
sendthrough有时候不行，xray的socketopt的windows下的interface逻辑可以参考：https://github.com/SagerNet/sing/blob/dev/common/control/bind_windows.go
