### ISSUE TITLE
请问 流量嗅探 原理？

### ISSUE THREAD

**Issue by z826540272** [XTLS/Xray-core#282]
路由器passwall，默认开启流量嗅探，客户端用国内DNS，查询解析是虚假ip，依然可以正常访问google等网站。
是不是开启 流量嗅探的情况下，xray会检查所有入站域名，重新对其进行DNS解析,然后按虚假ip返回数据？

**Comment by JimhHan** [comment]
> 当设置了sniffing中的enable为true,Xray处理此连接的流量时,会从流量的数据中,嗅探出域名

**Comment by rurirei** [comment]
https://github.com/v2fly/v2ray-core/blob/master/app/dispatcher/sniffer.go

**Comment by rprx** [comment]
@rurirei 请优先发 Xray-core 而不是 v2fly 的链接
