### ISSUE TITLE
geosite.dat 和geoip.dat这2个文件如何自定义位置

### ISSUE THREAD

**Issue by bzw1204** [XTLS/Xray-core#2826]
请问下geosite.dat 和geoip.dat这2个文件如何自定义位置

**Comment by hkbase** [comment]
在～/.bashrc文件末尾添加下面的内容，根据自己的文件路径修改：
```
root# vi ~/.bashrc
......
export XRAY_LOCATION_CONFIG=/usr/local/etc/xray
export XRAY_LOCATION_ASSET=/usr/local/share/xray
```
最后运行一下source ~/.bashrc 立即生效。

**Comment by bzw1204** [comment]
> 在～/.bashrc文件末尾添加下面的内容，根据自己的文件路径修改：
> 
> ```
> root# vi ~/.bashrc
> ......
> export XRAY_LOCATION_ASSET=/usr/local/share/xray
> ```
> 
> 最后运行一下source ~/.bashrc 立即生效。

感谢，已经解决了，我实在windows下使用的
