### ISSUE TITLE
为什么 outbound 可以写成一个结构， 但 routing 里的 rules 要写成 json.Raw ? 我想调用 routing.rules 里的 outboundTag 怎么用？

### ISSUE THREAD

**Issue by crazypeace** [XTLS/Xray-core#2833]
需要请教大佬。 为什么 outbound 可以写成一个结构， 但 routing 里的 rules 要写成 json.Raw ? 我想调用 routing.rules 里的 outboundTag 怎么用？

![image](https://github.com/XTLS/Xray-core/assets/665889/94e65b74-8254-4730-a6f8-8d7f3997689a)

![image](https://github.com/XTLS/Xray-core/assets/665889/a20ebd07-70e2-4b0b-a90c-ac3dac68e01d)

**Comment by Fangliding** [comment]
参考已有的函数解析出来咯（）
