### ISSUE TITLE
[Feature Request] Configurable Default outbound

### ISSUE THREAD

**Issue by X-Oracle** [XTLS/Xray-core#2834]
Hi.
in route section, when we have "ipIfNoneMatch" it will go to first entry of the outbound.

it is ok but what if I want to default to another outbound?
moving outbounds is sometimes hard if too many are there.

my suggestion is ...
adding a new key (named for ex: "defaultOutbound") in `route` so when there is no match, it would send request to the desired outbound instead of the first.

**Comment by Fangliding** [comment]
@X-Oracle sing box has this feature😢

**Comment by X-Oracle** [comment]
@Fangliding 

I know sing-box has it but x-ray core can benefit from this too.

Routing traffic to an outbound without rearranging outbounds is a great option from my opinion.

Sing box vless doesn't go well when client is x-ray core (v2rayN and V2rayNG) so I rather not switch to it.

**Comment by Fangliding** [comment]
add a route rule can make this
