### ISSUE TITLE
[Safety Request] Official and reproducible docker builds, and repo builds for Debian & RHEL ecosystems | 官方的, 可重现的 Docker builds，以及申请纳入 Debian 和 RHEL 生态系统的 repo builds.

### ISSUE THREAD

**Issue by R8s6** [XTLS/Xray-core#2837]
Docker builds can be used on virtually any Linux distros.

Currently there are 2 "endorsed" docker builds:
[iamybj/docker-xray](https://hub.docker.com/r/iamybj/docker-xray)
[teddysun/xray](https://hub.docker.com/r/teddysun/xray)

But questions arise immediately: who are iambj and teddysun anyways? Are they core developers of this project? Why can they be trusted?

There's seemingly no quick answers to their trustworthiness or identities (which, to their benefits, should be well protected from ccp anyways), and because chinese government can, as they wish, arrest and prosecute any person who tries to get past GFW, this is a sensitive issue with regards to the devs' and users' personal safety.

So it is utterly important to provide chain of trust from the source code to the docker builds, such that the docker builds are  built exactly from the source code.

On a lower priority, the same reasoning applies to my humble request for Debian & RHEL builds, too, because, if `xray` were accepted by debian or redhat linux, the package will have trusted maintainers, and this would make `xray` available and trustworthy for most servers.

Thank you very much.

### 中文

Docker builds 可以在几乎任何 Linux 发行版上使用。

目前有两个被链接的 Docker builds:
[iamybj/docker-xray](https://hub.docker.com/r/iamybj/docker-xray)
[teddysun/xray](https://hub.docker.com/r/teddysun/xray)

但我們难免立刻会问：iamybj 和 teddysun 到底是谁？他们是这个项目的核心开发人员吗？为什么可以信任他们？

对于他们的信誉或身份，似乎没有快速的答案（这些信息免于被中国政府得知对他们个人来说其实是很好的)，而由于中国政府可以逮捕和起诉任何一个尝试翻墙的人，这里提到的 docker build 的问题涉及到开发人员和用户的个人安全。

因此，从源代码到 Docker 构建提供信任链是非常重要的，以确保 Docker build 是完完全全从源代码精确构建的。

在较低的优先级上，同样的推理也适用于我对 Debian 和 RHEL builds 的谦虚请求，因为如果 `xray` 被 Debian 或 RedHat Linux 接受，该软件包将拥有可信的维护者，这将使 `xray` 在大多数服务器上是可用并且可信的。

非常感谢。

**Comment by R8s6** [comment]
Found official docker repo (发现官方 docker):
https://ghcr.io/xtls/xray-core

It's actually always been there under "packages" on the right side of the main page.

I added a simple line to `README.md`, which is now merged.

case closed.

**Comment by RPRX** [comment]
感谢你提的 issue，https://github.com/XTLS/Xray-core/commit/a476310aec06250f5e09262d1638157b7190ff1c 已移除 iamybj/docker-xray 并显著标注两处 Official

可以信任 @teddysun ，~~其实他的也相当于 Official~~

看到 tempest 是 @Fangliding 加的，@Fangliding 来说明一下情况，~~不过这个是开源脚本应该没问题~~

**Comment by Fangliding** [comment]
@RPRX 我朋友写的 非常简短随便看
最开始就是觉得为什么官方脚本这么长
