### ISSUE TITLE
API文档及示例补充讨论

### ISSUE THREAD

**Issue by crossfw** [XTLS/Xray-core#284]
对于API文档的示例,大家有什么建议吗?

首先,感谢各位开发者的付出,让我们可以使用到这么好用的穿墙工具.
对于其应用方向的开发者,现有API文档存在 只说明其作用,而未说明其使用方法的问题, 我在过去20天内独自开发了Xray对接SSPanel的开源辅助程序, 参照Xray源码对其API使用有些许了解, 所以想补充下API文档,为后来的开发者铺路.

目前我的设想是这样的: 
- ./docs里存.md文档, 说明其包含的API和其应参照的文件地址.
- ./examples 里放各个API的调用方法, 其对应的_test.go 内放具体实现方法(包括一开始的创建Client等操作).<br> 并且在文件中补足注释

```tree
├── docs
│   └── ...
├── examples
│   ├── inbound.go
│   ├── inbound_test.go
│   ├── alertInbound.go
│   ├── alertInbound_test.go
|   └── ...
└── README.md
```

**Comment by Xray9** [comment]
@crossfw 太支持了，感觉可以放到 https://xtls.github.io/develop/intro/

可以节省想贡献代码的人的很多时间

**Comment by crossfw** [comment]
前几天在上课， 所以目前咕了 HandlerService 的部分， 我先放在了我的仓库里
https://github.com/crossfw/Xray-API-documents
各位有什么建议可以提一下，主要的说明我还是采取了注释的形式完成，在 example 目录下有示例文件。

**Comment by crossfw** [comment]
API示例已经全部完成了

**Comment by arturwu168** [comment]
大大您好, 我看了您的範例但還是不太會用, 不知道您可否指斆一二, 感激不盡

**Comment by arturwu168** [comment]
我主是想加入一個user
