### ISSUE TITLE
按照官方文档(https://xtls.github.io/config/api.html#apiobject)配置了api，grpc服务的监听端口是不是10085？

### ISSUE THREAD

**Issue by cppbeliever** [XTLS/Xray-core#2845]
按照官方文档(https://xtls.github.io/config/api.html#apiobject) 配置了api，grpc服务的监听端口是不是10085？

如果是的话，我执行xray api stats, 为什么提示：failed to dial 127.0.0.1:8080

**Comment by chise0713** [comment]
https://xtls.github.io/document/command.html

**Comment by cppbeliever** [comment]
> https://xtls.github.io/document/command.html

@chise0713   这个信息对我没有用，兄弟！

**Comment by chise0713** [comment]
https://xtls.github.io/document/level-2/traffic_stats.html#%E6%9F%A5%E7%9C%8B%E6%B5%81%E9%87%8F%E4%BF%A1%E6%81%AF

**Comment by cppbeliever** [comment]
@chise0713 
输入：xray api statsquery --server=127.0.0.1:10088
输出： failed to dial 127.0.0.1:10085

兄弟，还是不行。

**Comment by chise0713** [comment]
dokodemo-door有没有开入口，配置文件放出来看看

**Comment by cppbeliever** [comment]
{
  // 1\_日志设置
  "log": {
    "loglevel": "debug", // 内容从少到多: "none", "error", "warning", "info", "debug"
    "access": "/home/benjamin/xray_log/access.log", // 访问记录
    "error": "/home/benjamin/xray_log/error.log" // 错误记录
  },
  // 2_DNS 设置
  "dns": {
    "servers": [
      "https+local://1.1.1.1/dns-query", // 首选 1.1.1.1 的 DoH 查询，牺牲速度但可防止 ISP 偷窥
      "localhost"
    ]
  },
  "api": {
    "tag": "api",
    "services": ["HandlerService", "LoggerService", "StatsService"]
  },
  "stats":{},
  "policy":{
      "levels": {
      "0": {
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    },
    "system": {
      "statsInboundUplink": true,
      "statsInboundDownlink": true,
      "statsOutboundUplink": true,
      "statsOutboundDownlink": true
    }
  },
  // 3*分流设置
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      // 3.1 防止服务器本地流转问题：如内网被攻击或滥用、错误的本地回环等
      {
        "type": "field",
        "ip": [
          "geoip:private" // 分流条件：geoip 文件内，名为"private"的规则（本地）
        ],
        "outboundTag": "block" // 分流策略：交给出站"block"处理（黑洞屏蔽）
      },
      {
        // 3.2 防止服务器直连国内
        "type": "field",
        "ip": ["geoip:cn"],
        "outboundTag": "block"
      },
      // 3.3 屏蔽广告
      {
        "type": "field",
        "domain": [
          "geosite:category-ads-all" // 分流条件：geosite 文件内，名为"category-ads-all"的规则（各种广告域名）
        ],
        "outboundTag": "block" // 分流策略：交给出站"block"处理（黑洞屏蔽）
      },
      {
     	 "inboundTag": ["api"],
     	 "outboundTag": "api",
      	 "type": "field"
      }
    ]
  },
  // 4*入站设置
  // 4.1 这里只写了一个最简单的 vless+xtls 的入站，因为这是 Xray 最强大的模式。如有其他需要，请根据模版自行添加。
  "inbounds": [
    {
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": “xxxx”, // 填写你的 UUID
            "flow": "xtls-rprx-vision",
            "level": 0,
            "email": “xxx”
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "dest": 8080 // 默认回落到防探测的代理
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "tls",
        "tlsSettings": {
          "alpn": "http/1.1",
          "certificates": [
            {
              "certificateFile": "/home/benjamin/xray_cert/xray.crt",
              "keyFile": "/home/benjamin/xray_cert/xray.key"
            }
          ]
        }
      }
    },
    {
    	"listen": "127.0.0.1",
   	 "port": 10085,
    	"protocol": "dokodemo-door",
    	"settings": {
      	"address": "127.0.0.1"
    	},
    	"tag": "api"
    }
  ],
  // 5*出站设置
  "outbounds": [
    // 5.1 第一个出站是默认规则，freedom 就是对外直连（vps 已经是外网，所以直连）
    {
      "tag": "direct",
      "protocol": "freedom"
    },
    // 5.2 屏蔽规则，blackhole 协议就是把流量导入到黑洞里（屏蔽）
    {
      "tag": "block",
      "protocol": "blackhole"
    }
  ]
}



@chise0713   谢谢你，帮我看看。

**Comment by chise0713** [comment]
你应该将api的路由放在最上方。你现在无法访问是因为private的block在api上面，127段属于private，被block了

**Comment by cppbeliever** [comment]
@chise0713   一语点醒梦中人啊，拜谢真大哥，感谢你眨眼之间解决困扰我几天的问题，请收下我的跪拜。感谢大哥。祝大哥梦想成真 。。谢谢谢谢。

**Comment by chise0713** [comment]
没问题就把issue关了吧

**Comment by cppbeliever** [comment]
@chise0713  好的。
