### ISSUE TITLE
xray服务器启用api,端口是10085，但是远程telnet这个端口不通，为什么？ 

### ISSUE THREAD

**Issue by cppbeliever** [XTLS/Xray-core#2858]
xray服务器启用api,端口是10085，但是远程telnet这个端口不通，为什么？

**Comment by zxbiao** [comment]
建议你先看看XRAY的API是用什么协议操作的
https://xtls.github.io/document/command.html#xray-api

**Comment by cppbeliever** [comment]
问题解决了，是因为vps 防火墙设置问题 ，谢谢回复。，
