### ISSUE TITLE
geoip.dat 和geosite.dat文件是什么格式的文件

### ISSUE THREAD

**Issue by hezhaozhao-git** [XTLS/Xray-core#2859]
geoip.dat 和geosite.dat文件是什么格式的文件，我想自己解析这两个文件，如何才能做到呢？

**Comment by hezhaozhao-git** [comment]
我想把他读取成字符串，如何才能做到？

**Comment by NSIOISN** [comment]
https://github.com/Loyalsoldier/v2ray-rules-dat

**Comment by kouyiguo** [comment]
本质是 protobuf 编码文件。
具体加载和解析可以参考
https://github.com/XTLS/libXray/blob/main/xray/geo.go

**Comment by kouyiguo** [comment]
They are protobuf encoded files.
Related codes in:
https://github.com/XTLS/libXray/blob/main/xray/geo.go

You can convert router.GeoIPList and router.GeoSiteList to what you want.

**Comment by hezhaozhao-git** [comment]
Ok, I've finished decoding this in my project: https://github.com/hezhaozhao-git/kitty_proxy

**Comment by yuhan6665** [comment]
answered. Thanks for your work BTW!
