### ISSUE TITLE
使用API 替换outbounds 后连接没重置

### ISSUE THREAD

**Issue by Alion548** [XTLS/Xray-core#286]
假设：
原outbounds tag out_proxy 连接到1.1.1.1，使用api将tag out_proxy 变更到2.2.2.2，使用 netstat -apn | grep 1.1.1.1 能看到好多条TCP连接依然存在。

**Comment by rprx** [comment]
平滑才是正常的吧

**Comment by crossfw** [comment]
> 假设：
> 原outbounds tag out_proxy 连接到1.1.1.1，使用api将tag out_proxy 变更到2.2.2.2，使用 netstat -apn | grep 1.1.1.1 能看到好多条TCP连接依然存在。

这应该和你policy配置有关吧[仅猜测]. 而且TCP TIME_WAIT状态也会保留一段时间

**Comment by Alion548** [comment]
有一种场景会出现问题：比如当前连接IP是：1.1.1.1，由于未知原因中断了（没有正确释放TCP链接），通过API切换到2.2.2.2，此时要刷新多次后才能使流量走2.2.2.2。
