### ISSUE TITLE
freedom 的目标地址要分配一个超级大的内存，是bug吗？怎么规避？

### ISSUE THREAD

**Issue by 50infivedays** [XTLS/Xray-core#2869]
runtime: out of memory: cannot allocate 30471455145721856-byte block (2017558528 in use)
fatal error: out of memory

goroutine 1242479 [running]:
runtime.throw({0x1302e25?, 0x3620d041c02?})
        runtime/panic.go:1077 +0x5c fp=0xc065a03178 sp=0xc065a03148 pc=0x43c59c
runtime.(*mcache).allocLarge(0xc065a031f8?, 0x6c41a0838033e2, 0x80?)
        runtime/mcache.go:236 +0x176 fp=0xc065a031c0 sp=0xc065a03178 pc=0x41ad36
runtime.mallocgc(0x6c41a0838033e2, 0x0, 0x0)
        runtime/malloc.go:1123 +0x4f6 fp=0xc065a03228 sp=0xc065a031c0 pc=0x411e56
runtime.rawstring(...)
        runtime/string.go:267
runtime.rawstringtmp(0x0?, 0x6c41a0838033e2)
        runtime/string.go:131 +0x3e fp=0xc065a03250 sp=0xc065a03228 pc=0x458a5e
runtime.concatstrings(0x0?, {0xc065a032e0?, 0x3, 0x0?})
        runtime/string.go:51 +0xe5 fp=0xc065a032c0 sp=0xc065a03250 pc=0x458445
runtime.concatstring3(0x0?, {0x838033df01010101?, 0x0?}, {0x14bf340?, 0x0?}, {0x13477f5?, 0x0?})
        runtime/string.go:64 +0x65 fp=0xc065a03320 sp=0xc065a032c0 pc=0x4586a5
github.com/xtls/xray-core/common/net.Destination.NetAddr({{0x14db8a0?, 0xc03e913fc4?}, 0x50?, 0x2?})
        github.com/xtls/xray-core/common/net/destination.go:93 +0x76 fp=0xc065a03380 sp=0xc065a03320 pc=0x6898b6
github.com/xtls/xray-core/common/net.Destination.String({{0x14db8a0?, 0xc03e913fc4?}, 0x9874?, 0x0?})
        github.com/xtls/xray-core/common/net/destination.go:111 +0x74 fp=0xc065a033c8 sp=0xc065a03380 pc=0x689994
github.com/xtls/xray-core/transport/internet.(*DefaultSystemDialer).Dial(0x1e09e40, {0x14dbad0?, 0xc053966ab0}, {0x0, 0x0}, {{0x14db8a0?, 0xc03e913fc4?}, 0x9518?, 0xc0?}, 0x0)
        github.com/xtls/xray-core/transport/internet/system_dialer.go:50 +0x85 fp=0xc065a034e8 sp=0xc065a033c8 pc=0x6e1465
github.com/xtls/xray-core/transport/internet.DialSystem({0x14dbad0, 0xc053966ab0?}, {{0x14db8a0?, 0xc03e913fc4?}, 0x0?, 0x0?}, 0x0)
        github.com/xtls/xray-core/transport/internet/dialer.go:130 +0x4b4 fp=0xc065a035b0 sp=0xc065a034e8 pc=0x6de054
github.com/xtls/xray-core/transport/internet/tcp.Dial({0x14dbad0, 0xc053966ab0}, {{0x14db8a0, 0xc03e913fc4}, 0x50, 0x2}, 0xc000313a40)
        github.com/xtls/xray-core/transport/internet/tcp/dialer.go:18 +0x1a9 fp=0xc065a036b8 sp=0xc065a035b0 pc=0xa43fc9
github.com/xtls/xray-core/transport/internet.Dial({0x14dbad0, 0xc053966ab0}, {{0x14db8a0?, 0xc03e913fc4?}, 0x3fc4?, 0xc0?}, 0xc000313a40?)
        github.com/xtls/xray-core/transport/internet/dialer.go:57 +0x1d0 fp=0xc065a03758 sp=0xc065a036b8 pc=0x6dcd30
github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dial(0xc000324880, {0x14dbad0?, 0xc053966ab0?}, {{0x14db8a0, 0xc03e913fc4}, 0x50, 0x2})
        github.com/xtls/xray-core/app/proxyman/outbound/handler.go:276 +0xb0b fp=0xc065a03910 sp=0xc065a03758 pc=0xa6204b
github.com/xtls/xray-core/proxy/freedom.(*Handler).Process.func1()
        github.com/xtls/xray-core/proxy/freedom/freedom.go:151 +0x335 fp=0xc065a039c0 sp=0xc065a03910 pc=0xc2a8b5
github.com/xtls/xray-core/common/retry.(*retryer).On(0xc065a03c08, 0xc065a03c70)
        github.com/xtls/xray-core/common/retry/retry.go:27 +0xc6 fp=0xc065a03a60 sp=0xc065a039c0 pc=0xc269a6
github.com/xtls/xray-core/proxy/freedom.(*Handler).Process(0xc000321b00, {0x14dbad0, 0xc053966ab0}, 0xc0435401e0, {0x14d2148, 0xc000324880})
        github.com/xtls/xray-core/proxy/freedom/freedom.go:135 +0x405 fp=0xc065a03cd0 sp=0xc065a03a60 pc=0xc28525
github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dispatch(0xc000324880, {0x14dbad0, 0xc053966ab0}, 0xc0435401e0)
        github.com/xtls/xray-core/app/proxyman/outbound/handler.go:206 +0x3f8 fp=0xc065a03d68 sp=0xc065a03cd0 pc=0xa610b8
github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc000311500, {0x14dbad0, 0xc053966ab0}, 0xc0435401e0, {{0x14db8a0, 0xc04b5a0990}, 0x50, 0x2})
        github.com/xtls/xray-core/app/dispatcher/default.go:443 +0xbc2 fp=0xc065a03eb8 sp=0xc065a03d68 pc=0x85e0e2
github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch.func1()
        github.com/xtls/xray-core/app/dispatcher/default.go:265 +0x5ef fp=0xc065a03fe0 sp=0xc065a03eb8 pc=0x85c4ef
runtime.goexit()
        runtime/asm_amd64.s:1650 +0x1 fp=0xc065a03fe8 sp=0xc065a03fe0 pc=0x472861
created by github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 1242476
        github.com/xtls/xray-core/app/dispatcher/default.go:238 +0x405

**Comment by Fangliding** [comment]
请提供配置
