### ISSUE TITLE
如果 UDP 53 端口，走 Xray 代理的话，会造成电脑重启后，时间同步服务无法网络自动同步，请问如何解决？

### ISSUE THREAD

**Issue by zw963** [XTLS/Xray-core#2870]
嘿， 最近家里的联通 vn009 5G 路由器遭遇了 DNS 绑架。直接将域名 github.githubassets.com  IP 地址硬编码为 0.0.0.0，我花七百多大洋买的，欲哭无泪。

有一个需求是这样，我自己写的透明代理脚本，在我的一台老本子上也在用，那个本子 BIOS 电池没电了，只要重启，时间就自动恢复到几年前，所以，重启后必须依赖 linux 的时间同步服务来调整时间。

为了解决 DNS 绑架问题，我曾经尝试写如下代码来配置 mangle 的 OUTPUT chain.

```
iptables -t mangle -A V2RAY_MASK -d 192.168.0.0/16 -p tcp -j RETURN
iptables -t mangle -A V2RAY_MASK -d 192.168.0.0/16 -p udp ! --dport 53 -j RETURN
```

但是这样配置后，重启我的旁路由 （重启后，立即运行各种 iptables 命令编写的 shell 脚本,来配置），时间无法同步了，一直是几年前的时间，这造成 xray 无法正确连接。

换成下面这行代码，重启后，时间时间自动同步了。

```
iptables -t mangle -A V2RAY_MASK -d 192.168.0.0/16 -j RETURN
```

但是这无法解决运营商光猫本地劫持域名的问题。

我用旁路由用的系统是 centos 8, 请问我该如何来修复这个问题？

谢谢。

**Comment by harvey-git** [comment]
`{
        "type": "field",
        "outboundTag": "direct",
        "inboundTag": [
          "transparent"
        ],
        "port": 123,
        "network": "udp"
      },`
在route下面的rules里面增加一条这个规则！

**Comment by zw963** [comment]
> `{ "type": "field", "outboundTag": "direct", "inboundTag": [ "transparent" ], "port": 123, "network": "udp" },` 在route下面的rules里面增加一条这个规则！

Hi, 你好，多谢回复，我按照你的提示，添加如下内容到 client 配置中。

```json
{
                "type": "field",
                "inboundTag": ["transparent"],
                "port": 123,
                "network": "udp",
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "inboundTag": ["transparent"],
                "port": 323,
                "network": "udp",
                "outboundTag": "direct"
            },
```

但仍旧不工作，我猜测可能是因为在 client 与 server 建立连接之前，时间相差很大，所以仍旧是失败。

我也尝试用 iptables 做同样的事情，貌似也是不生效。

```sh
    iptables -t mangle -A V2RAY_MASK -p udp --dport 123 -j RETURN
    iptables -t mangle -A V2RAY_MASK -p udp --dport 323 -j RETURN

    # 如果是旁路由，记得替换下面两行为：iptables -t mangle -A V2RAY_MASK -d 192.168.0.0/16 -j RETURN
    # 来确保时间同步服务可以正常工作。
    iptables -t mangle -A V2RAY_MASK -d 192.168.0.0/16 -p tcp -j RETURN
    iptables -t mangle -A V2RAY_MASK -d 192.168.0.0/16 -p udp ! --dport $dns_port -j RETURN
```

但是也不总是不生效，偶尔有那么一次，似乎可以的 ... 可能跟 systemd 的启动顺序有关吧，我实在 centos 8 上部署，
使用的时间同步服务如下：

```
[root@localhost ~]# systemctl status chronyd
● chronyd.service - NTP client/server
   Loaded: loaded (/usr/lib/systemd/system/chronyd.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-06-22 19:11:55 CST; 3min 20s ago
     Docs: man:chronyd(8)
           man:chrony.conf(5)
  Process: 819 ExecStartPost=/usr/libexec/chrony-helper update-daemon (code=exited, status=0/SUCCESS)
  Process: 771 ExecStart=/usr/sbin/chronyd $OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 779 (chronyd)
    Tasks: 1 (limit: 23020)
   Memory: 2.1M
   CGroup: /system.slice/chronyd.service
           └─779 /usr/sbin/chronyd

Jun 22 19:11:55 localhost.localdomain systemd[1]: Starting NTP client/server...
Jun 22 19:11:55 localhost.localdomain chronyd[779]: chronyd version 4.2 starting (+CMDMON +NTP +REFCLOCK +RTC +PRIVD>
Jun 22 19:11:55 localhost.localdomain chronyd[779]: Frequency -8.509 +/- 6.681 ppm read from /var/lib/chrony/drift
Jun 22 19:11:55 localhost.localdomain chronyd[779]: Using right/UTC timezone to obtain leap second data
Jun 22 19:11:55 localhost.localdomain systemd[1]: Started NTP client/server.
```

旁路由我使用一个 systemd 服务来启动 iptables, 我甚至加了 After=chronyd, 还是不工作。

```
[root@localhost system]# cat iptables-rule.service 
[Unit]
Description=Iptables rule
After=network.target
After=chronyd
Wants=network.target

[Service]
Type=oneshot
RemainAfterExit=yes
# 注意分号前后要有空格
ExecStart=/opt/etc/apply_iptables_rule.sh

[Install]
WantedBy=multi-user.target
```

**Comment by zw963** [comment]
忘了说了，chronyd 监听在 323

```
[root@localhost ~]# netstat -anlp |grep chronyd
udp        0      0 127.0.0.1:323           0.0.0.0:*                           778/chronyd         
udp6       0      0 ::1:323                 :::*                                778/chronyd         
unix  2      [ ]         DGRAM                    23855    778/chronyd          /run/chrony/chronyd.sock
unix  2      [ ]         DGRAM                    22139    778/chronyd    
```

**Comment by us254** [comment]
Adjust the firewall rules to ensure time synchronization: Your firewall rules must permit traffic for time synchronization, which by default uses NTP on UDP port 123. The current rules that include the NTP port seem to be structured correctly:

```
iptables -t mangle -A V2RAY_MASK -p udp --dport 123 -j RETURN
iptables -t mangle -A V2RAY_MASK -p udp --dport 323 -j RETURN
```
This setup should, in theory, mark the packets on the specified ports to bypass Xray and be directly processed, which should allow chronyd to synchronize the time without interference.

Make sure the custom systemd service unit for your iptables rules is ordered properly regarding chronyd.service. Use After=chronyd.service in the [Unit] section of your service file to ensure that your time synchronization completes before applying your firewall rules. 

```
[Unit]
Description=Iptables rule
After=network.target chronyd.service
Wants=chronyd.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/opt/etc/apply_iptables_rule.sh

[Install]
WantedBy=multi-user.target
Make sure you reload the systemd daemon and enable the updated service with:
```
```
systemctl daemon-reload
systemctl enable iptables-rule.service
systemctl start iptables-rule.service
```

After making these changes, you need to test the time synchronization on reboot to ensure chronyd is getting the correct time.

If the synchronization still fails, the unofficial workaround you mentioned with adding a sleep command in your script could be used as a last resort. 


The problem described sounds like it's related to the ordering and timing of different network services when the system boots.

**Comment by us254** [comment]
The JSON configuration provided previously for Xray focused on port 123, the standard NTP port. If your chronyd instance is also using port 323 for some reason (perhaps for internal communication), you’d need to account for this in both your iptables and Xray routing:

For iptables:

```
iptables -t mangle -A V2RAY_MASK -p udp --dport 323 -j RETURN

```

For Xray:

```
{
  "type": "field",
  "inboundTag": ["transparent"],
  "port": 323,
  "network": "udp",
  "outboundTag": "direct"
}
```


Adjust the systemd service file that handles your proxy configuration script to run after `chronyd.service`

test your configurations by restarting the system and checking the status of `chronyd`

```
systemctl restart chronyd
systemctl status chronyd
```

**Comment by zw963** [comment]
Wow, thank you very much! `After=network.target chronyd.service` works like a charm!

i guess i misusage the `After=` in systemd, following only network.target take effect.

```
After=network.target
After=chronyd
```
