### ISSUE TITLE
outbounds是否有限制？

### ISSUE THREAD

**Issue by clcc2019** [XTLS/Xray-core#2892]
outbounds如果配置上千个，然后使用路由做负载均衡，走相同outbounds概率比较大

**Comment by yomnxkcs** [comment]
随便统计了一下日志，1000个服务器用random均衡策略。一共抽了450次，抽到360个不同的服务器。被抽最多的一个服务器抽了5次。不是很均匀但还在合理范围内。我的服务器数量不是一千个，上面的是用实测数据按比例缩放。

你统计出来的数据是怎样的？

**Comment by yuhan6665** [comment]
Does not seem an issue
