### ISSUE TITLE
wireguard 入站 和出战 好像UDP 不能用 只能用TCP

### ISSUE THREAD

**Issue by YiGeRen-yl** [XTLS/Xray-core#2908]
wireguard 入站 和出战 好像UDP 不能用 只能用TCP

**Comment by ischub** [comment]
@YiGeRen-yl 建议直接贴配置和验证方法

**Comment by chise0713** [comment]
@YiGeRen-yl

**Comment by YiGeRen-yl** [comment]
> @YiGeRen-yl 建议直接贴配置和验证方法

,{
  "protocol": "wireguard",
  "tag": "wireguard-1",
  "settings": {
   "secretKey": "OOnyMUELLm8ez3w4bYtc3Leb2euftiy1F5xEFWM4QUE=",
    "Address": ["10.7.0.2/32"],
    "mtu": 1440,
"network": "tcp,udp",
    "peers": [
      {
                    "publicKey": "ILUhlUGYz4Bhtv5nInpMSTOHsvQo9TMsHYK5Ahu06mY=",
                    "preSharedKey": "lSjJw99jwfDyytjBaoARojfxGWhMj0dGrhAdZTCyUew=",
        "AllowedIPs": ["0.0.0.0/0","::/0"],
        "endpoint": "xxx:51820"
      }
    ],
        "kernelMode": false
  }
}
这个是出战配置 然后用入站SOCKS5 开启UDP测的 UDP block了
