### ISSUE TITLE
@YiGeRen-yl 建议直接贴配置和验证方法

### ISSUE THREAD

**Issue by YiGeRen-yl** [XTLS/Xray-core#2909]
@YiGeRen-yl 建议直接贴配置和验证方法

_Originally posted by @ischub in https://github.com/XTLS/Xray-core/issues/2908#issuecomment-1880381239_
          我按照这个网站 搭入站 然后用wireguard windows客户端 连上wiregaurd 也是UDP BLOCK TCP能用

**Comment by ischub** [comment]
@YiGeRen-yl 在官网文档和源码(infra/conf/wireguard.go)中均没有看到指定network的地方 

type WireGuardConfig struct {
 IsClient bool `json:""`

 KernelMode     *bool                 指定network的地方 

type W SecretKey      string                到指定network的地方 

type Address        []string               json:"address"
 Peers          []*WireGuardPeerConfig json:"peers"
 MTU            int32                  json:"mtu"
 NumWorkers     int32                  json:"workers"
 Reserved       []byte                到指定network的地方 

typ DomainStrategy string                到指定network的地方 

type Wire}

**Comment by ischub** [comment]
@YiGeRen-yl 你ya是不是有点无耻啊，为啥不把issues关闭，却把你自己发的内容删掉，单保留我的回复在挂在上面，是什么意思

**Comment by ischub** [comment]
@YiGeRen-yl 。。。居然是新开了一个issues，建议关闭这个issues
