### ISSUE TITLE
Fallback直接回落到https（反代

### ISSUE THREAD

**Issue by Fhokud** [XTLS/Xray-core#292]
也许可以节省web配置时间，直接丢给某个网站假装镜像站

**Comment by even0306** [comment]
可以回落给http的端口，然后重新跳转到https的端口

**Comment by Fhokud** [comment]
示例
域名aaa.aa VLESS_TCP_XTLS 443端口
由Fallback直接回落到https://openwrt.org

效果:访问https://aaa.aa返回openwrt.org的网页内容（反代



> 可以回落给http的端口，然后重新跳转到https的端口

访问https://aaa.aa会回返回一个openwtr.org的HTTP301，然后跳转到https://openwrt.org，而不是上述效果

**Comment by rprx** [comment]
1. 重复 https://github.com/XTLS/Xray-core/issues/89
2. 或者 https://github.com/XTLS/Xray-core/issues/271#issuecomment-784112855
3. 其实直接 301 到其它网站似乎也正常

**Comment by Hypdncy** [comment]
> 1. 重复 #89
> 2. 或者 [#271 (comment)](https://github.com/XTLS/Xray-core/issues/271#issuecomment-784112855)
> 3. 其实直接 301 到其它网站似乎也正常

现在的回落功能似乎无法使用，我使用的是VLESS-TCP-XTLS模式（xtls-rprx-direct），1.4版本，报错信息如下
nd: connection ends > proxy/vless/inbound: connection ends > context canceled
und: failed to process outbound traffic > proxy/freedom: connection ends > context canceled
und: failed to process outbound traffic > proxy/freedom: connection ends > context canceled
nd: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to transfer response payload > io: read/write on closed pipe
und: failed to process outbound traffic > proxy/freedom: connection ends > context canceled
und: failed to process outbound traffic > proxy/freedom: connection ends > context canceled
nd: connection ends > proxy/vless/inbound: connection ends > context canceled
nd: connection ends > proxy/vless/inbound: connection ends > context canceled

**Comment by Issads** [comment]
抓包看了看，现在回落到外站，fallback返回的是一个302重定向，之后就是被回落的外站与客户端直接建立连接了。

似乎这样是不合理的？因为既然跳转走了那么本服务器就不该有这么大流量了。。。正常应该是xray服务端直接向被回落的站点获取数据并返回给客户端把。。。
