### ISSUE TITLE
[Feature Request] DnsObject中的"clientIP"支持CIDR写法

### ISSUE THREAD

**Issue by Benjamin1919** [XTLS/Xray-core#2920]
目前DnsObject中的"clientIP"只支持单个IP，如"1.2.3.4"
希望可以支持CIDR写法，如"1.2.3.0/24" 

这样做的好处：
1. 进行ECS查询时可以在一定程度上隐藏自己的IP；
2. ECS查询的准确度和成功率要高于单个IP

**Comment by Fangliding** [comment]
反正不用写真的 随便填个不就行了(
