### ISSUE TITLE
[feature request] can you export some apis to a new repo as a client

### ISSUE THREAD

**Issue by Nyx2022** [XTLS/Xray-core#2922]
i found xray is very popular now, but in some cases, i wanna use a library as dependence to build a client program which support kind of protocols with xray server,but i can not find this lib, so can you export some apis to a new repo as a client,thank you in advance

**Comment by yuhan6665** [comment]
https://github.com/XTLS/libXray
https://github.com/2dust/AndroidLibXrayLite
