### ISSUE TITLE
Win7就到1.8.6了吗？

### ISSUE THREAD

**Issue by NERO-Tsui** [XTLS/Xray-core#2926]
直到弹出错误框，才后知后觉是go编译的﹏毫无编程基础，自编无能..最近正在折腾ventoy

**Comment by chise0713** [comment]
你本地拿 go1.20 编译不就行

**Comment by yomnxkcs** [comment]
> 你本地拿 go1.20 编译不就行

v1.8.7用到Multipath TCP，slices这些。用golang 1.20编译的时候要加什么参数吗？

**Comment by ischub** [comment]
@yomnxkcs 去下个新版go ，1.20编译要改mod ，

**Comment by yomnxkcs** [comment]
> @yomnxkcs 去下个新版go ，1.20编译要改mod ，

golang 1.21不支持win7，这个issue问的就是win7。
如果要改代码才能编译，对普通用户来说太难了。

**Comment by ischub** [comment]
@yomnxkcs go.mod改版本号为 1.20看能编译不  普通用户 就换系统吧

**Comment by yomnxkcs** [comment]
试了下用golang 1.20编译，去除掉slices和MultipathTCP相关的代码就可以编译，并且能在win7里面运行。目前用到这两个功能的代码量很少，改起来不是很难。

当然是否要支持win7的决定权在xray项目组手里。尊重项目组的最后决定。

**Comment by chise0713** [comment]
可以自己 fork 一个删掉那些内容来兼容 1.20，~~但是感觉不如升级系统~~

**Comment by Fangliding** [comment]
原来go1.21不支持win7吗。。那当初或许是该谨慎一点点

**Comment by chise0713** [comment]
但是 mptcp 必须要 go1.21。。。

**Comment by yuhan6665** [comment]
时代是向前发展的 项目不会花太多精力做兼容 老设备如果无法更新请使用旧版core。。

**Comment by RPRX** [comment]
所以 Win7 能直接运行 Xray-core 1.8.4 吗，还是说需要用 Go 1.20 重新编译？仅好奇

**Comment by AndersonGhost** [comment]
> 试了下用golang 1.20编译，去除掉slices和MultipathTCP相关的代码就可以编译，并且能在win7里面运行。目前用到这两个功能的代码量很少，改起来不是很难。
> 
> 当然是否要支持win7的决定权在xray项目组手里。尊重项目组的最后决定。

大佬，可否给出最新版本的能在win7上运行的Xray core 二进制文件呀？感谢！或者如何编译？

**Comment by vrnobody** [comment]
@AndersonGhost 

把go.mod中的go 1.22改成go 1.20，接着搜索SetMultipathTCP，把代码注释掉，其实只有两行。
然后就可以按普通go项目那样编译：`go build -v -o xray.exe -trimpath -ldflags "-s -w -buildid=" ./main`
go.mod里面好像还有个包要降下版本，忘了，根据编译提示改吧。

不想编译的话可以看下这个项目[Xray-core experimental](https://github.com/vrnobody/Xray-core/releases)，但是那里修改了很多代码没自己编译那么原汁原味。

**Comment by AndersonGhost** [comment]
> @AndersonGhost
> 
> 把go.mod中的go 1.22改成go 1.20，接着搜索SetMultipathTCP，把代码注释掉，其实只有两行。 然后就可以按普通go项目那样编译：`go build -v -o xray.exe -trimpath -ldflags "-s -w -buildid=" main` go.mod里面好像还有个包要降下版本，忘了，根据编译提示改吧。
> 
> 不想编译的话可以看下这个项目[Xray-core experimental](https://github.com/vrnobody/Xray-core/releases)，但是那里修改了很多代码没自己编译那么原汁原味。

好的，谢谢

**Comment by dashabiguard** [comment]
使用go1.21.4可编译，Windows7也可以运行，无需修改代码。
只需修改go.mod，把开头的go 1.22改成go1.21。
然后使用以下命令更新go.mod：
go mod tidy
最后正常编译即可：
go build -o xray.exe -trimpath -ldflags "-s -w -buildid=" ./main
