### ISSUE TITLE
请问下 小米AC2100路由器的 mt7621 mipsel_24kc架构，应该下载<Releases>中的哪个版本呀

### ISSUE THREAD

**Issue by songyuyx** [XTLS/Xray-core#2929]
Which version in <Releases> is match with XiaoMi R2100 Router?(mt7621 mipsel_24kc)

**Comment by lxhao61** [comment]
[Xray-linux-mips32le.zip](https://github.com/XTLS/Xray-core/releases/download/v1.8.7/Xray-linux-mips32le.zip)

**Comment by songyuyx** [comment]
> [Xray-linux-mips32le.zip](https://github.com/XTLS/Xray-core/releases/download/v1.8.7/Xray-linux-mips32le.zip)

谢谢指教，好人一生平安

**Comment by yuhan6665** [comment]
answered
