### ISSUE TITLE
vless reality节点无法连接

### ISSUE THREAD

**Issue by Berg-E5** [XTLS/Xray-core#2932]
大佬们，帮忙看看，创建的reality节点无法连接，是我哪里设置的不对吗
![9fc946851f1a633c9df0e97149ef0ca](https://github.com/XTLS/Xray-core/assets/125849101/51207b2f-032f-4722-8384-8d6485f08b86)

**Comment by chise0713** [comment]
你 dest 和 sni 不是相同的，dest 是否有包括该 sni 的证书

**Comment by yuhan6665** [comment]
Closing as no info
