### ISSUE TITLE
Route all Traffic through WARP Wireguard 

### ISSUE THREAD

**Issue by wulfric93** [XTLS/Xray-core#2933]
how to Pass all Traffic through WARP Wireguard ?

**Comment by yuhan6665** [comment]
https://xtls.github.io/document/level-2/warp.html

**Comment by MrSaeid007** [comment]
> https://xtls.github.io/document/level-2/warp.html

Hi, Since Wireguard support has been added to xray, Is it possible that Xray support l2tp too? many router in market only support l2tp & pptp and it will be great if we can use this.
Thank you @yuhan6665
