### ISSUE TITLE
1.8.6之后是否会通过GO 1.20编译Windows7版本？

### ISSUE THREAD

**Issue by zsbstephen** [XTLS/Xray-core#2936]
RT，还有macOS 10.13和10.14也是。

**Comment by chise0713** [comment]
https://github.com/XTLS/Xray-core/issues/2926#issuecomment-1887423955

**Comment by zsbstephen** [comment]
> [#2926 (comment)](https://github.com/XTLS/Xray-core/issues/2926#issuecomment-1887423955)
工控机、低功耗软路由升级win10比较困难，对硬件性能和资源消耗也会高很多，两难……

**Comment by yuhan6665** [comment]
如果不会整就停留在184吧

**Comment by RPRX** [comment]
所以 Win7 能直接运行 Xray-core 1.8.4 吗，还是说需要用 Go 1.20 重新编译？仅好奇

**Comment by dashabiguard** [comment]
https://github.com/XTLS/Xray-core/discussions/3373
