### ISSUE TITLE
请问如果routing 模块中rules 中有多条规则命中系统按什么逻辑执行？

### ISSUE THREAD

**Issue by Bearljj** [XTLS/Xray-core#294]
"routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      { // 劫持 53 端口 UDP 流量，使用 V2Ray 的 DNS
        "type": "field",
        "inboundTag": [
          "transparent"
        ],
        "port": 53,
        "network": "udp",
        "outboundTag": "dns-out" 
      },     
      {
        "type": "field", 
        "ip": [ 
          // 设置 DNS 配置中的国内 DNS 服务器地址直连，以达到 DNS 分流目的
          "223.5.5.5",
          "114.114.114.114"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "ip": [ 
          // 设置 DNS 配置中的国外 DNS 服务器地址走代理，以达到 DNS 分流目的
          "8.8.8.8",
          "1.1.1.1"
        ],
        "outboundTag": "proxy" // 改为你自己代理的出站 tag
      },

比如这个规则树下，客户端发起一个DNS查询，如果查询服务器是8.8.8.8；由于第一条规则就命中了，直接发往DNS-out出口；那么是不是直接就出站了而永远不会触发通过proxy的路由呢？
该问题再泛化一下，如果命中了rules中的多条规则系统如何执行？找了各个地方的文档也没有明确说明；另外，outbounds 中如果配置了协议为dns的 dns-out出口并设定了server属性，查询包是直接出站还是会再进入routing 中根据server中的值再次路由呢

**Comment by JimhHan** [comment]
> 如果命中了rules中的多条规则系统如何执行？

直接执行第一条被命中的路由，不会匹配后续规则

> 找了各个地方的文档也没有明确说明

[文档](https://xtls.github.io/config/base/routing/)中可能表述不是很清楚：
对于每一个连接，路由将根据这些规则依次进行判断，**当一个规则生效时，即将这个连接转发**至它所指定的 `outboundTag`或 `balancerTag`。

> 另外，outbounds 中如果配置了协议为dns的 dns-out出口并设定了server属性，查询包是直接出站还是会再进入routing 中根据server中的值再次路由呢

对于内置DNS服务器发出的查询，DNS出站会**直接**将其发送至server。

对于 A/AAAA 查询，DNS 出站会将其转发到内置DNS服务器。后续是否进入routing取决于dns设置。
对于其他种类的查询，直接发送至指定的server。

**Comment by Bearljj** [comment]
感谢解答，对于后面那个环节我还有些疑问，假设有如下DNS设置：
"dns": {
    "servers": [
      {
        "address": "223.5.5.5", //中国大陆域名使用阿里的 DNS
        "port": 53,
        "domains": [
          "geosite:cn",
          "ntp.org",   // NTP 服务器
          "$myserver.address" // 此处改为你 VPS 的域名
        ]
      }，
      {
        "address": "8.8.8.8", //非中国大陆域名使用 Google 的 DNS
        "port": 53,
        "domains": [
          "geosite:geolocation-!cn"
        ]
      }
    ]
  },
当网络中的客户端访问google.com时，由于符合geosite:geolocation-!cn应当向8.8.8.8发起DNS请求，此时的请求是否属于53端口上的dns请求而 命中rules里的第一条规则么？这么一来是不是就直接通过dns-out出站了？那么如何实现DNS分流呢，什么情况下才会触发rules里的关于8.8.8.8应该走proxy呢。
您说到的是内置DNS流量直接出站，是不是意味着内置DNS流量会直连系统网络设置中的DNS服务器？

**Comment by Bearljj** [comment]
实际使用中，如果把rules中的8.8.8.8改为direct确实会比proxy方式快，说明客户端的dns请求确实触发了这条规则，可是按照前面解释的逻辑，只要是53端口上的请求都会命中第一条直接通过dns-out出站了啊；系统到底是如何触发并捕获了访问8.8.8.8的53端口上的流量而不触发第一条dns-out规则，却能命中8.8.8.8的proxy规则呢

**Comment by JimhHan** [comment]
> 此时的请求是否属于53端口上的dns请求而 命中rules里的第一条规则么？这么一来是不是就直接通过dns-out出站了？那么如何实现DNS分流呢，什么情况下才会触发rules里的关于8.8.8.8应该走proxy呢。

可以为内置`DNS`服务器设置tag：

> 由内置 DNS 发出的查询流量，除 localhost 和 DOHL_ 模式外，都可以用此标识在路由使用 inboundTag 进行匹配。

> 您说到的是内置DNS流量直接出站，是不是意味着内置DNS流量会直连系统网络设置中的DNS服务器？
不经过本地设置，直接向指定的服务器发送查询。

> 系统到底是如何触发并捕获了访问8.8.8.8的53端口上的流量而不触发第一条dns-out规则，却能命中8.8.8.8的proxy规则呢

因为您第一条路由中设置了`inboundTag`。

**Comment by Bearljj** [comment]
再次感谢！
最后一个解释正好触及我另一个问题，顺便请教：
在inbounds中配置的任意门协议中打了标签的流量是否只含iptables转发来的流量？所以当客户端发向V2ray内置DNS服务的dns查询流量上会有标签，而客户端通过dns模块拿到dns服务地址后自行发起的DNS流量就没有标签了，所以会命中后面的规则？

**Comment by JimhHan** [comment]
> 在inbounds中配置的任意门协议中打了标签的流量是否只含iptables转发来的流量？

任意门会对所有经过的流量打上标签。

> 而客户端通过dns模块拿到dns服务地址后自行发起的DNS流量就没有标签了，所以会命中后面的规则？

内置DNS服务器发出的所有流量均会被打上标签。这个标签取决于dns设置中的`tag`。如果`tag`为空值，则会被打上随机标签。

**Comment by Bearljj** [comment]
如果任意门标签为A，DNSobject上的标签为B；当客户端浏览器访问google.com时，首先发起DNS查询，此时被iptables转发至任意门，打上了标签A，然后进入DNS模块，发现应该发往8.8.8.8,此时是会再被打上B么?那系统是在哪个环节去触发DNS模块中的规则呢？是不是流量一进入本机53端口自动就去触发，然后出站的标签就已经替换为DNS设置中的tag了？

**Comment by JimhHan** [comment]
> 然后进入DNS模块，发现应该发往8.8.8.8,此时是会再被打上B么?

是的。准确来讲，DNS查询进入内置DNS服务器后，会丢掉原有的tag。

> 那系统是在哪个环节去触发DNS模块中的规则呢？

当其他模块通过内置DNS服务器进行查询时触发。

> 是不是流量一进入本机53端口自动就去触发，然后出站的标签就已经替换为DNS设置中的tag了？

不是，只有DNS出站将查询转发给内置DNS服务器后，才会替换tag。

**Comment by Bearljj** [comment]
是不是流量一进入本机53端口自动就去触发，然后出站的标签就已经替换为DNS设置中的tag了？

不是，只有DNS出站将查询转发给内置DNS服务器后，才会替换tag。

如果系统劫持了53端口，相当于本机就是一台DNS服务器了，如果执行nslookup www.google.com 127.0.0.1,那么这个查询是否会触发DNS模块，将查询转发至8.8.8.8并将出站流量打上标签B呢

**Comment by JimhHan** [comment]
> 如果系统劫持了53端口，相当于本机就是一台DNS服务器了，如果执行nslookup www.google.com 127.0.0.1,那么这个查询是否会触发DNS模块，将查询转发至8.8.8.8并将出站流量打上标签B呢

依据具体情况而定。
要达到此场景，需要一个监听`127.0.0.1:53` 的 `dokodemo-door`，与一个有效的路由规则将来自此入站的请求转发到`dns`出站。
