### ISSUE TITLE
不支持Windows7也应该说明一下吧

### ISSUE THREAD

**Issue by wilsonjor** [XTLS/Xray-core#2942]
不支持Windows7也应该说明一下吧，害的我瞎折腾半天找不出原因！

**Comment by CosecantNeko** [comment]
不支持 Windows 7 的是 go 1.21
不是 xray
而且 go 也说了 1.20 是最后一个支持 win7 的版本

你用 1.20 go 编译 xray 就能在 win7 上跑了

**Comment by chise0713** [comment]
这是上游 go 的锅，和 Xray 项目没关系。
自从 go1.21 开始，很多远古系统都不能运行了，是 go 的决定

**Comment by chise0713** [comment]
> 不支持 Windows 7 的是 go 1.21 不是 xray 而且 go 也说了 1.20 是最后一个支持 win7 的版本
> 
> 你用 1.20 go 编译 xray 就能在 win7 上跑了

1.8.7 有些包是依赖 go1.20 的，所以还得改代码，麻烦。不如就用 1.8.6

**Comment by yuhan6665** [comment]
可以 release 说明了

**Comment by RPRX** [comment]
所以 Win7 能直接运行 Xray-core 1.8.4 吗，还是说需要用 Go 1.20 重新编译？仅好奇

**Comment by KC9226** [comment]
> 所以 Win7 能直接运行 Xray-core 1.8.4 吗，还是说需要用 Go 1.20 重新编译？仅好奇

win7 下Xray-core 1.8.7之前的版本都能正常运行。

**Comment by RPRX** [comment]
> win7 下Xray-core 1.8.7之前的版本都能正常运行。

如果只是升级了某个依赖导致了 v1.8.7 不能运行，下个版本可以先回退那个依赖，麻烦你找下是哪个

**Comment by Fangliding** [comment]
I'm afraid 1.8.6 is the last version available for Win7
