### ISSUE TITLE
延迟高的出奇

### ISSUE THREAD

**Issue by shentong0722** [XTLS/Xray-core#2945]
（怀疑是延迟问题但是不确定），自建的VMESS节点，VPS配置2核2G绝对够用，我的网络环境是电信1000Mbps宽带，VPS是万兆，用speedtest测速基本都能跑满800+速度说明没有问题，但是打开网页白屏时间很长，真的特别长，非常影响日常使用体验，打开之后速度也没问题，比如看youtube 8K没有任何卡顿

**Comment by stqfdyr** [comment]
能用不得了，在审查制度比肩伊朗的河南，我的 reality 都 jb 慢的不能用了快，昨天晚上刚搭建两个 reality 节点，跑满带宽，今天一看只剩下一点速度了，试了好多次都是这样

**Comment by shentong0722** [comment]
> 能用不得了，在审查制度比肩伊朗的河南，我的 reality 都 jb 慢的不能用了快，昨天晚上刚搭建两个 reality 节点，跑满带宽，今天一看只剩下一点速度了，试了好多次都是这样，这 jb 谁研究的呢？

问题倒是没有不过我在做机场主，靠这个赚点小钱，还是想尽可能把节点效率提上去

**Comment by chika0801** [comment]
你要说你的vps是不是回cn优化线路，还是你用了如先到国内机，国内到国外中转了的。不说靠猜也帮不了你。并且你想要别人帮到你，不发个配置（两端），别人也帮不到你。

**Comment by shentong0722** [comment]
服务端现在在用xui测试，配置大概都是这个模板：
![image](https://github.com/XTLS/Xray-core/assets/63089521/1444ee25-b8fa-4a44-9350-a288678aef61)
客户端Ubuntu22上用的Clash Verge，Clash-meta内核，测速基本如下图：延迟基本3000+
![image](https://github.com/XTLS/Xray-core/assets/63089521/147ce359-6ad8-4137-8220-3a3fa758157f)

**Comment by boy516** [comment]
看一下你的上传，有时候上传占满可能会有这种情况。

**Comment by shentong0722** [comment]
> 看一下你的上传，有时候上传占满可能会有这种情况。

上传？什么意思？客户端的上传还是服务端的？

**Comment by boy516** [comment]
> > 看一下你的上传，有时候上传占满可能会有这种情况。
> 
> 
> 
> 上传？什么意思？客户端的上传还是服务端的？

看看你的上传，有没有把上传占满

**Comment by shentong0722** [comment]
> > > 看一下你的上传，有时候上传占满可能会有这种情况。
> > 
> > 
> > 上传？什么意思？客户端的上传还是服务端的？
> 
> 看看你的上传，有没有把上传占满

那肯定是没有的，我基本不用上传：
![image](https://github.com/XTLS/Xray-core/assets/63089521/b0bad3d3-d99c-4c4d-9440-72afd4b6f62c)

**Comment by iKira** [comment]
1、你开机场，光这一点就不会有太多人理你。
2、没有日志、没有服务端和客户端详细环境说明，更加不会有人理你。
3、本质上这是你的使用问题，不是issue。

**Comment by stqfdyr** [comment]
> > 能用不得了，在审查制度比肩伊朗的河南，我的 reality 都 jb 慢的不能用了快，昨天晚上刚搭建两个 reality 节点，跑满带宽，今天一看只剩下一点速度了，试了好多次都是这样，这 jb 谁研究的呢？
> 
> 问题倒是没有不过我在做机场主，靠这个赚点小钱，还是想尽可能把节点效率提上去

你都开机场了，只能顺从你了
