### ISSUE TITLE
ss命令看xray会有用随机的udp端口

### ISSUE THREAD

**Issue by toyo2333** [XTLS/Xray-core#2952]
docker部署的，host模式

inbound只监听了TCP 443，但用 `ss -tulpn` 有时候就看到 xray会随机用一个udb端口

```
Netid State  Recv-Q Send-Q  Local Address:Port    Peer Address:Port                                   
udp   UNCONN 0      0                   *:49489              *:*     users:(("xray",pid=25178,fd=54))
.....
```

想问问是我哪里配置的问题还是说机制上是这样的？

**Comment by toyo2333** [comment]
机器上也有Hy2，用udp。xray随机用udp端口是什么作用啊？
Netid   State    Recv-Q    Send-Q       Local Address:Port        Peer Address:Port                                          
udp     UNCONN   0         0                        *:443                    *:*       users:(("hysteria",pid=10730,fd=3))   
udp     UNCONN   0         0                        *:44643                  *:*       users:(("xray",pid=11837,fd=23))      
udp     UNCONN   0         0                        *:52432                  *:*       users:(("xray",pid=11837,fd=53))

**Comment by KobeArthurScofield** [comment]
只要有任何从 Xray 发出去的 UDP 数据就会自动开启这样一个端口，比如 DNS 查询或者代理了 UDP 数据包并且转发了。

正常现象，任何程序发送 UDP 包都会有这样一个随机端口，超时结束后会自动消失。

**Comment by toyo2333** [comment]
了解了 谢谢！
