### ISSUE TITLE
dokodemo-door protocol with multiple destinations

### ISSUE THREAD

**Issue by miladrahimi** [XTLS/Xray-core#2958]
Is it possible to configure a "dokodemo-door" inbound with support for multiple addresses, utilizing load balancing among them? Similar to the shadowsocks outbound feature, where multiple servers are specified, and it employs round-robin or other algorithms to distribute the load evenly across the defined servers.

Current inbound:
```json
    {
      "listen": "0.0.0.0",
      "port": 1234,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "1.2.3.4"
      },
      "tag": "relay"
    }
```

Expected inbound:
```json
    {
      "listen": "0.0.0.0",
      "port": 1234,
      "protocol": "dokodemo-door",
      "settings": {
        "addresses": ["1.2.3.4", "3.4.5.6", "5.6.7.8"]
      },
      "tag": "relay"
    }
```

**Comment by yuhan6665** [comment]
Please try load balancing in routing
https://xtls.github.io/config/routing.html#balancerobject

**Comment by miladrahimi** [comment]
I've read that but it doesn't work with the "dokodemo-door" protocol, I want to expose a single port and have multiple destinations.

**Comment by yuhan6665** [comment]
Please try it and post config and logs if not working

**Comment by miladrahimi** [comment]
@yuhan6665 I tested the following config but it doesn't work. 

I'm trying to expose port 1000 and forward the incoming traffic from that port to 127.0.0.1:2000 and 127.0.0.1:3000, the load balancing strategy could be random or round-robin, it doesn't matter.

```json
{
  "inbounds": [
    {
      "port": 1000,
      "protocol": "dokodemo-door",
      "settings": {
        "network": "tcp,udp"
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {
        "redirect": "127.0.0.1:2000"
      },
      "tag": "outbound1"
    },
    {
      "protocol": "freedom",
      "settings": {
        "redirect": "127.0.0.1:3000"
      },
      "tag": "outbound2"
    }
  ],
  "routing": {
    "rules": [
      {
        "type": "field",
        "network": "tcp,udp",
        "balancerTag": "load-balancer"
      }
    ],
    "balancers": [
      {
        "tag": "load-balancer",
        "selector": ["outbound1", "outbound2"],
        "strategy": {
          "type": "random"
        }
      }
    ]
  }
}
```
