### ISSUE TITLE
Reality偷PVE，回落时PVE能访问，但PVE中的控制台ws方式连接，无法访问。

### ISSUE THREAD

**Issue by ZqinKing** [XTLS/Xray-core#2959]
xtls+reality偷本地的PVE服务器，直接访问PVE时页面能打开，PVE控制台无法正常使用。

reality配置使用样例中的模板配置。

PVE报错如下：
VM106 main.js:145  WebSocket connection to 'wss://xxx.xxx.xxx:8443/api2/json/nodes/kvm/vncwebsocket?port=5901&vncticket=PVEVNC%3A65ADC41B%3A%3A2onAaej30Iby7Smd0pf6lsdXYLC6dYSXYArmVHtA0E2jQOr%2FFfGPBCZjeai1AmvPtBWIbDHITKG7y72lip63kRoJ3ZhGfbU6QPbDq%2B1xBhJBUb6Ymju4ntGahChM0LJAT2RuCXtnzUAcX26opyVmKo4r3V8bJXgwQ6RNNLGU5cTWlkf0vFIX8hr7cLvY56JuV92ix1mWHMlaC646kD6EZ28U58461F5yEHW%2BQlhhNhkzErG1K4PO9%2FxTzDdTQKGNXsddpFH38m60MtX2GQQw5tBeP5XbyLnVwflBi0RlAkYzrC%2BXO%2F486%2BKNDejttIM9CZF8gr%2FR1fyL8n%2FTJUSh%2BQ%3D%3D' failed:

**Comment by eatbaba** [comment]
是这样的，pve的wss是js调用的，pve的wss的请求地址被js写的是绝对路径。比如请求的时候是请求xxx.com/xxxx，而不是直接请求根目录/xxxx。可能需要反代修改一下返回的js。

**Comment by ZqinKing** [comment]
> 是这样的，pve的wss是js调用的，pve的wss的请求地址被js写的是绝对路径。比如请求的时候是请求xxx.com/xxxx，而不是直接请求根目录/xxxx。可能需要反代修改一下返回的js。

嗯，确实是绝对路径，但是路径的host地址是xray的回落地址，页面可以正常回落。
