### ISSUE TITLE
从V2ray复制过来的配置文件无法工作

### ISSUE THREAD

**Issue by Bearljj** [XTLS/Xray-core#296]
我有一个一直配置好trojan的VPS，已经用了将近一年了，最近在测试Xray，先不管后面的iptables配置问题，同样的配置文件，用./v2ray -config ./config.json 启动后 其他机器运行curl 有如下返回；
~ » curl -Is -x 192.168.50.200:1088 https://www.google.com  yaoyuan@MacBook-Pro
HTTP/1.1 200 Connection established
同一个配置文件
sudo -u xray_tproxy ./Xray -c ./config.json启动后再用同样的测试客户机运行curl命令无返回，日志也没有输出
{
  "log": {
    "access": "/usr/local/Xray/access.log",
    "error": "/usr/local/Xray/error.log",
    "loglevel": "info"
  },
  "inbounds": [
    {
      "port": 1088,
      "listen": "0.0.0.0",
      "protocol": "http",
      "settings": {
        "userLevel": 0,
        "auth": "noauth",
        "udp": true,
        "ip": "0.0.0.0"
      }
    },
    {
      "port": 12345,
      "protocol": "dokodemo-door",
      "settings": {
        "network": "tcp,udp",
        "followRedirect": true
      },
      "streamSettings": {
        "sockopt": {
          "tproxy": "tproxy"
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "trojan",
      "tag": "proxy",
      "streamSettings": {
                "network": "tcp",
                "security": "tls"
            },
      "settings": {
       "servers": [
          {
            "address": "********",
            "port": 443,
            "password": "*********",
            "level": 0
          }
         ]
        }
    },
    {
      "protocol": "freedom",
      "settings": {
           "domainStrategy": "UseIP"
      },
      "tag": "direct"
    },
    {
      "tag": "dns-out",
      "protocol": "dns"
    }
  ],
  "dns": {
     "hosts": {
        "**********": "*************"
    },
     "servers": [
      {
        "address": "223.5.5.5", //中国大陆域名使用阿里的 DNS
        "port": 53,
        "clientIp": "1.1.1.1",
        "domains": [
          "geosite:cn",
          "ntp.org",   // NTP 服务器
          "***************"
        ]
      },
      {
        "address": "114.114.114.114", //中国大陆域名使用 114 的 DNS (备用)
        "port": 53,
        "clientIp": "1.1.1.1",
        "domains": [
          "geosite:cn",
          "ntp.org",   // NTP 服务器
          "***************"
        ]
      },
      {
        "address": "8.8.8.8", //非中国大陆域名使用 Google 的 DNS
        "port": 53,
        "clientIp": "1.1.1.1",
        "domains": [
          "geosite:geolocation-!cn"
        ]
      },
      {
        "address": "1.1.1.1", //非中国大陆域名使用 Cloudflare 的 DNS
        "port": 53,
        "clientIp": "1.1.1.1", 
        "domains": [
          "geosite:geolocation-!cn"
        ]
      },
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "domainStrategy": "IPIfNonMatch",
    "settings": {
      "rules": [
        { // 劫持 53 端口 UDP 流量，使用 V2Ray 的 DNS
        "type": "field",
        "inboundTag": [
          "transparent"
        ],
        "port": 53,
        "outboundTag": "dns-out" 
      },    
      { // 直连 123 端口 UDP 流量（NTP 协议）
        "type": "field",
        "inboundTag": [
          "transparent"
        ],
        "port": 123,
        "network": "udp",
        "outboundTag": "direct" 
      },
      {
        "type": "field",
        "domain": ["geosite:cn"],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "source": [
           "192.168.50.198"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field", 
        "ip": [ 
          // 设置 DNS 配置中的国内 DNS 服务器地址直连，以达到 DNS 分流目的
          "223.5.5.5",
          "114.114.114.114"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "ip": [ 
          // 设置 DNS 配置中的国外 DNS 服务器地址走代理，以达到 DNS 分流目的
          "8.8.8.8",
          "1.1.1.1"
        ],
        "outboundTag": "proxy" // 改为你自己代理的出站 tag
      },   
        {
          "type": "field",
          "ip": ["geoip:private"],
          "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": ["geoip:cn"],
          "outboundTag": "direct"
        },
        {
        "type": "field",
        "protocol":["bittorrent"], 
        "outboundTag": "direct"
        }
      ]
    }
  }
}

**Comment by rprx** [comment]
目测是程序未成功启动
