### ISSUE TITLE
使用XUI面板 Xray内核1.5.8 Vless可以正常使用，内核只要高于1.5.8就报错。。。。。。

### ISSUE THREAD

**Issue by boy516** [XTLS/Xray-core#2960]
Xray 1.8.7 (Xray, Penetrates Everything.) 3f0bc13 (go1.21.5 linux/amd64)

A unified platform for anti-censorship.

2024/01/21 21:55:09 [Info] infra/conf/serial: Reading config: bin/config.json

Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: VLESS clients: "flow" doesn't support "xtls-rprx-direct" in this version

感谢回复~~~~~~

**Comment by ywm** [comment]
你使用的Xui面板问题
请仔细阅读报错内容，查看对应config文件做出更改
新版本中删除了此流控

**Comment by boy516** [comment]
> 你使用的Xui面板问题 请仔细阅读报错内容，查看对应config文件做出更改 新版本中删除了
感谢回复

> 你使用的Xui面板问题 请仔细阅读报错内容，查看对应config文件做出更改 新版本中删除了此流控

感谢回复，我找了半天没找到文件位置

**Comment by boy516** [comment]
> xtls

找到了 找到了

**Comment by yuhan6665** [comment]
Answered
