### ISSUE TITLE
Vmess - user do not exist

### ISSUE THREAD

**Issue by dugong-lewat** [XTLS/Xray-core#2964]
Can anyone explain why the "user do not exist" even though I have done it carefully
this happens only in VMESS

![Screenshot_20240123-220508](https://github.com/XTLS/Xray-core/assets/110967975/b32da56b-9073-4936-853f-14fdaceac7cb)
![Screenshot_20240123-220620~2](https://github.com/XTLS/Xray-core/assets/110967975/24c1cc16-ab55-4258-a574-23b417b5d12d)
![Screenshot_20240123-220315~2](https://github.com/XTLS/Xray-core/assets/110967975/675fcd13-1cb9-46ac-9145-5a8f2b11e1a0)

**Comment by Fangliding** [comment]
I have encountered this issue on my server before, but I did not spend time investigating it. Later, I lost access to that server and was unable to reproduce it to locate the problem
Based on my experience, VLESS doesn't have this problem, you can try it

**Comment by Fangliding** [comment]
> I have encountered this issue on my server before, but I did not spend time investigating it. Later, I lost access to that server and was unable to reproduce it to locate the problem Based on my experience, VLESS doesn't have this problem, you can try it

Btw, the same config can well work on other server, very very strange

**Comment by signigelchan** [comment]
Same issue, try reboot your server .

**Comment by ymliusu** [comment]
Is that the same time between client and server?

**Comment by yuhan6665** [comment]
可能的原因：

客户端和服务器端的用户 ID 不匹配。
客户端与服务器的时间不匹配，误差超过 90 秒钟。
