### ISSUE TITLE
Fragment for Vless and Vmess links

### ISSUE THREAD

**Issue by bjerfan** [XTLS/Xray-core#2965]
Hello, Is there anyway to make fragments from inside the vless:// or vmess:// links? i have seached and tried so many different methods to see if this works on links but the only way is config's json file. Can we have it from the link in next versions? it would be really good!

**Comment by Fangliding** [comment]
@bjerfan Fragment is an option for free outbound and is usually not used alone but in conjunction with other outbounds. This means it needs a complete config file to use, but the share link only contains information for a single outbound
