### ISSUE TITLE
多用户和流量统计 配置文件写法

### ISSUE THREAD

**Issue by gcphym** [XTLS/Xray-core#297]
加了一个用户，然后根据 https://xtls.github.io/config/base/api/,  https://xtls.github.io/config/base/policy/,  https://xtls.github.io/config/base/stats/, 这三篇想开启统计，但是搞好上不了网了，提示
```[Warning] [1456737508] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://104.19.92.118/b0c5): 502 Bad Gateway > websocket: bad handshake] > common/retry: all retry attempts failed```
我的配置文件是这样的
```
{
  "log": {
    "loglevel": "warning"
  },
  "api": {
    "tag": "api",
    "services": [
      "StatsService"
    ]
  },
  "dns": {},
   "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "block"
      }
    ]
  },
  {
  "settings": {
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      }
    ]
  },
  "strategy": "rules"
  },
  "policy": {
    "levels": {
      "0": {
        "statsUserUplink": true,
        "statsUserDownlink": true,
      }
    },
    "system": {
      "statsInboundUplink": true,
      "statsInboundDownlink": true,
      "statsOutboundUplink": true,
      "statsOutboundDownlink": true
    }
  },
  "inbounds": [
    {
      "port": 10000,
      "listen": "127.0.0.1",
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "email": "a",
	    "id": "40d3d26c-bf99-40c8-938d-8189d6e0ad5d",
	    "level": 0
          },
          {
            "email": "b",
	    "id": "40d3d26c-bf99-40c8-938d-8189d6e0ad5e",
	    "level": 0
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "ws",
        "security": "none",
        "wsSettings": {
          "path": "/b0c5"
        }
      }
    },
    {
    "listen": "127.0.0.1",
    "port": 10085,
    "protocol": "dokodemo-door",
    "settings": {
      "address": "127.0.0.1"
    },
    "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "tag": "block"
    }
  ],
  "transport": {},
  "stats": {},
  "reverse": {}
}
```
请好心人帮我看看问题在哪，谢谢

**Comment by gcphym** [comment]
这是我之前正常使用的配置
```
{
  "log": {
    "loglevel": "warning"
  },
  "api": null,
  "dns": {},
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "block"
      }
    ]
  },
  "policy": {},
  "inbounds": [
    {
      "port": 10000,
      "listen": "127.0.0.1",
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "40d3d26c-bf99-40c8-938d-8189d6e0ad5d"
          },
          {
            "id": "40d3d26c-bf99-40c8-938d-8189d6e0ad5e"
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "ws",
        "security": "none",
        "wsSettings": {
          "path": "/b0c5"
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "tag": "block"
    }
  ],
  "transport": {},
  "stats": null,
  "reverse": {}
}
```
这样是可以正常访问外网的

**Comment by rprx** [comment]
路由那里 JSON 格式错误，请使用专业编辑器，比如 VS Code

这样可能可行：

```json
{
  "log": {
    "loglevel": "warning"
  },
  "api": {
    "tag": "api",
    "services": [
      "StatsService"
    ]
  },
  "dns": {},
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "block"
      },
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api"
      }
    ]
  },
  "policy": {
    "levels": {
      "0": {
        "statsUserUplink": true,
        "statsUserDownlink": true,
      }
    },
    "system": {
      "statsInboundUplink": true,
      "statsInboundDownlink": true,
      "statsOutboundUplink": true,
      "statsOutboundDownlink": true
    }
  },
  "inbounds": [
    {
      "port": 10000,
      "listen": "127.0.0.1",
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "email": "a",
            "id": "40d3d26c-bf99-40c8-938d-8189d6e0ad5d",
            "level": 0
          },
          {
            "email": "b",
            "id": "40d3d26c-bf99-40c8-938d-8189d6e0ad5e",
            "level": 0
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "ws",
        "security": "none",
        "wsSettings": {
          "path": "/b0c5"
        }
      }
    },
    {
      "listen": "127.0.0.1",
      "port": 10085,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "tag": "block"
    }
  ],
  "transport": {},
  "stats": {},
  "reverse": {}
}
```

**Comment by gcphym** [comment]
> 路由那里 JSON 格式错误，请使用专业编辑器，比如 VS Code
> 
> 这样可能可行：
> 
> ```json
> {
>   "log": {
>     "loglevel": "warning"
>   },
>   "api": {
>     "tag": "api",
>     "services": [
>       "StatsService"
>     ]
>   },
>   "dns": {},
>   "routing": {
>     "domainStrategy": "AsIs",
>     "rules": [
>       {
>         "type": "field",
>         "ip": [
>           "geoip:private"
>         ],
>         "outboundTag": "block"
>       },
>       {
>         "type": "field",
>         "inboundTag": [
>           "api"
>         ],
>         "outboundTag": "api"
>       }
>     ]
>   },
>   "policy": {
>     "levels": {
>       "0": {
>         "statsUserUplink": true,
>         "statsUserDownlink": true,
>       }
>     },
>     "system": {
>       "statsInboundUplink": true,
>       "statsInboundDownlink": true,
>       "statsOutboundUplink": true,
>       "statsOutboundDownlink": true
>     }
>   },
>   "inbounds": [
>     {
>       "port": 10000,
>       "listen": "127.0.0.1",
>       "protocol": "vless",
>       "settings": {
>         "clients": [
>           {
>             "email": "a",
>             "id": "40d3d26c-bf99-40c8-938d-8189d6e0ad5d",
>             "level": 0
>           },
>           {
>             "email": "b",
>             "id": "40d3d26c-bf99-40c8-938d-8189d6e0ad5e",
>             "level": 0
>           }
>         ],
>         "decryption": "none"
>       },
>       "streamSettings": {
>         "network": "ws",
>         "security": "none",
>         "wsSettings": {
>           "path": "/b0c5"
>         }
>       }
>     },
>     {
>       "listen": "127.0.0.1",
>       "port": 10085,
>       "protocol": "dokodemo-door",
>       "settings": {
>         "address": "127.0.0.1"
>       },
>       "tag": "api"
>     }
>   ],
>   "outbounds": [
>     {
>       "protocol": "freedom",
>       "tag": "direct"
>     },
>     {
>       "protocol": "blackhole",
>       "tag": "block"
>     }
>   ],
>   "transport": {},
>   "stats": {},
>   "reverse": {}
> }
> ```

你好 我在电脑上用的是notepad++,所以格式应该是没问题的，我刚刚复制了一下，还是不行，看了下错误还是这个```[Warning] [2943627196] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://mydomain/b0c5): 502 Bad Gateway > websocket: bad handshake] > common/retry: all retry attempts failed```

**Comment by rprx** [comment]
1. 你最初的配置 100% 存在格式问题
2. 看起来还是程序没运行，推测配置文件没换成功，**请关注服务端日志**

**Comment by rprx** [comment]
发现 JSON 格式错误不止一处，删掉了一个逗号，已测试可以运行：

```json
{
  "log": {
    "loglevel": "warning"
  },
  "api": {
    "tag": "api",
    "services": [
      "StatsService"
    ]
  },
  "dns": {},
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "block"
      },
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api"
      }
    ]
  },
  "policy": {
    "levels": {
      "0": {
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    },
    "system": {
      "statsInboundUplink": true,
      "statsInboundDownlink": true,
      "statsOutboundUplink": true,
      "statsOutboundDownlink": true
    }
  },
  "inbounds": [
    {
      "port": 10000,
      "listen": "127.0.0.1",
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "email": "a",
            "id": "40d3d26c-bf99-40c8-938d-8189d6e0ad5d",
            "level": 0
          },
          {
            "email": "b",
            "id": "40d3d26c-bf99-40c8-938d-8189d6e0ad5e",
            "level": 0
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "ws",
        "security": "none",
        "wsSettings": {
          "path": "/b0c5"
        }
      }
    },
    {
      "listen": "127.0.0.1",
      "port": 10085,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "tag": "block"
    }
  ],
  "transport": {},
  "stats": {},
  "reverse": {}
}
```

**Comment by gcphym** [comment]
> 1. 你最初的配置 100% 存在格式问题
> 2. 看起来还是程序没运行，推测配置文件没换成功，**请关注服务端日志**

确实可以了，谢谢。

服务端日志是/var/log/xray下面的两个文件吧，我之前看过，不知道为什么是空的...

**Comment by gcphym** [comment]
> 1. 你最初的配置 100% 存在格式问题
> 2. 看起来还是程序没运行，推测配置文件没换成功，**请关注服务端日志**

再请问一下 这个配置具体要用什么命令看流量统计呢 https://xtls.github.io/config/base/stats/ , 这里写的```user>>>[email]>>>traffic>>>downlink``` 看不太懂...我试了一下输入```xray api stats```，提示```failed to dial 127.0.0.1:8080```，是不是还要开一下8080端口

**Comment by rprx** [comment]
正好脚本有更新：https://github.com/XTLS/Xray-install

> Notice: Xray will NOT log to `/var/log/xray/*.log` by default. Configure `"log"` to specify log files.

`xray api stats -s 127.0.0.1:10085`，或者任意门端口改为 8080

**Comment by gcphym** [comment]
> > 1. 你最初的配置 100% 存在格式问题
> > 2. 看起来还是程序没运行，推测配置文件没换成功，**请关注服务端日志**
> @rprx 
> 再请问一下 这个配置具体要用什么命令看流量统计呢 https://xtls.github.io/config/base/stats/ , 这里写的`user>>>[email]>>>traffic>>>downlink` 看不太懂...我试了一下输入`xray api stats`，提示`failed to dial 127.0.0.1:8080`，是不是还要开一下8080端口

谢谢 搞定了
```xray api stats --server=127.0.0.1:10085 -name "user>>>a>>>traffic>>>downlink"```

**Comment by gcphym** [comment]
> 正好脚本有更新：https://github.com/XTLS/Xray-install
> 
> > Notice: Xray will NOT log to `/var/log/xray/*.log` by default. Configure `"log"` to specify log files.
> 
> `xray api stats -s 127.0.0.1:10085`，或者任意门端口改为 8080

请问统计信息如何清除或是重置呢，命令里没看到

**Comment by gcphym** [comment]
> > 正好脚本有更新：https://github.com/XTLS/Xray-install
> > > Notice: Xray will NOT log to `/var/log/xray/*.log` by default. Configure `"log"` to specify log files.
> > 
> > 
> > `xray api stats -s 127.0.0.1:10085`，或者任意门端口改为 8080
> 
> 请问统计信息如何清除或是重置呢，命令里没看到

```xray api stats --server=127.0.0.1:10085 -name "user>>>a>>>traffic>>>downlink" -reset``` 单位是字节 看的好费劲...

**Comment by whao** [comment]
> 发现 JSON 格式错误不止一处，删掉了一个逗号，已测试可以运行：
> 
> ```json
> {
>   "log": {
>     "loglevel": "warning"
>   },
>   "api": {
>     "tag": "api",
>     "services": [
>       "StatsService"
>     ]
>   },
>   "dns": {},
>   "routing": {
>     "domainStrategy": "AsIs",
>     "rules": [
>       {
>         "type": "field",
>         "ip": [
>           "geoip:private"
>         ],
>         "outboundTag": "block"
>       },
>       {
>         "type": "field",
>         "inboundTag": [
>           "api"
>         ],
>         "outboundTag": "api"
>       }
>     ]
>   },
>   "policy": {
>     "levels": {
>       "0": {
>         "statsUserUplink": true,
>         "statsUserDownlink": true
>       }
>     },
>     "system": {
>       "statsInboundUplink": true,
>       "statsInboundDownlink": true,
>       "statsOutboundUplink": true,
>       "statsOutboundDownlink": true
>     }
>   },
>   "inbounds": [
>     {
>       "port": 10000,
>       "listen": "127.0.0.1",
>       "protocol": "vless",
>       "settings": {
>         "clients": [
>           {
>             "email": "a",
>             "id": "40d3d26c-bf99-40c8-938d-8189d6e0ad5d",
>             "level": 0
>           },
>           {
>             "email": "b",
>             "id": "40d3d26c-bf99-40c8-938d-8189d6e0ad5e",
>             "level": 0
>           }
>         ],
>         "decryption": "none"
>       },
>       "streamSettings": {
>         "network": "ws",
>         "security": "none",
>         "wsSettings": {
>           "path": "/b0c5"
>         }
>       }
>     },
>     {
>       "listen": "127.0.0.1",
>       "port": 10085,
>       "protocol": "dokodemo-door",
>       "settings": {
>         "address": "127.0.0.1"
>       },
>       "tag": "api"
>     }
>   ],
>   "outbounds": [
>     {
>       "protocol": "freedom",
>       "tag": "direct"
>     },
>     {
>       "protocol": "blackhole",
>       "tag": "block"
>     }
>   ],
>   "transport": {},
>   "stats": {},
>   "reverse": {}
> }
> ```

我今天也遇到了相似的问题看了这个 https://github.com/XTLS/Xray-core/issues/687 issue 里面提到要把 api 的 routing 放在最前面就可以了，实测确实解决问题。但是看你的这个配置api的routing没有放在最前面也可以运行吗？如果放在后面的话 `xray api stats` 会报错 `failed to dial 127.0.0.1:10085`

**Comment by tlccc** [comment]
> 正好脚本有更新：https://github.com/XTLS/Xray-install
> 
> > Notice: Xray will NOT log to `/var/log/xray/*.log` by default. Configure `"log"` to specify log files.
> 
> `xray api stats -s 127.0.0.1:10085`，或者任意门端口改为 8080

输 `xray api stats` 报 `failed to dial 127.0.0.1:8080`，输 `xray api stats -s 127.0.0.1:10085` 报 `failed to get stats: rpc error: code = Unknown desc = app/stats/command:  not found.
` 大哥 这个怎么弄？
配置如下
```json
{
    "log": {
        "loglevel": "warning",
        "access": "/var/log/xray/access.log",
        "error": "/var/log/xray/error.log"
    },
    "api": {
        "tag": "api",
        "services": [
            "StatsService"
        ]
    },
    "routing": {
        "domainStrategy": "AsIs",
        "rules": [
            {
                "inboundTag": [
                    "api"
                ],
                "outboundTag": "api",
                "type": "field"
            },
            {
                "type": "field",
                "ip": [
                    "geoip:private"
                ],
                "outboundTag": "block"
            },
            {
                "type": "field",
                "domain": [
                    "geosite:category-ads-all"
                ],
                "outboundTag": "block"
            }
        ]
    },
    "policy": {
        "levels": {
            "0": {
                "statsUserUplink": true,
                "statsUserDownlink": true
            }
        },
        "system": {
            "statsInboundUplink": true,
            "statsInboundDownlink": true,
            "statsOutboundUplink": true,
            "statsOutboundDownlink": true
        }
    },
    "inbounds": [
        {
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "1043336b-7741-4ea6-9512-a264d9e40d9d",
                        "flow": "xtls-rprx-direct",
                        "level": 0,
                        "email": "love"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": 1310,
                        "xver": 1
                    },
                    {
                        "path": "/websocket",
                        "dest": 1234,
                        "xver": 1
                    },
                    {
                        "path": "/vmesstcp",
                        "dest": 2345,
                        "xver": 1
                    },
                    {
                        "path": "/vmessws",
                        "dest": 3456,
                        "xver": 1
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "alpn": [
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "/home/vpsadmin/xray_cert/xray.crt",
                            "keyFile": "/home/vpsadmin/xray_cert/xray.key"
                        }
                    ]
                }
            }
        },
        {
            "port": 1310,
            "listen": "127.0.0.1",
            "protocol": "trojan",
            "settings": {
                "clients": [
                    {
                        "password": "12345678",
                        "level": 0,
                        "email": "trojan"
                    }
                ],
                "fallbacks": [
                    {
                        "dest": 80
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "none",
                "tcpSettings": {
                    "acceptProxyProtocol": true
                }
            }
        },
        {
            "port": 1234,
            "listen": "127.0.0.1",
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "c43f7576-ef46-4496-b830-fa74daa3207e",
                        "level": 0,
                        "email": "vlws"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "ws",
                "security": "none",
                "wsSettings": {
                    "acceptProxyProtocol": true,
                    "path": "/websocket"
                }
            }
        },
        {
            "port": 2345,
            "listen": "127.0.0.1",
            "protocol": "vmess",
            "settings": {
                "clients": [
                    {
                        "id": "b85e117a-0b16-448f-9159-919d7b30963d",
                        "level": 0,
                        "email": "vmtcp"
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "none",
                "tcpSettings": {
                    "acceptProxyProtocol": true,
                    "header": {
                        "type": "http",
                        "request": {
                            "path": [
                                "/vmesstcp"
                            ]
                        }
                    }
                }
            }
        },
        {
            "port": 3456,
            "listen": "127.0.0.1",
            "protocol": "vmess",
            "settings": {
                "clients": [
                    {
                        "id": "e70a2383-9c1b-45b7-b591-c66885e61841",
                        "level": 0,
                        "email": "vmws"
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "security": "none",
                "wsSettings": {
                    "acceptProxyProtocol": true,
                    "path": "/vmessws"
                }
            }
        },
        {
            "listen": "127.0.0.1",
            "port": 10085,
            "protocol": "dokodemo-door",
            "settings": {
                "address": "127.0.0.1"
            },
            "tag": "api"
        }
    ],
    "outbounds": [
        {
            "tag": "direct",
            "protocol": "freedom"
        },
        {
            "tag": "block",
            "protocol": "blackhole"
        }
    ],
    "stats": {}
}
```

**Comment by tufu9441** [comment]
> > 正好脚本有更新：https://github.com/XTLS/Xray-install
> > > Notice: Xray will NOT log to `/var/log/xray/*.log` by default. Configure `"log"` to specify log files.
> > 
> > 
> > `xray api stats -s 127.0.0.1:10085`，或者任意门端口改为 8080
> 
> 输 `xray api stats` 报 `failed to dial 127.0.0.1:8080`，输 `xray api stats -s 127.0.0.1:10085` 报 `failed to get stats: rpc error: code = Unknown desc = app/stats/command: not found. ` 大哥 这个怎么弄？ 配置如下
> 
> ```json
> {
>     "log": {
>         "loglevel": "warning",
>         "access": "/var/log/xray/access.log",
>         "error": "/var/log/xray/error.log"
>     },
>     "api": {
>         "tag": "api",
>         "services": [
>             "StatsService"
>         ]
>     },
>     "routing": {
>         "domainStrategy": "AsIs",
>         "rules": [
>             {
>                 "inboundTag": [
>                     "api"
>                 ],
>                 "outboundTag": "api",
>                 "type": "field"
>             },
>             {
>                 "type": "field",
>                 "ip": [
>                     "geoip:private"
>                 ],
>                 "outboundTag": "block"
>             },
>             {
>                 "type": "field",
>                 "domain": [
>                     "geosite:category-ads-all"
>                 ],
>                 "outboundTag": "block"
>             }
>         ]
>     },
>     "policy": {
>         "levels": {
>             "0": {
>                 "statsUserUplink": true,
>                 "statsUserDownlink": true
>             }
>         },
>         "system": {
>             "statsInboundUplink": true,
>             "statsInboundDownlink": true,
>             "statsOutboundUplink": true,
>             "statsOutboundDownlink": true
>         }
>     },
>     "inbounds": [
>         {
>             "port": 443,
>             "protocol": "vless",
>             "settings": {
>                 "clients": [
>                     {
>                         "id": "1043336b-7741-4ea6-9512-a264d9e40d9d",
>                         "flow": "xtls-rprx-direct",
>                         "level": 0,
>                         "email": "love"
>                     }
>                 ],
>                 "decryption": "none",
>                 "fallbacks": [
>                     {
>                         "dest": 1310,
>                         "xver": 1
>                     },
>                     {
>                         "path": "/websocket",
>                         "dest": 1234,
>                         "xver": 1
>                     },
>                     {
>                         "path": "/vmesstcp",
>                         "dest": 2345,
>                         "xver": 1
>                     },
>                     {
>                         "path": "/vmessws",
>                         "dest": 3456,
>                         "xver": 1
>                     }
>                 ]
>             },
>             "streamSettings": {
>                 "network": "tcp",
>                 "security": "xtls",
>                 "xtlsSettings": {
>                     "alpn": [
>                         "http/1.1"
>                     ],
>                     "certificates": [
>                         {
>                             "certificateFile": "/home/vpsadmin/xray_cert/xray.crt",
>                             "keyFile": "/home/vpsadmin/xray_cert/xray.key"
>                         }
>                     ]
>                 }
>             }
>         },
>         {
>             "port": 1310,
>             "listen": "127.0.0.1",
>             "protocol": "trojan",
>             "settings": {
>                 "clients": [
>                     {
>                         "password": "12345678",
>                         "level": 0,
>                         "email": "trojan"
>                     }
>                 ],
>                 "fallbacks": [
>                     {
>                         "dest": 80
>                     }
>                 ]
>             },
>             "streamSettings": {
>                 "network": "tcp",
>                 "security": "none",
>                 "tcpSettings": {
>                     "acceptProxyProtocol": true
>                 }
>             }
>         },
>         {
>             "port": 1234,
>             "listen": "127.0.0.1",
>             "protocol": "vless",
>             "settings": {
>                 "clients": [
>                     {
>                         "id": "c43f7576-ef46-4496-b830-fa74daa3207e",
>                         "level": 0,
>                         "email": "vlws"
>                     }
>                 ],
>                 "decryption": "none"
>             },
>             "streamSettings": {
>                 "network": "ws",
>                 "security": "none",
>                 "wsSettings": {
>                     "acceptProxyProtocol": true,
>                     "path": "/websocket"
>                 }
>             }
>         },
>         {
>             "port": 2345,
>             "listen": "127.0.0.1",
>             "protocol": "vmess",
>             "settings": {
>                 "clients": [
>                     {
>                         "id": "b85e117a-0b16-448f-9159-919d7b30963d",
>                         "level": 0,
>                         "email": "vmtcp"
>                     }
>                 ]
>             },
>             "streamSettings": {
>                 "network": "tcp",
>                 "security": "none",
>                 "tcpSettings": {
>                     "acceptProxyProtocol": true,
>                     "header": {
>                         "type": "http",
>                         "request": {
>                             "path": [
>                                 "/vmesstcp"
>                             ]
>                         }
>                     }
>                 }
>             }
>         },
>         {
>             "port": 3456,
>             "listen": "127.0.0.1",
>             "protocol": "vmess",
>             "settings": {
>                 "clients": [
>                     {
>                         "id": "e70a2383-9c1b-45b7-b591-c66885e61841",
>                         "level": 0,
>                         "email": "vmws"
>                     }
>                 ]
>             },
>             "streamSettings": {
>                 "network": "ws",
>                 "security": "none",
>                 "wsSettings": {
>                     "acceptProxyProtocol": true,
>                     "path": "/vmessws"
>                 }
>             }
>         },
>         {
>             "listen": "127.0.0.1",
>             "port": 10085,
>             "protocol": "dokodemo-door",
>             "settings": {
>                 "address": "127.0.0.1"
>             },
>             "tag": "api"
>         }
>     ],
>     "outbounds": [
>         {
>             "tag": "direct",
>             "protocol": "freedom"
>         },
>         {
>             "tag": "block",
>             "protocol": "blackhole"
>         }
>     ],
>     "stats": {}
> }
> ```

我跟你的报错一模一样，同求解决方法~

**Comment by tlccc** [comment]
> > > 正好脚本有更新：https://github.com/XTLS/Xray-install
> > > > Notice: Xray will NOT log to `/var/log/xray/*.log` by default. Configure `"log"` to specify log files.
> > > 
> > > 
> > > `xray api stats -s 127.0.0.1:10085`，或者任意门端口改为 8080
> > 
> > 
> > 输 `xray api stats` 报 `failed to dial 127.0.0.1:8080`，输 `xray api stats -s 127.0.0.1:10085` 报 `failed to get stats: rpc error: code = Unknown desc = app/stats/command: not found. ` 大哥 这个怎么弄？ 配置如下
> > ```json
> > {
> >     "log": {
> >         "loglevel": "warning",
> >         "access": "/var/log/xray/access.log",
> >         "error": "/var/log/xray/error.log"
> >     },
> >     "api": {
> >         "tag": "api",
> >         "services": [
> >             "StatsService"
> >         ]
> >     },
> >     "routing": {
> >         "domainStrategy": "AsIs",
> >         "rules": [
> >             {
> >                 "inboundTag": [
> >                     "api"
> >                 ],
> >                 "outboundTag": "api",
> >                 "type": "field"
> >             },
> >             {
> >                 "type": "field",
> >                 "ip": [
> >                     "geoip:private"
> >                 ],
> >                 "outboundTag": "block"
> >             },
> >             {
> >                 "type": "field",
> >                 "domain": [
> >                     "geosite:category-ads-all"
> >                 ],
> >                 "outboundTag": "block"
> >             }
> >         ]
> >     },
> >     "policy": {
> >         "levels": {
> >             "0": {
> >                 "statsUserUplink": true,
> >                 "statsUserDownlink": true
> >             }
> >         },
> >         "system": {
> >             "statsInboundUplink": true,
> >             "statsInboundDownlink": true,
> >             "statsOutboundUplink": true,
> >             "statsOutboundDownlink": true
> >         }
> >     },
> >     "inbounds": [
> >         {
> >             "port": 443,
> >             "protocol": "vless",
> >             "settings": {
> >                 "clients": [
> >                     {
> >                         "id": "1043336b-7741-4ea6-9512-a264d9e40d9d",
> >                         "flow": "xtls-rprx-direct",
> >                         "level": 0,
> >                         "email": "love"
> >                     }
> >                 ],
> >                 "decryption": "none",
> >                 "fallbacks": [
> >                     {
> >                         "dest": 1310,
> >                         "xver": 1
> >                     },
> >                     {
> >                         "path": "/websocket",
> >                         "dest": 1234,
> >                         "xver": 1
> >                     },
> >                     {
> >                         "path": "/vmesstcp",
> >                         "dest": 2345,
> >                         "xver": 1
> >                     },
> >                     {
> >                         "path": "/vmessws",
> >                         "dest": 3456,
> >                         "xver": 1
> >                     }
> >                 ]
> >             },
> >             "streamSettings": {
> >                 "network": "tcp",
> >                 "security": "xtls",
> >                 "xtlsSettings": {
> >                     "alpn": [
> >                         "http/1.1"
> >                     ],
> >                     "certificates": [
> >                         {
> >                             "certificateFile": "/home/vpsadmin/xray_cert/xray.crt",
> >                             "keyFile": "/home/vpsadmin/xray_cert/xray.key"
> >                         }
> >                     ]
> >                 }
> >             }
> >         },
> >         {
> >             "port": 1310,
> >             "listen": "127.0.0.1",
> >             "protocol": "trojan",
> >             "settings": {
> >                 "clients": [
> >                     {
> >                         "password": "12345678",
> >                         "level": 0,
> >                         "email": "trojan"
> >                     }
> >                 ],
> >                 "fallbacks": [
> >                     {
> >                         "dest": 80
> >                     }
> >                 ]
> >             },
> >             "streamSettings": {
> >                 "network": "tcp",
> >                 "security": "none",
> >                 "tcpSettings": {
> >                     "acceptProxyProtocol": true
> >                 }
> >             }
> >         },
> >         {
> >             "port": 1234,
> >             "listen": "127.0.0.1",
> >             "protocol": "vless",
> >             "settings": {
> >                 "clients": [
> >                     {
> >                         "id": "c43f7576-ef46-4496-b830-fa74daa3207e",
> >                         "level": 0,
> >                         "email": "vlws"
> >                     }
> >                 ],
> >                 "decryption": "none"
> >             },
> >             "streamSettings": {
> >                 "network": "ws",
> >                 "security": "none",
> >                 "wsSettings": {
> >                     "acceptProxyProtocol": true,
> >                     "path": "/websocket"
> >                 }
> >             }
> >         },
> >         {
> >             "port": 2345,
> >             "listen": "127.0.0.1",
> >             "protocol": "vmess",
> >             "settings": {
> >                 "clients": [
> >                     {
> >                         "id": "b85e117a-0b16-448f-9159-919d7b30963d",
> >                         "level": 0,
> >                         "email": "vmtcp"
> >                     }
> >                 ]
> >             },
> >             "streamSettings": {
> >                 "network": "tcp",
> >                 "security": "none",
> >                 "tcpSettings": {
> >                     "acceptProxyProtocol": true,
> >                     "header": {
> >                         "type": "http",
> >                         "request": {
> >                             "path": [
> >                                 "/vmesstcp"
> >                             ]
> >                         }
> >                     }
> >                 }
> >             }
> >         },
> >         {
> >             "port": 3456,
> >             "listen": "127.0.0.1",
> >             "protocol": "vmess",
> >             "settings": {
> >                 "clients": [
> >                     {
> >                         "id": "e70a2383-9c1b-45b7-b591-c66885e61841",
> >                         "level": 0,
> >                         "email": "vmws"
> >                     }
> >                 ]
> >             },
> >             "streamSettings": {
> >                 "network": "ws",
> >                 "security": "none",
> >                 "wsSettings": {
> >                     "acceptProxyProtocol": true,
> >                     "path": "/vmessws"
> >                 }
> >             }
> >         },
> >         {
> >             "listen": "127.0.0.1",
> >             "port": 10085,
> >             "protocol": "dokodemo-door",
> >             "settings": {
> >                 "address": "127.0.0.1"
> >             },
> >             "tag": "api"
> >         }
> >     ],
> >     "outbounds": [
> >         {
> >             "tag": "direct",
> >             "protocol": "freedom"
> >         },
> >         {
> >             "tag": "block",
> >             "protocol": "blackhole"
> >         }
> >     ],
> >     "stats": {}
> > }
> > ```
> 
> 我跟你的报错一模一样，同求解决方法~

一直没弄明白，老哥 你要是解决了可否告知一声  感谢

**Comment by toyo2333** [comment]
有人知道如果是docker 运行的 该怎么写呢？
