### ISSUE TITLE
无敌一键 xRay/Sing-Box/Nginx 批量管理脚本

### ISSUE THREAD

**Issue by Aeakaw** [XTLS/Xray-core#2977]
https://github.com/cfwss/conf/tree/main

包含协议：
    xRay
    vless-tcp-xtls/vless-tcp/vless-ws/vless-grpc/vmess-tcp/vmess-ws/vmess-grpc/shadowsocks-tcp/shadowsocks-ws/shadowsocks-grpc/trojan-tcp/trojan-ws/trojan-grpc
    Sing-Box
    vless-ws/vmess-ws/trojan-ws/shadowsocks-tcp/tuic-tcp/naive-tcp/hysteria2-tcp

**Comment by Aeakaw** [comment]
![Uploading main_menu.jpg…]()

**Comment by Aeakaw** [comment]
![main_menu](https://github.com/XTLS/Xray-core/assets/15069203/ebb68abc-9981-42ab-846b-3454be12ba77)

**Comment by chise0713** [comment]
不说打广告，你这大小写全错完了

**Comment by stqfdyr** [comment]
请翻译一下什么是 issue
