### ISSUE TITLE
Add Fragment option to vless config 

### ISSUE THREAD

**Issue by 090ebier** [XTLS/Xray-core#2978]
Hello guys from the xray team, since manipulating the config and converting it to json is annoying for many beginners, I ask you to add the fragment feature to the vless address itself, so that its entries can be added through the relevant panels such as x-ui.

**Comment by Fangliding** [comment]
Fragment is not vless feature, so it will definitely not be added to the vless protocol setting. Placing it in TLSObject may be acceptable, wait for a PR :)

**Comment by 090ebier** [comment]
Well, this feature can be in the vless address, but to activate it, use a default configuration in the client that is included in the updates, in such a way that the parameters inside the vless address, such as "tag": "fragment",
       "protocol": "freedom",
       "settings": {
         "fragment": {
           "packets": "tlshell",
           "length": "10-20",
           "interval": "10-20" replace the default parameters of its own json file

**Comment by chise0713** [comment]
https://github.com/XTLS/Xray-core/issues/2897#issuecomment-1878758112

**Comment by yuhan6665** [comment]
Answered
