### ISSUE TITLE
32位程序无法在windows server2003上运行！

### ISSUE THREAD

**Issue by simonchan6688** [XTLS/Xray-core#298]
32位程序无法在windows server2003上运行！
![image](https://user-images.githubusercontent.com/34909952/108968304-94107300-76bb-11eb-91b1-57e983dd36e6.png)

**Comment by JimhHan** [comment]
> Go 1.10 is the last release that will run on Windows XP or Windows Vista. Go 1.11 will require Windows 7 or later.
