### ISSUE TITLE
错误日志出现大量context canceled错误

### ISSUE THREAD

**Issue by harvey-git** [XTLS/Xray-core#2981]
error.log里面类似这样的
`failed to retrieve response for connectivity-check.ubuntu.com. > Post "https://1.1.1.1/dns-query": context canceled
failed to retrieve response for discovery-v4.syncthing.net. > Post "https://1.1.1.1/dns-query": context deadline exceeded
failed to retrieve response for www.blogger.com. > Post "https://1.1.1.1/dns-query": context canceled
`
错误日志一直在增加这种格式错误记录 failed to retrieve response for  后面的域名可能多种多样，上面的三种是最常见的。
其实不影响正常使用，但是轻微强迫症患者看到这些，有点难受，也怀疑出现这类日志错误会不会有有某种隐藏的问题。
ps:最新的1.8.7的内存占用控制得很好，在之前版本随机出现的内存泄漏问题没有再观察到了！

**Comment by yuhan6665** [comment]
日志问题可以不管
