### ISSUE TITLE
hysteria protocol

### ISSUE THREAD

**Issue by itsDantes** [XTLS/Xray-core#2982]
please add hysteria2 protocol, its fast and stable. also sing-box app support it but v2rayng still miss this protocol

**Comment by itsDantes** [comment]
@ll11l1lIllIl1lll its all chinese bro. i don't know why your team not add this protocol.

**Comment by stqfdyr** [comment]
> @ll11l1lIllIl1lll its all chinese bro. i cant read chinese. i don't know why your team not add this protocol.

all in all，xray team is no plan for this yet
You're welcome to ask questions, but don't be throwing around orders.

**Comment by us254** [comment]
https://github.com/XTLS/Xray-core/issues/2635

The user is asking if Xray will support "Hysteria 2," which seems to be a reference to a network protocol or software that is designed to improve proxy availability in weak network environments by using aggressive packet sending strategies. The user expresses a desire to have both "reality" for normal network conditions and "Hysteria 2" for night time use, all within Xray, to avoid running multiple Docker containers or services.

The developer, RPRX, responds by explaining that there are no current plans to support Hysteria in Xray. The reasons provided are:

1. The aggressive packet sending strategy of Hysteria is essentially a way to compete for network resources, which can degrade the experience for others. If everyone were to use it, it would lead to a worse overall situation.
2. Hysteria and similar protocols are not designed to circumvent censorship like the Great Firewall of China (GFW), and there is no historical data on how the GFW might specifically block these protocols.
3. There is a concern that if such protocols became mainstream, the GFW would study their differences from standard QUIC and eventually everyone would have to revert to using standard QUIC.

RPRX suggests that it is better to observe the situation, especially considering the first point, which is likened to an arms race of sorts where everyone ends up in a meaningless competition, and if the protocols become mainstream, they will likely be scrutinized and potentially blocked by the GFW.

Another contributor, tobyxdd, adds that whether Hysteria's packet sending is considered "aggressive" is subjective, and emphasizes that using the bandwidth promised by ISPs without breaking speed limits is reasonable. They also mention that congestion control varies across different systems and configurations, and that many types of internet traffic do not use congestion control at all, such as online gaming.

Tobyxdd clarifies that Hysteria is careful not to modify the core QUIC protocol layer, as it also serves as a regular HTTP/3 server handling browser requests. They note that while there are subtle differences between various QUIC implementations, Hysteria aims to behave consistently with other HTTP/3 web servers that use the quic-go library. They also express a reluctance to preemptively make changes that could potentially create new distinguishing features that might be targeted by the GFW.

The developer's response indicates a cautious approach to protocol support, prioritizing the stability and reliability of the existing system over the adoption of new and potentially risky features.

**Comment by Fangliding** [comment]
One day, maybe, or maybe not（）
