### ISSUE TITLE
problem with cloudflare proxied dns zone

### ISSUE THREAD

**Issue by Mr-persian** [XTLS/Xray-core#2992]
`proxy/http:` failed to read response from 149.154.167.41:80 > malformed HTTP response "\x12\x04\x00\x00\x00\x00\x00

2024/02/04 09:59:00 127.0.0.1:14959 accepted //149.154.175.100:443 [http -> proxy]
2024/02/04 09:59:00 127.0.0.1:14961 accepted http://149.154.175.100:80/api [http -> proxy]
2024/02/04 09:59:00 [Warning] [3212607727] proxy/http: failed to read response from 149.154.175.100:80 > malformed HTTP response "\x12\x04\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00d\x00\x04\x00\x01\x00\x00\x00\x05\x00\xff\xff\xff\x00\x00\x04\b\x00\x00\x00\x00\x00\x7f\xff\x00\x00\x00\x00\b\a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01"'

i try everything i found on internet but it dosent worked.pls help #

**Comment by yuhan6665** [comment]
post your config
