### ISSUE TITLE
如何添加多个节点到xray服务器

### ISSUE THREAD

**Issue by Birddle** [XTLS/Xray-core#2995]
### Discussed in https://github.com/XTLS/Xray-core/discussions/2994

<div type='discussions-op-text'>

<sup>Originally posted by **Birddle** February  5, 2024</sup>
我已经实现了一个xray服务器。但是我想要用另一台其他地区的服务器作为备用节点。
我知道我可以再用其他的子域名搭建第二台服务器来实现。但是。。。有另一个方法吗？一个子域名使用两个服务器，然后在客户端能够自主切换。</div>

**Comment by yuhan6665** [comment]
Answered https://github.com/XTLS/Xray-core/discussions/2994
