### ISSUE TITLE
Bug in Xray | Shadowsocks

### ISSUE THREAD

**Issue by ahmadipiralvan** [XTLS/Xray-core#2996]
### Description
Hi dears,
I noticed the xray core stops and restarts from time to time.
This problem is annoying and may happen many times during the day.
We need to find the problem.

I understand that this is a problem with the Shadowsocks protocol.

I have a inbound with the following specifications:
**Shadowsocks | aes-256-gcm | TCP+UDP | Sniffing ON**

### Version
xray: 1.8.7

### Xray Log Report:
```
Feb 05 17:05:19 localhost systemd[1]: x-ui.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 05 17:05:19 localhost systemd[1]: x-ui.service: Killing process 14281 (xray-linux-amd6) with signal SIGKILL.
Feb 05 17:05:19 localhost systemd[1]: x-ui.service: Failed with result 'exit-code'.
Feb 05 17:05:19 localhost systemd[1]: x-ui.service: Consumed 49min 34.643s CPU time.
```

Also, maybe this problem is related to the problem raised in the shadowsocks repository:
https://github.com/shadowsocks/shadowsocks-libev/issues/2402

**Comment by yuhan6665** [comment]
Kill by system is not a xray issue. Though we acknowledge there is memory leak to be fixed
