### ISSUE TITLE
v2ray-core中为什么移除xtls

### ISSUE THREAD

**Issue by usgate** [XTLS/Xray-core#3]
挺好用的功能，是因为什么？

**Comment by guanhemeng** [comment]
原因很复杂，LICENSE只是个导火索（直接原因）
rprxx将会发布完整的来龙去脉（需要时间整理）
过程并不愉快

**Comment by rprx** [comment]
目前的重心是建设 Project X，有空（或有必要时）再深究这件事。

**Comment by LsnmxNB** [comment]
@rprx 大佬莫生气，冷静下来

**Comment by vivodi** [comment]
### v2ray、v2fly和xray的前世今生
### 起源
最初的项目名叫 [v2ray](https://github.com/v2ray/v2ray-core) 。

### 更名
2019 年，v2ray 的原作者在网络上突然消失，由于开发组的其他人没有完整的仓库权限，项目更名 [v2fly](https://github.com/v2fly/v2ray-core) 后继续进行开发。

### 决裂
2020 年，[RPRX](https://github.com/RPRX) 开发了 [XTLS协议](https://github.com/XTLS/Go) 。他将 XTLS 协议的代码公开，但许可证是[专有代码](https://zh.wikipedia.org/wiki/%E4%B8%93%E6%9C%89%E8%BD%AF%E4%BB%B6)，因这部分代码不符合 Debian 包的打包规则（Debian包只允许打包符合 [OSI](https://opensource.org/) 要求的代码），v2ray 的 Debian 包维护者请求 RPRX 将他开发的相关代码使用开源许可证，但 RPRX 不同意此更改，相关讨论参见 https://github.com/XTLS/Go/issues/9 。此后 Debian 包维护者在 https://github.com/v2ray/v2ray-core/issues/2789 提议 v2fly 移除 XTLS 协议以便他能继续为此项目提供 Debian 包，后经 [Project X讨论群](https://t.me/projectXray) 投票决定放弃 Debian 包或移除 XTLS 协议，最终选择移除 XTLS 协议。

v2fly 移除 XTLS 协议后，RPRX 分叉 v2fly-core 项目，建立了包含 XTLS 协议的 [Xray-core](https://github.com/XTLS/Xray-core) 项目。不同于 v2fly 使用的 [MIT](https://github.com/v2fly/v2ray-core#MIT-1-ov-file) 许可证，Xray-core 使用 [MPL 2.0](https://github.com/XTLS/Xray-core?tab=MPL-2.0-1-ov-file#readme) 许可证。

### 结束语
RPRX 因一己私利而促使项目分家的行为对开源社区造成了深深的伤害，他应该被永远钉在开源社区的耻辱柱上。

**Comment by Fangliding** [comment]
@vivodi ?

**Comment by httpservlet** [comment]
> ### v2ray、v2fly和xray的前世今生
> ### 起源
> 最初的项目名叫 [v2ray](https://github.com/v2ray/v2ray-core) 。
> 
> ### 更名
> 2019 年，v2ray 的原作者在网络上突然消失，由于开发组的其他人没有完整的仓库权限，项目更名 [v2fly](https://github.com/v2fly/v2ray-core) 后继续进行开发。
> 
> ### 决裂
> 2020 年，[RPRX](https://github.com/RPRX) 开发了 [XTLS协议](https://github.com/XTLS/Go) 。他将 XTLS 协议的代码公开，但许可证是[专有代码](https://zh.wikipedia.org/wiki/%E4%B8%93%E6%9C%89%E8%BD%AF%E4%BB%B6)，因这部分代码不符合 Debian 包的打包规则（Debian包只允许打包符合 [OSI](https://opensource.org/) 要求的代码），v2ray 的 Debian 包维护者请求 RPRX 将他开发的相关代码使用开源许可证，但 RPRX 不同意此更改，相关讨论参见 [XTLS/Go#9](https://github.com/XTLS/Go/issues/9) 。此后 Debian 包维护者在 [v2ray/v2ray-core#2789](https://github.com/v2ray/v2ray-core/issues/2789) 提议 v2fly 移除 XTLS 协议以便他能继续为此项目提供 Debian 包，后经 [Project X讨论群](https://t.me/projectXray) 投票决定放弃 Debian 包或移除 XTLS 协议，最终选择移除 XTLS 协议。
> 
> v2fly 移除 XTLS 协议后，RPRX 分叉 v2fly-core 项目，建立了包含 XTLS 协议的 [Xray-core](https://github.com/XTLS/Xray-core) 项目。不同于 v2fly 使用的 [MIT](https://github.com/v2fly/v2ray-core#MIT-1-ov-file) 许可证，Xray-core 使用 [MPL 2.0](https://github.com/XTLS/Xray-core?tab=MPL-2.0-1-ov-file#readme) 许可证。
> 
> ### 结束语
> RPRX 因一己私利而促使项目分家的行为对开源社区造成了深深的伤害，他应该被永远钉在开源社区的耻辱柱上。

屁话真多, 作者愿意什么开源协议就用什么开源协议? 我要你妈献给我, 你不愿意, 那你就是"因一己私利而对我造成了深深的伤害，你应该被永远钉在社会和谐的耻辱柱上。"

**Comment by X-ether** [comment]
> ### v2ray、v2fly和xray的前世今生
> ### 起源
> 最初的项目名叫 [v2ray](https://github.com/v2ray/v2ray-core) 。
> 
> ### 更名
> 2019 年，v2ray 的原作者在网络上突然消失，由于开发组的其他人没有完整的仓库权限，项目更名 [v2fly](https://github.com/v2fly/v2ray-core) 后继续进行开发。
> 
> ### 决裂
> 2020 年，[RPRX](https://github.com/RPRX) 开发了 [XTLS协议](https://github.com/XTLS/Go) 。他将 XTLS 协议的代码公开，但许可证是[专有代码](https://zh.wikipedia.org/wiki/%E4%B8%93%E6%9C%89%E8%BD%AF%E4%BB%B6)，因这部分代码不符合 Debian 包的打包规则（Debian包只允许打包符合 [OSI](https://opensource.org/) 要求的代码），v2ray 的 Debian 包维护者请求 RPRX 将他开发的相关代码使用开源许可证，但 RPRX 不同意此更改，相关讨论参见 [XTLS/Go#9](https://github.com/XTLS/Go/issues/9) 。此后 Debian 包维护者在 [v2ray/v2ray-core#2789](https://github.com/v2ray/v2ray-core/issues/2789) 提议 v2fly 移除 XTLS 协议以便他能继续为此项目提供 Debian 包，后经 [Project X讨论群](https://t.me/projectXray) 投票决定放弃 Debian 包或移除 XTLS 协议，最终选择移除 XTLS 协议。
> 
> v2fly 移除 XTLS 协议后，RPRX 分叉 v2fly-core 项目，建立了包含 XTLS 协议的 [Xray-core](https://github.com/XTLS/Xray-core) 项目。不同于 v2fly 使用的 [MIT](https://github.com/v2fly/v2ray-core#MIT-1-ov-file) 许可证，Xray-core 使用 [MPL 2.0](https://github.com/XTLS/Xray-core?tab=MPL-2.0-1-ov-file#readme) 许可证。
> 
> ### 结束语
> RPRX 因一己私利而促使项目分家的行为对开源社区造成了深深的伤害，他应该被永远钉在开源社区的耻辱柱上。

不是，这位同志我也是真的搞不懂…

要是觉得Xray不好就不要逛这个讨论区，不要用这个项目…开源协议是什么样是作者自由！
我看您似乎也没有这方面的项目啊…
这位同志要是有点本事应该自己分叉一个sb2ray用MIT协议开源，而不是在这里喷RPRX大佬！

**Comment by Fangliding** [comment]
@X-ether 不是哥们 issues区是讨论技术问题的地方 不是贴吧论坛 一些你自己的想法没有实际用处就不用发了 更别说还挖坟

**Comment by X-ether** [comment]
> @X-ether 不是哥们 issues区是讨论技术问题的地方 不是贴吧论坛 一些你自己的想法没有实际用处就不用发了 更别说还挖坟

抱歉大佬我错了，您删除吧…
抱歉给您造成困扰…我错了，抱歉…
