### ISSUE TITLE
请问如何指定配置文件路径以及验证配置文件的正确性

### ISSUE THREAD

**Issue by slinar** [XTLS/Xray-core#30]
如题，我通过help查看了相关信息。并没有找到这样的选项

**Comment by rprx** [comment]
兼容 v2ray 现在的用法（即无指令），指令还在调整中。

**Comment by badO1a5A90** [comment]
> 如题，我通过help查看了相关信息。并没有找到这样的选项

try 
xray run -c /usr/local/etc/xray/config.json
xray run -test -c /usr/local/etc/xray/config.json

**Comment by slinar** [comment]
谢谢！

**Comment by rprx** [comment]
> xray run -test -c /usr/local/etc/xray/config.json

其实可能很会取消这个用法，变成 `xray test`，所以目前 test 不推荐这样用，推荐直接 -test

**Comment by rprx** [comment]
> xray run -test -c /usr/local/etc/xray/config.json

其实可能很会取消这个用法，变成 `xray test -c`，所以目前 test 不推荐通过 run 用，建议直接 `xray -test -c`

**Comment by badO1a5A90** [comment]
确实 xray test -c 比较好
