### ISSUE TITLE
Speed Test On The Same Server Shows VMESS > VLESS > TROJIAN

### ISSUE THREAD

**Issue by changyp6** [XTLS/Xray-core#301]
I just did a test on my server with 3 different protocols.
The result is very interesting.
When using VMESS, ping speed and download speed are the fastest
When using VLESS, download speed is about 70% of VMESS
When using TROJAIN, download speed is about 60% of VMESS

This test result is very interesting, I remembered that the first time I test different protocols, VLESS was faster than VMESS.
My router has CRYPTO hardware instruction set, I suspect that VMESS uses AEAD has better performance in this situation?

XRAY author please help investigate on this issue.

**Comment by rprx** [comment]
如果你用的是 TLS 而不是 XTLS，又因为 Xray 给裸协议开了全平台 ReadV，目前得到这个结果是合理的。

**Comment by changyp6** [comment]
> 如果你用的是 TLS 而不是 XTLS，又因为 Xray 给裸协议开了全平台 ReadV，目前得到这个结果是合理的。

I see.
Thanks for the answer.

**Comment by rprx** [comment]
https://github.com/badO1a5A90/Performance/blob/main/performance_test/Xray/speed_test_20201202.md

这里的图已经很清楚了（这个测试都有 ReadV），Xray-core 本就比 v2fly-core 快很多，这是固有差距。

固有差距，再加上 v2fly-core 其实没有全平台 ReadV，硬路由上 v2fly-core 的 VMess 比 Xray-core 的慢很多，欢迎测试、反馈数据。
