### ISSUE TITLE
reality+grpc在没有真实连接的时候，被连上443端口并且会跑流量

### ISSUE THREAD

**Issue by stupidloud** [XTLS/Xray-core#3010]
配置如下，一些值用了替代。
我这个配置运行在azure的vps一星期跑出了几十美元的流量费，观察iftop 有一些陌生ip，有国内chinnet也有CF，连上了443端口，每连接以1.3-3mbps的速率流出数据

{
    "log": {
        "loglevel": "warning"
    },
    "inbounds": [
        {
            "listen": "0.0.0.0",
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "xxx-xxx-xxx-xxx-xxx",
                        "flow": "" // 留空
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "grpc",
                "security": "reality",
                "realitySettings": {
                    "show": true,
                    "dest": "someweb.com:443", 
                    "xver": 0,
                    "serverNames": [ 
                        "someweb.com" 
                    ],
                    "privateKey": "prikey_replacement", 
                    "shortIds": [ 
                        "" 
                    ]
                },
                "grpcSettings": {
                    "serviceName": "titlab" 
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ],
    "policy": {
        "levels": {
            "0": {
                "handshake": 2,
                "connIdle": 120
            }
        }
    }
}

**Comment by chika0801** [comment]
猜测你dest用有域名网站套了cf，被人扫了拿你机当中转用？

**Comment by stupidloud** [comment]
> 猜测你dest用有域名网站套了cf，被人扫了拿你机当中转用？

看了下这个域名确实套了cf。
所以应该选择未套cdn的国际网站域名是吗？

**Comment by chika0801** [comment]
dest域名如果是套了cf，参考这视频https://m.youtube.com/watch?v=NbruiJShUCE 里面最后部分内容。
解决方法是如果是偷自己，在nginx配置中只允许自己的域名，如果非要dest用别人的，要么你不管，要看，nginx来监听443，sni分流形式到xray，需要在ng配置中用那个相应参数

**Comment by stupidloud** [comment]
> dest域名如果是套了cf，参考这视频https://m.youtube.com/watch?v=NbruiJShUCE 里面最后部分内容。 解决方法是如果是偷自己，在nginx配置中只允许自己的域名，如果非要dest用别人的，要么你不管，要看，nginx来监听443，sni分流形式到xray，需要在ng配置中用那个相应参数

谢谢。明白了，我大概率是成了冤大头了

**Comment by chika0801** [comment]
> 请问大佬，如果目标网站Dest填写邻居的IP：443（不填域名：443），SNI填写邻居域名，也会出现被反撸流量的情况吗？

要看你的邻居接入CF的CDN没有。有，就会。
