### ISSUE TITLE
版本1.8.7，目前打算配置warp为默认出站，但一配置似乎就无法联网，官方的wireguard客户端也是不可以，配置如下，私密信息已隐藏

### ISSUE THREAD

**Issue by Barron857** [XTLS/Xray-core#3018]
{
      "protocol": "wireguard",
      "settings": {
        "secretKey": "999999999",
        "peers": [
          {
            "publicKey": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
            "endpoint": "engage.cloudflareclient.com:2408",
            "allowedIPs": ["0.0.0.0/0", "::/0"]
          }
        ],
        "kernelMode": false
      },
      "tag": "warp"
    }

**Comment by Barron857** [comment]
似乎后面可以了，但仍然不知原因所在，速度奇慢，优选ip后有所改善，✋

**Comment by Barron857** [comment]
如有XD知道原因还请告知，谢啦，✋

**Comment by rileyaaa** [comment]
我也无法联网，目前已经退回1.8.6。回退后一切正常。我是直接路由配置warp协议进行连接的。

**Comment by w9666** [comment]
域名换成IP

**Comment by rileyaaa** [comment]
> 域名换成IP

一直使用的ip，优选过的

**Comment by Barron857** [comment]
> > 域名换成IP
> 
> 一直使用的ip，优选过的

应该是这个情况，谢啦，不过优选过感觉速度还是有点感人

**Comment by Barron857** [comment]
> > > 域名换成IP
> > 
> > 
> > 一直使用的ip，优选过的
> 
> 应该是这个情况，谢啦，不过优选过感觉速度还是有点感人

不然我都想默认出口warp了

**Comment by Barron857** [comment]
> 我也无法联网，目前已经退回1.8.6。回退后一切正常。我是直接路由配置warp协议进行连接的。

似乎换成ip可以解决

**Comment by rileyaaa** [comment]
> > 我也无法联网，目前已经退回1.8.6。回退后一切正常。我是直接路由配置warp协议进行连接的。
> 
> 似乎换成ip可以解决

我一直都是用ip哇。0 0也是不行。最后我就回退了

**Comment by Barron857** [comment]
> > > 我也无法联网，目前已经退回1.8.6。回退后一切正常。我是直接路由配置warp协议进行连接的。
> > 
> > 
> > 似乎换成ip可以解决
> 
> 我一直都是用ip哇。0 0也是不行。最后我就回退了

我之前也不行，但最后一次换的ip可以，就是速度吧实在感人

**Comment by rileyaaa** [comment]
> > > > 我也无法联网，目前已经退回1.8.6。回退后一切正常。我是直接路由配置warp协议进行连接的。
> > > 
> > > 
> > > 似乎换成ip可以解决
> > 
> > 
> > 我一直都是用ip哇。0 0也是不行。最后我就回退了
> 
> 我之前也不行，但最后一次换的ip可以，就是速度吧实在感人

那还是会退吧- -速度慢不行

**Comment by Barron857** [comment]
> > > > > 我也无法联网，目前已经退回1.8.6。回退后一切正常。我是直接路由配置warp协议进行连接的。
> > > > 
> > > > 
> > > > 似乎换成ip可以解决
> > > 
> > > 
> > > 我一直都是用ip哇。0 0也是不行。最后我就回退了
> > 
> > 
> > 我之前也不行，但最后一次换的ip可以，就是速度吧实在感人
> 
> 那还是回退吧- -速度慢不行
那个是爬好久才动一下

**Comment by qwerr0** [comment]
WARP 对配置低的小鸡不友好, 速度很难跑满, 还有就是部分地区要 官方WARP / WARP-GO 才能用,比如香港

**Comment by Barron857** [comment]
> WARP 对配置低的小鸡不友好, 速度很难跑满, 还有就是部分地区要 官方WARP / WARP-GO 才能用,比如香港 如果在墙内用 WARP, UDP 很容易被阻断

我小鸡是4c8g的，配置还是过得去的应该，LA机子

**Comment by maoxikun** [comment]
配置文件加上dns模块试试

**Comment by kilvn** [comment]
破案了，龟壳arm配置，1.8.7 关了内核模式就好了，不然无论如何都无法上网

默认true
kernelMode: true 

需要设置为false
kernelMode: false 

节点地址依然使用域名 engage.cloudflareclient.com:2408

https://xtls.github.io/config/outbounds/wireguard.html#outboundconfigurationobject

**Comment by kilvn** [comment]
![image](https://github.com/XTLS/Xray-core/assets/16423601/9bf34066-9590-43a8-b394-a7eae9ec772f)

回国流量走的 warp+，已经奏效了，但是速度非常感人，就很拨号上网一样🥹

**Comment by Barron857** [comment]
> ![image](https://private-user-images.githubusercontent.com/16423601/307563611-9bf34066-9590-43a8-b394-a7eae9ec772f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NzgwODksIm5iZiI6MTcwODg3Nzc4OSwicGF0aCI6Ii8xNjQyMzYwMS8zMDc1NjM2MTEtOWJmMzQwNjYtOTU5MC00M2E4LWIzOTQtYTdlYWU5ZWM3NzJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDE2MTYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2OTQzODFmZDg4ZDQyYmE0YmIwMWYwNzkyNjEzOGY0ZTdjZDhlOGYxMDM0MDc3ODU3NTllYmY2ZDRjNjAzOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._XRMcPyD-1SEwgWbFzkDUU1g4aI9k33s_ziOYkuyGxo)
> 
> 回国流量走的 warp+，已经奏效了，但是速度非常感人，就很拨号上网一样🥹

那我应该也是关闭了内核模式所以好了，挺溜的，速度真的龟爬🧗…

**Comment by yuhan6665** [comment]
solved
