### ISSUE TITLE
Mux Bug,导致谷歌不通

### ISSUE THREAD

**Issue by z826540272** [XTLS/Xray-core#302]
软件:passwall
开启mux,8
curl测试,
curl 172.217.161.130 ,通
curl 172.217.161.129 ,通
curl 172.217.161.128 ,通
curl 172.217.161.127 ,不通
再次测试
curl 172.217.161.130 ,不通
curl 172.217.161.129 ,不通
curl 172.217.161.128 ,不通

反复测试几次,只要尝试一次 curl 172.217.161.127 之后
.128  .129  .130
全部不通,或者一次通一次不通.
关闭Mux后正常

**Comment by AkinoKaede** [comment]
日志

**Comment by z826540272** [comment]
2021/02/25 12:39:17 [Info] infra/conf/serial: Reading config: /var/etc/passwall/TCP_SOCKS_13d5f2190d364db08c4b608089e2c8d4.json
2021/02/25 12:39:17 [Warning] core: Xray 1.3.0 started
2021/02/25 12:39:26 10.0.0.188:59426 accepted tcp:216.58.200.78:443 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 12:39:28 tcp:127.0.0.1:50996 accepted tcp:8.8.4.4:53 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 12:39:28 10.0.0.218:9389 accepted tcp:140.82.114.25:443 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 12:39:28 10.0.0.218:9392 accepted tcp:172.217.161.128:80 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 12:39:29 10.0.0.218:9397 accepted tcp:172.217.161.128:80 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 12:39:32 tcp:127.0.0.1:50998 accepted tcp:8.8.4.4:53 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 12:39:32 10.0.0.218:9398 accepted tcp:52.74.223.119:443 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 12:39:34 10.0.0.218:9399 accepted tcp:140.82.114.25:443 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 12:39:35 10.0.0.218:9402 accepted tcp:172.217.161.128:80 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 12:39:37 10.0.0.218:9407 accepted tcp:172.217.161.128:80 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 12:39:38 10.0.0.218:9410 accepted tcp:172.217.161.128:80 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 12:39:39 10.0.0.218:9413 accepted tcp:172.217.161.128:80 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 12:39:40 10.0.0.218:9416 accepted tcp:172.217.161.128:80 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 12:39:40 10.0.0.218:9417 accepted tcp:172.217.160.78:443 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 12:39:41 10.0.0.218:9418 accepted tcp:172.217.24.10:443 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 12:39:42 10.0.0.218:9421 accepted tcp:172.217.161.127:80 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 12:39:46 10.0.0.218:9426 accepted tcp:172.217.161.128:80 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 12:39:47 tcp:127.0.0.1:51000 accepted tcp:8.8.4.4:53 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 12:39:47 10.0.0.218:9427 accepted tcp:172.217.24.14:443 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 12:40:04 10.0.0.188:59428 accepted tcp:216.58.200.78:443 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 12:40:04 10.0.0.188:59430 accepted tcp:216.58.200.78:443 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 12:40:07 10.0.0.218:9438 accepted tcp:172.217.161.129:80 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 12:40:09 10.0.0.218:9441 accepted tcp:172.217.161.129:80 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 12:40:11 10.0.0.218:9444 accepted tcp:172.217.161.128:80 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 12:40:13 10.0.0.218:9449 accepted tcp:172.217.161.128:80 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 12:40:14 10.0.0.218:9452 accepted tcp:172.217.161.128:80 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 12:40:16 10.0.0.218:9455 accepted tcp:172.217.161.127:80 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 12:40:19 10.0.0.218:9460 accepted tcp:172.217.161.128:80 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 12:40:26 10.0.0.218:9463 accepted tcp:172.217.24.14:443 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 12:40:38 10.0.0.218:9468 accepted tcp:172.217.161.129:80 [2ddb7d5ad56a4492bf9e6def4ff38ed6]

**Comment by AkinoKaede** [comment]
@z826540272 你这日志全是 accepted…哪里看得出问题

**Comment by z826540272** [comment]
> @z826540272 你这日志全是 accepted…哪里看得出问题
不知道，路由器应该可以复现

**Comment by AkinoKaede** [comment]
我没有这样的设备

**Comment by z826540272** [comment]
2021/02/25 13:09:43 [Info] [658976544] app/dispatcher: default route for tcp:172.217.161.128:80
2021/02/25 13:09:43 [Info] [658976544] common/mux: dispatching request to tcp:172.217.161.128:80
2021/02/25 13:09:43 10.0.0.218:10540 accepted tcp:172.217.161.128:80 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 13:09:44 [Debug] [3601833245] proxy/dokodemo: processing connection from: 10.0.0.218:10543
2021/02/25 13:09:44 [Info] [3601833245] proxy/dokodemo: received request for 10.0.0.218:10543
2021/02/25 13:09:44 [Info] [3601833245] app/dispatcher: sniffed domain: 172.217.161.128
2021/02/25 13:09:44 [Info] [3601833245] app/dispatcher: default route for tcp:172.217.161.128:80
2021/02/25 13:09:44 [Info] [3601833245] common/mux: dispatching request to tcp:172.217.161.128:80
2021/02/25 13:09:44 10.0.0.218:10543 accepted tcp:172.217.161.128:80 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 13:09:44 [Debug] [481784498] proxy/dokodemo: processing connection from: 10.0.0.218:10546
2021/02/25 13:09:44 [Info] [481784498] proxy/dokodemo: received request for 10.0.0.218:10546
2021/02/25 13:09:44 [Info] [481784498] app/dispatcher: sniffed domain: 172.217.161.128
2021/02/25 13:09:44 [Info] [481784498] app/dispatcher: default route for tcp:172.217.161.128:80
2021/02/25 13:09:44 [Info] [481784498] common/mux: dispatching request to tcp:172.217.161.128:80
2021/02/25 13:09:44 10.0.0.218:10546 accepted tcp:172.217.161.128:80 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 13:09:45 [Debug] [20326703] proxy/dokodemo: processing connection from: 10.0.0.218:10549
2021/02/25 13:09:45 [Info] [20326703] proxy/dokodemo: received request for 10.0.0.218:10549
2021/02/25 13:09:45 [Info] [20326703] app/dispatcher: sniffed domain: 172.217.161.128
2021/02/25 13:09:45 [Info] [20326703] app/dispatcher: default route for tcp:172.217.161.128:80
2021/02/25 13:09:45 [Info] [20326703] common/mux: dispatching request to tcp:172.217.161.128:80
2021/02/25 13:09:45 10.0.0.218:10549 accepted tcp:172.217.161.128:80 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 13:09:46 [Debug] [1542897760] proxy/dokodemo: processing connection from: 10.0.0.218:10553
2021/02/25 13:09:46 [Info] [1542897760] proxy/dokodemo: received request for 10.0.0.218:10553
2021/02/25 13:09:46 [Info] [1542897760] app/dispatcher: sniffed domain: 172.217.161.128
2021/02/25 13:09:46 [Info] [1542897760] app/dispatcher: default route for tcp:172.217.161.128:80
2021/02/25 13:09:46 [Info] [1542897760] common/mux: dispatching request to tcp:172.217.161.128:80
2021/02/25 13:09:46 10.0.0.218:10553 accepted tcp:172.217.161.128:80 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 13:09:54 [Debug] [1953388656] proxy/dokodemo: processing connection from: 10.0.0.218:10562
2021/02/25 13:09:54 [Info] [1953388656] proxy/dokodemo: received request for 10.0.0.218:10562
2021/02/25 13:09:54 [Info] [1953388656] app/dispatcher: sniffed domain: 172.217.161.127
2021/02/25 13:09:54 [Info] [1953388656] app/dispatcher: default route for tcp:172.217.161.127:80
2021/02/25 13:09:54 [Info] [1953388656] common/mux: dispatching request to tcp:172.217.161.127:80
2021/02/25 13:09:54 10.0.0.218:10562 accepted tcp:172.217.161.127:80 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 13:10:11 [Debug] [203990257] proxy/dokodemo: processing connection from: 10.0.0.218:10569
2021/02/25 13:10:11 [Info] [203990257] proxy/dokodemo: received request for 10.0.0.218:10569
2021/02/25 13:10:11 [Info] [203990257] app/dispatcher: sniffed domain: 172.217.161.128
2021/02/25 13:10:11 [Info] [203990257] app/dispatcher: default route for tcp:172.217.161.128:80
2021/02/25 13:10:11 [Info] [203990257] common/mux: dispatching request to tcp:172.217.161.128:80
2021/02/25 13:10:11 10.0.0.218:10569 accepted tcp:172.217.161.128:80 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 13:10:38 [Debug] [1611858077] proxy/dokodemo: processing connection from: 10.0.0.188:39062
2021/02/25 13:10:38 [Info] [1611858077] proxy/dokodemo: received request for 10.0.0.188:39062
2021/02/25 13:10:38 [Info] [1611858077] app/dispatcher: sniffed domain: www.youtube.com
2021/02/25 13:10:38 [Info] [1611858077] app/dispatcher: default route for tcp:www.youtube.com:443
2021/02/25 13:10:38 [Info] [1611858077] common/mux: dispatching request to tcp:www.youtube.com:443
2021/02/25 13:10:38 10.0.0.188:39062 accepted tcp:172.217.161.174:443 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 13:10:39 [Debug] [2477136559] proxy/dokodemo: processing connection from: 10.0.0.188:39064
2021/02/25 13:10:39 [Info] [2477136559] proxy/dokodemo: received request for 10.0.0.188:39064
2021/02/25 13:10:39 [Info] [2477136559] app/dispatcher: default route for tcp:172.217.161.174:443
2021/02/25 13:10:39 [Info] [2477136559] common/mux: dispatching request to tcp:172.217.161.174:443
2021/02/25 13:10:39 10.0.0.188:39064 accepted tcp:172.217.161.174:443 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 13:11:01 [Info] [203990257] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport request > read tcp 10.0.0.10:1041->10.0.0.218:10569: read: connection reset by peer
2021/02/25 13:11:01 [Info] [203990257] common/mux: failed to fetch all input > io: read/write on closed pipe
2021/02/25 13:11:01 [Debug] [4105547997] proxy/dokodemo: processing connection from: 10.0.0.218:10599
2021/02/25 13:11:01 [Info] [4105547997] proxy/dokodemo: received request for 10.0.0.218:10599
2021/02/25 13:11:01 [Info] [4105547997] app/dispatcher: sniffed domain: 172.217.161.128
2021/02/25 13:11:01 [Info] [4105547997] app/dispatcher: default route for tcp:172.217.161.128:80
2021/02/25 13:11:01 [Info] [4105547997] common/mux: dispatching request to tcp:172.217.161.128:80
2021/02/25 13:11:01 10.0.0.218:10599 accepted tcp:172.217.161.128:80 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 13:11:04 [Info] [4105547997] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport request > read tcp 10.0.0.10:1041->10.0.0.218:10599: read: connection reset by peer
2021/02/25 13:11:04 [Info] [4105547997] common/mux: failed to fetch all input > io: read/write on closed pipe
2021/02/25 13:11:06 [Debug] [1633286844] proxy/dokodemo: processing connection from: 10.0.0.218:10604
2021/02/25 13:11:06 [Info] [1633286844] proxy/dokodemo: received request for 10.0.0.218:10604
2021/02/25 13:11:06 [Info] [1633286844] app/dispatcher: sniffed domain: 172.217.161.129
2021/02/25 13:11:06 [Info] [1633286844] app/dispatcher: default route for tcp:172.217.161.129:80
2021/02/25 13:11:06 [Info] [1633286844] common/mux: dispatching request to tcp:172.217.161.129:80
2021/02/25 13:11:06 10.0.0.218:10604 accepted tcp:172.217.161.129:80 [2ddb7d5ad56a4492bf9e6def4ff38ed6]

**Comment by z826540272** [comment]
2021/02/25 13:12:00 10.0.0.218:10650 accepted tcp:216.58.200.238:443 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 13:12:02 [Debug] [1409895057] proxy/dokodemo: processing connection from: 10.0.0.218:10653
2021/02/25 13:12:02 [Info] [1409895057] proxy/dokodemo: received request for 10.0.0.218:10653
2021/02/25 13:12:02 [Info] [1409895057] app/dispatcher: sniffed domain: alive.github.com
2021/02/25 13:12:02 [Info] [1409895057] app/dispatcher: default route for tcp:alive.github.com:443
2021/02/25 13:12:02 [Info] [1409895057] common/mux: dispatching request to tcp:alive.github.com:443
2021/02/25 13:12:02 10.0.0.218:10653 accepted tcp:140.82.112.25:443 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 13:12:02 [Info] [3035798779] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > context canceled
2021/02/25 13:12:02 [Info] [3315882538] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > context canceled
2021/02/25 13:12:02 [Info] [3035798779] common/mux: failed to fetch all input > io: read/write on closed pipe
2021/02/25 13:12:02 [Info] [3315882538] common/mux: failed to fetch all input > io: read/write on closed pipe
2021/02/25 13:12:04 [Info] [598834774] proxy/socks: TCP Connect request to tcp:8.8.4.4:53
2021/02/25 13:12:04 [Info] [598834774] app/dispatcher: default route for tcp:8.8.4.4:53
2021/02/25 13:12:04 [Info] [598834774] common/mux: dispatching request to tcp:8.8.4.4:53
2021/02/25 13:12:04 tcp:127.0.0.1:52854 accepted tcp:8.8.4.4:53 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 13:12:04 [Debug] [72007611] proxy/dokodemo: processing connection from: 10.0.0.218:10654
2021/02/25 13:12:04 [Info] [72007611] proxy/dokodemo: received request for 10.0.0.218:10654
2021/02/25 13:12:04 [Info] [72007611] app/dispatcher: sniffed domain: content-autofill.googleapis.com
2021/02/25 13:12:04 [Info] [72007611] app/dispatcher: default route for tcp:content-autofill.googleapis.com:443
2021/02/25 13:12:04 [Info] [72007611] common/mux: dispatching request to tcp:content-autofill.googleapis.com:443
2021/02/25 13:12:04 10.0.0.218:10654 accepted tcp:172.217.27.138:443 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 13:12:04 [Debug] [2383133032] proxy/dokodemo: processing connection from: 10.0.0.218:10655
2021/02/25 13:12:04 [Info] [2383133032] proxy/dokodemo: received request for 10.0.0.218:10655
2021/02/25 13:12:04 [Info] [2383133032] app/dispatcher: sniffed domain: alive.github.com
2021/02/25 13:12:04 [Info] [2383133032] app/dispatcher: default route for tcp:alive.github.com:443
2021/02/25 13:12:04 [Info] [2383133032] common/mux: dispatching request to tcp:alive.github.com:443
2021/02/25 13:12:04 10.0.0.218:10655 accepted tcp:140.82.112.25:443 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 13:12:14 [Info] [2769486087] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > context canceled
2021/02/25 13:12:14 [Info] [2212005866] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > context canceled
2021/02/25 13:12:14 [Info] [3397573202] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > context canceled
2021/02/25 13:12:14 [Info] [2280258670] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > context canceled
2021/02/25 13:12:14 [Info] [2477136559] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > context canceled
2021/02/25 13:12:14 [Info] [2212005866] common/mux: failed to fetch all input > io: read/write on closed pipe
2021/02/25 13:12:14 [Info] [2769486087] common/mux: failed to fetch all input > io: read/write on closed pipe
2021/02/25 13:12:14 [Info] [2477136559] common/mux: failed to fetch all input > io: read/write on closed pipe
2021/02/25 13:12:14 [Info] [3397573202] common/mux: failed to fetch all input > io: read/write on closed pipe
2021/02/25 13:12:14 [Info] [2280258670] common/mux: failed to fetch all input > io: read/write on closed pipe
2021/02/25 13:12:20 [Debug] [2036036583] proxy/dokodemo: processing connection from: 10.0.0.112:54106
2021/02/25 13:12:20 [Info] [2036036583] proxy/dokodemo: received request for 10.0.0.112:54106
2021/02/25 13:12:20 10.0.0.112:54106 accepted tcp:172.217.24.74:443 [2ddb7d5ad56a4492bf9e6def4ff38ed6]
2021/02/25 13:12:20 [Info] [2036036583] app/dispatcher: sniffed domain: chromesyncpasswords-pa.googleapis.com
2021/02/25 13:12:20 [Info] [2036036583] app/dispatcher: default route for tcp:chromesyncpasswords-pa.googleapis.com:443
2021/02/25 13:12:20 [Info] [2036036583] common/mux: dispatching request to tcp:chromesyncpasswords-pa.googleapis.com:443
2021/02/25 13:13:11 [Info] [1189582218] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > context canceled
2021/02/25 13:13:11 [Info] [1189582218] common/mux: failed to fetch all input > io: read/write on closed pipe

**Comment by z826540272** [comment]
PC端复现
curl --socks5 127.0.0.1:10808 172.217.161.129

**Comment by KyonCN** [comment]
我以为只有我遇到了 看来是openwrt问题 滚到最新版后 ws彻底没法用了 就算关了mux 速度也会降
