### ISSUE TITLE
freedom出站的domainStrategy设置成AsIs，按照文档说的优先级由系统控制。

### ISSUE THREAD

**Issue by leslieqwq** [XTLS/Xray-core#3020]
我配置了一个freedom出站，domainStrategy是AsIs，然后再routing里把tcp和udp全部丢给这个出站。
文档说： "AsIs"：Freedom 使用系统 DNS 同时查询 A 和 AAAA 记录获取 IP，向此域名发出连接。IPv4 或 IPv6 优先级由系统控制。
我的系统已经是ipv4优先了，不管是curl ip.sb还是nslookup。都是v4优先。但是在xray里还是优先获取了ipv6

**Comment by chika0801** [comment]
你发一下你两端配置文件，才好分析。

**Comment by gszj2018** [comment]
因为xray是go语言编写的，go用的是自己的dns解析逻辑不是系统自带的getaddrinfo，如果你的“系统优先级”指的是gai.conf的话，那对xray来说就是无效的。

**Comment by yuhan6665** [comment]
Answered
