### ISSUE TITLE
Frequent restarts Xray 

### ISSUE THREAD

**Issue by hunter-xyz** [XTLS/Xray-core#3027]
i have a bing problem with xray 1.8.7 after few hours xray automatically restarted from few minutes to 4 hours in max duration that can work without restart

so i change xray to 1.7.5 now this problem Much better than before but now every 13h will restart but very better that 1.8.7 

1.8.7 is very unstable but 1.7.5 90% is more stable 

But this problem is not completely solved

Can anyone guide me?

tnx

**Comment by qwerr0** [comment]
What is the reason for the restart? OOM?

**Comment by hunter-xyz** [comment]
![image](https://github.com/XTLS/Xray-core/assets/142353771/e582ba10-fae4-4f44-83fb-742fcad8543b)

**Comment by qwerr0** [comment]
![image](https://github.com/XTLS/Xray-core/assets/155908258/335a6e32-e801-46b9-b6ec-d03997dcf453)
Logs

**Comment by amiralipoor20072007** [comment]
I have the same problem

Here is my warning log 

2024/02/16 14:17:30 WARNING - XRAY: [1646272470] app/dispatcher: non existing outTag: blocked
2024/02/16 14:17:30 WARNING - XRAY: [1442439944] app/dispatcher: non existing outTag: blocked
2024/02/16 14:17:30 WARNING - XRAY: [999450809] app/dispatcher: non existing outTag: blocked
2024/02/16 14:17:30 WARNING - XRAY: [1784283545] app/dispatcher: non existing outTag: blocked
2024/02/16 14:17:30 WARNING - XRAY: [170110445] app/dispatcher: non existing outTag: blocked
2024/02/16 14:17:30 WARNING - XRAY: [857614339] app/dispatcher: non existing outTag: blocked
2024/02/16 14:17:30 WARNING - XRAY: [3500373746] app/dispatcher: non existing outTag: blocked
2024/02/16 14:17:30 WARNING - XRAY: [3737486588] app/dispatcher: non existing outTag: blocked

**Comment by hunter-xyz** [comment]
> Add Conf:
> 
> ```json
> {
>   "outbounds": [
>     {
>       "tag": "blocked",
>       "protocol": "blackhole"
>     }
>   ]
> }
> ```

this is for me ? or not ?

this is my xray config :

`

  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "log": {
    "error": "./error.log",
    "loglevel": "warning"
  },
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    },
`

**Comment by amiralipoor20072007** [comment]
> Add Conf:
> ```json
> {
>   "outbounds": [
>     {
>       "tag": "blocked",
>       "protocol": "blackhole"
>     }
>   ]
> }
> 
> ```

I add it but it doesn't help , i still have to restart it every couple hours

**Comment by hunter-xyz** [comment]
yep
me too
but with 1.7.5 is more stable than 1.8.7 
today i did switch to 1.8.0 from 1.7.5 but i need more time to test it 

i think 1.8.7 is unstable and is poppy choppy

**Comment by Eslender73** [comment]
> yep me too but with 1.7.5 is more stable than 1.8.7 today i did switch to 1.8.0 from 1.7.5 but i need more time to test it
> 
> i think 1.8.7 is unstable and is poppy choppy

do you use trojan config?

**Comment by hunter-xyz** [comment]
no i have not

i have just vless tcp and vmess tcp without tls
and ws with tls 
just trhee ports i have on my panel 


with 1.8.0 my panel running for 16h without restart !!! 

i think 1.8.0 is full stable !

![image](https://github.com/XTLS/Xray-core/assets/142353771/c454c52f-fd2d-40f4-aede-76814cac3b70)

**Comment by masbur** [comment]
I have the same problem

I have 2 types of configuration
1. single service, trojan (OOM Error)
2. all in one service (works fine)

Single service using VPS 2 Core 4 GB RAM, then I tried upgrading to 4 Core 8 GB RAM, as a result the RAM always runs out and get OOM Error.

User active < 20

NB: single service vmess and vless work fine

**Comment by hunter-xyz** [comment]
i did test hardware config but It had no effect

but xray 1.8.3 is very good and It restarts very rarely and its acceptable

**Comment by RPRX** [comment]
Try 1.8.4

**Comment by masbur** [comment]
I tried version 1.8.8 RAM usage was better except trojan

And this is result from xray 1.8.4 ( trojan )
![image](https://github.com/XTLS/Xray-core/assets/16659305/d36a49b0-58e1-4645-a7b7-8fd7a0144198)

traffic 100Mbps
user active < 20

**Comment by hunter-xyz** [comment]
The only solution that worked 100% is that the RAM of the vps is at least 4GB and version of xray must 1.8.1

**Comment by karimi12** [comment]
I had this error in log  before restart 
version 1.8.10:
` 9 ERROR - X-UI: Failure in running xray-core: exit status 2`

config: vless+TLS+TCP -- fallback --> vless + ws
