### ISSUE TITLE
ERROR - XRAY: peer(bmXO…fgyo)

### ISSUE THREAD

**Issue by roozbehalamdari** [XTLS/Xray-core#3030]
Hello, I encountered a problem in the X-UI panel. Please help me how to solve this problem
Error : 
peer(bmXO…fgyo)

![Error](https://github.com/XTLS/Xray-core/assets/131817501/956c5c57-a499-47e2-b04c-513890c9259f)

**Comment by roozbehalamdari** [comment]
No, unfortunately, I don't know where to raise my problem, can you please give me the link?
thank you

**Comment by amirhakimnejad** [comment]
I'm having the same problem(sometimes). It looks like something is crashing, and for me,  nothing will fix it until you restart Xray a few times.
It happens on the Wireguard module.

**Comment by roozbehalamdari** [comment]
> I'm having the same problem(sometimes). It looks like something is crashing, and for me, nothing will fix it until you restart Xray a few times. It happens on the Wireguard module.

Yes, unfortunately, that's exactly it, please teach me if you find a solution, my friend
thank you

**Comment by dimzon** [comment]
> > I'm having the same problem(sometimes). It looks like something is crashing, and for me, nothing will fix it until you restart Xray a few times. It happens on the Wireguard module.
> 
> Yes, unfortunately, that's exactly it, please teach me if you find a solution, my friend thank you

just replace warp endpoint address with another IP and try another ports. Use google for "WARP endpoint IP PORT"

**Comment by yuhan6665** [comment]
Please state what is the actual problem, not just log. Also attach config.
