### ISSUE TITLE
About traffic routing

### ISSUE THREAD

**Issue by AnnaPetrovaWer** [XTLS/Xray-core#3036]
Good day!
I wanted to consult with you regarding implementing certain functionalities using xray-core.

The situation involves:

A foreign server
The use of vless+tcp+reality+flow
A local server within the country
The goal is to direct traffic from the client to the foreign server and, based on specific geographical conditions, either send it directly or redirect it to a local server in my country using WG/SS if it meets certain rules.

RULES:

{
    "outboundTag": "local_route",
    "ip": [
        "geoip:fi",
    ],
    "type": "field"
}
OUTBOUND:

{
      "tag": "local_route",
      "protocol": "wireguard",
      "settings": {…}
}
I've managed a solution but feel it might be rudimentary and am seeking advice from esteemed colleagues for a more appropriate and optimized approach.

Thank you!

**Comment by yuhan6665** [comment]
Your config is fine. See more in https://xtls.github.io/config/routing.html
