### ISSUE TITLE
反代TCP能否保留源IP地址

### ISSUE THREAD

**Issue by qn2060** [XTLS/Xray-core#3039]
昨天试用了一下反代，用的是core: Xray 1.8.7 started  版本

反代成功了，但是real server显示的请求的源IP为 127.0.0.1
![image](https://github.com/XTLS/Xray-core/assets/15309040/18da0c9d-35ab-4e45-b8bd-6777b92df7ef)

一直想找一款反代tcp并且能保留源IP地址的工具，lvs的几种模式对我的场景都不适用，因为我的外界请求流量是nat进来的，需要原进原出。

不知道这种功能能不能实现，感谢！

**Comment by yuhan6665** [comment]
solved
