### ISSUE TITLE
Balancer with leastPing strategy routes to direct for the 1st interval duration.

### ISSUE THREAD

**Issue by pulsarice** [XTLS/Xray-core#3042]
I have 3 reverse (portal) tunnels to my server and I use a balancer to choose the reverse tunnel with the least ping.
when xray starts, the first observatory probe fails immediately and all routing rules with a balancertag go to the first outbound (direct).
I've set the interval to 5s. 
5 seconds after xray has started, the second probe succeeds and now my balancertag actually routes traffic based on selector object and will not use direct.
to mitigate this problem I've added this before the direct outbound:
```
  {
    "tag": "proxy",
    "protocol": "freedom",
    "proxySettings": {
      "tag": "portal-1"
    }
  },
  {
    "tag": "direct",
    "protocol": "freedom"
  }, ...
```
Now for the first 5 seconds, my packets won't go to direct, but will use portal-1

Do you have a better workaround?

**Comment by us254** [comment]
```
{
  // Other configurations
  "outbounds": [
    {
      "tag": "portal-1",
      "protocol": "freedom",
      // Other settings for portal-1
    },
    {
      "tag": "portal-2",
      "protocol": "freedom",
      // Other settings for portal-2
    },
    {
      "tag": "portal-3",
      "protocol": "freedom",
      // Other settings for portal-3
    },
    {
      "tag": "fallback",
      "protocol": "freedom",
      // Other settings for fallback
    },
    {
      "tag": "direct",
      "protocol": "freedom"
    }
  ],
  "routing": {
    "rules": [
      {
        // ... your other rules
      },
      {
        "type": "field",
        "inboundTag": ["balancer-inbound-tag"], // Replace with your actual inbound tag
        "balancerTag": "balancer",
        "fallbackTag": "fallback" // Use the fallback tag here
      }
    ]
  }
  // Other configurations
}
```

**Comment by yuhan6665** [comment]
Fixed in main. Still recommend you to have a fallbacktag setting
