### ISSUE TITLE
Reality 能否负载均衡

### ISSUE THREAD

**Issue by ixxmu** [XTLS/Xray-core#3046]
比如，我有十个vps的不同ip地址，将一个域名解析到不同的10个ip地址上负载均衡，我能否用一套reality配置使用！

目前测试是不行的

**Comment by kilvn** [comment]
梯子靠的是线路，线路好，一台顶一个集群，线路不好你整 100 台也就那样，没什么意义

**Comment by ixxmu** [comment]
算了，提了也没人搭理！ 
关了，几百台专线换个协议吧
