### ISSUE TITLE
How to mod core xray to support payload

### ISSUE THREAD

**Issue by SaungKancil** [XTLS/Xray-core#3048]
How to mod xray core to support payload http request like this

GET / HTTP/1.1[crlf]Host: google.com[crlf]Connection: Keep-Alive[crlf]User-Agent: [ua][crlf][crlf]BMOVE / HTTP/1.1[crlf]Host: [host][crlf]Upgrade: websocket[crlf][crlf][crlf][split]HTTP/1.1 200 OK[crlf][crlf]

**Comment by yuhan6665** [comment]
Not enough info

**Comment by freddymulenda9-lgtm** [comment]
Bonjour boss,  j'suis très reconnaissant de tout,  j'suis pas connecté
