### ISSUE TITLE
证书更新以后需要重启xray吗?

### ISSUE THREAD

**Issue by HiColinn** [XTLS/Xray-core#305]
目前使用acme.sh维护证书文件,定期自动更新证书,那么证书更新以后,需要手动重启xray来刷新证书吗?

**Comment by AkinoKaede** [comment]
目前设置 `OcspStapling` 便可热重载，不需要重启

**Comment by HiColinn** [comment]
如果使用OcspStapling 来检查证书更新,比如acme.sh在A时间点更新了证书,但是xray的检查证书更新的周期还没到(假设是B时间点),那么A->B这段时间,证书已经更新了,但是xray还没有检查证书,也没有热重载,这种情况怎么解决?
还是说用acme.sh的更新证书后的后置动作来重启xray?

**Comment by ShinyGwyn** [comment]
> 如果使用OcspStapling 来检查证书更新,比如acme.sh在A时间点更新了证书,但是xray的检查证书更新的周期还没到(假设是B时间点),那么A->B这段时间,证书已经更新了,但是xray还没有检查证书,也没有热重载,这种情况怎么解决?
> 还是说用acme.sh的更新证书后的后置动作来重启xray?

检查时间缩短. 提前一个月重签证书. 完全没影响. 下版本默认开启热重载

**Comment by wulabing** [comment]
@ShinyGwyn 理论情况下 提前30天更新证书，只会触发一次 可以优先考虑使用amce.sh的 reloadcmd

**Comment by HiColinn** [comment]
> > 如果使用OcspStapling 来检查证书更新,比如acme.sh在A时间点更新了证书,但是xray的检查证书更新的周期还没到(假设是B时间点),那么A->B这段时间,证书已经更新了,但是xray还没有检查证书,也没有热重载,这种情况怎么解决?
> > 还是说用acme.sh的更新证书后的后置动作来重启xray?
> 
> 检查时间缩短. 提前一个月重签证书. 完全没影响. 下版本默认开启热重载

谢谢回复,还有个问题,OcspStapling参数值太小会影响性能吗?目前主要是配置acme.sh使用,letsencrypt 证书有效期是90天,acme.sh是60天自动更新证书,那么OcspStapling参数值设置多少才更合适呢?

**Comment by HiColinn** [comment]
> @ShinyGwyn 理论情况下 提前30天更新证书，只会触发一次 可以优先考虑使用amce.sh的 reloadcmd

是的,我也是考试,如果非常及时的话,就让acme.sh更新证书以后自动重载xray,和以前重载nginx一样,只是不知道哪个更好点

**Comment by ShinyGwyn** [comment]
> > > 如果使用OcspStapling 来检查证书更新,比如acme.sh在A时间点更新了证书,但是xray的检查证书更新的周期还没到(假设是B时间点),那么A->B这段时间,证书已经更新了,但是xray还没有检查证书,也没有热重载,这种情况怎么解决?
> > > 还是说用acme.sh的更新证书后的后置动作来重启xray?
> > 
> > 
> > 检查时间缩短. 提前一个月重签证书. 完全没影响. 下版本默认开启热重载
> 
> 谢谢回复,还有个问题,OcspStapling参数值太小会影响性能吗?目前主要是配置acme.sh使用,letsencrypt 证书有效期是90天,acme.sh是60天自动更新证书,那么OcspStapling参数值设置多少才更合适呢?

3600
