### ISSUE TITLE
WARNING - XRAY: [3284902805] app/proxyman/inbound: connection ends

### ISSUE THREAD

**Issue by roozbehalamdari** [XTLS/Xray-core#3050]
hello please help me , how to fix this error on my panel ?
Thanks
![image](https://github.com/XTLS/Xray-core/assets/131817501/6d7970c5-f63a-4d23-8e55-8e295767f29c)
![image](https://github.com/XTLS/Xray-core/assets/131817501/f2ff72cf-7e0c-41e8-a492-d5347afb5e5e)
![image](https://github.com/XTLS/Xray-core/assets/131817501/5ced9ab0-b118-4a87-bc8d-3e42c1e59fde)

`WARNING - XRAY: [3284902805] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to write A response payload > transport/internet/grpc/encoding: failed to send data over gRPC tunnel > rpc error: code = Canceled desc = context canceled`

**Comment by yuhan6665** [comment]
If it works fine, you can safely ignore this log

**Comment by roozbehalamdari** [comment]
> If it works fine, you can safely ignore this log

Thanks Bro ♥
