### ISSUE TITLE
如何进行热更新

### ISSUE THREAD

**Issue by lmmqxyx404** [XTLS/Xray-core#3051]
我想研究一下X-ray core源码，该如何配置热更新啊？就是改动源码后，可以立刻编译，然后运行

**Comment by us254** [comment]
This script assumes that you have `inotify-tools` installed for file watching.

```bash
#!/bin/bash

# Prepare the environment
curl -sLo go.tar.gz https://go.dev/dl/$(curl -sL https://golang.org/VERSION?m=text|head -1).linux-amd64.tar.gz
rm -rf /usr/local/go
tar -C /usr/local/ -xzf go.tar.gz
rm go.tar.gz
echo -e "export PATH=\$PATH:/usr/local/go/bin" > /etc/profile.d/go.sh
source /etc/profile.d/go.sh
go version
apt install -y git

# Download the code
git clone https://github.com/XTLS/Xray-core.git

# Set the source directory and binary path
SOURCE_DIR="Xray-core"
BINARY="/usr/local/bin/xray"

# Function to compile and restart the X-ray process
compile_and_restart() {
    cd "$SOURCE_DIR"
    git pull
    go mod download
    go env -w CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v2
    go build -v -o xray -trimpath -ldflags "-s -w -buildid=" ./main

    # Kill the running X-ray process (if any)
    pkill -f "$BINARY"

    # Copy the new binary and make it executable
    cp -f xray "$BINARY"
    chmod +x "$BINARY"

    # Start the new X-ray process
    "$BINARY" &
}

# Initial compile and start
compile_and_restart

# Watch for changes in the source directory using inotifywait
inotifywait -m -e close_write -r "$SOURCE_DIR" | while read -r directory events filename; do
    # If a Go source file is changed, recompile and restart
    if [[ "$filename" =~ \.go$ ]]; then
        echo "Detected change in $filename, recompiling..."
        compile_and_restart
    fi
done
```

Save this script in a file, for example `hot_reload.sh`, and make it executable with the command `chmod +x hot_reload.sh`. You can then run the script with `./hot_reload.sh` to start the hot reloading process.


- This script will start the Xray process after the initial compilation and will continue to monitor the source directory for changes.
- When a `.go` file is saved, the script will recompile the source code and restart the Xray process with the new binary.
- Ensure that you have the appropriate permissions to execute these commands, especially for operations that require root access, such as copying the binary to `/usr/local/bin/`.

**Comment by lmmqxyx404** [comment]
Thanks so much.
But I found a moe effective way to learn the code. I was reading the vless_test.go file.
