### ISSUE TITLE
How to find the connected client Local IP? (For Port Forwarding)

### ISSUE THREAD

**Issue by jamiekarvans** [XTLS/Xray-core#3054]
hi i want to use use port for example 8080 but i want to hide my ip while doing so,
so i have bought a VPS and installed V2Ray with Xray core on it, now i connect to my vps using v2ray but how to port forward the data from port 8080 on VPS to the client connected local ip? 
is there any Virual ip adresses for each client or dhcp ip? anything?
hwo to find it and forward data to the ip?

**Comment by jamiekarvans** [comment]
Perfect, thank you.

**Comment by jamiekarvans** [comment]
There is no information about the local ip, it just sends data from all the
users to 172.16.1.1
How can I find the local ip of each connectwd device?

**Comment by yuhan6665** [comment]
Answered. 内网信息在客户端上有
