### ISSUE TITLE
Reality缓存被“偷”网站的特征信息

### ISSUE THREAD

**Issue by raintean** [XTLS/Xray-core#3056]
### Discussed in https://github.com/XTLS/Xray-core/discussions/2060

<div type='discussions-op-text'>

<sup>Originally posted by **raintean** May 11, 2023</sup>
看了源码, 没看懂.  也搜过issue/discussion没有找到.  
想了解一下, 每次客户端连接到服务器的时候, 服务器都是临时去fetch证书信息的吗?</div>

**Comment by Fangliding** [comment]
@raintean 是的 根据服务器到dest会凭空多出几到十几毫秒的延迟

**Comment by kilvn** [comment]
如果能缓存几分钟到几小时是不是一定程度能减少每次的延迟

**Comment by Zxis233** [comment]
> 如果能缓存几分钟到几小时是不是一定程度能减少每次的延迟

这是未来等待开发的特性，R佬在一个Issue下提过
