### ISSUE TITLE
[Bug] 🐛 burstObservatory 不会在启动的时候自动运行

### ISSUE THREAD

**Issue by Harry-zklcdc** [XTLS/Xray-core#3058]
如题，配置了`burstObservatory`观测项后，检测并不会在启动时自动运行，而是必须等待 `burstObservatory.pingConfig.interval` 设置的时长后，才能第一次检测，否则就会回落到 `balancers.fallbackTag` 或代理失败

**Comment by Harry-zklcdc** [comment]
附上配置
```json
"burstObservatory": {
        "subjectSelector": [
            "Proxy"
        ],
        "pingConfig": {
            "destination": "https://www.google.com/gen_204",
            "interval": "600s",
            "connectivity": "http://connectivitycheck.platform.hicloud.com/generate_204",
            "timeout": "30s",
            "sampling": 2
        }
    }
```

**Comment by Harry-zklcdc** [comment]
日志 

> 已略去无关日志

```log
2024/02/27 01:13:27 [Warning] core: Xray 1.8.8 started
2024/02/27 01:19:05 [Debug] app/observatory/burst: checking Proxy_1
2024/02/27 01:19:48 [Debug] app/observatory/burst: checking Proxy_3
```

**Comment by RPRX** [comment]
~~试下 v2fly 有没有该问题~~

**Comment by Harry-zklcdc** [comment]
有看到相关Issu: https://github.com/v2fly/v2ray-core/issues/2837

**Comment by RPRX** [comment]
~~我就知道，因为那边的很多东西是名义上做了但实际上几乎没人用过，所以有点 buggy，以前就经常遇到~~

麻烦 @yuhan6665 修一下

**Comment by BI7PRK** [comment]
我的配置了 leastLoad 的 `burstObservatory` 但在日志中没看到任何相关信息。而`leastPing`策略才有在日志中看到结果。
是配置有错了？

```
         "routing": {


		"balancers": [
			{
				"tag": "balancer",
				"strategy": {
					"type": "leastLoad"
				},
				"selector": [
					"proxy_"
				]
			}
		]
	},
	"burstObservatory": {
		"pingConfig": {
			"destination": "https://www.gstatic.com/generate_204",
			"interval": "15m",
			"timeout": "15s",
			"connectivity": "http://connectivitycheck.platform.hicloud.com/generate_204",
			"sampling": 2
		},
		"subjectSelector": [
			"proxy_"
		]
	},
```

**Comment by Harry-zklcdc** [comment]
你配置了15分钟的话，~~按照当前版本~~可能需要7分钟之后才会有第一次测试日志输出

**Comment by BI7PRK** [comment]
> 你配置了15分钟的话，~按照当前版本~可能需要7分钟之后才会有第一次测试日志输出

几个小时过去了，一条信息都没见到。日志已经是debug级别。

**Comment by Harry-zklcdc** [comment]
那我真不太晓得了，我这边是正常的，~~除了没法一启动就检测~~

**Comment by BI7PRK** [comment]
> 那我真不太晓得了，我这边是正常的，~除了没法一启动就检测~

间隔时间调到10秒，就有日志输出了 ^_^

`[Debug] app/observatory/burst: checking proxy_main`
但不像`leastPing`策略可以看到延时值
` [Info] app/observatory: the outbound proxy_main is alive:0.875003953`

**Comment by yuhan6665** [comment]
@BI7PRK @Harry-zklcdc 最新的 main 应该修好了 有空麻烦测一下 https://github.com/XTLS/Xray-core/actions/runs/8166925945
不过可能还是设置 balancers.fallbackTag 一个默认节点比较妥当

**Comment by Harry-zklcdc** [comment]
正常了

日志
```bash
2024/03/06 13:29:12 [Warning] core: Xray 1.8.8 started
2024/03/06 13:29:12 [Info] app/observatory/burst: perform one-time health check for tags [Proxy_1 Proxy_2 Proxy_3 Proxy_4 Proxy_5 Proxy_6 Proxy_7]
2024/03/06 13:29:12 [Debug] app/observatory/burst: checking Proxy_7
2024/03/06 13:29:12 [Debug] app/observatory/burst: checking Proxy_3
2024/03/06 13:29:12 [Debug] app/observatory/burst: checking Proxy_1
2024/03/06 13:29:12 [Debug] app/observatory/burst: checking Proxy_4
2024/03/06 13:29:12 [Debug] app/observatory/burst: checking Proxy_2
2024/03/06 13:29:12 [Debug] app/observatory/burst: checking Proxy_5
2024/03/06 13:29:12 [Debug] app/observatory/burst: checking Proxy_6
```

**Comment by BI7PRK** [comment]
> @BI7PRK @Harry-zklcdc 最新的 main 应该修好了 有空麻烦测一下 https://github.com/XTLS/Xray-core/actions/runs/8166925945 不过可能还是设置 balancers.fallbackTag 一个默认节点比较妥当


报告：请留意是否还存在问题，情况如下：
第一次全节点检测正常运行，但是在后续工作中似乎没有全部检测。配置如下：
有3个节点：proxy_s1; proxy_s2; proxy_s3。出站配置顺序也是顺的。

```JSON
"burstObservatory": {
		"pingConfig": {
			"destination": "https://www.gstatic.com/generate_204",
			"interval": "2m",
			"timeout": "15s",
			"connectivity": "http://connectivitycheck.platform.hicloud.com/generate_204",
			"sampling": 2
		},
		"subjectSelector": [
			"proxy_"
		]
	},
```
在日志中记录中只有 proxy_s1; proxy_s2 出现。proxy_s3 没有出现过。

**Comment by yuhan6665** [comment]
@BI7PRK 确保使用 debug 日志 看一下 “checking ..” 开头的日志有没有

**Comment by BI7PRK** [comment]
> @BI7PRK 确保使用 debug 日志 看一下 “checking ..” 开头的日志有没有

日志为debug，搜索内容 `burst` 
自刚才反馈之时，重启过核心。现在能看到全部节点的检测。我再继续观察。感谢大佬回复。打扰啦。

**Comment by Arrow-Li** [comment]
> > 那我真不太晓得了，我这边是正常的，~除了没法一启动就检测~
> 
> 间隔时间调到10秒，就有日志输出了 ^_^
> 
> `[Debug] app/observatory/burst: checking proxy_main` 但不像`leastPing`策略可以看到延时值 ` [Info] app/observatory: the outbound proxy_main is alive:0.875003953`

```
19:11:40 [Info] app/observatory: the outbound proxy1 is alive:0.2930329
19:11:40 [Info] app/observatory: the outbound proxy is alive:0.8141488
```
alive后面的数值是延时秒吗，0.29就是290ms？

**Comment by yuhan6665** [comment]
> alive后面的数值是延时秒吗，0.29就是290ms？

是的
