### ISSUE TITLE
请求改进日志显示

### ISSUE THREAD

**Issue by ddvcx** [XTLS/Xray-core#306]
xray 1.3.0 win64客户端, 日志等级为warning

1/经常出现这样的警告, 请帮忙看下怎么解决
2021/02/26 08:56:53 [Warning] [3159599242] proxy/http: failed to read response from scdown.qq.com > io: read/write on closed pipe
2021/02/26 08:58:35 [Warning] [1561070041] app/proxyman/inbound: connection ends > proxy/http: connection ends > proxy/http: failed to write response > write tcp 127.0.0.1:8001->127.0.0.1:49281: wsasend: An established connection was aborted by the software in your host machine.

2/大多数日志的格式为: 网址:端口, 如:
2021/02/26 08:57:01 127.0.0.1:65512 accepted //lp.open.weixin.qq.com:443 [HTTP入站 -> 直连]
但是有些日志的格式为: 网址/路径, 如:
2021/02/26 08:56:52 127.0.0.1:65509 accepted http://scdown.qq.com/download/HelperUpdate.htm [HTTP入站 -> 直连]
2021/02/26 09:02:31 127.0.0.1:49698 accepted http://scrootca1.ocsp.secomtrust.net/MEowSDBGMEQwQjAJBgUrDgMCGgUABBToZI35nvnlbqQAOxgex2VgV2SjmAQUoHNJmWjchVtl45soL1efvTO8B0gCCRK5sPpy4NhIxg%3D%3D [HTTP入站 -> 代理]
非常不美观, 请问如何能让他们统一为较短的网址?

log记录:
2021/02/26 08:56:45 127.0.0.1:65506 accepted http://91.108.56.133:80/api [HTTP入站 -> 代理]
2021/02/26 08:56:52 127.0.0.1:65509 accepted http://scdown.qq.com/download/HelperUpdate.htm [HTTP入站 -> 直连]
2021/02/26 08:56:53 [Warning] [3159599242] proxy/http: failed to read response from scdown.qq.com > io: read/write on closed pipe
2021/02/26 08:57:01 127.0.0.1:65512 accepted //lp.open.weixin.qq.com:443 [HTTP入站 -> 直连]
2021/02/26 08:57:18 127.0.0.1:65523 accepted //lp.open.weixin.qq.com:443 [HTTP入站 -> 直连]
2021/02/26 08:57:24 127.0.0.1:65527 accepted //slscr.update.microsoft.com:443 [HTTP入站 -> 直连]
2021/02/26 08:58:09 127.0.0.1:49235 accepted //res.wx.qq.com:443 [HTTP入站 -> 直连]
2021/02/26 08:58:15 127.0.0.1:49246 accepted //oauthaccountmanager.googleapis.com:443 [HTTP入站 -> 代理]
2021/02/26 08:58:35 127.0.0.1:49280 accepted //91.108.56.133:443 [HTTP入站 -> 代理]
2021/02/26 08:58:35 127.0.0.1:49281 accepted http://91.108.56.133:80/api [HTTP入站 -> 代理]
2021/02/26 08:58:35 [Warning] [1561070041] app/proxyman/inbound: connection ends > proxy/http: connection ends > proxy/http: failed to write response > write tcp 127.0.0.1:8001->127.0.0.1:49281: wsasend: An established connection was aborted by the software in your host machine.
2021/02/26 09:00:05 127.0.0.1:49434 accepted //api.github.com:443 [HTTP入站 -> 代理]
2021/02/26 09:02:31 127.0.0.1:49698 accepted http://crl.identrust.com/DSTROOTCAX3CRL.crl [HTTP入站 -> 代理]
2021/02/26 09:02:31 127.0.0.1:49698 accepted http://scrootca1.ocsp.secomtrust.net/MEowSDBGMEQwQjAJBgUrDgMCGgUABBToZI35nvnlbqQAOxgex2VgV2SjmAQUoHNJmWjchVtl45soL1efvTO8B0gCCRK5sPpy4NhIxg%3D%3D [HTTP入站 -> 代理]
2021/02/26 09:02:35 127.0.0.1:49702 accepted //91.108.56.133:443 [HTTP入站 -> 代理]

服务器设置:
{
	"inbounds": [
		{
			"listen": "0.0.0.0",
			"port": 443,
			"protocol": "vless",
			"settings": {
				"clients": [
					{
						"id": "", // UUID
						"flow": "xtls-rprx-direct"
					}
				],
				"decryption": "none",
				"fallbacks": [
					{
						"dest": 80,
						"xver": 0
					}
				]
			},
			"streamSettings": {
				"network": "tcp",
				"security": "xtls",
				"xtlsSettings": {
					"alpn": ["http/1.1"],
					"certificates": [
						{
							"certificateFile": "/",
							"keyFile": "/"
						}
					]
				}
			}
		}
	],

	"outbounds": [
		{
			"protocol": "freedom"
		}
	],

	"routing": {
		"domainStrategy": "AsIs",
		"rules": [
			{
				"type": "field",
				"outboundTag": "block",
				"protocol": ["bittorrent"]
			}
		]
	}
}

客户端设置:
{
	"log": {
		"loglevel": "warning" // none, error, warning, info, debug
	},

    "inbounds": [
        {
			"listen": "0.0.0.0",
            "port": 8000,
            "protocol": "socks",
            "tag": "SOCKS入站",
            "settings": {
                "auth": "noauth",
                "udp": true
            },
            "sniffing": { // 域名和协议的路由分流需要此项
                "enabled": true,
                "destOverride": ["http", "tls"]
            }
        },
		{
			"listen": "0.0.0.0",
			"port": 8001,
			"protocol": "http",
            "tag": "HTTP入站",
            "sniffing": { // 域名和协议的路由分流需要此项
                "enabled": true,
                "destOverride": ["http", "tls"]
            }
		}
	],

	"outbounds": [
		{
			"protocol": "vless",
			"tag": "代理",
			"settings": {
				"vnext": [
					{
                        "address": "", // 域名或服务器 IP (无需解析域名)
						"port": 443,
						"users": [
							{
								"id": "",
								"encryption": "none",
								"flow": "xtls-rprx-direct"
							}
						]
					}
				]
			},
			"streamSettings": {
				"network": "tcp",
				"security": "xtls",
				"xtlsSettings": {
					"allowInsecure": true,
                    "serverName": "" // 域名
				}
			}
		},
		{
			"protocol": "blackhole",
			"tag": "屏蔽"
		},
		{
			"protocol": "freedom",
			"tag": "直连"
		}    
	],

	"routing": { //从上往下匹配
		"domainStrategy": "IPOnDemand", // AsIs, IPIfNonMatch, IPOnDemand
		"rules": [
			{
				"type": "field",
				"outboundTag": "屏蔽",
				"domain": [
					"geosite:ad"
				]
			},
			{
				"type": "field",
				"outboundTag": "直连",
				"protocol": [
					"bittorrent"
				]
			},
			{
				"type": "field",
				"outboundTag": "直连",
				"domain": [
					"geosite:cn"
				]
			},
			{
				"type": "field",
				"outboundTag": "直连",
				"ip": [
					"geoip:cn",
					"geoip:private"
				]
			},
		    {
				"type": "field",
				"network":"tcp,udp",
				"outboundTag": "代理"
			}
		]
	}
}

**Comment by AkinoKaede** [comment]
日志应该显示足够详细的信息，TLS 的是因为加密无法获取到 URL

**Comment by ddvcx** [comment]
> 日志应该显示足够详细的信息，TLS 的是因为加密无法获取到 URL

多谢解答, 可能我描述问题没有清楚
显示足够详细的信息没问题,  显示简单的信息也没问题
我的意思是不应该把两者混在一起,显示
希望能有个设置控制这两种显示方式
