### ISSUE TITLE
有关reality三分钟阻断的问题

### ISSUE THREAD

**Issue by Daryl-Do** [XTLS/Xray-core#3062]
近一年一直受到三分钟阻断的影响，不知道有没有解决办法？

VPS是甲骨文美西的机子，一开始使用ws+cdn(cf)+vmess/vless/其他，cdn的节点ip经常受到阻断，表现为几分钟连不上，然后又恢复。有试过优选ip+负载均衡，印象中是所有用过的ip都被阻断过。优选cf变得越来越难，现在这个协议只做备用。

目前近半年用的是reality+vision，一开始偷别人的（大厂），近一两个月开始频繁被阻断；改成偷自己的后，依然会被阻断。

当然被阻断具体多久没有仔细算过，大概率是大家常说的三分钟。

个人猜想：
1. 配置哪里出错了？ 比如禁回国流量在x-ui不知道怎么配置。
2. 甲骨文的某些ip段被当做cdn对待，被墙/运营商选择性阻断。坐标上海联通。

**Comment by chika0801** [comment]
要么你换你的运营商，要么你不用甲骨文，换vps商家

**Comment by RPRX** [comment]
~~去年的日经问题，甲骨文是这样的~~

昨天我看到群里 kevin 说他有个线路用 vision+reality 会被干扰，用浏览器却不会，我觉得 gfw 可能在测试针对 vision 现有的那些参数了，@yuhan6665 会改一下参数给他试试，你可以也索要一份试试，另外你需要测试下只高频浏览伪装站是否容易被阻断

~~虽然我觉得对你的情况没用，甲骨文 IP 段太脏了，先 Close 了，顺便改个标题~~
