### ISSUE TITLE
XRV only accepts XUDP other than all MUX traffic

### ISSUE THREAD

**Issue by maskedeken** [XTLS/Xray-core#3066]
这里限制了只有XUDP能够通过XRV，但似乎放开所有MUX流量也没有问题？
[https://github.com/XTLS/Xray-core/blob/1c8375997d627d6ae40df4f4c242293d01659974/proxy/vless/inbound/inbound.go#L499](https://github.com/XTLS/Xray-core/blob/1c8375997d627d6ae40df4f4c242293d01659974/proxy/vless/inbound/inbound.go#L499)

**Comment by RPRX** [comment]
~~一年了~~，v1.8.8 终于默认把包括 XUDP 在内的所有场景置于 Flow 的统一调控之下，~~意义挺重大的~~，建议大家升级

v1.9.0 除了 Seed 外，还可能会给 XUDP 开无限 padding，具体的默认行为到时会和 Seed 一起进行说明

**Comment by csryt** [comment]
@RPRX 大佬来群里吹流弊，大佬辛苦了，不懂但已阅。

**Comment by maskedeken** [comment]
Got it

**Comment by RPRX** [comment]
还有就是为了能够裸奔，不过 v1.9.0 的 Seed 可以设置 XRV 只 padding 不裸奔，可以和 WS、H2、gRPC 等传输方式结合使用

还有目前 H2、gRPC 都是默认只开一条 TCP 来多路复用，这个非常不合理，打算在 v1.9.0 中加一些控制参数

**Comment by RPRX** [comment]
> 还有目前 H2、gRPC 都是只开一条 TCP 来多路复用，这个非常不合理，打算在 v1.9.0 中加一些控制参数

这个还没做，@maskedeken 你有兴趣的话可以给它俩加个 `concurrency` 参数，0 代表无限复用（当前行为），-1 代表不复用
