### ISSUE TITLE
failed to load system root certificate

### ISSUE THREAD

**Issue by Vohrt** [XTLS/Xray-core#307]
使用VLESS-TCP-XTLS-WHATEVER配置，虽然systemctl status xray 中显示active(running)，但是所有客户端连接都显示io：read/write on closed pipe
log中存在 [Error] transport/internet/xtls: failed to load system root certificate

Feb 26 22:48:10 VpsTokyo1 xray[773]: Xray 1.3.0 (Xray, Penetrates Everything.) Custom (go1.15.8 linux/amd64)
Feb 26 22:48:10 VpsTokyo1 xray[773]: A unified platform for anti-censorship.
Feb 26 22:48:10 VpsTokyo1 xray[773]: 2021/02/26 22:48:10 [Info] infra/conf/serial: Reading config: /usr/local/etc/xray/config.json
Feb 26 22:48:12 VpsTokyo1 xray[773]: 2021/02/26 22:48:12 [Error] transport/internet/xtls: failed to load system root certificate > transport/internet/xtls: append cert to root
Feb 26 22:48:12 VpsTokyo1 xray[773]: 2021/02/26 22:48:12 [Warning] transport/internet/xtls: ignoring invalid X509 key pair > tls: failed to find certificate PEM data in certificate input, but did find a private key; PEM inputs may have >
Feb 26 22:48:12 VpsTokyo1 xray[773]: 2021/02/26 22:48:12 [Warning] transport/internet/tcp: accepting PROXY protocol
Feb 26 22:48:12 VpsTokyo1 xray[773]: 2021/02/26 22:48:12 [Warning] transport/internet/websocket: accepting PROXY protocol
Feb 26 22:48:12 VpsTokyo1 xray[773]: 2021/02/26 22:48:12 [Warning] transport/internet/tcp: accepting PROXY protocol
Feb 26 22:48:12 VpsTokyo1 xray[773]: 2021/02/26 22:48:12 [Warning] transport/internet/websocket: accepting PROXY protocol
Feb 26 22:48:12 VpsTokyo1 xray[773]: 2021/02/26 22:48:12 [Warning] core: Xray 1.3.0 started

**Comment by AkinoKaede** [comment]
证书配置错误

**Comment by korben1029** [comment]
我也遇到了这个问题，但我解决了，示例里证书配置用的是cer和key，这样就会出错，换成pem那个证书就可以了
