### ISSUE TITLE
REALITY is getting blocked everyday! Xray must use SNI to Connect to Dest

### ISSUE THREAD

**Issue by APT-ZERO** [XTLS/Xray-core#3074]
Hello,
Currently there is a huge problem with REALITY
Xray-core uses no SNI to get Certificate of Dest (So it will get an wrong Cert!) and also uses no SNI to get their homepage to show to GFW (so in 99% of websites will just show an Error when no SNI used to connect to them)
I think that's why REALITY is getting blocked easily this days
When i set "example.com:443" as 'dest' of 'realitySettings', Why Xray-core don't use 'example.com' as SNI to connect to it?

**Comment by Fangliding** [comment]
This depends on how dest handles connections without sni, xray will remain consistent with dest, which is the correct behavior

**Comment by RPRX** [comment]
> Xray-core uses no SNI to get Certificate of Dest (So it will get an wrong Cert!) and also uses no SNI to get their homepage to show to GFW

Incorrect.
