### ISSUE TITLE
请问xray-core是否支持搭配shadowsocks的simple-obfs http混淆插件使用？

### ISSUE THREAD

**Issue by zsbstephen** [XTLS/Xray-core#3078]
RT，因为VPS跑VLESS+WS+TLS的443端口被封，为了抢救小鸡修改了配置文件，增加了一段shadowsocks2022的inbound

        "inboundDetour": [ {
                "listen": "127.0.0.1",
                "port": 55555,
                "protocol": "shadowsocks",
                "settings": {
                        "method": "2022-blake3-chacha20-poly1305",
                        "password": "openssl_-base32_passphrase",
                        "udp": true,
                        "network": "tcp,udp"
                }               ,
                "tag": "shadowsocks"
        }
        ],

考虑到即使shadowsocks2022虽然解决了重放攻击和被主动探测的问题，但依然有流量特征直接暴露的问题，为了小鸡IP端口使用寿命，编译安装了 @madeye 的simple-obfs http混淆插件，将流量伪装成http流量并且让obfs监听80端口，创建好开机启动服务，接收到的数据解除混淆后转发给SSD的55555端口
 https://github.com/shadowsocks/simple-obfs

        {
                "server":    "0.0.0.0",
                "server_port": 80,
                "dst_addr":    "127.0.0.1:55555",
                "timeout": 60,
                "obfs":    "http",
                "reuse_port": true,
                "fast_open": true
        }

然后在OpenWrt的PassWall和安卓手机的Shadowsocks上部署都能测试通过可以正常工作，虽然速度比VLESS VISION Reality慢一些不过也可以理解，但在防火墙流确实是显示成http流量。唯独剩下Windows PC了，shadowsocks Windows版已经快2年没更新，不支持新的2022-blake3-chacha20-poly1305和2022-blake3-aes-256-gcm加密算法；隔壁sing-box也不支持simple-obfs插件。难道只能靠local-obfs.exe跑standalone模式了么 T_T ？

**Comment by KobeArthurScofield** [comment]
是的，而且如果需要 UDP 转发的话得写两个 outbound

**Comment by yuhan6665** [comment]
Answered. No plan for legacy
