### ISSUE TITLE
Snapchat blocking VPNs

### ISSUE THREAD

**Issue by Heclalava** [XTLS/Xray-core#3079]
So Snapchat will not work on any v2ray xray server I have (about 70). It is usually one server per customer/family, so not a lot users or data flowing through the VPN to Snapchat.  I have tried to change the IP address of one server and still no luck. Even CN2/GIA servers from gigsgigs are blocked. 

I don't think it is IP address blocking, and reportedly Astrill works for Snapchat. 

Setup is xray reality on most the servers.  

I have tried to disable GPS access to snapchat, forcing all traffic to go through the VPN and not splitting to have Chinese traffic bypass the VPN. It is not like it is completely blocked by Snapchat, you can still access the app, but you are unable to send friend requests, and can't send snaps and messages. 

So I am curious why none of the xray servers work but Astrill is fine. What is the blocking mechanism? Is there a work around?

**Comment by Heclalava** [comment]
> In fact, when you use full route mode to use some software, there is no difference between self hosted xray server and VPN provider. Why are you would to use gigsgigs cloud? there are too much Chinese users at here. I think it absolutely IP affect you. could you please try another one server provider if possible?
> 
> 事實上，當您使用 全局模式 去使用某些程式時，在這種情況下，自託管XRAY伺服器和VPN供應商沒有任何區別。 您爲什麼會考慮使用GIGSGIGS雲呢？這兒有太多中國用戶了。我認爲IP地址問題絕對會影響您的。如果可以的話，也許您可以嘗試別的伺服器託管商？

It doesn't make a difference which supplier I use. I've got 6 different suppliers with servers in different countries, different ISPs. How can every IP across 15 servers tested be affected?

Snapchat is somehow detecting that the connection is from a VPN. My customer who told me about the issue, we changed the IP and the new IP didn't work. That's when I went to go test other servers from all my suppliers and it's the same across the board.

**Comment by yuhan6665** [comment]
Not a xray issue if your service doesn't like it.
