### ISSUE TITLE
Xray(https)回落到nginx(http)报400的问题

### ISSUE THREAD

**Issue by HiColinn** [XTLS/Xray-core#308]
![2021-02-27_035027](https://user-images.githubusercontent.com/65964332/109348053-fe3d3980-78ae-11eb-8829-d0fcf78864f8.jpg)
目前我所采用的是xray标准回落思路,即:
    访问ip:80(http)-->nginx-->301转到xray坚挺的443(https)-->转到nginx监听的8080端口(一个正常网站),整个流程都没有问题,域名也也能正常从http转到https,但是转到8080以后会报400错误,
    不知道是不是我配置错误?
    还是这就是正常情况?
    如果是正常情况,那么443端口被xray占用以后,我再想把一些域名转到Nginx监听的正常网站就行不通了?

附上Nginx配置:
```
server {
    listen 80;
    server_name *.domain.vip;
    return 301 https://$http_host$request_uri;
}
server {
    listen 127.0.0.1:8080;
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }
    #root   /usr/share/nginx/html;
    #index index.html;
    add_header Strict-Transport-Security "max-age=63072000" always;
}
```
附上Xray配置:
```
{
    "log": {
        "loglevel": "warning"
    },
    "inbounds": [{
        "listen": "0.0.0.0",
        "port": 443,
        "protocol": "vless",
        "settings": {
            "clients": [{
                "id": "6bd", // 填写你的 UUID
                "flow": "xtls-rprx-direct",
                "level": 0,
                "email": "a@qq.com"
            }],
            "decryption": "none",
            "fallbacks": [{
                    "dest": "8080", // 默认回落到本地的80端口
                    "xver": 1
                },
                {
                    "path": "/websocket", // 必须换成自定义的 PATH
                    "dest": 1234,
                    "xver": 1
                }
            ]
        },
        "streamSettings": {
            "network": "tcp",
            "security": "xtls",
            "xtlsSettings": {
                "alpn": [
                    "h2,http/1.1"
                ],
                "certificates": [{
                    "certificateFile": "/etc/xray/ssl/io.vip/fullchain.cer", // 换成你的证书，绝对路径
                    "keyFile": "/etc/xray/ssl/io.vip/io.vip.key" // 换成你的私钥，绝对路径
                }]
            }
        }
    }],
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ]
}
```

**Comment by cwyin7788** [comment]
> ![2021-02-27_035027](https://user-images.githubusercontent.com/65964332/109348053-fe3d3980-78ae-11eb-8829-d0fcf78864f8.jpg)
> 目前我所采用的是xray标准回落思路,即:
> 访问ip:80(http)-->nginx-->301转到xray坚挺的443(https)-->转到nginx监听的8080端口(一个正常网站),整个流程都没有问题,域名也也能正常从http转到https,但是转到8080以后会报400错误,
> 不知道是不是我配置错误?
> 还是这就是正常情况?
> 如果是正常情况,那么443端口被xray占用以后,我再想把一些域名转到Nginx监听的正常网站就行不通了?
> 
> 附上Nginx配置:
> 
> ```
> server {
>     listen 80;
>     server_name *.domain.vip;
>     return 301 https://$http_host$request_uri;
> }
> server {
>     listen 127.0.0.1:8080;
>     location / {
>         root   /usr/share/nginx/html;
>         index  index.html index.htm;
>     }
>     #root   /usr/share/nginx/html;
>     #index index.html;
>     add_header Strict-Transport-Security "max-age=63072000" always;
> }
> ```
> 
> 附上Xray配置:
> 
> ```
> {
>     "log": {
>         "loglevel": "warning"
>     },
>     "inbounds": [{
>         "listen": "0.0.0.0",
>         "port": 443,
>         "protocol": "vless",
>         "settings": {
>             "clients": [{
>                 "id": "6bd", // 填写你的 UUID
>                 "flow": "xtls-rprx-direct",
>                 "level": 0,
>                 "email": "a@qq.com"
>             }],
>             "decryption": "none",
>             "fallbacks": [{
>                     "dest": "8080", // 默认回落到本地的80端口
>                     "xver": 1
>                 },
>                 {
>                     "path": "/websocket", // 必须换成自定义的 PATH
>                     "dest": 1234,
>                     "xver": 1
>                 }
>             ]
>         },
>         "streamSettings": {
>             "network": "tcp",
>             "security": "xtls",
>             "xtlsSettings": {
>                 "alpn": [
>                     "h2,http/1.1"
>                 ],
>                 "certificates": [{
>                     "certificateFile": "/etc/xray/ssl/io.vip/fullchain.cer", // 换成你的证书，绝对路径
>                     "keyFile": "/etc/xray/ssl/io.vip/io.vip.key" // 换成你的私钥，绝对路径
>                 }]
>             }
>         }
>     }],
>     "outbounds": [
>         {
>             "protocol": "freedom"
>         }
>     ]
> }
> ```

你nginx和xray配置檔都需要配置一個http2端口，令xray解開xtls / tls後，回落到該http2端口，例如xray要這樣：

 "fallbacks": [{
                   "dest": "8080", // 默认回落到本地的80端口
                     "xver": 1
                 },
                 {
                     "path": "/websocket", // 必须换成自定义的 PATH
                     "dest": 1234,
                     "xver": 1
                 },
                {
                    "alpn": "h2", 
                    "dest": 8081,
                    "xver": 1
                }
]
         },


nginx這樣配置：

listen 127.0.0.1:8080;
listen 127.0.0.1:8081 http2;

我再想把一些域名转到Nginx监听的正常网站就行不通了? ＜---你可以用xray的sni域名分流功能，1.22及之後的版本可用，

https://bionicosmos.github.io/XTLS.github.io/documents/level-1/fallbacks-with-sni/

**Comment by HiColinn** [comment]
> > 目前我所采用的是xray标准回落思路,即:
> > 访问ip:80(http)-->nginx-->301转到xray坚挺的443(https)-->转到nginx监听的8080端口(一个正常网站),整个流程都没有问题,域名也也能正常从http转到https,但是转到8080以后会报400错误,
> > 不知道是不是我配置错误?
> > 还是这就是正常情况?
> > 如果是正常情况,那么443端口被xray占用以后,我再想把一些域名转到Nginx监听的正常网站就行不通了?
> > 附上Nginx配置:
> > ```
> > server {
> >     listen 80;
> >     server_name *.domain.vip;
> >     return 301 https://$http_host$request_uri;
> > }
> > server {
> >     listen 127.0.0.1:8080;
> >     location / {
> >         root   /usr/share/nginx/html;
> >         index  index.html index.htm;
> >     }
> >     #root   /usr/share/nginx/html;
> >     #index index.html;
> >     add_header Strict-Transport-Security "max-age=63072000" always;
> > }
> > ```
> > 
> > 
> > 附上Xray配置:
> > ```
> > {
> >     "log": {
> >         "loglevel": "warning"
> >     },
> >     "inbounds": [{
> >         "listen": "0.0.0.0",
> >         "port": 443,
> >         "protocol": "vless",
> >         "settings": {
> >             "clients": [{
> >                 "id": "6bd", // 填写你的 UUID
> >                 "flow": "xtls-rprx-direct",
> >                 "level": 0,
> >                 "email": "a@qq.com"
> >             }],
> >             "decryption": "none",
> >             "fallbacks": [{
> >                     "dest": "8080", // 默认回落到本地的80端口
> >                     "xver": 1
> >                 },
> >                 {
> >                     "path": "/websocket", // 必须换成自定义的 PATH
> >                     "dest": 1234,
> >                     "xver": 1
> >                 }
> >             ]
> >         },
> >         "streamSettings": {
> >             "network": "tcp",
> >             "security": "xtls",
> >             "xtlsSettings": {
> >                 "alpn": [
> >                     "h2,http/1.1"
> >                 ],
> >                 "certificates": [{
> >                     "certificateFile": "/etc/xray/ssl/io.vip/fullchain.cer", // 换成你的证书，绝对路径
> >                     "keyFile": "/etc/xray/ssl/io.vip/io.vip.key" // 换成你的私钥，绝对路径
> >                 }]
> >             }
> >         }
> >     }],
> >     "outbounds": [
> >         {
> >             "protocol": "freedom"
> >         }
> >     ]
> > }
> > ```
> 
> 你nginx和xray配置檔都需要配置一個http2端口，令xray解開xtls / tls後，回落到該http2端口，例如xray要這樣：
> 
> "fallbacks": [{
> "dest": "8080", // 默认回落到本地的80端口
> "xver": 1
> },
> {
> "path": "/websocket", // 必须换成自定义的 PATH
> "dest": 1234,
> "xver": 1
> },
> {
> "alpn": "h2",
> "dest": 8081,
> "xver": 1
> }
> ]
> },
> 
> nginx這樣配置：
> 
> listen 127.0.0.1:8080;
> listen 127.0.0.1:8081 http2;
> 
> 我再想把一些域名转到Nginx监听的正常网站就行不通了? ＜---你可以用xray的sni域名分流功能，1.22及之後的版本可用，
> 
> https://bionicosmos.github.io/XTLS.github.io/documents/level-1/fallbacks-with-sni/
> 
> 溫馨提示：你的截圖見到你的服務器域名了，快點把它遮蓋吧。

您好,域名是假的,哈哈哈,感谢提醒!
但是依然没有解决问题,我修改后的配置如下:
Nginx:
```
server {
    listen 80;
    server_name *.i.vip;
    return 301 https://$http_host$request_uri;
}
server {
    listen 127.0.0.1:8080;
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }
    add_header Strict-Transport-Security "max-age=63072000" always;
}
server {
    listen 127.0.0.1:8081 http2;
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }
}

```
Xray:
```
{
    "log": {
        "loglevel": "warning"
    },
    "inbounds": [{
        "listen": "0.0.0.0",
        "port": 443,
        "protocol": "vless",
        "settings": {
            "clients": [{
                "id": "956988fb36bd", // 填写你的 UUID
                "flow": "xtls-rprx-direct",
                "level": 0,
                "email": "a@qq.com"
            }],
            "decryption": "none",
            "fallbacks": [
                {
                    "dest": "8080", // 默认回落到本地的8080端口(http)
                    "xver": 1
                },
                {
                    "alpn": "h2",
                    "dest": "8081", // 默认回落到本地的8081端口(h2)
                    "xver": 1
                }
            ]
        },
        "streamSettings": {
            "network": "tcp",
            "security": "xtls",
            "xtlsSettings": {
                "alpn": [
                    "h2,http/1.1"
                ],
                "certificates": [{
                    "certificateFile": "/etc/xray/ssl/i.vip/fullchain.cer", // 换成你的证书，绝对路径
                    "keyFile": "/etc/xray/ssl/i.vip/i.vip.key" // 换成你的私钥，绝对路径
                }]
            }
        }
    }],
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ]
}
```

按您说的修改以后,依然是报400错误

**Comment by HiColinn** [comment]
附上Nginx日志:
```
127.0.0.1 - - [27/Feb/2021:15:45:48 +0800] "PROXY TCP4 88.202.233.156 88.202.233.156 59936 443" 400 157 "-" "-" "-"
127.0.0.1 - - [27/Feb/2021:15:45:50 +0800] "PROXY TCP4 88.202.233.156 88.202.233.156 59942 443" 400 157 "-" "-" "-"
127.0.0.1 - - [27/Feb/2021:15:45:50 +0800] "PROXY TCP4 88.202.233.156 88.202.233.156 59944 443" 400 157 "-" "-" "-"
127.0.0.1 - - [27/Feb/2021:15:46:07 +0800] "PROXY TCP4 88.202.233.156 88.202.233.156 59954 443" 400 157 "-" "-" "-"
127.0.0.1 - - [27/Feb/2021:15:46:07 +0800] "PROXY TCP4 88.202.233.156 88.202.233.156 59958 443" 400 157 "-" "-" "-"
88.202.233.156 - - [27/Feb/2021:15:46:07 +0800] "GET /favicon.ico HTTP/1.1" 301 169 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36" "-"
127.0.0.1 - - [27/Feb/2021:15:46:08 +0800] "PROXY TCP4 88.202.233.156 88.202.233.156 59968 443" 400 157 "-" "-" "-"
127.0.0.1 - - [27/Feb/2021:15:46:08 +0800] "PROXY TCP4 88.202.233.156 88.202.233.156 59974 443" 400 157 "-" "-" "-"
127.0.0.1 - - [27/Feb/2021:15:46:16 +0800] "PROXY TCP4 88.202.233.156 88.202.233.156 59980 443" 400 157 "-" "-" "-"
127.0.0.1 - - [27/Feb/2021:15:46:16 +0800] "PROXY TCP4 88.202.233.156 88.202.233.156 59982 443" 400 157 "-" "-" "-"
39.96.139.158 - - [27/Feb/2021:15:46:17 +0800] "GET / HTTP/1.1" 301 169 "-" "Go-http-client/1.1" "-"
127.0.0.1 - - [27/Feb/2021:15:46:18 +0800] "PROXY TCP4 39.96.139.158 88.202.233.156 59948 443" 400 157 "-" "-" "-"
39.96.139.158 - - [27/Feb/2021:15:46:44 +0800] "\x16\x03\x01\x00\xEE\x01\x00\x00\xEA\x03\x03Z\x0EFX\x09\xDD\x99i\xD6\x84\xBE\x048D\xA6'u\x1EO\xD7\xCC\xC32\xEC\x10\x08bKH\xF3\xCA\x9C \x92\xF4G\xDF\xA3y}jfW\xF0\xF2\xC6\xEB\x0F\x1A'\x0E\x12\x0Ec\xC3\xF4?\x1D\x22+F\x9F\x7FA\x9F\x00&\xC0/\xC00\xC0+\xC0,\xCC\xA8\xCC\xA9\xC0\x13\xC0\x09\xC0\x14\xC0" 400 157 "-" "-" "-"
59.126.35.90 - - [27/Feb/2021:15:46:50 +0800] "GET / HTTP/1.1" 301 169 "-" "Mozilla/5.0" "-"
39.96.139.158 - - [27/Feb/2021:15:47:16 +0800] "\x16\x03\x01\x00\xEE\x01\x00\x00\xEA\x03\x03A\xB0\x83\xDF\x0Eg\xC6\xAB\xC1,\x1C\xA5_lD\xBB1\x94\x8B*\x9E\xD1\x87\x15-\xA6\xBDo\xB8\xC0\xE9c \x8C\x81\x0F\x93\xE5\xD6B\x0Cv" 400 157 "-" "-" "-"
127.0.0.1 - - [27/Feb/2021:15:47:26 +0800] "PROXY TCP4 88.202.233.156 88.202.233.156 59996 443" 400 157 "-" "-" "-"
127.0.0.1 - - [27/Feb/2021:15:47:26 +0800] "PROXY TCP4 88.202.233.156 88.202.233.156 59998 443" 400 157 "-" "-" "-"
39.96.139.158 - - [27/Feb/2021:15:47:49 +0800] "\x16\x03\x01\x00\xEE\x01\x00\x00\xEA\x03\x03\xAAW=\xB7\x1BR4\xA1\x9B\xEF\xFC\xD5\xE8l\xA5\xEA\x04\xCC\x13uo0\x17\xE7\xDD\xB1\xDF\xCBb\x8B.\x9E \xFF\xD2\x12\x9D2\xA5\xFC\xD0\x0CS\xD7\xDB8\xF0gK\xA5M\x055\x88\x15\x7Fx8\xD8\xFF*\xF0\xD3Q\xC4\x00&\xC0/\xC00\xC0+\xC0,\xCC\xA8\xCC\xA9\xC0\x13\xC0\x09\xC0\x14\xC0" 400 157 "-" "-" "-"
127.0.0.1 - - [27/Feb/2021:15:48:07 +0800] "PROXY TCP4 88.202.233.156 88.202.233.156 60008 443" 400 157 "-" "-" "-"
127.0.0.1 - - [27/Feb/2021:15:48:07 +0800] "PROXY TCP4 88.202.233.156 88.202.233.156 60010 443" 400 157 "-" "-" "-"
[root@89 ~]# 
```

**Comment by JimhHan** [comment]
nginx 需要设置接受 proxy_protocol。可以参照[bionicosmos的文档](https://bionicosmos.github.io/XTLS.github.io/documents/level-1/fallbacks-with-sni/#fn:4)中的Nginx配置

**Comment by cwyin7788** [comment]
> 附上Nginx日志:
> 
> ```
> 127.0.0.1 - - [27/Feb/2021:15:45:48 +0800] "PROXY TCP4 88.202.233.156 88.202.233.156 59936 443" 400 157 "-" "-" "-"
> 127.0.0.1 - - [27/Feb/2021:15:45:50 +0800] "PROXY TCP4 88.202.233.156 88.202.233.156 59942 443" 400 157 "-" "-" "-"
> 127.0.0.1 - - [27/Feb/2021:15:45:50 +0800] "PROXY TCP4 88.202.233.156 88.202.233.156 59944 443" 400 157 "-" "-" "-"
> 127.0.0.1 - - [27/Feb/2021:15:46:07 +0800] "PROXY TCP4 88.202.233.156 88.202.233.156 59954 443" 400 157 "-" "-" "-"
> 127.0.0.1 - - [27/Feb/2021:15:46:07 +0800] "PROXY TCP4 88.202.233.156 88.202.233.156 59958 443" 400 157 "-" "-" "-"
> 88.202.233.156 - - [27/Feb/2021:15:46:07 +0800] "GET /favicon.ico HTTP/1.1" 301 169 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36" "-"
> 127.0.0.1 - - [27/Feb/2021:15:46:08 +0800] "PROXY TCP4 88.202.233.156 88.202.233.156 59968 443" 400 157 "-" "-" "-"
> 127.0.0.1 - - [27/Feb/2021:15:46:08 +0800] "PROXY TCP4 88.202.233.156 88.202.233.156 59974 443" 400 157 "-" "-" "-"
> 127.0.0.1 - - [27/Feb/2021:15:46:16 +0800] "PROXY TCP4 88.202.233.156 88.202.233.156 59980 443" 400 157 "-" "-" "-"
> 127.0.0.1 - - [27/Feb/2021:15:46:16 +0800] "PROXY TCP4 88.202.233.156 88.202.233.156 59982 443" 400 157 "-" "-" "-"
> 39.96.139.158 - - [27/Feb/2021:15:46:17 +0800] "GET / HTTP/1.1" 301 169 "-" "Go-http-client/1.1" "-"
> 127.0.0.1 - - [27/Feb/2021:15:46:18 +0800] "PROXY TCP4 39.96.139.158 88.202.233.156 59948 443" 400 157 "-" "-" "-"
> 39.96.139.158 - - [27/Feb/2021:15:46:44 +0800] "\x16\x03\x01\x00\xEE\x01\x00\x00\xEA\x03\x03Z\x0EFX\x09\xDD\x99i\xD6\x84\xBE\x048D\xA6'u\x1EO\xD7\xCC\xC32\xEC\x10\x08bKH\xF3\xCA\x9C \x92\xF4G\xDF\xA3y}jfW\xF0\xF2\xC6\xEB\x0F\x1A'\x0E\x12\x0Ec\xC3\xF4?\x1D\x22+F\x9F\x7FA\x9F\x00&\xC0/\xC00\xC0+\xC0,\xCC\xA8\xCC\xA9\xC0\x13\xC0\x09\xC0\x14\xC0" 400 157 "-" "-" "-"
> 59.126.35.90 - - [27/Feb/2021:15:46:50 +0800] "GET / HTTP/1.1" 301 169 "-" "Mozilla/5.0" "-"
> 39.96.139.158 - - [27/Feb/2021:15:47:16 +0800] "\x16\x03\x01\x00\xEE\x01\x00\x00\xEA\x03\x03A\xB0\x83\xDF\x0Eg\xC6\xAB\xC1,\x1C\xA5_lD\xBB1\x94\x8B*\x9E\xD1\x87\x15-\xA6\xBDo\xB8\xC0\xE9c \x8C\x81\x0F\x93\xE5\xD6B\x0Cv" 400 157 "-" "-" "-"
> 127.0.0.1 - - [27/Feb/2021:15:47:26 +0800] "PROXY TCP4 88.202.233.156 88.202.233.156 59996 443" 400 157 "-" "-" "-"
> 127.0.0.1 - - [27/Feb/2021:15:47:26 +0800] "PROXY TCP4 88.202.233.156 88.202.233.156 59998 443" 400 157 "-" "-" "-"
> 39.96.139.158 - - [27/Feb/2021:15:47:49 +0800] "\x16\x03\x01\x00\xEE\x01\x00\x00\xEA\x03\x03\xAAW=\xB7\x1BR4\xA1\x9B\xEF\xFC\xD5\xE8l\xA5\xEA\x04\xCC\x13uo0\x17\xE7\xDD\xB1\xDF\xCBb\x8B.\x9E \xFF\xD2\x12\x9D2\xA5\xFC\xD0\x0CS\xD7\xDB8\xF0gK\xA5M\x055\x88\x15\x7Fx8\xD8\xFF*\xF0\xD3Q\xC4\x00&\xC0/\xC00\xC0+\xC0,\xCC\xA8\xCC\xA9\xC0\x13\xC0\x09\xC0\x14\xC0" 400 157 "-" "-" "-"
> 127.0.0.1 - - [27/Feb/2021:15:48:07 +0800] "PROXY TCP4 88.202.233.156 88.202.233.156 60008 443" 400 157 "-" "-" "-"
> 127.0.0.1 - - [27/Feb/2021:15:48:07 +0800] "PROXY TCP4 88.202.233.156 88.202.233.156 60010 443" 400 157 "-" "-" "-"
> [root@89 ~]# 
> ```

你試試將fallback的xver改為0。

nginx的8080、8081兩個LISTEN放在1個server裡，別分開，雖然我不知道有沒有關係，但我是將2個端口的LISTEN放在1個server內的

除了你沒用proxy protocol外，你和我的配置也差不多了。

**Comment by HiColinn** [comment]
> nginx 需要设置接受 proxy_protocol。可以参照[bionicosmos的文档](https://bionicosmos.github.io/XTLS.github.io/documents/level-1/fallbacks-with-sni/#fn:4)中的Nginx配置

的确是这个原因,已解决,感谢~

**Comment by HiColinn** [comment]
> 沒用proxy protocol

确实是因为没有使用沒用proxy protocol,已经解决,感谢
