### ISSUE TITLE
为什么从前天开始，我的所有服务器都无法使用了，显示真延迟=-1，更新订阅和v2rayn也不行

### ISSUE THREAD

**Issue by vonBigCooler** [XTLS/Xray-core#3083]
代码显示一下内容，
2024/03/02 09:34:06 系统代理设置改变Pac
2024/03/02 09:34:06 127.0.0.1:7020 accepted //www.google.com:443 [http -> proxy]
2024/03/02 09:34:16 当前服务的真连接延迟: -1 ms
总不能是我的所有服务器都崩掉了吧。

**Comment by vonBigCooler** [comment]
哪位大哥看到可以帮忙解答一下吗

**Comment by chika0801** [comment]
你这类故障，建议你加下xray群，在线问问其他人，你这样发内容，和在这发这问题，基本上没人愿意（想）回你。

**Comment by vonBigCooler** [comment]
谢谢大哥，方便告诉我如何找到相应的群聊信息吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XTLS/Xray-core"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月2日(星期六) 上午9:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [XTLS/Xray-core] 为什么从前天开始，我的所有服务器都无法使用了，显示真延迟=-1，更新订阅和v2rayn也不行 (Issue #3083)





 
你这类故障，建议你加下xray群，在线问问其他人，你这样发内容，和在这发这问题，基本上没人愿意（想）回你。

**Comment by stqfdyr** [comment]
close吧

**Comment by JohnnyZhang0628** [comment]
我也是的，一直-1，

**Comment by vonBigCooler** [comment]
谢谢各位的回答，问题已经解决了，出现-1基本就是服务器坏掉了。重新找一些服务器更新就好了。只不过这次十几个服务器基本都同时坏掉了，我就没有认为是服务器的问题一开始

**Comment by JohnnyZhang0628** [comment]
@vonBigCooler 服务器坏掉是什么意思？我的服务器查看Xray还是在运行的

**Comment by vonBigCooler** [comment]
如果你的正常可以访问外网就没啥问题喽，我找的节点全部不能用了，所以连接上之后真延迟全部为-1

**Comment by stqfdyr** [comment]
所以你并没有自己搭建，只是找来的节点-1连不上了就来这里问？
