### ISSUE TITLE
请问有没有办法实现多个协议共用一组uuid

### ISSUE THREAD

**Issue by fyhong** [XTLS/Xray-core#3086]
例如
{ "port": 1001, "protocol": "vless",  "settings": {  "decryption": "none", "clients": [ "clients_tag" ] },
{ "port": 1001, "protocol": "vmess",  "settings": { "clients": [ "clients_tag" ] }

{
"clients": [ "tag:" "clients_tag",
{ "id": "id1" },
{ "id": "id2 }
] }

**Comment by chise0713** [comment]
你这么做的目的是？

**Comment by Fangliding** [comment]
@chise0713 哥们你TG号怎么没了（）

**Comment by chise0713** [comment]
@Fangliding ~~杜叔叔发威了，这次死了的是我第七个号，不想玩 tg 了~~

**Comment by chise0713** [comment]
> @Fangliding ~杜叔叔发威了，这次死了的是我第七个号，不想玩 tg 了~

来个人搭个 matrix 桥我就能复活了（

**Comment by Fangliding** [comment]
@chise0713 免费那个太拉了 我得问问我朋友能不能借过来用用

**Comment by chise0713** [comment]
@Fangliding 谢谢喵！~~（先谢了再说~~

**Comment by Fangliding** [comment]
> @Fangliding 谢谢喵！~（先谢了再说~

弄完了 可以pm我 @fangliding:matrix.org 拉进来

**Comment by chise0713** [comment]
> > @Fangliding 谢谢喵！~（先谢了再说~
> 
> 弄完了 可以pm我 @fangliding:matrix.org 拉进来

gh 这个自动大写@有点碍事（

**Comment by yuhan6665** [comment]
No plan. Complex config should use API
