### ISSUE TITLE
xray配置了443端口，但443没有被监听

### ISSUE THREAD

**Issue by weiming7335** [XTLS/Xray-core#3093]
防火墙：
Status: active

To                         Action      From
--                         ------      ----
22/tcp                     ALLOW       Anywhere                  
Nginx Full                 ALLOW       Anywhere                  
22/tcp (v6)                ALLOW       Anywhere (v6)             
Nginx Full (v6)            ALLOW       Anywhere (v6) 

xray :config.json配置
。。。
"inbounds": [
    {
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "***", // 填写你的 UUID
            "flow": "xtls-rprx-vision",
            "level": 0,
            "email": "vpsadmin@yourdomain.com"
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "dest": 8080 // 默认回落到防探测的代理
          }
        ]
      },
。。。

xray 是启动的
    xray.service - Xray Service
     Loaded: loaded (/etc/systemd/system/xray.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/xray.service.d
             └─10-donot_touch_single_conf.conf
     Active: active (**running**) since Mon 2024-03-04 05:35:35 UTC; 5h 17min ago

nginx配置

    server {
                listen 80;
                server_name ***;
                return 301 https://$http_host$request_uri;

        }
        server {
           listen 127.0.0.1:8080;
           root /home/vpsadmin/www/webpage;
           index index.html;
           add_header Strict-Transport-Security "max-age=63072000" always;
        }

运行 sudo ss -tuln | grep 443 没有内容显示

**Comment by xqzr** [comment]
```shell
sudo ss -tlnp | grep 443
```

**Comment by Fangliding** [comment]
lsof -i:443
