### ISSUE TITLE
建议：支持多组连接观测模块

### ISSUE THREAD

**Issue by Yochee** [XTLS/Xray-core#3094]
场景：我有一台香港的vps，一台美国的vps，我希望中日韩新澳的ip走hk，其它墙外ip走us，但为了提高可用性我希望他们互为备份。
解决方案：创建两个连接观测模块，一个probe我香港vps的伪装网站，一个probe我美国vps的伪装网站，并用这两个连接观测配合leastPing来决定优先级。
目前observatory不支持数组，无法做到这一点

**Comment by yuhan6665** [comment]
写两个balancer共用observatory然后给不同的costs？

**Comment by Yochee** [comment]
> 写两个balancer共用observatory然后给不同的costs？

现在balancer有cost这个参数么？而且我的想法是通过测服务器本身的延迟来决定优先级（probe香港服务器，绕美国肯定慢，反之同理），只用observatory实现不了

**Comment by Yochee** [comment]
经过一通研究发现balancer里的fallback功能就能满足这个需求，但是目前strategy是leastping的时候fallback不工作，希望未来能修改

**Comment by nftbty** [comment]
> 经过一通研究发现balancer里的fallback功能就能满足这个需求，但是目前strategy是leastping的时候fallback不工作，希望未来能修改

因为**fallback**是添加`leastLoad`策略时新增的。看源代码，其他策略只有`random`有添加**fallback**支持，`leastPing`和`roundRobin`都还不支持 `fallback`这个参数，估计是漏掉了，就下面这段：
https://github.com/XTLS/Xray-core/blob/9b5c3f417eefbad79b9f761a0682498f3d03155f/app/router/config.go#L124-L165

**Comment by RPRX** [comment]
@yuhan6665 加一下应该不难，加了就发 189 吧，~~好想要这个版本~~

**Comment by Fangliding** [comment]
> @yuhan6665 加一下应该不难，加了就发 189 吧，~好想要这个版本~

有点必要的 还没发布的内容包括了一个新的底层传输和安全更新
