### ISSUE TITLE
Splice won't apply to Android.

### ISSUE THREAD

**Issue by rurirei** [XTLS/Xray-core#31]
#6 goos=android for Android is needed.
https://github.com/XTLS/Xray-core/blob/16544c18aba5594be57f588c7d7f5ed294940e22/infra/conf/vless.go#L172-L175

**Comment by rurirei** [comment]
build variant recommended in addition as
```go
// +build linux,!android

// +build android
```

**Comment by rprx** [comment]
（该问题已在此 issue 前解决，请看代码

**Comment by rprx** [comment]
（但还是要感谢反馈，v1.1.1 已 pre-release，稍后补充详细的 release note，含 v1.1.0

**Comment by rurirei** [comment]
i think it should worked without test on Android (build passed.).

**Comment by rurirei** [comment]
it should works without my test on Android (build passed).

**Comment by rurirei** [comment]
@rprx could you add [my repo](https://github.com/rurirei/kitsunebi/tree/release_xtls) to tag Android client of README?

**Comment by rprx** [comment]
@rurirei 

https://github.com/XTLS/Xray-core/commit/decb012f9d94d31ac7fc75c18d6e36eb3d0abd2b 已添加，建议适当修改主分支的说明

**Comment by rprx** [comment]
@rurirei 

https://github.com/XTLS/Xray-core/commit/decb012f9d94d31ac7fc75c18d6e36eb3d0abd2b 已添加，请适当修改各分支和 releases 的说明（因为目前有些地方不符合实际情况）

**Comment by rurirei** [comment]
ok. i'll update those later.

**Comment by rurirei** [comment]
> @rurirei
> 
> [decb012](https://github.com/XTLS/Xray-core/commit/decb012f9d94d31ac7fc75c18d6e36eb3d0abd2b) 已添加，请适当修改各分支和 releases 的说明（因为目前有些地方不符合实际情况）

latest app released.

explaination for what, what else need to do?
