### ISSUE TITLE
Splice cause low usage report and can not be turned off

### ISSUE THREAD

**Issue by MK0ltra** [XTLS/Xray-core#3100]
So problem is, All versions of Xray after 1.8.4 have problem with user stats, usage reports are lower than actual so i can't update to latest version and stuck on 1.8.4. Also i've set `xray.buf.splice=disable` in env so i can turn off splice but i still see `CopyRawConn splice` in logs so this option is not working.

Should i change all CanSpliceCopy to value of 3 and then compile the code, Is this gonna work? There's also hard-coded values here:
https://github.com/XTLS/Xray-core/blob/6991c119e7551b3b19935fc3169da2dfb7be439b/proxy/vless/encoding/encoding.go#L185

**Comment by MK0ltra** [comment]
related issues to splice: https://github.com/XTLS/Xray-core/issues/2883 https://github.com/XTLS/Xray-core/issues/1671

**Comment by RPRX** [comment]
@yuhan6665 这里可能是没给另一边 counter 加，我们把它和 https://github.com/XTLS/Xray-core/issues/3058 修了后发 v1.8.9 吧，等下我更新下分享链接标准

**Comment by RPRX** [comment]
@yuhan6665 https://github.com/XTLS/Xray-core/discussions/716 已更新。你修一下这个 issue 和 https://github.com/XTLS/Xray-core/issues/3058 （启动时跑一下检测就行），我修一下 https://github.com/XTLS/Xray-core/issues/2248 和 https://github.com/XTLS/Xray-core/issues/3101

**Comment by yuhan6665** [comment]
嗯。。测了一下客户端和服务器的 inbound outbound splice 都没有问题 ~~当然流量统计是滞后的~~
另外 xray.buf.splice=disable 只能用来关闭服务端的 splice 应该也是没有问题的
