### ISSUE TITLE
[REQ] TCP HTTP Templates for WS

### ISSUE THREAD

**Issue by fodhelper** [XTLS/Xray-core#3110]
TCP HTTP Request & Response Templates are great
Multiple Host, Path, Headers + Randomization at runtime. It's best
Please set same Templates for WebSocket

**Comment by Fangliding** [comment]
Xray does not support randomization of these parameters
HttpHeaderObject is too old and from the current perspective, the design is not perfect, not recommended for use

**Comment by fodhelper** [comment]
>> Xray does not support randomization of these parameters

So this does not work? But still can send a random to each user after subscription update and that's good too
![image](https://github.com/XTLS/Xray-core/assets/41063376/a0ecdcf4-f52f-4e16-b706-5da4ea78bab5)
>> HttpHeaderObject is too old and from the current perspective, the design is not perfect, not recommended for use

Is there any better alternative? From current Transports of Xray, this one is the best and the most complex one
