### ISSUE TITLE
求助：vless+xtls回落报“failed to fallback request payload”错误

### ISSUE THREAD

**Issue by wingarcher** [XTLS/Xray-core#3113]
两台服务器都是ubuntu22.04,协议都是vless+xtls，其中dmit回落正常，rn的回落异常，客户端是ssrplus最新编译版本。
即使我把rn上的nginx和xray配置文件都修改成dmit上得一样，同样出现了回落失败问题。

1）通过xray的日志发现，dmit收到的报文为：
2024/03/05 15:29:34 [Info] [1598556121] proxy/vless/inbound: fallback starts > proxy/vless/encoding: invalid request version
2024/03/05 15:29:34 [Info] [1598556121] proxy/vless/inbound: realName = sc.******.top
2024/03/05 15:29:34 [Info] [1598556121] proxy/vless/inbound: realAlpn = 
2024/03/05 15:29:34 [Info] [2067403968] proxy/vless/inbound: firstLen = 458
2024/03/05 15:29:34 [Info] [2067403968] proxy/vless/inbound: fallback starts > proxy/vless/encoding: invalid request version

2） rn收到的报文为：
2024/03/05 15:05:38 [Info] [844578511] proxy/vless/inbound: firstLen = 148
2024/03/05 15:05:38 [Info] [844578511] proxy/vless/inbound: fallback starts > proxy/vless/encoding: invalid request version
2024/03/05 15:05:38 [Info] [844578511] proxy/vless/inbound: realName = th.******.top
2024/03/05 15:05:38 [Info] [844578511] proxy/vless/inbound: realAlpn = h2
2024/03/05 15:05:38 [Info] [844578511] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > read tcp ******:443->******:38028: use of closed network connection

3）nginx版本是一样的：
nginx version: nginx/1.18.0 (Ubuntu)
built with OpenSSL 3.0.2 15 Mar 2022
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -ffile-prefix-map=/build/nginx-zctdR4/nginx-1.18.0=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -Wl,-z,now -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-compat --with-debug --with-pcre-jit --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --add-dynamic-module=/build/nginx-zctdR4/nginx-1.18.0/debian/modules/http-geoip2 --with-http_addition_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_sub_module

4）xray
dmit上是 1.8.4
rn上是 1.8.8

5) 附件截图为xray和nginx的截图
![xray](https://github.com/XTLS/Xray-core/assets/134398957/e67ee49c-dfdf-43e5-9778-c897d61a1060)

**Comment by zxbiao** [comment]
大概是alpn传递的问题，估计是和两端的Xray-core版本不一致的原因。
还有，排除过程应该是全部版本一致才是，环境的差异作为唯一变量才能体现出故障点的所在。

**Comment by wingarcher** [comment]
最终在rn的服务器上，服务端限定了"http/1.1"，回落就正常了,具体如下：
"alpn":["http/1.1"]
谢谢大佬指点！！
