### ISSUE TITLE
xray支持 L2TP,PPTP, L2TP over IPSec 这三种协议吗？

### ISSUE THREAD

**Issue by cppbeliever** [XTLS/Xray-core#3122]
xray支持 L2TP,PPTP, L2TP over IPSec 这三种协议吗？

**Comment by Fangliding** [comment]
@cppbeliever 不支持

**Comment by cppbeliever** [comment]
@Fangliding  谢谢

**Comment by ZqinKing** [comment]
> xray支持 L2TP,PPTP, L2TP over IPSec 这三种协议吗？

这些都该淘汰了，延迟高、速度慢、配置复杂。

**Comment by MrSaeid007** [comment]
> @cppbelieverNot supported

Hi @Fangliding Can you send a PR to xray-core about adding l2tp & pptp?
Maybe they accept this PR.

**Comment by RPRX** [comment]
> Maybe they accept this PR.

不会合并
