### ISSUE TITLE
文档 "StreamSettingsObject" "network" 应添加 “httpupgrade” 选项

### ISSUE THREAD

**Issue by Jason-2048** [XTLS/Xray-core#3124]
[xray](https://xtls.github.io/config/transport.html#streamsettingsobject)
参照 [v2fly](https://www.v2fly.org/v5/config/stream.html#%E6%94%AF%E6%8C%81%E7%9A%84%E4%BC%A0%E8%BE%93%E6%B5%81%E5%8D%8F%E8%AE%AE)

**Comment by Fangliding** [comment]
https://github.com/XTLS/Xray-docs-next/pull/484
