### ISSUE TITLE
VLESS TCP XTLS HTTPS 配置问题

### ISSUE THREAD

**Issue by zhqtoo** [XTLS/Xray-core#313]
HI 大家好，
  按照之前在Github 上找到的配置文件配置了，VLESS 443 端口进 然后 进程回落到Nginx ，Nginx听进程并且开启了PROXY protocol发送，网站用的WordPress，解析没有问题，可是没办法完全HTTPS，也设置了HTTP跳转HTTPS，现在打开网站是显示的混合内容，不能完全HTTPS，XRAY使用没有问题，就是网址没办法完全HTTPS，火狐浏览器显示不安全，有混合内容，不知道哪位大神可以帮忙看看，
万分感谢。
NGINX的配置文件如下：
server
{
    listen 80;
    return 301 https://$host$request_uri;
}
server
{   
    listen unix:/dev/shm/h2c.sock http2 proxy_protocol;
    listen unix:/dev/shm/h1.sock proxy_protocol;
    set_real_ip_from 127.0.0.1;  
    index index.php index.html index.htm default.php default.htm default.html;
    root /www/webfiles/;

XRAY 配置文件如下：
{
  "log": {
    "loglevel": "warning",
    "error": "/var/log/xray/error.log", 
    "access": "/var/log/xray/access.log" 
  },
    "inbounds":[
     {
         "port": 443, 
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 
            "flow": "xtls-rprx-direct", 
            "level": 0
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "alpn": "h2", 
            "dest": "/dev/shm/h2c.sock", 
            "xver": 1 
          },
          {
            "alpn": "http/1.1",
            "dest": "/dev/shm/h1.sock", 
            "xver": 1 
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls", 
        "xtlsSettings": { 

          "alpn":["h2","http/1.1" ],
          "minVersion": "1.2",
          "preferServerCipherSuites": true,
          "cipherSuites": "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
          "certificates": [
            {
              "ocspStapling": 3600, 

            }
          ]
        }
      }
    }
  ],
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "ip": ["geoip:private"],
        "outboundTag": "blocked"
      }
    ]
  },
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "blocked",
      "protocol": "blackhole",
      "settings": {}
    }
  ]
}

**Comment by cwyin7788** [comment]
> HI 大家好，
> 按照之前在Github 上找到的配置文件配置了，VLESS 443 端口进 然后 进程回落到Nginx ，Nginx听进程并且开启了PROXY protocol发送，网站用的WordPress，解析没有问题，可是没办法完全HTTPS，也设置了HTTP跳转HTTPS，现在打开网站是显示的混合内容，不能完全HTTPS，XRAY使用没有问题，就是网址没办法完全HTTPS，火狐浏览器显示不安全，有混合内容，不知道哪位大神可以帮忙看看，网址是
> https://www.playerzhq.com
> 万分感谢。
> NGINX的配置文件如下：
> server
> {
> listen 80;
> server_name playerzhq.com [www.playerzhq.com](http://www.playerzhq.com);
> return 301 https://$host$request_uri;
> }
> server
> {
> listen unix:/dev/shm/h2c.sock http2 proxy_protocol;
> listen unix:/dev/shm/h1.sock proxy_protocol;
> set_real_ip_from 127.0.0.1;
> server_name playerzhq.com [www.playerzhq.com](http://www.playerzhq.com);
> index index.php index.html index.htm default.php default.htm default.html;
> root /www/webfiles/playerzhq.com;
> 
> XRAY 配置文件如下：
> {
> "log": {
> "loglevel": "warning",
> "error": "/var/log/xray/error.log",
> "access": "/var/log/xray/access.log"
> },
> "inbounds":[
> {
> "port": 443,
> "protocol": "vless",
> "settings": {
> "clients": [
> {
> "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
> "flow": "xtls-rprx-direct",
> "level": 0
> }
> ],
> "decryption": "none",
> "fallbacks": [
> {
> "alpn": "h2",
> "dest": "/dev/shm/h2c.sock",
> "xver": 1
> },
> {
> "alpn": "http/1.1",
> "dest": "/dev/shm/h1.sock",
> "xver": 1
> }
> ]
> },
> "streamSettings": {
> "network": "tcp",
> "security": "xtls",
> "xtlsSettings": {
> "serverName": "playerzhq.com",
> "alpn":["h2","http/1.1" ],
> "minVersion": "1.2",
> "preferServerCipherSuites": true,
> "cipherSuites": "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
> "certificates": [
> {
> "ocspStapling": 3600,
> "certificateFile": "/home/ssl/playerzhq/fullchain.pem",
> "keyFile": "/home/ssl/playerzhq/playerzhq.key"
> }
> ]
> }
> }
> }
> ],
> "routing": {
> "domainStrategy": "IPIfNonMatch",
> "rules": [
> {
> "type": "field",
> "ip": ["geoip:private"],
> "outboundTag": "blocked"
> }
> ]
> },
> "outbounds": [
> {
> "protocol": "freedom",
> "settings": {}
> },
> {
> "tag": "blocked",
> "protocol": "blackhole",
> "settings": {}
> }
> ]
> }

不明白「不能完全HTTPS」的意思，是這個問題嗎？Xray的回落遇上WP就會這樣

https://github.com/XTLS/Xray-core/issues/243#issuecomment-778533838

**Comment by zhqtoo** [comment]
> 
> 
> 不明白「不能完全HTTPS」的意思，是這個問題嗎？Xray的回落遇上WP就會這樣
> 
> [#243 (comment)](https://github.com/XTLS/Xray-core/issues/243#issuecomment-778533838)

你打开我的网站就知道了，显示的是混合内容，可以正常解析网站，网站是HTTPS 打开的，但是有内容是HTTP的所以会这样，不知道得哪里去调整设置才能正常了

**Comment by cwyin7788** [comment]
> > 不明白「不能完全HTTPS」的意思，是這個問題嗎？Xray的回落遇上WP就會這樣
> > [#243 (comment)](https://github.com/XTLS/Xray-core/issues/243#issuecomment-778533838)
> 
> 你打开我的网站就知道了，显示的是混合内容，可以正常解析网站，网站是HTTPS 打开的，但是有内容是HTTP的所以会这样，不知道得哪里去调整设置才能正常了，你发的那个我看了，那个fastcgi的配置我也有加过之前，问题依旧，打开网站还是显示的是混合内容，谢谢了

那就是上面回覆你的#243問題了

**Comment by zhqtoo** [comment]
> 
> 
> > > 不明白「不能完全HTTPS」的意思，是這個問題嗎？Xray的回落遇上WP就會這樣
> > > [#243 (comment)](https://github.com/XTLS/Xray-core/issues/243#issuecomment-778533838)
> > 
> > 
> > 你打开我的网站就知道了，显示的是混合内容，可以正常解析网站，网站是HTTPS 打开的，但是有内容是HTTP的所以会这样，不知道得哪里去调整设置才能正常了，你发的那个我看了，那个fastcgi的配置我也有加过之前，问题依旧，打开网站还是显示的是混合内容，谢谢了
> 
> 那就是上面回覆你的#243問題了
> 
> 看了，把你的網站刪除吧

那个我进去看了，我的不是乱码，我单独有个配置问价加了相应的配置，我的情况是网站是HTTPS的，进去以后有内容是HTTP的，所以火狐这类浏览器就显示不安全，用IE可以正常显示，没有乱码的问题，我另外个配置文件有这些内容，我用的是宝塔，有好几个配置文件套在里面，还是非常感谢
location /
{
	 try_files $uri $uri/ /index.php?$args;
}

rewrite /wp-admin$ $scheme://$host$uri/ permanent;
 
 location ~ \.php$ {
        try_files $uri =404;
        fastcgi_index index.php;
        fastcgi_pass unix:/tmp/php-cgi-74.sock;
        include fastcgi_params;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        fastcgi_param  SERVER_PORT	443;
        fastcgi_param  HTTPS		"on";
    }

**Comment by cwyin7788** [comment]
我用自己的wp截圖，我剛才看到你的網站，就像這樣：

圖 1.)

<img width="1044" alt="截圖 2021-02-27 下午8 57 16" src="https://user-images.githubusercontent.com/53026952/109387882-b960e380-793e-11eb-8b5b-a068b0acb099.png">

而正常是應該這樣的：

圖 2.)

<img width="1041" alt="截圖 2021-02-27 下午8 57 59" src="https://user-images.githubusercontent.com/53026952/109387898-d0073a80-793e-11eb-9bef-e9c4885b68de.png">

你遇上的是第一張圖的問題嗎？如果是的話，那#243確實就是我的解決方法啊。

沒加上fastcgi_param HTTPS "on";就是(圖1.)

加上後，顯示就正常了(圖2.)

而我剛才看你的網站，確實是出現(圖1.)的問題，但我沒有截圖。

(我是用firefox截圖的)

**Comment by JimhHan** [comment]
非Xray的问题，Close。

在此感谢对于Xray的支持，请在提问之前查询资料与已有的issue，谢谢配合。

**Comment by zhqtoo** [comment]
不是图一的问题，看下来感觉有可能是进程回落会有问题，端口回落就可以
![图片](https://user-images.githubusercontent.com/79741547/109412468-1f9f4200-79e3-11eb-8fd7-bb67c3d8464b.png)
![图片](https://user-images.githubusercontent.com/79741547/109412479-29c14080-79e3-11eb-8121-43679a354c15.png)
![图片](https://user-images.githubusercontent.com/79741547/109412485-35146c00-79e3-11eb-81af-c98f867e44bb.png)
![图片](https://user-images.githubusercontent.com/79741547/109412494-3ba2e380-79e3-11eb-8b12-184240ed73cd.png)
![图片](https://user-images.githubusercontent.com/79741547/109412501-43628800-79e3-11eb-9b16-4ddaf310fafd.png)

**Comment by cwyin7788** [comment]
> 不是图一的问题，看下来感觉有可能是进程回落会有问题，端口回落就可以，那个配置我加了，宝塔里有INCLUD 某个配置，那个配置我之前发了，包括你提到的那个配置，那个配置是有的，十分感谢,另外问下，群聊是在哪里？

安裝telegram，然後在手機瀏覽器輸入下圖的網址就可以了，在群裡再聊吧。

![EDA3CAAA-11CF-4659-8ECB-C5A5CB043DDD](https://user-images.githubusercontent.com/53026952/109412814-144d1600-79e5-11eb-874b-a9bf0cdd79ed.jpeg)

**Comment by zhqtoo** [comment]
好的，太感谢了

**Comment by andy7z** [comment]
我也遇到过这个问题, 前端xray 监听443端口, 回落到Nginx的80. 对于xray与Nginx之间的连接为http连接 (你这是sock应该差不多意思, 我没看懂) , 所以对Nginx而言这就是一个http连接, 网站 (WP) 也会认为这是一个http连接, 所以返回页面内的link地址也是http的 (如果返回相对地址url就好了) , 所以, 对于客户端浏览器而言, 收到的是https的网站内夹杂http的link, 自然会认为是不安全的. 我用的typecho博客, 有参数可以配置强制启用https, wp应该也有类似的设置方法
