### ISSUE TITLE
REALITY POLICY

### ISSUE THREAD

**Issue by AnnaPetrovaWer** [XTLS/Xray-core#3132]
亲爱的朋友们，大家好！
如果我现在只使用REALITY和最新的1.8.9内核，设置policy值还有意义吗？
如果有，为什么需要这么做？

```json
"policy": {
    "levels": {
        "0": {
            "handshake": 2,
            "connIdle": 120
        }
    }
}
```

**Comment by chika0801** [comment]
"handshake": 2, "connIdle": 120
            "connIdle": 120

Deze 2 parameters bestaan al heel lang en we hebben ze niet expres veranderd. Ze hebben een standaardwaarde als ze niet worden geschreven.

Op een dag zei RPRX in een antwoord, waarschijnlijk half gekscherend, dat het mogelijk is dat Chinese firewalls erop vertrouwen dat iedereen dezelfde timeout-responstijd heeft om een aspect van de functie te krijgen.

Pas nadat ik die opmerking had gelezen, heb ik een andere waarde ingesteld dan de standaardwaarde in de configuratie van sommige VPS'en die ik gebruik.

Of het nu waar is of niet, het maakt niet zoveel meer uit. De geschiedenis van deze parameter is hoe hij is ontstaan.

Vertaald met DeepL.com (gratis versie)
