### ISSUE TITLE
REALITY SHORTID

### ISSUE THREAD

**Issue by AnnaPetrovaWer** [XTLS/Xray-core#3133]
亲爱的朋友们！
我想问一下，现在在REALITY中使用SHORTID参数有多重要？

我用包跟踪器测试了流量，看看使用short_id有没有什么不同，但我没有发现任何对我有用的线索。

我想知道，这个参数在交互的哪个阶段被使用？

**Comment by chika0801** [comment]
SHORTID

Deze parameter werd door een vriend in China gevraagd toen het REALITY voorbeeld werd uitgebracht op welke scenario's het effect zou hebben.

RPRX heeft het er in sommige berichten over. De post die er voor mij uitsprong was toen de Iraanse netizen een situatie rapporteerden en RPRX antwoordde met zijn mening, ik kan de link naar die post niet meer vinden.

Mijn mening over het belang van deze parameter is minder belangrijk. Ik heb bijvoorbeeld een VPS voor 5 vrienden om me heen en ik gebruik dezelfde set SHORTID parameters.


Vertaald met DeepL.com (gratis versie)

**Comment by AnnaPetrovaWer** [comment]
我看到RPRX的一条信息，他写道：
[COMMENT](https://github.com/XTLS/Xray-core/issues/2059#issuecomment-1543724596)
建议为每个人分配不同的ShortID，如果客户端配置泄露了，有助于找出谁是内鬼，这就是ShortID存在的意义。

但是我对GO语言的了解不足，无法理解我们在代码的哪个部分和阶段处理这个值？

在看到这条信息之前，我以为授权是通过UUID进行的。

我们如何传递SHORTID？你能帮我弄清楚吗？

**Comment by AnnaPetrovaWer** [comment]
我想感谢您帮助我理解并回答我的愚蠢问题！❤️🤝

**Comment by AnnaPetrovaWer** [comment]
我是否正确理解，shortid在TLS握手过程中被包含在SessionId中，并为每个会话添加了一个独特的标识符？
从逻辑上讲，这种SessionId的变化使会话更加独特，可以用于提供额外的安全性或混淆，以及在特定的安全逻辑或会话管理上下文中识别会话。
但是，SessionId的长度是有限制的，对吗？

**Comment by us254** [comment]
- The ShortID is used during the TLS handshake to uniquely identify the session. It is included as part of the `SessionId`.
- The ShortID is passed as a hexadecimal string in the configuration and is decoded into a byte array of length 8.
- The purpose of the ShortID is to provide additional security and obfuscation by making the session more unique. It can also be used to identify the session in a specific security logic or session management context.
- There is a limit to the length of the SessionID, and the ShortID is typically 8 bytes long.
