### ISSUE TITLE
Disable Invalid url warning

### ISSUE THREAD

**Issue by NBogos** [XTLS/Xray-core#3136]
Hello guys! Vless-xtls-reality. If I connect to external ip of my x-ray server without domain, i.e https://x.x.x.x:443, I get  "Invalid URL
The requested URL "[no URL]", is invalid" with right certificate of the real site I chose. Is there a way to disable this warning or replace it to my own page ?

**Comment by chika0801** [comment]
https://github.com/chika0801/Xray-examples/blob/main/VLESS-Vision-REALITY/config_server.json

Let's say you build a simple REALITY server using the configuration in the link.

You type https://VPS IP:443 in the client's browser and you get an error message. This is a normal occurrence.

If you are asking questions about this situation, don't worry about it.

The usual way you would want to test this is to change the host file on the client side, and put the URL that you put in the dest in your server side configuration, corresponding to the IP of your VPS.

Restart your browser and enter the url in dest to display the website content.

Translated with DeepL.com (free version)

**Comment by NBogos** [comment]
Yeah, I want to change it to my own error page like as you could do it in squid or nginx, or remove it completely so non authorised users wouldn't see xray's default no url error.

**Comment by chika0801** [comment]
You should not be able to change this error message using VLESS-Vision-REALITY. Nor is it the cause of your server being blocked by your country's firewall.

You can try a combination of forms inside VLESS-Vision-REALITY that we call Steal Your Own, which you can learn about first.

**Comment by NBogos** [comment]
Ok got you.
