### ISSUE TITLE
REALITY FALLBACK

### ISSUE THREAD

**Issue by AnnaPetrovaWer** [XTLS/Xray-core#3137]
好的，午安！
尊敬的朋友们，目前需要在一个端口上组织多个协议 VLESS TCP REALITY + VLESS GRPC TLS 的存在。
从安全性和效率的角度来看，更正确的组织这种工作模式是什么？我想将 REALITY 设置在 443 端口上，其余的则通过 fallback 或其他方式。
不太想使用 nginx/haproxy，但如果没有其他办法的话……
如果您有时间和机会分享经验，我将不胜感激。

**Comment by mclovin-2k** [comment]
VLESS TCP REALITY + VLESS GRPC REALITY 可以通过 fallback 实现。
但是 VLESS TCP REALITY + VLESS GRPC TLS 只能通过 nginx/haproxy 了。

**Comment by chika0801** [comment]
https://github.com/chika0801/Xray-examples/blob/main/VLESS-gRPC-REALITY/config_server_shared_port.json

If you want VLESS-TCP-VISION-REALITY VLESS-gRPC-REALITY to share port 443, you can refer to this configuration file.

It is not recommended that you learn other N configurations in one, my personal preference is to keep it simple .

**Comment by AnnaPetrovaWer** [comment]
> https://github.com/chika0801/Xray-examples/blob/main/VLESS-gRPC-REALITY/config_server_shared_port.json
> 
> 
> 
> If you want VLESS-TCP-VISION-REALITY VLESS-gRPC-REALITY to share port 443, you can refer to this configuration file.
> 
> 
> 
> It is not recommended that you learn other N configurations in one, my personal preference is to keep it simple .

您好！
感谢您的回复和您宝贵的时间，我的亲爱的朋友！
请问这种配置方案的安全性如何？
据我所知，建议将grpc与某种nginx一起使用
还是我理解错了？

**Comment by chika0801** [comment]
https://github.com/chika0801/Xray-examples

For use in mainland China. I don't recommend using VLESS-WebSocket_or_HTTPUpgrade-TLS in the combinations listed in the link above.

Refer to the link https://github.com/chika0801/Xray-examples/blob/main/warning.md#memo-5 for the reason.

I have personally observed that when using XXX+WS+TLS, some Chinese forums such as hostloc report blocked ports. I'm not sure if using XXX+WS+TLS with Mux can reduce the chance of port blocking.

I list XXX+WS/HTTPupgrade+TLS only as a configuration demonstration.

What combination you use to make your VPS's ports less likely to be blocked by your country's firewall though in not mainland China requires your own experimentation.
