### ISSUE TITLE
Request for Community Chat Room Creation and Bridge with Existing Telegram Channel

### ISSUE THREAD

**Issue by Sortnz** [XTLS/Xray-core#3139]
Hello Community Team,

I am reaching out to kindly request the creation of a Matrix chat room for our community. Additionally, it would be greatly beneficial if this new chat room could be bridged with our existing Telegram channel.

The integration between Matrix and Telegram would foster a more unified and seamless communication experience for our community members who prefer different platforms. I believe this would significantly enhance our community's interaction and collaboration.

For your convenience, a free bridging service is available at [t2bot](https://t2bot.io/telegram), which provides a straightforward setup process. I am confident that this service would meet our needs without incurring additional costs.

Thank you very much for considering this request. I am looking forward to your positive response and am available to assist with the setup process if needed.

**Comment by chise0713** [comment]
Are you looking for #projectXray:matrix.org ?

**Comment by Fangliding** [comment]
We already have one #projectXray:matrix.org
Contact our telegram group admin to get an invitation
