### ISSUE TITLE
mux多路复用问题

### ISSUE THREAD

**Issue by liliang233** [XTLS/Xray-core#3142]
提一个小问题，不知道其他人有没有遇到过

场景：两台服务器，一台是中转，一台是落地出口，在中转机的outbound上做了一下配置

      "mux": {
               "enabled": true,
               "concurrency": 1024,
               "xudpConcurrency": 1024,
               "xudpProxyUDP443": "skip"
             },

不管协议是走socks5  vless 还是vmess 都会偶发证书错误的情况，例如apple的域名到google的ip，已经排查了dns污染（国内外全自建dns，并且实现分流）

而且我把上面两个并发调小，还是会有问题 ，关掉才不复现。

能否基于域的mux，是否走h2就能解决类似的问题？

**Comment by us254** [comment]
To use domain-based MUX and h2 in Go to solve the certificate error issue, you can modify the Xray configuration and code as follows:

1. In the Xray configuration, enable MUX and set `xudpProxyUDP443` to `"skip"`:

```json
"mux": {
  "enabled": true,
  "concurrency": 1024,
  "xudpConcurrency": 1024,
  "xudpProxyUDP443": "skip"
}
```

2. In the `infra/conf/xray.go` file, update the `MuxConfig` struct and `Build` function:

```go
type MuxConfig struct {
  Enabled         bool   `json:"enabled"`
  Concurrency     int16  `json:"concurrency"`
  XudpConcurrency int16  `json:"xudpConcurrency"`
  XudpProxyUDP443 string `json:"xudpProxyUDP443"`
}

func (m *MuxConfig) Build() (*proxyman.MultiplexingConfig, error) {
  if m.Concurrency < 0 {
    return nil, newError("invalid mux concurrency: ", m.Concurrency)
  }
  if m.XudpConcurrency < 0 {
    return nil, newError("invalid mux xudp concurrency: ", m.XudpConcurrency)
  }

  switch m.XudpProxyUDP443 {
  case "reject", "allow", "skip":
  default:
    return nil, newError(`unknown "xudpProxyUDP443" value: `, m.XudpProxyUDP443)
  }

  return &proxyman.MultiplexingConfig{
    Enabled:         m.Enabled,
    Concurrency:     uint32(m.Concurrency),
    XudpConcurrency: uint32(m.XudpConcurrency),
    XudpProxyUDP443: m.XudpProxyUDP443,
  }, nil
}
```

3. In the `app/proxyman/outbound/handler.go` file, update the `NewHandler` function to set the `XudpProxyUDP443` field:

```go
func NewHandler(ctx context.Context, config *proxyman.OutboundHandlerConfig) (outbound.Handler, error) {
  // ...

  h.udp443 = config.XudpProxyUDP443

  // ...
}
```

4. Use domain-based MUX by setting the target address to a domain like `"v1.mux.cool"` when creating outbound connections. For example, in `proxy/vmess/outbound/outbound.go`:

```go
if target.Address.Family().IsDomain() && target.Address.Domain() == "v1.mux.cool" {
  command = protocol.RequestCommandMux
}

request := &protocol.RequestHeader{
  Command: command,
  Address: target.Address,
  Port:    target.Port,
}
```

5. Enable h2 in the outbound `streamSettings` configuration:

```json
"streamSettings": {
  "network": "tcp",
  "security": "tls",
  "tlsSettings": {
    "serverName": "example.com"
  },
  "httpSettings": {
    "path": "/path",
    "host": [
      "example.com"
    ]
  }
}
```

By making these changes, Xray will use domain-based MUX and h2 for outbound connections, which should help mitigate the certificate error issue. The `xudpProxyUDP443` setting is set to `"skip"` to avoid using MUX for UDP/443 traffic.
