### ISSUE TITLE
Listen to no port (Disable Inbound)

### ISSUE THREAD

**Issue by APT-ZERO** [XTLS/Xray-core#3145]
Hello
Please add option to make an Inbound to Listen to no port (by setting Port to '-1' for example)
It's good for when we want to temporary Disable an Inbound without removing it
Or for Client designs like :
https://github.com/2dust/v2rayN/issues/4745#issuecomment-2002022186

**Comment by vrnobody** [comment]
I downvote this idea.

Firstly, unused inbound could be commented out.
```json
{
  "inbounds":[
    /* {
      ...
    }, */
    ...
  ],
  ...
}
```

Secondly, import a complete config from subscription is a bad idea. Bad guys can take advantage of  [reverse feature](https://www.v2fly.org/config/reverse.html) to expose local ports (e.g. 22, 3389) to the public network. (Sorry I can not find the English manual of this feature). This could be a security risk.

**Comment by vrnobody** [comment]
For the first part, you are talking about standards and I am talking about reality (literally). You can use comments in the configuration of xray-core.

For the second part, I just used reverse as an example. Bad guys can take advantage of other configuration items, but I do not intend to discuss the details.

**Comment by vrnobody** [comment]
You are thinking in the wrong direction. A safe approach is to use a whitelist, which only accept necessary and safe configuration items. No matter how good your blacklist is, it can only write down already exists configuration items. Xray-core is continuously updating, new unsafe configuration items will appear in the future.

To your question, yes there are. But your list is good enough to prove that import the entire configuration from subscription is a bad idea. If you are just importing the configuration locally, that is totally fine.
