### ISSUE TITLE
proto貌似没有完整的配置？

### ISSUE THREAD

**Issue by SoHugePenguin** [XTLS/Xray-core#3150]
我想要通过proto多语言做个接口来实现添加出入站。
我主要使用 vless+tls+reality
但是我发现好像proto的api代码生成只能添加基本的配置？
我看xray.transport.internet.tls.Config 等proto文件是有实现的。
但是添加in和out都没有这些加强类的配置？
不知道是不是我的问题。

      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "tcpSettings": {
          "header": {
            "type": "none"
          },
          "serverName": "",
          "rejectUnknownSni": false,
          "allowInsecure": true,
          "alpn": [
            "h2",
            "http/1.1"
          ],
          "minVersion": "1.2",
          "cipherSuites": "chacha20poly1305",
          "certificates": {
            "ocspStapling": 3600,
            "oneTimeLoading": false,
            "usage": "encipherment",
            "certificateFile": "/penguin/nfs_storage/ssl/fullchain.pem",
            "keyFile": "/penguin/nfs_storage/ssl/privkey.pem"
          },
          "disableSystemRoot": false,
          "enableSessionResumption": false,
          "fingerprint": "",
          "pinnedPeerCertificateChainSha256": [
            ""
          ]
        },
        "realitySettings": {
          "show": false,
          "dest": "",
          "serverNames": [
            "cmin2.aua.lol"
          ],
          "privateKey": "",
          "shortIds": [
            ""
          ]
        }
      },
      
      
      希望能用api方法添加 vless+tls+reality 的出入站来加强安全。

**Comment by Fangliding** [comment]
这部分代码太远古了一直没更新的样子 欢迎pr（）

**Comment by SoHugePenguin** [comment]
> 这部分代码太远古了一直没更新的样子 欢迎pr（）

是这样，我看都四年前五年前了，捂脸

**Comment by SoHugePenguin** [comment]
> tls和reality都是SecuritySettings，应该是二选一的关系。像cipherSuites这些配置项属于tlsSettings，上面贴出的配置放到了tcpSettings里面，会生效吗？

会的，是加成功了，只是代码比较古老所以没有新的那些设置实现。先就这样吧，我也没学过go，主java的。
