### ISSUE TITLE
能不能直接回落到ssh的某一端口，或许gcp shell可以用得到

### ISSUE THREAD

**Issue by Alex-coffen** [XTLS/Xray-core#316]
能不能直接回落到ssh的某一端口，或许gcp shell可以用得到？

**Comment by rprx** [comment]
可以，目前的回落分流都是解 TLS，你需要在客户端配置 SSH over TLS

**Comment by BioniCosmos** [comment]
@rprx 請問 Xray 的回落可以在 L4 上轉發任意 TLS 加密的 TCP 流量是嗎？

**Comment by rprx** [comment]
@BioniCosmos 目前不是这样设计的，不是传统 SNI 分流

**Comment by BioniCosmos** [comment]
所以說，回落的限制是什麼？只能回落到 Xray 入站和 HTTP 伺服器？

除了支持 Xray 的 HTTP VLESS VMess Trojan 入站以外，Dokodemo-door Socks Shadowsocks 是否支持？

**Comment by BioniCosmos** [comment]
@rprx

**Comment by rprx** [comment]
@BioniCosmos 没有限制，不会检查，无脑转发

**Comment by Alex-coffen** [comment]
我baidu了也google了， 都没找到怎么配置ssh over TLS...
