### ISSUE TITLE
how to set mutiple peers in wireguard inbounds?

### ISSUE THREAD

**Issue by lengmo23** [XTLS/Xray-core#3166]
Xray从1.8.6起增加了wireguard的入站协议支持。使用以下配置成功实现入站wireguard协议监听。
```
    "inbounds": [
      {
        "port": 33112,
        "protocol": "wireguard",
        "settings": {
            "secretKey": "[secret key]",
            "peers": [
                {
                    "publicKey": "[public key]",
                    "allowedIPs": [
                        "IP"
                    ]
                }
            ],
            "kernelMode": false,
            "mtu": 1328
        },
        "tag": "wgserver"
    }
    ]
```

但是我想知道如何在同一端口监听多个peer对端？我尝试在peers的[]添加另一对公钥，如下所示：
```
    "inbounds": [
      {
        "port": 33112,
        "protocol": "wireguard",
        "settings": {
            "secretKey": "[secret key]",
            "peers": [
                {
                    "publicKey": "[public key]",
                    "allowedIPs": [
                        "IP"
                    ]
                },
                {
                   "publicKey": "[public key2]",
                   "allowedIPs": [
                       "IP2"
                   ]
                }
            ],
            "kernelMode": false,
            "mtu": 1328
        },
        "tag": "wgserver"
    }
    ]
```
这样配置能够运行，但是peers1和peers2似乎都不能响应。

**Comment by JakATom** [comment]
多peers配置这样配置：

{
  "inbounds": [
    {
      "tag": "wgserver",
      "listen": "127.0.0.1",
      "port": 8388,
      "protocol": "wireguard",
      "settings": {
        "secretKey": "",
        "address": [
          "10.0.0.1"
        ],
        "peers": [
          {
            "publicKey": "=", // peer1 
            "allowedIPs": [
              "10.0.0.3/32"
            ],
        "endpoint": "10.0.0.3:8388"
          },
      {
            "publicKey": "", // peer2
            "allowedIPs": [
              "10.0.0.4/32"
            ],
            "endpoint": "10.0.0.4:8388"
          },
      {
            "publicKey": "",  // peer3
        "allowedIPs": [
              "10.0.0.5/32"
            ],
            "endpoint": "10.0.0.5:8388"
          },
      {
            "publicKey": "",  // peer4
            "allowedIPs": [
                  "10.0.0.6/32"
                ],
            "endpoint": "10.0.0.6:8388"
          }

        ],
        "kernelMode": false,
        "mtu": 1280
      }
    }
    
  ],
  
  "outbounds": [
    {
      "protocol": "freedom",
      "tag": "direct"
    }
  ]
}
