### ISSUE TITLE
HTTPUpgrade Over CDN Problem.

### ISSUE THREAD

**Issue by xdeepsm0kex** [XTLS/Xray-core#3181]
When I try to connect this problem is showing : (VLESS+HttpUpgrade+CDN+noTLS)

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x8627a5]
goroutine 7 [running]:
bufio.(*Writer).Flush(0xc000314100)
	bufio/bufio.go:639 +0x45
net/http.(*Request).write(0xc00014a000, {0x0, 0x0}, 0x0, 0x0, 0x0)
	net/http/request.go:764 +0xbd7
net/http.(*Request).Write(...)
	net/http/request.go:555
github.com/xtls/xray-core/transport/internet/httpupgrade.dialhttpUpgrade({0x1738f80, 0xc0001c29c0}, {{0x1738d88, 0xc0002d95d0}, 0x1f90, 0x2}, 0xc0002e3a40)
	github.com/xtls/xray-core/transport/internet/httpupgrade/dialer.go:56 +0x8be
github.com/xtls/xray-core/transport/internet/httpupgrade.dial({0x1738f80, 0xc0001c29c0}, {{0x1738d88, 0xc0002d95d0}, 0x1f90, 0x2}, 0xc0002e3a40)
	github.com/xtls/xray-core/transport/internet/httpupgrade/dialer.go:78 +0x189
github.com/xtls/xray-core/transport/internet.Dial({0x1738f80, 0xc0001c29c0}, {{0x1738d88?, 0xc0002d95d0?}, 0x95d0?, 0xc0?}, 0x0?)
	github.com/xtls/xray-core/transport/internet/dialer.go:60 +0x1c7
github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dial(0xc0002f0900, {0x1738f80?, 0xc0001c29c0?}, {{0x1738d88, 0xc0002d95d0}, 0x1f90, 0x2})
	github.com/xtls/xray-core/app/proxyman/outbound/handler.go:280 +0xa13
github.com/xtls/xray-core/proxy/vless/outbound.(*Handler).Process.func1()
	github.com/xtls/xray-core/proxy/vless/outbound/outbound.go:85 +0xa6
github.com/xtls/xray-core/common/retry.(*retryer).On(0xc0001b1cb0, 0xc0001b1d40)
	github.com/xtls/xray-core/common/retry/retry.go:27 +0xc6
github.com/xtls/xray-core/proxy/vless/outbound.(*Handler).Process(0xc0002f6510, {0x1738f80, 0xc0001c29c0}, 0xc0003120e0, {0x1736610, 0xc0002f0900})
	github.com/xtls/xray-core/proxy/vless/outbound/outbound.go:82 +0x28e
github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dispatch(0xc0002f0900, {0x1738f80, 0xc0001c29c0}, 0xc0003120e0)
	github.com/xtls/xray-core/app/proxyman/outbound/handler.go:206 +0x3d8
github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc0002cb9e0, {0x1738f80, 0xc0001c29c0}, 0xc0003120e0, {{0x1738d88, 0xc0003000a0}, 0x1bb, 0x2})
	github.com/xtls/xray-core/app/dispatcher/default.go:443 +0xca6
created by github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 6
	github.com/xtls/xray-core/app/dispatcher/default.go:237 +0x4f9

**Comment by Fangliding** [comment]
The release version requires TLS
And we planned to remove it

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/issues/3128
