### ISSUE TITLE
authority

### ISSUE THREAD

**Issue by AnnaPetrovaWer** [XTLS/Xray-core#3184]
大家好，亲爱的朋友们！

我刚开始学习如何处理阻塞的科学，并想向更有经验的同志们询问：
什么是gRPC authority，它如何帮助我们？
非常感谢您的回答。

**Comment by Jimmisama** [comment]
更有经验的同志只有两个，还不打算说

**Comment by RPRX** [comment]
> 更有经验的同志只有两个，还不打算说

~~因为确实是不能说~~

**Comment by chika0801** [comment]
尬住了

**Comment by jarnx** [comment]
> > 更有经验的同志只有两个，还不打算说
> 
> ~~因为确实是不能说~~

Is it because saying it will bring bad consequences?  Like the Great Firewall of China?  Itchy heart.....

**Comment by junlongzzz** [comment]
> > 更有经验的同志只有两个，还不打算说
> 
> ~因为确实是不能说~

~~迪米特法则~~
