### ISSUE TITLE
QUIC Poor Performance

### ISSUE THREAD

**Issue by APT-ZERO** [XTLS/Xray-core#3185]
Hello
I did multiple speedtest benchmarks, server and client both are germany vps
This is QUIC Speedtest results :
![image](https://github.com/XTLS/Xray-core/assets/41063376/ec79bacc-b481-48aa-8a1b-aed193aa611d)
This is WebSocket Speedtest results :
![image](https://github.com/XTLS/Xray-core/assets/41063376/b81cf8df-c199-4d9f-a323-05dfd0ea6e74)
Why is speed of QUIC is so bad, even it's ping is higher than WebSocket!

**Comment by chika0801** [comment]
It was this slow with QUIC in Xray, and we tested it when QUIC was only added to Xray with the same results you are testing now.

If you must use QUIC, I recommend you to take a look at hysteria2 TUIC for these 2 programs.

**Comment by swg0101** [comment]
Just tried it here as well and was surprised how much slower it was compared to the other TLS-based protocols. Interestingly, setting the encryption to TLS also breaks the connectivity and I have to set it to none for anything to work (yet it is still very slow).
