### ISSUE TITLE
ROUTING QUESTIONS

### ISSUE THREAD

**Issue by AnnaPetrovaWer** [XTLS/Xray-core#3188]
您好亲爱的朋友们!

我的客户端设置了规则:geoip:ru -> direct,所有其他连接都通过代理。

一切运行良好。

我想询问这样一个问题,在这种设置下,如果一个本地政府网站(如site.ru)在其网站上嵌入了在site.com上托管的像素,而这个像素会收集访问和请求统计数据,那么我就会向政府网站泄露我的代理信息和与代理的连接。

因为我的IP-ru将与代理IP-com同时出现,这两者可以被关联起来。

**Comment by chika0801** [comment]
Suppose you visit site.ru, and there is a link URL in the web page which is site.com, this site.com URL is in your local Xray-core, and according to your client configuration, it will go into DNS resolution first time, and if the IP is RU's, it will be directly connected. If the IP is non-RU, according to your rules such as proxy, it will be sent to your proxy VPS.
