### ISSUE TITLE
客户端指定证书时会出现警告信息

### ISSUE THREAD

**Issue by kousyougi** [XTLS/Xray-core#319]
服务器是用 LetsEncrypt的证书

客户端不使用系统的证书，手动指定DST_Root_CA_X3根证书时，会出现

Xray 1.3.0 (Xray, Penetrates Everything.) Custom (go1.15.8 linux/amd64)
A unified platform for anti-censorship.
Xray 1.3.0 (Xray, Penetrates Everything.) Custom (go1.15.8 linux/amd64)
A unified platform for anti-censorship.
2021/02/28 21:08:58 [Info] infra/conf/serial: Reading config: /etc/xray/config.json
2021/02/28 21:08:58 [Warning] core: Xray 1.3.0 started
2021/02/28 21:08:58 [Warning] transport/internet/xtls: ignoring invalid X509 key pair > tls: failed to find any PEM data in key input
2021/02/28 21:08:59 [Warning] transport/internet/xtls: ignoring invalid X509 key pair > tls: failed to find any PEM data in key input
2021/02/28 21:08:59 [Warning] transport/internet/xtls: ignoring invalid X509 key pair > tls: failed to find any PEM data in key input

交叉比对，客户端放其他CA根证书会无法上网。所以确认有在检查证书的正确性。

设定是

                "xtlsSettings": {
                    "certificates": [{"certificateFile": "/etc/dst.crt"}],
                    "disableSystemRoot": true,
                    "serverName": "my.domain"
                },

不指定证书时，不会跳出这些警告信息。

我需要理会这个警告信息吗？

**Comment by kousyougi** [comment]
自问自答
有人跟我说加这个就好了
 "certificates": [{"usage": "verify",
虽然不知道原理是什么，加了就没有这个警告信息了。

**Comment by rprx** [comment]
多看文档
