### ISSUE TITLE
想知道如何持久化存储xray配置文件

### ISSUE THREAD

**Issue by SoHugePenguin** [XTLS/Xray-core#3192]
通过gPRC添加的用户，重启xray后会丢失所有用户并回到最开始的config.json配置状态。有什么办法可以持久吗？或者说我可以用docker持久化存储哪些东西？

**Comment by Fangliding** [comment]
@SoHugePenguin 不行 做不到
docker持久化存储自己谷歌

**Comment by SoHugePenguin** [comment]
> @SoHugePenguin 不行 做不到 docker持久化存储自己谷歌

好的，谢谢。那看起来docker可以做到一点

**Comment by RPRX** [comment]
~~我有个大胆的想法，要不写个新 core，配置全靠 API 添加吧，直接解析分享链接，就是说它的配置文件就是一行行 API 指令~~

**Comment by flyapple2016** [comment]
> 通过gPRC添加的用户，重启xray后会丢失所有用户并回到最开始的config.json配置状态。有什么办法可以持久吗？或者说我可以用docker持久化存储哪些东西？

是可以的，我就用。把配置写死一起编译成二进制文件

**Comment by SoHugePenguin** [comment]
> > 通过gPRC添加的用户，重启xray后会丢失所有用户并回到最开始的config.json配置状态。有什么办法可以持久吗？或者说我可以用docker持久化存储哪些东西？
> 
> 是可以的，我就用。把配置写死一起编译成二进制文件

配置写死不就和config.json初始配置是一样了吗？要改源码编译的话我认为应该加个数据库，文件系统存储，每次启动时都初始化。

**Comment by flyapple2016** [comment]
> > > 通过gPRC添加的用户，重启xray后会丢失所有用户并回到最开始的config.json配置状态。有什么办法可以持久吗？或者说我可以用docker持久化存储哪些东西？
> > 
> > 
> > 是可以的，我就用。把配置写死一起编译成二进制文件
> 
> 配置写死不就和config.json初始配置是一样了吗？要改源码编译的话我认为应该加个数据库，文件系统存储，每次启动时都初始化。 我是打算加个环境变量指定数据存储的位置，docker的好处就充分发挥了。


我没明白你的需求到底是什么。如果是配置写死永远不改了，我现在就是这样弄的。如果是想读取一个链接的配置，我记得好像也有这个功能。你可以把源代码让gpt解释一下，main/confloader/external/external.go

**Comment by SoHugePenguin** [comment]
> > > > 通过gPRC添加的用户，重启xray后会丢失所有用户并回到最开始的config.json配置状态。有什么办法可以持久吗？或者说我可以用docker持久化存储哪些东西？
> > > 
> > > 
> > > 是可以的，我就用。把配置写死一起编译成二进制文件
> > 
> > 
> > 配置写死不就和config.json初始配置是一样了吗？要改源码编译的话我认为应该加个数据库，文件系统存储，每次启动时都初始化。 我是打算加个环境变量指定数据存储的位置，docker的好处就充分发挥了。
> 
> 我没明白你的需求到底是什么。如果是配置写死永远不改了，我现在就是这样弄的。如果是想读取一个链接的配置，我记得好像也有这个功能。你可以把源代码让gpt解释一下，main/confloader/external/external.go

我这边搞的是会员制呢，搞流量付费的（暂无），所以说这个场景就很需要CURD，目前我已靠曲线救国方法解决了没问题了，就这样吧。
