### ISSUE TITLE
小小白白话文第七章 7.8 服务器优化之二：开启 HTTP 自动跳转 HTTPS后网页打不开

### ISSUE THREAD

**Issue by febrarybe** [XTLS/Xray-core#3194]
您好，我根据您的文章安装了xray，在进行到第七步的时候：“ 7.8 服务器优化之二：开启 HTTP 自动跳转 HTTPS”后网页打不开，x-ray也无法正常启动。之前的步骤都正常。不知道哪里出现了问题。请老师有空帮忙解答一下。

**Comment by Pen9G** [comment]
如果你能给出你的nginx配置内容、xray配置内容和网页打不开的报错信息，说不定会有人为你解答？

**Comment by JotmKKmkLTzE** [comment]
根据你的描述，  xray无法正常启动，说明 xray配置出现了问题。   其次，该配置中xray作为前置程序，xray无法启动，网页自然无法打开。

**Comment by Fangliding** [comment]
无详细信息 而且与核心无关
