### ISSUE TITLE
REALITY fallback

### ISSUE THREAD

**Issue by AnnaPetrovaWer** [XTLS/Xray-core#3197]
大家好！
我想在一个配置中合并几个连接到同一个端口。
Reality + GRPC，例如在nginx后面。
假设在443端口前面有REALITY，目的地是nginx。
我能做到这一点。
我不明白如何安全地将vless+grpc添加到这个方案中？让它也能通过443端口访问。
是通过fallback吗？Dest？请分享你的经验，如何正确做到这一点？
谢谢！

**Comment by masbur** [comment]
You can try this
- Reality Fallbacks dest -> Reality + gRPC
- Reality Settings dest -> Vless TLS -> Fallbacks [ ws / grpc / etc ]
