### ISSUE TITLE
请问有没有计划添加可以直接使用的增删用户的api命令？

### ISSUE THREAD

**Issue by g552656** [XTLS/Xray-core#32]
像流量统计那样可以直接使用的api命令
多谢

**Comment by rprx** [comment]
这个可能复杂一些，看看 @qjebbs 是否有计划实现

**Comment by qjebbs** [comment]
![image](https://user-images.githubusercontent.com/16953333/101134575-911a5f00-3645-11eb-8e7f-889f6bd864cc.png)

不敢当，现在支持的rpc接口几乎都有对应的api命令。没有的就没那么方便可以实现了。

**Comment by rprx** [comment]
应该是 Alter?

**Comment by qjebbs** [comment]
看起来是😅

**Comment by g552656** [comment]
因为从v2ray开始就没有过多的api文档
请问有alter这样的api命令吗可以增删用户？

**Comment by rprx** [comment]
@qjebbs 

还请帮忙测试下 v1.1.1 的 API 是否可以正常使用

**Comment by qjebbs** [comment]
@rprx 
https://github.com/v2fly/v2ray-core/blob/9367e9b1f2906220eb6c68c639aaf2fed77c6bf1/commands/all/api/shared.go#L43

看来是这个方法不对。还是因为我没研究过grpc，一看里面只这方法，就猜是它了。应该是哪一个？😅

**Comment by qjebbs** [comment]
@rprx 

```go
func showResponese(m proto.Message) {
	msg := ""
	bs, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		msg = fmt.Sprintf("error: %s\n\n,%v", err, m)
	} else {
		msg = string(bs)
		msg = strings.TrimSpace(msg)
	}
	if msg == "" {
		return
	}
	fmt.Println(msg)
}
```

上述改为json包转换就可以了。你直接改了发 patch版吧，就不pr那么麻烦了。

> 旧proto包有个`proto.MarshalTextString(resp)`，换新包我没多想，以为是同一个，结果翻车了。

不过，根据我测试结果

`./v2ctl api --server=127.0.0.1:10085 StatsService.QueryStats 'pattern: "" reset: false'`

新旧的实现都会报 

```
rpc error: code = Unknown desc = app/stats/command: QueryStats only works its own stats.Manager.
```

不知道是不是我环境问题，无法解决。

**Comment by rprx** [comment]
@xianren78 

替换 main/commands/all/api/shared.go 最底部的函数为上面的代码试试

**Comment by xianren78** [comment]
> @xianren78
> 
> 替换 main/commands/all/api/shared.go 最底部的函数为上面的代码试试

没有编译环境...😅

**Comment by NutterChen** [comment]
等等 这不是已经实现了吗？

https://www.v2fly.org/config/api.html#%E6%94%AF%E6%8C%81%E7%9A%84-api-%E5%88%97%E8%A1%A8

[https://s3.ax1x.com/2020/12/04/DbqW4I.png](url)

**Comment by NutterChen** [comment]
https://github.com/XTLS/Xray-core/blob/16544c18aba5594be57f588c7d7f5ed294940e22/app/proxyman/command/command.proto#L17

**Comment by xianren78** [comment]
> @rprx
> 
> ```go
> func showResponese(m proto.Message) {
> 	if IsNil(m) {
> 		return
> 	}
> 	msg := ""
> 	bs, err := json.MarshalIndent(m, "", "  ")
> 	if err != nil {
> 		msg = fmt.Sprintf("error: %s\n\n,%v", err, m)
> 	} else {
> 		msg = string(bs)
> 		msg = strings.TrimSpace(msg)
> 	}
> 	if msg == "" {
> 		return
> 	}
> 	fmt.Println(msg)
> }
> func IsNil(i interface{}) bool {
> 	vi := reflect.ValueOf(i)
> 	if vi.Kind() == reflect.Ptr {
> 		return vi.IsNil()
> 	}
> 	return i == nil
> }
> ```
> 
> 上述改为json包转换就可以了。你直接改了发 patch版吧，就不pr那么麻烦了。
> 
> > 旧proto包有个`proto.MarshalTextString(resp)`，换新包我没多想，以为是同一个，结果翻车了。
> 
> 不过，根据我测试结果
> 
> `./v2ctl api --server=127.0.0.1:10085 StatsService.QueryStats 'pattern: "" reset: false'`
> 
> 新旧的实现都会报
> 
> ```
> rpc error: code = Unknown desc = app/stats/command: QueryStats only works its own stats.Manager.
> ```
> 
> 不知道是不是我环境问题，无法解决。

可以运行出数据，但是<符号乱码

![Screenshot_20201204-183806_Termius](https://user-images.githubusercontent.com/26913311/101154912-5aead880-3661-11eb-8626-cbafa6ee9eab.png)

**Comment by rprx** [comment]
@NutterChen 

这里是指 `xray api` 指令，不是指 Xray 接受的 API

**Comment by rprx** [comment]
@NutterChen 

这里是指 `xray api` 指令，不是指 Xray 拥有的 API

**Comment by g552656** [comment]
> 等等 这不是已经实现了吗？
> 
> https://www.v2fly.org/config/api.html#%E6%94%AF%E6%8C%81%E7%9A%84-api-%E5%88%97%E8%A1%A8
> 
> https://s3.ax1x.com/2020/12/04/DbqW4I.png

请教，是怎么实现的？

**Comment by rprx** [comment]
@qjebbs @xianren78 

为了避免 XSS，Go 序列化 JSON 时默认把尖括号等给转义了

**Comment by rprx** [comment]
@qjebbs @xianren78 

https://github.com/XTLS/Xray-core/commit/b69b52508c674351e5adacd46498c0033d6d5a4f

**Comment by rprx** [comment]
@qjebbs @xianren78 

https://github.com/XTLS/Xray-core/commit/0a9db2d3d3bd0d4d335397e9ce6bd83c6553f333

（为了改 commit message，force push 了三次。。

**Comment by vangork** [comment]
@g552656 

`	
import (
	"github.com/xtls/xray-core/app/proxyman/command"
	statsService "github.com/xtls/xray-core/app/stats/command"
	"github.com/xtls/xray-core/common/protocol"
	"github.com/xtls/xray-core/common/serial"
	"github.com/xtls/xray-core/proxy/trojan"
	"github.com/xtls/xray-core/proxy/vless"
	"github.com/xtls/xray-core/proxy/vmess"
)


func addV2rayVmessUser(client command.HandlerServiceClient, inboundTag string, level uint32, email string, id string, alterID uint32) error {
	_, err := client.AlterInbound(context.Background(), &command.AlterInboundRequest{
		Tag: inboundTag,
		Operation: serial.ToTypedMessage(&command.AddUserOperation{
			User: &protocol.User{
				Level: level,
				Email: email,
				Account: serial.ToTypedMessage(&vmess.Account{
					Id:      id,
					AlterId: alterID,
				}),
			},
		}),
	})
	return err
}

func addV2rayVlessUser(client command.HandlerServiceClient, inboundTag string, level uint32, email string, id string) error {
	_, err := client.AlterInbound(context.Background(), &command.AlterInboundRequest{
		Tag: inboundTag,
		Operation: serial.ToTypedMessage(&command.AddUserOperation{
			User: &protocol.User{
				Level: level,
				Email: email,
				Account: serial.ToTypedMessage(&vless.Account{
					Id:   id,
					Flow: "xtls-rprx-direct",
				}),
			},
		}),
	})
	return err
}

func addV2rayTrojanUser(client command.HandlerServiceClient, inboundTag string, level uint32, email string, password string) error {
	_, err := client.AlterInbound(context.Background(), &command.AlterInboundRequest{
		Tag: inboundTag,
		Operation: serial.ToTypedMessage(&command.AddUserOperation{
			User: &protocol.User{
				Level: level,
				Email: email,
				Account: serial.ToTypedMessage(&trojan.Account{
					Password: password,
				}),
			},
		}),
	})
	return err
}

func removeV2rayUser(client command.HandlerServiceClient, inboundTag string, email string) error {
	_, err := client.AlterInbound(context.Background(), &command.AlterInboundRequest{
		Tag: inboundTag,
		Operation: serial.ToTypedMessage(&command.RemoveUserOperation{
			Email: email,
		}),
	})
	return err
}

func getV2rayUserTraffic(client statsService.StatsServiceClient, email string, reset bool) {
	uplinkStr := fmt.Sprintf("user>>>%s>>>traffic>>>uplink", email)
	downlinkStr := fmt.Sprintf("user>>>%s>>>traffic>>>downlink", email)
	uplinkResp, err := client.GetStats(context.Background(), &statsService.GetStatsRequest{
		Name:   uplinkStr,
		Reset_: reset,
	})

	if err != nil {
		log.Printf("failed to call grpc command: %v", err)
	}

	downlinkResp, err := client.GetStats(context.Background(), &statsService.GetStatsRequest{
		Name:   downlinkStr,
		Reset_: reset,
	})

	if err != nil {
		log.Printf("failed to call grpc command: %v", err)
	}

	log.Printf("name: %v", email)
	log.Printf("uplink: %v", uplinkResp.Stat.Value)
	log.Printf("downlink: %v", downlinkResp.Stat.Value)
	log.Printf("total: %v", uplinkResp.Stat.Value+downlinkResp.Stat.Value)
}`

**Comment by qjebbs** [comment]
@vangork 你的代码完成度很高了，建议你去提个PR。我对grpc不熟悉，也没有添加用户相关的使用场景。没有相关需求的人做出来的东西很可能是不好用的。

**Comment by g552656** [comment]
@vangork 
非常感谢！

**Comment by rprx** [comment]
我觉得可以为 `xray api` 新增这个命令
