### ISSUE TITLE
Simplify Routing

### ISSUE THREAD

**Issue by fodhelper** [XTLS/Xray-core#3200]
Hello

I have 3 outbound in my xray's server config [DE, UK, USA]
And 5 Inbounds [REALITY, WS, TCP(HTTP), etc.] + HAProxy (for all in one port)

I made 3 copy of my REALITY TCP inbound with different Tags and Ports and serverNames, configured AIO port in fallback and HAProxy
and used 'inboundTag' RuleObject in Routing part of my server xray config to route each one to a different Outbound
Now i have 3 REALITY TCP client config, each one has a different outbound

If i do the same for all of my Inbounds, it will be a bad mess

I have tried 'source' and 'sourcePort', and i failed, i faced and solved many errors but failed at the end
'attrs' RuleObject is useless, because it's only for HTTP inbound
'user' RuleObject seems good, but does not supports 'Plain string' and also needs panel support

Could you please make a easier way to do Routing? currently it's a nightmare, i have tried anything i could for multiple weeks but failed

I think there is 2 good way :
01. Routing by the port that is used in Client config
- In this way, we can set multiple listen port for 1 inbound, use HAProxy or/and Xray's fallback to redirect connection to a different port by sni or host header, and route each listen port to a different outbound from Routing part of xray server (easy to do)
02. Support for 'Plain string' in 'user' RuleObject (will need Xray manager/panel support too)(hard for majority)

Thank you ❤️

**Comment by Fangliding** [comment]
why not use inbound tag(
