### ISSUE TITLE
BUG: Shadowsocks (2022-blake3-aes-256-gcm) connectivity problem after Windows 10 update

### ISSUE THREAD

**Issue by kiyan9** [XTLS/Xray-core#3201]
**Problem Description:**

After updating my Windows to the version and build at below, Shadowsocks with encryption method 2022-blake3-aes-256-gcm has stopped working! before the update it worked like a charm.

**OS: Windows 10 Pro
Version: 22H2
Build: 19045.4170**

Other shadowsocks encryption methods work perfectly fine on my machine, including chacha, xchacha and etc.
Only 2022-blake3 stack doesn't work.

Also, I have tried the exact same shadowsocks (2022-blake3-aes-256-gcm) config on Android/iPhone/Windows 11 and works fine on all of them.

Funny thing is I don't get any error in the log! it marks all connections as "accepted". here is some parts of the log:
```
2024/03/27 19:32:02 127.0.0.1:2697 accepted //api.github.com:443 [http -> proxy]
2024/03/27 19:32:03 127.0.0.1:2699 accepted //collector.github.com:443 [http -> proxy]
2024/03/27 19:32:03 127.0.0.1:2700 accepted //www.google.com:443 [http -> proxy]
2024/03/27 19:32:03 127.0.0.1:2703 accepted //www.google.com:443 [http -> proxy]
2024/03/27 19:32:03 127.0.0.1:2705 accepted //api.github.com:443 [http -> proxy]
2024/03/27 19:32:04 127.0.0.1:2707 accepted //www.google.com:443 [http -> proxy]
2024/03/27 19:32:04 127.0.0.1:2709 accepted //www.google.com:443 [http -> proxy]
2024/03/27 19:32:04 127.0.0.1:2711 accepted //web.whatsapp.com:443 [http -> proxy]
2024/03/27 19:32:05 127.0.0.1:2713 accepted //alive.github.com:443 [http -> proxy]
```
any help and update on this problem would be appreciated.

**Comment by dz-paji** [comment]
2022-blake3 (as described [here](https://shadowsocks.org/doc/sip022.html#_3-1-3-header)) contains a timestamp in the packet header.
