### ISSUE TITLE
无法登陆zoom

### ISSUE THREAD

**Issue by Firestar-Reimu** [XTLS/Xray-core#3202]
## 你正在使用哪个版本的 XRay？

Archlinux + XRay 1.8.9 + V2RayA 2.2.5.1

## 你的使用场景是什么？

使用Zoom

## 你看到的异常现象是什么？

无法通过邮箱/google登陆zoom，提示Error:1044

## 你期待看到的正常表现是怎样的？

只要将核心换成v2ray，就可以登陆zoom

## 请附上你的配置

**配置：**

![image](https://github.com/v2fly/v2ray-core/assets/65082432/880a3760-f63d-47e5-a6c9-e334b436caf6)

没有服务器端与自用端，也不知道json文件在哪

**Comment by Fangliding** [comment]
还是劳烦自己手写个尝试一下 不拿图形客户端算命(
