### ISSUE TITLE
Issues with VLESS+Tor

### ISSUE THREAD

**Issue by navalnyofficial** [XTLS/Xray-core#3206]
Hi. I have a problem. When i try to connect to Tor using XTLS-Reality VPN, it always crashes and the logs say: "connections died in state handshaking (TLS) with SSL state error in HANDSHAKE". How to fix that? I tried to enable and disable sniffing- did not help.

**Comment by systemhorse** [comment]
## Debian/Ubuntu server

Open port tcp/443 for input.

```
apt update && apt upgrade
```

```
bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install --beta -u root
```

```
xray uuid
```

```
xray x25519
```

```
openssl rand -hex 8
```

```
vi /usr/local/etc/xray/config.json
```

```
{
    "log": {
        "loglevel": "warning"
    },
    "inbounds": [
        {
            "listen": "0.0.0.0",
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "7400d1f4-dfb3-476c-8ee7-441d1396ea08",
                        "flow": "xtls-rprx-vision"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "tcp",
                "security": "reality",
                "realitySettings": {
                    "dest": "www.lovelive-anime.jp:443", 
                    "serverNames": [ 
                        "www.lovelive-anime.jp",
                        "lovelive-anime.jp"
                    ],
                    "privateKey": "2OQ-0gh5l1T_3NM1D1JduJkfaCltAHVjFACpfw-9Aks", 
                    "shortIds": [ 
                        "1b99f77ce8b762f8"
                    ]
                }
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls",
                    "quic"
                ]
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "tag": "block"
        }
    ]
}
```

```
systemctl restart xray
```

## Windows Xray client v2rayN

Download .NET 8 Desktop Runtime installer.

Run `windowsdesktop-runtime-8.*-win-x64.exe`.

Visit https://github.com/2dust/v2rayN/releases

Download `v2rayN-With-Core.zip`.

Unzip `v2rayN-With-Core.zip`.

Launch `v2rayN.exe`.

Select from the menu **Servers** > **Add [VLESS] server**.

* Core type Xray
* Alias `demo`
* Address `123.123.123.123`
* Port `443`
* UUID (id) `7400d1f4-dfb3-476c-8ee7-441d1396ea08`
* Flow `xtls-rprx-vision`
* Encryption `none`
* Transport protocol (network) `tcp`
* Camouflage type `none`
* Camouflage domain (host) blank
* Path blank
* TLS `reality`
* SNI `www.lovelive-anime.jp`
* Fingerprint `chrome`
* Public Key `G0htQ39cE0oWaf6eIE-crKcOWWqf6nihv6M0w1g-YTo`
* ShortId `1b99f77ce8b762f8`
* SpiderX blank

Press **Confirm**.

SOCKS5 proxy starts listening on localhost port `10808`.

## Windows Tor Browser

Visit https://www.torproject.org/download

Download `tor-browser-windows-x86_64-portable-*.exe`.

Run `tor-browser-windows-x86_64-portable-*.exe`.

Select **Configure Connection**.

Under **Advanced**, select **Settings**.

Check **I use a proxy to connect to the Internet**.

* Proxy Type **SOCKS5**
* Address `127.0.0.1`
* Port `10808`
* Username blank
* Password blank

Press **OK**.

Select **Select a built-in bridge**.

Select **obfs4**.

Click **Connect**.

**Comment by Fangliding** [comment]
```
"routeOnly": true
```

**Comment by sedut-pank** [comment]
And I have the same problem

**Comment by gentoosys** [comment]
it worked before, then stopped. disabled destovverride and it is working again

**Comment by ghost** [comment]
Let me access Tor directly through Vless. The bridges are very slow and I can't watch YouTube
