### ISSUE TITLE
Telegram Group Verification Question Wrong Answer

### ISSUE THREAD

**Issue by KyleJKC** [XTLS/Xray-core#3209]
Hi, I joined the telegram group and was prompted with a verification question. (Screenshot attached below).

The answer is pretty obvious, Y is not a valid nitrogen base of RNA, so the first answer should be correct.

However, the message indicated that an incorrect answer was chosen and I was kicked out of the group.

Did I do anything wrong or it's simply an error of the question?

<img width="522" alt="Screenshot 2024-03-29 at 3 48 17 PM" src="https://github.com/XTLS/Xray-core/assets/44722594/c9d8f635-c40f-4d12-8466-2126e747d5ee">

**Comment by Fangliding** [comment]
@KyleJKC I'm afraid it's valid
https://en.m.wikipedia.org/wiki/Nucleic_acid_notation

**Comment by KyleJKC** [comment]
> @KyleJKC I'm afraid it's valid https://en.m.wikipedia.org/wiki/Nucleic_acid_notation btw, don't spam this in issue, it's not for this usage

@Fangliding I apologize for spamming this tiny trivial thing in the issue section, but I am sure that there is a problem with the verification question.

The Wikipedia page mentions that "Y" refers to the Pyrimidine bases, which are Cytosine ("C") and Uracil ("U") in RNA.
<img width="716" alt="Screenshot 2024-03-29 at 5 09 39 PM" src="https://github.com/XTLS/Xray-core/assets/44722594/ed077ef7-ed7d-46c0-b7ad-71b5a84001b7">
In mRNA codons, only four letters ("A", "U", "G", and "C") that refer to specific nitrogen bases should appear.

Furthermore, according to [mRNA codon chart](https://www.google.com/url?sa=i&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FDNA_and_RNA_codon_tables&psig=AOvVaw1ygQRyRGYKA89YbLnwV04X&ust=1711843404348000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCMCht-LXmoUDFQAAAAAdAAAAABAJ), each of the choices besides "CGYGUU" would translate to ARG-VAL.

Again, I sincerely apologize for opening up this issue. However, since I was kicked out of the group, there's nowhere else left to report this error.

**Comment by Fangliding** [comment]
@KyleJKC Y represents C or U
Isn't CGC and CGU translated as Arg?

**Comment by KyleJKC** [comment]
@Fangliding If that explains the choice, then I have no clue about the correct answer to the question. Since GUU also translates to VAL.
Closing this issue now, the discussion on this question is getting meaningless.

**Comment by Fangliding** [comment]
@KyleJKC Well, maybe vertebrate have  mitochondrial alternative codons
