### ISSUE TITLE
[Feature Request] proxySettings enhancement

### ISSUE THREAD

**Issue by Xray9** [XTLS/Xray-core#321]
当前 Xray-core 的 [proxySettings](https://xtls.github.io/config/base/outbounds/#proxysettingsobject) 只能支持 `network` 为 `tcp` 的 [streamSettings](https://xtls.github.io/config/base/transport/#streamsettingsobject)，如果能够支持所有可以搭配的 network，将会使 Xray-core 更强大，我们可以仅仅在客户端就将两个 outbounds 串起来。 @JimhHan

**Comment by AkinoKaede** [comment]
v2fly/v2ray-core#718

**Comment by JimhHan** [comment]
https://github.com/XTLS/Xray-core/pull/234/commits/a31a609172c13009137822591467626978b23ca1
