### ISSUE TITLE
xray seems to be conected but nothing happen 

### ISSUE THREAD

**Issue by shmamadking** [XTLS/Xray-core#3212]
Hi 
running xray with my config file result  :
Xray 1.8.10 (Xray, Penetrates Everything.) 07ed094 (go1.22.1 linux/amd64)
A unified platform for anti-censorship.
2024/03/30 13:14:38 Using default config:  /home/enayat/v2ray-uri2json/scripts/config.json
2024/03/30 13:14:38 [Info] infra/conf/serial: Reading config: /home/enayat/v2ray-uri2json/scripts/config.json
2024/03/30 13:14:38 [Warning] core: Xray 1.8.10 started

but noting happened in my browsers 
 
by running _xray tls ping config.json_  i got 
Tls ping:  config.json
Failed to resolve IP: lookup config.json on 8.8.8.8:53: no such host

here is my conf.json file :
[config.json](https://github.com/XTLS/Xray-core/files/14811415/config.json)

I am really new to use xray in Ubuntu (22.04). can anybody help me to resolve my issue ?

**Comment by Fangliding** [comment]
"hosts": {
      "domain:googleapis.cn": "googleapis.com"
    }
?
