### ISSUE TITLE
DIVERT导致DNS请求分流混乱

### ISSUE THREAD

**Issue by rp-hello** [XTLS/Xray-core#3215]
参考[TProxy 透明代理（ipv4 and ipv6）配置教程](https://xtls.github.io/document/level-2/tproxy_ipv4_and_ipv6.html#%E4%BD%BF%E7%94%A8-iptables)中的配置，
有如下规则：
```
iptables -t mangle -I PREROUTING -p tcp -m socket -j DIVERT
```

但是如此配置后，dns流量会走物理网络直接出去；而不是预期的，走dns模块，且国外域名走代理。

具体来说，就是访问`ipleak.net`后，页面上dns server都是国内的。

删除掉这个`-m socket`规则后，就正常走了。页面上dns server都是国外的。

---
我的全部iptables配置：
```
*mangle
:V2RAY -
-A V2RAY -j RETURN -m mark --mark 0x2/0x2
-A V2RAY -p udp --dport 53 -j TPROXY --on-ip 127.0.0.1 --on-port 12345 --tproxy-mark 0x1
-A V2RAY -p tcp --dport 53 -j TPROXY --on-ip 127.0.0.1 --on-port 12345 --tproxy-mark 0x1
-A V2RAY -j RETURN -m set --match-set v2ray_src_direct_v4 src
-A V2RAY -j RETURN -m set --match-set v2ray_dst_direct_v4 dst
-A V2RAY -p tcp  -j TPROXY --on-ip 127.0.0.1 --on-port 12345 --tproxy-mark 0x1
-A V2RAY -p udp -j TPROXY --on-ip 127.0.0.1 --on-port 12345 --tproxy-mark 0x1
-A PREROUTING -i br-lan -j V2RAY
-A PREROUTING -j V2RAY -m mark --mark 0x1/0x1

:V2RAY_MASK -
-A V2RAY_MASK -j RETURN -m mark --mark 0x2/0x2
-A V2RAY_MASK -j RETURN -m set --match-set v2ray_src_direct_v4 src
-A V2RAY_MASK -j RETURN -m set --match-set v2ray_dst_direct_v4 dst
-A V2RAY_MASK -p tcp  -j MARK --set-xmark 0x1/0x1
-A V2RAY_MASK -p udp -j MARK --set-xmark 0x1/0x1
-A OUTPUT -j V2RAY_MASK

:V2RAY_DIVERT -
-A V2RAY_DIVERT -j MARK --set-mark 0x1
-A V2RAY_DIVERT -j ACCEPT
-I PREROUTING -p tcp -m socket -j V2RAY_DIVERT
COMMIT
```
xray配置：
```json
{
  "log": {
    "access": "/tmp/xray-access.log",
    "error": "/tmp/xray-error.log",
    "dnsLog": true,
    "loglevel": "debug"
  },
  "inbounds": [
    {
      "port": 12345,
      "protocol": "dokodemo-door",
      "settings": {
        "followRedirect": true,
        "network": "tcp,udp"
      },
      "streamSettings": {
        "sockopt": {
          "tproxy": "tproxy"
        }
      },
      "tag": "transparent",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http", "tls", "quic"
        ]
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      ...
    },
    {
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP"
      },
      "streamSettings": {
        "sockopt": {
          "mark": 255
        }
      },
      "tag": "direct"
    },
    {
      "tag": "dns_out",
      "protocol": "dns",
      "streamSettings": {
        "sockopt": {
          "mark": 255
        }
      }
    }
  ],
  "routing": {
    "domainMatcher": "mph",
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "transparent"
        ],
        "port": 53,
        "outboundTag": "dns_out"
      },
      {
        "type": "field",
        "ip": [
          "geoip:private",
          "geoip:cn"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "network": "tcp,udp",
        "outboundTag": "proxy"
      }
    ]
  },
  "dns": {
    "queryStrategy": "UseIPv4",
    "disableFallbackIfMatch": true,
    "servers": [
      {
        "address": "8.8.8.8",
        "port": 53,
        "domains": [
          "geosite:geolocation-!cn",
          "domain:v2fly.org",
          "domain:bing.com",
          "domain:cnbeta.com.tw"
        ]
      },
      {
        "address": "localhost",
        "port": 53,
        "domains": [
          "geosite:geolocation-cn"
        ]
      }
    ]
  }
}
```

**Comment by rp-hello** [comment]
我的猜想是，参考socket的文档（<https://man7.org/linux/man-pages/man8/iptables-extensions.8.html>）：

> This matches if an open TCP/UDP socket can be found by doing a socket lookup on the packet. It matches if there is an established or non-zero bound listening socket (possibly with a non-local address).

前半段的`an open TCP/UDP socket can be found`情况应该是没有问题的，如果这个数据包是归属于之前打开的socket，那么之前的socket应该也是转到了xray的。
但是后半段的`non-zero bound listening socket`怎么理解？如果有程序在监听53端口（比如路由器上原本的dnsmasq），那么就会直接ACCEPT么？这样的话，现象倒是和我这边的表现符合（dns请求直接走ISP网络了，xray没有收到。每次xray重启、iptables规则重载，会有两个dns请求走到xray中）

但是如果真的是上面的原因的话，DIVERT机制可能存在泄露dns的风险。

**Comment by Fangliding** [comment]
没道理啊。。建议检查下xray的日志

**Comment by robberphex** [comment]
> 没道理啊。。建议检查下xray的日志

当时的日志表现如下：
1. udp dns查询会到xray，因为divert仅对tcp生效。
2. tcp dns查询在xray日志中没有任何反映，我在路由器的wan口，也能抓到裸的dns请求（也就是说，过去几周，我的所有网站访问记录，都被ISP拿到了）。
    * 所以我在这个issue里面，怀疑是不是我们对socket模块理解有误。

**Comment by Fangliding** [comment]
> > 没道理啊。。建议检查下xray的日志
> 
> 当时的日志表现如下：
> 
> 1. udp dns查询会到xray，因为divert仅对tcp生效。
> 2. tcp dns查询在xray日志中没有任何反映，我在路由器的wan口，也能抓到裸的tcp dns请求（也就是说，过去几周，我的所有网站访问记录，都被ISP拿到了）。
>    
>    * 现在chrome默认发送的就是tcp dns请求了
>    * 所以我在这个issue里面，怀疑是不是我们对socket模块理解有误。

chrome的tcp dns是哪来的。。。 据我所知它应该只有doh 而且也不是默认的 就是开了它也不应该被所谓的“dns泄露检测”检测出来
这套规则仅适用于处理一般的udp53 dns 这个socket模块一时半会讲不清楚但是它应该和问题没关系才对
建议还是分析一下你在出口抓到的这个tcp dns是哪个程序发起的 以及被送到xray之后是怎么被处理的

**Comment by rp-hello** [comment]
> chrome的tcp dns是哪来的

没有开启doh的情况下，现在chrome会发送tcp dns请求。

> 这个socket模块一时半会讲不清楚但是它应该和问题没关系才对

刚刚实验了下。在其他条件都参考[TProxy 透明代理（ipv4 and ipv6）配置教程](https://xtls.github.io/document/level-2/tproxy_ipv4_and_ipv6.html#%E4%BD%BF%E7%94%A8-iptables)、[透明代理(TPROXY)](https://guide.v2fly.org/app/tproxy.html#%E9%85%8D%E7%BD%AE%E9%80%8F%E6%98%8E%E4%BB%A3%E7%90%86%E8%A7%84%E5%88%99)的情况下，
1. 如果是规则`iptables -t mangle -I PREROUTING -p tcp -m socket -j DIVERT`，那么dns是有泄露的：
    ![dns-leaked](https://github.com/XTLS/Xray-core/assets/133582491/9020b100-8ba6-4a4a-a9ca-952f0b6ee4f7)
2. 规则换成`iptables -t mangle -I PREROUTING -p tcp -m socket --transparent -j DIVERT`后，dns没有泄露：
    ![dns-not-leaked](https://github.com/XTLS/Xray-core/assets/133582491/799081fc-4f0b-4538-8956-72570573ddf3)

看起来是socket模块查找socket时候的问题，加上了仅查找transparent socket的限制后正常。

**Comment by Fangliding** [comment]
> > chrome的tcp dns是哪来的
> 
> 没有开启doh的情况下，现在chrome会发送tcp dns请求。
> 
> > 这个socket模块一时半会讲不清楚但是它应该和问题没关系才对
> 
> 刚刚实验了下。在其他条件都参考[TProxy 透明代理（ipv4 and ipv6）配置教程](https://xtls.github.io/document/level-2/tproxy_ipv4_and_ipv6.html#%E4%BD%BF%E7%94%A8-iptables)、[透明代理(TPROXY)](https://guide.v2fly.org/app/tproxy.html#%E9%85%8D%E7%BD%AE%E9%80%8F%E6%98%8E%E4%BB%A3%E7%90%86%E8%A7%84%E5%88%99)的情况下，
> 
> 1. 如果是规则`iptables -t mangle -I PREROUTING -p tcp -m socket -j DIVERT`，那么dns是有泄露的：
>    ![dns-leaked](https://private-user-images.githubusercontent.com/133582491/320306771-9020b100-8ba6-4a4a-a9ca-952f0b6ee4f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MTg5MTQsIm5iZiI6MTcxMjUxODYxNCwicGF0aCI6Ii8xMzM1ODI0OTEvMzIwMzA2NzcxLTkwMjBiMTAwLThiYTYtNGE0YS1hOWNhLTk1MmYwYjZlZTRmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QxOTM2NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTk5NWQ4N2E1NjZjMWI1MDdlYTZjN2M0MmY2YmY3MjQxZWJmODUzODMwZjNiYTVhYzE5NDAwNTgzMDMxMjk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xP-r2t6xbDEn_mzRSFK1V0i6E3UGFG7r5DxW2WQd2SE)
> 2. 规则换成`iptables -t mangle -I PREROUTING -p tcp -m socket --transparent -j DIVERT`后，dns没有泄露：
>    ![dns-not-leaked](https://private-user-images.githubusercontent.com/133582491/320307051-799081fc-4f0b-4538-8956-72570573ddf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MTg5MTQsIm5iZiI6MTcxMjUxODYxNCwicGF0aCI6Ii8xMzM1ODI0OTEvMzIwMzA3MDUxLTc5OTA4MWZjLTRmMGItNDUzOC04OTU2LTcyNTcwNTczZGRmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QxOTM2NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYmJjZjkzMTQyYTZkNTc1ZWI5NjNlOWQ4YjlhYmJlY2E1YTU4NTQ1MmFlZmNhOTU1MDU1MmFiZDJiOGY4NDAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uZ_3teq0GsttCtVyeFr3xCLNWzOu7ST3qcaeMjL1Jjw)
> 
> 看起来是socket模块查找socket时候的问题，加上了仅查找transparent socket的限制后正常。

看起来是一些奇奇怪怪的ipv6 bind问题导致ipv6 dns请求意外的被socket模块匹配了 用 ```--transparent``` 选项应该是一个合适的方法
这篇教程本身就有历史了 仅供参考(
