### ISSUE TITLE
Xray 1.8.10 breaks Fallback to WS

### ISSUE THREAD

**Issue by AmirReza2012** [XTLS/Xray-core#3216]
When using Vless + TCP + Vision + Fallback to websockets, switching server to version 1.8.10 breaks the websockets config and I get EOF error on xray 1.8.9 on android client.

Error log:
`proxy/vless/inbound: firstLen = 192
proxy/vless/inbound: fallback starts > proxy/vless/encoding: invalid request version
proxy/vless/inbound: realName = MYSNI
proxy/vless/inbound: realAlpn = http/1.1`

**Comment by lxhao61** [comment]
你 WebSocket 启用 0-RTT 吧？

**Comment by chika0801** [comment]
发你的nginx和xray配置文件

**Comment by lxhao61** [comment]
> > 你 WebSocket 启用了 0-RTT 吧？
> 
> I have tried "?ed=2048", "?ed=2560" and no early-data on the client side.
> 
> > 发你的nginx和xray配置文件
> 
> I noticed I had "/?ed=2560" for ws path on my server side xray configuration (to be able to more conveniently scan QR codes and have the ed written for me the link)
> 
> If I have on the server side: `"path": "/whatever?ed=2560"` this will keep working when I upgrade from 1.8.9 to 1.8.10
> 
> But if I have `"path": "/?ed=2560"` then upgrading to 1.8.10 will break the clients connections and return EOF
> 
> I think adding early-data to the server-side configuration is not necessary in the first place but it was working for me before 1.8.10, please correct me if I'm wrong.

晕！启用 WebSocket 0-RTT 仅客户端路径后加 ?ed=2048 或 ?ed=2560。版本 1.8.10 及以后客户端路径推荐加 ?ed=2560。

**Comment by lxhao61** [comment]
> > > > 你 WebSocket 启用了 0-RTT 吧？
> > > 
> > > 
> > > I have tried "?ed=2048", "?ed=2560" and no early-data on the client side.
> > > > 发你的nginx和xray配置文件
> > > 
> > > 
> > > I noticed I had "/?ed=2560" for ws path on my server side xray configuration (to be able to more conveniently scan QR codes and have the ed written for me the link)
> > > If I have on the server side: `"path": "/whatever?ed=2560"` this will keep working when I upgrade from 1.8.9 to 1.8.10
> > > But if I have `"path": "/?ed=2560"` then upgrading to 1.8.10 will break the clients connections and return EOF
> > > I think adding early-data to the server-side configuration is not necessary in the first place but it was working for me before 1.8.10, please correct me if I'm wrong.
> > 
> > 
> > 晕！启用 WebSocket 0-RTT 仅客户端路径后加 ?ed=2048 或 ?ed=2560。版本 1.8.10 及以后客户端路径推荐加 ?ed=2560。
> 
> Hi. Thank you. So adding ed to the server configuration is not necessary.

是的。

**Comment by chika0801** [comment]
@lxhao61 ed=xxxx 一直是只在客户端加就是了。

2048变2560是最近httpupgrade那个提交中提到事儿

最近就顺便把文档上修改了下这2个内容

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/issues/3222
