### ISSUE TITLE
Bug: Xray Crashing at random times.

### ISSUE THREAD

**Issue by HamedX2Z** [XTLS/Xray-core#3217]
there seem to be a bug within xray core that makes it crash and restart automatically after certain period of times I'll included the logs down here. does anyone know how i can fix this issue?

===============================================

2024/03/29 23:55:36 DEBUG - XRAY: A unified platform for anti-censorship.
2024/03/29 23:55:36 DEBUG - XRAY: Xray 1.8.9 (Xray, Penetrates Everything.) 37f8654 (go1.22.1 linux/amd64)
2024/03/29 23:55:36 DEBUG - X-UI: restart xray, force:false
2024/03/29 23:55:34 DEBUG - XRAY: created by github.com/xtls/xray-core/common/task.Run in goroutine 157527
2024/03/29 23:55:34 DEBUG - XRAY: (0xc000a81260?)
2024/03/29 23:55:34 DEBUG - XRAY: 99 +0x164
2024/03/29 23:55:34 DEBUG - XRAY: 0xc0003beda8?})
2024/03/29 23:55:34 DEBUG - XRAY: })
2024/03/29 23:55:34 DEBUG - XRAY: ?
2024/03/29 23:55:34 DEBUG - XRAY: 0x699d5c
2024/03/29 23:55:34 DEBUG - XRAY: ,
2024/03/29 23:55:34 DEBUG - XRAY: ?
2024/03/29 23:55:34 DEBUG - XRAY: 0xc0003bed00
2024/03/29 23:55:34 DEBUG - XRAY: ,
2024/03/29 23:55:34 DEBUG - XRAY: ?
2024/03/29 23:55:34 DEBUG - XRAY: 0xc000693c20
2024/03/29 23:55:34 DEBUG - XRAY: {
2024/03/29 23:55:34 DEBUG - XRAY: ,
2024/03/29 23:55:34 DEBUG - XRAY: }
2024/03/29 23:55:34 DEBUG - XRAY: 0xc001204700
2024/03/29 23:55:34 DEBUG - XRAY: ,
2024/03/29 23:55:34 DEBUG - XRAY: 0x152b0e0
2024/03/29 23:55:34 DEBUG - XRAY: {
2024/03/29 23:55:34 DEBUG - XRAY: (
2024/03/29 23:55:34 DEBUG - XRAY: github.com/xtls/xray-core/common/buf.WriteMultiBuffer
2024/03/29 23:55:34 DEBUG - XRAY: 0x496
2024/03/29 23:55:34 DEBUG - XRAY: +
2024/03/29 23:55:34 DEBUG - XRAY: 376
2024/03/29 23:55:34 DEBUG - XRAY: :
2024/03/29 23:55:34 DEBUG - XRAY: github.com/xtls/xray-core/proxy/freedom/freedom.go
2024/03/29 23:55:34 DEBUG - XRAY: )
2024/03/29 23:55:34 DEBUG - XRAY: }
2024/03/29 23:55:34 DEBUG - XRAY: 0x1fe6
2024/03/29 23:55:34 DEBUG - XRAY: ,
2024/03/29 23:55:34 DEBUG - XRAY: 0xd9
2024/03/29 23:55:34 DEBUG - XRAY: ,
2024/03/29 23:55:34 DEBUG - XRAY: 0xc000ad201a
2024/03/29 23:55:34 DEBUG - XRAY: {
2024/03/29 23:55:34 DEBUG - XRAY: ,
2024/03/29 23:55:34 DEBUG - XRAY: 0xc001204700
2024/03/29 23:55:34 DEBUG - XRAY: (
2024/03/29 23:55:34 DEBUG - XRAY: github.com/xtls/xray-core/proxy/freedom.(*FragmentWriter).Write
2024/03/29 23:55:34 DEBUG - XRAY: ]:
2024/03/29 23:55:34 DEBUG - XRAY: running
2024/03/29 23:55:34 DEBUG - XRAY: [
2024/03/29 23:55:34 DEBUG - XRAY: 157532
2024/03/29 23:55:34 DEBUG - XRAY: goroutine
2024/03/29 23:55:34 DEBUG - XRAY: runtime error: slice bounds out of range [:61150] with capacity 8166
2024/03/29 23:55:34 DEBUG - XRAY: panic:

===============================================

2024/03/31 19:12:41 DEBUG - X-UI: restart xray, force:false
2024/03/31 19:12:39 DEBUG - XRAY: github.com/xtls/xray-core/common/buf.(*SequentialWriter).WriteMultiBuffer(0xc001c807b0?, {0xc00187f9d8?, 0xc001b34b20?, 0xc0017a0da8?})
2024/03/31 19:12:39 DEBUG - XRAY: panic: runtime error: slice bounds out of range [:10345] with capacity 8166

===============================================

2024/03/31 20:54:39 DEBUG - X-UI: restart xray, force:false
2024/03/31 20:54:37 DEBUG - XRAY: panic: runtime error: slice bounds out of range [:8288] with capacity 8166

===============================================

2024/03/31 19:11:05 DEBUG - X-UI: restart xray, force:false
2024/03/31 19:11:03 DEBUG - XRAY: panic: runtime error: slice bounds out of range [:61780] with capacity 8166

**Comment by chika0801** [comment]
Looking at the logs you are using XUI of this type, try updating core to 1.8.10.

If you can install Xray manually, try installing it manually with some config files.

No one has reported a similar problem to yours for now. If you want help from others, demand to describe the problem and provide information as much as possible.

**Comment by yuhan6665** [comment]
You need to see error log file, see xray docs

**Comment by chika0801** [comment]
> Hello, thanks for the quick reply! I upgraded to 1.8.10, and the issue has gotten a lot better, but it still restarted a few times.
> and what kind of other information should I provide?

There are modifications of XUI by different authors, and you should say whose version you are using.
You need to post a screenshot of what protocol combination you have set up in XUI.

With this kind of problem, first of all if you suspect that it is a problem with the XRAY version upgrade, you should switch other versions and find the version number that doesn't have the problem. (You can try this)

Assuming that the problem is with version 1.8.9, you could do this by the principle of controlling variables, such as keeping the XUI version the same, opening the same protocol combinations in the same way, installing on a different VPS, making the same configurations, and seeing if the XRAY error reported by XUI will repeat itself.

Instead of just posting an XUI log, this behavior does not help anyone trying to help you. You should do basic troubleshooting tests yourself first when something goes wrong.

The principle of handling it this way .

Translated with DeepL.com (free version)

**Comment by yuhan6665** [comment]
@HamedX2Z  have you turn on fragmentation in server side? Please post your full configs

**Comment by yuhan6665** [comment]
最新的 main 应该修好了 https://github.com/XTLS/Xray-core/actions/runs/8584964230
~~虽然我认为你不应该在服务端用 fragment~~

**Comment by omidbarzegaran** [comment]
> Please export full stack trace. The fragment above is not enough to fix issue.

Likeeeeeeee
