### ISSUE TITLE
libxray.so占用异常

### ISSUE THREAD

**Issue by CraneSleep** [XTLS/Xray-core#3219]
安卓设备，miui14，偶然发现手机特别卡，看进程管理器发现libxray把cpu吃满了，重启该进程后恢复正常
![Screenshot_2024-04-02-09-02-03-530_com omarea vtools](https://github.com/XTLS/Xray-core/assets/83820216/77227f3b-49c7-4025-bf13-0ce2cf9a5138)

**Comment by chika0801** [comment]
下次遇到，自己再这样处理一下就是了，你发这样的内容没什么用。
