### ISSUE TITLE
Memory leak 

### ISSUE THREAD

**Issue by erfan-khadem** [XTLS/Xray-core#3221]
There is / has been a memory leak issue since at least version 1.8.9. I have tested the latest release, and it is leaking at a rate of about 1.7 GB for every 100 GB of traffic proxied, during a time frame of 24 hours and with 50 active users. I have not done experiments to correlate these numbers with each other, but it seems like the amount of leaked memory is proportional to the served traffic. There is also no ceiling to this, it just grows until `systemd-oomd` kills it. I have tried using `vless only`, `vless+vmess` and `vless+trojan`, and avoided the newly added transports but to no avail. I would be more than happy to experiment more and provide the team with more information. I am running `xray` behind `haproxy` and that behind cloudflare CDN.

OS: `Ubuntu 22.04`, all packages up-to-date.
Architecture: `Armv8`, Neoverse-N1 at Hetzner. Also generic `x86` platforms.
Memory: 4GB
Kernel: `Generic Ubuntu 5.15.0-xxx`
Logging: Disabled

**Comment by er888kh** [comment]
[heap.zip](https://github.com/XTLS/Xray-core/files/14843933/heap.zip)
Here is the result of heap profiling using `pprof`. memory usage was about 800MB when I took this profile.

**Comment by GFW-knocker** [comment]
@er888kh 
what kind of transmission do you use?
i know that grpc has memory leak in 1.8.0+ above
but ws is rather fine in my experience

**Comment by RPRX** [comment]
> same problem , in my experience , version 1.8.4 is fine , and after that version , xray will leak

麻烦逐个测试 v1.8.4 至 v1.8.6 之间的 commits，看一下哪个 commit 出现该问题

@er888kh 你那边也是这样吗？

**Comment by yuhan6665** [comment]
> [heap.zip](https://github.com/XTLS/Xray-core/files/14843933/heap.zip) Here is the result of heap profiling using `pprof`. memory usage was about 800MB when I took this profile.

From this pprof, the biggest is at readv reader with 220MB. Although I'm not sure if this is indeed a leak. Can you profile a bigger usage?

**Comment by amirhosss** [comment]
> Same issue on MT7981A (ARM64, cortex A53) with 512MB RAM, have try 1.8.4 and 1.8.10, both consume all RAM on device after first speedtest running and hangs

Same problem when running speedtest with chain-proxy config and using Xray-Core

**Comment by taoabc** [comment]
Same problem

**Comment by shakibamoshiri** [comment]
my VM faced an OS crash yesterday because of OOM.

here is the screenshot of the console after the crash
![xray-memory-leak](https://github.com/XTLS/Xray-core/assets/18571844/60863c47-125f-45df-a3d2-f4078681ebb0)


never did profiling for xray , but could it be for memory leaks ?
protocol: `vless-grpc`
number of users: around `30/40`
number of concurrent users : `10/15`
OS : `Debian 11 x64`
physical memory: `1G`
swap : off
xray : `Xray 1.8.7 (Xray, Penetrates Everything.) 3f0bc13 (go1.21.5 linux/amd64)`

total-vm: `2558796KB`
anon-rss: `561376KB`
file-rss: `0KB`

 _did not have full console access and so was not able to recover the OS; I had to rebuild it and no further logs_

**Comment by taoabc** [comment]
> my VM faced an OS crash yesterday because of OOM.
> 
> here is the screenshot of the console after the crash ![xray-memory-leak](https://private-user-images.githubusercontent.com/18571844/331126050-60863c47-125f-45df-a3d2-f4078681ebb0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MTU2NDgsIm5iZiI6MTcxNTkxNTM0OCwicGF0aCI6Ii8xODU3MTg0NC8zMzExMjYwNTAtNjA4NjNjNDctMTI1Zi00NWRmLWEzZDItZjQwNzg2ODFlYmIwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDAzMDkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1YmE2Njk4NzcwZGJiZDliOTM5ZGRjZDYyNjA2NjNhYjg4MDVmZjQ5YTZiNjZlYzE0NTVmYzdjNTIyMGJmYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qlZiVI44tq6nKrGXoM6dzVn7S9CjEb98NqVcaBjcm0U)
> 
> never did profiling for xray , but could it be for memory leaks ? protocol: `vless-grpc` number of users: around `30/40` number of concurrent users : `10/15` OS : `Debian 11 x64` physical memory: `1G` swap : off xray : `Xray 1.8.7 (Xray, Penetrates Everything.) 3f0bc13 (go1.21.5 linux/amd64)`
> 
> total-vm: `2558796KB` anon-rss: `561376KB` file-rss: `0KB`
> 
> **which protocol has the least memory leak ?**
> 
> _did not have full console access and so was not able to recover the OS; I had to rebuild it and no further logs_

I updated to 1.8.11, seems it's been mitigated. While it's easy to repro when I use 1.8.10

**Comment by EldestBard** [comment]
same problem on the latest version 1.18.13.
![image](https://github.com/XTLS/Xray-core/assets/20218235/56f0b5c3-1c3a-44c1-af17-1ac519582923)

**Comment by masbur** [comment]
I'm using version 1.8.16 and problem solved. except shadowsocks2022, still leak
![image](https://github.com/XTLS/Xray-core/assets/16659305/3e6ccf34-d9ba-44af-9339-b0b463161405)

**Comment by M03ED** [comment]
there is similar report's in marzban
https://github.com/Gozargah/Marzban/issues/1062
https://github.com/Gozargah/Marzban/issues/992|
https://github.com/Gozargah/Marzban/issues/814

**Comment by majidsadr** [comment]
@M03ED just in case what I was facing was not OOM issue. I couldn't find any reason for the issue. but with another configuration (WS+VMESS) I have about 5k sockstat TCP metrics and there are no issues with connections.

**Comment by boris768** [comment]
i checked original v2ray repository and found same bug
https://github.com/v2fly/v2ray-core/issues/3086

I used the patch from the bug and it seems to have helped with the big leak, at least the process doesn't eat memory as aggressively. tested on 1.8.23 release code

place to patch
https://github.com/XTLS/Xray-core/blob/41d03d1856a5b16521610792601a20fb1195418e/transport/pipe/impl.go#L92

**Comment by mmmray** [comment]
@boris768 Then it seems the real issue might be that some pipe is not correctly closed somewhere, or generally resources are not cleaned up in some inbound/outbound or transport. Unfortunately this patch has the ability to work around a variety of different issues, it doesn't really explain what's going on IMO

**Comment by boris768** [comment]
@mmmray, i testing this patch, that can be used as hack way to fix memory leak. I using simple XTLS-Reality setup and without fix 8-10 clients gives xray memory usage up to 700-800 mb in one day (OOM kills service). With fix,  memory peak usage reaches 150mb. 
At least, it gives info about mem leak place, i hope, it will help to fix.

**Comment by M03ED** [comment]
Is the problem solved ?

**Comment by mmmray** [comment]
Not **completed**, but it's missing too much information, nobody has investigated it much, and it's not clear if this is 1 issue or N issues. As a developer I also wouldn't know what to do with it right now. I guess, let's reopen when somebody has managed to make another heap profile. I think the patch cannot help with this, to be honest.

**Comment by 50infivedays** [comment]
after a long time of testing , it appears that this is not a memory leak , after i upgrade my machine to larger memory , this problem won't happen, maybe the newer version is just using much more memory .

**Comment by wrk6** [comment]
> after a long time of testing , it appears that this is not a memory leak , after i upgrade my machine to larger memory , this problem won't happen, maybe the newer version is just using much more memory .

You think that 64 gb is not enough?

**Comment by Muxa1L** [comment]
To me it helped to set env var GOMEMLIMIT="70MiB". 
Maybe it would be enough to just set GOGC to something like 50.
I'm running xray on router with 512MB mem, and so it's so low.
here is the graph. Added it at ~ 10:15
<img width="1704" height="682" alt="Image" src="https://github.com/user-attachments/assets/147af10b-72f6-407c-99d7-9e4d4fe20f72" />
