### ISSUE TITLE
升级到1.8.10后ws访问404

### ISSUE THREAD

**Issue by freeNestor** [XTLS/Xray-core#3222]
问题现象：服务端从1.8.7升级到1.8.10后（配置不变动），客户端(clash)访问服务端ng响应404（使用ws），降级回到1.8.7版本后正常。日志中没有其他报错。

服务端配置：
```
...
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": xxxx,
      "protocol": "trojan",
      "settings": {
        "clients": [
          {
            "password": "xxx"
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "acceptProxyProtocol": false,
          "path": "/xxx",
          "headers": {
            "host": "xxx.xy"
          }
        }
      }
    }
  ],
...
```

**Comment by Fangliding** [comment]
emmm 这里该不该要求match还是有点伤脑筋呢

**Comment by yuhan6665** [comment]
> emmm 这里该不该要求match还是有点伤脑筋呢

我是抄了 httpupgrade ;)

**Comment by Fangliding** [comment]
> > emmm 这里该不该要求match还是有点伤脑筋呢
> 
> 我是抄了 httpupgrade ;)

我之前以为服务端应该不会有人加的（）
果然稍微break一点东西就一堆人出事啊

**Comment by chika0801** [comment]
"headers": {
            "host": "xxx.xy"
          }


你服务端有这个，10版本要求客户端也要有对应的，会服务端会校验，解决方法去了就是。

**Comment by RPRX** [comment]
https://github.com/loyess/Shell/issues/122#issuecomment-2028584878

**Comment by freeNestor** [comment]
> "headers": { "host": "xxx.xy" }
> 
> 你服务端有这个，10版本要求客户端也要有对应的，会服务端会校验，解决方法去了就是。

clash客户端配置header了，但不行。好吧，最后ng上强制指定host可以了，可能是ng这里header被重写了？

**Comment by chika0801** [comment]
不用clash/c meta不清楚和10版本兼容怎样了。

**Comment by lys811074556** [comment]
大家好我问下载core文件了，怎么还是连接不上网络呀？

**Comment by aiastia** [comment]
> “标题”：{ “主机”：“xxx.xy” }
> 
> 如果你服务端有这个，10版本要求客户端也要有相应的，会服务端会检查，解决方案就是那个。

如果套了cf 的情况下 取消host 会连不上……感觉整个机制有点鸡肋

**Comment by cute** [comment]
@RPRX 

自Xray 1.8.10 开始，websocket 域名验证的方式是错误的。如果服务器使用不是默认端口，按照HTTP规定应该在Host里发送端口。如果客户端发送了端口，服务端则直接报错。

**Comment by yuhan6665** [comment]
@cute 感谢提醒 改成子字符串匹配了 https://github.com/XTLS/Xray-core/commit/4c516367886014ce98fa17cd8b0f20bd434c6e92

**Comment by cute** [comment]
@yuhan6665  

建议使用 net.SplitHostPort 处理 request.Host，进行 host 比较。

按照规范域名应该使用小写字母。

如果使用 strings.Contains, 服务端设置 www.example.com, 
那么客户端发送 www.example.com 里的任何一部分都是可以通过的。

**Comment by yuhan6665** [comment]
Done https://github.com/XTLS/Xray-core/commit/b8c0768b166a9963bc9529a88a3f20493a7e7d48

**Comment by kang000feng** [comment]
> > "headers": { "host": "xxx.xy" }
> 
> > 
> 
> > 你服务端有这个，10版本要求客户端也要有对应的，会服务端会校验，解决方法去了就是。
> 
> 
> 
> clash客户端配置header了，但不行。好吧，最后ng上强制指定host可以了，可能是ng这里header被重写了？

请问ng上如何强制指定host? 能否给个示例参考一下？ 謝謝

**Comment by freeNestor** [comment]
> > > "headers": { "host": "xxx.xy" }
> > 
> > 
> > > 
> > 
> > 
> > > 你服务端有这个，10版本要求客户端也要有对应的，会服务端会校验，解决方法去了就是。
> > 
> > 
> > clash客户端配置header了，但不行。好吧，最后ng上强制指定host可以了，可能是ng这里header被重写了？
> 
> 请问ng上如何强制指定host? 能否给个示例参考一下？ 謝謝

proxy_set_header Host $host;
