### ISSUE TITLE
能把服务器收到的域名重新发给客户端吗？

### ISSUE THREAD

**Issue by cygauss** [XTLS/Xray-core#3223]
比如像服务器屏蔽回国流量，block geoip:cn to blackhole。能否将该域名（ip）重新发给客户端，然后让客户端在国内直连该域名（ip）。或者有什么比较优的路由方案？

**Comment by cygauss** [comment]
利用xray的方向代理功能貌似可以让网站流量＞客户端》服务器》客户端 (＞指直连,》指代理)，但我翻了下文档，没找到怎么直接让客户端去访问还漏网之鱼。

**Comment by Fangliding** [comment]
你就不能在客户端把geoio:cn 直连吗

**Comment by cygauss** [comment]
> 你就不能在客户端把geoip:cn 直连吗

服务器和客户端同域名查询ip不同的情况，如果我想对可能有国内外不同ip的网站，访问其国外ip,就需要在服务器对它进行解析。那么就需要客户端把他放行到服务器。
问题就出在该网站其实只有一个国内ip，那么按照屏蔽国内流量，它就直接进黑洞了。这个时候就必须调整客户端分流，让它走直连，问题是调整总不可能都靠人工添加吧。

**Comment by chika0801** [comment]
他回你的意思是，你在客户端，可以把域名解析了，看是不是cnip，是这请求就直连出。

如果你在客户端不搞这步或假设这请求发到了服务端，这请求不能像你想的以回客户端的。你要么在服务端，把这请求最终blocl了，或进warp，或送到你另外台国外vps，让那台vps访问，都是方法

**Comment by cygauss** [comment]
我找到了一个方案，出站有dns这个协议，让客户端接受服务器处的dns解析结果再进行路由。这样服务器也不用嗅域名了。

**Comment by chika0801** [comment]
那你问，就要说具体客户端是什么，比如win openwrt v2rayng?

**Comment by Fangliding** [comment]
> > 你就不能在客户端把geoip:cn 直连吗
> 
> 服务器和客户端同域名查询ip不同的情况，如果我想对可能有国内外不同ip的网站，访问其国外ip,就需要在服务器对它进行解析。那么就需要客户端把他放行到服务器。 问题就出在该网站其实只有一个国内ip，那么按照屏蔽国内流量，它就直接进黑洞了。这个时候就必须调整客户端分流，让它走直连，问题是调整总不可能都靠人工添加吧。

ipondemand丢去服务端解析 然后再判断ip不就行了 只要你受得了每次查询都额外去服务器走一次的延迟

**Comment by cygauss** [comment]
> 那你问，就要说具体客户端是什么，比如win openwrt v2rayng?

😭xray-core.exe

**Comment by ashton2914** [comment]
> 我想到了一个方法，出站有dns这个协议，让客户端接受服务器处的dns解析结果再进行路由。这样服务器也不用嗅域名了。就是不知道可行不。

据我所知sing-box上可以实现你的想法，但可能跟你脑海中的那个思路不太一样

你可以写个国外的DNS服务，比如google的，然后使用你的代理出站来访问这个DNS服务器`＂detour＂： proxy，你可以配置在本地解析全部域名，然后再按照解析出来的ip来分流

```

    "dns": {
        "servers": [
            {
                "tag": "dns_proxy",
                "address": "https://8.8.8.8/dns-query",
                "address_resolver": "dns_resolver",
                "strategy": "ipv4_only",
                "detour": "proxy"
            },
....

```

**Comment by ashton2914** [comment]
> > 我想到了一个方法，出站有dns这个协议，让客户端接受服务器处的dns解析结果再进行路由。这样服务器也不用嗅域名了。就是不知道可行不。
> 
> 据我所知sing-box上可以实现你的想法，但可能跟你脑海中的那个思路不太一样
> 
> 你可以写个国外的DNS服务，比如google的，然后使用你的代理出站来访问这个DNS服务器`＂detour＂： proxy`，你可以配置在本地解析全部域名，然后再按照解析出来的ip来分流
> 
> ```
> 
>     "dns": {
>         "servers": [
>             {
>                 "tag": "dns_proxy",
>                 "address": "https://8.8.8.8/dns-query",
>                 "address_resolver": "dns_resolver",
>                 "strategy": "ipv4_only",
>                 "detour": "proxy"
>             },
> ....
> 
> ```

xray应该也是可以的，应该可以把dns的出站通过配置路由改到你的服务器，但我基本只在服务端用xray所以没试过

另外客户端clash.meta也可以这么操作，通过设置dns为 `dns_server#proxy` 来指定dns服务器的出站

**Comment by cygauss** [comment]
搞远程dns查询，延迟太高，因小失大，我认为一个可及时调整分流的客户端（如v2raya）+服务器屏蔽回国ip其实就是最优解了。ip在国内+没在geoip记录+网站没有地域特征+会有大量回国流量的情况，我估计是遇不到了。

**Comment by Fangliding** [comment]
@cygauss 所以您觉得您这个奇怪的 "发回客户端" 就是量子通信不造成延迟么(

**Comment by cygauss** [comment]
> @cygauss 所以您觉得您这个奇怪的 "发回客户端" 就是量子通信不造成延迟么(

我这个奇怪的方法肯定是包括在里面的啊。我又不是什么亚空间人。
