### ISSUE TITLE
求助，流量统计存在可以利用的*特性*

### ISSUE THREAD

**Issue by SoHugePenguin** [XTLS/Xray-core#3226]
我在使用流量统计的api发现，下载大文件的时候如果不下完或者是手动掐掉，流量状态是不会增加下载的量的：
如下：我下载1GB的文件：
![image](https://github.com/XTLS/Xray-core/assets/100383563/fdeea533-c5c6-416f-b0b0-cae289aa5fd3)

下载过程中调用api发现数据明显不对，很小，只是普通的传输根本没有记录下载的大额记录：
![image](https://github.com/XTLS/Xray-core/assets/100383563/9301617b-806d-475c-9e39-55c576cd026d)

下完了，或者自己掐掉，会突然变正常，应该是一次会话结束开始结算了：
![image](https://github.com/XTLS/Xray-core/assets/100383563/36e14867-e5f7-4ecb-9c1d-432b7c20967b)

于是我在想，如果我下一个100G的包甚至更大，不是可以恶意将vps的流量全部洗劫一空？？汗流浃背了兄弟。
求助，这玩意有什么解决方案吗？nginx能限流吗？
我的xray配置： vless+xtls+reality

**Comment by Fangliding** [comment]
我寻思这VPS不是你自己的 自己洗劫自己呢 API本意是自己方便统计而不是防盗

**Comment by SoHugePenguin** [comment]
> 我寻思这VPS不是你自己的 自己洗劫自己呢 API本意是自己方便统计而不是防盗

呃，因为我在开发可以管理用户的流量使用情况来进行封禁操作什么的：
差不多这种：
![image](https://github.com/XTLS/Xray-core/assets/100383563/87635432-cc5e-4710-b233-01abfe347e52)

但是这个统计结算方法在我这个有流量*限制*的网站服务来说是一个致命的漏洞。

**Comment by SoHugePenguin** [comment]
> 我寻思这VPS不是你自己的 自己洗劫自己呢 API本意是自己方便统计而不是防盗

我就怕用户本来只有10G流量，但是它可以一直下，下个100G，这种。

**Comment by Fangliding** [comment]
> > 我寻思这VPS不是你自己的 自己洗劫自己呢 API本意是自己方便统计而不是防盗
> 
> 我就怕用户本来只有10G流量，但是它可以一直下，下个100G，这种。

要卖钱麻烦自己修(
而且限10G挺奸商的

**Comment by SoHugePenguin** [comment]
> * Someone create an issue and trying to say that something is not working as expected or working differently.
> * You want to sell it? Just fix it yourself.
>   That just solved everything. Thanks
> 
> What's the point of creating issues then? Maybe just close the issue tab from GitHub. Also what's the point of traffic statistics? Maybe you should remove the feature completely, or should i also do it myself? Maybe project need a template for creating issue or a way to filter out issues related to "Business purpose", instead of ignoring them.

Thank you. I will fork a branch myself to solve this problem

**Comment by Fangliding** [comment]
> * Someone create an issue and trying to say that something is not working as expected or working differently.
> * You want to sell it? Just fix it yourself.
>   That just solved everything. Thanks
> 
> What's the point of creating issues then? Maybe just close the issue tab from GitHub. Also what's the point of traffic statistics? Maybe you should remove the feature completely, or should i also do it myself? Maybe project need a template for creating issue or a way to filter out issues related to "Business purpose", instead of ignoring them.

Why do you iran guys always like to say "you should remove it completely"? This sentence has no meaning and is annoying
Just like we have obligation to provide free support for your business

**Comment by MK0ltra** [comment]
> > * Someone create an issue and trying to say that something is not working as expected or working differently.
> > * You want to sell it? Just fix it yourself.
> >   That just solved everything. Thanks
> > 
> > What's the point of creating issues then? Maybe just close the issue tab from GitHub. Also what's the point of traffic statistics? Maybe you should remove the feature completely, or should i also do it myself? Maybe project need a template for creating issue or a way to filter out issues related to "Business purpose", instead of ignoring them.
> 
> Why do you iran guys always like to say "you should remove it completely"? This sentence has no meaning and is annoying Just like we have obligation to provide free support for your business

Who says I'm Iranian? Nobody ask you to fix anything or provide support for anything. The guy just create an issue and you go mad about it.

**Comment by SoHugePenguin** [comment]
fork后研究了几天代码，发现这个问题是可以轻松解决的，特此来分享：

先说结论：
导致流量不实时的根本原因是默认开启了splice功能。

什么是splice？
splice是Linux系统中的一个系统调用，它允许在两个文件描述符之间直接移动数据，而无需将数据从内核空间复制到用户空间，再从用户空间复制回内核空间。这种机制大大减少了数据在用户空间和内核空间之间的来回复制，从而提高了数据传输的效率，特别是在处理大量数据时。

在linux部署xray，如果你在意用户流量实时性，请把splice给禁用了(window没事)。
要禁用splice我已知的有两种。
第一种是改配置文件：
见 [issue: 2570](https://github.com/XTLS/Xray-core/discussions/2570)

第二种是改环境变量，xray部署在docker的建议这样：

docker run:
加个环境变量参数 -e 指定xray.buf.splice 为disabled

docker-compose:
environment:
      TZ: "Asia/Shanghai"
      xray.buf.splice: "disabled" # auto/enable/NOT_DEFINED_AT_ALL 是开启

当然，这只是经验分享，如果你不需要像我一样做业务的，不在乎用户流量非常细微的实时情况的可以不用管。
希望能帮到后来人。

**Comment by willsilicon** [comment]
> fork后研究了几天代码，发现这个问题是可以轻松解决的，特此来分享：
> 
> 先说结论： 导致流量不实时的根本原因是默认开启了splice功能。
> 
> 什么是splice？ splice是Linux系统中的一个系统调用，它允许在两个文件描述符之间直接移动数据，而无需将数据从内核空间复制到用户空间，再从用户空间复制回内核空间。这种机制大大减少了数据在用户空间和内核空间之间的来回复制，从而提高了数据传输的效率，特别是在处理大量数据时。
> 
> 在linux部署xray，如果你在意用户流量实时性，请把splice给禁用了(window没事)。 要禁用splice我已知的有两种。 第一种是改配置文件： 见 [issue: 2570](https://github.com/XTLS/Xray-core/discussions/2570)
> 
> 第二种是改环境变量，xray部署在docker的建议这样：
> 
> docker run: 加个环境变量参数 -e 指定xray.buf.splice 为disabled
> 
> docker-compose: environment: TZ: "Asia/Shanghai" xray.buf.splice: "disabled" # auto/enable/NOT_DEFINED_AT_ALL 是开启
> 
> 当然，这只是经验分享，如果你不需要像我一样做业务的，不在乎用户流量非常细微的实时情况的可以不用管。 希望能帮到后来人。

关闭后对其他的性能有影响吗？我最近发现用了几天流量自己重置了，程序也没重启。

**Comment by SoHugePenguin** [comment]
> > fork后研究了几天代码，发现这个问题是可以轻松解决的，特此来分享：
> > 先说结论： 导致流量不实时的根本原因是默认开启了splice功能。
> > 什么是splice？ splice是Linux系统中的一个系统调用，它允许在两个文件描述符之间直接移动数据，而无需将数据从内核空间复制到用户空间，再从用户空间复制回内核空间。这种机制大大减少了数据在用户空间和内核空间之间的来回复制，从而提高了数据传输的效率，特别是在处理大量数据时。
> > 在linux部署xray，如果你在意用户流量实时性，请把splice给禁用了(window没事)。 要禁用splice我已知的有两种。 第一种是改配置文件： 见 [issue: 2570](https://github.com/XTLS/Xray-core/discussions/2570)
> > 第二种是改环境变量，xray部署在docker的建议这样：
> > docker run: 加个环境变量参数 -e 指定xray.buf.splice 为disabled
> > docker-compose: environment: TZ: "Asia/Shanghai" xray.buf.splice: "disabled" # auto/enable/NOT_DEFINED_AT_ALL 是开启
> > 当然，这只是经验分享，如果你不需要像我一样做业务的，不在乎用户流量非常细微的实时情况的可以不用管。 希望能帮到后来人。
> 
> 关闭后对其他的性能有影响吗？我最近发现用了几天流量自己重置了，程序也没重启。

性能上不会有明显差距，放心用。
至于你说的为什么记录没了，大概率是自动重启了吧，或者有谁调了api重置，这个我没遇到过

**Comment by willsilicon** [comment]
> > > fork后研究了几天代码，发现这个问题是可以轻松解决的，特此来分享：
> > > 先说结论： 导致流量不实时的根本原因是默认开启了splice功能。
> > > 什么是splice？ splice是Linux系统中的一个系统调用，它允许在两个文件描述符之间直接移动数据，而无需将数据从内核空间复制到用户空间，再从用户空间复制回内核空间。这种机制大大减少了数据在用户空间和内核空间之间的来回复制，从而提高了数据传输的效率，特别是在处理大量数据时。
> > > 在linux部署xray，如果你在意用户流量实时性，请把splice给禁用了(window没事)。 要禁用splice我已知的有两种。 第一种是改配置文件： 见 [issue: 2570](https://github.com/XTLS/Xray-core/discussions/2570)
> > > 第二种是改环境变量，xray部署在docker的建议这样：
> > > docker run: 加个环境变量参数 -e 指定xray.buf.splice 为disabled
> > > docker-compose: environment: TZ: "Asia/Shanghai" xray.buf.splice: "disabled" # auto/enable/NOT_DEFINED_AT_ALL 是开启
> > > 当然，这只是经验分享，如果你不需要像我一样做业务的，不在乎用户流量非常细微的实时情况的可以不用管。 希望能帮到后来人。
> > 
> > 
> > 关闭后对其他的性能有影响吗？我最近发现用了几天流量自己重置了，程序也没重启。
> 
> 性能上不会有明显差距，放心用。 至于你说的为什么记录没了，大概率是自动重启了吧，或者有谁调了api重置，这个我没遇到过

仔细看了一下时间确实是自动重启了，而且是我自己很久前写的定时任务忘记了，btw这边有些人态度确实不好，不要在意。
