### ISSUE TITLE
[Feature Request] balancer enhancement

### ISSUE THREAD

**Issue by Xray9** [XTLS/Xray-core#323]
目前的 [balancer](https://xtls.github.io/config/base/routing/#balancerobject) 的功能有些太过简陋（~~与文档中的 `选出一个最合适的outbound` 相去甚远~~），我觉得我们可以增强它，譬如可以加上一个可用性判断，以及更多

https://github.com/XTLS/Xray-core/blob/7fb1f6535481ca544dd6d167b93c9181af6a18dd/app/router/balancing.go#L15-L22

https://github.com/XTLS/Xray-core/blob/7fb1f6535481ca544dd6d167b93c9181af6a18dd/app/proxyman/outbound/outbound.go#L143-L164

**Comment by AkinoKaede** [comment]
v2fly/v2ray-core#589

**Comment by Xray9** [comment]
@AkinoKaede 这个pr很好啊， 决定了基于这个改改提到这边来

**Comment by rprx** [comment]
@Xray9 其实可以先合再改

**Comment by hronro** [comment]
link related PR #168

**Comment by lelemka0** [comment]
有任何进展吗
