### ISSUE TITLE
骂战issue(如果关注技术问题，可忽略此issue)

### ISSUE THREAD

**Issue by Angel0726** [XTLS/Xray-core#3233]

**Comment by Fangliding** [comment]
绝望

**Comment by iKira** [comment]
关掉吧，rubbish issue

**Comment by Angel0726** [comment]
> 绝望

牛批了，河北的一家婚纱店。用他家wifi之前用naive他家秒劫持域名。现在连他家wifi，下午reality就ping不到了。今天更能ping

**Comment by Smallthing** [comment]
弱智issus。。。建议删除
自己偷别人的wifi还上瘾了

**Comment by Angel0726** [comment]
> 弱智issus。。。建议删除 自己偷别人的wifi还上瘾了

你傻逼吧。
1、我去拍婚纱照。连人wifi就成偷了。
2、目的是告诉大家，个别位置WiFi有识别功能。
你真有病，素质低，不了解情况瞎逼逼，恶意揣测他人。什么玩意

**Comment by azzvx** [comment]
理论上公共WIFI都要向派出所备案的...所以使用外部WIFI需要小心点。我都是用家里的路由转发梯子流量的。

**Comment by shallbytwo** [comment]
> 理论上公共WIFI都要向派出所备案的...所以使用外部WIFI需要小心点。我都是用家里的路由转发梯子流量的。

为啥流量要从家里路由器上绕呢？

**Comment by azzvx** [comment]
> > 理论上公共WIFI都要向派出所备案的...所以使用外部WIFI需要小心点。我都是用家里的路由转发梯子流量的。
> 
> 我也是刚刚知道要备案，他们可能是备案了。但是酒店没有事情，近期我住了几个酒店都没问题。我估计大家主要也是出差、咖啡店(毕竟去婚纱店的是少数)。那是不是可以理解酒店是安全的。

一般酒店都有自己的网维，而且客户上外网很正常。

**Comment by boshiiwo** [comment]
据我测试，石家庄5G 已经 白名单了，偷自己的证书，连不上，换成微软的才连上，宽带无影响
在石家庄万象城商场里的公共wifi， 包括 使用微软的 域名也连不上

**Comment by Angel0726** [comment]
> 据我测试，石家庄5G 已经 白名单了，偷自己的证书，连不上，换成微软的才连上，宽带无影响 在石家庄万象城商场里的公共wifi， 包括 使用微软的 域名也连不上

5G白名单什么意思，5G不能翻墙？

**Comment by Smallthing** [comment]
> > 弱智issus。。。建议删除 自己偷别人的wifi还上瘾了
> 
> 你傻逼吧。 1、我去拍婚纱照。连人wifi就成偷了。 2、目的是告诉大家，个别位置WiFi有识别能力，现在是发现了婚纱店，其他使用者会不会也出去旅游，在酒店发现呢？去结婚拍婚纱照发现呢？去咖啡厅，在咖啡厅发现这种问题呢。 最后 你真有病，素质真低，不了解情况瞎逼逼，恶意揣测他人。什么玩意

骂人的精力拿来思考吧。多测试几次不会？一次ping不到就是事实了？有没有可能他的路由器里面有不好的东西呢？

**Comment by Zxis233** [comment]
无效issue，一没控制变量测试，二没日志
要我给你画个符祈祷域名加白吗？

**Comment by Fangliding** [comment]
要讨论麻烦友好讨论 再骂战就关了(

**Comment by Angel0726** [comment]
> 要讨论麻烦友好讨论 再骂战就关了(
我先改个标题，以免浪费公共资源。如果过段时间他没回复，我就关了，毕竟也要给他说话的权利
