### ISSUE TITLE
httpUpgrade必需添加?ed=2560，才可以正常连接

### ISSUE THREAD

**Issue by xqdoo00o** [XTLS/Xray-core#3242]
服务端配置文件：
```
        {
            "port": 80,
            "protocol": "vmess",
            "settings": {
                "clients": [
                    {
                        "id": "xxxx",
                        "security": "aes-128-gcm"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "httpUpgrade",
                "httpUpgradeSettings": {
                    "path": "/ws"
                }
            }
        },
```
看debug日志是跟vmess有关？
```
2024/04/06 17:24:05 [Info] [1728523188] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > context canceled
2024/04/06 17:26:10 [Info] [4256423397] app/proxyman/inbound: connection ends > proxy/vmess/encoding: failed to read request header > EOF
```
不添加?ed=2560，无法直连，也无法通过cf连接。报错如上。

xray版本:
Xray 1.8.10 (Xray, Penetrates Everything.) 07ed094 (go1.22.1 linux/arm64)

**Comment by yxmyxmyyy** [comment]
同样是加?ed=2560才能连上

**Comment by lxhao61** [comment]
> 服务端配置文件：
> 
> ```
>         {
>             "port": 80,
>             "protocol": "vmess",
>             "settings": {
>                 "clients": [
>                     {
>                         "id": "xxxx",
>                         "security": "aes-128-gcm"
>                     }
>                 ],
>                 "decryption": "none"
>             },
>             "streamSettings": {
>                 "network": "httpUpgrade",
>                 "httpUpgradeSettings": {
>                     "path": "/ws"
>                 }
>             }
>         },
> ```
> 
> 看debug日志是跟vmess有关？
> 
> ```
> 2024/04/06 17:24:05 [Info] [1728523188] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > context canceled
> 2024/04/06 17:26:10 [Info] [4256423397] app/proxyman/inbound: connection ends > proxy/vmess/encoding: failed to read request header > EOF
> ```
> 
> 不添加?ed=2560，无法直连，也无法通过cf连接。报错如上。
> 
> xray版本: Xray 1.8.10 (Xray, Penetrates Everything.) [07ed094](https://github.com/XTLS/Xray-core/commit/07ed0946b502fb00661925e60a449886ec14e95d) (go1.22.1 linux/arm64)

配置示例错误，四不像。

**Comment by xqdoo00o** [comment]
> > 服务端配置文件：
> > ```
> >         {
> >             "port": 80,
> >             "protocol": "vmess",
> >             "settings": {
> >                 "clients": [
> >                     {
> >                         "id": "xxxx",
> >                         "security": "aes-128-gcm"
> >                     }
> >                 ],
> >                 "decryption": "none"
> >             },
> >             "streamSettings": {
> >                 "network": "httpUpgrade",
> >                 "httpUpgradeSettings": {
> >                     "path": "/ws"
> >                 }
> >             }
> >         },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 看debug日志是跟vmess有关？
> > ```
> > 2024/04/06 17:24:05 [Info] [1728523188] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > context canceled
> > 2024/04/06 17:26:10 [Info] [4256423397] app/proxyman/inbound: connection ends > proxy/vmess/encoding: failed to read request header > EOF
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 不添加?ed=2560，无法直连，也无法通过cf连接。报错如上。
> > xray版本: Xray 1.8.10 (Xray, Penetrates Everything.) [07ed094](https://github.com/XTLS/Xray-core/commit/07ed0946b502fb00661925e60a449886ec14e95d) (go1.22.1 linux/arm64)
> 
> 配置示例错误，四不像。

看下issue标题。。。

**Comment by Qian119lsj** [comment]
原来是这样 我还以为不加tls不给连接,加上?ed=2560就能连了

**Comment by lxhao61** [comment]
> > > 服务端配置文件：
> > > ```
> > >         {
> > >             "port": 80,
> > >             "protocol": "vmess",
> > >             "settings": {
> > >                 "clients": [
> > >                     {
> > >                         "id": "xxxx",
> > >                         "security": "aes-128-gcm"
> > >                     }
> > >                 ],
> > >                 "decryption": "none"
> > >             },
> > >             "streamSettings": {
> > >                 "network": "httpUpgrade",
> > >                 "httpUpgradeSettings": {
> > >                     "path": "/ws"
> > >                 }
> > >             }
> > >         },
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 看debug日志是跟vmess有关？
> > > ```
> > > 2024/04/06 17:24:05 [Info] [1728523188] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > context canceled
> > > 2024/04/06 17:26:10 [Info] [4256423397] app/proxyman/inbound: connection ends > proxy/vmess/encoding: failed to read request header > EOF
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 不添加?ed=2560，无法直连，也无法通过cf连接。报错如上。
> > > xray版本: Xray 1.8.10 (Xray, Penetrates Everything.) [07ed094](https://github.com/XTLS/Xray-core/commit/07ed0946b502fb00661925e60a449886ec14e95d) (go1.22.1 linux/arm64)
> > 
> > 
> > 配置示例错误，四不像。
> 
> 看下issue标题。。。



> > > 服务端配置文件：
> > > ```
> > >         {
> > >             "port": 80,
> > >             "protocol": "vmess",
> > >             "settings": {
> > >                 "clients": [
> > >                     {
> > >                         "id": "xxxx",
> > >                         "security": "aes-128-gcm"
> > >                     }
> > >                 ],
> > >                 "decryption": "none"
> > >             },
> > >             "streamSettings": {
> > >                 "network": "httpUpgrade",
> > >                 "httpUpgradeSettings": {
> > >                     "path": "/ws"
> > >                 }
> > >             }
> > >         },
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 看debug日志是跟vmess有关？
> > > ```
> > > 2024/04/06 17:24:05 [Info] [1728523188] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > context canceled
> > > 2024/04/06 17:26:10 [Info] [4256423397] app/proxyman/inbound: connection ends > proxy/vmess/encoding: failed to read request header > EOF
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 不添加?ed=2560，无法直连，也无法通过cf连接。报错如上。
> > > xray版本: Xray 1.8.10 (Xray, Penetrates Everything.) [07ed094](https://github.com/XTLS/Xray-core/commit/07ed0946b502fb00661925e60a449886ec14e95d) (go1.22.1 linux/arm64)
> > 
> > 
> > 配置示例错误，四不像。
> 
> 看下issue标题。。。



> > > 服务端配置文件：
> > > ```
> > >         {
> > >             "port": 80,
> > >             "protocol": "vmess",
> > >             "settings": {
> > >                 "clients": [
> > >                     {
> > >                         "id": "xxxx",
> > >                         "security": "aes-128-gcm"
> > >                     }
> > >                 ],
> > >                 "decryption": "none"
> > >             },
> > >             "streamSettings": {
> > >                 "network": "httpUpgrade",
> > >                 "httpUpgradeSettings": {
> > >                     "path": "/ws"
> > >                 }
> > >             }
> > >         },
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 看debug日志是跟vmess有关？
> > > ```
> > > 2024/04/06 17:24:05 [Info] [1728523188] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > context canceled
> > > 2024/04/06 17:26:10 [Info] [4256423397] app/proxyman/inbound: connection ends > proxy/vmess/encoding: failed to read request header > EOF
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 不添加?ed=2560，无法直连，也无法通过cf连接。报错如上。
> > > xray版本: Xray 1.8.10 (Xray, Penetrates Everything.) [07ed094](https://github.com/XTLS/Xray-core/commit/07ed0946b502fb00661925e60a449886ec14e95d) (go1.22.1 linux/arm64)
> > 
> > 
> > 配置示例错误，四不像。
> 
> 看下issue标题。。。



> > > 服务端配置文件：
> > > ```
> > >         {
> > >             "port": 80,
> > >             "protocol": "vmess",
> > >             "settings": {
> > >                 "clients": [
> > >                     {
> > >                         "id": "xxxx",
> > >                         "security": "aes-128-gcm"
> > >                     }
> > >                 ],
> > >                 "decryption": "none"
> > >             },
> > >             "streamSettings": {
> > >                 "network": "httpUpgrade",
> > >                 "httpUpgradeSettings": {
> > >                     "path": "/ws"
> > >                 }
> > >             }
> > >         },
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 看debug日志是跟vmess有关？
> > > ```
> > > 2024/04/06 17:24:05 [Info] [1728523188] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > context canceled
> > > 2024/04/06 17:26:10 [Info] [4256423397] app/proxyman/inbound: connection ends > proxy/vmess/encoding: failed to read request header > EOF
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 不添加?ed=2560，无法直连，也无法通过cf连接。报错如上。
> > > xray版本: Xray 1.8.10 (Xray, Penetrates Everything.) [07ed094](https://github.com/XTLS/Xray-core/commit/07ed0946b502fb00661925e60a449886ec14e95d) (go1.22.1 linux/arm64)
> > 
> > 
> > 配置示例错误，四不像。
> 
> 看下issue标题。。。

难道可以仅 issue 标题正确，其内容可以随便乱写！

**Comment by xqdoo00o** [comment]
> > > > 服务端配置文件：
> > > > ```
> > > >         {
> > > >             "port": 80,
> > > >             "protocol": "vmess",
> > > >             "settings": {
> > > >                 "clients": [
> > > >                     {
> > > >                         "id": "xxxx",
> > > >                         "security": "aes-128-gcm"
> > > >                     }
> > > >                 ],
> > > >                 "decryption": "none"
> > > >             },
> > > >             "streamSettings": {
> > > >                 "network": "httpUpgrade",
> > > >                 "httpUpgradeSettings": {
> > > >                     "path": "/ws"
> > > >                 }
> > > >             }
> > > >         },
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 看debug日志是跟vmess有关？
> > > > ```
> > > > 2024/04/06 17:24:05 [Info] [1728523188] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > context canceled
> > > > 2024/04/06 17:26:10 [Info] [4256423397] app/proxyman/inbound: connection ends > proxy/vmess/encoding: failed to read request header > EOF
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 不添加?ed=2560，无法直连，也无法通过cf连接。报错如上。
> > > > xray版本: Xray 1.8.10 (Xray, Penetrates Everything.) [07ed094](https://github.com/XTLS/Xray-core/commit/07ed0946b502fb00661925e60a449886ec14e95d) (go1.22.1 linux/arm64)
> > > 
> > > 
> > > 配置示例错误，四不像。
> > 
> > 
> > 看下issue标题。。。
> 
> 难道可以仅 issue 标题写明白，其下内容可以随便乱写！

。。。你好歹试试再评论吧，其他人也有这个问题的。。

**Comment by lxhao61** [comment]
> > > > > 服务端配置文件：
> > > > > ```
> > > > >         {
> > > > >             "port": 80,
> > > > >             "protocol": "vmess",
> > > > >             "settings": {
> > > > >                 "clients": [
> > > > >                     {
> > > > >                         "id": "xxxx",
> > > > >                         "security": "aes-128-gcm"
> > > > >                     }
> > > > >                 ],
> > > > >                 "decryption": "none"
> > > > >             },
> > > > >             "streamSettings": {
> > > > >                 "network": "httpUpgrade",
> > > > >                 "httpUpgradeSettings": {
> > > > >                     "path": "/ws"
> > > > >                 }
> > > > >             }
> > > > >         },
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 看debug日志是跟vmess有关？
> > > > > ```
> > > > > 2024/04/06 17:24:05 [Info] [1728523188] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > context canceled
> > > > > 2024/04/06 17:26:10 [Info] [4256423397] app/proxyman/inbound: connection ends > proxy/vmess/encoding: failed to read request header > EOF
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 不添加?ed=2560，无法直连，也无法通过cf连接。报错如上。
> > > > > xray版本: Xray 1.8.10 (Xray, Penetrates Everything.) [07ed094](https://github.com/XTLS/Xray-core/commit/07ed0946b502fb00661925e60a449886ec14e95d) (go1.22.1 linux/arm64)
> > > > 
> > > > 
> > > > 配置示例错误，四不像。
> > > 
> > > 
> > > 看下issue标题。。。
> > 
> > 
> > 难道可以仅 issue 标题写明白，其下内容可以随便乱写！
> 
> 。。。你好歹试试再评论吧，其他人也有这个问题的。。

没有说这个问题不存在或其它！我回复就是提醒你，你提供的配置示例写错了会造成其它人认为你配置错误造成的。

**Comment by xqdoo00o** [comment]
> > > > > > 服务端配置文件：
> > > > > > ```
> > > > > >         {
> > > > > >             "port": 80,
> > > > > >             "protocol": "vmess",
> > > > > >             "settings": {
> > > > > >                 "clients": [
> > > > > >                     {
> > > > > >                         "id": "xxxx",
> > > > > >                         "security": "aes-128-gcm"
> > > > > >                     }
> > > > > >                 ],
> > > > > >                 "decryption": "none"
> > > > > >             },
> > > > > >             "streamSettings": {
> > > > > >                 "network": "httpUpgrade",
> > > > > >                 "httpUpgradeSettings": {
> > > > > >                     "path": "/ws"
> > > > > >                 }
> > > > > >             }
> > > > > >         },
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > 看debug日志是跟vmess有关？
> > > > > > ```
> > > > > > 2024/04/06 17:24:05 [Info] [1728523188] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > context canceled
> > > > > > 2024/04/06 17:26:10 [Info] [4256423397] app/proxyman/inbound: connection ends > proxy/vmess/encoding: failed to read request header > EOF
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > 不添加?ed=2560，无法直连，也无法通过cf连接。报错如上。
> > > > > > xray版本: Xray 1.8.10 (Xray, Penetrates Everything.) [07ed094](https://github.com/XTLS/Xray-core/commit/07ed0946b502fb00661925e60a449886ec14e95d) (go1.22.1 linux/arm64)
> > > > > 
> > > > > 
> > > > > 配置示例错误，四不像。
> > > > 
> > > > 
> > > > 看下issue标题。。。
> > > 
> > > 
> > > 难道可以仅 issue 标题写明白，其下内容可以随便乱写！
> > 
> > 
> > 。。。你好歹试试再评论吧，其他人也有这个问题的。。
> 
> 没有说这个问题不存在或其它！我回复就是提醒你，你提供的配置示例写错了会造成其它人认为你配置错误造成的。

咱就说，能不能试试 再说我配置示例写错了。。

**Comment by lxhao61** [comment]
> > > > > > > 服务端配置文件：
> > > > > > > ```
> > > > > > >         {
> > > > > > >             "port": 80,
> > > > > > >             "protocol": "vmess",
> > > > > > >             "settings": {
> > > > > > >                 "clients": [
> > > > > > >                     {
> > > > > > >                         "id": "xxxx",
> > > > > > >                         "security": "aes-128-gcm"
> > > > > > >                     }
> > > > > > >                 ],
> > > > > > >                 "decryption": "none"
> > > > > > >             },
> > > > > > >             "streamSettings": {
> > > > > > >                 "network": "httpUpgrade",
> > > > > > >                 "httpUpgradeSettings": {
> > > > > > >                     "path": "/ws"
> > > > > > >                 }
> > > > > > >             }
> > > > > > >         },
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > >     
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >     
> > > > > > >   
> > > > > > > 看debug日志是跟vmess有关？
> > > > > > > ```
> > > > > > > 2024/04/06 17:24:05 [Info] [1728523188] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > context canceled
> > > > > > > 2024/04/06 17:26:10 [Info] [4256423397] app/proxyman/inbound: connection ends > proxy/vmess/encoding: failed to read request header > EOF
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > >     
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >     
> > > > > > >   
> > > > > > > 不添加?ed=2560，无法直连，也无法通过cf连接。报错如上。
> > > > > > > xray版本: Xray 1.8.10 (Xray, Penetrates Everything.) [07ed094](https://github.com/XTLS/Xray-core/commit/07ed0946b502fb00661925e60a449886ec14e95d) (go1.22.1 linux/arm64)
> > > > > > 
> > > > > > 
> > > > > > 配置示例错误，四不像。
> > > > > 
> > > > > 
> > > > > 看下issue标题。。。
> > > > 
> > > > 
> > > > 难道可以仅 issue 标题写明白，其下内容可以随便乱写！
> > > 
> > > 
> > > 。。。你好歹试试再评论吧，其他人也有这个问题的。。
> > 
> > 
> > 没有说这个问题不存在或其它！我回复就是提醒你，你提供的配置示例写错了会造成其它人认为你配置错误造成的。
> 
> 咱就说，能不能试试 再说我配置示例写错了。。

晕！！按照你现在提供的错误配置，不能可能测试！自己检查错误在什么地方？https://xtls.github.io/config/inbounds/vmess.html

**Comment by AsenHu** [comment]
> 晕！！按照你现在提供的错误配置，不可能测试！自己检查错误在什么地方？https://xtls.github.io/config/inbounds/vmess.html

你们能不能把引用删一下啊，叠这么长？

**Comment by Qian119lsj** [comment]
服务端inbounds
```
{
        "port": 5205,
        "protocol": "vmess",
        "settings": {
          "clients": [
            {
              "id": "a907048d-42f5-40b4-aaaa-5e37820daf20"
            }
          ]
        },
        "streamSettings": {
          "network": "httpupgrade",
          "security": "none",
          "httpupgradeSettings": {
            "path": "/ws"
          }
        }
}
```

客户端outbounds
```
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "1.1.1.1",
            "port": 80,
            "users": [
              {
                "id": "a907048d-42f5-40b4-8706-5e37820daf20",
                "alterId": 0,
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "httpupgrade",
        "httpupgradeSettings": {
          "path": "/ws"
        }
      }
    }
```

**Comment by lxhao61** [comment]
> > 晕！！按照你现在提供的错误配置，不可能测试！自己检查错误在什么地方？https://xtls.github.io/config/inbounds/vmess.html
> 
> 你们能不能把引用删一下啊，叠这么长？

是的，叠太长了。
一个示例配置被弄成 VMess 与 VLESS 的服务端与客户端四不像的组合，提醒他还不明白，无语！

**Comment by xqdoo00o** [comment]
> > 你们能不能把引用删一下啊，叠这么长？
> 
> 是的，叠太长了。 一个示例配置被弄成 VMess 与 VLESS 的服务端与客户端四不像的组合，提醒他还不明白，无语！

1，确实是弄混了，但是vless服务端配置改成vmess，只把l改成m就可以用。2, 多出来的客户端字段没啥用，但是写着也没问题。
参考楼上大佬写的配置。

**Comment by xqdoo00o** [comment]
依然报这个错误，服务端和客户端都已升级1.8.11
`2024/04/26 15:39:23 [Info] [3886561446] app/proxyman/inbound: connection ends > proxy/vmess/encoding: failed to read request header > EOF`
