### ISSUE TITLE
httpupgradeSettings is required field, wsSettings is not

### ISSUE THREAD

**Issue by mmmray** [XTLS/Xray-core#3244]
this is invalid config on latest release:

```
      "streamSettings": {
        "network": "httpupgrade"
      },
```

the error message is:

```
Failed to start: main: failed to create server > app/proxyman/outbound: failed to parse stream settings > transport/internet: unknown transport protocol: httpupgrade
```

that's surprising because this works:

```
      "streamSettings": {
        "network": "ws"
      },
```

in order to fix my httpupgrade config, i have to change it to:

```
      "streamSettings": {
        "network": "httpupgrade",
        "httpupgradeSettings": {}
      },
```

i traced this error message back to here: https://github.com/XTLS/Xray-core/blob/07ed0946b502fb00661925e60a449886ec14e95d/transport/internet/config.go#L64

and noticed that there is no ConfigCreator for httpupgrade, but there is one for websocket.

**Comment by Fangliding** [comment]
It should have been fixed. What is your xray version

**Comment by Fangliding** [comment]
@mmmray
Very Leeuwenhoek.
I already open a pull request to fix it.
Thank you.

**Comment by yuhan6665** [comment]
hmm I just noticed @mmmray is the poster started this one https://github.com/net4people/bbs/issues/281
Thanks for continuous contribution to the community from both of you!
