### ISSUE TITLE
请教一个转发证书的问题socks -> https

### ISSUE THREAD

**Issue by LOVECHEN** [XTLS/Xray-core#3259]
我把机器上的流量转发到xray-socks->然后把部分域名分流到我的proxyman进行分析，

无法获取正确的数据

如何让xray这里信任我的自签证书？

机器上已经安装自证书，直接抓包没问题。

补充

由于希望流量都走到同一个机器上，所以把流量先导向了xray-socks

**Comment by Fangliding** [comment]
tls配置里可以手动指定证书(散列)
