### ISSUE TITLE
clash连接VLESS-TCP-XTLS-Vision报错， proxy/vless/inbound: 8c5fb6b5-2e37-5ddd-a27f-18b27545c446 is not able to use "".

### ISSUE THREAD

**Issue by beilyly** [XTLS/Xray-core#3261]
请求大家的帮助， 在此先谢谢了。
问题描述： 使用VLESS-TCP-XTLS-Vision，  uuid检查了都正常， 也重新生成了，并且都同步，目前还是出现了问题。 app/proxyman/inbound: connection ends > proxy/vless/inbound: 8c5fb6b5-2e37-5ddd-a27f-18b27545c446 is not able to use "". Note that the pure TLS proxy has certain TLS in TLS characters.

版本： core: Xray 1.8.10 
clashx版本：1.118.1.1

配置代码：
```
{
  "log": {
    "loglevel": "info",
    "access":"/etc/xray/access.log",
   "error":"/etc/xray/error.log"

  },
  "routing": {
       "domainStrategy": "IPIfNonMatch",
       "rules": [
           {
               "type": "field",
               "ip": [
                   "geoip:cn"
               ],
               "outboundTag": "block"
           }
       ]
   },
   "inbounds": [
       {
           "listen": "0.0.0.0", // "0.0.0.0" Indicates listening to both IPv4 and IPv6
           "port": 443, // The port on which the server listens
           "protocol": "vless",
           "settings": {
               "clients": [
                   {
                       "id": "8c5fb6b5-2e37-5ddd-a27f-18b27545c446", // User ID, perform xray uuid generation, or a string of 1-30 bytes
                       "flow": "xtls-rprx-vision"
                   }
               ],
               "decryption": "none",
               "fallbacks": [
                   {
                       "dest": "8001",
                       "xver": 1
                   },
                   {
                       "alpn": "h2",
                       "dest": "8002",
                       "xver": 1
                   }
               ]
           },
           "streamSettings": {
               "network": "tcp",
               "security": "tls",
               "tlsSettings": {
                   "rejectUnknownSni": true,
                   "minVersion": "1.2",
                   "certificates": [
                       {
                           "ocspStapling": 3600,
                           "certificateFile": "/etc/xray/xxx.vip.crt", // For the certificate file, it is recommended to use fullchain (full SSL certificate chain). If there is only a website certificate, v2rayN can be used but v2rayNG cannot be used. Usually, the extension is not distinguished
                           "keyFile": "/etc/xray/xxx.vip.key" // private key file
                       }
                   ]
               }
           },
           "sniffing": {
               "enabled": true,
               "destOverride": [
                   "http",
                   "tls"
               ]
           }
       }
   ],
   "outbounds": [
       {
           "protocol": "freedom",
           "tag": "direct"
       },
       {
           "protocol": "blackhole",
           "tag": "block"
       }
   ],
   "policy": {
       "levels": {
           "0": {
               "handshake": 2, // The handshake time limit when the connection is established, in seconds, the default value is 4, it is recommended to be different from the default value
               "connIdle": 120 // Connection idle time limit in seconds, the default value is 300, it is recommended to be different from the default value
           }
       }
   }
}
```
`

clash 配置代码：
`  - {"name":"xx-node3-xray","type":"vless","server":"xxx.xxx.vip","port":443, "id":"8c5fb6b5-2e37-5ddd-a27f-18b27545c446", "uuid":"8c5fb6b5-2e37-5ddd-a27f-18b27545c446","tls":true,"servername":"xxx.xxx.vip","flow":"xtls-rprx-vision","network":"tcp","client-fingerprint":"chrome"}
  `
  
  错误日志：
2024/04/13 13:09:23 [Info] [2647091410] proxy/vless/inbound: received request for tcp:www.google.com:443
2024/04/13 13:09:23 [Warning] [2647091410] app/proxyman/inbound: connection ends > proxy/vless/inbound: 8c5fb6b5-2e37-5ddd-a27f-18b27545c446 is not able to use "". Note that the pure TLS proxy has certain TLS in TLS characters.
2024/04/13 13:09:25 [Info] [3796683863] proxy/vless/inbound: firstLen = 37
2024/04/13 13:09:25 [Info] [3796683863] proxy/vless/inbound: received request for tcp:www.google.com:443
2024/04/13 13:09:25 [Warning] [3796683863] app/proxyman/inbound: connection ends > proxy/vless/inbound: 8c5fb6b5-2e37-5ddd-a27f-18b27545c446 is not able to use "". Note that the pure TLS proxy has certain TLS in TLS characters.
2024/04/13 13:09:26 [Info] [131861204] proxy/vless/inbound: firstLen = 37
2024/04/13 13:09:26 [Info] [131861204] proxy/vless/inbound: received request for tcp:www.google.com:443
2024/04/13 13:09:26 [Warning] [131861204] app/proxyman/inbound: connection ends > proxy/vless/inbound: 8c5fb6b5-2e37-5ddd-a27f-18b27545c446 is not able to use "". Note that the pure TLS proxy has certain TLS in TLS characters.

**Comment by Fangliding** [comment]
xray当客户端是正常的么 如果正常请向clash反馈问题

**Comment by arror** [comment]
ClashX 的 VLESS 出站支持 flow：xtls-rprx-vision？

**Comment by beilyly** [comment]
> ClashX 的 VLESS 出站支持 flow：xtls-rprx-vision？

谢谢，我按照这个方向去查
