### ISSUE TITLE
Need help about UUID

### ISSUE THREAD

**Issue by TonDevv** [XTLS/Xray-core#3268]
I am going to change the 8-4-4-4-12 UUID algorithm a little, for example 4-4-8-4-12 or...
I want this change to be private and it does not need to be published publicly.
If there is a programmer who can help me in this way, please send me an email or contact info.
Fees will be paid.

**Comment by Fangliding** [comment]
ad

**Comment by TonDevv** [comment]
could you ? i can pay money for this project
