### ISSUE TITLE
路由里面的sourceport的使用问题

### ISSUE THREAD

**Issue by cnkmmk** [XTLS/Xray-core#327]
在文档中看到路由里面有 ”sourceport"的设置，个人理解为数据进入的端口，按下面的这样配置后，数据流不管是从8800，还是8801进入，全部都只会从默认的第一个出口出去，而不会分成走8800和8801两个不同出口。

请各位帮忙看一下，这个用法是有什么问题？

`    "routing": {
        "domainStrategy": "AsIs",
        "rules": [
            {
                "type": "field",
                “sourceport": 8800,
                "outboundTag": "8800"
            },
            {
                "type": "field",
                “sourceport": 8801,
                "outboundTag": "8801"
            }
        ]
    },
    "inbounds": [
        {
            "tag": "socks-in",
            "protocol": "socks",
            "port": 8000,
            "settings": {"udp": true}
        },
        {
            "protocol": "http",
            "port": "8800,8801"
        }

**Comment by JimhHan** [comment]
> sourcePort：number | string
> 来源端口

**Comment by JimhHan** [comment]
请仔细阅读文档，尽量减少主观臆断。
