### ISSUE TITLE
Low wireguard speed and Kernel mode error

### ISSUE THREAD

**Issue by eugenesmsk** [XTLS/Xray-core#3270]
Faced with the problem of low CPU speed (when configuring inbound).

Original speed: 250 MB/s
Xray Wireguard Speed: 40 Mb/s
Xray Shadowsocks Speed: 240 Mb/s

If you deploy a separate WG (wg-easy, for example), then the speed is about 240 MB/s.

I tried in Kernel mode (to turn on in the panel), but when turned on, there was an error in the logs:

![image](https://github.com/XTLS/Xray-core/assets/41268173/cbd52b6d-64d4-4650-a496-d4c367fdc99f)

I tried changing ports and MTU - with no results. The maximum CPU load is 50% during the speed measurement. Has anyone encountered such a problem?

**Comment by Fangliding** [comment]
Open issues to the panel.
