### ISSUE TITLE
New idea : add multi ip address server for cdn + example

### ISSUE THREAD

**Issue by worldamazingplaces** [XTLS/Xray-core#3271]
hello 
in iran we have new problem with tls fragment   

after for example 20 minute use of tls fragment . packets will be drop by gfw and will reconnect after 1minute

 i have an idea that we can add multi ip for outbounds server on cdn mode

for example

{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "none"
  },
  "inbounds": [
    {
      "tag": "socks",
      "port": 10808,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ],
        "routeOnly": false
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "allowTransparent": false
      }
    },
    {
      "tag": "http",
      "port": 10809,
      "listen": "127.0.0.1",
      "protocol": "http",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ],
        "routeOnly": false
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "allowTransparent": false
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address1": "cdn ip 1",
            "address2": "cdn ip 2",
            "address3": "cdn ip 3",
            "address4": "cdn ip 4",
            "address5": "cdn ip 5",
            "port": 443,
            "users": [
              {
                "id": "a8a3449d-69e0-4a92-9034-daff5101013d",
                "alterId": 0,
                "email": "t@t.tt",
                "security": "auto",
                "encryption": "none",
                "flow": ""
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": true,
          "serverName": "test.com",
          "alpn": [
            "h2",
            "http/1.1"
          ],
          "fingerprint": "chrome",
          "show": false
        },
        "wsSettings": {
          "path": "/?ed=2048",
          "headers": {
            "Host": "test.com"
          }
        },
        "sockopt": {
          "dialerProxy": "fragment",
          "tcpKeepAliveIdle": 100,
          "mark": 255,
          "tcpNoDelay": true
        }
      },
      "mux": {
        "enabled": false,
        "concurrency": 2,
        "xudpConcurrency": 2,
        "xudpProxyUDP443": "reject"
      }
    },
    {
      "tag": "fragment",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "AsIs",
        "fragment": {
          "packets": "tlshello",
          "length": "10-20",
          "interval": "10-20"
        }
      },
      "streamSettings": {
        "sockopt": {
          "tcpNoDelay": true,
          "tcpKeepAliveIdle": 100
        }
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    }
  ],
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "enabled": true
      },
      {
        "id": "5627785659655799759",
        "type": "field",
        "port": "0-65535",
        "outboundTag": "proxy",
        "enabled": true
      }
    ]
  }
}

and we can send tls fragment or other packets random between this cdn ips  it will be more difficult for gfw to detect random split packets with too many ips

**Comment by chise0713** [comment]
https://xtls.github.io/config/routing.html#balancerobject
You should use this.
