### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by OrLojqrG** [XTLS/Xray-core#3272]
In the go.mod, there are two dependencies `github.com/sagernet/sing` and `github.com/sagernet/sing-shadowsocks` that are under GPL-v3 or later, since the remaining code and these two dependencies in the project are static links, so the entire project should use GPL-V3 or Later(actually the combination of MPL-2.0 and GPL-v3 or later).

PS: According to the GNU official[https://www.gnu.org/licenses/gpl-faq.en.html#GPLStaticVsDynamic](url), no matter how the GPL code is being used (statically or dynamically linked), the terms and conditions of the GNU General Public License cover the whole combination.

There is an exception [https://www.gnu.org/licenses/gpl-faq.en.html#LinkingOverControlledInterface](url) that if the copyright holders of the project under GPL can authorize the linking exception with the condition of not modify the GPL project's code. However, it seems that the auther(s) of the `github.com/sagernet/sing` and `github.com/sagernet/sing-shadowsocks` doesn't claimed that. Maybe negotiation  with the copyright holder(s) of the `github.com/sagernet/sing` and `github.com/sagernet/sing-shadowsocks` is needed.

Of course, I'm not the layer and my opinion might not be so accurate.

**Comment by Fangliding** [comment]
Those libraries were linked by their author, and he is also a member of Project XTLS. So, I think it's ok

**Comment by RPRX** [comment]
~~经典 License issue~~

我的看法是：
1. SS2022 由于刚出生就赶上了 GFW 对全随机数流量的全面封锁，未能普及，连中转机场都是老 SS AEAD，~~毕竟在某些人眼中自建主流、直连机场主流、国外主流都不算主流协议，就国内中转机场万年 SS AEAD 算主流，至于中转成了什么，也不算主流~~
2. 本能由 Xray 内建实现的 SS2022 却依附于外部依赖，在可维护性上并不妥，并且一直有一些 bug，~~现在更是不给用了~~
3. 所以有人 PR 换成 v2fly 的内建实现会合并，即使只有出站，~~毕竟说白了这协议动不动都没人用~~，这整件事就很无聊、浪费时间
4. 当初有人想更多 sing 的依赖进入 Xray，三个 mux、TUN 什么的，~~这情况就问你爽不爽~~，然而现在有 XMUX，TUN 也快了

**Comment by RPRX** [comment]
~~于是有个 confused 被撤回了~~

顺便 @xqzr 有时间测试下吗 https://github.com/XTLS/Xray-core/discussions/4113#discussioncomment-11805220

**Comment by RPRX** [comment]
~~这下两个 confused 都被撤回了~~

To Nikita Korotaev：REALITY+XTLS 确实和 SS 一样不需要证书，且更安全、高效，只是提起简单人们首先会想到 SS，思想钢印

**Comment by RPRX** [comment]
老的 SS AEAD 是有必要保留的，因为中国的中转机场都拿它当“入口”，但 SS2022 没什么必要，不如推更好的 VLESS encryption

**Comment by stayshowsuch** [comment]
作为一个用户，我在这里评论一下
您回复一下1，我立马删除该评论

目前有很多中转的，他们入口用的是ss 2022 
并且众多软件也在近期开始兼容
如 https://t.me/egern_app/60247

在近期由于审查力度加强，倒是促进了ss 2022+v6 的解决方案
造成了近期的发展

我认为删除是个不妥的办法
应该解决问题，而不是逃避问题

我认为应该去获得许可

以上都是浅显理解，如有冒犯，望理解
麻烦了，尊敬的开发者们

**Comment by RPRX** [comment]
确实挺浅显的：
1. 全随机数就算换成了 v6 也是全随机数，一时取巧而已，即使 IP 封不完也能实时阻断
2. Xray 又不是 Meta，我本来就不喜欢非必要地引入外部库去实现协议，更不会要求人家 GPL 改成 MPL，这也不可能实现
3. **并且我对推动 VLESS 以外的协议的支持没有什么兴趣**，有人 PR 才可能会收
4. 所以入口用 SS2022 的问题，可以等 VLESS encryption 与 Xray 新客户端普及后用 VLESS，**至于其它客户端，我不关心**

**Comment by RPRX** [comment]
确实挺浅显的：
1. 全随机数就算换成了 v6 也是全随机数，一时取巧而已，即使 IP 封不完也能实时阻断
2. Xray 又不是 Meta，我本来就不喜欢非必要地引入外部库去实现协议，更不会要求人家 GPL 改成 MPL，这也不可能实现
3. **并且我对推动 VLESS 以外的协议的支持没有什么兴趣**，有人 PR 才可能会收
4. 所以入口用 SS2022 的问题，可以等 VLESS encryption 与 Xray 新客户端普及后用 VLESS，**至于非 Xray 客户端，我不关心**

**Comment by xqzr** [comment]
> ~于是有个 confused 被撤回了~
> 
> 顺便 @xqzr 有时间测试下吗 [#4113 (reply in thread)](https://github.com/XTLS/Xray-core/discussions/4113#discussioncomment-11805220)

有点意思，会安排

**Comment by RPRX** [comment]
@xqzr 这个不是很快就能试出来吗，我是想看 stream-up 上行是只需要个 SSE Header 响应还是要再加上不定期发数据保活

**Comment by RPRX** [comment]
@xqzr 这个不是很快就能试出来吗，我是想看 stream-up 上行是只需要个 SSE Header 响应还是要再加上服务端不定期发数据保活

**Comment by xqzr** [comment]
我从这里：https://github.com/XTLS/Xray-core/actions/runs/12722788908 下载了，可执行文件
它相比 `v24.12.31` ，状态码 000 在 `GET` 之后才出现，而不是同时出现。也有同时出现🤔
最新 actions
```nginx
::ffff:223.0.0.0 - - [11/Jan/2025:21:10:44 +0800] "GET https://s3.*.net:443/*/44ab61f6-4a2e-4ab7-a86b-f8c7990936c5?x_version=25.1.1 HTTP/3.0 TLSv1.3 TLS_AES_128_GCM_SHA256 s3.*.net" 200 758 "-" "quic-go HTTP/3"
::ffff:223.0.0.0 - - [11/Jan/2025:21:11:08 +0800] "GET https://s3.*.net:443/*/d486e84f-b3ea-49c5-a1de-6c25b7741e62?x_version=25.1.1 HTTP/3.0 TLSv1.3 TLS_AES_128_GCM_SHA256 s3.*.net" 200 766 "-" "quic-go HTTP/3"
::ffff:223.0.0.0 - - [11/Jan/2025:21:12:23 +0800] "GET https://s3.*.net:443/*/dc5bbdb0-6f24-4471-a35a-e9b10a1d6d5c?x_version=25.1.1 HTTP/3.0 TLSv1.3 TLS_AES_128_GCM_SHA256 s3.*.net" 200 793 "-" "quic-go HTTP/3"
::ffff:223.0.0.0 - - [11/Jan/2025:21:12:23 +0800] "POST https://s3.*.net:443/*/dc5bbdb0-6f24-4471-a35a-e9b10a1d6d5c?x_version=25.1.1 HTTP/3.0 TLSv1.3 TLS_AES_128_GCM_SHA256 s3.*.net" 000 0 "-" "quic-go HTTP/3"
::ffff:223.0.0.0 - - [11/Jan/2025:21:12:23 +0800] "POST https://s3.*.net:443/*/44ab61f6-4a2e-4ab7-a86b-f8c7990936c5?x_version=25.1.1 HTTP/3.0 TLSv1.3 TLS_AES_128_GCM_SHA256 s3.*.net" 000 0 "-" "quic-go HTTP/3"
::ffff:223.0.0.0 - - [11/Jan/2025:21:12:23 +0800] "POST https://s3.*.net:443/*/d486e84f-b3ea-49c5-a1de-6c25b7741e62?x_version=25.1.1 HTTP/3.0 TLSv1.3 TLS_AES_128_GCM_SHA256 s3.*.net" 000 0 "-" "quic-go HTTP/3"
```
v24.12.31
```nginx
::ffff:223.0.0.0 - - [11/Jan/2025:21:06:53 +0800] "POST https://s3.*.net:443/*/ff23b403-0f36-4e86-872b-782624597c37 HTTP/3.0 TLSv1.3 TLS_AES_128_GCM_SHA256 s3.*.net" 400 0 "-" "quic-go HTTP/3"
::ffff:223.0.0.0 - - [11/Jan/2025:21:06:53 +0800] "GET https://s3.*.net:443/*/ff23b403-0f36-4e86-872b-782624597c37 HTTP/3.0 TLSv1.3 TLS_AES_128_GCM_SHA256 s3.*.net" 200 758 "-" "quic-go HTTP/3"
::ffff:223.0.0.0 - - [11/Jan/2025:21:08:08 +0800] "GET https://s3.*.net:443/*/cc0fb07b-e947-41b9-afdc-ceedc525e553 HTTP/3.0 TLSv1.3 TLS_AES_128_GCM_SHA256 s3.*.net" 200 791 "-" "quic-go HTTP/3"
::ffff:223.0.0.0 - - [11/Jan/2025:21:08:08 +0800] "POST https://s3.*.net:443/*/cc0fb07b-e947-41b9-afdc-ceedc525e553 HTTP/3.0 TLSv1.3 TLS_AES_128_GCM_SHA256 s3.*.net" 000 0 "-" "quic-go HTTP/3"
```

**Comment by loginusetor** [comment]
> ~经典 License issue~
> 
> 我的看法是：
> 
>     1. SS2022 由于刚出生就赶上了 GFW 对全随机数流量的全面封锁，未能普及，连中转机场都是老 SS AEAD，~毕竟在某些人眼中自建主流、直连机场主流、国外主流都不算主流协议，就国内中转机场万年 SS AEAD 算主流，至于中转成了什么，也不算主流~
> 
>     2. 本能由 Xray 内建实现的 SS2022 却依附于外部依赖，在可维护性上并不妥，并且一直有一些 bug，~现在更是不给用了~
> 
>     3. 所以有人 PR 换成 v2fly 的内建实现会合并，即使只有出站，~毕竟说白了这协议动不动都没人用~，这整件事就很无聊、浪费时间
> 
>     4. 当初有人想更多 sing 的依赖进入 Xray，三个 mux、TUN 什么的，~这情况就问你爽不爽~，然而现在有 XMUX，TUN 也快了

坐等大佬的tun面世之时，就是隔壁的灭亡之日。

**Comment by RPRX** [comment]
我希望任何隔壁都好好活着，~~绝对不能只剩 Xray~~，并且我在这里也不是为了和谁竞争，早就说过只是想按顺序把该做的事情做好

**Comment by RPRX** [comment]
> Hi boss, when will the next version be released?

提起这个就来气，我本来想等 Golang 发新版就发新版 Xray，结果破天荒地都 1.12 了 Go 还没发新版，导致 NFT 快停滞二十天了

**Comment by zzlinwq** [comment]
百花齐放才是春

**Comment by RPRX** [comment]
@xqzr 感觉状态码不应为 000，你是不是把服务端 xPadding 关了？

**Comment by xqzr** [comment]
> @xqzr 感觉状态码不应为 000，你是不是把服务端 xPadding 关了？

✅两端都是 `-1`

**Comment by RPRX** [comment]
@xqzr 你没事填 -1 干嘛？删掉看看。~~你一直填个 -1 当什么正经用户呢，影响了这么久的测试反馈，下个版本填负数不给启动~~

**Comment by xqzr** [comment]
> > @xqzr 感觉状态码不应为 000，你是不是把服务端 xPadding 关了？
> 
> ✅两端都是 `-1`

哦还有...我只替换了，**客户端🤡**

**Comment by RPRX** [comment]
@xqzr 那你确实🤡，就是怕你们只替换了一端，我还特意强调要替换双端

**Comment by xqzr** [comment]
> @xqzr 你没事填 -1 干嘛？删掉看看。~你一直填个 -1 当什么正经用户呢，影响了这么久的测试反馈，下个版本填负数不给启动~

我认为这些“填充”是**垃圾**

**Comment by RPRX** [comment]
@xqzr 没有这些填充的话，固定包头长度能精准识别 XHTTP

**Comment by xqzr** [comment]
> 我从这里：https://github.com/XTLS/Xray-core/actions/runs/12722788908 下载了，可执行文件

移除 `xPadding` 后
```nginx
::ffff:* - - [12/Jan/2025:22:23:14 +0800] "GET https://s3.*.net:443/*/c84a1c4b-c439-42f0-b20b-da04ff4ae202?x_version=25.1.1&x_padding=000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 HTTP/3.0 TLSv1.3 TLS_AES_128_GCM_SHA256 s3.*.net" 200 762 "-" "quic-go HTTP/3"
::ffff:* - - [12/Jan/2025:22:24:29 +0800] "POST https://s3.*.net:443/*/c84a1c4b-c439-42f0-b20b-da04ff4ae202?x_version=25.1.1&x_padding=000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 HTTP/3.0 TLSv1.3 TLS_AES_128_GCM_SHA256 s3.*.net" 200 245 "-" "quic-go HTTP/3"
```
