### ISSUE TITLE
full cpu issue

### ISSUE THREAD

**Issue by karimi12** [XTLS/Xray-core#3276]
my server cpu was fulled by some users i check my log i see these lines

x.x.x.x:0 rejected  proxy/vless/encoding: failed to read request version > websocket: close 1006 (abnormal closure): unexpected EOF

**Comment by moohr** [comment]
@karimi12

**Comment by Fangliding** [comment]
No provided configuration, no detailed information.
If you are not using xray and it still consumes a lot of CPU, maybe you have encountered DDOS attack
