### ISSUE TITLE
dokodemo-door doesn't sniff UDP (QUIC) Connection

### ISSUE THREAD

**Issue by changyp6** [XTLS/Xray-core#328]
dolodemo-door protocol can only sniff HTTP TCP and TLS TCP connection, QUIC UDP connection is NOT sniffed.
If chrome / vivaldi browser enable QUIC feature, when watching videos from www.youtube.com
all xxxxxx.googlevideo.com will be UDP connections, however, these domains cannot be sniffed, the Routing protocol won't work properly on these connections.

Especially, if XRAY is working in BLACK-LIST mode, default connections will be directly connected, thus all UDP connections of xxxx.googlevideo.com is not proxied.

My question is that if it is possible to sniff UDP connection ?
If UDP connection can be sniffed, routing protocol will work, these UDP connections will go to proxy correctly.

**Comment by JimhHan** [comment]
Sniffing dose not support neither UDP connection nor quic yet.

**Comment by changyp6** [comment]
I have tested again, if xray is working at TPROXY transparent mode in PC, local UDP(QUIC) connection is directly sent to dokodemo-door, the connection won't be sniffed..
If xray is working at TPROXY transparent mode in OpenWRT router, local UDP(QUIC) connection from router is directly sent to dokodemo-door, the connection won't be sniffed, but connections from sub-network will be sniffed.

It seems that sub-network connection to the router is TCP connection.
