### ISSUE TITLE
REALITY Blocked by Zscaler Proxy

### ISSUE THREAD

**Issue by SpaceFlier100** [XTLS/Xray-core#3281]
Xray cannot connect with the following error: app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [REALITY: processed invalid connection] > common/retry: all retry attempts failed
Xray works fine on all other networks but fails specifically on this one, where the network uses a Zscaler proxy to block certain traffic. so far I've been able to get no VPN to penetrate the network (ironic since when you start xray it says penetrates everything). Is there some configuration I can add to make it bypass?
Server:
![image](https://github.com/XTLS/Xray-core/assets/108110429/8dc1e882-adb4-4432-b60a-a172bdcdabee)
Client:
![image](https://github.com/XTLS/Xray-core/assets/108110429/edbc452c-a4bd-4808-bdb6-802d0c61e7f1)

**Comment by Fangliding** [comment]
Not a core issue
By the way, we know nothing about the "Zscaler", any discussion about it is just a waste of time

**Comment by yuhan6665** [comment]
Zscaler is a corporate security proxy. Yeah I agree it is not core goal of this project to study and penetrate it.
~~although you can try a bank website as dest, I know zscaler has a whitelist for that~~
