### ISSUE TITLE
Xray not working on OpenBSD 7.5, syscalls show errno 35 Resource Temporary Unavailable

### ISSUE THREAD

**Issue by repliqa** [XTLS/Xray-core#3291]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I searched issues and did not find any similar issues.

### Version

```shell
1.8.10
```

### Description

The Xray proxy worked perfectly on OpenBSD 7.4, however updating to OpenBSD 7.5, users can send pings to the proxy server but it doesn't receive or forward packets properly. The logs on debug mode does not show anything. However, when checking the system calls, there's a continuous stream of errno 35 resource unavailable, with some 36 Operation now in progress and 65 No route to host. 

Asking the question on a OpenBSD community, A OpenBSD developer mentioned "syscall() was removed, you now need to use the libc wrappers for the relevant functions. I see this is written in Go - if it's using an old x/sys then updating may help  otherwise that may be complicated to change. "

At this moment I do not know how to fix the issue. Will the Xray proxy work on OpenBSD 7.5?

### Reproduction

Basic XTLS-Vision trojan/vmess/vless/proxy of your choice config.

### log

Xray client and server configs: https://pastebin.com/hEwyUxbb
Xray access logs: https://pastebin.com/DNRYsMEL
Xray error logs: https://pastebin.com/nJyVAAdG

**Comment by Fangliding** [comment]
Even if no connection is established, xray will at least output log to prompt that xray has been started. Are you sure you have correctly get the log

**Comment by repliqa** [comment]
Ouch, I was hugely mistaken. I had a bunch of config files and I thought the one being used by the init script had log verbosity set to debug.

I fixed that by setting it to debug. And I can connect to the server from the client, the server is also accepting the incoming connections which could be seen in the logs. However, the sites are not properly loading on the client side, instead stuck on an infinite loading screen.

And the resource not found syscalls.

However, one thing to mention is I am running xray from a chrooted environment. I copied all the dependencies, and also through the system calls figured out it needs /etc/resolv.conf and /etc/hosts files to function which I also copied, and that setup worked properly on OpenBSD 7.4.

**Comment by Fangliding** [comment]
The issues template has requested to provid client config, do not say "I am using xxxx gui client"....
And there is sitll no log

**Comment by repliqa** [comment]
I apologize for the inconvenience.

Xray client and server configs: https://pastebin.com/hEwyUxbb
Xray access logs: https://pastebin.com/DNRYsMEL
Xray error logs: https://pastebin.com/nJyVAAdG

**Comment by yuhan6665** [comment]
Please raise it with golang x/sys

**Comment by repliqa** [comment]
I'm sorry? Could you kindly rephrase that.

**Comment by yuhan6665** [comment]
Go 大佬秒回了 https://github.com/golang/go/issues/36435
Closing as known limitation

**Comment by 4a6f656c** [comment]
And as suspected: https://github.com/XTLS/Xray-core/blob/51504c624c4aa9c093cf607cfca16e9548743af0/common/buf/readv_posix.go#L30

**Comment by yuhan6665** [comment]
hmm interesting. It may work if you turn off readv (via env var xray.buf.readv) and sockopt. Thanks for your info!

**Comment by repliqa** [comment]
Will the source code be updated so Xray works on OpenBSD 7.5 or future versions? OpenBSD 7.6 will soon be out and 7.4 would being discontinued. And also, I think the issue needs to be reopened.

**Comment by yuhan6665** [comment]
@repliqa Please try turn off readv (via env var xray.buf.readv) and sockopt. If it still happens, please try to get logs as mentioned in https://github.com/XTLS/Xray-core/issues/3291#issuecomment-2082892605

**Comment by DavidOsipov** [comment]
I've fixed the issue here #5784 - workaround refused.
Proper fix should be on Go side: https://github.com/golang/go/issues/78049
