### ISSUE TITLE
Xray实现的ss的nat等级为2

### ISSUE THREAD

**Issue by tooiiby** [XTLS/Xray-core#330]
发现用Netch建立连接显示nat等级为2，以下是我的配置文件。

{
    "log": {
        "access": "/var/log/xray/access.log",
        "error": "/var/log/xray/error.log",
        "loglevel": "warning"
    },
    "inbounds": [
        {
            "listen": "0.0.0.0",
            "port": 20002,
            "tag": "xray-in",
            "protocol": "shadowsocks",
            "settings": {
                "clients": [
                    {
                        "email": "a@b.com",
                        "level": 0,
                        "method": "aes-256-gcm",
                        "password": "@@kkkk"
                    }
                ],
                "network": "tcp,udp"
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "settings": { },
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "settings": { },
            "tag": "blocked"
        }
    ],
    "dns": {
        "servers": [
            "https+local://1.1.1.1/dns-query",
                "1.1.1.1",
                "1.0.0.1",
                "8.8.8.8",
                "8.8.4.4",
                "localhost"
        ]
    },
    "routing": {
        "domainStrategy": "AsIs",
        "rules": [
            {
                "type": "field",
                "inboundTag": [
                    "xray-in"
                ],
                "outboundTag": "direct"
            }
        ]
    }
}

**Comment by tooiiby** [comment]
有时候会用iplc打游戏想不加密，在填"method": "none"以后xray无法正常运行。

**Comment by rprx** [comment]
1. 检查服务端防火墙
2. 若需 method none，请去掉 `clients` 的包裹（目前此填法只支持 SS AEAD）
