### ISSUE TITLE
override dest address & port in Xray-core

### ISSUE THREAD

**Issue by APT-ZERO** [XTLS/Xray-core#3304]
Hello
Is it possible to override dest address and port in Dokodemo-Door of Xray-core ?
like override_address and override_port in sing-box core
If it's not supported and not possible using tricks, is it planned to add it?

**Comment by Fangliding** [comment]
https://xtls.github.io/config/inbounds/dokodemo.html
```
{
  "address": "8.8.8.8",
  "port": 53,
  "network": "tcp",
  "timeout": 0,
  "followRedirect": false,
  "userLevel": 0
}
```
What do you think the ```address``` and ```port``` options here are for
