### ISSUE TITLE
1.8.11macos版本zip文件中没有执行文件

### ISSUE THREAD

**Issue by linze99** [XTLS/Xray-core#3305]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I searched issues and did not find any similar issues.

### Version

```shell
1.8.11
```

### Description

![截屏2024-04-26 14 05 59](https://github.com/XTLS/Xray-core/assets/30024479/add71b4b-2d1a-483c-813d-23ab12a57693)
zip文件解压后只有以下四个文件：
geoip.dat
geosite.dat
LICENSE
README.md 

### Reproduction

下载最新的压缩包，解压

**Comment by Fangliding** [comment]
Maybe https://github.com/XTLS/Xray-core/pull/3275

**Comment by KobeArthurScofield** [comment]
> Maybe #3275 

不用 maybe，就是……

估计 pr 的老哥也不知道自动构建会用到这个 makefile 就直接将 macOS 的输出文件名改了，然后 action 文件没跟着改，导致编译是编译了，但是收文件打包的时候没有找到对应名字的文件，直接就打半空包了……

看 action 最近产出的自动构建包 macOS 在这个更改之后全部半空包了…… 从 [#2084](https://github.com/XTLS/Xray-core/actions/runs/8719817858) 开始

~~要不要在 makefile 注明这个文件也会被自动构建使用更改时必须检查 actions~~

**Comment by Fangliding** [comment]
@KobeArthurScofield 就算修改action把它修了 感觉改名也不好 可能破坏一些软件的自动更新 要不考虑revert了 我手动补传一下？
@yuhan6665 
@RPRX

**Comment by KobeArthurScofield** [comment]
建议 revert，~~这 breaking 实在有点刺激了~~

反正原来 pr 里面提到的 ```lipo``` 做 fat binaty 得要有 Xcode 才能用，交叉编译的条件下用不着

**Comment by RPRX** [comment]
完美解决，~~用上了奇奇怪怪的经验~~：https://github.com/XTLS/Xray-core/issues/1582#issuecomment-1413259403, https://github.com/XTLS/Xray-core/commit/41b6559b7ca5b80d14b0f454868e562e91001548, https://github.com/XTLS/Xray-core/actions/runs/8847057146

**Comment by RPRX** [comment]
> 看了下现在编译会连 commit tag 也加上 ~改 action 的时候顺手在 checkout 那里加个 ref 指向主分支应该能避开 reproducible compile 的问题~

~~演示一下~~

**Comment by RPRX** [comment]
> 看了下现在编译会连 commit tag 也加上 ~改 action 的时候顺手在 checkout 那里加个 ref 指向主分支应该能避开 reproducible compile 的问题~

这样最多到 b892478，否则 Makefile 还是旧的，~~不如 hard code VERSION 为 45ab4cb~~

**Comment by KobeArthurScofield** [comment]
> ~~演示一下~~

一般情况下 checkout 那节是这样的：
``` yaml
      - name: Checkout codebase
        uses: actions/checkout@v4

```
这样默认就是指示读取这个分支当前的 commit 下的代码

加个 ref：
``` yaml
      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          ref: main # 指向 main 分支目前最新 commit 的代码，或者改成 commit tag 来指定特定的 commit

```
一般想在 action 里面编译点什么特定的东西或者改了东西不想动原来的 commit 就会这么干

> 这样最多到 https://github.com/XTLS/Xray-core/commit/b8924782a1b3fce25c05b192d27f9f6754f924dd，否则 Makefile 还是旧的，不如 hard code VERSION 为 https://github.com/XTLS/Xray-core/commit/45ab4cb5ba6ef5251aa2edcffc6f7ecc8629b345

因为 checkout 的读取有时候会略为尴尬
~~但是考虑到只懂了 makefile 似乎 release note 单独说明一下也行~~

**Comment by RPRX** [comment]
看看 https://github.com/XTLS/Xray-core/commit/cc1aac4b09010c3966be227843cce10d787f3630, https://github.com/XTLS/Xray-core/commit/0926d30209980e5b69cd4e74136428f5738d0382, https://github.com/XTLS/Xray-core/actions/runs/8850751494

**Comment by RPRX** [comment]
@KobeArthurScofield 不过咋还有 vcs.time，咋可能一样，~~有点过分了~~

**Comment by yuhan6665** [comment]
> @KobeArthurScofield 不过咋还有 vcs.time，咋可能一样，~有点过分了~
那个是 git author date 只要 commit 能对上就行

**Comment by KobeArthurScofield** [comment]
~~Xray-core 1.8.11 macOS 特典版 tag ~~

**Comment by RPRX** [comment]
> > @KobeArthurScofield 不过咋还有 vcs.time，咋可能一样，~有点过分了~
> 
> 那个是 git author date 只要 commit 能对上就行

~~这么说 vcs 应该是 version control system？~~

**Comment by RPRX** [comment]
感觉现在的 https://github.com/XTLS/Xray-core/issues/3305#issuecomment-2079636704 不如之前的 https://github.com/XTLS/Xray-core/issues/3305#issuecomment-2079157585 ，之前的更容易找到对应的 commit 去 reproduce，不过先这样吧

**Comment by RPRX** [comment]
@KobeArthurScofield ~~或者你找个方法能把 vcs.revision 和 vcs.time 这两个值改了也行~~

**Comment by KobeArthurScofield** [comment]
> @KobeArthurScofield ~或者你找个方法能把 vcs.revision 和 vcs.time 这两个值改了也行~

~~盒盖了而且好困~~

如果要完美解决的话特制一份编译指定 commit 的就行
然后因为出问题的是被改了文件名导致后续的打包问题，所以在 action 里面 build 里面 find 那一步把被改的文件名加进去匹配让 action 能捕获被改名的文件，然后多插一步把名字改回来就行
~~缺点是复杂了点~~
