### ISSUE TITLE
请问httpupgrade可以直连吗？还是必须得过一下nginx或cdn？

### ISSUE THREAD

**Issue by PHCSJC** [XTLS/Xray-core#3309]
版本是最新的1.8.11，我这边的测试结果：
直连不通，过cdn可以通，好奇怪，是这个协议中间必须过一手nginx或cdn吗？

**Comment by Fangliding** [comment]
肯定是不需要的啊

**Comment by PHCSJC** [comment]
@Fangliding 能给一个example吗？谢谢

**Comment by PHCSJC** [comment]
只写出过cdn的，直连写不出来

**Comment by Fangliding** [comment]
那去用ws吧 ws不通就是vps本身网不通(

**Comment by PHCSJC** [comment]
ws可以直通,httpupgrade直通就是不行，同端口，奇怪

**Comment by PHCSJC** [comment]
client带tls+cdn+server不带tls，可以通
client带tls+server不带tls，完全同上的配置，不通
client带tls+server带tls，不通
