### ISSUE TITLE
能否用于回国？

### ISSUE THREAD

**Issue by dragon100a** [XTLS/Xray-core#331]
我使用1.3.1版本在搬瓦工的服务器上，路由设置绕过局域网和大陆，科学上网是顺利的。
我的朋友托人买了腾讯云北京1m带宽的实例，人在国外，希望用国内的应用。

当前项目能否达到目的吗？若能，路由的思路大致是怎样的？

**Comment by ShinyGwyn** [comment]
默认直连. 代理大陆.

**Comment by dragon100a** [comment]
> 默认直连. 代理大陆.

感谢，我以为是全部代理。再有就是一开始担心这项目能不能在国内机器上装。
