### ISSUE TITLE
TLS handshake error

### ISSUE THREAD

**Issue by hassanAzhar143** [XTLS/Xray-core#3315]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I searched issues and did not find any similar issues.

### Version

```shell
1.8.8
```

### Description

i am making ios client based on Vmess TCP - TLS
http: TLS handshake error from 198.199.95.70:43252: tls: client offered only unsupported versions: []

### Reproduction

i run the xray and got this error on server console.

### log

```shell
2024/04/29 06:27:26 http: TLS handshake error from 198.199.95.70:43252: tls: client offered only unsupported versions: []
```

**Comment by Fangliding** [comment]
config

**Comment by hassanAzhar143** [comment]
{
    "policy":{
        "levels": {
            "8": {
              "handshake": 30,
              "connIdle": 4,
              "uplinkOnly": 1,
              "downlinkOnly": 1,
              "statsUserUplink": false,
              "statsUserDownlink": false,
              "bufferSize": 0
            }
        },
        "system": {
            "statsInboundUplink": false,
            "statsInboundDownlink": false
        }
    },
    "outbounds":[
        {
            "mux":{
                "enabled": true,
                "concurrency": 1024
            },
            "protocol":"vmess",
            "settings":{
                "vnext":[
                    {
                        "address":"172.233.88.55",
                        "users":[
                            {
                                "id":"d06f5dc4-214a-4ee1-a4e9-360e2711231a",
                                "alterId":16,
                                "level":0,
                                "security":"aes-128-gcm"
                            }
                        ],
                        "port":5002
                    }
                ]
            }
        }
    ]
}

**Comment by Fangliding** [comment]
Issue template required client and server config 
Did you read it?

**Comment by hassanAzhar143** [comment]
this is server configuration:
"settings":{
        "clients":[
                    {
            "id":"ID",
            "level":0,
            "alterId":16
          }
        ],
        "disableInsecureEncryption":true,
        "default":{
          "level":0,
          "alterId":16
        }
      },

"streamSettings":{
        "network":"tcp",
        "security":"tls",
        "tcpSettings":{
          "header":{
            "type":"none"
          }
        },
        "tlsSettings":{
          "serverName":"SERVER",
          "allowInsecure":false,
          "disableSystemRoot":true,
          "alpn":[
            "http/1.1"
          ],
          "certificates":[
            {
              "usage":"encipherment",
              "certificateFile":"/etc/v2ray/fullchain.pem",
              "keyFile":"/etc/v2ray/privkey.pem"
            }

**Comment by Fangliding** [comment]
You have set tls on the server, but not on the client.
