### ISSUE TITLE
Enhance log output

### ISSUE THREAD

**Issue by 1eo1** [XTLS/Xray-core#3316]
Hi,
To prevent spamming log and increse of log size in user management panels, I would like to request an option to hide an api request in log output or move to higher logging level. 
Thanks in advance

**Comment by Fangliding** [comment]
The log level of the API has already been debug.

**Comment by 1eo1** [comment]
> The log level of the API has already been debug.

no, it is not.  it is on warning level

> But in access log, all api requests generated by x-ui panel are printed

yes, the panel make requests every 10 seconds.  i think it would be better to move it to higher logging level

**Comment by yuhan6665** [comment]
There is no log level in access.log. No plan in changing. Use what people has offered
