### ISSUE TITLE
Cannot build version 1.8.11 from source code

### ISSUE THREAD

**Issue by changyp6** [XTLS/Xray-core#3319]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I searched issues and did not find any similar issues.

### Version

```shell
1.8.11
```

### Description

When building from source code, go reports error:
`gvisor.dev/gvisor v0.0.0-20231202080848-1f7806d17489 unknown revision 1f7806d17489`

### Reproduction

download 1.8.11 tar.gz
run `make`

**Comment by Fangliding** [comment]
Unable to reproduct
Our CI build use this makefile and it works well
Check your local go environment

**Comment by changyp6** [comment]
I've already found out the root cause.
Fedora's golang doesn't set GOSUMDB and GOPROXY.
After adding
`env GO111MODULES=on GOPROXY="https://proxy.golang.org,direct" GOSUMDB="sum.golang.org"`
before the build command
everything works.

This revision `gvisor.dev/gvisor v0.0.0-20231202080848-1f7806d17489` doesn't exist in gvisor.dev/gvisor's git anymore
It can only be retrieved from proxy.golang.org, which is an archive version

**Comment by changyp6** [comment]
> I've already found out the root cause. Fedora's golang doesn't set GOSUMDB and GOPROXY. After adding `env GO111MODULES=on GOPROXY="https://proxy.golang.org,direct" GOSUMDB="sum.golang.org"` before the build command everything works.
> 
> This revision `gvisor.dev/gvisor v0.0.0-20231202080848-1f7806d17489` doesn't exist in gvisor.dev/gvisor's git anymore It can only be retrieved from proxy.golang.org, which is an archive version

If anyone encounters the same issue, hope this post can give others some clue.
