### ISSUE TITLE
 [bug]升级1.3.1版本后，freedom的redirect功能依然失效，不能实现dns重定向

### ISSUE THREAD

**Issue by lw4free** [XTLS/Xray-core#332]
升级1.31后，freedom的redirect功能依然失效。与1.3.0对比，本地127.0.0.1:53服务收到dns请求，但dig请求time out。
配置及问题如之前问题反馈。[269](https://github.com/XTLS/Xray-core/issues/269#issue-808998638)

**Comment by rprx** [comment]
目测需要给 Freedom 返回的 UDP 加个来源改写，虽然这样不太符合 UDP 的本意

**Comment by rprx** [comment]
感谢反馈，请测试 https://github.com/XTLS/Xray-core/commit/055fb51ed9c1b44bcc790613b71720e85aeaf83d https://github.com/XTLS/Xray-core/actions/runs/624348878

**Comment by rprx** [comment]
不好意思，好像需要将来源改写为原目标而不是 UDPOverride

**Comment by rprx** [comment]
应该没有问题了，麻烦测试 https://github.com/XTLS/Xray-core/commit/e1a5392bebb1712d691bf5e12e57df297e6d4068 https://github.com/XTLS/Xray-core/actions/runs/626756286
