### ISSUE TITLE
Setting net.ipv4.conf.all.src_valid_mark=1 and enabling xray-core will cause a crash

### ISSUE THREAD

**Issue by xcf13363175** [XTLS/Xray-core#3324]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我搜索了issues，没有发现已提出的类似问题。

### 版本

```shell
v1.8.11
```

### 描述

The router uses xray and wireguard for intranet penetration. Once net.ipv4.conf.all.src_valid_mark=1 is set, the router crashes and must be unplugged and restarted.

### 重现方式

Setting net.ipv4.conf.all.src_valid_mark=1 and enabling xray-core will cause a crash

**Comment by yuhan6665** [comment]
Router crash is not an issue for this project. Re-open if you can find a crash in xray
