### ISSUE TITLE
Feature request: alive-only random/round-robin strategy

### ISSUE THREAD

**Issue by miladrahimi** [XTLS/Xray-core#3329]
Our outbound connections sometimes get blocked unexpectedly. To keep this from affecting users, load balancers (random/round-robin) should  automatically skip any blocked connections.

Seems there is a similar feature in v2ray:
https://github.com/v2fly/v2ray-core/pull/2850

**Comment by Fangliding** [comment]
There is already such feature, but it doesn't seem to be written in the document (damn)

**Comment by chise0713** [comment]
I think the label should be documentation instead dependencies.

**Comment by yuhan6665** [comment]
I need to move the code and add to round robin..

**Comment by yuhan6665** [comment]
应该可以了 https://github.com/XTLS/Xray-core/commit/84eeb56ae45f48b9ab5166abefb2fda40986b8a8
@miladrahimi please help test. On xray side, I didn't add extra config. You just need to add `fallbackTag` as well as `burstObservatory`, the feature should be on.
