### ISSUE TITLE
转发到tor,关闭sniffer后dns无法解析，请问怎么解决，配置是默认的reality

### ISSUE THREAD

**Issue by dcliubing** [XTLS/Xray-core#3347]

**Comment by kingwilliam** [comment]
我已很久没用 tor, 但试试看能否解答您问题
1. 你昰用 tor browser吗?
2. xtls 只能是 http/sock proxy, 远端还是要有 tor 进入点.

**Comment by dcliubing** [comment]
> 我已很久没用 tor, 但试试看能否解答您问题
> 
> 1. 你昰用 tor browser吗?
> 2. xtls 只能是 http/sock proxy, 远端还是要有 tor 进入点.
1.不是用 tor browser，chrome 上有proxyswitch插件 可以正常访问网页及tor 网页，不用proxyswitch插件只填socks代理就提示找不到dns
2.远端出站转发到tor

**Comment by Fangliding** [comment]
描述不清  未遵照模板
