### ISSUE TITLE
tls ech client and server configuration sample json file

### ISSUE THREAD

**Issue by worldamazingplaces** [XTLS/Xray-core#3350]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I searched issues and did not find any similar issues.

### Version

```shell
1.8.11
```

### Description

hello i want to test tls ech xray but there is no sample for it
how we can put ech key and ech config in client json file  or need some config on server side??
please send us document for config tls ech in xray  client json
or how does it work? should we use our own domain for generate ech key and config file? or can use google.com or other domains?

please give me sample file for client json and server json  

thanks

### Reproduction

hello i want to test tls ech xray but there is no sample for it
how we can put ech key and ech config in client json file  or need some config on server side??
please send us document for config tls ech in xray  client json
or how does it work? should we use our own domain for generate ech key and config file? or can use google.com or other domains?

please give me sample file for client json and server json  

thanks

**Comment by Fangliding** [comment]
Not supported yet
https://github.com/XTLS/Xray-core/pull/3253
