### ISSUE TITLE
关于文档中对sniffing和Tor的描述问题

### ISSUE THREAD

**Issue by CodingMoeButa** [XTLS/Xray-core#3357]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我搜索了issues，没有发现已提出的类似问题。

### 描述

文档中说“当使用 Tor 浏览器……需要关闭 "sniffing" 才能正常使用。”，测试发现仅关闭“destOverride”或者开启RouteOnly即可。

### 重现方式

```json
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "socks",
      "port": 10808,
      "listen": "0.0.0.0",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "routeOnly": false
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "allowTransparent": false
      }
    },
    {
      "tag": "http",
      "port": 10809,
      "listen": "0.0.0.0",
      "protocol": "http",
      "sniffing": {
        "enabled": true,
        "routeOnly": false
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "allowTransparent": false
      }
    },
    {
      "tag": "api",
      "port": 10813,
      "listen": "127.0.0.1",
      "protocol": "dokodemo-door",
      "settings": {
        "udp": false,
        "address": "127.0.0.1",
        "allowTransparent": false
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "shadowsocks",
      "settings": {
        "servers": [
          {
            "address": "example.com",
            "method": "chacha20-ietf-poly1305",
            "ota": false,
            "password": "anonymous",
            "port": 10800,
            "level": 1
          }
        ]
      },
      "streamSettings": {
        "network": "tcp"
      },
      "mux": {
        "enabled": false,
        "concurrency": -1
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    }
  ],
  "stats": {},
  "api": {
    "tag": "api",
    "services": [
      "StatsService"
    ]
  },
  "policy": {
    "system": {
      "statsOutboundUplink": true,
      "statsOutboundDownlink": true
    }
  },
  "dns": {
    "hosts": {
      "dns.google": "8.8.8.8",
      "proxy.example.com": "127.0.0.1"
    },
    "servers": [
      {
        "address": "223.5.5.5",
        "domains": [
          "geosite:cn",
          "geosite:geolocation-cn"
        ],
        "expectIPs": [
          "geoip:cn"
        ]
      },
      "1.1.1.1",
      "8.8.8.8",
      "https://dns.google/dns-query"
    ]
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "domainMatcher": "mph",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api"
      },
      {
        "type": "field",
        "port": "0-65535",
        "outboundTag": "proxy"
      }
    ]
  }
}
```

**Comment by chise0713** [comment]
问题是不打开相应的 destOverride，这个协议也不会被嗅探。

**Comment by CodingMoeButa** [comment]
> 问题是不打开相应的 destOverride，这个协议也不会被嗅探。

你没理解我说的问题。我没说Sniffing会嗅探Tor。这个问题的原因是Tor的TLS的SNI是假的，开启destOverride的情况下Xray会重写目标地址，导致Tor无法使用，关闭“destOverride”或者开启RouteOnly就行了。

**Comment by chise0713** [comment]
> > 问题是不打开相应的 destOverride，这个协议也不会被嗅探。
> 
> 你没理解我说的问题。我没说Sniffing会嗅探Tor。这个问题的原因是Tor的TLS的SNI是假的，开启destOverride的情况下Xray会重写目标地址，导致Tor无法使用，关闭“destOverride”或者开启RouteOnly就行了。

我的意思是 sniffing 的 destOverride 选项决定了会被嗅探到的协议，如 http / tls / quic，如果不填相当于没打开 sniffing。

**Comment by CodingMoeButa** [comment]
> > > 问题是不打开相应的 destOverride，这个协议也不会被嗅探。
> > 
> > 
> > 你没理解我说的问题。我没说Sniffing会嗅探Tor。这个问题的原因是Tor的TLS的SNI是假的，开启destOverride的情况下Xray会重写目标地址，导致Tor无法使用，关闭“destOverride”或者开启RouteOnly就行了。
> 
> 我的意思是 sniffing 的 destOverride 选项决定了会被嗅探到的协议，如 http / tls / quic，如果不填相当于没打开 sniffing。

不是这样的吧。Sniffing是嗅探，destOverride是重写，关闭destOverride不会导致Sniffing的关闭，Xray文档中也没提到关闭destOverride会关闭Sniffing。而且v2ray-core和sing-box的实现也是这样的。

我不清楚Xray的源代码，如果关闭destOverride会导致Sniffing的关闭的话，建议维护一下文档。

**Comment by chise0713** [comment]
> > > > 问题是不打开相应的 destOverride，这个协议也不会被嗅探。
> > > 
> > > 
> > > 你没理解我说的问题。我没说Sniffing会嗅探Tor。这个问题的原因是Tor的TLS的SNI是假的，开启destOverride的情况下Xray会重写目标地址，导致Tor无法使用，关闭“destOverride”或者开启RouteOnly就行了。
> > 
> > 
> > 我的意思是 sniffing 的 destOverride 选项决定了会被嗅探到的协议，如 http / tls / quic，如果不填相当于没打开 sniffing。
> 
> 不是这样的吧。Sniffing是嗅探，destOverride是重写，关闭destOverride不会导致Sniffing的关闭，Xray文档中也没提到关闭destOverride会关闭Sniffing。而且v2ray-core和sing-box的文档也是这样的。
> 
> 我不清楚Xray的源代码，如果关闭destOverride会导致Sniffing的关闭的话，建议维护一下文档。

你可以自行测试，文档也写的很清楚
>Xray只会嗅探 destOverride 中协议的域名用作路由，如果只想进行嗅探用作路由而不想重置目标地址，请在这里添加对应的协议并启用 routeOnly 。

**Comment by CodingMoeButa** [comment]
> > > > > 问题是不打开相应的 destOverride，这个协议也不会被嗅探。
> > > > 
> > > > 
> > > > 你没理解我说的问题。我没说Sniffing会嗅探Tor。这个问题的原因是Tor的TLS的SNI是假的，开启destOverride的情况下Xray会重写目标地址，导致Tor无法使用，关闭“destOverride”或者开启RouteOnly就行了。
> > > 
> > > 
> > > 我的意思是 sniffing 的 destOverride 选项决定了会被嗅探到的协议，如 http / tls / quic，如果不填相当于没打开 sniffing。
> > 
> > 
> > 不是这样的吧。Sniffing是嗅探，destOverride是重写，关闭destOverride不会导致Sniffing的关闭，Xray文档中也没提到关闭destOverride会关闭Sniffing。而且v2ray-core和sing-box的文档也是这样的。
> > 我不清楚Xray的源代码，如果关闭destOverride会导致Sniffing的关闭的话，建议维护一下文档。
> 
> 你可以自行测试，文档也写的很清楚
> 
> > Xray只会嗅探 destOverride 中协议的域名用作路由，如果只想进行嗅探用作路由而不想重置目标地址，请在这里添加对应的协议并启用 routeOnly 。

那仅开启Sniffing能嗅探Bittorrent吗？destOverrode里可没有Bittorrent。

**Comment by chise0713** [comment]
@CodingMoeButa 

> 你可以自行测试

并且，Bittorrnet 也不存在 destOverride

**Comment by Fangliding** [comment]
不是 这有啥好吵的
开sniffing的情况下 core默认不会拿嗅探到的域名去路由 只有开了 destoverride才会 但是开了之后会把本来发往特定IP的连接重置成域名 所以才有了后来的routeonly选项
至于torrent 这是对应路由里的协议字段 不是domain字段 和destoverride这一块没有关系 不过一直没人用嗅探域名以外的功能 所以有的时候才会说destoverride置空(约等于)关闭sniffing

**Comment by chise0713** [comment]
> > @CodingMoeButa
> > > 你可以自行测试
> > 
> > 
> > 并且，Bittorrnet 也不存在 destOverride
> 
> 你刚才说的 #[#3357 (comment)](https://github.com/XTLS/Xray-core/issues/3357#issuecomment-2108149731) 是“如果不填（destOverride）相当于没打开 sniffing”，这不文档也写了开启Sniffing能嗅探Bittorrent，所以关闭destOverride不会导致Sniffing的关闭，destOverride 选项也不会决定被嗅探到的协议有哪些。我不得不纠正你先前的说法。

朋友，别啃文咬字，我的确表达有误，我应该说："...如果不填相当于没打开对应协议 sniffing。"

并且，我们讨论的重点是 "destOverride是否会影响 「特定协议 sniffer」 的启用"，而不是 https://github.com/XTLS/Xray-core/issues/3357#issuecomment-2108176975 这里的 Bittorrent。

但是，我可以回答 https://github.com/XTLS/Xray-core/issues/3357#issuecomment-2108176975 中你提出的问题：仅开启 sniffing 且不填入 destOverride 并不会影响 Bittorrent 的嗅探，destOverride 的作用域只在路由和重置目标地址上。

晚安

**Comment by CodingMoeButa** [comment]
我只是想提议文档关于Tor的措辞需要修改，没想讨论别的。

我不知道你们之间有“destoverride置空(约等于)关闭sniffing”的说法。毕竟我是项目外人员，我想了解这个软件只能优先去读文档。我刚才很疑惑为什么开发者的说法和文档不一致，因为我就是使用了嗅探域名以外的功能，所以才会究根问底。

这是个误会。
