### ISSUE TITLE
 Quic sniffer  再次失效

### ISSUE THREAD

**Issue by dudylan** [XTLS/Xray-core#3359]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我搜索了issues，没有发现已提出的类似问题。

### 版本

```shell
1.8.4
在1.8.1中说明已经修复 Quic sniffer
当时看到即可尝试发现已经修复。但是最近出现还是无法sniffer 怀疑是http3 有更新
```

### 描述

 Quic sniffer 失效

### 重现方式

使用http3 的udp 通过sniffer的入站代理

**Comment by Fangliding** [comment]
至少给个配置文件说明没按预期sniff吧(

**Comment by RPRX** [comment]
至少用 1.8.11 吧，而且配置呢日志呢具体哪个域名没被 sniff 出来呢都没有，麻烦重发 issue
