### ISSUE TITLE
quic sniffer 失效

### ISSUE THREAD

**Issue by dudylan** [XTLS/Xray-core#3363]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我搜索了issues，没有发现已提出的类似问题。

### 版本

```shell
1.8.11
```

### 描述

在使用xray 访问http3 的网站时 无法通过sniffer 得出域名

### 重现方式

{
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "domain": [
            "www.baidu.com",
            "www.taurusxin.com"
          ],
          "outboundTag": "blackhole",
          "inboundTag": [
            "proxy2"
          ]
        },
        {
          "type": "field",
          "outboundTag": "direct",
          "inboundTag": [
            "proxy2"
          ]
        }
      ]
    },
    "stats": {},
    "inbounds": [
      {
        "port": 2809,
        "protocol": "socks",
        "listen": "127.0.0.1",
        "settings": {
          "auth": "password",
          "accounts": [
            {
              "user": "ABC",
              "pass": "ABC"
            }
          ],
          "udp": true
        },
        "tag": "proxy2",
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls",
            "quic"
          ]
        }
      }
    ],
    "outbounds": [
      {
        "protocol": "freedom",
        "settings": {},
        "tag": "direct"
      },
      {
        "protocol":"Blackhole",
        "tag" : "blackhole"
      }
    ],
    "log": {
      "loglevel": "debug",
      "dnsLog": true
    }
  }
以上是我的配置文件。
我使用的是netch源码进行的测试。 我把原本netch 启动xray的关掉。然后使他指向我手动启动的xray

我访问百度会出现连接已重置的页面。（因为我通过route把他转到了黑洞中）
我访问https://www.taurusxin.com/http3-enabled/时却可以正常访问  
我也在日志中清晰的看到
2024/05/15 11:58:27 [Info] [773605411] app/dispatcher: sniffed domain: www.baidu.com
baidu 有sniffed成功

但是我访问www.taurusxin.com时
[xray.log](https://github.com/XTLS/Xray-core/files/15316511/xray.log)
文件是我的日志
有一行
udp:127.0.0.1:64005 accepted udp:61.170.88.242:443 [proxy2 -> direct]
我确信这就是http3 的流量记录

**Comment by Fangliding** [comment]
也不是完全不能不过得弄一个sniff超时顺便还会增加延迟 em 问题是挺大的

**Comment by dudylan** [comment]
我很早就遇到了这个问题。但是当 看到1.8.1 更新记录后 升级版本尝试了一下。 当时是可以的。 但是又不行了。

**Comment by Fangliding** [comment]
实在不行可以用用fakedns()

**Comment by dudylan** [comment]
Fakedns 是需要自己指定IP的吧。

**Comment by dudylan** [comment]
为什么要抓包去看呢，日志里应该比较清楚的吧。
https://github.com/XTLS/Xray-core/issues/3363#issuecomment-2111973796

**Comment by SciFiDevSan** [comment]
基于Chromium的实现，在QUIC握手过程中，crypto frame可以被分片到多个UDP包中。这在Edge和Chrome等浏览器中表现明显，导致Xray无法正确处理QUIC流量。firefox遵循标准的QUIC实现，能够成功嗅探和处理QUIC流量，可以考虑使用firefox缓解一下。

不过是否有计划修复Xray中的QUIC嗅探问题，以确保与这些浏览器的兼容性？

**Comment by Fangliding** [comment]
整挺好
