### ISSUE TITLE
Invert Routing Rules

### ISSUE THREAD

**Issue by APT-ZERO** [XTLS/Xray-core#3365]
Please add invert for Routing Rules
for example
```
{
  "ip": ["geosite:cn"],
  "!Port": "80,443",
  "outboundTag": "block"
}
```
to match China IPs with any port except port 80 and 443

**Comment by Fangliding** [comment]
Maybe route all Chinese IP to block and add a rule to route 80,443 to different one

**Comment by Fangliding** [comment]
> Bro that is an Example, why are you acting like this

I see that you have opened many issues to provide these small proposals,some are useless, some are useful, but we have no responsibility to spend time implementing it. And these opinions are not very constructive either. So after consideration, I marked them as not planned. If you can implement these feature, we would be pleasure to merge.

**Comment by Fangliding** [comment]
I spend a whole week to closed massive number of issues to maintain a clean list of open issues. If I let these issues open until they pile up hundreds of open issues in the list like before, then they are no different from being closed.
