### ISSUE TITLE
1.8.12 docker模式下kernelMode": false,    wireguard出站错误

### ISSUE THREAD

**Issue by swxk521** [XTLS/Xray-core#3379]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我搜索了issues，没有发现已提出的类似问题。

### 版本

1.8.12

### 描述

1.8.12 docker模式下kernelMode": false,    wireguard出站错误

### 重现方式

        {
            "tag": "wgcf",
            "protocol": "wireguard",
            "settings": {
                "kernelMode": false,
                "secretKey": "************************",
                "address": [
                    "172.16.0.2/32",
                    "*******************/128"
                ],
                "peers": [
                    {
                        "publicKey": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
                        "endpoint": "engage.cloudflareclient.com:2408"
                    }
                ],
                "mtu": 1280,
                "domainStrategy": "ForceIPv6v4"
            }
        }

### 客户端配置

sdfdsffdssssssssssssssssssssss

### 服务端配置

<details><pre><code>
        {
            "tag": "wgcf",
            "protocol": "wireguard",
            "settings": {
                "kernelMode": false,
                "secretKey": "************************",
                "address": [
                    "172.16.0.2/32",
                    "*******************/128"
                ],
                "peers": [
                    {
                        "publicKey": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
                        "endpoint": "engage.cloudflareclient.com:2408"
                    }
                ],
                "mtu": 1280,
                "domainStrategy": "ForceIPv6v4"
            }
        }

</code></pre></details>

### 客户端日志

dfdfsdsf

### 服务端日志

<details><pre><code>
github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dial(0xc000ddbc00, {0x1556270, 0x1f40540}, {{0x1556858, 0xc0006bc0b0}, 0x968, 0x3})
        github.com/xtls/xray-core/app/proxyman/outbound/handler.go:288 +0xd1d
github.com/xtls/xray-core/proxy/wireguard.(*netBindClient).connectTo(0xc000d607d0, 0xc0003ef1a0)
        github.com/xtls/xray-core/proxy/wireguard/bind.go:131 +0x4b
github.com/xtls/xray-core/proxy/wireguard.(*netBindClient).Send(0xc000d607d0, {0xc0001fceb8, 0x1, 0x7f47bfe4d5b8?}, {0x155b1d8?, 0xc0003ef1a0})
        github.com/xtls/xray-core/proxy/wireguard/bind.go:174 +0x56
golang.zx2c4.com/wireguard/device.(*Peer).SendBuffers(0xc000db7b08, {0xc0001fceb8, 0x1, 0x1})
        golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/peer.go:136 +0x202
golang.zx2c4.com/wireguard/device.(*Peer).SendHandshakeInitiation(0xc000db7b08, 0x2?)
        golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/send.go:136 +0x3fe
golang.zx2c4.com/wireguard/device.(*Peer).SendStagedPackets(0xc000db7b08)
        golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/send.go:350 +0xe5
golang.zx2c4.com/wireguard/device.(*Device).RoutineReadFromTUN(0xc0000f1188)
        golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/send.go:293 +0x85d
created by golang.zx2c4.com/wireguard/device.NewDevice in goroutine 136
        golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/device.go:322 +0x44c
</code></pre></details>

**Comment by Fangliding** [comment]
。。完整配置 模板当耳边风是吧

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/releases/tag/v1.8.13
