### ISSUE TITLE
Suggestion: flag to disable logging in a separate inbound/outbound.

### ISSUE THREAD

**Issue by sakontwist** [XTLS/Xray-core#3384]
With a large number of servers we have to use monitoring, but zabbix creates quite a lot of connections and “spoils” server addresses. I use a separate dokodemo redirects on a regional VPS to not give connections to my ISP's blocking system, but because of this a huge amount of unnecessary information is written in the log of the regional vps, which makes it difficult to debug client problems.

**Comment by Fangliding** [comment]
If it's just debugging the server, I don't think it's necessary to do it on a large number of servers and even use monitoring. It is completely possible to place the service in a simpler environment.
By the way, the existing logging system of xray is also difficult to make overall modifications
