### ISSUE TITLE
编译xray-core时出现错误：gvisortun/tun.go中 'pkt.IsNil undefined' 的问题

### ISSUE THREAD

**Issue by ironWee** [XTLS/Xray-core#3385]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我搜索了issues，没有发现已提出的类似问题。

### 版本

1.8.12

### 描述

在构建 xray-core 项目时，遇到了一个编译错误。具体地说，错误信息显示在文件 gvisortun/tun.go 的第 160 行，报告了一个 pkt.IsNil undefined 错误。该错误表明 *stack.PacketBuffer 类型没有 IsNil 方法或字段。

### 重现方式

1. 下载xray-core 1.8.12的源代码
2. 修改go.mod文件，在其中添加：replace gvisor.dev/gvisor => gvisor.dev/gvisor go。（这么做的原因时，使用默认的go.mod配置，会出现gvisor未知版本的错误，手动修改gvisor为可用的版本v0.0.0-20240516011603-48d0743bfc4e，也会报错undefined: MaskOf64，在[https://github.com/google/gvisor/issues/8237](https://github.com/google/gvisor/issues/8237)中找到了解决办法）
3. 运行编译命令：`CGO_ENABLED=0 go build -v -o xray -trimpath -ldflags "-s -w -buildid=" ./main`，就会报错：
 ```github.com/xtls/xray-core/proxy/wireguard/gvisortun
# github.com/xtls/xray-core/proxy/wireguard/gvisortun
proxy/wireguard/gvisortun/tun.go:160:9: pkt.IsNil undefined (type *stack.PacketBuffer has no field or method IsNil)
```
- 操作系统版本：Ubuntu 22.04.2 LTS
- go版本：go version go1.22.2 linux/amd64

### 客户端配置

<details><pre><code>

</code></pre></details>

### 服务端配置

<details><pre><code>

</code></pre></details>

### 客户端日志

<details><pre><code>

</code></pre></details>

### 服务端日志

<details><pre><code>

</code></pre></details>

**Comment by Fangliding** [comment]
> 使用默认的go.mod配置，会出现gvisor未知版本的错误

项目本身的依赖完全是好的 不然release也编译不出来 你可以花一分钟开个codespace跑个make命令试一试

gvisor这玩意是出了名的难伺候 gomod里是23年的版本 你随便替换到最新版 炸是必然的
