### ISSUE TITLE
stop xray core in wiregourd

### ISSUE THREAD

**Issue by aliamg1356** [XTLS/Xray-core#3387]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I searched issues and did not find any similar issues.

### Version

1.8.12

### Description

In new versions 1.8.12 and 1.8.13, when we connect the wireguard, the kernel gets an error and stops

### Reproduction Method

wiregourd

### Client config

<details><pre><code>
wiregourd android client
</code></pre></details>

### Server config

<details><pre><code>
ubuntu20.0.4
</code></pre></details>

### Client log

<details><pre><code>
no log
</code></pre></details>

### Server log

<details><pre><code>
github.com/xtls/xray-core/app/proxyman/inbound/worker.go:306 +0x305
</code></pre></details>

**Comment by RPRX** [comment]
请重新测试 v1.8.3 并按规范发 issue

**Comment by aliamg1356** [comment]
> 请重新测试 v1.8.3 并按规范发 issue

This problem persists in version 1.8.13
