### ISSUE TITLE
API: Stats of the user remains when the user got deleted through API

### ISSUE THREAD

**Issue by somebodywashere** [XTLS/Xray-core#3390]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I searched issues and did not find any similar issues.

### Version

latest

### Description

The issue is that stats of the user remains when the user got deleted through API.

So If I want to delete and then add user through API with the same Email, then new user will keep the same stats until core is restarted. So only current solution is to restart Xray core or modify Email :(

I suggest that:
Stats of the user needs to be deleted with the user.
If not possible than we need to restart statsService on user deletion.
Or if even that's not acceptable than at least we need a method to restart statsService / flush stats without restarting whole core.

### Reproduction Method

Delete a user through API, then add a new user through API with the same Email. Stats will remain from deleted user.

### Client config

<details><pre><code>
not needed
</code></pre></details>

### Server config

<details><pre><code>
not needed
</code></pre></details>

### Client log

<details><pre><code>
not needed
</code></pre></details>

### Server log

<details><pre><code>
not needed
</code></pre></details>

**Comment by Fangliding** [comment]
Classic ancient feature's shit mountain issue

**Comment by somebodywashere** [comment]
> Classic ancient feature's shit mountain issue

What do you mean by that?

**Comment by chise0713** [comment]
> > Classic ancient feature's shit mountain issue
> 
> What do you mean by that?

https://en.wiktionary.org/wiki/屎山

**Comment by MK0ltra** [comment]
Well, this feature is useful for VPN sellers, so you should fix it yourself.
If you really think about it, there are people that connect to internet for business goals, Then if this project can help people connect to internet it should be **completely** removed from Github, because it's not for making money.

**Comment by somebodywashere** [comment]
> Well, this feature is useful for VPN sellers, so you should fix it yourself. If you really think about it, there are people that connect to internet for business goals, Then if this project can help people connect to internet it should be **completely** removed from Github, because it's not for making money.

Why being so toxic for actually no reason. I don't mean to add any new features and Yes, I can maybe fix it later on myself and make a PR. But If I post an issue there's some reasons behind that. 

From your logic it's better to remove API then

**Comment by yuhan6665** [comment]
Correct. API is designed for UI clients, web panels, 机场 backends and we are committed to improve APIs
..of the community, by the community, for the community :)

**Comment by Fangliding** [comment]
To be honest, I feel that the API of Xray is indeed undermaintenance, so many times, some things about it are put on hold
This system inherited from v2fly is indeed quite problematic. If we committed to repairing this, it would be like giving free work to commercial activities as mentioned above.
Personally, I do want to remove this system. Mature commercial panels use completely different mechanisms, but it seems that there are people who need it, and there are occasional PR submissions, so this is probably the current situation.

**Comment by Grvzard** [comment]
[https://github.com/Grvzard/Xray-core/tree/fix-stats](https://github.com/Grvzard/Xray-core/tree/fix-stats)
I don't think it's wise to use the built-in user management stuff, but check this out if it helps.

**Comment by somebodywashere** [comment]
> https://github.com/Grvzard/Xray-core/tree/fix-stats I don't think it's wise to use the built-in user management stuff, but check this out if it helps.

Thanks! Didn't have enought time to check tho. But uf you tested and everything is ok, I think it's ok to make a PR

**Comment by Fangliding** [comment]
仔细研究之后我觉得这个不应该算是BUG  这套东西的逻辑是 入站是入站 用户是用户 一个用户在多个入站中共享一个流量统计器 东西分开的 入站的用户删除不应该影响全局的流量统计

**Comment by yuhan6665** [comment]
有道理 所以业务逻辑应该是在删除或者新加email的时候使用 stats API 重置用户流量记录
core 可以不管
