### ISSUE TITLE
Bump up gvisor dependencies

### ISSUE THREAD

**Issue by gyuho** [XTLS/Xray-core#3395]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I searched issues and did not find any similar issues.

### Version

v1.8.11

### Description

`gvisor.dev/gvisor v0.0.0-20231202080848-1f7806d17489` seems outdated:

https://github.com/XTLS/Xray-core/blob/0a3c449cdf16f8dbd1f3823621f2a22806c43677/go.mod#L32

When a project has another dependency with higher gvisor version, the build will fail:

```
# github.com/xtls/xray-core/proxy/wireguard
../go/pkg/mod/github.com/xtls/xray-core@v1.8.11/proxy/wireguard/tun.go:197:131: too many arguments in call to gonet.NewUDPConn
        have (*stack.Stack, *waiter.Queue, tcpip.Endpoint)
        want (*waiter.Queue, tcpip.Endpoint)
```

https://github.com/XTLS/Xray-core/blob/0a3c449cdf16f8dbd1f3823621f2a22806c43677/proxy/wireguard/tun.go#L18-L22

### Reproduction Method

For example, you can have a dependency that itself imports the following:

> gvisor.dev/gvisor v0.0.0-20240306221502-ee1e1f6070e3

https://github.com/tailscale/tailscale/blob/5ad0dad15e96edf591e8c2c884af1c8d2fd3f52d/go.mod#L104

```go
import _ "tailscale.com/tsnet"
```

```go
require tailscale.com v1.66.4
```

Then importing `github.com/xtls/xray-core/proxy/wireguard` will fail.

### Client config

<details><pre><code>

</code></pre></details>

### Server config

<details><pre><code>

</code></pre></details>

### Client log

<details><pre><code>

</code></pre></details>

### Server log

<details><pre><code>

</code></pre></details>

**Comment by yuhan6665** [comment]
Yes, it is bounded by https://git.zx2c4.com/wireguard-go/log/
Someone need to fix in wireguard-go.
