### ISSUE TITLE
Weird behaviour of reverse proxy

### ISSUE THREAD

**Issue by pulsarice** [XTLS/Xray-core#3397]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I searched issues and did not find any similar issues.

### Version

1.8.11

### Description

I have 3 foreign servers connected to one domestic server using reverse proxy.

Previously I had only one reverse connection per foreign server (3 portals in total), But there was connection quality issues. 

I created 3 reverse proxies per foreign server.

Now On the domestic server I have 9 portals.
```
portal-serverA-1
portal-serverA-2
portal-serverA-3
portal-serverB-1
portal-serverB-2
portal-serverB-3
portal-serverC-1
portal-serverC-2
portal-serverC-3
```

for example portal-serverA-1 to A-3 connections are from the **same serverA**, but with **different port** numbers (all vless-tcp-reality with flow:none)
I am using leastPing balancers with this observatory configuration:
```
{
  "subjectSelector": [
    "portal"
  ],
  "probeURL": "...", // I tried different addresses like http://cp.cloudflare.com/ and http://www.gstatic.com/generate_204
  "probeInterval": "20s",
  "enableConcurrency": true
}
```
Users' traffic are routed using balancers. for example usergroup1 is always connected to serverA using `portal-serverA` selector.

Something strage is happening:
for example when usergroup1's requests are being routed through portal-serverA-1 and the traffic gets heavy, sometimes I get this in server log:
```
[Info] app/observatory: the outbound portal-serverA-3 is alive:0.111858545
[Info] app/observatory: the outbound portal-serverA-2 is alive:0.116969748
[Info] app/observatory: the outbound portal-serverA-1 is dead: > app/observatory: GET request failed:app/observatory: outbound failed to relay connection > Get "http://cp.cloudflare.com/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) > app/observatory: with outbound handler report > app/observatory: underlying connection failed > app/observatory: failed to produce report

//all other portals to other servers are alive too.
```
Then the balancer chooses another portal from the same server. But the same error might happen to the newly selected portal if the traffic load gets heavy.

Why the active portal from serverA fails to ping under heavy traffic, while other portals from the same server are ok (with good ping values around 100ms)? 
If the domestic server's network is congested, all 9 portals should fail.
If the serverA's network is congested, all 3 serverA's portals should fail.

Is it related to the behaviour of default MUX of reverse proxies? (I have not enabled MUX on outbound interconnections of foreign servers as per documentation).  Maybe the MUX is failing under heavy load!?

It could also be caused by Iranian GFW. I don't know for sure.

Does `"enableConcurrency": true` has any impact on this matter? I tried disabling it, but didn't see any meaningful difference.

**Comment by Fangliding** [comment]
When the traffic is high, the connection is disconnected (possibly due to various reasons)
Then the core will attempt to reconnect
It is normal for a single TCP connection to be disconnected due to excessive traffic in poor network conditions

**Comment by Fangliding** [comment]
> What are the MUX parameters used on reverse proxy connections? (like "concurrency" and ...)
This is a bit difficult to explain, in short, this parameter is not applicable to mux on reverse proxy, there is no such concept.

> What if I use a reverse connection that does not support mux, like vision? I tested it I'm wondering why it works!
The special mechanism of vision will not work, just like if you haven't enabled it
