### ISSUE TITLE
[Feature Request] Changing the order of ping checks when "enableConcurrency": false

### ISSUE THREAD

**Issue by pulsarice** [XTLS/Xray-core#3398]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I searched issues and did not find any similar issues.

### Version

1.8.11

### Description

On my server I have 9 portals.

I am using leastPing balancers with this observatory configuration:
```
{
  "subjectSelector": [
    "portal"
  ],
  "probeURL": "...",
  "probeInterval": "30s",
  "enableConcurrency": false
}
```

When I read the log, the portals are checked in alphabetical order:
```
portal-serverA-1
portal-serverA-2
portal-serverA-3
portal-serverB-1
portal-serverB-2
portal-serverB-3
portal-serverC-1
portal-serverC-2
portal-serverC-3
```
I want the order to be like this:
```
portal-serverA-1
portal-serverB-1
portal-serverC-1
portal-serverA-2
portal-serverB-2
portal-serverC-2
portal-serverA-3
portal-serverB-3
portal-serverC-3
```
I even changed the observatory like this:
```
{
  "subjectSelector": [
    "portal-serverA-1",
    "portal-serverB-1",
    "portal-serverC-1",
    "portal-serverA-2",
    "portal-serverB-2",
    "portal-serverC-2",
    "portal-serverA-3",
    "portal-serverB-3",
    "portal-serverC-3"
  ],
  "probeURL": "...",
  "probeInterval": "30s",
  "enableConcurrency": false
}
```
But the order that portals are being checked don't change.
Is it possible to change the order of ping checks?

**Comment by Fangliding** [comment]
It was intentionally designed like this

https://github.com/XTLS/Xray-core/blob/0a3c449cdf16f8dbd1f3823621f2a22806c43677/app/observatory/observer.go#L77

I don't think changing it is very useful
