### ISSUE TITLE
[Feature Request] https h2 proxy

### ISSUE THREAD

**Issue by YiGeRen-yl** [XTLS/Xray-core#3403]
我有个HTTPS节点，在xray上无法出战，使用HTTP打开TLS没用，但是用手机shadowsocks可以用。是否可以添加XRAY 出站

**Comment by Fangliding** [comment]
啥https节点和手机shadowsocks啊 说清楚点

**Comment by YiGeRen-yl** [comment]
> 啥https节点和手机shadowsocks啊 说清楚点

写错了就是正常的HTTPS 代理节点，用小火煎可以连上，放到xray出战连不上
我配置是这么写的

{
      "tag": "KR",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "服务器IP",//服务器IP
              "port": 110,//服务器端口
              "users": [
                {
                  "Username": "yl1677866238",//将my-username改为你的用户名.
                  "Password": "proverbdevice" //将my-password改为你的密码
                }
              ] 
            }
          ]
        },
        "streamSettings": {
          "security": "tls", //如果是HTTPS代理,需要將none改為tls
          "tlsSettings": {
            "allowInsecure": false
            //检测证书有效性
        }
      }
    }

**Comment by Fangliding** [comment]
测试了一会 具体情况如下
xray会尝试和服务端协商h2 如果协商成功 将会优先尝试使用http2进行连接
但是大多数时候 只是服务端的**TLS套件**接受了这个协商 大多数服务端包括xray都没有实现 h2 http proxy 导致无法正确连接

**Comment by YiGeRen-yl** [comment]
> 临时解决方法
> 
> ```
> "tlsSettings": {
>     "alpn": "http/1.1"
> }
> ```
> 
> 要不考虑添加一个参数 `"http2": false` http 出站默认不再尝试建立http2 除非设置为 `true` 不过想了想多少也是服务端实现不标准的原因 服务不支持h2协商出h2 不管也说得过去 ~然后测了下xray也这样 还是不回旋镖黑自己了~ @yuhan6665

改了也不行，https就是用不了，不知道什么原因。

**Comment by RPRX** [comment]
> 改了也不行，https就是用不了，不知道什么原因。

可能是服务端只支持 h2？~~我对 HTTPS 代理不了解~~

**Comment by Fangliding** [comment]
> > 改了也不行，https就是用不了，不知道什么原因。
> 
> 可能是服务端只支持 h2？~我对 HTTPS 代理不了解~

后来tg私聊我看了下 他那个服务端只支持tls1.2 xray自己发出的连接是tls1.3 only的(没有tls1.2的密码套件，服务端看到直接tls alert断开)

**Comment by RPRX** [comment]
> xray自己发出的连接是tls1.3 only的

？不是吧

**Comment by Fangliding** [comment]
> > xray自己发出的连接是tls1.3 only的
> 
> ？不是吧

抓包结果如此 我好像没在套件里看到tls1.2的
当然如果说指纹问题的话 utls没这个问题

**Comment by RPRX** [comment]
> > > xray自己发出的连接是tls1.3 only的
> > 
> > 
> > ？不是吧
> 
> 抓包结果如此 我好像没在套件里看到tls1.2的 当然如果说指纹问题的话 utls没这个问题

Xray 的 TLS 和 uTLS 都支持 1.2 的套件

**Comment by Fangliding** [comment]
> > > > xray自己发出的连接是tls1.3 only的
> > > 
> > > 
> > > ？不是吧
> > 
> > 
> > 抓包结果如此 我好像没在套件里看到tls1.2的 当然如果说指纹问题的话 utls没这个问题
> 
> Xray 的 TLS 和 uTLS 都支持 1.2 的套件

好吧是我搞错了 不过Xray发的tls只有14个套件 Chrome会发三十多个curl会发四十多个 估计是服务端奇怪实现拒绝了xray提供的套件

**Comment by yuhan6665** [comment]
Golang 比较超前 默认把安全性低的套件都删了 如果没有其它问题这个可以关了。。

**Comment by Fangliding** [comment]
@yuhan6665 h2那个问题还是有 动还是不动()

**Comment by yuhan6665** [comment]
我这边不算 priority ;) 那 issue 先放着

**Comment by RPRX** [comment]
~~标题和标签改了~~

**Comment by Fangliding** [comment]
~~什么时候这个issue从默认使用h1 http proxy升级为了支持h2 http proxy入站~~
