### ISSUE TITLE
Is now any available package for building IOS and Android client in Flutter or React Native

### ISSUE THREAD

**Issue by LinYKen** [XTLS/Xray-core#3409]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I searched issues and did not find any similar issues.

### Version

1.8.13

### Description

Is now any available package for building IOS and Android client in Flutter or React Native

### Reproduction Method

not a bug actually, just a simple question, hope someone knows

### Client config

<details><pre><code>

</code></pre></details>

### Server config

<details><pre><code>

</code></pre></details>

### Client log

<details><pre><code>

</code></pre></details>

### Server log

<details><pre><code>

</code></pre></details>

**Comment by Fangliding** [comment]
nope
