### ISSUE TITLE
2022 edition shadowsocks methods don't work for `clients`

### ISSUE THREAD

**Issue by fastaria** [XTLS/Xray-core#3411]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I searched issues and did not find any similar issues.

### Version

1.8.13

### Description

these methods
`2022-blake3-aes-128-gcm`
`2022-blake3-aes-256-gcm`
`2022-blake3-chacha20-poly1305`

are not supported for shadowsocks `clients`

---

This inbound config works
```json
{
  "protocol": "shadowsocks",
  "settings": {
    "password": "password",
    "method": "2022-blake3-aes-256-gcm"
  }
}
```

but this config throws `unsupported cipher method: 2022-blake3-aes-256-gcm` error
```json
{
  "protocol": "shadowsocks",
  "settings": {
    "clients": [
      {
        "password": "password",
        "method": "2022-blake3-aes-256-gcm"
      }
    ]
  }
}
```

### Reproduction Method

just start a server with the provided config

### Client config

N/A

### Server config

<details><pre><code>
{
  "inbounds": [
    {
      "protocol": "shadowsocks",
      "port": "1080",
      "settings": {
        "clients": [
          {
            "password": "eLnQ3f97C3t5tWBbxwQ0B/v3szGIGdAShNyOFKYBh3M=",
            "method": "2022-blake3-aes-256-gcm"
          }
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom"
    }
  ]
}
</code></pre></details>

### Client log

N/A

### Server log

<details><pre><code>
Started Xray Service.
Xray 1.8.13 (Xray, Penetrates Everything.) 3120ca4 (go1.22.3 linux/amd64)
A unified platform for anti-censorship.
Failed to start: main: failed to load config files: [/usr/local/etc/xray/config.json] > infra/conf: unsupported cipher method: 2022-blake3-chacha20-poly1305
xray.service: Main process exited, code=exited, status=23/n/a
</code></pre></details>

**Comment by Fangliding** [comment]
SS2022 does not support multi user mode(```"clients"```)
This mode has also been deprecated and removed from the document.

**Comment by Fangliding** [comment]
The doc isn't clear, I'll fix it later
