### ISSUE TITLE
[Feature Request] change socket‘s access permissions

### ISSUE THREAD

**Issue by lelemka0** [XTLS/Xray-core#342]
当inbound的listen为一Unix domain socket时，socket文件的权限为755。
当core及web服务器的运行用户不同，通过套接字反代时，无法访问。
希望能够设置socket权限

**Comment by rprx** [comment]
看来 DS 需要一个整体修改，包括解决奇怪的性能问题

**Comment by yuhan6665** [comment]
Fixed in v1.5.4
