### ISSUE TITLE
observatory dns problem when using vpn mode

### ISSUE THREAD

**Issue by s-kile** [XTLS/Xray-core#3425]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I searched issues and did not find any similar issues.

### Version

1.8.11

### Description

when using observatory, xray core can get ip from domains to test outbounds
but when using and vpn mode (like in v2rayng):

if not using observatory and balancers: xray core is able to get ip from domain for an outbound (and it will connect). 

but when using observatory and vpn mode: xray core seems to have problem to get ip of domains to check pings and no outbound  can be selected (however when replacing domains with ips observatory and balancer work fine)

### Reproduction Method

{

  "observatory": {
    "subjectSelector": [
      "proxy"
    ],
    "probeURL": "http://cp.cloudflare.com/generate_204",
    "probeInterval": "600s",
    "enableConcurrency": true
  },

  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "geoip:private"
        ]
      },
      {
        "type": "field",
        "balancerTag": "balast",
        "port": "0-65535"
      }
    ],
    "balancers": [
      {
        "tag": "least",
        "selector": [
          "proxy"
        ],
        "strategy": {
          "type": "leastping"
        },
        "fallbacktag": "block"
      }
    ]
  }
}

### Client config

<details><pre><code>

</code></pre></details>

### Server config

<details><pre><code>

</code></pre></details>

### Client log

<details><pre><code>

</code></pre></details>

### Server log

<details><pre><code>

</code></pre></details>

**Comment by Fangliding** [comment]
We do not have such called "vpn mode", this is usually related to some difficult to explain routing and loops.
Send issue to the GUI client

**Comment by s-kile** [comment]
@Fangliding 

> We do not have such called "vpn mode", this is usually related to some difficult to explain routing and loops. Send issue to the GUI client

@Fangliding 

with vpn mode i mean passing all the traffic through core. something v2rang does. and the core needs to resolve dns for itself and it is not related to gui client. please read carefully this is a very bigg issue when using observatory
