### ISSUE TITLE
Some problems with httpupgrade headers

### ISSUE THREAD

**Issue by mikeesierrah** [XTLS/Xray-core#3426]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I searched issues and did not find any similar issues.

### Version

1.8.13

### Description

When I set custom headers in the HTTP upgrade client configuration:

```json
"streamSettings": {
  "httpUpgradeSettings": {
    "host": "domain.com",
    "path": "/path",
    "headers": {
      "Sec-WebSocket-Version": "13",
      "Sec-WebSocket-Key": "X1xxxx=="
    }
  }
}
```
I get these packets inside pcap

GET /path HTTP/1.1
Host: domain.com
User-Agent: Go-http-client/1.1
Connection: upgrade
Sec-Websocket-Key: X1xxxx==
Sec-Websocket-Version: 13
Upgrade: websocket

At first glance, you might not notice the difference, but here’s what a standard WebSocket packet looks like in Wireshark: 
![image](https://github.com/XTLS/Xray-core/assets/144580664/079cf205-059b-493d-acaa-ab69236f39d2)

You’ll see the first ‘S’ in WebSocket is capitalized in normal ‘WS’, but it’s in lowercase in ‘HTTPupgrade’, while in my configuration JSON, it’s in caps. Also, the ‘U’ in ‘Connection: Upgrade’ is capitalized in a normal WebSocket, but in lowercase in HTTPupgrade.

It seems the core is altering the letter capitalization.

While these might seem trivial, a firewall can easily detect these anomalies and block or flag them.

### Reproduction Method

just try to add these settings to an httpupgrade connection and compare them with a normal ws 

no tls ofcourse

### Client config

<details><pre><code>
{
  "inbounds":[
    {
      "listen":"127.0.0.1",
      "port":10808,
      "protocol":"socks",
      "settings":{
        "auth":"noauth",
        "udp":true,
        "userLevel":8
      },
      "sniffing":{
        "destOverride":[
          "http",
          "tls"
        ],
        "enabled":true
      },
      "tag":"socks"
    },
    {
      "listen":"127.0.0.1",
      "port":10809,
      "protocol":"http",
      "settings":{
        "userLevel":8
      },
      "tag":"http"
    }
  ],
  "outbounds":[
    {
      "protocol":"vless",
      "settings":{
        "vnext":[
          {
            "address":"somedomain.domain",
            "port":8080,
            "users":[
              {
                "encryption":"none",
                "flow":"",
                "id":"0157f5d9-7cfc-418c-c3b4-d9acab3a7af1",
                "level":8,
                "security":"auto"
              }
            ]
          }
        ]
      },
      "streamSettings":{
        "httpupgradeSettings":{
          "host":"domain.com",
          "path":"/path",
          "headers":{
            "Sec-WebSocket-Version":"13",
            "Sec-WebSocket-Key":"X1O+jYrandomstuff=="
          }
        },
        "network":"httpupgrade",
        "security":"none"
      },
      "tag":"proxy"
    },
    {
      "protocol":"freedom",
      "settings":{
        
      },
      "tag":"direct"
    },
    {
      "protocol":"blackhole",
      "settings":{
        "response":{
          "type":"http"
        }
      },
      "tag":"block"
    }
  ]
}
</code></pre></details>

### Server config

<details><pre><code>
N/A
</code></pre></details>

### Client log

<details><pre><code>
N/A
</code></pre></details>

### Server log

<details><pre><code>
N/A
</code></pre></details>

**Comment by Fangliding** [comment]
@Fangliding 每天回这些狗吧issue还能涨点知识

**Comment by yuhan6665** [comment]
I'm ok if there is a way to keep capitalization
