### ISSUE TITLE
本地通过主机名访问的内网机器连接不上

### ISSUE THREAD

**Issue by asiaon123** [XTLS/Xray-core#3429]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我搜索了issues，没有发现已提出的类似问题。

### 版本

1.8.13

### 描述

本地内网的机器，本通过主机名连接，现在连接不上，看样子是没有去路由获取dns，不知道是配置不对还是什么原因

### 重现方式

统一局域网内的两台机器，一台通过主机名访问另一台

### 客户端配置

```json
"dns" : {
    "disableCache" : true,
    "disableFallback" : true,
    "disableFallbackIfMatch" : true,
    "queryStrategy" : "UseIPv4",
    "servers" : [
      {
        "address" : "8.8.8.8",
        "skipFallback" : false
      },
      {
        "address" : "tcp+local://223.5.5.5",
        "domains" : [
          "geosite:CN",
          "geosite:APPLE"
        ],
        "skipFallback" : false
      }
    ],
    "tag" : "dnsQuery"
  },
  "inbounds" : [
    {
      "listen" : "[::1]",
      "port" : 49897,
      "protocol" : "socks",
      "settings" : {
        "auth" : "noauth",
        "udp" : true
      },
      "sniffing" : {
        "destOverride" : [
          "http",
          "tls",
          "quic"
        ],
        "domainsExcluded" : [
          "courier.push.apple.com"
        ],
        "enabled" : true
      },
      "tag" : "socks"
    },
```

### 服务端配置

<details><pre><code>

</code></pre></details>

### 客户端日志

<details><pre><code>

</code></pre></details>

### 服务端日志

<details><pre><code>

</code></pre></details>

**Comment by Fangliding** [comment]
配置不全而且没有日志
主机名？ 主机名这部分奇奇怪怪的可能得用系统DNS才能解析出来

**Comment by asiaon123** [comment]
对 是主机名 ，就是 dns 搜索不到， 有没有能配置dns服务，如果搜索不到记录 能回到本机的 默认DNS解析的方式？

**Comment by Fangliding** [comment]
> 对 是主机名 ，就是 dns 搜索不到， 有没有能配置dns服务，如果搜索不到记录 能回到本机的 默认DNS解析的方式？

freedom的domainstrategy填asis 应该可以 如果不行的话我也没办法 去找golang
