### ISSUE TITLE
[Feature Request] ECH Support

### ISSUE THREAD

**Issue by Generator20** [XTLS/Xray-core#3436]
Is it possible to use unofficial SSL/TLS libraries like 'BoringSSL' or 'WolfSSL' in Xray-core?
These unofficial SSL/TLS libraries support the ECH or 'Encrypted Client Hello' feature which is very effective in bypassing DPIs.

**Comment by Fangliding** [comment]
Discussion see https://github.com/XTLS/Xray-core/pull/3253
In short, we decide to wait until gotls officially support it

**Comment by showgood163** [comment]
Is there any update on the client side ECH?
Seems like [the support is added in go 1.23](https://github.com/golang/go/issues/63369)

**Comment by Fangliding** [comment]
#3813
