### ISSUE TITLE
"routeOnly": true可否设计哪些域名不使用routeOnly

### ISSUE THREAD

**Issue by SatenRuiko-Lv0** [XTLS/Xray-core#3441]
inbound配置如下
inConfigure() {
	result='{
		"tag": "socks-in",
		"port": 10800,
		"protocol": "socks",
		"settings": {
			"network": "tcp,udp",
			"udp": true
		},
		"sniffing": {
			"enabled": 'true',
			"destOverride": ["http", "tls", "quic", "fakedns"],
			"routeOnly": true
		}
	}'
}
可否增加一个类似domainsExcluded的功能，为routeOnly配置一下哪些域名仅路由连接使用ip请求，哪些域名路由并直接请求？

**Comment by Fangliding** [comment]
没看懂你这句话啥意思 “仅路由连接使用ip请求”
这部分的逻辑很简单 sniffing开了会让dest从IP被重置成域名 想要某些域名不被重置就加进domainsExcluded 都不想重置就开routeOnly

**Comment by Fangliding** [comment]
1 我没看过代码不过应该是一样的 都是不重置目标地址
2 只是不重置地址 路由还是可以匹配到里面的域名
3 是
3 没有ipsExcluded这个参数

**Comment by SatenRuiko-Lv0** [comment]
> 1 我没看过代码不过应该是一样的 都是不重置目标地址 2 只是不重置地址 路由还是可以匹配到里面的域名 3 是 3 没有ipsExcluded这个参数

非常抱歉，大佬您有空的话可以看一下这个帖子吗，我是看到这上面说有ipsExcluded，所以才有这个疑问的
[https://github.com/XTLS/Xray-core/pull/643#issue-941463146](url)

**Comment by SatenRuiko-Lv0** [comment]
> 1 我没看过代码不过应该是一样的 都是不重置目标地址 2 只是不重置地址 路由还是可以匹配到里面的域名 3 是 3 没有ipsExcluded这个参数

非常抱歉，大佬您有空的话可以看一下这个帖子吗，我是看到这上面说有ipsExcluded，所以才有这个疑问的
https://github.com/XTLS/Xray-core/pull/643#issue-941463146

**Comment by Fangliding** [comment]
这是PR 还没合并 大概是历史原因 RPRX消失了一段时间 这个改动太大 其他人没合并 然后一直拖到现在 这段时间core细细碎碎还有一些其他改动导致现在这个PR也不好合并进来了 一直没人来复查就挂在这了

**Comment by SatenRuiko-Lv0** [comment]
> 这是PR 还没合并 大概是历史原因 RPRX消失了一段时间 这个改动太大 其他人没合并 然后一直拖到现在 这段时间core细细碎碎还有一些其他改动导致现在这个PR也不好合并进来 一直没人来复查就挂在这了 你看到的陈旧PR大都是这个原因还挂在那

明白了，非常感谢大佬解答
