### ISSUE TITLE
domainsExcluded支持正则表达式和geosite:cn写法

### ISSUE THREAD

**Issue by SatenRuiko-Lv0** [XTLS/Xray-core#3447]
现在的domainsExcluded只能单个域名往里写感觉实在是不够用哇
如题，不知道各位大佬有没有什么兴趣高抬贵手

**Comment by Fangliding** [comment]
考虑到这是一个被~~无限期~~鸽置的部分 不想动太多 我可以暂时糊一个简单的正则表达式进去 应该那么搞吗
@yuhan6665

**Comment by SatenRuiko-Lv0** [comment]
大佬牛逼，
(话说如果geo写法是不是会更容易实现一些)

**Comment by Fangliding** [comment]
没有 geo麻烦不少

**Comment by yuhan6665** [comment]
> 考虑到这是一个被~~无限期~~鸽置的部分 不想动太多 我可以暂时糊一个简单的正则表达式进去 应该那么搞吗
> @yuhan6665 

不动太多我觉得可以
