### ISSUE TITLE
HTTP Fingerprint Impersonate

### ISSUE THREAD

**Issue by APT-ZERO** [XTLS/Xray-core#3448]
Hello
Currently all proxy clients uses utls to impersonate real browser tls fingerprint
But idk why don't you add same option for non-tls proxies?

This is a request to http website using Google Chrome :
```
GET /online HTTP/1.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Cache-Control: no-cache
Host: brightuniqueyoungsunrise.neverssl.com
Pragma: no-cache
Proxy-Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
```
And this is a request to same website using Mozilla Firefox :
```
GET /online/ HTTP/1.1
Host: brightuniqueyoungsunrise.neverssl.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Upgrade-Insecure-Requests: 1
Connection: keep-alive
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Pragma: no-cache
Cache-Control: no-cache
```
Headers and their order is different for each clients, easy for firewall to fingerprint check http connections
Setting custom header using Xray will not make requests like real ones, and they are also hard to config

This golang lib have http fingerprint impersonate option, you can integrate this to Xray or create your own way
https://req.cool/docs/tutorial/http-fingerprint/

**Comment by Fangliding** [comment]
You can configure the required headers yourself. We do not intend to add more such camouflage to plain HTTP
