### ISSUE TITLE
reality 奇怪的现象.

### ISSUE THREAD

**Issue by wudgaby** [XTLS/Xray-core#3451]
我的reality配置如下.
在访问google,facebook都能很好响应.
但是在访问twitch.tv, x.com, youtube.com的时候. 打不开网站, 发现是有些js,css完全加载不出来. 
加载js出现ERR_CONNECTION_CLOSED.导致网站打不开.
使用trojan协议就没出现问题.
有大佬帮忙看看是什么原因吗? 已经焦头烂额了.
![image](https://github.com/XTLS/Xray-core/assets/234605/ed06c682-bfef-47c4-be83-d4ca3defdfb4)
![2](https://github.com/XTLS/Xray-core/assets/234605/b8969ebb-d902-4be9-85ca-18fc71dda343)

**Comment by Fangliding** [comment]
版本是多少 以前的xtls可能有一点这种小问题 现在已经基本完全修复了 以及如果不开xtls/reality是什么情况 如果还是这样只能是服务器自己的问题了

**Comment by wudgaby** [comment]
好的.谢谢. 似乎找到问题了
