### ISSUE TITLE
vless ws no tls cdn problem

### ISSUE THREAD

**Issue by DrAmirB** [XTLS/Xray-core#3452]
After upgrading the xray core from 1.8.9 to higher versions, vless ws no tls (cdn cloudflare) configs got an EOF error, which is resolved after downgrade to 1.8.9

I use this config:
<details><pre><code>
{
  "tag": "VLESS + WS",
  "listen": "0.0.0.0",
  "port": ,
  "protocol": "vless",
  "settings": {
      "clients": [],
      "decryption": "none"
    },
  "streamSettings": {
    "network": "ws",
    "wsSettings": {
      "path": "/",
      "headers": {
        "Host": "example.com"
      }
    },
    "security": "none"
  },
  "sniffing": {
    "enabled": true,
    "destOverride": ["http", "tls", "fakedns"]
  }
}
</code></pre></details>

**Comment by Fangliding** [comment]
Please provide logs and client config

**Comment by DrAmirB** [comment]
> Please provide logs and client config
> Follow the template otherwise this issue will be closed

```
[Warning] failed to handler mux client connection > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (ws://185.146.173.185:2052/example.com): 404 Not Found > websocket: bad handshake] > common/retry: all retry attempts failed

06-17 15:01:55.795 I/GoLog   (30402): [Warning] failed to handler mux client connection > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (example.com): 404 Not Found > websocket: bad handshake] > common/retry: all retry attempts failed

06-17 15:01:55.796 D/com.v2ray.ang(30402): measureV2rayDelay: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": EOF

06-17 15:01:55.807 I/GoLog   (30402): tcp:127.0.0.1:41752 accepted tcp:149.154.167.92:443 [socks -> proxy]

06-17 15:01:55.809 I/GoLog   (30402): tcp:127.0.0.1:41744 accepted tcp:149.154.167.92:443 [socks -> proxy]
````

**Comment by yuhan6665** [comment]
```
      "headers": {
        "Host": "example.com"
      }
```
Host 大小写问题？

**Comment by DrAmirB** [comment]
> ```
>       "headers": {
>         "Host": "example.com"
>       }
> ```
> Host 大小写问题？

I don't know exactly! I set a long host and path with cloudflare proxy on without using tls.
I can't connect to the config after the 1.8.10 update. I asked others who use the same method that I used. They have the same problem.

**Comment by Fangliding** [comment]
Core will now check if the host is correct, if doesn't it will throw an err(even though I emphasized it twice, I still haven't seen the server logs), and if it is not necessary, remove the header field on the server side

**Comment by yuhan6665** [comment]
Maybe try remove Host header

**Comment by DrAmirB** [comment]
I used randomly capital letters in host like:

Name1nAme2naMe3.example.CoM

Could this be the problem?
