### ISSUE TITLE
[Feature-Request] splithttp using http3

### ISSUE THREAD

**Issue by Mfire2001** [XTLS/Xray-core#3456]
I just saw the new realease and saw httpsplit,from my undrasting it works by having multiple connections for upload and download and can be used with cdns without websocket
Is it possible to have the same thing with http3?cloudflare supports quic but I think it deliveres connections to origin server using http1.1
This is what came to my brain:the server side is the same but the client send each GET /?session=<uuid> and POST /?session=<uuid> using http3 instead of http1.1 or h2

**Comment by Fangliding** [comment]
H3 is probably too complicated, especially now there are still many issues with QUIC

**Comment by Mfire2001** [comment]
> H3 is probably too complicated, especially now there are still many issues with QUIC

U are right, but i think it kinda worth it,since quic has built in multiplexing and u can have all the get and post requests using the same udp socket,xray uses http.client for handling requests right?I will see xray's code and see what I can do,

**Comment by Fangliding** [comment]
What I want to say is that the main purpose of this protocol is to pass through CDN, and even Cloudflare does not support h3 to origin, let alone other CDN.
If not use CDN, just as PoneyClairDeLune said there already be many good solutions.

**Comment by Fangliding** [comment]
The acceleration method used by hy2 is not applicable to CDN
In short, its performance is far from what you imagine

**Comment by RPRX** [comment]
我觉得可以为了 diversity 而支持 HTTP/3，无论有没有 acceleration，~~反正饼已经画在 release note 中了~~

**Comment by Fangliding** [comment]
I think this cloud be done soon
