### ISSUE TITLE
Why does reality protocol only support x25519 and not other algorithms like p-384?

### ISSUE THREAD

**Issue by xkrmee** [XTLS/Xray-core#3458]
Hello,

I have been exploring the `reality` protocol in `xray-core` and noticed that it only supports the `x25519` algorithm for certificate handling. I am curious about the rationale behind this decision and would like to understand why other algorithms, such as `p-384`, are not supported.

Here are a few specific questions I have:

1. **Technical Limitations**: Are there any technical limitations or challenges that prevent the support of algorithms like `p-384`? If so, could you please elaborate on these limitations?

2. **Security Considerations**: Is the choice of `x25519` based on specific security considerations that make it preferable over other algorithms? 

3. **Performance Impact**: Does supporting only `x25519` provide any performance benefits compared to other algorithms?

4. **Future Support**: Are there any plans to support additional algorithms like `p-384` or others in the future? If not, what are the main reasons for this decision?

Thank you for your time and for the excellent work on `xray-core`. I look forward to your insights on this matter.

Best regards,

**Comment by Fangliding** [comment]
We just chose it, x25519 is only used for internal processing, there are no compatibility issues, supporting other curves is meaningless.
Meanwhile, P-384 is considered a suspicious curve (NIST did not provide any explanation for its parameter selection, but instead provided a random seed)
