### ISSUE TITLE
无法通过xray使用部分SSH软件连接目标主机

### ISSUE THREAD

**Issue by islercn** [XTLS/Xray-core#3459]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我搜索了issues，没有发现已提出的类似问题。

### 版本

1.8.15

### 描述

有一个带密码的上游https代理，我把它转成了透明代理，用iptables转发。在测试中，上网、远程桌面什么的都没问题，但是用xshell之类的软件通过ssh连代理后的服务器，直接没反应（提示连接，然后就卡在那了），且：
1.kill掉xray，起ss的透明代理（其他都不变），秒连（意味着iptables转发没有问题）
2.用putty，秒连；用MobaXterm，连不上，和xshell一样（ss下可连）
3.将这个https代理用goproxy转成socks5，然后xshell下ssh设置这个socks5代理，秒连，但是xray连socks5也不行

防火墙配置：
iptables -t nat -A work -p tcp -m set --match-set worklist dst -j REDIRECT --to-ports 123

抓包的数据上看，除了xshell的包长度超过1500，putty没超，别的地方似乎没有任何区别了。

[也可以看goproxy的这个issue](https://github.com/snail007/goproxy/issues/480)

![1](https://user-images.githubusercontent.com/7038562/165885724-a17493f9-5caf-428b-9b28-a65a9a66db91.png)
![2](https://user-images.githubusercontent.com/7038562/165885728-aba29e04-71d0-4229-84bd-8d58cf123cc3.png)

### 重现方式

把上游https代理转成透明代理，xshell等软件无法通过代理连接目标服务器（SSH）

### 客户端配置

{
    "log": {
        "error": "/root/proxy/xray/error.log",
        "loglevel": "debug"
    },
    "inbounds": [
        {
            "port": 321,
            "protocol": "socks",
            "settings": {
                "udp": true
            }
        },
        {
            "port": 123,
            "protocol": "dokodemo-door",
            "sniffing": {
                "enabled": true,
                "destOverride": ["http", "tls"]
            },
            "settings": {
                "network": "tcp,udp",
                "followRedirect": true
            },
            "streamSettings": {
                "sockopt": {
                    "tproxy": "redirect"
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "http",
            "settings": {
                "servers": [
                    {
                        "address": "proxy.com",
                        "port": 12345,
                        "users": [
                            {
                                "user": "username",
                                "pass": "password"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "security": "tls",
                "tlsSettings": {
                    "allowInsecure": false
                }
            }
        }
    ]
}

### 服务端配置

上级是https代理，无配置

### 客户端日志

只记录到这么多，xxx.com和10.1.1.2对应同一台机器）：

透明代理日志：
2024/06/20 12:38:01 [Debug] [1299392023] proxy/dokodemo: processing connection from: 192.168.11.101:63925
2024/06/20 12:38:01 [Info] [1299392023] proxy/dokodemo: received request for 192.168.11.101:63925
2024/06/20 12:38:02 [Info] [1299392023] app/dispatcher: default route for tcp:10.1.1.2:22

SOCKS代理日志：
2024/06/20 12:25:43 [Info] [1352458977] proxy/socks: TCP Connect request to tcp:xxx.com:22
2024/06/20 12:25:43 [Info] [1352458977] app/dispatcher: default route for tcp:xxx.com:22

### 服务端日志

上级是https代理，无日志

**Comment by Fangliding** [comment]
完整日志

**Comment by islercn** [comment]
使用透明代理尝试连接一次，连不上关掉窗口，然后日志就这么多：

2024/06/21 03:29:35 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:321
2024/06/21 03:29:35 [Info] transport/internet/udp: listening UDP on 0.0.0.0:321
2024/06/21 03:29:35 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:123
2024/06/21 03:29:35 [Info] transport/internet/udp: listening UDP on 0.0.0.0:123
2024/06/21 03:29:35 [Warning] core: Xray 1.8.15 started
2024/06/21 03:29:37 [Info] [2033467147] proxy/dokodemo: received request for 192.168.1.101:59683
2024/06/21 03:29:38 [Info] [2033467147] app/dispatcher: default route for tcp:10.1.1.2:22
2024/06/21 03:29:42 [Info] [2033467147] transport/internet/tcp: dialing TCP to tcp:proxy.com:12345
2024/06/21 03:29:44 [Info] [2033467147] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > context canceled

**Comment by islercn** [comment]
使用socks5尝试一次，也是一样的，只有连接那两行变成了
2024/06/21 03:33:49 [Info] [3665786808] proxy/socks: TCP Connect request to tcp:xxx.com:22
2024/06/21 03:33:49 [Info] [3665786808] app/dispatcher: default route for tcp:xxx.com:22

**Comment by Fangliding** [comment]
如果不使用透明代理 直接用任意门映射一个ssh端口 再尝试连接这个端口 试试能不能用？（理论上处理流程是一样的）

**Comment by islercn** [comment]
就是没有日志才奇怪，xshell窗口直接是卡死的，ctrl+c没用，只能手动关掉标签页，看起来就像发送请求给xray，xray一直没接。

putty的日志是类似的，看上去没有任何的区别，但是可以连上：
2024/06/21 04:46:35 [Debug] app/log: Logger started
2024/06/21 04:46:35 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:321
2024/06/21 04:46:35 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:123
2024/06/21 04:46:35 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:321
2024/06/21 04:46:35 [Info] transport/internet/udp: listening UDP on 0.0.0.0:321
2024/06/21 04:46:35 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:123
2024/06/21 04:46:35 [Info] transport/internet/udp: listening UDP on 0.0.0.0:123
2024/06/21 04:46:35 [Warning] core: Xray 1.8.15 started
2024/06/21 04:46:38 [Debug] [260256817] proxy/dokodemo: processing connection from: 192.168.1.101:53901
2024/06/21 04:46:38 [Info] [260256817] proxy/dokodemo: received request for 192.168.1.101:53901
2024/06/21 04:46:38 [Info] [260256817] app/dispatcher: default route for tcp:10.1.1.2:22
2024/06/21 04:46:38 [Info] [260256817] transport/internet/tcp: dialing TCP to tcp:proxy.com:12345
2024/06/21 04:46:38 [Debug] transport/internet: dialing to tcp:proxy.com:12345

**Comment by Fangliding** [comment]
> 如果不使用透明代理 直接用任意门映射一个ssh端口 再尝试连接这个端口 试试能不能用？（理论上处理流程是一样的）

^

**Comment by islercn** [comment]
如果你是下面这个意思，那日志什么的是一样的，也是xshell不能连，putty可以连

{
  "port": 22222,
  "protocol": "dokodemo-door",
  "settings": {
    "address": "10.1.1.2",
    "port": 22,
    "network": "tcp",
    "timeout": 0,
    "followRedirect": false,
    "userLevel": 0
  }
},

**Comment by Fangliding** [comment]
我自己试了下nc监听端口 写程序发送2000字节的包 可以被任意门正常处理
自己电脑上的xshell也可以正常连 复现不了

**Comment by islercn** [comment]
我用刚发布的1.8.16，同一个配置，直接在windows下运行，然后连接127.0.0.1:22222，还是卡连接

也许和上级代理有关系，但是转透明代理的话gost是没问题的，转socks代理gost和goproxy都没问题，xray都有问题。

于是再换一个配置，直接把22222端口转发到openwrt的SSH端口，这回和上游代理完全没关系了，结果还是卡。。。

{
  "port": 22222,
  "protocol": "dokodemo-door",
  "settings": {
    "address": "192.168.11.1",
    "port": 2345,
    "network": "tcp",
    "timeout": 0,
    "followRedirect": false,
    "userLevel": 0
  },
},

然后我在服务器所在的内网下，用windows的xray把22222转发到一台服务器上，这回也和上游代理没关系，结果还是卡。。。


所以说，我换了客户机，换了目标服务器，换了代理开关，换了客户端软件（xshell，mobaxterm），都是xray不行，gost或者goproxy可以，那么还可以怎么测试证明不是xray的问题呢？

**Comment by islercn** [comment]
增加如下配置无效：

  "sniffing":{
     "enabled":true,
     "metadataOnly":true
  }

**Comment by islercn** [comment]
用v2ray似乎是一样的结果

**Comment by jiangjiangflies** [comment]
同样的问题，软路由透明代理，xshell连不上，但是内网主机可以。搜了好多没找到解决方法

**Comment by RPRX** [comment]
> 同样的问题，软路由透明代理，xshell连不上，但是内网主机可以。搜了好多没找到解决方法

Xray 应该早就不存在不兼容“服务端先发包”的问题了，xshell 用得这么广泛，代理不了的话会有大量报告，所以检查你的配置

**Comment by islercn** [comment]
> > 同样的问题，软路由透明代理，xshell连不上，但是内网主机可以。搜了好多没找到解决方法
> 
> Xray 应该早就不存在不兼容“服务端先发包”的问题了，xshell 用得这么广泛，代理不了的话会有大量报告，所以检查你的配置

不是服务器先发包吧，感觉就是对超过1500的包处理有问题？putty不超1500没问题，xshell超了有问题。如果把xray换成ss也没问题，所以感觉就是xray的问题

**Comment by peaceanddemocracy** [comment]
> > > 同样的问题，软路由透明代理，xshell连不上，但是内网主机可以。搜了好多没找到解决方法
> > 
> > 
> > Xray 应该早就不存在不兼容“服务端先发包”的问题了，xshell 用得这么广泛，代理不了的话会有大量报告，所以检查你的配置
> 
> 不是服务器先发包吧，感觉就是对超过1500的包处理有问题？putty不超1500没问题，xshell超了有问题。如果把xray换成ss也没问题，所以感觉就是xray的问题

@islercn 
情况一样，也碰到了，查了资料：
MTU (最大传输单元) 导致的黑洞效应
这是一个极易被忽视的技术细节。
原理: Xray 在封装数据包时（例如 VLESS + TLS + WS），会增加很多头部开销（Overhead）。如果最终的数据包大小超过了路径上某个路由器的 MTU（通常是 1492 或 1500），数据包会被分片或直接丢弃（如果设置了 DF 标志位）。
SSH 的僵局: SSH 在密钥交换阶段会发送较大的数据包。如果 Xray 的包过大被丢弃，而 ICMP 报错信息（Packet Too Big）又被防火墙拦截，就会发生 PMTU 黑洞。表现为：连接能建立，但一到交换密钥就卡死断开。
MTU 问题通常表现为：小包能通（比如 ping 没问题，简单的 TCP 握手能完成），但大包卡死（比如 SSH 到了密钥交换阶段，或者网页加载了一半卡住）。
以下是针对 Xray 和系统层面的具体解决办法，按操作难度从低到高排列：

方案一：在 Xray 客户端侧强制调小 MTU (最推荐)
不需要动服务器，直接在你的客户端（电脑或路由器）上操作。既然数据包因为“太大”被丢弃，我们就在源头把它切小一点。

操作步骤：

找到你的网卡接口：

Windows: 打开 CMD (管理员)，输入 netsh interface ipv4 show subinterfaces。找到你正在使用的网卡（比如 "Wi-Fi" 或 "Ethernet"）。
Linux/macOS: 终端输入 ifconfig 或 ip addr。
修改 MTU 值：
通常默认是 1500。建议尝试修改为 1350 或 1280（1280 是 IPv6 的最小要求，也是一个非常安全的保守值）。

Windows (管理员 CMD):

cmd
netsh interface ipv4 set subinterface "你的网卡名称" mtu=1350 store=persistent

例如：netsh interface ipv4 set subinterface "Wi-Fi" mtu=1350 store=persistent

macOS:

bash
sudo networksetup -setMTU "Wi-Fi" 1350

Linux:

bash
sudo ip link set dev eth0 mtu 1350  # eth0换成你的网卡名

测试效果： 修改后，重新连接 Xray 并尝试 SSH。如果成功，说明确实是 MTU 问题。你可以尝试慢慢调大这个数值（比如 1400, 1450），找到临界点，或者就维持在 1350。

方案二：利用 TCP MSS Clamping (路由/网关层修复)
如果你是在路由器（OpenWrt/软路由）上运行 Xray，这是最标准的解法。MTU 是物理层的限制，而 MSS (Maximum Segment Size) 是 TCP 层的参数。我们需要告诉 TCP：“别发那么大的包”。

原理： 修改防火墙规则，强制将所有穿过路由器的 TCP 连接的 MSS 值调小，以此留出足够的空间给 Xray 的加密头部。

操作步骤 (以 Linux/OpenWrt 为例)：

在防火墙的 iptables 规则中添加如下命令（通常加在 mangle 表中）：

bash
iptables -t mangle -A POSTROUTING -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu

或者更暴力的直接指定大小（推荐尝试这个）：

bash
iptables -t mangle -A POSTROUTING -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1300

解释：这行命令会拦截所有 TCP 握手包（SYN），强行把 MSS 设置为 1300。这样发送端发出的 TCP 数据包载荷最大只有 1300 字节，加上 Xray 的头部也不会超过 1500，从而避免被丢包。

方案三：Xray 配置层面的优化 (Mux 多路复用)
虽然 Xray 核心配置里没有直接叫 "MTU" 的参数，但开启 Mux (多路复用) 有时会加剧 MTU 问题，而有时关闭它能缓解。

检查配置： 查看你的客户端 config.json 中的 outbounds 部分。
尝试操作： 如果你开启了 mux，请关闭它。
json
"mux": {
  "enabled": false,  // 改为 false 试试
  "concurrency": -1
}

原因：Mux 会把多个 TCP 流塞进一个流里，这会增加协议头部开销，更容易触碰到 MTU 上限。
方案四：排查 ICMP 封锁 (根源分析)
MTU 黑洞产生的根本原因是：当路由器丢弃大包时，会发回一个 ICMP "Fragmentation Needed" (需要分片) 的报错包给发送端。如果你的网络环境（防火墙）把所有 ICMP 包都拦截了，发送端就不知道包被丢了，会一直傻傻地重传大包，导致连接卡死。

验证方法： 在你的电脑上 ping 一个禁止分片的大包。
Windows: ping -f -l 1472 www.baidu.com (1472 + 28头 = 1500)
测试： 逐渐减小 1472 这个数字（比如减到 1400, 1300）。
结果： 找到那个能 Ping 通的最大数值。假设是 1350 能通，1351 不通。那么你的最佳 MTU 设置应该是 1350 + 28 = 1378。
总结建议
最快验证： 先按 方案一，把电脑网卡 MTU 改成 1280。如果 SSH 立刻通了，那就是 MTU 问题无疑。
长期使用： 确认是 MTU 问题后，建议在路由器层面做 MSS Clamping (方案二)，这样局域网内所有设备都受益，不用逐个修改电脑设置。
