### ISSUE TITLE
透明代理下DNS劫持似乎无效

### ISSUE THREAD

**Issue by Arrow-Li** [XTLS/Xray-core#3461]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我搜索了issues，没有发现已提出的类似问题。

### 版本

1.8.4

### 描述

战网服务器在国内会被解析到网易关闭的地址，理论上dns劫持之后应该走vps的解析到国外，不知为何最后还是国内的ip

### 重现方式

```
curl -vvv -X POST https://prod.actual.battle.net
systemd-resolve --flush-caches
systemd-resolve -4 prod.actual.battle.net
```
<img width="668" alt="屏幕截图 2024-06-20 233519" src="https://github.com/XTLS/Xray-core/assets/17962902/824c5cd1-51ec-4866-a581-ed7e1ff8415d">

### 客户端配置

<details><pre><code>{
    "log": {
        "access": "xray/a.log",
        "dnsLog": true,
        "loglevel": "debug"
    },
    "routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "type": "field",
                "port": 53,
                "network": "tcp,udp",
                "outboundTag": "dns1"
            }
        ]
    },
    "inbounds": [
        {
            "tag": "in",
            "port": 11330,
            "protocol": "dokodemo-door",
            "settings": {
                "network": "tcp,udp",
                "followRedirect": true
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls",
                    "quic"
                ]
            },
            "streamSettings": {
                "sockopt": {
                    "tproxy": "tproxy"
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "*",
                        "port": 443,
                        "users": [
                            {
                                "id": "*",
                                "encryption": "none",
                                "flow": "xtls-rprx-vision"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "serverName": "",
                    "allowInsecure": false,
                    "fingerprint": "chrome"
                },
                "sockopt": {
                    "tcpFastOpen": true
                }
            },
            "tag": "proxy"
        },
        {
            "protocol": "freedom",
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "tag": "block"
        },
        {
            "tag": "dns1",
            "protocol": "dns"
        }
    ],
    "dns": {
        "servers": [
            "https://dns.google/dns-query"
        ]
    }
}
</code></pre></details>

### 客户端日志

<details><pre><code>2024/06/20 23:30:29 192.168.50.10:52620 accepted tcp:43.247.78.73:443 [in >> proxy]
2024/06/20 23:31:14 192.168.50.10:51924 accepted tcp:43.247.78.73:443 [in >> proxy]
</code></pre></details>

**Comment by Fangliding** [comment]
你家完整日志两行是吧

**Comment by Arrow-Li** [comment]
> 你家完整日志两行是吧

因为日志上下文和该问题无关，都是正常请求日志
<img width="686" alt="屏幕截图 2024-06-21 001828" src="https://github.com/XTLS/Xray-core/assets/17962902/0e6ad26f-285b-4a1a-ac7b-00b0b36e0214">

PS：不会说话可以不说

**Comment by fs8vsx59h** [comment]
注册表里有老国内战网的东西没删干净，和 xray 无关

**Comment by xqzr** [comment]
> > 你家完整日志两行是吧
> 
> 因为日志上下文和该问题无关，都是正常请求日志 <img alt="屏幕截图 2024-06-21 001828" width="686" src="https://private-user-images.githubusercontent.com/17962902/341489265-0e6ad26f-285b-4a1a-ac7b-00b0b36e0214.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MDA5OTgsIm5iZiI6MTcxODkwMDY5OCwicGF0aCI6Ii8xNzk2MjkwMi8zNDE0ODkyNjUtMGU2YWQyNmYtMjg1Yi00YTFhLWFjN2ItMDBiMGIzNmUwMjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDE2MjQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlOTg5YTg3ZDE3MDYxMDIwYWZlYWQ5Yzk3NDc3ODExOTkzYzYwYmI3OTFkYWQ3MzZjOTQzZjQ5YjY5ZGMxNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nZUm3hc3aiEsFueIi572SJhEuU5-1z9ILWENmkZ_HI4">
> 
> PS：不会说话可以不说

`"loglevel": "debug"` 似乎没有起作用

**Comment by Fangliding** [comment]
debug输出在error日志里 这里看起来是那个a.log里写的access日志 所以并不是完整日志 因为没写error log 所以debug日志输出去console了
自己不读模板然后说我不会说话(

**Comment by om2mo** [comment]
> > 你家完整日志两行是吧
> 
> 因为日志上下文和该问题无关，都是正常请求日志 <img alt="屏幕截图 2024-06-21 001828" width="686" src="https://private-user-images.githubusercontent.com/17962902/341489265-0e6ad26f-285b-4a1a-ac7b-00b0b36e0214.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5ODE5NDgsIm5iZiI6MTcxODk4MTY0OCwicGF0aCI6Ii8xNzk2MjkwMi8zNDE0ODkyNjUtMGU2YWQyNmYtMjg1Yi00YTFhLWFjN2ItMDBiMGIzNmUwMjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDE0NTQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5ZDI5M2M4MzcyYzIzMjUxMDI0NjRiYzZkNTE0YzJlZTE3YzcxY2ZmMzU1ZDFkYmFlYmMxYzFkNTVhZDFkYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UHoR3WYE5uvocJulEwxyI8b0uhcK_L1uKbObyfws5o0">
> 
> PS：不会说话可以不说

你这个是access日志，没有dns解析日志，因为dns根本没有其作用，就算dns改成1.2.3.4也照样运行

**Comment by slinar** [comment]
透明代理需要配置iptables和ip rule,可以把相关配置发出来看看

**Comment by Arrow-Li** [comment]
> 透明代理需要配置iptables和ip rule,可以把相关配置发出来看看

是这个原因，本机的53端口没有进入xray

---

原来的iptables是
```shell
/usr/sbin/iptables -t mangle -A XRAY -d 127.0.0.0/8 -j RETURN
```
修改之后就正常了
```shell
/usr/sbin/iptables -t mangle -A XRAY -d 127.0.0.0/8 -p tcp -j RETURN
/usr/sbin/iptables -t mangle -A XRAY -d 127.0.0.0/8 -p udp ! --dport 53 -j RETURN
```
