### ISSUE TITLE
SplitHTTP 服务端不支持h2c导致无法使用其他软件进行SSL卸载

### ISSUE THREAD

**Issue by ll11l1lIllIl1lll** [XTLS/Xray-core#3464]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我搜索了issues，没有发现已提出的类似问题。

### 版本

1.8.16

### 描述

![Image](https://github.com/XTLS/Xray-core/assets/88377095/b3c8b2a1-aed0-4799-8947-633bf95cfae3)
_SplitHTTP 传输不尊重服务器 TLS ALPN_
相关代码：
https://github.com/XTLS/Xray-core/blob/9432a600e651d1304afec6fceed2a6245eaa4002/transport/internet/splithttp/dialer.go#L134 注册使用 Dial()
https://github.com/XTLS/Xray-core/blob/9432a600e651d1304afec6fceed2a6245eaa4002/transport/internet/splithttp/dialer.go#L159 获取用于发送请求的 HTTP Client
https://github.com/XTLS/Xray-core/blob/9432a600e651d1304afec6fceed2a6245eaa4002/transport/internet/splithttp/dialer.go#L91 如果你使用了 TLS
https://github.com/XTLS/Xray-core/blob/9432a600e651d1304afec6fceed2a6245eaa4002/transport/internet/splithttp/dialer.go#L92 那么使用 h2      

![image](https://github.com/XTLS/Xray-core/assets/88377095/d9dce4a0-58cd-45e0-9c26-306239b323ec)
_即使 SplitHTTP 使用 http/1.1_
相关代码：
https://github.com/XTLS/Xray-core/blob/9432a600e651d1304afec6fceed2a6245eaa4002/transport/internet/splithttp/dialer.go#L171 只是生成 uuid
https://github.com/XTLS/Xray-core/blob/9432a600e651d1304afec6fceed2a6245eaa4002/transport/internet/splithttp/dialer.go#L189 多变的 path

### 重现方式

本地执行这二个配置文件然后 `curl ip-api.com --proxy "http://127.0.0.1:2082" -v --proxytunnel` 或者任何其他的测试

### 客户端配置

<details><pre><code>
{
  "log": {
    "loglevel": "debug"
  },
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "direct"
      }
    ]
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": "2083",
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": "127.0.0.1"
      }
    },
    {
      "listen": "127.0.0.1",
      "port": "2082",
      "protocol": "http"
    }
  ],
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "127.0.0.1",
            "port": 29371,
            "users": [
              {
                "id": "5c4f5f30-2659-413d-b356-eaea53fb0c15"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "splithttp",
        "splithttpSettings": {
          "host": "example.com",
          "path": "/splithttp"
        },
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": true,
          //"maxVersion": "1.2",
          //"masterKeyLog": "./logkey"
        }
      },
      "tag": "proxy"
    },
    {
      "protocol": "freedom",
      "tag": "direct"
    }
  ]
}

</code></pre></details>

### 服务端配置

<details><pre><code>
{
  "log": {
    "loglevel": "debug"
  },
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "ip": [
          "127.0.0.1"
        ],
        "outboundTag": "block"
      }
    ]
  },
  "inbounds": [
    {
      "listen": "0.0.0.0",
      "port": 29371,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "5c4f5f30-2659-413d-b356-eaea53fb0c15",
            "flow": "xtls-rprx-vision"
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "path": "/splithttp",
            "dest": "@splithttp"
          },
          {
            "path": "/ws",
            "dest": "@ws"
          },
          {
            "dest": "@should_not_be_there"
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "tls",
        "tlsSettings": {
          "certificates": [
            {
              "certificateFile": "./cert.cert",
              "keyFile": "./cert.key"
            }
          ],
          "alpn": ["http/1.1"]
        }
      }
    },

    {
      "listen": "@splithttp",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "5c4f5f30-2659-413d-b356-eaea53fb0c15"
          }
        ]
      },
      "streamSettings": {
        "network": "splithttp",
        "splithttpSettings": {
          "host": "example.com",
          "path": "/splithttp"
        },
        "security": "none"
      }
    },

    {
      "listen": "@ws",
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "5c4f5f30-2659-413d-b356-eaea53fb0c15"
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "httpupgrade",
        "httpupgradeSettings": {
          "host": "example.com",
          "path": "/ws"
        },
        "security": "none"
      }
    },

    {
      "listen": "@should_not_be_there",
      "protocol": "dokodemo-door",
      "settings": {
        "address": "1.1.1.1",
        "port": 443
      },
      "streamSettings": {
        "network": "tcp"
      }
    }

  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "tag": "block"
    }
  ]
}

</code></pre></details>

### 客户端日志

<details><pre><code>
Xray 1.8.16 (Xray, Penetrates Everything.) Custom (go1.22.3 linux/amd64)
A unified platform for anti-censorship.
2024/06/21 21:50:27 [Info] infra/conf/serial: Reading config: ./client_local.json
2024/06/21 21:50:27 [Debug] app/log: Logger started
2024/06/21 21:50:27 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:2083
2024/06/21 21:50:27 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:2082
2024/06/21 21:50:27 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:2083
2024/06/21 21:50:27 [Info] transport/internet/udp: listening UDP on 127.0.0.1:2083
2024/06/21 21:50:27 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:2082
2024/06/21 21:50:27 [Warning] core: Xray 1.8.16 started
2024/06/21 21:50:29 [Info] [440856616] proxy/http: request to Method [CONNECT] Host [ip-api.com:80] with URL [//ip-api.com:80]
2024/06/21 21:50:29 [Info] [440856616] app/dispatcher: default route for tcp:ip-api.com:80
2024/06/21 21:50:29 [Info] [440856616] transport/internet/splithttp: dialing splithttp to tcp:127.0.0.1:29371
2024/06/21 21:50:29 127.0.0.1:40834 accepted //ip-api.com:80 [proxy]
2024/06/21 21:50:29 [Debug] transport/internet: dialing to tcp:127.0.0.1:29371
2024/06/21 21:50:29 [Info] [440856616] proxy/vmess/outbound: tunneling request to tcp:ip-api.com:80 via 127.0.0.1:29371
2024/06/21 21:50:30 [Info] transport/internet/splithttp: failed to send download http request > Get "https://example.com/splithttp/1457f92d-13f1-4293-a2d7-207ce7a89f7e": unexpected EOF
2024/06/21 21:50:30 [Info] [440856616] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > common/drain: common/drain: unable to drain connection > transport/internet/splithttp: downResponse failed > proxy/vmess/encoding: Unable to Read Header Len > transport/internet/splithttp: downResponse failed
2024/06/21 21:50:30 [Info] [440856616] app/proxyman/inbound: connection ends > proxy/http: connection ends > io: read/write on closed pipe
2024/06/21 21:50:30 [Info] transport/internet/splithttp: failed to send upload > Post "https://example.com/splithttp/1457f92d-13f1-4293-a2d7-207ce7a89f7e/0": unexpected EOF

</code></pre></details>

### 服务端日志

<details><pre><code>
Xray 1.8.16 (Xray, Penetrates Everything.) Custom (go1.22.3 linux/amd64)
A unified platform for anti-censorship.
2024/06/21 21:50:28 [Info] infra/conf/serial: Reading config: ./server-df+ws.json
2024/06/21 21:50:28 [Debug] app/log: Logger started
2024/06/21 21:50:28 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:29371
2024/06/21 21:50:28 [Debug] app/proxyman/inbound: creating unix domain socket worker on @splithttp
2024/06/21 21:50:28 [Debug] app/proxyman/inbound: creating unix domain socket worker on @ws
2024/06/21 21:50:28 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:29371
2024/06/21 21:50:28 [Info] transport/internet/splithttp: listening unix domain socket(for SH) on @splithttp
2024/06/21 21:50:28 [Info] transport/internet/httpupgrade: listening unix domain socket(for HttpUpgrade) on @ws
2024/06/21 21:50:28 [Warning] core: Xray 1.8.16 started
2024/06/21 21:50:29 [Info] [2676620446] proxy/vless/inbound: firstLen = 64
2024/06/21 21:50:29 [Info] [2676620446] proxy/vless/inbound: fallback starts > proxy/vless/encoding: invalid request version
2024/06/21 21:50:29 [Info] [2676620446] proxy/vless/inbound: realName = 
2024/06/21 21:50:29 [Info] [2676620446] proxy/vless/inbound: realAlpn = http/1.1
2024/06/21 21:50:30 [Warning] [2676620446] app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to dial to @should_not_be_there > common/retry: [dial unix @should_not_be_there: connect: connection refused] > common/retry: all retry attempts failed

2024/06/21 22:01:26 [Info] [1804763553] proxy/vless/inbound: firstLen = 157
2024/06/21 22:01:26 [Info] [1804763553] proxy/vless/inbound: fallback starts > proxy/vless/encoding: invalid request version
2024/06/21 22:01:26 [Info] [1804763553] proxy/vless/inbound: realName = 
2024/06/21 22:01:26 [Info] [1804763553] proxy/vless/inbound: realAlpn = http/1.1
2024/06/21 22:01:26 [Info] [1804763553] proxy/vless/inbound: realPath = /splithttp/c074b6d2-fff8-4360-a0f8-0b513f22059d
2024/06/21 22:01:27 [Warning] [1804763553] app/proxyman/inbound: connection ends > proxy/vless/inbound: failed to dial to @should_not_be_there > common/retry: [dial unix @should_not_be_there: connect: connection refused] > common/retry: all retry attempts failed

</code></pre></details>

**Comment by Fangliding** [comment]
> > Speaking of which, the alpn sent by fallback only has http/1.1?
> 
> I am only learning about this now, but it seems that fallback's path-routing requires HTTP/1.1 and cannot read h2, but at the same time requires TLS. So path fallback cannot be used with splithttp at all.

Damn, this cloud be a problem

**Comment by Fangliding** [comment]
Since we already have reality, expanding the fallback feature is not very necessary

**Comment by KobeArthurScofield** [comment]
VLESS 的 fallback 是解了 TLS 之后直接往下发的，如果进来是 HTTP 1.1 + TLS 那么 fallback 下去的时候就是 HTTP 1.1 ，如果进来是 HTTP/2 的话下去是 h2c

所以尴尬的地方在 SplitHTTP 服务端不支持 h2c，h2c 的连接一过去 SplitHTTP 就“听二万打一筒”了，但是一用了 TLS 之后 SplitHTTP 目前必然会用 HTTP/2 导致卡在这里。

**Comment by KobeArthurScofield** [comment]
@mmmray So I think we can just note that do not use VLESS fallback falling into any SplitHTTP inbounds, until the solution is ready and released.

> I also wonder if grpc works with fallback?

It works. The gRPC and the HTTP/2 transport on the server side both support H2C.

**Comment by Fangliding** [comment]
> > It works. The gRPC and the HTTP/2 transport on the server side both support H2C.
> 
> does `path` routing work with gRPC? my understanding from the documentation is that it requires HTTP/1.1 to parse the path.

fallback can't read h2 path, I checked

**Comment by Fangliding** [comment]
> VLESS 的 fallback 是解了 TLS 之后直接往下发的，如果进来是 HTTP 1.1 + TLS 那么 fallback 下去的时候就是 HTTP 1.1 ，如果进来是 HTTP/2 的话下去是 h2c，不然 REALITY + Vision 还能回落到 HTTP/gRPC 弄出 REALITY 下面 Vision 和 HTTP/gRPC 共存这种玩法就不可行了。
> 
> 所以尴尬的地方在 SplitHTTP 服务端不支持 h2c，h2c 的连接一过去 SplitHTTP 就“听二万打一筒”了，但是一用了 TLS 之后 SplitHTTP 目前必然会用 HTTP/2 导致卡在这里。

确实 就说虽然fallback的alpn有问题但是应该不是出在这

**Comment by Fangliding** [comment]
> I believe h2c could be supported in splithttp server, but it seems that this does not improve the situation significantly, if `path` routing still does not work (and only alpn routing can be used)

This issue may also cause SSL offload issues for some software, and fallback is just one of them

**Comment by Fangliding** [comment]
It only needs to be supported on the server side(like http/1.1 with tls), and the client behavior does not need to be changed

**Comment by KobeArthurScofield** [comment]
如果的确要用 VLESS fallback 来落到 SplitHTTP 的话，目前的临时解决办法是 fallback 回落到 Nginx 或者 Caddy 来接收 fallback 的 h2c，再经由 Nginx/Caddy 以 HTTP1.1 的方式和 SplitHTTP 交换数据。缺点可能就是要多引入一个中间层不直观。

> it's not clear to me how h2c and HTTP/1.1 can be supported simultaneously.

Caddy also support listening HTTP1.1 and H2C simultaneous on the same port, maybe that would help.
