### ISSUE TITLE
使用 TPROXY 透明代理，无法连接

### ISSUE THREAD

**Issue by xiaobo-lab** [XTLS/Xray-core#3467]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我搜索了issues，没有发现已提出的类似问题。

### 版本

Xray 1.8.13 (Xray, Penetrates Everything.) 3120ca4 (go1.22.3 linux/amd64)

### 描述

参考文章https://xtls.github.io/document/level-2/iptables_gid.html中的TPROXY实现方式，流程和配置完全一致，但透明代理无法访问。可以确定不是代理的问题，因为inbounds改成正常的socks5和http代理是可用的。
配置好后运行wget命令结果如下：
>wget https://www.google.com
--2024-06-22 17:45:43--  https://www.google.com/
Resolving www.google.com (www.google.com)... 199.16.158.12, 2001::1
Connecting to www.google.com (www.google.com)|199.16.158.12|:443... connected.
OpenSSL: error:0A000126:SSL routines::unexpected eof while reading
Unable to establish SSL connection.

### 重现方式

系统是ubuntu 24.04。
>uname -a
Linux ubuntu 6.8.0-35-generic #35-Ubuntu SMP PREEMPT_DYNAMIC Mon May 20 15:51:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

已在/etc/passwd中添加了xray_tproxy用户。
>id xray_tproxy
uid=0(root) gid=23333 groups=0(root)

已使用 xray_tproxy 用户身份启动 xray
>sudo -u xray_tproxy xray -c ./config.json &

iptables的配置如下：
ip rule add fwmark 1 table 100
ip route add local 0.0.0.0/0 dev lo table 100

iptables -t mangle -N XRAY
iptables -t mangle -A XRAY -d 127.0.0.1/8 -j RETURN
iptables -t mangle -A XRAY -d 172.17.0.1/16 -j RETURN
iptables -t mangle -A XRAY -d 192.168.31.116/24 -j RETURN
iptables -t mangle -A XRAY -d 224.0.0.0/3 -j RETURN
iptables -t mangle -A XRAY -p tcp -j TPROXY --on-port 10808 --tproxy-mark 1
iptables -t mangle -A XRAY -p udp -j TPROXY --on-port 10808 --tproxy-mark 1
iptables -t mangle -A PREROUTING -j XRAY

iptables -t mangle -N XRAY_MASK
iptables -t mangle -A XRAY_MASK -m owner --gid-owner 23333 -j RETURN
iptables -t mangle -A XRAY_MASK -d 127.0.0.1/8 -j RETURN
iptables -t mangle -A XRAY_MASK -d 172.17.0.1/16 -j RETURN
iptables -t mangle -A XRAY_MASK -d 192.168.31.116/24 -j RETURN
iptables -t mangle -A XRAY_MASK -d 224.0.0.0/3 -j RETURN
iptables -t mangle -A XRAY_MASK -j MARK --set-mark 1
iptables -t mangle -A OUTPUT -p tcp -j XRAY_MASK
iptables -t mangle -A OUTPUT -p udp -j XRAY_MASK

### 客户端配置

<details><pre><code>
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "info"
  },
  "inbounds": [
    {
      "port": 10808,
      "protocol": "dokodemo-door",
      "settings": {
        "network": "tcp,udp",
        "followRedirect": true
      },
      "streamSettings": {
        "sockopt": {
          "tproxy": "tproxy"
        }
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "trojan",
      "settings": {
        "servers": [
          {
            "address": "9jm140.kikwcb.xyz",
            "method": "chacha20",
            "ota": false,
            "password": "cde7bf86-6b32-4dd4-bbc8-cba525a3cfb1",
            "port": 24201,
            "level": 1,
            "flow": ""
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": true,
          "serverName": "0gr4uqmtt8y41hcjsgrzdrc31.ourdvsss.com",
          "show": false
        }
      },
      "mux": {
        "enabled": false,
        "concurrency": -1
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    }
  ],
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "enabled": true
      },
      {
        "id": "5135101515023367852",
        "type": "field",
        "port": "0-65535",
        "outboundTag": "proxy",
        "enabled": true
      }
    ]
  }
}
</code></pre></details>

### 服务端配置

<details><pre><code>
无
</code></pre></details>

### 客户端日志

<details><pre><code>
Xray 1.8.13 (Xray, Penetrates Everything.) 3120ca4 (go1.22.3 linux/amd64)
A unified platform for anti-censorship.
2024/06/22 17:44:11 [Info] infra/conf/serial: Reading config: ./config.json
2024/06/22 17:44:11 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:10808
2024/06/22 17:44:11 [Info] transport/internet/udp: listening UDP on 0.0.0.0:10808
2024/06/22 17:44:11 [Warning] core: Xray 1.8.13 started
2024/06/22 17:45:43 [Info] [1355440748] proxy/dokodemo: received request for 192.168.31.116:52258
2024/06/22 17:45:43 [Info] [1355440748] app/dispatcher: taking detour [proxy] for [tcp:199.16.158.12:443]
2024/06/22 17:45:43 [Info] [1355440748] transport/internet/tcp: dialing TCP to tcp:9jm140.kikwcb.xyz:24201
2024/06/22 17:45:43 192.168.31.116:52258 accepted tcp:199.16.158.12:443 [proxy]
2024/06/22 17:45:43 [Info] [1355440748] proxy/trojan: tunneling request to tcp:199.16.158.12:443 via 9jm140.kikwcb.xyz:24201
2024/06/22 17:45:52 [Info] [1355440748] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > context canceled
</code></pre></details>

### 服务端日志

<details><pre><code>
无
</code></pre></details>

**Comment by xiaobo-lab** [comment]
过一段时间再运行wget会出现以下错误：
>wget https://www.google.com
--2024-06-22 18:33:39--  https://www.google.com/
Resolving www.google.com (www.google.com)... 31.13.94.36, 2001::1
Connecting to www.google.com (www.google.com)|31.13.94.36|:443... connected.
ERROR: no certificate subject alternative name matches
	requested host name ‘www.google.com’.
To connect to www.google.com insecurely, use `--no-check-certificate'.


>wget https://www.google.com --no-check-certificate
--2024-06-22 18:33:51--  https://www.google.com/
Resolving www.google.com (www.google.com)... 31.13.94.36, 2001::1
Connecting to www.google.com (www.google.com)|31.13.94.36|:443... connected.
WARNING: no certificate subject alternative name matches
	requested host name ‘www.google.com’.
HTTP request sent, awaiting response... 400 Bad Request
2024-06-22 18:33:53 ERROR 400: Bad Request.

**Comment by Fangliding** [comment]
古代教程仅供参考

**Comment by woshikedayaa** [comment]
> > Resolving [www.google.com](http://www.google.com) ([www.google.com](http://www.google.com))... 31.13.94.36, 2001::1
> > Connecting to [www.google.com](http://www.google.com) ([www.google.com)|31.13.94.36|:443]

31.13.94.36
DNS 被污染了吧 解析到 facebook的ip段去了咋还 

配置没打码，当然不排除有可能你是乱填的

**Comment by xiaobo-lab** [comment]
> 古代教程仅供参考

请问哪里有最新的教程可以参考吗？

**Comment by xiaobo-lab** [comment]
> > > Resolving [www.google.com](http://www.google.com) ([www.google.com](http://www.google.com))... 31.13.94.36, 2001::1
> > > Connecting to [www.google.com](http://www.google.com) ([www.google.com)|31.13.94.36|:443]
> 
> 31.13.94.36 DNS 被污染了吧 解析到 facebook的ip段去了咋还
> 
> 配置没打码，当然不排除有可能你是乱填的

DNS 污染应该怎么解决呀？

**Comment by woshikedayaa** [comment]
阅读文档，参考 DNS 模块 应该把对国外域名的解析交给 国外的VPS去解析

**Comment by xiaobo-lab** [comment]
> 阅读文档，参考 DNS 模块 应该把对国外域名的解析交给 国外的VPS去解析

可是，就算dns没问题，也访问不了，因为如果直接wget ip会出现以下错误：
wget https://199.16.158.12
--2024-06-22 19:57:50--  https://199.16.158.12/
Connecting to 199.16.158.12:443... connected.
OpenSSL: error:0A000126:SSL routines::unexpected eof while reading
Unable to establish SSL connection.

**Comment by xiaobo-lab** [comment]
> 古代教程仅供参考

可以帮我看看，我哪里配置的不对吗？

**Comment by xiaobo-lab** [comment]
@woshikedayaa  @Fangliding  可以帮我看看，我哪里配置的不对吗？

**Comment by xiaobo-lab** [comment]
已解决

**Comment by Fangliding** [comment]
唔 DNS
#form end user

**Comment by someonewating** [comment]
> @woshikedayaa @Fangliding 可以帮我看看，我哪里配置的不对吗？

您好，可以分享下您的解决方案吗？谢谢。
