### ISSUE TITLE
Xtls-orgin pictures sometimes fail to load

### ISSUE THREAD

**Issue by OneHappyForever** [XTLS/Xray-core#347]
Problem: when using xtls, youtube thumbnails sometimes don't load. Same with reddit thumbnails. Web pages and youtube videos play just fine though.

Maybe some plain text it's not being encrypted correctly?

Server: Xray 1.30.0

Client: v2rayn, shadowrocket, Qv2ray all have this issue

ISP: multiple ISPs have this issue

This leads me to think it's probably a protocol issue.

**Comment by rprx** [comment]
Use direct or splice.
