### ISSUE TITLE
reality连通性问题

### ISSUE THREAD

**Issue by jinbasex** [XTLS/Xray-core#3472]
服务端配置

  "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "uuid", // 必填，执行 ./xray uuid 生成，或 1-30 字节的字符串
                        "flow": "xtls-rprx-vision" // 选填，若有，客户端必须启用 XTLS
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "tcp",
                "security": "reality",
                "realitySettings": {
                    "show": true, // 选填，若为 true，输出调试信息
                    "dest": "player.live-video.net:443", // 必填，格式同 VLESS fallbacks 的 dest
                    "xver": 0, // 选填，格式同 VLESS fallbacks 的 xver
                    "serverNames": [ // 必填，客户端可用的 serverName 列表，暂不支持 * 通配符
                        "player.live-video.net"
                    ],
                    "privateKey": "密匙", // 必填，执行 ./xray x25519 生成
                    "minClientVer": "", // 选填，客户端 Xray 最低版本，格式为 x.y.z
                    "maxClientVer": "", // 选填，客户端 Xray 最高版本，格式为 x.y.z
                    "maxTimeDiff": 0, // 选填，允许的最大时间差，单位为毫秒
                    "shortIds": [ // 必填，客户端可用的 shortId 列表，可用于区分不同的客户端
                        "aced5566", // 若有此项，客户端 shortId 可为空
                        "acef1234" // 0 到 f，长度为 2 的倍数，长度上限为 16
                    ]
                }
            }
        }
    ]
}

客户端clash verge rev V1.6.4
- name: "vless"
  type: vless
  server: 服务器地址/iplc转发地址
  port: 对应端口
  udp: true
  uuid: 对应uuid
  flow: xtls-rprx-vision
  tls: true
  packet-encoding: xudp
  servername: player.live-video.net
  client-fingerprint: chrome
  skip-cert-verify: true
  reality-opts:
    public-key: 私钥对应的公钥
    short-id: aced5566
  network: tcp

服务端日志

Jun 24 09:46:05 主机名 xray[518578]: REALITY remoteAddr: 访问地址：端口        hs.c.ClientVer: [1 8 2]
Jun 24 09:46:05 主机名 xray[518578]: REALITY remoteAddr: 访问地址：端口       hs.c.ClientTime: 2024-06-24 09:46:10 +0800 HKT
Jun 24 09:46:05 主机名 xray[518578]: REALITY remoteAddr: 访问地址：端口        hs.c.ClientShortId: [172 237 85 102 0 0 0 0]
Jun 24 09:46:05 主机名 xray[518578]: REALITY remoteAddr: 访问地址：端口        hs.c.conn == conn: true
Jun 24 09:46:05 主机名 xray[518578]: REALITY remoteAddr: 访问地址：端口        len(s2cSaved): 4284        Server Hello: 127
Jun 24 09:46:05 主机名 xray[518578]: REALITY remoteAddr: 访问地址：端口        len(s2cSaved): 4157        Change Cipher Spec: 6
Jun 24 09:46:05 主机名 xray[518578]: REALITY remoteAddr: 访问地址：端口        len(s2cSaved): 4151        Encrypted Extensions: 32
Jun 24 09:46:05 主机名 xray[518578]: REALITY remoteAddr: 访问地址：端口        len(s2cSaved): 4119        Certificate: 5469
Jun 24 09:46:05 主机名 xray[518578]: REALITY remoteAddr: 访问地址：端口        len(s2cSaved): 5813        Certificate: 5469
Jun 24 09:46:05 主机名 xray[518578]: REALITY remoteAddr: 访问地址：端口       len(s2cSaved): 344        Certificate Verify: 286
Jun 24 09:46:05 主机名 xray[518578]: REALITY remoteAddr: 访问地址：端口        len(s2cSaved): 58        Finished: 58
Jun 24 09:46:05 主机名 xray[518578]: REALITY remoteAddr: 访问地址：端口       hs.handshake() err: <nil>
Jun 24 09:46:05 主机名 xray[518578]: REALITY remoteAddr: 访问地址：端口       hs.readClientFinished() err: <nil>
Jun 24 09:46:05 主机名 xray[518578]: REALITY remoteAddr: 访问地址：端口        hs.c.handshakeStatus: true

想请教一下是否我配置有误还是什么问题 哪怕用iplc转发也是连不上

**Comment by Fangliding** [comment]
请用xray客户端测试 我们不处理clash问题

**Comment by jinbasex** [comment]
> 请用xray客户端测试 我们不处理clash问题

也就是说这是单纯clash 的问题？ 我的配置没有任何问题？   但我用V2rayN也是这样一个情况。

**Comment by Fangliding** [comment]
我看了下那个dest是http/1.1 不支持h2

**Comment by jinbasex** [comment]
> 我看了下那个dest是http/1.1 不支持h2

那我明白了 感谢您的答疑解惑 谢谢
