### ISSUE TITLE
app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination

### ISSUE THREAD

**Issue by TommyYOyoyo** [XTLS/Xray-core#3481]
I'm using reality-ezpz one-click script to generate configs for my personal VPS in order to bypass the GFW. However, when I arrived to China, I couldn't connect to any website when I enable the connection. Upon examining the logs of V2rayXS, I noticed that this error was constantly producing: 
`app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp myIP:myPort: i/o timeout dial tcp  myIP:myPort: operation was canceled] > common/retry: all retry attempts failed`.

What might be causing this issue? 

### What I tried
- Changing the port from 443 to 80

**My VPS**: Google Cloud VM
### My server-side configs from reality-ezpz:
Core: xray  (v1.8.4)                                        
Server Address: <myIP>                        
Domain SNI: www.google.com
Port: 80
Transport: tcp
Security: reality
Safenet: OFF
WARP: ON
WARP License: <License> 
Telegram Bot: OFF   
Telegram Bot Token: none
Telegram Bot Admins: none

### My current client config.json:
```
{
  "routing" : {
    "name" : "all_to_main",
    "domainStrategy" : "AsIs",
    "rules" : [
      {
        "type" : "field",
        "outboundTag" : "RealityEZPZ",
        "port" : "0-65535"
      }
    ]
  },
  "inbounds" : [
    {
      "listen" : "127.0.0.1",
      "protocol" : "socks",
      "settings" : {
        "ip" : "127.0.0.1",
        "auth" : "noauth",
        "udp" : false
      },
      "tag" : "socksinbound",
      "port" : 1081
    },
    {
      "listen" : "127.0.0.1",
      "protocol" : "http",
      "settings" : {
        "timeout" : 0
      },
      "tag" : "httpinbound",
      "port" : 8001
    }
  ],
  "dns" : {
    "servers" : [
      "localhost"
    ]
  },
  "log" : {
    "error" : "\/var\/folders\/51\/1pgrz5295dg1b15vht_4rft00000gn\/T\/cenmrev.v2rayx.log\/error.log",
    "loglevel" : "warning",
    "access" : "\/var\/folders\/51\/1pgrz5295dg1b15vht_4rft00000gn\/T\/cenmrev.v2rayx.log\/access.log"
  },
  "outbounds" : [
    {
      "sendThrough" : "0.0.0.0",
      "mux" : {
        "enabled" : false,
        "concurrency" : 8
      },
      "protocol" : "vless",
      "settings" : {
        "vnext" : [
          {
            "address" : "myIP",
            "users" : [
              {
                "flow" : "xtls-rprx-vision",
                "id" : "1db09fb8-23c5-4731-9aa9-f374c790b6cc",
                "alterId" : 64,
                "security" : "none",
                "level" : 0,
                "encryption" : "none"
              }
            ],
            "port" : 80
          }
        ]
      },
      "tag" : "RealityEZPZ",
      "streamSettings" : {
        "sockopt" : {

        },
        "tlsSettings" : {
          "allowInsecure" : false,
          "alpn" : [
            "http\/1.1"
          ],
          "serverName" : "server.cc",
          "allowInsecureCiphers" : false
        },
        "wsSettings" : {
          "path" : "",
          "headers" : {

          }
        },
        "tcpSettings" : {
          "header" : {
            "type" : "none"
          }
        },
        "kcpSettings" : {
          "header" : {
            "type" : "none"
          },
          "mtu" : 1350,
          "congestion" : false,
          "tti" : 20,
          "uplinkCapacity" : 5,
          "writeBufferSize" : 1,
          "readBufferSize" : 1,
          "seed" : "",
          "downlinkCapacity" : 20
        },
        "httpSettings" : {
          "path" : "",
          "host" : [
            ""
          ]
        },
        "security" : "reality",
        "grpcSettings" : {
          "multiMode" : false
        },
        "quicSettings" : {
          "key" : "",
          "header" : {
            "type" : "none"
          },
          "security" : "none"
        },
        "realitySettings" : {
          "allowInsecureCiphers" : false,
          "allowInsecure" : false,
          "fingerprint" : "chrome",
          "serverName" : "www.google.com",
          "spiderX" : "",
          "alpn" : "h2,http\/1.1",
          "publicKey" : "9MxEqQ2BovCAZowoE8o8qruCWDGeI8ZzL9FLf0kngm0",
          "shortId" : "29d8da22cd1ddf9c"
        },
        "network" : "tcp",
        "xtlsSettings" : {
          "serverName" : "server.cc",
          "alpn" : [
            "http\/1.1"
          ],
          "allowInsecure" : false
        }
      }
    }
  ]
}
```

Thank you very much!

**Comment by Fangliding** [comment]
If it can be used outside of China, it is likely that your server has been blocked by GFW

**Comment by TommyYOyoyo** [comment]
> If it can be used outside of China, it is likely that your server has been blocked by GFW

I'm using WARP+ to hide the server address, which hides my server's address, also I can ssh into my server here in China. So it shouldn't be blocked, no?

**Comment by Fangliding** [comment]
Warp has nothing to do with blocking
It is common to ban one port, so SSH can still be available

**Comment by TommyYOyoyo** [comment]
> Warp has nothing to do with blocking It is common to ban one port, so SSH can still be available

Thanks for your answer. Is it only the port blocked (I need to continue trying others) or the IP address as well? I tried changing my server's IP address and port but it is still giving me the same results... Is there another way to connect?

**Comment by TommyYOyoyo** [comment]
Update: I finally got it working when I changed my SNI domain. Thank you for your helps.

**Comment by Fangliding** [comment]
google.com...

**Comment by TommyYOyoyo** [comment]
Yep, that was the default SNI, I changed it to swisscows.ch and now it is working like a charm!

**Comment by Fangliding** [comment]
because google is blocked in china(

**Comment by TommyYOyoyo** [comment]
You're right, I didn't think about that when I created my server.

**Comment by AUTORUN979** [comment]
How to do that please
