### ISSUE TITLE
Is it possible to compile Xray without some protocols?

### ISSUE THREAD

**Issue by a4gg** [XTLS/Xray-core#3483]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.

### Version

1.8.16

### Description

Many thanks to people developing and maintaining Xray which is vital for people abused by GFW.

Is it possible to compile Xray without some protocols like shadowsocks, trojan and wireguard? These are great protocols but I never use them with Xray.
It would be great to turn off some features selectively when compiling, like `./configure --without-some-feature`. But for now I'd appreciate it if someone tells me how to comment out some of the source code and compile.

Thank you and have a nice weekend.

### Reproduction Method

N/A

### Client config

N/A

### Server config

N/A

### Client log

N/A

### Server log

N/A

**Comment by Fangliding** [comment]
Similar designs are being adopted in sing box, it's a good idea. However, it needs to be designed from the beginning when building the project, and now it requires a lot of refactoring, which is currently unlikely

**Comment by Fangliding** [comment]
Btw, If you are familiar with golang, it is not difficult to remove some dependencies and compile.(((

**Comment by a4gg** [comment]
Thank you for the quick reply. 

I understand there are historical problems in many projects and refactoring them is beyond a person's ability.
I have zero knowledge of golang, but it should be massively easier to comment out some parts of source code than to compose and maintain this great Xray. I will try to do it myself after learning the ABC of golang.

Thank you.
