### ISSUE TITLE
load balancing for wireguard outbounds

### ISSUE THREAD

**Issue by Gholamreza29** [XTLS/Xray-core#3488]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.

### Version

1.8.10

### Description

I have three WireGuard configurations that I have used as outbounds. I have tried using the LeastPing load balancer, but it seems my traffic does not go through WireGuard and goes directly instead. 

### Reproduction Method

"balancers": [
      {
        "tag": "windsbal",
        "selector": [
          "man1",
          "down2",
          "disp1"
        ],
        "strategy": {
          "type": "leastPing"
        }
      }
    ]
  },
  "stats": {},
  "observatory": {
    "subjectSelector": [
      "windsbal"
    ],
    "probeURL": "http://www.google.com/gen_204",
    "probeInterval": "10m",
    "enableConcurrency": true
  }
}

### Client config

<details><pre><code>
"balancers": [
      {
        "tag": "windsbal",
        "selector": [
          "manchester",
          "custard",
          "biscutis"
        ],
        "strategy": {
          "type": "leastPing"
        }
      }
    ]
  },
  "stats": {},
  "observatory": {
    "subjectSelector": [
      "windsbal"
    ],
    "probeURL": "http://www.google.com/gen_204",
    "probeInterval": "10m",
    "enableConcurrency": true
  }
}
</code></pre></details>

### Server config

<details><pre><code>
"balancers": [
      {
        "tag": "windsbal",
        "selector": [
          "manchester",
          "custard",
          "biscutis"
        ],
        "strategy": {
          "type": "leastPing"
        }
      }
    ]
  },
  "stats": {},
  "observatory": {
    "subjectSelector": [
      "windsbal"
    ],
    "probeURL": "http://www.google.com/gen_204",
    "probeInterval": "10m",
    "enableConcurrency": true
  }
}
</code></pre></details>

### Client log

<details><pre><code>
nothing
</code></pre></details>

### Server log

<details><pre><code>
nothing
</code></pre></details>

**Comment by Fangliding** [comment]
> I provided the complete config and logs

**Comment by Gholamreza29** [comment]
There is nothing abnormal in my logs and configs. The balancer works correctly when I'm using Round-robin but, when I'm changing it to Leastping it is not working.

**Comment by RPRX** [comment]
> 1.8.10

看到就头痛，@Fangliding issue 模板加一个必须针对最新版，但可以测试旧版有无问题

**Comment by Fangliding** [comment]
那我把version去掉加一个打钩的好了

**Comment by MrMalekfar** [comment]
same issue.
