### ISSUE TITLE
SplitHTTP now does not support fallbacks.

### ISSUE THREAD

**Issue by fscarmen** [XTLS/Xray-core#3493]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.

### Version

v1.8.16

### Description

According to @Fangliding reference, fallback only wrote the code to read the http/1.1 path not the h2 one.

### Reproduction Method

```
{
    "inbounds": [
        {
            "listen": "0.0.0.0",
            "port": 8080,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "9f3b5e3a-d5fc-4969-9170-6da4c8877660",
                        "flow": "xtls-rprx-vision"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "path": "/split",
                        "dest": 3001
                    }
                ]
            }
        },
        {
            "port": 3001,
            "listen": "127.0.0.1",
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "9f3b5e3a-d5fc-4969-9170-6da4c8877660"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "splithttp",
                "splithttpSettings": {
                    "path": "/split"
                }
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls",
                    "quic"
                ],
                "metadataOnly": false
            }
        }
    ]
}
```

### Client config

<details><pre><code>
v2rayN
</code></pre></details>

### Server config

<details><pre><code>
{
    "inbounds": [
        {
            "listen": "0.0.0.0",
            "port": 8080,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "9f3b5e3a-d5fc-4969-9170-6da4c8877660",
                        "flow": "xtls-rprx-vision"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "path": "/split",
                        "dest": 3001
                    }
                ]
            }
        },
        {
            "port": 3001,
            "listen": "127.0.0.1",
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "9f3b5e3a-d5fc-4969-9170-6da4c8877660"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "splithttp",
                "splithttpSettings": {
                    "path": "/split"
                }
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls",
                    "quic"
                ],
                "metadataOnly": false
            }
        }
    ]
}
</code></pre></details>

### Client log

<details><pre><code>
...
</code></pre></details>

### Server log

<details><pre><code>
...
</code></pre></details>

**Comment by Fangliding** [comment]
fallback只支持h1的path 毕竟以前都是用来转ws的也就问题不大 但是splithttp可能用到h2
有一个问题是 一个h2连接由于其多路复用的属性 里面可能包含不止一个path tcp连接又只有一条 所以估计只能读第一个path就分流了
再就是处理h2帧的问题

**Comment by Fangliding** [comment]
In fact, it only reads a few bytes of the request and forwards it, should has nothing to do with other HTTP feature

> **EDIT: Just to be clear, the workaround is to set `"alpn": "http/1.1"` on the client**
> 
> > One problem is that an h2 connection may contain more than one path due to its multiplexing attribute
> 
> ~I do wonder if fallback works with HTTP/1.1 keepalive...~

**Comment by RPRX** [comment]
试试 https://github.com/XTLS/Xray-core/pull/3505#issuecomment-2222234902
