### ISSUE TITLE
QUIC problem

### ISSUE THREAD

**Issue by OghabTeam** [XTLS/Xray-core#3494]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.

### Version

1.8.16

### Description

I use the panel-to-panel reverse tunnel method and the vmess QUIC protocol, and the problem I have is that the xray script on the first server restarts every one or two minutes and the vpn is disconnected. Please solve the problem, we need this protocol.

### Reproduction Method

none

### Client config

<details><pre><code>

</code></pre></details>

### Server config

<details><pre><code>

</code></pre></details>

### Client log

<details><pre><code>

</code></pre></details>

### Server log

<details><pre><code>

</code></pre></details>

**Comment by OghabTeam** [comment]
On other protocols like tcp or grpc there is no problem and it works well!

**Comment by Fangliding** [comment]
No config, no log, just some words....

**Comment by OghabTeam** [comment]
Here are the tunnel settings:
[
  {
    "tag": "prx4",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "2001:470:1f10:e1f::2",
          "port": 8080,
          "users": [
            {
              "id": "ec9fcbf3-d88a-4439-9e8e-b4c65644b6a9"
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "quic",
      "security": "none",
      "quicSettings": {
        "security": "chacha20-poly1305",
        "key": "6YdMTBZPEH",
        "header": {
          "type": "wireguard"
        }
      },
      "sockopt": {
        "dialerProxy": "",
        "tcpFastOpen": true,
        "tcpKeepAliveInterval": 0,
        "tcpMptcp": true,
        "tcpNoDelay": false
      }
    }
  },
  {
    "tag": "block",
    "protocol": "blackhole",
    "settings": {
      "response": {
        "type": "http"
      }
    }
  },
  {
    "tag": "direct",
    "protocol": "freedom",
    "settings": {}
  }
]

**Comment by OghabTeam** [comment]
> No config, no log, just some words....

Hello? can you help please Will you fix this problem in the next update?
