### ISSUE TITLE
Reality 偷域名的问题

### ISSUE THREAD

**Issue by hanxin-menglei** [XTLS/Xray-core#3497]
如果我用reality偷了某个域名xxx.xxx.com，然后用这个节点在短期内进行了大流量下载或者发送过很多次请求，那么xxx.xxx.com的服务器会检测到异常行为吗？

**Comment by Fangliding** [comment]
会知道有很多个来自你服务器的握手

**Comment by yaoyao-moe** [comment]
会，并且可能给你加入blacklist，但是有可能只是返回403（
