### ISSUE TITLE
域名解析宽匹配问题

### ISSUE THREAD

**Issue by harvey-git** [XTLS/Xray-core#3498]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [ ] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了issues，没有发现已提出的类似问题。

### 版本

1.8.6-最新

### 描述

xray部署在openwrt（本机透明代理也有类似结果）上，ip4/v6双栈通过nftables透明代理,dns被规则拦截到透明代理的链里转发到xray的input端口，刚刚启动相关配置能正常运行约至少两个小时，然后在在大约3小时以后，dns开始随机不再解析类似xxx.github.com,xxx.google.com，repo.jellyfin.org，xxxx.aliyun.com这样的域名，nslookup会直接返回空解析结果。
然后导致包括但不限于天猫精灵，apt update之类需要访问这些二级域名的应用异常不工作，
[03_dns.json](https://github.com/user-attachments/files/16066108/03_dns.json)
[02_routing.json](https://github.com/user-attachments/files/16066110/02_routing.json)

### 重现方式

出现上诉故障后，简单重启动xray服务，故障就能消失，然后约几个小时候后再次出现。
此外如果chrome系浏览器通过 [SwitchyOmega]插件代理到xray的socks端口则全程不会出现故障。

### 客户端配置

rule
<details><pre><code>
{
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "domainMatcher": "mph",
    "balancers": [
      {
        "tag": "apric",
        "selector": [
          "bw2",
          "bw3",
          "bw1",
          "jp1",
          "jp2"
        ]
      }
    ],
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "metrics_in"
        ],
        "outboundTag": "metrics_out"
      },
      {
        "type": "field",
        "protocol": [
          "bittorrent"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "inboundTag": [
          "transparent"
        ],
        "port": 123,
        "network": "udp"
      },
      {
        "type": "field",
        "outboundTag": "dns-out",
        "inboundTag": [
          "dns-in",
          "go-apric",
          "socks5",
          "transparent"
        ],
        "port": 53
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "inboundTag": [
          "go-apric",
          "socks5"
        ],
        "ip": [
          "10.0.0.0/8",
          "114.114.114.114",
          "119.29.29.29",
          "119.6.6.6",
          "172.16.0.0/12",
          "192.168.0.0/16",
          "223.5.5.5",

          "geoip:cn",
          "geoip:private"
        ]
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "10.0.0.0/8",
          "100.64.0.0/10",
          "103.10.124.0/23",
          "103.143.19.140",
          "103.21.244.0/22",
          "103.22.200.0/22",
          "103.28.54.0/24",
          "103.31.4.0/22",
          "104.16.0.0/13",
          "104.24.0.0/14",
          "108.162.192.0/18",
          "114.114.114.114",
          "119.29.29.29",
          "119.6.6.6",
          "131.0.72.0/22",
          "141.101.64.0/18",
          "146.66.152.0/24",
          "146.66.155.0/24",
          "153.254.86.0/24",
          "155.133.224.0/22",
          "155.133.230.0/24",
          "155.133.232.0/23",
          "155.133.234.0/24",
          "155.133.236.0/22",
          "155.133.240.0/23",
          "155.133.244.0/23",
          "155.133.246.0/24",
          "155.133.248.0/21",
          "162.158.0.0/15",
          "162.254.192.0/21",
          "169.254.0.0/16",
          "172.16.0.0/12",
          "173.245.48.0/20",
          "185.25.182.0/23",
          "188.114.96.0/20",
          "190.217.32.0/22",
          "190.93.240.0/20",
          "192.168.0.0/16",
          "192.69.96.0/22",
          "197.234.240.0/22",
          "198.41.128.0/17",
          "205.185.194.0/24",
          "205.196.6.0/24",
          "208.64.200.0/22",
          "208.78.164.0/22",
          "223.5.5.5",
          "224.0.0.0/4",
          "45.121.184.0/24",
          "61.128.128.68",
          "geoip:cn",
          "geoip:private"
        ]
      },
      {
        "type": "field",
        "outboundTag": "bw1",
        "inboundTag": [
          "gametunnel"
        ]
      },
      {
        "type": "field",
        "balancerTag": "apric",
        "inboundTag": [
          "go-apric",
          "socks5"
        ]
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": [
          "domain:115.com",
          "domain:8686c.com",
          "domain:alicdn.com",
          "domain:bscstorage.net",
          "domain:clngaa.com",
          "domain:eccdnx.com",
          "domain:jd.com",
          "domain:microsoft.com",
          "domain:ntp.org",
          "domain:pinyuncloud.com",
          "domain:pphimalayanrt.com",
          "domain:yifile.com",
          "domain:steamchina.com",
          "domain:8686c.com",
          "domain:bscstorage.net",
          "domain:clngaa.com",
          "domain:eccdnx.com",
          "domain:ksyna.com",
          "domain:pinyuncloud.com",
          "domain:pphimalayanrt.com",
          "domain:steamchina.com",
          "domain:steamcontent.com",
          "domain:steampowered.com",
          "domain:steamserver.net",
          "domain:steamusercontent.com",
          "domain:tnkjmec.com",
          "domain:wmsj.cn",
          "domain:wmsjsteam.com",
          "domain:tnkjmec.com",
          "domain:wmsj.cn",
          "geosite:category-games@cn",
          "geosite:cn",
          "geosite:tld-cn",
          "keyword:115",
          "regexp:\\.ali.*\\.com$",
          "regexp:\\.jd.*\\.com$"
        ]
      },
      {
        "type": "field",
        "balancerTag": "apric",
        "ip": [
          "1.1.1.1",
          "8.8.8.8",
          "68.183.204.194",
          "geoip:facebook",
          "geoip:google",
          "geoip:telegram",
          "geoip:twitter"
        ]
      },
      {
        "type": "field",
        "balancerTag": "apric",
        "domain": [
          "domain:18comic.vip",
          "domain:18lib.com",
          "domain:23img.com",
          "domain:64clouds.com",
          "domain:6park.com",
          "domain:7jt8y.app",
          "domain:7livq.app",
          "domain:91porn.com",
          "domain:91porny.com",
          "domain:appsflyer.com",
          "domain:blr844.com",
          "domain:chatgpt.com",
          "domain:chenyudong.com",
          "domain:cloud.unity3d.com",
          "domain:cool18.com",
          "domain:dmm.co.jp",
          "domain:facebook.com",
          "domain:fonts.googleapis.com",
          "domain:getdroidtips.com",
          "domain:gedecomix.com",
          "domain:ggpht.com",
          "domain:gifyu.com",
          "domain:git.io",
          "domain:github.com",
          "domain:github.io",
          "domain:githubusercontent.com",
          "domain:githubassets.com",
          "domain:gnome-look.org",
          "domain:im.ge",
          "domain:google-analytics.com",
          "domain:google.com.hk",
          "domain:googleapis.com",
          "domain:googletagmanager.com",
          "domain:googleusercontent.com",
          "domain:googlevideo.com",
          "domain:greasyfork.org",
          "domain:gstatic.com",
          "domain:hellhades.com",
          "domain:i-m.dev",
          "domain:imgbox.com",
          "domain:imgur.com",
          "domain:internal.unity3d.com",
          "domain:javbus.com",
          "domain:javdb.com",
          "domain:javstore.net",
          "domain:jdbstatic.com",
          "domain:jellyfin.org",
          "domain:jsdelivr.net",
          "domain:name.com",
          "domain:oaistatic.com",
          "domain:openai.com",
          "domain:openmediavault.org",
          "domain:p2wt.com",
          "domain:plarium.com",
          "domain:plrm.zone",
          "domain:policyrouting.org",
          "domain:pornhub.com",
          "domain:porncomixonline.net",
          "domain:proxmox.com",
          "domain:rootmygalaxy.net",
          "domain:softs.im",
          "domain:sourceforge.net",
          "domain:stackexchange.com",
          "domain:stackoverflow.com",
          "domain:superuser.com",
          "domain:syncthing.net",
          "domain:t66y.com",
          "domain:tailscale.com",
          "domain:tampermonkey.net",
          "domain:teamcode.com",
          "domain:twitter.com",
          "domain:unity3d.com",
          "domain:v2ex.com",
          "domain:v2fly.org",
          "domain:wzip.date",
          "domain:wzip.download",
          "domain:x-plarium.com",
          "domain:xn--qiq612bj6tu9uj4fepk.com",
          "domain:xwbo.com",
          "domain:youtube.com",
          "domain:ytimg.com",
          "domain:zerotier.com",
          "geosite:geolocation-!cn",
          "geosite:gfw",
          "geosite:github",
          "geosite:greatfire",
          "keyword:bandwagonhost",
          "keyword:btsow",
          "keyword:bwg",
          "keyword:cdp.cloud",
          "keyword:fwupd",
          "keyword:gg",
          "keyword:github",
          "keyword:goog",
          "keyword:google",
          "keyword:gpt",
          "keyword:hell",
          "keyword:img.",
          "keyword:jav",
          "keyword:jellyfin",
          "keyword:loonlog",
          "keyword:openai",
          "keyword:plar",
          "keyword:plrm",
          "keyword:top",
          "keyword:twrp",
          "keyword:winehq"
        ]
      },
      {
        "type": "field",
        "outboundTag": "blocked",
        "domain": [
          "geosite:category-ads"
        ]
      },
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api"
      }
    ]
  }
}
</code></pre></details>

dns
<details><pre><code>
{
  "dns": {
    "queryStrategy": "UseIP",
    "hosts": {
      "domain:v2fly.org": "www.vicemc.net",
      "domain:wikipedia.org": "www.wikimedia.org",
      "domain:shadowsocks.org": "electronicsrealm.com",
      "domain:google.com.hk": "google.com",
      "dns.google": "8.8.8.8",
      "cdn-ali.content.steamchina.com": "2409:8c20:bea1:2::249c:bb29",
      "xz.pphimalayanrt.com": "2409:8c20:bea1:2::249c:bb29",
      "lv.queniujq.cn": "2409:8c20:bea1:2::249c:bb29",
      "alibaba.cdn.steampipe.steamcontent.com": "2409:8c20:bea1:2::249c:bb29",
      "upos-hz-mirrorakam.akamaized.net": "223.119.248.25",
      "steamusercontent-a.akamaihd.net": "223.119.248.25"
    },
    "servers": [
        "https://1.1.1.1/dns-query",
      {
        "address": "223.5.5.5",
        "port": 53,
        "domains": [
          "geosite:tld-cn",
          "geosite:cn",
          "geosite:category-games@cn",
          "domain:ntp.org",
          "domain:115.com",
          "domain:alicdn.com",
          "domain:microsoft.com",
          "domain:yifile.com",
          "domain:8686c.com",
          "domain:bscstorage.net",
          "domain:clngaa.com",
          "domain:eccdnx.com",
          "domain:pinyuncloud.com",
          "domain:pphimalayanrt.com",
          "domain:steamchina.com",
          "domain:tnkjmec.com",
          "domain:wmsj.cn",
          "keyword:115",
          "domain:jd.com",
          "regexp:\\.ali.*\\.com$",
          "regexp:\\.jd.*\\.com$"
        ],
        "expectIPs": [
          "103.143.19.140",
          "103.21.244.0/22",
          "103.22.200.0/22",
          "103.31.4.0/22",
          "104.16.0.0/13",
          "104.24.0.0/14",
          "108.162.192.0/18",
          "114.114.114.114",
          "119.29.29.29",
          "119.6.6.6",
          "131.0.72.0/22",
          "141.101.64.0/18",
          "162.158.0.0/15",
          "172.64.0.0/13",
          "173.245.48.0/20",
          "188.114.96.0/20",
          "190.93.240.0/20",
          "197.234.240.0/22",
          "198.41.128.0/17",
          "223.5.5.5",
          "10.0.0.0/8",
          "172.16.0.0/16",
          "192.168.0.0/16",
          "61.128.128.68",
          "geoip:cn",
          "geoip:private"
        ]
      },
      "https://dns.google/dns-query"
    ]
  }
}
</code></pre></details>

### 服务端配置

<details><pre><code>

</code></pre></details>

### 客户端日志

<details><pre><code>

</code></pre></details>

### 服务端日志

<details><pre><code>

</code></pre></details>

**Comment by Fangliding** [comment]
出问题时候 日志（打开dnslog）

**Comment by Fangliding** [comment]
close as no response
