### ISSUE TITLE
大佬考虑添加homebrew仓库支持吗？

### ISSUE THREAD

**Issue by KyonCN** [XTLS/Xray-core#35]
[https://github.com/v2ray/homebrew-v2ray](url)
就像v2ray这个homebrew仓库一样，mac系统下用brew来管理xray-core的升级会很方便。

**Comment by rprx** [comment]
可以，如果你愿意尝试维护的话

**Comment by KyonCN** [comment]
我可以维护 但我要换个账号 这个账号太容易track到本人了  麻烦删除这个issue 我去换个账号准备仓库

**Comment by rprx** [comment]
Ok
