### ISSUE TITLE
求教 client->中转->落地 的场景中，如何在中转阶段将目标站点域名通过内置DNS解析为IP地址再出站

### ISSUE THREAD

**Issue by g-u-a-n** [XTLS/Xray-core#3507]
### 首先感谢 Xray 开源项目为我提供的便利，衷心感谢众位贡献者大佬们的付出。

# 使用场景
本人有以下的使用场景：

1. 通过软路由实现代理，由软路由负责DNS解析，其中被污染的域名由软路由向VPS转发DNS查询。
    代理方式是：`软路由与国外中转机直接连接`
2. 在终端通过SS之类的客户端实现代理
    代理方式是：`SS客户端 -> 国内中转机 -> 国外中转机`

# 想要实现的效果
由`国外中转机`统一处理分流落地，`国内中转机`只负责拉国外中转机的线路

# 目前的策略配置
由于本人主要还是通过 **场景1** 软路由来实现代理，且DNS查询已由软路由处理。所以在`国外中转机`配置中，设定： 

`routing.domainStrategy = AsIs`
`inbounds.sniffing.routeOnly = true`
`inbounds.sniffing.destOverride = ["http", "tls", "quic"]`

由于在 **场景1** 中，DNS查询已通过软路由实现，所以通过以上设定可以避免`国外中转机`在路由分流阶段的DNS二次查询，最终实现在`国外中转机`实现域名+IP地址分流。

# 目前遇到的问题
基于 **目前的策略配置** 想要实现域名+IP地址分流，就要确保Xray客户端传递过来的目标站点是解析之后的IP地址，之后Xray服务端再通过sniffing嗅探出域名，最终实现域名+IP地址分流效果。

✔ 在 **场景1** 中，能够实现域名+IP地址分流效果。

❌ 在 **场景2** 中，无法完全实现，因为`国内中转机`向`国外中转机`传递的是目标站点的域名而非IP地址，又因`国外中转机`在 **场景1** 中避免二次DNS查询而设定的 `routing.domainStrategy = AsIs` ，最终导致只能实现域名分流，无法实现IP地址分流。

# 个人的解决措施/求教
既然在 **场景2** 中，`国内中转机`向`国外中转机`传递的是目标站点的域名而非IP地址，那么就在`国内中转机`中将目标站点的域名先解析为IP地址，再传递给`国外中转机`，查阅文档发现 [内置dns服务器章节](https://xtls.github.io/config/dns.html#dns-%E6%9C%8D%E5%8A%A1%E5%99%A8) 有相关介绍内容：

> 如 在 sockopt 中，将 domainStrategy 设置为 UseIP, 此出站发起的系统连接，将先由内置服务器解析为 IP, 然后进行连接。

所以在`国内中转机`中设定 `outbounds.streamSettings.sockopt.domainStrategy = UseIP` ，但此设定依然无法解决问题，`国内中转机`向`国外中转机`传递的还是域名，并没有通过内置服务器解析为IP后再连接。（可能是我曲解了关于此设定的作用）

其他可行的解决方式

- ❌ 直接将 `routing.domainStrategy = AsIs` 改为 `routing.domainStrategy = IPIfNonMatch`（在 **场景1** 使用中导致重复的DNS查询耗时，有点不够极致哈{~~屁事多~~}）
- ❌ 直接在`国内中转机`中进行分流落地（需要在国内和国外中转机分别维护分流策略，无法统一管理，有点不够优雅哈{~~手还懒~~}）

### 求教各位大佬们，有无能够在outbound出站之前，能更好的实现将目标站点解析为IP地址，再二次代理分流的方式？
（有点类似 Freedom 中的 `domainStrategy = UseIP` 效果，但是 Freedom 是直连）

**Comment by Fangliding** [comment]
这个好久了 我以前也纳闷 事实是 可以抽时间写一下

**Comment by Fangliding** [comment]
这个好久了 我以前也纳闷 事实是不支持 可以抽时间写一下

**Comment by Fangliding** [comment]
那udp不管好了 这东西真不好动(

**Comment by Fangliding** [comment]
讲道理现有的机制遇到dest为域名的udp请求一样会出问题吧(

**Comment by Fangliding** [comment]
开源拖拉机你行你上 反正我不用.png

**Comment by yuhan6665** [comment]
*ray 的代理逻辑是域名优于 IP 所以原 po 的问题我认为是国外中转机 routing.domainStrategy = AsIs 应该在这方面下功夫

~~比如搞两个 core 解决不同场景的需求~~
