### ISSUE TITLE
The solution to the problem of not connecting splithttp with some cdns

### ISSUE THREAD

**Issue by internetfreedomir** [XTLS/Xray-core#3509]
Is it possible to send each get or post request in splithttp as a separate tls handshake?
Because sending get and post requests at the same time makes it not work with some CDNs! 
These CDNs send responses to requests one by one!

**Comment by internetfreedomir** [comment]
> In order to even just establish a single connection, splithttp needs one _long-running_ GET request, and then send POST requests while that GET request is still ongoing.
> 
> If the CDN only supports one HTTP request at a time, it will not work at all, because the transport can only open either the upload or the download half, but not both.
> 
> Why do you think the CDN can only handle one request at a time? That's very unusual, and to be honest I strongly doubt it for anything that calls itself a CDN.

cdn support said that only one http request can be handled in each tls handshake

**Comment by internetfreedomir** [comment]
Maybe it can't be called CDN, but the features they provide are just like a simple reverse proxy

**Comment by internetfreedomir** [comment]
> > cdn support said that only one http request can be handled in each tls handshake
> 
> then it may only support HTTP/1.1 and also provide the `Connection: close` response header (or close the connection by itself), and the transport should function normally.
> 
> I need way more information to do anything useful with this report.
> 
> * does it have anything to do with TLS? does it work without TLS?
> * which CDN are we talking about? If you cannot tell me that's ok

One of Iran's CDNs !
They also support http2

I think they used php to make a simple reverse proxy, so it includes php limits for concurrent requests! Of course, I asked about this, but they said that we cannot explain the CDN structure

**Comment by internetfreedomir** [comment]
> I think the CDN just does not support h2, which matches your description of "one request at a time" (but, per connection!). In that case please either try disabling TLS, or it will be fixed in the next version, where you can set `alpn=http/1.1`

So I will wait for the next versions and I know that nothing is standard in Iran, not even CDNs ! 😂

**Comment by internetfreedomir** [comment]
> Send me an email (see profile) and I'll take a look at the specific CDN if you cannot disclose it. I may have to ask for access credentials.
> 
> Otherwise I think this is too much of a guessing game. If you say the CDN supports h2 most likely the next version won't fix anything.

Even if I give config for those who are outside Iran, it will not connect because this CDN can only be connected from inside Iran. But I checked the download link without any problem with idm in Windows and adm in Android, even when multi-part download was on, it was downloaded! 
splithttp also connects, but it is not stable at all, and when downloading, the upload is interrupted, and when uploading, the download is interrupted!

**Comment by internetfreedomir** [comment]
By the way, it only connects with mux!
But mux does not make the connection stable, and again, when it is downloading, it is not uploading and when it is uploading, it is not downloading!

**Comment by Fangliding** [comment]
A wired service doesn't allow
