### ISSUE TITLE
VLESS+xtls访问google.com报请求的域名与服务器的证书不匹配

### ISSUE THREAD

**Issue by bruce2k** [XTLS/Xray-core#351]
根据小小白白话文配置完毕后，能正常访问CNN且能看视频，可访问Google.com时您的连接不安全。可以正常访问油管，但无法观看视频，求指点！

证书申请命令：
acme.sh --issue -d www.mydomain.com -w /home/XXXX/www/webpage --keylength ec-256 --force
证书安装命令：
acme.sh --install-cert -d www.mydomain.com --ecc \
             --fullchain-file ~/xray_cert/xray.crt \
             --key-file ~/xray_cert/xray.key

**Comment by bruce2k** [comment]
file:///home/bruce/%E5%9B%BE%E7%89%87/2021-03-08%2018-12-14%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png

**Comment by bruce2k** [comment]
图

**Comment by JimhHan** [comment]
Thanks for your support. Please check your network and try again.

**Comment by bruce2k** [comment]
my network looks fine,don't know why the issue happen.

**Comment by bruce2k** [comment]
hi, @jimHan,could you pls tell me check which option?

**Comment by bruce2k** [comment]
Hi,Jim Han, could you please,tell me check which option? thanks a lot!发自我的华为手机-------- 原始邮件 --------发件人： Jim Han <notifications@github.com>日期： 2021年3月9日周二 10:42收件人： XTLS/Xray-core <Xray-core@noreply.github.com>抄送： bruce2k <bruce2k@163.com>, Author <author@noreply.github.com>主    题： Re: [XTLS/Xray-core] VLESS+xtls访问google.com报请求的域名与服务器的证书不匹配 (#351)
Closed #351.
