### ISSUE TITLE
Request for TCP socket option TCP_NOTSENT_LOWAT

### ISSUE THREAD

**Issue by galaxyport** [XTLS/Xray-core#3516]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.

### Version

latest

### Description

Based on the article written at https://blog.cloudflare.com/http-2-prioritization-with-nginx, this TCP option on the server can reduce bufferbloat in HTTP/2 and gRPC, enabling a more responsive connection. However, when this option is enabled on the server, it only affects the user's downlink.

By adding this socket option to Xray, we can also benefit from its advantages on the uplink side.

### Reproduction Method

REQUEST OPTION

### Client config

<details><pre><code>

</code></pre></details>

### Server config

<details><pre><code>

</code></pre></details>

### Client log

<details><pre><code>

</code></pre></details>

### Server log

<details><pre><code>

</code></pre></details>

**Comment by Fangliding** [comment]
Even we add it, it can only work on Linux client.
If you are using Linux you can use sysctl to change it.
Btw, change it has no help to xray(xray has no such "critical resource", all data are the same)

**Comment by galaxyport** [comment]
Currently, adding this option to Android is not possible because it requires root system access. However, if it is added, it will be possible to use it on Android without root.

The term "critical resource" is used in relation to HTTP/2, whereas this option operates on TCP.

I was thinking that this option can be effective in preventing bufferbloat if there is a bandwidth limitation on the outgoing side. In such a case, in multiplexed connections like h2 and gRPC, the sending buffer can be kept small so that a large portion of the data doesn't sit in the operating system's buffer. When the upload bandwidth is low, if a large amount of data is buffered on TCP, it causes head-of-line blocking for each connection within the multiplex. The connections in the multiplex will wait until the previous request is sent before they can be sent. With the addition of this option, the connections will be used more fairly, reducing latency.

**Comment by Fangliding** [comment]
Actually, setting sockopt on Android is not always effective(
The key is that TCP buffer affects HTTP2's resource prioritization, resulting in delayed loading of critical resources and slow down the loading speed of the entire webpage. It is obvious that xray does not have such a thing.
Putting aside theory, at least provide test results that this sockopt can increase speed, otherwise this will not be planned

**Comment by Fangliding** [comment]
In the end, we still supported this. You can test whether it will bring performance improvement ((

**Comment by galaxyport** [comment]
> In the end, we still supported this. You can test whether it will bring performance improvement ((

thank you, theoretically it shouldn't bring speed gains, actually it can cut a little bit of that performance in favor of responsiveness and latency in bloated connections specifically variable speed links, for example when we have low upload speed  and variable upload speed on mobile data.

**Comment by BK8000L** [comment]
> You can test whether it will bring performance improvement

link speed is 10mbit/s

vless+mux1024+lowat=4294967295 (linux default)
![image](https://github.com/user-attachments/assets/447ef77a-e172-40a1-a490-d17d0c5a5675)

vless+mux1024+lowat=16384 (like on cloudflare)
![image](https://github.com/user-attachments/assets/97617459-35b1-43fe-900b-dac815ee9144)

vless+mux1024+cloudflare+lowat=4294967295 (linux default)
![image](https://github.com/user-attachments/assets/e57cf3f8-77f4-4a20-b004-ee51ceba3155)

vless+mux1024+cloudflare+lowat=16384 (like on cloudflare)
![image](https://github.com/user-attachments/assets/9af7dae6-7ab2-4494-ae93-09c2b5f05c0c)

lowat was changed on both sides
