### ISSUE TITLE
TPROXY method blocking traffics of the docker containers

### ISSUE THREAD

**Issue by Ali-Flt** [XTLS/Xray-core#3525]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.

### Version

1.8.16

### Description

I am using this method for tproxy: https://github.com/XTLS/Xray-docs-next/blob/main/docs/document/level-2/tproxy.md
I use the nftables rules for routing. Everything works fine except for the fact that the docker containers that are running on the same machine as the tproxy lose access to the internet when I start the nftables service. 
I also tried changing the tproxy method from "tproxy" to "redirect" in the xray json config file but got the same result.

### Reproduction Method

Reproduce using these steps: https://github.com/Ali-Flt/xray-tproxy/tree/main

### Client config

<details><pre><code>

</code></pre></details>

### Server config

<details><pre><code>

</code></pre></details>

### Client log

<details><pre><code>

</code></pre></details>

### Server log

<details><pre><code>

</code></pre></details>

**Comment by Fangliding** [comment]
Docker will add additional iptables rules , which will affect the user's own added rules and cause errors. This is not the core issue

**Comment by Ali-Flt** [comment]
@Fangliding any suggestions how to mitigate this though?
