### ISSUE TITLE
全局代理pip/conda https请求无法识别

### ISSUE THREAD

**Issue by Phoveran** [XTLS/Xray-core#353]
如图，如果改为http访问即可识别
![image](https://user-images.githubusercontent.com/38107945/110427392-a4c0e000-80e2-11eb-889f-7305839c180f.png)
![image](https://user-images.githubusercontent.com/38107945/110427470-c621cc00-80e2-11eb-82e2-06dcb2369e3a.png)

**Comment by Phoveran** [comment]
入站配置如下
"inbounds": [
    {
      "tag": "socks",
      "port": 10808,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "allowTransparent": false
      }
    },
    {
      "tag": "http",
      "port": 10809,
      "listen": "127.0.0.1",
      "protocol": "http",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "udp": false,
        "allowTransparent": false
      }
    }
  ]

**Comment by AkinoKaede** [comment]
首先，这个不是 Xray 的问题
按照我的经验，可能是把代理错误配置成了 https
