### ISSUE TITLE
linux 中作为客户端内存泄露 以及 TLS 连接错误

### ISSUE THREAD

**Issue by jiaopengzi** [XTLS/Xray-core#3544]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了issues，没有发现已提出的类似问题。

### 版本

Xray 1.8.18

### 描述

如下  xray 的客户端配置文件`config.json`，

- 问题1：现在有个问题在debian中使用，会造成内存泄露，直到卡死。

- 问题2：当下载的时候，刚开始网速是可以的能到10M每秒，突然网速就只有几十KB了。

     

请大佬帮忙看看是什么问题。

环境如下：

```bash
root@ecs48:~# uname -a
Linux ecs48 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux
root@ecs48:~# ./xray --version
Xray 1.8.18 (Xray, Penetrates Everything.) 9e6d7a3 (go1.22.5 linux/amd64)
A unified platform for anti-censorship.
```

另外相同的服务端在我的 openwrt 软路由中使用时正常的。

附件中是错误日志。

### 重现方式

重试了很多次都是一样的。

### 客户端配置
<details><pre><code>
{
  "log": {
    "access": "/var/log/xray/access.log",
    "error": "/var/log/xray/error.log",
    "loglevel": "warning",
    "dnsLog": false
  },
  "inbounds": [
    {
      "tag": "http",
      "port": 8888,
      "listen": "172.24.83.237",
      "protocol": "http",
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"],
        "routeOnly": false
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "allowTransparent": false
      }
    },
    {
      "tag": "socks",
      "port": 8889,
      "listen": "172.24.83.237",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"],
        "routeOnly": false
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "allowTransparent": false
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "2*.*.*.*3",
            "port": 27001,
            "users": [
              {
                "id": "8844e******7fa51b32",
                "email": "fX*****e@xray.com",
                "security": "auto",
                "encryption": "none",
                "flow": "xtls-rprx-vision"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "serverName": "www.amazon.com",
          "fingerprint": "chrome",
          "show": false,
          "publicKey": "9rx7J******2J7uVc",
          "shortId": "70****631",
          "spiderX": ""
        }
      },
      "mux": {
        "enabled": false,
        "concurrency": -1
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    }
  ],
  "dns": {
    "hosts": {
      "dns.google": "8.8.8.8"
    },
    "servers": [
      {
        "address": "223.5.5.5",
        "domains": ["geosite:cn"],
        "expectIPs": ["geoip:cn"]
      },
      "1.1.1.1",
      "8.8.8.8"
    ]
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "domain": ["geosite:category-ads-all"],
        "outboundTag": "block"
      },
      {
        "type": "field",
        "domain": [
          "geosite:cn",
          "full:xunhupay.com",
          "full:bilibili.com",
          "full:baidu.com",
          "full:tencent.com",
          "full:qq.com",
          "full:weixin.qq.com",
          "full:weixin.com",
          "full:wechat.com",
          "full:gitee.com",
          "full:jiaopengzi.com",
          "full:aliyun.com",
          "full:taobao.com",
          "full:iconfont.cn",
          "full:jd.com",
          "full:huya.com",
          "full:bilibili.cn",
          "full:bilivideo.com",
          "full:bilivideo.cn",
          "full:biliapi.com",
          "full:biliapi.net",
          "full:apple.com",
          "full:ubuntu.com",
          "full:lanhome.com",
          "full:bcebos.com",
          "full:163.com",
          "full:download.microsoft.com",
          "full:download.prss.microsoft.com",
          "full:tsinghua.edu.cn",
          "full:containerd.io",
          "full:azure.com",
          "full:douban.com"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "ip": ["geoip:private", "geoip:cn", "223.5.5.5"],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "protocol": ["bittorrent"],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "domain": [
          "geosite:geolocation-!cn",
          "full:google.com",
          "full:google.com.hk",
          "full:accounts.google.com",
          "full:aistudio.google.com",
          "full:accounts.google.com.hk",
          "full:obsproject.com",
          "full:element-plus.org",
          "full:mozilla.org",
          "full:github.com",
          "full:python.org",
          "full:youtube.com",
          "full:linux.com",
          "full:docker.io",
          "full:hub.docker.com",
          "full:docker.com",
          "full:download.docker.com",
          "full:go.uber.org",
          "full:golang.org",
          "full:gorm.io",
          "full:moul.io",
          "full:gopkg.in",
          "full:sigs.k8s.io",
          "full:npmjs.com",
          "full:powerbi.com",
          "full:outlook.live.com",
          "full:openai.com",
          "full:unraid.net",
          "full:proxmox.com",
          "full:debian.org",
          "full:enterprisedb.com",
          "full:alpinelinux.org",
          "full:jetbrains.com",
          "full:deb.debian.org",
          "full:security.debian.org",
          "full:yourdomain.com"
        ],
        "outboundTag": "proxy"
      },
      {
        "type": "field",
        "ip": ["1.1.1.1"],
        "outboundTag": "proxy"
      }
    ]
  }
}

</code></pre></details>

### 服务端配置

<details><pre><code>
{
  "log": null,
  "routing": {
    "rules": [
      {
        "inboundTag": ["api"],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": ["geoip:private"],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": ["bittorrent"],
        "type": "field"
      }
    ]
  },
  "dns": null,
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "streamSettings": null,
      "tag": "api",
      "sniffing": null
    },
    {
      "listen": null,
      "port": 27001,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "8844******7fa51b32",
            "email": "fX******ve@xray.com",
            "flow": "xtls-rprx-vision"
          }
        ],
        "decryption": "none",
        "fallbacks": []
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "show": false,
          "dest": "www.amazon.com:443",
          "xver": 0,
          "serverNames": ["www.amazon.com"],
          "privateKey": "qETaay******Pqk4",
          "publicKey": "9rx7******l2J7uVc",
          "minClient": "",
          "maxClient": "",
          "maxTimediff": 0,
          "shortIds": ["", "b1", "0768", "6408bc", "70980631"]
        },
        "tcpSettings": {
          "header": {
            "type": "none"
          },
          "acceptProxyProtocol": false
        }
      },
      "tag": "inbound-27001",
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls", "quic"]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "transport": null,
  "policy": {
    "levels": {
      "0": {
        "handshake": 10,
        "connIdle": 100,
        "uplinkOnly": 2,
        "downlinkOnly": 3,
        "statsUserUplink": true,
        "statsUserDownlink": true,
        "bufferSize": 10240
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "api": {
    "services": ["HandlerService", "LoggerService", "StatsService"],
    "tag": "api"
  },
  "stats": {},
  "reverse": null,
  "fakeDns": null
}

</code></pre></details>

### 客户端日志

[access.log](https://github.com/user-attachments/files/16260760/access.log)
[error.log](https://github.com/user-attachments/files/16260761/error.log)

### 服务端日志
[access.log](https://github.com/user-attachments/files/16260763/access.log)
[error.log](https://github.com/user-attachments/files/16260764/error.log)

**Comment by Fangliding** [comment]
确定吃内存的是xray么 还有是怎么个用法 有没有用tun之类的东西

**Comment by jiaopengzi** [comment]
重启开机后启动 pid是 772
![7bada30eef1a00cd0cdde99237e0cb6](https://github.com/user-attachments/assets/64a13549-ccb3-4555-87e7-934426e3bd98)

中途卡死了，没法使用ssh工具，从后台查看 自动重启的pid 7505
![image](https://github.com/user-attachments/assets/6a9ac4ea-d6ec-4d92-a040-b532171d1f38)

用法就是使用一个xray作为客户端，至于tun我不懂，应该是没有使用吧。

**Comment by iamumr** [comment]
我貌似也这样，ubuntu更新了1.8.18 Xray，今天吃满了内存，ssh都登入不上去了，我回退1.8.8了，还在测试。windows下1.8.18没有这个问题，不知道是不是版本的问题。

**Comment by RPRX** [comment]
上个稳定版 v1.8.16 有该问题吗？我看了下 v1.8.16 之后的代码基本上与 VLESS Vision REALITY 客户端无关

**Comment by jiaopengzi** [comment]
> 上个稳定版 v1.8.16 有该问题吗？我看了下 v1.8.16 之后的代码基本上与 VLESS-Vision-REALITY 客户端无关

昨天挨个试了试貌似都是有问题的，
![image](https://github.com/user-attachments/assets/919da5e8-c795-45be-927a-0d6b23920a77)

之前一直稳定跑了大半年了。不知道为啥突然就这样了。我重新上传了客户端和服务端的 debug级别的日志。请大佬查看。我再试试将客户端和服务端都换成 1.18.16 再来反馈。

**Comment by jiaopengzi** [comment]
> 上个稳定版 v1.8.16 有该问题吗？我看了下 v1.8.16 之后的代码基本上与 VLESS-Vision-REALITY 客户端无关

![image](https://github.com/user-attachments/assets/c0eae957-883e-4563-920c-a650070a57b2)


服务端和客户端更换为 `1.18.16` ，内存飙高，崩溃。服务端和客户端配置没有变。

**Comment by iamumr** [comment]
回退后，尝试1.8.8,1.8.7,1.8.3本地Ubuntu依旧高内存占用、崩溃，服务器（最小安装）回退后稳定，均为Ubuntu22.04，出问题端昨天使用apt upgrade进行过升级，有没有可能为某依赖包导致？

**Comment by jiaopengzi** [comment]
> 回退后，尝试1.8.8,1.8.7,1.8.3本地Ubuntu依旧高内存占用、崩溃，服务器（最小安装）回退后稳定，均为Ubuntu22.04，出问题端昨天使用apt upgrade进行过升级，有没有可能为某依赖包导致？

你用的那个版本的 xray ？我使用 Ubuntu22.04 和 Ubuntu20.04 也有同样的问题。

**Comment by RPRX** [comment]
所以是不是近期 Ubuntu 升级了啥包导致的，主要是 Xray v1.8 这些版本那么久了，至今就你俩报告这问题

**Comment by jiaopengzi** [comment]
搞了2天了，xray 客户端使用还是不行。
换了个思路，服务端还是使用 xray ，在本地 openwrt 软路由上 使用 shadowsocks 作为服务端中转了一下(有公网ip)，在服务器上使用 shadowsocks-libev 作为客户端 。可以实现了。

**Comment by GeekSquirrel** [comment]
最近openwrt软路由也出现了同样的问题，之前稳定运行了大半年，最近一两个月，会在比较短的时间内吃满内存，然后导致dns解析异常，慢则不到一天，快则几十分钟。没有找到触发的问题的具体原因。但是重置了路由器配置，又从passwall换到passwall2，最终表现都一样，所以怀疑是xray的问题。
