### ISSUE TITLE
前端用haproxy反代reality无法使用send-proxy-v2配置，导致无法获取真实IP

### ISSUE THREAD

**Issue by phoenixxie0** [XTLS/Xray-core#3563]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了issues，没有发现已提出的类似问题。

### 版本

1.8.19

### 描述

前端用haproxy反代reality无法使用send-proxy-v2配置，导致无法获取真实IP
haproxy相关配置如下
`
frontend reality
  mode tcp
  bind :33333 tfo alpn h2,http/1.1
  tcp-request inspect-delay 5s
  tcp-request content accept if { req.ssl_hello_type 1 }
  acl tls req.ssl_hello_type 1
  acl reality req_ssl_sni -i xxx.xxx.xxx
  use_backend xray if reality

backend xray
  mode tcp
  option ssl-hello-chk
  timeout server 1h
  retry-on conn-failure empty-response response-timeout
  server xray /dev/shm/xray/xtls.socket send-proxy-v2 tfo
 `

### 重现方式

均可重现

### 客户端配置

<details><pre><code>
    "outbounds": [
        {
            "protocol": "vless", 
            "settings": {
                "vnext": [
                    {
                        "address": "1.2.3", 
                        "port": 33333, 
                        "users": [
                            {
                                "id": "123456",
                                "flow": "xtls-rprx-vision",
                                "encryption": "none"
                            }
                        ]
                    }
                ]
            }, 
            "streamSettings": {
                "network": "tcp",
                "security": "reality",
                "realitySettings": {
                    "show": false, 
                    "fingerprint": "firefox", 
                    "serverName": "xxx.xxx.xxx.xxx",
                    "publicKey": "xxxxx",
                    "shortId": "xxxxx", 
                    "spiderX": ""
                },
                "sockopt": {
                    "mark": 255
                }
            }
        }, 
</code></pre></details>

### 服务端配置

<details><pre><code>
"inbounds": [
        {
            "listen": "/dev/shm/xray/xtls.socket,0777",
            //"listen": "0.0.0.0",
            //"port": 35365,
            "protocol": "vless", 
            "settings": {
                "clients": [
                    {
                        "id": "zzzzzz",
                        "flow": "xtls-rprx-vision"
                    }
                ],
                "decryption": "none"
            }, 
            "streamSettings": {
                "network": "tcp",
                "security": "reality",
                "realitySettings": {
                    "show": true, 
                    "acceptProxyProtocol": true, 
                    "dest": "/var/run/nginx-ssl.sock", 
                    "xver": 2, 
                    "serverNames": [
                        "aaa.bbb.ccc"
                    ],
                    "privateKey": "xxxxx", 
                    "minClientVer": "1.7.5", 
                    "maxClientVer": "", 
                    "maxTimeDiff": 6000, 
                    "shortIds": 
                        "xxx"
                    ]
                }
            }, 
            "disableInsecureEncryption": true,
            "tag": "xtls-port"
        },
</code></pre></details>

### 客户端日志

<details><pre><code>
2024/07/20 18:47:38 [Warning] core: Xray 1.8.18 started
2024/07/20 18:47:38 [Info] app/dispatcher: taking detour [interconn] for [tcp:test-fhome.xray.com:0]
2024/07/20 18:47:38 [Info] transport/internet/tcp: dialing TCP to tcp:aaaaaaaaaa:5121
2024/07/20 18:47:38 [Debug] transport/internet: dialing to tcp:aaaaaaaaa:5121
2024/07/20 18:47:38 [Info] app/dispatcher: taking platform initialized detour [SA-GIA] for [tcp:www.google.com:443]
2024/07/20 18:47:38 [Info] transport/internet/tcp: dialing TCP to tcp:102.223.72.246:443
2024/07/20 18:47:38 [Debug] transport/internet: dialing to tcp:102.223.72.246:443
2024/07/20 18:47:38 [Info] [2447860657] proxy/socks: TCP Connect request to tcp:8.8.8.8:853
2024/07/20 18:47:38 [Info] [2447860657] app/dispatcher: taking detour [US-GIA] for [tcp:8.8.8.8:853]
2024/07/20 18:47:38 [Info] [2447860657] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:38 [Debug] [2447860657] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:38 [Info] [2879710526] proxy/socks: TCP Connect request to tcp:1.0.0.1:853
2024/07/20 18:47:38 [Info] [2879710526] app/dispatcher: taking detour [US-GIA] for [tcp:1.0.0.1:853]
2024/07/20 18:47:38 [Info] [2879710526] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:38 [Debug] [2879710526] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:38 [Info] [1523488124] proxy/socks: TCP Connect request to tcp:149.154.167.41:80
2024/07/20 18:47:38 [Info] [3525952310] proxy/socks: TCP Connect request to tcp:149.154.167.41:443
2024/07/20 18:47:38 [Info] [1523488124] app/dispatcher: sniffed domain: 149.154.167.41
2024/07/20 18:47:38 [Info] [1523488124] app/dispatcher: taking detour [US-GIA] for [tcp:149.154.167.41:80]
2024/07/20 18:47:38 [Info] [1523488124] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:38 [Debug] [1523488124] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:38 [Info] [3525952310] app/dispatcher: taking detour [US-GIA] for [tcp:149.154.167.41:443]
2024/07/20 18:47:38 [Info] [3525952310] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:38 [Debug] [3525952310] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:38 [Info] [1258424194] proxy/socks: TCP Connect request to tcp:[2001:67c:4e8:f002::a]:443
2024/07/20 18:47:38 [Info] [1258424194] app/dispatcher: taking detour [US-GIA] for [tcp:[2001:67c:4e8:f002::a]:443]
2024/07/20 18:47:38 [Info] [1258424194] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:38 [Debug] [1258424194] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:38 [Info] proxy/vless/outbound: tunneling request to tcp:www.google.com:443 via 102.223.72.246:443
2024/07/20 18:47:38 [Info] proxy: XtlsFilterTls found tls client hello! 266
2024/07/20 18:47:38 [Info] proxy: XtlsPadding 266 854 0
2024/07/20 18:47:38 [Info] [3525952310] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:38 [Debug] [3525952310] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:38 [Info] [2447860657] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:38 [Debug] [2447860657] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:38 [Info] [1258424194] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:38 [Debug] [1258424194] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:38 [Info] [1523488124] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:38 [Debug] [1523488124] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:38 [Info] [2879710526] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:38 [Debug] [2879710526] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:38 [Info] [4210129002] proxy/socks: TCP Connect request to tcp:91.108.56.172:80
2024/07/20 18:47:38 [Info] [3722291823] proxy/socks: TCP Connect request to tcp:91.108.56.172:80
2024/07/20 18:47:38 [Info] [4210129002] app/dispatcher: sniffed domain: 91.108.56.172
2024/07/20 18:47:38 [Info] [4210129002] app/dispatcher: taking detour [US-GIA] for [tcp:91.108.56.172:80]
2024/07/20 18:47:38 [Info] [3722291823] app/dispatcher: sniffed domain: 91.108.56.172
2024/07/20 18:47:38 [Info] [4210129002] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:38 [Info] [3722291823] app/dispatcher: taking detour [US-GIA] for [tcp:91.108.56.172:80]
2024/07/20 18:47:38 [Debug] [4210129002] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:38 [Info] [3722291823] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:38 [Debug] [3722291823] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:38 [Info] proxy/vmess/outbound: tunneling request to tcp:test-fhome.xray.com:0 via aaa.fff.cccc:5121
2024/07/20 18:47:38 [Info] common/mux: received request for udp:reverse.internal.v2fly.org:0
2024/07/20 18:47:38 [Info] proxy: Xtls Unpadding new block, content 4089 padding 36 command 0
2024/07/20 18:47:38 [Info] proxy: XtlsFilterTls found tls 1.3! 1163 TLS_AES_128_GCM_SHA256
2024/07/20 18:47:38 [Info] proxy: XtlsPadding 64 1276 0
2024/07/20 18:47:38 [Info] proxy: XtlsPadding 129 972 2
2024/07/20 18:47:38 [Info] [4210129002] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:38 [Debug] [4210129002] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:38 [Info] [3722291823] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:38 [Debug] [3722291823] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:39 [Info] [3525952310] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:39 [Debug] [3525952310] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:39 [Info] [1258424194] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:39 [Debug] [1258424194] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:39 [Info] [2879710526] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:39 [Debug] [2879710526] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:39 [Info] [2447860657] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:39 [Debug] [2447860657] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:39 [Info] [1523488124] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:39 [Debug] [1523488124] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:39 [Info] proxy: Xtls Unpadding new block, content 206 padding 1069 command 2
2024/07/20 18:47:39 [Info] proxy: CopyRawConn readv
2024/07/20 18:47:39 [Info] app/observatory: the outbound SA-GIA is alive:0.883840558
2024/07/20 18:47:39 [Debug] [636823136] proxy/dokodemo: processing connection from: 127.0.0.1:51820
2024/07/20 18:47:39 [Info] [636823136] proxy/dokodemo: received request for 127.0.0.1:51820
2024/07/20 18:47:39 [Info] [636823136] app/dispatcher: taking detour [US-GIA] for [udp:127.0.0.1:4500]
2024/07/20 18:47:39 [Info] [636823136] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:39 [Debug] [636823136] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:39 [Info] [636823136] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:39 [Debug] [636823136] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:39 [Info] [4210129002] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:39 [Debug] [4210129002] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:39 [Info] [3722291823] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:39 [Debug] [3722291823] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:39 [Info] [3525952310] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:39 [Debug] [3525952310] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:39 [Info] [2879710526] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:39 [Debug] [2879710526] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:39 [Info] [1258424194] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:39 [Debug] [1258424194] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:39 [Info] [2447860657] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:39 [Debug] [2447860657] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:39 [Info] [1523488124] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:39 [Debug] [1523488124] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:39 [Info] [636823136] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:39 [Debug] [636823136] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:40 [Info] [4210129002] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:40 [Debug] [4210129002] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:40 [Info] [3722291823] transport/internet/tcp: dialing TCP to tcp:xxx.xxx.xxx.xxx:35365
2024/07/20 18:47:40 [Debug] [3722291823] transport/internet: dialing to tcp:xxx.xxx.xxx.xxx:35365
</code></pre></details>

### 服务端日志

<details><pre><code>
2024/07/20 06:44:20 [Debug] app/log: Logger started
2024/07/20 06:44:20 [Info] app/dns: DNS: created UDP client initialized for 8.8.4.4:53
2024/07/20 06:44:20 [Info] app/dns: DNS: created Local DNS-over-QUIC client for quic+local://dns.adguard.com
2024/07/20 06:44:20 [Info] app/dns: DNS: created Local DOH client for https://dns.google/dns-query
2024/07/20 06:44:20 [Info] app/dns: DNS: created Local DOH client for https://1.0.0.1/dns-query
2024/07/20 06:44:20 [Debug] app/router: MphDomainMatcher is enabled for 697 domain rule(s)
2024/07/20 06:44:20 [Debug] app/router: MphDomainMatcher is enabled for 3 domain rule(s)
2024/07/20 06:44:20 [Debug] app/router: MphDomainMatcher is enabled for 96440 domain rule(s)
2024/07/20 06:44:20 [Debug] app/proxyman/inbound: creating unix domain socket worker on /dev/shm/xray/xtls.socket,0777
2024/07/20 06:44:20 [Debug] app/proxyman/inbound: creating unix domain socket worker on /dev/shm/xray/vlessws.socket,0777
2024/07/20 06:44:20 [Debug] app/proxyman/inbound: creating unix domain socket worker on /dev/shm/xray/vmessws.socket,0777
2024/07/20 06:44:20 [Info] transport/internet/httpupgrade: listening unix domain socket(for HttpUpgrade) on /dev/shm/xray/vlessws.socket,0777
2024/07/20 06:44:20 [Info] transport/internet/websocket: listening unix domain socket(for WS) on /dev/shm/xray/vmessws.socket,0777
2024/07/20 06:44:20 [Info] transport/internet/tcp: listening Unix Domain Socket on /dev/shm/xray/xtls.socket,0777
2024/07/20 06:44:20 [Warning] core: Xray 1.8.19 started
2024/07/20 06:44:20 [Info] app/dispatcher: taking platform initialized detour [warp-socks5] for [tcp:www.google.com:443]
2024/07/20 06:44:20 [Info] transport/internet/tcp: dialing TCP to tcp:127.0.0.1:40000
2024/07/20 06:44:20 [Debug] transport/internet: dialing to tcp:127.0.0.1:40000
2024/07/20 06:44:20 [Info] transport/internet/tcp: dialing TCP to tcp:127.0.0.1:40000
2024/07/20 06:44:20 [Debug] transport/internet: dialing to tcp:127.0.0.1:40000
2024/07/20 06:44:21 [Info] transport/internet/tcp: dialing TCP to tcp:127.0.0.1:40000
2024/07/20 06:44:21 [Debug] transport/internet: dialing to tcp:127.0.0.1:40000
2024/07/20 06:44:21 [Info] transport/internet/tcp: dialing TCP to tcp:127.0.0.1:40000
2024/07/20 06:44:21 [Debug] transport/internet: dialing to tcp:127.0.0.1:40000
2024/07/20 06:44:21 [Info] [1636268745] proxy/vless/inbound: firstLen = 538
2024/07/20 06:44:21 [Info] [1636268745] proxy/vless/inbound: received request for tcp:91.108.56.172:80
2024/07/20 06:44:21 [Info] [1636268745] app/dispatcher: default route for tcp:91.108.56.172:80
2024/07/20 06:44:21 [Info] [1636268745] proxy: Xtls Unpadding new block, content 225 padding 248 command 0
2024/07/20 06:44:21 [Info] [1636268745] transport/internet/tcp: dialing TCP to tcp:91.108.56.172:80
2024/07/20 06:44:21 [Debug] [1636268745] transport/internet: dialing to tcp:91.108.56.172:80
2024/07/20 06:44:21 [Info] [1636268745] proxy: Xtls Unpadding new block, content 92 padding 40 command 0
2024/07/20 06:44:21 [Info] [1037059144] proxy/vless/inbound: firstLen = 341
2024/07/20 06:44:21 [Info] [1037059144] proxy/vless/inbound: received request for tcp:[2001:b28:f23f:f005::a]:443
2024/07/20 06:44:21 [Info] [1037059144] app/dispatcher: default route for tcp:[2001:b28:f23f:f005::a]:443
2024/07/20 06:44:21 [Info] [1037059144] transport/internet/tcp: dialing TCP to tcp:[2001:b28:f23f:f005::a]:443
2024/07/20 06:44:21 [Debug] [1037059144] transport/internet: dialing to tcp:[2001:b28:f23f:f005::a]:443
2024/07/20 06:44:21 [Info] [1037059144] proxy: Xtls Unpadding new block, content 237 padding 27 command 0
2024/07/20 06:44:21 [Info] [313388609] proxy/vless/inbound: firstLen = 332
2024/07/20 06:44:21 [Info] [313388609] proxy/vless/inbound: received request for tcp:91.108.56.172:80
2024/07/20 06:44:21 [Info] [313388609] app/dispatcher: default route for tcp:91.108.56.172:80
2024/07/20 06:44:21 [Info] [313388609] transport/internet/tcp: dialing TCP to tcp:91.108.56.172:80
2024/07/20 06:44:21 [Debug] [313388609] transport/internet: dialing to tcp:91.108.56.172:80
2024/07/20 06:44:21 [Info] [313388609] proxy: Xtls Unpadding new block, content 226 padding 41 command 0
2024/07/20 06:44:21 [Info] [313388609] proxy: Xtls Unpadding new block, content 132 padding 107 command 0
2024/07/20 06:44:21 [Info] [3294520442] proxy/vless/inbound: firstLen = 203
2024/07/20 06:44:21 [Info] [3294520442] proxy/vless/inbound: received request for tcp:[2001:b28:f23f:f005::a]:443
2024/07/20 06:44:21 [Info] [3294520442] proxy: Xtls Unpadding new block, content 121 padding 5 command 0
2024/07/20 06:44:21 [Info] [3294520442] app/dispatcher: default route for tcp:[2001:b28:f23f:f005::a]:443
2024/07/20 06:44:21 [Info] [3294520442] transport/internet/tcp: dialing TCP to tcp:[2001:b28:f23f:f005::a]:443
2024/07/20 06:44:21 [Debug] [3294520442] transport/internet: dialing to tcp:[2001:b28:f23f:f005::a]:443
2024/07/20 06:44:21 [Info] [3277150911] proxy/vless/inbound: firstLen = 411
2024/07/20 06:44:21 [Info] [3277150911] proxy/vless/inbound: received request for tcp:91.108.56.172:443
2024/07/20 06:44:21 [Info] [3277150911] app/dispatcher: default route for tcp:91.108.56.172:443
2024/07/20 06:44:21 [Info] [3277150911] proxy: Xtls Unpadding new block, content 173 padding 173 command 0
2024/07/20 06:44:21 [Info] [3277150911] transport/internet/tcp: dialing TCP to tcp:91.108.56.172:443
2024/07/20 06:44:21 [Debug] [3277150911] transport/internet: dialing to tcp:91.108.56.172:443
2024/07/20 06:44:21 [Info] [1565238784] proxy/vless/inbound: firstLen = 351
2024/07/20 06:44:21 [Info] [1565238784] proxy/vless/inbound: received request for tcp:91.108.56.172:443
2024/07/20 06:44:21 [Info] [1565238784] proxy: Xtls Unpadding new block, content 201 padding 85 command 0
2024/07/20 06:44:21 [Info] [1565238784] app/dispatcher: default route for tcp:91.108.56.172:443
2024/07/20 06:44:21 [Info] [1565238784] transport/internet/tcp: dialing TCP to tcp:91.108.56.172:443
2024/07/20 06:44:21 [Debug] [1565238784] transport/internet: dialing to tcp:91.108.56.172:443
2024/07/20 06:44:21 [Info] [3649767900] proxy/vless/inbound: firstLen = 319
2024/07/20 06:44:21 [Info] [3649767900] proxy/vless/inbound: received request for tcp:91.108.56.172:443
2024/07/20 06:44:21 [Info] [3649767900] app/dispatcher: default route for tcp:91.108.56.172:443
2024/07/20 06:44:21 [Info] [3649767900] proxy: Xtls Unpadding new block, content 133 padding 121 command 0
2024/07/20 06:44:21 [Info] [3649767900] transport/internet/tcp: dialing TCP to tcp:91.108.56.172:443
2024/07/20 06:44:21 [Debug] [3649767900] transport/internet: dialing to tcp:91.108.56.172:443
2024/07/20 06:44:21 [Info] [1636268745] proxy/freedom: connection opened to tcp:91.108.56.172:80, local endpoint 
2024/07/20 06:44:21 [Info] [3649767900] proxy: CopyRawConn readv
2024/07/20 06:44:21 [Info] transport/internet/tcp: dialing TCP to tcp:127.0.0.1:40000
2024/07/20 06:44:21 [Debug] transport/internet: dialing to tcp:127.0.0.1:40000
2024/07/20 06:44:21 [Info] [1636268745] proxy: XtlsPadding 275 113 0
2024/07/20 06:44:21 [Info] [1037059144] proxy: XtlsPadding 125 244 0
2024/07/20 06:44:21 [Info] [3294520442] proxy: XtlsPadding 169 74 0
2024/07/20 06:44:21 [Info] [313388609] proxy: XtlsPadding 242 209 0
2024/07/20 06:44:21 [Info] [3277150911] proxy: XtlsPadding 133 185 0
2024/07/20 06:44:21 [Info] [1565238784] proxy: XtlsPadding 153 100 0
2024/07/20 06:44:21 [Info] [3649767900] proxy: XtlsPadding 153 190 0
2024/07/20 06:44:21 [Info] [3277150911] proxy: Xtls Unpadding new block, content 169 padding 49 command 0
2024/07/20 06:44:21 [Info] [3649767900] proxy: Xtls Unpadding new block, content 185 padding 188 command 0
2024/07/20 06:44:21 [Info] [1565238784] proxy: Xtls Unpadding new block, content 121 padding 22 command 0
2024/07/20 06:44:21 [Info] app/proxyman/outbound: app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to find an available destination > common/retry: [dial tcp 127.0.0.1:40000: connect: connection refused] > common/retry: all retry attempts failed
2024/07/20 06:44:21 [Info] app/observatory: the outbound warp-socks5 is dead: GET request failed:app/observatory: outbound failed to relay connection > Get "https://www.google.com/generate_204": io: read/write on closed pipewith outbound handler report underlying connection failed > app/observatory: underlying connection error > app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to find an available destination > common/retry: [dial tcp 127.0.0.1:40000: connect: connection refused] > common/retry: all retry attempts failed
2024/07/20 06:44:21 [Info] [3277150911] proxy: XtlsPadding 89 86 0
2024/07/20 06:44:21 [Info] [3649767900] proxy: XtlsPadding 89 172 0
2024/07/20 06:44:23 [Info] [3294520442] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > context canceled
2024/07/20 06:44:23 [Info] [3294520442] app/proxyman/inbound: failed to close connection > tls: failed to send closeNotify alert (but connection was closed anyway): write unix /dev/shm/xray/xtls.socket->@: write: broken pipe
2024/07/20 06:44:23 [Info] [3649767900] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > context canceled
2024/07/20 06:44:23 [Info] [3649767900] app/proxyman/inbound: failed to close connection > tls: failed to send closeNotify alert (but connection was closed anyway): write unix /dev/shm/xray/xtls.socket->@: write: broken pipe
2024/07/20 06:44:23 [Info] [313388609] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > context canceled
2024/07/20 06:44:23 [Info] [313388609] app/proxyman/inbound: failed to close connection > tls: failed to send closeNotify alert (but connection was closed anyway): write unix /dev/shm/xray/xtls.socket->@: write: broken pipe
2024/07/20 06:44:23 [Info] [1037059144] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > context canceled
2024/07/20 06:44:23 [Info] [1037059144] app/proxyman/inbound: failed to close connection > tls: failed to send closeNotify alert (but connection was closed anyway): write unix /dev/shm/xray/xtls.socket->@: write: broken pipe
2024/07/20 06:44:23 [Info] [3277150911] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > context canceled
2024/07/20 06:44:23 [Info] [3277150911] app/proxyman/inbound: failed to close connection > tls: failed to send closeNotify alert (but connection was closed anyway): write unix /dev/shm/xray/xtls.socket->@: write: broken pipe
2024/07/20 06:44:23 [Info] [1565238784] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > context canceled
2024/07/20 06:44:23 [Info] [1565238784] app/proxyman/inbound: failed to close connection > tls: failed to send closeNotify alert (but connection was closed anyway): write unix /dev/shm/xray/xtls.socket->@: write: broken pipe
2024/07/20 06:44:23 [Info] [1636268745] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > context canceled
2024/07/20 06:44:23 [Info] [1636268745] app/proxyman/inbound: failed to close connection > tls: failed to send closeNotify alert (but connection was closed anyway): write unix /dev/shm/xray/xtls.socket->@: write: broken pipe
2024/07/20 06:44:25 [Info] transport/internet/tcp: REALITY: processed invalid connection
2024/07/20 06:44:26 [Info] transport/internet/tcp: REALITY: processed invalid connection
2024/07/20 06:44:26 [Info] transport/internet/tcp: REALITY: processed invalid connection
2024/07/20 06:44:27 [Info] transport/internet/tcp: REALITY: processed invalid connection
2024/07/20 06:44:27 [Info] transport/internet/tcp: REALITY: processed invalid connection
2024/07/20 06:44:27 [Info] transport/internet/tcp: REALITY: processed invalid connection
2024/07/20 06:44:28 [Info] transport/internet/tcp: REALITY: processed invalid connection
2024/07/20 06:44:28 [Info] transport/internet/tcp: REALITY: processed invalid connection
2024/07/20 06:44:29 [Info] transport/internet/tcp: REALITY: processed invalid connection
2024/07/20 06:44:30 [Info] transport/internet/tcp: REALITY: processed invalid connection
2024/07/20 06:44:38 [Info] transport/internet/tcp: REALITY: processed invalid connection
2024/07/20 06:44:38 [Info] transport/internet/tcp: REALITY: processed invalid connection
2024/07/20 06:44:38 [Info] transport/internet/tcp: REALITY: processed invalid connection
2024/07/20 06:44:38 [Info] transport/internet/tcp: REALITY: processed invalid connection
2024/07/20 06:44:38 [Info] transport/internet/tcp: REALITY: processed invalid connection
2024/07/20 06:44:38 [Info] transport/internet/tcp: REALITY: processed invalid connection
2024/07/20 06:44:38 [Info] transport/internet/tcp: REALITY: processed invalid connection
2024/07/20 06:44:38 [Info] transport/internet/tcp: REALITY: processed invalid connection
2024/07/20 06:44:38 [Info] transport/internet/tcp: REALITY: processed invalid connection
2024/07/20 06:44:38 [Info] transport/internet/tcp: REALITY: processed invalid connection
2024/07/20 06:44:38 [Info] transport/internet/tcp: REALITY: processed invalid connection
2024/07/20 06:44:38 [Info] transport/internet/tcp: REALITY: processed invalid connection
</code></pre></details>

**Comment by phoenixxie0** [comment]
不适用send-proxy-v2参数是可以正常使用的，但是无法传递IP，这样比较麻烦一些

**Comment by donnyxray** [comment]
Use **send-proxy**, not send-proxy-v2.

**Comment by RPRX** [comment]
`acceptProxyProtocol` 写错地方了，不应该写 `realitySettings` 里，去看文档

**Comment by phoenixxie0** [comment]
> Use **send-proxy**, not send-proxy-v2.
> 
> Note that send-proxy does cause occasional errors. See #1873

Use  send-proxy is also not work
