### ISSUE TITLE
[feature-request]splitting routes for splithttp

### ISSUE THREAD

**Issue by Mfire2001** [XTLS/Xray-core#3571]
First of all,a big thanks to all the developers of this project
One of the largest fingerprints a proxy server has is the traffic flow which  the ratio of download and upload is about 1:1
To fix this issue we can use splithttp but with diffrent routes for upload and download
We could have all the uploads via cdn and all the downloads directly to proxy server
using this gfw will see only downloads from our server and (maybe)could assume it is a file server

**Comment by Fangliding** [comment]
想了半天还是不敲英语了
会有的 仍然在讨论中
但是代理服务器到客户端的上行下载流量什么时候是 1:1 了 嘴上说着 fingerprint 以为多砖业最后又闹个笑掉大牙的笑话提issue前过点脑子行不行(
