### ISSUE TITLE
Splithttp alpn http/1.1 doesn't work with CDNs e.g. cloudflare

### ISSUE THREAD

**Issue by internetfreedomir** [XTLS/Xray-core#3573]
Splithttp alpn http/1.1 works directly but not with cdn !

I tested this with many CDNs but it didn't connect .

It only connects directly !

(It connects with CDNs when alpn is h2 so the error is only with http/1.1)

Both server and client are v1.8.21

**Comment by internetfreedomir** [comment]
Also, it doesn't connect with alpn http/1.1 when it is reverse-proxied with a web server like nginx !

**Comment by RPRX** [comment]
**Xray-core 不允许你在选择浏览器指纹时修改 ALPN，所以只有服务端只支持 HTTP/1.1+TLS 时才会协商出 HTTP/1.1**

而 TLS 存在时 SplitHTTP 客户端会默认使用 H2，所以此时你 ALPN 选择 HTTP/1.1 只是指示不要用 H2，并没有修改浏览器指纹

服务端支持 H2 时你不必用 HTTP/1.1，如果你非要用，客户端不能选 fingerprint，需要留空，然后 ALPN 选择 HTTP/1.1

**Comment by internetfreedomir** [comment]
> **Xray-core 不允许你在选择浏览器指纹时修改 ALPN，所以只有服务端只支持 HTTP/1.1+TLS 时才会协商出 HTTP/1.1**
> 
> 而 TLS 存在时 SplitHTTP 客户端会默认使用 H2，所以此时你 ALPN 选择 HTTP/1.1 只是指示不要用 H2，并没有修改浏览器指纹
> 
> 服务端支持 H2 时你不必用 HTTP/1.1，如果你非要用，客户端不能选 fingerprint，需要留空，然后 ALPN 选择 HTTP/1.1

Didn't connect with fingerprint and without fingerprint . I want to use CDNs that only support http/1.1 ! 
So, v1.8.21 does not support http/1.1 + tls because practically what you added cannot be used with cdn !

**Comment by RPRX** [comment]
> Didn't connect with fingerprint and without fingerprint . I want to use CDNs that only support http/1.1 ! So, v1.8.21 does not support http/1.1 + tls because practically what you added cannot be used with cdn !

我不知道为什么会有 CDN 支持 TLS 却只支持 HTTP/1.1，~~或许提供下名字~~

根据目前的代码，客户端 ALPN 选 HTTP/1.1 时内层一定会用 HTTP/1.1，如果是上述 CDN 但用不了，可能 SplitHTTP 不支持它

**Comment by internetfreedomir** [comment]
> > Didn't connect with fingerprint and without fingerprint . I want to use CDNs that only support http/1.1 ! So, v1.8.21 does not support http/1.1 + tls because practically what you added cannot be used with cdn !
> 
> 我不知道为什么会有 CDN 支持 TLS 却只支持 HTTP/1.1，~或许提供下名字~
> 
> 根据目前的代码，客户端 ALPN 选 HTTP/1.1 时内层一定会用 HTTP/1.1，如果是上述 CDN 但用不了，可能 SplitHTTP 不支持它

Maybe there is a problem with the cdn that I am testing Of course, when I realized that it does not connect with Cloudflare, I thought that the problem was with http/1.1 + tls

**Comment by internetfreedomir** [comment]
> **Xray-core 不允许你在选择浏览器指纹时修改 ALPN，所以只有服务端只支持 HTTP/1.1+TLS 时才会协商出 HTTP/1.1**
> 
> 而 TLS 存在时 SplitHTTP 客户端会默认使用 H2，所以此时你 ALPN 选择 HTTP/1.1 只是指示不要用 H2，并没有修改浏览器指纹
> 
> 服务端支持 H2 时你不必用 HTTP/1.1，如果你非要用，客户端不能选 fingerprint，需要留空，然后 ALPN 选择 HTTP/1.1

I checked again and you are right that it works without fingerprint, but this is dangerous to use !

**Comment by internetfreedomir** [comment]
It connects with fingerprint = Android too !
