### ISSUE TITLE
SplitHTTP 服务端直接用 Xray 开 H3 时内存占用高

### ISSUE THREAD

**Issue by kirito201711** [XTLS/Xray-core#3574]
内存消耗非常快，服务器内存很快占用100%，然后cpu也跟着占用100%，然后xray就无法正常工作了

**Comment by kirito201711** [comment]
这是客户端的设置
![屏幕截图 2024-07-22 092103](https://github.com/user-attachments/assets/16c7e2a5-de73-445d-99a8-f3a3ea6704f9)

**Comment by kirito201711** [comment]
这是服务端的
` {
      "listen": null,
      "port": 2083,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "email": "zqnx928v",
            "flow": "",
            "id": "**********************************"
          }
        ],
        "decryption": "none",
        "fallbacks": []
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls",
          "quic",
          "fakedns"
        ],
        "enabled": true,
        "metadataOnly": false,
        "routeOnly": false
      },
      "streamSettings": {
        "network": "splithttp",
        "security": "tls",
        "splithttpSettings": {
          "headers": {},
          "host": "",
          "maxConcurrentUploads": 1000000,
          "maxUploadSize": 8,
          "path": "/"
        },
        "tlsSettings": {
          "alpn": [
            "h2",
            "http/1.1",
            "h3"
          ],
          "certificates": [
            {
              "certificate": [
                "-----BEGIN CERTIFICATE-----",
                "MIIEFTCCAv2gAwIBAgIUQrwizCs9zQAFaEMgKdyzbm+wakAwDQYJKoZIhvcNAQEL",
                "BQAwgagxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH",
                "Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBDbG91ZGZsYXJlLCBJbmMuMRswGQYD",
                "VQQLExJ3d3cuY2xvdWRmbGFyZS5jb20xNDAyBgNVBAMTK01hbmFnZWQgQ0EgMTJm",
                "ZDBjZGQzYTk3Mjk1NjU1MGQ3MWNiNjgxY2E0ZGMwHhcNMjQwNzE5MTM1MzAwWhcN",
                "MzQwNzE3MTM1MzAwWjAiMQswCQYDVQQGEwJVUzETMBEGA1UEAxMKQ2xvdWRmbGFy",
                "ZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALHUu1hhCXTqcH4XAA/I",
                "SVgZWWHX26x9b4spN190C8W5yWTb95c5Mas4uvM6S0Vq7LjfStKiEw72erYKFMP1",
                "or7UbhiTJACxfo+PgzCMpf3LlwpzZ2HCbc817yTcy/TMEVQYRyhmAsn7Wl2j44Ta",
                "tQmXA3EwxAVG4KUs160U5UHREw5twRzj3VT3o5ivwqso6HcOaHMN9uPc5r2JTI6S",
                "O6DGw3oOtS+hiEFLA+rOE360BuhnMyuNhyqqobEG3qdITGRkXQO11LdKmjoeCEYp",
                "r0OQ6aRpHkXTJEmt7d6KJ1wZe4lzMPgVxWab6ZaNIjb/KXYKabmDDBOhOZPm5dqe",
                "/psCAwEAAaOBuzCBuDATBgNVHSUEDDAKBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAA",
                "MB0GA1UdDgQWBBTtZcd9/01GD8+7QLQyri4LAn9ImDAfBgNVHSMEGDAWgBSy51BF",
                "xHYHQgPJqr1KKdZlbY+djzBTBgNVHR8ETDBKMEigRqBEhkJodHRwOi8vY3JsLmNs",
                "b3VkZmxhcmUuY29tLzg2YTE1YTNhLWU2MzMtNDg4Ny04M2FhLTM0Yzc3ZDFiNDNj",
                "YS5jcmwwDQYJKoZIhvcNAQELBQADggEBACy/lDlCKrp1r3DG8vgQjCTpIJ0916Cb",
                "TUpOAwPkQdRVwaovXDBKR7U4oBIYN5I7hZwZ+lOMUWFbqMW6MfwR9npdROvQuuL2",
                "2hyTvg5922k5pEV02LRv3xF+xsJ8NF0M4zodheZ/Ln6xIYHLBKP2T9Do/I7shEQF",
                "ty01sYS6OfHDrXOXsdkZljqYO1MvyljKsBTHo92tcOZWJyd1rDh1wG0LIvgd9GNf",
                "IHX6g81afX0NUNOERtx2snP55PsjLf6UJozpHZpqbNF6NRSET/eYfII2HAgmn5c/",
                "2L7KTxZNGYpMVA+B7rABDez7eEH2CJw8Xg3DAszAo9m1hr0jd6uoq7o=",
                "-----END CERTIFICATE-----",
                ""
              ],
              "key": [
                "-----BEGIN PRIVATE KEY-----",
                "MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCx1LtYYQl06nB+",
                "FwAPyElYGVlh19usfW+LKTdfdAvFuclk2/eXOTGrOLrzOktFauy430rSohMO9nq2",
                "ChTD9aK+1G4YkyQAsX6Pj4MwjKX9y5cKc2dhwm3PNe8k3Mv0zBFUGEcoZgLJ+1pd",
                "o+OE2rUJlwNxMMQFRuClLNetFOVB0RMObcEc491U96OYr8KrKOh3DmhzDfbj3Oa9",
                "iUyOkjugxsN6DrUvoYhBSwPqzhN+tAboZzMrjYcqqqGxBt6nSExkZF0DtdS3Spo6",
                "HghGKa9DkOmkaR5F0yRJre3eiidcGXuJczD4FcVmm+mWjSI2/yl2Cmm5gwwToTmT",
                "5uXanv6bAgMBAAECggEAMOct//9rcNX5yor7rttm5A3QiTopxHUYRB45BoxsolrV",
                "meFt5I3LbWkj7DhnM7dUUwDA3EzKze4VT9NU45C8yRq1DhgEqhYllkgijSrYiQNA",
                "TZTv5K/pr7aGxc3cXrzxtP0aMG9hK/dt4dtseYAFkhYP0cRV25eitnmu8/+PjjoB",
                "j8BKIezGQgR0/70209BNCM6Cm4Ofetsa+ZoD26WpkRNE8lO/0wH2VOA8GcsqVYm5",
                "IvDHr9o4X4Q6cT2MZ7kaHpqhNn98ksbOJLVd/a2rcGiif8BdBBQzP4ZAS6uBuqmd",
                "7q7YhNB3tndI6Nl92Z+qtVajux/RFfWIMLQcBmlY3QKBgQDksWnpnFqaG8R+1CY7",
                "dcGHWsmXSW4SLoTj7hYtTXH9KfdlD/pG9n3KDHZPNi4X6yjRsw1aOMSPYBFDLQ9Y",
                "ndheFcgXTEkGkfYP3xnwytVs9RcYXdPavkLa1qZ+ADXDTb8OoPBLW9sl1NHq9at4",
                "kiKk48frEMTchsCDOWtyJAblFQKBgQDHEJcJiMauG59+vGxmpPw1c5NwosOcUMvX",
                "/PCMUGGaUi3V1klh9gpu07bI1ThsWY2gkg6/IxE8r9J+OGY1tr7uZ1DJCPSw91Ld",
                "jtkSFyvRNZ/EGknTwWMOJHp10G0hHXgN+bzFKGuQfg1N5QHs30F221naX6c1ADsH",
                "gA5PCXqg7wKBgC9KQIx+OH4Fn+xaEk3ZW9uRen4+QPShiflYEl3r1dZ0ByRu2WIz",
                "Nm/Bg/V9TqrDhf1W+Tve4UaEpw0tFC9O9J8AAhBPRgqFxEwj5klUqC2PwObZACYL",
                "keeO237SrEtmmEt+HDJ5HCgGiiH8CykzjtZqA70oCo1PkB+SkBVaPdLBAoGATaYv",
                "BE0SEwA7athdAH0C1GbM8HbNDsCFgy7rNhB0whmkP3FjFo8+6pQzDIv/gmQ8VpIi",
                "pnQrWRzMYuflFra+K4ipfoG70PvomvwJuIDJWsYsF/aZLbyVwwJ/sk0nBG/WUL1F",
                "4TIvIyHIVsYpxhggFRjjJ8eAFbCNVhOhgTsVVokCgYAZfphDfOw50/Sj8eyRRJmL",
                "aSXly/WZVUUsFpOVAGPcisVom14vQgcIFko4rLg/WBSzkFNxaDc/x31rBEFw89IH",
                "aViOaVBk8j7MUF81tkAFNTxNDllLSfG8PRiyP2KRcqup3QNNsRNYDxFqqggi5Dvm",
                "/8RZ9P1hchNBod13oskZFw==",
                "-----END PRIVATE KEY-----",
                ""
              ],
              "ocspStapling": 3600,
              "oneTimeLoading": false,
              "usage": "encipherment"
            }
          ],
          "cipherSuites": "",
          "disableSystemRoot": false,
          "enableSessionResumption": false,
          "maxVersion": "1.3",
          "minVersion": "1.2",
          "rejectUnknownSni": false,
          "serverName": "hkk.fastsamber.cf"
        }
      },
      "tag": "inbound-2083"
    }`

**Comment by Fangliding** [comment]
旧的h3有问题 尝试新版本

**Comment by kirito201711** [comment]
> 旧的h3有问题 尝试新版本

服务端就是最新的1.8.21版本

**Comment by Fangliding** [comment]
客户端呢

**Comment by kirito201711** [comment]
v2rayng是1.8.33，是最新了，v2rayn的core也是最新。

**Comment by Fangliding** [comment]
v2rayn(g)没更新

**Comment by RPRX** [comment]
这个是少有的服务端直接用 Xray 开 H3，~~属于无人区~~，“但更推荐的做法是 **在服务端前套一个反代软件，这样才可以使用 BBR。**”

不过这个 issue 可以因为 [diversity](https://github.com/XTLS/Xray-core/issues/3456#issuecomment-2181861593) 而留着，需要改一下标题

**Comment by RPRX** [comment]
有人能复现的话可以 label 个 bug

**Comment by kirito201711** [comment]
“但更推荐的做法是 在服务端前套一个反代软件，这样才可以使用 BBR。”

 请问应该使用哪种反代软件，具体该如何操作？

**Comment by kirito201711** [comment]
我终于知道我为啥会内存爆炸了，我将下面两个值不小心填反了
"maxUploadSize"
"maxConcurrentUploads"
导致连接数非常高，内存和cpu最后就爆了
