### ISSUE TITLE
Please add the possibility of using http/1.1 with fingerprint to splithttp

### ISSUE THREAD

**Issue by internetfreedomir** [XTLS/Xray-core#3578]
Thanks to all the people who made splithttp.

This protocol is almost complete, but the only problem is that I cannot use http/1.1 + tls with fingerprint ! 
With the ws protocol, the connection is forced to use http/1.1 and it also works with fingerprint ! 

Is it possible to add this to splithttp as well ?

**Comment by RPRX** [comment]
不建议用 HTTP/1.1，除非服务端不支持 H2，为什么服务端提供了 H2 而你却只想用 HTTP/1.1？

**Comment by internetfreedomir** [comment]
> 不建议用 HTTP/1.1，除非服务端不支持 H2，为什么服务端提供了 H2 而你却只想用 HTTP/1.1？

There are 3 important reasons 

1- Iran applies restrictions based on alpn, for example, sometimes grpc connects well and sometimes ws, and now splithttp with h3 and this shows that there are restrictions based on alpn (of course, these restrictions are not fixed and almost It is changed every 1 to 2 months) 

2- We need a complete protocol that can be connected under any conditions! 

3- Some Iranian CDNs support h2 and http/1.1, but splithttp only connects with http/1.1! (h2 doesn't connect with fingerprint or without fingerprint, but http/1.1 connects without fingerprint)

I don't know the structure of china gfw, but I know very well that Iran's filtering system is not static and is constantly changing.

**Comment by internetfreedomir** [comment]
If we want a protocol that cannot be limited by alpn in any way, http/1.1 must also be connected (with fingerprint).

**Comment by internetfreedomir** [comment]
> * I have serious doubts that you are going to get the performance you want if HTTP/1.1 is actually used, regardless of ALPN.
> * Setting ALPN manually compromises the fingerprint itself. Do you think pretending to be Chrome but only sending `http/1.1` is reasonable? Why do you want to camouflage as websocket connection?
> * Please be specific in what you are seeing. Sometimes this protocol is blocked, sometimes the other one, but there are many ways to distinguish protocols, why do you think it is ALPN?
> * As always, PRs are welcome but features like this are not prioritized for the sake of being "complete."

If we consider what you say, then ws and grpc protocol are completely distinguishable because ws = http/1.1 and grpc = h2, and this makes vpn appear based on alpn ! 
So the first xray protocol that cannot be recognized by alpn is splithttp ?
With this setting :
      "alpn": [
            "h3",
            "h2",
            "http/1.1"
          ],

**Comment by internetfreedomir** [comment]
> Identical issue to #3573...

I solved the problem by changing cdn settings and disabling http2 in cdn settings .

Now it connects with fingerprint !
