### ISSUE TITLE
Can h3 be used with [h2, http/1.1] at the same time? (splithttp)

### ISSUE THREAD

**Issue by internetfreedomir** [XTLS/Xray-core#3587]
I set client alpn to :
`      "alpn": [
            "h3",
            "h2",
            "http/1.1"
          ],`
I also set fingerprint to chrome, but always the connection is only with h2, not with h3.

That's why I ask: Can h3 be used with [h2, http/1.1] at the same time? (It means that the server chooses to be h3 or h2 or http/1.1)

**Comment by Fangliding** [comment]
手动指定内部请求版本仅在alpn数组只有一项的时候生效 不然遵循核心自带逻辑

**Comment by internetfreedomir** [comment]
> 手动指定内部请求版本仅在alpn数组只有一项的时候生效 不然遵循核心自带逻辑

please add h3 and h2 and http/1.1 so that the server chooses which one to use.
