### ISSUE TITLE
Using the browser algorithm for selecting the HTTP version for splithttp

### ISSUE THREAD

**Issue by ahmad0489** [XTLS/Xray-core#3591]
ALPN in TCP: In TCP requests, the browser sends a list of supported protocols like HTTP/1.1 and HTTP/2 via ALPN. The server selects one of these protocols, and the connection is established based on that protocol.

ALPN in UDP: For HTTP/3, which is based on QUIC and UDP, the browser uses ALPN in TLS to negotiate and select the HTTP/3 protocol.

Protocol Selection Process:

The browser first establishes a TCP connection and uses ALPN to negotiate whether the server supports HTTP/2.

If the server supports HTTP/2, the browser checks if the server also supports HTTP/3. This is done using the Alt-Svc header or the ALTSVC frame in HTTP/2.

If the server indicates support for HTTP/3, the browser simultaneously establishes a QUIC connection based on UDP. This new connection does not require terminating the TCP connection and can be done in parallel.

If the HTTP/3 connection is successful, the browser may switch to using it and terminate the HTTP/2 connection.

This process allows the browser to efficiently select the best HTTP version for each connection.

**Comment by ahmad0489** [comment]
So, ALPN in a TCP connection includes both HTTP/2 and HTTP/1.1, while in a UDP connection, it only includes HTTP/3. The sequence is as follows: first, a TCP request is sent. If the connection is HTTP/2 and the server indicates that it supports HTTP/3, a QUIC request is then sent.

Using this algorithm in `xray-core` can improve connection quality by offering three options:

`TCP connection only`, which includes HTTP/2 and HTTP/1.1.

`UDP connection only`, which includes HTTP/3.

`Browser algorithm`, which starts with HTTP/2 and switches to HTTP/3 if the server supports it.

**Comment by Fangliding** [comment]
Actually, after discussion, we gave up the ALPN negotiation because it would add to much unnecessary complexity

**Comment by ahmad0489** [comment]
> ~This has already floated around as an idea to match browser behavior more closely, but it is also quite a lot of complexity with unclear payoff.~ what fangliding said. Many clients already have ways to select the most efficient config based on ping, so this selection of protocol can be done by just having multiple configs. Adding more negotiation mechanisms on top also makes it more difficult to debug.
> 
> Right now, not even ALPN negotiation between h1 and h2 works correctly due to limitations in the golang http stack (TLS connections always assume h2) -- I suggest to start there, because that behavior is actually a more likely source of confusion.
> 
> If you need this behavior you can use [browser dialer](https://xtls.github.io/en/config/features/browser_dialer.html) for now, and if this behavior makes a difference in practice (very unlikely in my opinion) then we can talk about adding it to the golang code as well.

This doesn't affect speed or ping. It simply ensures that if the server supports HTTP/3, it will connect using that. If not, it will connect using HTTP/2.
