### ISSUE TITLE
Incorrect ALPN

### ISSUE THREAD

**Issue by hiddify-com** [XTLS/Xray-core#3596]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.

### Version

1.8.21

### Description

When i configure Xray to use ALPN with only http/1.1, clients will still send both HTTP/1.1 and H2 in the ALPN extension during the SSL handshake while i think it should not even that it can not connect with h2 .

![image](https://github.com/user-attachments/assets/546bd99f-13f6-409e-82b5-3b61daa43558)

### Reproduction Method

```
{
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "listen": "127.0.0.1",
        "port": 10808,
        "protocol": "socks",
        "settings": {
            "udp": true
        }
      }
    ],
    "outbounds": [{
        "mux": {
          "concurrency": -1,
          "enabled": false
        },
        "protocol": "vless",
        "settings": {
          "vnext": [
            {
              "address": "",
              "port": 443,
              "users": [
                {
                  "encryption": "none",
                  "flow": "",
                  "id": "",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "splithttp",
          "security": "tls",
          "splithttpSettings": {
            "host": "",
            "path": "/split"
          },
          "tlsSettings": {
            "allowInsecure": false,
            "alpn": [
              "http/1.1"
            ],
            "fingerprint": "chrome",
            "serverName": ""
          }
        },
        "tag": "def tls splithttp direct vless"
      }
    }]
  }
```

### Client config

<details><pre><code>

{
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "listen": "127.0.0.1",
        "port": 10808,
        "protocol": "socks",
        "settings": {
            "udp": true
        }
      }
    ],
    "outbounds": [{
        "mux": {
          "concurrency": -1,
          "enabled": false
        },
        "protocol": "vless",
        "settings": {
          "vnext": [
            {
              "address": "",
              "port": 443,
              "users": [
                {
                  "encryption": "none",
                  "flow": "",
                  "id": "",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "splithttp",
          "security": "tls",
          "splithttpSettings": {
            "host": "",
            "path": "/split"
          },
          "tlsSettings": {
            "allowInsecure": false,
            "alpn": [
              "http/1.1"
            ],
            "fingerprint": "chrome",
            "serverName": ""
          }
        },
        "tag": "def tls splithttp direct vless"
      }
    }]
  }

</code></pre></details>

### Server config

<details><pre><code>
not related
</code></pre></details>

### Client log

<details><pre><code>
not related
</code></pre></details>

### Server log

![image](https://github.com/user-attachments/assets/791bc2eb-530c-4a5f-addf-6d4870907a61)

<details><pre><code>
not related
</code></pre></details>

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/issues/3573#issuecomment-2241934194
https://github.com/XTLS/Xray-core/pull/3583#issuecomment-2246146466

**Comment by Fangliding** [comment]
`"fingerprint"` will override alpn

**Comment by RPRX** [comment]
@Fangliding https://github.com/XTLS/Xray-core/pull/3583#issuecomment-2246230130

**Comment by Fangliding** [comment]
> @Fangliding [#3583 (comment)](https://github.com/XTLS/Xray-core/pull/3583#issuecomment-2246230130)

OK检查了一下其实其他东西也会被覆盖 都加进去了（其实就是copyConfig函数没有的东西
