### ISSUE TITLE
关于 HTTP 代理指定 Host 请求头的问题

### ISSUE THREAD

**Issue by xNyapAe3** [XTLS/Xray-core#3597]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了issues，没有发现已提出的类似问题。

### 版本

1.8.21

### 描述

通过 IP 的形式访问某网站（ http://1.2.3.4 ），并指定 Host 请求头（test.example.com），直接访问，响应正常；走 HTTP 代理响应出错；走 SOCKS 代理也正常。查看 error.log，发现走 HTTP 代理时，Host 显示是 1.2.3.4，而不是指定的 test.example.com。

### 重现方式

- 直接访问（正常）
```bash
curl -sv 'http://1.2.3.4/abc.html' \
 -H 'Host: test.example.com'
```
\> GET /abc.html HTTP/1.1
\> Host: test.example.com
\> User-Agent: curl/8.4.0
\> Accept: */*
\> 
< HTTP/1.1 200 OK
< Server: nginx
< Date: Fri, 26 Jul 2024 09:01:44 GMT
< Content-Type: application/vnd.apple.mpegurl
< Content-Length: 1688
< Connection: keep-alive
< Host-Ip: 1.2.3.4
< Cache-Control: max-age=2
< Age: 0
< 
...

- HTTP 代理（报错）
```bash
curl -sv 'http://1.2.3.4/abc.html' \
 -x 'http://127.0.0.1:2080' \
 -H 'Host: test.example.com'
```
\*   Trying 127.0.0.1:2080...
\* Connected to 127.0.0.1 (127.0.0.1) port 2080
\> GET /abc.html HTTP/1.1
\> Host: test.example.com
\> User-Agent: curl/8.4.0
\> Accept: */*
\> Proxy-Connection: Keep-Alive
\> 
< HTTP/1.1 403 Forbidden
< Content-Length: 147
< Connection: keep-alive
< Content-Type: text/html
< Date: Fri, 26 Jul 2024 09:06:48 GMT
< Keep-Alive: timeout=4
< No_service: 1
< Proxy-Connection: keep-alive
< Server: nginx
< 
......

- SOCKS 代理（正常）
```bash
curl -sv 'http://1.2.3.4/abc.html' \
 -x 'socks5://127.0.0.1:2081' \
 -H 'Host: test.example.com'
```
......

另外，也对照通过 [mitmproxy](https://github.com/mitmproxy/mitmproxy) 代理访问，响应正常，并且请求地址显示是 http://test.example.com/abc.html

### 客户端配置

<details><pre><code>
{
    "log": {
        "loglevel": "info",
        "access": "log/access.log",
        "error": "log/error.log"
    },
    "inbounds": [
        {
            "port": 2080,
            "listen": "127.0.0.1",
            "protocol": "http",
            "tag": "test-http"
        },
        {
            "port": 2081,
            "listen": "127.0.0.1",
            "protocol": "socks",
            "tag": "test-socks"
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "settings": {},
            "tag": "direct"
        }
    ],
    "routing": {
        "domainStrategy": "IPOnDemand",
        "rules": [
            {
                "type": "field",
                "inboundTag": [
                    "test-socks",
                    "test-http"
                ],
                "outboundTag": "direct"
            }
        ]
    }
}
</code></pre></details>

### 服务端配置

<details><pre><code>
无
</code></pre></details>

### 客户端日志

<details><pre><code>
2024/07/26 17:05:11 [Debug] app/log: Logger started
2024/07/26 17:05:11 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:2080
2024/07/26 17:05:11 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:2081
2024/07/26 17:05:11 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:2080
2024/07/26 17:05:11 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:2081
2024/07/26 17:05:11 [Warning] core: Xray 1.8.21 started
2024/07/26 17:06:48 [Info] [3353614455] proxy/http: request to Method [GET] Host [1.2.3.4] with URL [http://1.2.3.4/abc.html]
2024/07/26 17:06:48 [Info] [3353614455] app/dispatcher: taking detour [direct] for [tcp:1.2.3.4:80]
2024/07/26 17:06:48 [Info] [3353614455] transport/internet/tcp: dialing TCP to tcp:1.2.3.4:80
2024/07/26 17:06:48 [Debug] [3353614455] transport/internet: dialing to tcp:1.2.3.4:80
2024/07/26 17:06:48 [Info] [3353614455] proxy/freedom: connection opened to tcp:1.2.3.4:80, local endpoint 192.168.1.2:57869, remote endpoint 1.2.3.4:80
2024/07/26 17:06:48 [Info] [3353614455] proxy: CopyRawConn readv
2024/07/26 17:06:48 [Info] [3353614455] app/proxyman/inbound: connection ends > proxy/http: failed to read http request > EOF
2024/07/26 17:18:23 [Info] [2280141223] proxy/socks: TCP Connect request to tcp:1.2.3.4:80
2024/07/26 17:18:23 [Info] [2280141223] app/dispatcher: taking detour [direct] for [tcp:1.2.3.4:80]
2024/07/26 17:18:23 [Info] [2280141223] transport/internet/tcp: dialing TCP to tcp:1.2.3.4:80
2024/07/26 17:18:23 [Debug] [2280141223] transport/internet: dialing to tcp:1.2.3.4:80
2024/07/26 17:18:23 [Info] [2280141223] proxy/freedom: connection opened to tcp:1.2.3.4:80, local endpoint 192.168.1.2:61452, remote endpoint 1.2.3.4:80
2024/07/26 17:18:23 [Info] [2280141223] proxy: CopyRawConn readv
2024/07/26 17:18:24 [Info] [2280141223] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
</code></pre></details>

### 服务端日志

<details><pre><code>
无
</code></pre></details>

**Comment by Fangliding** [comment]
根据http代理的定义 http代理服务端将从客户端请求的 GET http://xxx.com 获取目标并写入实际传出的host头 curl将这个1.2.3.4放进了GET目标 xray自然这么传出 用host参数来指定域名只是构建一个这样的http请求的小把戏 URL在很多其他地方会用到 只改host头并不完美 再举个例子你用https这样就不通了因为curl还需要用链接里的域名来传出SNI以及验证证书
如果你真的需要为某个域名指定IP 请用 resolve参数
