### ISSUE TITLE
reality间歇性中断，然后自动恢复

### ISSUE THREAD

**Issue by toyo2333** [XTLS/Xray-core#3605]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了issues，没有发现已提出的类似问题。

### 版本

最新版

### 描述

1、docker部署的
2、同样的部署在另外2台vps上没问题,客户端使用的是clash.meta
3、在当前这台vps上今天就开始比较常见的出现间歇中断，大概几分钟后恢复。（昨天前天都没有问题）
4、配置是偷其他站，可以排除其他站本身的故障问题，在出问题的vps上换了2个域名都存在间歇性中断

出现中断前后会有这种日志
```
app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > context canceled
```

然后出现过一些奇怪的ip用错误域名的请求，比如记录到这个：
```
REALITY remoteAddr: 124.221.88.165:34398
REALITY remoteAddr: 124.221.88.165:34398        forwarded SNI: visa.cn
REALITY remoteAddr: 124.221.88.165:34398        hs.c.handshakeStatus: false
2024/07/27 23:18:07 [Info] transport/internet/tcp: REALITY: processed invalid connection
```
看这IP居然是CNNIC的~ 很奇怪

还有这个

```
REALITY remoteAddr: 20.236.248.238:55530
REALITY remoteAddr: 20.236.248.238:55530        forwarded SNI: 
REALITY remoteAddr: 20.236.248.238:55530        hs.c.handshakeStatus: false
2024/07/27 23:22:33 [Info] transport/internet/tcp: REALITY: processed invalid connection
```

可能是什么原因？这是出现了bug么？比如xray在处理 REALITY: processed invalid connection 出现了阻塞（看上去就像是堵住了），然后恢复的时候看到日志里有 processed invalid connection

### 重现方式

只能在一台机器上出现，某天开始重复出现，几分钟一次。

### 客户端配置

N/A

### 服务端配置

N/A

### 客户端日志

N/A

### 服务端日志

N/A

**Comment by charley008** [comment]
> 解决了

怎么解决的？我好像也遇到过
