### ISSUE TITLE
1.8.23 SplitHTTP 引入 scMinPostsIntervalMs 等选项参数配置为字符串 "10-50" 的形式时，在android15系统上不能启动

### ISSUE THREAD

**Issue by wansenlyt** [XTLS/Xray-core#3615]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了issues，没有发现已提出的类似问题。

### 版本

1.8.23

### 描述

抄VLESS-TLS-SplitHTTP-H3的示例，当配置以下参数为区间时，不能在android15系统上启动，
如：
......
"scMaxEachPostBytes": 500000-1000000,
"scMaxConcurrentPosts": 50-100,
"scMinPostsIntervalMs": 30-50
......
然后给参数加上引号也是不能启动
如：
......
"scMaxEachPostBytes": “500000-1000000”,
"scMaxConcurrentPosts": “50-100”,
"scMinPostsIntervalMs": “30-50”
......

同样的配置将上面三个选项删除，则在android15系统上的客户端可正常启动。

### 重现方式

......
"scMaxEachPostBytes": 500000-1000000,
"scMaxConcurrentPosts": 50-100,
"scMinPostsIntervalMs": 30-50
......

### 客户端配置

抄VLESS-TLS-SplitHTTP-H3的示例

{
    "inbounds": [
        {
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls",
                    "quic"
                ]
            },
            "port": 10808,
            "listen": "127.0.0.1",
            "protocol": "socks",
            "settings": {
                "udp": true
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "example.com", // Change to your domain.
                        "port": 443,
                        "users": [
                            {
                                "id": "UUID", // Change to your UUID.
                                "encryption": "none"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "splithttp",
                "security": "tls",
                "splithttpSettings": {
                    "path": "/splithttp",
                    "host": "example.com", // Change to your domain.
                    "scMaxEachPostBytes": 500000-1000000,
                    "scMaxConcurrentPosts": 50-100,
                    "scMinPostsIntervalMs": 30-50
                },
                "tlsSettings": {
                    "serverName": "example.com", // Change to your domain.
                    "alpn": [
                        "h3"
                    ]
                }
            }
        }
    ]
}

### 服务端配置

抄VLESS-TLS-SplitHTTP-H3的示例，服务端未配置上述三个选项，即保持默认。

### 客户端日志

未提供

### 服务端日志

未提供

**Comment by Fangliding** [comment]
config写的都是直引号 ""
看看你写的啥玩意 “”

**Comment by wyx2685** [comment]
@wansenlyt 太过于end user

**Comment by Fangliding** [comment]
我自己测试没问题 你又不提供日志
