### ISSUE TITLE
1.8.23 SplitHTTP 引入 scMinPostsIntervalMs 等选项，参数配置为字符串 "10-50" 的形式时，在android15系统上不能启动

### ISSUE THREAD

**Issue by wansenlyt** [XTLS/Xray-core#3616]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了issues，没有发现已提出的类似问题。

### 版本

1.8.23

### 描述

抄VLESS-TLS-SplitHTTP-H3的示例，当配置以下参数为区间时，不能在android15系统上启动，
如：
......
"scMaxEachPostBytes": 500000-1000000,
"scMaxConcurrentPosts": 50-100,
"scMinPostsIntervalMs": 30-50
......
然后给参数加上引号也是不能启动
如：
......
"scMaxEachPostBytes": "500000-1000000",
"scMaxConcurrentPosts": "50-100",
"scMinPostsIntervalMs": "30-50"
......

同样的配置将上面三个选项删除，则在android15系统上的客户端可正常启动。

### 重现方式

......
"scMaxEachPostBytes": 500000-1000000,
"scMaxConcurrentPosts": 50-100,
"scMinPostsIntervalMs": 30-50
......

### 客户端配置

......
{
"protocol": "vless",
"settings": {
"vnext": [
{
"address": "XXX.com",
"port": 443,
"users": [
{
"id": "XXX",
"encryption": "none"
}
]
}
]
},
"streamSettings": {
"network": "splithttp",
"security": "tls",
"splithttpSettings": {
"path": "/split", // 与服务端一致
"host": "XXX.com", // 若"address": "" 中填的是VPS的IP，此处必须填Nginx配置中server_name的值，否则会因在Nginx配置中启用了ssl_reject_handshake而连接失败
"scMaxEachPostBytes": "500000-1000000", // 上传分块的最大大小，单位为字节，默认值为1000000,即1MB
"scMaxConcurrentPosts": "30-100", // 单个连接上传post的最大并发数，默认为100
"scMinPostsIntervalMs": "30-50", // 仅客户端，发起POST上传请求的最小间隔, 默认值为30
"noSSEHeader": false
},
"tlsSettings": {
"serverName": "XXX.com",
"fingerprint": "chrome",
"alpn": [
"h3"
]
}
}
},
......

### 服务端配置

抄VLESS-TLS-SplitHTTP-H3的示例，服务端未配置上述三个选项，即保持默认。

### 客户端日志

未提供

### 服务端日志

未提供

**Comment by LOVECHEN** [comment]
用 `30` 或者 `50` 不是 `30-50` 其他的value一样 , 错误日志不是会明确提示你的吗？
