### ISSUE TITLE
求解：关于透明代理的工作逻辑，也许与Fullcone相关

### ISSUE THREAD

**Issue by Bearljj** [XTLS/Xray-core#362]
我在软路由上架设了透明代理模式的Xray，服务端与软路由均为1.3.1；如果直接连接软路由，其他应用均工作正常，但是Netflix无法访问，此时如果通过socks指向软路由中的Xray则也可以正常使用netflix；如果再在软路由下面架设一个路由，二级路由的wan口口与软路由在同一个lan中，网关及DNS均指向软路由，客户机连到二级路由的wifi上则可以成功访问netflix。具体的原因有没有大佬可以解惑呢。。。。。。。

**Comment by azzvx** [comment]
你做了UDP的透明代理了么？
做了的话需要在`iptables`里`PREROUTING`的规则链在`-p udp -j TPROXY`之前的位置添加一条 `iptables -t mangle -A XRAY -j RETURN -d $WAN_IP`，避免UDP回环。`$WAN_IP`指你的WAN口获取的IP。
如果你是OpenWRT，可以用`WAN_IP=$(ifstatus wan | jsonfilter -e '@["ipv4-address"][0].address')`自动获取。

**Comment by Bearljj** [comment]
> 你做了UDP的透明代理了么？
> 做了的话需要在`mangle`表`PREROUTING`里的规则链中，在`-p udp -j TPROXY`之前的位置添加一条 `iptables -t mangle -A XRAY -j RETURN -d $WAN_IP`，避免UDP回环。`$WAN_IP`指你的WAN口获取的IP。
> 如果你是OpenWRT，可以用`WAN_IP=$(ifstatus wan | jsonfilter -e '@["ipv4-address"][0].address')`自动获取。

感谢回复，我的软路由是副路由，并没有WAN口，所以应该不是回环问题，重点在于之前如果直连软路由网飞不能用，或者用一会儿就掉；而挂在再下面一级路由下面就没事儿；另外，现在两端都升级了1.4，使用了FakeDNS之后可以访问网飞了，但是登陆的时候非常慢，登录后基本正常；细节上，如果直接使用软路由透明网关使用代码调用浏览器去生成key的话无法进入登陆页面，而使用socks代理则完全正常，感觉底层工作逻辑还是有些细微区别的

**Comment by azzvx** [comment]
> > 你做了UDP的透明代理了么？
> > 做了的话需要在`mangle`表`PREROUTING`里的规则链中，在`-p udp -j TPROXY`之前的位置添加一条 `iptables -t mangle -A XRAY -j RETURN -d $WAN_IP`，避免UDP回环。`$WAN_IP`指你的WAN口获取的IP。
> > 如果你是OpenWRT，可以用`WAN_IP=$(ifstatus wan | jsonfilter -e '@["ipv4-address"][0].address')`自动获取。
> 
> 感谢回复，我的软路由是副路由，并没有WAN口，所以应该不是回环问题，重点在于之前如果直连软路由网飞不能用，或者用一会儿就掉；而挂在再下面一级路由下面就没事儿；另外，现在两端都升级了1.4，使用了FakeDNS之后可以访问网飞了，但是登陆的时候非常慢，登录后基本正常；细节上，如果直接使用软路由透明网关使用代码调用浏览器去生成key的话无法进入登陆页面，而使用socks代理则完全正常，感觉底层工作逻辑还是有些细微区别的

如果你是拿软路由拨号的，下面的估计对你有帮助，不是的话不用看了。
`WAN口`实际是`WAN接口`的意思，不是物理意义上的WAN网口。`WAN_IP`一般指你获得的拨号获得的公网IP。
你不在iptables对公网IP做处理，那么UDP就会形成回环。你开Xray的access log，会看到一连串`[公网IP:xxxx] -> [公网IP:xxxx]`的记录。
Socks代理正常是UDP流量被Socks代理代理了，然后走了TCP的流量(vless或vmess)。

**Comment by Bearljj** [comment]
> > > 你做了UDP的透明代理了么？
> > > 做了的话需要在`mangle`表`PREROUTING`里的规则链中，在`-p udp -j TPROXY`之前的位置添加一条 `iptables -t mangle -A XRAY -j RETURN -d $WAN_IP`，避免UDP回环。`$WAN_IP`指你的WAN口获取的IP。
> > > 如果你是OpenWRT，可以用`WAN_IP=$(ifstatus wan | jsonfilter -e '@["ipv4-address"][0].address')`自动获取。
> > 
> > 
> > 感谢回复，我的软路由是副路由，并没有WAN口，所以应该不是回环问题，重点在于之前如果直连软路由网飞不能用，或者用一会儿就掉；而挂在再下面一级路由下面就没事儿；另外，现在两端都升级了1.4，使用了FakeDNS之后可以访问网飞了，但是登陆的时候非常慢，登录后基本正常；细节上，如果直接使用软路由透明网关使用代码调用浏览器去生成key的话无法进入登陆页面，而使用socks代理则完全正常，感觉底层工作逻辑还是有些细微区别的
> 
> 如果你是拿软路由拨号的，下面的估计对你有帮助，不是的话不用看了。
> `WAN口`实际是`WAN接口`的意思，不是物理意义上的WAN网口。`WAN_IP`一般指你获得的拨号获得的公网IP。
> 你不在iptables对公网IP做处理，那么UDP就会形成回环。你开Xray的access log，会看到一连串`[公网IP:xxxx] -> [公网IP:xxxx]`的记录。
> Socks代理正常是UDP流量被Socks代理代理了，然后走了TCP的流量(vless或vmess)。

感谢回复，我明白你说的那个逻辑，我的环境里软路由是旁路副路由，并不是主路由，拨号是在主路由上完成的；现在的问题不在这个地方，重点是其他的应用都正常，就是网飞比较特殊。之前有个帖子说好像subnet会把 udp转成TCP，udp无法嗅探，我再研究一下。
