### ISSUE TITLE
1.8.21后反向代理功能有问题

### ISSUE THREAD

**Issue by Yochee** [XTLS/Xray-core#3620]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了issues，没有发现已提出的类似问题。

### 版本

1.8.21/1.8.23

### 描述

虽然反向代理估计是个冷门功能，但从v2ray时代一路用到现在，用于公司电脑的内网穿透，一直很稳定...更新1.8.21后，在没改变配置文件的情况下突然不好用了，症状是bridge端重启后会连不上portal。老版本有时也有这个情况，但是重启portal就好了，新版重启portal后要等很久才能随缘连上

### 重现方式

1.8.21后重启bridge端xray，portal端无法联通bridge端。重启portal端xray，有时还是无法联通。

### 客户端配置

<details><pre><code>
{
  "reverse": {
    "portals": [{
      "tag": "reverse",
      "domain": "office.my.domain"
    }]
  },
  "inbound": {
    "tag": "home"
  },
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [{
      "ip": ["172.16.0.0/24"],
      "outboundTag": "reverse"
    },{
      "inboundTag": ["home"],
      "domain": "full:office.my.domain",
      "outboundTag": "reverse"
    }]
  }
}
</code></pre></details>

### 服务端配置

<details><pre><code>
{
  "reverse": {
    "bridges": [{
      "tag": "reverse",
      "domain": "office.my.domain"
    }]
  },
  "outbounds": [{
    "tag": "direct"
  },{
    "tag": "home"
  }],
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [{
      "inboundTag": ["reverse"],
      "domain":["full:office.my.domain"],
      "outboundTag": "home"
    }]
  }
}
</code></pre></details>

### 客户端日志

<details><pre><code>
[Info] [1891685979] proxy/vless/inbound: firstLen = 408
[Info] [1891685979] proxy/vless/inbound: received request for tcp:172.16.0.1:80
[Info] [1891685979] app/dispatcher: taking detour [reverse] for [tcp:172.16.0.1:80]
[Info] [1891685979] app/reverse: failed to process reverse connection > app/reverse: empty worker list
[Info] [1891685979] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > io: read/write on closed pipe
</code></pre></details>

### 服务端日志

<details><pre><code>
[Info] app/dispatcher: taking detour [home] for [tcp:office.my.domain:0]
[Info] proxy/vless/outbound: tunneling request to tcp:office.my.domain:0 via home.my.domain:443
</code></pre></details>

**Comment by Fangliding** [comment]
1.8.20是好的么
以及日志

**Comment by Yochee** [comment]
> 1.8.20是好的么 以及日志

我从1.8.13更新到1.8.21的，冲着h3过cdn的功能升级的，1.8.20没试过
日志...有点乱，我回家整理下贴上来

**Comment by Yochee** [comment]
> 1.8.20是好的么 以及日志

已更新日志，看起来是portal端出了问题：app/reverse: failed to process reverse connection > app/reverse: empty worker list

**Comment by Fangliding** [comment]
具体 出现问题的 版本
这块代码应该是几年没人动的 如果坏了的话很奇怪

**Comment by Yochee** [comment]
> 具体 出现问题的 版本 这块代码应该是几年没人动的 如果坏了的话很奇怪

周末我各个版本折腾下找一找，这功能不知道用的人多不多，对我还挺重要的...

**Comment by Jinnrry** [comment]
+1 同样问题，我是docker compose部署，dockerfile，配置文件等等全部没变更的情况下，仅仅是docker comopose pull升级了一下镜像版本，升级后也是偶发出现这个问题。

**Comment by mclovin-2k** [comment]
我天天用反向代理  没发现问题

**Comment by Yochee** [comment]
> 我天天用反向代理 没发现问题 你这个配置写的明显不对 Server端应该是 portals，Client 端才是 bridges

server和portal，client和bridge又没有明确对应关系

**Comment by Yochee** [comment]
> Please figure out which version introduced your problem. It is probably not 1.8.21 but some older version.

I'll update test log with earlier versions later today

**Comment by mclovin-2k** [comment]
> > 我天天用反向代理 没发现问题 你这个配置写的明显不对 Server端应该是 portals，Client 端才是 bridges
> 
> server和portal，client和bridge又没有明确对应关系

当然有对应关系了。
建议你去仔细看看文档。

**Comment by Yochee** [comment]
> > > 我天天用反向代理 没发现问题 你这个配置写的明显不对 Server端应该是 portals，Client 端才是 bridges
> > 
> > 
> > server和portal，client和bridge又没有明确对应关系
> 
> 当然有对应关系了。 建议你去仔细看看文档。

偏题了，不想在这怼你，你下吧

**Comment by Jinnrry** [comment]
现象和OP说的完全一致，因为人不在内网机器旁边，不敢随便改配置抓日志，重启后能不能连上真的是随缘。前几天我升级到了1.8.23，这几天没有出现断联，但是我看release log也没有相关改动。

贴一下我的配置文件

内网服务器：
<details><pre><code>
{
  "log": {
    "loglevel": "debug"
  },
  "reverse": {
    "bridges": [
      {
        "tag": "bridge",
        "domain": "reverse.proxy"
      }
    ]
  },
  "outbounds": [
    {
      "tag": "interconn",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "jxxx",
            "port": 8443,
            "users": [
              {
                "id": "xxxx",
                "encryption": "none",
                "flow": "xtls-rprx-vision"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "tls",
        "tlsSettings": {
          "serverName": "xxxx",
          "allowInsecure": false,
          "fingerprint": "chrome"
        }
      }
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "out"
    }
  ],
  "routing": {
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "bridge"
        ],
        "domain": [
          "full:reverse.proxy"
        ],
        "outboundTag": "interconn"
      },
      {
        "type": "field",
        "inboundTag": [
          "bridge"
        ],
        "outboundTag": "out"
      }
    ]
  }
}

</code></pre></details>
公网服务器
<details><pre><code>
{
  "log": {
    "loglevel": "warning"
  },
  "reverse": {
    "portals": [
      {
        "tag": "portal",
        "domain": "reverse.proxy"
      }
    ]
  },
  "inbounds": [
    {
      "tag": "external",
      "port": 443,
      "protocol": "vless",
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      },
      "settings": {
        "clients": [
          {
            "id": "xxxxx",
            "flow": "xtls-rprx-vision",
            "level": 0,
            "email": "@external"
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "dest": "/unix/h2.sock",
            "xver": 2
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "tls",
        "tlsSettings": {
          "alpn": [
            "h2",
            "http/1.1"
          ],
          "certificates": [
            {
              "certificateFile": "/ssl/public.crt",
              "keyFile": "/ssl/private.key"
            }
          ]
        }
      }
    },
    {
      "tag": "interconn",
      "port": 8443,
      "protocol": "vless",
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      },
      "settings": {
        "clients": [
          {
            "id": "xxxxx",
            "flow": "xtls-rprx-vision",
            "level": 0,
            "email": "@external"
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "dest": "/unix/h2.sock",
            "xver": 2
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "tls",
        "tlsSettings": {
          "alpn": [
            "h2",
            "http/1.1"
          ],
          "certificates": [
            {
              "certificateFile": "/ssl/public.crt",
              "keyFile": "/ssl/private.key"
            }
          ]
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    },
    {
      "protocol": "socks",
      "settings": {
        "servers": [
          {
            "address": "127.0.0.1",
            "port": 40000
          }
        ]
      },
      "tag": "wrap"
    }
  ],
  "routing": {
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "external"
        ],
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "portal"
      },
      {
        "type": "field",
        "domain": [
          "geosite:cn"
        ],
        "outboundTag": "wrap"
      },
      {
        "type": "field",
        "inboundTag": [
          "external"
        ],
        "domain": [
          "ipinfo.io",
          "openai.com",
          "spotify.com"
        ],
        "outboundTag": "wrap"
      },
      {
        "type": "field",
        "inboundTag": [
          "interconn"
        ],
        "domain": [],
        "outboundTag": "portal"
      },
      {
        "type": "field",
        "port": "0-65535",
        "outboundTag": "direct"
      }
    ]
  }
}

</code></pre></details>

**Comment by Yochee** [comment]
抱歉，看起来是我搞错了原因，折腾几天尝试不同版本的server和client的排列组合后，发现都有这个问题，说明不是版本问题。最后想起来前段时间换了反向代理隧道的协议，从vless+tcp+vision+reality换成了vless+h2+reality，换回去后就好了。不负责任猜测可能和h2自带的mux有关

**Comment by mclovin-2k** [comment]
> > > > 我天天用反向代理 没发现问题 你这个配置写的明显不对 Server端应该是 portals，Client 端才是 bridges
> > > 
> > > 
> > > server和portal，client和bridge又没有明确对应关系
> > 
> > 
> > 当然有对应关系了。 建议你去仔细看看文档。
> 
> 偏题了，不想在这怼你，你下吧

哈哈 你自己不会配置，又不看文档
在这里提这种无效 Issue 存粹是浪费大家的时间
我用H2/GRPC反向代理根本没问题，甚至我都可以搭配 CDN +GRPC 反向代理
不过我是不会帮你分析原因的，RTFM
