### ISSUE TITLE
识别 SOCKS4A 请求中可能的 IP 地址以提高稳健性

### ISSUE THREAD

**Issue by ckwastra** [XTLS/Xray-core#3622]
### 完整性要求

- [x] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了issues，没有发现已提出的类似问题。

### 版本

1.8.23

### 描述

作为 SOCKS4 协议的扩展，[SOCKS4A](https://www.openssh.com/txt/socks4a.protocol) 允许客户端以特殊格式在请求中使用域名作为目标地址，以便服务端解析域名。然而，即使目标是 IP 地址，某些客户端仍然会使用此格式发送请求（例如 [cURL](https://github.com/curl/curl/blob/c3fe2dd25cf1e9c1c458a6a57a5be00c5c0cf575/lib/socks.c#L431-L447) 和 [Gecko](https://github.com/mozilla/gecko-dev/blob/354c834a39dc9d77cc95957ba0249ec173fe392a/netwerk/socket/nsSOCKSIOLayer.cpp#L656-L674)）。这导致 Xray 错误地将其中的 IP 地址视为域名，并在进行路由规则匹配时指向错误的出口：

https://github.com/XTLS/Xray-core/blob/4c82ef8a1b79a609efd3f7ba947896b6f8a2917c/proxy/socks/protocol.go#L72-L78

尽管这听起来更像是客户端实现的问题，主动识别请求中的地址类型也能提高 Xray 的稳健性。需要注意的是，[Gecko](https://github.com/mozilla/gecko-dev/blob/354c834a39dc9d77cc95957ba0249ec173fe392a/netwerk/socket/nsSOCKSIOLayer.cpp#L843-L854) 发送的 SOCKS5 请求同样存在上述问题，但由于 Xray 在处理 SOCKS5 请求时能够识别可能的 IP 地址，因此能够正确处理：

https://github.com/XTLS/Xray-core/blob/4c82ef8a1b79a609efd3f7ba947896b6f8a2917c/common/protocol/address.go#L213-L218

### 重现方式

1. 使用以下配置启动 Xray：
   ```
   xray run -c config.json
   ```
2. 使用 cURL 向其发送 SOCKS4A 请求，目标为 192.168.1.1：
   ```
   curl -x socks4a://127.0.0.1:1081 192.168.1.1
   ```
3. cURL 返回以下结果，即连接被错误地关闭：
   ```
   curl: (52) Empty reply from server
   ```

### 客户端配置

<details>

```json
{
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 1081,
      "protocol": "socks"
    }
  ],
  "log": {
    "loglevel": "debug",
    "dnsLog": true
  },
  "outbounds": [
    {
      "protocol": "freedom"
    },
    {
      "protocol": "blackhole",
      "tag": "block"
    }
  ],
  "routing": {
    "rules": [
      {
        "domain": [
          "full:192.168.1.1"
        ],
        "outboundTag": "block"
      }
    ]
  }
}
```

</details>

### 服务端配置

N/A

### 客户端日志

<details>

```
Xray 1.8.23 (Xray, Penetrates Everything.) Custom (go1.22.5 darwin/amd64)
A unified platform for anti-censorship.
2024/08/01 23:17:26 [Info] infra/conf/serial: Reading config: config.json
2024/08/01 23:17:26 [Debug] app/log: Logger started
2024/08/01 23:17:26 [Debug] app/router: MphDomainMatcher is enabled for 1 domain rule(s)
2024/08/01 23:17:26 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:1081
2024/08/01 23:17:26 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1081
2024/08/01 23:17:26 [Warning] core: Xray 1.8.23 started
2024/08/01 23:17:35 [Info] [2709202480] proxy/socks: TCP Connect request to tcp:192.168.1.1:80
2024/08/01 23:17:35 [Info] [2709202480] app/dispatcher: taking detour [block] for [tcp:192.168.1.1:80]
2024/08/01 23:17:35 tcp:127.0.0.1:64492 accepted tcp:192.168.1.1:80 [block]
2024/08/01 23:17:35 [Info] [2709202480] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
```

</details>

### 服务端日志

N/A

**Comment by RPRX** [comment]
感谢报告问题，打算把 Socks4(a) 删掉：https://github.com/XTLS/Xray-core/discussions/1967

**Comment by Fangliding** [comment]
顺便提一句Chrome发送的socks5请求也有这种问题

> 感谢报告问题，打算把 Socks4(a) 删掉：#1967

Windows目前还只支持socks4 还是留着吧 反正也这玩意没依赖

**Comment by RPRX** [comment]
@Fangliding ~~那还是不删了，你修一下 Socks 吧~~

**Comment by RPRX** [comment]
@Fangliding ~~按 https://github.com/XTLS/Xray-core/commit/b11fcf0ac23358319a1f64e2d0659cee58f0a9c7#commitcomment-144976076 重新写一下开个 PR 吧~~

**Comment by Fangliding** [comment]
> @Fangliding ~按 [b11fcf0#commitcomment-144976076](https://github.com/XTLS/Xray-core/commit/b11fcf0ac23358319a1f64e2d0659cee58f0a9c7#commitcomment-144976076) 重新写一下开个 PR 吧~

就一行要不直接amend吧
