### ISSUE TITLE
[功能建议]希望出个语法检查功能

### ISSUE THREAD

**Issue by huangguiniab** [XTLS/Xray-core#363]
在给服务器安装的时候遇到了谜之报错
```
A unified platform for anti-censorship.
2021/03/11 19:40:04 [Info] infra/conf/serial: Reading config: config.conf
Failed to start: main: failed to load config files: [config.conf] > infra/conf: failed to load inbound detour config. > json: cannot unmarshal string into Go struct field VLessInboundFallback.fallbacks.xver of type uint64
```
我琢磨半天也不知道自己到底错在了哪里(其实就是少了个逗号)，希望报错能人性化一些，如果能回复在哪行出现了错误就非常好，而且每次尝试都得启动一次，非常不方便，如果能一条命令检查比如xray -t a.conf就方便了很多

**Comment by huangguiniab** [comment]
艹，我才发现是xver的问题，不过这个功能可以有

**Comment by xiaokangwang** [comment]
你们可以建议 rprx 写个json schema

**Comment by z826540272** [comment]
json很麻烦 语法  标点符号太多

**Comment by AkinoKaede** [comment]
@z826540272 xray 还支持 yaml toml 和 protobuf

**Comment by wy16W2pIilK1xgqN** [comment]
希望能支持 HOCON 配置文件格式。
比 yaml 功能强大灵活，解决其语法歧义问题，还没有空格惨案。
https://github.com/ustc-zzzz/HOCON-CN-Translation/blob/master/HOCON.md
https://www.zhihu.com/question/41253282/answer/119857880

**Comment by jyf007** [comment]
@wy16W2pIilK1xgqN interesting,and i think yaml needs too

**Comment by PMExtra** [comment]
I'm working about json schema for xray configuration.

**Comment by PMExtra** [comment]
Sorry I'm suspend this work, it's the schema that still work in progress.

https://gist.githubusercontent.com/PMExtra/73f9dc33cba869184f74fc6a47e8c2e9/raw/15c34bb3734e063e5fbc8cdd597bea7fd65c1fbb/config.schema.json
