### ISSUE TITLE
WebSocket Host does not support Cname Domain!

### ISSUE THREAD

**Issue by alipour66m** [XTLS/Xray-core#3656]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.

### Version

1.8.23

### Description

Suppose the the webSocket host is domian1.com
And the Domian2.com is a Cname for the domian1.com.
In this case, WebSocket does't work with Domian2.com
Since the domains are filtered quickly in Iran, manually changing the domain from the panel is a time-consuming task.
This was possible in version 1.8.9
Please provide this link for versions 1.8.24

### Reproduction Method

any vless+ws + CDN .

### Client config

<details><pre><code>
any vless+ws + CDN .
</code></pre></details>

### Server config

<details><pre><code>
any vless+ws + CDN .
</code></pre></details>

### Client log

<details><pre><code>
any vless+ws + CDN .
</code></pre></details>

### Server log

<details><pre><code>
any vless+ws + CDN .
</code></pre></details>

**Comment by Fangliding** [comment]
Remove the Host field in server config
