### ISSUE TITLE
Does Not work Split HTTP/3

### ISSUE THREAD

**Issue by HiddifyOfficial** [XTLS/Xray-core#3659]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [ ] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.

### Version

1.8.23

### Description

Hello. Thank you for all your hard work

**After updating the kernel to version 1.8.23, these protocols do not work:**
**Split HTTP/3**

Client:
Streisand 
FoXray 

This protocol was working fine before the clients updated the Xray kernel

### Reproduction Method

Noting 

### Client config

<details><pre><code>

</code></pre></details>

### Server config

<details><pre><code>

</code></pre></details>

### Client log

<details><pre><code>

</code></pre></details>

### Server log

<details><pre><code>

</code></pre></details>

**Comment by Fangliding** [comment]
not following template
