### ISSUE TITLE
请求为rule模块添加IPv4/IPv6的RoutingObject，用于单独指定出口

### ISSUE THREAD

**Issue by Kaze1027** [XTLS/Xray-core#3669]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了issues，没有发现已提出的类似问题。

### 版本

Xray 1.8.23 (Xray, Penetrates Everything.) 4c82ef8 (go1.22.5 linux/amd64)

## 一、目标
请求为rule模块添加IPv4/IPv6的RoutingObject，用于单独指定出口。该需求主要是为了实现某些仅有IPv4地址的vps指定流量出口所用。例如指定IPv6流量走warp创建的socks5服务。
### 配置信息
我有一台搬瓦工DC6线路的vps，但是该线路一直仅拥有ipv4地址，后面通过HE申请了一个免费的ipv6隧道为该vps创建了一个拥有ipv6地址的接口，接口信息如下：

<details><summary>/etc/network/interfaces</summary>
<p>

```
auto he-ipv6
iface he-ipv6 inet6 v4tunnel
        address 2001:XXX:c:3cc::X
        netmask 64
        endpoint 66.220.18.42
        local 216.XX.187.XX
        ttl 255
        gateway 2001:XXX:c:3cc::X
```

</p>
</details> 

### 配置出现错误
虽然为vps添加了ipv6支持，但是近期HE的地址频繁出现google验证和阻断，并且时常将google.com重定向到google.cn/m，严重影响使用。
### 计划解决方法
因此我使用warp在本地创建了一个socks服务，打算使用warp的IPv6地址
### ~~1.outbound模块freedom协议直接分流~~
**该方法未能实现目标。**
**失败原因：** 出站协议的freedom的配置项`"domainStrategy"`具有区分IPv4和IPv6的能力，但是不允许使用重复tag的outbound。

<details><summary>xray.json（freedom直接分流）</summary>
<p>

```
"outbounds": [
	{
		"protocol": "freedom",
		"domainStrategy": "UseIPv4",
		"tag": "Outbounds_Direct"
	},
	{
		"protocol": "freedom",
		"domainStrategy": "UseIPv6",
		"tag": "Outbounds_Direct"
	}
]
```

</p>
</details> 

### ~~2.outbound模块loopback协议回流到rule模块分流~~
**该方法未能实现目标。**
**失败原因：** 目前rule模块暂不支持区分IPv4和IPv6

<details><summary>xray.json（loopback回流rule分流）</summary>
<p>

```
{
	"inbounds": [
		{
			"tag": "Inbounds_VLESS"
		}
	],
	"outbounds": [
		{
			"protocol": "loopback",
			"settings": {
				"inboundTag": "traffic-input"
			},
			"tag": "Outbounds_Loopback"
		},
		{
			"protocol": "freedom",
			"domainStrategy": "UseIPv4",
			"tag": "Outbounds_Direct_v4"
		},
		{
			"protocol": "freedom",
			"domainStrategy": "UseIPv6",
			"redirect": "127.0.0.1:40000",
			"tag": "Outbounds_Direct_v6"
		},
		{
			"protocol": "socks",
			"settings": {
				"servers": [
					{
						"address": "127.0.0.1",
						"port": 40000
					}
				]
			},
			"tag": "Outbounds_Warp"
		}
	],
	"routing": {
		"domainStrategy": "IPIfNonMatch",
		"rules": [
			{
				"type": "field",
				"inboundTag": "Inbounds_VLESS",
				"outboundTag": "Outbounds_Loopback"
			},
			{
				"type": "field",
				"inboundTag": "traffic-input",
				"ipprotocolversion": "IPv4",
				"outboundTag": "Outbounds_Direct_v4"
			},
			{
				"type": "field",
				"inboundTag": "traffic-input",
				"ipprotocolversion": "IPv6",
				"outboundTag": "Outbounds_Direct_v6"
			}
		]
	}
}
```

</p>
</details> 

## 四、目前临时实现方法
虽然现在rule不支持通过ipv4或者ipv6来进行分流，但是，利用outbound的一个特性“列表中的第一个元素作为主 outbound。当路由匹配不存在或没有匹配成功时，流量由主 outbound 发出。”我们可以这样实现（但是这毕竟不是他正确的用法）：
<details><summary>xray.json（第一个outbound的邪恶用法）</summary>
<p>

```
"outbounds": [
		{
			"protocol": "freedom"
		},
		{
			"protocol": "socks",
			"domainStrategy": "UseIPv6",
			"settings": {
				"servers": [
					{
						"address": "127.0.0.1",
						"port": 40000
					}
				]
			},
			"tag": "Outbounds_Direct"
		},
		{
			"protocol": "socks",
			"settings": {
				"servers": [
					{
						"address": "127.0.0.1",
						"port": 40000
					}
				]
			},
			"tag": "Outbounds_Warp"
		}
	]
```

</p>
</details> 

### 重现方式

非Bug，Issue无需求请求模块。

### 客户端配置

<details><pre><code>
N/A
</code></pre></details>

### 服务端配置

<details><pre><code>
见上文
</code></pre></details>

### 客户端日志

<details><pre><code>
N/A
</code></pre></details>

### 服务端日志

<details><pre><code>
N/A
</code></pre></details>

**Comment by Fangliding** [comment]
。。。
匹配所有ipv6: ::/0
匹配所有ipv4 0.0.0.0/0
