### ISSUE TITLE
vless入站+wireguard出站不通

### ISSUE THREAD

**Issue by msbtx** [XTLS/Xray-core#3683]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了issues，没有发现已提出的类似问题。

### 版本

Xray 1.8.23 (Xray, Penetrates Everything.) 4c82ef8 (go1.22.5 linux/amd64)

### 描述

服务端使用wireguard出站不通。入站使用nginx tls前置+xray vless
1. 配置没变，若干个版本以前是好的，不确定是哪个版本开始不行了。
2. 注册新的warp账号配置尝试，仍然不通。
3. 出站换成direct能够正常工作。

### 重现方式

在服务端将默认出站换成wireguard，客户端尝试访问google.com，网络不通。

### 客户端配置

<details><pre><code>
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "xxx",
            "port": 443,
            "users": [
              {
                "id": "xxx",
                "alterId": 0,
                "email": "xxx",
                "security": "auto",
                "encryption": "none"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false,
          "serverName": "xxx.xxx.top",
          "fingerprint": "safari"
        },
        "wsSettings": {
          "path": "/xxx",
          "headers": {
            "Host": "xxx.xxx.top"
          }
        }
      },
      "mux": {
        "enabled": true,
        "concurrency": 8
      }
    },
</code></pre></details>

### 服务端配置

<details><pre><code>
{
	"log": {
		"access": "/var/log/xray/access.log",
		"error": "/var/log/xray/error.log",
		"loglevel": "debug",
		"dnsLog": true
	},
	"inbounds": [
		{
			"listen": "/dev/shm/xray_ws.sock,666",
			"protocol": "vless",
			"tag": "vless_in",
			"settings": {
				"clients": [
					{
						"id": "xxxx",
						"level": 0,
						"email": "xxxxxx"
					}
				],
				"decryption": "none"
			},
			"streamSettings": {
				"network": "ws",
				"security": "none",
				"wsSettings": {
					"path": "xxxx"
				}
			}
		}
	],
	"outbounds": [
		{
			"protocol": "wireguard",
			"settings": {
				"secretKey": "xxxxxxx",
				"address": [
					"172.16.0.2/32"
				],
				"peers": [
					{
						"publicKey": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
						"endpoint": "engage.cloudflareclient.com:2408",
						"allowedIPs": [
							"0.0.0.0/0"
						]
					}
				],
				"reserved": [111, 111, 111],
				"mtu": 1280,
				"domainStrategy": "ForceIPv4"
			},
			"tag": "warp-out"
		},
		{
			"protocol": "freedom",
			"settings": {},
			"tag": "direct"
		},
		{
			"protocol": "blackhole",
			"settings": {},
			"tag": "block"
		}
	],
	"routing": {
		"domainStrategy": "IPIfNonMatch",
		"rules": [
			{
				"type": "field",
				"ip": [
					"geoip:private"
				],
				"outboundTag": "block"
			},
			{
				"type": "field",
				"domain": [
					"geosite:cn"
				],
				"outboundTag": "warp-out"
			},
			{
				"type": "field",
				"ip": [
					"geoip:cn"
				],
				"outboundTag": "warp-out"
			},
			{
				"type": "field",
				"inboundTag": [
					"vless_in"
				],
			//	"outboundTag": "direct"
				"outboundTag": "warp-out"
			}
		]
	},
	"dns": {
		"servers": [
			"localhost"
		]
	}
}

</code></pre></details>

### 客户端日志

<details><pre><code>
2024/08/14 23:09:26 [Warning] core: Xray 1.8.23 started
2024/08/14 23:09:27 127.0.0.1:14631 accepted //www.google.com:443 [http10829 -> proxy10829]
</code></pre></details>

### 服务端日志

<details><pre><code>
2024/08/14 23:09:27 [Info] [1613034410] proxy/vless/inbound: firstLen = 222
2024/08/14 23:09:27 [Info] [1613034410] proxy/vless/inbound: received request for tcp:v1.mux.cool:0
2024/08/14 23:09:27 [Info] [1613034410] common/mux: received request for tcp:www.google.com:443
2024/08/14 23:09:27 [Info] [1613034410] app/dispatcher: taking detour [warp-out] for [tcp:www.google.com:443]
2024/08/14 23:09:27 [Info] switching dialer
2024/08/14 23:09:27 [Debug] app/dns: domain engage.cloudflareclient.com will use DNS in order: [localhost]
2024/08/14 23:09:27 [Info] app/dns: Localhost got answer: engage.cloudflareclient.com -> [162.159.192.1]
2024/08/14 23:09:27 [Debug] UAPI: Updating private key
2024/08/14 23:09:27 [Debug] peer(bmXO…fgyo) - UAPI: Created
2024/08/14 23:09:27 [Debug] peer(bmXO…fgyo) - UAPI: Updating endpoint
2024/08/14 23:09:27 [Debug] peer(bmXO…fgyo) - UAPI: Adding allowedip
2024/08/14 23:09:27 [Debug] UDP bind has been updated
2024/08/14 23:09:27 [Debug] peer(bmXO…fgyo) - Starting
2024/08/14 23:09:27 [Debug] Interface state was Down, requested Up, now Up
2024/08/14 23:09:27 [Debug] app/dns: domain www.google.com will use DNS in order: [localhost]
2024/08/14 23:09:27 [Debug] Routine: encryption worker 1 - started
2024/08/14 23:09:27 [Debug] Routine: decryption worker 1 - started
2024/08/14 23:09:27 [Debug] Routine: handshake worker 1 - started
2024/08/14 23:09:27 [Debug] Routine: TUN reader - started
2024/08/14 23:09:27 [Debug] Routine: event worker - started
2024/08/14 23:09:27 [Debug] Interface up requested
2024/08/14 23:09:27 [Debug] Routine: receive incoming Open - started
2024/08/14 23:09:27 [Debug] peer(bmXO…fgyo) - Routine: sequential sender - started
2024/08/14 23:09:27 [Info] app/dns: Localhost got answer: www.google.com -> [142.250.68.4]
2024/08/14 23:09:27 [Debug] peer(bmXO…fgyo) - Sending handshake initiation
2024/08/14 23:09:27 [Debug] [1613034410] transport/internet: dialing to udp:162.159.192.1:2408
2024/08/14 23:09:32 [Debug] peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 2)
2024/08/14 23:09:32 [Debug] peer(bmXO…fgyo) - Sending handshake initiation
2024/08/14 23:09:36 [Info] [1613034410] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to transfer request payload > websocket: close 1006 (abnormal closure): unexpected EOF
2024/08/14 23:09:36 [Info] [1613034410] app/proxyman/inbound: failed to close connection > transport/internet/websocket: failed to close connection > transport/internet/websocket: write unix /dev/shm/xray_ws.sock->@: write: broken pipe
2024/08/14 23:09:36 [Info] [1613034410] common/mux: unexpected EOF > common/mux: failed to read metadata > io: read/write on closed pipe
2024/08/14 23:09:37 [Debug] peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 2)
2024/08/14 23:09:37 [Debug] peer(bmXO…fgyo) - Sending handshake initiation
2024/08/14 23:09:42 [Debug] peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 3)
2024/08/14 23:09:42 [Debug] peer(bmXO…fgyo) - Sending handshake initiation
2024/08/14 23:09:48 [Debug] peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 4)
2024/08/14 23:09:48 [Debug] peer(bmXO…fgyo) - Sending handshake initiation
2024/08/14 23:09:53 [Debug] peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 5)
2024/08/14 23:09:53 [Debug] peer(bmXO…fgyo) - Sending handshake initiation
2024/08/14 23:09:58 [Debug] peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 6)
2024/08/14 23:09:58 [Debug] peer(bmXO…fgyo) - Sending handshake initiation
2024/08/14 23:10:03 [Debug] peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 7)
2024/08/14 23:10:03 [Debug] peer(bmXO…fgyo) - Sending handshake initiation
2024/08/14 23:10:08 [Debug] peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 8)
2024/08/14 23:10:08 [Debug] peer(bmXO…fgyo) - Sending handshake initiation
2024/08/14 23:10:14 [Debug] peer(bmXO…fgyo) - Handshake did not complete after 5 seconds, retrying (try 9)
2024/08/14 23:10:14 [Debug] peer(bmXO…fgyo) - Sending handshake initiation

</code></pre></details>

**Comment by Fangliding** [comment]
出现问题的具体版本

**Comment by msbtx** [comment]
> 出现问题的具体版本

我回退了版本好像依然不行，可能是被cf限制了，我是LA机房的，我记得之前得加上reserved的三个值才能连，现在好像直接连不上了。
