### ISSUE TITLE
vless xtls使用1.3.1后经常出现断流，是最近网路状况还是软件本身的原因？之前几乎没出现过

### ISSUE THREAD

**Issue by fredericky123** [XTLS/Xray-core#369]
如题，不知道跟最近的网路有关吗？

**Comment by fredericky123** [comment]
具体错误是：app/proxyman/inbound: connection ends > proxy/http: connection ends > proxy/http: failed to write response > write tcp 127.0.0.1:8889->127.0.0.1:56197: write: broken pipe

**Comment by aoeg** [comment]
解决了？一直断流vmess没事，换到xtls几分钟就断流

**Comment by fredericky123** [comment]
是大佬直接关贴了
[cry]

**Comment by ShinyGwyn** [comment]
网络问题

**Comment by aoeg** [comment]
我的问题解决了，是端口问题，trojan 和 xray都占用了433，两者都断流。修改一个端口就没问题了

**Comment by fredericky123** [comment]
> 我的问题解决了，是端口问题，trojan 和 xray都占用了443，两者都断流。修改一个端口就没问题了

然而我只开了xray，这几天有所好转，但还是会出现断流
