### ISSUE TITLE
ERROR - X-UI: Failure in running xray-core:exit status 0xffffffff

### ISSUE THREAD

**Issue by Morrigan-Ship** [XTLS/Xray-core#3696]
OS: windows
version: 1.8.23

**Comment by Fangliding** [comment]
We do not handle panel issues

**Comment by Morrigan-Ship** [comment]
its xray core error not panel error
i using panel for manage xray
i checked its from xray

**Comment by mmmray** [comment]
@Morrigan-Ship the reason we don't deal with bugreports like this is because the information provided is so minimal, there is actually no way to tell what is wrong or which component has a bug. we have a bug report template for this purpose.
