### ISSUE TITLE
panic with this error

### ISSUE THREAD

**Issue by kabo00os** [XTLS/Xray-core#3699]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.

### Version

1.8.23

### Description

After some time this error will be displayed

### Reproduction Method

splithttp method

### Client config

<details><pre><code>
-
</code></pre></details>

### Server config

<details><pre><code>
-
</code></pre></details>

### Client log

<details><pre><code>
panic: close of closed channel

goroutine 2667 [running]:
github.com/quic-go/quic-go/http3.(*hijackableBody).requestDone(...)
	github.com/quic-go/quic-go@v0.45.1/http3/body.go:124
github.com/quic-go/quic-go/http3.(*hijackableBody).Close(0x1400018ef30)
	github.com/quic-go/quic-go@v0.45.1/http3/body.go:130 +0x38
github.com/quic-go/quic-go/http3.(*gzipReader).Close(0x140008817f8?)
	github.com/quic-go/quic-go@v0.45.1/http3/gzip_reader.go:38 +0x28
github.com/xtls/xray-core/transport/internet/splithttp.(*LazyReader).Close(0x140007edc80)
	github.com/xtls/xray-core/transport/internet/splithttp/lazy_reader.go:53 +0xc8
github.com/xtls/xray-core/transport/internet/splithttp.(*LazyReader).Close(0x140007edcb0)
	github.com/xtls/xray-core/transport/internet/splithttp/lazy_reader.go:53 +0xc8
github.com/xtls/xray-core/transport/internet/splithttp.(*splitConn).Close(0x1400028bcc0)
	github.com/xtls/xray-core/transport/internet/splithttp/connection.go:26 +0x50
github.com/xtls/xray-core/proxy/vless/outbound.(*Handler).Process(0x140003858c0, {0x10537bd58, 0x140003b1b90}, 0x1400030ecc0, {0x105379008, 0x1400038c300})
	github.com/xtls/xray-core/proxy/vless/outbound/outbound.go:295 +0x1158
github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dispatch(0x1400038c300, {0x10537bd58, 0x140003b1b90}, 0x1400030ecc0)
	github.com/xtls/xray-core/app/proxyman/outbound/handler.go:211 +0x3a8
github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0x140001fc900, {0x10537bd58, 0x140003b1b90}, 0x1400030ecc0, {{0x10537bb28, 0x14000300aa0}, 0x50, 0x2})
	github.com/xtls/xray-core/app/dispatcher/default.go:461 +0x918
created by github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 2708
	github.com/xtls/xray-core/app/dispatcher/default.go:252 +0x4a8
</code></pre></details>

### Server log

<details><pre><code>
-
</code></pre></details>

**Comment by mmmray** [comment]
https://github.com/quic-go/quic-go/issues/2143

**Comment by mmmray** [comment]
@kabo00os if you are able to, please test #3710

**Comment by kabo00os** [comment]
This problem occurs with burstObservatory
When several configs are added, sometimes this problem occurs
