### ISSUE TITLE
反向代理没法正常运行

### ISSUE THREAD

**Issue by vangork** [XTLS/Xray-core#37]
按照此方法设置反向代理，配置完全一致。
https://guide.v2fly.org/app/reverse2.html#b-%E7%9A%84%E9%85%8D%E7%BD%AE
v2ray-core 4.32.1 可以成功运行。

在服务器B上Xray-core v1.1.1 运行error.log报错如下
app/reverse: failed to process reverse connection > common/mux: unable to find an available mux client

**Comment by rprx** [comment]
这个报错是 v2ray-core 的

**Comment by vangork** [comment]
> 这个报错是 v2ray-core 的

已更细
