### ISSUE TITLE
rprx开始圈钱，建议各位用sing-box，抵制人品低下的垃圾作者

### ISSUE THREAD

**Issue by fuckrprx** [XTLS/Xray-core#3704]
[sing-box](https://github.com/SagerNet/sing-box)比xray更强大

**Comment by PoneyClairDeLune** [comment]
lol no thanks

> I suggest you use sing-box to boycott the bad authors.

then boycott sing-box first with that logic lmao

**Comment by RPRX** [comment]
该说的都在 Project X Channel 说过了，自己去看，敌对行为 issue 会删掉，另外已 block 这两个账号
