### ISSUE TITLE
sing-box是第一个实现了shadowtls的代理平台，支持Hysteria。

### ISSUE THREAD

**Issue by fuckrprx** [XTLS/Xray-core#3707]
Reality有剽窃嫌疑。

**Comment by fuckrprx** [comment]
作者至今无法解释为什么reality是在 shadow-tls 发布六个月后发布的，即使声称文档和定义早就写好了。

**Comment by RPRX** [comment]
看得我想笑

我知道其他人为什么不删这些 issue，因为这些 issue 是攻击的证据，不过这么多天了 webarchive 早有了吧，删了
