### ISSUE TITLE
建议改名

### ISSUE THREAD

**Issue by Acytoo** [XTLS/Xray-core#371]
Google搜索xray，排名第一的是一款渗透工具xray，然后都是跟x光有关的内容。有没有给这款工具改名的想法？为了减少歧义，方便推广。

**Comment by rprx** [comment]
不改名，对于这类项目，混淆视听挺好的。

**Comment by NetHeritage** [comment]
用的多了  xray这个词就具有新的含义了

**Comment by tdynamicl** [comment]
哈哈X光
