### ISSUE TITLE
VLESS-XTLS-uTLS-REALITY the Edge browser will display a 403 error message

### ISSUE THREAD

**Issue by mike-668** [XTLS/Xray-core#3721]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.

### Version

1.8.23

### Description

VLESS-XTLS-uTLS-REALITY
Set the server camouflage URL to "www.amazon.com", and the computer does not enable the proxy to access https://VPSip, and the Edge browser will display a 403 error message.

Regarding disguised URLs, I have a suggestion: set up a domain, Xray automatically detects the region where the VPS is located, and randomly calls URLs from the database, instead of having users set them up by themselves as they do now. This can avoid the problem of multiple people using the same proxy server and disguising the same URL, and is more in line with user access habits, making it more difficult for GFW to detect.

### Reproduction Method

The server configuration file is modified as shown in the example, PC browser edge accesses VPS without proxy, ip

### Client config

<details><pre><code>
 "outbounds": [
        {
            "tag": "proxy",
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "ip of VPS", 
                        "port": 443, 
                        "users": [
                            {
                                "id": "UUID", 
                                "encryption": "none",
                                "flow": "xtls-rprx-vision"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "reality",
                "realitySettings": {
                    "show": false,
                    "fingerprint": "chrome", 
                    "serverName": "www.amazon.com", 
                    "publicKey": "xray x25519",
                    "spiderX": "", 
                    "shortId": "8 or 16 id"
</code></pre></details>

### Server config

<details><pre><code>
"inbounds": [
        {
            "listen": "0.0.0.0",
            "port": 443, 
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "UUID", 
                        "flow": "xtls-rprx-vision"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "tcp",
                "security": "reality",
                "realitySettings": {
                    "show": false,
                    "dest": "www.amazon.com:443", 
                    "xver": 0,
                    "serverNames": [
                        "www.amazon.com"
                    ],
                    "privateKey": "xray x25519",
                    "shortIds": [
                        "8 or 16 id"
                    ]
                }
</code></pre></details>

### Client log

<details><pre><code>
none
</code></pre></details>

### Server log

<details><pre><code>
none
</code></pre></details>

**Comment by Fangliding** [comment]
Because browser will not send SNI if using https://+ip, so site will return error
About the suggestion, we will not consider any pre-set list, this will only make it easier to target
