### ISSUE TITLE
sing-box陷入资金困难，需要资助。xray大量使用sing-box的代码。

### ISSUE THREAD

**Issue by singsingbox** [XTLS/Xray-core#3736]
[请资助sing-box](https://github.com/sponsors/nekohasekai)

**Comment by mmmray** [comment]
~~quic-go is the same, let's open an issue for it~~

**Comment by RPRX** [comment]
不论是谁在操纵这些账号，不断地开这些弱智 issue 只会显得你很傻逼，删了
