### ISSUE TITLE
routing service python grpc api

### ISSUE THREAD

**Issue by whoisthisrez** [XTLS/Xray-core#3745]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [ ] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

 # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
  status = StatusCode.UNIMPLEMENTED
  details = "unknown service xray.app.router.command.RoutingService"
  debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"unknown service xray.app.router.command.RoutingService", grpc_status:12, created_time:"2024-08-27T11:18:21.294100599+03:30"}"
>
<_InactiveRpcError of RPC that terminated with:
  status = StatusCode.UNIMPLEMENTED
  details = "unknown service xray.app.router.command.RoutingService"
  debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"unknown service xray.app.router.command.RoutingService", grpc_status:12, created_time:"2024-08-27T11:18:21.294100599+03:30"}"

### Reproduction Method

.

### Client config

<details><pre><code>

</code></pre></details>

### Server config

<details><pre><code>

</code></pre></details>

### Client log

<details><pre><code>

</code></pre></details>

### Server log

<details><pre><code>

</code></pre></details>

**Comment by Fangliding** [comment]
?
