### ISSUE TITLE
在mt7621(mipsle32)上直接运行xray v1.8.24会崩溃

### ISSUE THREAD

**Issue by christarcher** [XTLS/Xray-core#3748]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

没有以任何配置启动,空配置启动都会崩溃
版本: v1.8.24
我已经在自己的另一台机器上下载并比对了,确认文件为release中v1.8.24的Xray-linux-mips32le.zip压缩包中的xray文件

我之前使用v1.8.23在mt7621 设备上正常使用

### 重现方式

在mt7621的设备上运行
下载后直接./xray运行就崩溃

### 客户端配置

none

### 服务端配置

none

### 客户端日志

这里放的是在我vps上显示的sha256和文件头分析:
<details><pre><code>
root@hkg3-lite-2024:/tmp/xraytest# wget https://github.com/XTLS/Xray-core/releases/download/v1.8.24/Xray-linux-mips32le.zip--2024-08-31 12:23:56--  https://github.com/XTLS/Xray-core/releases/download/v1.8.24/Xray-linux-mips32le.zip
Resolving github.com (github.com)... 
(下载这一段省略)
Xray-linux-mips32le.zip            100%[===============================================================>]  21.28M  38.7MB/s    in 0.6s    

2024-08-31 12:23:58 (38.7 MB/s) - ‘Xray-linux-mips32le.zip’ saved [22318719/22318719]

root@hkg3-lite-2024:/tmp/xraytest# ls
Xray-linux-mips32le.zip
root@hkg3-lite-2024:/tmp/xraytest# unzip Xray-linux-mips32le.zip 
Archive:  Xray-linux-mips32le.zip
  inflating: xray_softfloat          
  inflating: xray                    
  inflating: geoip.dat               
  inflating: LICENSE                 
  inflating: README.md               
  inflating: geosite.dat             
root@hkg3-lite-2024:/tmp/xraytest# sha256sum xray
**f1a9d90afa3e50879d024f4395386f7668bb2791cce39b78e3f271cc951369e4**  xray
root@hkg3-lite-2024:/tmp/xraytest# file xray
**xray: ELF 32-bit LSB executable, MIPS, MIPS32 version 1 (SYSV), statically linked, stripped**

</code></pre></details>

### 服务端日志

这里放的是我在mt7621设备上遇到崩溃的日志:
<details><pre><code>
/tmp # ls
xraymipsel32
/tmp # busybox sha256sum xraymipsel32 
**f1a9d90afa3e50879d024f4395386f7668bb2791cce39b78e3f271cc951369e4**  **与上面在vps中下载的文件一致**: xraymipsel32
/tmp # cat /proc/cpuinfo
system type             : **MT7621**
machine                 : Unknown
processor               : 0
cpu model               : MIPS 1004Kc V2.15
BogoMIPS                : 583.68
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa                     : mips1 mips2 mips32r1 mips32r2
ASEs implemented        : mips16 dsp mt
shadow register sets    : 1
kscratch registers      : 0
core                    : 0
VPE                     : 0
VCED exceptions         : not available
VCEI exceptions         : not available
(其他核心省略)

/tmp # ./xraymipsel32 
runtime: eventfd failed with 4294967207
fatal error: runtime: eventfd failed

goroutine 1 gp=0x2400128 m=0 mp=0x1d634c0 [running, locked to thread]:
runtime.throw({0x1290d08, 0x17})
        runtime/panic.go:1067 +0x48 fp=0x2490cb0 sp=0x2490c9c pc=0xadc8c
runtime.netpollinit()
        runtime/netpoll_epoll.go:31 +0x234 fp=0x2490cf8 sp=0x2490cb0 pc=0x5ac00
runtime.netpollGenericInit()
        runtime/netpoll.go:224 +0x8c fp=0x2490d00 sp=0x2490cf8 pc=0x599dc
internal/poll.runtime_pollServerInit()
        runtime/netpoll.go:215 +0x38 fp=0x2490d04 sp=0x2490d00 pc=0xac44c
sync.(*Once).doSlow(0x1d6eee8, 0x12d683c)
        sync/once.go:76 +0x10c fp=0x2490d2c sp=0x2490d04 pc=0xdb874
sync.(*Once).Do(...)
        sync/once.go:67
internal/poll.(*pollDesc).init(0x245e158, 0x245e140)
        internal/poll/fd_poll_runtime.go:39 +0x70 fp=0x2490d3c sp=0x2490d2c pc=0x158504
internal/poll.(*FD).Init(0x245e140, {0x1279bce, 0x4}, 0x1)
        internal/poll/fd_unix.go:66 +0xb4 fp=0x2490d50 sp=0x2490d3c pc=0x1596dc
os.newFile(0x3, {0x24aa018, 0x17}, 0x1, 0x0)
        os/file_unix.go:237 +0x1f4 fp=0x2490d74 sp=0x2490d50 pc=0x16977c
os.openFileNolog({0x24aa018, 0x17}, 0x0, 0x0)
        os/file_unix.go:297 +0x1e0 fp=0x2490dc0 sp=0x2490d74 pc=0x169a04
os.OpenFile({0x24aa018, 0x17}, 0x0, 0x0)
        os/file.go:385 +0x70 fp=0x2490de0 sp=0x2490dc0 pc=0x167cb8
os.Open(...)
        os/file.go:365
google.golang.org/protobuf/internal/detrand.binaryHash()
        google.golang.org/protobuf@v1.34.2/internal/detrand/rand.go:46 +0x70 fp=0x2490e84 sp=0x2490de0 pc=0x1e9b8c
google.golang.org/protobuf/internal/detrand.init()
        google.golang.org/protobuf@v1.34.2/internal/detrand/rand.go:38 +0x38 fp=0x2490e90 sp=0x2490e84 pc=0x1e9af4
runtime.doInit1(0x1cc2448)
        runtime/proc.go:7278 +0x148 fp=0x2490fb4 sp=0x2490e90 pc=0x77c24
runtime.doInit(...)
        runtime/proc.go:7245
runtime.main()
        runtime/proc.go:254 +0x454 fp=0x2490fec sp=0x2490fb4 pc=0x636fc
runtime.goexit({})
        runtime/asm_mipsx.s:664 +0x4 fp=0x2490fec sp=0x2490fec pc=0xb7be0

goroutine 2 gp=0x2400488 m=nil [force gc (idle)]:
runtime.gopark(0x12d66d8, 0x1d60260, 0x11, 0xa, 0x1)
        runtime/proc.go:424 +0x128 fp=0x244efd4 sp=0x244efc8 pc=0xade18
runtime.goparkunlock(...)
        runtime/proc.go:430
runtime.forcegchelper()
        runtime/proc.go:337 +0x128 fp=0x244efec sp=0x244efd4 pc=0x63a9c
runtime.goexit({})
        runtime/asm_mipsx.s:664 +0x4 fp=0x244efec sp=0x244efec pc=0xb7be0
created by runtime.init.6 in goroutine 1
        runtime/proc.go:325 +0x44

goroutine 3 gp=0x24005a8 m=nil [GC sweep wait]:
runtime.gopark(0x12d66d8, 0x1d60ea0, 0xc, 0x9, 0x1)
        runtime/proc.go:424 +0x128 fp=0x244f7c4 sp=0x244f7b8 pc=0xade18
runtime.goparkunlock(...)
        runtime/proc.go:430
runtime.bgsweep(0x245c000)
        runtime/mgcsweep.go:277 +0xe8 fp=0x244f7e4 sp=0x244f7c4 pc=0x43a98
runtime.gcenable.gowrap1()
        runtime/mgc.go:203 +0x64 fp=0x244f7ec sp=0x244f7e4 pc=0x30ce4
runtime.goexit({})
        runtime/asm_mipsx.s:664 +0x4 fp=0x244f7ec sp=0x244f7ec pc=0xb7be0
created by runtime.gcenable in goroutine 1
        runtime/mgc.go:203 +0xb4

goroutine 4 gp=0x24006c8 m=nil [GC scavenge wait]:
runtime.gopark(0x12d66d8, 0x1d61ee0, 0xd, 0xa, 0x2)
        runtime/proc.go:424 +0x128 fp=0x244ffbc sp=0x244ffb0 pc=0xade18
runtime.goparkunlock(...)
        runtime/proc.go:430
runtime.(*scavengerState).park(0x1d61ee0)
        runtime/mgcscavenge.go:425 +0x98 fp=0x244ffd0 sp=0x244ffbc pc=0x404e4
runtime.bgscavenge(0x245c000)
        runtime/mgcscavenge.go:653 +0x74 fp=0x244ffe4 sp=0x244ffd0 pc=0x40d88
runtime.gcenable.gowrap2()
        runtime/mgc.go:204 +0x64 fp=0x244ffec sp=0x244ffe4 pc=0x30c70
runtime.goexit({})
        runtime/asm_mipsx.s:664 +0x4 fp=0x244ffec sp=0x244ffec pc=0xb7be0
created by runtime.gcenable in goroutine 1
        runtime/mgc.go:204 +0x114

goroutine 5 gp=0x2400a28 m=nil [runnable]:
runtime.runfinq()
        runtime/mfinal.go:176 fp=0x244e7ec sp=0x244e7ec pc=0x2f6b8
runtime.goexit({})
        runtime/asm_mipsx.s:664 +0x4 fp=0x244e7ec sp=0x244e7ec pc=0xb7be0
created by runtime.createfing in goroutine 1
        runtime/mfinal.go:163 +0x98

/tmp # ./xray1823 
Xray 1.8.23 (Xray, Penetrates Everything.) 4c82ef8 (go1.22.5 linux/mipsle)
A unified platform for anti-censorship.
2024/08/31 12:44:37 Using config from STDIN
2024/08/31 12:44:37 [Info] infra/conf/serial: Reading config: stdin:
</code></pre></details>

**Comment by mmmray** [comment]
first guess is https://github.com/XTLS/Xray-core/commit/592c2daf58f3b7a41edb3feb664e77ebaa1d2da4

**Comment by Fangliding** [comment]
如果真的是楼上所说的原因 试一下这个？
https://github.com/Fangliding/Xray-core/actions/runs/10647357523

**Comment by christarcher** [comment]
> 这些报错不像是xray的问题 像是golang自己的问题 如果真的是楼上所说的原因 试一下这个？ 改成了go122编译 https://github.com/Fangliding/Xray-core/actions/runs/10647357523

测试了,可以正常运行,看来的确是golang的问题

**Comment by omid-official** [comment]
@christarcher Can you tell us what is your kernel version?
Use this command
```
uname -a
```

**Comment by christarcher** [comment]
> @christarcher Can you tell us what is your kernel version? Use this command
> 
> ```
> uname -a
> ```

~ # uname -a
Linux 3.10.14 #1472 SMP Tue Jul 16 17:52:40 CST 2024 mips GNU/Linux
~ # cat /proc/version
Linux version 3.10.14 (zb@linktoo-server1) (gcc version 4.6.3 (Buildroot 2012.11.1) ) #1472 SMP Tue Jul 16 17:52:40 CST 2024

**Comment by omid-official** [comment]
> > @christarcher Can you tell us what is your kernel version? Use this command
> > ```
> > uname -a
> > ```
> 
> ~ # uname -a Linux 3.10.14 #1472 SMP Tue Jul 16 17:52:40 CST 2024 mips GNU/Linux ~ # cat /proc/version Linux version 3.10.14 (zb@linktoo-server1) (gcc version 4.6.3 (Buildroot 2012.11.1) ) #1472 SMP Tue Jul 16 17:52:40 CST 2024
> 
> The reason for the crash may be that this kernel is too old

Golang requires Kernel version 2.6.32 or later

**Comment by omid-official** [comment]
I guess the problem occurred after this PR.

https://github.com/golang/go/commit/d068c2cb620c1daeedc8b9cce488af45a6c2c889

**Comment by omid-official** [comment]
> The reason for the crash may be that this kernel is too old

Try to update the kernel
It is possible that eventfd was added to the MIPS kernel in later versions.
The required kernel version depends on the architecture also.

**Comment by christarcher** [comment]
I found another router device that also uses MT7621 CPU.
I downloaded and tried to run, heres result:
xray softfloat version runs well, however xray(hard float) tells Illegal Instruction
This may be because the CPU on this device does not support hardware floating point operations.

New device log:
<detail><code><pre>
/tmp/tmp # ./xray
Illegal instruction
/tmp/tmp # ./xray_softfloat 
Xray 1.8.24 (Xray, Penetrates Everything.) 6baad79 (go1.23.0 linux/mipsle)
A unified platform for anti-censorship.
2024/09/01 06:38:09 Using config from STDIN
2024/09/01 06:38:09 [Info] infra/conf/serial: Reading config: &{Name:stdin: Format:json}
^C
/tmp/tmp # sha256sum xray
f1a9d90afa3e50879d024f4395386f7668bb2791cce39b78e3f271cc951369e4  xray
/tmp/tmp # sha256sum xray_softfloat 
09037fb0d77de0b4966863bd4f6e09a4e86bf6b9fead0df402b39dfbf95f2556  xray_softfloat
/tmp/tmp # cat /proc/cpuinfo
system type             : MediaTek MT7621 ver:1 eco:3
machine                 : MediaTek MT7621 RFB (802.11ax,SNOR)
processor               : 0
cpu model               : MIPS 1004Kc V2.15
BogoMIPS                : 586.13
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa                     : mips1 mips2 mips32r1 mips32r2
ASEs implemented        : mips16 dsp mt
shadow register sets    : 1
kscratch registers      : 0
package                 : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available
VPE                     : 0

/tmp/tmp # uname -a
Linux AP800AX 4.4.198 #0 SMP Mon Mar 21 03:01:05 UTC 2022 mips GNU/Linux
/tmp/tmp # cat /proc/version
Linux version 4.4.198 (ycore@ycore-70TUA000CN) (gcc version 5.4.0 (LEDE GCC 5.4.0 unknown) ) #0 SMP Mon Mar 21 03:01:05 UTC 2022
</pre></code></detail>


However, on the original device, both the hardware floating point and software floating point versions will crash.

Previous device log:
<detail><code><pre>
/ac_update # ls
xray_softfloat
/ac_update # sha256sum ./xray_softfloat 
-sh: sha256sum: not found
/ac_update # sha256sum ./xray_softfloat
-sh: sha256sum: not found
/ac_update # busybox sha256sum ./xray_softfloat
09037fb0d77de0b4966863bd4f6e09a4e86bf6b9fead0df402b39dfbf95f2556  ./xray_softfloat
/ac_update # ./xray_softfloat 
runtime: eventfd failed with 4294967207
fatal error: runtime: eventfd failed

goroutine 1 gp=0x2400128 m=0 mp=0x1d734c0 [running, locked to thread]:
runtime.throw({0x12a0d2b, 0x17})
        runtime/panic.go:1067 +0x48 fp=0x2490cb0 sp=0x2490c9c pc=0xb1298
runtime.netpollinit()
        runtime/netpoll_epoll.go:31 +0x234 fp=0x2490cf8 sp=0x2490cb0 pc=0x5b8d4
runtime.netpollGenericInit()
        runtime/netpoll.go:224 +0x8c fp=0x2490d00 sp=0x2490cf8 pc=0x5a6b0
internal/poll.runtime_pollServerInit()
        runtime/netpoll.go:215 +0x38 fp=0x2490d04 sp=0x2490d00 pc=0xafa58
sync.(*Once).doSlow(0x1d7eee8, 0x12e685c)
        sync/once.go:76 +0x10c fp=0x2490d2c sp=0x2490d04 pc=0xe0980
sync.(*Once).Do(...)
        sync/once.go:67
internal/poll.(*pollDesc).init(0x245e158, 0x245e140)
        internal/poll/fd_poll_runtime.go:39 +0x70 fp=0x2490d3c sp=0x2490d2c pc=0x15e188
internal/poll.(*FD).Init(0x245e140, {0x1289bce, 0x4}, 0x1)
        internal/poll/fd_unix.go:66 +0xb4 fp=0x2490d50 sp=0x2490d3c pc=0x15f360
os.newFile(0x3, {0x24ae000, 0x19}, 0x1, 0x0)
        os/file_unix.go:237 +0x1f4 fp=0x2490d74 sp=0x2490d50 pc=0x16f400
os.openFileNolog({0x24ae000, 0x19}, 0x0, 0x0)
        os/file_unix.go:297 +0x1e0 fp=0x2490dc0 sp=0x2490d74 pc=0x16f688
os.OpenFile({0x24ae000, 0x19}, 0x0, 0x0)
        os/file.go:385 +0x70 fp=0x2490de0 sp=0x2490dc0 pc=0x16d93c
os.Open(...)
        os/file.go:365
google.golang.org/protobuf/internal/detrand.binaryHash()
        google.golang.org/protobuf@v1.34.2/internal/detrand/rand.go:46 +0x70 fp=0x2490e84 sp=0x2490de0 pc=0x1efc28
google.golang.org/protobuf/internal/detrand.init()
        google.golang.org/protobuf@v1.34.2/internal/detrand/rand.go:38 +0x38 fp=0x2490e90 sp=0x2490e84 pc=0x1efb90
runtime.doInit1(0x1cd2448)
        runtime/proc.go:7278 +0x148 fp=0x2490fb4 sp=0x2490e90 pc=0x78bfc
runtime.doInit(...)
        runtime/proc.go:7245
runtime.main()
        runtime/proc.go:254 +0x454 fp=0x2490fec sp=0x2490fb4 pc=0x646d4
runtime.goexit({})
        runtime/asm_mipsx.s:664 +0x4 fp=0x2490fec sp=0x2490fec pc=0xbb1ec

goroutine 2 gp=0x2400488 m=nil [force gc (idle)]:
runtime.gopark(0x12e66f8, 0x1d70260, 0x11, 0xa, 0x1)
        runtime/proc.go:424 +0x128 fp=0x244efd4 sp=0x244efc8 pc=0xb1424
runtime.goparkunlock(...)
        runtime/proc.go:430
runtime.forcegchelper()
        runtime/proc.go:337 +0x128 fp=0x244efec sp=0x244efd4 pc=0x64a74
runtime.goexit({})
        runtime/asm_mipsx.s:664 +0x4 fp=0x244efec sp=0x244efec pc=0xbb1ec
created by runtime.init.6 in goroutine 1
        runtime/proc.go:325 +0x44

goroutine 3 gp=0x24005a8 m=nil [GC sweep wait]:
runtime.gopark(0x12e66f8, 0x1d70ea0, 0xc, 0x9, 0x1)
        runtime/proc.go:424 +0x128 fp=0x244f7c4 sp=0x244f7b8 pc=0xb1424
runtime.goparkunlock(...)
        runtime/proc.go:430
runtime.bgsweep(0x245c000)
        runtime/mgcsweep.go:277 +0xe8 fp=0x244f7e4 sp=0x244f7c4 pc=0x44758
runtime.gcenable.gowrap1()
        runtime/mgc.go:203 +0x64 fp=0x244f7ec sp=0x244f7e4 pc=0x31030
runtime.goexit({})
        runtime/asm_mipsx.s:664 +0x4 fp=0x244f7ec sp=0x244f7ec pc=0xbb1ec
created by runtime.gcenable in goroutine 1
        runtime/mgc.go:203 +0xb4

goroutine 4 gp=0x24006c8 m=nil [GC scavenge wait]:
runtime.gopark(0x12e66f8, 0x1d71ee0, 0xd, 0xa, 0x2)
        runtime/proc.go:424 +0x128 fp=0x244ffbc sp=0x244ffb0 pc=0xb1424
runtime.goparkunlock(...)
        runtime/proc.go:430
runtime.(*scavengerState).park(0x1d71ee0)
        runtime/mgcscavenge.go:425 +0x98 fp=0x244ffd0 sp=0x244ffbc pc=0x40c38
runtime.bgscavenge(0x245c000)
        runtime/mgcscavenge.go:653 +0x74 fp=0x244ffe4 sp=0x244ffd0 pc=0x41600
runtime.gcenable.gowrap2()
        runtime/mgc.go:204 +0x64 fp=0x244ffec sp=0x244ffe4 pc=0x30fbc
runtime.goexit({})
        runtime/asm_mipsx.s:664 +0x4 fp=0x244ffec sp=0x244ffec pc=0xbb1ec
created by runtime.gcenable in goroutine 1
        runtime/mgc.go:204 +0x114

goroutine 5 gp=0x2400a28 m=nil [runnable]:
runtime.runfinq()
        runtime/mfinal.go:176 fp=0x244e7ec sp=0x244e7ec pc=0x2fa04
runtime.goexit({})
        runtime/asm_mipsx.s:664 +0x4 fp=0x244e7ec sp=0x244e7ec pc=0xbb1ec
created by runtime.createfing in goroutine 1
        runtime/mfinal.go:163 +0x98

</pre></code></detail>

I'm not sure if this is due to system or missing dependencies.
I can open a shell for you to debug if you need.

**Comment by omid-official** [comment]
Maybe CONFIG_FUTEX and CONFIG_EPOLL are not enable.

**Comment by omid-official** [comment]
Try this command

```
grep CONFIG_EPOLL /boot/config-$(uname -r)
```

**Comment by christarcher** [comment]
> Try this command
> 
> ```
> grep CONFIG_EPOLL /boot/config-$(uname -r)
> ```

The compiler may not have chosen to save the configuration file

<details>
~ # grep CONFIG_EPOLL /boot/config-$(uname -r)
grep: /boot/config-3.10.14: No such file or directory

~ # ls /lib/modules
2.6.21   2.6.36   3.10.14
~ # ls /lib/modules/3.10.14
~ # ls /lib/modules/2.6.36
kernel           kpatch.ko        modules.builtin  modules.order
~ # ls /lib/modules/2.6.21
kernel       modules.dep
</details>
