### ISSUE TITLE
Windows 设置系统环境变量 HTTP_PROXY 后， npm 安装脚本 proxy/http: failed to write response > write tcp 127.0.0.1:1083->127.0.0.1:20141

### ISSUE THREAD

**Issue by devoudi** [XTLS/Xray-core#3758]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [ ] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

首先代理正常，只是在cmd中通过系统环境变量的HTTP_PROXY也是正常的。

![image](https://github.com/user-attachments/assets/34a4ab60-d4ca-4e34-bde6-4e46c1123291)

因为在npm的某个安装脚本里执行了 `C:\Windows\system32\cmd.exe /d /s /c node install.js` 没办法设置命令行代理，所以就设置了系统的环境变量 HTTP_PROXY和HTTPS_PROXY，设置完成后，安装就提示，导致安装失败

```
app/proxyman/inbound: connection ends > proxy/http: connection ends > proxy/http: failed to write response > write tcp 127.0.0.1:1083->127.0.0.1:20141: wsasend: An established connection was aborted by the software in your host machine.
```

![image](https://github.com/user-attachments/assets/54131f4e-fd2f-4447-9460-2b31e49cfa1d)

![image](https://github.com/user-attachments/assets/fc3c14f1-0349-44ac-862b-22228346be92)

目前怀疑应该是loopback exemption的问题导致的，但是目前搜索只看到了UWP的设置，并没有看到有针对某个exe的设置。

另外针对这种脚本安装，有没有别的方式能实现的。

### 重现方式

![image](https://github.com/user-attachments/assets/bc910af3-adce-40dc-b8ad-c5ddc71c016f)

### 客户端配置

<details><pre><code>

</code></pre></details>

### 服务端配置

<details><pre><code>

</code></pre></details>

### 客户端日志

<details><pre><code>
app/proxyman/inbound: connection ends > proxy/http: connection ends > proxy/http: failed to write response > write tcp 127.0.0.1:1083->127.0.0.1:20141: wsasend: An established connection was aborted by the software in your host machine.
</code></pre></details>

### 服务端日志

<details><pre><code>

</code></pre></details>

**Comment by Fangliding** [comment]
一没配置二没日志。。。
只要curl能用就代表核心是正常的 不是我们的问题
从仅有的一点信息看 设置了socks5代理 然后读到了https请求的路径(?) 错误是github自己关闭了连接 npm显示的是网络错误不是503 看起来是程序自己哪里不对
