### ISSUE TITLE
L2TP inbound support for router client

### ISSUE THREAD

**Issue by sayomelu** [XTLS/Xray-core#376]
Is it possible to bound a vmess proxy to L2TP inbound which could be used on a router for all local network proxy.

**Comment by MarksonHon** [comment]
@sayomelu Xray IS NOT an VPN program

**Comment by sayomelu** [comment]
> @sayomelu Xray IS NOT an VPN program

but it can be used as a VPN software.

**Comment by JimhHan** [comment]
Thanks for your support. 
Since Xray isn’t a VPN program, the best approach to achieve your goals is to use a **real** VPN program .

I highly recommend everyone to think twice before submitting an issue, especially inexperienced users.
