### ISSUE TITLE
Replacement for QUIC Transport

### ISSUE THREAD

**Issue by APT-ZERO** [XTLS/Xray-core#3772]

**Comment by Fangliding** [comment]
Why do you think mKCP have fec....

**Comment by Fangliding** [comment]
> So it just post same packet multiple times and there is no FEC? what a waste of bandwidth QUIC had SACK against packet loss, it was working good after the latest quic-go updates, it could even get more useful with udp-noise feature of freedom outbound, idk why you even removed it

Firstly, I suggest that you learn these network protocols before leaving a comment... Many of your comments are incorrect and meaningless.
Secondly, RPRX thinks that SplitHTTP h3 could replace QUIC, so it was removed. You can try migrating your QUIC to SplitHTTP h3
