### ISSUE TITLE
DNS设置成这种方式解析好像无效:

### ISSUE THREAD

**Issue by ckula9** [XTLS/Xray-core#3773]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

nip.io是一个动态指定解析服务商,比如你写1.2.3.4.nip.io它会给你解析到1.2.3.4

我的xray dns配置:
 "dns": {
   "hosts": {
      "regexp:^([0-9.]+)\.xyz$": "\\1"
    }
 }

用上面的配置好像1.2.3.4.xyz并没有被解析成1.2.3.4,  也就是后面的\\1好像并没有引用到前面正则的第一个括号里面的内容,

是还不支持这种吗, 以后会添加吗,  建议添加这种写法支持

### 重现方式

"dns": {
   "hosts": {
      "regexp:^([0-9.]+)\.xyz$": "\\1"
    }
 }

### 客户端配置

<details><pre><code>

</code></pre></details>

### 服务端配置

<details><pre><code>

</code></pre></details>

### 客户端日志

<details><pre><code>

</code></pre></details>

### 服务端日志

<details><pre><code>

</code></pre></details>

**Comment by ckula9** [comment]
1楼代码里写的时两个 \ \,  \ \ 1,

提交后有一个\被github给消失了

**Comment by Fangliding** [comment]
在代码里这东西就是一个键对值 没有反向引用这样的逻辑操作
