### ISSUE TITLE
domainStrategy 的Use/ForceIPv4v6、Use/ForceIPv6v4 并不能回落

### ISSUE THREAD

**Issue by VariatezzZ** [XTLS/Xray-core#3777]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [ ] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

domainStrategy 的**Use/ForceIPv4v6**实际效果等同于**Use/ForceIPv4**，**Use/ForceIPv6v4** 等同于**Use/ForceIPv6**，并不能实现回落。

dns 的 queryStrategy 为 UseIP，xray-core: v24.9.7， commit id: 3d9137c
- 若目标网站仅有ipv4，domainStrategy 为Use/ForceIPv6v4 并不能回落使用ipv4进行连接，反之亦然

- 若本地仅有v4，domainStrategy 为Use/ForceIPv6v4 ，访问双栈网站，不能回落至v4连接，反之亦然

- 若目标网站配置双栈ip，但目标网站实际v6地址并不能连接时，domainStrategy 为Use/ForceIPv6v4 时同样不能回落到v4地址进行连接，反之亦然

### 重现方式

以www.bilibili.com 为例，dns 的 hosts 只指定 v4地址，freedom 的 domainStrategy 设置为Use/ForceIPv6v4 ，用curl配置代理发送https://www.bilibili.com 的请求，会有openSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.bilibili.com:443 错误；chrome为ERR_CONNECTION_CLOSED错误

### 客户端配置

none

### 服务端配置

none

### 客户端日志

none

### 服务端日志

none

**Comment by Fangliding** [comment]
Xray只是随机选择一个符合条件的IP连接 不会对地址测活 ipv6v4 的作用是从一个双栈网站中随机挑选一个ipv6地址 可能文档措辞不太对 回头改一下

**Comment by VariatezzZ** [comment]
但是目标网站仅有v4地址，设置成ipv6v4貌似也无法完成连接啊？
```
var strategy = [][]byte{
	//              name        strategy,   prefer, fallback
	{0, 0, 0}, //   AsIs        none,       /,      /
	{1, 0, 0}, //   UseIP       use,        both,   none
	{1, 4, 0}, //   UseIPv4     use,        4,      none
	{1, 6, 0}, //   UseIPv6     use,        6,      none
	{1, 4, 6}, //   UseIPv4v6   use,        4,      6
	{1, 6, 4}, //   UseIPv6v4   use,        6,      4
	{2, 0, 0}, //   ForceIP     force,      both,   none
	{2, 4, 0}, //   ForceIPv4   force,      4,      none
	{2, 6, 0}, //   ForceIPv6   force,      6,      none
	{2, 4, 6}, //   ForceIPv4v6 force,      4,      6
	{2, 6, 4}, //   ForceIPv6v4 force,      6,      4
}
```
注释的fallback到底什么意思啊，按照我的理解，假如dns解析网站仅有v4地址，domainStrategy 为IPv6v4时，也能回落到v4进行连接，实际该情况是无法连接

**Comment by Fangliding** [comment]
无法复现 我这里测出来可以 本来你就没按模板要求填 不算命

**Comment by VariatezzZ** [comment]
差不多自己找到问题了，感谢回答。
