### ISSUE TITLE
Mux 无限接流量

### ISSUE THREAD

**Issue by z826540272** [XTLS/Xray-core#378]
测试地址。
http://speed.hetzner.de/
1GB，取消下载后仍然跑满带宽
大概接1分钟左右自动停止。
观察到MUX无线接流量/访问无法到达的ip地址造成周围IP不可达，和服务端有关。
用的机场，测试了三家机场，表现均不一样

A机场
访问无法到达的ip地址会暂时造成邻近IP地址不可达[172.217.161.128]，并且此时会触发无限接流量BUG。
如果不故意去访问无法到达的ip地址，一般会在1秒左右流量趋于0.
使用此命令触发无限接流量BUG
curl -x socks5://127.0.0.1:10808 172.217.161.127

B机场 
访问无法到达的ip地址[172.217.161.127]不会造成无法访问邻近ip[172.217.161.128]，但仍然存在停止下载后跑15秒左右流量的问题。
不进行上述测试，直接停止下载，仍然会有5秒左右的流量峰值。

C机场  
访问无法到达的ip地址只会造成邻近ip[172.217.161.128]延迟3秒响应。这一家基本不存在Mux无限跑流量的问题，停止下载后最多继续跑3秒。

D机场：
某公益机场，一切正常。无延迟响应，无停止下载继续跑流量。停止下载后瞬间0流量。

客户端是都是XRAY

相关问题：
https://github.com/v2fly/v2ray-core/issues/747

Vmess+WS
启动服务(2021/3/16 3:31:47)...
Xray 1.3.1 (Xray, Penetrates Everything.) Custom (go1.16 windows/amd64)
A unified platform for anti-censorship.
2021/03/16 03:31:47 [Info] infra/conf/serial: Reading config: C:\Users\vilin\Desktop\v2rayN-Core\config.json
2021/03/16 03:31:47 [Debug] app/log: Logger started
2021/03/16 03:31:47 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:10808
2021/03/16 03:31:47 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:10809
2021/03/16 03:31:47 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:5657
2021/03/16 03:31:47 [Debug] app/stats: create new counter outbound>>>proxy>>>traffic>>>uplink
2021/03/16 03:31:47 [Debug] app/stats: create new counter outbound>>>proxy>>>traffic>>>downlink
2021/03/16 03:31:47 [Debug] app/stats: create new counter outbound>>>direct>>>traffic>>>uplink
2021/03/16 03:31:47 [Debug] app/stats: create new counter outbound>>>direct>>>traffic>>>downlink
2021/03/16 03:31:47 [Debug] app/stats: create new counter outbound>>>block>>>traffic>>>uplink
2021/03/16 03:31:47 [Debug] app/stats: create new counter outbound>>>block>>>traffic>>>downlink
2021/03/16 03:31:47 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:10808
2021/03/16 03:31:47 [Info] transport/internet/udp: listening UDP on 0.0.0.0:10808
2021/03/16 03:31:47 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:10809
2021/03/16 03:31:47 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:5657
2021/03/16 03:31:47 [Warning] core: Xray 1.3.1 started
2021/03/16 03:31:47 [Info] [4073945699] proxy/http: request to Method [CONNECT] Host [alive.github.com:443] with URL [//alive.github.com:443]
2021/03/16 03:31:47 [Info] [4073945699] app/dispatcher: sniffed domain: alive.github.com
2021/03/16 03:31:47 127.0.0.1:13477 accepted //alive.github.com:443 [http -> proxy]
2021/03/16 03:31:47 [Info] [4073945699] app/dispatcher: taking detour [proxy] for [tcp:alive.github.com:443]
2021/03/16 03:31:47 [Info] [4073945699] common/mux: dispatching request to tcp:alive.github.com:443
2021/03/16 03:31:47 [Info] transport/internet/websocket: creating connection to tcp:117.34.14.30:80
2021/03/16 03:31:47 [Info] [1828174855] proxy/http: request to Method [CONNECT] Host [mtalk.google.com:5228] with URL [//mtalk.google.com:5228]
2021/03/16 03:31:47 [Info] [1828174855] app/dispatcher: sniffed domain: mtalk.google.com
2021/03/16 03:31:47 [Info] [1828174855] app/dispatcher: taking detour [proxy] for [tcp:mtalk.google.com:5228]
2021/03/16 03:31:47 [Info] [1828174855] common/mux: dispatching request to tcp:mtalk.google.com:5228
2021/03/16 03:31:47 127.0.0.1:13473 accepted //mtalk.google.com:5228 [http -> proxy]
2021/03/16 03:31:47 [Info] proxy/vmess/outbound: tunneling request to tcp:v1.mux.cool:9527 via tcp:117.34.14.30:80
2021/03/16 03:31:47 [Info] [3089783846] proxy/http: request to Method [CONNECT] Host [alive.github.com:443] with URL [//alive.github.com:443]
2021/03/16 03:31:47 [Info] [3089783846] app/dispatcher: sniffed domain: alive.github.com
2021/03/16 03:31:47 [Info] [3089783846] app/dispatcher: taking detour [proxy] for [tcp:alive.github.com:443]
2021/03/16 03:31:47 127.0.0.1:13474 accepted //alive.github.com:443 [http -> proxy]
2021/03/16 03:31:47 [Info] [3089783846] common/mux: dispatching request to tcp:alive.github.com:443
2021/03/16 03:31:48 [Debug] [3497827418] proxy/dokodemo: processing connection from: 127.0.0.1:13479
2021/03/16 03:31:48 [Info] [3497827418] proxy/dokodemo: received request for 127.0.0.1:13479
2021/03/16 03:31:48 127.0.0.1:13479 accepted tcp:127.0.0.1:0 [api -> api]
2021/03/16 03:31:48 [Info] [3497827418] app/dispatcher: taking detour [api] for [tcp:127.0.0.1:0]
2021/03/16 03:31:54 [Info] [4286586864] proxy/http: request to Method [CONNECT] Host [github.com:443] with URL [//github.com:443]
2021/03/16 03:31:54 [Info] [4286586864] app/dispatcher: sniffed domain: github.com
2021/03/16 03:31:54 [Info] [4286586864] app/dispatcher: taking detour [proxy] for [tcp:github.com:443]
2021/03/16 03:31:54 [Info] [4286586864] common/mux: dispatching request to tcp:github.com:443
2021/03/16 03:31:54 127.0.0.1:13480 accepted //github.com:443 [http -> proxy]
2021/03/16 03:31:55 [Info] [3636104220] proxy/http: request to Method [CONNECT] Host [content-autofill.googleapis.com:443] with URL [//content-autofill.googleapis.com:443]
2021/03/16 03:31:55 [Info] [3636104220] app/dispatcher: sniffed domain: content-autofill.googleapis.com
2021/03/16 03:31:55 [Info] [3636104220] app/dispatcher: taking detour [proxy] for [tcp:content-autofill.googleapis.com:443]
2021/03/16 03:31:55 [Info] [3636104220] common/mux: dispatching request to tcp:content-autofill.googleapis.com:443
2021/03/16 03:31:55 127.0.0.1:13481 accepted //content-autofill.googleapis.com:443 [http -> proxy]
2021/03/16 03:31:57 [Info] [661455169] proxy/http: request to Method [GET] Host [speed.hetzner.de] with URL [http://speed.hetzner.de/1GB.bin]
2021/03/16 03:31:57 [Info] [661455169] app/dispatcher: taking detour [proxy] for [tcp:speed.hetzner.de:80]
2021/03/16 03:31:57 127.0.0.1:13483 accepted http://speed.hetzner.de/1GB.bin [http -> proxy]
2021/03/16 03:31:57 [Info] [661455169] common/mux: dispatching request to tcp:speed.hetzner.de:80
2021/03/16 03:32:04 [Info] [3089783846] app/proxyman/inbound: connection ends > proxy/http: connection ends > context canceled
2021/03/16 03:32:04 [Info] [3089783846] common/mux: failed to fetch all input > io: read/write on closed pipe
2021/03/16 03:32:14 [Info] [3925178453] proxy/socks: TCP Connect request to tcp:172.217.161.127:80
2021/03/16 03:32:14 [Info] [3925178453] app/dispatcher: sniffed domain: 172.217.161.127
2021/03/16 03:32:14 [Info] [3925178453] app/dispatcher: taking detour [proxy] for [tcp:172.217.161.127:80]
2021/03/16 03:32:14 [Info] [3925178453] common/mux: dispatching request to tcp:172.217.161.127:80
2021/03/16 03:32:14 tcp:127.0.0.1:13486 accepted tcp:172.217.161.127:80 [socks -> proxy]
2021/03/16 03:32:18 [Warning] [661455169] app/proxyman/inbound: connection ends > proxy/http: connection ends > proxy/http: failed to write response > readfrom tcp 127.0.0.1:10809->127.0.0.1:13483: write tcp 127.0.0.1:10809->127.0.0.1:13483: wsasend: An established connection was aborted by the software in your host machine.
2021/03/16 03:32:18 [Info] [661455169] common/mux: failed to fetch all input > io: read/write on closed pipe
2021/03/16 03:32:31 [Info] [3655023966] proxy/http: request to Method [CONNECT] Host [91.108.56.126:443] with URL [//91.108.56.126:443]
2021/03/16 03:32:31 [Info] [3655023966] app/dispatcher: taking detour [proxy] for [tcp:91.108.56.126:443]
2021/03/16 03:32:31 127.0.0.1:13487 accepted //91.108.56.126:443 [http -> proxy]
2021/03/16 03:32:31 [Info] [3655023966] common/mux: dispatching request to tcp:91.108.56.126:443
2021/03/16 03:32:31 [Info] [651274111] proxy/http: request to Method [POST] Host [91.108.56.126:80] with URL [http://91.108.56.126:80/api]
2021/03/16 03:32:31 [Info] [651274111] app/dispatcher: taking detour [proxy] for [tcp:91.108.56.126:80]
2021/03/16 03:32:31 127.0.0.1:13488 accepted http://91.108.56.126:80/api [http -> proxy]
2021/03/16 03:32:31 [Info] [651274111] common/mux: dispatching request to tcp:91.108.56.126:80
2021/03/16 03:32:32 [Info] [4251557576] proxy/http: request to Method [CONNECT] Host [91.108.56.126:443] with URL [//91.108.56.126:443]
2021/03/16 03:32:32 [Info] [4251557576] app/dispatcher: taking detour [proxy] for [tcp:91.108.56.126:443]
2021/03/16 03:32:32 [Info] [4251557576] common/mux: dispatching request to tcp:91.108.56.126:443
2021/03/16 03:32:32 127.0.0.1:13489 accepted //91.108.56.126:443 [http -> proxy]
2021/03/16 03:32:32 [Info] [3580108128] proxy/http: request to Method [POST] Host [91.108.56.126:80] with URL [http://91.108.56.126:80/api]
2021/03/16 03:32:32 [Info] [3580108128] app/dispatcher: taking detour [proxy] for [tcp:91.108.56.126:80]
2021/03/16 03:32:32 127.0.0.1:13490 accepted http://91.108.56.126:80/api [http -> proxy]
2021/03/16 03:32:32 [Info] [3580108128] common/mux: dispatching request to tcp:91.108.56.126:80
2021/03/16 03:32:34 [Info] [1259979847] proxy/http: request to Method [CONNECT] Host [91.108.56.126:443] with URL [//91.108.56.126:443]
2021/03/16 03:32:34 [Info] [1259979847] app/dispatcher: taking detour [proxy] for [tcp:91.108.56.126:443]
2021/03/16 03:32:34 127.0.0.1:13491 accepted //91.108.56.126:443 [http -> proxy]
2021/03/16 03:32:34 [Info] [1259979847] common/mux: dispatching request to tcp:91.108.56.126:443
2021/03/16 03:32:34 [Info] [4013888291] proxy/http: request to Method [POST] Host [91.108.56.126:80] with URL [http://91.108.56.126:80/api]
2021/03/16 03:32:34 [Info] [4013888291] app/dispatcher: taking detour [proxy] for [tcp:91.108.56.126:80]
2021/03/16 03:32:34 [Info] [4013888291] common/mux: dispatching request to tcp:91.108.56.126:80
2021/03/16 03:32:34 127.0.0.1:13492 accepted http://91.108.56.126:80/api [http -> proxy]
2021/03/16 03:32:34 [Info] transport/internet/websocket: creating connection to tcp:117.34.14.30:80
2021/03/16 03:32:34 [Info] proxy/vmess/outbound: tunneling request to tcp:v1.mux.cool:9527 via tcp:117.34.14.30:80

**Comment by z826540272** [comment]
日志是A机场相关。

**Comment by JimhHan** [comment]
感谢反馈。
已知问题，提交前请查询已有 issue。
