### ISSUE TITLE
AC86U运行Xray-linux-arm64-v8a报错out of memory

### ISSUE THREAD

**Issue by Tsukimeizi** [XTLS/Xray-core#38]
@RT-AC86U-A9E0:/tmp/home/root# uname -a
Linux RT-AC86U-A9E0 4.1.27 #2 SMP PREEMPT Fri Aug 14 16:38:14 EDT 2020 aarch64 ASUSWRT-Merlin

@RT-AC86U-A9E0:/tmp/home/root# free -m
             total       used       free     shared    buffers     cached
Mem:        440368     240308     200060      38272          0      53572
-/+ buffers/cache:     186736     253632
Swap:            0          0          0

@RT-AC86U-A9E0:/tmp/home/root# ./ray
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x9a4be7, 0x16)
        runtime/panic.go:1116 +0x54 fp=0x7ff895cc60 sp=0x7ff895cc30 pc=0x41714
runtime.sysMap(0x4000000000, 0x4000000, 0x105dd38)
        runtime/mem_linux.go:169 +0xbc fp=0x7ff895cca0 sp=0x7ff895cc60 pc=0x2686c
runtime.(*mheap).sysAlloc(0x10417a0, 0x400000, 0x7ff895cdb8, 0x3501c)
        runtime/malloc.go:727 +0x188 fp=0x7ff895cd50 sp=0x7ff895cca0 pc=0x1b3b8
runtime.(*mheap).grow(0x10417a0, 0x1, 0x0)
        runtime/mheap.go:1344 +0x80 fp=0x7ff895cdc0 sp=0x7ff895cd50 pc=0x35250
runtime.(*mheap).allocSpan(0x10417a0, 0x1, 0x2a00, 0x105dd48, 0x0)
        runtime/mheap.go:1160 +0x5ec fp=0x7ff895ce40 sp=0x7ff895cdc0 pc=0x3504c
runtime.(*mheap).alloc.func1()
        runtime/mheap.go:907 +0x60 fp=0x7ff895cea0 sp=0x7ff895ce40 pc=0x6a620
runtime.(*mheap).alloc(0x10417a0, 0x1, 0x7ff895012a, 0x25f44)
        runtime/mheap.go:901 +0x64 fp=0x7ff895cef0 sp=0x7ff895cea0 pc=0x34674
runtime.(*mcentral).grow(0x1054658, 0x0)
        runtime/mcentral.go:506 +0x74 fp=0x7ff895cf40 sp=0x7ff895cef0 pc=0x262b4
runtime.(*mcentral).cacheSpan(0x1054658, 0x1cd18)
        runtime/mcentral.go:177 +0x41c fp=0x7ff895cfd0 sp=0x7ff895cf40 pc=0x2600c
runtime.(*mcache).refill(0x7f8d62e108, 0x2a)
        runtime/mcache.go:142 +0xbc fp=0x7ff895d000 sp=0x7ff895cfd0 pc=0x2596c
runtime.(*mcache).nextFree(0x7f8d62e108, 0xffffffffffffff2a, 0x105b178, 0x102a240, 0x7ff895d098)
        runtime/malloc.go:880 +0x8c fp=0x7ff895d050 sp=0x7ff895d000 pc=0x1badc
runtime.mallocgc(0x180, 0x991c80, 0x7ff895d101, 0x7ff895d158)
        runtime/malloc.go:1061 +0x6b4 fp=0x7ff895d110 sp=0x7ff895d050 pc=0x1c324
runtime.newobject(0x991c80, 0x45078)
        runtime/malloc.go:1195 +0x38 fp=0x7ff895d140 sp=0x7ff895d110 pc=0x1c738
runtime.malg(0x8000, 0x0)
        runtime/proc.go:3514 +0x2c fp=0x7ff895d190 sp=0x7ff895d140 pc=0x4c07c
runtime.mpreinit(0x102a240)
        runtime/os_linux.go:340 +0x28 fp=0x7ff895d1b0 sp=0x7ff895d190 pc=0x3ee68
runtime.mcommoninit(0x102a240, 0xffffffffffffffff)
        runtime/proc.go:663 +0xdc fp=0x7ff895d200 sp=0x7ff895d1b0 pc=0x4519c
runtime.schedinit()
        runtime/proc.go:565 +0xa4 fp=0x7ff895d270 sp=0x7ff895d200 pc=0x44cf4
runtime.rt0_go(0x7ff895de47, 0x0, 0x7ff895de4d, 0x7ff895de70, 0x7ff895de7f, 0x7ff895deaa, 0x7ff895deb2, 0x7ff895debd, 0x7ff895ded0, 0x7ff895dee0, ...)
        runtime/asm_arm64.s:69 +0xb4 fp=0x7ff895d2a0 sp=0x7ff895d270 pc=0x70cf4

**Comment by rprx** [comment]
场景、版本、配置分别是？

**Comment by Tsukimeizi** [comment]
asus ac86u路由meilin固件跑xray，uname -a可以看到aarch64，运行xray v1.1.1和v1.0.0的arm64版本都报上面的错误，但是换成arm32后正常

配置
{
    "log": {
        "loglevel": "info"
    },
    "inbounds": [
        {
            "port": 1080,
            "protocol": "socks",
            "settings": {
                "auth": "noauth",
                "udp": true
            },
            "sniffing": {
                "enabled": true,
                "destOverride": ["http", "tls"]
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "XXXX",
                        "port": 233,
                        "users": [
                            {
                                "id": "XXXX",
                                "flow": "xtls-rprx-splice",
                                "encryption": "none"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls"
            },
            "tag": "proxy"
        },
        {
            "protocol": "freedom",
            "settings": {},
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "settings": {},
            "tag": "block"
        }
    ]
}

**Comment by rprx** [comment]
是启动即报错还是？

**Comment by Tsukimeizi** [comment]
是启动报错

**Comment by rprx** [comment]
你在 Project X 群里吗？请私聊我，需要一些测试

**Comment by rprx** [comment]
另外，v2ray-core v4.32.1 和 v4.33.0 是否有这样的问题？

**Comment by Tsukimeizi** [comment]
谢谢，我不在群里，v2ray的arm64一样，不过问题已经解决。
golang会自动申请较大的内存，导致虚拟内存不足，扩一下swap分区就好了。

**Comment by rprx** [comment]
https://github.com/XTLS/Xray-core/issues/10

可否在原来的环境下试试 v2ray-core v4.31.3？这个版本还没内置 JSON 解析

https://github.com/v2fly/v2ray-core/releases/tag/v4.31.3

**Comment by rprx** [comment]
https://github.com/XTLS/Xray-core/releases/tag/v1.1.4

**Comment by ax003** [comment]
这是有ac86u可以用的插件了？
