### ISSUE TITLE
## Hey, I've Got an Idea: Upgrading GeoIP and Geosite to Rule-sets

### ISSUE THREAD

**Issue by surfacing7336** [XTLS/Xray-core#3814]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

So, here's the thing. Xray's current GeoIP and Geosite setup works, but there's room for improvement. I've been looking at sing-box, and they've switched to a rule-set system that seems to be working really well for them.

I'm thinking we could do something similar for Xray. Why don't we consider moving to a rule-set system? It's not a huge leap, but it could make a big difference.

### The Good Stuff (Benefits)
1. It'll likely run faster with optimized data structures.
2. We'd get more flexibility in how we set things up.
3. Updates and maintenance should be easier.
4. You could add your own rules alongside the standard GeoIP/Geosite data.
5. And it might even use less memory and match things quicker.

I really think this could be a significant improvement for Xray. What are your thoughts on this? Is it something you'd be interested in exploring?

### Reproduction Method

Based 

### Client config

<details><pre><code>

</code></pre></details>

### Server config

<details><pre><code>

</code></pre></details>

### Client log

<details><pre><code>

</code></pre></details>

### Server log

<details><pre><code>

</code></pre></details>

**Comment by Fangliding** [comment]
The current system is working well and there is no need to refactor. Perhaps we can make it compatible .srs file, but we currently have no plans to do so, pr is welcome
