### ISSUE TITLE
nginx前置转发xray时，xray无法获取真实请求IP

### ISSUE THREAD

**Issue by pmkol** [XTLS/Xray-core#3825]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

我的服务端部署结构是：
nginx(stream) -> xray(trojan) -> nginx(http)
以上已经全部开启了proxy_protocol且通信正常

---

测试过程：

通过浏览器请求trojan域名，正常回落到 nginx(http) 这一级，在 nginx(http) 落地这一级的日志中，发现无法获取客户端真实IP，而都是127.0.0.1

追溯到 xray(trojan) 层，日志中的请求IP也都是127.0.0.1；（貌似proxy_protocol没有传输真实IP）

追溯到 nginx(stream) 层，日志中可以获取真实的请求IP；

将部署结构修改为 nginx(stream) -> nginx(http) 测试，nginx(http) 层可以正确获取真实的请求IP；

将部署结构修改为 nginx(stream) -> 其它golang程序 (use proxy_protocol) 测试，其它golang程序日志中能返回真实请求IP。

---

相关配置文件已经贴出，xray在上游使用nginx stream转发时，要怎么获取真实客户端IP呢？

这个问题是不是xray监听时没有通过proxy_protocol传输真实请求IP的原因导致的？

后续测试补充：又用uds的方法回落到nginx，经测试回落后端nginx时proxy_protocol是可以携带IP的，
应该是nginx(stream) -> xray(trojan) 这个阶段，xray没有通过proxy_protocol拿到前置nginx携带的真实IP。

### 重现方式

-

### 客户端配置

-

### 服务端配置

xray
<details><pre><code>
    "inbounds": [
        {
            "listen": "127.0.0.1",
            "port": 8081,
            "protocol": "trojan",
            "settings": {
                "clients": [
                    {
                        "password":"123456"
                    }
                ],
                "fallbacks": [
                    {
                        "dest": "8043",
                        "xver": 1      #这里v1与v2都测试过
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "none",
                "sockopt": {
                    "tcpFastOpen": false,
                    "domainStrategy": "UseIP",
                    "acceptProxyProtocol": true,      #这里开启了ProxyProtocol
                    "tcpcongestion": "bbr"
                }
            }
        },
}
</code></pre></details>

nginx 1.26.2 stream
<details><pre><code>
stream {
    server {
        listen 443;
        server_name xxx.xxx.xxx;

        ssl_preread on;

        proxy_protocol on;
        proxy_pass unix:/dev/shm/trojan_nginx.sock;
    }

    server {
        listen unix:/dev/shm/trojan_nginx.sock ssl proxy_protocol reuseport;

        access_log /data/wwwlogs/trojan_nginx.log proxy;

        ssl_certificate /data/ssl/xxx.pem;
        ssl_certificate_key /data/ssl/xxx.key;
        ssl_session_cache shared:SSL:8m;
        ssl_session_tickets on;
        ssl_session_timeout 1440m;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        ssl_ecdh_curve X25519:secp384r1;
        ssl_conf_command Ciphersuites TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384;
        ssl_ciphers TLS-AES-128-GCM-SHA256:TLS-AES-256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305;
        ssl_alpn h2 http/1.1;

        set_real_ip_from 0.0.0.0/0;

        proxy_protocol on;
        proxy_pass 127.0.0.1:8081;
    }
}
</code></pre></details>

nginx 1.26.2 http
<details><pre><code>
http {
    server {
        listen 8043 proxy_protocol;
        http2 on;      #关闭h2的测试过，获取不到真实IP
        server_name xxx.xxx.xxx;

        access_log /data/wwwlogs/fallback_nginx.log web;

        proxy_set_header Host            $host;
        proxy_set_header X-Real-IP       $proxy_protocol_addr;
        proxy_set_header X-Forwarded-For $proxy_protocol_addr;

        set_real_ip_from 0.0.0.0/0;
        #real_ip_header X-Forwarded-For;      #写入X-Forwarded-For的头测试过，获取不到真实IP
        real_ip_header proxy_protocol;

        location / {
            return 404;
        }
    }
}
</code></pre></details>

### 客户端日志

-

### 服务端日志

xray日志
<details><pre><code>
2024/09/17 13:26:48 from 127.0.0.1:47430 accepted tcp:api.github.com:443
2024/09/17 13:26:50 from 127.0.0.1:47446 rejected  proxy/trojan: not trojan protocol
2024/09/17 13:27:19 from 127.0.0.1:35064 accepted tcp:www.google.com:443
</code></pre></details>

nginx stream 日志
<details><pre><code>
123.123.123.123 - [17/Sep/2024:13:26:42 +0800] TLSv1.3/TLS_AES_128_GCM_SHA256 h2 xxx.xxx.xxx 200 287 454
123.123.123.123 - [17/Sep/2024:13:26:43 +0800] TLSv1.3/TLS_AES_128_GCM_SHA256 h2 xxx.xxx.xxx 200 311 373
123.123.123.123 - [17/Sep/2024:13:27:20 +0800] TLSv1.3/TLS_AES_128_GCM_SHA256 h2 xxx.xxx.xxx 200 4805 1617
</code></pre></details>

nginx http 日志
（log_format 的请求IP相关配置 $remote_addr - $proxy_protocol_addr - ...）
<details><pre><code>
127.0.0.1 - 127.0.0.1 - [17/Sep/2024:13:26:50 +0800] "GET / HTTP/2.0" 503 592 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
127.0.0.1 - 127.0.0.1 - [17/Sep/2024:13:26:50 +0800] "GET /favicon.ico HTTP/2.0" 503 592 "https://xxx.xxx.xxx/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"

#后面又用uds的方法回落到nginx，发回落时proxy_protocol是可以携带IP的
unix: - 127.0.0.1 - [17/Sep/2024:23:21:35 +0800] "GET / HTTP/2.0" 503 592 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
unix: - 127.0.0.1 - [17/Sep/2024:23:21:35 +0800] "GET /favicon.ico HTTP/2.0" 503 592 "https://xxx.xxx.xxx/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
</code></pre></details>

**Comment by Fangliding** [comment]
streamsettings这个accept proxy protocol似乎有点buggy(或许学隔壁删掉？) 而且不知道能不能和vless这个xver一起用

**Comment by pmkol** [comment]
> streamsettings这个accept proxy protocol似乎有点buggy(或许学隔壁删掉？) 而且不知道能不能和vless这个xver一起用

用uds的方法回落到nginx测试了一下，会返回127.0.0.1这个IP，说明回落后端nginx时proxy_protocol是可以携带IP的，
应该是nginx(stream) -> xray(trojan) 这个阶段，xray没有通过proxy_protocol拿到前置nginx携带的真实IP导致的

所以只需要解决当nginx前置且开启proxy_protocol时，xray无法通过proxy_protocol拿到真实请求IP的问题，应该就可以了

**Comment by JotmKKmkLTzE** [comment]
你好， nginx stream 在使用 unix套接字 与  下面的 server 通信时， proxy_protocol 会失效，需换用 127.0.0.1:8080 等 ip:port 的方式 与 下面的 server 进行通信，此时 proxy_protocol  会生效。

**Comment by pmkol** [comment]
> 你好， nginx stream 在使用 unix套接字 与 下面的 server 通信时， proxy_protocol 会失效，需换用 127.0.0.1:8080 等 ip:port 的方式 与 下面的 server 进行通信，此时 proxy_protocol 会生效。 并且 ，server代码段中，通过proxy_protocol 获取真实ip时，使用： set_real_ip_from 127.0.0.1 ; real_ip_header proxy_protocol; 此时，$remote_addr 的值 会被改成 真实来源ip。

```
stream {
server {
    listen 443;
    server_name xxx.xxx.xxx;
    ssl_preread on;

    proxy_protocol on;
    proxy_pass unix:/dev/shm/trojan_nginx.sock;
}

server {
    listen unix:/dev/shm/trojan_nginx.sock ssl proxy_protocol reuseport;

    access_log /data/wwwlogs/trojan_nginx.log proxy;

    ssl_certificate /data/ssl/xxx.pem;
    ssl_certificate_key /data/ssl/xxx.key;
    ssl_session_cache shared:SSL:8m;
    ssl_session_tickets on;
    ssl_session_timeout 1440m;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ecdh_curve X25519:secp384r1;
    ssl_conf_command Ciphersuites TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384;
    ssl_ciphers TLS-AES-128-GCM-SHA256:TLS-AES-256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305;
    ssl_alpn h2 http/1.1;

    set_real_ip_from 0.0.0.0/0;

    proxy_protocol on;
    proxy_pass 127.0.0.1:8081;
}
}
```

与xray通信的nginx，就是使用IP回源的啊，不过我是转发了2次，你的意思是，nginx两个stream server之间的通信也需要用IP才可以么？

**Comment by pmkol** [comment]
> 你好， nginx stream 在使用 unix套接字 与 下面的 server 通信时， proxy_protocol 会失效，需换用 127.0.0.1:8080 等 ip:port 的方式 与 下面的 server 进行通信，此时 proxy_protocol 会生效。 并且 ，server代码段中，通过proxy_protocol 获取真实ip时，使用： set_real_ip_from 127.0.0.1 ; real_ip_header proxy_protocol; 此时，$remote_addr 的值 会被改成 真实来源ip。

测试了一下，的确是上面我说的问题，可以正确获取IP了，感谢

**Comment by Fangliding** [comment]
这汤姆不是 nginx(uds)→nginx(ip)→xray(ip)→nginx么 proxy protocol在最前面就丢了。。

**Comment by pmkol** [comment]
> 这汤姆不是 nginx(uds)→nginx(ip)→xray(ip)→nginx么 proxy protocol在最前面就丢了。。

proxy protocol没有丢，我又测试了下
nginx(ip)→nginx(uds)→xray(uds)→nginx，开启proxy protocol后是可以获取真实IP的

但如果第一级用nginx(uds)，就需要在stream加set_real_ip_from unix:，但这样不知为何，后面的xray直接就不接收数据了
