### ISSUE TITLE
splithttp not working after network switch

### ISSUE THREAD

**Issue by kabo00os** [XTLS/Xray-core#3831]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [x] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

I have a problem
After connecting, splithttp works fine, but if the Wi-Fi network changes, the connection is not established (but after several minutes, the connection is established sometimes)

This problem can be clearly seen in the phone programs when the phone goes to sleep mode, after waking up the connection is not established and the X-ray core must be loaded again.

this problem with h2 and http/1.1

### Reproduction Method

Change network

### Client config

<details><pre><code>
-
</code></pre></details>

### Server config

<details><pre><code>
-
</code></pre></details>

### Client log

<details><pre><code>
2024/09/19 07:52:41 [Info] transport/internet/splithttp: failed to send download http request > Get "***/b2d8443c-3f37-4b26-b5d2-c050990d8f63?x_padding=0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000": context canceled
2024/09/19 07:52:47 [Info] [229683001] proxy/socks: TCP Connect request to tcp:alive.github.com:443
</code></pre></details>

### Server log

<details><pre><code>
-
</code></pre></details>

**Comment by Fangliding** [comment]
Not following the template, unable to reproduce. I tested myself that splithttp can recover after switching network
This is usually related to the power-saving strategy of Android apps and devices, and is unlikely to be the core issue

**Comment by mmmray** [comment]
I recommend to use `"xmux": {"cMaxLifetimeMs": 30000}` to work around such issues, but you have to wait for the new version. I have heard about issues like this a lot in the context of splithttp, but am also unable to reproduce.

**Comment by kabo00os** [comment]
> I recommend to use `"xmux": {"cMaxLifetimeMs": 30000}` to work around such issues, but you have to wait for the new version. I have heard about issues like this a lot in the context of splithttp, but am also unable to reproduce.

I checked all the settings but the problem is not solved
Tested platforms: Mac, Android, iOS

I checked with 4 different ISPs
