### ISSUE TITLE
hi in new ver xray i get this error when xray restart

### ISSUE THREAD

**Issue by moh3nasiyat** [XTLS/Xray-core#3833]
hi in new ver xray i get this error when xray restart

"Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: Failed to build SplitHTTP config. > infra/conf: maxConnections cannot be specified together with maxConcurrency"

_Originally posted by @moh3nasiyat in https://github.com/XTLS/Xray-core/issues/3806#issuecomment-2360260995_

**Comment by Fangliding** [comment]
Please fill in the template. At least provide config file
