### ISSUE TITLE
xray启动不了

### ISSUE THREAD

**Issue by yy028** [XTLS/Xray-core#3834]
![image](https://github.com/user-attachments/assets/b5298664-0377-4fcf-9bed-2516d985583d)

**Comment by yy028** [comment]
这是怎么回事，求大佬指点

**Comment by yy028** [comment]
> 问题模板
不好意思我不清楚配置模板什么意思

xray配置的这个文件
{
    "log": {
        "loglevel": "warning"
    },
    "inbounds": [
        {
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "72bac1c4-02de-49b4-e498-fa8767638c23", 
                        "flow": "xtls-rprx-direct"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": 8388
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "alpn": [
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "/usr/local/etc/xray/server.crt", 
                            "keyFile": "/usr/local/etc/xray/server.key"
                        }
                    ]
                }
            }
        },
        {
            "port": 8388,
            "listen": "127.0.0.1",
            "protocol": "trojan",
            "settings": {
                "clients": [
                    {
                        "password": "111"
                    }
                ],
                "fallbacks": [
                    {
                        "dest": "180.76.138.44:80"
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "none"
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ]
}

**Comment by Fangliding** [comment]
开issue的时候会选模板 开空的还得点下面一行小字 可以瞎看不到小字看不懂英文 不会瞎看不到大字和中文吧
说回这个xtls-rprx-direct已经被删了 不知道你哪抄来的远古配置

**Comment by yy028** [comment]
> 开问题的时候会选模板下面开空的还得点一行小字可以盲目看不到小字看不懂英文不会盲目看不到大字和中文吧 说回这个xtls-rprx-direct已经被删了不知道你哪个抄本的远古配置

那我删掉

**Comment by yy028** [comment]
怎么删除啊，太抱歉了

**Comment by Fangliding** [comment]
就这样吧没关系
