### ISSUE TITLE
routing配置了分流规则， Xray-android-arm64-v8a-V24.9.19只会走outbounds内第一个出站配置

### ISSUE THREAD

**Issue by wansenlyt** [XTLS/Xray-core#3836]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [ ] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

pixel8pro，系统为android15beta2，比如在routing配置了多个分流规则，Xray-android-arm64-v8a-V24.9.19仍只会走outbounds内第一个出站配置，而不遵守routing配置。

### 重现方式

outbounds若配置了两个以上的出站配置，第一次启动后，观察日志，可发现只有默认的第一个出站连接记录；将outbounds第二个出站调到第一位后，再次启动xray，会发现只有原第二个出站配置的日志。

### 客户端配置

以下为outbounds的省略配置：
{
  "outbounds": [
        {
    "protocol": "vless",
    "tag": "tcp-reality",
    "settings": {
      "vnext": [
       …………
    },
    {
    "protocol": "vless",
    "tag": "tcp-split",
    "settings": {
      "vnext": [
        …………
    },
}

以下为routing的省略配置：
{
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "AsIs",
      "rules": [
        "type": "field",
        "domain": [
          "domain:twimg.co",
          "domain:twimg.com",
          "domain:wikimedia.org",
          "domain:ytimg.com"
          ],
        "outboundTag": "tcp-reality"
        },
        {
        "type": "field",
        "domain": [
          "full:telegram.me",
          "full:telegram.org",
          "full:twitter.com",
          "domain:cd4o.com",
          "domain:cdn.ampproject.net",
          "domain:cdn.ampproject.org",
          "domain:certificate-transparency.org",
          "domain:youtube.com"
          ],
        "outboundTag": "tcp-split"
        },
       …………

### 服务端配置

配置未改动

### 客户端日志

首次日志：
2024/09/20 08:25:15 from tcp:127.0.0.1:60544 accepted tcp:8.8.8.8:853 [split-in >> tcp-reality]
2024/09/20 08:25:17 from tcp:127.0.0.1:60556 accepted tcp:mtalk.google.com:5228 [split-in >> tcp-reality]
2024/09/20 08:25:17 from tcp:127.0.0.1:60566 accepted tcp:mtalk.google.com:5228 [split-in >> tcp-reality]
2024/09/20 08:25:18 from tcp:127.0.0.1:56404 accepted tcp:userlocation.googleapis.com:443 [split-in >> tcp-reality]
2024/09/20 08:25:18 from tcp:127.0.0.1:56410 accepted tcp:geomobileservices-pa.googleapis.com:443 [split-in >> tcp-reality]
2024/09/20 08:25:19 from tcp:127.0.0.1:56422 accepted tcp:www.youtube.com:443 [split-in >> tcp-reality]
…………

将 tcp-split调整为首要出站配置后的日志：
2024/09/20 08:27:24 from tcp:127.0.0.1:53756 accepted tcp:www.gstatic.com:80 [split-in >> tcp-split]
2024/09/20 08:27:28 from tcp:127.0.0.1:58450 accepted tcp:www.gstatic.com:80 [socks-in >> tcp-split]
2024/09/20 08:27:30 from udp:127.0.0.1:55722 accepted udp:8.8.8.8:443 [split-in >> tcp-split]
2024/09/20 08:28:01 from tcp:127.0.0.1:57370 accepted tcp:raw.githubusercontent.com:443 [split-in >> tcp-split]
2024/09/20 08:29:01 from tcp:127.0.0.1:49476 accepted tcp:www.youtube.com:443 [split-in >> tcp-split]
2024/09/20 08:29:01 from tcp:127.0.0.1:49466 accepted tcp:www.youtube.com:443 [split-in >> tcp-split]
2024/09/20 08:29:01 from tcp:127.0.0.1:49488 accepted tcp:www.youtube.com:443 [split-in >> tcp-split]
…………

### 服务端日志

无

**Comment by RPRX** [comment]
@Fangliding

**Comment by Fangliding** [comment]
![image](https://github.com/user-attachments/assets/5e0d9444-e116-4db1-a9ea-c55032d7cab2)
你这个配置格式都是错的

**Comment by KobeArthurScofield** [comment]
这是已经废弃的旧式配置，已经干掉了。
routing 下面直接就是 rules。

顺便好奇一下哪里抄来的配置，现在的文档都没有的

**Comment by Fangliding** [comment]
自己看路由文档 老早以前就被移除 前段时间把代码删了
