### ISSUE TITLE
使用SplitHTTP访问speed.cloudflare.com测速上传时日志报错

### ISSUE THREAD

**Issue by Tsukimeizi** [XTLS/Xray-core#3839]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [ ] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

speed.cloudflare.com测速上传时卡顿，日志报错。

### 重现方式

访问speed.cloudflare.com测速。

### 客户端配置

<details><pre><code>
    {
      "tag": "proxy-out-hk",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "x.x.x.x",
            "port": 443,
            "users": [
              {
                "id": "XXXX",
                "encryption": "none"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "splithttp",
        "splithttpSettings": {
          "path": "/split",
          "host": "XXXX",
          "scMinPostsIntervalMs": "10-20"
        },
        "security": "tls",
        "tlsSettings": {
          "serverName": "XXXX"
        }
      }
    },
</code></pre></details>

### 服务端配置

<details><pre><code>
{
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "XXXX"
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "splithttp",
        "splithttpSettings": {
          "path": "/split",
          "host": "XXXX"
        },
        "security": "tls",
        "tlsSettings": {
          "serverName": "XXXX",
          "certificates": [
            {
              "certificateFile": "/usr/local/bin/XXXX.crt",
              "keyFile": "/usr/local/bin/XXXX.key"
            }
          ]
        }
      }
    }
</code></pre></details>

### 客户端日志

<details><pre><code>
2024/09/21 20:33:28 [Info] [3801258153] transport/internet/splithttp: failed to send upload > transport/internet/splithttp: bad status code:500 Internal Server Error
2024/09/21 20:33:28 [Info] [3801258153] transport/internet/splithttp: failed to send upload > transport/internet/splithttp: bad status code:500 Internal Server Error
2024/09/21 20:33:28 [Info] [3801258153] transport/internet/splithttp: failed to send upload > transport/internet/splithttp: bad status code:500 Internal Server Error
2024/09/21 20:33:29 [Info] [1360372902] transport/internet/splithttp: failed to send upload > transport/internet/splithttp: bad status code:500 Internal Server Error
</code></pre></details>

### 服务端日志

<details><pre><code>
2024/09/21 20:33:28 [Info] [1641031247] app/proxyman/outbound: app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: connection ends > proxy/freedom: failed to process request > writev tcp x.x.x.x:44110->172.66.0.218:443: writev: connection reset by peer
2024/09/21 20:33:28 [Info] [1641031247] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to transfer request payload > io: read/write on closed pipe
2024/09/21 20:33:28 [Info] transport/internet/splithttp: failed to upload > transport/internet/splithttp: splithttp packet queue closed
2024/09/21 20:33:28 [Info] transport/internet/splithttp: failed to upload > transport/internet/splithttp: splithttp packet queue closed
2024/09/21 20:33:28 [Info] transport/internet/splithttp: failed to upload > transport/internet/splithttp: splithttp packet queue closed
2024/09/21 20:33:29 [Info] [273689716] app/proxyman/outbound: app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: connection ends > proxy/freedom: failed to process request > writev tcp x.x.x.x:44096->172.66.0.218:443: writev: connection reset by peer
2024/09/21 20:33:29 [Info] [273689716] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to transfer response payload > io: read/write on closed pipe
2024/09/21 20:33:29 [Info] transport/internet/splithttp: failed to upload > transport/internet/splithttp: splithttp packet queue closed
2024/09/21 20:33:29 [Info] transport/internet/splithttp: failed to upload > transport/internet/splithttp: splithttp packet queue closed
</code></pre></details>

**Comment by Fangliding** [comment]
已知问题 已经强调上传性能有限
