### ISSUE TITLE
安卓版1.4.0在骁龙625设备下性能过低

### ISSUE THREAD

**Issue by kanshurichard** [XTLS/Xray-core#384]
Xray版本1.4.0使用Xray4Magisk部署在Android10.0/骁龙625 CPU的设备上（联想TB-8703N）：

协议为VLESS+TCP+XTLS

功能正常，但网速极慢，如Google Play下载，大约50-200kB/s。已试过切换direct和splice，速度基本不变。

直连国内网速正常。

**使用V2rayNG APP连接相同服务器，速度正常（2MB/s+)**

另一台小米9（骁龙855/安卓11），使用完全相同的Magisk方法和配置文件部署，连接相同服务器，网速正常（5MB/s+）

骁龙625和855性能的确存在差距，但似乎不应该有这几十上百倍的差距。

怀疑是否部分代码与骁龙625的Cortex-A53架构不兼容？

希望可以有更多朋友在各种安卓设备上测试。

**Comment by CerteKim** [comment]
提供以下 /data/xray/run/service.log

**Comment by JimhHan** [comment]
请尝试使用tls

**Comment by kanshurichard** [comment]
[service.log](https://github.com/XTLS/Xray-core/files/6149478/service.log)

文件在此。谢谢。

另外，使用V2rayNG APP连接相同服务器，速度正常（2MB/s+)

**Comment by CerteKim** [comment]
appid.list bypass 配置错误，不能用包名，只能用 appid。

**Comment by CerteKim** [comment]
不过速度问题可能不是来自于 appid.list 的配置错误，提供一下 error.log （注意删除敏感信息）

**Comment by kanshurichard** [comment]
的确，恢复为ALL后，性能没有变化

[error.log](https://github.com/XTLS/Xray-core/files/6149625/error.log)

**Comment by JimhHan** [comment]
@kanshurichard 
是否方便加入我们的 [tg群](https://t.me/projectXray)？

**Comment by kanshurichard** [comment]
已切换TLS测试，Google Play性能基本没有变（50-100kB/s）
Speedtest性能比XTLS下降约一半（10-20Mbps下降到5-10Mbps），看起来符合XTLS更省资源的设定

所以看起来不是XTLS的问题
依旧怀疑DNS
但是小米9下面Google Play速度就极快，DNS都是同样的设定

**Comment by kanshurichard** [comment]
把小米9的所有配置文件完整复制过来之后，Google Play下载速度提升了几倍（500KB/s)，基本符合骁龙625的性能了

看起来应该是之前动某个DNS文件时候，改成一个访问Google Play很慢的源了。

抱歉耽误大家时间了。
