### ISSUE TITLE
xtls-rprx-vision 回落 trojan 出现问题

### ISSUE THREAD

**Issue by 5points** [XTLS/Xray-core#3841]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

内核版本是Xray 24.9.19
流控使用的是xtls-rprx-vision
回落服务有两个: 一个是trojan，一个为shadowsocks。
目前情况是：
vless+xtls-rprx-vision是可以使用的
也成功回落了8445端口的shadowsocks，android和pc端的（v2rayN和v2rayng）都可以使用。
唯独就是trojan没法成功回落，并且也无法使用。
即使我把8446端口的trojan服务换成vless还是shadowsocks，依旧也无法使用。
我参考的资料如下：
https://xtls.github.io/document/level-1/fallbacks-lv1.html
https://github.com/XTLS/Xray-examples/blob/main/VLESS-TCP-XTLS-Vision/config_server.json

### 重现方式

即使我把8446端口改成别的，亦或者trojan协议换成vless或shadowsocks，也和描述一样，无法使用（回落）
<details><pre><code>
  "inbounds": [
    {
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "xray uuid",
            "flow": "xtls-rprx-vision"
          }
        ],
        "decryption": "none",
		"fallbacks": [
		  {
			"dest": 8446,
			"xver": 1
		  },
		  {
			"dest": 8445,
			"xver": 1
		  }
		]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "tls",
        "tlsSettings": {
			"rejectUnknownSni": true,
			"minVersion": "1.2",
			"certificates": [
			     {
					 "ocspStapling": 3600,
					 "certificateFile": "/path/certs/cert.cer",
					 "keyFile": "/path/certs/cert.key"
				 }
            ],
            "alpn": [
              "http/1.1",
			  "h2"
            ]			  
		},
        "kcpSettings": {},
        "wsSettings": {},
        "httpSettings": {},
        "quicSettings": {},
        "grpcSettings": {},
        "realitySettings": {}
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls",
          "quic"
        ]
      }
	},
    {
      "listen": "127.0.0.1",
      "port": 8446,
      "protocol": "shadowsocks",
      "settings": {
         "method": "2022-blake3-chacha20-poly1305",
         "password": "openssl rand -base64 32"
      },
      "streamSettings": {
        "network": "tcp",
        "security": "none",
        "tlsSettings": {},
        "tcpSettings": {
		  "acceptProxyProtocol": true
		},
        "kcpSettings": {},
        "wsSettings": {},
        "httpSettings": {},
        "quicSettings": {},
        "grpcSettings": {}
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls",
          "quic"
        ]
      }
    },
    {
      "listen": "127.0.0.1",
      "port": 8445,
      "protocol": "shadowsocks",
      "settings": {
         "method": "2022-blake3-chacha20-poly1305",
         "password": "openssl rand -base64 32"
      },
      "streamSettings": {
        "network": "tcp",
        "security": "none",
        "tlsSettings": {},
        "tcpSettings": {
		  "acceptProxyProtocol": true
		},
        "kcpSettings": {},
        "wsSettings": {},
        "httpSettings": {},
        "quicSettings": {},
        "grpcSettings": {}
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls",
          "quic"
        ]
      }
    }
  ]
</code></pre></details>

### 客户端配置

<details><pre><code>
N/A
</code></pre></details>

### 服务端配置

<details><pre><code>
{
  "log": {
    "access": "/var/log/xray/access.log",
    "error": "/var/log/xray/error.log",
    "loglevel": "info"
  },
  "inbounds": [
    {
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "xray uuid",
            "flow": "xtls-rprx-vision"
          }
        ],
        "decryption": "none",
		"fallbacks": [
		  {
			"dest": 8446,
			"xver": 1
		  },
		  {
			"dest": 8445,
			"xver": 1
		  }
		]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "tls",
        "tlsSettings": {
			"rejectUnknownSni": true,
			"minVersion": "1.2",
			"certificates": [
			     {
					 "ocspStapling": 3600,
					 "certificateFile": "/path/certs/cert.cer",
					 "keyFile": "/path/certs/cert.key"
				 }
            ],
            "alpn": [
              "http/1.1",
			  "h2"
            ]			  
		},
        "kcpSettings": {},
        "wsSettings": {},
        "httpSettings": {},
        "quicSettings": {},
        "grpcSettings": {},
        "realitySettings": {}
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls",
          "quic"
        ]
      }
	},
    {
	  "listen": "127.0.0.1",
      "port": 8446,
      "protocol": "trojan",
      "settings": {
		 "clients": [
		     {
                 "password": "password",
				 "level": 0
			 }
		 ],
      "decryption":"none",
	  "fallbacks": [
	    {
		  "dest": 8181
		}
	   ]
	  },
      "streamSettings": {
        "network": "tcp",
        "security": "none",
        "tcpSettings": {
		  "acceptProxyProtocol": true
		}
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls",
          "quic"
        ]
      }
    },
    {
      "listen": "127.0.0.1",
      "port": 8445,
      "protocol": "shadowsocks",
      "settings": {
         "method": "2022-blake3-chacha20-poly1305",
         "password": "openssl rand -base64 32"
      },
      "streamSettings": {
        "network": "tcp",
        "security": "none",
        "tlsSettings": {},
        "tcpSettings": {
		  "acceptProxyProtocol": true
		},
        "kcpSettings": {},
        "wsSettings": {},
        "httpSettings": {},
        "quicSettings": {},
        "grpcSettings": {}
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls",
          "quic"
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "block"
    }
  ],
  "routing": {
    "rules": [
      {
        "type": "field",
        "ip": [
          "geoip:cn",
          "geoip:private",
          "0.0.0.0/8",
          "10.0.0.0/8",
          "100.64.0.0/10",
          "169.254.0.0/16",
          "172.16.0.0/12",
          "192.0.0.0/24",
          "192.0.2.0/24",
          "192.168.0.0/16",
          "198.18.0.0/15",
          "198.51.100.0/24",
          "203.0.113.0/24",
          "::1/128",
          "fc00::/7",
          "fe80::/10"
        ],
        "outboundTag": "block"
      },
      {
        "type": "field",
        "outboundTag": "blocked",
        "domain": [
          "geosite:cn",
          "geosite:geolocation-cn"
        ]
      },
      {
        "type": "field",
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ]
      }
    ]
  }
}
</code></pre></details>

### 客户端日志

<details><pre><code>
N/A
</code></pre></details>

### 服务端日志

<details><pre><code>
2024/09/22 00:54:54 [Debug] app/log: Logger started
2024/09/22 00:54:54 [Debug] app/router: MphDomainMatcher is enabled for 11276 domain rule(s)
2024/09/22 00:54:54 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:443
2024/09/22 00:54:54 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:8446
2024/09/22 00:54:54 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:8445
2024/09/22 00:54:54 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:443
2024/09/22 00:54:54 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:8446
2024/09/22 00:54:54 [Warning] transport/internet/tcp: accepting PROXY protocol
2024/09/22 00:54:54 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:8445
2024/09/22 00:54:54 [Warning] transport/internet/tcp: accepting PROXY protocol
2024/09/22 00:54:54 [Warning] core: Xray 24.9.19 started
2024/09/22 00:55:43 [Info] [618579228] proxy/vless/inbound: firstLen = 350
2024/09/22 00:55:43 [Info] [618579228] proxy/vless/inbound: fallback starts > proxy/vless/encoding: invalid request version
2024/09/22 00:55:43 [Info] [618579228] proxy/vless/inbound: realName = dog.meow.fox
2024/09/22 00:55:43 [Info] [618579228] proxy/vless/inbound: realAlpn = http/1.1
2024/09/22 00:55:43 [Info] [716299557] app/proxyman/inbound: connection ends > shadowsocks: serve TCP from 111.222.33.444:64952: chacha20poly1305: message authentication failed
2024/09/22 00:55:43 [Info] [618579228] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > read tcp 192.168.0.160:443->111.222.33.444:64952: use of closed network connection
2024/09/22 00:56:28 [Info] [2725070513] proxy/vless/inbound: firstLen = 851
2024/09/22 00:56:28 [Info] [2725070513] proxy/vless/inbound: fallback starts > proxy/vless/encoding: invalid request version
2024/09/22 00:56:28 [Info] [2725070513] proxy/vless/inbound: realName = dog.meow.fox
2024/09/22 00:56:28 [Info] [2725070513] proxy/vless/inbound: realAlpn = http/1.1
2024/09/22 00:56:28 [Info] [1844146854] proxy/shadowsocks_2022: tunnelling request to tcp:www.google.com:443
2024/09/22 00:56:28 [Info] [1844146854] app/dispatcher: sniffed domain: www.google.com
2024/09/22 00:56:28 [Info] [1844146854] app/dispatcher: default route for tcp:www.google.com:443
2024/09/22 00:56:28 [Info] [1844146854] transport/internet/tcp: dialing TCP to tcp:www.google.com:443
2024/09/22 00:56:28 [Debug] [1844146854] transport/internet: dialing to tcp:www.google.com:443
2024/09/22 00:56:28 [Info] [1844146854] proxy/freedom: connection opened to tcp:www.google.com:443, local endpoint 192.168.0.160:6502, remote endpoint 142.250.197.100:443
2024/09/22 00:56:28 [Info] [1844146854] proxy: CopyRawConn readv
2024/09/22 00:56:30 [Info] [2725070513] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > context canceled
/var/log/xray # cat error.log 
2024/09/22 00:54:54 [Debug] app/log: Logger started
2024/09/22 00:54:54 [Debug] app/router: MphDomainMatcher is enabled for 11276 domain rule(s)
2024/09/22 00:54:54 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:443
2024/09/22 00:54:54 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:8446
2024/09/22 00:54:54 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:8445
2024/09/22 00:54:54 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:443
2024/09/22 00:54:54 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:8446
2024/09/22 00:54:54 [Warning] transport/internet/tcp: accepting PROXY protocol
2024/09/22 00:54:54 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:8445
2024/09/22 00:54:54 [Warning] transport/internet/tcp: accepting PROXY protocol
2024/09/22 00:54:54 [Warning] core: Xray 24.9.19 started
2024/09/22 00:55:43 [Info] [618579228] proxy/vless/inbound: firstLen = 350
2024/09/22 00:55:43 [Info] [618579228] proxy/vless/inbound: fallback starts > proxy/vless/encoding: invalid request version
2024/09/22 00:55:43 [Info] [618579228] proxy/vless/inbound: realName = dog.meow.fox
2024/09/22 00:55:43 [Info] [618579228] proxy/vless/inbound: realAlpn = http/1.1
2024/09/22 00:55:43 [Info] [716299557] app/proxyman/inbound: connection ends > shadowsocks: serve TCP from 111.222.33.444:64952: chacha20poly1305: message authentication failed
2024/09/22 00:55:43 [Info] [618579228] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > read tcp 192.168.0.160:443->111.222.33.444:64952: use of closed network connection
2024/09/22 00:56:28 [Info] [2725070513] proxy/vless/inbound: firstLen = 851
2024/09/22 00:56:28 [Info] [2725070513] proxy/vless/inbound: fallback starts > proxy/vless/encoding: invalid request version
2024/09/22 00:56:28 [Info] [2725070513] proxy/vless/inbound: realName = dog.meow.fox
2024/09/22 00:56:28 [Info] [2725070513] proxy/vless/inbound: realAlpn = http/1.1
2024/09/22 00:56:28 [Info] [1844146854] proxy/shadowsocks_2022: tunnelling request to tcp:www.google.com:443
2024/09/22 00:56:28 [Info] [1844146854] app/dispatcher: sniffed domain: www.google.com
2024/09/22 00:56:28 [Info] [1844146854] app/dispatcher: default route for tcp:www.google.com:443
2024/09/22 00:56:28 [Info] [1844146854] transport/internet/tcp: dialing TCP to tcp:www.google.com:443
2024/09/22 00:56:28 [Debug] [1844146854] transport/internet: dialing to tcp:www.google.com:443
2024/09/22 00:56:28 [Info] [1844146854] proxy/freedom: connection opened to tcp:www.google.com:443, local endpoint 192.168.0.160:6502, remote endpoint 142.250.197.100:443
2024/09/22 00:56:28 [Info] [1844146854] proxy: CopyRawConn readv
2024/09/22 00:56:30 [Info] [2725070513] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > context canceled
2024/09/22 00:56:55 [Info] [3499473975] proxy/vless/inbound: firstLen = 1186
2024/09/22 00:56:55 [Info] [3499473975] proxy/vless/inbound: received request for tcp:www.google.com:443
2024/09/22 00:56:55 [Info] [3499473975] proxy: Xtls Unpadding new block, content 579 padding 739 command 0
2024/09/22 00:56:55 [Info] [3499473975] proxy: XtlsFilterTls found tls client hello! 579
2024/09/22 00:56:55 [Info] [3499473975] app/dispatcher: sniffed domain: www.google.com
2024/09/22 00:56:55 [Info] [3499473975] app/dispatcher: default route for tcp:www.google.com:443
2024/09/22 00:56:55 [Info] [3499473975] transport/internet/tcp: dialing TCP to tcp:www.google.com:443
2024/09/22 00:56:55 [Debug] [3499473975] transport/internet: dialing to tcp:www.google.com:443
2024/09/22 00:56:55 [Info] [3499473975] proxy/freedom: connection opened to tcp:www.google.com:443, local endpoint 192.168.0.160:44776, remote endpoint 142.250.197.100:443
2024/09/22 00:56:55 [Info] [3499473975] proxy: XtlsFilterTls found tls 1.3! 219 TLS_AES_256_GCM_SHA384
2024/09/22 00:56:55 [Info] [3499473975] proxy: XtlsPadding 219 1041 0
2024/09/22 00:56:56 [Info] [3499473975] proxy: Xtls Unpadding new block, content 80 padding 936 command 0
2024/09/22 00:56:56 [Info] [3499473975] proxy: Xtls Unpadding new block, content 74 padding 1038 command 2
2024/09/22 00:56:56 [Info] [3499473975] proxy: CopyRawConn readv
2024/09/22 00:56:56 [Info] [3499473975] proxy: XtlsPadding 778 226 2
/var/log/xray # cat error.log 
2024/09/22 00:54:54 [Debug] app/log: Logger started
2024/09/22 00:54:54 [Debug] app/router: MphDomainMatcher is enabled for 11276 domain rule(s)
2024/09/22 00:54:54 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:443
2024/09/22 00:54:54 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:8446
2024/09/22 00:54:54 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:8445
2024/09/22 00:54:54 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:443
2024/09/22 00:54:54 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:8446
2024/09/22 00:54:54 [Warning] transport/internet/tcp: accepting PROXY protocol
2024/09/22 00:54:54 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:8445
2024/09/22 00:54:54 [Warning] transport/internet/tcp: accepting PROXY protocol
2024/09/22 00:54:54 [Warning] core: Xray 24.9.19 started
2024/09/22 00:55:43 [Info] [618579228] proxy/vless/inbound: firstLen = 350
2024/09/22 00:55:43 [Info] [618579228] proxy/vless/inbound: fallback starts > proxy/vless/encoding: invalid request version
2024/09/22 00:55:43 [Info] [618579228] proxy/vless/inbound: realName = dog.meow.fox
2024/09/22 00:55:43 [Info] [618579228] proxy/vless/inbound: realAlpn = http/1.1
2024/09/22 00:55:43 [Info] [716299557] app/proxyman/inbound: connection ends > shadowsocks: serve TCP from 111.222.33.444:64952: chacha20poly1305: message authentication failed
2024/09/22 00:55:43 [Info] [618579228] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > read tcp 192.168.0.160:443->111.222.33.444:64952: use of closed network connection
2024/09/22 00:56:28 [Info] [2725070513] proxy/vless/inbound: firstLen = 851
2024/09/22 00:56:28 [Info] [2725070513] proxy/vless/inbound: fallback starts > proxy/vless/encoding: invalid request version
2024/09/22 00:56:28 [Info] [2725070513] proxy/vless/inbound: realName = dog.meow.fox
2024/09/22 00:56:28 [Info] [2725070513] proxy/vless/inbound: realAlpn = http/1.1
2024/09/22 00:56:28 [Info] [1844146854] proxy/shadowsocks_2022: tunnelling request to tcp:www.google.com:443
2024/09/22 00:56:28 [Info] [1844146854] app/dispatcher: sniffed domain: www.google.com
2024/09/22 00:56:28 [Info] [1844146854] app/dispatcher: default route for tcp:www.google.com:443
2024/09/22 00:56:28 [Info] [1844146854] transport/internet/tcp: dialing TCP to tcp:www.google.com:443
2024/09/22 00:56:28 [Debug] [1844146854] transport/internet: dialing to tcp:www.google.com:443
2024/09/22 00:56:28 [Info] [1844146854] proxy/freedom: connection opened to tcp:www.google.com:443, local endpoint 192.168.0.160:6502, remote endpoint 142.250.197.100:443
2024/09/22 00:56:28 [Info] [1844146854] proxy: CopyRawConn readv
2024/09/22 00:56:30 [Info] [2725070513] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > context canceled
2024/09/22 00:56:55 [Info] [3499473975] proxy/vless/inbound: firstLen = 1186
2024/09/22 00:56:55 [Info] [3499473975] proxy/vless/inbound: received request for tcp:www.google.com:443
2024/09/22 00:56:55 [Info] [3499473975] proxy: Xtls Unpadding new block, content 579 padding 739 command 0
2024/09/22 00:56:55 [Info] [3499473975] proxy: XtlsFilterTls found tls client hello! 579
2024/09/22 00:56:55 [Info] [3499473975] app/dispatcher: sniffed domain: www.google.com
2024/09/22 00:56:55 [Info] [3499473975] app/dispatcher: default route for tcp:www.google.com:443
2024/09/22 00:56:55 [Info] [3499473975] transport/internet/tcp: dialing TCP to tcp:www.google.com:443
2024/09/22 00:56:55 [Debug] [3499473975] transport/internet: dialing to tcp:www.google.com:443
2024/09/22 00:56:55 [Info] [3499473975] proxy/freedom: connection opened to tcp:www.google.com:443, local endpoint 192.168.0.160:44776, remote endpoint 142.250.197.100:443
2024/09/22 00:56:55 [Info] [3499473975] proxy: XtlsFilterTls found tls 1.3! 219 TLS_AES_256_GCM_SHA384
2024/09/22 00:56:55 [Info] [3499473975] proxy: XtlsPadding 219 1041 0
2024/09/22 00:56:56 [Info] [3499473975] proxy: Xtls Unpadding new block, content 80 padding 936 command 0
2024/09/22 00:56:56 [Info] [3499473975] proxy: Xtls Unpadding new block, content 74 padding 1038 command 2
2024/09/22 00:56:56 [Info] [3499473975] proxy: CopyRawConn readv
2024/09/22 00:56:56 [Info] [3499473975] proxy: XtlsPadding 778 226 2
2024/09/22 00:57:14 [Info] [826697406] proxy/vless/inbound: firstLen = 658
2024/09/22 00:57:14 [Info] [826697406] proxy/vless/inbound: fallback starts > proxy/vless/encoding: invalid request version
2024/09/22 00:57:14 [Info] [826697406] proxy/vless/inbound: realName = dog.meow.fox
2024/09/22 00:57:14 [Info] [826697406] proxy/vless/inbound: realAlpn = http/1.1
2024/09/22 00:57:14 [Info] [466711338] app/proxyman/inbound: connection ends > shadowsocks: serve TCP from 111.222.33.444:65023: chacha20poly1305: message authentication failed
2024/09/22 00:57:14 [Info] [826697406] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > read tcp 192.168.0.160:443->111.222.33.444:65023: use of closed network connection
</code></pre></details>

**Comment by RPRX** [comment]
https://xtls.github.io/config/features/fallback.html#%E8%A1%A5%E5%85%85%E8%AF%B4%E6%98%8E

> 若配置了几个 alpn 和 path 均相同的子元素，则会以最后的为准。
