### ISSUE TITLE
error: Wrong format of time, it should be in the format of 12:34:56, under 10:00:00 should be start with 0, e.g. 01:23:45.

### ISSUE THREAD

**Issue by alexlii1971** [XTLS/Xray-core#3848]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

If run:

bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install --logrotate $time

It will show:

root@Xray:~# bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install --logrotate
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 31107  100 31107    0     0  68824      0 --:--:-- --:--:-- --:--:-- 68824
error: Wrong format of time, it should be in the format of 12:34:56, under 10:00:00 should be start with 0, e.g. 01:23:45.

### Reproduction Method

run:

bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install --logrotate $time

### Client config

<details><pre><code>
1
</code></pre></details>

### Server config

<details><pre><code>
1
</code></pre></details>

### Client log

<details><pre><code>
1
</code></pre></details>

### Server log

<details><pre><code>
1
</code></pre></details>

**Comment by Fangliding** [comment]
As its requirement
