### ISSUE TITLE
在最新的iOS17.6.1和iOS18系统上面，连上海外的节点，访问WebSocket的地址，无法正常通信

### ISSUE THREAD

**Issue by yang1339** [XTLS/Xray-core#3849]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

1. 在iOS18和iOS17.6.1上面出现，采用的是Shadowsrocket客户端，连的海外的节点
2. 直接连接是可以正常访问的，在低版本的iOS上面也可以正常访问,在17.3，17.5的版本上都有测试
3. 脱离了环境之后，采用网上的WebSocket测试工具测试接口，也做了测试，直接连可以正常访问和通信，连上VPN不能访问

### 重现方式

在这个地址上面可以连接测试地址：http://tools.fun/websocket.html
测试地址可以是任何WebSocket的服务：ws://124.222.224.186:8800，
在直接连的时候，可以得到正常的反馈，连上VPN就没有反应了，实际上可以连上

### 客户端配置

<details><pre><code>

</code></pre></details>

### 服务端配置

<details><pre><code>

</code></pre></details>

### 客户端日志

<details><pre><code>

</code></pre></details>

### 服务端日志

<details><pre><code>

</code></pre></details>

**Comment by Fangliding** [comment]
小火箭的问题来这干什么
