### ISSUE TITLE
求大哥拉我入tg群啊，回答错误了4次问题

### ISSUE THREAD

**Issue by 5165153** [XTLS/Xray-core#3851]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

我的tg号是：https://t.me/xianbei11451419198109

### Reproduction Method

我的tg号是：https://t.me/xianbei11451419198109

### Client config

我的tg号是：https://t.me/xianbei11451419198109

### Server config

我的tg号是：https://t.me/xianbei11451419198109

### Client log

我的tg号是：https://t.me/xianbei11451419198109

### Server log

我的tg号是：https://t.me/xianbei11451419198109

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/discussions/3844#discussioncomment-10718390

**Comment by RPRX** [comment]
这种bt的问题已经存在几年了，其实最开始我觉得风扇设置的这些问题~~严重限制了群人数的增长~~，但后来我觉得人不在多而在精，入群考验的是独立查找答案的能力~~以及一点点运气~~，只有这样才能保证群的高质量交流，~~以及珍惜留在群里的资格不要违反群规~~
