### ISSUE TITLE
splithttp xPaddingBytes format error

### ISSUE THREAD

**Issue by ahmad0489** [XTLS/Xray-core#3854]
``` json
//A number in " "
"xPaddingBytes": "100"

//empty
"xPaddingBytes": ""

//-1 in " "
"xPaddingBytes": "-1"
```
These are giving error from xray-core, please check and fix this problem.

**Comment by Fangliding** [comment]
better have a change

**Comment by mmmray** [comment]
@ahmad0489 out of curiosity, did this get triggered by some panel/

**Comment by ahmad0489** [comment]
> @ahmad0489 out of curiosity, did this get triggered by some panel?

No! I found this bug with v2rayNG. At first, I thought that the problem was with my json, but after checking the log, I realized that the problem was with xray.
@mmmray
