### ISSUE TITLE
outbounds tag无法生效

### ISSUE THREAD

**Issue by jh0072110** [XTLS/Xray-core#3858]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

在https://github.com/XTLS/Xray-core/commit/697156f6f6fee139ed16c6585c73addd1b49d961 构建中，outbounds tag貌似无法生效

### 重现方式

通过geosite进行分流至某一outbounds tag时（比方说解锁流媒体的落地服务器），该tag无法生效，落地服务器也没有连入logs

### 客户端配置

不重要的部分

### 服务端配置

outbounds:
  - tag: IP4_out
    protocol: freedom
    settings:
      domainStrategy: UseIPv4
  - tag: IP6_out
    protocol: freedom
    settings:
      domainStrategy: UseIPv6
  - tag: Unlock
    protocol: shadowsocks
    settings:
      servers:
        - address: "落地IP"
          port: 1234
          method: 2022-blake3-aes-128-gcm
          password: ooxx

### 客户端日志

不重要的部分2

### 服务端日志

可能不重要的部分

**Comment by jh0072110** [comment]
找到问题了，不能乱该tcp成raw……

**Comment by blog2020** [comment]
我用ss 2022-blake3-aes-128-gcm出站无法连接，楼主你是怎么解决的，说一下吧
