### ISSUE TITLE
Reality无法回落itunes.apple.com，one-piece.com

### ISSUE THREAD

**Issue by 5165153** [XTLS/Xray-core#3860]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

使用itunes.apple.com，还有one-piece.com作为回落，会分别遇到

1.Invalid URL
The requested URL "[no URL]", is invalid.
Reference #9.bfa86468.1727691316.16367aea

https://errors.edgesuite.net/9.bfa86468.1727691316.16367aea

2.此站点的连接不安全
example ip 使用不受支持的协议。
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

报错，不知道为什么，又应该如何解决

### 重现方式

将回落配置为itunes.apple.com，还有one-piece.com，浏览器直接访问https://ip

### 客户端配置

<details><pre><code>
 "realitySettings": {
                    "dest": "itunes.apple.com:443", // You can also use `one-piece.com:443` as dest
                    "serverNames": [
                        "itunes.apple.com"   
</code></pre></details>

### 服务端配置

<details><pre><code>
 "realitySettings": {
                    "dest": "itunes.apple.com:443", // You can also use `one-piece.com:443` as dest
                    "serverNames": [
                        "itunes.apple.com"   
</code></pre></details>

### 客户端日志

null error

### 服务端日志

null error

**Comment by RPRX** [comment]
> 浏览器直接访问https://ip

？
