### ISSUE TITLE
add MASQUE protocol support

### ISSUE THREAD

**Issue by developer861** [XTLS/Xray-core#3861]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

Cloudflare Warp has recently integrated a new tunneling protocol called MASQUE, which enhances stability and speed, particularly in regions such as Iran and China. Based on my tests, it performs faster than WireGuard. 
I recommend implementing this new protocol into the Xray-core.

https://blog.cloudflare.com/unlocking-quic-proxying-potential/

https://quic-go.net/docs/masque/

https://blog.cloudflare.com/masque-building-a-new-protocol-into-cloudflare-warp/

https://blog.cloudflare.com/zero-trust-warp-with-a-masque/

### Reproduction Method

isn't needed

### Client config

isn't needed

### Server config

isn't needed

### Client log

isn't needed

### Server log

isn't needed

**Comment by RPRX** [comment]
懒得 decrypt，需要等开源或有 spec

还有 MASQUE 现在能不能用 Cloudflare 的那些 Web IP？如果不能的话挺鸡肋的，GFW 直接把 MASQUE IP 都封了就能封死了

**Comment by developer861** [comment]
yes it's currently working on cloudflare official client in latest beta release 

and i just saw this project
https://github.com/quic-go/masque-go

the implementation of protocol in go i guess it might help

**Comment by Fangliding** [comment]
SNI是固定的 随随便便就ban掉了  xray的嗅探都能毙掉 没必要盯着cf薅还多加一个出站
