### ISSUE TITLE
[Feature Request] 在redirect模式的透明代理中记录URL到access log

### ISSUE THREAD

**Issue by someonewating** [XTLS/Xray-core#3864]
Hi Community,

在redirect的透明代理下，我发现从dokodemo-door 入栈的流量在access log中只会显示IP地址，不会像http proxy入栈那样显示URL。我认为这对审计来说非常不方便。因此，请问开发团队是否有对dokodemo-door 入栈的流量的URL写入access log的计划？

举例来说，如果我想知道有一个网站在流经xray时被哪一个路由规则匹配，在http proxy的入栈下，我可以直接从access log看到我的URL以及对应的处理方式(proxiy, direct, or block)。但在dokodemo-door 入栈下只能看到IP地址。

我的配置:
```
{
      "tag": "transparent",
      "port": 10000,
      "protocol": "dokodemo-door",
      "listen": "0.0.0.0",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ],
        "metadataOnly": false,
        "routeOnly": true
      },
      "settings": {
        "network": "tcp,udp",
        "followRedirect": true
      },
      "streamSettings": {
        "sockopt": {
          "tproxy": "redirect"
        }
      }
    }
```

access log中看到的：`2024/10/01 00:00:00 172.20.0.3:52170 accepted tcp:34.96.126.106:443 [transparent -> block]`

我尝试过将log level调低，调整到debug后是可以从error.log中看到：`2024/10/01 00:00:00[Info] [4086000000] app/dispatcher: sniffed domain: stats.grafana.org`。这说明xray其实是探测到了我实际请求的URL的。

我查阅了相关信息，找到了一个issue [在tproxy的透明代理入站的access log中显示域名](https://github.com/XTLS/Xray-core/issues/834)，说是expected behavior。也在tg群里请教了下，结论也是如上。

介于此，我认为没有必要只在debug level下才把这个信息展示出来，把探测到的URL放入access log会使access log更加易读。

我没有软件开发经验，没法对代码进行分析以尝试理解当前为什么access log在dokodemo-door 仅记录IP。还请各位大佬看下我的理解对不对，能不能把这个功能添加进来。如果是我的配置有误，恳请指正。

提前拜谢！

**Comment by Fangliding** [comment]
close as expected 的意思是这个行为是没毛病的 和预期的一样 不是bug 不是说你反馈的行为是预期的
tproxy接收的就是ip连接 所以就显示ip连接 sniff是其他模块

**Comment by someonewating** [comment]
Hi @Fangliding ， 我知道这是个expected behavior，但这个issue的主要目的是feature request，我只是在feature request的基础上问下有没有可能是我的配置错了。

如果配置没错的话我还是想提个feature request。我觉得既然error log在debug下能探测到url，那把url写入access log是一个很reasonable的行为啊。

**Comment by someonewating** [comment]
我去，有大佬已经提pr #3865 了。
