### ISSUE TITLE
[FR] Connection lifetime limit for Mux.Cool

### ISSUE THREAD

**Issue by fodhelper** [XTLS/Xray-core#3868]
Hi,
Some days ago i was playing with Mux.Cool and Xmux settings and was monitoring results on Wireshark
then i noticed when a connection is alive more a long time (on CDN IP) it's speed will get limited and cMaxLifetimeMs of Xmux did a great job to solve this problem, but Mux.Cool does not have such a feature (for HTTP/1.1)
so mmmray suggested me to create this feature request to add a feature like cMaxLifetimeMs of Xmux to Mux.Cool

**Comment by Fangliding** [comment]
planned, no need a new issue
