### ISSUE TITLE
pls add amnezia support

### ISSUE THREAD

**Issue by helpmebro911** [XTLS/Xray-core#3869]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

https://github.com/Slava-Shchipunov/awg-openwrt
https://docs.amnezia.org/en/documentation/amnezia-wg/#working-principle
pls add amnezia support

### Reproduction Method

https://github.com/Slava-Shchipunov/awg-openwrt
https://docs.amnezia.org/en/documentation/amnezia-wg/#working-principle
pls add amnezia support

### Client config

https://github.com/Slava-Shchipunov/awg-openwrt
https://docs.amnezia.org/en/documentation/amnezia-wg/#working-principle
pls add amnezia support

### Server config

<details><pre><code>

</code></pre></details>

### Client log

<details><pre><code>

</code></pre></details>

### Server log

<details><pre><code>

</code></pre></details>

**Comment by Fangliding** [comment]
?
