### ISSUE TITLE
splithttp能不能支持reality

### ISSUE THREAD

**Issue by nicelic** [XTLS/Xray-core#3870]
目前使用了splithttp，效果很好。但使用tls加密就会暴露自己域名，而且使用“冷门域名”tls加密加上大流量，一封一个准，容易被封；不使用tls加密，则会退回到http1.1，速度和开销变高，尤其移动网络大概率会频繁的断开重新握手，体验更差。能不能加上reality进行伪装，或者不是呀tls加密时http2.0是一个可选项。

**Comment by RPRX** [comment]
XHTTP 会支持 REALITY，但你这写的像是 #from_
