### ISSUE TITLE
splithttp  9.19、9.30内核设置并发数时崩溃

### ISSUE THREAD

**Issue by nicelic** [XTLS/Xray-core#3872]
我使用的是xui，xray内核，19  30设置最大并发数，只要重启内核就会崩溃无法重启，但只要设置成零就行了。至于是xray还是xui没有去深究。
另外，splithttp使用http1.1在Wireshark抓取数据包时可以看到多个http1.1连接。使用http2.0  tls加密时只看到一次握手，即使使用大流量也没有看到建立第二个握手，我在下载数据时忽快忽慢，波动较大，随即断开该连接整个下载暂停，之后抓取数据包，只看到一个tls握手。是不是splithttp使用http2.0 tls后所有数据都走在了一个https里面，那么该splithttp与其他的https有个区别。

**Comment by Fangliding** [comment]
issue模板

**Comment by mmmray** [comment]
#3835 is the fix for the crash

xmux is the answer if you want multiple tls handshakes with h2
