### ISSUE TITLE
无法编译

### ISSUE THREAD

**Issue by ChaingTsung** [XTLS/Xray-core#3874]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

![image](https://github.com/user-attachments/assets/50bb2bad-ba60-473b-8094-7ad44f2c236a)
```log
holive@Holive-Router:~$ git clone https://github.com/XTLS/Xray-core.git
正克隆到 'Xray-core'...
remote: Enumerating objects: 14021, done.
remote: Counting objects: 100% (5415/5415), done.
remote: Compressing objects: 100% (1932/1932), done.
remote: Total 14021 (delta 4324), reused 3561 (delta 3464), pack-reused 8606 (from 1)
接收对象中: 100% (14021/14021), 5.23 MiB | 4.02 MiB/s, 完成.
处理 delta 中: 100% (9979/9979), 完成.
holive@Holive-Router:~$ cd Xray-core && go mod download
go: gvisor.dev/gvisor@v0.0.0-20231202080848-1f7806d17489: invalid version: unknown revision 1f7806d17489
```

### Reproduction Method

![image](https://github.com/user-attachments/assets/3b291396-6419-4cd4-973e-27a2adc6205a)

### Client config

<details><pre><code>

</code></pre></details>

### Server config

<details><pre><code>

</code></pre></details>

### Client log

<details><pre><code>
![image](https://github.com/user-attachments/assets/372732cd-2fb4-430c-8aa9-5ae45a2a6f46)

</code></pre></details>

### Server log

<details><pre><code>
![image](https://github.com/user-attachments/assets/dc40cd77-3e2b-413c-8039-3b857111e644)

</code></pre></details>

**Comment by Fangliding** [comment]
本地go的什么问题 无法复现 不是核心问题

**Comment by MHSanaei** [comment]
@Fangliding 
hey how are you?
sorry i don't want to open an issue for my problem but can you check this
https://pkg.go.dev/github.com/xtls/xray-core
the package stuck on v1.8.24 as latest version please fix it

**Comment by chise0713** [comment]
maybe golang only recognize versions that follows semver?

**Comment by Fangliding** [comment]
> @Fangliding hey how are you? sorry i don't want to open an issue for my problem but can you check this https://pkg.go.dev/github.com/xtls/xray-core the package stuck on v1.8.24 as latest version please fix it

It is a problem, might need some change to fix

**Comment by RPRX** [comment]
@MHSanaei https://github.com/XTLS/Xray-core/issues/3875#issuecomment-2391506170

**Comment by RPRX** [comment]
@ChaingTsung 关于你的问题，似乎部分 goproxy 并没有该版本的 gvisor，曾经打算 fork 一份进 Project X

**Comment by crazypeace** [comment]
https://zelikk.blogspot.com/2024/10/xray-gvisor-github-codespaces.html
