### ISSUE TITLE
Nothing work after updating xray on the linux server  to version 24.9.30.

### ISSUE THREAD

**Issue by alegz81** [XTLS/Xray-core#3879]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

After updating xray on the server and client to version 24.9.30, nothing works. 
If I return version 1.8.24 on the server, then everything works.
Tested on two different servers with Ubuntu LTS

### Reproduction Method

Server Ubuntu 24.04.1 LTS or Ubuntu 22.04.5 LTS
xray v24.9.30 on server

### Client config

<details><pre><code>
{
  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "socks",
      "port": 1080,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "allowTransparent": false
      }
    },
    {
      "tag": "http",
      "port": 1081,
      "listen": "127.0.0.1",
      "protocol": "http",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "udp": false,
        "allowTransparent": false
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "server ip",
            "port": 63573,
            "users": [
              {
                "id": "uuid",
                "alterId": 0,
                "email": "blabla",
                "security": "auto"
              }
            ]
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    }
  ],
  "routing": {
    "domainStrategy": "AsIs",
    "domainMatcher": "linear",
    "rules": [
      {
        "type": "field",
        "outboundTag": "proxy",
        "domain": [
          "geosite:google"
        ],
        "enabled": true
      },
      {
        "type": "field",
        "outboundTag": "block",
        "domain": [
          "geosite:category-ads-all"
        ],
        "enabled": true
      }
    ]
  }
}

</code></pre></details>

### Server config

<details><pre><code>
{
  "log": {
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": 63573,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "uuid",
            "level": 1,
            "alterId": 0,
            "security": "auto",
            "email": "blabla"
          },
          {
            "id": "uuid",
            "level": 1,
            "alterId": 0,
            "security": "auto",
            "email": "blabla2"
          }
        ]
      }
    }
  ],
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "rules": [
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      }
    ]
  },
  "dns": {
    "servers": [
      "1.1.1.1"
    ]
  }
}
</code></pre></details>

### Client log

<details><pre><code>
Xray 24.9.30 (Xray, Penetrates Everything.) 3b06af8 (go1.23.1 windows/amd64)
A unified platform for anti-censorship.
2024/10/04 17:06:53 [Info] infra/conf/serial: Reading config: &{Name:swe.json Format:json}
2024/10/04 17:06:53 [Debug] app/log: Logger started
2024/10/04 17:06:53 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:1080
2024/10/04 17:06:53 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:1081
2024/10/04 17:06:53 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1080
2024/10/04 17:06:53 [Info] transport/internet/udp: listening UDP on 127.0.0.1:1080
2024/10/04 17:06:53 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:1081
2024/10/04 17:06:53 [Warning] core: Xray 24.9.30 started
2024/10/04 17:06:57 [Info] [824875022] proxy/socks: TCP Connect request to tcp:edge.microsoft.com:443
2024/10/04 17:06:57 [Info] [824875022] app/dispatcher: sniffed domain: edge.microsoft.com
2024/10/04 17:06:57 from tcp:127.0.0.1:55377 accepted tcp:edge.microsoft.com:443 [socks >> proxy]
2024/10/04 17:06:57 [Info] [824875022] app/dispatcher: default route for tcp:edge.microsoft.com:443
2024/10/04 17:06:57 [Info] [824875022] transport/internet/tcp: dialing TCP to tcp:server-ip:63573
2024/10/04 17:06:57 [Debug] [824875022] transport/internet: dialing to tcp:server-ip:63573
2024/10/04 17:06:57 [Info] [271255380] proxy/socks: TCP Connect request to tcp:go.microsoft.com:443
2024/10/04 17:06:57 [Info] [271255380] app/dispatcher: sniffed domain: go.microsoft.com
2024/10/04 17:06:57 from tcp:127.0.0.1:55379 accepted tcp:go.microsoft.com:443 [socks >> proxy]
2024/10/04 17:06:57 [Info] [271255380] app/dispatcher: default route for tcp:go.microsoft.com:443
2024/10/04 17:06:57 [Info] [271255380] transport/internet/tcp: dialing TCP to tcp:server-ip:63573
2024/10/04 17:06:57 [Debug] [271255380] transport/internet: dialing to tcp:server-ip:63573
2024/10/04 17:06:57 [Info] [824875022] proxy/vmess/outbound: tunneling request to tcp:edge.microsoft.com:443 via server-ip:63573
2024/10/04 17:06:57 [Info] [271255380] proxy/vmess/outbound: tunneling request to tcp:go.microsoft.com:443 via server-ip:63573
2024/10/04 17:06:58 [Info] [824875022] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
2024/10/04 17:06:58 [Info] [287481691] proxy/socks: TCP Connect request to tcp:edge.microsoft.com:443
2024/10/04 17:06:58 [Info] [287481691] app/dispatcher: sniffed domain: edge.microsoft.com
2024/10/04 17:06:58 [Info] [287481691] app/dispatcher: default route for tcp:edge.microsoft.com:443
2024/10/04 17:06:58 [Info] [287481691] transport/internet/tcp: dialing TCP to tcp:server-ip:63573
2024/10/04 17:06:58 [Debug] [287481691] transport/internet: dialing to tcp:server-ip:63573
2024/10/04 17:06:58 from tcp:127.0.0.1:55384 accepted tcp:edge.microsoft.com:443 [socks >> proxy]
2024/10/04 17:06:58 [Info] [271255380] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
2024/10/04 17:06:58 [Info] [1521530420] proxy/socks: TCP Connect request to tcp:go.microsoft.com:443
2024/10/04 17:06:58 [Info] [1521530420] app/dispatcher: sniffed domain: go.microsoft.com
2024/10/04 17:06:58 [Info] [1521530420] app/dispatcher: default route for tcp:go.microsoft.com:443
2024/10/04 17:06:58 [Info] [1521530420] transport/internet/tcp: dialing TCP to tcp:server-ip:63573
2024/10/04 17:06:58 [Debug] [1521530420] transport/internet: dialing to tcp:server-ip:63573
2024/10/04 17:06:58 from tcp:127.0.0.1:55386 accepted tcp:go.microsoft.com:443 [socks >> proxy]
2024/10/04 17:06:58 [Info] [1521530420] proxy/vmess/outbound: tunneling request to tcp:go.microsoft.com:443 via server-ip:63573
2024/10/04 17:06:58 [Info] [1521530420] app/proxyman/outbound: app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > read tcp 192.168.0.201:55387->server-ip:63573: wsarecv: An existing connection was forcibly closed by the remote host.
2024/10/04 17:06:58 [Info] [1521530420] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2024/10/04 17:06:58 [Info] [1041064018] proxy/socks: TCP Connect request to tcp:edge.microsoft.com:443
2024/10/04 17:06:58 [Info] [1041064018] app/dispatcher: sniffed domain: edge.microsoft.com
2024/10/04 17:06:58 [Info] [1041064018] app/dispatcher: default route for tcp:edge.microsoft.com:443
2024/10/04 17:06:58 [Info] [1041064018] transport/internet/tcp: dialing TCP to tcp:server-ip:63573
2024/10/04 17:06:58 [Debug] [1041064018] transport/internet: dialing to tcp:server-ip:63573
2024/10/04 17:06:58 from tcp:127.0.0.1:55388 accepted tcp:edge.microsoft.com:443 [socks >> proxy]
2024/10/04 17:06:59 [Info] [1041064018] proxy/vmess/outbound: tunneling request to tcp:edge.microsoft.com:443 via server-ip:63573
2024/10/04 17:06:59 [Info] [2523817042] proxy/socks: TCP Connect request to tcp:www.bing.com:443
2024/10/04 17:06:59 [Info] [2523817042] app/dispatcher: sniffed domain: www.bing.com
2024/10/04 17:06:59 [Info] [2523817042] app/dispatcher: default route for tcp:www.bing.com:443
2024/10/04 17:06:59 [Info] [2523817042] transport/internet/tcp: dialing TCP to tcp:server-ip:63573
2024/10/04 17:06:59 [Debug] [2523817042] transport/internet: dialing to tcp:server-ip:63573
2024/10/04 17:06:59 from tcp:127.0.0.1:55390 accepted tcp:www.bing.com:443 [socks >> proxy]
2024/10/04 17:06:59 [Info] [2730026762] proxy/socks: TCP Connect request to tcp:edge.microsoft.com:443
2024/10/04 17:06:59 [Info] [275839698] proxy/socks: TCP Connect request to tcp:edge.microsoft.com:443
2024/10/04 17:06:59 [Info] [557739276] proxy/socks: TCP Connect request to tcp:www.bing.com:443
2024/10/04 17:06:59 [Info] [2730026762] app/dispatcher: sniffed domain: edge.microsoft.com
2024/10/04 17:06:59 from tcp:127.0.0.1:55396 accepted tcp:edge.microsoft.com:443 [socks >> proxy]
2024/10/04 17:06:59 [Info] [2730026762] app/dispatcher: default route for tcp:edge.microsoft.com:443
2024/10/04 17:06:59 [Info] [2730026762] transport/internet/tcp: dialing TCP to tcp:server-ip:63573
2024/10/04 17:06:59 from tcp:127.0.0.1:55397 accepted tcp:edge.microsoft.com:443 [socks >> proxy]
2024/10/04 17:06:59 [Debug] [2730026762] transport/internet: dialing to tcp:server-ip:63573
2024/10/04 17:06:59 [Info] [275839698] app/dispatcher: sniffed domain: edge.microsoft.com
2024/10/04 17:06:59 [Info] [275839698] app/dispatcher: default route for tcp:edge.microsoft.com:443
2024/10/04 17:06:59 [Info] [275839698] transport/internet/tcp: dialing TCP to tcp:server-ip:63573
2024/10/04 17:06:59 [Debug] [275839698] transport/internet: dialing to tcp:server-ip:63573
2024/10/04 17:06:59 [Info] [557739276] app/dispatcher: sniffed domain: www.bing.com
2024/10/04 17:06:59 from tcp:127.0.0.1:55398 accepted tcp:www.bing.com:443 [socks >> proxy]
2024/10/04 17:06:59 [Info] [557739276] app/dispatcher: default route for tcp:www.bing.com:443
2024/10/04 17:06:59 [Info] [557739276] transport/internet/tcp: dialing TCP to tcp:server-ip:63573
2024/10/04 17:06:59 [Debug] [557739276] transport/internet: dialing to tcp:server-ip:63573
2024/10/04 17:06:59 [Info] [2523817042] proxy/vmess/outbound: tunneling request to tcp:www.bing.com:443 via server-ip:63573
2024/10/04 17:06:59 [Info] [723716138] proxy/socks: TCP Connect request to tcp:edge.microsoft.com:443
2024/10/04 17:06:59 [Info] [4277565703] proxy/socks: TCP Connect request to tcp:edge.microsoft.com:443
2024/10/04 17:06:59 [Info] [2543541367] proxy/socks: TCP Connect request to tcp:www.bing.com:443
2024/10/04 17:06:59 [Info] [723716138] app/dispatcher: sniffed domain: edge.microsoft.com
2024/10/04 17:06:59 [Info] [723716138] app/dispatcher: default route for tcp:edge.microsoft.com:443
2024/10/04 17:06:59 [Info] [723716138] transport/internet/tcp: dialing TCP to tcp:server-ip:63573
2024/10/04 17:06:59 [Debug] [723716138] transport/internet: dialing to tcp:server-ip:63573
2024/10/04 17:06:59 from tcp:127.0.0.1:55405 accepted tcp:edge.microsoft.com:443 [socks >> proxy]
2024/10/04 17:06:59 from tcp:127.0.0.1:55406 accepted tcp:edge.microsoft.com:443 [socks >> proxy]
2024/10/04 17:06:59 [Info] [4277565703] app/dispatcher: sniffed domain: edge.microsoft.com
2024/10/04 17:06:59 [Info] [4277565703] app/dispatcher: default route for tcp:edge.microsoft.com:443
2024/10/04 17:06:59 [Info] [4277565703] transport/internet/tcp: dialing TCP to tcp:server-ip:63573
2024/10/04 17:06:59 [Debug] [4277565703] transport/internet: dialing to tcp:server-ip:63573
2024/10/04 17:06:59 [Info] [2543541367] app/dispatcher: sniffed domain: www.bing.com
2024/10/04 17:06:59 [Info] [2543541367] app/dispatcher: default route for tcp:www.bing.com:443
2024/10/04 17:06:59 [Info] [2543541367] transport/internet/tcp: dialing TCP to tcp:server-ip:63573
2024/10/04 17:06:59 [Debug] [2543541367] transport/internet: dialing to tcp:server-ip:63573
2024/10/04 17:06:59 from tcp:127.0.0.1:55407 accepted tcp:www.bing.com:443 [socks >> proxy]
2024/10/04 17:06:59 [Info] [557739276] proxy/vmess/outbound: tunneling request to tcp:www.bing.com:443 via server-ip:63573
2024/10/04 17:06:59 [Info] [275839698] proxy/vmess/outbound: tunneling request to tcp:edge.microsoft.com:443 via server-ip:63573
2024/10/04 17:06:59 [Info] [2730026762] proxy/vmess/outbound: tunneling request to tcp:edge.microsoft.com:443 via server-ip:63573
2024/10/04 17:06:59 [Info] [2523817042] app/proxyman/outbound: app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > read tcp 192.168.0.201:55391->server-ip:63573: wsarecv: An existing connection was forcibly closed by the remote host.
2024/10/04 17:06:59 [Info] [2523817042] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2024/10/04 17:06:59 [Info] [723716138] proxy/vmess/outbound: tunneling request to tcp:edge.microsoft.com:443 via server-ip:63573
2024/10/04 17:06:59 [Info] [4277565703] proxy/vmess/outbound: tunneling request to tcp:edge.microsoft.com:443 via server-ip:63573
2024/10/04 17:06:59 [Info] [2543541367] proxy/vmess/outbound: tunneling request to tcp:www.bing.com:443 via server-ip:63573
2024/10/04 17:06:59 [Info] [275839698] app/proxyman/outbound: app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > read tcp 192.168.0.201:55400->server-ip:63573: wsarecv: An existing connection was forcibly closed by the remote host.
2024/10/04 17:06:59 [Info] [275839698] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2024/10/04 17:06:59 [Info] [2730026762] app/proxyman/outbound: app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > read tcp 192.168.0.201:55399->server-ip:63573: wsarecv: An existing connection was forcibly closed by the remote host.
2024/10/04 17:06:59 [Info] [2730026762] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2024/10/04 17:06:59 [Info] [287481691] proxy/vmess/outbound: tunneling request to tcp:edge.microsoft.com:443 via server-ip:63573
2024/10/04 17:06:59 [Info] [2736837708] proxy/socks: TCP Connect request to tcp:edge.microsoft.com:443
2024/10/04 17:06:59 [Info] [2736837708] app/dispatcher: sniffed domain: edge.microsoft.com
2024/10/04 17:06:59 from tcp:127.0.0.1:55411 accepted tcp:edge.microsoft.com:443 [socks >> proxy]
2024/10/04 17:06:59 [Info] [2736837708] app/dispatcher: default route for tcp:edge.microsoft.com:443
2024/10/04 17:06:59 [Info] [2736837708] transport/internet/tcp: dialing TCP to tcp:server-ip:63573
2024/10/04 17:06:59 [Debug] [2736837708] transport/internet: dialing to tcp:server-ip:63573
2024/10/04 17:06:59 [Info] [2543541367] app/proxyman/outbound: app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > read tcp 192.168.0.201:55410->server-ip:63573: wsarecv: An existing connection was forcibly closed by the remote host.
2024/10/04 17:06:59 [Info] [2543541367] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2024/10/04 17:06:59 [Info] [1482102426] proxy/socks: TCP Connect request to tcp:www.bing.com:443
2024/10/04 17:06:59 [Info] [1482102426] app/dispatcher: sniffed domain: www.bing.com
2024/10/04 17:06:59 [Info] [1482102426] app/dispatcher: default route for tcp:www.bing.com:443
2024/10/04 17:06:59 [Info] [1482102426] transport/internet/tcp: dialing TCP to tcp:server-ip:63573
2024/10/04 17:06:59 [Debug] [1482102426] transport/internet: dialing to tcp:server-ip:63573
2024/10/04 17:06:59 from tcp:127.0.0.1:55413 accepted tcp:www.bing.com:443 [socks >> proxy]
2024/10/04 17:06:59 [Info] [1482102426] proxy/vmess/outbound: tunneling request to tcp:www.bing.com:443 via server-ip:63573
2024/10/04 17:06:59 [Info] [2736837708] proxy/vmess/outbound: tunneling request to tcp:edge.microsoft.com:443 via server-ip:63573
2024/10/04 17:06:59 [Info] [2461086850] proxy/socks: TCP Connect request to tcp:go.microsoft.com:443
2024/10/04 17:06:59 [Info] [2461086850] app/dispatcher: sniffed domain: go.microsoft.com
2024/10/04 17:06:59 [Info] [2461086850] app/dispatcher: default route for tcp:go.microsoft.com:443
2024/10/04 17:06:59 [Info] [2461086850] transport/internet/tcp: dialing TCP to tcp:server-ip:63573
2024/10/04 17:06:59 [Debug] [2461086850] transport/internet: dialing to tcp:server-ip:63573
2024/10/04 17:06:59 from tcp:127.0.0.1:55416 accepted tcp:go.microsoft.com:443 [socks >> proxy]
2024/10/04 17:07:00 [Info] [2461086850] proxy/vmess/outbound: tunneling request to tcp:go.microsoft.com:443 via server-ip:63573
2024/10/04 17:07:00 [Info] [723716138] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
2024/10/04 17:07:00 [Info] [2565234904] proxy/socks: TCP Connect request to tcp:edge.microsoft.com:443
2024/10/04 17:07:00 [Info] [2565234904] app/dispatcher: sniffed domain: edge.microsoft.com
2024/10/04 17:07:00 [Info] [2565234904] app/dispatcher: default route for tcp:edge.microsoft.com:443
2024/10/04 17:07:00 [Info] [2565234904] transport/internet/tcp: dialing TCP to tcp:server-ip:63573
2024/10/04 17:07:00 [Debug] [2565234904] transport/internet: dialing to tcp:server-ip:63573
2024/10/04 17:07:00 from tcp:127.0.0.1:55418 accepted tcp:edge.microsoft.com:443 [socks >> proxy]
2024/10/04 17:07:00 [Info] [4277565703] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
2024/10/04 17:07:00 [Info] [2747995595] proxy/socks: TCP Connect request to tcp:edge.microsoft.com:443
2024/10/04 17:07:00 [Info] [2747995595] app/dispatcher: sniffed domain: edge.microsoft.com
2024/10/04 17:07:00 [Info] [2747995595] app/dispatcher: default route for tcp:edge.microsoft.com:443
2024/10/04 17:07:00 [Info] [2747995595] transport/internet/tcp: dialing TCP to tcp:server-ip:63573
2024/10/04 17:07:00 [Debug] [2747995595] transport/internet: dialing to tcp:server-ip:63573
2024/10/04 17:07:00 from tcp:127.0.0.1:55420 accepted tcp:edge.microsoft.com:443 [socks >> proxy]
2024/10/04 17:07:00 [Info] [2565234904] proxy/vmess/outbound: tunneling request to tcp:edge.microsoft.com:443 via server-ip:63573
2024/10/04 17:07:00 [Info] [2747995595] proxy/vmess/outbound: tunneling request to tcp:edge.microsoft.com:443 via server-ip:63573
2024/10/04 17:07:01 [Info] [1482102426] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
2024/10/04 17:07:01 [Info] [2747995595] app/proxyman/outbound: app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > read tcp 192.168.0.201:55421->server-ip:63573: wsarecv: An existing connection was forcibly closed by the remote host.
2024/10/04 17:07:01 [Info] [2747995595] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2024/10/04 17:07:01 [Info] [2736837708] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
2024/10/04 17:07:01 [Info] [3954536724] proxy/socks: TCP Connect request to tcp:edge.microsoft.com:443
2024/10/04 17:07:01 [Info] [3954536724] app/dispatcher: sniffed domain: edge.microsoft.com
2024/10/04 17:07:01 [Info] [3954536724] app/dispatcher: default route for tcp:edge.microsoft.com:443
2024/10/04 17:07:01 [Info] [3954536724] transport/internet/tcp: dialing TCP to tcp:server-ip:63573
2024/10/04 17:07:01 [Debug] [3954536724] transport/internet: dialing to tcp:server-ip:63573
2024/10/04 17:07:01 from tcp:127.0.0.1:55422 accepted tcp:edge.microsoft.com:443 [socks >> proxy]
2024/10/04 17:07:01 [Info] [2461086850] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
2024/10/04 17:07:01 [Info] [3954536724] proxy/vmess/outbound: tunneling request to tcp:edge.microsoft.com:443 via server-ip:63573
2024/10/04 17:07:01 [Info] [1362122576] proxy/socks: TCP Connect request to tcp:go.microsoft.com:443
2024/10/04 17:07:01 [Info] [1362122576] app/dispatcher: sniffed domain: go.microsoft.com
2024/10/04 17:07:01 [Info] [1362122576] app/dispatcher: default route for tcp:go.microsoft.com:443
2024/10/04 17:07:01 [Info] [1362122576] transport/internet/tcp: dialing TCP to tcp:server-ip:63573
2024/10/04 17:07:01 [Debug] [1362122576] transport/internet: dialing to tcp:server-ip:63573
2024/10/04 17:07:01 from tcp:127.0.0.1:55424 accepted tcp:go.microsoft.com:443 [socks >> proxy]
2024/10/04 17:07:01 [Info] [2565234904] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
2024/10/04 17:07:02 [Info] [1362122576] proxy/vmess/outbound: tunneling request to tcp:go.microsoft.com:443 via server-ip:63573
2024/10/04 17:07:02 [Info] [3954536724] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
2024/10/04 17:07:04 [Debug] app/log: Logger closing
</code></pre></details>

### Server log

<details><pre><code>
Xray 24.9.30 (Xray, Penetrates Everything.) 3b06af8 (go1.23.1 linux/amd64)
A unified platform for anti-censorship.
2024/10/04 17:10:48 [Info] infra/conf/serial: Reading config: &{Name:config.json Format:json}
2024/10/04 17:10:48 [Debug] app/log: Logger started
2024/10/04 17:10:48 [Info] app/dns: DNS: created UDP client initialized for 1.1.1.1:53
2024/10/04 17:10:48 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:63573
2024/10/04 17:10:48 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:63573
2024/10/04 17:10:48 [Warning] core: Xray 24.9.30 started
2024/10/04 17:11:13 [Info] [1287483751] proxy/vmess/inbound: received request for tcp:edge.microsoft.com:443
2024/10/04 17:11:13 [Info] [1287483751] app/dispatcher: default route for tcp:edge.microsoft.com:443
2024/10/04 17:11:13 [Info] [1287483751] app/dispatcher: default outbound handler not exist
2024/10/04 17:11:13 [Info] [1287483751] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > EOF
2024/10/04 17:11:13 [Info] [2595109033] proxy/vmess/inbound: received request for tcp:go.microsoft.com:443
2024/10/04 17:11:13 [Info] [2595109033] app/dispatcher: default route for tcp:go.microsoft.com:443
2024/10/04 17:11:13 [Info] [2595109033] app/dispatcher: default outbound handler not exist
2024/10/04 17:11:13 [Info] [2595109033] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > EOF
2024/10/04 17:11:14 [Info] [1604279753] proxy/vmess/inbound: received request for tcp:edge.microsoft.com:443
2024/10/04 17:11:14 [Info] [1604279753] app/dispatcher: default route for tcp:edge.microsoft.com:443
2024/10/04 17:11:14 [Info] [1604279753] app/dispatcher: default outbound handler not exist
2024/10/04 17:11:14 [Info] [1604279753] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > EOF
2024/10/04 17:11:14 [Info] [2203448025] proxy/vmess/inbound: received request for tcp:go.microsoft.com:443
2024/10/04 17:11:14 [Info] [2203448025] app/dispatcher: default route for tcp:go.microsoft.com:443
2024/10/04 17:11:14 [Info] [2203448025] app/dispatcher: default outbound handler not exist
2024/10/04 17:11:14 [Info] [2203448025] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > EOF
2024/10/04 17:11:15 [Info] [3995835198] proxy/vmess/inbound: received request for tcp:edge.microsoft.com:443
2024/10/04 17:11:15 [Info] [3995835198] app/dispatcher: default route for tcp:edge.microsoft.com:443
2024/10/04 17:11:15 [Info] [3995835198] app/dispatcher: default outbound handler not exist
2024/10/04 17:11:15 [Info] [3995835198] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > EOF
2024/10/04 17:11:16 [Info] [3286787737] proxy/vmess/inbound: received request for tcp:www.bing.com:443
2024/10/04 17:11:16 [Info] [3286787737] app/dispatcher: default route for tcp:www.bing.com:443
2024/10/04 17:11:16 [Info] [3286787737] app/dispatcher: default outbound handler not exist
2024/10/04 17:11:16 [Info] [3286787737] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > EOF
2024/10/04 17:11:16 [Info] [683095571] proxy/vmess/inbound: received request for tcp:edge.microsoft.com:443
2024/10/04 17:11:16 [Info] [683095571] app/dispatcher: default route for tcp:edge.microsoft.com:443
2024/10/04 17:11:16 [Info] [683095571] app/dispatcher: default outbound handler not exist
2024/10/04 17:11:16 [Info] [683095571] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > EOF
2024/10/04 17:11:16 [Info] [968532423] proxy/vmess/inbound: received request for tcp:edge.microsoft.com:443
2024/10/04 17:11:16 [Info] [968532423] app/dispatcher: default route for tcp:edge.microsoft.com:443
2024/10/04 17:11:16 [Info] [968532423] app/dispatcher: default outbound handler not exist
2024/10/04 17:11:16 [Info] [968532423] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > proxy/vmess/inbound: failed to transfer request > io: read/write on closed pipe
2024/10/04 17:11:16 [Info] [1354497334] proxy/vmess/inbound: received request for tcp:www.bing.com:443
2024/10/04 17:11:16 [Info] [1354497334] app/dispatcher: default route for tcp:www.bing.com:443
2024/10/04 17:11:16 [Info] [1354497334] app/dispatcher: default outbound handler not exist
2024/10/04 17:11:16 [Info] [1354497334] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > EOF
2024/10/04 17:11:16 [Info] [1563568199] proxy/vmess/inbound: received request for tcp:edge.microsoft.com:443
2024/10/04 17:11:16 [Info] [1563568199] app/dispatcher: default route for tcp:edge.microsoft.com:443
2024/10/04 17:11:16 [Info] [1563568199] app/dispatcher: default outbound handler not exist
2024/10/04 17:11:16 [Info] [1563568199] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > EOF
2024/10/04 17:11:16 [Info] [1593330950] proxy/vmess/inbound: received request for tcp:edge.microsoft.com:443
2024/10/04 17:11:16 [Info] [1593330950] app/dispatcher: default route for tcp:edge.microsoft.com:443
2024/10/04 17:11:16 [Info] [1593330950] app/dispatcher: default outbound handler not exist
2024/10/04 17:11:16 [Info] [1593330950] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > EOF
2024/10/04 17:11:16 [Info] [4007707716] proxy/vmess/inbound: received request for tcp:edge.microsoft.com:443
2024/10/04 17:11:16 [Info] [4007707716] app/dispatcher: default route for tcp:edge.microsoft.com:443
2024/10/04 17:11:16 [Info] [4007707716] app/dispatcher: default outbound handler not exist
2024/10/04 17:11:16 [Info] [4007707716] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > EOF
2024/10/04 17:11:16 [Info] [3996171895] proxy/vmess/inbound: received request for tcp:www.bing.com:443
2024/10/04 17:11:16 [Info] [3996171895] app/dispatcher: default route for tcp:www.bing.com:443
2024/10/04 17:11:16 [Info] [3996171895] app/dispatcher: default outbound handler not exist
2024/10/04 17:11:16 [Info] [3996171895] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > EOF
2024/10/04 17:11:16 [Info] [472264731] proxy/vmess/inbound: received request for tcp:edge.microsoft.com:443
2024/10/04 17:11:16 [Info] [472264731] app/dispatcher: default route for tcp:edge.microsoft.com:443
2024/10/04 17:11:16 [Info] [472264731] app/dispatcher: default outbound handler not exist
2024/10/04 17:11:16 [Info] [472264731] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > EOF
2024/10/04 17:11:16 [Info] [459920864] proxy/vmess/inbound: received request for tcp:go.microsoft.com:443
2024/10/04 17:11:16 [Info] [459920864] app/dispatcher: default route for tcp:go.microsoft.com:443
2024/10/04 17:11:16 [Info] [459920864] app/dispatcher: default outbound handler not exist
2024/10/04 17:11:16 [Info] [459920864] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > EOF
2024/10/04 17:11:17 [Info] [546761065] proxy/vmess/inbound: received request for tcp:edge.microsoft.com:443
2024/10/04 17:11:17 [Info] [546761065] app/dispatcher: default route for tcp:edge.microsoft.com:443
2024/10/04 17:11:17 [Info] [546761065] app/dispatcher: default outbound handler not exist
2024/10/04 17:11:17 [Info] [546761065] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > EOF
2024/10/04 17:11:17 [Info] [2224757521] proxy/vmess/inbound: received request for tcp:www.bing.com:443
2024/10/04 17:11:17 [Info] [2224757521] app/dispatcher: default route for tcp:www.bing.com:443
2024/10/04 17:11:17 [Info] [2224757521] app/dispatcher: default outbound handler not exist
2024/10/04 17:11:17 [Info] [2224757521] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > EOF
2024/10/04 17:11:17 [Info] [1187568260] proxy/vmess/inbound: received request for tcp:go.microsoft.com:443
2024/10/04 17:11:17 [Info] [1187568260] app/dispatcher: default route for tcp:go.microsoft.com:443
2024/10/04 17:11:17 [Info] [1187568260] app/dispatcher: default outbound handler not exist
2024/10/04 17:11:17 [Info] [1187568260] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > EOF
</code></pre></details>

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/pull/3769#issuecomment-2334915139
