### ISSUE TITLE
Browser Dialer lost connection after reloading browser websocket page on Xray-core v24.9.30 .

### ISSUE THREAD

**Issue by tkszhzy** [XTLS/Xray-core#3882]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [ ] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

If reopen websoket page ,  Broswer dialer will not work anymore .

and must reboot xray to work.

### Reproduction Method

none

### Client config

<details><pre><code>
none
</code></pre></details>

### Server config

<details><pre><code>
none
</code></pre></details>

### Client log

[Info] [3827992590] app/proxyman/outbound: app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [websocket: close 1001 (going away)] > common/retry: all retry attempts failed

### Server log

<details><pre><code>
none
</code></pre></details>

**Comment by Fangliding** [comment]
configuration

**Comment by RPRX** [comment]
> If reopen websoket page , Broswer dialer will not work anymore .
> 
> and must reboot xray to work.

@Fangliding 你试下能不能复现

**Comment by Fangliding** [comment]
> > If reopen websoket page , Broswer dialer will not work anymore .
> > and must reboot xray to work.
> 
> @Fangliding 你试下能不能复现

我都没用过 要config的原因很大一部分是我复现要用 然而99%的人全部把要求当耳旁风 修就算了还得自己写配置真的有点淦了

**Comment by mmmray** [comment]
https://github.com/XTLS/Xray-core/pull/3832

@PoneyClairDeLune I just saw that `onmessage = ` and `addEventListener("message")` are mixed in the same PR. the intention is to overwrite the previous event handler with a new one, but I think the current code might run both. I'm not sure. Anyway, this PR is the only change to BD in 24.9.30

**Comment by PoneyClairDeLune** [comment]
@mmmray Ouch, gotta see how to prevent multiple handlers from getting run when available.

**Comment by hossinasaadi** [comment]
> @mmmray Ouch, gotta see how to prevent multiple handlers from getting run when available.

may you should prevent like :

`	ws.addEventListener("message", (event) => {},{ once: true })
`

https://github.com/PoneyClairDeLune/Xray-core/blob/3632e83faa70f2bdd08507c54b251ecd22092e6c/transport/internet/browser_dialer/dialer.html#L136-L137

**Comment by mmmray** [comment]
I'm tempted to just revert addEventListener to `ws.onmessage` -- i think it's actually easier to reason about what happens with that kind of syntax

**Comment by mmmray** [comment]
opened a PR for that #3906, but while testing, I found that I cannot reproduce this issue at all (even on main) -- anyway, please test the linked PR, and/or figure out which version introduced the issue

**Comment by RPRX** [comment]
前两天看了下他们改的 browser dialer，Xray 仍会预检浏览器发来的 WS 连接是否可用，理论上没这问题，@mmmray 也没能复现
