### ISSUE TITLE
从1.8.24版本升级到v24.x.x后，无法连接了（tproxy透明代理）

### ISSUE THREAD

**Issue by bluehj777** [XTLS/Xray-core#3883]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

tproxy透明代理连接，在1.8.24上一切正常，未改变服务端和客户端的配置文件。升级到24.9.30后无法连接。(不用透明代理，用V2RAYNG客户端连24.9.30正常)

### 重现方式

客户端和服务端都是DEBIAN x64系统.

### 客户端配置

<details><pre><code>
{
  "log": {
    "access": "/var/log/v2ray_access.log",
    "error": "/var/log/v2ray_error.log",
    "loglevel": "none"
  },
  "inbounds": [
    {
      "protocol": "dokodemo-door",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "listen": "127.0.0.1",
      "port": 60080,
      "settings": {
        "network": "tcp,udp",
        "followRedirect": true
      },
      "streamSettings": {
        "sockopt": {
          "tproxy": "tproxy"
        }
      }
    }
  ],
  "outbound": {
    "protocol": "vless",
    "settings": {
      "vnext": [
        {
          "address": "xray.abc.com",
          "port": 443,
          "users": [
            {
              "id": "xxxx-XXXX-XXXXXXXXXXXXXXXXX",
              "alterId": 0,
              "security": "auto",
              "encryption": "none",
              "flow": "xtls-rprx-vision"
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "tcp",
      "security": "reality",
      "realitySettings": {
        "serverName": "www.xxx.com",
        "fingerprint": "chrome",
        "show": false,
        "publicKey": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "shortId": "",
        "spiderX": ""
      }
    },
    "mux": {
      "enabled": false,
      "concurrency": -1
    }
  }
}
</code></pre></details>

### 服务端配置

<details><pre><code>
{
  "log": {
    "access": "/var/log/v2ray_access.log",
    "error": "/var/log/v2ray_error.log",
    "loglevel": "none"
  },
  "inbounds": [
    {
      "port": 443,
      "protocol": "vless",
      "listen": "0.0.0.0",
      "settings": {
        "udp": true,
        "clients": [
          {
            "id": "xxxx-XXXX-XXXXXXXXXXXXXXXXX",
            "flow": "xtls-rprx-vision"
          }
        ],
        "decryption": "none"
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "show": false,
          "dest": "www.xxx.com:443",
          "xver": 0,
          "serverNames": [
            "www.xxx.com"
          ],
          "privateKey": "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ",
          "publicKey": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
          "maxTimeDiff": 0,
          "shortIds": [
            ""
          ]
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "NFUNLOCK",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "go.netflix.com",
            "port": 1234,
            "users": [
              {
                "id": "XXXXX-XXXXXXXX-XXXXXXXXX",
                "security": "auto"
              }
            ]
          }
        ]
      }
    },
    {
      "tag": "microsoft",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "go.microsoft.com",
            "port": 1234,
            "users": [
              {
                "id": "XXXXX-XXXXXXXX-XXXXXXXXX",
                "security": "auto"
              }
            ]
          }
        ]
      }
    },
    {
      "protocol": "freedom",
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "tag": "block"
    }
  ],
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "domain": [
          "geosite:netflix"
        ],
        "outboundTag": "NFUNLOCK"
      },
      {
        "type": "field",
        "domain": [
          "geosite:microsoft"
        ],
        "outboundTag": "microsoft"
      },
      {
        "type": "field",
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "block"
      }
    ]
  }
}
</code></pre></details>

### 客户端日志

<details><pre><code>
1.8.24日志：
2024/10/05 21:12:26 [Warning] core: Xray 1.8.24 started
2024/10/05 21:12:29 [Debug] [1673661197] proxy/dokodemo: processing connection from: 192.168.100.252:56062
2024/10/05 21:12:29 [Info] [1673661197] proxy/dokodemo: received request for 192.168.100.252:56062
2024/10/05 21:12:29 [Info] [1673661197] app/dispatcher: default route for tcp:8.8.8.8:53
2024/10/05 21:12:29 [Info] [1673661197] transport/internet/tcp: dialing TCP to tcp:xray.abc.com:443
2024/10/05 21:12:29 [Debug] [1673661197] transport/internet: dialing to tcp:xray.abc.com:443
2024/10/05 21:12:29 [Info] [1673661197] proxy/vless/outbound: tunneling request to tcp:8.8.8.8:53 via xray.abc.com:443
2024/10/05 21:12:29 [Info] [1673661197] proxy: XtlsPadding 36 181 0

以上1.8.24一切正常

====================================================
24.9.30日志
2024/10/05 21:15:45 [Warning] core: Xray 24.9.30 started
2024/10/05 21:15:54 [Debug] [1232329444] proxy/dokodemo: processing connection from: 192.168.100.252:33790
2024/10/05 21:15:54 [Info] [1232329444] proxy/dokodemo: received request for 192.168.100.252:33790
2024/10/05 21:15:54 [Info] [1232329444] app/dispatcher: default route for tcp:8.8.8.8:53
2024/10/05 21:15:54 [Info] [1232329444] app/dispatcher: default outbound handler not exist
2024/10/05 21:15:55 [Info] [1232329444] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > context canceled
</code></pre></details>

### 服务端日志

<details><pre><code>
无
</code></pre></details>

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/pull/3769#issuecomment-2334915139
