### ISSUE TITLE
1.4版本升级后ws协议都无法连接了

### ISSUE THREAD

**Issue by magicmatt2020** [XTLS/Xray-core#389]
客户端（v2rayn)和服务端都升级到了1.4版本，客户端path加了?ed=2048，目前所有ws协议的都无法连接了

**Comment by rprx** [comment]
@magicmatt2020 通常是没更新服务端

**Comment by magicmatt2020** [comment]
> @magicmatt2020 通常是没更新服务端

请问服务端在path也需要加?ed=2048么？服务端核心已更新为1.4

**Comment by wf09** [comment]
@magicmatt2020 服务端不需要，客户端添加即可

**Comment by magicmatt2020** [comment]
> @magicmatt2020 服务端不需要，客户端添加即可

之前只是在客户端添加了，但ws协议的都链接不上

**Comment by wf09** [comment]
@magicmatt2020 上日志

**Comment by magicmatt2020** [comment]
客户端日志：

2021/03/17 11:00:30 [Warning] core: Xray 1.4.0 started
2021/03/17 11:00:37 127.0.0.1:57387 accepted //www.google.com:443 [http -> proxy]
2021/03/17 11:00:37 127.0.0.1:57389 accepted //www.google.com:443 [http -> proxy]
2021/03/17 11:00:38 127.0.0.1:57391 accepted //www.google.com:443 [http -> proxy]
2021/03/17 11:00:38 127.0.0.1:57393 accepted //www.google.com:443 [http -> proxy]
2021/03/17 11:00:38 [Warning] [4219851758] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://104.25.189.0/gavlessws): 526 Origin SSL Certificate Error > websocket: bad handshake
2021/03/17 11:00:38 127.0.0.1:57395 accepted //www.google.com:443 [http -> proxy]
2021/03/17 11:00:38 [Warning] [3880749112] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://104.25.189.0/gavlessws): 526 Origin SSL Certificate Error > websocket: bad handshake
2021/03/17 11:00:38 127.0.0.1:57397 accepted //www.google.com:443 [http -> proxy]
2021/03/17 11:00:38 [Warning] [2033363542] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://104.25.189.0/gavlessws): 526 Origin SSL Certificate Error > websocket: bad handshake

**Comment by wf09** [comment]
@magicmatt2020 Origin SSL Certificate Error

**Comment by magicmatt2020** [comment]
> @magicmatt2020 Origin SSL Certificate Error

已查了，把cloudflare上ssl设置从strick改成full就行了，已解决，谢谢！

**Comment by magicmatt2020** [comment]
> @magicmatt2020 Origin SSL Certificate Errror，

已解决，把cloudflare上ssl设置从strict改成full就行了，谢谢
