### ISSUE TITLE
Add domain names support in WireGuard configs

### ISSUE THREAD

**Issue by Anderhar** [XTLS/Xray-core#3892]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

If WireGuard provider uses domain name as an endpoint instead of a regular static IP, xray (as well as sing-box) cannot resolve it which leads to connection failure.

Personally tested with v2rayNG.

Notably, the AmneziaVPN developers also discovered this problem and have already [solved](https://github.com/amnezia-vpn/amnezia-client/commit/46cd740a84a5bdac6922d2b3b5795f4f10d21d64) it in the recent release.

### Reproduction Method

Try connecting to [Widscribe](https://windscribe.com/) VPN provider. In it's WG configs endpoint looks like `lux-123-wg.whiskergalaxy.com:443`, and you'll see that xray doesn't seem to know what to do with it. But if you resolve domain manually and put the resulting IP in coresponding field of the xray config, connection will be established.

### Client config

Not providing my config just because it has to contain my personal credentials of the Windscribe user to be functional (sorry). Though, it is easily reproducible. 

### Server config

<details><pre><code>

</code></pre></details>

### Client log

<details><pre><code>

</code></pre></details>

### Server log

<details><pre><code>

</code></pre></details>

**Comment by Fangliding** [comment]
I have I warp config generate bot and it have no problem with  `"endpoint": "engage.cloudflareclient.com:2408"`
Considering that you have not provided any useful additional information, not following template, I can't fix anything
