### ISSUE TITLE
请问大佬 mac和win 使用splice是不是无解了？以及将来有无xtls+splice+ws的计划？

### ISSUE THREAD

**Issue by fredericky123** [XTLS/Xray-core#39]
RT，多谢，为了保护ip，长期稳定，套个袜子显得格外重要

**Comment by rprx** [comment]
首先，Windows 10 有 WSL

不过还未验证 WSL 1 是否真正能用 Splice、不清楚 WSL 2 会不会带来额外拷贝开销，感兴趣的可以试试

Windows 提供了 TransmitFile，但似乎不能用于两个 TCP 对接

不熟悉 macOS

---

**XTLS 原理上不支持 WS**（真该有新的文档了，过几天弄）

不带 TLS 的 WS 理论上可以支持类似 XTLS 的东西，目前没有实现它的计划

或者 https://github.com/v2ray/discussion/issues/815#issuecomment-680012582

**Comment by fredericky123** [comment]
感谢大佬解答

**Comment by SekiBetu** [comment]
https://docs.microsoft.com/zh-cn/windows/win32/api/mswsock/nf-mswsock-transmitfile?redirectedfrom=MSDN
WIN10的零拷贝技术能不能用仍然是个迷，感觉网上都没人提起过
其实不需要零拷贝，入门级的intel i5-10400f 也6核12线程了，远远可以容纳xray.exe的大流量运行，splice的意义重点在于路由器等linux设备的低功耗运行
