### ISSUE TITLE
Added DDNS Support

### ISSUE THREAD

**Issue by getjake** [XTLS/Xray-core#3902]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

When the server is a dynamic dns (known as ddns) domain. As the domain's A or AAAA records updates to a new one, the xray-client will lose the connection to the server, and will NOT re-establish connection to the new IP.

### Reproduction Method

1. Register a sub-domain on cloudflare.com, set the TTL to 1 minutes. 
2. Point the domain to a your home-server (likely a dynamic IP address).
3. Restart your router / modem of your home-server, in which case you will get a new IP.
4. Update the sub-domain's IP to the new one. You will find xray client will not connect.

### Client config

Not necessary.

### Server config

Not necessary.

### Client log

Not necessary.

### Server log

Not necessary.

**Comment by Fangliding** [comment]
It is obvious that Xray's DNS cache will not refresh immediately and will require waiting for several minutes
