### ISSUE TITLE
Panic on splithttp

### ISSUE THREAD

**Issue by outofdate-debug** [XTLS/Xray-core#3909]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [ ] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

I get  panic error

### 重现方式

it happens when you use splithttp (h3) transport.

### 客户端配置

<details><pre><code>
{
      "settings": {
        "vnext": [
          {
            "port": 443,
            "users": [
              {
                "encryption": "none",
                "id": "",
                "level": 0
              }
            ],
            "address": ""
          }
        ]
      },
      "streamSettings": {
        "network": "splithttp",
        "tlsSettings": {
          "fingerprint": "chrome",
          "serverName": "",
          "allowInsecure": true,
          "alpn": [
            "h3"
          ]
        },
        "splithttpSettings": {
          "host": "",
          "path": "/",
          "xmux": {
            "scMaxEachPostBytes": "5000000-8000000",
            "scMaxConcurrentPosts": "100-200",
            "scMinPostsIntervalMs": "10-50",
            "noSSEHeader": false,
            "xPaddingBytes": "100-1000",
            "maxConnections": 1,
            "cMaxReuseTimes": 0,
            "cMaxLifetimeMs": 0
          }
        },
        "sockopt": {
          "mark": 255
        },
        "security": "tls"
      },
      "mux": {
        "enabled": false
      },
      "protocol": "vless",
      "tag": ""
    },
</code></pre></details>

### 服务端配置

<details><pre><code>

</code></pre></details>

### 客户端日志

<details><pre><code>
panic: connection already exists

goroutine 13575 [running]:
github.com/quic-go/quic-go.(*connMultiplexer).AddConn(0x230fd88, {0xb6c44a30, 0x3b99228})
	github.com/quic-go/quic-go@v0.46.0/multiplexer.go:59 +0x150
github.com/quic-go/quic-go.(*Transport).dial.(*Transport).init.func2()
	github.com/quic-go/quic-go@v0.46.0/transport.go:266 +0x45c
sync.(*Once).doSlow(0x40b3dac, 0x3ed3ec0)
	sync/once.go:76 +0xa8
sync.(*Once).Do(0x40b3dac, 0x3ed3ec0)
	sync/once.go:67 +0x40
github.com/quic-go/quic-go.(*Transport).init(...)
	github.com/quic-go/quic-go@v0.46.0/transport.go:225
github.com/quic-go/quic-go.(*Transport).dial(0x40b3d68, {0x107ceac, 0x2bef290}, {0x1077fc8, 0x223f218}, {0x0, 0x0}, 0x3b10408, 0x33da1c0, 0x1)
	github.com/quic-go/quic-go@v0.46.0/transport.go:212 +0x68
github.com/quic-go/quic-go.(*Transport).DialEarly(...)
	github.com/quic-go/quic-go@v0.46.0/transport.go:204
github.com/quic-go/quic-go.DialEarly({0x107ceac, 0x2bef290}, {0x107eea0, 0x3b99228}, {0x1077fc8, 0x223f218}, 0x3b10408, 0x33da1c0)
	github.com/quic-go/quic-go@v0.46.0/client.go:95 +0x108
github.com/xtls/xray-core/transport/internet/splithttp.createHTTPClient.func2({0x107ceac, 0x2bef290}, {0x3615ac0, 0xc}, 0x3b10408, 0x33da1c0)
	github.com/xtls/xray-core/transport/internet/splithttp/dialer.go:167 +0x320
github.com/quic-go/quic-go/http3.(*RoundTripper).dial(0x22c4e60, {0x107ceac, 0x2bef290}, {0x3615ac0, 0xc})
	github.com/quic-go/quic-go@v0.46.0/http3/roundtrip.go:312 +0x254
github.com/quic-go/quic-go/http3.(*RoundTripper).getClient.func1()
	github.com/quic-go/quic-go@v0.46.0/http3/roundtrip.go:249 +0x88
created by github.com/quic-go/quic-go/http3.(*RoundTripper).getClient in goroutine 12418
	github.com/quic-go/quic-go@v0.46.0/http3/roundtrip.go:246 +0x22c

</code></pre></details>

### 服务端日志

<details><pre><code>

</code></pre></details>

**Comment by outofdate-debug** [comment]
yes, I'm using latest version.

**Comment by Fangliding** [comment]
full log

**Comment by outofdate-debug** [comment]
that is all I get in stdout.

**Comment by Fangliding** [comment]
There may also be stderr, and log set to debug level should include more information like startup information (by the way, the config you provided is also incomplete)

**Comment by outofdate-debug** [comment]
you are right. it should be stderr.
I try to reproduce again with debug level.  and give full config.

**Comment by Fangliding** [comment]
close as no response
