### ISSUE TITLE
v24.9.30的socks5无法连接warp开启的socks5代理

### ISSUE THREAD

**Issue by phoenixxie0** [XTLS/Xray-core#3913]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

v24.9.30的socks5无法连接warp开启的socks5代理。通过curl测试，warp开启的socks5代理工作正常，但是xray无法连接。奇怪的是，socks5代理测试了是正常的。xray的配置也没有修改过。

### 重现方式

路由设置出口位socks对应的出口，网络不通

### 客户端配置

<details><pre><code>
N/A
</code></pre></details>

### 服务端配置

<details><pre><code>
   "outbounds": [
        {
            "protocol": "freedom", 
            "settings": {
                "domainStrategy": "UseIPv6v4"
            }, 
            "tag": "direct"
        }, 
        {
            "protocol": "freedom", 
            "settings": {
                "domainStrategy": "UseIPv6"
            }, 
            "tag": "ipv6"
        }, 
        {
            "protocol": "socks", 
            "settings": {
                "servers": [
                    {
                        "address": "127.0.0.1",
                        "port": 40000
                    }
                ]
            }, 
            "tag": "warp-socks5"
        }, 
        {
            "protocol": "blackhole", 
            "settings": { }, 
            "tag": "blocked"
        }
    ], 
    "routing": {
        "domainStrategy": "IPIfNonMatch", 
        "domainMatcher": "hybrid", 
        "rules": [
            {
                "type": "field", 
                "domain": [
                    "geosite:category-ads"
                ], 
                "outboundTag": "blocked"
            }, 
            {
                "type": "field",
                "ip": [
                    "8.8.8.8",
                    "8.8.4.4",
                    "1.1.1.1",
                    "1.0.0.1"
                ],
                "networks": "tcp,udp",
                "portList": [53,443,853],
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "domain": [
                    "dns.google",
                    "dns.adguard.com",
                    "dns.rubyfish.cn"
                ], 
                "networks": "tcp,udp",
                "portList": [53,443,853],
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "domain": [
                    "geosite:youtube"
                ], 
                "networks": "tcp,udp",
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "ip": [
                    //"geoip:cloudflare",
                    "geoip:netflix",
                    "geoip:cn"
                ],
                "outboundTag": "warp-socks5"
            },
            {
                "type": "field", 
                "domain": [
                    "geosite:cloudflare",
                    "geosite:cn",
                    "geosite:netflix", 
                    "geosite:google-cn",
                    "geosite:google",
                    "geosite:facebook",
                    //"geosite:instagram",
                    "geosite:twitter",
                    "geosite:category-porn",
                    "geosite:tiktok",
                    "geosite:openai"
                ], 
                "outboundTag": "warp-socks5"
            }
        ]
    },
	"observatory": {
        "probeInterval": "36s",
        "subjectSelector": [
            "warp-wireguard",
		    "warp-socks5"
        ],
        "probeURL": "https://www.google.com/generate_204",
        "probeInterval": "1m"
    }
} 
</code></pre></details>

### 客户端日志

<details><pre><code>
N/A
</code></pre></details>

### 服务端日志

<details><pre><code>
2024/10/15 07:08:37 from DNS accepted https://dns.google/dns-query [local]
2024/10/15 07:08:37 from DNS accepted https://1.0.0.1/dns-query [local]
2024/10/15 07:08:38 from 116.253.137.113:13370 accepted tcp:github.com:443 [xtls-port >> direct]
2024/10/15 07:08:39 from 116.253.137.113:13377 accepted tcp:alive.github.com:443 [xtls-port >> direct]
2024/10/15 07:08:42 from 116.253.137.113:13386 accepted tcp:1.0.0.1:853 [xtls-port -> direct]
2024/10/15 07:08:46 from 116.253.137.113:13403 accepted tcp:www.gstatic.com:80 [xtls-port -> warp-socks5]
2024/10/15 07:08:46 from 124.226.36.48:49586 accepted tcp:www.gstatic.com:80 [xtls-port -> warp-socks5]
2024/10/15 07:08:48 from 116.253.137.113:13425 accepted tcp:www.cloudflare.com:443 [xtls-port -> warp-socks5]
2024/10/15 07:08:48 from 116.253.137.113:13435 accepted tcp:1.0.0.1:853 [xtls-port -> direct]
2024/10/15 07:08:49 from 116.253.137.113:13436 accepted tcp:www.cloudflare.com:443 [xtls-port -> warp-socks5]
2024/10/15 07:08:49 from 116.253.137.113:13449 accepted tcp:edge.microsoft.com:443 [xtls-port >> direct]
2024/10/15 07:08:54 from 116.253.137.113:13466 accepted tcp:1.0.0.1:853 [xtls-port -> direct]
2024/10/15 07:08:54 from 116.253.137.113:13468 accepted tcp:www.cloudflare.com:443 [xtls-port -> warp-socks5]
2024/10/15 07:08:55 from 116.253.137.113:13471 accepted tcp:www.cloudflare.com:443 [xtls-port -> warp-socks5]
</code></pre></details>

<details><pre><code>
2024/10/15 07:08:29 [Warning] core: Xray 24.9.30 started
2024/10/15 07:08:29 [Info] app/dispatcher: taking platform initialized detour [warp-socks5] for [tcp:www.google.com:443]
2024/10/15 07:08:29 [Info] transport/internet/tcp: dialing TCP to tcp:127.0.0.1:40000
2024/10/15 07:08:29 [Debug] transport/internet: dialing to tcp:127.0.0.1:40000
2024/10/15 07:08:29 [Info] app/proxyman/outbound: app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > proxy/socks: server rejects request: 1
2024/10/15 07:08:29 [Warning] app/observatory: the outbound warp-socks5 is dead: GET request failed:app/observatory: outbound failed to relay connection > Get "https://www.google.com/generate_204": io: read/write on closed pipewith outbound handler report underlying connection failed > app/observatory: underlying connection error > app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > proxy/socks: server rejects request: 1
2024/10/15 07:08:30 [Info] [579496748] proxy/vless/inbound: firstLen = 379
2024/10/15 07:08:30 [Info] [579496748] proxy/vless/inbound: received request for tcp:91.108.56.172:443
2024/10/15 07:08:30 [Info] [579496748] app/dispatcher: default route for tcp:91.108.56.172:443
2024/10/15 07:08:30 [Info] [579496748] transport/internet/tcp: dialing TCP to tcp:91.108.56.172:443
2024/10/15 07:08:30 [Debug] [579496748] transport/internet: dialing to tcp:91.108.56.172:443
2024/10/15 07:08:30 [Info] [579496748] proxy: Xtls Unpadding new block, content 241 padding 73 command 0
2024/10/15 07:08:30 [Info] [955127124] proxy/vless/inbound: firstLen = 462
2024/10/15 07:08:34 [Info] [1810899743] proxy/vless/inbound: received request for tcp:android.apis.google.com:443
2024/10/15 07:08:34 [Info] [1810899743] app/dispatcher: taking detour [warp-socks5] for [tcp:android.apis.google.com:443]
2024/10/15 07:08:34 [Info] [1810899743] transport/internet/tcp: dialing TCP to tcp:127.0.0.1:40000
2024/10/15 07:08:34 [Debug] [1810899743] transport/internet: dialing to tcp:127.0.0.1:40000
2024/10/15 07:08:34 [Info] [1810899743] proxy: Xtls Unpadding new block, content 543 padding 151 command 0
2024/10/15 07:08:34 [Info] [1810899743] proxy: XtlsFilterTls found tls client hello! 543
2024/10/15 07:08:34 [Info] [1810899743] app/proxyman/outbound: app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > proxy/socks: server rejects request: 1
2024/10/15 07:08:34 [Info] [1810899743] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > io: read/write on closed pipe
2024/10/15 07:08:35 [Info] [788149435] proxy/vless/inbound: firstLen = 1186
2024/10/15 07:08:35 [Info] [788149435] proxy/vless/inbound: received request for tcp:android.apis.google.com:443
2024/10/15 07:08:35 [Info] [788149435] app/dispatcher: taking detour [warp-socks5] for [tcp:android.apis.google.com:443]
2024/10/15 07:08:35 [Info] [788149435] transport/internet/tcp: dialing TCP to tcp:127.0.0.1:40000
2024/10/15 07:08:35 [Debug] [788149435] transport/internet: dialing to tcp:127.0.0.1:40000
2024/10/15 07:08:35 [Info] [788149435] proxy: Xtls Unpadding new block, content 575 padding 529 command 0
2024/10/15 07:08:35 [Info] [788149435] proxy: XtlsFilterTls found tls client hello! 575
2024/10/15 07:08:35 [Info] [788149435] app/proxyman/outbound: app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > proxy/socks: server rejects request: 1
2024/10/15 07:08:35 [Info] [788149435] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > io: read/write on closed pipe
</code></pre></details>

**Comment by RPRX** [comment]
看了下代码 Socks5 客户端的部分似乎动，换成 v1.8.24 试试

**Comment by phoenixxie0** [comment]
> ![image](https://private-user-images.githubusercontent.com/45535409/376658876-a2285fcd-940f-43d4-aa3b-65aa6b9110ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMDUwNDYsIm5iZiI6MTcyOTAwNDc0NiwicGF0aCI6Ii80NTUzNTQwOS8zNzY2NTg4NzYtYTIyODVmY2QtOTQwZi00M2Q0LWFhM2ItNjVhYTZiOTExMGVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE1MDU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwNjYwM2U2NWFlNjk5NTBlYzk5NTE5YmQ3OWRhODIzMGE4NWQzZGZmYzI2MDY3MDk4OGZkMDE4MjJhMzEyYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1cyPqFrNBxtg9ztheDLLSoHhgoOT_QH4Z4UrCiJTvrE) 还费事去装了个 warp cli 无法复现

warp的版本是多少，我用的2024.9.346.0，然后使用curl测试
curl -sx socks5h://127.0.0.1:40000  https://www.cloudflare.com/cdn-cgi/trace 不行，
curl -sx socks5://127.0.0.1:40000  https://www.cloudflare.com/cdn-cgi/trace 正常。
似乎是远程解析不能了的问题？

**Comment by Fangliding** [comment]
> > ![image](https://private-user-images.githubusercontent.com/45535409/376658876-a2285fcd-940f-43d4-aa3b-65aa6b9110ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMDUwNDYsIm5iZiI6MTcyOTAwNDc0NiwicGF0aCI6Ii80NTUzNTQwOS8zNzY2NTg4NzYtYTIyODVmY2QtOTQwZi00M2Q0LWFhM2ItNjVhYTZiOTExMGVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE1MDU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwNjYwM2U2NWFlNjk5NTBlYzk5NTE5YmQ3OWRhODIzMGE4NWQzZGZmYzI2MDY3MDk4OGZkMDE4MjJhMzEyYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1cyPqFrNBxtg9ztheDLLSoHhgoOT_QH4Z4UrCiJTvrE) 还费事去装了个 warp cli 无法复现
> 
> warp的版本是多少，我用的2024.9.346.0，然后使用curl测试 curl -sx socks5h://127.0.0.1:40000 https://www.cloudflare.com/cdn-cgi/trace 不行， curl -sx socks5://127.0.0.1:40000 https://www.cloudflare.com/cdn-cgi/trace 正常。 似乎是远程解析不能了的问题？

稍微搜了一下 是不支持 https://community.cloudflare.com/t/warp-socks5-proxy-mode-should-support-udp/502374 不是xray的问题

**Comment by phoenixxie0** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/45535409/376658876-a2285fcd-940f-43d4-aa3b-65aa6b9110ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMDUwNDYsIm5iZiI6MTcyOTAwNDc0NiwicGF0aCI6Ii80NTUzNTQwOS8zNzY2NTg4NzYtYTIyODVmY2QtOTQwZi00M2Q0LWFhM2ItNjVhYTZiOTExMGVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE1MDU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwNjYwM2U2NWFlNjk5NTBlYzk5NTE5YmQ3OWRhODIzMGE4NWQzZGZmYzI2MDY3MDk4OGZkMDE4MjJhMzEyYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1cyPqFrNBxtg9ztheDLLSoHhgoOT_QH4Z4UrCiJTvrE) 还费事去装了个 warp cli 无法复现
> > 
> > 
> > warp的版本是多少，我用的2024.9.346.0，然后使用curl测试 curl -sx socks5h://127.0.0.1:40000 https://www.cloudflare.com/cdn-cgi/trace 不行， curl -sx socks5://127.0.0.1:40000 https://www.cloudflare.com/cdn-cgi/trace 正常。 似乎是远程解析不能了的问题？
> 
> 稍微搜了一下 是不支持 https://community.cloudflare.com/t/warp-socks5-proxy-mode-should-support-udp/502374 不是xray的问题

xray的socks出口需要远程解析？

**Comment by Fangliding** [comment]
> > > > ![image](https://private-user-images.githubusercontent.com/45535409/376658876-a2285fcd-940f-43d4-aa3b-65aa6b9110ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMDUwNDYsIm5iZiI6MTcyOTAwNDc0NiwicGF0aCI6Ii80NTUzNTQwOS8zNzY2NTg4NzYtYTIyODVmY2QtOTQwZi00M2Q0LWFhM2ItNjVhYTZiOTExMGVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE1MDU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwNjYwM2U2NWFlNjk5NTBlYzk5NTE5YmQ3OWRhODIzMGE4NWQzZGZmYzI2MDY3MDk4OGZkMDE4MjJhMzEyYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1cyPqFrNBxtg9ztheDLLSoHhgoOT_QH4Z4UrCiJTvrE) 还费事去装了个 warp cli 无法复现
> > > 
> > > 
> > > warp的版本是多少，我用的2024.9.346.0，然后使用curl测试 curl -sx socks5h://127.0.0.1:40000 https://www.cloudflare.com/cdn-cgi/trace 不行， curl -sx socks5://127.0.0.1:40000 https://www.cloudflare.com/cdn-cgi/trace 正常。 似乎是远程解析不能了的问题？
> > 
> > 
> > 稍微搜了一下 是不支持 https://community.cloudflare.com/t/warp-socks5-proxy-mode-should-support-udp/502374 不是xray的问题
> 
> xray的socks出口需要远程解析？ 另外我看了发现2024.9.346.0版本的socks5代理方式确实存在问题

得看具体配置 总之就是得把dns请求用doh一类的玩意发出去

我们只处理xray本身的问题(如果有)

**Comment by malagebidi** [comment]
同样的问题，我先把warp回滚了试试

**Comment by istarkov** [comment]
I did downgrade to `cloudflare-warp-2024.6.497`, no luck. (Started to connect but sites are not working)


Anyone have working config?
Mine is broken even with downgraded warp. (below user blabla@gmail.com can't open any site)

<details>
<summary>CONFIG</summary>

```json
{
  "log": {
    "loglevel": "warning"
  },
  "outbounds": [
    {
      "protocol": "freedom",
      "tag": "freedom"
    },
    {
      "protocol": "blackhole",
      "tag": "Reject",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    },
    {
      "tag": "warp",
      "protocol": "socks",
      "settings": {
        "servers": [
          {
            "address": "127.0.0.1",
            "port": 4000
          }
        ]
      }
    }
  ],
  "routing": {
    "rules": [
      {
        "type": "field",
        "outboundTag": "Reject",
        "inboundTag": ["vless-reality"],
        "domain": ["geosite:category-ads-all"]
      },
      {
        "type": "field",
        "outboundTag": "warp",
        "inboundTag": ["vless-reality"],
        "user": ["blabla@gmail.com"]
      }
    ]
  },
  "dns": {
    "servers": [
      "1.1.1.1",
      "8.8.4.4",
      "8.8.8.8",
      "https+local://1.1.1.1/dns-query",
      "https+local://8.8.8.8/dns-query"
    ]
  },
  "inbounds": [
    {
      "tag": "vless-reality",
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "some-id",
            "flow": "xtls-rprx-vision",
            "userLevel": 0,
            "email": "blabla@gmail.com"
          },
          {
            "id": "some-id-2",
            "flow": "xtls-rprx-vision",
            "userLevel": 0,
            "email": "blabla2@gmail.com"
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "dest": "speed.cloudflare.com:443",
          "serverNames": ["speed.cloudflare.com"],
          "privateKey": "private-key",
          "shortIds": ["", "ff"],
          "show": true
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls", "quic"],
        "routeOnly": true
      }
    }
  ]
}
```
</details>
