### ISSUE TITLE
chatgpt.com真人验证： vless-SpliteHTTP验证过不了一直重复验证，但vless-reality-tcp可以通过验证，

### ISSUE THREAD

**Issue by tqangxl** [XTLS/Xray-core#3918]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

chatgpt.com真人验证： vless-SpliteHTTP验证过不了一直重复验证，但vless-reality-tcp可以通过验证，

### 重现方式

面板用的3x-ui 的[v2.4.3](https://github.com/MHSanaei/3x-ui/releases) 
![image](https://github.com/user-attachments/assets/e30a5042-26ff-4f43-9566-a8e2abc9be1c)

![image](https://github.com/user-attachments/assets/efc735b2-da47-4c78-bc30-abfca9fe700c)
vless-SpliteHTTPclient：
![image](https://github.com/user-attachments/assets/26962522-2eb3-4a30-8a1e-67814899880d)

### 客户端配置

<details><pre><code>
vless-SpliteHTTPclient：
![image](https://github.com/user-attachments/assets/26962522-2eb3-4a30-8a1e-67814899880d)
![image](https://github.com/user-attachments/assets/efc735b2-da47-4c78-bc30-abfca9fe700c)
</code></pre></details>

### 服务端配置

<details><pre><code>

![image](https://github.com/user-attachments/assets/d59c8116-14fc-4b6c-9140-dadbca90a199)

![image](https://github.com/user-attachments/assets/24c18742-da92-413c-a5a7-63cdec15a827)

</code></pre></details>

### 客户端日志

<details><pre><code>
怎么看
</code></pre></details>

### 服务端日志

<details><pre><code>
怎么看
</code></pre></details>

**Comment by Fangliding** [comment]
请按模板填写 不处理只给几张面板截图的问题
