### ISSUE TITLE
6.6版本，每运行一段时间（半小时左右）控制台就会报错，网络就无法访问，重启服务后正常；

### ISSUE THREAD

**Issue by wangduokai** [XTLS/Xray-core#3922]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

zz_v2rayN-With-Core-SelfContained 6.6版本

### 重现方式

运行一段时间就会出现，https://github.com/2dust/v2rayN/issues/5685 建议fingerprint 在windows下，有时候会有问题，不要用random，但我改成chrome后依然存在此问题；

### 客户端配置

<details><pre><code>
![image](https://github.com/user-attachments/assets/d6ec6193-0e20-41c1-a6a7-c30e16db635e)

</code></pre></details>

### 服务端配置

<details><pre><code>

</code></pre></details>

### 客户端日志

<details><pre><code>
[log.txt](https://github.com/user-attachments/files/17408503/log.txt)

</code></pre></details>

### 服务端日志

<details><pre><code>

</code></pre></details>

**Comment by Fangliding** [comment]
dup 都说了日志不全 多发一遍不会有任何改变

**Comment by wangduokai** [comment]
我ctrl+a copy的控制台所有日志信息，如果不全的话，我怎么才能发出全的来呢？

**Comment by Fangliding** [comment]
> 我ctrl+a copy的控制台所有日志信息，如果不全的话，我怎么才能发出全的来呢？

嗯，，写个配置自己跑吧 一没法复现二没日志真没办法
