### ISSUE TITLE
Question regarding Xray Shadowsocks.

### ISSUE THREAD

**Issue by lostsoul6** [XTLS/Xray-core#3923]
Hello @RPRX ,

I recently noticed that the shadowsocks offered in outline manager is not detected by my ISP but the shadowsocks offered in xray-core gets detected after a while . 

I contacted outline members to see what the difference is and they told me they use connection prefixes : https://www.reddit.com/r/outlinevpn/wiki/index/prefixing/

Is there anyway this could be implemented in xray-core?

Regards,

**Comment by Fangliding** [comment]
It does not in shadowsocks standard, it is an outline feature
If you want to disguise traffic as another protocol, you can use xray's transport protocol
