### ISSUE TITLE
Multi-port blocking is invalid

### ISSUE THREAD

**Issue by starry1314** [XTLS/Xray-core#3926]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

I want to block connections to matching ports, the following settings tested and failed to block

### 重现方式

Start the following configuration. The client uses V2rayng.apk and connects to a certain game. The port is 7500. The test cannot be blocked.

### 客户端配置

N/A

### 服务端配置

<details><pre><code>
{
    "inbounds": [
        {
            "port": 10001,
            "protocol": "shadowsocks",
            "settings": {
                "method": "chacha20-ietf-poly1305",
                "password": "q9oXgT",
                "network": "tcp,udp"
            },
            "streamSettings": {
                "sockopt": {
                    "mark": 255,
                    "interface": "10.50.1.184"
                }
            },
            "tag": "inbound-10001"
        }
    ],
    "outbounds": [
        {
            "tag": "inbound-10001",
            "protocol": "freedom",
            "sendThrough": "10.50.1.184",
            "settings": {}
        },
        {
            "protocol": "blackhole",
            "settings": {},
            "tag": "blocked"
        }
    ],
    "routing": {
        "rules": [
            {
                "type": "field",
                "inboundTag": [
                    "inbound-10001"
                ],
                "outboundTag": "inbound-10001"
            },
            {
                "type": "field",
                "port": "7500,8012,14001,15030,15498,2013,12001",
                "outboundTag": "blocked"
            },
            {
                "type": "field",
                "ip": [
                    "geoip:private"
                ],
                "outboundTag": "blocked"
            },
            {
                "type": "field",
                "protocol": [
                    "bittorrent"
                ],
                "outboundTag": "blocked"
            }
        ]
    }
}
</code></pre></details>

### 客户端日志

N/A

### 服务端日志

N/A

**Comment by Fangliding** [comment]
路由会匹配到第一个符合条件的条目 你的第一个路由匹配inboundtag已经匹配到了就不会往下匹配了 要生效的话把下面的挪到上面去

**Comment by starry1314** [comment]
> 路由会匹配到第一个符合条件的条目 你的第一个路由匹配inboundtag已经匹配到了就不会往下匹配了 要生效的话把下面的挪到上面去

你好~已調整如下不過還是阻斷失敗
路由跟OUT都往上移了

`{
    "routing": {
        "rules": [
            {
                "type": "field",
                "inboundTag": [
                    "inbound-10001"
                ],
                "outboundTag": "inbound-10001"
            },
            {
                "type": "field",
                "port": "17700,8201,15030,13700,14002,8012,7500,7700,15498,14001,12000,12070,10100,33004,12001,17701,6112,2013,6040",
                "outboundTag": "blocked"
            },
            {
                "type": "field",
                "ip": [
                    "geoip:private"
                ],
                "outboundTag": "blocked"
            },
            {
                "type": "field",
                "protocol": [
                    "bittorrent"
                ],
                "outboundTag": "blocked"
            }
        ]
    },
    "outbounds": [
        {
            "tag": "inbound-10001",
            "protocol": "freedom",
            "sendThrough": "10.50.1.184",
            "settings": {}
        },
        {
            "protocol": "blackhole",
            "settings": {},
            "tag": "blocked"
        }
    ],
    "inbounds": [
        {
            "port": 10001,
            "protocol": "shadowsocks",
            "settings": {
                "method": "chacha20-ietf-poly1305",
                "password": "q9oXgT",
                "network": "tcp,udp"
            },
            "streamSettings": {
                "sockopt": {
                    "mark": 255,
                    "interface": "10.50.1.184"
                }
            },
            "tag": "inbound-10001"
        }
    ]
}`

**Comment by Fangliding** [comment]
这不还是在第二条。。 
![image](https://github.com/user-attachments/assets/59699d53-a4f1-4bd8-b4dc-1d263865a57d)

**Comment by starry1314** [comment]
了解了!謝謝
> 这不还是在第二条。。 ![image](https://private-user-images.githubusercontent.com/45535409/377738921-59699d53-a4f1-4bd8-b4dc-1d263865a57d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMzA5MzAsIm5iZiI6MTcyOTIzMDYzMCwicGF0aCI6Ii80NTUzNTQwOS8zNzc3Mzg5MjEtNTk2OTlkNTMtYTRmMS00YmQ4LWI0ZGMtMWQyNjM4NjVhNTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDA1NTAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmY2E3YWVlOTMxNjQ5Mzg5OTU1YTg5Nzc2ODA5YjRiZDQ1NDI2NTc3ZmI2NjBlNDhmNWRhOWYyZDcyNDBhNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1CsXFX74S6zdjAl_PML-EDXrp2hbqK211oFXzZFLbjo)
