### ISSUE TITLE
OPENWRT 升級了1.4，不能科學上網了，所有節點都超時怎麼回事呢？

### ISSUE THREAD

**Issue by slayercjc** [XTLS/Xray-core#393]
OPENWRT 升級了1.4，不能科學上網了，所有節點都超時怎麼回事呢？

**Comment by rprx** [comment]
日志

**Comment by woniuzfb** [comment]
2021/03/16 21:11:11 [Debug] transport/internet/udp: UDP original destination: udp:10.0.0.129:53
2021/03/16 21:11:11 [Debug] [3734972717] proxy/dokodemo: processing connection from: 10.0.0.173:53005
2021/03/16 21:11:11 [Info] [3734972717] proxy/dokodemo: received request for 10.0.0.173:53005
2021/03/16 21:11:11 [Info] [3734972717] app/dispatcher: taking detour [dns_out] for [udp:10.0.0.129:53]
2021/03/16 21:11:11 [Info] [3734972717] proxy/dns: handling DNS traffic to udp:10.0.0.129:53
2021/03/16 21:11:11 [Info] app/dns: failed to lookup ip for domain www.googleapis.com at server localhost > empty response

DNS 填 localhost 的全部挂了

**Comment by JimhHan** [comment]
感谢您的反馈，与 https://github.com/XTLS/Xray-core/issues/383 重复。
稍后修复。
