### ISSUE TITLE
Unblock mux limit?

### ISSUE THREAD

**Issue by Fangliding** [XTLS/Xray-core#3931]
mux的复用有三层限制

协议限制 mux.cool 的流id长2个字节 也就是说它支持65535个流
conf解析里 其类型为int16 长度上限为32767
代码里硬编码的神秘 MaxConnection 参数为128

也就是说mux的实际上限为128 而非文档里的1024(已经实验验证)
文档我改掉了 不知道有没有必要取消掉128的限制 改成1024(和旧文档类似) 还是顶满到32767或者65535 我不知道复用如此巨量的流会不会造成问题

btw, mux.cool里的concurrency实际行为和splithttp的MaxReuseTimes其实是一样的 子连接ID只会一直递增 关掉的流并不会为这个连接腾出地方 递增到concurrency的值就认为这条连接已经满了 然后会去新开连接

**Comment by yuhan6665** [comment]
yeah I think we can tidy it up when working on new mux options
