### ISSUE TITLE
啟動多組配置文件與端口服務~啟動失敗 提示端口佔用(查詢沒有)

### ISSUE THREAD

**Issue by starry1314** [XTLS/Xray-core#3939]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

1.透過API啟動數百個連續端口的服務,部分端口發現啟動失敗後查詢
顯示該端口已占用,但實際查詢提示的佔用端口卻沒有服務佔用

### 重现方式

使用站群啟動有多個配置文件如20組.每個配置文件會啟動有10個SK5服務端口
發現連接不上後查詢為該情況

### 客户端配置

N/A.

### 服务端配置

<details><pre><code>
{
    "inbounds": [
        {
            "port": 29015,
            "protocol": "socks",
            "settings": {
                "auth": "password",
                "accounts": [
                    {
                        "user": "aaa",
                        "pass": "aaa"
                    }
                ],
                "udp": true
            },
            "streamSettings": {
                "sockopt": {
                    "mark": 255,
                    "interface": "10.50.1.10"
                }
            },
            "tag": "inbound-29015"
        }
    ],
    "outbounds": [
        {
            "tag": "inbound-29015",
            "protocol": "freedom",
            "sendThrough": "10.50.1.10",
            "settings": {}
        },
        {
            "protocol": "blackhole",
            "settings": {},
            "tag": "blocked"
        }
    ],
    "routing": {
        "rules": [
            {
                "type": "field",
                "port": "7700,3343,17700,8201,15498,13700,15030,8012,10100,33004,12001,14000,9001,14002,6040,14001,12000,7500,9933,17701,12070,2013,6112",
                "outboundTag": "blocked"
            },
            {
                "type": "field",
                "inboundTag": [
                    "inbound-29015"
                ],
                "outboundTag": "inbound-29015"
            },
            {
                "type": "field",
                "ip": [
                    "geoip:private"
                ],
                "outboundTag": "blocked"
            },
            {
                "type": "field",
                "protocol": [
                    "bittorrent"
                ],
                "outboundTag": "blocked"
            }
        ]
    }
}
</code></pre></details>

### 客户端日志

N/A.

### 服务端日志

<details><pre><code>
root@GostV3-xray:~# /usr/local/bin/xray run -c /etc/xray/aaa_batch_0_config.json
Xray 24.9.30 (Xray, Penetrates Everything.) 3b06af8 (go1.23.1 linux/amd64)
A unified platform for anti-censorship.
2024/10/24 12:33:02 [Info] infra/conf/serial: Reading config: &{Name:/etc/xray/aaa_batch_0_config.json Format:json}
Failed to start: app/proxyman/inbound: failed to listen TCP on 29015 > transport/internet: failed to listen on address: 0.0.0.0:29015 > transport/internet/tcp: failed to listen TCP on 0.0.0.0:29015 > listen tcp 0.0.0.0:29015: bind: address already in use
root@GostV3-xray:~# sudo lsof -i :29015
-bash: sudo: command not found
</code></pre></details>

**Comment by Fangliding** [comment]
可以挂上笑话了
```
root@GostV3-xray:~# sudo lsof -i :29015
-bash: sudo: command not found
```
=查询没有发现占用
