### ISSUE TITLE
how to create a pure socks5 and http proxy 

### ISSUE THREAD

**Issue by jyf007** [XTLS/Xray-core#394]
can i remove the sniffing part,my client configure file inbounds part is broken in both socks5 proxy and http proxy
my client json configure file code
```json
{
  "log": {
    "loglevel": "error"
  },
  "inbounds": [{
      "port": 1080,
      "listen": "0.0.0.0",
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": "127.0.0.1"
      }},{
      "port": "8118",
      "listen": "0.0.0.0",
      "protocol": "http"
    }],
  "outbounds": [{
      "protocol": "vless",
      "settings": {
        "vnext": [{
            "address": "0.0.0.0",
            "port": 0,
            "users": [{
                "id": "UUID",
                "flow": "xtls-rprx-direct",
  "encryption": "none",
                "level": 0
              }]
          }]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
            "serverName": "fake"
        },
        "allowInsecure": "true"
      }
  }]   
}
```

**Comment by JimhHan** [comment]
I have confirmed a bug related to sniffer. Could you please try whether  [this commit](https://github.com/XTLS/Xray-core/commits/fix/sniffer-panic) solve your problem ?
You can find a pre-build binary [here](https://github.com/XTLS/Xray-core/actions/runs/660780039).

**Comment by Bearljj** [comment]
> here

这个bug会影响什么呢，透明路由下的sniffer是否相关？

**Comment by jyf007** [comment]
well,the patch still doesn't work for the configure json 
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to google.com:443

**Comment by Bearljj** [comment]
This's my config,it works well;your error does not seem to be related to inbound settings.
"inbounds": [
    {
            "tag": "socks-in",
            "protocol": "socks",
            "listen": "127.0.0.1",   
            "port": 10800,         
            "settings": {
                "udp": true
            }
    }
  ]

> well,the patch still doesn't work for the configure json
> curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to google.com:443

**Comment by jyf007** [comment]
`
{
  "dns": {
    "hosts": {
      "domain:googleapis.cn": "googleapis.com"
    },
    "servers": [
      "1.1.1.1",
      {
        "address": "223.5.5.5",
        "domains": [
          "geosite:cn"
        ],
        "expectIPs": [
          "geoip:cn"
        ],
        "port": 53
      }
    ]
  },
  "inbounds": [
    {
      "port": 10808,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true
      },
      "tag": "socks"
    },
    {
      "port": 10809,
      "protocol": "http",
      "settings": {
        "userLevel": 8
      },
      "tag": "http"
    },
    {
      "listen": "127.0.0.1",
      "port": 10853,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "1.1.1.1",
        "network": "tcp,udp",
        "port": 53
      },
      "tag": "dns-in"
    }
  ],
  "log": {
    "loglevel": "warning"
  },
  "outbounds": [
    {
      "mux": {
        "concurrency": -1,
        "enabled": false
      },
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "0.0.0.0",
            "port": 0,
            "users": [
              {
                "alterId": 0,
                "encryption": "none",
                "flow": "xtls-rprx-direct",
                "id": "UUID",
                "level": 8,
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
          "allowInsecure": true,
          "serverName": ""
        }
      },
      "tag": "proxy"
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    },
    {
      "protocol": "dns",
      "tag": "dns-out"
    }
  ],
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "inboundTag": [
          "dns-in"
        ],
        "outboundTag": "dns-out",
        "type": "field"
      },
      {
        "ip": [
          "1.1.1.1"
        ],
        "outboundTag": "proxy",
        "port": "53",
        "type": "field"
      },
      {
        "ip": [
          "223.5.5.5"
        ],
        "outboundTag": "direct",
        "port": "53",
        "type": "field"
      },
      {
        "domain": [
          "domain:googleapis.cn"
        ],
        "outboundTag": "proxy",
        "type": "field"
      },
      {
        "domain": [
          ""
        ],
        "outboundTag": "direct",
        "type": "field"
      },
      {
        "ip": [
        ],
        "outboundTag": "direct",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "direct",
        "type": "field"
      },
      {
        "ip": [
          "geoip:cn"
        ],
        "outboundTag": "direct",
        "type": "field"
      },
      {
        "domain": [
          "geosite:cn"
        ],
        "outboundTag": "direct",
        "type": "field"
      }
    ]
  }
}

`

**Comment by jyf007** [comment]
> This's my config,it works well;your error does not seem to be related to inbound settings.
> "inbounds": [
> {
> "tag": "socks-in",
> "protocol": "socks",
> "listen": "127.0.0.1",
> "port": 10800,
> "settings": {
> "udp": true
> }
> }
> ]
> 
> > well,the patch still doesn't work for the configure json
> > curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to google.com:443

i mean other part is block the socks5 proxy steam

**Comment by Bearljj** [comment]
"hosts": {
      "domain:googleapis.cn": "googleapis.com"
    },
What does this mean？Delete it and try again

**Comment by jyf007** [comment]
@Bearljj Well,i can't delete from v2rayNG,because it is automatic generate this part.

**Comment by Bearljj** [comment]
> @Bearljj Well,i can't delete from v2rayNG,because it is automaticly generating this part,i only know v2rayNG is working

You'd better check your DNS configuration first

**Comment by jyf007** [comment]
which part,the /etc/resolv.conf or the xray configure file tunnel one dns and rewritte the first file

**Comment by jyf007** [comment]
@jyf007 And my shadowsocks-libev works well,why should i reflush /etc/resolv.conf

**Comment by jyf007** [comment]
@jyf007 Then if xray needs to write a large route table,it shows a vpn service than proxy service,i have to figure out which part block the pure proxy steam between the inbound and outbound,otherwise i have to switch to trojan which is simple than vpn server

**Comment by jyf007** [comment]
I am wrong,i figure out that "allowInsecure": true is the key to solve it
