### ISSUE TITLE
failed to fallback request payload 

### ISSUE THREAD

**Issue by doughnutscranberry** [XTLS/Xray-core#3940]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

Unable to successfully connect to the server, the domain name can be pinged. I referred to

https://github.com/XTLS/Xray-examples/blob/main/VLESS-TCP-TLS-WS%20(recommended)/config_server.jsonc

### Reproduction Method

Start the server and then connect to the client, both the client and the server are the same latest version of xray

### Client config

![image](https://github.com/user-attachments/assets/a82ccdc1-88b2-427a-9b2b-dab1ee83d144)

### Server config

<details><pre><code>
{
    "log": {
        "loglevel": "debug"
    },
    "inbounds": [
        {
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "96849933-bbdb-4376-b008-68f17c04aff4", // 填写你的 UUID
                        "level": 0,
                        "email": "love@v2fly.org"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": 80
                    },
                    {
                        "path": "/123456", // 必须换成自定义的 PATH
                        "dest": 1234,
                        "xver": 1
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "alpn": [
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "domian.crt", // 换成你的证书，绝对路径
                            "keyFile": "domian.key" // 换成你的私钥，绝对路径
                        }
                    ]
                }
            }
        },
        {
            "port": 1234,
            "listen": "127.0.0.1",
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "96849933-bbdb-4376-b008-68f17c04aff4", // 填写你的 UUID
                        "level": 0,
                        "email": "love@v2fly.org"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "ws",
                "security": "none",
                "wsSettings": {
                    "acceptProxyProtocol": true, // 提醒：若你用 Nginx/Caddy 等反代 WS，需要删掉这行
                    "path": "/123456" // 必须换成自定义的 PATH，需要和上面的一致
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ]
}
</code></pre></details>

### Client log

<details><pre><code>

</code></pre></details>

### Server log

<details><pre><code>
```
Xray 24.9.30 (Xray, Penetrates Everything.) 3b06af8 (go1.23.1 linux/amd64)
A unified platform for anti-censorship.
2024/10/24 12:38:13 [Debug] app/log: Logger started
2024/10/24 12:38:13 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:443
2024/10/24 12:38:13 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:1234
2024/10/24 12:38:13 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:443
2024/10/24 12:38:13 [Info] infra/conf/serial: Reading config: &{Name:/root/config.json Format:json}
2024/10/24 12:38:13 [Info] transport/internet/websocket: listening TCP(for WS) on 127.0.0.1:1234
2024/10/24 12:38:13 [Warning] transport/internet/websocket: accepting PROXY protocol
2024/10/24 12:38:13 [Warning] core: Xray 24.9.30 started
2024/10/24 12:39:18 [Info] [3641335632] proxy/vless/inbound: firstLen = 0
2024/10/24 12:39:18 [Info] [3641335632] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly
2024/10/24 12:39:18 [Info] [3641335632] proxy/vless/inbound: realName =
2024/10/24 12:39:18 [Info] [3641335632] proxy/vless/inbound: realAlpn =
2024/10/24 12:39:18 [Info] [3641335632] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > read tcp ip.ip:443->171.43.247.232:17246: i/o timeout
2024/10/24 12:40:06 [Info] [1339497051] proxy/vless/inbound: firstLen = 0
2024/10/24 12:40:06 [Info] [1339497051] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly
2024/10/24 12:40:06 [Info] [1339497051] proxy/vless/inbound: realName =
2024/10/24 12:40:06 [Info] [1339497051] proxy/vless/inbound: realAlpn =
2024/10/24 12:40:06 [Info] [1339497051] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > read tcp ip.ip:443->171.43.247.232:17433: read: connection reset by peer
2024/10/24 12:40:55 [Info] [3979425721] proxy/vless/inbound: firstLen = 0
2024/10/24 12:40:55 [Info] [3979425721] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly
2024/10/24 12:40:55 [Info] [3979425721] proxy/vless/inbound: realName =
2024/10/24 12:40:55 [Info] [3979425721] proxy/vless/inbound: realAlpn =
2024/10/24 12:40:55 [Info] [3979425721] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > read tcp ip.ip:443->171.43.247.232:17424: i/o timeout
2024/10/24 12:41:05 [Info] [2154690179] proxy/vless/inbound: firstLen = 0
2024/10/24 12:41:05 [Info] [2154690179] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly
2024/10/24 12:41:05 [Info] [2154690179] proxy/vless/inbound: realName =
2024/10/24 12:41:05 [Info] [2154690179] proxy/vless/inbound: realAlpn =
2024/10/24 12:41:05 [Info] [2154690179] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > read tcp ip.ip:443->171.43.247.232:17430: i/o timeout
2024/10/24 12:41:06 [Info] [3101464465] proxy/vless/inbound: firstLen = 0
2024/10/24 12:41:06 [Info] [3101464465] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly
2024/10/24 12:41:06 [Info] [3101464465] proxy/vless/inbound: realName =
2024/10/24 12:41:06 [Info] [3101464465] proxy/vless/inbound: realAlpn =
2024/10/24 12:41:06 [Info] [1876745691] proxy/vless/inbound: firstLen = 0
2024/10/24 12:41:06 [Info] [1876745691] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly
2024/10/24 12:41:06 [Info] [1876745691] proxy/vless/inbound: realName =
2024/10/24 12:41:06 [Info] [1876745691] proxy/vless/inbound: realAlpn =
2024/10/24 12:41:06 [Info] [1876745691] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > read tcp ip.ip:443->171.43.247.232:17437: i/o timeout
2024/10/24 12:41:06 [Info] [3101464465] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > read tcp ip.ip:443->171.43.247.232:17438: i/o timeout
2024/10/24 12:41:06 [Info] [1555936670] proxy/vless/inbound: firstLen = 0
2024/10/24 12:41:06 [Info] [1555936670] proxy/vless/inbound: fallback starts > proxy/vless/inbound: fallback directly
2024/10/24 12:41:06 [Info] [1555936670] proxy/vless/inbound: realName =
2024/10/24 12:41:06 [Info] [1555936670] proxy/vless/inbound: realAlpn =
2024/10/24 12:41:06 [Info] [1555936670] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > read tcp ip.ip:443->171.43.247.232:17436: i/o timeout
```
</code></pre></details>

**Comment by Fangliding** [comment]
issues is for reporting bugs, not helping area, you can seek help elsewhere
