### ISSUE TITLE
Shadowsocks2022 api AddUser error

### ISSUE THREAD

**Issue by fantik11** [XTLS/Xray-core#3943]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

While using 2022-blake3-aes-128-gcm cipher, when adding a user via RPC api an error occurs (Unknown desc = app/proxyman/command: proxy is not a UserManager). With all other ciphers (not 2022-*) adding works fine. I suspect that the problem is in protobuf, but I have not found any documentation on how to do it properly.

Rpc call snippet
```
_, err := ctl.HsClient.AlterInbound(context.Background(), &command.AlterInboundRequest{
	Tag: "shadowsocks-inbound",
	Operation: serial.ToTypedMessage(&command.AddUserOperation{
		User: &protocol.User{
			Level: 0,
			Email: "9f9d4b96-a550-4b38-82b3-d1821292da50@example.com",
			Account: serial.ToTypedMessage(&shadowsocks.Account{
				Password: "F6SZ0hClVS9qUyCt42dgArDzKIl6YYUE78dX04k1K/I=",
				// CipherType: ssCipherType, // Shadowsocks only, not 2022
			}),
		},
	}),
})
````

### Reproduction Method

- Use a minimal xray-core configuration with shadowsocks inbound and 2022-blake3-aes-128-gcm encryption
- Connect to the api and try to add a user using the code above
- RPC will return error "proxy is not a UserManager"

### Client config

<details><pre><code>

</code></pre></details>

### Server config

<details><pre><code>
{
  "log": {
    "loglevel": "debug"
  },
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "apiOut"
      },
    ]
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 8080,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "streamSettings": null,
      "tag": "api",
      "sniffing": null
    },
    {
      "listen": "0.0.0.0",
      "port": 12345,
      "protocol": "shadowsocks",
      "settings": {
        "password": "5UXfrllMpI1mo7NNc5qTXij+yxY4R+4H/YMfb1kcUqc=",
        "method": "2022-blake3-aes-128-gcm",
        "network": "tcp,udp"
      },
      "streamSettings": {
        "network": "tcp",
        "security": "none",
        "tcpSettings": {
          "acceptProxyProtocol": false,
          "header": {
            "type": "none"
          }
        }
      },
      "tag": "shadowsocks-inbound",
      "sniffing": {
        "destOverride": [
          "http",
          "tls",
          "quic",
          "fakedns"
        ],
        "enabled": true,
        "metadataOnly": false,
        "routeOnly": false
      }
    }
  ],
  "outbounds": [
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP"
      }
    },
  ],
  "policy": {
    "levels": {
      "0": {
        "statsUserUplink": false,
        "statsUserDownlink": false,
        "uplinkOnly": 0,
        "downlinkOnly": 0,
        "bufferSize": 2048
      }
    },
  },
  "api": {
    "tag": "apiOut",
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService",
      "ReflectionService"
    ]
  }
}
</code></pre></details>

### Client log

<details><pre><code>

</code></pre></details>

### Server log

<details><pre><code>
[XRAY-0][891964405] proxy/dokodemo: processing connection from: 127.0.0.1:41100
[XRAY-0][891964405] proxy/dokodemo: received request for 127.0.0.1:41100
[XRAY-0][891964405] app/dispatcher: taking detour [apiOut] for [tcp:127.0.0.1:0]
[XRAY-0]2024/10/25 00:54:40 from 127.0.0.1:41100 accepted tcp:127.0.0.1:0 [api -> apiOut]
2024/10/25 00:54:40 rpc error: code = Unknown desc = app/proxyman/command: proxy is not a UserManager
</code></pre></details>

**Comment by Fangliding** [comment]
你的猜测是正确的。这可能有些奇怪，其实shadowsocks2022中并没有所谓的多用户模式，xray中的“多用户模式”其实是通过协议定义中的relay实现的 正确的 protomessage构造方法可能需要参考这个函数
https://github.com/XTLS/Xray-core/blob/main/infra/conf/shadowsocks.go#L102

**Comment by fantik11** [comment]
Could you provide example please? I looked through the codebase and found that [this](https://github.com/XTLS/Xray-core/blob/94338c94e93ba4296042c295708808a79ff53bc8/app/proxyman/command/command.go#L41) function executed after all AddUserOperation, so I need to avoid using this protomessage. But how to alter inbound without it?

**Comment by Fangliding** [comment]
> Could you provide example please? I looked through the codebase and found that [this](https://github.com/XTLS/Xray-core/blob/94338c94e93ba4296042c295708808a79ff53bc8/app/proxyman/command/command.go#L41) function executed after all AddUserOperation, so I need to avoid using this protomessage. But how to alter inbound without it?

sorry, I made some mistake. Forget what I said
ss2022 has many mode, If you didn't enter multi user in the config, it will work in single user mode, in this situation, it has no user manager.
So the correct way to fix is writing `"clients":[]` (at least one valid user) to make it work at multi user mode

**Comment by fantik11** [comment]
> Sorry, I made some mistake. Forget what I said ss2022 has many mode, If you didn't enter multi user in the config, it will work in single user mode, in this situation, it has no user manager. So the correct way to fix is writing `"clients":[]` (at least one valid user) to make it work at multi user mode

Thank you, all works
