### ISSUE TITLE
建议新增支持配置启动进程数

### ISSUE THREAD

**Issue by 724899020** [XTLS/Xray-core#3946]
我在openwrt上运行xray-core，我路由器内存有限，但是默认就启动了1+8个进程。。。。我的xray并不需要服务多大流量，启动8个进程占用了我太多内存。。麻烦可以配置启动进程数量。chatgpt告诉我可以用 export GOMAXPROCS=2的方式控制，但是没有效果。

**Comment by Fangliding** [comment]
你设置的环境变量不一定传达的到程序 取决于它是怎么启动的
还有就算你设置了也不一定降低启动的线程 因为这个参数限制的是能同时运行的线程而不是go能启动的线程
