### ISSUE TITLE
送每天200G不限速

### ISSUE THREAD

**Issue by wangjikuaiche** [XTLS/Xray-core#3956]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

网际快车，全中转线路
官网:wjkc123.com
免费账号：88888888@wjkc123.com 密码: 88888888
每天200G不限速，超过后限速20Mbits

### 重现方式

网际快车，全中转线路
官网:wjkc123.com
免费账号：88888888@wjkc123.com 密码: 88888888
每天200G不限速，超过后限速20Mbits

### 客户端配置

网际快车，全中转线路
官网:wjkc123.com
免费账号：88888888@wjkc123.com 密码: 88888888
每天200G不限速，超过后限速20Mbits

### 服务端配置

网际快车，全中转线路
官网:wjkc123.com
免费账号：88888888@wjkc123.com 密码: 88888888
每天200G不限速，超过后限速20Mbits

### 客户端日志

网际快车，全中转线路
官网:wjkc123.com
免费账号：88888888@wjkc123.com 密码: 88888888
每天200G不限速，超过后限速20Mbits

### 服务端日志

网际快车，全中转线路
官网:wjkc123.com
免费账号：88888888@wjkc123.com 密码: 88888888
每天200G不限速，超过后限速20Mbits

**Comment by RPRX** [comment]
Blocked，原始内容已删
