### ISSUE TITLE
Program coding upgrade

### ISSUE THREAD

**Issue by decorativefamily** [XTLS/Xray-core#3957]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

Available Issue

### 重现方式

https://www.codefactor.io/repository/github/xtls/xray-core

### 客户端配置

https://github.com/user-attachments/assets/cf48cb54-b322-4df1-988a-203b39e59098

### 服务端配置

<details><pre><code>

</code></pre></details>

### 客户端日志

<details><pre><code>

</code></pre></details>

### 服务端日志

<details><pre><code>

</code></pre></details>

**Comment by Fangliding** [comment]
Bad code is everywhere, pr is welcome

**Comment by Fangliding** [comment]
Just to mention, if you just throw a link and saying you should refactor may be considered impolite in many places（

**Comment by mmmray** [comment]
there are many tools like this, many of them only produce noise (don't know about this one), i tend to assume this is not worth the time. if there is a major thing to refactor, even then I think it's not sensible to open issues for
