### ISSUE TITLE
升级至24.10.31，在没有修改任何配置的情况下Vmess和Vless节点无法使用。

### ISSUE THREAD

**Issue by AquaSimulacra** [XTLS/Xray-core#3959]
### 完整性要求

- [ ] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [ ] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

升级至24.10.31，在没有修改任何配置的情况下Vmess和Vless节点无法使用。降级至24.10.16后恢复正常。

### 重现方式

从24.10.16升级至24.10.31。出现如下报错
![image](https://github.com/user-attachments/assets/770bed5f-4f40-49b4-b910-dae3c1d9063b)

### 客户端配置

<details><pre><code>
N/A
</code></pre></details>

### 服务端配置

<details><pre><code>
{
  "log": {
    "access": "none",
    "dnsLog": true,
    "error": "./error.log",
    "loglevel": "error"
  },
  "api": {
    "tag": "api",
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ]
  },
  "inbounds": [
    {
      "tag": "api",
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      }
    }
  ],
  "outbounds": [
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP"
      }
    },
    {
      "tag": "blocked",
      "protocol": "blackhole",
      "settings": {}
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "statsUserDownlink": true,
        "statsUserUplink": true
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true,
      "statsOutboundDownlink": true,
      "statsOutboundUplink": true
    }
  },
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api"
      },
      {
        "type": "field",
        "outboundTag": "blocked",
        "ip": [
          "geoip:private"
        ]
      },
      {
        "type": "field",
        "outboundTag": "blocked",
        "domain": [
          "geosite:category-ads-all",
          "ext:geosite_IR.dat:category-ads-all"
        ]
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "geoip:cn"
        ]
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": [
          "geosite:cn",
          "regexp:.*\\.cn$"
        ]
      }
    ]
  },
  "stats": {}
}
</code></pre></details>

### 客户端日志

<details><pre><code>
N/A
</code></pre></details>

### 服务端日志

<details><pre><code>
对不起，我找不到服务端的日志在哪
</code></pre></details>

**Comment by Fangliding** [comment]
无效config 没有日志

**Comment by AquaSimulacra** [comment]
经过排查之后发现和wireguard有关
{
  "id": 7,
  "userId": 0,
  "up": 0,
  "down": 0,
  "total": 0,
  "remark": "WireGuard",
  "enable": true,
  "expiryTime": 0,
  "listen": "",
  "port": ,
  "protocol": "wireguard",
  "settings": "{\n  \"mtu\": 1420,\n  \"secretKey\": \"=\",\n  \"peers\": [\n    {\n      \"privateKey\": \"=\",\n      \"publicKey\": \"=\",\n      \"preSharedKey\": \"=\",\n      \"allowedIPs\": [\n        \"10.0.0.2/32\"\n      ],\n      \"keepAlive\": 0\n    }\n  ],\n  \"kernelMode\": false\n}",
  "streamSettings": "",
  "tag": "inbound",
  "sniffing": "{\n  \"enabled\": true,\n  \"destOverride\": [\n    \"http\",\n    \"tls\",\n    \"quic\",\n    \"fakedns\"\n  ],\n  \"metadataOnly\": false,\n  \"routeOnly\": false\n}",
  "clientStats": []
}

**Comment by Fangliding** [comment]
好吧我懂了
