### ISSUE TITLE
gomobile bind failing for IOS target

### ISSUE THREAD

**Issue by alikashan** [XTLS/Xray-core#3961]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

I am running `gomobile bind -target=ios/arm64` command to generate IOS .xcframework 

but it is failing with error

`gomobile: /Users/user/go/bin/gobind -lang=go,objc -outdir=/var/folders/47/9fhwlylx55xb9x7cgywsbh100000gn/T/gomobile-work-3462033653/ios -tags=ios . failed: exit status 1
no exported names in the package "."
no exported names in the package "."
no exported names in the package "."
no exported names in the package "."`

### Reproduction Method

gomobile bind -target=ios/arm64

### Client config

<details><pre><code>
not specified
</code></pre></details>

### Server config

<details><pre><code>
not specified
</code></pre></details>

### Client log

<details><pre><code>
not specified
</code></pre></details>

### Server log

<details><pre><code>
not specified
</code></pre></details>

**Comment by Fangliding** [comment]
?
gomobile bind -target=ios/arm64 PkgName
And this repository is not intended to be compiled into lib

**Comment by alikashan** [comment]
> ? gomobile bind -target=ios/arm64 PkgName And this repository is not intended to be compiled into lib

are you planning to add mobile support soon? or can you suggest any repo for mobile?

I want to create Android and IOS native libraries so that I can use them in my own VPN applications
