### ISSUE TITLE
Wireguard + fakedns go panic

### ISSUE THREAD

**Issue by eichgee** [XTLS/Xray-core#3962]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

Client version: 1.8.24 (latest version still giving same error)

When core instance close immediately after receiving connection request it will panic but if there's some delay before close, panic didn't occur. in this case it seems wireguard client trying to close multiple times. i have no issue if i disabled fakedns feature.

19:25:12.664  E  panic: close of closed channel
19:25:12.664  E  
19:25:12.665  E  goroutine 37 [running]:
19:25:12.666  E  github.com/xtls/xray-core/proxy/wireguard/gvisortun.(*netTun).Close(0xc000266ea0)
19:25:12.667  E  	Xray-core/proxy/wireguard/gvisortun/tun.go:180 +0x38
19:25:12.669  E  github.com/xtls/xray-core/proxy/wireguard.(*tunnel).Close(0xc0002668d0)
19:25:12.672  E  	Xray-core/proxy/wireguard/tun.go:89 +0xc4
19:25:12.673  E  github.com/xtls/xray-core/proxy/wireguard.(*gvisorNet).Close(0xc0004945b0?)
19:25:12.675  E  	Xray-core/proxy/wireguard/tun.go:127 +0x15
19:25:12.676  E  github.com/xtls/xray-core/proxy/wireguard.(*Handler).makeVirtualTun(0xc0004945b0)
19:25:12.677  E  	Xray-core/proxy/wireguard/client.go:250 +0xd3
19:25:12.684  E  github.com/xtls/xray-core/proxy/wireguard.(*Handler).processWireGuard(0xc0004945b0, {0x7fa550800998, 0xc0004ac5a0}, {0x7fa5507fef40, 0xc0004a0580})
19:25:12.685  E  	Xray-core/proxy/wireguard/client.go:122 +0x32b
19:25:12.692  E  github.com/xtls/xray-core/proxy/wireguard.(*Handler).Process(0xc0004945b0, {0x7fa550800998, 0xc0004ac5a0}, 0xc000331620, {0x7fa5507fef40, 0xc0004a0580})
19:25:12.694  E  	Xray-core/proxy/wireguard/client.go:139 +0x113
19:25:12.697  E  github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dispatch(0xc0004a0580, {0x7fa550800998, 0xc0004ac5a0}, 0xc000331620)
19:25:12.698  E  	Xray-core/app/proxyman/outbound/handler.go:211 +0x388
19:25:12.704  E  github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc000475aa0, {0x7fa550800998, 0xc0004ac5a0}, 0xc000331620, {{0x7fa550800ca8, 0xc000487420}, 0x1bb, 0x2})
19:25:12.705  E  	Xray-core/app/dispatcher/default.go:471 +0xa66
19:25:12.705  E  created by github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 36
19:25:12.706  E  	Xray-core/app/dispatcher/default.go:252 +0x56c
19:25:12.707  A  Fatal signal 6 (SIGABRT), code -6 in tid 9324 (com.xx.xx)

### Reproduction Method

Here is the golang code i used to reproduce issue

```
func MeasureOutboundDelay(ConfigureFileContent string, Url string) (string, error) {
	config, err := v2serial.LoadJSONConfig(strings.NewReader(ConfigureFileContent))
	if err != nil {
		return "", err
	}

	config.Inbound = nil

	inst, err := v2core.New(config)
	if err != nil {
		return "", err
	}

	err = inst.Start()
	if err != nil {
		return "", err
	}

	defer inst.Close()
	delay, err := measureInstDelay(context.Background(), inst, Url)
	return delay, err
}

func measureInstDelay(ctx context.Context, inst *v2core.Instance, url string) (string, error) {
	req, err := http.NewRequestWithContext(ctx, "HEAD", url, nil)
	if err != nil {
		return "", err
	}
	req.Header.Add("Connection", "close")
	req.Header.Add("Accept-Encoding", "gzip")

	connectTimeout := 5 * time.Second

	tr := &http.Transport{
		TLSHandshakeTimeout: connectTimeout,
		TLSClientConfig: &tls.Config{
			InsecureSkipVerify: true,
		},
		DisableKeepAlives: true,
		DialContext: func(ctx context.Context, network, addr string) (net.Conn, error) {
			dest, err := v2net.ParseDestination(fmt.Sprintf("%s:%s", network, addr))
			if err != nil {
				return nil, err
			}
			return v2core.Dial(ctx, inst, dest)
		},
	}

	c := &http.Client{
		Transport: tr,
		Timeout:   connectTimeout,
	}

	start := time.Now()
	resp, err := c.Do(req)
	if err != nil {
		return "", err
	}
	defer c.CloseIdleConnections()
	defer resp.Body.Close()

	timeElapsed := time.Since(start).Milliseconds()
	httpStatus := resp.Status

	return fmt.Sprintf("%s,%d", httpStatus, timeElapsed), nil
}
```

### Client config

<details><pre><code>
{
  "log": {
    "loglevel": "debug"
  },
  "policy": {
    "0": {
      "handshake": 4,
      "connIdle": 300,
      "uplinkOnly": 0,
      "downlinkOnly": 0,
      "bufferSize": 0
    }
  },
  "inbounds": [
    {
      "port": 1080,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "settings": {
        "udp": true
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "fakedns"
        ]
      },
      "tag": "socks"
    },
    {
      "listen": "0.0.0.0",
      "port": 7777,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "8.8.8.8",
        "network": "tcp,udp",
        "port": 53
      },
      "tag": "dns-inbound"
    }
  ],
  "outbounds": [
    {
      "protocol": "wireguard",
      "settings": {
        "secretKey": "secretKey",
        "peers": [
          {
            "endpoint": "example:5555",
            "publicKey": "publicKey"
          }
        ],
        "address": [
          "10.10.10.10"
        ]
      },
      "tag": "proxy",
      "mux": {
        "enabled": false,
        "concurrency": 8,
        "xudpConcurrency": 8,
        "xudpProxyUDP443": "reject"
      }
    },
    {
      "protocol": "freedom",
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    },
    {
      "protocol": "dns",
      "tag": "dns-outbound"
    }
  ],
  "routing": {
    "domainMatcher": "mph",
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "inboundTag": "dns-inbound",
        "outboundTag": "dns-outbound",
        "type": "field"
      },
      {
        "type": "field",
        "ip": [
          "8.8.8.8",
          "8.8.4.4"
        ],
        "port": "53",
        "outboundTag": "proxy"
      }
    ]
  },
  "dns": {
    "servers": [
      "fakedns",
      "8.8.8.8",
      "8.8.4.4"
    ]
  },
  "fakedns": [
    {
      "ipPool": "198.18.0.0\/16",
      "poolSize": 65536
    }
  ]
}
</code></pre></details>

### Server config

<details><pre><code>
n/a
</code></pre></details>

### Client log

<details><pre><code>
2024/11/01 15:18:32 [Debug] app/log: Logger started
2024/11/01 15:18:32 [Info] app/dns: DNS: created UDP client initialized for 8.8.8.8:53
2024/11/01 15:18:32 [Info] app/dns: DNS: created UDP client initialized for 8.8.4.4:53
2024/11/01 15:18:32 [Warning] core: Xray 1.8.24 started
2024/11/01 15:18:32 [Info] app/dispatcher: default route for tcp:www.google.com:443
2024/11/01 15:18:32 [Info] switching dialer
2024/11/01 15:18:32 from DNS accepted udp:8.8.8.8:53 [xray.system.75b66e05-c2c8-43b5-8dc6-a43e1436419d -> proxy]
2024/11/01 15:18:32 [Debug] app/dns: domain myserver.com will use DNS in order: [FakeDNS UDP:8.8.8.8:53 UDP:8.8.4.4:53]
2024/11/01 15:18:32 [Debug] app/dns: skip DNS resolution for domain myserver.com at server FakeDNS
2024/11/01 15:18:32 [Debug] app/dns: UDP:8.8.8.8:53 querying DNS for: myserver.com.
2024/11/01 15:18:32 [Debug] transport/internet/udp: dispatch request to: udp:8.8.8.8:53
2024/11/01 15:18:32 [Info] transport/internet/udp: establishing new connection for udp:8.8.8.8:53
2024/11/01 15:18:32 [Info] app/dispatcher: taking detour [proxy] for [udp:8.8.8.8:53]
2024/11/01 15:18:36 [Info] app/dns: failed to lookup ip for domain myserver.com at server UDP:8.8.8.8:53 > context deadline exceeded
2024/11/01 15:18:36 [Debug] app/dns: UDP:8.8.4.4:53 querying DNS for: myserver.com.
2024/11/01 15:18:36 [Debug] transport/internet/udp: dispatch request to: udp:8.8.4.4:53
2024/11/01 15:18:36 [Info] transport/internet/udp: establishing new connection for udp:8.8.4.4:53
2024/11/01 15:18:36 from DNS accepted udp:8.8.4.4:53 [xray.system.75b66e05-c2c8-43b5-8dc6-a43e1436419d -> proxy]
2024/11/01 15:18:36 [Info] app/dispatcher: taking detour [proxy] for [udp:8.8.4.4:53]
2024/11/01 15:18:37 [Debug] app/log: Logger closing
</code></pre></details>

### Server log

<details><pre><code>
n/a
</code></pre></details>

**Comment by Fangliding** [comment]
Your config caused dns loop
