### ISSUE TITLE
Xray doesn't bind to 51820 when using WireGuard inbound

### ISSUE THREAD

**Issue by robigan** [XTLS/Xray-core#3970]
***My main Question: How do I turn on debug output in XRay to find out why it isn't binding?***

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

My configuration was working a week ago, after a period of inactivity, XRay has stopped binding to 51820 when using WireGuard inbound. I have no idea what's going on, and I am not sure how to get XRay to provide more debug output. This is happening both on versions v24.10.31 and v24.9.30. 

### Reproduction Method

Setup server with XRay in Docker and give it necessary server config and certs, download XRay through Homebrew on MacOS and start it with client config. Run `sudo lsof -PiTCP -sTCP:LISTEN` on MacOS and find out that XRay isn't bound to 51820 for WG, but is successfully bound to 1086 for SOCKS proxy. When attempting to use WireGuard for MacOS and connect, it somehow magically connects without reporting any issues. (I don't think WG for MacOS reports incorrect handshakes).

My WG config:
```
[Interface]
PrivateKey = uLCmH2vxOIEiVRdjj93yDS7MsPKai9o36wffRXASW24=

[Peer]
PublicKey = MFV2TgX6LCztW8xWPtVp58iiYKR51Owa3kX75rupfVk=
AllowedIPs = 0.0.0.0/5, 8.0.0.0/7, 11.0.0.0/8, 12.0.0.0/6, 16.0.0.0/4, 32.0.0.0/5, 40.0.0.0/6, 44.0.0.0/8, 45.0.0.0/9, 45.128.0.0/13, 45.136.0.0/20, 45.136.16.0/21, 45.136.24.0/22, 45.136.28.0/23, 45.136.30.0/25, 45.136.30.128/26, 45.136.30.192/29, 45.136.30.200/30, 45.136.30.204/32, 45.136.30.206/31, 45.136.30.208/28, 45.136.30.224/27, 45.136.31.0/24, 45.136.32.0/19, 45.136.64.0/18, 45.136.128.0/17, 45.137.0.0/16, 45.138.0.0/15, 45.140.0.0/14, 45.144.0.0/12, 45.160.0.0/11, 45.192.0.0/10, 46.0.0.0/7, 48.0.0.0/4, 64.0.0.0/2, 128.0.0.0/3, 160.0.0.0/5, 168.0.0.0/6, 172.0.0.0/12, 172.32.0.0/11, 172.64.0.0/10, 172.128.0.0/9, 173.0.0.0/8, 174.0.0.0/7, 176.0.0.0/4, 192.0.0.0/9, 192.128.0.0/11, 192.160.0.0/13, 192.169.0.0/16, 192.170.0.0/15, 192.172.0.0/14, 192.176.0.0/12, 192.192.0.0/10, 193.0.0.0/8, 194.0.0.0/7, 196.0.0.0/6, 200.0.0.0/5, 208.0.0.0/4, 224.0.0.0/3
Endpoint = 127.0.0.1:51820
```

### Client config

<details><pre><code>
{
    "inbounds": [
        {
            "port": 1086, // SOCKS proxy port, you need to configure the proxy in the browser and point to this port
            "listen": "127.0.0.1",
            "protocol": "socks",
            "settings": {
                "udp": true
            }
        },
        {
            "listen": "127.0.0.1",
            "port": 51820,
            "protocol": "wireguard",
            "settings": {
                "secretKey": "iF+mx9/eOYhEk+CRO+1iP5u0/t8nlH2upTtd1vv/jHc=",
                "peers": [
                    {
                        "publicKey": "Aeoln4SN8ifRDOBw+KCipS12y072rbXINZxQEd9QqQw=",
                        "allowedIPs":["0.0.0.0/0"]
                    }
                ],
                "noKernelTun": true, // disables kernel mode checking
                "mtu": 1420 // optional, default 1420
            }              
        }
    ],
    "outbounds": [
        // {
        //     "protocol": "vmess",
        //     "settings": {
        //         "vnext": [
        //             {
        //                 "address": "45.136.30.205", // server address, please modify it to your own server ip or domain name
        //                 "port": 21906, // server port
        //                 "users": [
        //                     {
        //                         "id": "638f6e5e-8e02-46aa-8a2e-250a0701b6b5"
        //                     }
        //                 ]
        //             }
        //         ]
        //     }
        // },
        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "45.136.30.205", // server address, please modify it to your own server ip or domain name
                        "port": 443, // server port
                        "users": [
                            {
                                "id": "638f6e5e-8e02-46aa-8a2e-250a0701b6b5",
                                "encryption": "none"/* , */
                                // "flow": "xtls-rprx-vision"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "serverName": "robigan.com", // SNI, if "address" is filled with the domain name of the server, it can be left blank. If "address" is filled with the IP of the server, fill in the domain name contained in the certificate of the server here
                    "allowInsecure": false,
                    "fingerprint": "chrome" // Used to configure the fingerprint of the specified TLS Client Hello, Xray will simulate the TLS fingerprint through the uTLS library, or generate it randomly
                }
            },
            "tag": "vless-outbound"
        },
        {
            "protocol": "freedom",
            "tag": "direct"
        }
    ],
    "routing": {
        "domainStrategy": "IPOnDemand",
        "rules": [
            {
                "type": "field",
                "ip": [
                    "geoip:private"
                ],
                "outboundTag": "direct"
            }
        ]
    }
}
</code></pre></details>

### Server config

<details><pre><code>
// Config file of V2Ray. This file follows standard JSON format, with comments support.
// Uncomment entries below to satisfy your needs. Also read our manual for more detail at
// https://www.v2fly.org/
{
  "log": {
    // By default, V2Ray writes access log to stdout.
    // "access": "/path/to/access/log/file",

    // By default, V2Ray write error log to stdout.
    // "error": "/path/to/error/log/file",

    // Log level, one of "debug", "info", "warning", "error", "none"
    "loglevel": "warning"
  },
  // List of inbound proxy configurations.
  "inbounds": [/* {
    // Port to listen on. You may need root access if the value is less than 1024.
    "port": 21906,
    // IP address to listen on. Change to "0.0.0.0" to listen on all network interfaces.
    "listen": "0.0.0.0",
    // Tag of the inbound proxy. May be used for routing.
    "tag": "vmess-inbound",
    // Protocol name of inbound proxy.
    "protocol": "vmess",
    // Settings of the protocol. Varies based on protocol.
    "settings": {
      "clients": [
        {
          "id": "638f6e5e-8e02-46aa-8a2e-250a0701b6b5"
        }
      ]
    }
    // Enable sniffing on TCP connection.
    //"sniffing": {
      //"enabled": true,
      // Target domain will be overriden to the one carried by the connection, if the connection is HTTP or HTTPS.
      //"destOverride": ["http", "tls"]
    //}
  }, */{
    // Port to listen on. You may need root access if the value is less than 1024.
    "port": 443,
    // IP address to listen on. Change to "0.0.0.0" to listen on all network interfaces.
    "listen": "0.0.0.0",
    // Tag of the inbound proxy. May be used for routing.
    "tag": "vless-inbound",
    // Protocol name of inbound proxy.
    "protocol": "vless",
    // Settings of the protocol. Varies based on protocol.
    "settings": {
      "clients": [
        {
          "id": "638f6e5e-8e02-46aa-8a2e-250a0701b6b5"/* , */
          // "flow": "xtls-rprx-vision"
        }
      ],
      "decryption": "none"
    },
    // Transport/Stream settings
    "streamSettings": {
			"network": "tcp",
			"security": "tls",
			"tlsSettings": {
				"alpn": ["h2", "http/1.1"],
        "minVersion": "1.3",
				"certificates": [{
					"certificateFile": "/etc/xray/cert/pub.pem",
					"keyFile": "/etc/xray/cert/key.pem"
				}]
			}
		}
  }],
  // List of outbound proxy configurations.
  "outbounds": [{
    // Protocol name of the outbound proxy.
    "protocol": "freedom",
    // Settings of the protocol. Varies based on protocol.
    "settings": {},
    // Tag of the outbound. May be used for routing.
    "tag": "direct"
  },{
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  }],

  // Transport is for global transport settings. If you have multiple transports with same settings
  // (say mKCP), you may put it here, instead of in each individual inbound/outbounds.
  //"transport": {},

  // Routing controls how traffic from inbounds are sent to outbounds.
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules":[
      {
        // Blocks access to private IPs. Remove this if you want to access your router.
        "type": "field",
        "ip": ["geoip:private"],
        "outboundTag": "blocked"
      }
    ]
  },

  // Dns settings for domain resolution.
  "dns": {
    // Static hosts, similar to hosts file.
    // "hosts": {
    //   // Match v2fly.org to another domain on CloudFlare. This domain will be used when querying IPs for v2fly.org.
    //   "domain:v2fly.org": "www.vicemc.net"

    //   // The following settings help to eliminate DNS poisoning in mainland China.
    //   // It is safe to comment these out if this is not the case for you.
    //   // "domain:github.io": "pages.github.com",
    //   // "domain:wikipedia.org": "www.wikimedia.org",
    //   // "domain:shadowsocks.org": "electronicsrealm.com"
    // },
    "servers": [
      // "1.1.1.1",
      // "1.0.0.1"
      "https+local://1.1.1.1/dns-query"
      // {
      //   "address": "114.114.114.114",
      //   "port": 53,
      //   // List of domains that use this DNS first.
      //   "domains": [
      //     "geosite:cn"
      //   ]
      // },
      // "8.8.8.8",
      // "localhost"
    ]
  }

  // Policy controls some internal behavior of how V2Ray handles connections.
  // It may be on connection level by user levels in 'levels', or global settings in 'system.'
  // "policy": {
  //   // Connection policys by user levels
  //   "levels": {
  //     "0": {
  //       "uplinkOnly": 0,
  //       "downlinkOnly": 0
  //     }
  //   },
  //   "system": {
  //     "statsInboundUplink": false,
  //     "statsInboundDownlink": false,
  //     "statsOutboundUplink": false,
  //     "statsOutboundDownlink": false
  //   }
  // },

  // Stats enables internal stats counter.
  // This setting can be used together with Policy and Api.
  // "stats":{},

  // Api enables gRPC APIs for external programs to communicate with V2Ray instance.
  //"api": {
    //"tag": "api",
    //"services": [
    //  "HandlerService",
    //  "LoggerService",
    //  "StatsService"
    //]
  //},

  // You may add other entries to the configuration, but they will not be recognized by V2Ray.
  // "other": {}
}
</code></pre></details>

### Client log

<details><pre><code>
Xray 24.10.31 (Xray, Penetrates Everything.) Custom (go1.23.2 darwin/arm64)
A unified platform for anti-censorship.
2024/11/04 21:40:32 [Info] infra/conf/serial: Reading config: &{Name:./v2fly-client.json Format:json}
2024/11/04 21:40:32 [Warning] proxy/wireguard: Using gVisor TUN.
2024/11/04 21:40:35 [Warning] core: Xray 24.10.31 started
</code></pre></details>

### Server log

<details><pre><code>
2024/11/05 03:54:13 from DNS accepted https://1.1.1.1/dns-query [local]
2024/11/05 03:54:13 from DNS accepted https://1.1.1.1/dns-query [local]
2024/11/05 03:54:13 from 2.40.58.148:57386 accepted tcp:firefox.settings.services.mozilla.com:443 [vless-inbound >> direct]
2024/11/05 03:54:15 from 2.40.58.148:57391 accepted tcp:ac.duckduckgo.com:443 [vless-inbound >> direct]
2024/11/05 03:54:15 from 2.40.58.148:57393 accepted tcp:ac.duckduckgo.com:443 [vless-inbound >> direct]
2024/11/05 03:54:15 from 2.40.58.148:57395 accepted tcp:ac.duckduckgo.com:443 [vless-inbound >> direct]
2024/11/05 03:54:15 from 2.40.58.148:57398 accepted tcp:www.google.com:443 [vless-inbound >> direct]
2024/11/05 03:54:15 from 2.40.58.148:57401 accepted tcp:lh3.googleusercontent.com:443 [vless-inbound >> direct]
2024/11/05 03:54:15 from 2.40.58.148:57402 accepted tcp:www.gstatic.com:443 [vless-inbound >> direct]
2024/11/05 03:54:16 from 2.40.58.148:57407 accepted tcp:ogads-pa.clients6.google.com:443 [vless-inbound >> direct]
2024/11/05 03:54:16 from 2.40.58.148:57409 accepted tcp:apis.google.com:443 [vless-inbound >> direct]
...
</code></pre></details>

**NB: Traffic information is from when using SOCKS proxy instead, which works**

**Comment by Fangliding** [comment]
It works, it's fine (((

**Comment by robigan** [comment]
> It works, it's fine (((

Then how come it's not binding? Is there any way to turn on more verbose logging so I can find out what the problem is?

**Comment by robigan** [comment]
Got it working eventually by setting an Address field for my WireGuard client's Interface, although it isn't explicitly required by WireGuard macOS. (I thought macOS implementation would tunnel regardless)

For the record, I found that verbose logging is turned on through the config.
