### ISSUE TITLE
docker最新版本wireguard出站功能无法正常使用

### ISSUE THREAD

**Issue by atlanticfirst** [XTLS/Xray-core#3975]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

docker新版本里的wireguard出站似乎无法使用，日志里也沒有发现报错，尝试了把noKernelTun设置成true或者false都不行，只有wireguard出站的流量会遇到问题，direct的流量就是正常的，日志里很多app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > context canceled以及context deadline exceeded错误

### 重现方式

能夠正常打开网页

### 客户端配置

无配置

### 服务端配置

   {
      "tag": "wireguard",
      "protocol": "wireguard",
      "settings": {
          "noKernelTun": false,
          "secretKey": "psk",
          "address": [
              "ip"
          ],
          "peers": [
              {
                  "publicKey": "pbk",
                  "keepAlive": 25,
                  "allowedIPs": [
                      "0.0.0.0/0"
                  ],
                  "endpoint": "ip:port"
              }
          ]
      }
    },

### 客户端日志

 无日志

### 服务端日志

 沒有报错

**Comment by Fangliding** [comment]
约等于没有的信息 无法复现

**Comment by hahach** [comment]
我今天从上个月的release升级了一下，也遇到kerneltun的问题，配置文件是以前的，没有填这个选项，服务端wireguard出站有问题。有大量[Warning] proxy/wireguard: Using kernel TUN. 提示。
我这添加设置为false后问题到是解决了。服务端是openvz小鸡，开启了tun权限
