### ISSUE TITLE
apache2反代+回落

### ISSUE THREAD

**Issue by badgv** [XTLS/Xray-core#398]
目前环境：客户端使用wss连接apache2，apache2做ws反向代理指向xray的tcp监听端口，做回落至xray的ws监听端口，能正常使用.
尝试添加 http/2的支持：
客户端使用http/2连接apache2,apache2已开启http2和proxy_http2模块，apache2做h2c反向代理指向xray的tcp监听端，做回落至xray的h2(无加密)监听端口，无法使用。
apache2反代配置：
![image](https://user-images.githubusercontent.com/45598380/111570074-f9e5ab80-87de-11eb-8187-21355fe43dce.png)
xray配置:
![image](https://user-images.githubusercontent.com/45598380/111570155-226da580-87df-11eb-91e1-199f08a2b394.png)
![image](https://user-images.githubusercontent.com/45598380/111570188-36190c00-87df-11eb-8937-46a7d31585b1.png)
请教下大佬们是哪里不对导致http/2不能这样反代使用

**Comment by AkinoKaede** [comment]
启用了 `acceptProxyProtocol`，应该设置 `xver` 为 1 或 2

**Comment by badgv** [comment]
> 启用了 `acceptProxyProtocol`，应该设置 `xver` 为 1 或 2

xver我也试过设置为1，还是用不了，还有可能是哪里不对呢？

**Comment by rprx** [comment]
`path` 不支持 h2c

**Comment by badgv** [comment]
> `path` 不支持 h2c

那意思是xray回落配置不能加path是吗？
我客户端是带path的，是不是把apache2中的反代配置，删除/XXXX目录，回落删除/XXXX,只保留alpn吗？

**Comment by badgv** [comment]
> `path` 不支持 h2c

我现在直接用h2，不使用h2c了，xray回落到h2+tls(自签证书）,apache2忽略了证书验证，也连不上
