### ISSUE TITLE
Statsonline API bug

### ISSUE THREAD

**Issue by hiddify-com** [XTLS/Xray-core#3983]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

I was trying to updating `https://github.com/hiddify/xtlsapi` However, the new `statsonline` API seems is not working. while, the statsquery works fine. 
It shows the following error:
``` 
failed to get stats: rpc error: code = Unknown desc = app/stats/command: user>>>>>>online not found.
```

### Reproduction Method

run xray and try to use new commands
```
./xray api statsonline
failed to get stats: rpc error: code = Unknown desc = app/stats/command: user>>>>>>online not found.
```

```
 ./xray api stats
failed to get stats: rpc error: code = Unknown desc = app/stats/command:  not found.
```

```
 ./xray api statsquery
{
    "stat": [
        {
            "name": "outbound>>>freedom>>>traffic>>>uplink",
            "value": 146
        },
        {
            "name": "outbound>>>out>>>traffic>>>uplink"
        },
        {
            "name": "user>>>4b50ac78-80e7-4749-bc73-9b44bc32d071@hiddify.com>>>traffic>>>uplink",
            "value": 146
        },
        {
            "name": "inbound>>>xtls>>>traffic>>>downlink"
        },
        {
            "name": "inbound>>>socks>>>traffic>>>downlink",
            "value": 1288
        },
        {
            "name": "inbound>>>xtls>>>traffic>>>uplink",
            "value": 210
        },
        {
            "name": "outbound>>>freedom>>>traffic>>>downlink",
            "value": 1272
        },
        {
            "name": "outbound>>>out>>>traffic>>>downlink",
            "value": 1276
        },
        {
            "name": "user>>>4b50ac78-80e7-4749-bc73-9b44bc32d071@hiddify.com>>>traffic>>>downlink",
            "value": 1272
        },
        {
            "name": "inbound>>>socks>>>traffic>>>uplink",
            "value": 184
        }
    ]
}
```

### Client config

<details><pre><code>
not applicable
</code></pre></details>

### Server config

<details><pre><code>
{
  "log": {
    "loglevel": "debug"
  },
  "inbounds": [
    {
      "tag": "socks",
      "listen": "127.0.0.1",
      "port": 1234,
      "protocol": "socks",
      "settings": {
        "udp": true
      }
    },
    {
      "tag": "xtls",
      "listen": "127.0.0.1",
      "port": 1235,
      "protocol": "vless",
      "settings": {
        "decryption": "none",
        "clients": [
          {
            "id": "4b50ac78-80e7-4749-bc73-9b44bc32d071",
            "email": "4b50ac78-80e7-4749-bc73-9b44bc32d071@hiddify.com"
          }
        ]
      }
    }
  ],
  "outbounds": [
    {
      "tag": "freedom",
      "protocol": "freedom"
    },
    {
      "tag": "out",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "127.0.0.1",
            "port": 1235,
            "users": [
              {
                "id": "4b50ac78-80e7-4749-bc73-9b44bc32d071",
                "encryption": "none"
              }
            ]
          }
        ]
      }
    }
  ],
  "api": {
    "tag": "api",
    "listen": "127.0.0.1:8080",
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService",
      "RoutingService"
    ]
  },
  "stats": {},
  "policy": {
    "levels": {
      "0": {
        "statsUserUplink": true,
        "statsUserDownlink": true,
        "statsUserOnline": true
        
      }
    },
    "system": {
      "statsInboundUplink": true,
      "statsInboundDownlink": true,
      "statsOutboundUplink": true,
      "statsOutboundDownlink": true
    }
  },
  "routing": {
    "rules": [
      {
        "inboundTag": [
          "socks"
        ],
        "outboundTag": "out",
        "type": "field"
      },
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      }
    ]
  }
}
</code></pre></details>

### Client log

<details><pre><code>
not applicable
</code></pre></details>

### Server log

<details><pre><code>
Noting
</code></pre></details>

**Comment by Fangliding** [comment]
broken #3637 @hossinasaadi

**Comment by Fangliding** [comment]
It needs a connection to create that object

**Comment by hiddify-com** [comment]
I have created a connection. As you can see the connection has been already established.
``` 
 {
            "name": "user>>>4b50ac78-80e7-4749-bc73-9b44bc32d071@hiddify.com>>>traffic>>>downlink",
            "value": 1272
        }
```

**Comment by Fangliding** [comment]
./xray api statsonline -server=127.0.0.1:8080 -email "love@xray.com"
