### ISSUE TITLE
透明代理的时候，http代理无法通过远端发出

### ISSUE THREAD

**Issue by cod1ingcoding** [XTLS/Xray-core#3989]
### 完整性要求

- [x] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [ ] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

最新版本的xray，在透明代理下的主机，其他一切正常，

但是如果用类似下面的命令，over透明代理，通过x.x.x.x这个http代理服务器访问https://yy.com
```bash
curl -x http://x.x.x.x:8080 https://yy.com
```
http payload是
```
CONNECT yy.com:443 HTTP/1.1
Host: yy.com:443
```

正常情况下：
xray所在的代理服务器应该是把tcp请求转发到x.x.x.x的8080端口，并转发http payload，

实际情况：
抓包发现，xray所在的服务器，这个tcp直接被转发到了 z.z.z.z:8080（z.z.z.z是yy.com域名解析的结果），服务器日志则是看着向 z.z.z.z:8080发起了http(s)请求。

### 重现方式

随便找一个透明代理下的主机都可以复现，我测试了手里很多台不同版本xray-core透明代理下的机器。尝试过关闭客户端的嗅探，也是一样的结果。

**Comment by Fangliding** [comment]
老生常谈的问题 这是http代理自己的锅 发出的htttp请求host就是 yy.com 这是完全合乎http语义的 被xray嗅探到然后重置到yy.com了 要不用socks5要不就把嗅探关了

**Comment by Fangliding** [comment]
服务端有嗅探 客户端有嗅探 哪边有覆盖都会导致这种问题 具体发生在哪你得检查日志 issue只处理行为不符合预期的bug

**Comment by cod1ingcoding** [comment]
服务器、客户端都关闭嗅探还是不行，还是会定位到http协议里的Host目标+http代理服务器的端口。

**Comment by cod1ingcoding** [comment]
> 服务端有嗅探 客户端有嗅探 哪边有覆盖都会导致这种问题 具体发生在哪你得检查日志 issue只处理行为不符合预期的bug

服务器、客户端都关闭嗅探还是不行，还是会定位到http协议里的Host目标+http代理服务器的端口。

**Comment by Fangliding** [comment]
我不会算命 你一张嘴说有问题我也没办法不是 如果你觉得这是bug 我模板里要求的四个空是一个没有的
