### ISSUE TITLE
WireGuard无法连接到Tor

### ISSUE THREAD

**Issue by HappyLeslieAlexander** [XTLS/Xray-core#3992]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [ ] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

使用Xray搭建了一个VLESS和一个WireGuard VPN，配置了两个路由规则：1. WARP（默认出站） 2. Direct

然后通过路由规则将WireGuard路由到Direct，VLESS不做设置，此时VLESS正常工作，从WARP出站；WireGuard直接访问网站也正常direct出站，但是无法连接到Tor

尝试更改：
删除WARP出站，只保留Direct到默认出站
然后WireGuard能连接到Tor了

不知道是什么奇奇怪怪的Bug

### 重现方式

如上描述

### 客户端配置

官方的的WireGuard客户端导入配置

### 服务端配置

N/A

### 客户端日志

N/A

### 服务端日志

N/A

**Comment by Fangliding** [comment]
一没配置二没日志 模板耳边风
