### ISSUE TITLE
[feature request] request docker distribution support

### ISSUE THREAD

**Issue by nJhEqnvK** [XTLS/Xray-core#4]
Add distribution for hub.docker.com plz.

**Comment by rprx** [comment]
别急，等秋水大佬

**Comment by nJhEqnvK** [comment]
> 别急，等秋水大佬

哈哈，等着有镜像后直接替换

**Comment by rprx** [comment]
https://hub.docker.com/r/teddysun/xray

已补充 README.md，正在补充 v1.0.0 的 Release Note
