### ISSUE TITLE
令我迷惑的证书不可用？

### ISSUE THREAD

**Issue by Fhokud** [XTLS/Xray-core#40]
aapanel签发的证书（.pem），
证书直接挪到Xray_v1.1.1后v2rayng_v1.5.1使用vless_xtls/tls无法连接
但设置不验证证书以后可以连接（迷惑）
浏览器可正常https访问

**Comment by SekiBetu** [comment]
万能的777权限给了吗

**Comment by Fhokud** [comment]
那必须的啊，但没用

**Comment by SekiBetu** [comment]
> 那必须的啊，但没用

那不清楚了，可以服务端日志调成debug等级 复制粘贴上来让大佬看吧

**Comment by JimhHan** [comment]
请检查是否使用fullchain证书，正常的格式如下：
```
-----BEGIN CERTIFICATE-----
... ...
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
... ...
-----END CERTIFICATE-----
```

**Comment by cuihao777** [comment]
> aapanel签发的证书（.pem），
> 证书直接挪到Xray_v1.1.1后v2rayng_v1.5.1使用vless_xtls/tls无法连接
> 但设置不验证证书以后可以连接（迷惑）
> 浏览器可正常https访问

你需要fullchain证书，估计你的安卓系统缺乏中间证书。

**Comment by rprx** [comment]
目测换 fullchain 即正常，[Xray-examples](https://github.com/XTLS/Xray-examples) 有注明。
