### ISSUE TITLE
输出 [Info] transport/internet/tcp: REALITY: processed invalid connection 日志从 warning 级别。

### ISSUE THREAD

**Issue by zw963** [XTLS/Xray-core#4001]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

这个问题无需提供日志。

是这样的，最近服务器突然连不上了，默认我的服务端配置（大多数人应该和我一样）都是输出 warning 级别日志到文件，但是查看日志后，看不到任何信息，直到我改为 info, 才看到 reality 指定的域名出问题了。

我觉得是否考虑将下面的日志

```
[Info] transport/internet/tcp: REALITY: processed invalid connection
```

作为 warning 级别来输出呢？

### 重现方式

无需

### 客户端配置

无需

### 服务端配置

无需

### 客户端日志

无需

### 服务端日志

无需

**Comment by Fangliding** [comment]
@RPRX 加一行 reality verify failed 还是说算了

**Comment by RPRX** [comment]
> @RPRX 加一行 reality verify failed 还是说算了

服务端的不改，客户端的可以改成 AtWarning，我看了下代码，输出日志时会遍历 inner severity，就能取到 warning
