### ISSUE TITLE
fakedns有些时好象会导到错误的IP

### ISSUE THREAD

**Issue by kousyougi** [XTLS/Xray-core#401]
我用Chrome连facebook，有时后会有些影片显示无法载入。(dokodemo的tproxy)
但用 无fakedns的socks检查却正常。

开开发者模式检查，看到
读取失败的路径是 https://video.ftpe8-3.fna.fbcdn.net/*******************
错误信息是 证书错误。无法读取。
再检查证书，证书的内容是
DNS Name=*.ftpe8-2.fna.fbcdn.net
DNS Name=ftpe8-2.fna.fbcdn.net

nslookup video.ftpe8-3.fna.fbcdn.net 得到 198.18.56.200
再开https://198.18.56.200 检查证书还是
DNS Name=*.ftpe8-2.fna.fbcdn.net
DNS Name=ftpe8-2.fna.fbcdn.net
看起来 video.ftpe8-3.fna.fbcdn.net 好像跑到别的IP去了。

我VPS那边的DNS应该是没有乱掉。
在VPS端 检查 nslookup video.ftpe8-3.fna.fbcdn.net 得到 203.74.69.146
DNS Name=*.ftpe8-3.fna.fbcdn.net
DNS Name=ftpe8-3.fna.fbcdn.net
可以得到正常的IP跟正常的证书。

我查xray的dns ttl 是600秒、十分钟。
想说会不会是我浏览器缓存的DNS还没更新。
但这个错误持续超过十分钟，维持了很久。

fakedns的ip pool设定是 65535 ，
开机到现在，只有我一个人用，没有上太多网站，DNS记录应该不到1000个。

最后把客户端的xray重新启动一遍就正常了。

有人也遇到一样的状况吗？

**Comment by rurirei** [comment]
say your configuration and logs.

**Comment by AkinoKaede** [comment]
请提供日志和配置

**Comment by kousyougi** [comment]
我现在把log打开，等同样的状况重现。

**Comment by JimhHan** [comment]
@AkinoKaede 说实话这个有点神奇

**Comment by kousyougi** [comment]
观察了几天，发现是接了smartdns才会有这个奇怪的现象。把smartdns换成dnsmasq之后就正常了。
