### ISSUE TITLE
作为内网DNS服务器时如果服务器有多个IP，UDP协议只有一个IP（IPv6）能正常使用

### ISSUE THREAD

**Issue by klxyy** [XTLS/Xray-core#4016]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

服务器有多个IP（IPv6）时，xray使用dokodemo-door协议做为内网DNS服务器只有一个IP（IPv6）可通过UDP协议访问，其它IP（IPv6）地址不能正确返回结果。只有UDP协议有问题，TCP协议使用正常。
需要设置iptables才能正常使用，iptables命令：
ip6tables -t nat -A PREROUTING -p udp --dst fe80::12 -j DNAT --to-destination fe80::11
查看之前的issues有人提到过，但是似乎没有解决？

### 重现方式

配置多个内网IP（IPv6），百分之百复现。

### 客户端配置

无

### 服务端配置

"tag": "dns-in",
"listen": "0.0.0.0",
"port": 53,
"protocol": "dokodemo-door",
"settings": {
	"address": "10.10.10.1",
	"port": 53,
	"network": "tcp,udp",
	"followRedirect": false
}

### 客户端日志

无

### 服务端日志

无

**Comment by Fangliding** [comment]
![image](https://github.com/user-attachments/assets/d43b9e57-025b-4120-a445-f8178767af3a)
