### ISSUE TITLE
请问这个是什么问题？所有节点都延时，我把日志发上来，帮忙看下，实在弄不好了。

### ISSUE THREAD

**Issue by slayercjc** [XTLS/Xray-core#402]
Xray 1.4.0 (Xray, Penetrates Everything.) Custom (go1.16.2 linux/amd64)
A unified platform for anti-censorship.
2021/03/19 08:43:14 [Info] infra/conf/serial: Reading config: /var/etc/passwall/TCP.json
2021/03/19 08:43:14 [Warning] core: Xray 1.4.0 started
2021/03/19 08:43:20 192.168.50.195:3619 accepted tcp:172.217.24.202:443 [da7aae2f2e1d4e8e8727942b2c26abbe]
2021/03/19 08:43:37 192.168.50.195:3620 accepted tcp:172.217.24.202:443 [da7aae2f2e1d4e8e8727942b2c26abbe]
2021/03/19 08:43:41 192.168.50.195:3621 accepted tcp:172.217.24.202:443 [da7aae2f2e1d4e8e8727942b2c26abbe]
2021/03/19 08:43:53 [Warning] [4149847411] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: i/o timeout dial tcp: operation was canceled] > common/retry: all retry attempts failed
2021/03/19 08:44:07 192.168.50.88:56997 accepted tcp:172.64.130.33:443 [da7aae2f2e1d4e8e8727942b2c26abbe]
2021/03/19 08:44:10 192.168.50.88:58944 accepted tcp:172.64.131.33:443 [da7aae2f2e1d4e8e8727942b2c26abbe]
2021/03/19 08:44:10 [Warning] [3472950755] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: lookup xray.slayercjc.tk on [::1]:53: dial udp [::1]:53: operation was canceled dial tcp: i/o timeout dial tcp: operation was canceled] > common/retry: all retry attempts failed
2021/03/19 08:44:11 192.168.50.195:3623 accepted tcp:172.217.24.202:443 [da7aae2f2e1d4e8e8727942b2c26abbe]
2021/03/19 08:44:13 192.168.50.88:43720 accepted tcp:172.64.131.33:443 [da7aae2f2e1d4e8e8727942b2c26abbe]
2021/03/19 08:44:13 192.168.50.195:3624 accepted tcp:172.217.31.238:443 [da7aae2f2e1d4e8e8727942b2c26abbe]
2021/03/19 08:44:13 [Warning] [3462325506] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: i/o timeout dial tcp: lookup xray.slayercjc.tk on [::1]:53: read udp [::1]:56512->[::1]:53: i/o timeout dial tcp: operation was canceled] > common/retry: all retry attempts failed
2021/03/19 08:44:15 192.168.50.195:3625 accepted tcp:204.79.197.219:443 [da7aae2f2e1d4e8e8727942b2c26abbe]
2021/03/19 08:44:16 [Warning] [2932045946] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: operation was canceled] > common/retry: all retry attempts failed
2021/03/19 08:44:16 192.168.50.88:40260 accepted tcp:172.64.130.33:443 [da7aae2f2e1d4e8e8727942b2c26abbe]
2021/03/19 08:44:17 192.168.50.195:3627 accepted tcp:204.79.197.200:443 [da7aae2f2e1d4e8e8727942b2c26abbe]
2021/03/19 08:44:19 [Warning] [2768545344] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: operation was canceled] > common/retry: all retry attempts failed
2021/03/19 08:44:21 192.168.50.195:3628 accepted tcp:216.58.199.3:443 [da7aae2f2e1d4e8e8727942b2c26abbe]
2021/03/19 08:44:22 [Warning] [1039383743] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: operation was canceled] > common/retry: all retry attempts failed
2021/03/19 08:44:22 192.168.50.195:3629 accepted tcp:204.79.197.200:443 [da7aae2f2e1d4e8e8727942b2c26abbe]
2021/03/19 08:44:25 [Warning] [879015654] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: operation was canceled] > common/retry: all retry attempts failed
2021/03/19 08:44:31 [Warning] [1593288481] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: operation was canceled] > common/retry: all retry attempts failed
2021/03/19 08:44:31 [Warning] [3048073034] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: operation was canceled] > common/retry: all retry attempts failed
2021/03/19 08:44:31 192.168.50.195:3632 accepted tcp:172.217.24.202:443 [da7aae2f2e1d4e8e8727942b2c26abbe]
2021/03/19 08:44:31 192.168.50.195:3634 accepted tcp:172.217.24.202:443 [da7aae2f2e1d4e8e8727942b2c26abbe]
2021/03/19 08:44:31 192.168.50.195:3633 accepted tcp:172.217.24.202:443 [da7aae2f2e1d4e8e8727942b2c26abbe]
2021/03/19 08:44:31 192.168.50.195:3635 accepted tcp:172.217.24.202:443 [da7aae2f2e1d4e8e8727942b2c26abbe]
2021/03/19 08:44:31 192.168.50.195:3636 accepted tcp:172.217.24.202:443 [da7aae2f2e1d4e8e8727942b2c26abbe]
2021/03/19 08:44:39 192.168.50.88:34900 accepted tcp:172.64.131.33:443 [da7aae2f2e1d4e8e8727942b2c26abbe]
2021/03/19 08:44:41 192.168.50.195:3639 accepted tcp:172.217.24.202:443 [da7aae2f2e1d4e8e8727942b2c26abbe]
2021/03/19 08:44:42 192.168.50.195:3640 accepted tcp:172.217.163.228:443 [da7aae2f2e1d4e8e8727942b2c26abbe]
2021/03/19 08:44:44 [Warning] [777901916] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: lookup xray.slayercjc.tk on [::1]:53: dial udp [::1]:53: operation was canceled dial tcp: i/o timeout dial tcp: operation was canceled] > common/retry: all retry attempts failed
2021/03/19 08:44:45 192.168.50.88:40276 accepted tcp:172.64.130.33:443 [da7aae2f2e1d4e8e8727942b2c26abbe]
2021/03/19 08:44:46 [Warning] [2880113385] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: i/o timeout dial tcp: operation was canceled] > common/retry: all retry attempts failed
2021/03/19 08:44:48 [Warning] [1750885689] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: operation was canceled] > common/retry: all retry attempts failed
2021/03/19 08:44:48 [Warning] [2782727484] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: i/o timeout dial tcp: operation was canceled] > common/retry: all retry attempts failed

**Comment by JimhHan** [comment]
>  dial udp [::1]:53

老朋友了，建议设置 [sockopt](https://xtls.github.io/Xray-docs-next/config/transport.html#sockoptobject) 中的 `domainStrategy` 为 `UseIP`，并设置 [内置 dns 服务器](https://xtls.github.io/Xray-docs-next/config/dns.html)。

**Comment by slayercjc** [comment]
> > 拨打udp [:: 1]：53
> 
> 老朋友了，建议设置[sockopt](https://xtls.github.io/Xray-docs-next/config/transport.html#sockoptobject)中的`domainStrategy`为`UseIP`，并设置[内置dns服务器](https://xtls.github.io/Xray-docs-next/config/dns.html)。

请问怎么设置呢？我是新手，不太懂，能教一下吗？

**Comment by JimhHan** [comment]
建议使用 v2rayng

**Comment by slayercjc** [comment]
> 如果您使用安卓，建议使用v2rayng。

我使用的是OPENWRT里面的PASSWALL，更新了xray1.4内核

**Comment by JimhHan** [comment]
是否使用了 xray DoH ？

**Comment by slayercjc** [comment]
> 是否使用了xray DoH？

没有，我用的是PDNSD通过TCP节点请求DNS

**Comment by slayercjc** [comment]
同样的节点，用SSRP就可以，用PASSWALL就不行，你说的设置，是设置PASSWALL吗？在哪设置呢

**Comment by slayercjc** [comment]
同样的节点，用SSRP就可以，用PASSWALL就不行，你说的设置，是设置PASSWALL吗？在哪设置呢

**Comment by JimhHan** [comment]
@slayercjc 更新到 1.4 后出现此问题？

**Comment by slayercjc** [comment]
> @slayercjc更新到xray 1.4后出现此问题？

是的

**Comment by slayercjc** [comment]
> > @slayercjc更新到xray 1.4后出现此问题？
> 
> 是的

方便价格VX吗，VX：24165159
我在TG群里也问了，有几个人和我一样的问题。。。。。

**Comment by JimhHan** [comment]
请向 passwall 反馈
