### ISSUE TITLE
[Enchancement] Add functionality for masking UDP traffic to fake TCP

### ISSUE THREAD

**Issue by 0xffabc** [XTLS/Xray-core#4034]
### Discussed in https://github.com/XTLS/Xray-core/discussions/3924

<div type='discussions-op-text'>
        The issue is that, some ISPs tend to block UDP for reasons such as reducing vpn usage, blocking web calls, etc, however, there are plenty of people who still want to use UDP instead of TCP due to it's speed. 
 
The solution is adding a feature for masking UDP packets to look like TCP ones as it is written in discussions

<hr>
<sup>Originally posted by **iopq** October 17, 2024</sup>
Hysteria 1 had FakeTCP which prevented UDP blocks. No current software has support for this, so my UDP connections get dropped after after an hour. Could this be implemented in xray?</div>

**Comment by 0xffabc** [comment]
@iopq

> The design is as follows:

> The packets to the server will look like syn/ack and so forth to establish it, and it will appear like a TCP connection over SSL - exactly like connecting to a normal website. But actually it's transmitting UDP packets out of order as the payload.

> All of the middleboxes will see it as TCP connections to some website while you're playing some p2p game over UDP or having some kind of a call

**Comment by Fangliding** [comment]
hy2都丢掉fake tcp了 一方面有开销 一方面只有Linux没有Windows还必须要root

**Comment by iopq** [comment]
That's a limitation of hysteria, udp2raw has a windows and mac version

https://github.com/wangyu-/udp2raw-multiplatform/issues/56

iOS may be possible as a VPN service

**Comment by 0xffabc** [comment]
Go has native raw sockets supports afaik
For frontend applications, you can manipulate over raw sockets via TUN on android, for linux we have libsockets, and for windows, windivert for sure
It's not a huge problem that these drivers require root/admin access
Implementing this is possible on almost every platform and partially on iOS.

**Comment by Fangliding** [comment]
pr is always welcome
