### ISSUE TITLE
homebrew 仓库中的服务功能

### ISSUE THREAD

**Issue by TinyFlag** [XTLS/Xray-core#404]
在@N4FA 的homebrew仓库中服务配置的plist中的运行路径是是xray的真实文件路径,但路径下没有dat文件,假如配置了xray分流并用到了dat文件,服务会无法启动.

**Comment by JimhHan** [comment]
@TinyFlag 感谢反馈。我认为应该反馈到 @N4FA  的仓库。

**Comment by AkinoKaede** [comment]
目前 Xray-core 已进入 Homebrew 官方仓库
