### ISSUE TITLE
[Feature Request] Raw HTTP Headers

### ISSUE THREAD

**Issue by fodhelper** [XTLS/Xray-core#4040]
Xray already have Fragment and Noise GFW bypass methods that can bypass Russia and Iran GFW
But there is more tricks like the ones in the popular tool [byedpi](https://github.com/hufrea/byedpi) and others for non tls HTTP connections
and some closed source vpn apps also uses a combination of duplicate host header and space/null characters that worked on cf

If you add a option to set Raw HTTP Request Headers for HTTP based transports, it can include all possible http header tricks

```POST /path HTTP/1.1\r\nHost: example.com\r\nUpgrade: websocket\r\n```
just pure user input for http header and no default header or value

If it's structure be like Noise so payloads can be base64 then users will be able to use non-ASCII characters
and maybe even send each Host value in a different tcp packet with a delay/null-bytes between characters to fool GFW

**Comment by Fangliding** [comment]
基于http的传输都可以修改请求头。至于乱改http头部数据，大概不会有那么无聊的功能

**Comment by wanliyunyan** [comment]
@Fangliding 大佬，我有一个修改请求头的需求，我这客户端出站
``` 
{
			"tag": "proxy",
			"protocol": "vless",
			"settings": {
				"vnext": [{
					"address": "address",
					"port": port,
					"users": [{
						"id": "id",
						"alterId": 0,
						"email": "t@t.tt",
						"security": "auto",
						"encryption": "none"
					}]
				}]
			},
			"streamSettings": {
				"network": "httpupgrade",
				"httpupgradeSettings": {
					"path": "/",
					"headers": {
						"X-Real-IP": "1.2.3.4"
					}
				}
			},
			"mux": {
				"enabled": false,
				"concurrency": -1
			}
		}
``` 
这个X-Real-IP根本带不到目标服务器，是哪配置不对吗？
