### ISSUE TITLE
请求 `h3KeepalivePeriod` 增加（开放）到 `xhttpSettings`

### ISSUE THREAD

**Issue by xqzr** [XTLS/Xray-core#4053]
https://github.com/XTLS/Xray-core/blob/513f18bf531ef5f92464c2affefed0db4f28280b/transport/internet/splithttp/dialer.go#L145
https://t.me/projectXray/4028205?thread=4028205

**Comment by RPRX** [comment]
@Fangliding 我看到你开了个 branch，啥时候 PR

**Comment by xqzr** [comment]
> @Fangliding 我看到你开了个 branch，啥时候 PR

https://t.me/projectXray/4088721?thread=4086152

**Comment by Fangliding** [comment]
需要的话随时都能合 没啥问题

**Comment by RPRX** [comment]
开个 PR 吧，我可能要改改

**Comment by RPRX** [comment]
话说我之前好像在 github 上问过 @mmmray，他说这个 KeepAlivePeriod 是针对整一个大连接，但现在看起来像是针对子连接的？还是说 quic-go 的定义和标准库 http 不同？你看下 h2+packet-up 会不会这样

**Comment by xqzr** [comment]
> 你看下 h2+packet-up 会不会这样

会
h2 ping 间隔 45 秒
https://github.com/XTLS/Xray-core/blob/f7bd98b13c739303a46a6d15d8e0d482123384df/transport/internet/splithttp/dialer.go#L38
https://t.me/projectXray/4080103?thread=4079750

**Comment by RPRX** [comment]
H2 的描述：

>	// ReadIdleTimeout is the timeout after which a health check using ping
	// frame will be carried out if no frame is received on the connection.
	// Note that a ping response will is considered a received frame, so if
	// there is no other traffic on the connection, the health check will
	// be performed every ReadIdleTimeout interval.
	// If zero, no health check is performed.
	ReadIdleTimeout time.Duration

H3 的描述：

>	// KeepAlivePeriod defines whether this peer will periodically send a packet to keep the connection alive.
	// If set to 0, then no keep alive is sent. Otherwise, the keep alive is sent on that period (or at most
	// every half of MaxIdleTimeout, whichever is smaller).
	KeepAlivePeriod time.Duration

如果也像 H2 一样是 if no frame is received on the connection 才发保活包，那么在 TLS 上看到不断有数据进来，不发保活包也合理

**Comment by RPRX** [comment]
~~看错了，之前简单看了下，把分钟看成了秒，我重来~~

看起来这个 KeepAlivePeriod 的确是针对整一个大连接的，无数据时才保活，但有时会同时有多个大连接存在，比如你发的那个 h2

**Comment by RPRX** [comment]
然后我又想到了 XTLS：
- 如果不用 XTLS，浏览器 h2 发这种包，像 Trojan 多裹一层的长度就很固定、很刺眼，可以被精准识别
- 如果用 XTLS，指纹伪装选 Chrome，浏览器最好也是用 Chrome，不然 KeepAlivePeriod 可能不同，此前有提过
- 如果用 XHTTP，也是多裹一层，不过有多路复用，还有它自己也会发这种包，可以迷惑 GFW

~~看来 Switch 还是很有必要的~~
