### ISSUE TITLE
Memory leak with high user load

### ISSUE THREAD

**Issue by norollback1337** [XTLS/Xray-core#4054]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

Hello everyone! I'm experiencing a memory leak issue with a large number of active users. When the problem occurs, there's a sharp increase in memory consumption which then drops back to normal levels after about 2 minutes. However, after each spike, the baseline memory usage incrementally increases, indicating a potential memory leak.

I'm using the latest version of 3x-ui, and I've also tried rolling back to several previous versions, but this didn't resolve the issue. I monitored the traffic on xray's API interface during the problem occurrence, and there were no suspicious requests from 3x-ui to xray during these spikes.

Using pprof for memory analysis during these spikes revealed potential issues, but I'm not sure how to address them in the code. Also, there are no log records (function calls or similar) while the problem occurs.

System details:
- Average number of active users: 2-3k
- Protocol: exclusively vless
- mux and warp are disabled in the panel
- Server resources: 128 cores, 64GB RAM
- Network traffic bandwidth is 5Gb/s

Has anyone encountered similar issues or can suggest possible solutions? I can share pprof analysis results if needed.
![image](https://github.com/user-attachments/assets/cac58671-3273-489c-a79b-357f74716c3d)
![heap](https://github.com/user-attachments/assets/8b9a4c35-7c7a-42d7-8bb9-324807283737)

### Reproduction Method

-

### Client config

<details><pre><code>
Applications that supports vless protocol
</code></pre></details>

### Server config

<details><pre><code>
{
  "log": {
    "access": "./access.log",
    "dnsLog": true,
    "error": "./error.log",
    "loglevel": "debug"
  },
  "api": {
    "tag": "api",
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ]
  },
  "inbounds": [
    {
      "tag": "api",
      "listen": "0.0.0.0",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "0.0.0.0"
      }
    }
  ],
  "outbounds": [
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP"
      }
    },
    {
      "tag": "blocked",
      "protocol": "blackhole",
      "settings": {}
    },
    {
      "tag": "<REDACTED>",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "<REDACTED>",
            "port": 443,
            "users": [
              {
                "id": "<REDACTED>",
                "flow": "xtls-rprx-vision",
                "encryption": "none"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "publicKey": "<REDACTED>",
          "fingerprint": "chrome",
          "serverName": "google.com",
          "shortId": "<REDACTED>",
          "spiderX": "/"
        },
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        }
      }
    },
    {
      "tag": "<REDACTED>",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "<REDACTED>",
            "port": 443,
            "users": [
              {
                "id": "<REDACTED>",
                "flow": "xtls-rprx-vision",
                "encryption": "none"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "publicKey": "<REDACTED>",
          "fingerprint": "chrome",
          "serverName": "google.com",
          "shortId": "<REDACTED>",
          "spiderX": "/"
        },
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        }
      }
    },
    {
      "tag": "<REDACTED>",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "<REDACTED>",
            "port": 443,
            "users": [
              {
                "id": "<REDACTED>",
                "flow": "xtls-rprx-vision",
                "encryption": "none"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "publicKey": "<REDACTED>",
          "fingerprint": "chrome",
          "serverName": "google.com",
          "shortId": "<REDACTED>",
          "spiderX": "/"
        },
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        }
      }
    },
    {
      "tag": "<REDACTED>",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "<REDACTED>",
            "port": 443,
            "users": [
              {
                "id": "<REDACTED>",
                "flow": "xtls-rprx-vision",
                "encryption": "none"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "publicKey": "<REDACTED>",
          "fingerprint": "chrome",
          "serverName": "google.com",
          "shortId": "<REDACTED>",
          "spiderX": "/"
        },
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        }
      }
    },
    {
      "tag": "<REDACTED>",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "<REDACTED>",
            "port": 443,
            "users": [
              {
                "id": "<REDACTED>",
                "flow": "xtls-rprx-vision",
                "encryption": "none"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "publicKey": "<REDACTED>",
          "fingerprint": "chrome",
          "serverName": "google.com",
          "shortId": "<REDACTED>",
          "spiderX": "/"
        },
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        }
      }
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "statsUserDownlink": true,
        "statsUserUplink": true
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true,
      "statsOutboundDownlink": true,
      "statsOutboundUplink": true
    }
  },
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api"
      },
      {
        "type": "field",
        "outboundTag": "blocked",
        "ip": [
          "geoip:private"
        ]
      },
      {
        "type": "field",
        "network": "TCP,UDP",
        "inboundTag": [
          "inbound-443"
        ],
        "protocol": [
          "bittorrent"
        ],
        "outboundTag": "blocked"
      },
      {
        "type": "field",
        "port": "6881,6882,6883,6884,6885,6886,6887,6888,6889,6969,1337",
        "network": "TCP,UDP",
        "inboundTag": [
          "inbound-443"
        ],
        "outboundTag": "blocked"
      },
      {
        "type": "field",
        "domainMatcher": "hybrid",
        "domain": [
          ... some-domains ...
        ],
        "network": "TCP,UDP",
        "inboundTag": [
          "inbound-443"
        ],
        "protocol": [
          "http",
          "tls",
          "bittorrent"
        ],
        "outboundTag": "blocked"
      },
      {
        "type": "field",
        "domain": [
          "geosite:category-ads-all",
          "ext:geosite_IR.dat:category-ads-all"
        ],
        "outboundTag": "blocked"
      },
      {
        "type": "field",
        "domainMatcher": "hybrid",
        "domain": [
          ... some-domains ...
        ],
        "network": "TCP,UDP",
        "inboundTag": [
          "inbound-443"
        ],
        "protocol": [
          "tls",
          "http"
        ],
        "balancerTag": "<REDACTED>"
      },
      {
        "type": "field",
        "domainMatcher": "hybrid",
        "inboundTag": [
          "inbound-443"
        ],
        "balancerTag": "<REDACTED>"
      },
      {
        "type": "field",
        "domainMatcher": "hybrid",
        "network": "tcp",
        "inboundTag": [
          "inbound-444"
        ],
        "protocol": [
          "http",
          "tls"
        ],
        "balancerTag": "<REDACTED>"
      },
      {
        "type": "field",
        "domainMatcher": "hybrid",
        "domain": [
          ... some-domains ...
        ],
        "network": "TCP,UDP",
        "inboundTag": [
          "inbound-8443"
        ],
        "protocol": [
          "http",
          "tls"
        ],
        "balancerTag": "<REDACTED>"
      },
      {
        "type": "field",
        "domainMatcher": "hybrid",
        "network": "TCP,UDP",
        "inboundTag": [
          "inbound-8443"
        ],
        "protocol": [
          "http",
          "tls"
        ],
        "outboundTag": "direct"
      }
    ],
    "balancers": [
      {
        "tag": "<REDACTED>",
        "selector": [
          "<REDACTED>",
          "<REDACTED>",
          "<REDACTED>"
        ],
        "fallbackTag": "direct",
        "strategy": {
          "type": "roundRobin"
        }
      },
      {
        "tag": "<REDACTED>",
        "selector": [
          "<REDACTED>"
        ],
        "fallbackTag": "direct"
      },
      {
        "tag": "<REDACTED>",
        "selector": [
          "<REDACTED>",
          "<REDACTED>"
        ],
        "fallbackTag": "direct",
        "strategy": {
          "type": "roundRobin"
        }
      }
    ]
  },
  "stats": {}
}
</code></pre></details>

Sample client inbound configuration (in 3x-ui located outside of main server config):
<details><pre><code>
          {
            "email": "<REDACTED>",
            "flow": "xtls-rprx-vision",
            "id": "<REDACTED>"
          },
          {
            "email": "<REDACTED>",
            "flow": "xtls-rprx-vision",
            "id": "<REDACTED>"
          },
          {
            "email": "<REDACTED>",
            "flow": "xtls-rprx-vision",
            "id": "<REDACTED>"
          },
          {
            "email": "<REDACTED>",
            "flow": "xtls-rprx-vision",
            "id": "<REDACTED>"
          },
</code></pre></details>

### Client log

<details><pre><code>
-
</code></pre></details>

### Server log

<details><pre><code>
-
</code></pre></details>

**Comment by mastak6** [comment]
i have this problem !!

**Comment by mastak6** [comment]
please help

**Comment by Fangliding** [comment]
pprof profiles?

**Comment by norollback1337** [comment]
@Fangliding 
Here is the pprof profile analysis screenshot, and below is the pprof heap screenshot.
![profile](https://github.com/user-attachments/assets/5342a2ef-a10a-49fa-bd97-1563c163b250)

**Comment by Fangliding** [comment]
I suggest disabling the balancer as it seems to have little problem

**Comment by RPRX** [comment]
~~起夜级~~

**Comment by yuhan6665** [comment]
@norollback1337 I think I fixed the problem.
#4095
It should fix memory leak at balancers, observatory and fakedns. Need some testing to confirm it is working as expected.
https://github.com/XTLS/Xray-core/actions/runs/12108714019
