### ISSUE TITLE
i/o timeout & io: read/write on closed pipe

### ISSUE THREAD

**Issue by Pauluooooo** [XTLS/Xray-core#4055]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

使用 Reality 节点，断流，一会好一会坏，查看日志会有 i/o timeout 的提示，但是在移动网络下正常，是运营商阻断了吗?

### 重现方式

使用节点，直接访问 Google

### 客户端配置

Clash verge 只列出节点部分
<details><pre><code>
proxies: 
   
  - name: "XXXX"
    type: vless
    server: XXXXX
    port: 10590
    uuid: XXXXXX
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: hkust.edu.hk
    reality-opts:
      public-key: XXXXX
    client-fingerprint: chrome 
</code></pre></details>

### 服务端配置

Xray-Core 
<details><pre><code>
{
    "log": {
        "access": "/var/log/xray/access.log",
        "error": "/var/log/xray/error.log",
        "loglevel": "debug",
        "dnsLog": true
    },
    "inbounds": [
        {
            "listen": "0.0.0.0",
            "port": 10590, 
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "XXXXXXX",
                        "flow": "xtls-rprx-vision"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "tcp",
                "security": "reality",
                "realitySettings": {
                    "dest": "hkust.edu.hk:443",
                    "serverNames": [
                        "hkust.edu.hk"
                    ],
                    "privateKey": "XXXXXXX",
                    "shortIds": [
                        ""
                    ]
                }
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls",
                    "quic"
                ],
                "routeOnly": true
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "tag": "direct"
        }
    ]
}
</code></pre></details>

### 客户端日志

<details><pre><code>
time="2024-11-24T12:07:16.5643924+08:00" level=debug msg="Auth success from 127.0.0.1:14947 -> "
time="2024-11-24T12:07:16.5643924+08:00" level=debug msg="[Rule] use default rules"
time="2024-11-24T12:07:21.5649662+08:00" level=warning msg="[TCP] dial Proxy (match RuleSet/proxy) 127.0.0.1:14947(chrome.exe) --> mtalk.google.com:443 error: XXXXXX:10590 connect error: connect failed: dial tcp XXXXX:10590: i/o timeout"
time="2024-11-24T12:07:21.5649662+08:00" level=debug msg="Auth success from 127.0.0.1:14949 -> "
time="2024-11-24T12:07:21.5649662+08:00" level=debug msg="[Rule] use default rules"
time="2024-11-24T12:07:21.5795041+08:00" level=debug msg="use specified fingerprint:Chrome"
time="2024-11-24T12:07:21.6032885+08:00" level=debug msg="REALITY Authentication: true, AEAD: *aes.gcmAsm"
time="2024-11-24T12:07:21.6038086+08:00" level=debug msg="XTLS Vision write padding2: command=0, payloadLen=1763, paddingLen=0"
time="2024-11-24T12:07:21.6038086+08:00" level=info msg="[TCP] 127.0.0.1:14949(chrome.exe) --> mtalk.google.com:443 match RuleSet(proxy) using Proxy[Claw-HK]"
time="2024-11-24T12:07:21.6479382+08:00" level=debug msg="XTLS Vision read padding: command=0, payloadLen=5600, paddingLen=177"
time="2024-11-24T12:07:21.6479382+08:00" level=debug msg="XTLS Vision found TLS 1.2, packetLength=5600"
time="2024-11-24T12:07:21.6487239+08:00" level=debug msg="XTLS Vision read padding: command=0, payloadLen=2063, paddingLen=140"
time="2024-11-24T12:07:21.6487239+08:00" level=debug msg="XTLS Vision write padding2: command=1, payloadLen=64, paddingLen=907"
time="2024-11-24T12:07:21.6760239+08:00" level=debug msg="XTLS Vision read padding: command=2, payloadLen=537, paddingLen=469"
time="2024-11-24T12:07:21.6761867+08:00" level=debug msg="XTLS Vision direct read start"
</code></pre></details>

### 服务端日志

error 日志
<details><pre><code>
2024/11/24 12:07:19 [Info] [4017663300] proxy: XtlsFilterTls found tls client hello! 1108
2024/11/24 12:07:19 [Info] [4017663300] app/dispatcher: sniffed domain: mtalk.google.com
2024/11/24 12:07:19 [Info] [4017663300] app/dispatcher: default route for tcp:mtalk.google.com:443
2024/11/24 12:07:19 [Info] [4017663300] transport/internet/tcp: dialing TCP to tcp:mtalk.google.com:443
2024/11/24 12:07:19 [Debug] [4017663300] transport/internet: dialing to tcp:mtalk.google.com:443
2024/11/24 12:07:19 [Info] [4017663300] proxy/freedom: connection opened to tcp:mtalk.google.com:443, local endpoint 10.3.14.212:54932, remote endpoint 64.233.188.188:443
2024/11/24 12:07:19 [Info] [4017663300] proxy: XtlsFilterTls found tls 1.3! 5600 TLS_AES_128_GCM_SHA256
2024/11/24 12:07:19 [Info] [4017663300] proxy: XtlsPadding 5600 177 0
2024/11/24 12:07:19 [Info] [4017663300] proxy: XtlsPadding 2063 140 0
2024/11/24 12:07:19 [Info] [4017663300] proxy: Xtls Unpadding new block, content 64 padding 907 command 1
2024/11/24 12:07:19 [Info] [4017663300] proxy: XtlsPadding 537 469 2
2024/11/24 12:07:19 [Info] [4017663300] proxy: CopyRawConn splice
2024/11/24 12:07:21 [Info] [892117808] app/proxyman/outbound: app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: connection ends > readfrom tcp 10.3.14.212:10590->14.155.189.37:28824: splice: connection reset by peer
2024/11/24 12:07:21 [Info] [892117808] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to transfer response payload > io: read/write on closed pipe
2024/11/24 12:07:22 [Info] [1824536619] app/proxyman/inbound: connection ends > shadowsocks: serve TCP from 14.155.189.82:28418: upload: write tcp 10.3.14.212:6600->14.155.189.82:28418: write: connection timed out
</code></pre></details>

access log
<details><pre><code>
2024/11/24 12:07:19 from 14.155.232.86:28887 accepted tcp:mtalk.google.com:443 [direct]
</code></pre></details>

**Comment by Fangliding** [comment]
线路不好连接断了

**Comment by Pauluooooo** [comment]
> 线路不好连接断了

阿里的线路，其他服务器都没问题，就它断，流量又好好的

**Comment by Fangliding** [comment]
可能你用的SNI被干扰了 还有这里不处理其他核心遇到的问题
