### ISSUE TITLE
XHTTP with downloadSettings does not return the requested web page

### ISSUE THREAD

**Issue by xjkj8** [XTLS/Xray-core#4080]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

On the client PC, Firefox browser on Windows 10 was configured to use Xray-core v24.11.21. 

The web page whatismyipaddress.com was requested.

Firefox browser displayed only a blank page instead of the requested web page.

### Reproduction Method

On Debian 12 server, install Xray-core v24.11.21 with XTLS/Xray-install script. Run xray with the systemd service file.

On Windows 10 client, download Xray-windows-64.zip v24.11.21. Run xray.exe from the command line.

### Client config

<details><pre><code>
{
    "log": {
        "loglevel": "info"
    },
    "routing": {
        "rules": [
            {
                "ip": [
                    "geoip:private"
                ],
                "outboundTag": "direct"
            }
        ]
    },
    "inbounds": [
        {
            "listen": "127.0.0.1",
            "port": 10808,
            "protocol": "socks"
        },
        {
            "listen": "127.0.0.1",
            "port": 10809,
            "protocol": "http"
        }
    ],
    "outbounds": [
        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "**.**.**.**",
                        "port": 443,
                        "users": [
                            {
                                "id": "151940d1-50a9-49dd-94cc-0884bbb59127",
                                "encryption": "none"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "xhttp",
                "xhttpSettings": {
                    "path": "/pujw2bcn",
                    "downloadSettings": {
                        "address": "**.**.**.**", 
                        "port": 8443,
                        "network": "xhttp",
                        "xhttpSettings": {
                            "path": "/pujw2bcn"
                        },
                        "security": "reality",
                        "realitySettings": {
                            "fingerprint": "chrome",
                            "serverName": "www.bing.com",
                            "publicKey": "9Mrn_IDBy4s2j6H_MRMwL_Ih7f4ZONSksfymJ0-etTY"
                        }
                    }
                },
                "security": "reality",
                "realitySettings": {
                    "fingerprint": "chrome",
                    "serverName": "www.asus.com",
                    "publicKey": "8zSuQb5wxHUOYj_pLZ5DBBeFFEoczCOPVW6WFJSAB2k" 
                }
            }
        },
        {
            "protocol": "freedom",
            "tag": "direct"
        }
    ]
}
</code></pre></details>

### Server config

<details><pre><code>
{
    "log": {
        "loglevel": "info"
    },
    "inbounds": [
        {
            "listen": "@xhttp",
            "protocol": "vless",
            "settings": {
                "decryption": "none",
                "clients": [
                    {
                        "id": "151940d1-50a9-49dd-94cc-0884bbb59127"
                    }
                ]
            },
            "streamSettings": {
                "network": "xhttp",
                "xhttpSettings": {
                    "path": "/pujw2bcn"
                }
            }
        },
        {
            "listen": "0.0.0.0",
            "port": 443,
            "protocol": "vless",
            "settings": {
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": "@xhttp"
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "reality",
                "realitySettings": {
                    "xver": 0,
                    "target": "www.asus.com:443",
                    "serverNames": [
                        "www.asus.com"
                    ],
                    "privateKey": "iJ094QDXKk0bDmZUPTxxZNytl256u1cqn7bQ1MsciDo",
                    "shortIds": [
                        ""
                    ]
                }
            }
        },
        {
            "listen": "0.0.0.0",
            "port": 8443,
            "protocol": "vless",
            "settings": {
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": "@xhttp"
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "reality",
                "realitySettings": {
                    "xver": 0,
                    "target": "www.bing.com:443",
                    "serverNames": [
                        "www.bing.com"
                    ],
                    "privateKey": "2NZPdafvN3akvX6pqNfZbDVd6PYZHlcyqRsd38Dd4Cw",
                    "shortIds": [
                        ""
                    ]
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "tag": "block"
        }
    ]
}
</code></pre></details>

### Client log

<details><pre><code>
[Info] [1178609711] proxy/socks: TCP Connect request to tcp:whatismyipaddress.com:80
[Info] [1178609711] app/dispatcher: default route for tcp:whatismyipaddress.com:80
from tcp:127.0.0.1:59645 accepted tcp:whatismyipaddress.com:80
[Info] [1178609711] transport/internet/splithttp: dialing splithttp to tcp:**.**.**.**:443
[Info] [1178609711] transport/internet/splithttp: XHTTP is using mode: stream-up
[Info] [1178609711] proxy/vless/outbound: tunneling request to tcp:whatismyipaddress.com:80 via **.**.**.**:443
[Info] transport/internet/reality: REALITY localAddr: 10.0.0.132:59646      DialTLSContext

[Info] [2978169963] proxy/socks: TCP Connect request to tcp:push.services.mozilla.com:443
[Info] [2978169963] app/dispatcher: default route for tcp:push.services.mozilla.com:443
[Info] [2978169963] transport/internet/splithttp: dialing splithttp to tcp:**.**.**.**:443
[Info] [2978169963] transport/internet/splithttp: XHTTP is using mode: stream-up
[Info] [2978169963] proxy/vless/outbound: tunneling request to tcp:push.services.mozilla.com:443 via **.**.**.**:443
 from tcp:127.0.0.1:59647 accepted tcp:push.services.mozilla.com:443
[Info] transport/internet/reality: REALITY localAddr: 10.0.0.132:59648      DialTLSContext

[Info] [727417288] proxy/socks: TCP Connect request to tcp:whatismyipaddress.com:80
[Info] [727417288] app/dispatcher: default route for tcp:whatismyipaddress.com:80
 from tcp:127.0.0.1:59649 accepted tcp:whatismyipaddress.com:80
[Info] [727417288] transport/internet/splithttp: dialing splithttp to tcp:**.**.**.**:443
[Info] [727417288] transport/internet/splithttp: XHTTP is using mode: stream-up
[Info] [727417288] proxy/vless/outbound: tunneling request to tcp:whatismyipaddress.com:80 via **.**.**.**:443
[Info] transport/internet/reality: REALITY localAddr: 10.0.0.132:59650      DialTLSContext
</code></pre></details>

### Server log

<details><pre><code>
[Info] [2500453426] proxy/vless/inbound: firstLen = 70
[Info] [2500453426] proxy/vless/inbound: fallback starts > proxy/vless/encoding: invalid request version
[Info] [2500453426] proxy/vless/inbound: realName = www.bing.com
[Info] [2500453426] proxy/vless/inbound: realAlpn =
[Info] [3394812765] proxy/vless/inbound: firstLen = 0
[Info] [3394812765] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
[Info] [561381297] proxy/vless/inbound: firstLen = 0
[Info] [561381297] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
[Info] [1688186321] proxy/vless/inbound: firstLen = 0
[Info] [1688186321] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
[Info] [1821959833] proxy/vless/inbound: firstLen = 0
[Info] [1821959833] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
[Info] [3110279669] proxy/vless/inbound: firstLen = 0
[Info] [3110279669] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
[Info] [3280814406] proxy/vless/inbound: firstLen = 0
[Info] [3280814406] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
[Info] [300611709] proxy/vless/inbound: firstLen = 0
[Info] [300611709] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
[Info] [1747893840] proxy/vless/inbound: firstLen = 0
[Info] [1747893840] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
[Info] [2274265780] proxy/vless/inbound: firstLen = 0
[Info] [2274265780] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
[Info] [621792754] proxy/vless/inbound: firstLen = 0
[Info] [621792754] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
[Info] [1849588429] proxy/vless/inbound: firstLen = 0
[Info] [1849588429] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
[Info] [2079987345] proxy/vless/inbound: firstLen = 0
[Info] [2079987345] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
[Info] [2808161726] proxy/vless/inbound: firstLen = 0
[Info] [2808161726] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
[Info] [3266443824] proxy/vless/inbound: firstLen = 0
[Info] [3266443824] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
[Info] [590052304] proxy/vless/inbound: firstLen = 0
[Info] [590052304] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
[Info] [1605134916] proxy/vless/inbound: firstLen = 0
[Info] [1605134916] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
[Info] [671527417] proxy/vless/inbound: firstLen = 0
[Info] [671527417] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF
</code></pre></details>

**Comment by RPRX** [comment]
无此 bug，检查配置

**Comment by Fangliding** [comment]
这是一个极端罕见的问题 华硕这个官网使用的密钥交换算法是p-256 不是常见的x25519 所以reality不能用

**Comment by xjkj8** [comment]
@Fangliding That's it! I change `www.asus.com` to `www.apple.com` and it works. Thanks!
