### ISSUE TITLE
访问 v1.mux.cool 被作为 mux 处理，并且出现 Error

### ISSUE THREAD

**Issue by xqzr** [XTLS/Xray-core#4088]
```batch
curl -x [::1]:1084 v1.mux.cool
```
```log
2024/07/17 02:49:01 [Error] [3776900861] common/mux: unexpected EOF > common/mux: failed to read metadata > common/mux: invalid metalen 18245
2024/07/17 02:49:01 [Warning] [3776900861] app/proxyman/inbound: connection ends > proxy/http: connection ends > proxy/http: failed to write whole request > io: read/write on closed pipe
2024/07/17 02:49:01 [Warning] [3776900861] proxy/http: failed to read response from v1.mux.cool > io: read/write on closed pipe
```
https://t.me/projectXray/3763503?thread=3763267

**Comment by RPRX** [comment]
符合预期，~~除非有应用通过访问这些地址来判断是 ray/sb 还是其它的什么~~

**Comment by xqzr** [comment]
> 通过访问这些地址来判断是 ray/sb 还是其它

这正是我所**担心**的事情

**Comment by RPRX** [comment]
> > 通过访问这些地址来判断是 ray/sb 还是其它
> 
> 这正是我所**担心**的事情

只有 VLESS 和 VMess 有原生的 Mux 指令，其它协议就是传 v1.mux.cool，所以其它协议是修不好的，而 sb 是所有协议都修不好

**Comment by Fangliding** [comment]
反正这是一个无效地址不管啥当服务端 curl过去都是断开吧

**Comment by xqzr** [comment]
> 反正这是一个无效地址

https://mux.cool/cdn-cgi/trace

**Comment by RPRX** [comment]
> 反正这是一个无效地址不管啥当服务端 curl过去都是断开吧

断开的时间和形式可能不同，大概

> https://mux.cool/cdn-cgi/trace

~~不过 v1.mux.cool 无站点~~

**Comment by xqzr** [comment]
> v1.mux.cool 无站点

也无解析。不过，也许**将来**会有

**Comment by Fangliding** [comment]
现在它没有 祈祷以后也不会有吧
理论上是没法完全缓解的 因为攻击者完全可以构建一个符合mux帧的请求让xray进入mux模式 这是跨协议支持不可避免的
我能想出来的最大的威胁是网页尝试跨站访问 v1.mux.cool 如果真的有这种事 倒是可以采用一些简单的缓解措施 出事再说吧

**Comment by xqzr** [comment]
> 其它协议就是传 v1.mux.cool

也许，它导致了这个问题 #4089

**Comment by xqzr** [comment]
> 网页尝试跨站访问 v1.mux.cool

相关阅读：https://www.v2ex.com/t/1076579
