### ISSUE TITLE
sniffing分流出现中转请求异常

### ISSUE THREAD

**Issue by DTCproto** [XTLS/Xray-core#409]
正常情况：本地 wss -> A机器：sni分流 -> vless tls -> B机器
**_异常情况：本地 grpcs_** -> A机器：sni分流 -> vless tls -> B机器
[中转去除tls后正常]

异常日志：
panic: EOF
goroutine 2090 [running]:
github.com/xtls/xray-core/common.Must(...)
        github.com/xtls/xray-core/common/common.go:26
github.com/xtls/xray-core/common.Must2(...)
        github.com/xtls/xray-core/common/common.go:32
github.com/xtls/xray-core/common/buf.Compact(0xc0004e02e0, 0x4, 0x4, 0xc00039d2d0, 0xc0004e02e0, 0x4)
        github.com/xtls/xray-core/common/buf/multi_buffer.go:151 +0x2c5
github.com/xtls/xray-core/transport/internet/tls.(*Conn).WriteMultiBuffer(0xc00039d610, 0xc0004e02e0, 0x4, 0x4, 0x0, 0x6b5339)
        github.com/xtls/xray-core/transport/internet/tls/tls.go:21 +0x49
github.com/xtls/xray-core/common/buf.(*BufferedWriter).WriteMultiBuffer(0xc0005bb170, 0xc0004e02e0, 0x4, 0x4, 0x0, 0x0)
        github.com/xtls/xray-core/common/buf/writer.go:136 +0x35e
github.com/xtls/xray-core/common/buf.copyInternal(0x102d920, 0xc000524d80, 0x102e460, 0xc0005bb170, 0xc000466b10, 0xc0005bb101, 0xc000466af8)
        github.com/xtls/xray-core/common/buf/copy.go:87 +0x1b2
github.com/xtls/xray-core/common/buf.Copy(0x102d920, 0xc000524d80, 0x102e460, 0xc0005bb170, 0xc0005a2f60, 0x1, 0x1, 0x1019240, 0xc00014eed8)
        github.com/xtls/xray-core/common/buf/copy.go:104 +0xa8
github.com/xtls/xray-core/proxy/vless/outbound.(*Handler).Process.func2(0x0, 0x0)
        github.com/xtls/xray-core/proxy/vless/outbound/outbound.go:210 +0x5d6
github.com/xtls/xray-core/common/task.Run.func1(0xc00039d618, 0xc0005bf5c0, 0xc00019bc80)
        github.com/xtls/xray-core/common/task/task.go:28 +0x2b
created by github.com/xtls/xray-core/common/task.Run
        github.com/xtls/xray-core/common/task/task.go:27 +0x152

**Comment by JimhHan** [comment]
是否启用了 Multi Mode？

**Comment by DTCproto** [comment]
> 是否启用了 Multi Mode？

已启用

**Comment by JimhHan** [comment]
@DTCproto 

https://github.com/XTLS/Xray-core/commit/aa2472a0b475840d4498fce18c7ade7b86904bf3 中修复了此问题。如果方便，请测试下修复后是否还会出现异常。
 在 [这里](https://github.com/XTLS/Xray-core/actions/runs/670648704) 可以找到预编译的二进制文件。

**Comment by DTCproto** [comment]
> @DTCproto 
> 
> https://github.com/XTLS/Xray-core/commit/aa2472a0b475840d4498fce18c7ade7b86904bf3 中修复了此问题。如果方便，请测试下修复后是否还会出现异常。
>  在 [这里](https://github.com/XTLS/Xray-core/actions/runs/670648704) 可以找到预编译的二进制文件。

actions编译失败了

**Comment by DTCproto** [comment]
> > https://github.com/XTLS/Xray-core/commit/aa2472a0b475840d4498fce18c7ade7b86904bf3 中修复了此问题。如果方便，请测试下修复后是否还会出现异常。
> >  在 [这里](https://github.com/XTLS/Xray-core/actions/runs/670648704) 可以找到预编译的二进制文件。
> 
@JimhHan  actions编译失败了

**Comment by JimhHan** [comment]
@DTCproto 是的，发现了一点问题，正在修

**Comment by JimhHan** [comment]
现在可以了。
https://github.com/XTLS/Xray-core/actions/runs/670929184
