### ISSUE TITLE
speedtest网页测速导致VPS限速,重启xray立刻恢复正常

### ISSUE THREAD

**Issue by chuncai111** [XTLS/Xray-core#4101]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

我是用的vless+reality+xtls-rprx-vision,在speedtest网页连续测速几次后,VSP直接限速,开始sudo ss -K才能恢复,最后发现是xray的问题,只要限速,重启xray才正常,我不知道怎么解决,网上搜是因为测速期间,会有大量tcp连接,xray不能及时清理吗?或者有什么及时清理的指令呢?我用最新三个版本的xray和18版本的都是这样

### 重现方式

使用vless+reality+xtls-rprx-vision的VSP,进行speedtest网页连续测速,绝对会触发这个情况

### 客户端配置

<details><pre><code>

</code></pre></details>

### 服务端配置

<details><pre><code>

</code></pre></details>

### 客户端日志

<details><pre><code>

</code></pre></details>

### 服务端日志

<details><pre><code>

</code></pre></details>

**Comment by RPRX** [comment]
Speedtest 的连接数就是很多，而 Vision 没有多路复用，不过这么久了都没别人报告这情况的话，推荐你换个 VPS 或服务商
