### ISSUE TITLE
speedtest网页测速导致VPS限速,重启xray立刻恢复正常

### ISSUE THREAD

**Issue by chuncai111** [XTLS/Xray-core#4103]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

中午发的被关了,我没说清,我用的是搬瓦工VPS,商家绝对不会限速,也用RN服务器测试了,并且也使用过纯净的系统,只要使用vless+reality+xtls-rprx-vision都是会触发这个情况,因为正常的富强机器,没有别的业务,本身TCP连接就少,所有可能四五次甚至五六次才会触发,但是我的机器有几个网页,tcp连接多,所以测速一两次就会直接触发限速.目前我测试的 只有使用hy2那个协议不会被影响,不知道这是设计的问题还是啥?我该如何解决?为啥不会把测速的tcp连接结束后及时清理呢
我是用的vless+reality+xtls-rprx-vision,在speedtest网页连续测速几次后,或者fast.com网页测速几次也会限速,VSP直接限速,开始sudo ss -K才能恢复,最后发现是xray的问题,只要限速,重启xray才正常,我不知道怎么解决,网上搜是因为测速期间,会有大量tcp连接,xray不能及时清理吗?或者有什么及时清理的指令呢?我用最新三个版本的xray和18版本的都是这样.

### Reproduction Method

使用vless+reality+xtls-rprx-vision的VSP,进行speedtest网页连续测速,绝对会触发这个情况

### Client config

<details><pre><code>

</code></pre></details>

### Server config

<details><pre><code>

</code></pre></details>

### Client log

<details><pre><code>

</code></pre></details>

### Server log

<details><pre><code>

</code></pre></details>

**Comment by Fangliding** [comment]
如果你日志还是空着的话那还是会关的
以及你试过不开vision会有问题吗
还有你VPS打成了VSP

**Comment by chuncai111** [comment]
这种问题延伸到,如果测速的tcp连接xray不能及时清理,被限速,那如果平常多人共用xray的节点,是否也会触发这个限速?只是当网卡了一会? 个人猜想哈,看看大佬怎么说

**Comment by RPRX** [comment]
说实话我印象中没人报告过这种问题，你 VPS 换个操作系统试试

**Comment by chuncai111** [comment]
> 说实话我印象中没人报告过这种问题，你 VPS 换个操作系统试试

换过了,我使用了debian11,12,cen9官方的,和DD的纯净系统都试过了,都会触发这个情况,像我说,没人会一直在网页测速,大家都是跑个融合怪差不多.新机tcp连接少,所以三四次不会触发,但是确实有这个问题存在

**Comment by avsba001** [comment]
> > 说实话我印象中没人报告过这种问题，你 VPS 换个操作系统试试
> 
> 换过了,我使用了debian11,12,cen9官方的,和DD的纯净系统都试过了,都会触发这个情况,像我说,没人会一直在网页测速,大家都是跑个融合怪差不多.新机tcp连接少,所以三四次不会触发,但是确实有这个问题存在

同搬瓦工，没遇到，除非hk85

**Comment by chuncai111** [comment]
> > > 说实话我印象中没人报告过这种问题，你 VPS 换个操作系统试试
> > 
> > 
> > 换过了,我使用了debian11,12,cen9官方的,和DD的纯净系统都试过了,都会触发这个情况,像我说,没人会一直在网页测速,大家都是跑个融合怪差不多.新机tcp连接少,所以三四次不会触发,但是确实有这个问题存在
> 
> 同搬瓦工，没遇到，除非hk85

不管DC几,你按我写的触发情况试

**Comment by AtticusZeller** [comment]
最近也碰到过必须要重启

**Comment by chuncai111** [comment]
有新进展了,目前发现各大测速网页,会导致xray有很大 类似于ESTAB      0       3501400 [::ffff:xx.xx.225.xx]:40002 [::ffff:xx.37.xx.182]:63620 users:(("xray-linux-amd6",pid=35082,fd=107))  ,这样的连接,Recv−Q累加大于10m,VPS就会限速.
使用ss -antp | awk '/xray-linux-amd6/ && $3 > 1000000 {
    split($NF, a, "="); 
    split(a[2], b, ","); 
    if (b[1] ~ /^[0-9]+$/) {
        print b[1]
    }
}' | xargs -r kill -9,删除大的连接,就能恢复.
看油管有类似大连接的时候,可以及时自动断开Recv−Q大的
但是测速网页产生的,会一直存在,我已经关网页了,现在看原因就是xray对某些连接判断有误?清除不及时?
tcp我简单了解一下,一发一收,互相确定,自动清除缓存,那现在就是收到了,没处理好,?导致堵塞吗?

**Comment by avsba001** [comment]
> > > > 说实话我印象中没人报告过这种问题，你 VPS 换个操作系统试试
> > > 
> > > 
> > > 换过了,我使用了debian11,12,cen9官方的,和DD的纯净系统都试过了,都会触发这个情况,像我说,没人会一直在网页测速,大家都是跑个融合怪差不多.新机tcp连接少,所以三四次不会触发,但是确实有这个问题存在
> > 
> > 
> > 同搬瓦工，没遇到，除非hk85
> 
> 不管DC几,你按我写的触发情况试

我调tcp内核参数的时候speedtest测了一晚上都没这样啊，协议一直是vless+reality+xtls-rprx-vision

**Comment by chuncai111** [comment]
> > > > > 说实话我印象中没人报告过这种问题，你 VPS 换个操作系统试试
> > > > 
> > > > 
> > > > 换过了,我使用了debian11,12,cen9官方的,和DD的纯净系统都试过了,都会触发这个情况,像我说,没人会一直在网页测速,大家都是跑个融合怪差不多.新机tcp连接少,所以三四次不会触发,但是确实有这个问题存在
> > > 
> > > 
> > > 同搬瓦工，没遇到，除非hk85
> > 
> > 
> > 不管DC几,你按我写的触发情况试
> 
> 我调tcp内核参数的时候speedtest测了一晚上都没这样啊，协议一直是vless+reality+xtls-rprx-vision

你测速的时候,连上VPS,测速一次,输入: ss -antp | grep xray  
你就会发现有几m的读取缓存,一直测速,他就一直涨,累计到10m,触发限速.你实时对比着一看就明白了

**Comment by avsba001** [comment]
> > > > > > 说实话我印象中没人报告过这种问题，你 VPS 换个操作系统试试
> > > > > 
> > > > > 
> > > > > 换过了,我使用了debian11,12,cen9官方的,和DD的纯净系统都试过了,都会触发这个情况,像我说,没人会一直在网页测速,大家都是跑个融合怪差不多.新机tcp连接少,所以三四次不会触发,但是确实有这个问题存在
> > > > 
> > > > 
> > > > 同搬瓦工，没遇到，除非hk85
> > > 
> > > 
> > > 不管DC几,你按我写的触发情况试
> > 
> > 
> > 我调tcp内核参数的时候speedtest测了一晚上都没这样啊，协议一直是vless+reality+xtls-rprx-vision
> 
> 你测速的时候,连上VPS,测速一次,输入: ss -antp | grep xray 你就会发现有几m的读取缓存,一直测速,他就一直涨,累计到10m,触发限速.你实时对比着一看就明白了

确实有个奇怪的10mbps左右的限速，我测试一下和bwg机房有关联不，dmit的gia没这个限制，起码不是线路问题

**Comment by avsba001** [comment]
![image](https://github.com/user-attachments/assets/cfd63b6b-5d50-40c7-bdd9-99ca43943ff6)
试了下，我在dc9 限速10m，直接迁移到dc6 单线程都能上360m了，貌似是触发了bwg某些限制策略导致的线路限速

**Comment by RPRX** [comment]
~~那先关了~~
