### ISSUE TITLE
Wrong/missing tags in routing rules prevent app from working entirely

### ISSUE THREAD

**Issue by eliotcougar** [XTLS/Xray-core#4105]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

I was told to report this bug here, instead of v2rayN
Recently v2rayN implemented regional geofiles support, and that uncovered an annoying issue with routing rules and tags.
Basically, when there is a tag in routing rules that is missing in the geoip/geosite files, the xray-core reports an error in the log, and stops working. As the result, the whole app stops routing any traffic for the whole machine.

In my case, I was using the custom Russian geosite/geoip regional setting, and I had some routing rules that referenced tags that only exist in that Russian version of geoip/geosite files. When the program was updated, it downloaded the default "Chinese" geoip/geosite files for some reason, and replaced them. After v2rayN restarted, the routing rules were referencing some missing tags. The program couldn't fix itself by re-downloading the correct "Russian" files because no traffic could flow due to error. At this point, manual intervention is required. Auto-update cannot be used reliably in unattended mode. What if a geosite.dat maintainer decides to remove or rename a tag? After an autoupdate, if the user has used that tag, their internet will suddenly stop working.

Why can't the core just display an error in the log about wrong/missing tags, but keep working normally, ignoring the wrong/missing tags in the routing rules. **In other words, this kind of error should be non-blocking, and fail gracefully.**

### Reproduction Method

Include a nonexistent geosite/geoip tag in the routing config.

### Client config

<details><pre><code>
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api"
      },
      {
        "type": "field",
        "outboundTag": "proxy",
        "domain": [
          "geosite:ru-blocked-all"
        ]
      },
      {
        "type": "field",
        "outboundTag": "proxy",
        "ip": [
          "geoip:ru-blocked"
        ]
      },
      {
        "type": "field",
        "port": "0-65535",
        "outboundTag": "direct"
      }
    ]
</code></pre></details>

### Server config

<details><pre><code>
not needed
</code></pre></details>

### Client log

<details><pre><code>
2024/12/04 14:32:58 [Info] infra/conf/serial: Reading config: &{Name:config.json Format:json}
Failed to start: main: failed to load config files: [config.json] > infra/conf: invalid field rule > infra/conf: failed to parse domain rule: geosite:ru-blocked-alll > infra/conf: failed to load geosite: RU-BLOCKED-ALLL > infra/conf: list not found in geosite.dat: RU-BLOCKED-ALL
</code></pre></details>

### Server log

<details><pre><code>
not needed
</code></pre></details>

**Comment by Fangliding** [comment]
We have support for custom geo file `"ext:file:tag"` https://xtls.github.io/config/routing.html#ruleobject

**Comment by eliotcougar** [comment]
> We have support for custom geo file `"ext:file:tag"` https://xtls.github.io/config/routing.html#ruleobject

That's not related to the issue at all. 
I did tell v2rayN devs that it would be better to separate specific regional tags into a separate file and load it via ext:file:, but they said "not planned" and decided to have separate full geoip/geosite files with entirely different sets of tags. That makes maintaining rulesets a pain since you can never know when a file gets reverted during an update, or a maintainer alters a geoip/geosite file tags in a new update. The machine becomes inaccessible and requires manual intervention when something like that happens.

Is there a reason why the wrong/missing tag is an ERROR, and not just an INFO or WARNING?..

**Comment by Fangliding** [comment]
There is much debate about whether the core should exit upon encountering certain errors or simply log a message and bypass. In general, we will not change them unless there are compelling reasons. You need the core to not accidentally exit. What if someone else accidentally wrote a wrong letter in their block rule, causing the connection to leak without being found?

**Comment by eliotcougar** [comment]
> There is much debate about whether the core should exit upon encountering certain errors or simply log a message and bypass. In general, we will not change them unless there are compelling reasons. You need the core to not accidentally exit. What if someone else accidentally wrote a wrong letter in their block rule, causing the connection to leak without being found? I'm just providing the best looking suggestion, the behavior of the third-party client has nothing to do with us

Yes, I thought about that scenario too. I'll try to communicate that to the v2rayN. Sadly, the need for censorship circumvention is rapidly becoming multinational, and the first implementation of the "regional settings" feature by v2rayN is a little bit of mess.
