### ISSUE TITLE
dial tcp: lookup 127.1: no such host

### ISSUE THREAD

**Issue by qupig** [XTLS/Xray-core#4122]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

It seems that in `Ubuntu`, if the outbound address is written as `127.1`, the routing will fail. If it is changed to the complete `127.0.0.1`, it will work normal.

But the strange thing is that both of the above writings work in macOS. In other words, there is no issues in writing `127.1` in macOS as outbound address.

Just curious about the reason for this difference.

Xray 24.11.30

### Reproduction Method

Forward socks to an `127.1` outbound, I haven't tested other protocols.

### Client config

<details>

```json
{
    "log": {
        "loglevel": "debug"
    },
    "inbounds": [
        {
            "tag": "in-test",
            "port": 11080,
            "listen": "127.0.0.1",
            "protocol": "socks",
            "settings": {
                "auth": "noauth",
                "udp": true
            }
        }
    ],
    "outbounds": [
        {
            "tag": "out-test",
            "protocol": "socks",
            "settings": {
                "servers": [
                    {
                        "address": "127.1",
                        "port": 22080
                    }
                ]
            }
        }
    ],
    "routing": {
        "domainStrategy": "AsIs",
        "rules": [
            {
                "inboundTag": [
                    "in-test"
                ],
                "outboundTag": "out-test"
            }
        ]
    }
}
```

</details>

### Server config

N/A

### Client log

```sh
app/proxyman/outbound: app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to find an available destination > common/retry: [dial tcp: lookup 127.1: no such host] > common/retry: all retry attempts failed
```

### Server log

N/A

**Comment by xqzr** [comment]
IPv4 缩写（`127.1`）应用兼容性，不理想。
建议使用 IPv6 `::1`

**Comment by xqzr** [comment]
> But this may only works well for loopback, not other devices such as `10.1`.

fd10::1

**Comment by Fangliding** [comment]
This is not a standard format, the actual behavior depends on the syscall of different systems
Issues only for bug feedback, do not post irrelevant content here
