### ISSUE TITLE
xray-core cannnot listen ipv4

### ISSUE THREAD

**Issue by jmjasonchan** [XTLS/Xray-core#413]
I have no idea why the xray-core cannot listen on ipv4? only listen on ipv6 on the oracle vps, anyone can help me?

**Comment by AkinoKaede** [comment]
Please provide your configurations and logs

**Comment by jmjasonchan** [comment]
{
    "log": {
        "loglevel": "warning"
    },
    "inbounds": [
        {
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "439c8795-d896-4d60-9e11-5e20axxxxxxxxxx", // 填写你的 UUID
                        "level": 0,
                        "email": "quanyan.chen@gmail.com"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": 80
                    },
                    {
                        "path": "/websocket", // 必须换成自定义的 PATH
                        "dest": 1234,
                        "xver": 1
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "alpn": [
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "/etc/nginx/cerfication/wordpress/wordpress.crt", // 换成你的证书，绝对路径
                            "keyFile": "/etc/nginx/cerfication/wordpress/wordpress.key" // 换成你的私钥，绝对路径
                        }
                    ]
                }
            }



Mar 20 14:20:57 ubuntu20-04 systemd[1]: Stopping Xray Service...
-- Subject: A stop job for unit xray.service has begun execution
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- A stop job for unit xray.service has begun execution.
--
-- The job identifier is 5021.
Mar 20 14:20:57 ubuntu20-04 systemd[1]: xray.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- The unit xray.service has successfully entered the 'dead' state.
Mar 20 14:20:57 ubuntu20-04 systemd[1]: Stopped Xray Service.
-- Subject: A stop job for unit xray.service has finished
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- A stop job for unit xray.service has finished.
--
-- The job identifier is 5021 and the job result is done.
Mar 20 14:20:57 ubuntu20-04 systemd[1]: Started Xray Service.
-- Subject: A start job for unit xray.service has finished successfully
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- A start job for unit xray.service has finished successfully.
--
-- The job identifier is 5021.
Mar 20 14:20:57 ubuntu20-04 xray[17151]: Xray 1.4.0 (Xray, Penetrates Everything                                                                                        .) Custom (go1.16.2 linux/amd64)
Mar 20 14:20:57 ubuntu20-04 xray[17151]: A unified platform for anti-censorship.
Mar 20 14:20:57 ubuntu20-04 xray[17151]: 2021/03/20 14:20:57 [Info] infra/conf/s                                                                                        erial: Reading config: /usr/local/etc/xray/config.json
Mar 20 14:20:57 ubuntu20-04 xray[17151]: 2021/03/20 14:20:57 [Warning] transport                                                                                        /internet/websocket: accepting PROXY protocol
Mar 20 14:20:57 ubuntu20-04 xray[17151]: 2021/03/20 14:20:57 [Warning] core: Xra                                                                                        y 1.4.0 started

**Comment by jmjasonchan** [comment]
{
    "log": {
        "loglevel": "warning"
    },
    "inbounds": [
        {
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "439c8795-d896-4d60-9e11-5e20axxxxxxxxxx", // 填写你的 UUID
                        "level": 0,
                        "email": "quanyan.chen@gmail.com"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": 80
                    },
                    {
                        "path": "/websocket", // 必须换成自定义的 PATH
                        "dest": 1234,
                        "xver": 1
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "alpn": [
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "/etc/nginx/cerfication/wordpress/wordpress.crt", // 换成你的证书，绝对路径
                            "keyFile": "/etc/nginx/cerfication/wordpress/wordpress.key" // 换成你的私钥，绝对路径
                        }
                    ]
                }
            }



Mar 20 14:20:57 ubuntu20-04 systemd[1]: Stopping Xray Service...
-- Subject: A stop job for unit xray.service has begun execution
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- A stop job for unit xray.service has begun execution.
--
-- The job identifier is 5021.
Mar 20 14:20:57 ubuntu20-04 systemd[1]: xray.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- The unit xray.service has successfully entered the 'dead' state.
Mar 20 14:20:57 ubuntu20-04 systemd[1]: Stopped Xray Service.
-- Subject: A stop job for unit xray.service has finished
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- A stop job for unit xray.service has finished.
--
-- The job identifier is 5021 and the job result is done.
Mar 20 14:20:57 ubuntu20-04 systemd[1]: Started Xray Service.
-- Subject: A start job for unit xray.service has finished successfully
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- A start job for unit xray.service has finished successfully.
--
-- The job identifier is 5021.
Mar 20 14:20:57 ubuntu20-04 xray[17151]: Xray 1.4.0 (Xray, Penetrates Everything                                                                                        .) Custom (go1.16.2 linux/amd64)
Mar 20 14:20:57 ubuntu20-04 xray[17151]: A unified platform for anti-censorship.
Mar 20 14:20:57 ubuntu20-04 xray[17151]: 2021/03/20 14:20:57 [Info] infra/conf/s                                                                                        erial: Reading config: /usr/local/etc/xray/config.json
Mar 20 14:20:57 ubuntu20-04 xray[17151]: 2021/03/20 14:20:57 [Warning] transport                                                                                        /internet/websocket: accepting PROXY protocol
Mar 20 14:20:57 ubuntu20-04 xray[17151]: 2021/03/20 14:20:57 [Warning] core: Xra                                                                                        y 1.4.0 started

**Comment by rprx** [comment]
不写 `listen` 实际上是会同时监听 IPv4、IPv6 的，只是 `netstat` 命令可能会只显示 IPv6
