### ISSUE TITLE
xhttp+reality无法连接

### ISSUE THREAD

**Issue by juneszh** [XTLS/Xray-core#4130]
### 完整性要求

- [ ] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [ ] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

按照这个配置：https://github.com/lxhao61/integrated-examples/blob/main/Xray(VLESS%2BXHTTP%2BREALITY)/xray_config.json

实际上原来"network": "raw"时是可用的，两端改为”xhttp“就不行。

xray/error.log

> 2024/12/07 15:30:56 [Info] [452644276] proxy/vless/inbound: firstLen = 0
2024/12/07 15:30:56 [Info] [452644276] app/proxyman/inbound: connection ends > proxy/vless/encoding: failed to read request version > EOF

### 重现方式

Ubuntu 20.04 LTS
Xray 24.11.30 (Xray, Penetrates Everything.) 98a72b6 (go1.23.3 linux/amd64)

### 客户端配置

<details><pre><code>

</code></pre></details>

### 服务端配置

<details><pre><code>

</code></pre></details>

### 客户端日志

<details><pre><code>

</code></pre></details>

### 服务端日志

<details><pre><code>

</code></pre></details>

**Comment by Fangliding** [comment]
信息约等于没有

**Comment by juneszh** [comment]
> 信息约等于没有

已补充

**Comment by Fangliding** [comment]
![image](https://github.com/user-attachments/assets/38c7c8e4-c4dd-4143-b7c7-dbc5d8644373)
xtls不支持xhttp

**Comment by lxhao61** [comment]
就是，你配置 xtls-rprx-vision 干啥？

**Comment by juneszh** [comment]
> ![image](https://private-user-images.githubusercontent.com/45535409/393502129-38c7c8e4-c4dd-4143-b7c7-dbc5d8644373.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1Njc4OTYsIm5iZiI6MTczMzU2NzU5NiwicGF0aCI6Ii80NTUzNTQwOS8zOTM1MDIxMjktMzhjN2M4ZTQtYzRkZC00MTQzLWI3YzctZGJjNWQ4NjQ0MzczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDEwMzMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMTM2ZmZjMzQzMjMzMzBhNDI2YzQyNzkzODhmYThmMzllMWZhNzdiODZlY2E5MmJhMzZkODIxOGZiZTI0NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2xfcTb0ytNSMHWiB16ZZOi4SqeqYeXyg3JCbrBNkLDU) xtls不支持xhttp

原来删掉"flow": "xtls-rprx-vision"就可以，感谢

**Comment by juneszh** [comment]
> 就是，你配置 xtls-rprx-vision 干啥？

因为看配置跟原来"network": "raw"时差不多，没发现clients里少了"flow": "xtls-rprx-vision"
