### ISSUE TITLE
反向代理使用ws+tls+cdn出站无法正确反向代理

### ISSUE THREAD

**Issue by bigoovip** [XTLS/Xray-core#4136]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

Xray 24.11.30，cdn使用cloudflare免费计划。

客户端配置如下，通过ws+tls+cdn出站连接xray服务端，无法访问被反代的服务器，但使用同样配置的ws+tls+cdn用来代理上网，是可以正常代理上网的。
尝试使用vless+tcp+reality出站连接xray服务端，可以正常访问被反代的服务器。

### 重现方式

被反代的服务器处于无公网环境，通过ws+tls+cdn出站连接xray服务端，即可重现

### 客户端配置

<details><pre><code>
{
	"log": {
		"access": "",
		"error": "",
		"loglevel": "debug"
	},
	"reverse": {
		"bridges": [
			{
				"tag": "bridge",
				"domain": "localhost"
			}
		]
	},
	"outbounds": [
		{
			"tag": "bridgeout",
			"protocol": "freedom"
		},
		{
			"tag": "cdn",
			"protocol": "vmess",
			"settings": {
				"vnext": [
					{
						"address": "优选ip",
						"port": 443,
						"users": [
							{
								"id": "uuid",
								"security": "auto",
								"level": 0
							}
						]
					}
				]
			},
			"streamSettings": {
				"network": "ws",
				"wsSettings": {
					"path": "/",
					"host": "源服务器域名"
				},
				"security": "tls",
				"tlsSettings": {
					"serverName": "源服务器域名",
					"fingerprint": "chrome"
				}
			}
		}
	],
	"routing": {
		"rules": [
			{
				"type": "field",
				"inboundTag": [
					"bridge"
				],
				"domain": [
					"full:localhost"
				],
				"outboundTag": "cdn"
			},
			{
				"type": "field",
				"inboundTag": [
					"dsm_bridge"
				],
				"outboundTag": "bridgeout"
			}
		]
	}
}
</code></pre></details>

### 服务端配置

<details><pre><code>
{
	"log": {
		"loglevel": "warning"
	},
	"reverse": {
		"portals": [
			{
				"tag": "portal",
				"domain": "localhost"
			}
		]
	},
	"inbounds": [
		{
			"tag": "cc",
			"port": "nginx转发端口",
			"protocol": "dokodemo-door",
			"settings": {
				"address": "内网ip",
				"port": "内网服务端口",
				"network": "tcp"
			}
		},
		{
			"tag": "cdn",
			"listen": "0.0.0.0",
			"port": "监听端口",
			"protocol": "vmess",
			"settings": {
				"clients": [
					{
						"id": "uuid"
					}
				]
			},
			"streamSettings": {
				"network": "ws",
				"wsSettings": {
					"acceptProxyProtocol": true,
					"path": "/"
				},
				"security": "tls",
				"tlsSettings": {
					"alpn": [
						"h2",
						"http/1.1"
					],
					"certificates": [
						{
							"certificateFile": "/etc/xray/xx.cer",
							"keyFile": "/etc/xray/xx.key"
						}
					]
				}
			},
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls",
					"quic"
				]
			}
		}
	],
	"outbounds": [
		{
			"protocol": "freedom",
			"tag": "direct"
		},
		{
			"protocol": "blackhole",
			"tag": "block"
		}
	],
	"routing": {
		"rules": [
			{
				"type": "field",
				"inboundTag": [
					"cc"
				],
				"outboundTag": "portal"
			},
			{
				"type": "field",
				"inboundTag": [
					"tunnel"
				],
				"domain": [
					"full:localhost"
				],
				"outboundTag": "portal"
			}
		]
	}
}
</code></pre></details>

### 客户端日志

<details><pre><code>
2024/12/10 00:13:53 [Debug] app/log: Logger started
2024/12/10 00:13:53 [Debug] app/router: MphDomainMatcher is enabled for 1 domain rule(s)
2024/12/10 00:13:53 [Warning] core: Xray 24.11.30 started
2024/12/10 00:13:53 [Info] app/dispatcher: taking detour [cdn] for [tcp:localhost:0]
2024/12/10 00:13:53 [Info] transport/internet/websocket: creating connection to tcp:优选ip:443
2024/12/10 00:13:53 [Debug] transport/internet: dialing to tcp:优选ip:443
2024/12/10 00:13:54 [Info] proxy/vmess/outbound: tunneling request to tcp:localhost:0 via 优选ip:443
2024/12/10 00:13:55 [Info] app/proxyman/outbound: app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > websocket: close 1000 (normal)
2024/12/10 00:13:55 [Info] common/mux: unexpected EOF > common/mux: failed to read metadata > io: read/write on closed pipe
2024/12/10 00:13:57 [Info] app/dispatcher: taking detour [cdn] for [tcp:localhost:0]
2024/12/10 00:13:57 [Info] transport/internet/websocket: creating connection to tcp:优选ip:443
2024/12/10 00:13:57 [Debug] transport/internet: dialing to tcp:优选ip:443
2024/12/10 00:13:57 [Info] proxy/vmess/outbound: tunneling request to tcp:localhost:0 via 优选ip:443
2024/12/10 00:13:59 [Info] app/proxyman/outbound: app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > websocket: close 1000 (normal)
</code></pre></details>

### 服务端日志

<details><pre><code>
2024/12/10 00:20:59 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:nginx服务端口
2024/12/10 00:20:59 [Warning] transport/internet/tcp: accepting PROXY protocol
2024/12/10 00:20:59 [Info] transport/internet/websocket: listening TCP(for WS) on 0.0.0.0:监听端口
2024/12/10 00:20:59 [Warning] transport/internet/websocket: accepting PROXY protocol
2024/12/10 00:20:59 [Warning] core: Xray 24.11.30 started
2024/12/10 00:21:00 [Info] [1279776616] proxy/vmess/inbound: received request for tcp:8.8.4.4:443
2024/12/10 00:21:00 [Info] [1279776616] app/dispatcher: sniffed domain: dns.google
2024/12/10 00:21:00 [Info] [1279776616] app/dispatcher: default route for tcp:dns.google:443
2024/12/10 00:21:00 [Info] [1279776616] transport/internet/tcp: dialing TCP to tcp:dns.google:443
2024/12/10 00:21:00 [Info] [1279776616] proxy/freedom: connection opened to tcp:dns.google:443, local endpoint 10.0.0.211:40104, remote endpoint 8.8.4.4:443
2024/12/10 00:21:00 [Info] [1279776616] proxy: CopyRawConn readv
2024/12/10 00:21:01 [Info] [1975973203] proxy/vmess/inbound: received request for tcp:v1.mux.cool:0
2024/12/10 00:21:01 [Info] [1975973203] common/mux: received request for udp:ip:3478
2024/12/10 00:21:01 [Info] [1975973203] app/dispatcher: default route for udp:ip:3478
2024/12/10 00:21:01 [Info] [1975973203] proxy/freedom: connection opened to udp:ip:3478, local endpoint [::]:34635, remote endpoint ip:3478
2024/12/10 00:21:01 [Info] [4257088795] proxy/vmess/inbound: received request for tcp:ip:443
2024/12/10 00:21:01 [Info] [4257088795] app/dispatcher: sniffed domain: alive.github.com
2024/12/10 00:21:01 [Info] [4257088795] app/dispatcher: default route for tcp:alive.github.com:443
2024/12/10 00:21:01 [Info] [4257088795] transport/internet/tcp: dialing TCP to tcp:alive.github.com:443
2024/12/10 00:21:01 [Info] [4257088795] proxy/freedom: connection opened to tcp:alive.github.com:443, local endpoint 10.0.0.211:49912, remote endpoint 服务器ip:443
2024/12/10 00:21:01 [Info] [4257088795] proxy: CopyRawConn readv
2024/12/10 00:21:02 [Info] [4130047647] proxy/vmess/inbound: received request for tcp:localhost:0
2024/12/10 00:21:02 [Info] [4130047647] app/dispatcher: default route for tcp:localhost:0
2024/12/10 00:21:02 [Info] [4130047647] transport/internet/tcp: dialing TCP to tcp:localhost:0
2024/12/10 00:21:02 [Info] [4130047647] transport/internet/tcp: dialing TCP to tcp:localhost:0
2024/12/10 00:21:02 [Info] [4130047647] transport/internet/tcp: dialing TCP to tcp:localhost:0
2024/12/10 00:21:02 [Info] [4130047647] transport/internet/tcp: dialing TCP to tcp:localhost:0
2024/12/10 00:21:02 [Info] [4130047647] transport/internet/tcp: dialing TCP to tcp:localhost:0
2024/12/10 00:21:03 [Info] [4130047647] app/proxyman/outbound: app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: failed to open connection to tcp:localhost:0 > common/retry: [dial tcp [::1]:0: connect: connection refused] > common/retry: all retry attempts failed
2024/12/10 00:21:03 [Info] [4130047647] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > io: read/write on closed pipe
2024/12/10 00:21:06 [Info] [2213580123] proxy/vmess/inbound: received request for tcp:localhost:0
2024/12/10 00:21:06 [Info] [2213580123] app/dispatcher: default route for tcp:localhost:0
2024/12/10 00:21:06 [Info] [2213580123] transport/internet/tcp: dialing TCP to tcp:localhost:0
2024/12/10 00:21:06 [Info] [2213580123] transport/internet/tcp: dialing TCP to tcp:localhost:0
2024/12/10 00:21:06 [Info] [2213580123] transport/internet/tcp: dialing TCP to tcp:localhost:0
2024/12/10 00:21:06 [Info] [3209071237] proxy/vmess/inbound: received request for tcp:ip:443
2024/12/10 00:21:06 [Info] [3209071237] proxy: CopyRawConn readv
2024/12/10 00:21:06 [Info] [2213580123] transport/internet/tcp: dialing TCP to tcp:localhost:0
2024/12/10 00:21:06 [Info] [2213580123] transport/internet/tcp: dialing TCP to tcp:localhost:0
2024/12/10 00:21:06 [Info] [1180297951] proxy/dokodemo: received request for 127.0.0.1:36470
2024/12/10 00:21:06 [Info] [1180297951] app/dispatcher: taking detour [portal] for [tcp:内网ip:内网服务端口]
2024/12/10 00:21:06 [Info] [1180297951] app/reverse: failed to process reverse connection > app/reverse: empty worker list
2024/12/10 00:21:06 [Info] [1180297951] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2024/12/10 00:21:07 [Info] [2213580123] app/proxyman/outbound: app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: failed to open connection to tcp:localhost:0 > common/retry: [dial tcp [::1]:0: connect: connection refused] > common/retry: all retry attempts failed
2024/12/10 00:21:07 [Info] [2213580123] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > io: read/write on closed pipe
2024/12/10 00:21:10 [Info] [1775880316] proxy/vmess/inbound: received request for tcp:localhost:0
2024/12/10 00:21:10 [Info] [1775880316] app/dispatcher: default route for tcp:localhost:0
2024/12/10 00:21:10 [Info] [1775880316] transport/internet/tcp: dialing TCP to tcp:localhost:0
2024/12/10 00:21:10 [Info] [1775880316] transport/internet/tcp: dialing TCP to tcp:localhost:0
2024/12/10 00:21:10 [Info] [1775880316] transport/internet/tcp: dialing TCP to tcp:localhost:0
2024/12/10 00:21:10 [Info] [1775880316] transport/internet/tcp: dialing TCP to tcp:localhost:0
2024/12/10 00:21:10 [Info] [1775880316] transport/internet/tcp: dialing TCP to tcp:localhost:0
</code></pre></details>

**Comment by RPRX** [comment]
反向代理能不能用与 CDN 无关，目前没有其他人报告反向代理坏了，先在本地尝试最简配置反向代理
