### ISSUE TITLE
[Feature Request] Add stun protocol

### ISSUE THREAD

**Issue by deepsm0ke** [XTLS/Xray-core#4139]
Add stun protocol to "protocol" tag in routing rules and take a block action for it. This will allow webrtc stun to be blocked to prevent webrtc public ip leak.

### Config :

![Screenshot_20241210_023457_Chrome](https://github.com/user-attachments/assets/fcd3fe80-0cfe-4c21-a217-7f226debe3d0)

**Comment by RPRX** [comment]
可以有，但浏览器设代理的话 webrtc 似乎不会被代理，也就是说不会经过 core

**Comment by Fangliding** [comment]
这有锤子用 漏webrtc的原因是webrtc不走系统代理 根本不进核心才泄露 如果是被透明代理的话也不存在泄露问题 顶多泄露一个local address 这也和stun没关系 本来就能拿到的
