### ISSUE TITLE
[Feature] Routing API

### ISSUE THREAD

**Issue by ghost** [XTLS/Xray-core#414]
## 增加动态调整路由的API

```
 rpc AddRule(AddRuleRequest) returns (AddRuleResponse){}
 rpc AlterRule(AlterRoutingRuleRequest) returns (AlterRuleResponse){}
 rpc RemoveRule(RemoveRoutingRuleRequest) returns (RemoveRuleResponse){}
 rpc SetRules(repeated RoutingRule) returns (){}
 rpc GetRules() returns (repeated RoutingRule){}

 rpc AddBalancer(AddBalancerRequest) returns (AddBalancerResponse){}
 rpc AlterBalancer(AlterBalancerRequest) returns (AlterBalancerResponse){}
 rpc RemoveBalancer(RemoveBalancerRequest) returns (RemoveBalancerResponse){} 
 rpc GetBalancers() returns (repeated BalancingRule){}
```
- AddRuleRequest中加入指定index字段，不指定则append到最后

### draft 1

在 https://github.com/XTLS/Xray-core/pull/412 中，@tat5522 引入了的 6 个API ：

``` 
 rpc AddRoutingRule(AddRoutingRuleRequest) returns (AddRoutingRuleResponse){}
 rpc AlterRoutingRule(AlterRoutingRuleRequest) returns (AlterRoutingRuleResponse){}
 rpc RemoveRoutingRule(RemoveRoutingRuleRequest) returns (RemoveRoutingRuleResponse){}
 rpc AddBalancingRule(AddBalancingRuleRequest) returns (AddBalancingRuleResponse){}
 rpc AlterBalancingRule(AlterBalancingRuleRequest) returns (AlterBalancingRuleResponse){}
 rpc RemoveBalancingRule(RemoveBalancingRuleRequest) returns (RemoveBalancingRuleResponse){} 
```

此方式可以调整任意一个路由规则，但是需要为每一条路由引入 Tag。
此方案可能需要添加几个借口获取 BalancingRules 与 RoutingRules。
此方案的 `AddRoutingRule` 还需要考虑添加规则的位置。

### draft 2

``` 
 rpc SetRules(repeated RoutingRule) returns (){}
 rpc GetRules() returns (repeated RoutingRule){}
 rpc SetBalancer(BalancingRule) returns (){}
 rpc GetBalancers() returns (repeated BalancingRule){}
```

与方案1不同，方案二选择修改整个路由规则，无需为每个路由添加tag。
在一定程度上，所有路由规则是一个整体。因此我认为，修个整个路由规则更加合理。

希望能够与 @DuckSoft @2dust @yuhan6665 @CerteKim 等第三方客户端作者共同确定此接口。

**Comment by rurirei** [comment]
> 此方式可以调整任意一个路由规则，但是需要为每一条路由引入 Tag

former agreed as it is similar to v2ray/xray routing conf in personally.

**Comment by tat5522** [comment]
> 此方式可以调整任意一个路由规则，但是需要为每一条路由引入 Tag。
通过此方案可以很容易的控制路由规则，无控制路由规则需求时`RuleObject`中无需带入Tag属性，与现有Config没有变化。
此方案使用者只需做好对应的关系映射采用Tag进行控制。

> 在一定程度上，所有路由规则是一个整体。因此我认为，修个整个路由规则更加合理。
此方案由于没有Tag属性，控制时需要对所有路由规则进行遍历找到所需修改的路由规则再修改。
个人认为此方案对于使用者提升了复杂度。

**Comment by JimhHan** [comment]
@tat5522 

将二者合并？
```
 rpc AddRule(AddRuleRequest) returns (AddRuleResponse){}
 rpc AlterRule(AlterRoutingRuleRequest) returns (AlterRuleResponse){}
 rpc RemoveRule(RemoveRoutingRuleRequest) returns (RemoveRuleResponse){}
 rpc SetRules(repeated RoutingRule) returns (){}
 rpc GetRules() returns (repeated RoutingRule){}

 rpc AddBalancer(AddBalancerRequest) returns (AddBalancerResponse){}
 rpc AlterBalancer(AlterBalancerRequest) returns (AlterBalancerResponse){}
 rpc RemoveBalancer(RemoveBalancerRequest) returns (RemoveBalancerResponse){} 
 rpc GetBalancers() returns (repeated BalancingRule){}
```

另：现在的 `AddRoutingRule` 实为 `AppendRoutingRule`，是否有必要修改？

**Comment by tat5522** [comment]
> ```
>  rpc AddRule(AddRuleRequest) returns (AddRuleResponse){}
>  rpc AlterRule(AlterRoutingRuleRequest) returns (AlterRuleResponse){}
>  rpc RemoveRule(RemoveRoutingRuleRequest) returns (RemoveRuleResponse){}
>  rpc SetRules(repeated RoutingRule) returns (){}
>  rpc GetRules() returns (repeated RoutingRule){}
> 
>  rpc AddBalancer(AddBalancerRequest) returns (AddBalancerResponse){}
>  rpc AlterBalancer(AlterBalancerRequest) returns (AlterBalancerResponse){}
>  rpc RemoveBalancer(RemoveBalancerRequest) returns (RemoveBalancerResponse){} 
>  rpc GetBalancers() returns (repeated BalancingRule){}
> ```

两者合并挺好。

> 另：现在的 `AddRoutingRule` 实为 `AppendRoutingRule`，是否有必要修改？

保持`AddRoutingRule`是为了与`HandlerService`风格保持一致。确实`AppendRoutingRule`更符合实际。

**Comment by JimhHan** [comment]
或许可以修改 `AddRoutingRule`，使其将新规则添加到某个位置？

**Comment by tat5522** [comment]
> 或许可以修改 `AddRoutingRule`，使其将新规则添加到指定位置？

`AddRuleRequest`中加入指定index位置，不指定则append到最后

**Comment by JimhHan** [comment]
好的。

@rprx @AkinoKaede 是否还有其他补充？

**Comment by AkinoKaede** [comment]
`GetRules()` 是获取所有规则吗，或许可以增加一个 `GetRule()`，通过 tag 获取单条规则。

**Comment by tat5522** [comment]
> `GetRules()` 是获取所有规则吗，或许可以增加一个 `GetRule()`，通过 tag 获取单条规则。

可以增加，只返回单条规则不返回index。

**Comment by tat5522** [comment]
@JimhHan 

我在尝试添加GetRules相关API，遇到了一个问题。

RoutingObject在初始化的时候，Domain如果带有`geosite:`参数，这个参数在`infra/conf/router.go`中会被`parseDomainRule`方法转为具体的domain内容。而这个内容在后面`app/router/router.go`中被`rule.BuildCondition()`方法转为了`DomainMatcher`对象，这个过程似乎是不可逆转的。

**Comment by tat5522** [comment]
> 另外现有的Domain加载都是由`infra/conf`包来进行加载，函数都是私有方法。API加入的地方是在`app/router`下，外部添加`RoutingRule`时，也无法加载`geosite:`，`geoip:`具体的内容。这一点想询问是否可以把`infra/conf`下的一些方法进行导出给其它的包使用？

打算采用与config一致的结构作为API的参数，这样可以调用`infra/conf/router.go``ParseRule`方法。与config保持一致，API入参也与config一致

**Comment by JimhHan** [comment]
@tat5522 

不需要修改 `infra/conf`，加载 geo*dat 的函数本质为 `proto. Unmarshal`，调用者可以自行解析。

另：我最近会将 `GeoSite` `GeoIP`从 `router` 中剥离，并实现单独的配置解析，您可以先跳过这方面的内容。

**Comment by tat5522** [comment]
> ```
>  rpc AddRule(AddRuleRequest) returns (AddRuleResponse){}
>  rpc AlterRule(AlterRoutingRuleRequest) returns (AlterRuleResponse){}
>  rpc RemoveRule(RemoveRoutingRuleRequest) returns (RemoveRuleResponse){}
> 
>  rpc AddBalancer(AddBalancerRequest) returns (AddBalancerResponse){}
>  rpc AlterBalancer(AlterBalancerRequest) returns (AlterBalancerResponse){}
>  rpc RemoveBalancer(RemoveBalancerRequest) returns (RemoveBalancerResponse){} 
> ```

上述API已实现并提交。

GetXXX相关API因为`rule.BuildCondition()`时被转为了`Matcher`对象，获取不到原有的内容，这部分API暂未实现。

**Comment by tat5522** [comment]
> ```
>  rpc SetRules(repeated RoutingRule) returns (){}
>  rpc GetRules() returns (repeated RoutingRule){}
>  rpc GetRule(GetRoutingRuleRequest) returns (RoutingRule){}
> 
>  rpc GetBalancers() returns (repeated BalancingRule){}
> ```

上述路由API已经实现。其中RoutingRule相关Get API,由于部分`Condition`转换成对应的`Matcher`无法还原成`RoutingRule`，故在转换的时候增加了一个副本保存原有内容。
为了不占用内存，默认不开启副本备份。需要添加环境变量`XRAY_ROUTER_API_GETSET`才可以开启。不开启无法使用GetRuleAPI。
@rprx  @AkinoKaede @JimhHan

**Comment by yuhan6665** [comment]
可以 来一个大佬 整理一下代码
