### ISSUE TITLE
连接报错connect error: REALITY is based on uTLS, please set a client-fingerprint

### ISSUE THREAD

**Issue by xia0sheng** [XTLS/Xray-core#4140]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

服务器ubuntu 24.04  
xray --version
Xray 24.11.30 (Xray, Penetrates Everything.) 98a72b6 (go1.23.3 linux/amd64)
A unified platform for anti-censorship.
本地客户端用的 clash verge 2.0.2

### 重现方式

配置好服务端和客户端后，在clash verge测试延迟的时候，就会报错connect error: REALITY is based on uTLS, please set a client-fingerprint

### 客户端配置

<details><pre><code>
{
    "name": "Azure",
    "type": "vless",
    "server": "xxxx",
    "port": 10086,
    "uuid": "xxxxx",
    "network": "tcp",
    "tls": true,
    "udp": true,
    "flow": "xtls-rprx-vision",
    "reality-opts": {
        "public-key": "GWPTbc9V19ZPZZre2jUpViQyiXyv7cVHRS1PV27RC3k",
        "short-id": "a1b2c3d4e5f6a7b8",
        "client-fingerprint": "chrome"
      }
    }
</code></pre></details>

### 服务端配置

<details><pre><code>
{
  "log": {
    "loglevel": "debug"
  },
  "inbounds": [
    {
      "port": 10086,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "xxxx",
            "flow": "xtls-rprx-vision"
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "show": false,
          "dest": "www.bing.com:443",
          "serverNames": ["www.bing.com"],
          "privateKey": "qHnE0PgcYoeTZaiC4cyKanealw_Z6ApskJTiWyfsfyM",
          "shortIds": ["a1b2c3d4e5f6a7b8"]
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom"
    }
  ]
}
</code></pre></details>

### 客户端日志

<details><pre><code>
connect error: REALITY is based on uTLS, please set a client-fingerprint
</code></pre></details>

### 服务端日志

<details><pre><code>
服务端  [Info] transport/internet/tcp: REALITY: processed invalid connection
</code></pre></details>

**Comment by RPRX** [comment]
非 Xray-core 问题

**Comment by xia0sheng** [comment]
> 非 Xray-core 问题

确实不是xray的问题，小火箭可以连上

**Comment by wyx2685** [comment]
> > 非 Xray-core 问题
> 
> 确实不是xray的问题，小火箭可以连上

这是在委婉的说您的技能水平存在问题，您能稍微不要太搞笑嘛我受不了了

**Comment by xia0sheng** [comment]
> > > 非 Xray-core 问题
> > 
> > 
> > 确实不是xray的问题，小火箭可以连上
> 
> 这是在委婉的说您的技能水平存在问题，您能稍微不要太搞笑嘛我受不了了

确实技能水平存在问题哈，因为以前没用过xray，第一次弄，有点不熟悉哈，不过现在问题解决了

**Comment by xia0sheng** [comment]
解决了，应该是少了个servername参数，和一些参数位置存放
clash verge 全局扩展脚本的正确配置如下：
{
    "name": "Azure_Vless",
    "type": "vless",
    "server": "IP",
    "port": 10086,
    "uuid": "uuid",
    "network": "tcp",
    "tls": true,
    "udp": true,
    "tfo": false,
    "flow": "xtls-rprx-vision",
    "skip-cert-verify": false,
    "reality-opts": {
        "public-key": "public-key",
        "short-id": "short-id"        
      },
    "client-fingerprint": "chrome",
    "servername": "www.bing.com"
    }

**Comment by RPRX** [comment]
~~不是，其实我的意思只是这个是你使用 Clash.Meta 的问题，与 Xray-core 无关~~
