### ISSUE TITLE
路由与freedom中DNS解析不一致

### ISSUE THREAD

**Issue by HeXis-YS** [XTLS/Xray-core#4146]
假设要通过IP规则进行分流。对于通过DNS查询到的所有IP，只要其中有一个符合条件则匹配成功。
https://github.com/XTLS/Xray-core/blob/9cb6816383ddc6580f5a0c38a8f8df2aacf9397b/app/router/condition.go#L145-L151
但是对于需要单独解析的出站（例如freedom），会再次进行DNS查询，然后从结果中随机选择一个。
https://github.com/XTLS/Xray-core/blob/9cb6816383ddc6580f5a0c38a8f8df2aacf9397b/transport/internet/dialer.go#L155-L163
考虑以下情况：通过DNS查询一个域名返回了2个中国IP和2个美国IP（尽管这种情况几乎不存在）。根据用户配置的规则，由于优先匹配到了中国IP，所以路由模块把这个连接分流到直连出站。但是在出站时随机到了一个美国IP，导致连接非常缓慢，甚至无法连接。
无论如何，如果设置了路由规则，在连接时也应遵循规则。即使上述情况很难遇到，重复查询也可能会返回不同的IP，并浪费一次查询的时间。

**Comment by Fangliding** [comment]
一般来说期望是解析出来的IP是不会飘的 文中提到的情况过于刁钻 也可以用expectIPs处理
至于浪费查询时间这是不会的 因为都是调用DNS模块的原因第二次查询会直接从cache取得查询结果
至于改是不太可能改的 ray的内部处理一直都是只支持一个dest(ip or domain) 这些路由用IP都是附加上去的额外信息 如果路由模块就解析成IP 那出站的IP64 prefer怎么办

**Comment by HeXis-YS** [comment]
感谢回复。你说的确实有道理，issue先关了
~~看了更多代码之后感觉ray对DNS缓存疑似有些过于依赖了~~
不过按照我个人的想法，应该以路由规则优先。如果是域名规则匹配的，那么喜欢v4还是v6就是出站决定了。如果是IPv4规则匹配的，即使出站prefer v6，也应该使用v4的IP。否则路由规则就失去意义了~~因为出站已经凌驾于路由规则之上了~~。
