### ISSUE TITLE
limit user bandwidth 

### ISSUE THREAD

**Issue by e3lz** [XTLS/Xray-core#415]
can anyone help me i want to limit a users bandwidth .

**Comment by rurirei** [comment]
v2fly/v2ray-core#403

**Comment by e3lz** [comment]
is it possible to set a limit to how much user can use , limit can only do so little , i want to offer full speed but limited bandwidth

**Comment by e3lz** [comment]
also there is no limit on how many users can use one username at same time , these futures where in OpenVPN like systems but not in proxy

**Comment by AkinoKaede** [comment]
PR Welcome

**Comment by AkinoKaede** [comment]
Try to use #444.  
https://github.com/XTLS/Xray-core/actions/runs/690459051

**Comment by TL3E** [comment]
@AkinoKaede Will this feature be merged with xray? We're all waiting.
