### ISSUE TITLE
0e2304c 开始仅配置dns，而没有配置fakedns启动失败

### ISSUE THREAD

**Issue by o0HalfLife0o** [XTLS/Xray-core#4155]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [ ] 问题在 Release 最新的版本上可以成功复现

### 描述

freebsd amd64更新到[0e2304c](https://github.com/XTLS/Xray-core/actions/runs/12267663202) 后启动失败，提示
`Failed to start: main: failed to create server > core: not all dependencies are resolved.`
@yuhan6665 

### 服务端配置

<details><pre><code>
{
    "log": {
        "loglevel": "debug",
        "error": "xray_error.log"
    },
    "inbounds":[
        {
            "port":15450,
            //"listen":"@ws.sock,0666",
            "protocol":"vless",
            "settings":{
                "clients":[
                    {
                        "id":"uuid",
                        "level":0
                    }
                ],
                "decryption":"none"
            },
            "streamSettings":{
                "network":"ws",
                "security":"none",
                "wsSettings":{
                    //"acceptProxyProtocol": true,
                    "path":"/uuid-ws"
                }
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls",
                    "quic"
                ]
            },
            "sockopt": {
                "tcpFastOpen": true,
                "tcpMptcp": true,
                "tcpNoDelay": true
            }
        },
        {
            "listen":"@xhttp.sock,0666",
            "protocol":"vless",
            "settings":{
                "clients":[
                    {
                        "id":"uuid",
                        "level":0
                    }
                ],
                "decryption": "none"
            },
            "streamSettings":{
                "network":"xhttp",
                "security": "none",
                "xhttpSettings": {
                    //"acceptProxyProtocol": true,
                    "path": "/uuid-sh"
                }
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls",
                    "quic"
                ]
            },
            "sockopt": {
                "tcpFastOpen": true,
                "tcpMptcp": true,
                "tcpNoDelay": true
            }
        }
    ],
    "dns": {
        "servers": [
            "8.8.8.8",
            "1.1.1.1", 
            "9.9.9.9"
        ]
    },
    "outbounds": [
        {
            "tag": "WARP",
            "protocol": "wireguard",
            "settings": {
                "secretKey": "",
                "address": [
                    "/128",
                    "172.16.0.2/32"
                ],
                "peers": [
                    {
                        "publicKey": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
                        "endpoint": "162.159.193.10:2408",
                        "keepAlive": 60
                    }
                ],
                "reserved": [84, 226, 72],
                "mtu": 1420  //1280
            }
        },
        {
            "tag": "direct-out",
            "protocol": "freedom",
            "streamSettings":{
                "sockopt": {
                    "domainStrategy": "UseIPv4"
                }
            }
        }
    ],
    "routing": {
        "domainStrategy": "IPOnDemand",
        "rules": [
            {
                "outboundTag": "WARP",
                "domain":[
                    "domain:openai.com",
                    "domain:chatgpt.com",
                    "domain:ai.com",
                    "domain:netflix.com",
                    "domain:gemini.google.com"
                ]
            },
            {
                "outboundTag": "direct-out",
                "ip": [
                    "0.0.0.0/0"
                ]
            }
        ]
    }
}
</code></pre></details>

### 服务端日志

<details><pre><code>
Xray 24.11.30 (Xray, Penetrates Everything.) 8cd9a74 (go1.23.4 freebsd/amd64)
A unified platform for anti-censorship.
2024/12/11 17:36:18 [Info] infra/conf/serial: Reading config: &{Name:./config.json Format:json}
2024/12/11 17:36:18 [Debug] app/log: Logger started
2024/12/11 17:36:18 [Info] app/dns: DNS: created UDP client initialized for 8.8.8.8:53
2024/12/11 17:36:18 [Info] app/dns: DNS: created UDP client initialized for 1.1.1.1:53
2024/12/11 17:36:18 [Info] app/dns: DNS: created UDP client initialized for 9.9.9.9:53
2024/12/11 17:36:18 [Debug] app/router: MphDomainMatcher is enabled for 5 domain rule(s)
Failed to start: main: failed to create server > core: not all dependencies are resolved.
</code></pre></details>

**Comment by RPRX** [comment]
@o0HalfLife0o 就是说有配置 DNS 就会出现这个错误吗

**Comment by RPRX** [comment]
> 试下了dns里面外面写没写fakedns，启动时都不会报错了

~~我也试出来了~~

**Comment by RPRX** [comment]
~~总之这些 register 什么的我明年就给它干掉，太踏马难维护了，我看着都是懵逼的~~

**Comment by yuhan6665** [comment]
> @RPRX fakedns配置项还是有点问题，如果只配置了ipPool，而没有配置poolSize，就会启动失败，但是根据文档，poolSize是有默认值的
> 
> ```
>   "fakedns": {
>     "ipPool": "198.18.0.0/15"
>   }
> ```

这块是这样的 如果用户无配置 那么有一个默认的 fakedns 配置
但是如果你写了 ipPool 目前并没有默认的 poolSize 导致 poolSize = 0 所以启动失败
还有 poolSize 必须小于 ipPool 可分配 IP 总数 否则一直使用会导致 IP 池用完 所以如果配置检测到 poolSize 过大也会启动失败

**Comment by yuhan6665** [comment]
> ~总之这些 register 什么的我明年就给它干掉，太踏马难维护了，我看着都是懵逼的~

Guys, please don't delete dependency injection. I know, DI can have many issues: registration order, circular dependencies, slowness. But you just need to solve these issues and it is a must in my opinion as *Ray is not a pet project. You need proper architecture to support more features and extensions.
For one example here,
https://github.com/XTLS/Xray-core/blob/7d0a80b501d430542ae851043de3da4d68335325/core/xray.go#L200
You should NEVER call New() on different features in your code logic. That's why *Ray has another layer of Interface ConfigCreator. Imagine this, I can substitute a fake implementation of DNS module (to return success or failures as I want) or a fake Observatory module (without waiting for it to send real request)
DI make it possible to stub these in your test, however you want it.
