### ISSUE TITLE
在安卓脚本上运行报错，使用v2ray则正常

### ISSUE THREAD

**Issue by xwwbest** [XTLS/Xray-core#416]
2021/03/21 07:21:14 [Warning] failed to handler mux client connection > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://123.com/):  > dial tcp: lookup 123.com on [::1]:53: read udp [::1]:42595->[::1]:53: read: connection refused transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://123.com/):  > dial tcp: lookup 123.com on [::1]:53: read udp [::1]:37005->[::1]:53: read: connection refused transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://123.com/):  > dial tcp: lookup 123.com on [::1]:53: read udp [::1]:40270->[::1]:53: read: connection refused transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://123.com/):  > dial tcp: l

用的是ws tls cdn，日志里的域名信息改为了123. com

**Comment by xwwbest** [comment]
https://github.com/v2ray/v2ray-core/issues/1909

是不是这个的问题

**Comment by JimhHan** [comment]
@xwwbest 

已知问题，已经修复。请将 [sockopt](https://xtls.github.io/Xray-docs-next/config/transport.html#sockoptobject) 中的 `DomainStrategy` 选项设置为 `UseIP`，并设置内置 DNS 服务器。

可以参考一下 [曦曦的Xray4Magisk](https://github.com/CerteKim/Xray4Magisk/tree/master/xray/etc/confs)， ~~或者直接用 Xray4Magisk。~~
