### ISSUE TITLE
密西根大学-基于嵌套的 TLS 握手指纹识别混淆代理流量

### ISSUE THREAD

**Issue by egg1234** [XTLS/Xray-core#4168]
Diwen Xue, University of Michigan; Michalis Kallitsis, Merit Network, Inc.;
Amir Houmansadr, UMass Amherst; Roya Ensafi, University of Michigan

This paper is included in the Proceedings of the
33rd USENIX Security Symposium
August 14–16, 2024 • Philadelphia, PA, USA

https://www.usenix.org/conference/usenixsecurity24/presentation/xue-fingerprinting
https://www.usenix.org/system/files/usenixsecurity24-xue-fingerprinting.pdf
https://www.usenix.org/system/files/sec24summer-prepub-465-xue.pdf

中文简单译文
https://web.archive.org/web/20241215173726/https://www.buaq.net/go-282273.html

**Comment by Fangliding** [comment]
火星救援
