### ISSUE TITLE
[Feature] Reverse API

### ISSUE THREAD

**Issue by tat5522** [XTLS/Xray-core#417]
计划增加反向代理(`ReverseObject`)的API控制。预加入以下API
```
  rpc AddBridge(AddBridgeRequest) returns (AddBridgeResponse){}
  rpc RemoveBridge(RemoveBridgeRequest) returns (RemoveBridgeResponse){}
  rpc AddPortal(AddPortalRequest) returns (AddPortalResponse){}
  rpc RemovePortal(RemovePortalRequest) returns (RemovePortalResponse){}
```
由于Reverse运行的特殊性，故不支持动态修改`Domain`参数

添加此API后配合[RoutingAPI](https://github.com/XTLS/Xray-core/issues/414)可以做到动态加入无公网IP的设备做出口代理和内网穿透。

@JimhHan @rprx @AkinoKaede

**Comment by tat5522** [comment]
>
>rpc GetBridges(GetBridgesRequest) returns (GetBridgesResponse){}
>rpc GetPortals(GetPortalsRequest) returns (GetPortalsResponse){}
>

新增并实现以上两个接口，用于获取当前的反向代理内容。

**Comment by nbwbcn** [comment]
any instructions or documentation? TAT

**Comment by nbwbcn** [comment]
正向和反向能不能共存呢？Can forward proxy and reverse proxy work together?

**Comment by 2512500960** [comment]
这个功能增加了吗
