### ISSUE TITLE
xhttp configuration not working when max option is enabled

### ISSUE THREAD

**Issue by rasa68** [XTLS/Xray-core#4172]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [ ] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

In version 15.12.24, when the max option is enabled in the client, the xhttp configuration does not work!

### Reproduction Method

This was not a problem in the previous version.

### Client config

<details><pre><code>

</code></pre></details>

### Server config

<details><pre><code>

</code></pre></details>

### Client log

<details><pre><code>

</code></pre></details>

### Server log

<details><pre><code>

</code></pre></details>

**Comment by Fangliding** [comment]
没有任何信息

**Comment by rasa68** [comment]
I have an xhttp config with reality tls.
In the previous version the kernel worked without any problems, but in version 15.12.24 if max is enabled in the client the config does not work. When I disable max the config works again.
