### ISSUE TITLE
BUG in Xray-core v24.12.15

### ISSUE THREAD

**Issue by chitoz1300** [XTLS/Xray-core#4176]
Hello, I have encountered a bug in the latest version of Xray-core v24.12.15.
There is an issue with the HTTP configuration, which continuously displays the following warning:

```
2024/12/17 04:36:25 [Warning] common/errors: This feature WebSocket transport (with ALPN http/1.1, etc.) is deprecated and being migrated to XHTTP H2 & H3. Please update your config(s) according to release note and documentation before removal.
```
Furthermore, when this warning appears, the connection is completely lost.
In contrast, in Xray-core v24.11.30, this warning does not occur, and the connection remains stable.
Please fix this, thanks!

**Comment by fraybyl** [comment]
Read what it says
> is deprecated and being migrated to XHTTP H2 & H3. Please update your config(s) according to release note and documentation before removal.

**Comment by Fangliding** [comment]
虽然这个提示很无聊但它只是在解析config的时候抛出一行字而已 和后续ws没有任何关系 如果仍坚信有问题请按模板提交问题

**Comment by rosebe** [comment]
The problem may occur as mentioned in https://github.com/XTLS/Xray-core/pull/4177.
