### ISSUE TITLE
https inbound + vison reality outbound = ERR_SSL_PROTOCOL_ERROR (remote error: tls: bad record MAC)

### ISSUE THREAD

**Issue by buptnarc** [XTLS/Xray-core#4180]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

用了老版本和最新的12.15，windows10，chrome/edge，zero omega插件

代理链：远程服务器（ubuntu x64，xray-vison reality服务端）- 本地服务器（ubuntu x64，xray-vison reality客户端）- windows主机（浏览器+zero omega插件）

inbound是https，outbound是vison reality，报ERR_SSL_PROTOCOL_ERROR，去掉密码也不行

outbound换其他的，没问题

同一套配置，去掉inbound的tls设置(相当于只用http)，outbound不变（vison reality）也没问题

唯独https+vison reality有问题

### Reproduction Method

inbound设置https，inbound设置vison reality

### Client config

<details><pre><code>
"inbounds": [
        {
            "port": 1234,
            "listen": "0.0.0.0",
            "protocol": "http",
            "settings": {
                "auth": "password",
                "accounts": [
                    {
                        "user": "abc",
                        "pass": "123456"
                    }
                ],
                "allowTransparent": false
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                    "serverName": "proxy.abc.com",
                    "alpn": [
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "/data/fullchain.cer",
                            "keyFile": "/data/abc.com.key"
                        }
                    ]
                }
            }
        }
    ],
    "outbounds": [
        {
            "tag": "us",
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "us.abc.com",
                        "port": 443,
                        "users": [
                            {
                                "id": "asd",
                                "flow": "xtls-rprx-vision",
                                "encryption": "none"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "reality",
                "realitySettings": {
                    "fingerprint": "chrome",
                    "serverName": "speed.cloudflare.com",
                    "publicKey": "dbfhjbsdaasdnajsdkjanskjdnasasdasd",
                    "shortId": ""
                }
            }
        }
    ],
</code></pre></details>

### Server config

<details><pre><code>
    {
      "port": 443,
      "listen": "0.0.0.0",
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "asdasdasd",
            "email": "reality@abc.com",
            "flow": "xtls-rprx-vision"
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "dest": "speed.cloudflare.com:443",
          "serverNames": [
            "speed.cloudflare.com"
          ],
          "privateKey": "asdasdasdasdasd",
          "shortIds": [
            ""
          ]
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls",
          "quic"
        ]
      },
      "tag": "reality"
    }
</code></pre></details>

### Client log

<details><pre><code>
2024/12/18 16:17:01 [Info] [1295124580] proxy/http: request to Method [CONNECT] Host [collector.github.com:443] with URL [//collector.github.com:443]
2024/12/18 16:17:01 [Info] [1295124580] app/dispatcher: taking detour [us] for [tcp:collector.github.com:443]
2024/12/18 16:17:01 [Info] [1295124580] transport/internet/tcp: dialing TCP to tcp:us.abc.com:443
2024/12/18 16:17:01 [Debug] [1295124580] transport/internet: dialing to tcp:us.abc.com:443
2024/12/18 16:17:01 from 10.1.1.114:55531 accepted //collector.github.com:443 [us -> us]
2024/12/18 16:17:01 [Info] [1295124580] proxy/vless/outbound: tunneling request to tcp:collector.github.com:443 via us.abc.com:443
2024/12/18 16:17:01 [Info] [1295124580] proxy: XtlsFilterTls found tls client hello! 1905
2024/12/18 16:17:01 [Info] [1295124580] proxy: XtlsPadding 1905 166 0
2024/12/18 16:17:02 [Info] [391607722] proxy/http: request to Method [CONNECT] Host [optimizationguide-pa.googleapis.com:443] with URL [//optimizationguide-pa.googleapis.com:443]
2024/12/18 16:17:02 [Info] [391607722] app/dispatcher: taking detour [us] for [tcp:optimizationguide-pa.googleapis.com:443]
2024/12/18 16:17:02 [Info] [391607722] transport/internet/tcp: dialing TCP to tcp:us.abc.com:443
2024/12/18 16:17:02 [Debug] [391607722] transport/internet: dialing to tcp:us.abc.com:443
2024/12/18 16:17:02 from 10.1.1.114:55532 accepted //optimizationguide-pa.googleapis.com:443 [us -> us]
2024/12/18 16:17:02 [Info] [928522427] proxy/http: request to Method [CONNECT] Host [www.google.com:443] with URL [//www.google.com:443]
2024/12/18 16:17:02 [Info] [928522427] app/dispatcher: taking detour [us] for [tcp:www.google.com:443]
2024/12/18 16:17:02 from 10.1.1.114:55533 accepted //www.google.com:443 [us -> us]
2024/12/18 16:17:02 [Info] [928522427] transport/internet/tcp: dialing TCP to tcp:us.abc.com:443
2024/12/18 16:17:02 [Debug] [928522427] transport/internet: dialing to tcp:us.abc.com:443
2024/12/18 16:17:02 [Info] [1295124580] proxy: Xtls Unpadding new block, content 4062 padding 237 command 0
2024/12/18 16:17:02 [Info] [1295124580] proxy: XtlsFilterTls found tls 1.3! 1163 TLS_AES_128_GCM_SHA256
2024/12/18 16:17:02 [Info] [1295124580] proxy: XtlsPadding 64 979 0
2024/12/18 16:17:02 [Info] [1295124580] proxy: XtlsPadding 92 982 2
2024/12/18 16:17:02 [Info] [391607722] proxy/vless/outbound: tunneling request to tcp:optimizationguide-pa.googleapis.com:443 via us.abc.com:443
2024/12/18 16:17:02 [Info] [391607722] proxy: XtlsFilterTls found tls client hello! 2316
2024/12/18 16:17:02 [Info] [391607722] proxy: XtlsPadding 2316 217 0
2024/12/18 16:17:02 [Info] [928522427] proxy/vless/outbound: tunneling request to tcp:www.google.com:443 via us.abc.com:443
2024/12/18 16:17:02 [Info] [928522427] proxy: XtlsFilterTls found tls client hello! 2210
2024/12/18 16:17:02 [Info] [928522427] proxy: XtlsPadding 2210 64 0
2024/12/18 16:17:02 [Info] [1295124580] proxy: Xtls Unpadding new block, content 248 padding 978 command 2
2024/12/18 16:17:02 [Info] [1295124580] proxy: CopyRawConn splice
2024/12/18 16:17:02 [Info] [1295124580] app/proxyman/inbound: connection ends > proxy/http: connection ends > remote error: tls: bad record MAC
2024/12/18 16:17:02 [Info] [391607722] proxy: Xtls Unpadding new block, content 1484 padding 168 command 0
2024/12/18 16:17:02 [Info] [391607722] proxy: XtlsFilterTls inconclusive server hello 1163 58
2024/12/18 16:17:02 [Info] [391607722] proxy: XtlsFilterTls found tls 1.3! 321 TLS_AES_128_GCM_SHA256
2024/12/18 16:17:02 [Info] [391607722] proxy: XtlsPadding 74 1000 0
2024/12/18 16:17:02 [Info] [391607722] proxy: XtlsPadding 92 978 2
2024/12/18 16:17:02 [Info] [928522427] proxy: Xtls Unpadding new block, content 1463 padding 178 command 0
2024/12/18 16:17:02 [Info] [928522427] proxy: XtlsFilterTls inconclusive server hello 1163 58
2024/12/18 16:17:02 [Info] [928522427] proxy: XtlsFilterTls found tls 1.3! 300 TLS_AES_128_GCM_SHA256
2024/12/18 16:17:02 [Info] [928522427] proxy: XtlsPadding 74 1208 0
2024/12/18 16:17:02 [Info] [928522427] proxy: XtlsPadding 92 829 2
2024/12/18 16:17:02 [Info] [391607722] proxy: Xtls Unpadding new block, content 1000 padding 113 command 2
2024/12/18 16:17:02 [Info] [391607722] proxy: CopyRawConn splice
2024/12/18 16:17:02 [Info] [391607722] app/proxyman/inbound: connection ends > proxy/http: connection ends > remote error: tls: bad record MAC
2024/12/18 16:17:02 [Info] [928522427] proxy: Xtls Unpadding new block, content 989 padding 200 command 2
2024/12/18 16:17:02 [Info] [928522427] proxy: CopyRawConn splice
2024/12/18 16:17:02 [Info] [928522427] app/proxyman/inbound: connection ends > proxy/http: connection ends > remote error: tls: bad record MAC

</code></pre></details>

### Server log

<details><pre><code>
2024/12/18 03:29:48 [Warning] core: Xray 24.12.15 started
2024/12/18 03:29:59 [Info] [2091049641] proxy/vless/inbound: firstLen = 1186
2024/12/18 03:29:59 [Info] [2091049641] proxy/vless/inbound: received request for tcp:www.google.com:443
2024/12/18 03:29:59 [Info] [2091049641] proxy: Xtls Unpadding new block, content 2218 padding 176 command 0
2024/12/18 03:29:59 [Info] [2091049641] proxy: XtlsFilterTls found tls client hello! 1106
2024/12/18 03:29:59 [Info] [2091049641] app/dispatcher: sniffed domain: www.google.com
2024/12/18 03:29:59 [Info] [2091049641] app/dispatcher: taking detour [direct] for [tcp:www.google.com:443]
2024/12/18 03:29:59 [Info] [2091049641] transport/internet/tcp: dialing TCP to tcp:www.google.com:443
2024/12/18 03:29:59 [Debug] [2091049641] transport/internet: dialing to tcp:www.google.com:443
2024/12/18 03:29:59 from 114.114.114.114:44794 accepted tcp:www.google.com:443 [reality -> direct] email: reality@abc.com
2024/12/18 03:29:59 [Info] [4020457082] proxy/vless/inbound: firstLen = 1186
2024/12/18 03:29:59 [Info] [4020457082] proxy/vless/inbound: received request for tcp:optimizationguide-pa.googleapis.com:443
2024/12/18 03:29:59 [Info] [4020457082] proxy: Xtls Unpadding new block, content 2220 padding 6 command 0
2024/12/18 03:29:59 [Info] [4020457082] proxy: XtlsFilterTls found tls client hello! 1089
2024/12/18 03:29:59 [Info] [4020457082] app/dispatcher: sniffed domain: optimizationguide-pa.googleapis.com
2024/12/18 03:29:59 [Info] [2091049641] proxy/freedom: connection opened to tcp:www.google.com:443, local endpoint 1.1.1.1:60948, remote endpoint 142.250.217.132:443
2024/12/18 03:29:59 [Info] [4020457082] app/dispatcher: taking detour [direct] for [tcp:optimizationguide-pa.googleapis.com:443]
2024/12/18 03:29:59 [Info] [4020457082] transport/internet/tcp: dialing TCP to tcp:optimizationguide-pa.googleapis.com:443
2024/12/18 03:29:59 [Debug] [4020457082] transport/internet: dialing to tcp:optimizationguide-pa.googleapis.com:443
2024/12/18 03:29:59 from 114.114.114.114:51446 accepted tcp:optimizationguide-pa.googleapis.com:443 [reality -> direct] email: reality@abc.com
2024/12/18 03:29:59 [Info] [2091049641] proxy: XtlsFilterTls found tls 1.3! 1467 TLS_AES_128_GCM_SHA256
2024/12/18 03:29:59 [Info] [2091049641] proxy: XtlsPadding 1467 15 0
2024/12/18 03:29:59 [Info] [4020457082] proxy/freedom: connection opened to tcp:optimizationguide-pa.googleapis.com:443, local endpoint 1.1.1.1:55444, remote endpoint 142.250.72.138:443
2024/12/18 03:29:59 [Info] [4020457082] proxy: XtlsFilterTls found tls 1.3! 1484 TLS_AES_128_GCM_SHA256
2024/12/18 03:29:59 [Info] [4020457082] proxy: XtlsPadding 1484 195 0
2024/12/18 03:29:59 [Info] [2091049641] proxy: Xtls Unpadding new block, content 74 padding 1282 command 0
2024/12/18 03:29:59 [Info] [2091049641] proxy: Xtls Unpadding new block, content 92 padding 1097 command 2
2024/12/18 03:29:59 [Info] [2091049641] proxy: CopyRawConn readv
2024/12/18 03:29:59 [Info] [2091049641] proxy: XtlsPadding 997 233 2
2024/12/18 03:29:59 [Info] [4020457082] proxy: Xtls Unpadding new block, content 74 padding 1298 command 0
2024/12/18 03:29:59 [Info] [4020457082] proxy: Xtls Unpadding new block, content 92 padding 905 command 2
2024/12/18 03:29:59 [Info] [4020457082] proxy: CopyRawConn readv
2024/12/18 03:29:59 [Info] [4020457082] proxy: XtlsPadding 1000 103 2
2024/12/18 03:29:59 [Info] [4020457082] proxy: CopyRawConn splice
2024/12/18 03:29:59 [Info] [2091049641] proxy: CopyRawConn splice
2024/12/18 03:30:00 [Info] [3693803701] proxy/vless/inbound: firstLen = 614
2024/12/18 03:30:00 [Info] [3693803701] proxy/vless/inbound: received request for tcp:www.gstatic.com:80
2024/12/18 03:30:00 [Info] [3693803701] proxy: Xtls Unpadding new block, content 28 padding 199 command 1
2024/12/18 03:30:00 [Info] [3693803701] app/dispatcher: sniffed domain: www.gstatic.com
2024/12/18 03:30:00 [Info] [3693803701] app/dispatcher: taking detour [direct] for [tcp:www.gstatic.com:80]
2024/12/18 03:30:00 from 114.114.114.114:51386 accepted tcp:www.gstatic.com:80 [reality -> direct] email: reality@abc.com
2024/12/18 03:30:00 [Info] [3693803701] transport/internet/tcp: dialing TCP to tcp:www.gstatic.com:80
2024/12/18 03:30:00 [Debug] [3693803701] transport/internet: dialing to tcp:www.gstatic.com:80
2024/12/18 03:30:00 [Info] [3693803701] proxy/freedom: connection opened to tcp:www.gstatic.com:80, local endpoint 1.1.1.1:38372, remote endpoint 142.251.40.35:80
2024/12/18 03:30:00 [Info] [3693803701] proxy: XtlsPadding 146 55 0
2024/12/18 03:30:01 [Info] [3693803701] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > context canceled

</code></pre></details>

**Comment by Fangliding** [comment]
dup #4033 这个splice有点小问题

**Comment by yuhan6665** [comment]
特殊用法 自己用环境变量关掉 splice 吧

**Comment by islercn** [comment]
> 关掉 splice

在inbound的settings里增加"splice": false还是会提示ERR_SSL_PROTOCOL_ERROR

**Comment by Fangliding** [comment]
为什么你会觉得有这个设置？

**Comment by islercn** [comment]
> 为什么你会觉得有这个设置？

那请问如何配置能避免此问题？
