### ISSUE TITLE
xhttp 报错 invalid x_padding length:0

### ISSUE THREAD

**Issue by lhbdhr** [XTLS/Xray-core#4183]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

server端报错，无法代理。服务端和客户端都更新到最新了， 2024.12.18
配置：caddy 反代 + vless + xhttp + cdn，其实就是以前ws那一套，只是ws换成了xhttp

server启动是没错误的，客户端一发请求，服务端日志就多一条 **invalid x_padding length:0**
最关键的是，我的caddy收到的请求是有 padding 的。

caddy日志
```
{"level":"debug","ts":"2024/12/19 04:14:13","logger":"http.handlers.reverse_proxy","msg":"upstream roundtrip","upstream":"127.0.0.1:1234","duration":0.000859591,"request":{"remote_ip":"xxx.xxx.xxx.xxx","remote_port":"28256","client_ip":"xxx.xxx.xxx.xxx","proto":"HTTP/1.1","method":"GET","host":"example.com","uri":"/whatismyip/f3ab5ba1-5e3c-4c7b-86a2-f5006a30a56b","headers":{"Accept-Encoding":["gzip"],"User-Agent":["Amazon CloudFront"],"X-Forwarded-Host":["example.com"],"X-Amz-Cf-Id":["GhVgJ4Qz5UNRjmGvD_jNWYB8MezULNkheu4wX6CjEjnsos3rGgHC5Q=="],"X-Forwarded-Proto":["https"],"X-Forwarded-For":["xxx.xxx.xxx.xxx"],"Via":["2.0 xxxxxxxxxxxxxxxxxxx.cloudfront.net (CloudFront)"]},"tls":{"resumed":true,"version":771,"cipher_suite":49195,"proto":"","server_name":"example.com"}},"headers":{"Content-Length":["0"],"Access-Control-Allow-Methods":["GET, POST"],"Access-Control-Allow-Origin":["*"],"X-Padding":["00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"],"Date":["Thu, 19 Dec 2024 04:14:13 GMT"]},"status":400}
{"level":"debug","ts":"2024/12/19 04:14:13","logger":"events","msg":"event","name":"tls_get_certificate","id":"c0c52f07-e508-412b-b214-229168ccaa79","origin":"tls","data":{"client_hello":{"CipherSuites":[49196,49200,49195,49199,49188,49192,49162,49172,49187,49191,49161,49171,157,156,53,60,47,10,4,255],"ServerName":"example.com","SupportedCurves":[23,29,24],"SupportedPoints":"AA==","SignatureSchemes":[1025,1281,1537,769,1027,1283,1539,771,513,515],"SupportedProtos":["h2"],"SupportedVersions":[771,770,769],"RemoteAddr":{"IP":"xxx.xxx.xxx.xxx","Port":13826,"Zone":""},"LocalAddr":{"IP":"xxx.xxx.xxx.xxx","Port":41969,"Zone":""}}}}
{"level":"debug","ts":"2024/12/19 04:14:13","logger":"tls.handshake","msg":"choosing certificate","identifier":"example.com","num_choices":1}
{"level":"debug","ts":"2024/12/19 04:14:13","logger":"tls.handshake","msg":"default certificate selection results","identifier":"example.com","subjects":["example.com"],"managed":true,"issuer_key":"acme-v02.api.letsencrypt.org-directory","hash":"166dea7195224b232f24f7fe17c37c2bbcc387c8d8de2181756724f242789137"}
{"level":"debug","ts":"2024/12/19 04:14:13","logger":"tls.handshake","msg":"matched certificate in cache","remote_ip":"xxx.xxx.xxx.xxx","remote_port":"13826","subjects":["example.com"],"managed":true,"expiration":"2025/03/19 01:21:52","hash":"166dea7195224b232f24f7fe17c37c2bbcc387c8d8de2181756724f242789137"}
{"level":"debug","ts":"2024/12/19 04:14:13","logger":"http.handlers.reverse_proxy","msg":"selected upstream","dial":"127.0.0.1:1234","total_upstreams":1}
{"level":"debug","ts":"2024/12/19 04:14:13","logger":"http.handlers.reverse_proxy","msg":"upstream roundtrip","upstream":"127.0.0.1:1234","duration":0.000917904,"request":{"remote_ip":"xxx.xxx.xxx.xxx","remote_port":"8646","client_ip":"xxx.xxx.xxx.xxx","proto":"HTTP/1.1","method":"GET","host":"example.com","uri":"/whatismyip/0be21cea-cbb5-4737-9e00-684de26e2235","headers":{"Via":["2.0 xxxxxxxxxxxxxxxxxxx.cloudfront.net (CloudFront)"],"Accept-Encoding":["gzip"],"User-Agent":["Amazon CloudFront"],"X-Forwarded-Host":["example.com"],"X-Amz-Cf-Id":["RvWSX5DwemQp4rSB1WlpkwLqmeLarme54Yr5vau_zUUMqraPL2OHwg=="],"X-Forwarded-Proto":["https"],"X-Forwarded-For":["xxx.xxx.xxx.xxx"]},"tls":{"resumed":true,"version":771,"cipher_suite":49195,"proto":"","server_name":"example.com"}},"headers":{"Access-Control-Allow-Origin":["*"],"X-Padding":["00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"],"Date":["Thu, 19 Dec 2024 04:14:13 GMT"],"Content-Length":["0"],"Access-Control-Allow-Methods":["GET, POST"]},"status":400}
```
caddyfile
```
{
  log {
    output stdout
    level debug
    format json {
      time_local
      time_format wall
    }
  }

  email xxxxxxxxx@gmail.com
  acme_dns cloudflare xxxxxxxxxxxxxxxxxxxxxxxxxx
}
# 源站端口，过cdn时变成443端口
example.com:41969 {
  handle /whatismyip/* {
    reverse_proxy http://127.0.0.1:1234
  }
  respond {remote_host} 200
}
```

### 重现方式

我已经尽量提供信息了，不知道其他人是否可以复现。

### 客户端配置

<details><pre><code>
    {
      "tag": "proxy",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "example.com",
            "port": 443,
            "users": [
              {
                "id": "xxxxxxxxxxxxxxxxxxxxxxxxxx",
                "encryption": "none"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "xhttp",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false,
          "fingerprint": "chrome"
        },
        "xhttpSettings": {
          "path": "/whatismyip",
          "mode": "auto"
        }
      }
    },
</code></pre></details>

### 服务端配置

<details><pre><code>
    {
      "listen": "127.0.0.1",
      "port": 1234,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "xhttp",
        "xhttpSettings": {
          "path": "/whatismyip",
	  "mode": "auto"
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls", "quic"]
      }
    }
</code></pre></details>

### 客户端日志

<details><pre><code>
2024/12/19 12:28:50 [Warning] core: Xray 24.12.18 started
2024/12/19 12:30:11 [Info] [698475743] proxy/socks: TCP Connect request to tcp:www.google.com:443
2024/12/19 12:30:11 [Info] [698475743] app/dispatcher: sniffed domain: www.google.com
2024/12/19 12:30:11 [Info] [698475743] app/dispatcher: taking detour [proxy] for [tcp:www.google.com:443]
2024/12/19 12:30:11 [Info] [698475743] transport/internet/splithttp: XHTTP is dialing to tcp:example.com:443, mode stream-up, HTTP version 2, host example.com
2024/12/19 12:30:11 [Info] [698475743] proxy/vless/outbound: tunneling request to tcp:www.google.com:443 via example.com:443
2024/12/19 12:30:11 from tcp:127.0.0.1:9855 accepted tcp:www.google.com:443 [socks -> proxy]
2024/12/19 12:30:12 [Info] [698475743] transport/internet/splithttp: invalid status code on download:400 Bad Request
2024/12/19 12:30:12 [Info] [698475743] app/proxyman/outbound: app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to decode response header > proxy/vless/encoding: failed to read response version > transport/internet/splithttp: downResponse failed
2024/12/19 12:30:12 [Info] [698475743] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
2024/12/19 12:30:12 [Info] [494072152] proxy/socks: TCP Connect request to tcp:www.google.com:443
2024/12/19 12:30:12 [Info] [494072152] app/dispatcher: sniffed domain: www.google.com
2024/12/19 12:30:12 [Info] [494072152] app/dispatcher: taking detour [proxy] for [tcp:www.google.com:443]
2024/12/19 12:30:12 from tcp:127.0.0.1:9861 accepted tcp:www.google.com:443 [socks -> proxy]
2024/12/19 12:30:12 [Info] [494072152] transport/internet/splithttp: XHTTP is dialing to tcp:example.com:443, mode stream-up, HTTP version 2, host example.com
2024/12/19 12:30:12 [Info] [494072152] proxy/vless/outbound: tunneling request to tcp:www.google.com:443 via example.com:443
2024/12/19 12:30:12 [Info] [494072152] transport/internet/splithttp: invalid status code on download:400 Bad Request
2024/12/19 12:30:12 [Info] [494072152] app/proxyman/outbound: app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to decode response header > proxy/vless/encoding: failed to read response version > transport/internet/splithttp: downResponse failed
2024/12/19 12:30:12 [Info] [494072152] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
</code></pre></details>

### 服务端日志

<details><pre><code>
2024/12/19 12:12:23 [Debug] app/log: Logger started
2024/12/19 12:12:23 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:41970
2024/12/19 12:12:23 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:1234
2024/12/19 12:12:23 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:41970
2024/12/19 12:12:23 [Info] transport/internet/splithttp: listening TCP for XHTTP on 127.0.0.1:1234
2024/12/19 12:12:23 [Warning] core: Xray 24.12.18 started
2024/12/19 12:14:09 [Info] transport/internet/splithttp: invalid x_padding length:0
2024/12/19 12:14:09 [Info] transport/internet/splithttp: invalid x_padding length:0
2024/12/19 12:14:09 [Info] transport/internet/splithttp: invalid x_padding length:0
2024/12/19 12:14:10 [Info] transport/internet/splithttp: invalid x_padding length:0
2024/12/19 12:14:10 [Info] transport/internet/splithttp: invalid x_padding length:0
2024/12/19 12:14:10 [Info] transport/internet/splithttp: invalid x_padding length:0
</code></pre></details>

**Comment by Fangliding** [comment]
sever把那个什么padding length调成0就不检查了
似乎是CloudFront把querysting丢掉了 那玩意检测的是中国

**Comment by Fangliding** [comment]
sever把那个什么padding length调成0就不检查了
似乎是CloudFront把querysting丢掉了 那玩意检测的是这个

**Comment by RPRX** [comment]
忘了回复这个 issue，我猜是他自己 CFT 配置错了把 query string 扔了，~~毕竟 XHTTP 这么新还不至于引起 CFT 注意吧~~

**Comment by lhbdhr** [comment]
> 忘了回复这个 issue，我猜是他自己 CFT 配置错了把 query string 扔了，~毕竟 XHTTP 这么新还不至于引起 CFT 注意吧~

感谢大佬们的指点，已经通了，果然是CFT，缓存配置时，转发 query string 到源站关掉了，修改之后就通了。

**Comment by aawwsslll** [comment]
我也是用的这个模式，下载速度明显偏低，你有这个问题吗

**Comment by lhbdhr** [comment]
> 我也是用的这个模式，下载速度明显偏低，你有这个问题吗。多线程下载速度被锁死了上限2MB。

我speed.cloudflare.com测速了，244Mbps，下载速度没问题。

**Comment by Btu2023V** [comment]
> 感谢大佬们的指点，已经通了，果然是CFT，缓存配置时，转发 query string 到源站关掉了，修改之后就通了。

兄弟你缓存是怎样配置的？给我参考一下。

**Comment by lhbdhr** [comment]
> 兄弟你缓存是怎样配置的？给我参考一下。
直接选Legacy cache settings
然后 
Headers 选 none
query 选 all
Cookies 选 none 
就是完全不要缓存。

**Comment by xiaozhezi** [comment]
@lhbdhr  请教下，我的cloudfront也是按照你这个配置的。但是链接失败，日志显示get/post方法都是"http2: frame too large"。 请问你遇到过没？
