### ISSUE TITLE
使用DOH 本地模式 (DOHL)发送dns请求时的指纹是golang的指纹

### ISSUE THREAD

**Issue by intmain0** [XTLS/Xray-core#4185]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

客户端配置里已经开启了utls，使用DOH 本地模式 (DOHL)发送dns请求时的指纹还是golang的指纹。虽然这里的utls指纹指的是客户端到服务端的连接，但是既然有这个选项了，也帮DOHL用上utls吧！

### 重现方式

![屏幕截图 2024-12-19 215434](https://github.com/user-attachments/assets/39c30368-1d9d-407d-9aee-585f75053bd5)
JA4:t13i1910h2_9dc949149365_e7c285222651
听说wireshark的ja4插件存在无法正确获取版本号的问题导致ja4_a计算不准，搜索"9dc949149365_e7c285222651"后发现是ngrok 3.8.0的指纹，详见https://ja4db.com/fingerprint/ja4/t13d191000_9dc949149365_e7c285222651

![屏幕截图 2024-12-19 221032](https://github.com/user-attachments/assets/0c4d9d29-edff-4d02-88d6-9be4d0a4e8a6)
这个是客户端到服务端的握手包，是chrome的指纹。

### 客户端配置

<details><pre><code>
{
  "dns": {

    "servers": [
      {
        "address": "223.5.5.5",
        "domains": [
          "geosite:cn",
          "geosite:geolocation-cn"
        ],
        "expectIPs": [
          "geoip:cn"
        ],
        "skipFallback": true
      },
      "https+local://x.x.x.x/dns-query"
    ]
  },

  "log": {
    "access": "",
    "error": "",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "socks",
      "port": 10808,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ],
        "routeOnly": false
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "allowTransparent": false
      }
    },
    {
      "tag": "http",
      "port": 10809,
      "listen": "127.0.0.1",
      "protocol": "http",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ],
        "routeOnly": false
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "allowTransparent": false
      }
    },
    {
      "tag": "api",
      "port": 10813,
      "listen": "127.0.0.1",
      "protocol": "dokodemo-door",
      "settings": {
        "udp": false,
        "address": "127.0.0.1",
        "allowTransparent": false
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "",
            "port": 443,
            "users": [
              {
                "id": "",
                "alterId": 0,
                "email": "t@t.tt",
                "security": "auto",
                "encryption": "none"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "grpc",
        "security": "reality",
        "realitySettings": {
          "serverName": "",
          "fingerprint": "chrome",
          "show": false,
          "publicKey": "",
          "shortId": "",
          "spiderX": ""
        },
        "grpcSettings": {
          "serviceName": "grpc",
          "multiMode": false,
          "idle_timeout": 60,
          "health_check_timeout": 20,
          "permit_without_stream": false,
          "initial_windows_size": 0
        }
      },
      "mux": {
        "enabled": false,
        "concurrency": -1
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    }
  ],
  "stats": {},
  "api": {
    "tag": "api",
    "services": [
      "StatsService"
    ]
  },
  "policy": {
    "system": {
      "statsOutboundUplink": true,
      "statsOutboundDownlink": true
    }
  },

  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "domainMatcher": "mph",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api"
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": [

        ]
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [

        ]
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": [

        ]
      },
      {
        "type": "field",
        "outboundTag": "proxy",
        "domain": [

        ]
      }
    ]
  }
}
</code></pre></details>

### 服务端配置

<details><pre><code>

</code></pre></details>

### 客户端日志

<details><pre><code>

</code></pre></details>

### 服务端日志

<details><pre><code>

</code></pre></details>

**Comment by Fangliding** [comment]
很显而易见事 并不是bug
只是查doh的连接没什么大不了的 真介意的话就让查询连接走代理吧
