### ISSUE TITLE
xray跑shadowsocks协议无法监听端口

### ISSUE THREAD

**Issue by zsbstephen** [XTLS/Xray-core#4186]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

创建一个使用shadowsocks协议的inboundDetour，监听本地55555端口（接收由simple-obfs混淆插件obfs-local进程转发过来数据），以前某个版本之前一直是可以正常工作的，不知道哪个版本之后就失效了，运行netstat -ntlp发现xray并未监听55555端口。

### 重现方式

Debian 9 x64系统，跑linux 64位xray，创建一个使用shadowsocks协议的inboundDetour

### 客户端配置

不用

### 服务端配置

<details><pre><code>

        "inboundDetour": [ {
                "listen": "127.0.0.1",
                "port": 55555,
                "protocol": "Shadowsocks",
                "settings": {
                        "method": "2022-blake3-chacha20-poly1305",
                        "password": "password",
                        "udp": true,
                        "network": "tcp,udp"
                },
                "tag": "Shadowsocks"
        }
        ],

</code></pre></details>

### 客户端日志

不用

### 服务端日志

不用

**Comment by xqzr** [comment]
> `"inboundDetour"`

`inbound`

**Comment by Fangliding** [comment]
一些古代神秘字段被删除了 真不知道你们哪找来的

**Comment by xqzr** [comment]
> 真不知道你们哪找来的

AI

**Comment by zsbstephen** [comment]
> 一些早就弃用的古代神秘字段被删除了 真不知道你们哪找来的

21年抄项目官方的示例配置模板，一直沿用没改过，不晓得配置字段有变化。
