### ISSUE TITLE
同样配置，v24.11.30后无法使用vless+xhhtp+tls，但vless+vison+tls没问题

### ISSUE THREAD

**Issue by CharlesWou** [XTLS/Xray-core#4188]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

一样的vless+xhhtp+tls服务器配置，在24.11.30版可以，更新服务端后（24.12.15及24.12.18）无法连接。另外测试了下，换成vless+vison+tls就没问题。

### 重现方式

服务端只部署了一个xray（v24.12.15或v24.12.18），客户端V2rayN V7.3.2（XrayCore v24.12.18）。

### 客户端配置

<details><pre><code>
![image](https://github.com/user-attachments/assets/1bc56fc5-239a-42ff-b09c-54cbbb30cb6b)
</code></pre></details>

### 服务端配置

<details><pre><code>
{
  "inbounds": [
    {
      "listen": "0.0.0.0",
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "xxxxx-xxxxx-xxxxx-xxxxx-xxxxx"
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "xhttp",
        "security": "tls",
        "tlsSettings": {
          "alpn": ["h3","h2","http/1.1"],
          "certificates": [
            {
              "certificateFile": "/path/file.crt",
              "keyFile": "/path/file.key"
            }
          ]
        },
        "xhttpSettings": {
          "path": "/n23ih165gs",
          "mode": "auto"
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls", "quic"],
        "metadataOnly": false
      }
    }
  ],
  "outbounds": [
    {
      "tag": "direct",
      "protocol": "freedom"
    },
    {
      "tag": "block",
      "protocol": "blackhole"
    }
  ]
}
</code></pre></details>

### 客户端日志

<details><pre><code>
2024/12/20 17:33:43 [Debug] [3578812891] proxy/socks: Not Socks request, try to parse as HTTP request
2024/12/20 17:33:43 [Info] [3578812891] proxy/http: request to Method [CONNECT] Host [signaler-pa.clients6.google.com:443] with URL [//signaler-pa.clients6.google.com:443]
2024/12/20 17:33:43 [Info] [3578812891] app/dispatcher: sniffed domain: signaler-pa.clients6.google.com
2024/12/20 17:33:43 [Info] [3578812891] app/dispatcher: taking detour [proxy] for [tcp:signaler-pa.clients6.google.com:443]
2024/12/20 17:33:43 [Info] [3578812891] common/mux: dispatching request to tcp:signaler-pa.clients6.google.com:443
2024/12/20 17:33:43 from 127.0.0.1:55544 accepted //signaler-pa.clients6.google.com:443 [socks -> proxy]
2024/12/20 17:33:43 [Info] common/mux: failed to handler mux client connection > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to decode response header > proxy/vless/encoding: failed to read response version > EOF
2024/12/20 17:33:43 [Info] common/mux: failed to read metadata > io: read/write on closed pipe
2024/12/20 17:33:43 [Info] [487868102] common/mux: failed to fetch all input > io: read/write on closed pipe
2024/12/20 17:33:43 [Info] [3578812891] common/mux: failed to fetch all input > io: read/write on closed pipe
2024/12/20 17:33:43 [Debug] [3707396349] proxy/socks: Not Socks request, try to parse as HTTP request
2024/12/20 17:33:43 [Warning] [3707396349] app/proxyman/inbound: connection ends > proxy/http: failed to read http request > malformed HTTP request "\x00"
2024/12/20 17:33:43 [Info] [1925986097] proxy/socks: TCP Connect request to tcp:www.google.com:443
2024/12/20 17:33:43 [Info] [1925986097] app/dispatcher: sniffed domain: www.google.com
2024/12/20 17:33:43 [Info] [1925986097] app/dispatcher: taking detour [proxy] for [tcp:www.google.com:443]
2024/12/20 17:33:43 from tcp:127.0.0.1:55550 accepted tcp:www.google.com:443 [socks -> proxy]
2024/12/20 17:33:43 [Info] [1925986097] common/mux: dispatching request to tcp:www.google.com:443
2024/12/20 17:33:43 [Info] transport/internet/splithttp: XHTTP is dialing to tcp:aaa.example.com:443, mode stream-up, HTTP version 2, host aaa.example.com
2024/12/20 17:33:43 [Info] proxy/vless/outbound: tunneling request to tcp:v1.mux.cool:9527 via aaa.example.com:443
2024/12/20 17:33:44 [Info] [487868102] app/proxyman/inbound: connection ends > proxy/http: connection ends > context canceled
2024/12/20 17:33:44 [Info] [3578812891] app/proxyman/inbound: connection ends > proxy/http: connection ends > context canceled
2024/12/20 17:33:44 [Debug] [4199268108] proxy/socks: Not Socks request, try to parse as HTTP request
2024/12/20 17:33:44 [Info] [4199268108] proxy/http: request to Method [CONNECT] Host [signaler-pa.clients6.google.com:443] with URL [//signaler-pa.clients6.google.com:443]
2024/12/20 17:33:44 [Debug] [846992898] proxy/socks: Not Socks request, try to parse as HTTP request
2024/12/20 17:33:44 [Info] [846992898] proxy/http: request to Method [CONNECT] Host [signaler-pa.clients6.google.com:443] with URL [//signaler-pa.clients6.google.com:443]
2024/12/20 17:33:44 [Info] [4199268108] app/dispatcher: sniffed domain: signaler-pa.clients6.google.com
2024/12/20 17:33:44 [Info] [4199268108] app/dispatcher: taking detour [proxy] for [tcp:signaler-pa.clients6.google.com:443]
2024/12/20 17:33:44 from 127.0.0.1:55551 accepted //signaler-pa.clients6.google.com:443 [socks -> proxy]
2024/12/20 17:33:44 [Info] [4199268108] common/mux: dispatching request to tcp:signaler-pa.clients6.google.com:443
2024/12/20 17:33:44 [Info] [846992898] app/dispatcher: sniffed domain: signaler-pa.clients6.google.com
2024/12/20 17:33:44 [Info] [846992898] app/dispatcher: taking detour [proxy] for [tcp:signaler-pa.clients6.google.com:443]
2024/12/20 17:33:44 from 127.0.0.1:55552 accepted //signaler-pa.clients6.google.com:443 [socks -> proxy]
2024/12/20 17:33:44 [Info] [846992898] common/mux: dispatching request to tcp:signaler-pa.clients6.google.com:443
2024/12/20 17:33:44 [Info] common/mux: failed to handler mux client connection > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to decode response header > proxy/vless/encoding: failed to read response version > EOF
2024/12/20 17:33:44 [Info] common/mux: failed to read metadata > io: read/write on closed pipe
2024/12/20 17:33:44 [Info] [1925986097] common/mux: failed to fetch all input > io: read/write on closed pipe
2024/12/20 17:33:44 [Info] [846992898] common/mux: failed to fetch all input > io: read/write on closed pipe
2024/12/20 17:33:44 [Info] [4199268108] common/mux: failed to fetch all input > io: read/write on closed pipe
2024/12/20 17:33:44 [Debug] [2656990034] proxy/socks: Not Socks request, try to parse as HTTP request
2024/12/20 17:33:44 [Info] [2656990034] proxy/http: request to Method [CONNECT] Host [alive.github.com:443] with URL [//alive.github.com:443]
2024/12/20 17:33:44 [Info] [2656990034] app/dispatcher: sniffed domain: alive.github.com
2024/12/20 17:33:44 [Info] [2656990034] app/dispatcher: taking detour [proxy] for [tcp:alive.github.com:443]
2024/12/20 17:33:44 from 127.0.0.1:55553 accepted //alive.github.com:443 [socks -> proxy]
2024/12/20 17:33:44 [Info] [2656990034] common/mux: dispatching request to tcp:alive.github.com:443
2024/12/20 17:33:44 [Info] transport/internet/splithttp: XHTTP is dialing to tcp:aaa.example.com:443, mode stream-up, HTTP version 2, host aaa.example.com
2024/12/20 17:33:44 [Info] proxy/vless/outbound: tunneling request to tcp:v1.mux.cool:9527 via aaa.example.com:443
2024/12/20 17:33:45 [Info] [846992898] app/proxyman/inbound: connection ends > proxy/http: connection ends > context canceled
2024/12/20 17:33:45 [Info] [4199268108] app/proxyman/inbound: connection ends > proxy/http: connection ends > context canceled
2024/12/20 17:33:45 [Info] [1925986097] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
2024/12/20 17:33:45 当前延迟: -1 ms，none
</code></pre></details>

### 服务端日志

<details><pre><code>
024/12/20 09:33:43 [Info] [543355129] proxy/vless/inbound: firstLen = 2307
2024/12/20 09:33:43 [Info] [543355129] proxy/vless/inbound: received request for tcp:v1.mux.cool:0
2024/12/20 09:33:43 [Info] [543355129] common/mux: received request for tcp:signaler-pa.clients6.google.com:443
2024/12/20 09:33:43 [Info] [543355129] common/mux: unexpected EOF > common/mux: failed to process data > common/mux: unexpected network TCP
2024/12/20 09:33:43 [Info] [543355129] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to transfer request payload > io: read/write on closed pipe
2024/12/20 09:33:43 [Info] [351062478] proxy/vless/inbound: firstLen = 451
2024/12/20 09:33:43 [Info] [351062478] proxy/vless/inbound: received request for tcp:v1.mux.cool:0
2024/12/20 09:33:43 [Info] [351062478] common/mux: received request for tcp:www.google.com:443
2024/12/20 09:33:43 [Info] [351062478] common/mux: unexpected EOF > common/mux: failed to process data > common/mux: unexpected network TCP
2024/12/20 09:33:44 [Info] [351062478] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to transfer request payload > io: read/write on closed pipe
2024/12/20 09:33:44 [Info] [1625309643] proxy/vless/inbound: firstLen = 1905
2024/12/20 09:33:44 [Info] [1625309643] proxy/vless/inbound: received request for tcp:v1.mux.cool:0
2024/12/20 09:33:44 [Info] [1625309643] common/mux: received request for tcp:alive.github.com:443
2024/12/20 09:33:44 [Info] [1625309643] common/mux: unexpected EOF > common/mux: failed to process data > common/mux: unexpected network TCP
2024/12/20 09:33:44 [Info] transport/internet/splithttp: failed to validate path, request:/cgi-bin/../../../../../../../../../../bin/sh, config:/n23ih165gs/
2024/12/20 09:33:45 [Info] [1625309643] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to transfer request payload > io: read/write on closed pipe
2024/12/20 09:33:46 [Info] [2888961363] proxy/vless/inbound: firstLen = 3626
2024/12/20 09:33:46 [Info] [2888961363] proxy/vless/inbound: received request for tcp:v1.mux.cool:0
2024/12/20 09:33:46 [Info] [2888961363] common/mux: received request for tcp:ssl.gstatic.com:443
2024/12/20 09:33:46 [Info] [2888961363] common/mux: unexpected EOF > common/mux: failed to process data > common/mux: unexpected network TCP
2024/12/20 09:33:47 [Info] transport/internet/splithttp: failed to validate path, request:/hello.world, config:/n23ih165gs/
2024/12/20 09:33:48 [Info] transport/internet/splithttp: failed to validate path, request:/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php, config:/n23ih165gs/
2024/12/20 09:33:49 [Info] transport/internet/splithttp: failed to validate path, request:/vendor/phpunit/phpunit/Util/PHP/eval-stdin.php, config:/n23ih165gs/
2024/12/20 09:33:49 [Info] transport/internet/splithttp: failed to validate path, request:/vendor/phpunit/src/Util/PHP/eval-stdin.php, config:/n23ih165gs/
2024/12/20 09:33:49 [Info] [2888961363] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to transfer request payload > io: read/write on closed pipe
2024/12/20 09:33:50 [Info] [843473780] proxy/vless/inbound: firstLen = 1836
2024/12/20 09:33:50 [Info] [843473780] proxy/vless/inbound: received request for tcp:v1.mux.cool:0
2024/12/20 09:33:50 [Info] [843473780] common/mux: received request for tcp:signaler-pa.clients6.google.com:443
2024/12/20 09:33:50 [Info] [843473780] common/mux: unexpected EOF > common/mux: failed to process data > common/mux: unexpected network TCP
2024/12/20 09:33:50 [Info] [843473780] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to transfer request payload > io: read/write on closed pipe
2024/12/20 09:33:50 [Info] transport/internet/splithttp: failed to validate path, request:/vendor/phpunit/Util/PHP/eval-stdin.php, config:/n23ih165gs/
2024/12/20 09:33:51 [Info] transport/internet/splithttp: failed to validate path, request:/vendor/phpunit/phpunit/LICENSE/eval-stdin.php, config:/n23ih165gs/
2024/12/20 09:33:51 [Info] transport/internet/splithttp: failed to validate path, request:/vendor/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php, config:/n23ih165gs/
2024/12/20 09:33:51 [Info] [2111823730] proxy/vless/inbound: firstLen = 1836
2024/12/20 09:33:51 [Info] [2111823730] proxy/vless/inbound: received request for tcp:v1.mux.cool:0
2024/12/20 09:33:51 [Info] [2111823730] common/mux: received request for tcp:signaler-pa.clients6.google.com:443
2024/12/20 09:33:51 [Info] [2111823730] common/mux: unexpected EOF > common/mux: failed to process data > common/mux: unexpected network TCP
2024/12/20 09:33:51 [Info] transport/internet/splithttp: failed to validate path, request:/phpunit/phpunit/src/Util/PHP/eval-stdin.php, config:/n23ih165gs/
2024/12/20 09:33:51 [Info] transport/internet/splithttp: failed to validate path, request:/phpunit/phpunit/Util/PHP/eval-stdin.php, config:/n23ih165gs/
2024/12/20 09:33:53 [Info] [2111823730] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > proxy/vless/inbound: failed to transfer request payload > io: read/write on closed pipe
2024/12/20 09:33:54 [Info] [1195409781] proxy/vless/inbound: firstLen = 1858
2024/12/20 09:33:54 [Info] [1195409781] proxy/vless/inbound: received request for tcp:v1.mux.cool:0
2024/12/20 09:33:54 [Info] [1195409781] common/mux: received request for tcp:alive.github.com:443
2024/12/20 09:33:54 [Info] [1195409781] common/mux: unexpected EOF > common/mux: failed to process data > common/mux: unexpected network TCP
2024/12/20 09:33:57 [Info] transport/internet/splithttp: failed to validate path, request:/phpunit/src/Util/PHP/eval-stdin.php, config:/n23ih165gs/
2024/12/20 09:33:58 [Info] transport/internet/splithttp: failed to validate path, request:/phpunit/Util/PHP/eval-stdin.php, config:/n23ih165gs/
2024/12/20 09:34:00 [Info] transport/internet/splithttp: failed to validate path, request:/lib/phpunit/phpunit/src/Util/PHP/eval-stdin.php, config:/n23ih165gs/
2024/12/20 09:34:00 [Info] transport/internet/splithttp: failed to validate path, request:/lib/phpunit/phpunit/Util/PHP/eval-stdin.php, config:/n23ih165gs/
</code></pre></details>

**Comment by Fangliding** [comment]
不接受一张图作为配置的反馈
大概率是一楼说的ng的全局mux的问题

**Comment by CharlesWou** [comment]
> 客户端配置没上传成功，目前看到的来说，服务端删除alpn和mode，客户端v2rayn需要更新到最新版，并且关闭mux

感谢，客户端关闭mux后，就能连接了！
