### ISSUE TITLE
服务端如何改监听ipv4？

### ISSUE THREAD

**Issue by liweishu** [XTLS/Xray-core#419]
服务端默认监听的ipv6，但是我这服务器ipv6有点问题，结果没法用了。
请问服务端如何改监听ipv4？

系统：debian10

**Comment by AkinoKaede** [comment]
duplicate #413

**Comment by rprx** [comment]
1. https://github.com/XTLS/Xray-core/issues/413#issuecomment-804206625
2. 若只需监听 IPv4，请填写 `listen`
