### ISSUE TITLE
xhttp + tls 下载网速比其他模式显著的低

### ISSUE THREAD

**Issue by aawwsslll** [XTLS/Xray-core#4190]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

尝试了reality模式下载最少稳定5MB以上的速度，而xhttp + tls 速度只1MB到2MB之间，基本只能稳定在1MB多点。
其他各种主流模式都有尝试了，速度都是正常的。我这边尝试了xhttp的三个模式， 其中stream-one无法连接，下载时无法连接到网络，"packet-up" 和 "stream-up" ，几乎没啥差距。很奇怪的点是，虽然xhttp下载油管的视频速度不行，但是在线看4K没什么问题，这边播放，一小时（七八个G大小的油管在线视频），未出现卡顿问题，拖动进度条也是3秒内响应。

### 重现方式

我用的是这个一键搭建的脚本匹配的，https://github.com/233boy/Xray， tls用的免费域名，然后用的cloudflare做的dns域名解析。
下载用的idm嗅探到youtube的视频，然后开启了16线程下载，其他主流协议稳定最低保持5MB以上的速度，而xhttp只有可怜的1MB
出头。

### 客户端配置

<details><pre><code>

</code></pre></details>

### 服务端配置

<details><pre><code>

</code></pre></details>

### 客户端日志

<details><pre><code>

</code></pre></details>

### 服务端日志

<details><pre><code>

</code></pre></details>

**Comment by Fangliding** [comment]
没填模板 不接受脚本或者面板作为提交内容

**Comment by aawwsslll** [comment]
> 没填模板 不接受脚本或者面板作为提交内容

你这边可以用这个模板试试下载速度是否正常，如果你正常当我没说，我也不用这个模式了，可能不兼容我的网络或者是233的一键脚本有问题。
