### ISSUE TITLE
客户端偶尔会CPU占用率持续居高不下

### ISSUE THREAD

**Issue by shenlijun** [XTLS/Xray-core#42]
具体什么原因还没有跟进，也许大家都可以关注下看看是不是特例

在一台CPU是i5-9400T的PVE上面做得网关透明代理，debian10

偶尔用HTOP查看xray进程的cpu占用达到200-300%，而且会长时间持续，直到重启服务
遇到过2次

另外一台CPU是E3-1265L的PVE暂时还没发现这个现象

**Comment by shenlijun** [comment]
网关不是在虚拟机里
是直接在底层的debian上

**Comment by rprx** [comment]
等待更多报告

**Comment by badO1a5A90** [comment]
透明代理运行一段时候CPU一直满负荷的.大多数原因是iptable没写好,导致某些情况下出现回环了.

**Comment by shenlijun** [comment]
> 透明代理运行一段时候CPU一直满负荷的.大多数原因是iptable没写好,导致某些情况下出现回环了.

确实iptable有个地方没写好，关于53端口的
说来也奇怪，两台PVE都有这个问题，但是都可以正常透明代理，而且其中一台从来没出现过占用高的问题

改了iptable再观察一段时间看看

**Comment by badO1a5A90** [comment]
可能没有问题的那一台，不会有别处发来的53端口流量吧。

**Comment by shenlijun** [comment]
> 可能没有问题的那一台，不会有别处发来的53端口流量吧。

家里和单位的拓扑确实有些差异，因为之前没有配置log，所以不知道具体是什么原因。最近两天又没有高占用，等待中......
有可能改了iptables之后就真的没有问题了

**Comment by badO1a5A90** [comment]
是否已经解决？

**Comment by shenlijun** [comment]
> 是否已经解决？

最近没有出现了，应该就是iptable的问题
