### ISSUE TITLE
回国流量禁用不彻底

### ISSUE THREAD

**Issue by JYQ17** [XTLS/Xray-core#4200]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

路由设置屏蔽geoip:cn后开全局部分国内网站像百度、腾讯仍可以打开

### Reproduction Method

N/A

### Client config

N/A

### Server config

 "routing": {
   "domainStrategy": "IPIfNonMatch",
   "rules": [
     {
       "inboundTag": [
         "api"
       ],
       "outboundTag": "api",
       "type": "field"
     },
     {
       "ip": [
         "geoip:private",
         "geoip:cn"
       ],
       "outboundTag": "blocked",
       "type": "field"
     },
     {
       "outboundTag": "blocked",
       "protocol": [
         "bittorrent"
       ],
       "type": "field"
     },
     {
       "domain": [
         "geosite:openai",
         "ip.gs"
       ],
       "outboundTag": "warp",
       "type": "field"
     }
   ]
 },
"outbounds": [
  {
    "protocol": "freedom",
    "settings": {
      "domainStrategy": "AsIs",
      "noises": [],
      "redirect": ""
    },
    "tag": "direct"
  },
  {
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  },
  {
    "protocol": "wireguard",
    "settings": {
      "address": [
        "AAA",
        "AAA"
      ],
      "domainStrategy": "ForceIP",
      "mtu": 1420,
      "noKernelTun": false,
      "peers": [
        {
          "allowedIPs": [
            "0.0.0.0/0",
            "::/0"
          ],
          "endpoint": "AAA",
          "keepAlive": 0,
          "publicKey": "AAA"
        }
      ],
      "reserved": [
       AAA
      ],
      "secretKey": "AAA",
      "workers": 2
    },
    "tag": "warp"
  }
],

### Client log

<details><pre><code>

</code></pre></details>

### Server log

<details><pre><code>

</code></pre></details>

**Comment by Fangliding** [comment]
有的时候这些网站可能提供海外CDN没匹配上国内IP 可以考虑用geosite
