### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by sing-cube** [XTLS/Xray-core#4209]
您好！
@RPRX 我想了解您对当前环境下 TROJAN 的看法，以及 TROJAN 和 xHTTP 结合使用的实际效果。
我不太明白为什么要选择 VLESS，因为我用 TROJAN 也能实现同样的功能。

**Comment by wyx2685** [comment]
@sing-cube trojan 毕竟 不是自家人

**Comment by Fangliding** [comment]
因为自有协议可以扩展(虽然现阶段好像只有 xtls) 别的区别不大

**Comment by RPRX** [comment]
VLESS 出了 Seed 后可以配合 XHTTP 使用

我觉得这种问题真是无聊，Trojan 标准又不在我们这里且早已停止更新，而 VLESS 是我们的协议，不选 VLESS 选什么
