### ISSUE TITLE
vpn 导致网址对应于 127.0.0.5，自动添加了 localhost 证书，然后无法访问，这个应该怎么解决？ 谢谢了

### ISSUE THREAD

**Issue by billpeace** [XTLS/Xray-core#4210]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

某个网站  是vpn 网站，对应IP 是 127.0.0.5 是VPN 改变DNS 导致的。

目前会自动添加 localhost 证书，想了解下，这个应该怎么取消呢？

![image](https://github.com/user-attachments/assets/cec00c77-c8fb-4988-8468-c56d1fa5d332)
![image](https://github.com/user-attachments/assets/597b0ca0-d173-4e28-a787-4b9532f9150e)

### 重现方式

某个网站  是vpn 网站，对应IP 是 127.0.0.5 是VPN 改变DNS 导致的。

### 客户端配置

无

### 服务端配置

无

### 客户端日志

无

### 服务端日志

无

**Comment by Fangliding** [comment]
这跟xray有锤子关系

**Comment by billpeace** [comment]
解决了  发现咋回事了。

谢谢了。 本地IIS 开启了 443访问，而且还带有证书
