### ISSUE TITLE
Outbound-routing issues

### ISSUE THREAD

**Issue by Ahmad-2213** [XTLS/Xray-core#4213]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [ ] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

I have defined multiple outbound tags including vless/vmess and performed BurstObservatoy on  outbounds ( because I use the vmess link for some specific sites, I didn't include it to balancer tags for routing)
according to config, I've routed some websites through proxy11 which is vmess link , now the problem here is that the domains are mis-matched and sometimes all the data is routed through proxy11 which is absolutely unwanted.

### Reproduction Method

try to perform burstObservatory and different routing for various outbounds.
Include Vless/Vmess together in outbound.

### Client config

{
    
    "dns": {
	"queryStrategy": "UseIPv4",
        "servers": [
            "fakedns",
	    "8.8.8.8"
        ],
        "tag": "dns-in"
    },
    "fakedns": {
        "ipPool": "198.18.0.0/15",
        "poolSize": 10000
    },
    "inbounds": [
        {
            "listen": "0.0.0.0",
            "port": 10808,
            "protocol": "socks",
            "settings": {
                "udp": true
            },
            "sniffing": {
                "destOverride": [
                    "http",
                    "tls",
		    "quic",
                    "fakedns"
                ],
                "enabled": true
            },
            "tag": "socks"
        }
    ],
    "log": {
        "dnsLog": false,
        "loglevel": "info"
    },
    "outbounds": [
        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "x",
                        "port": 443,
                        "users": [
                            {
                                "encryption": "none",
                                "id": "x"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "xhttp",
                "security": "tls",
                "tlsSettings": {
                    "allowInsecure": true,
                    "alpn": [
                        "h2"
                    ],
                    "minVersion": "1.3",
                    "serverName": "x"
                },
                  "xhttpSettings": {
          "host": "x",
          "mode": "stream-one",
          "path": "/xhttp"
                }
            },
            "tag": "proxy"
        },
        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "x",
                        "port": 443,
                        "users": [
                            {
                                "encryption": "none",
                                "id": "x"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "xhttp",
                "security": "tls",
                "tlsSettings": {
                    "allowInsecure": true,
                    "alpn": [
                        "h2"
                    ],
                    "minVersion": "1.3",
                    "serverName": "x"
                },
                  "xhttpSettings": {
          "host": "x",
          "mode": "stream-one",
          "path": "/xhttp"
                }
            },
            "tag": "proxy1"
        },
        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "x",
                        "port": 443,
                        "users": [
                            {
                                "encryption": "none",
                                "id": "x"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "xhttp",
                "security": "tls",
                "tlsSettings": {
                    "allowInsecure": true,
                    "alpn": [
                        "h2"
                    ],
                    "minVersion": "1.3",
                    "serverName": "x"
                },
                  "xhttpSettings": {
          "host": "x",
          "mode": "stream-one",
          "path": "/xhttp"
                }
            },
            "tag": "proxy2"
        },
        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "x",
                        "port": 443,
                        "users": [
                            {
                                "encryption": "none",
                                "id": "x"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "xhttp",
                "security": "tls",
                "tlsSettings": {
                    "allowInsecure": true,
                    "alpn": [
                        "h2"
                    ],
                    "minVersion": "1.3",
                    "serverName": "x"
                },
                  "xhttpSettings": {
          "host": "x",
          "mode": "stream-one",
          "path": "/xhttp"
                }
            },
            "tag": "proxy3"
        },
        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "x",
                        "port": 443,
                        "users": [
                            {
                                "encryption": "none",
                                "id": "x"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "xhttp",
                "security": "tls",
                "tlsSettings": {
                    "allowInsecure": true,
                    "alpn": [
                        "h2"
                    ],
                    "minVersion": "1.3",
                    "serverName": "x"
                },
                  "xhttpSettings": {
          "host": "x",
          "mode": "stream-one",
          "path": "/xhttp"
                }
            },
            "tag": "proxy4"
        },
        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "x",
                        "port": 443,
                        "users": [
                            {
                                "encryption": "none",
                                "id": "x"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "xhttp",
                "security": "tls",
                "tlsSettings": {
                    "allowInsecure": true,
                    "alpn": [
                        "h2"
                    ],
                    "minVersion": "1.3",
                    "serverName": "x"
                },
                  "xhttpSettings": {
          "host": "x",
          "mode": "stream-one",
          "path": "/xhttp"
                }
            },
            "tag": "proxy5"
        },
        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "x",
                        "port": 443,
                        "users": [
                            {
                                "encryption": "none",
                                "id": "x"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "xhttp",
                "security": "tls",
                "tlsSettings": {
                    "allowInsecure": true,
                    "alpn": [
                        "h2"
                    ],
                    "minVersion": "1.3",
                    "serverName": "x"
                },
                  "xhttpSettings": {
          "host": "x",
          "mode": "stream-one",
          "path": "/xhttp"
                }
            },
            "tag": "proxy6"
        },
        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "x",
                        "port": 443,
                        "users": [
                            {
                                "encryption": "none",
                                "id": "x"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "xhttp",
                "security": "tls",
                "tlsSettings": {
                    "allowInsecure": true,
                    "alpn": [
                        "h2"
                    ],
                    "minVersion": "1.3",
                    "serverName": "x"
                },
                  "xhttpSettings": {
          "host": "x",
          "mode": "stream-one",
          "path": "/xhttp"
                }
            },
            "tag": "proxy7"
        },
        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "x",
                        "port": 8443,
                        "users": [
                            {
                                "encryption": "none",
                                "id": "x"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "xhttp",
                "security": "tls",
                "tlsSettings": {
                    "allowInsecure": true,
                    "alpn": [
                        "h2"
                    ],
                    "minVersion": "1.3",
                    "serverName": "x"
                },
                  "xhttpSettings": {
          "host": "x",
          "mode": "stream-one",
          "path": "/xhttp"
                }
            },
            "tag": "proxy8"
        },
        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "x",
                        "port": 443,
                        "users": [
                            {
                                "encryption": "none",
                                "id": "x"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "xhttp",
                "security": "tls",
                "tlsSettings": {
                    "allowInsecure": true,
                    "alpn": [
                        "h2"
                    ],
                    "minVersion": "1.3",
                    "serverName": "x"
                },
                  "xhttpSettings": {
          "host": "x",
          "mode": "stream-one",
          "path": "/xhttp"
                }
            },
            "tag": "proxy9"
        },
        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "x",
                        "port": 443,
                        "users": [
                            {
                                "encryption": "none",
                                "id": "x"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "xhttp",
                "security": "tls",
                "tlsSettings": {
                    "allowInsecure": true,
                    "alpn": [
                        "h2"
                    ],
                    "minVersion": "1.3",
                    "serverName": "x"
                },
                  "xhttpSettings": {
          "host": "x",
          "mode": "stream-one",
          "path": "/xhttp"
                }
            },
            "tag": "proxy10"
        },
	{
            "protocol": "vmess",
            "settings": {
                "vnext": [
                    {
                        "address": "x",
                        "port": 443,
                        "users": [
                            {
                                "encryption": "none",
                                "id": "x"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "security": "tls",
                "tlsSettings": {
                    "allowInsecure": true,
                    "alpn": [
                        "h3"
                    ],
                    "serverName": "x"
                },
                "wsSettings": {
                    "host": "x",
                    "path": "/"
                }
            },
            "tag": "proxy11"
        },
        {
            "protocol": "freedom",
            "settings": {
                "domainStrategy": "UseIP"
            },
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "settings": {
                "response": {
                    "type": "none"
                }
            },
            "tag": "block"
        },
        {
            "protocol": "dns",
            "tag": "dns-out"
        }
    ],
      "burstobservatory": {
        "pingconfig": {
            "connectivity": "http://detectportal.firefox.com/success.txt",
            "destination": "http://detectportal.firefox.com/success.txt",
            "interval": "120s",
            "sampling": 10,
            "timeout": "10s"
        },
        "subjectSelector": [
	    "proxy",
            "proxy1",
            "proxy2",
            "proxy3",
            "proxy4",
            "proxy5",
            "proxy6",
            "proxy7",
            "proxy8",
            "proxy9",
            "proxy10",
	    "proxy11"
        ]
    },
    "routing": {
        "balancers": [
            {
                "fallbackTag": "proxy",
                "selector": [
                    "proxy1",
                    "proxy2",
                    "proxy3",
                    "proxy4",
                    "proxy5",
                    "proxy6",
                    "proxy7",
                    "proxy8",
                    "proxy9",
                    "proxy10"
                ],
                "strategy": {
                    "type": "LeastLoad"
                },
                "tag": "balancer"
            }
        ],
        "domainMatcher": "hybrid",
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "inboundTag": [
                    "dns-in"
                ],
                "outboundtag": "dns-out",
                "port": "53",
                "type": "field"
            },
            {
                "network": "udp",
                "outboundtag": "direct",
                "port": "0-52,54-65535",
                "type": "field"
            },
            {
                "domain": [
                    "geosite:private",
                    "doamin:botstop.com",
                    "domain:hcaptcha.com",
                    "domain:hcaptchastatus.com",
                    "domain:gstatic.com",
                    "domain:yahoo.com",
                    "domain:msftconnecttest.com",
                    "domain:msftncsi.com",
                    "domain:apple.com",
                    "domain:detectportal.firefox.com",
                    "domain:networkcheck.kde.org",
	            "domain:www.google.com",
		    "domain:clarity.ms",
                    "domain:ir",
                    "domain:ttvnw.net",
                    "domain:aparat.com",
                    "domain:telewebion.com",
                    "domain:namasha.com",
	            "domain:varzesh3.com"
                ],
                "outboundTag": "direct",
                "type": "field"
            },
	    {
                "domain": [
		    "domain:to",
                    "domain:cfd",
		    "domain:fofa.info"
                ],
                "outboundTag": "proxy11",
                "type": "field"
            },
            {
                "ip": [
                    "geoip:private"
                ],
                "outboundTag": "direct",
                "type": "field"
            },
            {
                "port":"0-65535",
                "balancerTag": "balancer"
            }
        ]
    }
}

### Server config

<details><pre><code>
---
</code></pre></details>

### Client log

2024/12/26 09:50:29 [Info] [1221197485] proxy/vless/outbound: tunneling request to tcp:gateway-us-east1-b.discord.gg:443 via x:443
2024/12/26 09:58:52 [Info] [652915202] proxy/vmess/outbound: tunneling request to tcp:translate.googleapis.com:443 via x:443

### Server log

<details><pre><code>
---
</code></pre></details>

**Comment by Fangliding** [comment]
I didn't see the complete log
According to the only two rows of logs, the two requests were indeed assigned different outbounds
If you have more questions, you can set the `ruleTag` to observe the routing matching situation

**Comment by vrnobody** [comment]
The tags matching algorithm used by observatory and balancer is something like "starts with". So "proxy" can match "proxy1" "proxy11" "proxy-whatever". First change "proxy11" to sth. not starts with "proxy" and see if there are any other problems.
