### ISSUE TITLE
学习xhttp配置，配置报错

### ISSUE THREAD

**Issue by zhfish** [XTLS/Xray-core#4218]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

配置参考的是 https://github.com/XTLS/Xray-core/discussions/4118#discussioncomment-11593313
想做xhttp+Reality 直连
客户端的out标签里，如果不配置privatekey运行会报错，配置了连接会报错
```
Xray 24.12.18 (Xray, Penetrates Everything.) cab2fde (go1.23.4 linux/amd64)
A unified platform for anti-censorship.
2024/12/28 15:28:04 [Info] infra/conf/serial: Reading config: &{Name:/usr/local/etc/xray/config.json Format:json}
Failed to start: main: failed to load config files: [/usr/local/etc/xray/config.json] > infra/conf: Failed to build REALITY config. > infra/conf: empty "privateKey"
```

### 重现方式

curl -x "socks5://127.0.0.1:2080" ipinfo.io 

### 客户端配置

<details><pre><code>
{
  "inbounds": [
    {
      "port": 2080,
      "protocol": "socks",
      "listen": "0.0.0.0",
      "settings": {
        "udp": true
      }
    }
  ],
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "domain": [
          "geosite:cn"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "ip": [
          "geoip:cn",
          "geoip:private"
        ],
        "outboundTag": "direct"
      }
    ]
  },
  "outbounds": [
    {
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "xx.xx.xx.xx",
            "port": 443,
            "users": [
              {
                "id": "dbfd9f87-xxxxxxxxx-aca2b02cf9b6",
                "encryption": "none"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "xhttp",
        "security": "reality",
        "xhttpSettings": {
          "mode": "auto",
          "host": "",
          "path": "/xxx"
        },
        "realitySettings": {
          "target": "www.xxx.com:443",
          "fingerprint": "chrome",
          "serverNames": [
            "www.xxx.com"
          ],
          "publicKey": "HjFyJ4SJynrkxxxxx-I7IPOSGe9k4",
          "privateKey": "yISeHkAwmGXxxxxxx0DjEb3vH-EjEU0", //如果不加这行会报错
          "shortIds": [
            ""
          ]
        }
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    }
  ]
}
</code></pre></details>

### 服务端配置

<details><pre><code>
{
  "inbounds": [
    {
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "dbfd9f87-xxxxxxxxx-aca2b02cf9b6",
            "email": "xxxxx@qq.com"
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "xhttp",
        "security": "reality",
        "realitySettings": {
          "target": "www.xxxxx.com:443",
          "xver": 0,
          "serverNames": [
            "www.xxxxx.com"
          ],
          "privateKey": "yISeHkAwmGxxxxxxxBgAu0DjEb3vH-EjEU0",
          "shortIds": [
            ""
          ]
        },
        "xhttpSettings": {
          "host": "",
          "path": "/xxxx",
          "mode": "auto"
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls",
          "quic"
        ],
        "metadataOnly": false
      }
    }
  ],
  "routing": {
    "rules": [
      {
        "type": "field",
        "protocol": [
          "bittorrent"
        ],
        "outboundTag": "block"
      }
    ]
  },
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {}
    }
  ]
}
</code></pre></details>

### 客户端日志

<details><pre><code>
                                                                [15:19:11]
2024/12/28 15:19:07 [Info] transport/internet/udp: listening UDP on 0.0.0.0:2081
2024/12/28 15:19:07 [Warning] core: Xray 24.12.18 started
2024/12/28 15:19:10 [Info] [1673720657] proxy/socks: TCP Connect request to tcp:ipinfo.io:80
2024/12/28 15:19:10 [Info] [1673720657] app/dispatcher: taking detour [out] for [tcp:ipinfo.io:80]
2024/12/28 15:19:10 [Debug] [1673720657] transport/internet/splithttp: XMUX: creating xmuxClient because xmuxClients is empty
2024/12/28 15:19:10 [Info] [1673720657] transport/internet/splithttp: XHTTP is dialing to tcp:xx.xx.xx.xx:1443, mode stream-one, HTTP version 2, host 103.135.249.29
2024/12/28 15:19:10 [Info] [1673720657] proxy/vless/outbound: tunneling request to tcp:ipinfo.io:80 via xx.xx.xx.xx:443
2024/12/28 15:19:10 [Debug] [1673720657] transport/internet: dialing to tcp:xx.xx.xx.xx:1443
2024/12/28 15:19:10 [Info] [1673720657] transport/internet/splithttp: failed to open https://xx.xx.xx.xx/xxx/?x_padding=0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 > Post "https://xx.xx.xx.xx/xxx/?x_padding=0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000": transport/internet/reality: REALITY: publicKey == nil
2024/12/28 15:19:11 [Info] [1673720657] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
</code></pre></details>

### 服务端日志

<details><pre><code>
N/A，服务端无日志
</code></pre></details>

**Comment by RPRX** [comment]
REALITY 配置了 `target` 时会按服务端配置解析，无关 XHTTP

issue 区不要发非 bug

**Comment by zzlinwq** [comment]
> ### 完整性要求
> * [x]  我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
> * [x]  我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
> * [x]  我搜索了 issues, 没有发现已提出的类似问题。
> * [x]  问题在 Release 最新的版本上可以成功复现
> 
> ### 描述
> 配置参考的是 [#4118 (comment)](https://github.com/XTLS/Xray-core/discussions/4118#discussioncomment-11593313) 想做xhttp+Reality 直连 客户端的out标签里，如果不配置privatekey运行会报错，配置了连接会报错
> 
> ```
> Xray 24.12.18 (Xray, Penetrates Everything.) cab2fde (go1.23.4 linux/amd64)
> A unified platform for anti-censorship.
> 2024/12/28 15:28:04 [Info] infra/conf/serial: Reading config: &{Name:/usr/local/etc/xray/config.json Format:json}
> Failed to start: main: failed to load config files: [/usr/local/etc/xray/config.json] > infra/conf: Failed to build REALITY config. > infra/conf: empty "privateKey"
> ```
> 
> ### 重现方式
> curl -x "socks5://127.0.0.1:2080" ipinfo.io
> 
> ### 客户端配置
> ```
> 
> {
>   "inbounds": [
>     {
>       "port": 2080,
>       "protocol": "socks",
>       "listen": "0.0.0.0",
>       "settings": {
>         "udp": true
>       }
>     }
>   ],
>   "routing": {
>     "domainStrategy": "IPIfNonMatch",
>     "rules": [
>       {
>         "type": "field",
>         "domain": [
>           "geosite:cn"
>         ],
>         "outboundTag": "direct"
>       },
>       {
>         "type": "field",
>         "ip": [
>           "geoip:cn",
>           "geoip:private"
>         ],
>         "outboundTag": "direct"
>       }
>     ]
>   },
>   "outbounds": [
>     {
>       "protocol": "vless",
>       "settings": {
>         "vnext": [
>           {
>             "address": "xx.xx.xx.xx",
>             "port": 443,
>             "users": [
>               {
>                 "id": "dbfd9f87-xxxxxxxxx-aca2b02cf9b6",
>                 "encryption": "none"
>               }
>             ]
>           }
>         ]
>       },
>       "streamSettings": {
>         "network": "xhttp",
>         "security": "reality",
>         "xhttpSettings": {
>           "mode": "auto",
>           "host": "",
>           "path": "/xxx"
>         },
>         "realitySettings": {
>           "target": "www.xxx.com:443",
>           "fingerprint": "chrome",
>           "serverNames": [
>             "www.xxx.com"
>           ],
>           "publicKey": "HjFyJ4SJynrkxxxxx-I7IPOSGe9k4",
>           "privateKey": "yISeHkAwmGXxxxxxx0DjEb3vH-EjEU0", //如果不加这行会报错
>           "shortIds": [
>             ""
>           ]
>         }
>       }
>     },
>     {
>       "tag": "direct",
>       "protocol": "freedom",
>       "settings": {}
>     }
>   ]
> }
> ```
> 
> ### 服务端配置
> ```
> 
> {
>   "inbounds": [
>     {
>       "port": 443,
>       "protocol": "vless",
>       "settings": {
>         "clients": [
>           {
>             "id": "dbfd9f87-xxxxxxxxx-aca2b02cf9b6",
>             "email": "xxxxx@qq.com"
>           }
>         ],
>         "decryption": "none"
>       },
>       "streamSettings": {
>         "network": "xhttp",
>         "security": "reality",
>         "realitySettings": {
>           "target": "www.xxxxx.com:443",
>           "xver": 0,
>           "serverNames": [
>             "www.xxxxx.com"
>           ],
>           "privateKey": "yISeHkAwmGxxxxxxxBgAu0DjEb3vH-EjEU0",
>           "shortIds": [
>             ""
>           ]
>         },
>         "xhttpSettings": {
>           "host": "",
>           "path": "/xxxx",
>           "mode": "auto"
>         }
>       },
>       "sniffing": {
>         "enabled": true,
>         "destOverride": [
>           "http",
>           "tls",
>           "quic"
>         ],
>         "metadataOnly": false
>       }
>     }
>   ],
>   "routing": {
>     "rules": [
>       {
>         "type": "field",
>         "protocol": [
>           "bittorrent"
>         ],
>         "outboundTag": "block"
>       }
>     ]
>   },
>   "outbounds": [
>     {
>       "protocol": "freedom",
>       "settings": {}
>     },
>     {
>       "tag": "block",
>       "protocol": "blackhole",
>       "settings": {}
>     }
>   ]
> }
> ```
> 
> ### 客户端日志
> ```
> 
>                                                                 [15:19:11]
> 2024/12/28 15:19:07 [Info] transport/internet/udp: listening UDP on 0.0.0.0:2081
> 2024/12/28 15:19:07 [Warning] core: Xray 24.12.18 started
> 2024/12/28 15:19:10 [Info] [1673720657] proxy/socks: TCP Connect request to tcp:ipinfo.io:80
> 2024/12/28 15:19:10 [Info] [1673720657] app/dispatcher: taking detour [out] for [tcp:ipinfo.io:80]
> 2024/12/28 15:19:10 [Debug] [1673720657] transport/internet/splithttp: XMUX: creating xmuxClient because xmuxClients is empty
> 2024/12/28 15:19:10 [Info] [1673720657] transport/internet/splithttp: XHTTP is dialing to tcp:xx.xx.xx.xx:1443, mode stream-one, HTTP version 2, host 103.135.249.29
> 2024/12/28 15:19:10 [Info] [1673720657] proxy/vless/outbound: tunneling request to tcp:ipinfo.io:80 via xx.xx.xx.xx:443
> 2024/12/28 15:19:10 [Debug] [1673720657] transport/internet: dialing to tcp:xx.xx.xx.xx:1443
> 2024/12/28 15:19:10 [Info] [1673720657] transport/internet/splithttp: failed to open https://xx.xx.xx.xx/xxx/?x_padding=0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 > Post "https://xx.xx.xx.xx/xxx/?x_padding=0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000": transport/internet/reality: REALITY: publicKey == nil
> 2024/12/28 15:19:11 [Info] [1673720657] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
> ```
> 
> ### 服务端日志
> ```
> 
> N/A，服务端无日志
> ```

你是什么操作系统?  WIN10 ?  怎么看客户端日志？  怎么看服务端日志？

**Comment by zhfish** [comment]
> REALITY 配置了 `target` 时会按服务端配置解析，无关 XHTTP
> 
> issue 区不要发非 bug

多谢R佬，大佬一阵见血，是我抄作业没抄对
