### ISSUE TITLE
ROOT CA

### ISSUE THREAD

**Issue by sing-cube** [XTLS/Xray-core#4219]
你好！
@RPRX ，我想听听您对以下问题的专业意见。
目前，在俄罗斯，访问某些官方网站和平台需要在用户设备上安装政府的根证书。
在使用代理的情况下，这可能带来哪些风险？使用安装了政府根证书的REALITY和TLS是否安全？
谢谢！

**Comment by Fangliding** [comment]
issues区是反馈bug的 不要发这些东西

**Comment by RPRX** [comment]
要求安装根证书一般只是为了能打开特定网站，如果这些根证书被用于中间人攻击，那么 TLS 不安全，但 REALITY 安全

这样的问题应当发到 discussions
