### ISSUE TITLE
Xray 24.12.28版本配置balancers后，启动异常

### ISSUE THREAD

**Issue by sakullla** [XTLS/Xray-core#4222]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

route配置中配置balancers后，启动异常报错“Failed to start: main: failed to create server > core: not all dependencies are resolved.”。
移除掉balancers后正常启动

### 重现方式

按照配置文件在服务器端启动

### 客户端配置

跟客户端无关，服务器端启动异常

### 服务端配置

<details><pre><code>
{
    "log": {
        "loglevel": "warning"
    },
    "routing": {
        "domainStrategy": "IPIfNonMatch",
        "balancers": [
            {
                "tag": "ai-balancer",
                "selector": [
                    "ai"
                ],
                "fallbackTag": "direct",
                "strategy": {
                    "type": "roundRobin",
                    "settings": {}
                }
            }
        ]
    },
    "inbounds": [
        {
            "listen": "0.0.0.0",
            "port": 22222,
            "protocol": "shadowsocks",
            "settings": {
                "password": "11111",
                "method": "aes-128-gcm",
                "network": "tcp,udp",
                "clients": [
                    {
                        "password": "11111",
                        "method": "aes-128-gcm"
                    }
                ]
            },
            "streamSettings": {
                "sockopt": {
                    "tcpFastOpen": true,
                    "tcpMptcp": true,
                    "tcpNoDelay": true
                }
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls",
                    "quic"
                ]
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "streamSettings": {
                "sockopt": {
                    "tcpFastOpen": true
                }
            },
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "tag": "block"
        }
    ]
}
</code></pre></details>

### 客户端日志

无

### 服务端日志

<details><pre><code>
Dec 29 17:37:14 miku-hk systemd[1]: Started xray.service - Xray Service.
Dec 29 17:37:14 miku-hk xray[771]: Xray 24.12.28 (Xray, Penetrates Everything.) 93f72db (go1.23.4 linux/amd64)
Dec 29 17:37:14 miku-hk xray[771]: A unified platform for anti-censorship.
Dec 29 17:37:14 miku-hk xray[771]: 2024/12/29 17:37:14 [Info] infra/conf/serial: Reading config: &{Name:/usr/local/etc/xray/config.json Format:json}
Dec 29 17:37:14 miku-hk xray[771]: Failed to start: main: failed to create server > core: not all dependencies are resolved.
Dec 29 17:37:14 miku-hk systemd[1]: xray.service: Main process exited, code=exited, status=23/n/a
Dec 29 17:37:14 miku-hk systemd[1]: xray.service: Failed with result 'exit-code'.
</code></pre></details>

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/pull/4206/files#issuecomment-2564669962

话说同样配置 v24.12.18 也会报错吗

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/pull/4206#issuecomment-2564669962

话说同样配置 v24.12.18 也会报错吗

**Comment by sakullla** [comment]
> 话说同样配置 v24.12.18 也会报错吗

Xray 24.12.18 (Xray, Penetrates Everything.) cab2fde (go1.23.4 linux/amd64) 这个版本启动没问题

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/pull/4206#issuecomment-2564678435

你试试把我说那两处 RequireFeatures 都改成 OptionalFeatures

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/pull/4206#issuecomment-2564682021

貌似是文档未记载的预期行为，你不用 API 增减出站的话要么一定走要么一定不会走 fallbackTag，所以它被用来赋予新的意义了

**Comment by sakullla** [comment]
> [#4206 (comment)](https://github.com/XTLS/Xray-core/pull/4206#issuecomment-2564682021)
> 
> 貌似是文档未记载的预期行为，你不用 API 增减出站的话要么一定走要么一定不会走 fallbackTag，所以它被用来赋予新的意义了

配置observatory后启动正常

**Comment by RPRX** [comment]
其实我是想把这两处改成 OptionalFeatures，和原来的行为一致，看 @yuhan6665 怎么想，正好我还有些想改的明天可以发个版

**Comment by yuhan6665** [comment]
是的这是 feature 不是 bug
https://github.com/XTLS/Xray-core/commit/84eeb56ae45f48b9ab5166abefb2fda40986b8a8 已经明确说了如果你想要 fallback 功能 也就是说在探测过可用的节点里面 random 或者 roundrobin 那么你必须定义一个 observatory

**Comment by yuhan6665** [comment]
之前不报错是因为 injection 会漏掉 resolution 所以 fallback 实际上没起作用也不报错

**Comment by yuhan6665** [comment]
https://github.com/XTLS/Xray-docs-next/pull/627
