### ISSUE TITLE
Reality的设计思路似乎有漏洞

### ISSUE THREAD

**Issue by caikun233** [XTLS/Xray-core#4226]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

这个问题在设计的时候似乎被忽略了，直奔主题：
首先，在一次请求中，中间人至少能够拿到两个信息：目标IP与TLS SNI。
中间人持有了SNI里的域名，也就持有了这个域名的DNS解析结果，即使它用了CDN也能很快拿到所有IP的列表，而使用了reality的请求目标IP显然不可能在这些DNS解析结果里。
再加上Reality可以模拟一些普通浏览器的Fingerprint，在中间人看来，这是一个普通浏览器用白名单里的域名访问了理应无法正常访问此网站的IP，却在正常的通信。
修改了host确实也会有这种表现，但一般人是不会对白名单里的域名这么操作的，那么这条请求就已经被逮住了。

### 重现方式

well...?

### 客户端配置

<details><pre><code>

</code></pre></details>

### 服务端配置

<details><pre><code>

</code></pre></details>

### 客户端日志

<details><pre><code>

</code></pre></details>

### 服务端日志

<details><pre><code>

</code></pre></details>

**Comment by Fangliding** [comment]
reality只是提供一种安全伪造SNI的方法 其他仁者见仁智者见智
以及issue区是反馈BUG的

**Comment by RPRX** [comment]
我觉得你说的属于潜在的 weakness，因为现实情况比较多变，但是这并不是“Reality的设计思路似乎有漏洞”，而是“偷别人”这种行为固有的一些问题，REALITY 只是尽最大努力提供更好的实践，否则大家遇到封未知流量+SNI 白名单难不成直接躺平吗？

**Comment by osongsongo** [comment]
> 我觉得你说的属于潜在的 weakness，因为现实情况比较多变，但是这并不是“Reality的设计思路似乎有漏洞”，而是“偷别人”这种行为固有的一些问题，REALITY 只是尽最大努力提供更好的实践，否则大家遇到封未知流量+SNI 白名单难不成直接躺平吗？

所以“偷自己”是不是就没有上述问题了

**Comment by RPRX** [comment]
> 所以“偷自己”是不是就没有上述问题了

当然

**Comment by ll11l1lIllIl1lll** [comment]
但是对于一些 CDN 非公开但是就是能用的 IP (eg. Cloudflare London) 被用来优选应该怎么办呢？
可能你会说那封掉也没有影响，那有人报复社会去滥墙 IP 怎么办呢？哈哈。

**Comment by RPRX** [comment]
~~群友想啥呢，谁跟你们一样宅，跨年我肯定出去玩的，跑了，明天再更新 XHTTP 的文章和 v24.12.31 的 release notes~~
