### ISSUE TITLE
`tcpNoDelay`选项无效

### ISSUE THREAD

**Issue by HeXis-YS** [XTLS/Xray-core#4227]
在Xray-core中，`tcpNoDelay`选项用于启用/禁用`TCP_NODELAY`。而在代码中，只写了启用`TCP_NODELAY`的逻辑。
https://github.com/XTLS/Xray-core/blob/93f72db9fd21d7c6d006d0137e74efdd242b8171/transport/internet/sockopt_linux.go#L106-L110
根据Go的代码，`TCP_NODELAY`默认是启用的。
https://github.com/golang/go/blob/194de8fbfaf4c3ed54e1a3c1b14fc67a830b8d95/src/net/tcpsock.go#L289-L290
因此，用户无法通过`tcpNoDelay`禁用`TCP_NODELAY`。~~但仍然可以通过`customSockopt`禁用~~
希望开发者可以修复这个问题（以及文档）。

**Comment by Fangliding** [comment]
有点道理 回头改成默认true填false显式禁用吧

**Comment by RPRX** [comment]
> 默认true填false显式禁用吧

https://github.com/XTLS/Xray-core/pull/3871#issuecomment-2420770309

我们不要搞默认值为 true 的吧，可以把 tcpNoDelay 删掉，由 customSockopt 禁用

**Comment by RPRX** [comment]
今天我还要改下 XMUX，然后发个真 · 24 最后一版

**Comment by Fangliding** [comment]
我还以为按照以前的命名规则要noTcpNoDelay呢()
直接删好像确实好些

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/pull/2021#issuecomment-1566975181

这个 PR 引入的无意义选项，无人用，@Fangliding 你开个 PR 删一下它吧

**Comment by RPRX** [comment]
总之 Xray 遵循 `填 false/0/""  == 没填 == 要取默认值`
