### ISSUE TITLE
Upstream Sent Too Large http2 frame

### ISSUE THREAD

**Issue by changyp6** [XTLS/Xray-core#423]
Hi Developer,
When I enable gPRC transport, when nginx 1.19.8, after running sometime, nginx reports:
```
*187 upstream sent too large http2 frame: 4740180 while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: xxx.xxx.xxx.xxx, request: "POST /upload/TunMulti HTTP/2.0", upstream: "grpc://unix:/run/xray/vless-grpc.socket:", host: "xxx.xxx.xxx.xxx"
```
When this error occurs, gRPC actually doesn't send out any data.

**Comment by changyp6** [comment]
After googling, someone suggests to add following configurations to nginx
```
            proxy_buffer_size       8192k;
            proxy_buffers           8 2048k;
            proxy_busy_buffers_size 8192k;
```
However, no matter how large I increase the buffer, the error always occurs time to time

I don't know if it is possible to limit the sending data size in Xray or not ?

**Comment by kirin10000** [comment]
try
```
    client_max_body_size 0;
```
？

**Comment by changyp6** [comment]
It's my mistake.
I forgot to change "network" from "ws" to "grpc" on my servier side.
After changing it to grpc, no error message are reported again.
