### ISSUE TITLE
IPIfNonMatch路由策略疑似有bug

### ISSUE THREAD

**Issue by CharlesWou** [XTLS/Xray-core#4230]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我提供了完整的配置文件和日志，而不是出于自己的判断只给出截取的部分。
- [X] 我搜索了 issues, 没有发现已提出的类似问题。
- [X] 问题在 Release 最新的版本上可以成功复现

### 描述

当路由规则最后一条是所有流量都proxy的时候，IPIfNonMatch路由策略的“匹配不到域名就解析成IP再匹配”功能会失效。

### 重现方式

测试使用的Core：24.12.18 
使用如下的客户端路由规则配置文件
测试网址：front.liduoxing.com

该网址不在geosite:cn，但其ip:47.103.86.57在geoip:cn的47.96.0.0/11条目中
如果不去掉规则最后一条的所有流量都proxy（catch all），发现会强制走proxy（非预期行为）
如果去掉规则最后一条的所有流量都proxy（catch all），正常走国内direct（预期行为），外网访问也正常没问题

### 客户端配置

<details><pre><code>
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": [
          "geosite:cn"
        ]
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "geoip:cn"
        ]
      },
      {
        "type": "field",
        "port": "0-65535",
        "outboundTag": "proxy"
      }
    ]
  }
</code></pre></details>

### 服务端配置

<details><pre><code>

</code></pre></details>

### 客户端日志

<details><pre><code>

</code></pre></details>

### 服务端日志

<details><pre><code>

</code></pre></details>

**Comment by Fangliding** [comment]
IPIfNonMatch 的意思是没有匹配到任何路由规则 再解析 匹配 catch all 也是路由规则 自然匹配到catch all

**Comment by CharlesWou** [comment]
但我的配置文件里面有geoip:cn的规则，为什么没匹配上呢？

**Comment by Fangliding** [comment]
日志没有是要算命吗

**Comment by CharlesWou** [comment]
```
[Debug] [3033088042] proxy/socks: Not Socks request, try to parse as HTTP request
[Info] [3033088042] proxy/http: request to Method [CONNECT] Host [front.liduoxing.com:443] with URL [//front.liduoxing.com:443]
[Info] [3033088042] app/dispatcher: sniffed domain: front.liduoxing.com
[Info] [3033088042] app/dispatcher: taking detour [proxy] for [tcp:front.liduoxing.com:443]
from 127.0.0.1:59003 accepted //front.liduoxing.com:443 [socks -> proxy]
[Info] [3033088042] transport/internet/tcp: dialing TCP to tcp:test.example.com:443
[Debug] [3033088042] transport/internet: dialing to tcp:test.example.com:443
[Debug] [1213532610] proxy/socks: Not Socks request, try to parse as HTTP request
[Info] [1213532610] proxy/http: request to Method [CONNECT] Host [libcdn.mbimc.com:443] with URL [//libcdn.mbimc.com:443]
[Info] [1213532610] app/dispatcher: sniffed domain: libcdn.mbimc.com
[Info] [1213532610] app/dispatcher: taking detour [direct] for [tcp:libcdn.mbimc.com:443]
from 127.0.0.1:59005 accepted //libcdn.mbimc.com:443 [socks -> direct]
[Info] [1213532610] transport/internet/tcp: dialing TCP to tcp:libcdn.mbimc.com:443
[Debug] [1213532610] transport/internet: dialing to tcp:libcdn.mbimc.com:443
[Info] [1213532610] proxy/freedom: connection opened to tcp:libcdn.mbimc.com:443, local endpoint 10.10.88.17:59006, remote endpoint 47.103.86.57:443
[Info] [1213532610] proxy: CopyRawConn readv
[Info] [3033088042] proxy/vless/outbound: tunneling request to tcp:front.liduoxing.com:443 via test.example.com:443
[Info] [3033088042] proxy: XtlsFilterTls found tls client hello! 571
[Info] [3033088042] proxy: XtlsPadding 571 712 0
[Info] [3033088042] app/proxyman/inbound: connection ends > proxy/http: connection ends > context canceled
[Debug] [1433697135] proxy/socks: Not Socks request, try to parse as HTTP request
[Info] [1433697135] proxy/http: request to Method [CONNECT] Host [front.liduoxing.com:443] with URL [//front.liduoxing.com:443]
[Info] [1433697135] app/dispatcher: sniffed domain: front.liduoxing.com
[Info] [1433697135] app/dispatcher: taking detour [proxy] for [tcp:front.liduoxing.com:443]
from 127.0.0.1:59007 accepted //front.liduoxing.com:443 [socks -> proxy]
[Info] [1433697135] transport/internet/tcp: dialing TCP to tcp:test.example.com:443
[Debug] [1433697135] transport/internet: dialing to tcp:test.example.com:443
[Info] [1433697135] proxy/vless/outbound: tunneling request to tcp:front.liduoxing.com:443 via test.example.com:443
[Info] [1433697135] proxy: XtlsFilterTls found tls client hello! 603
[Info] [1433697135] proxy: XtlsPadding 603 501 0
2024/12/31 11:37:22 [Info] [1433697135] app/proxyman/inbound: connection ends > proxy/http: connection ends > context canceled

```
日志已调节为debug，但貌似并没有路由判断相关信息，直接显示taking detour了

**Comment by Fangliding** [comment]
送进来的请求是 front.liduoxing.com 没有IP
路由模块转一圈 匹配到你最后一条规则 直接出去了 有问题吗
只有没有匹配到任何规则 才会尝试解析IP 然后再走一遍路由模块

**Comment by CharlesWou** [comment]
那是不是最后的proxy是有点“画蛇添足”，如果去掉，会对外网访问产生什么不良影响吗？

**Comment by xiaoxiaomolimicha** [comment]
> 那是不是最后的proxy是有点“画蛇添足”，如果去掉，会对外网访问产生什么不良影响吗？

推荐你去看看不良林讲的*ray路由规则，你的配置有很大的问题，如果你不想看视频，可以去详细看看小小白文档中讲的路由规则，https://www.youtube.com/watch?v=50iVDmqzDW8&t=813s

**Comment by CharlesWou** [comment]
好的，谢谢，我看下视频

> > 那是不是最后的proxy是有点“画蛇添足”，如果去掉，会对外网访问产生什么不良影响吗？
> 
> 推荐你去看看不良林讲的*ray路由规则，你的配置有很大的问题，如果你不想看视频，可以去详细看看小小白文档中讲的路由规则，https://www.youtube.com/watch?v=50iVDmqzDW8&t=813s

**Comment by xiaoxiaomolimicha** [comment]
看完视频你自然就明白了
