### ISSUE TITLE
能否考虑用tar.xz打包linux的安装包？

### ISSUE THREAD

**Issue by UJX6N** [XTLS/Xray-core#43]
xray安装包压缩后

zip格式：8.03MB
xz格式：5.32MB

xz只有zip的2/3大小

现在linux打包挺多用xz格式的

**Comment by rprx** [comment]
其实我也比较喜欢 xz，但这个差距似乎没有太大区别，zip 更通用些。

或者默认 UPX，zip 后会不会小一些？

**Comment by UJX6N** [comment]
我也就是一说，确实zip更通用些

**Comment by wsa01378** [comment]
便携平台建议UPX，OpenWRT的RAM有时仅20-30MB FREE

**Comment by rprx** [comment]
@wsa01378 

这个 U 印象中有人 Speedtest 多线程跑到 260，你试试

**Comment by rprx** [comment]
@wsa01378 

https://t.me/projectXray/53270

的确是 MT7621，请期待 Xray-core v1.1.3，可以先试试群内 pin 的测试版

（如果反馈真实，MT7621 上 15 倍了

**Comment by rprx** [comment]
Linux x64 的初步测试结果：原始程序启动占 20MB 内存，UPX 后占 24MB 内存，静置一段时间后，两者都会占 28MB

但 UPX 对架构的支持不是 Go 的超集，无法同时应用于当前所有二进制，所以最终决定在 release note 写个指引
