### ISSUE TITLE
shadowrocket算macOS客户端吗？

### ISSUE THREAD

**Issue by f2sky** [XTLS/Xray-core#434]
目前macOS客户端支持还是空白状态吗？

**Comment by JimhHan** [comment]
@f2sky macOS 可以直接用brew，或者Qv2ray。Shadowsrocket 可以运行在 Apple Silicon，属于macOS 客户端。
另：建议在 Discussions 询问类似问题

**Comment by f2sky** [comment]
非程序员，电焊工一名
Qv2ray：客户端臃肿不堪，什么东西都往里面塞，无论如何配置不成功；
v2rayU：配置好了勉强能用，就是经常断流，源码都已经不公开了；

没有M1，所以Shadowsrocket也用不上。

另外clash作者也说不跟进 VLESS。

所以现状就是，确实没有可以正常用的macOS客户端。

协议的完善需要越来越多的人用起来，我不认为非程序员的macOS用户是个非常小的群体。
望 XTLS 尽快完善。

目前解决方案：使用VMess，晚上网络效果没有 VLESS 好。

**Comment by Butterflyflower** [comment]
@f2sky Qv2ray是插件形式，需要什么下载什么插件，并不臃肿。

**Comment by JimhHan** [comment]
@f2sky 1: 这里是 Xray-core，请不要在此处请求客户端。
2: 直接运行 core 的人不在少数，自己写配置很简单。
3: macOS 还有 homebrew 等工具。
4: 无论是使用 Xray 还是 macOS，都需要一定的知识基础。如果您不想在这方面花费一点精力，Clash 是个更好的选择。

**Comment by f2sky** [comment]
@JimhHan 
不用以这种高高在上的方式来回答问题。

什么叫「不想在这方面花费一点精力」？为了要用你这个工具，我就必须要学会看代码、运行代码、用指令行配置、运行？

你不会以为macOS用户90%都是程序员吧？

**Comment by crysislinux** [comment]
人家不是告诉你不会搞去就去用clash么，而且这是core，issue不是哪来回答这种问题的。建议锁帖

**Comment by JimhHan** [comment]
@f2sky 

我对我用词不当向您道歉。

有必要强调的一点是，自己写配置很简单，无论是否有足够的能力。macOS 还有 homebrew，automator 等工具，虽然需要一定的相关知识，但是学习成本极低。即使对于没有一点相关知识的人，都能够完成。

> 直接运行 core 的人不在少数，自己写配置很简单。
> macOS 还有 homebrew 等工具

但是确实，我因一时冲动使用了错误的词语与语气，同时也因一时疏忽没有考虑类似您的用户。我在此再次向您道歉。

**Comment by f2sky** [comment]
@JimhHan 道歉就重了，本来就是来讨论的。
我确实也尝试过很多客户端，联系过好几个客户端作者，在并没有好的选择的情况下来这里求助的。

客户端工具不完善，或者作者不跟进、观望，本质上还是协议没有完善好，没有被认可。所以我才来这里发问。

还是感谢大佬的付出。

讨论到此为止吧。

**Comment by JimhHan** [comment]
@f2sky 感谢理解。
缺少 macOS 客户端，是因为苹果过于严格的安全策略，与昂贵的开发者账号导致。并非因为协议不完善。

**Comment by rprx** [comment]
> 客户端工具不完善，或者作者不跟进、观望，本质上还是协议没有完善好，没有被认可。

这个推导是不完全正确的，那么多存在漏洞的老旧协议有简单的客户端，仅仅是因为它们出现得早。

其次，Qv2ray 并不复杂，建议重试一下。
