### ISSUE TITLE
无法放行QUIC流量（直连也不行）

### ISSUE THREAD

**Issue by haomuch** [XTLS/Xray-core#437]
使用https://quic.nginx.org/网站测试，无论流控模式选择xtls-rprx-direct-udp443还是xtls-rprx-direct，而且对https://quic.nginx.org/网站选择直连路由，但是网站仍然显示无法使用QUIC模式，并且testing页面无法加载QUIC流量。
![image](https://user-images.githubusercontent.com/3903046/112408557-fa3bf480-8d52-11eb-837d-d623ff2dfe98.png)
![image](https://user-images.githubusercontent.com/3903046/112408685-38391880-8d53-11eb-87b8-2e140f0b91f7.png)

完全关闭v2ray后，网站QUIC成功开启
![image](https://user-images.githubusercontent.com/3903046/112408748-51da6000-8d53-11eb-9015-43dc3ffc5cca.png)

**Comment by AkinoKaede** [comment]
HTTP 代理不能代理 UDP 流量，建议使用 Socks5
