### ISSUE TITLE
开启 流量嗅探 会造成连接HTTPS网站高延迟.

### ISSUE THREAD

**Issue by z826540272** [XTLS/Xray-core#438]
连接HTTPS网站延迟大概多一个RTT时间以上.
在我的4核PC电脑上，有70-90ms的额外延迟，服务器位置在香港。应该不是CPU性能的问题。

开启 流量嗅探
curl -w "@C:\Windows\time.txt" -o NUL -s -x socks5://127.0.0.1:10808 https://www.google.com/generate_204
     time_namelookup:  0.000056s
        time_connect:  0.010232s
     time_appconnect:  0.162372s
    time_pretransfer:  0.162612s
       time_redirect:  0.000000s
  time_starttransfer:  0.224112s
                     ----------
          time_total:  0.224153s

关闭  流量嗅探
curl -w "@C:\Windows\time.txt" -o NUL -s -x socks5://127.0.0.1:10808 https://www.google.com/generate_204
     time_namelookup:  0.000066s
        time_connect:  0.010193s
     time_appconnect:  0.000000s
    time_pretransfer:  0.000000s
       time_redirect:  0.000000s
  time_starttransfer:  0.000000s
                     ----------
          time_total:  0.154546s

**在 另一台高延迟服务器上进行同样测试，开启 流量嗅探，Https Google 450ms延迟，关闭 流量嗅探 后，延迟降低215ms左右.**

PC端可以关闭 流量嗅探 正常使用，路由器端关闭后会网络会不正常，所以路由器翻墙不好避免这个问题

**Comment by z826540272** [comment]
协议是单VMESS,TCP，无额外配置

**Comment by Acytoo** [comment]
这个没办法避免吧，增加嗅探就是增加几次处理，消耗时间。

能关闭sniffing就关闭，越简单越快。

跟分流，dns有关的东西都难搞。

**Comment by z826540272** [comment]
> 这个没办法避免吧，增加嗅探就是增加几次处理，消耗时间。
> 
> 能关闭sniffing就关闭，越简单越快。
> 
> 跟分流，dns有关的东西都难搞。

http协议 开嗅探没有增加延迟，https增加了，所以可能还可以解决

**Comment by Acytoo** [comment]
> 一会试试http协议

如果你主要想增强的是 https 的性能，建议换成 VLESS + xtls，据说处理 https 加密时，能少几步，快一些。

看看 xtls 的原理，VLESS 与 vmess 的区别，也可以看看这个 issue [关于XTLS的疑问](https://github.com/XTLS/Go/issues/2)。
