### ISSUE TITLE
建议 fallbacks 新增 unix domain socket

### ISSUE THREAD

**Issue by kousyougi** [XTLS/Xray-core#439]
建议fallbacks支援unix domain socket
设定檔写成类似：

"fallbacks": [
                    {
                        "dest": "unix:/tmp/app.socket",
                        "xver": 1
                    }
                ]

想全在xray里面运作，不占用port。

如果可以的话，现有unix domain socket写在streamSettings的network里，不能跟ws搭配。希望inbounds跟outbounds的unix domain socket 可以直接写在listen跟address栏位：
 "inbounds": [
        {
        "listen": "unix:/tmp/app.socket",
        }
]
 "outbounds": [
        {
        "address": "unix:/tmp/app.socket",
        }
]

谢谢

**Comment by AkinoKaede** [comment]
除了出站 address 使用 socket，均已支持

**Comment by JimhHan** [comment]
@kousyougi 
请阅读 [文档](https://xtls.github.io/Xray-docs-next/config/features/fallback.html#fallbacks-%E9%85%8D%E7%BD%AE)

**Comment by kousyougi** [comment]
> @kousyougi
> 请阅读 [文档](https://xtls.github.io/Xray-docs-next/config/features/fallback.html#fallbacks-%E9%85%8D%E7%BD%AE)

感激
