### ISSUE TITLE
[Feature Request] 允许指定网卡出口

### ISSUE THREAD

**Issue by wloot** [XTLS/Xray-core#441]
当前 Outbound 配置有 `sendThrough` 来指定出口IP, 然而这却不适合 wireguard 类似的POINTOPOINT网卡, 直接指定为interface address会无法连接网络.

具体来说, 我想通过这个功能, 让指定流量走cloudflare warp的wireguard网卡(https://github.com/ViRb3/wgcf), 来解锁netflix等流媒体.

curl 有类似的 `--interface` 参数(https://stackoverflow.com/questions/33066407/how-to-use-curl-on-specific-interface), 可以指定接口名或IP, 测试了上述的wireguard网卡, 只有指定接口名称时可以正常连接.

**Comment by gxind** [comment]
感觉可以 用sockopt mark打上标 然后用路由表试试
但是 个人不是很喜欢动路由表，所以。。+1

**Comment by Zzz3m** [comment]
sendthrough+路由表写from就可以或者fwmark也可以

**Comment by wloot** [comment]
> sendthrough+路由表写from就可以或者fwmark也可以

无法实现按域名分流, 而且感觉能软件实现的就没必要动路由表了

**Comment by gxind** [comment]
> > sendthrough+路由表写from就可以或者fwmark也可以
> 
> 无法实现按域名分流, 而且感觉能软件实现的就没必要动路由表了

其实是可以的 你弄两个 outbound free 一个mark上 一个不mark 然后route项分流 
确实 我觉得软件能实现是最好的

**Comment by Zzz3m** [comment]
> > sendthrough+路由表写from就可以或者fwmark也可以
> 
> 无法实现按域名分流, 而且感觉能软件实现的就没必要动路由表了

可以的啊，你将分流的功能交给Xray就行。指定的域名或者tag走sendthrough或者mark，其余的直出就好。@gxind说的对

**Comment by wloot** [comment]
> > > sendthrough+路由表写from就可以或者fwmark也可以
> > 
> > 
> > 无法实现按域名分流, 而且感觉能软件实现的就没必要动路由表了
> 
> 可以的啊，你将分流的功能交给Xray就行。指定的域名或者tag走sendthrough或者mark，其余的直出就好。@gxind说的对

那就是我不懂了。。能不能请教下具体的指令?

**Comment by JimhHan** [comment]
感谢各位，这个功能对于 Xray 较为困难，建议使用路由表。
可以查阅 [新出炉的文档](https://xtls.github.io/Xray-docs-next/document/level-2/redirect.html#_6%E3%80%81%E5%AE%8C%E6%88%90-wireguard-%E7%9B%B8%E5%85%B3%E8%AE%BE%E7%BD%AE)。

**Comment by Zzz3m** [comment]
{
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": <port>,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIPv6"
        //设置默认用户走指定方式”UseIPv6”或者”UseIPv4”
      }
    },
    {
      "protocol": "freedom",
      "tag": "wg0",
      "streamSettings": {
        "sockopt": {
          "mark": <mark>
        }
      },
      "settings": {
        "domainStrategy": "UseIPv6"
      }
      //设置fwmark为<mark>的用户走指定方式”UseIPv6””UseIPv4”
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "policy": {
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "type": "field",
        "outboundTag": "wg0",
        "inboundTag": [
          "<inboundTag>"
          //需要之前在inbound中指定好Tag，我这里是api生成的,还可以添加域名等等
        ]
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ]
  },
  "stats": {}
}

**Comment by aeeq** [comment]
有方法实现，gost 有现成的
[dialer_linux.go](https://github.com/go-gost/core/blob/c2a1dd2a89cbdf6c0d645a9d04a69ef09aff57d0/common/net/dialer/dialer_linux.go#L7)
