### ISSUE TITLE
vless+gRPC模式下设置tls minVersion参数无效

### ISSUE THREAD

**Issue by Bearljj** [XTLS/Xray-core#442]
这两天在试用gRPC，速度确实挺快，但是发现建立连接时还是tls1.2，不知道是不是具有普遍性：
这是服务端设置的片段
...
"tlsSettings": {
                    "allowInsecure": false,
                    "minVersion": "1.3",
                    "alpn": [
                        "h2"   
                    ],
...

使用起来后wiresharp抓包发现

![image](https://user-images.githubusercontent.com/43111343/112564122-a0e8c980-8e15-11eb-9b2b-10a05ec9625c.png)

**Comment by JimhHan** [comment]
@Bearljj 

是 TLS1.3 与 WireShark 的特性，[ref](https://networkengineering.stackexchange.com/questions/55752/why-does-wireshark-show-version-tls-1-2-here-instead-of-tls-1-3)

**Comment by Bearljj** [comment]
经过观察发现确实挺奇怪，也有1.3的连接，而且仔细看握手的往返，虽然标识1.2，但行为逻辑又跟1.3很像，不知道具体逻辑是啥
