### ISSUE TITLE
Bug可能提示

### ISSUE THREAD

**Issue by Theddeus** [XTLS/Xray-core#447]
![IMG_20210326_172653.jpg](https://user-images.githubusercontent.com/77157598/112719679-08496b00-8f35-11eb-8d88-de69989f0444.jpg)
使用上述文件所示配置，xray服务器端提示"shadowsocks password unspecified"使用v2raycore运行相同配置文件正常，提示xraycore的shadowsocks配置文件读取可能存在bug。
以上。

**Comment by rprx** [comment]
setings -> settings

**Comment by Theddeus** [comment]
谢谢大佬解答&&对不起，提了个智障的issue
