### ISSUE TITLE
[猜测] 无法嗅探出quic连接的sni

### ISSUE THREAD

**Issue by wloot** [XTLS/Xray-core#448]
一个多ip服务器, 其中一个ip被google识别成了大陆, 无法使用youtube premium, 于是服务器xray设置了分流youtube域名, 并开启嗅探http, tls.

安卓手机使用clash for android, 一切正常(通过打开youtube app, 然后测试youtube premium)
使用v2rayng(xray内核1.4.0), youtube premium无法使用.

查看服务器连接日志发现: 
`accepted udp:173.194.5.172:443`
似乎是未能嗅探出quic连接的sni

* 能否修复嗅探
* 或能否在inbound默认禁用quic

**Comment by wloot** [comment]
简单测试了下, 在服务端禁用443端口的udp后恢复正常.

可不可以考虑vmess/vless等tcp协议默认禁用quic? 毕竟quic over tcp相当于两套流控了.

**Comment by JimhHan** [comment]
1. sniffing 不支持 QUIC。(duplicate with https://github.com/XTLS/Xray-core/issues/328)
2. 嗅探结果不会体现在 access log 上。
3. 可以使用路由禁用 quic。
