### ISSUE TITLE
关于xver的问题

### ISSUE THREAD

**Issue by monsterzzzz** [XTLS/Xray-core#45]
关于回落设置，发现一个问题，如果在fallbacks里面设置了xver，回落到本机上的websocket就不正常，服务端返回为"invalid request version"，去掉xver就正常了，具体配置如下：
{
    "log": {
        "loglevel": "warning"
    }, 
    "inbounds": [
        {
            "listen": "0.0.0.0", 
            "port": 443, 
            "protocol": "vless", 
            "settings": {
                "clients": [
                    {
                        "id": "af0eab97-85e2-46ac-ac23-da430b5b7ef1", 
                        "level": 0, 
                        "email": "a@b.com",
                        "flow":"xtls-rprx-direct"
                    }
                ], 
                "decryption": "none", 
                "fallbacks": [
                    {
                        "path": "/ray",
                        "dest": 17777,
                        **"xver": 1**
                    },                 	
                    {
                        "dest": 17666
                    }                    
                ]
            }, 
            "streamSettings": {
                "network": "tcp", 
                "security": "xtls", 
                "xtlsSettings": {
                    "serverName": "example.com", 
                    "alpn": [
                        "h2", 
                        "http/1.1"
                    ], 
                    "certificates": [
                        {
                            "certificateFile": "/etc/xray/cert/fullchain.cer", 
                            "keyFile": "/etc/xray/cert/private.key"
                        }
                    ]
                }
            }
        },
        {
            "port": 17777,
            "listen": "127.0.0.1",
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "69065602-0043-4b2b-b743-7c67fb8482dc",
                        "level": 0,
                        "email": "b@b.com"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "ws",
                "security": "none",
                "wsSettings": {
                    "path": "/ray"
                }
            }
        }
    ], 
    "outbounds": [
        {
            "protocol": "freedom", 
            "settings": { }
        }
    ]
}

**Comment by monsterzzzz** [comment]
> 如何 xver为 1或2
> 被回落的网站需要开启接受 proxy protocol

还真是这样

**Comment by badO1a5A90** [comment]
> > 如何 xver为 1或2
> > 被回落的网站需要开启接受 proxy protocol
> 
> 还真是这样

这本来就是这个设置的意义,向后传递真实的源头IP.
1或2是指proxy protocol的版本号
