### ISSUE TITLE
splice模式下进行较大的git clone操作会断开

### ISSUE THREAD

**Issue by vojeus** [XTLS/Xray-core#453]
vless+tls+xtls-rprx-splice
clone一个400M的repo,  总是无法完成。
git的提示
fatal: The remote end hung up unexpectedly
fatal: early EOF

切换到xtls-rprx-direct下没有问题。

**Comment by rprx** [comment]
Xray-core 会关闭 5 分钟上下行均不活跃的连接，Splice 会被认为是下行不活跃（因为交给了系统），而上行一般不会 5 分钟不活跃

但是 git clone 这类场景就比较尴尬，目前还没有想到比较合适的解决方案
