### ISSUE TITLE
shadowsocks aead可以被caddy反向代理吗？

### ISSUE THREAD

**Issue by Dimitri2020007** [XTLS/Xray-core#457]
{
    "inbounds": [
        {
            "listen": "",
            "protocol": "shadowsocks",
            "settings": {
                "clients": [
                    {
                        "password": "",
                        "method": ""
                    }
                ],
                "network": "tcp,udp"
            },
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ]
}

caddy反代不知道咋写没贴出来

**Comment by JimhHan** [comment]
@Dimitri2020007 不可以 试试ws

**Comment by Dimitri2020007** [comment]
shadowsocks能用ws?
