### ISSUE TITLE
升级到1。4。1后 设置变XRAY_BROWSER_DIALER之后上不去网

### ISSUE THREAD

**Issue by shanshan9231** [XTLS/Xray-core#463]
升级到1。4。1后，原先我的所有WS配置全都连不上。
换回1。4。0就正常。
具体的表现是 服务端收好像收不到客端的数据，
以上服务端是1。4。1
具体客端配置如下
{
"log": {
"loglevel": "none"
},
  "inbounds": [ 
    { 
      "tag": "10809",
      "port": 10909, 
      "listen": "0.0.0.0", 
      "protocol": "socks", 
       "sniffing":{
          "enabled": true,
          "destOverride": ["http", "tls"]
      },
      "settings": { 
        "auth": "noauth", 
      "udp": true,
      "ip":"0.0.0.0"
      } 
    },
    {
      "tag": "65535",
      "listen": "0.0.0.0",
      "port": "65535", 
      "protocol": "http"
    }
  ], 
  "outbounds": [ 
    { 
      "tag": "80",
"protocol": "vmess",
"settings": {
"vnext": [
{
"address": "IP",
"port": PORT,
"users": [
{
"id": "UUID"
}
]
}
]
},
      "streamSettings": { 
        "network": "ws", 
        "security": "tls", 
        "tlsSettings": { 
          "allowInsecure": true, 
          "serverName": "ADDRESS" 
        }, 
        "wsSettings": { 
          "connectionReuse": true, 
          "path": "1234", 
            "headers": { 
              "Host": "ADDRESS" 
            } 
        } 
      }
    },
    { 
      "tag": "hole", 
      "protocol": "blackhole", 
      "settings": { 
      }
    },
    { 
      "tag": "direct", 
      "protocol": "freedom", 
      "settings": { 
      } 
    }
  ]
}

**Comment by rprx** [comment]
检查下是否设置了环境变量 `XRAY_BROWSER_DIALER`？

**Comment by shanshan9231** [comment]
是这个问题。谢谢

**Comment by rprx** [comment]
如果你设置了这个环境变量，则必须在 Xray-core 运行后先用浏览器打开那个网页。
