### ISSUE TITLE
build error on Go 1.16

### ISSUE THREAD

**Issue by rurirei** [XTLS/Xray-core#464]
though xray-core requires go 1.16 (introduced in #421), there is a bug of go 1.6 https://github.com/golang/go/issues/44129, i met this on gomobile.

this is not bug of xray-core.

@yuhan6665 do you met this?

@rprx will possible to replace `embed` to others?

p.s. go 1.15 works on v2ray-core.

```
# Go 1.16
Error: ../../../../pkg/mod/golang.org/x/mobile@v0.0.0-20210220033013-bdb1ca9a1e08/internal/importers/ast.go:37:2: missing go.sum entry for module providing package golang.org/x/tools/go/packages (imported by golang.org/x/mobile/cmd/gobind); to add:
	go get golang.org/x/mobile/cmd/gobind@v0.0.0-20210220033013-bdb1ca9a1e08
gomobile: go install -v golang.org/x/mobile/cmd/gobind failed: exit status 1

# Go 1.15
/rurirei/tmp/build/go/src/github.com/xtls/xray-core/transport/internet/websocket/dialer.go:5:2: package embed is not in GOROOT (/rurirei/tmp/usr/bin/go/1.15.10/x64/src/embed)
```

**Comment by ShinyGwyn** [comment]
go 1.16.2

**Comment by rurirei** [comment]
@ShinyGwyn 1.16.2 v.s. 1.15.10

**Comment by ShinyGwyn** [comment]
> @ShinyGwyn 1.16.2 v.s. 1.15.10

build with -mod=mod ?

**Comment by rprx** [comment]
Go 1.16+ 默认启用 go module，试试改成 auto？

**Comment by rurirei** [comment]
@rprx this is on Go Modules.

**Comment by rurirei** [comment]
conc: Go 1.16 default to enables Go Modules, as disables it to solves this.

p.s. i do not enjoy in deprecated `go get`.

**Comment by rprx** [comment]
@rurirei 我猜应该不需要 off，改为 auto 即可像使用 Go 1.15.x 一样编译，彻底解决要等 gomobile 的修复了。

**Comment by rurirei** [comment]
@rprx `auto` causes other errors.

**Comment by yuhan6665** [comment]
@rurirei @2dust I think I ran into the same issue with you when doing `gomobile init` from the command line. Then I found a fix:

1.  Change the xray-core to the last working version, where go sum have all the dependencies
2.  Open project in VS code
3.  When I open go.mode, the UI hint me to "update dependencies"
4.  It magically fix it

https://github.com/2dust/AndroidLibXrayLite/pull/5

**Comment by rurirei** [comment]
@yuhan6665 what project do dependency update for?

**Comment by yuhan6665** [comment]
> @yuhan6665 what project do dependency update for?

AndroidLibXrayLite.
I updated Golang to 1.16.2 and gomobile a couple weeks ago. Maybe that's why it is working for me

**Comment by rurirei** [comment]
@yuhan6665 i'm in trouble. 😿

**Comment by hzjnet** [comment]
> Go 1.16+ 默认启用 go module，试试改成 auto？

经过测试不行，换成15版本也是
