### ISSUE TITLE
panic: XTLS Splice: not TCP inbound

### ISSUE THREAD

**Issue by jiahaoliang** [XTLS/Xray-core#465]
System: ``uname -a``
```Linux raspberrypi1 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux```

Description: 
I use a Raspberry Pi 3B+ as a proxy. It is configured with multiple inbounds and an outbound of XTLS with xtls-rprx-splice to my remote VPS.
Whenever a client connect to my Pi, Xray just keeps crashing and systemctl restart it every second. I don't see anything special from access.log or error.log. But journalctl shows following:
``journalctl -xe``
```
Apr 01 18:29:30 raspberrypi1 xray[4929]: panic: XTLS Splice: not TCP inbound
Apr 01 18:29:30 raspberrypi1 xray[4929]: goroutine 56 [running]:
Apr 01 18:29:30 raspberrypi1 xray[4929]: github.com/xtls/xray-core/proxy/vless/encoding.ReadV.func1(0x2888398, 0xa4b68c, 0x27181e0, 0xa498ac, 0x2131570, 0xa4a47c, 0x28883a8, 0x2651f00, 0xa42af0, 0x271f950, ...)
Apr 01 18:29:30 raspberrypi1 xray[4929]:         github.com/xtls/xray-core/proxy/vless/encoding/encoding.go:209 +0x5cc
Apr 01 18:29:30 raspberrypi1 xray[4929]: github.com/xtls/xray-core/proxy/vless/encoding.ReadV(0xa42848, 0x28884d8, 0xa420a0, 0x2714230, 0xa42af0, 0x271f950, 0x2888398, 0xa4a47c, 0x28883a8, 0xa498ac, ...)
Apr 01 18:29:30 raspberrypi1 xray[4929]:         github.com/xtls/xray-core/proxy/vless/encoding/encoding.go:235 +0x74
Apr 01 18:29:30 raspberrypi1 xray[4929]: github.com/xtls/xray-core/proxy/vless/outbound.(*Handler).Process.func3(0x0, 0x0)
Apr 01 18:29:30 raspberrypi1 xray[4929]:         github.com/xtls/xray-core/proxy/vless/outbound/outbound.go:240 +0x300
Apr 01 18:29:30 raspberrypi1 xray[4929]: github.com/xtls/xray-core/common/task.OnSuccess.func1(0x18100053, 0x2454140)
Apr 01 18:29:30 raspberrypi1 xray[4929]:         github.com/xtls/xray-core/common/task/task.go:12 +0x24
Apr 01 18:29:30 raspberrypi1 xray[4929]: github.com/xtls/xray-core/common/task.Run.func1(0x28883c8, 0x289eb40, 0x20f48e0)
Apr 01 18:29:30 raspberrypi1 xray[4929]:         github.com/xtls/xray-core/common/task/task.go:28 +0x1c
Apr 01 18:29:30 raspberrypi1 xray[4929]: created by github.com/xtls/xray-core/common/task.Run
Apr 01 18:29:30 raspberrypi1 xray[4929]:         github.com/xtls/xray-core/common/task/task.go:27 +0x10c
Apr 01 18:29:30 raspberrypi1 systemd[1]: xray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 01 18:29:30 raspberrypi1 systemd[1]: xray.service: Unit entered failed state.
Apr 01 18:29:30 raspberrypi1 systemd[1]: xray.service: Failed with result 'exit-code'.
Apr 01 18:29:31 raspberrypi1 systemd[1]: xray.service: Service hold-off time over, scheduling restart.
Apr 01 18:29:31 raspberrypi1 systemd[1]: Stopped Xray Service.
```

---------------
Any idea how to fix it?

**Comment by JimhHan** [comment]
@jiahaoliang 使用了xtls不支持的传输方式。
Closed.

**Comment by rprx** [comment]
@jiahaoliang Splice 对入站有要求

**Comment by jiahaoliang** [comment]
@JimhHan @rprx Got it. Thank you guys for the quick response.

For anyone else may checkout this issue in the future,
https://xtls.github.io/config/outbound-protocols/vless/#userobject

---
Splice 是 Linux Kernel 提供的函数，系统内核直接转发 TCP，不再经过 Xray 的内存，大大减少了数据拷贝、CPU 上下文切换的次数。

Splice 模式的的使用限制：

Linux 环境
**入站协议为 Dokodemo door、Socks、HTTP 等纯净的 TCP 连接, 或其它使用了 XTLS 的入站协议**
出站协议为 VLESS + XTLS 或 Trojan + XTLS
此外，使用 Splice 时网速显示会滞后，这是特性，不是 bug。

需要注意的是，使用 mKCP 协议时不会使用 Splice（是的，虽然没有报错，但实际上根本没用到）。

**Comment by jiahaoliang** [comment]
@rprx @JimhHan, one more question, is it possible to config Xray the following way,

a. Splice compatible inbounds (Dokodemo door、Socks、HTTP, XTLS ) -> router rules decides "direct" or "proxy" -> if "proxy" matches, route to the rprx-splice outbound;
b. Splice incompatible inbounds (all others) -> router rules decides "direct" or "proxy" -> if "proxy" matches, route to a rprx-direct outbound;
