### ISSUE TITLE
dns服务器clientIp配置项不起作用

### ISSUE THREAD

**Issue by ggggle** [XTLS/Xray-core#466]
Xray版本1.4.0
搭建透明代理，国内站点dns通过223.5.5.5解析，配置clientIp为124.160.189.1，通过抓包查看发往223.5.5.5的dns请求，并没有Client Subnet选项。
![image](https://user-images.githubusercontent.com/8306108/113373519-98583c00-939d-11eb-8aa9-9387b4da1b79.png)

使用 dig www.baidu.com @223.5.5.5 +subnet=124.160.189.1 +short 请求可以看到对应选项
![image](https://user-images.githubusercontent.com/8306108/113373399-53340a00-939d-11eb-8792-9ef8e9eda0e8.png)

![image](https://user-images.githubusercontent.com/8306108/113373649-ecfbb700-939d-11eb-9389-4bd2d2a94178.png)

**Comment by JimhHan** [comment]
`clientIp` 放错地方了。
https://xtls.github.io/Xray-docs-next/config/dns.html#dnsobject

**Comment by ggggle** [comment]
> `clientIp` 放错地方了。
> https://xtls.github.io/Xray-docs-next/config/dns.html#dnsobject

https://www.v2fly.org/config/dns.html#dnsobject
xray不打算支持该功能吗,https://github.com/v2fly/v2ray-core/pull/504

**Comment by JimhHan** [comment]
@ggggle @AkinoKaede 正在做 DNS App 的重构，可以加一下

**Comment by AkinoKaede** [comment]
try to use #400

**Comment by ggggle** [comment]
thanks
