### ISSUE TITLE
xray是否有可能支持dropbear协议

### ISSUE THREAD

**Issue by jacklee789** [XTLS/Xray-core#468]
最近试用dropbear协议80端口，感觉突破封锁能力接近trojan协议443端口，比ss强不少。

网上有较多dropbear免费资源，即便是免费服务器，晚高峰也可以流畅看youtube1080p视频。

目前trojan协议用客户端v2rayn，dropbear协议用客户端Bitvise。

请问xray是否有可能支持dropbear协议？

如果可以支持，那么只需用v2rayn客户端就可以同时搞定trojan和dropbear。

**Comment by AkinoKaede** [comment]
我没记错的话 Dropbear 是一个 SSH 实现，所以是 SSH Tunnel？

**Comment by jacklee789** [comment]
我是技术外行，只知道用起来确实速度快。

这里是免费节点     https://cloudssh.us/

这里是客户端      https://www.bitvise.com/ssh-client-download

**Comment by AkinoKaede** [comment]
> 我是技术外行，只知道用起来确实速度快。
> 
> 这里是免费节点 https://cloudssh.us/
> 
> 这里是客户端 https://www.bitvise.com/ssh-client-download

那确认是 SSH Tunnel 了，之前有讨论过，特征太明显了，大概是不支持的。不过如果你有兴趣的话可以提交 PR
