### ISSUE TITLE
1.4.2版本无法加载没有扩展名的json文件

### ISSUE THREAD

**Issue by ddvcx** [XTLS/Xray-core#469]
更新1.4.2后, 运行不成功, 命令如下
/usr/local/x run -config /usr/local/xc
把xc改名为xc.json可以运行
之前版本一直不需要扩展名也能加载配置的, 希望能修复下这个bug

**Comment by AkinoKaede** [comment]
这不是 bug 而是 feature，因为没有扩展名所以无法自动获取到配置文件的格式，你可以使用 --format=json 参数
