### ISSUE TITLE
1.1.2 使用xtls 只要config中出现mux设定 就会无法执行

### ISSUE THREAD

**Issue by aaronchin** [XTLS/Xray-core#47]
使用qv2ray搭配1.1.2版xray核心+xtls（其他版本没尝试过）只要enable mux就会出现
Configuration Error "[Info] main/jsonem: Reading config: C:/Users/admin/AppData/Local/qv2ray/generated/config.gen.json"
V2Ray kernel failed to start
在openwrt x86使用shadowsocksr+中使用1.1.2 core+xtls，因为ssr+会自己把mux:false加到设定档中同样会造成1.1.2 xray core无法启动，只有在config中将mux删除才能启动1.1.2版xray

**Comment by rprx** [comment]
XTLS 不支持 Mux，Mux `"enabled": false` 不会导致无法启动。

https://github.com/rprx/v2fly-github-io/blob/master/docs/config/protocols/vless.md#xtls-%E9%BB%91%E7%A7%91%E6%8A%80

**Comment by aaronchin** [comment]
v2-ssr-retcp.json 部分内容如下
{
   "outbound": {
     "settings": {
       "vnext": [
         {
           "port": 443,
           "users": [
             {
               "flow": "xtls-rprx-splice",
               "encryption": "none",
               "id": "x"
             }
           ],
           "address": "x"
         }
       ]
     },
     **"mux": false,**
     "protocol": "vless",
     "streamSettings": {
       "network": "tcp",
       "tlsSettings": {
         "serverName": "x",
         "allowInsecure": false
       },
       "xtlsSettings": {
         "serverName": "x",
         "allowInsecure": false
       },
---------------------------------------------
当执行带有"mux": false的config的时候 会显示如下错误
root@OpenWrt:/tmp/etc# /usr/bin/xray -config v2-ssr-retcp.json
Xray 1.1.2 (OpenWrt) Custom (go1.15.5 linux/amd64)
A unified platform for anti-censorship.
panic: infra/conf/serial: failed to read config file at line 18 char 17 > json: cannot unmarshal bool into Go struct field OutboundDetourConfig.outbound.mux of type conf.MuxConfig

goroutine 1 [running]:
github.com/xtls/xray-core/common.Must(...)
        github.com/xtls/xray-core/common/common.go:26
github.com/xtls/xray-core/main/jsonem.init.0.func1(0xd727e0, 0xc0001b4c80, 0x7fffe3188ec4, 0x4, 0xc00007fdd0)
        github.com/xtls/xray-core/main/jsonem/jsonem.go:27 +0x473
github.com/xtls/xray-core/core.LoadConfig(0xed7f4d, 0x4, 0x7fffe3188eb7, 0x11, 0xd727e0, 0xc0001b4c80, 0xc00013fd30, 0xccfb86, 0xffd1a0)
        github.com/xtls/xray-core/core/config.go:67 +0x262
main.startXray(0x6708af, 0x0, 0xc0001bc180, 0x164)
        github.com/xtls/xray-core/main/run.go:158 +0x12e
main.executeRun(0x14fd100, 0xc0001ba4b0, 0x0, 0x0)
        github.com/xtls/xray-core/main/run.go:65 +0x4a
github.com/xtls/xray-core/main/commands/base.Execute()
        github.com/xtls/xray-core/main/commands/base/execute.go:64 +0x285
main.main()
        github.com/xtls/xray-core/main/main.go:22 +0x16e

**Comment by rprx** [comment]
@aaronchin 

Mux 配置格式错了，即使不是 XTLS，也启动不了。

**Comment by aaronchin** [comment]
了解 这应该是shadowsocksr+的问题 谢谢

**Comment by rprx** [comment]
@aaronchin 

建议向他们反馈一下

**Comment by aaronchin** [comment]
已经去反馈了
