### ISSUE TITLE
fallback到nginx代理端口报400

### ISSUE THREAD

**Issue by HerzSchnee** [XTLS/Xray-core#470]
fallback回落到nginx代理的8900端口，http访问域名后能跳转https，但是https会报400
xray配置如下：
{
  "log": {
    "loglevel": "warning",
    "access": "/var/log/xray/access.log",
    "error": "/var/log/xray/error.log"
  },
  "inbounds": [
    {
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "id-id-id",
            "flow": "xtls-rprx-direct",
            "level": 0,
            "email": "love@example.com"
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "dest": 8900,
            "xver": 1
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
          "alpn": [
            "http/1.1"
          ],
          "certificates": [
            {
              "certificateFile": "/etc/ssl/cert.pem",
              "keyFile": "/etc/ssl/key.pem"
            }
          ]
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom"
    }
  ]
}

nginx配置如下:
server {
    listen       80;
    server_name  example.com www.example.com;

    return 301 https://$http_host$request_uri;
}
server {
    listen       8900;
    server_name  localhost;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

实在想不到问题出在哪里，请帮忙查看一下原因，多谢了

**Comment by ggggle** [comment]
fallbacks的xver改成0，或者nginx配置处理proxy协议
https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/

**Comment by HerzSchnee** [comment]
> 
> 
> fallbacks的xver改成0，或者nginx配置处理proxy协议
> https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/

非常感谢！
