### ISSUE TITLE
【功能需求】关于outbounds中的DNS协议

### ISSUE THREAD

**Issue by wutongskype** [XTLS/Xray-core#471]
怎么说呢,我感觉目前来说,现在DNS服务功能比较鸡肋,
按白话文教(https://guide.v2fly.org/basics/dns.html)程里面只能拦截Type A和Type AAAA
即使配合dokodemo-door协议进行对外服务也有不完善的地方.
而且只作用于outbounds就只作为V2内置的服务使用,无法给操作系统或对外服务使用.
其settings中address还不支持DOT或者DOH.
原版作为outbounds如下:
{
  "tag":"ChinaDNSout",
  "protocol":"dns",
  "settings":{"network": "tcp","address": "8.8.8.8", "port": 53}  ///---目前此处address还无法使用DOH DOT地址.
}

**Comment by wutongskype** [comment]
建议增加个locallisten功能,从而达到监听一个本地端口,达到对外服务和转发的功能.并且在settings的address中增加DOT/DOH/DOQ等未来DNS协议的支持.
配置模板如下:
{
	"tag":"*****DNSout",
	"protocol":"dns",
	"settings": {
		"locallisten":"127.0.0.1:53"		///新增监听本地IP和端口达到对外服务的作用.
		"network": "tcp,udp", 				///接受何种查询
		"address": "8.8.8.8",					///转发地址,保留普通DNS,增加DOT,DOH,DOQ的支持
										///参考模式1	"address": "https://dns.alidns.com/dns-query", DOH协议
										///参考模式2	"address": "https://dns.google/dns-query", DOH协议
										///参考模式3	"address": "tls://dns.google:853", DOT协议
										///参考模式4	"address": "doq://dns.google:853xxx", DOQ协议
                    "port": 53, ///为可选配置,转发目标的端口,非标准端口时使用
	},
	"proxySettings":{"tag":"WS+TLSout","transportLayer":true}
            ///使用某出墙协议作为前置代理或者使用direct达到墙内DNS直连,国外DNS走隧道.
}

**Comment by wutongskype** [comment]
然后配合DNS模块完整配置如下:
"outbounds": [
							{
								"tag":"ChinaDNSout", ///国内DNS
								"protocol":"dns",
								"settings": {
													"locallisten":"127.0.0.1:53"		
													"network": "tcp,udp", 				
													"address": "https://dns.alidns.com/dns-query",	 ///国内DNS使用国内阿里DOH
													///"port": 53, ///此处使用了DOH所以注销此处端口设置
								},
								"proxySettings":{"tag":"direct","transportLayer":true}	///此处为国内DNS所需指定前置代理为直连
							},
							{
								"tag":"GlobalDNSout", ///国外DNS
								"protocol":"dns",
								"settings": {
													"locallisten":"127.0.0.2:53"		
													"network": "tcp,udp", 				
													"address": "https://dns.google/dns-query",	///国外DNS使用GoogleDOH
													///"port": 53, ///此处使用了DOH所以注销此处端口设置
								},
								"proxySettings":{"tag":"WS+TLS","transportLayer":true}	///此处为国外DNS,指定某出墙隧道tag
							},
							

],

"dns":	{
				"hosts": {"xxxxxxxxxx.com": "127.0.0.1"},
				"servers": [
									{
										"address": "127.0.0.1:53",  ///国内阿里DNS 
										///"port": 53, ///使用DOH模式时无效
										"domains": ["geosite:cn"],
										"expectIPs": ["geoip:cn"]
									},
									{
										"address": "127.0.0.2:53", ///国外GoogleDNS
										"port": 53, ///使用DOH模式时无效
										"domains": [
														"geosite:geolocation-!cn",
														"geosite:speedtest",
														"ext:h2y.dat:gfw"
										]
									},
				],
				"disableCache":true
			
}

或者直接在inbounds中增加个DNS协议,然后用Route\Rule功能进行国内国外分流,从而达到防污染+加密+隐私的功能.
其实老外有个DNSproxy项目(https://github.com/AdguardTeam/dnsproxy)
但是目前这货还没有使用前置代理的功能,也没有国内国外分流的功能.
但是有个edns/edns-addr的功能,还能解析的不那么离谱,可以参考一哈.
--edns             Use EDNS Client Subnet extension
--edns-addr=       Send EDNS Client Address

**Comment by JimhHan** [comment]
请使用 dokodemo+routing

**Comment by wutongskype** [comment]
> 请使用 dokodemo+routing

问题是使用dokodemo，也无法做到完美国内外分流，如果我在dns中指定多个doh服务器，怎么分流呢

**Comment by JimhHan** [comment]
@wutongskype 内置dns分流

**Comment by wutongskype** [comment]
如果第一dns服务器指定为国内的，那我访问的域名是不是都要去它上面逛一圈，这样就无法保证隐私性

**Comment by JimhHan** [comment]
@wutongskype 可以设置域名优先查询服务器

**Comment by rurirei** [comment]
@wutongskype you made much misunderstanding on _ray dns app, as you need to use other dns app. github.com/coredns/coredns recommend.
