### ISSUE TITLE
从v2ray->xray的调整问题

### ISSUE THREAD

**Issue by Cirooo** [XTLS/Xray-core#474]
我使用nginx作为入口，接管443端口及配置了相应的数字证书，反向代理了websocket转发到原v2ray的一个端口，如12121。
v2ray这边只配置了监听12121，一个用户，以及ws协议。
"inbounds": [
    {
      "port": 12121, // 服务器监听端口
      "protocol": "vmess",    // 主传入协议
      "settings": {
        "clients": [
          {
            "id": "myuserid",  // 用户 ID，客户端与服务器必须相同
            "alterId": 64
          }
        ]
      },
      "streamSettings":{
        "network":"ws",
        "wsSettings":{
          "path":"/randompath"
        }
      }
    }
  ],

最近由于android端升级需要用到xray，服务端装好也用了这套配置，参照example把client中的alterId去掉改成level，协议改成vless，streamSettings中加入security none。结果不好使。
app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://mydomain.com/randompath): 502 Bad Gateway > websocket: bad handshake] > common/retry: all retry attempts failed
我肯定是接着用nginx作为入口的，所以不会使用xray接管443。fallback分发功能在我这种情况下用不着，xray直接处理12121监听到的内容即可。
这种情况我需要怎么改才能顺利切换服务核心？

**Comment by rurirei** [comment]
> 最近由于android端升级需要用到xray，服务端装好也用了这套配置

are you on v2rayNG ::)

**Comment by JimhHan** [comment]
>  502 Bad Gateway

请检查xray服务端是否启动，是否正确设定端口。

注：如果检查无误，请重新打开issue，并提供服务端日志。

**Comment by Cirooo** [comment]
> > 最近由于android端升级需要用到xray，服务端装好也用了这套配置
> 
> are you on v2rayNG ::)

Yep. As I added the option "decryption": "none", it's working now.
