### ISSUE TITLE
鉴于大佬的肝帝属性，我也来恬不知耻地要新功能了

### ISSUE THREAD

**Issue by firerflystar** [XTLS/Xray-core#478]
现在上github基本都是先看下XRAY有没新的更新。
偶尔就发现一些激动人心的新功能，比如上个版本的dialerProxy现在用来给几台chromebook的安卓代理用。
但是用国内的APP，想要让它直连就麻烦了，路由现在貌似没有提供按APP类型的规则。如果可能请考虑加上。

**Comment by jyf007** [comment]
@firerflystar 这国内分流不香吗？

**Comment by jyf007** [comment]
@firerflystar Why not use the xray-core directly and use vmess2json to generate configure file to handle the proxy smarter than pure configure ile

**Comment by firerflystar** [comment]
@jyf007 如果加上APP规则的话 就可以按APP分配使用不同的代理

**Comment by jyf007** [comment]
@firerflystar oh i see,but i can't make it

**Comment by rurirei** [comment]
app rule? you are talking about Client features.

**Comment by firerflystar** [comment]
@jyf007 上面的表达不大清楚，应该是对于有多个代理需求的场景， APP规则比较有用，不同的程序使用各自使用不同的代理出去

**Comment by JimhHan** [comment]
@firerflystar 
可以使用 xray4Magisk

**Comment by AkinoKaede** [comment]
这个是路由做不到的，不过 Andorid 上的 VpnService  可以做到这个。
https://developer.android.com/reference/android/net/VpnService

**Comment by firerflystar** [comment]
@JimhHan @AkinoKaede 非常感谢!!!
