### ISSUE TITLE
原版openwrt软件包里的xray怎么使用？

### ISSUE THREAD

**Issue by MoroboshiDai** [XTLS/Xray-core#479]
用树莓派4派刷了个原版openwrt，发现软件仓库里有xray-core ，xray-example，xray-geodata三个app，安装后没有管理界面，想问一下这个应该怎么使用？【谷歌上查了，没有此类资料】

**Comment by raindrops2005** [comment]
@MoroboshiDai 不是所有的软件都有图形界面

**Comment by JimhHan** [comment]
我觉得这似乎不是 xray 的问题。

**Comment by raindrops2005** [comment]
@JimhHan 自信点，把似乎去掉。
这本来就不是一个问题。

**Comment by AkinoKaede** [comment]
这些软件包并不提供 LuCI Application
