### ISSUE TITLE
VLESS-gRPC 无法建立连接，配置是否有误？

### ISSUE THREAD

**Issue by Nehcknarf** [XTLS/Xray-core#483]
基本上参考了：
[https://github.com/XTLS/Xray-examples/tree/main/VLESS-GRPC](url)
xray和caddy均在容器内运行
容器执行命令：

```
docker run -d --name caddy --restart=always \
    -v /etc/caddy/Caddyfile:/etc/caddy/Caddyfile \
    -v /etc/caddy/data:/data \
    -v /etc/caddy/config:/config \
    -p 80:80 -p 443:443 \
    caddy caddy file-server --domain x.cyou
```
```
docker run -d --name xray --restart=always \
    -v /etc/xray:/etc/xray \
    -p 2002:2002 \
    teddysun/xray
```
Caddyfile配置：
```
x.cyou {
    @grpc {
        protocol grpc
        path /Neo/*
    }
    reverse_proxy @grpc h2c://127.0.0.1:2002
    root * /var/www
    file_server
}
```
服务器配置：
```
{
  "log": {
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": 2002,
      "listen": "127.0.0.1",
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "3065xxxx-xxxx-xxxx-xxxx-xxxx2c78af8e"
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "grpc",
        "grpcSettings": {
          "serviceName": "Neo",
          "multiMode": true
        }
      }
    }
  ],
  "outbounds": [
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "blocked",
      "protocol": "blackhole",
      "settings": {}
    }
  ],
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked"
      }
    ]
  }
}
```
客户端配置：
![cli](https://user-images.githubusercontent.com/38715732/113845853-7e1cc480-97c8-11eb-8771-2abfefc98950.png)

**Comment by Nehcknarf** [comment]
感觉是容器间通讯的问题？

**Comment by JimhHan** [comment]
> 容器间不能使用 `127.0.0.1` 通讯

**Comment by Immity** [comment]
xray使用host模式

**Comment by Nehcknarf** [comment]
> > 容器间不能使用 `127.0.0.1` 通讯

修改了新一版的配置，容器内可以相互ping通，但是客户端还是报503，求助各位大佬。
配置开启了multiMode
容器执行命令：
```
docker run -d --name caddy --network=my-net --restart=always \
    -v /etc/caddy/Caddyfile:/etc/caddy/Caddyfile \
    -v /etc/caddy/data:/data \
    -v /etc/caddy/config:/config \
    -p 80:80 -p 443:443 \
    caddy caddy file-server --domain nehcknarf.cyou
```
```
docker run -d --name xray --network=my-net --restart=always \
    -v /etc/xray:/etc/xray \
    -p 2002:2002 \
    teddysun/xray
```
Caddyfile配置：
```
x.cyou {
    @grpc {
        protocol grpc
        path /Neo/*
    }
    reverse_proxy @grpc h2c://xray:2002
    root * /var/www
    file_server
}
```
服务器配置：
```
{
  "log": {
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": 2002,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "3065xxxx-xxxx-xxxx-xxxx-xxxx2c78af8e"
          }
        ],
        "encryption": "none"
      },
      "streamSettings": {
        "network": "grpc",
        "grpcSettings": {
          "serviceName": "Neo",
          "multiMode": true
        }
      }
    }
  ],
  "outbounds": [
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "blocked",
      "protocol": "blackhole",
      "settings": {}
    }
  ],
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked"
      }
    ]
  }
}
```
客户端配置：
![QQ截图20210411202746](https://user-images.githubusercontent.com/38715732/114304183-70d34300-9b04-11eb-86e7-bcf1a2ab33ac.png)

**Comment by nJhEqnvK** [comment]
我猜问题是在这
```
reverse_proxy @grpc h2c://xray:2002
```
xray这个hostname你没设置，所以无法进行转发
你都把两个容器绑定到my-net下了应该可以用localhost了吧（不确定）

>xray使用host模式
他的意思是两个容器都用--network=host，这样这俩镜像都使用的宿主机网络，你直接走localhost就行

另外推荐用[domain socket](https://xtls.github.io/config/transports/domainsocket/)，效率更高、消耗资源更少
感兴趣可以参考我这个issue https://github.com/XTLS/Xray-core/issues/486 贴的配置

**Comment by Nehcknarf** [comment]
> 我猜问题是在这
> 
> ```
> reverse_proxy @grpc h2c://xray:2002
> ```
> 
> xray这个hostname你没设置，所以无法进行转发
> 你都把两个容器绑定到my-net下了应该可以用localhost了吧（不确定）
> 
> > xray使用host模式
> > 他的意思是两个容器都用--network=host，这样这俩镜像都使用的宿主机网络，你直接走localhost就行
> 
> 另外推荐用[domain socket](https://xtls.github.io/config/transports/domainsocket/)，效率更高、消耗资源更少
> 感兴趣可以参考我这个issue #486 贴的配置

加了 hostname 还是不行，--network=host + localhost 我试过也不行，奇怪了。还是非常感谢，有空我看下 domain socket

**Comment by nJhEqnvK** [comment]
奇了怪了，你直接复制docker命令试试：
```bash
docker run -d --name caddy --network=host --restart=always \
    -v /etc/caddy/Caddyfile:/etc/caddy/Caddyfile \
    -v /etc/caddy/data:/data \
    -v /etc/caddy/config:/config \
    caddy caddy file-server --domain nehcknarf.cyou
```

```bash
docker run -d --name xray --network=host --restart=always \
    -v /etc/xray:/etc/xray \
    teddysun/xray
```

如果还是不行就通过`docker logs xray `和`docker logs caddy`把log导出来一起附上看看

**Comment by Nehcknarf** [comment]
> 奇了怪了，你直接复制docker命令试试：
> 
> ```shell
> docker run -d --name caddy --network=host --restart=always \
>     -v /etc/caddy/Caddyfile:/etc/caddy/Caddyfile \
>     -v /etc/caddy/data:/data \
>     -v /etc/caddy/config:/config \
>     caddy caddy file-server --domain nehcknarf.cyou
> ```
> 
> ```shell
> docker run -d --name xray --network=host --restart=always \
>     -v /etc/xray:/etc/xray \
>     teddysun/xray
> ```
> 
> 如果还是不行就通过`docker logs xray `和`docker logs caddy`把log导出来一起附上看看
xray日志没啥信息，caddy日志似乎也一切正常
```
{"level":"info","ts":1618282228.1069918,"msg":"shutting down apps then terminating","signal":"SIGTERM"}
{"level":"info","ts":1618282228.7556498,"logger":"tls.cache.maintenance","msg":"stopped background certificate maintenance","cache":"0xc000257570"}
{"level":"info","ts":1618282228.7580621,"msg":"shutdown done","signal":"SIGTERM"}
{"level":"warn","ts":1618282308.0348866,"logger":"admin","msg":"admin endpoint disabled"}
{"level":"info","ts":1618282308.039061,"logger":"http","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"static","https_port":443}
{"level":"info","ts":1618282308.039125,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"static"}
{"level":"info","ts":1618282308.042071,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["x.cyou"]}
{"level":"info","ts":1618282308.0481603,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0001fe000"}
{"level":"info","ts":1618282308.059702,"logger":"tls","msg":"cleaned up storage units"}
{"level":"info","ts":1618282308.0949776,"msg":"autosaved config","file":"/config/caddy/autosave.json"}
2021/04/13 02:51:48 Caddy 2 serving static files on :443

```

**Comment by nJhEqnvK** [comment]
> > 奇了怪了，你直接复制docker命令试试：
> > ```shell
> > docker run -d --name caddy --network=host --restart=always \
> >     -v /etc/caddy/Caddyfile:/etc/caddy/Caddyfile \
> >     -v /etc/caddy/data:/data \
> >     -v /etc/caddy/config:/config \
> >     caddy caddy file-server --domain nehcknarf.cyou
> > ```
> > 
> > 
> > ```shell
> > docker run -d --name xray --network=host --restart=always \
> >     -v /etc/xray:/etc/xray \
> >     teddysun/xray
> > ```
> > 
> > 
> > 如果还是不行就通过`docker logs xray `和`docker logs caddy`把log导出来一起附上看看
> 
> xray日志没啥信息，caddy日志似乎也一切正常？
> 
> ```
> Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 linux/amd64)
> A unified platform for anti-censorship.
> 2021/04/13 10:51:47 [Info] infra/conf/serial: Reading config: /etc/xray/config.json
> 2021/04/13 10:51:47 [Warning] core: Xray 1.4.2 started
> ```
> 
> ```
> {"level":"info","ts":1618282228.1069918,"msg":"shutting down apps then terminating","signal":"SIGTERM"}
> {"level":"info","ts":1618282228.7556498,"logger":"tls.cache.maintenance","msg":"stopped background certificate maintenance","cache":"0xc000257570"}
> {"level":"info","ts":1618282228.7580621,"msg":"shutdown done","signal":"SIGTERM"}
> {"level":"warn","ts":1618282308.0348866,"logger":"admin","msg":"admin endpoint disabled"}
> {"level":"info","ts":1618282308.039061,"logger":"http","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"static","https_port":443}
> {"level":"info","ts":1618282308.039125,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"static"}
> {"level":"info","ts":1618282308.042071,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["x.cyou"]}
> {"level":"info","ts":1618282308.0481603,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0001fe000"}
> {"level":"info","ts":1618282308.059702,"logger":"tls","msg":"cleaned up storage units"}
> {"level":"info","ts":1618282308.0949776,"msg":"autosaved config","file":"/config/caddy/autosave.json"}
> 2021/04/13 02:51:48 Caddy 2 serving static files on :443
> ```

这个情况还真不知道了，实在不行换nignx吧。。。

**Comment by Nehcknarf** [comment]
> > > 奇了怪了，你直接复制docker命令试试：
> > > ```shell
> > > docker run -d --name caddy --network=host --restart=always \
> > >     -v /etc/caddy/Caddyfile:/etc/caddy/Caddyfile \
> > >     -v /etc/caddy/data:/data \
> > >     -v /etc/caddy/config:/config \
> > >     caddy caddy file-server --domain nehcknarf.cyou
> > > ```
> > > 
> > > 
> > > ```shell
> > > docker run -d --name xray --network=host --restart=always \
> > >     -v /etc/xray:/etc/xray \
> > >     teddysun/xray
> > > ```
> > > 
> > > 
> > > 如果还是不行就通过`docker logs xray `和`docker logs caddy`把log导出来一起附上看看
> > 
> > 
> > xray日志没啥信息，caddy日志似乎也一切正常？
> > ```
> > Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 linux/amd64)
> > A unified platform for anti-censorship.
> > 2021/04/13 10:51:47 [Info] infra/conf/serial: Reading config: /etc/xray/config.json
> > 2021/04/13 10:51:47 [Warning] core: Xray 1.4.2 started
> > ```
> > 
> > 
> > ```
> > {"level":"info","ts":1618282228.1069918,"msg":"shutting down apps then terminating","signal":"SIGTERM"}
> > {"level":"info","ts":1618282228.7556498,"logger":"tls.cache.maintenance","msg":"stopped background certificate maintenance","cache":"0xc000257570"}
> > {"level":"info","ts":1618282228.7580621,"msg":"shutdown done","signal":"SIGTERM"}
> > {"level":"warn","ts":1618282308.0348866,"logger":"admin","msg":"admin endpoint disabled"}
> > {"level":"info","ts":1618282308.039061,"logger":"http","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"static","https_port":443}
> > {"level":"info","ts":1618282308.039125,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"static"}
> > {"level":"info","ts":1618282308.042071,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["x.cyou"]}
> > {"level":"info","ts":1618282308.0481603,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0001fe000"}
> > {"level":"info","ts":1618282308.059702,"logger":"tls","msg":"cleaned up storage units"}
> > {"level":"info","ts":1618282308.0949776,"msg":"autosaved config","file":"/config/caddy/autosave.json"}
> > 2021/04/13 02:51:48 Caddy 2 serving static files on :443
> > ```
> 
> 这个情况还真不知道了，实在不行换nignx吧。。。

有可能是xray容器时间不同步导致的，但是VLESS说是不依赖于系统时间

**Comment by Nehcknarf** [comment]
> > > 奇了怪了，你直接复制docker命令试试：
> > > ```shell
> > > docker run -d --name caddy --network=host --restart=always \
> > >     -v /etc/caddy/Caddyfile:/etc/caddy/Caddyfile \
> > >     -v /etc/caddy/data:/data \
> > >     -v /etc/caddy/config:/config \
> > >     caddy caddy file-server --domain nehcknarf.cyou
> > > ```
> > > 
> > > 
> > > ```shell
> > > docker run -d --name xray --network=host --restart=always \
> > >     -v /etc/xray:/etc/xray \
> > >     teddysun/xray
> > > ```
> > > 
> > > 
> > > 如果还是不行就通过`docker logs xray `和`docker logs caddy`把log导出来一起附上看看
> > 
> > 
> > xray日志没啥信息，caddy日志似乎也一切正常？
> > ```
> > Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 linux/amd64)
> > A unified platform for anti-censorship.
> > 2021/04/13 10:51:47 [Info] infra/conf/serial: Reading config: /etc/xray/config.json
> > 2021/04/13 10:51:47 [Warning] core: Xray 1.4.2 started
> > ```
> > 
> > 
> > ```
> > {"level":"info","ts":1618282228.1069918,"msg":"shutting down apps then terminating","signal":"SIGTERM"}
> > {"level":"info","ts":1618282228.7556498,"logger":"tls.cache.maintenance","msg":"stopped background certificate maintenance","cache":"0xc000257570"}
> > {"level":"info","ts":1618282228.7580621,"msg":"shutdown done","signal":"SIGTERM"}
> > {"level":"warn","ts":1618282308.0348866,"logger":"admin","msg":"admin endpoint disabled"}
> > {"level":"info","ts":1618282308.039061,"logger":"http","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"static","https_port":443}
> > {"level":"info","ts":1618282308.039125,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"static"}
> > {"level":"info","ts":1618282308.042071,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["x.cyou"]}
> > {"level":"info","ts":1618282308.0481603,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0001fe000"}
> > {"level":"info","ts":1618282308.059702,"logger":"tls","msg":"cleaned up storage units"}
> > {"level":"info","ts":1618282308.0949776,"msg":"autosaved config","file":"/config/caddy/autosave.json"}
> > 2021/04/13 02:51:48 Caddy 2 serving static files on :443
> > ```
> 
> 这个情况还真不知道了，实在不行换nignx吧。。。

成功解决了，方案在下面，原来是caddy指令多了
[https://github.com/XTLS/Xray-core/issues/510#issuecomment-820435114](url)
