### ISSUE TITLE
[Feature Request]Dokodemo-Door支持Domain Socket

### ISSUE THREAD

**Issue by m-d-z-z** [XTLS/Xray-core#484]
先上配置：
`        {
            "listen": "/usr/local/xray/var/socks/api.socket",
            "port": 0,
            "protocol": "dokodemo-door",
            "tag": "grpc-api",
            "streamSettings": {
                "network": "domainsocket",
                "dsSetting": {
                    "path": "/usr/local/xray/var/socks/api.socket",
                    "abstract": false,
                    "padding": false
                }
            }
        }
`
在配置api的时候会用到Dokodemo-door，希望能使用domain-socket作为api的传输方式，而不需要占用系统一个端口。
使用此配置貌似无效，在相应路径没有找到api.socket文件。
仔细翻找了一下closed issue，发现了是不支持的。
https://github.com/v2fly/v2ray-core/issues/383
不知道大佬们有没有计划去做这个（（

**Comment by JimhHan** [comment]
@m-d-z-z 

可以设置 dokodemo 配置的 `network` 选项为 `unix`。[文档](https://xtls.github.io/Xray-docs-next/config/inbounds/dokodemo.html#inboundconfigurationobject)

**Comment by Soberia** [comment]
To use Unix domain socket for API:
```json
{
  "tag": "api",
  "protocol": "dokodemo-door",
  "listen": "/tmp/xray/api.sock,766",
  "settings": {
    "address": "",
    "network": "unix"
  }
}
```

**Comment by supernovaw** [comment]
I'm currently setting up dokodemo-door with a Unix socket and the above example by @Soberia isn't working unless I also add `"port": 1` (or any number except zero) inside `"settings"`. Without `"port": 1`, Xray crashes with the following stack trace. This seems to be a bug in Xray, but I'm not certain. If it indeed a bug, I hope somebody opens a new issue.

```
panic: strconv.Atoi: parsing "": invalid syntax

goroutine 50 [running]:
github.com/xtls/xray-core/common.Must(...)
    github.com/xtls/xray-core/common/common.go:22
github.com/xtls/xray-core/common.Must2[...](...)
    github.com/xtls/xray-core/common/common.go:30
github.com/xtls/xray-core/proxy/dokodemo.(*DokodemoDoor).Process(…)
    github.com/xtls/xray-core/proxy/dokodemo/dokodemo.go:91 +0x12f1
github.com/xtls/xray-core/app/proxyman/inbound.(*dsWorker).callback(…)
    github.com/xtls/xray-core/app/proxyman/inbound/worker.go:521 +0x806
created by github.com/xtls/xray-core/app/proxyman/inbound.(*dsWorker).Start.func1 in goroutine 49
    github.com/xtls/xray-core/app/proxyman/inbound/worker.go:541 +0x7a
```
My version: Xray 25.9.11 (3edfb0e, go1.25.1 linux/amd64)
