### ISSUE TITLE
关于P2P的兼容性问题

### ISSUE THREAD

**Issue by ddiiccoo** [XTLS/Xray-core#488]
我使用带有最新的1.4.2版本XRAY模块的OPENWRT路由，其他都正常，就是下载BT非常困难，不管是用VLESS还是TROJAN都几乎下载不动或速度极慢。但换了官方原版的TROJAN后，就可以顺利的下载，速度也正常。请问是否是因为我XRAY的某个配置参数导致的？或者说怎么改一改参数，可以更好的兼容P2P？
我的OPENWRT中VLESS客户端配置文件如下：
{
   "outbound": {
     "settings": {
       "vnext": [
         {
           "port": 443,
           "users": [
             {
               "flow": "xtls-rprx-direct",
               "encryption": "none",
               "id": "xxx"
             }
           ],
           "address": "xxx.com"
         }
       ]
     },
     "protocol": "vless",
     "streamSettings": {
       "network": "tcp",
       "xtlsSettings": {
         "serverName": "xxx.com",
         "allowInsecure": true
       },
       "security": "xtls"
     }
   },
   "log": {
     "loglevel": "warning"
   },
   "inbound": {
     "sniffing": {
       "enabled": false,
       "destOverride": [
         "http",
         "tls"
       ]
     },
     "port": 1234,
     "protocol": "dokodemo-door",
     "settings": {
       "network": "tcp,udp",
       "followRedirect": true
     }
   }
 }

**Comment by rprx** [comment]
理论上不存在此问题

**Comment by muziling** [comment]
这么一说，今天我的BT也下不去，太奇怪了，以往也是用xray，下载都好好的。 唯一不同是升级了版本且使用了ed参数

**Comment by ddiiccoo** [comment]
> 理论上不存在此问题

报告，基本总结出规律了。就是在XTLS下BT基本上下不动，或者很慢。但是在TLS下，一切正常

**Comment by ddiiccoo** [comment]
> 这么一说，今天我的BT也下不动，太奇怪了，以往也是用xray，下载都好好的。 唯一不同是升级了版本且使用了ed参数，
> 再看了一下，好像没关系，有ed参数的时候，也有下载过，正常。

我测试，主要是XTLS导致的，跟版本倒没有关系
