### ISSUE TITLE
openwrt使用xray 1.4.2 ，vless，allowInsecure只能设为true？

### ISSUE THREAD

**Issue by FatDNA** [XTLS/Xray-core#491]
openwrt19.07，1.4.2下，outbounds -> streamSettings -> xtlsSettings -> allowInsecure 必须设为 true 才能正常上网，设为 false 时看error日志似乎提示证书方面有问题（服务器证书没过期）。而1.4.2之前的版本设为false都可正常使用的。
但1.4.2下windows V2ranN与Android V2rayNG则无此问题。
请问大佬们该如何解决？

**Comment by twzchi** [comment]
尝试下V2rayN 是否复现问题。。。
正常的话，那就是编译的固件有bug

**Comment by FatDNA** [comment]
> 尝试下V2rayN 是否复现问题。。。
> 正常的话，那就是编译的固件有bug

V2rayN与V2rayNG更新到１.4.2都没有出现此问题。OpenWRt中，linux64与arm32-v7a两台不同路由器，尝试使用不同服务器都出现同样问题。

**Comment by wloot** [comment]
同样遇到了类似问题，allowInsecure设置为false会导致xray吃满路由器cpu，导致卡死，设置为true才行。

**Comment by AkinoKaede** [comment]
自行检查 `ca-certificates` 软件包是否安装并正常使用

**Comment by 1715173329** [comment]
一般情况下，安装 `ca-bundle` 软件包即可

**Comment by FatDNA** [comment]
ca-*这两项当然是有的，不是缺失它们的问题，否则之前版本的xray也会有问题。我路由器是全局代理，所以下载新版本zip包后只解压xray执行文件一个，chmod 755后也只会覆盖旧执行文件一个，其它完全没变动，所以只可能是1.4.2版的执行文件在证书方面的要求改变了。

**Comment by wloot** [comment]
> ca-*这两项当然是有的，不是缺失它们的问题，否则之前版本的xray也会有问题。我路由器是全局代理，所以下载新版本zip包后只解压xray执行文件一个，chmod 755后也只会覆盖旧执行文件一个，其它完全没变动，所以只可能是1.4.2版的执行文件在证书方面的要求改变了。

你试过1.4.1有问题吗?

**Comment by FatDNA** [comment]
> > ca-*这两项当然是有的，不是缺失它们的问题，否则之前版本的xray也会有问题。我路由器是全局代理，所以下载新版本zip包后只解压xray执行文件一个，chmod 755后也只会覆盖旧执行文件一个，其它完全没变动，所以只可能是1.4.2版的执行文件在证书方面的要求改变了。
> 
> 你试过1.4.1有问题吗?

没有，1.4.0和以前是没问题的。

**Comment by JimhHan** [comment]
@FatDNA 

请提供 error 日志

**Comment by rprx** [comment]
v1.4.2 有 uTLS，个人认为是 GUI 的问题

**Comment by wloot** [comment]
> @FatDNA
> 
> 请提供 error 日志

这是我之前反馈的, allowInsecure=false导致xray长时间占满cpu时的日志: https://pastebin.com/c6y4UTJG

环境是openwrt 21.02, mipsel_24kc硬路由小米ac2100, gui是passwall最新版.

占满cpu时执行shell都困难, 有时访问网络, 但极其缓慢.

**Comment by FatDNA** [comment]
问题解决！

error日志：
===========
2021/03/06 06:09:57 [Info] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to decode response header > proxy/vless/encoding: failed to read response version > x509: certificate has expired or is not yet valid: current time 2021-03-06T06:09:57Z is before 2021-04-05T15:56:14Z
===========
原来是openwrt默认的时间服务器可能在国内（或者只是我所用的广东联通）并不能访问，导致系统时间永远同步不了，时间就停留在写入系统日子，所以出现以上错误提示。
我删除系统默认的时间服务器，并增设时间服务器为time.windows.com，再将allowInsecure改回false。重启路由器后，系统时间变正常了，xray也能正常工作了。之后尝试重启几次都没再出现问题。
谢谢各位大佬的帮忙！但为何只有1.4.2版本的才会这样就有待各位开发大佬解决了。

**Comment by rprx** [comment]
@FatDNA @wloot 说实话，两位的问题感觉不像是 core 的问题

**Comment by FatDNA** [comment]
> @FatDNA @wloot 说实话，两位的问题感觉不像是 core 的问题
确实，我的似乎不是，但之前版本无此问题。

**Comment by wloot** [comment]
> @FatDNA @wloot 说实话，两位的问题感觉不像是 core 的问题

应该不是了... 我直接测了xray v1.0也有同样问题, 不过还是不知道到底哪里出毛病了...

**Comment by rprx** [comment]
@FatDNA @wloot 应该是插件更新导致的，请在插件对应的仓库提 issue

**Comment by rprx** [comment]
@wloot 对了，CPU 占满一般是透明代理死循环

**Comment by wloot** [comment]
> @wloot 对了，CPU 占满一般是透明代理死循环

奇怪了.... 我使用top指令看到的是xray进程在大量占用cpu

**Comment by AkinoKaede** [comment]
> > @wloot 对了，CPU 占满一般是透明代理死循环
> 
> 奇怪了.... 我使用top指令看到的是xray进程在大量占用cpu

透明代理死循环是这样的…

**Comment by junmin** [comment]
> > @FatDNA
> > 请提供 error 日志
> 
> 这是我之前反馈的, allowInsecure=false导致xray长时间占满cpu时的日志: https://pastebin.com/c6y4UTJG
> 
> 环境是openwrt 21.02, mipsel_24kc硬路由小米ac2100, gui是passwall最新版(之前试过helloworld也是一样的问题).
> 
> 占满cpu时执行shell都困难, 有时可以访问网络, 但极其缓慢.
> 
> 正在测试1.4.0有没有这个情况, 到时候会更新

我这也一模一样的情况，也是这个硬件，我还有newifi d2+openwrt 19.07，也是一样的问题。
看xray日志也看不出什么问题来

**Comment by wloot** [comment]
> > > @FatDNA
> > > 请提供 error 日志
> > 
> > 
> > 这是我之前反馈的, allowInsecure=false导致xray长时间占满cpu时的日志: https://pastebin.com/c6y4UTJG
> > 环境是openwrt 21.02, mipsel_24kc硬路由小米ac2100, gui是passwall最新版(之前试过helloworld也是一样的问题).
> > 占满cpu时执行shell都困难, 有时可以访问网络, 但极其缓慢.
> > 正在测试1.4.0有没有这个情况, 到时候会更新
> 
> 我这也一模一样的情况，也是这个硬件，我还有newifi d2+openwrt 19.07，也是一样的问题。
> 看xray日志也看不出什么问题来

可能是这个原因 https://github.com/XTLS/Xray-core/discussions/562

**Comment by junmin** [comment]
> > > > @FatDNA
> > > > 请提供 error 日志
> > > 
> > > 
> > > 这是我之前反馈的, allowInsecure=false导致xray长时间占满cpu时的日志: https://pastebin.com/c6y4UTJG
> > > 环境是openwrt 21.02, mipsel_24kc硬路由小米ac2100, gui是passwall最新版(之前试过helloworld也是一样的问题).
> > > 占满cpu时执行shell都困难, 有时可以访问网络, 但极其缓慢.
> > > 正在测试1.4.0有没有这个情况, 到时候会更新
> > 
> > 
> > 我这也一模一样的情况，也是这个硬件，我还有newifi d2+openwrt 19.07，也是一样的问题。
> > 看xray日志也看不出什么问题来
> 
> 可能是这个原因 #562

@wloot 你有测试过了吗？

**Comment by wloot** [comment]
> > > > > @FatDNA
> > > > > 请提供 error 日志
> > > > 
> > > > 
> > > > 这是我之前反馈的, allowInsecure=false导致xray长时间占满cpu时的日志: https://pastebin.com/c6y4UTJG
> > > > 环境是openwrt 21.02, mipsel_24kc硬路由小米ac2100, gui是passwall最新版(之前试过helloworld也是一样的问题).
> > > > 占满cpu时执行shell都困难, 有时可以访问网络, 但极其缓慢.
> > > > 正在测试1.4.0有没有这个情况, 到时候会更新
> > > 
> > > 
> > > 我这也一模一样的情况，也是这个硬件，我还有newifi d2+openwrt 19.07，也是一样的问题。
> > > 看xray日志也看不出什么问题来
> > 
> > 
> > 可能是这个原因 #562
> 
> @wloot 你有测试过了吗？

没有

**Comment by junmin** [comment]
@wloot 

好像可以了。根据你说的 https://github.com/XTLS/Xray-core/discussions/562 里面的信息，我查看了一下我服务器上面的证书，也是里面说的zerossl的证书，zerossl是acme.sh默认使用的CA，我没有按照他说的改用站点证书，然后在客户端设置使用中间证书，而是直接把服务器的证书换成let's encrypt的ec256证书。

```
DOMAIN=xxx.xxx.com
~/.acme.sh/acme.sh --set-default-ca  --server  letsencrypt
~/.acme.sh/acme.sh   --issue -d $DOMAIN --keylength ec-256 --standalone --force

然后install到需要的path或者直接ln一下：
CERT_FILE="/usr/local/etc/xray/${DOMAIN}.pem"
KEY_FILE="/usr/local/etc/xray/${DOMAIN}.key"
~/.acme.sh/acme.sh  --install-cert -d $DOMAIN --ecc \
>             --key-file       $KEY_FILE  \
>             --fullchain-file $CERT_FILE \


重启xray，在客户端设置allowInsecure=false使用
```
