### ISSUE TITLE
关于开启websocket 0-rtt的问题

### ISSUE THREAD

**Issue by nexusman2016** [XTLS/Xray-core#493]
开发者你好
我的websocket配置的path是类似
/xraypath/
这种末端带一个斜杠的path地址
请问这种情况下想开启websocket 0-rtt
是不是将地址写成
/xraypath/?ed=2048
就可以了？还是说不支持这种末端带斜杠的path地址 只能将服务器配置文件改成
/xraypath
以对应客户端
/xraypath?ed=2048

向大佬们求助

**Comment by mcbbsandnz** [comment]
我记得是服务端不变，客户端的path后面加上?ed=2048就行了

**Comment by nexusman2016** [comment]
> 我记得是服务端不变，客户端的path后面加上?ed=2048就行了

是的 但是我想确认一下path末尾存在斜杠的情况下加上?ed=2048是否好用

**Comment by AkinoKaede** [comment]
应该支持

**Comment by JimhHan** [comment]
@AkinoKaede
