### ISSUE TITLE
fakedns优先级问题

### ISSUE THREAD

**Issue by ggggle** [XTLS/Xray-core#495]
版本1.4.2
![image](https://user-images.githubusercontent.com/8306108/114258842-fe773b80-99fb-11eb-92d9-2f92ed236782.png)
dns配置如上，当无法从223.6.6.6解析domain:apple.com，比如外网断开或者超时，将会从fakedns获取一条记录，即使domain:apple.com不在fakedns的domains列表里面。
这种情况不应该从fakedns解析吧，应该必须要匹配domains才去使用该dns解析

相关日志：
> 2021/04/10 09:27:51 [Info] [1764230497] proxy/dns: handling DNS traffic to udp:192.168.7.109:53
2021/04/10 09:27:51 [Info] [935905698] proxy/dokodemo: received request for 192.168.7.105:51890
2021/04/10 09:27:51 [Info] [935905698] app/dispatcher: sniffed domain: courier.push.apple.com
2021/04/10 09:27:51 [Info] [935905698] app/dispatcher: taking detour [direct] for [tcp:courier.push.apple.com:5223]
2021/04/10 09:27:51 [Info] [935905698] proxy/freedom: opening connection to tcp:courier.push.apple.com:5223
2021/04/10 09:27:55 [Info] app/dns: failed to lookup ip for domain 32-courier.push.apple.com at server UDP:223.6.6.6:53 > context deadline exceeded
2021/04/10 09:27:55 [Info] app/dns: FakeDNS got answer: 32-courier.push.apple.com -> [198.18.130.107]

**Comment by ggggle** [comment]
或者是domain:apple.com包含在geosite:geolocation-!cn里面了？

**Comment by JimhHan** [comment]
alidns 超时了，所以用了 FakeDNS
