### ISSUE TITLE
路由设置中的反向匹配"geoip:!cn"不可用,///"geosite:!cn",不可用

### ISSUE THREAD

**Issue by wutongskype** [XTLS/Xray-core#497]
![Snipaste_2021-04-10_23-14-38](https://user-images.githubusercontent.com/40192806/114274822-cf3fe900-9a52-11eb-8cdb-ac2d6571a811.jpg)

日志提示无效规则说明里却又反向匹配这么一说

**Comment by AkinoKaede** [comment]
你看的 V2Fly 的文档吧，Xray 目前还没有这个 feature

**Comment by wutongskype** [comment]
> 你看的 V2Fly 的文档吧，Xray 目前还没有这个 feature

额,,尽快加上把....我先另想办法凑活....
