### ISSUE TITLE
分流模式 SSH 走代理连接会在一分钟自动断开

### ISSUE THREAD

**Issue by CeeIM** [XTLS/Xray-core#502]
测试于 OpenWrt 下 VSSR、PassWall 插件，都是用 Xray 的分流功能，均出现此情况。
开启了 Xray 分流，一台 VPS 同时测试不走代理和走代理（不活跃情况下）的连接：
直连 SSH 无操作仅挂机，试过一小时都不会断开，SSH 客户端设置了 30 秒保活。
走 Xray 分流的连接在一分钟准时断开（无操作），SSH 客户端如何设置保活都无效。
关闭基于 Xray 核心的分流功能才正常，应该是默认心跳时长问题？如何更改呢？
分流功能太好用了，除了路由器其他电脑无需增加额外设置的情况下想有个两全其美的办法。

**Comment by JimhHan** [comment]
@CeeIM 设置一下 connIdle？

**Comment by CeeIM** [comment]
> @CeeIM 设置一下 connIdle？

你好请问保持连接应该如何设置？配置文件没看到有相关的 = =

**Comment by JimhHan** [comment]
@CeeIM https://xtls.github.io/Xray-docs-next/config/policy.html#policyobject

**Comment by CeeIM** [comment]
> @CeeIM https://xtls.github.io/Xray-docs-next/config/policy.html#policyobject

在路由器插件中没有找到文档中的选项，但是问题似乎解决了：
订阅的节点默认连接超时是 60 秒，但我单一选择一个节点使用的时候这个规则貌似不会生效，SSH 不会断开所以没有发现该问题，但 Xray 分流模式会校验该数值，所以每分钟自动超时断开，我现在将连接超时改掉之后好像正常了。
![image](https://user-images.githubusercontent.com/18570103/114392042-d558d580-9bca-11eb-81f6-3a823cb254b2.png)

但我还有一点疑惑，分流模式下，连接超时为 60 秒，我在 SSH 客户端设置保持连接 30 秒也无法维持该连接是为何？谢谢。
![image](https://user-images.githubusercontent.com/18570103/114392373-41d3d480-9bcb-11eb-941b-bd6792326835.png)

**Comment by JimhHan** [comment]
请提供连接断开时的日志。

**Comment by CeeIM** [comment]
2021/04/12 12:38:05 [Debug] [1979334808] proxy/dokodemo: processing connection from: 10.0.0.224:5418
2021/04/12 12:38:05 [Info] [1979334808] proxy/dokodemo: received request for 10.0.0.224:5418
2021/04/12 12:38:05 [Info] [1979334808] app/dispatcher: taking detour [default] for [tcp:SSH:22]
2021/04/12 12:38:05 [Info] [1979334808] transport/internet/tcp: dialing TCP to tcp:127.0.0.1:2082
2021/04/12 12:38:05 [Debug] transport/internet: dialing to tcp:127.0.0.1:2082
2021/04/12 12:38:05 10.0.0.224:5418 accepted tcp:SSH:22 [default]
2021/04/12 12:38:06 [Info] [1274439912] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: connection ends > context canceled
2021/04/12 12:38:06 [Info] [1274439912] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2021/04/12 12:38:06 [Info] [898731047] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > context canceled
2021/04/12 12:38:06 [Info] [898731047] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: connection ends > context canceled
2021/04/12 12:38:06 [Info] [1979334808] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > context canceled
2021/04/12 12:38:06 [Info] [1979334808] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: connection ends > context canceled
2021/04/12 12:38:09 [Debug] [2693515666] proxy/dokodemo: processing connection from: localhost:12143
2021/04/12 12:38:09 [Info] [2693515666] proxy/dokodemo: received request for localhost:12143
2021/04/12 12:38:09 [Info] [2693515666] app/dispatcher: taking detour [default] for [tcp:1.0.0.1:53]
2021/04/12 12:38:09 [Info] [2693515666] transport/internet/tcp: dialing TCP to tcp:127.0.0.1:2082
2021/04/12 12:38:09 [Debug] transport/internet: dialing to tcp:127.0.0.1:2082
2021/04/12 12:38:09 localhost:12143 accepted tcp:1.0.0.1:53 [default]
2021/04/12 12:38:09 [Debug] [1287829888] proxy/dokodemo: processing connection from: 10.0.0.224:5421
2021/04/12 12:38:09 [Info] [1287829888] proxy/dokodemo: received request for 10.0.0.224:5421
2021/04/12 12:38:09 [Info] [1287829888] app/dispatcher: sniffed domain: 91.108.56.175
2021/04/12 12:38:09 [Info] [1287829888] app/dispatcher: taking detour [Telegram] for [tcp:91.108.56.175:80]
2021/04/12 12:38:09 [Info] [1287829888] transport/internet/tcp: dialing TCP to tcp:127.0.0.1:2083
2021/04/12 12:38:09 [Debug] transport/internet: dialing to tcp:127.0.0.1:2083
2021/04/12 12:38:09 10.0.0.224:5421 accepted tcp:91.108.56.175:80 [Telegram]
2021/04/12 12:38:09 [Debug] [2346336218] proxy/dokodemo: processing connection from: localhost:35260
2021/04/12 12:38:09 [Info] [2346336218] proxy/dokodemo: received request for localhost:35260
2021/04/12 12:38:09 [Info] [2346336218] app/dispatcher: taking detour [default] for [tcp:1.0.0.1:53]
2021/04/12 12:38:09 [Info] [2346336218] transport/internet/tcp: dialing TCP to tcp:127.0.0.1:2082
2021/04/12 12:38:09 [Debug] transport/internet: dialing to tcp:127.0.0.1:2082
2021/04/12 12:38:09 localhost:35260 accepted tcp:1.0.0.1:53 [default]
2021/04/12 12:38:10 [Debug] [1280575899] proxy/dokodemo: processing connection from: 10.0.0.224:5422
2021/04/12 12:38:10 [Info] [1280575899] proxy/dokodemo: received request for 10.0.0.224:5422
2021/04/12 12:38:10 [Info] [1280575899] app/dispatcher: sniffed domain: client.relay.crisp.chat
2021/04/12 12:38:10 [Info] [1280575899] app/dispatcher: taking detour [default] for [tcp:client.relay.crisp.chat:443]
2021/04/12 12:38:10 [Info] [1280575899] transport/internet/tcp: dialing TCP to tcp:127.0.0.1:2082
2021/04/12 12:38:10 [Debug] transport/internet: dialing to tcp:127.0.0.1:2082
2021/04/12 12:38:10 10.0.0.224:5422 accepted tcp:159.89.200.136:443 [default]
2021/04/12 12:38:10 [Info] [2693515666] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: connection ends > context canceled
2021/04/12 12:38:10 [Info] [2693515666] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2021/04/12 12:38:11 [Info] [2346336218] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: connection ends > context canceled
2021/04/12 12:38:11 [Info] [2346336218] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2021/04/12 12:38:24 [Debug] [796784080] proxy/dokodemo: processing connection from: 10.0.0.224:5429
2021/04/12 12:38:24 [Info] [796784080] proxy/dokodemo: received request for 10.0.0.224:5429
2021/04/12 12:38:24 [Info] [796784080] app/dispatcher: sniffed domain: 172.217.24.46
2021/04/12 12:38:24 [Info] [796784080] app/dispatcher: taking detour [default] for [tcp:172.217.24.46:80]
2021/04/12 12:38:24 [Info] [796784080] transport/internet/tcp: dialing TCP to tcp:127.0.0.1:2082
2021/04/12 12:38:24 [Debug] transport/internet: dialing to tcp:127.0.0.1:2082
2021/04/12 12:38:24 10.0.0.224:5429 accepted tcp:172.217.24.46:80 [default]
2021/04/12 12:38:24 [Debug] [80769508] proxy/dokodemo: processing connection from: 10.0.0.224:5430
2021/04/12 12:38:24 [Info] [80769508] proxy/dokodemo: received request for 10.0.0.224:5430
2021/04/12 12:38:24 [Info] [80769508] app/dispatcher: sniffed domain: www.google.com
2021/04/12 12:38:24 [Info] [80769508] app/dispatcher: taking detour [default] for [tcp:www.google.com:443]
2021/04/12 12:38:24 [Info] [80769508] transport/internet/tcp: dialing TCP to tcp:127.0.0.1:2082
2021/04/12 12:38:24 [Debug] transport/internet: dialing to tcp:127.0.0.1:2082
2021/04/12 12:38:24 10.0.0.224:5430 accepted tcp:142.250.204.36:443 [default]
2021/04/12 12:38:24 [Debug] [846186167] proxy/dokodemo: processing connection from: localhost:46540
2021/04/12 12:38:24 [Info] [846186167] proxy/dokodemo: received request for localhost:46540
2021/04/12 12:38:24 [Info] [846186167] app/dispatcher: taking detour [default] for [tcp:1.0.0.1:53]
2021/04/12 12:38:24 [Info] [846186167] transport/internet/tcp: dialing TCP to tcp:127.0.0.1:2082
2021/04/12 12:38:24 [Debug] transport/internet: dialing to tcp:127.0.0.1:2082
2021/04/12 12:38:24 localhost:46540 accepted tcp:1.0.0.1:53 [default]
2021/04/12 12:38:25 [Info] [846186167] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: connection ends > context canceled
2021/04/12 12:38:25 [Info] [846186167] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2021/04/12 12:38:42 [Debug] [1387295200] proxy/dokodemo: processing connection from: 10.0.0.224:5455
2021/04/12 12:38:42 [Info] [1387295200] proxy/dokodemo: received request for 10.0.0.224:5455
2021/04/12 12:38:42 [Info] [1387295200] app/dispatcher: sniffed domain: activity.windows.com
2021/04/12 12:38:42 [Info] [1387295200] app/dispatcher: taking detour [default] for [tcp:activity.windows.com:443]
2021/04/12 12:38:42 [Info] [1387295200] transport/internet/tcp: dialing TCP to tcp:127.0.0.1:2082
2021/04/12 12:38:42 [Debug] transport/internet: dialing to tcp:127.0.0.1:2082
2021/04/12 12:38:42 10.0.0.224:5455 accepted tcp:20.44.232.74:443 [default]
2021/04/12 12:39:05 [Debug] [770416864] proxy/dokodemo: processing connection from: localhost:48402
2021/04/12 12:39:05 [Info] [770416864] proxy/dokodemo: received request for localhost:48402
2021/04/12 12:39:05 [Info] [770416864] app/dispatcher: sniffed domain: www.google.com
2021/04/12 12:39:05 [Info] [770416864] app/dispatcher: taking detour [default] for [tcp:www.google.com:443]
2021/04/12 12:39:05 [Info] [770416864] transport/internet/tcp: dialing TCP to tcp:127.0.0.1:2082
2021/04/12 12:39:05 [Debug] transport/internet: dialing to tcp:127.0.0.1:2082
2021/04/12 12:39:05 localhost:48402 accepted tcp:142.250.204.36:443 [default]
2021/04/12 12:39:06 [Info] [770416864] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > context canceled
2021/04/12 12:39:06 [Info] [770416864] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: connection ends > context canceled
2021/04/12 12:39:32 [Debug] [621990911] proxy/dokodemo: processing connection from: localhost:11460
2021/04/12 12:39:32 [Info] [621990911] proxy/dokodemo: received request for localhost:11460
2021/04/12 12:39:32 [Info] [621990911] app/dispatcher: taking detour [default] for [tcp:1.0.0.1:53]
2021/04/12 12:39:32 [Info] [621990911] transport/internet/tcp: dialing TCP to tcp:127.0.0.1:2082
2021/04/12 12:39:32 [Debug] transport/internet: dialing to tcp:127.0.0.1:2082
2021/04/12 12:39:32 localhost:11460 accepted tcp:1.0.0.1:53 [default]
2021/04/12 12:39:33 [Debug] [836852502] proxy/dokodemo: processing connection from: localhost:53508
2021/04/12 12:39:33 [Info] [836852502] proxy/dokodemo: received request for localhost:53508
2021/04/12 12:39:33 [Info] [836852502] app/dispatcher: taking detour [default] for [tcp:1.0.0.1:53]
2021/04/12 12:39:33 [Info] [836852502] transport/internet/tcp: dialing TCP to tcp:127.0.0.1:2082
2021/04/12 12:39:33 [Debug] transport/internet: dialing to tcp:127.0.0.1:2082
2021/04/12 12:39:33 localhost:53508 accepted tcp:1.0.0.1:53 [default]
2021/04/12 12:39:33 [Debug] [2636539523] proxy/dokodemo: processing connection from: localhost:50531
2021/04/12 12:39:33 [Info] [2636539523] proxy/dokodemo: received request for localhost:50531
2021/04/12 12:39:33 [Info] [2636539523] app/dispatcher: taking detour [default] for [tcp:1.0.0.1:53]
2021/04/12 12:39:33 [Info] [2636539523] transport/internet/tcp: dialing TCP to tcp:127.0.0.1:2082
2021/04/12 12:39:33 [Debug] transport/internet: dialing to tcp:127.0.0.1:2082
2021/04/12 12:39:33 localhost:50531 accepted tcp:1.0.0.1:53 [default]
2021/04/12 12:39:33 [Debug] [1697916552] proxy/dokodemo: processing connection from: localhost:48164
2021/04/12 12:39:33 [Info] [1697916552] proxy/dokodemo: received request for localhost:48164
2021/04/12 12:39:33 [Info] [1697916552] app/dispatcher: taking detour [default] for [tcp:1.0.0.1:53]
2021/04/12 12:39:33 [Info] [1697916552] transport/internet/tcp: dialing TCP to tcp:127.0.0.1:2082
2021/04/12 12:39:33 [Debug] transport/internet: dialing to tcp:127.0.0.1:2082
2021/04/12 12:39:33 localhost:48164 accepted tcp:1.0.0.1:53 [default]
2021/04/12 12:39:33 [Debug] [1588314163] proxy/dokodemo: processing connection from: localhost:18355
2021/04/12 12:39:33 [Info] [1588314163] proxy/dokodemo: received request for localhost:18355
2021/04/12 12:39:33 [Info] [1588314163] app/dispatcher: taking detour [default] for [tcp:1.0.0.1:53]
2021/04/12 12:39:33 [Info] [1588314163] transport/internet/tcp: dialing TCP to tcp:127.0.0.1:2082
2021/04/12 12:39:33 [Debug] transport/internet: dialing to tcp:127.0.0.1:2082
2021/04/12 12:39:33 localhost:18355 accepted tcp:1.0.0.1:53 [default]
2021/04/12 12:39:33 [Debug] [3652700039] proxy/dokodemo: processing connection from: 10.0.0.1:57018
2021/04/12 12:39:33 [Info] [3652700039] proxy/dokodemo: received request for 10.0.0.1:57018
2021/04/12 12:39:33 [Debug] [1932807757] proxy/dokodemo: processing connection from: 10.0.0.1:57016
2021/04/12 12:39:33 [Info] [1932807757] proxy/dokodemo: received request for 10.0.0.1:57016
2021/04/12 12:39:33 [Info] [3652700039] app/dispatcher: taking detour [default] for [tcp:64.233.189.27:25]
2021/04/12 12:39:33 [Info] [3652700039] transport/internet/tcp: dialing TCP to tcp:127.0.0.1:2082
2021/04/12 12:39:33 [Debug] transport/internet: dialing to tcp:127.0.0.1:2082
2021/04/12 12:39:33 [Info] [1932807757] app/dispatcher: taking detour [default] for [tcp:64.233.189.27:25]
2021/04/12 12:39:33 [Info] [1932807757] transport/internet/tcp: dialing TCP to tcp:127.0.0.1:2082
2021/04/12 12:39:33 [Debug] transport/internet: dialing to tcp:127.0.0.1:2082
2021/04/12 12:39:33 10.0.0.1:57018 accepted tcp:64.233.189.27:25 [default]
2021/04/12 12:39:33 10.0.0.1:57016 accepted tcp:64.233.189.27:25 [default]
2021/04/12 12:39:34 [Info] [621990911] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: connection ends > context canceled
2021/04/12 12:39:34 [Info] [621990911] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2021/04/12 12:39:34 [Info] [836852502] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: connection ends > context canceled
2021/04/12 12:39:34 [Info] [836852502] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2021/04/12 12:39:34 [Info] [2636539523] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > context canceled
2021/04/12 12:39:34 [Info] [2636539523] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: connection ends > context canceled
2021/04/12 12:39:34 [Info] [1697916552] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > context canceled
2021/04/12 12:39:34 [Info] [1697916552] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: connection ends > context canceled
2021/04/12 12:39:34 [Info] [1588314163] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > context canceled
2021/04/12 12:39:34 [Info] [1588314163] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: connection ends > context canceled

**Comment by CeeIM** [comment]
@JimhHan SSH IP 已隐藏为：tcp:SSH:22

**Comment by JimhHan** [comment]
似乎没有异常。也许是路由器插件导致的。
先 close了。有如果有其他异常请重新打开 issue。
