### ISSUE TITLE
xray有时候会占用udp53端口，导致本地dnsmasq服务不能使用

### ISSUE THREAD

**Issue by ericwang2006** [XTLS/Xray-core#504]
# 这个问题是我iptables规则设置的问题 iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53 导致了循环访问

此问题已经可以复现,  我把配置文件做了适当简化, 就做了一个freedom出口
目前测试**和服务器端配置无关**
复现步骤如下

- 操作系统alpine 3.13 （Linux mydns 5.4.109-0-virt #1-Alpine SMP Wed, 31 Mar 2021 10:17:30 UTC x86_64 Linux）

- 开dnsmasq服务, dnsmasq服务配置文件如下
```
port=53
conf-dir=/etc/dnsmasq.d
resolv-file=/etc/resolv.dnsmasq.conf
strict-order
clear-on-reload
cache-size=10000
```

- xray客户端配置文件,做透明代理

```
{
    "log":
    {
        "access": "/tmp/v2ray_access_log.log",
        "error": "/tmp/v2ray_error_log.log",
        "loglevel": "warning"
    },
    "inbounds": [
        {
            "tag": "transparent",
            "port": 12345,
            "protocol": "dokodemo-door",
            "settings":
            {
                "network": "tcp,udp",
                "followRedirect": true
            },
            "sniffing":
            {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            }
        }
    ],
//由于和服务器配置无关,这里只做一个freedom出口
    "outbounds": [
        {
            "tag": "direct",
            "protocol": "freedom",
            "settings":
            {},
            "streamSettings":
            {
                "sockopt":
                {
                    "mark": 255
                }
            }
        }
    ],
    "dns":
    {
        "servers": [
            "114.114.114.114"
        ]
    },
    "routing":
    {
        "domainStrategy": "IPOnDemand",
        "rules": [
            {
                "type": "field",
                "ip": [
                    "geoip:private"
                ],
                "outboundTag": "direct"
            }
        ]
    }
}

```

- iptables规则如下

```
#/bin/sh
iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53

iptables -t nat -N V2RAY
iptables -t nat -A V2RAY -d 0.0.0.0/8 -j RETURN
iptables -t nat -A V2RAY -d 10.0.0.0/8 -j RETURN
iptables -t nat -A V2RAY -d 127.0.0.0/8 -j RETURN
iptables -t nat -A V2RAY -d 169.254.0.0/16 -j RETURN
iptables -t nat -A V2RAY -d 172.16.0.0/12 -j RETURN
iptables -t nat -A V2RAY -d 192.168.0.0/16 -j RETURN
iptables -t nat -A V2RAY -d 224.0.0.0/4 -j RETURN
iptables -t nat -A V2RAY -d 240.0.0.0/4 -j RETURN
iptables -t nat -A V2RAY -p tcp -j RETURN -m mark --mark 0xff
iptables -t nat -A V2RAY -p tcp -j REDIRECT --to-ports 12345
iptables -t nat -A PREROUTING -p tcp -j V2RAY

ip rule add fwmark 1 table 100 
ip route add local 0.0.0.0/0 dev lo table 100
iptables -t mangle -N V2RAY
iptables -t mangle -A V2RAY -p udp -m udp --dport 443 -j RETURN
iptables -t mangle -A V2RAY -d 0.0.0.0/8 -j RETURN
iptables -t mangle -A V2RAY -d 10.0.0.0/8 -j RETURN
iptables -t mangle -A V2RAY -d 127.0.0.0/8 -j RETURN
iptables -t mangle -A V2RAY -d 169.254.0.0/16 -j RETURN
iptables -t mangle -A V2RAY -d 172.16.0.0/12 -j RETURN
iptables -t mangle -A V2RAY -d 192.168.0.0/16 -j RETURN
iptables -t mangle -A V2RAY -d 224.0.0.0/4 -j RETURN
iptables -t mangle -A V2RAY -d 240.0.0.0/4 -j RETURN
iptables -t mangle -A V2RAY -p udp -j TPROXY --on-port 12345 --tproxy-mark 1
iptables -t mangle -A PREROUTING -p udp -j V2RAY
```

- 测试方法
打开浏览器, 必须使用**chrome**浏览器(ie和firefox经测试没问题)
访问一个**不存在**的域名, 比如地址栏输入 [http://www.not_exist_domain.com](http://www.not_exist_domain.com)
xray就会开始监听udp 53端口, 并且Recv-Q的值非常大，`netstat -nlp` 类似下面结果
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
udp    10752      0 192.168.2.50:53         0.0.0.0:*                           2499/v2ray
udp    19968      0 192.168.2.50:53         0.0.0.0:*                           2499/v2ray
```
如果iptables规则中没有
_iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53_
xray就开始监听UDP 8.8.8.8:53, 类似下面这样
`udp    10752      0 8.8.8.8:53         0.0.0.0:*                           2499/v2ray`

我的chrome版本是 90.0.4430.72（正式版本） （64 位）
经测试和扩展插件无关，即使是使用隐身模式也可以复现

目前我已经从最新版本一直测试到了1.2.4版本, 均可以复现 (改用V2Ray 4.32.1没有问题)
有最新的测试结果我再补充

**Comment by AkinoKaede** [comment]
LISTEN 代表监听，没有看见 Xray 监听 53/UDP

**Comment by ericwang2006** [comment]
> LISTEN 代表监听，没有看见 Xray 监听 53/UDP

如果监听端口是UDP端口，是不会显示LISTEN的，只有TCP端口才会显示LISTEN
我的命令是**netstat -nlptu**有 -l 参数，-l参数是--listening，表示只列出所有监听的端口
我查了一下man，
   -l, --listening
       Show only listening sockets.  (These are omitted by default.)

   -a, --all
       Show  both  listening and non-listening sockets.  With the --interfaces
       option, show interfaces that are not up

只显示监听端口（ Show only listening sockets）也是netstat的默认行为（omitted by default），除非加了-a参数

我觉得从日志来看Xray还是监听了UDP 53端口
但是具体原因可能比较复杂，我提供的信息也可能是不足够的
我也愿意进一步补充信息，希望开发者能帮忙看一下（我充分理解这并非是开发者的义务）
非常感谢！

**Comment by ericwang2006** [comment]
今天又出现了一次这种情况,这次我保留了一份完整的netstat的结果
```
mydns:~# netstat -nlptu>ttt.txt
mydns:~# cat ttt.txt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:1043            0.0.0.0:*               LISTEN      2886/shttpd
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      19297/dnsmasq
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      2486/sshd [listener
tcp        0      0 :::53                   :::*                    LISTEN      19297/dnsmasq
tcp        0      0 :::22                   :::*                    LISTEN      2486/sshd [listener
tcp        0      0 :::3128                 :::*                    LISTEN      19239/v2ray
tcp        0      0 :::1080                 :::*                    LISTEN      19239/v2ray
tcp        0      0 :::12345                :::*                    LISTEN      19239/v2ray
tcp        0      0 :::10430                :::*                    LISTEN      21415/v2ray
tcp        0      0 :::5353                 :::*                    LISTEN      19239/v2ray
udp        0      0 0.0.0.0:60689           0.0.0.0:*                           -
udp        0      0 0.0.0.0:2393            0.0.0.0:*                           -
udp      768      0 192.168.2.99:53         0.0.0.0:*                           19239/v2ray
udp      768      0 192.168.2.99:53         0.0.0.0:*                           19239/v2ray
udp    39936      0 192.168.2.99:53         0.0.0.0:*                           19239/v2ray
udp    17664      0 192.168.2.99:53         0.0.0.0:*                           19239/v2ray
udp    34560      0 192.168.2.99:53         0.0.0.0:*                           19239/v2ray
udp    13824      0 192.168.2.99:53         0.0.0.0:*                           19239/v2ray
udp        0      0 0.0.0.0:53              0.0.0.0:*                           19297/dnsmasq
udp        0      0 0.0.0.0:67              0.0.0.0:*                           19297/dnsmasq
udp        0      0 :::57490                :::*                                19239/v2ray
udp        0      0 :::34976                :::*                                19239/v2ray
udp        0      0 :::10430                :::*                                21415/v2ray
udp        0      0 :::57569                :::*                                19239/v2ray
udp        0      0 :::5353                 :::*                                19239/v2ray
udp        0      0 :::60689                :::*                                -
udp        0      0 :::37670                :::*                                19239/v2ray
udp        0      0 :::2393                 :::*                                -
udp        0      0 :::42512                :::*                                19239/v2ray
udp        0      0 :::58900                :::*                                19239/v2ray
udp        0      0 :::53                   :::*                                19297/dnsmasq
udp        0      0 :::12345                :::*                                19239/v2ray
```

**Comment by azzvx** [comment]
> 今天又出现了一次这种情况,这次我保留了一份完整的netstat的结果
> 
> ```
> mydns:~# netstat -nlptu>ttt.txt
> mydns:~# cat ttt.txt
> Active Internet connections (only servers)
> Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
> tcp        0      0 0.0.0.0:1043            0.0.0.0:*               LISTEN      2886/shttpd
> tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      19297/dnsmasq
> tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      2486/sshd [listener
> tcp        0      0 :::53                   :::*                    LISTEN      19297/dnsmasq
> tcp        0      0 :::22                   :::*                    LISTEN      2486/sshd [listener
> tcp        0      0 :::3128                 :::*                    LISTEN      19239/v2ray
> tcp        0      0 :::1080                 :::*                    LISTEN      19239/v2ray
> tcp        0      0 :::12345                :::*                    LISTEN      19239/v2ray
> tcp        0      0 :::10430                :::*                    LISTEN      21415/v2ray
> tcp        0      0 :::5353                 :::*                    LISTEN      19239/v2ray
> udp        0      0 0.0.0.0:60689           0.0.0.0:*                           -
> udp        0      0 0.0.0.0:2393            0.0.0.0:*                           -
> udp      768      0 192.168.2.99:53         0.0.0.0:*                           19239/v2ray
> udp      768      0 192.168.2.99:53         0.0.0.0:*                           19239/v2ray
> udp    39936      0 192.168.2.99:53         0.0.0.0:*                           19239/v2ray
> udp    17664      0 192.168.2.99:53         0.0.0.0:*                           19239/v2ray
> udp    34560      0 192.168.2.99:53         0.0.0.0:*                           19239/v2ray
> udp    13824      0 192.168.2.99:53         0.0.0.0:*                           19239/v2ray
> udp        0      0 0.0.0.0:53              0.0.0.0:*                           19297/dnsmasq
> udp        0      0 0.0.0.0:67              0.0.0.0:*                           19297/dnsmasq
> udp        0      0 :::57490                :::*                                19239/v2ray
> udp        0      0 :::34976                :::*                                19239/v2ray
> udp        0      0 :::10430                :::*                                21415/v2ray
> udp        0      0 :::57569                :::*                                19239/v2ray
> udp        0      0 :::5353                 :::*                                19239/v2ray
> udp        0      0 :::60689                :::*                                -
> udp        0      0 :::37670                :::*                                19239/v2ray
> udp        0      0 :::2393                 :::*                                -
> udp        0      0 :::42512                :::*                                19239/v2ray
> udp        0      0 :::58900                :::*                                19239/v2ray
> udp        0      0 :::53                   :::*                                19297/dnsmasq
> udp        0      0 :::12345                :::*                                19239/v2ray
> ```

dnsmasq为什么设置监听0.0.0.0呢？直接不设置让它监听每个接口就好了啊。先把位置占走，xray就不会监听了。

**Comment by ericwang2006** [comment]
> > 今天又出现了一次这种情况,这次我保留了一份完整的netstat的结果
> > ```
> > mydns:~# netstat -nlptu>ttt.txt
> > mydns:~# cat ttt.txt
> > Active Internet connections (only servers)
> > Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
> > tcp        0      0 0.0.0.0:1043            0.0.0.0:*               LISTEN      2886/shttpd
> > tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      19297/dnsmasq
> > tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      2486/sshd [listener
> > tcp        0      0 :::53                   :::*                    LISTEN      19297/dnsmasq
> > tcp        0      0 :::22                   :::*                    LISTEN      2486/sshd [listener
> > tcp        0      0 :::3128                 :::*                    LISTEN      19239/v2ray
> > tcp        0      0 :::1080                 :::*                    LISTEN      19239/v2ray
> > tcp        0      0 :::12345                :::*                    LISTEN      19239/v2ray
> > tcp        0      0 :::10430                :::*                    LISTEN      21415/v2ray
> > tcp        0      0 :::5353                 :::*                    LISTEN      19239/v2ray
> > udp        0      0 0.0.0.0:60689           0.0.0.0:*                           -
> > udp        0      0 0.0.0.0:2393            0.0.0.0:*                           -
> > udp      768      0 192.168.2.99:53         0.0.0.0:*                           19239/v2ray
> > udp      768      0 192.168.2.99:53         0.0.0.0:*                           19239/v2ray
> > udp    39936      0 192.168.2.99:53         0.0.0.0:*                           19239/v2ray
> > udp    17664      0 192.168.2.99:53         0.0.0.0:*                           19239/v2ray
> > udp    34560      0 192.168.2.99:53         0.0.0.0:*                           19239/v2ray
> > udp    13824      0 192.168.2.99:53         0.0.0.0:*                           19239/v2ray
> > udp        0      0 0.0.0.0:53              0.0.0.0:*                           19297/dnsmasq
> > udp        0      0 0.0.0.0:67              0.0.0.0:*                           19297/dnsmasq
> > udp        0      0 :::57490                :::*                                19239/v2ray
> > udp        0      0 :::34976                :::*                                19239/v2ray
> > udp        0      0 :::10430                :::*                                21415/v2ray
> > udp        0      0 :::57569                :::*                                19239/v2ray
> > udp        0      0 :::5353                 :::*                                19239/v2ray
> > udp        0      0 :::60689                :::*                                -
> > udp        0      0 :::37670                :::*                                19239/v2ray
> > udp        0      0 :::2393                 :::*                                -
> > udp        0      0 :::42512                :::*                                19239/v2ray
> > udp        0      0 :::58900                :::*                                19239/v2ray
> > udp        0      0 :::53                   :::*                                19297/dnsmasq
> > udp        0      0 :::12345                :::*                                19239/v2ray
> > ```
> 
> dnsmasq为什么设置监听0.0.0.0呢？直接不设置让它监听每个接口就好了啊。先把位置占走，xray就不会监听了。

alpine系统的dnsmasq似乎是有问题,配置文件已经添加了
listen-address=127.0.0.1,192.168.2.99
但是重启服务后始终是监听以下两个端口
udp        0      0 0.0.0.0:53              0.0.0.0:*                           2475/dnsmasq
udp        0      0 :::53                   :::*                                2475/dnsmasq

xray占用udp 53端口我总觉得存在某种规律, 只是我现在还没有找到, 目前是不定期的出现

**Comment by azzvx** [comment]
我自己试了一下，你只设置`listen-address`是没用的，要同时设置`bind-interfaces`，否则随便咋整监听的都是`0.0.0.0`。
而且正常情况只要设置`bind-interfaces`就好了，它会自动监听每个接口的53端口，不用手动设置`listen-address`指定。

**Comment by ericwang2006** [comment]
> `bind-interfaces`就好了

你说得对, 加上bind-interfaces就好了

但是不一定会解决xray占用udp 53端口的问题, 就像上面我用nc命令的测试, 
udp端口不会被某个进程独占
而是后占用的进程是实际占有者.

我先bind-interfaces测试一下吧,谢谢你

**Comment by ericwang2006** [comment]
此问题已经可以复现, 步骤如下
目前已经测试,和服务器端配置无关,甚至和具体的协议都没有关系(vless和vmess都测试过)
复现步骤如下

操作系统alpine 3.13 （Linux mydns 5.4.109-0-virt #1-Alpine SMP Wed, 31 Mar 2021 10:17:30 UTC x86_64 Linux）
开dnsmasq服务, dnsmasq服务配置文件如下
```
port=53
conf-dir=/etc/dnsmasq.d
resolv-file=/etc/resolv.dnsmasq.conf
strict-order
clear-on-reload
cache-size=10000
```

xray客户端配置文件
做透明代理

```
{
    "log":
    {
        "access": "/tmp/v2ray_access_log.log",
        "error": "/tmp/v2ray_error_log.log",
        "loglevel": "warning"
    },
    "inbounds": [
        {
            "tag": "transparent",
            "port": 12345,
            "protocol": "dokodemo-door",
            "settings":
            {
                "network": "tcp,udp",
                "followRedirect": true
            },
            "sniffing":
            {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            }
        },
        {
            "protocol": "dokodemo-door",
            "port": 5353,
            "settings":
            {
                "address": "1.1.1.1",
                "port": 53,
                "network": "tcp,udp",
                "timeout": 0
            }
        }
    ],
//出口的协议不关键,试过自建vps和机场都可以复现
    "outbounds": [
        {
            "tag": "proxy",
            "protocol": "vmess",
            "settings":
            {
                "vnext": [
                    {
                        "address": "x.x.x.x",
                        "port": 80,
                        "users": [
                            {
                                "id": "合法id",
                                "alterId": 1,
                                "email": "t@t.tt",
                                "security": "auto"
                            }
                        ]
                    }
                ]
            },
            "streamSettings":
            {
                "network": "ws",
                "wsSettings":
                {
                    "connectionReuse": true,
                    "path": "/",
                    "headers":
                    {
                        "Host": "003.cdn.8x.cx.hit.edu.cn"
                    }
                }
            },
            "mux":
            {
                "enabled": false,
                "concurrency": -1
            }
        },
        {
            "tag": "direct",
            "protocol": "freedom",
            "settings":
            {},
            "streamSettings":
            {
                "sockopt":
                {
                    "mark": 255
                }
            }
        },
        {
            "tag": "block",
            "protocol": "blackhole",
            "settings":
            {
                "response":
                {
                    "type": "http"
                }
            }
        }
    ],
    "dns":
    {
        "servers": [
            "8.8.4.4",
            "1.1.1.1"
        ]
    },
    "routing":
    {
        "domainStrategy": "IPOnDemand",
        "rules": [
            {
                "type": "field",
                "ip": [
                    "223.5.5.5",
                    "119.29.29.29"
                ],
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "ip": [
                    "8.8.4.4",
                    "1.1.1.1"
                ],
                "outboundTag": "proxy"
            },
            {
                "type": "field",
                "ip": [
                    "geoip:private"
                ],
                "outboundTag": "direct"
            }
        ]
    }
}
```
iptables规则如下

```
#/bin/sh
iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53
iptables -t nat -A POSTROUTING -s 10.0.0.0/8 -o eth0 -j MASQUERADE

#gfw模式
iptables -t nat -N V2RAY
iptables -t nat -A V2RAY -d 0.0.0.0/8 -j RETURN
iptables -t nat -A V2RAY -d 10.0.0.0/8 -j RETURN
iptables -t nat -A V2RAY -d 127.0.0.0/8 -j RETURN
iptables -t nat -A V2RAY -d 169.254.0.0/16 -j RETURN
iptables -t nat -A V2RAY -d 172.16.0.0/12 -j RETURN
iptables -t nat -A V2RAY -d 192.168.0.0/16 -j RETURN
iptables -t nat -A V2RAY -d 224.0.0.0/4 -j RETURN
iptables -t nat -A V2RAY -d 240.0.0.0/4 -j RETURN
iptables -t nat -A V2RAY -p tcp -j RETURN -m mark --mark 0xff
iptables -t nat -A V2RAY -p tcp -m set --match-set myvps dst -j RETURN
iptables -t nat -A V2RAY -p tcp -m set --match-set gfwlist  dst -j REDIRECT --to-ports 12345
iptables -t nat -A V2RAY -p tcp -m set --match-set dnslist  dst -j REDIRECT --to-ports 12345
iptables -t nat -A PREROUTING -p tcp -j V2RAY

iptables -t nat -A OUTPUT -p tcp -m set --match-set dnslist  dst -j REDIRECT --to-ports 12345

ip rule add fwmark 1 table 100 
ip route add local 0.0.0.0/0 dev lo table 100
iptables -t mangle -N V2RAY
iptables -t mangle -A V2RAY -p udp -m udp --dport 443 -j RETURN
iptables -t mangle -A V2RAY -d 0.0.0.0/8 -j RETURN
iptables -t mangle -A V2RAY -d 10.0.0.0/8 -j RETURN
iptables -t mangle -A V2RAY -d 127.0.0.0/8 -j RETURN
iptables -t mangle -A V2RAY -d 169.254.0.0/16 -j RETURN
iptables -t mangle -A V2RAY -d 172.16.0.0/12 -j RETURN
iptables -t mangle -A V2RAY -d 192.168.0.0/16 -j RETURN
iptables -t mangle -A V2RAY -d 224.0.0.0/4 -j RETURN
iptables -t mangle -A V2RAY -d 240.0.0.0/4 -j RETURN
iptables -t mangle -A V2RAY -p udp -m set --match-set myvps dst -j RETURN
iptables -t mangle -A V2RAY -p udp -m set --match-set gfwlist  dst -j TPROXY --on-port 12345 --tproxy-mark 1
iptables -t mangle -A V2RAY -p udp -m set --match-set dnslist  dst -j TPROXY --on-port 12345 --tproxy-mark 1
iptables -t mangle -A PREROUTING -p udp -j V2RAY
```

测试网页
test.htm
将下面内容存成一个test.htm文件, 用chrome打开, 点击网页中的链接, xray就开始监听本地udp53端口
```
<html>
     <a href="http://jump.bdimg.com/safecheck/index?url=x+Z5mMbGPAulE0oDRLBHgg/QRgPz4donD82mvcQ2wZXgkD14o+5pxKpbX8IWTsRFHSYcgr+eQFpVRg4DfT02fz4b3hBvK3p9RtsSVars1dANJekKwBRCrc3tZjfPTSQcmnGkH1LFjPyFlX88n2jsWuM3NiDmSrW0bBtv3uWGB1k/cCU/DwPrrMZBTM6g9kyFdj2oeHoEzTI="  target="_blank" >点我点我点我</a>
</html>
```

目前我已经从最新版本一直测试到了1.2.4版本, 均可以复现 (改用V2Ray 4.32.1没有问题)
有最新的测试结果我再补充

**Comment by oscarpp1984** [comment]
root@ImmortalWrt:~# netstat -apn | grep 53
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      11447/dnsmasq
tcp        0      0 192.168.2.1:53          0.0.0.0:*               LISTEN      11447/dnsmasq
tcp        0      0 xxx.164.104.158:53      0.0.0.0:*               LISTEN      11447/dnsmasq
tcp        0      0 0.0.0.0:5355            0.0.0.0:*               LISTEN      8466/wsdd2
tcp        0      0 xxx.164.104.158:53106   199.180.112.22:443      ESTABLISHED 10415/xray
tcp        0      0 xxx.164.104.158:53108   xxx.180.112.22:443      ESTABLISHED 10415/xray
tcp        0      0 xxx.164.104.158:53034   xxx.180.112.22:443      ESTABLISHED 10341/xray
tcp     8232      0 xxx.164.104.158:35382   xxx.102.178.59:80       CLOSE_WAIT  12144/node
tcp        0      0 xxx.164.104.158:41530   xxx.102.178.59:80       CLOSE_WAIT  12144/node
tcp     8448      0 xxx.164.104.158:53122   xxx.102.178.60:80       CLOSE_WAIT  12144/node
tcp        0      0 xxx.164.104.158:53074   xxx.180.112.22:443      TIME_WAIT   -
tcp        0      0 xxx.164.104.158:53062   xxx.180.112.22:443      TIME_WAIT   -
tcp        0      0 xxx.164.104.158:53098   xxx.180.112.22:443      ESTABLISHED 10341/xray
tcp        0      0 xxx.164.104.158:53070   xxx.180.112.22:443      ESTABLISHED 10341/xray
tcp        0      0 ::1:53                  :::*                    LISTEN      11447/dnsmasq
tcp        0      0 fe80::7801:ceff:fe7c:7f7b:53 :::*                    LISTEN      11447/dnsmasq
tcp        0      0 fd6d:c634:846e::1:53    :::*                    LISTEN      11447/dnsmasq
tcp        0      0 fe80::7801:ceff:fe7c:7f7c:53 :::*                    LISTEN      11447/dnsmasq
tcp        0      0 :::5355                 :::*                    LISTEN      8466/wsdd2
tcp        0      0 :::5355                 :::*                    LISTEN      8466/wsdd2
tcp        0      0 ::ffff:192.168.2.1:1041 ::ffff:192.168.2.155:53779 ESTABLISHED 10341/xray
udp    11520      0 192.168.2.1:53          0.0.0.0:*                           10415/xray
udp     6144      0 192.168.2.1:53          0.0.0.0:*                           10415/xray
udp        0      0 127.0.0.1:53            0.0.0.0:*                           11447/dnsmasq
udp        0      0 192.168.2.1:53          0.0.0.0:*                           11447/dnsmasq
udp        0      0 xxx.164.104.158:53      0.0.0.0:*                           11447/dnsmasq
udp        0      0 192.168.2.1:5351        0.0.0.0:*                           7204/miniupnpd
udp        0      0 0.0.0.0:5355            0.0.0.0:*                           8466/wsdd2
udp        0      0 ::1:53                  :::*                                11447/dnsmasq
udp        0      0 fe80::xxxx:ceff:fe7c:7f7b:53 :::*                                11447/dnsmasq
udp        0      0 fd6d:xxxx:846e::1:53    :::*                                11447/dnsmasq
udp        0      0 fe80::xxxx:ceff:fe7c:7f7c:53 :::*                                11447/dnsmasq
udp        0      0 :::5355                 :::*                                8466/wsdd2
udp        0      0 :::5355                 :::*                                8466/wsdd2
unix  2      [ ]         DGRAM                      2538 1430/hostapd        /var/run/hostapd/global


用的是r2s软路由，不定期就会dns不能解析，每次只要失败，运行netstat就会看见xray在53端口，只要停掉passwall，马上恢复正常，已经改用ssrplus了。

**Comment by yaotthaha** [comment]
和我一样的问题，也是Xray无故占用53/udp端口

**Comment by dfldylan** [comment]
有同样的问题，注意一下图中我是简单地mv xray /usr/bin/v2ray了，所以名字是v2ray
<img width="629" alt="截屏2022-05-01 23 22 15" src="https://user-images.githubusercontent.com/28103567/166152645-f4cc9564-be95-408c-a5d9-75d00f431d55.png">
换成v2ray 4.44就不会出现这种问题。
<img width="629" alt="截屏2022-05-01 23 24 25" src="https://user-images.githubusercontent.com/28103567/166152737-694951d8-fb6a-4237-9908-275a19e72fb3.png">
设备是r4s，arm64的

**Comment by kid-oh** [comment]
我的r2s有时一些网站打不开 不知道是不是这个原因
