### ISSUE TITLE
额外idbug

### ISSUE THREAD

**Issue by chuan01** [XTLS/Xray-core#509]
额外id 10000以上就会刷爆内存和swap

**Comment by HynoR** [comment]
这得十年脑血栓才想的出来aid调这么高吧

**Comment by zhouchenh** [comment]
根据设备可用内存大小限制一下最大aid？

**Comment by JimhHan** [comment]
1. xray 要记录这 10000 个 id 前后 60 秒的哈希值。仅仅这些数据就需要 38.4 MB 的内存，何况还需要记录到 map 中。
2. 如此巨大的 alterID 没用任何实际意义，尤其是 vMess 已经支持了  AEAD。
