### ISSUE TITLE
用的是torjan协议，xbox 连外服，丢包非常严重，怀疑是MTU的值导致，请教大佬如何破

### ISSUE THREAD

**Issue by hackingchen** [XTLS/Xray-core#513]
好不容易搞到fullcone，时延还好，但是100%丢包了。
用UU加速器的时候，MTU是1452
上了torjan之后，MTU是1500

**Comment by z826540272** [comment]
用ss/ssr

**Comment by wutongskype** [comment]
建议用xtls,quic,mkcp等...
建议去 https://lala.im/
看看啦啦大佬的相关游戏加速的方案.
不过线路质量大于软件技术
世界加钱可及

**Comment by hackingchen** [comment]
> 建议用xtls,quic,mkcp等...
> 建议去 https://lala.im/
> 看看啦啦大佬的相关游戏加速的方案.
> 不过线路质量大于软件技术
> 世界加钱可及

谢谢回复，lala的看过了，越看越迷糊了，现在先转换方向试一下。

**Comment by GleenJi** [comment]
我打彩六稳定50-60延迟

**Comment by hackingchen** [comment]
> 我打彩六稳定50-60延迟

请教大佬，你是用什么方案？Xbox直接上软路由吗？有没有做各类加速？

**Comment by GleenJi** [comment]
> 
> 
> > 我打彩六稳定50-60延迟
> 
> 请教大佬，你是用什么方案？Xbox直接上软路由吗？有没有做各类加速？

sry，忘说了，我是pc彩六..............

**Comment by GleenJi** [comment]
> 
> 
> > 我打彩六稳定50-60延迟
> 
> 请教大佬，你是用什么方案？Xbox直接上软路由吗？有没有做各类加速？

直接电脑netch

**Comment by sndnnlfhvk** [comment]
> > 建议用xtls,quic,mkcp等...
> > 建议去 https://lala.im/
> > 看看啦啦大佬的相关游戏加速的方案.
> > 不过线路质量大于软件技术
> > 世界加钱可及
> 
> 谢谢回复，lala的看过了，越看越迷糊了，现在先转换方向试一下。

下意识地看来下帖子的时间，quic,mkcp等方案是秒封的。

**Comment by wutongskype** [comment]
> > > 建议用xtls,quic,mkcp等...
> > > 建议去 https://lala.im/
> > > 看看啦啦大佬的相关游戏加速的方案.
> > > 不过线路质量大于软件技术
> > > 世界加钱可及
> > 
> > 
> > 谢谢回复，lala的看过了，越看越迷糊了，现在先转换方向试一下。
> 
> 下意识地看来下帖子的时间，quic,mkcp等方案是秒封的。

是游戏被封还是ip被墙？我们这一直都好着，mkcp用seed应该没事，就是一直有bug，会把网络堵死，连接都跑完了完了还在那发包，记得3.0时代还是2.0时代就没这问题，不知修复了没。再就是quic，很久以前测过，被运营商qos的太严重了，再就是不支持多线程，用idm下载时从idm上看有多线程，但是速度起不来，从路由器看是一个单线程。。。。估计俺姿势不对，跑这些udp的协议估计要套个udpraw一些的伪装或加速程序。

**Comment by wutongskype** [comment]
> > > 建议用xtls,quic,mkcp等...
> > > 建议去 https://lala.im/
> > > 看看啦啦大佬的相关游戏加速的方案.
> > > 不过线路质量大于软件技术
> > > 世界加钱可及
> > 
> > 
> > 谢谢回复，lala的看过了，越看越迷糊了，现在先转换方向试一下。
> 
> 下意识地看来下帖子的时间，quic,mkcp等方案是秒封的。



> > > 建议用xtls,quic,mkcp等...
> > > 建议去 https://lala.im/
> > > 看看啦啦大佬的相关游戏加速的方案.
> > > 不过线路质量大于软件技术
> > > 世界加钱可及
> > 
> > 
> > 谢谢回复，lala的看过了，越看越迷糊了，现在先转换方向试一下。
> 
> 下意识地看来下帖子的时间，quic,mkcp等方案是秒封的。

说真的之前v2的纯udp协议就没一个好用的。。。现在xray不知道修复没。真希望能出一个，自带伪装过墙，自带udpraw功能破udpqos，兼顾多倍发包提升稳定性减少丢包等，专为游戏、轻流量等场景开发的协议。

**Comment by ymcoming** [comment]
udp未必会qos，那是老观念。过去我这里电信qos udp 到5000kbps死死的，现在再没这情况了。想来5G、千兆什么的出来后，这qos临界值提高了，提高到多少我不知道，但看4K奈飞什么的，肯定不会qos，我经常用xray的mkcp连续追剧8一10小时。

**Comment by jiuqi9997** [comment]
@ymcoming 这边东莞移动，udp随时随地被qos限速到虚无
