### ISSUE TITLE
关于https回落，域名监听，tls和xtls问题的汇总，

### ISSUE THREAD

**Issue by stonegr** [XTLS/Xray-core#516]
首先感谢大佬的辛勤付出，测试了一上午，发现如下问题，若是我使用方法问题还请大佬指点
1、非443端口搭建vless xtls时，比如881，http://a.com:8881不能设置跳转https://a.com:8881,
因为xray监听8881，所以nginx无法做处理
2、回落问题，烦请大佬说下怎么测试，
![image](https://user-images.githubusercontent.com/74632994/114806461-613f4d00-9dd7-11eb-9ef2-0ac1785f9cdc.png)
![image](https://user-images.githubusercontent.com/74632994/114806554-8b910a80-9dd7-11eb-81c7-b0a33d4a05cc.png)
测试https://a.com:8881可以回落到网站，但是http://a.com:8881不能
3、在上诉协议中，我使用泛域名证书，无论是tls 还是 xtls 中假设serverName：1.a.com，但是我将sni或者host改为2.a.com都能连接成功且使用，如果使用单个域名证书则不出现这个问题。
![image](https://user-images.githubusercontent.com/74632994/114806721-ca26c500-9dd7-11eb-98a7-2c95f28a8ed0.png)

最后再次感谢大佬的辛勤付出，如果能够解决，不胜感激！

**Comment by wutongskype** [comment]
https://lala.im/7666.html
https://lala.im/7737.html
参考一下这两个吧,没搞懂你啥意思.
主要看你是nginx前置,还是xray前置.
反正我是xray前置搞成了,照着终极配置模板来就行了.nginx前置SNI分流还没搞懂.
https://github.com/XTLS/Xray-examples/tree/main/VLESS-TCP-XTLS-WHATEVER

**Comment by adldeez** [comment]
第二个问题，servername是客户端用的吧……服务器端要限制证书只能单域名证书吧……

第一个问题你一定要把http和https放在同一个端口……
大概可以用nginx的stream模块在最前先分流一次……

nginx多加一个server监听8882，里面设置return 301，可以参考配置示例……
xray监听8883

然后给nginx.conf加上stream分流
`stream {
    map $ssl_preread_server_name $backend {
        default tohttp;
        "TLSv1.1" tohttps;
        "TLSv1.2" tohttps;
        "TLSv1.3" tohttps;
    }
    upstream tohttp {
        server 127.0.0.1:8882;
    }
    upstream tohttps {
        server 127.0.0.1:8883;
    }
    server {
        listen 8881;
        proxy_pass $backend;
        ssl_preread on;
    }
}`

不知道可不可行……
