### ISSUE TITLE
复现无限流量

### ISSUE THREAD

**Issue by yuhan6665** [XTLS/Xray-core#517]
在 v2rayNG 上测试的时候偶然发现了这个问题，方法如下：
1. 在同一台 vps 上加两个 inbound 一个 vmess quic（以下例子中 port 9715）一个可用入口（以下例子中 port 443，vless xtls）
2. 将设置中 quic key 故意写错
3. 连接 quic，等一会产生一些流量，显示连接失败
4. 断开 quic，连另一个可用配置
5. 发现去 9715 的无限流量

PS: 测了一下 v2fly 是一样的

[infinite.txt](https://github.com/XTLS/Xray-core/files/6314964/infinite.txt)

**Comment by yuhan6665** [comment]
啥都不懂，从流量日志入手
```
	Line 300: 2021-04-15 11:00:54.510 6305-6346/com.v2ray.ang I/GoLog: [Debug] [2693955182] transport/internet/udp: dispatch request to: udp:ip.addr.1.1:9715
	Line 307: 2021-04-15 11:00:54.713 6305-6364/com.v2ray.ang I/GoLog: [Debug] [2693955182] transport/internet/udp: dispatch request to: udp:ip.addr.1.1:9715
	Line 309: 2021-04-15 11:00:54.713 6305-6364/com.v2ray.ang I/GoLog: [Debug] [2693955182] transport/internet/udp: dispatch request to: udp:ip.addr.1.1:9715
	Line 311: 2021-04-15 11:00:55.121 6305-6340/com.v2ray.ang I/GoLog: [Debug] [2693955182] transport/internet/udp: dispatch request to: udp:ip.addr.1.1:9715
	Line 313: 2021-04-15 11:00:55.121 6305-6340/com.v2ray.ang I/GoLog: [Debug] [2693955182] transport/internet/udp: dispatch request to: udp:ip.addr.1.1:9715
	Line 315: 2021-04-15 11:00:55.921 6305-6341/com.v2ray.ang I/GoLog: [Debug] [2693955182] transport/internet/udp: dispatch request to: udp:ip.addr.1.1:9715
	Line 317: 2021-04-15 11:00:55.921 6305-6341/com.v2ray.ang I/GoLog: [Debug] [2693955182] transport/internet/udp: dispatch request to: udp:ip.addr.1.1:9715
	Line 319: 2021-04-15 11:00:57.531 6305-6340/com.v2ray.ang I/GoLog: [Debug] [2693955182] transport/internet/udp: dispatch request to: udp:ip.addr.1.1:9715
	Line 321: 2021-04-15 11:00:57.531 6305-6340/com.v2ray.ang I/GoLog: [Debug] [2693955182] transport/internet/udp: dispatch request to: udp:ip.addr.1.1:9715
```
发现这个流量的间隔是 200ms 400ms 800ms 1600ms，总共5次。找到对应代码为 `retry.ExponentialBackoff(5, 200)`

**Comment by yuhan6665** [comment]
周末研究了一下，似乎是因为 quic 未使用 system dialer 然后在安卓上未被 vpn protect。所有流量似乎是经过了 core 两次。。

**Comment by rurirei** [comment]
> 周末研究了一下，似乎是因为 quic 未使用 system dialer 然后在安卓上未被 vpn protect。所有流量似乎是经过了 core 两次。。

try https://github.com/rurirei/Kitsunebi/blob/go/app/src/main/java/io/github/rurirei/v2rayng/service/V2RayVpnService.kt#L187

**Comment by yuhan6665** [comment]
@rurirei thanks for your idea. I tried to exclude v2rayNG in per-app vpn, it does fix the traffic display however after I took a close look by adding log here 
https://github.com/XTLS/Xray-core/blob/7b7084f825a7d74938061b223c79f21801acb7ef/proxy/vmess/outbound/outbound.go#L64
I find core still dials

也就是说还是 core 的问题。另外我发现这个 dial 好像不是无限的，而是会持续很长很长时间。最后会输出以下日志
`26657-26719/com.v2ray.ang I/GoLog: [Warning] [4196287253] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [NO_ERROR: Handshake did not complete in time] > common/retry: all retry attempts failed`

**Comment by yuhan6665** [comment]
经过推敲终于搞清楚了问题所在。这个代码会把失败的 dial 重试 5 次
https://github.com/XTLS/Xray-core/blob/7b7084f825a7d74938061b223c79f21801acb7ef/proxy/vmess/outbound/outbound.go#L62
当底层是 quic 时会在这里握手 8 秒 （近期升级 quic 后变为 5 秒）
https://github.com/XTLS/Xray-core/blob/7b7084f825a7d74938061b223c79f21801acb7ef/transport/internet/quic/dialer.go#L160
所以对于一个不通的节点，每一个请求会在这里用至少 40 秒。而且 quic `openConnection()` 是加锁的，结果就是会有越来越多的请求在这里阻塞等锁。

这个具体问题应当不难解决，但是我看这个 retry 用的地方很多，一旦遇到底层有锁，再加上网络出错就很容易出现无限累加的情况，这是不是其它“无限流量”的原因？
@rprx @AkinoKaede
