### ISSUE TITLE
"cipherSuites" option in XTLS doesn't seem work

### ISSUE THREAD

**Issue by tghBrgS2** [XTLS/Xray-core#521]
I set "cipherSuites" following [this pr](https://github.com/XTLS/Xray-core/pull/78). But when I test my website on SSL Labs, the TLS cipher suites are not what I specified.

Server configuraton:
```json
{
    "inbounds": [
        {
            "port": 443,
            "listen": "0.0.0.0",
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "[deleted]",
                        "flow": "xtls-rprx-direct",
                        "level": 0
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": 10808,
                        "xver": 0
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "alpn": [
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "[deleted]",
                            "keyFile": "[deleted]"
                        }
                    ],
                    "minVersion": "1.3",
                    "cipherSuites": "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256",
                    "preferServerCipherSuites": true
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ]
}
```
The SSL Labs test result is still the default order for TLS 1.3, which is ```TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384```.

**Comment by chika0801** [comment]
give you my temp

    "inbounds": [
        {
            "listen": "0.0.0.0",
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "",
                        "flow": "xtls-rprx-direct"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": "/dev/shm/default.sock",
                        "xver": 2
                    },
                    {
                        "alpn": "h2",
                        "dest": "/dev/shm/h2c.sock",
                        "xver": 2
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "minVersion": "1.2",
                    "cipherSuites": "TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
                    "preferServerCipherSuites": true,
                    "alpn": [
                        "h2",
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "keyFile": "",
                            "certificateFile": "",
                            "ocspStapling": 3600
                        }
                    ]
                }
            }
        }
    ],

**Comment by Funny-T** [comment]
https://github.com/XTLS/Xray-core/issues/114

> "minVersion": "1.3" 

this is a feature

**Comment by tghBrgS2** [comment]
> 
> 
> #114
> 
> > "minVersion": "1.3"
> 
> this is a feature

Thank you.

I will close the issue.
