### ISSUE TITLE
关于为DoH域名解析添加默认IP类型DNS服务器的功能建议

### ISSUE THREAD

**Issue by eihei233** [XTLS/Xray-core#522]
在使用DoH的时候，需要对DoH的域名进行解析，为了防止未拿到自己域名IP的DoH，自己解析自己域名的情况，可以添加一个指定的IP类型DNS服务器来帮助解析DoH域名的功能。

例如：
使用DoHL时，在Windows或者Linux系统中，DoHL请求不会经过router和outbound，直接使用本机的DNS服务解析DoHL的域名并发送DNS请求。但是在Android系统中，例如使用VpnService的v2rayng，会把接管的所有DNS请求通过任意门转发给内置DNS服务器解析，DoH自身的域名解析将再次进行解析，从而无法拿到DoH自己的IP。（目前可行的解决方法似乎只有添加hosts）

**Comment by rurirei** [comment]
for desktop
```jsonc
 "dns": {
    "hosts": {
      "dns.google": "8.8.8.8"
    },
    "servers": [
      "https://dns.google/dns-query"
    ],
    "tag": "nameserver"
  },
```

for Android, v2rayNG uses system dns to solve all query of AsIs freedom outbound. (addition, my new app will provide the feature to apply hosts of v2ray to Android freedom outbound as well.)

**Comment by chika0801** [comment]
doh服务器直接填ip的形式能解决吗
比如
https://1.1.1.1/dns-query

**Comment by rurirei** [comment]
@chika0801 not recommended.

**Comment by eihei233** [comment]
> for desktop
> 
> ```js
>  "dns": {
>     "hosts": {
>       "dns.google": "8.8.8.8"
>     },
>     "servers": [
>       "https://dns.google/dns-query"
>     ],
>     "tag": "nameserver"
>   },
> ```
> 
> for Android, v2rayNG uses system dns to solve all query of AsIs freedom outbound. (addition, my new app will provide the feature to apply hosts of v2ray to Android freedom outbound as well.)

Thank you for your reply. But it seems that while enabling local DNS in v2rayng's setting, all DNS request will be sent to xray again (for example port 10853 if specified in setting), no matter the option in Freedom is AsIs or UseIP, since VpnService will handle all kinds of data stream including DNS request. This means that dohl's name resolution will not be handled by system DNS servers, at least for Android 9.0. In this circumstance, you can only use hosts in xray's DNS settings to solve this problem, which might be a little bit imperfect or so.

**Comment by rurirei** [comment]
@eihei233 all you need to know first. https://github.com/rurirei/Kitsunebi/issues/6#issuecomment-719166632 https://github.com/2dust/v2rayNG/issues/798

**Comment by eihei233** [comment]
> for desktop
> ```jsonc
>  "dns": {
>     "hosts": {
>       "dns.google": "8.8.8.8"
>     },
>     "servers": [
>       "https://dns.google/dns-query"
>     ],
>     "tag": "nameserver"
>   },
> ```
> 
> for Android, v2rayNG uses system dns to solve all query of AsIs freedom outbound. (addition, my new app will provide the feature to apply hosts of v2ray to Android freedom outbound as well.)

Thank you for your reply. Actually, none of those you mentioned answers my questions. Maybe we can discuss via IM if it is okay for you.

**Comment by rurirei** [comment]
@eihei233 you're on much mistakes. i may write a thread to explain the differences of mobile platform in later. **v2ray/xray documentation does nothing specified for mobile platform**.

> This means that dohl's name resolution will not be handled by system DNS servers, at least for Android 9.0.

all dns data is from android system dns server (generally, on Android), and tun2socks, routing, forwarding it to v2ray.

> In this circumstance, you can only use hosts in xray's DNS settings to solve this problem, which might be a little bit imperfect or so.

hosts of v2ray configuration does nothing for dns data in fact (generally, on v2rayNG, localdns. **hosts will not apply to DoHL dns in v2ray**), because those dns data is from android system. hosts could be featured on my new app in later.

conclusionally speaking, there are only two types of data on android: data with remote-server destination, or with non-proxied. dns data is of the latter.

`localdns` does dns data forwarding, and you can use DoH, DoHL, or whatever else.

you can find any explaination in xiaokangwang/AndroidLibV2ray, credits.

**Comment by rurirei** [comment]
**dns is too complicated to explain**, just trust me please, on Android.

**Comment by eihei233** [comment]
@rurirei Thank you for your detailed explanation☺️. Actually, I know what you mean. Forgive me for not describing the situation carefully. I did turn on the Local DNS option in v2rayng's setting, so hosts may affect the results of resolving DoHL's domain name since the request for resolving the DoHL's domain will be forwarded to xray's own DNS server.

So, my question is if it is possible to send the DoHL's own domain resolving request to the system DNS server rather than xray's DNS server even the Local DNS option was turned on. (which seems not possible)

**Comment by rurirei** [comment]
@eihei233 
> I did turn on the Local DNS option in v2rayng's setting, so hosts may affect the results of resolving DoHL's domain name since the request for resolving the DoHL's domain will be forwarded to xray's own DNS server.

**no affects at all**. DoHL do dns forwarding with direct connection.

> if it is possible to send the DoHL's own domain resolving request to the system DNS server rather than xray's DNS server even the Local DNS option was turned on. (which seems not possible)

the process of dns data: system dns -> tun2socks (local dns) -> v2ray outbound (routing to dns outbound) -> v2ray nameserver (DoH, DoHL, or simply udp).

conclusion: the requirement could not be done on v2rayNG, could be done by setup hosts config on desktop.
