### ISSUE TITLE
使用 homebrew 安装的 xray 缺少 plist 

### ISSUE THREAD

**Issue by pys1992** [XTLS/Xray-core#524]
使用 homebrew 安装的 xray 缺少 plist

**Comment by pys1992** [comment]
可以参考这个，https://github.com/xiruizhao/homebrew-xray/blob/d033b37ba964fe2df56a68f3ae188f5bf93b67c9/Formula/xray.rb#L38

**Comment by AkinoKaede** [comment]
不了解这个，不过这个应该找软件包的维护者了…

**Comment by pys1992** [comment]
> 不了解这个，不过这个应该找软件包的维护者了…

咦，我还以为是官方维护的。

**Comment by AkinoKaede** [comment]
翻了半天，发现有 PR 了，Homebrew/homebrew-core#73393
