### ISSUE TITLE
About Naming

### ISSUE THREAD

**Issue by namingPolice** [XTLS/Xray-core#526]
rename ```loglevel``` of ```{ "log": { "loglevel": "" } }``` to ```level``` plz

**Comment by AkinoKaede** [comment]
Why?

**Comment by AkinoKaede** [comment]
> > Why?
> 
> cuz the parent key already contains `"log"`

OK, I think your are right.

**Comment by hmol233** [comment]
Closing due to https://github.com/XTLS/Xray-core/pull/534 and https://github.com/v2fly/v2ray-core/issues/1094#issuecomment-872237656 .

> it would create unnecessary frictions.
