### ISSUE TITLE
使用fallback回落进行多域名https访问请问如何配置

### ISSUE THREAD

**Issue by kettly1260** [XTLS/Xray-core#529]
现在用的是fallback回落到nginx，使用的是一个泛域名
但是我同时还有其它域名需要布置，但是看教程只能通过SNI分流，且域名证书要SAN证书才行。请问有什么办法可以添加多个泛域名证书或者多个域名证书实现网页的正常访问

**Comment by lxhao61** [comment]
如下两种方法之一都可以实现你需求。
1、nginx SNI分流
2、fallbacks SNI shunt
参考https://github.com/lxhao61/integrated-examples

**Comment by kettly1260** [comment]
@lxhao61 请问fallback sni shunt是fallback之后加name进行分流吗？这个好像要san证书才可以反正不同顶级域名的网页吧？请问这个具体怎么配置呢
