### ISSUE TITLE
是否支持homebrew安装xray-core?

### ISSUE THREAD

**Issue by hyliang96** [XTLS/Xray-core#53]
希望能使用homebrew安装xray-core, 请问会提供这样的github repo以供brew cask install吗?

**Comment by rprx** [comment]
之前也有一位朋友询问此事，他表示要换个号打包，让我删除那个 issue，然后好像就没有下文了。。。

我这里没有相应的环境，还是需要找一位热心朋友来维护。

**Comment by KyonCN** [comment]
[https://github.com/N4FA/homebrew-xray](url)
@rprx @hyliang96

**Comment by rprx** [comment]
@N4FA 加油

**Comment by N4FA** [comment]
I have been on 996 work schedule this month.
I will finish the repo in this week.

**Comment by N4FA** [comment]
@rprx  the repo is ready for macos users 
https://github.com/N4FA/homebrew-xray
I am sorry, other work delayed the repo.

**Comment by rprx** [comment]
@N4FA

感谢你的工作，还请帮忙给 [homebrew-core](https://github.com/Homebrew/homebrew-core) 提交 PR

我们同时在计划推出独立的 geoip & geosite 库，到时需要更新一下它们的来源

**Comment by N4FA** [comment]
OK

**Comment by rprx** [comment]
README.md 已添加 Homebrew https://github.com/XTLS/Xray-core/commit/09f9d03fb62a17253826bf17c36b5e7eddc12141

@N4FA 你仓库的 README 有一处忘了改

**Comment by rprx** [comment]
@N4FA 其实我指的是 Uninstall 那里（差点理解成另外的意思，哈哈），以及刚刚发现 defualt config file location 也需要改

**Comment by N4FA** [comment]
🎄🎄🎄

**Comment by rprx** [comment]
@N4FA 圣诞快乐！刚看到还有一个 typo：defualt（上面直接 copy 的，也跟着写错了）
