### ISSUE TITLE
关于CDN加速，XRay是应该开启缓存 还是应该bypass？

### ISSUE THREAD

**Issue by jayvzh** [XTLS/Xray-core#536]
我用的国外服务器，xray+xtls-rprx-direct ,然后套了国内的CDN，
之前v2ray+ws+tls我是设置的转发路径/xxx/*都bypass，不缓存的，

我以为CDN只是为了解决国内访问慢，作为一个中转通道的作用，因为随时访问的东西都不一样，所以不应该缓存，
我这样理解对吗？

然后现在xray+xtls来套CDN的话，因为没有路径转发，是不是应该设置/*全局bypass?

CDN在bypass的情况下是会抓取实时源站数据，还是让client直接访问源站? bypass状态有没有中转通道加速效果？

**Comment by kxjhcmc** [comment]
xtls不支持cdn吧？

**Comment by jayvzh** [comment]
为什么不支持？ CDN原理上不是CDN服务器访问443端口 然后获得数据吗？
我已经试了，开始能用一会，后来断了，现在还没排查出是什么问题，
所以想看看是不是缓存的事
xtls不支持ws我知道，也不兼容cdn吗？
