### ISSUE TITLE
feedback error

### ISSUE THREAD

**Issue by jkle112** [XTLS/Xray-core#540]
Finding targets
go: github.com/xtls/xray-core@v1.4.2: Get "https://goproxy.io/github.com/xtls/xray-core/@v/v1.4.2.mod": x509: certificate signed by unknown authority

Building targets
go: github.com/xtls/xray-core@v1.4.2: Get "https://goproxy.io/github.com/xtls/xray-core/@v/v1.4.2.mod": x509: certificate signed by unknown authority

![Screenshot from 2021-04-25 18-32-06](https://user-images.githubusercontent.com/17021524/115991085-54053800-a5f9-11eb-96b4-f87151330140.png)

**Comment by hmol233** [comment]
> x509: certificate signed by unknown authority

是 https://goproxy.io 的问题。
