### ISSUE TITLE
请大神指教-xray 状态: 错误-failed to listen TCP on 38691-但防火墙跟宝塔中端口都放行了。

### ISSUE THREAD

**Issue by dadatan** [XTLS/Xray-core#542]
安装环境：腾讯云轻量服务器，已用宝塔搭建了3个网站，具体软件如下
![image](https://user-images.githubusercontent.com/83439725/116644787-e49b9980-a9a6-11eb-947d-3e8fc1c6497f.png)
。
Xray错误信息如下(已隐去IP)：
Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 linux/amd64)

A unified platform for anti-censorship.

2021/04/30 11:22:25 [Info] infra/conf/serial: Reading config: /usr/local/v2-ui/bin/config.json

Failed to start: app/proxyman/inbound: failed to listen TCP on 38691 > transport/internet: failed to listen on address: xx.xx.xx.xx:38691 > transport/internet/tcp: failed to listen TCP on xx.xx.xx.xx:38691 > listen tcp xx.xx.xx.xx:38691: bind: cannot assign requested address

**Comment by xqzr** [comment]
删除 `/usr/local/v2-ui/bin/config.json` 里 `入口` 的 `"listen": "xx.xx.xx.xx"`

**Comment by dadatan** [comment]
搞定了，谢谢大神！！

**Comment by zhonglouisweiwei** [comment]
Xray 1.4.5 (Xray, Penetrates Everything.) Custom (go1.17.1 linux/amd64)

A unified platform for anti-censorship.

2021/10/10 02:43:39 [Info] infra/conf/serial: Reading config: bin/config.json

Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: invalid VMess user > json: cannot unmarshal number -1 into Go struct field VMessAccount.alterId of type uint16

那位大哥知道，我这个报错啥情况。。

**Comment by aguero119** [comment]
http: TLS handshake error from x.x.x.x:5: read tcp 10.0.0.39:x->x.x.x.x:5: use of closed network connection
请问怎么解决?

**Comment by aguero119** [comment]
@xqzr
