### ISSUE TITLE
似乎连接udp 通过vmess协议时，cpu占用特别高

### ISSUE THREAD

**Issue by fishg** [XTLS/Xray-core#543]
似乎连接udp 通过vmess协议时，cpu占用特别高，游戏带10M带宽，2千两个连接时，服务端的cpu比tcp高的多，几乎单核占满。但不知道有什么debug方法可以热分析？

**Comment by Smallthing** [comment]
UDP本来就是cpu占用高

**Comment by AkinoKaede** [comment]
应该是正常现象
