### ISSUE TITLE
fakedns bug?

### ISSUE THREAD

**Issue by delphinuz** [XTLS/Xray-core#547]
使用一段时间后，会出现连线到 127.0.0.1:443。

切换到非fakedns设定，再切换回有fakedns后才会正常。

**Comment by rurirei** [comment]
?

**Comment by delphinuz** [comment]
抱歉忘了留log，如下：

```
tcp:127.0.0.1:21958 accepted tcp:127.0.0.1:443 [socks5-in -> direct] 
tcp:127.0.0.1:21960 accepted tcp:127.0.0.1:443 [socks5-in -> direct] 
tcp:127.0.0.1:21965 accepted tcp:127.0.0.1:443 [socks5-in -> direct] 
tcp:127.0.0.1:21966 accepted tcp:127.0.0.1:443 [socks5-in -> direct] 
```

使用fakedns大约数天后(pool满了？)，就会发生无法连线问题。看一下log，会一直出现类似以上的讯息，就是xray不停地连线到本地port 443(按理应是远端port 443?)。

不常出现，使用fakedns有2周以上吧，大约出现3~4次，多是使用一段时间后(数天)。

解决方式，就是再切换回没有fakedns的设定，使用几分钟后再切回有fakedns设定，如此就不会再出现连线到本地port 443的问题。

**Comment by rurirei** [comment]
need more.

**Comment by delphinuz** [comment]
![1620310750118](https://user-images.githubusercontent.com/615043/117314527-6e70c880-aeb9-11eb-816f-700aaa2c7656.jpg)

刚刚又发生了，截图如上。

**Comment by Ciacconas** [comment]
没见过, 出现这种之后, 正常使用受影响吗

**Comment by hmol233** [comment]
请提供下列信息：
- 配置文件
- 包含 [DNS查询日志](https://xtls.github.io/Xray-docs-next/config/log.html#logobject) 的 **Error** 日志

**Comment by yuhan6665** [comment]
也许跟 pool 满了有关系，现在的默认 ip 池只比映射池大1，而 fakedns 需要从 ip 池中找到未使用的一个，也就是说映射满了之后平均需要循环 3 万次才能找到那个未被使用的 ip。。
@delphinuz 你能试一下把池减小 10 倍，也就是 6000 左右，看还有没有问题？

**Comment by delphinuz** [comment]
> 没见过, 出现这种之后, 正常使用受影响吗
以前会，因为突然无法正常连线，看一下xray log才知道有这样问题。
至昨天比较特别，一开启xay就出现，但可正常连线。

> 请提供下列信息： 
> * 配置文件
> * 包含 [DNS查询日志](https://xtls.github.io/Xray-docs-next/config/log.html#logobject) 的 **Error** 日志
好的，等错误的dnslog出现后，一起放上来。

> 也许跟 pool 满了有关系，现在的默认 ip 池只比映射池大1，而 fakedns 需要从 ip 池中找到未使用的一个，也就是说映射满了之后平均需要循环 3 万次才能找到那个未被使用的 ip。。
> @delphinuz 你能试一下把池减小 10 倍，也就是 6000 左右，看还有没有问题？
以前也是这样想，因为多半都是使用3~5天以上，才会出现这问题。常时我也是猜想是pool满了。不过昨天是第一次启动就出现，所以就不知是否如此。但我先缩小试试。

**Comment by hmol233** [comment]
@delphinuz 

抱歉，DNS查询日志位于 **Access** 日志中。

另：如果方便的话，请提供一下配置文件中的 DNS 相关内容。

**Comment by delphinuz** [comment]
终于找到bug发生规律。

win10下使用第三方的应用，其可选择http或socks5。使用http时很正常，出现正常网域(domain.com:443)连线，但使用socks5时，却是连线到 127.0.0.1:443, 如下图

![2](https://user-images.githubusercontent.com/615043/120106911-79a1d600-c191-11eb-9672-8950b1be7f15.jpg)

目前fakedns的相关设定如下，其中进站的http(1081)与socks5(1080)除了port不同，其于都一样，不知为何最后一个是正常网域可连线，一个郤是127.0.0.1无法连线。

```
   "dns": {
        "queryStrategy": "UseIPv4",
        "servers": [
            {
                "address": "fakedns",
                "domains": [
                    "geosite:geolocation-!cn"
                ]
            },
            {
                "address": "https+local://223.5.5.5/dns-query",
                "domains": [
                    "geosite:cn"
                ],
                "expectIPs": [
                    "geoip:cn"
                ]
            },
            "https+local://1.1.1.1/dns-query",
            "8.8.4.4"
        ],
        "tag": "dns-server"
    },
```

inbounds
```

   "inbounds": [
        {
            "listen": "0.0.0.0",
            "port": 1080,
            "protocol": "socks",
            "settings": {
                "auth": "noauth",
                "udp": true
            },
            "sniffing": {
                "destOverride": [
                    "fakedns"
                ],
                "enabled": true,
                "metadataOnly": true
            },
            "tag": "socks5-in"
        },
        {
            "listen": "0.0.0.0",
            "port": 1081,
            "protocol": "http",
            "sniffing": {
                "destOverride": [
                    "fakedns"
                ],
                "enabled": true,
                "metadataOnly": true
            },
            "tag": "http-in"
        },
        {
            "listen": "0.0.0.0",
            "port": 53,
            "protocol": "dokodemo-door",
            "settings": {
                "address": "1.1.1.1",
                "network": "tcp,udp",
                "port": 53
            },
            "tag": "dns-in"
        }
    ],
```
outbounds
```
      {
            "protocol": "freedom",
            "settings": {
                "domainStrategy": "UseIP"
            },
            "tag": "direct"
        },
        {
            "protocol": "dns",
            "tag": "dns-out"
        },
```
routing

```
  "routing": {
        "domainStrategy": "IPIfNonMatch",
         {
                "inboundTag": [
                    "dns-in"
                ],
                "outboundTag": "dns-out",
                "type": "field"
            },
      {
                "ip": [
                    "1.1.1.1"
                ],
                "network": "tcp,udp",
                "outboundTag": "proxy",
                "type": "field"
            },
}
```

**Comment by ilpl** [comment]
我也遇到了, fakedns 在路由器长时间使用会有可能链接失败(部分网站单个子域名),排除是协议的问题,我试过出口ss/grpc/socks 都会遇到. 重启xray后正常.dns 查询到的是 fakedns的ip 但就是无法链接. curl 192.18.x.x(失败的子域名) 超时, 其他fakedns ip正常.
