### ISSUE TITLE
反向代理功能能否关闭mux？

### ISSUE THREAD

**Issue by paul13579** [XTLS/Xray-core#551]
反向代理功能能否关闭mux？
我现在需要把内网服务映射出去，由于需要映射的服务是HTTPS，为了提高性能，使用了VLESS+XTLS配合反向代理
XTLS应该是不支持MUX的，但是服务端客户端还是使用了MUX，虽然可以正常使用，但是经常会出现以下错误
common/mux: failed to fetch all input > io: read/write on closed pipe
common/mux: failed to write to downstream. closing session 169 > io: read/write on closed pip
如果换成TROJAN+XTLS，则会报错，协议验证不通过，关闭反向代理功能后正常
已经在outbounds设置关闭mux，但从日志中看到依然会使用mux

**Comment by hmol233** [comment]
TLDR 不能。

反向代理是使用 mux.cool 实现的，不能关闭 mux

**Comment by QGB** [comment]
```

2023/02/23 16:39:49 [Info] common/mux: failed to write to downstream. closing session 6 > io: read/write on closed pipe
```

**Comment by WhaleFell** [comment]
reality 使用反向代理, 当网络变化中断一段时间时, 反向代理就失效了.
