### ISSUE TITLE
xray-Core在高网络负载下上网很卡，忍不了之后搭建了一个ssr之后就很好用

### ISSUE THREAD

**Issue by whp98** [XTLS/Xray-core#558]
我电脑跑网心云x86上传基本占满，使用v2rayN客户端上国内网站是正常的，但是一旦使用google还有youtube就很卡 ，我也不知道是客户端有问题还是咋的。
忍了几天受不了了，就直接搭建了一个ssr然后配合客户端使用起来丝滑流畅，不知道是哪里的问题，希望有人能解答一下我的疑惑

**Comment by whp98** [comment]
![L%W$YJ3AB$ WMH572K3MHM6](https://user-images.githubusercontent.com/32877126/117939442-a1dca880-b33a-11eb-8208-a210cfa0758c.png)
![ZX_QJT6WH0U3RJ8NMZJSSV](https://user-images.githubusercontent.com/32877126/117939686-e6684400-b33a-11eb-9408-65f7954b29ce.png)
![image](https://user-images.githubusercontent.com/32877126/117939818-0861c680-b33b-11eb-94a1-06ec99dfdb8b.png)

**Comment by MarksonHon** [comment]
你用的XTLS流控都不是Windows能用的，Emmmm

**Comment by whp98** [comment]
几种都试过也是不行的

**Comment by whp98** [comment]
低负载下能正常使用

**Comment by whp98** [comment]
![image](https://user-images.githubusercontent.com/32877126/117940611-d309a880-b33b-11eb-8020-ae491593fbf6.png)
日常4-5上传

**Comment by whp98** [comment]
移动百兆宽带也就30照mbps上传左右吧

**Comment by whp98** [comment]
当前我使用'分布式计算'的方式解决了，首先手机开启v2ray允许局域网连接，然后电脑v2rayN使用socks5链接手机. 让手机作为网络出口就行，这个想法源自于手机并没有网络卡顿的情况，只是电脑不行于是我就这样做了，感兴趣的可以试试，我的问题算是暂时解决了，但是实际上这个上网卡断的问题还是真实存在的。

**Comment by POWER-FUL** [comment]
@whp98 网友题的啥沙雕issues

**Comment by timi-owo** [comment]
你的临时解决方案应该叫`“移动设备中转”`更合适吧... `“分布式计算”`...wtf?

win 系统不能用 splice 流控，xray 服务端是自己搭建的吗？

如果同机器同线路 ssr 没有问题，建议检查下 xray 的配置文件，多看看文档。

网心云能跑多少带宽跟代理没有任何关系。😅
