### ISSUE TITLE
现在的XRAY 是不是不支持 这个架构？target-mips_24kc_musl/xray-core-1.4.2

### ISSUE THREAD

**Issue by loofeal** [XTLS/Xray-core#560]
求问大神 现在的xray 是不是不支持target-mips_24kc_musl/xray-core-1.4.2 这个架构？还是说未来会支持？

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/118088272-67861080-b3f9-11eb-90be-f86c250b0b24.png)
这些不能运行吗

**Comment by yichya** [comment]
https://github.com/yichya/openwrt-xray/releases/download/v1.4.2/openwrt-xray_1.4.2-1_mips_24kc.ipk

没有带 cgo，直接装就行了

**Comment by loofeal** [comment]
> https://github.com/yichya/openwrt-xray/releases/download/v1.4.2/openwrt-xray_1.4.2-1_mips_24kc.ipk
> 
> 没有带 cgo，直接装就行了

谢谢 我试试看

**Comment by loofeal** [comment]
> https://github.com/yichya/openwrt-xray/releases/download/v1.4.2/openwrt-xray_1.4.2-1_mips_24kc.ipk
> 
> 没有带 cgo，直接装就行了

非常感谢你的帮助，我已经通过opkg 把你推荐给我的文件装入系统了，最后再次表达我的谢意。
