### ISSUE TITLE
[Bug] `buffer.UDP` 可能为 FakeIP

### ISSUE THREAD

**Issue by hmol233** [XTLS/Xray-core#563]
感谢群友 @getPanda 

例如 `Socks` 的实现：
https://github.com/XTLS/Xray-core/blob/1e3d739a5bcdccc1d27fa2b5c52bd64d9c995a1b/proxy/socks/protocol.go#L376

此处的 `buffer.UDP` 有可能为 FakeIP，并且不能被 sniffer override。

https://github.com/XTLS/Xray-core/blob/1e3d739a5bcdccc1d27fa2b5c52bd64d9c995a1b/proxy/socks/protocol.go#L394-L398
导致 FakeIP 作为 Destination 被发出。

**Comment by rprx** [comment]
该问题存在，sniffer 没处理 Xray-core 的 UDP

**Comment by rprx** [comment]
该问题存在，sniffer 没处理 Xray-core 的 buffer.UDP

**Comment by 5page** [comment]
如果这个bug解决了，那fakedns这个功能就完美了

**Comment by yuhan6665** [comment]
有人知道 fakedns 这个问题如何复现吗？或者能复现的能帮忙测试吗？我可以尝试修一下

**Comment by hmol233** [comment]
@yuhan6665 打开 FakeDNS 即可复现

**Comment by 5page** [comment]
> 有人知道 fakedns 这个问题如何复现吗？或者能复现的能帮忙测试吗？我可以尝试修一下

我当时情况是这样的。tproxy的透明网关开启fakedns，tcp上网都正常。这时候手机端开启wirguard代理，endpoint如果填ip，就没问题，如果填域名，那么wireguard就不通。

**Comment by yuhan6665** [comment]
@hmol233 @5page 由于我测不出问题，你们能帮忙测一下 https://github.com/XTLS/Xray-core/actions/runs/953330382
客户端和服务端都换一下

**Comment by ilpl** [comment]
> @hmol233 @5page 由于我测不出问题，你们能帮忙测一下 https://github.com/XTLS/Xray-core/actions/runs/953330382
> 客户端和服务端都换一下

貌似不行. 我用sstap 启动后 NatTypeTester 测试stun,udp 不通.

**Comment by 5page** [comment]
> @hmol233 @5page 由于我测不出问题，你们能帮忙测一下 https://github.com/XTLS/Xray-core/actions/runs/953330382
> 客户端和服务端都换一下

我测了一下，还是虚拟机开 tproxy 透明网关，开 fakedns ，同网段 wifi 下 android 客户端。udp 测试用 wireguard app, endpoint 填域名。

经测试，wireguard可以握手成功，而且可以上网。 error.log里也会不停地刷(应该也是正常的？):

```
2021/06/21 07:17:54 [Info] [2501355926] app/proxyman/inbound: sniffed domain for XUDP: xxxx.com
2021/06/21 07:17:54 [Info] [2669558999] app/dispatcher: fake dns got domain: xxxxx.com for ip: 198.18.134.116
```

但是有个网络稳定性特别差， xlts 80M带宽套了wireguard有时候只有几百K的测速结果。我试图在测试不同的情况时清空 android dns cache 但还是测下来网络很不稳定，毕竟是 wireguard 被套在 xtls 里，但很难说出网络稳定性差是什么原因。 

总之fakedns 对udp domain 是可以了，但是性能差问题的原因还未知。

**Comment by yuhan6665** [comment]
It should be fixed in 1.5.5
