### ISSUE TITLE
[feature] Multiple users at same port 

### ISSUE THREAD

**Issue by tshipenchko** [XTLS/Xray-core#569]
**Describe the features you want**
We want to use the same port for many users, separate by UUID

**Why do you need it**
In my country, only HTTPS are allowed. In addition, it is often necessary for different users to use different addresses for spoofing that change periodically, so you need to separate users by UUID.

**Comment by malikshi** [comment]
It's thier features! I'm using vmess port 443 with many clients/users

**Comment by AkinoKaede** [comment]
Already supported in VMess, VLESS, Trojan and Shadowsocks
