### ISSUE TITLE
请问grpc编码是protobuf还是flatbuffers

### ISSUE THREAD

**Issue by xqdoo00o** [XTLS/Xray-core#574]

**Comment by hmol233** [comment]
protobuf

**Comment by xqdoo00o** [comment]
> protobuf

只序列化bytes，是否没必要protobuf编码，感觉可以直接发raw bytes?
https://github.com/XTLS/Xray-core/blob/1e3d739a5bcdccc1d27fa2b5c52bd64d9c995a1b/transport/internet/grpc/encoding/stream.proto#L6-L8
protobuf应该不是零拷贝吧，估计也是cpu占用高的原因之一。



搜到一个grpc的自定义Codec [stackoverflow](https://stackoverflow.com/questions/60497813/how-to-pass-a-proto-binary-directly-in-a-grpc-call)

**Comment by hmol233** [comment]
是的。但是有一些问题：

- gRPC 也需要在头部添加 `No Compression Flag` 和 `Data Length`，会进行内存拷贝。
- 将 gRPC payload 打包为 HTTP/2 Frame 时可能也存在内存拷贝。
- 由于`[]byte` 复用，此处必须进行拷贝。

曾经实现过 [guna](https://github.com/Qv2ray/gun-lite/discussions/6)，但是由于其他内存拷贝的存在，并没有对性能产生没有显著影响。

这个想法更适合 [gun-lite](https://github.com/Qv2ray/gun-lite) 等，使用 HTTP 库模拟 gRPC 的场景。

> 估计也是cpu占用高的原因之一。

与 gRPC 的多路复用和其他机制有关。

**Comment by xqdoo00o** [comment]
> 曾经实现过 [guna](https://github.com/Qv2ray/gun-lite/discussions/6)，但是由于其他内存拷贝的存在，并没有对性能产生没有显著影响。

嗯，好的
