### ISSUE TITLE
1.4.2 回落bug 

### ISSUE THREAD

**Issue by architecturers** [XTLS/Xray-core#576]
入站的传输层用tcp，回落的传输层也是tcp的话，服务器端出错
此bug在服务器端 systemctl status xray.service 状态是 fail。
服务器端的配置（突出重点版 完整版配置正确 在v2ray 可正常运行 ）

`

{
    "inbounds": [
        {
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [],
                "decryption": "none",
                
                "fallbacks": [
                    {
                        "dest": 1231
                    },
                    {
                        "alpn": "h2",
                        "dest": 1232
                    },
                    {
                        "path": "/tcp",
                        "dest": 1234
                    }
                ]
            },
            
            "streamSettings": {
                "network": "tcp"
            }
        },
        
        {
            "listen": "127.0.0.1",
            "port": 1234,
            "protocol": "",
            "settings":{},
            
            "streamSettings": {
                "network": "tcp",
                "security": "none"
            }
        }
    ],
    
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ]
}

`

**Comment by hmol233** [comment]
> "protocol": ""
