### ISSUE TITLE
Unix Domian Socket   bind: address already in use

### ISSUE THREAD

**Issue by bigbighill** [XTLS/Xray-core#577]
服务器Debian 11 ，Docker 

docker-compose.yml:

> version: '3'

services:

  xray:
    image: teddysun/xray:latest
    container_name: xray
    restart: always
    volumes:
      - ./xraysock:/var/run
      - ./ssl:/ssl
      - ./xray-config:/etc/xray
      - ./xray-log:/var/log/xray
    ports:
      - "443:443"
    depends_on:
      - caddy
  
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./wwwroot:/usr/src
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./ssl:/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/  # caddy 2
      - ./caddy-config:/config

config.json:
 
> {
	"log": {
                "access": "/var/log/xray/access.log",
                "error": "/var/log/xray/error.log",
		"loglevel": "warning"
	},
	"inbounds": [
		{
			"port": 443,
			"protocol": "vless",
			"settings": {
				"clients": [
					{
						"id": "xxxxxx",
						"flow": "xtls-rprx-direct",
						"level": 0,
						"email": "love@example.com"
					}
				],
				"decryption": "none",
				"fallbacks": [
					{
						"dest": 1310,
						"xver": 1
					},
					{
						"path": "/aaa",
						"dest": 3456,
						"xver": 1
					},
					{
						"path": "/bbb",
						"dest": 5678,
						"xver": 1
					}
				]
			},
			"streamSettings": {
				"network": "tcp",
				"security": "xtls",
				"xtlsSettings": {
					"alpn": [
						"http/1.1"
					],
					"certificates": [
						{
							"certificateFile": "/ssl/ddd.tk/ddd.tk.crt",
							"keyFile": "/ssl/ddd.tk/ddd.tk.key"
						}
					]
				}
			}
		},
		{
			"port": 5678,
			"listen": "127.0.0.1",
			"protocol": "dokodemo-door",
			"tag": "wsdoko",
			"settings": {
				"address": "v1.mux.cool",
				"followRedirect": false,
				"network": "tcp"
			},
			"streamSettings": {
				"network": "ws",
				"wsSettings": {
					"acceptProxyProtocol": true,
					"path": "/bbb"
				}
			}
		},
		{
			"port": 9015,
			"protocol": "shadowsocks",
			"settings": {
				"clients": [
					{
						"password": "password",
						"method": "chacha20-ietf-poly1305",
						"network": "tcp,udp"
					}
				]
			},
			"streamSettings": {
				"network": "domainsocket"
			}
		},
		{
			"port": 1310,
			"listen": "127.0.0.1",
			"protocol": "trojan",
			"settings": {
				"clients": [
					{
						"password": "pass",
						"level": 0,
						"email": "love@example.com"
					},
					{
						"password": "pass",
						"level": 0,
						"email": "love1@example.com"
					}
				],
				"fallbacks": [
					{
						"dest": "127.0.0.1:80"
					}
				]
			},
			"streamSettings": {
				"network": "tcp",
				"security": "none",
				"tcpSettings": {
					"acceptProxyProtocol": true
				}
			}
		},
		{
			"port": 3456,
			"listen": "127.0.0.1",
			"protocol": "vmess",
			"settings": {
				"clients": [
					{
						"id": "xxxxxx",
						"level": 0,
						"alterId": 15,
						"email": "love@example.com"
					}
				]
			},
			"streamSettings": {
				"network": "ws",
				"security": "none",
				"wsSettings": {
					"acceptProxyProtocol": true,
					"path": "/aaa"
				}
			}
		}
	],
	"outbounds": [
		{
			"protocol": "freedom"
		},
		{
			"protocol": "blackhole",
			"settings": {},
			"tag": "blocked"
		},
		{
			"protocol": "freedom",
			"settings": {},
			"tag": "direct"
		},
		{
			"protocol": "freedom",
			"tag": "ssmux",
			"streamSettings": {
				"network": "domainsocket"
			}
		}
	],
	"routing": {
		"domainStrategy": "IPOnDemand",
		"rules": [
			{
				"type": "field",
				"inboundTag": [
					"wsdoko"
				],
				"outboundTag": "ssmux"
			},
			{
				"type": "field",
				"ip": [
					"0.0.0.0/8",
					"10.0.0.0/8",
					"100.64.0.0/10",
					"127.0.0.0/8",
					"169.254.0.0/16",
					"172.16.0.0/12",
					"192.0.0.0/24",
					"192.0.2.0/24",
					"192.168.0.0/16",
					"198.18.0.0/15",
					"198.51.100.0/24",
					"203.0.113.0/24",
					"::1/128",
					"fc00::/7",
					"fe80::/10"
				],
				"outboundTag": "blocked"
			},
			{
				"type": "field",
				"protocol": [
					"bittorrent"
				],
				"outboundTag": "blocked"
			}
		]
	},
	"transport": {
		"sockopt": {
			"tcpFastOpen": true
		},
		"dsSettings": {
			"path": "/var/run/ss-loop.sock"
		}
	}
}

ss+xray-plugin 不定期使用一段时间，xray就重启，服务端日志显示 ：

Xray 1.4.2 (Xray, Penetrates Everything.) Custom  ( go1.16.2 linux/amd64) A unified platform for anti-censorship.
20214/05/29 10.50.11 [Info] infra/conf/serial: Reading config: /etc/xray/config.json
Failed to start: app/proxyman/inbound: failed to listen TCP on 9015 > transport/internet: failed to listen on address: 0.0.0.0:9015 > transport/internet/domainsocket: failed to listen domian socket > listen unix /var/run/ss-loop.sock: bind: address already in use

![image](https://user-images.githubusercontent.com/26495337/120099963-de990400-c170-11eb-996b-aed738c51b14.png)

![image](https://user-images.githubusercontent.com/26495337/120100128-a1814180-c171-11eb-9403-4534f21389ce.png)

netstat nlp 也没有查到哪个进程占用9015端口，
删除 ss-loop.sock ss-loop.sock.lock ，docker restart xray 正常，但用一段时间故障复现，频率不高。
另个一台vps则同时的debian 10 、docker 则没有问题。

**Comment by xianren78** [comment]
你的处理方法就是对的，也只能这样。Xray为什么崩溃退出，需要贴日志出来。

**Comment by ruderal04o** [comment]
我是修改 xray.service.d文件夹里面的10-donot_touch_single_conf 里面添加删除这两个文件的命令解决的，可行，你也可以试一下。

**Comment by Clifftronix** [comment]
resolved
