### ISSUE TITLE
[Bug]当oneTimeLoading设置为true时，OCSP将失效

### ISSUE THREAD

**Issue by kirin10000** [XTLS/Xray-core#578]
如题，当配置如下时：
```json
                    "certificates": [
                        {
                            "certificateFile": "",
                            "keyFile": "",
                            "ocspStapling": 3600
                        }
                    ]
```
OCSP正常。
当配置如下时：
```json
                    "certificates": [
                        {
                            "certificateFile": "",
                            "keyFile": "",
                            "ocspStapling": 3600,
                            "oneTimeLoading": true
                        }
                    ]
```
OCSP没有开启。

且oneTimeLoading相关描述文档也有缺失

https://github.com/kirin10000/Xray-script/issues/53

**Comment by rurirei** [comment]
it's not a bug. https://github.com/XTLS/Xray-core/blob/1e3d739a5bcdccc1d27fa2b5c52bd64d9c995a1b/infra/conf/transport_internet.go#L303-L307

**Comment by kirin10000** [comment]
如果不是bug，那么相关文档描述缺失，需要补充。
目前文档中没有看到关于Onetimeloading的描述。
我是根据当时Biubiu的描述，结合字面意思，认为Onetimeloading与ocsp不冲突。而且现实中nginx也是一次性加载证书并开启ocsp

**Comment by BioniCosmos** [comment]
[PR](https://github.com/XTLS/Xray-core/pull/281) 里面有说明
