### ISSUE TITLE
最近经常出现这个错误

### ISSUE THREAD

**Issue by lsh1215225** [XTLS/Xray-core#579]
[Warning] [3176853963] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://work.lee27.gq/szwasd):  > read tcp 192.168.0.121:49780->132.226.236.122:443: i/o timeout transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://work.lee27.gq/szwasd):  > dial tcp: operation was canceled] > common/retry: all retry attempts failed

**Comment by hmol233** [comment]
> i/o timeout
