### ISSUE TITLE
21.02.0-rc2 不支持

### ISSUE THREAD

**Issue by wbxnewboy** [XTLS/Xray-core#582]
touch /home/openwrt/openwrt1/openwrt-21.02.0-rc2/build_dir/target-mipsel_24kc_musl/Xray-core-1.4.2/.configured_41d2667c412195535f2de588d2d090af
rm -f /home/openwrt/openwrt1/openwrt-21.02.0-rc2/build_dir/target-mipsel_24kc_musl/Xray-core-1.4.2/.built
touch /home/openwrt/openwrt1/openwrt-21.02.0-rc2/build_dir/target-mipsel_24kc_musl/Xray-core-1.4.2/.built_check
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/home/openwrt/openwrt1/openwrt-21.02.0-rc2/tmp/go-build" GO_MOD_CACHE_DIR="/home/openwrt/openwrt1/openwrt-21.02.0-rc2/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/xtls/xray-core" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/xtls/xray-core/main" GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/home/openwrt/openwrt1/openwrt-21.02.0-rc2/build_dir/target-mipsel_24kc_musl/Xray-core-1.4.2" GO_BUILD_DIR="/home/openwrt/openwrt1/openwrt-21.02.0-rc2/build_dir/target-mipsel_24kc_musl/Xray-core-1.4.2/.go_work/build" GO_BUILD_BIN_DIR="/home/openwrt/openwrt1/openwrt-21.02.0-rc2/build_dir/target-mipsel_24kc_musl/Xray-core-1.4.2/.go_work/build/bin/linux_mipsle" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/home/openwrt/openwrt1/openwrt-21.02.0-rc2/staging_dir/target-mipsel_24kc_musl/usr/share/gocode/src" GOOS="linux" GOARCH="mipsle" GO386="" GOARM="" GOMIPS="softfloat" GOMIPS64="" CGO_ENABLED=1 CC="mipsel-openwrt-linux-musl-gcc" CXX="mipsel-openwrt-linux-musl-g++" CGO_CFLAGS="-Os -pipe -mno-branch-likely -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -fmacro-prefix-map=/home/openwrt/openwrt1/openwrt-21.02.0-rc2/build_dir/target-mipsel_24kc_musl/Xray-core-1.4.2=Xray-core-1.4.2 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_CPPFLAGS="-I/home/openwrt/openwrt1/openwrt-21.02.0-rc2/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/usr/include -I/home/openwrt/openwrt1/openwrt-21.02.0-rc2/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/include/fortify -I/home/openwrt/openwrt1/openwrt-21.02.0-rc2/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/include" CGO_CXXFLAGS="-Os -pipe -mno-branch-likely -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -fmacro-prefix-map=/home/openwrt/openwrt1/openwrt-21.02.0-rc2/build_dir/target-mipsel_24kc_musl/Xray-core-1.4.2=Xray-core-1.4.2 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_LDFLAGS="-L/home/openwrt/openwrt1/openwrt-21.02.0-rc2/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/usr/lib -L/home/openwrt/openwrt1/openwrt-21.02.0-rc2/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib -znow -zrelro" GOPATH="/home/openwrt/openwrt1/openwrt-21.02.0-rc2/build_dir/target-mipsel_24kc_musl/Xray-core-1.4.2/.go_work/build" GOCACHE="/home/openwrt/openwrt1/openwrt-21.02.0-rc2/tmp/go-build" GOMODCACHE="/home/openwrt/openwrt1/openwrt-21.02.0-rc2/dl/go-mod-cache" GOENV=off /usr/bin/env bash /home/openwrt/openwrt1/openwrt-21.02.0-rc2/feeds/packages/lang/golang//golang-build.sh build -v -trimpath -ldflags "all=-buildid '1622210644' -linkmode external -extldflags '-L/home/openwrt/openwrt1/openwrt-21.02.0-rc2/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/usr/lib -L/home/openwrt/openwrt1/openwrt-21.02.0-rc2/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib -Wl,-z,now -Wl,-z,relro'"     -installsuffix "softfloat"   -ldflags "-s -w -X github.com/xtls/xray-core/core.build=OpenWrt -X github.com/xtls/xray-core/core.version=1.4.2 -buildid '1622210644' -linkmode external -extldflags '-L/home/openwrt/openwrt1/openwrt-21.02.0-rc2/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/usr/lib -L/home/openwrt/openwrt1/openwrt-21.02.0-rc2/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib -Wl,-z,now -Wl,-z,relro'"
Finding targets

Building targets

/home/openwrt/openwrt1/openwrt-21.02.0-rc2/staging_dir/host/bin/upx --lzma --best /home/openwrt/openwrt1/openwrt-21.02.0-rc2/build_dir/target-mipsel_24kc_musl/Xray-core-1.4.2/.go_work/build/bin/linux_mipsle/main
bash: /home/openwrt/openwrt1/openwrt-21.02.0-rc2/staging_dir/host/bin/upx: No such file or directory
Makefile:176: recipe for target '/home/openwrt/openwrt1/openwrt-21.02.0-rc2/build_dir/target-mipsel_24kc_musl/Xray-core-1.4.2/.built' failed
make[3]: *** [/home/openwrt/openwrt1/openwrt-21.02.0-rc2/build_dir/target-mipsel_24kc_musl/Xray-core-1.4.2/.built] Error 127
make[3]: Leaving directory '/home/openwrt/openwrt1/openwrt-21.02.0-rc2/package/openwrt-passwall/xray-core'
time: package/openwrt-passwall/xray-core/compile#4.64#1.57#6.46
    ERROR: package/openwrt-passwall/xray-core failed to build.
package/Makefile:112: recipe for target 'package/openwrt-passwall/xray-core/compile' failed
make[2]: *** [package/openwrt-passwall/xray-core/compile] Error 1
make[2]: Leaving directory '/home/openwrt/openwrt1/openwrt-21.02.0-rc2'
package/Makefile:108: recipe for target '/home/openwrt/openwrt1/openwrt-21.02.0-rc2/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/home/openwrt/openwrt1/openwrt-21.02.0-rc2/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/openwrt/openwrt1/openwrt-21.02.0-rc2'
/home/openwrt/openwrt1/openwrt-21.02.0-rc2/include/toplevel.mk:228: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by hmol233** [comment]
可能的原因：

> bash: /home/openwrt/openwrt1/openwrt-21.02.0-rc2/staging_dir/host/bin/upx: No such file or directory

另：这似乎并不是 xray 的问题，建议去 openwrt 咨询。
