### ISSUE TITLE
xray 能直連不能過cdn

### ISSUE THREAD

**Issue by vbuterin2** [XTLS/Xray-core#587]
2021/06/05 12:25:18 [Info] [36003780] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to decode response header > proxy/vless/encoding: failed to read response version > transport/internet/grpc/encoding: failed to fetch hunk from gRPC tunnel > rpc error: code = PermissionDenied desc = Forbidden: HTTP status code 403; transport: missing content-type field
2021/06/05 12:25:18 [Info] [36003780] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe

**Comment by zzx396** [comment]
首先你的CF要打开GRPC开关，其次只能选443端口。
