### ISSUE TITLE
关于回落nginx 后日志不显示xray转发的请求客户端的真实IP（显示为127.0.0.1)的问题

### ISSUE THREAD

**Issue by galaxyskyknight** [XTLS/Xray-core#591]
如题，xray 监听443，回落31300、31301(h2)，配置如下, xray 配置xver已配置为转发透明客户端IP（xver:1),  nginx端也配了proxy protocol. 目前xray代理和访问nginx反代的网站均OK,问题是我想跟踪xray回落后去访问nginx反代网站的客户端原始访问真实IP：通过在nginx日志里打印$http_x_forwarded_for|$http_x_real_ip|$remote_addr三个变量,发现只有$remote_addr有值为127.0.0.1，其他两个是空值，看上去是前端xray没有传下来（有点奇怪，我xver:1都配了）,请问要如何修改才能让xray吧原始访问443端口回落到31300、31301的客户端真实IP记录到Nginx log里？

//日志样例

**-|-|127.0.0.1** - - [07/Jun/2021:15:53:25 +0800] "POST /GARecord HTTP/2.0" 200 0 "https://www.yyy.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36" "-"

// xray部分配置
    "decryption": "none",
    "fallbacks": [
        {"dest":31300,"xver":1},
        {"alpn":"h2","dest":31301,"xver":1}
    ]
  },
  "streamSettings": {
    "network": "tcp",
    "security": "xtls",
    "xtlsSettings": {
      "minVersion": "1.2",
      "alpn": [
        "h2",
        "http/1.1"
      ],

//nginx 反代一个外部网站，部分配置如下：
http{
        log_format  main  '$http_x_forwarded_for|$http_x_real_ip|$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
        ......
       //吧access log定制为main描述的格式
       access_log /var/log/nginx/access.log main;
}
server {
    listen 80;
    limit_conn perip 2; 
    limit_rate 20k; 
    server_name xxx.com
    rewrite ^(.*)$ https://${server_name}$1 permanent;
}

server {

        listen 31300 proxy_protocol;
        listen 31301 proxy_protocol http2;
        limit_conn perip 2; 
        limit_rate 20k; 
        server_name xxx.com;
        ssl_certificate somewhere;
        ssl_certificate_key somewhere;

        rewrite ^/(.*) /$1;
        location / {
                proxy_set_header X-Forwarded-For $remote_addr;
                resolver 8.8.8.8 ipv6=off; //关掉ipv6访问
                #proxy_ssl_session_reuse off;
                proxy_pass https://www.yyyy.com;
        }
}

**Comment by ggggle** [comment]
set_real_ip_from 127.0.0.1;
real_ip_header proxy_protocol;

**Comment by galaxyskyknight** [comment]
感谢，看来还是我对nginx real ip module了解太少，搞定了！

**Comment by kr4lam** [comment]
不对啊，不是说XTLS不支持proxy_protocol吗？你确定你拿到了真实ip？我 proxy_protocol on; 了之后xray都不工作了。讲道理回落站拿到的tcp都没有header，怎么读出来的ip？
