### ISSUE TITLE
How to develop an iOS app with xray-core?

### ISSUE THREAD

**Issue by RyoHina** [XTLS/Xray-core#592]
.

**Comment by lgfyxx1** [comment]
You should learn HOW TO DEVELOP IOS APP first.

**Comment by RyoHina** [comment]
> You should learn HOW TO DEVELOP IOS APP first.

不懂就别瞎回，没人逼你好吗？

**Comment by lgfyxx1** [comment]
Mad Noob lol,

**Comment by thebadgateway** [comment]
where to get the kernel for ios?

**Comment by RyoHina** [comment]
1

**Comment by thebadgateway** [comment]
> 1

Could you find? tell me where to get instructions?
