### ISSUE TITLE
1.42版本不支持geoip:!cn类型，希望下版本加入

### ISSUE THREAD

**Issue by kz-wind** [XTLS/Xray-core#594]
报错如下
 Failed to start: main: failed to load config files: [/usr/local/etc/xray/config.json] > infra/conf: failed to parse DNS config > infra/conf: failed to build nameserver > infra/conf: invalid IP rule: [geoip:!cn] > infra/c

**Comment by Simonwe1** [comment]
可以routing中geoip:cn直连、others代理，效果等同

**Comment by kz-wind** [comment]
> 可以routing中geoip:cn直连、others代理，效果等同

我是在dns里中expectIPs模块使用

**Comment by kz-wind** [comment]
直接使用了Loyalsoldier/v2ray-rules-dat里的配置
"dns": {
  "hosts": {
    "dns.google": "8.8.8.8",
    "dns.pub": "119.29.29.29",
    "dns.alidns.com": "223.5.5.5",
    "geosite:category-ads-all": "127.0.0.1"
  },
  "servers": [
    {
      "address": "https://1.1.1.1/dns-query",
      "domains": ["geosite:geolocation-!cn"],
      "expectIPs": ["geoip:!cn"]
    },
    "8.8.8.8",
    {
      "address": "114.114.114.114",
      "port": 53,
      "domains": ["geosite:cn", "geosite:category-games@cn"],
      "expectIPs": ["geoip:cn"],
      "skipFallback": true
    },
    {
      "address": "localhost",
      "skipFallback": true
    }
  ]
}

**Comment by hmol233** [comment]
已经在 #443 完成。
