### ISSUE TITLE
do Not hardcode version name

### ISSUE THREAD

**Issue by rurirei** [XTLS/Xray-core#6]
thanks for your contributions in advanced.

could you do NOT hardcode versionName `v1` at packageName `github.com/xtls/xray-core/v1` as changed to `github.com/xtls/xray-core` as we could be easy to move for possible version/repo v2.

```golang
// now
import "github.com/xtls/xray-core/v1/core"

// instead
import "github.com/xtls/xray-core/core"
```

**Comment by rprx** [comment]
群里也有人提到了这个问题（是你吗？），我需要进一步研究

**Comment by rurirei** [comment]
no i don't know that is.

you can simply do a new branch `v2`

**Comment by rprx** [comment]
这个模块名是否会导致奇怪的问题（比如导入？

**Comment by rurirei** [comment]
it affects mod path ("v1") and not standard named obviously

**Comment by rurirei** [comment]
https://github.com/2dust/AndroidLibXrayLite/issues/1#issuecomment-734189816

**Comment by rurirei** [comment]
> 群里也有人提到了这个问题（是你吗？），我需要进一步研究

in the group?

**Comment by rurirei** [comment]
wait for changed.

**Comment by rprx** [comment]
@rurirei 

我在研究 XTLS 的 Splice 机会优化，请问安卓客户端和 Socks 入站间是 TCP 连接吗？（以及 NG 的情况？

**Comment by rurirei** [comment]
@rprx i did learn less on shadowsocks/badvpn v2rayNG used, i guess that should be on TCP connection.

**Comment by rurirei** [comment]
@rprx i do learn less on shadowsocks/badvpn v2rayNG used as i am not on known. i do comfirmed tun2socks i used is on TCP connections due
```go
    v2core.Dial(ctx, v.p, nil)
```

**Comment by rprx** [comment]
Xray-core v1.1.0+，已去除包名中的 `v1`。
