### ISSUE TITLE
xray在Openwrt PassWall中运行出错

### ISSUE THREAD

**Issue by zengli74** [XTLS/Xray-core#602]
Openwrt版本（自编译coolsnowwolf/lede，NanoPi R4S）：
root@OpenWrt:~# uname -a
Linux OpenWrt 5.4.124 #0 SMP PREEMPT Fri Jun 11 03:38:31 2021 aarch64 GNU/Linux

xray版本：
root@OpenWrt:~# xray --version
Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 linux/arm64)
A unified platform for anti-censorship.

配置xray之后发现passwall一直不能正常运行，跟踪了一下PassWall脚本，发现是执行命令：
/var/etc/passwall/bin/xray -config=/var/etc/passwall/TCP.json >/var/etc/passwall/TCP.log 2>&1 &

但是xray启动后很快就会退出，在TCP.out中有出错：
2021/06/14 19:22:24 mmap: cannot allocate memory

事实上，如果这时候在命令行直接执行：
/var/etc/passwall/bin/xray -config=/var/etc/passwall/TCP.json >/var/etc/passwall/TCP.log 2>&1 &

xray将会正常启动并正确运行，也就是说同样的命令在PassWall中调用就会出错，但手工执行就没有问题

**Comment by zengli74** [comment]
查看了下，Openwrt中的xray是同github网上下载的Xray-linux-arm64-v8a.zip是完全一致的

**Comment by hetaozhen** [comment]
几乎一样的问题，使用v2ray机场，分别重新编译了vssr passwall ssrp，这三个好像都是用xray的，tcp udp均无法启动运行，非得手动命令才能运行，换到ss节点完全正常。搞得我开始怀疑是机场在订阅配置里面弄了手脚。

**Comment by xiaorouji** [comment]
Please use uhttpd instead of nginx as the luci web server.

**Comment by hetaozhen** [comment]
有空编译一次，也怀疑过nginx，还没试到

**Comment by hetaozhen** [comment]
> Please use uhttpd instead of nginx as the luci web server.

It’s worked!

**Comment by acooler15** [comment]
https://github.com/fw876/helloworld/issues/586#issuecomment-881123393
使用nginx的，可以尝试修改`/etc/uwsgi/vassals/luci-webui.ini`文件的`limit-as`值，然后重启或者`/etc/init.d/uwsgi restart`

**Comment by hetaozhen** [comment]
> [fw876/helloworld#586 (comment)](https://github.com/fw876/helloworld/issues/586#issuecomment-881123393)
> 使用nginx的，可以尝试修改`/etc/uwsgi/vassals/luci-webui.ini`文件的`limit-as`值，然后重启或者`/etc/init.d/uwsgi restart`
uwsgi重启无法解决，limit-as值填多少呢？

**Comment by acooler15** [comment]
> > [fw876/helloworld#586 (comment)](https://github.com/fw876/helloworld/issues/586#issuecomment-881123393)
> > 使用nginx的，可以尝试修改`/etc/uwsgi/vassals/luci-webui.ini`文件的`limit-as`值，然后重启或者`/etc/init.d/uwsgi restart`
> > uwsgi重启无法解决，limit-as值填多少呢？

https://github.com/fw876/helloworld/issues/586#issuecomment-881123393
试试5000，只要大于xray的VSZ/VIRT的值就行

**Comment by smilesww** [comment]
> > > [fw876/helloworld#586 (comment)](https://github.com/fw876/helloworld/issues/586#issuecomment-881123393)
> > > 使用nginx的，可以尝试修改`/etc/uwsgi/vassals/luci-webui.ini`文件的`limit-as`值，然后重启或者`/etc/init.d/uwsgi restart`
> > > uwsgi重启无法解决，limit-as值填多少呢？
> 
> [fw876/helloworld#586 (comment)](https://github.com/fw876/helloworld/issues/586#issuecomment-881123393) 试试5000，只要大于xray的VSZ/VIRT的值就行

`/etc/uwsgi/vassals/luci-webui.ini`这个在哪找呢？大神 我小白找一下午没找到这个文件。putty里面没有。

**Comment by smilesww** [comment]
ssh也找不到。不知道是用哪个软件找的这个位置

**Comment by hetaozhen** [comment]
> 
上面不是写了路径吗？你是不是用nginx的？

**Comment by hetaozhen** [comment]
> > > > [fw876/helloworld#586 (comment)](https://github.com/fw876/helloworld/issues/586#issuecomment-881123393)
> > > > 使用nginx的，可以尝试修改`/etc/uwsgi/vassals/luci-webui.ini`文件的`limit-as`值，然后重启或者`/etc/init.d/uwsgi restart`
> > > > uwsgi重启无法解决，limit-as值填多少呢？
> > 
> > 
> > [fw876/helloworld#586 (comment)](https://github.com/fw876/helloworld/issues/586#issuecomment-881123393) 试试5000，只要大于xray的VSZ/VIRT的值就行
> 
> `/etc/uwsgi/vassals/luci-webui.ini`这个在哪找呢？大神 我小白找一下午没找到这个文件。putty里面没有。

上面不是写了路径吗？你是不是用nginx的？

**Comment by smilesww** [comment]
> > > > > [fw876/helloworld#586 (comment)](https://github.com/fw876/helloworld/issues/586#issuecomment-881123393)
> > > > > 使用nginx的，可以尝试修改`/etc/uwsgi/vassals/luci-webui.ini`文件的`limit-as`值，然后重启或者`/etc/init.d/uwsgi restart`
> > > > > uwsgi重启无法解决，limit-as值填多少呢？
> > > 
> > > 
> > > [fw876/helloworld#586 (comment)](https://github.com/fw876/helloworld/issues/586#issuecomment-881123393) 试试5000，只要大于xray的VSZ/VIRT的值就行
> > 
> > 
> > `/etc/uwsgi/vassals/luci-webui.ini`这个在哪找呢？大神 我小白找一下午没找到这个文件。putty里面没有。
> 
> 上面不是写了路径吗？你是不是用nginx的？

我用的是Finalshell 这个软件  连接上openwrt。然后只能看到/etc   下面的路径就找不到了。

**Comment by smilesww** [comment]
> > 
> 
> 上面不是写了路径吗？你是不是用nginx的？

不知道用的是哪个软件 ε=(´ο｀*)))唉

**Comment by acooler15** [comment]
> > > > > > [fw876/helloworld#586 (comment)](https://github.com/fw876/helloworld/issues/586#issuecomment-881123393)
> > > > > > 使用nginx的，可以尝试修改`/etc/uwsgi/vassals/luci-webui.ini`文件的`limit-as`值，然后重启或者`/etc/init.d/uwsgi restart`
> > > > > > uwsgi重启无法解决，limit-as值填多少呢？
> > > > 
> > > > 
> > > > [fw876/helloworld#586 (comment)](https://github.com/fw876/helloworld/issues/586#issuecomment-881123393) 试试5000，只要大于xray的VSZ/VIRT的值就行
> > > 
> > > 
> > > `/etc/uwsgi/vassals/luci-webui.ini`这个在哪找呢？大神 我小白找一下午没找到这个文件。putty里面没有。
> > 
> > 上面不是写了路径吗？你是不是用nginx的？
> 
> 我用的是Finalshell 这个软件  连接上openwrt。然后只能看到/etc   下面的路径就找不到了。

不可能呀，怎会只看到一层？

**Comment by hetaozhen** [comment]
> > 上面不是写了路径吗？你是不是用nginx的？
> 
> 不知道用的是哪个软件 ε=(´ο｀*)))唉

winscp

**Comment by acooler15** [comment]
> > > > > [fw876/helloworld#586 (comment)](https://github.com/fw876/helloworld/issues/586#issuecomment-881123393)
> > > > > 使用nginx的，可以尝试修改`/etc/uwsgi/vassals/luci-webui.ini`文件的`limit-as`值，然后重启或者`/etc/init.d/uwsgi restart`
> > > > > uwsgi重启无法解决，limit-as值填多少呢？
> > > 
> > > 
> > > [fw876/helloworld#586 (comment)](https://github.com/fw876/helloworld/issues/586#issuecomment-881123393) 试试5000，只要大于xray的VSZ/VIRT的值就行
> > 
> > `/etc/uwsgi/vassals/luci-webui.ini`这个在哪找呢？大神 我小白找一下午没找到这个文件。putty里面没有。
> 
> 上面不是写了路径吗？你是不是用nginx的？

shell下直接`vi /etc/uwsgi/vassals/luci-webui.ini`试试

**Comment by acooler15** [comment]
> > > > > > [fw876/helloworld#586 (comment)](https://github.com/fw876/helloworld/issues/586#issuecomment-881123393)
> > > > > > 使用nginx的，可以尝试修改`/etc/uwsgi/vassals/luci-webui.ini`文件的`limit-as`值，然后重启或者`/etc/init.d/uwsgi restart`
> > > > > > uwsgi重启无法解决，limit-as值填多少呢？
> > > > 
> > > > 
> > > > [fw876/helloworld#586 (comment)](https://github.com/fw876/helloworld/issues/586#issuecomment-881123393) 试试5000，只要大于xray的VSZ/VIRT的值就行
> > > 
> > > 
> > > `/etc/uwsgi/vassals/luci-webui.ini`这个在哪找呢？大神 我小白找一下午没找到这个文件。putty里面没有。
> > 
> > 上面不是写了路径吗？你是不是用nginx的？
> 
> 我用的是Finalshell 这个软件  连接上openwrt。然后只能看到/etc   下面的路径就找不到了。

shell下直接`vi /etc/uwsgi/vassals/luci-webui.ini`试试

**Comment by smilesww** [comment]
> 



> > > 上面不是写了路径吗？你是不是用nginx的？
> > 
> > 
> > 不知道用的是哪个软件 ε=(´ο｀*)))唉
> 
> winscp
这个软件也试了 没有找到。uwsgi这个没有。所以没办法往下了。

**Comment by acooler15** [comment]
> > 
> 
> 
> 
> > > > 上面不是写了路径吗？你是不是用nginx的？
> > > 
> > > 
> > > 不知道用的是哪个软件 ε=(´ο｀*)))唉
> > 
> > winscp
> 这个软件也试了 没有找到。uwsgi这个没有。所以没办法往下了。

那你应该用的不是nginx，能说下你的错误发生过程吗？这个方案只支持使用nginx的，且是在luci下启动失败，但在shell中直接运行可以成功的情况。

**Comment by smilesww** [comment]
> > > 
> > 
> > 
> > > > > 上面不是写了路径吗？你是不是用nginx的？
> > > > 
> > > > 
> > > > 不知道用的是哪个软件 ε=(´ο｀*)))唉
> > > 
> > > 
> > > winscp
> > > 这个软件也试了 没有找到。uwsgi这个没有。所以没办法往下了。
> 
> 那你应该用的不是nginx，能说下你的错误发生过程吗？这个方案只支持使用nginx的，且是在luci下启动失败，但在shell中直接运行可以成功的情况。

我的错误过程就是我用的N1软路由刷的openwrt。然后用passwall这个软件 用Xary节点的话  TCP和DUP都不启动，都是显示未运行 ，只有dns显示运行。。用其他的v2ray节点就没问题。所以查询到你们这个。但是不知如何修改

**Comment by acooler15** [comment]
> > > > 
> > > 
> > > 
> > > > > > 上面不是写了路径吗？你是不是用nginx的？
> > > > > 
> > > > > 
> > > > > 不知道用的是哪个软件 ε=(´ο｀*)))唉
> > > > 
> > > > 
> > > > winscp
> > > > 这个软件也试了 没有找到。uwsgi这个没有。所以没办法往下了。
> > 
> > 那你应该用的不是nginx，能说下你的错误发生过程吗？这个方案只支持使用nginx的，且是在luci下启动失败，但在shell中直接运行可以成功的情况。
> 
> 我的错误过程就是我用的N1软路由刷的openwrt。然后用passwall这个软件 用Xary节点的话  TCP和DUP都不启动，都是显示未运行 ，只有dns显示运行。。用其他的v2ray节点就没问题。所以查询到你们这个。但是不知如何修改

有没有试过在shell下直接启动xray?

**Comment by acooler15** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > > > > 上面不是写了路径吗？你是不是用nginx的？
> > > > > > > 
> > > > > > > 
> > > > > > > 不知道用的是哪个软件 ε=(´ο｀*)))唉
> > > > > > 
> > > > > > 
> > > > > > winscp
> > > > > > 这个软件也试了 没有找到。uwsgi这个没有。所以没办法往下了。
> > > > 
> > > > 
> > > > 那你应该用的不是nginx，能说下你的错误发生过程吗？这个方案只支持使用nginx的，且是在luci下启动失败，但在shell中直接运行可以成功的情况。
> > > 
> > > 
> > > 我的错误过程就是我用的N1软路由刷的openwrt。然后用passwall这个软件 用Xary节点的话  TCP和DUP都不启动，都是显示未运行 ，只有dns显示运行。。用其他的v2ray节点就没问题。所以查询到你们这个。但是不知如何修改
> > 
> > 有没有试过在shell下直接启动xray?
> 
> 我不会这样操作。

没办法确定问题，我也很难帮助你。

**Comment by smilesww** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > > > > 上面不是写了路径吗？你是不是用nginx的？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 不知道用的是哪个软件 ε=(´ο｀*)))唉
> > > > > > > 
> > > > > > > 
> > > > > > > winscp
> > > > > > > 这个软件也试了 没有找到。uwsgi这个没有。所以没办法往下了。
> > > > > 
> > > > > 
> > > > > 那你应该用的不是nginx，能说下你的错误发生过程吗？这个方案只支持使用nginx的，且是在luci下启动失败，但在shell中直接运行可以成功的情况。
> > > > 
> > > > 
> > > > 我的错误过程就是我用的N1软路由刷的openwrt。然后用passwall这个软件 用Xary节点的话  TCP和DUP都不启动，都是显示未运行 ，只有dns显示运行。。用其他的v2ray节点就没问题。所以查询到你们这个。但是不知如何修改
> > > 
> > > 
> > > 有没有试过在shell下直接启动xray?
> > 
> > 
> > 我不会这样操作。
> 
> 没办法确定问题，我也很难帮助你。

谢谢。我自己再摸索一下

**Comment by hamlinzheng** [comment]
> > > [fw876/helloworld#586 (comment)](https://github.com/fw876/helloworld/issues/586#issuecomment-881123393)
> > > 使用nginx的，可以尝试修改`/etc/uwsgi/vassals/luci-webui.ini`文件的`limit-as`值，然后重启或者`/etc/init.d/uwsgi restart`
> > > uwsgi重启无法解决，limit-as值填多少呢？
> 
> [fw876/helloworld#586 (comment)](https://github.com/fw876/helloworld/issues/586#issuecomment-881123393) 试试5000，只要大于xray的VSZ/VIRT的值就行

已解决，感谢~

**Comment by 4wrunner** [comment]
hamlinzheng 你好，请问怎么解决的，我碰到和你类似的问题，谢谢！
