### ISSUE TITLE
Issues related with security founded

### ISSUE THREAD

**Issue by Report-OSS-Security** [XTLS/Xray-core#607]
Dear XTLS.

We are Security Team at Samsung Research. We are interested in the security of open-source projects.
We'd like to inform you of security-related issues in your repository but we couldn't find a proper way to reach you.

Please follow the below steps.
1. Please send this repository url to report.oss.sec@gmail.com.
2. Leave a comment 'Confirmed' on this issue. The comment should be written by the repository owner.
3. Then we will send detailed information via your email.

If you have any questions, please let us know.

Best regards,
Security Team @ Samsung Research

**Comment by rprx** [comment]
> We, Samsung Security Team, 打钱

1. Project X 群群友一致认为这是钓鱼，槽点太多
2. 若非钓鱼，请提供 samsung.com 邮箱
3. https://github.com/Shinhyung-Choi/test/issues

**Comment by rprx** [comment]
看到你已经把 Shinhyung-Choi/test 删了，不过我发现了这个：https://shinhyungchoi.medium.com/
个人介绍是 Nexon（至少是韩国的），那么，若非钓鱼，请直接将详情发至 rprx@protonmail.com
