### ISSUE TITLE
[Bug] 重设`Dialer` 会导致 `DomainStrategy` 与 `DialerProxy` 失效

### ISSUE THREAD

**Issue by hmol233** [XTLS/Xray-core#608]
Thanks @nekohasekai, @AkinoKaede :

> AndroidLibXrayLite 会重设 Dialer，然后这个特性就炸了

**Comment by badO1a5A90** [comment]
@hmol233 所以 https://github.com/XTLS/Xray-core/pull/609 是可用的, 已经修复了这个问题对吗
