### ISSUE TITLE
通过vless协议回落nginx时无法使用http2以外的协议

### ISSUE THREAD

**Issue by LZYxiaobai** [XTLS/Xray-core#615]
因为环境比较复杂，服务端仍然是使用nginx的stream转发给xray再进行下一步处理，xray在这里起到的作用是让xray和正常网页使用同一个域名。
xray和nginx都配置好后，客户端xray可以正常连接使用，使用http2协议也可以正常获取到网页内容。但如果使用http1.1协议则无法获取网页。

xray配置

> {
 "outbound": {
  "streamSettings": null,
  "tag": null,
  "protocol": "freedom",
  "mux": null,
  "settings": null
 },
 "log": {
  "access": "/var/log/xray/vless_access.log",
  "loglevel": "info",
  "error": "/var/log/xray/vless_error.log"
 },
 "outboundDetour": [
  {
   "tag": "blocked",
   "protocol": "blackhole",
   "settings": null
  }
 ],
 "inbound": {
  "streamSettings": {
   "network": "tcp",
   "tcpSettings": {"acceptProxyProtocol": true},
   "xtlsSettings": {"preferServerCipherSuites": true,"enableSessionResumption":true,"certificates": [{"certificateFile": "cert.pem", "keyFile": "key.pem"}]},
   "security": "xtls"
  },
  "settings": {
   "ip": null,
   "udp": true,
   "decryption": "none",
   "fallbacks": [
        {
                "dest": 88,
                "xver": 1
        },
        {
                "path": "/vmesstls",
                "dest": 2456,
                "xver": 1
        }
   ],
   "clients": [
    {
     "flow": "xtls-rprx-direct",
     "id": "a-b-c-d-e-f"
    }
   ],
   "auth": null
  },
  "protocol": "vless",
  "port": 14235,
  "listen": null
 },
 "inboundDetour": null,
 "routing": {
  "settings": {
   "rules": [
    {
     "ip": [
      "0.0.0.0/8",
      "10.0.0.0/8",
      "100.64.0.0/10",
      "127.0.0.0/8",
      "169.254.0.0/16",
      "172.16.0.0/12",
      "192.0.0.0/24",
      "192.0.2.0/24",
      "192.168.0.0/16",
      "198.18.0.0/15",
      "198.51.100.0/24",
      "203.0.113.0/24",
      "::1/128",
      "fc00::/7",
      "fe80::/10"
     ],
     "domain": null,
     "type": "field",
     "port": null,
     "outboundTag": "blocked"
    }
   ],
   "domainStrategy": null
  },
  "strategy": "rules"
 },
 "dns": null
}

nginx 的一部分配置

> stream {
map $ssl_preread_server_name $name {
        a.com 127.0.0.1:14235;
        b.com 127.0.0.1:12345;
        c.com 127.0.0.1:55555;
        #default unix:/run/nginx-web.sock;
}
server {
                listen 443 reuseport so_keepalive=on;
                ssl_preread on;
                proxy_protocol on;
                proxy_pass $name;
        }
}
> server {
    listen 88 default_server http2 reuseport proxy_protocol;
    server_name a.com;
    add_header alt-svc 'h3-29=":443"; ma=86400, quic=":443"; ma=86400';
    gzip off;
    access_log /var/log/nginx/api_access.log pxpt;
    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';
    add_header Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
    location / {
                root /var/www/lua;
                index index.html;
        }
    include /var/www/api.conf;
}

以下是使用curl得到的结果(难以排版，还请见谅)

curl --http1.1 -v https://a.com
*   Trying xxx.xxx.xxx.xxx:443...
* Connected to a.com (xxx.xxx.xxx.xxx) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=*.a.com
*  start date: Jun 15 02:23:35 2021 GMT
*  expire date: Jul 17 02:23:35 2022 GMT
*  subjectAltName: host "a.com" matched cert's "*.a.com"
*  issuer: C=BE; O=GlobalSign nv-sa; CN=AlphaSSL CA - SHA256 - G2
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: a.com
> User-Agent: curl/7.74.0
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Received HTTP/0.9 when not allowed

* Closing connection 0
* TLSv1.3 (OUT), TLS alert, close notify (256):
curl: (1) Received HTTP/0.9 when not allowed

curl --http1.1 --http0.9 -v https://a.com
*   Trying xxx.xxx.xxx.xxx:443...
* Connected to a.com (xxx.xxx.xxx.xxx) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=*.a.com
*  start date: Jun 15 02:23:35 2021 GMT
*  expire date: Jul 17 02:23:35 2022 GMT
*  subjectAltName: host "a.com" matched cert's "*.a.com"
*  issuer: C=BE; O=GlobalSign nv-sa; CN=AlphaSSL CA - SHA256 - G2
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: a.com
> User-Agent: curl/7.74.0
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
* Failure writing output to destination
* Closing connection 0
* TLSv1.3 (OUT), TLS alert, close notify (256):

**Comment by 4piu** [comment]
I have the exact same problem, did you solve it?

**Comment by LZYxiaobai** [comment]
> I have the exact same problem, did you solve it?

Not really, I just used another map in nginx.conf to solve it by reading alpn protocol
Like this:
```
server {
	listen 443 reuseport so_keepalive=on;

	ssl_preread on;
	proxy_protocol on;

	proxy_pass $name;
}

map $ssl_preread_server_name $name {
	your.domain $xray;
	default __your_fallback_server__;
}

map $ssl_preread_alpn_protocols $xray {
        ~\bh2\b __your_xray_server__;
        default __your_fallback_server__;
}
```
