### ISSUE TITLE
ClubHouse Voice

### ISSUE THREAD

**Issue by libea18** [XTLS/Xray-core#617]
i test AnXray - sagernet - v2rayNG
in v2rayNG ( Xray-core ) and AnXray , clubhouse voice chat doesnt work ! 
clubhouse will be open but voices wont be play 
in sagernet is ok and work

i think Xray-core have some issue
could you help ?

**Comment by malikshi** [comment]
@libea18 i tested Discord VC work fine

**Comment by jiuqi9997** [comment]
@libea18 Test the NAT type when using SN and AX. Check if they are different.

**Comment by libea18** [comment]
@malikshi please test ClubHouse VC

**Comment by rprx** [comment]
你的服务端不是 Xray-core，或者和 XTLS 默认屏蔽了 UDP/443 有关（不过当前版本即使不屏蔽它，也不会进 XUDP）

---

当前版本的 XUDP 跳过了 UDP/443 和 UDP/53，下个版本 v1.5.0 不会跳过 UDP/443（因为会影响某些 BT 下载）

**Comment by jiuqi9997** [comment]
@rprx 他没在用XTLS

**Comment by rprx** [comment]
@jiuqi9997 我电脑的 telegram 暂时删了，不过我在看群，他的问题是服务端装的不是 Xray-core

**Comment by libea18** [comment]
@rprx thank you bro
solved
