### ISSUE TITLE
运行一段时间ut后udp报错

### ISSUE THREAD

**Issue by BGzErol** [XTLS/Xray-core#621]
在ut启用**UDP tracker支持**这个功能然后挂后台做种一段时间后udp会挂掉，NatTypeTester显示UdpBlocked。udp节点的日志节选如下：
2021/06/27 13:00:52 [Warning] [1976484283] app/proxyman/outbound: failed to process outbound traffic > proxy/trojan: failed to find an available destination > common/retry: [dial tcp: lookup xxxxxx.top on 127.0.0.1:53: dial udp 127.0.0.1:53: socket: too many open files] > common/retry: all retry attempts failed
2021/06/27 13:00:52 [Warning] [2726042615] app/proxyman/outbound: failed to process outbound traffic > proxy/trojan: failed to find an available destination > common/retry: [dial tcp: xxxxxx.top on 127.0.0.1:53: dial udp 127.0.0.1:53: socket: too many open files] > common/retry: all retry attempts failed
已经复现了两次了，出现这个问题的时候tcp代理是正常的。用的passwall，xray版本为1.4.2，协议用的trojan_xray
实测在ssrp上也有同样的问题，因此暂时排除passwall本身出bug。

**Comment by hmol233** [comment]
> socket: too many open files

尝试调大文件数限制？
