### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by wbxnewboy** [XTLS/Xray-core#626]
build github.com/xtls/xray-core/main: cannot load embed: malformed module path "embed": missing dot in first path element

Building targets
build .: cannot find module for path .

Cleaning module download cache (golang/go#27455)

Makefile:176: recipe for target '/home/openwrt/openwrt/openwrt/build_dir/target-mipsel_24kc_musl/Xray-core-1.4.2/.built' failed

**Comment by rprx** [comment]
Use Go 1.16+

**Comment by aaronchin** [comment]
使用 go version go1.16.5 linux/amd64
出现一样报错 build github.com/xtls/xray-core/main: cannot load embed: malformed module path "embed": missing dot in first path element
不过只有在编译 Allwinner A1x/A20/A3x 会出现这个状况
在編譯其他target都不會 目前測試过Allwinner H5 (aarch64) MT7621 IPQ40XX X86都正常
