### ISSUE TITLE
安卓APP更新

### ISSUE THREAD

**Issue by shuiliu11** [XTLS/Xray-core#628]
通过v2rayNG上网或者看YOUTUBE等都是正常的，但是打开GOOGLE商店更新APP，就没有速度，只能开VPN更新，请问怎么设置。

**Comment by MarksonHon** [comment]
你来错地方了，这里没有一个东西是叫做“游戏器”的。

**Comment by flower-elf** [comment]
> 
> 
> 通过游戏器上网或者看YOUTUBE等正常的，但是打开GOOGLE商店更新APP，就没有速度，只能开VPN更新，请问怎么设置。

请**不要**在不恰当的地方，提无关问题，这里**没有**叫做游戏器的东西

**Comment by wc7086** [comment]
您好，请问要预约哪个科室的医生。

**Comment by bigjunda** [comment]
建议预约小学语文老师重修

**Comment by imldy** [comment]
初步判断是分流(路由)问题，建议开全局试试。或者直接联系收你钱的人。

**Comment by shuiliu11** [comment]
> 初步判断是分流(路由)问题，建议开全局试试。或者直接联系收你钱的人。

应该是打完字我没有检查，已经改正过来了，但是v2rayNG没有全局，我用的xtls-rprx-direct这个选项，

**Comment by xianren78** [comment]
即使是v2rayNG，也不应该在这里提issue，右转去v2rayNG的issue区。

**Comment by shuiliu11** [comment]
> 即使是v2rayNG，也不应该在这里提issue，右转去v2rayNG的issue区。

这个软件是Project X作者推荐的，我是按照它的文章配置的，作者能推荐这个软件肯定是这个软件比较好，这个平台应该没有问题，我认为应该是某些设置错了，你没有那点水平回答就别捣乱，作者都没回我，难道你是作者？

**Comment by bigjunda** [comment]
这就是我小白我有理

**Comment by xianren78** [comment]
> 这就是我小白我有理

巨婴，想当然，我开车上路路就是我的，他还是个孩子。。。

**Comment by hmol233** [comment]
> 你也知道，那只是推荐，Project X作者推荐了不代表他一定会解决这个软件设置相关的问题
对应软件请在对应区域提issue
另外，请不要对他人无礼。
以上
