### ISSUE TITLE
Xray 1.1.3 Vless XTLS splice失效

### ISSUE THREAD

**Issue by smallprogram** [XTLS/Xray-core#63]
RT，1.1.2中客户端采用splice，服务端direct.服务端与客户端升级至1.1.3 同样的配置不变无法连接了。

**Comment by rprx** [comment]
客户端 Splice 对应服务端 Direct

**Comment by smallprogram** [comment]
> 客户端 Splice 对应服务端 Direct

我写错了，服务端是Direct

**Comment by badO1a5A90** [comment]
请附上相关的错误日志

**Comment by rprx** [comment]
请确认服务端正常运行，目测是没启动

**Comment by smallprogram** [comment]
经过一段时间的测试，并不是 Xray-core 1.1.3的问题。也非服务端和客户端配置问题。问题出自与路由器插件SSR+。感谢各位的回复。问题我先关了。
