### ISSUE TITLE
期望 vless 能和vmess一样支持动态端口

### ISSUE THREAD

**Issue by SturdyCat** [XTLS/Xray-core#630]
vless 单一端口容易被限流或封端口
vmess 动态端口模式工作正常
期望vless 能支持动态端口

**Comment by hahahrfool** [comment]
支持！把detour功能加回来就行

**Comment by xc1988** [comment]
最近封端口有点厉害

**Comment by LsnmxNB** [comment]
动态端口能还能B免443端口限速问题，广东地区基本TCP 443端口被限速

**Comment by LsnmxNB** [comment]
@hmol233  443端口限速是常态了，能不能提速支持一下vless的动态端口

**Comment by LsnmxNB** [comment]
@RPRX  支持下呗，443限流严重

**Comment by LsnmxNB** [comment]
顶起来

**Comment by LsnmxNB** [comment]
443端口限速利害，顶起来

**Comment by 362227** [comment]
端口被封严重

**Comment by LsnmxNB** [comment]
XTLS Vision/vless 是时候要支持动态端口了，现在动不动流量大点就封杀443端口

**Comment by redstoneleo** [comment]
都好几年了还是老样子，我也希望有动态端口
