### ISSUE TITLE
开cdn后，直连连不上，请问是什么原理

### ISSUE THREAD

**Issue by hahahrfool** [XTLS/Xray-core#632]
使用443端口+websocket + tls + cdn, 可以正常连上；然后我想再在另一个端口（比如44444）开一个xtls直连的（即Vless + XTLS + TCP），直接使用ip连接，因为域名的话会被解析到cloudflare，是不可以直接xtls的。但是我直连XTLS却连不上。

这是因为cdn的缘故吗？为什么呢？我明明直接指定了ip啊，而且两边的allow insecure 都打开了

还是说最近墙太高，导致我没法向该vps进行tls握手？（我已经通过nc探测确认该端口没被封禁）

另外，SNI不管是填写域名，还是填写ip，还是根本不填写，都无法正常连接。

我在另一个vps的相同配置下，未配置cdn，地址直接填ip，然后SNI什么也不填，可以直接连上

**Comment by Xia-Jingye** [comment]
Cloudflare 支持的 HTTP 端口：

80
8080
8880
2052
2082
2086
2095
Cloudflare 支持的 HTTPS 端口：

443
2053
2083
2087
2096
8443

44444端口Cloudflare会给你转发？

**Comment by Xia-Jingye** [comment]
首先，跟cdn没有任何关系，其次，为什么不把xtls也配置在443端口呢？最后，我不知道你使用何种方式把xtls监听在44444端口上的，还请自行检查xray是否正常监听了44444端口。

**Comment by hahahrfool** [comment]
> 
> 
> 首先，跟cdn没有任何关系，其次，为什么不把xtls也配置在443端口呢？最后，我不知道你使用何种方式把xtls监听在44444端口上的，还请自行检查xray是否正常监听了44444端口。

我同时监听了443，以及444xx-455xx的端口范围，端口范围的那个是单独的xtls，443就是各种回落那个。

**Comment by hahahrfool** [comment]
用nc测试，进行传输数据，服务端能够接收到，用的相同的端口。但是xray连接的话，服务端的日志根本没有显示，就像没有人连一样。

我之前某端口被封了，nc测试该端口发现nc是正常的。估计是墙封端口并不是直接封，而是封该端口的协议。如果如此，可能我的vps的所有端口范围的xtls协议都被封了。似乎墙能精准识别xtls？？

**Comment by Butterflyflower** [comment]
CF的CDN之支持部分端口
