### ISSUE TITLE
trojan的splice不能正常启用

### ISSUE THREAD

**Issue by seekingchan** [XTLS/Xray-core#64]
服务器配置

"inbounds": [
        {
            "port": 443,
            "protocol": "trojan",
            "settings": {
                "clients": [
                    {
                        "password": "*****",
                        "flow": "xtls-rprx-direct"
                    }
                ],

客户端 配置

"outbounds": [
    {
      "mux": {
        "concurrency": -1,
        "enabled": false
      },
      "protocol": "trojan",
      "settings": {
        "servers": [
          {
            "address": "****",
            "level": 8,
            "password": "***",
            "port": 443,
            "flow": "xtls-rprx-splice"
          }
        ]
      },
      "streamSettings": {
        "security": "xtls",
        "xtlsSettings": {
          "allowInsecure": true,
          "serverName": "****"
        }
      },
      "tag": "proxy"
    },

调试显示信息

XTLS DirectOut = true
XTLS DirectOut = true
XTLS DirectOut = true
XTLS DirectPre = true
XTLS DirectIn = true
XTLS ReadV
XTLS DirectPre = true
XTLS DirectIn = true

**Comment by rprx** [comment]
感谢反馈，发现 Trojan 代码中对 `account.Flow` 的修改会永久生效，下个版本修复此问题，在此之前建议用 VLESS XTLS

**Comment by rprx** [comment]
https://github.com/XTLS/Xray-core/commit/2e942e03036a7d06ff058130f6572a0a7cd3b892 应该解决了问题，你编译出来试试

**Comment by seekingchan** [comment]
XTLS DirectOut = true
XTLS DirectPre = true
XTLS DirectIn = true
XTLS Splice
现在正常了!感谢!

**Comment by rprx** [comment]
https://github.com/XTLS/Xray-core/releases/tag/v1.1.4
