### ISSUE TITLE
请问 xray 内置的 DNS 能不能实现 DNS 解析结果改写的功能？

### ISSUE THREAD

**Issue by jzp820927** [XTLS/Xray-core#641]
我想实现的功能，就是把所有使用了 cloudflare cdn 加速的域名，通过 xray 内部 DNS 解析的时候，DNS 响应结果全部固定返回为 1.1.1.1。原理大概是这样，先通过常规方式解析域名，然后判断解析结果中的 IP 地址，如果是 cloudflare 官方的 IP 地址段，就返回解析结果为 1.1.1.1。为什么需要这样的功能呢？因为我这边的宽带，针对 cloudflare 的地址段，有些能正常访问，有些又被阻断，在 cloudflare cdn 返回 IP 地址随机的情况下，就会造成有些网站能访问，有些不能，但是如果能全部返回一个固定的 cloudflare IP 的情况下（比如：1.1.1.1）那么就可以全部正常访问了。现在就想问下各位大佬 xray 的内置 DNS 能不能实现这个功能？如果不能，能否增加这个功能？如果不能增加这个功能，各位大佬能否告诉我下，有没有其他什么 DNS 软件，能实现这个功能的？

**Comment by WordsWorthLess** [comment]
如果我没有理解错的话, 你的需求,是:
	用cloudfare托管的域名, 作为你的outbound的伪装域名,然后还要将域名解释成宽带运营商没有阻断的ip.

其实方法有3个:
一  最简单:直接用ip做outbound服务器地址 "address" = "1.1.1.1"

二  脱裤子放屁的做法: 在 dns object有个host的object
	"dns": {
		"hosts": {   "我是伪装域名.com" = "1.1.1.1" }
	}
三  很复杂的做法:
	创建一个cloudflare的ip库,IP库里面加一个cloudflare的子条目,将所有没有被你的isp封锁的Cloudflare的IP加进去,然后编译成cloudflare.dat,复制到geoip.dat的目录下,
之后在dns 的server object里添加一项
	"dns": {
		"server": [
			{
				"address": "1.1.1.1",
				"port": 53,
				"domains": [ "我是伪装域名.com" ],
				"expectIPs": [ "ext:cloudflare.dat:cloudflare" ]
			}
		]
	}
具体教程这里有:https://github.com/v2fly/geoip

**Comment by jzp820927** [comment]
@WordsWorthLess 楼上的大佬，你应该理解错我的意思了，我只是纯粹用 xray 的 DNS 模块功能，而不代理流量，大概意思就是，把 xray 的 dns 设置为系统的 DNS，也就是设置 系统 DNS 为 127.0.0.1，然后当我要访问一个网站的时候，域名解析工作就会通过  xray 来负责解析域名，这个时候，xray 先做一次常规的 DNS 解析，比如通过 DOH 解析域名，然后判断域名解析结果的 IP 如果是 CF 的 IP，就统一返回解析结果为我设置的 1.1.1.1 。

为什么我会需要这样的需求呢？因为通过 CF CDN 的网站，域名解析结果都是 CF 的官方 IP（随机IP），但是我这儿 CF 的大部分官方 IP 网络不通，只有少部分 IP 能通（包括 1.1.1.1），所以如果我能把所有使用了 CF CDN 的域名都解析为固定的 1.1.1.1，就能直接访问，不用走代理了。

**Comment by xqdoo00o** [comment]
cf partner 就好了

**Comment by jzp820927** [comment]
@xqdoo00o 大佬，我说的不是我自己托管的域名，是全球所有使用了 CF CDN 的网站。

**Comment by 1850129573** [comment]
用路由加Freedom的redirect不知道行不行
````json
"routing": {
  "domainStrategy": "IPOnDemand",
  "rules": [
    {
      "type": "field",
	  "ip": ["geoip:cloudflare"],
	  "outboundTag": "cloudflare"
    }
  ]
}
````
````json
"outbounds": [
  {
    "protocol": "freedom",
	"tag": "cloudflare",
	"settings": {
	  "domainStrategy": "UseIP",
	  "redirect": "1.1.1.1:0"
	}
  }
]
````

**Comment by xqdoo00o** [comment]
用ipset + iptables DNAT 可以尝试下

**Comment by xqdoo00o** [comment]
> @1850129573 大佬，用你这个方案的话，所有 CF 的网站流量，全部都要经由 xray 转发，我的理想方案是，直接通过 DNS 解析出 1.1.1.1 的固定 IP，然后由我本地电脑直连网站。
> @xqdoo00o 这个只适用于 Linux 平台，windows 就无法了。

你的服务器是windows的么

**Comment by 1850129573** [comment]
> @1850129573 大佬，用你这个方案的话，所有 CF 的网站流量，全部都要经由 xray 转发，我的理想方案是，直接通过 DNS 解析出 1.1.1.1 的固定 IP，然后由我本地电脑直连网站。
> @xqdoo00o 这个只适用于 Linux 平台，windows 就无法了。

Dnsmasq的alias很适合这种情况，只可惜没有Windows版

**Comment by xqdoo00o** [comment]
服务器应该是linux吧，如果是机场那没办法。

**Comment by jzp820927** [comment]
@1850129573 大佬，Dnsmasq 的 alias，应该怎么配置？能给个配置示例发出来看看麽？
@xqdoo00o 我是在本机电脑 windows 上用的，为了这个小需求，专门去装个 linux，有种杀鸡用牛刀的感觉。

**Comment by xqdoo00o** [comment]
> @1850129573 大佬，Dnsmasq 的 alias，应该怎么配置？能给个配置示例发出来看看麽？
> @xqdoo00o 我是在本机电脑 windows 上用的，为了这个小需求，专门去装个 linux，有种杀鸡用牛刀的感觉。

DNS 可以远程解析，也就是在服务器解析dns，要是机场当我没说。

**Comment by jzp820927** [comment]
@xqdoo00o 大佬，就是个人使用，不是机场，我知道可以远程解析，不过感觉 ipset + iptables DNAT 配置起来有点复杂，你能说说配置流程嘛？我想了一下，还没想通用 ipset + iptables DNAT 怎么能实现我这个需求？

**Comment by xqdoo00o** [comment]
> @xqdoo00o 大佬，就是个人使用，不是机场，我知道可以远程解析，不过感觉 ipset + iptables DNAT 配置起来有点复杂，你能说说配置流程嘛？我想了一下，还没想通用 ipset + iptables DNAT 怎么能实现我这个需求？

用dnsmasq alias更简单，用dnsmasq吧
例如CF这个网段103.21.244.0/22。计算出ip范围是103.21.244.1到103.21.247.254。
dnsamsq.conf加一行
alias=103.21.244.1-103.21.247.254,1.1.1.1

**Comment by jzp820927** [comment]
@xqdoo00o 大佬，你发给我的这个配置，你亲自验证过可以实现这个功能嘛？我这边测试加入了这个配置，运行 dnsmasq 会报错，提示 alias 配置错误，无法运行程序，而且我通过  man dnsmasq 看过 dnsmasq 帮助文档了，好像确实不是这样配置的，通过查看 man 文档，我发现 dnsmasq 的 alias 好像也实现不了我的需求，我是要把一个段的所有 IP 映射到一个固定 IP，而 alias 实现的功能是一个段的 IP 一一映射，比如 192.168.1.1 -> 1.1.1.1，192.168.1.2 -> 1.1.1.2，192.168.1.3 -> 1.1.1.3，以此类推，也就是新IP的最后一段，和旧IP的最后一段是一样的，被改变的只有 IP 地址前3段，而不是多对一的映射。

**Comment by xqdoo00o** [comment]
那你还是ipset+iptables DNAT吧。
ipset用hash:net存网段。
iptables类似这样 iptables -t nat -A OUTPUT -p tcp -m set --match-set cflist dst -j DNAT --to-destination 1.1.1.1

**Comment by jzp820927** [comment]
@xqdoo00o 估计只能这样了，但是这个只能在 linux 上面用，局限性还是蛮大滴，不过还是谢谢了。

**Comment by An-nima** [comment]
Maybe you can use the built-in routing rules of v2ray / Xray. The route matches the IP and all exits are forwarded to 1.1.1.1.
In client config.json.
[https://www.v2fly.org/config/outbounds.html](https://www.v2fly.org/config/outbounds.html)
[https://www.v2fly.org/config/routing.html](https://www.v2fly.org/config/routing.html)
But I haven't tested it yet.

**Comment by jzp820927** [comment]
@An-nima 感觉大佬的建议，用 v2ray 中转流量，感觉还有点麻烦，我直接通过 iptables 实现这个功能了。
