### ISSUE TITLE
Xray的vmess动态端口无效

### ISSUE THREAD

**Issue by Busy-Bob** [XTLS/Xray-core#645]
同样的配置文件：

- Xray服务器端，v2ray/Xray 客户端，动态端口detour设置无效，只走主端口。
- v2ray服务器端，v2ray客户端，动态端口设置有效。

server配置和以下链接类似
https://guide.v2fly.org/advanced/dynamicport.html#%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%85%8D%E7%BD%AE

**Comment by hmol233** [comment]
close due to no information is provided
