### ISSUE TITLE
请教下这个错误是什么

### ISSUE THREAD

**Issue by xiaochenll** [XTLS/Xray-core#648]
app/proxyman/inbound: connection ends > proxy/http: connection ends > proxy/http: failed to write response > write tcp 127.0.0.1:1089->127.0.0.1:59252: wsasend: An established connection was aborted by the software in your host machine.

**Comment by WHATSUPTOYOU** [comment]
解决了吗兄弟  我也是这个情况

**Comment by shaojs321** [comment]
我也有

**Comment by us254** [comment]
> app/proxyman/inbound: connection ends > proxy/http: connection ends > proxy/http: failed to write response > write tcp 127.0.0.1:1089->127.0.0.1:59252: wsasend: An established connection was aborted by the software in your host machine.

Send the configuration settings for the server and client.
