### ISSUE TITLE
正常使用几分钟后就无法连接，得手动断开连接重新连接，查看日志有大量报错记录

### ISSUE THREAD

**Issue by likecreep** [XTLS/Xray-core#668]
你好，目前我遇到一个奇怪的问题。
服务端搭建的xray(1.4.2版本)+trojan。
在正常连接使用几分钟后，就无法访问任何网站，如同断网一般。得等待几分钟或者手动断开客户端再重新连接。
查看服务器日志，发现每次断开连接期间都有大量如下报错记录： （奇怪的是在另一台vps，用的同样的版本xray和同样的配置，并无如下问题，该问题仅在一台vps上反复复现，并且非常频繁。）
2021/08/07 10:38:08 [Info] [2970645924] app/proxyman/inbound: failed to close connection > tls: failed to send closeNotify alert (but connection was closed anyway): write tcp ip:port->ip:port: write: broken pipe
2021/08/07 10:38:08 [Info] [2970645924] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: connection ends > context canceled
2021/08/07 10:38:33 [Info] [3478793063] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:34 [Info] [1580027700] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:34 [Info] [1816686937] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:34 [Info] [935135355] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:34 [Info] [504546291] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:34 [Info] [453757026] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:34 [Info] [330903371] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:34 [Info] [1418207183] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [2789739087] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [3629539418] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [1595532460] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [870468813] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [2477591550] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [474164188] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [2657047079] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [3421889444] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [55294780] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [4262182667] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [3194621862] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [1939807170] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [1683427459] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [3285116647] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [1713492052] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [576180400] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [129329491] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [2880983222] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [819459692] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [1835209891] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [3918886018] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [2563049101] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [2131483533] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [1312287997] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [3907314452] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [3520859785] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [602329347] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [1719527355] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [1606437302] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [1916484796] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [1910935449] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [2925794322] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [3473922329] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [3774006003] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [3540103632] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [37382033] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [948876896] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [2582066722] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [3421708467] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [4006274965] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [75905496] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [2516906081] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [2336483280] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [2796195133] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [1162858507] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [1906864153] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [935610895] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [962667935] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [208076824] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [2504805201] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [116089124] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [102489940] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [1680705196] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [296705808] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [2370232623] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [2505561367] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [1200093221] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [2420599734] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [1054941309] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [1497223848] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [1746230941] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [560676498] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [1299402360] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [4179142556] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [1153822165] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [2753571199] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [3808924049] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [462524736] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [2783169718] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [3299984731] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [1386025905] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:38 [Info] [1561918136] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [3507813052] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [2333412930] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [1691344370] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [663711081] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [865639067] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [2577441493] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [4020797965] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [3286123836] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [2928198050] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [2764194612] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [536732002] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [3642112103] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [4173865593] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [1781334171] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [307068863] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [2274046580] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [440911291] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [1779640055] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [2747409516] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [3785660570] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [2046809665] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [337836956] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [3052255368] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [2196544662] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [4180550602] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [3059600678] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [2103482549] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [3206543675] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [357947154] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [72572056] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [2142382436] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [3015710960] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [3315630024] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [1863169537] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [1021058650] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [2275298394] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [790818042] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [1263023819] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [4125336149] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [1251168595] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [408841820] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [3605984335] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [3017193397] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [3150183670] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [2336317023] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [1783885674] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [1942961984] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [4054478077] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [3300847407] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [2947209701] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [1188347536] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [3400984267] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [1440254464] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [3171482751] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [828392343] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [1784229432] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [3327394941] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [719118738] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [1620702150] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [4182305447] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [1212219066] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [3065383551] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [325657749] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [3189775246] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [2102562275] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [3133225844] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [52131008] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [646717205] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [1190218391] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [1199142076] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [4023959438] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [985757726] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [2413864100] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [4124426160] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [1323694709] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [3530490459] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [558237374] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [195724778] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [418491935] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [2591895575] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [3015627058] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [2079647084] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [3950098496] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [4013834429] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF
2021/08/07 10:38:39 [Info] [1431602677] proxy/trojan: firstLen = 78
该条记录之后又可正常使用了。

**Comment by hmol233** [comment]
> 奇怪的是在另一台vps，用的同样的版本xray和同样的配置，并无如下问题，该问题仅在一台vps上反复复现

是网络问题？先关了，如果有新的信息请 reopen。
