### ISSUE TITLE
希望能有win上跑的无窗口版本

### ISSUE THREAD

**Issue by timi-owo** [XTLS/Xray-core#67]
如题，类似于wv2ray.exe
因为没有用GUI，手写的配置文件，然后设置的开机自启。
现在只能每次开机用winspy把console窗口手动隐藏。

**Comment by rprx** [comment]
https://github.com/XTLS/Xray-core/issues/28#issuecomment-736589268

这个方式会写在之后的文档里

**Comment by timi-owo** [comment]
> [#28 (comment)](https://github.com/XTLS/Xray-core/issues/28#issuecomment-736589268)
> 
> 这个方式会写在之后的文档里

好的，谢谢。

**Comment by iKira** [comment]
用这个
https://github.com/winsw/winsw

可以将xray-core添加为Win的系统服务，开机自动运行，不需要手动隐藏窗口。

**Comment by dmcdark** [comment]
自己写一个bat开机启动不就好了？
`@echo off
if "%1" == "h" goto begin
mshta vbscript:createobject("wscript.shell").run("%~nx0 h",0)(window.close)&&exit
:begin

D:/T-XTLS/Xray run -c D:/T-XTLS/Xray.json `

**Comment by dmcdark** [comment]
> 如题，类似于wv2ray.exe
> 因为没有用GUI，手写的配置文件，然后设置的开机自启。
> 现在只能每次开机用winspy把console窗口手动隐藏。

自己写一个bat开机启动不就好了？
`@echo off
if "%1" == "h" goto begin
mshta vbscript:createobject("wscript.shell").run("%~nx0 h",0)(window.close)&&exit
:begin

D:/Xray run -c D:/Xray.json `
