### ISSUE TITLE
请问从源码构建如何实现流量统计数据持久化？

### ISSUE THREAD

**Issue by rong280** [XTLS/Xray-core#670]
每当重启服务器或者重启服务后流量统计都会重新计算，这样感觉失去了统计的意义

**Comment by LOVEChen** [comment]
自己写个程序1分钟遍历一次并加到一个db上？

**Comment by hmol233** [comment]
xray 自身没有这个功能，同时，这也确实是一个应该由第三方软件实现的功能：

> 自己写个程序1分钟遍历一次并加到一个db上？

> 每当重启服务器或者重启服务后流量统计都会重新计算

在重启前将数据入库如何？

**Comment by ben-august** [comment]
想实现每个月固定某天才清零，但是有时候xray或者系统重启了流量统计就会清零。请问有解决方案了吗？重启前数据入库的话，请问这个数据是调用的哪个？位置在哪？
