### ISSUE TITLE
Xray-v1.4.2的VLESS+VMESS系统时间问题

### ISSUE THREAD

**Issue by LsnmxNB** [XTLS/Xray-core#675]
Xray-v1.4.2下服务配置文件上单独使用VLESS不再需要检验系统时间，这个是正确

但是VLESS+VMESS连使用VLESS协议都需要检验系统时间了

按道理使用VMESS协议才需要系统时间，而在服务配置文件上同时开启VLESS+VMESS时，连VLESS都需要检验系统时间了

不知道这是设计如此还是BUG

ps：
v2rayN，v2rayNG测试都如此排除客户端软件问题

以下服务器配置文件
{
    "log": {
        "loglevel": "warning"
    },
    "inbounds": [
        {
            "port": 443, # 可以换成其他端口
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "78", // 填写UUID，可以使用xray uuid生成
                        "flow": "xtls-rprx-direct",
                        "level": 0
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
						"alpn": "http/1.1",
                        "dest": "62998"   // 默认回落到本地的8080端口(http)						
                    }, 
                    {
                        "alpn": "h2",                         
						"dest": "62999"   // 默认回落到本地的8081端口(h2)						
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "alpn": [
					"h2",
                    "http/1.1"
                    ],
                    "certificates": [
                        {   
						    "ocspStapling": 3600,
                            "usage": "encipherment",
                            "certificateFile": "/root/.acme.sh/78.com/fullchain.cer", // 换成你的证书，绝对路径
                            "keyFile": "/root/.acme.sh/78.com/78.key" // 换成你的私钥，绝对路径
                        }
                    ]
                }
            }
			
        },
		  { 
      "port": 61169,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "78",
            "alterId": 3
          }
        ],
        "detour": {
          "to": "dynamicPort"   
        }
      }
    },
    {
      "protocol": "vmess",
      "port": "63999-65535", 
      "tag": "dynamicPort",  
      "settings": {
        "default": {
          "alterId": 3
        }
      },
      "allocate": {            
        "strategy": "random",  
        "concurrency": 2,      
        "refresh": 2           
      }
    }
    ],
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ]
}

**Comment by LsnmxNB** [comment]
@RPRX  大佬有空看看吧，谢谢

**Comment by hmol233** [comment]
- vless 里没有验证时间的机制
- 来点日志，或者其他 **能够说明情况** 的信息

**Comment by LsnmxNB** [comment]
> * vless 里没有验证时间的机制
> * 来点日志，或者其他 **能够说明情况** 的信息

我看了下 /var/log/xray 的日志并没有任何记录

只要VLESS+VMESS组合，使用VLESS修改系统时间就不能FQ了

这个情况100%复现，我好几台服务器都是如此

![Snipaste_2021-08-30_13-35-41](https://user-images.githubusercontent.com/42826027/132618840-e7bb5906-cceb-422a-ae5e-282565c78784.png)

**Comment by LsnmxNB** [comment]
@hmol233  日志给补上了，大佬有空请看看

**Comment by hmol233** [comment]
> tls: bad certificate

证书没有生效或已经过期。

**Comment by LsnmxNB** [comment]
> > tls: bad certificate
> 
> 证书没有生效或已经过期。

问题是我调整系统时间回正确时间什么问题也没有了

**Comment by hmol233** [comment]
@LsnmxNB 在客户端眼里
服务端发送的证书还有一个月才生效
client：？

**Comment by LsnmxNB** [comment]
> @LsnmxNB 在客户端眼里
> 服务端发送的证书还有一个月才生效
> client：？

移除vmess,仅保留vless就没有时间限制的问题

抬杠就没意思了，100%能复现的情况，日志也上传了

开源项目，我能理解，全凭个人爱好

**Comment by jiuqi9997** [comment]
这甚至和VLESS毫无关系，请你搞清楚情况。

> > tls: bad certificate
> 
> 证书没有生效或已经过期。

**Comment by LsnmxNB** [comment]
> 这甚至和VLESS毫无关系，请你搞清楚情况。
> 
> > > tls: bad certificate
> > 
> > 
> > 证书没有生效或已经过期。

没搞清楚的是你吧?请问你有复现?没有就不要上来就喷，提交使用问题有违反这项目的规定?

**Comment by SimonWe1** [comment]
> > @LsnmxNB 在客户端眼里
> > 服务端发送的证书还有一个月才生效
> > client：？
> 
> 移除vmess,仅保留vless就没有时间限制的问题
> 
> 抬杠就没意思了，100%能复现的情况，日志也上传了
> 
> 开源项目，我能理解，全凭个人爱好

已经说得很清楚了，TLS证书不生效，开发者的回复你自己不明白就是抬杠？
你调整的时间是8月9日，客户端连接时证书“来自未来”，此时你也无法正常使用443端口的网站。
VLESS没有时间认证，指的是时间误差不影响，而不是刻意调整时间导致TLS证书认证错误。

> > 这甚至和VLESS毫无关系，请你搞清楚情况。
> > > > tls: bad certificate
> > > 
> > > 
> > > 证书没有生效或已经过期。
> 
> 没搞清楚的是你吧?请问你有复现?没有就不要上来就喷，提交使用问题有违反这项目的规定?

已经说得很清楚了，TLS证书不生效，开发者的回复你自己不明白就是抬杠？
你调整的时间是8月9日，客户端连接时证书“来自未来”，此时你也无法正常使用443端口的网站。
VLESS没有时间认证，指的是时间误差不影响，而不是刻意调整时间导致TLS证书认证错误。

**Comment by IIIlllIIllIIIll** [comment]
> > @LsnmxNB 在客户端眼里
> > 服务端发送的证书还有一个月才生效
> > client：？
> 
> 移除vmess,仅保留vless就没有时间限制的问题
> 
> 抬杠就没意思了，100%能复现的情况，日志也上传了
> 
> 开源项目，我能理解，全凭个人爱好

在客户端打开```allowInsecure```，然后试试能不能正常使用，如果可以，就是证书有问题

**Comment by 1715173329** [comment]
我个人建议您联系 IETF 组织去掉 TLS 证书的时间限制。

**Comment by BioniCosmos** [comment]
@LsnmxNB 我确认一下，你的意思是不是说服务器上单独配置 VLESS 时不会出现问题？测试的时间误差是多长时间？

**Comment by LsnmxNB** [comment]
> > > @LsnmxNB 在客户端眼里
> > > 服务端发送的证书还有一个月才生效
> > > client：？
> > 
> > 
> > 移除vmess,仅保留vless就没有时间限制的问题
> > 抬杠就没意思了，100%能复现的情况，日志也上传了
> > 开源项目，我能理解，全凭个人爱好
> 
> 在客户端打开`allowInsecure`，然后试试能不能正常使用，如果可以，就是证书有问题

感谢提供建议，然而并不是证书问题

单独使用vless，时间对不上也没有这个问题

**Comment by LsnmxNB** [comment]
> @LsnmxNB 我确认一下，你的意思是不是说服务器上单独配置 VLESS 时不会出现问题？测试的时间误差是多长时间？

对的，我指的是服务器配置单独vless,相关一个月以上都没有问题，因为手头上很多测试机经常没电丢时间，刷机，单独vless完全不用调整手机时间就能fq,加上vless就不行了

**Comment by SimonWe1** [comment]
> > > > @LsnmxNB 在客户端眼里
> > > > 服务端发送的证书还有一个月才生效
> > > > client：？
> > > 
> > > 
> > > 移除vmess,仅保留vless就没有时间限制的问题
> > > 抬杠就没意思了，100%能复现的情况，日志也上传了
> > > 开源项目，我能理解，全凭个人爱好
> > 
> > 
> > 在客户端打开`allowInsecure`，然后试试能不能正常使用，如果可以，就是证书有问题
> 
> 感谢提供建议，然而并不是证书问题
> 
> 单独使用vless，时间对不上也没有这个问题

你自己测得有问题，仅VLESS，时间调到TLS证书申请前也会无法连接（刚也实测过了）。
再说一遍，就是TLS证书认证失败导致的，日志remote error: tls: bad certificate也没问题。

**Comment by BioniCosmos** [comment]
应该是你自己的问题，刚刚测试完毕。首先我将时钟调快 1 小时，VMess 因超过 90 秒而无法连接，VLESS 正常。然后把日期调到遥远的未来，两者均无法使用，纯 VLESS 的服务器也不行。

**Comment by badO1a5A90** [comment]
经过测试 ,仅VLESS一样会有问题,
其实用firefox直接访问回落的网站,浏览器会告诉你你的系统时间不正确,所以无法建立私密连接.

**Comment by 1715173329** [comment]
so, again
VLESS **自身**没有时间校验，如果你**仅**使用 VLESS 协议**裸奔**，那么你可以任意修改时间。
但是你搭配的 **TLS 套件** 本身有时间限制，如果你的系统时间不在证书有效时间内，那么无法通过校验（当然你可以选择不校验证书 :P，allowInsecure）。
另外，您可以尝试将系统时间调节回十年前，看看还有什么 HTTPS 网站可以正常打开。

**这不是 VLESS 协议的问题**

到此为止吧

**Comment by snowyu** [comment]
VLESS with xtls-rprx-direct is ok
VLESS with xtls-rprx-splice raise error: "tls: bad certificate"
