### ISSUE TITLE
把优选ip写入config.json根本没法连

### ISSUE THREAD

**Issue by kindusmithkindu** [XTLS/Xray-core#677]
把优选ip写入config.json根本没法连,只有把ip写入/etc/hosts才能连,如图:

![截图_2021-08-20_11-40-57](https://user-images.githubusercontent.com/88788264/130175903-fcb9c896-4410-4771-948b-b6594d9697b0.png)
这是我的配置文件:
{
    "log": {
	"error": "/var/log/xray/error.log",
        "loglevel": "warning",
	"dnsLog": false
    },
    "inbounds": [
        {
            "port": 1080,
            "listen": "127.0.0.1",
            "protocol": "socks",
            "settings": {
                "udp": true 
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "still-tree-fa21.malaizhichun.workers.dev",
                        "port": 443,
                        "users": [
                            {
                                "id": "myuuid", 
                                "encryption": "none",
                                "level": 0
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "security": "tls",
                "tlsSettings": {
		    "serverName": "still-tree-fa21.malaizhichun.workers.dev"
                },
                "wsSettings": {
                    "path": "/"
                }
            }
        }
    ]
}

**Comment by DuckSoft** [comment]
您是怎么“把优选ip写入config.json”的？在您提供的上述配置文件中，并未发现有”把优选ip写入config.json“的迹象，还请您详细描述，或提供变更后的 JSON 内容。

**Comment by kindusmithkindu** [comment]
把优选ip加入address或者servername段没法连,报错显示:

2021/08/20 11:41:38 [Warning] [2571045443] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://104.19.50.169/):  > dial tcp 104.19.50.169:443: i/o timeout transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://still-tree-fa21.malaizhichun.workers.dev/):  > dial tcp 104.19.50.169:443: operation was canceled transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://104.19.50.169/):  > dial tcp: operation was canceled] > common/retry: all retry attempts failed

**Comment by DuckSoft** [comment]
请仅将 "address": "still-tree-fa21.malaizhichun.workers.dev" 中的域名替换成“优选IP”，"serverName": "still-tree-fa21.malaizhichun.workers.dev" 不要更改，再试一次。

**Comment by kindusmithkindu** [comment]
就是这样设置的,换到address换到servername或者两个都换,都连不上啊

**Comment by DuckSoft** [comment]
`dial tcp 104.19.50.169:443: i/o timeout`

连接超时，估计被封端口了，节哀吧
