### ISSUE TITLE
Remove Qv2ray

### ISSUE THREAD

**Issue by zswdcx** [XTLS/Xray-core#678]
https://github.com/Qv2ray/Qv2ray/releases/tag/v2.7.0

**Comment by Nek0kawa1** [comment]
![](https://user-images.githubusercontent.com/75605635/130447361-c121a3f9-4e94-4ce6-87e5-5d43f591ab91.png)
![](https://user-images.githubusercontent.com/75605635/130447399-e1536211-90db-4b2a-abb6-4df1ddc98980.png)
Remove Xray-core.

**Comment by elvisw** [comment]
https://github.com/XTLS/Xray-core/pull/691
