### ISSUE TITLE
希望能够优化一下内存占用

### ISSUE THREAD

**Issue by timi-owo** [XTLS/Xray-core#68]
如题，从古老的v2ray 4.22.1版本升级过来的，几乎同样配置的情况下，
之前的版本开机占用≈10m，现在的版本开机占用＞60m，一段时间后才能勉强恢复正常（<20m）。
windows-amd64平台，作为客户端，服务器上（linux-amd64）也有内存占用过大的问题。

**Comment by rprx** [comment]
这应该是默认 jsonem 导致的，你试试 v2ray-core v4.32.0+

不过之前的相关报告大多来自华为的 arm64，amd64 上还是第一次听说

Linux x64 上，我们的测试结果是启动占 20MB

**Comment by timi-owo** [comment]
刚启动（有点恐怖）：
![1](https://user-images.githubusercontent.com/15129300/102016877-31872680-3d9e-11eb-8d36-85d62e93409d.png)
一段时间后（GC？）：
![2](https://user-images.githubusercontent.com/15129300/102016880-32b85380-3d9e-11eb-99aa-b91915d0edfe.png)

这是刚测试的，配置文件一样，三个都没有跑过流量。
其实这点内存没什么感觉，只是刚启动的时候有点离谱。
貌似要等一轮GC才能释放掉内存？不了解GO语言，瞎猜的。

**Comment by rprx** [comment]
看看 v2ray-core v4.29.x

**Comment by rprx** [comment]
@rprx 其实直接回复 BOT 好像也能回复

**Comment by timi-owo** [comment]
> 看看 v2ray-core v4.29.x

4.29.0没有问题，跟4.22.1表现一样。

**Comment by rprx** [comment]
看看 v2ray-core v4.31.3，这是默认 jsonem 前的最后一个版本

**Comment by SekiBetu** [comment]
https://eddycjy.gitbook.io/golang/di-1-ke-za-tan/why-vsz-large @rprx 有兴趣可以排查下启动过程中哪些代码申请的内存比较大，如果是很必须的代码，那就无解了

**Comment by timi-owo** [comment]
> 看看 v2ray-core v4.31.3，这是默认 jsonem 前的最后一个版本

4.31.3也没有问题。

**Comment by badO1a5A90** [comment]
@rprx 如果amd64架构也会出现的话,会不会是和jsonem加载某些设置有关.

**Comment by rprx** [comment]
看起来默认 jsonem 前调用 v2ctl 是总体瞬时占内存但很快释放，默认 jsonem 后就要等 GC，等下传一个手动调用 GC 的版本

**Comment by g552656** [comment]
我也有一个内存占用的问题一直没看到有人说以为只有我遇到
centos系统装的服务端，id比较多，自从更新4.28之后的版本，启动之后内存占用会一直不断增加，2G内存总量会一直占到1.8G，更新之前是用4.22.1版本，同样的用户数目，最高800M
在无数机器上测试，但都是centos7 64bit测试的，可以确定肯定是v2ray-core更新前后的区别
不知道是否有解。

**Comment by rprx** [comment]
https://github.com/XTLS/Xray-core/blob/decb012f9d94d31ac7fc75c18d6e36eb3d0abd2b/main/run.go#L81-L82

于是我发现，现在的代码中加载配置后已经主动触发 GC 了

**Comment by SekiBetu** [comment]
跟GC肯定没啥关系的呀，就算调用GC，你申请过程也是瞬时很大的，还是要在代码中找哪个地方调用多

**Comment by rprx** [comment]
@SekiBetu 比较奇怪的事情就是这部分内存最终会被释放，也不是内存泄漏。切片是一种可能，但配置文件占不了那么多内存。

**Comment by rprx** [comment]
@rprx 明天我调试一下 Xray 看看吧

**Comment by vangork** [comment]
@rprx 应该是读取配置文件的问题。我在红米ac2100（CPU：MT7621， RAM:128MB）上如果用xray读取json配置文件，一会就out of memory被killed了，如果把json配置文件转成pb格式的就能启动成功，所以应该是在parse json文件的时候占用的内存较大。

**Comment by rprx** [comment]
加了行 `debug.FreeOSMemory()`，看看还有没有加载 JSON 后释放内存不及时的问题

[Xray-windows-64.zip](https://github.com/XTLS/Xray-core/files/5686496/Xray-windows-64.zip)
[Xray-linux-64.zip](https://github.com/XTLS/Xray-core/files/5686499/Xray-linux-64.zip)
[Xray-linux-arm64-v8a.zip](https://github.com/XTLS/Xray-core/files/5686500/Xray-linux-arm64-v8a.zip)
[Xray-linux-mips32le.zip](https://github.com/XTLS/Xray-core/files/5686501/Xray-linux-mips32le.zip)

**Comment by rprx** [comment]
> 
> 
> https://github.com/XTLS/Xray-core/blob/decb012f9d94d31ac7fc75c18d6e36eb3d0abd2b/main/run.go#L81-L82
> 
> 于是我发现，现在的代码中加载配置后已经主动触发 GC 了

在这行后加的，原因是 `runtime.GC()` 似乎只是回收垃圾，并没有把内存返还给操作系统

**Comment by rprx** [comment]
这边进行了一些测试，发现问题不在 JSON，在 geofile 上，详情如下：

我在 Windows 上用简单的配置运行 Xray，观察到它只占了不到 5MB 的内存（群友也是这样），与你的情况完全不同。结合之前一直有的疑惑“加载个 JSON 为什么占那么多内存？”，遂想到 jsonem 还有加载转换 geofile 的功能，于是简单改了改配置以使用它们，可以看到此时 Xray 刚启动时会占较多的内存，并逐渐减到 10MB 多，与你的情况大致相符。

若使用我刚刚上传的 `debug.FreeOSMemory()` 版本，即使加载 geofile，也观察不到瞬时的内存占用。它仍然存在，但观察不到，就像以前版本的 v2ray 调用 v2ctl 一样：v2ctl 退出后，它占的内存会返还给操作系统，只是这一整个过程快到观察不到而已。

而对于接受不了瞬时内存占用的设备，比如一些硬路由，建议使用传统方式：先转 pb。我会在下个版本的 release note 中详细说明。

**Comment by badO1a5A90** [comment]
@rprx 破案了....

**Comment by vangork** [comment]
@rprx 确实，如果不配置routing，内存使用较小，如果routing里加载了geofile的话在parse的阶段就out of memory了。感谢debug。

**Comment by rprx** [comment]
@vangork 试试刚刚上传的测试版本，直接加载 json 和 .dat 还会不会被 kill

**Comment by timi-owo** [comment]
> 加了行 `debug.FreeOSMemory()`，看看还有没有加载 JSON 后释放内存不及时的问题
> 
> [Xray-windows-64.zip](https://github.com/XTLS/Xray-core/files/5686496/Xray-windows-64.zip)
> [Xray-linux-64.zip](https://github.com/XTLS/Xray-core/files/5686499/Xray-linux-64.zip)
> [Xray-linux-arm64-v8a.zip](https://github.com/XTLS/Xray-core/files/5686500/Xray-linux-arm64-v8a.zip)
> [Xray-linux-mips32le.zip](https://github.com/XTLS/Xray-core/files/5686501/Xray-linux-mips32le.zip)

此版本没有问题了。

**Comment by vangork** [comment]
> @vangork 试试刚刚上传的测试版本，直接加载 json 和 .dat 还会不会被 kill

试了，依旧会被kill，估计是128MB RAM不够用。
root@RM2100:/usr/local/xray# ./xray_softfloat
Xray 1.1.3 (Xray, Penetrates Everything.) Custom (go1.15.6 linux/mipsle)
A unified platform for anti-censorship.
2020/12/14 06:41:14 Using default config:  /usr/local/xray/config.json
2020/12/14 06:41:14 [Info] main/jsonem: Reading config: /usr/local/xray/config.json
Killed

在运行xray之前，路由有76MB的空闲RAM。
Mem: 44856K used, 76988K free, 388K shrd, 1512K buff, 3048K cached
CPU:   0% usr   0% sys   0% nic  98% idle   0% io   0% irq   0% sirq
Load average: 2.93 2.13 1.09 2/323 1605
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND

成功运行xray加载pb格式的配置文件并平稳运行后，内存剩余24MB，可见xray占用52MB左右RAM。
Mem: 97684K used, 24160K free, 388K shrd, 1412K buff, 12256K cached
CPU:   0% usr   0% sys   0% nic 100% idle   0% io   0% irq   0% sirq
Load average: 0.07 0.06 0.12 2/89 2210
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
 2210  1048 root     R     1256   1%   0% top
 1981     1 root     S     664m 558%   0% /usr/local/xray/xray -config /usr/local/xray/config.pb -format pb

刷的openwrt官方的snapshot版本没有swap分区。
root@RM2100:/usr/local/xray# df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/root                 3.3M      3.3M         0 100% /rom
tmpfs                    59.5M    388.0K     59.1M   1% /tmp
/dev/ubi0_1              97.8M     20.2M     72.9M  22% /overlay
overlayfs:/overlay       97.8M     20.2M     72.9M  22% /
tmpfs                   512.0K         0    512.0K   0% /dev

**Comment by rprx** [comment]
@vangork 好的，看来这种设备上需要先转 pb 了

**Comment by timi-owo** [comment]
> 这边进行了一些测试，发现问题不在 JSON，在 geofile 上，详情如下：
> 
> 我在 Windows 上用简单的配置运行 Xray，观察到它只占了不到 5MB 的内存（群友也是这样），与你的情况完全不同。结合之前一直有的疑惑“加载个 JSON 为什么占那么多内存？”，遂想到 jsonem 还有加载转换 geofile 的功能，于是简单改了改配置以使用它们，可以看到此时 Xray 刚启动时会占较多的内存，并逐渐减到 10MB 多，与你的情况大致相符。
> 
> 若使用我刚刚上传的 `debug.FreeOSMemory()` 版本，即使加载 geofile，也观察不到瞬时的内存占用。它仍然存在，但观察不到，就像以前版本的 v2ray 调用 v2ctl 一样：v2ctl 退出后，它占的内存会返还给操作系统，只是这一整个过程快到观察不到而已。
> 
> 而对于接受不了瞬时内存占用的设备，比如一些硬路由，建议使用传统方式：先转 pb。我会在下个版本的 release note 中详细说明。

不过我还是很疑惑为什么转换JSON和GEOFILE需要申请这么多内存......

**Comment by rprx** [comment]
@timi-owo 只是加载转换 geofile 的问题，与 JSON 无关

**Comment by SekiBetu** [comment]
> > 这边进行了一些测试，发现问题不在 JSON，在 geofile 上，详情如下：
> > 我在 Windows 上用简单的配置运行 Xray，观察到它只占了不到 5MB 的内存（群友也是这样），与你的情况完全不同。结合之前一直有的疑惑“加载个 JSON 为什么占那么多内存？”，遂想到 jsonem 还有加载转换 geofile 的功能，于是简单改了改配置以使用它们，可以看到此时 Xray 刚启动时会占较多的内存，并逐渐减到 10MB 多，与你的情况大致相符。
> > 若使用我刚刚上传的 `debug.FreeOSMemory()` 版本，即使加载 geofile，也观察不到瞬时的内存占用。它仍然存在，但观察不到，就像以前版本的 v2ray 调用 v2ctl 一样：v2ctl 退出后，它占的内存会返还给操作系统，只是这一整个过程快到观察不到而已。
> > 而对于接受不了瞬时内存占用的设备，比如一些硬路由，建议使用传统方式：先转 pb。我会在下个版本的 release note 中详细说明。
> 
> 不过我还是很疑惑为什么转换JSON和GEOFILE需要申请这么多内存......

我猜可能是把5m大小的geoip文件加载进内存，然后再给富裕的内存空间来进行转换吧

**Comment by timi-owo** [comment]
> > > 这边进行了一些测试，发现问题不在 JSON，在 geofile 上，详情如下：
> > > 我在 Windows 上用简单的配置运行 Xray，观察到它只占了不到 5MB 的内存（群友也是这样），与你的情况完全不同。结合之前一直有的疑惑“加载个 JSON 为什么占那么多内存？”，遂想到 jsonem 还有加载转换 geofile 的功能，于是简单改了改配置以使用它们，可以看到此时 Xray 刚启动时会占较多的内存，并逐渐减到 10MB 多，与你的情况大致相符。
> > > 若使用我刚刚上传的 `debug.FreeOSMemory()` 版本，即使加载 geofile，也观察不到瞬时的内存占用。它仍然存在，但观察不到，就像以前版本的 v2ray 调用 v2ctl 一样：v2ctl 退出后，它占的内存会返还给操作系统，只是这一整个过程快到观察不到而已。
> > > 而对于接受不了瞬时内存占用的设备，比如一些硬路由，建议使用传统方式：先转 pb。我会在下个版本的 release note 中详细说明。
> > 
> > 
> > 不过我还是很疑惑为什么转换JSON和GEOFILE需要申请这么多内存......
> 
> 我猜可能是把5m大小的geoip文件加载进内存，然后再给富裕的内存空间来进行转换吧

可能是吧，问题应该就在于 **GC 后没有立即 FREE 掉还给 OS** 导致部分内存有限的设备容易 OOM

猜测是 Go 内存管理里的一种内存池机制，不过好在可以 `debug.FreeOSMemory()` 但还是有瞬时内存占用。

刚试图看了一下 geofile 结构和相关路由模块的代码，发现有点读不懂哈哈，等我学会了 Go 再来贡献代码吧。

我觉得 geofile 有改进空间，或许可以不用 protobuf，但牵扯到的相关模块也要改。

还要考虑日渐增长的数据量和 routing 处理性能，以及历史数据的升级，改动量应该不小，还是个 breaking change。

目前大佬们的重心还是在协议和传输这一块，毕竟这个才是 Project V / Project X 的灵魂。

真的很感谢这个伟大的项目，除了用来翻墙还有很多实用的地方，简直神器。

**Comment by rprx** [comment]
由于 geoip.dat 比较大，所以我特意去看了下加载它的代码（也不至于占上百 MB 吧？），果然发现了问题：

https://github.com/XTLS/Xray-core/blob/2e942e03036a7d06ff058130f6572a0a7cd3b892/infra/conf/router.go#L329-L346

https://github.com/XTLS/Xray-core/blob/2e942e03036a7d06ff058130f6572a0a7cd3b892/infra/conf/router.go#L150-L171

**对于路由规则内的每一个 `geoip:`，都会从头加载 5MB 的 geoip.dat 并 Unmarshal + 遍历。**

**不用怀疑，`geosite:` 我也看了，也是这样。** 对于这两个，都是你写多少规则就重复多少次，你们可以验证一下。

所以，我决定重写这部分代码。

**Comment by g552656** [comment]
请问对服务端也有效吗？
现在服务端加载用户多了会慢慢占用到接近2G内存

**Comment by rprx** [comment]
@g552656 这应该是另一个问题了

**Comment by g552656** [comment]
唉，头疼

**Comment by rprx** [comment]
麻烦楼上各位试试这个版本

[Xray-windows-64.zip](https://github.com/XTLS/Xray-core/files/5688367/Xray-windows-64.zip)
[Xray-linux-64.zip](https://github.com/XTLS/Xray-core/files/5688372/Xray-linux-64.zip)
[Xray-linux-arm64-v8a.zip](https://github.com/XTLS/Xray-core/files/5688382/Xray-linux-arm64-v8a.zip)
[Xray-linux-mips32le.zip](https://github.com/XTLS/Xray-core/files/5688384/Xray-linux-mips32le.zip)

**Comment by Butterflyflower** [comment]
@rprx 速度好快，感谢。

**Comment by rprx** [comment]
上面的版本是给所有 geoip 和 geosite 做了缓存：每个文件只会加载、Unmarshal、遍历一次，并放到 map 里，加载完配置后给 map 赋值 nil，并主动触发 GC 和 FreeOSMemory，此时只有需要的部分会留在内存中。

在我的 Windows 系统上，只用到最新的 geoip.dat 时会占 50MB 多的瞬时内存（观察不到），加载完配置后只占 10MB 多。

瞬时占内存是必要的，如果某些设备上无法提供这些内存，还是得先转为 pb。

**Comment by SekiBetu** [comment]
解决了加载多次的问题，但是似乎geoip的读取是无法优化下来的，因为还是要读取至少一次的，这一次就是峰值，重复读似乎是不会重复申请内存空间的？
观察到的现象是
1.1.3版：使用了加强版的geoip和geosite，各自5mb大小，启动占用100mb，卡在80mb处很久(推测就是上述的重复加载过程)，然后降到60mb稳定
issue中的新版本：使用了加强版的geoip和geosite，各自5mb大小，启动占用150mb，瞬间掉到60mb稳定

**Comment by rprx** [comment]
@SekiBetu 瞬间掉到 60 是 FreeOSMemory 的功劳，1.1.3 还没有它。

目前看来，重复加载虽然不优雅，但的确不会叠加申请内存（如果够用的话）。这部分代码可以更优雅，但瞬时内存始终是必要的。

**Comment by rprx** [comment]
我想出了另一种方式：之前写 VLESS 的时候，VLESS 的结构中有 pb，观察到 Marshal 后的 pb 仍具有一定的可读性，毕竟 TLV。

所以，完全可以先从文件中取出需要的那部分再 Unmarshal，而不必把整个 5MB 的文件 Unmarshal 后再找需要的那部分。

这是一个通用解决方案。

**Comment by defead** [comment]
上面最后一个版本，不会kill了

**Comment by timi-owo** [comment]
> 麻烦楼上各位试试这个版本
> 
> [Xray-windows-64.zip](https://github.com/XTLS/Xray-core/files/5688367/Xray-windows-64.zip)
> [Xray-linux-64.zip](https://github.com/XTLS/Xray-core/files/5688372/Xray-linux-64.zip)
> [Xray-linux-arm64-v8a.zip](https://github.com/XTLS/Xray-core/files/5688382/Xray-linux-arm64-v8a.zip)
> [Xray-linux-mips32le.zip](https://github.com/XTLS/Xray-core/files/5688384/Xray-linux-mips32le.zip)

已测试 windows-amd64 和 linux-amd64 都非常 **nice**，感谢！@rprx

**Comment by rprx** [comment]
> 
> 
> 上面最后一个版本mips32le，不会kill了，最后占用内存在50M左右

现在我比较疑惑了：Go 在不同架构上管理内存的方式也不同吗？按理说如果重复加载不会叠加申请内存，那么那个测试版和 v1.1.3 不应该有区别。或许 Unmarshal 过程也比较耗内存？

**Comment by rprx** [comment]
请试试这个版本，在 https://github.com/XTLS/Xray-core/commit/aeddc630dd9015afebbb66a4544b063a09128447 的前提下简单实现了 https://github.com/XTLS/Xray-core/issues/68#issuecomment-744453123 ，**经测试大幅降低了瞬时内存占用，最终内存占用也会小一些。**

[Xray-windows-64.zip](https://github.com/XTLS/Xray-core/files/5691380/Xray-windows-64.zip)
[Xray-linux-64.zip](https://github.com/XTLS/Xray-core/files/5691382/Xray-linux-64.zip)
[Xray-linux-arm64-v8a.zip](https://github.com/XTLS/Xray-core/files/5691383/Xray-linux-arm64-v8a.zip)
[Xray-linux-mips32le.zip](https://github.com/XTLS/Xray-core/files/5691386/Xray-linux-mips32le.zip)

如果没有问题，我会把它和上一个带缓存的版本结合起来，实现优雅与高效并存。

**Comment by vangork** [comment]
@rprx 上个版本问题依旧，但是最新的这个版本解决了问题，感谢！

**Comment by wsa01378** [comment]
xray core mipsle32 占用较v2ray v4.2x高，路由Padavan linux 64M版跑v2正常，跑xray爆内存kill了

**Comment by rprx** [comment]
**最终版：文件加载缓存 + 预解析 pb 结构 https://github.com/XTLS/Xray-core/issues/68#issuecomment-744453123 + Unmarshal 出的 IP、Site 缓存 + 清空缓存、主动 GC、FreeOSMemory**

解决了很多问题，详情会写在下个版本的 release note 中。我这边测试 OK，请大家测试一下，如果没有问题，等下提交代码。

[Xray-android-arm64-v8a.zip](https://github.com/XTLS/Xray-core/files/5694364/Xray-android-arm64-v8a.zip)
[Xray-linux-64.zip](https://github.com/XTLS/Xray-core/files/5694366/Xray-linux-64.zip)
[Xray-linux-arm64-v8a.zip](https://github.com/XTLS/Xray-core/files/5694368/Xray-linux-arm64-v8a.zip)
[Xray-linux-mips32le.zip](https://github.com/XTLS/Xray-core/files/5694370/Xray-linux-mips32le.zip)
[Xray-windows-64.zip](https://github.com/XTLS/Xray-core/files/5694372/Xray-windows-64.zip)

**Comment by SekiBetu** [comment]
> **最终版：文件加载缓存 + 预解析 pb 结构 [#68 (comment)](https://github.com/XTLS/Xray-core/issues/68#issuecomment-744453123) + Unmarshal 出的 IP、Site 缓存 + 清空缓存、主动 GC、FreeOSMemory**
> 
> 解决了很多问题，详情会写在下个版本的 release note 中。我这边测试 OK，请大家测试一下，如果没有问题，等下提交代码。
> 
> [Xray-android-arm64-v8a.zip](https://github.com/XTLS/Xray-core/files/5694364/Xray-android-arm64-v8a.zip)
> [Xray-linux-64.zip](https://github.com/XTLS/Xray-core/files/5694366/Xray-linux-64.zip)
> [Xray-linux-arm64-v8a.zip](https://github.com/XTLS/Xray-core/files/5694368/Xray-linux-arm64-v8a.zip)
> [Xray-linux-mips32le.zip](https://github.com/XTLS/Xray-core/files/5694370/Xray-linux-mips32le.zip)
> [Xray-windows-64.zip](https://github.com/XTLS/Xray-core/files/5694372/Xray-windows-64.zip)

这版可以了，开局100mb占用，瞬间掉到40mb，慢慢升到60mb稳定

**Comment by rprx** [comment]
@SekiBetu 能到 100MB，应该是用了很多 geo 规则吧。因为这个版本中加载配置阶段 geo 文件会被缓存到内存中，你的两个加强版规则加起来占 10MB，然后预解析 pb 结构，只 Unmarshal 用到的部分且缓存，用不到的部分不会被 Unmarshal，大幅降低了瞬时内存占用。加载完配置后清理垃圾，包括清空内存中缓存的文件。

**Comment by SekiBetu** [comment]
后续几次测试都是开局只有50mb以下了，玄学，任务管理器的测试不可信，不知道Windows平台有没有什么其他手段检测程序启动资源占用情况的

**Comment by vangork** [comment]
@rprx 上个版本问题解决了，此版本又发了生启动oom了。

**Comment by rprx** [comment]
@SekiBetu 我这边只用 geoip.dat 的 private 的数据是：v1.1.3 瞬时占用 50MB+，优化版本瞬时占用 15MB 左右

**Comment by SekiBetu** [comment]
我觉得让低内存路由用户测试更准，毕竟物理限制，超出就boom

**Comment by vangork** [comment]
估计即使是上个版本，启动消耗的ram已经在临界值，这个版本完善增加了些许ram消耗就oom了。

**Comment by rprx** [comment]
@vangork 缓存机制会消耗一些内存，比如缓存那两个文件会多占不到 10MB，但也可能是缓存解析出的 IP 和 Site 的锅

**Comment by vangork** [comment]
> 缓存机制会消耗一些内存，比如缓存那两个文件会多占

@rprx ，应该就是这额外10MB的原因，因为上个版本启动时，瞬时峰值的可用ram不足10MB。此外使用的也是加强版的geosite和geoip, from：https://github.com/Loyalsoldier/v2ray-rules-dat. geoip和geosite均使用了。

```
"routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "domain": [
          "somedomain.com"
        ],
        "outboundTag": "vless1"
      },
      {
        "type": "field",
        "domain": [
          "geosite:geolocation-!cn"
        ],
        "outboundTag": "vless2"
      },
      {
        "type": "field",
        "domain": [
          "geosite:cn"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "ip": [
          "10.0.0.0/8"
        ],
        "outboundTag": "vless1"
      },
      {
        "type": "field",
        "ip": [
          "geoip:cn",
          "192.168.1.0/24",
          "192.168.100.0/24"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "outboundTag": "blocked",
        "domain": [
          "geosite:category-ads-all"
        ]
      }
    ]
  }
```

**Comment by rprx** [comment]
简化了 Map 结构，增加了几处 `runtime.GC()`。如果这个版本不行，那就默认关闭缓存，只是多次加载不怎么优雅。

[Xray-android-arm64-v8a.zip](https://github.com/XTLS/Xray-core/files/5694867/Xray-android-arm64-v8a.zip)
[Xray-linux-64.zip](https://github.com/XTLS/Xray-core/files/5694869/Xray-linux-64.zip)
[Xray-linux-arm64-v8a.zip](https://github.com/XTLS/Xray-core/files/5694872/Xray-linux-arm64-v8a.zip)
[Xray-linux-mips32le.zip](https://github.com/XTLS/Xray-core/files/5694873/Xray-linux-mips32le.zip)
[Xray-windows-64.zip](https://github.com/XTLS/Xray-core/files/5694876/Xray-windows-64.zip)

**Comment by rprx** [comment]
现在越来越觉得之前的多次加载不用改，只需加上预解析 pb 结构。

**Comment by vangork** [comment]
> 现在越来越觉得之前的多次加载不用改，只需加上预解析 pb 结构。

再及时GC就可以了。

**Comment by rprx** [comment]
@vangork 新的版本有问题吗

**Comment by vangork** [comment]
@rprx 感谢，可以使用。

**Comment by rprx** [comment]
@vangork 有观察到瞬时内存占多少吗

**Comment by SekiBetu** [comment]
![Snipaste_2020-12-15_17-56-26](https://user-images.githubusercontent.com/38283893/102202356-20820680-3ebf-11eb-929a-5b0ac66ff18c.png)
![Snipaste_2020-12-15_17-56-37](https://user-images.githubusercontent.com/38283893/102202379-2546ba80-3ebf-11eb-9e3a-4cc2d7437bf6.png)
![Snipaste_2020-12-15_17-56-46](https://user-images.githubusercontent.com/38283893/102202385-27107e00-3ebf-11eb-8212-023709d2d86c.png)
![Snipaste_2020-12-15_17-59-11](https://user-images.githubusercontent.com/38283893/102202393-28da4180-3ebf-11eb-9764-254f60f35541.png)
![Snipaste_2020-12-15_17-59-29](https://user-images.githubusercontent.com/38283893/102202394-2972d800-3ebf-11eb-8dff-daf4c6408450.png)
![Snipaste_2020-12-15_18-02-57](https://user-images.githubusercontent.com/38283893/102202398-2a0b6e80-3ebf-11eb-98fd-f7d931f7cc64.png)
![Snipaste_2020-12-15_18-04-51](https://user-images.githubusercontent.com/38283893/102202399-2aa40500-3ebf-11eb-9123-916be7076217.png)
这边提供这个方法来监测，刷新率只能降到1秒一次，还是有点误差的

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/102203241-3ba14600-3ec0-11eb-9c91-b1dfe752d89a.png)
更新：上述的Working Set更换为Private Bytes的结果和任务管理器的结果一模一样

**Comment by vangork** [comment]
@rprx，
无缓存版本
root@RM2100:~# cat /proc/8787/status
VmPeak:   680872 kB
VmSize:   680872 kB
**VmHWM:     48272 kB**
VmRSS:     48272 kB

当前版本
root@RM2100:~# cat /proc/8868/status | grep VmPeak
VmPeak:   681136 kB
VmSize:   681136 kB
**VmHWM:     61664 kB**
VmRSS:     55224 kB

PS:
VmPeak and VmSize are the peak/current total address space used. In other words, the sum of all virtual memory areas in the process, whatever they are used for.
VmHWM and VmRSS are the process’s peak/current usage of physical RAM.

**Comment by rprx** [comment]
@SekiBetu 你试试这个版本 https://github.com/XTLS/Xray-core/issues/68#issuecomment-744689847

**Comment by SekiBetu** [comment]
> @SekiBetu 你试试这个版本 [#68 (comment)](https://github.com/XTLS/Xray-core/issues/68#issuecomment-744689847)

![image](https://user-images.githubusercontent.com/38283893/102205595-4d381d00-3ec3-11eb-9b51-247463a28bfe.png)
比起第三个版本，这个版本的后两次测试明显大幅降低了内存占用，和我刚才测出来一样玄学，首次启动100mb，后面几次启动就掉下去了

**Comment by rprx** [comment]
@SekiBetu 结论不正确，我的猜想是你用到了几乎所有规则（比如除 CN 外），所以没有明显区别，这取决于具体的配置文件

**Comment by SekiBetu** [comment]
> @SekiBetu 结论不正确，我的猜想是你用到了几乎所有规则（比如除 CN 外），所以没有明显区别，这取决于具体的配置文件

我用的规则配置是geoip:cn、private和geosite:cn、private是代理的，然后geosite:category-ads-all是block

**Comment by rprx** [comment]
@SekiBetu 试试下面的版本，因为不太科学（或许是 CN 占很大一部分？）

**Comment by rprx** [comment]
**新的最终版：默认关闭的缓存机制 + 预解析 pb 结构 https://github.com/XTLS/Xray-core/issues/68#issuecomment-744453123 只 Unmarshal 需要的部分 + 多次主动 GC + FreeOSMemory**

这个版本应该最省内存了，望得到广泛测试。如果没有问题，等下提交代码。

[Xray-android-arm64-v8a.zip](https://github.com/XTLS/Xray-core/files/5695389/Xray-android-arm64-v8a.zip)
[Xray-linux-64.zip](https://github.com/XTLS/Xray-core/files/5695396/Xray-linux-64.zip)
[Xray-linux-arm64-v8a.zip](https://github.com/XTLS/Xray-core/files/5695398/Xray-linux-arm64-v8a.zip)
[Xray-linux-mips32le.zip](https://github.com/XTLS/Xray-core/files/5695401/Xray-linux-mips32le.zip)
[Xray-windows-64.zip](https://github.com/XTLS/Xray-core/files/5695406/Xray-windows-64.zip)

**Comment by defead** [comment]
> **新的最终版：默认关闭的缓存机制 + 预解析 pb 结构 [#68 (comment)](https://github.com/XTLS/Xray-core/issues/68#issuecomment-744453123) 只 Unmarshal 需要的部分 + 多次主动 GC + FreeOSMemory**
> 
> 这个版本应该最省内存了，望得到广泛测试。如果没有问题，等下提交代码。
> 
> [Xray-android-arm64-v8a.zip](https://github.com/XTLS/Xray-core/files/5695389/Xray-android-arm64-v8a.zip)
> [Xray-linux-64.zip](https://github.com/XTLS/Xray-core/files/5695396/Xray-linux-64.zip)
> [Xray-linux-arm64-v8a.zip](https://github.com/XTLS/Xray-core/files/5695398/Xray-linux-arm64-v8a.zip)
> [Xray-linux-mips32le.zip](https://github.com/XTLS/Xray-core/files/5695401/Xray-linux-mips32le.zip)
> [Xray-windows-64.zip](https://github.com/XTLS/Xray-core/files/5695406/Xray-windows-64.zip)

misp32le 占用内存 16M左右，比之前好多了

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/102211680-db180600-3ecb-11eb-87d4-dc5186af1058.png)
截到峰值的概率变小了
![image](https://user-images.githubusercontent.com/38283893/102211559-ac019480-3ecb-11eb-9c79-720e5243e64f.png)
这边丢人了，我发现峰值的产生应该是我没有关闭网页、QQ、Telegram等软件测试的结果，我又扔到windows沙盒中去测试，结果是很正常的从小到大，而没有峰值，所以release note可以注释一下，启动客户端core的时候机子不要连接大量网页

**Comment by vangork** [comment]
@rprx 完美
VmPeak:   680624 kB
VmSize:   680624 kB
VmHWM:     46388 kB
VmRSS:     46388 kB

**Comment by rprx** [comment]
GitHub 上和 Project X 群反馈均很理想，代码已提交 https://github.com/XTLS/Xray-core/commit/45f44c401acd31e0f5dcf8e7b4f2789cbc1be12a ， https://github.com/XTLS/Xray-core/issues/68#issuecomment-745231528 的文件均 Reproducible

这大幅降低了启动时的瞬时内存占用，并小幅降低了启动后的最终内存占用。

感谢此 issue 及各位的多次测试，现在解决了默认内部加载配置带来的问题，预解析 pb 结构更是让更多的设备可以直接加载配置。

**Comment by badO1a5A90** [comment]
测试结果完美,结案,撒花.

**Comment by qiumzh** [comment]
期待发版！我的小内存arm开发板，正遇到这个问题.

**Comment by wsa01378** [comment]
64M RAM WORK

**Comment by rprx** [comment]
> 
> 
> 64M RAM WORK

以前的版本可以吗

**Comment by rprx** [comment]
https://github.com/XTLS/Xray-core/releases/tag/v1.1.4

**Comment by muziling** [comment]
24047     1 proxy    S    4803m 994%   0% xray -c /root/xray.json

这个问题有完全解决了吗？x64路由跑了13天， 占用近5G。
# xray version
Xray 1.5.3 (Xray, Penetrates Everything.) OpenWrt (go1.17.6 linux/amd64)
A unified platform for anti-censorship.

**Comment by Mr-xn** [comment]
docker 里一样 out of memory killed process xxxx (xray) total-vm:6627100KB,anon-rss:253404KB

**Comment by realerikk0** [comment]
x64一样， /tmp/etc/passwall/bin/xray run -c /tmp/etc/passwall/TCP_SOCKS.json消耗了全部的memory，4GB，内存占用肉眼可见增加
