### ISSUE TITLE
VLESS+TCP+TLS模式，同样配置文件在windows10上正常，在Ubuntu 21.04上报x509: certificate signed by unknown authority错误

### ISSUE THREAD

**Issue by elfzweik** [XTLS/Xray-core#680]
服务端和客户端都是Xray-core，未使用第三方客户端。客户端监听socks5，routing rule设置geoip: private走proxy，用以连接远端内网中的路由器后台。客户端和服务端均在国内。Windows10下的客户端连接完全正常，Ubuntu21.04的客户端报如下错误。

2021/08/21 03:02:28 [Info] [1825122968] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to decode response header > proxy/vless/encoding: failed to read response version > x509: certificate signed by unknown authority

**Comment by jiuqi9997** [comment]
@elfzweik 检查证书链是否完整

**Comment by elfzweik** [comment]
> @elfzweik 检查证书链是否完整

是完整的，共3个文件。chain.pem也在

**Comment by elfzweik** [comment]
OK，搞定了。是我无知，以为只要把中间证书链文件放在同一目录下就行了。原来是要把chain.pem中的证书粘贴到cert.pem里面。
