### ISSUE TITLE
利用SNI分流，stream模块443流量转发后，可以富强和建立其他web网站，但是速度有很明显的下降的问题探究。

### ISSUE THREAD

**Issue by ChiehJang** [XTLS/Xray-core#685]
我目前使用的是VLESS+TCP+xtls-rprx-direct，网上找到的一键脚本和按步骤搭建，xray都需要占有443端口，
于是找到了利用SNI分流，stream模块加持下，解决了443端口被xray独占的情况,
但是网速大打折扣，比如若直接让xray监听443 速度快，可以跑满我本地的300Mbps电信带宽，但是不能再部署其他的网站，vps资源被浪费了有点不值得；若用了nginx stream模块，监听其他端口，443端口转发后，虽然也可以搭建其他web服务，可是安装了xray科学富强后，速度测速只有80Mmps，请问：这是nginxSNI这项技术的弊端吗，还是说我猜测可以实现相同的速度，只是多了这一步监听转发对vps性能过高，但我检查了CPU，两种情况都没有超过50%的负荷，所以特别想知道各位使用了分流共用443端口后，速度是否有明显的减弱。

**Comment by lw4free** [comment]
> 
> 
> > 我也使用nginx stream 测速有超过200M 使用tcp+tls(nginx)+vless 可以回落 不能使用xtls 你是怎样配置的?
> > 另请教 你使用nginx stream SNI的配置
> 
> 这是我自己写的笔记，里面有配置文件，可以实现xtls 也是参考了网上好多别人的配置， 但最终还是没有办法实现跑慢本地带宽，怀疑是两个原因，第一，VPS的CPU单核可能分流达不到性能要求，第二采用这样子分流的方式速度有较大损耗，或许可以通过调参来改善，但是毕竟不是专业的，也搞不太懂。
> [传送门](https://notes.zhangjie.work/index.php/archives/138/)

参考你的SNI配置成功分流，没有发现掉速，能跑300M+。
主要配置：
```
ningx:
stream {
    map $ssl_preread_server_name $name {
        mydomain                xtls;
        www.mydomain            http;
    }
    # upstream pool
    upstream xtls {
        server localhost:8081;
    }
    upstream http {
        server localhost:8080;
    }
    server {
        listen 443 so_keepalive=on;
        proxy_pass $name;
        proxy_protocol on;
        ssl_preread on;
    }
}
xray:
    {
      "tag": "xtls",
      "port": 8081,
      "listen": "127.0.0.1",
      "protocol": "vless",
      "settings": {
        "clients": [
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "dest": 8080
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
          "alpn": [
            "http/1.1"
          ],
          "certificates": [
            {
              "certificateFile": "/etc/ssl/cert.pem",
              "keyFile": "/etc/ssl/key.pem"
            }
          ]
        },
        "tcpSettings": {
          "acceptProxyProtocol": true
        }
      }
    },
```

**Comment by ChiehJang** [comment]
> > > 我也使用nginx stream 测速有超过200M 使用tcp+tls(nginx)+vless 可以回落 不能使用xtls 你是怎样配置的?
> > > 另请教 你使用nginx stream SNI的配置
> > 
> > 
> > 这是我自己写的笔记，里面有配置文件，可以实现xtls 也是参考了网上好多别人的配置， 但最终还是没有办法实现跑慢本地带宽，怀疑是两个原因，第一，VPS的CPU单核可能分流达不到性能要求，第二采用这样子分流的方式速度有较大损耗，或许可以通过调参来改善，但是毕竟不是专业的，也搞不太懂。
> > [传送门](https://notes.zhangjie.work/index.php/archives/138/)
> 
> 参考你的SNI配置成功分流，没有发现掉速，能跑300M+。
> 主要配置：
> 
> ```
> ningx:
> stream {
>     map $ssl_preread_server_name $name {
>         mydomain                xtls;
>         www.mydomain            http;
>     }
>     # upstream pool
>     upstream xtls {
>         server localhost:8081;
>     }
>     upstream http {
>         server localhost:8080;
>     }
>     server {
>         listen 443 so_keepalive=on;
>         proxy_pass $name;
>         proxy_protocol on;
>         ssl_preread on;
>     }
> }
> xray:
>     {
>       "tag": "xtls",
>       "port": 8081,
>       "listen": "127.0.0.1",
>       "protocol": "vless",
>       "settings": {
>         "clients": [
>         ],
>         "decryption": "none",
>         "fallbacks": [
>           {
>             "dest": 8080
>           }
>         ]
>       },
>       "streamSettings": {
>         "network": "tcp",
>         "security": "xtls",
>         "xtlsSettings": {
>           "alpn": [
>             "http/1.1"
>           ],
>           "certificates": [
>             {
>               "certificateFile": "/etc/ssl/cert.pem",
>               "keyFile": "/etc/ssl/key.pem"
>             }
>           ]
>         },
>         "tcpSettings": {
>           "acceptProxyProtocol": true
>         }
>       }
>     },
> ```

`listen 443 so_keepalive=on;`以及` "acceptProxyProtocol": true`，是我配置中所没有的，这或许就是我的不能跑满本地带宽的症结所在吧。前面熊猫大哥也提及了`reuseport 好像是会变慢`，看来真的是这个原因了。

**Comment by lw4free** [comment]
nginx和xray主要配置就上面那些了 其它配置应该对速度没有影响 我也没有跑满公司500M vps和透明网关比较弱鸡

**Comment by gcphym** [comment]
马克学习一下
