### ISSUE TITLE
还维护吗?

### ISSUE THREAD

**Issue by clcc2019** [XTLS/Xray-core#689]
还维护吗?不维护想换v2ray了

**Comment by kxjhcmc** [comment]
应该不维护了，放弃了

**Comment by GleenJi** [comment]
> 
> 
> 应该不维护了，放弃了

放弃了？为什么呀

**Comment by badO1a5A90** [comment]
> 应该不维护了，放弃了

不要随便下结论.
此贴终结

**Comment by hronro** [comment]
不说猜测，直说几个目前的事实：

1. 作者目前已经失联
1. 作者失联期间，整个项目没有新 commit，也没有一个 PR 被合并。
目前整个项目处于即使有人想继续维护（开发），也无能为力的状态
1. 没人知道作者以后还会不会出现，也没人知道作者如果出现以后还会不会继续维护项目

**Comment by Johnny256Dawson** [comment]
@hronro 根据群主人设，假设设备物理隔离，放假东西在学校没带，那么9月份开学就应该上线了，如果没有上线，可以先向内部开发者了解，确实了解不到那么就要关注下群主的情况

**Comment by hmol233** [comment]
1. 不能确定 @RPRX 已经失联。
2. 即使在所谓的“失联期间”，同样有贡献与Pull Request。其他维护者（我）有能力继续维护并发布更新，仅仅是由于 **自身原因** 无意于继续维护。

> 不要随便下结论.
> 此贴终结

目前，我更倾向于观望的态度。如果有人认为 Project X 已被放弃，那么请去 V2Fly 社区，那里可能更加适合你。

**Comment by badO1a5A90** [comment]
@hmol233 所以这是大H你的新号吗

**Comment by badO1a5A90** [comment]
[Xray-core v1.4.3](https://github.com/XTLS/Xray-core/releases/tag/v1.4.3) 已经发布
后续会周期性稳定更新
