### ISSUE TITLE
想自定义文件位置

### ISSUE THREAD

**Issue by GleenJi** [XTLS/Xray-core#69]
萌新，有些问题自己琢磨不来，问问大佬们：
我安装都是自己下载linux文件，然后通过winscp手动把文件xray，*.dat，config. json上传到自己想放的位置，所以问题来了，v2ray的.dat文件我知道是在v2ray.service里添加环境变量V2RAY_LOCATION_ASSET，那么xray呢？环境变量是不是就是XRAY_LOCATION_ASSET ？
还有，我发现不设置环境变量好像也没问题？就是.dat文件没放在默认位置，环境变量我也没设置的情况下，也可以正常使用，是不是此时xray（v2ray）只是不会读取. dat文件然后没法进行Routing判断？
不过我的服务器端cofig里面是没设置Routing的，所以是不是服务器端的xray(v2ray)用不到. dat ？

**Comment by xianren78** [comment]
是的，是的

**Comment by GleenJi** [comment]
> 
> 
> 是的，是的

感谢，经过几次尝试确实是XRAY_LOCATION_ASSET，如果.dat文件没在规定的位置下，config里还设置了和.dat相关的Routing，那xray(v2ray)是没办法启动的，会报错
