### ISSUE TITLE
新版 Xray-openbsd-arm64-v8a.zip 運行即退出

### ISSUE THREAD

**Issue by LearZhou** [XTLS/Xray-core#696]
剛剛本來準備升級一把，但運行即退出。回退到 1.4.2 就沒問題了。

**Comment by badO1a5A90** [comment]
- 某些版本,比如android-arm64-v8a, 可能会有问题
  1. 原因出在上游. 也即go本身的原因, go目前版本有 bug 导致交叉编译可能产生问题, 参见 https://github.com/golang/go/issues/47760. 
  2. go 已经在 https://github.com/golang/go/commit/47a57bc4f0c6a2b7ac12d4eed4ce305446654459 修复, 但还没 release 新版本. (需要等go release 新版本后重新编译一遍)
  3. 目前暂时的方式是可以使用 linux 的对应版本

已经 补充至 release notes

**Comment by LearZhou** [comment]
用OpenBSD系統老版本的go 1.6.2編譯成功，運行中...

**Comment by badO1a5A90** [comment]
待go发布新版后也会更新一次,这个先close了

**Comment by badO1a5A90** [comment]
Xray-core v1.4.3 已用 Go v1.17.1 重新编译并发布

下载地址不变
https://github.com/XTLS/Xray-core/releases/tag/v1.4.3

本次重新编译发布仅为了解决 Go v1.17 的 bug 引起的交叉编译问题,无其他任何变化

Go 已发布 v1.17.1, 理论上解决了交叉编译可能产生的问题 

~~- Go v1.17 编译时, 某些版本,比如android-arm64-v8a, 可能会有问题导致无法运行~~
  ~~1. 原因出在上游. 也即go本身的原因, go目前版本有 bug 导致交叉编译可能产生问题, 参见 https://github.com/golang/go/issues/47760.~~
  ~~2. go 已经在 https://github.com/golang/go/commit/47a57bc4f0c6a2b7ac12d4eed4ce305446654459 修复,~~
  ~~3. 之前暂时的方式是可以使用 linux 的对应版本~~

已重新用 Go v1.17.1 重新编译并发布.

如果您在 Xray v1.4.3 最初发布时下载对应版本出现无法运行问题的, 可重新下载对应版本并尝试运行.
如果您在 Xray v1.4.3 最初发布时下载版本运行后无问题的, 则可以无需关心.

PS: 运行 xray version 您可以看到编译所使用的 Go 的版本号
