### ISSUE TITLE
當關掉mux時，1.4.3版做客戶端仍然會經常出現以下警告

### ISSUE THREAD

**Issue by LearZhou** [XTLS/Xray-core#702]
2021/09/09 02:35:52 [Warning] [2077498016] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxx.xxx.xx/v2ray):  > dial tcp: operation was canceled] > common/retry: all retry attempts failed

以上客戶端方警告出現時，mux設置如下：
      "mux": {
        "concurrency": -1,
        "enabled": false
      },

目前最佳體驗是打開mux，但concurrency設置為1:
      "mux": {
        "concurrency": 1,
        "enabled": true
      },

以前報告過這個問題，可能是跟mux配合有關，沒處理好mux模塊完全關閉的情況，希望以後能夠得到改善，能夠在mux完全關閉的情況下也不出現warnings。

由於很多（第三方）客戶端不一定能夠隨心所欲設置mux，所以解決這個問題也會有實際的意義。

**Comment by yuhan6665** [comment]
Not a real issue, you can turn off log
