### ISSUE TITLE
无法正常运行

### ISSUE THREAD

**Issue by RSJWY** [XTLS/Xray-core#703]
Xray 1.4.0 (Xray, Penetrates Everything.) Custom (go1.16.2 linux/amd64)

A unified platform for anti-censorship.

2021/09/09 12:40:19 [Info] infra/conf/serial: Reading config: bin/config.json

Failed to start: app/proxyman/inbound: failed to listen TCP on 52120 > transport/internet: failed to listen on address: 1.117.87.137:52120 > transport/internet/tcp: failed to listen TCP on 1.117.87.137:52120 > listen tcp 1.117.87.137:52120: bind: cannot assign requested address

**Comment by badO1a5A90** [comment]
请附上配置和环境说明

**Comment by yuhan6665** [comment]
Close due to lack of information
