### ISSUE TITLE
xray的代理规则

### ISSUE THREAD

**Issue by GleenJi** [XTLS/Xray-core#706]
突然发现steam的代理规则对steam是直连的啊，包括v2ray，都是直连，ss的代理规则对steam是能够代理的，想问一下如果想自定义修改geo该怎么改？或者在routing里应添加哪些域名或者ip？萌新不会找代理规则，求指点

**Comment by ztoofar** [comment]
geo里面添加或者修改有点麻烦的，路由规则里面添加域名或者ip文档里面都有写的。

**Comment by yuhuangniu** [comment]
routing里直连的部分写上：geosite:steam

**Comment by GleenJi** [comment]
> geo里面添加或者修改有点麻烦的，路由规则里面添加域名或者ip文档里面都有写的。

会写，就是不知道具体steam的所有域名或者ip

**Comment by chika0801** [comment]
使用https://github.com/Loyalsoldier/v2ray-rules-dat 的数据库文件

    "routing": {
        "domainStrategy": "Asls",
        "rules": [
            {
                "type": "field",
                "inboundTag": [
                    "dns-in"
                ],
                "outboundTag": "dns-out"
            },
            {
                "type": "field",
                "domain": [
                    "geosite:category-ads-all"
                ],
                "outboundTag": "block"
            },
            {
                "type": "field",
                "domain": [
                    "geosite:cn",
                    "geosite:category-games@cn"
                ],
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "ip": [
                    "geoip:cn",
                    "geoip:private"
                ],
                "outboundTag": "direct"
            }
        ]
    },

我的规则，steam客户端会被代理，下载时走cdn节点是直连效果。

**Comment by IIIlllIIllIIIll** [comment]
> > routing里直连的部分写上：geosite:steam
> 
> 我只是想代理steamwebhelper.exe，而不想代理steam的下载，geosite:steam好像是连下载都代理了

先写```geosite:steam@cn```和```geosite:cn```直连，后面写```geosite:steam```代理
https://github.com/v2fly/domain-list-community/blob/009bb932a85998f4233916bb762ae9a6cd0d2ffe/data/steam#L13-L32

**Comment by GleenJi** [comment]
> > geo里面添加或者修改有点麻烦的，路由规则里面添加域名或者ip文档里面都有写的。
> 
> 会写，就是不知道具体steam的所有域名或者ip

找到了

**Comment by GleenJi** [comment]
> 使用https://github.com/Loyalsoldier/v2ray-rules-dat 的数据库文件
> 
> ```
> "routing": {
>     "domainStrategy": "Asls",
>     "rules": [
>         {
>             "type": "field",
>             "domain": [
>                 "geosite:category-ads-all"
>             ],
>             "outboundTag": "block"
>         },
>         {
>             "type": "field",
>             "domain": [
>                 "geosite:cn",
>                 "geosite:category-games@cn"
>             ],
>             "outboundTag": "direct"
>         },
>         {
>             "type": "field",
>             "ip": [
>                 "geoip:cn",
>                 "geoip:private"
>             ],
>             "outboundTag": "direct"
>         }
>     ]
> },
> ```
> 
> 我用的路由规则，steam客户端会被代理，下载文件时走cdn节点，是直连效果。具体写上面的规则文件里的说明

你的xray是默认代理steam的吗？我看你这个规则是所有cn部分直连，不知道为什么我用xray+netch代理steam社区和动态都是无法访问，用ss+proxifier代理steamwebhelper.exe就可以代理

**Comment by chika0801** [comment]
> > 使用https://github.com/Loyalsoldier/v2ray-rules-dat 的数据库文件
> > ```
> > "routing": {
> >     "domainStrategy": "Asls",
> >     "rules": [
> >         {
> >             "type": "field",
> >             "domain": [
> >                 "geosite:category-ads-all"
> >             ],
> >             "outboundTag": "block"
> >         },
> >         {
> >             "type": "field",
> >             "domain": [
> >                 "geosite:cn",
> >                 "geosite:category-games@cn"
> >             ],
> >             "outboundTag": "direct"
> >         },
> >         {
> >             "type": "field",
> >             "ip": [
> >                 "geoip:cn",
> >                 "geoip:private"
> >             ],
> >             "outboundTag": "direct"
> >         }
> >     ]
> > },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我用的路由规则，steam客户端会被代理，下载文件时走cdn节点，是直连效果。具体写上面的规则文件里的说明
> 
> 你的xray是默认代理steam的吗？我看你这个规则是所有cn部分直连，不知道为什么我用xray+netch代理steam社区和动态都是无法访问，用ss+proxifier代理steamwebhelper.exe就可以代理

我用我的配置，steam程序，浏览各主页，都是代理状态。下载是直连。没用netch，是用的v2rayn。

**Comment by GleenJi** [comment]
> 
> 
> geo里面添加或者修改有点麻烦的，路由规则里面添加域名或者ip文档里面都有写的。

找到原因了，是netch有问题，，并不是xray的代理规则不能代理steam

**Comment by GleenJi** [comment]
> 
> 
> 使用https://github.com/Loyalsoldier/v2ray-rules-dat 的数据库文件
> 
> ```
> "routing": {
>     "domainStrategy": "Asls",
>     "rules": [
>         {
>             "type": "field",
>             "domain": [
>                 "geosite:category-ads-all"
>             ],
>             "outboundTag": "block"
>         },
>         {
>             "type": "field",
>             "domain": [
>                 "geosite:cn",
>                 "geosite:category-games@cn"
>             ],
>             "outboundTag": "direct"
>         },
>         {
>             "type": "field",
>             "ip": [
>                 "geoip:cn",
>                 "geoip:private"
>             ],
>             "outboundTag": "direct"
>         }
>     ]
> },
> ```
> 
> 我用的路由规则，steam客户端会被代理，下载文件时走cdn节点，是直连效果。具体写上面的规则文件里的说明

找到原因了，是netch有问题，，并不是xray的代理规则不能代理steam

**Comment by GleenJi** [comment]
> 
> 
> > > routing里直连的部分写上：geosite:steam
> > 
> > 
> > 我只是想代理steamwebhelper.exe，而不想代理steam的下载，geosite:steam好像是连下载都代理了
> 
> 先写`geosite:steam@cn`直连，后面写`geosite:steam`代理

找到原因了，是netch有问题，，并不是xray的代理规则不能代理steam

**Comment by GleenJi** [comment]
找到原因了，是netch有问题，，并不是xray的代理规则不能代理steam，我得看看为什么netch代理steam有问题
