### ISSUE TITLE
树莓派4B用VLESS-TCP+XTLS满载能到900M多一点，估计是上限了

### ISSUE THREAD

**Issue by shenlijun** [XTLS/Xray-core#71]
截图是实际线路测试结果，总体来说个人不推荐树莓派4B，如果其他可选的开发板能稳定运行的情况下，性价比都比树莓派要好.大家可以尝试下其它替代品

CPU没交授权费没有AES，预计发热问题也不能持久，改天试一下香橙派4B，那个据说有AES，U本身应该也强一些（它还在路上）
![捕获](https://user-images.githubusercontent.com/8860591/102090131-0a8d2b00-3e58-11eb-95d4-6da59fbfd988.PNG)

500m以下的线路应该没问题吧，但这种情况下树莓派性价比就不太行了。据说R2S之类的也能跑上来，当然俺都没试过-_-#
![捕获1](https://user-images.githubusercontent.com/8860591/102090984-2218e380-3e59-11eb-9877-94e99f45b74b.PNG)

**Comment by shenlijun** [comment]
splice的。

其实大家可以都把手头上的设备测试看看，这样后来者非土豪可以按需选择适合自己的

**Comment by defead** [comment]
弱弱的问一句，你家的梯子有1G高么？

**Comment by badO1a5A90** [comment]
第一张图看起来榨干了。。。
话说这个成绩在一众硬件中相比较，应该也还算可以了吧

**Comment by shenlijun** [comment]
> 第一张图看起来榨干了。。。
> 话说这个成绩在一众硬件中相比较，应该也还算可以了吧

其实是可以的，但是总觉得有点高不成低不就，千兆差点意思，不跑千兆又有更便宜的替代

arm8标准要求要有aes，但是bcm2711没有，这个太骚了……

**Comment by hankclc** [comment]
树莓派4B现在只要200多了

**Comment by tritu** [comment]
Then this report should be run in chacha20 not AES. (When xtls can’t detect HasAES, it will use chacha20 cipher)

**Comment by shenlijun** [comment]
> 树莓派4B现在只要200多了

300多的香橙派更值得一试

**Comment by shenlijun** [comment]
> Then this report should be run in chacha20 not AES. (When xtls can’t detect HasAES, it will use chacha20 cipher)

Anyway， 900mb/s with 100% usage, maybe not a good choice yet
