### ISSUE TITLE
日志文件太大了

### ISSUE THREAD

**Issue by shuiliu11** [XTLS/Xray-core#714]
日志文件现在越来越大了，是不是只能手动删除，能不能只保留一周的，或者有其它方法？

**Comment by chika0801** [comment]
搜到这个命令 logrotate https://wsgzao.github.io/post/logrotate/ 我不会操作

**Comment by zhfreal** [comment]
man logrotate.conf，/etc/logrotate.d/下新增配置文件，自动处理日志。
比如：
/var/log/v2ray/*.log
{
        su v2ray v2ray
        rotate 7
        daily
        missingok
        notifempty
        delaycompress
        compress
        create 0640 v2ray v2ray
        postrotate
                /bin/systemctl restart v2ray
        endscript
}

**Comment by chika0801** [comment]
> man logrotate.conf，/etc/logrotate.d/下新增配置文件，自动处理日志。
> 比如：
> /var/log/v2ray/*.log
> {
> su v2ray v2ray
> rotate 7
> daily
> missingok
> notifempty
> delaycompress
> compress
> create 0640 v2ray v2ray
> postrotate
> /bin/systemctl restart v2ray
> endscript
> }



> man logrotate.conf，/etc/logrotate.d/下新增配置文件，自动处理日志。
> 比如：
> /var/log/v2ray/*.log
> {
> su v2ray v2ray
> rotate 7
> daily
> missingok
> notifempty
> delaycompress
> compress
> create 0640 v2ray v2ray
> postrotate
> /bin/systemctl restart v2ray
> endscript
> }

感谢你，已经结合文章看明白了

**Comment by Bit0r** [comment]
这是按照大小来压缩的，超过20M会自动压缩
```cfg
/var/log/xray/*.log {
	size 20M
	rotate 5
	missingok
	notifempty
	create 640 nobody adm
	compress
	postrotate
		systemctl restart xray
	endscript
}
```

**Comment by PMExtra** [comment]
systemctl restart xray 会切断当前所有连接，是否有一种方法重新打开日志文件但是不重启进程？类似nginx接受HUP信号量

**Comment by wy580477** [comment]
> systemctl restart xray 会切断当前所有连接，是否有一种方法重新打开日志文件但是不重启进程？类似nginx接受HUP信号量

不在配置文件里面指定日志位置，不保存日志文件，用journalctl -u xray 看日志就行了。journald会自动控制日志体积。

**Comment by PMExtra** [comment]
> > systemctl restart xray 会切断当前所有连接，是否有一种方法重新打开日志文件但是不重启进程？类似nginx接受HUP信号量
> 
> 不在配置文件里面指定日志位置，不保存日志文件，用journalctl -u xray 看日志就行了。journald会自动控制日志体积。

确实是一种思路，但是我这里xray服务器需要存储和归档审计日志（并非用作梯子，而是企业内部代理）。虽然可以定期从journald导出，但这又增加了额外的复杂性。journald也没办法单独对xray启用持久化。

**Comment by wy580477** [comment]
> 确实是一种思路，但是我这里xray服务器需要存储和归档审计日志（并非用作梯子，而是企业内部代理）。虽然可以定期从journald导出，但这又增加了额外的复杂性。journald也没办法单独对xray启用持久化。

journald 默认是会 forward 到 syslog 的，你可以考虑从 syslog 里面过滤出来。

还有些更专业的方案，比如 Promtail + loki 啥的。。。

**Comment by liuhgiceblood** [comment]
非常简单，多看文档吧！
https://xtls.github.io/config/api.html#apiobject
