### ISSUE TITLE
移动4g下无法正常代理

### ISSUE THREAD

**Issue by fyfh** [XTLS/Xray-core#718]
wifi下正常，试过trojan，一样的问题

**Comment by fyfh** [comment]
iphone 4g网络不行

**Comment by MarksonHon** [comment]
@fyfh 我觉得中国移动通信这家公司在歧视你，换我们中国网络联合通信有限公司的服务吧。🐶头

**Comment by rickrolled502** [comment]
我们中国电信集团有限公司欢迎您的到来，现在携号转网可享受 9.9 折优惠。

**Comment by hmol233** [comment]
🤔

**Comment by dev4u** [comment]
入网国际星链通信公司的不香？

**Comment by yaott2020-666** [comment]
看看ip是不是被移动墙了

**Comment by fyfh** [comment]
是shadowrocket的原因。。。

**Comment by fyfh** [comment]
shadowrocket里设置dns-server = 223.5.5.5
