### ISSUE TITLE
对于服务器端的配置文件config的sniffing

### ISSUE THREAD

**Issue by GleenJi** [XTLS/Xray-core#72]
我看example里面的一些例子，服务器端都没有sniffing，我知道sniffing是在inbounds里面，现在又有了回落分流功能，在使用回落分流的情况下，这个sniffing加在哪里？
比如：

inbounds:[

{fallbacks:[  {dest:port1},  {dest:port2},  …]},   A

{port1},   B

{port2},   C
…
]

难道得在每个回落的inbounds元素里面都加一个sniffing (比如B  C  …这些个inbounds元素都添加sniffing)？还是说只需添加一个（仅在A里面添加sniffing就行）？

（提一点我在客户端的config inbounds里面添加了sniffing，用的socks协议。。。）

这个sniffing我理解的不是太透彻，只是大概知道貌似是从流量中分辨内容，进而使用dns分流，最直接的体现就是用dns分流看奈飞，不过是在客户端开启了sniffing，服务器端并没有sniffing，能看奈飞，如果把客户端的sniffing关掉，服务器端也没有sniffing的情况下，就不能看显示使用代理了。。。那么这个sniffing不在客户端开启，只在服务器端开启行不行？（因为有的代理软件比如ss+v2ray plugin不支持sniffing吧）因此想知道如果在服务器端开启sniffing，在有回落分流的情况下这个sniffing放在哪？

还有一点疑问，我尝试了一下，在客户端，服务器端都关闭sniffing的情况下，貌似不影响Routing的判断？所以这个sniffing的具体功能是什么，什么时候发挥作用，理解的不透彻，期望有大佬可以说的更明白一些，谢谢

**Comment by badO1a5A90** [comment]
流量探测主要作用是用在透明代理等用途.
他的一个典型工作流程是这样的.
比如你有一个设备上网,去访问abc.com,
首先设备通过DNS查询得到abc.com是1.2.3.4,那么他会向1.2.3.4去发起连接.
透明代理不设置嗅探的话,收到的连接请求是1.2.3.4,是不能走域名规则的路由分流的.
透明代理设置了siffer,处理这个流量时,会 从这个流量的数据中,嗅探出域名,abc.com
然后把1.2.3.4重置为abc.com.路由就可以根据域名去走路由的规则分流,或者做更多的事情.

因为变成了一个向abc.com请求的连接,就可以做更多的事情,包括路由域名规则分流,重新做DNS解析等等...
还有一个siffer的选择配置是bt,可以嗅探bt流量的标识,然后路由中可以根据bt来做规则,比如服务端用来拦截,比如客户端固定转发到某个VPS去代理.

**Comment by GleenJi** [comment]
> 
> 
> 流量探测主要作用是用在透明代理等用途.
> 他的一个典型工作流程是这样的.
> 比如你有一个设备上网,去访问abc.com,
> 首先设备通过DNS查询得到abc.com是1.2.3.4,那么他会向1.2.3.4去发起连接.
> 透明代理不设置嗅探的话,收到的连接请求是1.2.3.4,是不能走域名规则的路由分流的.
> 透明代理设置了siffer,处理这个流量时,会 从这个流量的数据中,嗅探出域名,abc.com
> 然后把1.2.3.4重置为abc.com.路由就可以根据域名去走路由的规则分流,或者做更多的事情.
> 
> 因为变成了一个向abc.com请求的连接,就可以做更多的事情,包括路由域名规则分流,重新做DNS解析等等...
> 还有一个siffer的选择配置是bt,可以嗅探bt流量的标识,然后路由中可以根据bt来做规则,比如服务端用来拦截,比如客户端固定转发到某个VPS去代理.

我太小白了，是不是浏览器在访问一个网址的时候，已经先把域名解析成ip了，然后才把流量发送到v2ray，所以如果没有sniffing流量探测，v2ray在传输流量的时候根本不知道域名，那么v2ray路由的域名分流规则，还有v2ray的dns功能就起不到作用了。。。
我之前一直以为v2ray接收的流量直接包含域名了，所以才有疑问这个sniffing到底起到了什么作用（总是感觉好像没用），主要是我一直没搞懂从浏览器到v2ray的流量传递过程，其实是浏览器已经预先把域名解析成ip了，解析后才把流量给了v2ray，所以v2ray接收到的是ip流量，是不包含域名流量的，需要靠sniffing再嗅探出域名，整个过程也就是：
domain----浏览器------>>ip--------v2ray sniffing------>>domain+ip
大佬，我这么理解对不
这也就给我整明白了为什么我看奈飞服务端不用开sniffing，只要客户端开启sniffing就行了，然后在服务端配置dns分流功能，解析奈飞域名，最终就可以成功看奈飞了

**Comment by GleenJi** [comment]
> 
> 
> 流量探测主要作用是用在透明代理等用途.
> 他的一个典型工作流程是这样的.
> 比如你有一个设备上网,去访问abc.com,
> 首先设备通过DNS查询得到abc.com是1.2.3.4,那么他会向1.2.3.4去发起连接.
> 透明代理不设置嗅探的话,收到的连接请求是1.2.3.4,是不能走域名规则的路由分流的.
> 透明代理设置了siffer,处理这个流量时,会 从这个流量的数据中,嗅探出域名,abc.com
> 然后把1.2.3.4重置为abc.com.路由就可以根据域名去走路由的规则分流,或者做更多的事情.
> 
> 因为变成了一个向abc.com请求的连接,就可以做更多的事情,包括路由域名规则分流,重新做DNS解析等等...
> 还有一个siffer的选择配置是bt,可以嗅探bt流量的标识,然后路由中可以根据bt来做规则,比如服务端用来拦截,比如客户端固定转发到某个VPS去代理.

还有一个是，如果在服务端配置sniffing，该配置在哪？因为服务端用了回落分流功能，是配置在主inbounds里，就那个A里面，还是配置在回落分流后的分inbounds里面，比如B，C，D，.....
sniffing直接配置在主inbounds里会不会因为流量直接回落分流了而导致sniffing不起作用？

**Comment by badO1a5A90** [comment]
> 我太小白了，是不是浏览器在访问一个网址的时候，已经先把域名解析成ip了，然后才把流量发送到v2ray，所以如果没有sniffing流量探测，v2ray在传输流量的时候根本不知道域名，那么v2ray路由的域名分流规则，还有v2ray的dns功能就起不到作用了。。。
> 我之前一直以为v2ray接收的流量直接包含域名了，所以才有疑问这个sniffing到底起到了什么作用（总是感觉好像没用），主要是我一直没搞懂从浏览器到v2ray的流量传递过程，其实是浏览器已经预先把域名解析成ip了，解析后才把流量给了v2ray，所以v2ray接收到的是ip流量，是不包含域名流量的，需要靠sniffing再嗅探出域名，整个过程也就是：
> domain----浏览器------>>ip--------v2ray sniffing------>>domain+ip
> 大佬，我这么理解对不
> 这也就给我整明白了为什么我看奈飞服务端不用开sniffing，只要客户端开启sniffing就行了，然后在服务端配置dns分流功能，解析奈飞域名，最终就可以成功看奈飞了

不完全是这样,和具体使用方法有关.我上面举例的是透明代理的情况下的过程.和你理解的基本也是一致的.

但如果是在本地运行xray,监听了一个socks端口,假设是10086吧. 然后浏览器里面设置代理,指向127.0.0.1:10086.
这样的情况下.浏览器是会把请求直接传递给xray,并不会做域名解析,xray拿到的就是对这个域名的请求,然后根据路由规则进行分流,如果是走代理,那么就直接发往代理了,如果是直连,那么使用内置DNS/系统DNS(和freedom的domainStrategy有关)进行DNS解析,然后对地址发起连接访问.

这种情况下,不需要sniffing,也就是你说的（总是感觉好像没用）

一般自己用的话,服务端确实没有需要sniffing的场景

**Comment by GleenJi** [comment]
> 
> 
> > 我太小白了，是不是浏览器在访问一个网址的时候，已经先把域名解析成ip了，然后才把流量发送到v2ray，所以如果没有sniffing流量探测，v2ray在传输流量的时候根本不知道域名，那么v2ray路由的域名分流规则，还有v2ray的dns功能就起不到作用了。。。
> > 我之前一直以为v2ray接收的流量直接包含域名了，所以才有疑问这个sniffing到底起到了什么作用（总是感觉好像没用），主要是我一直没搞懂从浏览器到v2ray的流量传递过程，其实是浏览器已经预先把域名解析成ip了，解析后才把流量给了v2ray，所以v2ray接收到的是ip流量，是不包含域名流量的，需要靠sniffing再嗅探出域名，整个过程也就是：
> > domain----浏览器------>>ip--------v2ray sniffing------>>domain+ip
> > 大佬，我这么理解对不
> > 这也就给我整明白了为什么我看奈飞服务端不用开sniffing，只要客户端开启sniffing就行了，然后在服务端配置dns分流功能，解析奈飞域名，最终就可以成功看奈飞了
> 
> 不完全是这样,和具体使用方法有关.我上面举例的是透明代理(浏览器不设置代理/电视盒子/手机,直接通过透明代理上网的场景)的情况下的过程.和你理解的基本也是一致的.
> 
> 但如果是在本地运行xray,监听了一个socks端口,假设是10086吧. 然后浏览器里面设置代理,指向127.0.0.1:10086.
> 这样的情况下.浏览器是会把请求直接传递给xray,并不会做域名解析,xray拿到的就是对这个域名的请求,然后根据路由规则进行分流,如果是走代理,那么就直接发往代理了,如果是直连,那么使用内置DNS/系统DNS(和freedom的domainStrategy有关)进行DNS解析,然后对地址发起连接访问.
> 
> 这种情况下,不需要sniffing,也就是你说的（总是感觉好像没用）
> 
> 一般自己用的话,服务端确实没有需要sniffing的场景

非常感谢大佬，那个：
如果在服务端配置sniffing，该配置在哪？因为服务端用了回落分流功能，是配置在主inbounds里，就那个A里面，还是配置在回落分流后的分inbounds里面，比如B，C，D，.....
sniffing直接配置在主inbounds里会不会因为流量直接回落分流了而导致sniffing不起作用？

**Comment by jyf007** [comment]
can i remove the sniffing part,my inbounds is broken
my client code
```json
{
  "log": {
    "loglevel": "error"
  },
  "inbounds": [{
      "port": 1080,
      "listen": "0.0.0.0",
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": "127.0.0.1"
      }},{
      "port": "8118",
      "listen": "0.0.0.0",
      "protocol": "http"
    }],
  "outbounds": [{
      "protocol": "vless",
      "settings": {
        "vnext": [{
            "address": "0.0.0.0",
            "port": 0,
            "users": [{
                "id": "UUID",
                "flow": "xtls-rprx-direct",
  "encryption": "none",
                "level": 0
              }]
          }]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
            "serverName": "fake"
        },
        "allowInsecure": "true"
      }
  }]   
}
```

**Comment by jyf007** [comment]
@jyf007 here it is
