### ISSUE TITLE
[Bug] xray开启后, 客户端CPU占用率会非常高, 然后逐渐卡死

### ISSUE THREAD

**Issue by cary-sas** [XTLS/Xray-core#726]
非常奇怪的bug, **只有**在以下组合才会出现:
服务端 : **arm** ubuntu (甲骨文云) , 配合 caddy 
客户端 : arm v5 Linux (梅林路由器)
协议:  xtls , trojan -TCP , ss等**直连**协议. 

其他组合就不会出现这样的bug. 

服务端的json配置 文件格式是[这样](https://raw.githubusercontent.com/cary-sas/across/master/xray/etc/xray.json)
我也尝试看服务端的log , 也看不出什么特别的error.  
xray 最近的几个版本都这样.

**Comment by qnxsgwy** [comment]
go的ARMv5支持最近几个版本一直都有问题

**Comment by cary-sas** [comment]
我即使退回到1.3.1，问题还是存在。奇怪的是当服务端是x86架构的，客户端就没这个问题，（相同的配置文件）

**Comment by cary-sas** [comment]
找到了原因, 是由于选用了zerossl  ECC证书,换了RSA就解决了
