### ISSUE TITLE
关于shadowsocks+v2ray plugin

### ISSUE THREAD

**Issue by GleenJi** [XTLS/Xray-core#73]
我在使用ss+v2ray plugin，看example里面有一种dokodemo-door的配置，还有一种example没有的例子，是直接
protocol: shadowsocks   

streamSettings: ws

然后客户端ss的v2ray plugin设置mux=0

因为我发现dokodemo-door这种方式虽然配置文件需要写的多一些，但是mux可以设置为1及大于1的数值，而且测试延迟时明显要低，比如500ms

而第二种例子只能设置mux=0，测试延迟发现明显比第一种mux=1，2，3…高一倍，差不多就是1000多ms，正好是第一种的差不多2倍关系

在dokodemo-door的settings里面有一个
address:  v1.mux.cool
是不是这个东西就相当于
ss客户端可以开启mux=1，2，3…

使用过程中的疑惑，期望有大佬解释一下

**Comment by xqdoo00o** [comment]
想低延迟的话，加几行代码用tcp模式就好了

**Comment by GleenJi** [comment]
> 
> 
> 想低延迟的话，加几行代码用tcp模式就好了

主要我用的是垃圾vps，说实话套cdn才是正八经的给我提速了，选个好的cf ip小鸡默认4k都没问题，所以必需得用ws+tls+cdn模式，直接连接vps那就很难用了

**Comment by rprx** [comment]
v2 的 Mux 是 Mux over Protocol over Transport，即 Mux 除了会把传入的连接合为一条外，自己就是个代理协议

说实话我不熟悉 Shadowsocks 的 v2ray-plugin，之前我突然想做个 Xray-plugin，但有人建议我不要做

https://github.com/XTLS/Xray-core/commit/8f8f7dd66f1c116d55feaafde38f4c008592a70a 下个版本的 Xray-core 中 Shadowsocks 和 Trojan 都实现了 FullCone，直接用 Xray 自带的 SS 即可

**Comment by rprx** [comment]
对了，如果你开了 v2 的 Mux，则 UDP 也会由它处理，从而无法实现 FullCone。刚刚我看了下 Mux 的代码，只有加指令才能挽救。

下周我会写一个 UDP tunnel，即 UDP 聚合隧道，可以基于 Stream 或 Packet（无论是否可靠）。https://github.com/v2fly/v2ray-core/issues/112#issuecomment-688271288

**Comment by GleenJi** [comment]
> 
> 
> v2 的 Mux 是 Mux over Protocol over Transport，即 Mux 除了会把传入的连接合为一条外，自己就是个代理协议
> 
> 说实话我不熟悉 Shadowsocks 的 v2ray-plugin，之前我突然想做个 Xray-plugin，但有人建议我不要做
> 
> [8f8f7dd](https://github.com/XTLS/Xray-core/commit/8f8f7dd66f1c116d55feaafde38f4c008592a70a) 下个版本的 Xray-core 中 Shadowsocks 和 Trojan 都实现了 FullCone，直接用 Xray 自带的 SS 即可

👍

**Comment by bigbighill** [comment]
请教下，xray 服务端如何配置 实现 ss + v2ray-plugin

**Comment by guanhemeng** [comment]
> 请教下，xray 服务端如何配置 实现 ss + v2ray-plugin

不要总想着用插件，用原生客户端不更好吗......

**Comment by GleenJi** [comment]
> 
> 
> 请教下，xray 服务端如何配置 实现 ss + v2ray-plugin

我会两种模式，一种可以开启mux，一种必须是mux=0，我把mux=0的给你：
{
      "port": 12348,
      "listen": "127.0.0.1",     //因为是fallback到12348
      "protocol": "shadowsocks",
      "settings":
      {
        "method": "chacha20-ietf-poly1305",
        "password": "password"
      },
      "streamSettings": 
      {
        "network": "ws",
        "wsSettings": 
        {
          "path": "/path"
        }
      }
}

**Comment by bigbighill** [comment]
> > 请教下，xray 服务端如何配置 实现 ss + v2ray-plugin
> 
> 我会两种模式，一种可以开启mux，一种必须是mux=0，我把mux=0的给你：
> {
> "port": 12348,
> "listen": "127.0.0.1", //因为是fallback到12348
> "protocol": "shadowsocks",
> "settings":
> {
> "method": "chacha20-ietf-poly1305",
> "password": "password"
> },
> "streamSettings":
> {
> "network": "ws",
> "wsSettings":
> {
> "path": "/path"
> }
> }
> }

谢谢你的回复，上午也是这样配置的，好像没有成功，mux=0在哪里设置，shadowsocks for android v2ray-plugin 没有找到在哪设置的

另外请教下开启 mux的配置方式。

**Comment by bigbighill** [comment]
开启 mux 是不是类似这个帖子中的配置方式？
https://www.drsanwujiang.com/set-a-shield-to-your-plane-with-v2ray/

**Comment by xianren78** [comment]
> > > 请教下，xray 服务端如何配置 实现 ss + v2ray-plugin
> > 
> > 
> > 我会两种模式，一种可以开启mux，一种必须是mux=0，我把mux=0的给你：
> > {
> > "port": 12348,
> > "listen": "127.0.0.1", //因为是fallback到12348
> > "protocol": "shadowsocks",
> > "settings":
> > {
> > "method": "chacha20-ietf-poly1305",
> > "password": "password"
> > },
> > "streamSettings":
> > {
> > "network": "ws",
> > "wsSettings":
> > {
> > "path": "/path"
> > }
> > }
> > }
> 
> 谢谢你的回复，上午也是这样配置的，好像没有成功，mux=0在哪里设置，shadowsocks for android v2ray-plugin 没有找到在哪设置的
> 
> 另外请教下开启 mux的配置方式。

![Screenshot_20210202-205521](https://user-images.githubusercontent.com/26913311/106603343-2203ad00-6599-11eb-8749-285747fcce6b.png)

**Comment by bigbighill** [comment]
搞定了开启mux方式

把 address: v1.mux.cool  v1 写成了vl ，还有把 routing 规则调整了下

**Comment by GleenJi** [comment]
> 
> 
> > > 请教下，xray 服务端如何配置 实现 ss + v2ray-plugin
> > 
> > 
> > 我会两种模式，一种可以开启mux，一种必须是mux=0，我把mux=0的给你：
> > {
> > "port": 12348,
> > "listen": "127.0.0.1", //因为是fallback到12348
> > "protocol": "shadowsocks",
> > "settings":
> > {
> > "method": "chacha20-ietf-poly1305",
> > "password": "password"
> > },
> > "streamSettings":
> > {
> > "network": "ws",
> > "wsSettings":
> > {
> > "path": "/path"
> > }
> > }
> > }
> 
> 谢谢你的回复，上午也是这样配置的，好像没有成功，可能没有设置mux=0。
> 
> 另外请教下开启 mux的配置方式。

ss的vray-plugin必须加一项mux=0

**Comment by GleenJi** [comment]
> 
> 
> docker 布署，搞定了开启mux方式
> 
> 把 address: v1.mux.cool v1 写成了vl ，还有把 routing 规则调整了下

使用dokodemo-door麻烦许多，但是可以开启mux且必须mux!=0：
{
inbounds:[
{
{
      "port": 12347,
      "listen": "127.0.0.1",    //因为是fallback
      "protocol": "dokodemo-door",
      "settings":
      {
        "address": "v1.mux.cool"
      },
      "streamSettings": 
      {
        "network": "ws",
        "wsSettings": 
        {
          "path": "/path"
        }
      },
      "tag": "door"
    },
    {
      "port": 33333,
      "listen": "127.0.0.1",
      "protocol": "shadowsocks",
      "settings":
      {
        "method": "chacha20-ietf-poly1305",
        "password": "password"
      }
    }
}],
"routing": 
  {
    "rules": 
    [
      {
        "type": "field",
        "inboundTag":
        [
          "door"
        ],
        "outboundTag": "doorss"
      }
    ]
  },
"outbounds":
  [
    {
      "protocol": "freedom",
      "settings": 
      {
        "domainStrategy": "AsIs"
      },
      "tag": "direct"
    },
    {
      "protocol": "freedom",
      "settings": 
      {
        "redirect": "127.0.0.1:33333"
      },
      "tag": "doorss"
    }
  ]
}

**Comment by GleenJi** [comment]
> 
> 
> docker 布署，搞定了开启mux方式
> 
> 把 address: v1.mux.cool v1 写成了vl ，还有把 routing 规则调整了下

mux=0模式的ss+v2ray plugin比使用dokodemo-door方式代码精简太多了

**Comment by Ball727** [comment]
> 我在使用ss+v2ray plugin，看example里面有一种dokodemo-door的配置，还有一种example没有的例子，是直接 protocol: shadowsocks
> 
> streamSettings: ws
> 
> 然后客户端ss的v2ray plugin设置mux=0
> 
> 因为我发现dokodemo-door这种方式虽然配置文件需要写的多一些，但是mux可以设置为1及大于1的数值，而且测试延迟时明显要低，比如500ms
> 
> 而第二种例子只能设置mux=0，测试延迟发现明显比第一种mux=1，2，3…高一倍，差不多就是1000多ms，正好是第一种的差不多2倍关系
> 
> 在dokodemo-door的settings里面有一个 address: v1.mux.cool 是不是这个东西就相当于 ss客户端可以开启mux=1，2，3…
> 
> 使用过程中的疑惑，期望有大佬解释一下

请问您现在有办法把ss+v2rayplugin插件和xray结合起来吗？我想用这种ss节点 但是也想要xray的分流功能，如果有办法，能告诉我怎么实现吗？
