### ISSUE TITLE
请教一下，dns查询路由规则分流时，是根据dns服务器匹配路由规则，还是根据查询的域名匹配路由规则

### ISSUE THREAD

**Issue by alecthw** [XTLS/Xray-core#741]
例如
nslookup www.youtube.com 8.8.8.8

内置dns服务发出dns查询请求时，经过路由模块，是根据 8.8.8.8 匹配路由规则，还是根据 www.youtube.com 匹配路由规则？

问这个的原因，是为了解决多个代理下dns的分流问题

**Comment by Smoovsky** [comment]
内置DNS有自己的一套匹配DNS服务器的机制，匹配到DNS服务器后，根据DNS服务器的地址和协议再匹配路由规则

在使用内置DNS的时候：
nslookup www.youtube.com 8.8.8.8
的8.8.8.8会被无视（除非路由规则里排除了8.8.8.8:53导致没进入内置的DNS）
内置DNS使用 www.youtube.com进行匹配，假如配置为：
```
// ...
  "dns": {
    "servers": [
      "8.8.8.8",
      {
        "address": "1.1.1.1",
        "domains": ["domain:youtube.com"],
        "port": 53
      }
    ]
  }
// ...
```
则会使用1.1.1.1进行解析，至于怎么向1.1.1.1请求的，具体取决于出站路由的配置
