### ISSUE TITLE
透明代理按教程设置成功，成功后该机无法提供服务，从外网无法访问。如何配置？

### ISSUE THREAD

**Issue by AxIauk** [XTLS/Xray-core#747]
软硬件环境：家用NAS， Debian10
教程：透明代理（TProxy）配置教程 by a @BioniCosmos https://xtls.github.io/document/level-2/tproxy.html
路由器192.168.1.1 ，NAS 192.168.1.7 ，公网IPV4
功能需求：NAS 上有Nextcloud，Jellyfin for Docker等服务。启用透明代理后外网无法访问了。

如何修改路由才能实现？或者NAS还有一个网口设置成192.168.1.8，修改路由能实现吗？
感谢~1~

内网信息 
ip address | grep -w "inet" | awk '{print $2}'
127.0.0.1/8
192.168.0.3/24
192.168.1.7/24
172.17.0.1/16

路由配置：
ip rule add fwmark 1 table 100
ip route add local 0.0.0.0/0 dev lo table 100
iptables -t mangle -N XRAY
iptables -t mangle -A XRAY -d 10.0.0.0/8 -j RETURN
iptables -t mangle -A XRAY -d 100.64.0.0/10 -j RETURN
iptables -t mangle -A XRAY -d 127.0.0.0/8 -j RETURN
iptables -t mangle -A XRAY -d 169.254.0.0/16 -j RETURN
iptables -t mangle -A XRAY -d 172.16.0.0/12 -j RETURN
iptables -t mangle -A XRAY -d 192.0.0.0/24 -j RETURN
iptables -t mangle -A XRAY -d 224.0.0.0/4 -j RETURN
iptables -t mangle -A XRAY -d 240.0.0.0/4 -j RETURN
iptables -t mangle -A XRAY -d 255.255.255.255/32 -j RETURN
iptables -t mangle -A XRAY -d 192.168.0.0/16 -p tcp ! --dport 53 -j RETURN
iptables -t mangle -A XRAY -d 192.168.0.0/16 -p udp ! --dport 53 -j RETURN
iptables -t mangle -A XRAY -p tcp -j TPROXY --on-port 12345 --tproxy-mark 1
iptables -t mangle -A XRAY -p udp -j TPROXY --on-port 12345 --tproxy-mark 1
iptables -t mangle -A PREROUTING -j XRAY
iptables -t mangle -N XRAY_SELF
iptables -t mangle -A XRAY_SELF -d 10.0.0.0/8 -j RETURN
iptables -t mangle -A XRAY_SELF -d 100.64.0.0/10 -j RETURN
iptables -t mangle -A XRAY_SELF -d 127.0.0.0/8 -j RETURN
iptables -t mangle -A XRAY_SELF -d 169.254.0.0/16 -j RETURN
iptables -t mangle -A XRAY_SELF -d 172.16.0.0/12 -j RETURN
iptables -t mangle -A XRAY_SELF -d 192.0.0.0/24 -j RETURN
iptables -t mangle -A XRAY_SELF -d 224.0.0.0/4 -j RETURN
iptables -t mangle -A XRAY_SELF -d 240.0.0.0/4 -j RETURN
iptables -t mangle -A XRAY_SELF -d 255.255.255.255/32 -j RETURN
iptables -t mangle -A XRAY_SELF -d 192.168.0.0/16 -p tcp ! --dport 53 -j RETURN
iptables -t mangle -A XRAY_SELF -d 192.168.0.0/16 -p udp ! --dport 53 -j RETURN
iptables -t mangle -A XRAY_SELF -m mark --mark 2 -j RETURN
iptables -t mangle -A XRAY_SELF -p tcp -j MARK --set-mark 1
iptables -t mangle -A XRAY_SELF -p udp -j MARK --set-mark 1
iptables -t mangle -A OUTPUT -j XRAY_SELF

**Comment by BioniCosmos** [comment]
请使用 `iptables` 指令 `return` 相关服务。

e.g. 网站运行于 TCP 80 端口，只需添加 `iptables -t mangle -I XRAY_SELF -p tcp --sport 80 -j RETURN` 指令。若无效，继续添加 `iptables -t mangle -I XRAY -p tcp --dport 80 -j RETURN` 指令即可。

**Comment by AxIauk** [comment]
> 请使用 `iptables` 指令 `return` 相关服务。
> 
> e.g. 网站运行于 TCP 80 端口，只需添加 `iptables -t mangle -I XRAY_SELF -p tcp --sport 80 -j RETURN` 指令。若无效，继续添加 `iptables -t mangle -I XRAY -p tcp --dport 80 -j RETURN` 指令即可。

国庆快乐！感谢您的回复，指令有效，非常完美。
