### ISSUE TITLE
连github会出现 Fastly error: unknown domain

### ISSUE THREAD

**Issue by kousyougi** [XTLS/Xray-core#748]
连github.com的时后出现下面错误，这个月发生了两次。把xray关闭后重启就马上能连了。

Fastly error: unknown domain: github.com. Please check that this domain has been added to a service.
Details: cache-sjc10062-SJC

协定是xtls，有用fakedns，平台是openwrt x86-64，用tproxy连。

{
　"fakedns": {
　　"ipPool": "172.19.0.0/16",
　　"poolSize": 65535
　},
　"dns": {
　　"servers": [
　　　"fakedns"
　　]
　},
　"routing": {
　　"rules": [
　　　{
　　　　"type": "field",
　　　　"inboundTag": "transparent",
　　　　"outboundTag": "xtls"
　　　},
　　　{
　　　　"type": "field",
　　　　"inboundTag": "dns-in",
　　　　"outboundTag": "dns-out"
　　　}
　　]
　},
　"inbounds": [
　　{
　　　"tag": "transparent",
　　　"port": 12349,
　　　"protocol": "dokodemo-door",
　　　"settings": {
　　　　"network": "tcp",
　　　　"followRedirect": true
　　　},
　　　"sniffing": {
　　　　"enabled": true,
　　　　"destOverride": [
　　　　　"fakedns"
　　　　],
　　　　"metadataOnly": false
　　　},
　　　"streamSettings": {
　　　　"sockopt": {
　　　　　"tproxy": "tproxy"
　　　　}
　　　}
　　},
　　{
　　　"port": 5309,
　　　"tag": "dns-in",
　　　"protocol": "dokodemo-door",
　　　"settings": {
　　　　"address": "1.1.1.1",
　　　　"network": "udp"
　　　}
　　}
　],
　"outbounds": [
　　{
　　　"protocol": "vless",
　　　"tag": "xtls",
　　　"settings": {
　　　　"vnext": [
　　　　]
　　　},
　　　"streamSettings": {
　　　　"network": "tcp",
　　　　"security": "xtls",
　　　　"xtlsSettings": {
　　　　　"alpn": [
　　　　　　"h2"
　　　　　],
　　　　　"minVersion": "1.3",
　　　　　"enableSessionResumption": false,
　　　　　"certificates": [
　　　　　　{
　　　　　　　"usage": "verify",
　　　　　　　"certificateFile": ""
　　　　　　}
　　　　　],
　　　　　"disableSystemRoot": true,
　　　　　"serverName": ""
　　　　},
　　　　"sockopt": {
　　　　　"tcpFastOpen": true
　　　　}
　　　}
　　},
　　{
　　　"protocol": "dns",
　　　"tag": "dns-out"
　　}
　],
　"policy": {
　　"levels": {
　　　"0": {
　　　　"handshake": 4,
　　　　"connIdle": 3600,
　　　　"uplinkOnly": 0,
　　　　"downlinkOnly": 0,
　　　　"statsUserUplink": false,
　　　　"statsUserDownlink": false,
　　　　"bufferSize": 5120
　　　}
　　}
　}
}

**Comment by ljluestc** [comment]
```
#!/bin/sh

# 检查DNS配置是否正确
echo "检查DNS配置是否正确..."
# 替换以下内容为你的DNS服务器配置
your_dns_servers="8.8.8.8 8.8.4.4"
for dns_server in $your_dns_servers
do
    if ! nslookup github.com $dns_server >/dev/null 2>&1; then
        echo "无法解析域名 github.com 使用 DNS 服务器 $dns_server"
    else
        echo "DNS 服务器 $dns_server 正常解析 github.com"
        break
    fi
done

# 重启DNS服务
echo "尝试重启DNS服务..."
# 替换以下命令为你的DNS服务重启命令
# 通常可以使用以下命令重启DNS服务
# /etc/init.d/dnsmasq restart
# /etc/init.d/ubus restart
/etc/init.d/dnsmasq restart
/etc/init.d/ubus restart
sleep 5  # 等待5秒以确保DNS服务已重启
echo "DNS服务已重启"

# 检查DNS服务器
echo "检查DNS服务器..."
your_dns_servers="8.8.8.8 8.8.4.4 1.1.1.1"
for dns_server in $your_dns_servers
do
    if ! nslookup github.com $dns_server >/dev/null 2>&1; then
        echo "无法解析域名 github.com 使用 DNS 服务器 $dns_server"
    else
        echo "DNS 服务器 $dns_server 正常解析 github.com"
        break
    fi
done

# 清除DNS缓存
echo "清除DNS缓存..."
# 替换以下命令为你的DNS缓存清除命令
# 通常可以使用以下命令清除DNS缓存
# /etc/init.d/dnsmasq restart
# /etc/init.d/ubus restart
/etc/init.d/dnsmasq restart
/etc/init.d/ubus restart
sleep 5  # 等待5秒以确保DNS服务已重启
echo "DNS缓存已清除"

# 检查Fastly服务状态
echo "检查Fastly服务状态..."
# 使用curl检查Fastly服务状态
if curl -s https://status.fastly.com/ | grep -q "All systems operational"; then
    echo "Fastly服务正常"
else
    echo "Fastly服务可能存在问题，请检查 https://status.fastly.com/ 以获取更多信息"
fi

# 检查网络防火墙/代理
echo "检查网络防火墙/代理..."
# 确保没有网络防火墙或代理阻止DNS请求
# 如果你使用防火墙或代理，请检查其配置

# 检查Xray配置
echo "检查Xray配置..."
# 如果使用Xray，请确保其DNS设置正确
# 检查Xray配置文件以查看DNS相关设置

# 启用DNS日志
echo "启用DNS日志..."
# 替换以下命令为你的DNS日志启用命令
# 通常可以通过修改 /etc/config/dhcp 文件启用DNS日志
# 将 option logqueries '0' 更改为 option logqueries '1'
# /etc/init.d/dnsmasq restart
# /etc/init.d/ubus restart
/etc/init.d/dnsmasq restart
/etc/init.d/ubus restart
sleep 5  # 等待5秒以确保DNS服务已重启
echo "DNS日志已启用"

# 更新路由器固件
echo "更新路由器固件..."
# 如果问题仍然存在，考虑更新路由器固件
# 访问路由器的管理界面，查找固件更新选项

# 完成
echo "诊断和修复DNS问题的步骤已完成。"

```
