### ISSUE TITLE
freedom出站时，B站部分图片无法加载

### ISSUE THREAD

**Issue by Cirn09** [XTLS/Xray-core#751]
访问部分B站图片会无法加载，哪些不能会报错似乎是随机的。过段时间后可能全部正常了，也可能换了一批图片无法加载。
而且只有B站有这个问题

比如https://i0.hdslb.com/bfs/archive/2706c40aafea50bbfb05fdbef513b2dc787961b5.jpg@336w_190h_1c.webp
走`freedom`协议时会报错`ERR_SSL_VERSION_OR_CIPHER_MISMATCH`
而走代理反而正常

### 报错信息
![image](https://user-images.githubusercontent.com/25722111/135762214-6a294460-7b3a-4943-afc2-c85bfb9d2c7e.png)

### 用Python requests访问的报错：
> SSLError: HTTPSConnectionPool(host='i0.hdslb.com', port=443): Max retries exceeded with url: /bfs/archive/2706c40aafea50bbfb05fdbef513b2dc787961b5.jpg@336w_190h_1c.webp (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))

如果需要的话我可以再抓段流量

### 版本信息：
```
Xray 1.4.5 (Xray, Penetrates Everything.) Custom (go1.17.1 linux/amd64)
A unified platform for anti-censorship.
```

### 相关配置片段：

```
{
  "inbounds": [
    {
      "tag": "dr_in",
      "listen": "0.0.0.0",
      "port": 51423,
      "protocol": "socks",
      "settings": {
        "udp": true
      }
    }
  ],


  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "dr_in"
        ],
        "outboundTag": "dr_out"
      }
  ],


  "outbounds": [
    {
      "tag": "dr_out",
      "protocol": "freedom",
      "settings": {},
      "streamSettings": {
        "udp": true
      }
    }
  ]
}
```

### 访问日志片段
```
2021/10/04 00:16:08 [Info] [117041995] proxy/socks: TCP Connect request to tcp:i0.hdslb.com:443
2021/10/04 00:16:08 [Info] [117041995] app/dispatcher: taking detour [dr_out] for [tcp:i0.hdslb.com:443]
2021/10/04 00:16:08 [Info] [117041995] proxy/freedom: opening connection to tcp:i0.hdslb.com:443
2021/10/04 00:16:08 [Info] [117041995] transport/internet/tcp: dialing TCP to tcp:i0.hdslb.com:443
2021/10/04 00:16:08 tcp:192.168.9.22:54588 accepted tcp:i0.hdslb.com:443 [dr_in -> dr_out]
2021/10/04 00:16:08 [Info] [230146831] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: connection ends > context canceled
2021/10/04 00:16:08 [Info] [559446909] proxy/socks: TCP Connect request to tcp:i2.hdslb.com:443
2021/10/04 00:16:08 [Info] [559446909] app/dispatcher: taking detour [dr_out] for [tcp:i2.hdslb.com:443]
2021/10/04 00:16:08 [Info] [559446909] proxy/freedom: opening connection to tcp:i2.hdslb.com:443
2021/10/04 00:16:08 tcp:192.168.9.22:59061 accepted tcp:i2.hdslb.com:443 [dr_in -> dr_out]
2021/10/04 00:16:08 [Info] [559446909] transport/internet/tcp: dialing TCP to tcp:i2.hdslb.com:443
2021/10/04 00:16:08 [Info] [2445679213] proxy/dokodemo: received request for 192.168.9.22:59062
```

**Comment by xqzr** [comment]
需要 `routing` 完整配置

**Comment by Cirn09** [comment]
> 需要 `routing` 完整配置

### `routing.json`
```
{
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "domain": [
            "geolocation-!cn"
        ],
        "inboundTag": [
          "stp_in",
          "tp_in"
        ],
        "outboundTag": "clash_out"
      },

      {
        "type": "field",
        "inboundTag": [
          "dr_in"
        ],
        "outboundTag": "dr_out"
      },

      {
        "type": "field",
        "domain": [
            "geosite:cn"
        ],
        "inboundTag": [
          "stp_in",
          "tp_in"
        ],
        "outboundTag": "dr_out"
      },
      {
        "type": "field",
        "ip": [
            "geoip:cn"
        ],
        "inboundTag": [
          "stp_in",
          "tp_in"
        ],
        "outboundTag": "dr_out"
      },

      {
        "type": "field",
        "inboundTag": [
          "stp_in",
          "tp_in",
          "fp_in"
        ],
        "outboundTag": "clash_out"
      }
    ],
    "balancers": []
  }
}
```

### `outbounds.json`
```
{
  "outbounds": [
    {
      "tag": "dr_out",
      "protocol": "freedom",
      "settings": {},
      "streamSettings": {
        "udp": true
      }
    },
    {
      "tag": "clash_out",
      "protocol": "socks",
      "settings": {
        "servers": [
          {
            "address": "127.0.0.1",
            "port": 51420,
            "level": 0
          }
        ]
      },
      "streamSettings": {
        "udp": true
      }
    }
  ]
}
```

**Comment by xqzr** [comment]
据文档：https://xtls.github.io/config/transport.html `streamSettings` 里 没有 `"udp": true`。
尝试 修改 `"tag": "dr_out"` 为
```json
{
    "tag": "dr_out",
    "protocol": "freedom"
}
```

**Comment by Cirn09** [comment]
> 据文档：https://xtls.github.io/config/transport.html `streamSettings` 里 没有 `"udp": true`。 尝试 修改 `"tag": "dr_out"` 为
> 
> ```json
> {
>     "tag": "dr_out",
>     "protocol": "freedom"
> }
> ```

改完之后问题依然存在

**Comment by GleenJi** [comment]
很好奇为什么你们写自己的配置文件，总是搞得花里胡哨、乱七八糟、不容易看懂。。。。。。。。。。。。
我的客户端配置文件，访问b站直连没问题
`{
  "log": 
  {
    "loglevel": "warning",
    "access": "location\\access.log",
    "error": "location\\error.log"
  },

  "inbounds": 
  [
    {
      "port": 10801,
      "listen": "127.0.0.1",     
      "protocol": "socks",
      "settings": 
      {
        "udp": true
      },
      "sniffing": 
      {
        "enabled": true,
        "destOverride": [ "http", "tls" ]
      }
    }
  ],

  "routing": 
  {
    "domainStrategy": "IPIfNonMatch",
    "domainMatcher": "mph",
    "rules": 
    [
      {
        "type": "field",
        "domain": 
        [
          "geosite:cn"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "ip": 
        [
          "geoip:cn",
          "geoip:private"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "domain": 
        [
          "domain",          
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "ip": 
        [
          "180.76.76.76",
          "2400:da00::6666",
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "outboundTag": "direct"
      }
    ]
  },

  "outbounds": 
  [
    {
      "protocol": "vless",
      "settings": 
      {
        "vnext": 
        [         
          {
            "address": "ip or mydomain",
            "port": 443,
            "users": 
            [
              {
                "id": "myid",
                "encryption": "none"
              }
            ]
          }
        ]
      },
      "streamSettings": 
      {
        "network": "ws",
        "wsSettings": 
        {
          "path": "/mypath?ed=2048",
          "headers": 
          {
            "Host": "mydomain"
          }
        },
        "security": "tls",
        "tlsSettings": 
        {
          "serverName": "mydomain",
          "fingerprint": "randomized"
        }     
      },
      "mux": 
      {
        "enabled": true,
        "concurrency": 8
      },
      "tag": "proxy"
    },    
    {
      "protocol": "freedom",
      "settings": 
      {
        "domainStrategy": "UseIP"
      },
      "tag": "direct"
    }
  ],

  "dns": 
  {    
    "servers": 
    [      
      "180.76.76.76",
      "2400:da00::6666",
      "223.5.5.5",
      "223.6.6.6",
      "2400:3200::1",
      "2400:3200:baba::1",
      "localhost"
    ]
  }
}`

**Comment by GleenJi** [comment]
很好奇为什么你们写自己的配置文件，总是搞得花里胡哨、乱七八糟、不容易看懂。。。。。。。。。。。。
我的客户端配置文件，访问b站直连没问题
`{
  "log": 
  {
    "loglevel": "warning",
    "access": "location\\access.log",
    "error": "location\\error.log"
  },

  "inbounds": 
  [
    {
      "port": 10801,
      "listen": "127.0.0.1",     
      "protocol": "socks",
      "settings": 
      {
        "udp": true
      },
      "sniffing": 
      {
        "enabled": true,
        "destOverride": [ "http", "tls" ]
      }
    }
  ],

  "routing": 
  {
    "domainStrategy": "IPIfNonMatch",
    "domainMatcher": "mph",
    "rules": 
    [
      {
        "type": "field",
        "domain": 
        [
          "geosite:cn"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "ip": 
        [
          "geoip:cn",
          "geoip:private"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "domain": 
        [
          "domain"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "ip": 
        [
          "180.76.76.76",
          "2400:da00::6666",
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "outboundTag": "direct"
      }
    ]
  },

  "outbounds": 
  [
    {
      "protocol": "vless",
      "settings": 
      {
        "vnext": 
        [
          {
            "address": "ip or my domain",
            "port": 443,
            "users": 
            [
              {
                "id": "my id",
                "encryption": "none"
              }
            ]
          }
        ]
      },
      "streamSettings": 
      {
        "network": "ws",
        "wsSettings": 
        {
          "path": "/my path?ed=2048",
          "headers": 
          {
            "Host": "my domain"
          }
        },
        "security": "tls",
        "tlsSettings": 
        {
          "serverName": "my domain",
          "fingerprint": "randomized"
        }     
      },
      "mux": 
      {
        "enabled": true,
        "concurrency": 8
      },
      "tag": "proxy"
    },    
    {
      "protocol": "freedom",
      "settings": 
      {
        "domainStrategy": "UseIP"
      },
      "tag": "direct"
    }
  ],

  "dns": 
  {    
    "servers": 
    [      
      "180.76.76.76",
      "2400:da00::6666",
      "223.5.5.5",
      "223.6.6.6",
      "2400:3200::1",
      "2400:3200:baba::1",
      "localhost"
    ]
  }
}`
