### ISSUE TITLE
使用actions自动编译出错，提示证书过期

### ISSUE THREAD

**Issue by ozersource** [XTLS/Xray-core#758]
使用actions自动编译出错，日志如下 

go: github.com/ghodss/yaml@v1.0.1-0.20190212211648-25d852aebe32: Get "https://goproxy.io/github.com/ghodss/yaml/@v/v1.0.1-0.20190212211648-25d852aebe32.mod": x509: certificate has expired or is not yet valid: current time 2021-10-09T00:23:26Z is after 2021-09-25T00:00:00Z

**Comment by Dimitri2020007** [comment]
已有相同问题

https://github.com/XTLS/Xray-core/issues/753

https://github.com/goproxyio/goproxy/issues/185

**Comment by yuhan6665** [comment]
Fixed by new proxy: proxy.golang.org
