### ISSUE TITLE
Suggestion: support for encrypted config file

### ISSUE THREAD

**Issue by bzgszlk** [XTLS/Xray-core#76]
Not that I can help bring it or know the how-to, but having plain text configurations lying around is just not desirable in many situations.

I know we have had the separate v2ctl interpreter to generate pb format for v2ray in the past veiling the bare-eye visible texts, it was not an encryption in the sense to hide from prying eyes.

Sorry for the English, but I wouldn't trust my Chinese IME to do not evil on sensitive matters like this, there can't be too many precautions.

**Comment by vCit2dmW** [comment]
首先，你完全可以使用Linux的权限控制系统来达到相同的效果，即对于其他程序来说，配置文件无法访问。
其次，加解密配置文件可自行编写脚本非常容易的实现，只需要在解密后调用Excel可执行程序读取，随后删除被解密的文件即可。
此外，对于非对称加密来说，密钥对需要保存于你的电脑上，这对于直接保存配置文件来说没有什么区别。如果使用对称加密，你还是可以通过脚本来简单实现这一点。
我个人不认为加密对于目前来说是一个必须的选项，因为Xray的场景下并不需要如此高的安全级别，常规的对于服务器的保护手段，以及权限控制系统，这些已经足够的有效。

**Comment by bzgszlk** [comment]
感谢你的回复，给了我另外一个思路。

**Comment by NutterChen** [comment]
recommend you to use a app from Africa NapsternetV

It can encrypt configuration files

**Comment by rprx** [comment]
感谢建议，但只加密配置文件似乎解决不了什么问题（除非有更完整可行的机制）

比如程序运行时需要加密后的配置文件和对应的解密密钥，两者通常存放在同一台电脑上，可以被同时泄露

或许启动 Xray 时手动输入密码？
