### ISSUE TITLE
uTLS模仿 Chrome 指纹的缺陷

### ISSUE THREAD

**Issue by Demon-Cat** [XTLS/Xray-core#763]
似乎uTLS中的指纹模仿，Client Hello 报文特征的确跟 Chrome 的非常的接近。但我似乎发现了uTLS模仿的 Chrome 指纹中，好像缺失了 application_settings 扩展

````
Extension: application_settings (len=5)
    Type: application_settings (17513)
    Length: 5
    ALPS Extension Length: 3
    Supported ALPN List
        Supported ALPN Length: 2
        Supported ALPN: h2
````

<img width="913" alt="11" src="https://user-images.githubusercontent.com/90884281/136772401-81b51dac-5f0f-4bba-a4f3-112e80f5cf66.png">

<img width="908" alt="22" src="https://user-images.githubusercontent.com/90884281/136772420-c29c27e7-b62b-418e-8605-5c67ddaf363f.png">

**Comment by yuhan6665** [comment]
This is an issue in utls. Close for now
