### ISSUE TITLE
xray 程序报错？

### ISSUE THREAD

**Issue by jekoie** [XTLS/Xray-core#765]
启动服务(2021/10/13 9:28:33)...
2021/10/13 09:28:34 Using default config:  D:\v2rayN\config.json
panic: Calling Domain() on an IPv4Address.

goroutine 1 [running]:
github.com/xtls/xray-core/common/net.ipv4Address.Domain(...)
	github.com/xtls/xray-core/common/net/address.go:132
github.com/xtls/xray-core/transport/internet/tcp.ListenTCP({0xea6930, 0xc00002a0a8}, {0xea7c38, 0xc0014f26c4}, 0x0, 0xc0003045a0, 0xc0014f4d80)
	github.com/xtls/xray-core/transport/internet/tcp/hub.go:50 +0x17f
github.com/xtls/xray-core/transport/internet.ListenTCP({0xea6930, 0xc00002a0a8}, {0xea7c38, 0xc0014f26c4}, 0x7b90, 0x1, 0xffffffffffffffff)
	github.com/xtls/xray-core/transport/internet/tcp_hub.go:75 +0x25e
github.com/xtls/xray-core/app/proxyman/inbound.(*tcpWorker).Start(0xc000253a40)
	github.com/xtls/xray-core/app/proxyman/inbound/worker.go:122 +0x88
github.com/xtls/xray-core/app/proxyman/inbound.(*AlwaysOnInboundHandler).Start(0xc000077c38)
	github.com/xtls/xray-core/app/proxyman/inbound/always.go:153 +0x65
github.com/xtls/xray-core/app/proxyman/inbound.(*Manager).Start(0xc000211640)
	github.com/xtls/xray-core/app/proxyman/inbound/inbound.go:100 +0xeb
github.com/xtls/xray-core/core.(*Instance).Start(0x38ea09)
	github.com/xtls/xray-core/core/xray.go:347 +0x1e5
main.executeRun(0x14ba8a0, {0xc000228170, 0x34d194, 0x18})
	github.com/xtls/xray-core/main/run.go:79 +0x138
github.com/xtls/xray-core/main/commands/base.Execute()
	github.com/xtls/xray-core/main/commands/base/execute.go:64 +0x639
main.main()
	github.com/xtls/xray-core/main/main.go:22 +0x1b3

Xray 1.4.5 (Xray, Penetrates Everything.) Custom (go1.17.1 windows/amd64)
A unified platform for anti-censorship.
2021/10/13 09:28:34 [Info] infra/conf/serial: Reading config: D:\v2rayN\config.json

**Comment by haimingz** [comment]
Same issue here. Client: V2rayU on MacOS arm

```txt
Xray 1.8.4 (Xray, Penetrates Everything.) Custom (go1.21.0 darwin/arm64)
A unified platform for anti-censorship.
2023/11/16 18:09:20 [Info] infra/conf/serial: Reading config: config.json
panic: Calling Domain() on an IPv4Address.
```

```json
{

  "log": {

    "loglevel": "warning",

    "error": "",

    "access": ""

  },

  "inbounds": [

    {

      "protocol": "socks",

      "settings": {

        "auth": "noauth",

        "udp": false

      },

      "port": "5000",

      "listen": "127.0.0.1"

    },

    {

      "listen": "127.0.0.1",

      "protocol": "http",

      "settings": {

        "timeout": 360

      },

      "port": "0"

    }

  ],

  "outbounds": [

    {

      "mux": {

        "concurrency": 8,

        "enabled": false

      },

      "streamSettings": {

        "network": "tcp",

        "security": "none",

        "tcpSettings": {

          "header": {

            "type": "none"

          }

        }

      },

      "settings": {

        "vnext": [

          {

            "port": 7381,

            "address": "XXXXXXXX",

            "users": [

              {

                "security": "aes-128-gcm",

                "id": "xxxxxxxx",

                "alterId": 0,

                "level": 0

              }

            ]

          }

        ]

      },

      "tag": "proxy",

      "protocol": "vmess"

    },

    {

      "settings": {

        "userLevel": 0,

        "domainStrategy": "UseIP"

      },

      "tag": "direct",

      "protocol": "freedom"

    },

    {

      "tag": "block",

      "settings": {

        "response": {

          "type": "none"

        }

      },

      "protocol": "blackhole"

    }

  ],

  "dns": {},

  "routing": {

    "settings": {

      "rules": [],

      "domainStrategy": "AsIs"

    }

  },

  "transport": {}

}
```

**Comment by haimingz** [comment]
It seems my problem is with the HTTP port. It works after I set it to 1081.

see:
https://github.com/XTLS/Xray-core/issues/473#issuecomment-812871881
