### ISSUE TITLE
nginx http分流VLESS(gRPC), 如何传递客户端IP给VLESS?

### ISSUE THREAD

**Issue by laughtale233** [XTLS/Xray-core#766]
nginx 配置:
```
http {
    server {    
        listen 443 ssl http2;    
        server_name domain.com;
        ...
        ssl
        ...
        location /serverName/Tun {
            grpc_pass 127.0.0.1:9000; 
            grpc_set_header X-Real-IP $remote_addr;
        }
    }
}
```
grpc可以通过设置header传递客户端IP,
Xray好像不能读取客户端IP.

**Comment by badO1a5A90** [comment]
> 另外如果使用nginx的stream模块转发grpc流量给Xray, 不能开启proxy_protocol, 否则线路不通. grpcSettings是否需要加上AcceptProxyProtocol?

stream 分流的话, 在正常可用的配置中
nginx 的 配置文件的 stream 打开发送 proxy protocol, 即添加 proxy_protocol on;
xray 开启接收, 在服务端 xray 的 streamSettings 配置中增加 
        "sockopt": {
          "acceptProxyProtocol": true
        }
(tcp ws 有自己的配置, 也可以通过此处配置)

**Comment by laughtale233** [comment]
> 一直在看全局的tcpSettings和grpcSettings, 忽略了streamSettings. 谢谢解答.

**Comment by badO1a5A90** [comment]
@laughtale233 
https://github.com/XTLS/Xray-core/pull/769 已经解决了grpc 使用 http 分流时也读取真实IP的问题
注: 与 stream 分流不同, 这里不需要开启acceptProxyProtocol

**Comment by gcphym** [comment]
> > 另外如果使用nginx的stream模块转发grpc流量给Xray, 不能开启proxy_protocol, 否则线路不通. grpcSettings是否需要加上AcceptProxyProtocol?
> 
> stream 分流的话, 在正常可用的配置中 nginx 的 配置文件的 stream 打开发送 proxy protocol, 即添加 proxy_protocol on; xray 开启接收, 在服务端 xray 的 streamSettings 配置中增加
> 
> ```
>         "sockopt": {
>           "acceptProxyProtocol": true
>         }
> ```
> 
> (tcp ws 有自己的配置, 也可以通过此处配置)

请问和这个是同样的效果吗
```
	"tcpSettings": {
		"acceptProxyProtocol": true
	}
```
