### ISSUE TITLE
[Init] High DPI scaling is enabled 

### ISSUE THREAD

**Issue by ckbkdj** [XTLS/Xray-core#770]
我想知道Qv2ray配置内核的时候出现这个问题
[Init] High DPI scaling is enabled 
请问是插件的问题还是Qv2ray问题

**Comment by yuhan6665** [comment]
This message has nothing to do with core. Plz ask in Qv2ray

**Comment by chaojixiaoyao** [comment]
这个问题是 ”v2ray核心可执行文件“选错导致的。要选择v2ray.exe
