### ISSUE TITLE
疑似收发短信导致的待机耗电提高

### ISSUE THREAD

**Issue by Aniark** [XTLS/Xray-core#780]
协议为裸 grpc ，手机为 MIUI 12.5.1，数据网络为中国联通

待机前如果**没有**收发短信，那么待机状态下基本不耗电，就像没有开启 xray 一样
待机前如果**有**收发短信，那么待机状态下会耗电提高
待机中如果收到了短信，那么从收到短信起，会开始耗电提高

xray 客户端 xray4magisk anxray v2rayng ，均有以上情况

一个临时的解决方案是：在收发短信后重启 xray 客户端

**Comment by firerflystar** [comment]
真诚建议换其他运营商SIM卡试试 , 期待结果... 🤒

**Comment by yuhan6665** [comment]
Close as invalid
