### ISSUE TITLE
Xray速度也是分时段的吗

### ISSUE THREAD

**Issue by shuiliu11** [XTLS/Xray-core#782]
我有2台服务器都是美西线，不同的服务商，安装的系统和XRAY的配置都是完全一样的，就IP不一样，这2条线，最近在晚上9点后速度开始下降，我认为是这2条线路不行了，还填了单子问了客服。
今天晚上有时间我就在其中一条线上装了OUTLINE，结果满速运行（电信），关了OUTLINE,重新用v2rayN连接，再测试，最多只有outline三分之二的速度，包括ping都是高了几十毫秒，是的大概有40ms。
这2条线在白天时的速度用xray的情况下都是满速的，有没有大神能分析一下。
有要服务器测试的留言，服务器上没有任何东西！

**Comment by shenlijun** [comment]
感觉主要看机房和邻居vps的负载

我用搬瓦工都是CN2 GIA-E，线路应该没问题

日本，延迟60-70，能跑满千兆

晚上10-12点看youtube只有3-4kb/s

香港也差不多

但是洛杉矶的就不会，只是延迟要160+
