### ISSUE TITLE
1.5.0 dns配置格式

### ISSUE THREAD

**Issue by DoingDog** [XTLS/Xray-core#784]
原来在V2RayN中的dns配置(1.4.5可用)，升级1.5.0报错。
net/url: invalid control character in URL

配置如下
 "hosts": {
    "dns.google": "8.8.8.8",
    "dns.pub": "119.29.29.29",
    "dns.alidns.com": "223.5.5.5",
    "geosite:category-ads-all": "127.0.0.1"
  },
  "servers": [
    {
      "address": "https://1.1.1.1/dns-query",
      "domains": ["geosite:geolocation-!cn"],
      "expectIPs": ["geoip:!cn"]
    },
    "8.8.8.8",
    {
      "address": "114.114.114.114",
      "port": 53,
      "domains": ["geosite:cn", "geosite:category-games@cn"],
      "expectIPs": ["geoip:cn"],
      "skipFallback": true
    },
    {
      "address": "localhost",
      "skipFallback": true
    }
  ]

请问如何修改使适应新版

**Comment by hkbase** [comment]
楼上的链接地址有变化，下面贴出新的：
https://github.com/chika0801/Xray-examples/blob/main/VLESS-TCP-XTLS/dns_routing_example_config_client.json
https://github.com/chika0801/Xray-examples/blob/main/VLESS-TCP-XTLS/dns_routing_example_config_server.json

**Comment by Terry-Lzz** [comment]
同问。升级1.5.0后原来的DNS配置报错了
看了楼上发的配置，不知道该怎么填到v2rayN里头

**Comment by chika0801** [comment]
> 同问。升级1.5.0后原来的DNS配置报错了 看了楼上发的配置，不知道该怎么填到v2rayN里头

V2rayN你的意思是要在客户端用我发的配置吗？你得使用自定义配置功能。

具体操作方法参考
https://github.com/chika0801/Xray-examples/blob/main/VLESS-TCP-XTLS/dns_routing_example_config_client.json

**Comment by yuhan6665** [comment]
先关了
