### ISSUE TITLE
1.5.0 使用"dnsLog": true，不能记录DNS over QUIC local mode

### ISSUE THREAD

**Issue by chika0801** [XTLS/Xray-core#785]
Xray 1.5.0 服务器配置文件中使用"dnsLog": true，在access的LOG文件中，不能记录到DNS over QUIC local mode的DNS查询记录。表现是access log里没有域名查询的记录信息。

如果换成DNS over HTTPS local mode，则正常。
access log文件有类似记录

2021/10/24 15:42:24 27.10.130.169:0 accepted tcp:www.google.com:443 [direct]
2021/10/24 15:42:24 DoH accepted https://1.1.1.1/dns-query [local]
2021/10/24 15:42:24 DOHL//1.1.1.1 got answer: www.google.com -> [172.217.161.228] 90.387432ms
2021/10/24 15:42:24 27.10.130.169:0 accepted tcp:www.google.com:443 [direct]
2021/10/24 15:42:24 DOHL//1.1.1.1 cache HIT: www.google.com -> [172.217.161.228]
2021/10/24 15:42:24 27.10.130.169:0 accepted tcp:www.google.com:443 [direct]
2021/10/24 15:42:24 DOHL//1.1.1.1 cache HIT: www.google.com -> [172.217.161.228]

**Comment by yuhan6665** [comment]
It should be fixed in latest build
https://github.com/XTLS/Xray-core/actions/runs/2729773751

**Comment by chika0801** [comment]
大佬居然记得这个 感动5555

**Comment by yuhan6665** [comment]
> 大佬居然记得这个 感动5555

one commit a day, keep real ~~girl~~ life away

**Comment by yuhan6665** [comment]
fixed in 1.5.10
