### ISSUE TITLE
请问，内置dns模块有支持DoT （Dns over Tls）查询请求的计划吗？？

### ISSUE THREAD

**Issue by hkbase** [XTLS/Xray-core#786]
请问，有支持DoT （Dns over Tls）类型的dns查询请求的计划吗？？ 
希望内置dns模块能够支持dot类型的dns服务器。

config.json配置示例如下：
示例A：
"dns": {
 "servers": [
    {
      "address": "**tls+local://8.8.4.4**",
      "port": 853
    }
   ]
}

示例B：
"dns": {
 "servers": [
    {
      "address": "**tls://8.8.4.4**",
      "port": 853
    }
   ]
}

顺便向大家推荐一个支持udp，tcp，dot，doh协议的dns客户端工具dog ，
开源地址：https://github.com/ogham/dog
使用方式：
#dog twitter.com -n 8.8.4.4 -S
A twitter.com. 3m14s   104.244.42.65
A twitter.com. 3m14s   104.244.42.129

**Comment by toyo2333** [comment]
"dns": {
        "servers": [
            "tcp+local://8.8.8.8:853"
        ]
   }, 

写成这样报错 是因为不支持 DNS over TLS 么？
```
2026/08/29 17:58:54.507495 [Debug] app/dns: domain XXXX.com will use DNS in order: [TCPL//8.8.8.8:853]
2026/08/29 17:58:54.507811 [Info] app/dns: TCPL//8.8.8.8:853 querying DNS for: XXXX.com.
2026/08/29 17:58:54.508075 [Debug] transport/internet: dialing to tcp:8.8.8.8:853
2026/08/29 17:58:54.508407 [Debug] transport/internet: dialing to tcp:8.8.8.8:853
2026/08/29 17:58:54.509317 [Error] app/dns: failed to parse DNS over TCP response > app/dns: failed to parse DNS response > unpacking header: questions: insufficient data for base length type
2026/08/29 17:58:54.509930 [Error] app/dns: failed to parse DNS over TCP response > app/dns: failed to parse DNS response > unpacking header: questions: insufficient data for base length type
```
