### ISSUE TITLE
API流量统计功能不能用

### ISSUE THREAD

**Issue by xianren78** [XTLS/Xray-core#8]
```
# /usr/local/bin/xray api --server=127.0.0.1:10010 StatsService.QueryStats 'pattern: "" reset: false'
   failed to call service StatsService.QueryStats
```
结果如上。。

**Comment by qjebbs** [comment]
@rprx https://github.com/v2fly/v2ray-core/pull/369#issuecomment-725289191

https://github.com/v2fly/v2ray-core/pull/369/commits/b45770461c71b51d6901bafd2c6b0151410c64d2

https://github.com/v2fly/v2ray-core/pull/452

**Comment by rprx** [comment]
应该可以在下个版本中解决，同时可能会增加对 "V2RAY" 字样开头的兼容

**Comment by AAkira45** [comment]
感谢付出！希望下个版本解决后，我就能全线切换到xray-core了，谢谢

**Comment by rprx** [comment]
@AAkira45 

防止理解错误，他说的是 `xray api` 指令的问题，不是 Qv 等不显示流量统计的问题（后者是因为 API 名称变了，实际上仍可用）

**Comment by AAkira45** [comment]
好的谢谢提醒，我也指的是xray api而非Qv客户端

**Comment by rprx** [comment]
@qjebbs 

Xray 似乎可以直接支持 v5 的 API？看到你只是改了 api 指令，没有改 grpc 接口

**Comment by qjebbs** [comment]
> @qjebbs
> 
> Xray 似乎可以直接支持 v5 的 API？看到你只是改了 api 指令，没有改 grpc 接口

可以啊。我只是做了易用性修改，grpc接口那块我还不熟

**Comment by kobehuanghai** [comment]
是的如果增加了服务器端的流量统计那我就全线转Xray了，现在没有统计多人合用还是有点不方便

**Comment by xianren78** [comment]
> @rprx [v2fly/v2ray-core#369 (comment)](https://github.com/v2fly/v2ray-core/pull/369#issuecomment-725289191)
> 
> [v2fly/v2ray-core@b457704](https://github.com/v2fly/v2ray-core/commit/b45770461c71b51d6901bafd2c6b0151410c64d2)
> 
> [v2fly/v2ray-core#452](https://github.com/v2fly/v2ray-core/pull/452)

/usr/local/bin/xray api statsquery --server=127.0.0.1:10010 -pattern ''
xray 1.1.1 结果乱码？

**Comment by rprx** [comment]
https://github.com/XTLS/Xray-core/releases/tag/v1.1.2

`xray api` 输出格式均为 JSON，一些脚本可能要做对应修改，欢迎分享新的脚本。

或者直接调用 gRPC，比如 v2rayN、Qv2ray。（它们的流量统计也有数据了，gRPC 接口加了兼容）

如果存在新的问题，请开新的 issue。
