### ISSUE TITLE
VLESS+TLS/XTLS+TCP 443端口被封了

### ISSUE THREAD

**Issue by iamqk** [XTLS/Xray-core#802]
使用 wulabing脚本安装
带站点伪装 甲骨文云服务器 443 端口被封了
趁ip还在 赶紧卸载了
以后恢复成tls ws的吧

**Comment by yaott2020-666** [comment]
那你提issue干嘛

**Comment by ZqinKing** [comment]
> 站点伪装 甲骨文云服务器 443 端口被封了

5个站点都是XTLS+TCP 443用的好好的。

**Comment by bardophshampine** [comment]
建议关闭此issue

**Comment by dream10201** [comment]
今天我和我同事两台都是，确实被封了，22可连，443被封

**Comment by yaott2020-666** [comment]
怎么没人说是什么vps提供商

**Comment by ShawnZhang76** [comment]
今天Hostdare的被封了443

**Comment by lvlinkeji** [comment]
建议关闭此issue

**Comment by iamqk** [comment]
> 那你提issue干嘛

我vless tls ws很久都没有被封过，XLS也用了一段时间，但是被封了，是不是应该找找问题所在，以后别人使用的时候就可以防止TFW的封锁，所以我要提issue啊

**Comment by FanLuoh** [comment]
建议关闭此issue

**Comment by yaott2020-666** [comment]
> > 那你提issue干嘛
> 
> 我vless tls ws很久都没有被封过，XLS也用了一段时间，但是被封了，是不是应该找找问题所在，以后别人使用的时候就可以防止TFW的封锁，所以我要提issue啊

第一，没有证据表明上述协议有漏洞，所以你提issue也没用

第二，近期是敏感时期，gfw乱杀，不仅仅是代理，可能有些建站的也误封，有些代理长时间没有使用也被封，没有任何征兆，所以就更加没有必要提issue，自己更换ip或者vps即可

**Comment by ax003** [comment]
应该不是协议出问题了，前几天比较敏感，能感觉到墙在抽风，像我同一家vps提供商，一个vps抽风，另一个稳定。
表现形式就是，连接超时，不时22和443都连不上，一会儿又正常。
不过昨天开始就都正常了

**Comment by shenlijun** [comment]
xtls应该是有被检测到某种行为，在发现问题前还是用tls吧

那些建议关闭issue的，就呵呵了

xtls被封不是个例，都是换tls后就没问题了

**Comment by AkinoKaede** [comment]
> > > 那你提issue干嘛
> > 
> > 
> > 我vless tls ws很久都没有被封过，XLS也用了一段时间，但是被封了，是不是应该找找问题所在，以后别人使用的时候就可以防止TFW的封锁，所以我要提issue啊
> 
> 第一，没有证据表明上述协议有漏洞，所以你提issue也没用
> 
> 第二，近期是敏感时期，gfw乱杀，不仅仅是代理，可能有些建站的也误封，有些代理长时间没有使用也被封，没有任何征兆，所以就更加没有必要提issue，自己更换ip或者vps即可

XTLS/Go#16

**Comment by shenlijun** [comment]
上面那些建议关闭issue的兄弟，可千万别换tls啊

**Comment by yaott2020-666** [comment]
既然认为有漏洞，可以直接引流到另一个issue，可以关闭这个issue，我并无恶意，只是认为可以关闭一些无关紧要的issue

**Comment by shenlijun** [comment]
> 既然认为有漏洞，可以直接引流到另一个issue，可以关闭这个issue，我并无恶意，只是认为可以关闭一些无关紧要的issue

引流到哪个issue好呢？现在应该用xtls最多用户的就是xray吧，其它应用可能也没有被抓特征的问题。

又如何判断什么才是无关紧要的issue呢？个人觉得放一个有提示作用的issue在这里蛮好的。
如果是因为个人喜好一个工具或者自己暂时没问题就容不得别人提issue，大可不必

**Comment by shenlijun** [comment]
更上面的那个回复居然被人点了踩，可太秀了，不会打字？
而且还是一个没在这issue中回复过的人，有必要换个账号专门上来点一个么？
心理真jer阴暗吖

**Comment by chika0801** [comment]
LZ明显不是老MJJ没经历过百年大寿时期吧。这和你用什么组合没有关系。建议多去TG群hostloc混混涨涨经验祝你早日成为老MJJ。

**Comment by chika0801** [comment]
> > 那你提issue干嘛
> 
> 我vless tls ws很久都没有被封过，XLS也用了一段时间，但是被封了，是不是应该找找问题所在，以后别人使用的时候就可以防止TFW的封锁，所以我要提issue啊

https://github.com/XTLS/Xray-core/discussions/593#discussioncomment-845165

请知晓这个常识

**Comment by chika0801** [comment]
https://github.com/XTLS/Xray-core/issues/802#issuecomment-968021102

在意这个的在，用xray前置，用vless+tcp+xtls组合时把配置改成"xtlsSettings": {
                    "minVersion": "1.3",

**Comment by shenlijun** [comment]
> [#802 (comment)](https://github.com/XTLS/Xray-core/issues/802#issuecomment-968021102)
> 
> 在意这个的在，用xray前置，用vless+tcp+xtls组合时把配置改成"xtlsSettings": { "minVersion": "1.3",

这本身就是一个明显的特征

**Comment by shenlijun** [comment]
> > > 那你提issue干嘛
> > 
> > 
> > 我vless tls ws很久都没有被封过，XLS也用了一段时间，但是被封了，是不是应该找找问题所在，以后别人使用的时候就可以防止TFW的封锁，所以我要提issue啊
> 
> [#593 (comment)](https://github.com/XTLS/Xray-core/discussions/593#discussioncomment-845165)
> 
> 请知晓这个常识

和这个没什么关系，设置了，依然会因为xtls的特征被封

**Comment by shenlijun** [comment]
> LZ明显不是老MJJ没经历过百年大寿时期吧。这和你用什么组合没有关系。建议多去TG群hostloc混混涨涨经验祝你早日成为老MJJ。

同一天，3次连换ip，xtls撑不过一个小时，第4次改成tls一直用到了现在
同样的vps，同样的ip段

**Comment by shenlijun** [comment]
> LZ明显不是老MJJ没经历过百年大寿时期吧。这和你用什么组合没有关系。建议多去TG群hostloc混混涨涨经验祝你早日成为老MJJ。

说几个“貌似”的建议，提个TG，带着些许的优越感上来一顿踩和赞，是不是感觉是在批阅奏章吖……😄

**Comment by shenlijun** [comment]
Github，一个需要理性讨论的地方，一帮半吊子在这里阴阳怪气，都nm打的中文，向国际丢人是吧？

**Comment by shenlijun** [comment]
#623 
那时候就有人发现会自动封xtls了

**Comment by chika0801** [comment]
所以说这里没什么人说费话

**Comment by shenlijun** [comment]
> 所以说这里没什么人说费话

所以有的人看似不废话，实则阴阳怪气是吧

**Comment by chika0801** [comment]
> > 所以说这里没什么人说费话
> 
> 所以有的人看似不废话，实则阴阳怪气是吧

难得和你多BB，懂的人自然懂，就是类似这样的人来github开问题多了，也没有什么人爱在这讨论内容

**Comment by shenlijun** [comment]
> > > 所以说这里没什么人说费话
> > 
> > 
> > 所以有的人看似不废话，实则阴阳怪气是吧
> 
> 难得和你多BB，懂的人自然懂，就是类似这样的人来github开问题多了，也没有什么人爱在这讨论内容

呵呵，就是因为阴阳怪气的人多才导致人们不讨论的

你的另外连个删除的回复我看到了，一个是嫌这里小白多，一个是要长时间试
这个吧，小白与否怕你真的不一定有资格评价别人，以后没事还是少用这个词
二来长时间试就算了，换ip要花钱的

**Comment by shenlijun** [comment]
github这种藏龙卧虎的地方们可以自称小白，别随便说别人小白

**Comment by firerflystar** [comment]
把你的conf贴出来 说不定根本就是自己的问题

**Comment by yuhan6665** [comment]
最近墙比较高 有各种被封锁情况 提出自己遇到的问题是可以的 但需要注意不要以点盖面 不要故意引战 先关了
