### ISSUE TITLE
虛擬機4核測速，只有1核跑滿，其餘3核沒盡全力跑

### ISSUE THREAD

**Issue by i553041** [XTLS/Xray-core#81]
我的網絡環境在Mac上以xray的direct模式測速大約有460Mb，服務器是Linux，客戶端是Mac。

服務端和客戶端都是使用xray 1.1.3

最近推出了splice，但只支持Linux的客戶端，(客戶端我沒有Android和Linux)，昨天忽然想起，我可以在Mac上使用VMware Fusion虛擬機，安裝一個Linux(ubuntu)，來測試splice。

我用的Mac OS是big sur，4核i7，16GB內存

<img width="588" alt="截圖 2020-12-16 下午11 53 47" src="https://user-images.githubusercontent.com/53026952/102420377-fbb39d80-403c-11eb-9186-ee9d7bfbc465.png">

VMware Fusion：

<img width="692" alt="截圖 2020-12-16 下午11 54 03" src="https://user-images.githubusercontent.com/53026952/102420410-09692300-403d-11eb-8305-9b62028a922a.png">

分了4核，4GB內存給ubuntu用：

<img width="752" alt="截圖 2020-12-17 上午7 55 40" src="https://user-images.githubusercontent.com/53026952/102420713-b479dc80-403d-11eb-963c-e92ef2338eb9.png">

發現在splice、direct和vmess+ws+tls模式下，(已配置環境變量，確實輸出了splice / xtls / readv，
)，測速都是1核跑滿，其餘3核偷懶沒盡全力跑，令我的測速比不用虛擬機時更慢，(本來是想看看splice的威力)

3種模式測速時，處理器使用情況大約都是這樣：

<img width="1431" alt="截圖 2020-12-16 下午11 51 14" src="https://user-images.githubusercontent.com/53026952/102421289-138c2100-403f-11eb-9f6b-33d38b17000f.png">

令我的測速結果比之前更慢：

<img width="752" alt="截圖 2020-12-16 下午11 22 10" src="https://user-images.githubusercontent.com/53026952/102421339-33234980-403f-11eb-916d-a08c0b8d8316.png">

在虛擬機上測speedtest，跑到850多Mb，所以測試splice，硬件上應該是沒問題的：

<img width="1199" alt="截圖 2020-12-17 上午8 15 24" src="https://user-images.githubusercontent.com/53026952/102421789-42ef5d80-4040-11eb-868a-cf56d93960f3.png">

不知道是不是bug，所以前來報告一下。

**Comment by rprx** [comment]
太好了，终于遇到了这个问题。多核围观问题 99% 和开启协程的策略有关，但也可能受其它因素影响，等下先传几个版本你试试。

**Comment by rprx** [comment]
请分别试试下面两个版本，并反馈前三行输出

[Xray-linux-64.zip](https://github.com/XTLS/Xray-core/files/5707022/Xray-linux-64.zip)

[Xray-linux-64.zip](https://github.com/XTLS/Xray-core/files/5707028/Xray-linux-64.zip)

**Comment by rprx** [comment]
请分别试试下面两个版本，并反馈前三行输出

[Xray-linux-64.zip](https://github.com/XTLS/Xray-core/files/5707022/Xray-linux-64.zip)

[Xray-linux-64.zip](https://github.com/XTLS/Xray-core/files/5707154/Xray-linux-64.zip)

**Comment by i553041** [comment]
> 太好了，终于遇到了这个问题。多核围观问题 99% 和开启协程的策略有关，但也可能受其它因素影响，等下先传几个版本你试试。

我現在在上班，今晚下班後回家再試，再補充一下測試情況，我的虛擬機是客戶端(這樣才能測splice啊），在配置檔裡開了socks，然後我在mac的socks全局代理裡配置了虛擬機的socks，10.10.10.4:1089，再在同一台mac裡用瀏覽器進行speedtest測速。

**Comment by i553041** [comment]
> Xray-linux-64.zip

這是第一個xray，前三行輸出：

<img width="825" alt="截圖 2020-12-17 下午9 40 39" src="https://user-images.githubusercontent.com/53026952/102495459-145d9b00-40b1-11eb-81d1-1920e463cd39.png">

測速時的截圖：

<img width="1446" alt="截圖 2020-12-17 下午9 36 13" src="https://user-images.githubusercontent.com/53026952/102495587-35be8700-40b1-11eb-9985-92b4e7eb6f0c.png">

<img width="1407" alt="截圖 2020-12-17 下午9 36 31" src="https://user-images.githubusercontent.com/53026952/102495607-3fe08580-40b1-11eb-891d-876a8d0f16a8.png">

這是第二個xray，前三行輪出：

<img width="807" alt="截圖 2020-12-17 下午9 40 12" src="https://user-images.githubusercontent.com/53026952/102495672-57b80980-40b1-11eb-9ada-67ea158911b9.png">

測速時的截圖：

<img width="1449" alt="截圖 2020-12-17 下午9 42 07" src="https://user-images.githubusercontent.com/53026952/102495730-6c949d00-40b1-11eb-9e0b-36bb7e0d8c6a.png">

<img width="1422" alt="截圖 2020-12-17 下午9 42 24" src="https://user-images.githubusercontent.com/53026952/102495747-73bbab00-40b1-11eb-81b9-c6c246a668ee.png">

**Comment by badO1a5A90** [comment]
@i553041 麻烦附一份虚拟机内部直连测速的CPU占用.

**Comment by i553041** [comment]
> @i553041 麻烦附一份虚拟机内部直连测速的CPU占用.

<img width="1661" alt="截圖 2020-12-17 下午10 10 20" src="https://user-images.githubusercontent.com/53026952/102498319-c480d300-40b4-11eb-84b2-ce04cf4b9794.png">

**Comment by rprx** [comment]
我有个猜想是虚拟网卡的问题 https://github.com/v2fly/v2ray-core/issues/466#issuecomment-738493189

**Comment by badO1a5A90** [comment]
> > @i553041 麻烦附一份虚拟机内部直连测速的CPU占用.
> 
> 好像也有相同問題，但不肯定
> 
> <img alt="截圖 2020-12-17 下午10 10 20" width="1661" src="https://user-images.githubusercontent.com/53026952/102498319-c480d300-40b4-11eb-84b2-ce04cf4b9794.png">

其实也有一核比较有难...只是CPU未满不能完全确定.

**Comment by badO1a5A90** [comment]
@i553041 你虚拟网卡和主机用的是什么连接模式?

**Comment by i553041** [comment]
> @i553041 你虚拟网卡和主机用的是什么连接模式?

用這個模式，DHCP會派一個我內網 IP給虛擬機(10.10.10.5)，我Mac的內網IP是10.10.10.1

<img width="752" alt="截圖 2020-12-17 下午10 14 58" src="https://user-images.githubusercontent.com/53026952/102498787-5e488000-40b5-11eb-9174-2c78aa1051a6.png">

**Comment by badO1a5A90** [comment]
没有用过vmware fusion的虚拟机, 这应该算是桥接模式吧.

**Comment by badO1a5A90** [comment]
> 我有个猜想是虚拟网卡的问题 [v2fly/v2ray-core#466 (comment)](https://github.com/v2fly/v2ray-core/issues/466#issuecomment-738493189)

我用vmware workstation 装的debian并没有复现

**Comment by i553041** [comment]
> 没有用过vmware fusion的虚拟机, 这应该算是桥接模式吧.

上圖顯示的是Bridged Networking，應該是橋接模式不錯了，有沒有其他進程讓我可以跑滿網速和CPU再作測試？

**Comment by badO1a5A90** [comment]
> 上圖顯示的是Bridged Networking，應該是橋接模式不錯了，有沒有其他進程讓我可以跑滿網速和CPU再作測試？
限制CPU你可以在虚拟机的ubuntu上执行如下命令创建策略
```
apt install cgroup-tools
cgcreate -g cpu:test
cd /sys/fs/cgroup/cpu/test
echo 1000 > cpu.cfs_quota_us
echo 4000 > cpu.cfs_period_us
```
然后用下面代码执行speedtest(注意speedtest路径)
```
cgexec -g cpu:test speedtest
```

**Comment by i553041** [comment]
> > 上圖顯示的是Bridged Networking，應該是橋接模式不錯了，有沒有其他進程讓我可以跑滿網速和CPU再作測試？
> 
> 限制CPU你可以在虚拟机的ubuntu上执行如下命令创建策略
> 
> ```
> apt install cgroup-tools
> cgcreate -g cpu:test
> cd /sys/fs/cgroup/cpu/test
> echo 1000 > cpu.cfs_quota_us
> echo 4000 > cpu.cfs_period_us
> ```
> 
> 然后用下面代码执行speedtest(注意speedtest路径)
> 
> ```
> cgexec -g cpu:test speedtest
> ```

結果如下：

![image](https://user-images.githubusercontent.com/53026952/102504460-d31eb880-40bb-11eb-9b13-37dd3014545f.png)

![image](https://user-images.githubusercontent.com/53026952/102504502-e3cf2e80-40bb-11eb-9736-ec68e59140eb.png)

**Comment by badO1a5A90** [comment]
上面这个直连速度测试, 没有跑满网络瓶颈, 瓶颈应该在CPU.

但CPU也没有每个核心都跑满25%(理论应该如此,通过cgroup限制在25%了)

测试中CPU的表现也是一核有难(25%),多核围观(10%+)

这个测试没有用到Xray,所以这个一核有难多核围观的现象与Xray无关了.

可能是虚拟机/虚拟机网卡机制等问题引起的.

**Comment by badO1a5A90** [comment]
这个案子感觉破了,大概率就是vmware/VMware虚拟网卡的一些原因.
然后 一核有难多核围观 的悬案也断线了.

**Comment by badO1a5A90** [comment]
不过也不知道之前报告的是否是类似环境.
Xray下目前只此一例,且并非Xray的锅

(古老版本v2ray,编译使用的golang编译版本在1.5之前时确实可能有此问题
(因为v2ray中没有runtime.NumCPU()及runtime.GOMAXPROCS()相关代码

Xray编译使用golang版本已经足够高,会自动管理.

在没有新的报告之前也许可以认为已经解决了.

**Comment by Menma33** [comment]
<img width="573" alt="QQ20201218-001555@2x" src="https://user-images.githubusercontent.com/47851414/102513782-9efcc500-40c6-11eb-95af-0ae50aeacc88.png">
![2020-12-18 00 16 51](https://user-images.githubusercontent.com/47851414/102513814-a6bc6980-40c6-11eb-9eef-67d77c30ad50.jpg)
![2020-12-18 00 16 56](https://user-images.githubusercontent.com/47851414/102513829-ad4ae100-40c6-11eb-9e5c-3abd9953ecdd.jpg)
<img width="626" alt="QQ20201218-001830@2x" src="https://user-images.githubusercontent.com/47851414/102513864-b76cdf80-40c6-11eb-86af-e0ffe078b2ca.png">
使用相同的虚拟机环境跑了iperf3测试 复现了单核跑满3核围观的情况 所以应该是VMware的问题和Xray无关

**Comment by badO1a5A90** [comment]
> <img alt="QQ20201218-001555@2x" width="573" src="https://user-images.githubusercontent.com/47851414/102513782-9efcc500-40c6-11eb-95af-0ae50aeacc88.png">
> 
> ![2020-12-18 00 16 51](https://user-images.githubusercontent.com/47851414/102513814-a6bc6980-40c6-11eb-9eef-67d77c30ad50.jpg) ![2020-12-18 00 16 56](https://user-images.githubusercontent.com/47851414/102513829-ad4ae100-40c6-11eb-9e5c-3abd9953ecdd.jpg)
> <img alt="QQ20201218-001830@2x" width="626" src="https://user-images.githubusercontent.com/47851414/102513864-b76cdf80-40c6-11eb-86af-e0ffe078b2ca.png">
> 
> 使用相同的虚拟机环境跑了iperf3测试 复现了单核跑满3核围观的情况 所以应该是VMware的问题和Xray无关

感谢验证! 确定是VM的锅了.

**Comment by badO1a5A90** [comment]
> 使用相同的虚拟机环境跑了iperf3测试 复现了单核跑满3核围观的情况 所以和是VMware的问题和Xray无关

群友提示似乎应该用 -P 指定多个连接测试一下?

**Comment by Menma33** [comment]
> > 使用相同的虚拟机环境运行了iperf3测试复现了单核跑满3核围观的情况所以和是VMware的问题和Xray无关
> 
> 群友提示似乎应该用-P指定多个连接测试一下？

<img width="465" alt="QQ20201218-003324@2x" src="https://user-images.githubusercontent.com/47851414/102515405-b2a92b00-40c8-11eb-8c09-178ebb2e4f54.png">
<img src="https://user-images.githubusercontent.com/47851414/102515459-c6549180-40c8-11eb-97f5-76767cfb5a88.png">
结果还是单核100% 三个核心围观 基本可以确定是虚拟机的锅了

**Comment by Menma33** [comment]
<img src="https://user-images.githubusercontent.com/47851414/102520722-f141e400-40ce-11eb-9da3-7f43d6bbffce.jpg">
<img src="https://user-images.githubusercontent.com/47851414/102520762-00c12d00-40cf-11eb-867c-b4cbd890445c.jpg">
使用go版iperf测试 因为没有mac版开了Windows虚拟机侨接了物理网卡（最高速度只有千兆）所以跑不满Ubuntu虚拟机的cpu 但看起来依然是单个核心占用较高

**Comment by badO1a5A90** [comment]
> 使用go版iperf测试 因为没有mac版开了Windows虚拟机侨接了物理网卡（最高速度只有千兆）所以跑不满Ubuntu虚拟机的cpu 但看起来依然是单个核心占用较高


非常感谢这么多次的测试!


我觉得结论还是:

_(古老版本v2ray,编译使用的golang编译版本在1.5之前时确实可能有此问题
(因为v2ray中没有runtime.NumCPU()及runtime.GOMAXPROCS()相关代码_

Xray编译使用golang版本已经足够高,会自动管理.

**在没有新的报告之前也许可以认为已经解决了.** @rprx

**Comment by rprx** [comment]
其实我今天看了看 Xray 现在的代码，很多地方都开了新协程，比如出入站和 pipe，且一条连接的读写也是分开的两个协程
Go 现在都会自动利用多核，为了避免意外，我还特地上传了两个指定核心数的版本（第二个是二倍核心数），并没有解决问题
此外，在我的系统上，多个核心的占用率非常均匀，完全无法复现此问题，群里 pin 了消息，也没人能在正常环境下复现
结合其他人的一些测试，我的结论是 **该问题不是 Xray 或 v2ray 的代码问题，而是少数特殊环境本身的问题**

**Comment by rprx** [comment]
补充：这里的“一条连接”指的是 socket，比如客户端 VLESS 出站到服务器 VLESS 入站的 TCP 连接，本地 Socks5 则是另一条

我们可以记录一下出现此问题的场景，除了这里提到的场景外，据闻一些联发科 CPU 的路由器上也有此问题
