### ISSUE TITLE
问题：xray莫名其妙劫持了53端口

### ISSUE THREAD

**Issue by yaott2020-666** [XTLS/Xray-core#813]
用的是openwrt passwall
没有使用xray自带的dns功能，配置文件里没有dns模块
时不时就劫持了lanip:53导致无法上网

**Comment by yaott2020-666** [comment]
日志：
>   "outbounds": [
    {
      "streamSettings": {
        "sockopt": {
          "mark": 255
        }
      },
      "settings": {
        "domainStrategy": "UseIPv4"
      },
      "protocol": "freedom",
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "tag": "blackhole"
    },
    {
      "_flag_tag": "****",
      "_flag_proxy": 0,
      "_flag_proxy_tag": "nil",
      "settings": {
        "servers": [
          {
            "password": "",
            "port": 2082,
            "address": "127.0.0.1"
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "none"
      },
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "socks",
      "tag": "default"
    }
  ],
  "log": {
    "loglevel": "warning"
  },
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "domain": [
          "domain:ip6-localhost",
          "domain:ip6-loopback",
          "domain:local",
          "domain:localhost"
        ],
        "outboundTag": "direct"
      },
      {
        "ip": [
          "geoip:private",
          "::1\/128",
          "fc00::\/7",
          "fe80::\/10",
          "fd00::\/8"
        ],
        "type": "field",
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "domain": [
          "geosite:category-ads-all"
        ],
        "outboundTag": "blackhole"
      },
      {
        "ip": [
          "geoip:zerotier"
        ],
        "type": "field",
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "domain": [
          "geosite:cn"
        ],
        "outboundTag": "direct"
      },
      {
        "ip": [
          "geoip:cn",
          "geoip:cnv6"
        ],
        "type": "field",
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "domain": [
          "geosite:**"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "domain": [
          "geosite:gfw"
        ],
        "outboundTag": "default"
      },
      {
        "type": "field",
        "network": "tcp,udp",
        "outboundTag": "default"
      }
    ],
    "domainMatcher": "hybrid"
  },
  "inbounds": [
    {
      "port": 9050,
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "udp": true,
        "auth": "noauth"
      },
      "listen": "0.0.0.0"
    },
    {
      "settings": {
        "allowTransparent": false
      },
      "port": 9051,
      "protocol": "http",
      "listen": "0.0.0.0"
    },
    {
      "port": 1041,
      "protocol": "dokodemo-door",
      "streamSettings": {
        "sockopt": {
          "tproxy": "tproxy"
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "network": "tcp,udp",
        "followRedirect": true
      }
    }
  ]
}
>

**Comment by yaott2020-666** [comment]
离谱了这github编辑器。。。建议自己json格式化

**Comment by SekiBetu** [comment]
> 离谱了这github编辑器。。。建议自己json格式化

三个点，再写上json，结尾也用三个点包住

**Comment by SekiBetu** [comment]
```json
"outbounds": [ 
    { 
      "streamSettings": { 
        "sockopt": { 
          "mark": 255 
        } 
      }, 
      "settings": { 
        "domainStrategy": "UseIPv4" 
      }, 
      "protocol": "freedom", 
      "tag": "direct" 
    }, 
    { 
      "protocol": "blackhole", 
      "tag": "blackhole" 
    }, 
    { 
      "_flag_tag": "****", 
      "_flag_proxy": 0, 
      "_flag_proxy_tag": "nil", 
      "settings": { 
        "servers": [ 
          { 
            "password": "", 
            "port": 2082, 
            "address": "127.0.0.1" 
          } 
        ] 
      }, 
      "streamSettings": { 
        "network": "tcp", 
        "security": "none" 
      }, 
      "mux": { 
        "enabled": false, 
        "concurrency": 8 
      }, 
      "protocol": "socks", 
      "tag": "default" 
    } 
  ], 
  "log": { 
    "loglevel": "warning" 
  }, 
  "routing": { 
    "domainStrategy": "IPOnDemand", 
    "rules": [ 
      { 
        "type": "field", 
        "domain": [ 
          "domain:ip6-localhost", 
          "domain:ip6-loopback", 
          "domain:local", 
          "domain:localhost" 
        ], 
        "outboundTag": "direct" 
      }, 
      { 
        "ip": [ 
          "geoip:private", 
          "::1\/128", 
          "fc00::\/7", 
          "fe80::\/10", 
          "fd00::\/8" 
        ], 
        "type": "field", 
        "outboundTag": "direct" 
      }, 
      { 
        "type": "field", 
        "domain": [ 
          "geosite:category-ads-all" 
        ], 
        "outboundTag": "blackhole" 
      }, 
      { 
        "ip": [ 
          "geoip:zerotier" 
        ], 
        "type": "field", 
        "outboundTag": "direct" 
      }, 
      { 
        "type": "field", 
        "domain": [ 
          "geosite:cn" 
        ], 
        "outboundTag": "direct" 
      }, 
      { 
        "ip": [ 
          "geoip:cn", 
          "geoip:cnv6" 
        ], 
        "type": "field", 
        "outboundTag": "direct" 
      }, 
      { 
        "type": "field", 
        "domain": [ 
          "geosite:**" 
        ], 
        "outboundTag": "direct" 
      }, 
      { 
        "type": "field", 
        "domain": [ 
          "geosite:gfw" 
        ], 
        "outboundTag": "default" 
      }, 
      { 
        "type": "field", 
        "network": "tcp,udp", 
        "outboundTag": "default" 
      } 
    ], 
    "domainMatcher": "hybrid" 
  }, 
  "inbounds": [ 
    { 
      "port": 9050, 
      "protocol": "socks", 
      "sniffing": { 
        "enabled": true, 
        "destOverride": [ 
          "http", 
          "tls" 
        ] 
      }, 
      "settings": { 
        "udp": true, 
        "auth": "noauth" 
      }, 
      "listen": "0.0.0.0" 
    }, 
    { 
      "settings": { 
        "allowTransparent": false 
      }, 
      "port": 9051, 
      "protocol": "http", 
      "listen": "0.0.0.0" 
    }, 
    { 
      "port": 1041, 
      "protocol": "dokodemo-door", 
      "streamSettings": { 
        "sockopt": { 
          "tproxy": "tproxy" 
        } 
      }, 
      "sniffing": { 
        "enabled": true, 
        "destOverride": [ 
          "http", 
          "tls" 
        ] 
      }, 
      "settings": { 
        "network": "tcp,udp", 
        "followRedirect": true 
      } 
    } 
  ] 
} 
```

**Comment by yaott2020-666** [comment]
懂了，谢谢老哥

**Comment by yaott2020-666** [comment]
所以有人知道原因吗

**Comment by yaott2020-666** [comment]
破案了。。。我使用了内网域名，*ray设置路由规则是“IPOnDemand”，当内网域名经过*ray时，*ray就会查询dns，导致缓慢，我看错了，以为是*ray占用了
