### ISSUE TITLE
请增加 同时用多个cdn ip 连接 同一个服务器 达到 带宽叠加

### ISSUE THREAD

**Issue by gitv2ray** [XTLS/Xray-core#816]
现在是用cf ip优选，能达到较高速度。
请增加 用多个cdn 的ip连接到 同一 服务器，实现 多个cdn ip同时传输数据达到最大速度。
比如 用5个 cdn ip 连到 同一个 服务器，形成5个通道。用其中一个通道发送请求。
然后 服务器下了100M数据，但当一个通道时，只有1M传输速度。但是如果有
5个通道的话，就可能有5*1M的速度。
请各位大佬考虑添加一个这样的功能。谢谢！

**Comment by liberal-boy** [comment]
你说的功能应该类似二层的链路聚合，但在ws里面搞一个这种功能，麻烦很多，目前应该没有现成的上层"叠加宽带"的轮子，目测工程量极大，而且受众不会很多

**Comment by shenlijun** [comment]
用个靠谱点的vps就好了吖

PS：所有可以用硬件方式解决的问题都应该不优先考虑软件实现，就算成本稍高一点

**Comment by rampageX** [comment]
> 用个靠谱点的vps就好了吖
> 
> PS：所有可以用硬件方式解决的问题都应该不优先考虑软件实现，就算成本稍高一点

你这思维和马斯克的完全相反~我就随便一说啊。。。

**Comment by shenlijun** [comment]
> > 用个靠谱点的vps就好了吖
> > PS：所有可以用硬件方式解决的问题都应该不优先考虑软件实现，就算成本稍高一点
> 
> 你这思维和马斯克的完全相反~我就随便一说啊。。。

哇哈哈，996还是福报呐

**Comment by shenlijun** [comment]
> > 用个靠谱点的vps就好了吖
> > PS：所有可以用硬件方式解决的问题都应该不优先考虑软件实现，就算成本稍高一点
> 
> 你这思维和马斯克的完全相反~我就随便一说啊。。。

哇哈哈，996还是福报呐，1个亿还是小目标呐

**Comment by xqzr** [comment]
`vnext` 是一个数组

**Comment by UltraRabbit** [comment]
> 现在是用cf ip优选，能达到较高速度。 请增加 用多个cdn 的ip连接到 同一 服务器，实现 多个cdn ip同时传输数据达到最大速度。 比如 用5个 cdn ip 连到 同一个 服务器，形成5个通道。用其中一个通道发送请求。 然后 服务器下了100M数据，但当一个通道时，只有1M传输速度。但是如果有 5个通道的话，就可能有5*1M的速度。 请各位大佬考虑添加一个这样的功能。谢谢！

能够实时记录5个CDN节点的流量和阻塞情况，动态负载均衡出站流量就挺好了。链路聚合的方案在无稳定链路上还是蛮难做的。

**Comment by loveqianool** [comment]
https://github.com/fregie/mpx
