### ISSUE TITLE
V2rayNG installed on anbox using xray-core doesn't seem to be working

### ISSUE THREAD

**Issue by drHuangMHT** [XTLS/Xray-core#819]
I've installed v2rayNG on my **anbox** environment, but both x86 and armv8 version of the app don't seem to behave properly(unable to establish a connection). I open the logcat tab and find this
![Screenshot_20211121_092627](https://user-images.githubusercontent.com/59129019/142745778-c547741a-49e7-4e20-a3f6-26faad8cce3c.png)
So I assume that it is somewhat related to xray. Maybe it's not worth fixing, but I would like to report this anyway.  
Any other solution except v2ray?   

我在anbox里装了v2rayNG,但是都不能建立连接。logcat里有这样的输出（上面的截图）  
我猜可能是xray的问题所以在这里开了个issue，v2rayNG那边还没有。  
可能跟anbox有关，如果真是这样那可能不太值得修，但还是在这开个issue报告一下。  
不知道有没有其他办法可以让anbox里也能访问外网，或者干脆放弃。

**Comment by drHuangMHT** [comment]
要翻用adb设置http代理为宿主就行了，我把事情搞复杂了

**Comment by yuhan6665** [comment]
似乎跟 wsa 一样没有 vpn module 所以只能用仅代理模式 另外这个跟 core 无关 先关了

**Comment by drHuangMHT** [comment]
了解。
