### ISSUE TITLE
证书问题permission denied

### ISSUE THREAD

**Issue by gh2020gh** [XTLS/Xray-core#825]
设置好之后，xray有很短一段时间提示active (running)的，但是无法正常代理。重启服务器端之后，就变成failed，输出如下

Active: failed (Result: exit-code) since Tue 2021-11-23 04:31:53 UTC; 5s ago
     Docs: https://github.com/xtls
  Process: 950 ExecStart=/usr/local/bin/xray run -config /usr/local/etc/xray/config.json (code=exited, status=23)
 Main PID: 950 (code=exited, status=23)

Nov 23 04:31:53 vultr.guest systemd[1]: Started Xray Service.
Nov 23 04:31:53 vultr.guest xray[950]: Xray 1.4.5 (Xray, Penetrates Everything.) Custom (go1.17.1 linux/amd64)
Nov 23 04:31:53 vultr.guest xray[950]: A unified platform for anti-censorship.
Nov 23 04:31:53 vultr.guest xray[950]: 2021/11/23 04:31:53 [Info] infra/conf/serial: Reading config: /usr/local/etc/xray/config.json
Nov 23 04:31:53 vultr.guest xray[950]: Failed to start: main: failed to load config files: [/usr/local/etc/xray/config.json] > infra/conf: Failed to build XTLS config. > infra/conf: failed to parse certificate > open /root/xray_cert/xray.crt: permission denied
Nov 23 04:31:53 vultr.guest systemd[1]: xray.service: Main process exited, code=exited, status=23/n/a
Nov 23 04:31:53 vultr.guest systemd[1]: xray.service: Failed with result 'exit-code'.

请问该如何解决呢？谢谢

**Comment by gh2020gh** [comment]
客户端配置如下
{
  "policy": {
    "system": {
      "statsOutboundUplink": true,
      "statsOutboundDownlink": true
    }
  },
  "log": {
    "loglevel": "debug"
  },
  "inbounds": [
    {
      "tag": "socks",
      "port": 10800,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "allowTransparent": false
      }
    },
    {
      "tag": "http",
      "port": 10801,
      "listen": "127.0.0.1",
      "protocol": "http",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "udp": false,
        "allowTransparent": false
      }
    },
    {
      "tag": "api",
      "port": 7468,
      "listen": "127.0.0.1",
      "protocol": "dokodemo-door",
      "settings": {
        "udp": false,
        "address": "127.0.0.1",
        "allowTransparent": false
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "a",
            "port": 443,
            "users": [
              {
                "id": "b",
                "alterId": 0,
                "email": "t@t.tt",
                "security": "auto",
                "encryption": "none",
                "flow": "xtls-rprx-direct"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
          "allowInsecure": false,
          "serverName": "c"
        }
      },
      "mux": {
        "enabled": false,
        "concurrency": -1
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    }
  ],
  "stats": {},
  "api": {
    "tag": "api",
    "services": [
      "StatsService"
    ]
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "domainMatcher": "linear",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api"
      },
      {
        "type": "field",
        "outboundTag": "proxy",
        "domain": [
          "geosite:google"
        ]
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": [
          "domain:example-example.com",
          "domain:example-example2.com"
        ]
      },
      {
        "type": "field",
        "outboundTag": "block",
        "domain": [
          "geosite:category-ads-all"
        ]
      }
    ]
  }
}

**Comment by gh2020gh** [comment]
服务器端就跟官方教学里面的一样

"log": {
    "loglevel": "warning",
    "access": "/root/xray_log/access.log",
    "error": "/root/xray_log/error.log"
  },

  "dns": {
    "servers": [
      "https+local://1.1.1.1/dns-query", 
      "localhost"
    ]
  },

  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "block"
      },
      {
        "type": "field",
        "domain": [
          "geosite:category-ads-all"
        ],
        "outboundTag": "block"
      }
    ]
  },

  "inbounds": [
    {
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "a", 
            "flow": "xtls-rprx-direct",
            "level": 0,
            "email": "t@t.tt"
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "dest": 80
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
          "allowInsecure": false, 
          "minVersion": "1.2",
          "alpn": ["http/1.1"],
          "certificates": [
            {
              "certificateFile": "/root/xray_cert/xray.crt",
              "keyFile": "/root/xray_cert/xray.key"
            }
          ]
        }
      }
    }
  ],

  "outbounds": [
    {
      "tag": "direct",
      "protocol": "freedom"
    },
    {
      "tag": "block",
      "protocol": "blackhole"
    }
  ]
}

**Comment by lillehammer-no** [comment]
请在 `/root/xray_cert/` 路径下尝试使用 `ls -l` 命令确认证书权限，如果权限不恰当，可参照 [这里](https://github.com/v2fly/fhs-install-v2ray/wiki/Insufficient-permissions-when-using-certificates-zh-Hans-CN) 修改。

**Comment by gh2020gh** [comment]
非常感谢您的回复！
我看了证书权限，是这样

-rwxr-xr-x 1 root root 324 Nov 22 19:15 xray-cert-renew.sh
-rw-r--r-- 1 root root   0 Nov 23 04:28 xray.crt
-rw-r--r-- 1 root root 227 Nov 23 04:28 xray.key

我对这些代码的事情不太懂，我只知道这三个是755，644，644，
看了您给的参考之后还是不懂，请问该怎么修改呢？谢谢

**Comment by Vohrt** [comment]
权限不对，把证书权限开给xray。嫌麻烦就直接sudo 安装 xray.见linux部署脚本仓库的使用管理员身份安装命令

**Comment by gh2020gh** [comment]
我试过了把证书权限开放给root之外的用户，但是还是同样的错误提示。我打算先重新安装一遍试试。非常感谢！

**Comment by lillehammer-no** [comment]
鱼：
在 `/root/xray_cert/ ` 下分别执行 `chmod 644 xray.crt ` 和 `chmod 644 xray.key`

渔：
搜索关键词“Linux 权限位”，弄懂 `r` `w` `x` 之类的含义，重读前面的 [文档](https://github.com/v2fly/fhs-install-v2ray/wiki/Insufficient-permissions-when-using-certificates-zh-Hans-CN)，搜索文中用到的命令的含义。再确切一下您使用的更新证书的方式如何处理权限问题（比如对于 acme.sh 来说，用户改成什么就是什么了），避免自动更新后出问题。

**Comment by gh2020gh** [comment]
> 鱼： 在 `/root/xray_cert/ ` 下分别执行 `chmod 644 xray.crt ` 和 `chmod 644 xray.key`
> 
> 渔： 搜索关键词“Linux 权限位”，弄懂 `r` `w` `x` 之类的含义，重读前面的 [文档](https://github.com/v2fly/fhs-install-v2ray/wiki/Insufficient-permissions-when-using-certificates-zh-Hans-CN)，搜索文中用到的命令的含义。再确切一下您使用的更新证书的方式如何处理权限问题（比如对于 acme.sh 来说，用户改成什么就是什么了），避免自动更新后出问题。

谢谢，我刚刚试过chmod 777给两个证书文件，但是还是一样的错误。
现在正在从头安装，如果有问题也希望还能得到各位的帮助，非常感谢！

**Comment by lillehammer-no** [comment]
不好意思！权限没问题，刚睡醒迷迷糊糊看错了……抱歉！

**Comment by lillehammer-no** [comment]
我仔细看了下您贴的 `ls` 输出结果，看上去 crt 文件的体积是 0，这里可能有问题

**Comment by gh2020gh** [comment]
重新安装并且将证书的权限设置为755之后已经解决了问题，大概确实是权限出了错。非常感谢各位的帮助！

**Comment by fjn308** [comment]
解决了就好（回头看我一本正经地瞎指点跟个大傻子似的，真是看错了……

**Comment by lillehammer-no** [comment]
解决了就好（回头看我一本正经地瞎指点跟个大傻子似的，真是看错了……

**Comment by yuhan6665** [comment]
solved

**Comment by Marryii** [comment]
遇到相同的问题找了两天。。最后在另外一个issue上有个人说是不是上层文件夹的权限不够，需要至少x。
因为其实跟教程的时候没多想，用的root，然后加上权限之后status就绿了。。差点放弃了

**Comment by chika0801** [comment]
> 遇到相同的问题找了两天。。最后在另外一个issue上有个人说是不是上层文件夹的权限不够，需要至少x。 因为其实跟教程的时候没多想，用的root，然后加上权限之后status就绿了。。差点放弃了

历史是 xray core安装脚本来自
v2fly那边，那边的作者有这个

https://github.com/v2fly/fhs-install-v2ray/wiki/Insufficient-permissions-when-using-certificates

你用root安装遇到不到，多半人不了解这些历史
