### ISSUE TITLE
不懂技术，斗胆问个关于服务端内存占用的问题

### ISSUE THREAD

**Issue by g552656** [XTLS/Xray-core#83]
vmess+ws+tls模式，多用户，之前用v2core4.22.1，centos7总内存占到800M左右
升级4.28之后的版本，会不断增加至2G，不重启v2ray就会被kill
xray核心也试过，一样的占用，
试过config.json模式和api增加用户模式都是一样的情况。

vless+ws+tls模式，同样规模用户，内存占用只有280M-300M

无奈vless目前无法订阅，只能使用vmess+ws+tls的模式
请问有没有参数可以调整或可能的方法可以降低vmess+ws+tls的服务端内存占用呢？
试过调整policy里bufferSize的值不管用，配置文件里也没有复杂的routing项目。

**Comment by rprx** [comment]
麻烦找出具体是哪个版本的 core 开始出现这个问题的，可能今天就能解决。

**Comment by rprx** [comment]
VMess 是改成了 0 代表 AEAD，可能是一些新的策略导致的。

**Comment by g552656** [comment]
应该是从4.26版本
因为现在的安装脚本没办法安装老版本所以没办法测试每一个版本

**Comment by vangork** [comment]
@g552656 提供给你添加API的代码帮你开了机场，你这找老大当起网管了 ：）

**Comment by g552656** [comment]
@vangork 见笑啦，自从4.28之后高内存一直困扰，目前只能循环重启服务解决。

**Comment by rprx** [comment]
无关用途，解决共同的问题是有必要的，但需要明确第一个出问题的版本，这样才能更快定位到问题（目前有些猜想）

建议手动替换上 4.26 前后几个版本的二进制文件逐一尝试，如果不会，可以请 @vangork 帮忙

**Comment by vangork** [comment]
@rprx 老大，你这是坑我。:(  最好也加上配置文件。

**Comment by g552656** [comment]
@rprx 
centos7 64bit，启动v2ray前的初始内存总占用137M
启动v2ray后的内存总占用
4.22.0	450M 
4.23.2	450M 
4.23.3	450M 
4.23.4	455M 
4.24.0	605M 
从4.23.4开始，稍微多了5M，4.24.0开始上了一个台阶
各版本都会随着使用内存增加，但是很明显从4.23.4（包括4.23.4）增长速度变快。

**Comment by rprx** [comment]
哪个版本开始会出现你描述的“不重启v2ray就会被kill”问题？且必须确定前一个版本无此问题

**Comment by g552656** [comment]
不重启会被kill这个问题，因为它会不断增长，占用快到总内存数的时候就有可能被杀死进程了
重点不在“不重启”在于内存占用基数大并且增长很快

**Comment by rprx** [comment]
确定 4.23.3 没有这个问题吗？或者说，最终不至于必须重启？

**Comment by g552656** [comment]
对的

**Comment by rprx** [comment]
v2fly/v2ray-core ？

**Comment by g552656** [comment]
是从https://github.com/v2fly/v2ray-core/releases下载测试的

**Comment by rprx** [comment]
大概确定是哪里的问题了，晚些时候我会传一些测试版本

**Comment by g552656** [comment]
好地多谢。

**Comment by rprx** [comment]
请及时测试并反馈

[Xray-linux-64.zip](https://github.com/XTLS/Xray-core/files/5713883/Xray-linux-64.zip)

**Comment by g552656** [comment]
大佬，我是需要先安装一个xray，然后替换这个文件这样吗？
因为现有的机器还都是v2ray

**Comment by rprx** [comment]
改名成 v2ray 后替换即可

**Comment by g552656** [comment]
原系统v2ray4.33.0用你这个改名替换后无法启动

我用新机器测试的是
初始占用总内存到630
5分钟后到723M
20分钟到768M
我在持续观察看看

**Comment by g552656** [comment]
2小时34分，1.18G
3小时38分，1.19G
看起来还是增长但是后期就比较缓慢了

**Comment by rprx** [comment]
本来认为是 VMess drain 一直不关闭的问题，后来发现它还是会 60 秒超时，不过我先把非纯粹连接时的 drain 机制关掉了 https://github.com/XTLS/Xray-core/commit/f390047b37ee1dc68a9b0af749816db4670ebb1d

**Comment by zhanglianbo35** [comment]
add swap
