### ISSUE TITLE
support UDP in tunnel/portal

### ISSUE THREAD

**Issue by ghost** [XTLS/Xray-core#833]
It seems that UDP can not go through tunnel and portal, which are used in the reverse proxy mode to expose local port to the internet.

The original v2fly/v2ray support this, so I wonder if this is related to the modification by x-ray on the mux protocol.

**Comment by bardolphshampine** [comment]
what is that tunnel/portal

**Comment by cyber9723470** [comment]
https://www.v2fly.org/config/reverse.html

**Comment by tonitaboeningkgu76** [comment]
If you want to implement tunneling, try dokodemo-door which does support UDP.

**Comment by cyber9723470** [comment]
@RPRX  was this related to https://github.com/XTLS/Xray-core/discussions/252 ?
Tunnel relies on Mux.Cool
