### ISSUE TITLE
在tproxy的透明代理入站的access log中显示域名

### ISSUE THREAD

**Issue by LinaChong** [XTLS/Xray-core#834]
在开启sniffing的前提下，socks入站可以在access log之直接看到域名，但如果是tproxy透明代理入站只看得到ip。
![1.PNG](https://i.loli.net/2021/12/01/GTPaIsAtgj1h2YJ.png)
将error log开到info级别，可以看到基于域名的路由选择（透明代理入站）
![2.PNG](https://i.loli.net/2021/12/01/a1H9uOlKRw4z5Uq.png)
我希望在透明代理入站的access log中也可以直接看到域名，而不用将error log开到info级别，感谢

**Comment by om2mo** [comment]
你在隔壁已经问过了，而且告诉你什么原因了，还要再发。socks5本地不处理DNS，你当然可以看到域名。
建议关闭这个issue。

**Comment by yuhan6665** [comment]
Close as expected
