### ISSUE TITLE
请问各位大佬, Linux系统下有木有类似V2rayN这种可以订阅机场/快速使用机场节点的客户端??

### ISSUE THREAD

**Issue by wutongskype** [XTLS/Xray-core#837]
请问各位大佬, Linux系统下有木有类似V2rayN这种可以订阅机场/快速使用机场节点的客户端??
使用环境, 比如国内有台小鸡, Linux系统的, 想快速使用机场节点扶墙.
目前俺手动安装xray, 再上传配置, 再改配置感觉太麻烦了,也没办法直接导入vmess://这种连接

**Comment by yuhan6665** [comment]
https://github.com/v2rayA/v2rayA
https://github.com/Qv2ray/Qv2ray
