### ISSUE TITLE
关于nginx监听

### ISSUE THREAD

**Issue by ShuzenKokoa** [XTLS/Xray-core#843]
想请问一下 如果设置了多个fallbacks

在nginx监听的时候 是监听443 就够了 还是 fallbacks的全部端口 还是不用监听 因为我这个是和博客共存..

**Comment by xyz3282836** [comment]
无法共存，xray会监听443端口，实际你请求80端口，nginx设置好rewrite 443，会自动跳到443，而xray检测到是网站流量会fallback到nginx中另外一个你设置的本地web端口

**Comment by orangeByte** [comment]
fallbacks是xray内部的分流,xray只会向外暴露一个端口
