### ISSUE TITLE
哪位大佬还在开发anXray吖,希望能增加个使用前置代理的功能,比如添加两个out服务器,其中一个指定另一个为前置代理

### ISSUE THREAD

**Issue by wutongskype** [XTLS/Xray-core#844]
哪位大佬还在开发anXray吖,
希望能增加个使用前置代理的功能,
比如添加两个out服务器,
其中一个指定另一个为前置代理
在文档里就是下面这两个, 应该不难实现吧
https://xtls.github.io/config/outbound.html#proxysettingsobject
https://www.v2fly.org/config/outbounds.html#proxysettingsobject

**Comment by bardolphshampine** [comment]
但是这就要改路由表，让前置代理的ip直连

**Comment by wutongskype** [comment]
> 

不用把,我目前本机上大概就是下面这个配置, 192.168.1.22是openwrt里面的机场, 但是本机上这么用太麻烦了, 经常要改配置.

	"outbounds": [
					/// 转发目标VmessTCP
					{
						"tag": "转发目标",
						"sendThrough": "0.0.0.0",
						"protocol": "vmess",
						"settings": {"vnext":[{
												"address": "123.com",
												"port": 123, /// 那个随机端口
												"users":[{"id":"123123123123","alterId":0,"security":"auto"}]}]
						},
						"proxySettings": {"tag": "前置代理1"}
					},
					
					
					
					
					/// 前置代理SOCKS5
					{	
						"tag": "前置代理1",
						"sendThrough": "0.0.0.0", /// 用于发送数据的IP地址
						"protocol": "socks",
						"settings": {"servers": [{"address": "192.168.1.22","port": 10800}]}
					},
    


	],
	
	"routing": {
				"domainStrategy": "AsIs",
				"rules": [{"type": "field", "inboundTag": ["ProxyIN"], "outboundTag": "转发目标"}]
	},

**Comment by bardolphshampine** [comment]
我的想法可能是港机做前置，美机做后置

**Comment by yuhan6665** [comment]
Not an issue for core
