### ISSUE TITLE
1.5.1中的Shadowsocks安全性增强，是否需要手动在配置文件中增加ivCheck: true

### ISSUE THREAD

**Issue by chika0801** [XTLS/Xray-core#856]
根据v2fly文档，此选项是要在客户端和服务器端同时配置。请问1.5.1更新是否和v2fly的文档说明一样，是手动配置此参数后生效？

https://github.com/v2fly/v2ray-core/pull/777#issuecomment-813963430

https://www.v2fly.org/config/protocols/shadowsocks.html#inboundconfigurationobject

https://www.v2fly.org/config/protocols/shadowsocks.html#outboundconfigurationobject

**Comment by yuhan6665** [comment]
你说的没错 我仔细看了一下 这里其实有两个问题

- Xray 在实现单端口多用户的时候引入了一个漏洞 可以使用简单的边界探查的特征（不需要重放流量 而是简单的发送随机流量）这个问题在 1.5.1 修复后不需要配置
- SS 协议不像 VMESS 协议本身缺乏防重放机制 这个问题 *ray 一直都存在 1.5.1 把布隆过滤器搬来之后可以缓解这个问题 需要在配置中打开 ivCheck: true

我去更新一下 release note

**Comment by chika0801** [comment]
> 你说的没错 我仔细看了一下 这里其实有两个问题
> 
> * Xray 在实现单端口多用户的时候引入了一个漏洞 可以使用简单的边界探查的特征（不需要重放流量 而是简单的发送随机流量）这个问题在 1.5.1 修复后不需要配置
> * SS 协议不像 VMESS 协议本身缺乏防重放机制 这个问题 *ray 一直都存在 1.5.1 把布隆过滤器搬来之后可以缓解这个问题 需要在配置中打开 ivCheck: true
> 
> 我去更新一下 release note

感谢你的工作和回复。我懂了，结论是需要在客户端与服务器端相应位置增加ivCheck: true。我猜这个参数默认是false。
