### ISSUE TITLE
有observatory使用文档吗

### ISSUE THREAD

**Issue by Traced** [XTLS/Xray-core#858]
你好，有模块单独使用文档吗

**Comment by CHIZI-0618** [comment]
先看v2fly那边的文档吧, [ObservatoryObject](https://www.v2fly.org/config/observatory.html) .

**Comment by BI7PRK** [comment]
关于 probeURL 参数，默认内构地址为`api.v2fly.org`。那么这个地址否可以随便一个可用的地址呢？例如：openwrt.org.
还是这个地址是需要有特定的返回状态呀？

**Comment by CHIZI-0618** [comment]
看起来这边的默认probeURL是`https://www.google.com/generate_204`
代码在这里 https://github.com/XTLS/Xray-core/blob/main/app/observatory/observer.go#L157
