### ISSUE TITLE
测速链接重定向

### ISSUE THREAD

**Issue by jwstaceyOvO** [XTLS/Xray-core#865]
有些服务器到测速域名的延迟偏高,是否可以实现类似的需求？
检测到测速链接[https://www.google.com/generate_204](url)，则重定向为127.0.0.1的host,谷歌搜索不受影响

**Comment by yuhan6665** [comment]
你可以设置测速链接 probeURL https://www.v2fly.org/config/observatory.html#observatoryobject

**Comment by jwstaceyOvO** [comment]
请问这个可以影响客户端默认测速链接测试的结果吗？我想要的是客户端的测速链接在服务端上重定向到127.0.0.1，不需要更改客户端测速链接

yuhan6665 ***@***.***> 于2021年12月20日周一 10:17写道：

**Comment by yuhan6665** [comment]
由于是去 google 的真链接所以服务器无法重定向，不然就失去意义了。如果不想要这个特性，可以把连接改成不加密的 http

**Comment by jwstaceyOvO** [comment]
目前我可以改www.google.com为127.0.0.1，但是如此会导致谷歌无法访问，所以想问是否有特化url的实现，比如针对url:
/generate_204才解析为127.0.0.1,其余正常解析

yuhan6665 ***@***.***> 于2021年12月20日周一 10:31写道：

**Comment by yuhan6665** [comment]
path 加密的 所以不可能

**Comment by jwstaceyOvO** [comment]
那对于http的测速链接是否可以实现以上效果?如果有,如何实现

yuhan6665 ***@***.***> 于2021年12月20日周一 10:39写道：
