### ISSUE TITLE
[question] 关于OpenWRT与Windows客户端环境运行速率差异的疑问

### ISSUE THREAD

**Issue by BI7PRK** [XTLS/Xray-core#866]
各位大佬，鄙人自从使用了V1.5.0（包括服务端与客户端） 的版本后，发现不同客户端环境下存在不同速率的问题。请教一下主要是什么原因呢？

## Pi3：
<html><body>

项 | 版本
-- | --
型号 | Raspberry Pi 3 Model B Rev 1.2
架构 | ARMv8 Processor rev 4
固件版本 | OpenWrt 21.02.1 r16325-88151b8303 / LuCI openwrt-21.02 branch git-21.340.48972-61cc3b1
内核版本 | 5.4.154

</body>
</html>

## Windows 使用 v2rayN GUI 
对比均在同一时间段与同一网络环境，Windows 速率高于 OpenWRT 约1100Kbps 左右

**Comment by tritu** [comment]
ur Rpi 3B doesn’t support AES and its CPU is out of date
