### ISSUE TITLE
关于证书权限除了user=root还有什么优雅的解决方法吗

### ISSUE THREAD

**Issue by orangeByte** [XTLS/Xray-core#867]
之前一直懒省事直接user = root,前几天看到了一位同学在issue中提到可以新建用户readcert,chown root:readcert / example && chmod 640 /example 最后在systemd加入Group=readcert 但是我还是失败了🤔, 请问有什么其他方法吗, 或烦请指导.

**Comment by choicky** [comment]
我使用 caddy 生产证书。 caddy 用 `www-data` 用户运行。
xray 也用 `www-data`  运行。

**Comment by orangeByte** [comment]
@choicky 感谢建议,这是一个非常不错的方法,可惜我使用的是Certbot获取证书,这可能对我没有用,但对使用Caddy的可能非常有帮助👍

**Comment by huangguiniab** [comment]
创建新用户xray，拉入ssl-cert用户组
````
sudo addgroup --system ssl-cert
# 这个用户组一般系统自带，但是有的系统没有，所以这里仍然创建一次，如果已经存在，就会创建失败，请直接忽略
sudo adduser --system xray-server
sudo usermod -aG ssl-cert xray-server
````
root用户添加计划任务在crontab里面
任务含义：每5分钟重置一次权限
````
*/5 * * * * chown root ssl-cert -R /etc/ssl/private/
*/5 * * * * chmod 0740 -R /etc/ssl/private/
````
systemd配置文件里面
````
User=xray-server
Group=xray-server
````
大功告成，接下来将只要证书安装到/etc/ssl/private/目录里面，任何ssl-cert组的用户都能读取里面的证书，其他非root非组内成员无法读取

**Comment by orangeByte** [comment]
@huangguiniab 谢谢,这对我很重要😘
