### ISSUE TITLE
[BUG] Change client ip in access log to real client ip instead of 127.0.0.1 (accessing from fallbacks option)

### ISSUE THREAD

**Issue by aztecrabbit** [XTLS/Xray-core#870]
I want to limit 1 user 1 ip. But it's not possible if i use fallbacks option, because access log will give the client ip 127.0.0.1 instead of real client ip.

Can i make client ip always show real client ip instead of 127.0.0.1? Even if i use fallbacks option?

Or maybe can this project add option to limiting ip of 1 user, like in trojan-go do?

**Comment by malikshi** [comment]
> Or maybe can this project add option to limiting ip of 1 user, like in trojan-go do?

Bro can you share the script? xD

**Comment by orangeByte** [comment]
> > Or maybe can this project add option to limiting ip of 1 user, like in trojan-go do?
> 
> Bro can you share the script? xD

Do you want to get trojan-go script? you can search it in github.

**Comment by aztecrabbit** [comment]
> Bro can you share the script? xD

For limiting ip of 1 user? I'm using their api, https://p4gefau1t.github.io/trojan-go/advance/api/

**Comment by malikshi** [comment]
> > Bro can you share the script? xD
> 
> For limiting ip of 1 user? I'm using their api, https://p4gefau1t.github.io/trojan-go/advance/api/

Thanks bro
