### ISSUE TITLE
freedom=useip加上内定DOH可以对出口鸡隐藏所访问的域名吗?

### ISSUE THREAD

**Issue by wutongskype** [XTLS/Xray-core#876]
VPS是一台腾讯的轻量云-HK, 我想对它隐藏我想访问的域名, 这样freedom=useip加上内定DOH可以达到效果吗?
配置如下图
![image](https://user-images.githubusercontent.com/40192806/147656714-527de265-a96f-48ed-9f36-bcaaad7a99b3.png)

**Comment by yuhan6665** [comment]
Use DOH should be ok, you don't need UseIp in freedom outbound
