### ISSUE TITLE
请问有教程没？业务域名及FQ域名

### ISSUE THREAD

**Issue by viponedream** [XTLS/Xray-core#878]
我有一个正式网站 a.com
然后 x.a.com 作为翻墙用的。
请问要怎么配置？
有没有可以参考的啊。 google全网都没有一个成功的。

我参考了这些都没搭成功。
https://wan.lu/2021/xray-nginx-reuse-port-443.html
https://www.orzlee.com/proxy/2021/04/13/nginx-sni-offload-port-multiplexing-uses-xray-vless-xtls.html/comment-page-1
https://lala.im/7666.html

它显示这个错误 
2021/12/30 06:14:52 [error] 504#504: *634 no host in upstream "", client: 223.74.123.177, server: 0.0.0.0:443, bytes from/to client:0/0, bytes from/to upstream:0/0

单纯打开网站是可以正常显示网站内容了
a.com
x.a.com
单独打开这两个网站都是正常了，证书也正常。就是不能翻墙。

**Comment by viponedream** [comment]
[配置文件.zip](https://github.com/XTLS/Xray-core/files/7790858/default.zip)

**Comment by Ansen** [comment]
你应该先去看官方文档

**Comment by thisdk** [comment]
官方有安装和升级脚本,官方还有最佳配置示例.这些已经很方便了.只要你有https证书,最后只是改改https证书位置就能跑了.当然这是最基础的玩法.

**Comment by zxbiao** [comment]
你需要有一定的动手能力，然后参考这个：
https://blog.xmgspace.me/archives/nginx-sni-dispatcher.html

**Comment by viponedream** [comment]
> 你需要有一定的动手能力，然后参考这个： https://blog.xmgspace.me/archives/nginx-sni-dispatcher.html

好。谢谢。我试下
