### ISSUE TITLE
期待shadowsocks也能支持unix domain socket监听

### ISSUE THREAD

**Issue by ghost** [XTLS/Xray-core#882]
ss listen那项不用127.0.0.1用unix domain socket也能实现监听

转发效率比127.0.0.1高

**Comment by cod1ingcoding** [comment]
如果从效率来说，回环lo的效率其实比unix domain socket只低一点点， 不会成为网络瓶颈。

**Comment by Cptmacmillan2022007** [comment]
> 目前unix domain socket还没实现SOCK_DGRAM，也就是说加上unix domain socket支持也只能接受转发tcp，不能接受转发udp

所以只能用127.0.0.1喽？

**Comment by lucifer9** [comment]
> > 目前unix domain socket还没实现SOCK_DGRAM，也就是说加上unix domain socket支持也只能接受转发tcp，不能接受转发udp
> 
> 所以只能用127.0.0.1喽？

不用UDP的话，稍微修改一下应该可以支持监听unix domain socket
不过都用shadowsocks了大部分还是为了用上udp吧...

**Comment by Cptmacmillan2022007** [comment]
> > > 目前unix domain socket还没实现SOCK_DGRAM，也就是说加上unix domain socket支持也只能接受转发tcp，不能接受转发udp
> > 
> > 
> > 所以只能用127.0.0.1喽？
> 
> 不用UDP的话，稍微修改一下应该可以支持监听unix domain socket 不过都用shadowsocks了大部分还是为了用上udp吧...

是的
