### ISSUE TITLE
DNS请求流程

### ISSUE THREAD

**Issue by timeday1102** [XTLS/Xray-core#885]
这种dns配置下，加入我想访问google.com ，它是通过哪个dns地址查询google.com的ip呢？

访问google.com -> routing理由规则中查询不到 -> dns查询获取ip -> 通过 “https://223.5.5.5/dns-query”地址查询ip -> 被 “dns-out”出站代理拦截？ 换成“8.8.8.8” 查询？
还有，通过任意门6450端口进来的dns查询，是直接去“1.0.0.1” 查询， 还是被 “dns-out”出站代理拦截？ 换成“8.8.8.8” 查询？

![image](https://user-images.githubusercontent.com/57295339/148053076-75640e39-3912-4a87-815a-908c0406c29e.png)

**Comment by yuhan6665** [comment]
both will go to https://223.5.5.5/dns-query

**Comment by timeday1102** [comment]
> 两者都将转到https://223.5.5.5/dns-query

thank you
