### ISSUE TITLE
同一节点，移动联通宽带皆可用，电信宽带无法使用，手机电脑上测试都一样

### ISSUE THREAD

**Issue by sdshdv** [XTLS/Xray-core#887]
就这几天开始出现的，感觉很奇怪，我好几个节点都出现了这样的情况，移动联通无报错正常可用，电信完全无法使用，不知道有没有人和我同样情况的
报错内容：
2022/01/05 13:30:08 [Warning] [1251333804] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://ww2.521011.ml/Zh87Gmd0/):  > dial tcp: lookup ww2.521011.ml: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server.
2022/01/05 13:30:08 [Warning] [715161736] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://ww2.521011.ml/Zh87Gmd0/):  > dial tcp: lookup ww2.521011.ml: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server.

**Comment by yuhan6665** [comment]
DNS 解析 ww2.521011.ml 无回应 用 IP 试试

**Comment by sdshdv** [comment]
发现原因了，是因为电信宽带抽风无法解析出ml结尾的域名ip导致的，今天恢复了，又正常了
