### ISSUE TITLE
XBOX NAT类型限制 UDP 100%丢包

### ISSUE THREAD

**Issue by dddtc2005** [XTLS/Xray-core#888]
试了一下用VLESS+XTLS节点加速XBOX UDP，用XBOX自带网络测试观察到：

1. NAT类型为限制
2. 多人游戏网络测试为100%丢包

请各位帮忙看看问题可能出在什么地方？

端到端的配置情况为：

- 路由器通过Openwrt Passwall使用Xray透明代理，开启TCP和UDP节点（为同一个节点）
- XBOX (LAN IP: 192.168.2.81)通过Access control代理白名单，TCP代理常用端口（22,25,53,143,465,587,853,993,995,80,443），UDP代理所有端口
- 路由器开启了fullcone NAT, SYN-flood防御
- 路由器对XBOX做了 UDP 1-65536 端口转发
- VPS上允许了XBOX相关端口（TCP:53,80,3074, UDP:53,80,88,500,3074,3075,3544,4500）
- VPS上允许了UDP high ports (1024-65535)

相关log和配置见附件，这是一个端到端NAT测试的抓包。多人游戏测试有点大，如果这个信息量不够，也可以上传。
（为便于上传，JSON重命名了TXT）
[vps_server_xray_config_json.txt](https://github.com/XTLS/Xray-core/files/7815964/vps_server_xray_config_json.txt)
[router_iptables_proccessed.txt](https://github.com/XTLS/Xray-core/files/7815965/router_iptables_proccessed.txt)
[router_tcp_node_processed.log](https://github.com/XTLS/Xray-core/files/7815966/router_tcp_node_processed.log)
[router_tcp_xray_config_json.txt](https://github.com/XTLS/Xray-core/files/7815967/router_tcp_xray_config_json.txt)
[router_udp_node_proccessed.log](https://github.com/XTLS/Xray-core/files/7815968/router_udp_node_proccessed.log)
[router_udp_xray_config_json.txt](https://github.com/XTLS/Xray-core/files/7815969/router_udp_xray_config_json.txt)
[vps_access_proccessed.log](https://github.com/XTLS/Xray-core/files/7815986/vps_access_proccessed.log)
[vps_error_processed.log](https://github.com/XTLS/Xray-core/files/7815987/vps_error_processed.log)

**Comment by yuhan6665** [comment]
试一下手机或者 PC 客户端 不走路由器看一下 NAT

**Comment by dddtc2005** [comment]
> 试一下手机或者 PC 客户端 不走路由器看一下 NAT

谢谢建议。多做了几个测试。直接用PC xray-core 来访问可以确认NAT没有问题，并且测试结果看上去非常合理。多做了几个组合方便其他人参考：
| 路由器 端口转发 | VPS 防火墙 Inbound IP规则                                        | VPS 防火墙 Inbound Port规则 | Mapping             | Filtering               | NatTypeTester                |
|-----------------|--------------------------------------------------------|-----------------|---------------------|-------------------------|------------------------------|
| 无              | *                                                      | Allow 1024-65535      | EndpointIndependent | EndpointIndependent     | NAT 1 (Full Cone)            |
| 无              | Allow Router WAN IP Allow NatTypeTester stun server IP | *               | EndpointIndependent | AddressDependent        | NAT 2 (Restricted Cone)      |
| 无              | Allow Router WAN IP                                    | Allow 1024-65535      | EndpointIndependent | AddressAndPortDependent | NAT 3 (Port Restricted Cone) |
| 无              | Allow NatTypeTester Stun server IP                                   | Allow 1024-65535      | EndpointIndependent | AddressAndPortDependent | NAT 3 (Port Restricted Cone) |

之后路由器开启Passwall，从XBOX端用自带测试，得到的结果是：

- NAT 开放
- 多人游戏网络测试 丢包100%

暂时只做了以下两组测试，要找个时间再看看这个多人游戏测试丢包是为什么。
| Passwall | Passwall代理TCP                              | Passwall代理UDP | 路由器 端口转发                 | VPS防火墙 Inbound IP规则 | VPS防火墙 Inbound Port规则 | XBOX NAT | XBOX 多人游戏丢包率 |
|----------|----------------------------------------------|-----------------|---------------------------------|--------------------------|----------------------------|----------|---------------------|
| 开启     | 22,25,53,143,465,587,853,993,995,80,443,3074 | 全部            | 无                              | *                        | 1024-65535                 | Open     | 100%                |
| 开启     | 22,25,53,143,465,587,853,993,995,80,443,3074 | 全部            | 转发TCP 1-65535 转发UDP 1-65535 | *                        | 1024-65535                 | Open     | 100%                |
| 开启     | 全部                                         | 全部            | 转发TCP 1-65535 转发UDP 1-65535 | *                        | 1024-65535                 | Strict   | 100%                |

**Comment by f0re1gnKey** [comment]
关掉fullcone

**Comment by xhqpp** [comment]
upnp开了没有

**Comment by dddtc2005** [comment]
并不是下面这两个原因
> 关掉fullcone

> upnp开了没有

仔细排查了一下，发现是VPS 对XBOX Live Server 3074 端口发出的UDP包都是有去无回。
真正的原因是需要在VM上 [Turn Off Path MTU Discovery Feature](https://github.com/shadowsocks/shadowsocks-libev/issues/361#issuecomment-366837628)

甄别的关键是看IP Frame里面是否有set Don't frame flag
![Differences](https://user-images.githubusercontent.com/12397121/148562261-5d548ae2-2ed5-4e29-ae78-104831c9ffa2.jpg)

**Comment by xhqpp** [comment]
把ip_no_pmtu_disc里0改成1是这样吗

**Comment by dddtc2005** [comment]
> 把ip_no_pmtu_disc里0改成1是这样吗

是的

**Comment by Yohengg** [comment]
> 
跟你一样的问题，但是完全不知道怎么解决

**Comment by Lua12138** [comment]
> > 
> 
> 跟你一样的问题，但是完全不知道怎么解决

`echo 1 > /proc/sys/net/ipv4/ip_no_pmtu_disc`

**Comment by aqing779** [comment]
我的ip_no_pmtu_disc 里面是没内容的，空白文档
