### ISSUE TITLE
VLESS 回落到https-web

### ISSUE THREAD

**Issue by Fhokud** [XTLS/Xray-core#89]
VLESS的回落能不能去到其他网站服务器（https）

这样在配置回落的时候就可以直接把认证失败的流量拐到另一个web，不用自建web，配置节省时间。

**Comment by rprx** [comment]
一开始就有这样的想法，搁置了一段时间，不过现在我们可以继续增强回落分流功能了

**Comment by Fhokud** [comment]
还有几个想法
让xray支持返回一个合法的http301，在443回落到https-web的情况下监听80端口。
这样仅需要一个xray就可以快速建设一个完美伪装的web服务器

**Comment by Fhokud** [comment]
还有就是针对这个回落加一个限速，防止被搜索引擎抓走了后成了镜像/反代网站了

**Comment by shenlijun** [comment]
回落到其它web上的IP不一定能保护你自己的IP吧，你这样的分流行为表现就不正常

其实个人更希望回落能完全替代nginx之类的功能，这样家里搭建的服务就不用走“xray回落---vps上的nginx反向代理端口----xray反向代理管道-家里的服务器”这样奇怪的路径了

也许是我没掌握精髓？可以不用这么麻烦？ @rprx

**Comment by shenlijun** [comment]
> 还有一个想法
> 让xray支持返回一个合法的http301，在443回落到https-web的情况下监听80端口。
> 这样仅需要一个xray就可以快速建设一个完美伪装的web服务器

同求

**Comment by eMeab** [comment]
> > 还有一个想法
> > 让xray支持返回一个合法的http301，在443回落到https-web的情况下监听80端口。
> > 这样仅需要一个xray就可以快速建设一个完美伪装的web服务器
> 
> 同求

这种很不合理。 你监听的80端口跳去其他SNI的443端口 为什么呢？

**Comment by Fhokud** [comment]
> > > 还有一个想法
> > > 让xray支持返回一个合法的http301，在443回落到https-web的情况下监听80端口。
> > > 这样仅需要一个xray就可以快速建设一个完美伪装的web服务器
> > 
> > 
> > 同求
> 
> 这种很不合理。 你监听的80端口跳去其他SNI的443端口 为什么呢？

301到你自己的443端口啊

**Comment by Fhokud** [comment]
> 回落到其它web上的IP不一定能保护你自己的IP吧，你这样的分流行为表现就不正常
> 
> 其实个人更希望回落能完全替代nginx之类的功能，这样家里搭建的服务就不用走“xray回落---vps上的nginx反向代理端口----xray反向代理管道-家里的服务器”这样奇怪的路径了
> 
> 也许是我没掌握精髓？可以不用这么麻烦？

https访问你自己的域名到你自己的443端口 但web内容来自其他网站（http/https），这样就不会是一个简单的示例网站，同时还能节省部署时间，全部由xray处理

80端口不是空着吗
http 301你自己的域名到https，不整其他的

**Comment by shenlijun** [comment]
> > 回落到其它web上的IP不一定能保护你自己的IP吧，你这样的分流行为表现就不正常
> > 其实个人更希望回落能完全替代nginx之类的功能，这样家里搭建的服务就不用走“xray回落---vps上的nginx反向代理端口----xray反向代理管道-家里的服务器”这样奇怪的路径了
> > 也许是我没掌握精髓？可以不用这么麻烦？
> 
> https访问你自己的域名到你自己的443端口 但web内容来自其他网站（http/https），这样就不会是一个简单的示例网站，同时还能节省部署时间，全部由xray处理
> 
> 80端口不是空着吗
> http 301你自己的域名到https，不整其他的

我还整了其它的在自己家里，所以要反向代理，现在是中间得过一下nginx，xray直接处理不了

web内容来自其他网站（http/https），就表示从外部看来你有莫名的分流，不知道会不会被当作是一种特征

**Comment by eMeab** [comment]
> > 回落到其它web上的IP不一定能保护你自己的IP吧，你这样的分流行为表现就不正常
> > 其实个人更希望回落能完全替代nginx之类的功能，这样家里搭建的服务就不用走“xray回落---vps上的nginx反向代理端口----xray反向代理管道-家里的服务器”这样奇怪的路径了
> > 也许是我没掌握精髓？可以不用这么麻烦？
> 
> https访问你自己的域名到你自己的443端口 但web内容来自其他网站（http/https），这样就不会是一个简单的示例网站，同时还能节省部署时间，全部由xray处理
> 
> 80端口不是空着吗
> http 301你自己的域名到https，不整其他的

完全可以不用80端口啊. 你只是需要直接反代别人的网站这个功能

**Comment by Fhokud** [comment]
> > > 回落到其它web上的IP不一定能保护你自己的IP吧，你这样的分流行为表现就不正常
> > > 其实个人更希望回落能完全替代nginx之类的功能，这样家里搭建的服务就不用走“xray回落---vps上的nginx反向代理端口----xray反向代理管道-家里的服务器”这样奇怪的路径了
> > > 也许是我没掌握精髓？可以不用这么麻烦？
> > 
> > 
> > https访问你自己的域名到你自己的443端口 但web内容来自其他网站（http/https），这样就不会是一个简单的示例网站，同时还能节省部署时间，全部由xray处理
> > 80端口不是空着吗
> > http 301你自己的域名到https，不整其他的
> 
> 完全可以不用80端口啊. 你只是需要直接反代别人的网站这个功能
精辟

**Comment by Fhokud** [comment]
> > > 回落到其它web上的IP不一定能保护你自己的IP吧，你这样的分流行为表现就不正常
> > > 其实个人更希望回落能完全替代nginx之类的功能，这样家里搭建的服务就不用走“xray回落---vps上的nginx反向代理端口----xray反向代理管道-家里的服务器”这样奇怪的路径了
> > > 也许是我没掌握精髓？可以不用这么麻烦？
> > 
> > 
> > https访问你自己的域名到你自己的443端口 但web内容来自其他网站（http/https），这样就不会是一个简单的示例网站，同时还能节省部署时间，全部由xray处理
> > 80端口不是空着吗
> > http 301你自己的域名到https，不整其他的
> 
> 完全可以不用80端口啊. 你只是需要直接反代别人的网站这个功能

精辟，就这个

**Comment by LsnmxNB** [comment]
大佬上一下配置文件

> > > 回落到其它web上的IP不一定能保护你自己的IP吧，你这样的分流行为表现就不正常
> > > 其实个人更希望回落能完全替代nginx之类的功能，这样家里搭建的服务就不用走“xray回落---vps上的nginx反向代理端口----xray反向代理管道-家里的服务器”这样奇怪的路径了
> > > 也许是我没掌握精髓？可以不用这么麻烦？
> > 
> > 
> > https访问你自己的域名到你自己的443端口 但web内容来自其他网站（http/https），这样就不会是一个简单的示例网站，同时还能节省部署时间，全部由xray处理
> > 80端口不是空着吗
> > http 301你自己的域名到https，不整其他的
> 
> 完全可以不用80端口啊. 你只是需要直接反代别人的网站这个功能

**Comment by Fhokud** [comment]
Fallback可否支持回落到https
