### ISSUE TITLE
希望程序在找不到geosite.dat或geoip.dat时依然执行，而不是直接退出

### ISSUE THREAD

**Issue by lededev** [XTLS/Xray-core#890]
由于这两个文件比较大，一些小闪存路由器装不下，一旦配置了`geo*`之后，就会因文件不存在，总是启动失败。
然而xray起不来，程序也就没办法上外网去下载这两个文件到tmpfs内存盘里并重启xray来启用`geo*.dat`，这就出现一个先有鸡还是先有蛋的问题。
因此建议xray在加载`geo*.dat`失败后放弃geo规则继续执行，而不是直接退出。

**Comment by yuhan6665** [comment]
因为 xray 不支持热重载 你下载好了 横竖需要重启的 我觉得可以准备两个配置 一个不带 geosite geoip 一个完整的

**Comment by bitching** [comment]
> 因为 xray 不支持热重载 你下载好了 横竖需要重启的 我觉得可以准备两个配置 一个不带 geosite geoip 一个完整的

强烈建议作者加入hot reload，就跟nginx -s reload一样。

**Comment by yaotthaha** [comment]
可以试试cdn.jsdelivr.net

另外这个问题我在v2ray那边discussion提了
https://github.com/v2fly/v2ray-core/discussions/1537

**Comment by forever8938** [comment]
所以为什么透明代理还需要用dat文件分流？

**Comment by lededev** [comment]
> 所以为什么透明代理还需要用dat文件分流？

例如油管的那些站点只走油管专用线路，谷歌的其他站点只走另一条专业线路，奈飞的站点只走奈飞的专用线路。
很多人并非自己架个VPS只有一条线路那种。

**Comment by forever8938** [comment]
> > 所以为什么透明代理还需要用dat文件分流？
> 
> 例如油管的那些站点只走油管专用线路，谷歌的其他站点只走另一条专业线路，奈飞的站点只走奈飞的专用线路。
> 很多人并非自己架个VPS只有一条线路那种。

你没有VPS吗，把dat文件放到你的VPS上不就能下载了

**Comment by forever8938** [comment]
你的这个需求可以用dnsmasq和ipset实现，把域名列出来就行了，

**Comment by yaotthaha** [comment]
本地分流，例如教育网，学术网站，都很有用的。

另外，相比使用dnsmasq ipset，ray的根据geo资源文件更加简单

**Comment by lededev** [comment]
> 你的这个需求可以用dnsmasq和ipset实现，把域名列出来就行了，

再比如广告过滤，用geosite来描述就一句`geosite:category-ads`就行了，简单优雅，比起把所有广告站点的域名都列出来省事多了把。

**Comment by forever8938** [comment]
广告域名更应该用dnsmasq，因为包括墙内的域名，全部解析到127.0.0.1。category-ads-all只有几百条。

**Comment by yaotthaha** [comment]
就是把所有流量导入ray，让ray分流
