### ISSUE TITLE
如何升级xray-core到1.5.2？现在anxray内嵌的才1.4.5

### ISSUE THREAD

**Issue by huweitianc** [XTLS/Xray-core#892]
如何升级xray-core到1.5.2？现在anxray内嵌的才1.4.5

**Comment by waloyn** [comment]
里面不光xray低，clash也低，版本是1.6.5，但是当前最新版本是1.9.0
这个项目大概率是已经弃用了，看发布频道的消息，说是包括上游在内的维护困难，然后在play已购买的全部退款了。

**Comment by owmyfeellings** [comment]
可惜了这个好项目
