### ISSUE TITLE
使用doh时出现Post "https://dns.google/dns-query": context canceled

### ISSUE THREAD

**Issue by GeorgeRudd** [XTLS/Xray-core#893]
```[Error] app/dns: failed to retrieve response for mabping.chartbeat.net. > Post "https://dns.google/dns-query": context canceled```

客户端dns配置 用的是v2rayn 并且8.8.8.8和dns.google已经加到代理列表里了
```
{
	"hosts": {
		"dns.google": "8.8.8.8",
		"dns.alidns.com": "223.5.5.5"
	},
	"servers": [
		{
			"address": "https://dns.google/dns-query"
		},
		{
			"address": "https+local://dns.alidns.com/dns-query",
			"domains": [
				"geosite:cn"
			],
			"expectIPs": [
				"geoip:cn"
			]
		}
	]
}
```
服务端
```
{
	"hosts": {
		"dns.google": "8.8.8.8"
	},
	"servers": [
		{
			"address": "https+local://dns.google/dns-query"
		}
	]
}
```
请大神指点 谢谢

**Comment by yuhan6665** [comment]
需要看一下服务端日志 确保请求发给服务端了

**Comment by gcphym** [comment]
> 需要看一下服务端日志 确保请求发给服务端了

服务端 error.log 只看到一条
 [Info] app/dns: DNS: created Local DOH client for https://dns.google/dns-query

**Comment by yuhan6665** [comment]
你的客户端分流可能有问题 8.8.8.8 是不是没有走代理

**Comment by gcphym** [comment]
> 你的客户端分流可能有问题 8.8.8.8 是不是没有走代理

你好 8.8.8.8和dns.google已经在代理列表里

**Comment by yuhan6665** [comment]
看一下客户端完整配置和日志吧

**Comment by dotNetDR** [comment]
我也遇到这个问题。
