### ISSUE TITLE
我发现大家都不用4MB的最新geosite规则，而只用最新的geoip规则，这是为什么？

### ISSUE THREAD

**Issue by xnxnsu** [XTLS/Xray-core#9]

**Comment by rprx** [comment]
Xray v1.0.0 带的 geoip.dat 和 geosite.dat 是 v2fly/v2ray-core 仓库内的。

**Comment by badO1a5A90** [comment]
这一个是域名规则,一个是IP规则,没有什么联系或冲突.
而且我不知道你这个结论哪里来的,比如我自己就用geosite,也同时用geoip.

**Comment by jdnt** [comment]
geosite域名规则非常省心，特别是需要对某些网站做转发的时候

**Comment by shenlijun** [comment]
这取决于这个设置，如果用IPNoMatch就会先用geosite
  "routing": {
    "domainStrategy": "IPOnDemand",

**Comment by rprx** [comment]
看起来此问题不存在，目前打包的是 v2fly 的而不是 Loyalsoldier 的，之后可能会维护一份 Project X 的。

**Comment by lxsjgzs** [comment]
> 这取决于这个设置，如果用IPNoMatch就会先用geosite
> "routing": {
> "domainStrategy": "IPOnDemand",

请问若是 AsIs 的话会优先使用哪个文件？

**Comment by shenlijun** [comment]
> > 这取决于这个设置，如果用IPNoMatch就会先用geosite
> > "routing": {
> > "domainStrategy": "IPOnDemand",
> 
> 请问若是 AsIs 的话会优先使用哪个文件？

"AsIs": 只使用域名进行路由选择。默认值。
"IPIfNonMatch": 当域名没有匹配任何规则时，将域名解析成 IP（A 记录或 AAAA 记录）再次进行匹配；
当一个域名有多个 A 记录时，会尝试匹配所有的 A 记录，直到其中一个与某个规则匹配为止；
解析后的 IP 仅在路由选择时起作用，转发的数据包中依然使用原始域名；
"IPOnDemand": 当匹配时碰到任何基于 IP 的规则，将域名立即解析为 IP 进行匹配；

**Comment by lxsjgzs** [comment]
> > > 这取决于这个设置，如果用IPNoMatch就会先用geosite
> > > "routing": {
> > > "domainStrategy": "IPOnDemand",
> > 
> > 
> > 请问若是 AsIs 的话会优先使用哪个文件？
> 
> "AsIs": 只使用域名进行路由选择。默认值。
> "IPIfNonMatch": 当域名没有匹配任何规则时，将域名解析成 IP（A 记录或 AAAA 记录）再次进行匹配；
> 当一个域名有多个 A 记录时，会尝试匹配所有的 A 记录，直到其中一个与某个规则匹配为止；
> 解析后的 IP 仅在路由选择时起作用，转发的数据包中依然使用原始域名；
> "IPOnDemand": 当匹配时碰到任何基于 IP 的规则，将域名立即解析为 IP 进行匹配；

Thanks xd
