### ISSUE TITLE
http outbound存在阻塞问题

### ISSUE THREAD

**Issue by zhouh047** [XTLS/Xray-core#901]
似乎是Xray继承了V2ray导致的，V2ray那边有人提出过。
原问题地址：
https://github.com/v2ray/v2ray-core/issues/2731
问题复现：
https://github.com/v2ray/v2ray-core/issues/2731#issuecomment-691490454

**Comment by yuhan6665** [comment]
https://github.com/v2fly/v2ray-core/pull/189/
这个是分家之前修的 xray 已经有了
