### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by chenxqiyu** [XTLS/Xray-core#905]
v1.4.3 vmess协议的alertid填写正常访问，从v1.4.5之后都无法正常使用，必须设置alertid成0才行。【bug反馈】

v1. 4.3 fill in the alertid of vmess protocol for normal access, from v1.1 It cannot be used normally after 4.5. You must set alertid to 0. [bug feedback]

**Comment by yuhan6665** [comment]
这个不是 bug 是 feature
vmess md5 已经不安全所以默认禁用 xray.vmess.aead.forced 环境变量可以允许
