### ISSUE TITLE
在网页上测速后的一段时间内Xray仍然有大量下行流量

### ISSUE THREAD

**Issue by Kukuair** [XTLS/Xray-core#909]
我在V2RayN那边也有提这个问题，2dust给了我一个Xray的issue网址，所以我又来这边寻求答案了，问题就是我在 http://test.ustc.edu.cn/ 测速完以后(已经关闭网页标签或关闭浏览器)之后的十多秒时间内发现火绒的流量统计里Xray仍然有大量的下行流量，给人一种在下载测速没有完成的感觉或是Xray没有收到 “已经测速结束”的反馈导致仍然在下载 。
另外，我在退出V2RayN以后也尝试过再次测速，并没有复现该问题。
  详细的问题描述及日志还麻烦去这里查看 https://github.com/2dust/v2rayN/issues/2001#issue-1106988597

**Comment by kingcanfish** [comment]
老bug 了
https://github.com/v2fly/v2ray-core/issues/374
https://github.com/Dreamacro/clash/issues/1387
https://github.com/XTLS/Xray-core/issues/232

**Comment by HaoweiCh** [comment]
还没解决吗

**Comment by mand-byte** [comment]
v1.5.10 还是存在这个bug
