### ISSUE TITLE
能否为vless引入aead加密

### ISSUE THREAD

**Issue by Cptmacmillan2022007** [XTLS/Xray-core#910]
功能需求相关

可以配合已有的tls进一步增强安全性

vless本体一直没加密有点不放心

**Comment by xtccc** [comment]
加密，性能会下降吧，
vless的特点不就是只加密一次吗

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Cptmacmillan2022007 ***@***.***>
Sent: Monday, January 24, 2022 5:36:54 PM
To: XTLS/Xray-core ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [XTLS/Xray-core] 能否为vless引入aead加密 (Issue #910)


功能需求相关

可以配合已有的tls进一步增强安全性

vless本体一直没加密有点不放心

―

**Comment by xtccc** [comment]
加密，性能会下降吧，

vless的特点不就是只加密一次吗
________________________________
From: Cptmacmillan2022007 ***@***.***>
Sent: Monday, January 24, 2022 5:36:54 PM
To: XTLS/Xray-core ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [XTLS/Xray-core] 能否为vless引入aead加密 (Issue #910)


功能需求相关

可以配合已有的tls进一步增强安全性

vless本体一直没加密有点不放心

―

**Comment by yuhan6665** [comment]
vmess ~= vless + aead

**Comment by heiyubaiyu** [comment]
你这跟要求手机电池重新做成可拆卸一样，给我整无语了，vless本来就是有tls之后为了减少vmess不必要的二次加密才做出来的，想再加密回去用vmess😶

**Comment by kbr3NwSZ6kFq25** [comment]
> vmess ~= vless + aead

那在底层传输中加密 quic 数据包后直接使用vless过墙可以吗
