### ISSUE TITLE
請問shadowsocks舊協議跟多開問題

### ISSUE THREAD

**Issue by LiMoon** [XTLS/Xray-core#929]
因有些機場還在使用 AES_256_CFB，本來想透過 https://github.com/XTLS/Xray-core/pull/710/files 内修改的檔案回推回去，但有些代碼似乎已經在1.5.3最新版本消失 無法加回去再編譯，但本身又對GO語言不熟..也不知道要從何下手
後來試過 同台機器上運行 1.4.3 跟 最新版本 1.5.2 的，但發現 開了 1.5.2 後，在開 1.4.3 會互相衝突。
還是，是我的命令下錯了呢？ 謝謝。
```
d:\xray1.5.2
xray.exe run -confdir conf
```

1.4.3 我有把 xray 改成 xray2, 同時 port 有另外換新的, 與 1.5不使用同個port
```
d:\xray1.4.3
xray2.exe run -confdir conf
```

**Comment by yuhan6665** [comment]
你是说多开客户端？一般没有用 因为浏览器只会给一个 inbound port 发请求

**Comment by LiMoon** [comment]
想要不同版本在windows上開 xray.exe 。
例如 1.4.3 還能使用 outbounds的 shadowsocks AES_256_CFB加密協議(機場只有這個加密協議) ，TV 透過 inbounds 連入。
然後 其他ip 就改走 1.5.3 outbounds的版本。

主要是因為 1.5.3 不支持shadowsocks AES_256_CFB加密協議了

**Comment by LiMoon** [comment]
我測試時是不行的, 會互相衝突。
開了 1.4.3 xray, 而1.5的inbounds 就會無法連入, 相反先開了 1.5, 則1.4.3就無法連入該inbounds 設定

**Comment by jeffery9** [comment]
https://github.com/yanue/V2rayU/issues/1109  the same issue.

**Comment by jeffery9** [comment]
#1890
