### ISSUE TITLE
trojan-go插件，提示 专有设备供应商 篡改了你的安卓系统，不能用是什么原因呢

### ISSUE THREAD

**Issue by V0idk** [XTLS/Xray-core#937]

**Comment by lacafjh** [comment]
遇到同样的问题，之前解决过但是找不到那个 issue 了，可能是 AnXray 的 issue （已经关闭）里面的。

**Comment by slayercjc** [comment]
我也是这个问题，解决了吗

**Comment by addspell** [comment]
同问，naive插件也显示这个，是华为荣耀系的不支持吗？

**Comment by Angel0726** [comment]
> 同问，naive插件也显示这个，是华为荣耀系的不支持吗？

小米也是

**Comment by chika0801** [comment]
插件给后台权限，比如miui无限制

**Comment by Angel0726** [comment]
> 插件给后台权限，比如miui无限制

怎么设置

**Comment by Angel0726** [comment]
> 插件给后台权限，比如miui无限制

谢谢已经解决

**Comment by Starsocks** [comment]
华为手机：打开手机管家-应用启动管理-手动管理-开启允许自启动、允许关联启动、允许后台活动，就OK了

**Comment by MerlinLam** [comment]
> > 同问，naive插件也显示这个，是华为荣耀系的不支持吗？
> 
> 小米也是
小米只要把proxy 的自启动打开就可以了。

**Comment by G-Sea** [comment]
> 华为手机：打开手机管家-应用启动管理-手动管理-开启允许自启动、允许关联启动、允许后台活动，就OK了

感谢

**Comment by AndySkaura** [comment]
oppo:关联启动->trojan go->开启
