### ISSUE TITLE
proxy/vless/encoding: failed to read response version > remote error: tls: unrecognized name

### ISSUE THREAD

**Issue by lovewe** [XTLS/Xray-core#938]
自己搭建的服务，使用v2rayN 与 Xray 1.5.3 客户端连不上，查看日志出现
app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to decode response header > proxy/vless/encoding: failed to read response version > remote error: tls: unrecognized name

请问怎么解决

**Comment by yuhan6665** [comment]
应该是 tls 设置问题 看看 sni 是不是填错

**Comment by lovewe** [comment]
> 应该是 tls 设置问题 看看 sni 是不是填错

谢谢，已找到原因，证书生成的有问题

**Comment by fuyarchuk-kg** [comment]
what was wrong with certificates? i have the same issue

**Comment by Navidd777** [comment]
How did you solve it?
