### ISSUE TITLE
1.5.3 路由器版本 内存泄露严重

### ISSUE THREAD

**Issue by thinker007** [XTLS/Xray-core#943]
运行一周多内存占用达到170M

环境：asus ax86u 
版本：arm64v8

**Comment by shenlijun** [comment]
买个联想P350 tiny，插个r8125t4的网卡
装server2022，hyper v虚拟个openwrt，把r8125t4直通，再分个4g内存

windows装chrome可以硬解8k插电视，openwrt跑满10G都有可能😄

这样生活就没有烦恼了

**Comment by ZqinKing** [comment]
> 买个联想P350 tiny，插个r8125t4的网卡 装server2022，hyper v虚拟个openwrt，把r8125t4直通，再分个4g内存
> 
> windows装chrome可以硬解8k插电视，openwrt跑满10G都有可能😄
> 
> 这样生活就没有烦恼了

想多了。不上DPDK数据交换平面，X86的CPU跑不到10Gbps

**Comment by shenlijun** [comment]
> > 买个联想P350 tiny，插个r8125t4的网卡 装server2022，hyper v虚拟个openwrt，把r8125t4直通，再分个4g内存
> > windows装chrome可以硬解8k插电视，openwrt跑满10G都有可能😄
> > 这样生活就没有烦恼了
> 
> 想多了。不上DPDK数据交换平面，X86的CPU跑不到10Gbps

啊，确实说的有语病
其实想表达的是这个CPU可能支持到10G带宽的翻

而且一张4口2.5的网卡它也翻不了10G

**Comment by jliveusa** [comment]
的确占用大了，ax6 2天用到130m，触发oom

**Comment by cod1ingcoding** [comment]
golang占用170m内存算大吗？
