### ISSUE TITLE
第二次 Trojan Fallback 回落 与 h2c的问题？

### ISSUE THREAD

**Issue by tomxiang1** [XTLS/Xray-core#944]
![image](https://user-images.githubusercontent.com/45867336/154411499-e7763827-a114-47db-9eff-ac3d8fe1ecc2.png)
![image](https://user-images.githubusercontent.com/45867336/154411691-b4526fe1-5658-40b5-bd67-bca407741a7d.png)
问题就是Trojan客户端配置不能带有h2配置 如:"alpn":["h2","http/1.1"] ，只能删除h2写死成"alpn":["http/1.1"]配置后Trojan才能正常工作。

**Comment by BioniCosmos** [comment]
尝试将网站回落都放在 trojan 协议下。

**Comment by tomxiang1** [comment]
> 尝试将网站回落都放在 trojan 协议下。

已经试过了不行，感觉第二次回落，alpn信息已经拿不到了，无法区分h2和http1.1，Nginx又非要搞两个端口，所以现在已经换caddy2了。

**Comment by blog2020** [comment]
楼主，不换caddy有解决方法吗

**Comment by lxhao61** [comment]
> 楼主，不换caddy有解决方法吗

有办法，思路参考如下：
https://github.com/lxhao61/integrated-examples/blob/main/v2ray(E%2BB%2BC%2BF%2BA)%2Bnginx/1_v2ray_config.json

**Comment by blog2020** [comment]
@lxhao61  多谢大佬，好人一生平安
