### ISSUE TITLE
XRay客户端与服务器之间自动协商加密套件的玄学

### ISSUE THREAD

**Issue by tomxiang1** [XTLS/Xray-core#946]
![image](https://user-images.githubusercontent.com/45867336/154432165-09622cde-819f-47c9-beb3-b0aa5b7902f2.png)

![image](https://user-images.githubusercontent.com/45867336/154432520-0d7f8ddd-099b-40e9-abad-5e2885ef1f13.png)

默认情况下XRay都是用 TLS_AES_128_GCM_SHA256 套件，但是对于老机器如J1900不支持AES硬件加密用CHACHA20_POLY1305明显要快于AES，试了很多次XRay客服端配置中的cipherSuites里把chacha系列的加密套件写到最前面也不行，下发时会自动排序成固定顺序并且Tls1.3的AES套件永远删除不了郁闷了(Trojan的cipher与cipher_tls13都可以自定义顺序和数量)。
最后测试到崩溃边缘才发现

![image](https://user-images.githubusercontent.com/45867336/154435319-2a4090a7-5ad4-4e6c-8e1f-204196ccf249.png)

删除以上四个套件后奇迹产生了
![image](https://user-images.githubusercontent.com/45867336/154435639-0a45a002-ccf3-4bc7-a698-41c57d32bb6c.png)

在XRay客服端配置中的cipherSuites (已经删除上面的四个套件)
"cipherSuites":"TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256:TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256:TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA:TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA:TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA:TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA:TLS_RSA_WITH_AES_128_GCM_SHA256:TLS_RSA_WITH_AES_256_GCM_SHA384:TLS_RSA_WITH_AES_128_CBC_SHA:TLS_RSA_WITH_AES_256_CBC_SHA:TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA:TLS_RSA_WITH_3DES_EDE_CBC_SHA:TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256",

![image](https://user-images.githubusercontent.com/45867336/154435999-70fc7ad0-e21d-4a5d-8599-462ba74e6474.png)

![image](https://user-images.githubusercontent.com/45867336/154436098-75521f0c-8abb-4957-8a57-1a16cd1d13c7.png)

 不支持AES硬件解码的老机有希望了，玄学的XRay

**Comment by yuhan6665** [comment]
删除即说明客户端不支持这些套件 是预期现象
不删除的情况下要使用 chacha 可能需要改服务端套件
