### ISSUE TITLE
使用VLESS+TLS/XTLS+TCP

### ISSUE THREAD

**Issue by lfxx** [XTLS/Xray-core#95]
大佬您好，使用以上搭配，一旦ip被封是不是就不能用了，这样看来，VLESS+TLS+WS[CDN]是不是更保险点。能不能同时设置VLESS+TLS/XTLS+TCP和VLESS+TLS+WS[CDN]？

**Comment by AkinoKaede** [comment]
可以 參見 `https://github.com/XTLS/Xray-examples/tree/main/VLESS-TCP-XTLS-WHATEVER`

**Comment by lfxx** [comment]
好的谢谢
