### ISSUE TITLE
[solved]关于 Xray 回落设置中 proxy protocol 功能的疑惑

### ISSUE THREAD

**Issue by benhon-han** [XTLS/Xray-core#950]
Xray 配置了回落至 Nginx 真实站点，Xray 与 Nginx 之间使用 Unix domain socket 通信。Xray 的回落设置中启用 xver 参数并设置了值为 1。

Web 服务器上跑了一个 HTML5 测速的程序，测速时页面会显示来访者  IP 地址。（ https://github.com/librespeed/speedtest ）

现在遇到一个问题，使用 Cloudflare CDN 时，Nginx 可以获取到来访者的真实 IP 地址，（说明 Xray 确实向后给 Nginx 传递了真实来访 IP。）但是不使用 CDN 时，来访者 IP 地址显示错误为 “***unix:***”。

先前觉得问题出在 Nginx 的 set_real_ip_from 设置上，~~因为 set_real_ip_from 设置不支持 Unix domain socket 文件路径~~，但是想到启用 CDN 时又能正常获取正确来访 IP 地址，应该不是 Nginx 配置的问题。

目前还不知道问题出在哪儿，不知该如何解决。

Xray 配置文件：
```
{
  "inbounds": [
    {
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "UUID-UUID-UUID-UUID",
            "flow": "xtls-rprx-direct"
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "name": "xxx.com",
            "dest": "/dev/shm/default.sock",
            "xver": 1
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
          "minVersion": "1.2",
          "alpn": [
            "http/1.1"
          ],
          "certificates": [
            {
              "certificateFile": ".../xxx.com.crt",
              "keyFile": ".../xxx.com.key"
            }
          ]
        }
      }
    }
  ]
}
```

Nginx 配置：
```
server {
    listen unix:/dev/shm/default.sock proxy_protocol;
    server_name xxx.com;
    include .../cloudflare_ip.conf
    ... ...
}
```

cloudflare_ip.conf 内容
```
# cloudflare ips
# https://www.cloudflare.com/ips/
set_real_ip_from 127.0.0.1;
set_real_ip_from 173.245.48.0/20;
set_real_ip_from 103.21.244.0/22;
set_real_ip_from 103.22.200.0/22;
set_real_ip_from 103.31.4.0/22;
set_real_ip_from 141.101.64.0/18;
set_real_ip_from 108.162.192.0/18;
set_real_ip_from 190.93.240.0/20;
set_real_ip_from 188.114.96.0/20;
set_real_ip_from 197.234.240.0/22;
set_real_ip_from 198.41.128.0/17;
set_real_ip_from 162.158.0.0/15;
set_real_ip_from 172.64.0.0/13;
set_real_ip_from 131.0.72.0/22;
set_real_ip_from 104.16.0.0/13;
set_real_ip_from 104.24.0.0/14;
set_real_ip_from 2400:cb00::/32;
set_real_ip_from 2606:4700::/32;
set_real_ip_from 2803:f800::/32;
set_real_ip_from 2405:b500::/32;
set_real_ip_from 2405:8100::/32;
set_real_ip_from 2a06:98c0::/29;
set_real_ip_from 2c0f:f248::/32;

# use any of the following two
#real_ip_header CF-Connecting-IP;
real_ip_header X-Forwarded-For;

real_ip_recursive on;
```

**Comment by BioniCosmos** [comment]
```nginx
set_real_ip_from unix:/dev/shm/default.sock;
real_ip_header proxy_protocol;
```

**Comment by benhon-han** [comment]
> ```nginx
> set_real_ip_from unix:/dev/shm/default.sock;
> real_ip_header proxy_protocol;
> ```

@BioniCosmos 你好，在 Niginx 配置文件中添加了相关条目后，Nginx 的配置自检无法通过。
```
[user@server ~]# nginx -v
nginx version: nginx/1.20.0

[user@server ~]# nginx -t

nginx: [emerg] host not found in set_real_ip_from "unix:/dev/shm/default.sock" in .../cloudflare_ip.conf:2
nginx: configuration file /etc/nginx/nginx.conf test failed
```

**Comment by BioniCosmos** [comment]
Congratulations! Closed.

**Comment by soliujing** [comment]
> real_ip_header proxy_protocol;

@benhon-han 
我做了类似的配置，变更为proxy_protocol以后，通过cloudflare CDN的流量就会指向CDN的IP，非原始请求IP。

原因是通过proxy_protocol定位到的就是CDN的IP。只有如下配置可以取得原始IP。
```
#real_ip_header CF-Connecting-IP;
real_ip_header X-Forwarded-For;
```

不过在real_ip_header未修正的情况下，依然可以通过`$http_x_forwarded_for`，在nginx的log里记录相应内容；但是其他module，比如mod_security只会使用**real_ip**做相应的过滤规则。

如果确认问题的话，能否xray做此变更, 在fallback时添加x-forwarded-for header?
@BioniCosmos 

nginx log 配置
```
    log_format  main  '$remote_addr - $remote_user [$time_local] - $host - "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
```

响应的log内容，域名和原始IP打码了，保留了CF的IP

```
==> /var/log/nginx/access.log <==

172.70.122.186 - - [27/Feb/2022:20:42:35 -0500] - www.example.com - "HEAD / HTTP/1.1" 200 0 "-" "curl/7.79.1" "11.22.33.104"
11.22.33.104 - - [27/Feb/2022:20:42:41 -0500] - example.com - "HEAD / HTTP/1.1" 301 0 "-" "curl/7.79.1" "-"
11.22.33.104 - - [27/Feb/2022:20:42:42 -0500] - example.com - "HEAD / HTTP/1.1" 200 0 "-" "curl/7.79.1" "-"
```

**Comment by benhon-han** [comment]
> 
> 通过cloudflare CDN的流量就会指向CDN的IP，非原始请求IP。
> 

你需要先在 Nginx 配置中“定义” CDN 的节点地址。

```
# cloudflare ips
# https://www.cloudflare.com/ips/
set_real_ip_from 127.0.0.1;
set_real_ip_from 173.245.48.0/20;
set_real_ip_from 103.21.244.0/22;
set_real_ip_from 103.22.200.0/22;
set_real_ip_from 103.31.4.0/22;
set_real_ip_from 141.101.64.0/18;
set_real_ip_from 108.162.192.0/18;
set_real_ip_from 190.93.240.0/20;
set_real_ip_from 188.114.96.0/20;
set_real_ip_from 197.234.240.0/22;
set_real_ip_from 198.41.128.0/17;
set_real_ip_from 162.158.0.0/15;
set_real_ip_from 172.64.0.0/13;
set_real_ip_from 131.0.72.0/22;
set_real_ip_from 104.16.0.0/13;
set_real_ip_from 104.24.0.0/14;
set_real_ip_from 2400:cb00::/32;
set_real_ip_from 2606:4700::/32;
set_real_ip_from 2803:f800::/32;
set_real_ip_from 2405:b500::/32;
set_real_ip_from 2405:8100::/32;
set_real_ip_from 2a06:98c0::/29;
set_real_ip_from 2c0f:f248::/32;
```

**Comment by soliujing** [comment]
@benhon-han 
感谢回复，我的测试都是在制定set_real_ip_from 包括CDN节点的情况下测试得到的。

从[nginx 文档](https://nginx.org/en/docs/http/ngx_http_realip_module.html) 可以知道
```
set_real_ip_from -> Defines trusted addresses that are known to send correct replacement addresses.
real_ip_header -> Defines the request header field whose value will be used to replace the client address.
```
这两个需要同时指定，才可以从相应request header取得来源地址。

我的服务器路径大致如下：
直连：      example.com ->                     xray: 443 -> fallback 127.0.0.1:10443, xver: 1 (pass original IP to proxy_protocol) -> nginx listening 10443 proxy_protocol;
CF : www.example.com -> CF: 443 -> xray: 443 -> fallback 127.0.0.1:10443, xver: 1 (pass CF IP to proxy_protocol) -> nginx listening 10443 proxy_protocol;

分析：
-1 Cloudflare转发时会添加X-Forwarded-For header
-2 xray fallback时会根据传递request IP， 直连就是client IP，从CF转发的就是CDN节点地址；不会增加X-Forwarded-For header给到后续
-3 realip模块会在信任地址内(set_real_ip_from)根据指定的header(real_ip_header)来判定原始地址，可惜不能设定按多个来源尝试。

3就是冲突所在.

现状：
```
real_ip_header X-Forwarded-For;  可以获取通过CF的流量，直连的流量由于fallback转发时未添加x-forwarded-for，没有header可以参照，保留127.0.0.1作为来源地址
```

```
real_ip_header proxy_protocol;  可以获取直连的流量， CF的流量由于proxy_protocol传递来的是CF节点地址，所以CF节点就被设定为来源IP，即使set_real_ip_from指定CF节点也无法进一步追溯，同时x-forwarded-for里面包含真实请求来源
```
经多次测试以上二者不能共存，甚至尝试过用[headers-more-nginx](https://github.com/openresty/headers-more-nginx-module)来修改x-forwarded-for，也没有得到预期的结果。

能否共享一下server的access log来确认一下问题？
非常感谢🙏

**Comment by benhon-han** [comment]
我服务器上 Nginx 与 XRay 日志全部都禁用了，回落分流未使用端口而且使用 Unix domain socket，目前无论是否启用 CDN ，Web 服务器都能获取正确来访 IP。以下是详细配置，你看是否可以参考。

客户端
```
{
  "outbounds": [
    {
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "xxx.xxx.xxx.xxx",
            "port": 443,
            "users": [
              {
                "id": "UUID-UUID-UUID-UUID",
                "flow": "xtls-rprx-direct",
                "encryption": "none"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
          "serverName": "xxx.com"
        }
      }
    }
  ]
}
```
服务器端
```
{
  "inbounds": [
    {
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "UUID-UUID-UUID-UUID",
            "flow": "xtls-rprx-direct"
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "alpn": "h2",
            "name": "xxx.com",
            "dest": "/dev/shm/h2c.sock",
            "xver": 1
          },
          {
            "name": "xxx.com",
            "dest": "/dev/shm/default.sock",
            "xver": 1
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
          "minVersion": "1.2",
          "alpn": [
            "h2",
            "http/1.1"
          ],
          "certificates": [
            {
              "certificateFile": ".../xxx.com.crt",
              "keyFile": ".../xxx.com.key"
            }
          ]
        }
      }
    }
  ]
}
```
Nginx 配置
```
server {
    listen unix:/dev/shm/h2c.sock http2 proxy_protocol;
    listen unix:/dev/shm/default.sock proxy_protocol;

    server_name xxx.com;

    include .../cloudflare_ip.conf;
    ... ...
}
```
cloudflare_ip.conf
```
# cloudflare ips
set_real_ip_from unix:;
set_real_ip_from 127.0.0.1;
set_real_ip_from 173.245.48.0/20;
set_real_ip_from 103.21.244.0/22;
set_real_ip_from 103.22.200.0/22;
set_real_ip_from 103.31.4.0/22;
set_real_ip_from 141.101.64.0/18;
set_real_ip_from 108.162.192.0/18;
set_real_ip_from 190.93.240.0/20;
set_real_ip_from 188.114.96.0/20;
set_real_ip_from 197.234.240.0/22;
set_real_ip_from 198.41.128.0/17;
set_real_ip_from 162.158.0.0/15;
set_real_ip_from 104.16.0.0/13;
set_real_ip_from 104.24.0.0/14;
set_real_ip_from 172.64.0.0/13;
set_real_ip_from 131.0.72.0/22;
set_real_ip_from 2400:cb00::/32;
set_real_ip_from 2606:4700::/32;
set_real_ip_from 2803:f800::/32;
set_real_ip_from 2405:b500::/32;
set_real_ip_from 2405:8100::/32;
set_real_ip_from 2a06:98c0::/29;
set_real_ip_from 2c0f:f248::/32;

# use any one of the following
#real_ip_header CF-Connecting-IP;
#real_ip_header X-Forwarded-For;
real_ip_header proxy_protocol;

real_ip_recursive on;
```

**Comment by BioniCosmos** [comment]
@soliujing 您说的问题经过测试的确存在，从 Xray 传来的 Proxy Protocol 数据包中只会保留 CDN 地址。目前可行的解决措施是让 nginx 前置。

@benhon-han 

> 另外，服务器如有多个站点并且使用通配证书的话，回落分流不要使用 HTTP/2.0 (h2)。

可否对这句话进行解释？

**Comment by benhon-han** [comment]
> @soliujing 您说的问题经过测试的确存在，从 Xray 传来的 Proxy Protocol 数据包中只会保留 CDN 地址。~目前可行的解决措施是让 nginx 前置~。所以 `real_ip_header` 不使用 `proxy_protocol` 而使用 `X-Forwarded-For` 或 `CF-Connecting-IP` 即可解决。
> 
> @benhon-han
> 
> > 另外，服务器如有多个站点并且使用通配证书的话，回落分流不要使用 HTTP/2.0 (h2)。
> 
> 可否对这句话进行解释？

实际应用中发现的一个问题：

比如服务器上同时运行着两个站点 xxx.com 与 sub.xxx.com ，使用一张 xxx.com *.xxx.com 通配证书，XRay 同时为两个站点开启 HTTP/2.0 回落时，会出现两个站点相互“串流”的现象，如果为不同的站点使用不同的证书则没有这个问题。

看了部分其他的 issue 里说到，是因为 HTTP/2.0 的工作方式有别于 HTTP/1.1 导致的。

**Comment by soliujing** [comment]
> @soliujing 您说的问题经过测试的确存在，从 Xray 传来的 Proxy Protocol 数据包中只会保留 CDN 地址。目前可行的解决措施是让 nginx 前置。所以 real_ip_header 不使用 proxy_protocol 而使用 X-Forwarded-For 或 CF-Connecting-IP 即可解决。

@BioniCosmos 您的说法比较符合我测试的结果，以及对文档的解读。所以目前没有优雅的方案能同时记录“直连”以及“CF转发”的原始请求地址。

暂时想到一个方案，还没有经过测试，理论上应该可行的。
`就是nginx上再套一层转发，转发时将proxy_protocol_remote_address 写入 X-Forwarded-For，下游监听使用x-forwarded-for获取原始IP。`

大致访问路径如下：
直连： example.com -> xray: 443 -> fallback 127.0.0.1:10443, xver: 1 (pass original IP to proxy_protocol) -> nginx 10443 proxy_protocol, forward to 11443 (set x-forwarded-for to when it is BLANK) -> nginx 11443
CF : [www.example.com](http://www.example.com/) -> CF: 443 -> xray: 443 -> fallback 127.0.0.1:10443, xver: 1 (pass CF IP to proxy_protocol) -> nginx 10443 proxy_protocol , forward to 11443 (pass original XFF when not BLANK) -> nginx 11443

在nginx 11443 使用X-Forwarded-For获取来源地址，就能同时记录“直连”以及“CF转发”的原始请求地址了 ：）
只是多一层转发会效率下降，总觉得怪怪的。

> 我服务器上 Nginx 与 XRay 日志全部都禁用了，回落分流未使用端口而使用 Unix domain socket，目前无论是否启用 CDN ，Web 服务器都能获取正确来访 IP。

@benhon-han 非常感谢分享，如果不是在日志中而是web app中能获取来访IP的话，我的猜测是对应的web app本身做了相应的X-Forwarded-For对来源IP进行定位。虽然X-REAL-IP是CF的地址，但是App可以综合XFF来判定。

单纯技术讨论，如果方便的话可否打开nginx 访问日志，确认一下我的猜想是否正确？
```
    log_format  main  '$remote_addr - $remote_user [$time_local] - $host - "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
```
预期结果：日志中显示为x-real-ip （CDN节点IP），XFF为正确IP； 但是相应的app可以获取到来源IP。
我在同一服务器上有私人网盘服务，获取到的也是正确IP。

**Comment by BioniCosmos** [comment]
@benhon-han 可以看看[这篇教程](https://moecm.com/v2ray/the-vless-protocol-masquerading-and-the-fallback-mechanisms-for-routing-by-domain-names/)。

**Comment by BioniCosmos** [comment]
@soliujing `real_ip_header X-Forwarded-For;` 不能获取真实 IP 地址吗？

**Comment by soliujing** [comment]
> @soliujing `real_ip_header X-Forwarded-For;` 不能获取真实 IP 地址吗？

额，我的情况有点特殊。 

`real_ip_header X-Forwarded-For;`对经过CF中转的流量可以获取IP。
我有个别服务是不能过CDN访问的，会直连xray的443端口然后fallback转发到nginx localhost端口，此时XFF值为空，无法获取到real-ip，日志中就记录为127.0.0.1 ：）

综合考虑，还是使用了real_ip_header proxy_protocol; 对直连的流量记录；
同时在web app里综合XFF + X-real-ip 做来源判断。

现在问题主要是：CF转发的流量，nginx传入mod_security的x-real-ip 为CF节点，无法按HTTPBL来过滤。
所以在考虑方案，从源头去解决。

**Comment by BioniCosmos** [comment]
@soliujing I see. Xray 的回落只是一个玩具属性的东西，nginx stream 能做到的事也不多，也许 HAProxy 可以实现吧。

另外像你说的那样将 nginx 作为中转修改 HTTP Headers 应该是一个可行的方法。

**Comment by soliujing** [comment]
> @soliujing I see. Xray 的回落只是一个玩具属性的东西，nginx stream 能做到的事也不多，也许 HAProxy 可以实现吧。
> 
> 另外像你说的那样将 nginx 作为中转修改 HTTP Headers 应该是一个可行的方法。

了解了，多谢解惑。
nginx中转套娃的方式，后续有时间会去测试看看。HAProxy也可以了解一下。

**Comment by soliujing** [comment]
@BioniCosmos 测试了套娃，得到预期结果。 Problem resolved.. 有空再研究HAproxy吧。

```
server {
	listen  127.0.0.1:7443 proxy_protocol;
	set_real_ip_from 127.0.0.1;
	real_ip_header proxy_protocol;
	real_ip_recursive on;

	proxy_redirect off;  
	proxy_http_version 1.1;
	proxy_set_header Host $host ;
	proxy_set_header X-Real-IP $proxy_protocol_addr; 
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for ;  
... ...
    location / {
		proxy_pass http://127.0.0.1:9443;
	}
}

server {
	listen  127.0.0.1:9443;

	set_real_ip_from 127.0.0.1;
	## real_ip behind Cloudclare
	set_real_ip_from 103.21.244.0/22;
......
	real_ip_header X-Forwarded-For;
	real_ip_recursive on;
......
}
```

Nginx access log:

```
111.222.333.444 - - [28/Feb/2022:19:56:42 -0500] - example.com - "HEAD / HTTP/1.1" 200 0 "-" "curl/7.79.1" "111.222.333.444"
111.222.333.444 - - [28/Feb/2022:19:56:50 -0500] - www.example.com - "HEAD / HTTP/1.1" 200 0 "-" "curl/7.79.1" "111.222.333.444, 172.70.214.182"
```

**Comment by soliujing** [comment]
@benhon-han 
查阅[librespeed-speedtest源码](https://github.com/librespeed/speedtest)，证实了我的猜测：）

> 我服务器上 Nginx 与 XRay 日志全部都禁用了，回落分流未使用端口而使用 Unix domain socket，目前无论是否启用 CDN ，Web 服务器都能获取正确来访 IP。
> 
> @benhon-han 非常感谢分享，如果不是在日志中而是web app中能获取来访IP的话，我的猜测是对应的web app本身做了相应的X-Forwarded-For对来源IP进行定位。虽然REMOTE_ADDR是CF的地址，但是App可以综合XFF来判定。

```
    } elseif (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {
        $ip = $_SERVER['HTTP_X_FORWARDED_FOR'];
        $ip = preg_replace('/,.*/', '', $ip); # hosts are comma-separated, client is first
    } else {
        $ip = $_SERVER['REMOTE_ADDR'];
    }
```

代码可见：XFF优先级大于REMOTE_ADDR：
- CF转发的流量，会添加XFF，此时getIP获取到的为XFF对应IP信息，即真实地址；REMOTE_ADDR为CF节点，优先级靠后不生效。
- 直连流量，XFF为空，REMOTE_ADDR获取到的为proxy_protocol传入的remote address，即原始IP。

故两种情况下，都可以取得原始IP。结案！

欢迎技术探讨。
