### ISSUE TITLE
关于Quic和BBR

### ISSUE THREAD

**Issue by Hfenger** [XTLS/Xray-core#951]
谷歌的Quic自带BBR加速，Xray内置的Quic集成了BBR拥塞控制不？如果没集成未来有计划不？线路不佳的服务器用UDP目前来说简直是灾难，但是Quic的优势又太多了。

**Comment by yuhan6665** [comment]
QUIC's congestion control is based on TCP NewReno [[RFC6582](https://datatracker.ietf.org/doc/html/rfc6582)]
