### ISSUE TITLE
request:optimize log print,especially some useless log print 

### ISSUE THREAD

**Issue by FranzKafkaYu** [XTLS/Xray-core#953]
Hi:
Recently I configured my config.json as follows:

  "log": {
    "access": "/usr/local/log/access.log",
    "error": "/usr/local/log/error.log",
    "loglevel": "warning",
    "dnsLog": false
  }

and then I checked my log,found there existed too many useless logs like these:
**2022/02/20 15:16:16 127.0.0.1:57228 accepted tcp:127.0.0.1:0 [api]
2022/02/20 15:16:26 127.0.0.1:57230 accepted tcp:127.0.0.1:0 [api]
2022/02/20 15:16:36 127.0.0.1:57232 accepted tcp:127.0.0.1:0 [api]
2022/02/20 15:16:46 127.0.0.1:57234 accepted tcp:127.0.0.1:0 [api]
2022/02/20 15:16:56 127.0.0.1:57236 accepted tcp:127.0.0.1:0 [api]
2022/02/20 15:17:06 127.0.0.1:57238 accepted tcp:127.0.0.1:0 [api]
2022/02/20 15:17:16 127.0.0.1:57240 accepted tcp:127.0.0.1:0 [api]
2022/02/20 15:17:26 127.0.0.1:57242 accepted tcp:127.0.0.1:0 [api]
2022/02/20 15:17:36 127.0.0.1:57244 accepted tcp:127.0.0.1:0 [api]
2022/02/20 15:17:46 127.0.0.1:57246 accepted tcp:127.0.0.1:0 [api]**

Sometimes I will check my logs to see whether there are somethong suspicious,these useless log is annoying,
So maybe some developer can optimize log print.Thanks~

**Comment by yuhan6665** [comment]
You must have a script of some sort to call api every 10 seconds. Seems legit log print.
The access log doesn't have level, so the only way to turn it off is to remove access log.

**Comment by FranzKafkaYu** [comment]
OK,I got it.Thank you for your illustration.
