### ISSUE TITLE
存在DNS空解析的情况

### ISSUE THREAD

**Issue by zenyanbo** [XTLS/Xray-core#96]
从老版本以来，DNS就一直存在空解析的情况。服务端（有时候代理的域名无法解析）和客户端（v2rayng本地DNS，直连域名无法解析，无法被sniffing）。
日志中speedtest空解析
日志：https://paste.ubuntu.com/p/XYZd8wsXj5/
配置：https://paste.ubuntu.com/p/C3HSgqbRZn/
此问题测试与协议无关。应该就是内部DNS服务器出问题。

**Comment by badO1a5A90** [comment]
配置没有问题.
日志也正常(除偶发的DNS空解析).
靠这些似乎分析不出更多深入的可能性.

还有什么其他可以供参考或者复现的信息吗?

服务端有异常日志吗?
使用环境如何?
DOH是否发生过类似现象?

**Comment by zenyanbo** [comment]
> 配置没有问题.
> 日志也正常(除偶发的DNS空解析).
> 靠这些似乎分析不出更多深入的可能性.
> 
> 还有什么其他可以供参考或者复现的信息吗?
> 
> 服务端有异常日志吗?
> 使用环境如何?
> DOH是否发生过类似现象?

这种空解析的情况使得流量进入不了core，在服务端不可能有体现。当然有时候流量代理到服务端后，服务端也存在空解析的情况（比客户端罕见），比如油管，那种情况服务端是有日志的。但是太不好捕捉了。
DOH与普通UDP都有这个问题。
使用环境：v2rayng（设置了本地dns，第一次解析为空导致连接中断，流量无法进入core，现象：客户端空解析+服务端空解析）
                  clash（服务端空解析）

**Comment by badO1a5A90** [comment]
在服务端不可能有体现---指的是对这次DNS查询的日志(因为1111是被代理到服务端的)
看你的回复的意思是这次代理是成功的,也没有error?

**Comment by zenyanbo** [comment]
不，如果是客户端空解析，因为ng设置了本地代理，所以当APP第一次请求解析时，返回了空解析，所以连接中断，流量没有进入客户端的core。自然在服务端是没有体现的。

**Comment by rprx** [comment]
其实我一直觉得现在的代码中某些地方不协调，不过这个问题应该是偶发的解析失败？

**Comment by badO1a5A90** [comment]
也许和ng有关。
PC端似乎不会出现这种不应该的偶发空解析。

**Comment by badO1a5A90** [comment]
观察了PC上使用远程DOH解析的情况.
连续几天的日常使用环境, 50M+的日志, 只有19处 TypeA -> [], 并且都是因为域名真的无法解析有关(且有重复)
我觉得这不像是Xray内置DNS服务器的问题.

**Comment by zenyanbo** [comment]
自从取消了ng的本地dns，这问题就没遇到了，可是之前clash用很少时候也能遇到，最近也消失了。。我好迷啊，没找出啥关联。2021年1月13日 02:17，Arthur Morgan <notifications@github.com>写道：

观察了PC上使用远程DOH解析的情况.

连续几天的日常使用环境, 50M+的日志, 只有19处 TypeA -> [], 并且都是因为域名真的无法解析有关(且有重复)

我觉得这不像是Xray内置DNS服务器的问题.

**Comment by badO1a5A90** [comment]
建议可以先close,如果有问题再reopen
