### ISSUE TITLE
重新安装之后无法使用，请各位帮忙，谢谢！

### ISSUE THREAD

**Issue by gh2020gh** [XTLS/Xray-core#961]
之前xray一直可以正常使用，我设定了自动更新证书，但是不知道什么原因，acme.sh默认的zerossl服务器无法访问，导致无法更新。现在证书过期了，手动更新证书的时候也一直提示错误，我就把xray重新安装了一遍

我根据这篇文章的指示
https://github.com/acmesh-official/acme.sh/wiki/Change-default-CA-to-ZeroSSL
把默认证书服务器改回了letsencrypt，安装过程中没有错误提示。

安装之后，服务器端提示xray的状态是绿色的active (running) ，但是xray无法正常连接。ping服务器是通的，但是tcping超时。用v2rayN的测试服务器状态这一项测试的时候提示错误
failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp OOO: connectex: No connection could be made because the target machine actively refused it. dial tcp OOO: operation was canceled] > common/retry: all retry attempts failed

另外我已经确认证书文件和上层文件夹的权限都是755，且关闭了vps的防火墙。我使用了cloudflare解析我的域名，不知道有没有关系。

想要使用xray的时候，debug的提示基本上就是下面这两条

app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp OOO: connectex: No connection could be made because the target machine actively refused it.] > common/retry: all retry attempts failed

app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe

请问这可能是什么问题呢？我不是程序员，有可能的话请解释的浅显一点，非常感谢！

**Comment by gh2020gh** [comment]
补充一下，一旦重启服务器端的xray之后，active状态就变为failed了，

错误提示如下

Started Xray Service.
Xray 1.5.3 (Xray, Penetrates Everything.) Custom (go1.17.6 linux/amd64)
xray[6140]: A unified platform for anti-censorship.
xray[6140]: 2022/02/22 08:36:28 [Info] infra/conf/serial: Reading config: /usr/local/etc/xray/config
xray[6140]: Failed to start: main: failed to create server > app/log: failed to initialize access lo
systemd[1]: xray.service: Main process exited, code=exited, status=23/n/a
systemd[1]: xray.service: Failed with result 'exit-code'.
root:~# sudo systemctl status xray
● xray.service - Xray Service
   Loaded: loaded (/etc/systemd/system/xray.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/xray.service.d
           └─10-donot_touch_single_conf.conf
   Active: failed (Result: exit-code)
     Docs: https://github.com/xtls
  Process: 6140 ExecStart=/usr/local/bin/xray run -config /usr/local/etc/xray/config.json (code=exited, status=23)
 Main PID: 6140 (code=exited, status=23)

systemd[1]: Started Xray Service.
xray[6140]: Xray 1.5.3 (Xray, Penetrates Everything.) Custom (go1.17.6 linux/amd64)
xray[6140]: A unified platform for anti-censorship.
xray[6140]: [Info] infra/conf/serial: Reading config: /usr/local/etc/xray/config
xray[6140]: Failed to start: main: failed to create server > app/log: failed to initialize access lo
systemd[1]: xray.service: Main process exited, code=exited, status=23/n/a
systemd[1]: xray.service: Failed with result 'exit-code'.

希望能有人帮我解决这个问题，非常感谢！

**Comment by gh2020gh** [comment]
> failed to initialize access lo[gger] 无法创建 access.log 大概是权限问题 可以手动把以前的 log 删掉

非常感谢！权限的问题当时已经排除了。最后自己找办法解决了，方法是修改文件位置。

**Comment by singledog957** [comment]
> > failed to initialize access lo[gger] 无法创建 access.log 大概是权限问题 可以手动把以前的 log 删掉
> 
> 非常感谢！权限的问题当时已经排除了。最后自己找办法解决了，方法是修改文件位置。

请问可以详细说说吗，现在也碰到了一样的问题，谢谢

**Comment by hiiamboris** [comment]
I've had the following error:
```
app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination
connectex: No connection could be made because the target machine actively refused it.
```
on initial Xray setup in two circumstances:
1. extra comma in server's config -> it couldn't load it -> `systemctl status xray` showed me that config was faulty
2. `"alterId": 64` line being present on both client and server (as recommended by V2fly guide) -> removing this line everywhere fixed the issue
