### ISSUE TITLE
关于路由 RuleObject 中 port 与 sourcePort 的疑惑

### ISSUE THREAD

**Issue by benhon-han** [XTLS/Xray-core#962]
看到[官方文档](https://xtls.github.io/Xray-docs-next/en/config/routing.html#ruleobject)里有关于 RuleObject 的详解，但是端口这块儿还有些不甚理解，望解惑。

> port：number | string
> 目标端口范围，有三种形式：
> 
> "a-b"：a 和 b 均为正整数，且小于 65536。这个范围是一个前后闭合区间，当目标端口落在此范围内时，此规则生效。
> a：a 为正整数，且小于 65536。当目标端口为 a 时，此规则生效。
> 以上两种形式的混合，以逗号 "," 分隔。形如："53,443,1000-2000"。
> 
> sourcePort：number | string
> 
> 来源端口，有三种形式：
> 
> "a-b"：a 和 b 均为正整数，且小于 65536。这个范围是一个前后闭合区间，当目标端口落在此范围内时，此规则生效。
> a：a 为正整数，且小于 65536。当目标端口为 a 时，此规则生效。
> 以上两种形式的混合，以逗号 "," 分隔。形如："53,443,1000-2000"。

`port` 是指要终端用户需要访问的目标地址的端口，对的吧？（比如访问 http://www.google.com 的 80、https://www.google.com 的 443）
另外 `sourcePort` 到底是指终端用户的出栈端口，还是指中转服务器（Xray 客户端）的监听（入站）端口呢？这个不是很确定。

目前使用场景：
Xray 客户端部署在 LAN 中转服务器上，为每个入站端口配置不同的 tag（标识），并且路由策略也为每个入站 tag 指定不同的出站 tag，以实现 LAN 设备连接到中转服务器不同端口使用不同的（境外出口）线路的目的。

目前客户端配置：
```
{
  "inbounds": [
    {
      "port": 1080,
      "protocol": "socks",
      "tag": "2us"
    },
    {
      "port": 1081,
      "protocol": "socks",
      "tag": "2hk"
    },
    {
      "port": 1082,
      "protocol": "socks",
      "tag": "2sg"
    }
  ],
  "outbounds": [
    {
      "protocol": "vless",
      "tag": "us"
    },
    {
      "protocol": "vless",
      "tag": "hk"
    },
    {
      "protocol": "vless",
      "tag": "sg"
    }
  ],
  "routing": {
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "2us"
        ],
        "outboundTag": "us"
      },
      {
        "type": "field",
        "inboundTag": [
          "2hk"
        ],
        "outboundTag": "hk"
      },
      {
        "type": "field",
        "inboundTag": [
          "2sg"
        ],
        "outboundTag": "sg"
      }
    ]
  }
}
```

由于 Xray 客户端监听的端口众多，所以想“精简”一下配置。记得入站配置监听的端口是可以设定端口范围的，不过使用端口范围的话，路由策略里使用标识就不适用了。

设想精简后的客户端配置：
```
{
  "inbounds": [
    {
      "port": "1080-1082",
      "protocol": "socks",
      "allocate": {
        "strategy": "always"
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "vless",
      "tag": "us"
    },
    {
      "protocol": "vless",
      "tag": "hk"
    },
    {
      "protocol": "vless",
      "tag": "sg"
    }
  ],
  "routing": {
    "rules": [
      {
        "type": "field",
        "sourcePort": 1080,
        "outboundTag": "us"
      },
      {
        "type": "field",
        "sourcePort": 1081,
        "outboundTag": "hk"
      },
      {
        "type": "field",
        "sourcePort": 1082,
        "outboundTag": "sg"
      }
    ]
  }
}
```

**Comment by yuhan6665** [comment]
sourcePort 是指终端用户的出栈端口 用 inboundTag 是对的 目前没有更简便的路由写法

**Comment by benhon-han** [comment]
@yuhan6665 谢谢。
