### ISSUE TITLE
求助！用了一年的xray昨天开始不能正常使用！

### ISSUE THREAD

**Issue by bruce2k** [XTLS/Xray-core#964]
使用xray一年了，平常主要用来找资料觉得非常好用！从昨天开始无法正常使用。从浏览器直接输入我的域名可以正常访问，看了一下本地的error.log发现错误如下，服务器端的access.log（info级）没有任何记录，error.log也没有记录，求助大神帮忙看一下该如何处理！谢谢！！！
2022/02/23 16:26:33 [Warning] core: Xray 1.3.1 started
2022/02/23 16:27:34 [Warning] [357112320] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp xx.xxx.xxx.xxx:xxx: operation was canceled dial tcp: operation was canceled] > common/retry: all retry attempts failed
2022/02/23 16:27:34 [Warning] [928156897] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp xx.xxx.xxx.xxx:xxx: operation was canceled dial tcp: operation was canceled] > common/retry: all retry attempts failed

**Comment by yuhan6665** [comment]
how did you setup server side? Try turn on debug logging and check systemctl status on the server side.

**Comment by bruce2k** [comment]
thanks! @[yuhan6665]
follow your suggestion trun on the debug log, still nothing in access.log , just some start information in error.log. my server side config as below. 
{
    // 1_日志设置
    "log": {
        "loglevel": "debug",    // 内容从少到多: "none", "error", "warning", "info", "debug" 
        "access": "/xx/xx/xx/access.log",    // 访问记录
        "error": "/xx/xx/xx/error.log"    // 错误记录
    },

    // 2_DNS设置
    "dns": {
        "servers": [
            "https+local://1.1.1.1/dns-query",    // 首选1.1.1.1的DoH查询，牺牲速度但可防止ISP偷窥
            "localhost"
        ]
    },

    // 3_分流设置
    "routing": {
        "domainStrategy": "AsIs",
        "rules": [
            // 3.1 防止服务器本地流转问题：如内网被攻击或滥用、错误的本地回环等
            {
                "type": "field",
                "ip": [
                    "geoip:private"    // 分流条件：geoip文件内，名为"private"的规则（本地）
                ],
                "outboundTag": "block"    // 分流策略：交给出站"block"处理（黑洞屏蔽）
            },
            // 3.2 屏蔽广告
            {
                "type": "field",
                "domain": [
                    "geosite:category-ads-all"    // 分流条件：geosite文件内，名为"category-ads-all"的规则（各种广告域名）
                ],
                "outboundTag": "block"    // 分流策略：交给出站"block"处理（黑洞屏蔽）
            }
        ]
    },
   
    // 4_入站设置
    // 4.1 这里只写了一个最简单的vless+xtls的入站，因为这是Xray最强大的模式。如有其他需要，请根据模版自行添加。
    "inbounds": [
        {
            "port": xxx,
            "protocol": "vless",

            "settings": {
                "clients": [
                    {
                        "id": "xxxxxxx", // 填写你的 UUID
                        "flow": "xtls-rprx-direct",
                        "level": 0,
                        "email": "xx@xx.com"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": 8080 // 默认回落到防探测的代理
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "allowInsecure": false,    // 正常使用应确保关闭
                    "minVersion": "1.2",       // TLS最低版本设置
                    "alpn": [
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "/xx/xx/xx/xray.crt",
                            "keyFile": "/xx/xx/xx/xray.key"
                        }
                    ]
                }
            }
        }
    ],

    // 5_出站设置
    "outbounds": [
        // 5.1 第一个出站是默认规则，freedom就是对外直连（vps已经是外网，所以直连）
        {
            "tag": "direct",
            "protocol": "freedom"
        },
        // 5.2 屏蔽规则，blackhole协议就是把流量导入到黑洞里（屏蔽）
        {
            "tag": "block",
            "protocol": "blackhole"
        }
    ]
}

**Comment by bruce2k** [comment]
the server side error.log:

2022/02/24 02:18:05 [Debug] app/log: Logger started
2022/02/24 02:18:05 [Info] app/dns: DNS: created Local DOH client for https://1.1.1.1/dns-query
2022/02/24 02:18:05 [Info] app/dns: DNS: created localhost client
2022/02/24 02:18:05 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:xxxx
2022/02/24 02:18:05 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:xxxx
2022/02/24 02:18:05 [Warning] core: Xray 1.3.1 started

**Comment by yuhan6665** [comment]
Looks like you are using fallback. Is there any log when 从浏览器直接输入我的域名可以正常访问? You can also try add another inbound on different ports of your VPS and see if that works.

**Comment by bruce2k** [comment]
it's confuse me, i never change any configration, and it's works very well for 1 years, why the system will us fallback?

**Comment by chika0801** [comment]
> it's confuse me, i never change any configration, and it's works very well for 1 years, why the system will use fallback?
> 
> btw , use browser visit my website, still nothing in access.log and error.log. so sad.

你去用网站测一下你的端口是不是被封了。或者证书过期了。

**Comment by bruce2k** [comment]
我去vps上看了下貌似端口没有被封,证书我设了定时更新应该不会有问题

ubuntu:~$ sudo nc -zvw3 127.0.0.1 xxxx
Connection to 127.0.0.1 xxxx port [tcp/https] succeeded!

**Comment by chika0801** [comment]
> @chika0801 我去vps上看了下貌似端口没有被封,证书我设了定时更新应该不会有问题
> 
> ubuntu:~$ sudo nc -zvw3 127.0.0.1 xxxx Connection to 127.0.0.1 xxxx port [tcp/https] succeeded!

那帮不了你了。建议重装安VPS系统，重新搭一次好了。

**Comment by bruce2k** [comment]
@chika0801 好的，多谢！

**Comment by bruce2k** [comment]
@chika0801 今天做了下域名健康检测，确实是443端口被封了，只是我的vps设置是可用而已，咋整？

**Comment by bruce2k** [comment]
算了我重新搭环境吧

**Comment by chika0801** [comment]
> @chika0801 今天做了下域名健康检测，确实是443端口被封了，只是我的vps设置是可用而已，咋整？

https://github.com/chika0801/Xray-examples/tree/main/VLESS-TCP-XTLS
我用的配置 无非就是VPS配禁止访问CN 讨论的只开TLS1。3

剩下看脸。我几个VPS一年多有2年没被封443了。全网第一次大规模封443遭了后就加了禁止访问CN。

**Comment by chika0801** [comment]
你443封了直接改端口用就是，脸好几天443就回来了

**Comment by bruce2k** [comment]
@chika0801 抄作业失败了！我几乎照搬了你的配置！xray的版本是1.3.1
客户端：
{
    "log": {
        "loglevel": "warning",
        "access": "/xxx/access.log",    // 访问记录
        "error": "/xxx/error.log"    // 错误记录
    },
    "dns": {
        "servers": [
            "1.1.1.1"
        ]
    },
    "routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "type": "field",
                "ip": [
                    "1.1.1.1"
                ],
                "outboundTag": "proxy"
            },
            {
                "type": "field",
                "domain": [
                    "geosite:category-ads-all"
                ],
                "outboundTag": "block"
            },
            {
                "type": "field",
                "domain": [
                    "geosite:cn"
                ],
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "ip": [
                    "geoip:cn",
                    "geoip:private"
                ],
                "outboundTag": "direct"
            }
        ]
    },
    "inbounds": [
        {
            "listen": "127.0.0.1",
            "port": 1080,
            "protocol": "socks",
            "settings": {
                "udp": true
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            }
        },
        {
            "listen": "127.0.0.1",
            "port": 1081,
            "protocol": "http",
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "www.xxx.com",
                        "port": 443,
                        "users": [
                            {
                                "id": "xxx-xx-xx-xx-xx",
                                "encryption": "none",
                                "flow": "xtls-rprx-splice"
                                //"flow": "xtls-rprx-direct"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "serverName": "www.xxx.com",
                    "allowInsecure": false
                }
            },
            "tag": "proxy"
        },
        {
            "protocol": "freedom",
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "tag": "block"
        }
    ]
}
服务端：
{
    "log": {
        "loglevel": "warning",
        "access": "/xxx/access.log",    // 访问记录
        "error": "/xxx/error.log"    // 错误记录

    },
    "dns": {
        "servers": [
            "1.1.1.1"
        ]
    },
    "routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "type": "field",
                "ip": [
                    "1.1.1.1"
                ],
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "domain": [
                    "geosite:category-ads-all",
                    "geosite:cn"
                ],
                "outboundTag": "block"
            },
            {
                "type": "field",
                "ip": [
                    "geoip:cn",
                    "geoip:private"
                ],
                "outboundTag": "block"
            }
        ]
    },
    "inbounds": [
        {
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "xxx-xxx-xx-xxx-xx",
                        "flow": "xtls-rprx-direct"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "dest": "8001",
                        "xver": 1
                    },
                    {
                        "alpn": "h2",
                        "dest": "8002",
                        "xver": 1
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "rejectUnknownSni": true,
                    "minVersion": "1.3",
                    "certificates": [
                        {
                            "certificateFile": "/xx/xx/xx/xray.crt",
                            "keyFile": "/xx/xx/xx/xray.key"
                        }

                    ]
                }
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "tag": "block"
        }
    ]
}
nginx：
user www-data;
worker_processes auto;

error_log /xxx/xx/nginx/error.log notice;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}


http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '[$time_local] $proxy_protocol_addr:$proxy_protocol_port "$request" "$http_referer" "$http_user_agent"';
    #access_log /var/log/nginx/access.log main;

    sendfile on;
    keepalive_timeout 65;

    #server {
        #listen 80;
        #return 301 https://$host$request_uri;
    #}

    server {
        listen 127.0.0.1:8001 proxy_protocol;
        listen 127.0.0.1:8002 http2 proxy_protocol;
        set_real_ip_from 127.0.0.1;

        location / {
            root /xx/xx/xx/xx;
            index index.html;
        }

        error_page 500 502 503 504 /index.html;
        location = /index.html {
            root /xx/xx/xx/xx;
        }
    }
}

**Comment by bruce2k** [comment]
客户端的端口我改成8001了

客户端：
{
"log": {
"loglevel": "warning",
"access": "/xxx/access.log", // 访问记录
"error": "/xxx/error.log" // 错误记录
},
"dns": {
"servers": [
"1.1.1.1"
]
},
"routing": {
"domainStrategy": "IPIfNonMatch",
"rules": [
{
"type": "field",
"ip": [
"1.1.1.1"
],
"outboundTag": "proxy"
},
{
"type": "field",
"domain": [
"geosite:category-ads-all"
],
"outboundTag": "block"
},
{
"type": "field",
"domain": [
"geosite:cn"
],
"outboundTag": "direct"
},
{
"type": "field",
"ip": [
"geoip:cn",
"geoip:private"
],
"outboundTag": "direct"
}
]
},
"inbounds": [
{
"listen": "127.0.0.1",
"port": 1080,
"protocol": "socks",
"settings": {
"udp": true
},
"sniffing": {
"enabled": true,
"destOverride": [
"http",
"tls"
]
}
},
{
"listen": "127.0.0.1",
"port": 1081,
"protocol": "http",
"sniffing": {
"enabled": true,
"destOverride": [
"http",
"tls"
]
}
}
],
"outbounds": [
{
"protocol": "vless",
"settings": {
"vnext": [
{
"address": "www.xxx.com",
"port": 8001,
"users": [
{
"id": "xxx-xx-xx-xx-xx",
"encryption": "none",
"flow": "xtls-rprx-splice"
//"flow": "xtls-rprx-direct"
}
]
}
]
},
"streamSettings": {
"network": "tcp",
"security": "xtls",
"xtlsSettings": {
"serverName": "www.xxx.com",
"allowInsecure": false
}
},
"tag": "proxy"
},
{
"protocol": "freedom",
"tag": "direct"
},
{
"protocol": "blackhole",
"tag": "block"
}
]
}

**Comment by chika0801** [comment]
> @chika0801 抄作业失败了！我几乎照搬了你的配置！xray的版本是1.3.1 客户端： { "log": { "loglevel": "warning", "access": "/xxx/access.log", // 访问记录 "error": "/xxx/error.log" // 错误记录 }, "dns": { "servers": [ "1.1.1.1" ] }, "routing": { "domainStrategy": "IPIfNonMatch", "rules": [ { "type": "field", "ip": [ "1.1.1.1" ], "outboundTag": "proxy" }, { "type": "field", "domain": [ "geosite:category-ads-all" ], "outboundTag": "block" }, { "type": "field", "domain": [ "geosite:cn" ], "outboundTag": "direct" }, { "type": "field", "ip": [ "geoip:cn", "geoip:private" ], "outboundTag": "direct" } ] }, "inbounds": [ { "listen": "127.0.0.1", "port": 1080, "protocol": "socks", "settings": { "udp": true }, "sniffing": { "enabled": true, "destOverride": [ "http", "tls" ] } }, { "listen": "127.0.0.1", "port": 1081, "protocol": "http", "sniffing": { "enabled": true, "destOverride": [ "http", "tls" ] } } ], "outbounds": [ { "protocol": "vless", "settings": { "vnext": [ { "address": "www.xxx.com", "port": 443, "users": [ { "id": "xxx-xx-xx-xx-xx", "encryption": "none", "flow": "xtls-rprx-splice" //"flow": "xtls-rprx-direct" } ] } ] }, "streamSettings": { "network": "tcp", "security": "xtls", "xtlsSettings": { "serverName": "www.xxx.com", "allowInsecure": false } }, "tag": "proxy" }, { "protocol": "freedom", "tag": "direct" }, { "protocol": "blackhole", "tag": "block" } ] } 服务端： { "log": { "loglevel": "warning", "access": "/xxx/access.log", // 访问记录 "error": "/xxx/error.log" // 错误记录
> 
> ```
> },
> "dns": {
>     "servers": [
>         "1.1.1.1"
>     ]
> },
> "routing": {
>     "domainStrategy": "IPIfNonMatch",
>     "rules": [
>         {
>             "type": "field",
>             "ip": [
>                 "1.1.1.1"
>             ],
>             "outboundTag": "direct"
>         },
>         {
>             "type": "field",
>             "domain": [
>                 "geosite:category-ads-all",
>                 "geosite:cn"
>             ],
>             "outboundTag": "block"
>         },
>         {
>             "type": "field",
>             "ip": [
>                 "geoip:cn",
>                 "geoip:private"
>             ],
>             "outboundTag": "block"
>         }
>     ]
> },
> "inbounds": [
>     {
>         "port": 443,
>         "protocol": "vless",
>         "settings": {
>             "clients": [
>                 {
>                     "id": "xxx-xxx-xx-xxx-xx",
>                     "flow": "xtls-rprx-direct"
>                 }
>             ],
>             "decryption": "none",
>             "fallbacks": [
>                 {
>                     "dest": "8001",
>                     "xver": 1
>                 },
>                 {
>                     "alpn": "h2",
>                     "dest": "8002",
>                     "xver": 1
>                 }
>             ]
>         },
>         "streamSettings": {
>             "network": "tcp",
>             "security": "xtls",
>             "xtlsSettings": {
>                 "rejectUnknownSni": true,
>                 "minVersion": "1.3",
>                 "certificates": [
>                     {
>                         "certificateFile": "/xx/xx/xx/xray.crt",
>                         "keyFile": "/xx/xx/xx/xray.key"
>                     }
> 
>                 ]
>             }
>         },
>         "sniffing": {
>             "enabled": true,
>             "destOverride": [
>                 "http",
>                 "tls"
>             ]
>         }
>     }
> ],
> "outbounds": [
>     {
>         "protocol": "freedom",
>         "tag": "direct"
>     },
>     {
>         "protocol": "blackhole",
>         "tag": "block"
>     }
> ]
> ```
> 
> } nginx： user www-data; worker_processes auto;
> 
> error_log /xxx/xx/nginx/error.log notice; pid /run/nginx.pid;
> 
> events { worker_connections 1024; }
> 
> http { include /etc/nginx/mime.types; default_type application/octet-stream;
> 
> ```
> log_format main '[$time_local] $proxy_protocol_addr:$proxy_protocol_port "$request" "$http_referer" "$http_user_agent"';
> #access_log /var/log/nginx/access.log main;
> 
> sendfile on;
> keepalive_timeout 65;
> 
> #server {
>     #listen 80;
>     #return 301 https://$host$request_uri;
> #}
> 
> server {
>     listen 127.0.0.1:8001 proxy_protocol;
>     listen 127.0.0.1:8002 http2 proxy_protocol;
>     set_real_ip_from 127.0.0.1;
> 
>     location / {
>         root /xx/xx/xx/xx;
>         index index.html;
>     }
> 
>     error_page 500 502 503 504 /index.html;
>     location = /index.html {
>         root /xx/xx/xx/xx;
>     }
> }
> ```
> 
> }

你发这些我也帮不了你。你找台练手的VPS，按我那上面写的。。。从重装安系统开始搭。如果你有了SSL证书倒是可以跳过相应的。教程上我都写清楚了，剩下看你自己操作能力了。
