### ISSUE TITLE
高并发下的内存泄露问题

### ISSUE THREAD

**Issue by milozen** [XTLS/Xray-core#966]
服务器 2核4G
UBUNTU 20.04
面板 X-UI 版本 0.3.2
xray 版本 1.5.3
运行 trojan
TCP并发 12000 左右

运行8小时，938M
![d0a3e69f56b756ea0d27987b8fb0458](https://user-images.githubusercontent.com/50772707/155642872-08df0851-33e0-424c-b73f-6ca5d0a5c81e.png)

运行24小时，1.86G
![5248bb09e436cbd25f867331b58d5e6](https://user-images.githubusercontent.com/50772707/155642916-153d4a8a-e2a6-40df-b7bc-bccfe52b9698.png)

并发12000，bin/xray-linux-amd64 -c bin/config.json 文件句柄 128902
![image](https://user-images.githubusercontent.com/50772707/155643833-1235840b-7648-4eb4-87dd-6beb4657b028.png)

================
另外一台配置相同服务器
xray 版本 1.4.2
TCP并发1100-1300
5分钟， 199M
![967903d95a39b6a586d7568b0dc194b](https://user-images.githubusercontent.com/50772707/155643481-3a02b867-1266-4b05-b582-905c63cfdb9e.png)

23小时， 291M
![image](https://user-images.githubusercontent.com/50772707/155643546-782838ae-ed46-41ed-935f-e633d1faa9c3.png)

**Comment by milozen** [comment]
也怀疑可能和TCP优化不当有关，缺乏TCP优化知识，只是拷贝了以下网上高并发下的TCP配置文件：
ubuntu下解决高并发socket最大连接数限制，tcp默认1024个连接
https://blog.51cto.com/u_15127575/2903094


net.ipv4.ip_local_port_range = 1024 65535
net.core.rmem_max=16777216
net.core.wmem_max=16777216
net.ipv4.tcp_rmem=4096 87380 16777216
net.ipv4.tcp_wmem=4096 65536 16777216
net.ipv4.tcp_fin_timeout = 10
net.ipv4.tcp_timestamps = 0
net.ipv4.tcp_window_scaling = 0
net.ipv4.tcp_sack = 0
net.core.netdev_max_backlog = 30000
net.ipv4.tcp_no_metrics_save=1
net.core.somaxconn = 262144
net.ipv4.tcp_syncookies = 0
net.ipv4.tcp_max_orphans = 262144
net.ipv4.tcp_max_syn_backlog = 262144
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_syn_retries = 2
-----------------------------------
怀疑和以下配置不当有关系，文章中的配置可能是16G内存的服务器，但我服务器只有4G内存
net.core.rmem_max=16777216
net.core.wmem_max=16777216
net.ipv4.tcp_rmem=4096 87380 16777216
net.ipv4.tcp_wmem=4096 65536 16777216

**Comment by lflcan** [comment]
同遇到这个问题，但我把xray内核切回1.5.2版本就好了

**Comment by milozen** [comment]
> 同遇到这个问题，但我把xray内核切回1.5.2版本就好了

下午试试切1.5.2看看能不能解决，否则每天都得重启一次服务

**Comment by milozen** [comment]
> 同遇到这个问题，但我把xray内核切回1.5.2版本就好了

切到1.5.2还是有一样的情况，看来得做脚本自动重启服务了。

**Comment by DrWindays** [comment]
Out of memory: Killed process 32109 (xray) total-vm:815412kB, anon-rss:57404kB, file-rss:216kB, shmem-rss:0kB, UID:0 pgtables:84kB oom_score_adj:0
