### ISSUE TITLE
有用户名密码的HTTP代理在代理转发中不能连通

### ISSUE THREAD

**Issue by ak8099** [XTLS/Xray-core#968]
最后一个可以用的版本是 1.1.4 后面的更新就有这个问题了。v2ray也有同样的问题。
配置如下

{
	"inbounds": [

		{
			"tag": "in1080",
			"port": 1080,
			"listen": "192.168.2.66",
			"protocol": "http"
		}

	],
	"outbounds": [

		{
			"protocol": "blackhole"
		},

		{
			"tag": "bypass",
			"protocol": "shadowsocks",
			"settings": {
				"servers": [{
					"address": "xxx.bypass.com",
					"port": 8888,
					"password": "27735320-3ff1-49dc-b10c-8619e7c268b0",
					"method": "aes-256-gcm"
				}]
			}
		},

		{
			"tag": "out1080",
			"protocol": "http",
			"settings": {
				"servers": [{
					"address": "108.108.108.108",
					"port": 9999,
					"users": [{
						"user": "user",
						"pass": "1234"
					}]
				}]
			},
			"proxySettings": {
				"tag": "bypass"
			}
		}

	],
	"routing": {
		"rules": [

			{
				"type": "field",
				"inboundTag": ["in1080"],
				"outboundTag": "out1080"
			}

		]
	}
}

**Comment by benhon-han** [comment]
试试
```
{
    "inbounds": [
        {
            "port": 1080,
            "listen": "192.168.2.66",
            "protocol": "http",
            "tag": "in1080"
        }
    ],
    "outbounds": [
        {
            "protocol": "shadowsocks",
            "settings": {
                "servers": [
                    {
                        "address": "xxx.bypass.com",
                        "port": 8888,
                        "password": "27735320-3ff1-49dc-b10c-8619e7c268b0",
                        "method": "aes-256-gcm"
                    }
                ]
            },
            "tag": "bypass"
        },
        {
            "protocol": "http",
            "settings": {
                "servers": [
                    {
                        "address": "108.108.108.108",
                        "port": 9999,
                        "users": [
                            {
                                "user": "user",
                                "pass": "1234"
                            }
                        ]
                    }
                ]
            },
            "proxySettings": {
                "tag": "bypass",
                "transportLayer": true
            },
            "tag": "out1080"
        },
        {
            "protocol": "blackhole"
        }
    ],
    "routing": {
        "rules": [
            {
                "type": "field",
                "inboundTag": [
                    "in1080"
                ],
                "outboundTag": "out1080"
            }
        ]
    }
}
```

**Comment by ak8099** [comment]
参数没有起作用，跟之前是一样的反应。新版不能通，老版本1.1.4还是可以用。
我把日志传上来了。

[error.log](https://github.com/XTLS/Xray-core/files/8197663/error.log)

**Comment by LuisRain** [comment]
咋样 有同学解决了吗？
