### ISSUE TITLE
Vless TCP TLS 上传速度很慢

### ISSUE THREAD

**Issue by danerlt** [XTLS/Xray-core#97]
同一个服务器和客户端,用tarjan+TCP+TLS和vmess+TCP+TLS测试,100M的宽带上传速度都能达到50M左右,使用vless+TCP+tls测试速度下载速度能达到100M,上传速度一直在10M以内,.要怎么解决了?
![image](https://user-images.githubusercontent.com/14197717/102965555-04b6da00-4529-11eb-88f5-1f65c030a026.png)
服务器配置如下:
![image](https://user-images.githubusercontent.com/14197717/102965987-e7ced680-4529-11eb-821a-c05368bf647f.png)

**Comment by richardxyz** [comment]
观察到一样的情况，但是我认为这可能跟speedtest.net有关，使用speed.cloudflare.com和fast.com看看。

**Comment by badO1a5A90** [comment]
测试的时候speedtest.net的测速节点是同一个吗?
也许换一下测速节点会不一样?(可能是测速节点本身的限制)

**Comment by eMeab** [comment]
> 同一个服务器和客户端,用tarjan+TCP+TLS和vmess+TCP+TLS测试,100M的宽带上传速度都能达到50M左右,使用vless+TCP+tls测试速度下载速度能达到100M,上传速度一直在10M以内,.要怎么解决了?
> ![image](https://user-images.githubusercontent.com/14197717/102965555-04b6da00-4529-11eb-88f5-1f65c030a026.png)
> 服务器配置如下:
> ![image](https://user-images.githubusercontent.com/14197717/102965987-e7ced680-4529-11eb-821a-c05368bf647f.png)

服务器IP暴露了。

**Comment by Rakau** [comment]
完美错过正确打码的地方

**Comment by danerlt** [comment]
吓得我赶紧换一个
