### ISSUE TITLE
请问如何将json格式的配置写成 []*InboundHandlerConfig 形式？

### ISSUE THREAD

**Issue by gitv2ray** [XTLS/Xray-core#972]
如图:
![20220304084938](https://user-images.githubusercontent.com/71534870/156679284-6f070c98-ea1b-4793-93b8-ad138b987c59.png)

**Comment by yuhan6665** [comment]
https://github.com/XTLS/Xray-core/blob/cd93e10d581c322a745a7cb724ff1c889ef30cde/testing/scenarios/tls_test.go#L369-L394

**Comment by gitv2ray** [comment]
@yuhan6665 
感谢大佬回复，是我没把问题说清楚，现在重问一下如下图:
![20220305090625](https://user-images.githubusercontent.com/71534870/156861679-b01422b5-788c-41ec-82ed-dc9749edec1b.png)

**Comment by yuhan6665** [comment]
应该是直接填在 listen 里面吧 port 会被忽略

**Comment by gitv2ray** [comment]
@yuhan6665 
感谢，portlist 删掉，直接填 listen就可以了

` {
				ReceiverSettings: serial.ToTypedMessage(&proxyman.ReceiverConfig{
					Listen: net.NewIPOrDomain(net.ParseAddress("/etc/caddy/vmess")),
					StreamSettings: &internet.StreamConfig{
						ProtocolName: "websocket",
						TransportSettings: []*internet.TransportConfig{
							{
								ProtocolName: "websocket",
								Settings: serial.ToTypedMessage(&websocket.Config{
									Path: "/ccc",
								}),
							},
						},
					},
				}),
				ProxySettings: serial.ToTypedMessage(&inbound.Config{
					User: []*protocol.User{
						{
							Level: 0,
							Email: "",
							Account: serial.ToTypedMessage(&vmess.Account{
								Id:      "d45a79b4-6094-41cf-923d-42731e7ecf3e",
								AlterId: 0,
							}),
						},
					},
					SecureEncryptionOnly: false,
				}),
			},`
