### ISSUE TITLE
What are recommended client software for intel-based macOS?

### ISSUE THREAD

**Issue by Tualua** [XTLS/Xray-core#974]
Qv2Ray seems abandoned.

Any alternative that uses xray-core?

**Comment by benhon-han** [comment]
I'm using V2rayU on Intel-based MacBook and it works just fine, you can try it.

https://github.com/yanue/V2rayU

**Comment by hujesse83** [comment]
v2rayU

**Comment by ben-august** [comment]
clashx pro

**Comment by bash99** [comment]
I use clash.meta with web dashboard, same config for linux / windows

**Comment by yuhan6665** [comment]
先关了
