### ISSUE TITLE
xray api problem

### ISSUE THREAD

**Issue by Tualua** [XTLS/Xray-core#977]
Hello! I setup api according to documentation, but when I try to get stats I get error 

    failed to dial 127.0.0.1:8080

I tried to change port to 8080 but still got the same error

**Comment by FranzKafkaYu** [comment]
Hi,you should ensure the api port is  same as you set in config.json,which is a dokodemo-door port.
and the command usage like this :
xray api  stats --name="inbound>>>api>>>traffic>>>downlink"  --server=127.0.0.1:port 
the port is the dokodemo-door port.
Hope this will help you.

**Comment by FranzKafkaYu** [comment]
> Hello! I setup api according to documentation, but when I try to get stats I get error
> 
> ```
> failed to dial 127.0.0.1:8080
> ```
> 
> I tried to change port to 8080 but still got the same error

Hi,you should ensure the api port is same as you set in config.json,which is a dokodemo-door port.
and the command usage like this :
xray api stats --name="inbound>>>api>>>traffic>>>downlink" --server=127.0.0.1:port
the port is the dokodemo-door port.
Hope this will help you.

**Comment by lxhao61** [comment]
怎么实现Xray的流量统计，即怎么配置traffic.sh脚本。参考(V2ray的流量统计的流量信息的处理)[https://guide.v2fly.org/advanced/traffic.html#%E6%B5%81%E9%87%8F%E4%BF%A1%E6%81%AF%E7%9A%84%E5%A4%84%E7%90%86]。

**Comment by FranzKafkaYu** [comment]
> 怎么实现Xray的流量统计，即怎么配置traffic.sh脚本？希望实现类似[V2ray的流量统计](https://guide.v2fly.org/advanced/traffic.html)。

有提供api进行获取，使用脚本获取后进行累加，单位转换就可以了

**Comment by ben-august** [comment]
> > > 怎么实现Xray的流量统计，即怎么配置traffic.sh脚本？希望实现类似[V2ray的流量统计](https://guide.v2fly.org/advanced/traffic.html)。
> > 
> > 
> > 有提供api进行获取，使用脚本获取后进行累加，单位转换就可以了
> 
> 望具体告知V2ray的traffic.sh脚本（见如下）怎么修改。太笨，一直不成功。
> 
> #!/bin/bash
> 
> _APISERVER=127.0.0.1:10085 _V2CTL=/usr/local/bin/v2ctl
> 
> apidata () { local ARGS= if [[ $1 == "reset" ]]; then ARGS="reset: true" fi $_V2CTL api --server=$_APISERVER StatsService.QueryStats "${ARGS}" | awk '{ if (match($1, /name:/)) { f=1; gsub(/^"|link"$/, "", $2); split($2, p, ">>>"); printf "%s:%s->%s\t", p[1],p[2],p[4]; } else if (match($1, /value:/) && f){ f = 0; printf "%.0f\n", $2; } else if (match($0, /^>$/) && f) { f = 0; print 0; } }' }
> 
> print_sum() { local DATA="$1" local PREFIX="$2" local SORTED=$(echo "$DATA" | grep "^${PREFIX}" | sort -r) local SUM=$(echo "$SORTED" | awk ' /->up/{us+=$2} /->down/{ds+=$2} END{ printf "SUM->up:\t%.0f\nSUM->down:\t%.0f\nSUM->TOTAL:\t%.0f\n", us, ds, us+ds; }') echo -e "${SORTED}\n${SUM}" | numfmt --field=2 --suffix=B --to=iec | column -t }
> 
> DATA=$(apidata $1) echo "------------Inbound----------" print_sum "$DATA" "inbound" echo "-----------------------------" echo "------------Outbound----------" print_sum "$DATA" "outbound" echo "-----------------------------" echo echo "-------------User------------" print_sum "$DATA" "user" echo "-----------------------------"

``
#!/bin/bash

_APISERVER=127.0.0.1:10085
_V2CTL=/usr/local/bin/xray

apidata () {
    local ARGS=
    if [[ $1 == "reset" ]]; then
      ARGS="reset: true"
    fi
    $_V2CTL api statsquery --server=$_APISERVER "${ARGS}" \
    | awk '{
        if (match($1, /"name":/)) {
            f=1; gsub(/^"|link"|,$/, "", $2);
            split($2, p,  ">>>");
            printf "%s:%s->%s\t", p[1],p[2],p[4];
        }
        else if (match($1, /"value":/) && f){ f = 0; printf "%.0f\n", $2; }
        else if (match($0, /}/) && f) { f = 0; print 0; }
    }'
}

print_sum() {
    local DATA="$1"
    local PREFIX="$2"
    local SORTED=$(echo "$DATA" | grep "^${PREFIX}" | sort -r)
    local SUM=$(echo "$SORTED" | awk '
        /->up/{us+=$2}
        /->down/{ds+=$2}
        END{
            printf "SUM->up:\t%.0f\nSUM->down:\t%.0f\nSUM->TOTAL:\t%.0f\n", us, ds, us+ds;
        }')
    echo -e "${SORTED}\n${SUM}" \
    | numfmt --field=2 --suffix=B --to=iec \
    | column -t
}

DATA=$(apidata $1)
echo "------------Inbound----------"
print_sum "$DATA" "inbound"
echo "-----------------------------"
echo "------------Outbound----------"
print_sum "$DATA" "outbound"
echo "-----------------------------"
echo
echo "-------------User------------"
print_sum "$DATA" "user"
echo "-----------------------------"
``

**Comment by lxhao61** [comment]
> > > > 怎么实现Xray的流量统计，即怎么配置traffic.sh脚本？希望实现类似[V2ray的流量统计](https://guide.v2fly.org/advanced/traffic.html)。
> > > 
> > > 
> > > 有提供api进行获取，使用脚本获取后进行累加，单位转换就可以了
> > 
> > 
> > 望具体告知V2ray的traffic.sh脚本（见如下）怎么修改。太笨，一直不成功。
> > #!/bin/bash
> > _APISERVER=127.0.0.1:10085 _V2CTL=/usr/local/bin/v2ctl
> > apidata () { local ARGS= if [[ $1 == "reset" ]]; then ARGS="reset: true" fi $_V2CTL api --server=$_APISERVER StatsService.QueryStats "${ARGS}" | awk '{ if (match($1, /name:/)) { f=1; gsub(/^"|link"$/, "", $2); split($2, p, ">>>"); printf "%s:%s->%s\t", p[1],p[2],p[4]; } else if (match($1, /value:/) && f){ f = 0; printf "%.0f\n", $2; } else if (match($0, /^>$/) && f) { f = 0; print 0; } }' }
> > print_sum() { local DATA="$1" local PREFIX="$2" local SORTED=$(echo "$DATA" | grep "^${PREFIX}" | sort -r) local SUM=$(echo "$SORTED" | awk ' /->up/{us+=$2} /->down/{ds+=$2} END{ printf "SUM->up:\t%.0f\nSUM->down:\t%.0f\nSUM->TOTAL:\t%.0f\n", us, ds, us+ds; }') echo -e "${SORTED}\n${SUM}" | numfmt --field=2 --suffix=B --to=iec | column -t }
> > DATA=$(apidata $1) echo "------------Inbound----------" print_sum "$DATA" "inbound" echo "-----------------------------" echo "------------Outbound----------" print_sum "$DATA" "outbound" echo "-----------------------------" echo echo "-------------User------------" print_sum "$DATA" "user" echo "-----------------------------"
> 
> ```
> #!/bin/bash
> 
> _APISERVER=127.0.0.1:10085
> _V2CTL=/usr/local/bin/xray
> 
> apidata () {
>     local ARGS=
>     if [[ $1 == "reset" ]]; then
>       ARGS="reset: true"
>     fi
>     $_V2CTL api statsquery --server=$_APISERVER "${ARGS}" \
>     | awk '{
>         if (match($1, /"name":/)) {
>             f=1; gsub(/^"|link"|,$/, "", $2);
>             split($2, p,  ">>>");
>             printf "%s:%s->%s\t", p[1],p[2],p[4];
>         }
>         else if (match($1, /"value":/) && f){ f = 0; printf "%.0f\n", $2; }
>         else if (match($0, /}/) && f) { f = 0; print 0; }
>     }'
> }
> 
> print_sum() {
>     local DATA="$1"
>     local PREFIX="$2"
>     local SORTED=$(echo "$DATA" | grep "^${PREFIX}" | sort -r)
>     local SUM=$(echo "$SORTED" | awk '
>         /->up/{us+=$2}
>         /->down/{ds+=$2}
>         END{
>             printf "SUM->up:\t%.0f\nSUM->down:\t%.0f\nSUM->TOTAL:\t%.0f\n", us, ds, us+ds;
>         }')
>     echo -e "${SORTED}\n${SUM}" \
>     | numfmt --field=2 --suffix=B --to=iec \
>     | column -t
> }
> 
> DATA=$(apidata $1)
> echo "------------Inbound----------"
> print_sum "$DATA" "inbound"
> echo "-----------------------------"
> echo "------------Outbound----------"
> print_sum "$DATA" "outbound"
> echo "-----------------------------"
> echo
> echo "-------------User------------"
> print_sum "$DATA" "user"
> echo "-----------------------------"
> ```

感谢告知，谢谢！
总算搞定，也知道我为什么一直不成功了：statsquery要放在--server之前，延续v2ctl api命令顺序了。

**Comment by yuhan6665** [comment]
感谢大家 我调整了一下脚本 适配最新的 1.5.9
已更新文档 https://xtls.github.io/document/level-2/traffic_stats.html
